# Trabajo Práctico Integrador - Introducción al Análisis de Datos

**Caso:** análisis y predicción de cancelaciones en reservas hoteleras.

## 1. Presentación breve del problema

Una empresa hotelera desea estudiar el comportamiento de sus reservas para identificar patrones asociados a la cancelación de estadías. Para ello, dispone de información sobre reservas realizadas en dos tipos de establecimientos: hoteles urbanos y hoteles tipo resort.

El dataset incluye información sobre fechas de llegada, duración de la estadía, cantidad de huéspedes, canal de reserva, tipo de cliente, historial de cancelaciones, tarifa promedio por noche y estado final de la reserva.

**Variable objetivo:** `is_canceled`

- `0`: reserva no cancelada.
- `1`: reserva cancelada.

### 1.1 Preguntas orientadoras

- ¿Qué situación vinculada con las reservas quiere comprender la empresa hotelera?
- ¿Por qué puede ser importante conocer y anticipar las cancelaciones?
- ¿Qué representa la variable is_canceled dentro del problema de análisis?
- ¿Qué factores podrían estar relacionados con la cancelación de una reserva?
- ¿Qué preguntas podrían responderse cuando se comience a explorar el dataset?
- ¿Qué decisiones podría tomar un hotel a partir de una mejor comprensión de las cancelaciones?

### 1.2 Relación entre dato, información y conocimiento
- Dato: es la materia prima del analisis. Enetenderemos a un dato como un valor, una caracteristica o hecho asociado al fenomenno que se esta estudiando. Los datos, por si solos, no siempre tiene un significado claro y muchas veces aparcecen como valores aislados.
- Informacion: surge cunado los datos son organizados, procesados e interpretados de manera que adquieren significado.
- Conocimiento: aparece cuando la informacion se interpreta dentro un contexto y permite comprender mejor una situacion, explicar un fenomeno o tomar una decision fundamentada. Es la comprension que permite actuar con mayor fundamento.

### 1.3 Ciclo de vida del Analisis de datos
Es una secuencaia iterativa e interactiva de etapas. Iterativa porque el resultado de una etapa puede obligar a volver a pasos anteriores para mejorar la calidad del concimiento extraido, y es interactiva porque el analista participa activamente de todo el proceso.
<p>Se distinguen 6 etapas:
<p>- 1. Definición del problema: Todo análisis comienza con un problema a resolver, el cual puede ser un inconveniente, una pregunta específica o una necesidad del negocio. Todo el trabajo empieza una vez que se sabe a dónde se quiere llegar.
<p>- 2. Recolección de datos: Consiste en identificar y obtener el material de trabajo desde diversas fuentes de datos. Estas fuentes pueden ser bases de datos (consultas SQL), Data Warehouses, archivos de acceso público en la web o fuentes de empresas externas.
<p>- 3. Limpieza y preparación: Es considerada una etapa crítica, ya que busca garantizar que los datos estén en un estado apto para ser estudiados; si los datos están "sucios", los resultados serán de mala calidad. Incluye actividades como la integración de datos, el tratamiento de valores faltantes (nulos), la corrección de inconsistencias y la detección de valores atípicos.
<p>- 4. Análisis Exploratorio de Datos (EDA): En este paso se exploran los datos para resumirlos estadísticamente y se aplican técnicas de visualización para observar posibles patrones. También sirve para identificar anomalías, detectar problemas de calidad provenientes del paso anterior y plantear hipótesis preliminares.
<p>- 5. Modelado y evaluación: Los datos ya preparados se procesan utilizando algoritmos matemáticos (Aprendizaje Automático o Machine Learning, ya sea supervisado o no supervisado) para encontrar tendencias, patrones ocultos o predecir variables. Luego, estos modelos deben ser validados y evaluados correctamente para asegurar su calidad y efectividad.
<p>- 6. Comunicación y despliegue: Una vez completado el análisis, se elabora un informe final, gráficos o dashboards para comunicar el conocimiento descubierto a los interesados, a menudo apoyándose en el storytelling. Además, si se generaron modelos predictivos, estos pueden comenzar a utilizarse sobre nuevos datos (despliegue), requiriendo un monitoreo a largo plazo para validar que los patrones sigan siendo

##2. Datos de identificación

- **Apellido y nombre:** Rodriguez Joaquin , Pichulman Miguel
- **Comisión:** 12
- **Dataset asignado:** DATASET L
- **Entrega:** 1
- **Fecha:**

##3.1 Importación de librerías

In [2]:
# Librerías básicas
import pandas as pd

## 3.2 Carga del dataset

Cargar del archivo CSV correspondiente a la comisión numero 12, Dataset L.

In [3]:
from io import StringIO
from pathlib import Path

contenido_csv = """booking_id,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,arrival_date,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests
HB-050638,City Hotel,1,302,2024,May,18,5,2024-05-05,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-042358,City Hotel,1,65,2023,September,36,5,2023-09-05,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-113042,City Hotel,0,32,2025,May,22,30,2025-05-30,0,2,2,0.0,0,SC,ISR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,2
HB-020264,Resort Hotel,0,3,2024,February,8,25,2024-02-25,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,1,0,1,A,D,0,No Deposit,240.0,,0,Transient,43.0,1,2
HB-017627,Resort Hotel,0,5,2023,October,41,10,2023-10-10,2,6,2,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,36.0,,0,Transient,42.0,0,0
HB-004628,Resort Hotel,1,36,2024,March,12,24,2024-03-24,1,3,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,108.75,0,1
HB-035771,Resort Hotel,0,2,2025,April,18,29,2025-04-29,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,122.0,0,2
HB-049486,City Hotel,1,126,2024,April,15,14,2024-04-14,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,39,Transient,57.5,0,0
HB-067110,City Hotel,1,186,2025,April,18,28,2025-04-28,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.5,0,1
HB-082532,City Hotel,0,72,2023,December,52,27,2023-12-27,2,4,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,128.22,0,2
HB-065066,City Hotel,1,74,2025,March,12,23,2025-03-23,1,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,100.3,0,0
HB-086866,City Hotel,0,4,2024,April,15,9,2024-04-09,0,1,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,211.0,0,2
HB-072546,City Hotel,1,242,2025,July,31,30,2025-07-30,2,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,112.5,0,0
HB-087103,City Hotel,0,40,2024,April,15,11,2024-04-11,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,105.3,0,1
HB-048605,City Hotel,1,161,2024,March,13,25,2024-03-25,1,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,101,Transient,130.0,0,0
HB-105937,City Hotel,0,41,2025,February,7,13,2025-02-13,1,4,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,115.6,0,3
HB-099736,City Hotel,0,3,2024,October,40,2,2024-10-02,4,10,1,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,A,3,No Deposit,,45.0,0,Transient,0.0,0,0
HB-116099,City Hotel,0,414,2025,July,28,13,2025-07-13,0,2,1,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,95.5,0,0
HB-018325,Resort Hotel,0,82,2024,February,6,7,2024-02-07,2,0,2,0.0,0,Undefined,PRT,Groups,TA/TO,1,0,0,A,A,0,No Deposit,67.0,,0,Transient-Party,72.0,0,0
HB-060224,City Hotel,1,626,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-007784,Resort Hotel,1,74,2024,August,35,26,2024-08-26,2,3,3,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,262.0,0,0
HB-112024,City Hotel,0,26,2025,May,20,17,2025-05-17,0,2,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,474.0,,0,Transient-Party,130.0,0,0
HB-046737,City Hotel,0,28,2024,January,3,18,2024-01-18,1,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,76.69,0,0
HB-015731,Resort Hotel,0,67,2023,July,31,31,2023-07-31,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,241.0,,0,Transient,88.55,0,1
HB-046907,City Hotel,1,4,2024,January,4,25,2024-01-25,3,5,1,0.0,0,BB,AGO,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,64.08,0,1
HB-065180,City Hotel,1,170,2025,March,13,26,2025-03-26,2,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,96.9,0,0
HB-026221,Resort Hotel,0,61,2024,July,30,22,2024-07-22,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,172.0,1,0
HB-039089,Resort Hotel,0,1,2025,August,32,5,2025-08-05,1,1,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,299.0,0,0
HB-044037,City Hotel,1,92,2023,September,39,30,2023-09-30,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-059064,City Hotel,1,91,2024,October,42,20,2024-10-20,2,4,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,127.65,0,1
HB-112859,City Hotel,0,21,2025,May,20,18,2025-05-18,3,8,1,0.0,0,BB,AUS,Aviation,Corporate,0,0,0,D,D,0,No Deposit,,153.0,0,Transient,110.0,0,0
HB-012712,Resort Hotel,1,145,2025,July,28,13,2025-07-13,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,199.0,0,1
HB-041223,City Hotel,0,39,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-046645,City Hotel,1,9,2024,January,2,14,2024-01-14,0,2,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,67.5,0,0
HB-070519,City Hotel,1,150,2025,June,25,17,2025-06-17,2,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,120.0,0,0
HB-054720,City Hotel,1,158,2024,July,30,24,2024-07-24,2,2,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.25,0,0
HB-057162,City Hotel,1,141,2024,September,38,19,2024-09-19,2,5,1,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.8,0,1
HB-104692,City Hotel,0,52,2025,January,3,18,2025-01-18,0,3,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,86.4,0,1
HB-025390,Resort Hotel,0,8,2024,June,25,23,2024-06-23,0,2,2,3.0,0,BB,USA,Direct,Direct,0,0,0,H,H,0,No Deposit,250.0,,0,Transient,186.0,1,0
HB-052175,City Hotel,1,21,2024,June,22,1,2024-06-01,0,2,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,157.0,0,0
HB-063342,City Hotel,1,580,2025,February,6,9,2025-02-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-024908,Resort Hotel,0,38,2024,June,23,4,2024-06-04,2,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,121.4,0,1
HB-091154,City Hotel,0,243,2024,June,24,14,2024-06-14,0,3,2,0.0,0,BB,NLD,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,106.2,0,0
HB-061160,City Hotel,1,75,2024,December,49,2,2024-12-02,2,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,1
HB-033768,Resort Hotel,0,1,2025,March,9,2,2025-03-02,0,1,1,0.0,0,BB,DEU,Direct,Direct,0,0,0,D,D,1,No Deposit,,,0,Transient-Party,68.0,0,0
HB-002060,Resort Hotel,0,61,2023,September,39,29,2023-09-29,2,10,2,0.0,0,HB,BLR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,80.1,0,2
HB-070921,City Hotel,1,210,2025,June,26,25,2025-06-25,1,0,2,2.0,0,BB,ZAF,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,189.0,0,0
HB-083673,City Hotel,0,12,2024,February,6,6,2024-02-06,2,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,15.0,,0,Transient,55.72,0,0
HB-035070,Resort Hotel,0,49,2025,April,15,9,2025-04-09,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,57.0,0,1
HB-081902,City Hotel,1,181,2024,May,18,5,2024-05-05,2,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,26.0,,42,Transient,90.0,0,0
HB-004287,Resort Hotel,1,33,2024,March,9,1,2024-03-01,2,6,1,0.0,0,HB,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,50.0,0,0
HB-063918,City Hotel,1,134,2025,February,9,25,2025-02-25,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,75.0,0,0
HB-092935,City Hotel,0,239,2024,July,28,12,2024-07-12,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,107.0,0,1
HB-054499,City Hotel,1,58,2024,July,29,18,2024-07-18,1,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.5,0,0
HB-027377,Resort Hotel,0,185,2024,August,34,21,2024-08-21,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Contract,116.1,0,0
HB-064952,City Hotel,1,56,2025,March,12,21,2025-03-21,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,86.0,,0,Transient,85.0,0,0
HB-117438,City Hotel,0,331,2025,August,31,2,2025-08-02,0,2,2,2.0,0,BB,NLD,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,179.1,0,2
HB-021075,Resort Hotel,0,27,2024,February,7,14,2024-02-14,2,2,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,G,G,1,No Deposit,240.0,,0,Transient,90.0,1,0
HB-072872,City Hotel,1,275,2025,August,32,8,2025-08-08,0,4,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,2
HB-117349,City Hotel,0,208,2025,August,31,2,2025-08-02,0,1,2,0.0,0,HB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,157.0,0,1
HB-001624,Resort Hotel,1,60,2023,September,36,6,2023-09-06,2,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,146.0,0,0
HB-087598,City Hotel,0,6,2024,April,16,20,2024-04-20,0,2,1,0.0,0,BB,PRT,Aviation,Corporate,0,0,0,A,A,1,No Deposit,,153.0,0,Transient,95.0,0,0
HB-086457,City Hotel,0,58,2024,March,13,31,2024-03-31,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,90.9,0,1
HB-060720,City Hotel,1,128,2024,November,47,19,2024-11-19,1,1,2,0.0,0,BB,SVN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.0,0,0
HB-003226,Resort Hotel,0,40,2023,November,47,21,2023-11-21,0,1,3,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,E,2,No Deposit,,,0,Transient,67.5,0,2
HB-004844,Resort Hotel,0,171,2024,April,14,4,2024-04-04,1,1,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,Non Refund,298.0,,0,Transient-Party,85.0,0,0
HB-073813,City Hotel,1,286,2023,July,30,30,2023-07-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-041427,City Hotel,1,131,2023,August,33,15,2023-08-15,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-067546,City Hotel,1,143,2025,May,18,4,2025-05-04,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,151.0,,0,Transient,100.0,0,0
HB-018603,Resort Hotel,1,108,2024,March,9,1,2024-03-01,0,1,2,2.0,0,BB,PRT,Online TA,TA/TO,0,1,0,G,G,0,No Deposit,240.0,,0,Transient,98.0,0,2
HB-078874,City Hotel,0,36,2023,October,42,17,2023-10-17,0,1,1,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,102.6,0,2
HB-076005,City Hotel,1,336,2023,September,38,18,2023-09-18,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-083281,City Hotel,0,15,2024,January,4,24,2024-01-24,2,1,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,68.99,0,1
HB-112798,City Hotel,0,51,2025,May,22,26,2025-05-26,1,2,2,0.0,0,SC,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,1
HB-069141,City Hotel,1,236,2025,May,22,26,2025-05-26,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,1
HB-002763,Resort Hotel,0,11,2023,October,44,30,2023-10-30,1,2,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient,45.66,0,1
HB-098185,City Hotel,0,30,2024,September,39,24,2024-09-24,1,1,2,0.0,0,BB,ZAF,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,9.0,,0,Transient,143.55,0,0
HB-082778,City Hotel,1,68,2024,February,7,17,2024-02-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,37.0,,0,Transient,75.0,0,0
HB-069859,City Hotel,1,181,2025,June,23,8,2025-06-08,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,0,Transient,100.0,0,0
HB-116056,City Hotel,0,248,2025,July,28,11,2025-07-11,0,4,2,0.0,0,BB,DNK,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,89.1,0,1
HB-024861,Resort Hotel,0,8,2024,June,23,4,2024-06-04,1,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,C,0,No Deposit,,,0,Transient,109.0,0,0
HB-007458,Resort Hotel,0,278,2024,August,32,10,2024-08-10,1,4,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,159.5,0,1
HB-008303,Resort Hotel,1,164,2024,September,38,21,2024-09-21,2,7,1,0.0,0,BB,IRL,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,123.1,0,0
HB-024511,Resort Hotel,0,47,2024,May,21,21,2024-05-21,2,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient-Party,106.33,1,1
HB-025997,Resort Hotel,0,126,2024,July,28,8,2024-07-08,3,7,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,149.2,0,1
HB-069725,City Hotel,1,31,2025,June,23,4,2025-06-04,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,158.0,0,0
HB-046793,City Hotel,1,12,2024,January,3,19,2024-01-19,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,19.0,,0,Transient-Party,72.0,0,0
HB-073618,City Hotel,1,368,2025,August,35,28,2025-08-28,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,28.0,,0,Transient,80.1,0,0
HB-103181,City Hotel,0,217,2024,December,49,5,2024-12-05,3,7,1,1.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,7.0,,0,Transient,65.11,0,2
HB-037777,Resort Hotel,0,45,2025,June,26,23,2025-06-23,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,531.0,,0,Transient,144.4,0,2
HB-071680,City Hotel,1,47,2025,July,28,10,2025-07-10,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,52.0,,0,Transient,80.1,0,1
HB-043431,City Hotel,1,74,2023,September,38,18,2023-09-18,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-083213,City Hotel,0,11,2024,January,4,23,2024-01-23,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,87.0,0,0
HB-004359,Resort Hotel,1,30,2024,March,10,7,2024-03-07,1,5,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,38.0,,0,Transient-Party,68.4,0,0
HB-075640,City Hotel,1,281,2023,July,30,25,2023-07-25,2,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,60.0,0,0
HB-007080,Resort Hotel,1,29,2024,July,29,20,2024-07-20,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,331.0,0,Transient,115.0,0,0
HB-071646,City Hotel,1,95,2025,July,28,9,2025-07-09,2,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,190.0,0,2
HB-100535,City Hotel,0,157,2024,October,43,22,2024-10-22,2,5,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,102.86,0,2
HB-083308,City Hotel,0,0,2024,January,4,24,2024-01-24,2,2,2,0.0,1,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,2,No Deposit,83.0,,0,Transient,68.4,0,1
HB-084280,City Hotel,0,19,2024,February,8,19,2024-02-19,1,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.0,0,1
HB-002602,Resort Hotel,0,93,2023,October,43,23,2023-10-23,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,34.65,0,1
HB-076799,City Hotel,0,192,2023,August,31,6,2023-08-06,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,76.5,0,2
HB-032836,Resort Hotel,1,20,2025,February,6,7,2025-02-07,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,45.0,0,1
HB-061144,City Hotel,1,60,2024,December,49,2,2024-12-02,2,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,74.8,0,0
HB-017063,Resort Hotel,0,185,2023,September,38,21,2023-09-21,1,1,2,0.0,0,HB,FRA,Groups,TA/TO,0,0,0,A,C,0,No Deposit,208.0,,0,Transient-Party,90.0,0,0
HB-001358,Resort Hotel,1,2,2023,August,34,26,2023-08-26,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,110.0,0,Transient,137.7,0,0
HB-019169,Resort Hotel,0,27,2023,December,49,7,2023-12-07,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,240.0,,0,Transient,46.2,0,1
HB-114381,City Hotel,0,129,2025,June,25,17,2025-06-17,2,2,2,0.0,0,SC,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,0
HB-063477,City Hotel,1,67,2025,February,7,12,2025-02-12,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,80.0,0,0
HB-084084,City Hotel,0,5,2024,February,7,16,2024-02-16,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,91.0,0,0
HB-015288,Resort Hotel,0,2,2024,February,5,4,2024-02-04,2,3,1,0.0,0,BB,PRT,Direct,Direct,1,0,1,A,D,1,No Deposit,,,0,Transient-Party,43.8,1,0
HB-073124,City Hotel,1,11,2025,August,33,15,2025-08-15,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,12.0,0,0
HB-072492,City Hotel,1,490,2025,July,31,29,2025-07-29,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-093808,City Hotel,0,37,2024,July,30,26,2024-07-26,0,1,3,1.0,0,BB,PRT,Direct,Direct,0,0,0,E,F,0,No Deposit,14.0,,0,Transient,188.95,0,1
HB-014862,Resort Hotel,1,207,2023,September,39,26,2023-09-26,1,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,1,1,0,A,A,0,No Deposit,208.0,,0,Transient,34.0,0,0
HB-101120,City Hotel,0,53,2024,November,45,4,2024-11-04,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,1
HB-020546,Resort Hotel,0,6,2024,February,5,2,2024-02-02,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,1,No Deposit,,94.0,0,Transient,27.0,0,0
HB-075414,City Hotel,1,323,2023,September,36,5,2023-09-05,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-031036,Resort Hotel,0,17,2024,December,49,8,2024-12-08,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,240.0,,0,Transient,65.0,0,1
HB-092441,City Hotel,0,128,2024,July,27,1,2024-07-01,2,4,2,2.0,0,BB,USA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,163.2,0,2
HB-055993,City Hotel,1,105,2024,August,35,26,2024-08-26,1,2,3,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,150.3,0,0
HB-088121,City Hotel,0,9,2024,April,18,29,2024-04-29,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,29.0,,0,Transient-Party,110.0,0,0
HB-100317,City Hotel,0,22,2024,October,43,25,2024-10-25,0,1,2,0.0,0,SC,NOR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,110.0,0,0
HB-068114,City Hotel,1,105,2025,May,20,13,2025-05-13,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.0,0,0
HB-039937,Resort Hotel,0,236,2025,August,35,26,2025-08-26,2,5,2,0.0,1,BB,PRT,Direct,Direct,0,0,0,A,C,1,No Deposit,250.0,,0,Transient,124.54,0,2
HB-086907,City Hotel,0,159,2024,April,15,9,2024-04-09,1,1,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,3.0,,0,Transient-Party,65.0,0,0
HB-000411,Resort Hotel,0,37,2023,July,28,15,2023-07-15,2,4,2,0.0,0,HB,POL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,106.9,0,0
HB-076872,City Hotel,1,239,2023,October,42,17,2023-10-17,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-023756,Resort Hotel,0,23,2024,April,18,29,2024-04-29,1,2,3,0.0,0,HB,ESP,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,171.0,1,1
HB-046362,City Hotel,1,160,2023,December,52,30,2023-12-30,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,111,Transient-Party,70.0,0,0
HB-078753,City Hotel,0,2,2023,October,41,13,2023-10-13,0,3,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,26.0,,0,Transient-Party,91.0,0,0
HB-038831,Resort Hotel,0,192,2025,July,30,22,2025-07-22,3,6,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,F,F,1,No Deposit,250.0,,0,Transient,227.6,1,2
HB-005774,Resort Hotel,1,17,2024,May,20,13,2024-05-13,2,3,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,135.0,0,0
HB-075511,City Hotel,1,355,2023,October,40,7,2023-10-07,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-094750,City Hotel,0,149,2024,August,31,3,2024-08-03,2,4,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,119.0,0,1
HB-118418,City Hotel,0,113,2025,August,33,17,2025-08-17,0,3,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,121.5,0,3
HB-022095,Resort Hotel,0,22,2024,November,46,11,2024-11-11,0,1,3,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,C,0,No Deposit,,,0,Transient,65.0,0,0
HB-082192,City Hotel,0,47,2023,December,51,19,2023-12-19,2,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,B,B,0,No Deposit,14.0,,0,Transient,71.5,0,0
HB-064874,City Hotel,1,64,2025,March,12,18,2025-03-18,2,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.2,0,0
HB-045255,City Hotel,0,69,2023,October,43,25,2023-10-25,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,58,Transient-Party,85.67,0,0
HB-028331,Resort Hotel,0,297,2024,September,38,19,2024-09-19,3,7,2,0.0,0,HB,POL,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,315.0,,0,Transient,88.9,0,1
HB-052719,City Hotel,0,282,2024,June,23,9,2024-06-09,0,3,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,48,Transient-Party,73.33,0,1
HB-058534,City Hotel,1,461,2024,October,41,13,2024-10-13,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-036788,Resort Hotel,0,206,2025,May,21,20,2025-05-20,3,6,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,52.85,0,0
HB-116511,City Hotel,0,168,2025,July,29,17,2025-07-17,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,1
HB-043593,City Hotel,0,15,2023,September,38,20,2023-09-20,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,124.0,0,2
HB-109827,City Hotel,0,178,2025,April,15,12,2025-04-12,1,4,2,2.0,0,BB,ITA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,189.0,0,0
HB-042002,City Hotel,0,145,2023,August,35,29,2023-08-29,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-008509,Resort Hotel,1,243,2024,October,40,2,2024-10-02,2,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,49.0,0,0
HB-022142,Resort Hotel,0,29,2024,March,11,16,2024-03-16,0,3,1,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,D,0,No Deposit,250.0,,0,Transient,40.0,0,0
HB-108425,City Hotel,0,193,2025,March,12,23,2025-03-23,1,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,108.0,0,1
HB-106102,City Hotel,0,10,2025,February,8,19,2025-02-19,2,0,1,0.0,0,BB,ITA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,85.0,0,0
HB-065391,City Hotel,1,27,2025,April,14,2,2025-04-02,2,1,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,150.0,0,0
HB-075752,City Hotel,1,312,2023,August,34,25,2023-08-25,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-115350,City Hotel,0,217,2025,June,27,30,2025-06-30,2,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.08,0,0
HB-023530,Resort Hotel,0,0,2024,October,42,18,2024-10-18,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,2,A,E,0,No Deposit,,409.0,0,Transient,50.0,0,0
HB-070326,City Hotel,1,154,2025,June,24,15,2025-06-15,0,2,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,150.3,0,2
HB-074733,City Hotel,1,329,2023,September,37,11,2023-09-11,2,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,5.0,,0,Transient,90.0,0,0
HB-080767,City Hotel,1,180,2024,April,15,13,2024-04-13,0,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,21.0,,38,Transient,125.0,0,0
HB-079696,City Hotel,0,55,2024,March,13,31,2024-03-31,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,3,A,A,0,No Deposit,,40.0,0,Transient-Party,67.0,1,0
HB-023765,Resort Hotel,0,0,2024,May,18,2,2024-05-02,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,79.0,0,0
HB-055696,City Hotel,1,291,2024,August,34,19,2024-08-19,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,39.0,,0,Transient,115.0,0,0
HB-066459,City Hotel,1,44,2025,April,16,20,2025-04-20,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,85.0,0,0
HB-088042,City Hotel,0,79,2024,April,17,27,2024-04-27,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-029720,Resort Hotel,0,0,2024,November,44,3,2024-11-03,0,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient,75.0,0,0
HB-008259,Resort Hotel,1,244,2024,September,38,20,2024-09-20,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,80.0,0,1
HB-115913,City Hotel,0,201,2025,July,28,11,2025-07-11,0,2,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,9.0,,0,Transient,179.1,0,0
HB-099316,City Hotel,0,28,2024,October,41,10,2024-10-10,1,1,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,139.0,0,2
HB-024482,Resort Hotel,0,189,2024,May,20,16,2024-05-16,2,5,2,0.0,0,HB,POL,Offline TA/TO,TA/TO,0,0,0,E,E,1,No Deposit,315.0,,0,Transient-Party,82.95,0,1
HB-008257,Resort Hotel,1,244,2024,September,38,20,2024-09-20,2,5,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,71.0,0,2
HB-071807,City Hotel,1,229,2025,July,28,12,2025-07-12,1,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-005797,Resort Hotel,0,211,2024,May,20,14,2024-05-14,1,1,1,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,1,No Deposit,298.0,,0,Transient-Party,54.5,0,0
HB-047657,City Hotel,1,1,2024,February,9,28,2024-02-28,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,60.0,0,0
HB-067446,City Hotel,1,266,2025,May,18,3,2025-05-03,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,0,Transient,100.0,0,0
HB-055676,City Hotel,1,192,2024,August,33,18,2024-08-18,2,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,99.45,0,1
HB-058006,City Hotel,1,56,2024,October,40,5,2024-10-05,0,1,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.2,0,0
HB-106336,City Hotel,0,30,2025,February,5,2,2025-02-02,6,16,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,9.0,,0,Transient,115.6,0,3
HB-050358,City Hotel,1,15,2024,April,18,29,2024-04-29,0,2,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,177.0,0,0
HB-102548,City Hotel,0,35,2024,November,48,28,2024-11-28,1,2,1,0.0,0,BB,AUT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,65.0,0,0
HB-044491,City Hotel,1,41,2023,October,40,6,2023-10-06,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,98.67,0,2
HB-098274,City Hotel,0,20,2024,September,39,25,2024-09-25,2,0,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,85.5,0,1
HB-098798,City Hotel,0,89,2024,October,40,3,2024-10-03,1,1,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,16.0,,0,Transient,80.75,0,0
HB-019901,Resort Hotel,0,0,2024,February,7,13,2024-02-13,0,1,2,0.0,0,BB,PRT,Direct,Direct,1,0,1,A,A,1,No Deposit,,,0,Transient,65.0,0,0
HB-057446,City Hotel,1,418,2024,September,39,26,2024-09-26,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,223,Transient-Party,75.0,0,0
HB-020529,Resort Hotel,0,6,2024,January,5,31,2024-01-31,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,56.0,1,1
HB-030685,Resort Hotel,0,0,2024,November,48,30,2024-11-30,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,43.0,1,0
HB-028646,Resort Hotel,0,11,2024,October,41,9,2024-10-09,1,0,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,405.0,0,Transient-Party,50.0,0,1
HB-103626,City Hotel,0,9,2025,January,1,2,2025-01-02,1,0,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,1,D,D,0,No Deposit,9.0,,0,Group,148.0,0,1
HB-069005,City Hotel,1,225,2025,May,21,24,2025-05-24,0,4,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,0
HB-095059,City Hotel,0,184,2024,August,33,13,2024-08-13,0,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,103.5,0,1
HB-040167,City Hotel,0,96,2023,July,28,11,2023-07-11,2,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-068252,City Hotel,1,164,2025,May,20,15,2025-05-15,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-046023,City Hotel,0,135,2023,December,49,5,2023-12-05,2,1,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,60.0,0,0
HB-025324,Resort Hotel,0,161,2024,June,24,15,2024-06-15,2,5,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,69.0,,0,Transient,47.9,0,0
HB-054830,City Hotel,1,86,2024,July,30,27,2024-07-27,0,4,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.95,0,0
HB-078783,City Hotel,0,0,2023,October,41,15,2023-10-15,0,1,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,104.72,0,1
HB-036397,Resort Hotel,0,119,2025,May,19,7,2025-05-07,4,9,2,0.0,0,FB,GBR,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,314.0,,0,Transient-Party,118.8,0,0
HB-018742,Resort Hotel,0,2,2023,November,48,27,2023-11-27,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,330.0,,0,Transient-Party,29.0,0,0
HB-082435,City Hotel,0,21,2023,December,52,25,2023-12-25,2,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient-Party,58.0,0,1
HB-057880,City Hotel,1,102,2024,October,40,2,2024-10-02,2,1,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,0
HB-081173,City Hotel,0,6,2023,December,48,3,2023-12-03,0,2,2,0.0,0,BB,SGP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,151.0,,0,Transient-Party,55.0,0,0
HB-118126,City Hotel,0,504,2025,August,33,12,2025-08-12,2,1,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,1
HB-033097,Resort Hotel,0,0,2025,February,7,14,2025-02-14,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,68.0,1,1
HB-093322,City Hotel,0,161,2024,July,29,16,2024-07-16,2,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,87.13,0,1
HB-003694,Resort Hotel,0,165,2023,December,52,30,2023-12-30,0,4,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,308.0,,122,Transient-Party,136.5,0,0
HB-049663,City Hotel,1,9,2024,April,16,17,2024-04-17,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,101.0,0,0
HB-026115,Resort Hotel,0,160,2024,July,29,18,2024-07-18,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,96.0,,0,Transient,102.8,0,0
HB-054648,City Hotel,1,101,2024,July,30,22,2024-07-22,0,2,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,142.2,0,0
HB-102048,City Hotel,0,5,2024,November,47,19,2024-11-19,2,1,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,107.67,0,2
HB-027240,Resort Hotel,0,89,2024,August,33,15,2024-08-15,3,6,2,0.0,0,HB,RUS,Direct,Direct,0,0,0,F,F,1,No Deposit,250.0,,0,Transient,236.93,0,1
HB-060814,City Hotel,1,44,2024,November,47,22,2024-11-22,0,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.07,0,1
HB-114370,City Hotel,0,96,2025,June,25,18,2025-06-18,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,159.0,,0,Transient,98.17,0,0
HB-011276,Resort Hotel,1,221,2025,April,18,30,2025-04-30,2,5,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,71.43,0,0
HB-082128,City Hotel,1,99,2024,February,8,19,2024-02-19,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,1,0,A,A,0,No Deposit,,67.0,0,Transient-Party,80.0,0,0
HB-008217,Resort Hotel,1,206,2024,September,38,18,2024-09-18,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,104.75,0,1
HB-094120,City Hotel,0,180,2024,July,30,28,2024-07-28,1,3,2,0.0,0,SC,LTU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.0,0,1
HB-025591,Resort Hotel,0,182,2024,June,26,27,2024-06-27,1,5,2,1.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,95.0,1,2
HB-118178,City Hotel,0,46,2025,August,33,12,2025-08-12,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,1
HB-111086,City Hotel,0,109,2025,May,18,1,2025-05-01,1,4,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-051493,City Hotel,1,211,2024,May,21,20,2024-05-20,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,111,Transient,100.0,0,0
HB-033241,Resort Hotel,0,17,2025,February,8,17,2025-02-17,0,1,2,0.0,0,Undefined,PRT,Direct,Direct,0,0,0,E,E,1,No Deposit,250.0,,0,Transient,149.0,0,3
HB-082004,City Hotel,1,115,2024,March,12,20,2024-03-20,2,0,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,41.0,,22,Transient,70.0,0,0
HB-079131,City Hotel,0,0,2023,October,42,21,2023-10-21,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,F,0,No Deposit,,,0,Transient,107.0,0,0
HB-104972,City Hotel,0,78,2025,January,4,25,2025-01-25,0,2,1,0.0,0,BB,SVK,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,365.0,0,Transient-Party,85.0,0,0
HB-042675,City Hotel,0,69,2023,September,36,9,2023-09-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-010549,Resort Hotel,1,26,2025,March,11,14,2025-03-14,0,5,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient-Party,80.0,0,0
HB-055292,City Hotel,1,405,2024,August,32,10,2024-08-10,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,65.0,0,0
HB-089446,City Hotel,0,102,2024,May,20,19,2024-05-19,0,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,140.4,0,0
HB-096395,City Hotel,0,121,2024,August,35,26,2024-08-26,2,5,3,0.0,0,BB,FRA,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient,187.0,0,2
HB-061741,City Hotel,1,291,2024,December,52,24,2024-12-24,2,6,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,146.2,0,0
HB-091144,City Hotel,0,256,2024,June,24,15,2024-06-15,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-088223,City Hotel,0,3,2024,May,18,2,2024-05-02,1,0,1,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,104.72,0,1
HB-090121,City Hotel,0,1,2024,May,22,31,2024-05-31,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.0,0,1
HB-019656,Resort Hotel,0,45,2023,December,52,25,2023-12-25,2,3,2,2.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,C,C,0,No Deposit,196.0,,0,Transient,46.0,0,0
HB-036039,Resort Hotel,0,248,2025,May,18,3,2025-05-03,1,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,54.0,0,1
HB-065676,City Hotel,1,62,2025,April,14,6,2025-04-06,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,135.0,0,0
HB-086113,City Hotel,0,189,2024,March,13,25,2024-03-25,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Transient,60.0,0,1
HB-041423,City Hotel,0,131,2023,August,33,15,2023-08-15,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-015988,Resort Hotel,0,74,2023,August,32,9,2023-08-09,1,0,2,0.0,0,BB,USA,Direct,Direct,0,0,0,A,E,0,No Deposit,250.0,,0,Transient,134.0,0,0
HB-110431,City Hotel,0,30,2025,April,17,27,2025-04-27,0,1,1,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,124.0,0,1
HB-098885,City Hotel,0,46,2024,October,40,2,2024-10-02,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,90.55,0,1
HB-039007,Resort Hotel,0,1,2025,July,31,31,2025-07-31,1,4,1,2.0,0,HB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,242.0,,0,Transient,339.4,1,2
HB-113110,City Hotel,0,194,2025,May,22,28,2025-05-28,2,4,2,2.0,0,BB,FRA,Direct,Direct,0,0,0,G,G,1,No Deposit,14.0,,0,Transient,227.25,0,0
HB-037799,Resort Hotel,0,8,2025,June,26,29,2025-06-29,0,1,1,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,A,1,No Deposit,,525.0,0,Transient-Party,120.0,0,0
HB-006534,Resort Hotel,1,40,2024,June,24,16,2024-06-16,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,129.0,0,0
HB-043423,City Hotel,1,74,2023,September,38,18,2023-09-18,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-063835,City Hotel,1,594,2025,February,8,23,2025-02-23,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-111974,City Hotel,0,9,2025,May,20,17,2025-05-17,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,117.9,0,1
HB-054295,City Hotel,1,138,2024,July,28,11,2024-07-11,1,4,2,2.0,0,BB,ITA,Online TA,TA/TO,0,0,0,F,F,2,No Deposit,9.0,,0,Transient,169.15,0,0
HB-076061,City Hotel,1,364,2023,October,42,16,2023-10-16,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-103157,City Hotel,0,1,2024,December,50,12,2024-12-12,1,1,1,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,87.0,0,1
HB-059623,City Hotel,1,150,2024,October,44,30,2024-10-30,2,0,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.1,0,0
HB-074871,City Hotel,1,153,2023,August,31,3,2023-08-03,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-017892,Resort Hotel,0,163,2023,October,43,23,2023-10-23,1,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient-Party,47.0,0,1
HB-054997,City Hotel,1,114,2024,August,31,2,2024-08-02,0,2,2,3.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,8.0,,0,Transient,266.3,0,0
HB-099068,City Hotel,0,34,2024,October,40,6,2024-10-06,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,83.0,,0,Transient,153.0,0,0
HB-021338,Resort Hotel,0,9,2024,February,8,25,2024-02-25,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,82.0,0,Transient,30.0,0,0
HB-043993,City Hotel,1,96,2023,September,39,28,2023-09-28,1,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,1,No Deposit,3.0,,0,Transient-Party,138.0,0,0
HB-020347,Resort Hotel,0,3,2024,January,4,23,2024-01-23,1,1,2,0.0,0,BB,CHE,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,61.0,1,0
HB-100792,City Hotel,0,226,2024,October,44,29,2024-10-29,2,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,70.0,0,1
HB-081091,City Hotel,0,0,2024,November,48,29,2024-11-29,0,1,2,0.0,0,HB,PRT,Complementary,Direct,1,0,2,G,G,0,No Deposit,,,0,Transient,0.0,0,3
HB-025427,Resort Hotel,0,124,2024,June,25,18,2024-06-18,3,6,3,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,153.0,0,1
HB-084328,City Hotel,0,19,2024,February,8,19,2024-02-19,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,93.0,0,2
HB-083135,City Hotel,0,36,2024,January,3,19,2024-01-19,0,2,1,0.0,0,BB,USA,Offline TA/TO,TA/TO,0,0,0,A,D,2,No Deposit,19.0,,0,Transient-Party,71.0,0,0
HB-056095,City Hotel,1,99,2024,August,35,29,2024-08-29,1,1,2,0.0,0,SC,AUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,0
HB-018224,Resort Hotel,0,65,2023,November,45,8,2023-11-08,2,5,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,58.0,0,1
HB-111038,City Hotel,0,1,2025,May,18,3,2025-05-03,0,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,112.0,0,1
HB-087429,City Hotel,0,35,2024,April,16,18,2024-04-18,1,1,2,1.0,0,BB,THA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,112.5,0,2
HB-034096,Resort Hotel,0,30,2025,March,11,10,2025-03-10,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,G,G,0,No Deposit,250.0,,0,Transient,100.0,0,0
HB-071425,City Hotel,1,179,2025,July,27,5,2025-07-05,0,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,2
HB-050346,City Hotel,1,443,2024,April,18,29,2024-04-29,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,65.0,0,0
HB-024230,Resort Hotel,0,9,2024,May,20,15,2024-05-15,1,0,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,I,0,No Deposit,,,0,Transient-Party,70.0,0,0
HB-025178,Resort Hotel,0,177,2024,June,24,11,2024-06-11,2,4,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,93.0,0,2
HB-033814,Resort Hotel,0,163,2025,February,9,28,2025-02-28,0,5,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,H,H,1,No Deposit,240.0,,0,Transient-Party,87.0,0,0
HB-073436,City Hotel,1,199,2025,August,34,21,2025-08-21,2,5,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-080349,City Hotel,0,25,2023,November,45,10,2023-11-10,2,5,2,0.0,0,BB,HRV,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,68.0,0,1
HB-050514,City Hotel,1,16,2024,May,18,2,2024-05-02,1,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,156.0,0,0
HB-070870,City Hotel,1,208,2025,June,26,23,2025-06-23,2,5,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,1
HB-074105,City Hotel,1,328,2023,September,36,10,2023-09-10,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-022692,Resort Hotel,0,2,2024,March,13,31,2024-03-31,0,2,3,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,,0,Transient,131.0,1,0
HB-056297,City Hotel,1,178,2024,September,36,2,2024-09-02,2,5,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient-Party,112.01,0,0
HB-088717,City Hotel,0,66,2024,May,18,5,2024-05-05,2,4,2,0.0,0,SC,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,138.0,,0,Transient,85.0,0,0
HB-081410,City Hotel,0,1,2023,December,49,10,2023-12-10,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-068350,City Hotel,1,104,2025,May,20,15,2025-05-15,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-025736,Resort Hotel,0,10,2024,July,27,3,2024-07-03,2,4,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,196.33,1,1
HB-094134,City Hotel,0,301,2024,July,31,30,2024-07-30,1,1,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-005759,Resort Hotel,1,25,2024,May,19,12,2024-05-12,2,3,2,2.0,0,BB,NOR,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,135.0,0,0
HB-008715,Resort Hotel,0,362,2024,October,41,10,2024-10-10,2,5,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,1,No Deposit,,223.0,0,Transient-Party,68.0,0,0
HB-054575,City Hotel,1,78,2024,July,29,20,2024-07-20,0,2,3,0.0,0,BB,AGO,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,142.2,0,2
HB-093964,City Hotel,0,64,2024,July,30,26,2024-07-26,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.3,0,1
HB-014420,Resort Hotel,0,204,2024,September,38,17,2024-09-17,6,15,2,0.0,0,HB,BEL,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,102.86,0,1
HB-112089,City Hotel,0,70,2025,May,20,14,2025-05-14,2,4,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,192.0,0,0
HB-062015,City Hotel,1,151,2024,December,1,30,2024-12-30,0,2,2,1.0,0,BB,LUX,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,143.38,0,1
HB-000047,Resort Hotel,0,96,2023,July,26,2,2023-07-02,2,5,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient,58.95,0,1
HB-013990,Resort Hotel,0,11,2024,October,43,24,2024-10-24,1,3,1,0.0,0,BB,,Corporate,Direct,0,1,0,A,A,0,No Deposit,,39.0,0,Transient,52.0,0,0
HB-082981,City Hotel,0,1,2025,April,15,11,2025-04-11,0,1,1,0.0,0,BB,PRT,Complementary,Direct,1,0,6,A,A,0,No Deposit,,45.0,0,Group,0.0,0,1
HB-055851,City Hotel,1,116,2024,August,34,22,2024-08-22,1,5,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,150.3,0,0
HB-081589,City Hotel,1,197,2024,June,23,3,2024-06-03,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,21.0,,25,Transient,80.0,0,0
HB-046583,City Hotel,0,1,2024,January,2,8,2024-01-08,0,1,1,1.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,75.0,0,0
HB-033066,Resort Hotel,0,16,2025,February,7,11,2025-02-11,2,1,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,,0,Transient,72.0,1,0
HB-097563,City Hotel,0,40,2024,September,37,13,2024-09-13,0,5,1,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,1,No Deposit,86.0,,0,Transient-Party,108.0,0,0
HB-086478,City Hotel,0,191,2024,March,13,30,2024-03-30,1,4,2,0.0,0,BB,POL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Transient,69.0,0,0
HB-096788,City Hotel,0,224,2024,September,36,3,2024-09-03,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,109.31,0,1
HB-017249,Resort Hotel,1,289,2023,November,47,20,2023-11-20,1,2,2,0.0,0,FB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,134.0,,0,Transient-Party,69.0,0,0
HB-041696,City Hotel,0,6,2023,August,34,21,2023-08-21,2,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.4,0,0
HB-049745,City Hotel,1,108,2024,April,16,18,2024-04-18,1,4,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,82.4,0,0
HB-066414,City Hotel,1,11,2025,April,16,19,2025-04-19,1,4,2,0.0,0,SC,TUN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,150.0,0,2
HB-079303,City Hotel,0,4,2023,October,42,18,2023-10-18,2,4,2,0.0,0,BB,BRA,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,114.0,0,0
HB-004379,Resort Hotel,1,32,2024,March,10,9,2024-03-09,2,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,184.0,,0,Transient,40.8,0,0
HB-080706,City Hotel,0,32,2023,November,47,20,2023-11-20,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,119.0,,0,Transient-Party,73.0,0,0
HB-082664,City Hotel,0,44,2024,January,1,2,2024-01-02,2,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,98.0,0,0
HB-001865,Resort Hotel,1,32,2023,September,38,18,2023-09-18,2,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,0,No Deposit,250.0,,0,Transient,126.0,0,0
HB-057661,City Hotel,1,134,2024,September,39,29,2024-09-29,1,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,137.7,0,2
HB-103173,City Hotel,0,0,2024,December,50,13,2024-12-13,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,238.0,0,Transient,79.0,0,1
HB-005794,Resort Hotel,0,206,2024,May,20,14,2024-05-14,4,6,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,59.93,0,0
HB-049271,City Hotel,1,9,2024,April,15,8,2024-04-08,2,6,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,200.75,0,0
HB-045952,City Hotel,1,139,2023,December,48,3,2023-12-03,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,72.25,0,1
HB-108457,City Hotel,0,34,2025,March,12,21,2025-03-21,2,5,0,1.0,0,BB,BLR,Direct,Direct,0,0,0,B,A,1,No Deposit,14.0,,0,Transient,93.82,0,0
HB-114703,City Hotel,0,54,2025,June,26,24,2025-06-24,1,1,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,1
HB-084980,City Hotel,0,52,2024,March,10,6,2024-03-06,1,0,2,0.0,0,BB,JPN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.3,0,1
HB-079442,City Hotel,1,137,2024,January,4,27,2024-01-27,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,29.0,,45,Transient,70.0,0,0
HB-071307,City Hotel,1,167,2025,July,27,1,2025-07-01,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,117.9,0,0
HB-097215,City Hotel,0,46,2024,September,37,9,2024-09-09,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,158.4,0,0
HB-084658,City Hotel,0,30,2024,February,9,28,2024-02-28,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient-Party,72.0,0,1
HB-098825,City Hotel,0,10,2024,October,40,2,2024-10-02,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-065613,City Hotel,1,62,2025,April,14,6,2025-04-06,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,135.0,0,0
HB-073604,City Hotel,1,121,2025,August,35,27,2025-08-27,2,1,3,0.0,0,HB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,252.0,0,1
HB-021173,Resort Hotel,0,4,2024,February,7,16,2024-02-16,0,4,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,45.0,0,0
HB-062205,City Hotel,1,195,2025,January,1,4,2025-01-04,0,4,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,0
HB-107180,City Hotel,0,18,2025,March,10,5,2025-03-05,2,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,91.8,0,3
HB-090694,City Hotel,0,34,2024,June,23,9,2024-06-09,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,98.0,0,0
HB-041397,City Hotel,1,40,2023,August,33,15,2023-08-15,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-025549,Resort Hotel,0,166,2024,June,26,25,2024-06-25,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,E,1,No Deposit,156.0,,0,Transient,86.17,0,2
HB-012086,Resort Hotel,1,230,2025,June,24,12,2025-06-12,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,1,No Deposit,11.0,,0,Transient,83.7,0,1
HB-021984,Resort Hotel,0,12,2024,March,11,14,2024-03-14,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,62.0,0,Transient,30.0,0,0
HB-107252,City Hotel,0,43,2025,March,10,6,2025-03-06,1,3,2,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,70.69,0,2
HB-108970,City Hotel,0,111,2025,April,14,3,2025-04-03,1,1,2,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,95.0,0,1
HB-012273,Resort Hotel,1,329,2025,June,25,21,2025-06-21,2,7,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,C,1,No Deposit,240.0,,0,Transient,74.25,0,1
HB-068336,City Hotel,1,164,2025,May,20,15,2025-05-15,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-016018,Resort Hotel,0,120,2023,August,31,4,2023-08-04,2,5,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient-Party,90.95,0,1
HB-016176,Resort Hotel,0,3,2023,August,32,7,2023-08-07,3,7,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,211.0,0,3
HB-093788,City Hotel,0,74,2024,July,30,23,2024-07-23,2,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,52.0,,0,Transient,68.0,0,0
HB-080985,City Hotel,0,5,2023,December,48,1,2023-12-01,0,0,1,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,A,0,No Deposit,,45.0,0,Transient,0.0,0,0
HB-012483,Resort Hotel,1,59,2025,July,27,1,2025-07-01,2,5,2,1.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,178.31,0,1
HB-094619,City Hotel,0,115,2024,August,31,3,2024-08-03,0,4,2,1.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,123.75,0,2
HB-094919,City Hotel,0,146,2024,August,32,9,2024-08-09,0,3,2,0.0,0,BB,CHE,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,83.0,,0,Transient,113.56,0,0
HB-065020,City Hotel,1,46,2025,March,12,22,2025-03-22,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,8.0,,0,Transient,231.33,0,1
HB-093560,City Hotel,0,292,2024,July,29,21,2024-07-21,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,0
HB-026465,Resort Hotel,0,147,2024,July,30,27,2024-07-27,1,4,2,1.0,0,BB,AGO,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,212.5,0,2
HB-007133,Resort Hotel,1,149,2024,July,30,23,2024-07-23,2,5,2,1.0,0,FB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,2,No Deposit,96.0,,0,Transient,195.75,0,1
HB-062576,City Hotel,1,2,2025,January,3,15,2025-01-15,2,3,1,0.0,0,BB,BEL,Aviation,Corporate,0,0,0,A,A,0,No Deposit,,153.0,0,Transient,79.0,0,0
HB-053783,City Hotel,1,358,2024,June,26,30,2024-06-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-035203,Resort Hotel,0,34,2025,April,15,9,2025-04-09,2,5,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,493.0,,0,Contract,80.0,0,0
HB-116396,City Hotel,0,84,2025,July,29,16,2025-07-16,2,1,4,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,234.0,0,3
HB-032633,Resort Hotel,0,4,2025,January,5,30,2025-01-30,1,0,1,0.0,0,BB,GBR,Complementary,TA/TO,0,0,0,F,F,0,No Deposit,40.0,,0,Transient,0.0,0,1
HB-036450,Resort Hotel,0,2,2025,May,21,20,2025-05-20,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,C,C,1,No Deposit,240.0,,0,Transient-Party,150.0,1,1
HB-085641,City Hotel,0,44,2024,March,11,17,2024-03-17,0,2,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,103.95,0,0
HB-102188,City Hotel,0,214,2024,November,47,20,2024-11-20,2,2,2,0.0,0,BB,ITA,Groups,Corporate,0,0,0,A,D,1,No Deposit,,233.0,0,Transient,85.0,0,0
HB-094781,City Hotel,0,182,2024,August,32,7,2024-08-07,2,1,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,137.7,0,0
HB-105467,City Hotel,0,16,2025,February,6,4,2025-02-04,2,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-069847,City Hotel,1,191,2025,June,23,7,2025-06-07,0,4,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-009726,Resort Hotel,1,258,2024,December,52,29,2024-12-29,4,8,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,59.48,0,0
HB-107558,City Hotel,0,20,2025,March,11,13,2025-03-13,1,1,1,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,254.0,,0,Transient-Party,178.0,0,0
HB-045010,City Hotel,1,102,2023,October,42,16,2023-10-16,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-009644,Resort Hotel,1,227,2024,December,51,22,2024-12-22,2,4,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,46.8,0,0
HB-033315,Resort Hotel,0,15,2025,February,8,17,2025-02-17,1,2,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient-Party,85.0,0,0
HB-011567,Resort Hotel,1,107,2025,May,20,17,2025-05-17,2,5,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,147.0,0,0
HB-044781,City Hotel,0,0,2023,October,41,11,2023-10-11,2,0,2,0.0,0,BB,PRT,Direct,TA/TO,0,0,0,F,F,3,No Deposit,,,0,Transient,167.0,0,1
HB-090139,City Hotel,0,20,2024,May,22,29,2024-05-29,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,110.15,0,1
HB-041761,City Hotel,0,3,2023,August,34,23,2023-08-23,2,0,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,75.0,0,1
HB-048562,City Hotel,1,35,2024,March,13,25,2024-03-25,1,2,2,1.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient,76.05,0,1
HB-118118,City Hotel,0,170,2025,August,33,11,2025-08-11,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,4,No Deposit,9.0,,0,Transient-Party,175.5,0,0
HB-033574,Resort Hotel,0,121,2025,February,8,20,2025-02-20,2,5,2,1.0,1,HB,FRA,Offline TA/TO,TA/TO,0,0,0,C,C,1,No Deposit,464.0,,0,Transient,70.0,0,1
HB-087268,City Hotel,0,154,2024,April,16,15,2024-04-15,0,2,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,135.0,0,2
HB-084389,City Hotel,0,41,2024,February,8,22,2024-02-22,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient-Party,71.52,0,1
HB-064699,City Hotel,1,92,2025,March,11,15,2025-03-15,0,3,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,85.0,0,0
HB-004941,Resort Hotel,1,121,2024,April,15,9,2024-04-09,2,5,2,0.0,0,HB,GBR,Groups,Direct,0,0,0,D,D,0,Non Refund,273.0,,0,Transient,72.0,0,0
HB-084069,City Hotel,0,111,2024,February,7,14,2024-02-14,2,3,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,87.0,0,0
HB-066331,City Hotel,1,155,2025,April,16,17,2025-04-17,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,2
HB-088873,City Hotel,0,21,2024,May,19,9,2024-05-09,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,1
HB-034426,Resort Hotel,0,47,2025,March,12,20,2025-03-20,1,4,1,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,91.0,,0,Transient-Party,48.5,0,0
HB-088589,City Hotel,0,103,2024,May,18,5,2024-05-05,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,95.88,0,1
HB-086972,City Hotel,0,90,2024,April,15,11,2024-04-11,1,0,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,9.0,,0,Transient,105.3,0,1
HB-106584,City Hotel,0,26,2025,February,9,27,2025-02-27,1,0,1,0.0,0,SC,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,1
HB-065249,City Hotel,1,138,2025,March,13,30,2025-03-30,0,2,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.6,0,0
HB-036844,Resort Hotel,0,345,2025,May,21,24,2025-05-24,2,5,2,0.0,1,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,C,1,No Deposit,6.0,,0,Transient,53.57,1,2
HB-064797,City Hotel,1,205,2025,March,11,16,2025-03-16,0,3,2,0.0,0,SC,TUR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,0
HB-006120,Resort Hotel,0,225,2024,May,21,26,2024-05-26,0,3,1,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,A,2,No Deposit,,223.0,0,Transient-Party,60.0,0,0
HB-030940,Resort Hotel,0,154,2024,December,49,3,2024-12-03,2,4,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,D,D,1,No Deposit,250.0,,0,Transient,42.12,0,0
HB-028670,Resort Hotel,0,172,2024,October,41,7,2024-10-07,0,2,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,73.39,0,1
HB-040578,City Hotel,1,117,2023,August,31,1,2023-08-01,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-113950,City Hotel,0,154,2025,June,23,5,2025-06-05,3,7,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,144.0,0,1
HB-038092,Resort Hotel,0,3,2025,July,28,8,2025-07-08,0,1,3,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,G,G,2,No Deposit,240.0,,0,Transient,322.0,1,0
HB-077728,City Hotel,0,0,2023,September,38,21,2023-09-21,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,9.0,,0,Contract,155.0,0,1
HB-068424,City Hotel,1,79,2025,May,20,17,2025-05-17,0,2,2,0.0,0,SC,IND,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,112.5,0,0
HB-104285,City Hotel,0,13,2025,January,2,7,2025-01-07,2,1,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.29,0,0
HB-111340,City Hotel,0,118,2025,May,18,4,2025-05-04,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,97.02,0,1
HB-037987,Resort Hotel,0,47,2025,July,27,1,2025-07-01,2,3,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,C,I,0,No Deposit,240.0,,0,Transient,210.0,0,1
HB-095683,City Hotel,0,157,2024,August,34,19,2024-08-19,1,2,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,156.9,1,0
HB-011418,Resort Hotel,1,90,2025,May,19,6,2025-05-06,2,6,2,1.0,0,BB,IRL,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,98.0,0,0
HB-060883,City Hotel,1,56,2024,November,48,25,2024-11-25,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,93.6,0,1
HB-036882,Resort Hotel,0,203,2025,May,21,25,2025-05-25,2,5,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,1,No Deposit,,223.0,0,Transient-Party,59.71,0,0
HB-008593,Resort Hotel,1,383,2024,October,40,6,2024-10-06,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,315.0,,0,Transient-Party,48.0,0,0
HB-079028,City Hotel,0,1,2023,October,42,20,2023-10-20,0,1,1,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient,145.0,0,0
HB-067623,City Hotel,1,168,2025,May,19,5,2025-05-05,1,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.5,0,0
HB-079832,City Hotel,0,38,2023,October,44,31,2023-10-31,2,4,2,1.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,16.0,,0,Transient,64.72,0,1
HB-057356,City Hotel,1,254,2024,September,39,24,2024-09-24,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,96.0,0,0
HB-106421,City Hotel,0,30,2025,February,8,21,2025-02-21,0,4,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,92.94,0,0
HB-068437,City Hotel,1,66,2025,May,20,17,2025-05-17,0,4,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,144.0,0,0
HB-110466,City Hotel,0,102,2025,April,17,24,2025-04-24,1,3,1,0.0,0,BB,IRL,Groups,TA/TO,0,0,0,A,D,1,No Deposit,,424.0,0,Transient-Party,90.0,0,0
HB-092072,City Hotel,0,77,2024,June,26,26,2024-06-26,2,2,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,112.5,1,0
HB-060393,City Hotel,1,50,2024,November,45,9,2024-11-09,0,2,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,145.69,0,0
HB-118692,City Hotel,0,2,2025,August,34,23,2025-08-23,0,1,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,179.0,1,2
HB-043376,City Hotel,0,74,2023,September,38,18,2023-09-18,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-094521,City Hotel,0,120,2024,August,31,2,2024-08-02,0,4,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,72.25,0,0
HB-112588,City Hotel,0,208,2025,May,21,24,2025-05-24,0,2,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,114.4,0,0
HB-025723,Resort Hotel,0,9,2024,July,27,5,2024-07-05,0,3,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,159.07,1,1
HB-037546,Resort Hotel,0,157,2025,June,24,13,2025-06-13,2,7,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,314.0,,0,Transient,92.0,0,1
HB-096133,City Hotel,0,52,2024,August,35,28,2024-08-28,1,0,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,0
HB-059906,City Hotel,1,304,2024,November,44,3,2024-11-03,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,89.0,0,0
HB-069971,City Hotel,1,148,2025,June,23,8,2025-06-08,0,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,180.0,0,0
HB-092200,City Hotel,0,40,2024,June,26,29,2024-06-29,0,3,2,1.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,134.1,0,2
HB-036840,Resort Hotel,0,123,2025,May,20,17,2025-05-17,4,10,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,114.5,0,2
HB-075646,City Hotel,1,290,2023,August,31,3,2023-08-03,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-065717,City Hotel,1,66,2025,April,14,6,2025-04-06,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,4,Transient,135.0,0,0
HB-081844,City Hotel,1,178,2024,April,17,28,2024-04-28,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,46,Transient,110.0,0,0
HB-021613,Resort Hotel,0,60,2024,March,10,5,2024-03-05,0,1,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,251.0,,0,Transient,37.0,0,0
HB-035307,Resort Hotel,0,198,2025,April,16,15,2025-04-15,2,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,242.0,,0,Transient,98.5,1,1
HB-003018,Resort Hotel,1,40,2023,November,45,11,2023-11-11,0,4,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,281.0,,0,Transient-Party,40.0,0,0
HB-110867,City Hotel,0,256,2025,May,18,2,2025-05-02,0,1,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,110.0,0,1
HB-052394,City Hotel,1,163,2024,June,23,5,2024-06-05,2,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,171.0,,0,Transient,100.0,0,0
HB-016711,Resort Hotel,0,244,2023,September,35,2,2023-09-02,2,5,2,0.0,0,BB,IRL,Groups,TA/TO,0,0,0,A,A,0,No Deposit,96.0,,0,Transient-Party,57.0,0,0
HB-076877,City Hotel,1,239,2023,October,42,17,2023-10-17,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-089992,City Hotel,0,95,2024,May,22,29,2024-05-29,2,0,2,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,65.0,0,1
HB-016152,Resort Hotel,0,89,2023,August,32,10,2023-08-10,1,5,4,0.0,1,BB,PRT,Direct,Direct,0,0,0,H,H,3,No Deposit,,,0,Transient,190.0,0,1
HB-031808,Resort Hotel,0,73,2025,January,1,2,2025-01-02,1,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,242.0,,0,Transient,37.8,0,1
HB-026889,Resort Hotel,0,131,2024,August,32,8,2024-08-08,1,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,211.0,0,2
HB-067351,City Hotel,1,103,2025,May,18,2,2025-05-02,0,2,3,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,171.0,0,0
HB-088772,City Hotel,1,26,2024,November,44,2,2024-11-02,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,10,A,E,0,No Deposit,,219.0,0,Transient,88.0,0,1
HB-040294,City Hotel,0,90,2023,July,29,20,2023-07-20,1,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,11.0,,0,Transient,46.66,0,0
HB-009572,Resort Hotel,1,210,2024,December,50,13,2024-12-13,8,20,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,314.0,,0,Transient,47.57,0,0
HB-118564,City Hotel,0,39,2025,August,34,20,2025-08-20,2,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,310.0,,0,Transient,140.0,0,0
HB-037384,Resort Hotel,0,140,2025,June,24,10,2025-06-10,2,4,3,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,3,No Deposit,250.0,,0,Transient,207.0,1,1
HB-076664,City Hotel,0,12,2023,October,43,27,2023-10-27,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,2,8,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-100626,City Hotel,0,44,2024,October,44,28,2024-10-28,0,2,2,1.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,100.0,0,0
HB-011232,Resort Hotel,1,59,2025,April,18,29,2025-04-29,2,3,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,115.0,0,1
HB-040626,City Hotel,1,28,2023,August,31,3,2023-08-03,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-110370,City Hotel,0,310,2025,April,17,23,2025-04-23,2,2,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,21.0,,0,Transient-Party,68.88,0,0
HB-035928,Resort Hotel,0,10,2025,May,18,1,2025-05-01,1,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,106.5,0,1
HB-086522,City Hotel,0,76,2024,April,14,2,2024-04-02,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,87.3,0,1
HB-030211,Resort Hotel,0,52,2024,November,46,12,2024-11-12,2,3,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,29.0,0,0
HB-044328,City Hotel,1,89,2023,October,40,3,2023-10-03,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-002499,Resort Hotel,0,47,2023,October,42,19,2023-10-19,1,4,2,0.0,0,HB,ESP,Groups,Direct,0,0,0,A,A,0,No Deposit,,,47,Transient-Party,76.8,0,0
HB-102953,City Hotel,0,15,2024,December,49,7,2024-12-07,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,106.33,0,0
HB-019879,Resort Hotel,0,5,2024,January,1,4,2024-01-04,1,3,2,0.0,0,HB,PRT,Groups,Corporate,0,0,0,A,A,0,No Deposit,,174.0,0,Transient-Party,68.0,0,0
HB-074178,City Hotel,1,356,2023,October,40,8,2023-10-08,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-009625,Resort Hotel,1,226,2024,December,51,21,2024-12-21,0,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,55.8,0,1
HB-107351,City Hotel,0,176,2025,March,10,9,2025-03-09,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-084511,City Hotel,0,24,2024,February,9,27,2024-02-27,0,1,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.0,0,1
HB-101158,City Hotel,0,8,2024,November,44,3,2024-11-03,1,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,127.5,0,3
HB-070917,City Hotel,1,265,2025,June,26,24,2025-06-24,4,8,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,112.87,0,2
HB-097978,City Hotel,0,87,2024,September,38,21,2024-09-21,0,2,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,158.4,1,1
HB-047572,City Hotel,0,57,2024,February,9,27,2024-02-27,2,4,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,59.21,0,1
HB-018253,Resort Hotel,0,36,2023,November,45,7,2023-11-07,2,6,1,0.0,0,BB,DEU,Corporate,Corporate,0,0,0,A,A,1,No Deposit,185.0,281.0,0,Transient-Party,36.0,0,0
HB-064184,City Hotel,1,289,2025,March,9,2,2025-03-02,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,81.9,0,0
HB-035462,Resort Hotel,0,47,2025,April,16,16,2025-04-16,2,5,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,C,0,No Deposit,493.0,,0,Contract,83.0,1,1
HB-062602,City Hotel,1,55,2025,January,3,16,2025-01-16,2,5,2,2.0,0,BB,BRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,147.9,0,0
HB-041557,City Hotel,0,12,2023,August,33,18,2023-08-18,0,2,3,0.0,0,BB,ESP,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,110.0,0,2
HB-110942,City Hotel,0,9,2025,May,18,2,2025-05-02,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,89.0,0,1
HB-071781,City Hotel,1,229,2025,July,28,12,2025-07-12,1,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-054330,City Hotel,1,90,2024,July,28,13,2024-07-13,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.3,0,0
HB-111031,City Hotel,0,5,2025,May,18,1,2025-05-01,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,180.0,0,2
HB-097027,City Hotel,0,8,2024,September,37,11,2024-09-11,1,0,1,0.0,0,SC,AGO,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,129.0,0,0
HB-104739,City Hotel,0,77,2025,January,3,15,2025-01-15,2,4,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,B,A,1,No Deposit,9.0,,0,Transient,77.86,0,2
HB-058798,City Hotel,1,164,2024,October,42,16,2024-10-16,1,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,34.0,,0,Transient,115.0,0,0
HB-088448,City Hotel,0,4,2024,May,18,5,2024-05-05,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,G,0,No Deposit,9.0,,0,Transient,165.0,0,1
HB-004481,Resort Hotel,1,23,2024,March,12,19,2024-03-19,2,3,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,80.0,0,1
HB-027626,Resort Hotel,0,0,2024,September,36,3,2024-09-03,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,176.0,1,1
HB-004910,Resort Hotel,1,21,2024,April,14,7,2024-04-07,1,3,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,56.0,0,0
HB-056854,City Hotel,1,433,2024,September,37,15,2024-09-15,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-110879,City Hotel,0,104,2025,April,18,30,2025-04-30,2,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,123.0,0,0
HB-036017,Resort Hotel,0,21,2025,May,18,3,2025-05-03,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,100.8,0,0
HB-029040,Resort Hotel,0,6,2024,October,42,18,2024-10-18,0,1,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,241.0,,0,Transient,50.05,1,1
HB-061572,City Hotel,1,56,2024,December,51,16,2024-12-16,2,2,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,67.32,0,0
HB-112787,City Hotel,0,180,2025,May,21,25,2025-05-25,0,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,9.0,,0,Transient,108.0,0,2
HB-081607,City Hotel,0,17,2023,December,50,14,2023-12-14,1,0,2,0.0,0,BB,MEX,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,89.0,,0,Transient,69.6,0,0
HB-064681,City Hotel,1,6,2025,March,11,15,2025-03-15,0,2,1,0.0,0,BB,IRL,Direct,Direct,0,0,0,B,B,0,No Deposit,14.0,,0,Transient,100.6,0,0
HB-035033,Resort Hotel,0,152,2025,April,14,5,2025-04-05,2,5,3,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,C,3,No Deposit,,223.0,0,Transient-Party,68.0,0,0
HB-052256,City Hotel,1,330,2024,June,22,2,2024-06-02,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-110162,City Hotel,0,133,2025,April,16,19,2025-04-19,0,4,2,0.0,0,BB,ISL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,390.0,,0,Transient-Party,124.0,0,0
HB-084833,City Hotel,0,11,2024,March,10,4,2024-03-04,0,2,2,0.0,0,SC,AUT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,93.0,0,0
HB-011602,Resort Hotel,1,104,2025,May,21,20,2025-05-20,2,5,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,80.0,0,0
HB-004201,Resort Hotel,1,74,2024,February,9,26,2024-02-26,1,2,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,68.0,,0,Transient,70.0,0,0
HB-061040,City Hotel,1,215,2024,November,48,30,2024-11-30,0,4,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient,67.26,0,0
HB-083855,City Hotel,0,2,2024,February,7,13,2024-02-13,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,91.0,0,1
HB-106215,City Hotel,0,8,2025,March,13,30,2025-03-30,0,1,1,0.0,0,BB,ESP,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,174.0,0,Transient,80.0,0,0
HB-055718,City Hotel,1,24,2024,August,34,19,2024-08-19,2,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,78.0,0,0
HB-015249,Resort Hotel,1,207,2023,September,39,26,2023-09-26,1,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,208.0,,0,Transient,34.0,0,0
HB-005296,Resort Hotel,1,143,2024,April,17,24,2024-04-24,2,2,2,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,68.0,,0,Transient,84.0,0,0
HB-102956,City Hotel,0,71,2024,December,49,6,2024-12-06,0,4,3,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,105.0,0,0
HB-060002,City Hotel,1,107,2024,November,45,4,2024-11-04,1,2,2,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,124.2,0,1
HB-085950,City Hotel,0,51,2024,March,12,21,2024-03-21,1,3,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient-Party,83.3,0,1
HB-023079,Resort Hotel,0,0,2025,February,8,20,2025-02-20,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,12.0,0,Transient,35.0,0,0
HB-114231,City Hotel,0,39,2025,June,25,16,2025-06-16,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,153.0,0,0
HB-020472,Resort Hotel,0,16,2025,January,5,27,2025-01-27,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,1,0,1,E,E,0,No Deposit,240.0,,0,Transient,68.0,0,1
HB-099777,City Hotel,0,31,2024,October,42,15,2024-10-15,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-021300,Resort Hotel,0,12,2024,February,8,24,2024-02-24,0,1,2,0.0,1,BB,ARG,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,196.0,,0,Transient,36.0,1,1
HB-083029,City Hotel,0,2,2024,January,2,14,2024-01-14,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient-Party,66.0,0,0
HB-080614,City Hotel,1,12,2023,November,47,23,2023-11-23,1,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Contract,101.0,0,1
HB-011569,Resort Hotel,1,107,2025,May,20,17,2025-05-17,2,5,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,147.0,0,0
HB-056616,City Hotel,1,178,2024,September,37,9,2024-09-09,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,135.0,0,0
HB-040689,City Hotel,0,34,2023,August,31,5,2023-08-05,0,2,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-018105,Resort Hotel,0,0,2023,November,44,4,2023-11-04,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,1,No Deposit,,,0,Transient-Party,40.0,0,0
HB-099642,City Hotel,0,377,2024,October,42,14,2024-10-14,0,2,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,90.0,0,0
HB-099705,City Hotel,0,377,2024,October,42,14,2024-10-14,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,B,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-064833,City Hotel,1,16,2025,March,12,17,2025-03-17,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient,75.0,0,0
HB-026644,Resort Hotel,0,117,2024,August,31,1,2024-08-01,1,5,2,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,253.0,1,1
HB-065837,City Hotel,1,28,2025,April,15,9,2025-04-09,2,0,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,0
HB-079516,City Hotel,0,18,2023,October,43,26,2023-10-26,1,1,1,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Group,77.0,0,1
HB-042061,City Hotel,1,104,2023,August,35,30,2023-08-30,2,1,2,0.0,0,HB,ESP,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,90.0,0,0
HB-053804,City Hotel,1,358,2024,June,26,30,2024-06-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-077643,City Hotel,0,3,2023,September,38,21,2023-09-21,1,2,1,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,133.0,0,2
HB-101597,City Hotel,0,21,2024,November,46,11,2024-11-11,2,2,2,1.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,121.2,0,2
HB-068725,City Hotel,1,420,2025,May,21,20,2025-05-20,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-004250,Resort Hotel,1,44,2024,February,9,27,2024-02-27,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,2
HB-099213,City Hotel,0,180,2024,October,41,10,2024-10-10,1,2,1,0.0,0,BB,USA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,234.0,,0,Group,120.0,0,0
HB-114358,City Hotel,0,53,2025,June,25,18,2025-06-18,2,1,1,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,150.0,0,2
HB-001127,Resort Hotel,1,80,2023,August,33,15,2023-08-15,2,3,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,133.0,0,1
HB-025835,Resort Hotel,0,245,2025,June,25,22,2025-06-22,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,1,0,0,D,D,0,No Deposit,243.0,,0,Contract,84.8,0,1
HB-107706,City Hotel,0,55,2025,March,11,16,2025-03-16,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,94.0,,0,Transient-Party,65.0,0,1
HB-056321,City Hotel,1,420,2024,September,36,3,2024-09-03,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,35.0,,0,Transient,75.0,0,0
HB-106278,City Hotel,0,48,2025,February,8,22,2025-02-22,0,2,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,65.0,0,1
HB-092600,City Hotel,0,93,2024,July,27,5,2024-07-05,0,4,2,0.0,0,SC,NOR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,78.85,0,0
HB-054247,City Hotel,1,165,2024,July,28,10,2024-07-10,1,0,2,0.0,0,SC,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,103.5,0,1
HB-035102,Resort Hotel,0,13,2025,April,15,9,2025-04-09,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,196.0,,0,Transient-Party,117.0,0,1
HB-013723,Resort Hotel,1,216,2025,August,35,27,2025-08-27,2,5,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,175.0,,0,Transient,139.68,0,0
HB-104238,City Hotel,0,0,2025,January,2,7,2025-01-07,1,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,83.75,0,0
HB-108707,City Hotel,0,0,2025,March,13,30,2025-03-30,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,F,0,No Deposit,14.0,,0,Transient,104.0,0,0
HB-006483,Resort Hotel,1,149,2024,June,24,12,2024-06-12,2,5,2,0.0,1,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,108.9,0,2
HB-085496,City Hotel,0,23,2024,March,11,16,2024-03-16,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,80.0,0,0
HB-044013,City Hotel,0,68,2023,September,39,29,2023-09-29,0,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,20.0,,0,Transient-Party,65.0,0,0
HB-086502,City Hotel,0,86,2024,March,13,30,2024-03-30,1,4,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,B,B,0,No Deposit,,,0,Transient,71.19,0,1
HB-063434,City Hotel,1,67,2025,February,7,12,2025-02-12,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,80.0,0,0
HB-005519,Resort Hotel,1,171,2024,April,18,30,2024-04-30,4,10,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,65.7,0,2
HB-105446,City Hotel,0,57,2025,February,6,5,2025-02-05,2,2,1,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,51.05,0,1
HB-064001,City Hotel,1,127,2025,February,9,26,2025-02-26,1,0,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.6,0,2
HB-095025,City Hotel,0,140,2024,August,32,9,2024-08-09,0,5,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,A,0,No Deposit,85.0,,0,Transient,82.45,0,0
HB-050903,City Hotel,0,286,2024,May,19,11,2024-05-11,0,4,2,0.0,0,BB,AUT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,176,Transient-Party,99.0,0,1
HB-019100,Resort Hotel,0,0,2023,December,49,7,2023-12-07,1,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient-Party,38.4,0,0
HB-070689,City Hotel,1,32,2025,June,25,21,2025-06-21,0,2,2,0.0,0,SC,KOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,1
HB-092844,City Hotel,0,6,2024,July,28,11,2024-07-11,1,1,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,9.0,,0,Transient,166.0,0,1
HB-045160,City Hotel,0,66,2023,October,42,19,2023-10-19,1,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,89.25,0,2
HB-023322,Resort Hotel,0,56,2024,April,16,15,2024-04-15,2,5,2,0.0,0,HB,NLD,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,71.0,,0,Contract,59.5,0,0
HB-021910,Resort Hotel,0,44,2024,March,11,12,2024-03-12,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,2
HB-098050,City Hotel,0,150,2024,September,38,18,2024-09-18,2,5,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,89.0,,0,Transient,91.12,0,0
HB-007897,Resort Hotel,1,345,2024,September,35,1,2024-09-01,2,7,2,0.0,2,BB,PRT,Online TA,TA/TO,0,0,0,G,G,2,No Deposit,240.0,,0,Transient,145.0,0,1
HB-046089,City Hotel,1,106,2023,December,49,9,2023-12-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,57,Transient,75.0,0,0
HB-068675,City Hotel,1,165,2025,May,21,19,2025-05-19,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,225.0,0,0
HB-014009,Resort Hotel,0,1,2024,January,1,6,2024-01-06,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,10,A,E,1,No Deposit,,204.0,0,Transient,26.0,0,0
HB-061399,City Hotel,1,51,2024,December,50,9,2024-12-09,0,2,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,79.2,0,1
HB-016131,Resort Hotel,0,108,2023,August,32,11,2023-08-11,0,5,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,108.92,0,3
HB-080830,City Hotel,0,63,2023,November,47,23,2023-11-23,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Transient,60.0,0,0
HB-049604,City Hotel,0,136,2024,April,16,15,2024-04-15,2,2,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,89.25,0,0
HB-100142,City Hotel,0,192,2024,October,43,21,2024-10-21,0,2,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,29.0,,0,Transient-Party,95.0,0,0
HB-038617,Resort Hotel,0,179,2025,July,29,18,2025-07-18,1,5,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,117.43,0,0
HB-049826,City Hotel,0,270,2024,April,16,20,2024-04-20,0,4,2,0.0,0,BB,ISL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,187,Transient-Party,80.0,0,0
HB-107919,City Hotel,0,81,2025,March,12,17,2025-03-17,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,97.2,0,1
HB-071180,City Hotel,1,120,2025,June,26,29,2025-06-29,0,1,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,3,No Deposit,9.0,,0,Transient,126.0,0,1
HB-114859,City Hotel,0,31,2025,June,26,27,2025-06-27,0,1,1,0.0,0,BB,JPN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,2
HB-030174,Resort Hotel,0,29,2024,November,46,15,2024-11-15,0,1,1,0.0,0,BB,FRA,Groups,Corporate,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,48.0,0,0
HB-101636,City Hotel,0,74,2024,November,45,10,2024-11-10,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,155.0,,0,Transient,124.6,0,1
HB-012750,Resort Hotel,1,125,2025,July,29,15,2025-07-15,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,160.0,0,0
HB-029461,Resort Hotel,0,63,2024,October,43,25,2024-10-25,0,4,1,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,49.0,0,0
HB-008906,Resort Hotel,0,385,2024,October,42,19,2024-10-19,1,4,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,55.0,1,0
HB-030725,Resort Hotel,0,0,2024,December,48,1,2024-12-01,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,F,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-097555,City Hotel,0,286,2024,September,38,16,2024-09-16,0,2,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,44,Transient-Party,117.0,0,0
HB-119158,City Hotel,0,31,2025,August,35,28,2025-08-28,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,170.0,0,1
HB-051793,City Hotel,1,323,2024,May,21,26,2024-05-26,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-089940,City Hotel,0,5,2024,May,22,29,2024-05-29,1,0,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,258.0,0,Transient,99.0,0,0
HB-102213,City Hotel,0,8,2024,November,47,23,2024-11-23,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,75.2,0,0
HB-072869,City Hotel,1,169,2025,August,32,8,2025-08-08,0,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.5,0,0
HB-084862,City Hotel,0,1,2024,March,10,4,2024-03-04,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,G,G,0,No Deposit,,,0,Transient,70.0,0,1
HB-045683,City Hotel,0,140,2023,November,46,18,2023-11-18,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,29.0,,87,Transient-Party,75.0,0,1
HB-053300,City Hotel,1,290,2024,June,25,17,2024-06-17,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,108,Transient-Party,72.0,0,0
HB-004457,Resort Hotel,1,45,2024,March,12,19,2024-03-19,2,1,2,2.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,C,C,0,No Deposit,314.0,,0,Transient,65.65,0,0
HB-060955,City Hotel,1,5,2024,November,48,27,2024-11-27,2,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,89.89,0,3
HB-057732,City Hotel,1,315,2024,September,40,30,2024-09-30,1,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,69,Transient,160.0,0,0
HB-098045,City Hotel,0,19,2024,September,38,22,2024-09-22,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,169.0,0,2
HB-060216,City Hotel,1,277,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-095784,City Hotel,0,169,2024,August,34,22,2024-08-22,1,1,3,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,A,B,1,No Deposit,9.0,,0,Transient-Party,137.7,0,0
HB-004856,Resort Hotel,0,171,2024,April,14,4,2024-04-04,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,298.0,,0,Transient-Party,85.0,0,0
HB-083846,City Hotel,0,12,2024,February,7,13,2024-02-13,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,125.0,0,1
HB-044892,City Hotel,1,193,2023,October,41,15,2023-10-15,0,3,2,0.0,0,BB,,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,0,Transient,65.0,0,0
HB-022737,Resort Hotel,0,24,2024,March,13,28,2024-03-28,2,5,1,0.0,0,HB,LUX,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,,,0,Transient-Party,58.0,0,0
HB-102163,City Hotel,0,35,2024,November,47,23,2024-11-23,0,1,1,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,2
HB-009878,Resort Hotel,1,40,2025,January,3,16,2025-01-16,1,2,1,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,55.0,0,0
HB-037623,Resort Hotel,0,0,2025,June,26,23,2025-06-23,0,1,2,0.0,0,BB,SWE,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,138.0,0,0
HB-082952,City Hotel,0,11,2024,January,1,4,2024-01-04,1,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,70.0,0,0
HB-032217,Resort Hotel,0,40,2025,January,3,16,2025-01-16,1,2,1,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,A,F,3,No Deposit,,,0,Transient-Party,27.5,0,0
HB-056384,City Hotel,1,62,2024,September,36,4,2024-09-04,2,2,0,2.0,0,BB,USA,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient,96.23,0,0
HB-088643,City Hotel,0,2,2024,May,19,9,2024-05-09,1,0,1,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.0,0,1
HB-106424,City Hotel,0,68,2025,February,8,20,2025-02-20,1,4,2,0.0,0,BB,BGR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.1,0,2
HB-007062,Resort Hotel,1,93,2024,July,29,18,2024-07-18,2,5,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,192.0,0,0
HB-112181,City Hotel,0,105,2025,May,21,19,2025-05-19,0,2,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,3,No Deposit,9.0,,0,Transient,261.0,1,0
HB-060364,City Hotel,1,277,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-039486,Resort Hotel,0,207,2025,August,33,14,2025-08-14,1,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,173.45,1,2
HB-018507,Resort Hotel,0,4,2023,November,47,20,2023-11-20,0,2,2,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,58.0,0,1
HB-051995,City Hotel,1,135,2024,May,22,28,2024-05-28,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,96.0,0,0
HB-112045,City Hotel,0,33,2025,May,20,16,2025-05-16,0,3,2,2.0,0,BB,CN,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,244.0,0,0
HB-009135,Resort Hotel,0,18,2024,October,44,29,2024-10-29,0,1,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,44.0,1,0
HB-086124,City Hotel,0,81,2024,March,13,25,2024-03-25,1,2,3,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,D,2,No Deposit,3.0,,4,Transient-Party,94.0,0,0
HB-099133,City Hotel,0,349,2024,October,40,4,2024-10-04,1,5,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,58.0,,162,Transient-Party,90.0,0,0
HB-086504,City Hotel,0,36,2024,April,14,2,2024-04-02,1,1,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.9,0,2
HB-044056,City Hotel,0,83,2023,September,39,30,2023-09-30,0,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,26.0,,77,Transient-Party,112.2,0,0
HB-024704,Resort Hotel,0,59,2024,May,22,29,2024-05-29,2,0,3,0.0,0,BB,USA,Direct,Direct,0,0,0,G,G,3,No Deposit,250.0,,0,Transient,145.0,0,0
HB-109536,City Hotel,0,63,2025,April,15,7,2025-04-07,2,4,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.0,0,2
HB-006398,Resort Hotel,1,151,2024,June,23,7,2024-06-07,4,10,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,85.5,0,1
HB-100975,City Hotel,0,64,2024,November,44,1,2024-11-01,0,4,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,126.0,0,1
HB-043183,City Hotel,1,76,2023,September,37,16,2023-09-16,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-082993,City Hotel,0,21,2024,January,1,4,2024-01-04,1,5,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,92.0,0,0
HB-077486,City Hotel,1,11,2023,September,39,26,2023-09-26,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Contract,212.0,0,1
HB-032952,Resort Hotel,0,16,2025,February,6,7,2025-02-07,0,4,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,68.0,0,1
HB-109301,City Hotel,0,86,2025,April,14,4,2025-04-04,0,5,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,100.48,0,2
HB-081614,City Hotel,0,0,2023,December,50,14,2023-12-14,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,2,No Deposit,,,0,Transient,89.0,0,0
HB-011833,Resort Hotel,1,1,2025,June,22,1,2025-06-01,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,90.0,0,0
HB-039722,Resort Hotel,0,324,2025,August,33,13,2025-08-13,4,10,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Contract,134.85,0,0
HB-064183,City Hotel,1,28,2025,March,9,2,2025-03-02,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,95.0,0,0
HB-047866,City Hotel,1,56,2024,March,10,6,2024-03-06,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,82.45,0,0
HB-024591,Resort Hotel,0,141,2024,May,21,25,2024-05-25,0,1,2,0.0,0,BB,NOR,Offline TA/TO,TA/TO,0,0,0,D,E,0,No Deposit,251.0,,0,Transient-Party,59.0,0,1
HB-102043,City Hotel,0,41,2024,November,46,17,2024-11-17,2,3,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,E,E,3,No Deposit,14.0,,0,Transient,140.12,0,1
HB-046341,City Hotel,0,1,2023,December,52,30,2023-12-30,0,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.0,1,1
HB-051563,City Hotel,1,55,2024,May,21,21,2024-05-21,2,1,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,116.1,0,0
HB-091879,City Hotel,0,192,2024,June,26,24,2024-06-24,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,E,0,No Deposit,34.0,,0,Transient-Party,95.0,0,0
HB-104836,City Hotel,0,8,2025,January,3,19,2025-01-19,1,3,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.05,0,1
HB-116036,City Hotel,0,451,2025,July,28,12,2025-07-12,0,3,1,0.0,0,BB,AUS,Groups,TA/TO,0,0,0,A,A,1,No Deposit,229.0,,0,Transient-Party,91.33,0,1
HB-106286,City Hotel,0,48,2025,February,8,22,2025-02-22,0,2,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,65.0,0,1
HB-002021,Resort Hotel,0,163,2023,September,39,27,2023-09-27,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Contract,38.25,0,0
HB-049591,City Hotel,1,18,2024,April,16,15,2024-04-15,1,2,1,0.0,0,BB,ARE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,112.33,0,0
HB-083265,City Hotel,0,33,2024,January,4,25,2024-01-25,1,1,3,0.0,0,BB,ARG,Corporate,Corporate,0,0,0,A,D,1,No Deposit,38.0,,15,Transient-Party,95.0,0,1
HB-026834,Resort Hotel,0,107,2024,August,32,9,2024-08-09,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient-Party,221.0,0,2
HB-003212,Resort Hotel,0,78,2023,November,47,21,2023-11-21,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,E,0,No Deposit,,342.0,0,Transient-Party,32.0,0,0
HB-021323,Resort Hotel,0,0,2024,February,8,23,2024-02-23,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,34.4,0,0
HB-052605,City Hotel,1,63,2024,June,23,8,2024-06-08,0,3,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,159.3,0,0
HB-081909,City Hotel,1,181,2024,May,18,5,2024-05-05,2,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,26.0,,42,Transient,90.0,0,0
HB-026417,Resort Hotel,0,24,2024,July,31,29,2024-07-29,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,191.0,1,1
HB-019204,Resort Hotel,1,92,2024,February,9,26,2024-02-26,1,2,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,134.0,,0,Transient,79.0,0,0
HB-001399,Resort Hotel,0,31,2023,August,35,28,2023-08-28,0,2,2,2.0,0,BB,BRA,Direct,Direct,0,0,0,C,C,0,No Deposit,250.0,,0,Transient,181.0,1,2
HB-032837,Resort Hotel,0,17,2025,February,6,6,2025-02-06,1,0,1,0.0,0,BB,BRA,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,490.0,0,Transient,36.0,0,0
HB-110516,City Hotel,0,102,2025,April,17,24,2025-04-24,1,3,1,0.0,0,BB,IRL,Groups,TA/TO,0,0,0,A,A,1,No Deposit,,424.0,0,Transient-Party,90.0,0,0
HB-027890,Resort Hotel,0,54,2024,September,37,10,2024-09-10,2,2,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient,148.5,0,3
HB-048288,City Hotel,1,39,2024,March,12,20,2024-03-20,2,0,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,114.3,0,1
HB-095540,City Hotel,0,11,2024,August,33,13,2024-08-13,2,5,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,143.86,0,1
HB-042070,City Hotel,1,104,2023,August,35,30,2023-08-30,2,1,2,0.0,0,HB,ESP,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,90.0,0,0
HB-018439,Resort Hotel,0,14,2023,November,46,16,2023-11-16,1,3,3,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,106.57,0,2
HB-036967,Resort Hotel,0,9,2025,June,23,2,2025-06-02,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,79.8,1,1
HB-090682,City Hotel,0,40,2024,June,23,9,2024-06-09,0,1,2,0.0,0,BB,JPN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.9,0,1
HB-055258,City Hotel,1,86,2024,August,32,9,2024-08-09,0,2,2,1.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.69,0,1
HB-092317,City Hotel,0,158,2024,July,27,1,2024-07-01,1,2,2,2.0,0,BB,BEL,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,168.3,0,1
HB-089817,City Hotel,0,11,2024,May,21,25,2024-05-25,0,1,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,0
HB-071570,City Hotel,1,289,2025,July,28,7,2025-07-07,2,2,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,2
HB-052378,City Hotel,1,141,2024,June,23,4,2024-06-04,2,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.2,0,0
HB-046798,City Hotel,0,31,2024,January,3,19,2024-01-19,0,3,1,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,73.9,0,0
HB-019526,Resort Hotel,0,3,2023,December,52,25,2023-12-25,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,125.0,0,1
HB-111440,City Hotel,0,10,2025,May,19,7,2025-05-07,2,2,2,0.0,0,BB,AUT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,108.9,0,0
HB-099022,City Hotel,0,137,2024,October,40,3,2024-10-03,1,4,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,132.3,0,2
HB-065992,City Hotel,1,146,2025,April,15,12,2025-04-12,0,4,3,0.0,0,BB,CZE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,173.25,0,2
HB-051536,City Hotel,1,30,2024,May,21,21,2024-05-21,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,116.1,0,0
HB-009940,Resort Hotel,1,43,2025,January,5,27,2025-01-27,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,48.0,0,0
HB-036322,Resort Hotel,0,1,2025,May,20,16,2025-05-16,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,102.0,1,0
HB-030121,Resort Hotel,0,210,2024,November,45,10,2024-11-10,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,42.97,0,2
HB-045491,City Hotel,1,99,2023,October,44,30,2023-10-30,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,65.0,0,0
HB-058788,City Hotel,1,286,2024,October,42,16,2024-10-16,1,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,44.0,,0,Transient,90.0,0,0
HB-046605,City Hotel,0,7,2024,January,2,10,2024-01-10,2,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.0,0,1
HB-106832,City Hotel,0,24,2025,February,9,27,2025-02-27,1,4,1,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,108.8,0,2
HB-080609,City Hotel,0,57,2023,November,46,17,2023-11-17,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Transient,60.0,0,0
HB-020125,Resort Hotel,0,8,2024,January,3,15,2024-01-15,0,2,2,0.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient,55.0,0,0
HB-069258,City Hotel,1,132,2025,May,22,28,2025-05-28,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,28.0,,0,Transient,99.0,0,0
HB-087699,City Hotel,0,143,2024,April,17,22,2024-04-22,0,2,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,77.03,0,0
HB-004384,Resort Hotel,1,46,2024,March,11,11,2024-03-11,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,375.0,,0,Transient-Party,25.0,0,0
HB-118929,City Hotel,0,457,2025,August,35,25,2025-08-25,0,2,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,6.0,,0,Transient-Party,95.5,0,1
HB-023391,Resort Hotel,0,79,2024,April,17,22,2024-04-22,1,2,2,0.0,0,BB,USA,Direct,Direct,0,0,0,G,G,0,No Deposit,250.0,,0,Transient,117.0,0,0
HB-024171,Resort Hotel,0,468,2024,May,19,12,2024-05-12,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,E,0,No Deposit,249.0,,0,Transient-Party,67.0,0,0
HB-021296,Resort Hotel,0,0,2024,February,8,24,2024-02-24,0,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,241.0,,0,Transient,36.96,0,1
HB-064188,City Hotel,1,28,2025,March,9,2,2025-03-02,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,95.0,0,0
HB-056910,City Hotel,1,317,2024,September,37,15,2024-09-15,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,120.0,0,0
HB-019590,Resort Hotel,0,0,2023,December,52,27,2023-12-27,1,0,2,0.0,0,BB,USA,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,71.0,1,0
HB-070716,City Hotel,1,153,2025,June,25,21,2025-06-21,0,4,1,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,A,0,Non Refund,,348.0,0,Transient,110.0,0,0
HB-005630,Resort Hotel,1,119,2024,May,19,6,2024-05-06,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,65.7,0,1
HB-051623,City Hotel,0,141,2024,May,21,23,2024-05-23,1,0,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,72.76,0,1
HB-073107,City Hotel,1,201,2025,August,33,14,2025-08-14,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,52.0,,0,Transient,89.0,0,0
HB-090861,City Hotel,0,57,2024,June,24,10,2024-06-10,1,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,6.0,,0,Transient-Party,75.33,0,1
HB-090341,City Hotel,0,70,2024,June,23,3,2024-06-03,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,20.0,,0,Transient-Party,100.0,0,0
HB-087233,City Hotel,0,77,2024,April,15,14,2024-04-14,0,3,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,128.7,0,2
HB-052031,City Hotel,1,16,2024,May,22,29,2024-05-29,2,1,2,0.0,0,BB,CHN,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,112.33,0,1
HB-056105,City Hotel,1,28,2024,August,35,29,2024-08-29,1,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.33,0,0
HB-020730,Resort Hotel,0,28,2024,February,5,3,2024-02-03,2,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,59.0,1,1
HB-079517,City Hotel,0,12,2023,October,43,25,2023-10-25,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,D,0,No Deposit,37.0,,0,Transient-Party,85.67,0,0
HB-070704,City Hotel,1,153,2025,June,25,21,2025-06-21,0,4,1,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,A,0,Non Refund,,348.0,0,Transient,110.0,0,0
HB-005321,Resort Hotel,1,138,2024,April,17,25,2024-04-25,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,E,E,0,Non Refund,,,0,Transient,65.0,0,0
HB-067513,City Hotel,1,148,2025,May,18,4,2025-05-04,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,171.0,,0,Transient,95.0,0,0
HB-050741,City Hotel,1,38,2024,May,19,6,2024-05-06,2,3,2,1.0,0,HB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,149.68,0,0
HB-056712,City Hotel,1,79,2024,September,37,11,2024-09-11,2,0,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,168.3,0,0
HB-014081,Resort Hotel,0,1,2025,February,6,4,2025-02-04,1,1,2,0.0,0,BB,PRT,Direct,TA/TO,0,0,2,A,A,0,No Deposit,,,0,Transient,48.0,0,3
HB-089637,City Hotel,0,1,2024,May,21,23,2024-05-23,1,0,2,0.0,0,SC,GBR,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,149.0,0,0
HB-033506,Resort Hotel,0,28,2025,February,8,18,2025-02-18,2,5,2,0.0,0,FB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,87.0,1,0
HB-085959,City Hotel,0,151,2024,March,12,20,2024-03-20,2,3,2,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,121.0,,0,Transient,59.5,0,0
HB-100280,City Hotel,0,209,2024,October,43,21,2024-10-21,2,3,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.3,0,1
HB-102828,City Hotel,0,48,2024,December,49,4,2024-12-04,2,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,93.6,0,1
HB-107523,City Hotel,0,6,2025,March,11,13,2025-03-13,1,0,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,98.0,0,1
HB-062721,City Hotel,1,3,2025,January,3,19,2025-01-19,1,3,1,0.0,0,SC,NOR,Online TA,GDS,0,0,0,A,A,0,No Deposit,195.0,,0,Transient,78.0,0,0
HB-051184,City Hotel,0,139,2024,May,20,15,2024-05-15,2,1,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,F,1,No Deposit,9.0,,0,Transient-Party,105.3,0,0
HB-118123,City Hotel,0,187,2025,August,32,10,2025-08-10,2,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,168.0,,0,Transient,80.1,0,1
HB-032148,Resort Hotel,0,0,2025,January,3,18,2025-01-18,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,52.0,0,0
HB-072364,City Hotel,1,211,2025,July,30,27,2025-07-27,0,2,3,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,112.5,0,0
HB-078432,City Hotel,0,4,2023,October,40,6,2023-10-06,0,3,2,0.0,0,BB,TUR,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,82.0,,0,Transient-Party,90.0,0,1
HB-039940,Resort Hotel,0,30,2025,August,35,29,2025-08-29,0,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,196.5,1,2
HB-019954,Resort Hotel,0,0,2024,January,2,9,2024-01-09,1,1,2,0.0,0,BB,CHE,Direct,Direct,0,0,0,E,E,1,No Deposit,,,0,Transient,61.0,0,0
HB-077849,City Hotel,0,19,2023,September,39,28,2023-09-28,1,0,1,0.0,0,BB,CHE,Groups,TA/TO,0,0,0,A,B,1,No Deposit,1.0,,0,Transient-Party,170.0,0,0
HB-117499,City Hotel,0,175,2025,August,31,1,2025-08-01,0,4,2,2.0,0,BB,FRA,Direct,Direct,0,0,0,G,G,0,No Deposit,,,0,Transient,260.0,0,1
HB-072015,City Hotel,1,263,2025,July,29,17,2025-07-17,1,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,1
HB-113130,City Hotel,0,409,2025,May,22,31,2025-05-31,0,3,2,0.0,0,BB,AUS,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,1
HB-038619,Resort Hotel,0,8,2025,July,30,21,2025-07-21,1,2,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,240.0,,0,Transient,220.4,1,2
HB-110881,City Hotel,0,144,2025,April,17,27,2025-04-27,2,4,2,0.0,0,BB,NLD,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,124.5,0,0
HB-037864,Resort Hotel,0,272,2025,June,26,24,2025-06-24,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,80.1,0,1
HB-096973,City Hotel,0,183,2024,September,36,8,2024-09-08,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,44.0,,0,Transient-Party,110.0,0,1
HB-038841,Resort Hotel,0,161,2025,July,31,28,2025-07-28,1,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,177.0,,0,Transient,155.0,0,0
HB-010821,Resort Hotel,1,175,2025,April,14,6,2025-04-06,0,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,C,1,No Deposit,240.0,,0,Transient,60.0,0,0
HB-109542,City Hotel,0,14,2025,April,15,12,2025-04-12,0,1,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,224.0,0,0
HB-018516,Resort Hotel,0,5,2023,November,47,21,2023-11-21,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,F,0,No Deposit,240.0,,0,Transient,58.0,0,1
HB-108782,City Hotel,0,70,2025,March,13,30,2025-03-30,0,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,75.93,0,1
HB-003173,Resort Hotel,0,36,2023,November,47,20,2023-11-20,0,2,2,0.0,0,FB,ESP,Groups,TA/TO,0,0,0,A,C,0,No Deposit,38.0,,0,Transient-Party,64.0,0,0
HB-002627,Resort Hotel,1,148,2023,October,43,24,2023-10-24,0,1,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,47.0,0,0
HB-010629,Resort Hotel,1,350,2025,March,13,24,2025-03-24,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,11.0,,0,Transient,30.0,0,0
HB-023512,Resort Hotel,0,73,2024,April,18,29,2024-04-29,0,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,C,6,No Deposit,241.0,,0,Transient,0.0,0,1
HB-063167,City Hotel,1,56,2025,February,5,1,2025-02-01,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,60.0,0,0
HB-065120,City Hotel,1,37,2025,March,13,24,2025-03-24,3,7,2,2.0,0,BB,BRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,210.4,0,1
HB-114945,City Hotel,0,15,2025,June,26,27,2025-06-27,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,99.0,0,0
HB-075246,City Hotel,1,297,2023,August,32,10,2023-08-10,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-061179,City Hotel,1,15,2024,December,49,3,2024-12-03,2,1,2,0.0,0,HB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.0,0,0
HB-116686,City Hotel,0,280,2025,July,29,18,2025-07-18,1,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,107.1,0,4
HB-019614,Resort Hotel,0,131,2023,December,51,22,2023-12-22,2,5,2,0.0,0,HB,IRL,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,314.0,,0,Transient-Party,75.57,0,1
HB-065953,City Hotel,1,114,2025,April,15,10,2025-04-10,1,5,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,106.5,0,2
HB-003806,Resort Hotel,1,1,2024,January,2,9,2024-01-09,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,39.0,0,1
HB-071154,City Hotel,1,215,2025,June,26,28,2025-06-28,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-029079,Resort Hotel,0,25,2024,October,42,16,2024-10-16,2,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,40.0,0,0
HB-113504,City Hotel,0,104,2025,June,23,5,2025-06-05,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,354.0,,0,Transient-Party,139.4,0,0
HB-084709,City Hotel,0,0,2024,March,9,1,2024-03-01,0,2,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.0,0,1
HB-024822,Resort Hotel,0,34,2024,June,22,2,2024-06-02,0,3,2,0.0,0,BB,USA,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,157.0,0,0
HB-100054,City Hotel,0,87,2024,October,43,23,2024-10-23,2,1,3,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,141.9,0,0
HB-060031,City Hotel,1,305,2024,November,45,4,2024-11-04,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,89.0,0,0
HB-098837,City Hotel,0,37,2024,October,40,2,2024-10-02,2,1,3,0.0,0,BB,MAR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,158.4,0,1
HB-018866,Resort Hotel,0,0,2023,November,48,30,2023-11-30,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,1,No Deposit,,195.0,0,Transient,35.0,0,0
HB-085261,City Hotel,0,35,2024,March,10,9,2024-03-09,0,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,38.67,0,0
HB-118129,City Hotel,0,504,2025,August,33,12,2025-08-12,2,1,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,1
HB-088088,City Hotel,0,142,2024,April,18,29,2024-04-29,0,2,2,0.0,0,BB,ITA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,65.0,0,1
HB-088718,City Hotel,0,1,2024,May,19,9,2024-05-09,1,1,2,2.0,0,BB,NLD,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,9.0,,0,Transient,183.0,0,0
HB-058297,City Hotel,1,111,2024,October,41,10,2024-10-10,1,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,234.0,,0,Transient-Party,120.0,0,0
HB-039467,Resort Hotel,0,6,2025,August,33,17,2025-08-17,0,2,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,230.0,0,0
HB-005672,Resort Hotel,0,235,2024,May,19,9,2024-05-09,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,65.7,0,2
HB-045489,City Hotel,1,99,2023,October,44,30,2023-10-30,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,65.0,0,0
HB-084689,City Hotel,0,116,2024,February,9,28,2024-02-28,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,B,0,No Deposit,134.0,,0,Transient-Party,76.0,0,0
HB-058521,City Hotel,1,461,2024,October,41,13,2024-10-13,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-015489,Resort Hotel,0,133,2023,July,28,13,2023-07-13,3,5,2,0.0,0,BB,FIN,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,156.0,,0,Contract,142.63,0,1
HB-046589,City Hotel,0,17,2024,January,2,9,2024-01-09,1,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,155.0,,0,Transient,119.0,0,1
HB-059409,City Hotel,1,464,2024,October,44,28,2024-10-28,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,391,Transient,65.0,0,0
HB-099364,City Hotel,0,181,2024,October,41,11,2024-10-11,0,2,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,B,0,No Deposit,234.0,,0,Transient-Party,120.0,0,0
HB-030397,Resort Hotel,0,67,2024,November,47,18,2024-11-18,1,2,1,0.0,0,HB,ESP,Groups,TA/TO,0,0,0,A,A,1,No Deposit,411.0,,0,Transient-Party,0.0,0,0
HB-019012,Resort Hotel,0,16,2023,December,49,5,2023-12-05,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,2,No Deposit,,,0,Transient,68.0,1,0
HB-018152,Resort Hotel,0,4,2023,November,45,6,2023-11-06,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,68.5,0,1
HB-093768,City Hotel,0,40,2024,July,30,26,2024-07-26,0,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,B,0,No Deposit,39.0,,0,Transient-Party,125.0,0,1
HB-016162,Resort Hotel,0,220,2023,August,32,10,2023-08-10,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,40.0,,0,Contract,112.63,0,0
HB-049759,City Hotel,1,103,2024,April,16,19,2024-04-19,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,0,Transient,115.0,0,0
HB-062626,City Hotel,1,55,2025,January,3,18,2025-01-18,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,79.0,0,0
HB-004956,Resort Hotel,0,275,2024,April,15,10,2024-04-10,2,5,2,0.0,0,HB,GBR,Groups,Direct,0,0,0,D,D,0,No Deposit,273.0,,0,Transient-Party,72.45,0,0
HB-115991,City Hotel,0,73,2025,July,28,11,2025-07-11,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,K,5,No Deposit,,,23,Transient,80.0,0,1
HB-016032,Resort Hotel,0,6,2023,August,31,6,2023-08-06,2,4,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,217.83,0,3
HB-037671,Resort Hotel,0,134,2025,June,25,21,2025-06-21,0,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,F,1,No Deposit,250.0,,0,Transient,141.67,0,2
HB-031523,Resort Hotel,0,96,2024,December,52,24,2024-12-24,2,5,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,56.63,0,0
HB-083601,City Hotel,0,2,2024,February,6,6,2024-02-06,1,1,2,0.0,0,BB,HRV,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,102.0,1,1
HB-031974,Resort Hotel,0,11,2025,January,2,9,2025-01-09,1,3,1,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,171.0,,0,Transient,30.0,0,0
HB-092452,City Hotel,0,77,2024,July,27,5,2024-07-05,0,2,2,0.0,0,SC,AUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,1
HB-000703,Resort Hotel,1,85,2023,July,30,25,2023-07-25,4,10,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Contract,107.0,0,0
HB-005940,Resort Hotel,1,151,2024,May,20,17,2024-05-17,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,46.0,0,0
HB-031865,Resort Hotel,0,95,2025,January,2,8,2025-01-08,1,0,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,242.0,,0,Transient,37.8,0,1
HB-110182,City Hotel,0,133,2025,April,16,19,2025-04-19,0,4,2,0.0,0,BB,ISL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,390.0,,0,Transient-Party,124.0,0,0
HB-074267,City Hotel,1,281,2023,July,30,25,2023-07-25,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-034863,Resort Hotel,0,15,2025,March,13,30,2025-03-30,2,6,2,0.0,0,Undefined,PRT,Corporate,Corporate,0,0,0,A,D,1,No Deposit,,523.0,0,Transient-Party,120.0,0,0
HB-116220,City Hotel,0,11,2025,July,29,15,2025-07-15,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,106.24,0,3
HB-114236,City Hotel,0,173,2025,June,25,17,2025-06-17,1,1,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,83.0,,0,Transient,133.2,0,0
HB-108978,City Hotel,0,6,2025,April,14,2,2025-04-02,2,1,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,224.0,0,0
HB-041360,City Hotel,1,5,2023,August,33,15,2023-08-15,1,1,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Contract,162.0,0,1
HB-116657,City Hotel,0,16,2025,July,30,21,2025-07-21,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,139.0,0,1
HB-037434,Resort Hotel,0,236,2025,June,24,11,2025-06-11,2,5,1,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient,54.0,0,1
HB-013443,Resort Hotel,1,39,2025,August,33,15,2025-08-15,1,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,230.0,0,1
HB-057043,City Hotel,1,5,2024,September,38,17,2024-09-17,0,1,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,159.0,0,1
HB-092798,City Hotel,0,102,2024,July,28,8,2024-07-08,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,72.25,0,0
HB-039503,Resort Hotel,0,201,2025,August,33,13,2025-08-13,2,5,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,69.0,,0,Transient,121.5,0,0
HB-038897,Resort Hotel,0,58,2025,July,31,28,2025-07-28,2,3,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,242.0,0,2
HB-026102,Resort Hotel,0,38,2024,July,29,21,2024-07-21,0,1,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,179.0,1,1
HB-030248,Resort Hotel,0,14,2024,November,46,17,2024-11-17,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient,30.0,0,0
HB-077363,City Hotel,1,19,2023,October,40,6,2023-10-06,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,1,1,0,A,A,0,Non Refund,82.0,,0,Transient,80.0,0,0
HB-023196,Resort Hotel,0,23,2024,April,16,15,2024-04-15,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,240.0,,0,Transient,75.0,0,1
HB-112399,City Hotel,0,11,2025,May,21,23,2025-05-23,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,157.0,,0,Transient,104.0,0,0
HB-035873,Resort Hotel,0,0,2025,May,18,3,2025-05-03,0,1,1,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,62.0,0,1
HB-067304,City Hotel,1,46,2025,May,18,1,2025-05-01,1,3,1,1.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,3,No Deposit,9.0,,0,Transient,153.09,0,0
HB-065829,City Hotel,1,66,2025,April,15,9,2025-04-09,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-040840,City Hotel,1,1,2023,August,32,8,2023-08-08,1,1,2,0.0,0,SC,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,50.8,0,0
HB-041005,City Hotel,0,0,2023,August,32,10,2023-08-10,1,3,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,9.0,0,Transient,114.0,0,0
HB-105025,City Hotel,0,0,2025,January,4,25,2025-01-25,0,3,1,0.0,0,BB,CHN,Online TA,Corporate,0,0,0,B,B,0,No Deposit,,120.0,0,Transient,93.0,0,0
HB-078328,City Hotel,0,7,2024,November,45,9,2024-11-09,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,3,20,A,A,0,No Deposit,,40.0,0,Transient,67.0,1,0
HB-047616,City Hotel,1,1,2024,February,9,28,2024-02-28,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,60.0,0,0
HB-033413,Resort Hotel,0,36,2025,February,7,16,2025-02-16,2,5,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,A,C,1,No Deposit,250.0,,0,Transient,39.6,0,0
HB-084107,City Hotel,0,99,2024,February,8,19,2024-02-19,0,1,1,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,D,0,No Deposit,,67.0,0,Transient-Party,81.0,0,0
HB-069366,City Hotel,1,186,2025,May,22,30,2025-05-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,130.0,0,0
HB-031193,Resort Hotel,0,1,2024,December,51,17,2024-12-17,0,1,1,0.0,0,BB,NLD,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,39.0,1,1
HB-071490,City Hotel,1,175,2025,July,27,6,2025-07-06,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,117.9,0,0
HB-028107,Resort Hotel,0,1,2024,September,38,20,2024-09-20,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,282.0,,0,Transient-Party,65.0,0,0
HB-066405,City Hotel,1,195,2025,April,16,19,2025-04-19,0,4,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,1
HB-072121,City Hotel,1,14,2025,July,30,21,2025-07-21,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,139.33,0,0
HB-019399,Resort Hotel,0,11,2023,December,50,13,2023-12-13,2,2,1,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,42.9,1,1
HB-103393,City Hotel,0,1,2024,December,51,21,2024-12-21,0,1,2,0.0,0,BB,PRT,Complementary,TA/TO,0,0,0,D,D,0,No Deposit,17.0,,0,Transient,0.0,0,1
HB-117205,City Hotel,0,296,2025,July,30,27,2025-07-27,1,3,0,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,B,A,0,No Deposit,9.0,,0,Transient,98.85,0,1
HB-096026,City Hotel,0,158,2024,August,34,25,2024-08-25,0,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.5,0,0
HB-093158,City Hotel,0,184,2024,July,29,16,2024-07-16,1,1,2,0.0,0,HB,ITA,Groups,TA/TO,0,0,0,A,B,1,No Deposit,1.0,,0,Transient-Party,125.0,0,1
HB-117390,City Hotel,0,144,2025,August,31,1,2025-08-01,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.5,0,1
HB-082823,City Hotel,1,68,2024,February,7,17,2024-02-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,37.0,,0,Transient,75.0,0,0
HB-053404,City Hotel,1,31,2024,June,25,20,2024-06-20,1,1,2,0.0,0,BB,KOR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,162.35,0,0
HB-056386,City Hotel,1,69,2024,September,36,4,2024-09-04,2,3,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.9,0,1
HB-072779,City Hotel,1,103,2025,August,32,6,2025-08-06,2,0,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,E,E,3,No Deposit,9.0,,0,Transient,234.0,0,1
HB-016686,Resort Hotel,0,0,2023,September,36,6,2023-09-06,1,0,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,C,0,No Deposit,,,0,Transient,131.0,1,0
HB-033601,Resort Hotel,0,2,2025,February,9,26,2025-02-26,1,0,2,0.0,0,HB,ESP,Direct,Direct,0,0,0,A,A,3,No Deposit,250.0,,0,Transient,99.0,1,0
HB-112272,City Hotel,0,83,2025,May,21,19,2025-05-19,1,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,1
HB-085773,City Hotel,0,64,2024,March,12,19,2024-03-19,1,1,2,2.0,0,BB,PRT,Direct,Direct,0,0,0,E,F,0,No Deposit,,,0,Transient,159.6,0,2
HB-019238,Resort Hotel,1,92,2024,February,9,26,2024-02-26,1,2,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,134.0,,0,Transient,79.0,0,0
HB-006356,Resort Hotel,1,2,2024,June,23,5,2024-06-05,1,0,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient,109.0,0,1
HB-088732,City Hotel,0,1,2024,May,19,11,2024-05-11,0,1,1,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,159.0,,0,Transient,135.0,0,0
HB-091425,City Hotel,0,92,2024,June,24,14,2024-06-14,2,5,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,120.58,0,0
HB-021289,Resort Hotel,0,0,2024,February,8,20,2024-02-20,2,3,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-019575,Resort Hotel,0,23,2023,December,50,16,2023-12-16,3,9,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,53.9,0,1
HB-027428,Resort Hotel,0,39,2024,August,34,21,2024-08-21,3,5,2,0.0,0,HB,IRL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,270.38,0,2
HB-088064,City Hotel,0,14,2024,April,18,29,2024-04-29,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,65.0,0,0
HB-118836,City Hotel,0,152,2025,August,34,20,2025-08-20,2,4,2,1.0,0,BB,CYP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,148.5,0,2
HB-112776,City Hotel,0,1,2025,May,22,26,2025-05-26,0,2,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,B,B,1,No Deposit,14.0,,0,Transient,179.5,0,0
HB-075120,City Hotel,1,344,2023,September,39,26,2023-09-26,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-024001,Resort Hotel,0,45,2024,May,19,8,2024-05-08,2,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,393.0,,0,Transient-Party,64.6,1,1
HB-024123,Resort Hotel,0,236,2024,May,19,12,2024-05-12,0,3,2,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,C,0,No Deposit,315.0,,0,Transient-Party,48.0,0,0
HB-060824,City Hotel,1,44,2024,November,47,23,2024-11-23,0,2,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,83.6,0,2
HB-052004,City Hotel,1,153,2024,May,22,28,2024-05-28,2,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,121.5,0,1
HB-097883,City Hotel,0,82,2024,September,37,13,2024-09-13,2,7,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,149.4,0,3
HB-084603,City Hotel,0,28,2024,February,9,26,2024-02-26,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,70.04,0,1
HB-113490,City Hotel,0,30,2025,June,23,6,2025-06-06,0,2,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,1
HB-100056,City Hotel,0,2,2024,October,42,19,2024-10-19,0,4,1,0.0,0,SC,IND,Online TA,GDS,0,0,0,A,A,0,No Deposit,195.0,,0,Transient,134.0,0,0
HB-000515,Resort Hotel,0,44,2023,July,29,18,2023-07-18,2,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,1,No Deposit,250.0,,0,Transient,145.0,0,0
HB-019929,Resort Hotel,0,10,2024,January,1,5,2024-01-05,0,5,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,44.8,0,1
HB-093732,City Hotel,0,188,2024,July,30,22,2024-07-22,2,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,79.0,,0,Transient,72.76,0,2
HB-055053,City Hotel,1,391,2024,August,31,4,2024-08-04,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,59.0,0,0
HB-046102,City Hotel,1,106,2023,December,49,9,2023-12-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,57,Transient,75.0,0,0
HB-056899,City Hotel,1,317,2024,September,37,15,2024-09-15,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,120.0,0,0
HB-079260,City Hotel,1,444,2024,December,48,1,2024-12-01,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,34.0,,39,Transient,75.0,0,0
HB-101976,City Hotel,0,31,2024,November,46,14,2024-11-14,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,64.67,0,1
HB-039217,Resort Hotel,0,264,2025,August,32,7,2025-08-07,1,4,2,1.0,0,BB,CHE,Direct,Direct,0,0,0,G,G,0,No Deposit,250.0,,0,Transient,231.6,1,1
HB-005741,Resort Hotel,1,236,2024,May,19,12,2024-05-12,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,315.0,,0,Transient-Party,48.0,0,0
HB-011638,Resort Hotel,1,8,2025,May,21,23,2025-05-23,0,2,2,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,0.0,0,0
HB-002285,Resort Hotel,1,94,2023,October,40,8,2023-10-08,2,7,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,123.56,0,1
HB-073564,City Hotel,1,134,2025,August,35,26,2025-08-26,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,425.0,,0,Transient,127.1,0,0
HB-113632,City Hotel,0,28,2025,June,23,5,2025-06-05,1,4,2,0.0,0,HB,BEL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,175.0,0,1
HB-044803,City Hotel,1,105,2023,October,41,12,2023-10-12,1,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,110.0,0,0
HB-091913,City Hotel,0,53,2024,June,26,24,2024-06-24,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,65.0,0,1
HB-073808,City Hotel,1,286,2023,July,30,30,2023-07-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-095368,City Hotel,0,194,2024,August,33,14,2024-08-14,2,2,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.05,0,2
HB-007490,Resort Hotel,1,13,2024,August,33,12,2024-08-12,0,2,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,291.0,0,0
HB-091476,City Hotel,0,93,2024,June,25,20,2024-06-20,1,1,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.9,0,1
HB-036694,Resort Hotel,0,251,2025,May,21,21,2025-05-21,2,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient-Party,96.67,0,2
HB-072428,City Hotel,1,147,2025,July,31,28,2025-07-28,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.5,0,1
HB-115791,City Hotel,0,170,2025,July,28,8,2025-07-08,2,1,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,9.0,,0,Transient-Party,152.1,0,1
HB-016091,Resort Hotel,0,269,2023,August,32,8,2023-08-08,2,5,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,166.0,1,1
HB-045510,City Hotel,1,100,2023,October,44,31,2023-10-31,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-030113,Resort Hotel,0,45,2024,November,45,9,2024-11-09,2,4,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,37.8,0,2
HB-019676,Resort Hotel,0,33,2023,December,52,28,2023-12-28,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,43.38,0,1
HB-036257,Resort Hotel,0,156,2025,May,19,8,2025-05-08,2,5,2,0.0,0,HB,IRL,Groups,TA/TO,0,0,0,E,E,0,No Deposit,434.0,,0,Transient-Party,102.0,0,0
HB-023465,Resort Hotel,0,36,2024,April,17,24,2024-04-24,2,0,1,0.0,0,BB,DNK,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,242.0,,0,Transient,81.0,1,1
HB-034104,Resort Hotel,0,195,2025,March,10,5,2025-03-05,2,5,2,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,D,D,0,No Deposit,273.0,,0,Transient-Party,67.94,0,0
HB-066444,City Hotel,1,125,2025,April,16,20,2025-04-20,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,33.0,,0,Transient,85.0,0,0
HB-023143,Resort Hotel,0,33,2024,April,15,9,2024-04-09,2,5,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,171.0,,0,Transient,36.53,0,0
HB-065281,City Hotel,1,56,2025,March,14,31,2025-03-31,0,1,2,1.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,124.2,0,0
HB-032315,Resort Hotel,0,65,2025,January,4,21,2025-01-21,0,1,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,G,G,1,No Deposit,240.0,,0,Transient,82.0,0,0
HB-075081,City Hotel,1,278,2023,July,29,22,2023-07-22,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-019716,Resort Hotel,0,61,2023,December,52,30,2023-12-30,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,150.0,0,0
HB-099632,City Hotel,0,335,2024,October,41,13,2024-10-13,0,3,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,80.0,0,0
HB-069636,City Hotel,1,43,2025,June,23,3,2025-06-03,0,1,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,7.0,,0,Transient,212.8,0,1
HB-095063,City Hotel,0,3,2024,August,33,13,2024-08-13,0,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,168.0,0,2
HB-078229,City Hotel,0,0,2023,October,40,5,2023-10-05,1,1,2,0.0,0,BB,CN,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,114.0,0,0
HB-041528,City Hotel,1,3,2023,August,33,17,2023-08-17,2,5,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,38.0,0,Transient,79.2,0,0
HB-047862,City Hotel,0,90,2024,March,10,6,2024-03-06,2,3,1,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient-Party,74.95,0,0
HB-000540,Resort Hotel,0,0,2023,July,29,19,2023-07-19,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Group,98.0,1,0
HB-065561,City Hotel,1,373,2025,April,14,5,2025-04-05,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-034961,Resort Hotel,0,152,2025,April,14,5,2025-04-05,0,4,1,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,2,No Deposit,,223.0,0,Transient-Party,42.0,0,0
HB-039070,Resort Hotel,0,0,2025,August,32,6,2025-08-06,1,0,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,205.0,0,0
HB-048563,City Hotel,1,161,2024,March,13,25,2024-03-25,1,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,101,Transient,130.0,0,0
HB-052032,City Hotel,1,30,2024,May,22,29,2024-05-29,2,1,1,0.0,0,BB,CHN,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,129.9,0,0
HB-007744,Resort Hotel,0,43,2024,August,34,24,2024-08-24,0,3,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,D,F,3,No Deposit,250.0,,0,Transient,239.1,1,0
HB-016462,Resort Hotel,0,198,2023,August,34,27,2023-08-27,0,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,E,F,0,No Deposit,240.0,,0,Transient,166.0,0,2
HB-022163,Resort Hotel,0,71,2024,March,11,17,2024-03-17,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,61.4,0,2
HB-060794,City Hotel,1,78,2024,November,47,21,2024-11-21,1,2,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.6,0,0
HB-082065,City Hotel,0,7,2024,December,50,9,2024-12-09,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-059626,City Hotel,1,150,2024,October,44,30,2024-10-30,2,0,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.1,0,0
HB-119234,City Hotel,0,28,2025,August,35,30,2025-08-30,0,2,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,210.0,0,0
HB-072954,City Hotel,1,94,2025,August,32,10,2025-08-10,1,3,2,0.0,0,BB,DNK,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,155.0,0,0
HB-024428,Resort Hotel,0,48,2024,May,21,20,2024-05-20,0,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,240.0,,0,Transient,83.0,1,0
HB-001883,Resort Hotel,0,75,2023,September,38,19,2023-09-19,2,5,3,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,156.0,,0,Transient,96.26,0,1
HB-084299,City Hotel,0,13,2024,February,8,21,2024-02-21,2,0,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,87.0,0,0
HB-092112,City Hotel,0,0,2024,June,26,30,2024-06-30,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.0,0,0
HB-099724,City Hotel,0,335,2024,October,41,13,2024-10-13,0,3,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,80.0,0,0
HB-097965,City Hotel,0,57,2024,September,38,21,2024-09-21,0,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,157.0,,0,Transient,101.52,0,0
HB-118951,City Hotel,0,457,2025,August,35,25,2025-08-25,0,2,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,6.0,,0,Transient-Party,95.5,0,1
HB-062061,City Hotel,1,240,2024,December,1,31,2024-12-31,2,2,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,70.55,0,1
HB-067399,City Hotel,1,82,2025,May,18,3,2025-05-03,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,130.0,0,0
HB-110373,City Hotel,0,310,2025,April,17,23,2025-04-23,2,2,2,0.0,0,BB,AUT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,83.75,0,0
HB-043767,City Hotel,0,86,2023,September,38,24,2023-09-24,0,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,B,0,No Deposit,12.0,,0,Transient-Party,105.0,0,0
HB-019351,Resort Hotel,0,1,2023,December,50,16,2023-12-16,0,0,1,0.0,0,BB,PRT,Online TA,TA/TO,1,0,0,A,D,0,No Deposit,240.0,,0,Transient,0.0,0,1
HB-086387,City Hotel,0,69,2024,March,13,31,2024-03-31,0,2,1,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,1
HB-006822,Resort Hotel,0,256,2024,July,27,4,2024-07-04,1,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,93.0,1,1
HB-022641,Resort Hotel,0,3,2025,June,23,8,2025-06-08,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,0,A,A,0,No Deposit,,355.0,0,Transient,75.0,0,0
HB-026783,Resort Hotel,0,8,2024,August,32,10,2024-08-10,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,E,0,No Deposit,250.0,,0,Transient,219.0,0,0
HB-031322,Resort Hotel,0,5,2024,December,52,26,2024-12-26,1,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,1,A,A,0,No Deposit,314.0,,0,Transient,48.0,0,1
HB-004220,Resort Hotel,1,74,2024,February,9,26,2024-02-26,1,2,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,68.0,,0,Transient,70.0,0,0
HB-083466,City Hotel,0,15,2024,February,5,2,2024-02-02,0,1,1,0.0,0,BB,ESP,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-033535,Resort Hotel,0,119,2025,February,7,16,2025-02-16,2,8,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,66.72,0,0
HB-117975,City Hotel,0,179,2025,August,32,8,2025-08-08,0,5,3,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,159.0,,0,Transient,171.66,0,1
HB-102602,City Hotel,0,0,2024,November,48,30,2024-11-30,0,2,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,D,B,0,No Deposit,9.0,,0,Transient-Party,63.2,0,0
HB-102294,City Hotel,0,1,2024,November,48,25,2024-11-25,0,1,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,G,0,No Deposit,9.0,,0,Transient,181.0,0,2
HB-095455,City Hotel,0,30,2024,August,34,19,2024-08-19,0,1,2,0.0,0,SC,ISR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.1,0,1
HB-017766,Resort Hotel,0,6,2023,October,41,13,2023-10-13,2,6,2,0.0,0,BB,MAR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,76.13,1,0
HB-011578,Resort Hotel,1,124,2025,May,20,18,2025-05-18,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,85.0,0,1
HB-042102,City Hotel,0,145,2023,August,35,31,2023-08-31,1,2,2,0.0,0,HB,ISR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,80.0,0,1
HB-087441,City Hotel,0,3,2024,April,16,18,2024-04-18,1,1,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,70.0,0,0
HB-004286,Resort Hotel,1,57,2024,March,9,1,2024-03-01,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-045693,City Hotel,0,140,2023,November,46,18,2023-11-18,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,29.0,,87,Transient-Party,65.0,0,0
HB-033602,Resort Hotel,0,16,2025,February,9,25,2025-02-25,1,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient-Party,54.0,0,1
HB-117366,City Hotel,0,208,2025,August,31,2,2025-08-02,0,1,2,0.0,0,HB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,157.0,0,0
HB-069153,City Hotel,1,36,2025,May,22,26,2025-05-26,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,3.0,,0,Transient,136.0,0,0
HB-074253,City Hotel,1,377,2023,October,43,29,2023-10-29,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-012601,Resort Hotel,1,113,2025,July,28,7,2025-07-07,1,2,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,190.0,0,0
HB-077034,City Hotel,1,262,2023,November,45,9,2023-11-09,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-114587,City Hotel,0,226,2025,June,25,22,2025-06-22,0,3,2,0.0,0,SC,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,1
HB-087093,City Hotel,0,19,2024,April,15,13,2024-04-13,0,1,3,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,10.0,,0,Transient,154.0,0,0
HB-050413,City Hotel,1,62,2024,April,18,30,2024-04-30,1,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,140.4,0,0
HB-037553,Resort Hotel,0,159,2025,June,25,18,2025-06-18,2,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,436.0,,0,Transient,70.2,0,0
HB-023525,Resort Hotel,0,1,2024,April,17,26,2024-04-26,0,2,2,0.0,0,BB,EST,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,68.0,1,1
HB-032781,Resort Hotel,0,1,2025,February,6,4,2025-02-04,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,48.0,0,1
HB-018315,Resort Hotel,0,10,2023,November,46,16,2023-11-16,1,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient,31.0,1,0
HB-111306,City Hotel,0,144,2025,May,19,6,2025-05-06,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,52.0,,0,Transient-Party,90.0,0,1
HB-082443,City Hotel,0,26,2023,December,52,26,2023-12-26,2,2,3,0.0,0,BB,AUT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,16.0,,0,Transient,60.75,0,1
HB-101039,City Hotel,0,8,2024,November,44,3,2024-11-03,0,3,2,0.0,0,SC,IND,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,116.67,0,1
HB-049987,City Hotel,1,58,2024,April,17,22,2024-04-22,0,2,2,0.0,0,BB,CZE,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,118.8,0,0
HB-111862,City Hotel,0,8,2025,May,20,14,2025-05-14,2,1,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,121.6,0,1
HB-036065,Resort Hotel,0,217,2025,May,19,8,2025-05-08,2,5,1,0.0,0,HB,IRL,Groups,TA/TO,0,0,0,A,A,2,No Deposit,434.0,,61,Transient-Party,62.0,0,0
HB-082999,City Hotel,0,20,2024,January,2,10,2024-01-10,1,0,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,76.0,0,0
HB-082107,City Hotel,0,0,2024,January,3,19,2024-01-19,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,2,A,A,0,No Deposit,,40.0,0,Transient,66.0,0,0
HB-060424,City Hotel,1,489,2024,November,45,10,2024-11-10,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-114379,City Hotel,0,111,2025,June,25,20,2025-06-20,0,1,2,0.0,0,SC,AUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,0
HB-106626,City Hotel,0,0,2025,February,9,25,2025-02-25,2,1,2,1.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,135.33,1,2
HB-054171,City Hotel,1,170,2024,July,27,7,2024-07-07,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.95,0,0
HB-007292,Resort Hotel,1,152,2024,August,31,1,2024-08-01,2,5,2,2.0,0,HB,PRT,Direct,Direct,0,0,0,C,C,1,No Deposit,250.0,,0,Transient,212.14,0,0
HB-091491,City Hotel,0,39,2024,June,25,18,2024-06-18,2,3,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,168.0,,0,Transient,115.5,0,0
HB-081776,City Hotel,1,113,2024,February,8,25,2024-02-25,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,44,Transient,75.0,0,0
HB-093879,City Hotel,0,59,2024,July,30,24,2024-07-24,2,2,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.5,0,1
HB-023481,Resort Hotel,0,1,2024,April,16,16,2024-04-16,4,6,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,85.0,0,1
HB-108132,City Hotel,0,1,2025,March,12,22,2025-03-22,0,1,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.0,0,1
HB-016202,Resort Hotel,0,168,2023,August,32,11,2023-08-11,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,2.0,,0,Contract,104.55,0,0
HB-068195,City Hotel,1,164,2025,May,20,15,2025-05-15,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-111381,City Hotel,0,63,2025,May,19,7,2025-05-07,2,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,144.0,0,1
HB-087801,City Hotel,0,60,2024,April,17,25,2024-04-25,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient-Party,65.0,0,0
HB-097146,City Hotel,0,7,2024,September,37,9,2024-09-09,2,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,134.0,0,1
HB-083992,City Hotel,0,0,2024,February,7,16,2024-02-16,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.0,0,0
HB-037819,Resort Hotel,0,274,2025,June,25,16,2025-06-16,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,56.7,0,1
HB-037513,Resort Hotel,0,90,2025,June,24,15,2025-06-15,2,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,70.4,0,0
HB-003109,Resort Hotel,0,105,2023,November,46,18,2023-11-18,2,4,2,0.0,0,Undefined,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,313.0,,65,Transient-Party,69.0,0,0
HB-003200,Resort Hotel,0,78,2023,November,47,21,2023-11-21,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,342.0,0,Transient-Party,32.0,0,0
HB-065889,City Hotel,1,193,2025,April,15,9,2025-04-09,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,117.0,0,1
HB-076797,City Hotel,0,4,2023,August,32,8,2023-08-08,2,1,2,0.0,0,SC,DZA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Contract,80.0,0,1
HB-106539,City Hotel,0,11,2025,February,8,21,2025-02-21,0,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,99.28,0,0
HB-055884,City Hotel,1,195,2024,August,34,23,2024-08-23,1,5,2,0.0,0,HB,CHE,Online TA,TA/TO,0,0,0,D,D,5,No Deposit,9.0,,0,Transient,147.0,0,0
HB-046178,City Hotel,0,4,2023,December,51,21,2023-12-21,1,1,2,0.0,0,BB,MAR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,96.0,1,0
HB-106501,City Hotel,0,134,2025,February,9,25,2025-02-25,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,75.0,0,0
HB-035865,Resort Hotel,0,129,2025,April,18,28,2025-04-28,2,4,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,143.33,0,2
HB-116614,City Hotel,0,160,2025,July,29,15,2025-07-15,2,5,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,71.76,0,1
HB-070867,City Hotel,1,42,2025,June,26,23,2025-06-23,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,95.0,0,0
HB-002150,Resort Hotel,0,25,2023,October,40,3,2023-10-03,2,2,1,0.0,0,BB,OMN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,59.29,0,1
HB-000530,Resort Hotel,0,94,2023,July,29,18,2023-07-18,2,5,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,250.0,,0,Transient,115.0,0,1
HB-023392,Resort Hotel,0,79,2024,April,17,22,2024-04-22,1,2,2,0.0,0,BB,USA,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,102.0,1,0
HB-091049,City Hotel,0,206,2024,June,23,9,2024-06-09,2,5,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,127.47,0,1
HB-056477,City Hotel,1,113,2024,September,36,7,2024-09-07,1,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,118.8,0,0
HB-088466,City Hotel,0,103,2024,May,18,4,2024-05-04,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,154.0,,0,Transient-Party,80.0,0,0
HB-074793,City Hotel,1,364,2023,October,42,16,2023-10-16,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,6.0,,0,Transient-Party,109.0,0,0
HB-093262,City Hotel,0,87,2024,July,28,11,2024-07-11,3,6,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient,72.25,0,0
HB-083655,City Hotel,0,51,2024,February,6,7,2024-02-07,2,1,1,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,68.5,0,1
HB-112881,City Hotel,0,183,2025,May,22,28,2025-05-28,2,0,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,139.5,0,1
HB-048618,City Hotel,1,43,2024,March,13,25,2024-03-25,2,2,2,0.0,0,HB,BEL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,148.13,0,1
HB-103042,City Hotel,0,157,2024,December,49,8,2024-12-08,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient-Party,68.0,0,0
HB-074580,City Hotel,1,353,2023,October,40,5,2023-10-05,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-113529,City Hotel,0,21,2025,June,23,6,2025-06-06,0,3,1,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,1
HB-096053,City Hotel,0,77,2024,August,34,23,2024-08-23,0,5,1,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,,,0,Transient,108.65,0,2
HB-087352,City Hotel,0,79,2024,April,16,15,2024-04-15,1,2,3,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,128.7,0,2
HB-115245,City Hotel,0,462,2025,July,27,1,2025-07-01,2,1,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,2
HB-035103,Resort Hotel,0,133,2025,April,15,11,2025-04-11,0,2,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,62.0,0,1
HB-011273,Resort Hotel,1,221,2025,April,18,30,2025-04-30,2,5,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,71.43,0,0
HB-018482,Resort Hotel,0,0,2023,November,46,17,2023-11-17,0,4,1,0.0,0,HB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,20.0,0,Transient-Party,42.0,0,0
HB-107629,City Hotel,0,6,2025,March,11,15,2025-03-15,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,443.0,0,Transient-Party,65.0,0,1
HB-118338,City Hotel,0,54,2025,August,33,15,2025-08-15,0,4,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,152.5,0,3
HB-112038,City Hotel,0,75,2025,May,20,16,2025-05-16,0,3,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-004808,Resort Hotel,0,144,2024,April,14,1,2024-04-01,2,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,177.0,,0,Transient-Party,41.4,0,0
HB-074011,City Hotel,1,293,2023,August,31,6,2023-08-06,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-034912,Resort Hotel,0,152,2025,April,14,5,2025-04-05,0,4,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,C,2,No Deposit,,223.0,0,Transient-Party,50.0,0,0
HB-002849,Resort Hotel,0,0,2023,November,44,2,2023-11-02,1,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,240.0,,0,Transient,50.5,0,1
HB-072299,City Hotel,1,357,2025,July,30,26,2025-07-26,0,1,2,1.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,123.3,0,2
HB-026601,Resort Hotel,0,161,2024,July,31,30,2024-07-30,2,5,2,0.0,0,Undefined,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,181.0,,0,Transient,150.8,1,0
HB-037677,Resort Hotel,0,6,2025,June,26,23,2025-06-23,0,2,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient,172.0,0,1
HB-011482,Resort Hotel,1,14,2025,May,19,10,2025-05-10,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,96.14,0,0
HB-079190,City Hotel,0,10,2023,October,42,20,2023-10-20,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,126.0,0,1
HB-059062,City Hotel,0,290,2024,October,42,20,2024-10-20,2,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,3,No Deposit,9.0,,0,Transient-Party,90.95,0,0
HB-111884,City Hotel,0,21,2025,May,20,14,2025-05-14,2,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,163.33,0,1
HB-001076,Resort Hotel,0,1,2023,August,32,13,2023-08-13,0,1,3,0.0,0,BB,IRL,Corporate,Corporate,0,0,0,A,F,0,No Deposit,,110.0,0,Transient,158.0,1,1
HB-033444,Resort Hotel,0,33,2025,February,8,20,2025-02-20,1,3,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,184.0,,0,Transient,43.2,0,0
HB-008023,Resort Hotel,1,238,2024,September,36,7,2024-09-07,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,D,D,0,Non Refund,1.0,,0,Transient,89.0,0,0
HB-062715,City Hotel,1,49,2025,January,3,19,2025-01-19,0,3,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,E,E,2,No Deposit,14.0,,0,Transient,153.87,0,0
HB-119193,City Hotel,0,97,2025,August,35,28,2025-08-28,1,3,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,19.0,,0,Transient-Party,104.0,0,0
HB-034364,Resort Hotel,0,1,2025,March,12,21,2025-03-21,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,168.0,,0,Transient,66.5,1,0
HB-072577,City Hotel,1,79,2025,July,31,31,2025-07-31,1,4,2,0.0,0,SC,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,124.0,0,0
HB-077473,City Hotel,0,5,2023,September,38,20,2023-09-20,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,1,No Deposit,14.0,,0,Transient,146.0,1,2
HB-085806,City Hotel,0,54,2024,March,12,19,2024-03-19,2,1,1,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,55.8,0,0
HB-047649,City Hotel,1,1,2024,February,9,28,2024-02-28,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,60.0,0,0
HB-105037,City Hotel,0,128,2025,January,5,27,2025-01-27,0,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,57.93,0,1
HB-098401,City Hotel,0,35,2024,September,39,24,2024-09-24,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,9.0,,0,Transient,139.14,0,1
HB-073356,City Hotel,1,162,2025,August,34,19,2025-08-19,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,140.0,0,0
HB-059108,City Hotel,1,192,2024,October,43,21,2024-10-21,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,29.0,,0,Transient-Party,95.0,0,0
HB-108264,City Hotel,0,44,2025,March,12,21,2025-03-21,0,4,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,56.27,0,1
HB-055088,City Hotel,1,250,2024,August,31,4,2024-08-04,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,B,B,0,No Deposit,14.0,,0,Transient-Party,90.25,0,1
HB-078987,City Hotel,0,221,2023,October,42,17,2023-10-17,2,1,3,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,3.0,,0,Transient-Party,90.0,0,0
HB-053559,City Hotel,1,172,2024,June,26,24,2024-06-24,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,34.0,,0,Transient-Party,95.0,0,0
HB-094444,City Hotel,0,15,2024,August,31,2,2024-08-02,0,2,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,124.0,0,0
HB-010865,Resort Hotel,1,233,2025,April,15,8,2025-04-08,2,6,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,62.34,0,1
HB-001795,Resort Hotel,1,105,2023,September,37,15,2023-09-15,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,68.4,0,0
HB-008884,Resort Hotel,1,71,2024,October,42,18,2024-10-18,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,44.66,0,1
HB-013741,Resort Hotel,1,26,2025,August,35,28,2025-08-28,1,3,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,286.25,0,0
HB-029812,Resort Hotel,0,82,2024,November,45,4,2024-11-04,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,37.8,0,1
HB-092120,City Hotel,0,45,2024,June,26,29,2024-06-29,0,2,2,1.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,F,0,No Deposit,9.0,,0,Transient,134.1,0,1
HB-088595,City Hotel,0,110,2024,May,18,5,2024-05-05,1,3,2,0.0,0,SC,AUT,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,9.0,,0,Transient-Party,101.58,0,1
HB-102240,City Hotel,0,9,2024,November,47,23,2024-11-23,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,2,No Deposit,,40.0,0,Transient,67.0,0,0
HB-091863,City Hotel,0,265,2024,June,26,24,2024-06-24,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-054995,City Hotel,1,135,2024,August,31,2,2024-08-02,0,2,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,137.7,0,0
HB-077695,City Hotel,1,18,2023,October,40,4,2023-10-04,2,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,29.0,,0,Transient,110.0,0,0
HB-005261,Resort Hotel,1,106,2024,April,17,23,2024-04-23,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,52.2,0,0
HB-000531,Resort Hotel,1,40,2023,July,29,18,2023-07-18,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,196.0,,0,Transient,127.03,0,2
HB-105968,City Hotel,0,70,2025,February,7,15,2025-02-15,0,4,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,242.0,0,Transient-Party,78.0,0,0
HB-040581,City Hotel,1,2,2023,August,31,1,2023-08-01,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-041175,City Hotel,1,39,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,101.5,0,0
HB-091865,City Hotel,0,265,2024,June,26,24,2024-06-24,0,2,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,6.0,,0,Transient-Party,90.0,0,0
HB-115764,City Hotel,0,56,2025,July,28,8,2025-07-08,2,1,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,133.33,0,1
HB-117670,City Hotel,0,0,2025,August,32,7,2025-08-07,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,2,No Deposit,,,0,Transient,135.0,0,0
HB-103074,City Hotel,0,0,2024,December,50,10,2024-12-10,0,1,2,1.0,0,BB,PRT,Complementary,Direct,0,0,0,F,A,0,No Deposit,,45.0,0,Transient,0.0,0,1
HB-013513,Resort Hotel,1,168,2025,August,33,17,2025-08-17,2,6,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,237.5,0,2
HB-111837,City Hotel,0,2,2025,May,20,16,2025-05-16,0,1,1,0.0,0,BB,PRT,Groups,Corporate,0,0,0,A,E,0,No Deposit,,169.0,0,Transient-Party,110.0,0,0
HB-068997,City Hotel,1,174,2025,May,21,24,2025-05-24,0,3,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,198.0,0,0
HB-111942,City Hotel,0,9,2025,May,20,14,2025-05-14,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,179.0,0,2
HB-021284,Resort Hotel,0,0,2024,February,8,23,2024-02-23,0,2,1,0.0,0,BB,PRT,Complementary,TA/TO,0,0,0,E,E,0,No Deposit,15.0,,0,Transient,0.0,0,0
HB-050535,City Hotel,1,88,2024,May,18,3,2024-05-03,0,3,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,3.0,,0,Transient-Party,96.0,0,0
HB-080319,City Hotel,1,33,2023,December,49,9,2023-12-09,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,44.0,,0,Transient,110.0,0,0
HB-046638,City Hotel,1,17,2024,January,2,13,2024-01-13,4,10,1,0.0,0,BB,AGO,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,86.0,0,0
HB-067510,City Hotel,1,143,2025,May,18,4,2025-05-04,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,56.0,,0,Transient,120.0,0,0
HB-098137,City Hotel,0,132,2024,September,38,22,2024-09-22,0,3,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,162.0,0,2
HB-053351,City Hotel,1,156,2024,June,25,18,2024-06-18,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,96.0,0,0
HB-022909,Resort Hotel,0,31,2024,April,14,2,2024-04-02,2,6,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,71.11,0,0
HB-003557,Resort Hotel,0,49,2023,December,51,23,2023-12-23,0,0,2,1.0,0,HB,PRT,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,242.0,,0,Transient,0.0,0,1
HB-095113,City Hotel,0,180,2024,August,32,11,2024-08-11,1,3,2,1.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.75,0,0
HB-044140,City Hotel,0,85,2023,September,39,30,2023-09-30,0,3,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,31.0,,80,Transient-Party,100.0,0,0
HB-118893,City Hotel,0,457,2025,August,35,25,2025-08-25,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,122.4,0,1
HB-111206,City Hotel,0,53,2025,May,19,7,2025-05-07,1,0,1,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,143.1,0,2
HB-017054,Resort Hotel,0,185,2023,September,38,21,2023-09-21,1,1,2,0.0,0,HB,FRA,Groups,TA/TO,0,0,0,A,C,0,No Deposit,208.0,,0,Transient-Party,90.0,0,0
HB-110171,City Hotel,0,133,2025,April,16,19,2025-04-19,0,4,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,390.0,,0,Transient-Party,124.0,0,0
HB-113213,City Hotel,0,0,2025,June,23,3,2025-06-03,0,1,1,0.0,0,BB,TUR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,170.0,0,0
HB-046983,City Hotel,0,47,2024,January,5,31,2024-01-31,2,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,58.94,0,2
HB-072540,City Hotel,1,261,2025,July,31,30,2025-07-30,2,2,2,0.0,0,SC,TWN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,1
HB-075077,City Hotel,1,278,2023,July,29,22,2023-07-22,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-106534,City Hotel,0,134,2025,February,9,25,2025-02-25,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,75.0,0,0
HB-046558,City Hotel,0,0,2024,January,1,7,2024-01-07,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,0
HB-077208,City Hotel,1,5,2023,September,37,17,2023-09-17,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Transient,158.0,0,1
HB-085090,City Hotel,0,34,2024,March,10,4,2024-03-04,2,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,65.0,0,0
HB-070772,City Hotel,1,117,2025,June,25,22,2025-06-22,0,3,2,0.0,0,BB,HRV,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,0
HB-002606,Resort Hotel,0,119,2023,October,43,23,2023-10-23,2,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,C,0,No Deposit,2.0,,0,Contract,44.5,0,1
HB-070374,City Hotel,1,364,2025,June,25,16,2025-06-16,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,75.0,0,0
HB-095995,City Hotel,0,154,2024,August,35,26,2024-08-26,0,1,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,27.0,,0,Transient,72.25,0,0
HB-063717,City Hotel,1,45,2025,February,8,18,2025-02-18,2,1,2,2.0,0,BB,NLD,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,125.4,0,0
HB-069528,City Hotel,1,144,2025,June,22,1,2025-06-01,0,3,3,0.0,0,BB,IRL,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,168.55,0,2
HB-027819,Resort Hotel,0,234,2024,September,37,9,2024-09-09,1,2,1,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,82.4,0,1
HB-082572,City Hotel,0,52,2023,December,52,31,2023-12-31,0,2,2,2.0,0,BB,USA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Contract,207.0,1,2
HB-024834,Resort Hotel,0,177,2024,May,22,29,2024-05-29,2,5,2,2.0,0,BB,IRL,Online TA,TA/TO,0,0,0,G,G,1,No Deposit,240.0,,0,Transient,126.29,0,1
HB-012106,Resort Hotel,1,247,2025,June,24,13,2025-06-13,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,80.1,0,1
HB-035874,Resort Hotel,0,2,2025,April,17,27,2025-04-27,2,5,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,114.43,0,0
HB-112036,City Hotel,0,64,2025,May,20,16,2025-05-16,0,3,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,8.0,,0,Transient,135.0,0,0
HB-111254,City Hotel,0,136,2025,May,19,5,2025-05-05,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,89.1,0,0
HB-081066,City Hotel,1,85,2024,January,4,22,2024-01-22,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,29.0,,0,Transient,75.0,0,0
HB-036221,Resort Hotel,0,42,2025,May,20,12,2025-05-12,0,2,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient-Party,106.0,0,1
HB-112538,City Hotel,0,102,2025,May,21,21,2025-05-21,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,137.25,0,1
HB-077925,City Hotel,0,16,2023,September,39,25,2023-09-25,2,3,1,0.0,0,BB,CHE,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,170.0,0,0
HB-067171,City Hotel,1,116,2025,April,18,29,2025-04-29,1,1,3,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,189.0,0,0
HB-118514,City Hotel,0,9,2025,August,34,18,2025-08-18,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,183.33,0,1
HB-099838,City Hotel,0,256,2024,October,42,14,2024-10-14,2,3,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,133.11,0,2
HB-052981,City Hotel,1,188,2024,June,24,15,2024-06-15,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,39,Transient,130.0,0,0
HB-097545,City Hotel,0,254,2024,September,38,16,2024-09-16,0,2,1,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,91.0,0,0
HB-000999,Resort Hotel,0,81,2023,August,32,9,2023-08-09,2,4,2,1.0,1,FB,ESP,Direct,Direct,0,0,0,C,C,0,No Deposit,250.0,,0,Transient,277.0,1,1
HB-033209,Resort Hotel,0,32,2025,February,7,13,2025-02-13,1,3,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,241.0,,0,Transient,41.87,0,1
HB-115959,City Hotel,0,33,2025,July,28,9,2025-07-09,2,2,2,0.0,0,SC,IRN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.0,0,1
HB-119185,City Hotel,0,213,2025,August,35,28,2025-08-28,1,3,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,19.0,,0,Transient-Party,104.0,0,0
HB-050055,City Hotel,1,142,2024,April,17,22,2024-04-22,2,3,2,0.0,0,BB,POL,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,103.0,0,0
HB-061524,City Hotel,1,57,2024,December,50,15,2024-12-15,2,4,2,0.0,0,SC,ISR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,0
HB-044051,City Hotel,0,83,2023,September,39,30,2023-09-30,0,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,26.0,,77,Transient-Party,112.2,0,0
HB-069599,City Hotel,1,129,2025,June,23,2,2025-06-02,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,154.0,,0,Transient,130.0,0,0
HB-021350,Resort Hotel,0,0,2024,April,17,26,2024-04-26,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,4,A,C,0,No Deposit,,384.0,0,Transient,42.0,0,1
HB-108257,City Hotel,0,3,2025,March,12,23,2025-03-23,0,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,128.0,0,2
HB-074889,City Hotel,1,135,2023,July,28,15,2023-07-15,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,7.0,,0,Transient,58.9,0,0
HB-006642,Resort Hotel,0,322,2024,June,25,22,2024-06-22,0,3,2,0.0,0,HB,POL,Groups,Direct,0,0,0,A,E,0,No Deposit,,,75,Transient-Party,92.0,0,0
HB-015423,Resort Hotel,0,152,2023,July,26,2,2023-07-02,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Contract,88.4,0,0
HB-112373,City Hotel,0,183,2025,May,21,19,2025-05-19,2,3,1,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,139.5,0,2
HB-060222,City Hotel,1,626,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-050462,City Hotel,0,130,2024,May,18,1,2024-05-01,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,71.6,0,3
HB-112867,City Hotel,0,29,2025,May,22,28,2025-05-28,1,0,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,106.4,0,1
HB-116591,City Hotel,0,74,2025,July,29,20,2025-07-20,0,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,120.0,0,2
HB-071557,City Hotel,1,133,2025,July,28,7,2025-07-07,0,2,1,1.0,0,HB,ITA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,167.4,0,1
HB-021946,Resort Hotel,0,8,2024,March,11,11,2024-03-11,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,171.0,,0,Transient,43.0,1,1
HB-009858,Resort Hotel,1,18,2025,January,3,14,2025-01-14,1,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,68.0,0,2
HB-089495,City Hotel,0,189,2024,May,20,19,2024-05-19,0,3,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,65.0,0,0
HB-113479,City Hotel,0,11,2025,June,23,5,2025-06-05,1,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,186.67,0,0
HB-116579,City Hotel,0,185,2025,July,29,14,2025-07-14,2,6,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,42.0,,0,Transient,89.1,0,0
HB-114972,City Hotel,0,223,2025,June,26,24,2025-06-24,2,4,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,95.46,0,1
HB-032120,Resort Hotel,0,41,2025,January,3,17,2025-01-17,0,0,1,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,0.0,0,0
HB-023500,Resort Hotel,0,29,2024,April,16,20,2024-04-20,2,5,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,54.86,0,1
HB-117569,City Hotel,0,93,2025,August,32,4,2025-08-04,0,2,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,134.0,1,1
HB-063804,City Hotel,1,24,2025,February,8,21,2025-02-21,0,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,97.58,0,0
HB-082787,City Hotel,1,68,2024,February,7,17,2024-02-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,37.0,,0,Transient,75.0,0,0
HB-097492,City Hotel,0,291,2024,September,38,21,2024-09-21,0,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,1,A,D,0,No Deposit,3.0,,44,Transient-Party,117.0,0,0
HB-045771,City Hotel,0,98,2023,November,47,23,2023-11-23,1,2,1,0.0,0,BB,IND,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,70.0,0,0
HB-048486,City Hotel,1,12,2024,March,12,24,2024-03-24,0,3,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,183.67,0,0
HB-056304,City Hotel,1,193,2024,September,36,3,2024-09-03,0,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,108.9,0,1
HB-039318,Resort Hotel,0,190,2025,August,32,8,2025-08-08,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,40.0,,0,Contract,134.85,0,0
HB-069670,City Hotel,1,348,2025,June,23,3,2025-06-03,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient,90.0,0,0
HB-051585,City Hotel,1,23,2024,May,21,21,2024-05-21,2,4,2,0.0,0,BB,IND,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient,128.49,0,0
HB-026747,Resort Hotel,0,83,2024,August,31,4,2024-08-04,2,4,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,F,E,0,No Deposit,250.0,,0,Transient,216.0,1,3
HB-062150,City Hotel,1,335,2025,January,1,2,2025-01-02,1,4,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,145.35,0,1
HB-059341,City Hotel,1,475,2024,October,43,27,2024-10-27,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-098194,City Hotel,0,336,2024,September,38,21,2024-09-21,1,4,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,F,0,No Deposit,21.0,,0,Transient-Party,78.0,0,0
HB-051887,City Hotel,0,316,2024,May,21,26,2024-05-26,0,3,2,0.0,0,BB,AUT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,110.0,0,0
HB-059683,City Hotel,1,12,2024,October,44,31,2024-10-31,1,3,2,1.0,0,BB,RUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,129.25,0,2
HB-068025,City Hotel,1,183,2025,May,19,11,2025-05-11,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,0,Transient,130.0,0,0
HB-030227,Resort Hotel,0,1,2024,November,46,16,2024-11-16,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,127.0,,0,Transient,54.0,1,0
HB-050189,City Hotel,1,92,2024,April,17,25,2024-04-25,1,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.95,0,0
HB-047296,City Hotel,1,7,2024,February,7,15,2024-02-15,1,3,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,66.22,0,1
HB-069753,City Hotel,1,76,2025,June,23,5,2025-06-05,1,4,2,2.0,0,BB,POL,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,250.0,0,0
HB-067501,City Hotel,1,148,2025,May,18,4,2025-05-04,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,171.0,,0,Transient,95.0,0,0
HB-043199,City Hotel,0,76,2023,September,37,16,2023-09-16,0,2,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,B,0,No Deposit,1.0,,0,Transient-Party,0.0,0,0
HB-096977,City Hotel,0,183,2024,September,36,8,2024-09-08,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,44.0,,0,Transient-Party,110.0,0,1
HB-058939,City Hotel,1,32,2024,October,42,18,2024-10-18,0,2,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,150.0,0,0
HB-113657,City Hotel,0,48,2025,June,23,6,2025-06-06,0,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,180.0,0,1
HB-075263,City Hotel,1,299,2023,August,32,12,2023-08-12,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-000612,Resort Hotel,0,0,2023,July,29,22,2023-07-22,0,1,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,153.0,1,0
HB-112252,City Hotel,0,116,2025,May,21,19,2025-05-19,1,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,2
HB-115204,City Hotel,0,168,2025,June,26,26,2025-06-26,2,5,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,394.0,,0,Transient,80.1,0,3
HB-016142,Resort Hotel,0,108,2023,August,32,10,2023-08-10,1,5,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,149.0,0,3
HB-080550,City Hotel,1,8,2025,March,11,15,2025-03-15,0,1,1,0.0,0,BB,PRT,Complementary,Direct,1,1,1,A,A,0,No Deposit,,46.0,0,Transient,79.0,0,0
HB-073461,City Hotel,1,77,2025,August,34,23,2025-08-23,0,1,2,0.0,0,BB,ZWE,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,126.0,0,0
HB-090531,City Hotel,0,118,2024,June,23,6,2024-06-06,1,1,1,0.0,0,BB,ISR,Offline TA/TO,Corporate,0,0,0,A,B,1,No Deposit,191.0,,0,Transient-Party,110.0,0,0
HB-096038,City Hotel,0,143,2024,August,34,25,2024-08-25,0,3,1,0.0,0,BB,CZE,Groups,TA/TO,0,0,0,A,A,1,No Deposit,36.0,,0,Transient-Party,0.0,0,0
HB-102170,City Hotel,0,2,2024,November,47,21,2024-11-21,1,2,1,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,100.67,0,1
HB-051128,City Hotel,1,121,2024,May,20,14,2024-05-14,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,96.0,0,0
HB-076700,City Hotel,0,1,2024,September,36,6,2024-09-06,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,1,3,43,A,B,0,No Deposit,,40.0,0,Transient,67.0,1,0
HB-101059,City Hotel,0,8,2024,November,45,5,2024-11-05,0,1,2,0.0,0,BB,CHN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,359.0,,0,Transient-Party,130.0,0,0
HB-067447,City Hotel,1,108,2025,May,18,3,2025-05-03,0,4,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-095350,City Hotel,0,129,2024,August,33,17,2024-08-17,0,1,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,9.0,,0,Transient,146.7,0,3
HB-039179,Resort Hotel,0,2,2025,August,32,9,2025-08-09,0,1,2,2.0,0,BB,USA,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,230.0,1,1
HB-040859,City Hotel,1,30,2023,August,32,8,2023-08-08,2,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,86.0,0,0
HB-006061,Resort Hotel,1,209,2024,May,21,24,2024-05-24,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.72,0,1
HB-016014,Resort Hotel,0,81,2023,August,31,3,2023-08-03,3,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,261.0,,0,Transient,149.0,0,1
HB-009496,Resort Hotel,1,183,2024,December,49,3,2024-12-03,2,1,2,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,C,1,Non Refund,38.0,,0,Transient,72.0,0,0
HB-063850,City Hotel,1,58,2025,February,8,23,2025-02-23,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,132.0,,0,Transient,78.0,0,0
HB-056526,City Hotel,1,426,2024,September,36,8,2024-09-08,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-099939,City Hotel,0,103,2024,October,42,18,2024-10-18,0,3,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,135.0,0,1
HB-074294,City Hotel,1,309,2023,August,34,22,2023-08-22,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-084053,City Hotel,0,3,2024,September,38,19,2024-09-19,1,3,1,0.0,0,BB,PRT,Aviation,TA/TO,1,0,3,D,D,0,No Deposit,,153.0,0,Transient,110.0,0,0
HB-036165,Resort Hotel,0,257,2025,May,19,9,2025-05-09,0,4,2,0.0,0,HB,GBR,Groups,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,91.0,0,0
HB-080528,City Hotel,0,0,2023,November,46,17,2023-11-17,0,1,1,0.0,0,BB,AUS,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,79.0,0,0
HB-000752,Resort Hotel,1,298,2023,July,30,27,2023-07-27,1,5,3,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,175.0,,0,Transient,183.45,0,1
HB-053411,City Hotel,1,193,2024,June,25,20,2024-06-20,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,162.0,,39,Transient,120.0,0,0
HB-037705,Resort Hotel,0,247,2025,June,25,22,2025-06-22,1,3,2,0.0,0,HB,HUN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,108.9,0,0
HB-095428,City Hotel,0,45,2024,August,33,16,2024-08-16,0,3,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,177.3,0,2
HB-075427,City Hotel,1,327,2023,September,36,9,2023-09-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-100571,City Hotel,0,55,2024,October,44,29,2024-10-29,0,1,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,82.47,0,1
HB-011755,Resort Hotel,1,102,2025,May,22,28,2025-05-28,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,410.0,,0,Transient,45.5,0,0
HB-011666,Resort Hotel,1,462,2025,May,21,25,2025-05-25,0,3,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,78.0,0,0
HB-101495,City Hotel,0,45,2024,November,46,11,2024-11-11,0,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,1
HB-070771,City Hotel,1,41,2025,June,25,22,2025-06-22,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,170.0,0,0
HB-035119,Resort Hotel,0,166,2025,April,15,10,2025-04-10,1,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,36.55,0,1
HB-090635,City Hotel,0,1,2024,June,23,7,2024-06-07,0,2,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,115.0,0,1
HB-081464,City Hotel,0,22,2023,December,49,8,2023-12-08,0,4,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,43.5,0,0
HB-086809,City Hotel,0,75,2024,April,14,5,2024-04-05,0,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.83,0,0
HB-047596,City Hotel,1,116,2024,February,9,28,2024-02-28,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,61.0,0,0
HB-004984,Resort Hotel,1,212,2024,April,15,11,2024-04-11,2,5,2,0.0,0,HB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,273.0,,0,Transient,67.05,0,0
HB-038280,Resort Hotel,0,164,2025,July,27,4,2025-07-04,2,8,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,140.0,1,0
HB-061202,City Hotel,1,12,2024,December,49,4,2024-12-04,2,0,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,104.0,0,0
HB-046643,City Hotel,1,1,2024,January,2,14,2024-01-14,0,1,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,10.0,,0,Transient,66.7,0,0
HB-052163,City Hotel,1,18,2024,May,22,31,2024-05-31,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,15.0,,0,Transient,112.8,0,0
HB-023696,Resort Hotel,0,197,2024,April,18,30,2024-04-30,1,1,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,85.0,0,0
HB-108308,City Hotel,0,115,2025,March,12,23,2025-03-23,0,3,1,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,1,No Deposit,171.0,,0,Transient-Party,90.0,0,1
HB-079253,City Hotel,1,444,2024,December,48,1,2024-12-01,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,34.0,,39,Transient,75.0,0,0
HB-103213,City Hotel,0,2,2024,December,50,12,2024-12-12,1,3,1,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,42.28,0,1
HB-094178,City Hotel,0,148,2024,July,30,25,2024-07-25,2,5,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,105.96,0,1
HB-004702,Resort Hotel,1,24,2024,March,13,28,2024-03-28,2,5,1,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,58.0,0,0
HB-112189,City Hotel,0,168,2025,May,20,18,2025-05-18,0,3,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-106754,City Hotel,0,42,2025,February,9,26,2025-02-26,2,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,102.0,0,2
HB-014860,Resort Hotel,1,207,2023,September,39,26,2023-09-26,1,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,1,1,0,A,A,0,No Deposit,208.0,,0,Transient,34.0,0,0
HB-077450,City Hotel,0,0,2023,September,37,13,2023-09-13,2,4,1,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,136.0,0,0
HB-116870,City Hotel,0,33,2025,July,29,16,2025-07-16,4,6,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,2,No Deposit,14.0,,0,Transient,114.2,0,2
HB-046192,City Hotel,0,107,2023,December,51,23,2023-12-23,2,4,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,46.63,0,1
HB-094273,City Hotel,0,143,2024,July,30,28,2024-07-28,2,4,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,132.88,0,1
HB-023116,Resort Hotel,0,4,2024,April,16,15,2024-04-15,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,95.0,0,2
HB-044391,City Hotel,1,28,2023,October,40,5,2023-10-05,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,70.0,0,0
HB-052239,City Hotel,1,330,2024,June,22,2,2024-06-02,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-078522,City Hotel,0,7,2023,October,41,9,2023-10-09,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Contract,161.33,0,2
HB-042709,City Hotel,0,69,2023,September,36,9,2023-09-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-091410,City Hotel,0,4,2024,June,24,16,2024-06-16,2,3,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,9.0,,0,Transient,168.5,0,2
HB-086814,City Hotel,0,7,2024,April,15,8,2024-04-08,0,1,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,114.0,0,3
HB-096236,City Hotel,0,96,2024,August,35,28,2024-08-28,2,1,2,0.0,0,HB,POL,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,16.0,,0,Transient,85.0,0,0
HB-049110,City Hotel,1,105,2024,April,14,6,2024-04-06,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,0,Transient,75.0,0,0
HB-091278,City Hotel,0,1,2024,June,25,18,2024-06-18,0,1,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,168.0,1,2
HB-104865,City Hotel,0,4,2025,January,4,23,2025-01-23,1,0,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,75.46,0,1
HB-047545,City Hotel,1,35,2024,February,9,26,2024-02-26,1,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,84.9,0,1
HB-100052,City Hotel,0,41,2024,October,42,15,2024-10-15,2,5,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,8.0,,0,Transient,249.63,0,1
HB-086162,City Hotel,0,42,2024,March,12,24,2024-03-24,1,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.16,0,0
HB-046201,City Hotel,0,22,2023,December,51,24,2023-12-24,1,3,2,0.0,0,BB,MEX,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,87.0,0,1
HB-007466,Resort Hotel,1,76,2024,August,32,10,2024-08-10,4,10,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,202.57,0,0
HB-095591,City Hotel,0,1,2024,August,34,20,2024-08-20,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,139.0,0,0
HB-065518,City Hotel,1,81,2025,April,14,4,2025-04-04,0,5,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,83.0,,0,Transient,168.0,0,0
HB-061063,City Hotel,1,290,2024,December,48,1,2024-12-01,1,3,2,0.0,0,BB,SVK,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,86.7,0,0
HB-102270,City Hotel,0,191,2024,November,48,25,2024-11-25,0,1,2,0.0,0,SC,ROU,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,9.0,,0,Transient,71.1,0,0
HB-091375,City Hotel,0,44,2024,June,25,19,2024-06-19,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,7.0,,0,Transient,99.1,0,1
HB-073095,City Hotel,1,146,2025,August,33,14,2025-08-14,1,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.5,0,0
HB-063104,City Hotel,1,26,2025,January,5,31,2025-01-31,0,4,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,91.8,0,0
HB-019877,Resort Hotel,0,0,2024,January,1,6,2024-01-06,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,43.0,1,0
HB-111897,City Hotel,0,14,2025,May,20,14,2025-05-14,2,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,150.0,0,0
HB-047712,City Hotel,1,35,2024,February,9,29,2024-02-29,1,5,2,1.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.1,0,1
HB-118285,City Hotel,0,75,2025,August,33,14,2025-08-14,1,3,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.0,0,1
HB-064517,City Hotel,1,46,2025,March,11,11,2025-03-11,2,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,106.2,0,0
HB-079866,City Hotel,1,34,2023,December,49,8,2023-12-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,0,Transient,90.0,0,0
HB-067407,City Hotel,1,82,2025,May,18,3,2025-05-03,0,3,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,0
HB-084098,City Hotel,0,99,2024,February,8,19,2024-02-19,0,1,1,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,A,0,No Deposit,,67.0,0,Transient-Party,81.0,0,0
HB-010565,Resort Hotel,1,144,2025,March,11,14,2025-03-14,4,14,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,C,1,No Deposit,440.0,,0,Transient-Party,62.0,0,0
HB-094586,City Hotel,0,115,2024,August,31,3,2024-08-03,0,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,89.0,,0,Transient,77.18,0,1
HB-087954,City Hotel,0,13,2024,April,17,26,2024-04-26,0,3,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,58.0,,0,Transient-Party,73.0,0,0
HB-075210,City Hotel,1,294,2023,August,32,7,2023-08-07,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-082624,City Hotel,0,68,2023,December,52,31,2023-12-31,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,104.0,,0,Transient-Party,71.33,0,1
HB-104864,City Hotel,0,15,2025,January,4,20,2025-01-20,2,2,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,64.31,0,1
HB-087952,City Hotel,0,97,2024,April,17,25,2024-04-25,1,3,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,80.75,0,1
HB-078060,City Hotel,0,1,2023,October,39,1,2023-10-01,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,96.0,0,0
HB-023444,Resort Hotel,0,32,2024,April,16,19,2024-04-19,2,5,2,0.0,0,HB,GBR,Groups,Direct,0,0,0,D,D,0,No Deposit,273.0,,0,Transient-Party,38.22,0,0
HB-071978,City Hotel,1,30,2025,July,29,16,2025-07-16,2,3,2,1.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,176.0,0,1
HB-116965,City Hotel,0,53,2025,July,30,23,2025-07-23,2,3,2,2.0,0,HB,ESP,Direct,Direct,0,0,0,E,E,1,No Deposit,14.0,,0,Transient,256.72,1,1
HB-063670,City Hotel,1,15,2025,February,8,17,2025-02-17,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,95.0,0,0
HB-078139,City Hotel,0,12,2023,October,40,4,2023-10-04,1,0,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,3.0,,0,Transient-Party,72.0,0,0
HB-023249,Resort Hotel,0,31,2024,April,16,18,2024-04-18,1,1,2,0.0,0,BB,FRA,Groups,Corporate,0,0,0,E,E,0,No Deposit,,,0,Transient,91.0,1,0
HB-111669,City Hotel,0,15,2025,May,19,11,2025-05-11,0,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,200.0,0,1
HB-037474,Resort Hotel,0,208,2025,June,24,14,2025-06-14,1,4,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,314.0,,0,Transient,90.0,0,0
HB-047643,City Hotel,1,116,2024,February,9,28,2024-02-28,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,1.0,0,0
HB-062927,City Hotel,1,78,2025,January,4,25,2025-01-25,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,365.0,0,Transient-Party,85.0,0,0
HB-046790,City Hotel,1,151,2024,January,3,19,2024-01-19,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,19.0,,63,Transient-Party,80.0,0,0
HB-062842,City Hotel,1,59,2025,January,4,23,2025-01-23,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,326.0,,0,Transient,80.0,0,0
HB-004669,Resort Hotel,1,33,2024,March,13,26,2024-03-26,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,73.29,0,0
HB-051070,City Hotel,1,273,2024,May,20,13,2024-05-13,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,95.0,0,0
HB-110439,City Hotel,0,155,2025,April,17,24,2025-04-24,1,3,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.0,0,1
HB-036856,Resort Hotel,0,112,2025,May,22,28,2025-05-28,2,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,117.0,0,1
HB-020864,Resort Hotel,0,2,2024,February,6,7,2024-02-07,2,3,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,2.0,,0,Contract,71.0,0,0
HB-023715,Resort Hotel,0,197,2024,April,18,30,2024-04-30,1,1,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,D,0,No Deposit,298.0,,0,Transient-Party,85.0,0,0
HB-074088,City Hotel,1,321,2023,September,35,3,2023-09-03,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-119081,City Hotel,0,269,2025,August,34,22,2025-08-22,2,5,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,2
HB-098521,City Hotel,0,114,2024,September,39,24,2024-09-24,2,5,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,131.66,0,0
HB-031412,Resort Hotel,0,0,2024,December,52,27,2024-12-27,0,1,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,75.0,1,0
HB-041401,City Hotel,0,131,2023,August,33,15,2023-08-15,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-004319,Resort Hotel,1,52,2024,March,10,4,2024-03-04,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-080120,City Hotel,1,72,2023,December,52,27,2023-12-27,2,0,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,90.0,0,0
HB-067505,City Hotel,1,148,2025,May,18,4,2025-05-04,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,171.0,,0,Transient,95.0,0,0
HB-070577,City Hotel,1,201,2025,June,25,19,2025-06-19,1,1,2,0.0,0,BB,MEX,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.5,0,0
HB-030401,Resort Hotel,0,0,2024,November,47,20,2024-11-20,1,0,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,H,H,0,No Deposit,,,0,Transient,105.0,0,0
HB-041023,City Hotel,0,1,2023,August,32,11,2023-08-11,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,124.0,0,0
HB-059648,City Hotel,1,95,2024,October,44,30,2024-10-30,2,1,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.8,0,2
HB-054587,City Hotel,0,0,2024,July,29,20,2024-07-20,0,4,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,A,A,3,No Deposit,,,0,Transient,99.7,0,0
HB-012546,Resort Hotel,1,347,2025,July,27,3,2025-07-03,3,7,2,1.0,0,HB,NOR,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,232.0,0,0
HB-035750,Resort Hotel,0,58,2025,April,18,29,2025-04-29,1,1,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient-Party,127.0,0,0
HB-049895,City Hotel,0,270,2024,April,16,20,2024-04-20,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,187,Transient-Party,80.0,0,0
HB-098661,City Hotel,0,193,2024,September,40,30,2024-09-30,1,2,2,0.0,0,BB,DEU,Groups,Corporate,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,132.0,0,0
HB-015105,Resort Hotel,1,214,2023,October,40,3,2023-10-03,1,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,208.0,,0,Transient,34.0,0,0
HB-096111,City Hotel,0,0,2024,August,35,28,2024-08-28,1,0,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,149.0,0,0
HB-057518,City Hotel,1,53,2024,September,39,26,2024-09-26,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,105.0,0,0
HB-030905,Resort Hotel,0,0,2024,December,49,8,2024-12-08,0,0,2,0.0,0,BB,PRT,Direct,Direct,1,0,0,E,E,1,No Deposit,,,0,Transient,0.0,0,0
HB-118012,City Hotel,0,198,2025,August,33,11,2025-08-11,0,2,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,16.0,,0,Transient,80.1,0,0
HB-087220,City Hotel,0,38,2024,April,15,12,2024-04-12,0,4,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,139.95,0,2
HB-062411,City Hotel,1,205,2025,January,3,13,2025-01-13,0,1,2,0.0,0,BB,AUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,84.6,0,1
HB-110845,City Hotel,0,140,2025,April,18,28,2025-04-28,2,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,119.0,,0,Transient-Party,120.0,0,0
HB-107729,City Hotel,0,8,2025,March,11,16,2025-03-16,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,65.0,1,0
HB-088080,City Hotel,0,53,2024,April,17,28,2024-04-28,0,3,2,0.0,0,BB,JPN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,1
HB-088518,City Hotel,0,62,2024,May,19,7,2024-05-07,0,1,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,E,2,No Deposit,9.0,,0,Transient,159.3,0,2
HB-094870,City Hotel,0,159,2024,August,31,3,2024-08-03,2,6,2,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,99.45,0,0
HB-087906,City Hotel,0,100,2024,April,17,25,2024-04-25,1,2,1,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,10.0,,0,Transient,80.1,0,0
HB-118322,City Hotel,0,174,2025,August,33,14,2025-08-14,1,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,42.0,,0,Transient,80.1,0,1
HB-025456,Resort Hotel,0,21,2024,June,26,25,2024-06-25,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,120.0,0,1
HB-072248,City Hotel,1,27,2025,July,30,24,2025-07-24,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,152.0,0,2
HB-063415,City Hotel,1,57,2025,February,7,11,2025-02-11,2,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,2
HB-071077,City Hotel,1,26,2025,June,26,28,2025-06-28,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,280.0,0,Transient-Party,100.0,0,0
HB-006780,Resort Hotel,1,164,2024,July,27,1,2024-07-01,4,10,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,75.0,,0,Contract,105.4,0,1
HB-105966,City Hotel,0,114,2025,February,7,15,2025-02-15,0,4,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,242.0,0,Transient-Party,78.0,0,0
HB-068029,City Hotel,1,209,2025,May,19,11,2025-05-11,1,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,138.6,0,2
HB-024526,Resort Hotel,0,68,2024,May,20,18,2024-05-18,2,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,2,No Deposit,314.0,,0,Transient,74.4,1,0
HB-076111,City Hotel,1,260,2023,September,38,18,2023-09-18,0,2,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,1,Non Refund,6.0,,0,Transient-Party,80.0,0,0
HB-058829,City Hotel,1,283,2024,October,42,16,2024-10-16,2,0,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,96.0,0,0
HB-002653,Resort Hotel,1,148,2023,October,43,24,2023-10-24,0,1,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,47.0,0,0
HB-030482,Resort Hotel,0,47,2024,November,47,19,2024-11-19,2,3,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,37.8,0,2
HB-096021,City Hotel,0,143,2024,August,34,25,2024-08-25,0,3,1,0.0,0,BB,CZE,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,36.0,,0,Transient-Party,90.0,0,0
HB-014056,Resort Hotel,0,0,2024,May,22,29,2024-05-29,2,1,1,0.0,0,BB,,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,76.0,1,0
HB-032539,Resort Hotel,0,28,2025,January,5,27,2025-01-27,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,95.0,,0,Transient,34.0,0,0
HB-113899,City Hotel,0,73,2025,June,24,12,2025-06-12,1,1,2,0.0,0,SC,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,168.0,,0,Transient,80.1,0,1
HB-006628,Resort Hotel,1,155,2024,June,25,21,2024-06-21,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,136.0,0,1
HB-081840,City Hotel,1,178,2024,April,17,28,2024-04-28,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,46,Transient,110.0,0,0
HB-102785,City Hotel,0,43,2024,November,48,30,2024-11-30,2,4,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.8,0,1
HB-037448,Resort Hotel,0,102,2025,June,24,14,2025-06-14,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,134.0,1,1
HB-067811,City Hotel,1,12,2025,May,19,7,2025-05-07,4,6,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,144.8,0,1
HB-013459,Resort Hotel,1,61,2025,August,33,16,2025-08-16,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Group,188.6,0,0
HB-089133,City Hotel,0,6,2024,May,20,17,2024-05-17,0,1,1,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,90.0,0,0
HB-071955,City Hotel,1,14,2025,July,29,16,2025-07-16,1,0,2,0.0,0,SC,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.0,0,1
HB-007079,Resort Hotel,1,161,2024,July,29,19,2024-07-19,2,8,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,200.0,0,1
HB-097336,City Hotel,0,346,2024,September,37,13,2024-09-13,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-092304,City Hotel,0,47,2024,July,27,2,2024-07-02,1,1,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,150.3,0,2
HB-001870,Resort Hotel,1,77,2023,September,38,18,2023-09-18,2,7,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,87.33,0,1
HB-053809,City Hotel,1,358,2024,June,26,30,2024-06-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-089936,City Hotel,0,20,2024,May,22,28,2024-05-28,1,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,143.0,0,1
HB-010394,Resort Hotel,1,8,2025,March,10,3,2025-03-03,1,2,2,0.0,0,BB,PRT,Groups,Corporate,0,0,0,D,D,1,No Deposit,,223.0,0,Transient-Party,47.0,0,0
HB-085168,City Hotel,0,20,2024,March,10,7,2024-03-07,1,3,2,0.0,0,BB,SWE,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,65.58,0,0
HB-095655,City Hotel,0,210,2024,August,33,15,2024-08-15,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,67.42,0,1
HB-088857,City Hotel,0,56,2024,May,19,9,2024-05-09,1,3,2,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,121.0,,0,Transient,85.5,0,0
HB-068707,City Hotel,1,121,2025,May,21,20,2025-05-20,0,1,2,0.0,0,SC,ZAF,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-078714,City Hotel,0,6,2025,May,19,10,2025-05-10,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,25,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,1
HB-086530,City Hotel,0,7,2024,April,14,4,2024-04-04,1,0,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,95.0,0,0
HB-105095,City Hotel,0,41,2025,January,4,26,2025-01-26,0,3,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,69.56,0,0
HB-031493,Resort Hotel,0,16,2024,December,52,29,2024-12-29,0,1,1,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,60.0,0,1
HB-007947,Resort Hotel,1,83,2024,September,36,4,2024-09-04,1,0,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,154.0,0,0
HB-048021,City Hotel,1,56,2024,March,11,12,2024-03-12,2,2,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,63.75,0,0
HB-099319,City Hotel,0,30,2024,October,41,7,2024-10-07,2,3,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,164.13,1,1
HB-013045,Resort Hotel,1,52,2025,July,31,29,2025-07-29,2,2,2,1.0,0,BB,MAR,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,237.5,0,0
HB-020332,Resort Hotel,0,2,2024,January,3,16,2024-01-16,2,6,1,0.0,0,BB,DEU,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,38.1,0,0
HB-105913,City Hotel,0,16,2025,February,7,13,2025-02-13,1,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,79.0,,0,Transient,68.84,0,0
HB-070748,City Hotel,1,153,2025,June,25,21,2025-06-21,0,4,1,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,A,0,Non Refund,,348.0,0,Transient,110.0,0,0
HB-019491,Resort Hotel,0,25,2023,December,51,22,2023-12-22,0,1,2,0.0,1,BB,MAR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,46.4,0,3
HB-029103,Resort Hotel,0,301,2024,October,40,6,2024-10-06,4,10,1,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,2.0,,0,Contract,31.45,0,1
HB-098948,City Hotel,0,131,2024,October,40,4,2024-10-04,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,155.0,,0,Transient,144.67,0,1
HB-099155,City Hotel,0,5,2024,October,41,7,2024-10-07,1,2,1,0.0,0,BB,HUN,Online TA,TA/TO,0,0,0,A,B,1,No Deposit,9.0,,0,Transient,150.0,0,0
HB-095780,City Hotel,0,3,2024,August,34,23,2024-08-23,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,9.0,,0,Transient,139.0,0,1
HB-086884,City Hotel,0,134,2024,April,15,9,2024-04-09,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,90.0,0,1
HB-001417,Resort Hotel,1,42,2023,August,35,28,2023-08-28,2,4,2,1.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,250.0,,0,Transient,158.0,0,1
HB-061021,City Hotel,1,42,2024,November,48,29,2024-11-29,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,348.0,0,Transient,90.0,0,0
HB-110934,City Hotel,0,65,2025,May,18,1,2025-05-01,1,2,2,0.0,0,BB,LUX,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,141.2,0,0
HB-058279,City Hotel,1,76,2024,October,41,10,2024-10-10,1,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,234.0,,0,Transient-Party,120.0,0,0
HB-050306,City Hotel,1,295,2024,April,17,28,2024-04-28,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-015119,Resort Hotel,0,39,2023,July,27,7,2023-07-07,2,8,2,0.0,0,HB,PRT,Direct,Direct,0,0,1,E,E,1,No Deposit,,,0,Transient,107.1,1,2
HB-107028,City Hotel,0,2,2025,March,10,6,2025-03-06,0,0,0,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,D,K,0,No Deposit,9.0,,0,Transient,0.0,0,0
HB-068339,City Hotel,1,104,2025,May,20,15,2025-05-15,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-056257,City Hotel,0,0,2024,September,36,2,2024-09-02,0,1,1,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient,149.0,0,0
HB-013623,Resort Hotel,1,223,2025,August,34,23,2025-08-23,2,5,2,0.0,0,HB,RUS,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,222.0,0,2
HB-066441,City Hotel,1,168,2025,April,16,20,2025-04-20,0,3,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,166.5,0,3
HB-006855,Resort Hotel,0,240,2024,July,27,7,2024-07-07,2,3,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,108.0,0,1
HB-003363,Resort Hotel,1,44,2023,December,49,5,2023-12-05,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,70.0,0,0
HB-088140,City Hotel,0,47,2024,April,17,28,2024-04-28,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,0
HB-026646,Resort Hotel,0,41,2024,August,31,3,2024-08-03,0,4,2,1.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,226.0,0,1
HB-083499,City Hotel,0,13,2024,February,5,1,2024-02-01,1,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,66.0,0,0
HB-039981,Resort Hotel,0,97,2025,August,35,27,2025-08-27,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,118.5,0,1
HB-112748,City Hotel,0,226,2025,May,21,25,2025-05-25,0,3,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.1,0,2
HB-007868,Resort Hotel,0,326,2024,August,35,30,2024-08-30,2,8,1,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,314.0,,0,Transient,71.4,0,0
HB-065857,City Hotel,1,66,2025,April,15,9,2025-04-09,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-004074,Resort Hotel,1,112,2024,February,7,12,2024-02-12,0,2,2,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,68.0,0,0
HB-034283,Resort Hotel,0,26,2025,March,11,14,2025-03-14,0,5,1,0.0,0,HB,DEU,Direct,Direct,0,0,0,E,E,1,No Deposit,,,0,Transient-Party,65.0,0,0
HB-046216,City Hotel,0,8,2023,December,52,26,2023-12-26,2,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient-Party,92.58,1,0
HB-023678,Resort Hotel,0,18,2024,October,42,16,2024-10-16,2,4,2,0.0,0,BB,GBR,Online TA,TA/TO,1,0,0,F,F,0,No Deposit,241.0,,0,Transient,79.0,0,2
HB-067876,City Hotel,1,62,2025,May,19,8,2025-05-08,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,B,B,0,No Deposit,57.0,,0,Transient,136.22,0,0
HB-031012,Resort Hotel,0,0,2024,December,50,10,2024-12-10,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,61.0,0,0
HB-107259,City Hotel,0,12,2025,March,10,8,2025-03-08,0,2,1,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,2,No Deposit,14.0,,0,Transient,80.0,0,1
HB-043243,City Hotel,0,44,2023,September,37,17,2023-09-17,0,2,1,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,85.5,0,1
HB-115473,City Hotel,0,405,2025,July,27,4,2025-07-04,0,2,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,91.5,0,0
HB-074966,City Hotel,1,164,2023,August,33,14,2023-08-14,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient,12.0,0,0
HB-070222,City Hotel,1,139,2025,June,24,12,2025-06-12,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,110.0,0,0
HB-084885,City Hotel,0,24,2024,March,9,3,2024-03-03,0,3,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,117.0,0,0
HB-104564,City Hotel,0,1,2025,January,2,12,2025-01-12,2,3,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,2,No Deposit,14.0,,0,Transient,74.2,0,1
HB-115382,City Hotel,0,405,2025,July,27,4,2025-07-04,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,114.4,0,0
HB-002340,Resort Hotel,0,22,2023,October,41,9,2023-10-09,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,83.0,1,2
HB-051415,City Hotel,1,322,2024,May,20,19,2024-05-19,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,120,Transient,80.0,0,0
HB-108568,City Hotel,0,154,2025,March,13,26,2025-03-26,2,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,72.07,0,1
HB-087887,City Hotel,0,3,2024,April,17,25,2024-04-25,1,2,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,131.0,0,1
HB-090006,City Hotel,0,49,2024,May,22,30,2024-05-30,1,0,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,121.5,0,1
HB-087968,City Hotel,0,13,2024,April,17,26,2024-04-26,0,3,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,58.0,,0,Transient-Party,73.0,0,0
HB-085467,City Hotel,0,0,2024,March,11,14,2024-03-14,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,109.0,0,0
HB-043098,City Hotel,0,38,2023,September,37,14,2023-09-14,2,5,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,101.83,0,1
HB-046344,City Hotel,1,4,2023,December,52,30,2023-12-30,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,137.0,0,1
HB-064529,City Hotel,1,25,2025,March,11,12,2025-03-12,1,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-009217,Resort Hotel,1,292,2024,November,44,3,2024-11-03,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,368.0,,0,Transient-Party,38.0,0,0
HB-063197,City Hotel,1,573,2025,February,5,2,2025-02-02,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,59.0,0,0
HB-034404,Resort Hotel,0,96,2025,March,11,12,2025-03-12,4,7,2,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,50.55,0,0
HB-102021,City Hotel,0,2,2024,November,47,18,2024-11-18,2,2,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,92.86,0,0
HB-015617,Resort Hotel,0,50,2023,July,29,21,2023-07-21,2,6,2,1.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,109.65,0,1
HB-013034,Resort Hotel,1,129,2025,July,31,28,2025-07-28,2,5,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,252.0,0,1
HB-103689,City Hotel,0,109,2024,December,52,27,2024-12-27,0,3,3,0.0,0,BB,LTU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,92.65,0,0
HB-086428,City Hotel,0,50,2024,March,13,31,2024-03-31,0,3,2,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,65.0,0,1
HB-117729,City Hotel,0,174,2025,August,32,5,2025-08-05,2,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.5,0,1
HB-090792,City Hotel,0,107,2024,June,24,10,2024-06-10,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,187.0,,0,Transient-Party,120.0,0,0
HB-077642,City Hotel,0,2,2023,September,38,21,2023-09-21,1,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Group,77.0,0,0
HB-064714,City Hotel,1,92,2025,March,11,15,2025-03-15,0,3,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,85.0,0,0
HB-039306,Resort Hotel,0,239,2025,August,32,9,2025-08-09,1,4,2,0.0,0,BB,CN,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,183.2,0,1
HB-108567,City Hotel,0,38,2025,March,13,25,2025-03-25,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.05,0,2
HB-096517,City Hotel,0,78,2024,September,35,1,2024-09-01,0,3,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,149.4,0,1
HB-038116,Resort Hotel,0,253,2025,July,28,7,2025-07-07,0,2,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,89.1,0,0
HB-070450,City Hotel,1,44,2025,June,25,17,2025-06-17,2,1,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,1
HB-079128,City Hotel,0,1,2024,March,13,30,2024-03-30,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,40.0,0,Transient,67.0,0,0
HB-003889,Resort Hotel,1,18,2024,February,6,5,2024-02-05,1,2,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,240.0,,0,Transient,69.67,0,2
HB-013590,Resort Hotel,1,38,2025,August,34,21,2025-08-21,1,3,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,199.12,0,1
HB-052010,City Hotel,1,57,2024,May,22,28,2024-05-28,2,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,140.4,0,1
HB-056365,City Hotel,1,62,2024,September,36,4,2024-09-04,1,0,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.8,0,0
HB-039594,Resort Hotel,0,185,2025,August,33,13,2025-08-13,4,6,3,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,196.0,,0,Transient,229.13,0,1
HB-107718,City Hotel,0,43,2025,March,11,13,2025-03-13,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,91.8,0,3
HB-067738,City Hotel,1,117,2025,May,19,6,2025-05-06,2,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,96.0,0,0
HB-020056,Resort Hotel,0,7,2024,January,2,12,2024-01-12,0,3,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,39.0,0,1
HB-050434,City Hotel,1,120,2024,April,18,30,2024-04-30,2,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,87.13,0,0
HB-049091,City Hotel,1,105,2024,April,14,6,2024-04-06,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,0,Transient,75.0,0,0
HB-026550,Resort Hotel,0,179,2024,July,31,31,2024-07-31,2,2,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,96.0,,0,Transient-Party,103.5,0,1
HB-046760,City Hotel,0,151,2024,January,3,19,2024-01-19,0,2,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,2,No Deposit,19.0,,63,Transient-Party,71.0,0,0
HB-022246,Resort Hotel,0,50,2024,March,11,17,2024-03-17,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,56.0,0,1
HB-014328,Resort Hotel,0,31,2024,December,1,30,2024-12-30,0,2,2,0.0,0,HB,,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,305.0,0,1
HB-030635,Resort Hotel,0,45,2024,November,48,27,2024-11-27,2,0,2,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,D,1,No Deposit,,,0,Transient,0.0,0,0
HB-058164,City Hotel,1,17,2024,October,41,7,2024-10-07,0,2,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.0,0,1
HB-056603,City Hotel,1,178,2024,September,37,9,2024-09-09,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,135.0,0,0
HB-069760,City Hotel,1,148,2025,June,23,5,2025-06-05,1,5,2,1.0,0,BB,DEU,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,141.0,0,2
HB-039917,Resort Hotel,0,3,2025,August,35,26,2025-08-26,2,4,3,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,1,No Deposit,250.0,,0,Transient,252.57,1,2
HB-071911,City Hotel,1,476,2025,July,29,15,2025-07-15,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,0
HB-036569,Resort Hotel,0,239,2025,May,20,18,2025-05-18,2,4,2,0.0,0,HB,FRA,Direct,Direct,0,0,0,E,E,1,No Deposit,250.0,,0,Transient,101.28,0,0
HB-000509,Resort Hotel,0,19,2023,July,29,18,2023-07-18,2,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,F,0,No Deposit,240.0,,0,Transient,147.67,0,2
HB-033970,Resort Hotel,0,12,2025,March,10,5,2025-03-05,2,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,95.0,,0,Transient,34.0,0,0
HB-015528,Resort Hotel,0,37,2023,July,29,19,2023-07-19,2,3,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,146.95,0,2
HB-037442,Resort Hotel,0,2,2025,June,25,18,2025-06-18,1,0,2,0.0,0,BB,PRT,Direct,TA/TO,0,0,0,D,E,0,No Deposit,,,0,Transient,155.0,1,1
HB-052855,City Hotel,1,28,2024,June,24,13,2024-06-13,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,102.85,0,0
HB-043863,City Hotel,1,87,2023,September,39,25,2023-09-25,2,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-070800,City Hotel,1,137,2025,June,26,23,2025-06-23,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,125.0,0,0
HB-045119,City Hotel,0,41,2023,October,42,16,2023-10-16,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.9,0,2
HB-008480,Resort Hotel,1,71,2024,September,40,30,2024-09-30,2,7,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,92.89,0,0
HB-051538,City Hotel,1,23,2024,May,21,21,2024-05-21,0,1,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,140.4,0,0
HB-016346,Resort Hotel,0,66,2023,August,33,20,2023-08-20,2,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,161.6,0,0
HB-099069,City Hotel,0,27,2024,October,40,6,2024-10-06,0,3,1,0.0,0,BB,SWE,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,99.0,0,0
HB-044613,City Hotel,0,35,2023,October,40,8,2023-10-08,0,2,2,0.0,0,BB,TUR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,103.05,0,3
HB-068127,City Hotel,1,151,2025,May,20,13,2025-05-13,2,2,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,95.0,0,0
HB-063180,City Hotel,1,41,2025,February,5,1,2025-02-01,0,2,2,0.0,0,SC,JPN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,0
HB-098477,City Hotel,0,35,2024,September,39,25,2024-09-25,2,3,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,156.24,0,2
HB-057031,City Hotel,1,302,2024,September,38,16,2024-09-16,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,70,Transient,100.0,0,0
HB-033878,Resort Hotel,0,7,2025,March,9,2,2025-03-02,1,3,2,0.0,0,BB,BEL,Groups,Corporate,0,0,0,D,D,0,No Deposit,,223.0,0,Transient-Party,47.0,0,0
HB-060125,City Hotel,1,8,2024,November,45,5,2024-11-05,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,89.0,0,0
HB-070653,City Hotel,1,117,2025,June,25,20,2025-06-20,0,1,2,0.0,0,SC,AUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,0
HB-064406,City Hotel,1,608,2025,March,10,9,2025-03-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-096044,City Hotel,0,143,2024,August,34,25,2024-08-25,0,3,2,0.0,0,BB,CZE,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,36.0,,0,Transient-Party,100.0,0,0
HB-039843,Resort Hotel,0,73,2025,August,35,26,2025-08-26,2,2,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,167.2,0,1
HB-018211,Resort Hotel,0,29,2023,November,45,10,2023-11-10,0,5,2,1.0,0,BB,ESP,Corporate,Corporate,0,0,0,A,C,3,No Deposit,,281.0,0,Transient,60.0,0,1
HB-114536,City Hotel,0,2,2025,June,25,20,2025-06-20,0,3,2,0.0,0,BB,NLD,Direct,Direct,0,0,0,G,G,0,No Deposit,14.0,,0,Transient,333.67,0,0
HB-053953,City Hotel,1,132,2024,July,27,2,2024-07-02,2,5,2,1.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,114.75,0,2
HB-041183,City Hotel,0,39,2023,August,33,14,2023-08-14,0,2,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,87.0,0,0
HB-052893,City Hotel,1,71,2024,June,24,14,2024-06-14,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,120.0,0,0
HB-045325,City Hotel,0,69,2023,October,43,25,2023-10-25,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,58,Transient-Party,85.67,0,0
HB-032982,Resort Hotel,0,1,2025,February,7,10,2025-02-10,0,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,43.0,0,2
HB-111570,City Hotel,0,90,2025,May,19,6,2025-05-06,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,137.57,0,1
HB-074527,City Hotel,1,332,2023,September,37,14,2023-09-14,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-029732,Resort Hotel,0,31,2024,October,44,30,2024-10-30,2,4,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient-Party,70.45,0,2
HB-100253,City Hotel,0,210,2024,October,43,21,2024-10-21,2,2,3,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,105.4,0,0
HB-039173,Resort Hotel,0,5,2025,August,32,10,2025-08-10,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,244.0,0,2
HB-096011,City Hotel,0,150,2024,August,35,27,2024-08-27,0,1,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,109.8,0,1
HB-050626,City Hotel,1,302,2024,May,18,5,2024-05-05,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-100392,City Hotel,0,226,2024,October,43,25,2024-10-25,0,3,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,83.0,,0,Transient,102.76,0,0
HB-082150,City Hotel,1,99,2024,February,8,19,2024-02-19,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,1,0,A,A,0,No Deposit,,67.0,0,Transient-Party,80.0,0,0
HB-032036,Resort Hotel,0,0,2025,January,3,14,2025-01-14,0,1,2,0.0,0,BB,ITA,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,44.0,0,0
HB-071412,City Hotel,1,282,2025,July,27,5,2025-07-05,0,2,2,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,141.3,0,1
HB-060126,City Hotel,1,95,2024,November,45,5,2024-11-05,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,75.0,0,0
HB-052888,City Hotel,1,71,2024,June,24,14,2024-06-14,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,120.0,0,0
HB-100014,City Hotel,0,184,2024,October,42,18,2024-10-18,0,4,2,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.5,0,1
HB-098358,City Hotel,0,22,2024,September,39,27,2024-09-27,0,2,1,0.0,0,BB,GRC,Online TA,TA/TO,0,0,0,A,B,1,No Deposit,8.0,,0,Transient,133.0,0,1
HB-087821,City Hotel,0,1,2024,April,17,26,2024-04-26,0,1,3,0.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,0,No Deposit,14.0,,0,Transient,205.95,0,1
HB-077926,City Hotel,1,6,2023,October,39,1,2023-10-01,1,3,2,0.0,0,BB,PRT,Direct,Direct,0,1,0,A,A,0,No Deposit,,,0,Transient,100.0,0,0
HB-118181,City Hotel,0,5,2025,August,33,14,2025-08-14,1,1,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,9.0,,0,Transient,220.0,0,2
HB-038043,Resort Hotel,0,313,2025,July,27,1,2025-07-01,2,5,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,128.04,1,0
HB-080855,City Hotel,0,0,2023,December,48,3,2023-12-03,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,148.0,0,Transient,79.0,0,0
HB-083242,City Hotel,0,3,2024,January,4,25,2024-01-25,1,0,2,0.0,0,BB,PRT,Complementary,Direct,0,0,0,G,G,0,No Deposit,,,0,Transient,0.0,1,1
HB-066949,City Hotel,1,110,2025,April,17,26,2025-04-26,1,4,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,158.95,0,0
HB-054606,City Hotel,1,379,2024,July,29,21,2024-07-21,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-090842,City Hotel,0,0,2024,June,24,11,2024-06-11,1,1,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,108.57,0,0
HB-002314,Resort Hotel,1,78,2023,October,41,9,2023-10-09,1,2,2,0.0,0,FB,ESP,Groups,TA/TO,0,0,0,A,A,0,Non Refund,134.0,,0,Transient,92.0,0,0
HB-091480,City Hotel,0,125,2024,June,25,19,2024-06-19,2,1,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,102.8,0,2
HB-025370,Resort Hotel,0,161,2024,June,25,17,2024-06-17,2,5,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,78.5,0,0
HB-100944,City Hotel,0,183,2024,October,44,31,2024-10-31,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,B,A,1,No Deposit,9.0,,0,Transient,83.5,0,2
HB-015741,Resort Hotel,0,42,2023,July,30,27,2023-07-27,1,4,2,0.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient,133.0,0,0
HB-111988,City Hotel,0,77,2025,May,20,14,2025-05-14,2,3,2,0.0,0,BB,CHE,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,117.0,0,1
HB-013150,Resort Hotel,1,231,2025,August,31,2,2025-08-02,2,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,253.33,0,1
HB-111157,City Hotel,0,7,2025,May,18,3,2025-05-03,0,4,2,2.0,0,HB,ESP,Direct,Direct,0,0,0,G,G,1,No Deposit,14.0,,0,Transient,316.0,0,1
HB-053226,City Hotel,1,77,2024,June,25,17,2024-06-17,0,2,2,0.0,0,SC,HKG,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,116.1,0,0
HB-080621,City Hotel,0,12,2024,March,11,12,2024-03-12,0,1,1,0.0,0,BB,PRT,Direct,Direct,1,0,1,A,A,0,No Deposit,14.0,,0,Transient,97.0,0,0
HB-006695,Resort Hotel,1,170,2024,June,26,25,2024-06-25,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,72.0,0,2
HB-033022,Resort Hotel,0,2,2025,February,7,10,2025-02-10,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,2
HB-067951,City Hotel,1,35,2025,May,19,10,2025-05-10,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,39.0,,0,Transient-Party,130.0,0,0
HB-041780,City Hotel,0,53,2023,August,34,24,2023-08-24,1,1,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-112992,City Hotel,0,113,2025,May,22,30,2025-05-30,0,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,103.95,0,1
HB-029806,Resort Hotel,0,17,2024,November,45,5,2024-11-05,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient-Party,72.0,0,0
HB-028259,Resort Hotel,0,156,2024,September,38,21,2024-09-21,1,4,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,95.0,0,1
HB-038321,Resort Hotel,0,148,2025,July,28,10,2025-07-10,1,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,142.0,0,0
HB-089387,City Hotel,0,198,2024,May,21,20,2024-05-20,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,98,Transient-Party,65.0,0,0
HB-105764,City Hotel,0,26,2025,February,7,14,2025-02-14,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-093642,City Hotel,0,171,2024,July,29,20,2024-07-20,0,4,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,95.2,0,1
HB-090480,City Hotel,0,2,2024,June,23,6,2024-06-06,1,0,2,0.0,0,BB,PRT,Complementary,Direct,0,0,0,G,G,0,No Deposit,,,0,Transient,0.0,1,1
HB-029174,Resort Hotel,0,386,2024,October,42,20,2024-10-20,0,3,2,1.0,0,BB,GBR,Groups,Corporate,0,0,0,A,D,1,No Deposit,,,0,Transient-Party,60.0,0,1
HB-110619,City Hotel,0,28,2025,April,18,29,2025-04-29,0,1,2,0.0,0,SC,HKG,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,115.0,0,3
HB-019070,Resort Hotel,0,11,2023,December,49,5,2023-12-05,2,1,2,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,350.0,,0,Transient-Party,68.0,0,0
HB-055988,City Hotel,1,178,2024,August,35,26,2024-08-26,0,2,2,1.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,83.0,,0,Transient,117.6,0,0
HB-016425,Resort Hotel,0,15,2023,August,34,22,2023-08-22,2,5,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,F,G,1,No Deposit,,,0,Transient,258.43,1,0
HB-030038,Resort Hotel,0,67,2024,November,45,6,2024-11-06,2,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,E,F,0,No Deposit,240.0,,0,Transient,55.8,0,2
HB-081678,City Hotel,1,182,2024,April,17,27,2024-04-27,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,3.0,,50,Transient,75.0,0,0
HB-091639,City Hotel,0,2,2024,June,25,23,2024-06-23,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.0,0,1
HB-039256,Resort Hotel,0,233,2025,August,31,2,2025-08-02,2,9,3,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,143.57,0,2
HB-023371,Resort Hotel,0,3,2024,April,17,22,2024-04-22,0,2,1,0.0,0,BB,FRA,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient-Party,85.0,0,0
HB-067261,City Hotel,1,111,2025,April,18,30,2025-04-30,2,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,123.75,0,0
HB-106340,City Hotel,0,49,2025,February,8,21,2025-02-21,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,95.4,0,1
HB-016540,Resort Hotel,0,67,2023,August,34,23,2023-08-23,4,6,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,137.65,0,1
HB-009189,Resort Hotel,1,378,2024,November,44,1,2024-11-01,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,248.0,,0,Transient,46.0,0,0
HB-041893,City Hotel,0,8,2023,August,34,26,2023-08-26,0,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Contract,90.0,0,2
HB-049923,City Hotel,1,39,2024,April,16,20,2024-04-20,1,4,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,120.6,0,0
HB-083334,City Hotel,0,59,2024,January,4,28,2024-01-28,0,1,1,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,87.0,,0,Transient-Party,81.0,0,0
HB-078978,City Hotel,0,221,2023,October,42,17,2023-10-17,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,65.0,0,0
HB-073851,City Hotel,1,307,2023,August,33,20,2023-08-20,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-004763,Resort Hotel,0,169,2024,March,13,31,2024-03-31,1,3,3,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,C,1,Refundable,,223.0,0,Transient-Party,101.0,0,0
HB-069534,City Hotel,1,19,2025,June,22,1,2025-06-01,0,3,3,0.0,0,BB,IND,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,203.33,0,1
HB-103604,City Hotel,0,107,2024,December,51,21,2024-12-21,2,5,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,4,No Deposit,9.0,,0,Transient,76.69,0,1
HB-072694,City Hotel,1,110,2025,August,31,3,2025-08-03,0,3,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,195.0,0,1
HB-117364,City Hotel,0,208,2025,August,31,2,2025-08-02,0,1,2,0.0,0,HB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,157.0,0,1
HB-094708,City Hotel,0,123,2024,August,31,1,2024-08-01,2,5,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,83.0,,0,Transient,91.7,0,0
HB-067878,City Hotel,1,82,2025,May,19,8,2025-05-08,1,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,141.0,0,0
HB-076720,City Hotel,0,0,2025,January,4,24,2025-01-24,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,1,6,60,A,A,1,No Deposit,,40.0,0,Transient,65.0,0,1
HB-005276,Resort Hotel,1,103,2024,April,17,23,2024-04-23,4,6,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,68.0,0,0
HB-024880,Resort Hotel,0,141,2024,May,22,31,2024-05-31,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,E,1,No Deposit,143.0,,0,Transient,86.7,0,2
HB-044927,City Hotel,0,65,2023,October,42,16,2023-10-16,0,1,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,10.0,,0,Transient,89.2,0,1
HB-084354,City Hotel,0,1,2024,February,8,24,2024-02-24,0,1,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,91.0,0,0
HB-022041,Resort Hotel,0,12,2024,October,41,10,2024-10-10,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,5,A,A,0,No Deposit,,113.0,0,Transient,45.0,0,0
HB-038917,Resort Hotel,0,256,2025,July,30,27,2025-07-27,2,5,2,1.0,0,FB,PRT,Direct,Direct,0,0,0,A,A,3,No Deposit,250.0,,0,Transient,241.81,1,0
HB-062554,City Hotel,1,1,2025,January,3,14,2025-01-14,2,1,2,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,83.0,,0,Transient,175.2,0,0
HB-102543,City Hotel,0,10,2024,November,48,28,2024-11-28,1,2,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.33,0,2
HB-033045,Resort Hotel,0,1,2025,February,7,11,2025-02-11,1,1,2,1.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,I,1,No Deposit,314.0,,0,Transient,0.0,1,0
HB-093535,City Hotel,0,292,2024,July,29,21,2024-07-21,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,0
HB-059364,City Hotel,1,37,2024,October,43,27,2024-10-27,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,94.36,0,1
HB-085864,City Hotel,0,42,2024,March,12,22,2024-03-22,0,1,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,131.4,0,1
HB-067702,City Hotel,1,407,2025,May,19,6,2025-05-06,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-018534,Resort Hotel,0,5,2023,November,47,21,2023-11-21,1,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,58.0,0,1
HB-117156,City Hotel,0,14,2025,July,31,28,2025-07-28,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,150.0,0,1
HB-080611,City Hotel,1,51,2023,December,52,30,2023-12-30,0,3,2,2.0,0,BB,PRT,Online TA,TA/TO,0,1,0,F,F,0,No Deposit,9.0,,0,Transient,199.33,0,0
HB-060810,City Hotel,1,42,2024,November,47,22,2024-11-22,0,3,2,0.0,0,BB,NLD,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,95.38,0,1
HB-018104,Resort Hotel,0,0,2023,November,44,4,2023-11-04,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,1,No Deposit,,,0,Transient-Party,40.0,0,0
HB-074499,City Hotel,1,325,2023,September,36,7,2023-09-07,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-009901,Resort Hotel,1,123,2025,January,3,19,2025-01-19,2,5,2,2.0,0,BB,POL,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,82.0,0,0
HB-084891,City Hotel,0,56,2024,March,9,3,2024-03-03,0,3,2,0.0,0,BB,ESP,Groups,Corporate,0,0,0,A,A,0,No Deposit,,,0,Transient,72.0,0,0
HB-009338,Resort Hotel,1,1,2024,November,46,14,2024-11-14,1,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,60.0,0,1
HB-033059,Resort Hotel,0,22,2025,February,7,12,2025-02-12,1,0,2,2.0,0,BB,USA,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,242.0,,0,Transient,73.06,0,1
HB-099754,City Hotel,0,108,2024,October,42,14,2024-10-14,1,2,1,2.0,0,BB,DEU,Online TA,TA/TO,0,0,0,F,G,0,No Deposit,9.0,,0,Transient,190.8,0,1
HB-083296,City Hotel,0,33,2024,January,4,25,2024-01-25,1,2,2,0.0,0,BB,BRA,Corporate,Corporate,0,0,0,A,A,1,No Deposit,38.0,,15,Transient-Party,64.0,0,0
HB-112823,City Hotel,0,344,2025,May,22,27,2025-05-27,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,98,Transient-Party,128.0,0,1
HB-077813,City Hotel,1,32,2023,October,42,20,2023-10-20,1,5,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,6.0,,0,Transient,79.11,0,0
HB-068746,City Hotel,1,420,2025,May,21,20,2025-05-20,2,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,B,1,Non Refund,229.0,,0,Transient,80.0,0,0
HB-065568,City Hotel,1,373,2025,April,14,5,2025-04-05,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-036945,Resort Hotel,0,2,2025,June,22,1,2025-06-01,0,1,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,D,0,No Deposit,250.0,,0,Transient,85.0,0,0
HB-034291,Resort Hotel,0,66,2025,March,12,18,2025-03-18,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,60.0,0,3
HB-036703,Resort Hotel,0,19,2025,May,21,22,2025-05-22,1,4,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,99.0,0,3
HB-012930,Resort Hotel,1,200,2025,July,30,23,2025-07-23,4,8,2,2.0,0,BB,CHE,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,244.0,0,0
HB-096826,City Hotel,0,11,2024,September,36,6,2024-09-06,0,3,1,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,87.01,0,1
HB-012700,Resort Hotel,1,134,2025,July,28,12,2025-07-12,0,4,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,C,C,2,No Deposit,240.0,,0,Transient,196.25,0,0
HB-044657,City Hotel,0,80,2023,October,41,9,2023-10-09,0,2,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,12.0,,50,Transient-Party,108.0,0,0
HB-009298,Resort Hotel,1,135,2024,November,45,10,2024-11-10,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,37.8,0,0
HB-083151,City Hotel,0,3,2024,January,3,21,2024-01-21,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient-Party,66.0,0,0
HB-094394,City Hotel,0,0,2025,June,24,14,2025-06-14,0,1,1,0.0,0,BB,PRT,Complementary,Direct,1,4,15,A,E,0,No Deposit,,,0,Transient,0.0,0,1
HB-037874,Resort Hotel,0,274,2025,June,25,18,2025-06-18,4,10,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,96.56,0,1
HB-026061,Resort Hotel,0,1,2024,July,29,18,2024-07-18,1,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,149.0,0,1
HB-035183,Resort Hotel,0,44,2025,April,15,8,2025-04-08,2,5,2,2.0,0,BB,HUN,Direct,Direct,0,0,0,G,G,1,No Deposit,250.0,,0,Transient,148.57,0,3
HB-046141,City Hotel,1,11,2023,December,50,16,2023-12-16,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,95.0,0,0
HB-083501,City Hotel,0,1,2024,February,5,3,2024-02-03,0,2,3,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,133.0,0,1
HB-074534,City Hotel,1,332,2023,September,37,14,2023-09-14,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-002648,Resort Hotel,1,148,2023,October,43,24,2023-10-24,0,1,1,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,39.0,0,0
HB-047093,City Hotel,0,45,2024,February,6,6,2024-02-06,2,2,1,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,46.9,0,1
HB-012897,Resort Hotel,1,151,2025,July,30,22,2025-07-22,2,5,3,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient,208.05,0,0
HB-048796,City Hotel,1,14,2024,March,13,30,2024-03-30,2,8,2,0.0,0,BB,AGO,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,132.0,0,0
HB-073569,City Hotel,1,79,2025,August,35,26,2025-08-26,2,3,3,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,240.0,0,0
HB-030850,Resort Hotel,0,63,2024,November,48,29,2024-11-29,2,5,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,29.72,0,1
HB-110326,City Hotel,0,31,2025,April,17,21,2025-04-21,2,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,85.0,0,0
HB-054386,City Hotel,1,120,2024,July,28,14,2024-07-14,0,2,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,121.5,0,0
HB-057441,City Hotel,0,418,2024,September,39,26,2024-09-26,1,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,132.0,,223,Transient-Party,107.0,0,0
HB-053060,City Hotel,1,188,2024,June,24,15,2024-06-15,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,39,Transient,130.0,0,0
HB-013341,Resort Hotel,1,199,2025,August,32,10,2025-08-10,3,8,2,1.0,0,BB,ESP,Direct,Direct,0,0,0,C,C,0,No Deposit,250.0,,0,Transient,163.33,0,0
HB-107622,City Hotel,0,28,2025,March,11,14,2025-03-14,0,2,1,0.0,0,BB,NLD,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,65.0,0,0
HB-032874,Resort Hotel,0,1,2025,February,6,7,2025-02-07,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,355.0,0,Transient,35.0,0,0
HB-018233,Resort Hotel,0,37,2023,November,45,7,2023-11-07,2,6,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,60.2,1,1
HB-098949,City Hotel,0,31,2024,October,40,4,2024-10-04,0,3,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,119.7,0,0
HB-019344,Resort Hotel,1,13,2023,December,50,17,2023-12-17,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,1,0,A,A,0,No Deposit,195.0,,0,Transient,35.0,0,0
HB-053589,City Hotel,1,121,2024,June,26,24,2024-06-24,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,90.0,0,0
HB-005440,Resort Hotel,1,108,2024,April,18,29,2024-04-29,2,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,84.0,0,0
HB-044731,City Hotel,1,174,2023,October,41,10,2023-10-10,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,70.0,0,0
HB-061268,City Hotel,1,113,2024,December,49,6,2024-12-06,0,4,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.3,0,3
HB-089017,City Hotel,0,61,2024,May,20,13,2024-05-13,1,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,121.5,0,0
HB-024314,Resort Hotel,0,106,2024,May,19,10,2024-05-10,2,5,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,314.0,,0,Transient,52.56,0,1
HB-116819,City Hotel,0,21,2025,July,30,24,2025-07-24,1,0,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-116181,City Hotel,0,215,2025,July,28,13,2025-07-13,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,99.9,0,1
HB-060716,City Hotel,1,11,2024,November,47,18,2024-11-18,6,14,2,0.0,0,SC,AGO,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,75.86,0,0
HB-083703,City Hotel,0,59,2024,February,6,6,2024-02-06,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-015494,Resort Hotel,0,86,2023,July,27,8,2023-07-08,4,10,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,5.0,,0,Transient,83.79,1,0
HB-116163,City Hotel,0,254,2025,July,27,6,2025-07-06,2,8,3,0.0,0,BB,DNK,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,156.6,0,2
HB-039551,Resort Hotel,0,212,2025,August,33,17,2025-08-17,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,153.75,0,0
HB-032562,Resort Hotel,0,3,2025,January,5,27,2025-01-27,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,35.11,0,1
HB-093639,City Hotel,0,163,2024,July,30,22,2024-07-22,0,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,94.5,0,0
HB-054876,City Hotel,1,386,2024,July,30,28,2024-07-28,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-016818,Resort Hotel,0,111,2023,September,36,10,2023-09-10,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,F,F,0,No Deposit,301.0,,0,Transient,109.65,0,0
HB-106755,City Hotel,0,0,2025,March,9,1,2025-03-01,0,1,1,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,A,0,No Deposit,,45.0,0,Transient,0.0,0,2
HB-112083,City Hotel,0,91,2025,May,20,18,2025-05-18,0,2,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,86.63,0,0
HB-093589,City Hotel,0,10,2024,July,30,23,2024-07-23,0,1,1,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,9.0,,0,Transient,166.0,0,0
HB-107604,City Hotel,0,63,2025,March,11,10,2025-03-10,2,4,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,78.5,0,1
HB-069392,City Hotel,1,186,2025,May,22,30,2025-05-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,130.0,0,0
HB-069540,City Hotel,1,174,2025,June,22,1,2025-06-01,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,110.0,0,0
HB-004436,Resort Hotel,0,148,2024,March,11,17,2024-03-17,2,5,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,40.5,0,0
HB-101699,City Hotel,0,7,2024,November,46,16,2024-11-16,0,1,1,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,95.0,0,0
HB-045745,City Hotel,1,98,2023,November,47,23,2023-11-23,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,70.0,0,0
HB-053072,City Hotel,1,188,2024,June,24,15,2024-06-15,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,39,Transient,130.0,0,0
HB-081504,City Hotel,0,14,2023,December,50,11,2023-12-11,0,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,81.0,0,1
HB-036506,Resort Hotel,0,97,2025,May,20,16,2025-05-16,2,5,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,85.59,0,0
HB-043470,City Hotel,0,74,2023,September,38,18,2023-09-18,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-096405,City Hotel,0,6,2024,August,35,29,2024-08-29,1,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,83.0,,0,Transient,123.2,0,0
HB-047951,City Hotel,0,67,2024,March,10,10,2024-03-10,1,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,75.95,0,0
HB-112390,City Hotel,0,12,2025,May,21,23,2025-05-23,0,1,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,110.0,0,1
HB-082237,City Hotel,1,203,2024,June,22,2,2024-06-02,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,41,Transient,65.0,0,0
HB-097335,City Hotel,0,346,2024,September,37,13,2024-09-13,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-065238,City Hotel,1,629,2025,March,13,30,2025-03-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-029503,Resort Hotel,0,47,2024,October,44,28,2024-10-28,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,70.0,0,0
HB-011725,Resort Hotel,1,337,2025,May,22,27,2025-05-27,2,5,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,102.21,0,0
HB-005563,Resort Hotel,0,199,2024,May,18,2,2024-05-02,1,1,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,85.0,0,0
HB-003415,Resort Hotel,1,45,2023,December,49,5,2023-12-05,2,1,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,38.0,,0,Transient-Party,68.0,0,0
HB-058310,City Hotel,1,83,2024,October,41,10,2024-10-10,1,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,132.3,0,0
HB-012896,Resort Hotel,1,159,2025,July,30,22,2025-07-22,2,5,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,212.0,0,0
HB-106631,City Hotel,0,8,2025,February,9,27,2025-02-27,1,0,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,128.0,0,0
HB-114369,City Hotel,0,90,2025,June,25,18,2025-06-18,2,1,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,1
HB-082569,City Hotel,0,97,2023,December,52,29,2023-12-29,0,4,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Transient,60.5,0,1
HB-033706,Resort Hotel,0,0,2025,February,9,28,2025-02-28,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,0
HB-019850,Resort Hotel,0,3,2024,January,1,3,2024-01-03,2,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,240.0,,0,Transient,48.0,0,1
HB-093627,City Hotel,0,162,2024,July,29,20,2024-07-20,0,4,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.13,1,0
HB-077957,City Hotel,0,19,2023,September,39,28,2023-09-28,1,1,1,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,170.0,0,0
HB-000546,Resort Hotel,0,44,2023,July,29,19,2023-07-19,2,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,92.0,0,0
HB-055877,City Hotel,1,29,2024,August,34,23,2024-08-23,0,5,3,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,D,D,0,No Deposit,133.0,,0,Transient,208.9,0,0
HB-044663,City Hotel,0,80,2023,October,41,9,2023-10-09,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,12.0,,50,Transient-Party,136.0,0,0
HB-112918,City Hotel,0,135,2025,May,22,26,2025-05-26,2,2,2,0.0,0,SC,LUX,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,111.0,0,1
HB-004263,Resort Hotel,1,5,2024,February,9,27,2024-02-27,1,1,2,2.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,C,C,1,No Deposit,196.0,,0,Transient,85.0,0,0
HB-005942,Resort Hotel,1,151,2024,May,20,17,2024-05-17,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,46.0,0,0
HB-014514,Resort Hotel,0,0,2023,December,49,6,2023-12-06,1,0,1,0.0,0,BB,,Direct,Direct,0,0,2,A,E,0,No Deposit,,,0,Transient,53.0,0,0
HB-078210,City Hotel,1,8,2023,October,40,6,2023-10-06,0,1,1,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,A,0,No Deposit,,45.0,0,Transient,0.0,0,0
HB-046715,City Hotel,1,8,2024,January,3,16,2024-01-16,2,5,2,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,78.3,0,0
HB-040039,Resort Hotel,0,191,2025,August,35,31,2025-08-31,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,114.8,0,0
HB-023472,Resort Hotel,0,190,2024,April,16,19,2024-04-19,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,115.0,,0,Transient,75.6,0,0
HB-108322,City Hotel,0,116,2025,March,13,24,2025-03-24,0,2,1,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,171.0,,0,Transient-Party,90.0,0,0
HB-074264,City Hotel,1,267,2023,July,28,11,2023-07-11,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-072821,City Hotel,1,148,2025,August,32,7,2025-08-07,1,3,2,1.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,148.5,0,0
HB-078366,City Hotel,0,0,2024,April,14,1,2024-04-01,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,0,A,A,0,No Deposit,,40.0,0,Transient-Party,67.0,1,0
HB-030045,Resort Hotel,0,0,2024,November,46,11,2024-11-11,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,85.0,0,0
HB-049590,City Hotel,1,15,2024,April,16,15,2024-04-15,1,2,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,154.33,0,0
HB-026728,Resort Hotel,0,12,2024,August,34,25,2024-08-25,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,1,0,1,A,C,0,No Deposit,240.0,,0,Transient,211.0,0,1
HB-022464,Resort Hotel,0,3,2024,March,12,24,2024-03-24,0,3,1,0.0,0,Undefined,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,387.0,,0,Transient-Party,62.0,0,0
HB-041998,City Hotel,0,145,2023,August,35,29,2023-08-29,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-017690,Resort Hotel,0,287,2023,October,41,15,2023-10-15,1,3,3,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,C,2,No Deposit,,223.0,0,Transient-Party,62.5,0,0
HB-050403,City Hotel,0,145,2024,April,18,29,2024-04-29,2,4,1,1.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,69.56,0,0
HB-085153,City Hotel,0,16,2024,March,10,8,2024-03-08,0,3,1,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,D,D,2,No Deposit,,209.0,0,Transient-Party,76.0,0,0
HB-098549,City Hotel,0,2,2024,September,40,30,2024-09-30,0,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,205.0,0,2
HB-048952,City Hotel,1,72,2024,April,14,3,2024-04-03,2,1,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,87.3,0,0
HB-064235,City Hotel,1,27,2025,March,9,2,2025-03-02,0,3,1,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,0
HB-007268,Resort Hotel,1,96,2024,July,31,31,2024-07-31,2,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,241.0,0,0
HB-082795,City Hotel,1,68,2024,February,7,17,2024-02-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,37.0,,0,Transient,75.0,0,0
HB-017240,Resort Hotel,0,0,2023,October,39,1,2023-10-01,0,1,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient,120.0,1,0
HB-034759,Resort Hotel,0,0,2025,April,14,3,2025-04-03,1,0,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,68.0,0,0
HB-059665,City Hotel,1,50,2024,October,44,30,2024-10-30,2,3,2,0.0,0,HB,HUN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,162.4,0,1
HB-104102,City Hotel,0,28,2025,January,1,3,2025-01-03,0,3,1,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.0,0,1
HB-040475,City Hotel,1,81,2023,July,30,26,2023-07-26,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,1
HB-027059,Resort Hotel,0,1,2024,August,33,18,2024-08-18,0,1,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,179.0,0,2
HB-048503,City Hotel,0,97,2024,March,12,24,2024-03-24,1,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,64.98,0,1
HB-018328,Resort Hotel,0,82,2024,February,6,7,2024-02-07,2,0,2,0.0,0,Undefined,PRT,Groups,TA/TO,1,0,0,A,A,0,No Deposit,67.0,,0,Transient-Party,72.0,0,0
HB-037806,Resort Hotel,0,0,2025,June,26,29,2025-06-29,0,1,1,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,0.0,0,0
HB-100320,City Hotel,0,3,2024,October,43,23,2024-10-23,2,1,1,0.0,0,BB,BEL,Aviation,Corporate,0,0,0,D,E,0,No Deposit,,153.0,0,Transient,110.0,0,0
HB-094047,City Hotel,0,2,2024,December,51,21,2024-12-21,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,E,E,1,No Deposit,,51.0,0,Transient,105.0,0,0
HB-046537,City Hotel,0,33,2024,January,1,5,2024-01-05,0,3,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,87.5,0,0
HB-039702,Resort Hotel,0,210,2025,August,34,19,2025-08-19,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,261.0,,0,Transient,135.9,1,0
HB-055085,City Hotel,1,391,2024,August,31,4,2024-08-04,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-036857,Resort Hotel,0,1,2025,May,22,28,2025-05-28,2,1,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,240.0,,0,Transient,109.8,0,1
HB-041704,City Hotel,0,138,2023,August,34,22,2023-08-22,2,1,3,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,17.0,,0,Transient-Party,138.5,0,1
HB-085478,City Hotel,0,31,2024,March,11,14,2024-03-14,1,1,2,0.0,0,BB,TUR,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient-Party,81.9,0,1
HB-056155,City Hotel,1,82,2024,August,35,30,2024-08-30,0,5,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,F,F,2,No Deposit,9.0,,0,Transient,202.5,0,0
HB-043185,City Hotel,0,37,2023,September,37,16,2023-09-16,0,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient-Party,94.5,1,0
HB-053400,City Hotel,1,14,2024,June,25,20,2024-06-20,1,1,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,177.0,0,0
HB-001984,Resort Hotel,1,67,2023,September,39,25,2023-09-25,2,4,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,109.0,0,2
HB-034002,Resort Hotel,0,3,2025,March,10,6,2025-03-06,1,4,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,68.4,0,0
HB-059847,City Hotel,1,304,2024,November,44,3,2024-11-03,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,89.0,0,0
HB-094400,City Hotel,0,0,2025,August,33,15,2025-08-15,0,1,1,0.0,0,BB,PRT,Complementary,Direct,1,5,20,A,A,0,No Deposit,,45.0,0,Transient,0.0,0,3
HB-081921,City Hotel,1,278,2024,August,32,11,2024-08-11,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,65.0,0,0
HB-082112,City Hotel,0,13,2024,June,24,14,2024-06-14,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,7,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,1
HB-056426,City Hotel,1,232,2024,September,36,5,2024-09-05,1,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,100.3,0,0
HB-049180,City Hotel,1,274,2024,April,14,7,2024-04-07,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-018251,Resort Hotel,0,0,2023,November,46,14,2023-11-14,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,63.0,0,0
HB-107586,City Hotel,0,6,2025,March,11,14,2025-03-14,0,1,1,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-118511,City Hotel,0,9,2025,August,34,20,2025-08-20,1,0,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,9.0,,0,Transient,198.0,0,0
HB-099860,City Hotel,0,25,2024,October,42,17,2024-10-17,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-114762,City Hotel,0,396,2025,June,26,25,2025-06-25,2,0,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,95.5,0,1
HB-082311,City Hotel,0,27,2023,December,51,22,2023-12-22,1,5,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,48.33,0,0
HB-077189,City Hotel,0,0,2023,September,36,10,2023-09-10,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,152.0,0,0
HB-116272,City Hotel,0,9,2025,July,29,14,2025-07-14,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,132.0,0,1
HB-108261,City Hotel,0,61,2025,March,12,21,2025-03-21,0,4,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,85.0,,0,Transient,76.5,0,0
HB-019222,Resort Hotel,1,92,2024,February,9,26,2024-02-26,1,2,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,134.0,,0,Transient,79.0,0,0
HB-062989,City Hotel,1,61,2025,January,4,25,2025-01-25,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,326.0,,0,Transient,80.0,0,0
HB-083865,City Hotel,0,4,2024,February,7,13,2024-02-13,0,1,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,72.8,0,0
HB-100206,City Hotel,0,386,2024,October,43,23,2024-10-23,2,0,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-024927,Resort Hotel,0,123,2024,June,23,4,2024-06-04,2,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,57.6,0,0
HB-092300,City Hotel,0,136,2024,June,26,30,2024-06-30,1,3,2,0.0,0,HB,CZE,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient-Party,123.25,0,0
HB-068757,City Hotel,1,113,2025,May,21,20,2025-05-20,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,34.0,,0,Transient,190.0,0,0
HB-099941,City Hotel,0,9,2024,October,42,20,2024-10-20,0,1,1,0.0,0,BB,CHE,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,174.0,0,Transient,95.0,0,0
HB-024972,Resort Hotel,0,27,2024,June,23,9,2024-06-09,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient,141.0,1,1
HB-110591,City Hotel,0,78,2025,April,17,25,2025-04-25,0,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,121.5,0,1
HB-026692,Resort Hotel,0,174,2024,August,31,1,2024-08-01,2,5,2,1.0,0,Undefined,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,196.0,,0,Transient-Party,177.5,0,2
HB-010061,Resort Hotel,1,238,2025,February,7,10,2025-02-10,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,155.0,,0,Transient,54.0,0,0
HB-005641,Resort Hotel,1,80,2024,May,19,7,2024-05-07,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,58.0,0,0
HB-016850,Resort Hotel,0,254,2023,September,37,12,2023-09-12,2,2,2,0.0,0,BB,CN,Groups,TA/TO,0,0,0,A,A,1,No Deposit,15.0,,0,Transient-Party,36.0,0,0
HB-046229,City Hotel,0,5,2023,December,52,26,2023-12-26,2,2,2,0.0,0,SC,FIN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,63.0,0,0
HB-093785,City Hotel,0,167,2024,July,30,25,2024-07-25,1,1,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient-Party,72.25,0,1
HB-060329,City Hotel,1,277,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-035570,Resort Hotel,0,71,2025,April,16,19,2025-04-19,2,6,2,0.0,0,BB,AUS,Direct,Direct,0,0,0,F,F,2,No Deposit,250.0,,0,Transient-Party,104.5,0,0
HB-054914,City Hotel,1,301,2024,July,31,30,2024-07-30,1,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-101617,City Hotel,0,48,2024,November,46,13,2024-11-13,2,0,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-064098,City Hotel,1,601,2025,March,9,2,2025-03-02,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-113206,City Hotel,0,154,2025,May,22,31,2025-05-31,0,4,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,135.0,0,1
HB-089342,City Hotel,0,63,2024,May,20,17,2024-05-17,0,3,1,0.0,0,BB,GBR,Offline TA/TO,GDS,0,0,0,A,A,0,No Deposit,195.0,,0,Transient,136.0,0,0
HB-026798,Resort Hotel,0,6,2024,August,31,4,2024-08-04,2,5,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,229.71,0,1
HB-102631,City Hotel,0,53,2024,November,48,29,2024-11-29,0,4,0,2.0,0,BB,ROU,Online TA,TA/TO,0,0,0,B,A,0,No Deposit,9.0,,0,Transient,77.86,0,2
HB-020121,Resort Hotel,0,1,2024,January,3,16,2024-01-16,0,1,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,76.0,0,2
HB-103784,City Hotel,0,39,2024,December,52,28,2024-12-28,0,4,2,0.0,0,BB,SVN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,115.6,0,1
HB-013571,Resort Hotel,1,161,2025,August,34,20,2025-08-20,2,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,236.0,0,1
HB-063436,City Hotel,1,88,2025,February,7,12,2025-02-12,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,21,Transient,80.0,0,0
HB-109939,City Hotel,0,55,2025,April,16,17,2025-04-17,1,1,2,0.0,0,SC,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-056014,City Hotel,1,48,2024,August,35,26,2024-08-26,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,133.74,0,1
HB-058975,City Hotel,1,210,2024,October,42,19,2024-10-19,0,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.3,0,2
HB-025930,Resort Hotel,0,31,2024,July,28,9,2024-07-09,2,5,2,1.0,0,BB,IRL,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,242.0,,0,Transient,214.87,0,1
HB-028583,Resort Hotel,0,59,2024,October,40,5,2024-10-05,0,1,2,0.0,0,BB,USA,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,,0,Transient,89.1,1,0
HB-108316,City Hotel,0,116,2025,March,13,24,2025-03-24,0,2,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,171.0,,0,Transient-Party,100.0,0,1
HB-072433,City Hotel,1,147,2025,July,31,28,2025-07-28,1,2,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.5,0,0
HB-094760,City Hotel,0,115,2024,August,31,4,2024-08-04,2,3,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,110.7,0,2
HB-064016,City Hotel,1,17,2025,February,9,26,2025-02-26,2,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,D,D,0,No Deposit,30.0,,0,Transient-Party,75.0,0,0
HB-015637,Resort Hotel,0,24,2023,July,29,23,2023-07-23,2,5,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,242.0,,0,Transient,179.0,0,1
HB-077605,City Hotel,0,5,2023,September,38,19,2023-09-19,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,9.0,,0,Contract,140.75,0,2
HB-092725,City Hotel,0,110,2024,July,28,8,2024-07-08,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.3,0,1
HB-029149,Resort Hotel,0,72,2024,October,42,20,2024-10-20,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,251.0,,0,Transient,59.0,0,0
HB-089291,City Hotel,0,29,2024,May,20,17,2024-05-17,0,3,1,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,90.0,0,0
HB-101274,City Hotel,0,21,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,200.0,0,1
HB-090746,City Hotel,0,1,2024,June,24,10,2024-06-10,0,1,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,200.0,0,0
HB-071013,City Hotel,1,138,2025,June,26,27,2025-06-27,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,0
HB-045969,City Hotel,1,104,2023,December,48,3,2023-12-03,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,55.0,,0,Transient,75.0,0,0
HB-065208,City Hotel,1,120,2025,March,13,28,2025-03-28,0,3,2,0.0,0,SC,CN,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,88.0,0,0
HB-055574,City Hotel,1,148,2024,August,33,16,2024-08-16,2,5,2,0.0,0,BB,SVN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,119.69,0,0
HB-066104,City Hotel,1,103,2025,April,16,14,2025-04-14,1,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,181.5,0,1
HB-080121,City Hotel,1,72,2023,December,52,27,2023-12-27,2,0,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,90.0,0,0
HB-038524,Resort Hotel,0,197,2025,July,29,15,2025-07-15,2,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,164.63,1,2
HB-017720,Resort Hotel,1,8,2023,October,43,24,2023-10-24,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,1,0,A,A,0,No Deposit,,135.0,0,Transient,48.0,0,0
HB-096521,City Hotel,0,64,2024,September,36,2,2024-09-02,0,2,2,0.0,0,BB,CN,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,82.45,0,0
HB-053878,City Hotel,1,44,2024,July,27,1,2024-07-01,0,2,2,2.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient-Party,156.95,0,1
HB-026210,Resort Hotel,0,22,2024,July,30,22,2024-07-22,1,2,2,0.0,0,BB,SVN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,339.0,,0,Transient,157.87,0,0
HB-118691,City Hotel,0,175,2025,August,34,21,2025-08-21,1,2,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,135.0,0,2
HB-036772,Resort Hotel,0,107,2025,May,21,21,2025-05-21,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,52.85,0,1
HB-001267,Resort Hotel,0,0,2023,August,34,22,2023-08-22,0,1,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,A,C,0,No Deposit,,,0,Transient,172.0,0,0
HB-118088,City Hotel,0,181,2025,August,33,11,2025-08-11,2,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,100.48,0,0
HB-014113,Resort Hotel,0,127,2024,April,17,25,2024-04-25,3,5,2,0.0,0,BB,IRL,Direct,Direct,0,0,1,E,E,2,No Deposit,,,0,Transient,61.0,0,1
HB-008270,Resort Hotel,0,343,2024,September,38,21,2024-09-21,0,4,2,0.0,0,HB,BEL,Corporate,Corporate,0,0,0,A,A,0,No Deposit,183.0,,0,Transient-Party,92.0,0,0
HB-016726,Resort Hotel,0,47,2024,September,36,3,2024-09-03,2,5,2,0.0,0,BB,PRT,Direct,TA/TO,1,0,1,F,F,0,No Deposit,,,0,Transient,186.6,1,0
HB-028298,Resort Hotel,0,186,2024,September,39,23,2024-09-23,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,95.0,0,1
HB-080432,City Hotel,1,34,2023,December,49,8,2023-12-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,0,Transient,90.0,0,0
HB-112781,City Hotel,0,128,2025,May,22,26,2025-05-26,0,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient-Party,135.0,0,2
HB-105837,City Hotel,0,25,2025,February,7,11,2025-02-11,2,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,68.0,0,0
HB-073204,City Hotel,1,216,2025,August,33,16,2025-08-16,0,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,124.65,0,0
HB-036230,Resort Hotel,0,116,2025,May,19,11,2025-05-11,0,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient-Party,100.0,0,2
HB-100366,City Hotel,0,161,2024,October,43,25,2024-10-25,0,2,2,0.0,0,SC,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.1,0,3
HB-045307,City Hotel,0,69,2023,October,43,25,2023-10-25,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,D,0,No Deposit,37.0,,58,Transient-Party,85.67,0,0
HB-000210,Resort Hotel,0,112,2023,July,27,7,2023-07-07,4,10,2,0.0,0,HB,IRL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,156.0,,0,Contract,126.65,0,1
HB-016967,Resort Hotel,0,35,2023,September,38,18,2023-09-18,0,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,E,G,1,No Deposit,240.0,,0,Transient,114.0,0,2
HB-098640,City Hotel,0,159,2024,September,39,28,2024-09-28,1,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,133.2,0,1
HB-059658,City Hotel,1,159,2024,October,44,30,2024-10-30,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient,83.5,0,2
HB-091859,City Hotel,0,192,2024,June,26,24,2024-06-24,0,2,1,0.0,0,BB,SRB,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,34.0,,0,Transient-Party,95.0,0,0
HB-024329,Resort Hotel,0,105,2024,May,20,13,2024-05-13,2,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,75.0,0,1
HB-096513,City Hotel,0,8,2024,September,36,2,2024-09-02,0,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.0,0,1
HB-014830,Resort Hotel,1,222,2023,September,37,15,2023-09-15,1,5,2,0.0,0,FB,PRT,Groups,Corporate,0,25,0,A,A,0,Non Refund,252.0,,0,Transient,49.95,0,0
HB-099152,City Hotel,0,338,2024,October,41,7,2024-10-07,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,68,Transient-Party,90.67,0,1
HB-036713,Resort Hotel,0,203,2025,May,21,25,2025-05-25,0,3,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,4,No Deposit,,223.0,0,Transient-Party,49.0,1,0
HB-005990,Resort Hotel,1,41,2024,May,20,19,2024-05-19,0,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,105.0,0,0
HB-108718,City Hotel,0,81,2025,March,13,28,2025-03-28,0,4,3,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,103.41,0,1
HB-059390,City Hotel,1,30,2024,October,44,28,2024-10-28,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,103.0,,0,Transient,127.15,0,0
HB-079175,City Hotel,0,0,2023,October,42,22,2023-10-22,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,D,D,0,No Deposit,1.0,,0,Transient,60.0,0,0
HB-105868,City Hotel,0,29,2025,February,7,14,2025-02-14,0,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,80.0,0,2
HB-113988,City Hotel,0,7,2025,June,24,14,2025-06-14,0,1,2,1.0,0,BB,PRT,Complementary,Direct,0,0,0,A,D,1,No Deposit,,45.0,0,Transient,0.0,0,2
HB-052909,City Hotel,1,71,2024,June,24,14,2024-06-14,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,120.0,0,0
HB-015547,Resort Hotel,0,96,2023,July,29,18,2023-07-18,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,5.0,,0,Transient,96.3,0,0
HB-023110,Resort Hotel,0,112,2024,April,15,9,2024-04-09,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,156.0,,0,Transient,42.83,0,0
HB-075316,City Hotel,1,304,2023,August,33,17,2023-08-17,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-110187,City Hotel,0,173,2025,April,17,21,2025-04-21,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,2
HB-040526,City Hotel,0,126,2023,July,30,27,2023-07-27,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient-Party,85.5,1,1
HB-041944,City Hotel,0,4,2023,August,34,27,2023-08-27,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient,79.0,0,2
HB-041842,City Hotel,1,50,2023,August,34,25,2023-08-25,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-077147,City Hotel,1,0,2023,October,43,28,2023-10-28,0,2,2,0.0,0,BB,PRT,Complementary,Direct,1,0,5,A,F,0,No Deposit,,45.0,0,Transient,0.0,0,1
HB-081053,City Hotel,1,86,2024,January,4,22,2024-01-22,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,29.0,,35,Transient,75.0,0,0
HB-094628,City Hotel,0,131,2024,August,32,5,2024-08-05,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,76.23,0,2
HB-097153,City Hotel,0,31,2024,September,37,9,2024-09-09,2,2,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,149.4,0,2
HB-067844,City Hotel,1,42,2025,May,19,8,2025-05-08,1,2,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,139.0,0,1
HB-053726,City Hotel,1,100,2024,June,26,28,2024-06-28,0,1,2,1.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,130.5,0,2
HB-004607,Resort Hotel,1,106,2024,March,12,24,2024-03-24,1,3,2,0.0,0,FB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,68.0,,0,Transient,84.0,0,0
HB-008510,Resort Hotel,1,158,2024,October,40,2,2024-10-02,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,96.0,,0,Transient,46.0,0,1
HB-089258,City Hotel,0,64,2024,May,20,17,2024-05-17,0,2,1,0.0,0,BB,RUS,Corporate,TA/TO,0,0,0,A,B,0,No Deposit,,218.0,0,Transient-Party,130.0,0,0
HB-017329,Resort Hotel,0,202,2023,September,39,29,2023-09-29,2,5,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,E,G,0,No Deposit,250.0,,0,Transient,104.67,0,1
HB-002831,Resort Hotel,0,25,2023,October,44,31,2023-10-31,2,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,46.65,1,1
HB-066633,City Hotel,1,237,2025,April,17,22,2025-04-22,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,113.4,0,0
HB-018629,Resort Hotel,0,1,2025,March,9,1,2025-03-01,0,1,1,0.0,0,BB,PRT,Direct,Direct,1,0,5,A,A,0,No Deposit,250.0,399.0,0,Transient,34.2,0,1
HB-074870,City Hotel,1,164,2023,August,33,14,2023-08-14,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-111871,City Hotel,0,96,2025,May,20,14,2025-05-14,2,1,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,138.0,0,0
HB-013625,Resort Hotel,1,63,2025,August,34,23,2025-08-23,2,5,1,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,429.0,,0,Transient,174.54,0,0
HB-077267,City Hotel,1,5,2023,September,38,20,2023-09-20,2,0,2,0.0,0,BB,PRT,Corporate,Corporate,1,1,0,A,A,0,Non Refund,78.0,,0,Transient,100.0,0,0
HB-024921,Resort Hotel,0,86,2024,June,22,2,2024-06-02,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,243.0,,0,Contract,90.9,0,0
HB-021611,Resort Hotel,0,26,2024,March,9,1,2024-03-01,0,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,E,F,0,No Deposit,314.0,,0,Transient,60.4,1,0
HB-075912,City Hotel,1,274,2023,July,29,18,2023-07-18,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-015892,Resort Hotel,0,0,2023,August,31,4,2023-08-04,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,0,No Deposit,,,0,Transient,217.0,0,0
HB-026756,Resort Hotel,0,187,2024,August,32,8,2024-08-08,1,1,2,0.0,0,BB,CN,Direct,TA/TO,0,0,0,A,D,0,No Deposit,,,0,Transient,140.0,0,2
HB-074509,City Hotel,1,325,2023,September,36,7,2023-09-07,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-006115,Resort Hotel,1,276,2024,May,21,26,2024-05-26,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,46.98,0,1
HB-037847,Resort Hotel,0,295,2025,June,25,21,2025-06-21,2,8,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,107.1,0,2
HB-019379,Resort Hotel,0,2,2023,December,50,16,2023-12-16,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,,0,Transient,38.0,0,0
HB-060427,City Hotel,1,69,2024,November,45,10,2024-11-10,1,3,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,104.18,0,2
HB-054058,City Hotel,1,245,2024,July,27,6,2024-07-06,2,4,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,110.0,0,0
HB-106923,City Hotel,0,21,2025,March,10,4,2025-03-04,0,1,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,1
HB-114609,City Hotel,0,149,2025,June,26,24,2025-06-24,0,1,2,0.0,0,HB,USA,Corporate,Corporate,0,0,0,A,B,1,No Deposit,495.0,,0,Transient-Party,154.0,0,1
HB-002229,Resort Hotel,1,328,2023,October,40,6,2023-10-06,2,5,20,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,1,No Deposit,,,0,Group,0.0,0,0
HB-013930,Resort Hotel,0,112,2024,September,38,19,2024-09-19,5,10,1,0.0,0,BB,PRT,Direct,Direct,0,0,1,A,A,0,No Deposit,,,0,Transient,56.0,1,1
HB-022167,Resort Hotel,0,71,2024,March,11,17,2024-03-17,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,59.4,0,2
HB-052187,City Hotel,1,71,2024,June,22,1,2024-06-01,1,4,3,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,22.0,,0,Transient,115.6,0,0
HB-038064,Resort Hotel,0,166,2025,June,26,25,2025-06-25,4,10,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,243.0,,0,Transient,110.0,0,0
HB-061042,City Hotel,1,510,2024,December,48,1,2024-12-01,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,51.4,0,0
HB-002868,Resort Hotel,0,24,2023,November,44,3,2023-11-03,0,3,2,0.0,0,BB,ESP,Corporate,Corporate,0,0,0,A,A,1,No Deposit,334.0,281.0,0,Transient-Party,48.0,0,0
HB-078029,City Hotel,0,16,2023,September,39,30,2023-09-30,0,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,97.02,0,1
HB-043663,City Hotel,0,71,2023,September,38,22,2023-09-22,0,3,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,21.0,,0,Transient-Party,85.0,0,0
HB-030997,Resort Hotel,0,22,2024,December,50,9,2024-12-09,0,2,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient-Party,55.0,0,0
HB-056851,City Hotel,1,317,2024,September,37,15,2024-09-15,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,120.0,0,0
HB-106345,City Hotel,0,48,2025,February,8,22,2025-02-22,0,2,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,65.0,0,1
HB-058161,City Hotel,1,443,2024,October,41,7,2024-10-07,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,391,Transient,65.0,0,0
HB-046785,City Hotel,0,151,2024,January,3,19,2024-01-19,0,3,1,0.0,0,BB,ROU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,19.0,,63,Transient-Party,70.0,0,0
HB-110469,City Hotel,0,102,2025,April,17,24,2025-04-24,1,3,1,0.0,0,BB,IRL,Groups,TA/TO,0,0,0,A,A,1,No Deposit,,424.0,0,Transient-Party,90.0,0,0
HB-072493,City Hotel,1,276,2025,July,31,29,2025-07-29,2,1,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,156.6,0,3
HB-027822,Resort Hotel,0,234,2024,September,37,9,2024-09-09,1,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,75.03,0,1
HB-014603,Resort Hotel,0,37,2025,August,33,12,2025-08-12,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,0,No Deposit,250.0,,0,Transient,275.25,1,1
HB-046307,City Hotel,0,159,2023,December,52,29,2023-12-29,0,4,2,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,3.0,,111,Transient-Party,70.5,0,0
HB-012529,Resort Hotel,1,157,2025,July,27,3,2025-07-03,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,196.0,,0,Transient,158.57,0,0
HB-071884,City Hotel,1,39,2025,July,29,15,2025-07-15,0,1,1,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,0
HB-116745,City Hotel,0,256,2025,July,30,21,2025-07-21,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,107.1,0,2
HB-085455,City Hotel,0,30,2024,March,11,13,2024-03-13,2,1,2,0.0,1,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-052659,City Hotel,1,337,2024,June,23,9,2024-06-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-102693,City Hotel,0,29,2024,December,49,2,2024-12-02,0,2,2,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,85.0,0,0
HB-029746,Resort Hotel,0,200,2024,October,44,29,2024-10-29,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,171.0,,0,Transient,46.51,0,0
HB-109646,City Hotel,0,112,2025,April,15,12,2025-04-12,0,3,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,105.0,0,2
HB-018903,Resort Hotel,0,2,2023,December,48,2,2023-12-02,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,,0,Transient,38.0,0,0
HB-084304,City Hotel,0,12,2024,February,8,20,2024-02-20,2,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.0,0,0
HB-072371,City Hotel,1,153,2025,July,30,27,2025-07-27,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,166.5,0,0
HB-099876,City Hotel,0,54,2024,October,42,16,2024-10-16,2,2,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,21.0,,0,Transient-Party,66.5,0,0
HB-030169,Resort Hotel,0,29,2024,November,46,15,2024-11-15,0,1,1,0.0,0,BB,FRA,Groups,Corporate,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,48.0,0,0
HB-022598,Resort Hotel,0,0,2024,March,13,30,2024-03-30,0,1,2,0.0,0,BB,PRT,Direct,Direct,1,0,0,A,A,0,No Deposit,,,0,Transient,48.0,0,0
HB-098927,City Hotel,0,47,2024,October,40,2,2024-10-02,2,3,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,7.0,,0,Transient,79.0,0,2
HB-009238,Resort Hotel,1,201,2024,November,45,5,2024-11-05,1,1,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,37.8,0,0
HB-009752,Resort Hotel,1,156,2024,December,1,30,2024-12-30,1,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,173.1,0,0
HB-004520,Resort Hotel,1,60,2024,March,12,22,2024-03-22,0,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,83.4,0,1
HB-029440,Resort Hotel,0,91,2024,October,43,22,2024-10-22,2,5,3,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,128.14,1,0
HB-082017,City Hotel,1,115,2024,March,12,20,2024-03-20,2,0,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,41.0,,22,Transient,70.0,0,0
HB-018215,Resort Hotel,0,42,2023,November,45,10,2023-11-10,0,5,2,1.0,0,BB,ESP,Direct,Direct,0,0,0,H,H,3,No Deposit,250.0,,0,Transient,114.0,1,0
HB-106484,City Hotel,0,134,2025,February,9,25,2025-02-25,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,75.0,0,0
HB-081601,City Hotel,0,4,2024,March,10,7,2024-03-07,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,2,A,A,0,No Deposit,,40.0,0,Transient,66.0,0,0
HB-117376,City Hotel,0,159,2025,July,31,31,2025-07-31,1,2,2,3.0,0,BB,BEL,Direct,Direct,0,0,0,G,G,0,No Deposit,14.0,,0,Transient,260.0,0,1
HB-102645,City Hotel,0,0,2024,December,49,2,2024-12-02,0,2,2,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,0.0,0,0
HB-074149,City Hotel,1,342,2023,September,38,24,2023-09-24,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-030525,Resort Hotel,0,47,2024,November,47,21,2024-11-21,1,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,3,No Deposit,240.0,,0,Transient,37.8,0,1
HB-012880,Resort Hotel,1,28,2025,July,30,22,2025-07-22,2,4,2,2.0,0,HB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,353.0,0,0
HB-049798,City Hotel,1,103,2024,April,16,19,2024-04-19,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,0,Transient,115.0,0,0
HB-058354,City Hotel,1,67,2024,October,41,11,2024-10-11,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,99.71,0,0
HB-049159,City Hotel,1,52,2024,April,14,7,2024-04-07,0,1,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.9,0,0
HB-082034,City Hotel,1,305,2024,October,40,1,2024-10-01,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,35.0,,17,Transient,100.0,0,0
HB-104028,City Hotel,0,258,2024,December,52,28,2024-12-28,2,5,1,1.0,0,BB,CHE,Online TA,TA/TO,0,0,0,B,A,2,No Deposit,9.0,,0,Transient,73.41,0,3
HB-062474,City Hotel,1,38,2025,January,3,14,2025-01-14,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,Non Refund,,67.0,0,Transient,75.0,0,0
HB-010810,Resort Hotel,1,1,2025,April,14,5,2025-04-05,1,4,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,116.0,0,2
HB-114530,City Hotel,0,77,2025,June,25,18,2025-06-18,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,130.56,0,3
HB-112242,City Hotel,0,95,2025,May,20,18,2025-05-18,1,3,2,1.0,0,HB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,197.55,0,3
HB-054312,City Hotel,1,56,2024,July,28,12,2024-07-12,0,3,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,137.7,0,0
HB-067475,City Hotel,1,15,2025,May,18,4,2025-05-04,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,205.0,,0,Transient,136.0,0,1
HB-025636,Resort Hotel,0,9,2024,July,27,4,2024-07-04,1,0,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,F,0,No Deposit,240.0,360.0,0,Transient-Party,189.0,0,0
HB-087683,City Hotel,0,194,2024,April,16,21,2024-04-21,0,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,7.0,,0,Transient,73.46,0,0
HB-108860,City Hotel,0,103,2025,March,13,30,2025-03-30,1,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,104.4,0,1
HB-081123,City Hotel,1,146,2024,March,13,30,2024-03-30,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,86.0,,28,Transient,80.0,0,0
HB-013415,Resort Hotel,1,175,2025,August,33,14,2025-08-14,1,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,3,No Deposit,250.0,,0,Transient,274.5,0,0
HB-052350,City Hotel,1,66,2024,June,23,4,2024-06-04,1,1,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,154.8,0,0
HB-033258,Resort Hotel,0,35,2025,February,8,17,2025-02-17,0,2,3,1.0,0,BB,NLD,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,93.0,0,0
HB-081587,City Hotel,1,197,2024,June,23,3,2024-06-03,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,21.0,,25,Transient,80.0,0,0
HB-094363,City Hotel,0,29,2024,August,31,2,2024-08-02,0,1,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,149.0,0,1
HB-040791,City Hotel,0,36,2023,August,32,7,2023-08-07,0,2,3,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,D,1,No Deposit,1.0,,0,Transient-Party,84.0,0,1
HB-067507,City Hotel,1,148,2025,May,18,4,2025-05-04,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,171.0,,0,Transient,95.0,0,0
HB-102873,City Hotel,0,81,2024,December,49,7,2024-12-07,0,1,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,2
HB-018102,Resort Hotel,0,113,2023,October,44,31,2023-10-31,2,3,2,0.0,0,BB,SWE,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,42.28,0,0
HB-042971,City Hotel,1,8,2023,September,37,11,2023-09-11,0,2,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,118.5,0,1
HB-073888,City Hotel,1,321,2023,September,35,3,2023-09-03,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-079834,City Hotel,1,34,2023,December,49,8,2023-12-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,0,Transient,90.0,0,0
HB-047317,City Hotel,1,44,2024,February,7,17,2024-02-17,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,44.0,,3,Transient,75.0,0,0
HB-051600,City Hotel,0,142,2024,May,21,22,2024-05-22,2,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,114.3,0,0
HB-107254,City Hotel,0,46,2025,March,10,7,2025-03-07,0,3,2,0.0,0,BB,CHE,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,98.0,0,1
HB-059911,City Hotel,1,304,2024,November,44,3,2024-11-03,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,89.0,0,0
HB-104421,City Hotel,0,45,2025,January,2,9,2025-01-09,1,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,96.9,0,0
HB-018231,Resort Hotel,0,26,2023,November,45,7,2023-11-07,2,6,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,D,D,2,No Deposit,250.0,,0,Transient,56.0,0,1
HB-033191,Resort Hotel,0,214,2025,February,7,13,2025-02-13,1,3,1,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,240.0,,0,Transient,66.6,0,1
HB-033665,Resort Hotel,0,3,2025,February,9,27,2025-02-27,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,60.0,0,1
HB-084702,City Hotel,0,0,2024,March,9,2,2024-03-02,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,89.0,0,0
HB-094162,City Hotel,0,301,2024,July,31,30,2024-07-30,1,1,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-078219,City Hotel,0,10,2023,October,40,5,2023-10-05,1,1,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,120.0,0,1
HB-011918,Resort Hotel,1,319,2025,June,23,3,2025-06-03,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,74.25,0,1
HB-000902,Resort Hotel,0,14,2023,August,31,4,2023-08-04,0,5,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,241.0,0,2
HB-005422,Resort Hotel,1,1,2024,April,18,29,2024-04-29,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,85.0,0,1
HB-015873,Resort Hotel,0,1,2024,January,2,12,2024-01-12,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,D,0,No Deposit,,103.0,0,Transient,30.0,0,0
HB-048162,City Hotel,0,76,2024,March,12,18,2024-03-18,0,2,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,1
HB-001420,Resort Hotel,0,21,2023,August,35,28,2023-08-28,2,4,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,175.0,0,1
HB-052579,City Hotel,1,26,2024,June,23,8,2024-06-08,0,1,2,0.0,0,BB,PRT,Offline TA/TO,Corporate,0,0,0,A,A,0,No Deposit,191.0,,0,Transient-Party,120.0,0,0
HB-108919,City Hotel,0,162,2025,April,14,1,2025-04-01,2,1,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,296.0,,105,Transient-Party,88.2,0,0
HB-054532,City Hotel,1,33,2024,July,29,19,2024-07-19,0,2,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,134.1,0,0
HB-061851,City Hotel,1,248,2024,December,52,27,2024-12-27,0,5,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,70.55,0,0
HB-107285,City Hotel,0,0,2025,March,10,7,2025-03-07,0,4,2,0.0,0,SC,RUS,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,90.0,0,3
HB-006981,Resort Hotel,1,333,2024,July,29,15,2024-07-15,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,115.5,0,2
HB-113104,City Hotel,0,214,2025,May,22,28,2025-05-28,2,4,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,115.8,0,0
HB-010713,Resort Hotel,1,176,2025,March,13,27,2025-03-27,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,43.03,0,0
HB-055660,City Hotel,1,405,2024,August,33,18,2024-08-18,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-101553,City Hotel,0,43,2024,November,46,11,2024-11-11,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,88.46,0,1
HB-010844,Resort Hotel,1,95,2025,April,15,8,2025-04-08,2,3,3,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,150.0,0,0
HB-061702,City Hotel,1,25,2024,December,52,23,2024-12-23,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,104.0,0,0
HB-027451,Resort Hotel,0,179,2024,August,34,23,2024-08-23,2,5,2,1.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,177.5,0,1
HB-046930,City Hotel,0,173,2024,January,4,27,2024-01-27,2,5,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,27.0,,0,Transient,52.0,0,0
HB-029101,Resort Hotel,0,8,2024,October,42,18,2024-10-18,0,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,71.0,1,1
HB-024058,Resort Hotel,0,84,2024,April,17,27,2024-04-27,4,10,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,75.0,,0,Contract,68.85,0,0
HB-003292,Resort Hotel,1,81,2023,December,49,4,2023-12-04,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,32.4,0,2
HB-011436,Resort Hotel,1,2,2025,May,19,8,2025-05-08,1,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,E,0,No Deposit,152.0,,0,Transient,64.0,0,1
HB-099188,City Hotel,0,338,2024,October,41,7,2024-10-07,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,68,Transient-Party,90.67,0,1
HB-075205,City Hotel,1,294,2023,August,32,7,2023-08-07,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-073519,City Hotel,1,43,2025,August,35,25,2025-08-25,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,2
HB-072967,City Hotel,1,31,2025,August,33,11,2025-08-11,0,1,2,3.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,8.0,,0,Transient,352.5,0,1
HB-035121,Resort Hotel,0,70,2025,April,15,9,2025-04-09,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,241.0,,0,Transient,63.32,1,1
HB-067460,City Hotel,1,125,2025,May,18,3,2025-05-03,1,4,2,0.0,0,BB,HUN,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,108.0,0,0
HB-090287,City Hotel,0,0,2024,June,23,4,2024-06-04,0,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,129.0,0,1
HB-014374,Resort Hotel,0,1,2025,March,12,21,2025-03-21,0,1,1,0.0,0,BB,,Direct,Direct,0,0,3,A,C,0,No Deposit,,51.0,0,Transient,50.0,1,0
HB-064895,City Hotel,1,36,2025,March,12,19,2025-03-19,2,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,8.0,,0,Transient,93.22,0,0
HB-067976,City Hotel,1,196,2025,May,19,10,2025-05-10,0,2,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,143.55,0,2
HB-117750,City Hotel,0,77,2025,August,31,2,2025-08-02,2,5,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,394.0,,0,Transient,89.1,0,0
HB-060452,City Hotel,1,300,2024,November,46,11,2024-11-11,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,65.0,0,0
HB-028503,Resort Hotel,0,342,2024,September,39,29,2024-09-29,2,4,1,0.0,0,BB,IRL,Groups,TA/TO,0,0,0,A,A,1,No Deposit,201.0,,0,Transient-Party,38.0,0,0
HB-058873,City Hotel,1,67,2024,October,42,17,2024-10-17,1,0,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,34.0,,0,Transient,115.0,0,0
HB-032655,Resort Hotel,0,6,2025,January,5,31,2025-01-31,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,40.0,0,0
HB-043816,City Hotel,0,56,2023,September,39,25,2023-09-25,2,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,44.0,,0,Transient-Party,185.0,0,0
HB-071432,City Hotel,1,179,2025,July,27,5,2025-07-05,0,4,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,1
HB-013321,Resort Hotel,1,184,2025,August,32,9,2025-08-09,1,4,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,134.85,0,0
HB-107331,City Hotel,0,1,2025,March,11,11,2025-03-11,0,1,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,83.48,0,0
HB-061637,City Hotel,1,333,2024,December,51,21,2024-12-21,0,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,73.95,0,0
HB-049368,City Hotel,1,75,2024,April,15,11,2024-04-11,1,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.95,0,0
HB-002948,Resort Hotel,0,36,2023,November,45,7,2023-11-07,2,6,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,2,No Deposit,185.0,281.0,0,Transient-Party,36.0,0,0
HB-051796,City Hotel,1,323,2024,May,21,26,2024-05-26,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-080712,City Hotel,0,32,2023,November,47,20,2023-11-20,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,119.0,,0,Transient-Party,73.0,0,0
HB-082031,City Hotel,1,305,2024,October,40,1,2024-10-01,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,35.0,,17,Transient,100.0,0,0
HB-117378,City Hotel,0,14,2025,July,31,31,2025-07-31,1,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,180.0,0,1
HB-050298,City Hotel,1,295,2024,April,17,28,2024-04-28,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-036490,Resort Hotel,0,74,2025,May,20,14,2025-05-14,3,5,2,0.0,0,SC,GBR,Offline TA/TO,TA/TO,0,0,0,D,I,1,No Deposit,243.0,,0,Contract,0.0,0,2
HB-029539,Resort Hotel,0,178,2024,October,42,16,2024-10-16,4,10,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,314.0,,0,Transient,80.57,0,0
HB-002076,Resort Hotel,1,142,2023,September,39,30,2023-09-30,2,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,79.83,0,1
HB-032822,Resort Hotel,0,6,2025,February,5,1,2025-02-01,1,4,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,6.0,,0,Transient,68.0,0,0
HB-027595,Resort Hotel,0,103,2024,August,35,30,2024-08-30,0,4,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,198.5,0,3
HB-002328,Resort Hotel,0,3,2023,October,41,9,2023-10-09,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,83.33,0,2
HB-078549,City Hotel,0,282,2023,October,41,10,2023-10-10,2,1,2,0.0,0,BB,SWE,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,76.67,0,0
HB-047810,City Hotel,0,73,2024,March,10,4,2024-03-04,1,2,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,62.29,0,1
HB-039697,Resort Hotel,0,157,2025,August,34,19,2025-08-19,2,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,468.0,,0,Transient-Party,198.17,0,1
HB-079097,City Hotel,0,31,2023,October,42,18,2023-10-18,2,2,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,85.5,0,2
HB-085755,City Hotel,0,53,2024,March,11,17,2024-03-17,1,3,1,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,10.0,,0,Transient,81.7,0,1
HB-051448,City Hotel,1,198,2024,May,21,20,2024-05-20,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,B,1,No Deposit,1.0,,98,Transient-Party,65.0,0,0
HB-104253,City Hotel,0,14,2025,January,1,5,2025-01-05,1,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,73.0,0,1
HB-071975,City Hotel,1,147,2025,July,29,16,2025-07-16,2,2,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,0
HB-114038,City Hotel,0,102,2025,June,24,12,2025-06-12,1,3,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,168.0,,0,Transient,121.1,0,0
HB-033677,Resort Hotel,0,50,2025,February,9,25,2025-02-25,2,1,2,0.0,1,BB,PRT,Direct,Direct,0,0,0,A,A,2,No Deposit,250.0,,0,Transient,39.6,0,1
HB-090127,City Hotel,0,67,2024,May,22,30,2024-05-30,1,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,168.0,,0,Transient,80.75,0,0
HB-035157,Resort Hotel,0,351,2025,April,15,8,2025-04-08,2,5,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,D,D,0,No Deposit,298.0,,0,Transient-Party,82.0,0,0
HB-117246,City Hotel,0,244,2025,July,31,29,2025-07-29,2,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,2
HB-085684,City Hotel,0,115,2024,March,12,18,2024-03-18,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,90.0,0,0
HB-029491,Resort Hotel,0,118,2024,October,43,23,2024-10-23,2,5,2,0.0,0,BB,NLD,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient-Party,79.2,0,1
HB-113290,City Hotel,0,42,2025,June,23,3,2025-06-03,1,1,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,9.0,,0,Transient,250.0,0,0
HB-049427,City Hotel,1,90,2024,April,15,13,2024-04-13,0,4,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.75,0,0
HB-089490,City Hotel,0,52,2024,May,21,21,2024-05-21,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.9,0,2
HB-104646,City Hotel,0,156,2025,January,3,14,2025-01-14,2,3,2,1.0,0,BB,MEX,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,80.75,0,1
HB-010795,Resort Hotel,1,26,2025,April,14,4,2025-04-04,0,4,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,105.0,0,0
HB-067444,City Hotel,1,152,2025,May,18,3,2025-05-03,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,286.0,,0,Transient,100.0,0,0
HB-013484,Resort Hotel,1,187,2025,August,33,17,2025-08-17,1,3,2,0.0,0,HB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,212.0,0,0
HB-059935,City Hotel,1,50,2024,November,44,3,2024-11-03,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-050081,City Hotel,1,142,2024,April,17,22,2024-04-22,2,3,1,0.0,0,BB,POL,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,89.0,0,0
HB-080584,City Hotel,1,8,2024,January,2,14,2024-01-14,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,0,A,A,0,No Deposit,,40.0,0,Transient,66.0,0,0
HB-103966,City Hotel,0,269,2024,December,52,29,2024-12-29,2,3,1,0.0,0,BB,SWE,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,70.0,0,0
HB-063454,City Hotel,1,67,2025,February,7,12,2025-02-12,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,80.0,0,0
HB-004707,Resort Hotel,1,2,2024,March,13,28,2024-03-28,2,5,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,60.84,0,0
HB-010307,Resort Hotel,1,18,2025,February,9,25,2025-02-25,2,1,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,64.68,0,0
HB-008489,Resort Hotel,1,157,2024,October,40,1,2024-10-01,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,Non Refund,96.0,,0,Transient,52.0,0,0
HB-103027,City Hotel,0,4,2024,December,49,8,2024-12-08,0,3,2,2.0,0,BB,ESP,Direct,Direct,0,0,0,F,F,0,No Deposit,14.0,,0,Transient,178.0,0,2
HB-047208,City Hotel,1,30,2024,February,7,12,2024-02-12,1,2,1,0.0,0,BB,TUR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,68.7,0,0
HB-017387,Resort Hotel,0,239,2023,October,40,2,2023-10-02,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,36.13,0,0
HB-069771,City Hotel,1,437,2025,June,23,6,2025-06-06,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-023742,Resort Hotel,0,22,2024,April,18,30,2024-04-30,1,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,95.0,0,1
HB-105696,City Hotel,0,77,2025,February,7,10,2025-02-10,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,86.0,,0,Transient,77.52,0,0
HB-010790,Resort Hotel,1,255,2025,April,14,3,2025-04-03,3,7,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,67.5,0,0
HB-074592,City Hotel,1,353,2023,October,40,5,2023-10-05,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-048363,City Hotel,1,40,2024,March,12,22,2024-03-22,0,1,3,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,131.4,0,1
HB-018387,Resort Hotel,0,12,2023,November,46,16,2023-11-16,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,74.0,1,1
HB-010412,Resort Hotel,1,312,2025,March,10,5,2025-03-05,2,5,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,30.0,0,0
HB-113807,City Hotel,0,135,2025,June,24,10,2025-06-10,1,1,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,27.0,,0,Transient-Party,109.0,0,1
HB-006372,Resort Hotel,1,76,2024,June,23,6,2024-06-06,1,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,116.0,0,0
HB-114660,City Hotel,0,136,2025,June,25,22,2025-06-22,0,3,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,121.5,0,0
HB-047162,City Hotel,0,37,2024,February,6,11,2024-02-11,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.3,1,0
HB-073028,City Hotel,1,172,2025,August,33,12,2025-08-12,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,139.5,0,1
HB-008894,Resort Hotel,1,63,2024,October,42,18,2024-10-18,0,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,74.0,0,2
HB-017203,Resort Hotel,0,3,2023,September,39,29,2023-09-29,0,1,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,74.0,0,0
HB-092147,City Hotel,0,2,2024,June,26,29,2024-06-29,0,2,2,0.0,0,SC,ISR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,152.0,,0,Transient,104.79,0,0
HB-049898,City Hotel,1,270,2024,April,16,20,2024-04-20,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,187,Transient-Party,62.8,0,0
HB-047669,City Hotel,1,1,2024,February,9,28,2024-02-28,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,60.0,0,0
HB-075674,City Hotel,1,295,2023,August,32,8,2023-08-08,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-076838,City Hotel,0,1,2023,August,33,20,2023-08-20,0,2,1,0.0,0,BB,PRT,Complementary,Direct,1,0,1,A,D,1,No Deposit,,46.0,0,Transient,0.0,0,0
HB-000231,Resort Hotel,0,17,2023,July,27,9,2023-07-09,0,1,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,242.0,,0,Transient,123.0,0,3
HB-101824,City Hotel,0,0,2024,November,47,18,2024-11-18,0,1,2,0.0,0,SC,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,104.0,0,0
HB-086873,City Hotel,0,10,2024,April,15,9,2024-04-09,1,1,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,70.0,0,0
HB-100697,City Hotel,0,36,2024,October,44,28,2024-10-28,1,2,2,1.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,100.0,0,1
HB-014919,Resort Hotel,0,288,2024,October,44,28,2024-10-28,2,2,1,0.0,0,BB,PRT,Online TA,Direct,1,1,8,A,A,0,No Deposit,,,0,Transient,39.7,0,4
HB-058541,City Hotel,1,37,2024,October,41,13,2024-10-13,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,105.0,0,0
HB-026482,Resort Hotel,0,17,2024,July,31,30,2024-07-30,1,1,2,1.0,0,BB,PRT,Complementary,Direct,0,0,0,E,G,0,No Deposit,,,0,Transient,0.0,1,2
HB-114509,City Hotel,0,89,2025,June,25,19,2025-06-19,1,3,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,122.4,0,0
HB-001700,Resort Hotel,1,114,2023,September,36,10,2023-09-10,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,87.05,0,0
HB-013661,Resort Hotel,1,72,2025,August,35,25,2025-08-25,2,2,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,260.0,0,2
HB-032332,Resort Hotel,0,93,2025,January,3,19,2025-01-19,1,3,2,2.0,0,BB,POL,Online TA,TA/TO,0,0,0,G,G,1,No Deposit,240.0,,0,Transient,89.0,1,1
HB-055775,City Hotel,1,130,2024,August,34,20,2024-08-20,6,13,2,0.0,0,SC,AGO,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,101.98,0,0
HB-048671,City Hotel,1,92,2024,March,13,26,2024-03-26,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,170.0,,0,Transient,100.0,0,0
HB-007597,Resort Hotel,1,12,2024,August,33,16,2024-08-16,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,209.0,0,1
HB-089934,City Hotel,0,13,2024,May,22,29,2024-05-29,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.35,0,1
HB-057000,City Hotel,1,205,2024,September,38,16,2024-09-16,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,120.0,0,0
HB-091499,City Hotel,0,6,2025,May,18,4,2025-05-04,0,1,1,0.0,0,BB,ITA,Direct,TA/TO,1,0,1,D,D,0,No Deposit,14.0,,0,Transient-Party,175.0,0,1
HB-050944,City Hotel,1,309,2024,May,19,12,2024-05-12,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-077612,City Hotel,0,1,2023,September,38,20,2023-09-20,2,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,89.0,,0,Transient,91.2,0,0
HB-004945,Resort Hotel,1,32,2024,April,15,10,2024-04-10,2,2,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,65.0,0,0
HB-053531,City Hotel,1,351,2024,June,25,23,2024-06-23,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-104336,City Hotel,0,14,2025,January,2,10,2025-01-10,0,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.5,0,0
HB-051770,City Hotel,1,8,2024,May,21,25,2024-05-25,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,111.35,0,0
HB-026173,Resort Hotel,0,70,2024,July,29,19,2024-07-19,0,5,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient,170.2,0,1
HB-098788,City Hotel,0,27,2024,October,40,3,2024-10-03,1,1,2,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,95.0,0,0
HB-106768,City Hotel,0,3,2025,February,9,27,2025-02-27,1,3,2,0.0,0,SC,FIN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,1
HB-034600,Resort Hotel,0,48,2025,March,12,23,2025-03-23,2,5,1,0.0,0,Undefined,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,464.0,,0,Transient,47.0,0,0
HB-006011,Resort Hotel,1,2,2024,May,21,20,2024-05-20,0,2,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,89.0,0,0
HB-026085,Resort Hotel,0,26,2024,July,29,16,2024-07-16,2,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,179.0,1,1
HB-092565,City Hotel,0,81,2024,July,27,4,2024-07-04,1,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.3,0,1
HB-061782,City Hotel,1,262,2024,December,52,26,2024-12-26,1,3,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,63.75,0,0
HB-075498,City Hotel,1,341,2023,September,38,23,2023-09-23,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-096221,City Hotel,0,1,2024,August,35,26,2024-08-26,2,2,2,0.0,0,BB,GEO,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient,96.3,0,0
HB-105235,City Hotel,0,0,2025,January,4,23,2025-01-23,3,8,2,0.0,0,BB,AGO,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,88.0,0,0
HB-107839,City Hotel,0,93,2025,March,11,16,2025-03-16,0,3,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,79.2,0,0
HB-043880,City Hotel,0,192,2023,September,39,25,2023-09-25,2,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,102.0,0,0
HB-025280,Resort Hotel,0,294,2024,June,25,21,2024-06-21,0,5,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,76.8,0,1
HB-046899,City Hotel,1,33,2024,January,4,25,2024-01-25,1,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,38.0,,15,Transient-Party,62.0,0,0
HB-050240,City Hotel,1,15,2024,April,17,27,2024-04-27,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,103.44,0,0
HB-085473,City Hotel,0,6,2024,March,11,15,2024-03-15,0,1,1,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,62.0,0,0
HB-111082,City Hotel,0,14,2025,May,18,1,2025-05-01,1,4,2,0.0,0,BB,HRV,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,7.0,,0,Transient,115.76,0,1
HB-046419,City Hotel,1,148,2023,December,52,31,2023-12-31,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,98,Transient,77.5,0,0
HB-068425,City Hotel,1,66,2025,May,20,17,2025-05-17,0,2,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,144.0,0,0
HB-055647,City Hotel,1,107,2024,August,33,18,2024-08-18,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient-Party,135.27,0,0
HB-117215,City Hotel,0,40,2025,July,31,31,2025-07-31,1,0,1,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,140.0,0,1
HB-078538,City Hotel,0,3,2023,October,41,11,2023-10-11,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,136.0,0,1
HB-090038,City Hotel,0,9,2024,May,22,31,2024-05-31,0,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,131.0,0,2
HB-076905,City Hotel,1,342,2023,September,38,24,2023-09-24,2,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-031003,Resort Hotel,0,3,2024,December,49,8,2024-12-08,0,3,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,F,F,1,No Deposit,250.0,,0,Transient,110.0,0,0
HB-102577,City Hotel,0,15,2024,November,48,30,2024-11-30,0,2,2,0.0,0,BB,POL,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,81.0,0,0
HB-024320,Resort Hotel,0,175,2024,May,19,10,2024-05-10,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,314.0,,0,Transient,52.56,0,1
HB-059374,City Hotel,1,240,2024,October,43,27,2024-10-27,1,3,2,0.0,0,SC,DNK,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.75,0,0
HB-003385,Resort Hotel,1,149,2023,December,49,5,2023-12-05,2,1,2,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,38.0,,0,Transient,68.0,0,0
HB-040206,City Hotel,1,122,2023,July,28,16,2023-07-16,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.5,0,0
HB-006069,Resort Hotel,0,223,2024,May,21,24,2024-05-24,1,5,2,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,A,1,No Deposit,,223.0,0,Transient-Party,66.0,0,0
HB-001232,Resort Hotel,1,100,2023,August,33,20,2023-08-20,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,134.0,,0,Transient,158.5,0,0
HB-087901,City Hotel,0,5,2024,April,17,24,2024-04-24,2,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,123.5,0,0
HB-088107,City Hotel,0,80,2024,April,17,28,2024-04-28,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.2,0,1
HB-030918,Resort Hotel,0,21,2024,December,49,7,2024-12-07,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,240.0,,0,Transient,60.0,1,1
HB-118933,City Hotel,0,457,2025,August,35,25,2025-08-25,0,2,2,0.0,0,HB,AUT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,122.4,0,1
HB-067076,City Hotel,1,284,2025,April,18,28,2025-04-28,1,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.8,0,2
HB-117726,City Hotel,0,169,2025,August,32,7,2025-08-07,1,1,2,0.0,0,SC,ARG,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,112.5,0,0
HB-118662,City Hotel,0,227,2025,August,34,18,2025-08-18,2,4,2,2.0,0,HB,CN,Online TA,TA/TO,0,0,0,F,F,2,No Deposit,9.0,,0,Transient,199.77,0,1
HB-030732,Resort Hotel,0,13,2024,December,49,2,2024-12-02,0,1,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,240.0,,0,Transient,60.0,0,2
HB-040026,Resort Hotel,0,161,2025,August,35,30,2025-08-30,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,213.43,0,2
HB-106389,City Hotel,0,1,2025,February,8,23,2025-02-23,0,2,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,71.0,0,1
HB-055954,City Hotel,1,412,2024,August,34,25,2024-08-25,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-064477,City Hotel,1,113,2025,March,11,10,2025-03-10,2,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.4,0,2
HB-000946,Resort Hotel,1,46,2023,August,32,7,2023-08-07,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,153.0,0,0
HB-092487,City Hotel,0,91,2024,July,27,3,2024-07-03,2,2,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,103.5,0,0
HB-095729,City Hotel,0,106,2024,August,34,20,2024-08-20,2,1,3,0.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,141.9,0,0
HB-100940,City Hotel,0,57,2024,November,44,1,2024-11-01,0,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,1
HB-103193,City Hotel,0,12,2024,December,50,14,2024-12-14,0,1,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,75.2,0,0
HB-047222,City Hotel,0,37,2024,February,7,12,2024-02-12,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,87.3,0,0
HB-091729,City Hotel,0,265,2024,June,26,24,2024-06-24,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-106801,City Hotel,0,44,2025,February,9,27,2025-02-27,1,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,136.0,0,2
HB-100351,City Hotel,0,0,2024,October,43,26,2024-10-26,0,1,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,C,0,No Deposit,,,0,Transient,126.0,0,0
HB-116030,City Hotel,0,414,2025,July,28,13,2025-07-13,0,2,1,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,95.5,0,0
HB-062717,City Hotel,1,53,2025,January,3,19,2025-01-19,0,3,3,0.0,0,BB,KOR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,138.6,0,0
HB-028155,Resort Hotel,0,422,2024,September,37,12,2024-09-12,3,7,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,2.0,,0,Contract,62.9,0,1
HB-075333,City Hotel,1,311,2023,August,34,24,2023-08-24,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-015658,Resort Hotel,1,468,2024,May,19,12,2024-05-12,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,249.0,,0,Transient-Party,67.0,0,0
HB-050749,City Hotel,1,73,2024,May,19,7,2024-05-07,0,1,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.9,0,0
HB-064398,City Hotel,1,608,2025,March,10,9,2025-03-09,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,59.0,0,0
HB-068592,City Hotel,1,105,2025,May,21,19,2025-05-19,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-111235,City Hotel,0,179,2025,May,19,5,2025-05-05,1,2,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,99.0,0,0
HB-004445,Resort Hotel,0,133,2024,March,12,18,2024-03-18,2,2,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,32.0,1,0
HB-090535,City Hotel,0,118,2024,June,23,6,2024-06-06,1,1,1,0.0,0,BB,GBR,Offline TA/TO,Corporate,0,0,0,A,A,1,No Deposit,191.0,,0,Transient-Party,110.0,0,0
HB-084145,City Hotel,0,99,2024,February,8,19,2024-02-19,0,1,1,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,A,0,No Deposit,,67.0,0,Transient,81.0,0,0
HB-079625,City Hotel,0,6,2023,October,43,28,2023-10-28,0,3,2,0.0,0,HB,ISR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,6,Transient-Party,107.0,0,0
HB-031884,Resort Hotel,0,24,2025,January,2,6,2025-01-06,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient,34.0,0,0
HB-003260,Resort Hotel,0,28,2023,November,48,28,2023-11-28,0,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,0.0,0,1
HB-054224,City Hotel,1,17,2024,July,28,9,2024-07-09,1,1,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,187.0,0,0
HB-114493,City Hotel,0,30,2025,June,25,19,2025-06-19,1,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,160.0,0,1
HB-059426,City Hotel,1,199,2024,October,44,28,2024-10-28,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,29.0,,0,Transient-Party,95.0,0,0
HB-047583,City Hotel,1,115,2024,February,9,27,2024-02-27,2,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,134.0,,0,Transient-Party,60.0,0,0
HB-077111,City Hotel,0,219,2023,September,36,4,2023-09-04,1,2,1,0.0,0,BB,SWE,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,3.0,,0,Transient-Party,76.67,0,0
HB-093320,City Hotel,0,3,2024,July,29,19,2024-07-19,0,1,2,2.0,0,BB,SWE,Direct,Direct,0,0,0,G,B,0,No Deposit,14.0,,0,Transient,235.45,0,2
HB-088065,City Hotel,0,75,2024,April,17,26,2024-04-26,0,4,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,105.83,0,0
HB-095464,City Hotel,0,34,2024,August,33,17,2024-08-17,0,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.1,0,2
HB-106201,City Hotel,0,57,2025,February,8,19,2025-02-19,2,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,1
HB-112199,City Hotel,0,2,2025,May,20,18,2025-05-18,0,3,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,0
HB-056763,City Hotel,1,4,2024,September,37,13,2024-09-13,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,124.36,0,0
HB-073199,City Hotel,1,233,2025,August,33,16,2025-08-16,0,4,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,106.65,0,0
HB-023632,Resort Hotel,0,12,2024,April,17,27,2024-04-27,0,3,2,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,A,A,1,No Deposit,385.0,,0,Transient-Party,85.33,0,0
HB-080103,City Hotel,1,333,2024,September,38,20,2024-09-20,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,58.0,,19,Transient,90.0,0,0
HB-005221,Resort Hotel,0,191,2024,April,17,22,2024-04-22,1,2,2,0.0,0,Undefined,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,85.33,0,0
HB-032585,Resort Hotel,0,7,2025,January,5,27,2025-01-27,1,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient-Party,43.0,0,1
HB-007066,Resort Hotel,1,167,2024,July,29,18,2024-07-18,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,145.71,0,1
HB-045653,City Hotel,0,140,2023,November,46,18,2023-11-18,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,29.0,,87,Transient-Party,75.0,0,0
HB-022715,Resort Hotel,0,82,2024,March,13,30,2024-03-30,0,4,2,2.0,0,BB,SWE,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,104.5,1,0
HB-010769,Resort Hotel,1,10,2025,April,14,3,2025-04-03,1,0,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,314.0,,0,Transient,80.0,0,0
HB-053197,City Hotel,1,350,2024,June,25,17,2024-06-17,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,130.0,0,0
HB-055861,City Hotel,1,15,2024,August,34,23,2024-08-23,0,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,129.0,0,0
HB-111313,City Hotel,0,144,2025,May,19,6,2025-05-06,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,52.0,,0,Transient-Party,90.0,0,1
HB-075694,City Hotel,1,295,2023,August,32,8,2023-08-08,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-064894,City Hotel,1,31,2025,March,12,19,2025-03-19,2,3,1,0.0,0,BB,CN,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,113.0,0,1
HB-072810,City Hotel,1,123,2025,August,32,7,2025-08-07,1,1,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.0,0,1
HB-011257,Resort Hotel,1,172,2025,April,18,29,2025-04-29,2,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,314.0,,0,Transient,86.91,0,0
HB-040679,City Hotel,1,34,2023,August,31,5,2023-08-05,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-068566,City Hotel,1,123,2025,May,21,19,2025-05-19,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-093982,City Hotel,0,133,2024,July,30,28,2024-07-28,0,2,2,1.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,121.5,0,0
HB-025010,Resort Hotel,0,12,2025,February,6,3,2025-02-03,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,1,0,1,E,E,0,No Deposit,240.0,,0,Group,75.0,1,0
HB-055934,City Hotel,1,412,2024,August,34,25,2024-08-25,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-113224,City Hotel,0,18,2025,June,23,3,2025-06-03,0,1,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,99.0,0,0
HB-091125,City Hotel,0,107,2024,June,24,13,2024-06-13,1,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,87.67,0,1
HB-098516,City Hotel,0,29,2024,September,40,30,2024-09-30,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,179.38,0,0
HB-036983,Resort Hotel,0,2,2025,June,23,2,2025-06-02,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,125.0,0,1
HB-050167,City Hotel,0,113,2024,April,17,24,2024-04-24,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient,85.85,0,0
HB-115782,City Hotel,0,75,2025,July,27,4,2025-07-04,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,150.0,0,1
HB-113588,City Hotel,0,53,2025,June,23,5,2025-06-05,1,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,170.0,0,1
HB-035427,Resort Hotel,0,2,2025,April,17,21,2025-04-21,0,1,3,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,185.0,0,0
HB-090445,City Hotel,0,220,2024,June,23,4,2024-06-04,2,1,2,0.0,0,BB,USA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,73.33,0,1
HB-056045,City Hotel,1,69,2024,August,35,27,2024-08-27,2,1,3,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,162.3,0,1
HB-097816,City Hotel,0,104,2024,September,38,18,2024-09-18,2,1,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,80.75,0,0
HB-098668,City Hotel,0,193,2024,September,40,30,2024-09-30,1,2,2,0.0,0,BB,DEU,Groups,Corporate,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,132.0,0,0
HB-014606,Resort Hotel,0,3,2025,January,5,27,2025-01-27,2,2,2,0.0,0,HB,,Direct,TA/TO,0,0,1,A,E,1,No Deposit,250.0,,0,Transient,77.0,0,0
HB-072870,City Hotel,1,239,2025,August,32,8,2025-08-08,0,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.5,0,0
HB-051499,City Hotel,1,211,2024,May,21,20,2024-05-20,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,111,Transient,100.0,0,0
HB-015709,Resort Hotel,1,245,2023,September,39,25,2023-09-25,0,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,248.0,,0,Transient,80.0,0,0
HB-090572,City Hotel,0,247,2024,June,23,6,2024-06-06,1,1,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-002787,Resort Hotel,0,1,2023,October,44,31,2023-10-31,0,1,2,1.0,0,BB,ESP,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,,0,Transient,58.0,0,1
HB-036943,Resort Hotel,0,351,2025,May,22,26,2025-05-26,2,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,F,F,3,No Deposit,241.0,,0,Transient,81.53,0,2
HB-064246,City Hotel,1,67,2025,March,10,3,2025-03-03,0,2,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,151.2,0,1
HB-016890,Resort Hotel,0,55,2023,September,37,14,2023-09-14,1,1,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,A,G,0,No Deposit,,,0,Transient,98.0,0,1
HB-028448,Resort Hotel,0,4,2024,October,40,4,2024-10-04,0,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,180.0,,0,Transient,0.0,0,0
HB-034159,Resort Hotel,0,201,2025,March,10,5,2025-03-05,4,6,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,D,D,0,No Deposit,273.0,,6,Transient-Party,62.28,0,0
HB-021907,Resort Hotel,0,2,2024,March,11,11,2024-03-11,0,2,2,0.0,1,BB,PRT,Online TA,TA/TO,0,0,0,D,E,1,No Deposit,240.0,,0,Transient-Party,68.0,0,1
HB-109959,City Hotel,0,2,2025,April,16,17,2025-04-17,1,2,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,152.0,,0,Transient,79.7,0,0
HB-097619,City Hotel,0,54,2024,September,38,18,2024-09-18,1,0,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Group,125.1,0,1
HB-071982,City Hotel,1,0,2025,July,29,17,2025-07-17,1,0,2,0.0,0,SC,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,2
HB-072301,City Hotel,1,133,2025,July,30,26,2025-07-26,0,2,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,148.5,0,0
HB-019566,Resort Hotel,0,14,2023,December,52,25,2023-12-25,0,2,2,0.0,1,BB,PRT,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient,61.0,1,2
HB-067674,City Hotel,1,55,2025,May,19,6,2025-05-06,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,100.8,0,0
HB-078457,City Hotel,0,17,2023,October,40,3,2023-10-03,2,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Contract,119.71,0,1
HB-048991,City Hotel,1,91,2024,April,14,4,2024-04-04,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,80.0,0,0
HB-081445,City Hotel,0,6,2023,December,49,10,2023-12-10,0,2,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,0.0,0,0
HB-058977,City Hotel,1,154,2024,October,42,19,2024-10-19,0,4,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-013791,Resort Hotel,1,95,2025,August,35,31,2025-08-31,0,2,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,241.0,,0,Transient,290.0,0,2
HB-084880,City Hotel,0,21,2024,March,10,4,2024-03-04,0,1,2,0.0,0,HB,SVN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,131.0,0,0
HB-068176,City Hotel,1,16,2025,May,20,14,2025-05-14,2,2,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,159.6,0,1
HB-017062,Resort Hotel,0,185,2023,September,38,21,2023-09-21,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,C,0,No Deposit,208.0,,0,Transient-Party,90.0,0,0
HB-084858,City Hotel,0,1,2024,March,9,1,2024-03-01,0,4,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,119.0,0,1
HB-114293,City Hotel,0,11,2025,June,25,18,2025-06-18,2,0,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,10.0,,0,Transient,95.0,0,0
HB-057987,City Hotel,1,349,2024,October,40,4,2024-10-04,1,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,58.0,,162,Transient-Party,90.0,0,0
HB-028659,Resort Hotel,0,383,2024,October,40,6,2024-10-06,0,3,1,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,1,No Deposit,315.0,,0,Transient-Party,48.0,0,0
HB-081447,City Hotel,0,6,2023,December,49,10,2023-12-10,0,2,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient-Party,0.0,0,0
HB-000668,Resort Hotel,0,40,2023,July,30,25,2023-07-25,0,1,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,F,0,No Deposit,134.0,,0,Transient,107.0,0,0
HB-004544,Resort Hotel,1,43,2024,March,12,24,2024-03-24,0,3,3,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,314.0,,0,Transient,81.0,0,0
HB-022643,Resort Hotel,0,129,2024,March,12,24,2024-03-24,2,5,2,2.0,0,BB,IRL,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,242.0,,0,Transient,76.97,0,0
HB-015972,Resort Hotel,0,0,2023,August,32,10,2023-08-10,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,1,0,1,E,E,0,No Deposit,,,0,Transient,0.0,0,0
HB-092816,City Hotel,0,128,2024,July,28,8,2024-07-08,2,3,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.05,0,2
HB-109921,City Hotel,0,10,2025,April,16,18,2025-04-18,0,1,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,150.0,0,1
HB-057779,City Hotel,1,179,2024,September,40,30,2024-09-30,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,113.4,0,0
HB-006401,Resort Hotel,1,21,2024,June,23,8,2024-06-08,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,122.33,0,0
HB-074546,City Hotel,1,339,2023,September,38,21,2023-09-21,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-087793,City Hotel,0,4,2024,April,16,21,2024-04-21,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,103.18,0,1
HB-034536,Resort Hotel,0,0,2025,March,13,28,2025-03-28,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,65.0,1,0
HB-000533,Resort Hotel,0,64,2023,July,29,18,2023-07-18,2,5,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,128.25,0,1
HB-094737,City Hotel,0,111,2024,August,32,6,2024-08-06,2,1,2,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,148.5,0,2
HB-023832,Resort Hotel,0,35,2024,May,18,2,2024-05-02,1,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,242.0,,0,Transient,105.0,0,0
HB-103820,City Hotel,0,3,2024,December,52,28,2024-12-28,0,4,2,0.0,0,SC,HUN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,95.2,0,0
HB-049341,City Hotel,1,13,2024,April,15,11,2024-04-11,1,0,1,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,95.0,0,0
HB-101180,City Hotel,0,49,2024,November,45,4,2024-11-04,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,112.0,0,0
HB-021886,Resort Hotel,0,30,2024,March,10,7,2024-03-07,1,5,1,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,1,No Deposit,38.0,,0,Transient-Party,48.7,0,0
HB-032675,Resort Hotel,0,27,2025,January,5,30,2025-01-30,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,68.0,0,1
HB-027250,Resort Hotel,0,170,2024,August,33,17,2024-08-17,2,5,2,1.0,0,HB,PRT,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,284.86,1,1
HB-109425,City Hotel,0,30,2025,April,15,8,2025-04-08,2,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,180.0,0,0
HB-105684,City Hotel,0,4,2025,February,7,13,2025-02-13,1,0,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,52.0,,0,Transient,75.0,0,0
HB-021114,Resort Hotel,0,0,2024,March,10,9,2024-03-09,0,3,2,0.0,0,BB,PRT,Direct,Direct,1,0,1,D,E,1,No Deposit,,,0,Transient,69.0,1,1
HB-001596,Resort Hotel,0,26,2023,September,36,5,2023-09-05,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,C,C,0,No Deposit,142.0,,0,Contract,124.8,0,0
HB-045754,City Hotel,1,89,2023,November,47,23,2023-11-23,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,72.25,0,2
HB-012602,Resort Hotel,1,11,2025,July,28,7,2025-07-07,2,2,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,173.75,0,1
HB-092002,City Hotel,0,0,2024,June,26,28,2024-06-28,0,1,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,137.0,0,0
HB-109691,City Hotel,0,82,2025,April,15,12,2025-04-12,0,3,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.0,0,1
HB-080252,City Hotel,0,51,2023,November,45,11,2023-11-11,0,4,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Transient,60.0,0,1
HB-062691,City Hotel,1,23,2025,January,3,18,2025-01-18,2,4,2,0.0,0,BB,TUR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,99.24,0,0
HB-047121,City Hotel,0,33,2024,February,6,8,2024-02-08,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.3,0,1
HB-020896,Resort Hotel,0,4,2024,February,7,13,2024-02-13,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,58.0,0,2
HB-082478,City Hotel,0,38,2023,December,51,24,2023-12-24,2,5,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,83.57,0,0
HB-071191,City Hotel,1,135,2025,June,26,29,2025-06-29,0,2,2,0.0,0,BB,SAU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-053379,City Hotel,1,34,2024,June,25,19,2024-06-19,2,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,122.4,0,0
HB-020496,Resort Hotel,0,26,2024,January,5,30,2024-01-30,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-093119,City Hotel,0,84,2024,July,29,15,2024-07-15,0,2,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,121.5,0,2
HB-052085,City Hotel,1,55,2024,May,22,30,2024-05-30,1,2,1,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.35,0,0
HB-060448,City Hotel,1,300,2024,November,46,11,2024-11-11,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,65.0,0,0
HB-052915,City Hotel,1,71,2024,June,24,14,2024-06-14,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,120.0,0,0
HB-000088,Resort Hotel,1,79,2023,July,27,3,2023-07-03,6,15,2,1.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,108.73,0,2
HB-083890,City Hotel,0,2,2024,February,7,13,2024-02-13,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,60.83,0,1
HB-015925,Resort Hotel,0,0,2023,August,32,7,2023-08-07,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,F,0,No Deposit,240.0,,0,Transient,153.0,0,2
HB-059869,City Hotel,1,304,2024,November,44,3,2024-11-03,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,89.0,0,0
HB-117921,City Hotel,0,217,2025,August,32,8,2025-08-08,0,4,2,2.0,0,HB,DEU,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,83.0,,0,Transient,228.0,0,0
HB-065895,City Hotel,1,76,2025,April,15,9,2025-04-09,2,3,2,0.0,0,BB,NOR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,100.8,0,0
HB-111814,City Hotel,0,19,2025,May,20,13,2025-05-13,2,1,2,0.0,0,BB,CZE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,173.33,0,2
HB-058808,City Hotel,1,286,2024,October,42,16,2024-10-16,1,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,44.0,,0,Transient,90.0,0,0
HB-029929,Resort Hotel,0,73,2024,November,45,4,2024-11-04,2,4,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,48.47,0,0
HB-039638,Resort Hotel,0,1,2025,August,34,23,2025-08-23,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,159.2,0,1
HB-118075,City Hotel,0,295,2025,August,32,10,2025-08-10,1,3,3,0.0,0,BB,DNK,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,156.6,0,0
HB-017928,Resort Hotel,0,0,2023,October,43,26,2023-10-26,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient-Party,48.0,0,1
HB-011103,Resort Hotel,1,9,2025,April,16,19,2025-04-19,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,269.0,0,Transient,45.0,0,0
HB-091683,City Hotel,0,41,2024,June,25,21,2024-06-21,0,3,2,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,76.92,0,1
HB-116024,City Hotel,0,93,2025,July,28,12,2025-07-12,0,2,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient-Party,130.5,0,0
HB-009778,Resort Hotel,1,62,2025,January,1,1,2025-01-01,2,2,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,51.5,0,1
HB-083221,City Hotel,0,14,2024,January,4,23,2024-01-23,1,1,2,0.0,0,SC,KOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,69.5,0,1
HB-103164,City Hotel,0,0,2025,May,21,23,2025-05-23,0,1,1,0.0,0,BB,PRT,Direct,Direct,1,0,3,D,D,0,No Deposit,,408.0,0,Transient,110.0,0,0
HB-006608,Resort Hotel,1,177,2024,June,25,20,2024-06-20,1,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,Non Refund,240.0,,0,Transient,72.0,0,0
HB-098672,City Hotel,0,193,2024,September,40,30,2024-09-30,1,2,2,0.0,0,BB,DEU,Groups,Corporate,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,132.0,0,0
HB-089865,City Hotel,0,14,2024,May,22,27,2024-05-27,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,73.0,0,0
HB-027470,Resort Hotel,0,2,2024,August,35,26,2024-08-26,2,2,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient-Party,199.0,0,3
HB-005648,Resort Hotel,1,81,2024,May,19,7,2024-05-07,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,314.0,,0,Transient,52.56,0,0
HB-096775,City Hotel,0,63,2024,September,36,4,2024-09-04,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,103.95,0,1
HB-115730,City Hotel,0,171,2025,July,27,6,2025-07-06,1,3,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,68.61,0,1
HB-028547,Resort Hotel,0,159,2024,October,40,2,2024-10-02,2,2,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,77.0,1,1
HB-036316,Resort Hotel,0,0,2025,May,20,15,2025-05-15,1,0,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,79.0,1,0
HB-070667,City Hotel,1,60,2025,June,25,20,2025-06-20,0,3,2,0.0,0,SC,ARG,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,1
HB-013064,Resort Hotel,1,306,2025,July,31,29,2025-07-29,2,5,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,242.0,,0,Transient,204.62,0,1
HB-052763,City Hotel,1,69,2024,June,24,12,2024-06-12,2,4,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,120.0,0,0
HB-102373,City Hotel,0,47,2024,November,48,25,2024-11-25,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,9.0,,0,Transient,156.6,0,2
HB-005766,Resort Hotel,1,54,2024,May,20,13,2024-05-13,0,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,86.0,0,0
HB-042355,City Hotel,0,26,2023,September,36,5,2023-09-05,1,1,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,95.0,0,2
HB-037300,Resort Hotel,0,15,2025,June,24,11,2025-06-11,2,0,2,0.0,0,HB,ESP,Direct,Direct,0,0,0,D,D,1,No Deposit,250.0,,0,Transient,196.0,1,0
HB-105353,City Hotel,0,53,2025,February,6,4,2025-02-04,0,1,1,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,79.2,0,2
HB-069033,City Hotel,1,225,2025,May,21,24,2025-05-24,0,4,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,0
HB-052512,City Hotel,1,56,2024,June,23,8,2024-06-08,0,1,2,0.0,0,BB,PRT,Offline TA/TO,Corporate,0,0,0,A,A,0,No Deposit,191.0,,0,Transient-Party,120.0,0,0
HB-034909,Resort Hotel,0,152,2025,April,14,5,2025-04-05,0,4,1,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,2,No Deposit,,223.0,0,Transient-Party,49.0,1,0
HB-037551,Resort Hotel,0,159,2025,June,24,15,2025-06-15,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient,110.0,0,1
HB-006273,Resort Hotel,0,206,2024,May,22,31,2024-05-31,2,8,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Transient-Party,64.9,0,1
HB-023900,Resort Hotel,0,140,2024,May,19,6,2024-05-06,0,1,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,,251.0,0,Transient,59.0,0,0
HB-029400,Resort Hotel,0,8,2024,October,43,25,2024-10-25,0,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,81.0,0,2
HB-084242,City Hotel,0,1,2024,February,8,20,2024-02-20,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,81.0,0,0
HB-009200,Resort Hotel,1,113,2024,November,44,2,2024-11-02,0,2,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,37.8,0,2
HB-079208,City Hotel,0,23,2023,October,42,18,2023-10-18,2,3,3,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,E,0,No Deposit,28.0,,0,Transient,105.0,0,1
HB-041017,City Hotel,0,39,2023,August,32,10,2023-08-10,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,62.0,0,1
HB-082960,City Hotel,0,0,2023,October,41,15,2023-10-15,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,1,D,D,0,No Deposit,94.0,,0,Transient,0.0,0,0
HB-115773,City Hotel,0,158,2025,July,28,8,2025-07-08,2,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,1
HB-007041,Resort Hotel,1,181,2024,July,29,17,2024-07-17,4,8,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,160.0,0,2
HB-061591,City Hotel,1,52,2024,December,51,17,2024-12-17,2,4,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.9,0,1
HB-043341,City Hotel,1,74,2023,September,38,18,2023-09-18,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-021824,Resort Hotel,0,81,2024,March,10,9,2024-03-09,0,3,3,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,A,C,0,No Deposit,115.0,,0,Transient-Party,86.55,0,0
HB-068674,City Hotel,1,165,2025,May,21,19,2025-05-19,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,225.0,0,0
HB-009552,Resort Hotel,1,86,2024,December,49,8,2024-12-08,4,10,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,50.2,0,0
HB-037656,Resort Hotel,0,225,2025,June,25,18,2025-06-18,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,86.7,0,0
HB-025836,Resort Hotel,0,191,2024,July,27,7,2024-07-07,2,5,3,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,80.03,0,0
HB-112498,City Hotel,0,42,2025,May,21,21,2025-05-21,2,2,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,1
HB-048501,City Hotel,0,96,2024,March,12,24,2024-03-24,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,9.0,,0,Transient-Party,99.45,0,0
HB-029655,Resort Hotel,0,33,2024,October,43,27,2024-10-27,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,175.0,,0,Transient,55.1,0,0
HB-077685,City Hotel,1,18,2023,October,40,4,2023-10-04,2,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,29.0,,0,Transient,110.0,0,0
HB-048800,City Hotel,1,10,2024,March,13,31,2024-03-31,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,227.0,0,Transient-Party,95.0,0,0
HB-018954,Resort Hotel,0,2,2023,December,48,2,2023-12-02,0,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,39.0,0,0
HB-052645,City Hotel,1,43,2024,June,23,9,2024-06-09,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,75.54,0,1
HB-008241,Resort Hotel,1,199,2024,September,38,19,2024-09-19,1,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,158.0,0,0
HB-086712,City Hotel,0,64,2024,April,14,4,2024-04-04,1,3,3,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,130.05,0,3
HB-057704,City Hotel,1,136,2024,September,40,30,2024-09-30,1,2,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,154.8,0,1
HB-068417,City Hotel,1,40,2025,May,20,17,2025-05-17,0,2,1,0.0,0,BB,FRA,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,215.0,0,1
HB-092108,City Hotel,0,146,2024,June,26,29,2024-06-29,0,2,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,3,No Deposit,9.0,,0,Transient,130.0,0,2
HB-112283,City Hotel,0,122,2025,May,21,19,2025-05-19,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,1
HB-060979,City Hotel,1,35,2024,November,48,28,2024-11-28,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,75.0,0,0
HB-045698,City Hotel,0,79,2023,November,46,18,2023-11-18,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,52.85,0,2
HB-114056,City Hotel,0,60,2025,June,24,13,2025-06-13,0,3,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,168.0,,0,Transient,89.1,0,0
HB-025856,Resort Hotel,0,204,2024,July,28,9,2024-07-09,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,C,1,No Deposit,240.0,,0,Transient,94.6,0,0
HB-024711,Resort Hotel,0,4,2024,May,22,31,2024-05-31,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,47.0,0,Transient,57.0,0,0
HB-037729,Resort Hotel,0,15,2025,June,26,24,2025-06-24,2,1,2,0.0,1,BB,ESP,Direct,Direct,0,0,0,D,D,5,No Deposit,250.0,,0,Transient,150.0,0,1
HB-030409,Resort Hotel,0,115,2024,November,46,17,2024-11-17,1,3,2,0.0,0,BB,IRL,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,34.0,0,0
HB-102453,City Hotel,0,0,2024,November,48,28,2024-11-28,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,98.0,0,0
HB-054799,City Hotel,1,391,2024,July,30,27,2024-07-27,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,65.0,0,0
HB-090743,City Hotel,0,48,2024,June,23,8,2024-06-08,0,3,2,0.0,0,BB,ARG,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,98.87,0,2
HB-056170,City Hotel,1,179,2024,August,35,31,2024-08-31,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient-Party,103.69,0,0
HB-085095,City Hotel,0,46,2024,March,10,4,2024-03-04,2,3,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,16.0,,0,Transient,103.0,0,0
HB-097690,City Hotel,0,21,2024,September,37,15,2024-09-15,2,3,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,145.0,0,2
HB-022889,Resort Hotel,0,80,2024,April,14,7,2024-04-07,0,3,2,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,67.0,,0,Transient-Party,68.0,0,0
HB-084823,City Hotel,0,86,2024,March,9,2,2024-03-02,0,2,2,1.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,60.0,0,1
HB-023016,Resort Hotel,0,36,2024,April,14,7,2024-04-07,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,G,0,No Deposit,241.0,,0,Transient,81.51,0,2
HB-031931,Resort Hotel,0,0,2025,January,2,8,2025-01-08,2,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient,43.0,0,1
HB-118420,City Hotel,0,91,2025,August,33,16,2025-08-16,0,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,9.0,,0,Transient,150.0,0,1
HB-055357,City Hotel,1,247,2024,August,32,11,2024-08-11,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,96.3,0,0
HB-111152,City Hotel,0,51,2025,May,18,2,2025-05-02,0,5,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,126.0,0,0
HB-054743,City Hotel,1,133,2024,July,30,25,2024-07-25,1,2,2,2.0,0,BB,NLD,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,177.3,0,0
HB-118427,City Hotel,0,186,2025,August,33,17,2025-08-17,0,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,89.76,0,0
HB-059256,City Hotel,1,200,2024,October,43,24,2024-10-24,1,3,2,0.0,0,BB,NLD,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,100.3,0,0
HB-043127,City Hotel,0,14,2023,September,37,15,2023-09-15,0,3,1,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,114.0,0,1
HB-088277,City Hotel,0,180,2024,May,18,2,2024-05-02,1,1,2,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,100.0,0,1
HB-073532,City Hotel,1,222,2025,August,35,25,2025-08-25,1,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,0
HB-057541,City Hotel,1,250,2024,September,39,26,2024-09-26,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,95.0,0,0
HB-095772,City Hotel,0,11,2024,August,34,20,2024-08-20,2,2,1,1.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,120.12,0,1
HB-015919,Resort Hotel,0,258,2023,August,31,3,2023-08-03,1,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,134.0,0,0
HB-034032,Resort Hotel,0,3,2025,March,10,9,2025-03-09,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,65.0,0,1
HB-090141,City Hotel,0,21,2024,May,22,29,2024-05-29,2,3,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,101.15,0,0
HB-050826,City Hotel,1,9,2024,May,19,9,2024-05-09,1,3,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,141.0,0,0
HB-056645,City Hotel,1,17,2024,September,37,9,2024-09-09,1,2,0,2.0,0,BB,NLD,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient,109.45,0,2
HB-024919,Resort Hotel,0,71,2024,June,23,6,2024-06-06,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,128.0,1,1
HB-075967,City Hotel,1,301,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-003175,Resort Hotel,1,36,2023,November,47,20,2023-11-20,0,2,2,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,38.0,,0,Transient-Party,64.0,0,0
HB-059881,City Hotel,1,304,2024,November,44,3,2024-11-03,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,89.0,0,0
HB-062537,City Hotel,1,38,2025,January,3,14,2025-01-14,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,Non Refund,,67.0,0,Transient,75.0,0,0
HB-052898,City Hotel,1,71,2024,June,24,14,2024-06-14,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,120.0,0,0
HB-090883,City Hotel,0,19,2024,June,24,12,2024-06-12,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.35,0,1
HB-111309,City Hotel,0,144,2025,May,19,6,2025-05-06,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,52.0,,0,Transient-Party,90.0,0,1
HB-085367,City Hotel,0,6,2024,March,11,11,2024-03-11,1,2,2,0.0,0,SC,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.0,0,1
HB-081058,City Hotel,1,85,2024,January,4,22,2024-01-22,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,29.0,,0,Transient,85.0,0,0
HB-038965,Resort Hotel,0,230,2025,August,31,1,2025-08-01,0,3,2,0.0,1,BB,CN,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient-Party,155.75,0,2
HB-030488,Resort Hotel,0,7,2024,November,47,22,2024-11-22,0,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,336.0,,0,Transient,35.0,1,1
HB-100328,City Hotel,0,238,2024,October,43,22,2024-10-22,2,3,2,0.0,0,BB,CHE,Direct,Direct,0,0,0,B,B,1,No Deposit,14.0,,0,Transient-Party,81.28,0,0
HB-090736,City Hotel,0,1,2024,June,24,11,2024-06-11,0,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,0.0,0,0
HB-097904,City Hotel,0,159,2024,September,38,19,2024-09-19,1,2,2,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,144.0,0,0
HB-090448,City Hotel,0,220,2024,June,23,4,2024-06-04,2,1,2,0.0,0,BB,USA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,73.33,0,1
HB-064163,City Hotel,1,28,2025,March,9,2,2025-03-02,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,95.0,0,0
HB-021855,Resort Hotel,0,62,2024,March,10,7,2024-03-07,1,4,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,45.0,1,1
HB-028045,Resort Hotel,0,336,2024,September,37,15,2024-09-15,1,3,1,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,D,1,No Deposit,,223.0,0,Transient-Party,60.0,0,0
HB-044007,City Hotel,0,68,2023,September,39,29,2023-09-29,0,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,20.0,,0,Transient-Party,65.0,0,0
HB-118876,City Hotel,0,457,2025,August,35,25,2025-08-25,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,122.4,0,1
HB-025251,Resort Hotel,0,0,2024,June,25,20,2024-06-20,0,0,2,0.0,0,BB,PRT,Online TA,TA/TO,1,0,0,A,I,0,No Deposit,15.0,,0,Transient,0.0,0,0
HB-041490,City Hotel,0,7,2023,August,33,17,2023-08-17,1,1,2,2.0,0,SC,NLD,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,9.0,,0,Contract,153.0,0,0
HB-012114,Resort Hotel,1,288,2025,June,24,14,2025-06-14,0,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,80.1,0,1
HB-035127,Resort Hotel,0,62,2025,April,15,9,2025-04-09,2,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,77.84,1,1
HB-101191,City Hotel,0,2,2025,May,18,3,2025-05-03,0,1,1,0.0,0,BB,PRT,Direct,Direct,1,0,2,A,A,1,No Deposit,,,0,Transient,94.0,0,0
HB-096809,City Hotel,0,51,2024,September,36,7,2024-09-07,0,1,2,0.0,0,SC,CZE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.3,1,1
HB-056395,City Hotel,1,88,2024,September,36,4,2024-09-04,2,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,149.4,0,0
HB-082573,City Hotel,0,68,2023,December,52,30,2023-12-30,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,93.78,0,0
HB-028555,Resort Hotel,0,142,2024,September,39,26,2024-09-26,3,7,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,91.58,1,1
HB-110441,City Hotel,0,155,2025,April,17,24,2025-04-24,1,3,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,1
HB-052113,City Hotel,1,73,2024,May,22,31,2024-05-31,0,2,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,116.1,0,0
HB-008524,Resort Hotel,1,182,2024,October,40,3,2024-10-03,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,26.0,,0,Transient,79.8,0,0
HB-050187,City Hotel,1,13,2024,April,17,25,2024-04-25,1,2,2,0.0,0,SC,ALB,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.0,0,0
HB-070726,City Hotel,1,51,2025,June,25,21,2025-06-21,0,4,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.0,0,1
HB-076935,City Hotel,1,342,2023,September,38,24,2023-09-24,2,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-052296,City Hotel,1,133,2024,June,22,2,2024-06-02,1,3,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,104.76,0,1
HB-039226,Resort Hotel,0,166,2025,August,32,8,2025-08-08,0,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,,0,Transient,213.0,0,1
HB-032911,Resort Hotel,0,1,2025,February,6,8,2025-02-08,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,250.0,,0,Transient-Party,43.0,0,0
HB-085758,City Hotel,0,60,2024,March,11,17,2024-03-17,1,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.61,0,1
HB-004033,Resort Hotel,0,112,2024,February,7,12,2024-02-12,0,2,2,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,70.0,0,0
HB-107419,City Hotel,0,166,2025,March,11,10,2025-03-10,1,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,106.0,0,1
HB-039328,Resort Hotel,0,43,2025,August,32,8,2025-08-08,2,5,3,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,5.0,,0,Transient,269.43,1,0
HB-020543,Resort Hotel,0,16,2024,January,5,30,2024-01-30,2,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,241.0,,0,Transient,49.74,0,1
HB-117015,City Hotel,0,68,2025,July,31,28,2025-07-28,0,1,3,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,230.0,0,1
HB-080200,City Hotel,0,1,2023,November,45,12,2023-11-12,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,71.1,0,0
HB-028202,Resort Hotel,0,174,2024,September,38,20,2024-09-20,1,5,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,G,I,4,No Deposit,240.0,,0,Transient-Party,0.0,0,0
HB-084555,City Hotel,0,12,2024,February,8,24,2024-02-24,0,4,2,1.0,0,HB,FRA,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,9.0,,0,Transient-Party,158.5,0,3
HB-109046,City Hotel,0,64,2025,April,14,2,2025-04-02,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,1
HB-064929,City Hotel,1,56,2025,March,12,21,2025-03-21,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,86.0,,0,Transient,85.0,0,0
HB-053381,City Hotel,0,173,2024,June,25,19,2024-06-19,2,2,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,73.37,0,1
HB-027071,Resort Hotel,0,187,2024,August,33,15,2024-08-15,1,3,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,224.0,1,2
HB-084527,City Hotel,0,12,2024,February,9,26,2024-02-26,0,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.0,0,1
HB-109995,City Hotel,0,14,2025,April,16,19,2025-04-19,0,1,1,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,115.0,0,1
HB-083008,City Hotel,0,0,2024,January,2,12,2024-01-12,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,79.0,0,0
HB-085598,City Hotel,0,161,2024,March,11,15,2024-03-15,0,3,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,60.98,0,1
HB-033935,Resort Hotel,0,7,2025,March,9,2,2025-03-02,2,3,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,1,No Deposit,,223.0,0,Transient-Party,37.0,0,0
HB-000105,Resort Hotel,0,102,2023,July,27,4,2023-07-04,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,96.3,0,1
HB-037460,Resort Hotel,0,1,2025,June,25,18,2025-06-18,2,5,0,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,I,6,No Deposit,,,0,Transient,0.0,0,0
HB-015657,Resort Hotel,1,468,2024,May,19,12,2024-05-12,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,249.0,,0,Transient-Party,67.0,0,0
HB-040218,City Hotel,0,18,2023,July,29,18,2023-07-18,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,75.0,0,0
HB-109436,City Hotel,0,74,2025,April,15,9,2025-04-09,2,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,1
HB-037831,Resort Hotel,0,46,2025,June,26,24,2025-06-24,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,531.0,,0,Transient,156.0,0,2
HB-106467,City Hotel,0,14,2025,February,8,23,2025-02-23,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,121.33,0,1
HB-018770,Resort Hotel,0,3,2023,November,48,28,2023-11-28,0,1,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient,29.0,0,1
HB-067587,City Hotel,1,15,2025,May,19,5,2025-05-05,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,170.0,0,1
HB-113696,City Hotel,0,73,2025,June,23,8,2025-06-08,0,3,1,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,170.0,0,0
HB-050431,City Hotel,1,73,2024,April,18,30,2024-04-30,2,1,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,159.3,0,1
HB-111641,City Hotel,0,51,2025,May,19,10,2025-05-10,0,4,2,0.0,0,SC,COL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,155.03,0,1
HB-001970,Resort Hotel,1,7,2023,September,39,25,2023-09-25,0,1,3,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,G,0,No Deposit,,,0,Transient,129.0,0,0
HB-098555,City Hotel,0,0,2024,October,40,2,2024-10-02,0,0,2,1.0,0,HB,PRT,Online TA,TA/TO,1,0,0,A,K,0,No Deposit,9.0,,0,Transient,0.0,0,1
HB-006358,Resort Hotel,1,6,2024,June,23,5,2024-06-05,2,1,2,2.0,0,BB,DNK,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,169.0,0,0
HB-053139,City Hotel,1,344,2024,June,24,16,2024-06-16,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-002008,Resort Hotel,1,54,2023,September,39,26,2023-09-26,2,6,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,69.13,0,1
HB-011252,Resort Hotel,1,20,2025,April,18,29,2025-04-29,2,2,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,127.0,0,1
HB-018382,Resort Hotel,0,2,2023,November,46,15,2023-11-15,2,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,1,No Deposit,,80.0,0,Transient,43.0,0,0
HB-027573,Resort Hotel,0,159,2024,August,35,27,2024-08-27,2,5,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,115.0,,0,Transient,77.6,0,2
HB-004840,Resort Hotel,0,171,2024,April,14,4,2024-04-04,1,1,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,2,Non Refund,298.0,,0,Transient-Party,54.5,0,0
HB-016602,Resort Hotel,0,41,2023,September,35,1,2023-09-01,0,2,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,171.0,,0,Transient,65.5,0,0
HB-073966,City Hotel,1,279,2023,July,29,23,2023-07-23,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Contract,62.0,0,0
HB-007112,Resort Hotel,1,112,2024,July,30,22,2024-07-22,0,1,2,2.0,0,BB,PRT,Direct,Direct,0,0,0,G,G,0,No Deposit,250.0,,0,Transient,216.0,0,0
HB-051647,City Hotel,1,38,2024,May,21,23,2024-05-23,1,3,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,108.11,0,0
HB-000200,Resort Hotel,0,0,2023,July,27,7,2023-07-07,0,1,3,0.0,0,HB,PRT,Direct,Direct,0,0,0,C,C,0,No Deposit,,,0,Transient,195.0,1,0
HB-003621,Resort Hotel,1,59,2023,December,52,26,2023-12-26,2,6,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,65.18,0,1
HB-025978,Resort Hotel,0,217,2024,July,28,12,2024-07-12,1,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,240.0,,0,Transient,90.0,0,1
HB-104158,City Hotel,0,1,2025,January,1,5,2025-01-05,0,2,2,0.0,0,BB,GTM,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,59.0,0,0
HB-010658,Resort Hotel,1,102,2025,March,13,26,2025-03-26,2,1,1,0.0,0,BB,PRT,Groups,Corporate,0,0,0,A,A,0,Non Refund,495.0,,0,Transient,39.33,0,0
HB-111284,City Hotel,0,15,2025,May,19,6,2025-05-06,2,1,2,1.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,99.0,0,2
HB-096527,City Hotel,0,111,2024,September,35,1,2024-09-01,0,3,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,86.9,0,1
HB-058658,City Hotel,1,37,2024,October,41,13,2024-10-13,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,95.0,0,0
HB-019973,Resort Hotel,0,0,2024,January,2,9,2024-01-09,1,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,48.0,0,0
HB-031826,Resort Hotel,0,181,2025,January,1,5,2025-01-05,0,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,5,No Deposit,240.0,,0,Transient,68.0,1,1
HB-086869,City Hotel,0,90,2024,April,15,8,2024-04-08,1,2,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,1
HB-091552,City Hotel,0,116,2024,June,24,16,2024-06-16,2,5,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.06,0,2
HB-030004,Resort Hotel,0,95,2024,November,45,5,2024-11-05,2,5,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,G,G,1,No Deposit,240.0,,0,Transient,96.0,1,1
HB-055956,City Hotel,1,412,2024,August,34,25,2024-08-25,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-100620,City Hotel,0,30,2024,October,43,27,2024-10-27,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-098289,City Hotel,0,31,2024,September,39,27,2024-09-27,0,1,2,0.0,0,BB,UGA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-027064,Resort Hotel,0,140,2024,August,33,16,2024-08-16,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,240.0,,0,Transient,179.0,0,2
HB-108981,City Hotel,0,111,2025,April,14,3,2025-04-03,1,1,2,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,95.0,0,1
HB-026483,Resort Hotel,0,4,2024,August,31,1,2024-08-01,1,2,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,0,No Deposit,250.0,,0,Transient,257.0,1,2
HB-025605,Resort Hotel,0,8,2024,July,27,1,2024-07-01,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient-Party,159.0,0,0
HB-039469,Resort Hotel,0,57,2025,August,34,19,2025-08-19,2,5,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient-Party,283.43,0,4
HB-057235,City Hotel,1,440,2024,September,38,22,2024-09-22,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-063577,City Hotel,1,100,2025,February,7,14,2025-02-14,0,3,2,0.0,0,BB,LVA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.6,0,1
HB-012713,Resort Hotel,1,74,2025,July,28,13,2025-07-13,2,5,2,0.0,0,Undefined,PRT,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,314.0,,0,Transient,230.3,0,0
HB-102626,City Hotel,0,2,2024,December,48,1,2024-12-01,0,2,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,F,0,No Deposit,9.0,,0,Transient,142.0,0,2
HB-096377,City Hotel,0,2,2024,September,35,1,2024-09-01,0,1,1,0.0,0,BB,ESP,Corporate,Corporate,0,0,0,E,G,0,No Deposit,174.0,,0,Transient,125.0,0,0
HB-109534,City Hotel,0,64,2025,April,15,10,2025-04-10,1,2,2,0.0,0,BB,NLD,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,137.67,0,0
HB-111443,City Hotel,0,30,2025,May,19,10,2025-05-10,0,1,2,0.0,0,BB,NLD,Groups,TA/TO,0,0,0,A,A,1,No Deposit,39.0,,1,Transient-Party,140.0,0,0
HB-051958,City Hotel,0,316,2024,May,21,26,2024-05-26,0,3,2,0.0,0,BB,AUT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,110.0,0,0
HB-052362,City Hotel,1,275,2024,June,23,4,2024-06-04,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,5.0,,69,Transient,62.8,0,0
HB-034400,Resort Hotel,0,96,2025,March,11,12,2025-03-12,4,7,2,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,52.55,0,0
HB-007450,Resort Hotel,1,155,2024,August,32,10,2024-08-10,0,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,240.0,0,0
HB-011730,Resort Hotel,1,353,2025,May,22,27,2025-05-27,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,81.57,0,0
HB-012872,Resort Hotel,1,109,2025,July,30,21,2025-07-21,3,7,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,229.0,0,1
HB-056232,City Hotel,1,57,2024,September,35,1,2024-09-01,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,123.3,0,1
HB-010084,Resort Hotel,1,137,2025,February,7,10,2025-02-10,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,46.8,0,1
HB-047256,City Hotel,1,5,2024,February,7,13,2024-02-13,2,1,2,0.0,0,SC,IND,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.0,0,0
HB-007282,Resort Hotel,1,247,2024,August,31,1,2024-08-01,1,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,126.0,0,2
HB-071361,City Hotel,1,88,2025,July,27,3,2025-07-03,1,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,190.0,0,1
HB-018475,Resort Hotel,0,0,2023,November,47,23,2023-11-23,1,0,1,0.0,0,HB,PRT,Corporate,Corporate,1,0,1,A,D,1,No Deposit,,20.0,0,Transient-Party,42.0,0,0
HB-058589,City Hotel,1,37,2024,October,41,13,2024-10-13,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,95.0,0,0
HB-047282,City Hotel,1,17,2024,February,7,14,2024-02-14,2,1,2,0.0,0,BB,HUN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,91.0,0,1
HB-063192,City Hotel,1,187,2025,February,5,1,2025-02-01,2,5,2,0.0,1,SC,BRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,74.8,0,0
HB-042641,City Hotel,0,0,2023,September,36,8,2023-09-08,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,114.0,0,0
HB-023092,Resort Hotel,0,11,2024,April,15,11,2024-04-11,1,3,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,62.0,1,1
HB-034050,Resort Hotel,0,312,2025,March,10,5,2025-03-05,2,5,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,56.0,0,0
HB-007430,Resort Hotel,1,65,2024,August,32,8,2024-08-08,3,9,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,C,C,0,No Deposit,250.0,,0,Transient,222.5,0,0
HB-098020,City Hotel,0,271,2024,September,38,21,2024-09-21,0,3,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,101.33,0,1
HB-057867,City Hotel,1,44,2024,October,40,2,2024-10-02,2,0,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,113.4,0,0
HB-116408,City Hotel,0,288,2025,July,29,18,2025-07-18,0,2,1,2.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,8.0,,0,Transient,153.0,0,1
HB-109904,City Hotel,0,84,2025,April,16,18,2025-04-18,0,1,1,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,0
HB-087879,City Hotel,0,90,2024,April,17,23,2024-04-23,2,3,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,E,1,No Deposit,9.0,,0,Transient,129.02,1,1
HB-006766,Resort Hotel,1,68,2024,July,27,1,2024-07-01,0,1,3,1.0,0,BB,CN,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,225.0,0,0
HB-116489,City Hotel,0,167,2025,July,29,19,2025-07-19,0,2,2,1.0,0,BB,ARG,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.1,0,3
HB-087050,City Hotel,0,94,2024,April,15,12,2024-04-12,0,2,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,96.3,0,1
HB-037377,Resort Hotel,0,287,2025,June,24,14,2025-06-14,0,2,2,0.0,0,BB,CZE,Online TA,TA/TO,0,0,0,E,F,0,No Deposit,240.0,,0,Transient,121.1,1,2
HB-014276,Resort Hotel,0,75,2023,August,34,22,2023-08-22,2,5,3,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,2,No Deposit,,,0,Transient,175.0,0,0
HB-103637,City Hotel,0,248,2024,December,52,24,2024-12-24,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,B,A,1,No Deposit,9.0,,0,Transient,67.26,0,1
HB-102302,City Hotel,0,42,2024,November,47,24,2024-11-24,0,2,2,1.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,22.0,,0,Transient,85.05,0,0
HB-113325,City Hotel,0,102,2025,June,22,1,2025-06-01,2,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,176.4,0,2
HB-074861,City Hotel,1,164,2023,August,33,14,2023-08-14,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-093229,City Hotel,0,121,2024,July,29,16,2024-07-16,2,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.3,0,1
HB-086549,City Hotel,0,80,2024,March,13,31,2024-03-31,2,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,55.63,0,1
HB-114389,City Hotel,0,85,2025,June,25,17,2025-06-17,2,2,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,126.0,0,1
HB-013674,Resort Hotel,1,0,2025,August,35,26,2025-08-26,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,G,G,0,No Deposit,,,0,Transient,235.0,0,0
HB-013801,Resort Hotel,1,184,2025,August,35,31,2025-08-31,2,5,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,200.86,0,1
HB-097164,City Hotel,0,19,2024,September,37,12,2024-09-12,1,0,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.0,0,0
HB-004875,Resort Hotel,1,116,2024,April,14,4,2024-04-04,2,5,2,0.0,0,HB,GBR,Groups,Direct,0,0,0,D,D,0,Non Refund,273.0,,0,Transient,72.0,0,0
HB-088239,City Hotel,0,61,2024,May,20,15,2024-05-15,1,0,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,1,A,E,0,No Deposit,9.0,,0,Transient,135.9,0,2
HB-040133,City Hotel,0,67,2023,July,28,10,2023-07-10,2,3,2,2.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,22.0,,0,Transient,106.25,0,0
HB-086233,City Hotel,0,122,2024,March,13,27,2024-03-27,2,1,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,26.0,,0,Transient-Party,86.0,0,0
HB-039264,Resort Hotel,0,188,2025,August,31,3,2025-08-03,2,8,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,169.0,0,1
HB-036283,Resort Hotel,0,13,2025,May,20,14,2025-05-14,1,0,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient,48.0,0,0
HB-095581,City Hotel,0,180,2024,August,33,14,2024-08-14,2,5,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,7.0,,0,Transient,95.13,0,2
HB-074663,City Hotel,1,359,2023,October,41,11,2023-10-11,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-017010,Resort Hotel,0,239,2023,September,38,19,2023-09-19,1,1,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,H,0,No Deposit,248.0,,0,Transient-Party,80.0,0,0
HB-119231,City Hotel,0,213,2025,August,35,28,2025-08-28,1,3,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,19.0,,0,Transient-Party,104.0,0,0
HB-005291,Resort Hotel,1,143,2024,April,17,24,2024-04-24,2,2,2,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,68.0,,0,Transient,84.0,0,0
HB-055368,City Hotel,1,398,2024,August,32,11,2024-08-11,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-018131,Resort Hotel,0,11,2023,November,44,2,2023-11-02,1,4,2,0.0,0,BB,AUT,Corporate,Corporate,0,0,0,A,A,1,No Deposit,185.0,281.0,0,Transient-Party,43.2,0,0
HB-013478,Resort Hotel,1,184,2025,August,33,17,2025-08-17,0,2,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,200.0,0,2
HB-083349,City Hotel,0,58,2024,January,4,27,2024-01-27,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,87.0,,0,Transient-Party,91.0,0,0
HB-081781,City Hotel,1,113,2024,February,8,25,2024-02-25,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,44,Transient,75.0,0,0
HB-035755,Resort Hotel,0,0,2025,April,18,30,2025-04-30,1,0,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,100.0,0,0
HB-075666,City Hotel,1,290,2023,August,31,3,2023-08-03,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-049796,City Hotel,1,103,2024,April,16,19,2024-04-19,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,0,Transient,115.0,0,0
HB-035604,Resort Hotel,0,31,2025,April,17,23,2025-04-23,2,4,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,93.0,0,0
HB-043568,City Hotel,0,141,2023,September,38,20,2023-09-20,1,0,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,90.0,0,0
HB-093075,City Hotel,0,163,2024,July,28,14,2024-07-14,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient-Party,112.0,0,1
HB-066013,City Hotel,1,53,2025,April,15,13,2025-04-13,0,1,2,0.0,0,SC,ECU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,0
HB-015909,Resort Hotel,0,66,2023,August,31,3,2023-08-03,1,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,F,0,No Deposit,,,0,Transient,168.25,0,0
HB-043204,City Hotel,0,76,2023,September,37,16,2023-09-16,0,2,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-034790,Resort Hotel,0,1,2025,April,14,4,2025-04-04,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,127.0,,0,Transient-Party,61.6,0,0
HB-076124,City Hotel,1,288,2023,October,42,16,2023-10-16,0,2,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,1,Non Refund,6.0,,0,Transient-Party,80.0,0,0
HB-021993,Resort Hotel,0,13,2024,March,11,14,2024-03-14,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,3,No Deposit,,,0,Transient,45.0,0,0
HB-090256,City Hotel,0,112,2024,June,22,2,2024-06-02,0,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,100.0,0,0
HB-012183,Resort Hotel,1,308,2025,June,25,16,2025-06-16,3,7,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,80.1,0,1
HB-001917,Resort Hotel,0,111,2023,September,38,21,2023-09-21,1,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,89.0,0,1
HB-035808,Resort Hotel,0,100,2025,April,18,29,2025-04-29,2,1,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,D,D,0,No Deposit,385.0,,0,Transient-Party,93.0,0,1
HB-073033,City Hotel,1,123,2025,August,33,12,2025-08-12,2,3,3,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,177.08,0,1
HB-093540,City Hotel,0,119,2024,July,29,21,2024-07-21,0,2,2,1.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,16.0,,0,Transient,131.08,0,0
HB-056566,City Hotel,1,433,2024,September,36,8,2024-09-08,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,70.0,0,0
HB-068479,City Hotel,1,107,2025,May,20,18,2025-05-18,1,3,2,0.0,0,BB,LUX,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,146.25,0,0
HB-066379,City Hotel,1,23,2025,April,16,18,2025-04-18,0,3,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,214.0,0,0
HB-063411,City Hotel,1,58,2025,February,7,11,2025-02-11,2,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,95.4,0,0
HB-046751,City Hotel,1,0,2024,January,3,19,2024-01-19,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,,0,Transient,65.0,0,0
HB-073123,City Hotel,1,35,2025,August,33,15,2025-08-15,0,1,1,0.0,0,SC,MAR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,140.0,0,1
HB-006001,Resort Hotel,1,125,2024,May,20,19,2024-05-19,2,7,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,88.0,0,1
HB-073957,City Hotel,1,279,2023,July,29,23,2023-07-23,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Contract,62.0,0,0
HB-055275,City Hotel,0,218,2024,August,32,9,2024-08-09,0,4,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.95,0,1
HB-050533,City Hotel,1,75,2024,May,18,3,2024-05-03,0,2,2,0.0,0,BB,KOR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,140.4,0,1
HB-036134,Resort Hotel,0,117,2025,May,19,7,2025-05-07,2,2,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,C,1,No Deposit,410.0,,0,Transient,40.95,0,1
HB-106021,City Hotel,0,34,2025,February,8,17,2025-02-17,0,2,2,0.0,0,SC,AUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,67.76,0,1
HB-069460,City Hotel,1,292,2025,May,22,31,2025-05-31,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,90.0,0,0
HB-085192,City Hotel,0,38,2024,April,14,4,2024-04-04,1,3,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,6,E,E,1,No Deposit,,51.0,0,Transient,106.0,0,1
HB-044591,City Hotel,1,210,2023,October,40,8,2023-10-08,1,3,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,0.0,0,0
HB-039336,Resort Hotel,0,190,2025,August,32,8,2025-08-08,2,5,2,2.0,0,BB,CN,Direct,Direct,0,0,0,C,C,2,No Deposit,250.0,,0,Transient,198.0,0,1
HB-046596,City Hotel,1,29,2024,January,2,9,2024-01-09,2,4,1,1.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,100.0,0,0
HB-066072,City Hotel,1,136,2025,April,15,13,2025-04-13,1,3,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,173.25,0,0
HB-085716,City Hotel,0,1,2024,March,11,17,2024-03-17,0,3,2,0.0,1,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,119.67,0,2
HB-096564,City Hotel,0,0,2024,September,36,3,2024-09-03,0,1,2,0.0,0,SC,BEL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,139.13,0,0
HB-035448,Resort Hotel,0,150,2025,April,16,17,2025-04-17,1,5,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,129.0,1,1
HB-013963,Resort Hotel,0,0,2025,June,24,12,2025-06-12,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,2,13,A,A,0,No Deposit,,135.0,0,Transient,82.0,1,2
HB-081362,City Hotel,0,11,2023,December,49,5,2023-12-05,2,2,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,0.0,0,0
HB-040582,City Hotel,0,117,2023,August,31,1,2023-08-01,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-087298,City Hotel,0,122,2024,April,16,15,2024-04-15,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,151.0,,56,Transient-Party,85.0,0,0
HB-070826,City Hotel,1,233,2025,June,26,23,2025-06-23,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,105.0,0,0
HB-108385,City Hotel,0,50,2025,March,13,24,2025-03-24,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,115.2,1,3
HB-030914,Resort Hotel,0,3,2024,December,49,6,2024-12-06,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,60.0,0,1
HB-107765,City Hotel,0,8,2025,March,12,17,2025-03-17,0,1,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,2
HB-005859,Resort Hotel,1,9,2024,May,20,15,2024-05-15,1,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,315.0,,0,Transient-Party,70.0,0,0
HB-100704,City Hotel,0,4,2025,March,11,13,2025-03-13,1,1,1,0.0,0,BB,ESP,Aviation,Corporate,1,0,1,A,A,0,No Deposit,,153.0,0,Transient,80.0,0,2
HB-020656,Resort Hotel,0,25,2024,February,6,5,2024-02-05,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,29.0,0,0
HB-057573,City Hotel,1,103,2024,September,39,28,2024-09-28,0,1,1,0.0,0,SC,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,85.0,0,0
HB-067926,City Hotel,1,15,2025,May,19,9,2025-05-09,0,3,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,180.0,0,2
HB-005625,Resort Hotel,1,19,2024,May,19,6,2024-05-06,2,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,2,No Deposit,250.0,,0,Transient,118.7,0,0
HB-077676,City Hotel,0,3,2023,September,38,21,2023-09-21,1,2,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,133.0,0,2
HB-020961,Resort Hotel,0,2,2024,February,7,12,2024-02-12,0,2,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,95.0,0,0
HB-058471,City Hotel,1,97,2024,October,41,12,2024-10-12,1,4,2,0.0,0,BB,USA,Direct,Direct,0,0,0,F,F,3,No Deposit,14.0,,0,Transient,176.8,0,0
HB-056457,City Hotel,1,230,2024,September,36,6,2024-09-06,0,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,44.0,,0,Transient-Party,137.0,0,0
HB-022309,Resort Hotel,0,28,2024,March,12,19,2024-03-19,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,74.0,1,0
HB-105486,City Hotel,0,5,2025,February,6,4,2025-02-04,2,4,2,1.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,80.76,0,1
HB-105769,City Hotel,0,1,2025,February,7,14,2025-02-14,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,98.0,0,1
HB-104274,City Hotel,0,64,2025,January,1,3,2025-01-03,2,5,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,1
HB-082894,City Hotel,1,68,2024,February,7,17,2024-02-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,37.0,,0,Transient,75.0,0,0
HB-107461,City Hotel,0,66,2025,March,11,10,2025-03-10,1,2,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,154.0,,0,Transient-Party,80.0,0,1
HB-014657,Resort Hotel,0,152,2023,September,36,6,2023-09-06,7,15,2,0.0,0,HB,DEU,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,81.82,0,0
HB-079590,City Hotel,0,7,2023,October,43,29,2023-10-29,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient-Party,65.0,0,0
HB-086078,City Hotel,0,75,2024,March,12,24,2024-03-24,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,114.3,0,1
HB-083179,City Hotel,0,2,2024,January,4,23,2024-01-23,0,1,1,0.0,0,BB,PRT,Complementary,Direct,0,0,0,D,D,1,No Deposit,45.0,,0,Transient,0.0,1,0
HB-052654,City Hotel,1,337,2024,June,23,9,2024-06-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-065189,City Hotel,1,39,2025,March,13,27,2025-03-27,1,1,1,0.0,0,SC,MYS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.0,0,0
HB-071994,City Hotel,1,190,2025,July,29,17,2025-07-17,1,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,89.1,0,0
HB-095618,City Hotel,0,2,2024,August,34,19,2024-08-19,0,2,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,133.0,0,2
HB-091290,City Hotel,0,1,2024,June,25,18,2024-06-18,0,1,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,F,0,No Deposit,9.0,,0,Transient,159.0,0,2
HB-030832,Resort Hotel,0,7,2024,December,48,1,2024-12-01,1,3,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,97.25,1,0
HB-102550,City Hotel,0,14,2024,November,48,28,2024-11-28,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,80.0,0,0
HB-083678,City Hotel,0,59,2024,February,6,6,2024-02-06,2,2,2,0.0,0,BB,AUT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-076780,City Hotel,1,395,2024,March,12,21,2024-03-21,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-004241,Resort Hotel,0,123,2024,February,9,27,2024-02-27,1,1,2,0.0,0,FB,ESP,Groups,Direct,0,0,0,A,C,0,No Deposit,38.0,,0,Transient-Party,64.0,0,0
HB-010112,Resort Hotel,1,9,2025,February,7,13,2025-02-13,1,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,60.0,0,1
HB-093810,City Hotel,0,2,2024,July,30,25,2024-07-25,1,1,3,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient-Party,85.0,0,1
HB-077593,City Hotel,0,4,2024,April,16,18,2024-04-18,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,14,A,A,0,No Deposit,,40.0,0,Transient,67.0,0,1
HB-103776,City Hotel,0,7,2024,December,1,30,2024-12-30,0,2,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,158.0,0,0
HB-032212,Resort Hotel,0,40,2025,January,3,16,2025-01-16,1,2,1,0.0,0,Undefined,IDN,Groups,Direct,0,0,0,A,D,2,No Deposit,,,0,Transient-Party,55.0,0,0
HB-090787,City Hotel,0,107,2024,June,24,10,2024-06-10,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,187.0,,0,Transient-Party,130.0,0,1
HB-026704,Resort Hotel,0,174,2024,August,31,1,2024-08-01,2,5,2,1.0,0,Undefined,PRT,Offline TA/TO,TA/TO,0,0,0,A,B,1,No Deposit,196.0,,0,Transient-Party,165.0,0,3
HB-021606,Resort Hotel,0,32,2024,March,9,1,2024-03-01,0,5,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,56.0,0,1
HB-029641,Resort Hotel,0,0,2024,November,44,1,2024-11-01,0,1,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,55.0,0,0
HB-073458,City Hotel,1,173,2025,August,34,22,2025-08-22,2,7,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,202.5,0,0
HB-105567,City Hotel,0,24,2025,February,6,9,2025-02-09,0,3,2,0.0,0,BB,CHE,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-112046,City Hotel,0,12,2025,May,19,7,2025-05-07,4,8,2,0.0,0,BB,GRC,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,146.0,0,1
HB-085379,City Hotel,0,49,2024,March,10,9,2024-03-09,1,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,73.95,0,1
HB-098427,City Hotel,0,28,2024,September,39,27,2024-09-27,0,3,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,97.58,0,1
HB-055786,City Hotel,1,5,2024,August,34,21,2024-08-21,1,0,2,0.0,0,BB,PRT,Online TA,Corporate,0,0,0,A,A,0,Non Refund,,47.0,0,Transient,167.0,0,0
HB-095029,City Hotel,0,67,2024,August,33,13,2024-08-13,0,1,2,0.0,0,SC,LUX,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.1,0,1
HB-116685,City Hotel,0,423,2025,July,30,22,2025-07-22,1,1,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,122.4,0,1
HB-034778,Resort Hotel,0,19,2025,March,13,29,2025-03-29,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,75.0,,0,Transient,49.0,1,0
HB-001137,Resort Hotel,0,65,2023,August,33,15,2023-08-15,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,107.0,0,0
HB-001934,Resort Hotel,1,159,2023,September,38,22,2023-09-22,0,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,74.0,0,2
HB-102212,City Hotel,0,215,2024,November,47,21,2024-11-21,1,2,1,0.0,0,BB,POL,Groups,Corporate,0,0,0,A,A,1,No Deposit,,233.0,0,Transient,75.0,0,0
HB-045850,City Hotel,0,98,2023,November,47,23,2023-11-23,1,3,1,0.0,0,BB,DZA,Groups,TA/TO,0,0,0,A,A,1,No Deposit,37.0,,0,Transient-Party,70.0,0,0
HB-048940,City Hotel,0,109,2024,April,14,2,2024-04-02,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient,74.89,0,0
HB-086012,City Hotel,0,5,2024,March,12,21,2024-03-21,1,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,128.0,1,1
HB-097494,City Hotel,0,307,2024,September,37,11,2024-09-11,2,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,A,2,No Deposit,8.0,,0,Transient,108.0,0,0
HB-107947,City Hotel,0,24,2025,March,11,15,2025-03-15,1,4,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.4,0,0
HB-074539,City Hotel,1,339,2023,September,38,21,2023-09-21,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-051430,City Hotel,1,0,2024,May,21,20,2024-05-20,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,152.0,,0,Transient,88.56,0,0
HB-097683,City Hotel,0,7,2024,September,38,16,2024-09-16,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,7.0,,0,Transient,191.73,0,2
HB-058443,City Hotel,1,314,2024,October,41,12,2024-10-12,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,68,Transient,75.0,0,0
HB-092144,City Hotel,0,125,2024,June,26,30,2024-06-30,0,1,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.5,0,1
HB-069313,City Hotel,1,25,2025,May,22,30,2025-05-30,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,90.0,0,0
HB-047072,City Hotel,1,12,2024,February,6,6,2024-02-06,0,1,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.0,0,0
HB-060705,City Hotel,1,64,2024,November,47,18,2024-11-18,1,2,1,0.0,0,BB,LUX,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,86.4,0,1
HB-039524,Resort Hotel,0,163,2025,August,32,10,2025-08-10,2,8,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,40.0,,0,Contract,119.85,0,0
HB-113293,City Hotel,0,236,2025,June,23,3,2025-06-03,1,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,138.6,0,2
HB-026669,Resort Hotel,0,4,2024,August,32,6,2024-08-06,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,231.0,0,1
HB-089874,City Hotel,0,84,2024,May,21,26,2024-05-26,0,2,0,2.0,0,BB,PRT,Direct,Direct,0,0,0,B,B,1,No Deposit,14.0,,0,Transient,128.78,0,0
HB-053466,City Hotel,1,40,2024,June,25,21,2024-06-21,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,76.92,0,0
HB-003571,Resort Hotel,0,155,2023,December,51,24,2023-12-24,0,3,2,0.0,1,BB,GBR,Direct,Direct,0,0,0,C,C,0,No Deposit,250.0,,0,Transient-Party,47.6,0,3
HB-015372,Resort Hotel,0,186,2023,July,27,7,2023-07-07,0,4,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,154.0,0,1
HB-031646,Resort Hotel,0,123,2024,December,52,29,2024-12-29,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,84.83,0,1
HB-033699,Resort Hotel,0,48,2025,February,9,28,2025-02-28,0,1,2,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,49.74,0,1
HB-059790,City Hotel,1,21,2024,November,44,1,2024-11-01,0,4,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,102.0,0,1
HB-038642,Resort Hotel,0,0,2025,July,30,25,2025-07-25,0,1,2,0.0,0,BB,ESP,Direct,Direct,1,0,0,D,D,1,No Deposit,,,0,Transient,189.0,1,0
HB-090934,City Hotel,0,14,2024,June,24,12,2024-06-12,2,0,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.0,0,1
HB-049477,City Hotel,1,281,2024,April,15,14,2024-04-14,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-097988,City Hotel,0,53,2024,September,38,20,2024-09-20,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,115.04,0,1
HB-031591,Resort Hotel,0,55,2024,December,1,30,2024-12-30,0,2,2,0.0,1,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,164.0,1,2
HB-019965,Resort Hotel,0,3,2024,January,2,9,2024-01-09,1,1,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,147.0,,0,Transient,29.01,0,0
HB-094900,City Hotel,0,128,2024,August,32,8,2024-08-08,1,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.3,0,1
HB-090588,City Hotel,0,118,2024,June,23,6,2024-06-06,1,2,1,0.0,0,BB,POL,Offline TA/TO,Corporate,0,0,0,A,A,2,No Deposit,191.0,,0,Transient-Party,110.0,0,0
HB-107178,City Hotel,0,83,2025,March,10,5,2025-03-05,2,2,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,97.2,0,0
HB-089037,City Hotel,0,45,2024,May,19,12,2024-05-12,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,168.3,0,0
HB-062590,City Hotel,1,327,2025,January,3,16,2025-01-16,1,0,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,114.3,0,0
HB-033374,Resort Hotel,0,16,2025,February,8,17,2025-02-17,2,2,2,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,D,D,0,No Deposit,,498.0,0,Transient-Party,55.0,1,0
HB-015055,Resort Hotel,1,2,2025,January,1,4,2025-01-04,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,8,A,A,1,No Deposit,,270.0,0,Transient,35.0,0,0
HB-016790,Resort Hotel,0,52,2023,September,36,8,2023-09-08,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Contract,79.5,0,1
HB-112862,City Hotel,0,11,2025,May,21,24,2025-05-24,1,4,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,197.0,0,2
HB-020881,Resort Hotel,0,8,2024,February,7,12,2024-02-12,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,53.0,0,0
HB-029951,Resort Hotel,0,14,2024,November,45,9,2024-11-09,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,126.0,,0,Transient,30.0,1,0
HB-117676,City Hotel,0,206,2025,August,31,2,2025-08-02,2,4,2,2.0,0,HB,NLD,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,256.5,0,2
HB-069336,City Hotel,1,186,2025,May,22,30,2025-05-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,130.0,0,0
HB-022578,Resort Hotel,0,8,2024,March,13,28,2024-03-28,1,0,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,196.0,,0,Transient,61.2,0,0
HB-113880,City Hotel,0,4,2025,June,24,10,2025-06-10,2,1,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,219.33,0,2
HB-084644,City Hotel,0,116,2024,February,9,28,2024-02-28,2,1,1,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,76.0,0,0
HB-117289,City Hotel,0,19,2025,July,31,30,2025-07-30,2,1,3,0.0,0,BB,DNK,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,234.33,1,1
HB-106413,City Hotel,0,49,2025,February,8,20,2025-02-20,1,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.1,0,1
HB-083682,City Hotel,0,0,2024,February,6,8,2024-02-08,1,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,88.0,1,0
HB-035106,Resort Hotel,0,6,2025,April,15,10,2025-04-10,1,2,2,1.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,5,No Deposit,250.0,,0,Transient,123.28,0,0
HB-106429,City Hotel,0,34,2025,February,8,19,2025-02-19,2,4,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-045815,City Hotel,0,98,2023,November,47,23,2023-11-23,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,70.0,0,0
HB-051920,City Hotel,1,159,2024,May,21,26,2024-05-26,0,3,1,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,F,F,14,No Deposit,9.0,,0,Transient-Party,187.85,0,0
HB-084650,City Hotel,0,7,2024,February,9,29,2024-02-29,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,68.0,1,0
HB-001681,Resort Hotel,0,2,2023,September,36,9,2023-09-09,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,146.0,1,0
HB-023070,Resort Hotel,0,194,2024,April,14,6,2024-04-06,2,7,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,46.0,0,0
HB-006575,Resort Hotel,1,228,2024,June,25,18,2024-06-18,2,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,110.0,0,0
HB-051402,City Hotel,1,322,2024,May,20,19,2024-05-19,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,120,Transient,80.0,0,0
HB-010511,Resort Hotel,1,332,2025,March,11,11,2025-03-11,2,5,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,D,D,0,No Deposit,298.0,,0,Transient-Party,71.0,0,0
HB-069691,City Hotel,1,13,2025,June,23,4,2025-06-04,2,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,160.0,0,0
HB-017260,Resort Hotel,1,277,2023,October,40,5,2023-10-05,4,10,2,0.0,0,HB,GBR,Groups,Direct,0,1,0,D,D,0,Non Refund,273.0,,0,Transient,78.5,0,0
HB-048594,City Hotel,0,90,2024,March,13,25,2024-03-25,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,96.3,0,0
HB-079307,City Hotel,0,14,2023,October,42,20,2023-10-20,0,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,114.0,0,2
HB-035737,Resort Hotel,0,30,2025,April,17,27,2025-04-27,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,92.0,1,0
HB-085030,City Hotel,0,37,2024,March,10,4,2024-03-04,2,2,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,73.1,0,0
HB-000879,Resort Hotel,0,34,2023,August,31,2,2023-08-02,2,5,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,C,C,3,No Deposit,250.0,,0,Transient,174.76,1,1
HB-083490,City Hotel,0,5,2024,February,5,2,2024-02-02,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,64.0,0,0
HB-114477,City Hotel,0,13,2025,June,25,19,2025-06-19,1,3,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,9.0,,0,Transient,270.0,0,0
HB-041448,City Hotel,0,0,2023,August,33,16,2023-08-16,2,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,2,No Deposit,,,0,Transient,124.0,0,0
HB-021956,Resort Hotel,0,97,2024,March,10,4,2024-03-04,3,7,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,26.0,0,1
HB-011815,Resort Hotel,1,411,2025,May,22,31,2025-05-31,2,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,71.1,0,0
HB-057014,City Hotel,1,31,2024,September,38,16,2024-09-16,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,75.0,0,0
HB-072522,City Hotel,1,130,2025,July,31,29,2025-07-29,4,7,2,0.0,0,SC,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,71.1,0,1
HB-110783,City Hotel,0,16,2025,May,18,1,2025-05-01,1,0,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,96.0,0,1
HB-020026,Resort Hotel,0,0,2024,January,2,13,2024-01-13,0,1,1,0.0,0,BB,ESP,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,38.0,0,0
HB-089290,City Hotel,0,0,2024,May,20,19,2024-05-19,0,1,1,0.0,0,BB,FRA,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,210.0,0,0
HB-077495,City Hotel,0,263,2023,September,38,21,2023-09-21,1,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,B,0,No Deposit,21.0,,0,Transient-Party,67.0,0,0
HB-058862,City Hotel,1,284,2024,October,42,16,2024-10-16,2,3,2,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient-Party,81.82,0,0
HB-113660,City Hotel,0,91,2025,June,23,5,2025-06-05,1,5,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,130.67,0,0
HB-013130,Resort Hotel,1,136,2025,August,31,1,2025-08-01,2,5,3,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,301.43,0,0
HB-028059,Resort Hotel,0,11,2024,September,38,18,2024-09-18,1,0,2,0.0,0,BB,CHE,Offline TA/TO,TA/TO,0,0,0,D,E,0,No Deposit,251.0,,0,Transient,78.0,0,0
HB-030177,Resort Hotel,0,3,2024,December,52,27,2024-12-27,0,2,2,0.0,0,BB,PRT,Direct,Direct,1,0,1,A,I,0,No Deposit,250.0,,0,Transient,54.9,1,0
HB-027726,Resort Hotel,0,266,2024,September,36,2,2024-09-02,2,5,2,0.0,0,BB,LTU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,171.0,,0,Transient,65.66,0,0
HB-093669,City Hotel,0,186,2024,July,29,21,2024-07-21,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.95,0,1
HB-052767,City Hotel,1,69,2024,June,24,12,2024-06-12,2,4,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,120.0,0,0
HB-059138,City Hotel,1,192,2024,October,43,21,2024-10-21,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,29.0,,0,Transient-Party,95.0,0,0
HB-069111,City Hotel,1,247,2025,May,21,25,2025-05-25,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,138.6,0,1
HB-031448,Resort Hotel,0,39,2024,December,52,26,2024-12-26,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,60.0,0,0
HB-019087,Resort Hotel,0,5,2023,December,49,5,2023-12-05,2,1,2,0.0,0,HB,ESP,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,108.0,0,0
HB-049513,City Hotel,1,126,2024,April,15,14,2024-04-14,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,39,Transient,65.0,0,0
HB-071134,City Hotel,1,142,2025,June,26,28,2025-06-28,0,3,2,1.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.0,0,0
HB-088928,City Hotel,0,0,2024,May,20,13,2024-05-13,0,2,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,K,0,No Deposit,21.0,,0,Transient,90.0,0,0
HB-001442,Resort Hotel,1,54,2023,August,35,29,2023-08-29,2,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,121.5,0,0
HB-006798,Resort Hotel,0,236,2024,July,27,2,2024-07-02,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,81.0,0,2
HB-045590,City Hotel,1,63,2023,November,45,9,2023-11-09,1,4,2,0.0,1,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,91.63,0,2
HB-066773,City Hotel,1,146,2025,April,17,25,2025-04-25,0,3,2,0.0,0,SC,AUT,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,102.0,0,0
HB-100129,City Hotel,0,44,2024,October,42,20,2024-10-20,0,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,113.7,0,1
HB-039789,Resort Hotel,0,261,2025,August,34,24,2025-08-24,1,3,3,0.0,0,HB,POL,Offline TA/TO,TA/TO,0,0,0,A,C,1,No Deposit,315.0,,0,Contract,175.56,0,0
HB-028897,Resort Hotel,0,178,2024,October,41,10,2024-10-10,1,2,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,85.0,0,1
HB-012289,Resort Hotel,1,244,2025,June,25,22,2025-06-22,1,3,2,0.0,0,HB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,127.8,0,2
HB-112071,City Hotel,0,395,2025,May,20,17,2025-05-17,0,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,2
HB-058012,City Hotel,1,40,2024,October,40,5,2024-10-05,0,2,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.5,0,0
HB-017372,Resort Hotel,0,53,2023,October,40,4,2023-10-04,2,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,F,0,No Deposit,250.0,,0,Transient,65.4,1,2
HB-110787,City Hotel,0,107,2025,April,17,27,2025-04-27,2,3,2,0.0,0,HB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,154.8,0,2
HB-026404,Resort Hotel,0,8,2024,July,31,29,2024-07-29,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,214.0,0,1
HB-051042,City Hotel,1,273,2024,May,20,13,2024-05-13,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,95.0,0,0
HB-035971,Resort Hotel,0,36,2025,May,18,3,2025-05-03,0,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,85.2,0,1
HB-084876,City Hotel,0,36,2024,March,9,2,2024-03-02,0,3,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,117.3,0,1
HB-023789,Resort Hotel,1,4,2025,February,6,7,2025-02-07,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,3,A,D,0,No Deposit,,135.0,0,Transient,35.0,0,0
HB-050142,City Hotel,1,146,2024,April,17,24,2024-04-24,2,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,26.0,,50,Transient,95.0,0,0
HB-034870,Resort Hotel,0,26,2025,April,14,4,2025-04-04,0,4,2,0.0,0,BB,SRB,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient-Party,105.0,0,2
HB-101768,City Hotel,0,9,2024,November,46,14,2024-11-14,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,1
HB-023475,Resort Hotel,0,172,2024,April,16,18,2024-04-18,3,5,2,0.0,0,HB,IRL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,115.0,,0,Transient,75.6,0,0
HB-074220,City Hotel,1,278,2023,July,29,22,2023-07-22,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Contract,62.0,0,0
HB-020178,Resort Hotel,0,2,2025,February,7,15,2025-02-15,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,1,0,3,A,D,0,No Deposit,240.0,,0,Transient,55.0,0,1
HB-096547,City Hotel,0,156,2024,August,35,29,2024-08-29,1,5,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,111.6,0,0
HB-115148,City Hotel,0,215,2025,June,27,30,2025-06-30,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.05,0,1
HB-107599,City Hotel,0,20,2025,March,11,13,2025-03-13,1,2,1,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,1,No Deposit,254.0,,0,Transient-Party,153.67,0,0
HB-081677,City Hotel,1,182,2024,April,17,27,2024-04-27,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,3.0,,50,Transient,75.0,0,0
HB-094144,City Hotel,0,16,2024,July,31,30,2024-07-30,1,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,166.0,0,1
HB-045782,City Hotel,1,98,2023,November,47,23,2023-11-23,1,2,1,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,84.0,0,0
HB-031411,Resort Hotel,0,78,2024,December,52,26,2024-12-26,1,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,46.8,0,1
HB-033611,Resort Hotel,0,51,2025,February,9,25,2025-02-25,1,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,250.0,,0,Transient,44.0,0,0
HB-011083,Resort Hotel,1,168,2025,April,16,17,2025-04-17,1,3,2,0.0,0,HB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,81.0,0,2
HB-096563,City Hotel,0,40,2024,August,35,31,2024-08-31,0,4,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,168.0,,0,Transient,113.25,0,0
HB-089711,City Hotel,0,212,2024,May,21,20,2024-05-20,2,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,78.0,0,0
HB-095987,City Hotel,0,129,2024,August,34,25,2024-08-25,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,109.8,1,0
HB-048933,City Hotel,0,91,2024,April,14,2,2024-04-02,2,2,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,59.37,0,0
HB-091347,City Hotel,0,45,2024,June,25,18,2024-06-18,1,1,3,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,27.0,,0,Transient,122.4,0,0
HB-008422,Resort Hotel,0,542,2024,September,39,26,2024-09-26,2,5,2,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,E,E,0,No Deposit,253.0,,0,Transient-Party,89.0,0,2
HB-095370,City Hotel,0,0,2024,August,33,17,2024-08-17,0,1,2,0.0,0,BB,AUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,150.0,0,2
HB-114826,City Hotel,0,263,2025,June,26,23,2025-06-23,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,105.0,0,1
HB-038346,Resort Hotel,0,82,2025,July,28,12,2025-07-12,0,3,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,241.0,,0,Transient,176.8,0,1
HB-020214,Resort Hotel,0,40,2024,January,2,13,2024-01-13,2,5,1,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,314.0,,0,Transient,39.79,1,0
HB-088470,City Hotel,0,103,2024,May,18,4,2024-05-04,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,154.0,,0,Transient-Party,80.0,0,0
HB-096758,City Hotel,0,99,2024,September,36,5,2024-09-05,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,137.1,0,1
HB-006373,Resort Hotel,1,18,2024,June,23,6,2024-06-06,1,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,109.0,0,0
HB-045396,City Hotel,0,72,2023,October,43,28,2023-10-28,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,D,1,No Deposit,37.0,,58,Transient-Party,75.33,0,0
HB-029930,Resort Hotel,0,55,2024,November,45,6,2024-11-06,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,F,E,0,No Deposit,241.0,,0,Transient,46.43,0,0
HB-113951,City Hotel,0,97,2025,June,24,10,2025-06-10,2,3,2,1.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,170.5,0,0
HB-027900,Resort Hotel,0,116,2024,September,37,9,2024-09-09,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient,130.0,0,1
HB-063521,City Hotel,1,17,2025,February,7,13,2025-02-13,1,1,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,128.0,0,2
HB-106805,City Hotel,0,8,2025,February,9,28,2025-02-28,0,3,2,1.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,9.0,,0,Transient,137.0,1,2
HB-117970,City Hotel,0,53,2025,August,33,11,2025-08-11,0,2,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,2
HB-062687,City Hotel,1,14,2025,January,3,18,2025-01-18,0,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.78,0,0
HB-112503,City Hotel,0,13,2025,May,21,24,2025-05-24,0,1,1,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,160.0,0,2
HB-025519,Resort Hotel,0,220,2024,June,26,24,2024-06-24,2,5,2,0.0,1,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,314.0,,0,Transient,79.2,0,1
HB-022785,Resort Hotel,0,1,2024,April,14,6,2024-04-06,0,2,2,0.0,0,BB,USA,Direct,TA/TO,0,0,0,E,E,0,No Deposit,,,0,Transient,85.0,0,1
HB-105997,City Hotel,0,70,2025,February,7,15,2025-02-15,0,4,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,D,1,No Deposit,,242.0,0,Transient-Party,68.0,0,0
HB-095011,City Hotel,0,116,2024,August,33,12,2024-08-12,0,1,2,2.0,0,BB,USA,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,7.0,,0,Transient,202.74,0,1
HB-008109,Resort Hotel,1,65,2024,September,37,11,2024-09-11,2,3,2,1.0,0,BB,IRL,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,195.0,0,0
HB-038391,Resort Hotel,0,27,2025,July,29,14,2025-07-14,0,2,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,180.0,0,2
HB-116381,City Hotel,0,10,2025,July,29,15,2025-07-15,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,113.98,0,0
HB-050922,City Hotel,0,286,2024,May,19,11,2024-05-11,0,4,3,0.0,0,BB,AUT,Groups,TA/TO,0,0,0,A,D,1,No Deposit,30.0,,176,Transient-Party,143.5,0,1
HB-018512,Resort Hotel,0,18,2023,November,46,16,2023-11-16,1,5,2,0.0,0,BB,VEN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,64.0,1,2
HB-040935,City Hotel,0,120,2023,August,32,9,2023-08-09,2,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,2
HB-000643,Resort Hotel,0,18,2023,July,30,24,2023-07-24,0,2,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,D,G,0,No Deposit,250.0,,0,Transient,154.0,0,0
HB-019460,Resort Hotel,0,0,2023,December,51,19,2023-12-19,1,1,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,35.11,0,1
HB-047181,City Hotel,0,0,2024,February,7,12,2024-02-12,0,1,0,0.0,0,SC,PRT,Complementary,Corporate,0,0,0,D,A,2,No Deposit,,45.0,0,Transient,0.0,0,2
HB-006621,Resort Hotel,1,293,2024,June,25,21,2024-06-21,0,5,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,72.0,0,0
HB-070002,City Hotel,1,169,2025,June,23,8,2025-06-08,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,170.0,0,0
HB-055404,City Hotel,1,177,2024,August,33,12,2024-08-12,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,127.8,0,1
HB-093612,City Hotel,0,100,2024,July,30,22,2024-07-22,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,123.3,0,1
HB-067463,City Hotel,1,3,2025,May,18,4,2025-05-04,0,1,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,260.0,0,0
HB-013106,Resort Hotel,1,329,2025,July,31,31,2025-07-31,1,5,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,138.38,0,0
HB-042822,City Hotel,0,9,2023,September,36,10,2023-09-10,1,3,2,0.0,0,BB,AUT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,27.0,,0,Transient,63.75,0,0
HB-111414,City Hotel,0,167,2025,May,19,7,2025-05-07,2,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,42.0,,0,Transient,89.1,0,0
HB-098868,City Hotel,0,26,2024,October,40,3,2024-10-03,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,153.0,0,2
HB-066448,City Hotel,1,125,2025,April,16,20,2025-04-20,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,33.0,,0,Transient,85.0,0,0
HB-048445,City Hotel,0,97,2024,March,12,23,2024-03-23,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,65.42,0,1
HB-079527,City Hotel,1,192,2024,May,18,5,2024-05-05,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,D,D,0,No Deposit,9.0,,0,Transient,115.2,0,1
HB-052550,City Hotel,1,26,2024,June,23,8,2024-06-08,0,1,2,0.0,0,BB,PRT,Offline TA/TO,Corporate,0,0,0,A,A,0,No Deposit,191.0,,0,Transient-Party,120.0,0,0
HB-059863,City Hotel,1,304,2024,November,44,3,2024-11-03,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,89.0,0,0
HB-119075,City Hotel,0,10,2025,August,35,27,2025-08-27,2,0,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.5,0,2
HB-060672,City Hotel,1,21,2024,November,47,18,2024-11-18,0,2,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,174.0,0,1
HB-113225,City Hotel,0,25,2025,June,23,3,2025-06-03,0,1,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,0
HB-086274,City Hotel,0,4,2025,May,22,30,2025-05-30,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,12,A,A,0,No Deposit,,219.0,0,Transient,95.0,0,1
HB-053826,City Hotel,1,131,2024,June,26,30,2024-06-30,0,3,2,1.0,0,BB,CZE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,112.5,0,0
HB-079773,City Hotel,1,149,2024,March,13,26,2024-03-26,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,8.0,,0,Transient,91.56,0,0
HB-111250,City Hotel,0,17,2025,May,19,5,2025-05-05,1,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,0
HB-000331,Resort Hotel,0,1,2023,July,28,12,2023-07-12,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,80.1,0,0
HB-071610,City Hotel,1,122,2025,July,28,9,2025-07-09,2,0,2,1.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,144.0,0,0
HB-044272,City Hotel,0,204,2023,October,40,2,2023-10-02,1,2,1,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,7.0,,0,Transient,59.07,0,0
HB-057942,City Hotel,1,35,2024,October,40,3,2024-10-03,1,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.5,0,0
HB-107382,City Hotel,0,57,2025,March,11,11,2025-03-11,0,1,2,0.0,0,BB,USA,Online TA,GDS,0,0,0,A,A,0,No Deposit,195.0,,0,Transient,108.0,0,0
HB-046489,City Hotel,0,30,2024,January,1,3,2024-01-03,1,0,0,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,B,B,2,No Deposit,9.0,,0,Transient-Party,15.0,0,1
HB-080940,City Hotel,0,0,2023,November,48,28,2023-11-28,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient,77.25,0,2
HB-079973,City Hotel,0,52,2023,November,45,6,2023-11-06,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,73.2,0,1
HB-036789,Resort Hotel,0,307,2025,May,21,22,2025-05-22,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,40.0,,0,Transient,94.1,0,0
HB-050265,City Hotel,1,129,2024,April,17,27,2024-04-27,2,5,2,0.0,0,SC,RUS,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,92.89,0,0
HB-044717,City Hotel,0,79,2023,October,41,10,2023-10-10,1,1,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-051832,City Hotel,0,316,2024,May,21,26,2024-05-26,0,3,2,0.0,0,BB,AUT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,110.0,0,0
HB-014683,Resort Hotel,1,259,2023,September,37,17,2023-09-17,0,3,2,0.0,0,BB,GBR,Groups,Corporate,0,1,0,A,A,0,Non Refund,,223.0,0,Transient,40.05,0,0
HB-072568,City Hotel,1,174,2025,July,31,31,2025-07-31,1,3,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,184.5,0,0
HB-093260,City Hotel,0,112,2024,July,29,18,2024-07-18,1,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,104.5,0,1
HB-013903,Resort Hotel,0,2,2024,November,45,9,2024-11-09,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,1,8,A,H,0,No Deposit,,81.0,0,Transient,33.0,1,2
HB-075329,City Hotel,1,311,2023,August,34,24,2023-08-24,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-058538,City Hotel,1,37,2024,October,41,13,2024-10-13,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,95.0,0,0
HB-072713,City Hotel,1,87,2025,August,31,3,2025-08-03,2,5,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,133.29,0,1
HB-111714,City Hotel,0,114,2025,May,19,10,2025-05-10,0,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.0,0,1
HB-113327,City Hotel,0,4,2025,June,23,4,2025-06-04,2,0,2,0.0,0,BB,AUS,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,8.0,,0,Transient,280.0,0,2
HB-040623,City Hotel,1,28,2023,August,31,3,2023-08-03,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-051290,City Hotel,0,133,2024,May,20,17,2024-05-17,0,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,B,1,No Deposit,9.0,,0,Transient-Party,105.3,0,0
HB-048683,City Hotel,1,76,2024,March,13,26,2024-03-26,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,99.45,0,0
HB-099070,City Hotel,0,88,2024,October,41,7,2024-10-07,0,2,2,0.0,0,BB,POL,Corporate,Corporate,0,0,0,A,A,0,No Deposit,193.0,,0,Transient-Party,90.0,0,1
HB-022329,Resort Hotel,0,61,2024,March,12,19,2024-03-19,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,2
HB-031310,Resort Hotel,0,55,2024,December,51,19,2024-12-19,1,3,2,0.0,1,BB,CHN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,30.6,0,0
HB-113933,City Hotel,0,32,2025,June,24,12,2025-06-12,1,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,8,No Deposit,9.0,,0,Transient,190.0,0,1
HB-102133,City Hotel,0,33,2024,November,47,20,2024-11-20,2,1,2,0.0,0,SC,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,52.0,,0,Transient,63.0,0,0
HB-046045,City Hotel,1,198,2023,December,49,5,2023-12-05,2,1,2,0.0,0,HB,ESP,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,90.0,0,0
HB-018290,Resort Hotel,0,0,2023,November,46,15,2023-11-15,1,0,2,0.0,0,BB,CHE,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,59.0,1,0
HB-102160,City Hotel,0,215,2024,November,47,21,2024-11-21,1,2,1,0.0,0,BB,LTU,Groups,Corporate,0,0,0,A,A,0,No Deposit,,233.0,0,Transient,75.0,0,1
HB-029073,Resort Hotel,0,0,2024,October,42,17,2024-10-17,1,2,1,0.0,0,HB,ITA,Groups,Corporate,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,50.0,0,1
HB-086450,City Hotel,0,94,2024,March,13,28,2024-03-28,1,5,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,16.0,,0,Transient-Party,110.75,0,1
HB-023484,Resort Hotel,0,172,2024,April,16,18,2024-04-18,3,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,147.0,,0,Transient-Party,66.42,0,1
HB-065086,City Hotel,1,72,2025,March,13,24,2025-03-24,0,1,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,G,2,No Deposit,9.0,,0,Transient,79.2,0,0
HB-073080,City Hotel,1,73,2025,August,33,14,2025-08-14,1,0,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,200.0,0,0
HB-062642,City Hotel,1,54,2025,January,3,18,2025-01-18,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,171.0,,0,Transient,65.0,0,0
HB-084874,City Hotel,0,3,2024,March,9,2,2024-03-02,0,3,2,2.0,0,BB,CHE,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,183.0,0,0
HB-034307,Resort Hotel,0,26,2025,March,11,14,2025-03-14,0,5,1,0.0,0,HB,CHE,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient-Party,65.0,0,0
HB-003287,Resort Hotel,0,52,2023,December,48,3,2023-12-03,2,5,2,0.0,0,HB,GBR,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,87.53,0,0
HB-039794,Resort Hotel,0,315,2025,August,34,21,2025-08-21,2,5,2,1.0,0,HB,PRT,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,196.0,,0,Transient,282.03,1,1
HB-060420,City Hotel,1,489,2024,November,45,10,2024-11-10,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-074881,City Hotel,1,153,2023,August,31,3,2023-08-03,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-029856,Resort Hotel,0,26,2024,November,45,4,2024-11-04,1,2,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,65.14,0,1
HB-118539,City Hotel,0,240,2025,August,34,18,2025-08-18,2,2,3,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,158.1,0,1
HB-060679,City Hotel,1,301,2024,November,47,18,2024-11-18,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,52.0,0,0
HB-023011,Resort Hotel,0,26,2024,April,15,9,2024-04-09,2,2,3,1.0,0,BB,USA,Direct,Direct,0,0,0,H,H,3,No Deposit,250.0,,0,Transient,146.38,1,1
HB-056893,City Hotel,1,433,2024,September,37,15,2024-09-15,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-097534,City Hotel,0,65,2024,September,37,14,2024-09-14,0,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,149.4,0,1
HB-016171,Resort Hotel,0,2,2023,August,33,16,2023-08-16,1,0,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,241.0,,0,Transient,118.58,0,0
HB-050312,City Hotel,1,13,2024,April,17,28,2024-04-28,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,137.67,0,1
HB-022344,Resort Hotel,0,1,2024,March,12,24,2024-03-24,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,0.0,0,0
HB-041484,City Hotel,0,46,2023,August,33,17,2023-08-17,1,1,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-061789,City Hotel,1,102,2024,December,52,26,2024-12-26,1,3,0,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient-Party,101.34,0,0
HB-041799,City Hotel,0,53,2023,August,34,24,2023-08-24,1,1,2,1.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,D,1,No Deposit,1.0,,0,Transient-Party,62.0,0,1
HB-037285,Resort Hotel,0,19,2025,June,23,2,2025-06-02,3,7,2,0.0,0,HB,RUS,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,241.0,,0,Transient,172.8,0,1
HB-053217,City Hotel,1,350,2024,June,25,17,2024-06-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,140.0,0,0
HB-035584,Resort Hotel,0,85,2025,April,17,23,2025-04-23,2,3,2,0.0,0,FB,GBR,Offline TA/TO,TA/TO,0,0,0,A,E,0,No Deposit,40.0,,0,Contract,90.95,0,0
HB-007601,Resort Hotel,1,28,2024,August,33,16,2024-08-16,0,3,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,219.0,0,0
HB-100730,City Hotel,0,7,2024,October,44,29,2024-10-29,2,1,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,142.19,0,1
HB-100140,City Hotel,0,9,2024,October,43,21,2024-10-21,0,2,2,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,0.0,0,0
HB-047345,City Hotel,1,44,2024,February,7,17,2024-02-17,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,44.0,,3,Transient,75.0,0,0
HB-047736,City Hotel,1,8,2024,March,9,2,2024-03-02,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,94.0,,0,Transient-Party,56.0,0,0
HB-049118,City Hotel,1,105,2024,April,14,6,2024-04-06,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,0,Transient,75.0,0,0
HB-012393,Resort Hotel,1,48,2025,June,26,26,2025-06-26,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,E,F,0,No Deposit,531.0,,0,Transient,162.57,0,2
HB-062531,City Hotel,1,38,2025,January,3,14,2025-01-14,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,Non Refund,,67.0,0,Transient,75.0,0,0
HB-002283,Resort Hotel,0,10,2023,October,40,8,2023-10-08,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient-Party,48.57,0,1
HB-092641,City Hotel,0,254,2024,July,28,9,2024-07-09,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,B,A,0,No Deposit,9.0,,0,Transient-Party,100.7,0,1
HB-075528,City Hotel,1,355,2023,October,40,7,2023-10-07,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-046965,City Hotel,1,18,2024,January,5,29,2024-01-29,3,7,2,0.0,0,SC,AGO,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,77.2,0,0
HB-027100,Resort Hotel,0,99,2024,August,32,6,2024-08-06,4,10,2,0.0,0,HB,RUS,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,5.0,,0,Transient,190.34,0,0
HB-031345,Resort Hotel,0,73,2024,December,51,17,2024-12-17,3,6,2,0.0,0,HB,RUS,Direct,Direct,0,0,0,D,D,1,No Deposit,,,0,Transient,80.2,0,0
HB-109716,City Hotel,0,105,2025,April,15,13,2025-04-13,0,3,2,0.0,0,SC,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,80.1,0,0
HB-058848,City Hotel,1,132,2024,October,42,16,2024-10-16,2,2,3,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,151.2,0,0
HB-115539,City Hotel,0,66,2025,July,27,3,2025-07-03,1,3,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,150.0,0,1
HB-096841,City Hotel,0,203,2024,September,36,5,2024-09-05,1,3,2,1.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,102.08,0,1
HB-021538,Resort Hotel,0,0,2024,March,9,2,2024-03-02,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,45.0,0,0
HB-014156,Resort Hotel,0,5,2024,December,50,14,2024-12-14,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,2,A,D,0,No Deposit,,154.0,0,Transient,27.0,0,0
HB-118262,City Hotel,0,113,2025,August,33,14,2025-08-14,1,2,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,195.0,0,1
HB-074617,City Hotel,1,367,2023,October,42,19,2023-10-19,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-062970,City Hotel,1,61,2025,January,4,25,2025-01-25,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,326.0,,0,Transient,80.0,0,0
HB-105950,City Hotel,0,114,2025,February,7,15,2025-02-15,0,4,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,242.0,0,Transient-Party,78.0,0,0
HB-099762,City Hotel,0,31,2024,October,42,14,2024-10-14,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-082759,City Hotel,1,68,2024,February,7,17,2024-02-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,37.0,,0,Transient,75.0,0,0
HB-050224,City Hotel,1,116,2024,April,17,26,2024-04-26,4,10,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,86.21,0,0
HB-004741,Resort Hotel,0,169,2024,March,13,31,2024-03-31,0,3,2,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,E,1,Refundable,,223.0,0,Transient-Party,66.0,0,0
HB-115678,City Hotel,0,1,2025,July,27,6,2025-07-06,0,3,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,152.0,,0,Transient,89.67,0,0
HB-074195,City Hotel,1,363,2023,October,41,15,2023-10-15,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-003072,Resort Hotel,0,2,2023,November,46,13,2023-11-13,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,185.0,281.0,0,Transient-Party,43.2,0,0
HB-065766,City Hotel,1,124,2025,April,15,8,2025-04-08,1,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,1
HB-033560,Resort Hotel,0,3,2025,February,9,25,2025-02-25,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,80.0,0,2
HB-083947,City Hotel,0,1,2024,February,7,13,2024-02-13,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,80.0,0,0
HB-076443,City Hotel,1,358,2023,October,41,10,2023-10-10,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-065601,City Hotel,1,95,2025,April,14,5,2025-04-05,2,5,2,0.0,0,HB,ITA,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,134.25,0,0
HB-072327,City Hotel,1,243,2025,July,30,26,2025-07-26,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-111409,City Hotel,0,0,2025,May,19,10,2025-05-10,0,1,2,2.0,0,BB,BRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,260.0,0,0
HB-015147,Resort Hotel,0,8,2024,February,5,4,2024-02-04,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,D,0,No Deposit,,82.0,0,Transient,30.0,0,0
HB-043035,City Hotel,0,21,2023,September,37,12,2023-09-12,2,5,1,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,104.43,0,2
HB-042244,City Hotel,0,80,2023,September,35,3,2023-09-03,1,3,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,62.83,0,1
HB-078898,City Hotel,0,34,2023,October,42,18,2023-10-18,1,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,76.5,0,0
HB-079605,City Hotel,0,29,2023,October,43,27,2023-10-27,0,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Group,75.0,0,0
HB-046217,City Hotel,0,119,2023,December,52,26,2023-12-26,2,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,72.25,0,3
HB-032614,Resort Hotel,0,0,2025,January,5,30,2025-01-30,1,0,1,0.0,0,BB,PRT,Direct,TA/TO,1,0,0,A,A,1,No Deposit,,,0,Transient,47.0,1,1
HB-118191,City Hotel,0,3,2025,August,33,13,2025-08-13,2,1,1,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,180.0,0,1
HB-028296,Resort Hotel,0,217,2024,September,38,21,2024-09-21,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,59.6,0,1
HB-110657,City Hotel,0,21,2025,April,18,29,2025-04-29,0,1,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,115.0,0,2
HB-039167,Resort Hotel,0,134,2025,August,31,2,2025-08-02,2,6,3,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,3,No Deposit,40.0,,0,Contract,141.55,0,0
HB-111655,City Hotel,0,3,2025,May,19,11,2025-05-11,0,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,27.0,,0,Transient-Party,141.0,0,0
HB-015667,Resort Hotel,1,468,2024,May,19,12,2024-05-12,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,249.0,,0,Transient-Party,67.0,0,0
HB-069625,City Hotel,1,111,2025,June,23,2,2025-06-02,1,2,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-044160,City Hotel,1,199,2023,October,39,1,2023-10-01,2,7,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,94.5,0,0
HB-064015,City Hotel,1,19,2025,February,9,26,2025-02-26,2,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,D,D,0,No Deposit,30.0,,2,Transient-Party,75.0,0,0
HB-059605,City Hotel,1,64,2024,October,44,30,2024-10-30,1,0,1,0.0,0,BB,VNM,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,0
HB-064829,City Hotel,1,66,2025,March,12,17,2025-03-17,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.2,0,0
HB-074667,City Hotel,1,359,2023,October,41,11,2023-10-11,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-105389,City Hotel,0,17,2025,February,5,2,2025-02-02,1,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,100.3,0,0
HB-056338,City Hotel,1,420,2024,September,36,3,2024-09-03,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,35.0,,0,Transient,75.0,0,0
HB-054786,City Hotel,1,129,2024,July,30,26,2024-07-26,1,5,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,132.88,0,0
HB-066717,City Hotel,1,170,2025,April,17,23,2025-04-23,2,2,2,0.0,0,BB,AUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,4
HB-047941,City Hotel,1,47,2024,March,10,10,2024-03-10,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,91.8,0,0
HB-052871,City Hotel,1,107,2024,June,24,14,2024-06-14,0,2,2,0.0,0,SC,CPV,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient,116.1,0,0
HB-058714,City Hotel,1,75,2024,October,42,14,2024-10-14,2,5,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.0,0,2
HB-046876,City Hotel,0,27,2024,January,4,23,2024-01-23,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,93.0,0,0
HB-061602,City Hotel,1,103,2024,December,51,18,2024-12-18,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.4,0,0
HB-016011,Resort Hotel,0,129,2023,August,32,10,2023-08-10,2,5,2,1.0,0,FB,PRT,Direct,Direct,0,0,0,C,C,1,No Deposit,250.0,,0,Transient,225.08,1,2
HB-072780,City Hotel,1,258,2025,August,32,6,2025-08-06,2,0,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,0
HB-020650,Resort Hotel,0,5,2024,January,5,31,2024-01-31,2,4,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,F,0,No Deposit,2.0,,0,Transient,50.67,0,0
HB-055452,City Hotel,1,212,2024,August,33,13,2024-08-13,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,96.0,0,0
HB-072716,City Hotel,1,266,2025,August,31,3,2025-08-03,2,7,2,1.0,0,HB,BRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,8.0,,0,Transient,256.0,0,1
HB-057814,City Hotel,1,268,2024,October,40,1,2024-10-01,1,1,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,95.4,0,0
HB-049324,City Hotel,1,24,2024,April,15,10,2024-04-10,2,3,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,120.27,0,0
HB-100637,City Hotel,0,6,2024,October,43,26,2024-10-26,0,4,1,0.0,0,BB,FRA,Aviation,Corporate,0,0,0,D,D,0,No Deposit,,153.0,0,Transient,110.0,0,0
HB-028301,Resort Hotel,0,237,2024,September,37,15,2024-09-15,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Contract,64.9,0,1
HB-105789,City Hotel,0,15,2025,February,7,14,2025-02-14,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,42.0,,0,Transient,80.0,0,0
HB-032152,Resort Hotel,0,0,2025,January,3,18,2025-01-18,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,52.0,1,0
HB-075402,City Hotel,1,323,2023,September,36,5,2023-09-05,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-078989,City Hotel,0,221,2023,October,42,17,2023-10-17,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,65.0,0,0
HB-067135,City Hotel,1,9,2025,April,18,28,2025-04-28,2,2,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,8.0,,0,Transient,290.0,0,0
HB-103536,City Hotel,0,20,2024,December,51,21,2024-12-21,2,4,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,96.9,0,2
HB-036183,Resort Hotel,0,257,2025,May,19,9,2025-05-09,0,4,1,0.0,0,HB,GBR,Groups,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,67.5,0,0
HB-045285,City Hotel,0,69,2023,October,43,25,2023-10-25,2,1,2,0.0,0,BB,GRC,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,98.25,0,2
HB-037639,Resort Hotel,0,239,2025,June,25,19,2025-06-19,1,4,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient,99.0,0,1
HB-013313,Resort Hotel,1,193,2025,August,32,8,2025-08-08,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,190.0,0,1
HB-015215,Resort Hotel,1,267,2023,September,39,26,2023-09-26,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,96.0,,0,Transient,54.99,0,0
HB-102766,City Hotel,0,13,2024,December,49,5,2024-12-05,1,0,1,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.0,0,0
HB-025651,Resort Hotel,0,0,2024,July,27,4,2024-07-04,1,0,3,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,1,No Deposit,,,0,Transient,159.0,0,1
HB-054381,City Hotel,1,372,2024,July,28,14,2024-07-14,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-000027,Resort Hotel,0,48,2023,July,26,1,2023-07-01,2,5,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Contract,79.5,0,0
HB-044830,City Hotel,0,184,2023,October,41,12,2023-10-12,1,3,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.25,0,0
HB-099536,City Hotel,0,17,2024,October,41,9,2024-10-09,2,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,95.0,0,1
HB-014226,Resort Hotel,0,150,2025,February,9,24,2025-02-24,0,2,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,2,A,A,2,No Deposit,240.0,,0,Transient,64.8,0,1
HB-037904,Resort Hotel,0,160,2025,July,27,1,2025-07-01,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,110.0,0,1
HB-056309,City Hotel,1,40,2024,September,36,3,2024-09-03,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,96.0,0,0
HB-045518,City Hotel,1,100,2023,October,44,31,2023-10-31,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-077217,City Hotel,0,1,2023,September,37,14,2023-09-14,1,0,1,0.0,0,BB,CN,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,70.0,0,0
HB-008554,Resort Hotel,1,59,2024,October,40,6,2024-10-06,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,79.0,0,1
HB-062573,City Hotel,1,359,2025,January,3,15,2025-01-15,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,77.35,0,0
HB-023873,Resort Hotel,0,103,2024,May,18,1,2024-05-01,2,3,2,0.0,0,BB,NLD,Groups,TA/TO,0,0,0,A,A,7,No Deposit,95.0,,0,Transient-Party,47.0,0,0
HB-114155,City Hotel,0,218,2025,June,24,15,2025-06-15,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.5,0,1
HB-090377,City Hotel,0,191,2024,June,23,3,2024-06-03,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,132.0,0,0
HB-004827,Resort Hotel,0,171,2024,April,14,4,2024-04-04,1,1,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,Non Refund,298.0,,0,Transient-Party,85.0,0,0
HB-019004,Resort Hotel,0,7,2023,December,48,3,2023-12-03,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,49.07,1,1
HB-057269,City Hotel,1,276,2024,September,38,22,2024-09-22,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,178,Transient-Party,95.0,0,0
HB-100227,City Hotel,0,386,2024,October,43,23,2024-10-23,2,0,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-045189,City Hotel,1,65,2023,October,42,22,2023-10-22,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,89.25,0,2
HB-107505,City Hotel,0,49,2025,March,10,9,2025-03-09,1,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,91.8,0,0
HB-060123,City Hotel,1,11,2024,November,45,5,2024-11-05,0,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,140.0,0,1
HB-084664,City Hotel,0,116,2024,February,9,28,2024-02-28,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,82.0,0,0
HB-093951,City Hotel,0,178,2024,July,30,26,2024-07-26,0,3,2,1.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,112.5,0,1
HB-051277,City Hotel,1,217,2024,May,20,17,2024-05-17,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,95.4,0,0
HB-027717,Resort Hotel,0,237,2024,August,35,30,2024-08-30,2,7,2,1.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,C,1,No Deposit,196.0,,0,Transient,112.6,0,0
HB-045319,City Hotel,0,69,2023,October,43,25,2023-10-25,2,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,E,1,No Deposit,37.0,,58,Transient-Party,75.33,0,0
HB-043574,City Hotel,0,17,2023,September,38,20,2023-09-20,2,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-048732,City Hotel,1,60,2024,March,13,29,2024-03-29,0,1,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,123.3,0,1
HB-111293,City Hotel,0,90,2025,May,19,8,2025-05-08,1,0,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,3
HB-011878,Resort Hotel,1,113,2025,June,23,2,2025-06-02,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,110.0,0,1
HB-033725,Resort Hotel,0,40,2025,February,9,25,2025-02-25,2,3,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,92.0,0,1
HB-025604,Resort Hotel,0,8,2024,July,27,1,2024-07-01,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient-Party,171.0,1,0
HB-000855,Resort Hotel,0,3,2023,August,31,1,2023-08-01,2,5,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,188.29,0,2
HB-027802,Resort Hotel,0,3,2024,September,37,10,2024-09-10,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,240.0,,0,Transient,159.0,0,2
HB-071324,City Hotel,1,220,2025,July,27,2,2025-07-02,2,0,2,2.0,0,BB,DEU,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,179.1,0,0
HB-102459,City Hotel,0,67,2024,November,48,25,2024-11-25,2,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-070496,City Hotel,1,150,2025,June,25,17,2025-06-17,2,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,120.0,0,0
HB-054734,City Hotel,1,76,2024,July,30,25,2024-07-25,1,1,2,0.0,0,SC,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,63.75,0,0
HB-069962,City Hotel,1,169,2025,June,23,8,2025-06-08,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,170.0,0,0
HB-112098,City Hotel,0,22,2025,May,21,19,2025-05-19,0,1,2,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,0.0,0,1
HB-090823,City Hotel,0,87,2024,June,23,9,2024-06-09,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,97.71,0,1
HB-003285,Resort Hotel,0,45,2023,December,48,3,2023-12-03,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,55.95,1,1
HB-041675,City Hotel,0,1,2023,August,34,21,2023-08-21,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,9.0,,0,Transient,90.0,0,0
HB-020598,Resort Hotel,0,7,2024,February,5,3,2024-02-03,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-093906,City Hotel,0,85,2024,July,30,26,2024-07-26,0,3,0,2.0,0,BB,CHE,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient,106.54,0,1
HB-058619,City Hotel,1,37,2024,October,41,13,2024-10-13,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,95.0,0,0
HB-085909,City Hotel,0,112,2024,March,12,21,2024-03-21,1,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,7.0,,0,Transient,58.9,0,0
HB-062178,City Hotel,1,139,2025,January,1,3,2025-01-03,0,4,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.0,0,1
HB-097061,City Hotel,0,240,2024,September,37,10,2024-09-10,1,1,2,0.0,0,HB,ITA,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,96.0,0,1
HB-039288,Resort Hotel,0,1,2025,August,33,11,2025-08-11,0,2,3,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,295.0,1,0
HB-042987,City Hotel,1,65,2023,September,37,12,2023-09-12,2,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,86.0,0,0
HB-107409,City Hotel,0,144,2025,March,11,11,2025-03-11,1,1,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.6,0,3
HB-064677,City Hotel,1,37,2025,March,11,15,2025-03-15,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,378.0,,0,Transient,110.0,0,0
HB-000924,Resort Hotel,1,118,2023,August,31,6,2023-08-06,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,120.6,0,0
HB-052461,City Hotel,1,213,2024,June,23,7,2024-06-07,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,62,Transient,130.0,0,0
HB-055779,City Hotel,1,16,2024,August,34,21,2024-08-21,1,0,2,0.0,0,SC,MAR,Online TA,TA/TO,0,0,0,A,E,1,No Deposit,9.0,,0,Transient,129.0,0,1
HB-098210,City Hotel,0,39,2024,September,39,25,2024-09-25,1,0,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,10.0,,0,Transient,129.7,0,0
HB-067992,City Hotel,1,307,2025,May,19,11,2025-05-11,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,276.0,,0,Transient-Party,89.1,0,0
HB-068296,City Hotel,1,164,2025,May,20,15,2025-05-15,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-083148,City Hotel,0,0,2024,January,3,19,2024-01-19,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,101.0,0,0
HB-052842,City Hotel,1,146,2024,June,24,12,2024-06-12,2,1,2,2.0,0,BB,USA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,178.2,0,3
HB-048706,City Hotel,1,54,2024,March,13,28,2024-03-28,1,1,2,0.0,0,SC,MEX,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.1,0,0
HB-017669,Resort Hotel,0,287,2023,October,41,15,2023-10-15,1,3,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,0,No Deposit,,223.0,0,Transient-Party,44.5,0,0
HB-002809,Resort Hotel,0,155,2023,October,44,31,2023-10-31,0,1,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,36.0,1,1
HB-060774,City Hotel,1,18,2024,November,47,20,2024-11-20,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,71.21,0,0
HB-087735,City Hotel,0,6,2024,April,17,24,2024-04-24,1,0,2,0.0,0,HB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,147.0,0,2
HB-034968,Resort Hotel,0,9,2025,April,14,6,2025-04-06,0,3,2,0.0,0,HB,GBR,Direct,Direct,0,0,0,F,F,3,No Deposit,250.0,,0,Transient,162.0,0,1
HB-073180,City Hotel,1,13,2025,August,33,16,2025-08-16,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,160.0,0,0
HB-055712,City Hotel,1,187,2024,August,34,19,2024-08-19,1,2,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.3,0,0
HB-032596,Resort Hotel,0,4,2025,January,5,27,2025-01-27,1,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,43.0,0,2
HB-111688,City Hotel,0,277,2025,May,20,12,2025-05-12,1,2,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,16.0,,0,Transient,89.1,0,1
HB-073484,City Hotel,1,217,2025,August,34,23,2025-08-23,2,5,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.0,0,3
HB-007716,Resort Hotel,1,18,2024,August,34,22,2024-08-22,1,2,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,271.0,0,0
HB-066023,City Hotel,1,31,2025,April,15,13,2025-04-13,0,2,1,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,180.0,0,0
HB-040849,City Hotel,0,4,2023,August,32,8,2023-08-08,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-040473,City Hotel,1,125,2023,July,30,26,2023-07-26,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.5,0,0
HB-116069,City Hotel,0,451,2025,July,28,12,2025-07-12,0,3,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,2
HB-055500,City Hotel,1,252,2024,August,33,14,2024-08-14,2,3,2,2.0,0,BB,DEU,Online TA,TA/TO,0,0,0,B,B,2,No Deposit,9.0,,0,Transient-Party,163.63,0,1
HB-069203,City Hotel,1,196,2025,May,22,27,2025-05-27,1,1,1,0.0,0,SC,MEX,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,2
HB-113143,City Hotel,0,94,2025,May,22,31,2025-05-31,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,142.0,0,0
HB-069784,City Hotel,1,224,2025,June,23,6,2025-06-06,0,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,1
HB-118552,City Hotel,0,212,2025,August,34,18,2025-08-18,2,2,2,1.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.9,0,4
HB-094060,City Hotel,0,79,2024,July,30,24,2024-07-24,2,4,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.5,0,4
HB-111916,City Hotel,0,0,2025,May,20,17,2025-05-17,0,1,1,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,152.0,,0,Transient,106.28,0,0
HB-067009,City Hotel,1,111,2025,April,17,27,2025-04-27,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,0,Transient,120.0,0,0
HB-072038,City Hotel,1,88,2025,July,29,18,2025-07-18,0,3,2,0.0,0,BB,ARG,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,150.0,0,1
HB-104062,City Hotel,0,110,2025,January,1,3,2025-01-03,0,2,0,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,B,A,0,No Deposit,9.0,,0,Transient,91.6,0,1
HB-036373,Resort Hotel,0,260,2025,May,19,11,2025-05-11,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Contract,40.95,0,0
HB-017322,Resort Hotel,0,0,2023,October,40,4,2023-10-04,1,0,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient,86.0,1,0
HB-099578,City Hotel,0,105,2024,October,41,12,2024-10-12,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,132.0,,0,Transient-Party,75.0,0,0
HB-003254,Resort Hotel,0,57,2023,November,47,26,2023-11-26,0,3,1,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,36.0,0,1
HB-051594,City Hotel,0,142,2024,May,21,22,2024-05-22,2,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,114.3,0,0
HB-067443,City Hotel,1,266,2025,May,18,3,2025-05-03,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,0,Transient,100.0,0,0
HB-066154,City Hotel,1,58,2025,April,16,15,2025-04-15,0,1,2,0.0,0,SC,ISR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-023227,Resort Hotel,0,0,2024,April,16,18,2024-04-18,1,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,146.0,,0,Transient,40.0,0,0
HB-057407,City Hotel,1,25,2024,September,39,26,2024-09-26,1,0,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.0,0,0
HB-004393,Resort Hotel,1,22,2024,March,11,11,2024-03-11,0,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,43.0,0,0
HB-054109,City Hotel,1,365,2024,July,27,7,2024-07-07,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-092530,City Hotel,0,56,2024,July,27,3,2024-07-03,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.7,0,2
HB-027476,Resort Hotel,0,35,2024,August,35,30,2024-08-30,0,2,3,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,241.0,,0,Transient,244.09,0,1
HB-032185,Resort Hotel,0,40,2025,January,3,16,2025-01-16,1,2,1,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,55.0,0,0
HB-019120,Resort Hotel,0,19,2023,December,49,5,2023-12-05,2,1,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,26.0,0,0
HB-034326,Resort Hotel,0,0,2025,March,12,19,2025-03-19,1,0,2,0.0,0,BB,USA,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient-Party,100.0,0,0
HB-046277,City Hotel,0,2,2023,December,52,29,2023-12-29,0,2,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,89.0,,0,Transient,109.61,0,1
HB-032044,Resort Hotel,0,0,2025,January,3,14,2025-01-14,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,44.0,0,0
HB-112789,City Hotel,0,178,2025,May,21,25,2025-05-25,0,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-089128,City Hotel,0,0,2024,May,20,17,2024-05-17,0,1,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.0,0,0
HB-041362,City Hotel,0,40,2023,August,33,15,2023-08-15,2,2,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-106160,City Hotel,0,21,2025,February,8,19,2025-02-19,2,1,2,0.0,0,BB,JPN,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,83.0,,0,Transient,72.0,0,0
HB-017266,Resort Hotel,1,277,2023,October,40,5,2023-10-05,4,10,2,0.0,0,HB,GBR,Groups,Direct,0,1,0,D,D,0,Non Refund,273.0,,0,Transient,78.5,0,0
HB-012962,Resort Hotel,1,129,2025,July,30,25,2025-07-25,0,2,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,175.5,0,0
HB-085945,City Hotel,0,0,2024,March,12,24,2024-03-24,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,0.0,0,0
HB-030703,Resort Hotel,0,0,2024,December,48,1,2024-12-01,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,43.0,1,0
HB-040185,City Hotel,1,122,2023,July,28,13,2023-07-13,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,76.5,0,2
HB-002578,Resort Hotel,0,24,2023,October,42,22,2023-10-22,1,3,1,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,E,1,No Deposit,240.0,,0,Transient,56.4,1,1
HB-105811,City Hotel,0,19,2025,February,7,12,2025-02-12,2,2,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,90.71,0,0
HB-056268,City Hotel,1,120,2024,September,36,2,2024-09-02,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,115.0,0,0
HB-115360,City Hotel,0,1,2025,July,27,2,2025-07-02,2,1,2,0.0,0,SC,TUN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,152.0,,0,Transient,70.11,0,0
HB-093364,City Hotel,0,30,2024,July,29,15,2024-07-15,2,4,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,119.1,0,1
HB-012443,Resort Hotel,1,0,2025,June,27,30,2025-06-30,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,F,0,No Deposit,240.0,,0,Transient,144.0,0,0
HB-046939,City Hotel,1,30,2024,January,4,28,2024-01-28,0,3,2,0.0,0,SC,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,67.5,0,1
HB-110166,City Hotel,0,133,2025,April,16,19,2025-04-19,0,4,2,0.0,0,BB,ISL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,390.0,,0,Transient-Party,124.0,0,0
HB-033504,Resort Hotel,0,22,2025,February,8,23,2025-02-23,0,2,2,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,68.0,,0,Transient-Party,60.0,0,0
HB-097644,City Hotel,0,31,2024,September,38,16,2024-09-16,1,2,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,70.0,0,0
HB-004796,Resort Hotel,0,169,2024,March,13,31,2024-03-31,2,3,2,0.0,0,BB,NLD,Groups,Direct,0,0,0,A,A,1,Refundable,,223.0,0,Transient-Party,66.0,0,0
HB-010452,Resort Hotel,1,86,2025,March,10,9,2025-03-09,0,3,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,67.0,,0,Transient,46.0,0,0
HB-032285,Resort Hotel,0,27,2025,January,4,20,2025-01-20,0,2,2,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,468.0,,0,Transient-Party,62.4,0,1
HB-060484,City Hotel,1,138,2024,November,46,12,2024-11-12,0,1,1,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,1
HB-042608,City Hotel,0,26,2023,September,36,8,2023-09-08,0,1,2,0.0,0,BB,AUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,105.0,0,0
HB-110790,City Hotel,0,324,2025,April,18,29,2025-04-29,2,1,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,142.2,0,2
HB-093910,City Hotel,0,179,2024,July,30,27,2024-07-27,0,2,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,112.5,0,2
HB-118500,City Hotel,0,186,2025,August,33,14,2025-08-14,2,5,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,78.44,0,1
HB-003691,Resort Hotel,0,165,2023,December,52,30,2023-12-30,0,4,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,E,0,No Deposit,308.0,,122,Transient-Party,136.5,0,0
HB-098650,City Hotel,0,0,2024,September,39,29,2024-09-29,1,3,1,0.0,0,BB,DEU,Direct,Direct,0,0,0,F,F,3,No Deposit,,,0,Transient,225.0,0,0
HB-044878,City Hotel,0,43,2023,October,41,13,2023-10-13,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,63.0,,0,Transient-Party,75.0,0,0
HB-105437,City Hotel,0,68,2025,February,6,4,2025-02-04,2,2,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,79.2,0,0
HB-085299,City Hotel,0,27,2024,March,10,10,2024-03-10,0,3,2,0.0,1,BB,BEL,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,111.33,0,2
HB-096757,City Hotel,0,64,2024,September,36,4,2024-09-04,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,103.95,0,1
HB-092976,City Hotel,0,106,2024,July,28,11,2024-07-11,1,3,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.95,0,2
HB-104491,City Hotel,0,10,2025,January,2,12,2025-01-12,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,103.17,0,1
HB-020869,Resort Hotel,0,0,2024,February,6,11,2024-02-11,0,1,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,55.0,0,0
HB-055330,City Hotel,1,398,2024,August,32,11,2024-08-11,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,59.0,0,0
HB-066631,City Hotel,1,152,2025,April,17,22,2025-04-22,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,0,Transient,105.0,0,0
HB-113908,City Hotel,0,70,2025,June,24,13,2025-06-13,0,1,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,100.8,0,2
HB-063551,City Hotel,1,217,2025,February,7,13,2025-02-13,7,18,2,0.0,0,BB,ARE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.0,0,0
HB-001466,Resort Hotel,0,35,2023,August,35,31,2023-08-31,1,1,3,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,128.0,1,1
HB-062392,City Hotel,1,19,2025,January,2,12,2025-01-12,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,82.88,0,0
HB-083003,City Hotel,0,0,2024,January,1,7,2024-01-07,2,3,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,81.0,0,0
HB-117736,City Hotel,0,209,2025,August,32,6,2025-08-06,2,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,130.5,0,1
HB-036116,Resort Hotel,0,10,2025,May,19,6,2025-05-06,2,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,94.8,0,1
HB-010114,Resort Hotel,1,179,2025,February,7,13,2025-02-13,1,1,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,66.6,0,1
HB-044426,City Hotel,1,97,2023,October,40,5,2023-10-05,1,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,140.0,0,0
HB-055921,City Hotel,1,100,2024,August,34,24,2024-08-24,0,4,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,150.3,0,0
HB-051408,City Hotel,1,322,2024,May,20,19,2024-05-19,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,120,Transient,80.0,0,0
HB-080222,City Hotel,0,44,2023,November,45,11,2023-11-11,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Group,60.0,0,1
HB-090342,City Hotel,0,126,2024,June,22,2,2024-06-02,0,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient-Party,80.75,0,1
HB-089892,City Hotel,0,128,2024,May,22,27,2024-05-27,0,2,2,2.0,0,BB,DEU,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,207.9,0,2
HB-010799,Resort Hotel,1,205,2025,April,14,5,2025-04-05,0,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,81.0,0,1
HB-036544,Resort Hotel,0,11,2025,May,21,23,2025-05-23,0,1,1,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,58.0,1,1
HB-072935,City Hotel,1,184,2025,August,32,10,2025-08-10,0,3,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,164.7,0,0
HB-076888,City Hotel,0,181,2023,August,33,17,2023-08-17,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient-Party,76.5,0,2
HB-038031,Resort Hotel,0,244,2025,July,27,1,2025-07-01,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,99.0,0,2
HB-001218,Resort Hotel,0,91,2023,August,33,19,2023-08-19,0,4,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,C,1,No Deposit,240.0,,0,Transient,166.0,0,0
HB-077176,City Hotel,0,219,2023,September,36,4,2023-09-04,2,4,1,0.0,0,BB,SWE,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,3.0,,0,Transient-Party,78.33,0,0
HB-049381,City Hotel,1,47,2024,April,15,12,2024-04-12,0,1,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.9,0,0
HB-029578,Resort Hotel,0,159,2024,October,44,28,2024-10-28,1,2,2,0.0,0,BB,AUS,Direct,Direct,0,0,0,E,E,1,No Deposit,250.0,,0,Transient,71.2,0,0
HB-102622,City Hotel,0,235,2024,November,48,29,2024-11-29,0,4,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,73.95,0,1
HB-056865,City Hotel,1,317,2024,September,37,15,2024-09-15,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,120.0,0,0
HB-020872,Resort Hotel,0,22,2024,February,6,5,2024-02-05,2,6,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,27.35,0,0
HB-082005,City Hotel,1,115,2024,March,12,20,2024-03-20,2,0,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,41.0,,22,Transient,70.0,0,0
HB-051255,City Hotel,1,286,2024,May,20,17,2024-05-17,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,75,Transient,65.0,0,0
HB-047632,City Hotel,1,116,2024,February,9,28,2024-02-28,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,61.0,0,0
HB-060660,City Hotel,1,301,2024,November,47,18,2024-11-18,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,52.0,0,0
HB-117603,City Hotel,0,68,2025,August,32,5,2025-08-05,1,1,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,249.0,0,0
HB-099054,City Hotel,0,50,2024,December,50,13,2024-12-13,0,2,1,0.0,0,BB,SWE,Offline TA/TO,Direct,1,0,2,A,A,0,No Deposit,85.0,,0,Transient,67.5,0,1
HB-076081,City Hotel,1,364,2023,October,42,16,2023-10-16,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-095269,City Hotel,0,0,2024,August,33,16,2024-08-16,0,1,2,1.0,0,BB,FRA,Direct,Direct,0,0,0,A,F,0,No Deposit,14.0,,0,Transient,238.0,1,0
HB-099107,City Hotel,0,127,2024,October,40,3,2024-10-03,2,5,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,2
HB-023025,Resort Hotel,0,1,2024,April,15,12,2024-04-12,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,144.0,0,Transient-Party,48.0,1,0
HB-118689,City Hotel,0,95,2025,August,34,19,2025-08-19,2,3,1,0.0,0,BB,ARG,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,98.0,,0,Transient-Party,115.0,0,0
HB-107716,City Hotel,0,41,2025,March,11,13,2025-03-13,1,3,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,125.8,0,2
HB-103394,City Hotel,0,39,2024,December,51,19,2024-12-19,1,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,16.0,,0,Transient,102.0,0,0
HB-001195,Resort Hotel,1,93,2023,August,33,17,2023-08-17,3,5,2,0.0,1,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,134.0,0,2
HB-109775,City Hotel,0,98,2025,April,16,14,2025-04-14,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,90.1,0,0
HB-013667,Resort Hotel,1,253,2025,August,35,25,2025-08-25,2,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,153.75,0,1
HB-111193,City Hotel,0,19,2025,May,19,6,2025-05-06,1,1,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,150.0,0,4
HB-031970,Resort Hotel,0,6,2025,January,2,10,2025-01-10,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,C,0,No Deposit,181.0,,0,Transient-Party,34.0,0,1
HB-077713,City Hotel,0,2,2023,September,38,20,2023-09-20,2,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Contract,145.0,0,2
HB-074820,City Hotel,1,335,2023,September,37,17,2023-09-17,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,5.0,,0,Transient,75.0,0,0
HB-069584,City Hotel,1,189,2025,June,23,2,2025-06-02,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-045679,City Hotel,0,140,2023,November,46,18,2023-11-18,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,29.0,,87,Transient-Party,65.0,0,0
HB-029469,Resort Hotel,0,10,2024,October,43,26,2024-10-26,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,75.0,0,1
HB-047594,City Hotel,1,53,2024,February,9,28,2024-02-28,2,0,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,96.3,0,1
HB-012296,Resort Hotel,1,336,2025,June,25,22,2025-06-22,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,88.2,0,1
HB-042903,City Hotel,1,18,2023,September,37,11,2023-09-11,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Contract,116.75,0,1
HB-013992,Resort Hotel,0,0,2023,August,31,1,2023-08-01,0,1,2,0.0,0,BB,,Direct,Direct,0,0,1,G,G,0,No Deposit,,,0,Transient,200.0,1,1
HB-014200,Resort Hotel,0,8,2025,February,6,7,2025-02-07,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,3,A,E,0,No Deposit,,113.0,0,Transient,35.0,0,0
HB-087795,City Hotel,0,0,2024,April,17,23,2024-04-23,2,1,2,0.0,0,BB,HUN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,71.0,0,0
HB-000980,Resort Hotel,0,136,2023,August,32,8,2023-08-08,2,5,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,156.0,,0,Contract,90.95,0,1
HB-043110,City Hotel,1,54,2023,September,37,15,2023-09-15,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,85.5,0,2
HB-016538,Resort Hotel,0,1,2023,August,35,29,2023-08-29,2,2,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,134.0,1,3
HB-115070,City Hotel,0,200,2025,June,26,29,2025-06-29,0,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,1
HB-071491,City Hotel,1,78,2025,July,27,6,2025-07-06,0,3,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,1
HB-030801,Resort Hotel,0,80,2024,December,49,2,2024-12-02,0,2,1,0.0,0,BB,IRL,Groups,TA/TO,0,0,0,D,D,3,No Deposit,253.0,,0,Transient-Party,44.8,0,0
HB-050997,City Hotel,1,59,2024,May,20,13,2024-05-13,0,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.9,0,0
HB-091700,City Hotel,0,265,2024,June,26,24,2024-06-24,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-052874,City Hotel,1,71,2024,June,24,14,2024-06-14,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,120.0,0,0
HB-104687,City Hotel,0,0,2025,June,25,22,2025-06-22,0,1,1,0.0,0,BB,BEL,Aviation,Corporate,1,0,1,A,D,0,No Deposit,,153.0,0,Transient,95.0,0,0
HB-035942,Resort Hotel,0,81,2025,April,18,29,2025-04-29,2,5,2,0.0,0,BB,IDN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,143.0,,0,Transient,40.95,0,0
HB-053811,City Hotel,1,358,2024,June,26,30,2024-06-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-105786,City Hotel,0,63,2025,February,7,13,2025-02-13,1,1,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,140.4,0,2
HB-050841,City Hotel,0,126,2024,May,19,9,2024-05-09,1,5,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,111.35,0,1
HB-081939,City Hotel,1,278,2024,August,32,11,2024-08-11,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,65.0,0,0
HB-069237,City Hotel,1,79,2025,May,22,28,2025-05-28,2,1,1,0.0,0,BB,MAC,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,140.0,0,0
HB-053159,City Hotel,1,77,2024,June,24,16,2024-06-16,0,3,1,0.0,0,SC,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.1,0,0
HB-021738,Resort Hotel,0,1,2025,February,7,16,2025-02-16,0,1,1,0.0,0,HB,PRT,Complementary,Direct,1,0,1,G,G,1,No Deposit,,,0,Transient,0.0,1,2
HB-044285,City Hotel,0,198,2023,October,40,3,2023-10-03,1,1,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,60.0,0,0
HB-036421,Resort Hotel,0,8,2025,May,20,17,2025-05-17,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,H,0,No Deposit,240.0,,0,Transient,85.0,0,1
HB-018496,Resort Hotel,1,1,2023,November,47,21,2023-11-21,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,1,No Deposit,,,0,Transient,78.0,0,1
HB-076310,City Hotel,0,264,2023,July,27,8,2023-07-08,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-040478,City Hotel,1,27,2023,July,30,27,2023-07-27,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-115898,City Hotel,0,19,2025,July,28,9,2025-07-09,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,150.0,0,2
HB-058882,City Hotel,1,48,2024,October,42,17,2024-10-17,1,2,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,1
HB-063327,City Hotel,1,0,2025,February,6,9,2025-02-09,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,12.0,0,0
HB-026822,Resort Hotel,0,37,2024,August,32,8,2024-08-08,1,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,216.0,0,1
HB-098428,City Hotel,0,33,2024,September,39,28,2024-09-28,0,2,1,0.0,0,BB,PRT,Complementary,TA/TO,0,0,0,A,E,0,No Deposit,,,0,Transient-Party,65.0,0,0
HB-110794,City Hotel,0,26,2025,April,18,29,2025-04-29,2,1,2,0.0,0,SC,BGR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,133.0,0,0
HB-087607,City Hotel,0,5,2024,April,16,20,2024-04-20,0,3,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,126.0,0,1
HB-117489,City Hotel,0,160,2025,July,30,26,2025-07-26,2,8,1,2.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,22.0,,0,Transient,109.65,0,0
HB-088221,City Hotel,0,4,2024,May,18,2,2024-05-02,1,0,2,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,95.0,0,0
HB-028557,Resort Hotel,0,2,2024,October,40,4,2024-10-04,0,2,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,H,0,No Deposit,250.0,,0,Transient,96.0,1,0
HB-016927,Resort Hotel,0,97,2023,September,37,11,2023-09-11,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Transient,63.21,0,0
HB-068971,City Hotel,1,68,2025,May,21,24,2025-05-24,0,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,171.0,0,0
HB-095208,City Hotel,0,12,2024,August,33,15,2024-08-15,1,0,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,159.0,0,0
HB-015477,Resort Hotel,0,17,2023,July,28,16,2023-07-16,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,139.75,1,1
HB-011137,Resort Hotel,1,15,2025,April,17,22,2025-04-22,2,5,2,2.0,0,BB,NOR,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,165.71,0,0
HB-108998,City Hotel,0,111,2025,April,14,3,2025-04-03,1,1,2,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,95.0,0,1
HB-090221,City Hotel,0,91,2024,June,22,1,2024-06-01,0,3,3,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,B,0,No Deposit,22.0,,0,Transient,105.4,0,1
HB-029348,Resort Hotel,0,63,2024,October,43,23,2024-10-23,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,241.0,,0,Transient,42.43,0,1
HB-034490,Resort Hotel,0,65,2025,March,12,18,2025-03-18,2,6,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,468.0,,0,Transient-Party,82.0,0,0
HB-054152,City Hotel,1,128,2024,July,27,7,2024-07-07,0,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,103.5,0,0
HB-095402,City Hotel,0,169,2024,August,33,14,2024-08-14,2,3,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,4,No Deposit,9.0,,0,Transient,134.52,1,2
HB-098845,City Hotel,0,12,2024,October,40,2,2024-10-02,2,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-012151,Resort Hotel,1,223,2025,June,24,15,2025-06-15,2,7,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,170.0,0,0
HB-064981,City Hotel,1,56,2025,March,12,21,2025-03-21,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,86.0,,0,Transient,85.0,0,0
HB-027949,Resort Hotel,0,8,2024,September,37,13,2024-09-13,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,124.0,0,1
HB-087272,City Hotel,0,12,2024,April,16,15,2024-04-15,0,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,127.0,0,1
HB-098800,City Hotel,0,18,2024,October,40,3,2024-10-03,1,1,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-008907,Resort Hotel,0,385,2024,October,42,19,2024-10-19,1,4,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,49.0,0,0
HB-019391,Resort Hotel,0,7,2023,December,50,16,2023-12-16,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,F,1,No Deposit,,,0,Transient,38.0,0,3
HB-113422,City Hotel,0,155,2025,June,23,5,2025-06-05,1,1,2,2.0,0,BB,DEU,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,225.0,1,2
HB-050211,City Hotel,1,65,2024,April,17,26,2024-04-26,0,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.9,0,0
HB-017687,Resort Hotel,0,287,2023,October,41,15,2023-10-15,1,3,1,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,1,No Deposit,,223.0,0,Transient-Party,37.0,0,0
HB-086652,City Hotel,0,55,2024,April,14,6,2024-04-06,0,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,104.0,0,0
HB-105816,City Hotel,0,20,2025,February,7,14,2025-02-14,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,219.0,0,Transient,89.0,1,2
HB-046505,City Hotel,1,145,2024,January,1,3,2024-01-03,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,85,Transient,65.0,0,0
HB-050395,City Hotel,1,115,2024,April,18,29,2024-04-29,2,3,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,104.55,0,1
HB-016648,Resort Hotel,0,205,2023,September,36,4,2023-09-04,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,C,1,No Deposit,,,0,Transient-Party,74.5,0,1
HB-118650,City Hotel,0,0,2025,August,34,23,2025-08-23,0,1,1,0.0,0,BB,USA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,98.0,,0,Transient-Party,115.0,0,0
HB-113862,City Hotel,0,19,2025,June,24,11,2025-06-11,2,0,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,9.0,,0,Transient,109.0,0,1
HB-061534,City Hotel,1,78,2024,December,51,16,2024-12-16,0,2,2,1.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,120.49,0,0
HB-049771,City Hotel,1,103,2024,April,16,19,2024-04-19,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,0,Transient,115.0,0,0
HB-024655,Resort Hotel,0,44,2024,May,22,27,2024-05-27,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,90.0,0,0
HB-082646,City Hotel,0,56,2023,December,52,30,2023-12-30,1,4,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Contract,105.75,0,2
HB-027016,Resort Hotel,0,108,2024,August,33,12,2024-08-12,2,3,2,0.0,1,FB,ESP,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,5.0,,0,Transient,222.0,0,1
HB-026155,Resort Hotel,0,129,2024,July,29,16,2024-07-16,2,5,3,0.0,0,BB,DNK,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,253.0,,0,Transient,161.6,0,0
HB-004754,Resort Hotel,0,169,2024,March,13,31,2024-03-31,0,3,2,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,A,2,Refundable,,223.0,0,Transient-Party,72.0,1,0
HB-117098,City Hotel,0,159,2025,July,31,29,2025-07-29,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,139.5,1,0
HB-071242,City Hotel,1,135,2025,June,27,30,2025-06-30,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,30.0,,0,Transient,130.0,0,0
HB-086882,City Hotel,0,134,2024,April,15,9,2024-04-09,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,90.0,0,1
HB-117830,City Hotel,0,203,2025,July,31,31,2025-07-31,3,7,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,170.0,0,1
HB-033627,Resort Hotel,0,14,2025,February,9,25,2025-02-25,2,1,2,0.0,0,HB,ESP,Direct,Direct,0,0,0,F,F,1,No Deposit,250.0,,0,Transient,109.0,0,1
HB-114642,City Hotel,0,6,2025,June,26,23,2025-06-23,0,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,169.0,0,2
HB-051013,City Hotel,1,273,2024,May,20,13,2024-05-13,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,95.0,0,0
HB-109668,City Hotel,0,98,2025,April,15,9,2025-04-09,2,4,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,156.0,0,0
HB-024096,Resort Hotel,0,48,2024,May,19,11,2024-05-11,0,1,2,0.0,0,HB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,95.0,1,0
HB-021463,Resort Hotel,0,9,2024,February,9,27,2024-02-27,1,1,2,1.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient,68.75,0,1
HB-041911,City Hotel,0,55,2023,August,34,26,2023-08-26,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-068041,City Hotel,1,183,2025,May,19,11,2025-05-11,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,0,Transient,130.0,0,0
HB-033009,Resort Hotel,0,1,2025,February,7,10,2025-02-10,0,2,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,34.0,0,0
HB-115257,City Hotel,0,158,2025,June,26,29,2025-06-29,2,3,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,165.06,0,0
HB-059768,City Hotel,1,166,2024,November,44,1,2024-11-01,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,110.0,0,0
HB-016057,Resort Hotel,0,70,2023,August,32,10,2023-08-10,1,2,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,D,F,1,No Deposit,250.0,,0,Transient,166.0,1,0
HB-022472,Resort Hotel,0,62,2024,March,12,18,2024-03-18,2,7,2,0.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,171.0,,0,Transient,78.0,1,0
HB-108300,City Hotel,0,116,2025,March,13,24,2025-03-24,0,2,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,171.0,,0,Transient-Party,100.0,0,1
HB-117285,City Hotel,0,8,2025,August,31,1,2025-08-01,0,1,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.0,0,1
HB-103927,City Hotel,0,0,2025,January,1,2,2025-01-02,0,0,2,1.0,0,BB,PRT,Online TA,TA/TO,1,0,0,A,K,0,No Deposit,9.0,,0,Transient,0.0,0,2
HB-093255,City Hotel,0,135,2024,July,29,17,2024-07-17,2,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,8.0,,0,Transient,127.8,0,2
HB-016358,Resort Hotel,0,58,2023,August,33,19,2023-08-19,2,5,3,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,181.0,,0,Transient,161.71,0,0
HB-055726,City Hotel,1,303,2024,August,34,19,2024-08-19,2,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,78.0,0,0
HB-086231,City Hotel,0,122,2024,March,13,27,2024-03-27,2,1,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,26.0,,0,Transient-Party,86.0,0,0
HB-027433,Resort Hotel,0,1,2024,August,35,27,2024-08-27,1,1,2,0.0,0,BB,EGY,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,306.0,,0,Transient,122.89,0,0
HB-025256,Resort Hotel,0,16,2024,June,24,16,2024-06-16,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,241.0,,0,Transient,96.36,0,1
HB-061069,City Hotel,1,290,2024,December,48,1,2024-12-01,1,3,2,0.0,0,BB,SVK,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,86.7,0,0
HB-061181,City Hotel,1,72,2024,December,49,3,2024-12-03,2,1,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.8,0,2
HB-059764,City Hotel,1,166,2024,November,44,1,2024-11-01,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,110.0,0,0
HB-050799,City Hotel,1,32,2024,May,19,8,2024-05-08,2,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.9,0,0
HB-022561,Resort Hotel,0,12,2024,March,13,27,2024-03-27,2,0,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,55.0,1,1
HB-065061,City Hotel,1,79,2025,March,12,23,2025-03-23,0,3,2,0.0,0,BB,HUN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,106.2,0,0
HB-079576,City Hotel,0,6,2023,October,43,29,2023-10-29,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,98.0,,0,Transient-Party,130.0,0,0
HB-095656,City Hotel,0,73,2024,August,34,21,2024-08-21,1,0,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,7.0,,0,Transient,205.38,0,2
HB-032832,Resort Hotel,0,159,2025,February,6,4,2025-02-04,2,1,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,37.8,0,3
HB-055606,City Hotel,1,128,2024,August,33,17,2024-08-17,1,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,122.4,0,0
HB-063934,City Hotel,1,134,2025,February,9,25,2025-02-25,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,75.0,0,0
HB-084715,City Hotel,0,8,2024,March,9,2,2024-03-02,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,86.0,0,0
HB-090049,City Hotel,0,104,2024,May,22,29,2024-05-29,2,1,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient-Party,125.1,0,1
HB-042923,City Hotel,0,168,2023,September,37,11,2023-09-11,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,B,1,No Deposit,1.0,,0,Transient-Party,50.0,0,0
HB-063770,City Hotel,1,26,2025,February,8,20,2025-02-20,1,2,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.0,0,0
HB-102091,City Hotel,0,53,2024,November,47,19,2024-11-19,2,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,1
HB-115781,City Hotel,0,28,2025,July,28,9,2025-07-09,2,0,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,149.0,0,1
HB-082234,City Hotel,1,203,2024,June,22,2,2024-06-02,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,41,Transient,65.0,0,0
HB-058410,City Hotel,1,279,2024,October,41,12,2024-10-12,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,98.0,,0,Transient,110.0,0,0
HB-040691,City Hotel,0,12,2023,August,31,5,2023-08-05,0,3,2,0.0,0,BB,RUS,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,38.0,0,Transient-Party,65.0,0,0
HB-053547,City Hotel,1,81,2024,June,25,23,2024-06-23,0,1,1,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.9,0,0
HB-073469,City Hotel,1,33,2025,August,34,23,2025-08-23,0,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,129.5,0,1
HB-067383,City Hotel,1,82,2025,May,18,3,2025-05-03,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,130.0,0,0
HB-115315,City Hotel,0,8,2025,July,27,3,2025-07-03,1,0,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,190.0,0,1
HB-022088,Resort Hotel,0,36,2024,March,10,10,2024-03-10,2,6,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,0
HB-088464,City Hotel,0,104,2024,May,18,4,2024-05-04,0,3,1,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient-Party,110.1,0,0
HB-032058,Resort Hotel,0,10,2025,January,3,14,2025-01-14,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,55.0,1,1
HB-078602,City Hotel,0,221,2023,October,41,10,2023-10-10,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,65.0,0,0
HB-005029,Resort Hotel,1,168,2024,April,15,12,2024-04-12,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,245.0,,0,Transient,86.0,0,0
HB-106685,City Hotel,0,127,2025,February,9,26,2025-02-26,2,1,3,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,138.6,0,1
HB-115495,City Hotel,0,34,2025,July,27,5,2025-07-05,0,2,1,0.0,0,BB,AUT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,115.0,0,0
HB-091784,City Hotel,0,265,2024,June,26,24,2024-06-24,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-064938,City Hotel,1,195,2025,March,12,21,2025-03-21,0,3,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,2
HB-070331,City Hotel,1,320,2025,June,24,15,2025-06-15,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient,90.0,0,0
HB-028482,Resort Hotel,0,0,2024,October,40,5,2024-10-05,0,1,3,0.0,0,BB,ESP,Direct,Direct,1,0,0,D,D,0,No Deposit,,,0,Transient,141.0,1,0
HB-019058,Resort Hotel,0,0,2023,December,49,5,2023-12-05,2,1,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,348.0,,0,Transient-Party,51.67,0,0
HB-046048,City Hotel,0,135,2023,December,49,5,2023-12-05,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-086084,City Hotel,0,126,2024,March,12,24,2024-03-24,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,28.0,,0,Transient,55.0,0,0
HB-045132,City Hotel,0,184,2023,October,42,17,2023-10-17,2,6,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,B,A,0,No Deposit,7.0,,0,Transient-Party,65.29,0,1
HB-083431,City Hotel,0,20,2024,January,5,29,2024-01-29,1,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,99.0,0,1
HB-039019,Resort Hotel,0,201,2025,July,31,30,2025-07-30,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Transient,104.85,0,1
HB-044576,City Hotel,0,210,2023,October,40,8,2023-10-08,1,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,12.0,,0,Transient-Party,72.75,0,0
HB-051449,City Hotel,1,211,2024,May,21,20,2024-05-20,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,111,Transient,100.0,0,0
HB-111033,City Hotel,0,50,2025,May,18,1,2025-05-01,1,3,2,0.0,0,SC,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,1
HB-070387,City Hotel,1,123,2025,June,25,16,2025-06-16,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,153.0,0,0
HB-102837,City Hotel,0,50,2024,December,49,3,2024-12-03,2,2,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,22.0,,0,Transient,63.75,0,0
HB-002049,Resort Hotel,0,54,2023,September,39,29,2023-09-29,2,5,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,171.0,,0,Transient,56.59,0,0
HB-100160,City Hotel,0,84,2024,October,43,21,2024-10-21,1,2,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,80.75,0,2
HB-011563,Resort Hotel,1,81,2025,May,20,17,2025-05-17,0,4,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,160.0,0,1
HB-093804,City Hotel,0,118,2024,July,30,24,2024-07-24,2,1,2,2.0,0,BB,AUT,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,165.9,0,1
HB-118441,City Hotel,0,177,2025,August,33,16,2025-08-16,0,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,354.0,,0,Transient,121.77,0,0
HB-048698,City Hotel,1,44,2024,March,13,27,2024-03-27,2,3,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,135.22,0,1
HB-047587,City Hotel,1,1,2024,February,9,28,2024-02-28,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,60.0,0,0
HB-086290,City Hotel,0,0,2024,March,13,30,2024-03-30,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,73.0,0,0
HB-050483,City Hotel,1,437,2024,May,18,2,2024-05-02,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-093355,City Hotel,0,51,2024,July,29,18,2024-07-18,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,132.9,0,1
HB-031366,Resort Hotel,0,71,2024,December,52,23,2024-12-23,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,46.0,0,2
HB-003983,Resort Hotel,1,64,2024,February,6,11,2024-02-11,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,15.0,,0,Transient,29.0,0,0
HB-069224,City Hotel,1,102,2025,May,22,27,2025-05-27,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,85.0,,0,Transient,119.52,0,0
HB-078883,City Hotel,0,23,2023,October,42,16,2023-10-16,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,15.0,,0,Transient,98.4,0,2
HB-047094,City Hotel,1,4,2024,February,6,6,2024-02-06,2,4,2,0.0,0,SC,SEN,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,81.0,0,0
HB-104923,City Hotel,0,3,2025,January,4,24,2025-01-24,0,1,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,0
HB-020769,Resort Hotel,0,1,2024,February,6,7,2024-02-07,2,0,2,2.0,0,BB,PRT,Direct,Direct,0,0,0,H,H,0,No Deposit,,,0,Transient,98.0,1,0
HB-055665,City Hotel,1,143,2024,August,33,18,2024-08-18,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,140.7,0,0
HB-112143,City Hotel,0,90,2025,May,20,18,2025-05-18,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.0,0,2
HB-055734,City Hotel,1,303,2024,August,34,19,2024-08-19,2,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,78.0,0,0
HB-096545,City Hotel,0,40,2024,August,35,31,2024-08-31,0,4,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,168.0,,0,Transient,85.5,0,0
HB-073186,City Hotel,1,316,2025,August,33,16,2025-08-16,0,3,0,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient,104.05,0,3
HB-065343,City Hotel,1,125,2025,March,14,31,2025-03-31,2,2,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,91.44,0,1
HB-071560,City Hotel,1,133,2025,July,28,7,2025-07-07,0,2,2,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,141.3,0,1
HB-099182,City Hotel,0,7,2024,October,41,7,2024-10-07,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,205.0,0,2
HB-039898,Resort Hotel,0,28,2025,August,35,28,2025-08-28,1,2,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient-Party,262.0,0,2
HB-051388,City Hotel,1,28,2024,May,20,19,2024-05-19,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,174.0,0,Transient-Party,95.0,0,0
HB-053944,City Hotel,1,156,2024,July,27,2,2024-07-02,2,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,93.08,0,1
HB-111359,City Hotel,0,8,2025,July,30,25,2025-07-25,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,6,A,A,0,No Deposit,,238.0,0,Transient,65.0,1,0
HB-081946,City Hotel,1,272,2024,August,32,5,2024-08-05,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,41,Transient,65.0,0,0
HB-006765,Resort Hotel,1,164,2024,June,26,30,2024-06-30,4,10,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,243.0,,0,Contract,64.85,0,1
HB-112149,City Hotel,0,68,2025,May,20,17,2025-05-17,0,4,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,144.0,0,0
HB-022712,Resort Hotel,0,80,2024,April,14,3,2024-04-03,1,0,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,52.2,0,1
HB-085580,City Hotel,0,51,2024,March,11,15,2024-03-15,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.9,1,1
HB-057229,City Hotel,1,440,2024,September,38,22,2024-09-22,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-088194,City Hotel,0,4,2024,May,18,1,2024-05-01,1,0,1,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.0,0,1
HB-033549,Resort Hotel,0,70,2025,February,8,22,2025-02-22,0,4,3,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,C,2,No Deposit,,405.0,0,Transient-Party,58.0,1,0
HB-103547,City Hotel,0,11,2024,December,52,27,2024-12-27,0,1,2,2.0,0,BB,USA,Direct,Direct,0,0,0,F,F,1,No Deposit,,,0,Transient,209.0,0,0
HB-058888,City Hotel,1,605,2024,October,42,17,2024-10-17,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-069479,City Hotel,1,174,2025,June,22,1,2025-06-01,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,0,Transient,100.0,0,0
HB-067297,City Hotel,1,46,2025,May,18,1,2025-05-01,1,3,1,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,128.79,0,0
HB-047987,City Hotel,1,38,2024,March,11,11,2024-03-11,1,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,1
HB-007405,Resort Hotel,1,139,2024,August,32,7,2024-08-07,3,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,211.0,0,0
HB-053426,City Hotel,1,193,2024,June,25,20,2024-06-20,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,162.0,,39,Transient,120.0,0,0
HB-059679,City Hotel,1,36,2024,October,44,31,2024-10-31,1,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,95.0,0,0
HB-057435,City Hotel,0,418,2024,September,39,26,2024-09-26,1,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,132.0,,223,Transient-Party,107.0,0,0
HB-047903,City Hotel,1,43,2024,March,10,8,2024-03-08,1,5,1,0.0,0,BB,CPV,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,68.47,0,0
HB-033925,Resort Hotel,0,71,2025,January,2,10,2025-01-10,16,40,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,196.0,,0,Transient,28.79,0,0
HB-110421,City Hotel,0,108,2025,April,17,24,2025-04-24,1,2,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,108.0,0,1
HB-031943,Resort Hotel,0,11,2025,February,8,21,2025-02-21,2,5,2,0.0,0,BB,PRT,Direct,Direct,1,0,1,A,A,0,No Deposit,,,0,Transient,45.0,0,1
HB-086746,City Hotel,0,119,2024,April,14,4,2024-04-04,1,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient-Party,71.0,0,1
HB-103422,City Hotel,0,1,2024,December,51,20,2024-12-20,0,3,1,0.0,0,BB,HUN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.5,0,1
HB-039490,Resort Hotel,0,215,2025,August,33,13,2025-08-13,2,4,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,E,F,1,No Deposit,250.0,,0,Transient,203.19,1,1
HB-012666,Resort Hotel,1,3,2025,July,28,11,2025-07-11,0,1,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,145.0,0,1
HB-110549,City Hotel,0,116,2025,April,17,25,2025-04-25,0,4,2,1.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,121.5,0,1
HB-008305,Resort Hotel,0,397,2024,September,38,21,2024-09-21,0,4,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,96.0,,0,Transient-Party,70.5,0,1
HB-081670,City Hotel,1,182,2024,April,17,27,2024-04-27,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,3.0,,50,Transient,75.0,0,0
HB-033692,Resort Hotel,0,11,2025,February,9,28,2025-02-28,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,38.0,0,1
HB-028367,Resort Hotel,0,58,2024,September,39,25,2024-09-25,2,4,2,0.0,0,BB,NLD,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,110.0,0,2
HB-087536,City Hotel,0,0,2024,June,23,7,2024-06-07,0,1,1,0.0,0,SC,FRA,Online TA,TA/TO,1,0,1,A,A,0,No Deposit,9.0,,0,Group,109.0,0,1
HB-075383,City Hotel,1,313,2023,August,34,26,2023-08-26,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-090507,City Hotel,0,247,2024,June,23,6,2024-06-06,1,1,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,90.0,0,0
HB-056492,City Hotel,1,23,2024,September,36,8,2024-09-08,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.0,0,0
HB-024335,Resort Hotel,0,11,2024,May,20,16,2024-05-16,1,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,2,No Deposit,,178.0,0,Transient,42.0,0,0
HB-103429,City Hotel,0,127,2024,December,51,22,2024-12-22,0,2,2,0.0,0,BB,IND,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.0,0,3
HB-030443,Resort Hotel,0,1,2024,November,47,21,2024-11-21,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,60.0,0,1
HB-016841,Resort Hotel,0,180,2023,September,36,5,2023-09-05,4,6,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,71.55,0,0
HB-044332,City Hotel,1,89,2023,October,40,3,2023-10-03,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-017506,Resort Hotel,0,18,2023,October,41,12,2023-10-12,1,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,146.0,,0,Transient-Party,40.0,1,0
HB-005008,Resort Hotel,1,168,2024,April,15,12,2024-04-12,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,245.0,,0,Transient,86.0,0,0
HB-102792,City Hotel,0,105,2024,December,48,1,2024-12-01,2,3,3,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,116.8,0,2
HB-006276,Resort Hotel,1,7,2024,June,22,1,2024-06-01,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,83.0,0,Transient,57.0,0,0
HB-058746,City Hotel,1,41,2024,October,42,15,2024-10-15,2,1,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,145.2,0,2
HB-056250,City Hotel,1,37,2024,September,36,2,2024-09-02,0,1,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,1
HB-065964,City Hotel,1,217,2025,April,15,11,2025-04-11,0,3,2,1.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,133.2,0,1
HB-054705,City Hotel,0,206,2024,July,30,23,2024-07-23,14,34,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,K,6,No Deposit,9.0,,0,Transient-Party,0.0,0,1
HB-089680,City Hotel,0,34,2024,May,21,22,2024-05-22,2,1,1,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,98.1,0,1
HB-063504,City Hotel,1,70,2025,February,7,12,2025-02-12,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.4,0,1
HB-028348,Resort Hotel,0,137,2024,September,39,28,2024-09-28,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,F,0,No Deposit,240.0,,0,Transient,122.0,1,2
HB-055922,City Hotel,1,94,2024,August,34,24,2024-08-24,0,4,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,131.4,0,0
HB-088602,City Hotel,0,1,2024,May,19,8,2024-05-08,1,0,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,152.0,,0,Transient,56.47,0,0
HB-075786,City Hotel,1,323,2023,September,36,5,2023-09-05,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-051643,City Hotel,1,48,2024,May,21,23,2024-05-23,1,3,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,150.45,0,0
HB-065643,City Hotel,1,93,2025,April,14,6,2025-04-06,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,170.0,,0,Transient,85.0,0,0
HB-037794,Resort Hotel,0,251,2025,June,26,26,2025-06-26,1,3,2,0.0,0,HB,CN,Groups,TA/TO,0,0,0,D,F,0,No Deposit,96.0,,0,Transient-Party,108.0,0,1
HB-093886,City Hotel,0,159,2024,July,30,23,2024-07-23,2,3,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.05,0,2
HB-052912,City Hotel,1,11,2024,June,24,14,2024-06-14,0,3,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,D,D,0,Non Refund,,51.0,0,Transient,90.0,0,0
HB-071977,City Hotel,1,138,2025,July,29,16,2025-07-16,2,3,2,0.0,0,BB,ITA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,108.0,0,0
HB-022147,Resort Hotel,0,52,2024,March,11,13,2024-03-13,2,4,3,1.0,0,BB,CN,Online TA,TA/TO,0,0,0,H,H,1,No Deposit,240.0,,0,Transient,102.0,0,0
HB-054626,City Hotel,0,208,2024,July,29,21,2024-07-21,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient,104.62,1,0
HB-042511,City Hotel,0,55,2023,September,36,6,2023-09-06,2,0,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,B,0,No Deposit,1.0,,0,Transient-Party,75.0,0,0
HB-096168,City Hotel,0,216,2024,August,35,27,2024-08-27,2,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,96.3,0,2
HB-026831,Resort Hotel,0,2,2024,August,32,9,2024-08-09,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,F,0,No Deposit,240.0,,0,Transient,197.67,0,0
HB-054170,City Hotel,1,166,2024,July,27,7,2024-07-07,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,96.79,0,1
HB-116634,City Hotel,0,160,2025,July,29,20,2025-07-20,0,3,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,D,D,1,No Deposit,14.0,,0,Transient,119.4,0,0
HB-022324,Resort Hotel,0,25,2024,March,12,19,2024-03-19,2,2,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,115.0,,0,Transient,33.3,0,0
HB-046683,City Hotel,0,12,2024,January,3,15,2024-01-15,1,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.0,0,1
HB-097079,City Hotel,0,6,2024,September,36,8,2024-09-08,1,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,161.5,0,2
HB-038386,Resort Hotel,0,145,2025,July,28,12,2025-07-12,0,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,125.44,0,1
HB-098784,City Hotel,0,5,2024,October,40,4,2024-10-04,0,1,2,0.0,0,BB,AUT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,83.0,0,1
HB-073049,City Hotel,1,20,2025,August,33,13,2025-08-13,2,0,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,1
HB-063249,City Hotel,1,23,2025,February,6,3,2025-02-03,0,2,1,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,0
HB-082400,City Hotel,1,302,2024,October,40,6,2024-10-06,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,3.0,,0,Transient,105.0,0,0
HB-097838,City Hotel,0,39,2024,September,38,18,2024-09-18,2,1,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,125.1,0,0
HB-049961,City Hotel,1,43,2024,April,16,21,2024-04-21,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,168.0,,0,Transient,96.3,0,0
HB-108928,City Hotel,0,6,2025,April,14,3,2025-04-03,1,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,290.0,,0,Transient,119.0,0,0
HB-014911,Resort Hotel,0,192,2025,August,33,17,2025-08-17,2,8,3,0.0,0,HB,PRT,Direct,Direct,1,1,3,E,E,2,No Deposit,,,0,Transient,211.2,1,3
HB-045219,City Hotel,1,50,2023,October,43,24,2023-10-24,0,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,146.0,0,0
HB-073869,City Hotel,1,314,2023,August,34,27,2023-08-27,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-097944,City Hotel,0,2,2024,September,38,22,2024-09-22,0,1,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,7.0,,0,Transient,153.62,0,1
HB-062546,City Hotel,1,38,2025,January,3,14,2025-01-14,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,Non Refund,,67.0,0,Transient,75.0,0,0
HB-093892,City Hotel,0,17,2024,July,30,26,2024-07-26,0,2,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,9.0,,0,Transient,178.0,1,2
HB-080346,City Hotel,1,19,2023,December,49,5,2023-12-05,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,1,1,0,A,A,0,No Deposit,10.0,,0,Transient,69.0,0,0
HB-033134,Resort Hotel,0,6,2025,February,6,9,2025-02-09,2,5,2,0.0,0,Undefined,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,464.0,,0,Transient,66.0,0,0
HB-023336,Resort Hotel,0,96,2024,April,16,16,2024-04-16,2,5,2,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,52.2,0,0
HB-040570,City Hotel,1,117,2023,August,31,1,2023-08-01,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-054098,City Hotel,1,365,2024,July,27,7,2024-07-07,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,59.0,0,0
HB-061780,City Hotel,1,192,2024,December,52,26,2024-12-26,1,3,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,D,D,4,No Deposit,14.0,,0,Transient,93.39,0,0
HB-060408,City Hotel,1,10,2024,November,45,10,2024-11-10,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,120.0,0,0
HB-109899,City Hotel,0,65,2025,April,16,15,2025-04-15,2,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.5,0,0
HB-004464,Resort Hotel,1,31,2024,March,12,19,2024-03-19,2,3,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,43.0,0,2
HB-095978,City Hotel,0,207,2024,August,34,23,2024-08-23,0,4,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,99.45,0,1
HB-117182,City Hotel,0,16,2025,July,31,30,2025-07-30,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,178.0,0,2
HB-028244,Resort Hotel,0,1,2024,September,39,24,2024-09-24,1,1,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,149.5,0,1
HB-095050,City Hotel,0,93,2024,August,33,13,2024-08-13,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient,109.83,0,1
HB-000108,Resort Hotel,1,102,2023,July,27,4,2023-07-04,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,110.7,0,1
HB-037492,Resort Hotel,0,150,2025,June,24,13,2025-06-13,2,5,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,314.0,,0,Transient,126.2,0,0
HB-070307,City Hotel,1,201,2025,June,24,14,2025-06-14,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-027703,Resort Hotel,0,151,2024,September,36,4,2024-09-04,2,2,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,139.5,0,1
HB-102194,City Hotel,0,215,2024,November,47,21,2024-11-21,1,2,1,0.0,0,BB,CYP,Groups,Corporate,0,0,0,A,A,1,No Deposit,,233.0,0,Transient,75.0,0,0
HB-008902,Resort Hotel,1,23,2024,October,42,19,2024-10-19,0,3,2,0.0,0,BB,ZAF,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,60.0,0,1
HB-009479,Resort Hotel,1,183,2024,December,49,3,2024-12-03,2,1,2,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,38.0,,0,Transient,72.0,0,0
HB-016056,Resort Hotel,0,107,2023,August,32,10,2023-08-10,1,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,134.0,0,1
HB-105292,City Hotel,0,12,2025,January,5,30,2025-01-30,1,5,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,105.0,0,0
HB-067953,City Hotel,1,35,2025,May,19,10,2025-05-10,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,39.0,,0,Transient-Party,130.0,0,0
HB-085915,City Hotel,0,15,2024,March,12,20,2024-03-20,2,2,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,160.0,1,1
HB-102710,City Hotel,0,36,2024,December,49,3,2024-12-03,1,1,2,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,0.0,0,0
HB-019121,Resort Hotel,0,0,2023,December,49,7,2023-12-07,1,0,2,0.0,0,BB,JPN,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,241.0,,0,Transient,75.46,1,2
HB-095117,City Hotel,0,86,2024,August,33,12,2024-08-12,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.9,0,0
HB-077833,City Hotel,0,6,2023,October,41,12,2023-10-12,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-102895,City Hotel,0,8,2024,December,49,6,2024-12-06,0,2,1,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,72.38,0,1
HB-033064,Resort Hotel,0,18,2025,February,7,13,2025-02-13,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient-Party,58.0,0,1
HB-102509,City Hotel,0,38,2024,November,48,28,2024-11-28,1,1,2,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,0.0,0,1
HB-028963,Resort Hotel,0,68,2024,October,42,16,2024-10-16,1,0,2,0.0,0,BB,USA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient,54.0,1,0
HB-055587,City Hotel,1,184,2024,August,33,17,2024-08-17,0,1,2,1.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,A,5,No Deposit,9.0,,0,Transient-Party,164.25,0,2
HB-011218,Resort Hotel,1,100,2025,April,18,29,2025-04-29,2,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,D,D,0,No Deposit,385.0,,0,Transient-Party,85.0,0,0
HB-005834,Resort Hotel,1,211,2024,May,20,14,2024-05-14,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,86.0,0,0
HB-078191,City Hotel,0,0,2023,October,40,5,2023-10-05,1,0,1,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,96.0,0,0
HB-098342,City Hotel,0,0,2024,September,39,27,2024-09-27,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,1,No Deposit,174.0,,0,Transient-Party,160.0,0,0
HB-027398,Resort Hotel,0,104,2024,August,34,23,2024-08-23,0,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,146.75,1,1
HB-060010,City Hotel,1,305,2024,November,45,4,2024-11-04,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,89.0,0,0
HB-115774,City Hotel,0,0,2025,July,28,10,2025-07-10,1,0,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,9.0,,0,Transient,140.0,0,2
HB-047446,City Hotel,0,48,2024,February,8,21,2024-02-21,2,5,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,65.75,0,0
HB-009796,Resort Hotel,1,20,2025,January,1,2,2025-01-02,1,5,2,1.0,1,BB,FRA,Online TA,TA/TO,0,0,0,G,G,1,No Deposit,240.0,,0,Transient,88.0,0,1
HB-084950,City Hotel,0,0,2024,March,10,6,2024-03-06,0,0,2,0.0,0,BB,PRT,Online TA,TA/TO,1,0,0,D,K,0,No Deposit,9.0,,0,Transient,0.0,0,0
HB-115057,City Hotel,0,6,2025,June,27,30,2025-06-30,0,1,2,0.0,0,SC,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,160.0,0,1
HB-051293,City Hotel,1,51,2024,May,20,17,2024-05-17,0,3,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,159.3,0,0
HB-073261,City Hotel,1,163,2025,August,33,17,2025-08-17,1,3,2,1.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,148.5,0,0
HB-006901,Resort Hotel,0,292,2024,July,28,10,2024-07-10,1,0,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,72.9,0,2
HB-030490,Resort Hotel,0,93,2024,November,47,18,2024-11-18,2,5,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,56.83,0,3
HB-097698,City Hotel,0,220,2024,September,38,17,2024-09-17,2,1,1,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,177.0,,0,Transient-Party,128.0,0,0
HB-024270,Resort Hotel,0,0,2024,October,40,5,2024-10-05,0,1,1,0.0,0,BB,GBR,Direct,TA/TO,1,0,2,E,E,0,No Deposit,,,0,Transient,95.0,1,0
HB-116026,City Hotel,0,184,2025,July,28,9,2025-07-09,2,3,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,89.1,0,1
HB-087390,City Hotel,0,29,2024,April,16,17,2024-04-17,2,0,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,95.95,0,1
HB-057479,City Hotel,0,418,2024,September,39,26,2024-09-26,1,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,132.0,,223,Transient-Party,107.0,0,0
HB-009983,Resort Hotel,1,85,2025,February,5,1,2025-02-01,0,4,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,72.0,0,1
HB-065019,City Hotel,1,48,2025,March,12,22,2025-03-22,0,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,0
HB-119384,City Hotel,0,164,2025,August,35,31,2025-08-31,2,4,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,42.0,,0,Transient,87.6,0,0
HB-088528,City Hotel,0,190,2024,May,18,5,2024-05-05,0,3,2,0.0,0,BB,CHE,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,95.4,0,1
HB-033437,Resort Hotel,0,3,2025,February,8,21,2025-02-21,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,68.0,0,2
HB-117734,City Hotel,0,190,2025,August,32,5,2025-08-05,2,2,2,1.0,0,BB,FRA,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,170.0,0,4
HB-027028,Resort Hotel,0,178,2024,August,32,8,2024-08-08,3,7,2,1.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,190.1,1,2
HB-107779,City Hotel,0,53,2025,March,11,15,2025-03-15,0,3,2,0.0,0,HB,DZA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,102.56,0,2
HB-013542,Resort Hotel,1,173,2025,August,34,19,2025-08-19,2,3,2,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,250.0,0,0
HB-035701,Resort Hotel,0,253,2025,April,17,23,2025-04-23,2,5,2,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,D,D,1,No Deposit,273.0,,0,Transient-Party,80.94,0,0
HB-022886,Resort Hotel,0,80,2024,April,14,7,2024-04-07,0,3,2,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,67.0,,0,Transient-Party,68.0,0,0
HB-069245,City Hotel,1,132,2025,May,22,28,2025-05-28,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,28.0,,0,Transient,99.0,0,0
HB-048699,City Hotel,1,120,2024,March,13,27,2024-03-27,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,8.0,,0,Transient,84.15,0,0
HB-085993,City Hotel,0,3,2024,March,12,21,2024-03-21,1,3,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,129.0,0,2
HB-085308,City Hotel,0,11,2024,March,11,11,2024-03-11,0,2,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,74.8,0,0
HB-115743,City Hotel,0,5,2025,July,28,9,2025-07-09,1,0,3,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,198.0,0,0
HB-075580,City Hotel,0,257,2023,July,26,1,2023-07-01,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,101.5,0,0
HB-047663,City Hotel,1,1,2024,February,9,28,2024-02-28,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,60.0,0,0
HB-060392,City Hotel,1,50,2024,November,45,9,2024-11-09,0,2,1,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,145.69,0,0
HB-104033,City Hotel,0,22,2025,January,1,2,2025-01-02,1,1,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.0,0,1
HB-098940,City Hotel,0,22,2024,October,40,5,2024-10-05,0,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-085096,City Hotel,0,1,2024,March,10,8,2024-03-08,0,1,1,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,116.0,0,1
HB-085440,City Hotel,0,55,2024,March,11,13,2024-03-13,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,78.3,0,1
HB-118648,City Hotel,0,180,2025,August,34,21,2025-08-21,1,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,2
HB-059219,City Hotel,1,229,2024,October,43,22,2024-10-22,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,Non Refund,10.0,,0,Transient,89.25,0,0
HB-110606,City Hotel,0,21,2025,April,18,28,2025-04-28,0,1,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,K,0,No Deposit,9.0,,0,Transient,115.0,0,2
HB-027137,Resort Hotel,0,220,2024,August,33,15,2024-08-15,1,5,2,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,240.0,,0,Transient,190.0,0,1
HB-044788,City Hotel,0,0,2023,October,41,12,2023-10-12,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-036998,Resort Hotel,0,119,2025,June,23,3,2025-06-03,2,4,2,2.0,0,BB,IRL,Direct,Direct,0,0,0,G,G,1,No Deposit,250.0,,0,Transient-Party,175.0,0,1
HB-003821,Resort Hotel,1,122,2024,January,2,12,2024-01-12,12,30,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,22.11,0,0
HB-055016,City Hotel,0,210,2024,August,31,2,2024-08-02,0,4,2,2.0,0,BB,NLD,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,167.95,0,0
HB-117132,City Hotel,0,331,2025,July,30,24,2025-07-24,1,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient,91.85,0,3
HB-072901,City Hotel,1,132,2025,August,32,9,2025-08-09,0,3,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,195.0,0,2
HB-062352,City Hotel,1,3,2025,January,2,10,2025-01-10,0,4,2,0.0,0,BB,MAR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,83.09,0,1
HB-020726,Resort Hotel,0,10,2024,February,8,25,2024-02-25,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,1,0,1,D,D,0,No Deposit,242.0,,0,Group,58.0,0,2
HB-097918,City Hotel,0,159,2024,September,38,19,2024-09-19,1,2,2,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,A,3,No Deposit,240.0,,0,Transient-Party,144.0,0,0
HB-000405,Resort Hotel,0,38,2023,July,28,14,2023-07-14,4,10,2,0.0,0,HB,SWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,109.9,0,2
HB-031703,Resort Hotel,0,61,2024,December,51,22,2024-12-22,4,10,2,0.0,0,Undefined,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,464.0,,0,Transient,82.29,0,0
HB-059266,City Hotel,1,1,2024,October,43,25,2024-10-25,0,1,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,2
HB-068409,City Hotel,1,313,2025,May,20,17,2025-05-17,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,276.0,,0,Transient-Party,89.1,0,0
HB-103589,City Hotel,0,46,2024,December,52,25,2024-12-25,2,1,2,0.0,0,SC,JPN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,0
HB-104556,City Hotel,0,151,2025,January,3,16,2025-01-16,1,0,2,0.0,0,BB,AUS,Direct,Direct,0,0,0,A,A,3,No Deposit,14.0,,0,Transient,67.15,0,0
HB-049314,City Hotel,1,23,2024,April,15,10,2024-04-10,2,2,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.0,0,0
HB-010381,Resort Hotel,1,181,2025,March,9,1,2025-03-01,6,19,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,440.0,,0,Transient-Party,62.0,0,0
HB-084265,City Hotel,0,41,2024,February,8,19,2024-02-19,1,2,1,0.0,0,BB,DNK,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.9,0,0
HB-102111,City Hotel,0,0,2024,November,47,21,2024-11-21,1,1,1,0.0,0,BB,HRV,Groups,Corporate,0,0,0,A,C,0,No Deposit,,233.0,0,Transient,75.0,0,0
HB-043974,City Hotel,0,35,2023,September,39,26,2023-09-26,2,4,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,166.58,0,2
HB-024863,Resort Hotel,0,42,2024,June,23,4,2024-06-04,1,1,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,117.0,1,0
HB-091878,City Hotel,0,192,2024,June,26,24,2024-06-24,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,34.0,,0,Transient-Party,95.0,0,0
HB-023683,Resort Hotel,0,6,2024,April,18,29,2024-04-29,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,86.0,1,0
HB-086103,City Hotel,0,73,2024,March,12,24,2024-03-24,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,53.38,0,1
HB-093693,City Hotel,0,12,2024,July,30,24,2024-07-24,1,0,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,139.0,0,0
HB-063748,City Hotel,1,41,2025,February,8,20,2025-02-20,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,9,Transient,85.0,0,0
HB-049209,City Hotel,1,16,2024,April,14,7,2024-04-07,1,3,1,0.0,0,BB,SAU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,127.5,0,0
HB-095177,City Hotel,0,159,2024,August,32,8,2024-08-08,3,5,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,97.75,0,0
HB-066378,City Hotel,1,35,2025,April,16,18,2025-04-18,0,3,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,132.33,0,0
HB-035729,Resort Hotel,0,105,2025,April,17,27,2025-04-27,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,108.33,0,1
HB-036642,Resort Hotel,0,2,2025,May,21,21,2025-05-21,2,2,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,42.0,0,0
HB-061616,City Hotel,1,74,2024,December,51,19,2024-12-19,1,3,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,74.8,0,0
HB-051875,City Hotel,0,316,2024,May,21,26,2024-05-26,0,3,1,0.0,0,BB,AUT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,30.0,,0,Transient-Party,100.0,0,0
HB-093481,City Hotel,0,47,2024,July,29,17,2024-07-17,2,3,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,161.1,0,2
HB-094774,City Hotel,0,12,2024,August,32,6,2024-08-06,2,1,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,112.42,0,1
HB-045111,City Hotel,0,84,2023,October,42,16,2023-10-16,1,2,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,89.25,0,2
HB-088073,City Hotel,0,0,2024,April,17,28,2024-04-28,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,84.14,0,1
HB-119389,City Hotel,0,109,2025,August,35,31,2025-08-31,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,89.0,,0,Transient,104.4,0,0
HB-032716,Resort Hotel,0,0,2025,February,6,9,2025-02-09,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,1,0,1,A,A,0,No Deposit,241.0,,0,Group,36.96,0,1
HB-049063,City Hotel,1,105,2024,April,14,6,2024-04-06,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,0,Transient,75.0,0,0
HB-033150,Resort Hotel,0,1,2025,February,7,16,2025-02-16,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,62.0,1,1
HB-115040,City Hotel,0,368,2025,June,26,28,2025-06-28,0,3,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,2
HB-038209,Resort Hotel,0,12,2025,July,28,11,2025-07-11,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,337.0,0,Transient-Party,135.0,0,0
HB-064459,City Hotel,1,260,2025,March,11,10,2025-03-10,0,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.0,0,0
HB-090726,City Hotel,0,118,2024,June,23,6,2024-06-06,1,3,1,0.0,0,BB,TUR,Offline TA/TO,Corporate,0,0,0,A,A,1,No Deposit,191.0,,0,Transient-Party,110.0,0,0
HB-016247,Resort Hotel,0,84,2023,August,32,13,2023-08-13,2,6,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient,107.0,0,0
HB-001352,Resort Hotel,0,43,2023,August,34,25,2023-08-25,2,8,2,2.0,0,BB,ROU,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,206.6,0,0
HB-017743,Resort Hotel,0,287,2023,October,41,15,2023-10-15,2,3,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,D,1,No Deposit,,223.0,0,Transient-Party,50.5,1,0
HB-082083,City Hotel,0,13,2023,December,50,17,2023-12-17,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,58.0,0,0
HB-035992,Resort Hotel,0,221,2025,April,18,30,2025-04-30,2,5,2,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,71.43,0,0
HB-061465,City Hotel,1,26,2024,December,50,12,2024-12-12,2,5,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,154.0,,0,Transient,75.0,0,0
HB-107583,City Hotel,0,35,2025,March,10,9,2025-03-09,2,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,73.37,0,0
HB-048331,City Hotel,0,75,2024,March,12,21,2024-03-21,1,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient-Party,78.15,0,0
HB-100404,City Hotel,0,2,2024,October,43,27,2024-10-27,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-092896,City Hotel,0,7,2024,July,28,12,2024-07-12,0,2,2,1.0,0,BB,LUX,Offline TA/TO,TA/TO,0,0,0,D,A,0,No Deposit,83.0,,0,Transient,147.3,0,1
HB-025810,Resort Hotel,0,2,2024,July,28,11,2024-07-11,1,0,2,0.0,0,BB,MAR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,144.0,0,1
HB-100798,City Hotel,0,177,2024,October,44,30,2024-10-30,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,159.0,,0,Transient,90.9,0,0
HB-090950,City Hotel,0,54,2024,June,24,11,2024-06-11,2,1,2,0.0,0,SC,DEU,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,138.0,,0,Transient,85.0,0,0
HB-028658,Resort Hotel,0,11,2024,October,41,9,2024-10-09,1,0,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,E,0,No Deposit,,405.0,0,Transient-Party,50.0,0,1
HB-102955,City Hotel,0,46,2024,December,49,7,2024-12-07,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,102.6,1,2
HB-001641,Resort Hotel,0,143,2023,September,36,6,2023-09-06,4,6,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,142.0,,0,Contract,111.96,0,0
HB-099579,City Hotel,0,53,2024,October,42,14,2024-10-14,0,1,1,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,77.0,,0,Transient-Party,120.0,0,0
HB-087059,City Hotel,0,23,2024,April,15,10,2024-04-10,2,2,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,125.0,0,0
HB-013795,Resort Hotel,1,17,2025,August,35,31,2025-08-31,0,3,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,207.0,0,2
HB-036452,Resort Hotel,0,20,2025,May,20,18,2025-05-18,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,91.67,0,0
HB-007296,Resort Hotel,1,180,2024,August,31,1,2024-08-01,2,5,2,1.0,0,Undefined,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,196.0,,0,Transient-Party,177.5,0,2
HB-079667,City Hotel,0,18,2024,June,24,10,2024-06-10,0,1,2,2.0,0,BB,PRT,Direct,Direct,1,0,2,F,F,0,No Deposit,,,0,Transient,65.0,0,1
HB-116051,City Hotel,0,451,2025,July,28,12,2025-07-12,0,3,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,1
HB-036719,Resort Hotel,0,203,2025,May,21,25,2025-05-25,0,3,1,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,D,D,1,No Deposit,,223.0,0,Transient-Party,60.0,0,0
HB-093585,City Hotel,0,226,2024,July,30,22,2024-07-22,0,2,1,0.0,0,BB,USA,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,96,Transient-Party,64.25,0,0
HB-008517,Resort Hotel,1,186,2024,October,40,3,2024-10-03,1,3,2,1.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,156.0,,0,Transient,139.3,0,0
HB-041416,City Hotel,1,131,2023,August,33,15,2023-08-15,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-094343,City Hotel,0,127,2024,July,30,26,2024-07-26,2,6,2,1.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,101.13,0,1
HB-074349,City Hotel,1,269,2023,July,28,13,2023-07-13,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Contract,62.0,0,0
HB-116277,City Hotel,0,184,2025,July,29,15,2025-07-15,1,1,3,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,89.1,0,1
HB-010567,Resort Hotel,1,144,2025,March,11,14,2025-03-14,4,14,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,C,1,No Deposit,440.0,,0,Transient-Party,62.0,0,0
HB-050870,City Hotel,1,71,2024,May,19,10,2024-05-10,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,58.0,,0,Transient-Party,80.0,0,0
HB-078141,City Hotel,0,12,2023,October,40,4,2023-10-04,1,0,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,3.0,,0,Transient-Party,72.0,0,0
HB-102539,City Hotel,0,2,2024,November,48,26,2024-11-26,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.78,0,0
HB-027446,Resort Hotel,0,26,2024,August,34,22,2024-08-22,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,238.14,0,3
HB-053001,City Hotel,1,188,2024,June,24,15,2024-06-15,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,39,Transient,130.0,0,0
HB-118334,City Hotel,0,167,2025,August,33,16,2025-08-16,0,3,2,1.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,133.65,0,1
HB-044804,City Hotel,1,105,2023,October,41,12,2023-10-12,1,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,110.0,0,0
HB-062969,City Hotel,1,130,2025,January,4,25,2025-01-25,0,2,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,71.28,0,2
HB-082469,City Hotel,0,53,2023,December,52,29,2023-12-29,0,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,81.0,0,1
HB-118109,City Hotel,0,87,2025,August,33,12,2025-08-12,2,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,160.0,0,2
HB-117493,City Hotel,0,63,2025,July,31,30,2025-07-30,2,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,153.67,1,1
HB-003604,Resort Hotel,1,0,2023,December,52,25,2023-12-25,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,Non Refund,240.0,,0,Transient,55.0,0,0
HB-029335,Resort Hotel,0,37,2024,October,43,25,2024-10-25,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,60.0,0,2
HB-101686,City Hotel,0,24,2024,November,46,13,2024-11-13,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,80.0,0,0
HB-076494,City Hotel,1,414,2023,December,49,5,2023-12-05,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-000733,Resort Hotel,1,41,2023,July,30,27,2023-07-27,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,120.6,0,0
HB-108052,City Hotel,0,151,2025,March,12,20,2025-03-20,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,95.0,0,0
HB-038971,Resort Hotel,0,188,2025,July,31,28,2025-07-28,2,5,2,0.0,0,HB,LUX,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,185.75,0,1
HB-020633,Resort Hotel,0,5,2025,January,4,23,2025-01-23,1,3,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,378.0,0,Transient,35.0,0,0
HB-063284,City Hotel,1,104,2025,February,6,5,2025-02-05,2,0,2,1.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,100.44,0,0
HB-100329,City Hotel,0,46,2024,October,43,25,2024-10-25,0,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,119.5,0,2
HB-039912,Resort Hotel,0,50,2025,August,34,22,2025-08-22,2,8,2,0.0,0,BB,CHE,Direct,Direct,0,0,0,D,A,0,No Deposit,250.0,,0,Transient,241.75,1,1
HB-023216,Resort Hotel,0,34,2024,April,16,15,2024-04-15,1,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,E,0,No Deposit,156.0,,0,Transient,60.0,0,0
HB-066138,City Hotel,1,176,2025,April,16,14,2025-04-14,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,2.0,,0,Transient-Party,90.0,0,0
HB-046635,City Hotel,1,35,2024,January,2,13,2024-01-13,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,78.3,0,0
HB-054281,City Hotel,1,51,2024,July,28,11,2024-07-11,1,1,3,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,142.2,0,0
HB-053778,City Hotel,1,6,2024,June,26,30,2024-06-30,0,1,2,0.0,0,SC,LUX,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,139.0,0,1
HB-009497,Resort Hotel,1,183,2024,December,49,3,2024-12-03,2,1,2,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,38.0,,0,Transient,72.0,0,0
HB-026240,Resort Hotel,0,174,2024,July,29,18,2024-07-18,2,5,2,1.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,3,No Deposit,250.0,,0,Transient,155.11,0,2
HB-094486,City Hotel,0,186,2024,August,31,3,2024-08-03,0,2,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,9.0,,0,Transient,121.5,0,0
HB-023446,Resort Hotel,0,32,2024,April,16,19,2024-04-19,2,5,1,0.0,0,HB,GBR,Groups,Direct,0,0,0,A,A,0,No Deposit,273.0,,0,Transient-Party,44.36,0,0
HB-058499,City Hotel,1,461,2024,October,41,13,2024-10-13,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-048309,City Hotel,1,60,2024,March,12,20,2024-03-20,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,75.0,0,0
HB-067085,City Hotel,1,26,2025,April,18,28,2025-04-28,1,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,115.0,0,1
HB-102218,City Hotel,0,62,2024,November,47,20,2024-11-20,2,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-088419,City Hotel,0,88,2024,May,18,3,2024-05-03,0,3,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,3.0,,0,Transient-Party,96.0,0,0
HB-042385,City Hotel,0,19,2023,September,36,5,2023-09-05,2,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,9.0,,0,Contract,165.0,0,1
HB-103700,City Hotel,0,72,2024,December,52,26,2024-12-26,1,3,2,0.0,0,BB,CHE,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,52.0,,0,Transient,84.15,0,0
HB-108207,City Hotel,0,31,2025,March,12,19,2025-03-19,2,3,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,91.8,0,0
HB-013057,Resort Hotel,1,191,2025,July,31,29,2025-07-29,2,5,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,246.0,0,0
HB-064514,City Hotel,1,46,2025,March,11,11,2025-03-11,2,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,106.2,0,0
HB-050398,City Hotel,1,28,2024,April,18,29,2024-04-29,2,4,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,131.6,0,0
HB-015752,Resort Hotel,0,48,2023,July,29,20,2023-07-20,3,9,2,1.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,241.0,,0,Transient,99.45,0,2
HB-044062,City Hotel,1,92,2023,September,39,30,2023-09-30,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-059281,City Hotel,1,84,2024,October,43,25,2024-10-25,0,5,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,104.4,0,0
HB-036932,Resort Hotel,0,2,2025,June,22,1,2025-06-01,0,1,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,,0,Transient,115.0,0,0
HB-060250,City Hotel,1,626,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-051344,City Hotel,1,316,2024,May,20,19,2024-05-19,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,59.0,0,0
HB-068321,City Hotel,1,104,2025,May,20,15,2025-05-15,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-082631,City Hotel,0,38,2023,December,52,31,2023-12-31,0,3,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,B,0,No Deposit,104.0,,0,Transient,137.33,0,0
HB-008499,Resort Hotel,1,157,2024,October,40,1,2024-10-01,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,Non Refund,96.0,,0,Transient,52.0,0,0
HB-019118,Resort Hotel,0,1,2023,December,49,5,2023-12-05,2,1,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,175.0,,0,Transient,38.4,0,0
HB-100813,City Hotel,0,228,2024,October,44,30,2024-10-30,2,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.3,0,0
HB-006952,Resort Hotel,1,82,2024,July,28,13,2024-07-13,0,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,176.25,0,0
HB-041826,City Hotel,0,50,2023,August,34,25,2023-08-25,0,4,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-017263,Resort Hotel,1,277,2023,October,40,5,2023-10-05,4,10,2,0.0,0,HB,GBR,Groups,Direct,0,1,0,D,D,0,Non Refund,273.0,,0,Transient,78.5,0,0
HB-040786,City Hotel,0,36,2023,August,32,7,2023-08-07,0,2,3,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,D,1,No Deposit,1.0,,0,Transient-Party,84.0,0,1
HB-095714,City Hotel,0,49,2024,August,34,21,2024-08-21,2,0,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,161.1,0,1
HB-011526,Resort Hotel,1,337,2025,May,20,13,2025-05-13,4,6,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,54.0,0,0
HB-111548,City Hotel,0,90,2025,May,19,10,2025-05-10,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,83.0,,0,Transient,129.6,0,0
HB-055086,City Hotel,1,391,2024,August,31,4,2024-08-04,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-078021,City Hotel,0,1,2023,December,48,3,2023-12-03,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,2,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-114634,City Hotel,0,251,2025,June,25,21,2025-06-21,0,4,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,153.68,0,1
HB-049719,City Hotel,1,28,2024,April,16,18,2024-04-18,1,0,1,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,95.0,0,0
HB-035945,Resort Hotel,0,74,2025,April,18,29,2025-04-29,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,143.0,,0,Transient,44.38,0,0
HB-028243,Resort Hotel,0,203,2024,September,38,19,2024-09-19,2,5,2,0.0,0,BB,LTU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,80.0,0,2
HB-107055,City Hotel,0,5,2025,March,9,2,2025-03-02,2,3,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,1
HB-089094,City Hotel,0,45,2024,May,20,15,2024-05-15,2,0,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,A,E,1,No Deposit,14.0,,0,Transient,126.1,0,0
HB-102187,City Hotel,0,0,2024,November,47,23,2024-11-23,0,1,2,0.0,0,SC,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,0.0,0,0
HB-026630,Resort Hotel,0,158,2024,July,31,30,2024-07-30,2,5,2,0.0,0,HB,NOR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,253.0,,0,Transient,143.1,0,0
HB-051021,City Hotel,1,273,2024,May,20,13,2024-05-13,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,95.0,0,0
HB-012136,Resort Hotel,1,103,2025,June,24,15,2025-06-15,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,150.0,0,0
HB-104758,City Hotel,0,80,2025,January,3,19,2025-01-19,0,3,2,1.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,9.0,,0,Transient,111.6,0,2
HB-036058,Resort Hotel,0,207,2025,May,19,5,2025-05-05,1,2,2,0.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,68.4,0,0
HB-069761,City Hotel,1,238,2025,June,23,5,2025-06-05,2,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient,106.35,0,1
HB-055562,City Hotel,1,214,2024,August,33,16,2024-08-16,0,3,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.9,0,0
HB-018744,Resort Hotel,1,1,2023,November,48,28,2023-11-28,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,26.0,0,0
HB-117147,City Hotel,0,64,2025,July,31,29,2025-07-29,0,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,150.0,0,2
HB-110642,City Hotel,0,172,2025,April,17,27,2025-04-27,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,95.46,0,1
HB-023111,Resort Hotel,0,147,2024,April,15,8,2024-04-08,2,6,1,0.0,0,HB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient-Party,88.0,0,0
HB-074478,City Hotel,1,318,2023,August,35,31,2023-08-31,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-091362,City Hotel,0,69,2024,June,25,17,2024-06-17,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.9,0,1
HB-045634,City Hotel,0,139,2023,November,46,17,2023-11-17,0,5,1,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,4,No Deposit,29.0,,87,Transient-Party,65.0,0,0
HB-095793,City Hotel,0,16,2024,August,34,21,2024-08-21,2,1,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,129.0,0,2
HB-093545,City Hotel,0,292,2024,July,29,21,2024-07-21,0,2,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,6.0,,0,Transient-Party,90.0,0,0
HB-086244,City Hotel,0,13,2024,March,13,27,2024-03-27,2,2,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,79.15,0,0
HB-055343,City Hotel,1,398,2024,August,32,11,2024-08-11,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-071072,City Hotel,1,26,2025,June,26,28,2025-06-28,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,280.0,0,Transient-Party,100.0,0,0
HB-020050,Resort Hotel,0,0,2024,November,46,16,2024-11-16,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,1,0,1,A,D,0,No Deposit,184.0,,0,Transient,54.0,0,0
HB-030780,Resort Hotel,0,128,2024,December,49,3,2024-12-03,0,1,2,0.0,0,HB,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,64.0,0,1
HB-055593,City Hotel,1,61,2024,August,33,17,2024-08-17,0,2,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,168.3,0,0
HB-092166,City Hotel,0,160,2024,June,26,25,2024-06-25,2,5,2,1.0,0,BB,POL,Online TA,TA/TO,0,0,0,F,G,1,No Deposit,9.0,,0,Transient,208.13,0,1
HB-079838,City Hotel,1,34,2023,December,49,8,2023-12-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,0,Transient,90.0,0,0
HB-107245,City Hotel,0,2,2025,March,10,8,2025-03-08,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient,65.0,0,0
HB-054021,City Hotel,1,72,2024,July,27,6,2024-07-06,0,1,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,0
HB-094895,City Hotel,0,135,2024,August,32,9,2024-08-09,0,3,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,103.5,0,1
HB-099554,City Hotel,0,2,2024,October,41,13,2024-10-13,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,344.0,,0,Transient,109.65,0,0
HB-015029,Resort Hotel,0,96,2023,December,52,29,2023-12-29,0,5,2,0.0,0,HB,PRT,Direct,Direct,1,0,1,A,D,0,No Deposit,,,0,Transient,120.02,0,1
HB-027430,Resort Hotel,0,214,2024,August,34,19,2024-08-19,3,7,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,138.0,0,1
HB-047086,City Hotel,0,45,2024,February,6,6,2024-02-06,2,2,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,55.24,0,1
HB-071353,City Hotel,1,155,2025,July,27,3,2025-07-03,1,3,3,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,152.1,0,0
HB-031875,Resort Hotel,0,154,2024,December,52,29,2024-12-29,3,8,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,47.54,0,3
HB-105995,City Hotel,0,70,2025,February,7,15,2025-02-15,0,4,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,242.0,0,Transient-Party,78.0,0,0
HB-057489,City Hotel,1,418,2024,September,39,26,2024-09-26,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,223,Transient-Party,75.0,0,0
HB-096089,City Hotel,0,11,2024,August,35,28,2024-08-28,1,0,2,0.0,0,SC,FRA,Direct,Direct,0,0,0,A,A,2,No Deposit,,,0,Transient,109.0,0,0
HB-058734,City Hotel,1,163,2024,October,42,15,2024-10-15,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,34.0,,0,Transient,115.0,0,0
HB-005280,Resort Hotel,1,95,2024,April,17,23,2024-04-23,4,10,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,95.0,,0,Transient-Party,47.0,0,0
HB-093274,City Hotel,0,32,2024,July,29,18,2024-07-18,1,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,39.0,,0,Transient-Party,105.0,0,1
HB-031216,Resort Hotel,0,5,2024,December,51,18,2024-12-18,1,0,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,I,0,No Deposit,241.0,,0,Transient,35.11,0,1
HB-007668,Resort Hotel,1,13,2024,August,34,19,2024-08-19,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,227.0,0,1
HB-056623,City Hotel,1,66,2024,September,37,9,2024-09-09,0,2,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,168.3,0,0
HB-089379,City Hotel,0,0,2024,May,21,20,2024-05-20,0,1,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,9.0,,0,Transient,155.0,0,1
HB-004668,Resort Hotel,1,58,2024,March,13,26,2024-03-26,2,1,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,95.67,0,0
HB-020803,Resort Hotel,0,0,2024,February,6,10,2024-02-10,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,1,0,0,A,D,3,No Deposit,,,0,Transient-Party,55.0,1,0
HB-084030,City Hotel,0,12,2024,February,7,17,2024-02-17,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.0,1,0
HB-040244,City Hotel,0,103,2023,July,29,18,2023-07-18,2,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-082781,City Hotel,1,68,2024,February,7,17,2024-02-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,37.0,,0,Transient,75.0,0,0
HB-104245,City Hotel,0,1,2025,January,2,8,2025-01-08,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.5,0,0
HB-049062,City Hotel,1,105,2024,April,14,6,2024-04-06,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,0,Transient,75.0,0,0
HB-007056,Resort Hotel,1,130,2024,July,29,18,2024-07-18,1,4,2,2.0,0,BB,NLD,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,252.0,0,0
HB-062895,City Hotel,1,31,2025,January,4,24,2025-01-24,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.5,0,2
HB-087633,City Hotel,0,9,2024,April,16,20,2024-04-20,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,95.0,0,0
HB-041294,City Hotel,1,39,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,101.5,0,0
HB-094465,City Hotel,0,122,2024,August,31,2,2024-08-02,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,9.0,,0,Transient,118.8,0,1
HB-068078,City Hotel,1,156,2025,May,20,12,2025-05-12,1,2,1,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.8,0,0
HB-025864,Resort Hotel,0,137,2024,July,28,9,2024-07-09,2,3,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,119.0,0,1
HB-113546,City Hotel,0,31,2025,June,23,5,2025-06-05,1,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.0,0,2
HB-006298,Resort Hotel,0,208,2024,June,22,1,2024-06-01,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,E,0,No Deposit,40.0,,0,Transient,64.9,0,0
HB-081940,City Hotel,1,278,2024,August,32,11,2024-08-11,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,65.0,0,0
HB-098795,City Hotel,0,20,2024,October,40,2,2024-10-02,2,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,164.0,0,0
HB-004438,Resort Hotel,1,105,2024,March,12,18,2024-03-18,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,0
HB-090719,City Hotel,0,41,2024,June,23,7,2024-06-07,0,3,2,0.0,0,BB,BRA,Direct,Direct,0,0,0,D,G,0,No Deposit,,,0,Transient,118.0,0,3
HB-049130,City Hotel,0,92,2024,April,14,6,2024-04-06,0,1,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,1
HB-083347,City Hotel,0,4,2024,January,4,26,2024-01-26,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,117.0,1,1
HB-091676,City Hotel,0,53,2024,June,25,20,2024-06-20,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.9,0,2
HB-096706,City Hotel,0,61,2024,September,36,3,2024-09-03,2,2,2,0.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,A,B,1,No Deposit,42.0,,0,Transient,106.25,0,1
HB-048996,City Hotel,1,91,2024,April,14,4,2024-04-04,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,80.0,0,0
HB-019924,Resort Hotel,0,61,2024,January,1,5,2024-01-05,0,4,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,177.0,,0,Transient,45.0,0,1
HB-054316,City Hotel,1,176,2024,July,28,12,2024-07-12,0,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.95,0,0
HB-043218,City Hotel,0,16,2023,September,37,16,2023-09-16,1,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,116.4,0,2
HB-020816,Resort Hotel,0,0,2024,February,6,7,2024-02-07,2,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,F,0,No Deposit,,,0,Transient,65.0,0,2
HB-051980,City Hotel,1,0,2024,May,22,27,2024-05-27,0,2,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,,,0,Transient,182.33,0,1
HB-063481,City Hotel,1,67,2025,February,7,12,2025-02-12,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,80.0,0,0
HB-026878,Resort Hotel,0,9,2024,August,33,12,2024-08-12,0,1,2,1.0,0,HB,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,241.0,,0,Transient,202.28,0,0
HB-091067,City Hotel,0,7,2024,June,24,13,2024-06-13,1,2,1,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,3,No Deposit,9.0,,0,Transient,108.33,0,1
HB-114251,City Hotel,0,125,2025,June,24,15,2025-06-15,1,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,89.1,0,1
HB-004619,Resort Hotel,1,106,2024,March,12,24,2024-03-24,1,3,2,0.0,0,FB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,68.0,,0,Transient,84.0,0,0
HB-084919,City Hotel,0,22,2024,March,10,4,2024-03-04,0,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,87.0,0,0
HB-035801,Resort Hotel,0,100,2025,April,18,29,2025-04-29,2,1,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,385.0,,0,Transient-Party,83.0,0,1
HB-082387,City Hotel,1,108,2024,March,12,18,2024-03-18,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,154.0,,0,Transient,80.0,0,0
HB-065516,City Hotel,1,27,2025,April,14,4,2025-04-04,0,5,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,175.0,0,1
HB-028717,Resort Hotel,0,8,2024,October,40,6,2024-10-06,1,3,3,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,C,1,No Deposit,,405.0,0,Transient-Party,70.0,0,0
HB-089100,City Hotel,0,0,2024,May,20,17,2024-05-17,0,0,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,1,0,0,A,A,0,No Deposit,6.0,,0,Transient,0.0,0,0
HB-065947,City Hotel,1,85,2025,April,15,10,2025-04-10,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.25,0,0
HB-049459,City Hotel,1,281,2024,April,15,14,2024-04-14,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-084062,City Hotel,0,3,2024,February,7,18,2024-02-18,0,1,1,0.0,0,BB,JOR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,7.0,,0,Transient,66.57,0,1
HB-079082,City Hotel,0,0,2023,October,42,21,2023-10-21,0,1,1,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,D,E,0,No Deposit,87.0,,0,Transient-Party,145.0,0,1
HB-067814,City Hotel,1,17,2025,May,19,8,2025-05-08,1,0,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,10.0,,0,Transient,95.0,0,0
HB-025161,Resort Hotel,0,177,2024,June,24,10,2024-06-10,2,5,2,0.0,0,HB,IRL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,140.0,0,2
HB-044282,City Hotel,0,198,2023,October,40,3,2023-10-03,1,1,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,60.0,0,1
HB-043297,City Hotel,0,24,2023,September,37,17,2023-09-17,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,9.0,,0,Contract,117.67,0,2
HB-085056,City Hotel,0,0,2024,March,10,8,2024-03-08,0,0,1,0.0,0,BB,PRT,Direct,Direct,1,0,0,A,A,0,No Deposit,,,0,Transient,0.0,0,0
HB-011300,Resort Hotel,1,73,2025,May,18,1,2025-05-01,3,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,115.0,0,1
HB-010738,Resort Hotel,1,47,2025,March,13,30,2025-03-30,2,5,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,60.0,0,1
HB-012315,Resort Hotel,1,80,2025,June,26,24,2025-06-24,2,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,68.4,0,0
HB-078197,City Hotel,0,12,2023,October,40,3,2023-10-03,2,1,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,139.33,0,0
HB-086126,City Hotel,0,33,2024,March,13,25,2024-03-25,1,2,2,2.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,199.5,1,0
HB-042432,City Hotel,1,61,2023,September,36,5,2023-09-05,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-029492,Resort Hotel,0,118,2024,October,43,23,2024-10-23,2,5,3,0.0,0,BB,NLD,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient-Party,111.2,0,1
HB-103744,City Hotel,0,119,2024,December,52,28,2024-12-28,0,3,2,1.0,0,HB,CHE,Direct,Direct,0,0,0,E,G,1,No Deposit,14.0,,0,Transient,202.33,0,1
HB-038159,Resort Hotel,0,204,2025,July,27,1,2025-07-01,4,6,2,1.0,0,HB,ROU,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,185.5,0,2
HB-080594,City Hotel,0,1,2023,November,46,19,2023-11-19,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-085732,City Hotel,0,13,2024,March,12,20,2024-03-20,1,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,220.0,,0,Transient-Party,75.0,0,0
HB-113968,City Hotel,0,7,2025,June,24,9,2025-06-09,2,4,1,0.0,0,BB,PRT,Aviation,Corporate,0,0,0,D,D,0,No Deposit,,153.0,0,Transient,110.0,0,0
HB-095696,City Hotel,0,120,2024,August,33,18,2024-08-18,2,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,92.87,0,2
HB-109362,City Hotel,0,8,2025,April,15,7,2025-04-07,1,2,2,3.0,0,HB,ESP,Direct,Direct,0,0,0,G,G,0,No Deposit,,14.0,0,Transient,289.0,1,2
HB-054219,City Hotel,1,65,2024,July,28,9,2024-07-09,1,1,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,148.5,0,0
HB-052072,City Hotel,1,56,2024,May,22,30,2024-05-30,1,0,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,120.0,0,0
HB-019110,Resort Hotel,0,7,2023,December,49,7,2023-12-07,1,0,2,0.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,49.4,0,0
HB-114523,City Hotel,0,181,2025,June,25,20,2025-06-20,0,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,153.33,0,2
HB-063911,City Hotel,1,134,2025,February,9,25,2025-02-25,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,75.0,0,0
HB-047463,City Hotel,1,50,2024,February,8,22,2024-02-22,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,86.0,,0,Transient,12.0,0,0
HB-111458,City Hotel,0,86,2025,May,19,8,2025-05-08,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-102747,City Hotel,0,18,2024,December,49,2,2024-12-02,2,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,83.04,0,1
HB-018349,Resort Hotel,1,82,2024,February,6,7,2024-02-07,2,0,2,0.0,0,Undefined,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,67.0,,0,Transient-Party,66.0,0,0
HB-049592,City Hotel,1,61,2024,April,16,15,2024-04-15,1,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,124.8,0,0
HB-093304,City Hotel,0,4,2024,July,29,18,2024-07-18,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,1,No Deposit,,40.0,0,Transient,65.0,0,1
HB-089914,City Hotel,0,2,2024,May,21,26,2024-05-26,0,3,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,176.0,0,1
HB-038173,Resort Hotel,0,130,2025,July,28,9,2025-07-09,2,0,2,0.0,0,BB,TWN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,242.0,,0,Transient-Party,160.0,0,1
HB-059465,City Hotel,1,247,2024,October,44,28,2024-10-28,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,110.0,0,0
HB-022019,Resort Hotel,0,101,2024,March,11,14,2024-03-14,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,61.2,0,0
HB-048798,City Hotel,1,12,2024,March,13,30,2024-03-30,6,15,1,0.0,0,BB,AGO,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,128.06,0,0
HB-118053,City Hotel,0,149,2025,August,32,7,2025-08-07,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.5,0,1
HB-021649,Resort Hotel,0,5,2024,March,9,1,2024-03-01,0,5,1,0.0,0,HB,PRT,Groups,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient-Party,66.0,0,0
HB-090644,City Hotel,0,18,2024,June,23,8,2024-06-08,0,1,2,0.0,0,BB,TUR,Groups,Direct,0,0,0,A,A,0,Non Refund,,,2,Transient-Party,92.65,0,0
HB-066581,City Hotel,1,194,2025,April,17,21,2025-04-21,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,2
HB-049488,City Hotel,1,101,2024,April,15,14,2024-04-14,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,130.0,0,0
HB-106524,City Hotel,0,13,2025,February,8,23,2025-02-23,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,122.4,0,2
HB-067469,City Hotel,1,143,2025,May,18,4,2025-05-04,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,56.0,,0,Transient,120.0,0,0
HB-052993,City Hotel,1,239,2024,June,24,15,2024-06-15,0,2,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,80,Transient,90.6,0,0
HB-015436,Resort Hotel,0,139,2023,July,27,8,2023-07-08,2,6,2,1.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,2,No Deposit,250.0,,0,Transient,107.2,0,1
HB-086615,City Hotel,0,55,2024,April,14,6,2024-04-06,0,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,104.0,0,0
HB-004476,Resort Hotel,1,180,2024,March,12,19,2024-03-19,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,43.33,0,1
HB-063644,City Hotel,1,70,2025,February,7,16,2025-02-16,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,95.4,0,2
HB-028035,Resort Hotel,0,9,2024,September,38,18,2024-09-18,1,0,1,0.0,0,BB,GBR,Groups,Corporate,0,0,0,E,C,0,No Deposit,223.0,,0,Transient-Party,96.0,0,0
HB-055408,City Hotel,1,206,2024,August,33,12,2024-08-12,2,2,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.75,0,0
HB-034702,Resort Hotel,0,0,2025,March,14,31,2025-03-31,0,2,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,70.0,0,0
HB-030478,Resort Hotel,0,6,2024,November,46,13,2024-11-13,4,7,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,171.0,,0,Transient,42.0,0,0
HB-041368,City Hotel,0,40,2023,August,33,15,2023-08-15,2,2,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-090319,City Hotel,0,49,2024,June,23,3,2024-06-03,0,2,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,2,No Deposit,85.0,,0,Transient,80.75,0,0
HB-109391,City Hotel,0,248,2025,April,15,9,2025-04-09,2,0,2,0.0,0,BB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,58.0,,0,Transient-Party,80.0,0,1
HB-047995,City Hotel,1,40,2024,March,11,11,2024-03-11,2,2,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,71.1,0,0
HB-009819,Resort Hotel,1,2,2025,January,2,6,2025-01-06,2,3,1,0.0,0,BB,NGA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,43.0,0,1
HB-031895,Resort Hotel,0,60,2025,January,1,1,2025-01-01,4,5,2,0.0,0,HB,FRA,Direct,Direct,0,0,0,F,F,1,No Deposit,250.0,,0,Transient,90.6,0,1
HB-069451,City Hotel,1,292,2025,May,22,31,2025-05-31,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,B,1,No Deposit,229.0,,0,Transient-Party,90.0,0,0
HB-045846,City Hotel,0,98,2023,November,47,23,2023-11-23,1,2,1,0.0,0,BB,HUN,Groups,TA/TO,0,0,0,A,D,0,No Deposit,37.0,,0,Transient-Party,70.0,0,0
HB-084034,City Hotel,0,21,2024,February,7,17,2024-02-17,0,1,1,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.0,0,1
HB-012653,Resort Hotel,1,156,2025,July,28,10,2025-07-10,1,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,120.0,0,1
HB-112418,City Hotel,0,18,2025,May,21,22,2025-05-22,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,315.0,,0,Transient-Party,120.0,0,1
HB-004107,Resort Hotel,0,230,2024,February,7,12,2024-02-12,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,31.88,0,3
HB-045757,City Hotel,0,98,2023,November,47,23,2023-11-23,1,2,1,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,70.0,0,0
HB-078018,City Hotel,0,1,2023,September,39,29,2023-09-29,0,2,1,0.0,0,BB,IRL,Corporate,Corporate,0,0,0,A,A,0,No Deposit,92.0,,0,Transient-Party,85.0,0,0
HB-109234,City Hotel,0,75,2025,April,14,5,2025-04-05,0,4,1,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,85.0,0,0
HB-068218,City Hotel,1,104,2025,May,20,15,2025-05-15,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-115593,City Hotel,0,97,2025,July,27,6,2025-07-06,0,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,1
HB-018652,Resort Hotel,0,13,2023,November,47,22,2023-11-22,2,2,1,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,115.0,,0,Transient,22.5,0,0
HB-004940,Resort Hotel,1,121,2024,April,15,9,2024-04-09,2,5,2,0.0,0,HB,GBR,Groups,Direct,0,0,0,D,D,0,Non Refund,273.0,,0,Transient,72.0,0,0
HB-074059,City Hotel,1,314,2023,August,34,27,2023-08-27,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-050157,City Hotel,1,146,2024,April,17,24,2024-04-24,2,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,26.0,,50,Transient,95.0,0,0
HB-019136,Resort Hotel,1,2,2023,December,49,8,2023-12-08,0,5,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,1,No Deposit,,,0,Transient,38.0,0,0
HB-004116,Resort Hotel,1,161,2024,February,7,13,2024-02-13,6,15,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,77.4,0,1
HB-100996,City Hotel,0,15,2024,November,44,1,2024-11-01,0,4,2,0.0,0,SC,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.0,0,2
HB-115656,City Hotel,0,181,2025,July,27,3,2025-07-03,1,5,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,80.1,0,0
HB-087606,City Hotel,0,28,2024,April,16,21,2024-04-21,0,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,109.0,0,1
HB-027381,Resort Hotel,0,124,2024,August,33,16,2024-08-16,2,10,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,36.0,,0,Transient,145.11,0,0
HB-044470,City Hotel,1,97,2023,October,40,5,2023-10-05,1,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,140.0,0,0
HB-117657,City Hotel,0,151,2025,August,32,4,2025-08-04,1,2,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,125.0,0,0
HB-079514,City Hotel,1,81,2023,December,52,30,2023-12-30,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Contract,111.0,0,1
HB-074752,City Hotel,1,185,2023,August,35,29,2023-08-29,1,1,2,1.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,6.0,,0,Transient,93.09,0,0
HB-095941,City Hotel,0,17,2024,August,34,22,2024-08-22,1,3,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,230.0,1,1
HB-036913,Resort Hotel,0,203,2025,May,21,25,2025-05-25,2,5,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,1,No Deposit,,223.0,0,Transient-Party,66.71,0,0
HB-109588,City Hotel,0,44,2025,April,15,10,2025-04-10,1,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,129.5,0,1
HB-002440,Resort Hotel,0,7,2023,October,41,15,2023-10-15,0,0,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,I,3,No Deposit,,223.0,0,Transient-Party,0.0,0,0
HB-010291,Resort Hotel,1,191,2025,February,9,24,2025-02-24,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,314.0,,0,Transient,44.64,0,0
HB-063334,City Hotel,1,580,2025,February,6,9,2025-02-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-041335,City Hotel,1,39,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,101.5,0,0
HB-076626,City Hotel,0,210,2023,July,30,30,2023-07-30,0,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient-Party,76.5,0,0
HB-021163,Resort Hotel,0,30,2024,February,7,17,2024-02-17,0,3,2,0.0,0,BB,OMN,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-007387,Resort Hotel,1,248,2024,August,32,6,2024-08-06,4,6,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,157.5,0,1
HB-053403,City Hotel,1,31,2024,June,25,20,2024-06-20,1,1,2,0.0,0,BB,KOR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,107.1,0,0
HB-042380,City Hotel,1,65,2023,September,36,5,2023-09-05,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-086578,City Hotel,0,46,2024,April,14,3,2024-04-03,2,1,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,0
HB-048027,City Hotel,0,97,2024,March,11,12,2024-03-12,2,5,1,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,10.0,,0,Transient,58.6,0,0
HB-044777,City Hotel,0,63,2023,October,41,10,2023-10-10,2,3,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,8.0,,0,Transient,89.25,0,0
HB-070309,City Hotel,1,201,2025,June,24,14,2025-06-14,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-068563,City Hotel,1,105,2025,May,21,19,2025-05-19,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-107072,City Hotel,0,26,2025,March,9,1,2025-03-01,2,4,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,113.0,0,1
HB-047322,City Hotel,1,44,2024,February,7,17,2024-02-17,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,44.0,,3,Transient,75.0,0,0
HB-093573,City Hotel,0,292,2024,July,29,21,2024-07-21,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,0
HB-106475,City Hotel,0,134,2025,February,9,25,2025-02-25,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,75.0,0,0
HB-035853,Resort Hotel,0,59,2025,May,18,3,2025-05-03,1,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,115.0,0,0
HB-097249,City Hotel,0,19,2024,September,37,11,2024-09-11,2,1,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,16.0,,0,Transient,107.0,0,0
HB-066906,City Hotel,1,156,2025,April,17,26,2025-04-26,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,100.0,0,0
HB-007644,Resort Hotel,1,165,2024,August,33,18,2024-08-18,0,3,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,237.0,0,0
HB-102208,City Hotel,0,55,2024,November,47,22,2024-11-22,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,102.6,0,1
HB-077200,City Hotel,1,4,2023,September,37,16,2023-09-16,0,4,2,2.0,0,BB,PRT,Online TA,TA/TO,0,1,0,F,F,0,No Deposit,9.0,,0,Transient,224.5,0,2
HB-021772,Resort Hotel,0,6,2024,March,10,8,2024-03-08,0,2,2,0.0,1,BB,PRT,Complementary,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,0.0,0,1
HB-112998,City Hotel,0,113,2025,May,22,30,2025-05-30,0,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,103.95,0,1
HB-005220,Resort Hotel,0,191,2024,April,17,22,2024-04-22,1,2,2,0.0,0,Undefined,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,85.33,0,1
HB-016009,Resort Hotel,0,227,2025,May,19,5,2025-05-05,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,1,0,1,A,A,0,No Deposit,240.0,,0,Transient,56.0,0,3
HB-012709,Resort Hotel,1,27,2025,July,28,13,2025-07-13,2,3,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,178.0,0,0
HB-027392,Resort Hotel,0,6,2024,August,34,25,2024-08-25,0,3,2,0.0,0,BB,BRA,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,200.1,0,1
HB-111647,City Hotel,0,120,2025,May,19,11,2025-05-11,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,89.1,0,0
HB-111678,City Hotel,0,116,2025,May,19,11,2025-05-11,0,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,120.0,0,1
HB-021756,Resort Hotel,0,0,2024,March,10,7,2024-03-07,1,1,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,29.0,0,1
HB-055591,City Hotel,1,221,2024,August,33,17,2024-08-17,0,2,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.5,0,0
HB-031173,Resort Hotel,0,26,2024,December,50,11,2024-12-11,2,4,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,E,E,2,No Deposit,240.0,,0,Transient,95.0,0,2
HB-079598,City Hotel,0,296,2023,October,43,24,2023-10-24,2,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,7.0,,0,Transient-Party,56.01,0,0
HB-071768,City Hotel,1,451,2025,July,28,12,2025-07-12,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,90.0,0,0
HB-073754,City Hotel,1,265,2023,July,27,9,2023-07-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-020407,Resort Hotel,0,17,2024,January,3,21,2024-01-21,2,5,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,52.8,0,1
HB-047137,City Hotel,0,66,2024,February,6,9,2024-02-09,0,3,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient-Party,80.55,1,1
HB-074019,City Hotel,1,300,2023,August,32,13,2023-08-13,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-042696,City Hotel,0,69,2023,September,36,9,2023-09-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,B,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-110855,City Hotel,0,20,2025,April,18,28,2025-04-28,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,148.5,0,1
HB-085931,City Hotel,0,2,2024,March,12,22,2024-03-22,0,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.0,0,0
HB-100283,City Hotel,0,4,2024,October,43,25,2024-10-25,0,1,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,104.0,0,0
HB-001733,Resort Hotel,0,157,2023,September,37,11,2023-09-11,1,2,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,G,F,0,No Deposit,240.0,,0,Transient,153.0,0,1
HB-050537,City Hotel,1,88,2024,May,18,3,2024-05-03,0,3,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,3.0,,0,Transient-Party,96.0,0,0
HB-030747,Resort Hotel,0,0,2024,December,48,1,2024-12-01,0,2,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,D,E,1,No Deposit,,,0,Transient,51.0,1,0
HB-075768,City Hotel,1,323,2023,September,36,5,2023-09-05,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-058456,City Hotel,1,279,2024,October,41,12,2024-10-12,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,98.0,,0,Transient,110.0,0,0
HB-009723,Resort Hotel,1,9,2024,December,52,29,2024-12-29,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,5,No Deposit,,,0,Transient,78.8,0,1
HB-001419,Resort Hotel,1,35,2023,August,35,28,2023-08-28,2,4,2,2.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,0,No Deposit,,,0,Transient,141.67,0,2
HB-115079,City Hotel,0,240,2025,June,26,24,2025-06-24,2,5,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,42.0,,0,Transient,89.0,0,1
HB-026271,Resort Hotel,0,119,2024,July,30,22,2024-07-22,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,123.2,0,1
HB-033028,Resort Hotel,0,2,2025,February,7,11,2025-02-11,0,1,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,80.0,1,2
HB-116221,City Hotel,0,231,2025,July,29,15,2025-07-15,0,1,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,K,0,No Deposit,229.0,,0,Transient,90.0,0,0
HB-014476,Resort Hotel,0,0,2024,December,50,14,2024-12-14,0,1,1,0.0,0,BB,,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,35.0,0,0
HB-008045,Resort Hotel,1,208,2024,September,36,7,2024-09-07,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,134.0,0,1
HB-093298,City Hotel,0,69,2024,July,29,16,2024-07-16,2,2,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.5,0,3
HB-101291,City Hotel,0,33,2024,November,45,7,2024-11-07,1,2,1,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,197.0,0,2
HB-066296,City Hotel,1,128,2025,April,16,16,2025-04-16,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,0,Transient,100.0,0,0
HB-032886,Resort Hotel,0,10,2025,February,6,6,2025-02-06,1,1,3,0.0,0,Undefined,PRT,Groups,Corporate,0,0,0,A,C,0,No Deposit,,507.0,0,Transient-Party,120.0,0,0
HB-006003,Resort Hotel,1,101,2024,May,20,19,2024-05-19,3,8,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,96.0,,0,Transient-Party,63.0,0,0
HB-103910,City Hotel,0,207,2024,December,1,30,2024-12-30,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,104.0,,0,Transient,161.67,0,0
HB-048743,City Hotel,0,85,2024,March,13,29,2024-03-29,0,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,82.45,0,0
HB-025332,Resort Hotel,0,265,2024,June,24,15,2024-06-15,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,156.0,,0,Transient,68.4,0,2
HB-008857,Resort Hotel,1,243,2024,October,42,16,2024-10-16,2,5,2,1.0,0,HB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,242.0,,0,Transient,141.7,0,1
HB-065705,City Hotel,1,62,2025,April,14,6,2025-04-06,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,135.0,0,0
HB-112614,City Hotel,0,0,2025,May,21,25,2025-05-25,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,160.0,0,0
HB-114308,City Hotel,0,448,2025,June,25,17,2025-06-17,2,1,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,D,0,No Deposit,229.0,,0,Transient-Party,137.67,0,1
HB-048443,City Hotel,1,40,2024,March,12,23,2024-03-23,0,4,3,0.0,0,BB,VEN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,145.35,0,1
HB-090394,City Hotel,0,59,2024,June,23,3,2024-06-03,1,2,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,156.3,0,2
HB-006690,Resort Hotel,0,310,2024,June,26,24,2024-06-24,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,40.0,,0,Contract,85.3,0,0
HB-014193,Resort Hotel,1,160,2025,April,14,2,2025-04-02,2,3,2,0.0,0,BB,,Direct,Direct,0,1,4,E,E,0,No Deposit,,,0,Transient,70.8,0,3
HB-101796,City Hotel,0,0,2024,November,46,17,2024-11-17,0,1,1,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,95.0,0,1
HB-033149,Resort Hotel,0,3,2025,February,7,12,2025-02-12,2,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,57.0,,0,Transient,42.0,0,0
HB-111468,City Hotel,0,355,2025,May,19,8,2025-05-08,1,2,2,0.0,0,SC,MLT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.1,0,1
HB-042426,City Hotel,0,61,2023,September,36,5,2023-09-05,2,2,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,2,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-021600,Resort Hotel,0,18,2024,February,9,27,2024-02-27,2,5,2,2.0,0,BB,SWE,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,93.0,0,0
HB-041786,City Hotel,0,53,2023,August,34,24,2023-08-24,1,1,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-015574,Resort Hotel,0,11,2023,July,30,24,2023-07-24,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,E,0,No Deposit,,,0,Transient,150.0,0,1
HB-012740,Resort Hotel,1,59,2025,July,29,15,2025-07-15,1,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,2,No Deposit,250.0,,0,Transient,214.0,0,1
HB-039414,Resort Hotel,0,256,2025,August,32,8,2025-08-08,2,7,2,0.0,0,HB,BEL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,479.0,,0,Transient,131.85,0,4
HB-012140,Resort Hotel,1,219,2025,June,24,15,2025-06-15,0,3,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient,84.6,0,1
HB-089344,City Hotel,0,82,2024,May,20,17,2024-05-17,0,3,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,159.3,0,1
HB-071969,City Hotel,1,190,2025,July,29,16,2025-07-16,2,2,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,147.9,0,0
HB-097145,City Hotel,0,69,2024,September,37,12,2024-09-12,1,0,2,0.0,0,SC,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.1,0,1
HB-052788,City Hotel,1,69,2024,June,24,12,2024-06-12,2,4,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,120.0,0,0
HB-008485,Resort Hotel,1,65,2024,October,40,1,2024-10-01,2,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,99.0,0,1
HB-021056,Resort Hotel,0,0,2024,February,7,16,2024-02-16,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,45.0,0,0
HB-022567,Resort Hotel,0,20,2024,March,13,27,2024-03-27,2,0,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,80.0,0,1
HB-066012,City Hotel,1,164,2025,April,15,13,2025-04-13,0,1,2,0.0,0,HB,HUN,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,160.2,0,2
HB-088077,City Hotel,0,79,2024,April,17,28,2024-04-28,0,3,3,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,9.0,,0,Transient,149.1,0,1
HB-097287,City Hotel,0,172,2024,September,37,12,2024-09-12,1,2,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,16.0,,0,Transient,80.75,0,1
HB-119203,City Hotel,0,213,2025,August,35,28,2025-08-28,1,3,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,19.0,,0,Transient-Party,104.0,0,0
HB-118479,City Hotel,0,182,2025,August,32,9,2025-08-09,3,9,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,42.0,,0,Transient,89.1,0,1
HB-103731,City Hotel,0,80,2024,December,52,27,2024-12-27,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,114.9,0,1
HB-069348,City Hotel,1,186,2025,May,22,30,2025-05-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,130.0,0,0
HB-041757,City Hotel,0,10,2023,August,34,23,2023-08-23,1,0,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Contract,153.0,0,0
HB-039673,Resort Hotel,0,127,2025,August,34,18,2025-08-18,2,5,2,1.0,0,HB,PRT,Direct,Direct,0,0,0,E,E,4,No Deposit,250.0,,0,Transient,334.43,1,4
HB-081863,City Hotel,1,178,2024,April,17,28,2024-04-28,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,46,Transient,110.0,0,0
HB-016795,Resort Hotel,0,205,2023,September,35,3,2023-09-03,2,8,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,171.0,,0,Transient,82.35,0,0
HB-113720,City Hotel,0,0,2025,June,24,10,2025-06-10,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,144.0,0,2
HB-074794,City Hotel,1,364,2023,October,42,16,2023-10-16,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,6.0,,0,Transient-Party,109.0,0,0
HB-094459,City Hotel,0,1,2024,August,31,4,2024-08-04,0,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,151.0,0,1
HB-085303,City Hotel,0,162,2024,March,10,8,2024-03-08,0,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Group,62.0,0,1
HB-056920,City Hotel,1,185,2024,September,37,15,2024-09-15,0,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,116.1,0,0
HB-016050,Resort Hotel,1,222,2023,September,37,14,2023-09-14,1,1,2,0.0,0,HB,ESP,Groups,TA/TO,0,1,0,A,A,0,No Deposit,68.0,,0,Transient-Party,80.0,0,0
HB-025388,Resort Hotel,0,0,2024,June,26,24,2024-06-24,0,1,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient,161.0,1,0
HB-012586,Resort Hotel,1,168,2025,July,27,6,2025-07-06,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,142.67,0,2
HB-003742,Resort Hotel,0,88,2024,January,1,1,2024-01-01,0,2,2,0.0,0,HB,ARG,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,241.0,,0,Transient,73.46,0,2
HB-003704,Resort Hotel,0,165,2023,December,52,30,2023-12-30,0,4,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,C,0,No Deposit,308.0,,122,Transient,136.5,0,0
HB-022023,Resort Hotel,1,0,2024,April,16,20,2024-04-20,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,392.0,0,Transient-Party,58.5,0,0
HB-039501,Resort Hotel,0,223,2025,August,33,13,2025-08-13,2,5,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,131.49,0,0
HB-064613,City Hotel,1,13,2025,March,11,13,2025-03-13,1,2,2,0.0,0,BB,LVA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,151.33,0,0
HB-031896,Resort Hotel,0,26,2025,January,2,6,2025-01-06,2,2,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,241.0,,0,Transient,65.84,0,2
HB-117619,City Hotel,0,139,2025,August,32,5,2025-08-05,1,1,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.5,0,2
HB-003322,Resort Hotel,1,66,2023,December,49,5,2023-12-05,1,1,1,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,155.0,,0,Transient-Party,52.0,0,0
HB-105268,City Hotel,0,0,2025,January,5,31,2025-01-31,0,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,100.25,0,0
HB-068811,City Hotel,1,178,2025,May,21,20,2025-05-20,2,2,1,0.0,0,BB,KOR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.28,0,0
HB-102804,City Hotel,0,29,2024,November,48,30,2024-11-30,2,4,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,104.0,0,1
HB-113495,City Hotel,0,364,2025,June,25,16,2025-06-16,0,1,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,1,A,A,1,No Deposit,21.0,,0,Group,64.5,0,1
HB-103838,City Hotel,0,353,2024,December,52,29,2024-12-29,1,3,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,B,A,6,No Deposit,9.0,,0,Transient-Party,73.74,0,0
HB-040630,City Hotel,1,28,2023,August,31,3,2023-08-03,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-075152,City Hotel,1,278,2023,July,29,22,2023-07-22,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-026529,Resort Hotel,0,12,2024,August,31,2,2024-08-02,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,209.0,0,0
HB-028690,Resort Hotel,0,383,2024,October,40,6,2024-10-06,0,3,1,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,1,No Deposit,315.0,,0,Transient-Party,42.0,0,0
HB-020703,Resort Hotel,0,192,2024,February,6,7,2024-02-07,1,0,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,29.16,0,1
HB-056424,City Hotel,1,123,2024,September,36,5,2024-09-05,1,3,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.8,0,1
HB-081209,City Hotel,0,12,2023,December,49,5,2023-12-05,1,1,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,64.0,0,1
HB-077583,City Hotel,0,2,2023,December,48,2,2023-12-02,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,5,A,A,0,No Deposit,,40.0,0,Transient,74.0,0,0
HB-056911,City Hotel,1,26,2024,September,37,15,2024-09-15,0,2,2,0.0,0,SC,MAR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,139.0,0,0
HB-093074,City Hotel,0,186,2024,July,28,12,2024-07-12,0,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.95,0,2
HB-028526,Resort Hotel,0,245,2024,September,39,26,2024-09-26,3,7,2,0.0,0,HB,CN,Groups,TA/TO,0,0,0,A,A,0,No Deposit,15.0,,0,Transient-Party,80.0,0,1
HB-017214,Resort Hotel,0,167,2023,September,37,17,2023-09-17,4,10,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Contract,68.0,0,3
HB-020263,Resort Hotel,0,3,2024,January,3,21,2024-01-21,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,40.0,1,2
HB-081529,City Hotel,0,11,2023,December,50,11,2023-12-11,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,58.0,0,0
HB-044460,City Hotel,1,97,2023,October,40,5,2023-10-05,1,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,140.0,0,0
HB-082156,City Hotel,1,99,2024,February,8,19,2024-02-19,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,1,0,A,A,0,No Deposit,,67.0,0,Transient-Party,80.0,0,0
HB-058037,City Hotel,1,40,2024,October,40,5,2024-10-05,0,2,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.5,0,0
HB-015165,Resort Hotel,1,244,2023,September,35,2,2023-09-02,2,5,2,0.0,0,BB,IRL,Groups,TA/TO,0,24,0,A,A,0,No Deposit,96.0,,0,Transient-Party,8.0,0,0
HB-060421,City Hotel,1,489,2024,November,45,10,2024-11-10,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-079648,City Hotel,0,0,2023,October,44,30,2023-10-30,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,63.0,,0,Transient,85.0,0,0
HB-070310,City Hotel,1,201,2025,June,24,14,2025-06-14,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-094516,City Hotel,0,165,2024,July,31,31,2024-07-31,2,4,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,72.25,0,2
HB-035722,Resort Hotel,0,83,2025,April,18,29,2025-04-29,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,75.0,0,1
HB-077440,City Hotel,1,23,2023,October,40,7,2023-10-07,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,1,0,A,A,1,No Deposit,,,0,Transient,90.0,0,0
HB-010620,Resort Hotel,1,40,2025,March,12,23,2025-03-23,0,2,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,100.0,0,1
HB-015616,Resort Hotel,0,50,2023,July,29,21,2023-07-21,2,6,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,98.75,0,2
HB-062003,City Hotel,1,45,2024,December,1,30,2024-12-30,0,1,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,167.4,0,0
HB-112275,City Hotel,0,123,2025,May,20,16,2025-05-16,1,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,142.8,0,1
HB-108623,City Hotel,0,0,2025,March,13,29,2025-03-29,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,118.0,0,1
HB-015588,Resort Hotel,0,52,2023,July,29,20,2023-07-20,2,5,2,1.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,190.0,0,1
HB-022486,Resort Hotel,0,33,2024,March,13,25,2024-03-25,0,2,3,0.0,0,FB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,,,0,Transient,127.0,0,1
HB-075514,City Hotel,1,355,2023,October,40,7,2023-10-07,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-116883,City Hotel,0,143,2025,July,30,23,2025-07-23,2,1,3,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,9.0,,0,Transient,235.0,0,2
HB-084516,City Hotel,0,5,2024,February,8,24,2024-02-24,0,4,1,0.0,0,BB,NOR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,207.0,0,Transient-Party,80.0,0,0
HB-052548,City Hotel,1,16,2024,June,23,8,2024-06-08,0,1,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,92.65,0,0
HB-099220,City Hotel,0,8,2024,October,41,7,2024-10-07,2,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,179.0,1,2
HB-103274,City Hotel,0,88,2024,December,50,15,2024-12-15,0,3,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,1
HB-113692,City Hotel,0,73,2025,June,23,8,2025-06-08,0,3,1,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,170.0,0,0
HB-009626,Resort Hotel,1,2,2024,December,51,21,2024-12-21,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,146.0,,0,Transient,43.0,0,0
HB-027183,Resort Hotel,0,26,2024,August,34,22,2024-08-22,1,0,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,,,0,Transient,268.5,1,1
HB-096802,City Hotel,0,46,2024,September,36,5,2024-09-05,1,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,102.0,0,1
HB-061130,City Hotel,1,86,2024,December,49,2,2024-12-02,1,2,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,1
HB-113917,City Hotel,0,162,2025,June,24,12,2025-06-12,1,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,157.5,0,2
HB-116574,City Hotel,0,157,2025,July,28,8,2025-07-08,4,10,2,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,152.1,0,1
HB-049236,City Hotel,1,99,2024,April,15,8,2024-04-08,0,2,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient,85.5,0,1
HB-015570,Resort Hotel,0,72,2023,July,29,22,2023-07-22,0,4,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,110.75,0,1
HB-076771,City Hotel,1,395,2024,March,12,21,2024-03-21,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-109985,City Hotel,0,21,2025,April,16,18,2025-04-18,0,2,1,0.0,0,BB,GBR,Online TA,GDS,0,0,0,E,E,0,No Deposit,195.0,,0,Transient,175.0,0,0
HB-099480,City Hotel,0,3,2024,October,41,13,2024-10-13,0,1,1,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient,120.0,0,1
HB-006448,Resort Hotel,1,184,2024,June,24,11,2024-06-11,4,10,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,77.85,0,0
HB-077023,City Hotel,0,10,2023,August,35,28,2023-08-28,1,2,2,0.0,0,BB,AUT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,79.0,0,1
HB-000692,Resort Hotel,0,54,2023,July,30,25,2023-07-25,2,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,147.0,0,0
HB-116570,City Hotel,0,71,2025,July,29,16,2025-07-16,2,4,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,8.0,,0,Transient,120.0,0,1
HB-117581,City Hotel,0,170,2025,August,32,5,2025-08-05,0,1,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.5,0,1
HB-057216,City Hotel,1,296,2024,September,38,21,2024-09-21,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,26.0,,0,Transient-Party,85.0,0,0
HB-051322,City Hotel,1,1,2024,May,20,18,2024-05-18,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,120.0,0,0
HB-007940,Resort Hotel,1,262,2024,September,36,3,2024-09-03,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,81.0,0,2
HB-090722,City Hotel,0,63,2024,June,23,9,2024-06-09,0,1,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,109.0,0,1
HB-014712,Resort Hotel,1,259,2023,September,37,17,2023-09-17,0,3,2,0.0,0,BB,GBR,Groups,Corporate,0,1,0,A,A,0,Non Refund,,223.0,0,Transient,40.05,0,0
HB-067467,City Hotel,1,148,2025,May,18,4,2025-05-04,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,171.0,,0,Transient,95.0,0,0
HB-033296,Resort Hotel,0,73,2025,February,8,17,2025-02-17,1,2,2,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,498.0,0,Transient-Party,44.67,1,0
HB-046247,City Hotel,0,14,2023,December,52,27,2023-12-27,2,2,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient-Party,105.0,0,1
HB-034717,Resort Hotel,0,85,2025,March,13,30,2025-03-30,1,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,40.0,,0,Transient,69.0,0,0
HB-093735,City Hotel,0,136,2024,July,30,23,2024-07-23,2,1,2,0.0,0,BB,BEL,Groups,TA/TO,0,0,0,B,B,0,No Deposit,1.0,,0,Transient,75.0,0,0
HB-069109,City Hotel,1,167,2025,May,21,25,2025-05-25,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,0,Transient,115.0,0,0
HB-009387,Resort Hotel,1,32,2024,November,47,22,2024-11-22,0,1,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,78.0,0,1
HB-049609,City Hotel,1,19,2024,April,16,15,2024-04-15,2,5,3,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,150.43,0,2
HB-061889,City Hotel,1,193,2024,December,52,28,2024-12-28,0,4,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,120.7,0,1
HB-064658,City Hotel,1,28,2025,March,11,14,2025-03-14,0,4,3,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,132.18,0,0
HB-064518,City Hotel,1,207,2025,March,11,11,2025-03-11,2,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.0,0,1
HB-071836,City Hotel,1,25,2025,July,28,13,2025-07-13,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,1
HB-054675,City Hotel,1,133,2024,July,30,23,2024-07-23,0,1,3,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,189.0,0,0
HB-016189,Resort Hotel,0,81,2023,August,32,11,2023-08-11,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,241.0,,0,Transient,118.02,0,1
HB-105675,City Hotel,0,14,2025,February,7,13,2025-02-13,1,0,3,0.0,0,BB,KOR,Direct,Direct,0,0,0,A,D,2,No Deposit,14.0,,0,Transient,98.0,0,1
HB-004293,Resort Hotel,1,118,2024,March,9,2,2024-03-02,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,33.26,0,0
HB-057353,City Hotel,1,254,2024,September,39,24,2024-09-24,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,96.0,0,0
HB-097077,City Hotel,0,12,2024,September,37,11,2024-09-11,1,0,1,0.0,0,BB,CHN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,295.0,,0,Transient-Party,85.0,0,1
HB-059139,City Hotel,1,192,2024,October,43,21,2024-10-21,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,29.0,,0,Transient-Party,95.0,0,0
HB-065733,City Hotel,1,152,2025,April,15,7,2025-04-07,0,2,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,2
HB-092761,City Hotel,0,98,2024,July,28,9,2024-07-09,2,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,103.5,0,1
HB-093243,City Hotel,0,81,2024,July,29,16,2024-07-16,2,1,2,0.0,0,BB,USA,Offline TA/TO,TA/TO,0,0,0,A,A,3,No Deposit,,,0,Transient,96.0,0,0
HB-023313,Resort Hotel,0,2,2024,April,16,21,2024-04-21,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,146.0,,0,Transient,39.0,1,0
HB-000279,Resort Hotel,0,34,2023,July,28,10,2023-07-10,2,5,2,1.0,0,HB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,95.27,0,3
HB-105923,City Hotel,0,7,2025,February,7,12,2025-02-12,2,4,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,138.55,0,2
HB-012841,Resort Hotel,1,247,2025,July,29,19,2025-07-19,1,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,137.7,0,1
HB-078630,City Hotel,1,14,2023,October,41,15,2023-10-15,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,99.0,,0,Transient-Party,100.0,0,0
HB-021325,Resort Hotel,0,2,2024,February,8,25,2024-02-25,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,1,No Deposit,,,0,Transient,45.0,0,0
HB-055711,City Hotel,1,133,2024,August,34,19,2024-08-19,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,85.0,,0,Transient,82.45,0,0
HB-040841,City Hotel,0,0,2023,August,32,8,2023-08-08,1,1,2,0.0,0,BB,BRA,Direct,Direct,0,0,0,D,D,1,No Deposit,,,0,Transient,100.0,0,0
HB-070133,City Hotel,1,38,2025,June,24,10,2025-06-10,2,2,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.0,0,1
HB-116510,City Hotel,0,150,2025,July,29,18,2025-07-18,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,89.1,0,2
HB-031968,Resort Hotel,0,0,2025,January,2,12,2025-01-12,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,44.0,0,0
HB-085172,City Hotel,0,25,2024,March,10,7,2024-03-07,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,87.0,0,0
HB-095281,City Hotel,0,82,2024,August,33,14,2024-08-14,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,112.1,0,1
HB-082232,City Hotel,1,203,2024,June,22,2,2024-06-02,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,41,Transient,65.0,0,0
HB-116744,City Hotel,0,11,2025,July,30,21,2025-07-21,1,2,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,146.0,0,0
HB-053080,City Hotel,1,188,2024,June,24,15,2024-06-15,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,39,Transient,130.0,0,0
HB-093936,City Hotel,0,64,2024,July,30,26,2024-07-26,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.3,0,1
HB-057676,City Hotel,1,10,2024,September,40,30,2024-09-30,0,1,1,0.0,0,BB,PRT,Aviation,Corporate,0,0,0,D,D,0,No Deposit,,153.0,0,Transient,110.0,0,0
HB-049250,City Hotel,0,96,2024,April,15,8,2024-04-08,2,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,88.83,0,1
HB-067038,City Hotel,1,111,2025,April,17,27,2025-04-27,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,0,Transient,120.0,0,0
HB-028314,Resort Hotel,0,240,2024,September,38,18,2024-09-18,4,7,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Contract,53.85,0,1
HB-049019,City Hotel,0,90,2024,April,14,4,2024-04-04,1,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,82.45,0,1
HB-018044,Resort Hotel,0,0,2023,October,43,28,2023-10-28,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,2,No Deposit,,,0,Transient,48.0,0,0
HB-054413,City Hotel,1,18,2024,July,29,15,2024-07-15,0,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,139.0,0,1
HB-013688,Resort Hotel,1,17,2025,August,35,26,2025-08-26,2,4,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,C,C,1,No Deposit,250.0,,0,Transient,262.38,0,0
HB-001606,Resort Hotel,1,323,2023,September,36,5,2023-09-05,4,6,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,175.0,,0,Transient-Party,97.5,0,1
HB-023206,Resort Hotel,0,0,2024,April,16,17,2024-04-17,1,0,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,62.0,1,0
HB-078962,City Hotel,0,3,2024,April,15,11,2024-04-11,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,14,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,1
HB-055220,City Hotel,1,215,2024,August,32,8,2024-08-08,1,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.3,0,1
HB-067329,City Hotel,1,157,2025,May,18,1,2025-05-01,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,130.0,0,0
HB-068977,City Hotel,1,357,2025,May,21,24,2025-05-24,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.8,0,1
HB-059747,City Hotel,1,166,2024,November,44,1,2024-11-01,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,110.0,0,0
HB-021007,Resort Hotel,0,87,2024,February,6,9,2024-02-09,1,5,2,0.0,0,HB,MUS,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,98.0,0,2
HB-065231,City Hotel,1,26,2025,March,13,29,2025-03-29,2,5,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,100.0,0,1
HB-107404,City Hotel,0,49,2025,March,10,9,2025-03-09,1,3,2,0.0,0,SC,KOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,1
HB-069579,City Hotel,1,189,2025,June,23,2,2025-06-02,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-038579,Resort Hotel,0,145,2025,July,28,13,2025-07-13,2,8,2,1.0,0,HB,DEU,Online TA,TA/TO,0,0,0,C,C,1,No Deposit,240.0,,0,Transient,256.0,0,2
HB-025330,Resort Hotel,0,92,2024,June,25,17,2024-06-17,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,118.0,0,1
HB-073727,City Hotel,1,258,2023,July,26,2,2023-07-02,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-067440,City Hotel,1,15,2025,May,18,3,2025-05-03,0,3,2,0.0,0,BB,PHL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,145.0,0,0
HB-050953,City Hotel,1,309,2024,May,19,12,2024-05-12,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-043160,City Hotel,0,76,2023,September,37,16,2023-09-16,0,2,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-077888,City Hotel,0,18,2023,September,39,27,2023-09-27,2,1,1,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,170.0,0,0
HB-099029,City Hotel,0,163,2024,October,40,5,2024-10-05,0,3,1,0.0,0,BB,SWE,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,100.8,0,0
HB-093455,City Hotel,0,50,2024,July,29,20,2024-07-20,0,2,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,F,0,No Deposit,8.0,,0,Transient,157.9,0,2
HB-109713,City Hotel,0,93,2025,April,15,13,2025-04-13,0,3,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,89.1,0,1
HB-036874,Resort Hotel,0,314,2025,May,21,22,2025-05-22,3,7,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Contract,98.2,0,0
HB-046027,City Hotel,1,198,2023,December,49,5,2023-12-05,2,1,2,0.0,0,HB,ESP,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,90.0,0,0
HB-000897,Resort Hotel,1,36,2023,August,31,4,2023-08-04,0,3,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,221.0,0,0
HB-002990,Resort Hotel,0,164,2023,November,45,9,2023-11-09,2,5,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,61.2,1,0
HB-038220,Resort Hotel,0,192,2025,June,26,28,2025-06-28,4,10,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,314.0,,0,Transient,108.56,0,0
HB-110501,City Hotel,0,36,2025,April,17,22,2025-04-22,2,4,2,2.0,0,BB,NLD,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,8.0,,0,Transient,224.0,0,1
HB-070561,City Hotel,1,120,2025,June,25,18,2025-06-18,2,2,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.86,0,1
HB-074451,City Hotel,1,304,2023,August,33,17,2023-08-17,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-008408,Resort Hotel,1,339,2024,September,39,26,2024-09-26,3,6,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,15.0,,0,Transient,80.0,0,0
HB-020641,Resort Hotel,0,0,2024,February,6,5,2024-02-05,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,330.0,,0,Transient-Party,38.0,0,0
HB-020169,Resort Hotel,0,9,2024,January,2,14,2024-01-14,2,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,29.0,0,0
HB-042202,City Hotel,0,63,2023,September,35,2,2023-09-02,0,3,2,0.0,0,BB,BRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,60.0,0,1
HB-100216,City Hotel,0,386,2024,October,43,23,2024-10-23,2,0,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,90.0,0,1
HB-027253,Resort Hotel,0,67,2024,August,32,11,2024-08-11,4,9,2,1.0,0,BB,FRA,Direct,Direct,0,0,0,C,C,1,No Deposit,250.0,,0,Transient,221.62,0,0
HB-108866,City Hotel,0,130,2025,March,14,31,2025-03-31,1,2,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,16.0,,0,Transient,89.1,0,0
HB-037711,Resort Hotel,0,132,2025,June,25,19,2025-06-19,2,5,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,147.43,0,1
HB-068291,City Hotel,1,104,2025,May,20,15,2025-05-15,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,170.0,0,0
HB-088395,City Hotel,0,0,2024,May,18,4,2024-05-04,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,219.0,0,Transient,89.0,0,0
HB-078020,City Hotel,0,12,2023,November,47,25,2023-11-25,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,40.0,0,Transient-Party,65.0,0,1
HB-035650,Resort Hotel,0,252,2025,April,17,22,2025-04-22,2,5,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,D,D,2,No Deposit,273.0,,0,Transient-Party,76.8,0,0
HB-071800,City Hotel,1,171,2025,July,28,12,2025-07-12,0,4,3,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,161.1,0,2
HB-000867,Resort Hotel,1,80,2023,August,31,1,2023-08-01,4,6,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,242.0,,0,Transient,169.0,0,1
HB-042317,City Hotel,0,22,2023,September,36,4,2023-09-04,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,76.81,0,0
HB-005158,Resort Hotel,1,22,2024,April,16,18,2024-04-18,3,7,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,125.0,0,0
HB-092060,City Hotel,0,0,2024,October,40,3,2024-10-03,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,E,0,No Deposit,,238.0,0,Transient,65.0,0,0
HB-010135,Resort Hotel,1,92,2025,February,7,15,2025-02-15,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,39.9,0,1
HB-020290,Resort Hotel,0,1,2024,January,4,22,2024-01-22,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,330.0,,0,Transient-Party,38.0,0,0
HB-044989,City Hotel,1,102,2023,October,42,16,2023-10-16,0,2,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient-Party,80.0,0,0
HB-041789,City Hotel,0,53,2023,August,34,24,2023-08-24,1,1,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-064703,City Hotel,1,92,2025,March,11,15,2025-03-15,0,3,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,85.0,0,0
HB-047196,City Hotel,1,20,2024,February,7,12,2024-02-12,0,2,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.0,0,0
HB-117667,City Hotel,0,57,2025,August,31,2,2025-08-02,2,4,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,126.0,0,0
HB-099208,City Hotel,0,0,2024,October,41,9,2024-10-09,1,0,3,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,77.0,0,0
HB-105754,City Hotel,0,15,2025,February,6,9,2025-02-09,2,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-062313,City Hotel,1,129,2025,January,2,8,2025-01-08,2,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,D,D,0,Non Refund,,,0,Transient,67.0,0,0
HB-071769,City Hotel,1,81,2025,July,28,12,2025-07-12,0,2,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,150.0,0,2
HB-075748,City Hotel,1,312,2023,August,34,25,2023-08-25,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-067962,City Hotel,1,316,2025,May,19,10,2025-05-10,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.8,0,1
HB-010120,Resort Hotel,1,123,2025,February,7,13,2025-02-13,1,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,40.8,0,2
HB-030014,Resort Hotel,0,43,2024,November,45,5,2024-11-05,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,46.8,0,2
HB-016289,Resort Hotel,0,113,2023,August,33,15,2023-08-15,2,5,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,136.0,0,0
HB-046207,City Hotel,0,4,2023,December,52,25,2023-12-25,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.33,0,0
HB-085080,City Hotel,0,2,2024,March,10,7,2024-03-07,1,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,90.0,0,1
HB-047241,City Hotel,0,39,2024,February,7,13,2024-02-13,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,67.5,0,0
HB-040493,City Hotel,0,25,2023,July,30,27,2023-07-27,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-041233,City Hotel,1,0,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-107357,City Hotel,0,4,2025,March,11,10,2025-03-10,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.0,0,2
HB-053394,City Hotel,1,54,2024,June,25,20,2024-06-20,1,0,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,99.9,0,0
HB-113797,City Hotel,0,119,2025,June,23,5,2025-06-05,2,5,1,0.0,0,HB,BEL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,394.0,,0,Transient,100.6,0,1
HB-015007,Resort Hotel,1,244,2023,September,35,3,2023-09-03,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,19,0,A,A,0,Non Refund,,,0,Transient,36.0,0,0
HB-095837,City Hotel,0,4,2024,August,34,24,2024-08-24,0,1,2,0.0,0,SC,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.0,0,1
HB-085372,City Hotel,0,45,2024,March,11,12,2024-03-12,1,1,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,129.6,0,1
HB-045387,City Hotel,0,72,2023,October,43,28,2023-10-28,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,58,Transient-Party,85.67,0,0
HB-110211,City Hotel,0,19,2025,April,16,19,2025-04-19,1,4,2,0.0,0,HB,FRA,Direct,Direct,0,0,0,D,D,1,No Deposit,14.0,,0,Transient,176.0,0,0
HB-097317,City Hotel,0,346,2024,September,37,13,2024-09-13,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-001426,Resort Hotel,0,66,2023,August,35,28,2023-08-28,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,40.0,,0,Transient,97.5,0,0
HB-033787,Resort Hotel,0,0,2025,March,10,3,2025-03-03,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,2,No Deposit,250.0,,0,Transient-Party,60.0,0,0
HB-053987,City Hotel,1,174,2024,July,27,4,2024-07-04,1,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.5,0,0
HB-084366,City Hotel,0,3,2024,March,9,3,2024-03-03,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,40.0,0,Transient,67.0,1,1
HB-057973,City Hotel,1,184,2024,October,40,4,2024-10-04,0,3,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,122.4,0,0
HB-007414,Resort Hotel,1,236,2024,August,32,8,2024-08-08,1,3,2,0.0,1,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,138.0,0,2
HB-016577,Resort Hotel,0,31,2023,August,35,29,2023-08-29,2,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,105.2,0,1
HB-103499,City Hotel,0,20,2024,December,51,22,2024-12-22,1,3,2,1.0,0,BB,ECU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.4,0,0
HB-100874,City Hotel,0,102,2024,October,44,30,2024-10-30,2,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.05,0,2
HB-101446,City Hotel,0,7,2024,November,45,10,2024-11-10,0,2,2,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,0.0,0,0
HB-033946,Resort Hotel,0,0,2025,March,10,7,2025-03-07,0,1,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient-Party,60.0,0,0
HB-057763,City Hotel,1,267,2024,September,40,30,2024-09-30,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,26.0,,0,Transient,95.0,0,0
HB-085633,City Hotel,0,37,2024,March,12,18,2024-03-18,0,1,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,125.1,1,1
HB-035065,Resort Hotel,0,7,2025,April,15,11,2025-04-11,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient-Party,90.0,0,1
HB-034581,Resort Hotel,0,48,2025,March,12,23,2025-03-23,2,5,2,0.0,0,Undefined,FRA,Offline TA/TO,TA/TO,0,0,0,C,C,0,No Deposit,464.0,,0,Transient-Party,70.0,1,1
HB-017857,Resort Hotel,0,113,2023,October,42,18,2023-10-18,2,4,1,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,35.0,0,1
HB-048328,City Hotel,0,78,2024,March,12,20,2024-03-20,2,5,2,1.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,86.32,0,1
HB-117575,City Hotel,0,147,2025,August,31,1,2025-08-01,0,5,3,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,175.5,0,0
HB-071094,City Hotel,1,170,2025,June,26,28,2025-06-28,0,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,0
HB-001347,Resort Hotel,1,74,2023,August,34,25,2023-08-25,1,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,189.67,0,0
HB-052955,City Hotel,1,11,2024,June,24,14,2024-06-14,0,3,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,D,D,0,Non Refund,,51.0,0,Transient,90.0,0,0
HB-030024,Resort Hotel,0,20,2024,November,45,8,2024-11-08,0,4,2,0.0,0,BB,POL,Direct,Direct,0,0,0,E,E,1,No Deposit,250.0,,0,Transient,78.25,1,2
HB-084333,City Hotel,0,0,2024,February,8,22,2024-02-22,1,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,81.0,0,0
HB-016720,Resort Hotel,0,66,2023,August,35,29,2023-08-29,4,7,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,129.58,0,0
HB-059197,City Hotel,1,145,2024,October,43,22,2024-10-22,1,1,2,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,153.0,0,0
HB-003300,Resort Hotel,0,22,2023,December,49,4,2023-12-04,2,2,2,0.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,49.4,0,0
HB-048404,City Hotel,1,251,2024,March,12,22,2024-03-22,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,93,Transient,125.0,0,0
HB-113192,City Hotel,0,203,2025,May,22,31,2025-05-31,0,4,2,0.0,1,BB,NLD,Online TA,TA/TO,0,0,0,A,B,2,No Deposit,7.0,,0,Transient,91.51,0,3
HB-064969,City Hotel,1,56,2025,March,12,21,2025-03-21,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,86.0,,0,Transient,85.0,0,0
HB-089932,City Hotel,0,133,2024,May,21,24,2024-05-24,1,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,127.15,1,1
HB-089525,City Hotel,0,18,2024,May,21,21,2024-05-21,1,1,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,E,1,No Deposit,9.0,,0,Transient,158.0,0,3
HB-090556,City Hotel,0,247,2024,June,23,6,2024-06-06,1,1,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,0
HB-078686,City Hotel,0,31,2023,October,41,11,2023-10-11,2,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Contract,103.5,0,2
HB-027030,Resort Hotel,0,118,2024,August,33,15,2024-08-15,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,151.83,0,1
HB-088450,City Hotel,0,0,2024,May,18,2,2024-05-02,1,3,1,0.0,0,BB,SVN,Aviation,Corporate,0,0,0,A,A,0,No Deposit,,153.0,0,Transient-Party,95.0,0,0
HB-066955,City Hotel,1,110,2025,April,17,26,2025-04-26,1,4,3,0.0,0,SC,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,100.8,0,0
HB-001433,Resort Hotel,0,47,2023,August,35,29,2023-08-29,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,241.0,,0,Transient,103.18,0,1
HB-090919,City Hotel,0,3,2024,June,24,12,2024-06-12,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,100.0,0,0
HB-087499,City Hotel,0,29,2024,April,16,16,2024-04-16,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,102.8,0,1
HB-010113,Resort Hotel,1,42,2025,February,7,13,2025-02-13,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,2
HB-087296,City Hotel,0,5,2024,April,16,16,2024-04-16,0,1,2,0.0,0,BB,IND,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,129.0,0,0
HB-045478,City Hotel,1,99,2023,October,44,30,2023-10-30,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,65.0,0,0
HB-032178,Resort Hotel,0,40,2025,January,3,16,2025-01-16,1,2,1,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,55.0,0,0
HB-109779,City Hotel,0,30,2025,April,16,14,2025-04-14,1,2,3,1.0,0,BB,ITA,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,7.0,,0,Transient,206.52,0,1
HB-103452,City Hotel,0,24,2024,December,51,21,2024-12-21,0,4,2,2.0,0,BB,JPN,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,147.9,0,1
HB-045752,City Hotel,0,98,2023,November,47,23,2023-11-23,1,2,1,0.0,0,BB,IND,Groups,TA/TO,0,0,0,A,D,0,No Deposit,37.0,,0,Transient-Party,70.0,0,0
HB-038155,Resort Hotel,0,154,2025,July,27,6,2025-07-06,1,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,137.5,0,2
HB-091456,City Hotel,0,131,2024,June,25,17,2024-06-17,2,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,105.74,0,1
HB-066871,City Hotel,1,156,2025,April,17,26,2025-04-26,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,100.0,0,0
HB-013158,Resort Hotel,1,187,2025,August,31,2,2025-08-02,4,10,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,168.57,0,0
HB-045045,City Hotel,0,102,2023,October,42,16,2023-10-16,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,G,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-076226,City Hotel,1,165,2023,August,32,8,2023-08-08,2,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,86.0,0,0
HB-052994,City Hotel,1,188,2024,June,24,15,2024-06-15,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,39,Transient,130.0,0,0
HB-095590,City Hotel,0,0,2024,August,34,20,2024-08-20,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,125.0,0,0
HB-031621,Resort Hotel,0,110,2024,December,52,28,2024-12-28,1,4,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,E,E,1,No Deposit,,,0,Transient,148.0,1,1
HB-033445,Resort Hotel,0,149,2025,February,5,2,2025-02-02,6,16,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,240.0,,0,Transient,73.8,0,1
HB-060017,City Hotel,1,305,2024,November,45,4,2024-11-04,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,89.0,0,0
HB-042682,City Hotel,0,69,2023,September,36,9,2023-09-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-067412,City Hotel,1,266,2025,May,18,3,2025-05-03,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,0,Transient,100.0,0,0
HB-014611,Resort Hotel,0,1,2024,June,25,17,2024-06-17,0,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,3,A,A,0,No Deposit,,20.0,0,Transient,0.0,0,0
HB-020303,Resort Hotel,0,3,2024,January,4,23,2024-01-23,0,1,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-096077,City Hotel,0,136,2024,August,35,26,2024-08-26,0,2,1,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.9,0,1
HB-085219,City Hotel,0,96,2024,March,10,6,2024-03-06,2,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,60.0,0,0
HB-038573,Resort Hotel,0,153,2025,July,29,18,2025-07-18,0,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,207.0,0,3
HB-116755,City Hotel,0,423,2025,July,30,22,2025-07-22,1,1,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,95.5,0,0
HB-088381,City Hotel,0,99,2024,April,17,27,2024-04-27,2,6,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,121.0,,0,Transient-Party,80.75,0,1
HB-015381,Resort Hotel,0,151,2023,July,27,7,2023-07-07,0,4,2,2.0,0,HB,PRT,Direct,Direct,0,0,0,G,G,0,No Deposit,,,0,Transient,157.25,0,3
HB-027335,Resort Hotel,0,0,2024,August,35,26,2024-08-26,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,G,G,1,No Deposit,,,0,Transient,221.0,0,0
HB-038482,Resort Hotel,0,118,2025,July,29,15,2025-07-15,2,3,2,0.0,0,BB,ZAF,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient-Party,180.0,0,2
HB-038024,Resort Hotel,0,72,2025,July,27,5,2025-07-05,0,2,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,162.0,1,1
HB-042488,City Hotel,1,55,2023,September,36,6,2023-09-06,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,75.0,0,0
HB-052184,City Hotel,1,112,2024,June,22,1,2024-06-01,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,132.6,0,0
HB-043394,City Hotel,0,74,2023,September,38,18,2023-09-18,0,2,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,87.0,0,0
HB-002968,Resort Hotel,0,17,2023,November,45,8,2023-11-08,2,5,2,0.0,0,BB,FRA,Corporate,Corporate,0,0,0,A,D,1,No Deposit,334.0,281.0,0,Transient-Party,48.0,0,0
HB-048485,City Hotel,1,3,2024,March,12,24,2024-03-24,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,147.67,0,0
HB-115850,City Hotel,0,1,2025,July,28,11,2025-07-11,0,1,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,170.0,0,0
HB-089142,City Hotel,0,5,2024,May,20,15,2024-05-15,2,1,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,115.67,0,1
HB-110044,City Hotel,0,147,2025,April,16,18,2025-04-18,0,3,1,0.0,0,SC,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,15.0,,0,Transient,72.0,0,0
HB-083010,City Hotel,0,0,2024,January,2,12,2024-01-12,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.0,0,0
HB-079863,City Hotel,1,34,2023,December,49,8,2023-12-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,0,Transient,90.0,0,0
HB-082312,City Hotel,1,105,2023,December,52,31,2023-12-31,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Contract,76.5,0,1
HB-084307,City Hotel,0,19,2024,February,8,20,2024-02-20,2,1,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.0,0,1
HB-038660,Resort Hotel,0,20,2025,July,28,13,2025-07-13,4,8,2,0.0,0,SC,GBR,Complementary,Direct,0,0,0,F,I,7,No Deposit,,,0,Transient,0.0,0,1
HB-035786,Resort Hotel,0,0,2025,May,18,1,2025-05-01,1,0,1,0.0,0,HB,IRL,Online TA,TA/TO,1,0,0,A,D,1,No Deposit,240.0,,0,Transient,29.0,0,0
HB-019327,Resort Hotel,0,23,2023,December,49,9,2023-12-09,1,4,2,0.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,49.4,0,0
HB-009266,Resort Hotel,1,13,2024,November,45,6,2024-11-06,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,339.0,,0,Transient,43.2,0,0
HB-028230,Resort Hotel,0,13,2024,September,39,23,2024-09-23,1,2,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,107.4,1,0
HB-102515,City Hotel,0,25,2024,November,48,29,2024-11-29,0,1,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,75.2,0,0
HB-095332,City Hotel,0,161,2024,August,33,16,2024-08-16,0,2,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,6,No Deposit,9.0,,0,Transient-Party,82.35,0,2
HB-096336,City Hotel,0,195,2024,August,35,30,2024-08-30,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,109.8,0,0
HB-055818,City Hotel,1,171,2024,August,34,22,2024-08-22,1,1,3,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,137.7,0,0
HB-084285,City Hotel,0,4,2024,February,8,20,2024-02-20,1,1,2,0.0,0,BB,BRA,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,127.0,0,0
HB-039077,Resort Hotel,0,11,2025,August,31,2,2025-08-02,1,4,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,251.6,1,2
HB-109454,City Hotel,0,2,2025,April,15,11,2025-04-11,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,150.0,0,1
HB-053866,City Hotel,1,179,2024,July,27,1,2024-07-01,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,65.0,0,0
HB-038544,Resort Hotel,0,127,2025,July,29,18,2025-07-18,0,4,2,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,212.0,0,1
HB-016051,Resort Hotel,0,174,2023,August,31,4,2023-08-04,2,7,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,141.1,0,0
HB-096950,City Hotel,0,183,2024,September,36,8,2024-09-08,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,44.0,,0,Transient-Party,110.0,0,1
HB-065092,City Hotel,1,64,2025,March,13,24,2025-03-24,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,85.0,,0,Transient,81.0,0,0
HB-056531,City Hotel,1,426,2024,September,36,8,2024-09-08,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-029841,Resort Hotel,0,28,2024,October,44,31,2024-10-31,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,57.0,,0,Transient,32.31,0,0
HB-078063,City Hotel,0,3,2023,October,39,1,2023-10-01,0,1,1,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Contract,120.0,0,1
HB-089751,City Hotel,0,119,2024,May,21,23,2024-05-23,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,90.0,0,1
HB-068663,City Hotel,1,175,2025,May,21,19,2025-05-19,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,0,Transient,110.0,0,0
HB-032552,Resort Hotel,0,4,2025,January,5,27,2025-01-27,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,68.0,0,3
HB-049678,City Hotel,1,275,2024,April,16,17,2024-04-17,2,0,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,0,Transient,110.0,0,0
HB-070000,City Hotel,1,169,2025,June,23,8,2025-06-08,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,170.0,0,0
HB-084814,City Hotel,0,0,2024,March,9,2,2024-03-02,0,2,1,0.0,0,BB,PRT,Corporate,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,55.0,1,1
HB-061660,City Hotel,1,531,2024,December,51,22,2024-12-22,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-080996,City Hotel,1,101,2024,February,6,11,2024-02-11,1,3,1,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Contract,81.0,0,1
HB-081604,City Hotel,0,0,2024,May,22,30,2024-05-30,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,5,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-116775,City Hotel,0,423,2025,July,30,22,2025-07-22,1,1,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,95.5,0,0
HB-110711,City Hotel,0,225,2025,April,18,29,2025-04-29,1,1,2,0.0,0,HB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,141.0,0,0
HB-081158,City Hotel,0,0,2023,December,48,3,2023-12-03,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,75.0,0,0
HB-018053,Resort Hotel,0,3,2023,October,44,31,2023-10-31,0,1,1,0.0,0,HB,PRT,Complementary,Direct,0,0,0,A,E,0,No Deposit,,,0,Transient,0.0,0,0
HB-093019,City Hotel,0,149,2024,July,28,12,2024-07-12,0,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.45,0,1
HB-024569,Resort Hotel,0,79,2024,May,21,21,2024-05-21,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,80.0,0,0
HB-099044,City Hotel,0,228,2024,October,40,5,2024-10-05,0,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,102.85,0,1
HB-118276,City Hotel,0,105,2025,August,33,13,2025-08-13,2,3,2,0.0,0,SC,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,95.0,0,1
HB-066411,City Hotel,1,90,2025,April,16,19,2025-04-19,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,390.0,,0,Transient-Party,100.0,0,0
HB-015651,Resort Hotel,0,72,2023,July,30,26,2023-07-26,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,157.0,1,1
HB-097199,City Hotel,0,0,2024,September,37,12,2024-09-12,1,0,2,0.0,0,SC,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,150.0,0,0
HB-110351,City Hotel,0,5,2025,April,17,25,2025-04-25,0,1,2,2.0,0,HB,NLD,Direct,Direct,0,0,0,E,E,1,No Deposit,14.0,,0,Transient,275.0,0,1
HB-036388,Resort Hotel,0,115,2025,May,20,17,2025-05-17,0,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,85.0,0,2
HB-019055,Resort Hotel,0,3,2023,December,49,5,2023-12-05,2,1,2,0.0,0,HB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,38.0,,0,Transient-Party,68.0,0,0
HB-088819,City Hotel,0,68,2024,May,19,10,2024-05-10,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient-Party,135.9,1,1
HB-116933,City Hotel,0,69,2025,July,30,25,2025-07-25,0,4,2,0.0,0,BB,CHE,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,117.0,0,0
HB-081543,City Hotel,1,218,2024,June,23,9,2024-06-09,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,133.0,,0,Transient,135.0,0,0
HB-100655,City Hotel,0,35,2024,October,44,28,2024-10-28,1,2,2,0.0,0,BB,TUR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,129.0,0,1
HB-115677,City Hotel,0,95,2025,July,27,6,2025-07-06,0,3,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,1
HB-016572,Resort Hotel,1,247,2023,October,41,9,2023-10-09,1,2,1,0.0,0,FB,ESP,Groups,TA/TO,0,1,0,A,A,0,Non Refund,68.0,,0,Transient,19.0,0,0
HB-080776,City Hotel,1,180,2024,April,15,13,2024-04-13,0,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,21.0,,38,Transient,125.0,0,0
HB-101451,City Hotel,0,3,2024,November,45,10,2024-11-10,0,2,1,0.0,0,BB,BEL,Aviation,Corporate,0,0,0,D,D,0,No Deposit,,153.0,0,Transient-Party,95.0,0,0
HB-018942,Resort Hotel,0,17,2023,November,48,30,2023-11-30,1,3,1,0.0,0,BB,PRT,Groups,Corporate,0,0,0,A,A,0,No Deposit,,343.0,0,Transient-Party,42.0,1,0
HB-043278,City Hotel,0,162,2023,September,37,17,2023-09-17,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,70.0,0,0
HB-020115,Resort Hotel,0,20,2024,January,3,15,2024-01-15,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,348.0,,0,Transient,114.0,0,0
HB-085267,City Hotel,0,16,2024,March,10,10,2024-03-10,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.0,0,1
HB-023014,Resort Hotel,0,1,2024,April,15,12,2024-04-12,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,330.0,,0,Transient,67.5,0,0
HB-013670,Resort Hotel,1,253,2025,August,35,25,2025-08-25,2,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,153.75,0,1
HB-085061,City Hotel,0,1,2024,March,10,8,2024-03-08,0,1,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.0,0,0
HB-051201,City Hotel,1,1,2024,May,20,16,2024-05-16,1,0,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.0,0,0
HB-112337,City Hotel,0,203,2025,May,21,19,2025-05-19,2,2,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,101.38,0,1
HB-109115,City Hotel,0,68,2025,April,14,5,2025-04-05,0,2,2,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,,418.0,0,Transient-Party,110.0,0,0
HB-016496,Resort Hotel,0,199,2023,August,34,24,2023-08-24,2,5,2,0.0,0,HB,IRL,Offline TA/TO,TA/TO,0,0,0,E,E,1,No Deposit,175.0,,0,Transient-Party,142.65,0,1
HB-024450,Resort Hotel,0,86,2024,May,20,18,2024-05-18,0,4,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,D,E,0,No Deposit,75.0,,0,Transient,72.9,0,0
HB-042046,City Hotel,1,104,2023,August,35,30,2023-08-30,2,1,2,0.0,0,HB,ESP,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,90.0,0,0
HB-036205,Resort Hotel,0,118,2025,May,19,6,2025-05-06,2,5,1,1.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,101.71,0,1
HB-107112,City Hotel,0,137,2025,March,10,6,2025-03-06,1,1,3,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,F,0,No Deposit,37.0,,0,Transient-Party,80.0,0,1
HB-061615,City Hotel,1,72,2024,December,51,19,2024-12-19,1,3,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,119.0,0,0
HB-068330,City Hotel,1,22,2025,May,20,15,2025-05-15,1,2,2,0.0,0,BB,ARG,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,163.33,0,0
HB-112633,City Hotel,0,0,2025,May,21,22,2025-05-22,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,171.0,0,0
HB-003476,Resort Hotel,1,93,2023,December,51,19,2023-12-19,0,1,2,0.0,0,FB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,80.0,0,0
HB-108940,City Hotel,0,82,2025,April,14,1,2025-04-01,2,1,0,2.0,0,BB,FRA,Direct,Direct,0,0,0,B,B,0,No Deposit,14.0,,0,Transient-Party,98.55,0,0
HB-005215,Resort Hotel,0,191,2024,April,17,22,2024-04-22,1,2,2,0.0,0,Undefined,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,85.33,0,1
HB-028310,Resort Hotel,0,271,2024,September,38,22,2024-09-22,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,F,0,No Deposit,40.0,,0,Contract,76.5,0,1
HB-034339,Resort Hotel,0,0,2025,March,12,20,2025-03-20,1,0,1,0.0,0,BB,PRT,Direct,Corporate,0,0,0,A,D,0,No Deposit,,329.0,0,Transient,60.0,0,1
HB-090999,City Hotel,0,24,2024,June,24,13,2024-06-13,1,1,1,0.0,0,BB,MLT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.25,0,0
HB-035613,Resort Hotel,0,185,2025,April,17,23,2025-04-23,2,4,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,E,F,3,No Deposit,298.0,,154,Transient-Party,93.0,0,0
HB-044955,City Hotel,1,100,2023,October,42,16,2023-10-16,0,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient,108.0,0,0
HB-078115,City Hotel,0,17,2023,October,39,1,2023-10-01,0,3,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,113.33,0,0
HB-103178,City Hotel,0,83,2024,December,50,11,2024-12-11,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-041267,City Hotel,0,39,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-079589,City Hotel,0,7,2023,October,43,29,2023-10-29,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,65.0,0,0
HB-018390,Resort Hotel,0,11,2023,November,46,16,2023-11-16,1,2,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,5.0,,0,Transient,32.0,0,0
HB-002826,Resort Hotel,0,0,2023,October,44,31,2023-10-31,2,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,G,1,No Deposit,240.0,,0,Transient,69.0,0,1
HB-079456,City Hotel,1,137,2024,January,4,27,2024-01-27,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,29.0,,45,Transient,70.0,0,0
HB-084652,City Hotel,0,115,2024,February,9,27,2024-02-27,2,2,1,0.0,0,BB,MOZ,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,134.0,,0,Transient-Party,76.0,0,0
HB-110824,City Hotel,0,140,2025,April,18,28,2025-04-28,2,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,119.0,,0,Transient-Party,130.0,0,1
HB-080284,City Hotel,1,125,2024,February,8,21,2024-02-21,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,B,B,0,No Deposit,9.0,,0,Contract,81.0,0,1
HB-109822,City Hotel,0,16,2025,April,16,14,2025-04-14,1,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,138.33,0,1
HB-025724,Resort Hotel,0,171,2024,July,27,2,2024-07-02,2,5,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,94.94,0,3
HB-060578,City Hotel,1,280,2024,November,46,16,2024-11-16,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,91.8,0,1
HB-111787,City Hotel,0,91,2025,May,20,14,2025-05-14,1,0,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,108.0,0,4
HB-039746,Resort Hotel,0,220,2025,August,34,23,2025-08-23,0,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,123.77,0,1
HB-081104,City Hotel,1,82,2024,February,5,2,2024-02-02,0,5,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,21,Transient,96.0,0,0
HB-091094,City Hotel,0,11,2024,June,24,14,2024-06-14,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,D,D,0,No Deposit,,51.0,0,Transient-Party,90.0,0,0
HB-030240,Resort Hotel,0,0,2024,November,46,17,2024-11-17,0,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,53.4,0,0
HB-072582,City Hotel,1,184,2025,July,31,31,2025-07-31,1,5,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,175.5,0,1
HB-087893,City Hotel,0,39,2024,April,16,21,2024-04-21,2,5,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,117.98,0,1
HB-039584,Resort Hotel,0,226,2025,August,34,19,2025-08-19,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,F,1,No Deposit,240.0,,0,Transient,194.0,0,2
HB-091009,City Hotel,0,208,2024,June,24,11,2024-06-11,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,83.0,,0,Contract,80.24,0,2
HB-016585,Resort Hotel,0,26,2023,September,35,1,2023-09-01,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,146.0,0,2
HB-024452,Resort Hotel,0,117,2024,May,20,15,2024-05-15,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Contract,37.4,0,0
HB-073790,City Hotel,1,279,2023,July,29,23,2023-07-23,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-043572,City Hotel,0,13,2023,September,38,20,2023-09-20,2,0,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,87.78,0,1
HB-025266,Resort Hotel,0,154,2024,July,29,20,2024-07-20,2,4,2,2.0,0,BB,PRT,Direct,Direct,0,0,0,G,G,2,No Deposit,250.0,,0,Transient,227.0,0,0
HB-103252,City Hotel,0,9,2024,December,51,16,2024-12-16,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,98.0,0,0
HB-018456,Resort Hotel,1,17,2023,November,48,30,2023-11-30,1,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,,,0,Transient-Party,36.0,0,0
HB-038003,Resort Hotel,0,0,2025,July,27,5,2025-07-05,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,123.0,0,0
HB-083608,City Hotel,0,73,2024,February,5,4,2024-02-04,1,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,65.75,0,0
HB-061162,City Hotel,1,10,2024,December,49,2,2024-12-02,3,7,1,0.0,0,BB,AGO,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.59,0,0
HB-113420,City Hotel,0,41,2025,June,23,4,2025-06-04,2,1,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,153.33,0,2
HB-014000,Resort Hotel,0,113,2024,June,26,25,2024-06-25,4,6,1,0.0,0,BB,PRT,Direct,Direct,0,0,2,A,A,3,No Deposit,,,0,Transient,66.0,0,1
HB-032728,Resort Hotel,0,39,2025,January,5,31,2025-01-31,0,4,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient,34.0,0,0
HB-019700,Resort Hotel,0,304,2023,December,52,31,2023-12-31,0,2,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,171.0,,0,Transient,89.55,0,0
HB-054434,City Hotel,1,200,2024,July,29,15,2024-07-15,3,7,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.95,0,1
HB-087063,City Hotel,0,65,2024,April,15,11,2024-04-11,1,2,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,9.0,,0,Transient,137.7,0,1
HB-103142,City Hotel,0,6,2024,December,50,12,2024-12-12,1,0,1,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,1
HB-013098,Resort Hotel,1,172,2025,July,31,31,2025-07-31,1,4,2,0.0,0,HB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,212.0,0,0
HB-092664,City Hotel,0,28,2024,July,27,7,2024-07-07,0,3,2,0.0,0,SC,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,134.37,0,1
HB-013080,Resort Hotel,1,359,2025,July,31,30,2025-07-30,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,165.6,0,0
HB-062288,City Hotel,1,2,2025,January,2,8,2025-01-08,2,0,2,0.0,0,HB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.5,0,0
HB-064649,City Hotel,1,53,2025,March,11,14,2025-03-14,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,94.0,,0,Transient-Party,65.0,0,0
HB-010711,Resort Hotel,1,21,2025,March,13,27,2025-03-27,1,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,77.5,0,2
HB-009044,Resort Hotel,1,71,2024,October,43,24,2024-10-24,2,5,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,61.2,0,0
HB-084569,City Hotel,0,6,2024,February,8,24,2024-02-24,0,4,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,109.5,0,1
HB-113489,City Hotel,0,31,2025,June,23,4,2025-06-04,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,160.0,0,1
HB-116669,City Hotel,0,148,2025,July,29,18,2025-07-18,0,5,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient-Party,147.78,0,1
HB-041759,City Hotel,0,0,2023,August,34,23,2023-08-23,1,0,1,0.0,0,BB,UKR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,80.0,0,0
HB-097897,City Hotel,0,145,2024,September,38,19,2024-09-19,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,3.0,,0,Transient,80.75,0,0
HB-089620,City Hotel,0,11,2024,May,21,22,2024-05-22,2,0,2,1.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,159.0,0,3
HB-099690,City Hotel,0,377,2024,October,42,14,2024-10-14,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-028958,Resort Hotel,0,364,2024,October,41,12,2024-10-12,1,4,1,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,1,No Deposit,,223.0,0,Transient-Party,60.0,0,0
HB-018829,Resort Hotel,0,4,2023,November,48,27,2023-11-27,1,2,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient-Party,98.0,0,0
HB-071537,City Hotel,1,270,2025,July,28,7,2025-07-07,0,2,2,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,154.8,0,1
HB-084113,City Hotel,0,4,2024,February,8,19,2024-02-19,0,1,1,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,A,0,No Deposit,,67.0,0,Transient-Party,81.0,0,0
HB-043152,City Hotel,0,27,2023,September,37,16,2023-09-16,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,105.0,0,1
HB-105710,City Hotel,0,35,2025,February,7,11,2025-02-11,2,2,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,125.8,0,1
HB-007916,Resort Hotel,1,121,2024,September,36,2,2024-09-02,1,2,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,199.0,0,0
HB-069737,City Hotel,1,247,2025,June,23,5,2025-06-05,1,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,1
HB-080019,City Hotel,0,40,2023,November,45,7,2023-11-07,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,F,0,No Deposit,28.0,,0,Group,60.0,0,0
HB-103806,City Hotel,0,6,2024,December,52,28,2024-12-28,0,4,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,104.2,0,1
HB-031492,Resort Hotel,0,30,2024,December,52,28,2024-12-28,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,65.0,0,0
HB-116014,City Hotel,0,261,2025,July,28,12,2025-07-12,0,2,3,0.0,0,BB,SRB,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,156.6,0,1
HB-000242,Resort Hotel,0,77,2023,July,27,9,2023-07-09,2,3,2,0.0,0,BB,POL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient,65.5,0,0
HB-112822,City Hotel,0,246,2025,May,22,27,2025-05-27,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,128.0,0,1
HB-019533,Resort Hotel,0,4,2023,December,51,24,2023-12-24,0,2,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,C,2,No Deposit,240.0,,0,Transient,70.0,0,2
HB-009624,Resort Hotel,1,0,2024,December,51,21,2024-12-21,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,43.0,0,0
HB-046992,City Hotel,1,28,2024,February,5,1,2024-02-01,5,10,2,2.0,0,BB,AGO,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,152.53,0,0
HB-106468,City Hotel,0,134,2025,February,9,25,2025-02-25,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,75.0,0,0
HB-099224,City Hotel,0,34,2024,October,41,7,2024-10-07,2,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,153.0,0,2
HB-037939,Resort Hotel,0,212,2025,July,27,4,2025-07-04,1,5,2,0.0,0,HB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,140.0,0,1
HB-111478,City Hotel,0,10,2025,May,19,7,2025-05-07,2,2,2,0.0,0,BB,AUT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,108.9,0,0
HB-023050,Resort Hotel,0,61,2024,April,15,9,2024-04-09,2,3,3,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,C,2,No Deposit,314.0,,0,Transient,62.64,0,0
HB-012409,Resort Hotel,1,310,2025,June,26,27,2025-06-27,2,5,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,155.43,0,1
HB-024506,Resort Hotel,0,6,2024,May,21,23,2024-05-23,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,83.0,0,Transient,42.0,0,0
HB-003484,Resort Hotel,1,93,2023,December,51,19,2023-12-19,0,1,2,0.0,0,FB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,80.0,0,0
HB-009824,Resort Hotel,1,86,2025,January,2,7,2025-01-07,1,1,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,56.4,0,2
HB-080323,City Hotel,1,33,2023,December,49,9,2023-12-09,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,44.0,,0,Transient,110.0,0,0
HB-074212,City Hotel,1,363,2023,October,41,15,2023-10-15,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-006322,Resort Hotel,1,182,2024,June,23,3,2024-06-03,1,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,248.0,,0,Transient,97.3,0,0
HB-098794,City Hotel,0,36,2024,October,40,3,2024-10-03,1,1,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,148.5,1,2
HB-020410,Resort Hotel,0,0,2024,January,4,27,2024-01-27,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,45.0,0,0
HB-033735,Resort Hotel,0,0,2025,February,9,28,2025-02-28,0,2,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,65.5,0,0
HB-069508,City Hotel,1,174,2025,June,22,1,2025-06-01,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,0,Transient,100.0,0,0
HB-091255,City Hotel,0,22,2024,June,25,17,2024-06-17,0,2,2,0.0,0,BB,DNK,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,141.0,0,1
HB-039213,Resort Hotel,0,3,2025,August,32,6,2025-08-06,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,224.0,0,2
HB-086603,City Hotel,0,13,2024,April,14,4,2024-04-04,1,1,1,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,86.0,,0,Transient,76.0,0,0
HB-040207,City Hotel,1,82,2023,July,28,16,2023-07-16,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,0
HB-003602,Resort Hotel,1,0,2023,December,52,25,2023-12-25,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,Non Refund,240.0,,0,Transient,55.0,0,0
HB-007471,Resort Hotel,1,12,2024,August,32,11,2024-08-11,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,224.0,0,0
HB-112900,City Hotel,0,231,2025,May,22,26,2025-05-26,2,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.1,0,2
HB-101019,City Hotel,0,22,2024,November,44,1,2024-11-01,0,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,K,0,No Deposit,9.0,,0,Transient,111.0,1,2
HB-084377,City Hotel,0,9,2024,February,8,22,2024-02-22,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,91.0,0,1
HB-069341,City Hotel,1,25,2025,May,22,30,2025-05-30,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,90.0,0,0
HB-111362,City Hotel,0,0,2025,May,19,9,2025-05-09,0,1,1,0.0,0,SC,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,15.0,,0,Transient,104.0,0,0
HB-026008,Resort Hotel,0,20,2024,July,28,11,2024-07-11,2,5,2,0.0,0,BB,EST,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,164.71,0,1
HB-021368,Resort Hotel,0,2,2024,February,9,26,2024-02-26,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-020865,Resort Hotel,0,0,2024,February,6,11,2024-02-11,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient-Party,50.0,0,0
HB-021826,Resort Hotel,0,81,2024,March,10,9,2024-03-09,0,3,2,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,E,G,0,No Deposit,115.0,,0,Transient-Party,93.0,0,0
HB-074325,City Hotel,1,262,2023,July,27,6,2023-07-06,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Contract,62.0,0,0
HB-048247,City Hotel,1,393,2024,March,12,19,2024-03-19,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,70.53,0,0
HB-034506,Resort Hotel,0,326,2025,March,12,20,2025-03-20,2,5,2,0.0,0,HB,NLD,Direct,Direct,0,0,0,E,I,1,No Deposit,250.0,,0,Transient,91.8,0,2
HB-050168,City Hotel,1,68,2024,April,17,24,2024-04-24,2,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,108.38,0,1
HB-019839,Resort Hotel,0,28,2024,January,1,2,2024-01-02,2,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,56.33,1,1
HB-019405,Resort Hotel,0,0,2023,December,50,17,2023-12-17,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,1,No Deposit,,,0,Transient,38.0,0,0
HB-066210,City Hotel,1,87,2025,April,16,15,2025-04-15,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,95.0,0,0
HB-006992,Resort Hotel,1,143,2024,July,29,15,2024-07-15,2,7,2,2.0,1,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,12.0,0,0
HB-075792,City Hotel,1,323,2023,September,36,5,2023-09-05,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-057181,City Hotel,1,123,2024,September,38,20,2024-09-20,1,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,143.1,0,1
HB-062565,City Hotel,1,12,2025,January,3,14,2025-01-14,2,6,3,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,114.28,0,2
HB-001469,Resort Hotel,0,41,2023,August,35,31,2023-08-31,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,120.33,0,1
HB-024600,Resort Hotel,0,49,2024,May,21,25,2024-05-25,0,1,2,0.0,0,BB,USA,Offline TA/TO,TA/TO,0,0,0,F,F,0,No Deposit,360.0,,0,Transient-Party,105.0,0,1
HB-014631,Resort Hotel,0,63,2023,September,35,1,2023-09-01,0,4,2,1.0,0,HB,PRT,Direct,Direct,0,0,0,A,C,0,No Deposit,,,0,Transient,142.5,0,1
HB-014541,Resort Hotel,0,0,2023,December,51,21,2023-12-21,1,0,2,0.0,0,BB,,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,69.0,1,0
HB-071463,City Hotel,1,9,2025,July,27,6,2025-07-06,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.0,0,1
HB-100918,City Hotel,0,6,2024,October,44,30,2024-10-30,2,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,102.41,0,1
HB-095893,City Hotel,0,4,2024,November,44,1,2024-11-01,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,5,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,1
HB-067012,City Hotel,1,111,2025,April,17,27,2025-04-27,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,0,Transient,120.0,0,0
HB-054937,City Hotel,1,173,2024,July,31,31,2024-07-31,2,2,2,1.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.75,0,2
HB-083316,City Hotel,0,59,2024,January,4,28,2024-01-28,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,87.0,,0,Transient-Party,80.0,0,0
HB-071054,City Hotel,1,141,2025,June,26,27,2025-06-27,2,5,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,130.0,0,0
HB-010887,Resort Hotel,1,124,2025,April,15,9,2025-04-09,2,5,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,492.0,,0,Transient,80.0,0,0
HB-067556,City Hotel,1,129,2025,May,18,4,2025-05-04,0,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-080235,City Hotel,0,1,2023,November,46,14,2023-11-14,0,1,1,0.0,0,BB,ITA,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,144.0,0,Transient-Party,79.0,0,0
HB-102470,City Hotel,0,1,2024,November,48,28,2024-11-28,1,0,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.0,1,1
HB-018483,Resort Hotel,0,0,2023,November,47,23,2023-11-23,1,0,1,0.0,0,HB,PRT,Corporate,Corporate,1,0,1,A,D,1,No Deposit,,20.0,0,Transient-Party,42.0,0,0
HB-097151,City Hotel,0,24,2024,September,37,11,2024-09-11,2,0,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,142.0,1,1
HB-079198,City Hotel,0,14,2023,October,42,19,2023-10-19,1,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,92.17,0,1
HB-030646,Resort Hotel,0,0,2024,November,48,29,2024-11-29,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient-Party,43.0,0,0
HB-039115,Resort Hotel,0,23,2025,August,32,5,2025-08-05,2,1,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,242.84,0,0
HB-010907,Resort Hotel,1,124,2025,April,15,9,2025-04-09,2,5,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,C,1,Non Refund,492.0,,0,Transient,80.0,0,0
HB-086193,City Hotel,0,81,2024,March,13,25,2024-03-25,2,2,2,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,4,Transient-Party,69.5,0,0
HB-002998,Resort Hotel,0,36,2023,November,45,10,2023-11-10,0,5,2,1.0,0,BB,ESP,Direct,Direct,0,0,0,A,D,2,No Deposit,250.0,,0,Transient,73.2,1,0
HB-076389,City Hotel,0,273,2023,July,29,17,2023-07-17,0,2,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,87.0,0,0
HB-043384,City Hotel,0,74,2023,September,38,18,2023-09-18,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-115596,City Hotel,0,162,2025,July,27,3,2025-07-03,1,4,3,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,9.0,,0,Transient,179.1,0,2
HB-092422,City Hotel,0,10,2024,July,27,3,2024-07-03,2,1,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,166.0,0,1
HB-023459,Resort Hotel,0,15,2024,April,17,23,2024-04-23,2,1,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,93.67,0,1
HB-079871,City Hotel,1,34,2023,December,49,8,2023-12-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,0,Transient,90.0,0,0
HB-114187,City Hotel,0,132,2025,June,24,14,2025-06-14,0,4,3,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,209.7,0,2
HB-119041,City Hotel,0,23,2025,August,35,27,2025-08-27,1,0,2,0.0,0,BB,BGR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.1,0,1
HB-027532,Resort Hotel,0,24,2024,August,34,25,2024-08-25,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Transient,82.0,0,0
HB-095824,City Hotel,0,85,2024,August,34,19,2024-08-19,2,4,3,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,210.6,0,1
HB-029476,Resort Hotel,0,1,2024,October,43,27,2024-10-27,0,2,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,70.0,0,0
HB-092131,City Hotel,0,152,2024,June,26,27,2024-06-27,1,3,2,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.95,0,1
HB-107851,City Hotel,0,222,2025,March,12,18,2025-03-18,0,1,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,115.2,1,2
HB-000437,Resort Hotel,0,50,2023,July,28,16,2023-07-16,0,1,2,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,241.0,,0,Transient,123.2,0,0
HB-103454,City Hotel,0,3,2024,December,51,21,2024-12-21,0,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,82.88,0,1
HB-093150,City Hotel,0,90,2024,July,29,17,2024-07-17,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,94.5,0,0
HB-016033,Resort Hotel,0,94,2023,August,32,8,2023-08-08,2,2,2,0.0,1,HB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,206.0,1,1
HB-106852,City Hotel,0,212,2025,February,9,28,2025-02-28,0,4,2,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.3,0,1
HB-089234,City Hotel,0,64,2024,May,20,17,2024-05-17,0,2,1,0.0,0,BB,ESP,Corporate,TA/TO,0,0,0,A,A,0,No Deposit,,218.0,0,Transient-Party,130.0,0,1
HB-117617,City Hotel,0,0,2025,August,32,6,2025-08-06,1,0,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,170.0,0,0
HB-099300,City Hotel,0,1,2024,October,41,11,2024-10-11,0,1,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,153.0,0,2
HB-015980,Resort Hotel,0,213,2023,August,31,3,2023-08-03,2,5,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,175.0,,0,Transient,96.3,0,1
HB-091817,City Hotel,0,191,2024,June,25,23,2024-06-23,0,3,1,0.0,0,BB,SRB,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,34.0,,0,Transient-Party,95.0,0,0
HB-089776,City Hotel,0,13,2024,May,21,23,2024-05-23,1,2,2,1.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,7.0,,0,Transient,105.11,0,2
HB-103029,City Hotel,0,1,2024,December,49,6,2024-12-06,0,5,2,1.0,0,BB,ESP,Direct,Direct,0,0,0,E,E,1,No Deposit,14.0,,0,Transient,104.05,0,1
HB-010956,Resort Hotel,1,66,2025,April,15,13,2025-04-13,0,3,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,132.0,0,0
HB-055365,City Hotel,1,398,2024,August,32,11,2024-08-11,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-023436,Resort Hotel,0,9,2024,April,17,23,2024-04-23,1,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient-Party,100.5,1,1
HB-014282,Resort Hotel,0,2,2024,October,40,2,2024-10-02,2,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,5,A,A,0,No Deposit,250.0,,0,Transient,81.0,0,1
HB-008875,Resort Hotel,1,224,2024,October,42,17,2024-10-17,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,62.29,0,0
HB-034868,Resort Hotel,0,26,2025,April,14,4,2025-04-04,0,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient-Party,105.0,0,2
HB-094785,City Hotel,0,171,2024,August,32,6,2024-08-06,2,2,2,1.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.75,0,2
HB-102475,City Hotel,0,130,2024,November,48,26,2024-11-26,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,132.0,,0,Transient,68.0,0,0
HB-067322,City Hotel,1,157,2025,May,18,1,2025-05-01,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,130.0,0,0
HB-043554,City Hotel,0,25,2023,September,38,19,2023-09-19,2,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,118.15,0,1
HB-098585,City Hotel,0,328,2024,September,40,30,2024-09-30,0,2,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,38,Transient-Party,65.0,0,1
HB-061088,City Hotel,1,125,2024,December,48,1,2024-12-01,2,3,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,7.0,,0,Transient,132.67,0,0
HB-069745,City Hotel,1,265,2025,June,23,5,2025-06-05,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,136.75,0,1
HB-115601,City Hotel,0,273,2025,July,27,4,2025-07-04,0,4,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,89.1,0,1
HB-114220,City Hotel,0,1,2025,June,25,16,2025-06-16,0,2,2,0.0,0,BB,PER,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,190.0,0,1
HB-090243,City Hotel,0,1,2024,June,23,3,2024-06-03,0,1,2,0.0,0,BB,HRV,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,139.0,0,0
HB-109042,City Hotel,0,0,2025,April,14,5,2025-04-05,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,150.0,0,3
HB-048257,City Hotel,1,393,2024,March,12,19,2024-03-19,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,70.53,0,0
HB-068777,City Hotel,1,113,2025,May,21,20,2025-05-20,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,34.0,,0,Transient,190.0,0,0
HB-113215,City Hotel,0,21,2025,June,23,3,2025-06-03,0,1,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,209.0,0,2
HB-096185,City Hotel,0,231,2024,August,34,23,2024-08-23,2,5,3,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,96.9,0,2
HB-094039,City Hotel,0,4,2024,July,30,27,2024-07-27,0,3,3,0.0,0,BB,JPN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,177.0,1,1
HB-005708,Resort Hotel,1,468,2024,May,19,12,2024-05-12,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,249.0,,0,Transient-Party,67.0,0,0
HB-104487,City Hotel,0,55,2025,January,3,14,2025-01-14,0,1,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.6,0,2
HB-112138,City Hotel,0,175,2025,May,20,17,2025-05-17,0,3,3,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,7.0,,0,Transient,168.89,0,0
HB-012455,Resort Hotel,1,162,2025,June,27,30,2025-06-30,2,4,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,180.0,0,1
HB-055094,City Hotel,1,178,2024,August,31,4,2024-08-04,0,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,108.3,0,0
HB-051383,City Hotel,1,316,2024,May,20,19,2024-05-19,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-013939,Resort Hotel,0,245,2023,September,35,3,2023-09-03,4,12,2,0.0,0,BB,GBR,Direct,Direct,0,0,1,E,E,0,No Deposit,,,0,Transient,70.0,0,0
HB-004133,Resort Hotel,1,192,2024,February,7,15,2024-02-15,1,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,50.4,0,3
HB-008016,Resort Hotel,1,211,2024,September,36,7,2024-09-07,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,D,D,0,Non Refund,1.0,,0,Transient,89.0,0,0
HB-078136,City Hotel,0,12,2023,October,40,4,2023-10-04,1,0,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,3.0,,0,Transient-Party,72.0,0,0
HB-056819,City Hotel,1,73,2024,September,37,15,2024-09-15,0,1,2,0.0,0,SC,PRT,Corporate,Corporate,0,0,0,A,A,0,Non Refund,,233.0,0,Transient,100.0,0,1
HB-017954,Resort Hotel,0,41,2023,October,42,18,2023-10-18,4,6,2,1.0,0,BB,FRA,Direct,Direct,0,0,0,C,H,0,No Deposit,,,0,Transient-Party,66.0,0,1
HB-009652,Resort Hotel,1,99,2024,December,52,23,2024-12-23,2,2,1,0.0,0,BB,BLR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,37.4,0,0
HB-063365,City Hotel,1,45,2025,February,6,9,2025-02-09,2,5,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,115.6,0,0
HB-043765,City Hotel,0,86,2023,September,38,24,2023-09-24,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,105.0,0,1
HB-080602,City Hotel,0,5,2025,February,5,1,2025-02-01,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,2,6,A,A,0,No Deposit,,40.0,0,Transient,67.0,1,0
HB-051034,City Hotel,1,309,2024,May,20,13,2024-05-13,1,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,215,Transient-Party,101.0,0,0
HB-013987,Resort Hotel,0,7,2024,November,46,15,2024-11-15,0,1,1,0.0,0,BB,,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,171.0,,0,Transient,30.0,0,0
HB-068173,City Hotel,1,68,2025,May,20,14,2025-05-14,2,1,1,0.0,0,BB,PRT,Groups,Corporate,0,0,0,A,A,1,No Deposit,,169.0,0,Transient-Party,110.0,0,0
HB-100909,City Hotel,0,41,2024,November,44,2,2024-11-02,0,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,118.0,0,0
HB-066602,City Hotel,1,393,2025,April,17,22,2025-04-22,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-081588,City Hotel,1,197,2024,June,23,3,2024-06-03,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,21.0,,25,Transient,80.0,0,0
HB-034429,Resort Hotel,0,46,2025,March,12,20,2025-03-20,1,4,1,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,91.0,,0,Transient-Party,50.5,0,0
HB-039576,Resort Hotel,0,227,2025,August,33,16,2025-08-16,2,4,2,2.0,0,HB,PRT,Direct,Direct,0,0,0,G,G,0,No Deposit,250.0,,0,Transient,276.6,0,1
HB-036795,Resort Hotel,0,129,2025,May,21,25,2025-05-25,1,3,3,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,H,H,1,No Deposit,240.0,,0,Transient,160.0,0,0
HB-048316,City Hotel,1,65,2024,March,12,20,2024-03-20,2,2,2,2.0,0,BB,ITA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,161.5,0,0
HB-100098,City Hotel,0,25,2024,October,42,20,2024-10-20,0,3,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.0,0,1
HB-032189,Resort Hotel,0,40,2025,January,3,16,2025-01-16,1,2,1,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,A,D,1,No Deposit,,,0,Transient-Party,55.0,0,0
HB-008586,Resort Hotel,1,383,2024,October,40,6,2024-10-06,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,315.0,,0,Transient-Party,48.0,0,0
HB-046136,City Hotel,0,1,2023,December,50,14,2023-12-14,1,0,1,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,81.0,0,0
HB-050904,City Hotel,1,52,2024,May,19,11,2024-05-11,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,140.4,0,0
HB-004987,Resort Hotel,1,212,2024,April,15,11,2024-04-11,2,5,2,0.0,0,HB,PRT,Groups,Direct,0,0,0,D,D,0,Non Refund,273.0,,0,Transient,76.05,0,0
HB-062558,City Hotel,1,18,2025,January,3,14,2025-01-14,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,82.88,0,0
HB-118710,City Hotel,0,116,2025,August,34,21,2025-08-21,1,3,1,0.0,0,BB,FIN,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,98.0,,0,Transient-Party,125.0,0,0
HB-078009,City Hotel,0,1,2023,September,39,29,2023-09-29,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,92.0,,0,Transient-Party,85.0,0,0
HB-060610,City Hotel,1,496,2024,November,46,17,2024-11-17,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,51.4,0,0
HB-100578,City Hotel,0,229,2024,October,43,27,2024-10-27,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,70.44,0,2
HB-040820,City Hotel,0,0,2023,August,32,8,2023-08-08,0,1,2,0.0,0,BB,CHE,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Group,75.0,0,0
HB-050935,City Hotel,1,309,2024,May,19,12,2024-05-12,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,59.0,0,0
HB-103917,City Hotel,0,4,2024,December,52,29,2024-12-29,1,3,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,122.48,0,1
HB-018712,Resort Hotel,0,5,2023,November,47,22,2023-11-22,2,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,E,0,No Deposit,115.0,,0,Transient,41.3,0,0
HB-062426,City Hotel,1,29,2025,January,3,13,2025-01-13,0,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,0
HB-020777,Resort Hotel,0,3,2024,February,6,6,2024-02-06,2,1,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,241.0,,0,Transient,36.96,0,0
HB-104179,City Hotel,0,52,2025,January,2,6,2025-01-06,0,1,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,127.8,0,2
HB-050386,City Hotel,1,133,2024,April,18,29,2024-04-29,1,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.5,0,0
HB-038146,Resort Hotel,0,272,2025,July,27,6,2025-07-06,1,3,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,6.0,,0,Transient,138.6,0,2
HB-071599,City Hotel,1,120,2025,July,28,8,2025-07-08,2,3,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,198.0,0,0
HB-065046,City Hotel,1,622,2025,March,12,23,2025-03-23,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-028414,Resort Hotel,0,28,2024,September,39,26,2024-09-26,2,5,3,1.0,0,HB,FRA,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,242.57,1,1
HB-088475,City Hotel,0,154,2024,May,18,3,2024-05-03,0,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,89.25,0,0
HB-038414,Resort Hotel,0,103,2025,July,28,13,2025-07-13,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,2,No Deposit,241.0,,0,Transient,188.4,0,1
HB-031518,Resort Hotel,0,78,2024,December,52,24,2024-12-24,2,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,240.0,,0,Transient,58.04,0,1
HB-083847,City Hotel,0,7,2024,February,7,13,2024-02-13,0,1,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,127.0,0,1
HB-067055,City Hotel,1,46,2025,April,18,28,2025-04-28,0,1,1,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,0
HB-056420,City Hotel,1,226,2024,September,36,5,2024-09-05,1,2,3,0.0,0,BB,BRA,Direct,Direct,0,0,0,F,F,0,No Deposit,14.0,,0,Transient,172.8,0,0
HB-112594,City Hotel,0,208,2025,May,21,24,2025-05-24,0,2,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,114.4,0,0
HB-116677,City Hotel,0,186,2025,July,30,22,2025-07-22,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,B,0,No Deposit,22.0,,0,Transient,89.0,0,1
HB-062656,City Hotel,1,54,2025,January,3,18,2025-01-18,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,171.0,,0,Transient,65.0,0,0
HB-087236,City Hotel,0,29,2024,April,15,14,2024-04-14,0,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,102.0,0,1
HB-031394,Resort Hotel,0,73,2024,December,52,23,2024-12-23,2,2,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient-Party,87.9,1,1
HB-017097,Resort Hotel,0,262,2023,September,38,21,2023-09-21,1,3,2,0.0,0,HB,BEL,Groups,Corporate,0,0,0,A,A,0,No Deposit,183.0,,0,Transient-Party,89.2,0,0
HB-077721,City Hotel,0,6,2023,September,38,24,2023-09-24,0,1,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,20.0,,0,Transient,77.0,0,0
HB-118490,City Hotel,0,323,2025,August,34,18,2025-08-18,1,2,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,1
HB-059016,City Hotel,1,468,2024,October,42,20,2024-10-20,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-063845,City Hotel,1,21,2025,February,8,23,2025-02-23,0,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,118.0,0,0
HB-037672,Resort Hotel,0,35,2025,June,25,22,2025-06-22,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,162.83,0,1
HB-077729,City Hotel,0,1,2023,September,38,22,2023-09-22,0,3,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,D,E,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-033856,Resort Hotel,0,7,2025,March,9,2,2025-03-02,1,3,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,D,D,0,No Deposit,,223.0,0,Transient-Party,47.0,0,0
HB-083567,City Hotel,0,4,2024,February,6,5,2024-02-05,0,2,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,1,2
HB-097827,City Hotel,0,27,2024,September,38,17,2024-09-17,2,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,128.28,0,0
HB-113995,City Hotel,0,15,2025,June,24,14,2025-06-14,0,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,150.0,0,2
HB-097857,City Hotel,0,27,2024,September,38,20,2024-09-20,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,288.0,,0,Transient-Party,95.0,0,0
HB-038364,Resort Hotel,0,132,2025,July,28,10,2025-07-10,1,5,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,15.0,,0,Transient,164.4,0,1
HB-005349,Resort Hotel,0,189,2024,April,17,26,2024-04-26,0,2,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,248.0,,0,Transient,46.0,0,0
HB-010925,Resort Hotel,1,212,2025,April,15,10,2025-04-10,3,6,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,76.9,0,1
HB-046994,City Hotel,1,39,2024,February,5,1,2024-02-01,1,3,1,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,72.9,0,0
HB-114134,City Hotel,0,47,2025,June,24,15,2025-06-15,0,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.0,0,1
HB-049924,City Hotel,1,39,2024,April,16,20,2024-04-20,1,4,3,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.5,0,0
HB-021376,Resort Hotel,0,0,2024,February,9,27,2024-02-27,0,1,2,1.0,0,HB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,146.0,1,0
HB-014408,Resort Hotel,0,1,2025,February,7,11,2025-02-11,0,1,2,0.0,0,BB,,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,55.0,1,0
HB-010617,Resort Hotel,1,20,2025,March,12,22,2025-03-22,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,66.0,,0,Transient-Party,45.0,0,0
HB-037968,Resort Hotel,0,82,2025,June,25,21,2025-06-21,4,10,2,0.0,0,HB,ITA,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,159.0,0,0
HB-111375,City Hotel,0,82,2025,May,19,8,2025-05-08,1,1,2,0.0,0,SC,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,83.16,0,0
HB-009050,Resort Hotel,0,0,2024,October,43,25,2024-10-25,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,47.0,0,Transient,48.0,0,0
HB-041279,City Hotel,1,0,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-042777,City Hotel,1,44,2023,September,36,10,2023-09-10,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,41.0,,0,Transient,126.0,0,0
HB-022252,Resort Hotel,0,0,2024,March,12,21,2024-03-21,1,0,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,68.0,0,0
HB-040182,City Hotel,1,60,2023,July,28,13,2023-07-13,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,91.33,0,0
HB-103961,City Hotel,0,0,2025,January,1,2,2025-01-02,1,0,2,0.0,0,SC,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,96.0,0,2
HB-061985,City Hotel,1,341,2024,December,52,29,2024-12-29,2,3,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,71.91,0,2
HB-048565,City Hotel,1,161,2024,March,13,25,2024-03-25,1,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,101,Transient,130.0,0,0
HB-018579,Resort Hotel,0,0,2023,November,47,23,2023-11-23,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,E,0,No Deposit,,,0,Transient,58.0,1,0
HB-034376,Resort Hotel,0,96,2025,March,11,12,2025-03-12,4,7,2,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,E,E,4,No Deposit,,,0,Transient-Party,78.18,0,0
HB-037346,Resort Hotel,0,131,2025,June,24,11,2025-06-11,2,2,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,410.0,,0,Transient,58.7,0,0
HB-012111,Resort Hotel,1,175,2025,June,24,14,2025-06-14,0,3,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,140.0,0,1
HB-025260,Resort Hotel,0,0,2024,June,25,18,2024-06-18,1,1,2,0.0,0,BB,CN,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,,0,Transient,173.0,1,0
HB-068100,City Hotel,1,21,2025,May,20,12,2025-05-12,2,7,1,0.0,0,BB,AGO,Direct,Direct,0,0,0,G,G,0,No Deposit,14.0,,0,Transient,290.56,0,0
HB-116152,City Hotel,0,414,2025,July,28,13,2025-07-13,0,2,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,122.4,0,1
HB-034479,Resort Hotel,0,43,2025,March,13,25,2025-03-25,0,1,2,1.0,0,HB,ESP,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient-Party,153.0,1,0
HB-008846,Resort Hotel,1,14,2024,October,42,16,2024-10-16,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,60.0,0,1
HB-052572,City Hotel,1,56,2024,June,23,8,2024-06-08,0,1,2,0.0,0,BB,PRT,Offline TA/TO,Corporate,0,0,0,A,A,0,No Deposit,191.0,,0,Transient-Party,120.0,0,0
HB-105563,City Hotel,0,1,2025,February,7,10,2025-02-10,0,2,2,0.0,1,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,51.5,1,1
HB-060575,City Hotel,1,2,2024,November,46,16,2024-11-16,0,1,2,0.0,0,BB,CHE,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,105.0,0,0
HB-071363,City Hotel,1,288,2025,July,27,3,2025-07-03,1,4,2,0.0,0,SC,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,1
HB-076784,City Hotel,1,395,2024,March,12,21,2024-03-21,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-042476,City Hotel,0,55,2023,September,36,6,2023-09-06,2,0,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,75.0,0,0
HB-001099,Resort Hotel,0,0,2023,August,33,14,2023-08-14,0,1,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,D,F,0,No Deposit,240.0,,0,Transient-Party,172.0,0,2
HB-017644,Resort Hotel,0,287,2023,October,41,15,2023-10-15,0,3,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,E,1,No Deposit,,223.0,0,Transient-Party,44.5,0,0
HB-008839,Resort Hotel,1,181,2024,October,42,16,2024-10-16,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,11.0,,0,Transient,37.0,0,0
HB-077374,City Hotel,1,19,2023,October,40,6,2023-10-06,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,1,1,0,A,A,0,Non Refund,82.0,,0,Transient,90.0,0,0
HB-117621,City Hotel,0,94,2025,July,31,28,2025-07-28,3,7,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,42.0,,0,Transient,116.0,0,0
HB-114060,City Hotel,0,44,2025,June,24,15,2025-06-15,0,1,2,0.0,0,BB,USA,Online TA,GDS,0,0,0,D,D,0,No Deposit,195.0,,0,Transient,150.0,0,1
HB-027568,Resort Hotel,0,69,2024,August,35,29,2024-08-29,1,3,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,C,1,No Deposit,240.0,,0,Transient,200.0,0,1
HB-066894,City Hotel,1,156,2025,April,17,26,2025-04-26,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,100.0,0,0
HB-020370,Resort Hotel,0,1,2024,January,4,26,2024-01-26,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,39.0,0,0
HB-083080,City Hotel,0,42,2024,January,3,15,2024-01-15,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,60.0,0,0
HB-112393,City Hotel,0,11,2025,May,21,22,2025-05-22,1,1,1,0.0,0,BB,PER,Direct,Direct,0,0,0,F,F,0,No Deposit,14.0,,0,Transient-Party,235.0,0,2
HB-065070,City Hotel,1,90,2025,March,12,23,2025-03-23,1,3,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,100.3,0,0
HB-045899,City Hotel,0,84,2023,November,48,27,2023-11-27,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,64.0,0,0
HB-082428,City Hotel,0,0,2023,December,52,27,2023-12-27,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,28.0,,0,Transient,58.0,0,0
HB-104378,City Hotel,0,74,2025,January,2,7,2025-01-07,2,3,1,0.0,0,BB,USA,Groups,TA/TO,0,0,0,D,D,1,No Deposit,330.0,,0,Transient-Party,67.0,0,2
HB-093008,City Hotel,0,173,2024,July,28,11,2024-07-11,1,3,1,1.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,65.49,0,1
HB-069200,City Hotel,1,67,2025,May,22,27,2025-05-27,1,1,3,0.0,0,BB,DZA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,234.0,0,2
HB-109983,City Hotel,0,174,2025,April,16,17,2025-04-17,1,2,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,0
HB-092229,City Hotel,0,16,2024,July,27,1,2024-07-01,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,166.0,0,2
HB-049753,City Hotel,1,103,2024,April,16,19,2024-04-19,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,0,Transient,115.0,0,0
HB-061292,City Hotel,1,27,2024,December,49,7,2024-12-07,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,113.0,0,2
HB-060036,City Hotel,1,305,2024,November,45,4,2024-11-04,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,89.0,0,0
HB-061230,City Hotel,1,283,2024,December,49,5,2024-12-05,1,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,E,E,0,Non Refund,,51.0,0,Transient-Party,106.0,0,0
HB-080829,City Hotel,1,3,2023,November,48,28,2023-11-28,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,D,D,0,No Deposit,83.0,,0,Transient,77.6,0,1
HB-036912,Resort Hotel,0,352,2025,May,21,25,2025-05-25,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,66.0,0,0
HB-109220,City Hotel,0,76,2025,April,14,3,2025-04-03,1,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,89.1,0,1
HB-008406,Resort Hotel,1,339,2024,September,39,26,2024-09-26,3,6,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,15.0,,0,Transient,80.0,0,0
HB-052841,City Hotel,1,153,2024,June,24,12,2024-06-12,2,1,2,2.0,0,BB,USA,Online TA,TA/TO,0,0,0,F,F,2,No Deposit,9.0,,0,Transient,189.9,0,0
HB-095509,City Hotel,0,320,2024,August,33,18,2024-08-18,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-065316,City Hotel,1,80,2025,March,14,31,2025-03-31,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,56.0,,0,Transient,90.0,0,0
HB-110199,City Hotel,0,139,2025,April,17,23,2025-04-23,2,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,8.0,,0,Transient,12.0,0,1
HB-065969,City Hotel,1,92,2025,April,15,11,2025-04-11,0,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,135.0,0,1
HB-009632,Resort Hotel,1,1,2024,December,51,22,2024-12-22,0,1,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,5.0,,0,Transient,47.4,0,0
HB-011814,Resort Hotel,1,411,2025,May,22,31,2025-05-31,2,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,71.1,0,0
HB-077204,City Hotel,0,0,2023,September,37,12,2023-09-12,1,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-022403,Resort Hotel,0,18,2024,March,12,22,2024-03-22,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,54.0,0,0
HB-095975,City Hotel,0,139,2024,August,34,23,2024-08-23,0,4,2,0.0,0,BB,GEO,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,90.0,0,1
HB-080005,City Hotel,0,14,2023,November,44,5,2023-11-05,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,16.0,,0,Transient,43.5,0,0
HB-079212,City Hotel,0,6,2023,October,42,20,2023-10-20,0,3,1,0.0,0,BB,GRC,Direct,Direct,0,0,0,A,D,0,No Deposit,14.0,,0,Transient,109.0,0,2
HB-072285,City Hotel,1,34,2025,July,30,25,2025-07-25,0,3,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,240.0,0,1
HB-059777,City Hotel,1,166,2024,November,44,1,2024-11-01,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,110.0,0,0
HB-022213,Resort Hotel,0,14,2024,March,12,19,2024-03-19,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient,29.0,0,2
HB-021856,Resort Hotel,0,63,2024,March,10,5,2024-03-05,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,29.0,0,0
HB-042451,City Hotel,0,72,2023,September,36,5,2023-09-05,2,2,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,72.25,0,0
HB-022210,Resort Hotel,0,8,2024,March,12,18,2024-03-18,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,55.0,0,0
HB-056282,City Hotel,1,63,2024,September,36,2,2024-09-02,1,2,2,1.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,177.75,0,0
HB-041590,City Hotel,0,6,2023,August,33,18,2023-08-18,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,14.0,,0,Transient,75.0,0,2
HB-119387,City Hotel,0,102,2025,August,35,31,2025-08-31,2,5,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,225.43,0,2
HB-081864,City Hotel,1,178,2024,April,17,28,2024-04-28,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,46,Transient,110.0,0,0
HB-043168,City Hotel,0,76,2023,September,37,16,2023-09-16,0,2,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,B,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-097088,City Hotel,0,68,2024,September,37,9,2024-09-09,1,2,3,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,168.3,0,1
HB-106229,City Hotel,0,31,2025,February,8,19,2025-02-19,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,58.52,0,1
HB-067195,City Hotel,1,78,2025,April,18,29,2025-04-29,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient,90.0,0,0
HB-094068,City Hotel,0,170,2024,July,30,24,2024-07-24,2,5,3,0.0,0,BB,DNK,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,7.0,,0,Transient,95.13,0,2
HB-021258,Resort Hotel,0,24,2024,February,8,22,2024-02-22,1,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,36.96,0,2
HB-096866,City Hotel,0,8,2024,September,36,7,2024-09-07,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,8.0,,0,Transient,149.0,0,1
HB-118301,City Hotel,0,84,2025,August,33,14,2025-08-14,1,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient-Party,170.0,0,0
HB-106557,City Hotel,0,0,2025,February,9,27,2025-02-27,0,0,0,0.0,0,BB,PRT,Online TA,TA/TO,1,0,0,A,K,0,No Deposit,85.0,,0,Transient,0.0,0,0
HB-006144,Resort Hotel,0,225,2024,May,21,26,2024-05-26,1,3,1,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,A,2,No Deposit,,223.0,0,Transient-Party,60.0,1,0
HB-062379,City Hotel,1,47,2025,January,2,12,2025-01-12,0,2,1,0.0,0,SC,RUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,1
HB-048054,City Hotel,1,33,2024,March,11,14,2024-03-14,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-011510,Resort Hotel,1,201,2025,May,20,13,2025-05-13,1,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,76.5,0,1
HB-061632,City Hotel,1,15,2024,December,51,20,2024-12-20,2,5,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.4,0,0
HB-038082,Resort Hotel,0,159,2025,July,27,2,2025-07-02,2,5,2,0.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,112.5,0,1
HB-105149,City Hotel,0,0,2025,January,5,30,2025-01-30,1,0,1,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,94.0,,0,Transient,65.0,0,1
HB-013814,Resort Hotel,0,1,2024,February,5,2,2024-02-02,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,1,A,D,1,No Deposit,,94.0,0,Transient,27.0,0,0
HB-066425,City Hotel,1,71,2025,April,16,20,2025-04-20,0,2,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-015756,Resort Hotel,1,244,2023,September,35,2,2023-09-02,2,5,2,0.0,0,BB,IRL,Groups,TA/TO,0,1,0,A,A,0,No Deposit,96.0,,0,Transient-Party,8.0,0,0
HB-058175,City Hotel,1,14,2024,October,41,7,2024-10-07,0,2,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,E,E,0,No Deposit,,316.0,0,Transient,166.25,0,0
HB-094846,City Hotel,0,2,2024,August,32,9,2024-08-09,0,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,179.0,1,1
HB-067576,City Hotel,1,28,2025,May,18,4,2025-05-04,2,4,2,0.0,0,BB,AGO,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,152.33,0,0
HB-098978,City Hotel,0,29,2024,October,40,5,2024-10-05,0,2,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,186.2,0,3
HB-028407,Resort Hotel,0,59,2024,September,40,30,2024-09-30,0,2,2,0.0,0,HB,COL,Online TA,TA/TO,0,0,0,E,F,0,No Deposit,240.0,,0,Transient,150.0,0,1
HB-024668,Resort Hotel,0,3,2024,May,22,28,2024-05-28,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,195.0,1,2
HB-007735,Resort Hotel,1,59,2024,August,34,23,2024-08-23,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,189.0,0,0
HB-114062,City Hotel,0,137,2025,June,24,11,2025-06-11,2,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,89.1,0,0
HB-057513,City Hotel,1,53,2024,September,39,26,2024-09-26,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,105.0,0,0
HB-072281,City Hotel,1,64,2025,July,30,25,2025-07-25,0,2,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,150.0,0,0
HB-113544,City Hotel,0,116,2025,June,23,6,2025-06-06,0,3,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,153.0,0,0
HB-020912,Resort Hotel,0,0,2024,February,7,13,2024-02-13,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,66.0,1,0
HB-053206,City Hotel,1,245,2024,June,25,17,2024-06-17,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,0,Transient,75.0,0,0
HB-106378,City Hotel,0,7,2025,February,8,18,2025-02-18,2,5,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,99.22,0,1
HB-030790,Resort Hotel,0,29,2024,December,49,2,2024-12-02,0,2,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,1,No Deposit,250.0,,0,Transient-Party,58.74,0,0
HB-027376,Resort Hotel,0,2,2024,August,35,27,2024-08-27,0,1,2,0.0,0,BB,BRA,Direct,Direct,0,0,0,D,D,1,No Deposit,250.0,,0,Transient,204.0,0,1
HB-032457,Resort Hotel,0,9,2025,January,4,21,2025-01-21,2,4,1,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,5.0,,0,Transient,47.4,0,0
HB-069878,City Hotel,1,183,2025,June,23,8,2025-06-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,86.0,,0,Transient,120.0,0,0
HB-028532,Resort Hotel,0,210,2024,September,39,29,2024-09-29,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Contract,50.46,1,2
HB-064278,City Hotel,1,65,2025,March,10,3,2025-03-03,3,7,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,100.3,0,0
HB-101881,City Hotel,0,73,2024,November,46,17,2024-11-17,0,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,102.6,0,1
HB-075099,City Hotel,1,283,2023,July,30,27,2023-07-27,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-078539,City Hotel,1,3,2023,October,41,12,2023-10-12,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,40.0,,0,Transient,65.0,0,0
HB-028435,Resort Hotel,0,221,2024,September,39,26,2024-09-26,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Contract,72.75,0,0
HB-066942,City Hotel,1,88,2025,April,17,26,2025-04-26,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,170.0,,0,Transient,140.0,0,0
HB-108107,City Hotel,0,48,2025,March,12,19,2025-03-19,2,2,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,79.2,0,0
HB-023796,Resort Hotel,0,0,2024,May,18,3,2024-05-03,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,314.0,,0,Transient-Party,75.2,1,0
HB-092106,City Hotel,0,80,2024,June,26,27,2024-06-27,1,3,3,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient,96.9,0,0
HB-090936,City Hotel,0,139,2024,June,24,13,2024-06-13,1,0,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.9,0,0
HB-102057,City Hotel,0,2,2025,June,23,2,2025-06-02,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,40.0,0,Transient,75.0,0,0
HB-037466,Resort Hotel,0,5,2025,June,25,17,2025-06-17,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,250.0,,0,Transient,135.0,0,0
HB-062486,City Hotel,1,38,2025,January,3,14,2025-01-14,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,Non Refund,,67.0,0,Transient,75.0,0,0
HB-049033,City Hotel,1,104,2024,April,14,5,2024-04-05,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,96.0,0,0
HB-077820,City Hotel,0,17,2023,September,39,26,2023-09-26,2,1,1,0.0,0,BB,ITA,Groups,TA/TO,0,0,0,A,A,2,No Deposit,1.0,,0,Transient-Party,170.0,0,0
HB-107435,City Hotel,0,220,2025,March,11,10,2025-03-10,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,99.2,0,1
HB-034652,Resort Hotel,0,64,2025,March,13,26,2025-03-26,2,4,2,1.0,0,BB,DEU,Online TA,TA/TO,0,0,0,G,G,1,No Deposit,240.0,,0,Transient,94.0,0,1
HB-016488,Resort Hotel,0,63,2023,August,34,24,2023-08-24,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,15.0,,0,Transient,133.0,0,0
HB-078231,City Hotel,1,8,2023,October,41,10,2023-10-10,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,D,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-011435,Resort Hotel,1,2,2025,May,19,8,2025-05-08,1,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,E,0,No Deposit,152.0,,0,Transient,64.0,0,1
HB-074764,City Hotel,0,241,2023,October,42,19,2023-10-19,1,2,2,0.0,0,BB,USA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,60.0,0,0
HB-094125,City Hotel,0,198,2024,July,31,30,2024-07-30,1,1,2,0.0,0,HB,ITA,Groups,TA/TO,0,0,0,A,C,0,No Deposit,1.0,,0,Transient-Party,96.0,0,1
HB-000212,Resort Hotel,0,7,2023,July,27,8,2023-07-08,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,131.0,1,2
HB-024120,Resort Hotel,0,0,2024,May,19,11,2024-05-11,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,109.0,0,0
HB-061490,City Hotel,1,524,2024,December,50,15,2024-12-15,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,51.4,0,0
HB-025030,Resort Hotel,0,126,2024,May,22,30,2024-05-30,3,10,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,75.0,,0,Transient,98.6,0,0
HB-081019,City Hotel,1,86,2024,January,4,22,2024-01-22,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,29.0,,35,Transient,85.0,0,0
HB-004863,Resort Hotel,0,171,2024,April,14,4,2024-04-04,1,1,1,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,1,Non Refund,298.0,,0,Transient-Party,54.5,0,0
HB-001295,Resort Hotel,0,70,2023,August,34,22,2023-08-22,2,4,2,2.0,0,HB,PRT,Direct,Direct,0,0,0,C,C,1,No Deposit,250.0,,0,Transient,211.0,1,0
HB-059349,City Hotel,1,85,2024,October,43,27,2024-10-27,0,2,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.1,0,0
HB-032559,Resort Hotel,0,17,2025,January,4,23,2025-01-23,2,5,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,75.0,1,0
HB-055536,City Hotel,1,175,2024,August,33,15,2024-08-15,1,3,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.05,0,0
HB-029489,Resort Hotel,0,2,2024,October,44,29,2024-10-29,0,0,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,314.0,,0,Transient,0.0,0,0
HB-071826,City Hotel,1,185,2025,July,28,13,2025-07-13,0,3,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,156.6,0,0
HB-012070,Resort Hotel,1,125,2025,June,24,11,2025-06-11,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,410.0,,0,Transient,63.0,0,0
HB-045818,City Hotel,1,98,2023,November,47,23,2023-11-23,1,2,1,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,84.0,0,0
HB-074332,City Hotel,1,262,2023,July,27,6,2023-07-06,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Contract,62.0,0,0
HB-057956,City Hotel,1,207,2024,October,40,4,2024-10-04,0,1,2,0.0,0,SC,HKG,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.1,0,0
HB-016485,Resort Hotel,0,37,2023,August,34,27,2023-08-27,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,104.97,0,1
HB-089552,City Hotel,0,86,2024,May,21,20,2024-05-20,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,65.0,0,1
HB-034178,Resort Hotel,0,112,2025,March,11,15,2025-03-15,0,2,2,0.0,0,BB,GBR,Corporate,Direct,0,0,0,A,F,2,No Deposit,,477.0,0,Group,60.0,0,1
HB-019844,Resort Hotel,0,38,2024,January,1,3,2024-01-03,2,0,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,1,No Deposit,250.0,,0,Transient,34.0,1,0
HB-076597,City Hotel,1,224,2023,September,37,11,2023-09-11,1,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,90.0,0,0
HB-099524,City Hotel,0,185,2024,October,41,10,2024-10-10,1,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,113.4,0,2
HB-036930,Resort Hotel,0,5,2025,June,22,1,2025-06-01,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,67.5,0,0
HB-020917,Resort Hotel,0,4,2024,July,29,21,2024-07-21,0,3,1,0.0,0,BB,PRT,Online TA,TA/TO,1,0,5,A,A,0,No Deposit,240.0,,0,Transient,201.0,1,0
HB-097068,City Hotel,0,2,2024,September,37,11,2024-09-11,1,0,2,0.0,0,BB,USA,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,145.0,0,1
HB-112630,City Hotel,0,93,2025,May,21,23,2025-05-23,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,129.0,0,1
HB-087277,City Hotel,0,122,2024,April,16,15,2024-04-15,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,151.0,,56,Transient-Party,85.0,0,0
HB-013779,Resort Hotel,1,54,2025,August,35,30,2025-08-30,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,177.0,,0,Group,141.0,0,1
HB-040386,City Hotel,0,132,2023,July,29,23,2023-07-23,0,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,90.0,0,0
HB-087752,City Hotel,0,0,2024,April,17,23,2024-04-23,1,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,B,1,No Deposit,9.0,,0,Transient,114.0,0,0
HB-076824,City Hotel,0,0,2023,August,32,11,2023-08-11,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,9.0,,0,Contract,133.0,1,2
HB-097059,City Hotel,0,240,2024,September,37,10,2024-09-10,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,96.0,0,1
HB-113284,City Hotel,0,43,2025,June,23,3,2025-06-03,1,1,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,240.0,0,2
HB-020031,Resort Hotel,0,0,2024,January,2,13,2024-01-13,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,0
HB-061569,City Hotel,1,185,2024,December,51,16,2024-12-16,1,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,0
HB-033806,Resort Hotel,0,6,2025,March,9,1,2025-03-01,0,4,2,0.0,0,BB,BEL,Groups,Corporate,0,0,0,A,A,3,No Deposit,,223.0,0,Transient-Party,37.0,0,0
HB-006503,Resort Hotel,1,114,2024,June,24,13,2024-06-13,1,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,106.0,0,0
HB-028444,Resort Hotel,0,192,2024,September,38,19,2024-09-19,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Contract,48.75,0,2
HB-069842,City Hotel,1,115,2025,June,23,7,2025-06-07,0,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,130.67,0,0
HB-005106,Resort Hotel,0,185,2024,April,16,18,2024-04-18,1,1,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,C,0,No Deposit,298.0,,0,Transient-Party,85.0,0,0
HB-085637,City Hotel,0,54,2024,March,11,16,2024-03-16,0,3,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,83.4,0,0
HB-118364,City Hotel,0,125,2025,August,33,12,2025-08-12,2,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,155.0,0,1
HB-010709,Resort Hotel,1,6,2025,March,13,27,2025-03-27,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,135.0,0,Transient,35.0,0,0
HB-066278,City Hotel,1,128,2025,April,16,16,2025-04-16,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,0,Transient,100.0,0,0
HB-028998,Resort Hotel,0,318,2024,October,41,11,2024-10-11,2,5,2,0.0,0,BB,GBR,Groups,Direct,0,0,0,E,E,0,No Deposit,273.0,,0,Transient,78.81,0,0
HB-029153,Resort Hotel,0,43,2024,October,42,19,2024-10-19,0,3,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,60.0,0,0
HB-042570,City Hotel,0,0,2023,September,36,7,2023-09-07,1,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,148.67,0,0
HB-007119,Resort Hotel,1,32,2024,July,30,22,2024-07-22,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,209.0,0,0
HB-080355,City Hotel,1,3,2023,November,46,19,2023-11-19,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,85.0,,0,Transient,64.0,0,0
HB-056883,City Hotel,1,317,2024,September,37,15,2024-09-15,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,120.0,0,0
HB-041514,City Hotel,0,4,2023,August,33,17,2023-08-17,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,122.0,0,3
HB-020445,Resort Hotel,0,4,2025,June,27,30,2025-06-30,1,2,2,2.0,0,BB,PRT,Online TA,TA/TO,1,0,1,G,G,0,No Deposit,240.0,,0,Transient,226.67,0,2
HB-114475,City Hotel,0,14,2025,June,25,19,2025-06-19,1,3,1,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,220.0,0,1
HB-052178,City Hotel,1,77,2024,June,22,1,2024-06-01,0,3,2,0.0,0,SC,AUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,116.1,0,0
HB-076747,City Hotel,1,327,2023,September,36,9,2023-09-09,2,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,4.0,,0,Transient-Party,76.0,0,0
HB-089720,City Hotel,0,35,2024,May,21,24,2024-05-24,0,1,2,0.0,0,SC,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.1,0,1
HB-108859,City Hotel,0,0,2025,April,14,1,2025-04-01,1,1,2,0.0,1,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,115.0,0,0
HB-021385,Resort Hotel,0,1,2024,February,9,27,2024-02-27,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient,50.0,0,1
HB-031245,Resort Hotel,0,1,2025,January,4,24,2025-01-24,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,1,0,2,A,D,0,No Deposit,240.0,,0,Group,43.0,0,3
HB-049489,City Hotel,1,126,2024,April,15,14,2024-04-14,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,39,Transient,65.0,0,0
HB-010284,Resort Hotel,1,29,2025,February,9,24,2025-02-24,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient,34.0,0,1
HB-034819,Resort Hotel,0,74,2025,March,13,30,2025-03-30,2,5,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,113.29,0,1
HB-034614,Resort Hotel,0,214,2025,March,13,24,2025-03-24,2,5,2,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,D,D,1,No Deposit,273.0,,0,Transient-Party,62.91,0,0
HB-064127,City Hotel,1,28,2025,March,9,2,2025-03-02,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,95.0,0,0
HB-063777,City Hotel,1,29,2025,February,8,20,2025-02-20,1,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,69.7,0,0
HB-009448,Resort Hotel,1,44,2024,November,48,30,2024-11-30,0,1,1,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,0.0,0,0
HB-068605,City Hotel,1,105,2025,May,21,19,2025-05-19,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-049394,City Hotel,1,197,2024,April,15,12,2024-04-12,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,106.2,0,2
HB-069221,City Hotel,1,171,2025,May,22,27,2025-05-27,2,2,2,1.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,144.0,0,1
HB-044683,City Hotel,1,66,2023,October,41,9,2023-10-09,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,75.0,0,0
HB-078711,City Hotel,0,2,2024,December,50,14,2024-12-14,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,22,A,A,3,No Deposit,,40.0,0,Transient,65.0,0,1
HB-024244,Resort Hotel,0,110,2024,May,19,8,2024-05-08,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,241.0,,0,Transient,50.06,0,1
HB-111519,City Hotel,0,1,2025,May,19,11,2025-05-11,0,1,2,0.0,0,SC,RUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,150.0,0,0
HB-018753,Resort Hotel,0,4,2023,November,48,27,2023-11-27,0,2,2,1.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,2,No Deposit,250.0,,0,Transient,101.5,1,0
HB-064809,City Hotel,1,72,2025,March,11,16,2025-03-16,1,3,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,1
HB-021822,Resort Hotel,0,81,2024,March,10,9,2024-03-09,0,3,3,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,A,C,0,No Deposit,115.0,,0,Transient-Party,86.55,0,0
HB-092954,City Hotel,0,28,2024,July,28,14,2024-07-14,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,67.0,1,0
HB-071808,City Hotel,1,264,2025,July,28,12,2025-07-12,1,4,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,80.09,0,2
HB-013469,Resort Hotel,1,0,2025,August,33,17,2025-08-17,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,200.0,0,0
HB-091635,City Hotel,0,19,2024,June,25,22,2024-06-22,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,215.0,,0,Transient-Party,90.0,0,0
HB-103159,City Hotel,0,7,2025,February,6,7,2025-02-07,0,2,1,0.0,0,BB,DEU,Online TA,TA/TO,1,0,1,A,A,0,No Deposit,9.0,,0,Transient,98.0,0,2
HB-070969,City Hotel,1,145,2025,June,26,26,2025-06-26,1,2,3,0.0,0,HB,BRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,189.0,0,0
HB-071065,City Hotel,1,141,2025,June,26,27,2025-06-27,2,5,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,130.0,0,0
HB-081889,City Hotel,1,178,2024,April,17,28,2024-04-28,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,46,Transient,120.0,0,0
HB-097864,City Hotel,0,27,2024,September,38,20,2024-09-20,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,288.0,,0,Transient-Party,95.0,0,0
HB-038124,Resort Hotel,0,226,2025,July,27,3,2025-07-03,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,112.0,0,0
HB-041271,City Hotel,1,39,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,101.5,0,0
HB-033160,Resort Hotel,0,31,2025,February,7,14,2025-02-14,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient-Party,68.0,0,2
HB-029479,Resort Hotel,0,0,2024,November,45,5,2024-11-05,0,1,2,0.0,0,BB,PRT,Direct,Direct,1,0,1,A,D,1,No Deposit,,,0,Transient,78.0,0,0
HB-077045,City Hotel,1,262,2023,November,45,9,2023-11-09,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-006431,Resort Hotel,1,155,2024,June,24,10,2024-06-10,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,99.0,0,1
HB-073786,City Hotel,1,279,2023,July,29,23,2023-07-23,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-078942,City Hotel,0,14,2023,October,41,13,2023-10-13,2,5,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,131.43,0,2
HB-117969,City Hotel,0,308,2025,August,32,7,2025-08-07,1,5,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,98.1,0,1
HB-101473,City Hotel,0,26,2024,November,45,10,2024-11-10,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,118.07,0,1
HB-103752,City Hotel,0,115,2024,December,52,29,2024-12-29,0,2,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,107.41,0,2
HB-053956,City Hotel,1,54,2024,July,27,3,2024-07-03,2,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.9,0,0
HB-052957,City Hotel,1,71,2024,June,24,14,2024-06-14,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,120.0,0,0
HB-085035,City Hotel,0,0,2024,March,10,7,2024-03-07,1,0,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,90.0,0,1
HB-053243,City Hotel,1,245,2024,June,25,17,2024-06-17,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,0,Transient,75.0,0,0
HB-020384,Resort Hotel,0,0,2024,January,4,26,2024-01-26,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,39.0,0,0
HB-061627,City Hotel,1,13,2024,December,51,20,2024-12-20,0,3,1,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,78.0,0,0
HB-014527,Resort Hotel,0,0,2024,March,10,4,2024-03-04,0,2,1,0.0,0,BB,,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,56.0,1,0
HB-039641,Resort Hotel,0,7,2025,August,34,21,2025-08-21,1,2,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,274.67,0,2
HB-057597,City Hotel,1,163,2024,September,39,28,2024-09-28,1,4,2,2.0,0,BB,EST,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,187.28,0,0
HB-112062,City Hotel,0,395,2025,May,20,17,2025-05-17,0,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,1
HB-049176,City Hotel,1,274,2024,April,14,7,2024-04-07,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-105256,City Hotel,0,8,2025,February,5,2,2025-02-02,0,2,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,28.0,,0,Transient,75.0,0,0
HB-077900,City Hotel,0,16,2023,September,39,25,2023-09-25,2,3,1,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,170.0,0,0
HB-006163,Resort Hotel,1,143,2024,May,22,27,2024-05-27,0,2,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,,0,Transient,100.55,0,0
HB-012236,Resort Hotel,1,298,2025,June,25,19,2025-06-19,1,2,2,0.0,0,HB,URY,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,122.4,0,2
HB-076050,City Hotel,1,336,2023,September,38,18,2023-09-18,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-034696,Resort Hotel,0,28,2025,March,13,29,2025-03-29,0,4,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,50.0,0,0
HB-077106,City Hotel,0,219,2023,September,36,4,2023-09-04,1,2,1,0.0,0,BB,SWE,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,76.67,0,0
HB-061613,City Hotel,1,21,2024,December,51,19,2024-12-19,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.4,0,0
HB-013279,Resort Hotel,1,152,2025,August,32,7,2025-08-07,1,2,2,0.0,0,BB,MAR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,220.0,0,1
HB-089052,City Hotel,0,81,2024,May,20,15,2024-05-15,2,0,2,0.0,0,BB,CN,Groups,TA/TO,0,0,0,A,A,0,No Deposit,133.0,,0,Transient-Party,90.0,0,1
HB-105962,City Hotel,0,114,2025,February,7,15,2025-02-15,0,4,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,242.0,0,Transient-Party,78.0,0,0
HB-047593,City Hotel,0,54,2024,February,9,28,2024-02-28,1,0,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,87.5,1,0
HB-082761,City Hotel,1,68,2024,February,7,17,2024-02-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,37.0,,0,Transient,75.0,0,0
HB-015554,Resort Hotel,0,10,2023,July,29,20,2023-07-20,1,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,164.0,1,0
HB-072271,City Hotel,1,464,2025,July,30,25,2025-07-25,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-117241,City Hotel,0,83,2025,July,31,28,2025-07-28,2,2,3,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,220.0,0,1
HB-025570,Resort Hotel,0,160,2024,June,26,26,2024-06-26,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Contract,70.86,0,2
HB-073745,City Hotel,1,265,2023,July,27,9,2023-07-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-067334,City Hotel,1,123,2025,May,18,1,2025-05-01,1,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,139.5,0,1
HB-115108,City Hotel,0,169,2025,June,26,29,2025-06-29,0,3,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,131.7,0,1
HB-057897,City Hotel,1,43,2024,October,40,3,2024-10-03,1,0,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-112618,City Hotel,0,68,2025,May,21,22,2025-05-22,1,3,2,0.0,0,BB,BRA,Direct,Direct,0,0,0,A,A,2,No Deposit,14.0,,0,Transient-Party,144.0,0,0
HB-112449,City Hotel,0,90,2025,May,21,21,2025-05-21,2,1,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,117.0,0,1
HB-092580,City Hotel,0,126,2024,July,27,3,2024-07-03,2,4,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,131.47,0,0
HB-104853,City Hotel,0,0,2025,January,4,21,2025-01-21,2,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,108.16,0,0
HB-023504,Resort Hotel,0,6,2024,April,17,26,2024-04-26,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient-Party,64.0,0,0
HB-018490,Resort Hotel,0,1,2023,November,46,17,2023-11-17,0,4,1,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,37.7,0,0
HB-017737,Resort Hotel,0,236,2023,October,41,13,2023-10-13,2,5,2,1.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,95.0,,0,Transient,57.6,0,1
HB-022714,Resort Hotel,0,57,2024,March,13,31,2024-03-31,0,3,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,D,E,0,No Deposit,250.0,,0,Transient,57.9,0,0
HB-060115,City Hotel,1,11,2024,November,45,5,2024-11-05,0,1,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,150.0,0,1
HB-007910,Resort Hotel,1,19,2024,September,36,2,2024-09-02,0,2,2,0.0,0,HB,ESP,Direct,Direct,0,0,0,G,G,1,No Deposit,250.0,,0,Transient,227.1,0,0
HB-045830,City Hotel,1,98,2023,November,47,23,2023-11-23,1,2,1,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,84.0,0,0
HB-028389,Resort Hotel,0,198,2024,September,39,25,2024-09-25,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Contract,65.11,0,0
HB-020345,Resort Hotel,0,2,2024,January,4,25,2024-01-25,1,1,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,,,0,Transient,51.0,0,1
HB-115008,City Hotel,0,164,2025,June,26,28,2025-06-28,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,1,1
HB-000367,Resort Hotel,0,40,2023,July,28,13,2023-07-13,1,4,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,120.0,0,2
HB-064431,City Hotel,1,57,2025,March,10,9,2025-03-09,0,3,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.2,0,0
HB-046110,City Hotel,0,110,2023,December,49,9,2023-12-09,0,4,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,56.0,,69,Transient-Party,70.0,0,0
HB-109508,City Hotel,0,52,2025,April,15,12,2025-04-12,0,1,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,171.0,0,0
HB-029579,Resort Hotel,0,2,2024,October,44,31,2024-10-31,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,E,0,No Deposit,250.0,,0,Transient,0.0,0,2
HB-032555,Resort Hotel,0,17,2025,January,5,28,2025-01-28,0,1,2,0.0,0,BB,PRT,Groups,Corporate,0,0,0,A,C,0,Non Refund,,504.0,0,Transient-Party,36.0,0,0
HB-106262,City Hotel,0,11,2025,February,8,20,2025-02-20,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,84.7,0,1
HB-046978,City Hotel,0,28,2024,January,5,31,2024-01-31,2,0,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.0,0,1
HB-002384,Resort Hotel,0,78,2023,October,41,10,2023-10-10,3,6,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,79.22,0,1
HB-085415,City Hotel,0,29,2024,March,10,10,2024-03-10,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,9.0,,0,Transient,100.28,0,1
HB-022623,Resort Hotel,0,6,2024,March,13,30,2024-03-30,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,E,0,No Deposit,,178.0,0,Transient-Party,50.0,0,0
HB-054951,City Hotel,1,9,2024,August,31,1,2024-08-01,1,0,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,201.0,0,3
HB-009440,Resort Hotel,1,34,2024,November,48,29,2024-11-29,0,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,240.0,,0,Transient,56.0,0,1
HB-043756,City Hotel,0,86,2023,September,38,24,2023-09-24,0,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,105.0,0,0
HB-079023,City Hotel,1,0,2023,October,42,20,2023-10-20,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,1,0,0,D,F,0,No Deposit,3.0,,0,Transient,97.0,0,0
HB-064661,City Hotel,1,55,2025,March,11,15,2025-03-15,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,G,0,No Deposit,205.0,,0,Transient,65.0,0,0
HB-007305,Resort Hotel,1,5,2024,August,31,2,2024-08-02,0,1,2,1.0,1,BB,PRT,Direct,Direct,0,0,0,C,C,0,No Deposit,,,0,Transient,0.0,0,0
HB-004934,Resort Hotel,1,121,2024,April,15,9,2024-04-09,2,5,2,0.0,0,HB,GBR,Groups,Direct,0,0,0,D,D,0,Non Refund,273.0,,0,Transient,72.0,0,0
HB-096648,City Hotel,0,128,2024,September,36,2,2024-09-02,1,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,118.8,0,1
HB-069661,City Hotel,1,348,2025,June,23,3,2025-06-03,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient,90.0,0,0
HB-023087,Resort Hotel,0,57,2024,April,15,13,2024-04-13,0,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,240.0,,0,Transient,64.0,1,0
HB-117840,City Hotel,0,306,2025,August,32,7,2025-08-07,1,3,1,1.0,0,HB,BEL,Direct,Direct,0,0,0,B,A,1,No Deposit,14.0,,0,Transient-Party,122.9,0,0
HB-014674,Resort Hotel,0,154,2023,October,44,30,2023-10-30,1,2,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,36.0,0,0
HB-094938,City Hotel,0,106,2024,August,32,9,2024-08-09,0,3,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,159.3,1,2
HB-112567,City Hotel,0,208,2025,May,21,24,2025-05-24,0,2,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,114.4,0,0
HB-011142,Resort Hotel,1,239,2025,April,17,22,2025-04-22,2,5,3,0.0,0,FB,PRT,Groups,Corporate,0,0,0,C,C,0,No Deposit,,,0,Transient-Party,158.0,0,0
HB-056339,City Hotel,1,420,2024,September,36,3,2024-09-03,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,35.0,,0,Transient,75.0,0,0
HB-114686,City Hotel,0,37,2025,June,26,24,2025-06-24,1,1,1,0.0,0,SC,USA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,160.0,0,0
HB-080885,City Hotel,0,73,2023,November,47,24,2023-11-24,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,12.0,,27,Transient-Party,67.83,0,0
HB-064593,City Hotel,1,52,2025,March,11,13,2025-03-13,1,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,56.0,,0,Transient,80.0,0,0
HB-030699,Resort Hotel,0,54,2024,November,48,27,2024-11-27,2,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,55.8,0,2
HB-053630,City Hotel,1,40,2024,June,26,26,2024-06-26,2,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,100.02,0,0
HB-085451,City Hotel,0,41,2024,March,11,13,2024-03-13,2,1,2,0.0,0,BB,POL,Corporate,TA/TO,0,0,0,A,A,0,No Deposit,,193.0,0,Transient-Party,85.67,0,0
HB-103056,City Hotel,0,80,2024,December,50,9,2024-12-09,0,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-044142,City Hotel,0,23,2023,September,39,30,2023-09-30,0,4,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,116.03,0,1
HB-070818,City Hotel,1,227,2025,June,26,23,2025-06-23,0,2,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,0
HB-028192,Resort Hotel,0,24,2024,September,39,23,2024-09-23,0,1,2,0.0,0,BB,THA,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,,0,Transient-Party,169.0,0,2
HB-039138,Resort Hotel,0,165,2025,July,31,28,2025-07-28,4,8,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient-Party,165.33,0,0
HB-049362,City Hotel,1,50,2024,April,15,11,2024-04-11,1,3,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.45,0,0
HB-086411,City Hotel,0,0,2024,April,14,2,2024-04-02,0,1,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient,6.0,0,0
HB-117890,City Hotel,0,479,2025,August,32,9,2025-08-09,0,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,1
HB-096804,City Hotel,0,59,2024,September,36,7,2024-09-07,0,1,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.5,1,1
HB-058061,City Hotel,1,275,2024,October,40,5,2024-10-05,1,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,44.0,,0,Transient,90.0,0,0
HB-010917,Resort Hotel,1,54,2025,April,15,10,2025-04-10,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,90.0,0,2
HB-103201,City Hotel,0,0,2024,December,50,14,2024-12-14,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,1,No Deposit,,,0,Transient,70.2,0,0
HB-086670,City Hotel,0,79,2024,April,14,2,2024-04-02,2,3,2,0.0,0,BB,COL,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,92.65,0,1
HB-094018,City Hotel,0,172,2024,July,30,28,2024-07-28,0,2,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,9.0,,0,Transient,137.7,0,1
HB-093221,City Hotel,0,113,2024,July,29,15,2024-07-15,2,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,72.25,0,0
HB-106883,City Hotel,0,17,2025,March,10,3,2025-03-03,0,2,1,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,60.06,0,0
HB-002747,Resort Hotel,0,154,2023,October,44,30,2023-10-30,0,2,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,36.0,0,0
HB-097544,City Hotel,0,291,2024,September,38,21,2024-09-21,0,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,1,A,D,0,No Deposit,3.0,,44,Transient-Party,117.0,0,0
HB-002431,Resort Hotel,0,73,2023,October,41,13,2023-10-13,2,6,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,E,F,0,No Deposit,250.0,,0,Transient,73.38,0,2
HB-095945,City Hotel,0,3,2024,August,34,22,2024-08-22,1,3,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,98.56,0,1
HB-062162,City Hotel,1,221,2025,January,1,3,2025-01-03,0,2,2,1.0,0,HB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.85,0,0
HB-087436,City Hotel,0,49,2024,April,16,19,2024-04-19,0,1,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.9,0,1
HB-010922,Resort Hotel,1,62,2025,April,15,10,2025-04-10,1,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,79.0,0,1
HB-002823,Resort Hotel,0,155,2023,October,44,31,2023-10-31,1,1,1,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,36.0,0,0
HB-100869,City Hotel,0,18,2024,November,44,1,2024-11-01,0,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,1
HB-017101,Resort Hotel,0,262,2023,September,38,21,2023-09-21,1,3,2,0.0,0,HB,BEL,Groups,Corporate,0,0,0,A,A,0,No Deposit,183.0,,0,Transient-Party,89.2,0,0
HB-054085,City Hotel,1,245,2024,July,27,6,2024-07-06,2,4,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,110.0,0,0
HB-108089,City Hotel,0,24,2025,March,12,20,2025-03-20,1,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,85.0,0,0
HB-071143,City Hotel,1,215,2025,June,26,28,2025-06-28,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-024615,Resort Hotel,0,120,2024,May,21,22,2024-05-22,2,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,26.0,,0,Transient,66.8,0,0
HB-024781,Resort Hotel,0,176,2024,June,22,2,2024-06-02,0,1,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,E,0,No Deposit,251.0,,0,Transient,78.0,0,0
HB-043118,City Hotel,0,7,2023,September,37,15,2023-09-15,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,152.0,0,2
HB-005148,Resort Hotel,1,114,2024,April,16,18,2024-04-18,1,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,52.2,0,0
HB-018300,Resort Hotel,0,0,2023,November,46,16,2023-11-16,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,53.0,0,0
HB-015221,Resort Hotel,1,274,2023,October,40,3,2023-10-03,2,5,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,96.0,,0,Transient,36.05,0,0
HB-046105,City Hotel,1,110,2023,December,49,9,2023-12-09,0,4,2,2.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,G,G,1,No Deposit,56.0,,69,Transient-Party,113.5,0,0
HB-040618,City Hotel,1,28,2023,August,31,3,2023-08-03,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-032765,Resort Hotel,0,2,2025,February,6,3,2025-02-03,0,2,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient-Party,80.0,0,1
HB-090879,City Hotel,0,57,2024,June,24,10,2024-06-10,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,90.67,0,1
HB-111080,City Hotel,0,96,2025,May,18,3,2025-05-03,0,3,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-039515,Resort Hotel,0,25,2025,August,34,18,2025-08-18,0,2,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,205.2,0,1
HB-109188,City Hotel,0,48,2025,April,14,5,2025-04-05,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Contract,68.0,0,0
HB-061659,City Hotel,1,531,2024,December,51,22,2024-12-22,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-032075,Resort Hotel,0,48,2025,January,2,12,2025-01-12,1,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,42.0,0,1
HB-112117,City Hotel,0,84,2025,May,20,16,2025-05-16,0,4,2,0.0,0,BB,ROU,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,119.25,0,2
HB-050774,City Hotel,1,49,2024,May,19,7,2024-05-07,1,1,3,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,159.3,0,0
HB-018187,Resort Hotel,0,1,2023,November,45,11,2023-11-11,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,58.0,0,1
HB-098561,City Hotel,0,100,2024,September,39,28,2024-09-28,0,4,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,26.0,,0,Transient-Party,140.0,0,1
HB-037423,Resort Hotel,0,146,2025,June,24,15,2025-06-15,0,2,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient-Party,140.0,0,1
HB-041315,City Hotel,0,39,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-045260,City Hotel,0,69,2023,October,43,25,2023-10-25,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,58,Transient-Party,85.67,0,0
HB-012690,Resort Hotel,1,82,2025,July,28,12,2025-07-12,0,3,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,184.0,0,1
HB-064734,City Hotel,1,92,2025,March,11,15,2025-03-15,0,3,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,85.0,0,0
HB-037314,Resort Hotel,0,3,2025,June,24,12,2025-06-12,1,1,1,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,C,0,No Deposit,,,0,Transient,4.0,1,1
HB-103831,City Hotel,0,7,2024,December,1,30,2024-12-30,1,2,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,0
HB-067813,City Hotel,1,3,2025,May,19,8,2025-05-08,1,0,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,198.0,0,1
HB-110690,City Hotel,0,219,2025,April,18,29,2025-04-29,1,1,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.5,0,1
HB-103292,City Hotel,0,13,2024,December,50,14,2024-12-14,0,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.4,0,1
HB-091403,City Hotel,0,5,2024,June,25,20,2024-06-20,1,0,1,0.0,0,BB,FRA,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,227.0,0,Transient,95.0,0,0
HB-010280,Resort Hotel,1,76,2025,February,9,24,2025-02-24,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,42.0,0,2
HB-095860,City Hotel,0,154,2024,August,34,24,2024-08-24,0,1,2,0.0,0,BB,LUX,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.3,1,1
HB-102465,City Hotel,0,61,2024,November,48,26,2024-11-26,2,1,3,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,105.0,0,0
HB-060787,City Hotel,1,70,2024,November,47,21,2024-11-21,1,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,114.0,0,1
HB-045362,City Hotel,0,61,2023,October,43,27,2023-10-27,0,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,7.0,,0,Transient,74.61,0,1
HB-082376,City Hotel,1,108,2024,March,12,18,2024-03-18,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,154.0,,0,Transient,80.0,0,0
HB-040488,City Hotel,1,27,2023,July,30,27,2023-07-27,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-090546,City Hotel,0,0,2024,June,23,7,2024-06-07,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,109.0,0,0
HB-078491,City Hotel,0,0,2023,October,41,9,2023-10-09,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,152.0,0,0
HB-054273,City Hotel,1,49,2024,July,28,11,2024-07-11,1,0,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.15,0,0
HB-026712,Resort Hotel,0,3,2024,August,32,7,2024-08-07,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,165.0,0,1
HB-117848,City Hotel,0,0,2025,August,32,10,2025-08-10,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,150.0,0,0
HB-074536,City Hotel,1,339,2023,September,38,21,2023-09-21,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-011292,Resort Hotel,1,65,2025,May,18,1,2025-05-01,1,3,2,2.0,0,BB,IRL,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,123.0,0,2
HB-033671,Resort Hotel,0,4,2025,February,9,27,2025-02-27,1,0,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,314.0,,0,Transient,54.0,0,0
HB-010495,Resort Hotel,1,14,2025,March,11,10,2025-03-10,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,60.0,0,2
HB-107707,City Hotel,0,77,2025,March,11,15,2025-03-15,0,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,1
HB-066153,City Hotel,1,133,2025,April,16,15,2025-04-15,0,1,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.8,0,0
HB-053564,City Hotel,1,265,2024,June,26,24,2024-06-24,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-099105,City Hotel,0,59,2024,October,41,9,2024-10-09,1,0,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,108.0,0,1
HB-084786,City Hotel,0,7,2024,November,46,16,2024-11-16,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,8,A,A,0,No Deposit,,219.0,0,Transient,79.0,1,1
HB-029516,Resort Hotel,0,4,2024,October,44,28,2024-10-28,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,38.0,0,0
HB-019157,Resort Hotel,0,2,2023,December,49,9,2023-12-09,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient-Party,26.0,0,0
HB-052273,City Hotel,1,112,2024,June,22,2,2024-06-02,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,192.0,,0,Transient-Party,120.0,0,0
HB-075144,City Hotel,1,276,2023,July,29,20,2023-07-20,1,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,60.0,0,0
HB-084058,City Hotel,0,3,2024,February,7,18,2024-02-18,0,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,106.0,0,1
HB-116715,City Hotel,0,423,2025,July,30,22,2025-07-22,1,1,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,95.5,0,0
HB-062792,City Hotel,1,34,2025,January,4,22,2025-01-22,2,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,82.88,0,0
HB-108759,City Hotel,0,3,2025,March,14,31,2025-03-31,0,1,1,0.0,0,BB,ESP,Aviation,Corporate,0,0,0,A,A,0,No Deposit,,153.0,0,Transient,95.0,0,0
HB-109023,City Hotel,0,37,2025,April,14,2,2025-04-02,2,1,1,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,D,D,2,No Deposit,37.0,,0,Transient-Party,85.0,0,1
HB-068325,City Hotel,1,104,2025,May,20,15,2025-05-15,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,170.0,0,0
HB-039878,Resort Hotel,0,162,2025,August,34,24,2025-08-24,2,5,2,1.0,0,FB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,173.0,0,1
HB-098330,City Hotel,0,30,2024,September,39,25,2024-09-25,2,1,2,0.0,0,BB,LIE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,2
HB-048227,City Hotel,1,72,2024,March,12,19,2024-03-19,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient-Party,78.15,0,0
HB-072912,City Hotel,1,128,2025,August,32,9,2025-08-09,0,4,2,2.0,0,BB,USA,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,9.0,,0,Transient,235.0,0,1
HB-084536,City Hotel,0,45,2024,February,8,25,2024-02-25,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,80.3,0,1
HB-048908,City Hotel,1,53,2024,April,14,2,2024-04-02,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,123.3,0,0
HB-047570,City Hotel,1,115,2024,February,9,27,2024-02-27,2,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,B,1,No Deposit,134.0,,0,Transient-Party,61.0,0,0
HB-062997,City Hotel,1,61,2025,January,4,25,2025-01-25,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,326.0,,0,Transient,80.0,0,0
HB-118923,City Hotel,0,196,2025,August,34,23,2025-08-23,0,4,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,80.1,0,1
HB-073272,City Hotel,1,160,2025,August,34,18,2025-08-18,0,1,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,175.5,0,0
HB-099521,City Hotel,0,98,2024,October,41,10,2024-10-10,1,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,132.3,0,1
HB-068082,City Hotel,1,241,2025,May,20,12,2025-05-12,1,2,2,0.0,0,SC,LUX,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,132.33,0,1
HB-057818,City Hotel,1,179,2024,October,40,1,2024-10-01,2,1,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.9,0,2
HB-007763,Resort Hotel,1,31,2024,August,34,25,2024-08-25,0,3,1,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,214.0,0,0
HB-034102,Resort Hotel,0,0,2025,March,11,11,2025-03-11,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,F,0,No Deposit,,,0,Transient,100.0,0,1
HB-037940,Resort Hotel,0,176,2025,July,27,1,2025-07-01,2,1,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,112.5,0,1
HB-110397,City Hotel,0,135,2025,April,17,24,2025-04-24,1,2,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,99.0,0,0
HB-069051,City Hotel,1,138,2025,May,21,24,2025-05-24,1,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,89.1,0,1
HB-019477,Resort Hotel,0,46,2023,December,51,20,2023-12-20,2,0,2,1.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,6.0,,0,Transient-Party,32.5,0,1
HB-093724,City Hotel,0,148,2024,July,29,21,2024-07-21,2,3,3,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,D,3,No Deposit,9.0,,0,Transient,133.45,0,2
HB-092230,City Hotel,0,1,2024,June,26,27,2024-06-27,1,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,192.0,0,1
HB-110770,City Hotel,0,155,2025,April,18,28,2025-04-28,2,2,1,0.0,0,BB,DEU,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,99.0,0,1
HB-080036,City Hotel,0,4,2024,January,2,12,2024-01-12,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,1,11,4,A,A,0,No Deposit,9.0,,0,Transient,80.3,0,1
HB-077357,City Hotel,1,19,2023,October,40,6,2023-10-06,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,1,1,0,A,A,0,Non Refund,82.0,,0,Transient,80.0,0,0
HB-070392,City Hotel,1,226,2025,June,25,16,2025-06-16,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,105.0,0,0
HB-118383,City Hotel,0,219,2025,August,33,12,2025-08-12,2,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.5,0,1
HB-088084,City Hotel,0,142,2024,April,18,29,2024-04-29,0,2,2,0.0,0,BB,ITA,Groups,TA/TO,0,0,0,A,A,2,No Deposit,1.0,,0,Transient-Party,0.0,0,0
HB-003063,Resort Hotel,0,33,2023,November,45,12,2023-11-12,0,3,1,0.0,0,BB,FRA,Corporate,Corporate,0,0,0,A,C,2,No Deposit,334.0,281.0,0,Transient-Party,40.0,1,0
HB-012927,Resort Hotel,1,154,2025,July,30,23,2025-07-23,2,5,3,1.0,0,BB,POL,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,270.71,0,0
HB-075032,City Hotel,1,219,2023,September,36,4,2023-09-04,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,3.0,,0,Transient-Party,80.0,0,0
HB-006244,Resort Hotel,0,215,2024,May,22,30,2024-05-30,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,66.34,0,1
HB-058028,City Hotel,1,167,2024,October,40,5,2024-10-05,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,78.2,0,0
HB-083304,City Hotel,0,5,2025,February,9,28,2025-02-28,0,3,1,0.0,0,BB,FRA,Corporate,Corporate,1,0,1,A,A,3,No Deposit,,91.0,0,Transient,80.0,0,1
HB-078274,City Hotel,1,14,2023,October,41,15,2023-10-15,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,99.0,,0,Transient-Party,100.0,0,0
HB-099831,City Hotel,0,24,2024,October,42,16,2024-10-16,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,85.0,0,1
HB-053903,City Hotel,1,75,2024,July,27,1,2024-07-01,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,131.4,0,0
HB-036676,Resort Hotel,0,203,2025,May,21,25,2025-05-25,0,1,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,241.0,,0,Transient,119.35,0,1
HB-067940,City Hotel,1,57,2025,May,19,10,2025-05-10,0,1,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,134.1,0,0
HB-116799,City Hotel,0,8,2025,July,30,24,2025-07-24,1,0,2,0.0,0,BB,SRB,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,98.0,0,0
HB-083732,City Hotel,0,25,2024,February,6,7,2024-02-07,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,64.64,0,0
HB-030710,Resort Hotel,0,0,2024,December,48,1,2024-12-01,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,314.0,,0,Transient-Party,50.4,1,0
HB-075399,City Hotel,1,323,2023,September,36,5,2023-09-05,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-005328,Resort Hotel,1,138,2024,April,17,25,2024-04-25,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,E,E,0,Non Refund,,,0,Transient,65.0,0,0
HB-063034,City Hotel,1,61,2025,January,4,26,2025-01-26,2,6,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,66.29,0,0
HB-043385,City Hotel,0,74,2023,September,38,18,2023-09-18,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,B,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-044851,City Hotel,1,36,2023,October,41,13,2023-10-13,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,13.0,,0,Group,75.6,0,0
HB-048868,City Hotel,1,21,2024,March,13,31,2024-03-31,2,4,1,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.0,0,0
HB-082766,City Hotel,1,68,2024,February,7,17,2024-02-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,37.0,,0,Transient,75.0,0,0
HB-068659,City Hotel,1,175,2025,May,21,19,2025-05-19,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,0,Transient,110.0,0,0
HB-010651,Resort Hotel,1,105,2025,March,13,25,2025-03-25,2,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,56.0,0,2
HB-116328,City Hotel,0,476,2025,July,29,15,2025-07-15,2,1,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,1
HB-105183,City Hotel,0,240,2025,February,5,1,2025-02-01,0,1,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,2
HB-021403,Resort Hotel,0,4,2024,February,8,21,2024-02-21,2,5,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,171.0,,0,Transient,27.56,0,1
HB-070922,City Hotel,1,396,2025,June,26,25,2025-06-25,2,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,B,1,No Deposit,6.0,,0,Transient-Party,80.0,0,0
HB-074542,City Hotel,1,339,2023,September,38,21,2023-09-21,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-118163,City Hotel,0,234,2025,August,33,12,2025-08-12,2,2,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,109.38,0,3
HB-112259,City Hotel,0,72,2025,May,21,19,2025-05-19,1,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,144.0,0,2
HB-008798,Resort Hotel,0,342,2024,October,42,14,2024-10-14,2,5,2,0.0,0,BB,GBR,Groups,Direct,0,0,0,E,F,0,No Deposit,273.0,,125,Transient-Party,80.81,0,0
HB-038993,Resort Hotel,0,10,2025,August,31,1,2025-08-01,0,4,2,0.0,1,BB,CZE,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,209.75,0,3
HB-059292,City Hotel,1,98,2024,October,43,26,2024-10-26,0,2,2,0.0,0,SC,DNK,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.1,0,0
HB-009668,Resort Hotel,1,38,2024,December,52,24,2024-12-24,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,60.0,0,0
HB-076190,City Hotel,1,261,2023,October,42,16,2023-10-16,0,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,6.0,,0,Transient-Party,120.0,0,0
HB-010548,Resort Hotel,1,26,2025,March,11,14,2025-03-14,0,5,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient-Party,80.0,0,0
HB-040717,City Hotel,0,7,2023,August,31,5,2023-08-05,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,42.0,,0,Transient-Party,66.0,0,1
HB-064560,City Hotel,1,52,2025,March,11,13,2025-03-13,1,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,56.0,,0,Transient,80.0,0,0
HB-011818,Resort Hotel,1,411,2025,May,22,31,2025-05-31,2,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,71.1,0,0
HB-011945,Resort Hotel,1,102,2025,June,23,4,2025-06-04,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,410.0,,0,Transient,63.0,0,0
HB-028147,Resort Hotel,0,243,2024,September,38,18,2024-09-18,2,2,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,110.0,0,2
HB-003731,Resort Hotel,1,49,2023,December,52,31,2023-12-31,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,5.0,,0,Transient,145.87,0,1
HB-015419,Resort Hotel,0,162,2023,July,27,7,2023-07-07,2,7,2,0.0,0,BB,NOR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,142.0,,0,Contract,110.7,0,1
HB-007506,Resort Hotel,1,116,2024,August,33,12,2024-08-12,3,7,2,0.0,0,HB,ROU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,234.0,0,0
HB-067472,City Hotel,1,199,2025,May,18,4,2025-05-04,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,56.0,,56,Transient,110.0,0,0
HB-069470,City Hotel,1,82,2025,May,22,31,2025-05-31,0,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,189.0,0,2
HB-113428,City Hotel,0,24,2025,May,22,31,2025-05-31,2,5,1,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,D,D,4,No Deposit,9.0,,0,Transient,76.29,0,0
HB-066879,City Hotel,1,156,2025,April,17,26,2025-04-26,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,100.0,0,0
HB-083313,City Hotel,0,2,2024,January,4,24,2024-01-24,2,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.0,0,0
HB-081544,City Hotel,1,218,2024,June,23,9,2024-06-09,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,133.0,,0,Transient,135.0,0,0
HB-017658,Resort Hotel,0,287,2023,October,41,15,2023-10-15,1,3,1,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,1,No Deposit,,223.0,0,Transient-Party,37.0,0,0
HB-068555,City Hotel,1,175,2025,May,21,19,2025-05-19,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,44.0,,0,Transient,90.0,0,0
HB-000385,Resort Hotel,0,88,2023,July,28,13,2023-07-13,3,5,2,0.0,0,BB,FIN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Contract,96.3,0,0
HB-010680,Resort Hotel,1,103,2025,March,13,27,2025-03-27,1,1,2,0.0,0,BB,PRT,Groups,Corporate,0,0,0,E,E,0,Non Refund,495.0,,0,Transient,73.0,0,0
HB-047908,City Hotel,1,31,2024,March,10,9,2024-03-09,0,1,2,0.0,0,BB,HUN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,81.9,0,0
HB-108756,City Hotel,0,70,2025,March,13,30,2025-03-30,0,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-084656,City Hotel,0,5,2024,March,9,1,2024-03-01,0,1,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,D,1,No Deposit,1.0,,0,Transient,51.0,0,0
HB-095530,City Hotel,0,320,2024,August,33,18,2024-08-18,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-090517,City Hotel,0,247,2024,June,23,6,2024-06-06,1,1,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-060742,City Hotel,1,38,2024,November,47,19,2024-11-19,2,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.4,0,2
HB-112432,City Hotel,0,87,2025,May,21,22,2025-05-22,1,1,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,475.0,,0,Transient-Party,126.0,0,0
HB-074172,City Hotel,1,349,2023,October,39,1,2023-10-01,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-029105,Resort Hotel,0,178,2024,October,42,16,2024-10-16,2,2,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,96.0,,0,Transient,46.0,0,0
HB-100860,City Hotel,0,8,2024,November,44,2,2024-11-02,0,1,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,9.0,,0,Transient,120.0,0,2
HB-003030,Resort Hotel,1,37,2023,November,45,11,2023-11-11,0,4,2,1.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,281.0,,0,Contract,63.0,0,2
HB-105219,City Hotel,0,0,2025,February,5,2,2025-02-02,0,0,1,0.0,0,BB,PRT,Online TA,TA/TO,1,0,0,A,K,1,No Deposit,9.0,,0,Transient,0.0,0,1
HB-056353,City Hotel,1,420,2024,September,36,3,2024-09-03,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,35.0,,0,Transient,75.0,0,0
HB-105562,City Hotel,0,21,2025,February,6,7,2025-02-07,0,5,2,1.0,1,BB,ESP,Offline TA/TO,TA/TO,0,0,0,D,D,2,No Deposit,22.0,,0,Transient,98.26,0,2
HB-064245,City Hotel,1,86,2025,March,10,3,2025-03-03,0,2,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,51.35,0,1
HB-103406,City Hotel,0,1,2024,December,51,22,2024-12-22,0,1,2,0.0,0,BB,CHN,Direct,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient,96.0,0,0
HB-015953,Resort Hotel,0,0,2023,August,33,20,2023-08-20,0,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,1,0,1,D,A,0,No Deposit,196.0,,0,Transient,0.0,0,0
HB-071817,City Hotel,1,199,2025,July,28,13,2025-07-13,0,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,156.6,0,0
HB-002308,Resort Hotel,0,4,2023,October,41,9,2023-10-09,1,2,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,G,G,1,No Deposit,240.0,,0,Transient,113.33,0,1
HB-049640,City Hotel,0,109,2024,April,16,16,2024-04-16,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient,75.76,0,0
HB-070452,City Hotel,1,448,2025,June,25,17,2025-06-17,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,90.0,0,0
HB-112172,City Hotel,0,20,2025,May,21,20,2025-05-20,0,1,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,150.0,0,1
HB-048566,City Hotel,1,161,2024,March,13,25,2024-03-25,1,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,101,Transient,130.0,0,0
HB-060778,City Hotel,1,10,2024,November,47,20,2024-11-20,4,8,1,0.0,0,BB,SEN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.92,0,0
HB-038874,Resort Hotel,0,266,2025,July,31,28,2025-07-28,2,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,436.0,,0,Transient-Party,128.9,0,1
HB-001863,Resort Hotel,0,99,2023,September,38,18,2023-09-18,1,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,F,0,No Deposit,142.0,,0,Transient,81.2,0,0
HB-111344,City Hotel,0,157,2025,May,19,7,2025-05-07,2,0,2,0.0,0,SC,ZAF,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,80.1,0,0
HB-097096,City Hotel,0,38,2024,September,37,10,2024-09-10,1,1,2,0.0,0,BB,USA,Direct,Direct,0,0,0,D,D,1,No Deposit,14.0,,0,Transient,170.57,0,2
HB-043028,City Hotel,0,7,2023,September,37,12,2023-09-12,2,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,142.6,0,1
HB-067990,City Hotel,1,324,2025,May,19,11,2025-05-11,0,1,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,3
HB-045793,City Hotel,1,89,2023,November,47,23,2023-11-23,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,72.25,0,2
HB-069190,City Hotel,1,34,2025,May,22,26,2025-05-26,2,4,2,0.0,0,SC,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,1
HB-048545,City Hotel,1,78,2024,March,13,25,2024-03-25,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,154.0,,0,Transient,100.0,0,0
HB-117275,City Hotel,0,276,2025,July,31,30,2025-07-30,2,1,0,2.0,0,BB,DEU,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient,93.64,0,2
HB-046177,City Hotel,0,0,2023,December,51,21,2023-12-21,1,0,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,75.0,1,0
HB-095604,City Hotel,0,85,2024,August,33,16,2024-08-16,0,5,2,1.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,134.1,0,2
HB-065656,City Hotel,1,62,2025,April,14,6,2025-04-06,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,135.0,0,0
HB-099957,City Hotel,0,67,2024,October,42,17,2024-10-17,1,3,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,151.2,0,2
HB-033973,Resort Hotel,0,145,2025,February,9,26,2025-02-26,4,7,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,E,0,No Deposit,171.0,,0,Transient,41.51,0,0
HB-017424,Resort Hotel,0,9,2023,October,40,8,2023-10-08,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,281.0,,0,Contract,37.8,0,0
HB-009907,Resort Hotel,1,123,2025,January,4,20,2025-01-20,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,37.8,0,2
HB-069387,City Hotel,1,186,2025,May,22,30,2025-05-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,130.0,0,0
HB-011119,Resort Hotel,1,157,2025,April,17,21,2025-04-21,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,60.0,0,3
HB-114344,City Hotel,0,2,2025,June,25,20,2025-06-20,0,1,2,0.0,0,SC,FRA,Direct,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Group,150.0,0,0
HB-080470,City Hotel,1,34,2023,December,49,8,2023-12-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,0,Transient,90.0,0,0
HB-066749,City Hotel,1,123,2025,April,17,24,2025-04-24,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,123.75,0,1
HB-003241,Resort Hotel,0,21,2023,November,47,24,2023-11-24,0,1,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,38.4,0,2
HB-006484,Resort Hotel,1,40,2024,June,24,12,2024-06-12,2,5,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,194.0,0,0
HB-055577,City Hotel,1,184,2024,August,33,17,2024-08-17,0,1,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,A,7,No Deposit,9.0,,0,Transient-Party,139.5,0,1
HB-041596,City Hotel,0,9,2023,August,33,19,2023-08-19,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,81.0,0,1
HB-079908,City Hotel,0,5,2023,November,44,4,2023-11-04,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Group,70.0,0,0
HB-054583,City Hotel,1,149,2024,July,29,20,2024-07-20,0,3,2,1.0,0,BB,DNK,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,127.5,0,0
HB-044904,City Hotel,1,193,2023,October,41,15,2023-10-15,0,3,2,0.0,0,BB,,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,0,Transient,65.0,0,0
HB-066908,City Hotel,1,156,2025,April,17,26,2025-04-26,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,100.0,0,0
HB-015143,Resort Hotel,0,4,2025,March,12,20,2025-03-20,1,3,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,2,A,A,0,No Deposit,,62.0,0,Transient,35.0,0,0
HB-089235,City Hotel,0,86,2024,May,20,15,2024-05-15,2,2,2,2.0,0,BB,IRL,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,187.85,0,1
HB-116761,City Hotel,0,160,2025,July,30,23,2025-07-23,1,0,1,1.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,7.0,,0,Transient,102.35,0,0
HB-060064,City Hotel,1,11,2024,November,45,5,2024-11-05,0,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.0,0,1
HB-030768,Resort Hotel,0,128,2024,December,49,3,2024-12-03,0,1,2,0.0,0,HB,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,64.0,0,1
HB-092924,City Hotel,0,18,2024,July,28,11,2024-07-11,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,110.46,0,1
HB-006979,Resort Hotel,1,0,2024,July,29,15,2024-07-15,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,147.6,0,0
HB-043714,City Hotel,0,34,2023,September,38,23,2023-09-23,0,3,2,0.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,52.0,,33,Transient-Party,224.67,0,0
HB-037635,Resort Hotel,0,4,2025,June,25,19,2025-06-19,1,4,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,135.0,0,1
HB-022105,Resort Hotel,0,11,2024,March,12,18,2024-03-18,0,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,337.0,0,Transient-Party,0.0,0,1
HB-111823,City Hotel,0,10,2025,May,20,14,2025-05-14,2,0,1,0.0,0,SC,FRA,Direct,Direct,0,0,0,A,D,3,No Deposit,14.0,,0,Transient,101.37,0,2
HB-064329,City Hotel,1,4,2025,March,10,6,2025-03-06,1,0,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,78.4,0,0
HB-004885,Resort Hotel,1,40,2024,April,14,5,2024-04-05,0,5,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,58.0,0,1
HB-014565,Resort Hotel,0,2,2025,March,10,4,2025-03-04,0,1,2,0.0,0,BB,,Direct,TA/TO,0,0,4,D,D,0,No Deposit,250.0,,0,Transient,68.0,0,2
HB-069046,City Hotel,1,262,2025,May,21,24,2025-05-24,0,4,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,138.6,0,2
HB-019037,Resort Hotel,0,1,2023,December,49,5,2023-12-05,1,1,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,F,F,2,No Deposit,250.0,,0,Transient,78.0,0,1
HB-084921,City Hotel,0,1,2024,March,9,2,2024-03-02,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,9.0,,0,Transient,116.0,0,1
HB-041925,City Hotel,0,55,2023,August,34,26,2023-08-26,0,2,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,0.0,0,0
HB-035524,Resort Hotel,0,184,2025,April,16,19,2025-04-19,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient-Party,100.86,1,2
HB-108546,City Hotel,0,158,2025,March,13,27,2025-03-27,1,1,2,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,95.0,0,1
HB-001255,Resort Hotel,0,13,2023,August,34,21,2023-08-21,2,4,2,0.0,0,FB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,236.0,0,0
HB-099616,City Hotel,0,3,2024,October,42,15,2024-10-15,0,1,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,7.0,,0,Transient,157.27,0,1
HB-059997,City Hotel,1,305,2024,November,45,4,2024-11-04,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,89.0,0,0
HB-060520,City Hotel,1,238,2024,November,46,13,2024-11-13,2,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,55.08,0,0
HB-093477,City Hotel,0,177,2024,July,29,19,2024-07-19,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.3,0,1
HB-114035,City Hotel,0,36,2025,June,24,13,2025-06-13,0,3,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,139.5,1,0
HB-089031,City Hotel,0,104,2024,May,20,14,2024-05-14,2,1,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,159.3,0,2
HB-081184,City Hotel,0,7,2023,December,49,4,2023-12-04,0,2,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,72.25,0,1
HB-091249,City Hotel,0,150,2024,June,24,16,2024-06-16,0,3,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,90.0,0,1
HB-069747,City Hotel,1,7,2025,June,23,5,2025-06-05,1,3,1,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,200.0,0,1
HB-105681,City Hotel,0,25,2025,February,6,9,2025-02-09,2,3,2,0.0,1,BB,BRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,108.8,0,2
HB-077858,City Hotel,0,16,2023,September,39,25,2023-09-25,2,2,2,0.0,0,BB,ITA,Groups,TA/TO,0,0,0,A,D,1,No Deposit,1.0,,0,Transient-Party,170.0,0,0
HB-059082,City Hotel,1,192,2024,October,43,21,2024-10-21,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,29.0,,0,Transient-Party,95.0,0,0
HB-026247,Resort Hotel,0,165,2024,October,43,22,2024-10-22,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,,,0,Transient,57.0,0,0
HB-042181,City Hotel,0,14,2023,September,35,2,2023-09-02,0,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,10.0,,0,Transient,94.5,0,1
HB-079519,City Hotel,0,25,2023,October,43,25,2023-10-25,2,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,114.0,0,1
HB-105520,City Hotel,0,2,2025,February,6,6,2025-02-06,1,4,2,0.0,0,SC,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,54.71,0,1
HB-022470,Resort Hotel,0,68,2024,March,12,24,2024-03-24,0,3,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,120.0,0,2
HB-037882,Resort Hotel,0,44,2025,June,25,22,2025-06-22,2,8,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,531.0,,0,Transient,108.3,0,2
HB-042496,City Hotel,1,1,2023,September,36,6,2023-09-06,2,0,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,6.0,0,0
HB-015216,Resort Hotel,1,267,2023,September,39,26,2023-09-26,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,96.0,,0,Transient,54.99,0,0
HB-065952,City Hotel,1,88,2025,April,15,10,2025-04-10,1,4,1,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,100.44,0,0
HB-033327,Resort Hotel,0,0,2025,February,8,19,2025-02-19,1,0,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,,0,Transient-Party,80.0,0,0
HB-116964,City Hotel,0,138,2025,July,30,24,2025-07-24,1,3,1,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,78.66,0,0
HB-005987,Resort Hotel,1,40,2024,May,20,18,2024-05-18,0,2,1,0.0,0,BB,PRT,Groups,Corporate,0,0,0,A,A,0,Non Refund,,,0,Transient,55.0,0,0
HB-040633,City Hotel,1,28,2023,August,31,3,2023-08-03,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-057324,City Hotel,0,429,2024,September,39,23,2024-09-23,0,2,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,330,Transient-Party,65.0,0,0
HB-058736,City Hotel,1,32,2024,October,42,15,2024-10-15,2,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,161.33,0,0
HB-024923,Resort Hotel,0,118,2024,June,23,8,2024-06-08,0,1,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,E,0,No Deposit,251.0,,0,Transient,78.0,0,0
HB-119273,City Hotel,0,22,2025,August,35,28,2025-08-28,1,3,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,160.0,0,0
HB-068960,City Hotel,1,20,2025,May,21,24,2025-05-24,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,87.0,,0,Transient-Party,120.0,0,0
HB-024050,Resort Hotel,0,6,2024,May,19,11,2024-05-11,0,0,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,E,I,0,No Deposit,,110.0,0,Transient,0.0,0,0
HB-100501,City Hotel,0,69,2024,October,44,28,2024-10-28,0,1,1,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,57.52,0,1
HB-118560,City Hotel,0,0,2025,August,34,21,2025-08-21,1,0,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,198.0,0,0
HB-063455,City Hotel,1,67,2025,February,7,12,2025-02-12,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,80.0,0,0
HB-089927,City Hotel,0,1,2024,May,21,26,2024-05-26,1,3,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,9.0,,0,Transient,136.18,0,0
HB-041258,City Hotel,1,39,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,101.5,0,0
HB-008379,Resort Hotel,1,29,2024,September,39,25,2024-09-25,1,0,2,0.0,0,BB,MAR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,89.0,0,0
HB-089607,City Hotel,0,3,2025,June,24,11,2025-06-11,2,2,1,0.0,0,BB,DEU,Aviation,Corporate,1,0,1,A,A,0,No Deposit,,153.0,0,Transient,95.0,0,0
HB-010314,Resort Hotel,1,82,2025,February,9,25,2025-02-25,2,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,42.0,0,2
HB-060588,City Hotel,1,26,2024,November,46,16,2024-11-16,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,350.0,0,Transient-Party,77.0,0,0
HB-003643,Resort Hotel,0,49,2023,December,52,28,2023-12-28,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,89.5,1,2
HB-080687,City Hotel,0,55,2023,November,46,18,2023-11-18,0,4,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Transient,60.0,0,1
HB-098316,City Hotel,0,59,2024,September,39,26,2024-09-26,1,1,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,135.9,0,0
HB-026726,Resort Hotel,0,26,2024,August,31,2,2024-08-02,2,5,2,2.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,C,1,No Deposit,240.0,,0,Transient,313.71,0,1
HB-006260,Resort Hotel,0,105,2024,May,22,31,2024-05-31,2,5,2,1.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,1,No Deposit,314.0,,0,Transient,131.5,0,1
HB-029836,Resort Hotel,0,30,2024,October,44,31,2024-10-31,2,5,2,0.0,0,HB,SRB,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,69.04,0,1
HB-099106,City Hotel,0,3,2024,October,40,1,2024-10-01,3,6,2,0.0,0,BB,AGO,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,158.0,0,0
HB-094538,City Hotel,0,199,2024,August,31,2,2024-08-02,0,4,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,7.0,,0,Transient,70.44,0,2
HB-069603,City Hotel,1,129,2025,June,23,2,2025-06-02,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,154.0,,0,Transient,130.0,0,0
HB-046364,City Hotel,1,11,2023,December,52,30,2023-12-30,0,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,129.5,0,0
HB-068008,City Hotel,1,319,2025,May,19,11,2025-05-11,0,3,3,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,193.5,0,2
HB-098939,City Hotel,0,19,2024,October,40,5,2024-10-05,0,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,114.73,0,1
HB-103671,City Hotel,0,137,2024,December,52,24,2024-12-24,2,3,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,146.1,0,2
HB-080142,City Hotel,0,47,2023,November,45,11,2023-11-11,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-044198,City Hotel,0,164,2023,October,40,2,2023-10-02,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,19.0,,0,Transient-Party,100.0,0,0
HB-091430,City Hotel,0,0,2024,June,25,20,2024-06-20,1,1,1,0.0,0,BB,ITA,Direct,Direct,0,0,0,A,D,1,No Deposit,,,0,Transient,123.25,0,0
HB-095489,City Hotel,0,320,2024,August,33,18,2024-08-18,0,2,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,90.0,0,0
HB-042565,City Hotel,0,24,2023,September,36,7,2023-09-07,1,2,2,1.0,1,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,E,0,No Deposit,22.0,,0,Transient,99.5,0,0
HB-068885,City Hotel,1,26,2025,May,21,22,2025-05-22,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,128.0,0,0
HB-071414,City Hotel,1,282,2025,July,27,5,2025-07-05,0,2,2,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,141.3,0,1
HB-017140,Resort Hotel,0,207,2023,September,39,26,2023-09-26,1,1,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,208.0,,0,Transient,74.0,0,1
HB-090328,City Hotel,0,1,2024,June,22,2,2024-06-02,0,3,2,0.0,0,BB,DEU,Online TA,Corporate,0,0,0,A,D,0,No Deposit,,263.0,0,Transient,120.0,0,1
HB-041472,City Hotel,0,46,2023,August,33,17,2023-08-17,1,1,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,60.0,0,0
HB-115160,City Hotel,0,167,2025,June,27,30,2025-06-30,0,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,112.05,0,1
HB-098936,City Hotel,0,49,2024,October,40,5,2024-10-05,0,2,1,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,113.4,0,2
HB-097630,City Hotel,0,318,2024,September,38,16,2024-09-16,1,2,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,16.0,,0,Transient,80.75,0,0
HB-094724,City Hotel,0,11,2024,August,32,8,2024-08-08,1,0,2,2.0,0,BB,USA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,7.0,,0,Transient,191.35,0,1
HB-113623,City Hotel,0,4,2025,June,24,9,2025-06-09,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,124.5,0,0
HB-070293,City Hotel,1,201,2025,June,24,14,2025-06-14,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-050985,City Hotel,1,114,2024,May,19,12,2024-05-12,2,4,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,115.25,0,0
HB-070491,City Hotel,1,150,2025,June,25,17,2025-06-17,2,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,120.0,0,0
HB-005720,Resort Hotel,0,236,2024,May,19,12,2024-05-12,0,3,1,0.0,0,BB,IRL,Groups,TA/TO,0,0,0,A,A,1,No Deposit,315.0,,0,Transient-Party,48.0,0,0
HB-024062,Resort Hotel,0,73,2024,September,39,26,2024-09-26,3,7,2,0.0,0,BB,IRL,Direct,Direct,1,0,0,D,D,0,No Deposit,,,0,Transient,82.0,0,3
HB-118072,City Hotel,0,23,2025,August,32,8,2025-08-08,1,5,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,0
HB-082008,City Hotel,1,115,2024,March,12,20,2024-03-20,2,0,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,41.0,,22,Transient,70.0,0,0
HB-103532,City Hotel,0,1,2024,December,52,26,2024-12-26,1,0,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,115.0,0,3
HB-059930,City Hotel,1,304,2024,November,44,3,2024-11-03,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,89.0,0,0
HB-055137,City Hotel,1,218,2024,August,32,6,2024-08-06,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.3,0,1
HB-087822,City Hotel,0,101,2024,April,17,26,2024-04-26,0,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,35.0,,0,Transient-Party,98.0,0,0
HB-015786,Resort Hotel,0,32,2023,July,30,27,2023-07-27,1,5,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,250.0,,0,Transient,147.0,0,0
HB-096514,City Hotel,0,15,2024,August,35,31,2024-08-31,0,4,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,116.0,0,1
HB-031547,Resort Hotel,0,71,2025,January,1,1,2025-01-01,1,0,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,4,No Deposit,5.0,,0,Transient-Party,83.6,0,1
HB-076987,City Hotel,0,1,2023,August,34,23,2023-08-23,1,0,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,67.0,0,0
HB-108892,City Hotel,0,62,2025,March,14,31,2025-03-31,1,2,3,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,16.0,,0,Transient,116.1,0,1
HB-101290,City Hotel,0,75,2024,November,45,6,2024-11-06,2,2,1,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,112.28,0,3
HB-037147,Resort Hotel,0,313,2025,June,23,4,2025-06-04,2,3,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,314.0,,0,Transient,79.56,1,0
HB-101890,City Hotel,0,214,2024,November,47,20,2024-11-20,2,1,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,D,2,No Deposit,,233.0,0,Transient,85.0,0,1
HB-109883,City Hotel,0,49,2025,April,16,16,2025-04-16,2,0,2,0.0,0,SC,PRY,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,0
HB-064079,City Hotel,1,88,2025,March,9,1,2025-03-01,0,3,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.2,0,0
HB-016495,Resort Hotel,0,124,2023,August,33,17,2023-08-17,4,10,2,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,128.0,,0,Contract,110.7,0,1
HB-041635,City Hotel,0,1,2023,August,33,20,2023-08-20,0,1,1,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,A,0,No Deposit,,45.0,0,Transient,0.0,0,0
HB-057936,City Hotel,1,285,2024,October,40,3,2024-10-03,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,24,Transient,100.0,0,0
HB-038692,Resort Hotel,0,125,2025,July,28,13,2025-07-13,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,106.85,0,0
HB-060399,City Hotel,1,10,2024,November,45,10,2024-11-10,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,120.0,0,0
HB-076730,City Hotel,0,4,2025,July,29,16,2025-07-16,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,1,6,70,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,1
HB-001362,Resort Hotel,1,41,2023,August,34,26,2023-08-26,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,173.5,0,3
HB-067047,City Hotel,1,111,2025,April,17,27,2025-04-27,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,0,Transient,120.0,0,0
HB-003302,Resort Hotel,0,22,2023,December,49,4,2023-12-04,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,52.4,0,2
HB-014660,Resort Hotel,0,2,2024,December,51,16,2024-12-16,0,2,2,0.0,0,BB,,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,0
HB-029486,Resort Hotel,0,0,2024,October,44,28,2024-10-28,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,,0,Transient,85.0,0,0
HB-014670,Resort Hotel,0,0,2025,May,20,15,2025-05-15,1,0,1,0.0,0,BB,PRT,Direct,Direct,0,0,1,A,A,0,No Deposit,,,0,Transient,47.0,0,0
HB-110221,City Hotel,0,134,2025,April,17,22,2025-04-22,1,1,2,1.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,134.5,0,2
HB-096488,City Hotel,0,42,2024,August,35,30,2024-08-30,0,4,3,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,142.2,0,2
HB-054840,City Hotel,1,386,2024,July,30,28,2024-07-28,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-116179,City Hotel,0,277,2025,July,28,13,2025-07-13,0,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,1
HB-015780,Resort Hotel,0,56,2023,July,30,25,2023-07-25,2,6,2,0.0,0,BB,CHE,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,36.0,,0,Transient,102.45,0,0
HB-094435,City Hotel,0,170,2024,August,31,1,2024-08-01,1,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,105.3,0,0
HB-111023,City Hotel,0,20,2025,May,18,4,2025-05-04,0,1,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.0,0,1
HB-098930,City Hotel,0,3,2024,October,40,6,2024-10-06,0,1,1,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,B,0,No Deposit,,45.0,0,Transient,0.0,0,0
HB-046003,City Hotel,0,112,2023,December,49,4,2023-12-04,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,52.85,0,1
HB-002212,Resort Hotel,1,74,2023,October,40,5,2023-10-05,3,6,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,86.0,0,2
HB-087097,City Hotel,0,52,2024,April,15,9,2024-04-09,2,3,2,0.0,0,BB,AUT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,80.75,0,0
HB-010303,Resort Hotel,1,78,2025,February,9,25,2025-02-25,2,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,42.0,0,1
HB-092293,City Hotel,0,132,2024,July,27,1,2024-07-01,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,72.25,0,0
HB-091461,City Hotel,0,58,2024,June,25,21,2024-06-21,0,1,2,1.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,125.1,1,1
HB-047234,City Hotel,0,159,2024,February,7,13,2024-02-13,0,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,70.0,0,0
HB-104835,City Hotel,0,12,2025,January,3,16,2025-01-16,2,5,3,0.0,0,BB,HUN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,98.12,0,1
HB-108801,City Hotel,0,165,2025,April,14,1,2025-04-01,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,1
HB-101889,City Hotel,0,66,2024,November,47,18,2024-11-18,0,2,3,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,105.0,0,1
HB-009226,Resort Hotel,1,70,2024,November,44,3,2024-11-03,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,55.8,0,3
HB-006681,Resort Hotel,0,227,2024,June,25,23,2024-06-23,3,8,2,0.0,0,HB,POL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,315.0,,0,Transient,94.0,0,0
HB-074152,City Hotel,1,342,2023,September,38,24,2023-09-24,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-073830,City Hotel,1,300,2023,August,32,13,2023-08-13,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-073195,City Hotel,1,77,2025,August,33,16,2025-08-16,0,3,3,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,200.0,0,0
HB-087826,City Hotel,0,101,2024,April,17,26,2024-04-26,0,1,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,35.0,,0,Transient-Party,74.0,0,0
HB-054428,City Hotel,1,118,2024,July,29,15,2024-07-15,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.45,0,0
HB-019919,Resort Hotel,0,0,2024,January,2,8,2024-01-08,0,1,2,0.0,0,BB,USA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,36.0,,0,Transient,31.2,0,0
HB-013060,Resort Hotel,1,137,2025,July,31,29,2025-07-29,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,178.29,0,1
HB-111513,City Hotel,0,85,2025,May,19,10,2025-05-10,0,2,1,0.0,0,BB,AUT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,105.0,0,0
HB-003306,Resort Hotel,0,66,2023,December,49,5,2023-12-05,1,1,2,0.0,0,FB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,155.0,,0,Transient-Party,64.0,0,0
HB-051328,City Hotel,1,29,2024,May,20,18,2024-05-18,0,1,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,156.0,0,0
HB-116851,City Hotel,0,64,2025,July,30,23,2025-07-23,2,1,2,0.0,0,BB,ARG,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient-Party,129.9,0,1
HB-048172,City Hotel,1,91,2024,March,12,18,2024-03-18,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,20,Transient,75.0,0,0
HB-039103,Resort Hotel,0,27,2025,August,32,6,2025-08-06,2,0,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,227.0,0,2
HB-056060,City Hotel,1,199,2024,August,35,28,2024-08-28,1,0,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,128.7,0,1
HB-106210,City Hotel,0,2,2025,February,8,22,2025-02-22,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,219.0,0,Transient,80.0,0,2
HB-050861,City Hotel,1,8,2024,May,19,10,2024-05-10,0,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,108.57,0,0
HB-112133,City Hotel,0,90,2025,May,20,16,2025-05-16,0,4,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.25,0,0
HB-000127,Resort Hotel,0,8,2023,July,27,4,2023-07-04,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,123.0,0,0
HB-060387,City Hotel,1,109,2024,November,45,8,2024-11-08,0,4,1,0.0,0,BB,USA,Offline TA/TO,GDS,0,0,0,E,E,0,No Deposit,195.0,,0,Transient,216.0,0,1
HB-022450,Resort Hotel,0,121,2024,March,12,24,2024-03-24,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,77.4,0,1
HB-067282,City Hotel,1,79,2025,May,18,1,2025-05-01,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-096046,City Hotel,0,256,2024,August,35,26,2024-08-26,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,72.25,0,1
HB-080653,City Hotel,0,22,2023,November,46,19,2023-11-19,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,95.0,0,1
HB-084720,City Hotel,0,115,2024,February,9,27,2024-02-27,2,3,1,0.0,0,BB,MAR,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,134.0,,0,Transient-Party,76.0,0,0
HB-087944,City Hotel,0,3,2024,April,17,28,2024-04-28,0,1,1,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,128.0,1,0
HB-036576,Resort Hotel,0,93,2025,May,20,17,2025-05-17,2,5,2,0.0,0,FB,FRA,Direct,Direct,0,0,0,E,E,1,No Deposit,250.0,,0,Transient-Party,177.0,1,0
HB-022934,Resort Hotel,0,49,2024,April,14,1,2024-04-01,2,7,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient-Party,71.0,0,1
HB-027239,Resort Hotel,0,52,2024,August,33,17,2024-08-17,2,5,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,213.86,0,1
HB-074878,City Hotel,1,153,2023,August,31,3,2023-08-03,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-032894,Resort Hotel,0,31,2025,February,6,5,2025-02-05,2,2,2,0.0,0,HB,JPN,Direct,Direct,0,0,0,D,D,1,No Deposit,250.0,,0,Transient,78.6,0,0
HB-092290,City Hotel,0,232,2024,July,27,2,2024-07-02,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Contract,131.4,0,1
HB-009241,Resort Hotel,1,23,2024,November,45,5,2024-11-05,1,1,2,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,D,1,No Deposit,,,0,Transient,0.0,0,0
HB-002363,Resort Hotel,0,4,2023,October,41,10,2023-10-10,1,1,2,0.0,0,HB,ESP,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,101.5,0,1
HB-085793,City Hotel,0,5,2024,March,12,19,2024-03-19,2,1,1,0.0,0,BB,USA,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,79.17,0,0
HB-053055,City Hotel,1,239,2024,June,24,15,2024-06-15,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,80,Transient,112.2,0,0
HB-096638,City Hotel,0,217,2024,September,35,1,2024-09-01,1,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,27.0,,0,Transient-Party,80.75,0,1
HB-001047,Resort Hotel,1,22,2023,August,32,11,2023-08-11,1,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,241.0,0,0
HB-074664,City Hotel,1,359,2023,October,41,11,2023-10-11,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-099179,City Hotel,0,28,2024,October,41,8,2024-10-08,1,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,E,F,0,No Deposit,86.0,,0,Transient,171.87,0,0
HB-044477,City Hotel,1,97,2023,October,40,5,2023-10-05,1,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,140.0,0,0
HB-078325,City Hotel,0,105,2024,September,39,28,2024-09-28,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,3,17,A,A,1,No Deposit,,40.0,0,Transient,65.0,0,0
HB-073870,City Hotel,1,314,2023,August,34,27,2023-08-27,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-112897,City Hotel,0,11,2025,May,22,29,2025-05-29,1,0,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.0,0,2
HB-002362,Resort Hotel,0,4,2023,October,41,10,2023-10-10,1,1,2,1.0,0,BB,ESP,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient,102.5,1,3
HB-042138,City Hotel,0,16,2023,August,35,31,2023-08-31,1,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.5,0,0
HB-097404,City Hotel,0,47,2024,September,37,13,2024-09-13,0,3,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,281.0,,0,Transient-Party,120.0,0,0
HB-057819,City Hotel,1,167,2024,October,40,1,2024-10-01,2,1,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.1,0,0
HB-112386,City Hotel,0,18,2025,May,21,22,2025-05-22,1,1,3,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,D,D,1,No Deposit,315.0,,0,Transient-Party,165.0,0,1
HB-048313,City Hotel,1,60,2024,March,12,20,2024-03-20,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,75.0,0,0
HB-067657,City Hotel,1,233,2025,May,19,5,2025-05-05,2,2,2,0.0,0,HB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.6,0,0
HB-118735,City Hotel,0,115,2025,August,34,20,2025-08-20,2,3,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,3,No Deposit,98.0,,0,Transient-Party,115.0,0,0
HB-088432,City Hotel,0,10,2024,May,18,5,2024-05-05,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,156.0,0,1
HB-103227,City Hotel,0,234,2024,December,50,12,2024-12-12,1,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,76.84,0,1
HB-023941,Resort Hotel,0,2,2025,March,11,11,2025-03-11,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,1,0,2,E,E,0,No Deposit,240.0,,0,Transient-Party,97.0,1,2
HB-099390,City Hotel,0,0,2024,October,41,12,2024-10-12,0,1,1,0.0,0,SC,USA,Direct,Direct,0,0,0,B,B,1,No Deposit,,,0,Transient,136.0,0,0
HB-052401,City Hotel,1,163,2024,June,23,5,2024-06-05,2,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,171.0,,0,Transient,100.0,0,0
HB-054203,City Hotel,1,18,2024,July,28,8,2024-07-08,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,166.0,0,0
HB-042887,City Hotel,1,72,2023,September,37,11,2023-09-11,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,126.0,0,0
HB-012121,Resort Hotel,1,97,2025,June,24,14,2025-06-14,0,4,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,C,C,1,No Deposit,240.0,,0,Transient,160.0,0,1
HB-025965,Resort Hotel,0,0,2024,July,29,16,2024-07-16,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,B,0,No Deposit,,,0,Transient,157.0,1,0
HB-007620,Resort Hotel,1,143,2024,August,33,16,2024-08-16,4,10,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,177.79,0,0
HB-020080,Resort Hotel,0,8,2024,January,3,15,2024-01-15,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,54.0,1,1
HB-084690,City Hotel,0,117,2024,March,9,2,2024-03-02,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,7.0,,0,Transient,66.14,0,0
HB-045298,City Hotel,0,69,2023,October,43,25,2023-10-25,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,D,0,No Deposit,37.0,,58,Transient-Party,85.67,0,0
HB-006609,Resort Hotel,1,177,2024,June,25,20,2024-06-20,1,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,Non Refund,240.0,,0,Transient,85.5,0,0
HB-032599,Resort Hotel,0,18,2025,January,5,27,2025-01-27,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,467.0,,0,Transient,52.56,0,0
HB-021051,Resort Hotel,0,0,2024,November,48,29,2024-11-29,0,1,2,0.0,0,BB,PRT,Online TA,Direct,1,0,2,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,0
HB-097858,City Hotel,0,27,2024,September,38,20,2024-09-20,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,3,No Deposit,288.0,,0,Transient-Party,95.0,0,0
HB-023400,Resort Hotel,0,105,2024,April,17,22,2024-04-22,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,52.2,0,1
HB-110659,City Hotel,0,21,2025,April,18,29,2025-04-29,0,1,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,115.0,0,2
HB-054355,City Hotel,1,372,2024,July,28,14,2024-07-14,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-023731,Resort Hotel,0,3,2024,April,18,29,2024-04-29,1,2,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,C,0,No Deposit,,,0,Transient-Party,97.67,0,0
HB-001696,Resort Hotel,0,170,2023,September,36,10,2023-09-10,1,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,E,0,No Deposit,26.0,,0,Contract,70.98,0,0
HB-066783,City Hotel,1,53,2025,April,17,26,2025-04-26,0,1,2,2.0,0,BB,BRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,230.0,0,0
HB-009372,Resort Hotel,1,110,2024,November,47,19,2024-11-19,2,3,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,73.8,0,0
HB-009836,Resort Hotel,1,161,2025,January,2,9,2025-01-09,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,37.8,0,0
HB-102946,City Hotel,0,49,2024,December,49,8,2024-12-08,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.1,0,1
HB-026458,Resort Hotel,0,65,2024,July,31,29,2024-07-29,1,2,2,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,242.0,,0,Transient,192.67,0,1
HB-087912,City Hotel,0,32,2024,April,17,27,2024-04-27,0,1,2,1.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,9.0,,0,Transient,165.15,0,0
HB-070117,City Hotel,1,101,2025,June,24,10,2025-06-10,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,14.0,,0,Transient,126.0,0,1
HB-100189,City Hotel,0,189,2024,October,42,20,2024-10-20,2,3,2,1.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,98.5,0,0
HB-081753,City Hotel,1,113,2024,February,8,25,2024-02-25,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,44,Transient,75.0,0,0
HB-099166,City Hotel,0,51,2024,October,41,8,2024-10-08,1,1,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.5,0,1
HB-006570,Resort Hotel,1,62,2024,June,25,18,2024-06-18,2,2,3,1.0,0,BB,CN,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,194.0,0,0
HB-082533,City Hotel,0,70,2023,December,52,29,2023-12-29,0,4,2,1.0,0,HB,FRA,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,190.78,0,2
HB-101360,City Hotel,0,103,2024,November,45,7,2024-11-07,1,3,1,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,A,B,1,No Deposit,8.0,,0,Transient,186.0,0,2
HB-052442,City Hotel,1,0,2024,June,23,7,2024-06-07,0,1,2,1.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.0,0,0
HB-049712,City Hotel,1,57,2024,April,16,17,2024-04-17,2,5,2,0.0,0,HB,ISR,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,143.29,0,0
HB-043657,City Hotel,0,69,2023,September,38,22,2023-09-22,0,2,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,65,Transient-Party,106.0,0,0
HB-096690,City Hotel,0,48,2024,September,36,4,2024-09-04,2,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient,109.8,0,1
HB-094315,City Hotel,0,6,2025,July,29,18,2025-07-18,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,6,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,1
HB-037415,Resort Hotel,0,182,2025,June,24,13,2025-06-13,0,4,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,410.0,,0,Transient,58.2,0,0
HB-024702,Resort Hotel,0,3,2024,December,50,13,2024-12-13,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,1,0,1,A,D,0,No Deposit,240.0,,0,Transient,43.0,0,1
HB-010745,Resort Hotel,1,23,2025,March,14,31,2025-03-31,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,70.0,0,0
HB-111428,City Hotel,0,34,2025,May,19,9,2025-05-09,0,2,1,0.0,0,BB,TUR,Groups,TA/TO,0,0,0,A,A,2,No Deposit,39.0,,0,Transient-Party,130.0,0,0
HB-052107,City Hotel,1,57,2024,May,22,31,2024-05-31,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,120.0,0,0
HB-098513,City Hotel,0,36,2024,September,39,28,2024-09-28,0,3,2,0.0,0,BB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,87.0,0,0
HB-106819,City Hotel,0,8,2025,February,9,27,2025-02-27,1,3,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,3
HB-081188,City Hotel,0,6,2023,December,48,3,2023-12-03,0,3,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,81.67,0,0
HB-006352,Resort Hotel,1,161,2024,June,23,4,2024-06-04,2,6,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,72.0,0,1
HB-096860,City Hotel,0,56,2024,September,36,5,2024-09-05,1,3,1,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,123.98,0,2
HB-081145,City Hotel,0,106,2024,November,45,6,2024-11-06,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,D,A,4,No Deposit,,107.0,0,Transient-Party,103.0,0,0
HB-099215,City Hotel,0,110,2024,October,41,9,2024-10-09,1,0,1,0.0,0,BB,AUS,Offline TA/TO,TA/TO,0,0,0,A,K,1,No Deposit,234.0,,0,Transient-Party,120.0,0,0
HB-007501,Resort Hotel,1,19,2024,August,33,12,2024-08-12,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,225.67,0,0
HB-059814,City Hotel,1,54,2024,November,44,2,2024-11-02,1,4,2,0.0,0,SC,POL,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,85.6,0,3
HB-103978,City Hotel,0,294,2024,December,52,29,2024-12-29,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,82.11,0,1
HB-038502,Resort Hotel,0,158,2025,July,29,16,2025-07-16,2,2,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,410.0,,0,Transient,118.0,0,0
HB-091994,City Hotel,0,127,2024,June,26,27,2024-06-27,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.3,0,1
HB-051092,City Hotel,0,132,2024,May,20,13,2024-05-13,2,2,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,113.05,0,1
HB-095676,City Hotel,0,24,2024,August,34,20,2024-08-20,1,1,2,0.0,0,SC,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,139.0,0,2
HB-065133,City Hotel,1,278,2025,March,13,25,2025-03-25,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient,90.0,0,0
HB-106548,City Hotel,0,28,2025,February,8,21,2025-02-21,0,5,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,123.08,0,2
HB-055072,City Hotel,1,391,2024,August,31,4,2024-08-04,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-099502,City Hotel,0,6,2025,June,25,20,2025-06-20,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,4,A,A,0,No Deposit,,40.0,0,Transient,67.0,0,1
HB-042961,City Hotel,0,168,2023,September,37,11,2023-09-11,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,D,1,No Deposit,1.0,,0,Transient-Party,50.0,0,0
HB-048114,City Hotel,1,46,2024,March,11,17,2024-03-17,0,3,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,106.8,0,1
HB-046193,City Hotel,0,7,2023,December,51,23,2023-12-23,2,5,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,59.14,0,0
HB-118218,City Hotel,0,34,2025,August,33,16,2025-08-16,0,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,160.0,0,1
HB-054306,City Hotel,1,187,2024,July,28,11,2024-07-11,2,5,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,99.45,0,1
HB-067938,City Hotel,1,6,2025,May,19,10,2025-05-10,0,1,2,0.0,0,BB,PRT,Groups,Corporate,0,0,0,A,A,0,Non Refund,47.0,,0,Transient,90.0,0,0
HB-080001,City Hotel,1,23,2023,November,46,13,2023-11-13,1,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Contract,101.0,0,2
HB-085680,City Hotel,0,115,2024,March,12,18,2024-03-18,0,2,1,0.0,0,HB,FRA,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,70.0,0,0
HB-112376,City Hotel,0,20,2025,May,21,23,2025-05-23,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,150.0,0,1
HB-055426,City Hotel,1,188,2024,August,33,13,2024-08-13,1,1,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.3,0,0
HB-069820,City Hotel,1,134,2025,June,23,7,2025-06-07,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,110.0,0,0
HB-050631,City Hotel,1,302,2024,May,18,5,2024-05-05,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-030330,Resort Hotel,0,6,2024,November,46,13,2024-11-13,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Transient,62.12,0,0
HB-063857,City Hotel,1,58,2025,February,8,23,2025-02-23,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,132.0,,0,Transient,78.0,0,0
HB-042713,City Hotel,0,69,2023,September,36,9,2023-09-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-027390,Resort Hotel,0,31,2024,August,34,22,2024-08-22,1,5,3,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,224.07,0,1
HB-022253,Resort Hotel,0,10,2024,March,11,15,2024-03-15,2,5,2,0.0,0,HB,IRL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,115.0,,0,Transient,60.13,0,0
HB-076761,City Hotel,0,0,2023,August,32,8,2023-08-08,1,1,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,75.0,0,0
HB-100994,City Hotel,0,50,2024,November,45,4,2024-11-04,0,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,97.2,0,1
HB-008311,Resort Hotel,1,385,2024,September,38,21,2024-09-21,0,4,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,66.0,0,0
HB-035500,Resort Hotel,0,168,2025,April,16,19,2025-04-19,1,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,67.6,1,1
HB-084886,City Hotel,0,1,2024,March,10,5,2024-03-05,0,1,2,0.0,0,SC,CHE,Online TA,Direct,0,0,0,A,A,2,No Deposit,,,0,Transient,98.0,0,0
HB-057337,City Hotel,1,59,2024,September,39,24,2024-09-24,1,1,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,168.3,0,0
HB-013148,Resort Hotel,1,231,2025,August,31,2,2025-08-02,2,4,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,183.33,0,1
HB-080781,City Hotel,1,180,2024,April,15,13,2024-04-13,0,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,21.0,,38,Transient,125.0,0,0
HB-116262,City Hotel,0,5,2025,July,29,16,2025-07-16,1,0,2,0.0,0,BB,CN,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,115.0,0,0
HB-051503,City Hotel,1,211,2024,May,21,20,2024-05-20,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,111,Transient,100.0,0,0
HB-027423,Resort Hotel,0,95,2024,August,34,22,2024-08-22,2,5,3,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,15.0,,0,Transient,203.8,0,0
HB-036157,Resort Hotel,0,86,2025,May,19,10,2025-05-10,0,2,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,65.45,0,1
HB-110391,City Hotel,0,94,2025,April,16,19,2025-04-19,2,6,2,0.0,0,HB,DEU,Direct,Direct,0,0,0,D,D,1,No Deposit,14.0,,0,Transient,170.3,0,1
HB-051672,City Hotel,1,158,2024,May,21,24,2024-05-24,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,31,Transient,130.0,0,0
HB-041402,City Hotel,1,131,2023,August,33,15,2023-08-15,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-038896,Resort Hotel,0,52,2025,July,31,31,2025-07-31,1,1,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,E,F,0,No Deposit,241.0,,0,Transient,235.6,0,1
HB-027229,Resort Hotel,0,208,2024,August,33,13,2024-08-13,4,6,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,118.24,0,2
HB-095144,City Hotel,0,0,2024,August,33,14,2024-08-14,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,B,0,No Deposit,,,0,Transient,135.0,0,0
HB-004651,Resort Hotel,1,106,2024,March,12,24,2024-03-24,1,3,2,0.0,0,FB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,68.0,,0,Transient,84.0,0,0
HB-103665,City Hotel,0,55,2024,December,52,24,2024-12-24,2,3,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.24,0,2
HB-043145,City Hotel,0,12,2023,September,37,15,2023-09-15,2,7,1,0.0,0,BB,USA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,130.22,0,1
HB-106329,City Hotel,0,0,2025,February,8,23,2025-02-23,0,1,1,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,88.2,0,0
HB-077295,City Hotel,0,256,2023,September,37,14,2023-09-14,1,2,2,0.0,0,BB,SWE,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,4.0,,0,Transient-Party,76.67,0,0
HB-051959,City Hotel,0,316,2024,May,21,26,2024-05-26,0,3,2,0.0,0,BB,AUT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,110.0,0,0
HB-030403,Resort Hotel,0,115,2024,November,46,17,2024-11-17,1,3,2,0.0,0,BB,IRL,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,36.0,0,0
HB-036734,Resort Hotel,0,388,2025,May,21,25,2025-05-25,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,E,E,0,No Deposit,96.0,,0,Transient-Party,72.0,0,0
HB-101918,City Hotel,0,65,2024,November,47,18,2024-11-18,0,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-064574,City Hotel,1,52,2025,March,11,13,2025-03-13,1,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,56.0,,0,Transient,80.0,0,0
HB-029898,Resort Hotel,0,26,2024,November,44,2,2024-11-02,2,5,2,0.0,0,Undefined,ITA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,314.0,,0,Transient,87.65,0,0
HB-074315,City Hotel,1,262,2023,July,27,6,2023-07-06,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Contract,62.0,0,0
HB-024122,Resort Hotel,0,7,2024,May,19,11,2024-05-11,0,1,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,,405.0,0,Transient-Party,70.0,0,0
HB-004718,Resort Hotel,1,43,2024,March,13,30,2024-03-30,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,60.0,0,1
HB-116407,City Hotel,0,142,2025,July,29,16,2025-07-16,2,2,1,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,1
HB-090891,City Hotel,0,140,2024,June,23,9,2024-06-09,1,3,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,113.48,0,0
HB-034533,Resort Hotel,0,133,2025,March,11,15,2025-03-15,4,10,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,E,F,0,No Deposit,96.0,,0,Transient,45.0,0,0
HB-067051,City Hotel,1,112,2025,April,18,28,2025-04-28,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,0
HB-047719,City Hotel,0,55,2024,March,9,1,2024-03-01,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,84.8,0,1
HB-072723,City Hotel,1,80,2025,August,32,4,2025-08-04,0,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.0,0,0
HB-020786,Resort Hotel,0,26,2024,February,6,9,2024-02-09,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,364.0,0,Transient-Party,35.0,0,1
HB-010134,Resort Hotel,1,92,2025,February,7,15,2025-02-15,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,39.9,0,1
HB-108147,City Hotel,0,0,2025,March,12,22,2025-03-22,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,94.0,,0,Transient,65.0,0,1
HB-095635,City Hotel,0,0,2024,August,34,21,2024-08-21,1,0,2,1.0,0,SC,PRT,Direct,Direct,0,0,0,A,C,1,No Deposit,,,0,Transient,152.0,0,0
HB-111910,City Hotel,0,201,2025,May,20,14,2025-05-14,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.1,0,5
HB-040810,City Hotel,1,112,2023,August,32,7,2023-08-07,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,1
HB-038214,Resort Hotel,0,47,2025,July,28,11,2025-07-11,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,I,2,No Deposit,240.0,,0,Transient,160.0,0,0
HB-030307,Resort Hotel,0,47,2024,November,46,12,2024-11-12,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,52.4,0,1
HB-002168,Resort Hotel,0,53,2023,October,40,3,2023-10-03,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,56.0,0,2
HB-040799,City Hotel,0,36,2023,August,32,7,2023-08-07,0,2,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-011214,Resort Hotel,1,21,2025,April,18,29,2025-04-29,1,1,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,125.0,0,2
HB-024166,Resort Hotel,0,468,2024,May,19,12,2024-05-12,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,E,0,No Deposit,249.0,,0,Transient-Party,67.0,0,0
HB-081703,City Hotel,1,109,2024,February,8,21,2024-02-21,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,44,Transient,75.0,0,0
HB-013561,Resort Hotel,1,220,2025,August,34,19,2025-08-19,4,6,2,2.0,0,BB,IRL,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,244.0,0,0
HB-062824,City Hotel,1,59,2025,January,4,23,2025-01-23,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,326.0,,0,Transient,80.0,0,0
HB-000972,Resort Hotel,0,12,2023,August,32,8,2023-08-08,2,5,2,2.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,G,G,0,No Deposit,,,0,Transient,252.0,1,1
HB-106503,City Hotel,0,175,2025,February,8,19,2025-02-19,2,5,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,119.0,0,1
HB-049811,City Hotel,1,70,2024,April,16,20,2024-04-20,0,1,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,186.3,0,0
HB-022925,Resort Hotel,0,14,2024,April,14,7,2024-04-07,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,96.0,,0,Transient,47.4,1,1
HB-039873,Resort Hotel,0,162,2025,August,34,24,2025-08-24,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,152.43,1,2
HB-006248,Resort Hotel,1,71,2024,May,22,30,2024-05-30,2,5,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,116.43,0,0
HB-033522,Resort Hotel,0,4,2025,February,8,18,2025-02-18,2,5,2,1.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,96.02,0,0
HB-020168,Resort Hotel,0,5,2024,January,3,16,2024-01-16,2,1,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,44.8,0,1
HB-001796,Resort Hotel,0,99,2023,September,37,15,2023-09-15,0,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,147.0,,0,Transient,55.79,0,0
HB-084022,City Hotel,0,25,2024,February,7,16,2024-02-16,0,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,66.22,0,1
HB-092195,City Hotel,0,79,2024,June,26,29,2024-06-29,0,3,2,1.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,173.25,0,1
HB-056279,City Hotel,1,54,2024,September,36,2,2024-09-02,1,2,2,0.0,0,BB,HUN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,123.3,0,0
HB-011023,Resort Hotel,1,249,2025,April,16,14,2025-04-14,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,59.79,0,0
HB-044071,City Hotel,1,92,2023,September,39,30,2023-09-30,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-019834,Resort Hotel,0,23,2024,January,1,2,2024-01-02,2,1,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,50.33,1,0
HB-087198,City Hotel,0,58,2024,April,16,15,2024-04-15,0,1,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,G,0,No Deposit,9.0,,0,Transient,186.3,0,2
HB-012705,Resort Hotel,1,0,2025,July,28,13,2025-07-13,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,105.0,0,2
HB-078690,City Hotel,0,0,2023,November,44,3,2023-11-03,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,1,No Deposit,,40.0,0,Transient,65.0,0,0
HB-055231,City Hotel,1,34,2024,August,32,8,2024-08-08,1,2,2,1.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,194.85,0,1
HB-094660,City Hotel,0,56,2024,August,32,6,2024-08-06,1,1,2,1.0,0,BB,JPN,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,207.9,0,1
HB-077159,City Hotel,0,0,2024,March,10,9,2024-03-09,0,1,2,0.0,0,BB,PRT,Complementary,Direct,1,3,14,G,F,0,No Deposit,,45.0,0,Transient,0.0,0,1
HB-009968,Resort Hotel,1,12,2025,January,5,30,2025-01-30,1,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,242.0,,0,Transient,83.6,0,1
HB-087167,City Hotel,0,59,2024,April,15,11,2024-04-11,1,3,2,1.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,B,0,No Deposit,85.0,,0,Transient,93.08,0,1
HB-104823,City Hotel,0,141,2025,January,4,21,2025-01-21,1,1,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,299.0,,0,Transient,104.6,0,1
HB-105113,City Hotel,0,193,2025,January,4,26,2025-01-26,1,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,86.0,,0,Transient,68.0,0,0
HB-113304,City Hotel,0,128,2025,June,23,2,2025-06-02,1,2,3,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,115.0,0,0
HB-030092,Resort Hotel,0,19,2024,November,45,4,2024-11-04,3,7,2,0.0,0,HB,GBR,Direct,Direct,0,0,0,E,E,3,No Deposit,250.0,,0,Transient,89.77,0,0
HB-078660,City Hotel,0,20,2023,October,41,11,2023-10-11,2,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-083787,City Hotel,0,2,2024,February,6,10,2024-02-10,0,2,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,174.0,0,Transient-Party,72.0,0,0
HB-054718,City Hotel,1,166,2024,July,30,24,2024-07-24,2,2,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,85.01,0,0
HB-066031,City Hotel,1,19,2025,April,15,13,2025-04-13,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,174.0,0,0
HB-088507,City Hotel,0,157,2024,May,18,5,2024-05-05,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Contract,127.0,0,0
HB-100627,City Hotel,0,116,2024,October,44,29,2024-10-29,0,1,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,104.4,0,0
HB-103039,City Hotel,0,0,2024,December,49,7,2024-12-07,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,108.88,0,2
HB-066973,City Hotel,1,22,2025,April,17,27,2025-04-27,0,1,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,86.0,,0,Transient,84.0,0,0
HB-062580,City Hotel,1,39,2025,January,3,15,2025-01-15,4,7,3,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,117.81,0,0
HB-013578,Resort Hotel,1,143,2025,August,34,20,2025-08-20,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,174.04,0,1
HB-001448,Resort Hotel,0,11,2023,August,35,30,2023-08-30,2,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,103.5,1,3
HB-102132,City Hotel,0,95,2024,November,47,18,2024-11-18,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.0,0,1
HB-001759,Resort Hotel,1,149,2023,September,37,13,2023-09-13,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,73.8,0,1
HB-005964,Resort Hotel,0,191,2024,May,20,18,2024-05-18,2,5,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,46.98,0,1
HB-040946,City Hotel,1,39,2023,August,32,10,2023-08-10,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-046503,City Hotel,1,145,2024,January,1,3,2024-01-03,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,85,Transient,65.0,0,0
HB-016553,Resort Hotel,1,247,2023,October,41,9,2023-10-09,1,2,2,0.0,0,FB,ESP,Groups,TA/TO,0,1,0,A,A,0,Non Refund,68.0,,0,Transient,81.0,0,0
HB-015325,Resort Hotel,1,279,2023,October,40,8,2023-10-08,2,5,2,0.0,0,HB,IRL,Groups,TA/TO,0,1,0,A,A,0,No Deposit,142.0,,0,Transient-Party,63.4,0,0
HB-020725,Resort Hotel,0,21,2024,February,5,4,2024-02-04,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient-Party,48.0,0,2
HB-060624,City Hotel,1,496,2024,November,46,17,2024-11-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-071039,City Hotel,1,137,2025,June,26,27,2025-06-27,0,4,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,99.0,0,3
HB-107284,City Hotel,0,47,2025,March,10,6,2025-03-06,1,4,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-038794,Resort Hotel,0,30,2025,July,30,27,2025-07-27,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,F,1,No Deposit,240.0,,0,Transient,245.0,0,2
HB-038903,Resort Hotel,0,7,2025,August,31,1,2025-08-01,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,I,0,No Deposit,,,0,Transient,212.8,0,0
HB-102368,City Hotel,0,18,2024,November,48,25,2024-11-25,0,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,88.0,0,2
HB-073672,City Hotel,1,30,2025,August,35,30,2025-08-30,0,3,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,D,D,4,No Deposit,9.0,,0,Transient,166.33,0,1
HB-078689,City Hotel,0,0,2023,October,41,12,2023-10-12,1,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-016796,Resort Hotel,0,178,2023,September,37,12,2023-09-12,0,1,1,0.0,0,BB,SWE,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,251.0,,0,Transient,54.9,0,0
HB-047069,City Hotel,0,48,2024,February,6,6,2024-02-06,0,1,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.3,0,0
HB-018681,Resort Hotel,0,26,2023,November,47,21,2023-11-21,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,50.0,0,1
HB-067424,City Hotel,1,152,2025,May,18,3,2025-05-03,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,286.0,,0,Transient,100.0,0,0
HB-107075,City Hotel,0,0,2025,March,10,7,2025-03-07,0,0,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,1,0,0,E,K,0,No Deposit,15.0,,0,Transient,0.0,0,0
HB-055519,City Hotel,1,133,2024,August,33,15,2024-08-15,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,86.36,0,0
HB-046821,City Hotel,1,151,2024,January,3,19,2024-01-19,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,19.0,,63,Transient-Party,80.0,0,0
HB-031213,Resort Hotel,0,46,2024,December,51,17,2024-12-17,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient-Party,66.0,0,0
HB-093253,City Hotel,0,0,2024,July,29,18,2024-07-18,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,E,E,0,No Deposit,,210.0,0,Transient,139.0,1,0
HB-013834,Resort Hotel,0,4,2025,July,28,11,2025-07-11,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,3,A,A,1,No Deposit,,528.0,0,Transient,142.0,1,0
HB-026142,Resort Hotel,0,163,2024,July,29,16,2024-07-16,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,104.55,0,0
HB-115809,City Hotel,0,9,2025,July,28,9,2025-07-09,2,0,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,3,No Deposit,14.0,,0,Transient,184.0,0,1
HB-083012,City Hotel,0,9,2024,January,2,8,2024-01-08,2,3,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,44.8,0,0
HB-028491,Resort Hotel,0,172,2024,September,40,30,2024-09-30,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,86.0,0,1
HB-073345,City Hotel,1,162,2025,August,34,19,2025-08-19,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,140.0,0,0
HB-031171,Resort Hotel,0,101,2024,December,50,15,2024-12-15,0,2,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,241.0,,0,Transient,25.64,0,3
HB-040696,City Hotel,0,12,2023,August,31,5,2023-08-05,0,3,2,0.0,0,BB,RUS,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,38.0,0,Transient-Party,65.0,0,0
HB-075914,City Hotel,1,274,2023,July,29,18,2023-07-18,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-060590,City Hotel,1,61,2024,November,46,16,2024-11-16,0,4,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,0
HB-116243,City Hotel,0,8,2025,July,29,15,2025-07-15,1,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.0,0,1
HB-053092,City Hotel,1,188,2024,June,24,15,2024-06-15,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,39,Transient,130.0,0,0
HB-102616,City Hotel,0,6,2024,November,48,27,2024-11-27,2,4,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,68.0,0,0
HB-088770,City Hotel,0,16,2024,October,42,19,2024-10-19,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,8,A,A,0,No Deposit,,219.0,0,Transient,98.0,1,2
HB-091013,City Hotel,0,56,2024,June,24,12,2024-06-12,2,1,3,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,177.3,0,3
HB-019263,Resort Hotel,1,147,2024,April,18,29,2024-04-29,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,E,E,0,No Deposit,240.0,,0,Transient,79.2,0,0
HB-073009,City Hotel,1,189,2025,August,33,12,2025-08-12,2,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.5,0,0
HB-047979,City Hotel,0,74,2024,March,11,11,2024-03-11,1,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,78.3,0,1
HB-038639,Resort Hotel,0,119,2025,July,29,18,2025-07-18,2,5,3,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,206.03,0,0
HB-035667,Resort Hotel,0,234,2025,April,17,22,2025-04-22,2,5,2,0.0,0,Undefined,SWE,Groups,TA/TO,0,0,0,D,D,0,No Deposit,527.0,,0,Transient-Party,116.0,0,0
HB-094468,City Hotel,0,1,2024,August,31,4,2024-08-04,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.0,0,0
HB-023358,Resort Hotel,0,31,2024,April,16,18,2024-04-18,1,4,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,75.0,0,1
HB-043389,City Hotel,0,74,2023,September,38,18,2023-09-18,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-077028,City Hotel,0,0,2023,August,34,25,2023-08-25,2,7,1,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,A,2,No Deposit,,46.0,0,Transient,0.0,0,0
HB-011168,Resort Hotel,1,203,2025,April,17,25,2025-04-25,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,90.0,0,0
HB-019483,Resort Hotel,0,0,2024,October,43,26,2024-10-26,0,1,1,0.0,0,BB,PRT,Direct,Direct,1,0,2,A,E,0,No Deposit,,,0,Transient,50.0,0,0
HB-104122,City Hotel,0,79,2025,January,1,2,2025-01-02,1,3,3,0.0,0,BB,HUN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,119.0,0,1
HB-115030,City Hotel,0,107,2025,June,26,27,2025-06-27,0,3,0,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,7.0,,0,Transient,100.8,0,0
HB-010978,Resort Hotel,1,167,2025,April,15,13,2025-04-13,2,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,94.5,0,3
HB-052240,City Hotel,1,30,2024,June,22,2,2024-06-02,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,235.0,,0,Transient,140.0,0,0
HB-072756,City Hotel,1,314,2025,August,32,5,2025-08-05,2,1,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.5,0,0
HB-103057,City Hotel,0,58,2024,December,50,9,2024-12-09,0,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,102.6,1,1
HB-049251,City Hotel,0,96,2024,April,15,8,2024-04-08,2,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,88.83,0,0
HB-034114,Resort Hotel,0,31,2025,March,10,6,2025-03-06,2,5,3,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,464.0,,0,Transient,59.0,0,1
HB-017000,Resort Hotel,0,239,2023,September,38,19,2023-09-19,1,1,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,E,0,No Deposit,248.0,,0,Transient-Party,80.0,0,0
HB-081406,City Hotel,1,36,2023,December,51,20,2023-12-20,2,0,2,0.0,0,SC,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Transient,87.3,0,1
HB-044628,City Hotel,0,80,2023,October,41,9,2023-10-09,0,2,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,12.0,,50,Transient-Party,108.0,0,0
HB-102810,City Hotel,0,24,2024,December,49,4,2024-12-04,2,1,1,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,2
HB-027302,Resort Hotel,0,195,2024,August,34,23,2024-08-23,0,3,3,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,169.5,0,2
HB-087248,City Hotel,0,122,2024,April,16,15,2024-04-15,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,151.0,,56,Transient-Party,85.0,0,0
HB-036056,Resort Hotel,0,0,2025,May,19,6,2025-05-06,1,1,2,1.0,0,BB,NLD,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,128.0,0,0
HB-024390,Resort Hotel,0,0,2024,May,20,19,2024-05-19,0,0,2,0.0,0,BB,CN,Online TA,TA/TO,1,0,0,A,I,0,No Deposit,240.0,,0,Transient,0.0,0,0
HB-013167,Resort Hotel,1,101,2025,August,31,3,2025-08-03,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,213.75,0,0
HB-110239,City Hotel,0,97,2025,April,17,22,2025-04-22,1,1,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,150.0,1,3
HB-032072,Resort Hotel,0,0,2025,January,3,13,2025-01-13,1,2,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,34.0,0,0
HB-050567,City Hotel,1,147,2024,May,18,4,2024-05-04,0,4,2,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,101.7,0,0
HB-014978,Resort Hotel,1,166,2023,July,28,15,2023-07-15,0,2,2,0.0,0,FB,PRT,Groups,TA/TO,0,24,0,A,A,0,Non Refund,,,0,Transient,121.5,0,0
HB-093316,City Hotel,0,136,2024,July,28,13,2024-07-13,2,5,3,0.0,0,HB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,178.5,0,0
HB-018668,Resort Hotel,0,2,2023,November,47,23,2023-11-23,1,2,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,171.0,,0,Transient,29.0,0,0
HB-071429,City Hotel,1,182,2025,July,27,5,2025-07-05,0,4,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,1
HB-088314,City Hotel,0,10,2024,May,18,3,2024-05-03,0,1,2,0.0,0,SC,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,58.0,0,1
HB-018033,Resort Hotel,0,1,2023,October,44,30,2023-10-30,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,43.2,0,1
HB-105005,City Hotel,0,31,2025,January,4,22,2025-01-22,2,3,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,84.5,0,1
HB-105632,City Hotel,0,34,2025,February,6,9,2025-02-09,1,3,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,70.0,0,0
HB-088842,City Hotel,0,0,2025,March,11,16,2025-03-16,0,1,2,0.0,0,SC,LUX,Online TA,TA/TO,1,0,12,A,A,0,No Deposit,9.0,,0,Transient,98.0,0,0
HB-079713,City Hotel,1,105,2024,February,6,8,2024-02-08,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Transient,90.0,0,0
HB-113109,City Hotel,0,101,2025,May,22,30,2025-05-30,0,4,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,144.0,0,2
HB-020184,Resort Hotel,0,1,2024,January,3,17,2024-01-17,2,0,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,54.0,1,2
HB-013058,Resort Hotel,1,247,2025,July,31,29,2025-07-29,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,153.75,0,0
HB-014628,Resort Hotel,1,21,2024,July,30,27,2024-07-27,1,4,2,0.0,0,HB,,Direct,Direct,0,1,0,A,A,0,No Deposit,,,0,Transient,209.0,0,0
HB-037641,Resort Hotel,0,239,2025,June,25,19,2025-06-19,1,4,1,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient,99.0,0,1
HB-073375,City Hotel,1,176,2025,August,34,19,2025-08-19,2,3,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,115.02,0,1
HB-083016,City Hotel,0,0,2025,March,13,24,2025-03-24,0,1,1,0.0,0,BB,PRT,Direct,Direct,1,0,1,A,E,0,No Deposit,,163.0,0,Group,50.0,0,0
HB-009880,Resort Hotel,1,40,2025,January,3,16,2025-01-16,1,2,1,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,55.0,0,0
HB-050454,City Hotel,1,34,2024,May,18,1,2024-05-01,2,1,2,0.0,0,BB,SAU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.9,0,0
HB-103919,City Hotel,0,259,2024,December,52,28,2024-12-28,1,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,131.43,0,2
HB-087919,City Hotel,0,2,2024,April,17,27,2024-04-27,0,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,131.0,0,1
HB-053541,City Hotel,1,351,2024,June,25,23,2024-06-23,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-078578,City Hotel,1,1,2025,July,29,18,2025-07-18,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,16,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,1
HB-110701,City Hotel,0,237,2025,April,18,28,2025-04-28,1,2,2,0.0,0,SC,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,72.42,0,2
HB-038888,Resort Hotel,0,124,2025,July,30,23,2025-07-23,4,6,2,0.0,0,Undefined,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,158.85,0,2
HB-066876,City Hotel,1,88,2025,April,17,26,2025-04-26,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,170.0,,0,Transient,140.0,0,0
HB-000314,Resort Hotel,0,90,2023,July,28,12,2023-07-12,2,5,2,0.0,0,FB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,5.0,,0,Transient-Party,117.22,0,1
HB-085954,City Hotel,0,113,2024,March,12,22,2024-03-22,0,3,3,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,E,0,No Deposit,28.0,,0,Transient,82.0,0,1
HB-004139,Resort Hotel,0,99,2024,February,7,16,2024-02-16,2,7,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,115.0,,0,Transient,33.3,0,0
HB-073791,City Hotel,1,279,2023,July,29,23,2023-07-23,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-115806,City Hotel,0,11,2025,July,28,9,2025-07-09,2,0,2,0.0,0,BB,SVK,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,1
HB-032321,Resort Hotel,0,1,2025,January,4,21,2025-01-21,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,77.0,1,0
HB-088062,City Hotel,0,64,2024,April,17,25,2024-04-25,1,4,2,1.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,119.17,0,2
HB-044595,City Hotel,0,210,2023,October,40,8,2023-10-08,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,12.0,,0,Transient-Party,72.75,0,0
HB-026354,Resort Hotel,0,37,2024,July,30,23,2024-07-23,2,5,3,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,,,0,Transient,210.0,1,0
HB-031681,Resort Hotel,0,8,2025,January,1,4,2025-01-04,0,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,0.0,0,2
HB-095260,City Hotel,0,199,2024,August,33,14,2024-08-14,2,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,115.8,0,1
HB-060878,City Hotel,1,308,2024,November,48,25,2024-11-25,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,52.0,0,0
HB-010152,Resort Hotel,1,36,2025,February,8,17,2025-02-17,0,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,C,1,No Deposit,240.0,,0,Transient,48.0,0,1
HB-092336,City Hotel,0,147,2024,June,26,28,2024-06-28,2,5,2,1.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,106.25,0,2
HB-080561,City Hotel,0,35,2023,November,46,18,2023-11-18,0,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,113.4,0,1
HB-099318,City Hotel,0,158,2024,October,41,9,2024-10-09,2,1,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,151.2,0,2
HB-060746,City Hotel,1,247,2024,November,47,19,2024-11-19,2,3,2,0.0,0,SC,TUR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,63.75,0,0
HB-054896,City Hotel,1,167,2024,July,31,29,2024-07-29,0,2,3,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,137.7,0,0
HB-088556,City Hotel,0,7,2024,May,18,5,2024-05-05,0,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,144.0,0,0
HB-016847,Resort Hotel,0,254,2023,September,37,12,2023-09-12,2,2,2,0.0,0,BB,CN,Groups,TA/TO,0,0,0,A,A,1,No Deposit,15.0,,0,Transient-Party,36.0,0,0
HB-067627,City Hotel,1,81,2025,May,19,5,2025-05-05,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,162.0,0,0
HB-062542,City Hotel,1,18,2025,January,3,14,2025-01-14,1,1,3,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.5,0,1
HB-064344,City Hotel,1,29,2025,March,10,6,2025-03-06,1,3,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,15.0,,0,Transient,126.48,0,0
HB-067761,City Hotel,1,229,2025,May,19,6,2025-05-06,2,2,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,134.13,0,1
HB-105218,City Hotel,0,23,2025,February,5,2,2025-02-02,0,0,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,0.0,0,1
HB-097771,City Hotel,0,26,2024,September,38,18,2024-09-18,2,1,2,0.0,0,BB,RUS,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,95.0,0,0
HB-065068,City Hotel,1,100,2025,March,12,23,2025-03-23,1,3,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,100.3,0,0
HB-103291,City Hotel,0,38,2024,December,51,16,2024-12-16,0,2,2,0.0,0,BB,PRT,Complementary,TA/TO,0,0,0,A,A,0,No Deposit,132.0,,0,Transient,0.0,0,0
HB-084871,City Hotel,0,0,2024,March,10,4,2024-03-04,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.0,1,1
HB-068799,City Hotel,1,75,2025,May,21,20,2025-05-20,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,90.0,0,0
HB-018690,Resort Hotel,1,111,2024,March,10,10,2024-03-10,2,3,1,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,240.0,,0,Transient,39.0,0,1
HB-033614,Resort Hotel,0,3,2025,February,9,26,2025-02-26,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,314.0,,0,Transient,43.2,0,3
HB-088504,City Hotel,0,91,2024,May,18,4,2024-05-04,0,4,2,1.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,127.5,0,1
HB-094370,City Hotel,0,195,2024,July,30,27,2024-07-27,2,6,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,66.53,0,1
HB-072838,City Hotel,1,21,2025,August,32,7,2025-08-07,2,5,2,0.0,0,SC,PHL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,1
HB-038529,Resort Hotel,0,163,2025,July,29,18,2025-07-18,0,3,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,147.84,0,0
HB-061304,City Hotel,1,27,2024,December,49,7,2024-12-07,0,4,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,E,3,No Deposit,9.0,,0,Transient,171.44,0,1
HB-014080,Resort Hotel,0,6,2024,November,48,27,2024-11-27,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,1,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,2
HB-025095,Resort Hotel,0,159,2024,June,24,13,2024-06-13,1,1,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,84.0,1,1
HB-040968,City Hotel,0,39,2023,August,32,10,2023-08-10,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-047306,City Hotel,1,15,2024,February,7,16,2024-02-16,0,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,91.0,0,1
HB-027879,Resort Hotel,0,32,2024,September,37,12,2024-09-12,1,1,2,0.0,0,BB,TUR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,131.0,0,0
HB-028323,Resort Hotel,0,60,2024,September,39,25,2024-09-25,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,101.75,0,2
HB-095105,City Hotel,0,109,2024,August,33,12,2024-08-12,1,2,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,1
HB-070409,City Hotel,1,140,2025,June,25,16,2025-06-16,1,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,27.0,,0,Transient,93.6,0,0
HB-096822,City Hotel,0,1,2024,September,36,2,2024-09-02,2,5,1,0.0,0,BB,USA,Aviation,Corporate,0,0,0,A,A,0,No Deposit,,153.0,0,Transient,110.0,0,0
HB-118537,City Hotel,0,106,2025,August,33,15,2025-08-15,2,5,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,16.0,,0,Transient,121.0,0,0
HB-013593,Resort Hotel,1,295,2025,August,34,21,2025-08-21,1,3,3,1.0,0,HB,ESP,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,297.0,0,0
HB-007129,Resort Hotel,1,51,2024,July,30,23,2024-07-23,2,4,2,0.0,1,HB,ESP,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,226.0,0,1
HB-104145,City Hotel,0,27,2025,January,1,1,2025-01-01,2,3,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.24,0,3
HB-043792,City Hotel,1,26,2023,September,38,24,2023-09-24,1,3,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,231.0,0,1
HB-022878,Resort Hotel,0,71,2024,April,14,2,2024-04-02,2,5,2,0.0,0,FB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,26.0,,0,Transient,89.25,0,0
HB-099262,City Hotel,0,25,2024,October,41,8,2024-10-08,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-089508,City Hotel,0,30,2024,May,21,21,2024-05-21,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.9,0,1
HB-104103,City Hotel,0,28,2025,January,1,3,2025-01-03,0,3,1,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.0,0,1
HB-028993,Resort Hotel,0,339,2024,October,41,11,2024-10-11,2,5,2,0.0,0,BB,GBR,Groups,Direct,0,0,0,E,E,0,Refundable,273.0,,150,Transient-Party,78.81,0,0
HB-068538,City Hotel,1,175,2025,May,21,19,2025-05-19,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,44.0,,0,Transient,90.0,0,0
HB-058673,City Hotel,1,110,2024,October,42,14,2024-10-14,0,2,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,190.8,0,0
HB-049260,City Hotel,0,96,2024,April,15,8,2024-04-08,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,B,1,No Deposit,9.0,,0,Transient-Party,87.55,0,1
HB-112018,City Hotel,0,65,2025,May,20,15,2025-05-15,1,3,2,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,162.0,0,0
HB-063989,City Hotel,1,31,2025,February,9,25,2025-02-25,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,100.3,0,1
HB-079668,City Hotel,1,3,2024,November,46,12,2024-11-12,0,1,2,2.0,0,BB,PRT,Direct,Direct,1,0,3,F,F,0,No Deposit,,,0,Transient,75.0,0,1
HB-118388,City Hotel,0,108,2025,August,33,17,2025-08-17,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.0,0,3
HB-008737,Resort Hotel,0,364,2024,October,41,12,2024-10-12,0,4,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,2,No Deposit,,223.0,0,Transient-Party,66.0,0,0
HB-030454,Resort Hotel,0,34,2024,November,47,21,2024-11-21,1,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,69.0,1,1
HB-106405,City Hotel,0,1,2025,February,9,24,2025-02-24,0,1,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,0
HB-086952,City Hotel,0,89,2024,April,15,9,2024-04-09,2,1,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,79.5,0,1
HB-042695,City Hotel,1,85,2023,September,36,9,2023-09-09,0,2,2,0.0,0,BB,FRA,Groups,Corporate,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,110.0,0,0
HB-013399,Resort Hotel,1,216,2025,August,33,13,2025-08-13,4,6,2,1.0,0,HB,GBR,Direct,Direct,0,0,0,A,A,1,No Deposit,250.0,,0,Transient,180.5,0,0
HB-025152,Resort Hotel,0,3,2024,June,24,12,2024-06-12,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,241.0,,0,Transient,124.82,1,0
HB-010950,Resort Hotel,1,66,2025,April,15,12,2025-04-12,2,4,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,75.0,0,0
HB-014952,Resort Hotel,1,256,2023,August,31,1,2023-08-01,4,6,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,240.0,,0,Transient-Party,120.6,0,1
HB-094519,City Hotel,0,159,2024,August,32,5,2024-08-05,0,1,2,0.0,0,SC,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,94.5,0,0
HB-074852,City Hotel,1,335,2023,September,37,17,2023-09-17,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,5.0,,0,Transient,55.0,0,0
HB-019709,Resort Hotel,0,42,2023,December,52,30,2023-12-30,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,F,0,No Deposit,,,0,Transient,192.33,0,0
HB-044575,City Hotel,1,210,2023,October,40,8,2023-10-08,1,3,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,86.0,0,0
HB-081000,City Hotel,0,0,2023,December,48,2,2023-12-02,0,1,1,0.0,0,BB,ESP,Direct,Direct,1,0,0,A,A,1,No Deposit,,,0,Transient,69.0,0,0
HB-103970,City Hotel,0,65,2025,January,1,2,2025-01-02,1,0,2,2.0,0,BB,JPN,Online TA,TA/TO,0,0,0,F,G,0,No Deposit,9.0,,0,Transient,156.6,0,0
HB-112136,City Hotel,0,9,2025,May,21,19,2025-05-19,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,2
HB-049840,City Hotel,0,270,2024,April,16,20,2024-04-20,0,4,3,0.0,0,BB,ISL,Offline TA/TO,TA/TO,0,0,0,A,B,1,No Deposit,21.0,,187,Transient-Party,110.0,0,0
HB-026949,Resort Hotel,0,34,2024,August,32,10,2024-08-10,1,4,2,0.0,0,HB,ESP,Direct,Direct,0,0,0,F,G,1,No Deposit,250.0,,0,Transient,306.0,1,0
HB-039117,Resort Hotel,0,36,2025,August,32,4,2025-08-04,2,2,2,0.0,0,BB,AUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,239.75,0,2
HB-001320,Resort Hotel,0,0,2023,August,34,24,2023-08-24,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,F,0,No Deposit,240.0,,0,Transient,153.0,0,0
HB-068088,City Hotel,1,96,2025,May,20,12,2025-05-12,2,2,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,175.5,0,0
HB-107375,City Hotel,0,88,2025,March,10,9,2025-03-09,0,3,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,79.2,0,1
HB-038889,Resort Hotel,0,124,2025,July,30,23,2025-07-23,4,6,2,0.0,0,Undefined,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,158.85,0,2
HB-098810,City Hotel,1,0,2024,December,50,12,2024-12-12,1,0,2,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,341.0,,0,Transient,77.0,0,2
HB-113799,City Hotel,0,206,2025,June,24,9,2025-06-09,1,2,1,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,144.0,0,1
HB-107258,City Hotel,0,36,2025,March,10,6,2025-03-06,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,100.3,0,3
HB-080828,City Hotel,0,1,2023,November,47,25,2023-11-25,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,115.0,0,2
HB-119309,City Hotel,0,138,2025,August,35,29,2025-08-29,0,5,1,0.0,0,BB,JPN,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,117.9,0,0
HB-092363,City Hotel,0,25,2024,July,27,1,2024-07-01,2,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,72.25,0,0
HB-075282,City Hotel,1,299,2023,August,32,12,2023-08-12,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-067495,City Hotel,1,143,2025,May,18,4,2025-05-04,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,56.0,,0,Transient,120.0,0,0
HB-051921,City Hotel,0,316,2024,May,21,26,2024-05-26,0,3,2,0.0,0,BB,AUT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,110.0,0,0
HB-042655,City Hotel,0,69,2023,September,36,9,2023-09-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-095458,City Hotel,0,64,2024,August,33,14,2024-08-14,2,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.9,0,1
HB-033743,Resort Hotel,0,4,2025,February,9,28,2025-02-28,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,45.5,0,0
HB-064258,City Hotel,1,10,2025,March,10,3,2025-03-03,0,2,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,188.0,0,0
HB-104384,City Hotel,0,262,2025,January,2,9,2025-01-09,1,2,2,0.0,0,BB,ALB,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient-Party,114.3,0,3
HB-005678,Resort Hotel,0,203,2024,May,19,10,2024-05-10,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,248.0,,0,Transient-Party,46.0,0,0
HB-029168,Resort Hotel,0,11,2024,October,43,22,2024-10-22,2,2,2,0.0,0,BB,SWE,Groups,Corporate,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,65.0,1,0
HB-060717,City Hotel,1,3,2024,November,47,19,2024-11-19,0,1,2,0.0,0,SC,AGO,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,95.0,0,1
HB-033924,Resort Hotel,0,39,2025,February,9,28,2025-02-28,2,5,2,2.0,0,BB,NLD,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,98.29,0,0
HB-077601,City Hotel,0,9,2023,September,38,21,2023-09-21,1,1,2,1.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Group,90.5,0,1
HB-038848,Resort Hotel,0,1,2025,July,31,28,2025-07-28,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,172.67,1,1
HB-022844,Resort Hotel,0,3,2024,April,15,8,2024-04-08,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,C,0,No Deposit,146.0,,0,Transient-Party,54.0,0,0
HB-029035,Resort Hotel,0,22,2024,October,42,16,2024-10-16,2,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,45.89,0,1
HB-065040,City Hotel,1,622,2025,March,12,23,2025-03-23,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-022810,Resort Hotel,0,21,2024,April,14,6,2024-04-06,0,1,2,0.0,0,BB,AUT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,251.0,,0,Transient,59.0,0,0
HB-065011,City Hotel,1,6,2025,March,12,22,2025-03-22,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,86.0,,0,Transient,86.4,0,0
HB-107381,City Hotel,0,70,2025,March,10,8,2025-03-08,0,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,70.69,0,1
HB-004655,Resort Hotel,1,67,2024,March,13,25,2024-03-25,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,105.0,0,1
HB-088153,City Hotel,0,127,2024,April,17,28,2024-04-28,1,3,2,0.0,0,BB,USA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient,90.0,0,0
HB-007852,Resort Hotel,1,23,2024,August,35,29,2024-08-29,3,5,2,0.0,0,BB,MAR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,174.38,0,1
HB-101374,City Hotel,0,16,2024,November,45,6,2024-11-06,2,3,1,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,155.6,0,2
HB-090707,City Hotel,0,10,2024,June,23,9,2024-06-09,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,121.0,0,1
HB-024275,Resort Hotel,0,59,2024,May,19,8,2024-05-08,2,5,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,G,G,0,No Deposit,250.0,,0,Transient-Party,120.0,0,0
HB-065823,City Hotel,1,248,2025,April,15,9,2025-04-09,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,58.0,,0,Transient-Party,80.0,0,1
HB-041143,City Hotel,0,0,2023,August,32,13,2023-08-13,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,9.0,9.0,0,Transient,85.0,0,0
HB-033750,Resort Hotel,0,0,2025,February,9,28,2025-02-28,0,2,1,0.0,0,BB,DEU,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,38.0,0,0
HB-080870,City Hotel,0,73,2023,November,47,24,2023-11-24,0,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,27,Transient-Party,85.67,0,0
HB-036973,Resort Hotel,0,19,2025,May,22,27,2025-05-27,2,5,2,0.0,1,HB,IRL,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,241.0,,0,Transient,161.6,0,2
HB-007780,Resort Hotel,1,140,2024,August,35,26,2024-08-26,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,204.5,0,0
HB-022590,Resort Hotel,0,74,2024,March,12,22,2024-03-22,2,6,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,62.38,0,1
HB-034541,Resort Hotel,0,3,2025,March,13,27,2025-03-27,1,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,68.0,0,0
HB-101724,City Hotel,0,8,2024,November,46,15,2024-11-15,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,90.0,0,0
HB-038236,Resort Hotel,0,182,2025,July,28,12,2025-07-12,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,2,No Deposit,,,0,Transient-Party,0.0,0,1
HB-072578,City Hotel,1,81,2025,July,31,31,2025-07-31,1,4,3,0.0,0,BB,MAR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,224.0,0,2
HB-083897,City Hotel,0,2,2024,February,7,13,2024-02-13,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,95.0,0,0
HB-012542,Resort Hotel,1,280,2025,July,27,3,2025-07-03,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,112.8,0,0
HB-014559,Resort Hotel,0,2,2025,May,19,8,2025-05-08,1,0,2,2.0,0,BB,PRT,Online TA,Direct,0,0,1,G,G,0,No Deposit,240.0,,0,Transient,152.0,1,3
HB-094205,City Hotel,0,301,2024,July,31,30,2024-07-30,1,1,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,90.0,0,0
HB-050875,City Hotel,1,71,2024,May,19,10,2024-05-10,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,58.0,,0,Transient-Party,90.0,0,0
HB-012746,Resort Hotel,1,253,2025,July,29,15,2025-07-15,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,5,No Deposit,240.0,,0,Transient,188.0,0,0
HB-018975,Resort Hotel,0,0,2023,December,48,2,2023-12-02,0,3,1,0.0,0,BB,FIN,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,38.0,0,0
HB-105012,City Hotel,0,78,2025,January,4,25,2025-01-25,0,3,1,0.0,0,BB,LTU,Groups,TA/TO,0,0,0,A,A,1,No Deposit,,365.0,0,Transient-Party,85.0,0,0
HB-033214,Resort Hotel,0,22,2025,February,7,13,2025-02-13,1,3,1,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,C,C,1,No Deposit,314.0,,0,Transient,50.4,0,0
HB-047165,City Hotel,0,57,2024,February,6,11,2024-02-11,0,3,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.3,0,0
HB-020044,Resort Hotel,0,2,2024,January,2,14,2024-01-14,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,39.0,0,1
HB-106423,City Hotel,0,20,2025,February,8,20,2025-02-20,1,4,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,168.0,,0,Transient,68.0,0,2
HB-014729,Resort Hotel,1,259,2023,September,37,17,2023-09-17,0,3,2,0.0,0,BB,GBR,Groups,Corporate,0,1,0,A,A,0,Non Refund,,223.0,0,Transient,40.05,0,0
HB-029603,Resort Hotel,0,1,2024,October,44,31,2024-10-31,1,0,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,108.0,0,0
HB-046585,City Hotel,0,4,2024,January,2,8,2024-01-08,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,87.0,0,1
HB-097255,City Hotel,0,40,2024,September,37,11,2024-09-11,2,1,2,1.0,1,BB,IND,Direct,Direct,0,0,0,E,E,2,No Deposit,14.0,,0,Transient,158.95,0,0
HB-024617,Resort Hotel,0,45,2024,May,21,21,2024-05-21,2,4,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,75.0,0,1
HB-046085,City Hotel,1,106,2023,December,49,9,2023-12-09,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,57,Transient,70.0,0,0
HB-035678,Resort Hotel,0,276,2025,April,17,22,2025-04-22,2,5,2,0.0,0,Undefined,SWE,Groups,TA/TO,0,0,0,A,A,0,No Deposit,527.0,,0,Transient-Party,104.0,0,1
HB-114541,City Hotel,0,0,2025,June,26,23,2025-06-23,0,1,1,0.0,0,BB,FRA,Aviation,Corporate,0,0,0,A,A,0,No Deposit,,153.0,0,Transient,95.0,0,0
HB-116557,City Hotel,0,118,2025,July,29,15,2025-07-15,2,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-097709,City Hotel,0,95,2024,September,37,13,2024-09-13,2,5,2,0.0,0,HB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,183.6,0,1
HB-016390,Resort Hotel,0,7,2024,November,47,21,2024-11-21,1,3,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,5,A,A,0,No Deposit,154.0,,0,Transient,27.0,0,0
HB-062086,City Hotel,1,46,2025,January,1,1,2025-01-01,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,65.0,0,0
HB-118988,City Hotel,0,1,2025,August,35,27,2025-08-27,1,0,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.1,0,1
HB-029109,Resort Hotel,0,30,2024,October,42,16,2024-10-16,2,2,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,240.0,,0,Transient,113.75,1,2
HB-020537,Resort Hotel,0,65,2024,January,4,28,2024-01-28,2,3,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,78.0,0,1
HB-090001,City Hotel,0,2,2024,May,22,30,2024-05-30,1,0,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,131.0,0,0
HB-094274,City Hotel,0,1,2024,August,31,2,2024-08-02,0,1,1,0.0,0,BB,AGO,Corporate,Direct,0,0,0,A,A,0,No Deposit,,71.0,0,Transient,159.0,0,0
HB-050236,City Hotel,1,76,2024,April,17,27,2024-04-27,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,106.5,0,1
HB-015268,Resort Hotel,0,2,2025,August,31,3,2025-08-03,0,2,2,0.0,0,BB,PRT,Corporate,Corporate,1,1,7,D,D,0,No Deposit,,281.0,0,Transient,0.0,1,2
HB-058189,City Hotel,1,96,2024,October,41,7,2024-10-07,1,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.8,0,1
HB-048145,City Hotel,0,75,2024,March,11,17,2024-03-17,1,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,88.83,0,0
HB-057026,City Hotel,1,205,2024,September,38,16,2024-09-16,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,120.0,0,0
HB-064008,City Hotel,1,38,2025,February,9,26,2025-02-26,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,28.0,,0,Transient,75.0,0,0
HB-060281,City Hotel,1,277,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-101591,City Hotel,0,1,2024,November,45,9,2024-11-09,2,4,1,0.0,0,BB,AGO,Complementary,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,0.0,0,1
HB-074153,City Hotel,1,342,2023,September,38,24,2023-09-24,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-015790,Resort Hotel,0,32,2023,July,30,24,2023-07-24,2,7,2,0.0,0,BB,MAR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,128.2,0,1
HB-116096,City Hotel,0,414,2025,July,28,13,2025-07-13,0,2,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,114.4,0,1
HB-065933,City Hotel,1,77,2025,April,15,10,2025-04-10,1,3,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,101.25,0,1
HB-107368,City Hotel,0,46,2025,March,11,10,2025-03-10,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,71.1,0,0
HB-010739,Resort Hotel,1,15,2025,March,13,30,2025-03-30,2,6,1,0.0,0,Undefined,PRT,Groups,Corporate,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,90.0,0,0
HB-108238,City Hotel,0,35,2025,March,12,19,2025-03-19,2,4,2,0.0,0,HB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,91.82,0,1
HB-059586,City Hotel,1,183,2024,October,44,29,2024-10-29,2,1,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.1,0,2
HB-001922,Resort Hotel,0,96,2023,September,38,21,2023-09-21,2,5,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,D,G,0,No Deposit,8.0,,0,Transient,79.5,1,1
HB-116977,City Hotel,0,8,2025,July,30,27,2025-07-27,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-047900,City Hotel,0,80,2024,March,10,8,2024-03-08,0,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,75.95,0,0
HB-028841,Resort Hotel,0,18,2024,October,41,11,2024-10-11,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,60.0,0,3
HB-069977,City Hotel,1,169,2025,June,23,8,2025-06-08,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,170.0,0,0
HB-087019,City Hotel,0,87,2024,April,15,9,2024-04-09,2,2,2,0.0,0,SC,ARG,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,80.75,0,1
HB-117852,City Hotel,0,283,2025,August,32,9,2025-08-09,0,2,2,2.0,0,BB,BEL,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,179.1,0,0
HB-075220,City Hotel,1,294,2023,August,32,7,2023-08-07,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-036344,Resort Hotel,0,241,2025,May,20,12,2025-05-12,2,4,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,241.0,,0,Transient,41.58,0,1
HB-071780,City Hotel,1,169,2025,July,28,12,2025-07-12,0,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,116.1,0,0
HB-093516,City Hotel,0,30,2024,July,29,19,2024-07-19,0,4,3,1.0,0,BB,LVA,Direct,Direct,0,0,0,E,F,0,No Deposit,14.0,,0,Transient,180.45,0,2
HB-111172,City Hotel,0,10,2025,April,17,26,2025-04-26,2,9,1,0.0,0,BB,AGO,Direct,Direct,0,0,0,D,D,5,No Deposit,,,0,Transient,19.09,0,3
HB-051743,City Hotel,1,158,2024,May,21,24,2024-05-24,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,31,Transient,130.0,0,0
HB-106337,City Hotel,0,27,2025,February,8,21,2025-02-21,0,3,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-063273,City Hotel,1,26,2025,February,6,4,2025-02-04,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,83.3,0,0
HB-103094,City Hotel,0,89,2024,December,50,10,2024-12-10,1,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,104.0,0,2
HB-001110,Resort Hotel,0,81,2023,August,33,14,2023-08-14,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,166.0,1,0
HB-042659,City Hotel,0,16,2023,September,36,9,2023-09-09,0,2,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,105.0,0,2
HB-056036,City Hotel,1,231,2024,August,35,27,2024-08-27,1,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.5,0,0
HB-053493,City Hotel,1,44,2024,June,25,22,2024-06-22,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,0
HB-051232,City Hotel,1,451,2024,May,20,16,2024-05-16,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-094322,City Hotel,0,0,2024,August,31,2,2024-08-02,0,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,152.0,,0,Transient,73.81,0,0
HB-001190,Resort Hotel,0,79,2023,August,33,17,2023-08-17,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient,133.0,0,0
HB-053218,City Hotel,1,61,2024,June,25,17,2024-06-17,0,2,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,140.4,0,0
HB-107440,City Hotel,0,57,2025,March,11,10,2025-03-10,1,2,1,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,154.0,,0,Transient-Party,70.0,0,1
HB-061999,City Hotel,1,35,2024,December,52,29,2024-12-29,2,6,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,3,No Deposit,9.0,,0,Transient,114.98,0,2
HB-087677,City Hotel,0,0,2024,April,17,22,2024-04-22,0,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.0,0,0
HB-064208,City Hotel,1,28,2025,March,9,2,2025-03-02,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,95.0,0,0
HB-004972,Resort Hotel,1,212,2024,April,15,11,2024-04-11,2,5,2,0.0,0,HB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,273.0,,0,Transient,67.05,0,0
HB-028157,Resort Hotel,0,51,2024,September,38,17,2024-09-17,2,3,2,0.0,0,BB,LUX,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,143.6,0,0
HB-034989,Resort Hotel,0,152,2025,April,14,5,2025-04-05,1,4,1,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,D,D,4,No Deposit,,223.0,0,Transient-Party,67.0,1,0
HB-035686,Resort Hotel,0,23,2025,April,17,22,2025-04-22,2,5,2,0.0,0,Undefined,SWE,Groups,TA/TO,0,0,0,D,D,0,No Deposit,527.0,,0,Transient-Party,116.0,0,1
HB-051208,City Hotel,1,451,2024,May,20,16,2024-05-16,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-064513,City Hotel,1,12,2025,March,11,11,2025-03-11,1,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,123.0,0,0
HB-095806,City Hotel,0,41,2024,August,34,20,2024-08-20,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.4,0,1
HB-000135,Resort Hotel,0,9,2023,July,27,5,2023-07-05,1,0,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,184.0,,0,Transient,89.0,0,0
HB-049888,City Hotel,1,265,2024,April,16,20,2024-04-20,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,30.0,,0,Transient,101.0,0,0
HB-074036,City Hotel,1,307,2023,August,33,20,2023-08-20,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-035466,Resort Hotel,0,0,2025,April,16,20,2025-04-20,0,3,2,0.0,0,BB,FIN,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,80.0,0,0
HB-083518,City Hotel,0,31,2024,February,5,4,2024-02-04,0,2,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,174.0,0,Transient-Party,81.5,0,0
HB-047405,City Hotel,1,34,2024,February,8,19,2024-02-19,4,9,2,0.0,0,BB,AGO,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,84.69,0,0
HB-012479,Resort Hotel,1,146,2025,July,27,1,2025-07-01,2,3,2,1.0,0,HB,PRT,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,243.0,0,0
HB-057694,City Hotel,1,4,2024,September,40,30,2024-09-30,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,4,No Deposit,,321.0,0,Transient-Party,110.0,0,0
HB-060056,City Hotel,1,11,2024,November,45,5,2024-11-05,0,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,140.0,0,1
HB-012895,Resort Hotel,1,151,2025,July,30,22,2025-07-22,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient,151.0,0,0
HB-070219,City Hotel,1,139,2025,June,24,12,2025-06-12,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,110.0,0,0
HB-077248,City Hotel,1,6,2023,September,38,20,2023-09-20,2,0,2,0.0,0,BB,PRT,Corporate,Corporate,0,1,0,A,A,0,Non Refund,78.0,,0,Transient,100.0,0,0
HB-040154,City Hotel,0,96,2023,July,28,11,2023-07-11,2,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-009837,Resort Hotel,1,154,2025,January,2,9,2025-01-09,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,37.8,0,0
HB-078244,City Hotel,1,8,2023,October,41,10,2023-10-10,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-061828,City Hotel,1,346,2024,December,52,26,2024-12-26,3,8,2,2.0,0,BB,DEU,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,146.59,0,2
HB-006748,Resort Hotel,0,237,2024,June,26,28,2024-06-28,2,8,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,60.29,0,3
HB-002522,Resort Hotel,0,12,2023,October,42,20,2023-10-20,0,2,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,F,0,No Deposit,240.0,,0,Transient,47.0,0,0
HB-091284,City Hotel,0,87,2024,June,24,12,2024-06-12,2,5,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,134.42,0,1
HB-068152,City Hotel,1,197,2025,May,20,13,2025-05-13,2,2,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,46,Transient,95.0,0,0
HB-104973,City Hotel,0,79,2025,January,4,26,2025-01-26,0,1,1,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,D,1,No Deposit,,365.0,0,Transient-Party,85.0,0,0
HB-083054,City Hotel,0,50,2024,January,2,14,2024-01-14,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,20.0,,43,Transient-Party,52.0,0,2
HB-054928,City Hotel,1,208,2024,July,31,30,2024-07-30,2,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.75,0,0
HB-013384,Resort Hotel,1,176,2025,August,33,13,2025-08-13,2,0,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,232.0,0,1
HB-095074,City Hotel,0,4,2024,August,33,12,2024-08-12,0,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,157.0,,0,Transient,92.0,0,0
HB-073422,City Hotel,1,150,2025,August,34,21,2025-08-21,1,2,3,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,83.0,,0,Transient,257.0,0,0
HB-088514,City Hotel,0,36,2024,May,19,7,2024-05-07,0,1,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,104.49,0,0
HB-050736,City Hotel,0,124,2024,May,19,6,2024-05-06,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,114.3,0,0
HB-012798,Resort Hotel,1,2,2025,July,29,17,2025-07-17,1,5,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,209.5,0,0
HB-061400,City Hotel,1,322,2024,December,50,9,2024-12-09,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,52.0,0,0
HB-025989,Resort Hotel,0,35,2024,July,28,14,2024-07-14,1,3,3,0.0,0,BB,MOZ,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient,204.0,0,1
HB-009775,Resort Hotel,1,55,2024,December,1,31,2024-12-31,2,5,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,94.29,0,0
HB-048195,City Hotel,0,92,2024,March,12,18,2024-03-18,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,87.3,0,0
HB-032461,Resort Hotel,0,43,2025,January,4,21,2025-01-21,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,33.6,0,1
HB-016404,Resort Hotel,0,49,2023,August,34,22,2023-08-22,2,4,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,169.83,0,1
HB-033337,Resort Hotel,0,22,2025,February,8,18,2025-02-18,1,1,2,0.0,1,BB,PRT,Complementary,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,7.0,1,1
HB-007831,Resort Hotel,1,168,2024,August,35,29,2024-08-29,1,3,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,241.75,0,0
HB-036901,Resort Hotel,0,164,2025,May,22,28,2025-05-28,2,2,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,410.0,,0,Transient,58.7,0,1
HB-080890,City Hotel,0,4,2025,May,19,8,2025-05-08,1,0,1,0.0,0,BB,ESP,Corporate,Corporate,1,0,1,D,D,0,No Deposit,,148.0,0,Transient,110.0,0,1
HB-003950,Resort Hotel,1,103,2024,February,6,9,2024-02-09,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,332.0,,0,Transient-Party,50.0,0,0
HB-104851,City Hotel,0,16,2025,January,3,19,2025-01-19,1,3,2,0.0,0,SC,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,75.44,0,1
HB-041703,City Hotel,1,138,2023,August,34,22,2023-08-22,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-115432,City Hotel,0,265,2025,June,26,24,2025-06-24,4,8,2,0.0,0,BB,DNK,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,112.87,0,2
HB-008763,Resort Hotel,0,364,2024,October,41,12,2024-10-12,1,4,3,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,C,2,No Deposit,223.0,223.0,0,Transient-Party,101.0,0,0
HB-004886,Resort Hotel,1,40,2024,April,14,5,2024-04-05,0,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,58.0,0,1
HB-034502,Resort Hotel,0,143,2025,March,12,20,2025-03-20,2,5,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,C,1,No Deposit,464.0,,0,Transient,48.0,0,1
HB-012318,Resort Hotel,1,317,2025,June,26,24,2025-06-24,2,5,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,241.0,,0,Transient,98.09,0,1
HB-087818,City Hotel,0,63,2024,April,17,22,2024-04-22,2,3,2,1.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,7.0,,0,Transient,90.06,0,0
HB-068712,City Hotel,1,75,2025,May,21,20,2025-05-20,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,90.0,0,0
HB-087950,City Hotel,0,3,2024,April,17,27,2024-04-27,0,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,131.0,0,1
HB-070085,City Hotel,1,219,2025,June,24,9,2025-06-09,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,105.0,0,0
HB-072968,City Hotel,1,0,2025,August,33,11,2025-08-11,0,0,0,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,P,P,0,No Deposit,,,0,Transient,0.0,0,0
HB-048232,City Hotel,1,5,2024,March,12,19,2024-03-19,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,90.0,0,0
HB-114418,City Hotel,0,32,2025,June,25,20,2025-06-20,0,2,1,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,94.0,0,0
HB-044823,City Hotel,0,51,2023,October,41,12,2023-10-12,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,11.0,,0,Group,69.11,0,0
HB-072422,City Hotel,1,95,2025,July,31,28,2025-07-28,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.0,0,1
HB-043388,City Hotel,0,74,2023,September,38,18,2023-09-18,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-034348,Resort Hotel,0,295,2025,March,11,15,2025-03-15,2,4,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,26.64,0,1
HB-033518,Resort Hotel,0,22,2025,February,8,18,2025-02-18,2,5,2,1.0,0,BB,SWE,Online TA,TA/TO,0,0,0,G,G,1,No Deposit,240.0,,0,Transient,88.0,0,0
HB-078333,City Hotel,0,4,2025,January,3,16,2025-01-16,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,3,25,A,A,1,No Deposit,,40.0,0,Transient,67.0,1,0
HB-024935,Resort Hotel,0,113,2024,June,22,2,2024-06-02,2,5,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,59.31,0,0
HB-060916,City Hotel,1,43,2024,November,48,25,2024-11-25,2,2,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,0
HB-093183,City Hotel,0,81,2024,July,28,11,2024-07-11,2,5,3,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,190.29,0,0
HB-077102,City Hotel,0,219,2023,September,36,4,2023-09-04,1,2,1,0.0,0,BB,SWE,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,76.67,0,0
HB-096751,City Hotel,0,205,2024,September,36,5,2024-09-05,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.9,0,2
HB-111608,City Hotel,0,122,2025,May,19,11,2025-05-11,0,2,1,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,117.0,0,0
HB-106995,City Hotel,0,16,2025,March,10,5,2025-03-05,1,0,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,1
HB-060818,City Hotel,1,104,2024,November,47,22,2024-11-22,0,5,1,0.0,0,BB,PHL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,0
HB-107217,City Hotel,0,13,2025,March,10,9,2025-03-09,0,1,1,0.0,0,SC,LUX,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,10.0,,0,Transient,70.2,0,0
HB-095111,City Hotel,0,160,2024,August,32,8,2024-08-08,2,5,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,106.75,1,0
HB-099274,City Hotel,0,68,2024,October,41,8,2024-10-08,2,1,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,135.0,0,3
HB-005290,Resort Hotel,1,143,2024,April,17,24,2024-04-24,2,2,2,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,68.0,,0,Transient,84.0,0,0
HB-081707,City Hotel,1,109,2024,February,8,21,2024-02-21,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,44,Transient,75.0,0,0
HB-091316,City Hotel,0,45,2024,June,25,17,2024-06-17,1,2,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,65.0,0,1
HB-059820,City Hotel,1,14,2024,November,44,3,2024-11-03,0,1,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,112.0,0,1
HB-017318,Resort Hotel,0,0,2023,October,40,4,2023-10-04,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,0,No Deposit,,,0,Transient,76.0,0,0
HB-059007,City Hotel,1,468,2024,October,42,20,2024-10-20,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-107173,City Hotel,0,46,2025,March,10,7,2025-03-07,0,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.2,0,0
HB-020987,Resort Hotel,0,0,2024,February,7,12,2024-02-12,0,2,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,D,E,1,No Deposit,250.0,,0,Transient,97.5,0,0
HB-086775,City Hotel,0,2,2024,April,15,8,2024-04-08,0,1,1,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.0,0,0
HB-037001,Resort Hotel,0,118,2025,May,22,26,2025-05-26,2,7,2,0.0,0,BB,FIN,Direct,Direct,0,0,0,D,D,2,No Deposit,250.0,,0,Transient,99.28,0,0
HB-010071,Resort Hotel,1,238,2025,February,7,10,2025-02-10,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,155.0,,0,Transient,54.0,0,0
HB-052234,City Hotel,1,330,2024,June,22,2,2024-06-02,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-082949,City Hotel,0,0,2024,January,1,6,2024-01-06,0,2,1,0.0,0,BB,ESP,Corporate,Corporate,0,0,0,A,A,0,No Deposit,91.0,,0,Transient,79.0,0,0
HB-008191,Resort Hotel,0,336,2024,September,37,15,2024-09-15,2,3,1,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,A,2,No Deposit,,223.0,0,Transient-Party,60.0,1,0
HB-107249,City Hotel,0,42,2025,March,10,5,2025-03-05,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,91.8,0,0
HB-089845,City Hotel,0,7,2024,May,21,25,2024-05-25,0,2,2,2.0,0,BB,DEU,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,241.0,0,2
HB-095856,City Hotel,0,42,2024,August,34,22,2024-08-22,1,2,2,2.0,0,BB,ESP,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,192.3,1,2
HB-112769,City Hotel,0,7,2025,May,21,25,2025-05-25,0,3,1,0.0,0,BB,GBR,Online TA,GDS,0,0,0,A,D,0,No Deposit,195.0,,0,Transient,180.0,0,0
HB-016146,Resort Hotel,0,38,2023,August,32,13,2023-08-13,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,F,0,No Deposit,240.0,,0,Transient,171.9,0,1
HB-008293,Resort Hotel,1,168,2024,September,38,21,2024-09-21,2,4,2,0.0,0,BB,EST,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,95.67,0,0
HB-050729,City Hotel,1,54,2024,May,19,6,2024-05-06,0,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,116.1,0,0
HB-043743,City Hotel,0,50,2023,September,38,24,2023-09-24,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,86.4,0,1
HB-044631,City Hotel,0,50,2023,October,41,9,2023-10-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,32.0,,49,Transient-Party,85.0,0,0
HB-043975,City Hotel,0,35,2023,September,39,26,2023-09-26,2,4,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,166.58,0,2
HB-015389,Resort Hotel,0,130,2023,July,27,5,2023-07-05,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,196.0,,0,Transient,82.35,1,0
HB-069205,City Hotel,1,246,2025,May,22,27,2025-05-27,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,100.0,0,0
HB-011609,Resort Hotel,1,60,2025,May,21,21,2025-05-21,2,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,169.0,0,Transient-Party,50.0,0,0
HB-089869,City Hotel,0,14,2024,May,22,27,2024-05-27,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,62.5,0,0
HB-094264,City Hotel,0,110,2024,July,31,30,2024-07-30,2,1,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,7.0,,0,Transient,168.1,0,3
HB-088997,City Hotel,0,196,2024,May,19,12,2024-05-12,1,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,128.0,,0,Transient-Party,80.75,0,1
HB-088156,City Hotel,0,127,2024,April,17,28,2024-04-28,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,90.0,0,0
HB-016039,Resort Hotel,0,4,2023,August,32,9,2023-08-09,2,1,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,C,1,No Deposit,240.0,,0,Transient,187.0,0,3
HB-059521,City Hotel,1,247,2024,October,44,28,2024-10-28,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,110.0,0,0
HB-034658,Resort Hotel,0,0,2025,March,14,31,2025-03-31,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,521.0,0,Transient,65.0,0,0
HB-024961,Resort Hotel,0,146,2024,June,22,1,2024-06-01,2,8,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,72.0,0,1
HB-025371,Resort Hotel,0,164,2024,June,25,17,2024-06-17,2,5,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,,0,Transient,94.89,0,2
HB-062782,City Hotel,1,46,2025,January,4,22,2025-01-22,2,0,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,79.2,0,0
HB-113861,City Hotel,0,289,2025,June,24,14,2025-06-14,0,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,1,A,A,2,No Deposit,9.0,,0,Transient,128.7,0,2
HB-049505,City Hotel,1,101,2024,April,15,14,2024-04-14,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,130.0,0,0
HB-060933,City Hotel,1,128,2024,November,48,26,2024-11-26,1,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.0,0,1
HB-003673,Resort Hotel,0,165,2023,December,52,30,2023-12-30,0,4,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,C,0,No Deposit,308.0,,122,Transient-Party,136.5,0,0
HB-072136,City Hotel,1,423,2025,July,30,22,2025-07-22,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,80.0,0,0
HB-053828,City Hotel,1,85,2024,June,26,30,2024-06-30,0,3,2,0.0,0,SC,TUR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,103.5,0,0
HB-103948,City Hotel,0,41,2024,December,52,27,2024-12-27,2,5,2,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,220.0,,0,Transient-Party,69.29,0,0
HB-013359,Resort Hotel,1,161,2025,August,33,11,2025-08-11,1,2,2,2.0,0,BB,USA,Online TA,TA/TO,0,0,0,G,G,1,No Deposit,240.0,,0,Transient,300.0,0,1
HB-064328,City Hotel,1,27,2025,March,10,6,2025-03-06,1,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,75.0,0,0
HB-056747,City Hotel,1,126,2024,September,37,12,2024-09-12,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,173.0,,0,Transient,80.75,0,1
HB-024111,Resort Hotel,0,39,2024,May,19,10,2024-05-10,0,2,3,1.0,0,BB,BRA,Online TA,TA/TO,0,0,0,H,H,1,No Deposit,240.0,,0,Transient-Party,136.0,1,0
HB-045506,City Hotel,0,100,2023,October,44,31,2023-10-31,1,1,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-062212,City Hotel,1,11,2025,January,1,5,2025-01-05,0,1,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,1
HB-060426,City Hotel,1,489,2024,November,45,10,2024-11-10,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-119329,City Hotel,0,104,2025,August,35,31,2025-08-31,0,3,1,0.0,0,BB,JPN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,129.33,0,1
HB-104763,City Hotel,0,7,2025,January,4,20,2025-01-20,0,2,1,0.0,0,SC,ATA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.0,0,1
HB-105363,City Hotel,0,53,2025,February,6,3,2025-02-03,1,2,3,2.0,0,HB,ESP,Direct,Direct,0,0,0,G,G,1,No Deposit,14.0,,0,Transient,268.0,0,1
HB-109244,City Hotel,0,103,2025,April,14,6,2025-04-06,0,3,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,153.0,0,0
HB-000165,Resort Hotel,0,81,2023,July,27,6,2023-07-06,1,3,2,2.0,0,HB,CHE,Direct,Direct,0,0,0,G,G,0,No Deposit,250.0,,0,Transient,210.0,1,0
HB-111327,City Hotel,0,52,2025,May,19,6,2025-05-06,2,1,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,189.0,0,0
HB-102703,City Hotel,0,67,2024,December,49,2,2024-12-02,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-077003,City Hotel,0,0,2023,August,34,26,2023-08-26,0,1,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,B,0,No Deposit,9.0,,0,Contract,156.0,0,2
HB-006488,Resort Hotel,1,221,2024,June,24,12,2024-06-12,3,5,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,G,G,0,No Deposit,250.0,,0,Transient,114.75,0,1
HB-014326,Resort Hotel,0,5,2023,October,43,28,2023-10-28,0,2,1,0.0,0,BB,,Corporate,Corporate,0,0,0,A,A,1,No Deposit,,325.0,0,Transient-Party,48.0,1,0
HB-047042,City Hotel,1,38,2024,February,6,5,2024-02-05,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,87.3,0,1
HB-013854,Resort Hotel,0,1,2024,April,14,7,2024-04-07,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,56.0,0,1
HB-065093,City Hotel,1,256,2025,March,13,24,2025-03-24,0,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.0,0,0
HB-113714,City Hotel,0,39,2025,June,24,9,2025-06-09,0,2,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,220.0,0,1
HB-011582,Resort Hotel,1,45,2025,May,20,18,2025-05-18,2,5,2,2.0,0,BB,CN,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,169.0,0,1
HB-048395,City Hotel,1,42,2024,March,12,22,2024-03-22,0,3,2,1.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,22.0,,0,Transient,76.05,0,1
HB-066454,City Hotel,1,125,2025,April,16,20,2025-04-20,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,33.0,,0,Transient,85.0,0,0
HB-029198,Resort Hotel,0,390,2024,October,43,24,2024-10-24,1,0,2,0.0,0,BB,GBR,Groups,Corporate,0,0,1,A,A,3,No Deposit,,,0,Transient-Party,49.0,0,0
HB-063425,City Hotel,1,9,2025,February,7,11,2025-02-11,2,4,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,70.4,0,0
HB-095304,City Hotel,0,111,2024,August,33,16,2024-08-16,0,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,42.0,,0,Transient,72.25,0,0
HB-046039,City Hotel,0,135,2023,December,49,5,2023-12-05,2,1,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,D,1,No Deposit,1.0,,0,Transient-Party,60.0,0,0
HB-095158,City Hotel,0,152,2024,August,33,13,2024-08-13,2,1,3,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,146.7,0,1
HB-051098,City Hotel,1,10,2024,May,20,13,2024-05-13,2,3,1,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,215.0,0,0
HB-102664,City Hotel,0,232,2024,December,48,1,2024-12-01,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,91.8,0,2
HB-064206,City Hotel,1,28,2025,March,9,2,2025-03-02,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,95.0,0,0
HB-016410,Resort Hotel,1,288,2023,September,35,2,2023-09-02,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,1,No Deposit,240.0,,0,Transient-Party,110.7,0,0
HB-027569,Resort Hotel,0,10,2024,August,35,28,2024-08-28,2,3,2,1.0,0,HB,PRT,Direct,Direct,0,0,0,C,C,5,No Deposit,250.0,,0,Transient,213.0,1,0
HB-058830,City Hotel,1,283,2024,October,42,16,2024-10-16,2,0,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,96.0,0,0
HB-027908,Resort Hotel,0,189,2024,September,37,11,2024-09-11,2,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient,119.0,0,1
HB-044677,City Hotel,0,156,2023,October,41,9,2023-10-09,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.25,0,1
HB-068472,City Hotel,1,115,2025,May,20,18,2025-05-18,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,170.0,,0,Transient,190.0,0,0
HB-106647,City Hotel,0,17,2025,February,9,26,2025-02-26,2,1,1,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,1
HB-088587,City Hotel,0,103,2024,May,18,5,2024-05-05,1,3,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,95.88,0,1
HB-103722,City Hotel,0,123,2024,December,52,26,2024-12-26,1,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,105.61,0,2
HB-014350,Resort Hotel,0,72,2024,February,6,6,2024-02-06,2,1,2,1.0,0,Undefined,,Direct,Direct,0,0,1,D,F,1,No Deposit,,,0,Transient-Party,39.67,0,1
HB-000078,Resort Hotel,0,2,2023,July,27,3,2023-07-03,2,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,122.0,0,0
HB-104838,City Hotel,0,11,2025,January,4,20,2025-01-20,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,104.0,0,1
HB-089677,City Hotel,0,43,2024,May,21,21,2024-05-21,2,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,140.4,0,1
HB-102794,City Hotel,0,41,2024,December,49,2,2024-12-02,2,2,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.9,0,2
HB-013486,Resort Hotel,1,149,2025,August,33,17,2025-08-17,1,3,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,240.0,0,2
HB-001813,Resort Hotel,0,0,2023,September,37,16,2023-09-16,0,1,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,58.5,0,1
HB-062216,City Hotel,1,545,2025,January,1,5,2025-01-05,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-040901,City Hotel,0,16,2023,August,32,8,2023-08-08,2,2,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-017293,Resort Hotel,0,56,2023,September,39,30,2023-09-30,0,3,2,0.0,0,BB,LTU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,67.8,1,2
HB-092813,City Hotel,0,112,2024,July,27,7,2024-07-07,2,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient-Party,72.25,0,1
HB-009609,Resort Hotel,1,350,2024,December,51,19,2024-12-19,3,8,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,39.0,0,1
HB-082793,City Hotel,1,68,2024,February,7,17,2024-02-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,37.0,,0,Transient,75.0,0,0
HB-033853,Resort Hotel,0,7,2025,March,9,2,2025-03-02,1,3,1,0.0,0,BB,GBR,Groups,Corporate,0,0,0,D,F,1,No Deposit,,223.0,0,Transient-Party,47.0,0,0
HB-041383,City Hotel,0,40,2023,August,33,15,2023-08-15,2,2,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-085252,City Hotel,0,5,2024,March,10,7,2024-03-07,1,4,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,55.74,0,0
HB-094452,City Hotel,0,207,2024,August,31,4,2024-08-04,0,1,2,2.0,0,BB,DEU,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,168.3,0,1
HB-062380,City Hotel,1,20,2025,January,2,12,2025-01-12,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.5,0,1
HB-046499,City Hotel,1,145,2024,January,1,3,2024-01-03,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,85,Transient,65.0,0,0
HB-061391,City Hotel,1,322,2024,December,50,9,2024-12-09,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,52.0,0,0
HB-001821,Resort Hotel,0,42,2023,September,37,16,2023-09-16,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,74.0,0,0
HB-068570,City Hotel,1,105,2025,May,21,19,2025-05-19,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-066358,City Hotel,1,386,2025,April,16,18,2025-04-18,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-099498,City Hotel,0,6,2024,December,49,8,2024-12-08,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,2,No Deposit,,40.0,0,Transient,67.0,1,1
HB-088803,City Hotel,0,71,2024,May,19,10,2024-05-10,0,3,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,205.0,,0,Transient,126.0,0,1
HB-075781,City Hotel,1,323,2023,September,36,5,2023-09-05,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-049706,City Hotel,0,103,2024,April,16,17,2024-04-17,2,2,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,70.03,0,0
HB-080126,City Hotel,1,72,2023,December,52,27,2023-12-27,2,0,1,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,65.0,0,0
HB-004598,Resort Hotel,1,136,2024,March,12,24,2024-03-24,0,3,2,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,38.0,0,0
HB-006294,Resort Hotel,1,215,2024,June,22,1,2024-06-01,0,3,2,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,96.0,,0,Transient,110.0,0,0
HB-044355,City Hotel,0,29,2023,October,40,4,2023-10-04,2,0,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Group,76.81,0,0
HB-039950,Resort Hotel,0,217,2025,August,35,29,2025-08-29,0,4,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,410.0,,0,Transient,106.35,0,1
HB-057535,City Hotel,1,250,2024,September,39,26,2024-09-26,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,95.0,0,0
HB-097605,City Hotel,0,128,2024,September,38,16,2024-09-16,0,2,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,112.2,0,1
HB-025621,Resort Hotel,0,25,2024,July,27,3,2024-07-03,1,0,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,131.0,1,1
HB-051715,City Hotel,1,158,2024,May,21,24,2024-05-24,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,31,Transient,130.0,0,0
HB-036527,Resort Hotel,0,89,2025,May,21,19,2025-05-19,2,2,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,241.0,,0,Transient,100.0,0,1
HB-059510,City Hotel,1,189,2024,October,44,28,2024-10-28,1,2,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,109.8,0,0
HB-025926,Resort Hotel,0,24,2024,July,28,14,2024-07-14,0,2,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,B,1,No Deposit,240.0,,0,Transient,171.0,0,1
HB-062756,City Hotel,1,256,2025,January,4,21,2025-01-21,2,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,77.35,0,0
HB-028122,Resort Hotel,0,55,2024,September,38,19,2024-09-19,1,1,2,0.0,0,BB,LUX,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,80.0,0,1
HB-043903,City Hotel,0,192,2023,September,39,25,2023-09-25,2,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,102.0,0,0
HB-092693,City Hotel,0,177,2024,July,28,9,2024-07-09,1,1,3,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,D,1,No Deposit,1.0,,0,Transient-Party,139.2,0,0
HB-025437,Resort Hotel,0,41,2024,June,26,26,2024-06-26,1,0,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,129.0,0,1
HB-015526,Resort Hotel,0,178,2023,July,29,19,2023-07-19,2,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,E,1,No Deposit,5.0,,0,Transient,96.3,0,2
HB-078775,City Hotel,0,12,2023,October,41,12,2023-10-12,1,3,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,95.0,,0,Transient-Party,100.0,0,0
HB-056409,City Hotel,1,19,2024,September,36,5,2024-09-05,1,1,2,0.0,0,BB,COL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,145.0,0,1
HB-010491,Resort Hotel,1,142,2025,March,10,9,2025-03-09,2,3,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,60.3,0,0
HB-082365,City Hotel,1,108,2024,March,12,18,2024-03-18,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,154.0,,0,Transient,80.0,0,0
HB-022186,Resort Hotel,0,270,2024,March,11,13,2024-03-13,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,23.7,0,3
HB-089046,City Hotel,0,40,2024,May,20,13,2024-05-13,2,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.9,0,1
HB-014172,Resort Hotel,0,0,2024,April,14,6,2024-04-06,0,1,1,0.0,0,BB,,Corporate,Corporate,0,0,4,A,A,1,No Deposit,,,0,Transient,50.4,0,0
HB-079525,City Hotel,1,192,2024,May,18,5,2024-05-05,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,D,D,0,No Deposit,9.0,,0,Transient,115.2,0,1
HB-040983,City Hotel,0,0,2023,August,32,10,2023-08-10,1,1,2,1.0,0,BB,MAR,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,110.0,0,0
HB-000116,Resort Hotel,0,109,2023,July,27,4,2023-07-04,2,6,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,123.0,0,1
HB-016752,Resort Hotel,0,194,2023,September,35,1,2023-09-01,2,8,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,142.0,,0,Contract,71.55,0,0
HB-091590,City Hotel,0,13,2024,June,25,23,2024-06-23,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,95.0,0,1
HB-039958,Resort Hotel,0,63,2025,August,35,28,2025-08-28,1,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,118.5,0,1
HB-092907,City Hotel,0,93,2024,July,28,12,2024-07-12,0,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.5,0,1
HB-101535,City Hotel,0,54,2024,November,46,11,2024-11-11,1,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,2
HB-098205,City Hotel,0,336,2024,September,38,21,2024-09-21,1,4,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,78.0,0,0
HB-002494,Resort Hotel,0,47,2023,October,42,19,2023-10-19,1,4,2,0.0,0,HB,ESP,Groups,Direct,0,0,0,A,A,0,No Deposit,,,47,Transient-Party,76.8,0,0
HB-096636,City Hotel,0,104,2024,September,36,2,2024-09-02,1,2,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,138.6,0,2
HB-040247,City Hotel,1,103,2023,July,29,18,2023-07-18,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-007032,Resort Hotel,1,203,2024,July,29,17,2024-07-17,2,4,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,170.0,0,1
HB-008534,Resort Hotel,1,64,2024,October,40,4,2024-10-04,0,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,79.0,0,0
HB-070663,City Hotel,1,12,2025,June,25,20,2025-06-20,0,3,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,10.0,,0,Transient,95.0,0,0
HB-060581,City Hotel,1,97,2024,November,46,16,2024-11-16,0,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.0,0,1
HB-043749,City Hotel,0,86,2023,September,38,24,2023-09-24,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,12.0,,0,Transient-Party,87.5,0,0
HB-080404,City Hotel,1,34,2023,December,49,8,2023-12-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,0,Transient,90.0,0,0
HB-000912,Resort Hotel,0,0,2023,August,31,5,2023-08-05,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,L,F,0,No Deposit,,,0,Transient,200.0,0,0
HB-024345,Resort Hotel,0,138,2024,May,20,16,2024-05-16,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,242.0,,0,Transient,79.2,0,1
HB-012383,Resort Hotel,1,178,2025,June,26,26,2025-06-26,1,4,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,241.0,,0,Transient,131.67,0,0
HB-055595,City Hotel,1,145,2024,August,33,17,2024-08-17,0,2,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,1,No Deposit,,,0,Transient-Party,147.0,0,1
HB-009684,Resort Hotel,1,107,2024,December,52,25,2024-12-25,2,3,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,C,2,No Deposit,240.0,,0,Transient,59.5,0,1
HB-012635,Resort Hotel,1,151,2025,July,28,9,2025-07-09,2,3,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,160.0,0,2
HB-047283,City Hotel,1,25,2024,February,7,14,2024-02-14,2,1,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,72.8,0,0
HB-068762,City Hotel,1,38,2025,May,21,20,2025-05-20,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,13,Transient-Party,90.0,0,0
HB-092953,City Hotel,0,3,2024,July,28,13,2024-07-13,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,118.15,0,0
HB-017599,Resort Hotel,0,7,2023,October,41,12,2023-10-12,1,3,2,0.0,0,FB,PRT,Corporate,Corporate,0,0,0,A,A,1,Non Refund,,174.0,0,Transient-Party,109.0,0,0
HB-106090,City Hotel,0,5,2025,February,8,18,2025-02-18,1,1,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,9.0,0,0
HB-085351,City Hotel,0,133,2024,March,11,11,2024-03-11,1,2,2,0.0,0,BB,PER,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,129.0,,0,Transient-Party,84.33,0,1
HB-089549,City Hotel,0,86,2024,May,21,20,2024-05-20,1,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,3.0,,0,Transient-Party,60.0,0,0
HB-062857,City Hotel,1,59,2025,January,4,23,2025-01-23,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,326.0,,0,Transient,80.0,0,0
HB-062109,City Hotel,1,124,2025,January,1,2,2025-01-02,1,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,102.6,0,1
HB-011727,Resort Hotel,1,313,2025,May,22,27,2025-05-27,2,5,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,,0,Transient,86.91,0,0
HB-107841,City Hotel,0,192,2025,March,11,15,2025-03-15,0,4,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,119.0,0,2
HB-038824,Resort Hotel,0,82,2025,July,30,23,2025-07-23,3,5,2,0.0,0,HB,GBR,Direct,Direct,0,0,0,F,F,1,No Deposit,250.0,,0,Transient,294.0,0,2
HB-006128,Resort Hotel,1,183,2024,May,21,26,2024-05-26,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,65.7,0,1
HB-044010,City Hotel,0,68,2023,September,39,29,2023-09-29,0,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,20.0,,0,Transient-Party,65.0,0,0
HB-038283,Resort Hotel,0,0,2025,July,28,13,2025-07-13,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,E,E,0,No Deposit,,34.0,0,Transient,130.0,0,0
HB-053894,City Hotel,1,114,2024,July,27,1,2024-07-01,1,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,192.0,,0,Transient,75.0,0,0
HB-043849,City Hotel,1,87,2023,September,39,25,2023-09-25,2,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-100212,City Hotel,0,386,2024,October,43,23,2024-10-23,2,0,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-040972,City Hotel,1,39,2023,August,32,10,2023-08-10,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-028593,Resort Hotel,0,245,2024,September,39,26,2024-09-26,3,7,2,0.0,0,HB,CN,Groups,TA/TO,0,0,0,A,I,2,No Deposit,15.0,,0,Transient-Party,42.0,0,0
HB-075150,City Hotel,1,278,2023,July,29,22,2023-07-22,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-019007,Resort Hotel,0,4,2023,December,49,5,2023-12-05,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,330.0,,0,Transient,29.0,0,1
HB-003525,Resort Hotel,0,119,2023,December,51,21,2023-12-21,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,24.95,0,1
HB-058167,City Hotel,1,179,2024,October,41,7,2024-10-07,0,2,3,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,141.3,0,0
HB-083258,City Hotel,0,33,2024,January,4,25,2024-01-25,1,1,3,0.0,0,BB,BRA,Corporate,Corporate,0,0,0,A,D,1,No Deposit,38.0,,15,Transient-Party,95.0,0,0
HB-099549,City Hotel,0,0,2024,October,41,13,2024-10-13,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,B,0,No Deposit,23.0,,0,Transient,90.0,0,0
HB-104768,City Hotel,0,0,2025,January,4,21,2025-01-21,0,1,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,0
HB-067088,City Hotel,1,168,2025,April,18,28,2025-04-28,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.5,0,0
HB-053834,City Hotel,1,123,2024,June,26,30,2024-06-30,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.45,0,0
HB-019314,Resort Hotel,0,4,2023,December,50,11,2023-12-11,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,47.0,0,0
HB-067957,City Hotel,1,316,2025,May,19,10,2025-05-10,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.8,0,1
HB-014400,Resort Hotel,0,10,2024,October,44,29,2024-10-29,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient-Party,38.0,0,0
HB-037590,Resort Hotel,0,256,2025,June,24,9,2025-06-09,4,10,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,71.18,0,1
HB-100252,City Hotel,0,200,2024,October,43,23,2024-10-23,2,0,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,90.0,0,0
HB-054448,City Hotel,1,136,2024,July,29,16,2024-07-16,1,1,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,121.5,0,0
HB-046290,City Hotel,0,144,2023,December,52,29,2023-12-29,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,72.25,0,2
HB-086802,City Hotel,0,33,2024,April,14,5,2024-04-05,0,4,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,85.5,0,0
HB-109782,City Hotel,0,121,2025,April,15,13,2025-04-13,1,3,2,0.0,0,SC,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,132.0,,0,Transient,80.1,0,0
HB-065978,City Hotel,1,304,2025,April,15,12,2025-04-12,0,1,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,126.0,0,0
HB-099490,City Hotel,0,22,2024,October,41,13,2024-10-13,0,1,1,0.0,0,BB,ESP,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,67.0,1,0
HB-046548,City Hotel,0,0,2024,January,1,6,2024-01-06,0,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.3,0,1
HB-064820,City Hotel,1,7,2025,March,12,17,2025-03-17,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,95.0,0,0
HB-003893,Resort Hotel,1,18,2024,February,6,5,2024-02-05,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,56.57,0,2
HB-047363,City Hotel,1,44,2024,February,7,17,2024-02-17,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,44.0,,3,Transient,75.0,0,0
HB-093587,City Hotel,0,226,2024,July,30,22,2024-07-22,0,2,2,0.0,0,BB,USA,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,96,Transient-Party,76.5,0,1
HB-050435,City Hotel,0,118,2024,April,18,30,2024-04-30,2,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,97.75,0,1
HB-049445,City Hotel,1,17,2024,April,15,14,2024-04-14,0,2,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,145.0,0,0
HB-092201,City Hotel,0,195,2024,June,26,30,2024-06-30,0,2,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,27.0,,0,Transient,82.45,0,1
HB-109770,City Hotel,0,298,2025,April,16,14,2025-04-14,1,2,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,90.0,0,0
HB-000406,Resort Hotel,0,38,2023,July,28,14,2023-07-14,4,10,2,0.0,0,HB,SWE,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,241.0,,0,Transient,109.9,0,2
HB-013010,Resort Hotel,1,198,2025,July,30,27,2025-07-27,2,5,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,222.0,0,2
HB-093680,City Hotel,0,295,2024,July,29,21,2024-07-21,1,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,95.4,0,1
HB-103278,City Hotel,0,213,2024,December,51,17,2024-12-17,0,1,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,110.7,0,0
HB-089183,City Hotel,0,2,2024,May,20,15,2024-05-15,2,2,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,21.0,,0,Transient-Party,66.88,0,0
HB-028080,Resort Hotel,0,246,2024,September,37,10,2024-09-10,4,6,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,95.0,,0,Transient,77.22,0,2
HB-025450,Resort Hotel,0,10,2024,June,26,27,2024-06-27,1,0,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,184.0,,0,Transient,120.0,0,0
HB-063650,City Hotel,1,34,2025,February,7,16,2025-02-16,2,6,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,61.52,0,0
HB-078362,City Hotel,0,5,2023,October,40,4,2023-10-04,2,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,130.75,0,1
HB-101840,City Hotel,0,3,2024,November,46,14,2024-11-14,1,4,2,0.0,1,BB,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,94.35,0,2
HB-100953,City Hotel,0,74,2024,October,44,31,2024-10-31,1,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.23,0,2
HB-041964,City Hotel,0,1,2023,August,35,28,2023-08-28,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,106.0,0,2
HB-033605,Resort Hotel,0,25,2025,February,9,24,2025-02-24,1,2,2,0.0,0,HB,ZWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,65.83,0,1
HB-002676,Resort Hotel,0,50,2023,October,43,24,2023-10-24,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,143.0,,0,Contract,42.5,0,1
HB-099903,City Hotel,0,25,2024,October,42,17,2024-10-17,1,2,1,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,129.0,0,2
HB-093473,City Hotel,0,189,2024,July,29,17,2024-07-17,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,99.45,0,1
HB-008806,Resort Hotel,1,24,2024,October,42,15,2024-10-15,0,1,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,G,G,1,No Deposit,250.0,,0,Transient,141.0,0,1
HB-009096,Resort Hotel,1,117,2024,October,43,27,2024-10-27,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,E,E,5,No Deposit,240.0,,0,Transient-Party,66.02,0,0
HB-103762,City Hotel,0,16,2024,December,52,29,2024-12-29,0,2,2,0.0,0,BB,BRA,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,140.0,0,0
HB-064437,City Hotel,1,241,2025,March,10,9,2025-03-09,0,3,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,0
HB-112485,City Hotel,0,18,2025,May,21,21,2025-05-21,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,7.0,,0,Transient,126.0,0,1
HB-062020,City Hotel,1,18,2024,December,1,30,2024-12-30,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,148.0,0,2
HB-068071,City Hotel,1,189,2025,May,20,12,2025-05-12,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,143.1,0,1
HB-113759,City Hotel,0,40,2025,June,23,8,2025-06-08,0,3,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,190.0,0,2
HB-097922,City Hotel,0,159,2024,September,38,19,2024-09-19,1,2,2,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,144.0,0,0
HB-032591,Resort Hotel,0,3,2025,January,5,28,2025-01-28,1,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,72.0,0,1
HB-062780,City Hotel,1,40,2025,January,4,22,2025-01-22,1,0,2,0.0,0,SC,LUX,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,0
HB-050067,City Hotel,1,142,2024,April,17,22,2024-04-22,2,3,2,0.0,0,BB,POL,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,103.0,0,0
HB-027567,Resort Hotel,0,69,2024,August,35,29,2024-08-29,1,3,2,2.0,0,HB,PRT,Direct,Direct,0,0,0,G,G,1,No Deposit,250.0,,0,Transient,273.9,1,0
HB-099933,City Hotel,0,25,2024,October,42,18,2024-10-18,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,85.0,0,1
HB-109212,City Hotel,0,111,2025,April,14,5,2025-04-05,0,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,1
HB-097207,City Hotel,0,29,2024,September,37,9,2024-09-09,2,2,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,144.68,0,3
HB-032955,Resort Hotel,0,53,2025,February,6,4,2025-02-04,2,5,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,99.43,0,1
HB-088013,City Hotel,0,92,2024,April,17,24,2024-04-24,2,3,2,0.0,0,HB,FIN,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,97.41,0,1
HB-097524,City Hotel,0,74,2024,September,37,14,2024-09-14,0,4,3,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,168.3,0,0
HB-074950,City Hotel,1,153,2023,August,31,3,2023-08-03,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-046572,City Hotel,0,2,2024,January,2,8,2024-01-08,1,2,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,87.3,1,1
HB-106909,City Hotel,0,23,2025,March,9,2,2025-03-02,0,3,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,1
HB-037767,Resort Hotel,0,259,2025,June,26,24,2025-06-24,2,3,2,0.0,0,BB,CN,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,104.49,0,0
HB-058946,City Hotel,1,205,2024,October,42,18,2024-10-18,0,4,2,0.0,0,SC,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.5,0,2
HB-084312,City Hotel,0,35,2024,February,8,19,2024-02-19,2,2,2,0.0,0,SC,CHL,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient-Party,84.35,0,1
HB-104136,City Hotel,0,116,2025,January,1,2,2025-01-02,1,3,1,1.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,88.4,0,1
HB-085555,City Hotel,0,42,2024,March,11,16,2024-03-16,0,2,1,0.0,0,BB,DEU,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient-Party,71.1,0,1
HB-096880,City Hotel,0,88,2024,September,36,3,2024-09-03,2,5,1,0.0,0,BB,USA,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,86.0,,0,Transient-Party,85.0,0,1
HB-060880,City Hotel,1,308,2024,November,48,25,2024-11-25,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,52.0,0,0
HB-107145,City Hotel,0,22,2025,March,10,4,2025-03-04,2,2,2,2.0,0,BB,USA,Direct,Direct,0,0,0,G,G,0,No Deposit,14.0,,0,Transient,223.0,0,0
HB-043294,City Hotel,0,162,2023,September,37,17,2023-09-17,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,70.0,0,1
HB-021905,Resort Hotel,0,23,2024,March,11,12,2024-03-12,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,0
HB-062993,City Hotel,1,61,2025,January,4,25,2025-01-25,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,326.0,,0,Transient,80.0,0,0
HB-048085,City Hotel,1,11,2024,March,11,16,2024-03-16,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,B,B,0,No Deposit,138.0,,0,Transient,62.0,0,0
HB-013764,Resort Hotel,1,29,2025,August,35,29,2025-08-29,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,194.0,0,0
HB-031541,Resort Hotel,0,12,2024,December,52,27,2024-12-27,0,4,2,0.0,0,SC,PRT,Direct,Direct,0,0,0,A,I,3,No Deposit,,,0,Transient,0.0,0,0
HB-088645,City Hotel,0,49,2024,May,19,8,2024-05-08,2,0,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,116.1,0,2
HB-019958,Resort Hotel,0,0,2024,January,1,4,2024-01-04,2,5,2,0.0,0,BB,USA,Direct,Direct,0,0,0,A,D,5,No Deposit,,,0,Transient,48.0,0,0
HB-106940,City Hotel,0,82,2025,March,10,3,2025-03-03,0,2,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,142.2,0,1
HB-102063,City Hotel,0,215,2024,November,47,21,2024-11-21,1,1,1,0.0,0,BB,NLD,Groups,Corporate,0,0,0,A,A,3,No Deposit,,233.0,0,Transient,75.0,0,0
HB-109710,City Hotel,0,36,2025,April,16,15,2025-04-15,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,0
HB-006943,Resort Hotel,1,244,2024,July,28,12,2024-07-12,2,5,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,84.47,0,1
HB-062514,City Hotel,1,38,2025,January,3,14,2025-01-14,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,Non Refund,,67.0,0,Transient,75.0,0,0
HB-036872,Resort Hotel,0,303,2025,May,21,25,2025-05-25,2,5,2,0.0,1,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,56.7,0,0
HB-032702,Resort Hotel,0,8,2025,February,5,1,2025-02-01,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient-Party,48.0,1,1
HB-104730,City Hotel,0,29,2025,January,3,18,2025-01-18,0,3,1,0.0,0,BB,FIN,Groups,TA/TO,0,0,0,A,A,0,No Deposit,171.0,,0,Transient-Party,65.0,0,0
HB-036502,Resort Hotel,0,208,2025,May,20,16,2025-05-16,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,F,0,No Deposit,40.0,,0,Contract,70.85,0,0
HB-010914,Resort Hotel,1,217,2025,April,15,10,2025-04-10,1,1,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,314.0,,0,Transient,71.2,0,0
HB-067212,City Hotel,1,78,2025,April,18,29,2025-04-29,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient,90.0,0,0
HB-064904,City Hotel,1,46,2025,March,12,20,2025-03-20,1,2,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,142.2,0,0
HB-116830,City Hotel,0,108,2025,July,30,24,2025-07-24,1,1,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,3,No Deposit,83.0,,0,Transient,127.1,0,0
HB-008039,Resort Hotel,1,238,2024,September,36,7,2024-09-07,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,D,D,0,Non Refund,1.0,,0,Transient,89.0,0,0
HB-032495,Resort Hotel,0,5,2025,January,4,26,2025-01-26,0,3,2,2.0,0,BB,PRT,Direct,Direct,0,0,0,A,C,1,No Deposit,,,0,Transient-Party,53.33,0,1
HB-035047,Resort Hotel,0,11,2025,April,15,8,2025-04-08,2,2,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,117.0,0,1
HB-047232,City Hotel,0,37,2024,February,7,13,2024-02-13,0,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient-Party,69.53,0,0
HB-018373,Resort Hotel,0,4,2025,January,5,30,2025-01-30,1,0,1,0.0,0,BB,GBR,Complementary,TA/TO,1,0,2,F,F,0,No Deposit,40.0,,0,Transient,0.0,0,1
HB-078165,City Hotel,0,224,2023,October,40,2,2023-10-02,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,65.0,0,0
HB-036584,Resort Hotel,0,219,2025,May,20,18,2025-05-18,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,143.0,,0,Transient,80.85,0,0
HB-114131,City Hotel,0,179,2025,June,24,10,2025-06-10,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,42.0,,0,Transient,99.0,0,2
HB-078718,City Hotel,0,5,2025,July,31,31,2025-07-31,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,29,A,A,0,No Deposit,,40.0,0,Transient,67.0,1,1
HB-049276,City Hotel,0,112,2024,April,15,9,2024-04-09,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.3,0,0
HB-078308,City Hotel,0,1,2024,January,1,7,2024-01-07,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,3,A,A,0,No Deposit,,40.0,0,Transient-Party,65.0,0,0
HB-022829,Resort Hotel,0,72,2024,April,14,1,2024-04-01,2,5,4,1.0,0,BB,GBR,Direct,Direct,0,0,0,H,H,0,No Deposit,250.0,,0,Transient,134.06,0,0
HB-115625,City Hotel,0,307,2025,July,28,7,2025-07-07,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,B,A,1,No Deposit,9.0,,0,Transient,93.64,0,0
HB-052534,City Hotel,1,26,2024,June,23,8,2024-06-08,0,1,2,0.0,0,BB,PRT,Offline TA/TO,Corporate,0,0,0,A,A,0,No Deposit,191.0,,0,Transient-Party,120.0,0,0
HB-097659,City Hotel,0,31,2024,September,38,16,2024-09-16,1,2,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,75.0,0,0
HB-083851,City Hotel,0,4,2024,February,7,13,2024-02-13,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,81.0,0,0
HB-034976,Resort Hotel,0,152,2025,April,14,5,2025-04-05,1,4,1,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,C,4,No Deposit,,223.0,0,Transient-Party,48.0,0,0
HB-050503,City Hotel,1,437,2024,May,18,2,2024-05-02,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-022358,Resort Hotel,0,17,2024,March,12,22,2024-03-22,0,2,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,58.0,0,1
HB-070781,City Hotel,1,231,2025,June,25,22,2025-06-22,1,3,2,0.0,0,BB,HRV,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.5,0,2
HB-075835,City Hotel,1,337,2023,September,38,19,2023-09-19,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-093960,City Hotel,0,150,2024,July,30,27,2024-07-27,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.5,0,1
HB-042896,City Hotel,0,168,2023,September,37,11,2023-09-11,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,50.0,0,0
HB-094690,City Hotel,0,152,2024,August,32,5,2024-08-05,1,2,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,110.65,0,2
HB-112010,City Hotel,0,101,2025,May,20,17,2025-05-17,0,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.5,0,0
HB-027194,Resort Hotel,0,103,2024,August,34,19,2024-08-19,1,2,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,189.42,0,1
HB-110919,City Hotel,0,132,2025,May,18,1,2025-05-01,1,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,2
HB-035118,Resort Hotel,0,166,2025,April,15,10,2025-04-10,1,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,38.55,0,1
HB-077287,City Hotel,1,4,2023,September,38,20,2023-09-20,2,3,2,0.0,0,SC,PRT,Online TA,TA/TO,1,1,0,A,A,0,No Deposit,8.0,,0,Transient,133.0,0,1
HB-005749,Resort Hotel,1,236,2024,May,19,12,2024-05-12,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,315.0,,0,Transient-Party,48.0,0,0
HB-069852,City Hotel,1,15,2025,June,23,8,2025-06-08,0,1,1,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,119.2,0,0
HB-066972,City Hotel,1,1,2025,April,17,27,2025-04-27,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,166.5,0,2
HB-062510,City Hotel,1,38,2025,January,3,14,2025-01-14,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,Non Refund,,67.0,0,Transient,75.0,0,0
HB-029439,Resort Hotel,0,10,2024,October,43,26,2024-10-26,0,3,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,111.0,1,1
HB-087420,City Hotel,0,72,2024,April,15,13,2024-04-13,2,5,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,86.82,0,0
HB-046097,City Hotel,1,106,2023,December,49,9,2023-12-09,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,57,Transient,70.0,0,0
HB-027924,Resort Hotel,0,8,2024,September,37,11,2024-09-11,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,441.0,,0,Transient,93.6,0,0
HB-045412,City Hotel,0,72,2023,October,43,28,2023-10-28,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,58,Transient-Party,85.67,0,0
HB-097392,City Hotel,0,0,2024,September,37,15,2024-09-15,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,179.0,0,2
HB-000075,Resort Hotel,1,51,2023,July,27,3,2023-07-03,0,2,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,110.3,0,0
HB-095454,City Hotel,0,320,2024,August,33,18,2024-08-18,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-004643,Resort Hotel,1,106,2024,March,12,24,2024-03-24,1,3,2,0.0,0,FB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,68.0,,0,Transient,84.0,0,0
HB-109308,City Hotel,0,143,2025,April,14,6,2025-04-06,0,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient-Party,119.0,0,1
HB-003271,Resort Hotel,1,91,2023,November,48,30,2023-11-30,3,7,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,66.0,0,1
HB-114731,City Hotel,0,263,2025,June,26,23,2025-06-23,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,2,No Deposit,37.0,,0,Transient-Party,105.0,0,1
HB-113748,City Hotel,0,175,2025,June,24,9,2025-06-09,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,130.0,0,0
HB-118046,City Hotel,0,54,2025,August,32,10,2025-08-10,1,3,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,D,D,2,No Deposit,14.0,,0,Transient,157.5,0,0
HB-029284,Resort Hotel,0,4,2024,October,43,24,2024-10-24,1,0,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,5.0,,0,Transient,46.8,0,0
HB-008015,Resort Hotel,1,211,2024,September,36,7,2024-09-07,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,D,D,0,Non Refund,1.0,,0,Transient,89.0,0,0
HB-039104,Resort Hotel,0,96,2025,July,30,25,2025-07-25,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,135.0,0,1
HB-064624,City Hotel,1,138,2025,March,11,13,2025-03-13,1,4,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,75.68,0,1
HB-118571,City Hotel,0,113,2025,August,32,8,2025-08-08,4,10,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.0,0,1
HB-013312,Resort Hotel,1,225,2025,August,32,8,2025-08-08,0,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,206.0,0,2
HB-099948,City Hotel,0,47,2024,October,42,16,2024-10-16,2,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,97.82,0,1
HB-109804,City Hotel,0,52,2025,April,15,13,2025-04-13,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,148.5,1,0
HB-011395,Resort Hotel,1,214,2025,May,19,5,2025-05-05,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,54.0,0,0
HB-088605,City Hotel,0,102,2024,May,18,5,2024-05-05,1,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,132.6,0,1
HB-096582,City Hotel,0,143,2024,August,35,31,2024-08-31,1,4,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,101.31,0,1
HB-041980,City Hotel,0,3,2023,August,35,29,2023-08-29,0,1,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,1,No Deposit,,,0,Transient,90.0,0,2
HB-034899,Resort Hotel,0,150,2025,February,9,26,2025-02-26,12,30,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,39.41,0,2
HB-057066,City Hotel,1,5,2024,September,38,17,2024-09-17,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,166.5,0,1
HB-042785,City Hotel,0,12,2023,September,36,10,2023-09-10,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Group,105.0,0,0
HB-101683,City Hotel,0,43,2024,November,46,12,2024-11-12,2,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.48,0,2
HB-069913,City Hotel,1,183,2025,June,23,8,2025-06-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,86.0,,0,Transient,120.0,0,0
HB-059860,City Hotel,1,304,2024,November,44,3,2024-11-03,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,89.0,0,0
HB-074675,City Hotel,1,359,2023,October,41,11,2023-10-11,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-098248,City Hotel,0,4,2024,September,39,25,2024-09-25,2,0,1,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,118.58,0,1
HB-099326,City Hotel,0,25,2024,October,41,10,2024-10-10,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,23.0,,0,Transient,95.0,0,1
HB-047824,City Hotel,1,21,2024,March,10,4,2024-03-04,0,1,2,0.0,0,HB,SVN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,129.0,0,0
HB-022556,Resort Hotel,0,39,2024,March,13,25,2024-03-25,1,2,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,110.33,1,1
HB-095753,City Hotel,0,172,2024,August,34,21,2024-08-21,2,1,3,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,6.0,,0,Transient-Party,107.1,0,1
HB-082136,City Hotel,1,99,2024,February,8,19,2024-02-19,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,1,0,A,A,0,No Deposit,,67.0,0,Transient-Party,80.0,0,0
HB-016762,Resort Hotel,0,5,2023,September,36,7,2023-09-07,1,3,2,1.0,0,HB,PRT,Direct,Direct,0,0,0,A,C,1,No Deposit,250.0,,0,Transient,167.75,0,1
HB-098097,City Hotel,0,236,2024,September,38,22,2024-09-22,0,3,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,159.3,0,0
HB-092466,City Hotel,0,19,2024,July,27,3,2024-07-03,2,2,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,187.0,0,2
HB-041379,City Hotel,0,40,2023,August,33,15,2023-08-15,2,2,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,60.0,0,0
HB-069921,City Hotel,1,169,2025,June,23,8,2025-06-08,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,170.0,0,0
HB-087293,City Hotel,0,85,2024,April,15,11,2024-04-11,1,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,79.0,,0,Transient,72.76,0,0
HB-045897,City Hotel,0,84,2023,November,48,27,2023-11-27,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,56.0,0,0
HB-013345,Resort Hotel,1,311,2025,August,33,11,2025-08-11,2,2,1,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,E,E,2,No Deposit,240.0,,0,Transient,201.6,0,1
HB-108475,City Hotel,0,82,2025,March,12,21,2025-03-21,2,5,2,0.0,0,BB,HUN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,68.0,0,0
HB-103401,City Hotel,0,5,2024,December,51,18,2024-12-18,2,2,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,80.0,0,0
HB-006492,Resort Hotel,0,259,2024,June,24,13,2024-06-13,1,3,2,0.0,0,HB,RUS,Online TA,TA/TO,0,0,0,A,A,3,No Deposit,240.0,,0,Transient,99.0,0,2
HB-031099,Resort Hotel,0,6,2024,December,50,13,2024-12-13,0,1,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,41.11,1,1
HB-038398,Resort Hotel,0,0,2025,July,29,15,2025-07-15,0,1,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,230.0,0,0
HB-084271,City Hotel,0,14,2024,February,8,19,2024-02-19,1,2,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,40.67,0,0
HB-010903,Resort Hotel,1,124,2025,April,15,9,2025-04-09,2,5,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,C,1,Non Refund,492.0,,0,Transient,80.0,0,0
HB-064730,City Hotel,1,92,2025,March,11,15,2025-03-15,0,3,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,85.0,0,0
HB-000676,Resort Hotel,0,12,2023,July,30,25,2023-07-25,1,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,240.0,,0,Transient,153.0,0,1
HB-027143,Resort Hotel,0,3,2024,August,33,18,2024-08-18,0,3,2,0.0,1,BB,ESP,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,170.7,1,1
HB-100337,City Hotel,0,5,2024,October,43,25,2024-10-25,0,2,1,0.0,0,BB,ITA,Aviation,Corporate,0,0,0,A,A,0,No Deposit,,153.0,0,Transient,95.0,0,0
HB-059246,City Hotel,0,294,2024,October,43,23,2024-10-23,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,7.0,,0,Transient,76.58,0,1
HB-079737,City Hotel,0,4,2023,November,46,16,2023-11-16,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-022979,Resort Hotel,0,18,2024,April,15,11,2024-04-11,1,0,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,2,No Deposit,,,0,Transient,62.0,1,0
HB-033661,Resort Hotel,0,1,2025,February,9,26,2025-02-26,2,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,67.0,0,2
HB-088706,City Hotel,0,13,2024,May,19,9,2024-05-09,1,1,2,0.0,0,BB,KOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,85.47,0,1
HB-100974,City Hotel,0,57,2024,November,44,1,2024-11-01,0,4,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,1
HB-070177,City Hotel,1,22,2025,June,24,11,2025-06-11,2,2,2,0.0,0,SC,IND,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.0,0,1
HB-029616,Resort Hotel,0,10,2024,October,44,29,2024-10-29,2,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,38.0,0,2
HB-035770,Resort Hotel,0,47,2025,April,18,29,2025-04-29,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,171.0,,0,Transient,67.0,1,0
HB-077940,City Hotel,0,16,2023,September,39,25,2023-09-25,2,3,1,0.0,0,BB,ITA,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,170.0,0,0
HB-119136,City Hotel,0,4,2025,August,35,28,2025-08-28,1,1,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,219.0,0,2
HB-087011,City Hotel,0,2,2024,April,15,11,2024-04-11,1,1,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,104.0,0,1
HB-004849,Resort Hotel,0,171,2024,April,14,4,2024-04-04,1,1,1,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,1,Non Refund,298.0,,0,Transient-Party,54.5,0,0
HB-110146,City Hotel,0,133,2025,April,16,19,2025-04-19,0,4,2,0.0,0,BB,ISL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,390.0,,0,Transient-Party,124.0,0,0
HB-113675,City Hotel,0,7,2025,June,23,8,2025-06-08,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,10.0,,0,Transient,100.0,0,0
HB-027348,Resort Hotel,0,111,2024,August,34,20,2024-08-20,2,5,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,200.96,0,2
HB-008620,Resort Hotel,1,393,2024,October,41,8,2024-10-08,2,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,68.0,,0,Transient,72.0,0,0
HB-082223,City Hotel,1,317,2024,September,37,9,2024-09-09,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,58.0,,56,Transient,90.0,0,0
HB-053707,City Hotel,1,89,2024,June,26,27,2024-06-27,1,5,3,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,143.7,0,0
HB-060265,City Hotel,1,277,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-095330,City Hotel,0,38,2024,August,33,17,2024-08-17,0,1,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,168.3,0,0
HB-043826,City Hotel,0,56,2023,September,39,25,2023-09-25,2,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,2,No Deposit,44.0,,0,Transient-Party,185.0,0,0
HB-034293,Resort Hotel,0,2,2025,March,12,17,2025-03-17,0,2,2,0.0,0,HB,ESP,Direct,Direct,0,0,0,A,A,1,No Deposit,250.0,,0,Transient,102.0,0,0
HB-084519,City Hotel,0,0,2024,February,8,25,2024-02-25,0,3,2,0.0,0,BB,HRV,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,89.0,0,0
HB-093834,City Hotel,0,28,2024,July,30,27,2024-07-27,0,1,2,1.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,9.0,,0,Transient,169.0,0,1
HB-082611,City Hotel,0,50,2023,December,52,31,2023-12-31,0,3,2,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,71.33,0,0
HB-096532,City Hotel,0,66,2024,September,35,1,2024-09-01,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,141.9,0,1
HB-035007,Resort Hotel,0,29,2025,April,14,6,2025-04-06,2,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,107.0,0,1
HB-017069,Resort Hotel,0,160,2023,September,36,10,2023-09-10,4,10,1,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Contract,53.55,0,2
HB-016267,Resort Hotel,0,53,2023,August,33,15,2023-08-15,2,5,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,1,No Deposit,240.0,,0,Transient,235.71,0,0
HB-043327,City Hotel,0,72,2023,September,38,18,2023-09-18,0,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,108.0,0,0
HB-023540,Resort Hotel,0,1,2024,April,17,26,2024-04-26,0,2,2,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,114.0,1,1
HB-111675,City Hotel,0,114,2025,May,19,11,2025-05-11,0,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,1
HB-097462,City Hotel,0,252,2024,September,38,16,2024-09-16,0,1,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,95.4,0,2
HB-056434,City Hotel,1,81,2024,September,36,5,2024-09-05,1,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,86.0,,0,Transient-Party,95.0,0,0
HB-094146,City Hotel,0,73,2024,July,31,29,2024-07-29,1,2,3,1.0,0,BB,FRA,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,173.7,0,0
HB-033934,Resort Hotel,0,0,2025,March,10,7,2025-03-07,0,0,2,0.0,0,BB,PRT,Direct,Direct,1,0,0,A,A,0,No Deposit,,,0,Transient,0.0,0,0
HB-035622,Resort Hotel,0,1,2025,April,18,28,2025-04-28,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,330.0,,0,Transient-Party,50.0,0,1
HB-026189,Resort Hotel,0,169,2024,July,29,21,2024-07-21,0,3,2,0.0,0,BB,BRA,Online TA,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,173.67,1,2
HB-011293,Resort Hotel,1,65,2025,May,18,1,2025-05-01,1,3,2,1.0,0,BB,IRL,Direct,Direct,0,0,0,G,G,0,No Deposit,250.0,,0,Transient,150.0,0,0
HB-008057,Resort Hotel,0,363,2024,September,36,8,2024-09-08,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,241.0,,0,Transient,112.48,1,0
HB-020061,Resort Hotel,0,1,2024,January,2,12,2024-01-12,0,3,1,0.0,0,BB,FRA,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,67.0,1,0
HB-068568,City Hotel,1,105,2025,May,21,19,2025-05-19,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-064756,City Hotel,1,44,2025,March,11,15,2025-03-15,0,4,3,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,23.0,,0,Transient,110.0,0,0
HB-058007,City Hotel,1,40,2024,October,40,5,2024-10-05,0,1,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,125.55,0,0
HB-023860,Resort Hotel,0,1,2024,May,18,3,2024-05-03,0,3,1,0.0,0,BB,ARG,Direct,Direct,0,0,0,F,F,1,No Deposit,,,0,Transient,115.0,0,1
HB-029241,Resort Hotel,0,386,2024,October,42,20,2024-10-20,1,3,3,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,3,No Deposit,,,0,Transient-Party,79.0,0,1
HB-016140,Resort Hotel,0,69,2023,August,32,10,2023-08-10,1,5,2,0.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,196.0,,0,Transient,135.0,0,1
HB-098426,City Hotel,0,116,2024,September,39,25,2024-09-25,2,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,125.1,0,2
HB-012865,Resort Hotel,1,147,2025,July,30,21,2025-07-21,1,2,2,0.0,0,BB,SYC,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,175.0,0,1
HB-049916,City Hotel,0,270,2024,April,16,20,2024-04-20,0,4,2,0.0,0,BB,ISL,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,21.0,,187,Transient-Party,80.0,0,0
HB-021808,Resort Hotel,0,0,2024,March,11,12,2024-03-12,0,0,2,0.0,0,HB,GBR,Groups,TA/TO,1,0,0,A,D,0,No Deposit,115.0,,0,Transient-Party,0.0,0,0
HB-001180,Resort Hotel,1,98,2023,August,33,17,2023-08-17,1,3,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,149.4,0,0
HB-104258,City Hotel,0,3,2025,January,2,6,2025-01-06,1,2,2,0.0,0,BB,AUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,87.69,0,1
HB-117957,City Hotel,0,48,2025,August,32,9,2025-08-09,0,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,2
HB-105421,City Hotel,0,0,2025,February,6,7,2025-02-07,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,0
HB-078600,City Hotel,1,14,2023,October,43,26,2023-10-26,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Contract,126.0,0,1
HB-108213,City Hotel,0,69,2025,March,12,20,2025-03-20,1,3,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,138.55,0,0
HB-066272,City Hotel,1,88,2025,April,16,16,2025-04-16,2,0,2,1.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,0
HB-031731,Resort Hotel,0,105,2025,January,1,2,2025-01-02,1,2,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,29.0,0,0
HB-081795,City Hotel,1,117,2024,February,9,29,2024-02-29,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,44,Transient,75.0,0,0
HB-060434,City Hotel,1,300,2024,November,46,11,2024-11-11,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,65.0,0,0
HB-115979,City Hotel,0,48,2025,July,28,11,2025-07-11,0,2,1,1.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,1
HB-086185,City Hotel,0,59,2024,March,13,25,2024-03-25,2,2,2,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,11.0,,0,Transient,104.65,0,0
HB-014731,Resort Hotel,1,259,2023,September,37,17,2023-09-17,0,3,2,0.0,0,BB,GBR,Groups,Corporate,0,1,0,A,A,0,Non Refund,,223.0,0,Transient,40.05,0,0
HB-019060,Resort Hotel,0,11,2023,December,49,5,2023-12-05,2,1,2,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,350.0,,0,Transient-Party,68.0,0,0
HB-093000,City Hotel,0,133,2024,July,28,12,2024-07-12,0,3,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient-Party,137.7,0,2
HB-048239,City Hotel,1,0,2024,March,12,19,2024-03-19,1,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,141.0,0,1
HB-089071,City Hotel,0,116,2024,May,20,14,2024-05-14,2,1,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,112.5,0,0
HB-100921,City Hotel,0,174,2024,November,44,1,2024-11-01,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.9,0,3
HB-003588,Resort Hotel,0,51,2023,December,51,24,2023-12-24,1,3,2,0.0,0,BB,LTU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,89.25,0,0
HB-052263,City Hotel,1,62,2024,June,22,2,2024-06-02,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,235.0,,32,Transient,140.0,0,0
HB-023132,Resort Hotel,0,20,2024,April,15,12,2024-04-12,0,4,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient,43.4,0,1
HB-078975,City Hotel,1,16,2023,October,43,24,2023-10-24,0,1,2,2.0,0,BB,PRT,Online TA,TA/TO,0,1,0,F,F,0,No Deposit,9.0,,0,Transient,215.0,0,1
HB-070793,City Hotel,1,160,2025,June,26,23,2025-06-23,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,127.8,0,0
HB-057715,City Hotel,1,219,2024,September,40,30,2024-09-30,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,120.0,0,0
HB-038517,Resort Hotel,0,131,2025,July,29,17,2025-07-17,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,195.0,0,1
HB-067692,City Hotel,1,162,2025,May,19,6,2025-05-06,2,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,80.0,0,0
HB-020782,Resort Hotel,0,72,2024,February,6,6,2024-02-06,2,1,1,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,D,D,1,No Deposit,,,0,Transient-Party,56.67,0,0
HB-015676,Resort Hotel,0,50,2023,July,29,23,2023-07-23,2,6,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,149.25,1,0
HB-088895,City Hotel,0,69,2024,May,19,9,2024-05-09,1,4,1,1.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,135.15,0,2
HB-069882,City Hotel,1,183,2025,June,23,8,2025-06-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,86.0,,0,Transient,120.0,0,0
HB-029488,Resort Hotel,0,39,2024,October,44,29,2024-10-29,0,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,I,0,No Deposit,6.0,,0,Transient,0.0,0,0
HB-091981,City Hotel,0,8,2024,June,26,26,2024-06-26,2,1,2,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,85.0,,0,Transient,107.0,0,0
HB-063629,City Hotel,1,587,2025,February,7,16,2025-02-16,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-015941,Resort Hotel,0,4,2023,August,31,4,2023-08-04,0,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,211.0,0,3
HB-021420,Resort Hotel,0,6,2024,February,8,21,2024-02-21,3,5,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,156.0,,0,Transient,48.75,1,0
HB-032672,Resort Hotel,0,24,2025,January,5,28,2025-01-28,2,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,171.0,,0,Transient,42.0,0,0
HB-091909,City Hotel,0,53,2024,June,26,24,2024-06-24,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,65.0,0,1
HB-045355,City Hotel,1,61,2023,October,43,26,2023-10-26,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,72.24,0,1
HB-009249,Resort Hotel,1,211,2024,November,45,5,2024-11-05,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,11.0,,0,Transient,30.0,0,0
HB-079002,City Hotel,0,221,2023,October,42,17,2023-10-17,2,1,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,E,1,No Deposit,3.0,,0,Transient-Party,60.0,0,0
HB-012866,Resort Hotel,1,347,2025,July,30,21,2025-07-21,2,4,2,0.0,1,Undefined,PRT,Direct,Direct,0,0,0,G,G,1,No Deposit,250.0,,0,Transient,237.34,0,3
HB-051426,City Hotel,1,322,2024,May,20,19,2024-05-19,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,120,Transient,80.0,0,0
HB-090564,City Hotel,0,1,2024,June,23,7,2024-06-07,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,92.65,0,0
HB-014115,Resort Hotel,0,7,2023,November,45,10,2023-11-10,0,1,1,0.0,0,BB,,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,92.0,0,Transient,35.0,1,0
HB-035603,Resort Hotel,0,31,2025,April,17,23,2025-04-23,2,4,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,93.0,0,0
HB-026533,Resort Hotel,0,145,2024,July,30,25,2024-07-25,3,6,2,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,128.0,,0,Transient,121.7,0,0
HB-050125,City Hotel,1,31,2024,April,17,24,2024-04-24,1,0,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.5,0,0
HB-076624,City Hotel,0,0,2023,September,37,17,2023-09-17,0,1,1,0.0,0,BB,PRT,Complementary,TA/TO,1,0,2,A,A,2,No Deposit,,46.0,0,Transient,0.0,0,1
HB-085123,City Hotel,0,0,2024,March,9,2,2024-03-02,2,6,1,0.0,0,BB,GNB,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,75.65,0,0
HB-092440,City Hotel,0,1,2024,July,27,6,2024-07-06,0,1,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,112.42,0,1
HB-079582,City Hotel,0,34,2023,October,43,25,2023-10-25,2,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-077503,City Hotel,0,263,2023,September,38,21,2023-09-21,1,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,21.0,,0,Transient-Party,67.0,0,0
HB-051236,City Hotel,1,451,2024,May,20,16,2024-05-16,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-103416,City Hotel,0,4,2024,December,51,19,2024-12-19,1,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,81.6,0,2
HB-114078,City Hotel,0,157,2025,June,25,16,2025-06-16,0,1,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,99.0,0,0
HB-003804,Resort Hotel,0,169,2024,January,2,8,2024-01-08,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,50.4,0,1
HB-068773,City Hotel,1,113,2025,May,21,20,2025-05-20,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,34.0,,0,Transient,190.0,0,0
HB-104399,City Hotel,0,87,2025,January,2,12,2025-01-12,0,1,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.2,1,1
HB-109195,City Hotel,0,63,2025,April,14,4,2025-04-04,0,4,2,3.0,0,BB,FRA,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,7.0,,0,Transient,223.32,0,1
HB-005936,Resort Hotel,0,201,2024,May,20,16,2024-05-16,3,8,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient-Party,46.98,0,2
HB-111706,City Hotel,0,36,2025,May,20,12,2025-05-12,0,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,180.0,0,2
HB-082262,City Hotel,0,44,2024,January,1,2,2024-01-02,2,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,98.0,0,1
HB-018090,Resort Hotel,0,4,2023,November,44,2,2023-11-02,1,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient,25.0,0,0
HB-040203,City Hotel,1,109,2023,July,28,16,2023-07-16,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,76.5,0,0
HB-006971,Resort Hotel,0,311,2024,July,28,14,2024-07-14,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,314.0,,0,Transient,127.71,0,0
HB-064709,City Hotel,1,92,2025,March,11,15,2025-03-15,0,3,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,85.0,0,0
HB-067780,City Hotel,1,197,2025,May,19,7,2025-05-07,2,1,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,2
HB-026549,Resort Hotel,0,1,2024,August,31,3,2024-08-03,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,,0,Transient,151.0,0,1
HB-062753,City Hotel,1,305,2025,January,4,21,2025-01-21,2,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,77.35,0,1
HB-103161,City Hotel,0,0,2024,December,50,13,2024-12-13,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,87.0,0,0
HB-116547,City Hotel,0,105,2025,July,29,17,2025-07-17,1,4,2,2.0,0,BB,NOR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,8.0,,0,Transient,230.0,0,0
HB-044298,City Hotel,0,86,2023,October,40,3,2023-10-03,2,1,1,0.0,0,HB,ITA,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,63.0,0,0
HB-026952,Resort Hotel,0,110,2024,August,32,8,2024-08-08,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,199.29,0,1
HB-100990,City Hotel,0,83,2024,October,44,31,2024-10-31,1,4,2,1.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,106.38,0,1
HB-106301,City Hotel,0,48,2025,February,8,22,2025-02-22,0,2,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,65.0,0,1
HB-010441,Resort Hotel,1,218,2025,March,10,7,2025-03-07,2,5,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,87.0,0,0
HB-026321,Resort Hotel,0,54,2024,July,29,18,2024-07-18,3,7,3,0.0,0,HB,IRL,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,239.0,0,2
HB-008520,Resort Hotel,1,86,2024,October,40,3,2024-10-03,1,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,109.0,0,1
HB-117897,City Hotel,0,479,2025,August,32,9,2025-08-09,0,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,1
HB-096269,City Hotel,0,2,2024,August,35,28,2024-08-28,2,1,2,0.0,0,SC,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-116976,City Hotel,0,8,2025,July,30,27,2025-07-27,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-092878,City Hotel,0,36,2024,July,28,11,2024-07-11,1,1,1,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.9,0,0
HB-013229,Resort Hotel,1,238,2025,August,32,5,2025-08-05,2,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,168.0,0,1
HB-091156,City Hotel,0,256,2024,June,24,15,2024-06-15,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-000746,Resort Hotel,0,35,2023,July,30,27,2023-07-27,1,3,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,196.0,,0,Transient,149.0,0,0
HB-052897,City Hotel,1,71,2024,June,24,14,2024-06-14,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,120.0,0,0
HB-056455,City Hotel,1,230,2024,September,36,6,2024-09-06,0,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,44.0,,0,Transient-Party,137.0,0,0
HB-069189,City Hotel,1,131,2025,May,22,26,2025-05-26,2,2,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,108.0,0,1
HB-078613,City Hotel,0,221,2023,October,41,10,2023-10-10,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,65.0,0,0
HB-013722,Resort Hotel,1,20,2025,August,35,27,2025-08-27,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,11.0,,0,Transient,182.0,0,1
HB-007793,Resort Hotel,1,185,2024,August,35,26,2024-08-26,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient,166.14,0,1
HB-063611,City Hotel,1,65,2025,February,7,15,2025-02-15,2,8,2,1.0,0,BB,RUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,3
HB-013141,Resort Hotel,1,358,2025,August,31,1,2025-08-01,4,10,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,190.96,0,2
HB-117744,City Hotel,0,158,2025,August,32,5,2025-08-05,2,2,2,1.0,0,BB,DNK,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,148.5,0,2
HB-050161,City Hotel,1,68,2024,April,17,24,2024-04-24,2,2,1,1.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,79.56,0,0
HB-027898,Resort Hotel,0,0,2024,September,37,13,2024-09-13,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,127.0,,0,Transient-Party,136.0,0,0
HB-022484,Resort Hotel,0,94,2025,April,16,14,2025-04-14,0,2,2,0.0,0,BB,PRT,Direct,Direct,1,0,2,E,G,0,No Deposit,250.0,,0,Transient,103.5,0,0
HB-001341,Resort Hotel,1,54,2023,August,34,24,2023-08-24,2,5,3,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,2,No Deposit,,,0,Transient,196.0,0,1
HB-043255,City Hotel,0,56,2023,September,37,17,2023-09-17,0,2,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,20.0,,0,Transient-Party,82.0,0,0
HB-019293,Resort Hotel,0,11,2023,December,49,9,2023-12-09,0,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,46.4,0,1
HB-063228,City Hotel,1,30,2025,February,5,2,2025-02-02,2,4,2,0.0,0,BB,ISL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.1,0,2
HB-073340,City Hotel,1,162,2025,August,34,19,2025-08-19,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,140.0,0,0
HB-006491,Resort Hotel,1,150,2024,June,24,13,2024-06-13,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,121.0,0,1
HB-083385,City Hotel,0,21,2024,January,5,29,2024-01-29,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.3,0,1
HB-004290,Resort Hotel,1,219,2024,March,9,2,2024-03-02,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,310.0,,0,Transient,52.0,0,0
HB-096715,City Hotel,0,1,2024,September,36,6,2024-09-06,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,118.26,0,2
HB-048910,City Hotel,0,97,2024,April,14,2,2024-04-02,0,1,2,0.0,0,SC,SWE,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,76.5,1,1
HB-117116,City Hotel,0,5,2025,July,31,29,2025-07-29,0,1,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,161.0,0,2
HB-073092,City Hotel,1,83,2025,August,33,14,2025-08-14,1,2,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,170.0,0,1
HB-068784,City Hotel,1,113,2025,May,21,20,2025-05-20,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,34.0,,0,Transient,190.0,0,0
HB-062526,City Hotel,1,38,2025,January,3,14,2025-01-14,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,Non Refund,,67.0,0,Transient,75.0,0,0
HB-092338,City Hotel,0,128,2024,July,27,2,2024-07-02,2,1,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.3,0,1
HB-059221,City Hotel,1,229,2024,October,43,22,2024-10-22,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,Non Refund,10.0,,0,Transient,89.25,0,0
HB-035895,Resort Hotel,0,96,2025,April,18,29,2025-04-29,2,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient,43.2,0,0
HB-076826,City Hotel,0,1,2023,August,34,24,2023-08-24,1,0,2,1.0,0,BB,PRT,Online TA,TA/TO,1,0,2,D,D,2,No Deposit,9.0,9.0,0,Transient,123.5,0,3
HB-058620,City Hotel,1,37,2024,October,41,13,2024-10-13,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,95.0,0,0
HB-033553,Resort Hotel,0,25,2025,February,8,22,2025-02-22,0,4,1,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,436.0,,0,Transient,30.0,0,0
HB-062067,City Hotel,1,187,2025,January,1,1,2025-01-01,1,0,2,0.0,0,HB,RUS,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,137.7,0,3
HB-090667,City Hotel,0,118,2024,June,23,6,2024-06-06,1,2,1,0.0,0,BB,NLD,Offline TA/TO,Corporate,0,0,0,A,A,0,No Deposit,191.0,,0,Transient-Party,110.0,0,0
HB-096716,City Hotel,0,1,2024,September,36,5,2024-09-05,1,1,1,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,149.0,0,1
HB-014661,Resort Hotel,0,185,2023,July,27,6,2023-07-06,2,5,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,110.0,0,0
HB-009264,Resort Hotel,1,44,2024,November,45,5,2024-11-05,2,5,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,73.8,0,0
HB-055225,City Hotel,1,159,2024,August,32,8,2024-08-08,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.3,0,0
HB-040869,City Hotel,1,124,2023,August,32,8,2023-08-08,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-077085,City Hotel,0,45,2023,September,35,3,2023-09-03,0,2,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.5,0,1
HB-026245,Resort Hotel,0,114,2024,July,30,25,2024-07-25,1,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,1,No Deposit,250.0,,0,Transient,10.0,0,0
HB-023407,Resort Hotel,0,42,2024,April,17,23,2024-04-23,1,1,3,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,3,No Deposit,250.0,,0,Transient,99.0,1,0
HB-020931,Resort Hotel,0,24,2024,February,7,12,2024-02-12,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,59.0,1,0
HB-066221,City Hotel,1,87,2025,April,16,15,2025-04-15,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,95.0,0,0
HB-048460,City Hotel,1,50,2024,March,12,24,2024-03-24,0,1,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,115.2,0,2
HB-054210,City Hotel,1,167,2024,July,28,8,2024-07-08,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,105.83,0,1
HB-095352,City Hotel,0,2,2024,August,33,16,2024-08-16,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,177.5,0,1
HB-029907,Resort Hotel,0,47,2024,November,45,5,2024-11-05,2,2,2,0.0,2,HB,GBR,Online TA,TA/TO,0,0,0,A,C,1,No Deposit,240.0,,0,Transient,74.8,0,5
HB-100638,City Hotel,0,35,2024,October,44,28,2024-10-28,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,E,0,No Deposit,,,0,Transient,104.13,0,0
HB-001562,Resort Hotel,1,105,2023,September,36,4,2023-09-04,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,153.0,0,0
HB-058330,City Hotel,1,181,2024,October,41,11,2024-10-11,0,1,1,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,78.48,0,0
HB-073918,City Hotel,1,265,2023,July,27,9,2023-07-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Contract,62.0,0,0
HB-080335,City Hotel,1,33,2023,December,49,9,2023-12-09,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,44.0,,0,Transient,110.0,0,0
HB-089517,City Hotel,0,14,2024,May,20,18,2024-05-18,0,4,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,B,0,No Deposit,12.0,,0,Transient-Party,0.0,0,0
HB-018515,Resort Hotel,0,4,2023,November,47,20,2023-11-20,0,2,2,0.0,0,HB,ESP,Direct,Direct,0,0,0,F,F,1,No Deposit,250.0,,0,Transient,98.0,0,1
HB-093856,City Hotel,0,3,2024,July,30,25,2024-07-25,1,2,2,2.0,0,BB,ESP,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,205.33,0,2
HB-004245,Resort Hotel,0,123,2024,February,9,27,2024-02-27,1,1,2,0.0,0,FB,ESP,Groups,Direct,0,0,0,A,A,0,No Deposit,38.0,,0,Transient-Party,64.0,0,0
HB-069170,City Hotel,1,269,2025,May,22,26,2025-05-26,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,135.0,0,3
HB-015655,Resort Hotel,1,468,2024,May,19,12,2024-05-12,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,249.0,,0,Transient-Party,67.0,0,0
HB-115025,City Hotel,0,112,2025,June,26,27,2025-06-27,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,135.0,0,0
HB-053450,City Hotel,1,0,2024,June,25,20,2024-06-20,1,3,1,0.0,0,BB,PRT,Aviation,Corporate,0,0,0,A,A,0,No Deposit,,153.0,0,Transient,95.0,0,0
HB-044131,City Hotel,1,30,2023,September,39,30,2023-09-30,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,121.0,0,0
HB-071637,City Hotel,1,226,2025,July,28,9,2025-07-09,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-087287,City Hotel,0,122,2024,April,16,15,2024-04-15,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,151.0,,56,Transient-Party,85.0,0,0
HB-076267,City Hotel,1,147,2023,July,29,21,2023-07-21,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient,75.0,0,0
HB-110266,City Hotel,0,88,2025,April,17,21,2025-04-21,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,162.0,0,3
HB-010817,Resort Hotel,1,175,2025,April,14,6,2025-04-06,0,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,60.0,0,0
HB-066993,City Hotel,1,170,2025,April,17,27,2025-04-27,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.5,0,0
HB-051130,City Hotel,0,297,2024,May,20,14,2024-05-14,1,1,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,236,Transient-Party,65.0,0,0
HB-084400,City Hotel,0,15,2024,February,8,23,2024-02-23,0,2,2,0.0,0,BB,CHE,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,91.0,0,0
HB-050873,City Hotel,1,27,2024,May,19,10,2024-05-10,0,3,2,0.0,0,BB,TJK,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,141.0,0,0
HB-046328,City Hotel,1,140,2023,December,52,29,2023-12-29,0,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,70.0,0,0
HB-014771,Resort Hotel,1,259,2023,September,37,17,2023-09-17,0,3,1,0.0,0,BB,GBR,Groups,Corporate,0,1,0,A,A,0,Non Refund,,223.0,0,Transient,33.3,0,0
HB-006588,Resort Hotel,1,5,2024,June,25,19,2024-06-19,2,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,122.33,0,1
HB-012621,Resort Hotel,1,264,2025,July,28,8,2025-07-08,2,5,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,144.0,0,2
HB-093678,City Hotel,0,59,2024,July,30,23,2024-07-23,1,1,1,0.0,0,BB,JPN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.9,0,1
HB-027714,Resort Hotel,0,211,2024,September,35,1,2024-09-01,2,5,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient,129.0,0,1
HB-054502,City Hotel,1,52,2024,July,29,18,2024-07-18,1,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.5,0,0
HB-073753,City Hotel,1,265,2023,July,27,9,2023-07-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-041025,City Hotel,0,1,2023,August,32,11,2023-08-11,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,95.0,0,2
HB-038072,Resort Hotel,0,241,2025,July,27,2,2025-07-02,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Contract,97.4,0,0
HB-107339,City Hotel,0,46,2025,March,10,7,2025-03-07,0,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,7.0,,0,Transient,70.69,0,1
HB-093950,City Hotel,0,51,2024,July,30,26,2024-07-26,0,3,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.9,0,1
HB-035817,Resort Hotel,0,3,2025,April,18,28,2025-04-28,2,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient,98.25,1,1
HB-007717,Resort Hotel,1,77,2024,August,34,22,2024-08-22,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,240.0,,0,Transient,202.0,0,0
HB-046883,City Hotel,1,15,2024,January,4,23,2024-01-23,1,1,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,0
HB-109861,City Hotel,0,177,2025,April,16,15,2025-04-15,2,1,2,0.0,0,HB,CN,Groups,TA/TO,0,0,0,A,A,1,No Deposit,2.0,,0,Transient-Party,105.33,0,1
HB-106360,City Hotel,0,31,2025,February,8,20,2025-02-20,1,3,1,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,44.77,0,1
HB-013185,Resort Hotel,1,304,2025,August,32,4,2025-08-04,0,2,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,167.18,0,2
HB-011430,Resort Hotel,1,123,2025,May,19,7,2025-05-07,2,5,2,0.0,0,BB,CHE,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,90.0,0,1
HB-113710,City Hotel,0,101,2025,June,23,7,2025-06-07,0,4,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,148.5,0,0
HB-109909,City Hotel,0,67,2025,April,16,17,2025-04-17,1,1,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,180.0,1,1
HB-023774,Resort Hotel,0,5,2024,May,18,1,2024-05-01,2,0,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,105.0,0,1
HB-102761,City Hotel,0,2,2024,December,49,3,2024-12-03,2,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.0,0,1
HB-091737,City Hotel,0,265,2024,June,26,24,2024-06-24,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-025343,Resort Hotel,0,160,2024,June,24,16,2024-06-16,2,5,2,1.0,1,BB,GBR,Direct,Direct,0,0,0,G,G,0,No Deposit,250.0,,0,Transient,142.0,1,1
HB-047040,City Hotel,1,6,2024,February,6,5,2024-02-05,0,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,106.0,0,0
HB-112644,City Hotel,0,112,2025,May,22,26,2025-05-26,0,1,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-040213,City Hotel,0,18,2023,July,29,18,2023-07-18,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,75.0,0,0
HB-084213,City Hotel,0,15,2024,February,8,19,2024-02-19,0,2,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.0,0,1
HB-011762,Resort Hotel,1,338,2025,May,22,28,2025-05-28,2,5,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,118.67,0,0
HB-071522,City Hotel,1,178,2025,July,28,7,2025-07-07,0,2,2,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,143.1,0,0
HB-111056,City Hotel,0,117,2025,May,18,1,2025-05-01,1,4,2,0.0,0,SC,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-041524,City Hotel,0,5,2023,August,33,17,2023-08-17,1,5,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,B,B,0,No Deposit,14.0,,0,Transient,75.0,0,1
HB-010221,Resort Hotel,1,164,2025,February,8,20,2025-02-20,1,5,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient,37.0,0,0
HB-015261,Resort Hotel,0,0,2025,May,22,29,2025-05-29,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,154.0,0,Transient,45.0,0,0
HB-103381,City Hotel,0,152,2024,December,51,18,2024-12-18,2,2,2,0.0,0,SC,ISR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,2
HB-108497,City Hotel,0,206,2025,March,13,26,2025-03-26,2,1,2,0.0,0,BB,CN,Groups,TA/TO,0,0,0,A,A,1,No Deposit,296.0,,0,Transient-Party,72.0,0,0
HB-046973,City Hotel,0,47,2024,January,5,30,2024-01-30,2,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,55.24,0,0
HB-079395,City Hotel,0,11,2023,October,43,23,2023-10-23,2,2,2,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,26.0,,0,Transient-Party,88.5,0,0
HB-098272,City Hotel,0,18,2024,November,45,8,2024-11-08,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,1,No Deposit,,40.0,0,Transient,75.0,0,3
HB-077255,City Hotel,1,6,2023,September,38,20,2023-09-20,2,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,1,0,A,A,0,Non Refund,78.0,,0,Transient,90.0,0,0
HB-068084,City Hotel,1,97,2025,May,20,12,2025-05-12,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,147.0,0,0
HB-001613,Resort Hotel,0,74,2023,September,36,6,2023-09-06,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,241.0,,0,Transient,71.69,0,1
HB-105290,City Hotel,0,83,2025,January,5,30,2025-01-30,1,4,2,1.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,154.35,0,2
HB-093172,City Hotel,0,83,2024,July,28,14,2024-07-14,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.3,0,2
HB-041149,City Hotel,0,150,2023,August,32,13,2023-08-13,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,2
HB-047303,City Hotel,0,0,2024,February,7,16,2024-02-16,0,1,3,0.0,0,BB,FRA,Direct,TA/TO,0,0,0,D,D,1,No Deposit,,,0,Transient,111.0,0,0
HB-048319,City Hotel,0,90,2024,March,12,20,2024-03-20,2,3,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,51.71,0,1
HB-031167,Resort Hotel,0,59,2024,December,50,15,2024-12-15,0,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,30.6,0,0
HB-085226,City Hotel,0,0,2024,March,10,9,2024-03-09,0,2,1,0.0,0,SC,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient-Party,97.0,0,0
HB-100493,City Hotel,0,0,2024,October,44,29,2024-10-29,2,1,1,0.0,0,BB,CHN,Online TA,TA/TO,1,0,0,A,A,2,No Deposit,7.0,,0,Transient,70.03,0,1
HB-045515,City Hotel,1,100,2023,October,44,31,2023-10-31,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-014484,Resort Hotel,0,5,2024,April,17,27,2024-04-27,0,1,1,0.0,0,BB,,Corporate,Corporate,0,0,5,A,D,0,No Deposit,,269.0,0,Transient,45.0,0,0
HB-066791,City Hotel,1,96,2025,April,17,26,2025-04-26,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,130.0,0,0
HB-035623,Resort Hotel,0,36,2025,April,17,27,2025-04-27,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,G,F,1,No Deposit,240.0,,0,Transient,172.0,1,0
HB-039966,Resort Hotel,0,202,2025,August,35,27,2025-08-27,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,118.75,0,1
HB-067856,City Hotel,1,5,2025,May,19,8,2025-05-08,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,39.0,,0,Transient-Party,130.0,0,0
HB-057858,City Hotel,1,159,2024,October,40,1,2024-10-01,2,3,2,1.0,0,HB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,143.55,0,1
HB-116133,City Hotel,0,2,2025,July,29,14,2025-07-14,0,1,2,0.0,0,BB,CN,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,145.0,0,0
HB-010146,Resort Hotel,1,56,2025,February,7,16,2025-02-16,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-020043,Resort Hotel,0,0,2024,January,2,14,2024-01-14,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,40.0,0,0
HB-086451,City Hotel,0,94,2024,March,13,28,2024-03-28,1,5,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,16.0,,0,Transient-Party,110.75,0,1
HB-069210,City Hotel,1,106,2025,May,22,27,2025-05-27,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,89.1,0,0
HB-010151,Resort Hotel,1,30,2025,February,8,17,2025-02-17,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,0
HB-058773,City Hotel,1,258,2024,October,42,16,2024-10-16,1,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,0,Transient,110.0,0,0
HB-014418,Resort Hotel,0,0,2025,April,17,26,2025-04-26,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,2,A,B,0,No Deposit,,43.0,0,Transient,45.0,0,0
HB-034855,Resort Hotel,0,15,2025,March,13,30,2025-03-30,2,6,1,0.0,0,Undefined,PRT,Corporate,Corporate,0,0,0,A,A,1,No Deposit,,523.0,0,Transient-Party,90.0,0,0
HB-066591,City Hotel,1,186,2025,April,17,22,2025-04-22,1,1,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,0
HB-070100,City Hotel,1,219,2025,June,24,9,2025-06-09,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,105.0,0,0
HB-031610,Resort Hotel,0,198,2025,January,1,1,2025-01-01,1,0,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,4,No Deposit,,308.0,0,Transient-Party,0.0,0,0
HB-065406,City Hotel,1,129,2025,April,14,3,2025-04-03,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,0,Transient,100.0,0,0
HB-119301,City Hotel,0,43,2025,August,35,29,2025-08-29,0,4,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,137.25,0,1
HB-012268,Resort Hotel,1,17,2025,June,25,21,2025-06-21,0,3,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,155.0,0,1
HB-026699,Resort Hotel,0,4,2024,August,31,4,2024-08-04,1,3,2,0.0,1,HB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,253.5,0,1
HB-104227,City Hotel,0,118,2025,January,1,2,2025-01-02,1,5,2,2.0,0,BB,RUS,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,147.9,0,1
HB-050114,City Hotel,1,71,2024,April,17,23,2024-04-23,2,3,2,0.0,0,SC,CHL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,84.15,0,0
HB-103482,City Hotel,0,51,2024,December,51,20,2024-12-20,1,5,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.9,0,2
HB-088850,City Hotel,0,25,2024,May,19,10,2024-05-10,0,3,1,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,129.0,0,0
HB-096434,City Hotel,0,31,2024,August,35,28,2024-08-28,2,3,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,168.0,,0,Transient,108.3,0,0
HB-109975,City Hotel,0,120,2025,April,15,13,2025-04-13,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,91.31,0,0
HB-053923,City Hotel,1,76,2024,July,27,2,2024-07-02,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,131.4,0,0
HB-076740,City Hotel,0,160,2023,August,31,5,2023-08-05,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,76.5,0,1
HB-043813,City Hotel,0,56,2023,September,39,25,2023-09-25,2,2,2,0.0,0,BB,GRC,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,44.0,,0,Transient-Party,185.0,0,0
HB-069821,City Hotel,1,134,2025,June,23,7,2025-06-07,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,110.0,0,0
HB-095525,City Hotel,0,221,2024,August,33,18,2024-08-18,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,94.5,1,3
HB-047474,City Hotel,1,5,2024,February,8,23,2024-02-23,2,9,2,0.0,0,HB,SAU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,146.0,0,0
HB-109169,City Hotel,0,73,2025,April,14,3,2025-04-03,1,4,3,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,115.0,0,0
HB-075310,City Hotel,1,304,2023,August,33,17,2023-08-17,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-005885,Resort Hotel,0,213,2024,May,20,16,2024-05-16,1,1,1,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,1,No Deposit,298.0,,0,Transient-Party,54.5,0,0
HB-013646,Resort Hotel,1,71,2025,August,34,24,2025-08-24,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,220.0,0,0
HB-002345,Resort Hotel,0,7,2023,October,41,9,2023-10-09,2,3,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,175.0,,0,Transient,73.68,1,0
HB-036117,Resort Hotel,0,272,2025,May,18,4,2025-05-04,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Contract,78.85,0,0
HB-079263,City Hotel,0,6,2023,October,42,20,2023-10-20,0,3,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,120.0,0,1
HB-043393,City Hotel,0,74,2023,September,38,18,2023-09-18,0,2,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,87.0,0,0
HB-093052,City Hotel,0,96,2024,July,28,9,2024-07-09,2,5,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,141.56,0,2
HB-118373,City Hotel,0,201,2025,August,33,17,2025-08-17,0,2,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,235.0,0,0
HB-078184,City Hotel,0,9,2023,October,40,4,2023-10-04,2,0,1,0.0,0,BB,USA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,109.0,0,0
HB-071487,City Hotel,1,180,2025,July,27,6,2025-07-06,0,3,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,0
HB-101338,City Hotel,0,5,2024,November,45,6,2024-11-06,2,3,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,113.23,0,1
HB-082084,City Hotel,0,0,2023,December,51,19,2023-12-19,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,85.0,0,0
HB-092085,City Hotel,0,105,2024,June,26,26,2024-06-26,2,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.45,0,1
HB-113731,City Hotel,0,130,2025,June,24,9,2025-06-09,0,2,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,89.1,0,0
HB-032470,Resort Hotel,0,3,2025,January,4,26,2025-01-26,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,1,No Deposit,,,0,Transient,40.5,0,0
HB-082819,City Hotel,1,68,2024,February,7,17,2024-02-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,37.0,,0,Transient,75.0,0,0
HB-088783,City Hotel,0,30,2025,May,21,24,2025-05-24,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,20,A,A,0,No Deposit,,219.0,0,Transient,104.0,1,2
HB-008052,Resort Hotel,1,50,2024,September,36,8,2024-09-08,0,3,3,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,219.0,0,1
HB-108442,City Hotel,0,62,2025,March,13,25,2025-03-25,1,1,2,0.0,0,BB,HUN,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,9.0,,0,Transient,106.2,0,0
HB-110576,City Hotel,0,75,2025,April,17,25,2025-04-25,0,4,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,108.0,0,1
HB-055228,City Hotel,1,128,2024,August,32,8,2024-08-08,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.3,0,0
HB-068419,City Hotel,1,15,2025,May,20,17,2025-05-17,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,190.0,0,1
HB-040005,Resort Hotel,0,64,2025,August,35,31,2025-08-31,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,241.0,,0,Transient,187.19,0,1
HB-093831,City Hotel,0,153,2024,July,30,26,2024-07-26,0,2,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,137.7,0,0
HB-088775,City Hotel,0,7,2025,January,2,10,2025-01-10,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,12,A,A,1,No Deposit,,219.0,0,Transient,89.0,1,2
HB-107731,City Hotel,0,41,2025,March,11,13,2025-03-13,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,91.8,0,1
HB-065415,City Hotel,1,46,2025,April,14,3,2025-04-03,1,1,3,0.0,0,BB,LUX,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,171.0,0,0
HB-009041,Resort Hotel,1,86,2024,October,43,24,2024-10-24,1,5,2,0.0,0,HB,DZA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,98.0,0,2
HB-025845,Resort Hotel,0,5,2024,November,46,15,2024-11-15,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,2,A,A,0,No Deposit,,270.0,0,Transient,30.0,0,1
HB-099710,City Hotel,0,377,2024,October,42,14,2024-10-14,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-045235,City Hotel,1,50,2023,October,43,24,2023-10-24,0,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,146.0,0,0
HB-061583,City Hotel,1,8,2024,December,51,17,2024-12-17,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,78.0,0,1
HB-083163,City Hotel,0,0,2024,January,3,21,2024-01-21,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,81.0,0,0
HB-107763,City Hotel,0,55,2025,March,11,12,2025-03-12,2,4,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,91.8,0,1
HB-002282,Resort Hotel,0,132,2023,October,40,8,2023-10-08,1,3,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Contract,44.5,0,0
HB-100038,City Hotel,0,137,2024,October,42,15,2024-10-15,2,5,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,114.28,0,1
HB-022513,Resort Hotel,0,70,2024,March,12,23,2024-03-23,0,4,2,0.0,0,HB,ESP,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,94.5,0,0
HB-079948,City Hotel,0,22,2023,November,45,6,2023-11-06,0,2,2,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,75.0,0,0
HB-019073,Resort Hotel,0,11,2023,December,49,5,2023-12-05,2,1,2,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,350.0,,0,Transient-Party,68.0,0,0
HB-093312,City Hotel,0,37,2024,July,28,13,2024-07-13,2,5,3,1.0,0,BB,FRA,Direct,Direct,0,0,0,G,G,0,No Deposit,14.0,,0,Transient,237.73,0,3
HB-101655,City Hotel,0,39,2024,November,46,11,2024-11-11,2,3,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,73.81,0,1
HB-083307,City Hotel,0,1,2024,January,4,27,2024-01-27,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,100.0,1,0
HB-090176,City Hotel,0,6,2024,May,22,31,2024-05-31,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,101.15,0,0
HB-029226,Resort Hotel,0,386,2024,October,42,20,2024-10-20,1,3,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,49.0,0,0
HB-046026,City Hotel,0,135,2023,December,49,5,2023-12-05,2,1,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-044982,City Hotel,0,102,2023,October,42,16,2023-10-16,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-053216,City Hotel,1,350,2024,June,25,17,2024-06-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,140.0,0,0
HB-043210,City Hotel,0,21,2023,September,37,16,2023-09-16,0,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Contract,161.33,0,0
HB-099108,City Hotel,0,72,2024,October,41,9,2024-10-09,1,0,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,132.3,0,3
HB-119144,City Hotel,0,323,2025,August,35,29,2025-08-29,0,1,2,1.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,9.0,,0,Transient,125.1,0,2
HB-074958,City Hotel,1,164,2023,August,33,14,2023-08-14,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-008398,Resort Hotel,0,542,2024,September,39,26,2024-09-26,2,5,2,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,E,E,0,No Deposit,253.0,,0,Transient-Party,87.0,0,3
HB-066383,City Hotel,1,68,2025,April,16,18,2025-04-18,0,4,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,135.0,0,0
HB-004206,Resort Hotel,1,74,2024,February,9,26,2024-02-26,1,2,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,68.0,,0,Transient,70.0,0,0
HB-072219,City Hotel,1,100,2025,July,30,23,2025-07-23,3,5,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,225.0,0,2
HB-024140,Resort Hotel,0,87,2024,May,19,9,2024-05-09,1,3,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,44.66,0,2
HB-000481,Resort Hotel,0,64,2023,July,29,17,2023-07-17,2,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,175.0,,0,Transient-Party,84.8,0,1
HB-067767,City Hotel,1,101,2025,May,19,6,2025-05-06,2,4,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,135.0,0,2
HB-115722,City Hotel,0,157,2025,July,28,8,2025-07-08,1,1,2,0.0,0,BB,BRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,86.63,0,0
HB-112856,City Hotel,0,127,2025,May,22,26,2025-05-26,1,2,2,2.0,0,BB,FRA,Direct,Direct,0,0,0,G,G,0,No Deposit,14.0,,0,Transient,229.5,0,0
HB-000250,Resort Hotel,0,22,2023,July,28,10,2023-07-10,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,88.2,0,0
HB-077912,City Hotel,0,16,2023,September,39,25,2023-09-25,2,3,1,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,170.0,0,1
HB-066799,City Hotel,1,96,2025,April,17,26,2025-04-26,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,130.0,0,0
HB-045039,City Hotel,1,102,2023,October,42,16,2023-10-16,0,2,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,87.0,0,0
HB-084898,City Hotel,0,6,2024,February,9,28,2024-02-28,2,5,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,85.0,,0,Transient,80.2,0,0
HB-097495,City Hotel,0,5,2024,September,38,16,2024-09-16,0,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,B,1,No Deposit,7.0,,0,Transient,139.13,1,1
HB-078800,City Hotel,0,14,2023,October,41,15,2023-10-15,0,2,1,0.0,0,BB,DZA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,99.0,,0,Transient-Party,100.0,0,0
HB-071991,City Hotel,1,56,2025,July,29,17,2025-07-17,1,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.0,0,1
HB-019253,Resort Hotel,0,0,2024,January,2,11,2024-01-11,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,D,D,0,No Deposit,,,0,Transient,38.0,1,1
HB-007291,Resort Hotel,0,194,2024,August,31,1,2024-08-01,2,5,2,0.0,0,HB,POL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,315.0,,0,Transient,130.55,0,0
HB-092832,City Hotel,0,6,2024,July,28,12,2024-07-12,0,1,1,0.0,0,BB,FRA,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,227.0,0,Transient,79.0,0,0
HB-075502,City Hotel,1,341,2023,September,38,23,2023-09-23,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-086461,City Hotel,0,41,2024,March,13,31,2024-03-31,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.9,0,1
HB-032097,Resort Hotel,0,33,2025,January,3,14,2025-01-14,2,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,69.33,0,2
HB-042959,City Hotel,0,148,2023,September,37,11,2023-09-11,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,93.5,0,1
HB-098234,City Hotel,0,151,2024,September,39,23,2024-09-23,2,2,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,162.0,0,2
HB-028576,Resort Hotel,0,165,2024,October,40,2,2024-10-02,2,2,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,96.0,,0,Transient,46.0,0,0
HB-081942,City Hotel,1,278,2024,August,32,11,2024-08-11,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,65.0,0,0
HB-045497,City Hotel,1,100,2023,October,44,31,2023-10-31,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-103778,City Hotel,0,36,2024,December,52,28,2024-12-28,0,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,168.73,0,0
HB-041168,City Hotel,0,39,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-081483,City Hotel,0,4,2023,December,50,11,2023-12-11,0,1,2,2.0,1,BB,PRT,Complementary,Direct,0,0,0,B,B,0,No Deposit,45.0,,0,Transient,0.0,0,0
HB-038719,Resort Hotel,0,26,2025,July,30,24,2025-07-24,1,3,2,0.0,0,BB,AUS,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,239.0,0,0
HB-061811,City Hotel,1,66,2024,December,52,26,2024-12-26,1,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,110.84,0,0
HB-091828,City Hotel,0,192,2024,June,26,24,2024-06-24,0,2,1,0.0,0,BB,SRB,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,34.0,,0,Transient-Party,95.0,0,0
HB-090147,City Hotel,0,44,2024,June,22,1,2024-06-01,0,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.6,0,1
HB-116094,City Hotel,0,414,2025,July,28,13,2025-07-13,0,2,1,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,95.5,0,0
HB-074061,City Hotel,1,314,2023,August,34,27,2023-08-27,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-059577,City Hotel,1,128,2024,October,44,29,2024-10-29,2,1,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,123.3,0,1
HB-088446,City Hotel,0,164,2024,May,18,2,2024-05-02,1,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,B,1,No Deposit,8.0,,0,Transient,99.45,0,0
HB-062231,City Hotel,1,65,2025,January,1,5,2025-01-05,0,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.6,0,0
HB-077178,City Hotel,1,263,2023,September,38,21,2023-09-21,1,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,1,No Deposit,21.0,,0,Transient-Party,59.5,0,0
HB-104175,City Hotel,0,15,2025,January,1,3,2025-01-03,0,4,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,149.6,0,1
HB-024388,Resort Hotel,0,108,2024,May,20,14,2024-05-14,2,3,2,0.0,0,HB,ESP,Direct,Direct,0,0,0,D,D,1,No Deposit,250.0,,0,Transient,97.2,1,1
HB-024013,Resort Hotel,0,6,2025,February,8,20,2025-02-20,1,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,1,0,1,A,A,0,No Deposit,6.0,,0,Group,37.0,1,0
HB-012080,Resort Hotel,1,319,2025,June,24,12,2025-06-12,1,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,74.25,0,0
HB-049857,City Hotel,1,265,2024,April,16,20,2024-04-20,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,30.0,,0,Transient,101.0,0,0
HB-057922,City Hotel,1,285,2024,October,40,3,2024-10-03,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,24,Transient,100.0,0,0
HB-014586,Resort Hotel,0,19,2025,July,28,10,2025-07-10,1,4,2,1.0,0,HB,PRT,Direct,Direct,0,0,2,D,D,3,No Deposit,,,0,Transient,245.5,0,3
HB-025436,Resort Hotel,0,5,2024,June,26,25,2024-06-25,1,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,181.0,1,0
HB-042271,City Hotel,1,63,2023,September,36,4,2023-09-04,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,116.0,0,0
HB-021455,Resort Hotel,0,17,2024,February,9,26,2024-02-26,1,2,2,0.0,1,HB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,196.0,,0,Transient-Party,56.0,0,1
HB-083036,City Hotel,0,0,2024,January,2,14,2024-01-14,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,15.0,,0,Transient,72.8,0,0
HB-116930,City Hotel,0,79,2025,July,30,23,2025-07-23,2,2,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,190.0,0,2
HB-016374,Resort Hotel,0,41,2023,October,42,18,2023-10-18,4,6,2,1.0,0,BB,FRA,Direct,Direct,1,0,1,C,H,0,No Deposit,,,0,Transient-Party,66.0,0,1
HB-072531,City Hotel,1,47,2025,July,31,30,2025-07-30,2,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,155.0,,0,Transient,164.0,0,2
HB-115066,City Hotel,0,107,2025,June,26,29,2025-06-29,0,2,2,1.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,195.3,1,2
HB-109251,City Hotel,0,121,2025,April,15,7,2025-04-07,0,2,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,99.0,0,1
HB-054778,City Hotel,1,230,2024,July,30,26,2024-07-26,0,3,0,2.0,0,BB,BEL,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient-Party,86.5,0,1
HB-010932,Resort Hotel,1,51,2025,April,15,11,2025-04-11,0,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,90.0,0,2
HB-064696,City Hotel,1,92,2025,March,11,15,2025-03-15,0,3,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,85.0,0,0
HB-081117,City Hotel,1,146,2024,March,13,30,2024-03-30,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,86.0,,28,Transient,80.0,0,0
HB-042068,City Hotel,1,104,2023,August,35,30,2023-08-30,2,1,2,0.0,0,HB,ESP,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,90.0,0,0
HB-013061,Resort Hotel,1,56,2025,July,31,29,2025-07-29,2,5,2,2.0,0,BB,MAR,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,305.0,0,1
HB-111078,City Hotel,0,85,2025,May,19,6,2025-05-06,2,3,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Group,135.0,0,3
HB-063067,City Hotel,1,122,2025,January,5,28,2025-01-28,2,5,2,1.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,103.7,0,1
HB-116482,City Hotel,0,14,2025,July,29,17,2025-07-17,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,89.0,,0,Transient,121.6,0,0
HB-038514,Resort Hotel,0,25,2025,August,34,18,2025-08-18,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,1,0,1,A,A,0,No Deposit,240.0,,0,Transient-Party,244.0,0,2
HB-101942,City Hotel,0,3,2024,November,47,18,2024-11-18,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,111.0,0,4
HB-071431,City Hotel,1,200,2025,July,27,5,2025-07-05,0,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,1
HB-084911,City Hotel,0,39,2024,March,10,4,2024-03-04,0,2,1,0.0,0,BB,JPN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,77.5,0,1
HB-048079,City Hotel,1,47,2024,March,11,16,2024-03-16,0,2,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,0
HB-056970,City Hotel,1,43,2024,September,38,16,2024-09-16,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,86.0,,0,Transient-Party,130.0,0,0
HB-060815,City Hotel,1,46,2024,November,47,22,2024-11-22,0,4,2,0.0,0,SC,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,1
HB-009902,Resort Hotel,1,3,2025,January,4,20,2025-01-20,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,1,No Deposit,250.0,,0,Transient,60.0,0,0
HB-104006,City Hotel,0,0,2025,January,1,2,2025-01-02,1,1,1,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,,,0,Transient,0.0,0,1
HB-056106,City Hotel,1,28,2024,August,35,29,2024-08-29,1,2,3,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,155.73,0,1
HB-023729,Resort Hotel,0,8,2024,April,18,30,2024-04-30,1,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,91.0,1,1
HB-082732,City Hotel,0,39,2024,January,1,1,2024-01-01,2,3,2,0.0,0,SC,FIN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,60.97,0,0
HB-056716,City Hotel,1,32,2024,September,37,11,2024-09-11,2,1,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,149.4,0,0
HB-099555,City Hotel,0,2,2024,October,41,13,2024-10-13,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,344.0,,0,Transient-Party,109.65,0,0
HB-013911,Resort Hotel,0,16,2024,September,37,9,2024-09-09,2,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,152.1,0,0
HB-022291,Resort Hotel,0,0,2024,March,11,16,2024-03-16,2,5,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,E,0,No Deposit,171.0,,0,Transient,55.0,0,0
HB-017916,Resort Hotel,0,7,2024,April,14,6,2024-04-06,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,1,0,3,A,A,0,No Deposit,314.0,,0,Transient-Party,40.32,1,0
HB-079606,City Hotel,0,11,2023,October,43,23,2023-10-23,2,5,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,E,1,No Deposit,9.0,,0,Contract,116.71,0,3
HB-084489,City Hotel,1,3,2024,February,9,26,2024-02-26,0,0,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,9.0,,0,Transient,0.0,0,1
HB-065955,City Hotel,1,141,2025,April,15,11,2025-04-11,0,1,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.5,0,0
HB-054952,City Hotel,1,0,2024,August,31,1,2024-08-01,1,0,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.0,0,1
HB-067956,City Hotel,1,35,2025,May,19,10,2025-05-10,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,39.0,,0,Transient-Party,130.0,0,0
HB-067319,City Hotel,1,295,2025,May,18,1,2025-05-01,1,3,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,142.2,0,0
HB-003466,Resort Hotel,0,44,2023,December,50,17,2023-12-17,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,29.0,1,0
HB-066070,City Hotel,1,175,2025,April,15,13,2025-04-13,1,3,3,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,166.5,0,2
HB-008220,Resort Hotel,1,128,2024,September,38,18,2024-09-18,4,6,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,177.0,,0,Transient,116.0,0,0
HB-059487,City Hotel,1,189,2024,October,44,28,2024-10-28,1,2,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,109.8,0,0
HB-048275,City Hotel,1,393,2024,March,12,19,2024-03-19,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,70.53,0,0
HB-063661,City Hotel,1,91,2025,February,8,17,2025-02-17,0,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.6,0,1
HB-067027,City Hotel,1,111,2025,April,17,27,2025-04-27,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,0,Transient,120.0,0,0
HB-047907,City Hotel,1,2,2024,March,10,9,2024-03-09,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,219.0,0,Transient,88.0,0,0
HB-026176,Resort Hotel,0,133,2024,July,28,14,2024-07-14,2,8,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Contract,106.55,0,0
HB-011674,Resort Hotel,1,462,2025,May,21,25,2025-05-25,0,3,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,78.0,0,0
HB-102489,City Hotel,0,5,2025,March,10,8,2025-03-08,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,2,A,D,0,No Deposit,,219.0,0,Transient,80.0,0,2
HB-021849,Resort Hotel,0,46,2024,March,11,11,2024-03-11,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,3,No Deposit,375.0,,0,Transient-Party,29.0,0,0
HB-000823,Resort Hotel,0,4,2023,July,31,31,2023-07-31,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient-Party,192.0,0,2
HB-108627,City Hotel,0,45,2025,March,13,27,2025-03-27,1,2,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,88.2,0,2
HB-052218,City Hotel,1,330,2024,June,22,2,2024-06-02,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-021639,Resort Hotel,0,53,2024,February,9,26,2024-02-26,2,7,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,115.0,,0,Transient,26.1,0,1
HB-005664,Resort Hotel,0,256,2024,May,19,8,2024-05-08,4,6,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,2.0,,0,Contract,58.95,0,0
HB-110869,City Hotel,0,12,2025,April,18,30,2025-04-30,2,1,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,153.33,0,1
HB-054585,City Hotel,1,196,2024,July,29,20,2024-07-20,0,3,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.5,0,0
HB-032848,Resort Hotel,0,19,2025,February,6,6,2025-02-06,1,0,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,F,F,1,No Deposit,250.0,,0,Transient,102.0,0,0
HB-091640,City Hotel,0,37,2024,June,25,21,2024-06-21,0,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,1
HB-114340,City Hotel,0,35,2025,June,24,13,2025-06-13,2,5,2,0.0,0,HB,ROU,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,196.14,0,1
HB-007051,Resort Hotel,1,46,2024,July,29,18,2024-07-18,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,209.0,0,0
HB-104958,City Hotel,0,5,2025,January,4,23,2025-01-23,1,3,1,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,1
HB-099871,City Hotel,0,73,2024,October,44,28,2024-10-28,0,1,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,1,A,A,1,No Deposit,21.0,,0,Transient-Party,73.0,0,0
HB-033007,Resort Hotel,0,0,2025,February,7,11,2025-02-11,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient-Party,68.0,0,0
HB-067274,City Hotel,1,43,2025,May,18,1,2025-05-01,1,1,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,149.0,0,0
HB-086978,City Hotel,0,23,2024,April,15,9,2024-04-09,2,1,2,1.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,7.0,,0,Transient,93.82,0,2
HB-050416,City Hotel,1,87,2024,April,18,30,2024-04-30,1,1,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,111.6,0,1
HB-078251,City Hotel,0,14,2023,October,40,5,2023-10-05,1,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,109.0,0,0
HB-113698,City Hotel,0,73,2025,June,23,8,2025-06-08,0,3,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,140.0,0,0
HB-081623,City Hotel,1,130,2024,April,15,13,2024-04-13,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,29.0,,10,Transient,100.0,0,0
HB-000442,Resort Hotel,1,66,2023,July,28,16,2023-07-16,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,103.5,0,1
HB-083556,City Hotel,0,14,2024,February,5,4,2024-02-04,0,3,2,0.0,0,BB,GRC,Corporate,Corporate,0,0,0,G,G,1,No Deposit,,183.0,0,Transient-Party,112.0,0,0
HB-069652,City Hotel,1,348,2025,June,23,3,2025-06-03,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient,90.0,0,0
HB-105496,City Hotel,0,1,2025,February,6,8,2025-02-08,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,0
HB-082462,City Hotel,0,59,2023,December,52,28,2023-12-28,1,2,2,0.0,0,SC,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Group,73.73,0,0
HB-055633,City Hotel,1,405,2024,August,33,18,2024-08-18,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-058361,City Hotel,1,128,2024,October,41,11,2024-10-11,0,3,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.8,0,1
HB-101049,City Hotel,0,20,2024,November,45,6,2024-11-06,2,2,1,0.0,0,BB,EST,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,124.16,0,1
HB-003345,Resort Hotel,1,44,2023,December,49,5,2023-12-05,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,70.0,0,0
HB-081469,City Hotel,0,0,2023,December,50,11,2023-12-11,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,1,No Deposit,,40.0,0,Transient,75.0,0,1
HB-068083,City Hotel,1,80,2025,May,20,12,2025-05-12,1,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,129.0,0,0
HB-085785,City Hotel,0,53,2024,March,11,15,2024-03-15,2,5,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,83.92,1,1
HB-072207,City Hotel,1,204,2025,July,30,23,2025-07-23,2,2,3,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,170.0,0,0
HB-110567,City Hotel,0,98,2025,April,17,24,2025-04-24,1,4,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-071512,City Hotel,1,315,2025,July,28,7,2025-07-07,0,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient,91.85,0,3
HB-033034,Resort Hotel,0,4,2025,February,7,11,2025-02-11,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,E,0,No Deposit,250.0,,0,Transient,48.0,0,0
HB-055736,City Hotel,1,151,2024,August,34,19,2024-08-19,2,3,2,2.0,0,BB,POL,Online TA,TA/TO,0,0,0,B,B,2,No Deposit,9.0,,0,Transient,198.59,0,0
HB-048621,City Hotel,0,90,2024,March,13,25,2024-03-25,2,2,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient,79.8,0,1
HB-055116,City Hotel,1,238,2024,August,32,5,2024-08-05,0,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient-Party,86.75,0,0
HB-063952,City Hotel,1,134,2025,February,9,25,2025-02-25,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,75.0,0,0
HB-071151,City Hotel,1,286,2025,June,26,28,2025-06-28,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,71,Transient,110.0,0,0
HB-014666,Resort Hotel,0,9,2025,March,13,30,2025-03-30,0,1,1,0.0,0,BB,,Corporate,Corporate,0,0,2,A,A,0,No Deposit,,135.0,0,Transient,35.0,1,0
HB-007175,Resort Hotel,1,196,2024,July,30,25,2024-07-25,1,4,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,242.0,,0,Transient,190.0,0,0
HB-029651,Resort Hotel,0,43,2024,October,44,29,2024-10-29,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,F,1,No Deposit,240.0,,0,Transient,79.0,0,0
HB-024849,Resort Hotel,0,30,2024,May,22,30,2024-05-30,1,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,93.67,1,1
HB-041287,City Hotel,1,39,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,101.5,0,0
HB-051300,City Hotel,1,323,2024,May,20,17,2024-05-17,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,70.0,0,0
HB-056246,City Hotel,1,155,2024,September,35,1,2024-09-01,2,3,2,0.0,0,HB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,161.1,0,0
HB-067025,City Hotel,1,111,2025,April,17,27,2025-04-27,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,0,Transient,120.0,0,0
HB-000513,Resort Hotel,0,45,2023,July,29,18,2023-07-18,2,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,167.0,0,0
HB-061913,City Hotel,1,16,2024,December,52,28,2024-12-28,2,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,76.67,0,0
HB-043342,City Hotel,1,74,2023,September,38,18,2023-09-18,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-051850,City Hotel,0,316,2024,May,21,26,2024-05-26,0,3,2,0.0,0,BB,AUT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,110.0,0,0
HB-002276,Resort Hotel,0,3,2023,October,40,8,2023-10-08,0,3,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,281.0,,0,Contract,45.0,0,0
HB-088323,City Hotel,0,72,2024,May,18,2,2024-05-02,1,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,F,1,No Deposit,9.0,,0,Transient,149.4,0,2
HB-064221,City Hotel,1,289,2025,March,9,2,2025-03-02,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,81.9,0,0
HB-084403,City Hotel,0,6,2024,February,8,21,2024-02-21,2,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,70.0,0,0
HB-007872,Resort Hotel,1,83,2024,August,35,31,2024-08-31,0,4,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,216.0,0,0
HB-008648,Resort Hotel,1,151,2024,October,41,8,2024-10-08,1,1,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,4,No Deposit,240.0,,0,Transient,54.5,0,0
HB-076966,City Hotel,1,342,2023,September,38,24,2023-09-24,2,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-006515,Resort Hotel,1,248,2024,June,24,14,2024-06-14,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,72.0,0,0
HB-021692,Resort Hotel,0,1,2024,March,10,7,2024-03-07,1,0,1,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,D,0,No Deposit,250.0,,0,Transient-Party,40.0,0,0
HB-010075,Resort Hotel,1,238,2025,February,7,10,2025-02-10,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,155.0,,0,Transient,54.0,0,0
HB-072346,City Hotel,1,243,2025,July,30,26,2025-07-26,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-004356,Resort Hotel,1,196,2024,March,10,7,2024-03-07,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,242.0,,0,Transient,41.4,0,2
HB-099298,City Hotel,0,2,2024,October,41,11,2024-10-11,0,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,152.0,,0,Transient,92.98,0,0
HB-107892,City Hotel,0,94,2025,March,12,17,2025-03-17,1,2,2,0.0,0,BB,AUT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,72.0,0,0
HB-025708,Resort Hotel,1,9,2024,September,37,14,2024-09-14,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,3,2,D,D,0,No Deposit,,331.0,0,Transient,114.0,0,0
HB-003726,Resort Hotel,1,66,2023,December,52,31,2023-12-31,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,93.6,0,1
HB-092684,City Hotel,0,44,2024,July,28,9,2024-07-09,0,1,2,1.0,0,BB,ROU,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,189.9,0,2
HB-001597,Resort Hotel,1,94,2023,September,36,5,2023-09-05,2,5,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,G,G,0,No Deposit,,,0,Transient,153.0,0,0
HB-011513,Resort Hotel,1,201,2025,May,20,13,2025-05-13,1,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,76.5,0,1
HB-007604,Resort Hotel,1,293,2024,August,33,16,2024-08-16,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,126.0,0,2
HB-050476,City Hotel,1,114,2024,May,18,2,2024-05-02,1,1,1,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.9,0,0
HB-036908,Resort Hotel,0,42,2025,May,22,30,2025-05-30,0,2,2,0.0,0,BB,ARG,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,468.0,,0,Transient,98.4,1,0
HB-100432,City Hotel,0,55,2024,October,43,23,2024-10-23,2,3,2,0.0,0,SC,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,72.25,0,0
HB-096418,City Hotel,0,23,2024,August,35,30,2024-08-30,0,3,2,0.0,0,BB,ITA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,93.5,0,2
HB-016381,Resort Hotel,0,21,2023,August,34,26,2023-08-26,0,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,172.0,0,2
HB-097122,City Hotel,0,15,2024,September,37,11,2024-09-11,2,0,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,109.0,0,1
HB-033320,Resort Hotel,0,12,2025,February,8,19,2025-02-19,1,0,2,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,498.0,0,Transient-Party,40.0,0,1
HB-054538,City Hotel,1,43,2024,July,29,19,2024-07-19,0,3,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,123.9,0,0
HB-070833,City Hotel,1,233,2025,June,26,23,2025-06-23,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,105.0,0,0
HB-110636,City Hotel,0,6,2025,April,18,29,2025-04-29,0,1,1,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,160.0,0,1
HB-118411,City Hotel,0,120,2025,August,33,16,2025-08-16,0,4,2,0.0,0,HB,HUN,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient-Party,183.0,0,2
HB-026442,Resort Hotel,0,3,2024,July,31,30,2024-07-30,0,1,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,241.0,1,1
HB-029266,Resort Hotel,0,189,2024,October,43,21,2024-10-21,1,2,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,147.0,,0,Transient,53.57,0,1
HB-092859,City Hotel,0,1,2024,July,28,11,2024-07-11,1,1,2,1.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,169.0,0,2
HB-006489,Resort Hotel,0,221,2024,June,24,13,2024-06-13,0,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,I,0,No Deposit,314.0,,0,Transient,0.0,0,0
HB-038087,Resort Hotel,0,8,2025,July,28,7,2025-07-07,0,2,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,242.0,,0,Transient,199.0,1,1
HB-048387,City Hotel,1,251,2024,March,12,22,2024-03-22,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,93,Transient,125.0,0,0
HB-060497,City Hotel,1,54,2024,November,46,12,2024-11-12,2,1,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.2,0,1
HB-108337,City Hotel,0,104,2025,March,12,19,2025-03-19,2,5,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,20.0,,0,Transient-Party,75.0,0,1
HB-000085,Resort Hotel,0,99,2023,July,27,3,2023-07-03,3,7,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,115.0,,0,Contract,111.15,0,0
HB-005285,Resort Hotel,1,143,2024,April,17,24,2024-04-24,2,2,2,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,68.0,,0,Transient,84.0,0,0
HB-006652,Resort Hotel,0,253,2024,June,25,22,2024-06-22,0,3,2,0.0,0,HB,POL,Groups,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient-Party,92.0,0,0
HB-080469,City Hotel,1,34,2023,December,49,8,2023-12-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,0,Transient,90.0,0,0
HB-070383,City Hotel,1,55,2025,June,25,16,2025-06-16,0,2,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,1
HB-031001,Resort Hotel,0,0,2024,December,50,9,2024-12-09,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,91.0,0,1
HB-023101,Resort Hotel,0,28,2024,April,15,13,2024-04-13,0,2,2,0.0,0,BB,IND,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,60.0,0,0
HB-049792,City Hotel,1,103,2024,April,16,19,2024-04-19,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,0,Transient,115.0,0,0
HB-113008,City Hotel,0,135,2025,May,22,29,2025-05-29,1,2,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,133.06,0,1
HB-021444,Resort Hotel,0,16,2024,February,9,27,2024-02-27,1,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-090947,City Hotel,0,147,2024,June,24,11,2024-06-11,2,1,2,0.0,0,BB,BIH,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient-Party,102.3,0,0
HB-103445,City Hotel,0,67,2024,December,51,20,2024-12-20,0,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,64.67,0,1
HB-078743,City Hotel,0,4,2023,October,41,11,2023-10-11,2,3,1,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,92.4,0,0
HB-004871,Resort Hotel,1,116,2024,April,14,4,2024-04-04,2,5,2,0.0,0,HB,GBR,Groups,Direct,0,0,0,D,D,0,Non Refund,273.0,,0,Transient,72.0,0,0
HB-052593,City Hotel,1,12,2024,June,23,8,2024-06-08,0,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,121.0,0,1
HB-103333,City Hotel,0,89,2024,December,51,17,2024-12-17,2,1,1,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,2
HB-086391,City Hotel,0,53,2024,March,13,28,2024-03-28,1,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.85,0,2
HB-020490,Resort Hotel,0,42,2024,January,4,28,2024-01-28,0,3,3,0.0,0,BB,POL,Direct,Direct,0,0,0,A,D,0,No Deposit,250.0,,0,Transient,79.0,0,1
HB-046323,City Hotel,1,140,2023,December,52,29,2023-12-29,0,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,70.0,0,0
HB-005781,Resort Hotel,1,35,2024,May,20,14,2024-05-14,2,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,147.0,,0,Transient-Party,53.87,0,0
HB-031127,Resort Hotel,0,1,2024,December,50,14,2024-12-14,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,314.0,,0,Transient,34.4,0,1
HB-003448,Resort Hotel,0,140,2023,December,49,10,2023-12-10,0,0,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,F,I,0,No Deposit,241.0,,0,Transient,0.0,0,1
HB-114878,City Hotel,0,25,2025,June,26,27,2025-06-27,0,1,2,0.0,0,BB,DEU,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,280.0,0,Transient-Party,100.0,0,0
HB-114806,City Hotel,0,396,2025,June,26,25,2025-06-25,2,0,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,122.4,0,1
HB-091619,City Hotel,0,24,2024,June,25,23,2024-06-23,0,1,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,101.0,0,1
HB-063856,City Hotel,1,223,2025,February,8,23,2025-02-23,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,132.0,,165,Transient,78.0,0,0
HB-015815,Resort Hotel,0,77,2023,July,30,29,2023-07-29,1,4,2,1.0,1,BB,NOR,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,241.0,,0,Transient,121.35,0,3
HB-101128,City Hotel,0,1,2024,November,45,5,2024-11-05,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,94.0,,0,Transient,65.0,0,1
HB-090655,City Hotel,0,118,2024,June,23,6,2024-06-06,1,2,1,0.0,0,BB,ITA,Offline TA/TO,Corporate,0,0,0,A,A,0,No Deposit,191.0,,0,Transient-Party,110.0,0,0
HB-059912,City Hotel,1,304,2024,November,44,3,2024-11-03,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,89.0,0,0
HB-029588,Resort Hotel,0,32,2024,October,44,28,2024-10-28,2,2,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,58.4,1,0
HB-014837,Resort Hotel,1,222,2023,September,37,15,2023-09-15,1,5,2,0.0,0,FB,PRT,Groups,Corporate,0,25,0,A,A,0,Non Refund,252.0,,0,Transient,49.95,0,0
HB-023004,Resort Hotel,0,89,2024,April,15,12,2024-04-12,0,1,2,0.0,0,BB,CHE,Offline TA/TO,TA/TO,0,0,0,D,E,0,No Deposit,251.0,,0,Transient-Party,59.0,0,1
HB-058754,City Hotel,1,93,2024,October,42,15,2024-10-15,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,34.0,,0,Transient,115.0,0,0
HB-037761,Resort Hotel,0,238,2025,June,24,15,2025-06-15,4,10,1,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Contract,63.95,0,1
HB-050294,City Hotel,1,90,2024,April,17,28,2024-04-28,0,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,B,1,No Deposit,9.0,,0,Transient,127.8,0,1
HB-005983,Resort Hotel,1,40,2024,May,20,18,2024-05-18,0,2,1,0.0,0,BB,PRT,Groups,Corporate,0,0,0,A,A,0,Non Refund,,,0,Transient,55.0,0,0
HB-070408,City Hotel,1,157,2025,June,25,16,2025-06-16,1,2,3,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,166.5,0,0
HB-011538,Resort Hotel,1,278,2025,May,20,14,2025-05-14,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,67.5,0,1
HB-012332,Resort Hotel,1,241,2025,June,26,24,2025-06-24,4,6,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,105.66,0,0
HB-082026,City Hotel,1,305,2024,October,40,1,2024-10-01,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,35.0,,17,Transient,100.0,0,0
HB-028123,Resort Hotel,0,0,2024,September,38,20,2024-09-20,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,120.0,1,0
HB-066357,City Hotel,1,386,2025,April,16,18,2025-04-18,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-077292,City Hotel,0,256,2023,September,37,14,2023-09-14,1,2,1,0.0,0,BB,SWE,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,4.0,,0,Transient-Party,0.0,0,0
HB-089580,City Hotel,0,100,2024,May,20,19,2024-05-19,1,3,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,D,2,No Deposit,9.0,,0,Transient-Party,136.0,0,2
HB-008692,Resort Hotel,1,184,2024,October,41,9,2024-10-09,2,3,2,2.0,0,BB,IRL,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,126.4,0,0
HB-015178,Resort Hotel,1,246,2023,September,36,5,2023-09-05,2,5,2,0.0,0,BB,,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,96.0,,0,Transient-Party,58.95,0,0
HB-111832,City Hotel,0,114,2025,May,20,14,2025-05-14,2,1,2,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-103614,City Hotel,0,41,2024,December,52,27,2024-12-27,0,1,2,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,220.0,,0,Transient-Party,65.0,0,0
HB-058563,City Hotel,1,37,2024,October,41,13,2024-10-13,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,105.0,0,0
HB-089786,City Hotel,0,5,2024,May,21,24,2024-05-24,0,2,2,0.0,0,BB,ARG,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,78.0,0,Transient-Party,110.0,0,1
HB-012994,Resort Hotel,1,157,2025,July,30,26,2025-07-26,2,8,1,2.0,0,HB,ESP,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,266.5,0,1
HB-021908,Resort Hotel,0,2,2024,March,11,11,2024-03-11,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,240.0,,0,Transient-Party,74.0,1,0
HB-111650,City Hotel,0,29,2025,May,19,11,2025-05-11,0,3,1,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,190.0,0,2
HB-041499,City Hotel,0,4,2023,August,33,17,2023-08-17,1,2,1,0.0,0,BB,CHE,Direct,Direct,0,0,0,A,D,0,No Deposit,14.0,,0,Transient,67.0,0,0
HB-034517,Resort Hotel,0,241,2025,March,12,21,2025-03-21,2,5,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,D,D,0,No Deposit,273.0,,0,Transient-Party,41.6,0,0
HB-118227,City Hotel,0,172,2025,August,33,12,2025-08-12,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.5,0,1
HB-103493,City Hotel,0,29,2024,December,52,23,2024-12-23,1,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,104.0,0,0
HB-079088,City Hotel,0,5,2023,October,42,19,2023-10-19,1,2,2,0.0,0,BB,POL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,112.0,,0,Transient-Party,90.0,0,0
HB-057294,City Hotel,0,429,2024,September,39,23,2024-09-23,0,2,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,B,0,No Deposit,1.0,,330,Transient-Party,65.0,0,0
HB-091884,City Hotel,0,0,2024,June,26,26,2024-06-26,1,0,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,127.0,0,0
HB-115233,City Hotel,0,0,2025,July,27,2,2025-07-02,1,0,2,0.0,0,SC,PRT,Direct,Direct,0,0,0,B,B,1,No Deposit,,,0,Transient,98.0,0,0
HB-103546,City Hotel,0,219,2024,December,51,22,2024-12-22,2,3,2,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,A,A,3,No Deposit,9.0,,0,Transient,106.25,0,1
HB-080635,City Hotel,1,17,2023,December,49,5,2023-12-05,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Contract,107.0,0,0
HB-048841,City Hotel,1,267,2024,March,13,31,2024-03-31,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-004782,Resort Hotel,0,169,2024,March,13,31,2024-03-31,1,3,2,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,A,0,Refundable,,223.0,0,Transient-Party,66.0,0,0
HB-071085,City Hotel,1,201,2025,June,26,28,2025-06-28,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,59,Transient,125.0,0,0
HB-062466,City Hotel,1,38,2025,January,3,14,2025-01-14,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,Non Refund,,67.0,0,Transient,75.0,0,0
HB-110352,City Hotel,0,102,2025,April,17,24,2025-04-24,1,1,1,0.0,0,BB,IRL,Groups,TA/TO,0,0,0,A,A,1,No Deposit,,424.0,0,Transient-Party,90.0,0,0
HB-088002,City Hotel,0,3,2024,April,17,28,2024-04-28,0,1,1,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.0,0,0
HB-058935,City Hotel,1,97,2024,October,42,17,2024-10-17,2,5,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,0
HB-001200,Resort Hotel,0,13,2023,August,33,18,2023-08-18,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,172.0,0,0
HB-099324,City Hotel,0,35,2024,October,41,9,2024-10-09,2,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,138.0,0,3
HB-019580,Resort Hotel,0,1,2023,December,52,28,2023-12-28,0,0,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,C,1,No Deposit,240.0,,0,Transient,0.0,0,1
HB-008464,Resort Hotel,1,58,2024,September,40,30,2024-09-30,1,2,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,112.33,0,0
HB-036682,Resort Hotel,0,2,2025,May,21,25,2025-05-25,0,1,2,0.0,0,BB,PRT,Online TA,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,115.0,0,0
HB-098890,City Hotel,0,29,2024,October,40,3,2024-10-03,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,143.03,0,3
HB-037283,Resort Hotel,0,20,2025,June,24,11,2025-06-11,1,0,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,66.0,0,0
HB-103127,City Hotel,0,17,2024,December,50,10,2024-12-10,1,1,2,0.0,1,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,378.0,,0,Transient-Party,80.0,0,0
HB-106380,City Hotel,0,7,2025,February,8,20,2025-02-20,1,4,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Contract,68.0,0,0
HB-048762,City Hotel,1,112,2024,March,13,30,2024-03-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,64.0,0,0
HB-017299,Resort Hotel,0,170,2023,September,38,20,2023-09-20,4,10,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Contract,68.0,0,0
HB-117769,City Hotel,0,40,2025,August,32,6,2025-08-06,2,1,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,2
HB-117758,City Hotel,0,64,2025,August,32,6,2025-08-06,2,1,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,149.0,0,1
HB-090453,City Hotel,0,220,2024,June,23,4,2024-06-04,2,1,2,0.0,0,BB,USA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,73.33,0,1
HB-008871,Resort Hotel,1,224,2024,October,42,17,2024-10-17,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,62.29,0,0
HB-041741,City Hotel,0,44,2023,August,34,22,2023-08-22,2,1,2,0.0,0,HB,ITA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,86.0,0,0
HB-018119,Resort Hotel,0,0,2023,November,44,5,2023-11-05,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,63.0,1,0
HB-103034,City Hotel,0,122,2024,December,49,8,2024-12-08,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,83.0,,0,Transient-Party,68.0,0,0
HB-012969,Resort Hotel,1,117,2025,July,30,25,2025-07-25,0,4,2,1.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,3,No Deposit,250.0,,0,Transient,206.62,0,2
HB-075230,City Hotel,1,294,2023,August,32,7,2023-08-07,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,60.0,0,0
HB-040346,City Hotel,0,20,2023,July,29,22,2023-07-22,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-003727,Resort Hotel,1,69,2023,December,52,31,2023-12-31,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,93.6,0,1
HB-109689,City Hotel,0,102,2025,April,16,14,2025-04-14,0,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,139.5,0,1
HB-039091,Resort Hotel,0,87,2025,August,31,3,2025-08-03,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,244.0,0,2
HB-118751,City Hotel,0,210,2025,August,34,18,2025-08-18,2,5,1,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.51,0,3
HB-114362,City Hotel,0,0,2025,June,25,20,2025-06-20,0,1,1,0.0,0,SC,DNK,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,165.0,0,0
HB-037368,Resort Hotel,0,0,2025,June,24,14,2025-06-14,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,148.5,0,3
HB-044429,City Hotel,1,97,2023,October,40,5,2023-10-05,1,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,140.0,0,0
HB-035266,Resort Hotel,0,10,2025,April,16,15,2025-04-15,1,1,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,241.0,,0,Transient,165.4,1,1
HB-042072,City Hotel,1,104,2023,August,35,30,2023-08-30,2,1,2,0.0,0,HB,ESP,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,90.0,0,0
HB-007754,Resort Hotel,1,74,2024,August,34,24,2024-08-24,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,195.43,0,0
HB-099680,City Hotel,0,377,2024,October,42,14,2024-10-14,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-003539,Resort Hotel,0,131,2023,December,51,22,2023-12-22,2,5,2,0.0,0,HB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient-Party,64.14,0,1
HB-017565,Resort Hotel,0,5,2023,October,41,13,2023-10-13,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,66.0,0,2
HB-043617,City Hotel,0,60,2023,September,38,21,2023-09-21,1,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,20.0,,0,Transient-Party,49.5,0,0
HB-027632,Resort Hotel,0,24,2024,September,35,1,2024-09-01,1,3,2,0.0,0,BB,NGA,Online TA,TA/TO,0,0,0,F,E,0,No Deposit,241.0,,0,Transient,164.78,0,2
HB-032851,Resort Hotel,0,0,2025,February,6,7,2025-02-07,0,0,1,0.0,0,BB,PRT,Online TA,TA/TO,1,0,0,A,A,0,No Deposit,314.0,,0,Transient,0.0,0,0
HB-091320,City Hotel,0,1,2024,June,25,17,2024-06-17,1,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,70.0,0,0
HB-008260,Resort Hotel,1,244,2024,September,38,20,2024-09-20,2,5,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,135.0,0,2
HB-112383,City Hotel,0,5,2025,May,21,22,2025-05-22,1,1,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,1,No Deposit,315.0,,0,Transient-Party,110.0,0,0
HB-062833,City Hotel,1,59,2025,January,4,23,2025-01-23,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,326.0,,0,Transient,80.0,0,0
HB-097041,City Hotel,0,277,2024,September,36,5,2024-09-05,2,5,2,0.0,0,HB,NOR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,89.14,0,1
HB-115611,City Hotel,0,176,2025,July,28,7,2025-07-07,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,79.0,,0,Transient,85.68,0,0
HB-082779,City Hotel,1,68,2024,February,7,17,2024-02-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,37.0,,0,Transient,75.0,0,0
HB-056272,City Hotel,1,120,2024,September,36,2,2024-09-02,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,115.0,0,0
HB-089595,City Hotel,0,91,2024,May,21,21,2024-05-21,1,1,2,0.0,0,SC,CHL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,125.1,1,0
HB-002210,Resort Hotel,1,74,2023,October,40,5,2023-10-05,3,6,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,86.0,0,2
HB-006913,Resort Hotel,1,26,2024,July,28,11,2024-07-11,1,4,2,2.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,C,C,0,No Deposit,,,0,Transient,165.75,0,0
HB-026498,Resort Hotel,0,83,2024,July,30,25,2024-07-25,3,5,2,0.0,0,BB,ITA,Groups,Corporate,0,0,0,A,A,0,No Deposit,307.0,,0,Transient-Party,144.0,1,0
HB-071954,City Hotel,1,0,2025,July,29,16,2025-07-16,1,0,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,190.0,0,3
HB-079485,City Hotel,0,19,2023,October,43,27,2023-10-27,0,1,1,0.0,0,BB,ESP,Corporate,Corporate,0,0,0,A,A,0,No Deposit,106.0,,0,Group,95.0,0,1
HB-011105,Resort Hotel,1,28,2025,April,16,19,2025-04-19,0,2,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,100.0,0,1
HB-097833,City Hotel,0,78,2024,September,38,18,2024-09-18,2,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,158.4,1,1
HB-070674,City Hotel,1,54,2025,June,25,20,2025-06-20,0,5,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,B,B,0,No Deposit,,,0,Transient-Party,136.7,0,0
HB-036127,Resort Hotel,0,114,2025,May,18,4,2025-05-04,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,314.0,,0,Transient,63.2,0,0
HB-100783,City Hotel,0,3,2024,October,44,28,2024-10-28,2,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.0,0,2
HB-079017,City Hotel,0,5,2025,March,11,15,2025-03-15,0,1,1,0.0,0,BB,PRT,Complementary,Corporate,1,2,9,A,A,0,No Deposit,,45.0,0,Transient,0.0,0,1
HB-081368,City Hotel,0,11,2024,October,40,4,2024-10-04,0,2,1,0.0,0,HB,PRT,Complementary,Corporate,1,1,0,A,B,1,No Deposit,,45.0,0,Transient,0.0,0,0
HB-074515,City Hotel,1,332,2023,September,37,14,2023-09-14,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-025453,Resort Hotel,0,13,2024,June,26,25,2024-06-25,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,141.0,1,0
HB-046084,City Hotel,1,106,2023,December,49,9,2023-12-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,57,Transient,75.0,0,0
HB-077732,City Hotel,0,4,2023,September,38,22,2023-09-22,0,3,1,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,13.0,,0,Contract,111.2,0,1
HB-075001,City Hotel,1,181,2023,July,26,1,2023-07-01,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Transient-Party,76.5,0,3
HB-031512,Resort Hotel,0,2,2025,January,4,26,2025-01-26,0,2,2,0.0,0,BB,NLD,Direct,Direct,1,0,2,A,D,1,No Deposit,,,0,Transient,40.5,0,0
HB-107630,City Hotel,0,6,2025,March,11,15,2025-03-15,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,443.0,0,Transient,65.0,0,1
HB-109801,City Hotel,0,117,2025,April,15,13,2025-04-13,1,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,144.0,0,2
HB-073029,City Hotel,1,102,2025,August,33,12,2025-08-12,2,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.0,0,0
HB-046038,City Hotel,0,135,2023,December,49,5,2023-12-05,2,1,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-099818,City Hotel,0,0,2024,October,42,17,2024-10-17,1,1,1,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,2,No Deposit,,62.0,0,Transient-Party,95.0,0,0
HB-117972,City Hotel,0,308,2025,August,32,7,2025-08-07,1,5,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,89.1,0,1
HB-043899,City Hotel,1,87,2023,September,39,25,2023-09-25,2,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-110861,City Hotel,0,140,2025,April,18,28,2025-04-28,2,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,119.0,,0,Transient-Party,130.0,0,1
HB-073952,City Hotel,1,272,2023,July,28,16,2023-07-16,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Contract,62.0,0,0
HB-011164,Resort Hotel,1,203,2025,April,17,25,2025-04-25,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,90.0,0,0
HB-005533,Resort Hotel,0,199,2024,May,18,2,2024-05-02,1,1,1,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,1,No Deposit,298.0,,0,Transient-Party,54.5,0,0
HB-081674,City Hotel,1,182,2024,April,17,27,2024-04-27,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,3.0,,50,Transient,75.0,0,0
HB-076790,City Hotel,1,395,2024,March,12,21,2024-03-21,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-032224,Resort Hotel,0,40,2025,January,3,16,2025-01-16,1,2,1,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,55.0,0,0
HB-004695,Resort Hotel,1,66,2024,March,13,28,2024-03-28,1,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,52.0,0,2
HB-090897,City Hotel,0,58,2024,June,24,10,2024-06-10,1,2,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,159.3,0,2
HB-112866,City Hotel,0,127,2025,May,22,26,2025-05-26,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,28.0,,0,Transient,85.0,0,0
HB-043607,City Hotel,0,60,2023,September,38,21,2023-09-21,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,20.0,,0,Transient-Party,65.0,0,0
HB-069876,City Hotel,1,181,2025,June,23,8,2025-06-08,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,0,Transient,100.0,0,0
HB-001100,Resort Hotel,0,38,2023,August,33,14,2023-08-14,0,2,3,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,242.0,,0,Transient,266.4,0,2
HB-032922,Resort Hotel,0,7,2025,February,6,9,2025-02-09,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient-Party,43.0,0,2
HB-035237,Resort Hotel,0,267,2025,April,15,8,2025-04-08,3,6,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient-Party,54.68,0,0
HB-062024,City Hotel,1,226,2024,December,1,30,2024-12-30,1,2,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,105.0,0,1
HB-089136,City Hotel,0,70,2024,May,19,11,2024-05-11,2,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,9.0,,0,Transient,119.85,0,2
HB-098000,City Hotel,0,71,2024,September,38,19,2024-09-19,1,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,149.4,0,2
HB-014239,Resort Hotel,0,3,2024,January,3,15,2024-01-15,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,1,A,D,0,No Deposit,,291.0,0,Transient,30.0,0,0
HB-055463,City Hotel,1,225,2024,August,33,13,2024-08-13,2,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.3,0,0
HB-106314,City Hotel,0,48,2025,February,8,22,2025-02-22,0,2,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,65.0,0,1
HB-098172,City Hotel,0,237,2024,September,38,22,2024-09-22,1,3,2,0.0,0,BB,AUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,87.67,0,2
HB-118812,City Hotel,0,42,2025,August,35,26,2025-08-26,0,1,2,0.0,0,BB,PRT,Online TA,Direct,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,170.0,0,3
HB-048001,City Hotel,1,51,2024,March,11,11,2024-03-11,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,54.09,0,0
HB-022295,Resort Hotel,0,6,2024,March,12,22,2024-03-22,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,396.0,0,Transient,40.0,0,0
HB-057913,City Hotel,1,47,2024,October,40,3,2024-10-03,1,2,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,153.0,0,1
HB-079255,City Hotel,1,444,2024,December,48,1,2024-12-01,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,34.0,,39,Transient,75.0,0,0
HB-001111,Resort Hotel,0,6,2023,August,33,14,2023-08-14,2,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,195.8,1,1
HB-037064,Resort Hotel,0,14,2025,May,21,23,2025-05-23,4,10,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,3,No Deposit,250.0,,0,Transient,103.79,0,2
HB-064082,City Hotel,1,47,2025,March,9,1,2025-03-01,0,3,3,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,129.6,0,0
HB-006778,Resort Hotel,0,304,2024,July,27,1,2024-07-01,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,40.0,,0,Contract,59.8,0,1
HB-110895,City Hotel,0,174,2025,April,18,30,2025-04-30,2,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,2
HB-067260,City Hotel,1,113,2025,April,18,30,2025-04-30,2,2,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.75,0,0
HB-045202,City Hotel,0,48,2023,October,43,23,2023-10-23,2,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.5,0,0
HB-097992,City Hotel,0,47,2024,September,38,21,2024-09-21,0,2,1,0.0,0,BB,CHE,Direct,Direct,0,0,0,D,D,2,No Deposit,,,0,Transient,140.0,0,0
HB-030609,Resort Hotel,0,4,2024,November,48,27,2024-11-27,1,0,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,43.0,0,2
HB-117460,City Hotel,0,46,2025,July,31,31,2025-07-31,1,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,145.0,0,1
HB-024029,Resort Hotel,0,58,2024,May,19,8,2024-05-08,2,0,3,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,I,3,No Deposit,393.0,,0,Transient-Party,75.6,0,1
HB-087871,City Hotel,0,11,2024,April,17,23,2024-04-23,2,2,2,1.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,9.0,,0,Transient,141.5,0,2
HB-094755,City Hotel,0,8,2024,August,32,8,2024-08-08,1,0,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,171.0,0,1
HB-068012,City Hotel,1,120,2025,May,19,11,2025-05-11,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,89.1,0,0
HB-091716,City Hotel,0,265,2024,June,26,24,2024-06-24,0,2,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,B,1,No Deposit,6.0,,0,Transient-Party,90.0,0,0
HB-000450,Resort Hotel,0,10,2023,July,28,16,2023-07-16,2,3,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient-Party,150.2,0,1
HB-113849,City Hotel,0,43,2025,June,24,9,2025-06-09,2,2,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,150.0,0,2
HB-094820,City Hotel,0,122,2024,August,31,1,2024-08-01,3,6,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.5,0,1
HB-055916,City Hotel,1,137,2024,August,34,24,2024-08-24,0,4,3,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.95,0,0
HB-110474,City Hotel,0,93,2025,April,17,24,2025-04-24,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,123.75,0,0
HB-021725,Resort Hotel,0,0,2024,March,10,8,2024-03-08,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,46.0,1,0
HB-086922,City Hotel,0,59,2024,April,15,8,2024-04-08,1,2,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,137.7,0,0
HB-006549,Resort Hotel,1,92,2024,June,25,17,2024-06-17,1,2,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,176.0,0,0
HB-111917,City Hotel,0,1,2025,May,20,17,2025-05-17,0,1,1,0.0,0,SC,ESP,Direct,Direct,0,0,0,A,C,0,No Deposit,,,0,Transient,160.0,0,0
HB-085725,City Hotel,0,0,2024,March,12,20,2024-03-20,0,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,1,0,0,D,K,0,No Deposit,27.0,,0,Transient,0.0,0,0
HB-064110,City Hotel,1,131,2025,March,9,2,2025-03-02,0,1,2,0.0,0,SC,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,2
HB-013496,Resort Hotel,1,245,2025,August,33,17,2025-08-17,2,4,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,E,E,2,No Deposit,240.0,,0,Transient,222.0,0,2
HB-027832,Resort Hotel,0,10,2024,September,36,5,2024-09-05,2,5,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,3,No Deposit,250.0,,0,Transient,188.43,0,0
HB-078161,City Hotel,0,10,2023,October,40,2,2023-10-02,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Contract,186.67,0,2
HB-054049,City Hotel,1,245,2024,July,27,6,2024-07-06,2,4,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,110.0,0,0
HB-115710,City Hotel,0,151,2025,July,28,9,2025-07-09,1,0,2,0.0,0,BB,NZL,Online TA,TA/TO,0,0,0,E,F,0,No Deposit,9.0,,0,Transient,143.1,0,2
HB-071939,City Hotel,1,193,2025,July,29,15,2025-07-15,2,3,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,1
HB-012071,Resort Hotel,1,141,2025,June,24,11,2025-06-11,2,2,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,142.0,0,1
HB-006597,Resort Hotel,1,185,2024,June,25,19,2024-06-19,4,10,3,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,150.57,0,2
HB-082628,City Hotel,0,72,2023,December,51,23,2023-12-23,2,9,2,0.0,0,BB,ROU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,58.91,0,1
HB-023175,Resort Hotel,0,72,2024,April,15,9,2024-04-09,2,6,1,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,96.0,,0,Transient-Party,36.0,0,0
HB-109813,City Hotel,0,8,2025,April,15,13,2025-04-13,1,3,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,185.25,0,1
HB-114711,City Hotel,0,127,2025,June,26,23,2025-06-23,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-003056,Resort Hotel,0,49,2023,November,45,12,2023-11-12,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient-Party,68.0,0,2
HB-076792,City Hotel,1,202,2023,August,33,16,2023-08-16,2,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,2
HB-073408,City Hotel,1,272,2025,August,34,20,2025-08-20,4,5,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.1,0,0
HB-020431,Resort Hotel,0,4,2025,March,10,6,2025-03-06,1,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,12,A,A,0,No Deposit,,269.0,0,Transient,42.0,1,0
HB-057603,City Hotel,1,80,2024,September,39,29,2024-09-29,0,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.1,0,1
HB-067559,City Hotel,1,143,2025,May,18,4,2025-05-04,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,151.0,,0,Transient,100.0,0,0
HB-052864,City Hotel,1,113,2024,June,24,13,2024-06-13,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.85,0,0
HB-039397,Resort Hotel,0,44,2025,August,32,10,2025-08-10,2,5,3,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,196.0,,0,Transient-Party,337.0,0,2
HB-113700,City Hotel,0,39,2025,June,23,8,2025-06-08,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,9.0,,0,Transient,150.0,0,1
HB-033297,Resort Hotel,0,73,2025,February,8,17,2025-02-17,1,2,2,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,498.0,0,Transient-Party,40.0,0,0
HB-012500,Resort Hotel,1,171,2025,July,27,2,2025-07-02,2,1,2,2.0,0,BB,USA,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,180.0,0,0
HB-016023,Resort Hotel,0,67,2023,August,31,1,2023-08-01,4,6,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,191.7,0,1
HB-049582,City Hotel,1,122,2024,April,16,15,2024-04-15,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,151.0,,56,Transient-Party,85.0,0,0
HB-115906,City Hotel,0,48,2025,July,28,9,2025-07-09,2,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,89.1,0,0
HB-110962,City Hotel,0,50,2025,May,18,1,2025-05-01,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,153.0,0,2
HB-091114,City Hotel,0,256,2024,June,24,15,2024-06-15,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-024016,Resort Hotel,0,46,2024,May,19,9,2024-05-09,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,1,No Deposit,250.0,,0,Transient,71.0,1,1
HB-103396,City Hotel,0,345,2024,December,51,20,2024-12-20,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,78.3,0,2
HB-011847,Resort Hotel,1,263,2025,June,22,1,2025-06-01,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,89.0,0,0
HB-055110,City Hotel,1,181,2024,August,31,4,2024-08-04,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,112.2,0,1
HB-069532,City Hotel,1,16,2025,June,22,1,2025-06-01,0,3,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,133.33,0,1
HB-117793,City Hotel,0,64,2025,August,32,4,2025-08-04,2,4,2,2.0,0,BB,BEL,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,8.0,,0,Transient,305.0,0,1
HB-091599,City Hotel,0,6,2024,June,25,23,2024-06-23,0,1,2,0.0,0,BB,CHN,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,99.0,0,2
HB-092492,City Hotel,0,22,2024,July,27,5,2024-07-05,0,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,85.0,0,0
HB-047947,City Hotel,1,60,2024,March,10,10,2024-03-10,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,87.3,0,0
HB-036669,Resort Hotel,0,72,2025,May,21,21,2025-05-21,2,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,241.0,,0,Transient,108.0,0,1
HB-001149,Resort Hotel,0,84,2023,August,33,15,2023-08-15,4,10,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,261.0,,0,Transient,107.0,0,1
HB-075564,City Hotel,0,257,2023,July,26,1,2023-07-01,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,101.5,0,0
HB-052929,City Hotel,1,71,2024,June,24,14,2024-06-14,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,120.0,0,0
HB-044579,City Hotel,0,210,2023,October,40,8,2023-10-08,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,72.75,0,0
HB-020971,Resort Hotel,0,2,2024,February,7,13,2024-02-13,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,65.0,0,1
HB-012249,Resort Hotel,1,125,2025,June,25,19,2025-06-19,2,5,2,2.0,0,BB,NLD,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,153.71,0,2
HB-054860,City Hotel,1,386,2024,July,30,28,2024-07-28,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-014554,Resort Hotel,0,10,2024,December,51,17,2024-12-17,1,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,E,0,No Deposit,,,0,Transient,64.0,0,2
HB-078590,City Hotel,0,0,2024,April,16,18,2024-04-18,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,4,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-020076,Resort Hotel,0,20,2024,January,3,15,2024-01-15,0,1,1,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,241.0,,0,Transient,36.96,0,0
HB-006950,Resort Hotel,1,26,2024,July,28,13,2024-07-13,0,3,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient,169.67,0,1
HB-102081,City Hotel,0,11,2024,November,47,21,2024-11-21,1,1,1,0.0,0,BB,PRT,Direct,Corporate,0,0,0,E,E,1,No Deposit,,,0,Transient,115.0,0,0
HB-045504,City Hotel,1,100,2023,October,44,31,2023-10-31,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-091230,City Hotel,0,2,2024,June,24,13,2024-06-13,1,5,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Transient,90.95,0,0
HB-061936,City Hotel,1,15,2024,December,52,28,2024-12-28,2,5,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.11,0,2
HB-063291,City Hotel,1,25,2025,February,6,5,2025-02-05,2,5,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,0
HB-004449,Resort Hotel,0,167,2024,March,12,18,2024-03-18,4,9,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,33.3,0,0
HB-038522,Resort Hotel,0,9,2025,July,29,14,2025-07-14,2,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,237.71,0,1
HB-014297,Resort Hotel,0,0,2023,November,44,3,2023-11-03,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,1,A,A,0,No Deposit,,,0,Transient,40.0,1,0
HB-115038,City Hotel,0,368,2025,June,26,28,2025-06-28,0,3,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,2
HB-084710,City Hotel,0,0,2024,March,9,2,2024-03-02,0,1,1,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.0,0,0
HB-106067,City Hotel,0,4,2025,February,8,17,2025-02-17,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,28.0,,0,Contract,68.0,0,0
HB-009072,Resort Hotel,1,188,2024,October,43,26,2024-10-26,2,6,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,175.0,,0,Transient,37.2,0,0
HB-031223,Resort Hotel,0,28,2024,December,51,17,2024-12-17,1,1,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,54.0,1,0
HB-037018,Resort Hotel,0,48,2025,June,23,2,2025-06-02,0,2,2,0.0,0,HB,CN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,169.0,0,1
HB-014144,Resort Hotel,0,11,2024,April,16,19,2024-04-19,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,4,A,A,0,No Deposit,,154.0,0,Transient,39.0,0,1
HB-071435,City Hotel,1,357,2025,July,27,5,2025-07-05,0,4,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,89.1,0,1
HB-092914,City Hotel,0,90,2024,July,27,7,2024-07-07,2,5,3,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,159.0,,0,Transient,144.13,0,2
HB-067955,City Hotel,1,6,2025,May,19,10,2025-05-10,0,1,2,0.0,0,BB,PRT,Groups,Corporate,0,0,0,A,A,0,Non Refund,47.0,,0,Transient,90.0,0,0
HB-027437,Resort Hotel,0,18,2024,August,35,26,2024-08-26,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,201.0,0,1
HB-062873,City Hotel,1,59,2025,January,4,23,2025-01-23,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,326.0,,0,Transient,80.0,0,0
HB-018309,Resort Hotel,0,6,2024,December,52,27,2024-12-27,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,16.0,,0,Transient,30.0,0,0
HB-047966,City Hotel,0,65,2024,March,11,11,2024-03-11,0,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,78.3,0,1
HB-002518,Resort Hotel,0,0,2023,October,42,20,2023-10-20,0,1,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,D,D,1,No Deposit,,,0,Transient,56.0,1,0
HB-075986,City Hotel,1,301,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-077290,City Hotel,1,4,2023,September,37,16,2023-09-16,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,147.6,0,1
HB-080683,City Hotel,0,32,2023,November,47,20,2023-11-20,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,119.0,,0,Transient-Party,73.0,0,0
HB-103768,City Hotel,0,6,2024,December,1,30,2024-12-30,0,2,2,1.0,0,BB,THA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,158.0,0,2
HB-025552,Resort Hotel,0,98,2024,June,26,26,2024-06-26,2,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,123.33,0,0
HB-084989,City Hotel,0,29,2024,March,9,2,2024-03-02,1,4,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,87.0,0,0
HB-005846,Resort Hotel,1,9,2024,May,20,15,2024-05-15,1,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,315.0,,0,Transient-Party,70.0,0,0
HB-117825,City Hotel,0,143,2025,August,32,5,2025-08-05,2,3,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,2,No Deposit,14.0,,0,Transient,125.62,0,2
HB-013782,Resort Hotel,1,74,2025,August,35,30,2025-08-30,0,3,2,2.0,0,BB,USA,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,233.33,0,1
HB-086533,City Hotel,0,6,2024,April,14,2,2024-04-02,2,1,3,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,149.33,1,1
HB-107613,City Hotel,0,34,2025,March,11,12,2025-03-12,2,2,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,72.33,0,1
HB-111515,City Hotel,0,307,2025,May,19,11,2025-05-11,0,1,2,0.0,0,BB,MOZ,Offline TA/TO,TA/TO,0,0,0,A,D,2,No Deposit,467.0,,0,Transient-Party,89.1,0,0
HB-007594,Resort Hotel,1,119,2024,August,33,15,2024-08-15,3,6,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient-Party,246.0,0,0
HB-049721,City Hotel,1,57,2024,April,16,18,2024-04-18,1,1,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.3,0,0
HB-102397,City Hotel,0,130,2024,November,48,25,2024-11-25,0,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.0,0,2
HB-097124,City Hotel,0,34,2024,September,37,11,2024-09-11,2,0,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.1,0,2
HB-007427,Resort Hotel,1,157,2024,August,32,8,2024-08-08,1,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,182.0,0,0
HB-042736,City Hotel,0,71,2023,September,36,9,2023-09-09,0,2,1,0.0,0,BB,FRA,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,68.0,0,Transient-Party,90.0,0,0
HB-074956,City Hotel,1,153,2023,August,31,3,2023-08-03,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-007147,Resort Hotel,1,199,2024,July,30,23,2024-07-23,2,6,3,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,210.0,0,0
HB-026089,Resort Hotel,0,127,2024,July,28,14,2024-07-14,2,5,2,2.0,0,HB,PRT,Direct,Direct,0,0,0,C,C,6,No Deposit,250.0,,0,Transient,227.0,0,0
HB-007075,Resort Hotel,1,17,2024,July,29,19,2024-07-19,0,3,2,0.0,0,BB,IND,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,179.0,0,0
HB-030567,Resort Hotel,0,8,2024,November,48,26,2024-11-26,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient-Party,63.0,1,1
HB-079824,City Hotel,0,0,2023,November,44,5,2023-11-05,0,1,2,0.0,0,BB,PRT,Complementary,Direct,0,0,0,G,G,0,No Deposit,,,0,Transient,0.0,0,2
HB-003301,Resort Hotel,1,34,2023,December,49,4,2023-12-04,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,58.0,0,2
HB-003500,Resort Hotel,1,93,2023,December,51,19,2023-12-19,0,1,2,0.0,0,FB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,80.0,0,0
HB-101285,City Hotel,0,27,2024,November,45,7,2024-11-07,1,2,1,0.0,0,BB,BEL,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,361.0,0,Transient-Party,195.0,0,0
HB-016095,Resort Hotel,0,34,2023,August,32,9,2023-08-09,2,4,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,253.0,1,2
HB-093776,City Hotel,0,0,2024,July,30,25,2024-07-25,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,148.0,0,Transient,84.0,0,0
HB-066855,City Hotel,1,96,2025,April,17,26,2025-04-26,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,130.0,0,0
HB-088677,City Hotel,0,0,2024,May,19,9,2024-05-09,1,0,1,0.0,0,SC,RUS,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,42.0,,0,Transient,66.4,0,0
HB-113001,City Hotel,0,102,2025,May,22,27,2025-05-27,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,149.4,0,0
HB-110219,City Hotel,0,73,2025,April,17,21,2025-04-21,1,2,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,89.1,0,1
HB-091355,City Hotel,0,44,2024,June,25,18,2024-06-18,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,6.0,,0,Transient,96.3,0,0
HB-051115,City Hotel,1,76,2024,May,20,13,2024-05-13,2,3,2,0.0,0,BB,HUN,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,119.85,0,0
HB-108710,City Hotel,0,0,2025,March,13,29,2025-03-29,0,2,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,152.0,,0,Transient,58.45,0,0
HB-040646,City Hotel,0,0,2023,August,31,4,2023-08-04,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.0,0,0
HB-011451,Resort Hotel,1,302,2025,May,19,9,2025-05-09,0,4,2,0.0,0,HB,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,81.0,0,0
HB-019726,Resort Hotel,0,112,2023,December,52,30,2023-12-30,0,3,2,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,224.67,0,0
HB-111097,City Hotel,0,159,2025,May,19,6,2025-05-06,2,1,2,0.0,0,SC,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-063373,City Hotel,1,52,2025,February,7,10,2025-02-10,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,122.4,0,2
HB-051051,City Hotel,0,309,2024,May,20,13,2024-05-13,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,215,Transient-Party,65.0,0,0
HB-058922,City Hotel,1,63,2024,October,42,17,2024-10-17,1,3,2,2.0,0,BB,DEU,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,190.8,0,3
HB-114034,City Hotel,0,36,2025,June,24,13,2025-06-13,0,3,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,139.5,0,0
HB-085942,City Hotel,0,0,2024,March,12,24,2024-03-24,0,1,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,B,0,No Deposit,20.0,,0,Transient-Party,75.0,0,0
HB-047161,City Hotel,0,48,2024,February,6,11,2024-02-11,0,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,89.3,0,0
HB-115110,City Hotel,0,261,2025,June,26,29,2025-06-29,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,90.96,0,0
HB-020788,Resort Hotel,0,21,2024,February,6,6,2024-02-06,2,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,2,No Deposit,,,0,Transient,35.0,0,1
HB-007617,Resort Hotel,1,195,2024,August,33,16,2024-08-16,2,8,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,261.0,,0,Transient,124.2,0,0
HB-100735,City Hotel,0,103,2024,October,44,28,2024-10-28,2,2,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,123.3,0,1
HB-109217,City Hotel,0,68,2025,April,14,5,2025-04-05,0,3,1,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,K,1,No Deposit,,418.0,0,Transient-Party,100.0,0,0
HB-040615,City Hotel,1,28,2023,August,31,3,2023-08-03,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-021974,Resort Hotel,0,101,2024,March,10,8,2024-03-08,2,5,2,0.0,0,HB,BEL,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,49.4,0,0
HB-061810,City Hotel,1,90,2024,December,52,26,2024-12-26,1,4,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.74,0,0
HB-038608,Resort Hotel,0,99,2025,July,29,15,2025-07-15,3,6,2,2.0,0,BB,RUS,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,231.22,0,1
HB-017876,Resort Hotel,0,121,2023,October,42,18,2023-10-18,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Transient,43.93,0,0
HB-030102,Resort Hotel,0,167,2024,November,45,9,2024-11-09,1,4,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,87.0,0,1
HB-101569,City Hotel,0,21,2024,November,45,10,2024-11-10,1,3,2,0.0,0,SC,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,59.5,0,0
HB-050405,City Hotel,1,19,2024,April,18,30,2024-04-30,0,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,156.0,0,0
HB-112597,City Hotel,0,208,2025,May,21,24,2025-05-24,0,2,1,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,91.5,0,0
HB-101917,City Hotel,0,53,2024,November,47,18,2024-11-18,0,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-063533,City Hotel,1,52,2025,February,7,13,2025-02-13,1,3,1,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,74.8,0,0
HB-043491,City Hotel,0,77,2023,September,38,18,2023-09-18,2,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.25,0,0
HB-052411,City Hotel,1,163,2024,June,23,5,2024-06-05,2,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,171.0,,0,Transient,100.0,0,0
HB-100546,City Hotel,0,234,2024,October,43,25,2024-10-25,0,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,103.7,0,1
HB-049458,City Hotel,1,281,2024,April,15,14,2024-04-14,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-075208,City Hotel,1,294,2023,August,32,7,2023-08-07,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-079783,City Hotel,0,5,2023,November,44,2,2023-11-02,1,2,1,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,105.0,0,1
HB-094682,City Hotel,0,64,2024,August,32,6,2024-08-06,1,1,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,200.1,0,1
HB-073562,City Hotel,1,518,2025,August,35,26,2025-08-26,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,90.0,0,0
HB-026510,Resort Hotel,0,62,2025,April,16,19,2025-04-19,1,4,1,0.0,0,BB,ITA,Groups,Corporate,1,0,0,A,D,1,No Deposit,,307.0,0,Transient-Party,85.0,1,0
HB-010316,Resort Hotel,1,35,2025,February,9,25,2025-02-25,2,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,171.0,,0,Transient,60.0,0,0
HB-108133,City Hotel,0,47,2025,March,12,19,2025-03-19,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,68.0,0,0
HB-034539,Resort Hotel,0,120,2025,March,13,26,2025-03-26,2,1,1,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,37.0,0,1
HB-026009,Resort Hotel,0,152,2024,July,28,13,2024-07-13,1,4,3,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,242.0,,0,Transient,224.4,1,1
HB-043896,City Hotel,1,35,2023,September,39,25,2023-09-25,2,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-089781,City Hotel,0,8,2024,May,21,25,2024-05-25,0,1,2,0.0,0,SC,TUR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.0,0,0
HB-021977,Resort Hotel,0,0,2024,March,11,14,2024-03-14,1,0,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,47.0,0,Transient,30.0,0,0
HB-115670,City Hotel,0,238,2025,July,27,5,2025-07-05,0,4,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,68.61,0,2
HB-054702,City Hotel,1,75,2024,July,30,23,2024-07-23,2,5,2,1.0,0,BB,HUN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,123.3,0,0
HB-037873,Resort Hotel,0,20,2025,June,26,29,2025-06-29,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,168.0,,0,Transient,120.0,0,0
HB-068561,City Hotel,1,105,2025,May,21,19,2025-05-19,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-063492,City Hotel,1,67,2025,February,7,12,2025-02-12,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,80.0,0,0
HB-084336,City Hotel,0,17,2024,February,8,21,2024-02-21,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,87.0,0,0
HB-030544,Resort Hotel,0,67,2024,November,46,13,2024-11-13,4,9,2,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,E,E,2,No Deposit,240.0,,0,Transient,57.65,0,1
HB-079464,City Hotel,1,137,2024,January,4,27,2024-01-27,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,29.0,,45,Transient,70.0,0,0
HB-052268,City Hotel,1,130,2024,June,22,2,2024-06-02,0,3,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,116.1,0,0
HB-036960,Resort Hotel,0,137,2025,May,22,27,2025-05-27,2,5,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,49.95,0,1
HB-012684,Resort Hotel,1,234,2025,July,28,11,2025-07-11,2,6,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,218.0,0,2
HB-085967,City Hotel,0,2,2024,March,12,20,2024-03-20,2,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,130.0,0,1
HB-029254,Resort Hotel,0,173,2024,October,42,17,2024-10-17,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,57.0,0,1
HB-087891,City Hotel,0,88,2024,April,18,30,2024-04-30,0,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,1,A,A,0,No Deposit,9.0,,0,Transient-Party,126.9,0,1
HB-039757,Resort Hotel,0,0,2025,August,35,26,2025-08-26,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,1,No Deposit,240.0,,0,Transient,235.0,0,0
HB-114474,City Hotel,0,31,2025,June,25,19,2025-06-19,1,3,2,1.0,0,BB,DEU,Direct,Direct,0,0,0,D,D,1,No Deposit,14.0,,0,Transient,175.0,0,0
HB-080977,City Hotel,0,4,2023,November,48,29,2023-11-29,2,0,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,72.75,1,1
HB-103616,City Hotel,0,41,2024,December,52,27,2024-12-27,0,1,2,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,220.0,,0,Transient-Party,65.0,0,1
HB-026030,Resort Hotel,0,151,2024,July,29,16,2024-07-16,2,1,2,1.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,120.03,0,2
HB-087991,City Hotel,0,44,2024,April,17,27,2024-04-27,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,106.2,0,1
HB-043589,City Hotel,0,13,2023,September,38,20,2023-09-20,2,3,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,87.78,0,1
HB-059254,City Hotel,1,164,2024,October,43,24,2024-10-24,1,2,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,100.2,0,0
HB-015397,Resort Hotel,0,135,2023,July,27,8,2023-07-08,1,4,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,156.0,,0,Contract,55.68,0,0
HB-096203,City Hotel,0,8,2024,October,40,6,2024-10-06,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,1
HB-067524,City Hotel,1,143,2025,May,18,4,2025-05-04,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,56.0,,0,Transient,110.0,0,0
HB-014921,Resort Hotel,1,355,2024,December,49,7,2024-12-07,0,4,1,0.0,0,BB,PRT,Online TA,Direct,1,2,10,A,A,1,No Deposit,,,0,Transient,38.0,0,4
HB-102185,City Hotel,0,16,2024,November,47,23,2024-11-23,0,1,2,1.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,70.41,0,0
HB-080201,City Hotel,1,32,2023,December,49,8,2023-12-08,4,10,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,B,B,0,No Deposit,8.0,,0,Transient,90.35,0,1
HB-086801,City Hotel,0,36,2024,April,15,8,2024-04-08,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,B,1,No Deposit,9.0,,0,Transient-Party,103.95,1,0
HB-067341,City Hotel,1,201,2025,May,18,1,2025-05-01,3,5,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,149.4,0,1
HB-055342,City Hotel,1,398,2024,August,32,11,2024-08-11,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-064348,City Hotel,1,44,2025,March,10,6,2025-03-06,1,4,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,2
HB-100610,City Hotel,0,199,2024,October,44,28,2024-10-28,0,2,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,29.0,,0,Transient-Party,95.0,0,0
HB-084483,City Hotel,0,1,2024,February,9,26,2024-02-26,0,1,3,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,127.0,0,0
HB-063065,City Hotel,1,30,2025,January,5,28,2025-01-28,2,1,2,1.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.33,0,0
HB-006476,Resort Hotel,1,277,2024,June,24,12,2024-06-12,2,2,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-068952,City Hotel,1,284,2025,May,21,23,2025-05-23,0,5,2,1.0,0,BB,BGR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,134.55,0,3
HB-001717,Resort Hotel,0,111,2023,September,36,10,2023-09-10,2,7,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,101.5,0,0
HB-014255,Resort Hotel,0,151,2023,August,31,4,2023-08-04,2,8,2,0.0,0,HB,,Direct,Direct,0,0,0,A,A,2,No Deposit,,,0,Transient,147.0,0,1
HB-008570,Resort Hotel,0,383,2024,October,40,6,2024-10-06,0,3,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,D,0,No Deposit,315.0,,0,Transient-Party,48.0,0,0
HB-079695,City Hotel,0,37,2024,March,11,13,2024-03-13,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,2,A,A,0,No Deposit,,40.0,0,Transient-Party,67.0,1,0
HB-093884,City Hotel,0,148,2024,July,30,23,2024-07-23,2,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,A,0,No Deposit,22.0,,0,Transient,82.45,0,0
HB-081558,City Hotel,1,223,2024,June,24,14,2024-06-14,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,133.0,,40,Transient,135.0,0,0
HB-112542,City Hotel,0,192,2025,May,21,23,2025-05-23,0,2,2,0.0,0,BB,ISR,Direct,Direct,0,0,0,A,D,2,No Deposit,14.0,,0,Transient,117.1,1,2
HB-004898,Resort Hotel,1,31,2024,April,14,7,2024-04-07,0,3,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,67.0,,0,Transient-Party,68.0,0,0
HB-061931,City Hotel,1,237,2024,December,52,28,2024-12-28,2,5,2,1.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.26,0,0
HB-010387,Resort Hotel,1,21,2025,March,9,2,2025-03-02,0,3,2,0.0,0,HB,BEL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,112.0,0,1
HB-052404,City Hotel,1,163,2024,June,23,5,2024-06-05,2,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,171.0,,0,Transient,100.0,0,0
HB-090558,City Hotel,0,247,2024,June,23,6,2024-06-06,1,1,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-018995,Resort Hotel,0,2,2023,December,48,2,2023-12-02,0,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,54.0,1,0
HB-017934,Resort Hotel,0,48,2023,October,42,21,2023-10-21,2,5,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,86.0,0,3
HB-067079,City Hotel,1,209,2025,April,18,28,2025-04-28,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.5,0,2
HB-038046,Resort Hotel,0,164,2025,July,27,1,2025-07-01,2,5,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,D,D,1,No Deposit,,,0,Transient,121.43,1,1
HB-062073,City Hotel,1,46,2025,January,1,1,2025-01-01,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,65.0,0,0
HB-027144,Resort Hotel,0,17,2024,August,33,16,2024-08-16,0,5,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,311.0,0,1
HB-071239,City Hotel,1,354,2025,June,27,30,2025-06-30,0,1,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,0
HB-007277,Resort Hotel,0,285,2024,August,31,1,2024-08-01,1,3,2,2.0,0,BB,PRT,Direct,Direct,0,0,0,G,G,0,No Deposit,,,0,Transient,165.25,0,1
HB-023458,Resort Hotel,0,41,2024,April,17,23,2024-04-23,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,74.67,1,1
HB-055974,City Hotel,1,179,2024,August,34,25,2024-08-25,1,3,2,1.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,98.25,0,1
HB-001364,Resort Hotel,1,93,2023,August,34,26,2023-08-26,1,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,192.2,0,0
HB-056413,City Hotel,1,49,2024,September,36,5,2024-09-05,1,2,1,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,115.5,0,1
HB-016705,Resort Hotel,0,244,2023,September,35,2,2023-09-02,2,5,2,0.0,0,BB,IRL,Groups,TA/TO,0,0,0,A,A,0,No Deposit,96.0,,0,Transient-Party,57.0,0,0
HB-063961,City Hotel,1,134,2025,February,9,25,2025-02-25,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,75.0,0,0
HB-089158,City Hotel,0,49,2024,May,20,13,2024-05-13,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,140.4,0,1
HB-051820,City Hotel,1,323,2024,May,21,26,2024-05-26,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-100789,City Hotel,0,226,2024,October,44,29,2024-10-29,2,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,3.0,,0,Transient-Party,70.0,0,1
HB-107418,City Hotel,0,43,2025,March,11,10,2025-03-10,1,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,114.07,0,0
HB-108678,City Hotel,0,67,2025,March,13,26,2025-03-26,2,3,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,16.0,,0,Transient,95.2,0,1
HB-009194,Resort Hotel,1,378,2024,November,44,1,2024-11-01,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,248.0,,0,Transient,46.0,0,0
HB-023384,Resort Hotel,0,1,2024,April,17,23,2024-04-23,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,87.0,0,0
HB-081105,City Hotel,1,82,2024,February,5,2,2024-02-02,0,5,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,21,Transient,96.0,0,0
HB-012430,Resort Hotel,1,201,2025,June,26,29,2025-06-29,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient,110.0,0,1
HB-006973,Resort Hotel,1,63,2024,July,29,15,2024-07-15,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,177.5,0,0
HB-049665,City Hotel,1,275,2024,April,16,17,2024-04-17,2,0,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,0,Transient,110.0,0,0
HB-020776,Resort Hotel,0,23,2024,February,6,6,2024-02-06,2,1,2,1.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,15.0,,0,Transient,68.75,0,2
HB-113171,City Hotel,0,82,2025,May,22,31,2025-05-31,0,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,153.0,0,2
HB-071214,City Hotel,1,96,2025,June,26,29,2025-06-29,2,3,1,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,0
HB-090628,City Hotel,0,16,2024,June,23,8,2024-06-08,0,1,2,0.0,0,BB,TUR,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,92.65,0,0
HB-059485,City Hotel,1,247,2024,October,44,28,2024-10-28,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,110.0,0,0
HB-109684,City Hotel,0,0,2025,April,15,13,2025-04-13,0,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,425.0,,0,Transient,123.0,0,0
HB-100164,City Hotel,0,96,2024,October,42,19,2024-10-19,1,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,132.3,0,2
HB-019227,Resort Hotel,1,92,2024,February,9,26,2024-02-26,1,2,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,134.0,,0,Transient,79.0,0,0
HB-040734,City Hotel,0,83,2023,August,31,5,2023-08-05,1,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient-Party,85.5,1,1
HB-062173,City Hotel,1,64,2025,January,1,3,2025-01-03,0,4,2,1.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.4,0,2
HB-088642,City Hotel,0,49,2024,May,19,9,2024-05-09,1,0,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,121.5,0,1
HB-023267,Resort Hotel,0,32,2024,April,16,19,2024-04-19,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,G,0,No Deposit,,397.0,0,Transient-Party,59.0,0,1
HB-117984,City Hotel,0,101,2025,August,31,3,2025-08-03,2,8,1,0.0,0,HB,FRA,Direct,Direct,0,0,0,A,A,3,No Deposit,14.0,,0,Transient,130.5,0,2
HB-062423,City Hotel,1,277,2025,January,3,13,2025-01-13,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,59.91,0,0
HB-011994,Resort Hotel,1,304,2025,June,23,8,2025-06-08,2,3,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,298.0,,0,Transient,66.0,0,0
HB-046807,City Hotel,0,151,2024,January,3,19,2024-01-19,0,3,1,0.0,0,BB,SVN,Offline TA/TO,TA/TO,0,0,0,A,D,3,No Deposit,19.0,,63,Transient-Party,71.0,0,0
HB-104207,City Hotel,0,14,2025,January,2,6,2025-01-06,0,2,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,106.0,0,3
HB-028434,Resort Hotel,0,542,2024,September,39,26,2024-09-26,2,5,2,0.0,0,HB,NZL,Groups,TA/TO,0,0,0,A,A,0,No Deposit,253.0,,0,Transient-Party,68.0,0,1
HB-114127,City Hotel,0,47,2025,June,24,15,2025-06-15,0,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.0,0,1
HB-105897,City Hotel,0,12,2025,February,7,15,2025-02-15,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,75.0,0,1
HB-076744,City Hotel,1,327,2023,September,36,9,2023-09-09,2,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,4.0,,0,Transient-Party,76.0,0,0
HB-111731,City Hotel,0,221,2025,May,19,11,2025-05-11,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,138.6,0,1
HB-068410,City Hotel,1,32,2025,May,20,17,2025-05-17,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,185.0,0,0
HB-092333,City Hotel,0,136,2024,June,26,28,2024-06-28,2,5,2,0.0,0,SC,DNK,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,80.75,0,0
HB-032238,Resort Hotel,0,41,2025,January,3,17,2025-01-17,0,2,1,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,A,D,1,No Deposit,,,0,Transient-Party,55.0,0,0
HB-073719,City Hotel,1,258,2023,July,26,2,2023-07-02,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-104675,City Hotel,0,1,2025,January,3,17,2025-01-17,0,3,1,0.0,0,BB,CZE,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient,75.0,0,0
HB-052844,City Hotel,1,160,2024,June,24,12,2024-06-12,2,2,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient-Party,103.22,0,1
HB-045957,City Hotel,1,104,2023,December,48,3,2023-12-03,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,55.0,,0,Transient,75.0,0,0
HB-089651,City Hotel,0,11,2024,May,19,9,2024-05-09,5,10,1,0.0,0,BB,FRA,Aviation,Corporate,0,0,0,A,A,0,No Deposit,,153.0,0,Transient,95.0,0,0
HB-111383,City Hotel,0,0,2025,May,19,9,2025-05-09,0,1,1,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,9.0,,0,Transient,130.0,0,1
HB-003947,Resort Hotel,1,103,2024,February,6,9,2024-02-09,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,332.0,,0,Transient-Party,50.0,0,0
HB-042343,City Hotel,0,7,2023,September,36,5,2023-09-05,0,1,2,0.0,0,SC,AUT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,115.0,0,2
HB-063153,City Hotel,1,56,2025,February,5,1,2025-02-01,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,60.0,0,0
HB-070454,City Hotel,1,44,2025,June,25,17,2025-06-17,2,1,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,1
HB-021810,Resort Hotel,0,81,2024,March,10,9,2024-03-09,0,3,1,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,A,A,1,No Deposit,115.0,,0,Transient-Party,49.0,0,0
HB-078818,City Hotel,0,29,2023,October,41,13,2023-10-13,0,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,96.3,0,1
HB-092596,City Hotel,0,77,2024,July,27,4,2024-07-04,1,4,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,159.3,1,2
HB-113507,City Hotel,0,34,2025,June,23,5,2025-06-05,1,2,2,0.0,0,SC,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,89.0,0,0
HB-104735,City Hotel,0,36,2025,January,3,18,2025-01-18,0,3,2,0.0,0,BB,CYP,Groups,TA/TO,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,75.0,0,1
HB-024134,Resort Hotel,0,119,2024,May,19,12,2024-05-12,0,1,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,G,0,No Deposit,251.0,,0,Transient,59.0,0,1
HB-001311,Resort Hotel,0,62,2023,August,34,23,2023-08-23,2,5,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,156.0,,0,Transient,101.65,0,0
HB-064297,City Hotel,1,28,2025,March,10,4,2025-03-04,2,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,101.51,0,0
HB-009945,Resort Hotel,1,17,2025,January,5,28,2025-01-28,0,1,1,0.0,0,BB,PRT,Groups,Corporate,0,0,0,A,A,0,Non Refund,,504.0,0,Transient-Party,32.0,0,0
HB-087029,City Hotel,0,55,2024,April,15,12,2024-04-12,0,1,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient-Party,94.5,0,0
HB-042746,City Hotel,0,1,2023,September,36,9,2023-09-09,0,3,1,0.0,0,BB,FRA,Corporate,Corporate,0,0,0,A,D,1,No Deposit,,68.0,0,Transient-Party,90.0,0,0
HB-100547,City Hotel,0,85,2024,October,43,25,2024-10-25,0,4,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,104.4,0,2
HB-077697,City Hotel,0,0,2023,September,38,23,2023-09-23,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,F,0,No Deposit,,,0,Transient,152.0,0,2
HB-048477,City Hotel,1,38,2024,March,12,24,2024-03-24,0,3,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,133.8,0,0
HB-111782,City Hotel,0,191,2025,May,20,12,2025-05-12,1,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,137.1,0,1
HB-012218,Resort Hotel,1,135,2025,June,25,18,2025-06-18,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,112.0,0,1
HB-070615,City Hotel,1,210,2025,June,25,19,2025-06-19,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,154.0,,0,Transient,130.0,0,0
HB-104650,City Hotel,0,0,2025,January,3,17,2025-01-17,0,2,1,0.0,0,BB,AUT,Aviation,Corporate,0,0,0,D,D,0,No Deposit,,153.0,0,Transient,95.0,0,1
HB-014525,Resort Hotel,0,0,2024,March,13,30,2024-03-30,0,2,2,0.0,0,BB,,Direct,Direct,0,0,4,F,F,0,No Deposit,,,0,Transient,82.35,0,1
HB-015242,Resort Hotel,0,0,2025,March,13,29,2025-03-29,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,9,A,D,0,No Deposit,,47.0,0,Transient,35.0,1,0
HB-009409,Resort Hotel,1,48,2024,November,48,25,2024-11-25,1,2,2,2.0,0,BB,SWE,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,82.0,0,0
HB-045360,City Hotel,0,73,2023,October,43,26,2023-10-26,1,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,89.25,0,1
HB-015047,Resort Hotel,0,0,2023,November,45,12,2023-11-12,0,1,1,0.0,0,BB,PRT,Direct,Direct,1,0,1,A,F,0,No Deposit,,,0,Transient,45.0,0,1
HB-012408,Resort Hotel,1,309,2025,June,26,27,2025-06-27,2,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,147.0,,0,Transient,91.67,0,0
HB-007733,Resort Hotel,1,80,2024,August,34,23,2024-08-23,0,2,2,0.0,0,BB,URY,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,209.0,0,0
HB-089041,City Hotel,0,81,2024,May,20,15,2024-05-15,2,0,2,0.0,0,BB,CN,Groups,TA/TO,0,0,0,A,A,0,No Deposit,133.0,,0,Transient-Party,90.0,0,1
HB-014992,Resort Hotel,1,166,2023,July,28,15,2023-07-15,0,2,2,0.0,0,FB,PRT,Groups,TA/TO,0,24,0,A,A,0,Non Refund,,,0,Transient,121.5,0,0
HB-068054,City Hotel,1,128,2025,May,20,12,2025-05-12,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,1
HB-113629,City Hotel,0,118,2025,June,23,8,2025-06-08,0,2,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,126.0,0,1
HB-093111,City Hotel,0,37,2024,July,28,13,2024-07-13,0,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.9,0,2
HB-063656,City Hotel,1,87,2025,February,8,17,2025-02-17,0,2,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,71.28,0,0
HB-020637,Resort Hotel,0,2,2024,February,6,5,2024-02-05,0,2,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,D,D,1,No Deposit,250.0,,0,Transient,60.0,1,0
HB-044019,City Hotel,0,68,2023,September,39,29,2023-09-29,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,20.0,,0,Transient-Party,65.0,0,0
HB-113879,City Hotel,0,16,2025,June,24,12,2025-06-12,1,0,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,1
HB-071527,City Hotel,1,178,2025,July,28,7,2025-07-07,0,2,2,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,143.1,0,0
HB-005801,Resort Hotel,0,211,2024,May,20,14,2024-05-14,1,1,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,85.0,0,0
HB-018566,Resort Hotel,0,105,2023,November,46,18,2023-11-18,2,4,2,0.0,0,Undefined,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,313.0,,65,Transient-Party,69.0,0,0
HB-066222,City Hotel,1,87,2025,April,16,15,2025-04-15,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,95.0,0,0
HB-068735,City Hotel,1,420,2025,May,21,20,2025-05-20,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-110487,City Hotel,0,102,2025,April,17,24,2025-04-24,1,3,2,0.0,0,BB,IRL,Groups,TA/TO,0,0,0,A,C,0,No Deposit,,424.0,0,Transient-Party,100.0,0,0
HB-030115,Resort Hotel,0,4,2024,November,46,14,2024-11-14,1,0,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,43.0,0,2
HB-079234,City Hotel,1,444,2024,December,48,1,2024-12-01,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,34.0,,39,Transient,75.0,0,0
HB-000764,Resort Hotel,1,63,2023,July,30,28,2023-07-28,0,3,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,195.0,0,0
HB-093117,City Hotel,0,114,2024,July,28,13,2024-07-13,0,4,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,89.25,0,0
HB-068756,City Hotel,1,25,2025,May,21,20,2025-05-20,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,90.0,0,0
HB-108345,City Hotel,0,116,2025,March,13,24,2025-03-24,0,2,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,1,No Deposit,171.0,,0,Transient-Party,100.0,0,1
HB-035302,Resort Hotel,0,0,2025,April,16,18,2025-04-18,0,1,2,0.0,0,BB,BRA,Direct,TA/TO,1,0,0,D,D,0,No Deposit,,,0,Transient,101.0,0,2
HB-037179,Resort Hotel,0,319,2025,June,23,3,2025-06-03,2,5,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,A,A,4,No Deposit,250.0,,0,Transient,74.25,0,0
HB-077413,City Hotel,0,19,2023,October,40,6,2023-10-06,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,1,0,0,A,A,0,No Deposit,82.0,,0,Transient-Party,90.0,0,0
HB-018282,Resort Hotel,0,24,2023,November,44,3,2023-11-03,3,10,2,0.0,0,BB,FRA,Corporate,Corporate,0,0,0,A,A,2,No Deposit,334.0,281.0,0,Transient-Party,48.0,0,0
HB-050707,City Hotel,1,15,2024,May,19,6,2024-05-06,0,1,2,2.0,0,BB,BEL,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,221.0,0,0
HB-107306,City Hotel,0,63,2025,March,11,10,2025-03-10,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,3,No Deposit,14.0,,0,Transient,79.2,0,0
HB-016348,Resort Hotel,0,117,2023,August,33,18,2023-08-18,2,5,2,1.0,0,FB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,5.0,,0,Transient-Party,219.0,0,2
HB-104381,City Hotel,0,4,2025,January,2,10,2025-01-10,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,405.0,0,Transient-Party,79.0,0,0
HB-013897,Resort Hotel,0,2,2023,November,44,5,2023-11-05,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,1,2,A,E,2,No Deposit,,81.0,0,Transient,46.0,1,2
HB-021563,Resort Hotel,0,1,2024,March,9,2,2024-03-02,0,2,2,1.0,0,BB,CN,Direct,Direct,0,0,0,E,F,2,No Deposit,,,0,Transient,80.0,0,0
HB-013829,Resort Hotel,0,5,2024,March,10,8,2024-03-08,0,2,1,0.0,0,BB,,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,94.0,0,Transient,27.0,1,0
HB-062552,City Hotel,1,18,2025,January,3,14,2025-01-14,1,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,147.5,0,1
HB-069587,City Hotel,1,246,2025,June,23,2,2025-06-02,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,154.0,,117,Transient,130.0,0,0
HB-074924,City Hotel,1,136,2023,July,29,17,2023-07-17,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient,60.0,0,0
HB-004137,Resort Hotel,1,118,2024,February,7,15,2024-02-15,3,6,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,26.1,0,0
HB-016770,Resort Hotel,1,221,2023,October,41,10,2023-10-10,1,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,208.0,,0,Transient,34.0,0,0
HB-068525,City Hotel,1,175,2025,May,21,19,2025-05-19,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,44.0,,0,Transient,90.0,0,0
HB-019302,Resort Hotel,0,16,2023,December,50,11,2023-12-11,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,52.4,1,1
HB-104803,City Hotel,0,58,2025,January,3,15,2025-01-15,3,5,3,0.0,0,BB,CYP,Groups,TA/TO,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,100.0,0,2
HB-002553,Resort Hotel,0,160,2023,October,42,21,2023-10-21,2,5,1,0.0,0,BB,FIN,Direct,Direct,0,0,0,A,D,1,No Deposit,,,0,Transient,47.0,0,0
HB-070708,City Hotel,1,153,2025,June,25,21,2025-06-21,0,4,1,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,A,0,Non Refund,,348.0,0,Transient,110.0,0,0
HB-060322,City Hotel,1,626,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-062039,City Hotel,1,215,2024,December,1,30,2024-12-30,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,94.35,0,1
HB-112743,City Hotel,0,165,2025,May,21,25,2025-05-25,0,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,2
HB-001136,Resort Hotel,1,72,2023,August,33,15,2023-08-15,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,6.0,,0,Transient,149.0,0,0
HB-078194,City Hotel,0,19,2023,October,40,3,2023-10-03,2,1,3,0.0,0,BB,CMR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,15.0,,0,Transient,118.67,0,1
HB-000402,Resort Hotel,1,96,2023,July,28,14,2023-07-14,2,7,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,96.9,0,1
HB-003017,Resort Hotel,1,40,2023,November,45,11,2023-11-11,0,4,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,281.0,,0,Transient-Party,40.0,0,0
HB-075921,City Hotel,1,180,2023,July,29,19,2023-07-19,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,1,No Deposit,9.0,,0,Transient,76.5,0,2
HB-000777,Resort Hotel,0,30,2023,July,30,29,2023-07-29,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,240.0,,0,Transient,146.0,1,2
HB-101206,City Hotel,0,38,2024,November,45,4,2024-11-04,2,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,120.91,0,2
HB-079822,City Hotel,0,23,2023,November,44,5,2023-11-05,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-034572,Resort Hotel,0,48,2025,March,12,23,2025-03-23,2,5,2,0.0,0,Undefined,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,464.0,,0,Transient,66.0,0,0
HB-085596,City Hotel,0,7,2024,March,11,14,2024-03-14,1,3,2,0.0,0,BB,HUN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,124.0,0,1
HB-012277,Resort Hotel,1,28,2025,June,25,22,2025-06-22,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,106.4,0,1
HB-112257,City Hotel,0,12,2025,May,21,20,2025-05-20,1,1,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,119.0,0,1
HB-089821,City Hotel,0,8,2024,May,21,25,2024-05-25,0,1,1,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.25,0,1
HB-090525,City Hotel,0,0,2024,June,23,7,2024-06-07,0,1,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.0,0,0
HB-091925,City Hotel,0,190,2024,June,25,22,2024-06-22,1,4,1,0.0,0,BB,SRB,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,34.0,,0,Transient-Party,95.0,0,0
HB-066404,City Hotel,1,69,2025,April,16,19,2025-04-19,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,390.0,,0,Transient-Party,100.0,0,0
HB-019179,Resort Hotel,0,1,2023,December,49,9,2023-12-09,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,250.0,,0,Transient,43.0,0,0
HB-059560,City Hotel,1,54,2024,October,44,29,2024-10-29,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,132.0,,0,Transient,95.0,0,1
HB-019855,Resort Hotel,0,2,2024,February,7,17,2024-02-17,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,D,0,No Deposit,159.0,,0,Transient,25.0,0,0
HB-079665,City Hotel,0,8,2023,October,44,31,2023-10-31,0,1,2,2.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient,64.0,0,0
HB-059361,City Hotel,1,475,2024,October,43,27,2024-10-27,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-012721,Resort Hotel,1,135,2025,July,29,14,2025-07-14,1,2,2,2.0,0,BB,USA,Direct,Direct,0,0,0,C,C,0,No Deposit,250.0,,0,Transient,198.33,0,2
HB-083641,City Hotel,0,12,2024,February,6,7,2024-02-07,2,0,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,0,No Deposit,14.0,,0,Transient,136.5,0,1
HB-100332,City Hotel,0,188,2024,October,43,24,2024-10-24,1,2,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,94.14,0,1
HB-019570,Resort Hotel,1,16,2024,April,16,20,2024-04-20,1,4,1,0.0,0,BB,PRT,Direct,TA/TO,1,1,1,E,E,1,No Deposit,,,0,Transient,89.1,0,0
HB-119143,City Hotel,0,216,2025,August,35,26,2025-08-26,2,2,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,93.6,0,0
HB-010634,Resort Hotel,1,340,2025,March,13,24,2025-03-24,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,11.0,,0,Transient,30.0,0,0
HB-085687,City Hotel,0,67,2024,March,11,17,2024-03-17,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,108.3,1,0
HB-029998,Resort Hotel,0,104,2024,November,45,5,2024-11-05,2,5,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient-Party,54.0,0,1
HB-025025,Resort Hotel,0,93,2024,June,24,10,2024-06-10,0,2,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,6,No Deposit,240.0,,0,Transient-Party,166.0,0,0
HB-103339,City Hotel,0,45,2024,December,51,18,2024-12-18,2,0,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,0
HB-104500,City Hotel,0,0,2025,January,3,14,2025-01-14,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient,75.0,0,0
HB-025894,Resort Hotel,0,164,2024,July,27,1,2024-07-01,4,10,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,75.0,,0,Contract,105.4,0,0
HB-097228,City Hotel,0,191,2024,September,36,7,2024-09-07,2,5,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,16.0,,0,Transient,80.75,0,1
HB-008883,Resort Hotel,1,18,2024,October,42,18,2024-10-18,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,72.0,0,3
HB-056188,City Hotel,1,66,2024,August,35,31,2024-08-31,0,4,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.6,0,0
HB-085493,City Hotel,0,64,2024,March,11,12,2024-03-12,2,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,46.4,0,0
HB-072920,City Hotel,1,41,2025,August,32,9,2025-08-09,1,4,1,0.0,0,SC,IND,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,142.0,0,0
HB-023532,Resort Hotel,0,2,2024,April,17,26,2024-04-26,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient-Party,77.0,1,0
HB-003978,Resort Hotel,1,64,2024,February,6,11,2024-02-11,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,15.0,,0,Transient,29.0,0,0
HB-061760,City Hotel,1,294,2024,December,52,26,2024-12-26,1,0,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,112.5,0,0
HB-116792,City Hotel,0,31,2025,July,30,23,2025-07-23,2,0,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,170.0,0,1
HB-051784,City Hotel,0,144,2024,May,21,25,2024-05-25,1,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,92.55,0,0
HB-005240,Resort Hotel,1,83,2024,April,17,22,2024-04-22,2,5,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,71.0,,0,Transient,46.0,0,0
HB-068505,City Hotel,1,175,2025,May,21,19,2025-05-19,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,44.0,,0,Transient,90.0,0,0
HB-072868,City Hotel,1,478,2025,August,32,8,2025-08-08,0,4,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,C,2,No Deposit,229.0,,0,Transient-Party,88.5,0,0
HB-093820,City Hotel,0,68,2024,July,30,23,2024-07-23,2,2,2,0.0,0,BB,CN,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,89.25,0,1
HB-043312,City Hotel,1,72,2023,September,38,18,2023-09-18,0,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,108.0,0,0
HB-014839,Resort Hotel,1,222,2023,September,37,15,2023-09-15,1,5,2,0.0,0,FB,PRT,Groups,Corporate,0,25,0,A,A,0,Non Refund,252.0,,0,Transient,38.0,0,0
HB-025062,Resort Hotel,0,104,2024,June,24,12,2024-06-12,1,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,251.0,,0,Transient-Party,78.0,0,1
HB-036852,Resort Hotel,0,4,2025,May,22,28,2025-05-28,2,1,2,0.0,0,BB,CUB,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,240.0,,0,Transient,90.0,0,2
HB-096248,City Hotel,0,4,2024,August,35,29,2024-08-29,1,1,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,80.0,0,0
HB-015734,Resort Hotel,0,11,2023,July,30,24,2023-07-24,2,6,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,,0,Transient,194.0,0,0
HB-082835,City Hotel,1,68,2024,February,7,17,2024-02-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,37.0,,0,Transient,75.0,0,0
HB-044161,City Hotel,0,65,2023,October,40,2,2023-10-02,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,B,0,No Deposit,19.0,,59,Transient-Party,100.0,0,0
HB-007440,Resort Hotel,1,329,2024,August,32,9,2024-08-09,0,4,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,216.0,0,0
HB-062987,City Hotel,1,61,2025,January,4,25,2025-01-25,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,326.0,,0,Transient,80.0,0,0
HB-008456,Resort Hotel,1,55,2024,September,40,30,2024-09-30,0,2,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,154.0,0,0
HB-079524,City Hotel,1,192,2024,May,18,5,2024-05-05,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,D,D,0,No Deposit,9.0,,0,Transient,115.2,0,1
HB-088841,City Hotel,0,0,2025,February,9,24,2025-02-24,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,1,0,10,A,A,0,No Deposit,9.0,,0,Transient,70.2,0,0
HB-116573,City Hotel,0,15,2025,July,30,21,2025-07-21,0,1,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient-Party,138.0,0,3
HB-051562,City Hotel,1,62,2024,May,21,21,2024-05-21,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,95.88,0,0
HB-075667,City Hotel,1,290,2023,August,31,3,2023-08-03,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-094437,City Hotel,0,84,2024,August,31,1,2024-08-01,1,2,2,1.0,0,BB,GBR,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,169.0,0,1
HB-073075,City Hotel,1,207,2025,August,33,13,2025-08-13,2,5,3,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,199.16,0,3
HB-019765,Resort Hotel,0,116,2025,June,23,3,2025-06-03,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,1,0,2,E,E,0,No Deposit,181.0,,0,Transient,123.0,1,2
HB-021097,Resort Hotel,0,12,2024,February,7,15,2024-02-15,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,68.0,0,0
HB-111187,City Hotel,0,68,2025,May,18,4,2025-05-04,0,3,3,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,216.0,0,1
HB-097268,City Hotel,0,346,2024,September,37,13,2024-09-13,0,2,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,6.0,,0,Transient-Party,90.0,0,0
HB-103720,City Hotel,0,209,2024,December,52,26,2024-12-26,1,3,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,D,D,1,No Deposit,14.0,,0,Transient,84.07,1,0
HB-014434,Resort Hotel,0,25,2025,August,34,22,2025-08-22,0,3,3,0.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,1,No Deposit,,,0,Transient,335.0,0,2
HB-076774,City Hotel,1,395,2024,March,12,21,2024-03-21,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-109418,City Hotel,0,80,2025,April,15,8,2025-04-08,2,1,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,115.0,0,0
HB-046284,City Hotel,0,7,2023,December,52,29,2023-12-29,0,3,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,178.67,1,0
HB-032554,Resort Hotel,0,17,2025,January,5,28,2025-01-28,0,1,2,0.0,0,BB,PRT,Groups,Corporate,0,0,0,A,A,0,Non Refund,,504.0,0,Transient-Party,36.0,0,0
HB-069290,City Hotel,1,0,2025,May,22,29,2025-05-29,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,12.0,0,0
HB-094185,City Hotel,0,301,2024,July,31,30,2024-07-30,1,1,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-036749,Resort Hotel,0,77,2025,May,21,23,2025-05-23,0,5,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,1,No Deposit,250.0,,0,Transient,80.0,0,1
HB-025289,Resort Hotel,0,67,2024,June,25,19,2024-06-19,2,0,2,0.0,0,BB,ARG,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,129.0,0,0
HB-005544,Resort Hotel,1,199,2024,May,18,2,2024-05-02,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,85.0,0,0
HB-051168,City Hotel,1,72,2024,May,20,14,2024-05-14,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.85,0,1
HB-062001,City Hotel,1,45,2024,December,1,30,2024-12-30,0,1,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,167.4,0,0
HB-009118,Resort Hotel,0,16,2024,October,44,28,2024-10-28,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,44.0,1,0
HB-035532,Resort Hotel,0,60,2025,April,16,17,2025-04-17,3,6,1,0.0,0,BB,ITA,Groups,Corporate,0,0,0,A,A,2,No Deposit,,307.0,0,Transient-Party,92.0,0,0
HB-060161,City Hotel,1,277,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-058053,City Hotel,1,275,2024,October,40,5,2024-10-05,1,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,44.0,,0,Transient,90.0,0,0
HB-106925,City Hotel,0,22,2025,March,10,3,2025-03-03,0,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,79.0,0,0
HB-041350,City Hotel,0,6,2023,August,33,14,2023-08-14,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,93.2,0,0
HB-056514,City Hotel,1,426,2024,September,36,8,2024-09-08,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-105416,City Hotel,0,16,2025,February,6,5,2025-02-05,2,1,3,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,150.0,0,0
HB-072060,City Hotel,1,336,2025,July,29,19,2025-07-19,0,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.9,0,0
HB-104688,City Hotel,0,29,2025,January,3,18,2025-01-18,0,3,1,0.0,0,BB,NOR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,171.0,,0,Transient-Party,65.0,0,0
HB-105170,City Hotel,0,0,2025,January,5,30,2025-01-30,1,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,39.6,0,1
HB-065476,City Hotel,1,112,2025,April,14,4,2025-04-04,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,,385.0,0,Transient,95.0,0,0
HB-102137,City Hotel,0,2,2024,November,47,20,2024-11-20,2,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,92.67,0,1
HB-072158,City Hotel,1,150,2025,July,30,22,2025-07-22,2,1,3,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,175.5,0,0
HB-108528,City Hotel,0,158,2025,March,13,27,2025-03-27,1,1,2,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,95.0,0,1
HB-113949,City Hotel,0,29,2025,June,24,14,2025-06-14,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,109.0,0,2
HB-073501,City Hotel,1,185,2025,August,34,24,2025-08-24,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-110260,City Hotel,0,343,2025,April,17,21,2025-04-21,2,2,2,1.0,0,BB,ITA,Direct,Direct,0,0,0,G,G,1,No Deposit,,,0,Transient,213.3,0,2
HB-107462,City Hotel,0,42,2025,March,10,8,2025-03-08,1,4,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,105.0,0,0
HB-061218,City Hotel,1,195,2024,December,49,4,2024-12-04,2,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,72.0,0,0
HB-014090,Resort Hotel,0,1,2025,March,13,29,2025-03-29,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,1,D,D,0,No Deposit,196.0,,0,Transient,85.0,0,1
HB-021806,Resort Hotel,0,81,2024,March,10,9,2024-03-09,0,3,1,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,A,A,1,No Deposit,115.0,,0,Transient-Party,49.0,0,0
HB-050100,City Hotel,1,100,2024,April,17,23,2024-04-23,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,96.0,0,0
HB-068637,City Hotel,1,105,2025,May,21,19,2025-05-19,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-017549,Resort Hotel,0,2,2024,April,16,20,2024-04-20,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,195.0,0,Transient,42.0,0,0
HB-035044,Resort Hotel,0,155,2025,April,15,11,2025-04-11,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,5.0,,0,Transient,50.2,1,0
HB-002419,Resort Hotel,1,334,2023,October,41,12,2023-10-12,2,5,20,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Group,0.0,0,0
HB-108820,City Hotel,0,15,2025,March,14,31,2025-03-31,0,2,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,111.0,0,0
HB-118772,City Hotel,0,142,2025,August,34,24,2025-08-24,0,1,2,0.0,0,BB,USA,Direct,Direct,0,0,0,D,E,1,No Deposit,14.0,,0,Transient,150.0,0,2
HB-115268,City Hotel,0,3,2025,July,27,3,2025-07-03,1,0,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.0,0,1
HB-006705,Resort Hotel,1,226,2024,June,26,25,2024-06-25,2,5,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,G,G,0,No Deposit,250.0,,0,Transient,118.15,0,0
HB-036289,Resort Hotel,0,0,2025,May,20,14,2025-05-14,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,75.0,0,2
HB-068393,City Hotel,1,88,2025,May,20,16,2025-05-16,0,3,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,0
HB-072977,City Hotel,1,118,2025,August,33,11,2025-08-11,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,155.0,0,1
HB-087310,City Hotel,0,33,2024,April,15,14,2024-04-14,1,3,2,0.0,1,BB,ITA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,126.0,0,1
HB-047668,City Hotel,1,116,2024,February,9,28,2024-02-28,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,E,0,No Deposit,134.0,,0,Transient-Party,61.0,0,0
HB-055262,City Hotel,1,11,2024,August,32,9,2024-08-09,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,151.0,0,0
HB-008228,Resort Hotel,1,33,2024,September,38,19,2024-09-19,1,1,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,80.0,0,1
HB-112801,City Hotel,0,179,2025,May,21,25,2025-05-25,1,3,2,0.0,0,SC,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,111.0,0,1
HB-101151,City Hotel,0,44,2024,November,45,4,2024-11-04,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,110.13,0,2
HB-038694,Resort Hotel,0,210,2025,July,30,24,2025-07-24,1,2,2,1.0,0,HB,HUN,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient-Party,218.75,0,1
HB-114612,City Hotel,0,149,2025,June,26,24,2025-06-24,0,1,2,0.0,0,HB,USA,Corporate,Corporate,0,0,0,A,A,1,No Deposit,495.0,,0,Transient-Party,154.0,0,0
HB-053334,City Hotel,1,71,2024,June,25,17,2024-06-17,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,80.75,0,1
HB-054284,City Hotel,1,33,2024,July,28,11,2024-07-11,1,2,2,0.0,0,HB,MAR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,170.1,0,0
HB-073157,City Hotel,1,303,2025,August,33,16,2025-08-16,0,1,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.9,0,1
HB-054346,City Hotel,1,139,2024,July,28,13,2024-07-13,2,7,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,86.92,0,0
HB-081324,City Hotel,0,23,2023,December,49,4,2023-12-04,2,2,2,0.0,0,BB,ESP,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,143.0,0,Transient-Party,50.0,0,0
HB-109568,City Hotel,0,185,2025,April,15,13,2025-04-13,0,1,2,1.0,0,BB,CN,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,189.0,0,2
HB-114638,City Hotel,0,113,2025,June,25,21,2025-06-21,0,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-017204,Resort Hotel,0,46,2023,September,39,30,2023-09-30,2,6,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,A,A,1,No Deposit,171.0,,0,Transient,43.78,0,0
HB-000654,Resort Hotel,0,28,2023,July,30,24,2023-07-24,2,2,2,0.0,0,BB,ALB,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient,107.0,0,0
HB-065995,City Hotel,1,219,2025,April,15,12,2025-04-12,0,4,0,2.0,0,BB,SWE,Direct,Direct,0,0,0,B,B,0,No Deposit,14.0,,0,Transient,101.25,0,0
HB-075122,City Hotel,1,344,2023,September,39,26,2023-09-26,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-113115,City Hotel,0,223,2025,May,22,27,2025-05-27,2,5,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,125.1,0,1
HB-111798,City Hotel,0,94,2025,May,20,13,2025-05-13,2,1,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,147.0,0,2
HB-072775,City Hotel,1,265,2025,August,32,5,2025-08-05,3,6,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,89.1,0,0
HB-118395,City Hotel,0,23,2025,August,34,18,2025-08-18,0,1,3,1.0,0,BB,FRA,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,264.0,1,1
HB-096853,City Hotel,0,37,2024,September,36,5,2024-09-05,1,3,1,1.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,72.91,0,1
HB-025950,Resort Hotel,0,134,2024,July,28,12,2024-07-12,0,5,1,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,240.0,,0,Transient,140.0,0,1
HB-086654,City Hotel,0,55,2024,April,14,6,2024-04-06,0,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,B,0,No Deposit,56.0,,0,Transient-Party,104.0,0,0
HB-021865,Resort Hotel,0,5,2024,March,10,9,2024-03-09,0,3,3,1.0,0,BB,FIN,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient-Party,109.0,1,0
HB-029007,Resort Hotel,0,364,2024,October,41,12,2024-10-12,2,5,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,1,No Deposit,,223.0,0,Transient-Party,66.0,0,0
HB-050392,City Hotel,1,37,2024,April,18,29,2024-04-29,2,2,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.9,0,0
HB-042547,City Hotel,1,28,2023,September,36,7,2023-09-07,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,79.25,0,1
HB-011388,Resort Hotel,1,14,2025,May,19,5,2025-05-05,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,90.0,0,1
HB-063484,City Hotel,1,67,2025,February,7,12,2025-02-12,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,80.0,0,0
HB-027885,Resort Hotel,0,34,2024,September,37,11,2024-09-11,2,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,129.0,0,2
HB-118494,City Hotel,0,0,2025,August,34,20,2025-08-20,1,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,98.0,,0,Transient-Party,115.0,0,0
HB-053737,City Hotel,1,20,2024,June,26,28,2024-06-28,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,156.0,0,1
HB-070595,City Hotel,1,210,2025,June,25,19,2025-06-19,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,154.0,,0,Transient,130.0,0,0
HB-119287,City Hotel,0,177,2025,August,35,27,2025-08-27,2,4,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,175.95,0,1
HB-019249,Resort Hotel,0,1,2024,January,2,14,2024-01-14,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,I,0,No Deposit,,144.0,0,Transient-Party,30.0,1,0
HB-019298,Resort Hotel,0,3,2023,December,50,12,2023-12-12,0,1,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,46.0,1,0
HB-025748,Resort Hotel,0,12,2024,July,27,5,2024-07-05,0,5,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,146.7,0,1
HB-115950,City Hotel,0,59,2025,July,28,10,2025-07-10,1,2,3,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,16.0,,0,Transient,138.0,0,1
HB-047479,City Hotel,1,77,2024,February,8,24,2024-02-24,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,64.0,0,0
HB-038195,Resort Hotel,0,130,2025,July,28,9,2025-07-09,2,0,1,0.0,0,BB,TWN,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,242.0,,0,Transient-Party,160.0,0,1
HB-084405,City Hotel,0,1,2024,February,8,25,2024-02-25,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,71.0,0,0
HB-072394,City Hotel,1,12,2025,July,30,27,2025-07-27,2,5,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,216.86,0,1
HB-000931,Resort Hotel,0,3,2023,August,31,6,2023-08-06,2,4,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,181.5,0,3
HB-089151,City Hotel,0,97,2024,May,20,16,2024-05-16,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,80.75,0,0
HB-039065,Resort Hotel,0,211,2025,August,32,5,2025-08-05,1,1,1,2.0,0,BB,CN,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,180.42,0,2
HB-101252,City Hotel,0,95,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,DNK,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,185.4,0,1
HB-097065,City Hotel,0,33,2024,September,37,10,2024-09-10,1,1,3,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,120.6,0,0
HB-012351,Resort Hotel,1,311,2025,June,26,25,2025-06-25,2,5,2,2.0,0,BB,IRL,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,151.14,0,2
HB-011987,Resort Hotel,1,33,2025,June,23,7,2025-06-07,1,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,140.0,0,1
HB-057657,City Hotel,1,134,2024,September,39,29,2024-09-29,1,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,137.7,0,2
HB-056039,City Hotel,1,226,2024,August,35,27,2024-08-27,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,96.0,0,0
HB-112507,City Hotel,0,60,2025,May,21,21,2025-05-21,2,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,144.0,0,1
HB-027667,Resort Hotel,0,229,2024,September,36,3,2024-09-03,1,1,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,D,D,4,No Deposit,,,0,Transient-Party,115.0,0,1
HB-117363,City Hotel,0,208,2025,August,31,2,2025-08-02,0,1,2,0.0,0,HB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,157.0,0,1
HB-119319,City Hotel,0,160,2025,August,35,29,2025-08-29,0,5,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,153.9,0,0
HB-004013,Resort Hotel,1,140,2024,February,7,12,2024-02-12,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,50.0,0,0
HB-115027,City Hotel,0,0,2025,June,26,29,2025-06-29,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,170.0,0,1
HB-088255,City Hotel,0,162,2024,April,17,28,2024-04-28,2,3,2,1.0,0,BB,ITA,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,107.65,0,0
HB-117236,City Hotel,0,153,2025,July,31,29,2025-07-29,2,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,130.5,0,0
HB-039385,Resort Hotel,0,188,2025,August,33,12,2025-08-12,2,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,E,G,0,No Deposit,240.0,,0,Transient,210.0,0,3
HB-048881,City Hotel,0,89,2024,April,14,1,2024-04-01,0,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,87.3,0,1
HB-033137,Resort Hotel,0,5,2025,February,7,15,2025-02-15,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,C,0,No Deposit,168.0,,0,Transient-Party,30.0,0,0
HB-097590,City Hotel,0,111,2024,September,38,16,2024-09-16,0,2,3,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,9.0,,0,Transient,168.3,0,3
HB-077599,City Hotel,0,8,2023,September,38,20,2023-09-20,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,2
HB-094638,City Hotel,0,107,2024,August,32,5,2024-08-05,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,111.3,0,1
HB-083147,City Hotel,0,0,2024,January,3,20,2024-01-20,0,2,2,0.0,0,BB,ISR,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,89.0,0,0
HB-079820,City Hotel,0,7,2023,November,44,2,2023-11-02,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,95.0,0,1
HB-113605,City Hotel,0,141,2025,June,23,6,2025-06-06,0,3,1,2.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,162.0,0,3
HB-010278,Resort Hotel,1,46,2025,February,9,24,2025-02-24,1,2,2,1.0,0,BB,FRA,Direct,Direct,0,0,0,G,G,0,No Deposit,250.0,,0,Transient,87.0,0,0
HB-034820,Resort Hotel,0,45,2025,April,14,3,2025-04-03,1,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,68.33,0,1
HB-047223,City Hotel,1,4,2024,February,7,12,2024-02-12,2,5,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,128.29,0,1
HB-058527,City Hotel,1,37,2024,October,41,13,2024-10-13,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,95.0,0,0
HB-063097,City Hotel,1,8,2025,January,5,30,2025-01-30,3,5,2,0.0,0,SC,AGO,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,1
HB-104152,City Hotel,0,35,2025,January,1,2,2025-01-02,1,4,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,129.7,1,3
HB-036125,Resort Hotel,0,120,2025,May,19,10,2025-05-10,0,1,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,251.0,,0,Transient,62.0,0,0
HB-073520,City Hotel,1,115,2025,August,35,25,2025-08-25,0,2,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,195.0,0,2
HB-055261,City Hotel,1,200,2024,August,32,9,2024-08-09,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient-Party,72.25,0,1
HB-035884,Resort Hotel,0,1,2025,May,18,4,2025-05-04,0,1,1,0.0,0,BB,AUS,Direct,TA/TO,0,0,0,E,E,0,No Deposit,,,0,Transient,100.0,0,1
HB-071775,City Hotel,1,185,2025,July,28,12,2025-07-12,0,3,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,120.6,0,1
HB-108968,City Hotel,0,3,2025,April,14,3,2025-04-03,1,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,94.0,0,0
HB-087909,City Hotel,0,100,2024,April,17,25,2024-04-25,1,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,10.0,,0,Transient,81.2,0,0
HB-042095,City Hotel,1,145,2023,August,35,31,2023-08-31,1,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,90.0,0,0
HB-057703,City Hotel,1,157,2024,September,40,30,2024-09-30,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,135.9,0,0
HB-002274,Resort Hotel,0,77,2023,October,40,8,2023-10-08,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Contract,50.0,0,0
HB-013109,Resort Hotel,1,189,2025,July,31,31,2025-07-31,2,5,3,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,172.49,0,1
HB-110717,City Hotel,0,27,2025,April,18,28,2025-04-28,1,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,87.4,0,1
HB-072645,City Hotel,1,75,2025,August,31,2,2025-08-02,0,2,2,0.0,0,HB,NOR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,198.0,0,1
HB-078372,City Hotel,0,12,2023,October,40,5,2023-10-05,1,2,1,0.0,0,BB,DZA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-100418,City Hotel,0,123,2024,October,43,21,2024-10-21,2,5,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.24,0,0
HB-076178,City Hotel,1,261,2023,October,42,16,2023-10-16,0,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,6.0,,0,Transient-Party,120.0,0,0
HB-042963,City Hotel,0,168,2023,September,37,11,2023-09-11,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,60.0,0,0
HB-014004,Resort Hotel,0,7,2023,July,28,14,2023-07-14,0,1,1,0.0,0,BB,,Corporate,Corporate,0,0,5,A,C,0,No Deposit,,204.0,0,Transient,134.0,0,1
HB-021998,Resort Hotel,0,5,2024,March,11,14,2024-03-14,1,0,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,44.66,0,1
HB-110011,City Hotel,0,91,2025,April,16,17,2025-04-17,1,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-036877,Resort Hotel,0,34,2025,May,22,29,2025-05-29,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,103.0,1,1
HB-024695,Resort Hotel,0,0,2024,July,31,31,2024-07-31,1,0,2,0.0,0,BB,PRT,Direct,Direct,1,0,1,A,C,0,No Deposit,,,0,Transient,155.0,1,0
HB-065035,City Hotel,1,622,2025,March,12,23,2025-03-23,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,59.0,0,0
HB-032184,Resort Hotel,0,40,2025,January,3,16,2025-01-16,1,2,1,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,55.0,0,0
HB-042554,City Hotel,0,9,2023,September,36,7,2023-09-07,1,1,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,15.0,,0,Group,91.6,0,0
HB-082205,City Hotel,0,95,2023,December,51,18,2023-12-18,2,3,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,67.5,0,2
HB-029879,Resort Hotel,0,17,2024,November,45,5,2024-11-05,2,1,2,0.0,0,BB,LVA,Online TA,TA/TO,0,0,0,A,C,1,No Deposit,314.0,,0,Transient,43.2,0,0
HB-090431,City Hotel,0,191,2024,June,23,3,2024-06-03,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,3.0,,0,Transient-Party,49.5,0,0
HB-063873,City Hotel,1,195,2025,February,9,24,2025-02-24,0,1,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.0,0,1
HB-040067,City Hotel,0,3,2023,July,26,2,2023-07-02,0,3,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,58.67,0,0
HB-059304,City Hotel,1,267,2024,October,43,26,2024-10-26,0,3,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,128.7,0,1
HB-070724,City Hotel,1,212,2025,June,25,21,2025-06-21,0,4,1,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,A,0,Non Refund,,348.0,59,Transient,110.0,0,0
HB-116587,City Hotel,0,142,2025,July,29,19,2025-07-19,0,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,80.1,0,0
HB-102605,City Hotel,0,6,2024,December,48,1,2024-12-01,0,1,1,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,0
HB-075426,City Hotel,1,327,2023,September,36,9,2023-09-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-112110,City Hotel,0,395,2025,May,20,17,2025-05-17,0,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,0
HB-104444,City Hotel,0,28,2025,January,2,12,2025-01-12,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,106.0,0,2
HB-008024,Resort Hotel,1,238,2024,September,36,7,2024-09-07,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,D,D,0,Non Refund,1.0,,0,Transient,89.0,0,0
HB-028205,Resort Hotel,0,131,2024,September,38,19,2024-09-19,1,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,,,0,Transient,152.0,1,1
HB-077416,City Hotel,1,19,2023,October,40,6,2023-10-06,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,1,1,0,A,A,0,No Deposit,82.0,,0,Transient-Party,80.0,0,0
HB-026897,Resort Hotel,0,90,2024,August,32,10,2024-08-10,0,4,1,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,201.0,0,0
HB-115820,City Hotel,0,172,2025,July,28,7,2025-07-07,2,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,0
HB-016812,Resort Hotel,0,246,2023,September,36,7,2023-09-07,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,147.0,,0,Transient,60.51,0,0
HB-119355,City Hotel,0,63,2025,August,35,31,2025-08-31,0,3,3,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,195.33,0,2
HB-097794,City Hotel,0,12,2024,September,38,18,2024-09-18,2,1,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,142.33,0,1
HB-003198,Resort Hotel,0,78,2023,November,47,21,2023-11-21,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,342.0,0,Transient-Party,32.0,0,0
HB-053631,City Hotel,1,27,2024,June,26,26,2024-06-26,2,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,152.67,0,0
HB-008629,Resort Hotel,1,393,2024,October,41,8,2024-10-08,2,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,68.0,,0,Transient,72.0,0,0
HB-007332,Resort Hotel,1,143,2024,August,31,3,2024-08-03,2,5,1,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,211.0,0,0
HB-096250,City Hotel,0,2,2024,August,35,28,2024-08-28,2,1,3,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,123.0,0,1
HB-050045,City Hotel,1,142,2024,April,17,22,2024-04-22,2,3,1,0.0,0,BB,POL,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,89.0,0,0
HB-105302,City Hotel,0,60,2025,February,6,3,2025-02-03,0,2,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,1
HB-083709,City Hotel,0,59,2024,February,6,6,2024-02-06,2,2,3,0.0,0,BB,AUT,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,90.0,0,1
HB-007452,Resort Hotel,1,13,2024,August,32,10,2024-08-10,0,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,261.5,0,0
HB-006452,Resort Hotel,1,277,2024,June,24,12,2024-06-12,2,2,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-064550,City Hotel,1,9,2025,March,11,12,2025-03-12,2,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,102.43,0,0
HB-012167,Resort Hotel,1,110,2025,June,25,16,2025-06-16,2,2,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,158.0,0,0
HB-095760,City Hotel,0,172,2024,August,34,21,2024-08-21,2,1,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,6.0,,0,Transient-Party,82.45,0,1
HB-028724,Resort Hotel,0,223,2024,October,41,9,2024-10-09,1,0,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,E,0,No Deposit,251.0,,0,Transient-Party,59.0,0,1
HB-049806,City Hotel,1,29,2024,April,16,19,2024-04-19,0,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,120.35,0,0
HB-066507,City Hotel,1,130,2025,April,17,21,2025-04-21,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,286.0,,0,Transient,95.0,0,0
HB-092613,City Hotel,0,14,2024,July,28,8,2024-07-08,0,1,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,139.0,0,1
HB-019149,Resort Hotel,0,24,2023,December,49,6,2023-12-06,2,1,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,62.67,1,0
HB-038027,Resort Hotel,0,5,2025,July,27,5,2025-07-05,0,2,2,0.0,0,BB,CN,Direct,Direct,0,0,0,A,D,0,No Deposit,250.0,,0,Transient,169.0,1,0
HB-099664,City Hotel,0,3,2024,October,42,14,2024-10-14,0,2,1,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient-Party,90.0,0,0
HB-052060,City Hotel,1,115,2024,May,22,29,2024-05-29,2,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,132.6,0,1
HB-113906,City Hotel,0,10,2025,June,24,11,2025-06-11,2,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,91.2,0,1
HB-039152,Resort Hotel,0,2,2025,August,32,8,2025-08-08,0,1,3,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,300.0,0,1
HB-003957,Resort Hotel,1,103,2024,February,6,9,2024-02-09,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,332.0,,0,Transient-Party,50.0,0,0
HB-110834,City Hotel,0,29,2025,April,18,28,2025-04-28,2,2,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,123.5,0,3
HB-005445,Resort Hotel,1,108,2024,April,18,29,2024-04-29,2,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,84.0,0,0
HB-064094,City Hotel,1,135,2025,March,9,2,2025-03-02,0,1,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,102.6,0,1
HB-041889,City Hotel,0,2,2023,August,34,26,2023-08-26,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,40.0,,0,Transient,65.0,0,0
HB-025474,Resort Hotel,0,19,2024,June,26,28,2024-06-28,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,10.0,,0,Transient,65.0,1,0
HB-117444,City Hotel,0,6,2025,July,31,31,2025-07-31,1,3,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,2,No Deposit,14.0,,0,Transient,156.76,1,2
HB-002381,Resort Hotel,1,143,2023,October,41,10,2023-10-10,2,5,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,96.0,,0,Transient,36.05,0,0
HB-117755,City Hotel,0,135,2025,August,31,3,2025-08-03,2,4,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,80.1,0,1
HB-056245,City Hotel,1,176,2024,September,35,1,2024-09-01,1,3,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,150.45,0,0
HB-014189,Resort Hotel,0,454,2024,August,35,29,2024-08-29,3,8,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,40.0,,0,Contract,69.58,0,1
HB-109151,City Hotel,0,36,2025,April,14,3,2025-04-03,1,3,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,1
HB-037049,Resort Hotel,0,1,2025,June,22,1,2025-06-01,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,105.0,0,1
HB-065257,City Hotel,1,278,2025,March,13,30,2025-03-30,0,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.6,0,1
HB-081150,City Hotel,0,34,2023,December,48,1,2023-12-01,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,107.0,0,Transient-Party,80.0,0,0
HB-116446,City Hotel,0,59,2025,July,29,17,2025-07-17,1,2,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.0,0,1
HB-038203,Resort Hotel,0,159,2025,July,27,4,2025-07-04,2,6,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,127.5,0,2
HB-047577,City Hotel,1,16,2024,February,9,27,2024-02-27,2,5,1,0.0,0,BB,NGA,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,101.0,0,0
HB-011857,Resort Hotel,1,1,2025,June,23,2,2025-06-02,0,2,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,348.0,,0,Transient,105.0,0,0
HB-026017,Resort Hotel,0,14,2024,July,29,15,2024-07-15,2,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,135.91,0,1
HB-032133,Resort Hotel,0,3,2025,January,3,17,2025-01-17,0,1,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,D,I,0,No Deposit,,,0,Transient,65.0,1,0
HB-064003,City Hotel,1,2,2025,February,9,26,2025-02-26,2,0,2,1.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,184.0,0,1
HB-080158,City Hotel,1,226,2024,June,24,15,2024-06-15,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Contract,139.0,0,1
HB-081697,City Hotel,0,5,2023,December,50,14,2023-12-14,1,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,28.0,,0,Transient,58.0,0,0
HB-118628,City Hotel,0,115,2025,August,34,20,2025-08-20,2,1,2,0.0,0,BB,USA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,98.0,,0,Transient-Party,125.0,0,2
HB-052544,City Hotel,1,56,2024,June,23,8,2024-06-08,0,1,2,0.0,0,BB,PRT,Offline TA/TO,Corporate,0,0,0,A,A,0,No Deposit,191.0,,0,Transient-Party,120.0,0,0
HB-027650,Resort Hotel,0,176,2024,August,35,27,2024-08-27,3,6,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,250.0,,0,Transient,153.1,0,0
HB-064412,City Hotel,1,32,2025,March,10,9,2025-03-09,0,2,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,163.0,0,0
HB-106656,City Hotel,0,16,2025,February,9,25,2025-02-25,2,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,D,D,1,No Deposit,30.0,,0,Transient-Party,75.0,0,1
HB-090179,City Hotel,0,14,2024,June,22,2,2024-06-02,0,1,1,0.0,0,BB,USA,Direct,Direct,0,0,0,D,F,0,No Deposit,14.0,,0,Transient,120.7,0,0
HB-079358,City Hotel,0,30,2023,October,43,23,2023-10-23,1,2,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,118.2,0,1
HB-062877,City Hotel,1,59,2025,January,4,23,2025-01-23,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,326.0,,0,Transient,80.0,0,0
HB-103817,City Hotel,0,52,2024,December,52,29,2024-12-29,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,122.4,0,1
HB-082411,City Hotel,0,0,2024,January,2,11,2024-01-11,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,148.0,0,Transient,79.0,0,0
HB-105403,City Hotel,0,12,2025,February,6,5,2025-02-05,2,0,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,60.06,0,0
HB-033491,Resort Hotel,0,2,2025,February,8,23,2025-02-23,0,2,1,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,1,No Deposit,68.0,,0,Transient-Party,0.0,0,0
HB-096128,City Hotel,0,213,2024,August,34,23,2024-08-23,1,5,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient-Party,123.25,0,0
HB-021536,Resort Hotel,0,38,2024,February,8,25,2024-02-25,2,5,2,0.0,0,FB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,115.0,,0,Transient,69.21,0,0
HB-048888,City Hotel,1,32,2024,April,14,1,2024-04-01,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,131.4,0,0
HB-091555,City Hotel,0,0,2024,June,25,21,2024-06-21,0,2,1,0.0,0,BB,GRC,Aviation,Corporate,0,0,0,A,A,0,No Deposit,,153.0,0,Transient,95.0,0,0
HB-018103,Resort Hotel,0,0,2023,November,44,4,2023-11-04,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,2,No Deposit,,278.0,0,Transient-Party,40.0,1,0
HB-064450,City Hotel,1,65,2025,March,11,10,2025-03-10,0,1,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.2,0,0
HB-015807,Resort Hotel,0,53,2023,July,30,27,2023-07-27,2,5,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,242.0,,0,Transient,146.56,0,1
HB-014878,Resort Hotel,1,136,2023,July,29,20,2023-07-20,2,5,2,2.0,0,BB,PRT,Online TA,TA/TO,0,1,0,G,G,0,No Deposit,240.0,,0,Transient,237.0,0,0
HB-055333,City Hotel,1,36,2024,August,32,11,2024-08-11,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.9,0,1
HB-118753,City Hotel,0,95,2025,August,34,21,2025-08-21,1,3,2,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,80.1,0,1
HB-110043,City Hotel,0,147,2025,April,16,18,2025-04-18,0,3,2,0.0,0,SC,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,15.0,,0,Transient,79.2,0,0
HB-026376,Resort Hotel,0,151,2024,July,29,16,2024-07-16,4,10,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,114.41,0,1
HB-004587,Resort Hotel,0,162,2024,March,12,24,2024-03-24,0,3,2,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,84.0,0,0
HB-051082,City Hotel,1,309,2024,May,20,13,2024-05-13,1,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,215,Transient-Party,101.0,0,0
HB-111436,City Hotel,0,18,2025,May,19,9,2025-05-09,0,2,1,0.0,0,BB,DNK,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,135.0,0,0
HB-032227,Resort Hotel,0,40,2025,January,3,16,2025-01-16,1,2,1,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,A,C,0,No Deposit,,,0,Transient-Party,62.0,1,0
HB-073198,City Hotel,1,210,2025,August,33,16,2025-08-16,0,4,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,115.65,0,1
HB-035259,Resort Hotel,0,15,2025,April,16,14,2025-04-14,1,2,3,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,212.0,0,0
HB-059513,City Hotel,1,247,2024,October,44,28,2024-10-28,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,110.0,0,0
HB-041093,City Hotel,0,41,2023,August,32,12,2023-08-12,0,2,3,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,D,1,No Deposit,1.0,,0,Transient-Party,84.0,0,1
HB-070497,City Hotel,1,150,2025,June,25,17,2025-06-17,2,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,120.0,0,0
HB-024647,Resort Hotel,0,125,2024,May,21,22,2024-05-22,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Contract,48.75,0,0
HB-056976,City Hotel,0,422,2024,September,38,16,2024-09-16,0,2,2,0.0,0,HB,FRA,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,379,Transient-Party,90.0,0,1
HB-059532,City Hotel,1,275,2024,October,44,28,2024-10-28,2,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.95,0,1
HB-107181,City Hotel,0,101,2025,March,10,5,2025-03-05,2,2,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,0
HB-039304,Resort Hotel,0,87,2025,August,33,11,2025-08-11,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,230.0,0,2
HB-074181,City Hotel,1,356,2023,October,40,8,2023-10-08,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-015139,Resort Hotel,0,289,2023,November,47,20,2023-11-20,1,2,1,0.0,0,HB,GBR,Groups,TA/TO,0,0,1,A,E,1,No Deposit,134.0,,0,Transient-Party,13.0,0,1
HB-085869,City Hotel,0,109,2024,March,12,20,2024-03-20,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,F,F,2,No Deposit,28.0,,0,Transient,85.0,0,1
HB-106270,City Hotel,0,6,2025,February,8,23,2025-02-23,0,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,1
HB-015362,Resort Hotel,0,2,2023,July,27,9,2023-07-09,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,135.0,0,Transient,134.0,0,0
HB-005339,Resort Hotel,1,27,2024,April,17,25,2024-04-25,1,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,85.0,0,0
HB-026675,Resort Hotel,0,25,2024,August,32,7,2024-08-07,1,0,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,F,1,No Deposit,251.0,,0,Transient,131.0,0,0
HB-015003,Resort Hotel,1,244,2023,September,35,3,2023-09-03,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,19,0,A,A,0,Non Refund,,,0,Transient,36.0,0,0
HB-072822,City Hotel,1,46,2025,August,32,7,2025-08-07,1,2,1,0.0,0,SC,BHR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,1
HB-049816,City Hotel,0,110,2024,April,16,20,2024-04-20,0,2,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,A,A,3,No Deposit,9.0,,0,Transient-Party,72.8,0,0
HB-051792,City Hotel,1,75,2024,May,21,26,2024-05-26,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,140.4,0,0
HB-092614,City Hotel,0,30,2024,July,28,8,2024-07-08,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.9,0,1
HB-080606,City Hotel,0,28,2023,November,46,17,2023-11-17,0,3,3,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,16.0,,0,Transient,51.6,0,1
HB-053110,City Hotel,1,239,2024,June,24,15,2024-06-15,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,80,Transient,112.2,0,0
HB-076384,City Hotel,0,273,2023,July,29,17,2023-07-17,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-034271,Resort Hotel,0,0,2025,March,12,17,2025-03-17,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,95.0,0,1
HB-058019,City Hotel,1,53,2024,October,40,5,2024-10-05,0,2,1,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,113.4,0,2
HB-095942,City Hotel,0,47,2024,August,34,22,2024-08-22,1,3,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,85.0,0,0
HB-105701,City Hotel,0,10,2025,February,7,10,2025-02-10,2,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,2
HB-071028,City Hotel,1,39,2025,June,26,27,2025-06-27,0,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,123.0,0,1
HB-001443,Resort Hotel,1,87,2023,August,35,29,2023-08-29,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,122.86,0,0
HB-060602,City Hotel,1,139,2024,November,46,16,2024-11-16,2,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,68.0,0,0
HB-077235,City Hotel,0,327,2023,September,36,9,2023-09-09,2,4,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,21.0,,0,Transient-Party,76.0,0,0
HB-028656,Resort Hotel,0,11,2024,October,41,9,2024-10-09,1,0,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,405.0,0,Transient-Party,50.0,0,1
HB-118642,City Hotel,0,212,2025,August,34,22,2025-08-22,0,2,2,0.0,0,HB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,171.0,1,2
HB-063705,City Hotel,1,186,2025,February,8,17,2025-02-17,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.0,0,1
HB-085674,City Hotel,0,8,2024,March,12,18,2024-03-18,0,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,125.0,0,1
HB-014834,Resort Hotel,1,222,2023,September,37,15,2023-09-15,1,5,2,0.0,0,FB,PRT,Groups,Corporate,0,25,0,A,A,0,Non Refund,252.0,,0,Transient,49.95,0,0
HB-082357,City Hotel,1,94,2024,March,10,4,2024-03-04,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,154.0,,28,Transient,80.0,0,0
HB-021178,Resort Hotel,0,6,2024,February,8,19,2024-02-19,0,1,3,0.0,0,BB,AUT,Direct,Direct,0,0,0,A,G,2,No Deposit,,,0,Transient,39.0,0,1
HB-016821,Resort Hotel,0,17,2024,December,1,31,2024-12-31,2,1,1,0.0,0,BB,PRT,Direct,Direct,1,0,1,A,A,4,No Deposit,,,0,Transient,39.0,0,2
HB-037687,Resort Hotel,0,6,2025,June,26,25,2025-06-25,1,0,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,184.0,,0,Transient,104.0,1,0
HB-065411,City Hotel,1,229,2025,April,14,3,2025-04-03,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,100,Transient,100.0,0,0
HB-056927,City Hotel,0,258,2024,September,37,15,2024-09-15,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,106.2,0,0
HB-027886,Resort Hotel,0,34,2024,September,37,11,2024-09-11,2,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient-Party,129.0,0,3
HB-014673,Resort Hotel,0,10,2024,October,44,29,2024-10-29,1,1,2,0.0,0,BB,,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,38.0,0,2
HB-072269,City Hotel,1,464,2025,July,30,25,2025-07-25,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-086982,City Hotel,0,7,2024,April,15,9,2024-04-09,2,1,2,1.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,8.0,,0,Transient,133.83,0,2
HB-113011,City Hotel,0,85,2025,May,22,28,2025-05-28,2,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,42.0,,0,Transient,89.1,0,1
HB-111365,City Hotel,0,0,2025,May,19,8,2025-05-08,1,1,1,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,120.0,0,0
HB-068680,City Hotel,1,165,2025,May,21,19,2025-05-19,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,225.0,0,0
HB-081631,City Hotel,1,130,2024,April,15,13,2024-04-13,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,29.0,,10,Transient,100.0,0,0
HB-046287,City Hotel,0,146,2023,December,52,29,2023-12-29,0,3,2,0.0,0,BB,AUT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,99,Transient-Party,75.0,0,0
HB-075157,City Hotel,1,278,2023,July,29,22,2023-07-22,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,60.0,0,0
HB-015503,Resort Hotel,0,39,2023,July,29,20,2023-07-20,1,2,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,241.0,,0,Transient,103.95,0,1
HB-033201,Resort Hotel,0,94,2025,February,7,13,2025-02-13,1,3,2,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,152.0,,0,Transient-Party,62.0,0,0
HB-116759,City Hotel,0,253,2025,July,30,21,2025-07-21,1,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient-Party,107.1,0,0
HB-034956,Resort Hotel,0,152,2025,April,14,5,2025-04-05,0,4,2,1.0,0,BB,POL,Groups,TA/TO,0,0,0,A,C,3,No Deposit,,223.0,0,Transient-Party,58.0,0,0
HB-116848,City Hotel,0,6,2025,July,30,25,2025-07-25,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-053961,City Hotel,1,81,2024,July,27,3,2024-07-03,2,1,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,103.5,0,1
HB-050551,City Hotel,1,103,2024,May,18,4,2024-05-04,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,95.0,0,0
HB-076200,City Hotel,0,260,2023,July,27,4,2023-07-04,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-014588,Resort Hotel,1,172,2025,June,24,14,2025-06-14,2,5,2,0.0,0,BB,GBR,Direct,TA/TO,0,1,1,E,E,0,No Deposit,,,0,Transient,113.4,0,1
HB-024537,Resort Hotel,0,116,2024,May,20,18,2024-05-18,2,5,2,0.0,1,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,177.0,,0,Transient-Party,75.6,0,1
HB-111109,City Hotel,0,11,2025,May,18,4,2025-05-04,0,2,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,179.0,1,2
HB-103255,City Hotel,0,25,2024,December,50,13,2024-12-13,0,4,1,0.0,0,BB,EST,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,79.9,0,1
HB-079800,City Hotel,0,0,2023,November,44,4,2023-11-04,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,89.0,0,0
HB-020627,Resort Hotel,0,1,2024,February,5,2,2024-02-02,0,3,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,68.0,0,2
HB-108068,City Hotel,0,151,2025,March,12,20,2025-03-20,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,95.0,0,1
HB-038008,Resort Hotel,0,193,2025,July,27,4,2025-07-04,0,3,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,90.0,1,0
HB-098864,City Hotel,0,17,2024,October,40,3,2024-10-03,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-080415,City Hotel,1,34,2023,December,49,8,2023-12-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,0,Transient,90.0,0,0
HB-000259,Resort Hotel,0,21,2023,July,28,10,2023-07-10,1,2,2,0.0,0,BB,AUS,Direct,Direct,0,0,0,A,C,0,No Deposit,250.0,,0,Transient,98.0,0,1
HB-010422,Resort Hotel,1,312,2025,March,10,5,2025-03-05,2,5,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,30.0,0,0
HB-079382,City Hotel,0,12,2023,October,43,26,2023-10-26,1,0,2,0.0,0,BB,BRA,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,114.0,0,0
HB-010891,Resort Hotel,1,124,2025,April,15,9,2025-04-09,2,5,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,492.0,,0,Transient,80.0,0,0
HB-069974,City Hotel,1,41,2025,June,23,8,2025-06-08,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,1
HB-033464,Resort Hotel,0,48,2025,February,8,17,2025-02-17,2,5,2,2.0,0,BB,POL,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,88.0,0,0
HB-012745,Resort Hotel,1,55,2025,July,29,15,2025-07-15,2,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,2,No Deposit,250.0,,0,Transient,252.0,0,0
HB-099978,City Hotel,0,24,2024,October,42,17,2024-10-17,1,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,85.0,0,1
HB-111176,City Hotel,0,7,2025,May,19,5,2025-05-05,0,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,170.0,0,1
HB-045967,City Hotel,1,104,2023,December,48,3,2023-12-03,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,55.0,,0,Transient,75.0,0,0
HB-065737,City Hotel,1,118,2025,April,15,7,2025-04-07,0,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,1
HB-081057,City Hotel,1,85,2024,January,4,22,2024-01-22,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,29.0,,0,Transient,85.0,0,0
HB-088299,City Hotel,0,1,2024,May,18,3,2024-05-03,0,1,2,1.0,0,BB,FIN,Online TA,TA/TO,0,0,0,A,F,0,No Deposit,,,0,Transient,142.0,0,2
HB-113926,City Hotel,0,29,2025,June,24,11,2025-06-11,2,1,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,120.0,0,1
HB-028070,Resort Hotel,0,336,2024,September,37,15,2024-09-15,1,3,2,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,A,1,No Deposit,,223.0,0,Transient-Party,66.0,0,0
HB-064769,City Hotel,1,615,2025,March,11,16,2025-03-16,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-001016,Resort Hotel,1,63,2023,August,32,10,2023-08-10,1,4,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,205.0,0,0
HB-045644,City Hotel,0,140,2023,November,46,18,2023-11-18,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,29.0,,87,Transient-Party,65.0,0,0
HB-102690,City Hotel,0,61,2024,December,49,2,2024-12-02,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,102.6,0,2
HB-042812,City Hotel,0,14,2023,September,36,10,2023-09-10,2,6,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,100.88,0,0
HB-106127,City Hotel,0,28,2025,February,7,15,2025-02-15,2,4,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-036811,Resort Hotel,0,388,2025,May,21,25,2025-05-25,1,3,2,0.0,0,SC,CN,Groups,TA/TO,0,0,0,E,I,1,No Deposit,96.0,,0,Transient-Party,0.0,0,2
HB-114489,City Hotel,0,102,2025,June,25,18,2025-06-18,2,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,89.1,0,1
HB-023038,Resort Hotel,0,86,2024,August,35,31,2024-08-31,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,8,A,C,0,No Deposit,,154.0,0,Transient,66.0,0,0
HB-059406,City Hotel,1,199,2024,October,44,28,2024-10-28,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,29.0,,0,Transient-Party,95.0,0,0
HB-014994,Resort Hotel,1,166,2023,July,28,15,2023-07-15,0,2,2,0.0,0,FB,PRT,Groups,TA/TO,0,24,0,A,A,0,Non Refund,,,0,Transient,121.5,0,0
HB-071413,City Hotel,1,282,2025,July,27,5,2025-07-05,0,2,2,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,141.3,0,1
HB-095699,City Hotel,0,133,2024,August,34,21,2024-08-21,2,0,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.3,0,1
HB-005844,Resort Hotel,1,9,2024,May,20,15,2024-05-15,1,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,315.0,,0,Transient-Party,70.0,0,0
HB-032304,Resort Hotel,0,5,2025,January,4,21,2025-01-21,0,1,2,0.0,0,FB,ESP,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,6.0,,0,Transient,96.0,0,0
HB-100660,City Hotel,0,35,2024,October,44,28,2024-10-28,1,2,2,0.0,0,BB,TUR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,129.0,0,1
HB-031116,Resort Hotel,0,0,2024,December,50,14,2024-12-14,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,49.0,1,0
HB-003376,Resort Hotel,0,45,2023,December,49,5,2023-12-05,2,1,2,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,38.0,,0,Transient-Party,68.0,0,0
HB-094345,City Hotel,0,8,2024,July,31,31,2024-07-31,2,1,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient,86.53,0,0
HB-095897,City Hotel,0,5,2025,January,1,3,2025-01-03,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,9,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,1
HB-092864,City Hotel,0,78,2024,July,27,4,2024-07-04,3,6,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,128.8,0,1
HB-028169,Resort Hotel,0,239,2024,September,38,18,2024-09-18,2,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,110.0,0,1
HB-082951,City Hotel,0,0,2024,January,1,4,2024-01-04,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient,41.0,0,0
HB-035181,Resort Hotel,0,49,2025,April,15,13,2025-04-13,0,2,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,G,G,1,No Deposit,240.0,,0,Transient,175.0,0,0
HB-056200,City Hotel,1,419,2024,September,35,1,2024-09-01,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-074670,City Hotel,1,359,2023,October,41,11,2023-10-11,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-069045,City Hotel,1,311,2025,May,21,24,2025-05-24,0,4,0,2.0,0,BB,DNK,Online TA,TA/TO,0,0,0,B,B,2,No Deposit,9.0,,0,Transient,99.45,0,0
HB-117160,City Hotel,0,56,2025,July,30,24,2025-07-24,1,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,144.67,0,1
HB-012662,Resort Hotel,1,153,2025,July,28,10,2025-07-10,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,315.0,,0,Contract,130.05,0,0
HB-007232,Resort Hotel,1,59,2024,July,31,29,2024-07-29,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,200.0,0,0
HB-017474,Resort Hotel,1,283,2023,October,41,12,2023-10-12,2,5,2,0.0,0,HB,GBR,Groups,Direct,0,0,0,E,E,0,No Deposit,273.0,,0,Transient-Party,75.86,0,0
HB-089137,City Hotel,0,114,2024,May,20,15,2024-05-15,2,1,3,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,16.0,,0,Transient,115.6,0,1
HB-113276,City Hotel,0,1,2025,June,22,1,2025-06-01,1,3,2,0.0,1,BB,VEN,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,100.0,0,0
HB-084648,City Hotel,0,117,2024,February,9,29,2024-02-29,1,1,1,0.0,0,BB,DZA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,134.0,,0,Transient-Party,76.0,0,0
HB-081585,City Hotel,1,197,2024,June,23,3,2024-06-03,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,21.0,,25,Transient,80.0,0,0
HB-101723,City Hotel,0,8,2024,November,46,15,2024-11-15,0,2,2,0.0,0,BB,ITA,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,90.0,0,0
HB-007239,Resort Hotel,1,121,2024,July,31,30,2024-07-30,2,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,188.33,0,0
HB-036031,Resort Hotel,0,0,2025,May,19,7,2025-05-07,1,0,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,97.0,1,0
HB-036254,Resort Hotel,0,156,2025,May,19,8,2025-05-08,2,5,2,0.0,0,HB,IRL,Groups,TA/TO,0,0,0,E,E,0,No Deposit,434.0,,0,Transient-Party,101.43,0,0
HB-044653,City Hotel,0,50,2023,October,41,9,2023-10-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,32.0,,49,Transient-Party,85.0,0,0
HB-105755,City Hotel,0,7,2025,February,7,14,2025-02-14,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.0,0,0
HB-019683,Resort Hotel,0,17,2023,December,52,27,2023-12-27,2,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,55.0,0,2
HB-036843,Resort Hotel,0,300,2025,May,21,23,2025-05-23,2,6,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,1,No Deposit,,223.0,99,Transient-Party,62.81,0,0
HB-014650,Resort Hotel,0,165,2024,December,52,23,2024-12-23,1,2,1,0.0,0,HB,,Direct,Direct,0,0,1,E,E,1,No Deposit,,,0,Transient-Party,55.53,0,1
HB-032019,Resort Hotel,0,4,2025,January,3,14,2025-01-14,0,1,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,168.0,,0,Transient-Party,68.0,0,0
HB-118330,City Hotel,0,8,2025,August,33,15,2025-08-15,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,1,No Deposit,,485.0,0,Transient,84.0,0,3
HB-034742,Resort Hotel,0,121,2025,March,13,28,2025-03-28,2,5,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,55.49,0,1
HB-014221,Resort Hotel,0,1,2023,November,46,19,2023-11-19,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,35.11,0,0
HB-071638,City Hotel,1,226,2025,July,28,9,2025-07-09,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-088794,City Hotel,0,0,2024,May,19,11,2024-05-11,0,1,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,90.71,0,0
HB-058586,City Hotel,1,37,2024,October,41,13,2024-10-13,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,105.0,0,0
HB-003014,Resort Hotel,0,60,2023,November,45,11,2023-11-11,0,4,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,53.0,0,1
HB-073759,City Hotel,1,272,2023,July,28,16,2023-07-16,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-055295,City Hotel,1,405,2024,August,32,10,2024-08-10,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,65.0,0,0
HB-099656,City Hotel,0,377,2024,October,42,14,2024-10-14,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-101720,City Hotel,0,20,2024,November,46,13,2024-11-13,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.65,0,1
HB-034622,Resort Hotel,0,214,2025,March,13,24,2025-03-24,2,5,2,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,D,D,1,No Deposit,273.0,,0,Transient-Party,63.2,0,0
HB-105762,City Hotel,0,55,2025,February,7,11,2025-02-11,2,2,2,2.0,0,BB,TUN,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,149.6,0,1
HB-051428,City Hotel,0,166,2024,May,20,19,2024-05-19,2,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,105.28,0,1
HB-115445,City Hotel,0,405,2025,July,27,4,2025-07-04,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,114.4,0,0
HB-066463,City Hotel,1,44,2025,April,16,20,2025-04-20,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,85.0,0,0
HB-084825,City Hotel,0,7,2024,March,9,2,2024-03-02,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,94.0,,0,Transient-Party,67.0,0,0
HB-108543,City Hotel,0,68,2025,March,13,26,2025-03-26,2,1,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,72.0,0,0
HB-034681,Resort Hotel,0,112,2025,March,13,29,2025-03-29,0,4,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,72.5,0,0
HB-111392,City Hotel,0,1,2025,May,19,9,2025-05-09,0,1,2,0.0,0,BB,USA,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,130.0,0,0
HB-118870,City Hotel,0,457,2025,August,35,25,2025-08-25,0,2,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,6.0,,0,Transient-Party,95.5,0,1
HB-062662,City Hotel,1,54,2025,January,3,18,2025-01-18,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,171.0,,0,Transient,65.0,0,0
HB-029739,Resort Hotel,0,43,2024,November,44,1,2024-11-01,0,4,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,29.0,0,1
HB-068846,City Hotel,1,189,2025,May,21,21,2025-05-21,2,2,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,134.1,0,2
HB-088145,City Hotel,0,84,2024,April,17,28,2024-04-28,1,3,3,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,128.43,0,2
HB-035035,Resort Hotel,0,14,2025,April,15,11,2025-04-11,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient-Party,100.0,0,1
HB-075715,City Hotel,1,302,2023,August,33,15,2023-08-15,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-096293,City Hotel,0,29,2024,August,35,28,2024-08-28,2,1,3,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,150.17,0,3
HB-071349,City Hotel,1,148,2025,July,27,3,2025-07-03,1,2,3,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,177.3,0,1
HB-042572,City Hotel,0,0,2023,September,36,7,2023-09-07,1,2,1,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,11.0,,0,Transient,96.27,0,1
HB-110883,City Hotel,0,174,2025,April,18,30,2025-04-30,2,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,2
HB-053457,City Hotel,1,37,2024,June,25,20,2024-06-20,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,113.4,0,0
HB-071098,City Hotel,1,63,2025,June,26,28,2025-06-28,0,2,1,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,1
HB-066960,City Hotel,1,110,2025,April,17,26,2025-04-26,1,4,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,158.95,0,0
HB-032915,Resort Hotel,0,6,2025,February,6,6,2025-02-06,1,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,467.0,,0,Transient,46.08,0,0
HB-084146,City Hotel,0,15,2024,February,8,19,2024-02-19,0,1,1,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,B,0,No Deposit,,67.0,0,Transient-Party,81.0,1,0
HB-115188,City Hotel,0,178,2025,July,27,1,2025-07-01,1,1,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,86.63,0,1
HB-114503,City Hotel,0,44,2025,June,25,20,2025-06-20,0,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,146.67,0,1
HB-075123,City Hotel,1,344,2023,September,39,26,2023-09-26,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-113946,City Hotel,0,155,2025,June,24,12,2025-06-12,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,153.0,1,0
HB-105685,City Hotel,0,4,2025,February,7,13,2025-02-13,1,0,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,52.0,,0,Transient,75.0,0,0
HB-107161,City Hotel,0,174,2025,March,10,5,2025-03-05,2,2,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,90.0,0,1
HB-019956,Resort Hotel,0,2,2024,January,2,10,2024-01-10,1,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,314.0,,0,Transient,25.0,0,0
HB-047518,City Hotel,0,51,2024,February,8,25,2024-02-25,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.3,0,1
HB-089968,City Hotel,0,102,2024,June,23,5,2024-06-05,1,0,2,0.0,0,BB,ISR,Groups,TA/TO,0,0,1,A,A,0,No Deposit,1.0,,0,Transient-Party,65.0,0,1
HB-103883,City Hotel,0,32,2024,December,52,27,2024-12-27,1,5,2,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,220.0,,0,Transient-Party,70.0,0,1
HB-101452,City Hotel,0,58,2024,November,45,10,2024-11-10,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-075766,City Hotel,1,323,2023,September,36,5,2023-09-05,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-015079,Resort Hotel,1,252,2023,September,36,10,2023-09-10,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,240.0,,0,Transient,80.86,0,1
HB-063514,City Hotel,1,173,2025,February,7,12,2025-02-12,2,3,2,0.0,0,BB,TUR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.4,0,1
HB-020833,Resort Hotel,0,0,2024,February,6,10,2024-02-10,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,53.0,0,0
HB-093921,City Hotel,0,1,2024,July,30,27,2024-07-27,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient-Party,65.0,0,0
HB-042885,City Hotel,0,168,2023,September,37,11,2023-09-11,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,B,0,No Deposit,1.0,,0,Transient-Party,60.0,0,0
HB-092015,City Hotel,0,1,2024,June,26,28,2024-06-28,0,1,1,0.0,1,BB,NLD,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,133.0,0,2
HB-009179,Resort Hotel,1,378,2024,November,44,1,2024-11-01,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,248.0,,0,Transient,46.0,0,0
HB-092084,City Hotel,0,64,2024,June,26,27,2024-06-27,1,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,111.9,0,1
HB-037149,Resort Hotel,0,56,2025,June,23,2,2025-06-02,2,5,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,149.57,1,1
HB-009008,Resort Hotel,1,124,2024,October,43,22,2024-10-22,2,3,2,0.0,0,BB,PRT,Groups,Corporate,0,0,0,D,D,1,No Deposit,,,0,Transient-Party,65.0,0,0
HB-005932,Resort Hotel,0,265,2024,May,20,16,2024-05-16,3,7,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,46.75,0,1
HB-050171,City Hotel,1,60,2024,April,17,24,2024-04-24,2,2,1,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.46,0,0
HB-045254,City Hotel,0,81,2023,October,43,24,2023-10-24,2,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,89.25,0,2
HB-067389,City Hotel,1,82,2025,May,18,3,2025-05-03,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,130.0,0,0
HB-099892,City Hotel,0,13,2024,October,42,17,2024-10-17,1,2,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,2
HB-047693,City Hotel,1,116,2024,February,9,28,2024-02-28,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,61.0,0,0
HB-069310,City Hotel,1,35,2025,May,22,30,2025-05-30,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-005464,Resort Hotel,1,101,2024,April,18,29,2024-04-29,2,5,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,95.0,,0,Transient-Party,47.0,0,0
HB-021487,Resort Hotel,0,3,2024,February,9,26,2024-02-26,2,2,2,0.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,156.0,,0,Transient,68.75,0,0
HB-089419,City Hotel,0,0,2024,May,21,20,2024-05-20,0,1,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,150.0,0,0
HB-085719,City Hotel,0,0,2024,March,12,19,2024-03-19,0,1,2,1.0,0,BB,ESP,Direct,Direct,0,0,0,A,D,1,No Deposit,,,0,Transient,154.0,0,0
HB-037468,Resort Hotel,0,252,2025,June,24,12,2025-06-12,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,98.4,0,0
HB-097755,City Hotel,0,30,2024,September,38,18,2024-09-18,2,0,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,134.1,0,1
HB-058876,City Hotel,1,52,2024,October,42,17,2024-10-17,1,1,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,158.4,0,1
HB-087443,City Hotel,0,20,2024,April,16,17,2024-04-17,2,1,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,77.77,0,1
HB-031158,Resort Hotel,0,16,2024,December,51,16,2024-12-16,0,1,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,43.0,0,2
HB-025074,Resort Hotel,0,17,2024,June,24,11,2024-06-11,1,1,2,0.0,0,BB,GIB,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,141.0,0,0
HB-033248,Resort Hotel,0,83,2025,February,7,16,2025-02-16,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,314.0,,0,Transient-Party,45.6,0,0
HB-108010,City Hotel,0,97,2025,March,11,16,2025-03-16,2,3,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,63.75,0,0
HB-105296,City Hotel,0,29,2025,February,6,4,2025-02-04,0,1,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.0,0,2
HB-081436,City Hotel,1,112,2024,March,9,3,2024-03-03,0,3,2,0.0,0,SC,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Contract,84.3,0,2
HB-061684,City Hotel,1,288,2024,December,51,22,2024-12-22,2,5,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient-Party,67.26,0,0
HB-005014,Resort Hotel,1,168,2024,April,15,12,2024-04-12,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,245.0,,0,Transient,86.0,0,0
HB-002178,Resort Hotel,0,81,2023,October,40,4,2023-10-04,2,5,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,E,0,No Deposit,175.0,,0,Transient,63.66,0,0
HB-107190,City Hotel,0,11,2025,March,10,7,2025-03-07,0,2,1,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,441.0,,0,Transient-Party,130.0,0,2
HB-104676,City Hotel,0,22,2025,January,3,16,2025-01-16,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,99.24,0,0
HB-111549,City Hotel,0,90,2025,May,19,10,2025-05-10,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,83.0,,0,Transient,129.6,0,0
HB-111799,City Hotel,0,94,2025,May,20,13,2025-05-13,2,1,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,138.0,0,2
HB-088802,City Hotel,0,114,2024,May,19,10,2024-05-10,0,3,2,1.0,0,BB,ITA,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,136.0,0,1
HB-081337,City Hotel,0,0,2023,December,49,8,2023-12-08,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,45.0,0,0
HB-115993,City Hotel,0,17,2025,July,28,13,2025-07-13,0,1,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,170.0,0,0
HB-089793,City Hotel,0,31,2024,May,21,24,2024-05-24,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,108.9,0,1
HB-018660,Resort Hotel,0,5,2023,November,47,25,2023-11-25,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,94.0,0,Transient,25.0,0,0
HB-050381,City Hotel,1,71,2024,April,18,29,2024-04-29,1,2,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,198.9,0,0
HB-106495,City Hotel,0,134,2025,February,9,25,2025-02-25,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,75.0,0,0
HB-087876,City Hotel,0,71,2024,April,17,24,2024-04-24,2,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,88.5,0,0
HB-041567,City Hotel,0,6,2023,August,33,18,2023-08-18,0,4,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient,75.0,0,1
HB-117681,City Hotel,0,73,2025,August,31,3,2025-08-03,2,3,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,86.0,,0,Transient,161.0,0,0
HB-026579,Resort Hotel,0,166,2024,August,31,1,2024-08-01,1,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,E,F,0,No Deposit,8.0,,0,Transient,140.0,0,0
HB-075841,City Hotel,1,337,2023,September,38,19,2023-09-19,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-101741,City Hotel,0,17,2024,November,46,12,2024-11-12,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,75.4,0,1
HB-048061,City Hotel,0,75,2024,March,11,15,2024-03-15,0,2,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,67.5,0,0
HB-050975,City Hotel,1,130,2024,May,19,12,2024-05-12,1,3,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,113.05,0,1
HB-071796,City Hotel,1,229,2025,July,28,12,2025-07-12,1,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-052748,City Hotel,1,28,2024,June,24,10,2024-06-10,4,9,1,0.0,0,BB,AGO,Direct,Direct,0,0,0,E,E,2,No Deposit,14.0,,0,Transient,172.15,0,0
HB-058665,City Hotel,1,37,2024,October,41,13,2024-10-13,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,105.0,0,0
HB-052795,City Hotel,1,69,2024,June,24,12,2024-06-12,2,4,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,120.0,0,0
HB-024255,Resort Hotel,0,0,2024,May,20,14,2024-05-14,0,1,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,85.0,0,0
HB-104291,City Hotel,0,1,2025,January,2,8,2025-01-08,2,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,82.88,0,0
HB-104976,City Hotel,0,79,2025,January,4,26,2025-01-26,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,,365.0,0,Transient-Party,85.0,0,0
HB-115193,City Hotel,0,163,2025,July,27,1,2025-07-01,1,1,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,89.1,0,1
HB-106577,City Hotel,0,336,2025,February,8,21,2025-02-21,1,5,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,67.15,0,2
HB-006914,Resort Hotel,0,276,2024,July,28,11,2024-07-11,1,4,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,142.5,1,0
HB-024382,Resort Hotel,0,19,2024,May,20,16,2024-05-16,1,2,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient-Party,135.0,0,0
HB-078672,City Hotel,1,45,2023,November,46,19,2023-11-19,2,8,1,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,7.0,,0,Transient,69.24,0,0
HB-038674,Resort Hotel,0,49,2025,July,30,23,2025-07-23,2,1,2,0.0,0,BB,BRA,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient-Party,200.0,0,0
HB-020903,Resort Hotel,0,9,2024,February,7,13,2024-02-13,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,67.5,0,1
HB-117697,City Hotel,0,0,2025,August,32,7,2025-08-07,1,0,2,0.0,0,BB,USA,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,160.0,0,0
HB-033777,Resort Hotel,0,17,2025,June,25,22,2025-06-22,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,2,A,A,0,No Deposit,,331.0,0,Transient,75.0,0,0
HB-036858,Resort Hotel,0,36,2025,May,22,28,2025-05-28,2,1,2,0.0,0,BB,FIN,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,142.0,1,2
HB-015408,Resort Hotel,0,142,2023,July,26,2,2023-07-02,3,8,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,69.0,,0,Contract,89.68,0,0
HB-100540,City Hotel,0,73,2024,October,44,28,2024-10-28,0,1,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,21.0,,0,Transient-Party,62.5,0,0
HB-102116,City Hotel,0,215,2024,November,47,21,2024-11-21,1,1,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,D,2,No Deposit,,233.0,0,Transient,85.0,0,0
HB-113318,City Hotel,0,25,2025,June,23,4,2025-06-04,1,0,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,174.0,1,1
HB-032139,Resort Hotel,0,4,2025,January,3,15,2025-01-15,2,1,1,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,42.0,0,0
HB-082182,City Hotel,1,99,2024,February,8,19,2024-02-19,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,1,0,A,A,0,No Deposit,,67.0,0,Transient-Party,80.0,0,0
HB-093184,City Hotel,0,89,2024,July,29,17,2024-07-17,1,0,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,137.7,0,2
HB-031738,Resort Hotel,0,1,2025,January,1,2,2025-01-02,1,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,54.0,1,1
HB-020133,Resort Hotel,0,2,2024,January,2,10,2024-01-10,2,5,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,49.43,0,1
HB-101818,City Hotel,0,0,2024,November,47,18,2024-11-18,0,1,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,95.0,0,0
HB-075463,City Hotel,1,334,2023,September,37,16,2023-09-16,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-052278,City Hotel,1,98,2024,June,22,2,2024-06-02,0,3,2,2.0,0,BB,ITA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,198.9,0,0
HB-009578,Resort Hotel,1,125,2024,December,50,15,2024-12-15,2,5,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,82.8,0,1
HB-027235,Resort Hotel,0,101,2024,August,33,18,2024-08-18,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,314.0,,0,Transient,171.2,0,0
HB-037954,Resort Hotel,0,161,2025,July,27,1,2025-07-01,2,1,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,A,A,4,No Deposit,240.0,,0,Transient,144.0,1,2
HB-103296,City Hotel,0,26,2024,December,50,14,2024-12-14,0,4,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.4,0,1
HB-092708,City Hotel,0,100,2024,July,27,6,2024-07-06,1,4,3,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,D,2,No Deposit,7.0,,0,Transient,98.83,0,2
HB-091788,City Hotel,0,192,2024,June,26,24,2024-06-24,0,2,1,0.0,0,BB,ROU,Offline TA/TO,TA/TO,0,0,0,A,F,0,No Deposit,34.0,,0,Transient-Party,95.0,0,0
HB-002324,Resort Hotel,1,78,2023,October,41,9,2023-10-09,1,2,2,0.0,0,FB,ESP,Groups,TA/TO,0,0,0,A,A,0,Non Refund,134.0,,0,Transient,92.0,0,0
HB-029784,Resort Hotel,0,54,2024,October,44,30,2024-10-30,2,5,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,171.0,,0,Transient,35.0,0,0
HB-047772,City Hotel,1,81,2024,March,9,3,2024-03-03,0,3,2,0.0,0,BB,CZE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,96.3,0,0
HB-081887,City Hotel,1,178,2024,April,17,28,2024-04-28,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,46,Transient,120.0,0,0
HB-071741,City Hotel,1,219,2025,July,28,11,2025-07-11,0,3,2,1.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.1,0,0
HB-017207,Resort Hotel,0,236,2023,September,38,24,2023-09-24,2,5,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,175.0,,0,Transient,57.6,0,0
HB-085578,City Hotel,0,35,2024,March,11,16,2024-03-16,0,2,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,71.1,0,1
HB-016658,Resort Hotel,0,59,2023,August,35,30,2023-08-30,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,138.86,0,1
HB-030214,Resort Hotel,0,15,2024,November,46,12,2024-11-12,2,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,36.29,0,0
HB-097382,City Hotel,0,8,2024,September,37,15,2024-09-15,0,1,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,149.0,0,3
HB-051697,City Hotel,1,158,2024,May,21,24,2024-05-24,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,31,Transient,130.0,0,0
HB-090818,City Hotel,0,136,2024,June,23,9,2024-06-09,0,3,2,0.0,0,BB,CHE,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,103.68,0,2
HB-089019,City Hotel,0,100,2024,May,20,14,2024-05-14,1,1,3,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,219.6,1,2
HB-029851,Resort Hotel,0,10,2024,November,44,3,2024-11-03,1,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,60.0,0,2
HB-108576,City Hotel,0,206,2025,March,13,26,2025-03-26,2,1,2,0.0,0,BB,CN,Groups,TA/TO,0,0,0,A,A,0,No Deposit,296.0,,0,Transient-Party,72.0,0,0
HB-074748,City Hotel,1,329,2023,September,37,11,2023-09-11,2,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,5.0,,0,Transient,80.0,0,0
HB-067413,City Hotel,1,152,2025,May,18,3,2025-05-03,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,286.0,,0,Transient,100.0,0,0
HB-115957,City Hotel,0,250,2025,July,28,8,2025-07-08,2,3,0,2.0,0,BB,JOR,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient,93.65,0,1
HB-047054,City Hotel,1,43,2024,February,6,5,2024-02-05,1,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient,69.52,0,0
HB-074862,City Hotel,1,164,2023,August,33,14,2023-08-14,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-068904,City Hotel,1,50,2025,May,21,22,2025-05-22,1,2,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,144.0,0,1
HB-080045,City Hotel,0,4,2024,January,3,15,2024-01-15,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,1,11,5,A,A,0,No Deposit,9.0,,0,Transient,73.9,0,1
HB-095384,City Hotel,0,0,2024,August,33,18,2024-08-18,0,1,1,0.0,0,BB,USA,Direct,Direct,0,0,0,A,B,0,No Deposit,,,0,Transient,109.0,0,0
HB-094757,City Hotel,0,166,2024,August,32,6,2024-08-06,2,1,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,103.5,1,1
HB-056918,City Hotel,1,433,2024,September,37,15,2024-09-15,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-076350,City Hotel,1,139,2023,July,29,23,2023-07-23,2,6,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,1
HB-038294,Resort Hotel,0,21,2025,July,28,12,2025-07-12,0,2,2,0.0,0,BB,USA,Direct,Direct,0,0,0,A,E,0,No Deposit,250.0,,0,Transient,167.25,0,1
HB-007631,Resort Hotel,1,187,2024,August,33,17,2024-08-17,1,4,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,75.0,,0,Transient,143.1,0,1
HB-089895,City Hotel,0,67,2024,May,22,27,2024-05-27,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,140.4,0,1
HB-066156,City Hotel,1,58,2025,April,16,15,2025-04-15,0,1,2,0.0,0,SC,ISR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-109479,City Hotel,0,78,2025,April,15,7,2025-04-07,2,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-007828,Resort Hotel,1,333,2024,August,35,28,2024-08-28,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,86.79,0,2
HB-106949,City Hotel,0,203,2025,March,9,2,2025-03-02,0,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,57.93,0,2
HB-047738,City Hotel,1,3,2024,March,9,2,2024-03-02,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,101.0,0,0
HB-084121,City Hotel,0,4,2024,February,8,19,2024-02-19,0,1,1,0.0,0,BB,DEU,Corporate,TA/TO,0,0,0,A,D,0,No Deposit,,67.0,0,Transient-Party,81.0,0,0
HB-093099,City Hotel,0,73,2024,July,28,14,2024-07-14,0,3,2,0.0,0,BB,USA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,85.0,0,0
HB-078659,City Hotel,0,0,2023,October,41,11,2023-10-11,2,1,2,0.0,0,BB,BRA,Direct,Direct,0,0,0,A,D,1,No Deposit,,,0,Transient,114.0,0,0
HB-015235,Resort Hotel,0,0,2024,March,9,1,2024-03-01,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,2,A,D,2,No Deposit,47.0,,0,Transient,30.0,0,0
HB-037182,Resort Hotel,0,241,2025,June,23,3,2025-06-03,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,240.0,,0,Transient,95.6,0,2
HB-038206,Resort Hotel,0,153,2025,July,28,9,2025-07-09,2,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,120.0,0,1
HB-106338,City Hotel,0,27,2025,February,8,20,2025-02-20,1,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,63.42,0,0
HB-063852,City Hotel,1,58,2025,February,8,23,2025-02-23,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,132.0,,0,Transient,78.0,0,0
HB-108757,City Hotel,0,0,2025,March,13,30,2025-03-30,0,2,2,0.0,1,BB,PRT,Direct,Direct,0,0,0,F,F,1,No Deposit,,,0,Transient,182.0,0,0
HB-101217,City Hotel,0,26,2024,November,45,7,2024-11-07,1,1,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,153.23,0,1
HB-074583,City Hotel,1,353,2023,October,40,5,2023-10-05,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-013492,Resort Hotel,1,209,2025,August,33,17,2025-08-17,2,4,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,185.75,0,0
HB-023452,Resort Hotel,0,32,2024,April,16,19,2024-04-19,2,5,2,0.0,0,HB,GBR,Groups,Direct,0,0,0,D,D,0,No Deposit,273.0,,0,Transient-Party,69.36,0,0
HB-102788,City Hotel,0,35,2024,December,49,2,2024-12-02,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.4,0,1
HB-116676,City Hotel,0,249,2025,July,29,17,2025-07-17,1,5,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.9,0,1
HB-000807,Resort Hotel,1,31,2023,July,30,30,2023-07-30,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,242.0,,0,Transient,154.0,0,2
HB-085999,City Hotel,0,150,2024,March,12,19,2024-03-19,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,41.43,0,2
HB-035226,Resort Hotel,0,6,2025,April,16,14,2025-04-14,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,130.0,0,1
HB-008032,Resort Hotel,1,211,2024,September,36,7,2024-09-07,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,D,D,0,Non Refund,1.0,,0,Transient,89.0,0,0
HB-077885,City Hotel,0,17,2023,September,39,26,2023-09-26,2,2,1,0.0,0,BB,USA,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,170.0,0,0
HB-022697,Resort Hotel,0,32,2024,March,13,30,2024-03-30,0,4,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,367.0,,0,Transient,21.0,0,1
HB-099338,City Hotel,0,1,2024,October,41,10,2024-10-10,1,1,2,0.0,0,BB,CHE,Direct,Direct,0,0,0,A,D,1,No Deposit,14.0,,0,Transient,150.0,0,0
HB-020469,Resort Hotel,0,0,2024,November,48,25,2024-11-25,0,1,1,0.0,0,BB,PRT,Direct,Direct,1,0,2,A,D,1,No Deposit,,,0,Transient,38.7,0,0
HB-106001,City Hotel,0,114,2025,February,7,15,2025-02-15,0,4,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,242.0,0,Transient-Party,78.0,0,0
HB-086997,City Hotel,0,2,2024,July,27,3,2024-07-03,2,0,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,5,A,A,0,No Deposit,,40.0,0,Transient,67.0,1,0
HB-031877,Resort Hotel,0,119,2025,January,2,8,2025-01-08,1,0,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,44.0,1,0
HB-100740,City Hotel,0,79,2024,October,43,21,2024-10-21,4,7,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,172.23,0,1
HB-116058,City Hotel,0,248,2025,July,28,11,2025-07-11,0,4,2,1.0,0,BB,DNK,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.1,0,2
HB-007218,Resort Hotel,0,292,2024,July,30,28,2024-07-28,2,3,1,0.0,0,BB,IRL,Direct,Direct,0,0,0,D,D,2,No Deposit,250.0,,0,Transient,136.0,0,0
HB-004752,Resort Hotel,0,169,2024,March,13,31,2024-03-31,0,3,2,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,A,1,Refundable,,223.0,0,Transient-Party,66.0,0,0
HB-015537,Resort Hotel,0,2,2023,July,29,23,2023-07-23,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,9.0,0,Transient,114.0,0,0
HB-014605,Resort Hotel,0,1,2024,November,48,25,2024-11-25,2,3,2,0.0,0,HB,,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,314.0,,0,Transient,66.4,0,0
HB-026270,Resort Hotel,0,66,2024,July,30,24,2024-07-24,2,1,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,164.0,0,0
HB-077752,City Hotel,0,2,2023,September,38,23,2023-09-23,0,2,2,0.0,0,SC,IRN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,133.0,0,0
HB-019289,Resort Hotel,1,8,2023,December,50,12,2023-12-12,0,1,2,2.0,0,BB,PRT,Direct,Direct,0,0,0,H,H,0,No Deposit,,,0,Transient,98.0,0,0
HB-072688,City Hotel,1,170,2025,August,31,3,2025-08-03,0,3,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,175.5,0,0
HB-098878,City Hotel,0,3,2024,October,40,2,2024-10-02,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,128.0,0,0
HB-045436,City Hotel,0,72,2023,October,43,28,2023-10-28,0,3,2,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,58,Transient-Party,85.67,0,0
HB-071213,City Hotel,1,159,2025,June,26,29,2025-06-29,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,120.06,0,0
HB-035192,Resort Hotel,0,22,2025,April,15,13,2025-04-13,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,127.0,0,1
HB-089077,City Hotel,0,95,2024,May,19,12,2024-05-12,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,102.1,0,1
HB-011025,Resort Hotel,1,267,2025,April,16,14,2025-04-14,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,59.79,0,0
HB-090522,City Hotel,0,247,2024,June,23,6,2024-06-06,1,1,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-038916,Resort Hotel,0,108,2025,July,31,29,2025-07-29,2,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,260.6,0,2
HB-026872,Resort Hotel,0,205,2024,August,32,6,2024-08-06,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,117.21,0,1
HB-028229,Resort Hotel,0,248,2024,September,39,23,2024-09-23,1,2,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,80.0,0,1
HB-095377,City Hotel,0,0,2024,August,33,17,2024-08-17,0,1,1,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,K,1,No Deposit,9.0,,0,Transient,138.0,0,0
HB-075194,City Hotel,1,292,2023,August,31,5,2023-08-05,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-010377,Resort Hotel,1,181,2025,March,9,1,2025-03-01,6,19,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,440.0,,0,Transient-Party,58.6,0,0
HB-071172,City Hotel,1,107,2025,June,26,29,2025-06-29,0,1,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,171.0,0,0
HB-118471,City Hotel,0,19,2025,August,34,19,2025-08-19,0,1,2,2.0,0,BB,CZE,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,270.0,0,0
HB-012643,Resort Hotel,1,4,2025,July,28,10,2025-07-10,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,125.0,0,1
HB-106443,City Hotel,0,16,2025,February,8,22,2025-02-22,0,4,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,100.73,0,1
HB-082708,City Hotel,0,23,2024,January,1,2,2024-01-02,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,26.0,,0,Transient-Party,109.0,0,0
HB-103810,City Hotel,0,190,2024,December,52,28,2024-12-28,0,4,2,0.0,0,BB,SWE,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,167.8,0,0
HB-102592,City Hotel,0,45,2024,November,48,28,2024-11-28,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.4,0,0
HB-048352,City Hotel,0,89,2024,March,12,21,2024-03-21,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,83.66,0,1
HB-098886,City Hotel,0,19,2024,October,40,2,2024-10-02,2,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-054823,City Hotel,1,391,2024,July,30,27,2024-07-27,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,65.0,0,0
HB-098765,City Hotel,0,5,2024,October,40,3,2024-10-03,1,0,1,0.0,0,SC,NLD,Direct,Direct,0,0,0,A,B,0,No Deposit,14.0,,0,Transient,140.0,0,2
HB-114928,City Hotel,0,207,2025,June,26,26,2025-06-26,1,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-073704,City Hotel,1,14,2025,August,35,31,2025-08-31,1,3,3,0.0,0,BB,KWT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,231.75,0,0
HB-080088,City Hotel,1,333,2024,September,38,20,2024-09-20,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,58.0,,19,Transient,90.0,0,0
HB-028535,Resort Hotel,0,143,2024,September,39,26,2024-09-26,3,7,1,0.0,0,HB,CN,Groups,TA/TO,0,0,0,E,E,0,No Deposit,15.0,,0,Transient-Party,83.0,0,0
HB-005722,Resort Hotel,0,236,2024,May,19,12,2024-05-12,0,3,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,315.0,,0,Transient-Party,50.0,1,0
HB-059137,City Hotel,1,263,2024,October,43,21,2024-10-21,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,0,Transient,110.0,0,0
HB-038411,Resort Hotel,0,104,2025,July,28,11,2025-07-11,1,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,203.0,0,1
HB-094763,City Hotel,0,73,2024,August,32,6,2024-08-06,2,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,9.0,,0,Transient,140.4,1,2
HB-042881,City Hotel,0,168,2023,September,37,11,2023-09-11,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,0.0,0,0
HB-014988,Resort Hotel,1,166,2023,July,28,15,2023-07-15,0,2,2,0.0,0,FB,PRT,Groups,TA/TO,0,24,0,A,A,0,Non Refund,,,0,Transient,121.5,0,0
HB-068567,City Hotel,1,105,2025,May,21,19,2025-05-19,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-095855,City Hotel,0,0,2024,August,34,24,2024-08-24,0,1,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,D,F,0,No Deposit,14.0,,0,Transient,155.25,1,1
HB-021921,Resort Hotel,0,1,2024,March,11,12,2024-03-12,0,1,2,0.0,1,BB,PRT,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,240.0,,0,Transient,58.0,0,1
HB-108469,City Hotel,0,35,2025,March,13,25,2025-03-25,2,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,91.33,0,1
HB-094044,City Hotel,0,125,2024,July,31,29,2024-07-29,0,1,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.9,0,0
HB-095359,City Hotel,0,63,2024,August,33,15,2024-08-15,1,2,2,0.0,0,SC,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,63.75,0,0
HB-100652,City Hotel,0,0,2024,October,44,30,2024-10-30,1,0,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,0
HB-058554,City Hotel,1,37,2024,October,41,13,2024-10-13,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,105.0,0,0
HB-079209,City Hotel,0,27,2023,October,42,18,2023-10-18,2,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-067984,City Hotel,1,23,2025,May,19,10,2025-05-10,2,4,2,2.0,0,HB,FRA,Online TA,TA/TO,0,0,0,F,F,2,No Deposit,9.0,,0,Transient,328.67,0,3
HB-027249,Resort Hotel,0,19,2024,August,33,18,2024-08-18,2,4,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,296.33,0,3
HB-119202,City Hotel,0,213,2025,August,35,28,2025-08-28,1,3,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,19.0,,0,Transient-Party,104.0,0,0
HB-012734,Resort Hotel,1,242,2025,July,29,14,2025-07-14,2,6,2,1.0,0,HB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,242.0,,0,Transient,233.1,0,1
HB-090353,City Hotel,0,1,2024,June,22,2,2024-06-02,0,3,2,0.0,0,BB,AGO,Online TA,Corporate,0,0,0,A,D,0,No Deposit,,263.0,0,Transient,120.0,0,1
HB-020065,Resort Hotel,0,1,2024,January,3,15,2024-01-15,0,1,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,39.0,0,1
HB-102438,City Hotel,0,45,2024,November,47,24,2024-11-24,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,96.9,0,2
HB-078397,City Hotel,0,1,2024,May,18,3,2024-05-03,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,9,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,1
HB-025608,Resort Hotel,0,167,2024,June,25,20,2024-06-20,4,10,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,128.0,,0,Transient,68.0,0,1
HB-001357,Resort Hotel,0,2,2023,August,34,26,2023-08-26,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,181.0,,0,Transient-Party,96.3,0,1
HB-041449,City Hotel,0,1,2023,August,33,16,2023-08-16,2,1,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,D,D,1,No Deposit,14.0,,0,Group,139.0,0,0
HB-067473,City Hotel,1,143,2025,May,18,4,2025-05-04,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,56.0,,0,Transient,120.0,0,0
HB-107776,City Hotel,0,2,2025,March,11,16,2025-03-16,0,2,1,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-117727,City Hotel,0,83,2025,August,32,8,2025-08-08,0,1,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,230.0,0,3
HB-116192,City Hotel,0,214,2025,July,28,13,2025-07-13,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient-Party,99.9,0,1
HB-089910,City Hotel,0,109,2024,May,21,25,2024-05-25,0,4,3,0.0,0,BB,GBR,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,157.5,0,2
HB-053929,City Hotel,1,38,2024,July,27,2,2024-07-02,1,1,1,0.0,0,SC,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,0
HB-105107,City Hotel,0,0,2025,January,5,30,2025-01-30,0,0,0,0.0,0,SC,PRT,Online TA,TA/TO,1,0,0,A,K,0,No Deposit,9.0,,0,Transient,0.0,0,0
HB-052294,City Hotel,1,111,2024,June,22,2,2024-06-02,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,132.6,0,0
HB-081820,City Hotel,1,211,2024,May,22,31,2024-05-31,0,3,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,3.0,,46,Transient,115.0,0,0
HB-068962,City Hotel,1,20,2025,May,21,24,2025-05-24,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,87.0,,0,Transient-Party,120.0,0,0
HB-002375,Resort Hotel,1,143,2023,October,41,10,2023-10-10,2,5,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,96.0,,0,Transient,36.05,0,0
HB-105988,City Hotel,0,70,2025,February,7,15,2025-02-15,0,4,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,242.0,0,Transient-Party,78.0,0,0
HB-062233,City Hotel,1,65,2025,January,1,5,2025-01-05,0,3,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,138.6,0,0
HB-113742,City Hotel,0,239,2025,June,23,4,2025-06-04,2,5,0,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient-Party,107.45,0,1
HB-106401,City Hotel,0,5,2025,February,8,23,2025-02-23,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,3
HB-096539,City Hotel,0,200,2024,August,35,31,2024-08-31,0,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.4,0,1
HB-028460,Resort Hotel,0,159,2024,September,39,27,2024-09-27,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,314.0,,0,Transient-Party,91.49,0,0
HB-091063,City Hotel,0,9,2024,June,24,12,2024-06-12,2,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,121.0,0,1
HB-027013,Resort Hotel,0,6,2024,August,33,16,2024-08-16,0,1,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,251.0,1,1
HB-100331,City Hotel,0,236,2024,October,43,22,2024-10-22,2,3,1,1.0,0,BB,CHE,Direct,Direct,0,0,0,B,B,0,No Deposit,14.0,,0,Transient-Party,81.28,0,0
HB-079459,City Hotel,1,137,2024,January,4,27,2024-01-27,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,29.0,,45,Transient,70.0,0,0
HB-117501,City Hotel,0,0,2025,August,31,3,2025-08-03,0,2,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,119.6,0,1
HB-054335,City Hotel,1,8,2024,July,28,13,2024-07-13,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,151.0,0,1
HB-074292,City Hotel,1,309,2023,August,34,22,2023-08-22,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-098771,City Hotel,0,102,2024,October,40,2,2024-10-02,2,1,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-094421,City Hotel,0,182,2024,August,31,3,2024-08-03,0,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,9.0,,0,Transient,94.5,0,1
HB-004340,Resort Hotel,1,49,2024,March,10,5,2024-03-05,2,2,1,0.0,0,HB,PRT,Groups,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient-Party,66.0,0,0
HB-005687,Resort Hotel,0,203,2024,May,19,10,2024-05-10,0,2,1,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,1,No Deposit,248.0,,0,Transient-Party,30.0,0,0
HB-046351,City Hotel,0,160,2023,December,52,30,2023-12-30,0,3,2,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,111,Transient-Party,70.67,0,0
HB-012589,Resort Hotel,1,130,2025,July,27,6,2025-07-06,1,3,1,2.0,0,HB,NOR,Direct,Direct,0,0,0,G,G,1,No Deposit,250.0,,0,Transient,247.0,0,0
HB-012185,Resort Hotel,1,94,2025,June,25,17,2025-06-17,0,1,2,0.0,0,HB,GBR,Direct,Direct,0,0,0,A,A,1,No Deposit,250.0,,0,Transient,135.5,0,0
HB-058539,City Hotel,1,37,2024,October,41,13,2024-10-13,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,95.0,0,0
HB-095308,City Hotel,0,3,2024,August,33,15,2024-08-15,1,2,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,228.33,0,1
HB-027865,Resort Hotel,0,245,2024,September,36,6,2024-09-06,2,5,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,D,E,0,No Deposit,,,0,Transient-Party,86.71,0,2
HB-094636,City Hotel,0,137,2024,August,31,4,2024-08-04,1,3,3,0.0,0,BB,UKR,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,136.34,0,1
HB-019768,Resort Hotel,0,17,2025,February,9,26,2025-02-26,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,1,0,2,A,A,0,No Deposit,240.0,,0,Transient,48.0,1,4
HB-079743,City Hotel,0,40,2023,October,44,31,2023-10-31,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Transient,65.0,0,0
HB-057192,City Hotel,1,123,2024,September,38,20,2024-09-20,1,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,143.1,0,1
HB-097042,City Hotel,0,277,2024,September,36,5,2024-09-05,2,5,2,0.0,0,HB,NOR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,89.14,0,1
HB-078003,City Hotel,1,282,2023,October,41,10,2023-10-10,2,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,4.0,,0,Transient-Party,96.0,0,0
HB-108598,City Hotel,0,66,2025,March,13,27,2025-03-27,1,2,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,77.69,0,1
HB-082342,City Hotel,1,94,2024,March,10,4,2024-03-04,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,154.0,,28,Transient,80.0,0,0
HB-115061,City Hotel,0,330,2025,June,27,30,2025-06-30,0,1,1,1.0,0,BB,GBR,Direct,Direct,0,0,0,B,A,0,No Deposit,14.0,,0,Transient-Party,108.5,0,0
HB-108382,City Hotel,0,4,2025,March,13,24,2025-03-24,0,2,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient,170.0,0,0
HB-061343,City Hotel,1,517,2024,December,49,8,2024-12-08,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-039825,Resort Hotel,0,21,2025,August,35,25,2025-08-25,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,224.0,0,2
HB-061176,City Hotel,1,23,2024,December,49,3,2024-12-03,2,1,3,0.0,0,BB,TUR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,154.0,0,1
HB-015091,Resort Hotel,1,167,2023,July,27,7,2023-07-07,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,240.0,,0,Transient,110.7,0,1
HB-001499,Resort Hotel,1,14,2023,September,35,1,2023-09-01,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,113.0,0,0
HB-007563,Resort Hotel,0,291,2024,August,33,15,2024-08-15,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,126.0,0,2
HB-068737,City Hotel,1,113,2025,May,21,20,2025-05-20,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,34.0,,0,Transient,190.0,0,0
HB-087611,City Hotel,0,34,2024,April,17,22,2024-04-22,0,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,105.3,0,1
HB-008645,Resort Hotel,1,393,2024,October,41,8,2024-10-08,2,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,68.0,,0,Transient,72.0,0,0
HB-073969,City Hotel,1,279,2023,July,29,23,2023-07-23,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Contract,62.0,0,0
HB-015614,Resort Hotel,0,153,2023,July,29,21,2023-07-21,2,5,3,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,133.95,0,3
HB-015753,Resort Hotel,0,53,2023,July,29,22,2023-07-22,2,8,2,0.0,0,FB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,2,No Deposit,15.0,,0,Transient,111.2,0,0
HB-052477,City Hotel,1,213,2024,June,23,7,2024-06-07,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,62,Transient,130.0,0,0
HB-004087,Resort Hotel,1,140,2024,February,7,12,2024-02-12,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,50.0,0,0
HB-067731,City Hotel,1,162,2025,May,19,6,2025-05-06,2,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,80.0,0,0
HB-054815,City Hotel,1,391,2024,July,30,27,2024-07-27,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,65.0,0,0
HB-074981,City Hotel,1,260,2023,July,27,4,2023-07-04,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-021388,Resort Hotel,0,9,2024,February,9,27,2024-02-27,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,68.0,0,1
HB-077194,City Hotel,0,8,2023,September,36,9,2023-09-09,0,4,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,54.75,0,0
HB-011708,Resort Hotel,1,304,2025,May,22,26,2025-05-26,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,72.0,0,0
HB-020629,Resort Hotel,0,1,2024,February,5,4,2024-02-04,0,1,1,0.0,0,HB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,20.0,0,Transient,46.0,0,0
HB-019412,Resort Hotel,0,0,2024,March,11,11,2024-03-11,0,2,2,0.0,0,BB,PRT,Direct,Direct,1,0,1,D,F,0,No Deposit,,,0,Transient,71.0,1,1
HB-103287,City Hotel,0,29,2024,December,51,17,2024-12-17,0,1,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,144.0,0,0
HB-030492,Resort Hotel,0,2,2024,December,50,15,2024-12-15,0,1,1,0.0,0,BB,PRT,Direct,Direct,1,0,1,A,D,0,No Deposit,,421.0,0,Transient,39.0,0,0
HB-043412,City Hotel,1,74,2023,September,38,18,2023-09-18,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-061599,City Hotel,1,192,2024,December,51,18,2024-12-18,2,1,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.0,0,1
HB-092780,City Hotel,0,166,2024,July,27,7,2024-07-07,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.95,0,2
HB-087275,City Hotel,0,122,2024,April,16,15,2024-04-15,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,151.0,,56,Transient,40.5,0,0
HB-035748,Resort Hotel,0,24,2025,April,18,30,2025-04-30,1,0,2,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,100.0,0,1
HB-075622,City Hotel,1,281,2023,July,30,25,2023-07-25,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-107091,City Hotel,0,137,2025,March,10,6,2025-03-06,1,1,1,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,A,1,No Deposit,37.0,,0,Transient-Party,65.0,0,0
HB-052306,City Hotel,1,177,2024,June,23,3,2024-06-03,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,119.0,,0,Transient-Party,100.0,0,0
HB-034596,Resort Hotel,0,0,2025,March,13,27,2025-03-27,1,2,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,337.0,,0,Transient,60.0,0,0
HB-080704,City Hotel,0,32,2023,November,47,20,2023-11-20,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,119.0,,0,Transient-Party,73.0,0,0
HB-078000,City Hotel,0,0,2023,September,39,30,2023-09-30,0,0,1,0.0,0,SC,ESP,Groups,Direct,1,0,0,A,B,0,No Deposit,,,0,Transient,0.0,0,0
HB-019873,Resort Hotel,0,3,2024,January,1,5,2024-01-05,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,0
HB-047004,City Hotel,0,42,2024,February,5,3,2024-02-03,0,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,80.3,0,1
HB-018112,Resort Hotel,0,28,2023,November,44,4,2023-11-04,0,1,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,251.0,,0,Transient,36.0,0,0
HB-004638,Resort Hotel,1,106,2024,March,12,24,2024-03-24,1,3,2,0.0,0,FB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,68.0,,0,Transient,84.0,0,0
HB-055434,City Hotel,1,195,2024,August,33,13,2024-08-13,0,1,2,1.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,121.5,0,0
HB-026649,Resort Hotel,0,0,2024,August,32,7,2024-08-07,0,0,2,0.0,0,BB,PRT,Direct,Direct,1,0,0,A,A,0,No Deposit,,,0,Transient,0.0,0,0
HB-016355,Resort Hotel,0,83,2023,August,33,17,2023-08-17,3,6,1,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,3,No Deposit,,,0,Transient-Party,150.6,0,1
HB-044914,City Hotel,1,100,2023,October,42,16,2023-10-16,0,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient,108.0,0,0
HB-044404,City Hotel,0,40,2023,October,40,5,2023-10-05,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,3.0,,40,Transient-Party,70.0,0,0
HB-069297,City Hotel,1,180,2025,May,22,29,2025-05-29,1,2,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-081935,City Hotel,1,278,2024,August,32,11,2024-08-11,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,65.0,0,0
HB-037717,Resort Hotel,0,332,2025,June,26,25,2025-06-25,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,40.0,,0,Contract,64.42,0,0
HB-023328,Resort Hotel,0,18,2024,April,15,9,2024-04-09,4,9,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,95.0,,0,Transient,52.2,0,0
HB-067397,City Hotel,1,8,2025,May,18,3,2025-05-03,0,2,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,,,0,Transient,210.0,0,0
HB-095439,City Hotel,0,156,2024,August,33,14,2024-08-14,2,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,115.25,1,1
HB-079492,City Hotel,0,12,2023,November,47,25,2023-11-25,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,40.0,0,Transient-Party,65.0,0,0
HB-057281,City Hotel,1,187,2024,September,38,22,2024-09-22,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.85,0,1
HB-036560,Resort Hotel,0,0,2025,May,21,23,2025-05-23,0,1,2,0.0,0,BB,AUS,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,112.0,1,0
HB-096387,City Hotel,0,27,2024,August,35,31,2024-08-31,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,110.0,0,3
HB-012910,Resort Hotel,1,174,2025,July,30,22,2025-07-22,3,6,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,160.0,0,0
HB-016456,Resort Hotel,0,77,2023,August,34,24,2023-08-24,1,5,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,150.83,0,2
HB-092882,City Hotel,0,131,2024,July,28,10,2024-07-10,2,2,2,1.0,0,BB,DNK,Online TA,TA/TO,0,0,0,A,D,2,No Deposit,9.0,,0,Transient,136.5,0,2
HB-006933,Resort Hotel,0,309,2024,July,28,12,2024-07-12,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,240.0,,0,Transient,84.9,1,2
HB-031082,Resort Hotel,0,7,2024,December,50,13,2024-12-13,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,45.0,1,0
HB-098813,City Hotel,0,95,2024,October,40,2,2024-10-02,2,1,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,2
HB-081759,City Hotel,1,113,2024,February,8,25,2024-02-25,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,44,Transient,75.0,0,0
HB-025581,Resort Hotel,0,60,2024,June,26,30,2024-06-30,0,3,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,218.33,1,0
HB-059659,City Hotel,1,244,2024,October,44,30,2024-10-30,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.85,0,0
HB-117503,City Hotel,0,39,2025,August,31,2,2025-08-02,0,3,2,0.0,0,BB,USA,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,153.0,0,3
HB-114679,City Hotel,0,17,2025,June,26,25,2025-06-25,0,0,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,0.0,0,0
HB-015490,Resort Hotel,0,59,2023,July,28,16,2023-07-16,2,3,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,147.0,0,0
HB-116727,City Hotel,0,423,2025,July,30,22,2025-07-22,1,1,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,95.5,0,0
HB-054023,City Hotel,1,73,2024,July,27,6,2024-07-06,0,2,1,0.0,0,SC,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,0
HB-093017,City Hotel,0,79,2024,July,28,11,2024-07-11,1,4,3,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.5,0,0
HB-092126,City Hotel,0,144,2024,June,26,27,2024-06-27,1,3,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,80.75,0,0
HB-047532,City Hotel,0,54,2024,February,9,26,2024-02-26,0,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.3,0,0
HB-042439,City Hotel,0,2,2023,September,36,5,2023-09-05,2,2,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,0.0,0,0
HB-050065,City Hotel,1,142,2024,April,17,22,2024-04-22,2,3,1,0.0,0,BB,POL,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,89.0,0,0
HB-087338,City Hotel,0,73,2024,April,16,15,2024-04-15,1,2,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,137.7,0,2
HB-087695,City Hotel,0,1,2024,April,17,22,2024-04-22,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,152.0,,0,Transient,67.76,0,1
HB-007558,Resort Hotel,1,212,2024,August,33,14,2024-08-14,4,10,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,160.0,0,2
HB-038257,Resort Hotel,0,3,2025,July,28,10,2025-07-10,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,89.6,0,1
HB-019180,Resort Hotel,0,0,2023,December,49,9,2023-12-09,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,118.0,0,Transient,35.0,0,0
HB-015957,Resort Hotel,0,2,2023,August,32,8,2023-08-08,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient,189.9,0,3
HB-090335,City Hotel,0,2,2024,June,23,3,2024-06-03,0,2,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,20.0,,0,Transient-Party,90.0,0,0
HB-002641,Resort Hotel,1,148,2023,October,43,24,2023-10-24,0,1,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,47.0,0,0
HB-036915,Resort Hotel,0,353,2025,May,21,25,2025-05-25,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,6.0,,0,Transient,80.0,0,0
HB-083241,City Hotel,0,0,2024,January,4,25,2024-01-25,1,0,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,100.0,0,0
HB-004880,Resort Hotel,1,116,2024,April,14,4,2024-04-04,2,5,2,0.0,0,HB,GBR,Groups,Direct,0,0,0,D,D,0,Non Refund,273.0,,0,Transient,72.0,0,0
HB-118544,City Hotel,0,96,2025,August,34,20,2025-08-20,2,0,1,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,98.0,,0,Transient-Party,115.0,0,0
HB-054102,City Hotel,1,55,2024,July,27,7,2024-07-07,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,219.0,0,Transient-Party,79.0,0,0
HB-026935,Resort Hotel,0,13,2024,August,32,8,2024-08-08,2,5,3,0.0,0,HB,DEU,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,161.1,0,2
HB-068738,City Hotel,1,29,2025,May,21,20,2025-05-20,2,1,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,190.0,0,0
HB-088832,City Hotel,0,32,2024,July,27,7,2024-07-07,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,1,0,2,D,D,0,No Deposit,9.0,,0,Transient,149.4,0,1
HB-053279,City Hotel,1,350,2024,June,25,17,2024-06-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,140.0,0,0
HB-022938,Resort Hotel,0,26,2024,April,15,8,2024-04-08,0,2,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,D,D,1,No Deposit,250.0,,0,Transient,93.0,0,1
HB-052427,City Hotel,1,118,2024,June,23,6,2024-06-06,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,37.0,,0,Transient-Party,120.0,0,0
HB-013922,Resort Hotel,0,0,2024,April,17,26,2024-04-26,0,2,1,0.0,0,BB,,Corporate,Corporate,0,0,3,A,D,0,No Deposit,,103.0,0,Transient,42.0,0,0
HB-108535,City Hotel,0,158,2025,March,13,27,2025-03-27,1,1,2,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,95.0,0,1
HB-027142,Resort Hotel,0,124,2024,August,33,17,2024-08-17,0,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,191.0,0,1
HB-104079,City Hotel,0,23,2024,December,1,30,2024-12-30,2,4,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,115.9,0,2
HB-078247,City Hotel,1,8,2023,October,41,10,2023-10-10,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-102098,City Hotel,0,215,2024,November,47,21,2024-11-21,1,1,2,0.0,0,BB,ROU,Groups,Corporate,0,0,0,A,A,4,No Deposit,,233.0,0,Transient,85.0,0,0
HB-110307,City Hotel,0,130,2025,April,17,22,2025-04-22,2,2,2,0.0,0,SC,USA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,89.0,0,1
HB-065139,City Hotel,1,278,2025,March,13,25,2025-03-25,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient,90.0,0,0
HB-116495,City Hotel,0,167,2025,July,29,19,2025-07-19,0,2,2,0.0,0,BB,ARG,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,2
HB-072447,City Hotel,1,296,2025,July,31,28,2025-07-28,2,3,2,1.0,0,BB,DOM,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,183.08,0,0
HB-033794,Resort Hotel,0,7,2025,March,9,2,2025-03-02,0,3,1,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,1,No Deposit,,223.0,0,Transient-Party,29.0,0,0
HB-111859,City Hotel,0,11,2025,May,20,14,2025-05-14,2,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,114.0,0,1
HB-073746,City Hotel,1,265,2023,July,27,9,2023-07-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-010098,Resort Hotel,1,22,2025,February,7,11,2025-02-11,2,5,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,51.84,0,0
HB-112052,City Hotel,0,28,2025,May,20,16,2025-05-16,0,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,141.33,0,2
HB-105366,City Hotel,0,75,2025,February,6,3,2025-02-03,1,2,2,2.0,0,BB,ITA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,156.6,0,2
HB-064483,City Hotel,1,6,2025,March,11,10,2025-03-10,2,3,1,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,152.0,0,0
HB-041882,City Hotel,1,1,2023,August,34,26,2023-08-26,0,1,2,1.0,0,BB,PRT,Complementary,Direct,0,0,0,D,G,2,No Deposit,,45.0,0,Transient,0.0,0,2
HB-002240,Resort Hotel,0,33,2023,October,40,7,2023-10-07,0,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,66.3,1,2
HB-101548,City Hotel,0,17,2024,November,46,12,2024-11-12,1,1,2,0.0,0,SC,ZAF,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.0,0,2
HB-098632,City Hotel,0,2,2024,September,40,30,2024-09-30,0,2,2,0.0,0,BB,KAZ,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,209.5,0,2
HB-068090,City Hotel,1,223,2025,May,20,12,2025-05-12,2,2,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,79.0,,0,Transient,92.88,0,0
HB-044938,City Hotel,1,180,2023,October,42,16,2023-10-16,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,70.0,0,0
HB-116104,City Hotel,0,414,2025,July,28,13,2025-07-13,0,2,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,122.4,0,1
HB-025946,Resort Hotel,0,18,2024,July,29,15,2024-07-15,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,174.0,0,1
HB-007001,Resort Hotel,1,19,2024,July,29,16,2024-07-16,2,3,2,0.0,0,BB,LUX,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,194.0,0,0
HB-028221,Resort Hotel,0,0,2024,September,39,24,2024-09-24,0,1,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,195.0,0,0
HB-012514,Resort Hotel,1,174,2025,July,27,2,2025-07-02,2,5,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,182.86,0,1
HB-061428,City Hotel,1,9,2024,December,50,10,2024-12-10,0,1,0,2.0,0,BB,PRT,Complementary,Direct,0,0,0,B,A,0,No Deposit,,45.0,0,Transient-Party,0.0,0,1
HB-020109,Resort Hotel,0,43,2024,January,2,14,2024-01-14,0,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,29.0,0,0
HB-116274,City Hotel,0,172,2025,July,29,15,2025-07-15,1,1,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.1,0,0
HB-073555,City Hotel,1,65,2025,August,35,26,2025-08-26,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,83.0,,0,Transient,164.0,0,0
HB-109419,City Hotel,0,13,2025,April,15,10,2025-04-10,1,0,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,139.0,0,0
HB-109976,City Hotel,0,46,2025,April,16,17,2025-04-17,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,1
HB-003242,Resort Hotel,0,40,2023,November,47,24,2023-11-24,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,242.0,,0,Transient,41.4,1,2
HB-026289,Resort Hotel,0,98,2024,July,30,24,2024-07-24,2,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,172.0,1,1
HB-000908,Resort Hotel,0,1,2023,August,31,5,2023-08-05,0,0,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,I,0,No Deposit,240.0,,0,Transient,0.0,0,2
HB-077761,City Hotel,0,11,2023,September,38,23,2023-09-23,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,114.0,0,0
HB-075691,City Hotel,1,295,2023,August,32,8,2023-08-08,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-057919,City Hotel,1,49,2024,October,40,3,2024-10-03,1,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.8,0,2
HB-106373,City Hotel,0,0,2025,February,8,23,2025-02-23,0,1,1,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,152.0,,0,Transient,58.31,0,0
HB-073234,City Hotel,1,55,2025,August,33,17,2025-08-17,0,2,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,210.0,0,0
HB-097175,City Hotel,0,13,2024,September,37,12,2024-09-12,1,0,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,134.0,0,1
HB-104594,City Hotel,0,34,2025,January,3,18,2025-01-18,0,1,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,B,1,No Deposit,19.0,,0,Transient-Party,75.0,0,0
HB-008274,Resort Hotel,1,385,2024,September,38,21,2024-09-21,0,4,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,66.0,0,0
HB-056678,City Hotel,1,198,2024,September,37,9,2024-09-09,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,120.0,0,0
HB-067735,City Hotel,1,407,2025,May,19,6,2025-05-06,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-008755,Resort Hotel,0,364,2024,October,41,12,2024-10-12,1,4,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,G,3,No Deposit,,223.0,0,Transient-Party,137.0,1,1
HB-111300,City Hotel,0,144,2025,May,19,6,2025-05-06,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,52.0,,0,Transient-Party,90.0,0,1
HB-004805,Resort Hotel,0,0,2024,April,14,1,2024-04-01,0,2,1,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,D,0,Non Refund,,223.0,0,Transient-Party,60.0,0,0
HB-057895,City Hotel,1,28,2024,October,40,3,2024-10-03,1,0,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-049233,City Hotel,1,115,2024,April,15,8,2024-04-08,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,B,1,No Deposit,1.0,,34,Transient-Party,65.0,0,0
HB-072431,City Hotel,1,29,2025,July,31,28,2025-07-28,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,156.0,0,1
HB-076995,City Hotel,0,207,2023,August,34,21,2023-08-21,2,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient-Party,76.5,0,3
HB-054033,City Hotel,1,160,2024,July,27,6,2024-07-06,0,4,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.75,0,0
HB-065505,City Hotel,1,112,2025,April,14,4,2025-04-04,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,,385.0,0,Transient,95.0,0,0
HB-031839,Resort Hotel,0,0,2025,January,1,4,2025-01-04,0,4,1,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,E,2,No Deposit,,,0,Transient,0.0,0,1
HB-083137,City Hotel,0,12,2024,January,3,19,2024-01-19,0,2,1,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,19.0,,0,Transient-Party,71.0,0,0
HB-076705,City Hotel,0,3,2024,October,41,10,2024-10-10,1,3,1,0.0,0,BB,PRT,Corporate,Corporate,1,4,47,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,1
HB-017710,Resort Hotel,0,283,2023,October,41,12,2023-10-12,2,5,1,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,A,0,No Deposit,273.0,,0,Transient-Party,41.98,0,0
HB-034885,Resort Hotel,0,264,2025,April,14,1,2025-04-01,2,5,3,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,72.9,0,0
HB-066762,City Hotel,1,396,2025,April,17,25,2025-04-25,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-000701,Resort Hotel,0,115,2023,July,30,25,2023-07-25,4,6,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,120.6,0,2
HB-105339,City Hotel,0,4,2025,February,5,1,2025-02-01,0,4,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,2
HB-039045,Resort Hotel,0,173,2025,August,31,1,2025-08-01,0,5,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,C,C,3,No Deposit,314.0,,0,Transient,163.2,0,2
HB-069304,City Hotel,1,82,2025,May,22,29,2025-05-29,1,4,2,0.0,0,SC,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-083069,City Hotel,0,50,2024,January,2,14,2024-01-14,0,3,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,20.0,,43,Transient-Party,1.0,0,2
HB-079226,City Hotel,1,444,2024,December,48,1,2024-12-01,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,34.0,,39,Transient,75.0,0,0
HB-021270,Resort Hotel,0,0,2024,February,8,22,2024-02-22,1,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,51.0,1,1
HB-031325,Resort Hotel,0,54,2024,December,51,19,2024-12-19,1,4,1,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,43.0,0,1
HB-024728,Resort Hotel,0,0,2024,May,22,31,2024-05-31,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,109.0,0,0
HB-104886,City Hotel,0,4,2025,January,3,19,2025-01-19,2,4,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,86.0,,0,Transient,108.8,0,0
HB-118987,City Hotel,0,1,2025,August,35,27,2025-08-27,1,0,1,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,71.28,0,1
HB-065657,City Hotel,1,62,2025,April,14,6,2025-04-06,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,135.0,0,0
HB-022351,Resort Hotel,0,9,2024,March,12,20,2024-03-20,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,55.4,0,1
HB-071559,City Hotel,1,270,2025,July,28,7,2025-07-07,0,2,3,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,190.8,0,1
HB-049273,City Hotel,1,268,2024,April,15,8,2024-04-08,2,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,224,Transient-Party,78.0,0,0
HB-070894,City Hotel,1,319,2025,June,26,24,2025-06-24,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient,90.0,0,0
HB-108067,City Hotel,0,151,2025,March,12,20,2025-03-20,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,95.0,0,1
HB-075628,City Hotel,1,281,2023,July,30,25,2023-07-25,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-038281,Resort Hotel,0,30,2025,July,28,11,2025-07-11,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,194.0,0,1
HB-055661,City Hotel,1,405,2024,August,33,18,2024-08-18,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-053667,City Hotel,1,151,2024,June,26,27,2024-06-27,1,0,2,0.0,0,BB,PRT,Offline TA/TO,Corporate,0,0,0,E,E,0,Non Refund,191.0,,0,Transient,200.0,0,0
HB-094111,City Hotel,0,12,2024,July,31,30,2024-07-30,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,1
HB-118033,City Hotel,0,177,2025,August,32,10,2025-08-10,1,3,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,112.5,0,0
HB-034434,Resort Hotel,0,73,2025,March,12,18,2025-03-18,2,5,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,F,E,0,No Deposit,242.0,,0,Transient,85.0,1,1
HB-000677,Resort Hotel,0,51,2023,July,30,25,2023-07-25,2,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,142.0,,0,Transient,118.0,0,0
HB-015352,Resort Hotel,0,152,2023,July,26,2,2023-07-02,2,5,1,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Contract,60.35,0,2
HB-110930,City Hotel,0,2,2025,May,18,3,2025-05-03,0,1,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,180.0,0,2
HB-039028,Resort Hotel,0,231,2025,August,31,2,2025-08-02,0,4,2,0.0,1,HB,ESP,Online TA,TA/TO,0,0,0,D,D,3,No Deposit,240.0,,0,Transient,225.0,1,5
HB-017863,Resort Hotel,0,1,2023,October,43,23,2023-10-23,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,83.0,1,1
HB-055918,City Hotel,1,7,2024,August,34,24,2024-08-24,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,101.45,0,1
HB-016066,Resort Hotel,0,0,2023,August,32,12,2023-08-12,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient,192.0,0,1
HB-087205,City Hotel,0,70,2024,April,15,12,2024-04-12,0,4,0,3.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,B,B,0,No Deposit,20.0,,0,Transient-Party,9.0,0,1
HB-065441,City Hotel,1,57,2025,April,14,3,2025-04-03,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,0
HB-110068,City Hotel,0,20,2025,April,16,19,2025-04-19,0,2,2,0.0,0,SC,KOR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,115.0,0,2
HB-082487,City Hotel,0,11,2023,December,52,29,2023-12-29,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,E,F,0,No Deposit,167.0,,0,Transient,157.67,0,0
HB-078694,City Hotel,0,2,2023,December,50,17,2023-12-17,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,5,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-074396,City Hotel,1,290,2023,August,31,3,2023-08-03,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-039021,Resort Hotel,0,173,2025,July,30,26,2025-07-26,2,9,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,314.0,,0,Transient,132.91,0,0
HB-116773,City Hotel,0,180,2025,July,30,21,2025-07-21,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,162.33,1,1
HB-045751,City Hotel,0,98,2023,November,47,23,2023-11-23,1,2,1,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,D,0,No Deposit,37.0,,0,Transient-Party,70.0,0,0
HB-088943,City Hotel,0,36,2024,May,19,11,2024-05-11,0,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.9,0,1
HB-081637,City Hotel,1,130,2024,April,15,13,2024-04-13,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,29.0,,10,Transient,100.0,0,0
HB-069600,City Hotel,1,129,2025,June,23,2,2025-06-02,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,154.0,,0,Transient,130.0,0,0
HB-111301,City Hotel,0,169,2025,May,19,6,2025-05-06,2,1,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,52.0,,25,Transient-Party,80.0,0,0
HB-019459,Resort Hotel,0,0,2023,December,51,20,2023-12-20,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,48.0,0,0
HB-089287,City Hotel,0,97,2024,May,20,19,2024-05-19,0,1,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,116.1,0,1
HB-025301,Resort Hotel,0,162,2024,June,24,14,2024-06-14,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,55.44,0,1
HB-084553,City Hotel,0,5,2024,February,9,27,2024-02-27,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,81.07,1,2
HB-107167,City Hotel,0,174,2025,March,10,5,2025-03-05,2,2,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,90.0,0,1
HB-103311,City Hotel,0,253,2024,December,50,13,2024-12-13,1,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,73.95,0,2
HB-086860,City Hotel,0,53,2024,April,14,7,2024-04-07,0,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,137.7,0,0
HB-008926,Resort Hotel,1,386,2024,October,42,20,2024-10-20,1,3,2,0.0,0,BB,PRT,Groups,Corporate,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,49.0,0,0
HB-070436,City Hotel,1,43,2025,June,25,17,2025-06-17,0,1,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,144.0,0,1
HB-005382,Resort Hotel,1,12,2024,April,17,27,2024-04-27,0,3,2,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,A,A,1,No Deposit,385.0,,0,Transient-Party,72.0,0,0
HB-082245,City Hotel,1,97,2024,March,12,20,2024-03-20,2,5,1,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,9,Transient,79.43,0,0
HB-030213,Resort Hotel,0,51,2024,November,46,13,2024-11-13,2,2,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,52.4,0,1
HB-089753,City Hotel,0,119,2024,May,21,23,2024-05-23,1,2,1,0.0,0,BB,SWE,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,90.0,0,1
HB-096329,City Hotel,0,149,2024,August,35,27,2024-08-27,2,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,80.75,0,0
HB-014046,Resort Hotel,0,0,2024,February,5,2,2024-02-02,0,2,1,0.0,0,BB,,Direct,Direct,0,0,1,A,D,0,No Deposit,,,0,Transient,39.0,0,0
HB-041028,City Hotel,0,0,2023,August,32,11,2023-08-11,0,1,2,0.0,0,BB,PRT,Online TA,Direct,0,0,0,A,A,0,No Deposit,,49.0,0,Transient,111.6,0,0
HB-042808,City Hotel,0,6,2023,September,36,10,2023-09-10,2,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,134.83,0,1
HB-043566,City Hotel,1,141,2023,September,38,20,2023-09-20,1,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,90.0,0,0
HB-102293,City Hotel,0,159,2024,November,47,22,2024-11-22,0,4,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.0,0,2
HB-056134,City Hotel,1,14,2024,August,35,30,2024-08-30,0,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.0,0,0
HB-037053,Resort Hotel,0,105,2025,June,22,1,2025-06-01,1,3,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,E,E,1,No Deposit,250.0,,0,Transient,139.5,1,0
HB-041118,City Hotel,1,41,2023,August,32,12,2023-08-12,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-031791,Resort Hotel,0,6,2025,January,1,4,2025-01-04,0,3,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,468.0,,0,Transient,68.4,1,1
HB-027910,Resort Hotel,0,157,2024,September,37,11,2024-09-11,2,2,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,113.2,0,0
HB-059651,City Hotel,1,154,2024,October,44,30,2024-10-30,2,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,104.1,0,2
HB-038729,Resort Hotel,0,194,2025,July,29,17,2025-07-17,3,8,1,1.0,0,HB,CHE,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,159.85,0,0
HB-067830,City Hotel,1,88,2025,May,19,8,2025-05-08,1,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,170.0,,0,Transient,120.0,0,0
HB-106859,City Hotel,0,118,2025,March,9,1,2025-03-01,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,68.47,0,1
HB-093083,City Hotel,0,111,2024,July,29,16,2024-07-16,0,1,2,1.0,0,BB,DNK,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,121.5,0,1
HB-063848,City Hotel,1,58,2025,February,8,23,2025-02-23,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,132.0,,0,Transient,78.0,0,0
HB-053467,City Hotel,1,65,2024,June,25,21,2024-06-21,0,1,3,0.0,0,BB,AUS,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,132.3,0,0
HB-100238,City Hotel,0,386,2024,October,43,23,2024-10-23,2,0,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-037341,Resort Hotel,0,128,2025,June,24,13,2025-06-13,0,2,2,1.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,171.0,1,0
HB-073457,City Hotel,1,160,2025,August,34,22,2025-08-22,0,4,3,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,9.0,,0,Transient,202.5,0,0
HB-118138,City Hotel,0,145,2025,August,33,12,2025-08-12,2,1,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient-Party,129.83,1,0
HB-053510,City Hotel,1,82,2024,June,25,23,2024-06-23,0,1,2,0.0,0,SC,ISR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.5,0,0
HB-021965,Resort Hotel,0,2,2024,October,41,12,2024-10-12,0,1,1,0.0,0,BB,PRT,Corporate,TA/TO,1,0,3,A,D,0,No Deposit,,86.0,0,Transient,67.5,0,0
HB-068619,City Hotel,1,140,2025,May,21,19,2025-05-19,0,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,162.0,0,1
HB-095277,City Hotel,0,98,2024,August,33,14,2024-08-14,2,2,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,7.0,,0,Transient,78.35,0,1
HB-073824,City Hotel,1,300,2023,August,32,13,2023-08-13,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-099627,City Hotel,0,335,2024,October,41,13,2024-10-13,0,3,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,80.0,0,0
HB-078981,City Hotel,0,221,2023,October,42,17,2023-10-17,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,65.0,0,0
HB-098111,City Hotel,0,174,2024,September,38,22,2024-09-22,0,3,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,95.67,0,0
HB-052028,City Hotel,1,202,2024,May,22,29,2024-05-29,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,26.0,,0,Transient,90.0,0,0
HB-001623,Resort Hotel,0,61,2023,September,36,6,2023-09-06,2,4,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,128.0,0,0
HB-056567,City Hotel,1,163,2024,September,36,8,2024-09-08,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,44.0,,0,Transient-Party,110.0,0,0
HB-031571,Resort Hotel,0,31,2024,December,1,30,2024-12-30,0,2,2,0.0,0,HB,PRT,Groups,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,325.0,0,1
HB-006446,Resort Hotel,0,241,2024,June,24,11,2024-06-11,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient-Party,113.0,1,2
HB-093050,City Hotel,0,36,2024,July,29,15,2024-07-15,0,1,3,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,168.3,0,1
HB-039533,Resort Hotel,0,1,2025,August,34,18,2025-08-18,1,2,2,1.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,206.4,0,1
HB-065130,City Hotel,1,278,2025,March,13,25,2025-03-25,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient,90.0,0,0
HB-085975,City Hotel,0,14,2024,March,12,24,2024-03-24,0,1,2,1.0,0,HB,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,215.5,1,2
HB-012266,Resort Hotel,1,261,2025,June,25,21,2025-06-21,0,4,3,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,164.0,0,0
HB-062549,City Hotel,1,38,2025,January,3,14,2025-01-14,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,Non Refund,,67.0,0,Transient,75.0,0,0
HB-032609,Resort Hotel,0,3,2025,January,5,27,2025-01-27,1,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,35.11,0,1
HB-082564,City Hotel,0,0,2024,January,1,1,2024-01-01,0,1,3,1.0,0,BB,PRT,Direct,Direct,0,0,0,A,E,0,No Deposit,,,0,Transient,186.0,0,0
HB-011030,Resort Hotel,1,102,2025,April,16,15,2025-04-15,1,1,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,196.0,,0,Transient,102.5,0,0
HB-090868,City Hotel,0,57,2024,June,24,10,2024-06-10,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,90.67,0,1
HB-026637,Resort Hotel,0,248,2024,August,32,7,2024-08-07,2,0,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,3,No Deposit,240.0,,0,Transient,252.0,0,0
HB-071034,City Hotel,1,59,2025,June,26,27,2025-06-27,0,4,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,1
HB-096103,City Hotel,0,287,2024,August,34,24,2024-08-24,1,4,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,B,B,1,No Deposit,,,0,Transient,76.72,0,0
HB-057749,City Hotel,1,267,2024,September,40,30,2024-09-30,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,26.0,,0,Transient,95.0,0,0
HB-052758,City Hotel,1,103,2024,June,24,11,2024-06-11,1,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.9,0,0
HB-059571,City Hotel,1,109,2024,October,44,29,2024-10-29,2,1,2,2.0,0,BB,BRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,159.9,0,0
HB-026979,Resort Hotel,0,75,2024,August,33,13,2024-08-13,2,1,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,221.0,0,1
HB-111670,City Hotel,0,84,2025,May,19,11,2025-05-11,0,3,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,183.0,0,0
HB-116706,City Hotel,0,423,2025,July,30,22,2025-07-22,1,1,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,122.4,0,1
HB-049787,City Hotel,1,103,2024,April,16,19,2024-04-19,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,0,Transient,115.0,0,0
HB-061631,City Hotel,1,15,2024,December,51,20,2024-12-20,2,5,1,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.4,0,0
HB-113350,City Hotel,0,162,2025,June,23,3,2025-06-03,2,1,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,27.0,,0,Transient,84.6,0,0
HB-112819,City Hotel,0,122,2025,May,22,27,2025-05-27,1,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,104.0,0,0
HB-031991,Resort Hotel,0,22,2025,January,2,12,2025-01-12,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,48.0,0,1
HB-068076,City Hotel,1,262,2025,May,20,12,2025-05-12,1,2,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.1,0,1
HB-008475,Resort Hotel,1,35,2024,September,40,30,2024-09-30,2,3,1,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,A,3,No Deposit,240.0,,0,Transient,100.2,0,2
HB-019336,Resort Hotel,0,2,2023,December,49,7,2023-12-07,2,5,1,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,115.0,,0,Transient,34.2,0,0
HB-107970,City Hotel,0,7,2025,March,12,20,2025-03-20,1,0,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.0,0,0
HB-012828,Resort Hotel,1,39,2025,July,29,18,2025-07-18,0,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,116.5,0,0
HB-092442,City Hotel,0,14,2024,July,27,6,2024-07-06,0,1,1,0.0,0,BB,ESP,Corporate,Corporate,0,0,0,E,E,0,No Deposit,,18.0,0,Transient,143.0,0,0
HB-048189,City Hotel,1,34,2024,March,12,18,2024-03-18,0,2,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,162.45,0,0
HB-011053,Resort Hotel,1,158,2025,April,16,16,2025-04-16,2,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,70.8,0,1
HB-018403,Resort Hotel,0,6,2023,November,46,18,2023-11-18,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,104.0,,0,Transient,34.0,0,0
HB-061000,City Hotel,1,42,2024,November,48,29,2024-11-29,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,348.0,0,Transient,90.0,0,0
HB-053086,City Hotel,1,188,2024,June,24,15,2024-06-15,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,39,Transient,130.0,0,0
HB-069762,City Hotel,1,238,2025,June,23,5,2025-06-05,2,5,0,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient,106.35,0,1
HB-067301,City Hotel,1,157,2025,May,18,1,2025-05-01,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,130.0,0,0
HB-016827,Resort Hotel,0,25,2023,September,37,11,2023-09-11,1,2,2,0.0,0,HB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,135.67,0,1
HB-095532,City Hotel,0,156,2024,August,33,12,2024-08-12,2,6,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,106.89,0,1
HB-054831,City Hotel,1,63,2024,July,30,27,2024-07-27,0,4,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,121.05,0,0
HB-116251,City Hotel,0,10,2025,July,29,15,2025-07-15,1,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.0,0,2
HB-062292,City Hotel,1,129,2025,January,2,8,2025-01-08,2,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,D,D,0,Non Refund,,,0,Transient,67.0,0,0
HB-097740,City Hotel,0,3,2024,September,38,19,2024-09-19,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,1,No Deposit,,307.0,0,Transient-Party,148.13,1,0
HB-087581,City Hotel,0,30,2024,April,16,19,2024-04-19,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,103.5,0,0
HB-090503,City Hotel,0,247,2024,June,23,6,2024-06-06,1,1,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,F,0,No Deposit,6.0,,0,Transient-Party,111.0,0,0
HB-021829,Resort Hotel,0,81,2024,March,10,9,2024-03-09,0,3,3,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,A,D,0,No Deposit,115.0,,0,Transient-Party,86.55,0,0
HB-008443,Resort Hotel,1,63,2024,September,39,28,2024-09-28,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,96.0,,0,Transient-Party,76.0,0,0
HB-062405,City Hotel,1,62,2025,January,2,12,2025-01-12,2,7,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.4,0,1
HB-052216,City Hotel,0,172,2024,June,22,2,2024-06-02,0,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,94.95,0,0
HB-069272,City Hotel,1,228,2025,May,22,28,2025-05-28,2,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,44,Transient,130.0,0,0
HB-016214,Resort Hotel,0,59,2023,August,33,14,2023-08-14,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,F,0,No Deposit,240.0,,0,Transient,173.0,0,0
HB-015056,Resort Hotel,0,2,2025,February,7,15,2025-02-15,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,8,A,D,0,No Deposit,,270.0,0,Transient,35.0,0,0
HB-051065,City Hotel,0,309,2024,May,20,13,2024-05-13,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,215,Transient-Party,65.0,0,0
HB-100834,City Hotel,0,46,2024,October,44,30,2024-10-30,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-022752,Resort Hotel,0,41,2024,April,14,4,2024-04-04,0,0,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,I,2,No Deposit,314.0,,0,Transient,0.0,0,0
HB-052507,City Hotel,1,18,2024,June,23,7,2024-06-07,2,7,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,141.56,0,0
HB-014636,Resort Hotel,0,6,2023,November,47,24,2023-11-24,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,8.0,,0,Transient,45.0,0,0
HB-075774,City Hotel,1,323,2023,September,36,5,2023-09-05,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-003914,Resort Hotel,1,72,2024,February,6,6,2024-02-06,2,1,2,0.0,0,HB,PRT,Groups,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,73.33,0,0
HB-037530,Resort Hotel,0,236,2025,June,24,10,2025-06-10,4,7,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,314.0,,0,Transient-Party,115.68,0,0
HB-072983,City Hotel,1,88,2025,August,33,11,2025-08-11,1,2,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,195.0,0,0
HB-033744,Resort Hotel,0,4,2025,February,9,27,2025-02-27,1,2,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,74.0,1,2
HB-090703,City Hotel,0,0,2024,June,23,8,2024-06-08,0,2,1,0.0,0,BB,FRA,Offline TA/TO,Direct,0,0,0,A,A,0,No Deposit,191.0,,0,Transient-Party,110.0,0,0
HB-009469,Resort Hotel,1,128,2024,December,49,3,2024-12-03,0,1,2,0.0,0,HB,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,64.0,0,0
HB-002782,Resort Hotel,0,0,2023,October,44,31,2023-10-31,0,1,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,240.0,,0,Transient,49.0,0,0
HB-095109,City Hotel,0,117,2024,August,33,12,2024-08-12,1,2,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,155.7,0,1
HB-064601,City Hotel,1,52,2025,March,11,13,2025-03-13,1,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,56.0,,0,Transient,80.0,0,0
HB-071158,City Hotel,1,215,2025,June,26,28,2025-06-28,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-002540,Resort Hotel,1,19,2023,October,42,21,2023-10-21,0,2,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,208.0,,0,Transient-Party,60.0,0,0
HB-030104,Resort Hotel,0,19,2024,November,46,13,2024-11-13,1,0,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,0
HB-055312,City Hotel,1,405,2024,August,32,10,2024-08-10,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,65.0,0,0
HB-056452,City Hotel,1,230,2024,September,36,6,2024-09-06,0,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,44.0,,0,Transient-Party,137.0,0,0
HB-075568,City Hotel,0,257,2023,July,26,1,2023-07-01,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,101.5,0,0
HB-059940,City Hotel,1,32,2024,November,45,4,2024-11-04,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,124.0,0,1
HB-103542,City Hotel,0,87,2024,December,52,25,2024-12-25,2,0,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,0
HB-107089,City Hotel,0,137,2025,March,10,6,2025-03-06,1,1,2,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,80.0,0,1
HB-064913,City Hotel,1,50,2025,March,12,20,2025-03-20,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,91.8,0,0
HB-039665,Resort Hotel,0,160,2025,August,34,18,2025-08-18,2,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,314.0,,0,Transient,203.71,0,0
HB-061634,City Hotel,1,41,2024,December,51,21,2024-12-21,0,3,1,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,1
HB-019062,Resort Hotel,0,11,2023,December,49,5,2023-12-05,2,1,2,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,350.0,,0,Transient-Party,68.0,0,0
HB-080185,City Hotel,0,13,2025,February,7,13,2025-02-13,1,1,1,0.0,0,BB,FRA,Direct,Direct,1,0,2,A,A,1,No Deposit,,91.0,0,Transient,80.0,0,2
HB-065306,City Hotel,1,80,2025,March,14,31,2025-03-31,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,56.0,,0,Transient,90.0,0,0
HB-004929,Resort Hotel,1,121,2024,April,15,9,2024-04-09,2,5,2,0.0,0,HB,GBR,Groups,Direct,0,0,0,D,D,0,Non Refund,273.0,,0,Transient,72.0,0,0
HB-081566,City Hotel,1,223,2024,June,24,14,2024-06-14,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,133.0,,40,Transient,135.0,0,0
HB-016932,Resort Hotel,0,26,2024,February,7,15,2024-02-15,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,2,A,D,0,No Deposit,,86.0,0,Transient,38.0,0,0
HB-014264,Resort Hotel,0,16,2024,May,21,22,2024-05-22,2,1,1,0.0,0,BB,PRT,Direct,Corporate,0,1,5,A,A,1,No Deposit,,292.0,0,Transient,70.0,0,0
HB-036416,Resort Hotel,0,66,2025,May,20,13,2025-05-13,2,5,2,0.0,1,BB,PRT,Online TA,TA/TO,0,0,0,G,G,1,No Deposit,240.0,,0,Transient-Party,172.0,1,1
HB-083896,City Hotel,0,11,2024,February,7,13,2024-02-13,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,1,No Deposit,,,0,Transient,95.0,0,2
HB-015386,Resort Hotel,0,143,2023,July,27,9,2023-07-09,0,3,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,100.8,1,0
HB-027063,Resort Hotel,0,2,2024,August,33,17,2024-08-17,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,206.0,0,1
HB-021924,Resort Hotel,0,30,2024,March,11,11,2024-03-11,0,2,1,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,375.0,,0,Transient-Party,25.0,0,0
HB-098057,City Hotel,0,296,2024,September,38,21,2024-09-21,0,4,1,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,26.0,,0,Transient-Party,96.0,0,0
HB-063783,City Hotel,1,34,2025,February,8,20,2025-02-20,1,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,69.7,0,1
HB-037520,Resort Hotel,0,152,2025,June,25,20,2025-06-20,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,251.0,,0,Transient,80.0,0,0
HB-041015,City Hotel,0,0,2023,August,32,10,2023-08-10,1,1,2,0.0,0,BB,MOZ,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,75.0,0,0
HB-083327,City Hotel,0,33,2024,January,4,25,2024-01-25,1,3,2,0.0,0,BB,BRA,Corporate,Corporate,0,0,0,A,A,1,No Deposit,38.0,,15,Transient-Party,64.0,0,0
HB-062647,City Hotel,1,54,2025,January,3,18,2025-01-18,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,171.0,,0,Transient,65.0,0,0
HB-002882,Resort Hotel,0,24,2023,November,44,3,2023-11-03,3,10,1,0.0,0,BB,ITA,Corporate,Corporate,0,0,0,A,A,6,No Deposit,328.0,281.0,0,Transient,40.0,0,0
HB-053718,City Hotel,1,101,2024,June,26,27,2024-06-27,1,5,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,140.0,0,0
HB-050527,City Hotel,0,143,2024,May,18,2,2024-05-02,1,4,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,64.26,0,0
HB-106493,City Hotel,0,134,2025,February,9,25,2025-02-25,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,75.0,0,0
HB-034289,Resort Hotel,0,241,2025,March,12,17,2025-03-17,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,44.8,1,2
HB-078500,City Hotel,0,7,2023,October,40,8,2023-10-08,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,65.45,0,0
HB-043716,City Hotel,0,34,2023,September,38,23,2023-09-23,0,3,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,52.0,,33,Transient-Party,177.33,0,0
HB-022658,Resort Hotel,0,3,2024,March,13,28,2024-03-28,1,2,3,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,C,1,No Deposit,250.0,,0,Transient,78.0,1,0
HB-077785,City Hotel,1,2,2023,September,39,27,2023-09-27,2,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-016317,Resort Hotel,0,66,2023,August,33,17,2023-08-17,1,5,2,0.0,1,HB,ESP,Offline TA/TO,TA/TO,0,0,0,D,D,2,No Deposit,142.0,,0,Transient,149.2,0,1
HB-118348,City Hotel,0,108,2025,August,33,15,2025-08-15,0,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,130.5,0,0
HB-042328,City Hotel,0,82,2023,September,36,5,2023-09-05,0,1,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.25,1,2
HB-091531,City Hotel,0,41,2024,June,25,19,2024-06-19,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.45,0,1
HB-028991,Resort Hotel,0,339,2024,October,41,11,2024-10-11,2,5,2,0.0,0,BB,GBR,Groups,Direct,0,0,0,E,E,0,Refundable,273.0,,150,Transient-Party,80.81,0,0
HB-009028,Resort Hotel,1,35,2024,October,43,24,2024-10-24,1,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,60.0,0,0
HB-089747,City Hotel,0,123,2024,May,21,22,2024-05-22,2,2,2,0.0,1,BB,IRL,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient-Party,107.95,0,2
HB-018875,Resort Hotel,0,6,2023,December,48,1,2023-12-01,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,12.0,0,Transient,35.0,0,0
HB-083165,City Hotel,0,37,2024,January,4,22,2024-01-22,0,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,118.0,,0,Transient,0.0,0,0
HB-035733,Resort Hotel,0,70,2025,April,18,28,2025-04-28,0,2,1,0.0,0,BB,ZAF,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,58.52,0,1
HB-037150,Resort Hotel,0,4,2025,June,23,6,2025-06-06,0,3,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,C,0,No Deposit,,,0,Transient,128.0,0,0
HB-069819,City Hotel,1,23,2025,June,23,7,2025-06-07,0,2,2,0.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,52.0,,0,Transient,166.5,0,0
HB-009607,Resort Hotel,1,30,2024,December,51,19,2024-12-19,1,2,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,314.0,,0,Transient,64.4,0,0
HB-006771,Resort Hotel,1,178,2024,July,27,1,2024-07-01,2,5,2,0.0,1,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,81.0,0,1
HB-013695,Resort Hotel,1,90,2025,August,35,26,2025-08-26,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,201.43,0,1
HB-010081,Resort Hotel,1,89,2025,February,7,10,2025-02-10,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,C,3,No Deposit,240.0,,0,Transient,46.0,0,0
HB-018915,Resort Hotel,0,6,2023,December,48,1,2023-12-01,0,2,1,0.0,0,BB,ESP,Groups,Corporate,0,0,0,A,E,0,No Deposit,,343.0,0,Transient-Party,42.0,1,0
HB-111725,City Hotel,0,115,2025,May,20,12,2025-05-12,1,2,2,0.0,0,BB,LUX,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-074351,City Hotel,1,269,2023,July,28,13,2023-07-13,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Contract,62.0,0,0
HB-064564,City Hotel,1,52,2025,March,11,13,2025-03-13,1,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,56.0,,0,Transient,80.0,0,0
HB-117127,City Hotel,0,76,2025,July,30,27,2025-07-27,0,3,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,439.0,0,Transient,114.0,0,0
HB-071454,City Hotel,1,308,2025,July,27,5,2025-07-05,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,103.5,0,1
HB-041626,City Hotel,0,5,2023,August,33,19,2023-08-19,0,1,1,0.0,0,BB,PRT,Complementary,Corporate,0,0,0,A,A,0,No Deposit,45.0,,0,Transient,0.0,0,0
HB-059170,City Hotel,1,81,2024,October,43,21,2024-10-21,1,2,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.0,0,0
HB-048044,City Hotel,1,15,2024,March,11,13,2024-03-13,2,3,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,63.6,0,0
HB-028609,Resort Hotel,0,41,2024,October,40,3,2024-10-03,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,79.73,0,1
HB-072032,City Hotel,1,184,2025,July,29,18,2025-07-18,0,2,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,0
HB-103242,City Hotel,0,4,2024,December,51,16,2024-12-16,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,86.0,,0,Transient-Party,70.0,0,0
HB-100434,City Hotel,0,22,2024,October,43,25,2024-10-25,0,3,2,0.0,0,SC,AUT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,114.0,1,0
HB-106134,City Hotel,0,25,2025,February,8,19,2025-02-19,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-102317,City Hotel,0,6,2024,November,48,25,2024-11-25,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,95.0,0,1
HB-010041,Resort Hotel,1,18,2025,February,6,9,2025-02-09,2,7,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,242.0,,0,Transient,111.0,0,1
HB-044148,City Hotel,0,22,2023,October,39,1,2023-10-01,0,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,88.17,0,1
HB-027653,Resort Hotel,0,27,2024,September,36,2,2024-09-02,1,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,1,No Deposit,250.0,,0,Transient,155.0,0,1
HB-038130,Resort Hotel,0,334,2025,July,27,5,2025-07-05,1,4,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,6,No Deposit,250.0,,0,Transient-Party,123.38,0,0
HB-051526,City Hotel,1,212,2024,May,21,20,2024-05-20,2,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,78.0,0,0
HB-008013,Resort Hotel,1,211,2024,September,36,7,2024-09-07,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,D,D,0,Non Refund,1.0,,0,Transient,89.0,0,0
HB-032734,Resort Hotel,0,1,2025,February,6,3,2025-02-03,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,250.0,,0,Transient,43.0,0,0
HB-099659,City Hotel,0,377,2024,October,42,14,2024-10-14,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-101342,City Hotel,0,76,2024,November,45,6,2024-11-06,2,3,2,0.0,0,SC,KWT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,153.72,0,1
HB-099772,City Hotel,0,64,2024,October,42,14,2024-10-14,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,9.0,,0,Transient,132.3,0,1
HB-045162,City Hotel,0,61,2023,October,42,19,2023-10-19,1,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,89.25,0,2
HB-031776,Resort Hotel,0,43,2025,January,1,5,2025-01-05,0,1,2,0.0,0,HB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,59.66,1,1
HB-073804,City Hotel,1,286,2023,July,30,30,2023-07-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-001402,Resort Hotel,0,30,2023,August,35,28,2023-08-28,1,2,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,D,D,1,No Deposit,,,0,Transient,184.0,0,0
HB-004255,Resort Hotel,1,44,2024,February,9,27,2024-02-27,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,2
HB-070053,City Hotel,1,178,2025,June,24,9,2025-06-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,86.0,,0,Transient,130.0,0,0
HB-083537,City Hotel,0,13,2024,February,5,3,2024-02-03,0,4,1,0.0,0,BB,CHN,Corporate,Corporate,0,0,0,E,E,0,No Deposit,,183.0,0,Transient,86.0,0,0
HB-006847,Resort Hotel,0,317,2024,July,27,6,2024-07-06,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,240.0,,0,Transient,101.0,0,3
HB-064839,City Hotel,1,73,2025,March,12,17,2025-03-17,1,2,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,160.2,0,0
HB-012527,Resort Hotel,1,146,2025,July,27,3,2025-07-03,1,5,2,2.0,0,HB,ESP,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,206.33,0,1
HB-052120,City Hotel,1,113,2024,May,22,31,2024-05-31,0,3,1,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,A,0,Non Refund,,202.0,0,Transient,100.0,0,0
HB-096660,City Hotel,0,208,2024,September,36,3,2024-09-03,2,1,2,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,161.1,0,1
HB-058432,City Hotel,1,279,2024,October,41,12,2024-10-12,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,98.0,,0,Transient,110.0,0,0
HB-025283,Resort Hotel,0,294,2024,June,25,21,2024-06-21,0,5,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,64.8,0,1
HB-014108,Resort Hotel,0,237,2024,September,37,15,2024-09-15,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,243.0,,0,Contract,53.85,0,2
HB-017952,Resort Hotel,0,1,2025,February,8,21,2025-02-21,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,2,A,B,0,No Deposit,94.0,,0,Transient-Party,42.0,1,0
HB-080300,City Hotel,1,33,2023,December,49,9,2023-12-09,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,44.0,,0,Transient,110.0,0,0
HB-045664,City Hotel,0,140,2023,November,46,18,2023-11-18,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,D,2,No Deposit,29.0,,87,Transient-Party,65.0,0,0
HB-039261,Resort Hotel,0,189,2025,August,31,3,2025-08-03,2,8,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,314.0,,0,Transient-Party,163.08,0,0
HB-043783,City Hotel,1,86,2023,September,38,24,2023-09-24,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,120.0,0,0
HB-072745,City Hotel,1,198,2025,August,32,4,2025-08-04,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.5,0,0
HB-067041,City Hotel,1,111,2025,April,17,27,2025-04-27,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,0,Transient,120.0,0,0
HB-109627,City Hotel,0,78,2025,April,15,10,2025-04-10,1,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,119.25,0,1
HB-094221,City Hotel,0,5,2024,September,39,26,2024-09-26,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,3,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,1
HB-018964,Resort Hotel,0,2,2024,February,5,1,2024-02-01,1,1,1,0.0,0,BB,PRT,Online TA,TA/TO,1,0,1,A,D,0,No Deposit,240.0,,0,Transient,39.0,0,1
HB-080615,City Hotel,0,1,2023,November,46,19,2023-11-19,0,1,1,0.0,0,BB,BLR,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,110.0,0,1
HB-027559,Resort Hotel,0,219,2024,August,35,29,2024-08-29,1,3,2,0.0,0,BB,USA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,81.0,0,0
HB-040650,City Hotel,1,34,2023,August,31,5,2023-08-05,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-066946,City Hotel,1,242,2025,April,17,26,2025-04-26,0,4,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,126.9,0,2
HB-077922,City Hotel,0,1,2024,September,37,11,2024-09-11,2,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,1,1,0,A,B,0,No Deposit,6.0,,0,Transient,105.0,0,1
HB-042943,City Hotel,0,48,2023,September,37,11,2023-09-11,0,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,39.0,,48,Transient-Party,104.0,0,0
HB-078622,City Hotel,0,0,2023,October,41,11,2023-10-11,2,0,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,B,2,No Deposit,7.0,,0,Transient,88.94,0,0
HB-086242,City Hotel,0,77,2024,March,12,23,2024-03-23,2,6,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,27.0,,0,Transient,56.0,0,0
HB-107346,City Hotel,0,43,2025,March,11,11,2025-03-11,0,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,118.0,0,1
HB-059634,City Hotel,1,75,2024,October,44,30,2024-10-30,2,0,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,105.0,0,0
HB-011904,Resort Hotel,1,323,2025,June,23,3,2025-06-03,2,5,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,72.0,0,0
HB-006162,Resort Hotel,1,18,2024,May,22,27,2024-05-27,0,2,2,2.0,0,BB,USA,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,139.0,0,1
HB-043627,City Hotel,0,60,2023,September,38,21,2023-09-21,1,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,20.0,,0,Transient-Party,65.0,0,0
HB-064244,City Hotel,1,8,2025,March,9,2,2025-03-02,2,6,2,2.0,0,HB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,255.0,0,0
HB-100691,City Hotel,0,8,2024,October,44,29,2024-10-29,1,1,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,2,No Deposit,9.0,,0,Transient,170.0,0,2
HB-036276,Resort Hotel,0,156,2025,May,19,8,2025-05-08,2,5,1,0.0,0,HB,IRL,Groups,TA/TO,0,0,0,A,A,0,No Deposit,434.0,,0,Transient-Party,62.0,0,0
HB-026616,Resort Hotel,0,12,2024,August,31,2,2024-08-02,0,4,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,221.0,0,1
HB-093121,City Hotel,0,5,2024,July,28,14,2024-07-14,0,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,139.0,0,1
HB-105669,City Hotel,0,46,2025,February,7,11,2025-02-11,2,1,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,79.2,0,1
HB-084292,City Hotel,0,0,2024,February,8,21,2024-02-21,1,0,2,0.0,0,BB,AGO,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,100.0,0,0
HB-014070,Resort Hotel,0,2,2024,March,13,29,2024-03-29,0,0,1,0.0,0,BB,,Online TA,TA/TO,0,0,1,A,A,0,No Deposit,184.0,,0,Transient,0.0,0,0
HB-033118,Resort Hotel,0,44,2025,February,6,9,2025-02-09,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,36.12,0,0
HB-002702,Resort Hotel,1,114,2023,October,43,26,2023-10-26,7,16,1,0.0,0,BB,PRT,Groups,Corporate,0,0,0,A,A,0,Non Refund,281.0,,0,Contract,36.0,0,0
HB-114201,City Hotel,0,175,2025,June,24,15,2025-06-15,0,3,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,175.5,0,1
HB-068978,City Hotel,1,357,2025,May,21,24,2025-05-24,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.8,0,1
HB-084872,City Hotel,0,56,2024,March,9,3,2024-03-03,0,2,3,0.0,0,BB,PRT,Groups,Corporate,0,0,0,A,D,1,No Deposit,,,0,Transient-Party,103.0,0,0
HB-111171,City Hotel,0,152,2025,May,18,4,2025-05-04,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,139.5,0,2
HB-117872,City Hotel,0,0,2025,August,32,9,2025-08-09,0,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,9.0,,0,Transient,170.0,0,2
HB-105821,City Hotel,0,47,2025,February,7,12,2025-02-12,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.1,0,1
HB-041952,City Hotel,1,10,2023,August,35,28,2023-08-28,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Contract,80.0,0,1
HB-101588,City Hotel,0,12,2024,November,45,10,2024-11-10,2,3,2,0.0,0,BB,MEX,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,90.07,0,1
HB-071619,City Hotel,1,226,2025,July,28,9,2025-07-09,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-012091,Resort Hotel,1,94,2025,June,24,12,2025-06-12,3,5,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,160.0,0,1
HB-098876,City Hotel,0,42,2024,October,40,3,2024-10-03,1,2,2,0.0,0,BB,AUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,2
HB-081456,City Hotel,0,0,2023,December,50,11,2023-12-11,0,1,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,0.0,0,0
HB-093087,City Hotel,0,70,2024,July,28,11,2024-07-11,1,5,2,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,85.0,0,1
HB-008700,Resort Hotel,0,337,2024,October,41,9,2024-10-09,2,5,1,0.0,0,HB,GBR,Groups,Direct,0,0,0,A,A,1,No Deposit,273.0,,101,Transient-Party,44.81,0,0
HB-039323,Resort Hotel,0,132,2025,August,33,11,2025-08-11,2,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,135.0,0,0
HB-094094,City Hotel,0,188,2024,July,30,28,2024-07-28,0,3,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient-Party,80.75,0,0
HB-045995,City Hotel,1,134,2023,December,49,4,2023-12-04,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,91,Transient,65.0,0,0
HB-108063,City Hotel,0,151,2025,March,12,20,2025-03-20,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,95.0,0,0
HB-001509,Resort Hotel,1,97,2023,September,35,1,2023-09-01,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,120.71,0,0
HB-085938,City Hotel,0,44,2024,March,12,20,2024-03-20,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,9.0,,0,Transient,107.5,0,1
HB-078531,City Hotel,0,1,2023,October,41,9,2023-10-09,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,139.33,0,0
HB-079067,City Hotel,0,18,2023,October,42,16,2023-10-16,2,3,2,0.0,0,BB,JPN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,107.65,0,1
HB-094148,City Hotel,0,301,2024,July,31,30,2024-07-30,1,1,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,90.0,0,0
HB-111090,City Hotel,0,14,2025,May,18,2,2025-05-02,0,4,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,127.5,0,1
HB-032348,Resort Hotel,0,7,2025,January,4,23,2025-01-23,1,0,1,0.0,0,BB,PRT,Corporate,Direct,0,0,0,A,D,0,No Deposit,,195.0,0,Transient,35.0,0,0
HB-037400,Resort Hotel,0,159,2025,June,24,10,2025-06-10,2,5,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,80.47,0,1
HB-024178,Resort Hotel,0,4,2024,May,19,9,2024-05-09,1,4,2,0.0,0,BB,POL,Corporate,Corporate,0,0,0,E,E,0,No Deposit,,110.0,0,Transient,85.0,0,0
HB-077247,City Hotel,1,6,2023,September,38,20,2023-09-20,2,0,2,0.0,0,BB,PRT,Corporate,Corporate,0,1,0,A,A,0,Non Refund,78.0,,0,Transient,100.0,0,0
HB-097639,City Hotel,0,5,2024,September,38,17,2024-09-17,1,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,154.0,1,4
HB-096119,City Hotel,0,92,2024,August,35,26,2024-08-26,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.9,0,2
HB-039052,Resort Hotel,0,3,2025,August,32,4,2025-08-04,0,2,3,0.0,0,BB,PHL,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,241.0,,0,Transient,196.0,0,1
HB-048690,City Hotel,1,42,2024,March,13,27,2024-03-27,2,0,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,103.5,0,0
HB-005426,Resort Hotel,1,114,2024,April,18,29,2024-04-29,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,52.2,0,0
HB-054769,City Hotel,1,102,2024,July,30,26,2024-07-26,0,2,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.5,0,1
HB-028204,Resort Hotel,0,233,2024,September,37,11,2024-09-11,4,10,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Contract,90.76,0,2
HB-045881,City Hotel,0,98,2023,November,47,23,2023-11-23,1,3,2,0.0,0,BB,JOR,Groups,TA/TO,0,0,0,A,A,2,No Deposit,37.0,,0,Transient-Party,75.0,0,0
HB-008304,Resort Hotel,1,260,2024,September,38,21,2024-09-21,2,8,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,240.0,,0,Transient,85.5,0,1
HB-058697,City Hotel,1,162,2024,October,42,14,2024-10-14,2,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,34.0,,0,Transient,115.0,0,0
HB-030328,Resort Hotel,0,34,2024,November,47,18,2024-11-18,0,2,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,64.52,0,1
HB-058940,City Hotel,1,72,2024,October,42,18,2024-10-18,0,2,2,0.0,0,SC,ISR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-059544,City Hotel,1,222,2024,October,44,29,2024-10-29,0,1,2,2.0,0,HB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,219.6,0,0
HB-075702,City Hotel,1,295,2023,August,32,8,2023-08-08,2,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,60.0,0,0
HB-000687,Resort Hotel,0,54,2023,July,30,25,2023-07-25,2,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,147.0,0,0
HB-017259,Resort Hotel,1,277,2023,October,40,5,2023-10-05,4,10,2,0.0,0,HB,GBR,Groups,Direct,0,1,0,D,D,0,Non Refund,273.0,,0,Transient,78.5,0,0
HB-105540,City Hotel,0,28,2025,February,6,5,2025-02-05,2,4,1,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,97.65,0,1
HB-094508,City Hotel,0,28,2024,August,31,4,2024-08-04,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,125.1,0,1
HB-098537,City Hotel,0,54,2024,September,40,30,2024-09-30,0,1,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,132.3,0,1
HB-024765,Resort Hotel,0,69,2024,May,22,30,2024-05-30,1,2,2,0.0,1,HB,FRA,Online TA,TA/TO,0,0,0,A,C,2,No Deposit,240.0,,0,Transient,114.0,0,2
HB-043851,City Hotel,1,87,2023,September,39,25,2023-09-25,2,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-092807,City Hotel,0,1,2024,July,28,11,2024-07-11,1,0,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,152.0,,0,Transient,87.82,0,0
HB-084425,City Hotel,0,20,2024,February,8,24,2024-02-24,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,7.0,,0,Transient,67.22,0,2
HB-017433,Resort Hotel,0,16,2023,October,41,9,2023-10-09,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,1,No Deposit,,274.0,0,Transient-Party,48.0,0,0
HB-015297,Resort Hotel,0,31,2024,December,1,30,2024-12-30,0,2,2,0.0,0,HB,PRT,Complementary,Direct,1,0,2,E,E,3,No Deposit,,,0,Transient-Party,0.0,0,3
HB-023251,Resort Hotel,0,31,2024,April,16,18,2024-04-18,1,1,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,E,E,0,No Deposit,,,0,Transient,85.0,1,0
HB-057263,City Hotel,1,198,2024,September,38,22,2024-09-22,0,3,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,159.3,0,1
HB-108874,City Hotel,0,81,2025,March,14,31,2025-03-31,1,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,92.4,0,0
HB-095588,City Hotel,0,82,2024,August,34,19,2024-08-19,0,2,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,150.3,0,3
HB-023449,Resort Hotel,0,32,2024,April,16,19,2024-04-19,2,5,1,0.0,0,HB,GBR,Groups,Direct,0,0,0,A,C,0,No Deposit,273.0,,0,Transient-Party,46.36,0,0
HB-115181,City Hotel,0,33,2025,July,27,2,2025-07-02,1,0,2,0.0,0,SC,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,109.0,0,1
HB-089609,City Hotel,0,11,2024,May,19,9,2024-05-09,5,10,1,0.0,0,BB,ITA,Aviation,Corporate,0,0,0,A,A,0,No Deposit,,153.0,0,Transient,95.0,0,0
HB-065038,City Hotel,1,38,2025,March,12,23,2025-03-23,0,2,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,93.0,0,0
HB-114610,City Hotel,0,149,2025,June,26,24,2025-06-24,0,1,2,0.0,0,HB,USA,Corporate,Corporate,0,0,0,A,A,0,No Deposit,495.0,,0,Transient-Party,154.0,0,0
HB-075166,City Hotel,1,283,2023,July,30,27,2023-07-27,1,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,60.0,0,0
HB-042581,City Hotel,1,3,2023,September,36,7,2023-09-07,1,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,123.5,0,2
HB-048958,City Hotel,1,72,2024,April,14,3,2024-04-03,2,1,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,0
HB-033350,Resort Hotel,0,24,2025,February,8,17,2025-02-17,2,2,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,95.0,,0,Transient,60.0,0,0
HB-100750,City Hotel,0,8,2024,October,44,29,2024-10-29,2,1,1,0.0,0,SC,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,85.35,0,1
HB-042789,City Hotel,1,44,2023,September,36,10,2023-09-10,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,41.0,,0,Transient,126.0,0,0
HB-044839,City Hotel,0,60,2023,October,41,12,2023-10-12,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,3.0,,0,Transient-Party,65.0,0,1
HB-043578,City Hotel,0,141,2023,September,38,20,2023-09-20,1,0,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,90.0,0,1
HB-111058,City Hotel,0,41,2025,May,18,2,2025-05-02,0,4,2,2.0,0,BB,NLD,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,259.0,0,0
HB-049193,City Hotel,1,274,2024,April,14,7,2024-04-07,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-082075,City Hotel,0,0,2025,February,7,16,2025-02-16,0,1,1,0.0,0,BB,PRT,Complementary,Direct,1,0,2,A,A,0,No Deposit,,45.0,0,Transient,0.0,0,1
HB-092405,City Hotel,0,118,2024,June,26,26,2024-06-26,4,6,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,2,No Deposit,9.0,,0,Transient,113.33,0,2
HB-015514,Resort Hotel,0,126,2023,July,28,16,2023-07-16,2,6,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,154.8,1,1
HB-099427,City Hotel,0,206,2024,October,40,6,2024-10-06,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,102.85,0,1
HB-060140,City Hotel,1,157,2024,November,45,6,2024-11-06,2,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,117.68,0,1
HB-049608,City Hotel,1,90,2024,April,16,15,2024-04-15,2,5,2,0.0,0,BB,HUN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.95,0,0
HB-084267,City Hotel,0,16,2024,February,8,21,2024-02-21,1,0,1,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,86.0,0,1
HB-115939,City Hotel,0,139,2025,July,28,11,2025-07-11,0,2,3,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,152.1,0,1
HB-020216,Resort Hotel,0,6,2024,January,3,20,2024-01-20,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-037219,Resort Hotel,0,159,2025,June,24,10,2025-06-10,0,1,2,0.0,0,BB,NOR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,251.0,,0,Transient-Party,80.0,0,1
HB-112829,City Hotel,0,122,2025,May,22,27,2025-05-27,1,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,104.0,0,0
HB-016268,Resort Hotel,0,68,2023,August,33,16,2023-08-16,2,4,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,208.0,1,0
HB-107534,City Hotel,0,1,2025,March,11,13,2025-03-13,1,0,1,0.0,0,SC,DEU,Online TA,GDS,0,0,0,A,A,0,No Deposit,195.0,,0,Transient,88.0,0,0
HB-043357,City Hotel,1,74,2023,September,38,18,2023-09-18,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-039762,Resort Hotel,0,0,2025,August,35,27,2025-08-27,1,0,2,2.0,0,BB,CHE,Direct,Direct,0,0,0,H,H,1,No Deposit,,,0,Transient,220.5,1,0
HB-054886,City Hotel,0,207,2024,July,30,28,2024-07-28,2,4,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.75,0,0
HB-109605,City Hotel,0,83,2025,April,15,10,2025-04-10,1,3,2,1.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,100.0,0,0
HB-039024,Resort Hotel,0,45,2025,August,31,3,2025-08-03,0,3,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,242.0,,0,Transient,263.33,0,2
HB-029027,Resort Hotel,0,30,2024,October,42,15,2024-10-15,2,2,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,42.0,1,0
HB-018582,Resort Hotel,0,5,2023,November,47,22,2023-11-22,2,0,1,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,40.0,0,1
HB-106420,City Hotel,0,50,2025,February,8,20,2025-02-20,1,4,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,149.6,0,1
HB-083614,City Hotel,0,3,2024,February,6,8,2024-02-08,1,0,1,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient-Party,129.0,0,1
HB-093015,City Hotel,0,102,2024,July,28,10,2024-07-10,2,4,2,0.0,0,HB,BGR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,156.0,0,3
HB-057445,City Hotel,1,418,2024,September,39,26,2024-09-26,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,223,Transient-Party,75.0,0,0
HB-030735,Resort Hotel,0,1,2024,December,49,2,2024-12-02,0,1,3,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,93.0,0,0
HB-076056,City Hotel,1,364,2023,October,42,16,2023-10-16,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-037547,Resort Hotel,0,245,2025,June,24,12,2025-06-12,3,7,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,436.0,,0,Transient,85.7,0,0
HB-078412,City Hotel,0,21,2023,October,40,7,2023-10-07,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,F,0,No Deposit,9.0,,0,Contract,117.0,0,1
HB-081512,City Hotel,0,12,2024,January,4,24,2024-01-24,2,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,40.0,0,Transient-Party,66.0,0,1
HB-107794,City Hotel,0,182,2025,March,11,11,2025-03-11,2,6,2,0.0,0,BB,GBR,Corporate,TA/TO,0,0,0,A,A,0,No Deposit,330.0,,0,Transient-Party,90.0,0,1
HB-113948,City Hotel,0,5,2025,June,24,11,2025-06-11,2,2,2,0.0,0,BB,AUT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,159.0,,0,Transient,91.77,0,0
HB-054412,City Hotel,0,194,2024,July,29,15,2024-07-15,0,1,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient-Party,86.75,0,0
HB-073658,City Hotel,1,171,2025,August,35,29,2025-08-29,0,4,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,168.08,0,0
HB-061895,City Hotel,1,9,2024,December,52,28,2024-12-28,0,4,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,95.2,0,1
HB-058321,City Hotel,1,269,2024,October,41,10,2024-10-10,1,4,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,102.51,0,0
HB-076033,City Hotel,1,336,2023,September,38,18,2023-09-18,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-090771,City Hotel,0,70,2024,June,24,10,2024-06-10,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,85.0,0,1
HB-049904,City Hotel,1,265,2024,April,16,20,2024-04-20,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,30.0,,0,Transient,101.0,0,0
HB-037994,Resort Hotel,0,122,2025,June,27,30,2025-06-30,2,4,2,2.0,0,BB,ROU,Online TA,TA/TO,0,0,0,D,D,3,No Deposit,240.0,,0,Transient,151.67,0,1
HB-061380,City Hotel,1,305,2024,December,49,8,2024-12-08,1,3,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient-Party,63.75,0,1
HB-000756,Resort Hotel,1,101,2023,July,30,27,2023-07-27,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,219.43,0,2
HB-008574,Resort Hotel,1,383,2024,October,40,6,2024-10-06,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,315.0,,0,Transient-Party,48.0,0,0
HB-000894,Resort Hotel,0,94,2023,August,31,4,2023-08-04,0,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,F,0,No Deposit,240.0,,0,Transient,0.0,0,1
HB-004548,Resort Hotel,0,162,2024,March,12,24,2024-03-24,0,3,2,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,84.0,0,0
HB-106935,City Hotel,0,13,2025,March,9,2,2025-03-02,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,79.2,0,1
HB-104584,City Hotel,0,16,2025,January,3,15,2025-01-15,2,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,95.31,0,2
HB-071494,City Hotel,1,111,2025,July,27,6,2025-07-06,1,3,2,0.0,0,SC,AUT,Online TA,TA/TO,0,0,0,A,A,3,No Deposit,9.0,,0,Transient,108.0,0,0
HB-038317,Resort Hotel,0,27,2025,July,28,13,2025-07-13,0,2,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,194.0,0,1
HB-108896,City Hotel,0,37,2025,April,14,1,2025-04-01,1,1,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,1
HB-010269,Resort Hotel,1,26,2025,February,8,23,2025-02-23,2,5,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Transient,42.5,0,0
HB-032787,Resort Hotel,0,10,2025,February,6,3,2025-02-03,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,78.0,0,1
HB-107625,City Hotel,0,52,2025,March,11,12,2025-03-12,2,2,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,100.3,0,1
HB-083624,City Hotel,0,10,2024,February,6,8,2024-02-08,1,0,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,61.0,0,0
HB-048573,City Hotel,1,161,2024,March,13,25,2024-03-25,1,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,101,Transient,130.0,0,0
HB-043963,City Hotel,1,88,2023,September,39,26,2023-09-26,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-028273,Resort Hotel,0,285,2024,September,38,20,2024-09-20,2,5,2,0.0,0,BB,IRL,Groups,TA/TO,0,0,0,A,A,2,No Deposit,96.0,,0,Transient-Party,34.0,0,2
HB-108906,City Hotel,0,55,2025,March,13,30,2025-03-30,1,3,2,0.0,0,SC,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,86.9,0,0
HB-027065,Resort Hotel,0,1,2024,August,33,18,2024-08-18,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,191.0,1,3
HB-031994,Resort Hotel,0,259,2025,January,2,9,2025-01-09,1,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,55.8,0,2
HB-003759,Resort Hotel,1,113,2024,January,1,2,2024-01-02,0,1,2,0.0,0,HB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,305.0,,0,Transient,72.0,0,0
HB-111939,City Hotel,0,176,2025,May,20,15,2025-05-15,1,2,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,107.1,0,0
HB-059218,City Hotel,1,249,2024,October,43,22,2024-10-22,2,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,Non Refund,10.0,,20,Transient,80.75,0,0
HB-089956,City Hotel,0,32,2024,May,21,26,2024-05-26,1,3,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,7.0,,0,Transient,208.66,0,2
HB-034556,Resort Hotel,0,22,2025,March,13,27,2025-03-27,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,87.0,0,0
HB-097288,City Hotel,0,346,2024,September,37,13,2024-09-13,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-026671,Resort Hotel,0,203,2024,August,31,1,2024-08-01,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,127.71,0,1
HB-032738,Resort Hotel,0,0,2025,February,6,3,2025-02-03,0,1,1,0.0,0,BB,FIN,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,43.0,0,0
HB-015098,Resort Hotel,1,214,2023,October,40,3,2023-10-03,1,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,208.0,,0,Transient,34.0,0,0
HB-093081,City Hotel,0,85,2024,July,28,10,2024-07-10,2,5,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,140.27,0,2
HB-051142,City Hotel,1,121,2024,May,20,14,2024-05-14,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,96.0,0,0
HB-060811,City Hotel,1,44,2024,November,47,22,2024-11-22,0,3,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,82.13,0,0
HB-000071,Resort Hotel,1,62,2023,July,27,3,2023-07-03,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,97.0,0,1
HB-016463,Resort Hotel,0,198,2023,August,34,27,2023-08-27,0,3,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,156.0,,0,Contract,96.3,0,0
HB-042768,City Hotel,1,6,2023,September,36,10,2023-09-10,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,102.6,0,0
HB-091286,City Hotel,0,122,2024,June,24,16,2024-06-16,0,3,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,116.1,0,2
HB-078537,City Hotel,1,8,2023,October,42,20,2023-10-20,0,3,1,0.0,0,BB,PRT,Online TA,TA/TO,1,1,0,A,A,0,No Deposit,9.0,,0,Contract,120.0,0,2
HB-010979,Resort Hotel,1,86,2025,April,15,13,2025-04-13,2,3,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,93.94,0,0
HB-113865,City Hotel,0,32,2025,June,24,10,2025-06-10,2,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,133.33,0,0
HB-075673,City Hotel,1,295,2023,August,32,8,2023-08-08,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-108947,City Hotel,0,115,2025,April,14,1,2025-04-01,2,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,1
HB-097400,City Hotel,0,3,2024,September,37,15,2024-09-15,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,178.0,0,1
HB-112879,City Hotel,0,183,2025,May,22,28,2025-05-28,2,0,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,139.5,0,1
HB-071949,City Hotel,1,162,2025,July,29,15,2025-07-15,2,5,1,0.0,0,BB,LUX,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.1,0,0
HB-008123,Resort Hotel,0,422,2024,September,37,12,2024-09-12,3,7,2,0.0,1,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,3,No Deposit,2.0,,0,Contract,62.9,0,2
HB-018973,Resort Hotel,0,1,2023,December,48,3,2023-12-03,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,154.0,0,Transient,25.0,0,0
HB-041467,City Hotel,1,0,2023,August,33,17,2023-08-17,1,0,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,114.0,0,0
HB-043724,City Hotel,0,34,2023,September,38,23,2023-09-23,0,3,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,52.0,,33,Transient-Party,177.33,0,0
HB-092755,City Hotel,0,148,2024,July,27,1,2024-07-01,3,7,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,16.0,,0,Transient,102.25,0,0
HB-049104,City Hotel,1,105,2024,April,14,6,2024-04-06,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,0,Transient,75.0,0,0
HB-023221,Resort Hotel,0,91,2024,April,15,11,2024-04-11,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,115.0,,0,Transient,64.8,0,1
HB-019315,Resort Hotel,0,63,2024,November,47,18,2024-11-18,0,2,2,0.0,0,BB,PRT,Direct,TA/TO,1,0,1,A,A,1,No Deposit,250.0,,0,Transient,37.0,0,0
HB-002896,Resort Hotel,0,0,2023,November,44,5,2023-11-05,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,,0,Transient,40.0,0,0
HB-080209,City Hotel,0,33,2023,November,45,10,2023-11-10,0,4,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,27.0,,0,Group,42.0,0,1
HB-028241,Resort Hotel,0,0,2024,September,39,24,2024-09-24,1,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,G,G,0,No Deposit,,,0,Transient,167.5,0,0
HB-055840,City Hotel,1,141,2024,August,34,22,2024-08-22,1,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,103.05,0,0
HB-092040,City Hotel,0,20,2024,June,26,29,2024-06-29,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,75.0,0,0
HB-089855,City Hotel,0,2,2024,November,47,24,2024-11-24,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,1,No Deposit,,40.0,0,Transient,77.0,1,0
HB-109122,City Hotel,0,74,2025,April,14,3,2025-04-03,1,3,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,97.02,0,0
HB-019250,Resort Hotel,0,2,2023,December,49,9,2023-12-09,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-113184,City Hotel,0,132,2025,May,22,29,2025-05-29,1,5,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,9.0,,0,Transient,213.0,0,2
HB-046146,City Hotel,0,2,2023,December,50,17,2023-12-17,0,2,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,63.75,0,1
HB-068018,City Hotel,1,157,2025,May,19,11,2025-05-11,0,3,2,0.0,0,SC,LUX,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,2
HB-075524,City Hotel,1,355,2023,October,40,7,2023-10-07,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-000289,Resort Hotel,0,33,2023,July,28,11,2023-07-11,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,89.97,0,1
HB-064212,City Hotel,1,28,2025,March,9,2,2025-03-02,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,95.0,0,0
HB-033557,Resort Hotel,0,10,2025,February,9,24,2025-02-24,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,60.0,0,0
HB-036620,Resort Hotel,0,203,2025,May,21,25,2025-05-25,0,3,1,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,D,D,1,No Deposit,,223.0,0,Transient-Party,60.0,0,2
HB-068368,City Hotel,1,394,2025,May,20,16,2025-05-16,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient-Party,90.0,0,0
HB-025606,Resort Hotel,0,71,2024,June,26,30,2024-06-30,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,F,E,0,No Deposit,241.0,,0,Transient,140.14,0,2
HB-074562,City Hotel,1,346,2023,September,39,28,2023-09-28,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-084283,City Hotel,0,18,2024,February,8,21,2024-02-21,1,0,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.0,0,1
HB-089820,City Hotel,0,181,2024,May,21,23,2024-05-23,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,118.0,0,2
HB-030907,Resort Hotel,0,40,2024,December,48,1,2024-12-01,2,5,1,0.0,0,Undefined,FRA,Offline TA/TO,TA/TO,0,0,0,C,C,0,No Deposit,464.0,,0,Transient,48.0,0,0
HB-019154,Resort Hotel,0,0,2023,December,49,9,2023-12-09,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,43.0,0,0
HB-077890,City Hotel,0,18,2023,September,39,27,2023-09-27,2,1,1,0.0,0,BB,CHE,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,170.0,0,0
HB-018279,Resort Hotel,0,2,2025,March,10,6,2025-03-06,1,2,1,0.0,0,BB,GBR,Offline TA/TO,TA/TO,1,0,6,A,A,1,No Deposit,171.0,,0,Transient,30.0,0,1
HB-109320,City Hotel,0,1,2025,April,15,7,2025-04-07,1,2,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,120.0,0,1
HB-012075,Resort Hotel,1,192,2025,June,24,11,2025-06-11,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,88.0,0,0
HB-008568,Resort Hotel,0,383,2024,October,40,6,2024-10-06,0,3,1,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,1,No Deposit,315.0,,0,Transient-Party,44.0,0,0
HB-014979,Resort Hotel,1,166,2023,July,28,15,2023-07-15,0,2,2,0.0,0,FB,PRT,Groups,TA/TO,0,24,0,A,A,0,Non Refund,,,0,Transient,121.5,0,0
HB-001146,Resort Hotel,1,78,2023,August,33,15,2023-08-15,2,6,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,186.0,0,0
HB-012507,Resort Hotel,1,110,2025,July,27,2,2025-07-02,2,5,2,2.0,0,HB,ESP,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,238.0,0,1
HB-113520,City Hotel,0,17,2025,June,23,5,2025-06-05,1,2,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,156.67,0,2
HB-112328,City Hotel,0,100,2025,May,20,18,2025-05-18,2,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,28.0,,0,Contract,80.0,0,0
HB-071788,City Hotel,1,229,2025,July,28,12,2025-07-12,1,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-025690,Resort Hotel,0,9,2024,July,27,6,2024-07-06,0,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,159.0,1,1
HB-038278,Resort Hotel,0,152,2025,July,28,11,2025-07-11,0,3,2,0.0,0,BB,NOR,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,165.0,0,0
HB-017363,Resort Hotel,0,4,2023,October,40,6,2023-10-06,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,146.0,,0,Transient,43.0,1,0
HB-068833,City Hotel,1,101,2025,May,21,21,2025-05-21,2,1,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.0,0,0
HB-000029,Resort Hotel,0,77,2023,July,26,1,2023-07-01,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,94.0,0,0
HB-009083,Resort Hotel,1,248,2024,October,43,27,2024-10-27,0,3,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,70.0,0,1
HB-036179,Resort Hotel,0,257,2025,May,19,9,2025-05-09,0,4,2,0.0,0,HB,GBR,Groups,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,93.0,0,0
HB-115294,City Hotel,0,27,2025,July,27,2,2025-07-02,2,0,2,2.0,0,BB,BRA,Online TA,TA/TO,0,0,0,F,F,2,No Deposit,9.0,,0,Transient,250.0,0,0
HB-068449,City Hotel,1,127,2025,May,20,18,2025-05-18,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-111408,City Hotel,0,174,2025,May,19,9,2025-05-09,0,2,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,2
HB-051940,City Hotel,0,316,2024,May,21,26,2024-05-26,0,3,1,0.0,0,BB,AUT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,30.0,,0,Transient-Party,100.0,0,0
HB-030985,Resort Hotel,0,22,2024,December,49,8,2024-12-08,0,3,2,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,38.0,,0,Transient-Party,80.0,0,0
HB-049298,City Hotel,0,96,2024,April,15,9,2024-04-09,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,94.35,0,1
HB-091523,City Hotel,0,30,2024,June,25,19,2024-06-19,2,2,3,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,16.0,,0,Transient,111.6,0,1
HB-080777,City Hotel,1,180,2024,April,15,13,2024-04-13,0,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,21.0,,38,Transient,125.0,0,0
HB-103879,City Hotel,0,245,2024,December,52,29,2024-12-29,1,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,145.8,0,1
HB-012907,Resort Hotel,1,26,2025,July,30,22,2025-07-22,2,6,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,205.0,0,0
HB-102758,City Hotel,0,76,2024,December,49,3,2024-12-03,2,1,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,79.2,0,1
HB-117978,City Hotel,0,7,2025,August,32,10,2025-08-10,0,3,2,0.0,0,BB,MAR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,195.67,0,2
HB-106451,City Hotel,0,134,2025,February,9,25,2025-02-25,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,75.0,0,0
HB-044368,City Hotel,0,26,2023,October,40,4,2023-10-04,2,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,7.0,,0,Transient,80.85,0,1
HB-048396,City Hotel,1,43,2024,March,12,22,2024-03-22,0,3,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.2,0,0
HB-001432,Resort Hotel,0,47,2023,August,35,29,2023-08-29,2,1,1,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,103.18,0,1
HB-074979,City Hotel,1,260,2023,July,27,4,2023-07-04,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-028523,Resort Hotel,0,245,2024,September,39,26,2024-09-26,3,7,2,0.0,0,HB,CN,Groups,TA/TO,0,0,0,A,A,0,No Deposit,15.0,,0,Transient-Party,80.0,0,0
HB-054229,City Hotel,0,193,2024,July,28,9,2024-07-09,2,1,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,7.0,,0,Transient,76.85,0,1
HB-045932,City Hotel,0,84,2023,November,48,27,2023-11-27,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,64.0,0,0
HB-091447,City Hotel,0,125,2024,June,25,17,2024-06-17,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,128.69,0,1
HB-109327,City Hotel,0,3,2025,April,15,10,2025-04-10,1,2,2,0.0,0,SC,AGO,Online TA,Direct,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,150.0,0,2
HB-115474,City Hotel,0,405,2025,July,27,4,2025-07-04,0,2,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,91.5,0,0
HB-041686,City Hotel,0,2,2023,August,34,21,2023-08-21,2,2,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,79.0,0,0
HB-068693,City Hotel,1,165,2025,May,21,19,2025-05-19,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,225.0,0,0
HB-044995,City Hotel,0,102,2023,October,42,16,2023-10-16,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-088439,City Hotel,0,0,2024,May,18,5,2024-05-05,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,G,0,No Deposit,,216.0,0,Transient,111.2,0,0
HB-005852,Resort Hotel,1,9,2024,May,20,15,2024-05-15,1,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,315.0,,0,Transient-Party,70.0,0,0
HB-009468,Resort Hotel,1,45,2024,December,49,3,2024-12-03,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,56.0,0,1
HB-114884,City Hotel,0,168,2025,June,26,23,2025-06-23,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,100.48,0,1
HB-070243,City Hotel,1,13,2025,June,24,12,2025-06-12,1,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,150.0,0,1
HB-097977,City Hotel,0,2,2024,September,38,22,2024-09-22,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,F,1,No Deposit,9.0,,0,Transient,195.0,0,1
HB-029221,Resort Hotel,0,389,2024,October,43,23,2024-10-23,0,0,1,0.0,0,BB,PRT,Groups,Corporate,0,0,0,A,D,5,No Deposit,,,0,Transient-Party,0.0,0,0
HB-054463,City Hotel,1,156,2024,July,29,16,2024-07-16,2,3,2,1.0,0,BB,TUR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,111.35,0,2
HB-063639,City Hotel,1,86,2025,February,7,16,2025-02-16,0,3,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,138.6,0,1
HB-007166,Resort Hotel,1,42,2024,July,30,25,2024-07-25,1,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,209.0,0,0
HB-087225,City Hotel,0,1,2024,April,15,14,2024-04-14,0,2,1,0.0,0,BB,AUT,Aviation,Corporate,0,0,0,A,A,0,No Deposit,,153.0,0,Transient,95.0,0,0
HB-074792,City Hotel,1,336,2023,September,38,18,2023-09-18,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,6.0,,0,Transient-Party,109.0,0,0
HB-043259,City Hotel,0,56,2023,September,37,17,2023-09-17,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,20.0,,0,Transient-Party,82.0,0,0
HB-081625,City Hotel,1,130,2024,April,15,13,2024-04-13,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,29.0,,10,Transient,100.0,0,0
HB-037261,Resort Hotel,0,290,2025,May,22,29,2025-05-29,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,40.0,,0,Transient,85.7,0,0
HB-088325,City Hotel,0,24,2024,April,18,30,2024-04-30,2,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,133.5,0,1
HB-018749,Resort Hotel,0,6,2025,February,8,18,2025-02-18,0,1,2,2.0,0,BB,PRT,Direct,Direct,1,0,3,C,C,0,No Deposit,250.0,,0,Group,67.5,0,1
HB-038686,Resort Hotel,0,145,2025,July,29,20,2025-07-20,2,5,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,198.0,0,1
HB-116190,City Hotel,0,206,2025,July,28,10,2025-07-10,1,5,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,156.6,0,2
HB-024106,Resort Hotel,0,8,2024,May,19,8,2024-05-08,2,2,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Transient,72.0,0,0
HB-005921,Resort Hotel,1,95,2024,May,20,16,2024-05-16,1,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,73.0,0,1
HB-105010,City Hotel,0,198,2025,January,4,26,2025-01-26,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,1
HB-042841,City Hotel,0,8,2023,September,37,11,2023-09-11,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,100.0,0,0
HB-062290,City Hotel,1,129,2025,January,2,8,2025-01-08,2,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,D,D,0,Non Refund,,,0,Transient,67.0,0,0
HB-036094,Resort Hotel,0,85,2025,May,19,6,2025-05-06,2,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient-Party,102.0,0,1
HB-019906,Resort Hotel,1,8,2024,May,21,20,2024-05-20,0,1,1,0.0,0,BB,PRT,Groups,Corporate,1,1,1,D,D,1,Non Refund,,174.0,0,Transient-Party,94.5,0,0
HB-104852,City Hotel,0,38,2025,January,4,21,2025-01-21,1,1,1,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.0,0,1
HB-070845,City Hotel,1,233,2025,June,26,23,2025-06-23,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,105.0,0,0
HB-043335,City Hotel,0,74,2023,September,38,18,2023-09-18,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-045979,City Hotel,0,94,2023,December,49,4,2023-12-04,1,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,72.25,0,3
HB-060518,City Hotel,1,81,2024,November,46,13,2024-11-13,2,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,93.6,0,0
HB-022321,Resort Hotel,0,4,2024,March,12,20,2024-03-20,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,74.0,1,1
HB-042139,City Hotel,0,1,2023,September,35,1,2023-09-01,0,1,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Contract,95.0,0,1
HB-064052,City Hotel,1,121,2025,February,9,27,2025-02-27,1,3,3,1.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.9,0,2
HB-079902,City Hotel,0,45,2023,October,44,31,2023-10-31,2,5,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,90.64,0,2
HB-007739,Resort Hotel,1,41,2024,August,34,23,2024-08-23,0,5,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,287.0,0,0
HB-105033,City Hotel,0,4,2025,January,3,14,2025-01-14,4,10,1,0.0,0,BB,AGO,Offline TA/TO,TA/TO,0,0,0,A,E,2,No Deposit,128.0,,0,Transient,90.43,0,0
HB-058199,City Hotel,1,165,2024,October,41,7,2024-10-07,1,2,3,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,151.2,0,0
HB-117678,City Hotel,0,175,2025,August,32,7,2025-08-07,1,0,3,0.0,0,HB,POL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,155.1,0,3
HB-084218,City Hotel,0,99,2024,February,8,19,2024-02-19,0,2,1,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,D,1,No Deposit,,67.0,0,Transient-Party,81.0,0,0
HB-050996,City Hotel,1,79,2024,May,20,13,2024-05-13,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,159.3,0,1
HB-012181,Resort Hotel,1,308,2025,June,25,16,2025-06-16,3,7,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,80.1,0,1
HB-001794,Resort Hotel,1,175,2023,September,37,15,2023-09-15,0,4,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,15.0,,0,Transient-Party,0.0,0,0
HB-006422,Resort Hotel,1,151,2024,June,24,10,2024-06-10,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,99.0,0,0
HB-011152,Resort Hotel,1,31,2025,April,17,23,2025-04-23,1,0,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,E,1,No Deposit,298.0,,0,Transient-Party,74.0,0,0
HB-044304,City Hotel,1,89,2023,October,40,3,2023-10-03,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-011369,Resort Hotel,1,121,2025,May,18,4,2025-05-04,2,5,2,0.0,0,HB,IRL,Direct,Direct,0,0,0,D,D,2,No Deposit,250.0,,0,Transient,120.0,0,1
HB-045104,City Hotel,0,102,2023,October,42,16,2023-10-16,0,2,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,87.0,0,0
HB-063316,City Hotel,1,124,2025,February,6,7,2025-02-07,0,3,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,71.28,0,2
HB-006152,Resort Hotel,1,139,2024,May,21,26,2024-05-26,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,65.7,0,1
HB-103561,City Hotel,0,41,2024,December,52,27,2024-12-27,0,1,2,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,220.0,,0,Transient-Party,65.0,0,0
HB-054298,City Hotel,1,152,2024,July,28,11,2024-07-11,1,3,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,101.58,0,0
HB-107822,City Hotel,0,62,2025,March,11,15,2025-03-15,0,4,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,7.0,,0,Transient,48.5,0,1
HB-114206,City Hotel,0,33,2025,June,25,17,2025-06-17,0,1,2,0.0,0,SC,PRY,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,0
HB-095972,City Hotel,0,41,2024,August,34,24,2024-08-24,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient-Party,145.1,0,0
HB-106041,City Hotel,0,16,2025,February,7,16,2025-02-16,0,3,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,D,D,2,No Deposit,14.0,,0,Transient,105.55,0,1
HB-022032,Resort Hotel,0,36,2024,March,10,10,2024-03-10,2,5,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,59.14,2,2
HB-072548,City Hotel,1,333,2025,July,31,30,2025-07-30,4,5,2,1.0,0,BB,MAR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.7,0,0
HB-043871,City Hotel,1,87,2023,September,39,25,2023-09-25,2,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-041391,City Hotel,0,8,2023,August,33,15,2023-08-15,2,3,2,0.0,0,BB,NLD,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,75.0,0,0
HB-098487,City Hotel,0,33,2024,September,39,28,2024-09-28,0,2,1,0.0,0,BB,PRT,Complementary,TA/TO,0,0,0,A,E,0,No Deposit,,,0,Transient-Party,74.0,0,0
HB-101229,City Hotel,0,90,2024,November,45,7,2024-11-07,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,171.9,0,1
HB-044188,City Hotel,0,164,2023,October,40,2,2023-10-02,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,19.0,,0,Transient-Party,100.0,0,0
HB-064772,City Hotel,1,615,2025,March,11,16,2025-03-16,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-065548,City Hotel,1,373,2025,April,14,5,2025-04-05,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-112877,City Hotel,0,97,2025,May,22,26,2025-05-26,2,2,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,142.5,0,1
HB-042133,City Hotel,0,9,2023,August,35,31,2023-08-31,1,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,109.0,0,2
HB-067603,City Hotel,1,161,2025,May,19,5,2025-05-05,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,30.0,,0,Transient,120.0,0,0
HB-091211,City Hotel,0,12,2024,June,24,14,2024-06-14,0,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,146.0,0,2
HB-077075,City Hotel,0,219,2023,September,36,4,2023-09-04,0,1,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,108.0,0,0
HB-108364,City Hotel,0,116,2025,March,13,24,2025-03-24,0,2,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,1,No Deposit,171.0,,0,Transient-Party,100.0,0,1
HB-112407,City Hotel,0,0,2025,May,21,23,2025-05-23,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,0
HB-106297,City Hotel,0,48,2025,February,8,22,2025-02-22,0,2,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,65.0,0,1
HB-118176,City Hotel,0,165,2025,August,33,12,2025-08-12,2,2,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,B,A,0,No Deposit,14.0,,0,Transient-Party,146.25,0,0
HB-104728,City Hotel,0,29,2025,January,3,18,2025-01-18,0,3,1,0.0,0,BB,BEL,Groups,TA/TO,0,0,0,A,A,0,No Deposit,171.0,,0,Transient-Party,65.0,0,0
HB-055414,City Hotel,1,199,2024,August,33,12,2024-08-12,2,4,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,128.92,0,0
HB-043726,City Hotel,0,34,2023,September,38,23,2023-09-23,0,3,2,0.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,52.0,,33,Transient-Party,224.67,0,0
HB-110788,City Hotel,0,25,2025,April,18,30,2025-04-30,2,0,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,142.0,0,1
HB-014825,Resort Hotel,1,179,2023,August,32,11,2023-08-11,3,10,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,240.0,,0,Transient,134.0,0,0
HB-023549,Resort Hotel,0,15,2024,April,17,24,2024-04-24,2,2,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,,0,Transient,78.75,0,0
HB-080592,City Hotel,0,55,2023,November,46,15,2023-11-15,2,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Transient,60.0,0,0
HB-046894,City Hotel,1,17,2024,January,4,24,2024-01-24,4,6,1,0.0,0,BB,AGO,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,81.0,0,0
HB-059609,City Hotel,1,75,2024,October,44,30,2024-10-30,2,0,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,105.0,0,0
HB-096308,City Hotel,0,94,2025,June,23,2,2025-06-02,0,1,2,0.0,0,BB,PRT,Complementary,Direct,1,0,1,F,F,1,No Deposit,,45.0,0,Transient,0.0,1,4
HB-064355,City Hotel,1,109,2025,March,10,7,2025-03-07,0,2,1,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,54.05,0,0
HB-078216,City Hotel,0,6,2023,October,40,2,2023-10-02,2,3,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Group,176.4,0,0
HB-093242,City Hotel,0,109,2024,July,28,11,2024-07-11,3,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,113.26,0,1
HB-099102,City Hotel,0,174,2024,October,40,5,2024-10-05,0,4,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.1,0,2
HB-117523,City Hotel,0,170,2025,July,31,29,2025-07-29,2,5,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,89.0,,0,Transient,140.4,0,1
HB-022053,Resort Hotel,0,4,2025,May,20,15,2025-05-15,1,0,1,0.0,0,HB,PRT,Online TA,TA/TO,1,0,3,A,A,0,No Deposit,468.0,,0,Transient,48.38,0,0
HB-088349,City Hotel,0,81,2024,May,18,1,2024-05-01,2,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.85,0,2
HB-073350,City Hotel,1,162,2025,August,34,19,2025-08-19,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,140.0,0,0
HB-102058,City Hotel,0,35,2024,November,47,22,2024-11-22,0,1,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,1
HB-020667,Resort Hotel,0,2,2024,February,6,5,2024-02-05,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,2
HB-020527,Resort Hotel,0,0,2024,January,5,31,2024-01-31,1,0,3,0.0,0,BB,CHN,Offline TA/TO,TA/TO,0,0,0,A,C,0,No Deposit,5.0,,0,Transient,40.5,0,0
HB-014787,Resort Hotel,1,275,2023,October,40,4,2023-10-04,2,0,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,26,0,A,A,0,Non Refund,208.0,,0,Transient,50.0,0,0
HB-057711,City Hotel,1,315,2024,September,40,30,2024-09-30,1,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,69,Transient,160.0,0,0
HB-092691,City Hotel,0,115,2024,July,27,6,2024-07-06,1,4,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,97.75,0,0
HB-086059,City Hotel,0,48,2024,March,12,24,2024-03-24,0,3,3,0.0,0,BB,ESP,Direct,Direct,0,0,0,E,E,1,No Deposit,14.0,,0,Transient,190.2,1,1
HB-020984,Resort Hotel,0,0,2024,February,7,13,2024-02-13,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,75.0,0,1
HB-116649,City Hotel,0,29,2025,July,29,20,2025-07-20,0,3,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,1
HB-033392,Resort Hotel,0,16,2025,February,8,19,2025-02-19,2,1,3,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,54.75,0,0
HB-000205,Resort Hotel,0,0,2023,July,27,7,2023-07-07,0,4,2,0.0,0,BB,NLD,Direct,Direct,0,0,0,A,A,2,No Deposit,,,0,Transient,98.0,0,0
HB-028632,Resort Hotel,0,60,2024,October,40,3,2024-10-03,1,4,1,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient-Party,70.0,0,1
HB-069668,City Hotel,1,348,2025,June,23,3,2025-06-03,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient,90.0,0,0
HB-096506,City Hotel,0,46,2024,August,35,29,2024-08-29,1,4,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,100.62,0,0
HB-091536,City Hotel,0,55,2024,June,25,21,2024-06-21,0,2,2,0.0,0,BB,PRY,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,113.4,0,2
HB-020827,Resort Hotel,0,5,2024,February,6,10,2024-02-10,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,250.0,,0,Transient,51.0,1,0
HB-043453,City Hotel,0,74,2023,September,38,18,2023-09-18,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-118224,City Hotel,0,111,2025,August,33,14,2025-08-14,1,2,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,225.0,0,2
HB-108948,City Hotel,0,154,2025,March,14,31,2025-03-31,2,2,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,178.73,0,1
HB-105555,City Hotel,0,60,2025,February,7,10,2025-02-10,0,2,2,0.0,0,BB,MCO,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,73.46,0,1
HB-100218,City Hotel,0,386,2024,October,43,23,2024-10-23,2,0,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-074323,City Hotel,1,262,2023,July,27,6,2023-07-06,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Contract,62.0,0,0
HB-016811,Resort Hotel,0,53,2023,September,36,8,2023-09-08,1,5,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,E,E,1,No Deposit,250.0,,0,Transient,123.0,0,1
HB-117497,City Hotel,0,87,2025,August,31,3,2025-08-03,0,2,3,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,195.0,0,1
HB-107289,City Hotel,0,23,2025,March,10,7,2025-03-07,0,4,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,102.43,0,0
HB-049295,City Hotel,0,101,2024,April,15,9,2024-04-09,2,4,2,0.0,1,BB,POL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,85.28,0,2
HB-008020,Resort Hotel,1,238,2024,September,36,7,2024-09-07,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,D,D,0,Non Refund,1.0,,0,Transient,89.0,0,0
HB-023408,Resort Hotel,0,58,2024,April,17,23,2024-04-23,1,1,2,3.0,0,BB,PRT,Direct,Direct,0,0,0,H,H,0,No Deposit,250.0,,0,Transient,125.0,0,0
HB-066672,City Hotel,1,152,2025,April,17,22,2025-04-22,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,0,Transient,105.0,0,0
HB-034377,Resort Hotel,0,96,2025,March,11,12,2025-03-12,4,7,1,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,E,E,5,No Deposit,,,0,Transient-Party,65.09,0,0
HB-106002,City Hotel,0,114,2025,February,7,15,2025-02-15,0,4,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,242.0,0,Transient-Party,78.0,0,0
HB-019214,Resort Hotel,1,92,2024,February,9,26,2024-02-26,1,2,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,134.0,,0,Transient,79.0,0,0
HB-118025,City Hotel,0,1,2025,August,33,12,2025-08-12,0,1,3,0.0,0,BB,FRA,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,240.0,0,2
HB-110777,City Hotel,0,110,2025,April,17,27,2025-04-27,2,3,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,100.8,0,1
HB-021754,Resort Hotel,0,6,2024,March,10,6,2024-03-06,2,1,1,0.0,0,BB,UGA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,43.0,0,1
HB-038955,Resort Hotel,0,178,2025,July,30,24,2025-07-24,3,8,3,0.0,0,HB,AZE,Direct,Direct,0,0,0,A,A,1,No Deposit,250.0,,0,Transient,213.6,0,2
HB-052848,City Hotel,1,10,2024,June,24,12,2024-06-12,4,6,3,0.0,0,BB,SAU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,169.0,0,0
HB-094265,City Hotel,0,0,2024,August,31,1,2024-08-01,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,102.0,0,1
HB-049202,City Hotel,1,69,2024,April,14,7,2024-04-07,0,3,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,137.7,0,0
HB-004409,Resort Hotel,1,153,2024,March,11,13,2024-03-13,2,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,40.5,0,1
HB-021255,Resort Hotel,0,0,2024,February,8,23,2024-02-23,0,1,1,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,40.0,0,0
HB-056826,City Hotel,1,6,2024,September,37,15,2024-09-15,0,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,159.0,0,1
HB-053275,City Hotel,1,350,2024,June,25,17,2024-06-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,140.0,0,0
HB-115199,City Hotel,0,170,2025,June,27,30,2025-06-30,1,2,2,2.0,0,HB,POL,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,9.0,,0,Transient,182.4,0,1
HB-077822,City Hotel,0,16,2023,September,39,25,2023-09-25,2,2,1,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,170.0,0,0
HB-014768,Resort Hotel,1,259,2023,September,37,17,2023-09-17,0,3,1,0.0,0,BB,GBR,Groups,Corporate,0,1,0,A,A,0,Non Refund,,223.0,0,Transient,33.3,0,0
HB-018816,Resort Hotel,0,12,2023,November,48,28,2023-11-28,1,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,61.2,0,1
HB-048733,City Hotel,1,1,2024,March,13,29,2024-03-29,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.0,0,0
HB-089931,City Hotel,0,0,2024,May,22,29,2024-05-29,1,0,2,0.0,0,SC,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,0
HB-063382,City Hotel,1,32,2025,February,7,10,2025-02-10,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,83.3,0,1
HB-075901,City Hotel,1,274,2023,July,29,18,2023-07-18,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-051186,City Hotel,0,131,2024,May,20,15,2024-05-15,2,1,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,135.9,0,2
HB-078609,City Hotel,0,0,2023,October,41,11,2023-10-11,2,0,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,123.0,0,0
HB-024117,Resort Hotel,0,11,2024,May,20,15,2024-05-15,1,0,2,0.0,0,BB,GBR,Direct,Direct,0,0,1,A,C,0,Refundable,,405.0,0,Transient-Party,70.0,0,1
HB-019793,Resort Hotel,0,42,2023,December,52,30,2023-12-30,0,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,150.0,0,0
HB-063759,City Hotel,1,32,2025,February,8,20,2025-02-20,1,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,75.0,0,0
HB-016275,Resort Hotel,0,173,2023,August,33,17,2023-08-17,1,4,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,1,No Deposit,250.0,,0,Transient,130.9,0,1
HB-050659,City Hotel,1,124,2024,May,18,5,2024-05-05,0,3,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.5,0,1
HB-026842,Resort Hotel,0,66,2024,August,32,5,2024-08-05,2,5,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,221.0,1,1
HB-053223,City Hotel,1,350,2024,June,25,17,2024-06-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,140.0,0,0
HB-091964,City Hotel,0,36,2024,June,26,26,2024-06-26,2,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.35,0,0
HB-004717,Resort Hotel,1,36,2024,March,13,29,2024-03-29,2,7,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,105.22,0,1
HB-074530,City Hotel,1,332,2023,September,37,14,2023-09-14,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-078106,City Hotel,0,0,2023,October,40,2,2023-10-02,0,2,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,E,2,No Deposit,,,0,Transient-Party,145.0,0,0
HB-050907,City Hotel,0,286,2024,May,19,11,2024-05-11,0,4,2,0.0,0,BB,AUT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,30.0,,176,Transient-Party,99.0,0,1
HB-058937,City Hotel,1,1,2024,October,42,18,2024-10-18,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,22.0,,0,Transient,107.0,0,0
HB-067631,City Hotel,1,93,2025,May,19,5,2025-05-05,1,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,135.0,0,0
HB-074959,City Hotel,1,164,2023,August,33,14,2023-08-14,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-116621,City Hotel,0,11,2025,July,30,21,2025-07-21,0,2,2,1.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,159.0,0,1
HB-008587,Resort Hotel,1,383,2024,October,40,6,2024-10-06,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,315.0,,0,Transient-Party,48.0,0,0
HB-023055,Resort Hotel,0,178,2024,April,14,7,2024-04-07,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,48.76,0,0
HB-073244,City Hotel,1,30,2025,August,33,17,2025-08-17,0,3,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,2
HB-005442,Resort Hotel,1,108,2024,April,18,29,2024-04-29,2,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,84.0,0,0
HB-036411,Resort Hotel,0,30,2025,May,20,17,2025-05-17,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,90.0,0,2
HB-096135,City Hotel,0,287,2024,August,34,24,2024-08-24,1,4,2,1.0,0,BB,DEU,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,90.1,0,1
HB-103466,City Hotel,0,15,2024,December,51,20,2024-12-20,1,5,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,67.32,0,1
HB-095305,City Hotel,0,7,2024,August,33,16,2024-08-16,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient-Party,150.0,0,1
HB-110876,City Hotel,0,104,2025,April,18,30,2025-04-30,2,1,1,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,105.0,0,0
HB-000754,Resort Hotel,0,40,2023,July,30,27,2023-07-27,1,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,120.6,0,0
HB-003958,Resort Hotel,1,103,2024,February,6,9,2024-02-09,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,332.0,,0,Transient-Party,50.0,0,0
HB-023961,Resort Hotel,0,17,2024,May,18,5,2024-05-05,0,3,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,141.0,1,0
HB-108108,City Hotel,0,1,2025,March,12,22,2025-03-22,0,1,1,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,9.0,,0,Transient,89.0,0,1
HB-065143,City Hotel,1,145,2025,March,13,25,2025-03-25,2,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.6,0,1
HB-043024,City Hotel,1,68,2023,September,37,12,2023-09-12,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-066521,City Hotel,1,82,2025,April,17,21,2025-04-21,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-002970,Resort Hotel,0,37,2023,November,45,8,2023-11-08,2,5,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,2,No Deposit,185.0,281.0,0,Transient-Party,36.0,0,0
HB-078034,City Hotel,1,3,2023,October,40,4,2023-10-04,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,1,1,0,A,A,0,No Deposit,9.0,,0,Contract,126.0,0,0
HB-004085,Resort Hotel,1,112,2024,February,7,12,2024-02-12,0,2,2,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,68.0,0,0
HB-098841,City Hotel,0,1,2024,October,40,3,2024-10-03,1,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,E,G,2,No Deposit,341.0,,0,Transient,77.0,0,2
HB-117749,City Hotel,0,271,2025,August,31,2,2025-08-02,2,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,1
HB-034369,Resort Hotel,0,181,2025,March,12,19,2025-03-19,2,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,36.0,1,0
HB-009373,Resort Hotel,1,20,2024,November,47,19,2024-11-19,2,5,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,0
HB-093529,City Hotel,0,292,2024,July,29,21,2024-07-21,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,0
HB-105455,City Hotel,0,0,2025,February,6,9,2025-02-09,0,0,2,0.0,0,BB,PRT,Online TA,TA/TO,1,0,0,A,K,0,No Deposit,9.0,,0,Transient,0.0,0,3
HB-100768,City Hotel,0,184,2024,October,43,27,2024-10-27,2,3,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,2
HB-091684,City Hotel,0,14,2024,June,25,22,2024-06-22,0,2,2,0.0,0,SC,HUN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.0,0,1
HB-089830,City Hotel,0,109,2024,May,21,23,2024-05-23,1,3,2,0.0,0,BB,CHE,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-027943,Resort Hotel,0,229,2024,September,37,11,2024-09-11,2,2,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,B,0,No Deposit,96.0,,0,Transient,63.2,0,0
HB-052801,City Hotel,1,69,2024,June,24,12,2024-06-12,2,4,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,120.0,0,0
HB-052151,City Hotel,1,113,2024,May,22,31,2024-05-31,0,3,1,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,A,0,Non Refund,,202.0,0,Transient,100.0,0,0
HB-037499,Resort Hotel,0,157,2025,June,24,10,2025-06-10,4,6,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,98.4,0,0
HB-086213,City Hotel,0,2,2024,March,13,27,2024-03-27,2,1,3,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,83.0,,0,Transient,100.47,1,1
HB-112580,City Hotel,0,208,2025,May,21,24,2025-05-24,0,2,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,114.4,0,0
HB-040336,City Hotel,1,72,2023,July,29,22,2023-07-22,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,76.5,0,0
HB-116149,City Hotel,0,414,2025,July,28,13,2025-07-13,0,2,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,122.4,0,1
HB-052341,City Hotel,1,96,2024,June,23,4,2024-06-04,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.9,0,0
HB-065612,City Hotel,1,62,2025,April,14,6,2025-04-06,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,135.0,0,0
HB-075448,City Hotel,1,327,2023,September,36,9,2023-09-09,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,60.0,0,0
HB-094901,City Hotel,0,175,2024,August,32,10,2024-08-10,0,2,2,1.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,121.5,0,1
HB-052539,City Hotel,1,56,2024,June,23,8,2024-06-08,0,1,2,0.0,0,BB,PRT,Offline TA/TO,Corporate,0,0,0,A,A,0,No Deposit,191.0,,0,Transient-Party,120.0,0,0
HB-081554,City Hotel,1,223,2024,June,24,14,2024-06-14,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,133.0,,40,Transient,135.0,0,0
HB-116527,City Hotel,0,268,2025,July,29,16,2025-07-16,2,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,80.92,0,0
HB-008670,Resort Hotel,1,10,2024,October,41,9,2024-10-09,2,0,2,0.0,0,BB,PRT,Groups,Corporate,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,55.0,0,0
HB-048458,City Hotel,0,81,2024,March,12,23,2024-03-23,2,5,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.31,0,0
HB-090972,City Hotel,0,75,2024,June,23,8,2024-06-08,2,4,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,173.0,,0,Transient,80.75,0,0
HB-084008,City Hotel,0,0,2024,February,7,15,2024-02-15,1,1,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,136.0,0,0
HB-063630,City Hotel,1,587,2025,February,7,16,2025-02-16,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-077736,City Hotel,0,8,2023,September,38,19,2023-09-19,2,4,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,145.67,0,0
HB-044678,City Hotel,0,66,2023,October,41,9,2023-10-09,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient,75.0,0,0
HB-003479,Resort Hotel,1,93,2023,December,51,19,2023-12-19,0,1,2,0.0,0,FB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,80.0,0,0
HB-051598,City Hotel,1,127,2024,May,21,22,2024-05-22,2,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.3,0,0
HB-092714,City Hotel,0,156,2024,July,27,3,2024-07-03,3,5,2,0.0,0,HB,ESP,Direct,Direct,0,0,0,B,B,0,No Deposit,,,0,Transient-Party,110.44,0,1
HB-104451,City Hotel,0,65,2025,January,2,12,2025-01-12,0,2,1,0.0,0,BB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,366.0,0,Transient-Party,65.0,0,0
HB-099396,City Hotel,0,180,2024,October,41,10,2024-10-10,1,2,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,234.0,,0,Transient-Party,120.0,0,1
HB-002385,Resort Hotel,0,78,2023,October,41,10,2023-10-10,6,15,2,0.0,0,HB,BEL,Direct,Direct,0,0,0,D,D,1,No Deposit,,,0,Transient,106.0,0,1
HB-099845,City Hotel,0,359,2024,October,42,14,2024-10-14,2,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,21.0,,0,Transient-Party,39.0,0,1
HB-041176,City Hotel,1,39,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,101.5,0,0
HB-085453,City Hotel,0,41,2024,March,11,13,2024-03-13,2,1,2,0.0,0,BB,POL,Corporate,TA/TO,0,0,0,A,A,0,No Deposit,,193.0,0,Transient-Party,85.67,0,0
HB-112760,City Hotel,0,162,2025,May,21,23,2025-05-23,0,5,1,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-093145,City Hotel,0,88,2024,July,28,13,2024-07-13,1,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,9.0,,0,Transient,120.8,0,2
HB-008938,Resort Hotel,1,24,2024,October,43,21,2024-10-21,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,D,D,1,No Deposit,,,0,Transient-Party,60.0,0,1
HB-091231,City Hotel,0,150,2024,June,24,16,2024-06-16,0,3,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,90.0,0,1
HB-067745,City Hotel,1,18,2025,May,19,6,2025-05-06,2,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,150.0,0,1
HB-061156,City Hotel,1,32,2024,December,49,2,2024-12-02,2,2,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,147.9,0,0
HB-107552,City Hotel,0,0,2025,March,11,14,2025-03-14,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,D,D,0,No Deposit,444.0,444.0,0,Transient,95.0,0,0
HB-069115,City Hotel,1,170,2025,May,21,25,2025-05-25,0,3,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.5,0,0
HB-020943,Resort Hotel,0,31,2024,February,7,13,2024-02-13,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,F,0,No Deposit,240.0,,0,Transient,61.2,0,2
HB-058577,City Hotel,1,37,2024,October,41,13,2024-10-13,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,105.0,0,0
HB-108605,City Hotel,0,5,2025,March,13,29,2025-03-29,0,1,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.0,0,1
HB-049043,City Hotel,1,104,2024,April,14,5,2024-04-05,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,96.0,0,0
HB-017171,Resort Hotel,0,68,2023,September,38,24,2023-09-24,2,3,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,241.0,,0,Transient,69.91,1,1
HB-095626,City Hotel,0,163,2024,August,33,15,2024-08-15,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,72.25,0,1
HB-051947,City Hotel,0,316,2024,May,21,26,2024-05-26,0,3,2,0.0,0,BB,AUT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,110.0,0,0
HB-062569,City Hotel,1,23,2025,January,3,15,2025-01-15,2,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,92.63,0,1
HB-052128,City Hotel,1,6,2024,May,22,31,2024-05-31,0,3,1,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.0,0,0
HB-047555,City Hotel,1,43,2024,February,9,26,2024-02-26,2,4,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,73.8,0,0
HB-036119,Resort Hotel,0,72,2025,May,18,4,2025-05-04,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,52.85,0,0
HB-098164,City Hotel,0,18,2024,September,38,22,2024-09-22,1,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,150.5,0,1
HB-026960,Resort Hotel,0,42,2024,August,32,11,2024-08-11,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,C,B,0,No Deposit,196.0,,0,Transient-Party,235.0,0,0
HB-013240,Resort Hotel,1,208,2025,August,32,5,2025-08-05,4,7,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,206.0,0,2
HB-016434,Resort Hotel,0,47,2023,August,34,22,2023-08-22,2,5,2,1.0,0,FB,PRT,Direct,Direct,0,0,0,A,C,0,No Deposit,,,0,Transient,235.07,0,1
HB-062736,City Hotel,1,164,2025,January,4,20,2025-01-20,1,2,1,0.0,0,BB,CHL,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,85.2,0,1
HB-031858,Resort Hotel,0,0,2025,January,2,8,2025-01-08,1,0,2,0.0,0,BB,PRT,Direct,Direct,1,0,0,E,E,0,No Deposit,,,0,Transient,64.0,0,0
HB-047640,City Hotel,1,116,2024,February,9,28,2024-02-28,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,F,0,No Deposit,134.0,,0,Transient-Party,61.0,0,0
HB-071445,City Hotel,1,315,2025,July,27,5,2025-07-05,2,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,103.5,0,1
HB-066643,City Hotel,1,100,2025,April,17,22,2025-04-22,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,0,Transient,105.0,0,0
HB-031166,Resort Hotel,0,5,2024,December,50,10,2024-12-10,2,5,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,I,0,No Deposit,240.0,,0,Transient,58.43,1,1
HB-005758,Resort Hotel,1,236,2024,May,19,12,2024-05-12,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,315.0,,0,Transient-Party,48.0,0,0
HB-000218,Resort Hotel,0,0,2023,July,27,8,2023-07-08,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,146.0,,0,Transient,61.0,0,0
HB-107501,City Hotel,0,10,2025,March,11,12,2025-03-12,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,40.0,0,0
HB-022838,Resort Hotel,0,1,2024,April,14,7,2024-04-07,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,65.0,0,1
HB-099229,City Hotel,0,3,2024,October,41,10,2024-10-10,1,0,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,118.58,0,1
HB-099963,City Hotel,0,119,2024,October,42,16,2024-10-16,2,3,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,151.2,0,2
HB-057615,City Hotel,1,447,2024,September,39,29,2024-09-29,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-001297,Resort Hotel,0,6,2023,August,34,23,2023-08-23,2,2,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,,0,Transient,201.0,0,0
HB-059910,City Hotel,1,304,2024,November,44,3,2024-11-03,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,89.0,0,0
HB-040553,City Hotel,1,92,2023,July,31,31,2023-07-31,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,1
HB-039983,Resort Hotel,0,13,2025,August,35,28,2025-08-28,1,5,2,1.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,250.2,1,3
HB-035554,Resort Hotel,0,109,2025,April,17,25,2025-04-25,0,2,1,0.0,0,HB,AUT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,502.0,,0,Transient-Party,75.0,0,0
HB-118380,City Hotel,0,27,2025,August,33,15,2025-08-15,0,4,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,169.0,1,1
HB-074590,City Hotel,1,353,2023,October,40,5,2023-10-05,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-107503,City Hotel,0,99,2025,March,11,11,2025-03-11,1,1,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,9.0,,0,Transient,142.2,0,2
HB-019887,Resort Hotel,0,37,2024,January,1,3,2024-01-03,2,3,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,26.0,0,0
HB-082353,City Hotel,1,94,2024,March,10,4,2024-03-04,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,154.0,,28,Transient,80.0,0,0
HB-112224,City Hotel,0,103,2025,May,21,19,2025-05-19,1,2,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,144.0,0,1
HB-083023,City Hotel,0,1,2024,January,2,13,2024-01-13,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,80.0,0,0
HB-073037,City Hotel,1,85,2025,August,33,12,2025-08-12,2,3,3,0.0,0,BB,MAR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,200.0,0,0
HB-100091,City Hotel,0,192,2024,October,43,21,2024-10-21,0,2,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,29.0,,0,Transient-Party,95.0,0,0
HB-062251,City Hotel,1,32,2025,January,2,6,2025-01-06,0,2,2,0.0,0,SC,RUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,1
HB-006353,Resort Hotel,0,252,2024,June,23,4,2024-06-04,4,6,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,143.0,,0,Transient,64.9,0,3
HB-003049,Resort Hotel,0,33,2023,November,45,12,2023-11-12,0,3,1,0.0,0,BB,FRA,Corporate,Corporate,0,0,0,A,A,3,No Deposit,334.0,281.0,0,Transient-Party,40.0,0,0
HB-049183,City Hotel,1,274,2024,April,14,7,2024-04-07,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-077319,City Hotel,0,1,2023,September,37,15,2023-09-15,0,2,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,164.5,0,1
HB-114209,City Hotel,0,5,2025,June,25,17,2025-06-17,0,1,2,2.0,0,BB,PRT,Direct,Direct,0,0,0,G,G,0,No Deposit,,,0,Transient-Party,295.0,0,0
HB-005323,Resort Hotel,1,138,2024,April,17,25,2024-04-25,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,E,E,0,Non Refund,,,0,Transient,65.0,0,0
HB-108486,City Hotel,0,206,2025,March,13,26,2025-03-26,2,1,2,0.0,0,BB,CN,Groups,TA/TO,0,0,0,A,A,1,No Deposit,296.0,,0,Transient-Party,72.0,0,0
HB-115564,City Hotel,0,184,2025,July,28,7,2025-07-07,0,1,2,3.0,0,BB,ARM,Direct,Direct,0,0,0,G,G,0,No Deposit,14.0,,0,Transient,251.7,0,0
HB-015974,Resort Hotel,0,129,2023,August,31,1,2023-08-01,3,6,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,125.9,1,1
HB-115078,City Hotel,0,121,2025,June,26,27,2025-06-27,0,4,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,162.0,0,1
HB-093325,City Hotel,0,100,2024,July,29,18,2024-07-18,1,1,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,137.7,0,2
HB-095485,City Hotel,0,320,2024,August,33,18,2024-08-18,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-064072,City Hotel,1,41,2025,February,9,28,2025-02-28,1,5,2,0.0,0,BB,DZA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,100.3,0,0
HB-031301,Resort Hotel,0,0,2024,December,50,15,2024-12-15,2,5,1,0.0,0,Undefined,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,464.0,,0,Transient,47.0,0,0
HB-014730,Resort Hotel,1,259,2023,September,37,17,2023-09-17,0,3,2,0.0,0,BB,GBR,Groups,Corporate,0,1,0,A,A,0,Non Refund,,223.0,0,Transient,40.05,0,0
HB-085023,City Hotel,0,105,2024,March,10,5,2024-03-05,2,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,89.3,0,0
HB-059356,City Hotel,1,475,2024,October,43,27,2024-10-27,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-109906,City Hotel,0,30,2025,April,16,17,2025-04-17,1,1,2,2.0,0,BB,NZL,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,224.0,0,0
HB-019307,Resort Hotel,0,3,2023,December,50,12,2023-12-12,0,1,3,1.0,0,HB,PRT,Online TA,TA/TO,0,0,0,H,H,1,No Deposit,240.0,,0,Transient,154.0,0,0
HB-040822,City Hotel,0,0,2023,August,32,8,2023-08-08,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.0,0,1
HB-006171,Resort Hotel,1,7,2024,May,22,27,2024-05-27,0,1,1,0.0,0,HB,PRT,Groups,Corporate,0,0,0,A,A,0,Non Refund,,20.0,0,Transient,58.0,0,0
HB-016052,Resort Hotel,0,164,2023,July,30,30,2023-07-30,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,143.0,,0,Contract,112.63,0,1
HB-076245,City Hotel,1,200,2023,September,37,12,2023-09-12,2,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,86.0,0,0
HB-118911,City Hotel,0,457,2025,August,35,25,2025-08-25,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,122.4,0,1
HB-068056,City Hotel,1,84,2025,May,20,12,2025-05-12,0,2,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,189.0,0,0
HB-028094,Resort Hotel,0,168,2024,September,38,20,2024-09-20,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient-Party,10.0,0,2
HB-063038,City Hotel,1,149,2025,January,5,27,2025-01-27,0,1,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-052658,City Hotel,1,337,2024,June,23,9,2024-06-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-102431,City Hotel,0,92,2024,November,47,23,2024-11-23,1,4,3,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,92.65,0,0
HB-094461,City Hotel,0,159,2024,August,31,1,2024-08-01,1,3,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,99.45,0,1
HB-019851,Resort Hotel,0,3,2024,January,1,3,2024-01-03,2,1,2,0.0,0,BB,ZAF,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,240.0,,0,Transient,48.0,0,1
HB-116313,City Hotel,0,159,2025,July,29,16,2025-07-16,2,0,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,116.1,1,0
HB-017791,Resort Hotel,0,8,2025,January,5,31,2025-01-31,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,9,A,D,0,No Deposit,,380.0,0,Transient,35.0,0,0
HB-100259,City Hotel,0,386,2024,October,43,23,2024-10-23,2,0,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-069441,City Hotel,1,55,2025,May,22,31,2025-05-31,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,135.0,0,0
HB-001025,Resort Hotel,1,101,2023,August,32,10,2023-08-10,2,5,2,0.0,1,HB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,196.0,0,2
HB-072588,City Hotel,1,160,2025,July,31,31,2025-07-31,3,6,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,112.5,0,0
HB-098296,City Hotel,0,144,2024,September,39,23,2024-09-23,2,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,129.6,0,2
HB-003909,Resort Hotel,1,72,2024,February,6,6,2024-02-06,2,1,2,0.0,0,HB,PRT,Groups,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,73.33,0,0
HB-087056,City Hotel,0,82,2024,April,15,11,2024-04-11,1,2,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,80.75,0,0
HB-095456,City Hotel,0,35,2024,August,33,16,2024-08-16,0,4,3,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,168.3,0,2
HB-039627,Resort Hotel,0,94,2025,August,33,14,2025-08-14,3,7,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,135.0,0,0
HB-118611,City Hotel,0,176,2025,August,34,21,2025-08-21,1,1,2,0.0,0,HB,DEU,Direct,Direct,0,0,0,A,D,1,No Deposit,14.0,,0,Transient,135.0,0,1
HB-043861,City Hotel,0,192,2023,September,39,25,2023-09-25,2,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,102.0,0,0
HB-042760,City Hotel,1,15,2023,September,36,9,2023-09-09,0,4,2,0.0,0,SC,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,58.35,0,1
HB-031357,Resort Hotel,0,54,2024,December,52,25,2024-12-25,1,0,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,60.0,0,0
HB-042035,City Hotel,1,104,2023,August,35,30,2023-08-30,2,1,2,0.0,0,HB,ESP,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,90.0,0,0
HB-095898,City Hotel,0,4,2025,January,2,10,2025-01-10,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,10,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,1
HB-072340,City Hotel,1,243,2025,July,30,26,2025-07-26,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-011179,Resort Hotel,1,36,2025,April,17,27,2025-04-27,0,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,85.0,0,2
HB-102805,City Hotel,0,6,2024,November,48,30,2024-11-30,2,4,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,106.89,1,3
HB-088557,City Hotel,0,185,2024,May,19,6,2024-05-06,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,81.77,0,2
HB-112121,City Hotel,0,84,2025,May,20,14,2025-05-14,2,4,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.5,0,0
HB-012036,Resort Hotel,1,234,2025,June,24,9,2025-06-09,2,5,3,0.0,0,HB,IRL,Direct,Direct,0,0,0,E,E,1,No Deposit,250.0,,0,Transient,171.39,0,1
HB-075029,City Hotel,1,219,2023,September,36,4,2023-09-04,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,3.0,,0,Transient-Party,80.0,0,0
HB-028027,Resort Hotel,0,148,2024,September,38,18,2024-09-18,2,1,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,125.67,0,1
HB-033030,Resort Hotel,0,23,2025,February,7,11,2025-02-11,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,103.0,0,3
HB-061187,City Hotel,1,9,2024,December,49,3,2024-12-03,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.89,0,0
HB-051053,City Hotel,1,273,2024,May,20,13,2024-05-13,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,95.0,0,0
HB-010001,Resort Hotel,1,1,2025,February,6,4,2025-02-04,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,43.0,0,0
HB-020293,Resort Hotel,0,16,2024,January,3,20,2024-01-20,0,4,2,1.0,0,BB,FRA,Direct,Direct,0,0,0,G,G,0,No Deposit,,,0,Transient,71.0,0,0
HB-101282,City Hotel,0,27,2024,November,45,7,2024-11-07,1,2,1,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient-Party,195.0,0,0
HB-044853,City Hotel,0,36,2023,October,41,13,2023-10-13,0,3,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,26.0,,0,Transient-Party,112.0,0,0
HB-027403,Resort Hotel,0,23,2024,August,35,28,2024-08-28,2,1,2,2.0,0,BB,PRT,Direct,Direct,0,0,0,G,G,1,No Deposit,250.0,,0,Transient,283.0,1,0
HB-111616,City Hotel,0,104,2025,May,19,9,2025-05-09,0,4,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,85.0,0,2
HB-068480,City Hotel,1,236,2025,May,20,18,2025-05-18,1,3,3,0.0,0,HB,DNK,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,220.4,0,2
HB-088777,City Hotel,0,22,2025,January,4,25,2025-01-25,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,14,A,D,0,No Deposit,,219.0,0,Transient,89.0,1,2
HB-115829,City Hotel,0,64,2025,July,28,9,2025-07-09,2,1,2,0.0,0,BB,DNK,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,42.0,,0,Transient,103.5,0,1
HB-043707,City Hotel,0,83,2023,September,38,23,2023-09-23,0,2,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-019509,Resort Hotel,0,3,2023,December,51,24,2023-12-24,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,90.0,0,0
HB-000320,Resort Hotel,0,31,2023,July,28,12,2023-07-12,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Transient,123.0,0,0
HB-105109,City Hotel,0,193,2025,January,4,26,2025-01-26,1,3,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,15.0,,0,Transient,68.0,0,0
HB-118717,City Hotel,0,117,2025,August,34,22,2025-08-22,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,98.0,,0,Transient-Party,115.0,0,1
HB-029844,Resort Hotel,0,32,2024,November,45,4,2024-11-04,1,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,40.0,,0,Transient,58.65,0,0
HB-033836,Resort Hotel,0,1,2025,March,10,4,2025-03-04,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,2,No Deposit,240.0,,0,Transient-Party,67.0,1,1
HB-096449,City Hotel,0,28,2024,September,35,1,2024-09-01,0,2,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,0
HB-093528,City Hotel,0,191,2024,July,29,16,2024-07-16,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.95,1,1
HB-068352,City Hotel,1,104,2025,May,20,15,2025-05-15,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-033247,Resort Hotel,0,38,2025,February,7,12,2025-02-12,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient,48.0,0,2
HB-040894,City Hotel,0,16,2023,August,32,8,2023-08-08,2,2,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-052000,City Hotel,1,135,2024,May,22,28,2024-05-28,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,96.0,0,0
HB-061055,City Hotel,1,510,2024,December,48,1,2024-12-01,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-002658,Resort Hotel,1,148,2023,October,43,24,2023-10-24,0,1,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,47.0,0,0
HB-020704,Resort Hotel,0,0,2024,February,5,3,2024-02-03,1,4,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient,39.0,0,2
HB-041273,City Hotel,1,39,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,101.5,0,0
HB-070682,City Hotel,1,19,2025,June,25,20,2025-06-20,3,10,1,0.0,0,BB,IRN,Direct,Direct,0,0,0,G,G,0,No Deposit,14.0,,0,Transient,277.15,0,0
HB-098375,City Hotel,0,17,2024,September,39,25,2024-09-25,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,158.0,0,2
HB-103638,City Hotel,0,77,2024,December,52,24,2024-12-24,2,3,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,74.61,0,1
HB-000575,Resort Hotel,1,41,2023,July,29,20,2023-07-20,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,135.0,0,1
HB-054610,City Hotel,1,379,2024,July,29,21,2024-07-21,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-114763,City Hotel,0,263,2025,June,26,23,2025-06-23,2,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,37.0,,0,Transient-Party,6.9,0,2
HB-025372,Resort Hotel,0,194,2024,June,24,12,2024-06-12,4,8,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,101.0,0,1
HB-080816,City Hotel,0,55,2023,November,47,22,2023-11-22,2,1,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Group,60.0,0,0
HB-036092,Resort Hotel,0,0,2025,May,19,8,2025-05-08,1,0,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,E,I,0,No Deposit,240.0,,0,Transient,122.0,1,1
HB-102951,City Hotel,0,27,2024,December,49,6,2024-12-06,0,4,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,1
HB-001974,Resort Hotel,0,16,2023,September,39,25,2023-09-25,0,1,1,0.0,0,SC,PRT,Direct,Direct,0,0,0,A,A,4,No Deposit,,312.0,0,Transient-Party,80.0,0,1
HB-028975,Resort Hotel,0,189,2024,October,42,17,2024-10-17,1,0,2,0.0,0,BB,NLD,Online TA,Corporate,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,60.0,0,2
HB-032519,Resort Hotel,0,125,2025,January,4,22,2025-01-22,2,5,2,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,E,E,1,No Deposit,273.0,,4,Transient-Party,72.0,0,0
HB-042320,City Hotel,0,22,2023,September,36,4,2023-09-04,2,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,75.6,0,0
HB-083853,City Hotel,0,72,2024,February,7,12,2024-02-12,0,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,60.0,0,1
HB-008240,Resort Hotel,1,200,2024,September,38,19,2024-09-19,1,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,90.0,0,1
HB-054730,City Hotel,0,206,2024,July,30,25,2024-07-25,1,0,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.3,0,2
HB-114180,City Hotel,0,44,2025,June,25,17,2025-06-17,0,1,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,210.0,0,3
HB-037407,Resort Hotel,0,10,2025,June,24,13,2025-06-13,0,4,3,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,230.0,0,0
HB-004988,Resort Hotel,1,52,2024,April,15,11,2024-04-11,1,3,2,0.0,1,HB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,120.0,0,0
HB-049416,City Hotel,1,138,2024,April,15,13,2024-04-13,0,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,90.0,0,0
HB-084960,City Hotel,0,49,2024,March,9,2,2024-03-02,1,4,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,65.75,0,0
HB-106462,City Hotel,0,134,2025,February,9,25,2025-02-25,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,75.0,0,0
HB-033872,Resort Hotel,0,7,2025,March,9,2,2025-03-02,1,3,2,0.0,0,BB,BEL,Groups,Corporate,0,0,0,A,C,0,No Deposit,,223.0,0,Transient-Party,37.0,0,0
HB-037517,Resort Hotel,0,330,2025,June,24,10,2025-06-10,4,7,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,40.0,,0,Transient,85.7,0,0
HB-013407,Resort Hotel,1,53,2025,August,33,14,2025-08-14,1,2,3,1.0,0,HB,ESP,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,388.0,0,0
HB-052584,City Hotel,1,56,2024,June,23,8,2024-06-08,0,1,2,0.0,0,BB,PRT,Offline TA/TO,Corporate,0,0,0,A,A,0,No Deposit,191.0,,0,Transient-Party,120.0,0,0
HB-008350,Resort Hotel,1,39,2024,September,39,23,2024-09-23,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,139.0,0,1
HB-040552,City Hotel,1,115,2023,July,30,30,2023-07-30,0,3,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,55.08,0,0
HB-109200,City Hotel,0,102,2025,April,14,4,2025-04-04,0,4,3,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,157.25,0,1
HB-101485,City Hotel,0,32,2024,November,46,11,2024-11-11,0,2,2,0.0,0,SC,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,63.0,0,0
HB-048767,City Hotel,1,112,2024,March,13,30,2024-03-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,64.0,0,0
HB-060300,City Hotel,1,277,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-118989,City Hotel,0,290,2025,August,34,21,2025-08-21,2,5,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,99.0,0,2
HB-092842,City Hotel,0,30,2024,July,27,7,2024-07-07,2,4,3,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,168.3,0,4
HB-045118,City Hotel,0,118,2023,October,42,16,2023-10-16,1,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,98.25,1,1
HB-022244,Resort Hotel,0,5,2024,March,11,15,2024-03-15,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,95.0,,0,Transient,45.0,0,1
HB-019865,Resort Hotel,0,11,2024,January,1,3,2024-01-03,2,1,2,0.0,1,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient,39.0,1,1
HB-025984,Resort Hotel,0,227,2024,July,28,10,2024-07-10,3,5,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,96.0,,0,Transient,131.6,0,1
HB-039657,Resort Hotel,0,244,2025,August,33,15,2025-08-15,2,8,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,136.85,0,0
HB-043174,City Hotel,0,14,2023,September,37,16,2023-09-16,0,1,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Contract,114.0,0,1
HB-041400,City Hotel,0,131,2023,August,33,15,2023-08-15,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-087207,City Hotel,0,32,2024,April,15,13,2024-04-13,0,3,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,140.7,0,1
HB-103881,City Hotel,0,15,2024,December,52,27,2024-12-27,1,5,2,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,220.0,,0,Transient-Party,70.0,0,0
HB-113874,City Hotel,0,0,2025,June,24,12,2025-06-12,1,0,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,F,F,0,No Deposit,14.0,,0,Transient,265.0,0,0
HB-104734,City Hotel,0,29,2025,January,3,18,2025-01-18,0,3,1,0.0,0,BB,BEL,Groups,TA/TO,0,0,0,A,A,0,No Deposit,171.0,,0,Transient-Party,65.0,0,0
HB-006812,Resort Hotel,1,139,2024,July,27,3,2024-07-03,2,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,193.0,0,0
HB-093252,City Hotel,0,132,2024,July,28,13,2024-07-13,2,4,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.75,0,2
HB-097341,City Hotel,0,41,2024,September,37,14,2024-09-14,0,1,1,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,E,2,No Deposit,86.0,,0,Transient-Party,108.0,0,0
HB-007903,Resort Hotel,1,223,2024,September,35,1,2024-09-01,4,10,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Contract,90.1,0,2
HB-081311,City Hotel,0,37,2023,December,49,5,2023-12-05,2,1,3,0.0,0,HB,ESP,Direct,Direct,0,0,0,E,E,2,No Deposit,14.0,,0,Transient,196.35,1,0
HB-066566,City Hotel,1,158,2025,April,17,21,2025-04-21,2,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,1
HB-111326,City Hotel,0,117,2025,May,19,6,2025-05-06,2,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,100.8,0,1
HB-062265,City Hotel,1,10,2025,January,2,6,2025-01-06,2,2,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,71.19,0,0
HB-009795,Resort Hotel,1,47,2025,January,1,2,2025-01-02,1,4,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,72.0,0,2
HB-071236,City Hotel,1,135,2025,June,27,30,2025-06-30,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,30.0,,0,Transient,120.0,0,0
HB-025092,Resort Hotel,0,108,2024,June,24,11,2024-06-11,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,147.25,0,1
HB-110220,City Hotel,0,250,2025,April,16,18,2025-04-18,1,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,114.37,0,1
HB-052774,City Hotel,1,69,2024,June,24,12,2024-06-12,2,4,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,120.0,0,0
HB-114365,City Hotel,0,110,2025,June,25,19,2025-06-19,1,1,2,0.0,0,SC,ISR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,1
HB-112586,City Hotel,0,208,2025,May,21,24,2025-05-24,0,2,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,114.4,0,0
HB-066041,City Hotel,1,159,2025,April,15,13,2025-04-13,0,3,2,0.0,1,SC,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,117.0,0,1
HB-092995,City Hotel,0,113,2024,July,28,12,2024-07-12,0,3,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,137.7,0,2
HB-083475,City Hotel,0,0,2024,March,11,16,2024-03-16,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,2,A,D,0,No Deposit,,40.0,0,Transient,65.0,0,1
HB-102200,City Hotel,0,40,2024,November,47,20,2024-11-20,2,2,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,57.6,0,1
HB-073122,City Hotel,1,507,2025,August,33,15,2025-08-15,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-002580,Resort Hotel,0,21,2023,October,42,22,2023-10-22,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Transient,55.43,0,0
HB-077281,City Hotel,1,43,2023,October,43,23,2023-10-23,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Contract,105.12,0,2
HB-035062,Resort Hotel,0,4,2025,April,15,10,2025-04-10,1,2,1,0.0,0,HB,BEL,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,277.0,0,Transient,59.33,0,1
HB-110677,City Hotel,0,27,2025,April,18,28,2025-04-28,1,2,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,124.0,1,1
HB-049262,City Hotel,0,268,2024,April,15,8,2024-04-08,2,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,224,Transient-Party,78.0,0,0
HB-057074,City Hotel,1,76,2024,September,38,18,2024-09-18,2,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,102.68,0,0
HB-077652,City Hotel,1,98,2023,December,52,26,2023-12-26,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,8.0,,0,Transient,118.0,0,1
HB-074586,City Hotel,1,353,2023,October,40,5,2023-10-05,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-008283,Resort Hotel,0,343,2024,September,38,21,2024-09-21,0,4,1,0.0,0,HB,BEL,Corporate,Corporate,0,0,0,A,A,1,No Deposit,183.0,,0,Transient-Party,56.5,0,0
HB-083741,City Hotel,0,4,2024,February,6,8,2024-02-08,1,2,2,0.0,0,HB,BEL,Offline TA/TO,TA/TO,0,0,0,A,E,0,No Deposit,28.0,,0,Transient,117.0,0,0
HB-034036,Resort Hotel,0,14,2025,March,10,8,2025-03-08,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,60.0,0,2
HB-007438,Resort Hotel,1,169,2024,August,32,9,2024-08-09,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,180.0,0,2
HB-103880,City Hotel,0,44,2025,January,1,1,2025-01-01,1,0,2,1.0,0,BB,BRA,Groups,TA/TO,0,0,0,A,D,3,No Deposit,,,0,Transient-Party,65.0,0,0
HB-029396,Resort Hotel,0,116,2024,October,43,23,2024-10-23,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient-Party,68.0,0,1
HB-014274,Resort Hotel,0,17,2025,July,30,24,2025-07-24,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,2,14,A,F,0,No Deposit,,292.0,0,Transient,142.0,0,1
HB-001847,Resort Hotel,1,62,2023,September,37,17,2023-09-17,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,83.0,0,0
HB-116854,City Hotel,0,67,2025,July,30,24,2025-07-24,1,1,2,0.0,0,BB,USA,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,122.6,0,0
HB-019773,Resort Hotel,0,53,2023,December,52,27,2023-12-27,2,5,2,0.0,0,BB,CHE,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,6.0,,0,Transient,65.43,0,0
HB-107800,City Hotel,0,182,2025,March,11,11,2025-03-11,2,6,3,0.0,0,BB,GBR,Corporate,TA/TO,0,0,0,D,D,1,No Deposit,330.0,,0,Transient-Party,125.0,0,1
HB-019441,Resort Hotel,0,5,2023,December,51,19,2023-12-19,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,,0,Transient-Party,43.0,0,1
HB-056235,City Hotel,1,193,2024,September,35,1,2024-09-01,0,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.9,0,0
HB-054079,City Hotel,1,245,2024,July,27,6,2024-07-06,2,4,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,110.0,0,0
HB-053704,City Hotel,1,101,2024,June,26,27,2024-06-27,1,5,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,140.0,0,0
HB-100916,City Hotel,0,58,2024,October,44,31,2024-10-31,1,3,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.68,0,2
HB-070136,City Hotel,1,42,2025,June,24,10,2025-06-10,2,3,2,0.0,0,HB,HRV,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,131.6,0,1
HB-033747,Resort Hotel,0,3,2025,February,9,27,2025-02-27,1,2,2,1.0,0,BB,BRA,Online TA,TA/TO,0,0,0,C,C,1,No Deposit,240.0,,0,Transient,67.0,0,1
HB-035353,Resort Hotel,0,0,2025,April,16,17,2025-04-17,1,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,2,No Deposit,,,0,Transient,91.0,0,0
HB-078361,City Hotel,0,12,2023,October,40,7,2023-10-07,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,119.7,0,0
HB-111041,City Hotel,0,89,2025,May,18,1,2025-05-01,1,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,92.17,0,1
HB-040778,City Hotel,0,0,2023,August,32,7,2023-08-07,0,2,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Contract,162.0,1,1
HB-070742,City Hotel,1,115,2025,June,25,21,2025-06-21,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,93.6,0,0
HB-026587,Resort Hotel,0,34,2024,August,31,2,2024-08-02,0,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,165.23,0,0
HB-090436,City Hotel,0,75,2024,June,23,4,2024-06-04,1,1,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,89.28,0,0
HB-001477,Resort Hotel,0,26,2023,August,35,31,2023-08-31,1,3,2,2.0,0,HB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,250.0,,0,Transient,155.5,0,0
HB-045960,City Hotel,1,104,2023,December,48,3,2023-12-03,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,55.0,,0,Transient,75.0,0,0
HB-076289,City Hotel,1,147,2023,July,29,21,2023-07-21,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient,75.0,0,0
HB-055008,City Hotel,1,244,2024,August,31,2,2024-08-02,0,4,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,3,No Deposit,9.0,,0,Transient,90.95,0,0
HB-086414,City Hotel,0,4,2024,April,14,2,2024-04-02,0,1,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,1
HB-085731,City Hotel,0,13,2024,March,12,20,2024-03-20,1,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,220.0,,0,Transient-Party,85.0,0,1
HB-057419,City Hotel,1,35,2024,September,39,26,2024-09-26,1,1,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,149.4,0,1
HB-047670,City Hotel,1,116,2024,February,9,28,2024-02-28,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,61.0,0,0
HB-096652,City Hotel,0,15,2024,September,36,2,2024-09-02,1,2,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,153.0,0,0
HB-088520,City Hotel,0,7,2024,May,18,5,2024-05-05,0,3,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,112.0,0,0
HB-063323,City Hotel,1,36,2025,February,6,8,2025-02-08,2,4,1,0.0,0,SC,AGO,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,74.8,0,0
HB-033072,Resort Hotel,0,15,2025,February,6,8,2025-02-08,2,4,1,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,43.0,0,2
HB-059251,City Hotel,1,250,2024,October,43,24,2024-10-24,1,2,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,128.7,0,1
HB-057570,City Hotel,1,26,2024,September,39,27,2024-09-27,0,4,2,2.0,0,BB,BEL,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,226.5,0,0
HB-091108,City Hotel,0,256,2024,June,24,15,2024-06-15,0,2,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,90.0,0,0
HB-052730,City Hotel,1,8,2024,June,24,10,2024-06-10,0,2,2,0.0,0,BB,AUS,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,156.0,0,0
HB-021889,Resort Hotel,0,30,2024,March,10,7,2024-03-07,1,5,2,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,38.0,,0,Transient-Party,65.4,0,0
HB-077257,City Hotel,1,6,2023,September,38,20,2023-09-20,2,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,1,0,A,A,0,Non Refund,78.0,,0,Transient,90.0,0,0
HB-087715,City Hotel,0,186,2024,April,17,22,2024-04-22,1,2,3,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,23.0,,0,Transient-Party,115.0,0,0
HB-112215,City Hotel,0,123,2025,May,21,19,2025-05-19,0,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-030521,Resort Hotel,0,24,2024,November,46,13,2024-11-13,4,9,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,171.0,,0,Transient,54.0,0,0
HB-002473,Resort Hotel,0,68,2023,October,42,18,2023-10-18,4,6,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,55.0,0,2
HB-059303,City Hotel,1,2,2024,October,43,26,2024-10-26,0,2,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,130.0,0,0
HB-059934,City Hotel,1,51,2024,November,44,3,2024-11-03,1,3,1,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.0,0,0
HB-111352,City Hotel,0,1,2025,May,19,9,2025-05-09,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,238.0,0,Transient,65.0,0,0
HB-087412,City Hotel,0,41,2024,April,16,19,2024-04-19,0,1,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,99.9,1,1
HB-032538,Resort Hotel,0,0,2025,January,5,29,2025-01-29,1,0,2,0.0,0,BB,ITA,Direct,TA/TO,1,0,0,A,A,0,No Deposit,,,0,Transient-Party,45.0,0,2
HB-071750,City Hotel,1,312,2025,July,28,11,2025-07-11,0,4,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,126.73,0,1
HB-119372,City Hotel,0,175,2025,August,35,31,2025-08-31,1,3,2,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,42.0,,0,Transient,86.85,0,2
HB-035460,Resort Hotel,0,57,2025,April,16,14,2025-04-14,2,7,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,D,D,0,No Deposit,493.0,,0,Contract,92.0,0,0
HB-044578,City Hotel,1,210,2023,October,40,8,2023-10-08,1,3,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,B,0,No Deposit,12.0,,0,Transient-Party,0.0,0,0
HB-106640,City Hotel,0,3,2025,February,9,27,2025-02-27,1,1,1,0.0,0,SC,ZAF,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,88.0,0,2
HB-108309,City Hotel,0,116,2025,March,13,24,2025-03-24,0,2,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,D,1,No Deposit,171.0,,0,Transient-Party,100.0,0,1
HB-054252,City Hotel,1,54,2024,July,28,10,2024-07-10,2,0,2,0.0,0,SC,ZAF,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,103.5,0,0
HB-117315,City Hotel,0,208,2025,July,30,25,2025-07-25,2,6,3,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,16.0,,0,Transient,107.1,0,0
HB-083524,City Hotel,0,7,2024,February,6,5,2024-02-05,0,1,2,0.0,1,SC,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,81.0,0,2
HB-084901,City Hotel,0,316,2024,May,21,26,2024-05-26,0,3,2,0.0,0,BB,AUT,Groups,TA/TO,0,0,1,A,A,0,No Deposit,30.0,,0,Transient-Party,110.0,0,0
HB-107068,City Hotel,0,10,2025,March,10,5,2025-03-05,2,0,1,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.0,0,1
HB-070045,City Hotel,1,178,2025,June,24,9,2025-06-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,86.0,,0,Transient,130.0,0,0
HB-047268,City Hotel,1,1,2024,February,7,14,2024-02-14,1,0,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.0,0,0
HB-071068,City Hotel,1,141,2025,June,26,27,2025-06-27,2,5,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,130.0,0,0
HB-029683,Resort Hotel,0,34,2024,October,44,28,2024-10-28,2,5,2,0.0,0,HB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,89.59,0,2
HB-094980,City Hotel,0,111,2024,August,32,11,2024-08-11,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,127.8,0,1
HB-061447,City Hotel,1,30,2024,December,50,11,2024-12-11,2,0,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,2
HB-014146,Resort Hotel,0,9,2023,December,49,9,2023-12-09,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,154.0,0,Transient,25.0,0,0
HB-040293,City Hotel,1,119,2023,July,29,20,2023-07-20,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,76.5,0,1
HB-091187,City Hotel,0,144,2024,June,24,15,2024-06-15,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,9.0,,0,Transient,140.4,0,2
HB-107405,City Hotel,0,165,2025,March,10,9,2025-03-09,1,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.4,0,3
HB-058377,City Hotel,1,184,2024,October,41,12,2024-10-12,0,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.1,0,0
HB-064792,City Hotel,1,129,2025,March,11,16,2025-03-16,0,3,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.85,0,1
HB-032517,Resort Hotel,0,2,2025,January,5,28,2025-01-28,0,1,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,88.0,0,1
HB-092409,City Hotel,0,8,2024,June,26,30,2024-06-30,2,4,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,204.0,0,1
HB-078913,City Hotel,0,16,2023,October,41,15,2023-10-15,1,3,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,D,1,No Deposit,1.0,,0,Transient-Party,65.0,0,0
HB-044661,City Hotel,0,60,2023,October,41,9,2023-10-09,0,2,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,62.18,0,1
HB-061649,City Hotel,1,38,2024,December,51,21,2024-12-21,1,4,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.7,0,1
HB-100773,City Hotel,0,195,2024,October,44,28,2024-10-28,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.3,0,2
HB-008215,Resort Hotel,1,244,2024,September,38,18,2024-09-18,2,1,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,140.0,0,1
HB-092558,City Hotel,0,4,2024,July,27,6,2024-07-06,0,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,139.0,0,1
HB-041496,City Hotel,0,3,2023,August,33,17,2023-08-17,1,2,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,117.33,0,0
HB-028956,Resort Hotel,0,364,2024,October,41,12,2024-10-12,1,4,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,1,No Deposit,,223.0,0,Transient-Party,72.0,0,0
HB-030025,Resort Hotel,0,12,2024,November,45,8,2024-11-08,0,4,1,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient-Party,55.0,1,1
HB-055131,City Hotel,1,171,2024,August,32,5,2024-08-05,2,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.45,0,0
HB-068108,City Hotel,1,105,2025,May,20,13,2025-05-13,1,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-031750,Resort Hotel,0,1,2024,March,10,8,2024-03-08,0,3,2,0.0,0,BB,GBR,Direct,Direct,0,0,5,D,D,1,No Deposit,250.0,,0,Transient,39.33,0,0
HB-053637,City Hotel,1,37,2024,June,26,26,2024-06-26,2,1,2,1.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,115.32,0,0
HB-059045,City Hotel,1,91,2024,October,42,20,2024-10-20,0,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,132.3,0,2
HB-101275,City Hotel,0,34,2024,November,45,7,2024-11-07,1,2,1,0.0,0,BB,DEU,Online TA,GDS,0,0,0,A,A,0,No Deposit,195.0,,0,Transient,169.2,0,0
HB-075813,City Hotel,1,330,2023,September,37,12,2023-09-12,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-038736,Resort Hotel,0,140,2025,July,30,26,2025-07-26,0,2,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,200.0,0,2
HB-069930,City Hotel,1,169,2025,June,23,8,2025-06-08,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,170.0,0,0
HB-111919,City Hotel,0,13,2025,May,20,17,2025-05-17,0,1,1,0.0,0,BB,ESP,Corporate,Corporate,0,0,0,D,D,0,No Deposit,,150.0,0,Transient,110.0,0,0
HB-091310,City Hotel,0,1,2024,June,25,17,2024-06-17,1,2,2,0.0,0,BB,AUT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,75.0,0,1
HB-040809,City Hotel,0,0,2023,August,32,7,2023-08-07,2,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,75.0,0,0
HB-116426,City Hotel,0,59,2025,July,29,17,2025-07-17,1,2,3,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,200.0,0,0
HB-101456,City Hotel,0,76,2024,November,46,11,2024-11-11,0,2,2,0.0,0,SC,ZAF,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,1
HB-025803,Resort Hotel,0,128,2024,July,27,7,2024-07-07,2,3,2,1.0,0,BB,RUS,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,241.0,,0,Transient,169.95,0,1
HB-019932,Resort Hotel,0,20,2024,January,2,8,2024-01-08,0,2,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,258.0,,0,Transient,35.25,0,0
HB-111146,City Hotel,0,58,2025,May,19,6,2025-05-06,0,1,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,187.2,1,0
HB-031058,Resort Hotel,0,0,2024,December,50,12,2024-12-12,1,0,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,241.0,,0,Transient,41.11,1,1
HB-004346,Resort Hotel,1,49,2024,March,10,5,2024-03-05,2,2,2,0.0,0,HB,PRT,Groups,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient-Party,81.0,0,0
HB-106440,City Hotel,0,13,2025,February,8,22,2025-02-22,0,3,2,0.0,0,BB,GBR,Online TA,GDS,0,0,0,A,A,1,No Deposit,195.0,,0,Transient,105.33,0,1
HB-036994,Resort Hotel,0,50,2025,May,22,31,2025-05-31,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,1,No Deposit,250.0,,0,Transient,150.0,0,0
HB-069125,City Hotel,1,197,2025,May,21,25,2025-05-25,2,4,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,129.6,0,1
HB-040711,City Hotel,0,0,2023,August,31,5,2023-08-05,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,90.0,0,2
HB-115632,City Hotel,0,145,2025,July,27,6,2025-07-06,0,3,3,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,152.1,0,1
HB-005152,Resort Hotel,0,172,2024,April,16,18,2024-04-18,3,5,1,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,115.0,,0,Transient-Party,46.8,0,1
HB-000799,Resort Hotel,0,17,2023,July,30,30,2023-07-30,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,240.0,,0,Transient,153.0,0,1
HB-103147,City Hotel,0,198,2024,December,49,8,2024-12-08,2,3,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,63.75,0,2
HB-031030,Resort Hotel,0,9,2025,January,3,14,2025-01-14,0,1,2,0.0,0,HB,PRT,Online TA,TA/TO,1,0,1,A,D,0,No Deposit,240.0,,0,Transient,85.0,1,3
HB-072237,City Hotel,1,108,2025,July,30,24,2025-07-24,1,2,3,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,195.0,0,1
HB-113955,City Hotel,0,94,2025,June,24,11,2025-06-11,2,2,2,0.0,0,BB,PHL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,126.0,0,0
HB-023093,Resort Hotel,0,27,2024,April,15,8,2024-04-08,2,5,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient,64.8,0,0
HB-107251,City Hotel,0,75,2025,March,10,5,2025-03-05,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,91.8,0,1
HB-034205,Resort Hotel,0,26,2025,March,11,14,2025-03-14,0,2,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,55.0,0,0
HB-029886,Resort Hotel,0,0,2024,November,45,7,2024-11-07,1,0,2,0.0,0,BB,NLD,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,70.0,0,0
HB-113322,City Hotel,0,317,2025,June,23,2,2025-06-02,1,2,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,104.4,0,3
HB-033584,Resort Hotel,0,62,2025,February,9,25,2025-02-25,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-025080,Resort Hotel,0,0,2024,June,24,12,2024-06-12,2,0,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,126.0,1,1
HB-028132,Resort Hotel,0,19,2024,September,38,19,2024-09-19,1,1,2,0.0,0,Undefined,IRL,Direct,Direct,0,0,0,A,A,1,No Deposit,250.0,,0,Transient,169.0,1,0
HB-041766,City Hotel,0,11,2023,August,34,23,2023-08-23,2,1,2,1.0,0,BB,ESP,Direct,Direct,0,0,0,A,D,0,No Deposit,14.0,,0,Transient,90.0,0,1
HB-012194,Resort Hotel,1,250,2025,June,25,17,2025-06-17,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,80.1,0,2
HB-115359,City Hotel,0,74,2025,July,27,1,2025-07-01,2,2,1,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,150.0,0,1
HB-059898,City Hotel,1,304,2024,November,44,3,2024-11-03,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,89.0,0,0
HB-010587,Resort Hotel,1,232,2025,March,11,16,2025-03-16,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,55.8,0,1
HB-015836,Resort Hotel,0,4,2023,August,31,3,2023-08-03,1,0,2,1.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,241.0,,0,Transient,143.34,0,2
HB-045910,City Hotel,0,84,2023,November,48,27,2023-11-27,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,0.0,0,0
HB-093561,City Hotel,0,292,2024,July,29,21,2024-07-21,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,0
HB-088648,City Hotel,0,15,2024,May,20,18,2024-05-18,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,1,A,F,0,No Deposit,86.0,,0,Transient,112.8,0,0
HB-061026,City Hotel,1,35,2024,November,48,29,2024-11-29,4,11,2,0.0,0,SC,AGO,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,2
HB-114332,City Hotel,0,448,2025,June,25,17,2025-06-17,2,1,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,1
HB-106515,City Hotel,0,3,2025,February,9,24,2025-02-24,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,113.0,0,0
HB-117666,City Hotel,0,146,2025,August,32,4,2025-08-04,2,2,2,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,52.0,,0,Transient,80.1,0,1
HB-062323,City Hotel,1,129,2025,January,2,8,2025-01-08,2,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,D,D,0,Non Refund,,,0,Transient,67.0,0,0
HB-097202,City Hotel,0,20,2024,September,37,12,2024-09-12,1,0,1,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.0,0,2
HB-097589,City Hotel,0,84,2024,September,37,13,2024-09-13,0,5,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,168.3,0,2
HB-036757,Resort Hotel,0,2,2025,May,22,28,2025-05-28,1,0,2,0.0,0,BB,GBR,Direct,TA/TO,0,0,0,E,E,0,No Deposit,,,0,Transient,115.0,1,0
HB-111444,City Hotel,0,75,2025,May,19,9,2025-05-09,0,2,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,112.1,0,0
HB-117771,City Hotel,0,71,2025,August,32,6,2025-08-06,2,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,150.0,0,3
HB-096244,City Hotel,0,6,2024,August,35,26,2024-08-26,2,3,2,0.0,0,BB,SRB,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,101.73,0,1
HB-024529,Resort Hotel,0,119,2024,May,20,18,2024-05-18,2,5,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,36.0,,0,Transient,41.75,0,0
HB-068110,City Hotel,1,105,2025,May,20,13,2025-05-13,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.0,0,0
HB-008735,Resort Hotel,0,364,2024,October,41,12,2024-10-12,0,4,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,0,No Deposit,,223.0,0,Transient-Party,66.0,0,0
HB-063626,City Hotel,1,587,2025,February,7,16,2025-02-16,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-101515,City Hotel,0,50,2024,November,46,11,2024-11-11,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,8.0,,0,Transient,97.2,0,1
HB-022547,Resort Hotel,0,0,2024,March,13,27,2024-03-27,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,48.0,0,0
HB-069673,City Hotel,1,348,2025,June,23,3,2025-06-03,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient,90.0,0,0
HB-090360,City Hotel,0,126,2024,June,22,2,2024-06-02,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient-Party,80.75,0,0
HB-089974,City Hotel,0,95,2024,May,22,29,2024-05-29,2,0,1,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,0.0,0,0
HB-039915,Resort Hotel,0,31,2025,August,35,28,2025-08-28,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,196.75,1,2
HB-027405,Resort Hotel,0,97,2025,August,32,8,2025-08-08,2,5,2,0.0,0,HB,PRT,Direct,TA/TO,1,0,1,F,F,2,No Deposit,250.0,,0,Transient,349.0,0,2
HB-041441,City Hotel,0,5,2023,August,33,16,2023-08-16,2,3,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Contract,162.0,1,2
HB-074529,City Hotel,1,332,2023,September,37,14,2023-09-14,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-043711,City Hotel,0,83,2023,September,38,23,2023-09-23,0,2,3,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,D,1,No Deposit,1.0,,0,Transient-Party,84.0,0,0
HB-061546,City Hotel,1,185,2024,December,51,16,2024-12-16,1,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,0
HB-110081,City Hotel,0,145,2025,April,16,15,2025-04-15,2,5,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,16.0,,0,Transient,89.1,0,0
HB-036621,Resort Hotel,0,203,2025,May,21,25,2025-05-25,0,3,1,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,D,D,1,No Deposit,,223.0,0,Transient-Party,60.0,0,0
HB-016075,Resort Hotel,0,65,2023,August,32,8,2023-08-08,2,4,2,0.0,0,HB,ESP,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,209.0,0,1
HB-039031,Resort Hotel,0,174,2025,August,31,1,2025-08-01,0,5,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,D,D,1,No Deposit,250.0,,0,Transient,193.1,0,1
HB-110339,City Hotel,0,217,2025,April,17,25,2025-04-25,0,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,99.0,0,1
HB-001971,Resort Hotel,0,0,2023,September,39,25,2023-09-25,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,,240.0,0,Group,80.1,0,0
HB-023214,Resort Hotel,0,0,2024,April,16,17,2024-04-17,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,85.0,0,0
HB-088638,City Hotel,0,0,2024,December,51,22,2024-12-22,0,1,1,0.0,0,SC,PRT,Online TA,TA/TO,1,0,4,A,A,0,No Deposit,86.0,,0,Transient,56.0,0,0
HB-080189,City Hotel,0,0,2023,November,48,30,2023-11-30,3,7,1,0.0,0,BB,NLD,Online TA,TA/TO,1,0,1,A,A,1,No Deposit,,,0,Transient,69.0,0,1
HB-019357,Resort Hotel,0,0,2023,December,50,15,2023-12-15,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,355.0,0,Transient,35.0,0,0
HB-005378,Resort Hotel,1,12,2024,April,17,27,2024-04-27,0,3,2,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,A,A,1,No Deposit,385.0,,0,Transient-Party,72.0,0,0
HB-015140,Resort Hotel,1,217,2023,August,35,28,2023-08-28,3,7,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,40.0,,0,Contract,88.4,0,0
HB-057374,City Hotel,1,64,2024,September,39,24,2024-09-24,2,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,149.4,0,1
HB-030467,Resort Hotel,0,58,2024,November,46,17,2024-11-17,2,5,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,58.4,1,0
HB-106409,City Hotel,0,1,2025,February,9,24,2025-02-24,0,1,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.0,0,2
HB-057158,City Hotel,1,12,2024,September,38,19,2024-09-19,1,3,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,D,D,2,No Deposit,,280.0,0,Transient,110.0,0,0
HB-040153,City Hotel,1,96,2023,July,28,11,2023-07-11,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-103017,City Hotel,0,85,2024,December,49,8,2024-12-08,0,3,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-054177,City Hotel,1,94,2024,July,27,7,2024-07-07,2,3,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,146.7,0,0
HB-105211,City Hotel,0,43,2025,January,5,28,2025-01-28,2,3,2,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,68.0,0,1
HB-094513,City Hotel,0,114,2024,August,31,4,2024-08-04,0,2,3,0.0,0,BB,AUS,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,137.7,0,0
HB-013125,Resort Hotel,1,334,2025,August,31,1,2025-08-01,0,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,156.6,0,0
HB-074994,City Hotel,1,260,2023,July,27,4,2023-07-04,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-102009,City Hotel,0,1,2024,November,47,18,2024-11-18,1,2,0,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,K,1,No Deposit,9.0,,0,Transient,92.67,0,2
HB-011941,Resort Hotel,1,69,2025,June,23,4,2025-06-04,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,144.0,0,1
HB-031642,Resort Hotel,0,78,2024,December,1,31,2024-12-31,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,C,1,No Deposit,181.0,,0,Transient-Party,168.0,0,0
HB-094186,City Hotel,0,301,2024,July,31,30,2024-07-30,1,1,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,90.0,0,0
HB-044734,City Hotel,1,174,2023,October,41,10,2023-10-10,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,70.0,0,0
HB-031396,Resort Hotel,0,32,2024,December,51,19,2024-12-19,3,5,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,314.0,,0,Transient,50.15,0,0
HB-092288,City Hotel,0,153,2024,June,26,30,2024-06-30,1,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.75,0,2
HB-008445,Resort Hotel,1,63,2024,September,39,28,2024-09-28,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,96.0,,0,Transient-Party,76.0,0,0
HB-083416,City Hotel,0,2,2024,January,5,29,2024-01-29,0,2,2,1.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,9.0,,0,Transient,162.0,0,1
HB-098924,City Hotel,0,45,2024,October,40,4,2024-10-04,0,3,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,102.04,0,1
HB-036859,Resort Hotel,0,5,2025,May,22,29,2025-05-29,1,1,2,0.0,0,BB,CPV,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,81.0,0,1
HB-003208,Resort Hotel,0,124,2023,November,47,21,2023-11-21,0,1,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,D,F,0,No Deposit,241.0,,0,Transient,54.05,0,1
HB-012778,Resort Hotel,1,181,2025,July,29,16,2025-07-16,2,5,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,171.71,0,2
HB-042447,City Hotel,0,61,2023,September,36,5,2023-09-05,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-038545,Resort Hotel,0,160,2025,July,29,16,2025-07-16,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,143.0,,0,Transient,134.85,0,1
HB-100406,City Hotel,0,12,2024,October,43,25,2024-10-25,0,3,1,0.0,0,BB,BIH,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.0,0,2
HB-081402,City Hotel,0,75,2023,December,49,9,2023-12-09,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-102657,City Hotel,0,205,2024,December,48,1,2024-12-01,0,3,2,0.0,0,BB,DNK,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,83.0,,0,Transient,69.36,0,0
HB-082176,City Hotel,1,99,2024,February,8,19,2024-02-19,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,1,0,A,A,0,No Deposit,,67.0,0,Transient-Party,80.0,0,0
HB-113027,City Hotel,0,133,2025,May,22,29,2025-05-29,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,85.0,0,1
HB-056700,City Hotel,1,93,2024,September,37,10,2024-09-10,2,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,159.17,0,1
HB-052340,City Hotel,1,54,2024,June,23,4,2024-06-04,0,1,2,0.0,0,BB,KOR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,159.3,0,0
HB-115628,City Hotel,0,181,2025,July,27,6,2025-07-06,0,3,2,0.0,0,BB,POL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,89.1,0,0
HB-091731,City Hotel,0,192,2024,June,26,24,2024-06-24,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,34.0,,0,Transient-Party,95.0,0,0
HB-044234,City Hotel,0,164,2023,October,40,2,2023-10-02,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,19.0,,0,Transient-Party,100.0,0,0
HB-014411,Resort Hotel,0,58,2024,September,37,10,2024-09-10,2,5,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,E,0,No Deposit,,,0,Transient,130.0,1,1
HB-036826,Resort Hotel,0,2,2025,May,22,28,2025-05-28,2,0,2,0.0,0,HB,USA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,159.0,1,0
HB-037222,Resort Hotel,0,145,2025,June,23,4,2025-06-04,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Transient,70.4,0,0
HB-083393,City Hotel,0,4,2024,January,4,28,2024-01-28,0,3,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,95.0,1,1
HB-070069,City Hotel,1,219,2025,June,24,9,2025-06-09,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,105.0,0,0
HB-085866,City Hotel,0,12,2024,March,12,19,2024-03-19,2,2,2,0.0,0,SC,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,138.0,,0,Transient,71.8,1,0
HB-007955,Resort Hotel,1,164,2024,September,36,4,2024-09-04,2,5,2,2.0,0,FB,PRT,Direct,Direct,0,0,0,C,C,1,No Deposit,250.0,,0,Transient,240.6,0,0
HB-092637,City Hotel,0,91,2024,July,27,3,2024-07-03,2,5,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,146.7,0,0
HB-108791,City Hotel,0,48,2025,March,13,26,2025-03-26,2,5,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,142.61,0,1
HB-109937,City Hotel,0,96,2025,April,15,11,2025-04-11,2,6,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,187.0,0,2
HB-025473,Resort Hotel,0,33,2024,June,26,27,2024-06-27,1,1,2,0.0,0,BB,LTU,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,242.0,,0,Transient,131.0,0,0
HB-002415,Resort Hotel,0,2,2023,October,41,12,2023-10-12,1,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,56.0,0,1
HB-036863,Resort Hotel,0,314,2025,May,21,22,2025-05-22,3,7,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Contract,84.7,0,0
HB-111657,City Hotel,0,66,2025,May,19,11,2025-05-11,0,3,2,0.0,0,BB,ISL,Direct,Direct,0,0,0,G,G,0,No Deposit,14.0,,0,Transient,295.0,0,0
HB-036167,Resort Hotel,0,302,2025,May,19,9,2025-05-09,0,4,2,0.0,0,HB,GBR,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,81.0,0,0
HB-049905,City Hotel,0,265,2024,April,16,20,2024-04-20,0,4,2,0.0,0,BB,AUT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,176,Transient-Party,99.0,0,0
HB-013531,Resort Hotel,1,185,2025,August,34,18,2025-08-18,2,5,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,200.0,0,0
HB-056233,City Hotel,1,78,2024,September,35,1,2024-09-01,0,3,2,0.0,0,SC,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,122.1,0,0
HB-108126,City Hotel,0,28,2025,March,12,19,2025-03-19,2,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,91.8,0,0
HB-113727,City Hotel,0,96,2025,June,23,8,2025-06-08,0,3,3,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,9.0,,0,Transient,216.0,0,2
HB-100037,City Hotel,0,36,2024,October,42,20,2024-10-20,0,2,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.5,0,2
HB-025669,Resort Hotel,0,144,2024,June,26,27,2024-06-27,3,6,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,69.0,,0,Transient,83.7,0,1
HB-044305,City Hotel,1,89,2023,October,40,3,2023-10-03,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-086510,City Hotel,0,33,2024,April,14,2,2024-04-02,1,1,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,9.0,,0,Transient,131.4,0,0
HB-114802,City Hotel,0,396,2025,June,26,25,2025-06-25,2,0,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,122.4,0,1
HB-042161,City Hotel,0,5,2023,September,35,1,2023-09-01,0,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,96.0,0,0
HB-023261,Resort Hotel,0,32,2024,April,16,19,2024-04-19,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,E,0,No Deposit,,397.0,0,Transient-Party,50.0,0,0
HB-101805,City Hotel,0,0,2024,November,47,19,2024-11-19,0,0,0,0.0,0,BB,PRT,Online TA,TA/TO,1,0,0,A,A,0,No Deposit,9.0,,0,Transient,0.0,0,1
HB-011983,Resort Hotel,1,18,2025,June,23,7,2025-06-07,0,2,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,126.0,0,0
HB-040860,City Hotel,0,4,2023,August,32,8,2023-08-08,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-037000,Resort Hotel,0,130,2025,May,22,28,2025-05-28,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,70.4,0,0
HB-091185,City Hotel,0,60,2024,June,24,10,2024-06-10,2,5,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,B,0,No Deposit,16.0,,0,Transient,85.5,0,0
HB-105734,City Hotel,0,0,2025,February,7,14,2025-02-14,0,1,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,154.0,0,2
HB-073539,City Hotel,1,109,2025,August,35,25,2025-08-25,1,2,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,423.0,,0,Transient,142.41,0,0
HB-009599,Resort Hotel,1,206,2024,December,51,17,2024-12-17,6,12,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,34.8,0,0
HB-069770,City Hotel,1,437,2025,June,23,6,2025-06-06,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-052069,City Hotel,1,56,2024,May,22,30,2024-05-30,1,0,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,120.0,0,0
HB-023701,Resort Hotel,0,197,2024,April,18,30,2024-04-30,1,1,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,85.0,0,0
HB-005937,Resort Hotel,0,201,2024,May,20,16,2024-05-16,3,8,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,46.98,0,2
HB-074535,City Hotel,1,339,2023,September,38,21,2023-09-21,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-012077,Resort Hotel,1,140,2025,June,24,11,2025-06-11,2,4,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,E,E,2,No Deposit,240.0,,0,Transient,172.0,0,2
HB-103332,City Hotel,0,83,2024,December,51,18,2024-12-18,2,0,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-038552,Resort Hotel,0,1,2025,July,29,18,2025-07-18,0,4,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,233.0,0,1
HB-113072,City Hotel,0,61,2025,May,22,31,2025-05-31,0,2,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,1,No Deposit,,465.0,0,Transient,95.0,0,2
HB-087663,City Hotel,0,8,2024,April,16,21,2024-04-21,0,3,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,176.0,0,2
HB-114838,City Hotel,0,396,2025,June,26,25,2025-06-25,2,0,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,95.5,0,1
HB-021324,Resort Hotel,0,0,2024,February,9,29,2024-02-29,1,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,1,0,1,A,A,0,No Deposit,5.0,,0,Transient,34.4,0,1
HB-110313,City Hotel,0,31,2025,April,17,21,2025-04-21,2,3,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,21.0,,0,Transient-Party,75.0,0,0
HB-042079,City Hotel,1,18,2023,August,35,30,2023-08-30,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.0,0,1
HB-039145,Resort Hotel,0,14,2025,August,32,5,2025-08-05,2,2,2,0.0,0,BB,AUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,228.5,0,2
HB-100688,City Hotel,0,28,2024,October,44,30,2024-10-30,1,0,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,144.38,0,0
HB-064863,City Hotel,1,60,2025,March,12,18,2025-03-18,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,106.2,0,0
HB-074636,City Hotel,1,374,2023,October,43,26,2023-10-26,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-042858,City Hotel,0,168,2023,September,37,11,2023-09-11,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,60.0,0,0
HB-041732,City Hotel,1,138,2023,August,34,22,2023-08-22,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-114957,City Hotel,0,159,2025,June,26,23,2025-06-23,2,4,2,1.0,0,BB,DEU,Online TA,TA/TO,0,0,0,F,F,2,No Deposit,9.0,,0,Transient,189.0,0,0
HB-042687,City Hotel,1,55,2023,September,36,9,2023-09-09,0,2,2,0.0,0,BB,FRA,Corporate,Corporate,0,0,0,A,B,0,No Deposit,,68.0,0,Transient-Party,100.0,0,0
HB-005909,Resort Hotel,0,213,2024,May,20,16,2024-05-16,1,1,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient,85.0,0,0
HB-036919,Resort Hotel,0,212,2025,May,22,28,2025-05-28,2,2,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,410.0,,0,Transient,56.7,0,1
HB-042042,City Hotel,1,104,2023,August,35,30,2023-08-30,2,1,2,0.0,0,HB,ESP,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,90.0,0,0
HB-006186,Resort Hotel,0,204,2024,May,22,27,2024-05-27,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,59.28,0,2
HB-040641,City Hotel,0,0,2023,August,31,4,2023-08-04,0,2,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Contract,80.0,1,1
HB-077252,City Hotel,1,6,2023,September,38,20,2023-09-20,2,0,2,0.0,0,BB,PRT,Corporate,Corporate,0,1,0,A,A,0,Non Refund,78.0,,0,Transient,100.0,0,0
HB-053298,City Hotel,1,350,2024,June,25,17,2024-06-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,140.0,0,0
HB-005307,Resort Hotel,1,143,2024,April,17,24,2024-04-24,2,2,2,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,68.0,,0,Transient,84.0,0,0
HB-112415,City Hotel,0,59,2025,May,21,23,2025-05-23,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,89.1,0,2
HB-015592,Resort Hotel,0,42,2023,July,29,20,2023-07-20,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,175.0,,0,Transient,122.34,0,1
HB-060836,City Hotel,1,63,2024,November,47,23,2024-11-23,0,4,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,105.0,0,0
HB-106809,City Hotel,0,14,2025,March,9,2,2025-03-02,0,1,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,88.0,0,0
HB-014159,Resort Hotel,0,3,2024,May,20,16,2024-05-16,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,2,A,I,0,No Deposit,,154.0,0,Transient,39.0,0,0
HB-067054,City Hotel,1,46,2025,April,18,28,2025-04-28,0,1,1,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,0
HB-110357,City Hotel,0,84,2025,April,17,25,2025-04-25,0,2,1,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,90.09,0,1
HB-104097,City Hotel,0,306,2025,January,1,2,2025-01-02,1,3,2,1.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient-Party,92.65,0,0
HB-076139,City Hotel,1,273,2023,July,29,17,2023-07-17,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,6.0,,0,Transient-Party,101.5,0,0
HB-034152,Resort Hotel,0,159,2025,March,9,1,2025-03-01,4,10,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,96.0,,0,Transient,48.71,1,1
HB-110108,City Hotel,0,125,2025,April,16,20,2025-04-20,0,2,1,2.0,0,BB,DEU,Online TA,TA/TO,0,0,0,F,F,3,No Deposit,9.0,,0,Transient,198.0,0,0
HB-061948,City Hotel,1,538,2024,December,52,29,2024-12-29,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-096780,City Hotel,0,234,2024,September,36,5,2024-09-05,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,106.2,0,1
HB-030713,Resort Hotel,0,51,2024,November,48,26,2024-11-26,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,F,0,No Deposit,339.0,,0,Transient-Party,44.64,0,0
HB-073371,City Hotel,1,211,2025,August,34,19,2025-08-19,2,1,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,158.7,0,0
HB-024616,Resort Hotel,0,48,2024,May,21,22,2024-05-22,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,65.0,0,1
HB-110324,City Hotel,0,68,2025,April,17,21,2025-04-21,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.0,1,0
HB-012293,Resort Hotel,1,279,2025,June,25,22,2025-06-22,2,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,80.1,0,1
HB-088112,City Hotel,0,71,2024,April,17,27,2024-04-27,0,4,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.4,0,0
HB-059085,City Hotel,1,457,2024,October,43,21,2024-10-21,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,391,Transient,65.0,0,0
HB-032308,Resort Hotel,0,2,2025,January,4,21,2025-01-21,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,65.0,1,1
HB-031567,Resort Hotel,0,31,2024,December,1,30,2024-12-30,0,2,2,0.0,0,HB,PRT,Groups,Direct,0,0,0,A,C,0,No Deposit,,,0,Transient-Party,305.0,0,1
HB-031659,Resort Hotel,0,78,2025,January,1,2,2025-01-02,1,0,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,42.0,0,2
HB-112027,City Hotel,0,38,2025,May,20,14,2025-05-14,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,180.0,0,1
HB-043175,City Hotel,0,15,2023,September,37,16,2023-09-16,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,9.0,,0,Contract,115.0,0,2
HB-079055,City Hotel,0,2,2023,October,42,18,2023-10-18,2,1,2,0.0,0,BB,NLD,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,81.0,0,Transient-Party,123.0,0,0
HB-016158,Resort Hotel,0,72,2023,August,32,9,2023-08-09,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,149.0,,0,Transient,133.0,1,2
HB-070013,City Hotel,1,169,2025,June,23,8,2025-06-08,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,170.0,0,0
HB-015582,Resort Hotel,0,49,2023,July,29,23,2023-07-23,1,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,142.0,,0,Transient,92.0,0,0
HB-076959,City Hotel,1,342,2023,September,38,24,2023-09-24,2,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-024810,Resort Hotel,0,134,2024,May,22,31,2024-05-31,0,4,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,95.5,1,1
HB-061804,City Hotel,1,257,2024,December,52,26,2024-12-26,1,4,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,67.15,0,1
HB-060547,City Hotel,1,121,2024,November,46,14,2024-11-14,1,2,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,0
HB-021328,Resort Hotel,0,0,2024,February,8,22,2024-02-22,1,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,34.4,0,0
HB-059217,City Hotel,1,75,2024,October,43,22,2024-10-22,2,2,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,112.79,0,1
HB-096975,City Hotel,0,183,2024,September,36,8,2024-09-08,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,44.0,,0,Transient-Party,110.0,0,1
HB-117989,City Hotel,0,193,2025,August,32,10,2025-08-10,0,3,3,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,175.5,0,1
HB-060888,City Hotel,1,308,2024,November,48,25,2024-11-25,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,52.0,0,0
HB-025860,Resort Hotel,0,351,2025,June,26,29,2025-06-29,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,1,D,D,0,No Deposit,243.0,,0,Group,123.5,0,3
HB-092636,City Hotel,0,0,2024,July,28,9,2024-07-09,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,139.0,0,0
HB-045539,City Hotel,1,80,2023,November,44,2,2023-11-02,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,37.0,60,Transient,111.0,0,0
HB-018832,Resort Hotel,1,220,2024,July,27,4,2024-07-04,1,2,2,0.0,0,BB,PRT,Direct,Direct,0,1,0,A,A,0,No Deposit,250.0,,0,Transient,88.5,0,0
HB-080123,City Hotel,1,72,2023,December,52,27,2023-12-27,2,0,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,90.0,0,0
HB-064129,City Hotel,1,28,2025,March,9,2,2025-03-02,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,95.0,0,0
HB-087911,City Hotel,0,97,2024,April,17,25,2024-04-25,1,2,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,85.5,0,0
HB-106917,City Hotel,0,53,2025,February,9,26,2025-02-26,2,5,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,22.0,,0,Transient,108.5,0,0
HB-078367,City Hotel,1,3,2023,October,40,8,2023-10-08,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-119005,City Hotel,0,18,2025,August,35,26,2025-08-26,1,1,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,134.5,0,1
HB-110062,City Hotel,0,79,2025,April,16,18,2025-04-18,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,171.0,0,1
HB-075053,City Hotel,1,271,2023,July,28,15,2023-07-15,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-066386,City Hotel,1,68,2025,April,16,18,2025-04-18,0,4,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-069881,City Hotel,1,181,2025,June,23,8,2025-06-08,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,0,Transient,100.0,0,0
HB-099276,City Hotel,0,151,2024,October,40,6,2024-10-06,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,7.0,,0,Transient,91.48,0,2
HB-062744,City Hotel,1,13,2025,January,4,20,2025-01-20,8,20,1,0.0,0,BB,AGO,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,69.03,0,0
HB-033338,Resort Hotel,0,22,2025,February,8,17,2025-02-17,1,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,70.0,0,1
HB-013743,Resort Hotel,1,175,2025,August,35,28,2025-08-28,1,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,230.0,0,2
HB-014158,Resort Hotel,0,2,2023,December,48,2,2023-12-02,0,1,1,0.0,0,BB,,Corporate,Corporate,0,0,1,A,A,0,No Deposit,,154.0,0,Transient,25.0,0,0
HB-104170,City Hotel,0,61,2025,January,1,1,2025-01-01,2,4,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,101.43,0,1
HB-028399,Resort Hotel,0,96,2024,September,39,28,2024-09-28,0,4,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,96.0,,0,Transient-Party,78.0,0,0
HB-117128,City Hotel,0,352,2025,July,30,27,2025-07-27,0,3,2,1.0,0,BB,NLD,Online TA,TA/TO,0,0,0,B,A,2,No Deposit,9.0,,0,Transient,90.05,0,1
HB-013026,Resort Hotel,1,17,2025,July,31,28,2025-07-28,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,205.0,0,1
HB-114384,City Hotel,0,88,2025,June,25,18,2025-06-18,2,1,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,85.0,,0,Transient,151.2,0,0
HB-111162,City Hotel,0,143,2025,May,18,4,2025-05-04,0,3,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,136.67,0,1
HB-028549,Resort Hotel,0,163,2024,October,40,2,2024-10-02,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,95.0,1,2
HB-012056,Resort Hotel,1,0,2025,June,24,11,2025-06-11,1,0,1,0.0,0,BB,PRT,Complementary,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,0.0,0,0
HB-104520,City Hotel,0,1,2025,January,3,14,2025-01-14,0,1,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,179.0,0,0
HB-031455,Resort Hotel,0,191,2024,December,52,23,2024-12-23,2,4,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient-Party,39.8,0,2
HB-063006,City Hotel,1,16,2025,January,4,25,2025-01-25,4,12,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,59.5,0,0
HB-014139,Resort Hotel,0,0,2025,February,8,22,2025-02-22,0,3,1,0.0,0,BB,,Corporate,Corporate,0,0,0,A,D,1,No Deposit,,12.0,0,Transient,38.5,1,0
HB-075251,City Hotel,1,297,2023,August,32,10,2023-08-10,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-055153,City Hotel,1,113,2024,August,32,6,2024-08-06,2,1,3,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,83.0,,0,Transient,121.21,0,0
HB-093511,City Hotel,0,178,2024,July,29,20,2024-07-20,0,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,102.3,0,1
HB-038212,Resort Hotel,0,47,2025,July,28,11,2025-07-11,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,I,2,No Deposit,240.0,,0,Transient,160.0,0,0
HB-038372,Resort Hotel,0,0,2025,July,29,15,2025-07-15,0,1,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,155.0,0,0
HB-049800,City Hotel,1,103,2024,April,16,19,2024-04-19,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,0,Transient,115.0,0,0
HB-031154,Resort Hotel,0,10,2024,December,50,15,2024-12-15,0,1,1,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,43.0,0,1
HB-061305,City Hotel,1,81,2024,December,49,7,2024-12-07,0,4,2,1.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,152.55,0,1
HB-118281,City Hotel,0,108,2025,August,33,14,2025-08-14,1,3,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient-Party,155.0,0,3
HB-047976,City Hotel,1,39,2024,March,11,11,2024-03-11,1,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,0
HB-047333,City Hotel,1,44,2024,February,7,17,2024-02-17,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,44.0,,3,Transient,75.0,0,0
HB-060694,City Hotel,1,64,2024,November,47,18,2024-11-18,1,2,1,0.0,0,BB,LUX,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,86.4,0,1
HB-067968,City Hotel,1,316,2025,May,19,10,2025-05-10,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.8,0,1
HB-065454,City Hotel,1,184,2025,April,14,3,2025-04-03,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,111,Transient,105.0,0,0
HB-016586,Resort Hotel,0,94,2023,August,35,29,2023-08-29,2,3,1,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,106.21,0,1
HB-075330,City Hotel,1,311,2023,August,34,24,2023-08-24,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-096905,City Hotel,0,118,2024,September,36,3,2024-09-03,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,79.0,,0,Transient,99.28,0,0
HB-048426,City Hotel,1,45,2024,March,12,23,2024-03-23,0,2,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,92.7,0,0
HB-065001,City Hotel,1,28,2025,March,12,21,2025-03-21,0,4,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,92.18,0,0
HB-061581,City Hotel,1,43,2024,December,51,16,2024-12-16,2,3,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,82.72,0,1
HB-071505,City Hotel,1,103,2025,July,27,6,2025-07-06,2,5,2,0.0,0,SC,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,1
HB-001709,Resort Hotel,0,12,2023,September,36,10,2023-09-10,0,2,2,0.0,1,BB,PRI,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,75.46,0,2
HB-027572,Resort Hotel,0,226,2024,August,35,27,2024-08-27,2,5,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,213.43,1,0
HB-016772,Resort Hotel,1,221,2023,October,41,10,2023-10-10,1,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,208.0,,0,Transient,34.0,0,0
HB-020441,Resort Hotel,0,16,2024,January,4,27,2024-01-27,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-054833,City Hotel,1,36,2024,July,30,27,2024-07-27,1,4,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,7.0,,0,Transient,278.9,0,0
HB-097584,City Hotel,0,64,2024,September,37,15,2024-09-15,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,149.4,0,2
HB-104373,City Hotel,0,4,2025,January,2,10,2025-01-10,0,2,1,0.0,0,BB,ITA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,405.0,0,Transient-Party,70.0,0,0
HB-064346,City Hotel,1,29,2025,March,10,6,2025-03-06,1,3,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,0
HB-021069,Resort Hotel,0,1,2024,February,7,16,2024-02-16,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,330.0,,0,Transient-Party,45.0,0,0
HB-084190,City Hotel,0,16,2024,February,7,18,2024-02-18,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.0,0,0
HB-026509,Resort Hotel,0,83,2024,July,30,25,2024-07-25,3,5,2,0.0,0,BB,ITA,Groups,Corporate,0,0,0,A,A,0,No Deposit,307.0,,0,Transient-Party,144.0,0,0
HB-024387,Resort Hotel,0,14,2024,May,20,17,2024-05-17,0,2,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,G,G,1,No Deposit,240.0,,0,Transient,142.0,1,0
HB-064422,City Hotel,1,52,2025,March,10,9,2025-03-09,0,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,106.2,0,0
HB-012428,Resort Hotel,1,196,2025,June,26,29,2025-06-29,1,3,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,G,G,3,No Deposit,240.0,,0,Transient,180.0,0,0
HB-100903,City Hotel,0,36,2024,November,44,1,2024-11-01,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-026959,Resort Hotel,0,42,2024,August,32,11,2024-08-11,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,196.0,,0,Transient-Party,235.0,0,0
HB-009591,Resort Hotel,1,53,2024,December,51,17,2024-12-17,1,1,1,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,43.0,0,2
HB-094012,City Hotel,0,1,2024,July,31,29,2024-07-29,0,1,2,0.0,1,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,65.0,0,2
HB-104568,City Hotel,0,0,2025,January,3,16,2025-01-16,1,0,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,7.0,,0,Transient,67.76,0,1
HB-059740,City Hotel,1,166,2024,November,44,1,2024-11-01,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,110.0,0,0
HB-054654,City Hotel,1,65,2024,July,30,22,2024-07-22,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,64.0,0,0
HB-065426,City Hotel,1,73,2025,April,14,3,2025-04-03,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,105.0,0,0
HB-042030,City Hotel,1,12,2023,August,35,30,2023-08-30,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,90.0,0,2
HB-112637,City Hotel,0,72,2025,May,21,22,2025-05-22,1,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,136.8,0,0
HB-107830,City Hotel,0,57,2025,March,12,17,2025-03-17,0,2,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,79.2,0,0
HB-099440,City Hotel,0,180,2024,October,41,10,2024-10-10,1,2,1,0.0,0,BB,USA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,234.0,,0,Transient-Party,120.0,0,1
HB-029392,Resort Hotel,0,1,2024,October,43,26,2024-10-26,0,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,184.0,,0,Transient,96.0,1,0
HB-027975,Resort Hotel,0,115,2024,September,37,12,2024-09-12,1,3,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,125.97,0,2
HB-111240,City Hotel,0,31,2025,May,19,6,2025-05-06,1,1,2,0.0,0,BB,FRA,Corporate,Corporate,0,0,0,D,D,0,No Deposit,,450.0,0,Transient,133.0,0,0
HB-048731,City Hotel,1,51,2024,March,13,29,2024-03-29,0,1,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.9,0,0
HB-024982,Resort Hotel,0,193,2024,June,23,5,2024-06-05,2,4,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,171.0,,0,Transient,110.4,1,0
HB-087404,City Hotel,0,0,2024,April,16,18,2024-04-18,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,118.0,0,0
HB-042820,City Hotel,1,21,2023,September,36,10,2023-09-10,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,65.55,0,0
HB-002305,Resort Hotel,1,78,2023,October,41,9,2023-10-09,1,2,2,0.0,0,FB,ESP,Groups,TA/TO,0,0,0,A,A,0,Non Refund,134.0,,0,Transient,92.0,0,0
HB-021344,Resort Hotel,0,0,2024,April,15,11,2024-04-11,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,2,A,A,2,No Deposit,,384.0,0,Transient-Party,42.0,0,0
HB-047255,City Hotel,1,0,2024,February,7,13,2024-02-13,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,9.0,,0,Transient-Party,106.0,0,0
HB-110718,City Hotel,0,29,2025,April,18,29,2025-04-29,1,1,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,9.0,,0,Transient,115.0,0,0
HB-116459,City Hotel,0,234,2025,July,29,18,2025-07-18,0,3,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,156.6,0,2
HB-061891,City Hotel,1,12,2024,December,52,28,2024-12-28,0,4,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,125.8,0,1
HB-053369,City Hotel,1,91,2024,June,25,19,2024-06-19,2,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.9,0,0
HB-009854,Resort Hotel,1,10,2025,January,3,13,2025-01-13,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,44.0,0,0
HB-022843,Resort Hotel,0,48,2024,April,14,4,2024-04-04,1,4,2,0.0,0,FB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,26.0,,0,Transient,89.25,0,0
HB-101269,City Hotel,0,81,2024,November,45,6,2024-11-06,2,2,1,0.0,0,BB,DNK,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,146.6,0,1
HB-068489,City Hotel,1,85,2025,May,20,18,2025-05-18,2,5,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.14,0,1
HB-051558,City Hotel,1,35,2024,May,21,21,2024-05-21,1,1,2,0.0,0,BB,AUS,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,140.4,0,0
HB-063735,City Hotel,1,126,2025,February,8,19,2025-02-19,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.4,0,0
HB-070540,City Hotel,1,171,2025,June,25,17,2025-06-17,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,262.0,,0,Transient,89.1,0,0
HB-055907,City Hotel,1,192,2024,August,34,24,2024-08-24,0,4,2,0.0,0,SC,HUN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.25,0,0
HB-004397,Resort Hotel,1,51,2024,March,11,11,2024-03-11,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-073534,City Hotel,1,94,2025,August,35,25,2025-08-25,1,2,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,86.0,,0,Transient,127.47,0,0
HB-030817,Resort Hotel,0,80,2024,December,49,2,2024-12-02,0,2,2,0.0,0,BB,IRL,Groups,TA/TO,0,0,0,D,D,0,No Deposit,253.0,,0,Transient-Party,51.8,0,1
HB-044144,City Hotel,0,40,2023,September,39,30,2023-09-30,1,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,75.53,1,1
HB-117427,City Hotel,0,2,2025,August,31,3,2025-08-03,0,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,509.0,,0,Transient-Party,166.0,0,0
HB-097850,City Hotel,0,13,2024,September,38,20,2024-09-20,0,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,86.0,,0,Transient,119.2,0,0
HB-053513,City Hotel,1,351,2024,June,25,23,2024-06-23,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-072632,City Hotel,1,200,2025,August,31,1,2025-08-01,0,5,2,1.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,148.5,0,0
HB-001980,Resort Hotel,0,8,2023,September,39,25,2023-09-25,0,2,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,142.5,1,1
HB-081632,City Hotel,1,130,2024,April,15,13,2024-04-13,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,29.0,,10,Transient,100.0,0,0
HB-026047,Resort Hotel,0,180,2024,July,28,11,2024-07-11,3,6,3,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,C,1,No Deposit,69.0,,0,Transient,159.34,0,1
HB-065573,City Hotel,1,373,2025,April,14,5,2025-04-05,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-113491,City Hotel,0,13,2025,June,23,4,2025-06-04,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,128.0,0,1
HB-078849,City Hotel,0,29,2023,October,41,14,2023-10-14,0,4,2,2.0,0,BB,FIN,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Contract,163.58,0,1
HB-107615,City Hotel,0,34,2025,March,11,12,2025-03-12,2,2,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,72.33,0,1
HB-047578,City Hotel,1,115,2024,February,9,27,2024-02-27,2,6,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,134.0,,0,Transient-Party,64.75,0,0
HB-023326,Resort Hotel,0,54,2024,April,16,17,2024-04-17,2,3,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,8.0,,0,Transient,44.3,0,0
HB-037103,Resort Hotel,0,59,2025,June,23,3,2025-06-03,2,2,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,241.0,,0,Transient,152.0,0,1
HB-021803,Resort Hotel,0,45,2024,March,10,7,2024-03-07,1,4,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,171.0,,0,Transient,35.15,0,0
HB-027891,Resort Hotel,0,71,2024,September,37,12,2024-09-12,1,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,H,H,1,No Deposit,240.0,,0,Transient,167.0,1,1
HB-084759,City Hotel,0,4,2024,February,9,28,2024-02-28,2,2,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,133.0,0,2
HB-032558,Resort Hotel,0,56,2025,January,3,16,2025-01-16,4,10,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,171.0,,0,Transient,60.0,0,0
HB-103003,City Hotel,0,24,2024,December,49,7,2024-12-07,0,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,9.0,,0,Transient,96.9,0,2
HB-002468,Resort Hotel,0,47,2023,October,42,18,2023-10-18,2,5,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,241.0,,0,Transient,67.92,0,1
HB-022890,Resort Hotel,0,80,2024,April,14,7,2024-04-07,0,3,2,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,67.0,,0,Transient-Party,68.0,0,0
HB-037185,Resort Hotel,0,0,2025,June,24,9,2025-06-09,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,127.0,0,0
HB-052154,City Hotel,1,113,2024,May,22,31,2024-05-31,0,3,1,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,A,0,Non Refund,,202.0,0,Transient,100.0,0,0
HB-016740,Resort Hotel,0,1,2023,September,36,9,2023-09-09,0,1,1,0.0,0,BB,PRT,Corporate,Direct,0,0,0,A,A,0,No Deposit,,195.0,0,Transient-Party,134.0,0,0
HB-116462,City Hotel,0,20,2025,July,29,17,2025-07-17,1,3,2,0.0,0,BB,EST,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,123.2,0,0
HB-100277,City Hotel,0,108,2024,October,43,25,2024-10-25,0,1,2,1.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,7.0,,0,Transient,69.99,0,2
HB-089494,City Hotel,0,189,2024,May,20,19,2024-05-19,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,65.0,0,1
HB-091753,City Hotel,0,192,2024,June,26,24,2024-06-24,0,2,1,0.0,0,BB,SRB,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,34.0,,0,Transient-Party,95.0,0,0
HB-086960,City Hotel,0,89,2024,April,15,9,2024-04-09,2,1,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,9.0,,0,Transient-Party,162.3,0,0
HB-111727,City Hotel,0,80,2025,May,19,11,2025-05-11,1,3,2,0.0,0,SC,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,121.5,0,0
HB-068186,City Hotel,1,218,2025,May,20,15,2025-05-15,1,1,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,0
HB-098802,City Hotel,0,31,2024,October,40,2,2024-10-02,2,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,89.0,,0,Transient,104.64,0,0
HB-002991,Resort Hotel,0,50,2023,November,45,10,2023-11-10,0,2,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,156.0,,0,Transient,55.04,0,0
HB-018063,Resort Hotel,0,155,2023,October,44,31,2023-10-31,0,1,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,36.0,0,0
HB-101416,City Hotel,0,92,2024,November,46,11,2024-11-11,0,1,2,0.0,0,BB,THA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,364.0,,0,Transient-Party,90.0,0,0
HB-100943,City Hotel,0,43,2024,November,44,1,2024-11-01,0,3,1,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.07,0,1
HB-066229,City Hotel,1,54,2025,April,16,15,2025-04-15,2,2,3,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,200.7,0,0
HB-087101,City Hotel,0,76,2024,April,15,12,2024-04-12,0,2,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,96.3,0,1
HB-086678,City Hotel,0,55,2024,April,14,6,2024-04-06,0,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,56.0,,0,Transient-Party,104.0,0,0
HB-100930,City Hotel,0,66,2024,October,44,31,2024-10-31,1,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,104.85,0,1
HB-030358,Resort Hotel,0,7,2024,November,46,16,2024-11-16,0,4,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,177.0,,0,Transient,48.25,0,3
HB-090146,City Hotel,0,136,2024,May,22,29,2024-05-29,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,117.29,1,1
HB-040463,City Hotel,0,19,2023,July,30,25,2023-07-25,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-104272,City Hotel,0,46,2025,January,2,7,2025-01-07,2,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,102.6,0,2
HB-094371,City Hotel,0,122,2024,July,30,28,2024-07-28,2,5,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,140.27,0,0
HB-112307,City Hotel,0,1,2025,May,21,22,2025-05-22,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,144.0,0,0
HB-083134,City Hotel,0,1,2024,January,3,20,2024-01-20,0,1,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,111.0,1,1
HB-075807,City Hotel,1,330,2023,September,37,12,2023-09-12,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-088535,City Hotel,0,7,2024,May,18,5,2024-05-05,0,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,144.0,0,0
HB-108846,City Hotel,0,75,2025,March,14,31,2025-03-31,0,2,1,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.1,0,1
HB-117605,City Hotel,0,206,2025,August,31,3,2025-08-03,1,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,144.0,0,0
HB-071322,City Hotel,1,45,2025,July,27,2,2025-07-02,2,0,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.1,0,1
HB-080563,City Hotel,0,54,2023,November,46,18,2023-11-18,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,1
HB-060170,City Hotel,1,277,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-056286,City Hotel,1,241,2024,September,36,2,2024-09-02,2,2,2,0.0,0,BB,AUS,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,101.79,0,1
HB-097413,City Hotel,0,1,2024,September,37,15,2024-09-15,0,1,2,0.0,0,BB,PRT,Online TA,Corporate,0,0,0,A,B,1,No Deposit,,120.0,0,Transient,169.0,0,1
HB-109452,City Hotel,0,91,2025,April,15,9,2025-04-09,2,1,3,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,166.5,0,0
HB-077243,City Hotel,1,6,2023,September,38,20,2023-09-20,2,0,2,0.0,0,BB,PRT,Corporate,Corporate,0,1,0,A,A,0,No Deposit,78.0,,0,Transient,0.0,0,0
HB-078512,City Hotel,0,2,2025,June,26,28,2025-06-28,0,1,1,0.0,0,BB,JPN,Corporate,Corporate,1,0,2,A,A,0,No Deposit,,358.0,0,Transient,140.8,0,0
HB-094354,City Hotel,0,2,2024,August,31,2,2024-08-02,0,1,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,121.0,0,2
HB-076324,City Hotel,0,137,2023,July,28,11,2023-07-11,2,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,86.0,0,0
HB-010350,Resort Hotel,1,49,2025,February,9,28,2025-02-28,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,332.0,,0,Transient,35.0,0,0
HB-062260,City Hotel,1,356,2025,January,2,6,2025-01-06,1,2,1,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,0
HB-036428,Resort Hotel,0,13,2025,May,20,14,2025-05-14,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,68.4,0,1
HB-105121,City Hotel,0,4,2025,January,5,28,2025-01-28,1,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,108.0,0,0
HB-107885,City Hotel,0,21,2025,March,11,16,2025-03-16,1,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,78.0,0,0
HB-096002,City Hotel,0,159,2024,August,35,26,2024-08-26,0,1,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,9.0,,0,Transient,85.5,0,0
HB-117097,City Hotel,0,84,2025,July,30,26,2025-07-26,0,4,2,0.0,0,SC,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,1
HB-078286,City Hotel,0,1,2024,September,36,6,2024-09-06,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,3,A,A,0,No Deposit,,40.0,0,Transient,67.0,1,0
HB-035089,Resort Hotel,0,211,2025,April,14,6,2025-04-06,2,5,2,1.0,0,BB,GBR,Direct,Direct,0,0,0,G,G,0,No Deposit,250.0,,0,Transient,107.83,0,0
HB-013002,Resort Hotel,1,165,2025,July,30,27,2025-07-27,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,160.0,0,1
HB-007256,Resort Hotel,1,161,2024,July,31,30,2024-07-30,4,8,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,172.0,0,2
HB-068557,City Hotel,1,175,2025,May,21,19,2025-05-19,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,44.0,,0,Transient,90.0,0,0
HB-032249,Resort Hotel,0,1,2025,January,3,17,2025-01-17,0,2,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,66.0,0,0
HB-025490,Resort Hotel,0,157,2024,June,25,23,2024-06-23,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,243.0,,0,Contract,53.85,0,1
HB-019945,Resort Hotel,0,5,2024,January,2,9,2024-01-09,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,240.0,,0,Transient,39.0,0,1
HB-028980,Resort Hotel,0,231,2024,October,41,8,2024-10-08,3,6,2,0.0,0,SC,GBR,Groups,Direct,0,0,0,D,I,0,No Deposit,273.0,,0,Transient-Party,1.56,0,0
HB-045169,City Hotel,0,47,2023,October,42,20,2023-10-20,0,4,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Contract,94.5,0,2
HB-027541,Resort Hotel,0,221,2024,August,35,26,2024-08-26,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,314.0,,0,Transient,87.43,0,0
HB-019401,Resort Hotel,0,0,2023,December,50,17,2023-12-17,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,E,0,No Deposit,,144.0,0,Transient,25.0,0,0
HB-047560,City Hotel,1,0,2024,February,9,27,2024-02-27,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,60.0,0,0
HB-102084,City Hotel,0,58,2024,November,47,20,2024-11-20,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,1
HB-029249,Resort Hotel,0,36,2024,October,42,20,2024-10-20,1,3,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,6.0,0,0
HB-070360,City Hotel,1,150,2025,June,24,15,2025-06-15,1,3,3,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,168.75,0,0
HB-028633,Resort Hotel,0,60,2024,October,40,3,2024-10-03,1,4,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient-Party,79.0,0,1
HB-035888,Resort Hotel,0,41,2025,April,18,30,2025-04-30,2,2,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,95.0,0,0
HB-060572,City Hotel,1,39,2024,November,46,15,2024-11-15,2,5,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,1
HB-016334,Resort Hotel,0,45,2023,August,34,21,2023-08-21,1,2,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,153.0,0,1
HB-090859,City Hotel,0,3,2024,June,24,10,2024-06-10,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,90.67,0,0
HB-085001,City Hotel,0,33,2024,March,10,5,2024-03-05,1,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,83.9,0,0
HB-096602,City Hotel,0,226,2024,September,35,1,2024-09-01,1,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,27.0,,0,Transient-Party,80.75,0,1
HB-066113,City Hotel,1,321,2025,April,16,14,2025-04-14,1,2,2,0.0,0,BB,HUN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.8,0,1
HB-107425,City Hotel,0,2,2025,March,11,11,2025-03-11,1,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,128.0,0,0
HB-080644,City Hotel,0,32,2023,November,47,20,2023-11-20,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,119.0,,0,Transient-Party,73.0,0,0
HB-080946,City Hotel,0,0,2023,November,48,27,2023-11-27,0,2,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,51.3,0,0
HB-011760,Resort Hotel,1,222,2025,May,22,28,2025-05-28,2,3,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,77.22,0,0
HB-070799,City Hotel,1,126,2025,June,26,23,2025-06-23,0,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,0
HB-030086,Resort Hotel,0,20,2024,November,45,9,2024-11-09,1,4,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,D,E,0,No Deposit,6.0,,0,Transient,43.0,1,0
HB-083854,City Hotel,0,2,2024,February,7,13,2024-02-13,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,102.0,1,1
HB-106710,City Hotel,0,154,2025,March,9,1,2025-03-01,0,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.6,0,2
HB-100025,City Hotel,0,81,2024,October,42,16,2024-10-16,2,4,1,0.0,0,BB,ROU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,16.0,,0,Transient,76.5,0,0
HB-043284,City Hotel,0,162,2023,September,37,17,2023-09-17,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,70.0,0,0
HB-089653,City Hotel,0,0,2024,May,21,23,2024-05-23,1,0,1,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,34.0,,0,Transient-Party,115.0,0,1
HB-113613,City Hotel,0,42,2025,June,23,8,2025-06-08,0,2,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,128.7,0,0
HB-065481,City Hotel,1,112,2025,April,14,4,2025-04-04,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,B,1,Non Refund,,385.0,0,Transient,95.0,0,0
HB-113941,City Hotel,0,25,2025,June,24,11,2025-06-11,2,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,111.2,0,1
HB-083020,City Hotel,0,13,2024,January,2,11,2024-01-11,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,82.0,0,0
HB-067749,City Hotel,1,162,2025,May,19,6,2025-05-06,2,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,80.0,0,0
HB-024708,Resort Hotel,0,0,2024,May,22,29,2024-05-29,2,0,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,306.0,,0,Transient,42.51,1,0
HB-049780,City Hotel,1,103,2024,April,16,19,2024-04-19,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,0,Transient,115.0,0,0
HB-082555,City Hotel,0,89,2023,December,52,30,2023-12-30,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,79.82,0,0
HB-009359,Resort Hotel,1,28,2024,November,46,17,2024-11-17,2,5,1,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,43.0,0,0
HB-105711,City Hotel,0,17,2025,February,7,11,2025-02-11,2,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-076616,City Hotel,0,138,2023,July,30,25,2023-07-25,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,60.0,0,0
HB-041244,City Hotel,0,39,2023,August,33,14,2023-08-14,0,2,1,0.0,0,HB,USA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,87.0,0,0
HB-044790,City Hotel,0,60,2023,October,41,12,2023-10-12,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,3.0,,0,Transient-Party,65.0,0,1
HB-067258,City Hotel,1,118,2025,April,18,30,2025-04-30,2,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,137.25,0,1
HB-103515,City Hotel,0,89,2024,December,51,22,2024-12-22,2,3,2,2.0,0,BB,USA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,11.0,,0,Transient,94.72,0,0
HB-115203,City Hotel,0,147,2025,June,26,27,2025-06-27,1,5,2,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,122.7,0,1
HB-005791,Resort Hotel,1,190,2024,May,20,14,2024-05-14,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,79.2,0,2
HB-055160,City Hotel,1,66,2024,August,32,6,2024-08-06,2,2,3,0.0,0,BB,GEO,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,168.3,0,0
HB-084867,City Hotel,0,49,2024,March,9,2,2024-03-02,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,89.3,0,1
HB-052875,City Hotel,1,71,2024,June,24,14,2024-06-14,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,120.0,0,0
HB-026955,Resort Hotel,0,133,2024,August,31,4,2024-08-04,3,8,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient-Party,216.66,0,0
HB-013366,Resort Hotel,1,224,2025,August,33,12,2025-08-12,2,3,2,2.0,0,HB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,303.2,0,2
HB-000175,Resort Hotel,0,66,2023,July,27,6,2023-07-06,1,3,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,E,0,No Deposit,175.0,,0,Transient,91.5,0,0
HB-117928,City Hotel,0,3,2025,August,32,9,2025-08-09,0,3,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,230.0,0,1
HB-014888,Resort Hotel,1,265,2023,September,38,24,2023-09-24,1,3,2,0.0,0,HB,BEL,Groups,Corporate,0,14,0,A,A,0,Non Refund,183.0,,0,Transient,89.2,0,0
HB-029547,Resort Hotel,0,92,2024,October,43,27,2024-10-27,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient-Party,74.0,0,2
HB-060375,City Hotel,1,76,2024,November,45,7,2024-11-07,1,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,189.0,0,1
HB-026287,Resort Hotel,0,0,2024,July,30,26,2024-07-26,0,1,3,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,241.0,0,1
HB-072097,City Hotel,1,176,2025,July,29,20,2025-07-20,2,6,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,124.65,0,0
HB-025771,Resort Hotel,0,2,2024,July,28,9,2024-07-09,0,1,2,2.0,0,BB,PRT,Direct,Direct,0,0,0,H,H,0,No Deposit,250.0,419.0,0,Transient,246.0,0,0
HB-050686,City Hotel,0,130,2024,May,18,5,2024-05-05,0,3,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient-Party,104.4,0,1
HB-049253,City Hotel,1,104,2024,April,15,8,2024-04-08,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,90.95,0,0
HB-118010,City Hotel,0,20,2025,August,32,8,2025-08-08,0,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,180.0,0,1
HB-096007,City Hotel,0,40,2024,August,34,23,2024-08-23,0,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,149.4,0,0
HB-112886,City Hotel,0,183,2025,May,22,28,2025-05-28,2,0,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,139.5,0,1
HB-055303,City Hotel,1,405,2024,August,32,10,2024-08-10,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,65.0,0,0
HB-079681,City Hotel,0,37,2023,October,43,29,2023-10-29,1,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Transient,71.25,0,0
HB-108167,City Hotel,0,15,2025,March,12,23,2025-03-23,0,1,1,0.0,0,BB,DEU,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,93.0,0,0
HB-031430,Resort Hotel,0,185,2024,December,51,18,2024-12-18,4,7,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,339.0,,0,Transient,32.24,0,0
HB-012209,Resort Hotel,1,50,2025,June,25,18,2025-06-18,2,0,1,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,212.0,0,1
HB-039208,Resort Hotel,0,2,2025,August,32,10,2025-08-10,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,205.0,0,1
HB-106714,City Hotel,0,63,2025,February,9,26,2025-02-26,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,99.03,0,0
HB-077222,City Hotel,0,327,2023,September,36,9,2023-09-09,2,4,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,21.0,,0,Transient-Party,76.0,0,0
HB-039910,Resort Hotel,0,21,2025,August,35,30,2025-08-30,0,2,2,1.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,G,1,No Deposit,241.0,,0,Transient,186.0,0,2
HB-095983,City Hotel,0,129,2024,August,34,25,2024-08-25,0,2,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,128.7,0,0
HB-018243,Resort Hotel,0,35,2023,November,45,6,2023-11-06,2,7,1,0.0,0,BB,AUT,Corporate,Corporate,0,0,0,A,A,1,No Deposit,185.0,281.0,0,Transient-Party,36.0,0,0
HB-062733,City Hotel,1,4,2025,January,4,20,2025-01-20,1,2,3,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,158.0,0,0
HB-118423,City Hotel,0,156,2025,August,34,19,2025-08-19,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,130.5,0,2
HB-079632,City Hotel,0,5,2023,October,43,28,2023-10-28,0,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Contract,136.0,0,1
HB-102028,City Hotel,0,11,2024,November,47,19,2024-11-19,2,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.67,0,2
HB-114152,City Hotel,0,218,2025,June,24,15,2025-06-15,0,3,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,180.5,0,2
HB-084277,City Hotel,0,4,2024,February,8,19,2024-02-19,1,2,2,0.0,0,BB,LUX,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,76.8,0,0
HB-091349,City Hotel,0,27,2024,June,25,18,2024-06-18,1,1,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,177.0,0,1
HB-113848,City Hotel,0,29,2025,June,23,6,2025-06-06,2,5,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,170.0,0,1
HB-071583,City Hotel,1,182,2025,July,28,8,2025-07-08,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,82.47,0,1
HB-042074,City Hotel,1,104,2023,August,35,30,2023-08-30,2,1,2,0.0,0,HB,ESP,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,90.0,0,0
HB-107494,City Hotel,0,24,2025,March,11,12,2025-03-12,1,0,2,0.0,0,BB,CHN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,80.0,0,1
HB-040284,City Hotel,0,12,2023,July,29,18,2023-07-18,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-053825,City Hotel,1,17,2024,June,26,30,2024-06-30,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,151.0,0,1
HB-036285,Resort Hotel,0,10,2025,May,19,10,2025-05-10,1,4,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,94.0,1,0
HB-069810,City Hotel,1,134,2025,June,23,7,2025-06-07,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,110.0,0,0
HB-040695,City Hotel,0,135,2023,August,31,5,2023-08-05,0,3,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,B,D,2,No Deposit,14.0,,0,Transient-Party,76.5,0,3
HB-098576,City Hotel,0,328,2024,September,40,30,2024-09-30,0,2,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,38,Transient-Party,65.0,0,1
HB-073073,City Hotel,1,116,2025,August,33,13,2025-08-13,2,5,2,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,183.0,0,2
HB-083882,City Hotel,0,3,2024,February,7,12,2024-02-12,0,2,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,81.0,0,1
HB-053787,City Hotel,1,358,2024,June,26,30,2024-06-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-007115,Resort Hotel,1,34,2024,July,30,22,2024-07-22,0,2,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,211.0,0,0
HB-008531,Resort Hotel,1,149,2024,October,40,4,2024-10-04,0,5,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,69.0,0,0
HB-026970,Resort Hotel,0,24,2024,August,33,14,2024-08-14,2,0,3,0.0,1,BB,CN,Online TA,TA/TO,0,0,0,G,G,1,No Deposit,242.0,,0,Transient,299.0,0,0
HB-027203,Resort Hotel,0,23,2024,August,34,20,2024-08-20,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,231.0,0,2
HB-116596,City Hotel,0,136,2025,July,29,19,2025-07-19,0,3,2,1.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,174.0,0,3
HB-000423,Resort Hotel,0,57,2023,July,28,15,2023-07-15,0,2,2,0.0,0,FB,PRT,Groups,Direct,0,0,0,A,C,0,No Deposit,305.0,,0,Transient-Party,98.75,0,0
HB-069610,City Hotel,1,212,2025,June,23,2,2025-06-02,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,20.0,,0,Transient-Party,105.0,0,0
HB-028146,Resort Hotel,0,237,2024,September,37,15,2024-09-15,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Contract,62.9,0,0
HB-073176,City Hotel,1,13,2025,August,33,16,2025-08-16,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,160.0,0,0
HB-087199,City Hotel,0,1,2024,April,16,15,2024-04-15,0,1,2,0.0,0,SC,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,98.0,1,0
HB-086517,City Hotel,0,122,2024,April,14,2,2024-04-02,2,1,2,0.0,0,HB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,110.24,0,0
HB-104732,City Hotel,0,29,2025,January,3,18,2025-01-18,0,3,1,0.0,0,BB,FIN,Groups,TA/TO,0,0,0,A,A,0,No Deposit,171.0,,0,Transient-Party,65.0,0,0
HB-006927,Resort Hotel,1,24,2024,July,28,12,2024-07-12,0,3,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,159.0,0,0
HB-087589,City Hotel,0,29,2024,April,16,18,2024-04-18,1,3,2,1.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,163.46,0,2
HB-096738,City Hotel,0,14,2024,September,36,5,2024-09-05,1,1,1,0.0,1,SC,SVK,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,129.0,0,1
HB-021349,Resort Hotel,0,0,2024,April,15,11,2024-04-11,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,3,A,A,1,No Deposit,,384.0,0,Transient-Party,42.0,0,1
HB-054554,City Hotel,1,384,2024,July,29,20,2024-07-20,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,65.0,0,0
HB-094561,City Hotel,0,175,2024,August,31,2,2024-08-02,0,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,99.45,0,1
HB-113567,City Hotel,0,33,2025,June,23,6,2025-06-06,0,3,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,129.0,0,1
HB-101237,City Hotel,0,4,2024,November,45,8,2024-11-08,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,D,D,0,No Deposit,,219.0,0,Transient,94.0,0,0
HB-058280,City Hotel,1,76,2024,October,41,10,2024-10-10,1,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,234.0,,0,Transient-Party,120.0,0,0
HB-061763,City Hotel,1,80,2024,December,52,26,2024-12-26,1,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,102.6,0,0
HB-047613,City Hotel,1,1,2024,February,9,28,2024-02-28,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,60.0,0,0
HB-070515,City Hotel,1,150,2025,June,25,17,2025-06-17,2,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,120.0,0,0
HB-034160,Resort Hotel,0,56,2025,March,11,12,2025-03-12,2,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,62.0,1,1
HB-002242,Resort Hotel,0,21,2023,October,40,7,2023-10-07,0,2,1,0.0,0,BB,IRL,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,47.0,0,1
HB-026672,Resort Hotel,0,9,2024,August,32,5,2024-08-05,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,215.67,0,0
HB-010942,Resort Hotel,1,50,2025,April,15,12,2025-04-12,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,90.0,0,0
HB-039220,Resort Hotel,0,218,2025,August,32,5,2025-08-05,2,5,2,0.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,171.0,,0,Transient,135.9,0,1
HB-000094,Resort Hotel,0,109,2023,July,27,3,2023-07-03,0,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,123.0,0,2
HB-043186,City Hotel,0,27,2023,September,37,16,2023-09-16,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,2,No Deposit,40.0,,0,Transient,65.0,0,0
HB-065593,City Hotel,1,117,2025,April,14,5,2025-04-05,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,170.0,,0,Transient,93.5,0,0
HB-071312,City Hotel,1,38,2025,July,27,2,2025-07-02,2,0,1,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,149.0,0,1
HB-090901,City Hotel,0,137,2024,June,24,10,2024-06-10,1,2,2,0.0,0,BB,CHE,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,135.0,0,1
HB-068593,City Hotel,1,105,2025,May,21,19,2025-05-19,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-014157,Resort Hotel,0,8,2025,June,25,22,2025-06-22,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,3,A,D,0,No Deposit,,154.0,0,Transient,75.0,0,0
HB-083422,City Hotel,0,5,2024,January,3,15,2024-01-15,5,12,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,88.12,0,1
HB-078888,City Hotel,1,5,2023,October,42,19,2023-10-19,1,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,D,D,0,No Deposit,9.0,,0,Contract,136.0,0,2
HB-021752,Resort Hotel,0,31,2024,March,10,7,2024-03-07,1,1,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,95.0,,0,Transient,25.0,0,0
HB-091975,City Hotel,0,4,2024,June,26,26,2024-06-26,2,0,1,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,113.0,0,1
HB-102598,City Hotel,0,34,2024,November,48,27,2024-11-27,2,3,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,D,1,No Deposit,,,0,Transient-Party,75.0,0,0
HB-081358,City Hotel,0,11,2023,December,49,5,2023-12-05,2,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,104.0,0,0
HB-009770,Resort Hotel,1,42,2024,December,1,31,2024-12-31,1,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,G,G,0,No Deposit,,,0,Transient-Party,275.0,0,0
HB-050843,City Hotel,1,14,2024,May,19,9,2024-05-09,3,10,1,0.0,0,BB,AGO,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,170.85,0,0
HB-063829,City Hotel,1,594,2025,February,8,23,2025-02-23,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-054607,City Hotel,1,379,2024,July,29,21,2024-07-21,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-107395,City Hotel,0,35,2025,March,10,7,2025-03-07,0,5,2,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,52.0,,0,Transient,68.0,0,1
HB-046898,City Hotel,1,33,2024,January,4,25,2024-01-25,1,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,38.0,,15,Transient-Party,62.0,0,0
HB-037529,Resort Hotel,0,121,2025,June,24,12,2025-06-12,3,6,2,2.0,0,BB,IRL,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,180.0,0,4
HB-011591,Resort Hotel,1,300,2025,May,21,19,2025-05-19,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,67.5,0,0
HB-094032,City Hotel,0,20,2024,July,30,25,2024-07-25,1,4,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,159.0,0,1
HB-032856,Resort Hotel,0,0,2025,February,6,6,2025-02-06,1,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,2,No Deposit,,,0,Transient,47.0,1,0
HB-030336,Resort Hotel,0,14,2024,November,47,18,2024-11-18,0,2,1,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,36.0,1,1
HB-032605,Resort Hotel,0,43,2025,January,5,27,2025-01-27,1,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient-Party,48.0,0,1
HB-038929,Resort Hotel,0,181,2025,July,31,31,2025-07-31,1,2,3,0.0,0,HB,POL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,315.0,,0,Contract,175.58,0,0
HB-040327,City Hotel,0,20,2023,July,29,22,2023-07-22,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-039687,Resort Hotel,0,146,2025,August,34,19,2025-08-19,2,5,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient-Party,237.71,0,1
HB-045801,City Hotel,1,98,2023,November,47,23,2023-11-23,1,2,1,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,D,0,No Deposit,37.0,,0,Transient-Party,70.0,0,0
HB-011126,Resort Hotel,0,108,2025,April,17,21,2025-04-21,4,7,2,0.0,0,BB,PRT,Online TA,Direct,0,0,0,E,E,2,No Deposit,,,0,Transient,85.0,0,5
HB-074594,City Hotel,1,353,2023,October,40,5,2023-10-05,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-090355,City Hotel,0,146,2024,June,23,3,2024-06-03,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,9.0,,0,Transient-Party,106.2,0,1
HB-009432,Resort Hotel,1,101,2024,November,48,26,2024-11-26,2,5,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,37.8,0,0
HB-038511,Resort Hotel,0,82,2025,July,29,14,2025-07-14,2,4,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,209.33,0,1
HB-081652,City Hotel,0,83,2023,December,50,17,2023-12-17,0,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,0.0,0,1
HB-047051,City Hotel,0,55,2024,February,6,5,2024-02-05,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,59.28,0,1
HB-091109,City Hotel,0,28,2024,June,24,14,2024-06-14,0,3,1,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,108.42,0,1
HB-062455,City Hotel,1,38,2025,January,3,14,2025-01-14,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,Non Refund,,67.0,0,Transient,75.0,0,0
HB-053823,City Hotel,1,43,2024,June,26,30,2024-06-30,0,3,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,150.3,0,0
HB-076477,City Hotel,1,379,2023,October,44,31,2023-10-31,1,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-102739,City Hotel,0,36,2024,December,48,1,2024-12-01,2,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,68.07,0,1
HB-102402,City Hotel,0,131,2024,November,48,25,2024-11-25,0,2,1,0.0,0,BB,NLD,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,79.2,0,0
HB-033432,Resort Hotel,0,1,2025,February,8,22,2025-02-22,0,1,1,0.0,0,BB,ESP,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,61.2,0,0
HB-008669,Resort Hotel,1,131,2024,October,41,9,2024-10-09,2,0,2,0.0,0,BB,PRT,Groups,Corporate,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,55.0,0,0
HB-030249,Resort Hotel,0,14,2024,November,46,17,2024-11-17,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient,30.0,0,0
HB-111007,City Hotel,0,207,2025,May,18,2,2025-05-02,0,3,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,2
HB-058790,City Hotel,1,164,2024,October,42,16,2024-10-16,1,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,34.0,,0,Transient,115.0,0,0
HB-042834,City Hotel,1,87,2023,September,37,11,2023-09-11,0,2,2,0.0,0,BB,FRA,Groups,Corporate,0,0,0,A,D,0,Non Refund,,,0,Transient,100.0,0,0
HB-044926,City Hotel,1,100,2023,October,42,16,2023-10-16,0,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient,108.0,0,0
HB-101478,City Hotel,0,47,2024,November,45,10,2024-11-10,0,3,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,130.33,0,1
HB-115603,City Hotel,0,9,2025,July,27,6,2025-07-06,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,189.0,0,2
HB-075298,City Hotel,1,304,2023,August,33,17,2023-08-17,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-026814,Resort Hotel,0,7,2024,August,32,11,2024-08-11,0,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,231.0,1,0
HB-108054,City Hotel,0,151,2025,March,12,20,2025-03-20,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,95.0,0,0
HB-057279,City Hotel,1,143,2024,September,38,22,2024-09-22,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,129.6,0,0
HB-111481,City Hotel,0,6,2025,May,19,9,2025-05-09,0,2,1,0.0,0,BB,FRA,Direct,Direct,0,0,0,D,D,1,No Deposit,,,0,Transient,157.0,0,0
HB-042049,City Hotel,1,104,2023,August,35,30,2023-08-30,2,1,2,0.0,0,HB,ESP,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,90.0,0,0
HB-091062,City Hotel,0,155,2024,June,24,14,2024-06-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,119.24,1,0
HB-115567,City Hotel,0,214,2025,July,27,3,2025-07-03,1,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient-Party,89.1,0,1
HB-006207,Resort Hotel,0,225,2024,May,22,28,2024-05-28,1,1,1,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,F,1,No Deposit,298.0,,0,Transient-Party,54.5,0,0
HB-075598,City Hotel,0,257,2023,July,26,1,2023-07-01,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,101.5,0,0
HB-029657,Resort Hotel,0,40,2024,October,44,31,2024-10-31,1,2,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,52.4,0,0
HB-086299,City Hotel,0,2,2024,March,13,27,2024-03-27,2,2,3,0.0,0,BB,IRN,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,9.0,,0,Transient,147.0,0,2
HB-098265,City Hotel,0,36,2024,September,39,25,2024-09-25,2,0,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,90.09,0,1
HB-025917,Resort Hotel,0,23,2024,July,28,10,2024-07-10,2,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,171.0,1,1
HB-045621,City Hotel,0,80,2023,November,46,14,2023-11-14,2,1,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,65.45,0,1
HB-000281,Resort Hotel,1,100,2023,July,28,11,2023-07-11,2,3,2,1.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,149.0,,0,Transient,153.96,0,0
HB-108893,City Hotel,0,51,2025,March,14,31,2025-03-31,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,128.4,0,1
HB-064361,City Hotel,1,189,2025,March,10,7,2025-03-07,0,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,6,No Deposit,9.0,,0,Transient,91.8,0,1
HB-043201,City Hotel,0,37,2023,September,37,16,2023-09-16,0,2,1,0.0,0,BB,NZL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient-Party,85.5,1,0
HB-063944,City Hotel,1,134,2025,February,9,25,2025-02-25,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,75.0,0,0
HB-032820,Resort Hotel,0,36,2025,February,6,3,2025-02-03,1,2,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,240.0,,0,Transient,48.0,0,1
HB-073085,City Hotel,1,27,2025,August,33,14,2025-08-14,1,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,189.0,0,0
HB-087393,City Hotel,0,29,2024,April,16,18,2024-04-18,1,0,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,101.0,0,1
HB-103268,City Hotel,0,8,2024,December,51,16,2024-12-16,0,2,1,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,86.0,,0,Transient,54.4,0,0
HB-017831,Resort Hotel,0,292,2023,October,42,21,2023-10-21,0,2,1,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,208.0,,0,Transient-Party,60.0,0,0
HB-013126,Resort Hotel,1,334,2025,August,31,1,2025-08-01,1,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,156.6,0,0
HB-090389,City Hotel,0,7,2024,June,23,3,2024-06-03,1,2,2,0.0,0,BB,HRV,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,134.33,0,1
HB-030245,Resort Hotel,0,12,2024,November,48,27,2024-11-27,4,8,1,0.0,0,BB,PRT,Corporate,Direct,0,0,1,A,A,0,No Deposit,154.0,,0,Transient,27.0,0,0
HB-097004,City Hotel,0,125,2024,September,36,7,2024-09-07,0,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,136.0,0,2
HB-051786,City Hotel,1,323,2024,May,21,26,2024-05-26,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,59.0,0,0
HB-086902,City Hotel,0,159,2024,April,15,9,2024-04-09,1,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,70.0,0,1
HB-117644,City Hotel,0,151,2025,August,32,4,2025-08-04,1,2,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,125.0,0,0
HB-029459,Resort Hotel,0,7,2024,October,43,24,2024-10-24,1,4,2,1.0,1,HB,PRT,Online TA,TA/TO,0,0,0,A,C,2,No Deposit,240.0,,0,Transient-Party,119.0,0,3
HB-035805,Resort Hotel,0,100,2025,April,18,29,2025-04-29,2,1,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,385.0,,0,Transient-Party,83.0,0,1
HB-009120,Resort Hotel,1,79,2024,October,44,28,2024-10-28,1,2,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,98.0,0,0
HB-034505,Resort Hotel,0,12,2025,March,13,25,2025-03-25,1,1,2,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,D,1,No Deposit,,,0,Transient,0.0,0,0
HB-114729,City Hotel,0,396,2025,June,26,25,2025-06-25,2,0,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,95.5,0,1
HB-058067,City Hotel,1,191,2024,October,40,5,2024-10-05,1,4,2,0.0,0,SC,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.1,0,0
HB-030751,Resort Hotel,0,1,2024,November,48,29,2024-11-29,0,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,51.4,0,1
HB-106765,City Hotel,0,1,2025,March,9,2,2025-03-02,0,1,1,0.0,0,SC,BRA,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,88.0,0,0
HB-037462,Resort Hotel,0,174,2025,June,24,14,2025-06-14,0,4,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,124.0,1,0
HB-031205,Resort Hotel,0,6,2024,December,51,16,2024-12-16,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient-Party,48.0,0,1
HB-015590,Resort Hotel,0,67,2023,July,29,20,2023-07-20,2,5,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,120.43,1,1
HB-117375,City Hotel,0,315,2025,July,31,31,2025-07-31,1,2,3,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,139.5,0,2
HB-016367,Resort Hotel,1,0,2023,August,34,26,2023-08-26,0,1,2,1.0,0,BB,PRT,Direct,Direct,1,0,0,C,C,0,No Deposit,,,0,Transient,183.0,0,0
HB-108552,City Hotel,0,10,2025,March,13,27,2025-03-27,1,1,2,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,95.0,0,1
HB-016994,Resort Hotel,0,239,2023,September,38,19,2023-09-19,1,1,1,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,E,0,No Deposit,248.0,,0,Transient-Party,0.0,0,0
HB-061106,City Hotel,1,15,2024,December,49,2,2024-12-02,0,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,117.5,0,1
HB-059887,City Hotel,1,304,2024,November,44,3,2024-11-03,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,89.0,0,0
HB-062142,City Hotel,1,335,2025,January,1,2,2025-01-02,1,4,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,109.65,0,0
HB-099544,City Hotel,0,23,2024,October,41,7,2024-10-07,2,5,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,94.0,0,0
HB-115843,City Hotel,0,114,2025,July,28,8,2025-07-08,2,2,3,1.0,0,BB,SAU,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,7.0,,0,Transient,221.49,0,2
HB-100820,City Hotel,0,228,2024,October,44,30,2024-10-30,2,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,87.9,0,0
HB-085000,City Hotel,0,57,2024,March,10,4,2024-03-04,1,2,2,0.0,0,BB,ESP,Groups,Corporate,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,70.0,0,0
HB-055725,City Hotel,1,303,2024,August,34,19,2024-08-19,2,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,78.0,0,0
HB-101349,City Hotel,0,34,2024,November,45,6,2024-11-06,2,3,1,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,161.5,0,1
HB-031447,Resort Hotel,0,51,2024,December,52,26,2024-12-26,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,70.33,1,2
HB-017648,Resort Hotel,0,58,2023,October,42,18,2023-10-18,2,2,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,E,0,No Deposit,240.0,,0,Transient,56.0,0,2
HB-118921,City Hotel,0,131,2025,August,35,25,2025-08-25,0,2,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,244.0,0,0
HB-009864,Resort Hotel,1,87,2025,January,3,14,2025-01-14,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,33.6,0,0
HB-039527,Resort Hotel,0,2,2025,August,34,19,2025-08-19,0,1,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,241.0,,0,Transient,201.14,1,1
HB-046145,City Hotel,0,8,2023,December,50,16,2023-12-16,0,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,77.6,0,0
HB-083977,City Hotel,0,17,2024,September,39,26,2024-09-26,1,1,1,0.0,0,BB,FRA,Corporate,Corporate,1,0,2,A,D,0,No Deposit,91.0,,0,Transient,95.0,0,0
HB-017444,Resort Hotel,0,221,2023,October,41,10,2023-10-10,1,1,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,208.0,,0,Transient-Party,64.0,0,0
HB-041612,City Hotel,0,2,2023,August,33,19,2023-08-19,0,2,1,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,D,1,No Deposit,,45.0,0,Transient,0.0,0,0
HB-097140,City Hotel,0,10,2024,September,37,12,2024-09-12,1,0,1,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,87.01,0,1
HB-119385,City Hotel,0,21,2025,August,35,30,2025-08-30,2,5,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,394.0,,0,Transient,96.14,0,2
HB-008355,Resort Hotel,1,36,2024,September,39,23,2024-09-23,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,131.75,0,2
HB-108051,City Hotel,0,151,2025,March,12,20,2025-03-20,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,95.0,0,0
HB-108331,City Hotel,0,116,2025,March,13,24,2025-03-24,0,2,1,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,1,No Deposit,171.0,,0,Transient-Party,90.0,0,0
HB-101409,City Hotel,0,7,2024,November,45,8,2024-11-08,0,4,2,0.0,0,SC,UKR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,106.36,0,1
HB-014748,Resort Hotel,1,259,2023,September,37,17,2023-09-17,0,3,1,0.0,0,BB,GBR,Groups,Corporate,0,1,0,A,A,0,Non Refund,,223.0,0,Transient,33.3,0,0
HB-000578,Resort Hotel,1,60,2023,July,29,20,2023-07-20,1,4,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,195.0,0,0
HB-055191,City Hotel,1,195,2024,August,32,7,2024-08-07,2,1,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,146.7,0,2
HB-072881,City Hotel,1,180,2025,August,32,8,2025-08-08,2,6,2,0.0,0,HB,AUT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,223.0,0,1
HB-090120,City Hotel,0,87,2024,May,22,29,2024-05-29,2,2,0,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient,112.01,0,1
HB-079411,City Hotel,1,137,2024,January,4,27,2024-01-27,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,29.0,,45,Transient,70.0,0,0
HB-039813,Resort Hotel,0,204,2025,August,35,26,2025-08-26,2,1,2,1.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,15.0,,0,Transient-Party,168.6,0,2
HB-071198,City Hotel,1,71,2025,June,26,29,2025-06-29,0,3,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,0
HB-109996,City Hotel,0,32,2025,April,16,17,2025-04-17,1,2,2,2.0,0,HB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,7.0,,0,Transient,228.76,0,1
HB-049440,City Hotel,1,281,2024,April,15,14,2024-04-14,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,59.0,0,0
HB-096335,City Hotel,0,141,2024,August,35,29,2024-08-29,1,2,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.5,0,2
HB-020654,Resort Hotel,0,13,2024,February,6,5,2024-02-05,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,240.0,,0,Transient,59.0,1,1
HB-097182,City Hotel,0,5,2024,September,37,12,2024-09-12,1,0,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,139.0,0,0
HB-032147,Resort Hotel,0,40,2025,January,3,16,2025-01-16,1,2,1,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,A,D,1,No Deposit,,,0,Transient-Party,55.0,0,0
HB-038423,Resort Hotel,0,3,2025,July,27,6,2025-07-06,3,8,2,0.0,0,SC,CHE,Direct,Direct,0,0,0,F,I,8,No Deposit,,,0,Transient,0.0,0,2
HB-101747,City Hotel,0,2,2024,November,46,14,2024-11-14,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.35,0,1
HB-008747,Resort Hotel,0,364,2024,October,41,12,2024-10-12,0,4,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,D,0,No Deposit,,223.0,0,Transient-Party,66.0,0,0
HB-106100,City Hotel,0,44,2025,February,8,17,2025-02-17,2,2,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,149.6,0,0
HB-033729,Resort Hotel,0,6,2025,February,9,26,2025-02-26,2,2,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,2,No Deposit,250.0,,0,Transient-Party,51.25,0,0
HB-084051,City Hotel,0,2,2024,March,11,16,2024-03-16,0,2,1,0.0,0,BB,PRT,Aviation,TA/TO,1,0,1,A,A,0,No Deposit,,153.0,0,Transient,88.0,1,0
HB-018526,Resort Hotel,0,26,2023,November,47,21,2023-11-21,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,G,0,No Deposit,240.0,,0,Transient,54.0,1,1
HB-110097,City Hotel,0,79,2025,April,16,19,2025-04-19,0,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,162.0,0,1
HB-063541,City Hotel,1,8,2025,February,7,13,2025-02-13,1,3,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,138.55,0,0
HB-082002,City Hotel,1,115,2024,March,12,20,2024-03-20,2,0,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,41.0,,22,Transient,70.0,0,0
HB-030337,Resort Hotel,0,14,2024,November,47,18,2024-11-18,0,2,1,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,30.0,0,1
HB-031137,Resort Hotel,0,0,2024,December,50,15,2024-12-15,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,44.0,0,0
HB-046810,City Hotel,0,151,2024,January,3,19,2024-01-19,0,2,1,0.0,0,BB,NOR,Offline TA/TO,TA/TO,0,0,0,A,B,2,No Deposit,19.0,,63,Transient-Party,71.0,0,0
HB-099595,City Hotel,0,53,2024,October,42,14,2024-10-14,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,77.0,,0,Transient-Party,120.0,0,0
HB-027603,Resort Hotel,0,1,2024,September,36,2,2024-09-02,0,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,161.0,1,1
HB-082188,City Hotel,1,99,2024,February,8,19,2024-02-19,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,1,0,A,A,0,No Deposit,,67.0,0,Transient-Party,80.0,0,0
HB-119200,City Hotel,0,213,2025,August,35,28,2025-08-28,1,3,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,19.0,,0,Transient-Party,104.0,0,0
HB-013635,Resort Hotel,1,111,2025,August,34,24,2025-08-24,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,230.0,0,1
HB-014887,Resort Hotel,1,265,2023,September,38,24,2023-09-24,1,3,2,0.0,0,HB,BEL,Groups,Corporate,0,14,0,A,A,0,Non Refund,183.0,,0,Transient,89.2,0,0
HB-074584,City Hotel,1,353,2023,October,40,5,2023-10-05,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-067061,City Hotel,1,28,2025,April,18,28,2025-04-28,0,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,115.0,0,1
HB-049643,City Hotel,0,108,2024,April,16,16,2024-04-16,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient,75.76,0,0
HB-116105,City Hotel,0,293,2025,July,28,8,2025-07-08,2,5,2,0.0,0,BB,DNK,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,4
HB-072701,City Hotel,1,211,2025,August,31,3,2025-08-03,1,3,3,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,115.63,0,0
HB-072076,City Hotel,1,264,2025,July,29,20,2025-07-20,0,2,3,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,156.6,0,0
HB-094811,City Hotel,0,139,2024,August,32,7,2024-08-07,2,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,123.3,0,1
HB-008550,Resort Hotel,0,383,2024,October,40,6,2024-10-06,0,3,1,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,E,1,No Deposit,315.0,,0,Transient-Party,50.0,0,0
HB-017557,Resort Hotel,0,204,2023,October,40,7,2023-10-07,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,26.0,,0,Contract,55.46,1,0
HB-036587,Resort Hotel,0,117,2025,May,20,15,2025-05-15,3,7,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Transient,57.85,1,0
HB-064222,City Hotel,1,203,2025,March,9,2,2025-03-02,0,3,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,60.98,0,1
HB-016738,Resort Hotel,0,153,2023,September,35,3,2023-09-03,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,E,0,No Deposit,243.0,,0,Contract,77.58,0,0
HB-024038,Resort Hotel,0,0,2024,May,19,10,2024-05-10,0,1,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,C,0,No Deposit,,,0,Transient,79.0,1,0
HB-010423,Resort Hotel,1,312,2025,March,10,5,2025-03-05,2,5,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,30.0,0,0
HB-010778,Resort Hotel,1,10,2025,April,14,3,2025-04-03,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,Non Refund,,135.0,0,Transient,45.0,0,0
HB-005900,Resort Hotel,0,213,2024,May,20,16,2024-05-16,1,1,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,85.0,0,0
HB-105356,City Hotel,0,35,2025,February,5,2,2025-02-02,0,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,132.0,,0,Transient,72.0,0,0
HB-052930,City Hotel,1,71,2024,June,24,14,2024-06-14,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,120.0,0,0
HB-103930,City Hotel,0,207,2024,December,1,30,2024-12-30,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,104.0,,0,Transient,95.0,0,0
HB-089380,City Hotel,0,1,2024,May,21,20,2024-05-20,0,1,2,0.0,0,BB,USA,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,206.0,1,0
HB-027262,Resort Hotel,0,4,2024,August,34,25,2024-08-25,0,0,2,0.0,0,BB,CHE,Direct,Direct,0,0,0,D,D,2,No Deposit,250.0,,0,Transient,0.0,0,1
HB-040771,City Hotel,0,36,2023,August,32,7,2023-08-07,0,2,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-027935,Resort Hotel,0,15,2024,September,37,10,2024-09-10,2,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,C,0,No Deposit,250.0,,0,Transient,112.5,0,0
HB-055774,City Hotel,1,152,2024,August,34,20,2024-08-20,2,5,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,91.93,0,0
HB-023406,Resort Hotel,0,44,2024,April,17,23,2024-04-23,1,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,,0,Transient,80.0,0,0
HB-070777,City Hotel,1,195,2025,June,25,22,2025-06-22,1,3,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,10.0,,0,Transient,99.0,0,0
HB-029763,Resort Hotel,0,36,2024,October,44,29,2024-10-29,2,5,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,46.69,0,1
HB-042348,City Hotel,0,15,2023,September,36,5,2023-09-05,1,1,1,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,73.15,0,1
HB-112020,City Hotel,0,25,2025,May,20,16,2025-05-16,0,3,1,0.0,0,BB,RUS,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,474.0,,0,Transient-Party,130.0,0,0
HB-060968,City Hotel,1,11,2024,November,48,27,2024-11-27,2,5,1,0.0,0,SC,AGO,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,90.0,0,0
HB-039626,Resort Hotel,0,199,2025,August,34,19,2025-08-19,2,3,2,0.0,0,BB,AUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,125.2,0,1
HB-088229,City Hotel,0,35,2024,April,18,30,2024-04-30,2,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,140.4,0,1
HB-052287,City Hotel,1,118,2024,June,22,2,2024-06-02,0,3,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,116.1,0,0
HB-048967,City Hotel,0,104,2024,April,14,3,2024-04-03,2,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,82.45,0,1
HB-049420,City Hotel,1,99,2024,April,15,13,2024-04-13,0,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.3,0,1
HB-117546,City Hotel,0,65,2025,July,31,29,2025-07-29,2,6,2,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,184.0,0,1
HB-057882,City Hotel,1,10,2024,October,40,2,2024-10-02,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,85.0,,0,Transient,107.0,0,0
HB-087602,City Hotel,0,5,2024,April,15,11,2024-04-11,3,8,1,0.0,0,BB,FRA,Aviation,Corporate,0,0,0,A,A,0,No Deposit,153.0,,0,Transient,95.0,0,0
HB-020327,Resort Hotel,0,1,2024,January,4,23,2024-01-23,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,56.0,0,1
HB-111947,City Hotel,0,82,2025,May,19,10,2025-05-10,2,6,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,146.25,0,1
HB-042886,City Hotel,1,168,2023,September,37,11,2023-09-11,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,60.0,0,0
HB-075380,City Hotel,1,313,2023,August,34,26,2023-08-26,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-025144,Resort Hotel,0,5,2025,March,10,8,2025-03-08,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,10,A,D,0,No Deposit,,154.0,0,Transient,35.0,0,0
HB-071292,City Hotel,1,202,2025,July,27,1,2025-07-01,2,1,2,0.0,0,SC,AUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,0
HB-023256,Resort Hotel,0,32,2024,April,16,19,2024-04-19,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,E,0,No Deposit,,397.0,0,Transient-Party,50.0,0,0
HB-022769,Resort Hotel,0,28,2024,April,14,5,2024-04-05,0,0,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,C,1,No Deposit,115.0,,0,Transient,0.0,0,0
HB-069567,City Hotel,1,189,2025,June,23,2,2025-06-02,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-034130,Resort Hotel,0,112,2025,March,11,13,2025-03-13,1,0,2,0.0,0,BB,CHN,Groups,TA/TO,0,0,0,E,E,0,No Deposit,66.0,,0,Transient-Party,50.0,0,0
HB-089920,City Hotel,0,2,2024,May,22,29,2024-05-29,0,0,2,0.0,0,SC,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,0.0,0,1
HB-044751,City Hotel,0,79,2023,October,41,10,2023-10-10,1,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,0.0,0,0
HB-083372,City Hotel,0,5,2024,June,22,1,2024-06-01,0,1,2,0.0,0,BB,PRT,Direct,Direct,1,0,1,D,D,0,No Deposit,,,0,Transient,80.0,1,2
HB-001605,Resort Hotel,1,323,2023,September,36,5,2023-09-05,4,6,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,175.0,,0,Transient-Party,97.5,0,1
HB-041665,City Hotel,0,2,2023,August,34,21,2023-08-21,0,2,1,0.0,0,BB,AGO,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,75.0,0,0
HB-102424,City Hotel,0,19,2024,November,47,24,2024-11-24,1,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,2
HB-082782,City Hotel,1,68,2024,February,7,17,2024-02-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,37.0,,0,Transient,75.0,0,0
HB-103567,City Hotel,0,15,2024,December,52,27,2024-12-27,0,1,1,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,220.0,,0,Transient-Party,60.0,0,0
HB-075131,City Hotel,1,276,2023,July,29,20,2023-07-20,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-034057,Resort Hotel,0,171,2025,March,10,5,2025-03-05,2,5,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,E,E,0,No Deposit,298.0,,0,Transient-Party,73.0,0,0
HB-005467,Resort Hotel,1,87,2024,April,18,29,2024-04-29,2,5,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,D,D,0,Non Refund,71.0,,0,Transient,58.0,0,0
HB-034671,Resort Hotel,0,9,2025,March,13,30,2025-03-30,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,60.0,0,1
HB-110523,City Hotel,0,123,2025,April,17,24,2025-04-24,1,3,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,105.75,0,1
HB-033216,Resort Hotel,0,245,2025,February,7,12,2025-02-12,2,3,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,,0,Transient,55.8,0,0
HB-080524,City Hotel,0,22,2023,November,46,17,2023-11-17,0,1,1,0.0,0,BB,AUT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,127.0,0,Transient-Party,62.0,0,0
HB-018721,Resort Hotel,0,3,2023,November,48,27,2023-11-27,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient,35.0,1,1
HB-024488,Resort Hotel,0,36,2024,May,20,18,2024-05-18,1,4,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient,89.0,1,1
HB-021486,Resort Hotel,0,29,2024,February,9,26,2024-02-26,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,29.0,0,1
HB-115017,City Hotel,0,163,2025,June,26,28,2025-06-28,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,89.1,0,0
HB-026381,Resort Hotel,0,38,2024,July,30,24,2024-07-24,2,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,194.0,0,1
HB-044649,City Hotel,0,80,2023,October,41,9,2023-10-09,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,A,0,No Deposit,12.0,,50,Transient-Party,136.0,0,0
HB-046269,City Hotel,0,118,2023,December,52,28,2023-12-28,1,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,110.8,0,2
HB-061927,City Hotel,1,16,2024,December,52,28,2024-12-28,2,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,76.67,0,0
HB-069353,City Hotel,1,186,2025,May,22,30,2025-05-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,130.0,0,0
HB-065893,City Hotel,1,76,2025,April,15,9,2025-04-09,2,3,2,0.0,0,BB,NOR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,100.8,0,0
HB-068713,City Hotel,1,75,2025,May,21,20,2025-05-20,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,90.0,0,0
HB-024634,Resort Hotel,0,124,2024,May,21,21,2024-05-21,2,5,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,175.0,,0,Transient,54.56,0,0
HB-102138,City Hotel,0,65,2024,November,47,19,2024-11-19,2,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,159.0,,0,Transient,63.58,0,0
HB-026353,Resort Hotel,0,262,2024,July,30,25,2024-07-25,1,4,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,250.0,,0,Transient,146.0,1,1
HB-076476,City Hotel,1,379,2023,October,44,31,2023-10-31,1,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-080968,City Hotel,1,40,2024,January,1,6,2024-01-06,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,D,D,0,No Deposit,3.0,,0,Transient,60.0,0,1
HB-079419,City Hotel,1,137,2024,January,4,27,2024-01-27,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,29.0,,45,Transient,70.0,0,0
HB-081426,City Hotel,0,0,2024,April,16,20,2024-04-20,0,1,2,0.0,0,FB,PRT,Complementary,Direct,1,0,2,G,F,1,No Deposit,,45.0,0,Transient,0.0,0,1
HB-081052,City Hotel,1,86,2024,January,4,22,2024-01-22,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,29.0,,35,Transient,75.0,0,0
HB-078112,City Hotel,0,1,2023,October,40,2,2023-10-02,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,19.0,,0,Transient-Party,100.0,0,0
HB-091306,City Hotel,0,45,2024,June,25,17,2024-06-17,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,65.0,0,1
HB-061492,City Hotel,1,524,2024,December,50,15,2024-12-15,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-031031,Resort Hotel,0,6,2024,December,50,10,2024-12-10,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient-Party,65.0,0,1
HB-090051,City Hotel,0,2,2024,September,38,21,2024-09-21,0,1,1,0.0,0,BB,PRT,Complementary,Corporate,1,0,1,G,G,0,No Deposit,,45.0,0,Transient,0.0,0,0
HB-072471,City Hotel,1,41,2025,July,31,29,2025-07-29,1,1,2,0.0,0,SC,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,1
HB-020623,Resort Hotel,0,0,2024,February,5,4,2024-02-04,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,127.0,,0,Transient,30.5,1,0
HB-034874,Resort Hotel,0,33,2025,April,14,6,2025-04-06,0,2,2,0.0,0,BB,CHE,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,77.0,1,0
HB-108301,City Hotel,0,116,2025,March,13,24,2025-03-24,0,2,1,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,1,No Deposit,171.0,,0,Transient-Party,90.0,0,0
HB-055791,City Hotel,1,38,2024,August,34,21,2024-08-21,2,0,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,92.86,0,0
HB-000813,Resort Hotel,0,75,2023,July,30,30,2023-07-30,2,7,2,0.0,0,BB,CHE,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,36.0,,0,Transient-Party,125.89,0,1
HB-048101,City Hotel,0,99,2024,March,11,17,2024-03-17,0,2,2,0.0,0,SC,KWT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,67.5,0,0
HB-056795,City Hotel,1,41,2024,September,37,14,2024-09-14,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,86.0,,0,Transient-Party,130.0,0,0
HB-030202,Resort Hotel,0,52,2024,November,46,12,2024-11-12,2,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,6.0,,0,Transient,29.0,0,0
HB-007381,Resort Hotel,1,357,2024,August,32,6,2024-08-06,2,5,2,1.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,176.0,0,3
HB-024747,Resort Hotel,0,127,2024,May,21,25,2024-05-25,2,6,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,52.5,0,2
HB-066723,City Hotel,1,73,2025,April,17,23,2025-04-23,2,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,117.0,0,0
HB-051716,City Hotel,1,158,2024,May,21,24,2024-05-24,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,31,Transient,130.0,0,0
HB-041305,City Hotel,1,39,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,101.5,0,0
HB-103498,City Hotel,0,18,2024,December,52,23,2024-12-23,1,2,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,191.0,1,1
HB-051942,City Hotel,0,316,2024,May,21,26,2024-05-26,0,3,2,0.0,0,BB,AUT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,110.0,0,0
HB-003998,Resort Hotel,1,112,2024,February,7,12,2024-02-12,0,2,2,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,68.0,0,0
HB-093709,City Hotel,0,132,2024,July,29,19,2024-07-19,1,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,72.25,0,0
HB-062364,City Hotel,1,552,2025,January,2,12,2025-01-12,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,59.0,0,0
HB-116855,City Hotel,0,145,2025,July,30,24,2025-07-24,1,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.5,0,1
HB-056682,City Hotel,1,24,2024,September,37,9,2024-09-09,2,2,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,136.5,0,0
HB-072111,City Hotel,1,9,2025,July,30,21,2025-07-21,0,2,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,95.2,0,1
HB-038234,Resort Hotel,0,182,2025,July,28,12,2025-07-12,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,2,No Deposit,,,0,Transient-Party,0.0,1,1
HB-016972,Resort Hotel,0,258,2023,September,37,17,2023-09-17,0,2,2,0.0,0,HB,FRA,Groups,TA/TO,0,0,0,A,C,1,No Deposit,245.0,,0,Transient-Party,78.3,0,1
HB-013334,Resort Hotel,1,95,2025,August,32,10,2025-08-10,2,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,230.0,0,1
HB-008552,Resort Hotel,0,383,2024,October,40,6,2024-10-06,0,3,1,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,1,No Deposit,315.0,,0,Transient-Party,48.0,0,0
HB-038982,Resort Hotel,0,9,2025,August,31,2,2025-08-02,0,3,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,0,No Deposit,250.0,,0,Transient,254.67,0,1
HB-048794,City Hotel,0,88,2024,March,13,30,2024-03-30,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,82.45,0,1
HB-003105,Resort Hotel,0,16,2023,November,46,18,2023-11-18,0,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,36.0,1,0
HB-111680,City Hotel,0,13,2025,May,20,12,2025-05-12,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,210.0,0,1
HB-021899,Resort Hotel,0,1,2024,March,11,12,2024-03-12,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,240.0,,0,Transient,58.0,0,0
HB-101148,City Hotel,0,21,2024,November,45,6,2024-11-06,1,0,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,100.0,0,2
HB-077883,City Hotel,0,16,2023,September,39,25,2023-09-25,2,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,170.0,0,0
HB-021438,Resort Hotel,0,2,2024,February,9,27,2024-02-27,1,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,F,0,No Deposit,,,0,Transient,60.0,0,0
HB-090123,City Hotel,0,14,2024,May,22,31,2024-05-31,0,2,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,80.08,0,0
HB-029874,Resort Hotel,0,45,2024,November,45,5,2024-11-05,2,1,2,1.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,6.0,,0,Transient,36.5,0,0
HB-020386,Resort Hotel,0,0,2024,January,4,26,2024-01-26,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,154.0,0,Transient,27.0,0,0
HB-030840,Resort Hotel,0,24,2024,December,49,3,2024-12-03,2,1,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,60.0,0,2
HB-085530,City Hotel,0,58,2024,March,11,14,2024-03-14,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,78.3,0,1
HB-022235,Resort Hotel,0,22,2025,January,1,4,2025-01-04,0,4,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,1,0,0,A,C,0,No Deposit,171.0,,0,Transient,34.0,0,2
HB-037682,Resort Hotel,0,319,2025,June,25,16,2025-06-16,3,7,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,240.0,,0,Transient,88.74,0,1
HB-097364,City Hotel,0,221,2024,September,37,12,2024-09-12,1,3,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.65,0,1
HB-011106,Resort Hotel,1,174,2025,April,16,19,2025-04-19,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,54.0,0,1
HB-073608,City Hotel,1,36,2025,August,35,27,2025-08-27,2,1,3,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,223.0,0,1
HB-083990,City Hotel,0,10,2024,February,7,13,2024-02-13,2,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-058782,City Hotel,1,286,2024,October,42,16,2024-10-16,1,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,44.0,,0,Transient,90.0,0,0
HB-074395,City Hotel,1,290,2023,August,31,3,2023-08-03,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-116724,City Hotel,0,423,2025,July,30,22,2025-07-22,1,1,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,95.5,0,0
HB-111921,City Hotel,0,26,2025,May,20,17,2025-05-17,0,1,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,474.0,,0,Transient-Party,130.0,0,0
HB-040155,City Hotel,1,96,2023,July,28,11,2023-07-11,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-064720,City Hotel,1,92,2025,March,11,15,2025-03-15,0,3,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,85.0,0,0
HB-043080,City Hotel,0,135,2023,September,37,14,2023-09-14,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,90.0,0,0
HB-046428,City Hotel,0,19,2024,January,1,1,2024-01-01,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,81.82,0,1
HB-105846,City Hotel,0,9,2025,February,7,14,2025-02-14,0,2,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.0,0,0
HB-033949,Resort Hotel,0,0,2025,March,10,5,2025-03-05,2,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,70.0,0,0
HB-102476,City Hotel,0,60,2024,November,48,25,2024-11-25,2,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-034800,Resort Hotel,0,20,2025,March,13,28,2025-03-28,2,6,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,436.0,,0,Transient,100.0,0,1
HB-062574,City Hotel,1,6,2025,January,3,15,2025-01-15,2,3,1,0.0,0,BB,CHE,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,76.3,0,0
HB-080994,City Hotel,0,12,2023,November,48,29,2023-11-29,2,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,B,B,0,No Deposit,14.0,,0,Transient,74.42,0,1
HB-033124,Resort Hotel,0,7,2025,March,12,20,2025-03-20,1,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,1,0,1,A,D,0,No Deposit,146.0,,0,Group,35.0,0,0
HB-062917,City Hotel,1,61,2025,January,4,25,2025-01-25,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,326.0,,0,Transient,80.0,0,0
HB-104718,City Hotel,0,14,2025,January,3,18,2025-01-18,0,3,1,0.0,0,BB,BGR,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,124.0,0,1
HB-084124,City Hotel,0,8,2024,February,8,19,2024-02-19,0,1,1,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,E,1,No Deposit,,67.0,0,Transient-Party,81.0,0,0
HB-101001,City Hotel,0,64,2024,November,44,1,2024-11-01,0,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.6,0,2
HB-053993,City Hotel,1,105,2024,July,27,4,2024-07-04,1,4,2,1.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,123.25,0,0
HB-085231,City Hotel,0,8,2024,March,10,9,2024-03-09,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,138.0,,0,Transient,64.4,0,0
HB-052913,City Hotel,1,11,2024,June,24,14,2024-06-14,0,3,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,D,D,0,Non Refund,,51.0,0,Transient,90.0,0,0
HB-031624,Resort Hotel,0,66,2024,December,1,31,2024-12-31,1,1,1,1.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,175.5,0,1
HB-020718,Resort Hotel,0,4,2024,February,6,5,2024-02-05,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,64.0,1,0
HB-023434,Resort Hotel,0,28,2024,April,17,24,2024-04-24,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,65.0,0,1
HB-061567,City Hotel,1,185,2024,December,51,16,2024-12-16,1,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,0
HB-099232,City Hotel,0,186,2024,October,40,6,2024-10-06,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,79.66,0,1
HB-004873,Resort Hotel,1,116,2024,April,14,4,2024-04-04,2,5,2,0.0,0,HB,GBR,Groups,Direct,0,0,0,D,D,0,Non Refund,273.0,,0,Transient,72.0,0,0
HB-078319,City Hotel,0,0,2024,July,29,19,2024-07-19,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,3,12,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-079470,City Hotel,1,1,2023,October,43,28,2023-10-28,0,3,2,0.0,0,HB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,37.0,,0,Transient-Party,111.0,0,0
HB-099897,City Hotel,0,27,2024,October,42,17,2024-10-17,1,2,2,0.0,0,HB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,177.0,0,2
HB-077424,City Hotel,1,19,2023,October,40,6,2023-10-06,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,1,1,0,A,A,0,No Deposit,82.0,,0,Transient-Party,80.0,0,0
HB-054357,City Hotel,1,372,2024,July,28,14,2024-07-14,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-060522,City Hotel,1,17,2024,November,46,13,2024-11-13,2,1,2,0.0,0,SC,KOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,1
HB-099360,City Hotel,0,181,2024,October,41,11,2024-10-11,0,2,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,234.0,,0,Transient-Party,120.0,0,0
HB-010481,Resort Hotel,1,86,2025,March,10,9,2025-03-09,0,3,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,67.0,,0,Transient,46.0,0,0
HB-067477,City Hotel,1,199,2025,May,18,4,2025-05-04,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,56.0,,56,Transient,120.0,0,0
HB-036308,Resort Hotel,0,0,2025,May,20,15,2025-05-15,1,0,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,85.0,0,1
HB-078745,City Hotel,0,14,2023,October,41,15,2023-10-15,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,99.0,,0,Transient-Party,100.0,0,0
HB-078803,City Hotel,0,14,2023,October,41,15,2023-10-15,0,2,1,0.0,0,BB,DZA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,99.0,,0,Transient-Party,100.0,0,0
HB-063782,City Hotel,1,28,2025,February,8,20,2025-02-20,1,3,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,103.7,0,4
HB-055539,City Hotel,1,48,2024,August,33,15,2024-08-15,1,4,3,0.0,0,BB,MAR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,168.3,0,3
HB-094392,City Hotel,0,4,2025,June,23,2,2025-06-02,0,1,2,0.0,0,BB,PRT,Complementary,Direct,1,4,13,F,D,0,No Deposit,,45.0,0,Transient,0.0,0,3
HB-098957,City Hotel,0,127,2024,October,40,2,2024-10-02,2,3,3,0.0,0,BB,AUS,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,7.0,,0,Transient,146.92,0,1
HB-043953,City Hotel,1,88,2023,September,39,26,2023-09-26,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-033508,Resort Hotel,0,17,2025,February,8,20,2025-02-20,1,4,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,242.0,,0,Transient,104.8,0,1
HB-059582,City Hotel,1,18,2024,October,44,29,2024-10-29,2,1,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,1
HB-014776,Resort Hotel,1,195,2023,August,31,4,2023-08-04,0,5,2,0.0,0,HB,PRT,Direct,Direct,0,2,0,E,E,0,No Deposit,,,0,Transient,186.0,0,2
HB-066515,City Hotel,1,91,2025,April,17,21,2025-04-21,1,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-069735,City Hotel,1,111,2025,June,23,5,2025-06-05,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient,89.1,0,0
HB-051214,City Hotel,1,451,2024,May,20,16,2024-05-16,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-096876,City Hotel,0,109,2024,September,36,7,2024-09-07,0,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,129.6,0,1
HB-017102,Resort Hotel,0,262,2023,September,38,21,2023-09-21,1,3,2,0.0,0,HB,BEL,Groups,Corporate,0,0,0,A,A,0,No Deposit,183.0,,0,Transient-Party,89.2,0,0
HB-095674,City Hotel,0,14,2024,August,34,20,2024-08-20,1,1,1,2.0,0,BB,NLD,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,135.65,1,2
HB-112813,City Hotel,0,246,2025,May,22,27,2025-05-27,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,128.0,0,1
HB-052940,City Hotel,1,71,2024,June,24,14,2024-06-14,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,120.0,0,0
HB-093727,City Hotel,0,110,2024,July,30,22,2024-07-22,2,2,2,0.0,0,BB,KAZ,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,121.05,0,0
HB-117877,City Hotel,0,168,2025,August,32,7,2025-08-07,1,3,1,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,99.18,0,1
HB-085643,City Hotel,0,11,2024,March,11,16,2024-03-16,0,3,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,B,B,1,No Deposit,138.0,,0,Transient-Party,31.0,0,0
HB-037425,Resort Hotel,0,150,2025,June,23,3,2025-06-03,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,58.7,0,1
HB-103113,City Hotel,0,123,2024,December,50,9,2024-12-09,1,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,90.0,0,2
HB-097103,City Hotel,0,147,2024,September,36,8,2024-09-08,1,3,2,1.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,111.19,0,2
HB-041009,City Hotel,1,0,2023,August,32,10,2023-08-10,1,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,75.0,0,2
HB-022755,Resort Hotel,0,0,2024,April,14,4,2024-04-04,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,56.0,0,1
HB-018124,Resort Hotel,0,14,2023,November,44,3,2023-11-03,0,3,2,0.0,0,HB,BEL,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,240.0,,0,Transient,78.0,0,1
HB-028930,Resort Hotel,0,364,2024,October,41,12,2024-10-12,0,4,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,2,No Deposit,,223.0,0,Transient-Party,72.0,1,0
HB-038037,Resort Hotel,0,288,2025,July,27,3,2025-07-03,1,4,2,0.0,1,BB,PRT,Online TA,TA/TO,0,0,0,A,D,2,No Deposit,240.0,,0,Transient,115.68,1,3
HB-019878,Resort Hotel,0,12,2024,January,1,7,2024-01-07,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,48.0,0,2
HB-090857,City Hotel,0,57,2024,June,24,10,2024-06-10,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,90.67,0,1
HB-034235,Resort Hotel,0,112,2025,March,11,15,2025-03-15,0,3,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,477.0,0,Transient-Party,40.0,0,0
HB-112883,City Hotel,0,183,2025,May,22,28,2025-05-28,2,0,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,108.0,0,1
HB-106767,City Hotel,0,1,2025,March,9,2,2025-03-02,0,1,1,0.0,0,SC,BRA,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,88.0,0,0
HB-045332,City Hotel,1,60,2023,October,43,25,2023-10-25,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,89.25,0,2
HB-086979,City Hotel,0,81,2024,April,15,10,2024-04-10,2,0,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.5,0,1
HB-001577,Resort Hotel,0,73,2023,September,36,4,2023-09-04,2,7,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,G,G,1,No Deposit,240.0,,0,Transient,153.0,0,0
HB-041189,City Hotel,0,39,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-039569,Resort Hotel,0,104,2025,August,33,17,2025-08-17,2,3,3,1.0,0,HB,ESP,Online TA,TA/TO,0,0,0,H,H,2,No Deposit,240.0,,0,Transient,402.0,0,1
HB-096075,City Hotel,0,172,2024,August,34,25,2024-08-25,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,109.8,0,0
HB-079267,City Hotel,1,28,2023,October,43,29,2023-10-29,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,98.0,,0,Transient-Party,130.0,0,0
HB-003454,Resort Hotel,0,29,2023,December,49,10,2023-12-10,0,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,115.0,,0,Transient-Party,26.1,0,0
HB-083215,City Hotel,0,34,2024,January,4,24,2024-01-24,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,66.0,0,0
HB-035820,Resort Hotel,0,3,2025,April,18,29,2025-04-29,2,1,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,C,0,No Deposit,250.0,,0,Transient,97.0,1,0
HB-024503,Resort Hotel,0,129,2024,May,21,21,2024-05-21,2,1,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,177.0,,0,Transient,41.4,0,0
HB-090601,City Hotel,0,1,2024,June,23,8,2024-06-08,0,1,2,1.0,0,BB,CN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.0,0,2
HB-086700,City Hotel,0,55,2024,April,14,6,2024-04-06,0,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,104.0,0,0
HB-096531,City Hotel,0,66,2024,September,35,1,2024-09-01,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,132.9,0,1
HB-059734,City Hotel,1,166,2024,November,44,1,2024-11-01,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,110.0,0,0
HB-069485,City Hotel,1,174,2025,June,22,1,2025-06-01,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,0,Transient,100.0,0,0
HB-021395,Resort Hotel,0,23,2024,February,9,26,2024-02-26,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,58.0,0,1
HB-061028,City Hotel,1,8,2024,November,48,30,2024-11-30,0,2,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,90.0,0,1
HB-058593,City Hotel,1,37,2024,October,41,13,2024-10-13,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,105.0,0,0
HB-005205,Resort Hotel,1,57,2024,April,17,22,2024-04-22,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,95.0,0,0
HB-097217,City Hotel,0,61,2024,September,36,7,2024-09-07,2,5,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,207.64,1,1
HB-079241,City Hotel,1,444,2024,December,48,1,2024-12-01,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,34.0,,39,Transient,75.0,0,0
HB-024347,Resort Hotel,0,99,2024,May,20,15,2024-05-15,2,1,2,0.0,1,BB,IRL,Online TA,TA/TO,0,0,0,A,C,1,No Deposit,,,0,Transient,61.0,0,2
HB-082901,City Hotel,1,68,2024,February,7,17,2024-02-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,37.0,,0,Transient,75.0,0,0
HB-090608,City Hotel,0,5,2024,June,23,8,2024-06-08,0,1,1,0.0,0,SC,NZL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.0,0,1
HB-064796,City Hotel,1,197,2025,March,11,16,2025-03-16,0,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,2
HB-070092,City Hotel,1,219,2025,June,24,9,2025-06-09,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,105.0,0,0
HB-087459,City Hotel,0,5,2024,April,16,19,2024-04-19,0,1,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.0,0,0
HB-043748,City Hotel,0,86,2023,September,38,24,2023-09-24,0,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,105.0,0,0
HB-015580,Resort Hotel,0,46,2023,July,29,20,2023-07-20,2,5,3,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,C,0,No Deposit,142.0,,0,Transient,129.45,0,1
HB-095510,City Hotel,0,320,2024,August,33,18,2024-08-18,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-102725,City Hotel,0,85,2024,December,49,3,2024-12-03,1,1,1,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,4,No Deposit,9.0,,0,Transient,98.0,0,0
HB-086197,City Hotel,0,24,2024,March,13,26,2024-03-26,2,1,2,0.0,0,BB,AUT,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,100.0,0,0
HB-099031,City Hotel,0,30,2024,October,40,4,2024-10-04,0,4,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,144.8,0,1
HB-011986,Resort Hotel,1,2,2025,June,23,7,2025-06-07,0,4,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,,,0,Transient,140.0,0,2
HB-003357,Resort Hotel,1,44,2023,December,49,5,2023-12-05,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,70.0,0,0
HB-089616,City Hotel,0,11,2024,May,19,9,2024-05-09,5,10,1,0.0,0,BB,FRA,Aviation,Corporate,0,0,0,A,A,1,No Deposit,,153.0,0,Transient,95.0,0,0
HB-051802,City Hotel,1,323,2024,May,21,26,2024-05-26,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-065294,City Hotel,1,80,2025,March,14,31,2025-03-31,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,56.0,,0,Transient,90.0,0,0
HB-037572,Resort Hotel,0,145,2025,June,25,18,2025-06-18,2,2,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,410.0,,0,Transient,58.7,0,0
HB-026776,Resort Hotel,0,195,2024,August,31,4,2024-08-04,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Contract,116.1,0,0
HB-087440,City Hotel,0,3,2024,April,16,18,2024-04-18,1,1,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,70.0,0,0
HB-023244,Resort Hotel,0,86,2024,April,15,13,2024-04-13,2,5,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,94.0,1,1
HB-108847,City Hotel,0,75,2025,March,13,29,2025-03-29,0,4,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.1,0,2
HB-087299,City Hotel,0,122,2024,April,16,15,2024-04-15,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,151.0,,56,Transient-Party,85.0,0,0
HB-105085,City Hotel,0,40,2025,January,5,28,2025-01-28,0,1,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,113.58,0,2
HB-036824,Resort Hotel,0,204,2025,May,21,20,2025-05-20,4,6,2,0.0,0,HB,LVA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,68.95,0,0
HB-014421,Resort Hotel,0,0,2024,October,40,3,2024-10-03,1,1,2,0.0,0,BB,,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,96.0,1,0
HB-005867,Resort Hotel,1,38,2024,May,20,15,2024-05-15,2,5,3,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,152.0,0,0
HB-029965,Resort Hotel,0,0,2024,November,46,11,2024-11-11,0,1,2,0.0,0,BB,ITA,Direct,TA/TO,1,0,0,A,A,0,No Deposit,,,0,Transient,70.0,0,1
HB-004931,Resort Hotel,1,74,2024,April,15,9,2024-04-09,2,5,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,91.0,,0,Transient-Party,36.0,0,0
HB-024872,Resort Hotel,0,0,2024,June,23,6,2024-06-06,0,0,2,0.0,0,BB,PRT,Direct,Direct,1,0,0,A,I,0,No Deposit,250.0,,0,Transient,0.0,0,3
HB-034692,Resort Hotel,0,26,2025,March,14,31,2025-03-31,0,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,63.0,0,1
HB-079013,City Hotel,0,3,2024,June,26,27,2024-06-27,1,0,1,0.0,0,BB,PRT,Complementary,Corporate,1,2,5,A,A,0,No Deposit,,45.0,0,Transient,0.0,0,3
HB-008170,Resort Hotel,0,336,2024,September,37,15,2024-09-15,0,3,2,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,A,0,No Deposit,,223.0,0,Transient-Party,66.0,0,0
HB-048320,City Hotel,0,76,2024,March,12,20,2024-03-20,2,3,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,110.15,0,1
HB-063497,City Hotel,1,17,2025,February,7,12,2025-02-12,2,1,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,128.0,0,0
HB-113333,City Hotel,0,434,2025,June,23,3,2025-06-03,2,1,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,2
HB-038148,Resort Hotel,0,61,2025,July,28,9,2025-07-09,1,0,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,210.0,1,1
HB-090824,City Hotel,0,87,2024,June,23,9,2024-06-09,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,97.71,0,0
HB-019463,Resort Hotel,0,2,2023,December,50,17,2023-12-17,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,54.0,1,1
HB-091875,City Hotel,0,192,2024,June,26,24,2024-06-24,0,2,1,0.0,0,BB,SRB,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,34.0,,0,Transient-Party,95.0,0,0
HB-040619,City Hotel,1,28,2023,August,31,3,2023-08-03,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-061862,City Hotel,1,41,2024,December,52,27,2024-12-27,2,5,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,69.29,0,0
HB-117441,City Hotel,0,168,2025,July,31,31,2025-07-31,1,3,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,235.0,0,0
HB-043504,City Hotel,0,71,2023,September,38,18,2023-09-18,0,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.25,0,1
HB-058190,City Hotel,1,59,2024,October,41,7,2024-10-07,1,2,1,2.0,0,BB,CHN,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,171.72,0,0
HB-056001,City Hotel,1,115,2024,August,35,26,2024-08-26,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,131.4,0,0
HB-077092,City Hotel,0,219,2023,September,36,4,2023-09-04,1,2,1,0.0,0,BB,SWE,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,3.0,,0,Transient-Party,76.67,0,0
HB-087571,City Hotel,0,100,2024,April,16,18,2024-04-18,1,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,79.0,,0,Transient,65.96,0,0
HB-004230,Resort Hotel,0,123,2024,February,9,27,2024-02-27,1,1,2,0.0,0,FB,ESP,Groups,Direct,0,0,0,A,C,0,No Deposit,38.0,,0,Transient-Party,64.0,0,0
HB-099073,City Hotel,0,88,2024,October,41,7,2024-10-07,0,2,2,0.0,0,BB,POL,Corporate,Corporate,0,0,0,A,A,0,No Deposit,193.0,,0,Transient-Party,90.0,0,1
HB-019016,Resort Hotel,0,15,2023,December,49,4,2023-12-04,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient-Party,64.67,0,2
HB-094905,City Hotel,0,191,2024,August,32,8,2024-08-08,1,3,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient-Party,131.75,0,2
HB-064088,City Hotel,1,12,2025,March,9,1,2025-03-01,1,4,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,0
HB-081955,City Hotel,1,272,2024,August,32,5,2024-08-05,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,41,Transient,65.0,0,0
HB-045578,City Hotel,0,233,2023,November,45,7,2023-11-07,1,1,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,60.0,0,0
HB-010843,Resort Hotel,1,30,2025,April,15,8,2025-04-08,2,3,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,155.0,0,0
HB-028004,Resort Hotel,0,336,2024,September,37,15,2024-09-15,0,3,2,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,A,1,No Deposit,,223.0,0,Transient-Party,74.0,1,0
HB-016813,Resort Hotel,0,1,2023,September,37,11,2023-09-11,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,241.0,,0,Transient,92.4,0,0
HB-055682,City Hotel,1,209,2024,August,34,19,2024-08-19,0,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,100.8,0,0
HB-034788,Resort Hotel,0,69,2025,March,14,31,2025-03-31,2,3,4,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,147.0,,0,Transient,59.62,0,0
HB-057670,City Hotel,1,167,2024,September,39,29,2024-09-29,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,114.04,0,1
HB-000426,Resort Hotel,0,57,2023,July,28,15,2023-07-15,0,2,2,0.0,0,FB,PRT,Groups,Direct,0,0,0,A,D,0,No Deposit,305.0,,0,Transient,107.0,0,0
HB-104596,City Hotel,0,4,2025,January,3,17,2025-01-17,0,2,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,112.0,0,3
HB-011270,Resort Hotel,1,221,2025,April,18,30,2025-04-30,2,5,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,71.43,0,0
HB-094885,City Hotel,0,2,2024,August,32,11,2024-08-11,0,1,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,G,0,No Deposit,9.0,,0,Transient,185.0,0,2
HB-099118,City Hotel,0,85,2024,October,40,6,2024-10-06,1,3,2,0.0,0,BB,SWE,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,85.0,0,1
HB-063418,City Hotel,1,18,2025,February,7,11,2025-02-11,2,2,2,1.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,91.8,0,0
HB-095148,City Hotel,0,7,2024,August,33,12,2024-08-12,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,175.67,1,1
HB-071488,City Hotel,1,46,2025,July,27,6,2025-07-06,0,3,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,143.0,0,1
HB-020356,Resort Hotel,0,2,2024,January,4,24,2024-01-24,2,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,15.0,,0,Transient,25.0,0,0
HB-061422,City Hotel,1,37,2024,December,50,9,2024-12-09,2,3,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,51.05,0,1
HB-012988,Resort Hotel,1,42,2025,July,30,26,2025-07-26,2,5,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,220.0,0,2
HB-011462,Resort Hotel,1,302,2025,May,19,9,2025-05-09,0,4,2,0.0,0,HB,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,81.0,0,0
HB-113853,City Hotel,0,33,2025,June,24,9,2025-06-09,2,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,154.5,0,1
HB-091548,City Hotel,0,35,2024,June,25,21,2024-06-21,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,113.4,0,1
HB-019022,Resort Hotel,0,22,2023,December,49,5,2023-12-05,1,1,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,E,F,1,No Deposit,,,0,Transient,58.0,0,2
HB-040847,City Hotel,1,30,2023,August,32,8,2023-08-08,2,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,86.0,0,0
HB-000726,Resort Hotel,1,48,2023,July,30,27,2023-07-27,1,1,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,195.0,0,1
HB-038351,Resort Hotel,0,42,2025,July,28,11,2025-07-11,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,I,0,No Deposit,240.0,,0,Transient,184.0,0,2
HB-054683,City Hotel,1,4,2024,July,30,23,2024-07-23,1,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,141.0,0,0
HB-073138,City Hotel,1,309,2025,August,33,15,2025-08-15,0,4,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient,96.25,0,0
HB-081509,City Hotel,0,11,2023,December,50,11,2023-12-11,0,2,2,0.0,1,BB,PRT,Complementary,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,0.0,0,2
HB-009060,Resort Hotel,1,153,2024,October,43,26,2024-10-26,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,45.86,0,0
HB-019410,Resort Hotel,0,0,2023,December,50,17,2023-12-17,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,38.0,0,0
HB-001479,Resort Hotel,0,59,2023,August,35,31,2023-08-31,1,3,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,15.0,,0,Transient,105.5,0,2
HB-093352,City Hotel,0,5,2024,July,29,20,2024-07-20,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,122.0,0,0
HB-003218,Resort Hotel,0,15,2023,November,47,21,2023-11-21,0,1,2,1.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,G,1,No Deposit,,342.0,0,Transient-Party,44.0,0,0
HB-062646,City Hotel,1,54,2025,January,3,18,2025-01-18,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,171.0,,0,Transient,65.0,0,0
HB-107050,City Hotel,0,2,2025,March,10,5,2025-03-05,2,0,2,0.0,0,SC,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,92.5,0,0
HB-055093,City Hotel,1,6,2024,August,31,4,2024-08-04,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,166.0,0,0
HB-061694,City Hotel,1,60,2024,December,52,23,2024-12-23,0,1,2,2.0,0,BB,AUT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,156.6,0,1
HB-082218,City Hotel,1,317,2024,September,37,9,2024-09-09,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,58.0,,56,Transient,90.0,0,0
HB-068091,City Hotel,1,51,2025,May,20,12,2025-05-12,2,2,2,0.0,0,BB,TUR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,207.0,0,0
HB-057457,City Hotel,0,418,2024,September,39,26,2024-09-26,1,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,132.0,,223,Transient-Party,107.0,0,0
HB-087892,City Hotel,0,68,2024,April,17,26,2024-04-26,0,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,118.8,0,1
HB-093568,City Hotel,0,292,2024,July,29,21,2024-07-21,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,0
HB-107307,City Hotel,0,88,2025,March,10,8,2025-03-08,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,106.2,0,2
HB-097080,City Hotel,0,14,2024,September,37,11,2024-09-11,1,0,1,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.0,0,2
HB-078199,City Hotel,1,289,2024,July,29,20,2024-07-20,2,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Contract,95.4,0,2
HB-012256,Resort Hotel,1,321,2025,June,25,20,2025-06-20,0,5,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,103.05,0,1
HB-097223,City Hotel,0,63,2024,September,37,12,2024-09-12,1,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.1,0,2
HB-038572,Resort Hotel,0,6,2025,July,30,21,2025-07-21,0,2,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,142.21,0,1
HB-055981,City Hotel,1,46,2024,August,35,26,2024-08-26,0,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.1,0,0
HB-027338,Resort Hotel,0,87,2024,August,34,20,2024-08-20,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,3.0,,0,Transient,154.0,0,0
HB-095961,City Hotel,0,0,2024,August,34,25,2024-08-25,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,152.0,,0,Transient,92.98,0,0
HB-097575,City Hotel,0,105,2024,September,38,16,2024-09-16,0,2,3,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,9.0,,0,Transient,168.3,0,2
HB-074040,City Hotel,1,307,2023,August,33,20,2023-08-20,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-084701,City Hotel,0,17,2024,February,9,27,2024-02-27,2,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,46.4,0,0
HB-048759,City Hotel,1,112,2024,March,13,30,2024-03-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,64.0,0,0
HB-076578,City Hotel,1,207,2023,September,39,29,2023-09-29,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,20.0,,0,Transient,48.0,0,0
HB-007578,Resort Hotel,1,135,2024,August,33,15,2024-08-15,1,4,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,246.0,0,0
HB-076260,City Hotel,1,147,2023,July,29,21,2023-07-21,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient,75.0,0,0
HB-039393,Resort Hotel,0,315,2025,August,33,14,2025-08-14,1,2,2,0.0,0,BB,JPN,Online TA,TA/TO,0,0,0,E,G,0,No Deposit,240.0,,0,Transient,172.8,0,3
HB-076425,City Hotel,1,358,2023,October,41,10,2023-10-10,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-014916,Resort Hotel,0,126,2024,April,17,22,2024-04-22,1,2,1,0.0,0,BB,PRT,Online TA,Direct,1,1,5,A,D,1,No Deposit,,,0,Transient,44.1,0,4
HB-083471,City Hotel,0,3,2024,February,5,1,2024-02-01,1,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,86.0,0,1
HB-078036,City Hotel,1,19,2023,October,39,1,2023-10-01,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,111.75,0,1
HB-042874,City Hotel,0,168,2023,September,37,11,2023-09-11,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,50.0,0,0
HB-032020,Resort Hotel,0,4,2025,January,3,14,2025-01-14,0,1,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,168.0,,0,Transient-Party,68.0,0,0
HB-005828,Resort Hotel,1,211,2024,May,20,14,2024-05-14,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,85.0,0,0
HB-029494,Resort Hotel,0,14,2024,October,44,28,2024-10-28,0,2,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,36.0,0,0
HB-040283,City Hotel,0,12,2023,July,29,18,2023-07-18,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-048786,City Hotel,0,92,2024,March,13,30,2024-03-30,0,4,3,0.0,0,SC,AUT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,7.0,,0,Transient,78.54,0,1
HB-064711,City Hotel,1,92,2025,March,11,15,2025-03-15,0,3,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,85.0,0,0
HB-005738,Resort Hotel,1,236,2024,May,19,12,2024-05-12,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,315.0,,0,Transient-Party,48.0,0,0
HB-075312,City Hotel,1,304,2023,August,33,17,2023-08-17,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-046108,City Hotel,0,110,2023,December,49,9,2023-12-09,0,4,3,1.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,G,G,3,No Deposit,56.0,,69,Transient-Party,139.5,0,1
HB-063728,City Hotel,1,161,2025,February,8,19,2025-02-19,2,1,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,104.0,0,1
HB-017498,Resort Hotel,0,277,2023,October,40,6,2023-10-06,2,5,2,0.0,0,HB,GBR,Groups,Direct,0,0,0,D,D,0,No Deposit,273.0,,0,Transient-Party,68.74,0,0
HB-061894,City Hotel,1,21,2024,December,52,28,2024-12-28,0,4,2,0.0,0,BB,HUN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,129.58,0,0
HB-092872,City Hotel,0,12,2024,July,28,10,2024-07-10,2,1,2,0.0,0,SC,AUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,139.0,0,1
HB-026792,Resort Hotel,0,151,2024,August,32,8,2024-08-08,1,2,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,241.0,,0,Transient,204.5,0,0
HB-029934,Resort Hotel,0,66,2024,November,45,6,2024-11-06,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,C,1,No Deposit,240.0,,0,Transient,37.8,0,2
HB-024801,Resort Hotel,0,40,2024,May,22,30,2024-05-30,1,4,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,89.0,0,1
HB-080374,City Hotel,1,20,2023,November,48,29,2023-11-29,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Contract,97.0,0,1
HB-028944,Resort Hotel,0,2,2024,October,42,16,2024-10-16,1,0,2,0.0,0,BB,BEL,Online TA,Corporate,0,0,0,A,H,0,No Deposit,240.0,,0,Transient,81.0,1,1
HB-059286,City Hotel,1,0,2024,October,43,26,2024-10-26,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,89.0,0,0
HB-049682,City Hotel,1,275,2024,April,16,17,2024-04-17,2,0,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,0,Transient,110.0,0,0
HB-112737,City Hotel,0,233,2025,May,21,25,2025-05-25,0,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,2
HB-117867,City Hotel,0,18,2025,August,32,7,2025-08-07,1,3,2,0.0,0,BB,DNK,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,180.0,0,2
HB-105198,City Hotel,0,5,2025,February,5,1,2025-02-01,0,1,1,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.0,0,1
HB-023028,Resort Hotel,0,0,2024,April,15,14,2024-04-14,0,0,2,0.0,0,BB,FRA,Online TA,TA/TO,1,0,0,D,I,0,No Deposit,240.0,,0,Transient,0.0,1,1
HB-072243,City Hotel,1,273,2025,July,30,24,2025-07-24,1,3,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,179.1,0,0
HB-038925,Resort Hotel,0,124,2025,July,31,30,2025-07-30,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,209.0,0,3
HB-094670,City Hotel,0,209,2024,August,32,5,2024-08-05,1,2,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.3,1,1
HB-098434,City Hotel,0,218,2024,September,39,29,2024-09-29,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,116.1,0,2
HB-030674,Resort Hotel,0,76,2024,November,48,29,2024-11-29,0,2,2,0.0,0,BB,SWE,Corporate,Corporate,0,0,0,E,E,0,No Deposit,481.0,,0,Transient-Party,50.0,0,0
HB-047184,City Hotel,1,15,2024,February,7,12,2024-02-12,0,2,1,0.0,0,BB,AUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.0,0,0
HB-045917,City Hotel,0,84,2023,November,48,27,2023-11-27,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,64.0,0,0
HB-105029,City Hotel,0,60,2025,January,4,25,2025-01-25,0,3,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,120.1,1,1
HB-034338,Resort Hotel,0,3,2025,March,12,20,2025-03-20,1,0,1,0.0,0,BB,ESP,Complementary,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,0.0,1,0
HB-084159,City Hotel,0,8,2024,February,8,19,2024-02-19,0,1,1,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,A,0,No Deposit,,67.0,0,Transient-Party,81.0,0,0
HB-086812,City Hotel,0,8,2024,April,15,8,2024-04-08,0,1,1,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,7.0,,0,Transient,64.68,0,1
HB-072754,City Hotel,1,223,2025,August,32,5,2025-08-05,2,1,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.5,0,0
HB-020500,Resort Hotel,0,1,2024,January,5,30,2024-01-30,0,1,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,66.0,0,0
HB-115264,City Hotel,0,4,2025,July,27,3,2025-07-03,1,0,2,0.0,0,SC,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.0,0,0
HB-024661,Resort Hotel,1,6,2024,May,22,29,2024-05-29,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,I,0,No Deposit,250.0,,0,Transient,0.0,0,0
HB-055582,City Hotel,1,37,2024,August,33,17,2024-08-17,0,1,2,1.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,164.25,0,0
HB-036596,Resort Hotel,0,128,2025,May,20,18,2025-05-18,2,5,1,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Transient,34.2,0,0
HB-003383,Resort Hotel,0,59,2023,December,49,5,2023-12-05,2,1,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,D,2,No Deposit,240.0,,0,Transient,68.45,0,2
HB-054399,City Hotel,1,93,2024,July,28,14,2024-07-14,1,3,2,1.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.35,0,0
HB-056406,City Hotel,1,94,2024,September,36,5,2024-09-05,1,0,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,168.3,0,0
HB-052237,City Hotel,1,330,2024,June,22,2,2024-06-02,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-097742,City Hotel,0,74,2024,September,38,16,2024-09-16,2,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,95.0,0,0
HB-053382,City Hotel,1,44,2024,June,25,19,2024-06-19,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.45,0,0
HB-116654,City Hotel,0,167,2025,July,29,20,2025-07-20,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.9,0,2
HB-002181,Resort Hotel,0,54,2023,October,40,4,2023-10-04,4,7,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,40.0,,0,Contract,78.2,0,0
HB-061266,City Hotel,1,133,2024,December,49,6,2024-12-06,0,4,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,9.0,,0,Transient,100.3,0,1
HB-033805,Resort Hotel,0,7,2025,March,9,2,2025-03-02,0,3,1,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,2,No Deposit,,223.0,0,Transient-Party,29.0,0,0
HB-072598,City Hotel,1,493,2025,August,31,1,2025-08-01,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-053490,City Hotel,0,193,2024,June,25,22,2024-06-22,0,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,100.8,0,1
HB-077497,City Hotel,0,263,2023,September,38,21,2023-09-21,1,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,21.0,,0,Transient-Party,67.0,0,0
HB-076961,City Hotel,1,342,2023,September,38,24,2023-09-24,2,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-065138,City Hotel,1,278,2025,March,13,25,2025-03-25,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient,90.0,0,0
HB-031244,Resort Hotel,0,2,2024,December,52,29,2024-12-29,0,2,1,0.0,0,BB,PRT,Direct,TA/TO,1,0,1,A,A,0,No Deposit,250.0,,0,Transient-Party,75.0,0,3
HB-077300,City Hotel,0,256,2023,September,37,14,2023-09-14,1,2,1,0.0,0,BB,ARG,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,4.0,,0,Transient-Party,64.33,0,0
HB-028922,Resort Hotel,0,231,2024,October,41,8,2024-10-08,2,5,2,0.0,0,BB,GBR,Groups,Direct,0,0,0,D,D,0,No Deposit,273.0,,0,Transient-Party,71.36,0,0
HB-073335,City Hotel,1,140,2025,August,34,19,2025-08-19,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,155.0,0,1
HB-112685,City Hotel,0,12,2025,May,21,24,2025-05-24,0,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,0
HB-084310,City Hotel,0,152,2024,February,8,20,2024-02-20,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Transient,62.0,0,1
HB-037560,Resort Hotel,0,29,2025,June,24,15,2025-06-15,2,5,2,0.0,0,HB,LTU,Direct,Direct,0,0,0,A,A,1,No Deposit,250.0,,0,Transient,177.0,0,2
HB-039401,Resort Hotel,0,212,2025,August,33,11,2025-08-11,2,4,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,203.67,0,4
HB-096837,City Hotel,0,81,2024,September,36,5,2024-09-05,1,3,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,86.0,,0,Transient-Party,85.0,0,0
HB-034247,Resort Hotel,0,120,2025,March,11,15,2025-03-15,0,3,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,6,No Deposit,,477.0,8,Transient-Party,45.0,0,0
HB-014099,Resort Hotel,0,152,2025,August,34,18,2025-08-18,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,6,E,F,0,No Deposit,240.0,,0,Transient,254.0,1,4
HB-015115,Resort Hotel,1,214,2023,October,40,3,2023-10-03,1,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,208.0,,0,Transient,34.0,0,0
HB-067989,City Hotel,1,18,2025,May,19,10,2025-05-10,2,9,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,8.0,,0,Transient,294.55,0,1
HB-077289,City Hotel,1,9,2023,September,38,24,2023-09-24,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,1,0,A,A,0,No Deposit,14.0,,0,Transient,171.33,0,1
HB-113859,City Hotel,0,0,2025,June,24,12,2025-06-12,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,144.0,0,0
HB-104484,City Hotel,0,12,2025,January,2,11,2025-01-11,0,4,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,125.38,0,1
HB-025574,Resort Hotel,0,301,2024,June,25,20,2024-06-20,3,10,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,147.0,,0,Transient,71.25,0,0
HB-067710,City Hotel,1,169,2025,May,19,6,2025-05-06,2,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,0
HB-029481,Resort Hotel,0,8,2024,October,43,26,2024-10-26,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,I,1,No Deposit,,,0,Transient,92.5,1,1
HB-082662,City Hotel,0,44,2024,January,1,2,2024-01-02,2,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,98.0,0,0
HB-011169,Resort Hotel,1,203,2025,April,17,25,2025-04-25,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,90.0,0,0
HB-027248,Resort Hotel,0,85,2024,August,34,19,2024-08-19,2,3,1,1.0,0,FB,PRT,Direct,Direct,0,0,0,E,E,2,No Deposit,250.0,,0,Transient,283.0,0,0
HB-026391,Resort Hotel,0,164,2024,July,30,22,2024-07-22,2,6,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,128.18,0,1
HB-072543,City Hotel,1,196,2025,July,31,30,2025-07-30,2,3,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,112.5,0,0
HB-031755,Resort Hotel,0,0,2025,January,1,5,2025-01-05,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,44.0,0,0
HB-014981,Resort Hotel,1,166,2023,July,28,15,2023-07-15,0,2,2,0.0,0,FB,PRT,Groups,TA/TO,0,24,0,A,A,0,Non Refund,,,0,Transient,121.5,0,0
HB-109645,City Hotel,0,109,2025,April,15,10,2025-04-10,1,4,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,8.0,,0,Transient,102.6,0,1
HB-102911,City Hotel,0,0,2024,December,49,5,2024-12-05,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.89,0,1
HB-085088,City Hotel,0,7,2024,March,10,7,2024-03-07,1,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,96.0,0,1
HB-071964,City Hotel,1,193,2025,July,29,16,2025-07-16,2,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,2
HB-042907,City Hotel,1,28,2023,September,37,11,2023-09-11,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,113.79,0,1
HB-014528,Resort Hotel,0,1,2024,April,14,7,2024-04-07,0,3,2,1.0,0,BB,,Direct,Direct,0,0,0,D,D,1,No Deposit,250.0,,0,Transient,75.0,0,1
HB-032013,Resort Hotel,0,0,2025,January,5,29,2025-01-29,1,0,2,0.0,0,BB,CHN,Direct,Direct,1,0,1,A,A,0,No Deposit,,,0,Transient,45.0,0,0
HB-108812,City Hotel,0,190,2025,March,13,29,2025-03-29,0,4,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-096725,City Hotel,0,204,2024,September,36,3,2024-09-03,2,2,2,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,121.0,,0,Transient-Party,80.75,0,2
HB-034688,Resort Hotel,0,7,2025,July,30,26,2025-07-26,0,1,1,0.0,0,BB,PRT,Direct,Direct,1,0,1,A,D,1,No Deposit,,,0,Transient,164.0,0,0
HB-090444,City Hotel,0,247,2024,June,23,6,2024-06-06,0,0,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient-Party,0.0,0,1
HB-038432,Resort Hotel,0,0,2025,July,29,15,2025-07-15,2,1,3,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,205.33,0,0
HB-080718,City Hotel,0,32,2023,November,47,20,2023-11-20,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,119.0,,0,Transient-Party,73.0,0,0
HB-025142,Resort Hotel,0,2,2025,January,2,12,2025-01-12,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,8,A,D,0,No Deposit,,154.0,0,Transient,35.0,0,0
HB-082717,City Hotel,0,0,2024,January,3,18,2024-01-18,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,1,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-040148,City Hotel,0,61,2023,July,28,11,2023-07-11,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,55.96,0,0
HB-107836,City Hotel,0,66,2025,March,11,15,2025-03-15,0,4,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,134.3,0,1
HB-010687,Resort Hotel,1,103,2025,March,13,27,2025-03-27,1,1,2,0.0,0,BB,PRT,Groups,Corporate,0,0,0,D,D,0,Non Refund,495.0,,0,Transient,65.0,0,0
HB-060766,City Hotel,1,84,2024,November,47,20,2024-11-20,2,0,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,71.28,0,0
HB-022896,Resort Hotel,0,80,2024,April,14,7,2024-04-07,0,3,2,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,67.0,,0,Transient-Party,68.0,0,0
HB-017395,Resort Hotel,0,0,2023,October,40,5,2023-10-05,1,3,1,0.0,0,FB,PRT,Corporate,Corporate,0,0,0,A,H,1,No Deposit,,174.0,0,Transient-Party,76.0,1,0
HB-014810,Resort Hotel,1,267,2023,August,32,12,2023-08-12,0,2,2,0.0,0,HB,PRT,Online TA,TA/TO,0,1,0,E,E,0,No Deposit,240.0,,0,Transient,196.0,0,0
HB-077781,City Hotel,0,0,2023,September,39,26,2023-09-26,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,180.0,0,0
HB-101467,City Hotel,0,37,2024,November,46,12,2024-11-12,0,1,1,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,67.5,0,0
HB-086403,City Hotel,0,20,2024,March,13,28,2024-03-28,1,4,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,215.0,0,2
HB-082135,City Hotel,1,99,2024,February,8,19,2024-02-19,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,1,0,A,A,0,No Deposit,,67.0,0,Transient-Party,80.0,0,0
HB-090182,City Hotel,0,12,2024,May,22,30,2024-05-30,1,3,2,0.0,0,BB,EST,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,259.0,0,Transient-Party,111.35,0,0
HB-010618,Resort Hotel,1,61,2025,March,12,22,2025-03-22,0,3,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,70.0,0,0
HB-060938,City Hotel,1,30,2024,November,48,26,2024-11-26,2,1,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,0
HB-004178,Resort Hotel,1,26,2024,February,8,24,2024-02-24,0,4,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,39.0,0,1
HB-021042,Resort Hotel,0,2,2024,February,7,15,2024-02-15,1,0,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,339.0,,0,Transient,29.0,0,0
HB-056764,City Hotel,1,160,2024,September,37,13,2024-09-13,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-059075,City Hotel,1,263,2024,October,43,21,2024-10-21,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,0,Transient,110.0,0,0
HB-029054,Resort Hotel,0,5,2024,October,42,19,2024-10-19,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,54.9,0,0
HB-099567,City Hotel,0,77,2024,October,42,14,2024-10-14,0,1,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,135.1,0,0
HB-105061,City Hotel,0,13,2025,January,4,25,2025-01-25,0,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,79.69,0,1
HB-042479,City Hotel,0,55,2023,September,36,6,2023-09-06,2,0,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,75.0,0,0
HB-109076,City Hotel,0,54,2025,April,14,3,2025-04-03,1,2,2,2.0,0,HB,GBR,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,225.0,0,1
HB-103858,City Hotel,0,20,2025,January,1,1,2025-01-01,1,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,65.0,0,0
HB-080037,City Hotel,0,2,2024,January,2,13,2024-01-13,0,2,1,0.0,0,BB,DEU,Online TA,TA/TO,1,11,4,A,A,0,No Deposit,9.0,,0,Transient,77.5,0,0
HB-071909,City Hotel,1,44,2025,July,29,15,2025-07-15,2,1,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,153.33,0,1
HB-095905,City Hotel,0,5,2025,July,28,11,2025-07-11,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,17,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,1
HB-064013,City Hotel,1,17,2025,February,9,26,2025-02-26,2,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,D,D,0,No Deposit,30.0,,0,Transient-Party,75.0,0,0
HB-042964,City Hotel,0,10,2023,September,37,11,2023-09-11,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,128.5,0,2
HB-076258,City Hotel,1,221,2023,October,40,3,2023-10-03,2,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,86.0,0,0
HB-042024,City Hotel,0,14,2023,August,35,29,2023-08-29,2,5,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,79.0,0,0
HB-057800,City Hotel,1,261,2024,October,40,1,2024-10-01,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,96.0,0,0
HB-002064,Resort Hotel,0,2,2023,September,39,30,2023-09-30,0,2,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,H,1,No Deposit,,318.0,0,Transient,55.5,0,1
HB-077673,City Hotel,0,5,2023,September,38,19,2023-09-19,2,3,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,D,0,No Deposit,14.0,,0,Transient,117.8,0,0
HB-114198,City Hotel,0,28,2025,June,24,15,2025-06-15,0,3,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,80.1,0,0
HB-112037,City Hotel,0,20,2025,May,20,17,2025-05-17,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,144.4,0,1
HB-089200,City Hotel,0,64,2024,May,20,17,2024-05-17,0,2,1,0.0,0,BB,ITA,Corporate,TA/TO,0,0,0,A,A,0,No Deposit,,218.0,0,Transient-Party,130.0,0,0
HB-093760,City Hotel,0,71,2024,July,30,24,2024-07-24,2,1,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,72.25,0,0
HB-049913,City Hotel,1,265,2024,April,16,20,2024-04-20,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,30.0,,0,Transient,101.0,0,0
HB-074374,City Hotel,1,276,2023,July,29,20,2023-07-20,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Contract,62.0,0,0
HB-085038,City Hotel,0,0,2024,March,10,7,2024-03-07,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,89.0,0,0
HB-112043,City Hotel,0,82,2025,May,20,16,2025-05-16,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.0,0,0
HB-032374,Resort Hotel,0,29,2025,January,4,21,2025-01-21,2,2,1,0.0,1,BB,IRL,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,39.0,0,3
HB-089600,City Hotel,0,91,2024,May,21,21,2024-05-21,1,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,116.1,0,0
HB-051576,City Hotel,1,95,2024,May,21,21,2024-05-21,2,2,2,0.0,0,SC,BGR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.65,0,0
HB-085029,City Hotel,0,0,2024,March,10,7,2024-03-07,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,101.0,0,0
HB-024965,Resort Hotel,0,12,2024,June,23,8,2024-06-08,0,3,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,90.67,0,0
HB-071252,City Hotel,1,15,2025,June,27,30,2025-06-30,0,2,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,230.0,0,0
HB-030923,Resort Hotel,0,174,2024,December,49,8,2024-12-08,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,F,1,No Deposit,240.0,,0,Transient,55.8,0,3
HB-065451,City Hotel,1,3,2025,April,14,3,2025-04-03,1,3,1,0.0,0,BB,PRT,Aviation,Corporate,0,0,0,A,A,0,No Deposit,,153.0,0,Transient,126.0,0,0
HB-113062,City Hotel,0,11,2025,May,22,29,2025-05-29,1,3,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,157.5,0,1
HB-082913,City Hotel,0,0,2024,January,1,6,2024-01-06,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,67.49,0,0
HB-025560,Resort Hotel,0,128,2024,June,25,22,2024-06-22,2,8,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,109.1,0,1
HB-035610,Resort Hotel,0,6,2025,April,18,28,2025-04-28,0,1,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,I,0,No Deposit,240.0,,0,Transient,153.0,0,1
HB-037505,Resort Hotel,0,195,2025,June,23,7,2025-06-07,4,9,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,140.0,0,1
HB-075370,City Hotel,1,313,2023,August,34,26,2023-08-26,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-076003,City Hotel,1,336,2023,September,38,18,2023-09-18,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-077152,City Hotel,0,0,2023,December,50,16,2023-12-16,0,1,2,0.0,0,BB,PRT,Complementary,Direct,1,2,8,G,G,1,No Deposit,45.0,,0,Transient,0.0,0,1
HB-065075,City Hotel,1,126,2025,March,12,23,2025-03-23,0,3,2,0.0,0,BB,EST,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.6,0,2
HB-102335,City Hotel,0,56,2024,November,47,24,2024-11-24,0,3,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient-Party,95.38,0,1
HB-061855,City Hotel,1,196,2024,December,52,27,2024-12-27,1,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,101.15,0,0
HB-041522,City Hotel,1,4,2023,August,33,17,2023-08-17,1,5,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,134.17,0,2
HB-018539,Resort Hotel,0,289,2023,November,47,20,2023-11-20,1,2,2,0.0,0,HB,GIB,Groups,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,57.0,0,0
HB-056128,City Hotel,1,57,2024,August,35,29,2024-08-29,3,8,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,123.55,0,0
HB-031600,Resort Hotel,0,196,2024,December,1,30,2024-12-30,1,2,1,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,A,2,No Deposit,,308.0,0,Transient-Party,100.25,0,0
HB-059529,City Hotel,1,247,2024,October,44,28,2024-10-28,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,110.0,0,0
HB-038653,Resort Hotel,0,115,2025,July,29,18,2025-07-18,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,123.5,0,0
HB-028501,Resort Hotel,0,13,2024,October,40,1,2024-10-01,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,139.0,0,2
HB-092123,City Hotel,0,105,2024,June,26,26,2024-06-26,2,3,2,0.0,0,SC,NZL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.95,0,0
HB-034948,Resort Hotel,0,4,2025,April,15,8,2025-04-08,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,85.0,1,1
HB-081641,City Hotel,0,23,2023,December,50,16,2023-12-16,0,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,B,B,2,No Deposit,9.0,,0,Contract,81.75,0,1
HB-016503,Resort Hotel,0,59,2023,August,34,27,2023-08-27,2,3,2,2.0,1,HB,PRT,Direct,Direct,0,0,0,G,G,1,No Deposit,,,0,Transient,264.5,1,0
HB-055738,City Hotel,1,152,2024,August,34,19,2024-08-19,2,4,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.67,0,1
HB-008484,Resort Hotel,1,24,2024,October,40,1,2024-10-01,1,1,2,1.0,1,BB,PRT,Online TA,TA/TO,0,0,0,G,G,1,No Deposit,240.0,,0,Transient,169.0,0,3
HB-000432,Resort Hotel,0,57,2023,July,28,15,2023-07-15,0,2,2,0.0,0,FB,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,305.0,,0,Transient,107.0,0,0
HB-005281,Resort Hotel,1,9,2024,April,17,24,2024-04-24,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,81.0,0,0
HB-065740,City Hotel,1,31,2025,April,15,7,2025-04-07,0,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,0
HB-052965,City Hotel,1,71,2024,June,24,14,2024-06-14,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,120.0,0,0
HB-066091,City Hotel,1,166,2025,April,16,14,2025-04-14,0,2,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,114.0,0,1
HB-103701,City Hotel,0,103,2024,December,52,27,2024-12-27,0,3,3,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,6.0,,0,Transient,113.05,0,1
HB-117340,City Hotel,0,11,2025,July,31,30,2025-07-30,2,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,125.02,0,1
HB-099882,City Hotel,0,54,2024,October,42,16,2024-10-16,2,2,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,21.0,,0,Transient-Party,81.0,0,0
HB-043206,City Hotel,0,22,2023,September,37,16,2023-09-16,0,2,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,1,No Deposit,40.0,,0,Transient,75.0,0,0
HB-072650,City Hotel,1,200,2025,August,31,2,2025-08-02,0,3,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,177.3,0,0
HB-010669,Resort Hotel,1,103,2025,March,13,27,2025-03-27,1,1,2,0.0,0,BB,PRT,Groups,Corporate,0,0,0,E,E,0,Non Refund,495.0,,0,Transient,73.0,0,0
HB-053362,City Hotel,1,68,2024,June,25,18,2024-06-18,2,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,92.83,0,0
HB-071173,City Hotel,1,106,2025,June,26,29,2025-06-29,0,1,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,B,B,0,No Deposit,14.0,,0,Transient,121.5,0,1
HB-068696,City Hotel,1,93,2025,May,21,19,2025-05-19,2,2,2,0.0,0,SC,AUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-118327,City Hotel,0,191,2025,August,33,11,2025-08-11,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,168.0,,0,Transient,112.1,0,0
HB-024601,Resort Hotel,0,53,2024,May,21,22,2024-05-22,2,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,71.0,1,1
HB-041965,City Hotel,0,11,2023,August,35,28,2023-08-28,2,2,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,85.0,0,0
HB-044571,City Hotel,0,65,2023,October,40,8,2023-10-08,0,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,72.25,0,0
HB-016589,Resort Hotel,0,19,2023,September,35,1,2023-09-01,0,2,2,0.0,0,HB,ESP,Direct,Direct,0,0,0,E,F,0,No Deposit,,,0,Transient,176.0,1,3
HB-011519,Resort Hotel,1,124,2025,May,20,13,2025-05-13,2,4,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,115.0,0,1
HB-086818,City Hotel,0,23,2024,April,15,8,2024-04-08,0,1,2,0.0,0,SC,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.0,0,0
HB-099874,City Hotel,0,54,2024,October,42,16,2024-10-16,2,2,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,21.0,,0,Transient-Party,66.5,0,0
HB-050660,City Hotel,1,190,2024,May,18,5,2024-05-05,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient-Party,95.4,0,1
HB-065966,City Hotel,1,52,2025,April,15,11,2025-04-11,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,100.8,0,1
HB-002983,Resort Hotel,0,2,2023,November,45,9,2023-11-09,1,3,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,241.0,,0,Transient,77.23,1,1
HB-065332,City Hotel,1,161,2025,March,14,31,2025-03-31,1,2,3,0.0,0,BB,DNK,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,157.2,0,0
HB-039961,Resort Hotel,0,178,2025,August,35,27,2025-08-27,2,5,3,1.0,0,FB,PRT,Online TA,TA/TO,0,0,0,H,H,2,No Deposit,240.0,,0,Transient,383.0,1,3
HB-103900,City Hotel,0,207,2024,December,1,30,2024-12-30,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,104.0,,0,Transient,161.67,0,0
HB-020177,Resort Hotel,0,6,2024,April,17,28,2024-04-28,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,1,0,2,A,D,0,No Deposit,240.0,,0,Transient,56.0,0,0
HB-000226,Resort Hotel,0,394,2023,July,27,8,2023-07-08,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,89.68,0,0
HB-017621,Resort Hotel,0,0,2023,October,42,18,2023-10-18,1,0,1,0.0,0,BB,GBR,Groups,Corporate,1,0,0,A,D,0,No Deposit,,,0,Transient,58.0,0,0
HB-118843,City Hotel,0,43,2025,August,35,25,2025-08-25,0,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,3
HB-008150,Resort Hotel,0,335,2024,September,37,14,2024-09-14,1,4,2,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,A,2,No Deposit,,223.0,0,Transient-Party,76.4,1,0
HB-106942,City Hotel,0,19,2025,March,9,2,2025-03-02,0,3,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.0,0,1
HB-068271,City Hotel,1,104,2025,May,20,15,2025-05-15,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,170.0,0,0
HB-053797,City Hotel,1,358,2024,June,26,30,2024-06-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-070382,City Hotel,1,53,2025,June,25,16,2025-06-16,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,1
HB-057532,City Hotel,1,250,2024,September,39,26,2024-09-26,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,95.0,0,0
HB-033128,Resort Hotel,0,0,2025,February,7,14,2025-02-14,0,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,314.0,,0,Transient,54.4,0,0
HB-032011,Resort Hotel,0,4,2025,January,3,14,2025-01-14,0,1,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,168.0,,0,Transient-Party,68.0,0,0
HB-012246,Resort Hotel,1,34,2025,June,25,19,2025-06-19,1,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,143.33,0,2
HB-091820,City Hotel,0,192,2024,June,26,24,2024-06-24,0,2,1,0.0,0,BB,SRB,Offline TA/TO,TA/TO,0,0,0,A,F,0,No Deposit,34.0,,0,Transient-Party,95.0,0,0
HB-020812,Resort Hotel,0,0,2024,February,6,9,2024-02-09,0,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient-Party,58.0,0,2
HB-065369,City Hotel,1,162,2025,April,14,1,2025-04-01,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,296.0,,0,Transient-Party,98.0,0,0
HB-034128,Resort Hotel,0,134,2025,March,10,9,2025-03-09,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,241.0,,0,Transient,48.43,0,2
HB-042792,City Hotel,1,44,2023,September,36,10,2023-09-10,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,41.0,,0,Transient,126.0,0,0
HB-068416,City Hotel,1,56,2025,May,20,17,2025-05-17,0,1,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,7.0,,0,Transient,108.0,0,0
HB-014722,Resort Hotel,1,259,2023,September,37,17,2023-09-17,0,3,2,0.0,0,BB,GBR,Groups,Corporate,0,1,0,A,A,0,Non Refund,,223.0,0,Transient,40.05,0,0
HB-007844,Resort Hotel,1,196,2024,August,35,29,2024-08-29,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,314.0,,0,Transient,121.47,0,1
HB-025733,Resort Hotel,0,28,2024,July,27,6,2024-07-06,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,201.0,1,0
HB-082160,City Hotel,1,99,2024,February,8,19,2024-02-19,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,1,0,A,A,0,No Deposit,,67.0,0,Transient-Party,80.0,0,0
HB-007491,Resort Hotel,1,68,2024,August,33,12,2024-08-12,1,2,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,241.0,0,0
HB-000166,Resort Hotel,0,84,2023,July,27,6,2023-07-06,1,3,2,0.0,1,BB,PRT,Online TA,TA/TO,0,0,0,D,E,1,No Deposit,240.0,,0,Transient,97.0,0,2
HB-075950,City Hotel,1,301,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-002607,Resort Hotel,0,73,2023,October,43,23,2023-10-23,2,4,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,38.92,1,1
HB-082929,City Hotel,1,177,2024,May,19,8,2024-05-08,2,0,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,3.0,,0,Transient,121.0,0,0
HB-018856,Resort Hotel,0,0,2023,November,48,30,2023-11-30,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,331.0,0,Transient,48.0,0,0
HB-030072,Resort Hotel,0,37,2024,October,44,30,2024-10-30,4,10,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,50.02,0,2
HB-036317,Resort Hotel,0,110,2025,May,19,9,2025-05-09,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,40.95,0,0
HB-037881,Resort Hotel,0,152,2025,June,26,25,2025-06-25,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Transient,84.8,0,0
HB-007935,Resort Hotel,1,315,2024,September,36,2,2024-09-02,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,115.0,,0,Transient,64.8,0,0
HB-054885,City Hotel,0,237,2024,July,30,28,2024-07-28,2,4,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient-Party,81.5,0,1
HB-063552,City Hotel,1,21,2025,February,7,14,2025-02-14,0,1,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-062931,City Hotel,1,61,2025,January,4,25,2025-01-25,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,326.0,,0,Transient,80.0,0,0
HB-089013,City Hotel,0,32,2024,May,20,13,2024-05-13,1,2,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,7.0,,0,Transient,184.99,0,2
HB-039647,Resort Hotel,0,258,2025,August,34,20,2025-08-20,2,2,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,410.0,,0,Transient,118.5,0,2
HB-042810,City Hotel,0,16,2023,September,36,10,2023-09-10,2,6,1,0.0,0,BB,BRA,Direct,Direct,0,0,0,A,D,1,No Deposit,14.0,,0,Transient,100.88,0,0
HB-061916,City Hotel,1,16,2024,December,52,28,2024-12-28,2,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,76.67,0,0
HB-016148,Resort Hotel,0,19,2023,August,32,10,2023-08-10,1,5,2,0.0,1,BB,PRT,Direct,Direct,0,0,0,D,D,1,No Deposit,,,0,Transient,189.0,0,1
HB-068070,City Hotel,1,254,2025,May,20,12,2025-05-12,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,139.5,0,0
HB-088294,City Hotel,0,57,2025,August,31,1,2025-08-01,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,8,A,A,0,No Deposit,,221.0,0,Transient,80.0,0,0
HB-023156,Resort Hotel,0,72,2024,April,15,9,2024-04-09,2,5,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,96.0,,0,Transient-Party,41.4,0,0
HB-053030,City Hotel,1,188,2024,June,24,15,2024-06-15,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,39,Transient,130.0,0,0
HB-064979,City Hotel,1,56,2025,March,12,21,2025-03-21,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,86.0,,0,Transient,85.0,0,0
HB-049111,City Hotel,1,105,2024,April,14,6,2024-04-06,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,0,Transient,75.0,0,0
HB-089775,City Hotel,0,8,2024,May,21,25,2024-05-25,0,1,1,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,106.25,0,1
HB-112014,City Hotel,0,91,2025,May,20,18,2025-05-18,0,1,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,C,0,No Deposit,262.0,,0,Transient,89.1,0,0
HB-022307,Resort Hotel,0,19,2024,March,12,21,2024-03-21,1,1,2,0.0,1,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,C,1,No Deposit,196.0,,0,Transient,30.0,0,0
HB-044680,City Hotel,1,66,2023,October,41,9,2023-10-09,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,75.0,0,0
HB-008116,Resort Hotel,1,332,2024,September,37,12,2024-09-12,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,242.0,,0,Transient,117.0,0,0
HB-048246,City Hotel,1,18,2024,March,12,19,2024-03-19,2,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,113.67,0,0
HB-055017,City Hotel,1,137,2024,August,31,2,2024-08-02,2,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,103.09,0,0
HB-099257,City Hotel,0,6,2024,October,41,9,2024-10-09,2,0,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,F,0,No Deposit,132.0,,0,Transient,104.0,0,0
HB-026070,Resort Hotel,0,24,2024,July,29,21,2024-07-21,0,0,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient,0.0,0,0
HB-070751,City Hotel,1,270,2025,June,25,21,2025-06-21,2,4,2,0.0,0,BB,NLD,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,105.0,0,0
HB-103975,City Hotel,0,269,2024,December,52,29,2024-12-29,2,3,1,0.0,0,BB,SWE,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,70.0,0,0
HB-033212,Resort Hotel,0,94,2025,February,7,13,2025-02-13,1,3,2,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,152.0,,0,Transient,62.0,0,0
HB-084518,City Hotel,0,10,2024,February,8,24,2024-02-24,0,4,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,93.0,0,1
HB-020951,Resort Hotel,0,0,2024,February,6,9,2024-02-09,0,5,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,A,A,3,No Deposit,,,0,Transient,50.0,0,0
HB-067032,City Hotel,1,111,2025,April,17,27,2025-04-27,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,0,Transient,120.0,0,0
HB-074358,City Hotel,1,276,2023,July,29,20,2023-07-20,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Contract,62.0,0,0
HB-085388,City Hotel,0,4,2024,March,11,11,2024-03-11,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.0,0,2
HB-116019,City Hotel,0,160,2025,July,28,8,2025-07-08,2,4,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,116.1,0,2
HB-042558,City Hotel,1,3,2023,September,36,7,2023-09-07,1,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,123.5,0,2
HB-033591,Resort Hotel,0,3,2025,February,9,25,2025-02-25,1,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,E,0,No Deposit,250.0,,0,Transient,70.0,0,1
HB-029404,Resort Hotel,0,28,2024,November,48,28,2024-11-28,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,113.0,0,Transient,41.5,0,0
HB-075772,City Hotel,1,323,2023,September,36,5,2023-09-05,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-099766,City Hotel,0,10,2024,October,41,13,2024-10-13,1,3,3,0.0,0,SC,PRT,Direct,Direct,0,0,0,A,D,1,No Deposit,,,0,Transient,149.0,0,1
HB-093086,City Hotel,0,250,2024,July,28,11,2024-07-11,1,5,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,114.75,0,1
HB-119358,City Hotel,0,47,2025,August,35,31,2025-08-31,1,3,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,423.0,,0,Transient,91.02,0,0
HB-051176,City Hotel,1,81,2024,May,20,15,2024-05-15,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,133.0,,0,Transient-Party,90.0,0,0
HB-002513,Resort Hotel,0,69,2023,October,42,19,2023-10-19,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,37.56,0,0
HB-081976,City Hotel,1,115,2024,March,12,20,2024-03-20,2,0,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,41.0,,22,Transient,70.0,0,0
HB-034662,Resort Hotel,0,1,2025,March,14,31,2025-03-31,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,250.0,,0,Transient,65.0,0,1
HB-091762,City Hotel,0,265,2024,June,26,24,2024-06-24,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-061269,City Hotel,1,112,2024,December,49,6,2024-12-06,0,4,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,9.0,,0,Transient,100.3,0,2
HB-029557,Resort Hotel,0,11,2024,October,44,28,2024-10-28,1,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,C,0,No Deposit,,,0,Transient,44.0,1,0
HB-108602,City Hotel,0,38,2025,March,13,26,2025-03-26,2,2,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,71.82,0,0
HB-023808,Resort Hotel,0,33,2025,August,34,23,2025-08-23,0,2,2,0.0,0,BB,PRT,Corporate,Corporate,1,0,9,A,A,0,No Deposit,,154.0,0,Transient,145.0,0,0
HB-109224,City Hotel,0,159,2025,April,14,6,2025-04-06,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,1
HB-046622,City Hotel,0,6,2024,January,2,12,2024-01-12,0,2,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,69.5,0,2
HB-119126,City Hotel,0,181,2025,August,35,27,2025-08-27,2,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-051803,City Hotel,1,86,2024,May,21,26,2024-05-26,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,140.4,0,0
HB-044685,City Hotel,0,66,2023,October,41,9,2023-10-09,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,75.0,0,0
HB-009765,Resort Hotel,1,2,2024,December,1,30,2024-12-30,2,2,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,240.0,,0,Transient,71.25,0,2
HB-109757,City Hotel,0,241,2025,April,16,15,2025-04-15,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,8.0,,0,Transient,109.8,0,1
HB-082231,City Hotel,1,203,2024,June,22,2,2024-06-02,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,41,Transient,65.0,0,0
HB-047335,City Hotel,1,44,2024,February,7,17,2024-02-17,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,44.0,,3,Transient,75.0,0,0
HB-051404,City Hotel,1,322,2024,May,20,19,2024-05-19,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,120,Transient,80.0,0,0
HB-074576,City Hotel,1,353,2023,October,40,5,2023-10-05,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-058121,City Hotel,1,77,2024,October,40,6,2024-10-06,0,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,132.3,0,1
HB-042519,City Hotel,0,55,2023,September,36,6,2023-09-06,2,0,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,75.0,0,0
HB-097938,City Hotel,0,8,2024,September,38,21,2024-09-21,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,D,D,0,No Deposit,,304.0,0,Transient-Party,169.38,0,0
HB-069473,City Hotel,1,106,2025,May,22,31,2025-05-31,0,4,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,83.0,,0,Transient,163.8,0,0
HB-075594,City Hotel,0,257,2023,July,26,1,2023-07-01,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,101.5,0,0
HB-117679,City Hotel,0,0,2025,August,32,7,2025-08-07,1,0,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,1
HB-035513,Resort Hotel,0,75,2025,April,17,22,2025-04-22,2,1,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,78.85,0,0
HB-004978,Resort Hotel,1,212,2024,April,15,11,2024-04-11,2,5,2,0.0,0,HB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,273.0,,0,Transient,67.05,0,0
HB-077195,City Hotel,0,0,2023,September,37,11,2023-09-11,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,114.0,1,0
HB-036879,Resort Hotel,0,280,2025,May,21,25,2025-05-25,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,80.1,0,1
HB-087703,City Hotel,0,161,2024,April,17,22,2024-04-22,1,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,23.0,,0,Transient-Party,71.0,0,0
HB-058647,City Hotel,1,37,2024,October,41,13,2024-10-13,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,95.0,0,0
HB-112519,City Hotel,0,33,2025,May,21,22,2025-05-22,1,2,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,1
HB-079895,City Hotel,0,40,2023,November,44,2,2023-11-02,1,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Transient,60.0,0,0
HB-026648,Resort Hotel,0,42,2024,August,31,1,2024-08-01,1,5,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,2,No Deposit,240.0,,0,Transient,259.0,0,0
HB-013381,Resort Hotel,1,213,2025,August,33,12,2025-08-12,4,10,2,1.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,228.0,0,1
HB-101748,City Hotel,0,19,2024,November,46,13,2024-11-13,2,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,16.0,,0,Transient,80.0,0,0
HB-029561,Resort Hotel,0,1,2024,October,44,30,2024-10-30,1,0,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient-Party,66.0,0,0
HB-067903,City Hotel,1,56,2025,May,19,9,2025-05-09,0,1,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,142.36,0,0
HB-043717,City Hotel,0,34,2023,September,38,23,2023-09-23,0,3,2,0.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,A,B,0,No Deposit,52.0,,33,Transient-Party,224.67,0,0
HB-113088,City Hotel,0,218,2025,May,22,29,2025-05-29,1,3,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,133.65,0,1
HB-036025,Resort Hotel,0,3,2025,May,19,8,2025-05-08,0,0,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,437.0,0,Transient-Party,0.0,0,0
HB-118636,City Hotel,0,103,2025,August,33,17,2025-08-17,2,5,3,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,22.0,,0,Transient,109.65,0,1
HB-078760,City Hotel,0,23,2023,October,41,15,2023-10-15,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-017519,Resort Hotel,0,4,2024,September,39,27,2024-09-27,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,3,A,D,0,No Deposit,,9.0,0,Transient,59.0,0,0
HB-032091,Resort Hotel,0,18,2025,January,3,16,2025-01-16,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,F,1,No Deposit,,154.0,0,Transient,35.0,0,0
HB-066419,City Hotel,1,173,2025,April,16,20,2025-04-20,0,1,2,0.0,0,SC,ISR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,1
HB-083752,City Hotel,0,3,2024,February,6,7,2024-02-07,2,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,72.07,0,1
HB-108532,City Hotel,0,158,2025,March,13,27,2025-03-27,1,1,2,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,95.0,0,1
HB-081220,City Hotel,0,14,2023,December,48,3,2023-12-03,1,3,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,99.0,1,1
HB-104580,City Hotel,0,7,2025,January,2,11,2025-01-11,2,5,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,79.0,,0,Transient,74.31,0,0
HB-025426,Resort Hotel,0,35,2024,June,26,26,2024-06-26,1,0,2,0.0,0,HB,ESP,Direct,Direct,0,0,0,A,A,1,No Deposit,250.0,,0,Transient,159.0,1,0
HB-070404,City Hotel,1,226,2025,June,25,16,2025-06-16,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,105.0,0,0
HB-091623,City Hotel,0,0,2024,June,25,23,2024-06-23,0,1,2,2.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,126.0,0,0
HB-038192,Resort Hotel,0,300,2025,July,27,1,2025-07-01,4,6,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient-Party,129.26,0,1
HB-104618,City Hotel,0,34,2025,January,3,18,2025-01-18,0,1,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,19.0,,0,Transient-Party,75.0,0,0
HB-008117,Resort Hotel,1,24,2024,September,37,12,2024-09-12,1,2,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,173.0,0,1
HB-011360,Resort Hotel,1,210,2025,May,18,4,2025-05-04,2,5,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient,50.4,0,1
HB-048096,City Hotel,0,86,2024,March,11,16,2024-03-16,2,5,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,68.85,0,0
HB-002386,Resort Hotel,0,2,2023,October,41,11,2023-10-11,1,0,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,50.4,0,1
HB-024865,Resort Hotel,0,76,2024,May,22,30,2024-05-30,2,5,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,241.0,,0,Transient,109.45,1,1
HB-000355,Resort Hotel,0,0,2023,July,28,13,2023-07-13,1,1,4,0.0,0,BB,PRT,Direct,Direct,0,0,0,L,H,0,No Deposit,,,0,Transient,150.0,0,0
HB-082048,City Hotel,0,9,2023,December,51,18,2023-12-18,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,95.0,0,0
HB-064153,City Hotel,1,28,2025,March,9,2,2025-03-02,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,95.0,0,0
HB-020103,Resort Hotel,0,60,2024,January,3,16,2024-01-16,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,E,1,No Deposit,6.0,,0,Transient,26.0,0,0
HB-008776,Resort Hotel,0,364,2024,October,41,12,2024-10-12,1,4,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,3,No Deposit,,223.0,0,Transient-Party,66.0,0,0
HB-114178,City Hotel,0,194,2025,June,25,16,2025-06-16,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,90.09,0,1
HB-092862,City Hotel,0,111,2024,July,28,9,2024-07-09,2,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.83,0,2
HB-099256,City Hotel,0,10,2024,October,41,9,2024-10-09,2,0,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,118.0,,0,Transient,90.0,0,0
HB-083465,City Hotel,0,20,2024,January,5,31,2024-01-31,2,1,1,0.0,0,BB,DEU,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,76.0,0,0
HB-049828,City Hotel,1,270,2024,April,16,20,2024-04-20,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,187,Transient-Party,62.8,0,0
HB-112526,City Hotel,0,91,2025,May,21,22,2025-05-22,1,2,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,139.5,0,0
HB-041772,City Hotel,0,9,2023,August,34,23,2023-08-23,2,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,90.0,0,2
HB-052265,City Hotel,1,120,2024,June,22,2,2024-06-02,0,3,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,159.3,0,1
HB-034919,Resort Hotel,0,152,2025,April,14,5,2025-04-05,0,4,1,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,D,1,No Deposit,,223.0,0,Transient-Party,42.0,0,0
HB-092607,City Hotel,0,179,2024,July,27,4,2024-07-04,1,4,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,66.76,0,1
HB-107367,City Hotel,0,46,2025,March,11,10,2025-03-10,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,7.0,,0,Transient,77.93,0,0
HB-038634,Resort Hotel,0,154,2025,July,29,18,2025-07-18,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,143.0,,0,Transient,132.85,0,0
HB-061336,City Hotel,1,517,2024,December,49,8,2024-12-08,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-081656,City Hotel,0,10,2025,April,15,10,2025-04-10,1,0,1,0.0,0,BB,ESP,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,150.0,0,Transient,95.0,0,1
HB-035209,Resort Hotel,0,134,2025,April,15,13,2025-04-13,0,3,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,2,No Deposit,3.0,,0,Transient-Party,79.2,0,1
HB-035008,Resort Hotel,0,151,2025,April,14,4,2025-04-04,2,5,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,D,D,3,No Deposit,,223.0,0,Transient-Party,60.0,0,2
HB-017874,Resort Hotel,0,0,2023,October,43,24,2023-10-24,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,58.0,0,0
HB-021942,Resort Hotel,0,21,2024,March,11,12,2024-03-12,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,56.0,0,1
HB-097826,City Hotel,0,10,2024,September,38,19,2024-09-19,1,1,1,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,149.0,0,2
HB-043686,City Hotel,0,83,2023,September,38,23,2023-09-23,0,2,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-087481,City Hotel,0,25,2024,April,16,17,2024-04-17,2,2,2,1.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.5,0,0
HB-044573,City Hotel,0,210,2023,October,40,8,2023-10-08,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,12.0,,0,Transient-Party,72.75,0,0
HB-016278,Resort Hotel,0,117,2023,August,33,20,2023-08-20,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,120.6,0,2
HB-047826,City Hotel,1,21,2024,March,10,4,2024-03-04,0,1,1,0.0,0,BB,SVN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,85.0,0,0
HB-026793,Resort Hotel,0,84,2024,August,32,8,2024-08-08,1,2,2,1.0,0,BB,ESP,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,218.67,0,1
HB-080257,City Hotel,0,23,2023,November,45,12,2023-11-12,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,90.95,0,1
HB-085778,City Hotel,0,10,2024,March,12,19,2024-03-19,1,1,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,2,No Deposit,9.0,,0,Transient-Party,127.0,0,1
HB-047808,City Hotel,1,39,2024,March,10,4,2024-03-04,1,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,71.1,0,1
HB-083926,City Hotel,0,2,2024,February,6,10,2024-02-10,1,4,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,83.8,1,0
HB-010164,Resort Hotel,1,93,2025,February,8,17,2025-02-17,1,2,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,82.0,0,1
HB-033990,Resort Hotel,0,2,2025,March,11,10,2025-03-10,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,70.0,0,0
HB-028687,Resort Hotel,0,383,2024,October,40,6,2024-10-06,0,3,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,315.0,,0,Transient-Party,48.0,0,0
HB-109194,City Hotel,0,28,2025,April,14,3,2025-04-03,1,4,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,225.4,0,1
HB-024703,Resort Hotel,0,1,2024,May,22,30,2024-05-30,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,79.0,0,0
HB-069782,City Hotel,1,0,2025,June,23,6,2025-06-06,0,2,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,115.0,0,Transient,120.0,0,0
HB-048651,City Hotel,1,72,2024,March,13,26,2024-03-26,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,96.0,0,0
HB-089354,City Hotel,0,4,2024,September,39,27,2024-09-27,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,1,0,2,A,A,0,No Deposit,94.0,,0,Transient,75.0,0,2
HB-103887,City Hotel,0,244,2024,December,52,29,2024-12-29,1,3,3,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,83.0,,0,Transient,176.04,0,1
HB-008070,Resort Hotel,1,18,2024,September,37,9,2024-09-09,2,3,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,0,No Deposit,250.0,,0,Transient,179.0,0,0
HB-097714,City Hotel,0,220,2024,September,38,17,2024-09-17,2,1,1,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,177.0,,0,Transient-Party,128.0,0,0
HB-064204,City Hotel,1,28,2025,March,9,2,2025-03-02,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,95.0,0,0
HB-027649,Resort Hotel,0,176,2024,August,35,27,2024-08-27,3,6,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,250.0,,0,Transient,153.1,0,0
HB-011165,Resort Hotel,1,203,2025,April,17,25,2025-04-25,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,90.0,0,0
HB-080190,City Hotel,1,265,2024,August,31,3,2024-08-03,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,83.0,,0,Contract,72.08,0,1
HB-024101,Resort Hotel,0,31,2024,May,19,8,2024-05-08,2,2,3,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,101.4,0,0
HB-005345,Resort Hotel,1,13,2024,April,17,25,2024-04-25,9,24,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,D,D,0,No Deposit,,110.0,0,Transient,77.0,0,0
HB-110320,City Hotel,0,125,2025,April,17,21,2025-04-21,2,3,1,0.0,0,BB,FRA,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,120.0,0,1
HB-054954,City Hotel,1,4,2024,August,31,1,2024-08-01,1,1,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.0,0,0
HB-085855,City Hotel,0,18,2024,March,12,19,2024-03-19,2,2,3,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,153.0,0,2
HB-057392,City Hotel,1,13,2024,September,39,25,2024-09-25,2,0,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,149.0,0,0
HB-044317,City Hotel,1,89,2023,October,40,3,2023-10-03,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-095389,City Hotel,0,145,2024,August,33,17,2024-08-17,0,2,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,151.2,0,0
HB-115665,City Hotel,0,19,2025,July,28,7,2025-07-07,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,200.0,0,1
HB-041921,City Hotel,0,55,2023,August,34,26,2023-08-26,0,2,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,B,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-040143,City Hotel,1,65,2023,July,28,11,2023-07-11,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,1
HB-111514,City Hotel,0,307,2025,May,19,11,2025-05-11,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,467.0,,0,Transient-Party,89.1,0,0
HB-064038,City Hotel,1,104,2025,February,9,26,2025-02-26,4,7,1,0.0,0,BB,DZA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,1
HB-052997,City Hotel,1,188,2024,June,24,15,2024-06-15,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,39,Transient,130.0,0,0
HB-074145,City Hotel,1,342,2023,September,38,24,2023-09-24,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-004906,Resort Hotel,1,85,2024,April,14,7,2024-04-07,0,3,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,67.0,,0,Transient-Party,64.0,0,0
HB-058401,City Hotel,1,314,2024,October,41,12,2024-10-12,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,68,Transient,75.0,0,0
HB-076371,City Hotel,0,273,2023,July,29,17,2023-07-17,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-118305,City Hotel,0,157,2025,August,33,14,2025-08-14,1,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,80.1,0,1
HB-024067,Resort Hotel,0,56,2024,May,18,5,2024-05-05,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,E,0,No Deposit,243.0,,0,Contract,46.75,0,0
HB-070301,City Hotel,1,201,2025,June,24,14,2025-06-14,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-053720,City Hotel,1,22,2024,June,26,27,2024-06-27,1,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,164.33,0,0
HB-004961,Resort Hotel,0,275,2024,April,15,10,2024-04-10,2,5,2,0.0,0,HB,GBR,Groups,Direct,0,0,0,D,D,0,No Deposit,273.0,,0,Transient-Party,74.45,0,0
HB-069117,City Hotel,1,282,2025,May,21,25,2025-05-25,0,3,2,0.0,0,SC,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,129.0,0,1
HB-010344,Resort Hotel,1,49,2025,February,9,28,2025-02-28,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,332.0,,0,Transient,35.0,0,0
HB-045862,City Hotel,0,98,2023,November,47,23,2023-11-23,1,3,1,0.0,0,BB,JOR,Groups,TA/TO,0,0,0,A,D,1,No Deposit,37.0,,0,Transient-Party,70.0,0,0
HB-043105,City Hotel,0,61,2023,September,37,15,2023-09-15,0,1,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,98.25,1,1
HB-019473,Resort Hotel,0,5,2023,December,51,20,2023-12-20,2,0,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,47.0,1,1
HB-096453,City Hotel,0,64,2024,September,36,2,2024-09-02,0,1,2,1.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,E,1,No Deposit,9.0,,0,Transient,145.5,1,2
HB-049963,City Hotel,1,288,2024,April,16,21,2024-04-21,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-079406,City Hotel,1,137,2024,January,4,27,2024-01-27,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,29.0,,45,Transient,70.0,0,0
HB-010731,Resort Hotel,1,50,2025,March,13,29,2025-03-29,2,4,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,60.0,0,1
HB-014336,Resort Hotel,0,5,2025,March,10,4,2025-03-04,0,1,2,0.0,0,BB,,Online TA,TA/TO,0,0,1,A,A,0,No Deposit,240.0,,0,Transient,60.0,1,1
HB-023420,Resort Hotel,0,49,2024,April,17,23,2024-04-23,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,80.0,0,2
HB-035560,Resort Hotel,0,4,2025,April,17,26,2025-04-26,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,112.0,0,Transient,45.0,0,0
HB-046817,City Hotel,1,151,2024,January,3,19,2024-01-19,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,19.0,,63,Transient-Party,80.0,0,0
HB-065018,City Hotel,1,16,2025,March,12,22,2025-03-22,0,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.0,0,0
HB-107247,City Hotel,0,3,2025,March,10,9,2025-03-09,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,86.4,0,0
HB-083607,City Hotel,0,95,2024,February,6,5,2024-02-05,1,2,2,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,121.0,,0,Transient,72.0,0,0
HB-001369,Resort Hotel,0,41,2023,August,34,27,2023-08-27,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,240.0,,0,Transient,154.0,1,2
HB-065432,City Hotel,1,73,2025,April,14,3,2025-04-03,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,105.0,0,0
HB-078867,City Hotel,0,17,2023,October,42,16,2023-10-16,0,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,G,0,No Deposit,20.0,,17,Transient-Party,48.0,0,0
HB-063637,City Hotel,1,35,2025,February,7,16,2025-02-16,0,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,0
HB-040978,City Hotel,0,39,2023,August,32,10,2023-08-10,1,1,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-060336,City Hotel,1,277,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-060873,City Hotel,1,107,2024,November,48,25,2024-11-25,0,1,2,0.0,0,SC,UKR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,0
HB-070812,City Hotel,1,13,2025,June,26,23,2025-06-23,0,2,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,0
HB-011588,Resort Hotel,1,207,2025,May,21,19,2025-05-19,2,2,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,240.0,,0,Transient,117.0,0,1
HB-050493,City Hotel,1,437,2024,May,18,2,2024-05-02,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-057827,City Hotel,1,275,2024,October,40,1,2024-10-01,2,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,106.2,0,0
HB-075406,City Hotel,1,323,2023,September,36,5,2023-09-05,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-092318,City Hotel,0,140,2024,July,27,2,2024-07-02,1,1,2,2.0,0,BB,USA,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient,88.77,0,1
HB-048116,City Hotel,1,54,2024,March,11,17,2024-03-17,1,3,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.46,0,0
HB-044053,City Hotel,1,92,2023,September,39,30,2023-09-30,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-095210,City Hotel,0,34,2024,August,33,13,2024-08-13,2,1,2,1.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,152.1,0,0
HB-036398,Resort Hotel,0,105,2025,May,20,13,2025-05-13,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,40.95,0,0
HB-036637,Resort Hotel,0,7,2025,May,21,23,2025-05-23,0,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,127.0,,0,Transient-Party,49.6,0,0
HB-072514,City Hotel,1,206,2025,July,31,29,2025-07-29,2,4,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.5,0,1
HB-065366,City Hotel,1,162,2025,April,14,1,2025-04-01,2,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,296.0,,0,Transient-Party,98.0,0,0
HB-052309,City Hotel,1,177,2024,June,23,3,2024-06-03,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,119.0,,0,Transient-Party,100.0,0,0
HB-111620,City Hotel,0,3,2025,May,19,10,2025-05-10,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,211.33,0,1
HB-010216,Resort Hotel,1,25,2025,February,8,20,2025-02-20,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,3
HB-078592,City Hotel,0,5,2024,May,19,9,2024-05-09,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,6,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-080159,City Hotel,1,226,2024,June,24,15,2024-06-15,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Contract,139.0,0,1
HB-003733,Resort Hotel,0,69,2023,December,52,31,2023-12-31,0,3,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,199.73,0,3
HB-094783,City Hotel,0,248,2024,August,31,2,2024-08-02,2,6,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,121.0,,0,Transient,72.25,0,0
HB-005526,Resort Hotel,1,232,2024,May,18,1,2024-05-01,2,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,314.0,,0,Transient,70.4,0,0
HB-075714,City Hotel,1,302,2023,August,33,15,2023-08-15,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-116698,City Hotel,0,423,2025,July,30,22,2025-07-22,1,1,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,95.5,0,0
HB-114406,City Hotel,0,44,2025,June,25,18,2025-06-18,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,123.0,0,0
HB-087127,City Hotel,0,52,2024,April,15,11,2024-04-11,1,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.25,0,1
HB-002907,Resort Hotel,0,0,2023,November,45,6,2023-11-06,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,54.4,0,1
HB-075303,City Hotel,1,304,2023,August,33,17,2023-08-17,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-056290,City Hotel,1,59,2024,September,36,2,2024-09-02,2,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,120.96,0,1
HB-087116,City Hotel,0,58,2024,April,15,12,2024-04-12,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,11.0,,0,Transient,100.48,0,0
HB-097643,City Hotel,0,315,2024,September,38,17,2024-09-17,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,B,0,No Deposit,1.0,,38,Transient-Party,65.0,0,1
HB-006475,Resort Hotel,1,277,2024,June,24,12,2024-06-12,2,2,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-058950,City Hotel,1,195,2024,October,42,18,2024-10-18,0,4,1,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.9,0,2
HB-078454,City Hotel,0,17,2023,October,40,8,2023-10-08,0,2,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,E,0,No Deposit,14.0,,0,Transient,109.0,0,0
HB-024278,Resort Hotel,0,236,2024,May,19,12,2024-05-12,0,3,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,D,0,No Deposit,315.0,,0,Transient-Party,48.0,0,0
HB-022475,Resort Hotel,0,39,2024,March,13,25,2024-03-25,0,2,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,123.0,1,1
HB-009186,Resort Hotel,1,378,2024,November,44,1,2024-11-01,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,248.0,,0,Transient,46.0,0,0
HB-011202,Resort Hotel,1,215,2025,April,18,28,2025-04-28,2,2,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,82.8,0,2
HB-010982,Resort Hotel,1,227,2025,April,15,13,2025-04-13,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,65.04,0,2
HB-111881,City Hotel,0,221,2025,May,20,15,2025-05-15,1,1,2,0.0,0,BB,MEX,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,99.0,0,0
HB-002509,Resort Hotel,0,47,2023,October,42,19,2023-10-19,1,4,2,0.0,0,HB,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,,47,Transient-Party,76.8,0,0
HB-083580,City Hotel,0,0,2024,February,6,7,2024-02-07,0,0,1,0.0,0,BB,PRT,Online TA,TA/TO,1,0,0,A,A,0,No Deposit,9.0,,0,Transient,0.0,0,0
HB-091719,City Hotel,0,265,2024,June,26,24,2024-06-24,0,2,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,6.0,,0,Transient-Party,90.0,0,0
HB-006917,Resort Hotel,1,275,2024,July,28,11,2024-07-11,1,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,85.5,0,0
HB-003825,Resort Hotel,1,15,2024,January,2,13,2024-01-13,0,4,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,39.0,0,2
HB-025903,Resort Hotel,0,27,2024,July,28,11,2024-07-11,1,3,3,1.0,0,BB,IRL,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,224.0,0,0
HB-090910,City Hotel,0,57,2024,June,24,10,2024-06-10,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,90.67,0,1
HB-065713,City Hotel,1,69,2025,April,14,6,2025-04-06,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,Non Refund,,197.0,0,Transient,85.0,0,0
HB-008376,Resort Hotel,1,289,2024,September,39,24,2024-09-24,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,96.0,,0,Transient-Party,64.0,0,0
HB-063853,City Hotel,1,58,2025,February,8,23,2025-02-23,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,132.0,,0,Transient,78.0,0,0
HB-048736,City Hotel,1,24,2024,March,13,29,2024-03-29,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,134.33,0,0
HB-025975,Resort Hotel,0,1,2024,July,29,18,2024-07-18,0,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,0.0,0,0
HB-098416,City Hotel,0,7,2024,September,39,29,2024-09-29,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,135.0,1,1
HB-118935,City Hotel,0,457,2025,August,35,25,2025-08-25,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,122.4,0,1
HB-078563,City Hotel,0,1,2024,January,1,7,2024-01-07,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,40.0,0,Transient-Party,65.0,0,1
HB-085472,City Hotel,0,0,2024,March,11,13,2024-03-13,2,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,95.4,0,1
HB-091780,City Hotel,0,5,2024,June,25,23,2024-06-23,0,3,2,2.0,0,BB,PRT,Direct,Direct,0,0,0,G,G,1,No Deposit,,,0,Transient,193.45,0,2
HB-003004,Resort Hotel,1,40,2023,November,45,11,2023-11-11,0,4,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,281.0,,0,Transient-Party,40.0,0,0
HB-111694,City Hotel,0,128,2025,May,20,13,2025-05-13,0,1,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,193.5,0,1
HB-012157,Resort Hotel,1,8,2025,June,25,16,2025-06-16,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,130.0,0,Transient,75.0,0,0
HB-085413,City Hotel,0,3,2024,March,11,11,2024-03-11,2,2,2,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,85.0,,0,Transient,68.0,0,0
HB-071966,City Hotel,1,156,2025,July,29,16,2025-07-16,2,1,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,0
HB-091401,City Hotel,0,3,2024,June,25,20,2024-06-20,1,0,2,0.0,0,BB,PRT,Complementary,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,0.0,1,3
HB-092375,City Hotel,0,136,2024,June,26,28,2024-06-28,2,5,2,1.0,0,BB,DNK,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,106.25,0,0
HB-090683,City Hotel,0,0,2024,June,23,9,2024-06-09,0,1,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,152.0,,0,Transient,69.01,0,0
HB-046518,City Hotel,0,2,2024,January,1,4,2024-01-04,1,0,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.0,0,1
HB-046156,City Hotel,0,3,2023,December,51,18,2023-12-18,0,2,2,0.0,0,BB,ALB,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,65.89,0,0
HB-099673,City Hotel,0,377,2024,October,42,14,2024-10-14,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-116906,City Hotel,0,9,2025,July,30,24,2025-07-24,1,2,2,1.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,149.48,0,2
HB-007944,Resort Hotel,0,341,2024,September,36,3,2024-09-03,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,B,2,No Deposit,40.0,,0,Contract,87.8,0,1
HB-082630,City Hotel,0,43,2023,December,52,31,2023-12-31,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,B,0,No Deposit,104.0,,0,Transient,118.0,0,0
HB-096292,City Hotel,0,1,2025,August,35,29,2025-08-29,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,6,A,A,0,No Deposit,,40.0,0,Transient,67.0,0,3
HB-031960,Resort Hotel,0,6,2025,January,2,10,2025-01-10,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,181.0,,0,Transient-Party,34.0,1,1
HB-078196,City Hotel,0,18,2023,October,40,2,2023-10-02,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,111.75,0,2
HB-082838,City Hotel,1,68,2024,February,7,17,2024-02-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,37.0,,0,Transient,75.0,0,0
HB-004200,Resort Hotel,1,74,2024,February,9,26,2024-02-26,1,2,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,68.0,,0,Transient,70.0,0,0
HB-082066,City Hotel,0,18,2023,December,51,18,2023-12-18,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,75.0,0,2
HB-094447,City Hotel,0,1,2024,August,31,3,2024-08-03,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,B,0,No Deposit,9.0,,0,Transient,166.0,0,3
HB-016685,Resort Hotel,0,186,2023,September,36,4,2023-09-04,1,2,1,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,E,0,No Deposit,5.0,,0,Transient-Party,52.2,0,1
HB-077532,City Hotel,0,263,2023,September,38,21,2023-09-21,1,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,B,1,No Deposit,21.0,,0,Transient-Party,0.0,0,0
HB-055281,City Hotel,1,213,2024,August,32,9,2024-08-09,2,8,2,0.0,0,BB,ROU,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,80.75,0,1
HB-030806,Resort Hotel,0,80,2024,December,49,2,2024-12-02,0,2,2,0.0,0,BB,IRL,Groups,TA/TO,0,0,0,D,D,0,No Deposit,253.0,,0,Transient-Party,51.8,0,1
HB-031825,Resort Hotel,0,121,2025,January,2,6,2025-01-06,0,2,2,2.0,0,HB,DEU,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,136.0,1,0
HB-118018,City Hotel,0,190,2025,August,32,7,2025-08-07,1,5,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,175.5,0,0
HB-051719,City Hotel,1,158,2024,May,21,24,2024-05-24,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,31,Transient,130.0,0,0
HB-004410,Resort Hotel,1,25,2024,March,11,13,2024-03-13,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,242.0,,0,Transient,46.4,0,1
HB-004017,Resort Hotel,1,111,2024,February,7,12,2024-02-12,0,2,2,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,38.0,,0,Transient,70.0,0,0
HB-043135,City Hotel,0,28,2023,September,37,15,2023-09-15,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,15.0,,0,Transient,84.0,0,0
HB-058126,City Hotel,1,143,2024,October,40,6,2024-10-06,0,3,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,151.2,0,1
HB-007012,Resort Hotel,1,109,2024,July,29,16,2024-07-16,2,5,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,224.0,0,0
HB-000036,Resort Hotel,1,40,2023,July,26,2,2023-07-02,1,3,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,108.8,0,1
HB-110551,City Hotel,0,116,2025,April,17,25,2025-04-25,0,4,1,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,112.5,0,1
HB-066511,City Hotel,1,177,2025,April,17,21,2025-04-21,0,2,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,0
HB-093731,City Hotel,0,186,2024,July,30,22,2024-07-22,2,2,3,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,22.0,,0,Transient,96.9,0,1
HB-098702,City Hotel,0,117,2024,October,40,2,2024-10-02,1,0,1,0.0,0,SC,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,2
HB-094529,City Hotel,0,142,2024,August,31,3,2024-08-03,0,3,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,186.3,1,1
HB-109655,City Hotel,0,107,2025,April,15,11,2025-04-11,0,4,2,0.0,0,SC,TUR,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,103.5,0,1
HB-097979,City Hotel,0,244,2024,September,38,16,2024-09-16,2,5,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,78.54,0,1
HB-062682,City Hotel,1,54,2025,January,3,18,2025-01-18,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,171.0,,0,Transient,65.0,0,0
HB-103939,City Hotel,0,44,2025,January,1,1,2025-01-01,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,65.0,0,1
HB-082050,City Hotel,0,6,2024,March,9,2,2024-03-02,0,2,2,0.0,0,BB,PRT,Corporate,Corporate,1,0,2,A,A,1,No Deposit,,40.0,0,Transient,78.0,1,0
HB-014663,Resort Hotel,0,0,2024,January,1,6,2024-01-06,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,5.0,,0,Transient,30.0,0,0
HB-000708,Resort Hotel,1,88,2023,July,30,26,2023-07-26,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,154.0,0,1
HB-100444,City Hotel,0,2,2024,October,43,27,2024-10-27,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,67.0,1,0
HB-055670,City Hotel,1,108,2024,August,33,18,2024-08-18,2,4,2,0.0,0,BB,ITA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,116.1,0,0
HB-064708,City Hotel,1,92,2025,March,11,15,2025-03-15,0,3,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,85.0,0,0
HB-021049,Resort Hotel,0,0,2024,February,7,16,2024-02-16,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,1,No Deposit,,,0,Transient,40.0,0,0
HB-093034,City Hotel,0,95,2024,July,28,13,2024-07-13,0,3,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,121.5,0,2
HB-064788,City Hotel,1,3,2025,March,11,16,2025-03-16,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.0,0,0
HB-028038,Resort Hotel,0,9,2024,September,38,18,2024-09-18,1,0,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,E,E,0,No Deposit,223.0,,0,Transient-Party,90.0,0,0
HB-054906,City Hotel,1,177,2024,July,31,30,2024-07-30,0,1,1,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.9,0,0
HB-045466,City Hotel,1,64,2023,October,44,30,2023-10-30,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,76.5,0,0
HB-043158,City Hotel,0,76,2023,September,37,16,2023-09-16,0,2,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-091870,City Hotel,0,192,2024,June,26,24,2024-06-24,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,34.0,,0,Transient-Party,95.0,0,0
HB-018148,Resort Hotel,0,1,2023,November,45,7,2023-11-07,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,58.0,0,1
HB-022846,Resort Hotel,0,3,2024,April,15,8,2024-04-08,0,1,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,146.0,,0,Transient-Party,45.0,0,0
HB-016663,Resort Hotel,0,67,2023,September,36,5,2023-09-05,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,113.0,1,1
HB-119256,City Hotel,0,190,2025,August,34,23,2025-08-23,2,7,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,80.1,0,1
HB-030722,Resort Hotel,0,2,2024,December,49,2,2024-12-02,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,330.0,,0,Transient,30.0,0,1
HB-016936,Resort Hotel,0,6,2024,November,47,22,2024-11-22,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,5,A,E,0,No Deposit,,86.0,0,Transient,30.0,0,0
HB-044859,City Hotel,0,36,2023,October,41,13,2023-10-13,0,3,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,26.0,,0,Transient-Party,112.0,0,0
HB-023676,Resort Hotel,0,14,2024,April,18,30,2024-04-30,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,85.0,0,1
HB-044688,City Hotel,0,170,2023,October,41,9,2023-10-09,2,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,10.0,,0,Transient,119.0,0,0
HB-060762,City Hotel,1,95,2024,November,47,20,2024-11-20,2,0,2,0.0,0,BB,HUN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,84.6,0,2
HB-000280,Resort Hotel,0,34,2023,July,28,10,2023-07-10,2,5,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,241.0,,0,Transient,108.83,0,1
HB-011672,Resort Hotel,1,462,2025,May,21,25,2025-05-25,0,3,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,78.0,0,0
HB-007689,Resort Hotel,1,185,2024,August,34,20,2024-08-20,2,5,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,185.0,0,0
HB-062747,City Hotel,1,38,2025,January,4,21,2025-01-21,0,1,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,1
HB-003139,Resort Hotel,0,16,2023,November,46,19,2023-11-19,1,3,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,98.0,1,0
HB-022330,Resort Hotel,0,61,2024,March,12,19,2024-03-19,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,2
HB-046762,City Hotel,0,151,2024,January,3,19,2024-01-19,0,2,1,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,19.0,,63,Transient-Party,71.0,0,0
HB-006236,Resort Hotel,0,0,2024,May,22,30,2024-05-30,0,0,1,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,I,0,No Deposit,,223.0,0,Transient-Party,0.0,0,0
HB-073251,City Hotel,1,203,2025,August,33,17,2025-08-17,0,3,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,B,B,0,No Deposit,14.0,,0,Transient,138.02,0,0
HB-080377,City Hotel,1,34,2023,December,49,8,2023-12-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,0,Transient,90.0,0,0
HB-066197,City Hotel,1,84,2025,April,16,15,2025-04-15,2,1,3,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,231.0,0,0
HB-069257,City Hotel,1,132,2025,May,22,28,2025-05-28,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,28.0,,0,Transient,99.0,0,0
HB-015764,Resort Hotel,1,244,2023,September,35,2,2023-09-02,2,5,2,0.0,0,BB,IRL,Groups,TA/TO,0,1,0,A,A,0,No Deposit,96.0,,0,Transient-Party,8.0,0,0
HB-021634,Resort Hotel,0,53,2024,February,9,26,2024-02-26,2,7,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,115.0,,0,Transient,26.1,0,1
HB-061107,City Hotel,1,315,2024,December,49,2,2024-12-02,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,52.0,0,0
HB-001755,Resort Hotel,0,170,2023,September,37,12,2023-09-12,6,12,2,0.0,0,HB,SWE,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,69.0,,0,Contract,72.25,0,0
HB-026007,Resort Hotel,0,168,2024,July,27,4,2024-07-04,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Contract,91.96,0,1
HB-082461,City Hotel,0,15,2023,December,52,29,2023-12-29,0,2,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Contract,60.0,0,0
HB-074683,City Hotel,1,365,2023,October,42,17,2023-10-17,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-096175,City Hotel,0,56,2024,August,35,26,2024-08-26,2,2,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,162.0,0,2
HB-017681,Resort Hotel,0,287,2023,October,41,15,2023-10-15,1,3,1,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,1,No Deposit,,223.0,0,Transient-Party,37.0,0,0
HB-013135,Resort Hotel,1,176,2025,August,31,1,2025-08-01,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,26.0,,0,Transient,134.86,0,0
HB-040995,City Hotel,0,1,2023,August,32,10,2023-08-10,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,105.0,0,0
HB-071691,City Hotel,1,187,2025,July,28,10,2025-07-10,1,2,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,156.6,0,0
HB-116142,City Hotel,0,193,2025,July,28,12,2025-07-12,0,3,3,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,F,F,2,No Deposit,9.0,,0,Transient,179.1,0,1
HB-057104,City Hotel,1,27,2024,September,38,19,2024-09-19,1,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,287.0,,8,Transient,118.15,0,0
HB-114672,City Hotel,0,103,2025,June,25,21,2025-06-21,0,4,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,97.2,0,1
HB-029846,Resort Hotel,0,2,2024,November,45,6,2024-11-06,1,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,146.0,,0,Transient,52.0,1,0
HB-070750,City Hotel,1,153,2025,June,25,21,2025-06-21,0,4,1,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,A,0,Non Refund,,348.0,0,Transient,110.0,0,0
HB-094661,City Hotel,0,144,2024,August,31,3,2024-08-03,1,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,92.65,0,0
HB-096422,City Hotel,0,5,2024,August,35,28,2024-08-28,2,3,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,D,D,2,No Deposit,14.0,,0,Transient,110.01,0,0
HB-044922,City Hotel,1,180,2023,October,42,16,2023-10-16,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,70.0,0,0
HB-031519,Resort Hotel,0,79,2024,December,52,24,2024-12-24,2,5,2,0.0,0,HB,HUN,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,103.59,1,0
HB-061117,City Hotel,1,315,2024,December,49,2,2024-12-02,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,52.0,0,0
HB-051800,City Hotel,1,323,2024,May,21,26,2024-05-26,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-001401,Resort Hotel,1,42,2023,August,35,28,2023-08-28,1,2,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,1,No Deposit,240.0,,0,Transient,195.0,0,2
HB-027953,Resort Hotel,0,10,2024,September,37,13,2024-09-13,0,2,2,0.0,0,BB,TUR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,121.0,0,0
HB-103715,City Hotel,0,255,2024,December,52,27,2024-12-27,0,3,0,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,K,3,No Deposit,79.0,,0,Transient,20.88,0,0
HB-050978,City Hotel,1,120,2024,May,19,12,2024-05-12,1,3,1,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient-Party,110.59,0,0
HB-046734,City Hotel,0,2,2024,January,3,17,2024-01-17,2,1,2,0.0,0,BB,ITA,Direct,Direct,0,0,0,D,E,1,No Deposit,,,0,Transient,126.33,0,2
HB-028550,Resort Hotel,0,9,2024,October,40,5,2024-10-05,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,121.0,0,1
HB-074007,City Hotel,1,293,2023,August,31,6,2023-08-06,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-066940,City Hotel,1,96,2025,April,17,26,2025-04-26,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,130.0,0,0
HB-107412,City Hotel,0,15,2025,March,10,9,2025-03-09,1,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,104.55,0,0
HB-054624,City Hotel,1,379,2024,July,29,21,2024-07-21,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-064020,City Hotel,1,38,2025,February,9,26,2025-02-26,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,28.0,,0,Transient,75.0,0,0
HB-106004,City Hotel,0,114,2025,February,7,15,2025-02-15,0,4,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,242.0,0,Transient-Party,78.0,0,0
HB-090750,City Hotel,0,104,2024,June,23,7,2024-06-07,0,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,87.67,0,2
HB-111465,City Hotel,0,35,2025,May,19,10,2025-05-10,0,1,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,D,0,No Deposit,39.0,,0,Transient-Party,140.0,0,0
HB-079528,City Hotel,1,16,2023,November,45,11,2023-11-11,0,4,2,0.0,0,BB,PRT,Direct,Direct,0,1,0,D,D,0,No Deposit,14.0,,0,Transient,107.0,0,0
HB-099406,City Hotel,0,32,2024,October,41,7,2024-10-07,2,4,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,185.67,1,0
HB-061699,City Hotel,1,342,2024,December,52,23,2024-12-23,1,2,2,0.0,0,HB,DEU,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,103.5,0,0
HB-036768,Resort Hotel,0,200,2025,May,21,21,2025-05-21,2,5,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,69.0,,0,Transient,49.7,0,1
HB-111310,City Hotel,0,37,2025,May,18,4,2025-05-04,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,179.0,0,2
HB-064585,City Hotel,1,52,2025,March,11,13,2025-03-13,1,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,56.0,,0,Transient,80.0,0,0
HB-031662,Resort Hotel,0,78,2024,December,1,31,2024-12-31,2,1,3,1.0,0,HB,PRT,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,326.33,1,1
HB-066399,City Hotel,1,195,2025,April,16,19,2025-04-19,0,3,2,1.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,133.2,0,0
HB-087149,City Hotel,0,91,2024,April,15,12,2024-04-12,0,3,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient-Party,90.9,0,1
HB-030717,Resort Hotel,0,20,2024,December,48,1,2024-12-01,0,2,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient-Party,61.0,1,1
HB-092325,City Hotel,0,86,2024,July,27,1,2024-07-01,1,2,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,3,No Deposit,83.0,,0,Transient,86.36,0,0
HB-115638,City Hotel,0,261,2025,July,27,5,2025-07-05,0,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,1
HB-103152,City Hotel,0,6,2024,December,50,12,2024-12-12,1,0,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,108.0,0,1
HB-071963,City Hotel,1,41,2025,July,29,16,2025-07-16,2,1,3,0.0,0,BB,IDN,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,233.33,0,0
HB-017382,Resort Hotel,0,21,2023,October,40,7,2023-10-07,0,2,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,47.0,0,1
HB-097425,City Hotel,0,30,2024,September,37,15,2024-09-15,0,1,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.1,0,2
HB-110025,City Hotel,0,0,2025,April,16,17,2025-04-17,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient,117.0,0,2
HB-049700,City Hotel,1,3,2024,April,16,17,2024-04-17,2,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.0,0,0
HB-003368,Resort Hotel,1,45,2023,December,49,5,2023-12-05,2,1,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,38.0,,0,Transient-Party,68.0,0,0
HB-016294,Resort Hotel,0,87,2023,August,33,16,2023-08-16,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,40.0,,0,Contract,132.5,0,0
HB-093104,City Hotel,0,133,2024,July,28,13,2024-07-13,0,4,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient-Party,72.25,0,1
HB-042208,City Hotel,0,18,2023,September,35,2,2023-09-02,0,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,3,No Deposit,7.0,,0,Transient,76.81,0,2
HB-034617,Resort Hotel,0,0,2025,March,13,30,2025-03-30,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient-Party,70.0,0,1
HB-010118,Resort Hotel,1,205,2025,February,7,13,2025-02-13,1,3,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,37.8,0,1
HB-027411,Resort Hotel,0,82,2024,August,34,22,2024-08-22,2,5,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,190.43,0,0
HB-111542,City Hotel,0,92,2025,May,19,9,2025-05-09,0,3,2,0.0,0,BB,SVK,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,7.0,,0,Transient,95.59,0,1
HB-017325,Resort Hotel,0,53,2023,September,39,27,2023-09-27,3,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,74.2,0,1
HB-048998,City Hotel,1,68,2024,April,14,4,2024-04-04,1,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.5,0,0
HB-119210,City Hotel,0,213,2025,August,35,28,2025-08-28,1,3,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,19.0,,0,Transient-Party,104.0,0,0
HB-113301,City Hotel,0,135,2025,June,22,1,2025-06-01,1,3,2,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-096181,City Hotel,0,1,2024,August,35,28,2024-08-28,2,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,149.0,0,1
HB-009304,Resort Hotel,1,135,2024,November,45,10,2024-11-10,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,37.8,0,0
HB-094558,City Hotel,0,31,2024,August,31,4,2024-08-04,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.9,0,2
HB-072513,City Hotel,1,129,2025,July,31,29,2025-07-29,2,4,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.5,0,0
HB-106730,City Hotel,0,27,2025,February,9,26,2025-02-26,2,2,2,0.0,0,HB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,124.53,0,2
HB-018445,Resort Hotel,0,1,2023,November,46,19,2023-11-19,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,,0,Transient,38.0,0,0
HB-097937,City Hotel,0,1,2025,August,32,8,2025-08-08,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,D,0,No Deposit,,40.0,0,Transient,67.0,1,0
HB-109171,City Hotel,0,64,2025,April,14,3,2025-04-03,1,4,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,162.0,0,1
HB-026621,Resort Hotel,0,1,2024,August,32,5,2024-08-05,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,172.0,0,0
HB-012849,Resort Hotel,1,171,2025,July,29,20,2025-07-20,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,5.0,,0,Transient,156.0,0,0
HB-028845,Resort Hotel,0,0,2024,October,41,11,2024-10-11,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,76.0,0,0
HB-000849,Resort Hotel,1,10,2023,August,31,1,2023-08-01,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient-Party,202.0,0,0
HB-014006,Resort Hotel,0,8,2023,November,47,25,2023-11-25,0,1,1,0.0,0,BB,,Corporate,Corporate,0,0,7,A,D,0,No Deposit,,204.0,0,Transient,35.0,0,1
HB-083425,City Hotel,0,5,2024,January,4,28,2024-01-28,1,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,9.0,,0,Transient-Party,108.0,0,0
HB-057303,City Hotel,1,110,2024,September,39,23,2024-09-23,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,149.4,0,0
HB-008198,Resort Hotel,1,170,2024,September,38,16,2024-09-16,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,171.0,,0,Transient,90.0,0,0
HB-080317,City Hotel,1,33,2023,December,49,9,2023-12-09,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,44.0,,0,Transient,110.0,0,0
HB-002479,Resort Hotel,0,7,2023,October,42,19,2023-10-19,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,8.0,,0,Transient-Party,37.0,0,0
HB-037681,Resort Hotel,0,27,2025,June,26,24,2025-06-24,1,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,1,No Deposit,250.0,,0,Transient,160.0,0,1
HB-091235,City Hotel,0,95,2024,June,24,16,2024-06-16,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,137.1,0,1
HB-030733,Resort Hotel,0,23,2024,December,49,2,2024-12-02,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,75.0,0,0
HB-020817,Resort Hotel,0,2,2024,February,5,3,2024-02-03,2,5,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,49.0,0,1
HB-002277,Resort Hotel,0,71,2023,October,40,8,2023-10-08,0,3,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Contract,71.0,1,2
HB-090028,City Hotel,0,56,2024,May,22,30,2024-05-30,1,1,1,0.0,0,BB,BEL,Groups,TA/TO,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,120.0,0,0
HB-105870,City Hotel,0,87,2025,February,7,13,2025-02-13,1,3,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,147.9,0,0
HB-033971,Resort Hotel,0,0,2025,March,10,8,2025-03-08,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,146.0,,0,Group,32.0,0,0
HB-030361,Resort Hotel,0,123,2024,November,47,19,2024-11-19,0,1,2,0.0,0,BB,POL,Direct,Direct,0,0,0,A,D,1,No Deposit,250.0,,0,Transient,34.02,0,0
HB-061368,City Hotel,1,81,2024,December,49,8,2024-12-08,0,3,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,1
HB-112453,City Hotel,0,93,2025,May,21,21,2025-05-21,2,1,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,153.0,0,2
HB-038607,Resort Hotel,0,61,2025,July,28,10,2025-07-10,4,10,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,531.0,,0,Transient,171.53,0,2
HB-049096,City Hotel,1,55,2024,April,14,6,2024-04-06,0,1,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,0.0,0,0
HB-069262,City Hotel,1,84,2025,May,22,28,2025-05-28,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,153.0,0,0
HB-012825,Resort Hotel,1,227,2025,July,29,18,2025-07-18,0,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,151.25,0,3
HB-068774,City Hotel,1,66,2025,May,21,20,2025-05-20,2,1,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,180.0,0,1
HB-083831,City Hotel,0,13,2024,February,7,12,2024-02-12,0,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.0,0,1
HB-044178,City Hotel,0,164,2023,October,40,2,2023-10-02,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,19.0,,0,Transient-Party,100.0,0,0
HB-092354,City Hotel,0,100,2024,July,27,3,2024-07-03,2,0,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,146.7,0,2
HB-034731,Resort Hotel,0,92,2025,April,14,1,2025-04-01,1,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-036511,Resort Hotel,0,118,2025,May,21,22,2025-05-22,1,0,2,0.0,0,BB,NOR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,251.0,,0,Transient-Party,62.0,0,0
HB-026844,Resort Hotel,0,91,2024,August,32,8,2024-08-08,1,4,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,215.0,0,1
HB-023934,Resort Hotel,0,159,2024,May,18,5,2024-05-05,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,52.2,0,2
HB-097289,City Hotel,0,346,2024,September,37,13,2024-09-13,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-009195,Resort Hotel,1,378,2024,November,44,1,2024-11-01,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,C,1,Non Refund,248.0,,0,Transient,46.0,0,0
HB-055825,City Hotel,1,27,2024,August,34,22,2024-08-22,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,151.0,0,1
HB-103613,City Hotel,0,104,2024,December,52,25,2024-12-25,2,1,0,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,B,A,1,No Deposit,9.0,,0,Transient,91.6,0,2
HB-099593,City Hotel,0,53,2024,October,42,14,2024-10-14,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,77.0,,0,Transient-Party,120.0,0,0
HB-041715,City Hotel,0,0,2023,August,34,22,2023-08-22,0,1,2,2.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,130.0,0,2
HB-050061,City Hotel,1,142,2024,April,17,22,2024-04-22,2,3,2,0.0,0,BB,POL,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,103.0,0,0
HB-068520,City Hotel,1,105,2025,May,21,19,2025-05-19,0,1,2,0.0,0,SC,JEY,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-032293,Resort Hotel,0,0,2025,January,4,21,2025-01-21,0,1,1,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,40.0,0,0
HB-087976,City Hotel,0,13,2024,April,17,26,2024-04-26,0,3,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,58.0,,0,Transient-Party,96.0,0,0
HB-089140,City Hotel,0,4,2024,May,21,23,2024-05-23,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-094248,City Hotel,0,3,2024,August,31,1,2024-08-01,1,0,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,201.0,0,1
HB-083757,City Hotel,0,9,2024,February,6,10,2024-02-10,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,86.0,0,1
HB-116354,City Hotel,0,2,2025,July,29,16,2025-07-16,2,0,2,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,0.0,0,1
HB-095846,City Hotel,0,31,2024,August,34,22,2024-08-22,1,2,2,0.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,83.0,,0,Transient,147.72,0,0
HB-052556,City Hotel,1,56,2024,June,23,8,2024-06-08,0,1,2,0.0,0,BB,PRT,Offline TA/TO,Corporate,0,0,0,A,A,0,No Deposit,191.0,,0,Transient-Party,120.0,0,0
HB-037664,Resort Hotel,0,136,2025,June,25,17,2025-06-17,2,6,3,0.0,0,HB,PRT,Direct,Direct,0,0,0,E,E,2,No Deposit,250.0,,0,Transient,213.71,1,1
HB-098189,City Hotel,0,336,2024,September,38,21,2024-09-21,1,4,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,78.0,0,0
HB-098565,City Hotel,0,328,2024,September,40,30,2024-09-30,0,2,2,0.0,0,BB,ITA,Groups,TA/TO,0,0,0,A,B,0,No Deposit,1.0,,38,Transient-Party,65.0,0,1
HB-088198,City Hotel,0,11,2024,April,18,30,2024-04-30,1,1,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,225.0,0,2
HB-015740,Resort Hotel,0,50,2023,July,30,26,2023-07-26,2,4,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,207.0,1,0
HB-066684,City Hotel,1,135,2025,April,17,23,2025-04-23,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,171.0,,0,Transient,90.0,0,0
HB-075325,City Hotel,1,311,2023,August,34,24,2023-08-24,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-116611,City Hotel,0,6,2025,July,29,18,2025-07-18,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,159.5,0,1
HB-032102,Resort Hotel,0,4,2025,January,3,14,2025-01-14,2,1,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,240.0,,0,Transient,42.0,0,1
HB-054596,City Hotel,0,201,2024,July,29,21,2024-07-21,0,1,0,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,B,A,0,No Deposit,9.0,,0,Transient-Party,86.5,0,0
HB-016886,Resort Hotel,0,222,2023,September,37,14,2023-09-14,1,1,2,0.0,0,HB,ESP,Groups,TA/TO,0,0,0,A,D,0,No Deposit,68.0,,0,Transient,80.0,0,0
HB-031638,Resort Hotel,0,102,2024,December,1,30,2024-12-30,1,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,159.0,0,3
HB-009934,Resort Hotel,1,27,2025,January,5,27,2025-01-27,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,48.0,0,1
HB-079921,City Hotel,0,17,2023,November,45,6,2023-11-06,0,1,1,0.0,0,SC,AUT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Contract,104.0,1,1
HB-054075,City Hotel,1,245,2024,July,27,6,2024-07-06,2,4,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,110.0,0,0
HB-046532,City Hotel,0,28,2024,January,1,4,2024-01-04,1,3,3,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,159.0,,0,Transient-Party,122.0,0,1
HB-105275,City Hotel,0,2,2025,February,6,3,2025-02-03,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,80.0,0,0
HB-113844,City Hotel,0,43,2025,June,23,8,2025-06-08,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,156.0,0,1
HB-045906,City Hotel,0,84,2023,November,48,27,2023-11-27,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,0.0,0,0
HB-015520,Resort Hotel,0,1,2023,July,29,21,2023-07-21,0,3,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,177.0,0,0
HB-094179,City Hotel,0,89,2024,July,30,26,2024-07-26,1,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,121.8,0,1
HB-022848,Resort Hotel,0,3,2024,April,15,8,2024-04-08,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,C,0,No Deposit,146.0,,0,Transient-Party,54.0,0,0
HB-021835,Resort Hotel,0,2,2024,March,10,9,2024-03-09,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,77.33,1,1
HB-118428,City Hotel,0,32,2025,August,34,18,2025-08-18,0,2,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,180.0,0,1
HB-117737,City Hotel,0,209,2025,August,32,6,2025-08-06,2,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,130.5,0,1
HB-012191,Resort Hotel,1,155,2025,June,25,17,2025-06-17,2,4,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,180.0,0,0
HB-094350,City Hotel,0,3,2024,August,31,3,2024-08-03,0,1,3,0.0,0,SC,BRA,Online TA,Direct,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,174.0,0,1
HB-080006,City Hotel,1,25,2023,November,48,27,2023-11-27,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,B,B,0,No Deposit,9.0,,0,Contract,87.0,0,0
HB-012992,Resort Hotel,1,17,2025,July,30,26,2025-07-26,2,4,1,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,221.0,0,0
HB-003141,Resort Hotel,1,121,2023,November,46,19,2023-11-19,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,32.4,0,2
HB-052508,City Hotel,1,23,2024,June,23,7,2024-06-07,2,10,1,0.0,0,BB,AGO,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,175.17,0,0
HB-113431,City Hotel,0,27,2025,June,23,3,2025-06-03,2,2,2,0.0,0,SC,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,138.5,0,0
HB-100669,City Hotel,0,240,2024,October,43,27,2024-10-27,1,3,2,0.0,0,BB,DNK,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient-Party,90.95,0,2
HB-002975,Resort Hotel,0,3,2023,November,45,9,2023-11-09,1,0,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,49.0,0,2
HB-075250,City Hotel,1,297,2023,August,32,10,2023-08-10,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-036128,Resort Hotel,0,213,2025,May,18,4,2025-05-04,2,5,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,8.0,,0,Transient,43.2,0,1
HB-009348,Resort Hotel,1,185,2024,November,46,17,2024-11-17,0,1,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,55.8,0,3
HB-027692,Resort Hotel,0,95,2025,May,19,6,2025-05-06,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,1,0,1,D,D,0,No Deposit,40.0,,0,Contract,50.85,0,1
HB-043324,City Hotel,0,0,2023,September,38,18,2023-09-18,0,1,2,0.0,0,BB,ISR,Direct,TA/TO,0,0,0,A,E,0,No Deposit,,,0,Transient,152.0,0,1
HB-005127,Resort Hotel,0,185,2024,April,16,18,2024-04-18,1,1,1,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,1,No Deposit,298.0,,0,Transient-Party,54.5,0,0
HB-057989,City Hotel,1,7,2024,October,40,4,2024-10-04,0,5,1,0.0,0,SC,LTU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,2
HB-030487,Resort Hotel,0,25,2024,November,47,18,2024-11-18,2,5,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,69.0,1,1
HB-033756,Resort Hotel,0,7,2025,March,9,2,2025-03-02,2,3,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,2,No Deposit,,223.0,0,Transient-Party,44.0,1,0
HB-110676,City Hotel,0,0,2025,April,18,30,2025-04-30,1,0,2,0.0,0,SC,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,160.0,0,0
HB-059694,City Hotel,1,65,2024,November,44,1,2024-11-01,0,1,1,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,4
HB-035742,Resort Hotel,0,27,2025,April,16,20,2025-04-20,3,8,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,50.85,0,0
HB-028011,Resort Hotel,0,251,2024,September,37,13,2024-09-13,0,5,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,242.0,,0,Transient,107.3,0,1
HB-056247,City Hotel,0,238,2024,September,35,1,2024-09-01,2,4,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.07,0,1
HB-090600,City Hotel,0,118,2024,June,23,6,2024-06-06,1,2,1,0.0,0,BB,TUR,Offline TA/TO,Corporate,0,0,0,A,A,2,No Deposit,191.0,,0,Transient-Party,110.0,0,0
HB-062014,City Hotel,1,24,2024,December,1,30,2024-12-30,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,260.0,0,0
HB-016652,Resort Hotel,0,4,2023,September,36,4,2023-09-04,0,2,1,0.0,0,BB,ITA,Direct,Direct,0,0,0,A,E,0,No Deposit,,,0,Transient-Party,66.0,0,1
HB-025988,Resort Hotel,0,227,2024,July,28,10,2024-07-10,3,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,96.0,,0,Transient,131.6,0,1
HB-034925,Resort Hotel,0,152,2025,April,14,5,2025-04-05,0,4,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,1,No Deposit,,223.0,0,Transient-Party,48.0,0,0
HB-053754,City Hotel,1,41,2024,June,26,28,2024-06-28,2,6,2,1.0,0,BB,POL,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,150.3,0,0
HB-118258,City Hotel,0,288,2025,August,33,17,2025-08-17,1,3,2,1.0,1,HB,ITA,Direct,Direct,0,0,0,E,E,3,No Deposit,14.0,,0,Transient,44.0,0,3
HB-117046,City Hotel,0,89,2025,July,30,27,2025-07-27,0,2,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,7.0,,0,Transient,96.0,0,1
HB-092736,City Hotel,0,184,2024,July,28,10,2024-07-10,1,0,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.3,0,1
HB-051764,City Hotel,1,158,2024,May,21,24,2024-05-24,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,31,Transient,130.0,0,0
HB-035582,Resort Hotel,0,93,2025,April,17,22,2025-04-22,2,4,1,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,40.0,,0,Contract,51.2,0,0
HB-030601,Resort Hotel,0,2,2025,January,2,7,2025-01-07,1,1,1,0.0,0,BB,PRT,Direct,Direct,1,0,1,A,D,0,No Deposit,250.0,,0,Group,39.0,0,1
HB-073115,City Hotel,1,507,2025,August,33,15,2025-08-15,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-040304,City Hotel,1,20,2023,July,29,22,2023-07-22,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-013544,Resort Hotel,1,108,2025,August,34,19,2025-08-19,2,4,3,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,340.0,0,1
HB-065386,City Hotel,1,208,2025,April,14,1,2025-04-01,4,10,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,1
HB-026986,Resort Hotel,0,161,2024,August,32,9,2024-08-09,2,5,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,182.0,0,1
HB-113666,City Hotel,0,27,2025,June,23,7,2025-06-07,0,4,2,0.0,0,BB,ITA,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,153.0,0,0
HB-055965,City Hotel,1,412,2024,August,34,25,2024-08-25,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-003527,Resort Hotel,1,57,2023,December,51,22,2023-12-22,0,5,3,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,6.0,,0,Transient,54.68,0,1
HB-048463,City Hotel,1,58,2024,March,12,24,2024-03-24,0,1,2,0.0,0,SC,COL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.2,0,0
HB-111329,City Hotel,0,10,2025,May,19,6,2025-05-06,2,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,170.0,0,3
HB-117189,City Hotel,0,5,2025,July,31,29,2025-07-29,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,164.5,0,2
HB-057975,City Hotel,1,50,2024,October,40,4,2024-10-04,0,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.8,0,0
HB-005667,Resort Hotel,1,163,2024,May,19,9,2024-05-09,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,65.0,0,1
HB-055321,City Hotel,1,178,2024,August,32,10,2024-08-10,0,4,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.25,0,0
HB-059285,City Hotel,1,26,2024,October,43,26,2024-10-26,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,83.0,,0,Transient,99.2,0,0
HB-021495,Resort Hotel,0,0,2024,February,9,29,2024-02-29,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,1,No Deposit,,290.0,0,Transient,30.0,0,0
HB-046491,City Hotel,0,31,2024,January,1,3,2024-01-03,1,0,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,B,B,4,No Deposit,9.0,,0,Transient-Party,71.52,0,1
HB-085110,City Hotel,0,28,2024,March,10,7,2024-03-07,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient-Party,87.0,0,1
HB-044402,City Hotel,0,88,2023,October,40,5,2023-10-05,1,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,26.0,,77,Transient-Party,112.2,0,0
HB-057790,City Hotel,1,0,2024,October,40,1,2024-10-01,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,180.0,0,0
HB-074174,City Hotel,1,349,2023,October,39,1,2023-10-01,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-076849,City Hotel,0,204,2023,August,32,12,2023-08-12,0,4,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,76.5,0,3
HB-100241,City Hotel,0,386,2024,October,43,23,2024-10-23,2,0,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-043225,City Hotel,1,155,2023,September,37,16,2023-09-16,2,4,3,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,13.0,,0,Transient,126.48,0,0
HB-010615,Resort Hotel,1,12,2025,March,12,19,2025-03-19,2,5,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient-Party,34.0,0,0
HB-073451,City Hotel,1,41,2025,August,34,22,2025-08-22,0,3,2,1.0,0,SC,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,152.67,0,0
HB-095965,City Hotel,0,189,2024,August,34,20,2024-08-20,2,5,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,109.77,0,2
HB-097395,City Hotel,0,48,2024,September,37,14,2024-09-14,0,2,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,281.0,,0,Transient-Party,130.0,0,0
HB-083949,City Hotel,0,20,2024,February,7,13,2024-02-13,2,1,3,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,D,E,1,No Deposit,9.0,,0,Transient,187.0,0,2
HB-086617,City Hotel,0,56,2024,April,14,4,2024-04-04,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-051025,City Hotel,0,129,2024,May,20,13,2024-05-13,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,121.5,0,1
HB-098647,City Hotel,0,6,2024,October,40,1,2024-10-01,1,1,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,86.0,,0,Transient,152.0,0,0
HB-067199,City Hotel,1,22,2025,April,18,29,2025-04-29,2,1,2,0.0,0,SC,RUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,133.0,0,1
HB-065611,City Hotel,1,62,2025,April,14,6,2025-04-06,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,135.0,0,0
HB-011921,Resort Hotel,1,320,2025,June,23,3,2025-06-03,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,74.25,0,2
HB-083032,City Hotel,0,2,2024,January,2,14,2024-01-14,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient-Party,66.0,0,0
HB-014393,Resort Hotel,0,238,2025,July,29,17,2025-07-17,2,5,2,0.0,0,FB,PRT,Offline TA/TO,TA/TO,0,0,1,E,E,0,No Deposit,6.0,,0,Transient,185.6,1,2
HB-115410,City Hotel,0,405,2025,July,27,4,2025-07-04,0,2,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,91.5,0,0
HB-062940,City Hotel,1,61,2025,January,4,25,2025-01-25,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,326.0,,0,Transient,80.0,0,0
HB-089795,City Hotel,0,5,2024,May,21,24,2024-05-24,0,2,1,0.0,0,BB,COL,Corporate,Corporate,0,0,0,A,A,1,No Deposit,,78.0,0,Transient-Party,100.0,0,0
HB-058931,City Hotel,1,218,2024,October,42,17,2024-10-17,1,4,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.95,0,0
HB-050751,City Hotel,0,138,2024,May,19,7,2024-05-07,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.3,1,1
HB-045311,City Hotel,0,69,2023,October,43,25,2023-10-25,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,D,0,No Deposit,37.0,,58,Transient-Party,85.67,0,0
HB-081107,City Hotel,1,82,2024,February,5,2,2024-02-02,0,5,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,21,Transient,96.0,0,0
HB-091101,City Hotel,0,256,2024,June,24,15,2024-06-15,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-073405,City Hotel,1,123,2025,August,34,20,2025-08-20,2,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,155.0,0,1
HB-047752,City Hotel,1,33,2024,March,9,2,2024-03-02,0,4,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,73.1,0,0
HB-023015,Resort Hotel,0,1,2024,April,15,12,2024-04-12,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,330.0,,0,Transient,67.5,0,0
HB-040345,City Hotel,1,20,2023,July,29,22,2023-07-22,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-061940,City Hotel,1,52,2024,December,52,29,2024-12-29,0,2,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,148.91,0,2
HB-113383,City Hotel,0,434,2025,June,23,3,2025-06-03,2,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,0.0,0,0
HB-008677,Resort Hotel,1,131,2024,October,41,9,2024-10-09,2,1,2,0.0,0,BB,PRT,Groups,Corporate,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,55.0,0,0
HB-047725,City Hotel,1,54,2024,March,9,1,2024-03-01,0,4,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,47.43,0,0
HB-097300,City Hotel,0,346,2024,September,37,13,2024-09-13,0,2,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,6.0,,0,Transient-Party,90.0,0,0
HB-049834,City Hotel,1,265,2024,April,16,20,2024-04-20,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,30.0,,0,Transient,101.0,0,0
HB-057634,City Hotel,1,447,2024,September,39,29,2024-09-29,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-030109,Resort Hotel,0,34,2024,November,46,11,2024-11-11,2,2,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,147.0,,0,Transient,60.48,0,0
HB-001131,Resort Hotel,1,77,2023,August,33,15,2023-08-15,2,4,3,0.0,0,FB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,175.0,,0,Transient,209.2,0,0
HB-054436,City Hotel,1,5,2024,July,29,16,2024-07-16,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,151.0,0,0
HB-087851,City Hotel,0,58,2024,April,17,24,2024-04-24,2,1,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,81.08,0,0
HB-073919,City Hotel,1,265,2023,July,27,9,2023-07-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Contract,62.0,0,0
HB-030276,Resort Hotel,0,23,2024,November,46,12,2024-11-12,2,5,2,0.0,0,HB,IRL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,175.0,,0,Transient,57.39,0,0
HB-060712,City Hotel,1,25,2024,November,47,18,2024-11-18,2,3,2,1.0,0,HB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,146.7,0,2
HB-111868,City Hotel,0,168,2025,May,20,14,2025-05-14,2,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,0
HB-012172,Resort Hotel,1,60,2025,June,25,16,2025-06-16,2,5,2,1.0,0,HB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,167.0,0,1
HB-069944,City Hotel,1,169,2025,June,23,8,2025-06-08,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,170.0,0,0
HB-098935,City Hotel,0,37,2024,October,40,5,2024-10-05,0,2,3,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,9.0,,0,Transient,158.4,0,2
HB-002322,Resort Hotel,1,78,2023,October,41,9,2023-10-09,1,2,2,0.0,0,FB,ESP,Groups,TA/TO,0,0,0,A,A,0,Non Refund,134.0,,0,Transient,92.0,0,0
HB-038279,Resort Hotel,0,166,2025,July,27,4,2025-07-04,2,8,3,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,241.0,,0,Transient,180.02,0,1
HB-071229,City Hotel,1,135,2025,June,27,30,2025-06-30,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,30.0,,0,Transient,130.0,0,0
HB-095847,City Hotel,0,51,2024,August,34,22,2024-08-22,1,2,2,1.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,9.0,,0,Transient,152.1,0,1
HB-068170,City Hotel,1,71,2025,May,20,14,2025-05-14,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,115.2,0,0
HB-064012,City Hotel,1,17,2025,February,9,26,2025-02-26,2,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,D,D,0,No Deposit,30.0,,0,Transient-Party,75.0,0,0
HB-012228,Resort Hotel,1,57,2025,June,25,18,2025-06-18,2,5,2,1.0,0,HB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,167.0,0,1
HB-080743,City Hotel,1,34,2023,November,47,23,2023-11-23,1,2,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,102.6,0,0
HB-033077,Resort Hotel,0,5,2025,February,7,11,2025-02-11,2,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,60.0,0,2
HB-098610,City Hotel,0,130,2024,September,39,29,2024-09-29,0,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.5,0,2
HB-071181,City Hotel,1,121,2025,June,26,29,2025-06-29,0,1,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,230.0,0,0
HB-017123,Resort Hotel,1,277,2023,October,40,6,2023-10-06,2,5,2,0.0,0,HB,GBR,Groups,Direct,0,1,0,D,D,0,No Deposit,273.0,,0,Transient-Party,67.31,0,0
HB-059030,City Hotel,1,95,2024,October,42,20,2024-10-20,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,132.3,0,0
HB-080186,City Hotel,0,3,2025,February,8,20,2025-02-20,1,1,1,0.0,0,BB,FRA,Direct,Direct,1,0,3,A,A,0,No Deposit,,91.0,0,Transient,80.0,0,2
HB-060130,City Hotel,1,50,2024,November,45,5,2024-11-05,2,1,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,83.0,,0,Transient,114.09,0,0
HB-078090,City Hotel,0,4,2023,September,39,30,2023-09-30,0,3,2,0.0,0,SC,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,139.33,0,1
HB-019245,Resort Hotel,0,0,2023,December,49,10,2023-12-10,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,E,0,No Deposit,,144.0,0,Transient,25.0,0,0
HB-048703,City Hotel,1,70,2024,March,13,27,2024-03-27,2,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,11.0,,0,Transient,86.4,0,0
HB-020414,Resort Hotel,0,3,2024,January,4,28,2024-01-28,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,,0,Transient,39.0,0,0
HB-016327,Resort Hotel,0,87,2023,August,33,17,2023-08-17,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,196.0,,0,Transient,132.87,0,0
HB-081663,City Hotel,0,37,2023,December,50,14,2023-12-14,1,2,2,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,121.0,,0,Transient,70.0,0,0
HB-065699,City Hotel,1,69,2025,April,14,6,2025-04-06,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,Non Refund,,197.0,0,Transient,85.0,0,0
HB-046975,City Hotel,1,10,2024,January,5,30,2024-01-30,2,6,2,0.0,0,SC,TUR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.75,0,0
HB-062407,City Hotel,1,205,2025,January,3,13,2025-01-13,0,1,2,0.0,0,BB,AUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.0,0,1
HB-094442,City Hotel,0,187,2024,July,30,28,2024-07-28,2,5,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,80.75,1,0
HB-066680,City Hotel,1,11,2025,April,17,23,2025-04-23,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,102.6,0,0
HB-071804,City Hotel,1,229,2025,July,28,12,2025-07-12,1,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-060681,City Hotel,1,101,2024,November,47,18,2024-11-18,0,2,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.0,0,2
HB-013259,Resort Hotel,1,190,2025,August,32,6,2025-08-06,2,4,2,0.0,0,HB,MAR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,202.0,0,0
HB-085532,City Hotel,0,32,2024,March,11,13,2024-03-13,2,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-052496,City Hotel,1,213,2024,June,23,7,2024-06-07,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,62,Transient,130.0,0,0
HB-109130,City Hotel,0,69,2025,April,14,3,2025-04-03,1,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,0
HB-042454,City Hotel,0,55,2023,September,36,6,2023-09-06,2,0,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,75.0,0,0
HB-106057,City Hotel,0,23,2025,February,8,17,2025-02-17,1,2,1,0.0,0,BB,EST,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient,75.0,0,0
HB-018335,Resort Hotel,0,82,2024,February,6,7,2024-02-07,2,0,2,0.0,0,Undefined,PRT,Groups,TA/TO,1,0,0,A,A,0,No Deposit,67.0,,0,Transient-Party,72.0,0,0
HB-083638,City Hotel,0,28,2024,February,6,5,2024-02-05,2,2,0,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient-Party,73.39,0,1
HB-115251,City Hotel,0,4,2025,July,27,3,2025-07-03,1,0,1,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.0,0,1
HB-033333,Resort Hotel,0,31,2025,February,8,19,2025-02-19,1,0,2,0.0,2,BB,PRT,Online TA,TA/TO,0,0,0,A,C,2,No Deposit,240.0,,0,Transient-Party,50.0,1,2
HB-103348,City Hotel,0,32,2024,December,51,17,2024-12-17,2,2,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,66.59,1,1
HB-041364,City Hotel,0,40,2023,August,33,15,2023-08-15,2,2,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-030095,Resort Hotel,0,1,2024,November,46,13,2024-11-13,1,0,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,65.0,0,2
HB-015028,Resort Hotel,0,191,2024,April,17,22,2024-04-22,1,2,2,0.0,0,Undefined,PRT,Offline TA/TO,Direct,1,0,1,A,A,1,No Deposit,,,0,Transient-Party,85.33,0,0
HB-046069,City Hotel,1,198,2023,December,49,5,2023-12-05,2,1,2,0.0,0,HB,ESP,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,90.0,0,0
HB-091670,City Hotel,0,115,2024,June,25,19,2024-06-19,2,3,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,101.66,0,1
HB-061287,City Hotel,1,27,2024,December,49,7,2024-12-07,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,113.0,0,2
HB-079390,City Hotel,0,11,2023,October,43,23,2023-10-23,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,26.0,,0,Transient-Party,88.5,0,0
HB-081506,City Hotel,0,11,2023,December,50,11,2023-12-11,0,2,2,0.0,0,BB,PRT,Complementary,Direct,0,0,0,B,B,0,No Deposit,,,0,Transient,0.0,0,1
HB-106890,City Hotel,0,8,2025,March,9,2,2025-03-02,0,3,1,0.0,0,BB,LKA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.0,0,1
HB-076256,City Hotel,1,221,2023,October,40,3,2023-10-03,2,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,86.0,0,0
HB-012232,Resort Hotel,1,340,2025,June,25,18,2025-06-18,4,10,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Contract,56.7,0,0
HB-069635,City Hotel,1,271,2025,June,23,3,2025-06-03,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient,90.0,0,0
HB-034606,Resort Hotel,0,119,2025,March,13,26,2025-03-26,2,3,2,0.0,0,HB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,63.14,0,1
HB-071374,City Hotel,1,465,2025,July,27,4,2025-07-04,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-028573,Resort Hotel,0,0,2024,October,40,3,2024-10-03,1,2,2,0.0,0,BB,USA,Direct,Direct,0,0,0,E,E,1,No Deposit,,,0,Transient,124.0,1,0
HB-015811,Resort Hotel,0,3,2023,July,30,30,2023-07-30,1,3,2,2.0,0,BB,ESP,Direct,Direct,0,0,0,C,C,1,No Deposit,250.0,,0,Transient,188.0,0,2
HB-079160,City Hotel,0,1,2023,October,42,22,2023-10-22,0,0,1,0.0,0,BB,PRT,Complementary,Direct,0,0,0,D,A,0,No Deposit,,45.0,0,Transient,0.0,0,0
HB-073083,City Hotel,1,36,2025,August,33,14,2025-08-14,1,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,0
HB-087599,City Hotel,0,3,2024,April,16,21,2024-04-21,0,1,1,0.0,0,BB,ITA,Aviation,Corporate,0,0,0,D,G,0,No Deposit,,153.0,0,Transient,110.0,0,0
HB-114845,City Hotel,0,231,2025,June,26,27,2025-06-27,0,1,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,262.0,,0,Transient,89.1,0,0
HB-067378,City Hotel,1,7,2025,May,18,3,2025-05-03,0,1,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,150.0,0,1
HB-070020,City Hotel,1,169,2025,June,23,8,2025-06-08,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,170.0,0,0
HB-027246,Resort Hotel,0,14,2024,August,33,18,2024-08-18,2,4,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,15.0,,0,Transient,193.87,0,0
HB-107047,City Hotel,0,7,2025,March,10,6,2025-03-06,1,0,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,78.4,0,0
HB-107879,City Hotel,0,21,2025,March,11,16,2025-03-16,1,3,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,21.0,,0,Transient-Party,70.0,0,0
HB-106180,City Hotel,0,23,2025,February,8,18,2025-02-18,2,3,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,94.86,0,0
HB-096489,City Hotel,0,42,2024,August,35,30,2024-08-30,0,4,3,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,142.2,0,2
HB-014755,Resort Hotel,1,259,2023,September,37,17,2023-09-17,0,3,1,0.0,0,BB,GBR,Groups,Corporate,0,1,0,A,A,0,Non Refund,,223.0,0,Transient,33.3,0,0
HB-032455,Resort Hotel,0,0,2025,January,5,27,2025-01-27,1,2,2,0.0,0,BB,PRT,Direct,TA/TO,1,0,0,E,E,0,No Deposit,,,0,Transient,70.0,0,2
HB-047125,City Hotel,0,33,2024,February,6,8,2024-02-08,1,4,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,75.23,0,2
HB-075547,City Hotel,0,257,2023,July,26,1,2023-07-01,0,2,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient,80.0,0,0
HB-050391,City Hotel,0,117,2024,April,18,29,2024-04-29,2,2,2,0.0,0,BB,BGR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,95.2,0,1
HB-001604,Resort Hotel,1,155,2023,September,36,5,2023-09-05,3,6,2,2.0,0,HB,PRT,Online TA,TA/TO,0,0,0,G,G,1,No Deposit,240.0,,0,Transient,197.0,0,2
HB-026843,Resort Hotel,0,91,2024,August,32,8,2024-08-08,1,4,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,215.0,0,1
HB-015984,Resort Hotel,0,96,2023,August,31,3,2023-08-03,2,5,2,0.0,0,HB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,186.0,0,0
HB-052552,City Hotel,1,26,2024,June,23,8,2024-06-08,0,1,2,0.0,0,BB,PRT,Offline TA/TO,Corporate,0,0,0,A,A,0,No Deposit,191.0,,0,Transient-Party,120.0,0,0
HB-034484,Resort Hotel,0,43,2025,March,13,25,2025-03-25,0,1,2,1.0,0,HB,ESP,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient-Party,112.0,0,0
HB-082881,City Hotel,1,68,2024,February,7,17,2024-02-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,37.0,,0,Transient,75.0,0,0
HB-100522,City Hotel,0,197,2024,October,44,28,2024-10-28,0,1,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,168.3,0,1
HB-033013,Resort Hotel,0,19,2025,February,6,9,2025-02-09,0,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,171.0,,0,Transient,50.0,0,0
HB-093005,City Hotel,0,52,2024,July,28,13,2024-07-13,0,2,3,0.0,0,BB,FIN,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,176.7,1,1
HB-016882,Resort Hotel,0,222,2023,September,37,14,2023-09-14,1,1,2,0.0,0,HB,ESP,Groups,TA/TO,0,0,0,A,F,0,No Deposit,68.0,,0,Transient-Party,80.0,0,0
HB-103587,City Hotel,0,74,2024,December,52,25,2024-12-25,2,1,4,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,7.0,,0,Transient,174.42,0,2
HB-117774,City Hotel,0,82,2025,August,31,3,2025-08-03,2,4,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,112.5,0,3
HB-106678,City Hotel,0,67,2025,February,9,26,2025-02-26,2,1,1,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,73.46,0,2
HB-025195,Resort Hotel,0,297,2024,June,24,11,2024-06-11,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,92.9,0,1
HB-086770,City Hotel,0,83,2024,April,14,7,2024-04-07,0,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.3,0,1
HB-106186,City Hotel,0,21,2025,February,8,20,2025-02-20,1,2,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,190.0,0,1
HB-030230,Resort Hotel,0,39,2024,November,46,11,2024-11-11,2,4,1,0.0,0,BB,IRL,Direct,Direct,0,0,0,A,A,4,No Deposit,250.0,,0,Transient,29.41,0,0
HB-000646,Resort Hotel,1,105,2023,July,30,24,2023-07-24,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,6.0,,0,Transient,132.5,0,0
HB-083026,City Hotel,0,48,2024,January,2,8,2024-01-08,2,5,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,84.45,0,1
HB-067869,City Hotel,1,95,2025,May,19,8,2025-05-08,1,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,0
HB-027583,Resort Hotel,0,33,2024,August,35,28,2024-08-28,2,4,2,0.0,0,BB,CHE,Direct,Direct,0,0,0,C,C,0,No Deposit,250.0,,0,Transient,220.33,0,0
HB-112413,City Hotel,0,84,2025,May,21,22,2025-05-22,1,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,144.0,0,0
HB-064877,City Hotel,1,7,2025,March,12,18,2025-03-18,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,82.69,0,2
HB-071145,City Hotel,1,215,2025,June,26,28,2025-06-28,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-052208,City Hotel,1,330,2024,June,22,2,2024-06-02,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-061958,City Hotel,1,193,2024,December,52,29,2024-12-29,0,3,2,1.0,0,BB,BRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,160.2,0,0
HB-060582,City Hotel,1,116,2024,November,46,16,2024-11-16,0,3,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,122.4,0,1
HB-049095,City Hotel,1,55,2024,April,14,6,2024-04-06,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,80.0,0,0
HB-051872,City Hotel,0,316,2024,May,21,26,2024-05-26,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,110.0,0,0
HB-019048,Resort Hotel,0,0,2024,January,2,12,2024-01-12,0,1,2,0.0,0,BB,PRT,Direct,Direct,1,0,2,A,A,0,No Deposit,,,0,Transient,43.0,1,0
HB-111984,City Hotel,0,69,2025,May,19,10,2025-05-10,2,7,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,E,E,2,No Deposit,9.0,,0,Transient,186.0,0,3
HB-009952,Resort Hotel,1,33,2025,January,5,28,2025-01-28,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-118417,City Hotel,0,103,2025,August,33,17,2025-08-17,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,89.1,0,1
HB-062211,City Hotel,1,130,2025,January,1,4,2025-01-04,2,8,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,0
HB-025076,Resort Hotel,0,97,2024,May,22,30,2024-05-30,4,10,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,96.9,0,2
HB-036693,Resort Hotel,0,13,2025,May,21,21,2025-05-21,2,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient-Party,83.2,1,1
HB-064530,City Hotel,1,25,2025,March,11,12,2025-03-12,1,0,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,90.0,0,0
HB-114143,City Hotel,0,0,2025,June,25,17,2025-06-17,0,1,1,0.0,0,BB,PRT,Aviation,Corporate,0,0,0,A,D,0,No Deposit,,153.0,0,Transient,95.0,0,0
HB-044284,City Hotel,0,198,2023,October,40,3,2023-10-03,1,1,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,60.0,0,0
HB-061498,City Hotel,1,524,2024,December,50,15,2024-12-15,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-012340,Resort Hotel,1,103,2025,June,26,25,2025-06-25,2,1,2,0.0,0,BB,USA,Direct,Direct,0,0,0,G,G,2,No Deposit,250.0,,0,Transient,209.0,0,1
HB-082807,City Hotel,1,68,2024,February,7,17,2024-02-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,37.0,,0,Transient,75.0,0,0
HB-087722,City Hotel,0,0,2024,April,17,23,2024-04-23,1,1,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,123.0,1,0
HB-097107,City Hotel,0,69,2024,September,36,8,2024-09-08,1,3,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,168.3,0,2
HB-113256,City Hotel,0,211,2025,June,22,1,2025-06-01,1,3,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient-Party,107.1,0,0
HB-072468,City Hotel,1,35,2025,July,31,29,2025-07-29,1,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,1
HB-109225,City Hotel,0,73,2025,April,15,7,2025-04-07,0,2,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,220.0,0,0
HB-098634,City Hotel,0,182,2024,September,40,30,2024-09-30,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.9,0,2
HB-013487,Resort Hotel,1,40,2025,August,33,17,2025-08-17,1,3,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,242.0,,0,Transient,289.8,0,1
HB-060014,City Hotel,1,45,2024,November,45,4,2024-11-04,1,2,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.0,0,2
HB-119166,City Hotel,0,100,2025,August,35,27,2025-08-27,2,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,85.0,,0,Transient,89.1,0,1
HB-085486,City Hotel,0,59,2024,March,11,13,2024-03-13,2,1,2,0.0,0,SC,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,67.5,0,0
HB-100696,City Hotel,0,1,2024,October,44,28,2024-10-28,1,2,2,2.0,0,BB,DZA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,7.0,,0,Transient,211.76,0,1
HB-117971,City Hotel,0,296,2025,August,32,6,2025-08-06,2,5,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,262.0,,0,Transient,80.1,0,0
HB-067875,City Hotel,1,212,2025,May,19,8,2025-05-08,2,5,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,111.34,0,0
HB-099893,City Hotel,0,159,2024,October,42,16,2024-10-16,2,2,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,108.0,0,0
HB-051801,City Hotel,1,323,2024,May,21,26,2024-05-26,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-067139,City Hotel,1,117,2025,April,18,29,2025-04-29,0,1,1,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,153.0,0,0
HB-027145,Resort Hotel,0,18,2024,August,34,20,2024-08-20,0,1,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,D,F,0,No Deposit,250.0,,0,Transient,248.1,0,1
HB-115367,City Hotel,0,188,2025,June,26,28,2025-06-28,2,5,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,83.96,0,1
HB-109369,City Hotel,0,124,2025,April,15,8,2025-04-08,1,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,1
HB-014701,Resort Hotel,1,259,2023,September,37,17,2023-09-17,0,3,2,0.0,0,BB,GBR,Groups,Corporate,0,1,0,A,A,0,Non Refund,,223.0,0,Transient,40.05,0,0
HB-064784,City Hotel,1,176,2025,March,11,16,2025-03-16,0,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,1
HB-011481,Resort Hotel,1,140,2025,May,19,10,2025-05-10,2,5,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,96.0,,0,Transient-Party,48.0,0,0
HB-086913,City Hotel,0,91,2024,April,15,9,2024-04-09,1,1,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,58.9,0,1
HB-094730,City Hotel,0,22,2024,August,32,7,2024-08-07,2,0,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,139.0,0,0
HB-031607,Resort Hotel,0,196,2024,December,1,30,2024-12-30,1,2,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,308.0,0,Transient-Party,114.0,0,0
HB-037741,Resort Hotel,0,6,2025,June,26,25,2025-06-25,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,241.0,,0,Transient,100.8,0,1
HB-079493,City Hotel,0,2,2024,January,2,14,2024-01-14,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,2,A,A,0,No Deposit,,40.0,0,Transient-Party,66.0,0,0
HB-116566,City Hotel,0,244,2025,July,29,15,2025-07-15,2,5,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,1
HB-031253,Resort Hotel,0,1,2024,December,51,19,2024-12-19,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,59.0,1,1
HB-036773,Resort Hotel,0,107,2025,May,21,21,2025-05-21,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,52.85,0,1
HB-046336,City Hotel,1,140,2023,December,52,29,2023-12-29,0,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,70.0,0,0
HB-089622,City Hotel,0,14,2024,May,21,23,2024-05-23,1,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,87.0,,0,Transient,109.25,0,1
HB-079823,City Hotel,0,14,2023,November,44,2,2023-11-02,1,3,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Contract,108.45,1,1
HB-110512,City Hotel,0,1,2025,April,17,23,2025-04-23,2,3,1,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,190.0,0,1
HB-009850,Resort Hotel,1,129,2025,January,2,12,2025-01-12,2,3,2,0.0,0,HB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,47.8,0,0
HB-025035,Resort Hotel,0,14,2024,June,23,8,2024-06-08,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,124.0,0,1
HB-094116,City Hotel,0,301,2024,July,31,30,2024-07-30,1,1,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-075784,City Hotel,1,323,2023,September,36,5,2023-09-05,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-050731,City Hotel,1,48,2024,May,19,6,2024-05-06,1,2,3,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,159.3,0,0
HB-087309,City Hotel,0,88,2024,April,15,14,2024-04-14,1,3,2,0.0,0,BB,ITA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient-Party,80.75,0,0
HB-030800,Resort Hotel,0,80,2024,December,49,2,2024-12-02,0,2,2,0.0,0,BB,IRL,Groups,TA/TO,0,0,0,D,D,0,No Deposit,253.0,,0,Transient-Party,51.8,0,1
HB-091889,City Hotel,0,24,2024,June,26,26,2024-06-26,1,0,3,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,147.0,0,1
HB-072672,City Hotel,1,155,2025,August,31,2,2025-08-02,2,8,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,122.5,0,0
HB-069837,City Hotel,1,134,2025,June,23,7,2025-06-07,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,110.0,0,0
HB-046022,City Hotel,0,3,2023,December,49,5,2023-12-05,2,1,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,B,1,No Deposit,9.0,,0,Transient-Party,104.0,1,1
HB-053487,City Hotel,1,44,2024,June,25,22,2024-06-22,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,1
HB-059343,City Hotel,1,74,2024,October,43,27,2024-10-27,0,2,1,0.0,0,SC,AGO,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.1,0,3
HB-017295,Resort Hotel,0,51,2023,October,39,1,2023-10-01,0,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,74.4,1,1
HB-051779,City Hotel,0,169,2024,May,21,25,2024-05-25,0,4,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,123.25,0,0
HB-021491,Resort Hotel,0,2,2025,February,7,15,2025-02-15,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,D,0,No Deposit,,195.0,0,Transient,35.0,0,0
HB-042076,City Hotel,0,6,2023,August,35,30,2023-08-30,2,2,1,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,95.5,0,2
HB-097824,City Hotel,0,15,2024,September,38,20,2024-09-20,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,139.0,0,1
HB-087355,City Hotel,0,6,2024,April,16,16,2024-04-16,1,1,3,0.0,0,BB,BGD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,152.0,0,1
HB-023431,Resort Hotel,0,9,2024,April,17,23,2024-04-23,1,1,1,1.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,81.0,0,2
HB-062089,City Hotel,1,42,2025,January,1,1,2025-01-01,2,1,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.67,0,0
HB-074498,City Hotel,1,325,2023,September,36,7,2023-09-07,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-033023,Resort Hotel,0,2,2025,February,7,10,2025-02-10,0,2,2,0.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient,60.0,0,1
HB-059400,City Hotel,1,199,2024,October,44,28,2024-10-28,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,29.0,,0,Transient-Party,95.0,0,0
HB-045909,City Hotel,0,84,2023,November,48,27,2023-11-27,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,64.0,0,0
HB-098121,City Hotel,0,141,2024,September,39,23,2024-09-23,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,5,No Deposit,9.0,,0,Transient,128.8,0,1
HB-048652,City Hotel,1,72,2024,March,13,26,2024-03-26,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,96.0,0,0
HB-108739,City Hotel,0,35,2025,March,13,29,2025-03-29,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,111.33,0,0
HB-093840,City Hotel,0,46,2024,July,30,27,2024-07-27,0,1,2,1.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,9.0,,0,Transient,152.1,0,2
HB-117905,City Hotel,0,479,2025,August,32,9,2025-08-09,0,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,1
HB-016012,Resort Hotel,0,83,2023,August,32,7,2023-08-07,2,2,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,175.0,,0,Transient-Party,119.2,1,2
HB-000111,Resort Hotel,0,86,2023,July,27,4,2023-07-04,2,5,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,97.0,0,2
HB-072210,City Hotel,1,65,2025,July,30,23,2025-07-23,2,3,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,9.0,,0,Transient,223.6,0,0
HB-115266,City Hotel,0,462,2025,July,27,1,2025-07-01,2,1,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,1
HB-089562,City Hotel,0,86,2024,May,21,20,2024-05-20,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,65.0,0,1
HB-055995,City Hotel,1,148,2024,August,35,26,2024-08-26,1,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.9,0,0
HB-024121,Resort Hotel,0,89,2024,May,18,5,2024-05-05,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,43.76,0,0
HB-057654,City Hotel,1,160,2024,September,39,29,2024-09-29,1,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,131.4,0,1
HB-102850,City Hotel,0,0,2024,December,49,7,2024-12-07,0,1,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,1
HB-064419,City Hotel,1,241,2025,March,10,9,2025-03-09,0,3,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,0
HB-071380,City Hotel,1,6,2025,July,27,4,2025-07-04,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,80.0,0,0
HB-026394,Resort Hotel,0,1,2024,July,31,30,2024-07-30,0,1,2,0.0,0,BB,USA,Direct,TA/TO,0,0,0,D,D,0,No Deposit,,,0,Transient,221.0,0,1
HB-041506,City Hotel,1,3,2023,August,33,17,2023-08-17,1,2,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,38.0,0,Transient,120.0,0,0
HB-040160,City Hotel,0,96,2023,July,28,11,2023-07-11,2,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-062803,City Hotel,1,59,2025,January,4,23,2025-01-23,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,326.0,,0,Transient,80.0,0,0
HB-109620,City Hotel,0,4,2025,April,15,11,2025-04-11,0,3,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,122.67,0,1
HB-115754,City Hotel,0,153,2025,July,28,8,2025-07-08,1,1,2,1.0,0,BB,BRA,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,154.0,0,2
HB-061798,City Hotel,1,246,2024,December,52,26,2024-12-26,1,3,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,104.55,0,0
HB-105987,City Hotel,0,70,2025,February,7,15,2025-02-15,0,4,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,242.0,0,Transient-Party,78.0,0,0
HB-053983,City Hotel,1,264,2024,July,27,4,2024-07-04,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Contract,95.4,0,1
HB-022826,Resort Hotel,0,0,2024,April,14,3,2024-04-03,2,3,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,66.0,0,0
HB-060771,City Hotel,1,217,2024,November,47,20,2024-11-20,2,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,63.75,0,2
HB-070587,City Hotel,1,99,2025,June,25,19,2025-06-19,1,2,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,126.0,0,0
HB-091007,City Hotel,0,159,2024,December,51,22,2024-12-22,4,8,2,0.0,0,BB,BEL,Online TA,TA/TO,1,0,1,F,F,1,No Deposit,9.0,,0,Transient,146.2,0,2
HB-107721,City Hotel,0,70,2025,March,11,13,2025-03-13,1,3,1,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,74.8,0,0
HB-005509,Resort Hotel,1,187,2024,April,18,30,2024-04-30,2,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,44.1,0,0
HB-039769,Resort Hotel,0,199,2025,August,34,18,2025-08-18,3,7,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,132.85,0,0
HB-056613,City Hotel,1,266,2024,September,37,9,2024-09-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,32,Transient,105.0,0,0
HB-114260,City Hotel,0,155,2025,June,24,15,2025-06-15,1,3,1,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,137.25,0,2
HB-028207,Resort Hotel,0,233,2024,September,37,11,2024-09-11,4,10,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Contract,90.9,0,0
HB-077757,City Hotel,0,1,2023,September,38,22,2023-09-22,0,4,1,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,B,0,No Deposit,1.0,,0,Transient-Party,170.0,0,0
HB-113418,City Hotel,0,24,2025,June,23,4,2025-06-04,2,1,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,170.0,0,1
HB-042764,City Hotel,0,16,2023,September,36,9,2023-09-09,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,116.75,0,3
HB-034268,Resort Hotel,0,88,2025,March,11,11,2025-03-11,2,5,2,0.0,0,BB,DEU,Groups,TA/TO,0,0,0,A,C,2,No Deposit,177.0,,0,Transient-Party,34.0,0,0
HB-097860,City Hotel,0,27,2024,September,38,20,2024-09-20,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,288.0,,0,Transient-Party,95.0,0,0
HB-029493,Resort Hotel,0,20,2024,October,43,24,2024-10-24,1,5,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,241.0,,0,Transient,96.13,0,1
HB-043829,City Hotel,1,87,2023,September,39,25,2023-09-25,2,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-093673,City Hotel,0,74,2024,July,30,22,2024-07-22,1,2,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,142.5,0,0
HB-067543,City Hotel,1,143,2025,May,18,4,2025-05-04,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,151.0,,0,Transient,100.0,0,0
HB-070959,City Hotel,1,272,2025,June,26,26,2025-06-26,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,323.0,,59,Transient,115.0,0,0
HB-031338,Resort Hotel,0,0,2024,December,52,23,2024-12-23,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,56.0,0,1
HB-003458,Resort Hotel,0,66,2023,December,50,12,2023-12-12,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,115.0,,0,Transient,56.7,0,0
HB-090616,City Hotel,0,0,2024,June,23,8,2024-06-08,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,92.35,0,1
HB-090827,City Hotel,0,133,2024,June,23,9,2024-06-09,0,3,1,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,121.5,0,1
HB-102069,City Hotel,0,215,2024,November,47,21,2024-11-21,1,1,1,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,0,No Deposit,,233.0,0,Transient,75.0,0,0
HB-058610,City Hotel,1,37,2024,October,41,13,2024-10-13,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,95.0,0,0
HB-015763,Resort Hotel,1,244,2023,September,35,2,2023-09-02,2,5,2,0.0,0,BB,IRL,Groups,TA/TO,0,1,0,A,A,0,No Deposit,96.0,,0,Transient-Party,8.0,0,0
HB-052515,City Hotel,1,56,2024,June,23,8,2024-06-08,0,1,2,0.0,0,BB,PRT,Offline TA/TO,Corporate,0,0,0,A,A,0,No Deposit,191.0,,0,Transient-Party,120.0,0,0
HB-008238,Resort Hotel,1,171,2024,September,38,19,2024-09-19,1,5,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,92.33,0,2
HB-020724,Resort Hotel,0,21,2024,February,5,4,2024-02-04,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient-Party,48.0,0,2
HB-057201,City Hotel,1,117,2024,September,38,20,2024-09-20,0,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,143.1,0,0
HB-062906,City Hotel,1,53,2025,January,4,24,2025-01-24,0,4,3,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,117.81,0,0
HB-095036,City Hotel,0,111,2024,August,33,12,2024-08-12,0,2,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,1
HB-051407,City Hotel,1,322,2024,May,20,19,2024-05-19,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,120,Transient,80.0,0,0
HB-106488,City Hotel,0,134,2025,February,9,25,2025-02-25,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,75.0,0,0
HB-054865,City Hotel,1,386,2024,July,30,28,2024-07-28,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-078685,City Hotel,0,31,2023,October,41,11,2023-10-11,2,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Contract,94.5,0,2
HB-064606,City Hotel,1,105,2025,March,11,13,2025-03-13,1,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,56.0,,53,Transient,80.0,0,0
HB-037744,Resort Hotel,0,20,2025,June,26,25,2025-06-25,2,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,145.0,0,1
HB-044119,City Hotel,1,27,2023,September,39,30,2023-09-30,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,64.0,,21,Transient,108.0,0,0
HB-109519,City Hotel,0,60,2025,April,15,9,2025-04-09,2,2,2,1.0,0,BB,BGR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,128.0,0,1
HB-028484,Resort Hotel,0,342,2024,September,39,29,2024-09-29,2,4,1,0.0,0,BB,IRL,Groups,TA/TO,0,0,0,A,A,0,No Deposit,201.0,,0,Transient-Party,36.0,0,0
HB-002248,Resort Hotel,0,175,2023,October,40,7,2023-10-07,2,5,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,A,E,0,No Deposit,6.0,,0,Transient,41.6,1,0
HB-099066,City Hotel,0,88,2024,October,41,7,2024-10-07,0,2,1,0.0,0,BB,POL,Corporate,Corporate,0,0,0,A,A,1,No Deposit,193.0,,0,Transient-Party,80.0,0,0
HB-048686,City Hotel,1,5,2024,March,13,26,2024-03-26,2,5,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,146.0,0,0
HB-010899,Resort Hotel,1,124,2025,April,15,9,2025-04-09,2,5,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,492.0,,0,Transient,80.0,0,0
HB-107969,City Hotel,0,51,2025,March,12,17,2025-03-17,2,2,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-076523,City Hotel,1,195,2023,September,37,17,2023-09-17,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,20.0,,0,Transient,48.0,0,0
HB-119325,City Hotel,0,8,2025,August,35,31,2025-08-31,0,3,2,0.0,0,BB,ITA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,119.4,0,0
HB-111457,City Hotel,0,19,2025,May,19,6,2025-05-06,2,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,21.0,,0,Transient,140.0,0,0
HB-036530,Resort Hotel,0,303,2025,May,19,11,2025-05-11,4,8,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Contract,70.95,0,0
HB-071188,City Hotel,1,97,2025,June,26,29,2025-06-29,0,2,2,2.0,0,BB,NOR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,230.0,0,0
HB-090675,City Hotel,0,118,2024,June,23,6,2024-06-06,1,3,1,0.0,0,BB,RUS,Offline TA/TO,Corporate,0,0,0,A,A,1,No Deposit,191.0,,0,Transient-Party,110.0,0,0
HB-009121,Resort Hotel,1,42,2024,October,44,28,2024-10-28,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,C,1,No Deposit,240.0,,0,Transient,57.55,0,0
HB-059642,City Hotel,1,75,2024,October,44,30,2024-10-30,2,0,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,105.0,0,0
HB-031334,Resort Hotel,0,77,2024,December,52,23,2024-12-23,0,1,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,314.0,,0,Transient,44.64,0,0
HB-022721,Resort Hotel,0,169,2024,March,13,31,2024-03-31,1,3,2,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,A,0,Refundable,,223.0,0,Transient-Party,66.0,0,0
HB-008313,Resort Hotel,0,397,2024,September,38,21,2024-09-21,0,4,1,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,96.0,,0,Transient-Party,60.25,0,0
HB-107543,City Hotel,0,4,2025,March,11,14,2025-03-14,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,D,D,0,No Deposit,,444.0,0,Transient,95.0,0,0
HB-024910,Resort Hotel,0,136,2024,May,22,30,2024-05-30,3,7,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,64.78,0,1
HB-085121,City Hotel,0,5,2024,March,10,8,2024-03-08,0,2,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,12.0,,0,Transient-Party,1.0,0,0
HB-015108,Resort Hotel,1,214,2023,October,40,3,2023-10-03,1,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,208.0,,0,Transient,34.0,0,0
HB-103739,City Hotel,0,17,2024,December,52,29,2024-12-29,0,2,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,1
HB-014261,Resort Hotel,0,12,2023,October,42,18,2023-10-18,2,2,1,0.0,0,BB,,Corporate,Corporate,0,1,2,A,E,0,No Deposit,,292.0,0,Transient,48.0,1,0
HB-084612,City Hotel,0,32,2024,February,9,27,2024-02-27,1,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,78.5,0,2
HB-025377,Resort Hotel,0,156,2024,June,24,11,2024-06-11,4,10,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,143.0,,0,Transient,88.7,0,0
HB-029966,Resort Hotel,0,21,2024,November,45,8,2024-11-08,0,3,1,0.0,0,BB,PRT,Offline TA/TO,Corporate,0,0,0,A,A,2,No Deposit,146.0,,0,Transient,33.0,1,0
HB-040480,City Hotel,1,25,2023,July,30,27,2023-07-27,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-058885,City Hotel,1,605,2024,October,42,17,2024-10-17,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-072860,City Hotel,1,86,2025,August,32,8,2025-08-08,0,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,145.0,0,2
HB-113348,City Hotel,0,26,2025,June,23,2,2025-06-02,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,171.1,0,1
HB-095745,City Hotel,0,110,2024,August,34,22,2024-08-22,1,1,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,153.4,0,0
HB-104774,City Hotel,0,29,2025,January,3,18,2025-01-18,0,4,1,0.0,0,BB,SWE,Groups,TA/TO,0,0,0,A,A,1,No Deposit,171.0,,0,Transient-Party,65.0,0,0
HB-049344,City Hotel,1,37,2024,April,15,11,2024-04-11,1,1,2,0.0,0,BB,ARE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.3,0,0
HB-040577,City Hotel,0,117,2023,August,31,1,2023-08-01,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-040777,City Hotel,0,1,2023,August,32,7,2023-08-07,0,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,80.0,0,1
HB-071541,City Hotel,1,167,2025,July,28,7,2025-07-07,0,2,2,0.0,0,SC,DNK,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,0
HB-007266,Resort Hotel,1,133,2024,July,31,31,2024-07-31,2,5,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,197.71,0,0
HB-091236,City Hotel,0,150,2024,June,24,16,2024-06-16,0,3,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,90.0,0,1
HB-057046,City Hotel,1,19,2024,September,38,17,2024-09-17,0,1,2,0.0,0,BB,CHE,Direct,Direct,0,0,0,A,A,2,No Deposit,14.0,,0,Transient,178.0,0,3
HB-078369,City Hotel,0,1,2023,November,46,19,2023-11-19,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,1,A,A,0,No Deposit,,40.0,0,Transient-Party,65.0,0,0
HB-029196,Resort Hotel,0,386,2024,October,42,20,2024-10-20,0,3,1,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,2,No Deposit,,,0,Transient-Party,40.0,0,0
HB-113334,City Hotel,0,434,2025,June,23,3,2025-06-03,2,1,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,2
HB-033378,Resort Hotel,0,15,2025,February,8,19,2025-02-19,2,0,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,467.0,,0,Transient,35.28,0,0
HB-085693,City Hotel,0,115,2024,March,12,18,2024-03-18,0,2,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,70.0,0,0
HB-094596,City Hotel,0,66,2024,August,32,6,2024-08-06,0,1,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,207.9,0,1
HB-010641,Resort Hotel,1,214,2025,March,13,24,2025-03-24,3,7,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,D,D,0,No Deposit,273.0,,0,Transient-Party,28.0,0,0
HB-000619,Resort Hotel,0,16,2023,July,29,23,2023-07-23,0,0,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,C,I,0,No Deposit,242.0,,0,Transient,0.0,0,0
HB-073294,City Hotel,1,29,2025,August,34,18,2025-08-18,0,2,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,7.0,,0,Transient,254.96,0,1
HB-011692,Resort Hotel,1,162,2025,May,21,25,2025-05-25,2,5,2,2.0,0,BB,PRT,Groups,TA/TO,0,0,0,C,C,0,Refundable,,223.0,0,Transient-Party,99.0,0,0
HB-017281,Resort Hotel,0,272,2023,September,39,30,2023-09-30,0,3,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,C,0,No Deposit,256.0,,0,Transient-Party,73.0,0,0
HB-018311,Resort Hotel,0,12,2023,November,46,15,2023-11-15,2,0,2,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,0.0,0,0
HB-115178,City Hotel,0,198,2025,July,27,2,2025-07-02,1,0,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,G,G,1,No Deposit,83.0,,0,Transient,191.2,0,0
HB-046173,City Hotel,0,132,2023,December,51,20,2023-12-20,2,2,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,55.63,0,0
HB-066262,City Hotel,1,99,2025,April,16,15,2025-04-15,2,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,58.0,,0,Transient-Party,105.0,0,0
HB-052894,City Hotel,1,71,2024,June,24,14,2024-06-14,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,120.0,0,0
HB-015008,Resort Hotel,1,244,2023,September,35,3,2023-09-03,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,19,0,A,A,0,Non Refund,,,0,Transient,36.0,0,0
HB-009490,Resort Hotel,1,183,2024,December,49,3,2024-12-03,2,1,2,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,38.0,,0,Transient,72.0,0,0
HB-006530,Resort Hotel,1,249,2024,June,24,15,2024-06-15,2,8,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,72.0,0,1
HB-004806,Resort Hotel,0,144,2024,April,14,1,2024-04-01,2,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,177.0,,0,Transient-Party,41.4,0,0
HB-007581,Resort Hotel,1,54,2024,August,33,15,2024-08-15,1,5,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,221.0,0,0
HB-034058,Resort Hotel,0,171,2025,March,10,5,2025-03-05,2,5,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,E,E,0,No Deposit,298.0,,0,Transient-Party,73.0,0,0
HB-021667,Resort Hotel,0,10,2024,March,10,4,2024-03-04,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,240.0,,0,Transient,48.0,0,2
HB-042506,City Hotel,0,55,2023,September,36,6,2023-09-06,2,0,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,75.0,0,0
HB-033780,Resort Hotel,0,1,2025,February,9,28,2025-02-28,0,3,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,97.0,0,1
HB-019710,Resort Hotel,0,37,2023,December,52,30,2023-12-30,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,188.33,1,0
HB-047399,City Hotel,0,47,2024,February,8,19,2024-02-19,0,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.3,0,1
HB-115562,City Hotel,0,72,2025,July,27,1,2025-07-01,2,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,114.0,0,1
HB-029302,Resort Hotel,0,0,2024,October,43,24,2024-10-24,1,0,2,0.0,0,BB,ROU,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient,75.0,0,0
HB-041614,City Hotel,0,7,2023,August,33,19,2023-08-19,0,2,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Contract,97.0,0,1
HB-045098,City Hotel,1,102,2023,October,42,16,2023-10-16,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-063607,City Hotel,1,70,2025,February,7,15,2025-02-15,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,B,1,No Deposit,,242.0,0,Transient-Party,78.0,0,0
HB-023928,Resort Hotel,0,109,2024,May,18,1,2024-05-01,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,D,2,No Deposit,26.0,,0,Transient,39.95,0,0
HB-093522,City Hotel,0,292,2024,July,29,21,2024-07-21,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,0
HB-026195,Resort Hotel,0,107,2024,July,29,21,2024-07-21,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,219.0,1,2
HB-043843,City Hotel,1,87,2023,September,39,25,2023-09-25,2,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-082547,City Hotel,0,86,2023,December,52,30,2023-12-30,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,81.86,0,1
HB-061122,City Hotel,1,315,2024,December,49,2,2024-12-02,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,52.0,0,0
HB-005140,Resort Hotel,0,185,2024,April,16,18,2024-04-18,1,1,1,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,1,No Deposit,298.0,,0,Transient-Party,54.5,0,0
HB-005943,Resort Hotel,1,151,2024,May,20,17,2024-05-17,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,46.0,0,0
HB-020009,Resort Hotel,0,1,2024,January,2,12,2024-01-12,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,146.0,,0,Transient,31.0,1,1
HB-050382,City Hotel,0,133,2024,April,18,29,2024-04-29,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.3,0,1
HB-033561,Resort Hotel,0,70,2025,February,8,22,2025-02-22,0,4,2,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,405.0,0,Transient-Party,42.0,0,0
HB-006456,Resort Hotel,1,277,2024,June,24,12,2024-06-12,2,2,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-046990,City Hotel,1,18,2024,February,5,1,2024-02-01,1,5,2,2.0,0,BB,CHN,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient-Party,77.88,0,0
HB-077667,City Hotel,0,6,2023,September,38,23,2023-09-23,0,1,1,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,42.0,,0,Transient,0.0,0,1
HB-076321,City Hotel,0,137,2023,July,28,11,2023-07-11,2,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,86.0,0,0
HB-089458,City Hotel,0,189,2024,May,20,19,2024-05-19,0,3,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,65.0,0,1
HB-037817,Resort Hotel,0,12,2025,June,26,26,2025-06-26,1,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient,114.75,0,1
HB-097030,City Hotel,0,20,2024,September,37,11,2024-09-11,1,0,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.0,0,0
HB-005853,Resort Hotel,1,9,2024,May,20,15,2024-05-15,1,0,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient-Party,8.0,0,0
HB-031215,Resort Hotel,0,10,2024,December,50,15,2024-12-15,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,38.4,0,0
HB-092228,City Hotel,0,16,2024,July,27,1,2024-07-01,0,2,3,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,187.0,0,3
HB-051101,City Hotel,1,276,2024,May,20,13,2024-05-13,2,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,160,Transient,61.0,0,0
HB-039655,Resort Hotel,0,1,2025,August,34,22,2025-08-22,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,306.0,,0,Transient,151.29,0,0
HB-071531,City Hotel,1,207,2025,July,28,7,2025-07-07,0,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,2
HB-060094,City Hotel,1,95,2024,November,45,5,2024-11-05,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,75.0,0,0
HB-047449,City Hotel,1,17,2024,February,8,22,2024-02-22,1,0,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.0,0,0
HB-026265,Resort Hotel,0,151,2024,July,29,19,2024-07-19,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,4,No Deposit,181.0,,0,Transient,152.2,0,0
HB-044321,City Hotel,1,89,2023,October,40,3,2023-10-03,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-052293,City Hotel,1,116,2024,June,22,2,2024-06-02,1,3,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient-Party,127.5,0,0
HB-027973,Resort Hotel,0,165,2025,July,30,22,2025-07-22,2,5,2,0.0,0,BB,PRT,Direct,Direct,1,0,1,A,A,0,No Deposit,250.0,,0,Transient,139.5,0,0
HB-108792,City Hotel,0,75,2025,March,13,29,2025-03-29,0,4,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.1,0,2
HB-099398,City Hotel,0,36,2024,October,41,9,2024-10-09,2,2,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,9.0,,0,Transient,153.0,0,2
HB-023962,Resort Hotel,0,113,2024,May,19,7,2024-05-07,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,64.0,1,1
HB-064579,City Hotel,1,52,2025,March,11,13,2025-03-13,1,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,56.0,,0,Transient,80.0,0,0
HB-055760,City Hotel,1,149,2024,August,34,20,2024-08-20,2,1,3,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,137.7,0,0
HB-100875,City Hotel,0,13,2024,November,44,2,2024-11-02,0,1,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,9.0,,0,Transient,112.0,0,2
HB-044582,City Hotel,0,210,2023,October,40,8,2023-10-08,1,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,36.38,0,0
HB-089252,City Hotel,0,64,2024,May,20,17,2024-05-17,0,2,1,0.0,0,BB,MAR,Corporate,TA/TO,0,0,0,A,F,0,No Deposit,,218.0,0,Transient-Party,130.0,0,0
HB-010802,Resort Hotel,1,46,2025,April,14,5,2025-04-05,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,70.0,0,0
HB-032255,Resort Hotel,0,2,2025,January,3,18,2025-01-18,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,C,0,No Deposit,,178.0,0,Transient,35.0,0,0
HB-040038,Resort Hotel,0,379,2025,August,34,24,2025-08-24,4,10,2,1.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Contract,87.75,0,3
HB-020195,Resort Hotel,0,2,2024,December,51,16,2024-12-16,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,1,0,1,A,D,0,No Deposit,330.0,,0,Group,34.0,0,1
HB-072356,City Hotel,1,109,2025,July,30,26,2025-07-26,2,9,3,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,225.0,0,0
HB-011242,Resort Hotel,1,172,2025,April,18,29,2025-04-29,2,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,314.0,,0,Transient,97.71,0,0
HB-012520,Resort Hotel,1,53,2025,July,27,2,2025-07-02,4,10,2,0.0,0,HB,PRT,Corporate,Corporate,0,0,0,D,D,0,No Deposit,531.0,,0,Transient,120.0,0,1
HB-008115,Resort Hotel,1,333,2024,September,37,12,2024-09-12,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,242.0,,0,Transient,130.5,0,1
HB-099718,City Hotel,0,377,2024,October,42,14,2024-10-14,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-020022,Resort Hotel,0,0,2024,January,2,12,2024-01-12,0,1,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,86.0,0,0
HB-005851,Resort Hotel,1,9,2024,May,20,15,2024-05-15,1,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,315.0,,0,Transient-Party,70.0,0,0
HB-038931,Resort Hotel,0,226,2025,July,29,20,2025-07-20,4,10,2,0.0,0,HB,POL,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,315.0,,0,Contract,156.6,0,1
HB-090223,City Hotel,0,3,2024,June,23,3,2024-06-03,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,E,0,No Deposit,,,0,Transient,94.0,0,0
HB-099394,City Hotel,0,36,2024,October,41,9,2024-10-09,2,2,3,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,9.0,,0,Transient,171.9,0,3
HB-045784,City Hotel,0,98,2023,November,47,23,2023-11-23,1,2,1,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,70.0,0,0
HB-060931,City Hotel,1,88,2024,November,48,26,2024-11-26,0,1,2,2.0,0,BB,NLD,Online TA,TA/TO,0,0,0,F,F,3,No Deposit,9.0,,0,Transient,156.6,0,1
HB-076166,City Hotel,1,233,2023,September,38,18,2023-09-18,0,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,6.0,,0,Transient-Party,120.0,0,0
HB-001553,Resort Hotel,0,163,2023,September,35,3,2023-09-03,2,5,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,91.46,0,1
HB-069988,City Hotel,1,169,2025,June,23,8,2025-06-08,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,170.0,0,0
HB-053999,City Hotel,1,101,2024,July,27,4,2024-07-04,2,5,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,114.3,0,0
HB-066216,City Hotel,1,87,2025,April,16,15,2025-04-15,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,95.0,0,0
HB-000748,Resort Hotel,0,77,2023,July,30,27,2023-07-27,1,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,1,No Deposit,240.0,,0,Transient,195.0,0,1
HB-102310,City Hotel,0,122,2024,November,48,25,2024-11-25,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,197.0,0,Transient-Party,67.0,0,0
HB-091767,City Hotel,0,133,2024,June,25,21,2024-06-21,0,5,2,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,85.0,,0,Transient-Party,90.95,0,0
HB-048504,City Hotel,1,81,2024,March,12,24,2024-03-24,1,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,99.45,0,1
HB-005120,Resort Hotel,0,185,2024,April,16,18,2024-04-18,1,1,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,85.0,0,0
HB-041056,City Hotel,0,0,2023,August,32,11,2023-08-11,0,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,2,No Deposit,,,0,Transient,114.0,0,0
HB-110402,City Hotel,0,59,2025,April,17,26,2025-04-26,0,1,2,0.0,0,BB,CHE,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,130.5,0,2
HB-116696,City Hotel,0,423,2025,July,30,22,2025-07-22,1,1,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,95.5,0,0
HB-049779,City Hotel,1,103,2024,April,16,19,2024-04-19,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,0,Transient,115.0,0,0
HB-005862,Resort Hotel,1,9,2024,May,20,15,2024-05-15,1,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,315.0,,0,Transient-Party,70.0,0,0
HB-069391,City Hotel,1,186,2025,May,22,30,2025-05-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,130.0,0,0
HB-115145,City Hotel,0,128,2025,June,27,30,2025-06-30,0,2,2,0.0,0,BB,SAU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,112.05,0,4
HB-004802,Resort Hotel,1,76,2024,March,13,31,2024-03-31,3,8,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,51.87,0,1
HB-095908,City Hotel,0,5,2024,August,34,23,2024-08-23,0,3,2,0.0,0,BB,ESP,Corporate,Corporate,0,0,0,D,A,0,No Deposit,,62.0,0,Transient,95.0,0,0
HB-000275,Resort Hotel,0,115,2023,July,28,10,2023-07-10,2,7,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,120.6,0,2
HB-050147,City Hotel,1,146,2024,April,17,24,2024-04-24,2,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,26.0,,50,Transient,95.0,0,0
HB-072314,City Hotel,1,169,2025,July,30,26,2025-07-26,0,3,2,1.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,148.5,0,0
HB-021365,Resort Hotel,0,40,2024,February,8,20,2024-02-20,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,115.0,,0,Transient,40.79,0,0
HB-113562,City Hotel,0,44,2025,June,23,7,2025-06-07,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,2
HB-088456,City Hotel,0,0,2024,May,18,2,2024-05-02,1,3,1,0.0,0,BB,ESP,Aviation,Corporate,0,0,0,A,A,0,No Deposit,,153.0,0,Transient-Party,95.0,0,0
HB-098187,City Hotel,0,336,2024,September,38,21,2024-09-21,1,4,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,78.0,0,0
HB-016806,Resort Hotel,0,69,2023,September,36,10,2023-09-10,0,3,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,8.0,,0,Transient,97.5,1,0
HB-111017,City Hotel,0,6,2025,May,18,4,2025-05-04,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,77.0,,0,Transient-Party,115.0,0,0
HB-045651,City Hotel,0,140,2023,November,46,18,2023-11-18,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,D,1,No Deposit,29.0,,87,Transient-Party,65.0,0,0
HB-095442,City Hotel,0,203,2024,August,33,13,2024-08-13,2,5,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,122.76,0,1
HB-069459,City Hotel,1,409,2025,May,22,31,2025-05-31,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,1
HB-083176,City Hotel,0,7,2024,January,3,20,2024-01-20,0,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.67,0,1
HB-103465,City Hotel,0,100,2024,December,52,23,2024-12-23,0,2,3,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,105.0,0,0
HB-038115,Resort Hotel,0,52,2025,July,28,7,2025-07-07,0,2,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,210.0,0,0
HB-047777,City Hotel,1,11,2024,March,9,3,2024-03-03,1,3,2,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,138.0,0,0
HB-024901,Resort Hotel,0,16,2024,June,23,3,2024-06-03,2,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,111.0,0,1
HB-109754,City Hotel,0,81,2025,April,15,13,2025-04-13,0,3,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.0,0,2
HB-026795,Resort Hotel,0,55,2024,August,32,10,2024-08-10,0,1,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,269.0,1,0
HB-018525,Resort Hotel,0,0,2025,July,27,2,2025-07-02,1,0,2,0.0,0,BB,PRT,Direct,TA/TO,1,0,3,A,A,0,No Deposit,,,0,Transient,127.0,1,2
HB-007753,Resort Hotel,1,15,2024,August,34,24,2024-08-24,2,5,2,2.0,0,HB,PRT,Online TA,TA/TO,0,0,0,C,C,1,No Deposit,314.0,,0,Transient,220.49,0,0
HB-094998,City Hotel,0,13,2024,August,32,10,2024-08-10,0,3,3,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,7.0,,0,Transient,231.15,0,2
HB-099919,City Hotel,0,127,2024,October,42,18,2024-10-18,0,2,3,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,160.2,1,1
HB-048124,City Hotel,1,61,2024,March,11,17,2024-03-17,1,3,2,0.0,0,SC,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,78.41,0,0
HB-011391,Resort Hotel,1,29,2025,May,19,5,2025-05-05,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,104.0,0,1
HB-116967,City Hotel,0,1,2025,July,30,27,2025-07-27,0,1,1,1.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,1,No Deposit,,,0,Transient,238.0,0,0
HB-079684,City Hotel,0,42,2023,October,43,26,2023-10-26,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,98.36,0,1
HB-047920,City Hotel,1,52,2024,March,10,9,2024-03-09,0,4,2,0.0,0,SC,HUN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,63.75,0,0
HB-012129,Resort Hotel,1,13,2025,June,24,15,2025-06-15,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,420.0,,0,Transient-Party,95.0,0,0
HB-043602,City Hotel,0,60,2023,September,38,21,2023-09-21,1,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,20.0,,0,Transient-Party,65.0,0,0
HB-108869,City Hotel,0,194,2025,April,14,1,2025-04-01,1,1,3,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,105.0,0,0
HB-007854,Resort Hotel,1,14,2024,August,35,30,2024-08-30,0,3,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,221.0,0,1
HB-063125,City Hotel,1,56,2025,February,5,1,2025-02-01,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,60.0,0,0
HB-017008,Resort Hotel,0,239,2023,September,38,19,2023-09-19,1,1,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,248.0,,0,Transient-Party,80.0,0,0
HB-107536,City Hotel,0,65,2025,March,10,8,2025-03-08,2,4,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,67.15,0,1
HB-087907,City Hotel,0,81,2024,April,17,24,2024-04-24,2,2,2,0.0,0,HB,CHE,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient-Party,111.78,0,1
HB-052142,City Hotel,1,113,2024,May,22,31,2024-05-31,0,3,1,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,A,0,Non Refund,,202.0,0,Transient,100.0,0,0
HB-025719,Resort Hotel,0,9,2024,July,27,7,2024-07-07,0,1,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,219.0,1,0
HB-030422,Resort Hotel,0,4,2024,November,47,20,2024-11-20,1,0,2,0.0,0,BB,BRA,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,66.0,1,1
HB-068280,City Hotel,1,47,2025,May,20,15,2025-05-15,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,125.0,0,0
HB-048588,City Hotel,1,161,2024,March,13,25,2024-03-25,1,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,101,Transient,130.0,0,0
HB-043227,City Hotel,0,76,2023,September,37,16,2023-09-16,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,13.0,,0,Transient,71.4,0,1
HB-053986,City Hotel,1,143,2024,July,27,4,2024-07-04,1,2,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,137.7,0,1
HB-063767,City Hotel,1,90,2025,February,8,20,2025-02-20,1,2,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,71.28,0,0
HB-025942,Resort Hotel,0,174,2024,July,28,10,2024-07-10,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Contract,106.55,0,0
HB-005479,Resort Hotel,1,157,2024,April,18,29,2024-04-29,4,10,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,52.2,0,2
HB-085542,City Hotel,0,5,2025,March,11,15,2025-03-15,0,1,1,0.0,0,BB,PRT,Complementary,Direct,1,0,1,A,A,0,No Deposit,,46.0,0,Transient,65.0,0,2
HB-047695,City Hotel,1,116,2024,February,9,28,2024-02-28,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,61.0,0,0
HB-047502,City Hotel,1,53,2024,February,8,24,2024-02-24,0,3,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,67.5,0,0
HB-107920,City Hotel,0,58,2025,March,11,16,2025-03-16,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,70.69,0,2
HB-001892,Resort Hotel,1,114,2023,September,38,20,2023-09-20,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,66.6,0,0
HB-080242,City Hotel,0,2,2024,October,40,1,2024-10-01,0,1,2,2.0,0,BB,PRT,Direct,Direct,1,0,1,F,F,0,No Deposit,,,0,Transient,85.0,0,1
HB-090828,City Hotel,0,70,2024,June,23,9,2024-06-09,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.9,0,0
HB-086173,City Hotel,0,24,2024,March,13,26,2024-03-26,2,1,2,0.0,0,BB,DEU,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient,100.0,0,0
HB-082702,City Hotel,0,44,2024,January,1,2,2024-01-02,2,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,98.0,0,0
HB-038428,Resort Hotel,0,0,2025,July,29,17,2025-07-17,1,0,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,183.0,0,1
HB-032230,Resort Hotel,0,0,2025,January,3,16,2025-01-16,1,2,1,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,A,H,0,No Deposit,,,0,Transient-Party,55.0,0,0
HB-025128,Resort Hotel,0,98,2024,June,23,9,2024-06-09,2,5,2,0.0,1,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,243.0,,0,Contract,53.56,0,0
HB-017785,Resort Hotel,0,6,2024,March,11,16,2024-03-16,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,3,A,D,1,No Deposit,,380.0,0,Transient,30.0,0,0
HB-007821,Resort Hotel,1,23,2024,August,35,28,2024-08-28,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,181.8,0,1
HB-067080,City Hotel,1,186,2025,April,18,28,2025-04-28,1,2,2,0.0,1,BB,FRA,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,130.5,0,2
HB-114807,City Hotel,0,396,2025,June,26,25,2025-06-25,2,0,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,B,2,No Deposit,6.0,,0,Transient-Party,95.5,0,1
HB-078928,City Hotel,0,0,2023,October,42,18,2023-10-18,1,0,1,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,7.0,,0,Transient,87.78,0,0
HB-089966,City Hotel,0,102,2024,June,23,5,2024-06-05,1,0,1,0.0,0,BB,ISR,Groups,TA/TO,0,0,1,A,A,1,No Deposit,1.0,,0,Transient-Party,0.0,0,1
HB-061091,City Hotel,1,24,2024,December,48,1,2024-12-01,4,10,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,0
HB-063486,City Hotel,1,67,2025,February,7,12,2025-02-12,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,80.0,0,0
HB-079849,City Hotel,1,34,2023,December,49,8,2023-12-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,0,Transient,90.0,0,0
HB-019395,Resort Hotel,1,196,2024,June,26,29,2024-06-29,2,7,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,E,E,0,No Deposit,240.0,,0,Transient,106.0,0,2
HB-000333,Resort Hotel,0,13,2023,July,28,12,2023-07-12,2,0,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,88.2,0,0
HB-024304,Resort Hotel,0,90,2024,May,19,10,2024-05-10,2,5,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,68.0,0,0
HB-021204,Resort Hotel,0,1,2024,February,8,20,2024-02-20,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,0
HB-113082,City Hotel,0,49,2025,May,22,30,2025-05-30,0,3,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Transient,98.1,0,3
HB-101189,City Hotel,0,23,2024,November,46,12,2024-11-12,1,1,2,0.0,0,BB,PRT,Complementary,TA/TO,0,0,1,D,E,2,No Deposit,83.0,,0,Group,0.0,0,1
HB-006447,Resort Hotel,1,227,2024,June,24,11,2024-06-11,4,6,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,72.0,0,2
HB-014577,Resort Hotel,0,10,2024,February,6,9,2024-02-09,0,2,2,0.0,0,BB,,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,339.0,,0,Transient,29.0,0,0
HB-002025,Resort Hotel,0,85,2023,September,39,27,2023-09-27,4,8,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,83.67,0,1
HB-082447,City Hotel,0,40,2023,December,52,26,2023-12-26,2,2,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Contract,55.0,0,1
HB-099072,City Hotel,0,88,2024,October,41,7,2024-10-07,0,2,2,0.0,0,BB,POL,Corporate,Corporate,0,0,0,A,A,0,No Deposit,193.0,,0,Transient-Party,90.0,0,1
HB-024136,Resort Hotel,0,119,2024,May,19,12,2024-05-12,0,1,2,0.0,0,BB,CHE,Offline TA/TO,TA/TO,0,0,0,D,G,0,No Deposit,251.0,,0,Transient,59.0,0,1
HB-086885,City Hotel,0,159,2024,April,15,9,2024-04-09,1,1,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,3.0,,0,Transient-Party,65.0,0,0
HB-019284,Resort Hotel,1,318,2024,October,43,21,2024-10-21,2,5,1,0.0,0,FB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,175.0,,0,Transient,56.7,0,0
HB-056528,City Hotel,1,426,2024,September,36,8,2024-09-08,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-027792,Resort Hotel,0,42,2024,September,37,9,2024-09-09,0,2,1,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,162.0,1,1
HB-091104,City Hotel,0,256,2024,June,24,15,2024-06-15,0,2,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,90.0,0,0
HB-085880,City Hotel,0,23,2024,March,11,17,2024-03-17,2,4,2,0.0,0,BB,BGR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,168.0,,0,Transient,68.0,0,0
HB-091073,City Hotel,0,34,2024,June,24,14,2024-06-14,0,3,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,1
HB-110578,City Hotel,0,86,2025,April,17,27,2025-04-27,0,2,2,0.0,0,BB,TWN,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,99.0,0,1
HB-067165,City Hotel,1,187,2025,April,18,29,2025-04-29,1,1,2,1.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,140.3,0,1
HB-022367,Resort Hotel,0,41,2024,March,12,20,2024-03-20,2,2,1,2.0,0,BB,FIN,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,36.0,,0,Transient,46.4,0,0
HB-034851,Resort Hotel,0,56,2025,April,14,1,2025-04-01,2,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,526.0,,0,Transient-Party,43.2,0,0
HB-000160,Resort Hotel,0,79,2023,July,27,5,2023-07-05,4,10,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Contract,134.1,0,0
HB-086760,City Hotel,0,6,2024,April,14,7,2024-04-07,0,1,1,0.0,0,BB,PRT,Aviation,Corporate,0,0,0,A,A,0,No Deposit,,153.0,0,Transient,95.0,0,0
HB-113340,City Hotel,0,434,2025,June,23,3,2025-06-03,2,1,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,1
HB-033742,Resort Hotel,0,28,2025,February,7,16,2025-02-16,4,10,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,40.0,,0,Contract,81.76,0,0
HB-017339,Resort Hotel,0,1,2023,October,40,4,2023-10-04,2,0,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,76.0,0,0
HB-042119,City Hotel,0,5,2023,August,35,31,2023-08-31,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.25,0,2
HB-117228,City Hotel,0,168,2025,July,30,25,2025-07-25,2,5,2,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,168.0,,0,Transient,80.1,0,1
HB-109292,City Hotel,0,27,2025,April,14,6,2025-04-06,0,3,3,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,190.0,0,1
HB-018458,Resort Hotel,1,20,2023,December,48,3,2023-12-03,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,,,0,Transient-Party,36.0,0,0
HB-114073,City Hotel,0,27,2025,June,23,8,2025-06-08,2,7,2,0.0,0,BB,POL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,123.0,0,0
HB-045375,City Hotel,0,72,2023,October,43,28,2023-10-28,0,3,2,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,58,Transient-Party,85.67,0,0
HB-029445,Resort Hotel,0,0,2024,October,43,27,2024-10-27,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,75.0,0,0
HB-058879,City Hotel,1,131,2024,October,42,17,2024-10-17,1,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,132.3,0,0
HB-025089,Resort Hotel,0,155,2024,June,23,8,2024-06-08,2,5,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,240.0,,0,Transient,87.5,0,0
HB-103037,City Hotel,0,46,2024,December,49,8,2024-12-08,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,102.6,0,2
HB-041248,City Hotel,1,39,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,101.5,0,0
HB-095125,City Hotel,0,0,2024,August,32,9,2024-08-09,1,5,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,170.0,0,1
HB-007734,Resort Hotel,1,199,2024,August,34,23,2024-08-23,0,3,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,,0,Transient,131.0,0,0
HB-098913,City Hotel,0,23,2024,October,40,2,2024-10-02,2,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,94.36,0,1
HB-040181,City Hotel,1,122,2023,July,28,13,2023-07-13,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,76.5,0,2
HB-105614,City Hotel,0,33,2025,February,7,11,2025-02-11,0,1,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.0,0,1
HB-044658,City Hotel,0,80,2023,October,41,9,2023-10-09,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,12.0,,50,Transient-Party,136.0,0,0
HB-015103,Resort Hotel,1,214,2023,October,40,3,2023-10-03,1,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,208.0,,0,Transient,34.0,0,0
HB-065364,City Hotel,1,150,2025,April,14,1,2025-04-01,2,1,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,0
HB-027393,Resort Hotel,0,305,2024,August,34,21,2024-08-21,2,5,3,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,3,No Deposit,314.0,,0,Transient,178.08,0,1
HB-079100,City Hotel,0,5,2023,October,42,21,2023-10-21,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,3.0,,0,Transient-Party,0.0,0,0
HB-014058,Resort Hotel,0,0,2025,January,1,4,2025-01-04,0,3,1,0.0,0,BB,,Direct,Direct,0,0,2,A,D,1,No Deposit,,,0,Transient,45.0,1,1
HB-059408,City Hotel,1,464,2024,October,44,28,2024-10-28,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,391,Transient,65.0,0,0
HB-066166,City Hotel,1,123,2025,April,16,15,2025-04-15,1,1,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,171.0,0,2
HB-006698,Resort Hotel,1,4,2024,June,26,25,2024-06-25,1,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,169.0,0,0
HB-040599,City Hotel,0,0,2023,August,31,3,2023-08-03,1,0,2,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,0.0,0,0
HB-040534,City Hotel,0,0,2023,July,30,28,2023-07-28,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,0.0,0,0
HB-100180,City Hotel,0,146,2024,October,42,19,2024-10-19,1,4,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,166.5,0,2
HB-101936,City Hotel,0,26,2024,November,46,17,2024-11-17,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,83.0,,0,Transient,91.2,0,0
HB-081490,City Hotel,0,9,2024,December,50,10,2024-12-10,0,1,2,1.0,0,BB,PRT,Complementary,Direct,1,0,8,F,F,0,No Deposit,,45.0,0,Transient-Party,0.0,0,1
HB-014928,Resort Hotel,0,72,2024,March,13,25,2024-03-25,1,2,2,0.0,0,BB,PRT,Direct,Direct,1,0,1,D,D,0,No Deposit,250.0,,0,Transient,132.0,1,1
HB-031925,Resort Hotel,0,74,2025,January,2,9,2025-01-09,1,2,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,30.0,0,1
HB-057509,City Hotel,1,96,2024,September,39,26,2024-09-26,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.9,0,0
HB-075214,City Hotel,1,294,2023,August,32,7,2023-08-07,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-027768,Resort Hotel,0,234,2024,August,35,27,2024-08-27,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,68.0,0,0
HB-042461,City Hotel,0,55,2023,September,36,6,2023-09-06,2,0,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,75.0,0,0
HB-103347,City Hotel,0,86,2024,December,51,17,2024-12-17,2,1,3,0.0,0,BB,FRA,Direct,Direct,0,0,0,F,F,0,No Deposit,14.0,,0,Transient,193.08,0,3
HB-063285,City Hotel,1,61,2025,February,6,5,2025-02-05,2,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.6,0,1
HB-095568,City Hotel,0,79,2024,August,33,18,2024-08-18,0,3,3,0.0,0,BB,SWE,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,198.3,0,1
HB-005493,Resort Hotel,0,197,2024,April,18,30,2024-04-30,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,85.0,0,0
HB-117824,City Hotel,0,192,2025,August,32,9,2025-08-09,0,1,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,148.5,0,2
HB-010413,Resort Hotel,1,312,2025,March,10,5,2025-03-05,2,5,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,30.0,0,0
HB-039610,Resort Hotel,0,0,2025,August,34,22,2025-08-22,0,1,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient,180.0,0,0
HB-053290,City Hotel,1,245,2024,June,25,17,2024-06-17,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,0,Transient,75.0,0,0
HB-071732,City Hotel,1,77,2025,July,28,11,2025-07-11,0,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,2
HB-065434,City Hotel,1,73,2025,April,14,3,2025-04-03,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,105.0,0,0
HB-018850,Resort Hotel,0,25,2023,November,47,24,2023-11-24,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,115.0,,0,Transient-Party,55.32,0,1
HB-108573,City Hotel,0,146,2025,March,13,25,2025-03-25,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,K,0,No Deposit,7.0,,0,Transient,64.67,0,1
HB-117999,City Hotel,0,160,2025,August,32,7,2025-08-07,1,5,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,173.7,0,1
HB-114391,City Hotel,0,9,2025,June,25,20,2025-06-20,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,153.0,0,0
HB-057379,City Hotel,1,38,2024,September,39,24,2024-09-24,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,146.96,0,0
HB-026023,Resort Hotel,0,72,2024,July,28,11,2024-07-11,3,5,2,2.0,0,HB,GBR,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,287.5,1,0
HB-082261,City Hotel,0,44,2024,January,1,2,2024-01-02,2,1,2,0.0,0,HB,ITA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,98.0,0,0
HB-041130,City Hotel,1,7,2023,August,32,12,2023-08-12,1,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,90.0,0,1
HB-017392,Resort Hotel,0,0,2023,October,40,5,2023-10-05,1,3,2,0.0,0,FB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,174.0,0,Transient-Party,109.0,0,0
HB-044695,City Hotel,1,66,2023,October,41,9,2023-10-09,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,75.0,0,0
HB-045218,City Hotel,0,61,2023,October,43,24,2023-10-24,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,80.75,0,1
HB-071863,City Hotel,1,157,2025,July,29,14,2025-07-14,1,2,3,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,177.3,0,0
HB-042272,City Hotel,0,63,2023,September,36,4,2023-09-04,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,21.0,,0,Transient-Party,116.0,0,0
HB-042051,City Hotel,1,104,2023,August,35,30,2023-08-30,2,1,2,0.0,0,HB,ESP,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,90.0,0,0
HB-069430,City Hotel,1,87,2025,May,22,30,2025-05-30,0,3,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.67,0,0
HB-024164,Resort Hotel,0,468,2024,May,19,12,2024-05-12,0,2,2,0.0,0,HB,FRA,Groups,TA/TO,0,0,0,A,D,0,No Deposit,249.0,,0,Transient,69.0,0,0
HB-025775,Resort Hotel,0,220,2024,July,27,4,2024-07-04,2,5,2,0.0,0,FB,POL,Offline TA/TO,TA/TO,0,0,0,E,E,1,No Deposit,315.0,,0,Transient,135.3,0,0
HB-105083,City Hotel,0,14,2025,January,5,28,2025-01-28,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,0
HB-052639,City Hotel,1,27,2024,June,23,9,2024-06-09,0,1,2,0.0,0,BB,PRT,Offline TA/TO,Corporate,0,0,0,A,A,0,No Deposit,191.0,,0,Transient-Party,120.0,0,0
HB-085239,City Hotel,0,0,2024,May,21,24,2024-05-24,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,1,0,3,E,E,1,No Deposit,,174.0,0,Transient,159.0,0,0
HB-116233,City Hotel,0,8,2025,July,29,15,2025-07-15,1,1,2,0.0,0,BB,MOZ,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.0,0,3
HB-039554,Resort Hotel,0,202,2025,August,34,19,2025-08-19,1,1,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient-Party,194.0,0,2
HB-058254,City Hotel,1,265,2024,October,41,9,2024-10-09,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,100.3,0,0
HB-113537,City Hotel,0,28,2025,June,23,6,2025-06-06,0,3,2,0.0,0,SC,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,89.0,0,0
HB-091957,City Hotel,0,162,2024,June,26,26,2024-06-26,2,0,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,114.3,1,1
HB-086336,City Hotel,0,75,2024,March,13,28,2024-03-28,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,82.45,0,0
HB-088948,City Hotel,0,0,2024,May,20,14,2024-05-14,0,1,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,221.0,0,0
HB-017780,Resort Hotel,0,287,2023,October,41,15,2023-10-15,2,4,2,0.0,0,BB,PRT,Groups,Corporate,0,0,0,A,D,1,No Deposit,,223.0,0,Transient,44.5,0,0
HB-070066,City Hotel,1,178,2025,June,24,9,2025-06-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,86.0,,0,Transient,130.0,0,0
HB-009207,Resort Hotel,1,49,2024,November,44,2,2024-11-02,2,5,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,42.1,0,0
HB-062278,City Hotel,1,121,2025,January,2,6,2025-01-06,2,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.4,0,0
HB-007861,Resort Hotel,1,39,2024,August,35,30,2024-08-30,0,5,2,0.0,0,HB,,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,159.0,0,5
HB-097735,City Hotel,0,88,2024,September,37,15,2024-09-15,2,3,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,4,No Deposit,9.0,,0,Transient,149.4,0,1
HB-117702,City Hotel,0,0,2025,August,32,8,2025-08-08,0,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,1,0,0,A,A,0,No Deposit,262.0,,0,Transient,0.0,0,0
HB-072449,City Hotel,1,61,2025,July,31,28,2025-07-28,2,3,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,133.6,0,1
HB-007973,Resort Hotel,1,183,2024,September,36,5,2024-09-05,1,5,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,146.0,0,0
HB-052346,City Hotel,1,275,2024,June,23,4,2024-06-04,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,5.0,,69,Transient,62.8,0,0
HB-093237,City Hotel,0,66,2024,July,29,18,2024-07-18,1,0,1,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,69.3,0,1
HB-109979,City Hotel,0,92,2025,April,16,17,2025-04-17,1,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,97.02,0,1
HB-078908,City Hotel,0,16,2023,October,41,15,2023-10-15,1,3,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,90.0,0,0
HB-003674,Resort Hotel,0,165,2023,December,52,30,2023-12-30,0,4,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,308.0,,122,Transient-Party,84.5,0,0
HB-078917,City Hotel,1,34,2023,October,42,20,2023-10-20,0,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Contract,90.9,0,2
HB-050566,City Hotel,0,126,2024,May,18,4,2024-05-04,0,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,76.58,0,1
HB-008558,Resort Hotel,0,383,2024,October,40,6,2024-10-06,0,3,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,E,1,No Deposit,315.0,,0,Transient-Party,52.0,1,0
HB-015099,Resort Hotel,1,214,2023,October,40,3,2023-10-03,1,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,208.0,,0,Transient,34.0,0,0
HB-116897,City Hotel,0,138,2025,July,29,20,2025-07-20,2,5,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,138.21,0,0
HB-072633,City Hotel,1,85,2025,August,31,1,2025-08-01,1,5,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,144.33,0,1
HB-091393,City Hotel,0,243,2024,June,25,19,2024-06-19,2,0,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,8.0,,0,Transient,95.58,0,1
HB-108234,City Hotel,0,0,2025,March,13,24,2025-03-24,0,0,0,0.0,0,BB,PRT,Online TA,TA/TO,1,0,0,A,C,0,No Deposit,155.0,,0,Transient,0.0,0,1
HB-069093,City Hotel,1,68,2025,May,21,25,2025-05-25,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,171.0,0,0
HB-070227,City Hotel,1,24,2025,June,24,12,2025-06-12,1,1,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.0,0,1
HB-095962,City Hotel,0,133,2024,August,34,21,2024-08-21,2,3,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,70.04,0,2
HB-034799,Resort Hotel,0,152,2025,April,14,5,2025-04-05,1,4,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,D,D,1,No Deposit,,223.0,0,Transient-Party,69.0,1,1
HB-110653,City Hotel,0,205,2025,April,18,28,2025-04-28,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,95.46,0,1
HB-032540,Resort Hotel,0,18,2025,January,4,26,2025-01-26,0,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,48.0,0,2
HB-104492,City Hotel,0,10,2025,January,2,12,2025-01-12,0,3,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,120.67,0,1
HB-075365,City Hotel,1,313,2023,August,34,26,2023-08-26,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-029792,Resort Hotel,0,108,2024,October,44,31,2024-10-31,1,5,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,E,E,2,No Deposit,314.0,,0,Transient,51.47,0,0
HB-038307,Resort Hotel,0,0,2025,July,29,14,2025-07-14,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,1,0,0,A,A,0,No Deposit,241.0,,0,Transient,115.19,0,1
HB-001342,Resort Hotel,0,69,2023,August,34,25,2023-08-25,0,3,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,E,G,0,No Deposit,240.0,,0,Transient,164.0,0,2
HB-093012,City Hotel,0,184,2024,July,28,11,2024-07-11,1,4,3,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,22.0,,0,Transient,96.9,0,1
HB-084055,City Hotel,0,12,2024,October,43,24,2024-10-24,1,2,1,0.0,0,BB,PRT,Aviation,TA/TO,1,0,5,D,D,0,No Deposit,,153.0,0,Transient,110.0,0,0
HB-070935,City Hotel,1,97,2025,June,26,26,2025-06-26,1,0,2,2.0,0,BB,JEY,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,230.0,0,0
HB-073276,City Hotel,1,213,2025,August,34,18,2025-08-18,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,100.8,0,1
HB-048540,City Hotel,1,161,2024,March,13,25,2024-03-25,1,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,101,Transient,130.0,0,0
HB-048548,City Hotel,1,161,2024,March,13,25,2024-03-25,1,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,101,Transient,130.0,0,0
HB-115441,City Hotel,0,405,2025,July,27,4,2025-07-04,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,114.4,0,0
HB-094410,City Hotel,0,23,2024,August,31,2,2024-08-02,0,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,139.0,0,1
HB-003188,Resort Hotel,0,78,2023,November,47,21,2023-11-21,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,342.0,0,Transient-Party,32.0,0,0
HB-025087,Resort Hotel,0,103,2024,June,24,11,2024-06-11,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,F,1,No Deposit,240.0,,0,Transient,148.0,1,2
HB-115779,City Hotel,0,153,2025,July,28,8,2025-07-08,2,1,3,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,116.1,0,1
HB-031785,Resort Hotel,0,2,2025,January,1,3,2025-01-03,0,4,1,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,242.0,,0,Transient,50.85,0,1
HB-107345,City Hotel,0,13,2025,March,10,8,2025-03-08,0,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,,,0,Transient,100.3,0,1
HB-099409,City Hotel,0,187,2024,October,41,10,2024-10-10,1,2,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,78.41,0,0
HB-006667,Resort Hotel,1,295,2024,June,25,22,2024-06-22,1,4,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,57.51,0,1
HB-030809,Resort Hotel,0,3,2024,December,49,3,2024-12-03,0,1,3,1.0,0,HB,PRT,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,158.0,1,0
HB-019443,Resort Hotel,0,16,2023,December,51,19,2023-12-19,0,1,2,1.0,1,BB,ESP,Online TA,TA/TO,0,0,0,C,G,0,No Deposit,240.0,,0,Transient,69.0,1,3
HB-084997,City Hotel,0,16,2024,March,10,4,2024-03-04,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,69.35,0,1
HB-068940,City Hotel,1,8,2025,May,21,23,2025-05-23,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,190.0,0,1
HB-101050,City Hotel,0,18,2024,November,44,3,2024-11-03,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.0,1,2
HB-062330,City Hotel,1,45,2025,January,2,8,2025-01-08,2,4,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.4,0,0
HB-087975,City Hotel,0,13,2024,April,17,26,2024-04-26,0,3,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,58.0,,0,Transient-Party,96.0,0,0
HB-038620,Resort Hotel,0,172,2025,July,29,20,2025-07-20,1,3,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,192.0,0,1
HB-008893,Resort Hotel,1,132,2024,October,42,18,2024-10-18,0,4,3,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,103.0,0,0
HB-026201,Resort Hotel,0,11,2024,July,30,23,2024-07-23,0,1,2,0.0,1,BB,FRA,Direct,Direct,0,0,0,A,B,3,No Deposit,,423.0,0,Transient-Party,126.0,0,1
HB-079313,City Hotel,0,23,2023,October,42,21,2023-10-21,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Group,75.0,0,1
HB-060851,City Hotel,1,503,2024,November,47,24,2024-11-24,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-036860,Resort Hotel,0,184,2025,May,20,18,2025-05-18,4,10,2,0.0,0,HB,BEL,Offline TA/TO,TA/TO,0,0,0,A,C,1,No Deposit,479.0,,0,Transient,85.7,0,1
HB-069850,City Hotel,1,231,2025,June,23,7,2025-06-07,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,123.04,0,1
HB-072185,City Hotel,1,240,2025,July,30,23,2025-07-23,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-089236,City Hotel,0,64,2024,May,20,17,2024-05-17,0,2,1,0.0,0,BB,CHE,Corporate,TA/TO,0,0,0,A,A,0,No Deposit,,218.0,0,Transient-Party,130.0,0,0
HB-110835,City Hotel,0,140,2025,April,18,28,2025-04-28,2,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,119.0,,0,Transient-Party,130.0,0,1
HB-002482,Resort Hotel,0,7,2023,October,42,19,2023-10-19,1,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,127.0,,0,Transient,39.0,0,0
HB-014641,Resort Hotel,0,6,2025,January,5,30,2025-01-30,1,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,5,A,A,0,No Deposit,314.0,,0,Group,34.4,0,0
HB-067662,City Hotel,1,117,2025,May,19,5,2025-05-05,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,1
HB-080955,City Hotel,0,73,2023,November,48,27,2023-11-27,1,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,79.2,0,2
HB-014770,Resort Hotel,1,259,2023,September,37,17,2023-09-17,0,3,1,0.0,0,BB,GBR,Groups,Corporate,0,1,0,A,A,0,Non Refund,,223.0,0,Transient,33.3,0,0
HB-081519,City Hotel,0,2,2023,December,49,5,2023-12-05,3,6,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,149.0,0,Transient-Party,91.67,0,0
HB-090299,City Hotel,0,19,2024,June,22,2,2024-06-02,0,3,3,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,9.0,,0,Transient,170.33,0,1
HB-031860,Resort Hotel,0,1,2025,January,2,6,2025-01-06,0,2,2,2.0,0,BB,PRT,Direct,Direct,0,0,0,G,G,2,No Deposit,,,0,Transient,0.0,1,0
HB-024558,Resort Hotel,0,104,2024,May,20,17,2024-05-17,2,7,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,61.2,0,0
HB-062797,City Hotel,1,59,2025,January,4,23,2025-01-23,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,326.0,,0,Transient,80.0,0,0
HB-057543,City Hotel,1,250,2024,September,39,26,2024-09-26,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,95.0,0,0
HB-041415,City Hotel,0,131,2023,August,33,15,2023-08-15,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-098718,City Hotel,0,179,2024,October,40,1,2024-10-01,2,1,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.9,0,1
HB-035145,Resort Hotel,0,68,2025,April,15,13,2025-04-13,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,85.0,0,2
HB-110726,City Hotel,0,134,2025,April,18,30,2025-04-30,1,0,2,0.0,0,BB,USA,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,144.0,0,0
HB-047248,City Hotel,1,0,2024,February,7,13,2024-02-13,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,F,0,No Deposit,9.0,,0,Transient-Party,106.0,0,0
HB-045565,City Hotel,1,123,2023,November,45,6,2023-11-06,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,60.0,0,0
HB-008873,Resort Hotel,1,224,2024,October,42,17,2024-10-17,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,62.29,0,0
HB-059895,City Hotel,1,304,2024,November,44,3,2024-11-03,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,89.0,0,0
HB-085900,City Hotel,0,6,2024,March,12,21,2024-03-21,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,101.0,1,1
HB-057468,City Hotel,0,418,2024,September,39,26,2024-09-26,1,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,132.0,,223,Transient-Party,107.0,0,0
HB-004179,Resort Hotel,1,1,2024,February,8,25,2024-02-25,0,2,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,A,C,0,No Deposit,,,0,Transient,60.0,0,1
HB-112816,City Hotel,0,165,2025,May,22,26,2025-05-26,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.5,0,1
HB-044950,City Hotel,1,180,2023,October,42,16,2023-10-16,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,70.0,0,0
HB-081745,City Hotel,1,113,2024,February,8,25,2024-02-25,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,6,0,A,A,0,Non Refund,19.0,,44,Transient,75.0,0,0
HB-108426,City Hotel,0,127,2025,March,12,23,2025-03-23,1,3,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,2
HB-116539,City Hotel,0,193,2025,July,29,19,2025-07-19,0,3,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,1
HB-032969,Resort Hotel,0,2,2025,February,6,4,2025-02-04,2,5,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,43.14,0,0
HB-004378,Resort Hotel,1,26,2024,March,10,9,2024-03-09,2,4,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,184.0,,0,Transient,40.8,0,0
HB-051889,City Hotel,0,316,2024,May,21,26,2024-05-26,0,3,1,0.0,0,BB,AUT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,30.0,,0,Transient-Party,0.0,0,0
HB-043494,City Hotel,1,27,2023,September,38,18,2023-09-18,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.9,0,0
HB-082511,City Hotel,0,87,2023,December,52,29,2023-12-29,0,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient-Party,95.7,0,1
HB-039814,Resort Hotel,0,126,2025,August,34,24,2025-08-24,2,3,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,175.0,,0,Transient,204.0,0,2
HB-060162,City Hotel,1,277,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-077603,City Hotel,0,0,2023,September,38,19,2023-09-19,2,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,126.0,0,3
HB-110126,City Hotel,0,44,2025,April,16,20,2025-04-20,0,3,1,0.0,0,BB,ITA,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,106.67,0,0
HB-088924,City Hotel,0,1,2024,May,20,14,2024-05-14,0,1,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,221.0,0,2
HB-099159,City Hotel,0,95,2024,October,41,7,2024-10-07,1,2,3,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,151.2,0,2
HB-058671,City Hotel,1,330,2024,October,42,14,2024-10-14,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Contract,106.7,0,1
HB-000041,Resort Hotel,1,45,2023,July,26,2,2023-07-02,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,241.0,,0,Transient,117.81,0,0
HB-064035,City Hotel,1,98,2025,February,9,26,2025-02-26,2,4,2,0.0,0,SC,FIN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,0
HB-100292,City Hotel,0,189,2024,October,42,19,2024-10-19,2,5,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,72.76,0,0
HB-056431,City Hotel,1,195,2024,September,36,5,2024-09-05,1,4,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,140.25,0,0
HB-109319,City Hotel,0,26,2025,April,15,7,2025-04-07,0,2,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,188.0,0,0
HB-106039,City Hotel,0,14,2025,February,7,16,2025-02-16,0,3,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,98.0,0,1
HB-048024,City Hotel,0,71,2024,March,11,12,2024-03-12,2,3,2,0.0,0,SC,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,45.9,0,0
HB-064280,City Hotel,1,16,2025,March,10,4,2025-03-04,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,0
HB-003431,Resort Hotel,1,81,2023,December,49,6,2023-12-06,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,40.5,0,2
HB-067872,City Hotel,1,37,2025,May,19,8,2025-05-08,1,4,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,191.4,0,1
HB-045550,City Hotel,0,123,2023,November,45,6,2023-11-06,1,2,1,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,0.0,0,0
HB-018766,Resort Hotel,0,0,2023,November,48,27,2023-11-27,0,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,40.0,0,1
HB-117784,City Hotel,0,5,2025,August,32,8,2025-08-08,0,2,1,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,136.0,0,1
HB-047554,City Hotel,1,62,2024,February,9,26,2024-02-26,2,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,73.95,0,1
HB-033863,Resort Hotel,0,7,2025,March,9,2,2025-03-02,1,3,3,0.0,0,BB,NLD,Groups,Corporate,0,0,0,D,C,4,No Deposit,,223.0,0,Transient-Party,63.45,0,0
HB-095823,City Hotel,0,98,2024,August,34,21,2024-08-21,2,2,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.9,0,1
HB-100635,City Hotel,0,98,2024,October,43,24,2024-10-24,1,5,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,F,B,2,No Deposit,9.0,,0,Transient,89.5,0,2
HB-064044,City Hotel,1,112,2025,February,9,27,2025-02-27,1,2,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,0
HB-038425,Resort Hotel,0,110,2025,July,28,11,2025-07-11,2,5,2,0.0,0,HB,BEL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,479.0,,0,Transient,153.2,0,1
HB-064830,City Hotel,1,60,2025,March,12,17,2025-03-17,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,144.0,0,0
HB-055428,City Hotel,1,212,2024,August,33,13,2024-08-13,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,96.0,0,0
HB-033353,Resort Hotel,0,30,2025,February,7,16,2025-02-16,2,3,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,2,No Deposit,250.0,,0,Transient-Party,40.5,0,0
HB-068802,City Hotel,1,113,2025,May,21,20,2025-05-20,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,34.0,,0,Transient,190.0,0,0
HB-007145,Resort Hotel,1,98,2024,July,30,23,2024-07-23,2,5,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,224.43,0,0
HB-079477,City Hotel,0,12,2023,October,43,25,2023-10-25,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,D,0,No Deposit,37.0,,0,Transient-Party,85.67,0,0
HB-038474,Resort Hotel,0,283,2025,July,28,12,2025-07-12,2,5,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,A,F,0,No Deposit,240.0,,0,Transient,166.24,0,1
HB-106103,City Hotel,0,10,2025,February,8,18,2025-02-18,2,1,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,96.0,0,0
HB-107300,City Hotel,0,13,2025,March,11,10,2025-03-10,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.0,0,0
HB-045419,City Hotel,0,72,2023,October,43,28,2023-10-28,0,3,2,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,D,0,No Deposit,37.0,,58,Transient-Party,85.67,0,0
HB-112810,City Hotel,0,187,2025,May,21,25,2025-05-25,1,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,138.83,0,1
HB-000299,Resort Hotel,0,54,2023,July,28,11,2023-07-11,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,F,0,No Deposit,240.0,,0,Transient,123.0,0,0
HB-031444,Resort Hotel,0,0,2024,December,52,28,2024-12-28,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,65.2,1,1
HB-118336,City Hotel,0,84,2025,August,33,15,2025-08-15,0,4,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,152.0,0,1
HB-043081,City Hotel,0,135,2023,September,37,14,2023-09-14,1,2,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,90.0,0,0
HB-030513,Resort Hotel,0,9,2024,November,47,19,2024-11-19,2,4,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,63.0,0,2
HB-004291,Resort Hotel,1,219,2024,March,9,2,2024-03-02,2,5,2,0.0,0,HB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,310.0,,0,Transient,52.0,0,0
HB-098840,City Hotel,0,89,2024,October,40,3,2024-10-03,1,1,1,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,113.4,0,1
HB-107938,City Hotel,0,212,2025,March,12,17,2025-03-17,1,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,122.4,0,0
HB-007656,Resort Hotel,1,116,2024,August,33,18,2024-08-18,2,5,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,241.0,,0,Transient,238.16,0,0
HB-057835,City Hotel,1,179,2024,October,40,1,2024-10-01,2,1,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.9,0,2
HB-086295,City Hotel,0,79,2024,March,13,28,2024-03-28,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,87.3,0,1
HB-085856,City Hotel,0,121,2024,March,12,19,2024-03-19,2,2,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,43.5,0,0
HB-048720,City Hotel,1,79,2024,March,13,28,2024-03-28,1,4,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,72.25,0,0
HB-065585,City Hotel,1,75,2025,April,14,5,2025-04-05,0,4,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,132.0,,0,Transient-Party,85.0,0,0
HB-034018,Resort Hotel,0,107,2025,March,10,9,2025-03-09,0,2,1,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,E,E,1,No Deposit,96.0,,0,Transient-Party,72.0,0,0
HB-006197,Resort Hotel,0,225,2024,May,22,28,2024-05-28,1,1,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,E,0,No Deposit,298.0,,0,Transient-Party,85.0,0,0
HB-017807,Resort Hotel,0,1,2025,February,6,7,2025-02-07,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,2,A,A,1,No Deposit,,511.0,0,Transient,35.0,0,1
HB-061359,City Hotel,1,49,2024,December,49,8,2024-12-08,0,3,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,156.6,0,2
HB-115051,City Hotel,0,2,2025,June,27,30,2025-06-30,0,1,1,0.0,0,BB,AUT,Online TA,GDS,0,0,0,A,A,0,No Deposit,195.0,,0,Transient,180.0,0,0
HB-032078,Resort Hotel,0,77,2025,January,2,10,2025-01-10,1,5,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,42.0,0,1
HB-100287,City Hotel,0,0,2024,October,43,26,2024-10-26,0,0,1,0.0,0,SC,PRT,Online TA,TA/TO,1,0,0,A,K,0,No Deposit,7.0,,0,Transient,0.0,0,1
HB-095921,City Hotel,0,154,2024,August,34,24,2024-08-24,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.8,0,0
HB-114819,City Hotel,0,396,2025,June,26,25,2025-06-25,2,0,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,122.4,0,1
HB-007666,Resort Hotel,0,328,2024,August,34,19,2024-08-19,2,2,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,40.0,,0,Contract,120.1,0,0
HB-043797,City Hotel,0,56,2023,September,39,25,2023-09-25,0,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,K,1,No Deposit,44.0,,0,Transient-Party,0.0,0,0
HB-038959,Resort Hotel,0,87,2025,July,30,25,2025-07-25,2,8,3,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,F,E,0,No Deposit,241.0,,0,Transient,239.3,0,2
HB-110740,City Hotel,0,249,2025,April,18,29,2025-04-29,1,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,1
HB-052183,City Hotel,1,61,2024,June,22,1,2024-06-01,0,4,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,4,No Deposit,9.0,,0,Transient,159.3,0,1
HB-095353,City Hotel,0,118,2024,August,33,13,2024-08-13,2,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.3,0,1
HB-017268,Resort Hotel,1,277,2023,October,40,5,2023-10-05,4,10,1,0.0,0,HB,GBR,Groups,Direct,0,1,0,A,A,0,Non Refund,273.0,,0,Transient,48.5,0,0
HB-063227,City Hotel,1,31,2025,February,5,2,2025-02-02,2,4,2,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,122.4,0,3
HB-028218,Resort Hotel,0,13,2024,September,39,23,2024-09-23,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,136.0,1,1
HB-005171,Resort Hotel,1,91,2024,April,16,19,2024-04-19,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,196.0,,0,Transient,53.1,0,0
HB-048345,City Hotel,1,51,2024,March,12,21,2024-03-21,1,3,2,0.0,0,HB,BEL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,125.8,0,1
HB-104380,City Hotel,0,0,2025,January,2,11,2025-01-11,0,1,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,90.0,0,0
HB-052076,City Hotel,1,56,2024,May,22,30,2024-05-30,1,0,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,120.0,0,0
HB-026853,Resort Hotel,0,136,2024,August,32,7,2024-08-07,2,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,181.0,0,1
HB-104332,City Hotel,0,8,2025,January,2,7,2025-01-07,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,84.69,0,1
HB-055888,City Hotel,1,16,2024,August,34,24,2024-08-24,0,1,2,1.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,112.81,0,1
HB-064807,City Hotel,1,169,2025,March,11,16,2025-03-16,1,3,2,0.0,0,BB,LUX,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,96.9,0,0
HB-110448,City Hotel,0,70,2025,April,17,25,2025-04-25,0,3,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Contract,110.0,0,0
HB-113370,City Hotel,0,43,2025,June,23,3,2025-06-03,2,1,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,179.0,0,1
HB-001345,Resort Hotel,1,50,2023,August,34,25,2023-08-25,0,5,2,0.0,1,HB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,200.8,0,2
HB-052983,City Hotel,1,188,2024,June,24,15,2024-06-15,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,39,Transient,130.0,0,0
HB-096056,City Hotel,0,48,2024,August,34,24,2024-08-24,0,4,3,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,168.3,0,1
HB-076415,City Hotel,1,263,2023,September,38,21,2023-09-21,1,0,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,4.0,,0,Transient-Party,96.0,0,0
HB-003827,Resort Hotel,1,0,2024,January,3,15,2024-01-15,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient-Party,44.0,0,0
HB-003791,Resort Hotel,1,0,2024,January,1,7,2024-01-07,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,2
HB-090887,City Hotel,0,124,2024,June,24,10,2024-06-10,1,2,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,126.9,0,2
HB-112524,City Hotel,0,0,2025,May,21,23,2025-05-23,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,2,No Deposit,,,0,Transient,180.0,0,0
HB-082168,City Hotel,1,99,2024,February,8,19,2024-02-19,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,1,0,A,A,0,No Deposit,,67.0,0,Transient-Party,80.0,0,0
HB-012827,Resort Hotel,1,165,2025,July,29,18,2025-07-18,0,5,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,192.0,0,0
HB-072083,City Hotel,1,45,2025,July,29,20,2025-07-20,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,117.0,0,0
HB-078479,City Hotel,0,23,2023,October,41,9,2023-10-09,0,1,2,0.0,0,BB,USA,Offline TA/TO,TA/TO,0,0,0,D,F,0,No Deposit,90.0,,0,Transient,96.3,0,0
HB-009495,Resort Hotel,1,183,2024,December,49,3,2024-12-03,2,1,2,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,C,1,Non Refund,38.0,,0,Transient,72.0,0,0
HB-029116,Resort Hotel,0,37,2024,October,43,21,2024-10-21,0,2,2,0.0,0,BB,GBR,Groups,Corporate,0,0,1,A,A,1,No Deposit,,,0,Transient-Party,49.0,0,0
HB-005023,Resort Hotel,1,168,2024,April,15,12,2024-04-12,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,245.0,,0,Transient,86.0,0,0
HB-062577,City Hotel,1,52,2025,January,3,15,2025-01-15,2,4,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,96.9,0,0
HB-076126,City Hotel,1,288,2023,October,42,16,2023-10-16,0,2,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,1,Non Refund,6.0,,0,Transient-Party,80.0,0,0
HB-032353,Resort Hotel,0,4,2025,January,4,22,2025-01-22,2,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,37.0,1,0
HB-058445,City Hotel,1,279,2024,October,41,12,2024-10-12,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,98.0,,0,Transient,110.0,0,0
HB-118657,City Hotel,0,12,2025,August,34,20,2025-08-20,2,2,1,0.0,0,BB,USA,Groups,TA/TO,0,0,0,A,A,3,No Deposit,98.0,,0,Transient-Party,115.0,0,0
HB-077405,City Hotel,0,19,2023,October,40,6,2023-10-06,0,3,2,0.0,0,BB,TUR,Offline TA/TO,TA/TO,1,0,0,A,D,0,No Deposit,82.0,,0,Transient-Party,90.0,0,0
HB-035965,Resort Hotel,0,0,2025,May,19,5,2025-05-05,0,1,2,0.0,0,BB,CN,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,100.0,1,0
HB-063318,City Hotel,1,197,2025,February,6,7,2025-02-07,0,4,2,0.0,0,BB,ROU,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,74.8,0,0
HB-109233,City Hotel,0,75,2025,April,14,5,2025-04-05,0,4,1,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,85.0,0,0
HB-049695,City Hotel,1,28,2024,April,16,17,2024-04-17,2,1,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,115.03,0,1
HB-030201,Resort Hotel,0,0,2024,December,49,8,2024-12-08,0,1,2,0.0,0,BB,FRA,Direct,Direct,1,0,1,A,E,1,No Deposit,,,0,Transient,76.0,1,0
HB-026667,Resort Hotel,0,15,2024,August,31,4,2024-08-04,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,168.63,0,1
HB-108620,City Hotel,0,0,2025,March,13,24,2025-03-24,2,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,155.0,,0,Transient,110.0,0,1
HB-092469,City Hotel,0,92,2024,July,27,4,2024-07-04,1,2,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,B,B,1,No Deposit,14.0,,0,Transient-Party,104.52,0,0
HB-041340,City Hotel,1,3,2023,August,33,14,2023-08-14,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,126.67,0,2
HB-080682,City Hotel,0,32,2023,November,47,20,2023-11-20,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,119.0,,0,Transient-Party,73.0,0,0
HB-068845,City Hotel,1,128,2025,May,21,21,2025-05-21,2,2,2,0.0,0,BB,LUX,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,136.8,0,0
HB-059229,City Hotel,1,208,2024,October,43,22,2024-10-22,2,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.3,0,0
HB-008678,Resort Hotel,1,131,2024,October,41,9,2024-10-09,2,1,2,0.0,0,BB,PRT,Groups,Corporate,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,55.0,0,0
HB-082982,City Hotel,0,3,2025,June,24,9,2025-06-09,0,1,1,0.0,0,BB,PRT,Complementary,Direct,1,0,7,A,D,1,No Deposit,,45.0,0,Transient,0.0,0,0
HB-092549,City Hotel,0,118,2024,July,27,1,2024-07-01,2,5,2,0.0,0,BB,DNK,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,107.95,0,1
HB-037153,Resort Hotel,0,0,2025,June,23,8,2025-06-08,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,337.0,0,Transient,75.0,0,0
HB-045996,City Hotel,1,134,2023,December,49,4,2023-12-04,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,91,Transient,65.0,0,0
HB-100185,City Hotel,0,0,2024,October,43,24,2024-10-24,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,F,0,No Deposit,,,0,Transient,145.0,0,0
HB-029347,Resort Hotel,0,216,2024,October,41,13,2024-10-13,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,243.0,,0,Contract,48.75,0,0
HB-019578,Resort Hotel,0,2,2023,December,51,24,2023-12-24,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,H,H,2,No Deposit,240.0,,0,Transient,121.0,1,0
HB-043884,City Hotel,1,87,2023,September,39,25,2023-09-25,2,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-036563,Resort Hotel,0,168,2025,May,20,15,2025-05-15,3,6,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,163.0,,0,Transient,84.45,0,0
HB-118121,City Hotel,0,21,2025,August,33,14,2025-08-14,1,0,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,218.0,0,3
HB-104187,City Hotel,0,40,2025,January,1,3,2025-01-03,0,5,3,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,125.66,0,2
HB-107441,City Hotel,0,70,2025,March,10,9,2025-03-09,1,3,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.8,0,2
HB-106595,City Hotel,0,10,2025,February,9,27,2025-02-27,1,0,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,98.0,0,0
HB-109589,City Hotel,0,68,2025,April,15,10,2025-04-10,1,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,42.0,,0,Transient,89.1,0,0
HB-051816,City Hotel,1,323,2024,May,21,26,2024-05-26,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-018365,Resort Hotel,1,82,2024,February,6,7,2024-02-07,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,67.0,,0,Transient-Party,86.0,0,0
HB-054341,City Hotel,1,85,2024,July,28,13,2024-07-13,0,4,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.5,0,0
HB-045574,City Hotel,0,233,2023,November,45,7,2023-11-07,1,1,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,60.0,0,0
HB-073624,City Hotel,1,162,2025,August,35,28,2025-08-28,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,139.5,0,1
HB-055534,City Hotel,1,110,2024,August,33,15,2024-08-15,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.9,0,0
HB-104953,City Hotel,0,3,2025,January,4,23,2025-01-23,1,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,75.0,1,0
HB-057300,City Hotel,0,429,2024,September,39,23,2024-09-23,0,2,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,330,Transient-Party,65.0,0,0
HB-091827,City Hotel,0,0,2024,June,26,24,2024-06-24,0,2,1,0.0,0,BB,SRB,Offline TA/TO,TA/TO,0,0,0,A,D,2,No Deposit,34.0,,0,Transient-Party,0.0,0,0
HB-030836,Resort Hotel,0,0,2024,December,48,1,2024-12-01,1,3,2,0.0,1,BB,IRL,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,62.25,0,0
HB-032005,Resort Hotel,0,0,2025,January,3,14,2025-01-14,2,1,2,0.0,0,BB,SWE,Direct,Direct,1,0,0,A,A,1,No Deposit,,,0,Transient,50.0,1,0
HB-079249,City Hotel,1,444,2024,December,48,1,2024-12-01,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,34.0,,39,Transient,75.0,0,0
HB-081796,City Hotel,1,117,2024,February,9,29,2024-02-29,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,44,Transient,75.0,0,0
HB-101353,City Hotel,0,66,2024,November,45,7,2024-11-07,1,3,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,179.1,0,2
HB-014109,Resort Hotel,0,29,2024,September,37,12,2024-09-12,1,3,2,0.0,0,BB,,Online TA,TA/TO,0,0,0,G,G,1,No Deposit,240.0,,0,Transient,208.0,1,1
HB-027165,Resort Hotel,0,209,2024,August,33,15,2024-08-15,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,118.1,0,0
HB-007942,Resort Hotel,1,233,2024,September,36,3,2024-09-03,2,5,3,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,C,1,No Deposit,196.0,,0,Transient,66.6,0,1
HB-106449,City Hotel,0,0,2025,February,9,25,2025-02-25,0,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.0,0,1
HB-081318,City Hotel,0,47,2023,December,49,5,2023-12-05,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-025869,Resort Hotel,0,179,2024,July,27,4,2024-07-04,3,7,2,0.0,0,FB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,26.0,,0,Transient,100.89,0,0
HB-064260,City Hotel,1,141,2025,March,10,3,2025-03-03,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,102.6,0,2
HB-074572,City Hotel,1,346,2023,September,39,28,2023-09-28,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-048441,City Hotel,0,95,2024,March,12,23,2024-03-23,0,3,1,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,10.0,,0,Transient,75.1,0,0
HB-084760,City Hotel,0,115,2024,February,9,27,2024-02-27,2,3,1,0.0,0,BB,MAR,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,134.0,,0,Transient-Party,75.0,0,0
HB-007434,Resort Hotel,1,181,2024,August,32,8,2024-08-08,4,10,3,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,69.0,,0,Transient,196.7,0,1
HB-025599,Resort Hotel,0,4,2024,July,27,2,2024-07-02,0,1,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,201.0,1,0
HB-046661,City Hotel,0,40,2024,January,2,14,2024-01-14,1,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,69.5,0,1
HB-009922,Resort Hotel,1,13,2025,January,4,24,2025-01-24,0,1,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,88.0,0,0
HB-069329,City Hotel,1,186,2025,May,22,30,2025-05-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,130.0,0,0
HB-085923,City Hotel,0,14,2024,March,12,19,2024-03-19,2,3,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,146.2,0,2
HB-098333,City Hotel,0,33,2024,September,39,26,2024-09-26,1,1,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,119.0,0,1
HB-073315,City Hotel,1,230,2025,August,34,18,2025-08-18,2,2,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.9,0,1
HB-008783,Resort Hotel,0,365,2024,October,41,13,2024-10-13,1,3,2,0.0,0,BB,NLD,Groups,Corporate,0,0,0,A,H,1,No Deposit,,223.0,0,Transient-Party,66.0,0,0
HB-011726,Resort Hotel,1,313,2025,May,22,27,2025-05-27,2,5,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,59.79,0,0
HB-044436,City Hotel,1,97,2023,October,40,5,2023-10-05,1,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,140.0,0,0
HB-086322,City Hotel,0,5,2024,April,15,12,2024-04-12,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,221.0,0,Transient,104.0,0,3
HB-069442,City Hotel,1,0,2025,May,22,31,2025-05-31,0,2,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,229.0,0,1
HB-011427,Resort Hotel,1,17,2025,May,19,7,2025-05-07,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,68.0,0,1
HB-096160,City Hotel,0,41,2024,August,35,26,2024-08-26,2,2,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,157.28,0,0
HB-005324,Resort Hotel,1,138,2024,April,17,25,2024-04-25,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,E,E,0,Non Refund,,,0,Transient,65.0,0,0
HB-095376,City Hotel,0,1,2024,August,33,17,2024-08-17,0,1,1,0.0,0,SC,AUT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,152.0,,0,Transient,78.41,0,0
HB-043501,City Hotel,1,74,2023,September,38,18,2023-09-18,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-030935,Resort Hotel,0,16,2024,December,49,8,2024-12-08,0,1,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient-Party,71.0,1,0
HB-021190,Resort Hotel,0,20,2024,February,7,16,2024-02-16,0,5,3,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,C,0,No Deposit,196.0,,0,Transient,30.0,0,1
HB-097581,City Hotel,0,27,2024,September,38,16,2024-09-16,0,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,139.0,0,0
HB-095523,City Hotel,0,320,2024,August,33,18,2024-08-18,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-114702,City Hotel,0,44,2025,June,25,19,2025-06-19,2,5,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,112.91,0,1
HB-040603,City Hotel,0,84,2023,August,31,3,2023-08-03,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,85.5,1,1
HB-002116,Resort Hotel,1,29,2023,October,40,2,2023-10-02,1,2,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,G,G,1,No Deposit,250.0,,0,Transient,117.0,0,0
HB-101955,City Hotel,0,3,2024,November,47,19,2024-11-19,1,1,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,100.5,0,1
HB-091029,City Hotel,0,2,2024,June,24,14,2024-06-14,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,91.0,0,1
HB-019790,Resort Hotel,0,0,2024,January,1,2,2024-01-02,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient,68.0,0,0
HB-033871,Resort Hotel,0,7,2025,March,9,2,2025-03-02,1,3,1,0.0,0,BB,BEL,Groups,Corporate,0,0,0,A,C,1,No Deposit,,223.0,0,Transient-Party,29.0,0,0
HB-064274,City Hotel,1,25,2025,March,10,3,2025-03-03,2,5,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,134.3,0,0
HB-086983,City Hotel,0,77,2024,April,15,8,2024-04-08,2,2,2,0.0,0,BB,BRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,80.75,0,2
HB-025193,Resort Hotel,0,297,2024,June,24,11,2024-06-11,2,5,1,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,59.9,0,1
HB-106860,City Hotel,0,134,2025,February,9,27,2025-02-27,1,4,3,1.0,0,BB,AUT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,7.0,,0,Transient,152.76,0,1
HB-034984,Resort Hotel,0,1,2025,April,15,9,2025-04-09,1,0,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,65.6,0,1
HB-108533,City Hotel,0,158,2025,March,13,27,2025-03-27,1,1,1,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,A,1,No Deposit,37.0,,0,Transient-Party,95.0,0,0
HB-002583,Resort Hotel,0,24,2023,October,42,22,2023-10-22,0,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient-Party,76.0,0,2
HB-049388,City Hotel,1,27,2024,April,15,12,2024-04-12,0,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,1
HB-090958,City Hotel,0,2,2024,June,24,12,2024-06-12,2,0,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.5,0,2
HB-071224,City Hotel,1,135,2025,June,27,30,2025-06-30,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,30.0,,0,Transient,120.0,0,0
HB-005199,Resort Hotel,0,206,2024,April,16,21,2024-04-21,0,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient-Party,52.98,1,2
HB-023068,Resort Hotel,0,30,2024,April,15,13,2024-04-13,0,2,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,A,E,0,No Deposit,,,0,Transient,63.0,0,0
HB-007422,Resort Hotel,1,55,2024,August,32,8,2024-08-08,1,4,2,2.0,0,BB,LUX,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,278.6,0,0
HB-087479,City Hotel,0,96,2024,April,16,18,2024-04-18,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,96.3,1,1
HB-045786,City Hotel,0,98,2023,November,47,23,2023-11-23,1,2,1,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,70.0,0,0
HB-036671,Resort Hotel,0,129,2025,May,21,19,2025-05-19,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,40.95,0,0
HB-034500,Resort Hotel,0,31,2025,March,12,20,2025-03-20,2,5,2,0.0,0,BB,AUT,Groups,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient-Party,160.71,0,0
HB-053864,City Hotel,1,44,2024,July,27,1,2024-07-01,0,2,2,2.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient-Party,156.95,0,1
HB-053749,City Hotel,1,90,2024,June,26,28,2024-06-28,1,5,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.3,0,0
HB-041048,City Hotel,1,3,2023,August,32,11,2023-08-11,0,3,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,153.0,0,0
HB-000861,Resort Hotel,1,130,2023,August,31,1,2023-08-01,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,120.6,0,2
HB-099914,City Hotel,0,47,2024,October,42,16,2024-10-16,2,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,80.75,0,0
HB-083802,City Hotel,0,0,2024,February,7,12,2024-02-12,0,1,2,0.0,0,SC,BRA,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,79.0,0,2
HB-032384,Resort Hotel,0,4,2025,January,4,22,2025-01-22,2,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-098512,City Hotel,0,36,2024,September,39,28,2024-09-28,0,3,2,0.0,0,BB,DEU,Groups,TA/TO,0,0,0,A,C,1,No Deposit,21.0,,0,Transient-Party,87.0,0,0
HB-104075,City Hotel,0,76,2025,January,1,1,2025-01-01,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,75.86,0,1
HB-116571,City Hotel,0,17,2025,July,29,20,2025-07-20,0,2,3,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,423.0,,0,Transient,110.68,0,0
HB-014940,Resort Hotel,1,177,2023,August,33,15,2023-08-15,2,5,2,1.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,6.0,,0,Transient-Party,119.7,0,2
HB-080583,City Hotel,1,1,2023,November,46,19,2023-11-19,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-047304,City Hotel,1,40,2024,February,7,16,2024-02-16,0,1,1,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,72.9,0,0
HB-036607,Resort Hotel,0,14,2025,May,21,22,2025-05-22,1,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,1,No Deposit,,,0,Transient,145.75,1,1
HB-024773,Resort Hotel,0,147,2024,June,22,1,2024-06-01,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,241.0,,0,Transient,77.83,1,0
HB-117301,City Hotel,0,20,2025,July,31,31,2025-07-31,1,1,2,2.0,0,BB,CHN,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,234.0,0,0
HB-026336,Resort Hotel,0,234,2024,July,30,22,2024-07-22,2,5,3,0.0,0,HB,PRT,Direct,Direct,0,0,0,D,D,1,No Deposit,250.0,,0,Transient,213.55,1,1
HB-075336,City Hotel,1,311,2023,August,34,24,2023-08-24,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-114366,City Hotel,0,110,2025,June,25,19,2025-06-19,1,1,2,0.0,0,SC,ISR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-106246,City Hotel,0,45,2025,February,8,20,2025-02-20,1,2,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.2,0,1
HB-033923,Resort Hotel,0,7,2025,March,9,2,2025-03-02,1,3,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,D,D,0,No Deposit,,223.0,0,Transient-Party,54.0,1,0
HB-003772,Resort Hotel,1,103,2024,January,1,3,2024-01-03,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,36.45,0,1
HB-039400,Resort Hotel,0,212,2025,August,33,11,2025-08-11,2,4,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,203.67,0,4
HB-007918,Resort Hotel,1,36,2024,September,36,2,2024-09-02,1,2,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,169.0,0,1
HB-001498,Resort Hotel,0,0,2023,September,35,1,2023-09-01,0,5,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,250.0,,0,Transient,128.0,0,0
HB-004829,Resort Hotel,0,171,2024,April,14,4,2024-04-04,1,1,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,Non Refund,298.0,,0,Transient-Party,85.0,0,0
HB-092052,City Hotel,0,111,2024,June,26,26,2024-06-26,2,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.45,0,1
HB-023529,Resort Hotel,0,5,2024,May,22,30,2024-05-30,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,409.0,0,Transient-Party,54.0,0,0
HB-079555,City Hotel,0,35,2023,October,43,26,2023-10-26,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Transient,75.0,0,1
HB-095341,City Hotel,0,31,2024,August,33,15,2024-08-15,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,113.64,0,1
HB-049802,City Hotel,1,103,2024,April,16,19,2024-04-19,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,0,Transient,115.0,0,0
HB-086230,City Hotel,0,122,2024,March,13,27,2024-03-27,2,1,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,26.0,,0,Transient-Party,86.0,0,0
HB-098606,City Hotel,0,193,2024,September,39,29,2024-09-29,0,3,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,93.09,0,1
HB-107198,City Hotel,0,0,2025,March,10,8,2025-03-08,0,1,2,0.0,0,SC,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,75.0,0,0
HB-061408,City Hotel,1,322,2024,December,50,9,2024-12-09,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,52.0,0,0
HB-017376,Resort Hotel,0,50,2023,October,39,1,2023-10-01,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Transient,50.03,0,0
HB-018750,Resort Hotel,0,2,2023,November,48,28,2023-11-28,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,0
HB-045807,City Hotel,1,98,2023,November,47,23,2023-11-23,1,2,1,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,84.0,0,0
HB-066592,City Hotel,1,332,2025,April,17,22,2025-04-22,1,1,3,1.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,141.3,0,0
HB-037164,Resort Hotel,0,318,2025,June,23,2,2025-06-02,2,5,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,96.91,1,0
HB-033870,Resort Hotel,0,7,2025,March,9,2,2025-03-02,1,3,2,0.0,0,BB,BEL,Groups,Corporate,0,0,0,D,D,0,No Deposit,,223.0,0,Transient-Party,47.0,0,0
HB-070407,City Hotel,1,51,2025,June,25,16,2025-06-16,1,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,1
HB-063358,City Hotel,1,14,2025,February,6,9,2025-02-09,1,3,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,1
HB-057127,City Hotel,1,280,2024,September,38,19,2024-09-19,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,35,Transient,110.0,0,0
HB-004811,Resort Hotel,0,175,2024,April,14,2,2024-04-02,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,52.2,0,1
HB-085505,City Hotel,0,35,2024,March,11,14,2024-03-14,1,2,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-003898,Resort Hotel,1,72,2024,February,6,6,2024-02-06,2,1,2,0.0,0,HB,PRT,Groups,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,73.33,0,0
HB-035079,Resort Hotel,0,45,2025,April,15,9,2025-04-09,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,90.0,0,1
HB-119276,City Hotel,0,213,2025,August,35,28,2025-08-28,1,3,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,19.0,,0,Transient-Party,104.0,0,0
HB-105425,City Hotel,0,64,2025,February,6,6,2025-02-06,1,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.6,0,1
HB-050743,City Hotel,1,62,2024,May,19,7,2024-05-07,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,140.4,0,0
HB-009835,Resort Hotel,1,161,2025,January,2,9,2025-01-09,2,5,1,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,37.8,0,0
HB-096055,City Hotel,0,48,2024,August,34,24,2024-08-24,0,4,1,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,149.4,0,1
HB-018473,Resort Hotel,0,0,2024,February,5,4,2024-02-04,0,1,1,0.0,0,HB,PRT,Corporate,Corporate,1,0,2,A,A,0,No Deposit,,20.0,0,Transient,46.0,0,0
HB-000223,Resort Hotel,0,113,2023,July,27,8,2023-07-08,2,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,1,No Deposit,250.0,,0,Transient,77.96,1,1
HB-091141,City Hotel,0,256,2024,June,24,15,2024-06-15,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-112575,City Hotel,0,208,2025,May,21,24,2025-05-24,0,2,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,114.4,0,0
HB-110673,City Hotel,0,28,2025,April,18,29,2025-04-29,0,1,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,115.0,0,1
HB-025949,Resort Hotel,0,134,2024,July,28,12,2024-07-12,0,5,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,E,1,No Deposit,240.0,,0,Transient,140.0,0,1
HB-070057,City Hotel,1,178,2025,June,24,9,2025-06-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,86.0,,0,Transient,130.0,0,0
HB-103065,City Hotel,0,4,2024,December,49,7,2024-12-07,0,4,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.26,0,2
HB-034632,Resort Hotel,0,23,2025,March,13,29,2025-03-29,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,F,0,No Deposit,240.0,,0,Transient,102.0,1,1
HB-071276,City Hotel,1,121,2025,July,27,1,2025-07-01,0,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,135.0,0,0
HB-003677,Resort Hotel,0,165,2023,December,52,30,2023-12-30,0,4,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,308.0,,122,Transient-Party,138.5,0,0
HB-041618,City Hotel,0,2,2023,August,33,19,2023-08-19,2,5,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,99.14,0,0
HB-112004,City Hotel,0,25,2025,May,20,16,2025-05-16,0,3,1,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,474.0,,0,Transient-Party,130.0,0,0
HB-074646,City Hotel,1,374,2023,October,43,26,2023-10-26,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-098132,City Hotel,0,4,2024,September,39,23,2024-09-23,0,2,1,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,B,2,No Deposit,1.0,,0,Transient-Party,57.5,0,0
HB-031553,Resort Hotel,0,225,2024,December,52,26,2024-12-26,1,5,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,F,F,3,No Deposit,250.0,,0,Transient,76.2,0,0
HB-077947,City Hotel,0,17,2023,September,39,26,2023-09-26,2,2,1,0.0,0,BB,IRN,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,170.0,0,0
HB-115759,City Hotel,0,65,2025,July,28,10,2025-07-10,1,1,2,2.0,0,BB,FRA,Direct,Direct,0,0,0,E,E,1,No Deposit,14.0,,0,Transient,18.0,0,0
HB-035816,Resort Hotel,0,89,2025,April,18,28,2025-04-28,2,2,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,121.5,1,1
HB-097615,City Hotel,0,128,2024,September,38,16,2024-09-16,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,89.0,,0,Transient,100.29,0,3
HB-054668,City Hotel,1,171,2024,July,30,22,2024-07-22,2,6,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,81.25,0,2
HB-039112,Resort Hotel,0,187,2025,August,31,1,2025-08-01,2,5,2,0.0,0,HB,ROU,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,5.0,,0,Transient,190.97,0,1
HB-020870,Resort Hotel,0,8,2024,February,7,12,2024-02-12,0,2,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,D,1,No Deposit,250.0,,0,Transient,45.0,0,0
HB-060765,City Hotel,1,60,2024,November,47,20,2024-11-20,1,0,1,0.0,0,BB,CYP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,86.4,0,2
HB-079658,City Hotel,0,43,2023,October,43,29,2023-10-29,0,3,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,90.9,0,3
HB-013665,Resort Hotel,1,253,2025,August,35,25,2025-08-25,2,4,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,153.75,0,1
HB-029529,Resort Hotel,0,8,2024,October,44,28,2024-10-28,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,38.0,0,0
HB-096477,City Hotel,0,76,2024,August,35,30,2024-08-30,0,4,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,89.75,0,0
HB-018058,Resort Hotel,0,154,2023,October,44,30,2023-10-30,0,2,1,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,36.0,0,0
HB-106023,City Hotel,0,72,2025,February,7,16,2025-02-16,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,72.0,0,0
HB-067377,City Hotel,1,34,2025,May,18,3,2025-05-03,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,149.0,0,1
HB-110106,City Hotel,0,63,2025,April,16,20,2025-04-20,0,2,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,D,F,0,No Deposit,9.0,,0,Transient,135.0,0,1
HB-107130,City Hotel,0,31,2025,March,10,4,2025-03-04,2,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,77.23,0,0
HB-025883,Resort Hotel,0,23,2024,July,29,15,2024-07-15,0,0,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,0.0,0,1
HB-089577,City Hotel,0,86,2024,May,21,20,2024-05-20,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,65.0,0,1
HB-044091,City Hotel,1,27,2023,September,39,30,2023-09-30,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,64.0,,21,Transient,108.0,0,0
HB-116146,City Hotel,0,414,2025,July,28,13,2025-07-13,0,2,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,122.4,0,1
HB-115332,City Hotel,0,14,2025,June,27,30,2025-06-30,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,180.0,0,1
HB-010179,Resort Hotel,1,42,2025,February,8,18,2025-02-18,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,2
HB-074769,City Hotel,0,241,2023,October,42,19,2023-10-19,1,2,1,0.0,0,BB,USA,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,50.0,0,0
HB-074407,City Hotel,1,290,2023,August,31,3,2023-08-03,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-023654,Resort Hotel,0,24,2024,April,18,29,2024-04-29,0,1,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,G,G,1,No Deposit,250.0,,0,Transient,125.0,0,0
HB-099130,City Hotel,0,349,2024,October,40,4,2024-10-04,1,5,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,58.0,,162,Transient-Party,123.33,0,0
HB-098850,City Hotel,0,0,2024,October,40,5,2024-10-05,0,1,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,152.0,,0,Transient,92.98,0,0
HB-076577,City Hotel,1,207,2023,September,39,29,2023-09-29,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,20.0,,0,Transient,48.0,0,0
HB-087955,City Hotel,0,108,2024,April,17,28,2024-04-28,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,77.03,0,0
HB-084411,City Hotel,0,0,2024,May,20,17,2024-05-17,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,3,A,A,1,No Deposit,,40.0,0,Transient,65.0,0,1
HB-044344,City Hotel,0,61,2023,October,40,4,2023-10-04,2,0,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,91.0,0,0
HB-007361,Resort Hotel,1,156,2024,August,32,5,2024-08-05,2,5,3,0.0,1,BB,PRT,Direct,Direct,0,0,0,C,C,0,No Deposit,,,0,Transient,187.7,0,1
HB-073932,City Hotel,1,265,2023,July,27,9,2023-07-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Contract,62.0,0,0
HB-010569,Resort Hotel,1,144,2025,March,11,14,2025-03-14,4,14,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,C,1,No Deposit,440.0,,0,Transient-Party,62.0,0,0
HB-028043,Resort Hotel,0,336,2024,September,37,15,2024-09-15,1,3,2,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,A,1,No Deposit,,223.0,0,Transient-Party,81.0,1,0
HB-088081,City Hotel,0,142,2024,April,18,29,2024-04-29,0,2,1,0.0,0,BB,ITA,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,65.0,0,1
HB-092631,City Hotel,0,10,2024,July,27,7,2024-07-07,0,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,161.33,0,1
HB-046422,City Hotel,1,119,2024,January,1,1,2024-01-01,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,74.25,0,0
HB-022856,Resort Hotel,0,0,2024,April,14,7,2024-04-07,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,71.0,1,0
HB-048932,City Hotel,0,88,2024,April,14,2,2024-04-02,2,2,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,72.25,0,0
HB-093885,City Hotel,0,63,2024,July,30,23,2024-07-23,2,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.3,0,1
HB-083243,City Hotel,0,3,2024,January,4,25,2024-01-25,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.0,0,2
HB-056003,City Hotel,1,148,2024,August,35,26,2024-08-26,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.3,0,0
HB-076551,City Hotel,1,199,2023,September,38,21,2023-09-21,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,20.0,,0,Transient,48.0,0,0
HB-097927,City Hotel,0,80,2024,September,38,17,2024-09-17,2,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,149.4,0,2
HB-057397,City Hotel,1,89,2024,September,39,25,2024-09-25,2,1,3,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,127.33,0,0
HB-049691,City Hotel,1,45,2024,April,16,17,2024-04-17,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,112.8,0,1
HB-044117,City Hotel,1,28,2023,September,39,30,2023-09-30,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,105.0,0,1
HB-007027,Resort Hotel,1,146,2024,July,29,17,2024-07-17,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,242.0,0,0
HB-104447,City Hotel,0,65,2025,January,2,12,2025-01-12,0,2,1,0.0,0,BB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,366.0,0,Transient-Party,65.0,0,0
HB-082842,City Hotel,1,68,2024,February,7,17,2024-02-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,37.0,,0,Transient,75.0,0,0
HB-076390,City Hotel,0,273,2023,July,29,17,2023-07-17,0,2,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,87.0,0,0
HB-109210,City Hotel,0,41,2025,April,14,3,2025-04-03,1,4,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,137.2,0,1
HB-092841,City Hotel,0,147,2024,July,28,11,2024-07-11,1,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,0
HB-081772,City Hotel,1,113,2024,February,8,25,2024-02-25,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,44,Transient,75.0,0,0
HB-064864,City Hotel,1,61,2025,March,12,18,2025-03-18,0,1,3,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,129.6,0,0
HB-069823,City Hotel,1,23,2025,June,23,7,2025-06-07,0,2,2,0.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,52.0,,0,Transient,166.5,0,0
HB-109206,City Hotel,0,53,2025,March,13,29,2025-03-29,2,8,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,80.8,0,0
HB-012238,Resort Hotel,1,114,2025,June,25,19,2025-06-19,1,4,2,1.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,5.0,250.0,0,Transient,117.5,0,0
HB-079746,City Hotel,0,18,2023,October,44,31,2023-10-31,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,7.0,,0,Transient,78.54,0,1
HB-005011,Resort Hotel,1,168,2024,April,15,12,2024-04-12,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,245.0,,0,Transient,86.0,0,0
HB-068767,City Hotel,1,176,2025,May,21,20,2025-05-20,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,34.0,,63,Transient,190.0,0,0
HB-027812,Resort Hotel,0,287,2024,September,36,5,2024-09-05,2,5,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,Refundable,418.0,,0,Transient-Party,69.0,0,0
HB-011479,Resort Hotel,1,140,2025,May,19,10,2025-05-10,2,5,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,96.0,,0,Transient-Party,48.0,0,0
HB-002527,Resort Hotel,0,108,2023,October,42,20,2023-10-20,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Contract,36.0,0,1
HB-102178,City Hotel,0,215,2024,November,47,21,2024-11-21,1,2,2,0.0,0,BB,GRC,Groups,Corporate,0,0,0,A,A,2,No Deposit,,233.0,0,Transient,85.0,0,0
HB-109092,City Hotel,0,4,2025,April,14,3,2025-04-03,1,2,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,84.01,0,2
HB-042780,City Hotel,1,44,2023,September,36,10,2023-09-10,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,41.0,,0,Transient,126.0,0,0
HB-006841,Resort Hotel,0,272,2024,July,27,5,2024-07-05,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,2.0,,0,Contract,111.3,0,3
HB-057546,City Hotel,1,250,2024,September,39,26,2024-09-26,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,95.0,0,0
HB-038140,Resort Hotel,0,350,2025,June,27,30,2025-06-30,3,7,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,81.36,0,0
HB-101556,City Hotel,0,79,2024,November,46,11,2024-11-11,1,2,1,0.0,0,BB,DEU,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,79.2,0,0
HB-023921,Resort Hotel,0,2,2024,May,18,1,2024-05-01,2,4,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,135.0,0,0
HB-049036,City Hotel,1,104,2024,April,14,5,2024-04-05,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,96.0,0,0
HB-106064,City Hotel,0,42,2025,February,8,17,2025-02-17,1,2,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,105.33,0,0
HB-018147,Resort Hotel,0,69,2024,November,47,19,2024-11-19,0,1,2,0.0,0,HB,GBR,Online TA,TA/TO,1,0,0,D,D,0,No Deposit,241.0,,0,Transient,56.83,0,1
HB-011744,Resort Hotel,1,7,2025,May,22,28,2025-05-28,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,110.0,0,1
HB-050013,City Hotel,1,61,2024,April,17,22,2024-04-22,1,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,118.8,0,0
HB-067358,City Hotel,1,14,2025,May,18,2,2025-05-02,0,3,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,190.0,0,1
HB-006967,Resort Hotel,1,297,2024,July,28,14,2024-07-14,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,117.0,0,1
HB-052880,City Hotel,1,4,2024,June,24,14,2024-06-14,0,2,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,164.0,0,0
HB-117559,City Hotel,0,133,2025,August,32,4,2025-08-04,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.0,0,0
HB-098005,City Hotel,0,3,2024,September,38,20,2024-09-20,0,3,0,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient,155.68,0,4
HB-097663,City Hotel,0,150,2024,September,38,16,2024-09-16,1,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.9,0,1
HB-043415,City Hotel,0,74,2023,September,38,18,2023-09-18,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-007094,Resort Hotel,1,55,2024,July,29,21,2024-07-21,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,179.0,0,1
HB-001209,Resort Hotel,0,126,2023,August,33,18,2023-08-18,1,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,5.0,,0,Transient-Party,96.3,0,1
HB-076949,City Hotel,1,342,2023,September,38,24,2023-09-24,2,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-085654,City Hotel,0,87,2024,March,11,14,2024-03-14,1,4,1,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,63.75,0,2
HB-048700,City Hotel,1,6,2024,March,13,27,2024-03-27,2,3,3,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,161.0,0,0
HB-088625,City Hotel,0,30,2024,May,19,8,2024-05-08,1,0,2,0.0,1,BB,GBR,Direct,Direct,0,0,0,D,D,1,No Deposit,14.0,,0,Transient,170.0,1,0
HB-118161,City Hotel,0,214,2025,August,33,12,2025-08-12,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,42.0,,0,Transient,89.0,0,0
HB-108106,City Hotel,0,72,2025,March,12,20,2025-03-20,1,2,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,106.2,0,2
HB-104586,City Hotel,0,44,2025,January,3,14,2025-01-14,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,96.9,0,0
HB-076751,City Hotel,0,181,2023,August,31,6,2023-08-06,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient-Party,76.5,0,2
HB-105571,City Hotel,0,24,2025,February,6,5,2025-02-05,2,5,1,0.0,0,BB,MAR,Groups,TA/TO,0,0,0,A,A,1,No Deposit,,407.0,0,Transient-Party,75.0,0,0
HB-004852,Resort Hotel,1,139,2024,April,14,4,2024-04-04,1,1,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,242.0,,0,Transient,94.0,0,1
HB-091751,City Hotel,0,265,2024,June,26,24,2024-06-24,0,2,2,0.0,0,HB,BEL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-016527,Resort Hotel,0,97,2023,August,34,27,2023-08-27,2,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,121.67,1,0
HB-041131,City Hotel,0,6,2023,August,32,12,2023-08-12,1,4,2,0.0,0,BB,TUN,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,75.0,0,0
HB-089782,City Hotel,0,8,2024,May,21,25,2024-05-25,0,1,2,0.0,0,SC,TUR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.0,0,0
HB-054647,City Hotel,1,0,2024,July,30,22,2024-07-22,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,E,0,No Deposit,,40.0,0,Transient-Party,75.0,0,0
HB-067321,City Hotel,1,61,2025,May,18,1,2025-05-01,1,3,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,187.2,0,1
HB-085163,City Hotel,0,29,2024,March,10,7,2024-03-07,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,73.73,0,1
HB-013011,Resort Hotel,1,191,2025,July,30,27,2025-07-27,2,5,2,2.0,0,HB,NLD,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,292.0,0,0
HB-060244,City Hotel,1,277,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-006413,Resort Hotel,1,286,2024,June,23,9,2024-06-09,2,3,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,110.0,0,2
HB-036500,Resort Hotel,0,118,2025,May,20,16,2025-05-16,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,42.95,0,1
HB-113781,City Hotel,0,90,2025,June,24,10,2025-06-10,1,1,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,100.8,0,0
HB-016697,Resort Hotel,1,240,2023,November,45,6,2023-11-06,2,6,2,0.0,0,HB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,240.0,,0,Transient,59.4,0,1
HB-023199,Resort Hotel,0,72,2024,April,15,9,2024-04-09,2,6,1,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,96.0,,0,Transient-Party,36.0,0,0
HB-034862,Resort Hotel,0,15,2025,March,13,30,2025-03-30,2,6,2,0.0,0,Undefined,PRT,Corporate,Corporate,0,0,0,A,A,1,No Deposit,,523.0,0,Transient-Party,120.0,0,0
HB-026124,Resort Hotel,0,68,2024,July,29,18,2024-07-18,1,3,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,C,C,0,No Deposit,,,0,Transient,232.0,1,0
HB-027325,Resort Hotel,0,119,2024,August,34,20,2024-08-20,2,5,3,0.0,0,FB,PRT,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,196.0,,0,Transient-Party,248.8,0,1
HB-088007,City Hotel,0,56,2024,April,17,24,2024-04-24,2,3,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient-Party,115.09,0,2
HB-086167,City Hotel,0,68,2024,March,12,23,2024-03-23,2,4,2,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,16.0,,0,Transient,61.5,0,0
HB-083483,City Hotel,0,10,2024,February,5,2,2024-02-02,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,92.0,0,0
HB-115702,City Hotel,0,96,2025,July,28,7,2025-07-07,1,2,1,1.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,8.0,,0,Transient-Party,123.83,0,1
HB-019757,Resort Hotel,0,112,2023,December,52,30,2023-12-30,0,3,1,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,A,A,2,No Deposit,,,0,Transient-Party,155.67,0,0
HB-105174,City Hotel,0,11,2025,January,5,27,2025-01-27,2,3,1,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,48.5,0,1
HB-027326,Resort Hotel,0,108,2024,August,34,20,2024-08-20,2,5,2,0.0,0,FB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,196.0,,0,Transient,249.0,0,0
HB-023470,Resort Hotel,0,172,2024,April,16,18,2024-04-18,3,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,115.0,,0,Transient,64.8,0,1
HB-092964,City Hotel,1,54,2025,March,13,26,2025-03-26,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,10,A,A,0,No Deposit,,40.0,0,Transient,67.0,0,0
HB-030721,Resort Hotel,0,68,2024,December,48,1,2024-12-01,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,43.8,1,2
HB-059812,City Hotel,1,38,2024,November,44,2,2024-11-02,0,4,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,77.23,0,3
HB-067373,City Hotel,1,54,2025,May,18,3,2025-05-03,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,126.0,0,0
HB-009884,Resort Hotel,1,17,2025,January,3,16,2025-01-16,1,2,1,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,55.0,0,0
HB-097233,City Hotel,0,18,2024,September,37,11,2024-09-11,2,1,2,0.0,0,HB,MAR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,137.57,0,1
HB-041897,City Hotel,0,55,2023,August,34,26,2023-08-26,0,2,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,60.0,0,0
HB-060145,City Hotel,1,86,2024,November,45,6,2024-11-06,2,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,146.6,0,1
HB-061323,City Hotel,1,71,2024,December,49,8,2024-12-08,0,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,1
HB-104612,City Hotel,0,34,2025,January,3,18,2025-01-18,0,1,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,D,0,No Deposit,19.0,,0,Transient-Party,75.0,0,0
HB-068302,City Hotel,1,104,2025,May,20,15,2025-05-15,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-056392,City Hotel,1,58,2024,September,36,4,2024-09-04,2,4,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,128.1,0,1
HB-116000,City Hotel,0,159,2025,July,28,9,2025-07-09,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,84.92,0,1
HB-045384,City Hotel,0,72,2023,October,43,28,2023-10-28,0,3,2,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,58,Transient-Party,85.67,0,0
HB-092985,City Hotel,0,114,2024,July,28,11,2024-07-11,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,15.0,,0,Transient,81.26,0,0
HB-015473,Resort Hotel,0,41,2023,July,29,19,2023-07-19,1,0,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,175.0,,0,Transient,92.0,0,0
HB-050266,City Hotel,1,106,2024,April,17,27,2024-04-27,2,9,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,102.39,0,0
HB-091083,City Hotel,0,11,2024,June,24,14,2024-06-14,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,D,D,0,No Deposit,,51.0,0,Transient-Party,90.0,0,0
HB-068156,City Hotel,1,85,2025,May,20,13,2025-05-13,2,5,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,119.57,0,1
HB-039759,Resort Hotel,0,60,2025,August,35,25,2025-08-25,0,2,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,C,1,No Deposit,240.0,,0,Transient,230.0,0,2
HB-022407,Resort Hotel,0,8,2024,March,12,21,2024-03-21,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,74.0,0,1
HB-047619,City Hotel,1,1,2024,February,9,28,2024-02-28,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,60.0,0,0
HB-067530,City Hotel,1,143,2025,May,18,4,2025-05-04,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,151.0,,0,Transient,100.0,0,0
HB-022978,Resort Hotel,0,18,2024,April,15,11,2024-04-11,1,0,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,4,No Deposit,,,0,Transient,56.0,0,0
HB-062235,City Hotel,1,17,2025,January,1,5,2025-01-05,1,3,1,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.47,0,1
HB-108454,City Hotel,0,79,2025,March,13,25,2025-03-25,2,1,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,42.0,,0,Transient,72.0,0,1
HB-104270,City Hotel,0,121,2025,January,2,6,2025-01-06,2,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,104.0,0,1
HB-046248,City Hotel,0,21,2023,December,52,27,2023-12-27,2,2,2,2.0,0,BB,USA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,187.0,0,1
HB-090029,City Hotel,0,7,2024,May,22,31,2024-05-31,0,1,1,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,A,0,No Deposit,,45.0,0,Transient,0.0,0,0
HB-042829,City Hotel,0,168,2023,September,37,11,2023-09-11,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,D,1,No Deposit,1.0,,0,Transient-Party,0.0,0,0
HB-034931,Resort Hotel,0,78,2025,April,14,6,2025-04-06,0,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,F,0,No Deposit,40.0,,0,Contract,50.85,0,0
HB-087933,City Hotel,0,74,2024,April,17,25,2024-04-25,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.5,0,1
HB-073410,City Hotel,1,248,2025,August,34,21,2025-08-21,1,0,2,2.0,0,BB,AUT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,189.0,0,0
HB-052701,City Hotel,0,282,2024,June,23,9,2024-06-09,0,3,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,48,Transient-Party,73.33,0,1
HB-051390,City Hotel,1,316,2024,May,20,19,2024-05-19,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-041846,City Hotel,1,50,2023,August,34,25,2023-08-25,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-088217,City Hotel,0,1,2025,March,12,21,2025-03-21,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,4,A,A,0,No Deposit,,219.0,0,Transient,89.0,0,1
HB-095578,City Hotel,0,40,2024,August,34,19,2024-08-19,0,2,3,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,228.6,1,2
HB-021060,Resort Hotel,0,0,2024,February,7,16,2024-02-16,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,,0,Transient,35.0,0,0
HB-043810,City Hotel,0,56,2023,September,39,25,2023-09-25,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,F,0,No Deposit,44.0,,0,Transient-Party,185.0,0,0
HB-100462,City Hotel,0,104,2024,October,43,25,2024-10-25,0,3,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.1,0,1
HB-079298,City Hotel,0,22,2023,October,42,21,2023-10-21,0,3,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,87.78,0,2
HB-007572,Resort Hotel,1,78,2024,August,33,15,2024-08-15,1,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,242.0,,0,Transient,219.0,0,0
HB-097797,City Hotel,0,0,2024,September,38,19,2024-09-19,1,1,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,168.0,0,2
HB-109315,City Hotel,0,25,2025,April,14,5,2025-04-05,0,4,3,1.0,0,BB,FRA,Direct,Direct,0,0,0,G,G,1,No Deposit,14.0,,0,Transient,295.0,0,1
HB-026819,Resort Hotel,0,18,2024,August,32,10,2024-08-10,0,2,2,2.0,0,HB,ESP,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,357.0,0,0
HB-079085,City Hotel,0,5,2023,October,42,19,2023-10-19,1,2,2,0.0,0,BB,POL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,112.0,,0,Transient-Party,90.0,0,0
HB-028738,Resort Hotel,0,7,2024,October,40,5,2024-10-05,1,4,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,0,No Deposit,,405.0,0,Transient-Party,50.0,0,1
HB-057137,City Hotel,1,280,2024,September,38,19,2024-09-19,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,35,Transient,110.0,0,0
HB-048635,City Hotel,1,35,2024,March,13,25,2024-03-25,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient,63.0,0,0
HB-028454,Resort Hotel,0,62,2024,September,39,27,2024-09-27,2,5,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,127.19,0,1
HB-055048,City Hotel,1,170,2024,August,31,3,2024-08-03,2,5,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.75,0,2
HB-055332,City Hotel,1,156,2024,August,32,11,2024-08-11,0,1,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.9,0,0
HB-008301,Resort Hotel,1,181,2024,September,38,21,2024-09-21,4,10,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,241.0,,0,Transient,114.73,0,0
HB-111602,City Hotel,0,58,2025,May,19,7,2025-05-07,2,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,120.0,0,0
HB-076764,City Hotel,1,395,2024,March,12,21,2024-03-21,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-084130,City Hotel,0,99,2024,February,8,19,2024-02-19,0,1,1,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,A,0,No Deposit,,67.0,0,Transient-Party,81.0,0,0
HB-104857,City Hotel,0,101,2025,January,4,21,2025-01-21,2,1,2,0.0,0,SC,KOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,1
HB-019117,Resort Hotel,0,11,2023,December,49,6,2023-12-06,2,0,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,83.0,0,1
HB-090710,City Hotel,0,21,2024,June,23,9,2024-06-09,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,102.85,0,2
HB-070732,City Hotel,1,153,2025,June,25,21,2025-06-21,0,4,1,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,A,0,Non Refund,,348.0,0,Transient,110.0,0,0
HB-028255,Resort Hotel,0,156,2024,September,38,21,2024-09-21,1,4,3,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient,130.0,0,1
HB-036072,Resort Hotel,0,211,2025,May,18,2,2025-05-02,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,C,0,No Deposit,40.0,,0,Contract,40.95,0,0
HB-090749,City Hotel,0,3,2024,June,24,10,2024-06-10,0,1,1,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,187.0,,0,Transient-Party,120.0,0,0
HB-074210,City Hotel,1,363,2023,October,41,15,2023-10-15,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-040729,City Hotel,1,33,2023,August,31,5,2023-08-05,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,15.0,,0,Transient-Party,67.5,0,1
HB-081806,City Hotel,1,117,2024,February,9,29,2024-02-29,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,44,Transient,75.0,0,0
HB-057737,City Hotel,1,219,2024,September,40,30,2024-09-30,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,120.0,0,0
HB-111141,City Hotel,0,93,2025,May,19,5,2025-05-05,0,2,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,7.0,,0,Transient,79.0,0,0
HB-035162,Resort Hotel,0,351,2025,April,15,8,2025-04-08,2,5,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,D,D,0,No Deposit,298.0,,0,Transient-Party,68.0,0,0
HB-107862,City Hotel,0,46,2025,March,11,15,2025-03-15,0,4,2,0.0,0,BB,HUN,Online TA,TA/TO,0,0,0,E,F,0,No Deposit,9.0,,0,Transient,125.8,0,2
HB-042140,City Hotel,0,8,2023,September,35,1,2023-09-01,0,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,7.0,,0,Transient,73.15,0,0
HB-012302,Resort Hotel,1,11,2025,June,26,23,2025-06-23,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,170.0,0,0
HB-056187,City Hotel,1,175,2024,August,35,31,2024-08-31,0,4,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,112.63,0,0
HB-118157,City Hotel,0,224,2025,August,33,14,2025-08-14,1,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,9.0,,0,Transient,117.0,0,1
HB-116503,City Hotel,0,180,2025,July,29,18,2025-07-18,0,3,2,0.0,0,BB,AUT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,16.0,,0,Transient,89.1,0,1
HB-050480,City Hotel,1,437,2024,May,18,2,2024-05-02,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-055573,City Hotel,1,148,2024,August,33,16,2024-08-16,2,5,3,0.0,0,BB,SVN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,138.14,0,0
HB-104334,City Hotel,0,343,2025,January,2,9,2025-01-09,1,2,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,71.1,0,3
HB-074091,City Hotel,1,321,2023,September,35,3,2023-09-03,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-044364,City Hotel,0,61,2023,October,40,4,2023-10-04,2,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,73.0,0,0
HB-117719,City Hotel,0,250,2025,August,32,4,2025-08-04,2,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,1
HB-003343,Resort Hotel,1,149,2023,December,49,5,2023-12-05,2,1,2,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,38.0,,0,Transient,68.0,0,0
HB-090215,City Hotel,0,7,2024,June,23,3,2024-06-03,0,1,2,0.0,0,BB,PRT,Complementary,Direct,0,0,0,G,G,0,No Deposit,,,0,Transient,0.0,1,2
HB-027527,Resort Hotel,0,22,2024,August,35,28,2024-08-28,2,2,2,0.0,0,HB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,224.0,1,0
HB-051681,City Hotel,1,158,2024,May,21,24,2024-05-24,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,31,Transient,130.0,0,0
HB-058878,City Hotel,1,0,2024,October,42,17,2024-10-17,1,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,1,No Deposit,,,0,Transient,179.0,0,0
HB-101547,City Hotel,0,57,2024,November,46,11,2024-11-11,1,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,64.37,0,1
HB-080095,City Hotel,1,333,2024,September,38,20,2024-09-20,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,58.0,,19,Transient,90.0,0,0
HB-026250,Resort Hotel,0,173,2024,July,29,19,2024-07-19,2,5,3,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Transient,123.64,0,2
HB-030977,Resort Hotel,0,22,2024,December,49,8,2024-12-08,0,3,2,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,38.0,,0,Transient-Party,80.0,0,0
HB-075535,City Hotel,1,355,2023,October,40,7,2023-10-07,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-088338,City Hotel,0,38,2024,May,18,2,2024-05-02,1,2,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,116.1,0,1
HB-115742,City Hotel,0,131,2025,July,27,6,2025-07-06,1,3,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,0
HB-062204,City Hotel,1,73,2025,January,1,4,2025-01-04,0,4,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,51.05,0,1
HB-002731,Resort Hotel,0,1,2023,October,43,29,2023-10-29,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,39.0,1,0
HB-089828,City Hotel,0,4,2024,May,21,23,2024-05-23,1,2,1,0.0,0,BB,IRL,Aviation,Corporate,0,0,0,A,A,0,No Deposit,,153.0,0,Transient,95.0,0,0
HB-001450,Resort Hotel,0,37,2023,August,35,30,2023-08-30,2,1,2,0.0,0,HB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,115.2,1,0
HB-078541,City Hotel,0,282,2023,October,41,10,2023-10-10,2,1,2,0.0,0,BB,FIN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,76.67,0,0
HB-098790,City Hotel,0,42,2024,October,40,2,2024-10-02,2,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,97.02,0,1
HB-022815,Resort Hotel,0,0,2024,April,14,6,2024-04-06,0,1,2,2.0,0,BB,GBR,Direct,Direct,0,0,0,C,C,0,No Deposit,,,0,Transient,100.0,0,0
HB-002213,Resort Hotel,1,74,2023,October,40,5,2023-10-05,3,6,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,86.0,0,2
HB-071858,City Hotel,1,171,2025,July,29,14,2025-07-14,0,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,116.1,0,0
HB-000389,Resort Hotel,0,1,2023,July,28,14,2023-07-14,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient,8.0,0,1
HB-055344,City Hotel,1,233,2024,August,32,11,2024-08-11,0,2,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient,86.62,0,0
HB-106279,City Hotel,0,1,2025,February,8,22,2025-02-22,0,2,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,F,1,No Deposit,,435.0,0,Transient,91.0,0,0
HB-047188,City Hotel,1,15,2024,February,7,12,2024-02-12,0,2,2,0.0,0,SC,AUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.0,0,0
HB-096201,City Hotel,0,96,2024,August,35,27,2024-08-27,2,1,2,0.0,0,SC,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,63.75,0,0
HB-025622,Resort Hotel,0,13,2024,June,26,27,2024-06-27,2,5,3,0.0,0,BB,PRT,Direct,Direct,0,0,0,H,H,2,No Deposit,,,0,Transient,194.0,1,0
HB-038063,Resort Hotel,0,164,2025,July,27,4,2025-07-04,0,5,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,241.0,,0,Transient,133.04,0,1
HB-069484,City Hotel,1,174,2025,June,22,1,2025-06-01,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,0,Transient,100.0,0,0
HB-107084,City Hotel,0,137,2025,March,10,6,2025-03-06,1,1,2,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,80.0,0,1
HB-002058,Resort Hotel,1,76,2023,September,39,29,2023-09-29,2,6,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,81.45,0,1
HB-111204,City Hotel,0,190,2025,May,19,7,2025-05-07,1,0,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,94.59,0,1
HB-119064,City Hotel,0,172,2025,August,35,25,2025-08-25,2,2,3,0.0,0,BB,FRO,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,9.0,,0,Transient,202.5,0,1
HB-086490,City Hotel,0,66,2024,March,13,31,2024-03-31,1,3,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,76.93,0,0
HB-013372,Resort Hotel,1,186,2025,August,33,12,2025-08-12,2,5,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,208.57,0,0
HB-006872,Resort Hotel,0,272,2024,July,28,8,2024-07-08,2,5,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,142.5,1,0
HB-115439,City Hotel,0,405,2025,July,27,4,2025-07-04,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,114.4,0,0
HB-005803,Resort Hotel,0,211,2024,May,20,14,2024-05-14,1,1,1,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,1,No Deposit,298.0,,0,Transient-Party,54.5,0,0
HB-009530,Resort Hotel,1,16,2024,December,49,7,2024-12-07,0,4,2,0.0,0,FB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,177.0,,0,Transient,96.0,0,0
HB-017342,Resort Hotel,0,0,2023,October,40,4,2023-10-04,2,0,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,F,F,1,No Deposit,,,0,Transient,76.0,1,0
HB-067073,City Hotel,1,130,2025,April,18,28,2025-04-28,1,2,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,24.87,0,0
HB-065513,City Hotel,1,58,2025,April,14,4,2025-04-04,0,4,2,1.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.0,0,0
HB-093683,City Hotel,0,175,2024,July,30,23,2024-07-23,1,1,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.5,0,1
HB-055212,City Hotel,1,63,2024,August,32,8,2024-08-08,1,0,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,168.3,0,1
HB-085854,City Hotel,0,0,2024,March,12,22,2024-03-22,0,1,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,99.0,0,1
HB-076376,City Hotel,0,273,2023,July,29,17,2023-07-17,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-063843,City Hotel,1,27,2025,February,8,23,2025-02-23,0,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,118.0,0,0
HB-032421,Resort Hotel,0,6,2025,January,4,24,2025-01-24,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,0
HB-086977,City Hotel,0,13,2024,April,15,10,2024-04-10,2,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.0,0,0
HB-093406,City Hotel,0,112,2024,July,29,18,2024-07-18,1,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.3,0,1
HB-046957,City Hotel,1,24,2024,January,5,29,2024-01-29,1,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient,77.25,0,1
HB-036898,Resort Hotel,0,172,2025,May,22,28,2025-05-28,2,2,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,410.0,,0,Transient,63.0,0,0
HB-014054,Resort Hotel,0,5,2023,November,47,25,2023-11-25,0,1,1,0.0,0,BB,,Corporate,Corporate,0,0,1,A,A,0,No Deposit,,94.0,0,Transient,25.0,1,0
HB-107433,City Hotel,0,67,2025,March,11,10,2025-03-10,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,106.2,1,1
HB-062696,City Hotel,1,559,2025,January,3,19,2025-01-19,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-098860,City Hotel,0,150,2024,October,40,3,2024-10-03,1,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,118.8,0,2
HB-016455,Resort Hotel,0,77,2023,August,34,24,2023-08-24,1,5,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,150.83,0,2
HB-106664,City Hotel,0,7,2025,February,9,27,2025-02-27,1,1,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.0,0,0
HB-088182,City Hotel,0,64,2024,April,18,29,2024-04-29,1,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,116.1,0,1
HB-058066,City Hotel,1,275,2024,October,40,5,2024-10-05,1,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,44.0,,0,Transient,90.0,0,0
HB-057782,City Hotel,1,179,2024,September,40,30,2024-09-30,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,113.4,0,0
HB-047059,City Hotel,0,41,2024,February,6,5,2024-02-05,2,3,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.43,0,0
HB-045764,City Hotel,1,98,2023,November,47,23,2023-11-23,1,2,1,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,84.0,0,0
HB-101871,City Hotel,0,76,2024,November,46,17,2024-11-17,0,3,2,1.0,0,BB,GBR,Direct,Direct,0,0,0,A,D,1,No Deposit,14.0,,0,Transient,92.2,0,2
HB-035040,Resort Hotel,0,110,2025,April,15,9,2025-04-09,2,1,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,66.0,0,1
HB-044435,City Hotel,1,97,2023,October,40,5,2023-10-05,1,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,140.0,0,0
HB-117821,City Hotel,0,66,2025,August,32,7,2025-08-07,1,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,85.0,,0,Transient,98.1,0,0
HB-005217,Resort Hotel,0,191,2024,April,17,22,2024-04-22,1,2,2,0.0,0,Undefined,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,85.33,0,0
HB-095625,City Hotel,0,50,2024,August,34,19,2024-08-19,1,2,2,2.0,0,BB,GBR,Direct,Direct,0,0,0,G,G,0,No Deposit,14.0,,0,Transient,240.3,0,0
HB-106477,City Hotel,0,134,2025,February,9,25,2025-02-25,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,75.0,0,0
HB-016869,Resort Hotel,0,222,2023,September,37,14,2023-09-14,1,1,2,0.0,0,HB,FRA,Groups,TA/TO,0,0,0,A,D,0,No Deposit,68.0,,0,Transient-Party,80.0,0,0
HB-081169,City Hotel,0,17,2024,May,19,8,2024-05-08,2,1,1,0.0,0,BB,GRC,Direct,Direct,1,0,1,A,A,0,No Deposit,,,0,Transient,101.0,0,0
HB-099154,City Hotel,0,17,2024,October,41,8,2024-10-08,1,1,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-081399,City Hotel,0,19,2023,December,49,5,2023-12-05,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,10.0,,0,Transient,69.0,0,0
HB-118618,City Hotel,0,163,2025,August,34,19,2025-08-19,2,2,2,0.0,0,BB,LUX,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient-Party,131.5,0,1
HB-013308,Resort Hotel,1,328,2025,August,32,7,2025-08-07,4,10,2,2.0,0,HB,FRA,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,292.0,0,0
HB-056718,City Hotel,1,208,2024,September,37,11,2024-09-11,2,1,2,0.0,0,SC,CN,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient,116.1,0,0
HB-117429,City Hotel,0,2,2025,August,31,3,2025-08-03,0,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,2,No Deposit,509.0,,0,Transient-Party,166.0,0,0
HB-038303,Resort Hotel,0,0,2025,July,28,13,2025-07-13,0,1,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,I,0,No Deposit,240.0,,0,Transient,120.0,0,2
HB-092088,City Hotel,0,71,2024,June,26,26,2024-06-26,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,91.47,0,1
HB-031859,Resort Hotel,0,0,2025,January,2,7,2025-01-07,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,44.0,0,0
HB-078756,City Hotel,0,12,2023,October,41,12,2023-10-12,1,3,2,0.0,0,BB,AUT,Corporate,Corporate,0,0,0,A,D,1,No Deposit,95.0,,0,Transient-Party,100.0,0,0
HB-049290,City Hotel,1,73,2024,April,15,9,2024-04-09,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,107.95,0,1
HB-085831,City Hotel,0,81,2024,March,12,18,2024-03-18,2,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,B,1,No Deposit,16.0,,0,Transient,59.5,0,0
HB-108857,City Hotel,0,66,2025,March,14,31,2025-03-31,1,2,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,2,No Deposit,14.0,,0,Transient,92.4,0,1
HB-000310,Resort Hotel,0,8,2023,July,28,12,2023-07-12,2,4,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,169.0,1,2
HB-002707,Resort Hotel,0,0,2023,October,43,27,2023-10-27,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,1,1
HB-011442,Resort Hotel,1,82,2025,May,19,8,2025-05-08,1,3,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,85.0,0,0
HB-071571,City Hotel,1,289,2025,July,28,7,2025-07-07,2,2,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,155.0,0,2
HB-001873,Resort Hotel,0,65,2023,September,38,19,2023-09-19,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,122.0,1,2
HB-050568,City Hotel,1,104,2024,May,18,4,2024-05-04,0,4,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,B,1,No Deposit,9.0,,0,Transient,111.78,0,0
HB-103437,City Hotel,0,142,2024,December,51,22,2024-12-22,0,2,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,1
HB-106506,City Hotel,0,134,2025,February,9,25,2025-02-25,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,75.0,0,0
HB-093060,City Hotel,0,9,2024,July,28,13,2024-07-13,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,9.0,,0,Transient,166.0,0,2
HB-006725,Resort Hotel,1,47,2024,June,26,27,2024-06-27,1,0,1,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,129.0,0,0
HB-065844,City Hotel,1,66,2025,April,15,9,2025-04-09,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-057962,City Hotel,1,184,2024,October,40,4,2024-10-04,0,3,1,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient,101.05,0,0
HB-052415,City Hotel,1,163,2024,June,23,5,2024-06-05,2,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,171.0,,0,Transient,100.0,0,0
HB-031508,Resort Hotel,0,0,2024,December,1,30,2024-12-30,0,1,2,2.0,0,BB,ESP,Direct,TA/TO,1,0,0,C,C,0,No Deposit,,,0,Transient,106.5,0,0
HB-080221,City Hotel,0,44,2023,November,45,11,2023-11-11,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Group,60.0,0,1
HB-118297,City Hotel,0,10,2025,August,33,16,2025-08-16,0,2,2,2.0,0,BB,FRA,Direct,Direct,0,0,0,F,F,0,No Deposit,14.0,,0,Transient,260.0,0,1
HB-094764,City Hotel,0,31,2024,August,32,7,2024-08-07,2,0,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,9.0,,0,Transient,168.3,0,0
HB-037126,Resort Hotel,0,379,2025,June,22,1,2025-06-01,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Contract,56.7,0,1
HB-010822,Resort Hotel,1,180,2025,April,14,6,2025-04-06,1,3,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,51.75,0,1
HB-054268,City Hotel,1,49,2024,July,28,11,2024-07-11,1,0,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.15,0,0
HB-092078,City Hotel,0,31,2024,June,26,26,2024-06-26,2,2,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.1,0,1
HB-072929,City Hotel,1,186,2025,August,32,10,2025-08-10,0,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,112.5,0,0
HB-071794,City Hotel,1,229,2025,July,28,12,2025-07-12,1,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-038960,Resort Hotel,0,178,2025,July,31,30,2025-07-30,2,3,2,1.0,0,HB,PRT,Direct,Direct,0,0,0,D,D,2,No Deposit,,,0,Transient,202.6,1,4
HB-093101,City Hotel,0,141,2024,July,28,14,2024-07-14,0,3,2,0.0,0,SC,CN,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient-Party,103.5,0,1
HB-049449,City Hotel,1,51,2024,April,15,14,2024-04-14,0,2,1,0.0,0,BB,HKG,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,123.3,0,0
HB-110029,City Hotel,0,122,2025,April,16,14,2025-04-14,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.57,0,2
HB-006172,Resort Hotel,1,277,2024,May,22,27,2024-05-27,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,46.98,0,1
HB-020473,Resort Hotel,0,9,2024,January,5,29,2024-01-29,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-100424,City Hotel,0,45,2024,October,43,26,2024-10-26,0,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.5,0,0
HB-104061,City Hotel,0,0,2025,January,3,16,2025-01-16,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,408.0,0,Transient,80.0,0,1
HB-061113,City Hotel,1,266,2024,December,49,2,2024-12-02,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,56.0,,0,Transient,75.0,0,0
HB-005277,Resort Hotel,1,95,2024,April,17,23,2024-04-23,4,10,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,95.0,,0,Transient-Party,47.0,0,0
HB-078554,City Hotel,0,282,2023,October,41,10,2023-10-10,2,1,2,0.0,0,BB,SWE,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,76.67,0,0
HB-077837,City Hotel,0,17,2023,September,39,26,2023-09-26,2,1,2,0.0,0,BB,ITA,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,170.0,0,0
HB-000745,Resort Hotel,1,41,2023,July,30,27,2023-07-27,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,164.0,0,0
HB-007805,Resort Hotel,1,213,2024,August,35,27,2024-08-27,2,5,3,0.0,0,Undefined,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,196.0,,0,Transient,178.28,0,1
HB-043030,City Hotel,0,9,2023,September,37,12,2023-09-12,2,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Contract,130.17,0,2
HB-091693,City Hotel,1,26,2024,June,26,26,2024-06-26,2,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,1,0,D,K,0,No Deposit,9.0,,0,Transient,152.67,0,0
HB-044887,City Hotel,0,48,2023,October,41,14,2023-10-14,1,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,78.54,0,1
HB-112543,City Hotel,0,0,2025,May,21,23,2025-05-23,0,2,2,0.0,0,BB,ITA,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,185.0,0,0
HB-028135,Resort Hotel,0,30,2024,September,38,19,2024-09-19,1,1,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,118.0,1,3
HB-064812,City Hotel,1,262,2025,March,11,16,2025-03-16,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.0,0,1
HB-059549,City Hotel,1,0,2024,October,44,29,2024-10-29,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,150.0,0,0
HB-068363,City Hotel,1,104,2025,May,20,15,2025-05-15,1,4,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,147.6,0,0
HB-012668,Resort Hotel,1,95,2025,July,28,11,2025-07-11,0,3,2,0.0,0,BB,HKG,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,199.0,0,1
HB-100414,City Hotel,0,100,2024,October,43,24,2024-10-24,1,3,2,1.0,0,HB,DEU,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,221.18,0,0
HB-066573,City Hotel,1,82,2025,April,17,21,2025-04-21,2,2,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,171.0,0,0
HB-059342,City Hotel,1,475,2024,October,43,27,2024-10-27,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-111298,City Hotel,0,144,2025,May,19,5,2025-05-05,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,128.25,1,2
HB-097642,City Hotel,0,315,2024,September,38,17,2024-09-17,1,1,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,38,Transient-Party,65.0,0,1
HB-062125,City Hotel,1,39,2025,January,1,2,2025-01-02,1,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.4,0,0
HB-022406,Resort Hotel,0,24,2024,March,11,17,2024-03-17,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,52.2,0,0
HB-070283,City Hotel,1,98,2025,June,24,14,2025-06-14,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,7.0,,0,Transient,190.0,0,1
HB-039396,Resort Hotel,0,44,2025,August,32,10,2025-08-10,2,5,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,196.0,,0,Transient-Party,262.0,0,0
HB-065768,City Hotel,1,59,2025,April,15,8,2025-04-08,1,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,133.0,0,0
HB-033748,Resort Hotel,0,9,2025,February,8,23,2025-02-23,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,74.86,0,2
HB-092949,City Hotel,0,20,2025,January,5,29,2025-01-29,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,7,A,A,0,No Deposit,,40.0,0,Transient,67.0,1,0
HB-034435,Resort Hotel,0,192,2025,March,12,18,2025-03-18,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,314.0,,0,Transient,46.64,0,1
HB-016768,Resort Hotel,0,243,2023,September,36,4,2023-09-04,2,5,2,1.0,0,FB,PRT,Offline TA/TO,TA/TO,0,0,0,A,C,0,No Deposit,156.0,,0,Contract,132.19,0,1
HB-048659,City Hotel,1,67,2024,March,13,26,2024-03-26,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient-Party,76.16,0,1
HB-011788,Resort Hotel,1,71,2025,May,22,30,2025-05-30,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,126.67,0,0
HB-013314,Resort Hotel,1,34,2025,August,32,8,2025-08-08,0,4,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,5.0,,0,Transient,216.0,0,0
HB-035646,Resort Hotel,0,252,2025,April,17,22,2025-04-22,2,5,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,D,D,2,No Deposit,273.0,,0,Transient-Party,76.8,0,0
HB-054112,City Hotel,1,365,2024,July,27,7,2024-07-07,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-111374,City Hotel,0,117,2025,May,19,7,2025-05-07,2,1,1,0.0,0,BB,CHE,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,108.0,0,1
HB-025137,Resort Hotel,0,2,2024,November,47,24,2024-11-24,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,3,A,D,0,No Deposit,,154.0,0,Transient,27.0,0,0
HB-116876,City Hotel,0,56,2025,July,30,24,2025-07-24,1,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.0,0,1
HB-111085,City Hotel,0,322,2025,May,19,5,2025-05-05,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,75.0,0,0
HB-062735,City Hotel,1,178,2025,January,4,20,2025-01-20,1,2,2,0.0,0,BB,BLR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.0,0,0
HB-044935,City Hotel,1,100,2023,October,42,16,2023-10-16,0,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient,108.0,0,0
HB-103077,City Hotel,0,0,2024,December,49,8,2024-12-08,0,3,2,0.0,0,BB,BRA,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,128.0,0,0
HB-061513,City Hotel,1,58,2024,December,50,15,2024-12-15,0,3,2,0.0,0,SC,LUX,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,0
HB-000789,Resort Hotel,0,102,2023,July,30,29,2023-07-29,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,90.95,0,1
HB-003719,Resort Hotel,1,161,2023,December,52,31,2023-12-31,0,2,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,148.1,0,1
HB-019113,Resort Hotel,0,5,2023,December,49,5,2023-12-05,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,54.4,0,0
HB-073878,City Hotel,1,321,2023,September,35,3,2023-09-03,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-087541,City Hotel,0,2,2024,April,16,20,2024-04-20,0,2,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient,127.0,0,2
HB-100931,City Hotel,0,16,2024,October,44,31,2024-10-31,1,3,2,0.0,0,HB,FRA,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,161.0,0,0
HB-071916,City Hotel,1,476,2025,July,29,15,2025-07-15,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,0
HB-105692,City Hotel,0,26,2025,February,7,11,2025-02-11,2,1,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-028090,Resort Hotel,0,27,2024,September,38,16,2024-09-16,2,2,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,H,H,1,No Deposit,240.0,,0,Transient,174.5,0,1
HB-067675,City Hotel,1,99,2025,May,19,6,2025-05-06,1,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,135.0,0,0
HB-034566,Resort Hotel,0,226,2025,March,13,25,2025-03-25,2,2,1,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,314.0,,0,Transient-Party,28.64,0,0
HB-094296,City Hotel,0,2,2024,December,51,21,2024-12-21,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,6,A,A,0,No Deposit,,40.0,0,Transient,67.0,0,1
HB-030684,Resort Hotel,0,0,2024,November,48,30,2024-11-30,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,43.0,0,0
HB-059150,City Hotel,1,240,2024,October,43,21,2024-10-21,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,110.0,0,0
HB-037165,Resort Hotel,0,2,2025,June,23,6,2025-06-06,0,3,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,180.33,0,1
HB-085776,City Hotel,0,21,2024,March,12,20,2024-03-20,1,0,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,106.0,0,1
HB-043449,City Hotel,1,74,2023,September,38,18,2023-09-18,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-085899,City Hotel,0,157,2024,March,12,19,2024-03-19,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,90.0,0,1
HB-056707,City Hotel,1,52,2024,September,37,11,2024-09-11,2,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,86.0,,14,Transient-Party,130.0,0,0
HB-097559,City Hotel,0,286,2024,September,38,16,2024-09-16,0,2,1,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,3.0,,44,Transient-Party,91.0,0,0
HB-067660,City Hotel,1,206,2025,May,19,5,2025-05-05,2,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,1
HB-027502,Resort Hotel,0,25,2024,August,35,31,2024-08-31,0,1,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,260.0,0,0
HB-075351,City Hotel,1,311,2023,August,34,24,2023-08-24,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-108544,City Hotel,0,158,2025,March,13,27,2025-03-27,1,1,2,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,95.0,0,1
HB-009481,Resort Hotel,1,183,2024,December,49,3,2024-12-03,2,1,2,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,38.0,,0,Transient,72.0,0,0
HB-026785,Resort Hotel,0,34,2024,August,32,7,2024-08-07,2,2,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,221.0,0,0
HB-107066,City Hotel,0,33,2025,March,9,2,2025-03-02,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,100.3,0,0
HB-107917,City Hotel,0,130,2025,March,12,17,2025-03-17,1,2,2,2.0,0,BB,ITA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,156.6,0,1
HB-099917,City Hotel,0,70,2024,October,42,18,2024-10-18,0,2,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.2,0,2
HB-033093,Resort Hotel,0,98,2025,February,7,10,2025-02-10,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,53.8,1,2
HB-021467,Resort Hotel,0,3,2024,February,9,27,2024-02-27,1,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,E,0,No Deposit,171.0,,0,Transient,55.0,0,0
HB-080677,City Hotel,0,32,2023,November,47,20,2023-11-20,0,2,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,119.0,,0,Transient-Party,73.0,0,0
HB-033461,Resort Hotel,0,19,2025,February,8,22,2025-02-22,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,154.0,0,Transient,35.0,0,0
HB-028363,Resort Hotel,0,8,2024,September,40,30,2024-09-30,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,C,1,No Deposit,,448.0,0,Transient-Party,99.0,0,0
HB-030615,Resort Hotel,0,1,2024,November,48,26,2024-11-26,1,1,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,69.0,1,0
HB-048536,City Hotel,1,78,2024,March,13,25,2024-03-25,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,154.0,,0,Transient,100.0,0,0
HB-056737,City Hotel,1,67,2024,September,37,12,2024-09-12,1,0,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,168.3,0,1
HB-026072,Resort Hotel,0,186,2024,July,28,10,2024-07-10,4,7,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,143.0,,0,Transient,128.65,0,0
HB-057025,City Hotel,1,205,2024,September,38,16,2024-09-16,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,120.0,0,0
HB-104887,City Hotel,0,26,2025,January,4,25,2025-01-25,1,4,2,1.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,99.88,0,2
HB-010534,Resort Hotel,1,96,2025,March,11,12,2025-03-12,4,7,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,8.0,0,0
HB-073348,City Hotel,1,162,2025,August,34,19,2025-08-19,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,140.0,0,0
HB-101317,City Hotel,0,209,2024,November,45,6,2024-11-06,2,2,1,0.0,0,BB,SVK,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,152.1,0,1
HB-076848,City Hotel,0,204,2023,August,32,12,2023-08-12,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,76.5,0,3
HB-068036,City Hotel,1,23,2025,May,19,11,2025-05-11,1,3,2,0.0,0,SC,ARG,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,175.0,0,1
HB-005451,Resort Hotel,1,108,2024,April,18,29,2024-04-29,2,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,84.0,0,0
HB-042037,City Hotel,1,104,2023,August,35,30,2023-08-30,2,1,2,0.0,0,HB,ESP,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,90.0,0,0
HB-062603,City Hotel,1,64,2025,January,3,16,2025-01-16,2,5,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,0
HB-084646,City Hotel,0,115,2024,February,9,27,2024-02-27,2,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,134.0,,0,Transient-Party,76.0,0,0
HB-045062,City Hotel,1,102,2023,October,42,16,2023-10-16,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-118461,City Hotel,0,114,2025,August,33,17,2025-08-17,0,3,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,195.0,0,1
HB-087518,City Hotel,0,1,2024,April,16,18,2024-04-18,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,9.0,,0,Transient,122.67,0,0
HB-075571,City Hotel,0,257,2023,July,26,1,2023-07-01,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,101.5,0,0
HB-060638,City Hotel,1,2,2024,November,46,17,2024-11-17,0,3,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,168.0,0,1
HB-040656,City Hotel,0,1,2023,August,31,5,2023-08-05,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,75.0,0,1
HB-097550,City Hotel,0,62,2024,September,38,21,2024-09-21,0,1,1,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,1,A,A,0,No Deposit,3.0,,0,Transient-Party,91.0,0,0
HB-080869,City Hotel,0,25,2023,November,47,22,2023-11-22,2,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,65.0,0,0
HB-107073,City Hotel,0,8,2025,February,9,27,2025-02-27,3,5,2,0.0,0,SC,RUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,3
HB-075757,City Hotel,1,312,2023,August,34,25,2023-08-25,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-005908,Resort Hotel,0,213,2024,May,20,16,2024-05-16,1,1,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,298.0,,0,Transient-Party,54.5,0,0
HB-106256,City Hotel,0,12,2025,February,8,21,2025-02-21,0,3,1,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,10.0,,0,Transient,76.33,0,0
HB-113307,City Hotel,0,118,2025,June,23,2,2025-06-02,1,2,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,126.0,0,1
HB-118403,City Hotel,0,346,2025,August,33,12,2025-08-12,2,6,2,0.0,0,HB,ROU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,21.0,,0,Transient,116.15,0,0
HB-041890,City Hotel,0,55,2023,August,34,26,2023-08-26,0,2,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-096251,City Hotel,0,4,2024,August,35,29,2024-08-29,1,1,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,80.0,0,0
HB-096753,City Hotel,0,19,2024,September,36,6,2024-09-06,0,2,1,0.0,0,SC,FIN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.0,0,1
HB-003012,Resort Hotel,1,37,2023,November,45,11,2023-11-11,0,4,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,281.0,,0,Contract,48.0,0,2
HB-067034,City Hotel,1,111,2025,April,17,27,2025-04-27,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,0,Transient,120.0,0,0
HB-000706,Resort Hotel,0,50,2023,July,30,25,2023-07-25,2,5,3,0.0,0,BB,PRT,Direct,Direct,0,0,0,G,G,0,No Deposit,,,0,Transient,195.0,1,0
HB-103641,City Hotel,0,108,2024,December,52,25,2024-12-25,2,2,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,140.0,0,2
HB-071919,City Hotel,1,476,2025,July,29,15,2025-07-15,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,0
HB-051470,City Hotel,1,211,2024,May,21,20,2024-05-20,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,111,Transient,100.0,0,0
HB-040668,City Hotel,1,1,2023,August,31,5,2023-08-05,0,2,2,,0,BB,PRT,Direct,Undefined,0,0,0,B,B,0,No Deposit,14.0,,0,Transient-Party,12.0,0,1
HB-027770,Resort Hotel,0,0,2024,September,37,9,2024-09-09,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,145.0,0,0
HB-053304,City Hotel,1,88,2024,June,25,17,2024-06-17,0,2,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,116.1,0,0
HB-036121,Resort Hotel,0,6,2025,May,19,9,2025-05-09,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,E,0,No Deposit,,371.0,0,Transient,76.0,0,0
HB-021982,Resort Hotel,0,1,2024,March,11,14,2024-03-14,1,0,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,0
HB-069522,City Hotel,1,174,2025,June,22,1,2025-06-01,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,110.0,0,0
HB-037168,Resort Hotel,0,141,2025,June,23,6,2025-06-06,0,3,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,,0,Transient,126.0,0,2
HB-049629,City Hotel,1,57,2024,April,16,16,2024-04-16,2,1,2,2.0,0,BB,IRL,Online TA,TA/TO,0,0,0,F,F,6,No Deposit,9.0,,0,Transient,177.3,0,0
HB-067484,City Hotel,1,148,2025,May,18,4,2025-05-04,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,171.0,,0,Transient,95.0,0,0
HB-023171,Resort Hotel,0,249,2024,October,42,14,2024-10-14,2,5,2,0.0,0,BB,GBR,Groups,Direct,0,0,3,A,E,0,No Deposit,273.0,,0,Transient-Party,60.36,0,0
HB-075795,City Hotel,1,323,2023,September,36,5,2023-09-05,2,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,60.0,0,0
HB-078062,City Hotel,0,14,2023,September,39,30,2023-09-30,0,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,110.5,0,1
HB-072013,City Hotel,1,183,2025,July,29,17,2025-07-17,1,4,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,0
HB-072719,City Hotel,1,2,2025,August,32,4,2025-08-04,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,E,2,No Deposit,,,0,Transient,75.0,0,2
HB-107798,City Hotel,0,115,2025,March,11,16,2025-03-16,0,3,2,0.0,0,SC,LVA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,2
HB-076950,City Hotel,1,342,2023,September,38,24,2023-09-24,2,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-099052,City Hotel,0,9,2024,October,41,8,2024-10-08,0,1,1,0.0,0,BB,SWE,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,148.75,0,0
HB-095848,City Hotel,0,29,2024,August,34,23,2024-08-23,0,2,2,0.0,0,BB,SWE,Direct,Direct,0,0,0,A,A,2,No Deposit,14.0,,0,Transient,127.15,1,0
HB-094788,City Hotel,0,0,2024,August,32,9,2024-08-09,0,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,158.0,0,0
HB-006382,Resort Hotel,0,322,2024,June,23,6,2024-06-06,3,7,1,2.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,C,2,No Deposit,40.0,,0,Contract,78.5,0,2
HB-040576,City Hotel,1,117,2023,August,31,1,2023-08-01,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-001385,Resort Hotel,0,49,2023,August,34,27,2023-08-27,2,5,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,156.0,,0,Contract,90.39,0,0
HB-018584,Resort Hotel,0,0,2023,November,47,23,2023-11-23,1,0,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,38.0,1,0
HB-056370,City Hotel,1,62,2024,September,36,4,2024-09-04,1,0,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,0
HB-013871,Resort Hotel,0,6,2024,April,14,6,2024-04-06,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,2,A,D,0,No Deposit,,94.0,0,Transient,42.0,1,0
HB-011626,Resort Hotel,1,107,2025,May,21,22,2025-05-22,1,2,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,117.0,0,0
HB-056803,City Hotel,1,52,2024,September,37,14,2024-09-14,0,3,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,207.9,0,1
HB-000601,Resort Hotel,0,5,2023,July,29,21,2023-07-21,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,F,0,No Deposit,,154.0,0,Transient,99.5,0,0
HB-092262,City Hotel,0,46,2024,July,27,1,2024-07-01,0,2,2,0.0,0,SC,LBN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,1
HB-028014,Resort Hotel,0,336,2024,September,37,15,2024-09-15,0,3,2,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,E,0,No Deposit,,223.0,0,Transient-Party,74.0,1,0
HB-044720,City Hotel,1,174,2023,October,41,10,2023-10-10,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,70.0,0,0
HB-034055,Resort Hotel,0,171,2025,March,10,5,2025-03-05,2,5,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,E,E,0,No Deposit,298.0,,0,Transient-Party,73.0,0,0
HB-044701,City Hotel,1,66,2023,October,41,9,2023-10-09,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,75.0,0,0
HB-058373,City Hotel,1,182,2024,October,41,12,2024-10-12,0,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.1,0,0
HB-077797,City Hotel,0,3,2023,September,39,25,2023-09-25,1,2,2,0.0,0,BB,JPN,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,170.0,0,0
HB-111261,City Hotel,0,120,2025,May,19,5,2025-05-05,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,3
HB-053314,City Hotel,1,61,2024,June,25,17,2024-06-17,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.9,0,0
HB-059174,City Hotel,0,304,2024,October,43,21,2024-10-21,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,74.15,0,1
HB-036047,Resort Hotel,0,1,2025,May,19,6,2025-05-06,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,72.5,0,2
HB-104269,City Hotel,0,0,2025,January,2,7,2025-01-07,2,1,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.29,0,0
HB-055433,City Hotel,1,188,2024,August,33,13,2024-08-13,1,1,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.3,0,0
HB-111936,City Hotel,0,5,2025,May,20,17,2025-05-17,0,1,1,0.0,0,BB,ESP,Corporate,Corporate,0,0,0,D,F,0,No Deposit,,150.0,0,Transient,148.5,0,0
HB-113331,City Hotel,0,167,2025,June,23,2,2025-06-02,2,2,2,0.0,0,SC,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,141.0,0,2
HB-070978,City Hotel,1,105,2025,June,26,26,2025-06-26,1,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-047424,City Hotel,1,38,2024,February,8,20,2024-02-20,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,69.44,0,0
HB-087820,City Hotel,0,62,2024,April,17,24,2024-04-24,2,1,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,137.7,0,2
HB-004632,Resort Hotel,1,106,2024,March,12,24,2024-03-24,1,3,2,0.0,0,FB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,68.0,,0,Transient,84.0,0,0
HB-088831,City Hotel,0,3,2024,June,26,27,2024-06-27,1,0,2,0.0,0,BB,PRT,Direct,Direct,1,0,1,A,A,2,No Deposit,14.0,,0,Transient,143.1,1,0
HB-100089,City Hotel,0,192,2024,October,43,21,2024-10-21,0,2,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,29.0,,0,Transient-Party,95.0,0,0
HB-002027,Resort Hotel,0,0,2023,September,39,28,2023-09-28,1,0,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,68.53,1,1
HB-053377,City Hotel,1,38,2024,June,25,19,2024-06-19,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,52.0,,0,Transient,81.0,0,0
HB-085653,City Hotel,0,16,2024,March,12,18,2024-03-18,0,1,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,103.0,0,1
HB-118693,City Hotel,0,181,2025,August,34,18,2025-08-18,2,5,3,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,213.81,0,0
HB-055010,City Hotel,1,131,2024,August,31,2,2024-08-02,0,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.3,0,0
HB-003665,Resort Hotel,0,165,2023,December,52,30,2023-12-30,0,4,1,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,308.0,,122,Transient-Party,0.0,0,0
HB-099563,City Hotel,0,6,2024,October,41,13,2024-10-13,0,1,1,0.0,0,BB,ESP,Online TA,GDS,0,0,0,A,A,0,No Deposit,195.0,,0,Transient,95.0,0,0
HB-020616,Resort Hotel,0,7,2024,February,5,4,2024-02-04,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,39.0,0,2
HB-018117,Resort Hotel,0,1,2023,November,44,3,2023-11-03,0,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,36.0,0,1
HB-087279,City Hotel,0,74,2024,April,15,13,2024-04-13,0,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,99.45,0,1
HB-077645,City Hotel,0,7,2023,September,38,22,2023-09-22,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,126.0,0,2
HB-015421,Resort Hotel,0,189,2023,July,27,9,2023-07-09,2,5,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,5.0,,0,Transient,96.3,0,0
HB-067059,City Hotel,1,19,2025,April,18,28,2025-04-28,0,2,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,8.0,,0,Transient,290.01,0,3
HB-062043,City Hotel,1,10,2024,December,1,30,2024-12-30,2,3,2,0.0,0,BB,LUX,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,120.36,0,2
HB-116289,City Hotel,0,117,2025,July,29,15,2025-07-15,1,1,2,2.0,0,BB,FIN,Direct,Direct,0,0,0,F,F,0,No Deposit,14.0,,0,Transient,225.0,0,0
HB-109796,City Hotel,0,133,2025,April,16,15,2025-04-15,1,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.5,0,1
HB-048945,City Hotel,1,37,2024,April,14,3,2024-04-03,2,0,3,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,150.3,0,0
HB-055246,City Hotel,1,125,2024,August,32,8,2024-08-08,1,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.3,0,0
HB-067493,City Hotel,1,143,2025,May,18,4,2025-05-04,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,56.0,,0,Transient,110.0,0,0
HB-009663,Resort Hotel,1,90,2024,December,52,23,2024-12-23,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,37.8,0,0
HB-079491,City Hotel,0,5,2023,October,43,27,2023-10-27,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-013330,Resort Hotel,1,95,2025,August,32,10,2025-08-10,2,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,230.0,0,0
HB-043555,City Hotel,0,82,2023,September,38,19,2023-09-19,2,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.25,0,1
HB-075407,City Hotel,1,323,2023,September,36,5,2023-09-05,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-100387,City Hotel,0,31,2024,October,43,25,2024-10-25,0,3,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,149.0,0,2
HB-072916,City Hotel,1,201,2025,August,32,9,2025-08-09,0,4,3,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,175.5,0,0
HB-072178,City Hotel,1,138,2025,July,30,23,2025-07-23,2,1,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.5,0,0
HB-065971,City Hotel,1,269,2025,April,15,11,2025-04-11,0,4,2,0.0,0,BB,DNK,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,123.3,0,1
HB-051626,City Hotel,1,65,2024,May,21,23,2024-05-23,1,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,2,No Deposit,14.0,,0,Transient-Party,85.0,0,0
HB-036136,Resort Hotel,0,143,2025,May,19,8,2025-05-08,1,2,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,C,0,No Deposit,410.0,,0,Transient,42.28,0,0
HB-055803,City Hotel,1,224,2024,August,34,21,2024-08-21,2,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.75,0,0
HB-003384,Resort Hotel,1,149,2023,December,49,5,2023-12-05,2,1,2,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,38.0,,0,Transient,68.0,0,0
HB-007229,Resort Hotel,1,124,2024,July,31,29,2024-07-29,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,178.67,0,0
HB-104827,City Hotel,0,24,2025,January,4,21,2025-01-21,1,1,3,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,147.5,0,1
HB-109512,City Hotel,0,36,2025,April,15,10,2025-04-10,1,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,5
HB-052364,City Hotel,1,275,2024,June,23,4,2024-06-04,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,5.0,,69,Transient,62.8,0,0
HB-098283,City Hotel,0,20,2024,September,39,24,2024-09-24,2,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,129.0,0,2
HB-083852,City Hotel,0,1,2024,February,7,13,2024-02-13,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,95.0,0,2
HB-045755,City Hotel,0,98,2023,November,47,23,2023-11-23,1,2,1,0.0,0,BB,EGY,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,70.0,0,0
HB-093771,City Hotel,0,40,2024,July,30,26,2024-07-26,0,1,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,39.0,,0,Transient-Party,95.0,0,0
HB-094390,City Hotel,0,0,2025,May,21,24,2025-05-24,0,1,1,0.0,0,BB,PRT,Complementary,Direct,1,4,11,E,E,0,No Deposit,,45.0,0,Transient,0.0,0,3
HB-093897,City Hotel,0,121,2024,July,30,27,2024-07-27,0,1,2,1.0,0,HB,FRA,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,9.0,,0,Transient,173.25,1,1
HB-097343,City Hotel,0,346,2024,September,37,13,2024-09-13,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-088976,City Hotel,0,102,2024,May,20,13,2024-05-13,1,2,3,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,105.0,0,1
HB-093133,City Hotel,0,134,2024,July,28,13,2024-07-13,0,4,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,89.25,0,0
HB-009913,Resort Hotel,1,124,2025,January,4,22,2025-01-22,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,37.8,0,1
HB-020874,Resort Hotel,0,32,2024,February,7,12,2024-02-12,0,1,2,0.0,0,HB,PRT,Complementary,Direct,0,0,0,A,D,1,No Deposit,,,0,Transient,56.0,1,0
HB-023457,Resort Hotel,0,160,2024,April,16,18,2024-04-18,3,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,115.0,,0,Transient,66.8,0,1
HB-083488,City Hotel,1,8,2024,February,8,25,2024-02-25,0,2,1,0.0,0,BB,ESP,Direct,Direct,1,1,1,A,A,0,No Deposit,,,0,Transient,80.0,0,0
HB-066375,City Hotel,1,194,2025,April,16,18,2025-04-18,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,E,E,3,No Deposit,9.0,,0,Transient,162.0,0,1
HB-093564,City Hotel,0,292,2024,July,29,21,2024-07-21,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,0
HB-026172,Resort Hotel,0,177,2024,July,29,17,2024-07-17,2,5,2,1.0,0,HB,PRT,Direct,Direct,0,0,0,E,E,1,No Deposit,250.0,,0,Transient,197.0,0,2
HB-019675,Resort Hotel,0,16,2023,December,51,23,2023-12-23,2,6,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,171.0,,0,Transient,72.5,0,0
HB-089346,City Hotel,0,104,2024,May,20,17,2024-05-17,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,140.4,0,1
HB-081552,City Hotel,1,223,2024,June,24,14,2024-06-14,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,133.0,,40,Transient,135.0,0,0
HB-032289,Resort Hotel,0,107,2025,January,3,17,2025-01-17,0,5,3,1.0,0,BB,POL,Online TA,TA/TO,0,0,0,H,H,1,No Deposit,240.0,,0,Transient,94.0,1,0
HB-000996,Resort Hotel,1,122,2023,August,32,9,2023-08-09,2,4,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,166.0,0,2
HB-093123,City Hotel,0,125,2024,July,28,10,2024-07-10,2,5,2,0.0,0,SC,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,63.75,0,2
HB-010363,Resort Hotel,1,181,2025,March,9,1,2025-03-01,6,19,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,440.0,,0,Transient-Party,58.6,0,0
HB-048067,City Hotel,1,99,2024,March,11,15,2024-03-15,0,4,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,73.95,0,0
HB-003567,Resort Hotel,0,44,2023,December,51,24,2023-12-24,0,2,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,27.0,0,0
HB-004606,Resort Hotel,1,106,2024,March,12,24,2024-03-24,1,3,2,0.0,0,FB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,68.0,,0,Transient,84.0,0,0
HB-093230,City Hotel,0,79,2024,July,28,11,2024-07-11,3,5,3,1.0,0,BB,NOR,Direct,Direct,0,0,0,E,F,0,No Deposit,14.0,,0,Transient,161.11,0,0
HB-080860,City Hotel,0,0,2024,February,7,15,2024-02-15,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,6,A,A,0,No Deposit,,148.0,0,Transient,79.0,0,0
HB-014106,Resort Hotel,0,1,2024,January,2,14,2024-01-14,0,1,1,0.0,0,BB,,Direct,Direct,0,0,1,A,E,0,No Deposit,,144.0,0,Transient-Party,30.0,1,0
HB-013724,Resort Hotel,1,327,2025,August,35,27,2025-08-27,2,5,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,167.18,0,1
HB-005585,Resort Hotel,1,200,2024,May,18,2,2024-05-02,2,5,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,101.7,0,1
HB-086375,City Hotel,0,51,2024,March,13,30,2024-03-30,0,3,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,123.3,0,0
HB-049466,City Hotel,1,281,2024,April,15,14,2024-04-14,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-066626,City Hotel,1,393,2025,April,17,22,2025-04-22,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-068781,City Hotel,1,75,2025,May,21,20,2025-05-20,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,90.0,0,0
HB-104315,City Hotel,0,11,2025,May,19,8,2025-05-08,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,4,A,D,1,No Deposit,,408.0,0,Transient,99.5,0,0
HB-049693,City Hotel,0,105,2024,April,16,17,2024-04-17,2,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,96.3,0,0
HB-104389,City Hotel,0,52,2025,January,2,10,2025-01-10,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,79.2,0,1
HB-118545,City Hotel,0,1,2025,August,34,21,2025-08-21,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,140.0,0,0
HB-095845,City Hotel,0,7,2024,August,34,24,2024-08-24,0,1,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,137.0,1,2
HB-022560,Resort Hotel,0,0,2024,March,13,28,2024-03-28,1,0,1,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,48.0,0,0
HB-099237,City Hotel,0,3,2024,October,41,10,2024-10-10,1,0,1,0.0,0,SC,ESP,Online TA,GDS,0,0,0,A,D,0,No Deposit,195.0,,0,Transient,134.0,0,0
HB-046908,City Hotel,1,15,2024,January,4,25,2024-01-25,4,10,1,0.0,0,BB,DZA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,75.5,0,1
HB-087643,City Hotel,0,13,2024,April,16,19,2024-04-19,0,4,1,0.0,0,BB,GRC,Aviation,Corporate,0,0,0,A,A,0,No Deposit,153.0,,0,Transient,95.0,0,0
HB-069801,City Hotel,1,23,2025,June,23,7,2025-06-07,0,2,2,0.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,52.0,,0,Transient,166.5,0,0
HB-090071,City Hotel,0,1,2024,June,22,1,2024-06-01,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.0,0,0
HB-092374,City Hotel,0,152,2024,July,27,1,2024-07-01,2,2,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.75,0,1
HB-023027,Resort Hotel,0,42,2024,April,14,5,2024-04-05,2,7,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,C,0,No Deposit,75.0,,0,Transient,64.78,0,0
HB-095457,City Hotel,0,320,2024,August,33,18,2024-08-18,0,2,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,90.0,0,0
HB-117740,City Hotel,0,263,2025,August,32,8,2025-08-08,0,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,2
HB-082453,City Hotel,0,39,2023,December,52,29,2023-12-29,0,1,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,107.0,0,1
HB-089432,City Hotel,0,1,2024,May,21,20,2024-05-20,0,1,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,197.0,0,0
HB-115531,City Hotel,0,74,2025,July,27,5,2025-07-05,0,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,85.0,,0,Transient,80.1,0,0
HB-116351,City Hotel,0,158,2025,July,29,17,2025-07-17,1,0,3,0.0,0,BB,AUS,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,9.0,,0,Transient,152.1,0,1
HB-104880,City Hotel,0,16,2025,January,4,20,2025-01-20,2,2,0,2.0,0,BB,PRT,Direct,Direct,0,0,0,B,B,1,No Deposit,,,0,Transient-Party,6.0,1,1
HB-110509,City Hotel,0,74,2025,April,17,23,2025-04-23,2,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-002079,Resort Hotel,0,93,2023,September,39,30,2023-09-30,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,2.0,,0,Transient,71.93,0,0
HB-029910,Resort Hotel,0,7,2024,November,45,7,2024-11-07,1,1,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,57.97,1,1
HB-089450,City Hotel,0,22,2024,May,21,21,2024-05-21,0,1,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,156.0,0,1
HB-114834,City Hotel,0,93,2025,June,25,22,2025-06-22,2,3,2,0.0,0,BB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,85.0,0,0
HB-098856,City Hotel,0,0,2024,October,40,5,2024-10-05,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,150.0,0,1
HB-070406,City Hotel,1,151,2025,June,25,16,2025-06-16,1,2,3,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,162.0,0,1
HB-064512,City Hotel,1,127,2025,March,11,11,2025-03-11,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,0,Transient,80.0,0,0
HB-044829,City Hotel,0,60,2023,October,41,12,2023-10-12,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,3.0,,0,Transient-Party,65.0,0,1
HB-018932,Resort Hotel,0,19,2023,December,48,2,2023-12-02,0,2,1,0.0,0,BB,DEU,Groups,Corporate,0,0,0,A,A,0,No Deposit,,343.0,0,Transient-Party,36.0,0,0
HB-051964,City Hotel,0,172,2024,May,21,26,2024-05-26,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,123.25,0,0
HB-086962,City Hotel,0,71,2024,April,15,8,2024-04-08,2,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,107.95,0,0
HB-095743,City Hotel,0,156,2024,August,34,21,2024-08-21,2,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,103.5,1,0
HB-077553,City Hotel,0,5,2023,September,38,20,2023-09-20,2,0,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,92.4,0,1
HB-115523,City Hotel,0,152,2025,July,27,6,2025-07-06,0,1,3,0.0,0,BB,SVK,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,152.1,0,0
HB-009109,Resort Hotel,1,206,2024,October,43,27,2024-10-27,2,5,1,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,E,E,3,No Deposit,240.0,,0,Transient-Party,65.43,0,1
HB-100694,City Hotel,0,17,2024,October,44,29,2024-10-29,1,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,149.0,1,3
HB-032940,Resort Hotel,0,0,2025,February,6,9,2025-02-09,0,1,1,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,E,0,No Deposit,,,0,Transient,0.0,0,0
HB-067128,City Hotel,1,140,2025,April,18,28,2025-04-28,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,119.0,,0,Transient-Party,130.0,0,0
HB-013253,Resort Hotel,1,126,2025,August,32,6,2025-08-06,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,242.0,,0,Transient,239.0,0,1
HB-015515,Resort Hotel,0,44,2023,July,29,20,2023-07-20,1,3,2,0.0,0,HB,CN,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,115.85,0,0
HB-080172,City Hotel,0,91,2024,September,37,14,2024-09-14,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,2,A,D,1,No Deposit,,40.0,0,Transient,65.0,0,0
HB-105134,City Hotel,0,25,2025,January,5,27,2025-01-27,1,2,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,58.16,0,1
HB-023394,Resort Hotel,0,106,2024,April,17,24,2024-04-24,1,0,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,52.2,0,2
HB-051694,City Hotel,1,158,2024,May,21,24,2024-05-24,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,31,Transient,130.0,0,0
HB-066950,City Hotel,1,110,2025,April,17,26,2025-04-26,1,4,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,158.95,0,0
HB-021457,Resort Hotel,0,17,2024,February,9,26,2024-02-26,1,2,2,0.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,196.0,,0,Transient-Party,56.0,0,0
HB-075829,City Hotel,1,337,2023,September,38,19,2023-09-19,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-078643,City Hotel,1,8,2023,October,42,21,2023-10-21,0,2,1,0.0,0,BB,PRT,Direct,Direct,1,1,0,D,D,0,No Deposit,14.0,,0,Transient,126.0,0,1
HB-013072,Resort Hotel,1,51,2025,July,31,30,2025-07-30,2,2,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,206.9,0,0
HB-053816,City Hotel,1,132,2024,June,26,30,2024-06-30,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,96.3,0,0
HB-077463,City Hotel,0,5,2023,September,38,19,2023-09-19,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,9.0,,0,Contract,133.0,0,1
HB-113835,City Hotel,0,90,2025,June,24,11,2025-06-11,2,0,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,F,1,No Deposit,9.0,,0,Transient,189.0,0,0
HB-018051,Resort Hotel,0,159,2023,October,43,25,2023-10-25,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Contract,43.93,0,1
HB-073354,City Hotel,1,248,2025,August,34,19,2025-08-19,1,1,2,0.0,0,SC,AGO,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.05,0,1
HB-100425,City Hotel,0,72,2024,October,43,26,2024-10-26,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,104.4,0,0
HB-042184,City Hotel,0,1,2023,September,35,2,2023-09-02,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-011070,Resort Hotel,1,144,2025,April,16,16,2025-04-16,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,54.0,0,0
HB-014088,Resort Hotel,0,165,2024,August,33,13,2024-08-13,2,6,2,0.0,0,BB,,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,181.0,,0,Transient,138.0,1,0
HB-053051,City Hotel,1,188,2024,June,24,15,2024-06-15,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,39,Transient,130.0,0,0
HB-055664,City Hotel,1,178,2024,August,33,18,2024-08-18,0,3,1,1.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,124.5,0,0
HB-030410,Resort Hotel,0,115,2024,November,46,17,2024-11-17,1,3,2,0.0,0,BB,IRL,Groups,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,34.0,0,0
HB-096682,City Hotel,0,23,2024,September,36,5,2024-09-05,1,0,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,93.94,0,1
HB-020428,Resort Hotel,0,3,2024,December,49,6,2024-12-06,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,9,A,D,0,No Deposit,,269.0,0,Transient,30.0,0,0
HB-006590,Resort Hotel,0,267,2024,June,25,19,2024-06-19,2,4,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,60.35,0,1
HB-000283,Resort Hotel,0,304,2023,July,28,11,2023-07-11,2,4,2,0.0,1,BB,PRT,Direct,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,90.67,0,1
HB-060863,City Hotel,1,184,2024,November,47,24,2024-11-24,0,3,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,69.9,0,0
HB-039703,Resort Hotel,0,0,2025,August,35,25,2025-08-25,0,1,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,175.0,0,0
HB-095936,City Hotel,0,210,2024,August,34,25,2024-08-25,0,1,3,1.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,180.9,1,2
HB-030122,Resort Hotel,0,29,2024,November,45,9,2024-11-09,2,4,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,58.98,1,1
HB-015561,Resort Hotel,0,57,2023,July,29,18,2023-07-18,2,6,2,0.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,196.0,,0,Transient-Party,135.0,0,1
HB-110315,City Hotel,0,73,2025,April,17,23,2025-04-23,2,1,2,0.0,0,BB,USA,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,108.0,0,0
HB-070192,City Hotel,1,253,2025,June,24,11,2025-06-11,2,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,80,Transient,140.0,0,0
HB-076239,City Hotel,1,200,2023,September,37,12,2023-09-12,2,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,86.0,0,0
HB-089707,City Hotel,0,212,2024,May,21,20,2024-05-20,2,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,78.0,0,1
HB-106339,City Hotel,0,17,2025,February,8,19,2025-02-19,2,3,3,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.66,0,0
HB-055753,City Hotel,1,4,2024,August,34,20,2024-08-20,0,1,2,0.0,0,BB,PRT,Online TA,Corporate,0,0,0,A,A,0,Non Refund,,47.0,0,Transient,121.6,0,0
HB-087503,City Hotel,0,125,2024,April,16,18,2024-04-18,1,2,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,71.0,0,1
HB-025075,Resort Hotel,0,98,2024,May,22,30,2024-05-30,4,10,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,98.76,0,2
HB-000737,Resort Hotel,0,30,2023,July,30,27,2023-07-27,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,134.0,0,1
HB-046706,City Hotel,1,92,2024,January,3,16,2024-01-16,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,90.0,0,1
HB-020253,Resort Hotel,0,1,2024,January,3,21,2024-01-21,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,127.0,,0,Transient,26.5,0,0
HB-028839,Resort Hotel,0,364,2024,October,41,12,2024-10-12,2,4,2,0.0,0,BB,BEL,Groups,TA/TO,0,0,0,A,C,3,No Deposit,,223.0,0,Transient-Party,66.0,0,2
HB-074337,City Hotel,1,269,2023,July,28,13,2023-07-13,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Contract,62.0,0,0
HB-002094,Resort Hotel,0,22,2023,October,39,1,2023-10-01,1,3,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,,0,Transient,65.0,0,1
HB-008927,Resort Hotel,1,386,2024,October,42,20,2024-10-20,1,3,2,0.0,0,BB,PRT,Groups,Corporate,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,49.0,0,0
HB-013968,Resort Hotel,0,0,2025,April,17,21,2025-04-21,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,70.0,0,0
HB-027537,Resort Hotel,0,1,2024,August,35,27,2024-08-27,2,4,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,169.0,0,1
HB-030316,Resort Hotel,0,52,2024,November,46,12,2024-11-12,2,5,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,29.0,0,0
HB-000657,Resort Hotel,0,25,2023,July,30,24,2023-07-24,2,5,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,250.0,,0,Transient,115.0,0,0
HB-108404,City Hotel,0,2,2025,March,13,25,2025-03-25,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.0,1,2
HB-091983,City Hotel,0,10,2024,June,26,26,2024-06-26,2,1,2,0.0,0,BB,LUX,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,124.33,0,1
HB-010533,Resort Hotel,1,96,2025,March,11,12,2025-03-12,4,7,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,8.0,0,0
HB-029577,Resort Hotel,0,17,2024,October,44,30,2024-10-30,1,0,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,346.0,0,Transient,66.0,0,0
HB-056823,City Hotel,1,317,2024,September,37,15,2024-09-15,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,120.0,0,0
HB-066776,City Hotel,1,50,2025,April,17,25,2025-04-25,0,4,1,0.0,0,BB,CYP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,0
HB-065273,City Hotel,1,160,2025,March,13,30,2025-03-30,1,3,0,2.0,0,BB,ROU,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient,90.46,0,2
HB-079140,City Hotel,0,12,2023,October,42,20,2023-10-20,0,2,1,0.0,0,BB,FIN,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,105.0,0,Transient-Party,130.0,0,0
HB-116060,City Hotel,0,451,2025,July,28,12,2025-07-12,0,3,2,0.0,0,BB,USA,Groups,TA/TO,0,0,0,A,E,0,No Deposit,229.0,,0,Transient-Party,112.67,0,1
HB-081913,City Hotel,1,181,2024,May,18,5,2024-05-05,2,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,26.0,,42,Transient,90.0,0,0
HB-039170,Resort Hotel,0,183,2025,August,32,9,2025-08-09,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,E,0,No Deposit,,251.0,0,Transient-Party,141.0,0,1
HB-106034,City Hotel,0,42,2025,February,7,16,2025-02-16,0,3,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,67.76,0,2
HB-006174,Resort Hotel,1,7,2024,May,22,27,2024-05-27,0,1,1,0.0,0,HB,PRT,Groups,Corporate,0,0,0,A,A,0,Non Refund,,20.0,0,Transient,58.0,0,0
HB-011076,Resort Hotel,1,92,2025,April,16,17,2025-04-17,1,0,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,60.0,0,0
HB-006291,Resort Hotel,1,215,2024,June,22,1,2024-06-01,0,3,2,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,96.0,,0,Transient,110.0,0,0
HB-051608,City Hotel,0,160,2024,May,21,22,2024-05-22,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.45,0,1
HB-110744,City Hotel,0,21,2025,April,18,28,2025-04-28,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,175.0,0,1
HB-094827,City Hotel,0,97,2024,August,31,4,2024-08-04,2,5,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,85.0,,0,Transient,82.45,0,0
HB-039555,Resort Hotel,0,16,2025,August,33,15,2025-08-15,1,5,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,169.48,0,1
HB-050472,City Hotel,0,121,2024,May,18,2,2024-05-02,1,0,2,0.0,0,SC,FIN,Online TA,TA/TO,0,0,0,A,A,6,No Deposit,9.0,,0,Transient,129.0,0,1
HB-098575,City Hotel,0,100,2024,September,39,28,2024-09-28,0,4,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,26.0,,0,Transient-Party,140.0,0,1
HB-063693,City Hotel,1,15,2025,February,8,17,2025-02-17,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,95.0,0,0
HB-024113,Resort Hotel,0,38,2024,May,18,4,2024-05-04,2,6,2,0.0,0,HB,CHE,Direct,Direct,0,0,0,G,G,1,No Deposit,250.0,,0,Transient,155.0,0,0
HB-102328,City Hotel,0,232,2024,November,47,24,2024-11-24,0,3,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,110.7,0,0
HB-070849,City Hotel,1,233,2025,June,26,23,2025-06-23,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,105.0,0,0
HB-112198,City Hotel,0,10,2025,May,21,19,2025-05-19,0,2,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,165.0,0,0
HB-101477,City Hotel,0,47,2024,November,45,10,2024-11-10,0,3,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,130.33,0,1
HB-039451,Resort Hotel,0,17,2025,August,33,17,2025-08-17,0,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,230.0,0,2
HB-019517,Resort Hotel,0,7,2023,December,51,24,2023-12-24,0,1,2,2.0,0,Undefined,PRT,Direct,Direct,0,0,0,C,C,1,No Deposit,250.0,,0,Transient,149.0,0,0
HB-058993,City Hotel,1,468,2024,October,42,20,2024-10-20,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-080024,City Hotel,0,44,2023,November,44,5,2023-11-05,2,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Transient,60.0,0,0
HB-010139,Resort Hotel,1,56,2025,February,7,16,2025-02-16,0,3,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,43.0,0,1
HB-085361,City Hotel,0,62,2024,March,11,11,2024-03-11,1,2,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,60.29,0,1
HB-023998,Resort Hotel,0,146,2024,May,19,6,2024-05-06,2,2,1,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient-Party,44.1,0,0
HB-116798,City Hotel,0,177,2025,July,30,22,2025-07-22,2,1,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,89.0,0,0
HB-021760,Resort Hotel,0,10,2024,May,18,3,2024-05-03,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,371.0,0,Transient,42.0,0,1
HB-074757,City Hotel,1,241,2023,October,42,19,2023-10-19,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,60.0,0,0
HB-091495,City Hotel,0,55,2024,June,25,19,2024-06-19,2,2,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,114.0,0,2
HB-005344,Resort Hotel,1,93,2024,April,17,25,2024-04-25,2,5,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,113.57,0,0
HB-056099,City Hotel,1,43,2024,August,35,29,2024-08-29,1,2,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,144.9,0,0
HB-018793,Resort Hotel,0,0,2024,November,46,12,2024-11-12,0,1,2,0.0,0,BB,PRT,Direct,Direct,1,1,2,A,D,0,No Deposit,,,0,Transient,70.0,0,0
HB-005477,Resort Hotel,1,76,2024,April,18,29,2024-04-29,2,6,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,88.0,0,1
HB-069107,City Hotel,1,161,2025,May,21,25,2025-05-25,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,102.04,0,1
HB-037361,Resort Hotel,0,210,2025,June,24,12,2025-06-12,1,2,2,0.0,0,HB,POL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,315.0,,0,Contract,83.9,0,3
HB-114674,City Hotel,0,57,2025,June,25,20,2025-06-20,0,5,2,0.0,0,BB,EST,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,156.0,0,1
HB-010724,Resort Hotel,1,118,2025,March,13,29,2025-03-29,0,1,2,0.0,0,HB,CHN,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient,78.0,0,0
HB-022594,Resort Hotel,0,0,2024,March,13,29,2024-03-29,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,43.0,0,0
HB-089232,City Hotel,0,63,2024,May,20,16,2024-05-16,1,2,1,0.0,0,BB,IND,Corporate,TA/TO,0,0,0,A,A,1,No Deposit,,218.0,0,Transient-Party,130.0,0,0
HB-026499,Resort Hotel,0,0,2024,July,31,31,2024-07-31,2,0,1,0.0,0,BB,IRL,Direct,Direct,0,0,0,F,F,1,No Deposit,,,0,Transient,221.5,0,0
HB-067658,City Hotel,1,15,2025,May,19,5,2025-05-05,2,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,150.0,0,1
HB-104190,City Hotel,0,162,2025,January,1,4,2025-01-04,0,4,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,3
HB-044326,City Hotel,1,89,2023,October,40,3,2023-10-03,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-059739,City Hotel,1,166,2024,November,44,1,2024-11-01,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,Non Refund,236.0,,0,Transient,130.0,0,0
HB-078222,City Hotel,0,12,2024,October,41,9,2024-10-09,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,B,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-009047,Resort Hotel,1,8,2024,October,43,25,2024-10-25,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,40.0,0,0
HB-088087,City Hotel,0,142,2024,April,18,29,2024-04-29,0,2,2,0.0,0,BB,ITA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient,65.0,0,1
HB-039864,Resort Hotel,0,172,2025,August,34,24,2025-08-24,2,5,2,0.0,0,BB,ITA,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,205.0,0,2
HB-058324,City Hotel,1,129,2024,October,41,10,2024-10-10,1,5,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,132.3,0,0
HB-030572,Resort Hotel,0,45,2024,November,48,25,2024-11-25,0,2,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,67.8,0,1
HB-070958,City Hotel,1,213,2025,June,26,26,2025-06-26,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,323.0,,0,Transient,115.0,0,0
HB-117280,City Hotel,0,13,2025,August,31,1,2025-08-01,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,87.2,0,1
HB-063480,City Hotel,1,67,2025,February,7,12,2025-02-12,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,80.0,0,0
HB-021419,Resort Hotel,0,5,2024,February,9,27,2024-02-27,1,1,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,1,No Deposit,240.0,,0,Transient,96.0,1,0
HB-033108,Resort Hotel,0,0,2025,February,7,14,2025-02-14,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,F,0,No Deposit,,,0,Transient,0.0,0,1
HB-107928,City Hotel,0,56,2025,March,11,16,2025-03-16,1,3,1,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,74.8,0,3
HB-092898,City Hotel,0,97,2024,July,28,12,2024-07-12,0,2,2,1.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,9.0,,0,Transient,121.5,0,1
HB-077223,City Hotel,0,327,2023,September,36,9,2023-09-09,2,4,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,88.0,0,0
HB-080021,City Hotel,0,8,2023,November,45,6,2023-11-06,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,104.5,0,1
HB-024775,Resort Hotel,0,36,2024,May,22,30,2024-05-30,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,G,G,1,No Deposit,240.0,,0,Transient,145.0,0,0
HB-088879,City Hotel,0,66,2024,May,19,9,2024-05-09,1,3,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,152.15,0,1
HB-025244,Resort Hotel,0,222,2024,June,24,13,2024-06-13,2,5,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,E,F,3,No Deposit,250.0,,0,Transient,95.5,0,0
HB-111349,City Hotel,0,98,2025,May,19,7,2025-05-07,2,1,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,135.0,0,1
HB-027546,Resort Hotel,0,0,2024,August,35,31,2024-08-31,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,144.0,0,0
HB-063618,City Hotel,1,587,2025,February,7,16,2025-02-16,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-042431,City Hotel,1,61,2023,September,36,5,2023-09-05,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-003272,Resort Hotel,0,20,2023,December,48,1,2023-12-01,0,0,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,I,0,No Deposit,240.0,,0,Transient,0.0,0,0
HB-090957,City Hotel,0,26,2024,June,24,11,2024-06-11,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,95.0,0,0
HB-103317,City Hotel,0,10,2024,December,51,16,2024-12-16,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,89.0,,0,Transient,79.2,0,0
HB-018378,Resort Hotel,0,1,2023,November,46,17,2023-11-17,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,36.0,0,1
HB-002420,Resort Hotel,1,334,2023,October,41,12,2023-10-12,2,5,5,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Group,0.0,0,0
HB-109408,City Hotel,0,248,2025,April,15,9,2025-04-09,2,0,2,0.0,0,BB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,58.0,,0,Transient-Party,80.0,0,1
HB-034552,Resort Hotel,0,225,2025,March,11,15,2025-03-15,4,10,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,E,F,0,No Deposit,75.0,,0,Transient,44.5,0,1
HB-101760,City Hotel,0,13,2024,November,46,16,2024-11-16,0,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,73.15,0,1
HB-010167,Resort Hotel,1,320,2025,February,8,17,2025-02-17,2,4,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,93.0,0,0
HB-105627,City Hotel,0,12,2025,February,6,9,2025-02-09,1,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,57.6,0,1
HB-118363,City Hotel,0,113,2025,August,33,17,2025-08-17,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,155.0,0,1
HB-116442,City Hotel,0,136,2025,July,29,14,2025-07-14,2,4,1,0.0,0,HB,DNK,Direct,Direct,0,0,0,D,D,4,No Deposit,14.0,,0,Transient,173.0,0,0
HB-105878,City Hotel,0,23,2025,February,7,10,2025-02-10,2,5,2,0.0,0,SC,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,16.0,,0,Transient,59.5,0,0
HB-019400,Resort Hotel,0,11,2023,December,50,13,2023-12-13,2,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,38.4,0,1
HB-038885,Resort Hotel,0,335,2025,July,30,24,2025-07-24,3,6,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,134.85,0,1
HB-108781,City Hotel,0,83,2025,March,13,30,2025-03-30,0,3,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,103.8,0,1
HB-007444,Resort Hotel,1,217,2024,August,32,9,2024-08-09,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,126.0,0,0
HB-063841,City Hotel,1,594,2025,February,8,23,2025-02-23,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-076281,City Hotel,1,147,2023,July,29,21,2023-07-21,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient,75.0,0,0
HB-017176,Resort Hotel,0,0,2023,September,39,28,2023-09-28,1,0,2,0.0,0,BB,CHE,Direct,Direct,0,0,0,A,E,1,No Deposit,,,0,Transient,94.0,1,0
HB-023275,Resort Hotel,0,101,2024,April,16,16,2024-04-16,2,2,3,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,C,1,No Deposit,26.0,,0,Transient,17.6,1,1
HB-096018,City Hotel,0,143,2024,August,34,25,2024-08-25,0,3,2,0.0,0,BB,CZE,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,36.0,,0,Transient-Party,100.0,0,0
HB-036538,Resort Hotel,0,95,2025,May,20,14,2025-05-14,4,6,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,2,No Deposit,69.0,,0,Transient,79.85,0,0
HB-065333,City Hotel,1,187,2025,March,14,31,2025-03-31,2,2,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,72.42,0,1
HB-034451,Resort Hotel,0,9,2025,March,13,25,2025-03-25,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,82.0,1,1
HB-109805,City Hotel,0,34,2025,April,16,15,2025-04-15,1,1,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,1
HB-002211,Resort Hotel,1,74,2023,October,40,5,2023-10-05,3,6,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,86.0,0,2
HB-066801,City Hotel,1,96,2025,April,17,26,2025-04-26,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,130.0,0,0
HB-039945,Resort Hotel,0,10,2025,August,35,26,2025-08-26,2,5,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,241.0,,0,Transient,176.86,1,1
HB-085187,City Hotel,0,10,2024,March,10,7,2024-03-07,1,3,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,E,E,2,No Deposit,,51.0,0,Transient-Party,107.0,0,0
HB-013726,Resort Hotel,1,56,2025,August,35,28,2025-08-28,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,5.0,,0,Transient,152.0,0,0
HB-008279,Resort Hotel,1,385,2024,September,38,21,2024-09-21,0,4,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,66.0,0,0
HB-059827,City Hotel,1,482,2024,November,44,3,2024-11-03,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-005124,Resort Hotel,1,185,2024,April,16,18,2024-04-18,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,86.0,0,0
HB-000062,Resort Hotel,0,5,2023,July,26,2,2023-07-02,0,2,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,135.0,1,2
HB-021138,Resort Hotel,0,1,2024,February,7,18,2024-02-18,0,1,2,1.0,0,BB,ARG,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,64.0,1,0
HB-009147,Resort Hotel,1,112,2024,October,44,29,2024-10-29,2,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,65.27,0,1
HB-021657,Resort Hotel,0,50,2024,March,10,4,2024-03-04,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,1,No Deposit,,,0,Transient,56.0,0,1
HB-040087,City Hotel,1,106,2023,July,27,4,2023-07-04,1,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,68.0,0,0
HB-115748,City Hotel,0,122,2025,July,28,7,2025-07-07,1,2,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,0
HB-109742,City Hotel,0,82,2025,April,15,11,2025-04-11,0,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,2
HB-017590,Resort Hotel,0,4,2023,October,41,13,2023-10-13,0,2,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,76.0,0,2
HB-090193,City Hotel,0,16,2024,May,22,30,2024-05-30,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,100.73,0,1
HB-028495,Resort Hotel,0,19,2024,October,40,1,2024-10-01,2,2,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,99.0,0,1
HB-021228,Resort Hotel,0,0,2024,February,7,16,2024-02-16,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,45.5,0,0
HB-016960,Resort Hotel,0,258,2023,September,37,17,2023-09-17,0,2,2,0.0,0,HB,FRA,Groups,TA/TO,0,0,0,A,A,1,No Deposit,245.0,,0,Transient-Party,78.3,0,1
HB-042594,City Hotel,0,3,2023,September,36,7,2023-09-07,1,4,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,127.8,0,0
HB-071831,City Hotel,1,156,2025,July,28,13,2025-07-13,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,116.1,0,0
HB-004708,Resort Hotel,0,147,2024,March,13,28,2024-03-28,2,5,2,0.0,0,HB,LUX,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,,,0,Transient-Party,73.0,0,0
HB-081194,City Hotel,0,14,2023,December,49,4,2023-12-04,0,2,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,100.0,0,0
HB-009171,Resort Hotel,1,96,2024,October,44,31,2024-10-31,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,46.8,0,0
HB-019419,Resort Hotel,0,33,2023,December,50,12,2023-12-12,2,5,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,6.0,,0,Transient,49.4,0,0
HB-067065,City Hotel,1,206,2025,April,18,28,2025-04-28,0,2,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.5,0,3
HB-106555,City Hotel,0,29,2025,February,8,22,2025-02-22,1,4,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,9.0,,0,Transient,124.44,0,3
HB-109923,City Hotel,0,125,2025,April,16,16,2025-04-16,2,1,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,175.5,1,3
HB-081314,City Hotel,0,24,2023,December,49,5,2023-12-05,2,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,143.0,0,Transient-Party,47.0,0,0
HB-044247,City Hotel,0,164,2023,October,40,2,2023-10-02,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,19.0,,0,Transient-Party,100.0,0,0
HB-093790,City Hotel,0,169,2024,July,30,24,2024-07-24,2,1,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,94.5,0,1
HB-058820,City Hotel,1,36,2024,October,42,16,2024-10-16,1,0,1,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,1
HB-071786,City Hotel,1,229,2025,July,28,12,2025-07-12,1,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-065831,City Hotel,1,248,2025,April,15,9,2025-04-09,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,58.0,,0,Transient-Party,80.0,0,0
HB-049727,City Hotel,1,64,2024,April,16,18,2024-04-18,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,110.08,0,0
HB-029313,Resort Hotel,0,13,2024,October,43,24,2024-10-24,1,1,2,0.0,0,BB,SWE,Groups,Corporate,0,0,0,D,D,1,No Deposit,,,0,Transient-Party,67.0,1,0
HB-041373,City Hotel,0,40,2023,August,33,15,2023-08-15,2,2,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-107848,City Hotel,0,52,2025,March,12,17,2025-03-17,0,2,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,207.0,1,2
HB-118115,City Hotel,0,34,2025,August,33,14,2025-08-14,1,0,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,219.0,1,2
HB-047287,City Hotel,1,40,2024,February,7,14,2024-02-14,2,5,2,0.0,0,SC,CPV,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,77.23,0,0
HB-014547,Resort Hotel,0,0,2024,April,15,11,2024-04-11,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,3,A,A,0,No Deposit,,86.0,0,Transient,65.4,1,0
HB-107683,City Hotel,0,70,2025,March,11,13,2025-03-13,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,100.3,0,1
HB-090949,City Hotel,0,147,2024,June,24,11,2024-06-11,2,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient-Party,102.3,0,0
HB-072808,City Hotel,1,169,2025,August,32,7,2025-08-07,1,1,2,1.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,148.5,0,0
HB-091860,City Hotel,0,192,2024,June,26,24,2024-06-24,0,2,1,0.0,0,BB,SRB,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,34.0,,0,Transient-Party,95.0,0,0
HB-032946,Resort Hotel,0,7,2025,February,6,9,2025-02-09,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient-Party,43.0,0,2
HB-034099,Resort Hotel,0,4,2025,March,11,10,2025-03-10,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,63.0,0,1
HB-011008,Resort Hotel,1,87,2025,April,16,14,2025-04-14,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,76.67,0,1
HB-103584,City Hotel,0,105,2024,December,52,26,2024-12-26,1,1,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,83.05,0,0
HB-038452,Resort Hotel,0,0,2025,July,29,17,2025-07-17,1,0,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,154.0,0,0
HB-119284,City Hotel,0,115,2025,August,35,30,2025-08-30,0,3,2,0.0,0,SC,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,100.0,0,2
HB-026449,Resort Hotel,0,210,2024,July,30,27,2024-07-27,1,4,2,1.0,0,BB,SWE,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,186.1,0,1
HB-029820,Resort Hotel,0,29,2024,November,45,4,2024-11-04,0,2,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient-Party,55.8,0,2
HB-052396,City Hotel,1,163,2024,June,23,5,2024-06-05,2,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,171.0,,0,Transient,100.0,0,0
HB-016216,Resort Hotel,0,144,2023,August,33,15,2023-08-15,2,5,2,0.0,0,BB,SWE,Offline TA/TO,TA/TO,0,0,0,E,F,1,No Deposit,156.0,,0,Contract,119.25,1,2
HB-056035,City Hotel,1,226,2024,August,35,27,2024-08-27,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,96.0,0,0
HB-038224,Resort Hotel,0,327,2025,July,27,5,2025-07-05,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,106.24,0,2
HB-071050,City Hotel,1,141,2025,June,26,27,2025-06-27,2,5,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,130.0,0,0
HB-092152,City Hotel,0,38,2024,June,26,27,2024-06-27,1,3,2,0.0,0,SC,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,63.75,0,0
HB-071046,City Hotel,1,141,2025,June,26,27,2025-06-27,2,5,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,130.0,0,0
HB-054494,City Hotel,1,78,2024,July,29,18,2024-07-18,1,1,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,105.3,0,0
HB-118909,City Hotel,0,30,2025,August,35,25,2025-08-25,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,145.0,0,1
HB-034431,Resort Hotel,0,47,2025,March,12,20,2025-03-20,1,4,1,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,91.0,,0,Transient-Party,48.5,0,0
HB-031554,Resort Hotel,0,0,2024,December,1,31,2024-12-31,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,101.0,0,0
HB-034591,Resort Hotel,0,152,2025,March,12,23,2025-03-23,2,5,1,0.0,0,Undefined,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,464.0,,0,Transient,47.0,0,0
HB-058833,City Hotel,1,283,2024,October,42,16,2024-10-16,2,0,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,96.0,0,0
HB-117404,City Hotel,0,144,2025,July,31,30,2025-07-30,2,2,2,0.0,0,HB,RUS,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,173.7,0,2
HB-085092,City Hotel,0,40,2024,March,10,5,2024-03-05,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,83.9,0,1
HB-008146,Resort Hotel,0,327,2024,September,37,14,2024-09-14,0,4,2,0.0,0,BB,IRL,Groups,TA/TO,0,0,0,A,D,0,No Deposit,201.0,,0,Transient,59.4,0,0
HB-081824,City Hotel,1,178,2024,April,17,28,2024-04-28,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,46,Transient,110.0,0,0
HB-012656,Resort Hotel,1,289,2025,July,28,10,2025-07-10,1,4,2,0.0,0,BB,EST,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,138.38,0,0
HB-107642,City Hotel,0,27,2025,March,11,14,2025-03-14,0,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,113.0,0,3
HB-033515,Resort Hotel,0,6,2025,February,9,24,2025-02-24,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,E,0,No Deposit,,,0,Transient,61.2,0,1
HB-049222,City Hotel,1,18,2024,April,15,8,2024-04-08,0,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.0,0,0
HB-075451,City Hotel,1,334,2023,September,37,16,2023-09-16,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-105326,City Hotel,0,15,2025,February,6,3,2025-02-03,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,D,2,No Deposit,,396.0,0,Transient-Party,90.0,0,0
HB-067552,City Hotel,1,143,2025,May,18,4,2025-05-04,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,151.0,,0,Transient,100.0,0,0
HB-115599,City Hotel,0,188,2025,July,28,7,2025-07-07,0,1,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,89.1,0,0
HB-086271,City Hotel,0,1,2025,February,6,8,2025-02-08,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,9,A,A,0,No Deposit,,219.0,0,Transient,80.0,0,1
HB-051200,City Hotel,1,17,2024,May,20,15,2024-05-15,4,8,1,0.0,0,BB,PRT,Aviation,Corporate,0,0,0,D,A,1,No Deposit,,153.0,0,Transient,110.0,0,0
HB-107623,City Hotel,0,7,2025,March,11,15,2025-03-15,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,65.0,0,0
HB-024760,Resort Hotel,0,15,2025,June,25,18,2025-06-18,2,0,2,0.0,0,BB,PRT,Online TA,TA/TO,1,0,1,A,A,0,No Deposit,240.0,,0,Transient,140.0,0,1
HB-055772,City Hotel,1,152,2024,August,34,20,2024-08-20,2,5,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,91.93,0,0
HB-083980,City Hotel,0,11,2024,February,7,14,2024-02-14,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,87.0,0,0
HB-063266,City Hotel,1,49,2025,February,6,4,2025-02-04,1,1,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,1
HB-088797,City Hotel,0,65,2024,May,19,9,2024-05-09,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,119.85,0,1
HB-079435,City Hotel,1,137,2024,January,4,27,2024-01-27,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,29.0,,45,Transient,70.0,0,0
HB-108001,City Hotel,1,13,2025,May,22,29,2025-05-29,1,2,1,0.0,0,BB,SWE,Direct,Direct,1,1,1,A,A,0,No Deposit,,,0,Transient,95.0,0,0
HB-115225,City Hotel,0,126,2025,June,27,30,2025-06-30,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,128.4,1,0
HB-003275,Resort Hotel,0,118,2023,December,48,1,2023-12-01,2,5,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,29.16,0,1
HB-064785,City Hotel,1,246,2025,March,11,16,2025-03-16,0,3,3,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,122.4,0,0
HB-101811,City Hotel,0,21,2024,November,46,13,2024-11-13,2,4,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.4,0,1
HB-036520,Resort Hotel,0,195,2025,May,20,16,2025-05-16,2,5,2,0.0,0,HB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,115.0,0,1
HB-108894,City Hotel,0,95,2025,March,14,31,2025-03-31,1,2,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,110.4,0,1
HB-001786,Resort Hotel,0,107,2023,September,37,14,2023-09-14,1,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,76.67,0,1
HB-026556,Resort Hotel,0,136,2024,July,31,30,2024-07-30,2,3,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient,187.4,1,2
HB-079343,City Hotel,0,10,2023,October,42,22,2023-10-22,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,130.75,0,1
HB-005386,Resort Hotel,0,200,2024,April,17,27,2024-04-27,1,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,79.2,0,2
HB-043673,City Hotel,1,77,2023,September,38,22,2023-09-22,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,116.94,0,0
HB-113890,City Hotel,0,109,2025,June,24,12,2025-06-12,1,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,153.0,0,0
HB-064083,City Hotel,1,20,2025,March,9,1,2025-03-01,0,4,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,91.8,0,0
HB-090665,City Hotel,0,0,2024,June,23,8,2024-06-08,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,152.0,,0,Transient,73.07,0,0
HB-062843,City Hotel,1,59,2025,January,4,23,2025-01-23,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,326.0,,0,Transient,80.0,0,0
HB-110856,City Hotel,0,116,2025,April,18,28,2025-04-28,2,2,3,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,E,E,2,No Deposit,9.0,,0,Transient,155.25,0,2
HB-112311,City Hotel,0,99,2025,May,21,20,2025-05-20,2,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,144.0,0,0
HB-074329,City Hotel,1,262,2023,July,27,6,2023-07-06,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Contract,62.0,0,0
HB-029697,Resort Hotel,0,7,2024,November,44,3,2024-11-03,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,94.0,,0,Transient,27.0,0,0
HB-004054,Resort Hotel,1,112,2024,February,7,12,2024-02-12,0,2,2,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,68.0,0,0
HB-064710,City Hotel,1,92,2025,March,11,15,2025-03-15,0,3,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,85.0,0,0
HB-054618,City Hotel,1,379,2024,July,29,21,2024-07-21,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-000174,Resort Hotel,1,48,2023,July,27,6,2023-07-06,1,3,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,167.0,0,0
HB-049914,City Hotel,0,265,2024,April,16,20,2024-04-20,0,4,2,0.0,0,BB,AUT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,176,Transient-Party,99.0,0,0
HB-073789,City Hotel,1,279,2023,July,29,23,2023-07-23,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-061551,City Hotel,1,46,2024,December,51,16,2024-12-16,1,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,1
HB-101999,City Hotel,0,22,2024,November,46,17,2024-11-17,1,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,96.9,0,2
HB-111700,City Hotel,0,12,2025,May,20,13,2025-05-13,0,1,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,4,No Deposit,9.0,,0,Transient,180.0,0,3
HB-018114,Resort Hotel,0,21,2025,April,16,17,2025-04-17,1,1,2,0.0,0,HB,PRT,Online TA,TA/TO,1,0,1,A,A,0,No Deposit,240.0,,0,Transient,117.0,0,1
HB-077764,City Hotel,1,0,2023,September,39,26,2023-09-26,0,1,3,0.0,0,BB,PRT,Direct,Direct,1,0,0,D,D,0,No Deposit,,,0,Transient,200.0,0,0
HB-116643,City Hotel,0,55,2025,July,30,21,2025-07-21,0,2,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,148.5,1,1
HB-017808,Resort Hotel,0,2,2023,October,42,21,2023-10-21,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,,0,Transient,48.0,1,0
HB-011464,Resort Hotel,1,302,2025,May,19,9,2025-05-09,0,4,1,0.0,0,HB,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,57.5,0,0
HB-037288,Resort Hotel,0,168,2025,June,23,5,2025-06-05,3,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,141.5,0,2
HB-056521,City Hotel,1,25,2024,September,36,8,2024-09-08,0,2,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,139.0,0,0
HB-106324,City Hotel,0,7,2025,February,8,23,2025-02-23,0,1,1,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,85.0,,0,Transient,75.0,0,1
HB-089551,City Hotel,0,86,2024,May,21,20,2024-05-20,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,65.0,0,1
HB-001979,Resort Hotel,0,9,2023,September,39,25,2023-09-25,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,240.0,,0,Transient,96.5,0,1
HB-012394,Resort Hotel,1,296,2025,June,26,26,2025-06-26,2,5,3,0.0,0,HB,ESP,Direct,Direct,0,0,0,H,H,0,No Deposit,250.0,,0,Transient,187.53,0,0
HB-086880,City Hotel,0,134,2024,April,15,9,2024-04-09,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,90.0,0,1
HB-089805,City Hotel,0,91,2024,May,21,22,2024-05-22,2,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.65,0,1
HB-062361,City Hotel,1,47,2025,January,2,11,2025-01-11,0,4,1,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,0
HB-100367,City Hotel,0,13,2024,October,43,26,2024-10-26,0,1,2,1.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,118.0,,0,Transient,109.5,0,1
HB-097870,City Hotel,0,20,2024,September,38,19,2024-09-19,1,2,1,0.0,0,BB,POL,Corporate,Corporate,0,0,0,A,B,1,No Deposit,,293.0,0,Transient,119.0,0,0
HB-033607,Resort Hotel,0,25,2025,February,9,24,2025-02-24,1,2,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,65.83,0,1
HB-016058,Resort Hotel,0,212,2023,August,31,1,2023-08-01,4,8,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient-Party,164.0,0,1
HB-039111,Resort Hotel,0,11,2025,August,32,5,2025-08-05,2,1,3,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,343.0,1,1
HB-079183,City Hotel,0,5,2023,October,42,19,2023-10-19,1,3,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,9.0,,0,Contract,123.0,1,1
HB-010627,Resort Hotel,1,350,2025,March,13,24,2025-03-24,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,11.0,,0,Transient,30.0,0,0
HB-025738,Resort Hotel,0,143,2024,July,27,2,2024-07-02,2,5,2,0.0,0,BB,AUT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,177.0,,0,Transient,75.6,0,0
HB-021532,Resort Hotel,0,6,2024,March,9,2,2024-03-02,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,240.0,,0,Transient,43.0,0,0
HB-029070,Resort Hotel,0,0,2024,October,42,20,2024-10-20,0,1,2,1.0,0,BB,PRT,Direct,Direct,1,0,0,F,F,0,No Deposit,,,0,Transient,107.5,1,1
HB-050587,City Hotel,1,302,2024,May,18,5,2024-05-05,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,59.0,0,0
HB-061486,City Hotel,1,34,2024,December,50,14,2024-12-14,0,3,3,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,138.6,0,1
HB-090037,City Hotel,0,98,2024,May,22,30,2024-05-30,1,1,2,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,85.0,,0,Transient,89.75,1,0
HB-095876,City Hotel,0,1,2024,August,34,24,2024-08-24,0,1,2,0.0,1,SC,BRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,119.0,0,2
HB-004762,Resort Hotel,0,169,2024,March,13,31,2024-03-31,1,3,2,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,A,0,Refundable,,223.0,0,Transient-Party,66.0,0,0
HB-035958,Resort Hotel,0,194,2025,April,16,15,2025-04-15,6,15,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,47.5,0,2
HB-115839,City Hotel,0,18,2025,July,28,8,2025-07-08,2,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,102.6,0,2
HB-050121,City Hotel,1,8,2024,April,17,24,2024-04-24,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,101.0,0,0
HB-074488,City Hotel,1,318,2023,August,35,31,2023-08-31,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-071336,City Hotel,1,178,2025,July,27,2,2025-07-02,2,5,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,179.1,0,0
HB-110177,City Hotel,0,133,2025,April,16,19,2025-04-19,0,4,2,0.0,0,BB,ISL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,390.0,,0,Transient-Party,124.0,0,0
HB-060752,City Hotel,1,10,2024,November,47,20,2024-11-20,1,0,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,101.0,0,1
HB-055383,City Hotel,1,221,2024,August,33,12,2024-08-12,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,147,Transient-Party,80.0,0,0
HB-010006,Resort Hotel,1,83,2025,February,6,4,2025-02-04,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,37.0,0,0
HB-108138,City Hotel,0,1,2025,March,12,22,2025-03-22,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,429.0,0,Transient,80.0,1,0
HB-072451,City Hotel,1,296,2025,July,31,28,2025-07-28,2,3,2,1.0,0,BB,DOM,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,183.08,0,0
HB-002989,Resort Hotel,1,30,2023,November,45,9,2023-11-09,2,5,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,4,No Deposit,326.0,281.0,0,Transient-Party,48.0,0,0
HB-022262,Resort Hotel,0,37,2024,March,12,18,2024-03-18,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,58.0,0,2
HB-119272,City Hotel,0,213,2025,August,35,28,2025-08-28,1,3,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,19.0,,0,Transient-Party,104.0,0,0
HB-108218,City Hotel,0,67,2025,March,12,19,2025-03-19,2,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,B,0,No Deposit,22.0,,0,Transient,68.0,0,0
HB-087678,City Hotel,0,2,2024,April,16,21,2024-04-21,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,20.0,,0,Transient,95.0,0,0
HB-035207,Resort Hotel,0,31,2025,April,15,13,2025-04-13,0,3,1,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient-Party,127.0,0,2
HB-022606,Resort Hotel,0,55,2024,March,13,28,2024-03-28,1,1,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,D,0,No Deposit,250.0,,0,Transient,53.2,0,0
HB-023121,Resort Hotel,0,4,2024,April,16,15,2024-04-15,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,171.0,,0,Transient,46.0,0,0
HB-092091,City Hotel,0,154,2024,June,26,27,2024-06-27,1,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.95,0,1
HB-074829,City Hotel,1,335,2023,September,37,17,2023-09-17,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,5.0,,0,Transient,85.0,0,0
HB-104883,City Hotel,0,2,2025,January,4,21,2025-01-21,2,1,1,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,48.05,0,1
HB-084466,City Hotel,0,50,2024,February,8,24,2024-02-24,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,74.0,0,0
HB-048601,City Hotel,1,161,2024,March,13,25,2024-03-25,1,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,101,Transient,130.0,0,0
HB-026866,Resort Hotel,0,138,2024,August,32,7,2024-08-07,2,4,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,244.67,1,0
HB-112212,City Hotel,0,115,2025,May,20,18,2025-05-18,0,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,2
HB-115282,City Hotel,0,132,2025,July,27,1,2025-07-01,2,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,2
HB-102918,City Hotel,0,1,2024,December,49,5,2024-12-05,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,65.76,0,1
HB-062799,City Hotel,1,59,2025,January,4,23,2025-01-23,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,326.0,,0,Transient,80.0,0,0
HB-115013,City Hotel,0,102,2025,June,26,28,2025-06-28,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,117.0,0,2
HB-116171,City Hotel,0,25,2025,July,29,14,2025-07-14,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.0,0,1
HB-100095,City Hotel,0,12,2024,October,43,21,2024-10-21,0,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,1
HB-100454,City Hotel,0,32,2024,October,43,24,2024-10-24,1,3,2,0.0,0,BB,CHE,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-102504,City Hotel,0,35,2024,November,48,28,2024-11-28,1,1,2,0.0,0,BB,ITA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,75.0,0,0
HB-116747,City Hotel,0,129,2025,July,30,22,2025-07-22,1,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.5,0,0
HB-057447,City Hotel,1,80,2024,September,39,26,2024-09-26,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,75.0,0,0
HB-063872,City Hotel,1,184,2025,February,8,23,2025-02-23,0,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.6,0,0
HB-101984,City Hotel,0,65,2024,November,47,20,2024-11-20,1,0,1,0.0,0,SC,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,0
HB-039039,Resort Hotel,0,129,2025,August,31,2,2025-08-02,0,4,2,1.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,262.0,0,2
HB-089195,City Hotel,0,64,2024,May,20,17,2024-05-17,0,2,1,0.0,0,BB,TUR,Corporate,TA/TO,0,0,0,A,A,0,No Deposit,,218.0,0,Transient-Party,130.0,0,1
HB-075234,City Hotel,1,297,2023,August,32,10,2023-08-10,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-015351,Resort Hotel,0,152,2023,July,26,2,2023-07-02,2,5,1,0.0,0,HB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Contract,60.35,0,2
HB-070004,City Hotel,1,169,2025,June,23,8,2025-06-08,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,170.0,0,0
HB-076315,City Hotel,0,264,2023,July,27,8,2023-07-08,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,0.0,0,0
HB-042744,City Hotel,0,86,2023,September,36,9,2023-09-09,0,3,1,0.0,0,BB,FRA,Corporate,Corporate,0,0,0,A,A,1,No Deposit,,68.0,0,Transient-Party,90.0,0,0
HB-044877,City Hotel,0,36,2023,October,41,13,2023-10-13,0,3,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,26.0,,0,Transient-Party,112.0,0,0
HB-069643,City Hotel,1,348,2025,June,23,3,2025-06-03,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient,90.0,0,0
HB-093600,City Hotel,0,83,2024,July,30,23,2024-07-23,0,1,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,137.7,0,2
HB-036653,Resort Hotel,0,352,2025,May,21,25,2025-05-25,2,5,2,0.0,1,HB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,6.0,,0,Group,121.0,0,1
HB-086609,City Hotel,0,71,2024,April,14,3,2024-04-03,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,87.13,0,1
HB-015278,Resort Hotel,0,19,2024,July,29,19,2024-07-19,0,2,1,0.0,0,BB,PRT,Direct,Direct,1,0,5,A,A,0,No Deposit,,338.0,0,Transient,101.0,1,0
HB-094999,City Hotel,0,170,2024,August,32,6,2024-08-06,2,5,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,148.0,1,2
HB-047812,City Hotel,1,62,2024,March,10,4,2024-03-04,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.3,0,0
HB-057592,City Hotel,1,100,2024,September,39,28,2024-09-28,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,26.0,,0,Transient-Party,100.0,0,0
HB-017127,Resort Hotel,0,167,2023,September,37,17,2023-09-17,2,8,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Contract,62.48,0,2
HB-050802,City Hotel,1,31,2024,May,19,8,2024-05-08,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,97.71,0,0
HB-074202,City Hotel,1,363,2023,October,41,15,2023-10-15,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-097823,City Hotel,0,4,2024,September,38,19,2024-09-19,1,1,1,0.0,0,BB,NLD,Aviation,Corporate,0,0,0,A,B,2,No Deposit,,153.0,0,Transient,95.0,0,0
HB-099235,City Hotel,0,32,2024,October,41,10,2024-10-10,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,B,2,No Deposit,,174.0,0,Transient,95.0,0,0
HB-019323,Resort Hotel,0,5,2023,December,49,10,2023-12-10,1,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,156.0,,0,Transient,42.75,0,0
HB-053241,City Hotel,1,350,2024,June,25,17,2024-06-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,140.0,0,0
HB-093613,City Hotel,0,126,2024,July,30,23,2024-07-23,0,1,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,9.0,,0,Transient,146.7,1,2
HB-117122,City Hotel,0,34,2025,July,31,28,2025-07-28,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,1
HB-047139,City Hotel,0,45,2024,February,6,9,2024-02-09,0,4,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,65.75,0,1
HB-080820,City Hotel,1,26,2023,November,47,26,2023-11-26,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,1,0,A,A,0,No Deposit,14.0,,0,Group,85.0,0,0
HB-045390,City Hotel,0,72,2023,October,43,28,2023-10-28,0,3,2,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,58,Transient-Party,85.67,0,1
HB-007709,Resort Hotel,1,6,2024,August,34,22,2024-08-22,1,0,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,199.0,0,0
HB-091634,City Hotel,0,19,2024,June,25,22,2024-06-22,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,215.0,,0,Transient-Party,90.0,0,0
HB-049990,City Hotel,1,168,2024,April,17,22,2024-04-22,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,26.0,,77,Transient,85.0,0,0
HB-081355,City Hotel,0,1,2023,December,49,5,2023-12-05,2,2,2,0.0,1,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,72.0,0,1
HB-079138,City Hotel,0,32,2023,October,42,19,2023-10-19,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,96.3,0,1
HB-012484,Resort Hotel,1,334,2025,July,27,1,2025-07-01,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient-Party,107.1,0,1
HB-073221,City Hotel,1,294,2025,August,33,16,2025-08-16,2,5,2,1.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.39,0,2
HB-009153,Resort Hotel,1,126,2024,October,44,29,2024-10-29,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,41.29,0,0
HB-081646,City Hotel,0,0,2023,December,50,15,2023-12-15,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,148.0,0,Transient,75.0,0,0
HB-106361,City Hotel,0,26,2025,February,8,19,2025-02-19,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,63.17,0,0
HB-067470,City Hotel,1,143,2025,May,18,4,2025-05-04,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,56.0,,0,Transient,120.0,0,0
HB-019772,Resort Hotel,0,41,2023,December,52,31,2023-12-31,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,5.0,,0,Transient,145.87,0,1
HB-060174,City Hotel,1,626,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-005576,Resort Hotel,1,5,2024,May,18,2,2024-05-02,1,2,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,D,D,0,No Deposit,,110.0,0,Transient,84.0,0,0
HB-108040,City Hotel,0,0,2025,April,16,18,2025-04-18,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,408.0,,0,Transient,100.0,0,0
HB-086364,City Hotel,0,55,2024,March,13,29,2024-03-29,0,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.85,0,0
HB-021110,Resort Hotel,0,3,2024,February,7,14,2024-02-14,2,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,0.0,1,0
HB-057553,City Hotel,1,74,2024,September,39,27,2024-09-27,0,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,149.4,0,0
HB-063002,City Hotel,1,154,2025,January,4,25,2025-01-25,1,4,2,1.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,103.7,0,3
HB-031200,Resort Hotel,0,19,2024,December,51,17,2024-12-17,0,1,2,0.0,0,HB,ESP,Direct,Direct,0,0,0,F,F,4,No Deposit,250.0,,0,Transient-Party,99.0,0,0
HB-096361,City Hotel,0,43,2024,August,35,29,2024-08-29,1,3,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,144.23,0,0
HB-075285,City Hotel,1,299,2023,August,32,12,2023-08-12,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-117247,City Hotel,0,244,2025,July,31,29,2025-07-29,2,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,2
HB-010370,Resort Hotel,1,50,2025,March,9,1,2025-03-01,6,19,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,440.0,,0,Transient-Party,55.8,0,0
HB-108597,City Hotel,0,1,2025,March,13,29,2025-03-29,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,1
HB-006968,Resort Hotel,1,72,2024,July,28,14,2024-07-14,1,3,2,0.0,0,BB,LUX,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,177.5,0,0
HB-082798,City Hotel,1,68,2024,February,7,17,2024-02-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,37.0,,0,Transient,75.0,0,0
HB-003617,Resort Hotel,0,114,2023,December,52,26,2023-12-26,2,4,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,156.0,,0,Contract,41.33,0,1
HB-108590,City Hotel,0,88,2025,March,13,27,2025-03-27,1,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,63.36,0,0
HB-113037,City Hotel,0,251,2025,May,22,27,2025-05-27,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,125.1,0,1
HB-028672,Resort Hotel,0,11,2024,October,41,9,2024-10-09,1,0,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,405.0,0,Transient-Party,50.0,0,0
HB-010785,Resort Hotel,1,26,2025,April,14,3,2025-04-03,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,175.0,,0,Transient,72.0,0,0
HB-097262,City Hotel,0,125,2024,September,36,4,2024-09-04,4,6,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,99.79,0,5
HB-062885,City Hotel,1,12,2025,January,4,23,2025-01-23,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,102.85,0,1
HB-103362,City Hotel,0,109,2024,December,51,16,2024-12-16,2,3,0,2.0,0,BB,BRA,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient,77.86,0,2
HB-110063,City Hotel,0,215,2025,April,16,19,2025-04-19,0,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient-Party,117.0,0,2
HB-096842,City Hotel,0,45,2024,September,36,5,2024-09-05,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,15.0,,0,Transient,99.18,0,0
HB-044268,City Hotel,0,164,2023,October,40,2,2023-10-02,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,19.0,,0,Transient-Party,100.0,0,0
HB-091203,City Hotel,0,3,2024,June,25,17,2024-06-17,0,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,141.0,0,2
HB-007252,Resort Hotel,1,142,2024,July,31,30,2024-07-30,2,6,2,1.0,1,FB,PRT,Direct,Direct,0,0,0,C,C,1,No Deposit,250.0,,0,Transient,292.0,0,0
HB-094892,City Hotel,0,1,2024,August,32,10,2024-08-10,0,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,167.0,1,0
HB-070779,City Hotel,1,17,2025,June,25,22,2025-06-22,1,3,2,0.0,0,SC,ARE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,1
HB-027327,Resort Hotel,0,69,2024,August,34,25,2024-08-25,0,2,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,145.53,0,1
HB-004348,Resort Hotel,1,49,2024,March,10,5,2024-03-05,2,2,1,0.0,0,HB,PRT,Groups,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient-Party,66.0,0,0
HB-069464,City Hotel,1,292,2025,May,22,31,2025-05-31,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,90.0,0,0
HB-046128,City Hotel,0,100,2023,December,50,12,2023-12-12,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,72.25,0,2
HB-101318,City Hotel,0,40,2024,November,45,7,2024-11-07,1,2,1,0.0,0,BB,FRA,Online TA,GDS,0,0,0,A,A,0,No Deposit,195.0,,0,Transient,169.2,0,0
HB-099990,City Hotel,0,69,2024,October,42,16,2024-10-16,2,3,2,1.0,0,BB,DEU,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,7.0,,0,Transient,153.05,0,1
HB-018619,Resort Hotel,0,4,2023,November,47,23,2023-11-23,1,1,1,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,25.0,0,0
HB-087015,City Hotel,0,87,2024,April,15,9,2024-04-09,2,2,2,0.0,0,SC,ARG,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,80.75,0,2
HB-053582,City Hotel,1,121,2024,June,26,24,2024-06-24,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,90.0,0,0
HB-026911,Resort Hotel,0,1,2024,August,33,14,2024-08-14,1,0,3,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,234.0,0,1
HB-004296,Resort Hotel,1,219,2024,March,9,2,2024-03-02,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,310.0,,0,Transient,52.0,0,0
HB-088119,City Hotel,0,9,2024,April,18,29,2024-04-29,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,29.0,,0,Transient-Party,110.0,0,0
HB-064159,City Hotel,1,28,2025,March,9,2,2025-03-02,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,95.0,0,0
HB-072106,City Hotel,1,21,2025,July,30,21,2025-07-21,0,1,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-059735,City Hotel,1,166,2024,November,44,1,2024-11-01,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,110.0,0,0
HB-085106,City Hotel,0,56,2024,March,10,5,2024-03-05,2,3,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,B,1,No Deposit,9.0,,0,Transient-Party,65.75,0,0
HB-037659,Resort Hotel,0,9,2025,June,25,22,2025-06-22,0,3,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,181.0,1,0
HB-010868,Resort Hotel,1,200,2025,April,15,8,2025-04-08,4,6,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,E,1,No Deposit,240.0,,0,Transient,74.46,0,2
HB-118422,City Hotel,0,219,2025,August,33,17,2025-08-17,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,131.7,0,1
HB-115836,City Hotel,0,76,2025,July,28,10,2025-07-10,1,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,1
HB-103196,City Hotel,0,12,2024,December,50,14,2024-12-14,0,1,1,0.0,0,BB,NLD,Online TA,GDS,0,0,0,A,A,0,No Deposit,195.0,,0,Transient,94.0,0,0
HB-038395,Resort Hotel,0,0,2025,July,29,15,2025-07-15,0,1,2,1.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,147.7,0,1
HB-043036,City Hotel,0,30,2023,September,37,13,2023-09-13,2,0,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,94.5,0,1
HB-011710,Resort Hotel,1,231,2025,May,22,26,2025-05-26,2,4,2,0.0,0,HB,POL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,122.4,0,1
HB-091678,City Hotel,0,41,2024,June,25,20,2024-06-20,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,110.7,1,1
HB-057191,City Hotel,1,200,2024,September,38,20,2024-09-20,1,5,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,150.45,0,0
HB-013043,Resort Hotel,1,116,2025,July,31,29,2025-07-29,2,1,2,2.0,0,HB,CHE,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,287.0,0,1
HB-073646,City Hotel,1,521,2025,August,35,29,2025-08-29,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-070253,City Hotel,1,36,2025,June,24,12,2025-06-12,1,4,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,144.0,0,1
HB-036603,Resort Hotel,0,26,2025,May,21,24,2025-05-24,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,146.0,,0,Transient,45.0,0,0
HB-012146,Resort Hotel,1,219,2025,June,24,15,2025-06-15,0,3,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient,84.6,0,1
HB-105173,City Hotel,0,1,2025,January,5,31,2025-01-31,0,2,1,0.0,0,BB,BRA,Corporate,Corporate,0,0,0,A,A,1,No Deposit,,40.0,0,Transient,65.0,0,0
HB-044418,City Hotel,1,97,2023,October,40,5,2023-10-05,1,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,140.0,0,0
HB-061769,City Hotel,1,99,2024,December,52,26,2024-12-26,1,3,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,127.71,0,3
HB-092007,City Hotel,0,88,2024,June,26,26,2024-06-26,2,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,102.3,0,1
HB-069901,City Hotel,1,183,2025,June,23,8,2025-06-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,86.0,,0,Transient,120.0,0,0
HB-089339,City Hotel,0,116,2024,May,20,15,2024-05-15,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.45,0,1
HB-068024,City Hotel,1,183,2025,May,19,11,2025-05-11,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,0,Transient,130.0,0,0
HB-115114,City Hotel,0,249,2025,June,26,25,2025-06-25,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,129.09,0,0
HB-018920,Resort Hotel,0,9,2023,December,48,3,2023-12-03,0,1,1,0.0,0,BB,ESP,Groups,Corporate,0,0,0,A,D,0,No Deposit,,343.0,0,Transient-Party,36.0,0,0
HB-104129,City Hotel,0,1,2025,January,1,5,2025-01-05,0,1,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,95.0,0,1
HB-058696,City Hotel,1,162,2024,October,42,14,2024-10-14,2,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,34.0,,0,Transient,115.0,0,0
HB-068794,City Hotel,1,113,2025,May,21,20,2025-05-20,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,34.0,,0,Transient,190.0,0,0
HB-048516,City Hotel,1,35,2024,March,13,25,2024-03-25,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,Non Refund,12.0,,0,Transient,5400.0,0,0
HB-111607,City Hotel,0,12,2025,May,19,9,2025-05-09,0,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,187.5,0,1
HB-004580,Resort Hotel,0,136,2024,March,12,24,2024-03-24,0,3,2,0.0,0,Undefined,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,387.0,,0,Transient-Party,84.0,0,0
HB-074185,City Hotel,1,356,2023,October,40,8,2023-10-08,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-114516,City Hotel,0,137,2025,June,25,19,2025-06-19,1,3,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,105.25,0,1
HB-103821,City Hotel,0,115,2024,December,52,27,2024-12-27,0,5,2,2.0,0,BB,BRA,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,7.0,,0,Transient,170.63,0,2
HB-078012,City Hotel,0,0,2023,September,39,30,2023-09-30,0,1,2,0.0,0,SC,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,87.78,0,0
HB-114276,City Hotel,0,317,2025,June,25,18,2025-06-18,1,0,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,113.4,1,2
HB-101002,City Hotel,0,44,2024,November,44,3,2024-11-03,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,157.0,,0,Transient,77.76,0,0
HB-079556,City Hotel,0,35,2023,October,43,26,2023-10-26,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Transient,75.0,0,1
HB-072399,City Hotel,1,467,2025,July,31,28,2025-07-28,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-095802,City Hotel,0,84,2024,August,34,22,2024-08-22,1,1,2,0.0,0,BB,CN,Direct,Direct,0,0,0,E,F,0,No Deposit,14.0,,0,Transient,150.3,0,0
HB-011663,Resort Hotel,1,8,2025,May,21,25,2025-05-25,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,331.0,0,Transient,45.0,0,0
HB-069960,City Hotel,1,169,2025,June,23,8,2025-06-08,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,170.0,0,0
HB-046129,City Hotel,0,100,2023,December,50,12,2023-12-12,2,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,72.25,0,2
HB-100530,City Hotel,0,163,2024,October,44,28,2024-10-28,0,1,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,B,1,No Deposit,9.0,,0,Transient,80.1,0,2
HB-003587,Resort Hotel,0,178,2023,December,51,24,2023-12-24,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,29.16,0,0
HB-083577,City Hotel,0,22,2024,February,5,4,2024-02-04,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,71.6,0,1
HB-095519,City Hotel,0,17,2024,August,34,19,2024-08-19,0,1,2,0.0,1,BB,PRT,Direct,Direct,0,0,0,A,D,1,No Deposit,14.0,,0,Transient,118.15,0,0
HB-112662,City Hotel,0,137,2025,May,21,23,2025-05-23,0,4,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.5,0,1
HB-098828,City Hotel,0,9,2024,October,40,2,2024-10-02,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,85.0,0,1
HB-047954,City Hotel,1,23,2024,March,10,10,2024-03-10,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.0,0,0
HB-041272,City Hotel,1,39,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,101.5,0,0
HB-008967,Resort Hotel,1,138,2024,October,43,22,2024-10-22,2,2,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,68.0,0,0
HB-054370,City Hotel,1,372,2024,July,28,14,2024-07-14,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-020948,Resort Hotel,0,2,2024,February,7,13,2024-02-13,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,85.0,0,0
HB-002157,Resort Hotel,0,61,2023,October,40,3,2023-10-03,2,1,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,86.0,0,1
HB-061048,City Hotel,1,510,2024,December,48,1,2024-12-01,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-059204,City Hotel,1,202,2024,October,43,22,2024-10-22,2,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,109.8,0,0
HB-079102,City Hotel,0,5,2023,October,42,21,2023-10-21,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,0.0,0,0
HB-046230,City Hotel,0,8,2023,December,52,26,2023-12-26,2,3,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,77.35,0,1
HB-034784,Resort Hotel,0,149,2025,March,10,8,2025-03-08,8,20,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,96.0,,0,Transient,54.0,0,0
HB-099192,City Hotel,0,102,2024,October,41,9,2024-10-09,1,0,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-058458,City Hotel,1,279,2024,October,41,12,2024-10-12,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,98.0,,0,Transient,110.0,0,0
HB-095386,City Hotel,0,143,2024,August,33,18,2024-08-18,0,1,0,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient,97.54,0,1
HB-043528,City Hotel,0,75,2023,September,38,19,2023-09-19,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,B,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-067829,City Hotel,1,88,2025,May,19,8,2025-05-08,1,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,170.0,,0,Transient,120.0,0,0
HB-012873,Resort Hotel,1,108,2025,July,30,21,2025-07-21,3,7,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,242.0,,0,Transient,229.0,0,1
HB-080722,City Hotel,0,3,2023,November,47,20,2023-11-20,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,122.0,0,1
HB-074931,City Hotel,1,136,2023,July,29,17,2023-07-17,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient,50.0,0,0
HB-103786,City Hotel,0,275,2024,December,52,28,2024-12-28,0,4,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,82.45,0,2
HB-080680,City Hotel,0,56,2023,November,46,19,2023-11-19,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Transient,60.0,0,1
HB-118602,City Hotel,0,107,2025,August,34,19,2025-08-19,2,2,3,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,22.0,,0,Transient,116.1,0,1
HB-078555,City Hotel,0,4,2023,October,41,12,2023-10-12,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-026632,Resort Hotel,0,57,2024,August,31,4,2024-08-04,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,157.53,0,1
HB-060143,City Hotel,1,88,2024,November,45,6,2024-11-06,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,165.75,0,1
HB-092203,City Hotel,0,126,2024,June,26,28,2024-06-28,0,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.95,0,1
HB-019171,Resort Hotel,0,0,2023,December,49,9,2023-12-09,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,40.0,0,0
HB-106392,City Hotel,0,12,2025,February,8,20,2025-02-20,1,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,90.72,0,1
HB-115571,City Hotel,0,222,2025,July,27,5,2025-07-05,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient-Party,107.1,0,2
HB-058216,City Hotel,1,145,2024,October,41,8,2024-10-08,2,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-105584,City Hotel,0,35,2025,February,7,10,2025-02-10,0,2,3,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,108.26,0,2
HB-076698,City Hotel,0,2,2024,August,32,7,2024-08-07,2,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,3,41,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-050838,City Hotel,1,73,2024,May,19,9,2024-05-09,1,4,3,0.0,0,BB,IND,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,150.45,0,0
HB-092292,City Hotel,0,81,2024,June,26,30,2024-06-30,1,3,2,0.0,0,SC,CHL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,103.5,0,1
HB-072840,City Hotel,1,478,2025,August,32,8,2025-08-08,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-008496,Resort Hotel,1,157,2024,October,40,1,2024-10-01,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,Non Refund,96.0,,0,Transient,52.0,0,0
HB-039586,Resort Hotel,0,4,2025,August,34,20,2025-08-20,2,0,1,0.0,0,BB,PRT,Complementary,Corporate,0,0,0,A,E,0,No Deposit,302.0,,0,Transient,0.0,0,1
HB-065321,City Hotel,1,66,2025,March,14,31,2025-03-31,0,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,0
HB-067933,City Hotel,1,6,2025,May,19,10,2025-05-10,0,1,2,0.0,0,BB,PRT,Groups,Corporate,0,0,0,A,A,0,Non Refund,47.0,,0,Transient,90.0,0,0
HB-005294,Resort Hotel,1,143,2024,April,17,24,2024-04-24,2,2,2,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,68.0,,0,Transient,84.0,0,0
HB-001112,Resort Hotel,1,64,2023,August,33,14,2023-08-14,2,5,3,0.0,0,HB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,229.0,0,1
HB-005871,Resort Hotel,0,205,2024,May,20,15,2024-05-15,4,6,1,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,54.0,0,1
HB-034333,Resort Hotel,0,0,2025,March,12,20,2025-03-20,0,0,1,0.0,0,BB,PRT,Direct,Direct,1,0,0,A,D,0,No Deposit,,,0,Transient,0.0,0,0
HB-071326,City Hotel,1,102,2025,July,27,2,2025-07-02,2,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,135.0,0,0
HB-117201,City Hotel,0,56,2025,July,31,29,2025-07-29,1,1,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-068545,City Hotel,1,175,2025,May,21,19,2025-05-19,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,44.0,,0,Transient,90.0,0,0
HB-098462,City Hotel,0,213,2024,October,40,6,2024-10-06,0,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,1,D,G,0,No Deposit,8.0,,0,Group,122.4,0,1
HB-034478,Resort Hotel,0,11,2025,March,13,24,2025-03-24,0,2,2,0.0,0,HB,ESP,Direct,Direct,0,0,0,E,E,1,No Deposit,250.0,,0,Transient,119.0,1,0
HB-053311,City Hotel,1,290,2024,June,25,17,2024-06-17,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,108,Transient-Party,72.0,0,0
HB-100658,City Hotel,0,35,2024,October,44,28,2024-10-28,1,2,2,0.0,0,BB,TUR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,129.0,0,1
HB-094769,City Hotel,0,167,2024,August,31,4,2024-08-04,2,3,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,72.25,0,1
HB-078182,City Hotel,0,17,2023,October,40,2,2023-10-02,1,2,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,10.0,,0,Transient,113.33,0,1
HB-057955,City Hotel,1,207,2024,October,40,4,2024-10-04,0,1,2,0.0,0,SC,HKG,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.1,0,0
HB-026090,Resort Hotel,0,6,2024,July,29,17,2024-07-17,2,2,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,96.0,,0,Transient,117.2,0,0
HB-035045,Resort Hotel,0,53,2025,April,14,5,2025-04-05,2,5,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,140.62,0,1
HB-051561,City Hotel,1,24,2024,May,21,21,2024-05-21,2,1,3,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,8.0,,0,Transient,285.17,0,0
HB-040135,City Hotel,1,87,2023,July,28,10,2023-07-10,3,7,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,58.9,0,1
HB-039284,Resort Hotel,0,33,2025,August,32,8,2025-08-08,0,5,2,0.0,0,HB,BRA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,241.0,,0,Transient,196.0,0,2
HB-015395,Resort Hotel,0,143,2023,July,27,9,2023-07-09,1,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,26.0,,0,Contract,58.23,0,1
HB-004101,Resort Hotel,1,140,2024,February,7,12,2024-02-12,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,50.0,0,0
HB-084795,City Hotel,0,117,2024,February,9,29,2024-02-29,1,2,1,0.0,0,BB,EGY,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,134.0,,0,Transient-Party,76.0,0,0
HB-006366,Resort Hotel,1,176,2024,June,23,5,2024-06-05,3,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,85.5,0,2
HB-109617,City Hotel,0,4,2025,April,15,11,2025-04-11,0,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,153.33,0,1
HB-063421,City Hotel,1,18,2025,February,7,11,2025-02-11,2,2,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,108.8,0,0
HB-116270,City Hotel,0,32,2025,July,29,16,2025-07-16,1,0,2,2.0,0,BB,NOR,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,8.0,,0,Transient,295.0,0,1
HB-081484,City Hotel,0,4,2024,May,20,13,2024-05-13,0,1,4,0.0,0,BB,PRT,Complementary,Direct,1,0,2,G,G,2,No Deposit,,45.0,0,Transient,0.0,1,4
HB-102642,City Hotel,0,81,2024,December,49,2,2024-12-02,0,2,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,59.84,0,0
HB-020772,Resort Hotel,0,6,2024,February,6,7,2024-02-07,2,0,3,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,123.0,0,1
HB-047969,City Hotel,1,17,2024,March,11,11,2024-03-11,0,2,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.0,0,1
HB-033552,Resort Hotel,0,139,2025,February,7,12,2025-02-12,4,10,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,40.0,,0,Transient,99.0,0,0
HB-116369,City Hotel,0,178,2025,July,29,16,2025-07-16,2,1,3,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,107.1,0,0
HB-022374,Resort Hotel,0,31,2024,March,12,19,2024-03-19,2,3,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,81.0,1,0
HB-046540,City Hotel,0,4,2024,January,1,6,2024-01-06,0,1,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,86.0,1,0
HB-091880,City Hotel,0,192,2024,June,26,24,2024-06-24,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,34.0,,0,Transient-Party,95.0,0,0
HB-005550,Resort Hotel,1,199,2024,May,18,2,2024-05-02,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,85.0,0,0
HB-099930,City Hotel,0,40,2024,October,42,19,2024-10-19,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,85.5,0,0
HB-085255,City Hotel,0,16,2024,March,11,11,2024-03-11,0,1,2,0.0,0,BB,ESP,Corporate,TA/TO,0,0,0,A,A,0,No Deposit,,215.0,0,Transient-Party,75.0,0,0
HB-006998,Resort Hotel,1,103,2024,July,29,16,2024-07-16,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,180.0,0,0
HB-116907,City Hotel,0,102,2025,July,30,23,2025-07-23,2,2,3,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,85.0,,0,Transient,140.4,0,0
HB-088908,City Hotel,0,36,2024,May,19,11,2024-05-11,0,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.9,0,2
HB-038286,Resort Hotel,0,21,2025,July,28,11,2025-07-11,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,158.0,0,1
HB-074382,City Hotel,1,283,2023,July,30,27,2023-07-27,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-002433,Resort Hotel,0,1,2023,October,41,14,2023-10-14,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,5.0,,0,Transient-Party,37.6,1,1
HB-091574,City Hotel,0,0,2024,June,25,23,2024-06-23,0,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.0,0,1
HB-108169,City Hotel,0,58,2025,August,34,23,2025-08-23,0,2,1,0.0,0,BB,ITA,Online TA,TA/TO,1,0,1,A,A,0,No Deposit,7.0,,0,Transient,111.2,0,1
HB-051116,City Hotel,1,276,2024,May,20,13,2024-05-13,2,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,160,Transient,61.0,0,0
HB-063416,City Hotel,1,18,2025,February,7,11,2025-02-11,2,2,2,2.0,0,BB,CHE,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,9.0,,0,Transient,198.0,0,0
HB-059202,City Hotel,1,202,2024,October,43,22,2024-10-22,2,1,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,128.7,0,0
HB-027630,Resort Hotel,0,0,2024,September,36,3,2024-09-03,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,F,0,No Deposit,,,0,Transient,179.0,0,0
HB-032693,Resort Hotel,0,1,2025,February,5,1,2025-02-01,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,1,No Deposit,,130.0,0,Transient-Party,35.0,0,0
HB-036043,Resort Hotel,0,2,2025,May,19,7,2025-05-07,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,195.0,0,Group,45.0,0,0
HB-104700,City Hotel,0,29,2025,January,3,18,2025-01-18,0,3,1,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,171.0,,0,Transient-Party,65.0,0,0
HB-032948,Resort Hotel,0,14,2025,February,6,9,2025-02-09,0,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,467.0,,0,Transient,38.4,0,0
HB-096920,City Hotel,0,58,2024,September,36,8,2024-09-08,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,149.4,0,1
HB-098230,City Hotel,0,114,2024,September,39,23,2024-09-23,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,135.9,0,2
HB-009343,Resort Hotel,1,136,2024,November,46,14,2024-11-14,3,7,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,37.8,0,0
HB-088624,City Hotel,0,1,2024,May,19,6,2024-05-06,1,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,1,No Deposit,,216.0,0,Transient,105.0,0,0
HB-070238,City Hotel,1,20,2025,June,24,12,2025-06-12,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,99.0,0,0
HB-068266,City Hotel,1,104,2025,May,20,15,2025-05-15,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-037489,Resort Hotel,0,145,2025,June,25,18,2025-06-18,1,0,2,0.0,0,BB,NZL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,171.0,,0,Transient,59.4,0,0
HB-080339,City Hotel,0,61,2023,November,45,12,2023-11-12,1,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,81.9,0,1
HB-089785,City Hotel,0,8,2024,May,21,25,2024-05-25,0,1,2,0.0,0,SC,TUR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.0,0,0
HB-109510,City Hotel,0,160,2025,April,15,9,2025-04-09,2,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,2
HB-051809,City Hotel,1,323,2024,May,21,26,2024-05-26,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-071137,City Hotel,1,368,2025,June,26,28,2025-06-28,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-104303,City Hotel,0,75,2025,January,2,8,2025-01-08,2,1,1,0.0,0,BB,USA,Groups,TA/TO,0,0,0,D,D,0,No Deposit,330.0,,0,Transient-Party,67.0,0,2
HB-000465,Resort Hotel,1,15,2023,July,29,17,2023-07-17,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,134.0,0,1
HB-100488,City Hotel,0,0,2024,October,44,28,2024-10-28,0,0,0,0.0,0,SC,PRT,Online TA,TA/TO,1,0,0,A,K,0,No Deposit,9.0,,0,Transient,0.0,0,1
HB-098043,City Hotel,0,44,2024,September,38,20,2024-09-20,0,4,2,0.0,0,BB,IRN,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,157.0,,0,Transient,101.52,0,0
HB-103205,City Hotel,0,10,2024,December,50,15,2024-12-15,0,1,1,0.0,0,BB,MAR,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,88.0,0,0
HB-061188,City Hotel,1,70,2024,December,49,3,2024-12-03,2,2,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,74.8,0,2
HB-003114,Resort Hotel,0,105,2023,November,46,18,2023-11-18,2,4,2,0.0,0,Undefined,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,313.0,,65,Transient-Party,69.0,0,0
HB-109453,City Hotel,0,102,2025,April,15,9,2025-04-09,2,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,0
HB-035364,Resort Hotel,0,33,2025,April,15,8,2025-04-08,4,8,2,0.0,0,Undefined,GBR,Offline TA/TO,TA/TO,0,0,0,D,E,0,No Deposit,40.0,,0,Contract,106.85,0,1
HB-046822,City Hotel,1,151,2024,January,3,19,2024-01-19,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,19.0,,63,Transient-Party,80.0,0,0
HB-089507,City Hotel,0,189,2024,May,20,19,2024-05-19,0,3,1,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,65.0,0,0
HB-029523,Resort Hotel,0,10,2024,October,44,29,2024-10-29,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,36.0,0,0
HB-078438,City Hotel,0,0,2023,October,40,7,2023-10-07,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,138.0,0,0
HB-091319,City Hotel,0,45,2024,June,25,17,2024-06-17,1,2,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,65.0,0,1
HB-049389,City Hotel,1,29,2024,April,15,12,2024-04-12,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,111.15,0,0
HB-026161,Resort Hotel,0,140,2024,July,29,19,2024-07-19,0,4,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,175.0,,0,Transient,150.0,1,1
HB-058737,City Hotel,1,93,2024,October,42,15,2024-10-15,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,34.0,,0,Transient,115.0,0,0
HB-045919,City Hotel,0,84,2023,November,48,27,2023-11-27,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,64.0,0,1
HB-098260,City Hotel,0,35,2024,September,39,25,2024-09-25,2,0,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,117.0,0,2
HB-118591,City Hotel,0,11,2025,August,34,22,2025-08-22,0,1,1,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,D,G,1,No Deposit,9.0,,0,Transient,170.0,0,0
HB-064131,City Hotel,1,28,2025,March,9,2,2025-03-02,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,95.0,0,0
HB-045915,City Hotel,0,84,2023,November,48,27,2023-11-27,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,64.0,0,0
HB-102155,City Hotel,0,215,2024,November,47,21,2024-11-21,1,2,2,0.0,0,BB,POL,Groups,Corporate,0,0,0,A,D,2,No Deposit,,233.0,0,Transient,91.67,0,0
HB-043274,City Hotel,0,162,2023,September,37,17,2023-09-17,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,3.0,,0,Transient-Party,60.0,0,0
HB-097641,City Hotel,0,85,2024,September,37,15,2024-09-15,1,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,149.4,0,1
HB-054814,City Hotel,1,391,2024,July,30,27,2024-07-27,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,65.0,0,0
HB-086345,City Hotel,0,123,2024,March,13,28,2024-03-28,1,3,3,0.0,0,BB,DEU,Direct,Direct,0,0,0,A,B,1,No Deposit,,,0,Transient,93.0,0,2
HB-078766,City Hotel,1,14,2023,October,42,19,2023-10-19,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Contract,126.0,0,0
HB-070275,City Hotel,1,36,2025,June,24,13,2025-06-13,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,144.0,0,1
HB-118745,City Hotel,0,96,2025,August,34,21,2025-08-21,1,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,168.0,,0,Transient,89.1,0,0
HB-017517,Resort Hotel,0,3,2023,December,49,10,2023-12-10,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,9.0,0,Transient,35.0,0,0
HB-056659,City Hotel,1,198,2024,September,37,9,2024-09-09,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,90.0,0,0
HB-097628,City Hotel,0,179,2024,September,37,12,2024-09-12,2,5,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,80.75,0,0
HB-000713,Resort Hotel,1,33,2023,July,30,26,2023-07-26,2,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,5.0,,0,Transient,132.5,0,0
HB-028469,Resort Hotel,0,0,2024,October,40,3,2024-10-03,1,0,2,0.0,0,BB,SWE,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient,130.0,0,0
HB-018037,Resort Hotel,0,0,2023,October,44,30,2023-10-30,0,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,37.73,0,1
HB-024954,Resort Hotel,0,1,2024,June,23,9,2024-06-09,0,1,2,0.0,0,BB,ARG,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,119.0,0,0
HB-056094,City Hotel,1,102,2024,August,35,28,2024-08-28,6,12,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,111.7,0,0
HB-043205,City Hotel,0,15,2023,September,37,16,2023-09-16,0,2,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,9.0,,0,Contract,115.0,0,2
HB-069032,City Hotel,1,243,2025,May,21,24,2025-05-24,0,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,138.77,0,2
HB-071285,City Hotel,1,140,2025,July,27,1,2025-07-01,2,1,2,0.0,0,SC,JOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,0
HB-069029,City Hotel,1,262,2025,May,21,24,2025-05-24,0,4,3,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,157.5,0,2
HB-013735,Resort Hotel,1,172,2025,August,35,28,2025-08-28,1,2,3,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,315.0,,0,Contract,198.05,0,0
HB-093415,City Hotel,0,12,2024,July,29,19,2024-07-19,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,87.78,0,2
HB-113771,City Hotel,0,82,2025,June,23,8,2025-06-08,1,3,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,126.0,0,1
HB-052375,City Hotel,1,275,2024,June,23,4,2024-06-04,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,5.0,,69,Transient,62.8,0,0
HB-090401,City Hotel,0,58,2024,June,23,5,2024-06-05,1,0,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,76.92,0,1
HB-099145,City Hotel,0,85,2024,October,40,6,2024-10-06,1,3,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,85.0,0,1
HB-110283,City Hotel,0,7,2025,April,17,22,2025-04-22,2,1,2,0.0,0,BB,ITA,Direct,Direct,0,0,0,D,D,1,No Deposit,,,0,Transient,159.0,0,1
HB-004995,Resort Hotel,1,212,2024,April,15,11,2024-04-11,2,5,2,0.0,0,HB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,273.0,,0,Transient,67.05,0,0
HB-026033,Resort Hotel,0,12,2024,July,29,15,2024-07-15,2,2,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,193.5,0,1
HB-097222,City Hotel,0,8,2024,September,37,12,2024-09-12,1,1,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,8.0,,0,Transient,187.55,0,1
HB-041579,City Hotel,1,11,2023,August,33,18,2023-08-18,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,2,Non Refund,,48.0,0,Transient,67.0,0,0
HB-009745,Resort Hotel,1,196,2024,December,1,30,2024-12-30,1,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,C,1,No Deposit,,308.0,0,Transient-Party,180.0,0,0
HB-092687,City Hotel,0,151,2024,July,27,6,2024-07-06,1,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,120.7,0,1
HB-048972,City Hotel,1,81,2024,April,14,3,2024-04-03,2,3,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,10.0,,0,Transient,73.9,0,0
HB-047715,City Hotel,1,31,2024,March,9,1,2024-03-01,0,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,106.4,0,1
HB-070131,City Hotel,1,45,2025,June,24,10,2025-06-10,2,1,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,120.0,0,0
HB-027282,Resort Hotel,0,342,2025,August,34,20,2025-08-20,2,3,2,0.0,0,HB,PRT,Online TA,TA/TO,1,0,1,D,D,0,No Deposit,240.0,,0,Transient,185.4,0,2
HB-118184,City Hotel,0,139,2025,August,32,9,2025-08-09,2,5,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,83.0,,0,Transient,111.6,0,0
HB-001505,Resort Hotel,0,27,2023,September,35,1,2023-09-01,2,5,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,142.0,,0,Contract,101.03,0,0
HB-083414,City Hotel,0,2,2024,January,5,30,2024-01-30,0,1,1,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,80.0,0,1
HB-086596,City Hotel,0,5,2024,April,14,1,2024-04-01,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,141.0,0,2
HB-071990,City Hotel,1,7,2025,July,29,17,2025-07-17,1,1,3,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,210.0,0,0
HB-067685,City Hotel,1,162,2025,May,19,6,2025-05-06,2,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,80.0,0,0
HB-040602,City Hotel,1,76,2023,August,31,3,2023-08-03,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,12.0,0,0
HB-074409,City Hotel,1,290,2023,August,31,3,2023-08-03,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-078415,City Hotel,0,11,2023,October,40,4,2023-10-04,2,3,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,10.0,,0,Transient-Party,125.4,0,1
HB-076975,City Hotel,1,342,2023,September,38,24,2023-09-24,2,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-033548,Resort Hotel,0,70,2025,February,8,22,2025-02-22,0,4,2,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,405.0,0,Transient-Party,42.0,0,0
HB-076829,City Hotel,0,0,2023,August,32,12,2023-08-12,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,138.0,0,0
HB-071582,City Hotel,1,191,2025,July,28,8,2025-07-08,1,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,1
HB-083863,City Hotel,0,1,2024,February,7,13,2024-02-13,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.0,0,0
HB-092670,City Hotel,0,1,2024,July,27,6,2024-07-06,0,4,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,168.5,0,0
HB-062704,City Hotel,1,559,2025,January,3,19,2025-01-19,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-017467,Resort Hotel,0,35,2023,October,40,6,2023-10-06,1,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,B,0,No Deposit,171.0,,0,Transient,52.5,1,0
HB-068486,City Hotel,1,94,2025,May,20,18,2025-05-18,2,3,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.6,0,0
HB-003680,Resort Hotel,0,165,2023,December,52,30,2023-12-30,0,4,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,C,0,No Deposit,308.0,,122,Transient-Party,136.5,0,0
HB-010403,Resort Hotel,1,15,2025,March,10,5,2025-03-05,2,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,60.0,0,1
HB-073250,City Hotel,1,1,2025,August,33,17,2025-08-17,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,170.0,0,0
HB-071496,City Hotel,1,173,2025,July,27,6,2025-07-06,1,3,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,89.1,0,0
HB-087570,City Hotel,0,89,2024,April,16,18,2024-04-18,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.95,0,1
HB-023246,Resort Hotel,0,31,2024,April,16,18,2024-04-18,1,1,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,E,E,0,No Deposit,,,0,Transient,91.0,0,0
HB-036781,Resort Hotel,0,203,2025,May,21,25,2025-05-25,1,3,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,4,No Deposit,,223.0,0,Transient-Party,55.0,1,0
HB-081837,City Hotel,1,178,2024,April,17,28,2024-04-28,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,46,Transient,110.0,0,0
HB-064334,City Hotel,1,97,2025,March,10,6,2025-03-06,1,1,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,0
HB-002576,Resort Hotel,0,122,2023,October,42,22,2023-10-22,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,240.0,,0,Transient,55.0,0,2
HB-010835,Resort Hotel,1,24,2025,April,15,8,2025-04-08,0,1,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,E,F,0,No Deposit,240.0,,0,Transient,147.0,0,1
HB-060745,City Hotel,1,74,2024,November,47,19,2024-11-19,2,4,2,0.0,0,SC,MLT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,2
HB-045265,City Hotel,0,69,2023,October,43,25,2023-10-25,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,58,Transient-Party,85.67,0,0
HB-014532,Resort Hotel,0,2,2025,March,13,30,2025-03-30,0,1,1,0.0,0,BB,,Corporate,Corporate,0,0,3,A,A,0,No Deposit,,135.0,0,Transient,35.0,1,0
HB-056469,City Hotel,1,163,2024,September,36,7,2024-09-07,0,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,116.1,0,0
HB-043918,City Hotel,1,87,2023,September,39,25,2023-09-25,2,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-049383,City Hotel,1,47,2024,April,15,12,2024-04-12,0,1,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,B,1,No Deposit,9.0,,0,Transient,99.9,0,0
HB-008696,Resort Hotel,0,337,2024,October,41,9,2024-10-09,2,5,1,0.0,0,HB,GBR,Groups,Direct,0,0,0,A,A,1,No Deposit,273.0,,101,Transient-Party,42.81,0,0
HB-008486,Resort Hotel,1,157,2024,October,40,1,2024-10-01,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,Non Refund,96.0,,0,Transient,52.0,0,0
HB-055703,City Hotel,1,242,2024,August,34,19,2024-08-19,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.3,0,1
HB-054041,City Hotel,1,245,2024,July,27,6,2024-07-06,2,4,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,110.0,0,0
HB-071636,City Hotel,1,226,2025,July,28,9,2025-07-09,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-098076,City Hotel,0,296,2024,September,38,21,2024-09-21,0,4,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,26.0,,0,Transient-Party,117.0,0,1
HB-061375,City Hotel,1,98,2024,December,49,8,2024-12-08,0,3,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,2
HB-086661,City Hotel,0,55,2024,April,14,6,2024-04-06,0,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,104.0,0,0
HB-017012,Resort Hotel,0,239,2023,September,38,19,2023-09-19,1,1,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,C,0,No Deposit,248.0,,0,Transient-Party,80.0,0,0
HB-035123,Resort Hotel,0,53,2025,April,15,10,2025-04-10,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,70.53,1,1
HB-017076,Resort Hotel,0,0,2023,September,38,23,2023-09-23,0,1,2,0.0,0,BB,CHE,Direct,Direct,0,0,0,A,C,0,No Deposit,,,0,Transient,98.0,1,0
HB-095566,City Hotel,0,0,2024,August,34,20,2024-08-20,0,1,2,0.0,0,SC,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,129.0,0,0
HB-100401,City Hotel,0,33,2024,October,43,26,2024-10-26,0,2,1,0.0,0,SC,ITA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,109.0,0,0
HB-011823,Resort Hotel,1,411,2025,May,22,31,2025-05-31,2,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,71.1,0,0
HB-087252,City Hotel,0,26,2024,April,16,15,2024-04-15,0,2,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,145.0,0,2
HB-092033,City Hotel,0,120,2024,June,26,27,2024-06-27,1,2,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.5,0,0
HB-062413,City Hotel,1,277,2025,January,3,13,2025-01-13,0,2,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,83.61,0,0
HB-022347,Resort Hotel,0,44,2024,March,11,17,2024-03-17,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,2.0,,0,Contract,72.43,0,1
HB-042347,City Hotel,0,16,2023,September,36,5,2023-09-05,1,1,2,2.0,0,BB,ESP,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient,185.0,0,2
HB-076079,City Hotel,1,364,2023,October,42,16,2023-10-16,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-112170,City Hotel,0,105,2025,May,20,18,2025-05-18,0,3,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,144.0,0,2
HB-044408,City Hotel,0,88,2023,October,40,5,2023-10-05,1,1,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,26.0,,77,Transient-Party,90.6,0,0
HB-066076,City Hotel,1,155,2025,April,15,13,2025-04-13,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,0,Transient,130.0,0,0
HB-071178,City Hotel,1,107,2025,June,26,29,2025-06-29,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,171.0,0,0
HB-098967,City Hotel,0,163,2024,October,40,2,2024-10-02,2,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,168.0,,0,Transient-Party,80.75,0,0
HB-045109,City Hotel,0,41,2023,October,42,16,2023-10-16,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.9,0,2
HB-037248,Resort Hotel,0,45,2025,June,24,9,2025-06-09,0,2,2,0.0,1,HB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient-Party,172.0,0,0
HB-030815,Resort Hotel,0,25,2024,November,48,30,2024-11-30,0,4,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,40.8,0,1
HB-044832,City Hotel,0,166,2023,October,41,12,2023-10-12,1,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,89.25,0,2
HB-054345,City Hotel,1,193,2024,July,28,13,2024-07-13,2,7,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.95,0,0
HB-062858,City Hotel,1,59,2025,January,4,23,2025-01-23,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,326.0,,0,Transient,80.0,0,0
HB-027758,Resort Hotel,0,8,2024,September,37,10,2024-09-10,0,1,2,0.0,0,BB,PRT,Direct,TA/TO,0,0,0,A,C,0,No Deposit,,,0,Transient,171.0,1,1
HB-059753,City Hotel,1,166,2024,November,44,1,2024-11-01,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,110.0,0,0
HB-063871,City Hotel,1,38,2025,February,8,23,2025-02-23,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,102.0,0,0
HB-110669,City Hotel,0,15,2025,April,18,28,2025-04-28,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,425.0,,0,Transient,123.0,0,0
HB-074954,City Hotel,1,153,2023,August,31,3,2023-08-03,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-076113,City Hotel,1,260,2023,September,38,18,2023-09-18,0,2,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,1,Non Refund,6.0,,0,Transient-Party,80.0,0,0
HB-024040,Resort Hotel,0,22,2024,May,19,9,2024-05-09,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,72.0,1,1
HB-117912,City Hotel,0,147,2025,August,32,5,2025-08-05,2,5,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,184.5,0,1
HB-010606,Resort Hotel,1,201,2025,March,12,18,2025-03-18,2,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient,37.8,0,2
HB-041444,City Hotel,0,5,2023,August,33,16,2023-08-16,1,0,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,75.0,0,0
HB-063945,City Hotel,1,134,2025,February,9,25,2025-02-25,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,75.0,0,0
HB-046164,City Hotel,1,4,2023,December,51,19,2023-12-19,0,1,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient,154.5,0,0
HB-060054,City Hotel,1,95,2024,November,45,5,2024-11-05,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,75.0,0,0
HB-091630,City Hotel,0,8,2024,June,25,20,2024-06-20,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,128.5,0,2
HB-096730,City Hotel,0,53,2024,September,35,1,2024-09-01,2,4,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,121.35,0,1
HB-002401,Resort Hotel,0,41,2023,October,41,11,2023-10-11,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,56.0,0,1
HB-104118,City Hotel,0,7,2024,December,1,31,2024-12-31,2,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,118.2,0,1
HB-051004,City Hotel,1,91,2024,May,20,13,2024-05-13,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,140.4,0,0
HB-119353,City Hotel,0,63,2025,August,35,31,2025-08-31,0,3,3,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,195.33,0,2
HB-058874,City Hotel,1,67,2024,October,42,17,2024-10-17,1,0,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,34.0,,0,Transient,115.0,0,0
HB-009899,Resort Hotel,1,41,2025,January,3,19,2025-01-19,0,2,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,468.0,,0,Transient,57.6,0,0
HB-107105,City Hotel,0,137,2025,March,10,6,2025-03-06,1,1,2,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,80.0,0,1
HB-091689,City Hotel,0,2,2024,June,25,23,2024-06-23,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.0,1,2
HB-076449,City Hotel,1,379,2023,October,44,31,2023-10-31,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-106303,City Hotel,0,48,2025,February,8,22,2025-02-22,0,2,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,65.0,0,1
HB-094912,City Hotel,0,20,2024,August,32,10,2024-08-10,0,2,2,2.0,0,BB,ISR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,231.0,0,1
HB-008632,Resort Hotel,1,393,2024,October,41,8,2024-10-08,2,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,68.0,,0,Transient,72.0,0,0
HB-091238,City Hotel,0,150,2024,June,24,16,2024-06-16,0,3,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,90.0,0,1
HB-113493,City Hotel,0,364,2025,June,25,16,2025-06-16,0,1,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,1,A,A,0,No Deposit,21.0,,0,Group,75.0,0,1
HB-090020,City Hotel,0,56,2024,May,22,30,2024-05-30,1,1,1,0.0,0,BB,CHE,Groups,TA/TO,0,0,0,A,D,1,No Deposit,,,0,Transient-Party,120.0,0,0
HB-094607,City Hotel,0,84,2024,July,31,31,2024-07-31,2,5,3,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,151.59,0,1
HB-040627,City Hotel,1,28,2023,August,31,3,2023-08-03,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-001715,Resort Hotel,0,160,2023,September,36,10,2023-09-10,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Contract,48.88,0,0
HB-091166,City Hotel,0,256,2024,June,24,15,2024-06-15,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-010866,Resort Hotel,1,70,2025,April,15,8,2025-04-08,2,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,77.86,0,0
HB-105234,City Hotel,0,0,2025,January,4,23,2025-01-23,3,8,1,2.0,0,BB,AGO,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,88.0,0,0
HB-091718,City Hotel,0,265,2024,June,26,24,2024-06-24,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-021724,Resort Hotel,0,0,2024,March,10,8,2024-03-08,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,40.0,0,0
HB-060449,City Hotel,1,54,2024,November,46,11,2024-11-11,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,0
HB-019511,Resort Hotel,0,10,2023,December,51,24,2023-12-24,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,64.0,1,0
HB-054806,City Hotel,1,391,2024,July,30,27,2024-07-27,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,65.0,0,0
HB-032786,Resort Hotel,0,1,2025,February,6,3,2025-02-03,0,2,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,88.0,0,0
HB-039198,Resort Hotel,0,48,2025,August,32,7,2025-08-07,1,3,2,0.0,0,HB,OMN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,26.0,,0,Transient-Party,216.84,0,0
HB-083725,City Hotel,0,19,2024,February,6,7,2024-02-07,2,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,82.8,0,2
HB-093775,City Hotel,0,144,2024,July,30,25,2024-07-25,1,1,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,81.08,0,1
HB-059973,City Hotel,1,305,2024,November,45,4,2024-11-04,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,89.0,0,0
HB-014786,Resort Hotel,1,275,2023,October,40,4,2023-10-04,2,0,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,26,0,A,A,0,Non Refund,208.0,,0,Transient,50.0,0,0
HB-061007,City Hotel,1,42,2024,November,48,29,2024-11-29,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,348.0,0,Transient,90.0,0,0
HB-052884,City Hotel,1,71,2024,June,24,14,2024-06-14,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,120.0,0,0
HB-105502,City Hotel,0,63,2025,February,6,5,2025-02-05,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.4,0,2
HB-022062,Resort Hotel,0,18,2024,March,11,15,2024-03-15,0,2,2,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,54.0,1,1
HB-004630,Resort Hotel,1,106,2024,March,12,24,2024-03-24,1,3,2,0.0,0,FB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,68.0,,0,Transient,84.0,0,0
HB-021938,Resort Hotel,0,2,2024,March,11,12,2024-03-12,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient-Party,58.0,0,0
HB-031255,Resort Hotel,0,79,2024,December,51,16,2024-12-16,2,3,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,70.8,1,1
HB-061355,City Hotel,1,86,2024,December,49,8,2024-12-08,0,3,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,174.0,0,0
HB-082420,City Hotel,0,4,2023,December,52,26,2023-12-26,2,2,2,0.0,0,SC,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,52.5,0,2
HB-071500,City Hotel,1,387,2025,July,27,6,2025-07-06,1,3,2,2.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient,159.0,0,3
HB-034446,Resort Hotel,0,84,2025,March,9,1,2025-03-01,6,19,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,440.0,,0,Transient-Party,55.8,0,1
HB-052398,City Hotel,1,163,2024,June,23,5,2024-06-05,2,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,171.0,,0,Transient,100.0,0,0
HB-008085,Resort Hotel,1,118,2024,September,37,10,2024-09-10,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,130.43,0,0
HB-058244,City Hotel,1,124,2024,October,41,9,2024-10-09,2,0,2,1.0,0,BB,ISR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,135.0,0,0
HB-077090,City Hotel,0,17,2023,September,35,3,2023-09-03,0,3,1,1.0,0,BB,DEU,Direct,Direct,0,0,0,B,B,0,No Deposit,14.0,,0,Transient,89.25,0,1
HB-081761,City Hotel,1,113,2024,February,8,25,2024-02-25,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,44,Transient,75.0,0,0
HB-012278,Resort Hotel,1,107,2025,June,25,22,2025-06-22,0,2,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,120.0,0,2
HB-095567,City Hotel,0,0,2024,August,34,19,2024-08-19,0,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,148.0,0,0
HB-032597,Resort Hotel,0,0,2025,January,5,30,2025-01-30,1,3,1,0.0,0,BB,GBR,Direct,TA/TO,1,0,0,A,A,3,No Deposit,,,0,Transient,43.0,0,2
HB-021327,Resort Hotel,0,0,2024,February,8,22,2024-02-22,1,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,34.4,0,0
HB-116064,City Hotel,0,414,2025,July,28,13,2025-07-13,0,2,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,122.4,0,1
HB-060352,City Hotel,1,626,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-081135,City Hotel,1,146,2024,March,13,30,2024-03-30,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,86.0,,28,Transient,80.0,0,0
HB-068488,City Hotel,1,84,2025,May,20,18,2025-05-18,2,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.14,0,1
HB-039806,Resort Hotel,0,3,2025,August,35,27,2025-08-27,1,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,330.0,,0,Transient-Party,75.0,0,2
HB-058267,City Hotel,1,131,2024,October,41,10,2024-10-10,1,0,1,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,0
HB-002879,Resort Hotel,0,24,2023,November,44,3,2023-11-03,3,10,2,0.0,0,BB,ITA,Corporate,Corporate,0,0,0,A,A,2,No Deposit,326.0,281.0,0,Transient-Party,48.0,0,0
HB-047843,City Hotel,1,50,2024,March,10,5,2024-03-05,2,2,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient-Party,67.66,0,0
HB-100433,City Hotel,0,40,2024,October,43,25,2024-10-25,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-089573,City Hotel,0,25,2024,May,21,21,2024-05-21,1,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,155.0,1,1
HB-025222,Resort Hotel,0,130,2024,June,24,12,2024-06-12,2,5,2,2.0,0,BB,IRL,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,161.0,0,1
HB-037026,Resort Hotel,0,335,2025,May,22,26,2025-05-26,2,7,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,62.75,0,2
HB-061440,City Hotel,1,12,2024,December,50,10,2024-12-10,2,1,2,2.0,0,BB,MAR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,176.33,0,0
HB-011320,Resort Hotel,1,209,2025,May,18,3,2025-05-03,0,1,2,0.0,0,HB,RUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,82.8,0,0
HB-081159,City Hotel,0,59,2023,November,48,28,2023-11-28,2,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,106.2,0,1
HB-114611,City Hotel,0,149,2025,June,26,24,2025-06-24,0,1,2,0.0,0,HB,USA,Corporate,Corporate,0,0,0,A,A,0,No Deposit,495.0,,0,Transient-Party,154.0,0,1
HB-110593,City Hotel,0,82,2025,April,17,23,2025-04-23,2,4,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,123.0,0,1
HB-003438,Resort Hotel,1,81,2023,December,49,6,2023-12-06,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,40.5,0,2
HB-111234,City Hotel,0,51,2025,May,19,6,2025-05-06,1,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,134.1,0,0
HB-022601,Resort Hotel,0,0,2024,March,13,29,2024-03-29,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,48.0,0,0
HB-005843,Resort Hotel,1,9,2024,May,20,15,2024-05-15,1,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,315.0,,0,Transient-Party,70.0,0,0
HB-110454,City Hotel,0,41,2025,April,17,26,2025-04-26,0,2,1,0.0,0,BB,NLD,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,280.0,0,Transient-Party,110.0,0,0
HB-100348,City Hotel,0,151,2024,October,43,23,2024-10-23,2,2,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,104.85,0,2
HB-099856,City Hotel,0,57,2024,October,41,13,2024-10-13,2,4,1,0.0,0,BB,USA,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,128.7,0,0
HB-020149,Resort Hotel,0,0,2024,January,3,15,2024-01-15,0,2,2,0.0,0,BB,CHN,Direct,Direct,0,0,0,A,D,1,No Deposit,,,0,Transient,44.0,0,0
HB-041747,City Hotel,0,44,2023,August,34,22,2023-08-22,2,1,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,63.0,0,0
HB-079475,City Hotel,0,12,2023,October,43,25,2023-10-25,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,85.67,0,0
HB-112857,City Hotel,0,121,2025,May,22,26,2025-05-26,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-052454,City Hotel,1,213,2024,June,23,7,2024-06-07,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,62,Transient,130.0,0,0
HB-067269,City Hotel,1,18,2025,May,18,1,2025-05-01,1,0,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,0
HB-031556,Resort Hotel,0,14,2024,December,1,30,2024-12-30,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,G,0,No Deposit,240.0,,0,Transient,109.5,0,0
HB-083317,City Hotel,0,59,2024,January,4,28,2024-01-28,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,87.0,,0,Transient-Party,80.0,0,0
HB-028462,Resort Hotel,0,29,2024,October,40,1,2024-10-01,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,99.0,0,1
HB-004299,Resort Hotel,1,219,2024,March,9,2,2024-03-02,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,310.0,,0,Transient,52.0,0,0
HB-092179,City Hotel,0,53,2024,June,26,30,2024-06-30,0,2,2,0.0,0,BB,LBN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.7,0,1
HB-011410,Resort Hotel,1,295,2025,May,19,5,2025-05-05,2,6,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,54.0,0,1
HB-056750,City Hotel,1,199,2024,September,37,12,2024-09-12,1,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,E,E,0,Non Refund,,51.0,0,Transient-Party,106.0,0,0
HB-113449,City Hotel,0,29,2025,June,23,6,2025-06-06,0,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,10.0,,0,Transient,100.0,0,0
HB-067864,City Hotel,1,287,2025,May,19,8,2025-05-08,1,3,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,116.33,0,1
HB-011907,Resort Hotel,1,320,2025,June,23,3,2025-06-03,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,74.25,0,2
HB-116945,City Hotel,0,76,2025,July,30,24,2025-07-24,1,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.67,0,1
HB-007005,Resort Hotel,1,17,2024,July,29,16,2024-07-16,2,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,194.0,0,1
HB-116180,City Hotel,0,277,2025,July,28,13,2025-07-13,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,120.6,0,1
HB-043464,City Hotel,1,74,2023,September,38,18,2023-09-18,0,2,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient-Party,80.0,0,0
HB-109403,City Hotel,0,83,2025,April,15,8,2025-04-08,2,1,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,127.8,0,0
HB-030314,Resort Hotel,0,1,2024,November,47,18,2024-11-18,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,65.0,0,0
HB-038282,Resort Hotel,0,7,2025,July,28,13,2025-07-13,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,F,0,No Deposit,240.0,,0,Transient,145.0,0,0
HB-101037,City Hotel,0,56,2024,November,44,3,2024-11-03,0,3,2,0.0,0,BB,IND,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,86.4,0,0
HB-061035,City Hotel,1,30,2024,November,48,30,2024-11-30,0,3,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,104.0,0,2
HB-091334,City Hotel,0,45,2024,June,25,17,2024-06-17,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,65.0,0,1
HB-109774,City Hotel,0,298,2025,April,16,14,2025-04-14,1,2,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,6.0,,0,Transient-Party,80.0,0,0
HB-111450,City Hotel,0,149,2025,May,19,6,2025-05-06,2,3,2,0.0,0,SC,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,79.0,0,1
HB-058429,City Hotel,1,279,2024,October,41,12,2024-10-12,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,98.0,,0,Transient,110.0,0,0
HB-086888,City Hotel,0,159,2024,April,15,9,2024-04-09,1,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,70.0,0,1
HB-032742,Resort Hotel,0,3,2025,February,5,2,2025-02-02,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,159.0,0,Transient,35.0,0,1
HB-024697,Resort Hotel,0,10,2024,May,22,30,2024-05-30,1,0,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,196.0,,0,Transient,56.0,0,0
HB-032764,Resort Hotel,0,2,2025,February,6,3,2025-02-03,0,2,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient-Party,87.0,1,1
HB-051127,City Hotel,1,121,2024,May,20,14,2024-05-14,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,96.0,0,0
HB-029158,Resort Hotel,0,1,2024,December,49,5,2024-12-05,1,0,2,0.0,0,BB,PRT,Direct,Direct,1,0,1,A,D,1,No Deposit,,,0,Group,66.0,1,1
HB-011392,Resort Hotel,1,5,2025,May,19,5,2025-05-05,0,2,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,112.0,0,1
HB-083333,City Hotel,0,58,2024,January,4,27,2024-01-27,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,87.0,,0,Transient-Party,81.0,0,0
HB-021640,Resort Hotel,0,23,2024,March,10,4,2024-03-04,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,60.0,0,0
HB-055656,City Hotel,1,405,2024,August,33,18,2024-08-18,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-094889,City Hotel,0,158,2024,August,32,8,2024-08-08,1,3,2,0.0,0,BB,POL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,97.75,0,1
HB-111867,City Hotel,0,5,2025,May,20,13,2025-05-13,2,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,145.0,0,1
HB-058450,City Hotel,1,314,2024,October,41,12,2024-10-12,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,68,Transient,75.0,0,0
HB-078318,City Hotel,1,26,2024,July,28,11,2024-07-11,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,1,2,12,A,A,1,No Deposit,,40.0,0,Transient,65.0,0,0
HB-013807,Resort Hotel,0,7,2025,February,8,20,2025-02-20,1,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,94.0,,0,Transient,38.5,1,0
HB-062485,City Hotel,1,38,2025,January,3,14,2025-01-14,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,Non Refund,,67.0,0,Transient,75.0,0,0
HB-110753,City Hotel,0,27,2025,April,18,29,2025-04-29,1,1,2,0.0,0,HB,FRA,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,161.0,0,0
HB-006015,Resort Hotel,1,178,2024,May,21,20,2024-05-20,4,7,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,57.11,0,1
HB-012148,Resort Hotel,1,125,2025,June,24,15,2025-06-15,2,5,2,2.0,0,HB,PRT,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,196.0,0,2
HB-042908,City Hotel,1,28,2023,September,37,11,2023-09-11,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,113.79,0,2
HB-008470,Resort Hotel,1,231,2024,September,40,30,2024-09-30,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,96.0,,0,Transient,57.6,0,0
HB-042756,City Hotel,0,1,2023,September,36,9,2023-09-09,0,3,1,0.0,0,BB,FRA,Corporate,Corporate,0,0,0,A,D,1,No Deposit,,68.0,0,Transient-Party,90.0,0,0
HB-012219,Resort Hotel,1,45,2025,June,25,18,2025-06-18,2,4,2,0.0,0,HB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,203.67,0,0
HB-028666,Resort Hotel,0,383,2024,October,40,6,2024-10-06,0,3,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,C,0,No Deposit,315.0,,0,Transient-Party,54.0,1,0
HB-062195,City Hotel,1,86,2025,January,1,4,2025-01-04,0,3,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,2
HB-114701,City Hotel,0,220,2025,June,25,21,2025-06-21,1,4,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,76.24,0,1
HB-023957,Resort Hotel,0,10,2025,February,6,3,2025-02-03,0,1,2,0.0,0,BB,PRT,Direct,TA/TO,1,0,1,A,D,0,No Deposit,,,0,Transient,40.5,0,2
HB-117299,City Hotel,0,68,2025,July,30,26,2025-07-26,2,5,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,86.0,,0,Transient,153.49,0,0
HB-087107,City Hotel,0,25,2024,April,15,12,2024-04-12,0,2,3,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,7.0,,0,Transient,103.95,0,2
HB-069063,City Hotel,1,181,2025,May,21,25,2025-05-25,0,2,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,130.0,0,0
HB-104212,City Hotel,0,71,2025,January,1,4,2025-01-04,0,4,1,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,48.5,0,1
HB-023597,Resort Hotel,0,62,2024,April,17,25,2024-04-25,1,3,1,0.0,0,FB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,26.0,,0,Transient,53.01,0,0
HB-009679,Resort Hotel,1,131,2024,December,52,24,2024-12-24,2,5,1,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,52.33,0,0
HB-051650,City Hotel,1,0,2024,May,21,24,2024-05-24,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.0,0,0
HB-117222,City Hotel,0,117,2025,July,31,30,2025-07-30,2,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,52.0,,0,Transient,80.1,0,0
HB-049422,City Hotel,1,32,2024,April,15,13,2024-04-13,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,108.3,0,0
HB-095641,City Hotel,0,219,2024,August,34,20,2024-08-20,1,1,2,0.0,0,HB,ITA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,96.0,0,0
HB-073522,City Hotel,1,457,2025,August,35,25,2025-08-25,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,80.0,0,0
HB-017093,Resort Hotel,0,343,2024,September,38,21,2024-09-21,0,4,1,0.0,0,HB,PRT,Corporate,Corporate,1,0,1,A,E,1,No Deposit,183.0,,0,Transient-Party,56.5,0,0
HB-092315,City Hotel,0,154,2024,June,26,29,2024-06-29,1,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient-Party,72.25,0,1
HB-053773,City Hotel,1,5,2024,June,26,29,2024-06-29,0,4,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,134.0,0,0
HB-030753,Resort Hotel,0,128,2024,December,49,3,2024-12-03,0,1,2,0.0,0,HB,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,64.0,0,1
HB-066136,City Hotel,1,89,2025,April,16,14,2025-04-14,2,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,166.5,0,0
HB-002841,Resort Hotel,1,33,2023,November,44,1,2023-11-01,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,94.0,0,Transient,25.0,0,0
HB-052640,City Hotel,1,27,2024,June,23,9,2024-06-09,0,1,2,0.0,0,BB,PRT,Offline TA/TO,Corporate,0,0,0,A,A,0,No Deposit,191.0,,0,Transient-Party,120.0,0,0
HB-084718,City Hotel,0,21,2024,March,9,1,2024-03-01,0,2,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,142.0,0,2
HB-067303,City Hotel,1,157,2025,May,18,1,2025-05-01,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,130.0,0,0
HB-059446,City Hotel,1,199,2024,October,44,28,2024-10-28,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,29.0,,0,Transient-Party,95.0,0,0
HB-084420,City Hotel,0,5,2024,February,8,24,2024-02-24,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,207.0,0,Transient-Party,80.0,0,0
HB-110216,City Hotel,0,91,2025,April,16,20,2025-04-20,1,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-092382,City Hotel,0,62,2024,July,27,2,2024-07-02,2,2,3,0.0,0,BB,IND,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,150.3,0,2
HB-020775,Resort Hotel,0,23,2024,February,6,6,2024-02-06,2,1,2,1.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,15.0,,0,Transient,68.75,0,2
HB-043062,City Hotel,0,35,2023,September,37,14,2023-09-14,1,0,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,86.4,0,2
HB-110620,City Hotel,0,7,2025,April,18,29,2025-04-29,0,1,2,0.0,0,SC,EST,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,1
HB-071996,City Hotel,1,175,2025,July,29,17,2025-07-17,1,2,3,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,152.1,0,0
HB-011180,Resort Hotel,0,0,2025,April,17,27,2025-04-27,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,76.0,0,2
HB-014238,Resort Hotel,0,1,2023,December,49,10,2023-12-10,0,1,1,0.0,0,BB,,Corporate,Corporate,0,0,0,A,A,1,No Deposit,,291.0,0,Transient,35.0,0,0
HB-093880,City Hotel,0,190,2024,July,30,24,2024-07-24,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.95,1,1
HB-050418,City Hotel,1,45,2024,April,18,30,2024-04-30,1,1,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,159.3,0,0
HB-089388,City Hotel,0,198,2024,May,21,20,2024-05-20,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,98,Transient-Party,65.0,0,0
HB-082152,City Hotel,1,99,2024,February,8,19,2024-02-19,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,1,0,A,A,0,No Deposit,,67.0,0,Transient-Party,80.0,0,0
HB-028100,Resort Hotel,0,48,2024,September,38,18,2024-09-18,2,0,2,0.0,0,BB,LVA,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,,0,Transient,116.0,1,2
HB-053605,City Hotel,1,163,2024,June,26,25,2024-06-25,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,96.0,0,0
HB-107645,City Hotel,0,211,2025,March,11,13,2025-03-13,1,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,85.5,0,1
HB-037920,Resort Hotel,0,121,2025,June,26,27,2025-06-27,1,5,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,166.33,1,0
HB-045024,City Hotel,1,102,2023,October,42,16,2023-10-16,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-015853,Resort Hotel,0,158,2023,August,31,4,2023-08-04,0,1,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,112.0,0,0
HB-064209,City Hotel,1,91,2025,March,9,2,2025-03-02,0,3,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.0,0,1
HB-106907,City Hotel,0,17,2025,March,10,3,2025-03-03,0,2,1,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,60.06,0,0
HB-073730,City Hotel,1,258,2023,July,26,2,2023-07-02,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-037945,Resort Hotel,0,283,2025,June,26,27,2025-06-27,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,87.79,0,1
HB-054032,City Hotel,1,157,2024,July,27,6,2024-07-06,0,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.95,0,0
HB-103714,City Hotel,0,66,2024,December,52,23,2024-12-23,2,5,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,63.75,0,1
HB-060900,City Hotel,1,308,2024,November,48,25,2024-11-25,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,52.0,0,0
HB-085825,City Hotel,0,3,2024,March,12,21,2024-03-21,1,0,1,0.0,0,BB,ESP,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,148.0,0,Transient,79.0,0,0
HB-062016,City Hotel,1,311,2024,December,1,30,2024-12-30,0,2,2,1.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,112.5,0,1
HB-050262,City Hotel,1,160,2024,April,17,27,2024-04-27,2,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,147.0,,71,Transient,90.0,0,0
HB-064803,City Hotel,1,52,2025,March,11,16,2025-03-16,0,3,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,0
HB-091264,City Hotel,0,0,2024,June,25,18,2024-06-18,0,1,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,129.0,0,2
HB-084191,City Hotel,0,16,2024,February,7,17,2024-02-17,0,4,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,109.0,0,2
HB-011036,Resort Hotel,1,73,2025,April,16,15,2025-04-15,2,1,1,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,68.33,0,0
HB-020396,Resort Hotel,0,4,2024,January,4,22,2024-01-22,2,3,1,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,39.0,0,1
HB-084222,City Hotel,0,7,2024,February,8,20,2024-02-20,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.0,0,1
HB-002107,Resort Hotel,0,115,2023,October,39,1,2023-10-01,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,147.0,,0,Transient,36.74,0,1
HB-000856,Resort Hotel,1,124,2023,August,31,1,2023-08-01,2,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,120.6,0,1
HB-045339,City Hotel,0,90,2023,October,43,25,2023-10-25,2,4,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,89.25,0,0
HB-115649,City Hotel,0,162,2025,July,27,5,2025-07-05,0,4,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,152.1,0,0
HB-039760,Resort Hotel,0,64,2025,August,34,23,2025-08-23,0,4,2,0.0,0,BB,USA,Direct,Direct,0,0,0,E,E,2,No Deposit,250.0,,0,Transient,265.0,0,1
HB-058193,City Hotel,1,338,2024,October,41,7,2024-10-07,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,68,Transient-Party,80.0,0,0
HB-075338,City Hotel,1,311,2023,August,34,24,2023-08-24,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-002176,Resort Hotel,1,34,2023,October,40,4,2023-10-04,2,2,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,117.0,0,0
HB-076133,City Hotel,1,364,2023,October,42,16,2023-10-16,0,2,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,1,Non Refund,6.0,,0,Transient-Party,80.0,0,0
HB-047207,City Hotel,0,37,2024,February,7,12,2024-02-12,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient,71.55,0,0
HB-034831,Resort Hotel,0,48,2025,March,14,31,2025-03-31,2,5,2,0.0,0,HB,BEL,Online TA,TA/TO,0,0,0,E,F,0,No Deposit,240.0,,0,Transient,120.57,0,2
HB-047706,City Hotel,1,50,2024,February,9,29,2024-02-29,1,0,2,0.0,0,SC,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,0
HB-051260,City Hotel,1,286,2024,May,20,17,2024-05-17,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,75,Transient,65.0,0,0
HB-021614,Resort Hotel,0,1,2024,March,10,4,2024-03-04,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,74.0,1,0
HB-060231,City Hotel,1,626,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-007373,Resort Hotel,1,221,2024,August,32,6,2024-08-06,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,126.0,0,1
HB-043875,City Hotel,1,87,2023,September,39,25,2023-09-25,2,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-080008,City Hotel,1,2,2023,November,45,9,2023-11-09,3,8,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,95.81,0,0
HB-054861,City Hotel,1,386,2024,July,30,28,2024-07-28,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-026936,Resort Hotel,0,131,2024,August,32,8,2024-08-08,2,5,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,D,D,1,No Deposit,,,0,Transient-Party,180.1,0,1
HB-051977,City Hotel,1,64,2024,May,22,27,2024-05-27,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,140.4,0,0
HB-002528,Resort Hotel,0,75,2023,October,42,20,2023-10-20,2,7,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,40.0,,0,Contract,54.4,0,0
HB-084660,City Hotel,0,26,2024,February,9,28,2024-02-28,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,87.0,0,0
HB-028248,Resort Hotel,0,37,2024,September,39,25,2024-09-25,1,0,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient-Party,110.0,0,1
HB-016084,Resort Hotel,0,72,2023,August,32,10,2023-08-10,1,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,26.0,,0,Transient,132.05,0,0
HB-051497,City Hotel,1,22,2024,May,21,20,2024-05-20,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,34.0,,0,Transient,140.0,0,0
HB-095167,City Hotel,0,119,2024,August,33,12,2024-08-12,2,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.3,0,1
HB-095324,City Hotel,0,202,2024,August,33,15,2024-08-15,1,2,2,1.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,115.5,0,2
HB-116182,City Hotel,0,215,2025,July,28,13,2025-07-13,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,99.9,0,1
HB-037175,Resort Hotel,0,113,2025,June,23,2,2025-06-02,2,6,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,145.0,0,1
HB-068985,City Hotel,1,73,2025,May,21,24,2025-05-24,0,3,1,0.0,0,BB,MAC,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,153.0,0,0
HB-099428,City Hotel,0,180,2024,October,41,10,2024-10-10,1,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,234.0,,0,Transient-Party,120.0,0,1
HB-005092,Resort Hotel,1,232,2024,April,16,16,2024-04-16,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,52.2,0,1
HB-076080,City Hotel,1,364,2023,October,42,16,2023-10-16,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-076932,City Hotel,1,342,2023,September,38,24,2023-09-24,2,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-047942,City Hotel,1,61,2024,March,10,10,2024-03-10,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,87.3,0,0
HB-030365,Resort Hotel,0,4,2024,November,47,18,2024-11-18,0,2,2,0.0,0,BB,IRL,Groups,Direct,0,0,0,A,A,0,Refundable,,,0,Transient-Party,34.0,0,0
HB-112808,City Hotel,0,227,2025,May,21,25,2025-05-25,1,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.1,0,0
HB-070802,City Hotel,1,59,2025,June,26,23,2025-06-23,0,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.0,0,0
HB-014262,Resort Hotel,0,11,2023,December,48,1,2023-12-01,0,1,1,0.0,0,BB,,Corporate,Corporate,0,1,3,A,E,0,No Deposit,,292.0,0,Transient,35.0,0,0
HB-070592,City Hotel,1,210,2025,June,25,19,2025-06-19,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,154.0,,0,Transient,130.0,0,0
HB-114592,City Hotel,0,56,2025,June,26,23,2025-06-23,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.0,0,3
HB-027849,Resort Hotel,0,245,2024,September,36,6,2024-09-06,2,5,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,87.0,0,2
HB-109227,City Hotel,0,127,2025,April,15,7,2025-04-07,0,2,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,K,0,No Deposit,9.0,,0,Transient,130.5,0,2
HB-042283,City Hotel,0,4,2023,September,36,4,2023-09-04,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,124.0,1,1
HB-037310,Resort Hotel,0,1,2025,June,24,12,2025-06-12,1,1,1,0.0,0,BB,NLD,Direct,Direct,0,0,0,A,A,1,No Deposit,250.0,,0,Transient,149.0,1,0
HB-059365,City Hotel,1,110,2024,October,43,27,2024-10-27,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,104.4,0,1
HB-010828,Resort Hotel,1,47,2025,April,15,7,2025-04-07,1,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,103.33,0,2
HB-074203,City Hotel,1,363,2023,October,41,15,2023-10-15,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-055356,City Hotel,1,398,2024,August,32,11,2024-08-11,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-059078,City Hotel,1,457,2024,October,43,21,2024-10-21,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,391,Transient,65.0,0,0
HB-037821,Resort Hotel,0,274,2025,June,25,16,2025-06-16,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,58.7,0,1
HB-113552,City Hotel,0,20,2025,June,23,5,2025-06-05,1,3,2,0.0,0,BB,AUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,116.0,0,1
HB-112125,City Hotel,0,5,2025,May,20,18,2025-05-18,0,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,170.0,0,0
HB-059471,City Hotel,1,247,2024,October,44,28,2024-10-28,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,110.0,0,0
HB-015060,Resort Hotel,0,1,2024,October,40,5,2024-10-05,0,1,1,0.0,0,BB,ESP,Online TA,TA/TO,1,0,1,A,A,0,No Deposit,339.0,,0,Transient,68.8,0,0
HB-060194,City Hotel,1,277,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-043606,City Hotel,1,19,2023,September,38,21,2023-09-21,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,20.0,,0,Transient-Party,48.0,0,0
HB-033090,Resort Hotel,0,1,2025,February,7,15,2025-02-15,0,1,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,,,0,Transient,105.0,1,1
HB-003174,Resort Hotel,0,36,2023,November,47,20,2023-11-20,0,2,2,0.0,0,FB,ESP,Groups,TA/TO,0,0,0,A,C,0,No Deposit,38.0,,0,Transient-Party,64.0,0,0
HB-026427,Resort Hotel,0,12,2024,July,31,30,2024-07-30,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,221.0,1,1
HB-033367,Resort Hotel,0,15,2025,February,7,14,2025-02-14,2,5,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,69.71,0,2
HB-035164,Resort Hotel,0,72,2025,April,15,8,2025-04-08,2,5,1,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,D,D,0,No Deposit,298.0,,0,Transient-Party,68.0,0,0
HB-036655,Resort Hotel,0,99,2025,May,20,18,2025-05-18,2,5,2,0.0,0,BB,ROU,Direct,Direct,0,0,0,A,A,1,No Deposit,250.0,,0,Transient,90.0,0,1
HB-022950,Resort Hotel,0,33,2024,April,15,10,2024-04-10,1,0,1,0.0,0,BB,PRT,Corporate,Direct,0,0,0,A,A,0,No Deposit,,263.0,0,Transient-Party,42.0,0,0
HB-019236,Resort Hotel,1,92,2024,February,9,26,2024-02-26,1,2,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,134.0,,0,Transient,79.0,0,0
HB-056150,City Hotel,1,28,2024,August,35,30,2024-08-30,0,4,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.05,0,0
HB-056829,City Hotel,1,433,2024,September,37,15,2024-09-15,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-028787,Resort Hotel,0,0,2024,October,41,10,2024-10-10,1,0,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,65.0,0,1
HB-056663,City Hotel,1,198,2024,September,37,9,2024-09-09,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,120.0,0,0
HB-061643,City Hotel,1,36,2024,December,51,21,2024-12-21,1,4,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.4,0,2
HB-072680,City Hotel,1,62,2025,August,31,3,2025-08-03,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,150.0,0,0
HB-092661,City Hotel,0,31,2024,July,27,7,2024-07-07,0,3,2,1.0,0,BB,BRA,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,167.95,1,1
HB-038231,Resort Hotel,0,0,2025,July,28,11,2025-07-11,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient-Party,135.0,0,1
HB-108235,City Hotel,0,0,2025,March,13,24,2025-03-24,0,0,0,0.0,0,BB,PRT,Online TA,TA/TO,1,0,0,A,G,0,No Deposit,86.0,,0,Transient,0.0,0,0
HB-094945,City Hotel,0,274,2024,August,32,9,2024-08-09,0,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,107.0,0,2
HB-031413,Resort Hotel,0,155,2024,December,51,21,2024-12-21,2,5,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,E,E,2,No Deposit,250.0,,0,Transient,66.22,1,1
HB-049247,City Hotel,0,94,2024,April,15,8,2024-04-08,2,2,2,1.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,D,2,No Deposit,9.0,,0,Transient,96.13,0,1
HB-079427,City Hotel,1,137,2024,January,4,27,2024-01-27,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,29.0,,45,Transient,70.0,0,0
HB-008820,Resort Hotel,1,27,2024,October,42,15,2024-10-15,2,5,3,1.0,0,BB,IRL,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,145.71,0,0
HB-111021,City Hotel,0,67,2025,May,18,2,2025-05-02,0,3,2,0.0,0,BB,DNK,Groups,Corporate,0,0,0,A,A,0,No Deposit,,409.0,0,Transient-Party,120.0,0,0
HB-028317,Resort Hotel,0,16,2024,September,38,22,2024-09-22,2,5,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,131.43,1,2
HB-075870,City Hotel,1,351,2023,October,40,3,2023-10-03,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-019125,Resort Hotel,0,11,2023,December,49,7,2023-12-07,1,0,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,32.0,1,0
HB-096074,City Hotel,0,256,2024,August,35,26,2024-08-26,0,2,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,72.25,0,1
HB-092823,City Hotel,0,0,2024,July,28,12,2024-07-12,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,1
HB-012381,Resort Hotel,1,48,2025,June,26,26,2025-06-26,1,4,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,D,D,0,No Deposit,531.0,,0,Transient,76.0,0,0
HB-034643,Resort Hotel,0,157,2025,March,13,25,2025-03-25,2,5,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,177.0,,0,Transient,54.4,0,0
HB-037668,Resort Hotel,0,4,2025,June,26,23,2025-06-23,0,2,2,1.0,1,Undefined,ESP,Direct,Direct,0,0,0,C,C,2,No Deposit,250.0,,0,Transient,265.25,1,2
HB-064939,City Hotel,1,136,2025,March,12,21,2025-03-21,0,3,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.6,0,1
HB-081895,City Hotel,1,178,2024,April,17,28,2024-04-28,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,46,Transient,120.0,0,0
HB-024291,Resort Hotel,0,0,2024,May,20,16,2024-05-16,1,0,1,0.0,0,BB,GBR,Direct,Direct,1,0,0,A,A,1,No Deposit,,,0,Transient,70.0,0,0
HB-055748,City Hotel,1,133,2024,August,34,20,2024-08-20,0,1,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.5,0,0
HB-010339,Resort Hotel,1,49,2025,February,9,28,2025-02-28,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,C,1,Non Refund,332.0,,0,Transient,35.0,0,0
HB-083443,City Hotel,0,1,2024,February,5,1,2024-02-01,1,0,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,106.0,0,1
HB-051543,City Hotel,1,95,2024,May,21,21,2024-05-21,0,1,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,159.3,0,0
HB-115426,City Hotel,0,224,2025,July,27,2,2025-07-02,2,2,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,160.95,0,0
HB-103709,City Hotel,0,25,2024,December,52,27,2024-12-27,0,3,3,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,K,2,No Deposit,220.0,,0,Transient-Party,60.0,0,1
HB-071694,City Hotel,1,121,2025,July,28,10,2025-07-10,1,2,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,0
HB-012887,Resort Hotel,1,151,2025,July,30,22,2025-07-22,2,5,2,2.0,0,BB,ROU,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,265.0,0,0
HB-010900,Resort Hotel,1,124,2025,April,15,9,2025-04-09,2,5,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,492.0,,0,Transient,80.0,0,0
HB-113872,City Hotel,0,10,2025,June,24,11,2025-06-11,2,0,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,190.0,0,0
HB-011000,Resort Hotel,1,98,2025,April,16,14,2025-04-14,1,2,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,106.67,0,0
HB-085301,City Hotel,0,24,2024,March,10,10,2024-03-10,0,3,2,0.0,0,BB,CZE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.33,0,0
HB-045638,City Hotel,1,140,2023,November,46,18,2023-11-18,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,29.0,,87,Transient-Party,75.0,0,0
HB-050332,City Hotel,1,443,2024,April,18,29,2024-04-29,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,65.0,0,0
HB-050301,City Hotel,1,24,2024,April,17,28,2024-04-28,0,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,9.0,,0,Transient,144.5,0,0
HB-103176,City Hotel,0,25,2024,December,50,10,2024-12-10,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.89,0,2
HB-047928,City Hotel,1,51,2024,March,10,9,2024-03-09,2,6,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,63.75,0,0
HB-002090,Resort Hotel,0,44,2023,October,39,1,2023-10-01,0,3,2,1.0,0,HB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,118.5,0,2
HB-016712,Resort Hotel,0,0,2023,September,36,7,2023-09-07,1,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,C,0,No Deposit,,,0,Transient,131.0,1,0
HB-035504,Resort Hotel,0,108,2025,April,16,20,2025-04-20,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,93.75,0,2
HB-015952,Resort Hotel,0,71,2023,August,31,1,2023-08-01,2,6,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,196.0,,0,Transient,0.0,0,0
HB-023956,Resort Hotel,0,159,2024,May,18,5,2024-05-05,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,52.2,1,2
HB-060351,City Hotel,1,277,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-012255,Resort Hotel,1,87,2025,June,25,20,2025-06-20,0,4,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,160.0,0,0
HB-065094,City Hotel,1,77,2025,March,13,24,2025-03-24,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,106.2,0,0
HB-097920,City Hotel,0,159,2024,September,38,19,2024-09-19,1,2,2,0.0,0,BB,ZAF,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,144.0,0,0
HB-097388,City Hotel,0,1,2024,September,37,15,2024-09-15,0,1,1,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,159.0,0,1
HB-008414,Resort Hotel,1,339,2024,September,39,26,2024-09-26,3,6,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,15.0,,0,Transient,80.0,0,0
HB-094692,City Hotel,0,183,2024,August,31,3,2024-08-03,1,4,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient-Party,112.0,0,1
HB-040036,Resort Hotel,0,21,2025,August,35,31,2025-08-31,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,40.0,,0,Contract,101.7,0,2
HB-095559,City Hotel,0,5,2024,August,34,20,2024-08-20,0,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,130.0,0,1
HB-063191,City Hotel,1,37,2025,February,5,1,2025-02-01,2,4,3,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,9.0,,0,Transient,115.6,0,1
HB-074186,City Hotel,1,356,2023,October,40,8,2023-10-08,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-023495,Resort Hotel,0,7,2024,April,17,25,2024-04-25,1,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,65.0,0,1
HB-027317,Resort Hotel,0,204,2024,August,33,12,2024-08-12,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,2.0,,0,Contract,90.1,0,1
HB-002688,Resort Hotel,0,62,2023,October,43,25,2023-10-25,2,4,1,1.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,314.0,,0,Contract,44.8,0,0
HB-053725,City Hotel,1,2,2024,June,26,28,2024-06-28,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,139.0,0,0
HB-067511,City Hotel,1,143,2025,May,18,4,2025-05-04,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,56.0,,0,Transient,110.0,0,0
HB-106732,City Hotel,0,10,2025,February,9,27,2025-02-27,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,354.0,,0,Transient,89.33,0,0
HB-009717,Resort Hotel,1,335,2024,December,52,28,2024-12-28,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,64.0,0,1
HB-104472,City Hotel,0,10,2025,January,2,12,2025-01-12,0,2,1,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,88.0,0,1
HB-117432,City Hotel,0,2,2025,August,31,3,2025-08-03,0,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,509.0,,0,Transient-Party,166.0,0,0
HB-076251,City Hotel,1,221,2023,October,40,3,2023-10-03,2,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,86.0,0,0
HB-013518,Resort Hotel,1,19,2025,August,34,18,2025-08-18,0,2,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,262.0,0,0
HB-080724,City Hotel,0,67,2023,November,47,21,2023-11-21,1,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,79.2,0,1
HB-109269,City Hotel,0,75,2025,April,14,5,2025-04-05,0,4,1,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,85.0,0,0
HB-030957,Resort Hotel,0,1,2025,January,4,26,2025-01-26,0,2,2,0.0,0,BB,PRT,Direct,Direct,1,0,1,A,D,0,No Deposit,250.0,,0,Transient,52.0,1,1
HB-106280,City Hotel,0,48,2025,February,8,22,2025-02-22,0,2,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,65.0,0,1
HB-019999,Resort Hotel,0,5,2024,January,2,11,2024-01-11,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,274.0,0,Transient,38.0,0,0
HB-046960,City Hotel,1,35,2024,January,5,29,2024-01-29,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,82.45,0,1
HB-093570,City Hotel,0,292,2024,July,29,21,2024-07-21,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,0
HB-069255,City Hotel,1,132,2025,May,22,28,2025-05-28,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,28.0,,0,Transient,99.0,0,0
HB-008690,Resort Hotel,1,92,2024,October,41,9,2024-10-09,2,2,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,106.5,0,0
HB-107593,City Hotel,0,91,2025,March,11,11,2025-03-11,2,2,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,91.8,0,3
HB-096275,City Hotel,0,4,2024,August,35,30,2024-08-30,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,129.0,0,0
HB-031928,Resort Hotel,0,81,2025,January,3,16,2025-01-16,1,2,1,0.0,0,BB,PRT,Direct,Direct,0,0,1,A,A,0,No Deposit,,,0,Transient,30.0,0,1
HB-045106,City Hotel,0,102,2023,October,42,16,2023-10-16,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,E,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-049165,City Hotel,1,274,2024,April,14,7,2024-04-07,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-101514,City Hotel,0,9,2024,November,46,11,2024-11-11,0,2,2,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,0.0,1,3
HB-080952,City Hotel,0,11,2023,November,47,20,2023-11-20,3,7,1,0.0,0,BB,AGO,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,113.0,0,1
HB-060698,City Hotel,1,58,2024,November,47,18,2024-11-18,1,2,1,0.0,0,BB,LUX,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,86.4,0,3
HB-118841,City Hotel,0,70,2025,August,34,24,2025-08-24,0,2,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,199.0,0,2
HB-066392,City Hotel,1,162,2025,April,16,19,2025-04-19,0,1,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,3
HB-036268,Resort Hotel,0,156,2025,May,19,8,2025-05-08,2,5,2,0.0,0,HB,IRL,Groups,TA/TO,0,0,0,A,A,3,No Deposit,434.0,,0,Transient-Party,81.71,0,1
HB-004331,Resort Hotel,1,162,2024,March,10,4,2024-03-04,6,15,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,96.0,,0,Transient,82.0,0,0
HB-041218,City Hotel,1,0,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-104924,City Hotel,0,34,2025,January,4,24,2025-01-24,0,2,1,0.0,0,SC,ITA,Online TA,GDS,0,0,0,A,A,0,No Deposit,195.0,,0,Transient,69.5,0,1
HB-078099,City Hotel,0,19,2023,September,39,30,2023-09-30,0,4,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,7.0,,0,Transient,91.47,0,2
HB-114706,City Hotel,0,8,2025,June,26,25,2025-06-25,1,0,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,200.0,0,1
HB-070007,City Hotel,1,94,2025,June,23,8,2025-06-08,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,153.0,0,0
HB-004751,Resort Hotel,0,169,2024,March,13,31,2024-03-31,0,3,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,D,1,Refundable,,223.0,0,Transient-Party,66.0,0,0
HB-025205,Resort Hotel,0,215,2024,June,24,11,2024-06-11,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,G,0,No Deposit,240.0,,0,Transient,99.0,0,2
HB-084541,City Hotel,0,3,2024,February,8,25,2024-02-25,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,81.0,0,0
HB-036942,Resort Hotel,0,137,2025,May,22,30,2025-05-30,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient-Party,108.33,0,0
HB-115971,City Hotel,0,203,2025,July,28,9,2025-07-09,2,2,2,1.0,0,BB,FRA,Direct,Direct,0,0,0,D,D,2,No Deposit,14.0,,0,Transient,126.6,0,2
HB-037037,Resort Hotel,0,131,2025,May,22,29,2025-05-29,2,5,1,0.0,0,HB,CHE,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,161.29,0,2
HB-032508,Resort Hotel,0,15,2025,January,5,28,2025-01-28,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,250.0,,0,Transient,44.0,0,1
HB-079153,City Hotel,0,5,2023,October,42,19,2023-10-19,1,2,2,0.0,0,BB,POL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,112.0,,0,Transient-Party,90.0,0,0
HB-040536,City Hotel,0,1,2023,July,30,28,2023-07-28,0,2,1,0.0,0,BB,PRT,Corporate,Direct,0,0,0,A,A,3,No Deposit,,40.0,0,Transient,65.0,0,0
HB-034347,Resort Hotel,0,15,2025,March,12,19,2025-03-19,2,0,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,,0,Transient,90.0,0,2
HB-070533,City Hotel,1,165,2025,June,25,17,2025-06-17,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,262.0,,0,Transient,89.1,0,0
HB-084938,City Hotel,0,38,2024,March,9,3,2024-03-03,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,87.71,0,1
HB-054103,City Hotel,1,98,2024,July,27,7,2024-07-07,0,1,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.3,0,1
HB-112005,City Hotel,0,31,2025,May,20,14,2025-05-14,2,3,1,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,0,No Deposit,459.0,,0,Transient-Party,130.0,0,0
HB-054269,City Hotel,1,49,2024,July,28,11,2024-07-11,1,0,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.15,0,0
HB-038065,Resort Hotel,0,270,2025,July,27,1,2025-07-01,2,6,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,184.0,,0,Transient,103.75,0,0
HB-114664,City Hotel,0,115,2025,June,26,23,2025-06-23,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,3,No Deposit,9.0,,0,Transient,108.0,0,2
HB-066376,City Hotel,1,79,2025,April,16,18,2025-04-18,0,3,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,171.0,0,0
HB-059516,City Hotel,1,189,2024,October,44,28,2024-10-28,1,2,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,109.8,0,0
HB-003209,Resort Hotel,0,44,2023,November,47,21,2023-11-21,0,1,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,E,3,No Deposit,240.0,,0,Transient,73.5,1,3
HB-090713,City Hotel,0,118,2024,June,23,6,2024-06-06,1,3,1,0.0,0,BB,HUN,Offline TA/TO,Corporate,0,0,0,A,A,1,No Deposit,191.0,,0,Transient-Party,110.0,0,0
HB-004971,Resort Hotel,1,212,2024,April,15,11,2024-04-11,2,5,2,0.0,0,HB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,273.0,,0,Transient,67.05,0,0
HB-018164,Resort Hotel,0,0,2023,November,44,5,2023-11-05,1,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,56.0,0,0
HB-061577,City Hotel,1,9,2024,December,51,16,2024-12-16,1,2,2,0.0,0,SC,IDN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,78.0,0,0
HB-084883,City Hotel,0,15,2024,March,9,3,2024-03-03,0,3,2,2.0,0,HB,MAR,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,9.0,,0,Transient,242.33,0,2
HB-098070,City Hotel,0,296,2024,September,38,21,2024-09-21,0,4,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,26.0,,0,Transient-Party,117.0,0,1
HB-012691,Resort Hotel,1,20,2025,July,28,12,2025-07-12,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,200.0,0,2
HB-020566,Resort Hotel,0,0,2024,February,5,2,2024-02-02,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,1,No Deposit,,,0,Transient,58.0,0,0
HB-107649,City Hotel,0,12,2025,March,11,15,2025-03-15,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,103.0,,4,Transient-Party,109.0,1,0
HB-066087,City Hotel,1,53,2025,April,16,14,2025-04-14,0,1,3,0.0,0,HB,SWE,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,196.2,0,0
HB-062529,City Hotel,1,38,2025,January,3,14,2025-01-14,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,Non Refund,,67.0,0,Transient,75.0,0,0
HB-016966,Resort Hotel,0,258,2023,September,37,17,2023-09-17,0,2,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,3,No Deposit,245.0,,0,Transient-Party,59.85,0,0
HB-022966,Resort Hotel,0,0,2024,April,15,10,2024-04-10,1,0,2,0.0,0,BB,CN,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,71.0,1,0
HB-034792,Resort Hotel,0,89,2025,April,14,3,2025-04-03,1,1,2,2.0,0,HB,FRA,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,194.0,0,0
HB-057473,City Hotel,1,53,2024,September,39,26,2024-09-26,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,105.0,0,0
HB-042786,City Hotel,1,44,2023,September,36,10,2023-09-10,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,41.0,,0,Transient,126.0,0,0
HB-032726,Resort Hotel,0,41,2025,January,4,23,2025-01-23,3,8,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,43.0,0,2
HB-076360,City Hotel,0,273,2023,July,29,17,2023-07-17,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-042677,City Hotel,0,85,2023,September,36,9,2023-09-09,0,2,1,0.0,0,BB,FRA,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,68.0,0,Transient-Party,90.0,0,0
HB-106811,City Hotel,0,9,2025,February,9,26,2025-02-26,2,3,1,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,53.04,0,0
HB-018107,Resort Hotel,0,1,2024,February,6,11,2024-02-11,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,1,0,1,A,D,0,No Deposit,339.0,,0,Transient,25.0,1,0
HB-104798,City Hotel,0,58,2025,January,3,15,2025-01-15,3,5,2,0.0,0,BB,CYP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,25,Transient-Party,75.0,0,2
HB-011235,Resort Hotel,1,172,2025,April,18,29,2025-04-29,2,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,314.0,,0,Transient,97.71,0,0
HB-040765,City Hotel,0,36,2023,August,32,7,2023-08-07,0,2,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-102998,City Hotel,0,209,2024,December,49,8,2024-12-08,0,3,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,81.9,0,1
HB-014974,Resort Hotel,1,166,2023,July,28,15,2023-07-15,0,2,2,0.0,0,FB,PRT,Groups,TA/TO,0,24,0,A,A,0,Non Refund,,,0,Transient,121.5,0,0
HB-032438,Resort Hotel,0,0,2025,January,4,26,2025-01-26,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,40.0,0,0
HB-011500,Resort Hotel,1,116,2025,May,19,11,2025-05-11,0,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient-Party,100.0,0,0
HB-022440,Resort Hotel,0,3,2024,March,12,23,2024-03-23,0,2,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,185.5,1,2
HB-016623,Resort Hotel,0,74,2023,August,34,26,2023-08-26,2,7,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,134.0,0,0
HB-068035,City Hotel,1,130,2025,May,19,11,2025-05-11,1,3,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.0,0,0
HB-059732,City Hotel,1,166,2024,November,44,1,2024-11-01,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,110.0,0,0
HB-104604,City Hotel,0,34,2025,January,3,18,2025-01-18,0,1,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,D,0,No Deposit,19.0,,0,Transient-Party,75.0,0,0
HB-053488,City Hotel,1,19,2024,June,25,22,2024-06-22,0,2,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,215.0,,0,Transient-Party,100.0,0,0
HB-002779,Resort Hotel,0,0,2023,October,44,31,2023-10-31,0,1,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,49.0,0,0
HB-098805,City Hotel,0,1,2024,October,40,4,2024-10-04,0,1,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,204.0,0,0
HB-110375,City Hotel,0,310,2025,April,17,23,2025-04-23,2,2,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,83.75,0,1
HB-073879,City Hotel,1,321,2023,September,35,3,2023-09-03,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-077705,City Hotel,1,43,2023,October,43,23,2023-10-23,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,2.0,,0,Transient-Party,0.0,0,0
HB-086334,City Hotel,0,75,2024,March,13,28,2024-03-28,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,91.45,1,0
HB-028272,Resort Hotel,0,285,2024,September,38,20,2024-09-20,2,5,2,0.0,0,BB,IRL,Groups,TA/TO,0,0,0,D,E,1,No Deposit,96.0,,0,Transient-Party,78.0,0,3
HB-068667,City Hotel,1,72,2025,May,21,19,2025-05-19,1,2,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,144.0,0,0
HB-037518,Resort Hotel,0,136,2025,June,25,17,2025-06-17,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,123.8,1,0
HB-004546,Resort Hotel,1,152,2024,March,12,24,2024-03-24,0,3,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,42.3,0,2
HB-018759,Resort Hotel,0,15,2023,November,48,27,2023-11-27,0,2,2,0.0,0,HB,PRT,Corporate,Direct,0,0,0,D,D,0,No Deposit,,346.0,0,Transient-Party,66.0,1,0
HB-015024,Resort Hotel,0,7,2024,November,44,3,2024-11-03,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,4,A,D,0,No Deposit,94.0,,0,Transient,27.0,1,0
HB-115518,City Hotel,0,17,2025,July,27,4,2025-07-04,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,179.0,0,2
HB-000099,Resort Hotel,0,101,2023,July,27,3,2023-07-03,2,5,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,99.3,1,2
HB-043049,City Hotel,0,13,2023,September,37,13,2023-09-13,2,3,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,1,No Deposit,,40.0,0,Transient,65.0,0,0
HB-059647,City Hotel,1,197,2024,October,44,30,2024-10-30,2,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,82.5,0,0
HB-100807,City Hotel,0,241,2024,October,44,29,2024-10-29,2,2,0,2.0,0,BB,SWE,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient-Party,81.76,0,1
HB-051471,City Hotel,1,211,2024,May,21,20,2024-05-20,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,111,Transient,100.0,0,0
HB-109287,City Hotel,0,53,2025,April,15,7,2025-04-07,0,2,3,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,171.0,0,0
HB-050980,City Hotel,1,58,2024,May,19,12,2024-05-12,1,3,1,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.65,0,0
HB-065214,City Hotel,1,66,2025,March,13,28,2025-03-28,0,5,2,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.84,0,0
HB-028353,Resort Hotel,0,121,2024,September,39,25,2024-09-25,2,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,241.0,,0,Transient,98.75,0,1
HB-080848,City Hotel,0,8,2023,November,47,26,2023-11-26,0,1,1,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,62.37,0,0
HB-081390,City Hotel,0,6,2025,January,1,3,2025-01-03,0,1,1,0.0,0,BB,FRA,Corporate,Corporate,1,1,7,A,A,0,No Deposit,,91.0,0,Transient,80.0,0,3
HB-057163,City Hotel,1,141,2024,September,38,19,2024-09-19,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,129.86,0,3
HB-061852,City Hotel,1,247,2024,December,52,27,2024-12-27,1,5,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,110.78,0,0
HB-025861,Resort Hotel,0,2,2024,July,28,12,2024-07-12,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,1,No Deposit,,,0,Transient,171.0,1,1
HB-111911,City Hotel,0,179,2025,May,20,14,2025-05-14,2,2,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,116.33,0,1
HB-067189,City Hotel,1,78,2025,April,18,29,2025-04-29,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient,90.0,0,0
HB-014873,Resort Hotel,1,187,2023,August,31,4,2023-08-04,0,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,240.0,,0,Transient,134.0,0,1
HB-108854,City Hotel,0,86,2025,March,14,31,2025-03-31,1,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,101.4,1,0
HB-115672,City Hotel,0,192,2025,July,27,6,2025-07-06,0,3,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,89.1,0,0
HB-042940,City Hotel,0,0,2023,September,37,11,2023-09-11,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,124.0,0,1
HB-071206,City Hotel,1,145,2025,June,26,29,2025-06-29,1,3,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,121.05,0,0
HB-072365,City Hotel,1,76,2025,July,30,27,2025-07-27,0,2,2,0.0,0,SC,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.0,0,1
HB-095959,City Hotel,0,190,2024,August,34,22,2024-08-22,1,3,2,0.0,0,BB,EST,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,109.25,0,1
HB-088837,City Hotel,0,3,2025,January,1,5,2025-01-05,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,1,0,7,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,1
HB-097861,City Hotel,0,27,2024,September,38,20,2024-09-20,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,288.0,,0,Transient-Party,95.0,0,0
HB-013734,Resort Hotel,1,40,2025,August,35,28,2025-08-28,1,2,1,0.0,0,BB,LBN,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,230.0,0,1
HB-079896,City Hotel,0,1,2023,November,44,3,2023-11-03,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,80.0,0,0
HB-050465,City Hotel,0,118,2024,May,18,1,2024-05-01,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,107.95,0,0
HB-059868,City Hotel,1,304,2024,November,44,3,2024-11-03,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,89.0,0,0
HB-061961,City Hotel,1,151,2024,December,52,29,2024-12-29,0,3,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,143.28,0,1
HB-025442,Resort Hotel,0,124,2024,June,25,21,2024-06-21,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,122.86,0,2
HB-021000,Resort Hotel,0,1,2024,February,7,13,2024-02-13,1,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,240.0,,0,Transient,66.0,0,0
HB-026665,Resort Hotel,0,4,2024,August,31,4,2024-08-04,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,232.33,0,0
HB-111915,City Hotel,0,179,2025,May,20,14,2025-05-14,2,2,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,116.33,0,1
HB-010931,Resort Hotel,1,70,2025,April,15,11,2025-04-11,0,4,2,0.0,0,Undefined,ESP,Direct,Direct,0,0,0,A,A,1,No Deposit,250.0,,0,Transient,128.8,0,1
HB-022109,Resort Hotel,0,51,2024,March,11,17,2024-03-17,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,D,0,No Deposit,66.0,,0,Transient-Party,26.0,0,0
HB-089417,City Hotel,0,28,2024,May,21,20,2024-05-20,0,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,156.0,0,2
HB-085089,City Hotel,0,7,2024,March,10,7,2024-03-07,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,103.0,0,1
HB-062182,City Hotel,1,16,2025,January,1,3,2025-01-03,0,5,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.1,0,2
HB-004506,Resort Hotel,1,39,2024,March,12,21,2024-03-21,1,4,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,96.8,0,0
HB-099083,City Hotel,0,28,2024,October,40,3,2024-10-03,1,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,137.2,0,1
HB-054939,City Hotel,1,173,2024,July,31,31,2024-07-31,2,2,2,1.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.75,0,2
HB-040808,City Hotel,0,1,2023,August,32,7,2023-08-07,2,2,2,0.0,1,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,90.0,0,2
HB-051445,City Hotel,1,198,2024,May,21,20,2024-05-20,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,B,1,No Deposit,1.0,,98,Transient-Party,57.5,0,0
HB-032910,Resort Hotel,0,1,2025,February,6,8,2025-02-08,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,250.0,,0,Transient-Party,43.0,0,0
HB-026994,Resort Hotel,0,11,2024,August,33,15,2024-08-15,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,261.0,1,0
HB-084315,City Hotel,0,0,2024,February,8,22,2024-02-22,1,0,1,0.0,0,BB,CHN,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,85.0,0,0
HB-052622,City Hotel,1,27,2024,June,23,9,2024-06-09,0,1,2,0.0,0,BB,PRT,Offline TA/TO,Corporate,0,0,0,A,A,0,No Deposit,191.0,,0,Transient-Party,120.0,0,0
HB-105716,City Hotel,0,40,2025,February,7,11,2025-02-11,2,2,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,131.4,1,2
HB-112314,City Hotel,0,121,2025,May,21,20,2025-05-20,2,1,1,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,1
HB-016838,Resort Hotel,0,204,2023,September,36,8,2023-09-08,2,5,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,156.0,,0,Contract,55.68,0,0
HB-052380,City Hotel,0,153,2024,June,23,4,2024-06-04,2,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,106.2,0,1
HB-059076,City Hotel,1,263,2024,October,43,21,2024-10-21,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,0,Transient,110.0,0,0
HB-051762,City Hotel,1,11,2024,May,21,24,2024-05-24,0,3,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,160.0,0,0
HB-037484,Resort Hotel,0,73,2025,June,24,15,2025-06-15,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,170.0,0,1
HB-003961,Resort Hotel,1,312,2024,February,6,9,2024-02-09,4,10,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,171.0,,0,Transient,26.1,0,0
HB-093543,City Hotel,0,138,2024,July,29,18,2024-07-18,1,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,115.6,0,1
HB-036026,Resort Hotel,0,111,2025,May,18,1,2025-05-01,2,5,2,0.0,0,FB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Transient,92.95,0,0
HB-061395,City Hotel,1,36,2024,December,50,9,2024-12-09,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,104.0,0,0
HB-109683,City Hotel,0,5,2025,April,15,12,2025-04-12,0,3,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,165.67,1,1
HB-027706,Resort Hotel,0,186,2024,September,36,2,2024-09-02,2,4,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,,0,Transient,159.6,0,0
HB-064910,City Hotel,1,13,2025,March,12,20,2025-03-20,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,108.8,0,1
HB-106976,City Hotel,0,27,2025,March,10,3,2025-03-03,1,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,1
HB-108670,City Hotel,0,63,2025,March,13,27,2025-03-27,1,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,100.3,0,0
HB-066119,City Hotel,1,298,2025,April,16,14,2025-04-14,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,90.0,0,0
HB-064735,City Hotel,1,92,2025,March,11,15,2025-03-15,0,3,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,85.0,0,0
HB-007690,Resort Hotel,1,173,2024,August,34,20,2024-08-20,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,172.0,0,0
HB-076850,City Hotel,0,204,2023,August,32,12,2023-08-12,0,4,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,76.5,0,3
HB-016499,Resort Hotel,0,0,2023,August,35,29,2023-08-29,1,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,240.0,,0,Transient,120.6,0,1
HB-037692,Resort Hotel,0,136,2025,June,26,23,2025-06-23,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,134.0,1,1
HB-072261,City Hotel,1,242,2025,July,30,24,2025-07-24,3,10,3,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,156.6,0,0
HB-058078,City Hotel,1,454,2024,October,40,6,2024-10-06,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,59.0,0,0
HB-007811,Resort Hotel,1,219,2024,August,35,27,2024-08-27,4,6,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,134.0,0,1
HB-101270,City Hotel,0,34,2024,November,45,7,2024-11-07,1,2,1,0.0,0,BB,DEU,Online TA,GDS,0,0,0,A,A,0,No Deposit,195.0,,0,Transient,169.2,0,0
HB-094684,City Hotel,0,2,2024,August,32,7,2024-08-07,1,0,2,1.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,171.0,0,4
HB-090061,City Hotel,0,25,2024,May,22,30,2024-05-30,1,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.0,0,1
HB-000652,Resort Hotel,0,14,2023,July,30,24,2023-07-24,2,2,2,0.0,0,BB,SVN,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,149.7,1,1
HB-019359,Resort Hotel,0,0,2024,January,4,28,2024-01-28,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,2,A,D,0,No Deposit,355.0,,0,Transient,30.0,0,0
HB-084054,City Hotel,0,10,2024,September,39,26,2024-09-26,1,3,1,0.0,0,BB,PRT,Aviation,TA/TO,1,0,4,D,D,0,No Deposit,,153.0,0,Transient,110.0,0,0
HB-101118,City Hotel,0,44,2024,November,44,1,2024-11-01,0,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,91.8,0,2
HB-018476,Resort Hotel,0,0,2023,November,46,17,2023-11-17,0,4,1,0.0,0,HB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,20.0,0,Transient-Party,42.0,0,0
HB-031745,Resort Hotel,0,1,2024,March,10,5,2024-03-05,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,1,D,D,0,No Deposit,240.0,,0,Transient-Party,68.0,0,0
HB-054848,City Hotel,1,386,2024,July,30,28,2024-07-28,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-010524,Resort Hotel,1,57,2025,March,11,11,2025-03-11,2,5,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,D,D,0,No Deposit,298.0,,0,Transient-Party,64.0,0,0
HB-008569,Resort Hotel,0,383,2024,October,40,6,2024-10-06,0,3,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,C,0,No Deposit,315.0,,0,Transient-Party,54.0,1,0
HB-106010,City Hotel,0,60,2025,February,7,16,2025-02-16,0,3,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,1
HB-053361,City Hotel,1,68,2024,June,25,18,2024-06-18,2,1,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,89.53,0,0
HB-068262,City Hotel,1,104,2025,May,20,15,2025-05-15,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-112682,City Hotel,0,289,2025,May,21,24,2025-05-24,0,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,123.3,0,1
HB-093495,City Hotel,0,292,2024,July,29,21,2024-07-21,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,0
HB-098584,City Hotel,0,328,2024,September,40,30,2024-09-30,0,2,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,38,Transient-Party,65.0,0,1
HB-110445,City Hotel,0,7,2025,August,31,2,2025-08-02,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,1,No Deposit,,40.0,0,Transient,65.0,0,1
HB-097484,City Hotel,0,41,2024,September,37,14,2024-09-14,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,86.0,,0,Transient-Party,108.0,0,0
HB-053073,City Hotel,1,188,2024,June,24,15,2024-06-15,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,39,Transient,130.0,0,0
HB-086472,City Hotel,0,41,2024,March,13,31,2024-03-31,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.9,0,1
HB-037265,Resort Hotel,0,18,2025,June,24,9,2025-06-09,1,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,40.0,,0,Contract,73.0,0,0
HB-034013,Resort Hotel,0,107,2025,March,10,9,2025-03-09,0,2,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,E,F,0,No Deposit,96.0,,0,Transient-Party,99.0,0,0
HB-065540,City Hotel,1,79,2025,April,14,5,2025-04-05,0,2,1,0.0,0,BB,LUX,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,0
HB-114383,City Hotel,0,1,2025,June,25,21,2025-06-21,0,1,2,0.0,0,SC,USA,Online TA,TA/TO,1,0,0,A,A,0,No Deposit,7.0,,0,Group,128.0,0,2
HB-046415,City Hotel,1,148,2023,December,52,31,2023-12-31,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,98,Transient,77.5,0,0
HB-028001,Resort Hotel,0,336,2024,September,37,15,2024-09-15,0,3,1,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,A,1,No Deposit,,223.0,0,Transient-Party,60.0,0,0
HB-080523,City Hotel,0,8,2024,April,14,1,2024-04-01,0,2,2,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,D,1,No Deposit,,127.0,0,Transient,84.0,0,1
HB-059475,City Hotel,1,247,2024,October,44,28,2024-10-28,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,110.0,0,0
HB-016284,Resort Hotel,0,10,2023,August,33,17,2023-08-17,1,4,2,0.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,C,C,0,No Deposit,142.0,,0,Contract,191.6,0,0
HB-002945,Resort Hotel,1,36,2023,November,45,7,2023-11-07,2,6,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,281.0,,0,Transient-Party,40.0,0,0
HB-020289,Resort Hotel,0,11,2024,January,4,22,2024-01-22,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,G,G,0,No Deposit,,,0,Transient,71.0,0,1
HB-091803,City Hotel,0,192,2024,June,26,24,2024-06-24,0,2,1,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,34.0,,0,Transient-Party,95.0,0,0
HB-020538,Resort Hotel,0,117,2024,January,4,28,2024-01-28,2,3,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,156.0,,0,Transient,31.63,0,0
HB-104621,City Hotel,0,77,2025,January,3,16,2025-01-16,1,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,K,0,No Deposit,9.0,,0,Transient,79.2,0,1
HB-097284,City Hotel,0,346,2024,September,37,13,2024-09-13,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-043301,City Hotel,0,24,2023,September,37,17,2023-09-17,1,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Contract,119.25,0,0
HB-025392,Resort Hotel,0,322,2024,June,25,22,2024-06-22,0,3,2,0.0,0,HB,POL,Groups,Direct,0,0,0,A,A,0,No Deposit,,,75,Transient-Party,92.0,0,0
HB-057672,City Hotel,1,10,2024,September,40,30,2024-09-30,0,1,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,195.0,0,2
HB-030191,Resort Hotel,0,4,2024,November,46,14,2024-11-14,1,1,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,F,0,No Deposit,240.0,,0,Transient,63.0,0,2
HB-118637,City Hotel,0,129,2025,August,34,23,2025-08-23,0,1,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.0,0,2
HB-010830,Resort Hotel,1,32,2025,April,15,7,2025-04-07,2,5,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,159.29,0,0
HB-095573,City Hotel,0,37,2024,August,33,18,2024-08-18,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,144.9,1,2
HB-079389,City Hotel,0,1,2023,October,43,25,2023-10-25,2,0,3,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,163.0,0,2
HB-057602,City Hotel,1,258,2024,September,39,29,2024-09-29,0,1,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,106.2,0,1
HB-030073,Resort Hotel,0,52,2024,November,45,10,2024-11-10,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,29.0,0,0
HB-046278,City Hotel,0,120,2023,December,52,29,2023-12-29,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,72.25,0,1
HB-038374,Resort Hotel,0,18,2025,July,28,13,2025-07-13,0,3,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,166.0,0,1
HB-059079,City Hotel,1,279,2024,October,43,21,2024-10-21,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,65.0,0,0
HB-043011,City Hotel,0,68,2023,September,37,12,2023-09-12,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,B,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-114428,City Hotel,0,34,2025,June,25,20,2025-06-20,0,2,2,0.0,0,SC,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,96.0,0,1
HB-078799,City Hotel,0,14,2023,October,41,15,2023-10-15,0,2,1,0.0,0,BB,DZA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,99.0,,0,Transient-Party,100.0,0,0
HB-072274,City Hotel,1,464,2025,July,30,25,2025-07-25,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-013494,Resort Hotel,1,168,2025,August,33,17,2025-08-17,2,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,314.0,,0,Transient,176.0,0,1
HB-038937,Resort Hotel,0,31,2025,July,31,31,2025-07-31,1,2,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,205.0,0,3
HB-085737,City Hotel,0,13,2024,March,12,20,2024-03-20,1,0,1,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,220.0,,0,Transient-Party,6.0,0,0
HB-069558,City Hotel,1,145,2025,June,23,2,2025-06-02,0,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-057358,City Hotel,1,254,2024,September,39,24,2024-09-24,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,96.0,0,0
HB-015384,Resort Hotel,1,164,2023,July,28,11,2023-07-11,2,5,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,H,0,No Deposit,,,0,Transient,115.0,0,0
HB-059832,City Hotel,1,14,2024,November,44,3,2024-11-03,0,1,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,112.0,0,1
HB-054918,City Hotel,1,122,2024,July,31,30,2024-07-30,2,2,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,142.2,0,0
HB-008984,Resort Hotel,1,178,2024,October,43,22,2024-10-22,2,2,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,70.75,0,0
HB-073094,City Hotel,1,100,2025,August,33,14,2025-08-14,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,155.0,0,1
HB-053234,City Hotel,1,245,2024,June,25,17,2024-06-17,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,0,Transient,75.0,0,0
HB-071926,City Hotel,1,476,2025,July,29,15,2025-07-15,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,0
HB-065625,City Hotel,1,62,2025,April,14,6,2025-04-06,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,135.0,0,0
HB-107783,City Hotel,0,73,2025,March,11,15,2025-03-15,0,3,3,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,142.2,0,1
HB-004947,Resort Hotel,0,190,2024,April,15,10,2024-04-10,2,5,1,0.0,0,HB,GBR,Groups,Direct,0,0,0,A,A,0,No Deposit,273.0,,0,Transient-Party,47.9,0,0
HB-039180,Resort Hotel,0,195,2025,August,31,3,2025-08-03,2,5,2,1.0,1,BB,PRT,Direct,Direct,0,0,0,D,D,1,No Deposit,250.0,,0,Transient,182.16,0,2
HB-001756,Resort Hotel,0,149,2023,September,37,12,2023-09-12,2,5,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,275.0,,0,Transient,53.1,0,0
HB-056228,City Hotel,1,419,2024,September,35,1,2024-09-01,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-083635,City Hotel,0,18,2024,February,6,6,2024-02-06,2,1,1,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,81.8,0,1
HB-026126,Resort Hotel,0,173,2024,July,28,12,2024-07-12,2,9,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,143.0,,0,Transient,90.1,0,1
HB-100266,City Hotel,0,4,2024,October,43,24,2024-10-24,1,0,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,152.0,,0,Transient,110.71,0,0
HB-011312,Resort Hotel,1,41,2025,May,18,2,2025-05-02,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,100.0,0,1
HB-109887,City Hotel,0,51,2025,April,16,15,2025-04-15,2,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.0,0,1
HB-059949,City Hotel,1,74,2024,November,45,4,2024-11-04,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.6,0,0
HB-076607,City Hotel,0,138,2023,July,30,25,2023-07-25,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,2,No Deposit,1.0,,0,Transient-Party,57.0,0,0
HB-082820,City Hotel,1,68,2024,February,7,17,2024-02-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,37.0,,0,Transient,75.0,0,0
HB-030136,Resort Hotel,0,14,2025,March,10,8,2025-03-08,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,1,0,2,A,A,0,No Deposit,240.0,,0,Transient-Party,60.0,0,2
HB-065981,City Hotel,1,112,2025,April,15,12,2025-04-12,0,3,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,172.5,0,1
HB-029172,Resort Hotel,0,132,2024,October,42,16,2024-10-16,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,40.0,,0,Contract,95.0,0,0
HB-021875,Resort Hotel,0,30,2024,March,10,7,2024-03-07,1,5,2,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,38.0,,0,Transient-Party,65.4,0,0
HB-074162,City Hotel,1,349,2023,October,39,1,2023-10-01,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-053867,City Hotel,1,142,2024,July,27,1,2024-07-01,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,85.5,0,0
HB-057844,City Hotel,1,135,2024,October,40,1,2024-10-01,2,1,2,0.0,0,BB,TWN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,132.3,0,0
HB-083995,City Hotel,0,3,2024,February,7,14,2024-02-14,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,82.0,0,0
HB-105281,City Hotel,0,72,2025,February,5,2,2025-02-02,0,2,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,71.28,0,1
HB-038119,Resort Hotel,0,177,2025,July,27,6,2025-07-06,1,3,2,0.0,0,BB,KWT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,100.18,0,1
HB-022208,Resort Hotel,0,10,2024,March,12,19,2024-03-19,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,F,0,No Deposit,250.0,,0,Transient,75.0,0,0
HB-077688,City Hotel,1,18,2023,October,40,4,2023-10-04,2,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,29.0,,0,Transient,110.0,0,0
HB-059680,City Hotel,1,93,2024,October,44,31,2024-10-31,1,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.3,0,2
HB-102587,City Hotel,0,65,2024,December,49,6,2024-12-06,0,2,2,1.0,0,BB,ITA,Online TA,TA/TO,0,0,1,A,D,1,No Deposit,7.0,,0,Transient,72.07,0,2
HB-081400,City Hotel,0,75,2023,December,49,7,2023-12-07,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Transient,60.0,0,0
HB-001215,Resort Hotel,0,92,2023,August,33,18,2023-08-18,2,8,2,2.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,239.5,0,1
HB-010255,Resort Hotel,1,55,2025,February,8,23,2025-02-23,0,2,2,1.0,0,BB,CHL,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,93.0,0,0
HB-097574,City Hotel,0,88,2024,September,38,16,2024-09-16,0,2,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,D,B,0,No Deposit,9.0,,0,Transient,158.4,1,1
HB-090372,City Hotel,0,116,2024,June,22,2,2024-06-02,1,3,3,0.0,0,BB,IRL,Direct,Direct,0,0,0,D,D,3,No Deposit,14.0,,0,Transient-Party,136.25,0,0
HB-117291,City Hotel,0,181,2025,July,31,30,2025-07-30,2,1,2,0.0,0,BB,SWE,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,168.0,,0,Transient,80.1,0,0
HB-039643,Resort Hotel,0,19,2025,August,34,21,2025-08-21,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,210.0,0,2
HB-084465,City Hotel,0,1,2024,February,8,24,2024-02-24,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,73.61,0,0
HB-090148,City Hotel,0,140,2024,May,22,28,2024-05-28,2,4,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,B,0,No Deposit,7.0,,0,Transient,103.42,0,2
HB-065718,City Hotel,1,60,2025,April,14,6,2025-04-06,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,126.0,0,0
HB-014133,Resort Hotel,0,1,2025,January,4,21,2025-01-21,0,1,2,0.0,0,BB,,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,65.0,1,1
HB-113127,City Hotel,0,409,2025,May,22,31,2025-05-31,0,3,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,C,0,No Deposit,229.0,,0,Transient-Party,112.67,0,1
HB-099267,City Hotel,0,176,2024,October,41,7,2024-10-07,2,2,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,11.0,,0,Transient,94.12,0,0
HB-117553,City Hotel,0,69,2025,July,31,29,2025-07-29,2,6,2,0.0,0,SC,RUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,126.0,0,2
HB-028712,Resort Hotel,0,8,2024,October,40,6,2024-10-06,1,3,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,D,1,No Deposit,,405.0,0,Transient-Party,50.0,0,1
HB-059451,City Hotel,1,464,2024,October,44,28,2024-10-28,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,2,Non Refund,1.0,,391,Transient,65.0,0,0
HB-019949,Resort Hotel,0,1,2024,January,2,11,2024-01-11,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,1,No Deposit,195.0,,0,Transient,30.0,0,0
HB-083776,City Hotel,0,0,2024,February,6,10,2024-02-10,0,2,2,1.0,0,BB,GBR,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,104.0,0,0
HB-039954,Resort Hotel,0,1,2025,August,35,31,2025-08-31,0,2,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,184.0,1,0
HB-034425,Resort Hotel,0,15,2025,March,12,18,2025-03-18,2,5,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,314.0,,0,Transient,62.0,0,0
HB-020141,Resort Hotel,0,5,2024,January,3,16,2024-01-16,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,43.0,0,1
HB-006782,Resort Hotel,0,305,2024,July,27,1,2024-07-01,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,40.0,,0,Contract,59.8,0,0
HB-043406,City Hotel,1,74,2023,September,38,18,2023-09-18,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-046976,City Hotel,1,24,2024,January,5,30,2024-01-30,4,11,1,0.0,0,BB,AGO,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.14,0,0
HB-023076,Resort Hotel,0,75,2024,April,15,13,2024-04-13,0,2,1,0.0,0,BB,HUN,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,55.0,1,1
HB-097330,City Hotel,0,346,2024,September,37,13,2024-09-13,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-019733,Resort Hotel,0,112,2023,December,52,30,2023-12-30,0,3,2,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,237.33,0,0
HB-099067,City Hotel,0,1,2024,October,41,7,2024-10-07,0,2,2,0.0,0,BB,POL,Corporate,Corporate,0,0,0,A,A,1,No Deposit,193.0,,0,Transient-Party,90.0,0,1
HB-046484,City Hotel,0,2,2024,January,1,3,2024-01-03,2,0,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,67.66,0,0
HB-060295,City Hotel,1,277,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-077422,City Hotel,0,19,2023,October,40,6,2023-10-06,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,1,0,0,A,D,0,No Deposit,82.0,,0,Transient-Party,80.0,0,0
HB-103418,City Hotel,0,29,2024,December,51,19,2024-12-19,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.4,0,0
HB-107449,City Hotel,0,66,2025,March,11,10,2025-03-10,1,2,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,154.0,,0,Transient-Party,80.0,0,1
HB-062589,City Hotel,1,278,2025,January,3,16,2025-01-16,1,0,2,0.0,0,BB,SGP,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,67.15,0,0
HB-007319,Resort Hotel,1,434,2024,August,31,2,2024-08-02,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,40.0,,0,Contract,160.5,0,0
HB-057756,City Hotel,1,315,2024,September,40,30,2024-09-30,1,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,69,Transient,160.0,0,0
HB-105003,City Hotel,0,1,2025,January,4,26,2025-01-26,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,E,E,2,No Deposit,,365.0,0,Transient-Party,95.0,0,0
HB-098803,City Hotel,0,207,2024,September,40,30,2024-09-30,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,106.25,0,2
HB-011635,Resort Hotel,1,17,2025,May,21,22,2025-05-22,4,10,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,147.36,0,1
HB-034724,Resort Hotel,0,0,2025,April,14,3,2025-04-03,0,0,1,0.0,0,BB,PRT,Online TA,TA/TO,1,0,0,A,I,0,No Deposit,184.0,,0,Transient,0.0,0,0
HB-029247,Resort Hotel,0,62,2024,October,43,23,2024-10-23,1,0,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,E,1,No Deposit,240.0,,0,Transient,49.0,0,1
HB-021525,Resort Hotel,0,0,2024,March,9,2,2024-03-02,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,40.0,0,0
HB-106038,City Hotel,0,59,2025,February,7,14,2025-02-14,0,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,98.6,0,2
HB-026929,Resort Hotel,0,71,2024,August,33,12,2024-08-12,1,2,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,241.0,,0,Transient,178.43,0,1
HB-110129,City Hotel,0,44,2025,April,16,20,2025-04-20,0,3,1,0.0,0,BB,ITA,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,106.67,0,0
HB-079092,City Hotel,0,5,2023,October,42,19,2023-10-19,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,112.0,,0,Transient-Party,90.0,0,0
HB-052288,City Hotel,1,118,2024,June,22,2,2024-06-02,0,3,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,116.1,0,0
HB-001020,Resort Hotel,0,35,2023,August,32,10,2023-08-10,1,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,241.0,,0,Transient,164.65,0,1
HB-015304,Resort Hotel,0,0,2023,July,27,5,2023-07-05,1,0,2,2.0,0,BB,USA,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Group,153.0,0,0
HB-071001,City Hotel,1,34,2025,June,26,27,2025-06-27,0,1,3,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,189.0,0,1
HB-050488,City Hotel,1,437,2024,May,18,2,2024-05-02,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-077079,City Hotel,0,219,2023,September,36,4,2023-09-04,0,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,B,0,No Deposit,6.0,,0,Transient-Party,108.0,0,0
HB-031805,Resort Hotel,0,244,2024,December,51,22,2024-12-22,4,12,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,64.21,0,2
HB-097757,City Hotel,0,126,2024,September,37,15,2024-09-15,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,147.1,0,4
HB-003696,Resort Hotel,0,165,2023,December,52,30,2023-12-30,0,4,1,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,308.0,,122,Transient-Party,0.0,0,0
HB-096641,City Hotel,0,48,2024,August,35,31,2024-08-31,1,4,2,0.0,0,BB,CHE,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,168.0,,0,Transient,85.5,0,1
HB-112059,City Hotel,0,394,2025,May,20,16,2025-05-16,0,4,2,0.0,0,BB,AUS,Offline TA/TO,TA/TO,0,0,0,A,A,4,No Deposit,229.0,,0,Transient-Party,107.0,0,1
HB-053761,City Hotel,1,50,2024,June,26,29,2024-06-29,0,3,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,0
HB-007969,Resort Hotel,1,223,2024,September,36,5,2024-09-05,1,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,100.0,0,1
HB-057209,City Hotel,1,62,2024,September,38,21,2024-09-21,0,1,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,75.0,0,0
HB-039343,Resort Hotel,0,105,2025,August,32,8,2025-08-08,2,5,3,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,275.0,0,1
HB-008988,Resort Hotel,1,17,2024,October,43,22,2024-10-22,2,2,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,95.0,0,0
HB-040754,City Hotel,1,84,2023,August,31,6,2023-08-06,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,1
HB-025717,Resort Hotel,0,181,2024,July,27,4,2024-07-04,1,3,2,0.0,0,BB,DNK,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,108.0,0,1
HB-031466,Resort Hotel,0,61,2024,December,51,22,2024-12-22,2,5,1,0.0,0,Undefined,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,464.0,,0,Transient,77.14,0,0
HB-103138,City Hotel,0,7,2024,December,50,9,2024-12-09,2,2,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,86.78,0,1
HB-093035,City Hotel,0,87,2024,July,28,9,2024-07-09,2,5,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,8.0,,0,Transient,181.16,0,2
HB-099628,City Hotel,0,335,2024,October,41,13,2024-10-13,0,3,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,80.0,0,0
HB-040735,City Hotel,0,34,2023,August,31,5,2023-08-05,0,2,3,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,D,1,No Deposit,1.0,,0,Transient-Party,84.0,0,0
HB-022787,Resort Hotel,0,1,2024,April,14,5,2024-04-05,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,75.0,0,1
HB-034440,Resort Hotel,0,15,2025,March,12,19,2025-03-19,2,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,242.0,,0,Transient,95.0,0,1
HB-012324,Resort Hotel,1,86,2025,June,26,24,2025-06-24,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,140.0,0,0
HB-053371,City Hotel,1,38,2024,June,25,19,2024-06-19,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,52.0,,0,Transient,81.0,0,0
HB-112764,City Hotel,0,219,2025,May,21,25,2025-05-25,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,96.33,0,1
HB-082582,City Hotel,0,93,2023,December,52,30,2023-12-30,0,4,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,28.0,,0,Group,61.0,0,0
HB-070343,City Hotel,1,320,2025,June,24,15,2025-06-15,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient,90.0,0,0
HB-117616,City Hotel,0,132,2025,July,31,29,2025-07-29,3,6,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,141.78,0,2
HB-021104,Resort Hotel,0,28,2024,February,6,11,2024-02-11,2,5,2,1.0,0,HB,FRA,Online TA,TA/TO,0,0,0,E,E,2,No Deposit,241.0,,0,Transient,80.85,1,3
HB-041910,City Hotel,0,0,2023,August,34,26,2023-08-26,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,1,No Deposit,14.0,,0,Transient,148.0,0,0
HB-015566,Resort Hotel,0,51,2023,July,29,22,2023-07-22,0,4,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,147.0,,0,Transient,101.68,0,0
HB-112156,City Hotel,0,109,2025,May,20,18,2025-05-18,0,3,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,123.67,0,0
HB-113756,City Hotel,0,212,2025,June,24,9,2025-06-09,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,1
HB-102333,City Hotel,0,56,2024,November,47,24,2024-11-24,0,3,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient-Party,95.38,0,1
HB-003705,Resort Hotel,0,165,2023,December,52,30,2023-12-30,0,4,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,D,0,No Deposit,308.0,,122,Transient-Party,136.5,0,0
HB-108826,City Hotel,0,7,2025,March,12,22,2025-03-22,2,9,2,0.0,1,BB,PRT,Online TA,TA/TO,0,0,0,F,F,2,No Deposit,9.0,,0,Transient,212.73,0,2
HB-003503,Resort Hotel,1,113,2023,December,51,19,2023-12-19,2,2,2,0.0,1,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,66.0,0,1
HB-102494,City Hotel,0,5,2025,March,10,8,2025-03-08,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,3,A,D,0,No Deposit,,219.0,0,Transient,89.0,0,2
HB-059815,City Hotel,1,135,2024,November,44,2,2024-11-02,1,4,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.0,0,0
HB-027745,Resort Hotel,0,232,2024,September,36,3,2024-09-03,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,143.0,,0,Contract,79.9,0,0
HB-028199,Resort Hotel,0,174,2024,September,38,20,2024-09-20,0,4,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,G,G,3,No Deposit,240.0,,0,Transient-Party,154.0,0,0
HB-075109,City Hotel,1,344,2023,September,39,26,2023-09-26,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-036348,Resort Hotel,0,351,2025,May,18,4,2025-05-04,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Contract,42.95,0,0
HB-022284,Resort Hotel,0,76,2024,March,11,12,2024-03-12,4,6,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,78.0,0,1
HB-057941,City Hotel,1,223,2024,October,40,3,2024-10-03,1,3,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,102.85,0,0
HB-091509,City Hotel,0,0,2024,June,25,21,2024-06-21,0,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,,,0,Transient,101.7,0,1
HB-019499,Resort Hotel,0,34,2023,December,51,22,2023-12-22,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,240.0,,0,Transient,35.1,0,2
HB-073117,City Hotel,1,40,2025,August,33,15,2025-08-15,0,1,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,1
HB-051768,City Hotel,1,8,2024,May,21,25,2024-05-25,0,1,1,0.0,0,SC,TUR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.0,0,0
HB-015998,Resort Hotel,0,146,2023,August,31,3,2023-08-03,2,5,3,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,71.0,,0,Contract,130.01,0,2
HB-094935,City Hotel,0,63,2024,August,32,9,2024-08-09,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,144.1,0,0
HB-023053,Resort Hotel,0,0,2024,April,15,14,2024-04-14,0,1,2,0.0,0,BB,FRA,Direct,TA/TO,1,0,0,A,A,0,No Deposit,,,0,Transient,75.0,0,1
HB-019093,Resort Hotel,0,7,2023,December,49,5,2023-12-05,2,1,2,2.0,0,HB,ESP,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,241.0,,0,Transient,97.02,0,0
HB-072102,City Hotel,1,21,2025,July,30,21,2025-07-21,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,128.0,0,1
HB-032448,Resort Hotel,0,0,2025,January,4,26,2025-01-26,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-071071,City Hotel,1,142,2025,June,26,28,2025-06-28,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,125.0,0,0
HB-073688,City Hotel,1,134,2025,August,35,31,2025-08-31,0,2,2,1.0,0,BB,SAU,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,242.5,0,1
HB-083205,City Hotel,0,2,2024,January,4,23,2024-01-23,0,1,2,0.0,0,BB,ROU,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,96.0,0,1
HB-053947,City Hotel,0,209,2024,July,27,2,2024-07-02,2,4,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,72.75,0,1
HB-086416,City Hotel,0,59,2024,March,13,31,2024-03-31,0,3,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.9,0,1
HB-109697,City Hotel,0,116,2025,April,15,13,2025-04-13,0,2,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,126.0,1,0
HB-067569,City Hotel,1,17,2025,May,18,4,2025-05-04,1,3,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,152.5,0,0
HB-008062,Resort Hotel,1,3,2024,September,37,9,2024-09-09,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,100.0,0,0
HB-060586,City Hotel,1,16,2024,November,46,16,2024-11-16,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,355.0,,0,Transient-Party,75.0,0,0
HB-087782,City Hotel,0,45,2024,April,17,23,2024-04-23,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,24.0,,0,Transient-Party,95.0,0,1
HB-084742,City Hotel,0,45,2024,February,9,29,2024-02-29,1,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.3,0,0
HB-002988,Resort Hotel,0,49,2023,November,45,9,2023-11-09,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,52.2,0,2
HB-057091,City Hotel,1,31,2024,September,38,18,2024-09-18,2,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,7.0,,0,Transient,156.42,0,1
HB-030816,Resort Hotel,0,80,2024,December,49,2,2024-12-02,0,2,1,0.0,0,BB,IRL,Groups,TA/TO,0,0,0,D,D,3,No Deposit,253.0,,0,Transient-Party,44.8,0,0
HB-090866,City Hotel,0,3,2024,June,24,10,2024-06-10,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,90.67,0,0
HB-070444,City Hotel,1,7,2025,June,25,17,2025-06-17,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,180.0,0,1
HB-015020,Resort Hotel,0,6,2023,November,45,9,2023-11-09,1,3,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,E,1,No Deposit,,94.0,0,Transient,25.0,0,0
HB-015404,Resort Hotel,0,8,2023,September,36,9,2023-09-09,0,1,3,0.0,0,BB,PRT,Direct,Direct,1,0,1,G,G,0,No Deposit,,,0,Transient,153.0,1,2
HB-113097,City Hotel,0,17,2025,May,22,28,2025-05-28,2,3,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,111.52,0,0
HB-106439,City Hotel,0,3,2025,February,9,24,2025-02-24,0,1,3,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,216.0,0,Transient-Party,114.4,0,0
HB-042089,City Hotel,0,145,2023,August,35,31,2023-08-31,1,2,2,0.0,0,HB,ISR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,80.0,0,1
HB-019832,Resort Hotel,0,2,2024,January,1,1,2024-01-01,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,64.25,0,2
HB-041037,City Hotel,0,2,2023,August,32,11,2023-08-11,0,2,2,1.0,0,BB,FRA,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,90.0,0,1
HB-044868,City Hotel,0,36,2023,October,41,13,2023-10-13,0,3,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,26.0,,0,Transient-Party,91.0,0,0
HB-070379,City Hotel,1,55,2025,June,25,16,2025-06-16,0,2,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,1
HB-114239,City Hotel,0,141,2025,June,25,16,2025-06-16,1,2,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,89.1,0,0
HB-091061,City Hotel,0,2,2024,June,24,14,2024-06-14,0,2,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,104.0,0,1
HB-066214,City Hotel,1,212,2025,April,16,15,2025-04-15,2,2,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,110.0,0,0
HB-087853,City Hotel,0,144,2024,April,17,24,2024-04-24,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,71.0,0,0
HB-115186,City Hotel,0,169,2025,July,27,2,2025-07-02,1,0,2,0.0,0,BB,HUN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,0
HB-012385,Resort Hotel,1,313,2025,June,26,26,2025-06-26,1,4,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Refundable,40.0,,0,Contract,84.7,0,1
HB-042502,City Hotel,0,55,2023,September,36,6,2023-09-06,2,0,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,B,0,No Deposit,1.0,,0,Transient-Party,75.0,0,0
HB-118579,City Hotel,0,127,2025,August,33,16,2025-08-16,2,5,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,262.0,,0,Transient,80.1,0,1
HB-013203,Resort Hotel,1,166,2025,August,32,4,2025-08-04,2,4,2,2.0,0,BB,IRL,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,220.0,0,2
HB-033531,Resort Hotel,0,70,2025,February,8,22,2025-02-22,0,4,3,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,1,No Deposit,,405.0,0,Transient-Party,58.0,0,0
HB-095770,City Hotel,0,303,2024,August,34,19,2024-08-19,2,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,78.0,0,1
HB-066095,City Hotel,1,34,2025,April,16,14,2025-04-14,0,2,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,220.0,0,0
HB-110951,City Hotel,0,2,2025,May,18,4,2025-05-04,1,3,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,150.0,0,1
HB-086702,City Hotel,0,9,2024,April,14,6,2024-04-06,0,1,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,0.0,0,0
HB-027416,Resort Hotel,0,6,2024,August,35,28,2024-08-28,1,0,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,171.0,0,2
HB-109321,City Hotel,0,71,2025,April,14,6,2025-04-06,1,3,2,0.0,0,SC,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,80.1,0,0
HB-062105,City Hotel,1,123,2025,January,1,2,2025-01-02,1,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,102.6,0,1
HB-101187,City Hotel,0,0,2024,November,45,8,2024-11-08,0,0,1,0.0,0,BB,PRT,Aviation,Corporate,1,0,0,A,D,1,No Deposit,,153.0,0,Transient,0.0,0,0
HB-068895,City Hotel,1,159,2025,May,21,22,2025-05-22,1,2,1,0.0,0,BB,CYP,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,126.0,0,0
HB-051133,City Hotel,1,121,2024,May,20,14,2024-05-14,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,96.0,0,0
HB-046756,City Hotel,0,151,2024,January,3,19,2024-01-19,0,2,1,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,19.0,,63,Transient-Party,71.0,0,0
HB-086320,City Hotel,0,47,2024,March,13,28,2024-03-28,1,3,2,1.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,9.0,,0,Transient,101.15,0,2
HB-006804,Resort Hotel,1,138,2024,July,27,2,2024-07-02,4,6,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,134.0,0,0
HB-028971,Resort Hotel,0,364,2024,October,41,12,2024-10-12,1,4,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,1,No Deposit,,223.0,0,Transient-Party,66.0,0,1
HB-021839,Resort Hotel,0,14,2024,March,10,7,2024-03-07,1,4,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,1,No Deposit,250.0,,0,Transient,45.0,0,1
HB-010746,Resort Hotel,1,24,2025,March,14,31,2025-03-31,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,70.0,0,1
HB-047677,City Hotel,1,1,2024,February,9,28,2024-02-28,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,60.0,0,0
HB-042702,City Hotel,0,86,2023,September,36,9,2023-09-09,0,2,2,0.0,0,BB,FRA,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,68.0,0,Transient-Party,100.0,0,0
HB-096092,City Hotel,0,186,2024,August,35,28,2024-08-28,1,0,2,1.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,112.5,0,0
HB-002022,Resort Hotel,0,59,2023,September,39,27,2023-09-27,2,5,2,0.0,0,HB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,106.31,0,2
HB-038143,Resort Hotel,0,177,2025,June,27,30,2025-06-30,3,7,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,175.0,,0,Transient,79.2,0,0
HB-014183,Resort Hotel,0,80,2025,June,24,9,2025-06-09,2,2,2,0.0,0,FB,PRT,Direct,Direct,0,1,0,F,F,1,No Deposit,250.0,,0,Transient,195.0,0,0
HB-115679,City Hotel,0,0,2025,July,28,7,2025-07-07,0,2,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,152.0,,0,Transient,101.98,0,0
HB-068273,City Hotel,1,164,2025,May,20,15,2025-05-15,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-111227,City Hotel,0,179,2025,May,19,5,2025-05-05,1,2,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,99.0,0,0
HB-065274,City Hotel,1,60,2025,March,13,30,2025-03-30,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,104.4,0,0
HB-008483,Resort Hotel,1,65,2024,October,40,1,2024-10-01,1,1,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,99.0,0,1
HB-085782,City Hotel,0,13,2024,March,12,20,2024-03-20,1,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,220.0,,0,Transient,85.0,0,0
HB-014092,Resort Hotel,0,0,2023,December,48,3,2023-12-03,0,1,1,0.0,0,BB,,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,38.0,0,0
HB-093181,City Hotel,0,142,2024,July,28,13,2024-07-13,1,4,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,16.0,,0,Transient,72.25,0,2
HB-009583,Resort Hotel,1,38,2024,December,51,16,2024-12-16,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,4,No Deposit,240.0,,0,Transient,66.0,0,1
HB-087834,City Hotel,0,101,2024,April,17,26,2024-04-26,0,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,35.0,,0,Transient-Party,98.0,0,0
HB-018794,Resort Hotel,0,2,2025,March,12,18,2025-03-18,0,1,3,0.0,0,BB,PRT,Direct,Direct,1,1,3,D,D,0,No Deposit,,,0,Transient,115.0,0,1
HB-097708,City Hotel,0,4,2024,September,38,19,2024-09-19,1,0,2,0.0,0,SC,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,85.0,0,0
HB-112448,City Hotel,0,87,2025,May,21,22,2025-05-22,1,1,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,475.0,,0,Transient-Party,126.0,0,0
HB-071480,City Hotel,1,175,2025,July,27,6,2025-07-06,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,117.9,0,0
HB-093450,City Hotel,0,99,2024,July,29,18,2024-07-18,1,3,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,141.75,0,2
HB-064332,City Hotel,1,20,2025,March,10,6,2025-03-06,1,1,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,118.0,0,0
HB-027007,Resort Hotel,0,93,2024,August,33,14,2024-08-14,2,1,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,240.0,,0,Transient,216.33,0,1
HB-035414,Resort Hotel,0,30,2025,April,17,21,2025-04-21,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,169.0,0,Transient-Party,50.0,0,0
HB-018559,Resort Hotel,0,62,2023,November,46,18,2023-11-18,2,4,1,0.0,0,Undefined,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,313.0,,0,Transient-Party,18.5,0,0
HB-102737,City Hotel,0,50,2024,December,49,2,2024-12-02,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.6,0,2
HB-033206,Resort Hotel,0,94,2025,February,7,13,2025-02-13,1,3,2,0.0,0,HB,GBR,Complementary,TA/TO,0,0,0,A,A,0,No Deposit,152.0,,0,Transient-Party,0.0,0,0
HB-050050,City Hotel,1,142,2024,April,17,22,2024-04-22,2,3,1,0.0,0,BB,POL,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,89.0,0,0
HB-019257,Resort Hotel,1,86,2024,February,7,12,2024-02-12,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,,,0,Transient,50.0,0,0
HB-110505,City Hotel,0,102,2025,April,17,24,2025-04-24,1,3,1,0.0,0,BB,IRL,Groups,TA/TO,0,0,0,A,A,1,No Deposit,,424.0,0,Transient-Party,90.0,0,0
HB-015391,Resort Hotel,0,130,2023,July,27,4,2023-07-04,2,6,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,196.0,,0,Transient,64.9,0,1
HB-105957,City Hotel,0,70,2025,February,7,15,2025-02-15,0,4,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,D,0,No Deposit,,242.0,0,Transient-Party,78.0,0,0
HB-031276,Resort Hotel,0,117,2024,December,51,17,2024-12-17,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,29.11,0,1
HB-065072,City Hotel,1,102,2025,March,12,23,2025-03-23,1,3,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,100.3,0,1
HB-004570,Resort Hotel,1,13,2024,March,12,24,2024-03-24,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,92.0,0,0
HB-012640,Resort Hotel,1,60,2025,July,28,9,2025-07-09,2,5,2,0.0,0,HB,PRT,Corporate,Corporate,0,0,0,D,D,0,No Deposit,531.0,,0,Transient,120.0,0,0
HB-021424,Resort Hotel,0,3,2024,February,9,27,2024-02-27,1,1,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,171.0,,0,Transient,37.0,0,1
HB-037004,Resort Hotel,0,116,2025,June,22,1,2025-06-01,0,3,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,135.52,0,3
HB-045586,City Hotel,1,85,2023,November,45,7,2023-11-07,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,60,Transient,111.0,0,0
HB-062268,City Hotel,1,18,2025,January,2,6,2025-01-06,2,2,2,2.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,F,F,1,No Deposit,15.0,,0,Transient,116.79,0,2
HB-072220,City Hotel,1,74,2025,July,30,23,2025-07-23,4,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,145.56,0,1
HB-024856,Resort Hotel,0,16,2024,June,23,4,2024-06-04,1,1,3,1.0,0,BB,POL,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,186.0,1,0
HB-093332,City Hotel,0,187,2024,July,29,18,2024-07-18,1,2,2,1.0,0,BB,NOR,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,122.8,0,2
HB-107807,City Hotel,0,57,2025,March,11,16,2025-03-16,0,3,2,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-000907,Resort Hotel,0,81,2023,August,31,4,2023-08-04,2,8,2,0.0,0,HB,RUS,Direct,Direct,0,0,0,D,D,1,No Deposit,250.0,,0,Transient,187.8,0,1
HB-060861,City Hotel,0,326,2024,November,47,24,2024-11-24,0,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,67.5,0,2
HB-011048,Resort Hotel,1,4,2025,April,16,16,2025-04-16,2,0,3,1.0,0,BB,PRT,Direct,Direct,0,0,0,H,H,0,No Deposit,250.0,,0,Transient,181.0,0,0
HB-089285,City Hotel,0,57,2024,May,20,18,2024-05-18,0,2,1,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,111.6,0,2
HB-080925,City Hotel,0,11,2023,December,50,13,2023-12-13,2,0,1,0.0,0,BB,ITA,Online TA,TA/TO,1,0,1,A,A,0,No Deposit,7.0,,0,Transient,66.99,0,1
HB-073622,City Hotel,1,50,2025,August,35,28,2025-08-28,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,115.2,0,0
HB-030138,Resort Hotel,0,20,2024,November,46,13,2024-11-13,2,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,2,No Deposit,,,0,Transient,62.7,1,2
HB-073442,City Hotel,1,106,2025,August,34,22,2025-08-22,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.0,0,0
HB-107532,City Hotel,0,0,2025,March,11,13,2025-03-13,1,0,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,89.68,0,0
HB-092398,City Hotel,0,41,2024,July,27,2,2024-07-02,2,2,3,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,150.3,0,1
HB-023800,Resort Hotel,0,5,2024,May,20,18,2024-05-18,0,1,1,0.0,0,BB,PRI,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,154.0,0,Transient,39.0,0,0
HB-058976,City Hotel,1,67,2024,October,42,19,2024-10-19,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,117.6,0,0
HB-074194,City Hotel,1,356,2023,October,40,8,2023-10-08,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-001043,Resort Hotel,1,117,2023,August,32,11,2023-08-11,0,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,242.0,,0,Transient-Party,186.0,0,1
HB-017085,Resort Hotel,0,197,2023,September,37,15,2023-09-15,2,8,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,66.15,0,0
HB-059125,City Hotel,1,263,2024,October,43,21,2024-10-21,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,0,Transient,110.0,0,0
HB-098698,City Hotel,0,91,2024,September,40,30,2024-09-30,1,2,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,3.0,,0,Transient-Party,75.0,0,0
HB-051118,City Hotel,1,276,2024,May,20,13,2024-05-13,2,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,160,Transient,61.0,0,0
HB-024758,Resort Hotel,0,21,2024,May,22,30,2024-05-30,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,100.67,1,1
HB-045652,City Hotel,0,140,2023,November,46,18,2023-11-18,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,29.0,,87,Transient-Party,65.0,0,0
HB-003831,Resort Hotel,1,172,2024,January,3,17,2024-01-17,3,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,59.4,0,1
HB-025088,Resort Hotel,0,107,2024,June,23,8,2024-06-08,2,5,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient,106.0,0,1
HB-069365,City Hotel,1,186,2025,May,22,30,2025-05-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,130.0,0,0
HB-101373,City Hotel,0,16,2024,November,45,6,2024-11-06,2,3,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,169.6,0,1
HB-095877,City Hotel,0,14,2024,August,34,19,2024-08-19,2,4,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,155.83,0,1
HB-079484,City Hotel,0,43,2023,October,43,24,2023-10-24,2,2,1,0.0,0,BB,CN,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,147.25,0,1
HB-078586,City Hotel,0,3,2023,October,41,12,2023-10-12,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-038957,Resort Hotel,0,97,2025,August,31,1,2025-08-01,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,230.0,0,2
HB-083409,City Hotel,0,2,2024,January,5,30,2024-01-30,0,1,1,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,80.0,0,1
HB-029690,Resort Hotel,0,46,2024,November,44,2,2024-11-02,0,2,2,0.0,0,HB,LTU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,70.8,1,1
HB-038902,Resort Hotel,0,0,2025,July,31,29,2025-07-29,2,2,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,225.0,0,1
HB-077567,City Hotel,0,5,2023,September,38,22,2023-09-22,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,F,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-062992,City Hotel,1,61,2025,January,4,25,2025-01-25,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,326.0,,0,Transient,80.0,0,0
HB-117290,City Hotel,0,74,2025,July,31,29,2025-07-29,2,2,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,7.0,,0,Transient,185.0,0,1
HB-008986,Resort Hotel,1,178,2024,October,43,22,2024-10-22,2,2,3,1.0,0,BB,SWE,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,110.75,0,0
HB-003256,Resort Hotel,0,28,2023,November,48,27,2023-11-27,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,15.0,,0,Transient,26.1,0,0
HB-042868,City Hotel,1,72,2023,September,37,11,2023-09-11,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,126.0,0,0
HB-107387,City Hotel,0,8,2025,March,10,8,2025-03-08,0,4,1,0.0,0,BB,AGO,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,83.7,0,2
HB-113093,City Hotel,0,124,2025,May,22,30,2025-05-30,0,3,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient-Party,177.0,0,0
HB-069692,City Hotel,1,65,2025,June,23,4,2025-06-04,2,0,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,1
HB-070829,City Hotel,1,53,2025,June,26,23,2025-06-23,1,2,2,0.0,0,SC,LUX,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.67,0,1
HB-119342,City Hotel,0,181,2025,August,35,29,2025-08-29,0,5,1,0.0,0,BB,DNK,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.9,0,2
HB-001141,Resort Hotel,1,98,2023,August,33,15,2023-08-15,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,132.6,0,1
HB-067842,City Hotel,1,97,2025,May,19,8,2025-05-08,1,2,2,0.0,0,SC,HRV,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,79.0,0,1
HB-117973,City Hotel,0,125,2025,August,32,9,2025-08-09,0,4,2,0.0,0,BB,USA,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,112.5,0,2
HB-065970,City Hotel,1,170,2025,April,15,11,2025-04-11,0,4,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,193.5,0,2
HB-081591,City Hotel,1,197,2024,June,23,3,2024-06-03,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,21.0,,25,Transient,80.0,0,0
HB-014965,Resort Hotel,0,4,2025,February,6,6,2025-02-06,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,2,A,D,0,No Deposit,,120.0,0,Transient,42.0,1,1
HB-071986,City Hotel,1,155,2025,July,29,17,2025-07-17,1,1,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,1
HB-013192,Resort Hotel,1,353,2025,August,32,4,2025-08-04,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,138.38,0,1
HB-071706,City Hotel,1,181,2025,July,28,10,2025-07-10,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,120.6,0,0
HB-024170,Resort Hotel,0,468,2024,May,19,12,2024-05-12,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,E,0,No Deposit,249.0,,0,Transient-Party,67.0,0,0
HB-102141,City Hotel,0,215,2024,November,47,21,2024-11-21,1,1,2,0.0,0,BB,ESP,Groups,Corporate,0,0,0,A,A,1,No Deposit,,233.0,0,Transient,85.0,0,1
HB-070600,City Hotel,1,210,2025,June,25,19,2025-06-19,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,154.0,,0,Transient,130.0,0,0
HB-055424,City Hotel,1,76,2024,August,33,13,2024-08-13,0,1,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,207.9,0,0
HB-104872,City Hotel,0,17,2025,January,4,22,2025-01-22,2,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,79.0,1,0
HB-047259,City Hotel,1,38,2024,February,7,13,2024-02-13,2,1,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,67.5,0,0
HB-055298,City Hotel,1,186,2024,August,32,10,2024-08-10,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,118.8,0,1
HB-071492,City Hotel,1,49,2025,July,27,6,2025-07-06,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,80.1,0,0
HB-004896,Resort Hotel,1,85,2024,April,14,7,2024-04-07,0,3,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,67.0,,0,Transient-Party,64.0,0,0
HB-061908,City Hotel,1,16,2024,December,52,28,2024-12-28,2,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,76.67,0,0
HB-010371,Resort Hotel,1,240,2025,March,9,1,2025-03-01,4,10,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,26.64,0,0
HB-096883,City Hotel,0,13,2024,September,37,9,2024-09-09,0,1,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,139.0,0,2
HB-114830,City Hotel,0,93,2025,June,25,22,2025-06-22,2,3,2,0.0,0,BB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,85.0,0,0
HB-016169,Resort Hotel,0,21,2023,August,32,10,2023-08-10,2,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,241.0,0,1
HB-057899,City Hotel,1,12,2024,October,40,3,2024-10-03,1,1,2,0.0,0,SC,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.0,0,0
HB-032118,Resort Hotel,0,4,2025,January,3,17,2025-01-17,0,0,1,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,A,E,0,No Deposit,,,0,Transient-Party,0.0,0,0
HB-010089,Resort Hotel,1,1,2025,February,7,11,2025-02-11,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,48.0,0,0
HB-040391,City Hotel,1,132,2023,July,29,23,2023-07-23,1,3,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,85.0,0,0
HB-054433,City Hotel,1,200,2024,July,29,15,2024-07-15,3,7,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.95,0,1
HB-062844,City Hotel,1,59,2025,January,4,23,2025-01-23,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,326.0,,0,Transient,80.0,0,0
HB-056291,City Hotel,1,119,2024,September,36,2,2024-09-02,2,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,131.4,0,0
HB-078316,City Hotel,1,27,2024,June,26,29,2024-06-29,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,11,A,A,1,No Deposit,,40.0,0,Transient,65.0,0,0
HB-103569,City Hotel,0,208,2024,December,52,27,2024-12-27,0,1,2,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,220.0,,167,Transient-Party,81.0,0,1
HB-048758,City Hotel,1,112,2024,March,13,30,2024-03-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,64.0,0,0
HB-106063,City Hotel,0,197,2025,July,30,21,2025-07-21,1,2,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,1,D,D,0,No Deposit,7.0,,0,Transient,125.96,0,1
HB-099794,City Hotel,0,38,2024,October,42,15,2024-10-15,2,1,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,157.33,0,0
HB-089074,City Hotel,0,81,2024,May,20,15,2024-05-15,2,0,2,0.0,0,BB,CN,Groups,TA/TO,0,0,0,A,B,0,No Deposit,133.0,,0,Transient-Party,90.0,0,1
HB-059575,City Hotel,1,54,2024,October,44,29,2024-10-29,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,B,B,0,Non Refund,132.0,,0,Transient,95.0,0,1
HB-054677,City Hotel,1,9,2024,July,30,23,2024-07-23,0,1,2,1.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,169.0,0,0
HB-042605,City Hotel,0,0,2023,September,36,8,2023-09-08,0,1,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,114.0,0,0
HB-003308,Resort Hotel,1,66,2023,December,49,5,2023-12-05,1,1,2,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,155.0,,0,Transient-Party,64.0,0,0
HB-064521,City Hotel,1,9,2025,March,11,11,2025-03-11,2,3,2,0.0,0,BB,TUR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,103.7,0,0
HB-092045,City Hotel,0,119,2024,June,26,26,2024-06-26,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient-Party,83.83,0,1
HB-100511,City Hotel,0,2,2024,October,43,25,2024-10-25,0,4,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,109.38,0,1
HB-039253,Resort Hotel,0,128,2025,August,31,3,2025-08-03,2,8,3,0.0,0,HB,PRT,Direct,Direct,0,0,0,F,F,1,No Deposit,250.0,,0,Transient,368.1,1,1
HB-089684,City Hotel,0,0,2024,May,21,24,2024-05-24,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,9.0,,0,Transient,141.0,0,0
HB-034871,Resort Hotel,0,170,2025,April,14,1,2025-04-01,2,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,77.71,1,2
HB-050605,City Hotel,1,204,2024,May,18,5,2024-05-05,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,34.0,,96,Transient,100.0,0,0
HB-038666,Resort Hotel,0,220,2025,July,27,4,2025-07-04,6,16,3,0.0,0,BB,BEL,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,142.97,0,0
HB-023302,Resort Hotel,0,55,2024,April,16,17,2024-04-17,2,2,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,58.0,0,1
HB-021282,Resort Hotel,0,0,2024,February,8,22,2024-02-22,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,0
HB-040434,City Hotel,0,16,2023,July,30,25,2023-07-25,2,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,86.0,0,0
HB-014753,Resort Hotel,1,259,2023,September,37,17,2023-09-17,0,3,1,0.0,0,BB,GBR,Groups,Corporate,0,1,0,A,A,0,Non Refund,,223.0,0,Transient,33.3,0,0
HB-008389,Resort Hotel,1,310,2024,September,39,25,2024-09-25,4,10,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,75.0,,0,Contract,76.5,0,0
HB-096267,City Hotel,0,12,2024,August,35,30,2024-08-30,0,1,3,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,28.0,,0,Transient,138.0,0,0
HB-045853,City Hotel,0,98,2023,November,47,23,2023-11-23,1,3,1,0.0,0,BB,IND,Groups,TA/TO,0,0,0,A,A,1,No Deposit,37.0,,0,Transient-Party,70.0,0,0
HB-076106,City Hotel,1,364,2023,October,42,16,2023-10-16,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-061226,City Hotel,1,12,2024,December,49,5,2024-12-05,1,0,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,0
HB-106611,City Hotel,0,32,2025,February,9,25,2025-02-25,2,1,2,2.0,0,HB,ESP,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,203.0,0,2
HB-082970,City Hotel,0,3,2024,May,20,19,2024-05-19,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,1,0,11,A,A,0,No Deposit,94.0,,0,Transient-Party,45.0,0,2
HB-067156,City Hotel,1,181,2025,April,18,29,2025-04-29,1,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,0
HB-038830,Resort Hotel,0,28,2025,July,30,27,2025-07-27,1,3,2,0.0,0,BB,LUX,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,219.0,0,3
HB-012149,Resort Hotel,1,223,2025,June,24,15,2025-06-15,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,315.0,,0,Contract,81.9,0,0
HB-084635,City Hotel,0,115,2024,February,9,27,2024-02-27,2,2,2,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,134.0,,0,Transient-Party,87.0,0,0
HB-103886,City Hotel,0,0,2024,December,52,29,2024-12-29,1,3,1,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,220.0,,0,Transient-Party,65.0,0,0
HB-066815,City Hotel,1,88,2025,April,17,26,2025-04-26,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,170.0,,0,Transient,140.0,0,0
HB-087017,City Hotel,0,170,2024,April,15,8,2024-04-08,2,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,78.0,0,0
HB-063276,City Hotel,1,58,2025,February,6,4,2025-02-04,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.1,0,0
HB-099601,City Hotel,0,34,2024,October,41,13,2024-10-13,0,2,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,E,E,2,No Deposit,14.0,,0,Transient,175.5,0,0
HB-023830,Resort Hotel,0,0,2024,May,18,4,2024-05-04,0,1,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,60.83,0,0
HB-021852,Resort Hotel,0,24,2024,March,10,5,2024-03-05,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,115.0,,0,Transient,33.3,0,0
HB-071210,City Hotel,1,102,2025,June,26,29,2025-06-29,1,3,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,144.0,0,0
HB-066033,City Hotel,1,245,2025,April,15,13,2025-04-13,0,3,2,0.0,0,SC,CYP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,1
HB-108375,City Hotel,0,99,2025,March,12,23,2025-03-23,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,106.2,0,1
HB-032400,Resort Hotel,0,1,2025,January,4,25,2025-01-25,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,43.0,0,0
HB-035416,Resort Hotel,0,30,2025,April,17,21,2025-04-21,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,169.0,0,Transient-Party,50.0,0,0
HB-008248,Resort Hotel,1,297,2024,September,38,19,2024-09-19,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,315.0,,0,Transient,88.9,0,1
HB-031305,Resort Hotel,0,5,2025,February,8,20,2025-02-20,1,3,1,0.0,0,BB,PRT,Online TA,TA/TO,1,0,1,A,A,0,No Deposit,241.0,,0,Transient,33.65,0,2
HB-094979,City Hotel,0,221,2024,August,33,12,2024-08-12,0,1,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,147,Transient-Party,48.0,0,1
HB-099443,City Hotel,0,180,2024,October,41,10,2024-10-10,1,2,1,0.0,0,BB,USA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,234.0,,0,Transient-Party,120.0,0,0
HB-028653,Resort Hotel,0,3,2024,October,41,8,2024-10-08,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,240.0,,0,Transient-Party,80.0,0,0
HB-107515,City Hotel,0,73,2025,March,11,11,2025-03-11,2,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,106.2,0,2
HB-002311,Resort Hotel,0,21,2023,October,41,9,2023-10-09,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,67.0,0,1
HB-081222,City Hotel,0,40,2023,December,49,5,2023-12-05,1,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,9.0,,0,Transient,115.2,1,0
HB-074821,City Hotel,1,335,2023,September,37,17,2023-09-17,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,5.0,,0,Transient,85.0,0,0
HB-016608,Resort Hotel,0,55,2023,August,35,30,2023-08-30,2,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,119.0,0,1
HB-012526,Resort Hotel,1,178,2025,July,27,3,2025-07-03,1,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,155.83,0,0
HB-054973,City Hotel,1,37,2024,August,31,1,2024-08-01,1,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.9,0,0
HB-070358,City Hotel,1,320,2025,June,24,15,2025-06-15,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient,90.0,0,0
HB-063485,City Hotel,1,67,2025,February,7,12,2025-02-12,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,80.0,0,0
HB-092013,City Hotel,0,1,2024,June,26,28,2024-06-28,0,1,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,127.0,0,1
HB-076291,City Hotel,1,147,2023,July,29,21,2023-07-21,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient,64.5,0,0
HB-026857,Resort Hotel,0,16,2024,August,32,10,2024-08-10,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,227.1,1,0
HB-073055,City Hotel,1,39,2025,August,33,13,2025-08-13,2,1,3,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,210.0,0,0
HB-092312,City Hotel,0,154,2024,June,26,29,2024-06-29,1,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient-Party,72.25,0,1
HB-005556,Resort Hotel,0,199,2024,May,18,2,2024-05-02,1,1,1,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,1,No Deposit,298.0,,0,Transient-Party,54.5,0,0
HB-036298,Resort Hotel,0,2,2025,May,20,15,2025-05-15,1,0,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,82.0,1,2
HB-048209,City Hotel,0,94,2024,March,12,18,2024-03-18,1,2,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,87.3,0,1
HB-088245,City Hotel,0,0,2024,May,18,2,2024-05-02,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,139.0,0,0
HB-015226,Resort Hotel,1,160,2023,August,31,3,2023-08-03,1,3,2,0.0,0,BB,PRT,Direct,Direct,0,1,0,F,F,0,No Deposit,250.0,,0,Transient,164.15,0,1
HB-111574,City Hotel,0,155,2025,May,20,12,2025-05-12,0,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,144.0,0,1
HB-092296,City Hotel,0,132,2024,July,27,1,2024-07-01,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,72.25,0,0
HB-084137,City Hotel,0,99,2024,February,8,19,2024-02-19,0,1,1,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,A,0,No Deposit,,67.0,0,Transient-Party,80.0,0,0
HB-050058,City Hotel,1,142,2024,April,17,22,2024-04-22,2,3,1,0.0,0,BB,POL,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,89.0,0,0
HB-057762,City Hotel,1,267,2024,September,40,30,2024-09-30,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,26.0,,0,Transient,95.0,0,0
HB-069812,City Hotel,1,134,2025,June,23,7,2025-06-07,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,110.0,0,0
HB-002535,Resort Hotel,1,28,2023,October,42,21,2023-10-21,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,208.0,,0,Transient-Party,0.0,0,0
HB-022677,Resort Hotel,0,96,2024,March,12,24,2024-03-24,2,6,2,0.0,0,BB,AUS,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,47.56,0,2
HB-075116,City Hotel,1,344,2023,September,39,26,2023-09-26,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-055371,City Hotel,1,142,2024,August,32,11,2024-08-11,0,3,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,146.7,0,0
HB-064400,City Hotel,1,608,2025,March,10,9,2025-03-09,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,59.0,0,0
HB-024638,Resort Hotel,0,39,2024,May,21,25,2024-05-25,0,3,3,1.0,0,BB,BRA,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,140.0,0,0
HB-009755,Resort Hotel,1,72,2024,December,1,30,2024-12-30,1,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,159.0,0,0
HB-110210,City Hotel,0,19,2025,April,16,19,2025-04-19,1,4,2,0.0,0,HB,FRA,Direct,Direct,0,0,0,D,D,1,No Deposit,14.0,,0,Transient,176.0,0,0
HB-038763,Resort Hotel,0,149,2025,July,30,25,2025-07-25,0,4,2,0.0,0,HB,POL,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,245.0,0,1
HB-107689,City Hotel,0,21,2025,March,11,15,2025-03-15,0,2,1,0.0,0,SC,DEU,Online TA,GDS,0,0,0,A,A,0,No Deposit,195.0,,0,Transient,92.5,0,0
HB-040547,City Hotel,1,106,2023,July,30,29,2023-07-29,2,5,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,106.75,0,2
HB-023296,Resort Hotel,0,2,2024,April,16,20,2024-04-20,0,1,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,240.0,,0,Transient-Party,65.0,0,1
HB-051845,City Hotel,1,316,2024,May,21,26,2024-05-26,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,110.0,0,0
HB-067912,City Hotel,1,410,2025,May,19,9,2025-05-09,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-077012,City Hotel,0,188,2023,August,34,23,2023-08-23,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,89.25,0,1
HB-069342,City Hotel,1,25,2025,May,22,30,2025-05-30,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,90.0,0,0
HB-093357,City Hotel,0,60,2024,July,29,20,2024-07-20,0,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,81.08,0,1
HB-108764,City Hotel,0,23,2025,March,13,29,2025-03-29,0,3,1,0.0,0,BB,CZE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,128.0,0,1
HB-037344,Resort Hotel,0,0,2025,June,24,14,2025-06-14,0,1,2,0.0,0,BB,CHN,Online TA,TA/TO,1,0,0,D,D,0,No Deposit,240.0,,0,Transient,155.0,0,0
HB-088355,City Hotel,0,27,2024,May,18,4,2024-05-04,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,85.0,0,0
HB-033070,Resort Hotel,0,5,2025,February,7,11,2025-02-11,2,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,60.0,0,2
HB-021218,Resort Hotel,0,31,2024,February,7,18,2024-02-18,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,56.0,0,1
HB-074001,City Hotel,1,293,2023,August,31,6,2023-08-06,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-106812,City Hotel,0,63,2025,February,9,27,2025-02-27,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,A,1,No Deposit,9.0,,0,Transient,116.45,0,2
HB-091395,City Hotel,0,134,2024,June,24,15,2024-06-15,2,4,2,1.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.15,0,2
HB-069889,City Hotel,1,183,2025,June,23,8,2025-06-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,86.0,,0,Transient,120.0,0,0
HB-021873,Resort Hotel,0,23,2024,March,10,9,2024-03-09,0,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,58.0,0,0
HB-059011,City Hotel,1,468,2024,October,42,20,2024-10-20,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-092575,City Hotel,0,116,2024,July,27,7,2024-07-07,0,2,2,0.0,0,BB,NOR,Direct,Direct,0,0,0,A,A,2,No Deposit,14.0,,0,Transient,125.0,0,0
HB-051885,City Hotel,0,316,2024,May,21,26,2024-05-26,0,3,2,0.0,0,BB,AUT,Groups,TA/TO,0,0,0,A,D,0,No Deposit,30.0,,0,Transient-Party,110.0,0,0
HB-110286,City Hotel,0,236,2025,April,16,18,2025-04-18,2,5,2,0.0,0,SC,FIN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,99.0,0,1
HB-002636,Resort Hotel,1,148,2023,October,43,24,2023-10-24,0,1,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,47.0,0,0
HB-048432,City Hotel,1,5,2024,March,12,23,2024-03-23,0,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,101.0,0,0
HB-087622,City Hotel,0,26,2024,April,16,18,2024-04-18,1,4,2,0.0,0,HB,MAR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,133.8,0,0
HB-116049,City Hotel,0,468,2025,July,31,29,2025-07-29,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,1,A,A,1,No Deposit,229.0,,0,Group,0.0,0,0
HB-030218,Resort Hotel,0,15,2024,November,46,16,2024-11-16,0,1,2,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,56.0,1,0
HB-076603,City Hotel,0,138,2023,July,30,25,2023-07-25,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,60.0,0,0
HB-071123,City Hotel,1,368,2025,June,26,28,2025-06-28,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-061066,City Hotel,1,290,2024,December,48,1,2024-12-01,1,3,2,0.0,0,BB,SVK,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,73.95,0,0
HB-055828,City Hotel,1,37,2024,August,34,22,2024-08-22,1,2,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,207.9,0,2
HB-087626,City Hotel,0,62,2024,April,17,22,2024-04-22,0,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,91.48,0,1
HB-072874,City Hotel,1,324,2025,August,32,8,2025-08-08,0,5,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,2
HB-090689,City Hotel,0,118,2024,June,23,6,2024-06-06,1,3,1,0.0,0,BB,TUR,Offline TA/TO,Corporate,0,0,0,A,E,2,No Deposit,191.0,,0,Transient-Party,110.0,0,0
HB-025684,Resort Hotel,0,17,2024,July,27,4,2024-07-04,1,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,179.1,0,0
HB-103095,City Hotel,0,89,2024,December,50,10,2024-12-10,1,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,104.0,0,2
HB-086434,City Hotel,0,50,2024,March,13,31,2024-03-31,0,3,2,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,65.0,0,0
HB-041241,City Hotel,0,39,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-041342,City Hotel,0,150,2023,August,33,14,2023-08-14,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,1
HB-046354,City Hotel,1,160,2023,December,52,30,2023-12-30,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,111,Transient-Party,70.0,0,0
HB-099733,City Hotel,0,377,2024,October,42,14,2024-10-14,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-054215,City Hotel,1,154,2024,July,28,9,2024-07-09,0,1,3,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,146.7,0,0
HB-067423,City Hotel,1,152,2025,May,18,3,2025-05-03,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,286.0,,0,Transient,100.0,0,0
HB-073752,City Hotel,1,265,2023,July,27,9,2023-07-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-031159,Resort Hotel,0,41,2024,December,50,12,2024-12-12,1,4,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,250.0,,0,Transient,74.88,1,0
HB-088111,City Hotel,0,59,2024,April,17,28,2024-04-28,0,3,2,0.0,0,BB,CHE,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,168.0,,0,Transient,80.75,0,0
HB-104540,City Hotel,0,121,2025,January,2,10,2025-01-10,1,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,88.4,0,1
HB-040192,City Hotel,1,94,2023,July,28,14,2023-07-14,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,1
HB-018802,Resort Hotel,0,4,2023,November,48,27,2023-11-27,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,54.0,1,2
HB-028842,Resort Hotel,0,1,2024,October,41,11,2024-10-11,0,1,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,103.0,1,1
HB-058990,City Hotel,1,468,2024,October,42,20,2024-10-20,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-119167,City Hotel,0,0,2025,August,35,30,2025-08-30,0,1,1,0.0,0,BB,BRA,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,140.0,0,0
HB-068776,City Hotel,1,113,2025,May,21,20,2025-05-20,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,34.0,,0,Transient,190.0,0,0
HB-055489,City Hotel,1,66,2024,August,33,14,2024-08-14,2,1,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,207.9,0,0
HB-018987,Resort Hotel,0,8,2023,November,45,7,2023-11-07,8,20,2,0.0,0,Undefined,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,332.0,,0,Transient,65.0,0,0
HB-048517,City Hotel,1,37,2024,March,13,25,2024-03-25,0,1,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,143.1,0,1
HB-092401,City Hotel,0,37,2024,July,27,2,2024-07-02,2,2,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,8.0,,0,Transient,146.7,0,1
HB-108625,City Hotel,0,39,2025,March,13,26,2025-03-26,2,2,1,0.0,0,BB,SAU,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,7.0,,0,Transient,71.38,0,0
HB-030293,Resort Hotel,0,19,2024,November,46,15,2024-11-15,0,4,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient,30.6,0,0
HB-102908,City Hotel,0,4,2024,December,49,7,2024-12-07,0,2,1,0.0,0,BB,SVN,Online TA,TA/TO,0,0,0,A,K,0,No Deposit,7.0,,0,Transient,75.08,0,1
HB-063109,City Hotel,1,43,2025,February,5,1,2025-02-01,0,2,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,0
HB-077892,City Hotel,0,18,2023,September,39,27,2023-09-27,2,1,1,0.0,0,BB,ITA,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,170.0,0,0
HB-078466,City Hotel,0,2,2023,October,41,9,2023-10-09,0,1,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,91.0,0,0
HB-074297,City Hotel,1,330,2023,September,37,12,2023-09-12,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-017614,Resort Hotel,0,287,2023,October,41,15,2023-10-15,0,3,2,0.0,0,BB,BEL,Groups,Corporate,0,0,0,A,A,1,No Deposit,,223.0,0,Transient-Party,44.5,0,0
HB-081853,City Hotel,1,178,2024,April,17,28,2024-04-28,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,46,Transient,110.0,0,0
HB-041589,City Hotel,0,10,2023,August,33,18,2023-08-18,0,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,81.0,0,2
HB-051453,City Hotel,1,211,2024,May,21,20,2024-05-20,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,111,Transient,100.0,0,0
HB-034432,Resort Hotel,0,160,2025,March,12,18,2025-03-18,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,55.8,0,3
HB-032085,Resort Hotel,0,2,2025,May,21,22,2025-05-22,1,0,2,0.0,0,BB,PRT,Direct,TA/TO,1,0,3,C,C,0,No Deposit,,,0,Transient,105.0,0,1
HB-073976,City Hotel,1,286,2023,July,30,30,2023-07-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-060262,City Hotel,1,277,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-065566,City Hotel,1,373,2025,April,14,5,2025-04-05,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-102590,City Hotel,0,30,2024,November,48,30,2024-11-30,0,2,3,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,22.0,,0,Transient,98.1,0,0
HB-107768,City Hotel,0,65,2025,March,11,13,2025-03-13,1,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,67.15,0,2
HB-093359,City Hotel,0,53,2024,July,29,18,2024-07-18,1,2,2,0.0,0,SC,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,72.76,0,2
HB-082463,City Hotel,0,46,2023,December,52,26,2023-12-26,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,10.0,,0,Transient,78.0,0,2
HB-001033,Resort Hotel,1,31,2023,August,32,11,2023-08-11,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,211.0,0,2
HB-065558,City Hotel,1,373,2025,April,14,5,2025-04-05,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-091043,City Hotel,0,8,2024,June,24,13,2024-06-13,1,2,1,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.33,0,1
HB-040595,City Hotel,0,2,2023,August,31,2,2023-08-02,1,0,1,0.0,0,BB,AGO,Complementary,Direct,0,0,0,E,D,0,No Deposit,,,0,Transient,0.0,0,0
HB-103449,City Hotel,0,0,2024,December,52,23,2024-12-23,0,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,89.0,1,2
HB-016671,Resort Hotel,0,189,2023,August,35,31,2023-08-31,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,40.0,,0,Transient,104.98,0,0
HB-107399,City Hotel,0,45,2025,March,11,10,2025-03-10,0,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,74.39,0,0
HB-035272,Resort Hotel,0,86,2025,April,15,12,2025-04-12,1,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,115.0,0,1
HB-089428,City Hotel,0,2,2024,May,21,20,2024-05-20,0,1,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,197.0,1,0
HB-004237,Resort Hotel,0,123,2024,February,9,27,2024-02-27,1,1,2,0.0,0,FB,ESP,Groups,Direct,0,0,0,A,A,0,No Deposit,38.0,,0,Transient-Party,64.0,0,0
HB-087274,City Hotel,0,8,2024,April,15,14,2024-04-14,0,3,2,0.0,0,SC,ESP,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,115.0,0,1
HB-011322,Resort Hotel,1,83,2025,May,18,3,2025-05-03,0,4,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,147.0,0,0
HB-029291,Resort Hotel,0,3,2024,October,43,24,2024-10-24,1,0,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,37.31,0,1
HB-025135,Resort Hotel,0,27,2024,August,34,23,2024-08-23,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,D,0,No Deposit,,154.0,0,Transient,115.0,0,0
HB-076355,City Hotel,0,273,2023,July,29,17,2023-07-17,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-067820,City Hotel,1,88,2025,May,19,8,2025-05-08,1,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,170.0,,0,Transient,120.0,0,0
HB-051581,City Hotel,1,40,2024,May,21,21,2024-05-21,2,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.9,0,0
HB-085650,City Hotel,0,87,2024,March,11,14,2024-03-14,1,4,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,72.25,0,2
HB-063582,City Hotel,1,97,2025,February,7,14,2025-02-14,0,4,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.6,0,1
HB-072557,City Hotel,1,98,2025,July,31,31,2025-07-31,1,0,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,3,No Deposit,9.0,,0,Transient,155.0,0,1
HB-074970,City Hotel,1,257,2023,July,26,1,2023-07-01,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,6.0,,0,Transient,101.5,0,0
HB-071106,City Hotel,1,368,2025,June,26,28,2025-06-28,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-075965,City Hotel,1,301,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-022687,Resort Hotel,0,108,2024,April,14,1,2024-04-01,0,1,2,0.0,0,BB,AUS,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient,47.4,1,1
HB-068013,City Hotel,1,119,2025,May,19,11,2025-05-11,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,148.8,0,1
HB-097168,City Hotel,0,18,2024,September,37,12,2024-09-12,1,0,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.0,0,0
HB-114981,City Hotel,0,78,2025,June,26,28,2025-06-28,0,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,89.1,0,0
HB-047178,City Hotel,0,39,2024,February,6,11,2024-02-11,2,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.3,0,1
HB-065744,City Hotel,1,60,2025,April,15,7,2025-04-07,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-048062,City Hotel,1,55,2024,March,11,15,2024-03-15,0,3,2,1.0,0,BB,GBR,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,96.9,0,0
HB-030954,Resort Hotel,0,34,2024,December,50,9,2024-12-09,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-059180,City Hotel,1,78,2024,October,43,21,2024-10-21,2,2,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,132.3,0,0
HB-082734,City Hotel,0,101,2024,January,1,1,2024-01-01,2,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Transient,62.0,0,0
HB-081605,City Hotel,0,5,2024,June,24,13,2024-06-13,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,6,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,1
HB-045386,City Hotel,0,72,2023,October,43,28,2023-10-28,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,D,0,No Deposit,37.0,,58,Transient-Party,85.67,0,0
HB-001824,Resort Hotel,0,104,2023,September,37,16,2023-09-16,1,4,2,0.0,0,BB,CHL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,66.6,0,0
HB-083729,City Hotel,0,26,2024,February,6,7,2024-02-07,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,64.64,0,0
HB-090235,City Hotel,0,1,2024,June,22,2,2024-06-02,0,2,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,1,No Deposit,,174.0,0,Transient-Party,119.0,0,1
HB-018312,Resort Hotel,0,12,2023,November,46,16,2023-11-16,1,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,15.0,,0,Transient,25.0,0,0
HB-000802,Resort Hotel,1,31,2023,July,30,30,2023-07-30,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,242.0,,0,Transient,154.0,0,2
HB-012203,Resort Hotel,1,250,2025,June,25,17,2025-06-17,4,6,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,143.0,,0,Transient,56.7,0,0
HB-015644,Resort Hotel,1,239,2023,August,35,29,2023-08-29,4,10,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,143.0,,0,Contract,110.5,0,2
HB-037899,Resort Hotel,0,274,2025,June,26,24,2025-06-24,2,6,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,81.76,1,1
HB-090039,City Hotel,0,6,2024,May,22,31,2024-05-31,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,1,No Deposit,,40.0,0,Transient,65.0,0,0
HB-078857,City Hotel,0,289,2023,October,42,17,2023-10-17,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,21.0,,0,Transient-Party,0.0,0,0
HB-058640,City Hotel,1,37,2024,October,41,13,2024-10-13,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,105.0,0,0
HB-005410,Resort Hotel,1,168,2024,April,17,28,2024-04-28,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,257.0,,0,Transient,80.0,0,0
HB-093371,City Hotel,0,179,2024,July,29,17,2024-07-17,2,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.95,0,1
HB-056079,City Hotel,1,35,2024,August,35,28,2024-08-28,2,2,2,0.0,0,BB,GEO,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,111.83,0,0
HB-111433,City Hotel,0,96,2025,May,19,9,2025-05-09,0,2,2,0.0,0,SC,RUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,0
HB-103359,City Hotel,0,13,2024,December,51,19,2024-12-19,1,1,1,0.0,0,SC,DEU,Online TA,GDS,0,0,0,A,A,0,No Deposit,195.0,,0,Transient,78.0,0,0
HB-030912,Resort Hotel,0,7,2024,December,49,4,2024-12-04,2,2,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,81.75,1,0
HB-008424,Resort Hotel,0,542,2024,September,39,26,2024-09-26,2,5,3,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,A,C,1,No Deposit,253.0,,0,Transient-Party,99.0,0,0
HB-095671,City Hotel,0,16,2024,August,34,19,2024-08-19,1,2,2,2.0,0,HB,FRA,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,9.0,,0,Transient,283.67,1,1
HB-046297,City Hotel,1,146,2023,December,52,29,2023-12-29,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,99,Transient-Party,85.0,0,0
HB-105255,City Hotel,0,1,2025,January,5,29,2025-01-29,2,4,2,1.0,0,BB,TUR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.8,0,2
HB-038693,Resort Hotel,0,125,2025,July,28,13,2025-07-13,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,104.85,0,0
HB-053200,City Hotel,1,350,2024,June,25,17,2024-06-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,140.0,0,0
HB-019409,Resort Hotel,0,0,2024,January,1,4,2024-01-04,1,3,1,0.0,0,HB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,110.0,0,Transient-Party,40.0,0,1
HB-055644,City Hotel,1,107,2024,August,33,18,2024-08-18,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient-Party,135.27,0,0
HB-112341,City Hotel,0,75,2025,May,21,20,2025-05-20,2,1,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,2
HB-060591,City Hotel,1,89,2024,November,46,16,2024-11-16,0,4,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,57.6,0,0
HB-083021,City Hotel,0,5,2024,January,2,13,2024-01-13,0,1,1,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,65.0,0,0
HB-045165,City Hotel,0,40,2023,October,42,19,2023-10-19,1,5,2,0.0,0,BB,HRV,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,104.85,0,1
HB-042383,City Hotel,1,65,2023,September,36,5,2023-09-05,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-114458,City Hotel,0,0,2025,June,25,21,2025-06-21,0,1,2,0.0,0,BB,ZAF,Online TA,TA/TO,0,0,0,A,G,0,No Deposit,9.0,,0,Transient,162.0,0,0
HB-081331,City Hotel,0,3,2023,December,48,3,2023-12-03,2,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,58.0,0,0
HB-109653,City Hotel,0,110,2025,April,15,9,2025-04-09,2,4,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,102.0,0,1
HB-042980,City Hotel,1,65,2023,September,37,12,2023-09-12,2,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,86.0,0,0
HB-103882,City Hotel,0,15,2024,December,52,27,2024-12-27,1,5,2,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,220.0,,0,Transient-Party,70.0,0,1
HB-032047,Resort Hotel,0,1,2025,May,20,12,2025-05-12,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,1,0,1,A,A,0,No Deposit,240.0,,0,Transient,92.25,0,1
HB-065726,City Hotel,1,26,2025,April,15,7,2025-04-07,0,1,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-005829,Resort Hotel,1,211,2024,May,20,14,2024-05-14,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,85.0,0,0
HB-111036,City Hotel,0,17,2025,May,18,2,2025-05-02,0,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,2
HB-024583,Resort Hotel,0,97,2024,May,21,22,2024-05-22,2,2,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,66.0,1,1
HB-070684,City Hotel,1,303,2025,June,25,20,2025-06-20,1,5,2,1.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,129.6,0,1
HB-072766,City Hotel,1,120,2025,August,32,5,2025-08-05,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,85.0,,0,Transient,111.6,0,0
HB-021897,Resort Hotel,0,4,2024,March,11,13,2024-03-13,2,1,2,2.0,0,BB,ITA,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,93.0,1,0
HB-024054,Resort Hotel,0,31,2024,May,19,10,2024-05-10,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,75.0,0,1
HB-059464,City Hotel,1,247,2024,October,44,28,2024-10-28,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,110.0,0,0
HB-075199,City Hotel,1,292,2023,August,31,5,2023-08-05,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,60.0,0,0
HB-079287,City Hotel,0,24,2023,October,42,19,2023-10-19,1,4,3,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,28.0,,0,Group,105.0,0,0
HB-099403,City Hotel,0,125,2024,October,41,9,2024-10-09,2,2,0,2.0,0,BB,DEU,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient,110.7,0,4
HB-076105,City Hotel,1,364,2023,October,42,16,2023-10-16,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-093439,City Hotel,0,143,2024,July,29,18,2024-07-18,1,3,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,E,E,1,Non Refund,,51.0,0,Transient-Party,106.0,0,0
HB-049652,City Hotel,0,137,2024,April,16,17,2024-04-17,1,0,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,94.5,0,0
HB-102847,City Hotel,0,7,2024,December,49,6,2024-12-06,0,1,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient-Party,18.0,0,1
HB-063218,City Hotel,1,4,2025,February,5,2,2025-02-02,0,2,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,158.0,0,2
HB-057255,City Hotel,1,440,2024,September,38,22,2024-09-22,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-004960,Resort Hotel,0,275,2024,April,15,10,2024-04-10,2,5,2,0.0,0,HB,GBR,Groups,Direct,0,0,0,D,D,0,No Deposit,273.0,,0,Transient-Party,74.45,0,0
HB-007750,Resort Hotel,1,44,2024,August,34,24,2024-08-24,1,4,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,248.0,0,1
HB-084255,City Hotel,0,39,2024,February,8,19,2024-02-19,0,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,75.8,0,1
HB-038493,Resort Hotel,0,199,2025,July,29,15,2025-07-15,2,3,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,150.0,0,1
HB-020954,Resort Hotel,0,61,2024,February,5,4,2024-02-04,2,8,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,115.0,,0,Transient,42.5,0,0
HB-041417,City Hotel,0,131,2023,August,33,15,2023-08-15,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-039247,Resort Hotel,0,0,2025,August,33,11,2025-08-11,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,1,0,0,A,A,0,No Deposit,240.0,,0,Transient,190.0,0,1
HB-006506,Resort Hotel,0,223,2024,June,24,13,2024-06-13,2,5,1,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,314.0,,0,Transient,53.12,0,0
HB-088410,City Hotel,0,88,2024,May,18,3,2024-05-03,0,3,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,117.0,0,1
HB-118335,City Hotel,0,2,2025,August,33,16,2025-08-16,0,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,128.0,0,0
HB-009092,Resort Hotel,1,206,2024,October,43,27,2024-10-27,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,8,No Deposit,240.0,,0,Transient,53.79,0,1
HB-086600,City Hotel,0,78,2024,March,13,31,2024-03-31,2,4,2,0.0,0,BB,ARG,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,82.45,0,1
HB-063673,City Hotel,1,51,2025,February,8,17,2025-02-17,0,2,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,113.4,0,3
HB-110398,City Hotel,0,135,2025,April,17,24,2025-04-24,1,2,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,99.0,0,0
HB-077136,City Hotel,0,31,2024,November,46,13,2024-11-13,2,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,2,A,A,1,No Deposit,,40.0,0,Transient,67.0,1,0
HB-064365,City Hotel,1,154,2025,March,10,7,2025-03-07,0,4,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.4,0,1
HB-107508,City Hotel,0,56,2025,March,10,4,2025-03-04,3,6,1,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,100.3,0,1
HB-111232,City Hotel,0,147,2025,May,19,5,2025-05-05,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-109199,City Hotel,0,45,2025,April,15,7,2025-04-07,0,1,3,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,171.0,0,0
HB-102271,City Hotel,0,79,2024,November,47,19,2024-11-19,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,91.2,0,2
HB-009826,Resort Hotel,1,36,2025,January,2,7,2025-01-07,2,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,44.0,0,0
HB-067050,City Hotel,1,233,2025,April,17,27,2025-04-27,2,3,3,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,149.4,0,0
HB-045661,City Hotel,0,140,2023,November,46,18,2023-11-18,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,29.0,,87,Transient-Party,75.0,0,0
HB-060623,City Hotel,1,23,2024,November,46,17,2024-11-17,0,2,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,2
HB-068897,City Hotel,1,50,2025,May,21,22,2025-05-22,1,2,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,144.0,0,1
HB-083632,City Hotel,0,4,2024,February,6,7,2024-02-07,2,0,2,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,87.0,0,0
HB-068121,City Hotel,1,221,2025,May,20,13,2025-05-13,2,1,3,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,163.5,0,1
HB-111382,City Hotel,0,61,2025,May,19,6,2025-05-06,2,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,122.4,0,1
HB-107421,City Hotel,0,166,2025,March,11,10,2025-03-10,1,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,88.4,0,1
HB-114740,City Hotel,0,263,2025,June,26,23,2025-06-23,2,2,2,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,105.0,0,1
HB-033048,Resort Hotel,0,10,2025,February,7,12,2025-02-12,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-039441,Resort Hotel,0,140,2025,August,33,17,2025-08-17,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,231.0,0,2
HB-026597,Resort Hotel,0,1,2024,August,31,3,2024-08-03,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,196.0,,0,Transient,211.0,0,0
HB-100061,City Hotel,0,130,2024,October,43,21,2024-10-21,0,2,0,2.0,0,BB,IRL,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient,110.7,0,1
HB-031996,Resort Hotel,0,1,2025,January,3,13,2025-01-13,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-036111,Resort Hotel,0,46,2025,May,18,3,2025-05-03,2,5,2,0.0,0,HB,IRL,Direct,Direct,0,0,0,F,F,1,No Deposit,250.0,,0,Transient,163.71,0,0
HB-027172,Resort Hotel,0,91,2024,August,33,15,2024-08-15,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient-Party,199.0,0,1
HB-077091,City Hotel,0,17,2023,September,35,3,2023-09-03,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,B,B,0,No Deposit,14.0,,0,Transient,89.25,0,1
HB-026486,Resort Hotel,0,40,2024,July,30,28,2024-07-28,1,3,2,1.0,0,FB,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,339.0,,0,Transient,215.1,0,0
HB-102435,City Hotel,0,10,2024,November,48,25,2024-11-25,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.67,0,2
HB-096663,City Hotel,0,61,2024,September,36,2,2024-09-02,2,2,2,0.0,0,BB,DNK,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,118.8,1,1
HB-040530,City Hotel,1,81,2023,July,30,27,2023-07-27,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,1
HB-028559,Resort Hotel,0,14,2024,October,40,3,2024-10-03,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,2,No Deposit,6.0,,0,Transient,46.0,1,0
HB-119150,City Hotel,0,43,2025,August,35,29,2025-08-29,0,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,140.0,0,1
HB-011514,Resort Hotel,1,38,2025,May,20,13,2025-05-13,2,2,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,151.0,0,2
HB-076516,City Hotel,1,195,2023,September,37,17,2023-09-17,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,20.0,,0,Transient,48.0,0,0
HB-100760,City Hotel,0,242,2024,October,44,28,2024-10-28,2,2,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,95.13,0,1
HB-113734,City Hotel,0,214,2025,June,24,9,2025-06-09,0,2,1,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,96.25,0,0
HB-101621,City Hotel,0,19,2024,November,46,12,2024-11-12,2,1,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,119.33,0,2
HB-106930,City Hotel,0,84,2025,March,10,3,2025-03-03,0,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,2
HB-054443,City Hotel,1,135,2024,July,29,16,2024-07-16,1,1,2,1.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,83.0,,0,Transient,102.09,0,0
HB-112327,City Hotel,0,75,2025,May,21,21,2025-05-21,2,0,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,123.12,0,0
HB-036332,Resort Hotel,0,118,2025,May,19,10,2025-05-10,2,5,1,0.0,0,BB,IRL,Groups,TA/TO,0,0,0,A,A,0,No Deposit,96.0,,0,Transient-Party,42.0,0,0
HB-046838,City Hotel,0,41,2024,January,3,20,2024-01-20,0,4,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,62.0,0,0
HB-002663,Resort Hotel,1,99,2023,October,43,24,2023-10-24,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,65.0,0,2
HB-021948,Resort Hotel,0,1,2024,March,11,12,2024-03-12,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,64.0,1,0
HB-097087,City Hotel,0,58,2024,September,36,8,2024-09-08,1,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,16.0,,0,Transient,90.95,0,1
HB-048451,City Hotel,1,10,2024,March,12,23,2024-03-23,0,4,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,182.0,0,0
HB-006696,Resort Hotel,1,3,2024,June,26,25,2024-06-25,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,129.0,0,1
HB-073491,City Hotel,1,164,2025,August,34,24,2025-08-24,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.5,0,0
HB-066300,City Hotel,1,174,2025,April,16,16,2025-04-16,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,46,Transient,100.0,0,0
HB-119211,City Hotel,0,213,2025,August,35,28,2025-08-28,1,3,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,19.0,,0,Transient-Party,104.0,0,0
HB-005845,Resort Hotel,1,9,2024,May,20,15,2024-05-15,1,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,315.0,,0,Transient-Party,70.0,0,0
HB-043828,City Hotel,0,192,2023,September,39,25,2023-09-25,2,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,102.0,0,0
HB-073676,City Hotel,1,13,2025,August,35,30,2025-08-30,0,3,2,2.0,0,BB,RUS,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,246.33,0,0
HB-039251,Resort Hotel,0,46,2025,August,32,8,2025-08-08,0,5,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,508.0,,0,Transient-Party,243.81,0,4
HB-113472,City Hotel,0,14,2025,June,23,7,2025-06-07,0,1,1,0.0,0,BB,FRA,Corporate,Corporate,0,0,0,D,D,0,No Deposit,,227.0,0,Transient,130.5,0,0
HB-111370,City Hotel,0,116,2025,May,19,7,2025-05-07,2,1,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,89.1,0,0
HB-057063,City Hotel,1,26,2024,September,38,17,2024-09-17,2,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,152.33,0,2
HB-022633,Resort Hotel,0,8,2024,March,13,30,2024-03-30,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,0
HB-002006,Resort Hotel,0,136,2023,September,39,26,2023-09-26,2,5,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,36.0,,0,Transient,55.09,0,0
HB-049357,City Hotel,1,67,2024,April,15,11,2024-04-11,1,3,2,0.0,0,SC,FIN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.25,0,0
HB-101095,City Hotel,0,49,2024,November,44,2,2024-11-02,0,4,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-096288,City Hotel,0,1,2025,May,20,16,2025-05-16,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,2,A,D,0,No Deposit,,40.0,0,Transient,67.0,1,1
HB-084944,City Hotel,0,54,2024,March,10,5,2024-03-05,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,69.5,0,1
HB-041483,City Hotel,0,46,2023,August,33,17,2023-08-17,1,1,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-081856,City Hotel,1,178,2024,April,17,28,2024-04-28,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,46,Transient,110.0,0,0
HB-022312,Resort Hotel,0,63,2024,March,12,21,2024-03-21,1,1,1,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,C,A,0,No Deposit,242.0,,0,Transient,68.16,0,2
HB-031921,Resort Hotel,0,0,2025,January,2,11,2025-01-11,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,68.0,0,0
HB-045605,City Hotel,1,79,2023,November,46,13,2023-11-13,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,60.0,,69,Transient,75.0,0,0
HB-006752,Resort Hotel,1,208,2024,June,26,28,2024-06-28,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,143.0,,0,Transient,73.95,0,2
HB-085241,City Hotel,0,49,2024,March,10,4,2024-03-04,2,5,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,16.0,,0,Transient,65.0,0,0
HB-006374,Resort Hotel,0,282,2024,June,23,6,2024-06-06,1,3,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,E,G,0,No Deposit,240.0,,0,Transient,99.0,0,1
HB-101119,City Hotel,0,53,2024,November,45,4,2024-11-04,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,1
HB-107684,City Hotel,0,7,2025,March,11,14,2025-03-14,0,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.0,0,0
HB-089972,City Hotel,0,95,2024,May,22,29,2024-05-29,2,0,2,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,65.0,0,2
HB-077009,City Hotel,0,0,2023,October,43,27,2023-10-27,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,1,No Deposit,40.0,,0,Transient,65.0,0,0
HB-075127,City Hotel,1,276,2023,July,29,20,2023-07-20,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-020957,Resort Hotel,0,9,2024,February,7,13,2024-02-13,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient,29.0,0,0
HB-037203,Resort Hotel,0,320,2025,June,23,3,2025-06-03,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,3,No Deposit,240.0,,0,Transient,74.25,0,1
HB-012593,Resort Hotel,1,210,2025,July,27,6,2025-07-06,2,3,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,136.0,0,0
HB-003622,Resort Hotel,0,129,2023,December,52,26,2023-12-26,4,6,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,71.88,1,0
HB-035115,Resort Hotel,0,48,2025,April,15,9,2025-04-09,2,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,88.0,1,2
HB-056891,City Hotel,1,433,2024,September,37,15,2024-09-15,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-023506,Resort Hotel,0,3,2024,April,17,25,2024-04-25,1,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,250.0,,0,Transient,81.0,1,1
HB-105645,City Hotel,0,23,2025,February,7,10,2025-02-10,1,2,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,51.5,0,0
HB-071298,City Hotel,1,332,2025,July,27,1,2025-07-01,2,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,113.4,0,2
HB-112591,City Hotel,0,208,2025,May,21,24,2025-05-24,0,2,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,114.4,0,0
HB-046411,City Hotel,1,148,2023,December,52,31,2023-12-31,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,98,Transient,77.5,0,0
HB-029902,Resort Hotel,0,45,2024,November,45,5,2024-11-05,2,2,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,52.4,0,0
HB-037812,Resort Hotel,0,2,2025,June,26,29,2025-06-29,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,65.0,1,0
HB-099433,City Hotel,0,114,2024,October,41,13,2024-10-13,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,C,A,1,No Deposit,234.0,,0,Transient-Party,130.0,0,0
HB-089977,City Hotel,0,102,2024,June,23,5,2024-06-05,1,0,2,0.0,0,BB,ISR,Groups,TA/TO,0,0,1,A,A,0,No Deposit,1.0,,0,Transient-Party,65.0,0,1
HB-059474,City Hotel,1,247,2024,October,44,28,2024-10-28,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,110.0,0,0
HB-115766,City Hotel,0,125,2025,July,28,10,2025-07-10,1,0,3,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,170.5,0,0
HB-091234,City Hotel,0,150,2024,June,24,16,2024-06-16,0,3,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,90.0,0,1
HB-084375,City Hotel,0,86,2024,February,8,20,2024-02-20,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,7.0,,0,Transient,56.93,0,1
HB-058302,City Hotel,1,89,2024,October,41,10,2024-10-10,1,1,2,0.0,0,BB,KOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.8,0,1
HB-096885,City Hotel,0,89,2024,September,36,4,2024-09-04,2,4,1,0.0,0,BB,FIN,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,86.0,,0,Transient-Party,85.0,0,0
HB-039956,Resort Hotel,0,140,2025,August,35,28,2025-08-28,1,4,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,C,G,0,No Deposit,5.0,,0,Transient,225.2,1,0
HB-115634,City Hotel,0,179,2025,July,27,5,2025-07-05,0,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,8.0,,0,Transient,108.1,0,1
HB-094078,City Hotel,0,83,2024,July,30,28,2024-07-28,0,3,2,1.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,141.1,0,1
HB-014122,Resort Hotel,0,6,2025,February,5,1,2025-02-01,0,2,1,0.0,0,SC,,Corporate,Corporate,0,0,1,A,I,0,No Deposit,,356.0,0,Transient-Party,0.0,0,1
HB-021964,Resort Hotel,0,13,2024,June,25,21,2024-06-21,0,1,1,0.0,0,BB,PRT,Corporate,TA/TO,1,0,2,A,A,0,No Deposit,,86.0,0,Transient,65.0,0,0
HB-052308,City Hotel,1,177,2024,June,23,3,2024-06-03,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,119.0,,0,Transient-Party,100.0,0,0
HB-117134,City Hotel,0,91,2025,July,30,27,2025-07-27,0,3,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,112.5,0,0
HB-114004,City Hotel,0,40,2025,June,24,15,2025-06-15,0,1,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,2,No Deposit,9.0,,0,Transient-Party,230.0,0,0
HB-118655,City Hotel,0,189,2025,August,35,27,2025-08-27,2,0,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,1,A,A,1,No Deposit,9.0,,0,Transient,119.0,0,2
HB-066468,City Hotel,1,105,2025,April,16,20,2025-04-20,2,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.5,0,0
HB-094493,City Hotel,0,118,2024,August,31,2,2024-08-02,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,9.0,,0,Transient,118.8,0,1
HB-070187,City Hotel,1,173,2025,June,24,11,2025-06-11,2,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,140.0,0,0
HB-002544,Resort Hotel,0,54,2023,October,42,21,2023-10-21,0,4,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient,40.05,0,0
HB-027525,Resort Hotel,0,57,2024,August,35,30,2024-08-30,0,2,2,0.0,0,BB,NOR,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,102.0,1,1
HB-001072,Resort Hotel,0,78,2023,August,32,12,2023-08-12,1,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,134.0,0,0
HB-041164,City Hotel,1,87,2023,August,33,14,2023-08-14,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,12.0,0,0
HB-031601,Resort Hotel,0,196,2024,December,1,30,2024-12-30,1,2,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,308.0,0,Transient-Party,114.0,0,0
HB-005223,Resort Hotel,0,191,2024,April,17,22,2024-04-22,1,2,2,0.0,0,Undefined,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,85.33,0,0
HB-005776,Resort Hotel,0,195,2024,May,20,13,2024-05-13,2,5,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,C,0,No Deposit,314.0,,0,Transient,43.19,0,2
HB-061864,City Hotel,1,41,2024,December,52,27,2024-12-27,2,5,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,69.29,0,0
HB-047779,City Hotel,0,74,2024,March,9,3,2024-03-03,1,3,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,65.75,0,0
HB-067974,City Hotel,1,316,2025,May,19,10,2025-05-10,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.8,0,1
HB-101564,City Hotel,0,38,2024,November,45,10,2024-11-10,1,3,2,0.0,0,SC,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,59.5,0,0
HB-096254,City Hotel,0,220,2024,August,35,29,2024-08-29,1,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,9.0,,0,Transient,85.5,0,0
HB-100470,City Hotel,0,40,2024,October,43,25,2024-10-25,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-099344,City Hotel,0,68,2024,October,41,10,2024-10-10,1,2,2,1.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,136.3,0,1
HB-057106,City Hotel,1,19,2024,September,38,19,2024-09-19,1,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,287.0,,0,Transient,118.15,0,0
HB-053305,City Hotel,1,66,2024,June,25,17,2024-06-17,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.9,0,0
HB-036016,Resort Hotel,0,36,2025,May,18,4,2025-05-04,0,3,2,0.0,0,HB,IND,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,136.0,0,1
HB-002196,Resort Hotel,1,38,2023,October,40,4,2023-10-04,2,3,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,117.0,0,1
HB-091579,City Hotel,0,38,2024,June,25,20,2024-06-20,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.9,0,2
HB-011684,Resort Hotel,1,177,2025,May,21,25,2025-05-25,1,3,2,2.0,0,BB,AGO,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,155.0,0,1
HB-017287,Resort Hotel,0,272,2023,September,39,30,2023-09-30,0,3,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,C,0,No Deposit,256.0,,0,Transient,73.0,0,0
HB-044570,City Hotel,0,35,2023,October,40,8,2023-10-08,0,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,94.05,0,1
HB-063121,City Hotel,1,56,2025,February,5,1,2025-02-01,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,60.0,0,0
HB-078289,City Hotel,0,4,2023,October,41,12,2023-10-12,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,1
HB-008481,Resort Hotel,1,71,2024,September,40,30,2024-09-30,2,7,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,92.89,0,0
HB-012555,Resort Hotel,1,324,2025,July,27,4,2025-07-04,2,5,3,1.0,0,HB,IRL,Direct,Direct,0,0,0,H,H,1,No Deposit,250.0,,0,Transient,211.03,0,0
HB-035954,Resort Hotel,0,159,2025,April,18,29,2025-04-29,2,5,2,0.0,0,BB,BHS,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,50.85,0,0
HB-029769,Resort Hotel,0,96,2024,October,44,29,2024-10-29,2,5,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,,,0,Transient,78.43,0,2
HB-003459,Resort Hotel,0,194,2023,December,50,12,2023-12-12,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,28.33,0,0
HB-003294,Resort Hotel,0,23,2023,December,49,4,2023-12-04,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,41.4,0,0
HB-007950,Resort Hotel,1,170,2024,September,36,4,2024-09-04,2,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,181.0,,0,Transient,107.2,0,0
HB-072502,City Hotel,1,128,2025,July,31,29,2025-07-29,2,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.5,0,0
HB-106080,City Hotel,0,32,2025,February,7,15,2025-02-15,1,4,2,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,122.74,0,1
HB-117086,City Hotel,0,158,2025,July,30,24,2025-07-24,1,4,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,80.1,0,0
HB-110571,City Hotel,0,98,2025,April,18,28,2025-04-28,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,117.0,0,1
HB-050241,City Hotel,1,15,2024,April,17,27,2024-04-27,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,103.44,0,2
HB-032017,Resort Hotel,0,4,2025,January,3,14,2025-01-14,0,1,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,168.0,,0,Transient-Party,68.0,0,0
HB-118811,City Hotel,0,2,2025,August,35,25,2025-08-25,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,K,0,No Deposit,,,0,Transient,170.0,0,3
HB-065462,City Hotel,1,296,2025,April,14,3,2025-04-03,1,5,3,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,193.5,0,0
HB-001532,Resort Hotel,0,154,2023,September,35,3,2023-09-03,0,3,2,0.0,0,BB,SMR,Corporate,Direct,0,0,0,A,A,0,No Deposit,,268.0,0,Transient-Party,88.2,0,0
HB-082413,City Hotel,0,1,2024,June,24,14,2024-06-14,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,2,A,A,0,No Deposit,,148.0,0,Transient,95.0,0,0
HB-075371,City Hotel,1,313,2023,August,34,26,2023-08-26,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-047310,City Hotel,1,17,2024,February,7,16,2024-02-16,0,4,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.0,0,2
HB-005753,Resort Hotel,1,236,2024,May,19,12,2024-05-12,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,315.0,,0,Transient-Party,48.0,0,0
HB-052990,City Hotel,1,103,2024,June,24,15,2024-06-15,0,1,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,116.1,0,0
HB-000007,Resort Hotel,0,0,2023,July,26,1,2023-07-01,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,0,No Deposit,,,0,Transient,107.0,0,0
HB-098290,City Hotel,0,29,2024,September,39,25,2024-09-25,2,1,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,154.93,0,2
HB-026439,Resort Hotel,0,19,2025,August,33,13,2025-08-13,2,0,2,1.0,0,BB,PRT,Direct,TA/TO,1,0,1,A,I,0,No Deposit,250.0,,0,Transient,248.0,1,1
HB-087157,City Hotel,0,94,2024,April,15,13,2024-04-13,0,2,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,85.5,0,1
HB-072337,City Hotel,1,243,2025,July,30,26,2025-07-26,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-019150,Resort Hotel,0,25,2023,November,48,30,2023-11-30,3,7,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,48.0,0,2
HB-085890,City Hotel,0,73,2024,March,12,20,2024-03-20,2,2,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,16.0,,0,Transient,59.5,0,0
HB-050425,City Hotel,0,121,2024,April,18,30,2024-04-30,2,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,91.5,0,0
HB-092668,City Hotel,0,167,2024,July,27,6,2024-07-06,0,4,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,80.75,0,1
HB-110435,City Hotel,0,15,2025,April,17,27,2025-04-27,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,435.0,0,Transient,95.0,0,0
HB-101474,City Hotel,0,59,2024,November,46,11,2024-11-11,0,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-028268,Resort Hotel,0,61,2024,September,39,24,2024-09-24,2,1,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,129.33,0,1
HB-115847,City Hotel,0,51,2025,July,28,9,2025-07-09,2,1,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,168.0,,0,Transient,80.1,0,0
HB-054005,City Hotel,1,23,2024,July,27,5,2024-07-05,0,2,1,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,145.0,0,0
HB-057368,City Hotel,1,88,2024,September,39,24,2024-09-24,2,1,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,207.9,0,1
HB-027862,Resort Hotel,0,196,2024,September,36,3,2024-09-03,4,6,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,240.0,,0,Transient,158.0,1,1
HB-028489,Resort Hotel,0,18,2024,September,40,30,2024-09-30,2,3,2,0.0,1,BB,ESP,Online TA,TA/TO,0,0,0,G,G,2,No Deposit,240.0,,0,Transient,178.2,1,2
HB-074150,City Hotel,1,342,2023,September,38,24,2023-09-24,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-017488,Resort Hotel,0,277,2023,October,40,6,2023-10-06,2,5,2,0.0,0,HB,GBR,Groups,Direct,0,0,0,D,E,0,No Deposit,273.0,,0,Transient-Party,68.74,0,0
HB-064335,City Hotel,1,106,2025,March,10,6,2025-03-06,1,1,2,0.0,0,BB,GRC,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.2,0,1
HB-042444,City Hotel,1,26,2023,September,36,5,2023-09-05,2,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,116.85,0,1
HB-109765,City Hotel,0,147,2025,April,15,13,2025-04-13,1,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,105.68,0,1
HB-092311,City Hotel,0,19,2024,July,27,1,2024-07-01,1,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,151.0,0,1
HB-064787,City Hotel,1,121,2025,March,11,16,2025-03-16,0,3,2,0.0,0,BB,GRC,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.6,0,0
HB-089131,City Hotel,0,56,2024,May,20,14,2024-05-14,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,132.6,0,1
HB-019840,Resort Hotel,0,14,2024,January,1,3,2024-01-03,2,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,250.0,,0,Transient,43.0,0,1
HB-033738,Resort Hotel,0,26,2025,February,8,23,2025-02-23,2,5,1,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,B,1,No Deposit,40.0,,0,Transient,42.5,0,3
HB-099855,City Hotel,0,37,2024,October,42,16,2024-10-16,2,1,2,0.0,0,BB,BGR,Online TA,TA/TO,0,0,0,A,K,0,No Deposit,7.0,,0,Transient,112.68,0,1
HB-078114,City Hotel,0,0,2023,September,39,28,2023-09-28,1,5,2,0.0,0,BB,MOZ,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,164.67,0,0
HB-028695,Resort Hotel,0,11,2024,October,41,9,2024-10-09,1,0,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,405.0,0,Transient-Party,50.0,0,1
HB-094904,City Hotel,0,163,2024,August,32,8,2024-08-08,1,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,78.96,0,1
HB-112600,City Hotel,0,208,2025,May,21,24,2025-05-24,0,2,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,114.4,0,0
HB-091738,City Hotel,0,265,2024,June,26,24,2024-06-24,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-026849,Resort Hotel,0,26,2024,August,32,11,2024-08-11,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,3,No Deposit,240.0,,0,Transient,233.0,1,1
HB-011016,Resort Hotel,1,46,2025,April,16,14,2025-04-14,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,93.0,0,0
HB-106738,City Hotel,0,7,2025,February,9,27,2025-02-27,1,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,0
HB-045121,City Hotel,0,84,2023,October,42,16,2023-10-16,1,2,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,89.25,0,2
HB-094817,City Hotel,0,103,2024,August,32,7,2024-08-07,2,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,131.4,0,2
HB-029369,Resort Hotel,0,19,2024,October,43,26,2024-10-26,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,331.0,0,Transient-Party,54.0,0,0
HB-036785,Resort Hotel,0,203,2025,May,21,25,2025-05-25,1,3,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,2,No Deposit,,223.0,0,Transient-Party,60.13,1,0
HB-039689,Resort Hotel,0,204,2025,August,33,16,2025-08-16,2,8,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,69.0,,0,Transient,148.7,0,0
HB-104236,City Hotel,0,28,2025,January,1,5,2025-01-05,1,3,2,1.0,0,BB,HRV,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,2
HB-010995,Resort Hotel,1,43,2025,April,16,14,2025-04-14,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,105.0,0,1
HB-045585,City Hotel,1,85,2023,November,45,7,2023-11-07,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,60,Transient,111.0,0,0
HB-091948,City Hotel,0,63,2024,June,26,26,2024-06-26,2,0,2,0.0,0,BB,FIN,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,89.1,0,0
HB-029635,Resort Hotel,0,43,2024,October,44,28,2024-10-28,2,3,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,58.4,1,0
HB-041604,City Hotel,0,4,2023,August,33,19,2023-08-19,1,4,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,E,E,1,No Deposit,14.0,,0,Group,89.0,0,0
HB-015805,Resort Hotel,0,21,2023,July,31,31,2023-07-31,1,2,2,2.0,0,BB,BRA,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,242.0,,0,Transient,188.0,0,1
HB-041863,City Hotel,0,5,2023,August,34,25,2023-08-25,2,5,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,20.0,,0,Transient,100.0,0,1
HB-026552,Resort Hotel,0,179,2024,July,31,31,2024-07-31,2,2,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,96.0,,0,Transient-Party,105.5,0,1
HB-031753,Resort Hotel,0,0,2024,March,10,8,2024-03-08,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,5,A,D,0,No Deposit,241.0,,0,Transient,37.45,1,0
HB-011713,Resort Hotel,1,350,2025,May,22,26,2025-05-26,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,93.29,0,1
HB-065495,City Hotel,1,112,2025,April,14,4,2025-04-04,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,,385.0,0,Transient,95.0,0,0
HB-059712,City Hotel,1,166,2024,November,44,1,2024-11-01,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,110.0,0,0
HB-045316,City Hotel,0,69,2023,October,43,25,2023-10-25,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,58,Transient-Party,85.67,0,0
HB-037942,Resort Hotel,0,232,2025,June,26,24,2025-06-24,4,6,1,1.0,0,BB,NOR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,94.17,0,2
HB-104042,City Hotel,0,72,2025,January,1,3,2025-01-03,0,1,2,0.0,0,BB,KOR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,102.6,0,1
HB-015239,Resort Hotel,0,0,2024,May,22,30,2024-05-30,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,6,A,A,0,No Deposit,47.0,,0,Transient,57.0,0,0
HB-006012,Resort Hotel,0,193,2024,May,21,20,2024-05-20,2,6,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,50.02,0,1
HB-101258,City Hotel,0,34,2024,November,45,6,2024-11-06,2,2,2,0.0,0,BB,FIN,Direct,Direct,0,0,0,A,K,0,No Deposit,,,0,Transient,176.25,0,0
HB-101541,City Hotel,0,180,2024,November,46,13,2024-11-13,1,0,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,54.75,0,2
HB-021339,Resort Hotel,0,4,2025,March,11,13,2025-03-13,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,82.0,0,Transient,35.0,0,0
HB-069431,City Hotel,1,140,2025,May,22,30,2025-05-30,0,4,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,121.5,0,1
HB-011243,Resort Hotel,1,104,2025,April,18,29,2025-04-29,2,5,2,2.0,0,BB,IRL,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,155.0,0,0
HB-052886,City Hotel,1,71,2024,June,24,14,2024-06-14,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,120.0,0,0
HB-116145,City Hotel,0,414,2025,July,28,13,2025-07-13,0,2,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,122.4,0,1
HB-047152,City Hotel,1,10,2024,February,6,10,2024-02-10,0,4,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,3,No Deposit,9.0,,0,Transient,126.5,0,2
HB-033280,Resort Hotel,0,1,2025,February,8,18,2025-02-18,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,,0,Transient,87.0,1,1
HB-063978,City Hotel,1,44,2025,February,9,25,2025-02-25,2,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,121.0,0,0
HB-080042,City Hotel,0,4,2024,January,3,15,2024-01-15,0,1,2,0.0,0,SC,FRA,Online TA,TA/TO,1,11,5,A,A,0,No Deposit,9.0,,0,Transient,77.0,0,1
HB-117058,City Hotel,0,27,2025,July,30,26,2025-07-26,0,3,2,2.0,0,BB,GBR,Direct,Direct,0,0,0,F,F,0,No Deposit,14.0,,0,Transient,245.0,0,0
HB-068467,City Hotel,1,115,2025,May,20,18,2025-05-18,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,170.0,,0,Transient,190.0,0,0
HB-073339,City Hotel,1,140,2025,August,34,19,2025-08-19,0,1,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,195.0,0,1
HB-072462,City Hotel,1,96,2025,July,31,29,2025-07-29,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,403.0,,0,Transient,80.1,0,1
HB-057233,City Hotel,1,440,2024,September,38,22,2024-09-22,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-050803,City Hotel,1,14,2024,May,19,8,2024-05-08,2,3,3,0.0,0,BB,TUR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,159.0,0,0
HB-077492,City Hotel,0,263,2023,September,38,21,2023-09-21,1,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,B,0,No Deposit,21.0,,0,Transient-Party,67.0,0,0
HB-007516,Resort Hotel,1,91,2024,August,33,13,2024-08-13,1,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,189.0,0,0
HB-027914,Resort Hotel,0,230,2024,September,36,8,2024-09-08,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Contract,57.8,0,0
HB-078389,City Hotel,0,3,2023,October,41,12,2023-10-12,1,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-106956,City Hotel,0,0,2025,March,10,5,2025-03-05,0,0,2,0.0,0,BB,PRT,Direct,Direct,1,0,0,A,A,1,No Deposit,,,0,Transient,0.0,0,0
HB-068027,City Hotel,1,331,2025,May,19,11,2025-05-11,1,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,2
HB-001452,Resort Hotel,0,5,2023,August,35,30,2023-08-30,2,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,142.0,,0,Contract,106.8,0,0
HB-081671,City Hotel,1,182,2024,April,17,27,2024-04-27,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,3.0,,50,Transient,75.0,0,0
HB-083091,City Hotel,0,4,2024,March,13,29,2024-03-29,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,3,2,A,D,1,No Deposit,,72.0,0,Transient,40.0,0,1
HB-055908,City Hotel,1,195,2024,August,34,24,2024-08-24,0,4,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.25,0,1
HB-077467,City Hotel,0,3,2023,September,38,19,2023-09-19,1,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,29.0,,0,Transient-Party,120.0,0,0
HB-060986,City Hotel,1,35,2024,November,48,28,2024-11-28,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,2,No Deposit,,,0,Transient-Party,75.0,0,0
HB-105127,City Hotel,0,0,2025,January,4,26,2025-01-26,1,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,91.8,0,0
HB-096959,City Hotel,0,176,2024,September,36,8,2024-09-08,0,3,2,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,171.0,,0,Transient-Party,125.1,0,0
HB-113671,City Hotel,0,71,2025,June,23,8,2025-06-08,0,3,3,0.0,0,BB,IND,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,159.6,0,0
HB-016613,Resort Hotel,0,220,2023,September,36,4,2023-09-04,0,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Group,141.0,0,2
HB-099038,City Hotel,0,9,2024,October,40,6,2024-10-06,0,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,149.0,1,1
HB-075801,City Hotel,1,330,2023,September,37,12,2023-09-12,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-115955,City Hotel,0,33,2025,July,28,11,2025-07-11,0,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,1
HB-059596,City Hotel,1,174,2024,October,44,29,2024-10-29,2,2,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,162.9,0,0
HB-085878,City Hotel,0,61,2024,March,12,19,2024-03-19,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,B,1,No Deposit,138.0,,0,Transient,63.58,0,0
HB-016361,Resort Hotel,0,272,2023,August,33,17,2023-08-17,3,6,2,3.0,0,BB,BEL,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,199.0,0,3
HB-038785,Resort Hotel,0,27,2025,July,30,26,2025-07-26,0,4,2,1.0,0,HB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,207.59,1,1
HB-016552,Resort Hotel,1,247,2023,October,41,9,2023-10-09,1,2,2,0.0,0,FB,ESP,Groups,TA/TO,0,1,0,A,A,0,Non Refund,68.0,,0,Transient,81.0,0,0
HB-055626,City Hotel,1,51,2024,August,33,18,2024-08-18,0,2,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,152.1,0,0
HB-010382,Resort Hotel,1,181,2025,March,9,1,2025-03-01,6,19,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,440.0,,0,Transient-Party,58.6,0,0
HB-036977,Resort Hotel,0,14,2025,June,23,2,2025-06-02,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,97.0,0,1
HB-068344,City Hotel,1,104,2025,May,20,15,2025-05-15,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,170.0,0,0
HB-041812,City Hotel,0,13,2023,August,34,24,2023-08-24,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,90.0,0,2
HB-087685,City Hotel,0,112,2024,May,19,6,2024-05-06,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,1,A,A,0,No Deposit,,,0,Transient,98.69,0,1
HB-116695,City Hotel,0,423,2025,July,30,22,2025-07-22,1,1,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,122.4,0,1
HB-073544,City Hotel,1,267,2025,August,35,25,2025-08-25,2,2,1,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.8,0,0
HB-058784,City Hotel,1,286,2024,October,42,16,2024-10-16,1,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,44.0,,0,Transient,90.0,0,0
HB-109600,City Hotel,0,59,2025,April,15,10,2025-04-10,1,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,117.0,1,0
HB-083096,City Hotel,0,2,2024,April,16,20,2024-04-20,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,3,4,A,D,0,No Deposit,,72.0,0,Transient,45.0,0,1
HB-067255,City Hotel,1,190,2025,April,18,30,2025-04-30,2,1,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,1
HB-003635,Resort Hotel,0,90,2023,December,52,28,2023-12-28,1,4,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,125.51,1,0
HB-000952,Resort Hotel,0,116,2023,August,32,7,2023-08-07,2,5,2,1.0,1,BB,PRT,Offline TA/TO,TA/TO,0,0,0,C,C,0,No Deposit,5.0,,0,Transient,133.5,1,2
HB-115134,City Hotel,0,167,2025,June,27,30,2025-06-30,0,2,2,2.0,0,BB,SWE,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,184.05,0,0
HB-019811,Resort Hotel,0,89,2023,December,52,30,2023-12-30,1,4,1,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,109.2,0,0
HB-108608,City Hotel,0,1,2025,March,13,29,2025-03-29,0,1,2,0.0,0,SC,CN,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,7.0,,0,Transient,74.48,0,1
HB-046832,City Hotel,0,4,2024,January,3,20,2024-01-20,0,1,1,0.0,0,BB,FRA,Online TA,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,80.0,0,1
HB-009996,Resort Hotel,1,28,2025,February,6,3,2025-02-03,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,48.0,0,0
HB-051095,City Hotel,0,132,2024,May,20,13,2024-05-13,2,2,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,113.05,0,1
HB-066679,City Hotel,1,18,2025,April,17,23,2025-04-23,1,0,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,102.6,0,0
HB-100609,City Hotel,0,37,2024,October,43,27,2024-10-27,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,153.0,1,3
HB-067618,City Hotel,1,189,2025,May,19,5,2025-05-05,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,100.0,0,0
HB-026679,Resort Hotel,0,18,2024,August,31,3,2024-08-03,1,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,175.2,0,0
HB-006065,Resort Hotel,0,223,2024,May,21,24,2024-05-24,0,5,1,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,A,1,No Deposit,,223.0,0,Transient-Party,68.0,1,0
HB-055920,City Hotel,1,104,2024,August,34,24,2024-08-24,0,4,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,150.3,0,0
HB-039923,Resort Hotel,0,21,2025,August,35,25,2025-08-25,2,5,2,1.0,0,BB,MAR,Online TA,TA/TO,0,0,0,E,E,3,No Deposit,240.0,,0,Transient,277.71,1,3
HB-011614,Resort Hotel,1,60,2025,May,21,21,2025-05-21,2,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,169.0,0,Transient-Party,50.0,0,0
HB-057564,City Hotel,1,60,2024,September,39,27,2024-09-27,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.9,0,0
HB-111617,City Hotel,0,104,2025,May,19,9,2025-05-09,0,4,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,85.0,0,2
HB-013302,Resort Hotel,1,200,2025,August,32,7,2025-08-07,2,5,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,200.0,0,0
HB-074239,City Hotel,1,377,2023,October,43,29,2023-10-29,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-014213,Resort Hotel,0,120,2025,July,27,1,2025-07-01,2,6,2,0.0,0,BB,PRT,Direct,Direct,0,0,2,D,D,1,No Deposit,250.0,,0,Transient,144.0,1,1
HB-090204,City Hotel,0,192,2024,May,22,28,2024-05-28,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,66.71,0,0
HB-113864,City Hotel,0,21,2025,June,24,11,2025-06-11,2,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,103.2,0,0
HB-055914,City Hotel,1,112,2024,August,34,24,2024-08-24,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,157.0,,0,Transient,116.28,0,0
HB-038254,Resort Hotel,0,149,2025,July,28,9,2025-07-09,2,2,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,410.0,,0,Transient,116.5,0,0
HB-065384,City Hotel,1,76,2025,April,14,1,2025-04-01,2,5,3,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,163.8,0,0
HB-060238,City Hotel,1,277,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-081425,City Hotel,0,0,2024,March,13,30,2024-03-30,0,1,1,0.0,0,HB,PRT,Complementary,Direct,1,0,1,F,F,0,No Deposit,,45.0,0,Transient,0.0,0,1
HB-104294,City Hotel,0,10,2025,January,2,8,2025-01-08,2,1,1,0.0,0,BB,USA,Groups,TA/TO,0,0,0,D,D,0,No Deposit,330.0,,0,Transient-Party,69.0,0,2
HB-048710,City Hotel,1,12,2024,March,13,28,2024-03-28,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,38.67,0,0
HB-104882,City Hotel,0,10,2025,January,4,22,2025-01-22,2,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,77.0,,0,Transient-Party,65.0,0,0
HB-098191,City Hotel,0,39,2024,September,39,25,2024-09-25,1,0,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,10.0,,0,Transient,129.7,0,0
HB-043639,City Hotel,0,17,2023,September,38,21,2023-09-21,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,133.0,1,1
HB-100010,City Hotel,0,256,2024,October,42,16,2024-10-16,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,,333.0,0,Transient-Party,100.75,0,0
HB-005394,Resort Hotel,1,168,2024,April,17,28,2024-04-28,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,257.0,,0,Transient,80.0,0,0
HB-111565,City Hotel,0,193,2025,May,19,6,2025-05-06,2,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,124.46,0,2
HB-090935,City Hotel,0,120,2024,June,24,13,2024-06-13,1,0,2,1.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient-Party,143.1,0,4
HB-056758,City Hotel,1,255,2024,September,37,12,2024-09-12,1,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,100.3,0,0
HB-022949,Resort Hotel,0,49,2024,April,15,8,2024-04-08,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,46.66,0,1
HB-033180,Resort Hotel,0,94,2025,February,7,13,2025-02-13,1,3,1,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,152.0,,0,Transient-Party,44.0,0,0
HB-058178,City Hotel,1,443,2024,October,41,7,2024-10-07,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,391,Transient,65.0,0,0
HB-042970,City Hotel,1,7,2023,September,37,11,2023-09-11,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,138.0,0,2
HB-084571,City Hotel,0,1,2024,February,9,27,2024-02-27,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,91.0,0,1
HB-069502,City Hotel,1,174,2025,June,22,1,2025-06-01,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,0,Transient,100.0,0,0
HB-102011,City Hotel,0,215,2024,November,47,21,2024-11-21,1,1,1,0.0,0,BB,SWE,Groups,Corporate,0,0,0,A,A,1,No Deposit,,233.0,0,Transient,75.0,0,0
HB-056968,City Hotel,1,422,2024,September,38,16,2024-09-16,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,379,Transient-Party,65.0,0,0
HB-031378,Resort Hotel,0,128,2024,December,51,21,2024-12-21,2,4,1,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient-Party,71.1,0,2
HB-025618,Resort Hotel,0,139,2024,June,26,29,2024-06-29,1,4,2,0.0,0,HB,ESP,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,153.42,1,0
HB-057902,City Hotel,1,36,2024,October,40,3,2024-10-03,1,1,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.2,0,0
HB-106712,City Hotel,0,30,2025,February,9,26,2025-02-26,2,2,2,0.0,0,BB,NLD,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient-Party,77.0,0,2
HB-071456,City Hotel,1,240,2025,July,27,5,2025-07-05,1,4,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,91.08,0,1
HB-067000,City Hotel,1,316,2025,April,17,27,2025-04-27,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.8,0,0
HB-007522,Resort Hotel,1,121,2024,August,33,13,2024-08-13,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,197.67,0,0
HB-103562,City Hotel,0,25,2024,December,52,27,2024-12-27,0,1,1,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,220.0,,0,Transient-Party,65.0,0,0
HB-044923,City Hotel,1,180,2023,October,42,16,2023-10-16,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,70.0,0,0
HB-031237,Resort Hotel,0,9,2024,December,51,18,2024-12-18,2,0,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,62.0,1,1
HB-077856,City Hotel,0,17,2023,September,39,26,2023-09-26,2,1,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,2,No Deposit,1.0,,0,Transient-Party,170.0,0,0
HB-044439,City Hotel,1,97,2023,October,40,5,2023-10-05,1,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,140.0,0,0
HB-080815,City Hotel,0,6,2023,November,47,22,2023-11-22,2,1,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,27.0,,0,Transient,37.33,0,0
HB-030995,Resort Hotel,0,82,2024,December,49,7,2024-12-07,0,4,2,0.0,0,BB,ESP,Groups,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,33.3,0,0
HB-097039,City Hotel,0,30,2024,September,37,11,2024-09-11,1,0,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,9.0,,0,Transient,149.4,0,1
HB-023686,Resort Hotel,0,4,2024,April,18,30,2024-04-30,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient,95.0,1,1
HB-074257,City Hotel,1,267,2023,July,28,11,2023-07-11,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-064173,City Hotel,1,28,2025,March,9,2,2025-03-02,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,95.0,0,0
HB-064873,City Hotel,1,62,2025,March,12,18,2025-03-18,2,1,3,0.0,0,HB,LUX,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,169.2,0,0
HB-068755,City Hotel,1,420,2025,May,21,20,2025-05-20,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,B,1,Non Refund,229.0,,0,Transient,90.0,0,0
HB-063093,City Hotel,1,14,2025,January,5,30,2025-01-30,1,3,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,0
HB-024260,Resort Hotel,0,236,2024,May,19,12,2024-05-12,0,3,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,315.0,,0,Transient-Party,48.0,0,0
HB-050542,City Hotel,0,145,2024,May,18,3,2024-05-03,0,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,99.45,0,0
HB-073586,City Hotel,1,195,2025,August,35,26,2025-08-26,2,5,3,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-108848,City Hotel,0,36,2025,April,14,1,2025-04-01,1,1,1,2.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,120.0,0,0
HB-007347,Resort Hotel,1,98,2024,August,31,4,2024-08-04,2,5,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient,201.0,0,0
HB-012929,Resort Hotel,1,251,2025,July,30,23,2025-07-23,3,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,174.0,0,1
HB-086342,City Hotel,0,57,2024,March,13,28,2024-03-28,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.85,0,1
HB-004018,Resort Hotel,1,111,2024,February,7,12,2024-02-12,0,2,2,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,38.0,,0,Transient,70.0,0,0
HB-009157,Resort Hotel,1,2,2024,October,44,30,2024-10-30,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,76.0,0,0
HB-040896,City Hotel,0,16,2023,August,32,8,2023-08-08,2,2,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-074723,City Hotel,0,0,2024,June,25,21,2024-06-21,0,2,1,0.0,0,BB,PRT,Complementary,Direct,1,0,26,A,A,0,No Deposit,,45.0,0,Transient,0.0,0,3
HB-004933,Resort Hotel,1,121,2024,April,15,9,2024-04-09,2,5,2,0.0,0,HB,GBR,Groups,Direct,0,0,0,D,D,0,Non Refund,273.0,,0,Transient,72.0,0,0
HB-079718,City Hotel,1,60,2023,December,52,29,2023-12-29,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,D,D,0,No Deposit,9.0,,0,Transient,110.43,0,0
HB-015912,Resort Hotel,0,73,2023,July,30,30,2023-07-30,2,7,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,95.0,,0,Transient,123.0,0,0
HB-026144,Resort Hotel,0,1,2024,July,30,22,2024-07-22,0,1,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,149.0,0,1
HB-021342,Resort Hotel,0,0,2024,February,8,23,2024-02-23,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,1,No Deposit,,384.0,0,Transient-Party,30.0,0,0
HB-018631,Resort Hotel,0,2,2025,May,21,24,2025-05-24,0,1,1,0.0,0,BB,PRT,Corporate,Direct,1,0,7,A,A,0,No Deposit,,399.0,0,Transient,45.0,0,1
HB-047552,City Hotel,1,28,2024,February,9,26,2024-02-26,1,2,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,125.77,0,1
HB-062478,City Hotel,1,38,2025,January,3,14,2025-01-14,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,Non Refund,,67.0,0,Transient,75.0,0,0
HB-075647,City Hotel,1,290,2023,August,31,3,2023-08-03,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-025880,Resort Hotel,0,258,2024,July,27,4,2024-07-04,3,8,2,0.0,0,BB,DNK,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,242.0,,0,Transient,130.5,0,0
HB-001618,Resort Hotel,1,73,2023,September,36,6,2023-09-06,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,98.0,0,1
HB-051846,City Hotel,0,316,2024,May,21,26,2024-05-26,0,3,2,0.0,0,BB,AUT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,110.0,0,0
HB-106480,City Hotel,0,134,2025,February,9,25,2025-02-25,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,75.0,0,0
HB-024008,Resort Hotel,0,58,2024,May,19,8,2024-05-08,2,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,393.0,,0,Transient-Party,48.6,0,1
HB-099764,City Hotel,0,32,2024,October,42,15,2024-10-15,1,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-028742,Resort Hotel,0,5,2024,October,41,11,2024-10-11,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,47.0,0,Transient,42.0,0,0
HB-043151,City Hotel,0,13,2023,September,37,16,2023-09-16,0,1,2,0.0,0,BB,IND,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,98.4,0,0
HB-055124,City Hotel,1,159,2024,August,32,5,2024-08-05,1,2,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,143.7,0,0
HB-028050,Resort Hotel,0,233,2024,September,38,18,2024-09-18,1,0,2,0.0,0,HB,CHE,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,251.0,,0,Transient-Party,104.0,0,1
HB-075337,City Hotel,1,311,2023,August,34,24,2023-08-24,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-043926,City Hotel,0,65,2023,September,39,25,2023-09-25,2,3,1,0.0,0,BB,GRC,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,130.9,0,2
HB-075709,City Hotel,1,302,2023,August,33,15,2023-08-15,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-031185,Resort Hotel,0,0,2024,December,51,16,2024-12-16,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,45.6,0,1
HB-046951,City Hotel,1,1,2024,January,5,29,2024-01-29,0,1,1,0.0,0,BB,DEU,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,90.0,0,0
HB-107570,City Hotel,0,4,2025,March,11,13,2025-03-13,1,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,93.48,0,0
HB-059672,City Hotel,1,54,2024,October,44,30,2024-10-30,2,4,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,111.0,0,1
HB-025504,Resort Hotel,0,157,2024,June,25,23,2024-06-23,2,5,3,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,C,1,No Deposit,243.0,,0,Contract,81.85,0,1
HB-041811,City Hotel,0,7,2023,August,34,24,2023-08-24,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,90.0,0,1
HB-021134,Resort Hotel,0,0,2025,February,6,8,2025-02-08,0,1,2,0.0,0,BB,PRT,Direct,Direct,1,0,0,D,D,0,No Deposit,,,0,Transient,56.0,1,0
HB-104643,City Hotel,0,34,2025,January,3,18,2025-01-18,0,1,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,D,0,No Deposit,19.0,,0,Transient-Party,75.0,0,0
HB-007299,Resort Hotel,0,265,2024,August,31,1,2024-08-01,2,5,3,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,196.0,,0,Transient,143.3,0,1
HB-022875,Resort Hotel,0,3,2024,April,15,8,2024-04-08,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,146.0,,0,Transient,45.0,0,0
HB-049873,City Hotel,0,270,2024,April,16,20,2024-04-20,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,187,Transient-Party,80.0,0,0
HB-097113,City Hotel,0,4,2024,September,37,11,2024-09-11,1,0,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,149.0,0,1
HB-057390,City Hotel,1,41,2024,September,39,25,2024-09-25,2,0,2,0.0,0,BB,ARG,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.9,0,1
HB-080756,City Hotel,1,176,2024,April,15,9,2024-04-09,1,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,21.0,,0,Transient,125.0,0,0
HB-077698,City Hotel,0,6,2023,September,38,21,2023-09-21,1,2,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,114.0,0,1
HB-072305,City Hotel,1,465,2025,July,30,26,2025-07-26,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,229.0,,0,Transient-Party,90.0,0,0
HB-043040,City Hotel,0,4,2023,September,37,13,2023-09-13,2,1,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,9.0,,0,Contract,186.33,0,1
HB-048603,City Hotel,1,161,2024,March,13,25,2024-03-25,1,2,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,2,Non Refund,12.0,,101,Transient,105.0,0,0
HB-001299,Resort Hotel,1,79,2023,August,34,23,2023-08-23,2,3,3,1.0,0,HB,PRT,Direct,Direct,0,0,0,H,H,0,No Deposit,250.0,,0,Transient,259.0,0,0
HB-018636,Resort Hotel,0,1,2023,November,47,24,2023-11-24,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,40.0,0,1
HB-092286,City Hotel,0,86,2024,July,27,1,2024-07-01,1,2,2,1.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,3,No Deposit,83.0,,0,Transient,107.69,0,1
HB-029066,Resort Hotel,0,3,2025,January,3,19,2025-01-19,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,459.0,0,Transient,39.0,1,0
HB-048147,City Hotel,1,75,2024,March,11,17,2024-03-17,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient,80.0,0,0
HB-114956,City Hotel,0,46,2025,June,26,27,2025-06-27,0,2,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,108.0,0,0
HB-015955,Resort Hotel,0,129,2023,August,31,6,2023-08-06,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,E,0,No Deposit,,,0,Transient-Party,118.5,0,1
HB-012372,Resort Hotel,1,50,2025,June,26,26,2025-06-26,1,1,2,0.0,0,BB,LBN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,176.0,0,1
HB-005840,Resort Hotel,1,9,2024,May,20,15,2024-05-15,1,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,315.0,,0,Transient-Party,70.0,0,0
HB-113643,City Hotel,0,41,2025,June,23,8,2025-06-08,0,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,140.0,0,1
HB-081476,City Hotel,0,6,2023,December,49,10,2023-12-10,0,2,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,0.0,0,0
HB-035039,Resort Hotel,0,7,2025,April,15,11,2025-04-11,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,E,1,No Deposit,240.0,,0,Transient-Party,105.0,0,1
HB-108773,City Hotel,0,123,2025,March,13,28,2025-03-28,0,5,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.64,0,0
HB-006873,Resort Hotel,1,209,2024,July,28,8,2024-07-08,2,5,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,163.0,0,0
HB-083964,City Hotel,0,0,2024,February,7,15,2024-02-15,1,0,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,127.0,0,0
HB-076685,City Hotel,0,4,2024,April,15,10,2024-04-10,2,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,3,28,A,A,0,No Deposit,,40.0,0,Transient-Party,65.0,0,0
HB-052637,City Hotel,1,27,2024,June,23,9,2024-06-09,0,1,2,0.0,0,BB,PRT,Offline TA/TO,Corporate,0,0,0,A,A,0,No Deposit,191.0,,0,Transient-Party,120.0,0,0
HB-086245,City Hotel,0,14,2024,March,13,29,2024-03-29,0,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,7.0,,0,Transient,89.32,0,1
HB-064390,City Hotel,1,258,2025,March,10,8,2025-03-08,0,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.0,0,0
HB-023792,Resort Hotel,0,0,2024,May,21,25,2024-05-25,0,1,2,0.0,0,BB,PRT,Direct,Direct,1,0,1,A,A,0,No Deposit,,,0,Transient,129.0,0,0
HB-111473,City Hotel,0,34,2025,May,19,9,2025-05-09,0,2,2,0.0,0,BB,SRB,Groups,TA/TO,0,0,0,A,A,1,No Deposit,39.0,,0,Transient-Party,140.0,0,0
HB-020036,Resort Hotel,0,8,2024,January,2,13,2024-01-13,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,358.0,0,Transient,30.0,0,0
HB-081808,City Hotel,1,117,2024,February,9,29,2024-02-29,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,44,Transient,75.0,0,0
HB-094001,City Hotel,0,188,2024,July,30,23,2024-07-23,2,5,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.75,0,1
HB-117153,City Hotel,0,145,2025,July,30,27,2025-07-27,0,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,16.0,,0,Transient,80.1,0,1
HB-040484,City Hotel,1,27,2023,July,30,27,2023-07-27,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-048323,City Hotel,1,65,2024,March,12,20,2024-03-20,2,3,3,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,85.0,,0,Transient,124.0,0,1
HB-000854,Resort Hotel,1,3,2023,August,31,1,2023-08-01,2,3,2,2.0,0,HB,PRT,Direct,Direct,0,0,0,C,C,1,No Deposit,250.0,,0,Transient,237.0,0,1
HB-086726,City Hotel,0,78,2024,April,14,7,2024-04-07,0,1,1,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,86.0,,0,Transient,72.72,0,0
HB-113191,City Hotel,0,203,2025,May,22,31,2025-05-31,0,4,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,7.0,,0,Transient,91.51,0,3
HB-117664,City Hotel,0,92,2025,August,31,2,2025-08-02,2,4,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,125.0,0,2
HB-029755,Resort Hotel,0,6,2024,November,44,2,2024-11-02,0,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,242.0,,0,Transient,67.19,1,1
HB-041191,City Hotel,0,39,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-108485,City Hotel,0,72,2025,March,13,24,2025-03-24,2,2,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,85.0,,0,Transient,76.5,0,0
HB-019438,Resort Hotel,0,11,2023,December,51,18,2023-12-18,0,2,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,46.0,0,1
HB-054845,City Hotel,1,386,2024,July,30,28,2024-07-28,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-052035,City Hotel,1,202,2024,May,22,29,2024-05-29,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,26.0,,0,Transient,90.0,0,0
HB-057322,City Hotel,0,429,2024,September,39,23,2024-09-23,0,2,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,330,Transient-Party,65.0,0,0
HB-020750,Resort Hotel,0,72,2024,February,6,6,2024-02-06,2,1,2,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,73.33,0,0
HB-006490,Resort Hotel,1,65,2024,June,24,13,2024-06-13,1,0,2,0.0,0,BB,RUS,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,107.1,0,0
HB-112566,City Hotel,0,60,2025,May,21,23,2025-05-23,0,3,2,0.0,0,HB,ESP,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,189.0,1,0
HB-074916,City Hotel,1,136,2023,July,29,17,2023-07-17,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient,60.0,0,0
HB-116778,City Hotel,0,174,2025,July,29,18,2025-07-18,2,5,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.13,0,1
HB-098593,City Hotel,0,1,2024,September,39,29,2024-09-29,0,3,2,0.0,0,HB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,325.0,,0,Transient-Party,146.0,0,0
HB-055924,City Hotel,1,128,2024,August,34,24,2024-08-24,1,4,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,7.0,,0,Transient,137.91,0,0
HB-020425,Resort Hotel,0,8,2024,October,42,19,2024-10-19,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,6,A,A,0,No Deposit,,269.0,0,Transient,45.0,0,0
HB-019895,Resort Hotel,0,0,2024,January,2,8,2024-01-08,0,1,2,0.0,0,HB,PRT,Groups,Corporate,1,0,0,A,A,0,No Deposit,,,0,Transient-Party,43.0,1,0
HB-065261,City Hotel,1,61,2025,March,13,30,2025-03-30,0,3,1,0.0,0,SC,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.8,0,1
HB-041572,City Hotel,0,10,2023,August,33,18,2023-08-18,0,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,9.0,,0,Transient,90.0,0,2
HB-087652,City Hotel,0,65,2024,April,17,23,2024-04-23,0,1,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,118.8,0,0
HB-044168,City Hotel,0,164,2023,October,40,2,2023-10-02,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,19.0,,0,Transient-Party,100.0,0,0
HB-039611,Resort Hotel,0,330,2025,August,34,20,2025-08-20,2,1,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,E,F,1,No Deposit,240.0,,0,Transient,172.8,0,2
HB-050380,City Hotel,1,96,2024,April,18,29,2024-04-29,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.9,0,1
HB-076760,City Hotel,0,0,2023,August,31,6,2023-08-06,1,3,2,0.0,0,SC,RUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,81.0,0,0
HB-060173,City Hotel,1,277,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-009661,Resort Hotel,1,91,2024,December,52,23,2024-12-23,2,4,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient-Party,75.6,0,1
HB-018542,Resort Hotel,0,289,2023,November,47,20,2023-11-20,1,2,2,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,57.0,0,0
HB-053050,City Hotel,1,188,2024,June,24,15,2024-06-15,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,39,Transient,130.0,0,0
HB-059044,City Hotel,1,163,2024,October,42,20,2024-10-20,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-059124,City Hotel,1,457,2024,October,43,21,2024-10-21,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,391,Transient,65.0,0,0
HB-047145,City Hotel,1,34,2024,February,6,10,2024-02-10,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,67.5,0,1
HB-116411,City Hotel,0,189,2025,July,29,18,2025-07-18,0,2,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,86.63,0,1
HB-111648,City Hotel,0,147,2025,May,19,10,2025-05-10,0,4,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,27.0,,0,Transient,89.1,0,0
HB-088663,City Hotel,0,12,2024,May,19,8,2024-05-08,2,0,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.0,0,1
HB-104638,City Hotel,0,34,2025,January,3,18,2025-01-18,0,1,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,B,0,No Deposit,19.0,,0,Transient-Party,75.0,0,0
HB-085619,City Hotel,0,6,2024,March,11,14,2024-03-14,1,4,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,118.0,1,1
HB-044163,City Hotel,0,24,2023,October,40,2,2023-10-02,0,1,2,0.0,0,BB,LBN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,50.0,,0,Transient,111.6,0,0
HB-057207,City Hotel,1,200,2024,September,38,20,2024-09-20,2,8,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,129.54,0,0
HB-017552,Resort Hotel,0,16,2023,October,41,14,2023-10-14,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,56.0,1,1
HB-047407,City Hotel,1,17,2024,February,8,19,2024-02-19,6,15,1,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,103.39,0,1
HB-017485,Resort Hotel,0,0,2023,October,41,12,2023-10-12,0,0,2,1.0,0,BB,PRT,Corporate,Corporate,1,0,0,A,I,0,No Deposit,,,0,Transient,0.0,0,0
HB-044907,City Hotel,0,43,2023,October,41,15,2023-10-15,1,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,99.0,0,2
HB-007762,Resort Hotel,1,29,2024,August,34,25,2024-08-25,0,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,214.0,0,0
HB-088916,City Hotel,0,37,2024,May,20,13,2024-05-13,0,1,1,0.0,0,SC,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,116.1,0,0
HB-062453,City Hotel,1,38,2025,January,3,14,2025-01-14,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,Non Refund,,67.0,0,Transient,75.0,0,0
HB-026495,Resort Hotel,0,149,2024,July,30,27,2024-07-27,2,4,3,0.0,0,HB,CHE,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,233.0,0,1
HB-021961,Resort Hotel,0,0,2024,March,11,13,2024-03-13,1,0,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-001829,Resort Hotel,1,65,2023,September,37,16,2023-09-16,2,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,81.5,0,1
HB-037114,Resort Hotel,0,4,2025,June,23,4,2025-06-04,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,526.0,,0,Transient,95.0,0,0
HB-022552,Resort Hotel,0,28,2024,March,12,21,2024-03-21,2,5,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,D,E,0,No Deposit,,,0,Transient,95.14,0,0
HB-011724,Resort Hotel,1,312,2025,May,22,27,2025-05-27,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,59.79,0,1
HB-022663,Resort Hotel,0,0,2024,March,13,29,2024-03-29,0,2,2,0.0,0,BB,SYR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,54.0,0,0
HB-099526,City Hotel,0,24,2024,October,41,10,2024-10-10,1,3,2,0.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,115.0,0,0
HB-118296,City Hotel,0,113,2025,August,33,13,2025-08-13,2,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,164.0,1,2
HB-032277,Resort Hotel,0,0,2025,January,4,20,2025-01-20,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,45.0,0,0
HB-010833,Resort Hotel,1,84,2025,April,15,7,2025-04-07,2,4,2,2.0,0,HB,GBR,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,193.0,0,0
HB-035482,Resort Hotel,0,62,2025,April,16,19,2025-04-19,1,4,1,0.0,0,BB,RUS,Corporate,Corporate,0,0,0,A,C,3,No Deposit,,307.0,0,Transient-Party,85.0,0,0
HB-037061,Resort Hotel,0,1,2025,June,23,2,2025-06-02,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,95.0,0,1
HB-076821,City Hotel,0,2,2024,July,28,8,2024-07-08,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,1,2,4,A,A,1,No Deposit,,40.0,0,Transient,77.0,1,0
HB-101827,City Hotel,0,96,2024,November,46,16,2024-11-16,0,3,1,0.0,0,BB,LTU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,84.6,0,0
HB-068850,City Hotel,1,91,2025,May,21,21,2025-05-21,2,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,138.6,0,0
HB-068855,City Hotel,1,209,2025,May,21,21,2025-05-21,2,4,0,2.0,0,BB,DNK,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient,110.75,0,1
HB-046904,City Hotel,1,0,2024,January,4,25,2024-01-25,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,100.0,0,1
HB-052134,City Hotel,1,113,2024,May,22,31,2024-05-31,0,3,1,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,A,0,Non Refund,,202.0,0,Transient,100.0,0,0
HB-019685,Resort Hotel,0,3,2023,December,52,31,2023-12-31,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,0,No Deposit,242.0,,0,Transient,110.2,1,1
HB-112506,City Hotel,0,128,2025,May,21,21,2025-05-21,2,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,2
HB-117807,City Hotel,0,13,2025,August,32,9,2025-08-09,0,1,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,270.0,0,3
HB-072490,City Hotel,1,468,2025,July,31,29,2025-07-29,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,0
HB-116183,City Hotel,0,215,2025,July,28,13,2025-07-13,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,99.9,0,1
HB-018157,Resort Hotel,0,1,2023,November,45,7,2023-11-07,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,330.0,,0,Transient,31.0,0,0
HB-064553,City Hotel,1,92,2025,March,11,12,2025-03-12,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,91.8,0,1
HB-057840,City Hotel,1,281,2024,October,40,1,2024-10-01,2,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,174,Transient-Party,96.0,0,0
HB-084029,City Hotel,0,7,2024,February,7,14,2024-02-14,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,66.57,0,1
HB-103456,City Hotel,0,65,2024,December,51,21,2024-12-21,0,4,3,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,22.0,,0,Transient,122.65,0,0
HB-026192,Resort Hotel,0,156,2024,July,29,20,2024-07-20,0,4,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,96.0,,0,Transient-Party,102.8,0,1
HB-027866,Resort Hotel,0,5,2024,September,37,12,2024-09-12,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,119.0,0,1
HB-010373,Resort Hotel,1,84,2025,March,9,1,2025-03-01,6,19,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,440.0,,0,Transient-Party,55.8,0,0
HB-000834,Resort Hotel,1,18,2023,July,31,31,2023-07-31,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,149.7,0,1
HB-003927,Resort Hotel,1,8,2024,February,6,6,2024-02-06,4,10,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,25.0,0,0
HB-059905,City Hotel,1,304,2024,November,44,3,2024-11-03,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,89.0,0,0
HB-070320,City Hotel,1,201,2025,June,24,14,2025-06-14,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-019532,Resort Hotel,0,40,2023,December,51,19,2023-12-19,2,5,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient-Party,49.4,0,0
HB-075597,City Hotel,0,257,2023,July,26,1,2023-07-01,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,101.5,0,0
HB-052742,City Hotel,1,128,2024,June,24,10,2024-06-10,1,2,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,116.1,0,0
HB-035762,Resort Hotel,0,96,2025,April,18,29,2025-04-29,1,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,C,0,No Deposit,250.0,,0,Transient,76.5,0,0
HB-099310,City Hotel,0,24,2024,October,41,9,2024-10-09,2,1,2,0.0,0,BB,ROU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,42.0,,0,Transient,95.0,0,1
HB-006059,Resort Hotel,1,68,2024,May,21,24,2024-05-24,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient,77.0,0,0
HB-057710,City Hotel,1,315,2024,September,40,30,2024-09-30,1,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,69,Transient,160.0,0,0
HB-028219,Resort Hotel,0,16,2024,September,39,24,2024-09-24,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,240.0,,0,Transient,134.0,0,2
HB-093559,City Hotel,0,292,2024,July,29,21,2024-07-21,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,0
HB-096322,City Hotel,0,181,2024,August,35,30,2024-08-30,0,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.3,0,2
HB-117190,City Hotel,0,15,2025,July,30,27,2025-07-27,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,157.0,0,1
HB-029464,Resort Hotel,0,27,2024,October,44,28,2024-10-28,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,E,1,No Deposit,240.0,,0,Transient,95.0,0,2
HB-005646,Resort Hotel,1,75,2024,May,19,7,2024-05-07,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,88.0,0,1
HB-003954,Resort Hotel,0,103,2024,February,6,9,2024-02-09,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,332.0,,0,Transient,50.0,0,1
HB-083105,City Hotel,0,0,2024,January,3,19,2024-01-19,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,180.0,,0,Transient,66.0,1,0
HB-023546,Resort Hotel,0,25,2024,April,17,26,2024-04-26,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,2,No Deposit,250.0,,0,Transient,85.5,0,0
HB-106120,City Hotel,0,22,2025,February,7,16,2025-02-16,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,97.58,0,0
HB-085422,City Hotel,0,4,2024,March,11,12,2024-03-12,2,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,107.0,0,1
HB-045167,City Hotel,0,45,2023,October,42,20,2023-10-20,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,94.5,0,2
HB-063948,City Hotel,1,134,2025,February,9,25,2025-02-25,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,75.0,0,0
HB-116859,City Hotel,0,13,2025,July,30,22,2025-07-22,2,2,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,199.5,0,1
HB-037020,Resort Hotel,0,21,2025,June,23,2,2025-06-02,0,2,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,101.5,1,1
HB-069378,City Hotel,1,186,2025,May,22,30,2025-05-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,130.0,0,0
HB-010849,Resort Hotel,1,60,2025,April,15,8,2025-04-08,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient,76.0,0,0
HB-093159,City Hotel,0,184,2024,July,29,16,2024-07-16,1,1,2,0.0,0,HB,ITA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,125.0,0,1
HB-083441,City Hotel,0,1,2024,February,5,1,2024-02-01,1,0,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,66.22,0,1
HB-036426,Resort Hotel,0,16,2025,May,20,18,2025-05-18,0,2,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,G,G,0,No Deposit,250.0,,0,Transient,176.67,1,1
HB-055501,City Hotel,1,251,2024,August,33,14,2024-08-14,2,3,0,2.0,0,BB,DEU,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient-Party,81.5,0,1
HB-112206,City Hotel,0,114,2025,May,20,17,2025-05-17,0,4,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,3,No Deposit,9.0,,0,Transient,123.75,0,1
HB-008093,Resort Hotel,1,75,2024,September,37,11,2024-09-11,2,1,2,0.0,1,BB,BRA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient,117.73,0,0
HB-054927,City Hotel,1,150,2024,July,31,30,2024-07-30,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,8.0,,0,Transient,123.3,0,0
HB-044988,City Hotel,1,102,2023,October,42,16,2023-10-16,0,2,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient-Party,80.0,0,0
HB-017726,Resort Hotel,0,0,2023,October,42,18,2023-10-18,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,76.0,0,0
HB-085607,City Hotel,0,3,2024,March,11,14,2024-03-14,1,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,3.0,,0,Transient,0.0,0,2
HB-061410,City Hotel,1,322,2024,December,50,9,2024-12-09,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,52.0,0,0
HB-045091,City Hotel,1,102,2023,October,42,16,2023-10-16,0,2,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient-Party,80.0,0,0
HB-073572,City Hotel,1,162,2025,August,35,26,2025-08-26,2,3,2,2.0,0,BB,USA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,235.0,0,0
HB-073365,City Hotel,1,158,2025,August,34,19,2025-08-19,2,1,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,83.0,,0,Transient,212.0,0,0
HB-016744,Resort Hotel,0,4,2024,November,47,23,2024-11-23,0,1,1,0.0,0,BB,PRT,Corporate,Direct,1,0,3,A,D,0,No Deposit,,195.0,0,Transient,35.0,0,0
HB-041767,City Hotel,0,12,2023,August,34,23,2023-08-23,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,9.0,,0,Contract,90.0,0,3
HB-009332,Resort Hotel,1,81,2024,November,46,12,2024-11-12,2,4,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,37.8,0,1
HB-065352,City Hotel,1,162,2025,April,14,1,2025-04-01,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,296.0,,0,Transient-Party,98.0,0,0
HB-096137,City Hotel,0,47,2024,August,35,28,2024-08-28,1,0,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,99.0,0,0
HB-119286,City Hotel,0,135,2025,August,35,27,2025-08-27,2,4,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,157.17,0,1
HB-081925,City Hotel,1,278,2024,August,32,11,2024-08-11,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,65.0,0,0
HB-074432,City Hotel,1,297,2023,August,32,10,2023-08-10,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-026900,Resort Hotel,0,147,2024,August,33,12,2024-08-12,0,2,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,271.0,1,0
HB-015106,Resort Hotel,1,214,2023,October,40,3,2023-10-03,1,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,208.0,,0,Transient,34.0,0,0
HB-037232,Resort Hotel,0,19,2025,June,24,9,2025-06-09,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,154.0,1,1
HB-001430,Resort Hotel,0,0,2023,August,35,29,2023-08-29,1,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient,134.0,0,1
HB-080155,City Hotel,1,226,2024,June,24,15,2024-06-15,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Contract,139.0,0,1
HB-011627,Resort Hotel,1,5,2025,May,21,22,2025-05-22,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,90.0,0,2
HB-009932,Resort Hotel,1,24,2025,January,5,27,2025-01-27,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-062267,City Hotel,1,42,2025,January,2,6,2025-01-06,2,2,2,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,15.0,,0,Transient,70.72,0,0
HB-046385,City Hotel,1,148,2023,December,52,30,2023-12-30,1,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,79,Transient,67.0,0,0
HB-036391,Resort Hotel,0,3,2025,May,20,14,2025-05-14,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,71.0,1,1
HB-047265,City Hotel,1,11,2024,February,7,13,2024-02-13,8,21,1,0.0,0,BB,AGO,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,103.38,0,0
HB-102941,City Hotel,0,66,2024,December,49,5,2024-12-05,1,4,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,68.07,0,1
HB-028801,Resort Hotel,0,16,2024,October,41,9,2024-10-09,2,0,1,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,C,1,No Deposit,,,0,Transient-Party,55.0,0,0
HB-109322,City Hotel,0,178,2025,April,15,9,2025-04-09,1,0,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,151.2,0,2
HB-004970,Resort Hotel,1,79,2024,April,15,11,2024-04-11,1,3,1,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,79.0,0,0
HB-015738,Resort Hotel,0,34,2023,July,30,26,2023-07-26,2,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,146.0,0,0
HB-107605,City Hotel,0,8,2025,March,11,15,2025-03-15,0,1,1,0.0,0,BB,ITA,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,428.0,0,Transient,80.0,0,0
HB-018223,Resort Hotel,0,37,2023,November,45,8,2023-11-08,2,5,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,1,No Deposit,185.0,281.0,0,Transient-Party,36.0,0,0
HB-104156,City Hotel,0,1,2025,January,1,5,2025-01-05,0,2,2,0.0,0,BB,GTM,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,68.0,0,0
HB-082642,City Hotel,0,23,2024,January,1,1,2024-01-01,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,60.0,0,0
HB-084378,City Hotel,0,0,2024,February,8,23,2024-02-23,0,2,3,0.0,0,BB,BRA,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,136.0,0,0
HB-010032,Resort Hotel,1,55,2025,February,6,7,2025-02-07,2,5,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,88.0,0,1
HB-017009,Resort Hotel,0,239,2023,September,38,19,2023-09-19,1,1,1,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,248.0,,0,Transient-Party,59.0,0,0
HB-041456,City Hotel,0,5,2023,August,33,16,2023-08-16,2,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,105.0,0,2
HB-031756,Resort Hotel,0,153,2025,January,1,2,2025-01-02,1,3,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,55.8,0,2
HB-112887,City Hotel,0,183,2025,May,22,28,2025-05-28,2,0,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,108.0,0,1
HB-068920,City Hotel,1,212,2025,May,21,22,2025-05-22,2,5,2,0.0,0,HB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.56,0,1
HB-018222,Resort Hotel,0,24,2023,November,44,3,2023-11-03,2,10,2,0.0,0,BB,ITA,Corporate,Corporate,0,0,0,A,A,1,No Deposit,326.0,281.0,0,Transient-Party,49.5,1,0
HB-084391,City Hotel,0,18,2024,February,8,21,2024-02-21,2,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,87.0,0,0
HB-010692,Resort Hotel,1,103,2025,March,13,27,2025-03-27,1,1,2,0.0,0,BB,PRT,Groups,Corporate,0,0,0,D,D,0,Non Refund,495.0,,0,Transient,65.0,0,0
HB-100716,City Hotel,0,9,2024,October,44,30,2024-10-30,2,0,1,0.0,0,BB,NOR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,120.0,0,0
HB-080086,City Hotel,1,333,2024,September,38,20,2024-09-20,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,58.0,,19,Transient,90.0,0,0
HB-001155,Resort Hotel,0,37,2023,August,33,16,2023-08-16,1,0,1,0.0,0,BB,PRT,Groups,Corporate,0,0,0,A,A,0,No Deposit,,307.0,0,Transient-Party,172.0,0,0
HB-073308,City Hotel,1,173,2025,August,34,18,2025-08-18,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.2,0,0
HB-102835,City Hotel,0,17,2024,December,49,2,2024-12-02,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,107.09,1,2
HB-001274,Resort Hotel,1,72,2023,August,34,22,2023-08-22,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,134.0,0,0
HB-022832,Resort Hotel,0,76,2024,April,14,3,2024-04-03,2,3,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,83.3,0,1
HB-117439,City Hotel,0,0,2025,August,31,3,2025-08-03,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,9.0,,0,Transient,125.1,0,1
HB-030823,Resort Hotel,0,18,2024,December,49,2,2024-12-02,0,2,2,0.0,0,BB,IRL,Groups,TA/TO,0,0,0,D,D,0,No Deposit,253.0,,0,Transient-Party,51.8,0,1
HB-087123,City Hotel,0,53,2024,April,15,11,2024-04-11,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,76.58,0,1
HB-072727,City Hotel,1,340,2025,August,32,4,2025-08-04,1,2,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,9.0,,0,Transient,175.5,0,0
HB-034706,Resort Hotel,0,0,2025,April,14,1,2025-04-01,0,1,2,0.0,0,BB,AGO,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,,0,Transient,110.0,1,0
HB-022206,Resort Hotel,0,18,2024,March,12,18,2024-03-18,0,2,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,43.0,0,1
HB-050479,City Hotel,1,33,2024,May,18,2,2024-05-02,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.9,0,0
HB-081619,City Hotel,1,130,2024,April,15,13,2024-04-13,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,29.0,,10,Transient,100.0,0,0
HB-100567,City Hotel,0,31,2024,October,43,27,2024-10-27,0,3,2,0.0,0,BB,THA,Online TA,TA/TO,0,0,0,A,A,3,No Deposit,9.0,,0,Transient,129.0,0,2
HB-052486,City Hotel,1,213,2024,June,23,7,2024-06-07,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,62,Transient,130.0,0,0
HB-051651,City Hotel,1,41,2024,May,21,24,2024-05-24,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,2,No Deposit,,179.0,0,Transient,89.0,0,0
HB-096979,City Hotel,0,179,2024,September,36,8,2024-09-08,0,3,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,150.45,0,2
HB-116009,City Hotel,0,3,2025,July,28,12,2025-07-12,0,2,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,152.0,,0,Transient,86.35,0,0
HB-117261,City Hotel,0,134,2025,July,30,27,2025-07-27,2,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,139.5,0,2
HB-057618,City Hotel,1,447,2024,September,39,29,2024-09-29,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-107457,City Hotel,0,115,2025,March,11,10,2025-03-10,1,2,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,154.0,,49,Transient-Party,0.0,0,1
HB-056120,City Hotel,1,206,2024,August,35,29,2024-08-29,1,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.95,0,0
HB-030860,Resort Hotel,0,17,2025,February,6,6,2025-02-06,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,D,0,No Deposit,,490.0,0,Transient,36.0,0,0
HB-092821,City Hotel,0,57,2024,July,28,12,2024-07-12,0,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.3,0,1
HB-099588,City Hotel,0,105,2024,October,41,12,2024-10-12,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,132.0,,0,Transient-Party,75.0,0,0
HB-081193,City Hotel,0,63,2023,December,48,3,2023-12-03,0,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,102.9,0,1
HB-044483,City Hotel,1,42,2023,October,40,6,2023-10-06,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,8.0,,0,Transient,86.4,0,1
HB-022182,Resort Hotel,0,0,2024,March,11,17,2024-03-17,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,315.0,,0,Transient,25.0,0,0
HB-044958,City Hotel,0,102,2023,October,42,16,2023-10-16,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-095805,City Hotel,0,0,2024,August,34,23,2024-08-23,0,1,2,2.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,159.0,0,0
HB-106189,City Hotel,0,10,2025,February,8,21,2025-02-21,0,2,2,0.0,0,SC,NLD,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,70.0,0,2
HB-115437,City Hotel,0,405,2025,July,27,4,2025-07-04,0,2,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,91.5,0,0
HB-078999,City Hotel,0,34,2023,October,41,15,2023-10-15,2,3,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Contract,94.3,0,0
HB-017734,Resort Hotel,0,287,2023,October,41,15,2023-10-15,1,3,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,D,2,No Deposit,,223.0,0,Transient-Party,52.0,1,0
HB-047313,City Hotel,1,44,2024,February,7,17,2024-02-17,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,44.0,,3,Transient,75.0,0,0
HB-072819,City Hotel,1,0,2025,August,32,7,2025-08-07,1,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,150.0,0,0
HB-008135,Resort Hotel,0,334,2024,September,37,13,2024-09-13,2,5,2,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,A,2,No Deposit,,223.0,0,Transient-Party,69.43,0,0
HB-083325,City Hotel,0,2,2024,January,4,27,2024-01-27,0,1,1,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,A,0,No Deposit,,45.0,0,Transient-Party,0.0,0,0
HB-117274,City Hotel,0,276,2025,July,31,30,2025-07-30,2,1,2,2.0,0,BB,DEU,Online TA,TA/TO,0,0,0,B,B,3,No Deposit,9.0,,0,Transient,93.64,0,2
HB-085427,City Hotel,0,57,2024,March,11,11,2024-03-11,2,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,82.45,0,2
HB-000571,Resort Hotel,0,79,2023,July,29,20,2023-07-20,1,3,2,0.0,1,BB,PRT,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient,115.0,0,3
HB-003156,Resort Hotel,0,36,2023,November,47,20,2023-11-20,0,2,2,0.0,0,FB,ESP,Groups,TA/TO,0,0,0,A,C,0,No Deposit,38.0,,0,Transient-Party,64.0,0,0
HB-071317,City Hotel,1,39,2025,July,27,2,2025-07-02,2,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,129.0,0,1
HB-090022,City Hotel,0,14,2024,May,22,30,2024-05-30,1,1,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,134.0,0,1
HB-034250,Resort Hotel,0,339,2025,March,11,11,2025-03-11,2,5,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,D,D,0,No Deposit,298.0,,0,Transient-Party,64.0,0,0
HB-052079,City Hotel,1,56,2024,May,22,30,2024-05-30,1,0,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,120.0,0,0
HB-079086,City Hotel,0,5,2023,October,42,19,2023-10-19,1,2,2,0.0,0,BB,POL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,112.0,,0,Transient-Party,90.0,0,0
HB-058970,City Hotel,1,67,2024,October,42,19,2024-10-19,0,3,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.0,0,0
HB-101579,City Hotel,0,180,2024,November,46,13,2024-11-13,1,0,1,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,51.28,0,2
HB-047822,City Hotel,1,17,2024,March,10,4,2024-03-04,3,7,2,0.0,0,SC,DZA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,83.4,0,0
HB-022748,Resort Hotel,0,169,2024,March,13,31,2024-03-31,1,3,2,0.0,0,BB,BEL,Groups,Direct,0,0,0,A,A,0,Refundable,,223.0,0,Transient-Party,66.0,0,0
HB-002673,Resort Hotel,0,96,2023,October,43,24,2023-10-24,2,4,2,2.0,0,BB,ZMB,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,96.67,0,3
HB-051237,City Hotel,1,451,2024,May,20,16,2024-05-16,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-014121,Resort Hotel,0,2,2024,October,42,17,2024-10-17,1,2,1,0.0,0,BB,,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,327.0,,0,Transient,39.0,0,0
HB-089392,City Hotel,0,198,2024,May,21,20,2024-05-20,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,98,Transient-Party,65.0,0,0
HB-064413,City Hotel,1,608,2025,March,10,9,2025-03-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-000408,Resort Hotel,0,0,2023,July,28,14,2023-07-14,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,C,0,No Deposit,,,0,Transient,134.0,0,0
HB-091225,City Hotel,0,73,2024,June,24,16,2024-06-16,0,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,149.4,0,1
HB-044074,City Hotel,0,83,2023,September,39,30,2023-09-30,0,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,26.0,,77,Transient-Party,112.2,0,0
HB-054768,City Hotel,1,38,2024,July,30,26,2024-07-26,0,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.1,0,1
HB-092533,City Hotel,0,5,2024,July,27,6,2024-07-06,0,2,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,F,0,No Deposit,,,0,Transient,143.0,0,0
HB-027545,Resort Hotel,0,70,2024,August,35,26,2024-08-26,2,5,2,0.0,1,BB,IRL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,170.43,0,2
HB-009570,Resort Hotel,1,5,2024,December,50,12,2024-12-12,5,13,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,C,0,No Deposit,10.0,,0,Transient,41.4,0,0
HB-038083,Resort Hotel,0,10,2025,July,27,6,2025-07-06,0,3,3,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,212.0,0,2
HB-091609,City Hotel,0,80,2024,June,25,23,2024-06-23,0,1,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.3,0,1
HB-000986,Resort Hotel,0,5,2023,August,32,9,2023-08-09,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,306.0,,0,Transient,127.31,0,0
HB-018831,Resort Hotel,0,1,2023,November,48,28,2023-11-28,1,1,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,98.0,0,0
HB-047879,City Hotel,0,92,2024,March,10,7,2024-03-07,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.3,0,1
HB-099123,City Hotel,0,349,2024,October,40,4,2024-10-04,1,5,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,58.0,,162,Transient-Party,96.67,0,0
HB-003127,Resort Hotel,0,62,2023,November,46,18,2023-11-18,2,4,2,0.0,0,Undefined,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,313.0,,0,Transient-Party,69.0,0,0
HB-043387,City Hotel,0,35,2023,September,38,18,2023-09-18,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,F,0,No Deposit,9.0,,0,Transient,145.35,0,1
HB-019941,Resort Hotel,0,19,2024,January,1,3,2024-01-03,2,5,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,242.0,,0,Transient,82.5,1,1
HB-113204,City Hotel,0,135,2025,June,22,1,2025-06-01,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-021029,Resort Hotel,0,0,2024,February,7,15,2024-02-15,1,0,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,45.0,0,0
HB-003540,Resort Hotel,0,131,2023,December,51,22,2023-12-22,2,5,2,0.0,0,HB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,65.57,0,1
HB-002864,Resort Hotel,0,0,2023,November,44,3,2023-11-03,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,46.0,1,0
HB-006637,Resort Hotel,1,247,2024,June,25,22,2024-06-22,0,3,2,0.0,0,HB,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,92.0,0,0
HB-098865,City Hotel,0,21,2024,October,40,3,2024-10-03,1,2,2,0.0,0,SC,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,99.33,0,1
HB-048302,City Hotel,1,60,2024,March,12,20,2024-03-20,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,75.0,0,0
HB-022453,Resort Hotel,0,4,2024,March,12,20,2024-03-20,2,4,3,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,1,No Deposit,,,0,Transient,105.0,0,0
HB-065478,City Hotel,1,112,2025,April,14,4,2025-04-04,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,,385.0,0,Transient,95.0,0,0
HB-064268,City Hotel,1,6,2025,March,10,3,2025-03-03,2,2,1,0.0,0,SC,AGO,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,91.8,0,0
HB-061467,City Hotel,1,97,2024,December,50,12,2024-12-12,2,5,2,1.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,103.7,0,1
HB-004391,Resort Hotel,1,46,2024,March,11,11,2024-03-11,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,375.0,,0,Transient-Party,25.0,0,0
HB-074384,City Hotel,1,283,2023,July,30,27,2023-07-27,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-004496,Resort Hotel,0,207,2024,March,12,20,2024-03-20,2,5,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,70.91,0,0
HB-078943,City Hotel,0,13,2023,October,42,18,2023-10-18,2,0,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Contract,120.0,0,0
HB-029549,Resort Hotel,0,17,2024,October,44,30,2024-10-30,1,0,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,346.0,0,Transient-Party,66.0,1,0
HB-090895,City Hotel,0,140,2024,June,23,9,2024-06-09,1,3,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,113.48,0,0
HB-099027,City Hotel,0,212,2024,October,40,1,2024-10-01,2,5,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,92.65,0,2
HB-097808,City Hotel,0,12,2024,September,38,18,2024-09-18,2,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,171.33,0,1
HB-087844,City Hotel,0,36,2024,April,17,23,2024-04-23,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,118.8,0,1
HB-076028,City Hotel,1,336,2023,September,38,18,2023-09-18,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-081521,City Hotel,0,2,2023,December,50,13,2023-12-13,1,0,2,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,0.0,0,1
HB-078884,City Hotel,0,23,2023,October,42,16,2023-10-16,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,15.0,,0,Transient,98.4,0,2
HB-102526,City Hotel,0,4,2024,November,48,26,2024-11-26,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,75.51,0,0
HB-051894,City Hotel,0,316,2024,May,21,26,2024-05-26,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,110.0,0,0
HB-043563,City Hotel,0,141,2023,September,38,20,2023-09-20,1,0,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,90.0,0,0
HB-078835,City Hotel,0,0,2023,October,41,15,2023-10-15,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,99.0,,0,Transient,100.0,0,0
HB-068129,City Hotel,1,151,2025,May,20,13,2025-05-13,2,2,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,95.0,0,0
HB-042824,City Hotel,0,6,2023,September,36,10,2023-09-10,1,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,116.25,0,2
HB-085294,City Hotel,0,49,2024,March,11,11,2024-03-11,0,2,2,0.0,0,BB,DEU,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,65.0,0,1
HB-067026,City Hotel,1,111,2025,April,17,27,2025-04-27,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,0,Transient,120.0,0,0
HB-054484,City Hotel,1,65,2024,July,29,17,2024-07-17,2,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient-Party,131.75,0,1
HB-040813,City Hotel,0,141,2023,August,32,7,2023-08-07,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,0
HB-082032,City Hotel,1,305,2024,October,40,1,2024-10-01,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,35.0,,17,Transient,100.0,0,0
HB-104354,City Hotel,0,262,2025,January,2,9,2025-01-09,1,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient-Party,81.9,0,2
HB-110382,City Hotel,0,7,2025,April,17,26,2025-04-26,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,D,D,0,No Deposit,,219.0,0,Transient,110.0,0,0
HB-073751,City Hotel,1,265,2023,July,27,9,2023-07-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-089439,City Hotel,0,0,2024,May,21,20,2024-05-20,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,,0,Transient,95.0,0,0
HB-046333,City Hotel,1,140,2023,December,52,29,2023-12-29,0,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,70.0,0,0
HB-054755,City Hotel,1,127,2024,July,30,25,2024-07-25,1,3,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.25,0,0
HB-092181,City Hotel,0,100,2024,June,26,30,2024-06-30,0,2,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,103.5,0,0
HB-061700,City Hotel,1,62,2024,December,52,23,2024-12-23,1,2,2,1.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,120.88,0,1
HB-064851,City Hotel,1,98,2025,March,12,17,2025-03-17,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,68.0,0,1
HB-061220,City Hotel,1,35,2024,December,49,4,2024-12-04,2,5,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,74.8,0,2
HB-019347,Resort Hotel,1,17,2023,December,52,27,2023-12-27,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,1,No Deposit,240.0,,0,Transient,61.0,0,1
HB-095227,City Hotel,0,75,2024,August,33,12,2024-08-12,2,3,3,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,168.3,0,2
HB-057765,City Hotel,1,219,2024,September,40,30,2024-09-30,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,120.0,0,0
HB-054732,City Hotel,1,35,2024,July,30,25,2024-07-25,1,0,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.1,0,0
HB-086094,City Hotel,0,77,2024,March,13,25,2024-03-25,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,109.8,0,0
HB-061376,City Hotel,1,60,2024,December,49,8,2024-12-08,1,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.4,0,2
HB-086735,City Hotel,0,1,2024,April,14,6,2024-04-06,0,2,3,0.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient,197.0,0,0
HB-097486,City Hotel,0,21,2024,September,37,15,2024-09-15,0,2,1,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,139.0,0,2
HB-051911,City Hotel,0,316,2024,May,21,26,2024-05-26,0,3,2,0.0,0,BB,AUT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,110.0,0,0
HB-103829,City Hotel,0,278,2024,December,52,28,2024-12-28,1,4,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,71.23,0,1
HB-004262,Resort Hotel,0,123,2024,February,9,27,2024-02-27,1,1,2,0.0,0,FB,ESP,Groups,Direct,0,0,0,A,A,0,No Deposit,38.0,,0,Transient-Party,64.0,0,0
HB-111496,City Hotel,0,34,2025,May,19,9,2025-05-09,0,2,1,0.0,0,BB,RUS,Groups,TA/TO,0,0,0,A,A,2,No Deposit,39.0,,0,Transient-Party,130.0,0,0
HB-024248,Resort Hotel,0,236,2024,May,19,12,2024-05-12,0,3,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,315.0,,0,Transient-Party,48.0,0,0
HB-061254,City Hotel,1,102,2024,December,49,6,2024-12-06,0,2,1,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,B,1,No Deposit,9.0,,0,Transient,86.4,0,2
HB-088212,City Hotel,0,10,2024,April,18,30,2024-04-30,2,1,3,0.0,0,BB,DEU,Direct,Direct,0,0,0,D,F,1,No Deposit,,,0,Transient,183.0,1,2
HB-026681,Resort Hotel,0,187,2025,August,31,1,2025-08-01,2,5,2,0.0,0,BB,PRT,Direct,Direct,1,0,1,D,D,0,No Deposit,,,0,Transient,175.23,1,1
HB-040315,City Hotel,0,20,2023,July,29,22,2023-07-22,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-101574,City Hotel,0,54,2024,November,46,11,2024-11-11,1,2,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.0,0,1
HB-040364,City Hotel,0,132,2023,July,29,23,2023-07-23,0,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,90.0,0,0
HB-021515,Resort Hotel,0,1,2024,March,9,1,2024-03-01,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,0
HB-090851,City Hotel,0,136,2024,June,23,9,2024-06-09,1,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,2,No Deposit,,,0,Transient,103.68,0,2
HB-051559,City Hotel,1,23,2024,May,21,21,2024-05-21,1,1,1,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,156.0,0,0
HB-008055,Resort Hotel,1,293,2024,September,36,8,2024-09-08,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,90.0,0,1
HB-050091,City Hotel,0,120,2024,April,17,23,2024-04-23,1,1,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,95.2,0,0
HB-085843,City Hotel,0,0,2024,March,12,21,2024-03-21,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,99.0,0,0
HB-021411,Resort Hotel,0,3,2024,February,9,27,2024-02-27,1,1,1,0.0,0,FB,ESP,Complementary,TA/TO,0,0,0,A,A,2,No Deposit,38.0,,0,Transient-Party,0.0,0,0
HB-065868,City Hotel,1,66,2025,April,15,9,2025-04-09,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-035725,Resort Hotel,0,28,2025,April,17,26,2025-04-26,0,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,G,G,1,No Deposit,240.0,,0,Transient-Party,165.0,1,0
HB-018972,Resort Hotel,0,16,2024,February,5,4,2024-02-04,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,1,0,1,A,D,0,No Deposit,240.0,,0,Transient,14.0,1,1
HB-115908,City Hotel,0,23,2025,July,28,11,2025-07-11,0,2,1,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,112.0,0,1
HB-078394,City Hotel,0,6,2024,March,13,29,2024-03-29,0,4,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,6,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-107584,City Hotel,0,3,2025,March,11,13,2025-03-13,1,1,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,177.0,1,0
HB-021488,Resort Hotel,0,0,2024,February,9,29,2024-02-29,1,0,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,43.0,0,0
HB-030225,Resort Hotel,0,80,2024,November,44,3,2024-11-03,4,10,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,E,E,2,No Deposit,240.0,,0,Transient,85.8,1,1
HB-064490,City Hotel,1,127,2025,March,11,11,2025-03-11,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,0,Transient,80.0,0,0
HB-015717,Resort Hotel,1,245,2023,September,39,25,2023-09-25,0,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,248.0,,0,Transient,80.0,0,0
HB-088372,City Hotel,0,79,2024,May,18,2,2024-05-02,1,2,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,116.1,0,0
HB-000954,Resort Hotel,1,113,2023,August,32,7,2023-08-07,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,105.0,,0,Transient-Party,154.38,0,1
HB-040762,City Hotel,1,0,2023,August,32,7,2023-08-07,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.0,0,0
HB-001397,Resort Hotel,0,4,2023,August,35,28,2023-08-28,0,2,2,1.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,G,1,No Deposit,242.0,,0,Transient,180.55,0,2
HB-066279,City Hotel,1,62,2025,April,16,16,2025-04-16,2,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,126.0,0,0
HB-002710,Resort Hotel,0,3,2023,October,43,27,2023-10-27,0,2,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,49.2,1,1
HB-027843,Resort Hotel,0,223,2024,September,36,5,2024-09-05,3,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,314.0,,0,Transient,77.6,0,1
HB-025268,Resort Hotel,0,152,2024,June,24,14,2024-06-14,2,5,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,E,0,No Deposit,250.0,,0,Transient,100.6,0,1
HB-064178,City Hotel,1,28,2025,March,9,2,2025-03-02,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,95.0,0,0
HB-044838,City Hotel,0,60,2023,October,41,12,2023-10-12,1,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,3.0,,0,Transient-Party,60.0,0,0
HB-059500,City Hotel,1,189,2024,October,44,28,2024-10-28,1,2,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,109.8,0,0
HB-049411,City Hotel,0,101,2024,April,15,12,2024-04-12,2,5,2,0.0,0,BB,LUX,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,93.38,0,0
HB-077041,City Hotel,1,262,2023,November,45,9,2023-11-09,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-085432,City Hotel,0,0,2024,March,11,15,2024-03-15,0,0,2,0.0,0,BB,PRT,Complementary,Direct,1,0,0,A,A,0,No Deposit,,,0,Transient,0.0,0,0
HB-115854,City Hotel,0,98,2025,July,28,9,2025-07-09,2,1,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,86.4,0,1
HB-019963,Resort Hotel,0,23,2024,January,1,7,2024-01-07,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,68.0,1,0
HB-091960,City Hotel,0,74,2024,June,26,27,2024-06-27,1,0,2,1.0,0,BB,FIN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,112.5,0,0
HB-106913,City Hotel,0,192,2025,March,9,2,2025-03-02,0,3,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,86.4,0,2
HB-072953,City Hotel,1,112,2025,August,32,10,2025-08-10,1,3,3,0.0,0,SC,DNK,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.0,0,0
HB-064066,City Hotel,1,199,2025,February,9,28,2025-02-28,0,2,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,2
HB-017212,Resort Hotel,0,167,2023,September,37,17,2023-09-17,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Contract,45.9,0,0
HB-111840,City Hotel,0,6,2025,May,20,14,2025-05-14,2,1,1,0.0,0,BB,CHL,Groups,Corporate,0,0,0,A,A,0,No Deposit,,169.0,0,Transient-Party,110.0,0,0
HB-042135,City Hotel,0,7,2023,August,35,31,2023-08-31,1,5,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,75.0,0,0
HB-008140,Resort Hotel,1,0,2024,September,37,14,2024-09-14,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,86.0,0,0
HB-117434,City Hotel,0,2,2025,August,31,3,2025-08-03,0,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,509.0,,0,Transient-Party,166.0,0,0
HB-090660,City Hotel,0,118,2024,June,23,6,2024-06-06,1,2,1,0.0,0,BB,PRT,Offline TA/TO,Corporate,0,0,0,A,A,0,No Deposit,191.0,,0,Transient-Party,110.0,0,0
HB-096209,City Hotel,0,12,2024,December,49,8,2024-12-08,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,7,A,A,0,No Deposit,,40.0,0,Transient,67.0,0,1
HB-110005,City Hotel,0,16,2025,April,16,18,2025-04-18,0,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,115.0,0,2
HB-104268,City Hotel,0,16,2025,January,2,8,2025-01-08,2,0,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.5,0,0
HB-087904,City Hotel,0,209,2024,April,17,25,2024-04-25,1,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,81.77,0,1
HB-060414,City Hotel,1,489,2024,November,45,10,2024-11-10,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-098712,City Hotel,0,281,2024,October,40,1,2024-10-01,2,1,2,1.0,0,HB,ITA,Groups,TA/TO,0,0,0,A,D,1,No Deposit,1.0,,174,Transient-Party,96.0,0,0
HB-053171,City Hotel,1,245,2024,June,25,17,2024-06-17,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,0,Transient,75.0,0,0
HB-031887,Resort Hotel,0,0,2025,January,2,9,2025-01-09,1,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,30.0,0,0
HB-007681,Resort Hotel,1,190,2024,August,34,20,2024-08-20,2,3,2,1.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,3.0,,0,Transient,144.0,0,2
HB-089615,City Hotel,0,36,2024,May,21,21,2024-05-21,2,1,2,0.0,0,BB,NOR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,42.0,,0,Transient,85.5,0,0
HB-062881,City Hotel,1,159,2025,January,4,23,2025-01-23,1,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.0,0,0
HB-063959,City Hotel,1,134,2025,February,9,25,2025-02-25,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,75.0,0,0
HB-039002,Resort Hotel,0,173,2025,July,30,24,2025-07-24,3,9,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,160.0,0,2
HB-010276,Resort Hotel,1,27,2025,February,9,24,2025-02-24,1,2,2,1.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,110.0,0,0
HB-116297,City Hotel,0,11,2025,July,29,16,2025-07-16,2,0,1,0.0,0,BB,KOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,129.0,0,1
HB-084830,City Hotel,0,5,2024,March,9,1,2024-03-01,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient,51.0,0,0
HB-066952,City Hotel,1,110,2025,April,17,26,2025-04-26,1,4,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,190.8,0,0
HB-040062,City Hotel,1,88,2023,July,26,1,2023-07-01,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,1
HB-063130,City Hotel,1,56,2025,February,5,1,2025-02-01,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,60.0,0,0
HB-119361,City Hotel,0,195,2025,August,35,29,2025-08-29,1,5,2,0.0,0,BB,JPN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,1
HB-034708,Resort Hotel,1,0,2025,August,34,24,2025-08-24,0,1,1,0.0,0,BB,AGO,Direct,Direct,1,0,2,G,G,0,No Deposit,,,0,Transient,190.0,0,0
HB-000741,Resort Hotel,1,74,2023,July,30,27,2023-07-27,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,171.0,,0,Transient,107.0,0,1
HB-072485,City Hotel,1,67,2025,July,31,29,2025-07-29,2,1,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient,120.0,0,1
HB-015910,Resort Hotel,0,93,2023,August,31,2,2023-08-02,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,134.0,0,3
HB-009618,Resort Hotel,1,208,2024,December,51,20,2024-12-20,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,37.8,0,0
HB-075627,City Hotel,1,281,2023,July,30,25,2023-07-25,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-106343,City Hotel,0,17,2025,February,8,18,2025-02-18,2,4,2,1.0,0,BB,FRA,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,114.21,0,1
HB-056540,City Hotel,1,433,2024,September,36,8,2024-09-08,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,70.0,0,0
HB-117389,City Hotel,0,81,2025,July,31,31,2025-07-31,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,114.67,0,1
HB-116979,City Hotel,0,174,2025,July,29,18,2025-07-18,2,8,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,93.78,1,0
HB-098875,City Hotel,0,12,2024,October,40,3,2024-10-03,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-070679,City Hotel,1,294,2025,June,25,20,2025-06-20,2,7,2,0.0,0,SC,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,1
HB-017617,Resort Hotel,0,287,2023,October,41,15,2023-10-15,0,3,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,F,1,No Deposit,,223.0,0,Transient-Party,44.5,0,0
HB-088522,City Hotel,0,0,2024,May,19,6,2024-05-06,0,2,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,139.0,0,1
HB-003464,Resort Hotel,0,71,2023,December,50,15,2023-12-15,0,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,I,1,No Deposit,240.0,,0,Transient,0.0,0,0
HB-012843,Resort Hotel,1,187,2025,July,29,19,2025-07-19,2,6,2,0.0,0,HB,RUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,183.28,0,1
HB-016236,Resort Hotel,0,124,2023,August,33,17,2023-08-17,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,240.0,,0,Transient,120.6,0,0
HB-116189,City Hotel,0,0,2025,July,29,15,2025-07-15,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,2
HB-081288,City Hotel,0,17,2023,December,49,4,2023-12-04,2,2,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,101.5,1,2
HB-098829,City Hotel,0,9,2024,October,40,2,2024-10-02,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,85.0,0,1
HB-062995,City Hotel,1,61,2025,January,4,25,2025-01-25,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,326.0,,0,Transient,80.0,0,0
HB-017524,Resort Hotel,0,26,2025,May,21,24,2025-05-24,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,1,0,1,A,E,0,No Deposit,146.0,,0,Group,45.0,0,0
HB-065535,City Hotel,1,54,2025,April,14,5,2025-04-05,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-031128,Resort Hotel,0,47,2024,December,49,8,2024-12-08,2,5,2,0.0,0,Undefined,FRA,Offline TA/TO,TA/TO,0,0,0,A,C,0,No Deposit,464.0,,0,Transient,64.0,0,0
HB-020001,Resort Hotel,0,5,2024,January,2,9,2024-01-09,2,2,2,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,50.0,0,1
HB-033587,Resort Hotel,0,88,2025,February,9,25,2025-02-25,1,1,2,2.0,0,BB,USA,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,82.0,0,1
HB-033783,Resort Hotel,0,7,2025,March,9,2,2025-03-02,0,2,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,D,D,0,No Deposit,,223.0,0,Transient-Party,54.0,1,0
HB-030775,Resort Hotel,0,128,2024,December,49,3,2024-12-03,0,1,2,0.0,0,HB,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,64.0,0,1
HB-061926,City Hotel,1,16,2024,December,52,28,2024-12-28,2,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,76.67,0,0
HB-084206,City Hotel,0,15,2024,February,7,18,2024-02-18,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,196.0,,0,Transient-Party,86.0,0,0
HB-087271,City Hotel,0,154,2024,April,16,15,2024-04-15,0,2,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,135.0,0,2
HB-117927,City Hotel,0,221,2025,August,32,10,2025-08-10,0,2,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,148.5,0,1
HB-105133,City Hotel,0,2,2025,January,5,27,2025-01-27,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-037975,Resort Hotel,0,276,2025,July,27,2,2025-07-02,2,1,2,0.0,0,HB,LTU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,103.37,1,1
HB-064698,City Hotel,1,92,2025,March,11,15,2025-03-15,0,3,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,85.0,0,0
HB-005975,Resort Hotel,1,40,2024,May,20,18,2024-05-18,0,2,1,0.0,0,BB,PRT,Groups,Corporate,0,0,0,A,A,0,Non Refund,,,0,Transient,55.0,0,0
HB-018209,Resort Hotel,0,36,2023,November,45,7,2023-11-07,2,6,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,E,E,2,No Deposit,185.0,281.0,0,Transient-Party,52.2,0,0
HB-028128,Resort Hotel,0,45,2024,September,38,18,2024-09-18,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,86.0,0,2
HB-014747,Resort Hotel,1,259,2023,September,37,17,2023-09-17,0,3,1,0.0,0,BB,GBR,Groups,Corporate,0,1,0,A,A,0,Non Refund,,223.0,0,Transient,33.3,0,0
HB-052223,City Hotel,1,55,2024,June,22,2,2024-06-02,0,2,3,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,159.3,0,0
HB-016471,Resort Hotel,0,12,2023,August,34,24,2023-08-24,1,5,2,0.0,0,BB,MAR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,198.33,0,2
HB-057890,City Hotel,1,258,2024,October,40,2,2024-10-02,2,5,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.1,0,0
HB-075538,City Hotel,1,355,2023,October,40,7,2023-10-07,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-103179,City Hotel,0,83,2024,December,50,11,2024-12-11,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-006656,Resort Hotel,0,322,2024,June,25,22,2024-06-22,0,3,2,0.0,0,HB,POL,Groups,Direct,0,0,0,A,A,0,No Deposit,,,75,Transient-Party,92.0,0,0
HB-077166,City Hotel,0,0,2024,December,51,19,2024-12-19,1,1,2,0.0,0,BB,PRT,Complementary,Direct,1,4,20,G,G,1,No Deposit,,45.0,0,Transient,0.0,0,2
HB-098616,City Hotel,0,10,2024,September,40,30,2024-09-30,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,204.0,0,2
HB-011644,Resort Hotel,1,280,2025,May,21,23,2025-05-23,0,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient,54.0,0,1
HB-056307,City Hotel,1,60,2024,September,36,3,2024-09-03,1,1,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,123.3,0,1
HB-098231,City Hotel,0,19,2024,September,39,23,2024-09-23,1,2,2,0.0,0,SC,ISR,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,7.0,,0,Transient,107.03,0,1
HB-063641,City Hotel,1,70,2025,February,7,16,2025-02-16,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,95.4,0,2
HB-024924,Resort Hotel,0,143,2024,June,22,2,2024-06-02,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,26.0,,0,Transient,70.98,0,0
HB-090979,City Hotel,0,95,2024,June,24,10,2024-06-10,2,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,119.85,0,1
HB-058055,City Hotel,1,275,2024,October,40,5,2024-10-05,1,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,44.0,,0,Transient,90.0,0,0
HB-071352,City Hotel,1,230,2025,July,27,3,2025-07-03,1,2,2,0.0,0,BB,PHL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,1
HB-113120,City Hotel,0,409,2025,May,22,31,2025-05-31,0,3,2,0.0,0,BB,AUS,Groups,TA/TO,0,0,0,A,A,3,No Deposit,229.0,,0,Transient-Party,112.67,0,1
HB-065795,City Hotel,1,147,2025,April,15,8,2025-04-08,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,117.0,0,1
HB-061128,City Hotel,1,105,2024,December,49,2,2024-12-02,0,2,2,1.0,0,HB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,152.55,0,0
HB-028456,Resort Hotel,0,214,2024,September,39,27,2024-09-27,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,40.0,,0,Contract,84.95,0,0
HB-067289,City Hotel,1,61,2025,May,18,1,2025-05-01,1,2,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-032001,Resort Hotel,0,4,2025,January,3,13,2025-01-13,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,314.0,,0,Transient-Party,38.4,0,0
HB-064657,City Hotel,1,50,2025,March,11,14,2025-03-14,0,4,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,0
HB-117344,City Hotel,0,54,2025,July,31,31,2025-07-31,1,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,10.0,,0,Transient,95.0,0,0
HB-042484,City Hotel,0,1,2023,September,36,6,2023-09-06,2,0,1,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,B,0,No Deposit,1.0,,0,Transient-Party,75.0,0,0
HB-004446,Resort Hotel,1,25,2024,March,12,18,2024-03-18,2,4,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,196.0,,0,Transient,38.0,0,0
HB-100149,City Hotel,0,71,2024,October,43,22,2024-10-22,1,1,2,0.0,0,HB,CN,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,39.0,,0,Transient-Party,142.5,0,0
HB-087984,City Hotel,0,186,2024,April,17,24,2024-04-24,2,3,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,68.55,0,0
HB-041270,City Hotel,0,39,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-048857,City Hotel,0,86,2024,March,13,31,2024-03-31,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,82.45,0,1
HB-117319,City Hotel,0,3,2025,July,31,31,2025-07-31,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-026154,Resort Hotel,0,0,2024,July,30,22,2024-07-22,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,166.0,0,0
HB-058446,City Hotel,1,279,2024,October,41,12,2024-10-12,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,98.0,,0,Transient,110.0,0,0
HB-004315,Resort Hotel,1,2,2024,March,10,4,2024-03-04,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient,75.0,0,1
HB-099017,City Hotel,0,174,2024,October,40,4,2024-10-04,0,4,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,141.3,0,0
HB-009068,Resort Hotel,1,54,2024,October,43,26,2024-10-26,2,6,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,74.04,0,0
HB-069886,City Hotel,1,181,2025,June,23,8,2025-06-08,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,0,Transient,100.0,0,0
HB-074481,City Hotel,1,318,2023,August,35,31,2023-08-31,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-084178,City Hotel,0,2,2024,February,7,17,2024-02-17,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,72.0,0,0
HB-010351,Resort Hotel,1,49,2025,February,9,28,2025-02-28,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,332.0,,0,Transient,35.0,0,0
HB-003146,Resort Hotel,0,36,2023,November,47,20,2023-11-20,0,2,2,0.0,0,FB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,38.0,,0,Transient-Party,64.0,0,0
HB-047607,City Hotel,1,1,2024,February,9,28,2024-02-28,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,60.0,0,0
HB-044978,City Hotel,0,102,2023,October,42,16,2023-10-16,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-114999,City Hotel,0,219,2025,June,25,20,2025-06-20,2,8,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.5,0,1
HB-026656,Resort Hotel,0,37,2024,August,32,5,2024-08-05,0,2,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,246.0,0,2
HB-023205,Resort Hotel,0,59,2024,April,15,11,2024-04-11,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,53.4,0,2
HB-058064,City Hotel,1,275,2024,October,40,5,2024-10-05,1,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,44.0,,0,Transient,90.0,0,0
HB-035670,Resort Hotel,0,252,2025,April,17,22,2025-04-22,2,5,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,D,D,2,No Deposit,273.0,,0,Transient-Party,76.8,0,0
HB-002018,Resort Hotel,1,81,2023,September,39,27,2023-09-27,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,66.29,0,0
HB-088712,City Hotel,0,55,2024,May,19,6,2024-05-06,2,3,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,164.9,0,1
HB-070009,City Hotel,1,94,2025,June,23,8,2025-06-08,0,3,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,189.0,0,0
HB-078542,City Hotel,0,7,2023,October,41,12,2023-10-12,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-042507,City Hotel,0,55,2023,September,36,6,2023-09-06,2,0,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,75.0,0,0
HB-110450,City Hotel,0,63,2025,April,17,26,2025-04-26,0,2,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,135.0,0,0
HB-036438,Resort Hotel,0,93,2025,May,20,18,2025-05-18,0,3,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,C,C,1,No Deposit,240.0,,0,Transient,123.0,0,2
HB-043608,City Hotel,0,60,2023,September,38,21,2023-09-21,1,1,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,20.0,,0,Transient-Party,0.0,0,0
HB-012817,Resort Hotel,1,236,2025,July,29,17,2025-07-17,5,11,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,242.0,,0,Transient,182.92,0,0
HB-071652,City Hotel,1,107,2025,July,28,9,2025-07-09,2,2,3,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,171.0,0,0
HB-107904,City Hotel,0,96,2025,March,12,17,2025-03-17,1,2,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,79.2,0,0
HB-102964,City Hotel,0,16,2024,December,49,8,2024-12-08,0,2,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,75.0,0,0
HB-043180,City Hotel,0,7,2023,September,37,16,2023-09-16,0,2,1,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,13.0,,0,Contract,113.6,0,0
HB-085363,City Hotel,0,88,2024,March,11,12,2024-03-12,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,E,0,No Deposit,28.0,,0,Transient,58.0,0,0
HB-086611,City Hotel,0,68,2024,April,14,4,2024-04-04,1,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.3,0,1
HB-055038,City Hotel,1,122,2024,August,31,3,2024-08-03,0,4,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.95,0,1
HB-092406,City Hotel,0,68,2024,July,27,4,2024-07-04,1,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,6.0,,0,Transient,107.95,0,0
HB-050793,City Hotel,1,108,2024,May,19,8,2024-05-08,2,0,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,16.0,,0,Transient,110.75,0,0
HB-011643,Resort Hotel,1,8,2025,May,21,23,2025-05-23,0,2,1,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,54.0,0,1
HB-096557,City Hotel,0,1,2024,September,36,3,2024-09-03,0,1,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,149.0,0,1
HB-027121,Resort Hotel,0,2,2024,August,34,19,2024-08-19,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,339.0,,0,Transient,159.2,0,2
HB-063658,City Hotel,1,15,2025,February,8,17,2025-02-17,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,95.0,0,0
HB-020801,Resort Hotel,0,69,2024,February,6,8,2024-02-08,1,1,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,26.0,0,0
HB-105604,City Hotel,0,28,2025,February,6,8,2025-02-08,0,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,100.8,0,1
HB-027920,Resort Hotel,0,223,2024,September,35,1,2024-09-01,4,10,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Contract,81.9,0,0
HB-041355,City Hotel,0,4,2023,August,33,15,2023-08-15,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,9.0,,0,Contract,124.0,0,1
HB-091000,City Hotel,0,15,2024,June,24,14,2024-06-14,0,1,1,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.0,0,1
HB-042689,City Hotel,0,69,2023,September,36,9,2023-09-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-110986,City Hotel,0,102,2025,May,18,2,2025-05-02,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-053352,City Hotel,0,168,2024,June,25,18,2024-06-18,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,116.55,0,2
HB-008904,Resort Hotel,1,123,2024,October,42,19,2024-10-19,0,4,2,0.0,0,BB,ZAF,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,240.0,,0,Transient,58.0,0,2
HB-045120,City Hotel,0,84,2023,October,42,16,2023-10-16,1,2,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,8.0,,0,Transient,89.25,0,2
HB-079682,City Hotel,0,6,2023,October,44,30,2023-10-30,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,87.27,0,1
HB-111603,City Hotel,0,68,2025,May,19,9,2025-05-09,0,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,162.0,0,1
HB-003781,Resort Hotel,1,20,2024,January,1,4,2024-01-04,1,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,242.0,,0,Transient,54.4,0,1
HB-110274,City Hotel,0,68,2025,April,16,20,2025-04-20,2,3,2,0.0,0,BB,ROU,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,108.0,0,3
HB-015083,Resort Hotel,1,152,2023,July,29,18,2023-07-18,2,6,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,1,No Deposit,142.0,,0,Contract,126.1,0,1
HB-057627,City Hotel,1,447,2024,September,39,29,2024-09-29,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-052249,City Hotel,1,330,2024,June,22,2,2024-06-02,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-019226,Resort Hotel,1,92,2024,February,9,26,2024-02-26,1,2,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,134.0,,0,Transient,79.0,0,0
HB-101240,City Hotel,0,0,2024,November,45,5,2024-11-05,2,2,2,0.0,0,BB,AGO,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,89.0,0,0
HB-091448,City Hotel,0,117,2024,June,25,17,2024-06-17,2,3,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.74,0,1
HB-111000,City Hotel,0,67,2025,May,18,2,2025-05-02,0,3,2,0.0,0,BB,NOR,Groups,Corporate,0,0,0,A,A,0,No Deposit,,409.0,0,Transient-Party,120.0,0,0
HB-018356,Resort Hotel,1,82,2024,February,6,7,2024-02-07,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,67.0,,0,Transient-Party,86.0,0,0
HB-101669,City Hotel,0,0,2024,November,46,15,2024-11-15,0,1,1,0.0,0,SC,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,88.0,0,0
HB-010277,Resort Hotel,1,46,2025,February,9,24,2025-02-24,1,2,2,1.0,0,BB,FRA,Direct,Direct,0,0,0,G,G,0,No Deposit,250.0,,0,Transient,87.0,0,0
HB-113205,City Hotel,0,107,2025,June,22,1,2025-06-01,0,3,2,1.0,0,BB,ISR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,156.0,0,3
HB-063996,City Hotel,1,23,2025,February,9,25,2025-02-25,4,11,2,0.0,0,BB,AGO,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,113.0,0,0
HB-082035,City Hotel,1,305,2024,October,40,1,2024-10-01,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,35.0,,17,Transient,100.0,0,0
HB-036512,Resort Hotel,0,118,2025,May,21,22,2025-05-22,1,0,2,0.0,0,BB,NOR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,251.0,,0,Transient-Party,62.0,0,0
HB-046839,City Hotel,1,18,2024,January,3,20,2024-01-20,0,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,87.0,0,2
HB-078214,City Hotel,0,7,2023,October,40,5,2023-10-05,1,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,26.0,,0,Transient-Party,112.2,0,0
HB-027438,Resort Hotel,0,22,2024,August,35,27,2024-08-27,1,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,216.0,0,1
HB-057343,City Hotel,1,254,2024,September,39,24,2024-09-24,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,96.0,0,0
HB-087280,City Hotel,0,122,2024,April,16,15,2024-04-15,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,151.0,,56,Transient-Party,85.0,0,0
HB-092207,City Hotel,0,99,2024,June,26,27,2024-06-27,1,4,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,94.35,0,1
HB-002613,Resort Hotel,1,165,2023,October,43,23,2023-10-23,2,5,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,47.0,0,2
HB-065842,City Hotel,1,66,2025,April,15,9,2025-04-09,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-010847,Resort Hotel,1,351,2025,April,15,8,2025-04-08,2,5,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,D,D,0,No Deposit,298.0,,0,Transient-Party,82.0,0,0
HB-074296,City Hotel,1,330,2023,September,37,12,2023-09-12,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-051607,City Hotel,1,28,2024,May,21,22,2024-05-22,2,2,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,149.15,0,0
HB-117843,City Hotel,0,208,2025,August,32,6,2025-08-06,2,3,2,0.0,0,SC,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,132.0,,0,Transient,67.15,0,1
HB-067247,City Hotel,1,105,2025,April,18,30,2025-04-30,2,0,1,0.0,0,SC,PHL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,103.5,0,0
HB-018711,Resort Hotel,0,0,2024,April,16,19,2024-04-19,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,H,0,No Deposit,,137.0,0,Transient,74.0,0,0
HB-023131,Resort Hotel,0,20,2024,April,15,12,2024-04-12,0,4,1,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,177.0,,0,Transient,35.1,0,1
HB-061158,City Hotel,1,57,2024,December,49,2,2024-12-02,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.4,0,1
HB-010902,Resort Hotel,1,124,2025,April,15,9,2025-04-09,2,5,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,C,1,Non Refund,492.0,,0,Transient,80.0,0,0
HB-006221,Resort Hotel,1,108,2024,May,22,28,2024-05-28,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,76.86,0,1
HB-102973,City Hotel,0,259,2024,December,49,7,2024-12-07,0,4,3,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,104.55,0,1
HB-054590,City Hotel,0,207,2024,July,29,20,2024-07-20,1,4,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,80.75,0,0
HB-023691,Resort Hotel,0,1,2024,May,18,2,2024-05-02,1,0,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,90.0,0,0
HB-099950,City Hotel,0,66,2024,October,42,17,2024-10-17,1,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.8,0,1
HB-002039,Resort Hotel,1,56,2023,September,39,28,2023-09-28,2,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,108.09,0,2
HB-109817,City Hotel,0,94,2025,April,16,14,2025-04-14,1,2,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,42.0,,0,Transient,98.1,1,0
HB-096677,City Hotel,0,15,2024,September,36,5,2024-09-05,1,0,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,119.0,0,0
HB-043968,City Hotel,1,88,2023,September,39,26,2023-09-26,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-067160,City Hotel,1,26,2025,April,18,29,2025-04-29,1,1,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,103.5,0,1
HB-098298,City Hotel,0,34,2024,September,39,25,2024-09-25,2,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,82.23,0,1
HB-112891,City Hotel,0,140,2025,May,21,25,2025-05-25,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.5,0,1
HB-108537,City Hotel,0,158,2025,March,13,27,2025-03-27,1,1,2,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,95.0,0,1
HB-107585,City Hotel,0,0,2025,March,11,14,2025-03-14,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,85.0,0,0
HB-063596,City Hotel,1,8,2025,February,7,15,2025-02-15,0,3,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,168.0,0,0
HB-088766,City Hotel,0,14,2024,September,37,14,2024-09-14,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,4,A,E,0,No Deposit,,219.0,0,Transient,89.0,0,1
HB-043587,City Hotel,0,13,2023,September,38,20,2023-09-20,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,G,0,No Deposit,10.0,,0,Transient,111.6,0,1
HB-065621,City Hotel,1,312,2025,April,14,6,2025-04-06,0,2,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,109.8,0,0
HB-090366,City Hotel,0,213,2024,May,22,29,2024-05-29,3,5,2,0.0,0,BB,ROU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient-Party,80.24,0,1
HB-084955,City Hotel,0,4,2024,March,10,7,2024-03-07,1,3,2,0.0,0,HB,DZA,Offline TA/TO,TA/TO,0,0,1,A,A,0,No Deposit,12.0,,0,Transient-Party,106.0,0,0
HB-046530,City Hotel,0,1,2024,January,1,4,2024-01-04,1,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,9.0,,0,Transient,99.0,0,0
HB-099636,City Hotel,0,335,2024,October,41,13,2024-10-13,0,3,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,80.0,0,0
HB-119186,City Hotel,0,213,2025,August,35,28,2025-08-28,1,3,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,19.0,,0,Transient-Party,104.0,0,0
HB-030938,Resort Hotel,0,1,2024,December,49,4,2024-12-04,2,3,1,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,D,1,No Deposit,250.0,,0,Transient,52.75,0,0
HB-031125,Resort Hotel,0,10,2024,December,50,12,2024-12-12,1,2,2,0.0,0,BB,POL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,26.0,,0,Transient,36.0,0,0
HB-106666,City Hotel,0,130,2025,February,9,25,2025-02-25,2,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,96.9,0,1
HB-094509,City Hotel,0,0,2024,August,31,4,2024-08-04,0,1,2,0.0,0,SC,PRT,Direct,Direct,0,0,0,B,B,1,No Deposit,,,0,Transient,120.0,0,0
HB-041930,City Hotel,0,8,2023,August,34,26,2023-08-26,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,9.0,,0,Contract,90.0,0,2
HB-113040,City Hotel,0,7,2025,May,22,31,2025-05-31,0,1,1,0.0,0,BB,PRT,Aviation,Corporate,0,0,0,D,D,0,No Deposit,,153.0,0,Transient,110.0,0,0
HB-030335,Resort Hotel,0,7,2024,November,47,18,2024-11-18,0,2,2,0.0,0,BB,MAR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,314.0,,0,Transient,72.0,1,0
HB-052019,City Hotel,1,48,2024,May,22,29,2024-05-29,2,0,2,0.0,0,BB,KOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,121.5,0,0
HB-080392,City Hotel,1,34,2023,December,49,8,2023-12-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,0,Transient,90.0,0,0
HB-096605,City Hotel,0,66,2024,September,36,2,2024-09-02,1,2,2,0.0,0,SC,COL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,87.3,0,1
HB-110550,City Hotel,0,83,2025,April,17,25,2025-04-25,0,4,2,1.0,0,BB,UKR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,148.5,1,2
HB-066720,City Hotel,1,55,2025,April,17,23,2025-04-23,2,2,2,0.0,0,BB,TUR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,162.0,0,0
HB-054752,City Hotel,1,195,2024,July,30,25,2024-07-25,1,3,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.75,0,0
HB-048118,City Hotel,1,75,2024,March,11,17,2024-03-17,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient,80.0,0,0
HB-077749,City Hotel,0,0,2023,September,38,21,2023-09-21,1,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,B,0,No Deposit,,,0,Transient,147.0,0,1
HB-091576,City Hotel,0,31,2024,June,25,17,2024-06-17,2,5,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,85.0,,0,Transient,96.3,0,0
HB-107663,City Hotel,0,11,2025,March,11,12,2025-03-12,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.93,0,1
HB-025866,Resort Hotel,0,0,2024,July,28,13,2024-07-13,0,1,2,0.0,0,BB,USA,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,161.0,0,0
HB-078071,City Hotel,1,282,2023,October,41,10,2023-10-10,2,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,4.0,,0,Transient-Party,96.0,0,0
HB-015164,Resort Hotel,1,244,2023,September,35,2,2023-09-02,2,5,2,0.0,0,BB,IRL,Groups,TA/TO,0,24,0,A,A,0,No Deposit,96.0,,0,Transient-Party,8.0,0,0
HB-093780,City Hotel,0,83,2024,July,30,24,2024-07-24,2,1,3,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,22.0,,0,Transient,96.9,0,1
HB-071186,City Hotel,1,200,2025,June,26,29,2025-06-29,0,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,0
HB-045532,City Hotel,0,62,2023,November,44,1,2023-11-01,2,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,6.0,,0,Transient,63.3,0,0
HB-065132,City Hotel,1,157,2025,March,13,25,2025-03-25,2,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.6,0,0
HB-090267,City Hotel,0,112,2024,June,22,2,2024-06-02,0,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,100.0,0,0
HB-033401,Resort Hotel,0,41,2025,February,8,18,2025-02-18,2,2,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,196.0,,0,Transient-Party,43.0,0,0
HB-072135,City Hotel,1,423,2025,July,30,22,2025-07-22,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,80.0,0,0
HB-098103,City Hotel,0,141,2024,September,39,23,2024-09-23,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,3,No Deposit,9.0,,0,Transient,123.8,0,1
HB-106830,City Hotel,0,5,2025,February,9,28,2025-02-28,0,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,91.8,0,2
HB-035483,Resort Hotel,0,76,2025,April,17,21,2025-04-21,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,F,0,No Deposit,241.0,,0,Transient,47.55,0,1
HB-036435,Resort Hotel,0,85,2025,May,20,14,2025-05-14,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,80.85,0,0
HB-092751,City Hotel,0,10,2024,July,28,9,2024-07-09,1,1,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,73.0,0,0
HB-098332,City Hotel,0,112,2024,September,39,26,2024-09-26,1,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,139.8,0,0
HB-043502,City Hotel,1,74,2023,September,38,18,2023-09-18,0,2,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient-Party,80.0,0,0
HB-072186,City Hotel,1,197,2025,July,30,23,2025-07-23,2,1,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,180.0,0,0
HB-092710,City Hotel,0,80,2024,July,28,8,2024-07-08,1,2,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,147.9,0,3
HB-063986,City Hotel,1,35,2025,February,9,25,2025-02-25,2,2,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,134.3,0,1
HB-021734,Resort Hotel,0,25,2024,March,10,6,2024-03-06,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-074093,City Hotel,1,321,2023,September,35,3,2023-09-03,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-118652,City Hotel,0,189,2025,August,35,27,2025-08-27,2,0,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,1,A,A,1,No Deposit,9.0,,0,Transient-Party,119.0,0,3
HB-068752,City Hotel,1,420,2025,May,21,20,2025-05-20,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-030374,Resort Hotel,0,72,2024,November,47,18,2024-11-18,0,2,2,0.0,0,HB,ESP,Direct,Direct,0,0,0,A,D,0,No Deposit,250.0,,0,Transient,47.8,0,2
HB-109060,City Hotel,0,91,2025,April,14,2,2025-04-02,2,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,4
HB-063237,City Hotel,1,56,2025,February,6,3,2025-02-03,0,2,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,0
HB-102314,City Hotel,0,64,2024,November,47,21,2024-11-21,1,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,88.4,0,2
HB-059760,City Hotel,1,166,2024,November,44,1,2024-11-01,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,110.0,0,0
HB-018909,Resort Hotel,0,7,2023,December,48,2,2023-12-02,0,1,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,6.0,,0,Transient-Party,8.0,0,1
HB-067465,City Hotel,1,72,2025,May,18,4,2025-05-04,0,1,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,189.0,0,0
HB-052984,City Hotel,1,188,2024,June,24,15,2024-06-15,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,39,Transient,130.0,0,0
HB-065753,City Hotel,1,31,2025,April,15,7,2025-04-07,1,2,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,0
HB-034365,Resort Hotel,0,337,2025,February,8,23,2025-02-23,8,20,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,E,E,1,No Deposit,,,0,Transient,46.4,0,1
HB-099340,City Hotel,0,182,2024,October,41,12,2024-10-12,0,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,C,0,No Deposit,234.0,,0,Transient-Party,0.0,0,0
HB-049624,City Hotel,0,131,2024,April,16,16,2024-04-16,2,1,1,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,81.3,0,0
HB-058010,City Hotel,1,48,2024,October,40,5,2024-10-05,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,120.0,0,0
HB-110157,City Hotel,0,133,2025,April,16,19,2025-04-19,0,4,2,0.0,0,BB,ISL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,390.0,,0,Transient-Party,124.0,0,0
HB-049915,City Hotel,0,265,2024,April,16,20,2024-04-20,0,4,1,0.0,0,BB,AUT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,30.0,,176,Transient-Party,84.5,0,0
HB-033482,Resort Hotel,0,6,2025,February,9,24,2025-02-24,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,E,0,No Deposit,,,0,Transient,68.2,1,1
HB-074652,City Hotel,1,374,2023,October,43,26,2023-10-26,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-082465,City Hotel,0,31,2023,December,52,28,2023-12-28,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,80.0,0,0
HB-028608,Resort Hotel,0,128,2024,September,40,30,2024-09-30,2,5,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,96.23,0,0
HB-014127,Resort Hotel,0,0,2025,April,15,11,2025-04-11,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,2,A,E,0,No Deposit,,,0,Transient,86.5,0,0
HB-041576,City Hotel,1,5,2023,August,33,18,2023-08-18,3,10,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Contract,98.62,0,2
HB-023309,Resort Hotel,0,46,2024,April,16,15,2024-04-15,2,5,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,D,D,1,No Deposit,250.0,,0,Transient,68.0,0,0
HB-048157,City Hotel,1,42,2024,March,11,17,2024-03-17,2,5,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,124.79,0,1
HB-094119,City Hotel,0,198,2024,July,31,30,2024-07-30,1,1,2,0.0,0,HB,ITA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,96.0,0,1
HB-098622,City Hotel,0,221,2024,September,39,29,2024-09-29,0,3,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient-Party,115.5,0,2
HB-055282,City Hotel,1,91,2024,August,32,9,2024-08-09,4,10,2,0.0,0,BB,AGO,Direct,Direct,0,0,0,G,G,0,No Deposit,14.0,,0,Transient,247.0,0,0
HB-044031,City Hotel,1,20,2023,September,39,29,2023-09-29,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,136.67,0,2
HB-051460,City Hotel,1,211,2024,May,21,20,2024-05-20,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,111,Transient,100.0,0,0
HB-037228,Resort Hotel,0,16,2025,June,24,9,2025-06-09,0,2,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,8.0,,0,Transient,107.0,1,0
HB-069068,City Hotel,1,181,2025,May,21,25,2025-05-25,0,2,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,130.0,0,0
HB-008007,Resort Hotel,1,211,2024,September,36,7,2024-09-07,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,D,D,0,Non Refund,1.0,,0,Transient,89.0,0,0
HB-075726,City Hotel,1,302,2023,August,33,15,2023-08-15,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-116543,City Hotel,0,8,2025,July,30,21,2025-07-21,0,1,2,2.0,0,BB,DEU,Direct,Direct,0,0,0,F,F,0,No Deposit,14.0,,0,Transient,245.0,0,0
HB-117161,City Hotel,0,287,2025,July,30,26,2025-07-26,1,4,2,2.0,0,BB,USA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,179.1,0,0
HB-028844,Resort Hotel,0,0,2024,October,41,12,2024-10-12,0,0,2,0.0,0,BB,FRA,Online TA,Direct,1,0,0,A,I,0,No Deposit,240.0,,0,Transient,0.0,0,1
HB-070756,City Hotel,1,295,2025,June,25,22,2025-06-22,0,2,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,108.0,0,2
HB-036299,Resort Hotel,0,0,2025,May,20,15,2025-05-15,1,0,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,47.0,0,0
HB-039298,Resort Hotel,0,84,2025,August,32,8,2025-08-08,1,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,230.0,0,2
HB-113216,City Hotel,0,4,2025,June,23,2,2025-06-02,0,2,2,1.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,141.0,,0,Transient,144.0,0,3
HB-060533,City Hotel,1,16,2024,November,46,13,2024-11-13,2,4,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,2
HB-117658,City Hotel,0,46,2025,August,32,4,2025-08-04,1,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,1
HB-096502,City Hotel,0,216,2024,August,35,30,2024-08-30,0,4,2,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,85.0,,0,Transient,86.7,0,0
HB-091173,City Hotel,0,256,2024,June,24,15,2024-06-15,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-038055,Resort Hotel,0,185,2025,July,27,1,2025-07-01,2,5,2,2.0,0,HB,PRT,Direct,Direct,0,0,0,G,G,1,No Deposit,250.0,,0,Transient,207.0,0,0
HB-038628,Resort Hotel,0,1,2025,July,30,22,2025-07-22,1,1,2,0.0,0,HB,CN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,526.0,,0,Transient,165.44,0,0
HB-021735,Resort Hotel,0,1,2024,March,10,8,2024-03-08,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,G,G,0,No Deposit,,,0,Transient,0.0,1,2
HB-004944,Resort Hotel,1,27,2024,April,15,10,2024-04-10,2,2,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,,0,Transient,72.0,0,0
HB-086503,City Hotel,0,86,2024,March,13,30,2024-03-30,1,4,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,B,B,0,No Deposit,,,0,Transient,71.19,0,1
HB-076312,City Hotel,0,264,2023,July,27,8,2023-07-08,0,2,3,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,84.0,0,0
HB-093441,City Hotel,0,2,2025,July,30,23,2025-07-23,1,0,2,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,D,1,No Deposit,,40.0,0,Transient,75.0,0,0
HB-000375,Resort Hotel,1,81,2023,July,28,13,2023-07-13,1,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,98.5,0,2
HB-006257,Resort Hotel,0,235,2024,May,22,31,2024-05-31,1,5,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,156.0,,0,Transient-Party,83.0,0,1
HB-026079,Resort Hotel,0,171,2025,July,28,9,2025-07-09,4,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,1,0,1,A,A,0,No Deposit,40.0,,11,Contract,104.85,0,3
HB-106969,City Hotel,0,4,2025,March,10,3,2025-03-03,0,2,1,0.0,0,BB,GRC,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,15.0,,0,Transient,78.4,0,0
HB-017354,Resort Hotel,0,270,2023,September,39,28,2023-09-28,3,7,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,A,A,0,No Deposit,95.0,,0,Transient,52.0,0,0
HB-107069,City Hotel,0,28,2025,March,10,4,2025-03-04,2,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,3
HB-055130,City Hotel,1,119,2024,August,32,5,2024-08-05,2,2,1,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,144.45,0,0
HB-087378,City Hotel,0,2,2024,April,16,18,2024-04-18,1,0,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.0,0,0
HB-080353,City Hotel,0,61,2023,November,46,14,2023-11-14,2,1,2,0.0,0,BB,TUR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,81.9,0,2
HB-082831,City Hotel,1,68,2024,February,7,17,2024-02-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,37.0,,0,Transient,75.0,0,0
HB-061992,City Hotel,1,269,2024,December,52,29,2024-12-29,2,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,70.0,0,0
HB-048272,City Hotel,1,393,2024,March,12,19,2024-03-19,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,70.53,0,0
HB-080028,City Hotel,1,0,2023,November,45,10,2023-11-10,0,1,2,0.0,0,BB,PRT,Direct,Direct,1,0,0,A,A,0,No Deposit,,,0,Transient,89.0,0,0
HB-001882,Resort Hotel,0,110,2023,September,38,19,2023-09-19,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,241.0,,0,Transient,65.1,0,0
HB-116025,City Hotel,0,16,2025,July,28,11,2025-07-11,0,3,2,2.0,0,BB,FIN,Online TA,TA/TO,0,0,0,F,G,0,No Deposit,9.0,,0,Transient,236.67,0,0
HB-085681,City Hotel,0,34,2024,March,11,15,2024-03-15,0,5,2,0.0,0,HB,EST,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,129.6,0,1
HB-057910,City Hotel,1,150,2024,October,40,3,2024-10-03,1,2,2,1.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.0,0,0
HB-021267,Resort Hotel,0,0,2024,February,9,26,2024-02-26,0,1,1,0.0,0,BB,PRT,Direct,Direct,1,0,1,A,A,1,No Deposit,,,0,Transient,40.0,0,0
HB-010773,Resort Hotel,1,10,2025,April,14,3,2025-04-03,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,Non Refund,,135.0,0,Transient,45.0,0,0
HB-102579,City Hotel,0,21,2024,November,48,30,2024-11-30,0,2,2,0.0,0,BB,POL,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,81.0,0,0
HB-087129,City Hotel,0,26,2024,April,15,11,2024-04-11,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,123.5,0,1
HB-039125,Resort Hotel,0,191,2025,July,31,30,2025-07-30,4,5,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,129.67,0,0
HB-022319,Resort Hotel,0,28,2024,March,12,21,2024-03-21,1,1,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,D,E,1,No Deposit,250.0,,0,Transient,55.0,0,1
HB-099878,City Hotel,0,53,2024,October,42,16,2024-10-16,2,2,1,0.0,0,BB,DEU,Groups,TA/TO,0,0,0,A,A,2,No Deposit,21.0,,0,Transient-Party,66.5,0,0
HB-077059,City Hotel,1,262,2023,November,45,9,2023-11-09,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-045552,City Hotel,0,123,2023,November,45,6,2023-11-06,1,2,2,0.0,0,BB,JPN,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,60.0,0,0
HB-064114,City Hotel,1,601,2025,March,9,2,2025-03-02,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-053699,City Hotel,1,101,2024,June,26,27,2024-06-27,1,5,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,140.0,0,0
HB-084819,City Hotel,0,0,2024,March,9,3,2024-03-03,0,1,1,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.0,0,0
HB-103826,City Hotel,0,11,2024,December,1,30,2024-12-30,0,2,2,0.0,1,BB,PRT,Direct,Direct,0,0,0,A,A,3,No Deposit,,,0,Transient,120.0,0,3
HB-024103,Resort Hotel,0,5,2024,May,19,11,2024-05-11,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,1,No Deposit,250.0,,0,Transient,84.6,1,0
HB-006500,Resort Hotel,1,65,2024,June,24,13,2024-06-13,1,4,3,1.0,0,HB,PRT,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,232.0,0,0
HB-118505,City Hotel,0,268,2025,August,34,18,2025-08-18,1,2,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.1,0,0
HB-077929,City Hotel,0,18,2023,September,39,27,2023-09-27,2,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,B,1,No Deposit,1.0,,0,Transient-Party,170.0,0,0
HB-011307,Resort Hotel,1,74,2025,May,18,2,2025-05-02,2,5,1,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,115.0,0,2
HB-019481,Resort Hotel,0,0,2023,December,51,21,2023-12-21,1,0,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,38.0,0,0
HB-099089,City Hotel,0,85,2024,October,41,7,2024-10-07,0,2,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,151.2,0,1
HB-084975,City Hotel,0,29,2024,March,10,4,2024-03-04,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,87.0,0,0
HB-104686,City Hotel,0,3,2025,January,3,15,2025-01-15,2,3,1,0.0,0,BB,PRT,Aviation,Corporate,0,0,0,A,A,1,No Deposit,,153.0,0,Transient,79.0,0,0
HB-095021,City Hotel,0,108,2024,August,32,6,2024-08-06,2,5,3,0.0,0,BB,DNK,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,146.7,0,1
HB-001735,Resort Hotel,0,1,2023,September,37,11,2023-09-11,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,F,0,No Deposit,240.0,,0,Transient,135.0,1,1
HB-084561,City Hotel,0,33,2024,February,8,23,2024-02-23,0,5,2,0.0,0,BB,HRV,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.46,0,1
HB-027166,Resort Hotel,0,154,2024,August,33,15,2024-08-15,2,5,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,250.0,,0,Transient,185.44,0,0
HB-056092,City Hotel,1,187,2024,August,35,28,2024-08-28,2,5,2,1.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,111.35,0,0
HB-097951,City Hotel,0,1,2024,September,38,22,2024-09-22,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,210.0,0,1
HB-031361,Resort Hotel,0,152,2024,December,52,24,2024-12-24,1,1,2,0.0,0,HB,GBR,Direct,Direct,0,0,0,A,A,1,No Deposit,250.0,,0,Transient,84.02,0,1
HB-042698,City Hotel,1,69,2023,September,36,9,2023-09-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-086240,City Hotel,0,119,2024,March,13,29,2024-03-29,0,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,39.0,,0,Transient-Party,101.0,0,0
HB-055104,City Hotel,1,86,2024,August,31,4,2024-08-04,2,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,85.0,,0,Transient,82.45,0,0
HB-050313,City Hotel,1,96,2024,April,17,28,2024-04-28,0,3,2,2.0,0,BB,ITA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,180.3,0,0
HB-076692,City Hotel,0,13,2024,June,24,14,2024-06-14,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,1,3,35,A,A,2,No Deposit,,40.0,0,Transient,65.0,0,1
HB-086644,City Hotel,0,55,2024,April,14,6,2024-04-06,0,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,104.0,0,0
HB-109313,City Hotel,0,0,2025,April,14,6,2025-04-06,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,1
HB-078802,City Hotel,0,14,2023,October,41,15,2023-10-15,0,2,1,0.0,0,BB,DZA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,99.0,,0,Transient-Party,100.0,0,0
HB-014385,Resort Hotel,0,0,2025,January,5,30,2025-01-30,1,0,1,0.0,0,BB,PRT,Direct,TA/TO,0,2,2,A,A,0,No Deposit,,,0,Transient,40.0,0,1
HB-080053,City Hotel,0,8,2024,February,6,10,2024-02-10,0,3,3,0.0,0,BB,ESP,Online TA,TA/TO,1,11,22,D,D,1,No Deposit,9.0,,0,Transient,92.67,0,2
HB-059829,City Hotel,1,482,2024,November,44,3,2024-11-03,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-055454,City Hotel,1,188,2024,August,33,13,2024-08-13,1,1,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.3,0,0
HB-011966,Resort Hotel,1,35,2025,June,23,5,2025-06-05,1,5,2,0.0,0,HB,BEL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,193.67,0,1
HB-063309,City Hotel,1,24,2025,February,6,6,2025-02-06,1,5,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,67.32,0,0
HB-107715,City Hotel,0,60,2025,March,11,13,2025-03-13,1,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,7.0,,0,Transient,57.6,0,1
HB-051967,City Hotel,0,316,2024,May,21,26,2024-05-26,2,4,1,0.0,0,BB,AUT,Groups,TA/TO,0,0,0,A,A,3,No Deposit,30.0,,0,Transient-Party,205.0,0,0
HB-066654,City Hotel,1,100,2025,April,17,22,2025-04-22,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,0,Transient,105.0,0,0
HB-090822,City Hotel,0,113,2024,June,23,9,2024-06-09,0,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,116.1,0,1
HB-060186,City Hotel,1,277,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-017935,Resort Hotel,0,40,2023,October,42,20,2023-10-20,2,6,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,2.0,,0,Contract,42.5,0,0
HB-036135,Resort Hotel,0,8,2025,May,19,6,2025-05-06,2,3,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,48.0,0,0
HB-003654,Resort Hotel,0,165,2023,December,52,30,2023-12-30,0,4,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,C,0,No Deposit,308.0,,122,Transient-Party,136.5,0,0
HB-026883,Resort Hotel,0,205,2024,August,32,7,2024-08-07,2,5,3,0.0,0,HB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,194.0,1,1
HB-116186,City Hotel,0,154,2025,July,29,15,2025-07-15,0,1,3,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,152.1,0,0
HB-045129,City Hotel,1,38,2023,October,42,17,2023-10-17,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,105.12,0,2
HB-034106,Resort Hotel,0,274,2025,March,11,10,2025-03-10,1,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,F,0,No Deposit,240.0,,0,Transient,57.8,0,2
HB-088191,City Hotel,0,99,2024,April,17,28,2024-04-28,1,3,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,101.58,0,1
HB-038803,Resort Hotel,0,122,2025,July,30,23,2025-07-23,2,5,2,2.0,0,BB,BEL,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,360.0,0,1
HB-046387,City Hotel,1,148,2023,December,52,30,2023-12-30,1,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,79,Transient,67.0,0,0
HB-097034,City Hotel,0,277,2024,September,36,5,2024-09-05,2,5,1,0.0,0,HB,NOR,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,21.0,,0,Transient-Party,79.57,0,0
HB-062421,City Hotel,1,165,2025,January,3,13,2025-01-13,0,2,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,0
HB-059122,City Hotel,1,279,2024,October,43,21,2024-10-21,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,65.0,0,0
HB-050271,City Hotel,1,295,2024,April,17,28,2024-04-28,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,59.0,0,0
HB-026496,Resort Hotel,0,160,2024,July,30,28,2024-07-28,2,3,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,96.0,,0,Transient,129.2,0,1
HB-081221,City Hotel,0,8,2023,December,48,3,2023-12-03,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,58.41,0,0
HB-034006,Resort Hotel,0,107,2025,March,10,9,2025-03-09,0,2,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,E,F,0,No Deposit,96.0,,0,Transient-Party,99.0,0,0
HB-004922,Resort Hotel,1,22,2024,April,15,9,2024-04-09,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,96.0,,0,Transient-Party,35.1,0,0
HB-114028,City Hotel,0,83,2025,June,24,14,2025-06-14,0,2,2,0.0,0,BB,USA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,146.0,0,2
HB-013808,Resort Hotel,0,7,2024,January,2,13,2024-01-13,0,2,1,0.0,0,BB,,Corporate,Corporate,0,0,0,A,D,0,No Deposit,94.0,,0,Transient,27.0,0,0
HB-081621,City Hotel,1,130,2024,April,15,13,2024-04-13,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,29.0,,10,Transient,100.0,0,0
HB-003407,Resort Hotel,1,44,2023,December,49,5,2023-12-05,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,70.0,0,0
HB-118789,City Hotel,0,115,2025,August,34,21,2025-08-21,1,3,2,1.0,0,BB,FIN,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,195.0,0,3
HB-057742,City Hotel,1,315,2024,September,40,30,2024-09-30,1,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,69,Transient,160.0,0,0
HB-109291,City Hotel,0,79,2025,April,14,3,2025-04-03,1,5,2,0.0,0,BB,NLD,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,123.3,0,0
HB-058241,City Hotel,1,102,2024,October,41,9,2024-10-09,1,0,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-019680,Resort Hotel,0,28,2023,December,52,28,2023-12-28,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,61.0,1,1
HB-035991,Resort Hotel,0,221,2025,April,18,30,2025-04-30,2,5,2,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,A,C,1,No Deposit,,,0,Transient-Party,73.43,0,0
HB-040744,City Hotel,0,0,2023,August,31,6,2023-08-06,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,80.0,1,2
HB-039969,Resort Hotel,0,171,2025,August,35,27,2025-08-27,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,75.0,,0,Transient,131.4,1,0
HB-058678,City Hotel,1,233,2024,October,42,14,2024-10-14,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,90.0,0,0
HB-050919,City Hotel,0,286,2024,May,19,11,2024-05-11,0,4,2,0.0,0,BB,AUT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,176,Transient-Party,99.0,0,1
HB-011891,Resort Hotel,1,16,2025,June,23,3,2025-06-03,0,1,1,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,128.0,0,0
HB-116461,City Hotel,0,76,2025,July,29,16,2025-07-16,2,3,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,108.0,0,0
HB-086684,City Hotel,0,60,2024,April,14,2,2024-04-02,2,3,2,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,107.78,0,1
HB-097582,City Hotel,0,24,2024,September,38,16,2024-09-16,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,149.0,0,1
HB-105926,City Hotel,0,28,2025,February,7,13,2025-02-13,1,4,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-103514,City Hotel,0,69,2024,December,52,23,2024-12-23,2,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient-Party,77.86,0,1
HB-023670,Resort Hotel,0,6,2024,April,18,29,2024-04-29,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,80.0,1,0
HB-065884,City Hotel,1,28,2025,April,15,9,2025-04-09,2,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,0
HB-029002,Resort Hotel,0,0,2024,October,42,17,2024-10-17,1,0,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,75.0,0,0
HB-115352,City Hotel,0,462,2025,July,27,1,2025-07-01,2,2,2,0.0,0,BB,AUS,Groups,TA/TO,0,0,0,A,A,1,No Deposit,229.0,,0,Transient-Party,107.0,0,1
HB-030889,Resort Hotel,0,14,2024,December,49,5,2024-12-05,1,2,2,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,84.0,0,0
HB-000308,Resort Hotel,0,53,2023,July,28,12,2023-07-12,1,0,2,2.0,0,BB,CN,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,153.0,1,0
HB-076758,City Hotel,0,1,2023,August,32,9,2023-08-09,1,0,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.0,0,0
HB-094984,City Hotel,0,178,2024,August,32,10,2024-08-10,0,3,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,9.0,,0,Transient,127.5,0,2
HB-103013,City Hotel,0,1,2024,December,50,10,2024-12-10,0,1,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,202.0,0,0
HB-102996,City Hotel,0,157,2024,December,49,8,2024-12-08,0,3,2,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,83.0,,0,Transient-Party,68.0,0,0
HB-063391,City Hotel,1,78,2025,February,7,10,2025-02-10,2,3,2,0.0,0,BB,HUN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,96.9,0,0
HB-008548,Resort Hotel,0,383,2024,October,40,6,2024-10-06,0,2,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,E,0,No Deposit,315.0,,0,Transient-Party,54.0,1,0
HB-041505,City Hotel,1,9,2023,August,33,17,2023-08-17,1,2,1,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,153.0,0,2
HB-014719,Resort Hotel,1,259,2023,September,37,17,2023-09-17,0,3,2,0.0,0,BB,GBR,Groups,Corporate,0,1,0,A,A,0,Non Refund,,223.0,0,Transient,40.05,0,0
HB-083401,City Hotel,0,67,2024,January,5,29,2024-01-29,0,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,57.0,0,0
HB-011490,Resort Hotel,1,13,2025,May,19,11,2025-05-11,0,3,1,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,87.67,0,1
HB-048042,City Hotel,1,71,2024,March,11,13,2024-03-13,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,73.95,0,0
HB-000865,Resort Hotel,0,66,2023,August,31,1,2023-08-01,2,6,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,240.0,,0,Transient,193.13,0,0
HB-030763,Resort Hotel,0,10,2024,December,49,3,2024-12-03,0,1,1,0.0,0,HB,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,44.0,0,0
HB-094112,City Hotel,0,117,2024,July,31,29,2024-07-29,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,123.3,0,1
HB-007077,Resort Hotel,1,88,2024,July,29,19,2024-07-19,0,5,2,0.0,0,HB,GEO,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,212.0,0,0
HB-030796,Resort Hotel,0,2,2024,December,49,2,2024-12-02,0,2,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,0,No Deposit,250.0,,0,Transient,65.85,1,0
HB-013725,Resort Hotel,1,305,2025,August,35,27,2025-08-27,4,6,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,40.0,,0,Transient,131.4,0,2
HB-098158,City Hotel,0,276,2024,September,38,22,2024-09-22,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,178,Transient-Party,95.67,0,0
HB-095005,City Hotel,0,280,2024,August,33,12,2024-08-12,0,1,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,B,F,2,No Deposit,8.0,,0,Transient,198.9,1,2
HB-073531,City Hotel,1,94,2025,August,35,25,2025-08-25,1,2,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,83.0,,0,Transient,122.45,0,0
HB-033163,Resort Hotel,0,1,2025,February,8,17,2025-02-17,0,2,2,0.0,0,BB,USA,Online TA,Direct,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,68.0,0,1
HB-002884,Resort Hotel,0,24,2023,November,44,3,2023-11-03,3,10,1,0.0,0,BB,FRA,Corporate,Corporate,0,0,0,A,A,2,No Deposit,334.0,281.0,0,Transient-Party,40.0,0,0
HB-044338,City Hotel,0,61,2023,October,40,4,2023-10-04,2,0,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,91.0,0,0
HB-046525,City Hotel,0,7,2024,January,1,4,2024-01-04,1,2,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,82.0,0,0
HB-006416,Resort Hotel,1,15,2024,June,23,9,2024-06-09,2,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,141.0,0,0
HB-075946,City Hotel,1,301,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-072900,City Hotel,1,479,2025,August,32,9,2025-08-09,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,229.0,,0,Transient-Party,112.67,0,0
HB-003091,Resort Hotel,0,74,2023,November,46,16,2023-11-16,0,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,0.0,0,1
HB-053208,City Hotel,1,350,2024,June,25,17,2024-06-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,140.0,0,0
HB-031769,Resort Hotel,0,0,2025,January,2,6,2025-01-06,0,1,3,0.0,0,BB,NLD,Online TA,TA/TO,1,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,48.0,0,0
HB-080443,City Hotel,1,34,2023,December,49,8,2023-12-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,0,Transient,90.0,0,0
HB-064990,City Hotel,1,56,2025,March,12,21,2025-03-21,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,86.0,,0,Transient,85.0,0,0
HB-093367,City Hotel,0,179,2024,July,29,17,2024-07-17,2,2,1,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.95,0,1
HB-071992,City Hotel,1,155,2025,July,29,17,2025-07-17,1,1,2,1.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.1,0,1
HB-005562,Resort Hotel,0,199,2024,May,18,2,2024-05-02,1,1,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,85.0,0,0
HB-064637,City Hotel,1,97,2025,March,11,14,2025-03-14,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,0,Transient,85.0,0,0
HB-109767,City Hotel,0,298,2025,April,16,14,2025-04-14,1,2,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,90.0,0,0
HB-012476,Resort Hotel,1,197,2025,July,27,1,2025-07-01,2,4,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,314.0,,0,Transient,127.8,0,2
HB-063501,City Hotel,1,39,2025,February,7,12,2025-02-12,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.0,0,0
HB-095119,City Hotel,0,8,2024,August,33,13,2024-08-13,1,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,132.0,0,0
HB-031674,Resort Hotel,0,127,2024,December,52,28,2024-12-28,2,5,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,75.0,,0,Transient,94.89,0,0
HB-099799,City Hotel,0,45,2024,October,42,17,2024-10-17,1,0,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,185.4,1,2
HB-115986,City Hotel,0,21,2025,July,28,8,2025-07-08,2,3,2,0.0,0,BB,CHL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,152.0,0,2
HB-034207,Resort Hotel,0,0,2025,March,11,15,2025-03-15,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,85.0,0,2
HB-053979,City Hotel,1,52,2024,July,27,4,2024-07-04,1,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.9,0,0
HB-000322,Resort Hotel,0,48,2023,July,28,12,2023-07-12,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Transient,123.0,0,1
HB-072774,City Hotel,1,265,2025,August,32,5,2025-08-05,3,6,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,89.1,0,0
HB-047480,City Hotel,1,77,2024,February,8,24,2024-02-24,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,64.0,0,0
HB-022290,Resort Hotel,0,36,2024,March,11,16,2024-03-16,2,5,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,69.0,,0,Transient-Party,36.6,1,1
HB-052674,City Hotel,1,337,2024,June,23,9,2024-06-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-081537,City Hotel,1,218,2024,June,23,9,2024-06-09,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,133.0,,0,Transient,135.0,0,0
HB-103619,City Hotel,0,106,2024,December,52,25,2024-12-25,2,1,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,140.0,0,2
HB-113942,City Hotel,0,36,2025,June,24,13,2025-06-13,0,2,2,1.0,0,BB,IND,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,114.8,0,2
HB-034014,Resort Hotel,0,107,2025,March,10,9,2025-03-09,0,2,1,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,E,E,1,No Deposit,96.0,,0,Transient-Party,74.0,0,0
HB-110251,City Hotel,0,44,2025,April,16,20,2025-04-20,1,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,85.0,0,0
HB-070981,City Hotel,1,99,2025,June,26,26,2025-06-26,1,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-074246,City Hotel,1,377,2023,October,43,29,2023-10-29,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-031948,Resort Hotel,0,1,2025,March,12,23,2025-03-23,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,1,0,4,A,D,0,No Deposit,240.0,,0,Transient,70.0,0,0
HB-014302,Resort Hotel,0,0,2025,April,16,18,2025-04-18,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,6,A,D,0,No Deposit,,290.0,0,Transient,45.0,0,0
HB-025071,Resort Hotel,0,258,2024,June,24,12,2024-06-12,1,0,2,0.0,0,BB,EST,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient,64.8,1,2
HB-034674,Resort Hotel,0,103,2025,March,13,29,2025-03-29,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,48.0,0,0
HB-118004,City Hotel,0,148,2025,August,32,10,2025-08-10,0,3,2,1.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,148.5,0,2
HB-076600,City Hotel,0,138,2023,July,30,25,2023-07-25,0,1,1,0.0,0,BB,BRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,57.0,0,0
HB-068192,City Hotel,1,320,2025,May,20,15,2025-05-15,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,90.0,0,1
HB-008299,Resort Hotel,1,197,2024,September,38,21,2024-09-21,2,5,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,D,D,0,Non Refund,253.0,,0,Transient,66.6,0,0
HB-013650,Resort Hotel,1,237,2025,August,34,24,2025-08-24,2,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,153.75,0,1
HB-118606,City Hotel,0,103,2025,August,33,16,2025-08-16,2,5,3,0.0,0,HB,BEL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,394.0,,0,Transient,119.0,0,1
HB-001259,Resort Hotel,0,65,2023,August,34,21,2023-08-21,2,5,2,0.0,0,HB,IRL,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,188.71,0,0
HB-119079,City Hotel,0,518,2025,August,35,26,2025-08-26,2,1,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,1
HB-083070,City Hotel,0,2,2024,January,3,15,2024-01-15,0,2,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,9.0,,0,Transient,87.3,0,0
HB-044753,City Hotel,0,63,2023,October,41,10,2023-10-10,1,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,89.25,0,1
HB-100119,City Hotel,0,88,2024,October,42,20,2024-10-20,0,3,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,151.2,0,1
HB-018244,Resort Hotel,0,2,2023,November,46,14,2023-11-14,0,1,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,98.0,0,0
HB-108190,City Hotel,0,15,2025,March,12,22,2025-03-22,0,2,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,7.0,,0,Transient,98.4,0,0
HB-062002,City Hotel,1,64,2024,December,1,30,2024-12-30,0,1,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,131.4,0,1
HB-099146,City Hotel,0,77,2024,October,41,7,2024-10-07,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,132.3,0,3
HB-005575,Resort Hotel,1,45,2024,May,18,2,2024-05-02,1,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,95.0,0,0
HB-086476,City Hotel,0,165,2024,March,13,30,2024-03-30,1,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,94.18,0,0
HB-041290,City Hotel,1,0,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-096760,City Hotel,0,46,2024,September,36,7,2024-09-07,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,98.1,0,1
HB-058369,City Hotel,1,104,2024,October,41,11,2024-10-11,2,5,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,132.3,0,0
HB-066310,City Hotel,1,245,2025,April,16,16,2025-04-16,2,3,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-043328,City Hotel,0,72,2023,September,38,18,2023-09-18,0,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,108.0,0,0
HB-015573,Resort Hotel,0,11,2023,July,30,24,2023-07-24,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,E,0,No Deposit,,,0,Transient,150.0,0,1
HB-112322,City Hotel,0,100,2025,May,21,20,2025-05-20,2,1,1,0.0,0,SC,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,2
HB-001743,Resort Hotel,1,101,2023,September,37,12,2023-09-12,0,1,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,153.0,0,1
HB-009964,Resort Hotel,1,82,2025,January,5,29,2025-01-29,2,5,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,72.0,0,0
HB-114350,City Hotel,0,50,2025,June,25,19,2025-06-19,1,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,150.0,0,1
HB-085622,City Hotel,0,17,2024,March,11,17,2024-03-17,0,2,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,174.0,,0,Transient-Party,80.0,0,1
HB-114111,City Hotel,0,35,2025,June,24,12,2025-06-12,1,4,2,0.0,0,HB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,151.2,0,2
HB-065907,City Hotel,1,236,2025,April,15,9,2025-04-09,2,5,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,3,No Deposit,9.0,,0,Transient,170.36,0,1
HB-089496,City Hotel,0,25,2024,May,20,19,2024-05-19,0,3,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,F,F,1,No Deposit,14.0,,0,Transient,184.45,0,0
HB-073005,City Hotel,1,197,2025,August,33,12,2025-08-12,2,1,2,0.0,0,BB,USA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,112.5,0,0
HB-020556,Resort Hotel,0,1,2025,April,15,11,2025-04-11,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,2,A,A,0,No Deposit,,43.0,0,Transient,45.0,0,0
HB-073084,City Hotel,1,49,2025,August,33,14,2025-08-14,1,1,2,0.0,0,SC,AUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,1
HB-053782,City Hotel,1,358,2024,June,26,30,2024-06-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-053418,City Hotel,1,193,2024,June,25,20,2024-06-20,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,162.0,,39,Transient,120.0,0,0
HB-009871,Resort Hotel,1,18,2025,January,3,16,2025-01-16,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,F,1,No Deposit,,154.0,0,Transient,35.0,0,0
HB-072293,City Hotel,1,244,2025,July,30,25,2025-07-25,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,80.1,0,0
HB-031763,Resort Hotel,0,154,2025,January,1,5,2025-01-05,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,37.8,1,1
HB-003318,Resort Hotel,0,66,2023,December,49,5,2023-12-05,1,1,2,0.0,0,FB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,155.0,,0,Transient-Party,64.0,0,0
HB-015357,Resort Hotel,0,121,2023,July,27,3,2023-07-03,2,5,2,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,115.0,,0,Contract,58.95,0,1
HB-027880,Resort Hotel,0,63,2024,September,37,12,2024-09-12,1,1,2,0.0,1,BB,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,348.0,,0,Transient,119.0,0,1
HB-026003,Resort Hotel,0,0,2024,July,29,17,2024-07-17,1,0,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,115.0,0,0
HB-107979,City Hotel,0,17,2025,March,12,20,2025-03-20,1,0,1,0.0,0,BB,FRA,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,91.0,0,Transient,80.0,0,0
HB-085099,City Hotel,0,0,2024,March,10,6,2024-03-06,2,1,2,0.0,0,BB,AGO,Online TA,Direct,0,0,0,D,E,1,No Deposit,,,0,Transient,110.0,0,1
HB-071820,City Hotel,1,199,2025,July,28,13,2025-07-13,0,2,3,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,0
HB-104871,City Hotel,0,0,2025,January,4,22,2025-01-22,2,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,88.0,0,0
HB-007553,Resort Hotel,1,54,2024,August,33,14,2024-08-14,2,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,189.0,0,0
HB-094118,City Hotel,0,301,2024,July,31,30,2024-07-30,1,1,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-096391,City Hotel,0,4,2024,August,35,28,2024-08-28,2,3,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,113.96,0,1
HB-026764,Resort Hotel,0,9,2024,August,32,7,2024-08-07,2,1,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,227.0,0,1
HB-088927,City Hotel,0,12,2024,May,19,11,2024-05-11,0,4,2,0.0,0,BB,CHE,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,104.0,0,0
HB-101756,City Hotel,0,199,2024,November,46,16,2024-11-16,0,2,3,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,140.0,0,0
HB-062425,City Hotel,1,124,2025,January,3,13,2025-01-13,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,1
HB-073548,City Hotel,1,228,2025,August,35,25,2025-08-25,2,6,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,0
HB-029496,Resort Hotel,0,0,2025,January,3,16,2025-01-16,1,1,2,0.0,0,BB,NLD,Corporate,Corporate,1,0,1,A,G,2,No Deposit,,447.0,0,Transient,36.0,1,1
HB-115703,City Hotel,0,133,2025,July,28,7,2025-07-07,1,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,2
HB-117416,City Hotel,0,292,2025,August,31,2,2025-08-02,0,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,4
HB-009168,Resort Hotel,1,245,2024,October,44,31,2024-10-31,1,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,54.0,0,1
HB-024381,Resort Hotel,0,29,2024,May,20,17,2024-05-17,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,1,No Deposit,,104.0,0,Transient,94.5,0,0
HB-038229,Resort Hotel,0,3,2025,July,28,10,2025-07-10,1,1,2,1.0,0,HB,PRT,Online TA,TA/TO,0,0,0,C,C,1,No Deposit,240.0,,0,Transient,193.0,0,1
HB-098683,City Hotel,0,91,2024,September,40,30,2024-09-30,1,2,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,3.0,,0,Transient-Party,75.0,0,0
HB-011523,Resort Hotel,1,89,2025,May,20,13,2025-05-13,2,6,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,115.0,0,2
HB-093969,City Hotel,0,0,2024,July,31,29,2024-07-29,0,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.0,0,0
HB-020820,Resort Hotel,0,1,2024,February,6,7,2024-02-07,2,1,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient,29.0,0,0
HB-074989,City Hotel,1,260,2023,July,27,4,2023-07-04,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-072025,City Hotel,1,177,2025,July,29,17,2025-07-17,2,5,2,0.0,0,HB,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,149.79,0,1
HB-060326,City Hotel,1,277,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-035219,Resort Hotel,0,73,2025,April,15,13,2025-04-13,0,3,2,0.0,0,HB,ESP,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,115.5,1,0
HB-023898,Resort Hotel,0,25,2024,May,18,4,2024-05-04,0,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,111.0,1,0
HB-047877,City Hotel,1,49,2024,March,10,7,2024-03-07,1,2,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,87.3,0,0
HB-037235,Resort Hotel,0,0,2025,June,24,9,2025-06-09,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,149.0,1,0
HB-074443,City Hotel,1,304,2023,August,33,17,2023-08-17,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-069487,City Hotel,1,174,2025,June,22,1,2025-06-01,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,0,Transient,100.0,0,0
HB-076102,City Hotel,1,364,2023,October,42,16,2023-10-16,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-096385,City Hotel,0,26,2024,August,35,31,2024-08-31,0,2,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,110.0,0,1
HB-117882,City Hotel,0,479,2025,August,32,9,2025-08-09,0,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,1
HB-026524,Resort Hotel,0,188,2024,July,30,27,2024-07-27,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,40.0,,0,Contract,115.05,0,1
HB-042573,City Hotel,0,5,2023,September,36,7,2023-09-07,1,2,1,0.0,0,BB,VEN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,78.03,0,0
HB-069548,City Hotel,1,133,2025,June,22,1,2025-06-01,1,3,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,184.5,0,0
HB-102336,City Hotel,0,13,2024,November,47,22,2024-11-22,0,5,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,78.23,0,1
HB-067022,City Hotel,1,111,2025,April,17,27,2025-04-27,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,0,Transient,120.0,0,0
HB-001669,Resort Hotel,0,175,2023,September,36,8,2023-09-08,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,143.0,,0,Transient,91.5,0,0
HB-068239,City Hotel,1,164,2025,May,20,15,2025-05-15,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-022839,Resort Hotel,0,0,2024,April,14,5,2024-04-05,0,3,1,0.0,0,BB,IRL,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,56.0,0,0
HB-096362,City Hotel,0,176,2024,September,35,1,2024-09-01,0,1,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,F,0,No Deposit,9.0,,0,Transient,159.3,0,2
HB-037943,Resort Hotel,0,278,2025,June,26,27,2025-06-27,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,143.0,,0,Contract,100.2,0,0
HB-006361,Resort Hotel,1,107,2024,June,23,5,2024-06-05,2,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,80.0,0,1
HB-044476,City Hotel,1,97,2023,October,40,5,2023-10-05,1,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,140.0,0,0
HB-013515,Resort Hotel,1,158,2025,August,34,18,2025-08-18,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,230.0,0,1
HB-110522,City Hotel,0,16,2025,April,17,26,2025-04-26,0,2,1,0.0,0,BB,NLD,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,174.5,0,0
HB-084860,City Hotel,0,6,2024,March,10,4,2024-03-04,0,1,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient-Party,140.0,0,0
HB-082033,City Hotel,1,305,2024,October,40,1,2024-10-01,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,35.0,,17,Transient,100.0,0,0
HB-119224,City Hotel,0,6,2025,August,35,28,2025-08-28,1,3,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,7.0,,0,Transient,190.0,0,1
HB-072254,City Hotel,1,344,2025,July,30,24,2025-07-24,1,5,2,0.0,0,SC,HUN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,1
HB-055084,City Hotel,1,391,2024,August,31,4,2024-08-04,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-100957,City Hotel,0,55,2024,November,44,2,2024-11-02,0,2,2,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,97.2,0,1
HB-110294,City Hotel,0,343,2025,April,17,21,2025-04-21,2,2,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,B,A,1,No Deposit,,,0,Transient,99.25,0,1
HB-036736,Resort Hotel,0,388,2025,May,21,25,2025-05-25,0,3,1,0.0,0,BB,CN,Groups,TA/TO,0,0,0,E,E,1,No Deposit,96.0,,0,Transient-Party,72.0,0,0
HB-056109,City Hotel,1,164,2024,August,35,29,2024-08-29,1,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.3,0,0
HB-036658,Resort Hotel,0,142,2025,May,20,18,2025-05-18,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,314.0,,0,Transient,84.8,0,0
HB-050847,City Hotel,0,298,2024,May,19,10,2024-05-10,0,2,2,0.0,0,BB,NZL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,207,Transient-Party,93.0,0,0
HB-000585,Resort Hotel,1,28,2023,July,29,20,2023-07-20,2,5,2,1.0,0,FB,PRT,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient,240.64,0,0
HB-094484,City Hotel,0,182,2024,August,31,3,2024-08-03,0,2,2,1.0,0,SC,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,118.0,0,1
HB-069374,City Hotel,1,186,2025,May,22,30,2025-05-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,130.0,0,0
HB-002592,Resort Hotel,0,0,2023,October,43,23,2023-10-23,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,73.0,1,1
HB-092899,City Hotel,0,93,2024,July,28,12,2024-07-12,0,2,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,121.5,0,2
HB-081071,City Hotel,1,68,2023,December,48,2,2023-12-02,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,2
HB-034148,Resort Hotel,0,0,2025,March,11,13,2025-03-13,1,0,2,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,65.0,0,1
HB-080140,City Hotel,0,15,2023,November,45,10,2023-11-10,0,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.0,0,3
HB-044386,City Hotel,0,40,2023,October,40,5,2023-10-05,1,1,3,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,3.0,,40,Transient-Party,98.0,0,0
HB-001927,Resort Hotel,0,95,2023,September,38,21,2023-09-21,3,6,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,F,0,No Deposit,241.0,,0,Transient,73.98,0,0
HB-073663,City Hotel,1,223,2025,August,35,29,2025-08-29,0,4,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,2
HB-026796,Resort Hotel,0,200,2024,August,31,1,2024-08-01,3,7,3,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,26.0,,0,Transient,132.96,0,2
HB-103734,City Hotel,0,1,2024,December,52,29,2024-12-29,0,2,3,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,A,1,No Deposit,9.0,,0,Transient,188.0,0,1
HB-092187,City Hotel,0,113,2024,June,26,27,2024-06-27,1,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,7.0,,0,Transient,92.65,0,1
HB-058893,City Hotel,1,605,2024,October,42,17,2024-10-17,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-105730,City Hotel,0,3,2025,February,7,13,2025-02-13,1,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,103.0,,0,Transient,80.0,0,0
HB-079804,City Hotel,1,5,2023,November,45,8,2023-11-08,2,0,1,0.0,0,BB,PRT,Direct,Direct,0,1,0,A,A,0,No Deposit,14.0,,0,Transient,84.0,0,1
HB-084234,City Hotel,0,2,2024,February,7,14,2024-02-14,2,5,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,55.74,0,0
HB-055785,City Hotel,1,24,2024,August,34,21,2024-08-21,1,0,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,139.0,0,1
HB-072878,City Hotel,1,364,2025,August,32,8,2025-08-08,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,116.0,0,0
HB-083364,City Hotel,0,17,2024,January,4,26,2024-01-26,0,4,1,0.0,0,SC,FIN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,55.0,0,0
HB-112063,City Hotel,0,395,2025,May,20,17,2025-05-17,0,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,0
HB-036649,Resort Hotel,0,238,2025,May,21,21,2025-05-21,2,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,88.0,1,1
HB-102347,City Hotel,0,0,2024,November,47,24,2024-11-24,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,74.54,0,0
HB-053088,City Hotel,1,188,2024,June,24,15,2024-06-15,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,39,Transient,130.0,0,0
HB-075092,City Hotel,1,283,2023,July,30,27,2023-07-27,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-099548,City Hotel,0,45,2024,October,41,11,2024-10-11,0,3,2,0.0,0,SC,SWE,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-050285,City Hotel,1,295,2024,April,17,28,2024-04-28,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-117896,City Hotel,0,479,2025,August,32,9,2025-08-09,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,1
HB-000662,Resort Hotel,0,43,2023,July,30,24,2023-07-24,2,7,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,166.0,0,0
HB-107343,City Hotel,0,51,2025,March,10,9,2025-03-09,0,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.2,0,1
HB-024083,Resort Hotel,0,48,2024,May,19,11,2024-05-11,0,1,2,0.0,0,HB,FRA,Direct,Direct,0,0,0,A,C,0,No Deposit,,,0,Transient-Party,95.0,1,0
HB-084822,City Hotel,0,6,2024,March,9,2,2024-03-02,0,2,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,70.0,0,0
HB-079549,City Hotel,0,6,2023,October,43,25,2023-10-25,2,2,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,118.5,0,3
HB-117521,City Hotel,0,1,2025,August,32,4,2025-08-04,0,1,2,1.0,0,BB,RUS,Direct,Direct,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,170.0,0,0
HB-105238,City Hotel,0,59,2025,January,4,25,2025-01-25,2,7,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,88.98,0,2
HB-116349,City Hotel,0,156,2025,July,29,15,2025-07-15,2,1,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,116.1,0,0
HB-060879,City Hotel,1,308,2024,November,48,25,2024-11-25,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,52.0,0,0
HB-017919,Resort Hotel,0,0,2023,October,43,26,2023-10-26,1,0,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,35.1,0,0
HB-116901,City Hotel,0,90,2025,July,30,24,2025-07-24,1,2,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.0,0,0
HB-088659,City Hotel,0,0,2024,May,19,9,2024-05-09,1,0,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,79.31,0,1
HB-054220,City Hotel,1,53,2024,July,28,9,2024-07-09,1,1,3,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,148.5,0,0
HB-056524,City Hotel,1,426,2024,September,36,8,2024-09-08,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-086881,City Hotel,0,82,2024,April,15,9,2024-04-09,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,72,Transient-Party,90.0,0,1
HB-033600,Resort Hotel,0,16,2025,February,9,25,2025-02-25,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient-Party,49.0,0,1
HB-107813,City Hotel,0,54,2025,March,11,15,2025-03-15,0,4,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,68.0,0,0
HB-103965,City Hotel,0,58,2024,December,52,29,2024-12-29,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,178.56,0,2
HB-011798,Resort Hotel,1,295,2025,May,22,30,2025-05-30,2,8,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,80.1,0,1
HB-020251,Resort Hotel,0,0,2024,February,7,15,2024-02-15,1,3,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,D,0,No Deposit,,47.0,0,Transient,30.0,0,0
HB-111982,City Hotel,0,59,2025,May,20,15,2025-05-15,1,3,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,162.0,0,3
HB-001183,Resort Hotel,0,96,2023,August,33,17,2023-08-17,1,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,134.0,0,3
HB-037010,Resort Hotel,0,76,2025,May,22,31,2025-05-31,0,4,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,155.5,1,0
HB-096096,City Hotel,0,155,2024,August,35,26,2024-08-26,1,2,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.5,0,2
HB-054500,City Hotel,1,75,2024,July,29,18,2024-07-18,1,2,2,1.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,0.0,0,0
HB-059817,City Hotel,1,30,2024,November,44,2,2024-11-02,4,9,1,2.0,0,BB,USA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,186.22,0,0
HB-078633,City Hotel,1,14,2023,October,41,15,2023-10-15,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,99.0,,0,Transient-Party,100.0,0,0
HB-030671,Resort Hotel,0,1,2024,November,48,29,2024-11-29,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,1,3
HB-062438,City Hotel,1,54,2025,January,3,14,2025-01-14,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,Non Refund,,67.0,16,Transient,75.0,0,0
HB-016352,Resort Hotel,0,58,2023,August,33,20,2023-08-20,2,4,2,0.0,0,HB,BEL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,153.3,0,1
HB-016574,Resort Hotel,0,110,2025,June,24,15,2025-06-15,2,7,2,0.0,0,BB,IRL,Online TA,TA/TO,1,0,1,C,C,1,No Deposit,240.0,,0,Transient,160.0,0,0
HB-091654,City Hotel,0,19,2024,June,25,22,2024-06-22,0,2,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,1,No Deposit,215.0,,0,Transient-Party,100.0,0,0
HB-033058,Resort Hotel,0,32,2025,February,6,8,2025-02-08,1,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient-Party,68.0,0,2
HB-032164,Resort Hotel,0,1,2025,January,3,19,2025-01-19,0,2,2,0.0,0,BB,FRA,Direct,TA/TO,0,0,0,D,D,1,No Deposit,,,0,Transient,62.0,1,0
HB-032420,Resort Hotel,0,85,2025,January,1,5,2025-01-05,6,15,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,241.0,,0,Transient,69.99,0,1
HB-106334,City Hotel,0,44,2025,February,8,19,2025-02-19,2,3,2,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,61.93,0,1
HB-048608,City Hotel,1,36,2024,March,13,25,2024-03-25,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,137.4,0,1
HB-001440,Resort Hotel,0,136,2023,August,35,29,2023-08-29,2,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,112.0,0,2
HB-051935,City Hotel,0,316,2024,May,21,26,2024-05-26,0,3,2,0.0,0,BB,AUT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,110.0,0,0
HB-012935,Resort Hotel,1,32,2025,July,30,24,2025-07-24,1,3,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,135.0,0,0
HB-024410,Resort Hotel,0,2,2024,May,20,15,2024-05-15,2,3,2,3.0,0,BB,PRT,Corporate,Corporate,0,0,0,H,H,1,No Deposit,,110.0,0,Transient,140.0,1,3
HB-097481,City Hotel,0,115,2024,September,37,13,2024-09-13,0,4,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,118.8,0,0
HB-021083,Resort Hotel,0,31,2024,February,7,14,2024-02-14,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,53.2,0,2
HB-034921,Resort Hotel,0,152,2025,April,14,5,2025-04-05,0,4,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,1,No Deposit,,223.0,0,Transient-Party,48.0,0,0
HB-093891,City Hotel,0,24,2024,July,30,26,2024-07-26,0,2,3,0.0,0,BB,TWN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,187.0,0,0
HB-090343,City Hotel,0,144,2024,June,22,2,2024-06-02,0,3,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,95.4,0,0
HB-033732,Resort Hotel,0,13,2025,February,8,21,2025-02-21,2,7,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,436.0,,0,Transient,44.0,0,0
HB-111148,City Hotel,0,334,2025,May,18,2,2025-05-02,0,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,132.3,1,3
HB-065024,City Hotel,1,305,2025,March,12,22,2025-03-22,0,4,2,2.0,0,BB,DNK,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient,141.14,0,0
HB-053613,City Hotel,1,77,2024,June,26,26,2024-06-26,1,0,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.3,0,1
HB-032046,Resort Hotel,0,3,2025,January,3,14,2025-01-14,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-100256,City Hotel,0,87,2024,October,43,22,2024-10-22,2,1,3,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,105.4,0,0
HB-021597,Resort Hotel,0,1,2024,March,9,1,2024-03-01,0,4,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,44.66,0,1
HB-102775,City Hotel,0,50,2024,December,49,3,2024-12-03,2,1,2,0.0,1,BB,ESP,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,88.2,0,1
HB-014111,Resort Hotel,0,8,2024,September,39,23,2024-09-23,1,2,2,0.0,0,BB,,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,446.0,,0,Transient,103.5,0,0
HB-015446,Resort Hotel,0,5,2023,July,28,15,2023-07-15,0,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,119.25,1,1
HB-090065,City Hotel,0,55,2024,May,22,29,2024-05-29,2,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,120.0,0,0
HB-097265,City Hotel,0,82,2024,September,36,5,2024-09-05,3,7,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,16.0,,0,Transient,90.95,0,0
HB-116366,City Hotel,0,151,2025,July,28,12,2025-07-12,2,5,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,143.1,0,2
HB-109089,City Hotel,0,120,2025,April,14,3,2025-04-03,1,2,1,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,109.8,0,1
HB-026598,Resort Hotel,0,1,2024,August,31,4,2024-08-04,0,1,2,0.0,1,BB,PRT,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,199.0,0,3
HB-079928,City Hotel,0,21,2023,November,44,5,2023-11-05,0,2,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,76.0,0,0
HB-090027,City Hotel,0,4,2024,May,22,31,2024-05-31,0,1,1,0.0,0,BB,FRA,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,260.0,0,Transient-Party,121.0,0,0
HB-037575,Resort Hotel,0,75,2025,June,24,15,2025-06-15,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,G,G,1,No Deposit,240.0,,0,Transient,223.57,0,1
HB-110851,City Hotel,0,325,2025,May,18,1,2025-05-01,1,0,1,0.0,0,BB,USA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,93.5,0,1
HB-038473,Resort Hotel,0,90,2025,July,28,12,2025-07-12,2,5,1,1.0,1,BB,PRT,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,242.0,,0,Transient,224.16,0,3
HB-005238,Resort Hotel,1,83,2024,April,17,22,2024-04-22,2,5,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,71.0,,0,Transient,46.0,0,0
HB-002908,Resort Hotel,0,38,2023,November,45,6,2023-11-06,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,57.0,0,1
HB-114310,City Hotel,0,172,2025,June,25,18,2025-06-18,2,0,2,2.0,0,BB,USA,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,7.0,,0,Transient,219.46,0,1
HB-091373,City Hotel,0,45,2024,June,25,17,2024-06-17,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,65.0,0,1
HB-062384,City Hotel,1,552,2025,January,2,12,2025-01-12,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-083044,City Hotel,0,1,2024,January,2,13,2024-01-13,0,4,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,9.0,,0,Transient-Party,180.0,1,1
HB-068327,City Hotel,1,164,2025,May,20,15,2025-05-15,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-041939,City Hotel,1,1,2023,August,34,27,2023-08-27,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,160.0,0,0
HB-089957,City Hotel,0,16,2024,May,22,29,2024-05-29,2,0,2,0.0,0,BB,BRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,109.0,0,0
HB-049752,City Hotel,1,103,2024,April,16,19,2024-04-19,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,0,Transient,115.0,0,0
HB-011968,Resort Hotel,1,303,2025,June,23,5,2025-06-05,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,80.1,0,0
HB-066543,City Hotel,1,164,2025,April,17,21,2025-04-21,1,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,1
HB-011209,Resort Hotel,1,21,2025,April,18,29,2025-04-29,1,1,2,0.0,1,BB,PRT,Direct,Direct,0,0,0,C,C,0,No Deposit,,,0,Transient,114.0,0,0
HB-044286,City Hotel,1,198,2023,October,40,3,2023-10-03,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,60.0,0,0
HB-035541,Resort Hotel,0,203,2025,April,17,25,2025-04-25,0,2,2,0.0,0,HB,AUT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,502.0,,0,Transient-Party,90.0,0,0
HB-047063,City Hotel,1,28,2024,February,6,5,2024-02-05,2,7,1,0.0,0,BB,CPV,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,101.78,0,0
HB-108499,City Hotel,0,78,2025,March,13,25,2025-03-25,2,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,7.0,,0,Transient,77.23,0,1
HB-090884,City Hotel,0,19,2024,June,24,12,2024-06-12,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.35,0,1
HB-002272,Resort Hotel,0,77,2023,October,40,8,2023-10-08,0,3,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,250.0,,0,Contract,71.0,1,2
HB-071801,City Hotel,1,229,2025,July,28,12,2025-07-12,1,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-066648,City Hotel,1,100,2025,April,17,22,2025-04-22,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,0,Transient,105.0,0,0
HB-086327,City Hotel,0,116,2024,March,13,25,2024-03-25,2,5,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,104.14,0,1
HB-116739,City Hotel,0,89,2025,July,30,22,2025-07-22,1,1,2,1.0,1,BB,BRA,Direct,Direct,0,0,0,E,E,1,No Deposit,14.0,,0,Transient,180.0,0,3
HB-048002,City Hotel,1,64,2024,March,11,11,2024-03-11,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,73.95,0,0
HB-016339,Resort Hotel,0,80,2023,August,33,17,2023-08-17,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,149.0,,0,Transient,133.0,0,0
HB-065322,City Hotel,1,72,2025,March,14,31,2025-03-31,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,110.4,0,1
HB-010609,Resort Hotel,1,309,2025,March,12,18,2025-03-18,4,10,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,84.6,0,0
HB-093937,City Hotel,0,67,2024,July,30,24,2024-07-24,2,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.3,0,3
HB-114650,City Hotel,0,38,2025,June,25,21,2025-06-21,0,4,2,0.0,0,BB,HUN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,170.0,0,2
HB-082786,City Hotel,1,68,2024,February,7,17,2024-02-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,37.0,,0,Transient,75.0,0,0
HB-104434,City Hotel,0,275,2025,January,3,13,2025-01-13,0,1,3,0.0,0,BB,AUS,Direct,Direct,0,0,0,D,D,1,No Deposit,14.0,,0,Transient,116.7,0,1
HB-086353,City Hotel,0,30,2024,March,13,30,2024-03-30,0,2,2,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,85.5,0,0
HB-064870,City Hotel,1,10,2025,March,12,18,2025-03-18,1,1,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,168.0,0,0
HB-059243,City Hotel,1,83,2024,October,43,23,2024-10-23,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,115.56,0,0
HB-092122,City Hotel,0,49,2024,June,26,27,2024-06-27,1,4,2,0.0,0,BB,AUT,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,103.5,0,0
HB-034063,Resort Hotel,0,53,2025,March,10,5,2025-03-05,2,5,1,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,40.0,0,0
HB-002788,Resort Hotel,1,155,2023,October,44,31,2023-10-31,0,1,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient-Party,36.0,0,0
HB-010253,Resort Hotel,1,22,2025,February,8,23,2025-02-23,0,2,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,D,0,No Deposit,68.0,,0,Transient-Party,46.0,0,0
HB-030593,Resort Hotel,0,5,2024,November,48,26,2024-11-26,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,240.0,,0,Transient,43.0,0,1
HB-033049,Resort Hotel,0,32,2025,February,6,8,2025-02-08,1,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient-Party,68.0,0,2
HB-098021,City Hotel,0,271,2024,September,38,21,2024-09-21,0,3,1,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,12.0,,0,Transient-Party,85.67,0,0
HB-043402,City Hotel,0,74,2023,September,38,18,2023-09-18,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-078528,City Hotel,0,2,2023,October,41,10,2023-10-10,1,1,1,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,F,0,No Deposit,86.0,,0,Transient,106.4,0,0
HB-112157,City Hotel,0,63,2025,May,21,19,2025-05-19,0,2,2,0.0,0,SC,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,144.0,0,2
HB-063423,City Hotel,1,13,2025,February,7,11,2025-02-11,2,4,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,198.0,0,0
HB-001230,Resort Hotel,1,82,2023,August,33,19,2023-08-19,2,7,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,198.0,0,0
HB-115044,City Hotel,0,22,2025,June,26,28,2025-06-28,0,3,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,1
HB-000962,Resort Hotel,1,78,2023,August,32,8,2023-08-08,1,1,2,2.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,0,No Deposit,250.0,,0,Transient,181.0,0,0
HB-118596,City Hotel,0,199,2025,August,34,18,2025-08-18,2,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.72,0,1
HB-105504,City Hotel,0,11,2025,February,6,6,2025-02-06,1,3,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,51.05,0,2
HB-036217,Resort Hotel,0,101,2025,May,19,7,2025-05-07,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,72.66,0,0
HB-022580,Resort Hotel,0,2,2024,March,13,27,2024-03-27,2,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,43.2,0,1
HB-093603,City Hotel,0,226,2024,July,30,22,2024-07-22,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,96,Transient-Party,76.5,0,1
HB-107547,City Hotel,0,20,2025,March,11,13,2025-03-13,1,1,1,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,254.0,,0,Transient-Party,173.13,0,0
HB-027164,Resort Hotel,0,113,2024,August,33,13,2024-08-13,3,6,3,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,1,No Deposit,,,0,Transient,211.67,0,0
HB-008495,Resort Hotel,1,157,2024,October,40,1,2024-10-01,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,Non Refund,96.0,,0,Transient,52.0,0,0
HB-099489,City Hotel,0,1,2024,October,41,12,2024-10-12,0,2,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,100.1,0,1
HB-109539,City Hotel,0,143,2025,April,15,12,2025-04-12,0,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,2
HB-118791,City Hotel,0,55,2025,August,34,20,2025-08-20,2,3,1,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,2,No Deposit,98.0,,0,Transient-Party,115.0,0,0
HB-006106,Resort Hotel,0,224,2024,May,21,25,2024-05-25,1,4,2,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,A,2,No Deposit,,223.0,0,Transient-Party,66.0,0,0
HB-061201,City Hotel,1,23,2024,December,49,4,2024-12-04,2,0,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.0,0,1
HB-118229,City Hotel,0,62,2025,August,33,15,2025-08-15,0,2,2,0.0,0,BB,USA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,126.0,0,3
HB-051892,City Hotel,0,316,2024,May,21,26,2024-05-26,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,110.0,0,0
HB-039097,Resort Hotel,0,1,2025,August,32,6,2025-08-06,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,241.0,,0,Transient,144.4,0,1
HB-054424,City Hotel,1,210,2024,July,29,15,2024-07-15,2,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,96.0,0,0
HB-077036,City Hotel,1,262,2023,November,45,9,2023-11-09,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-079233,City Hotel,1,444,2024,December,48,1,2024-12-01,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,34.0,,39,Transient,75.0,0,0
HB-050438,City Hotel,1,12,2024,April,18,30,2024-04-30,2,4,1,0.0,0,BB,AGO,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,154.33,0,0
HB-072847,City Hotel,1,478,2025,August,32,8,2025-08-08,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-064849,City Hotel,1,8,2025,March,12,17,2025-03-17,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,87.04,0,0
HB-087970,City Hotel,0,13,2024,April,17,26,2024-04-26,0,3,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,58.0,,0,Transient-Party,73.0,0,0
HB-105866,City Hotel,0,34,2025,February,7,12,2025-02-12,2,3,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,111.52,0,0
HB-006195,Resort Hotel,1,212,2024,May,22,28,2024-05-28,1,1,2,0.0,0,FB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,175.0,,0,Transient,83.16,0,0
HB-045036,City Hotel,1,102,2023,October,42,16,2023-10-16,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-012950,Resort Hotel,1,189,2025,July,30,24,2025-07-24,2,5,2,0.0,0,HB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,183.75,0,0
HB-026344,Resort Hotel,0,147,2024,July,30,22,2024-07-22,2,5,3,0.0,0,Undefined,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,196.0,,0,Transient,190.0,0,1
HB-023555,Resort Hotel,0,72,2024,April,18,29,2024-04-29,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,F,0,No Deposit,240.0,,0,Transient,101.25,0,0
HB-011284,Resort Hotel,1,221,2025,April,18,30,2025-04-30,2,5,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,83.43,0,0
HB-117508,City Hotel,0,156,2025,August,31,2,2025-08-02,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,168.0,,0,Transient,89.1,0,0
HB-001814,Resort Hotel,0,6,2023,September,37,16,2023-09-16,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,1,No Deposit,,204.0,0,Transient,55.0,0,0
HB-058855,City Hotel,1,54,2024,October,42,16,2024-10-16,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,72.0,0,0
HB-037138,Resort Hotel,0,1,2025,June,23,6,2025-06-06,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,123.5,0,0
HB-086757,City Hotel,0,86,2024,April,14,5,2024-04-05,0,3,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.5,0,1
HB-046846,City Hotel,0,19,2024,January,3,21,2024-01-21,0,1,1,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient-Party,75.0,0,1
HB-001983,Resort Hotel,0,79,2023,September,39,25,2023-09-25,2,3,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,89.0,0,1
HB-043887,City Hotel,1,87,2023,September,39,25,2023-09-25,2,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-000224,Resort Hotel,1,280,2023,July,27,8,2023-07-08,2,5,2,1.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,112.0,0,1
HB-101376,City Hotel,0,15,2024,November,45,8,2024-11-08,0,3,1,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,130.9,0,1
HB-086098,City Hotel,0,129,2024,March,13,25,2024-03-25,0,2,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,7.0,,0,Transient,72.75,0,0
HB-052313,City Hotel,1,177,2024,June,23,3,2024-06-03,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,119.0,,0,Transient-Party,100.0,0,0
HB-119390,City Hotel,0,205,2025,August,35,29,2025-08-29,2,7,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,151.2,0,2
HB-011669,Resort Hotel,1,462,2025,May,21,25,2025-05-25,0,3,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,78.0,0,0
HB-015041,Resort Hotel,0,81,2024,May,18,3,2024-05-03,2,7,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,1,0,1,D,D,1,No Deposit,314.0,,0,Transient,52.56,0,0
HB-062630,City Hotel,1,55,2025,January,3,18,2025-01-18,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,79.0,0,0
HB-001317,Resort Hotel,1,9,2023,August,34,23,2023-08-23,4,6,1,1.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,122.0,0,2
HB-116719,City Hotel,0,423,2025,July,30,22,2025-07-22,1,1,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,122.4,0,1
HB-026112,Resort Hotel,0,81,2024,July,29,16,2024-07-16,2,4,2,0.0,1,FB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,5.0,,0,Transient,174.0,0,0
HB-045965,City Hotel,1,104,2023,December,48,3,2023-12-03,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,55.0,,0,Transient,75.0,0,0
HB-117309,City Hotel,0,60,2025,July,31,30,2025-07-30,2,1,3,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,189.33,0,1
HB-027498,Resort Hotel,0,272,2024,August,34,24,2024-08-24,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,171.0,,0,Transient,140.31,0,1
HB-063272,City Hotel,1,27,2025,February,6,4,2025-02-04,2,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.0,0,0
HB-078425,City Hotel,0,11,2023,October,40,4,2023-10-04,2,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,10.0,,0,Transient-Party,119.7,0,1
HB-026015,Resort Hotel,0,287,2024,July,28,12,2024-07-12,2,5,1,0.0,0,BB,NOR,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,8.0,,0,Transient,81.6,0,1
HB-083228,City Hotel,0,4,2024,January,4,25,2024-01-25,1,0,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,38.0,,0,Transient-Party,64.0,0,0
HB-048166,City Hotel,1,91,2024,March,12,18,2024-03-18,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,20,Transient,75.0,0,0
HB-087357,City Hotel,0,47,2024,April,16,15,2024-04-15,1,2,2,2.0,0,BB,POL,Online TA,TA/TO,0,0,0,F,F,2,No Deposit,9.0,,0,Transient,173.12,0,2
HB-084995,City Hotel,0,56,2024,March,9,2,2024-03-02,1,4,2,0.0,0,BB,ARG,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,55.38,0,0
HB-048653,City Hotel,1,72,2024,March,13,26,2024-03-26,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,96.0,0,0
HB-103658,City Hotel,0,74,2024,December,52,26,2024-12-26,1,2,2,0.0,0,BB,BGR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,102.6,0,1
HB-023628,Resort Hotel,0,12,2024,April,17,27,2024-04-27,0,3,2,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,A,A,1,No Deposit,385.0,,0,Transient-Party,85.33,0,0
HB-056506,City Hotel,1,426,2024,September,36,8,2024-09-08,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-025806,Resort Hotel,0,182,2024,July,27,5,2024-07-05,2,5,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,E,E,1,No Deposit,250.0,,0,Transient,97.75,0,1
HB-065616,City Hotel,1,62,2025,April,14,6,2025-04-06,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,135.0,0,0
HB-027219,Resort Hotel,0,0,2024,August,34,22,2024-08-22,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,179.0,0,1
HB-050506,City Hotel,1,437,2024,May,18,2,2024-05-02,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-043862,City Hotel,0,192,2023,September,39,25,2023-09-25,2,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,102.0,0,0
HB-046767,City Hotel,0,151,2024,January,3,19,2024-01-19,0,2,1,0.0,0,BB,CZE,Offline TA/TO,TA/TO,0,0,0,A,D,4,No Deposit,19.0,,63,Transient-Party,71.0,0,0
HB-054766,City Hotel,1,150,2024,July,30,25,2024-07-25,5,15,2,0.0,0,SC,AGO,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.1,0,0
HB-105896,City Hotel,0,19,2025,February,7,14,2025-02-14,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,168.0,,0,Transient,80.0,0,0
HB-012901,Resort Hotel,1,151,2025,July,30,22,2025-07-22,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient,151.0,0,0
HB-004759,Resort Hotel,0,169,2024,March,13,31,2024-03-31,0,3,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,D,1,Refundable,,223.0,0,Transient-Party,66.0,0,0
HB-093165,City Hotel,0,70,2024,July,28,14,2024-07-14,1,3,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,7.0,,0,Transient,165.63,0,2
HB-056743,City Hotel,1,5,2024,September,37,12,2024-09-12,1,1,1,0.0,0,BB,PRT,Aviation,Corporate,0,0,0,D,D,0,No Deposit,,153.0,0,Transient,110.0,0,0
HB-013567,Resort Hotel,1,337,2025,August,34,20,2025-08-20,2,1,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,185.75,0,0
HB-007951,Resort Hotel,1,237,2024,September,36,4,2024-09-04,2,3,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,147.0,,0,Transient,89.3,0,0
HB-082186,City Hotel,1,99,2024,February,8,19,2024-02-19,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,1,0,A,A,0,No Deposit,,67.0,0,Transient-Party,80.0,0,0
HB-061100,City Hotel,1,98,2024,December,49,2,2024-12-02,0,2,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,1
HB-050775,City Hotel,0,125,2024,May,19,7,2024-05-07,2,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,9.0,,0,Transient,114.3,0,1
HB-092227,City Hotel,0,51,2024,July,27,1,2024-07-01,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.9,0,1
HB-080688,City Hotel,0,55,2023,November,46,18,2023-11-18,0,4,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Transient,60.0,0,1
HB-089216,City Hotel,0,92,2024,May,20,15,2024-05-15,2,2,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,9.0,,0,Transient,150.45,0,2
HB-006651,Resort Hotel,0,253,2024,June,25,22,2024-06-22,0,3,2,0.0,0,HB,POL,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,92.0,0,0
HB-045470,City Hotel,1,99,2023,October,44,30,2023-10-30,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,65.0,0,0
HB-088018,City Hotel,0,16,2024,March,11,11,2024-03-11,14,35,0,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,K,21,No Deposit,,215.0,0,Transient-Party,0.0,0,0
HB-037845,Resort Hotel,0,9,2025,June,27,30,2025-06-30,0,1,2,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,B,1,No Deposit,,525.0,0,Transient-Party,120.0,0,0
HB-112234,City Hotel,0,96,2025,May,21,20,2025-05-20,1,1,1,0.0,0,BB,ITA,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,126.0,0,0
HB-109222,City Hotel,0,91,2025,April,14,5,2025-04-05,0,4,1,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,7.0,,0,Transient,69.3,0,1
HB-083034,City Hotel,0,0,2024,January,2,14,2024-01-14,0,1,1,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,64.0,0,0
HB-083508,City Hotel,0,31,2024,February,5,4,2024-02-04,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,1,No Deposit,,174.0,0,Transient-Party,77.0,0,0
HB-074538,City Hotel,1,339,2023,September,38,21,2023-09-21,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-050137,City Hotel,1,146,2024,April,17,24,2024-04-24,2,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,26.0,,50,Transient,95.0,0,0
HB-010747,Resort Hotel,1,64,2025,March,14,31,2025-03-31,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,2
HB-031169,Resort Hotel,0,27,2024,December,50,9,2024-12-09,2,6,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,G,G,1,No Deposit,250.0,,0,Transient,87.46,1,1
HB-044817,City Hotel,1,105,2023,October,41,12,2023-10-12,1,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,110.0,0,0
HB-094128,City Hotel,0,198,2024,July,31,30,2024-07-30,1,1,1,0.0,0,HB,ITA,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,0.0,0,1
HB-001844,Resort Hotel,0,110,2023,September,37,17,2023-09-17,1,3,1,0.0,0,BB,NLD,Direct,Direct,0,0,0,A,A,1,No Deposit,250.0,,0,Transient-Party,65.0,0,0
HB-040470,City Hotel,1,19,2023,July,30,25,2023-07-25,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-104390,City Hotel,0,52,2025,January,2,10,2025-01-10,0,2,2,2.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,148.2,0,1
HB-017869,Resort Hotel,0,7,2023,October,43,24,2023-10-24,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,58.0,1,2
HB-003379,Resort Hotel,1,149,2023,December,49,5,2023-12-05,2,1,2,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,38.0,,0,Transient,68.0,0,0
HB-024848,Resort Hotel,0,210,2024,June,22,2,2024-06-02,0,3,3,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,115.0,,0,Transient,129.44,0,1
HB-029923,Resort Hotel,0,22,2024,November,45,7,2024-11-07,1,1,1,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,60.0,0,1
HB-094155,City Hotel,0,301,2024,July,31,30,2024-07-30,1,1,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-032676,Resort Hotel,0,0,2025,February,5,1,2025-02-01,0,0,2,0.0,0,BB,PRT,Online TA,TA/TO,1,0,0,A,D,0,No Deposit,240.0,,0,Transient,0.0,0,1
HB-068973,City Hotel,1,166,2025,May,21,24,2025-05-24,0,2,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,108.0,0,3
HB-018698,Resort Hotel,0,12,2023,November,47,25,2023-11-25,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,196.0,,0,Transient,25.0,0,0
HB-100354,City Hotel,0,12,2024,October,43,26,2024-10-26,0,1,1,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,130.0,0,0
HB-038520,Resort Hotel,0,143,2025,July,29,16,2025-07-16,2,3,3,0.0,0,HB,PRT,Direct,Direct,0,0,0,E,E,1,No Deposit,250.0,,0,Transient,299.2,1,0
HB-027663,Resort Hotel,0,207,2024,August,35,29,2024-08-29,2,5,2,0.0,0,BB,ROU,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,11.0,,0,Transient,75.6,0,0
HB-046426,City Hotel,0,30,2024,January,1,1,2024-01-01,0,2,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,92.0,0,1
HB-108384,City Hotel,0,4,2025,March,13,25,2025-03-25,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.0,0,2
HB-086513,City Hotel,0,84,2024,March,13,30,2024-03-30,1,4,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,75.34,0,0
HB-016413,Resort Hotel,1,288,2023,September,35,2,2023-09-02,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,1,No Deposit,240.0,,0,Transient-Party,110.7,0,0
HB-054480,City Hotel,1,21,2024,July,29,17,2024-07-17,2,1,4,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,8.0,,0,Transient,299.33,0,0
HB-051689,City Hotel,1,158,2024,May,21,24,2024-05-24,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,31,Transient,130.0,0,0
HB-030687,Resort Hotel,0,12,2024,December,49,2,2024-12-02,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,1,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-089726,City Hotel,0,48,2024,May,21,22,2024-05-22,2,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,92.83,0,2
HB-092743,City Hotel,0,138,2024,July,27,5,2024-07-05,1,5,2,0.0,0,HB,AUT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,16.0,,0,Transient,102.25,0,0
HB-069713,City Hotel,1,173,2025,June,23,4,2025-06-04,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,120.0,0,0
HB-060567,City Hotel,1,261,2024,November,46,15,2024-11-15,0,4,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,106.25,0,0
HB-088631,City Hotel,0,0,2024,May,19,9,2024-05-09,1,0,2,0.0,0,SC,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,68.53,0,1
HB-070736,City Hotel,1,153,2025,June,25,21,2025-06-21,0,4,1,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,A,0,Non Refund,,348.0,0,Transient,110.0,0,0
HB-037440,Resort Hotel,0,162,2025,June,24,12,2025-06-12,1,5,2,0.0,1,HB,PRT,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,155.0,0,2
HB-111781,City Hotel,0,92,2025,May,20,12,2025-05-12,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,147.0,0,1
HB-018004,Resort Hotel,0,0,2024,April,14,7,2024-04-07,0,1,1,0.0,0,BB,PRT,Direct,Corporate,1,1,13,A,D,0,No Deposit,47.0,,0,Transient,42.0,0,0
HB-107753,City Hotel,0,53,2025,March,11,13,2025-03-13,1,4,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,92.02,0,1
HB-006635,Resort Hotel,1,127,2024,June,25,21,2024-06-21,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,106.0,0,1
HB-000150,Resort Hotel,1,93,2023,July,27,5,2023-07-05,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,15.0,,0,Transient,105.5,0,0
HB-055143,City Hotel,1,196,2024,August,32,6,2024-08-06,1,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.5,0,0
HB-107871,City Hotel,0,21,2025,March,11,16,2025-03-16,1,3,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,21.0,,0,Transient-Party,70.0,0,0
HB-085792,City Hotel,0,5,2024,March,12,19,2024-03-19,2,1,1,0.0,0,BB,USA,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,79.17,0,0
HB-089686,City Hotel,0,35,2024,May,21,21,2024-05-21,2,2,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,129.2,0,0
HB-092592,City Hotel,0,173,2024,July,28,8,2024-07-08,0,1,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,9.0,,0,Transient,177.3,0,2
HB-103959,City Hotel,0,46,2025,January,1,1,2025-01-01,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,65.0,0,0
HB-034284,Resort Hotel,0,175,2025,March,11,12,2025-03-12,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,46.8,0,2
HB-115394,City Hotel,0,405,2025,July,27,4,2025-07-04,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,114.4,0,0
HB-080589,City Hotel,0,5,2023,November,46,15,2023-11-15,2,3,1,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,73.15,0,0
HB-118764,City Hotel,0,41,2025,August,34,22,2025-08-22,0,3,2,1.0,0,SC,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,152.67,0,1
HB-057538,City Hotel,1,250,2024,September,39,26,2024-09-26,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,95.0,0,0
HB-004826,Resort Hotel,0,171,2024,April,14,4,2024-04-04,1,1,1,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,1,Non Refund,298.0,,0,Transient-Party,54.5,0,0
HB-011949,Resort Hotel,1,272,2025,June,23,4,2025-06-04,2,5,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,98.06,0,3
HB-015881,Resort Hotel,0,5,2023,August,31,1,2023-08-01,2,3,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,165.32,0,2
HB-046466,City Hotel,1,150,2024,January,1,2,2024-01-02,2,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,91,Transient,101.0,0,0
HB-053486,City Hotel,1,2,2024,June,25,22,2024-06-22,0,1,1,0.0,0,SC,DEU,Offline TA/TO,GDS,0,0,0,A,A,0,No Deposit,195.0,,0,Transient,124.0,0,0
HB-104480,City Hotel,0,165,2025,January,3,13,2025-01-13,0,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,89.1,0,1
HB-024521,Resort Hotel,0,87,2024,May,21,21,2024-05-21,2,1,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,125.33,0,2
HB-083742,City Hotel,0,57,2024,February,6,7,2024-02-07,2,2,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,B,B,1,No Deposit,,,0,Transient,65.0,0,1
HB-041098,City Hotel,0,41,2023,August,32,12,2023-08-12,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-002904,Resort Hotel,0,4,2023,November,45,6,2023-11-06,0,1,1,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,70.0,0,0
HB-027162,Resort Hotel,0,68,2024,August,34,22,2024-08-22,3,6,2,0.0,0,BB,ITA,Direct,Direct,0,0,0,D,D,2,No Deposit,250.0,,0,Transient,191.32,1,0
HB-056800,City Hotel,1,77,2024,September,37,14,2024-09-14,0,3,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,149.4,0,0
HB-012664,Resort Hotel,1,5,2025,July,28,11,2025-07-11,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,125.0,0,1
HB-064745,City Hotel,1,92,2025,March,11,15,2025-03-15,0,3,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,85.0,0,0
HB-098613,City Hotel,0,11,2024,September,40,30,2024-09-30,0,2,2,0.0,1,BB,DEU,Direct,Direct,0,0,0,E,A,1,No Deposit,14.0,,0,Transient,218.0,1,0
HB-099603,City Hotel,0,53,2024,October,42,14,2024-10-14,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,77.0,,0,Transient-Party,120.0,0,0
HB-117437,City Hotel,0,129,2025,July,31,30,2025-07-30,2,3,2,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,81.9,0,0
HB-007478,Resort Hotel,1,48,2024,August,32,11,2024-08-11,2,3,2,0.0,0,HB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,251.0,0,0
HB-026635,Resort Hotel,0,196,2024,August,31,1,2024-08-01,1,5,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,69.0,,0,Transient,90.1,0,0
HB-048965,City Hotel,1,73,2024,April,14,3,2024-04-03,2,1,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,72.0,0,0
HB-073051,City Hotel,1,51,2025,August,33,13,2025-08-13,2,1,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,210.0,0,1
HB-007179,Resort Hotel,1,154,2024,July,30,25,2024-07-25,1,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,222.33,0,1
HB-047917,City Hotel,1,19,2024,March,10,9,2024-03-09,0,3,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.0,0,0
HB-023949,Resort Hotel,0,40,2024,May,19,7,2024-05-07,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,85.0,0,1
HB-041214,City Hotel,1,39,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,101.5,0,0
HB-069860,City Hotel,1,183,2025,June,23,8,2025-06-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,86.0,,0,Transient,120.0,0,0
HB-087895,City Hotel,0,63,2024,April,17,25,2024-04-25,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.6,0,1
HB-052498,City Hotel,1,213,2024,June,23,7,2024-06-07,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,62,Transient,130.0,0,0
HB-001439,Resort Hotel,0,11,2023,August,35,29,2023-08-29,2,3,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,140.4,1,2
HB-072325,City Hotel,1,160,2025,July,30,26,2025-07-26,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,42.0,,0,Transient,80.1,0,1
HB-084993,City Hotel,0,56,2024,March,9,3,2024-03-03,1,3,2,0.0,0,BB,ESP,Groups,Corporate,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,72.0,0,0
HB-066826,City Hotel,1,156,2025,April,17,26,2025-04-26,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,100.0,0,0
HB-091668,City Hotel,0,27,2024,June,25,22,2024-06-22,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,120.12,0,1
HB-105102,City Hotel,0,4,2025,January,5,27,2025-01-27,1,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,80.0,0,0
HB-013142,Resort Hotel,1,352,2025,August,31,1,2025-08-01,4,10,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,190.96,0,1
HB-025611,Resort Hotel,0,18,2024,July,27,1,2024-07-01,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,129.0,0,1
HB-109714,City Hotel,0,105,2025,April,15,13,2025-04-13,0,3,2,0.0,0,SC,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,42.0,,0,Transient,80.1,0,1
HB-112927,City Hotel,0,12,2025,May,22,29,2025-05-29,1,0,1,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,A,0,No Deposit,,45.0,0,Transient,0.0,0,0
HB-045197,City Hotel,0,52,2023,October,43,23,2023-10-23,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,7.0,,0,Transient,72.76,0,1
HB-033615,Resort Hotel,0,119,2025,February,9,25,2025-02-25,2,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,62.0,0,0
HB-008290,Resort Hotel,0,343,2024,September,38,21,2024-09-21,0,4,2,0.0,0,HB,BEL,Corporate,Corporate,0,0,0,A,A,0,No Deposit,183.0,,0,Transient-Party,92.0,0,0
HB-080878,City Hotel,0,73,2023,November,47,24,2023-11-24,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,12.0,,27,Transient-Party,0.0,0,0
HB-052714,City Hotel,0,282,2024,June,23,9,2024-06-09,0,3,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,48,Transient-Party,73.33,0,1
HB-036390,Resort Hotel,0,94,2025,May,20,16,2025-05-16,0,3,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,240.0,,0,Transient,100.0,0,1
HB-056009,City Hotel,1,149,2024,August,35,26,2024-08-26,2,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.5,0,0
HB-078120,City Hotel,0,17,2023,October,40,2,2023-10-02,0,2,2,0.0,0,BB,AUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,89.71,0,1
HB-067144,City Hotel,1,8,2025,April,18,29,2025-04-29,0,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,1
HB-071082,City Hotel,1,142,2025,June,26,28,2025-06-28,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,125.0,0,0
HB-031804,Resort Hotel,0,0,2025,January,1,5,2025-01-05,0,2,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,E,E,1,No Deposit,,,0,Transient,64.0,0,0
HB-077284,City Hotel,0,0,2023,September,37,15,2023-09-15,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,B,0,No Deposit,,,0,Transient,95.0,0,0
HB-009941,Resort Hotel,1,43,2025,January,5,27,2025-01-27,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,48.0,0,0
HB-001388,Resort Hotel,0,30,2023,August,35,28,2023-08-28,0,1,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,G,0,No Deposit,250.0,,0,Transient,115.0,0,3
HB-080851,City Hotel,0,0,2023,November,47,26,2023-11-26,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,148.0,,0,Transient,88.0,0,0
HB-017381,Resort Hotel,0,67,2023,October,40,4,2023-10-04,2,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,52.4,0,1
HB-000800,Resort Hotel,0,3,2023,July,30,30,2023-07-30,0,3,3,1.0,0,HB,PRT,Direct,Direct,0,0,0,G,G,0,No Deposit,,,0,Transient,250.33,0,2
HB-089304,City Hotel,0,2,2024,May,20,19,2024-05-19,0,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient,0.0,0,2
HB-115344,City Hotel,0,139,2025,July,27,2,2025-07-02,2,1,2,0.0,0,HB,CZE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,150.3,0,0
HB-078852,City Hotel,0,289,2023,October,42,17,2023-10-17,0,1,2,0.0,0,BB,SWE,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,67.0,0,0
HB-107900,City Hotel,0,176,2025,March,12,18,2025-03-18,1,1,2,0.0,0,SC,IND,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,1
HB-054175,City Hotel,1,166,2024,July,27,7,2024-07-07,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,99.45,0,0
HB-009763,Resort Hotel,1,196,2024,December,1,30,2024-12-30,1,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,,308.0,0,Transient-Party,114.0,0,0
HB-043019,City Hotel,0,68,2023,September,37,12,2023-09-12,2,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,60.0,0,0
HB-047564,City Hotel,1,53,2024,February,9,27,2024-02-27,2,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,3,No Deposit,9.0,,0,Transient,84.3,0,2
HB-079694,City Hotel,0,10,2024,February,5,4,2024-02-04,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,1,No Deposit,,40.0,0,Transient-Party,66.0,0,0
HB-106473,City Hotel,0,134,2025,February,9,25,2025-02-25,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,75.0,0,0
HB-115925,City Hotel,0,153,2025,July,28,11,2025-07-11,0,2,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,141.3,0,0
HB-013489,Resort Hotel,1,247,2025,August,33,17,2025-08-17,1,3,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,315.0,,0,Contract,130.05,0,0
HB-083611,City Hotel,0,0,2024,February,6,8,2024-02-08,0,0,1,0.0,0,BB,PRT,Direct,Direct,1,0,0,D,D,0,No Deposit,,,0,Transient,0.0,0,0
HB-091194,City Hotel,0,2,2024,June,24,16,2024-06-16,0,2,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,129.0,0,1
HB-079424,City Hotel,1,137,2024,January,4,27,2024-01-27,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,29.0,,45,Transient,70.0,0,0
HB-019283,Resort Hotel,1,28,2024,January,1,1,2024-01-01,2,6,2,2.0,0,BB,PRT,Online TA,TA/TO,0,1,0,G,G,1,No Deposit,240.0,,0,Transient,94.25,0,0
HB-046326,City Hotel,1,140,2023,December,52,29,2023-12-29,0,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,70.0,0,0
HB-076420,City Hotel,1,358,2023,October,41,10,2023-10-10,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-027685,Resort Hotel,0,228,2024,September,36,2,2024-09-02,2,2,2,0.0,0,BB,USA,Direct,Direct,0,0,0,E,F,0,No Deposit,250.0,,0,Transient,111.75,1,0
HB-020053,Resort Hotel,0,1,2024,January,2,14,2024-01-14,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,25.0,0,0
HB-031767,Resort Hotel,0,0,2025,January,1,5,2025-01-05,0,1,2,0.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,6.0,,0,Transient,68.0,0,1
HB-037654,Resort Hotel,0,152,2025,June,24,11,2025-06-11,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Transient,70.4,0,0
HB-031324,Resort Hotel,0,54,2024,December,51,19,2024-12-19,1,4,2,0.0,1,BB,CHN,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,66.0,0,1
HB-102572,City Hotel,0,21,2024,November,48,30,2024-11-30,0,2,1,0.0,0,BB,POL,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,76.0,0,0
HB-050325,City Hotel,1,51,2024,April,17,28,2024-04-28,2,3,2,0.0,0,BB,GRC,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient-Party,116.1,0,0
HB-033859,Resort Hotel,0,56,2025,March,9,2,2025-03-02,1,3,2,1.0,0,BB,BEL,Direct,Direct,0,0,0,G,G,0,No Deposit,250.0,,0,Transient,103.0,1,0
HB-019135,Resort Hotel,1,193,2024,June,25,18,2024-06-18,4,10,1,0.0,0,BB,PRT,Online TA,TA/TO,1,1,0,A,A,0,No Deposit,240.0,,0,Transient,67.89,0,1
HB-073116,City Hotel,1,507,2025,August,33,15,2025-08-15,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-066823,City Hotel,1,156,2025,April,17,26,2025-04-26,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,100.0,0,0
HB-007544,Resort Hotel,1,105,2024,August,33,13,2024-08-13,4,6,2,2.0,0,HB,MAR,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,309.0,0,0
HB-099115,City Hotel,0,218,2024,October,41,7,2024-10-07,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,106.1,0,2
HB-022891,Resort Hotel,0,80,2024,April,14,7,2024-04-07,0,3,2,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,67.0,,0,Transient-Party,68.0,0,0
HB-078323,City Hotel,0,91,2024,September,37,14,2024-09-14,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,1,3,15,A,A,3,No Deposit,,40.0,0,Transient,65.0,0,0
HB-113360,City Hotel,0,229,2025,June,23,4,2025-06-04,2,0,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,172.8,0,1
HB-078878,City Hotel,0,34,2023,October,42,16,2023-10-16,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,104.85,0,0
HB-084599,City Hotel,0,36,2024,February,9,27,2024-02-27,1,1,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,107.3,1,1
HB-105481,City Hotel,0,15,2025,February,6,9,2025-02-09,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,91.8,0,1
HB-057837,City Hotel,1,281,2024,October,40,1,2024-10-01,2,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,174,Transient-Party,96.0,0,0
HB-111576,City Hotel,0,32,2025,May,19,7,2025-05-07,2,4,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,159.33,0,0
HB-074188,City Hotel,1,356,2023,October,40,8,2023-10-08,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-015536,Resort Hotel,0,106,2023,July,29,21,2023-07-21,0,3,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,F,0,No Deposit,241.0,,0,Transient,88.55,0,1
HB-030426,Resort Hotel,0,90,2024,November,46,17,2024-11-17,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,39.8,0,1
HB-001224,Resort Hotel,1,23,2023,August,33,19,2023-08-19,2,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,241.0,0,1
HB-031202,Resort Hotel,0,28,2024,December,51,16,2024-12-16,0,2,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,240.0,,0,Transient,54.0,1,1
HB-097403,City Hotel,0,48,2024,September,37,14,2024-09-14,0,2,3,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,E,E,2,No Deposit,281.0,,0,Transient-Party,175.0,0,0
HB-090021,City Hotel,0,18,2024,May,22,29,2024-05-29,2,1,1,0.0,0,BB,USA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,112.33,0,1
HB-086785,City Hotel,0,18,2024,April,15,8,2024-04-08,0,1,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.0,0,1
HB-116173,City Hotel,0,184,2025,July,29,15,2025-07-15,0,1,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,89.1,0,1
HB-040612,City Hotel,1,28,2023,August,31,3,2023-08-03,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-099395,City Hotel,0,279,2024,October,41,10,2024-10-10,1,2,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,16.0,,0,Transient-Party,76.5,0,1
HB-080686,City Hotel,0,32,2023,November,47,20,2023-11-20,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,119.0,,0,Transient-Party,73.0,0,0
HB-083750,City Hotel,0,18,2024,February,6,8,2024-02-08,1,2,1,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.0,0,1
HB-083263,City Hotel,0,33,2024,January,4,25,2024-01-25,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,1,No Deposit,38.0,,15,Transient-Party,59.0,0,0
HB-065256,City Hotel,1,58,2025,March,13,30,2025-03-30,0,3,1,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.8,0,0
HB-092019,City Hotel,0,13,2024,June,26,28,2024-06-28,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,146.0,0,1
HB-049370,City Hotel,0,104,2024,April,15,11,2024-04-11,1,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,65.67,0,1
HB-118666,City Hotel,0,93,2025,August,34,19,2025-08-19,2,3,1,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,98.0,,0,Transient-Party,123.0,0,0
HB-023378,Resort Hotel,0,1,2024,April,17,23,2024-04-23,0,1,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,240.0,,0,Transient,93.0,1,0
HB-077748,City Hotel,0,0,2023,September,38,21,2023-09-21,1,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,B,0,No Deposit,,,0,Transient,147.0,0,1
HB-039650,Resort Hotel,0,75,2025,August,34,22,2025-08-22,0,2,1,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,241.0,,0,Transient,202.0,0,1
HB-093761,City Hotel,0,104,2024,July,29,18,2024-07-18,3,6,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,120.8,0,3
HB-071388,City Hotel,1,214,2025,July,27,4,2025-07-04,0,3,2,1.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.1,0,0
HB-011498,Resort Hotel,1,233,2025,May,19,11,2025-05-11,2,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,67.5,0,0
HB-074714,City Hotel,0,0,2024,February,6,10,2024-02-10,0,1,1,0.0,0,BB,PRT,Complementary,Corporate,1,0,17,D,D,0,No Deposit,,45.0,0,Transient,0.0,0,2
HB-016605,Resort Hotel,1,216,2023,October,40,5,2023-10-05,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,E,E,0,No Deposit,171.0,,0,Transient,57.6,0,0
HB-110065,City Hotel,0,169,2025,April,16,20,2025-04-20,0,1,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,G,0,No Deposit,7.0,,0,Transient,90.09,0,1
HB-063329,City Hotel,1,580,2025,February,6,9,2025-02-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-000202,Resort Hotel,0,8,2023,July,27,7,2023-07-07,0,4,3,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,H,H,2,No Deposit,240.0,,0,Transient,193.0,0,1
HB-021159,Resort Hotel,0,0,2024,February,8,19,2024-02-19,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,,0,Transient,40.0,0,0
HB-056487,City Hotel,1,258,2024,September,36,8,2024-09-08,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,41,Transient,65.0,0,0
HB-057859,City Hotel,1,157,2024,October,40,1,2024-10-01,2,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,132.3,0,0
HB-082340,City Hotel,1,94,2024,March,10,4,2024-03-04,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,154.0,,28,Transient,80.0,0,0
HB-018923,Resort Hotel,0,17,2023,November,48,30,2023-11-30,1,3,1,0.0,0,BB,PRT,Groups,Corporate,0,0,0,A,A,0,No Deposit,,343.0,0,Transient-Party,36.0,0,0
HB-009117,Resort Hotel,0,14,2024,October,44,28,2024-10-28,0,2,3,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,2,No Deposit,,,0,Transient,68.0,0,1
HB-118997,City Hotel,0,213,2025,August,35,28,2025-08-28,1,3,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,19.0,,0,Transient-Party,104.0,0,2
HB-057680,City Hotel,1,240,2024,September,40,30,2024-09-30,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,140.4,0,0
HB-078390,City Hotel,0,5,2023,November,45,11,2023-11-11,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,2,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-026420,Resort Hotel,0,32,2024,July,30,27,2024-07-27,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,F,0,No Deposit,240.0,,0,Transient,208.5,0,0
HB-054920,City Hotel,1,56,2024,July,31,30,2024-07-30,2,2,3,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,168.3,0,0
HB-004191,Resort Hotel,1,30,2024,February,9,26,2024-02-26,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,3
HB-106318,City Hotel,0,48,2025,February,8,22,2025-02-22,0,2,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,65.0,0,1
HB-021390,Resort Hotel,0,3,2024,February,9,27,2024-02-27,0,1,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,95.0,0,2
HB-078345,City Hotel,0,21,2023,October,40,7,2023-10-07,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,85.0,0,1
HB-017504,Resort Hotel,0,18,2023,October,41,12,2023-10-12,1,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,146.0,,0,Transient-Party,37.0,0,0
HB-111530,City Hotel,0,86,2025,May,19,9,2025-05-09,0,3,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,171.0,0,1
HB-020120,Resort Hotel,0,19,2024,January,3,16,2024-01-16,0,1,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,251.0,,0,Transient,37.0,0,0
HB-057030,City Hotel,1,302,2024,September,38,16,2024-09-16,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,70,Transient,100.0,0,0
HB-035218,Resort Hotel,0,89,2025,April,16,14,2025-04-14,0,2,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient-Party,122.0,0,3
HB-111419,City Hotel,0,24,2025,May,19,10,2025-05-10,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,180.0,0,1
HB-028986,Resort Hotel,0,2,2024,October,42,17,2024-10-17,1,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,327.0,,0,Transient,45.0,1,0
HB-065724,City Hotel,1,32,2025,April,14,6,2025-04-06,2,4,2,0.0,0,SC,MAR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,0
HB-038005,Resort Hotel,0,0,2025,July,27,5,2025-07-05,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,541.0,0,Transient,93.0,0,0
HB-001336,Resort Hotel,1,61,2023,August,34,24,2023-08-24,1,5,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,150.83,0,1
HB-047266,City Hotel,1,4,2024,February,7,14,2024-02-14,1,0,2,0.0,0,SC,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,118.0,,0,Transient,60.4,0,0
HB-017574,Resort Hotel,0,287,2023,October,41,15,2023-10-15,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,,223.0,0,Transient-Party,44.5,0,2
HB-013562,Resort Hotel,1,353,2025,August,34,19,2025-08-19,4,6,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,244.0,0,1
HB-075450,City Hotel,1,334,2023,September,37,16,2023-09-16,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-117059,City Hotel,0,201,2025,July,31,28,2025-07-28,0,1,2,1.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,148.0,0,1
HB-023569,Resort Hotel,0,6,2025,June,23,8,2025-06-08,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,1,0,1,A,A,0,No Deposit,5.0,,0,Transient,105.6,0,0
HB-042279,City Hotel,1,63,2023,September,36,4,2023-09-04,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,116.0,0,0
HB-105844,City Hotel,0,53,2025,February,7,11,2025-02-11,2,3,2,0.0,0,BB,JPN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,68.0,0,1
HB-104498,City Hotel,0,1,2025,January,2,11,2025-01-11,0,4,1,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,47.04,0,0
HB-013737,Resort Hotel,1,152,2025,August,35,28,2025-08-28,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,95.0,,0,Transient,141.0,0,0
HB-056534,City Hotel,1,433,2024,September,36,8,2024-09-08,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,70.0,0,0
HB-016085,Resort Hotel,0,69,2023,August,32,10,2023-08-10,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,134.0,0,0
HB-031040,Resort Hotel,0,82,2024,December,49,7,2024-12-07,0,4,2,0.0,0,BB,ESP,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,39.3,1,0
HB-117795,City Hotel,0,149,2025,August,31,3,2025-08-03,2,5,2,0.0,0,BB,SWE,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,80.1,0,1
HB-008919,Resort Hotel,1,386,2024,October,42,20,2024-10-20,1,3,2,0.0,0,BB,PRT,Groups,Corporate,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,49.0,0,0
HB-116697,City Hotel,0,423,2025,July,30,22,2025-07-22,1,1,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,122.4,0,1
HB-037215,Resort Hotel,0,137,2025,June,23,4,2025-06-04,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Transient,70.4,0,0
HB-109145,City Hotel,0,0,2025,April,14,5,2025-04-05,0,2,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,1
HB-011630,Resort Hotel,1,62,2025,May,21,22,2025-05-22,1,3,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,C,C,2,No Deposit,240.0,,0,Transient,125.0,0,1
HB-095309,City Hotel,0,1,2024,August,33,17,2024-08-17,0,1,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,89.0,,0,Transient,109.8,0,0
HB-040541,City Hotel,0,64,2023,July,30,28,2023-07-28,2,5,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,88.4,0,1
HB-003430,Resort Hotel,1,81,2023,December,49,6,2023-12-06,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,41.4,0,2
HB-020197,Resort Hotel,0,10,2024,January,3,19,2024-01-19,0,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,I,0,No Deposit,240.0,,0,Transient,0.0,0,1
HB-022544,Resort Hotel,0,1,2024,March,13,27,2024-03-27,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,38.4,0,0
HB-103565,City Hotel,0,41,2024,December,52,27,2024-12-27,0,1,2,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,220.0,,0,Transient-Party,65.0,0,0
HB-012989,Resort Hotel,1,93,2025,July,30,26,2025-07-26,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,2,No Deposit,241.0,,0,Transient,206.12,0,1
HB-117876,City Hotel,0,168,2025,August,32,7,2025-08-07,1,3,1,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,99.18,0,1
HB-050898,City Hotel,1,162,2024,May,19,11,2024-05-11,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Contract,135.0,0,0
HB-006350,Resort Hotel,1,78,2024,June,23,4,2024-06-04,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,116.0,0,0
HB-070073,City Hotel,1,219,2025,June,24,9,2025-06-09,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,105.0,0,0
HB-075789,City Hotel,1,323,2023,September,36,5,2023-09-05,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-055969,City Hotel,1,232,2024,August,34,25,2024-08-25,0,3,1,0.0,0,BB,AUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.9,0,0
HB-105569,City Hotel,0,17,2025,February,7,10,2025-02-10,0,2,1,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,57.06,0,0
HB-118956,City Hotel,0,171,2025,August,34,23,2025-08-23,0,4,3,0.0,0,BB,VNM,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,7.0,,0,Transient,133.38,0,1
HB-027312,Resort Hotel,0,214,2024,August,33,16,2024-08-16,2,8,2,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,206.2,0,2
HB-008415,Resort Hotel,1,339,2024,September,39,26,2024-09-26,3,6,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,15.0,,0,Transient,80.0,0,0
HB-102193,City Hotel,0,44,2024,November,47,22,2024-11-22,0,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.8,0,2
HB-095738,City Hotel,0,107,2024,August,34,21,2024-08-21,2,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.7,0,1
HB-042946,City Hotel,0,168,2023,September,37,11,2023-09-11,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,50.0,0,0
HB-053700,City Hotel,1,101,2024,June,26,27,2024-06-27,1,5,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,140.0,0,0
HB-013870,Resort Hotel,0,4,2024,January,4,26,2024-01-26,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,1,A,D,0,No Deposit,,94.0,0,Transient,33.0,1,0
HB-052919,City Hotel,1,71,2024,June,24,14,2024-06-14,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,120.0,0,0
HB-111687,City Hotel,0,0,2025,May,20,13,2025-05-13,0,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient,169.0,0,1
HB-024782,Resort Hotel,0,252,2024,June,22,1,2024-06-01,0,2,2,0.0,0,BB,URY,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,92.0,1,2
HB-006299,Resort Hotel,0,216,2024,June,22,1,2024-06-01,2,7,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,C,C,0,No Deposit,8.0,,0,Transient,58.1,0,0
HB-065789,City Hotel,1,60,2025,April,15,8,2025-04-08,2,1,1,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,144.0,0,1
HB-046383,City Hotel,1,148,2023,December,52,30,2023-12-30,1,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,79,Transient,67.0,0,0
HB-114080,City Hotel,0,45,2025,June,24,15,2025-06-15,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,150.0,0,1
HB-067965,City Hotel,1,316,2025,May,19,10,2025-05-10,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,123.3,0,1
HB-006560,Resort Hotel,1,256,2024,June,25,17,2024-06-17,2,7,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,72.0,0,1
HB-033184,Resort Hotel,0,70,2025,February,7,12,2025-02-12,2,3,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,65.91,0,1
HB-108558,City Hotel,0,1,2025,March,13,27,2025-03-27,1,1,1,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,95.0,0,0
HB-070591,City Hotel,1,210,2025,June,25,19,2025-06-19,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,154.0,,0,Transient,130.0,0,0
HB-098639,City Hotel,0,254,2024,September,39,29,2024-09-29,1,3,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,100.3,0,0
HB-062484,City Hotel,1,38,2025,January,3,14,2025-01-14,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,Non Refund,,67.0,0,Transient,75.0,0,0
HB-087267,City Hotel,0,29,2024,April,15,13,2024-04-13,0,4,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,143.18,0,1
HB-022314,Resort Hotel,0,15,2024,March,12,19,2024-03-19,2,2,1,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient-Party,58.0,0,0
HB-103392,City Hotel,0,5,2024,December,51,21,2024-12-21,0,1,1,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,78.0,0,2
HB-052998,City Hotel,1,188,2024,June,24,15,2024-06-15,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,39,Transient,130.0,0,0
HB-082334,City Hotel,1,1,2023,December,52,29,2023-12-29,0,4,2,0.0,1,BB,PRT,Groups,TA/TO,0,0,0,B,B,2,No Deposit,29.0,,0,Transient,72.5,0,2
HB-021472,Resort Hotel,0,7,2024,February,9,26,2024-02-26,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,68.0,0,1
HB-112676,City Hotel,0,151,2025,May,21,23,2025-05-23,0,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,162.0,0,4
HB-070046,City Hotel,1,175,2025,June,24,9,2025-06-09,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,99.0,0,0
HB-107973,City Hotel,0,55,2025,March,11,16,2025-03-16,2,3,1,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,74.8,0,1
HB-002784,Resort Hotel,1,155,2023,October,44,31,2023-10-31,0,1,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,36.0,0,0
HB-070154,City Hotel,1,18,2025,June,24,11,2025-06-11,2,1,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,99.0,0,1
HB-037467,Resort Hotel,0,1,2025,June,24,15,2025-06-15,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,135.0,0,1
HB-061502,City Hotel,1,524,2024,December,50,15,2024-12-15,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-116217,City Hotel,0,65,2025,July,29,15,2025-07-15,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,126.0,0,1
HB-063791,City Hotel,1,38,2025,February,8,20,2025-02-20,1,5,2,0.0,0,BB,KOR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,98.6,0,1
HB-113116,City Hotel,0,26,2025,May,22,31,2025-05-31,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,2,No Deposit,229.0,,0,Transient-Party,0.0,0,0
HB-021002,Resort Hotel,0,2,2024,February,7,13,2024-02-13,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient,61.5,0,0
HB-073077,City Hotel,1,105,2025,August,33,14,2025-08-14,1,0,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,155.0,0,1
HB-110205,City Hotel,0,23,2025,April,17,23,2025-04-23,1,0,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,0.0,0,0
HB-056923,City Hotel,1,176,2024,September,37,15,2024-09-15,0,3,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,198.9,0,0
HB-009273,Resort Hotel,1,44,2024,November,45,6,2024-11-06,2,5,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,37.8,0,2
HB-079048,City Hotel,1,9,2023,October,43,28,2023-10-28,0,4,3,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,D,D,0,No Deposit,8.0,,0,Transient,166.25,0,2
HB-054191,City Hotel,1,3,2024,July,28,8,2024-07-08,0,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,139.0,0,0
HB-074215,City Hotel,1,278,2023,July,29,22,2023-07-22,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Contract,62.0,0,0
HB-024533,Resort Hotel,0,165,2024,May,20,17,2024-05-17,2,6,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,52.2,0,2
HB-002219,Resort Hotel,0,0,2023,October,40,6,2023-10-06,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,0.0,0,0
HB-082477,City Hotel,0,1,2023,December,52,29,2023-12-29,0,2,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,152.0,,0,Transient,72.67,0,0
HB-051338,City Hotel,0,148,2024,May,20,18,2024-05-18,0,4,2,1.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,108.19,0,2
HB-099397,City Hotel,0,279,2024,October,41,10,2024-10-10,1,2,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,16.0,,0,Transient-Party,76.5,0,1
HB-083231,City Hotel,0,0,2024,January,4,25,2024-01-25,1,0,1,0.0,0,BB,PRT,Corporate,Direct,0,0,0,A,A,0,No Deposit,,148.0,0,Transient,79.0,0,0
HB-080655,City Hotel,0,42,2023,November,47,20,2023-11-20,0,2,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Group,63.0,0,2
HB-074819,City Hotel,1,335,2023,September,37,17,2023-09-17,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,5.0,,0,Transient,75.0,0,0
HB-070768,City Hotel,1,186,2025,June,25,22,2025-06-22,0,3,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,166.5,0,1
HB-068289,City Hotel,1,104,2025,May,20,15,2025-05-15,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-041261,City Hotel,1,39,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,101.5,0,0
HB-075621,City Hotel,1,281,2023,July,30,25,2023-07-25,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-009798,Resort Hotel,1,36,2025,January,1,2,2025-01-02,3,7,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,42.0,0,2
HB-068983,City Hotel,1,208,2025,May,21,24,2025-05-24,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,12.0,0,0
HB-028876,Resort Hotel,0,1,2024,October,41,11,2024-10-11,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,104.0,,0,Transient,67.5,1,0
HB-044920,City Hotel,1,180,2023,October,42,16,2023-10-16,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,70.0,0,0
HB-033533,Resort Hotel,0,21,2025,February,8,22,2025-02-22,0,4,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,405.0,0,Transient-Party,36.0,0,0
HB-013703,Resort Hotel,1,19,2025,August,35,26,2025-08-26,4,6,2,1.0,0,FB,PRT,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,5.0,,0,Transient,245.3,0,0
HB-006271,Resort Hotel,1,33,2024,May,22,31,2024-05-31,2,5,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,162.71,0,0
HB-056755,City Hotel,1,32,2024,September,37,12,2024-09-12,1,4,0,2.0,0,BB,SAU,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient,124.25,0,0
HB-007989,Resort Hotel,1,211,2024,September,36,7,2024-09-07,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,D,D,0,Non Refund,1.0,,0,Transient,89.0,0,0
HB-089635,City Hotel,0,7,2024,May,20,18,2024-05-18,2,4,1,2.0,0,BB,BRA,Direct,Direct,0,0,0,G,G,0,No Deposit,14.0,,0,Transient,218.45,0,0
HB-095469,City Hotel,0,320,2024,August,33,18,2024-08-18,0,2,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,90.0,0,0
HB-035766,Resort Hotel,0,14,2025,April,18,29,2025-04-29,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,103.0,1,0
HB-074747,City Hotel,1,329,2023,September,37,11,2023-09-11,2,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,5.0,,0,Transient,80.0,0,0
HB-057306,City Hotel,0,271,2024,September,39,23,2024-09-23,0,2,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient-Party,95.4,0,0
HB-044377,City Hotel,0,28,2023,October,40,5,2023-10-05,1,0,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,94.5,0,2
HB-038747,Resort Hotel,0,219,2025,July,30,24,2025-07-24,1,4,2,1.0,0,Undefined,PRT,Direct,Direct,0,0,0,A,A,3,No Deposit,250.0,,0,Transient,249.38,1,0
HB-102740,City Hotel,0,0,2024,December,49,5,2024-12-05,1,0,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,0
HB-070457,City Hotel,1,448,2025,June,25,17,2025-06-17,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,90.0,0,0
HB-090571,City Hotel,0,247,2024,June,23,6,2024-06-06,1,1,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,93.0,0,0
HB-053247,City Hotel,1,101,2024,June,25,17,2024-06-17,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,95.88,0,0
HB-034352,Resort Hotel,0,0,2025,March,12,21,2025-03-21,0,1,1,0.0,0,HB,PRT,Complementary,Direct,0,0,0,A,E,0,No Deposit,,,0,Transient,0.0,0,0
HB-067921,City Hotel,1,197,2025,May,19,9,2025-05-09,0,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.7,0,1
HB-066830,City Hotel,1,156,2025,April,17,26,2025-04-26,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,100.0,0,0
HB-032022,Resort Hotel,0,4,2025,January,3,14,2025-01-14,0,1,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,D,0,No Deposit,168.0,,0,Transient-Party,68.0,0,0
HB-090653,City Hotel,0,118,2024,June,23,6,2024-06-06,1,2,1,0.0,0,BB,ESP,Offline TA/TO,Corporate,0,0,0,A,A,0,No Deposit,191.0,,0,Transient-Party,110.0,0,0
HB-100619,City Hotel,0,181,2024,October,44,28,2024-10-28,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.9,0,2
HB-053497,City Hotel,1,98,2024,June,25,23,2024-06-23,0,1,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.5,0,1
HB-033457,Resort Hotel,0,1,2025,February,8,23,2025-02-23,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,60.0,1,0
HB-056037,City Hotel,1,209,2024,August,35,27,2024-08-27,1,1,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.0,0,1
HB-092873,City Hotel,0,112,2024,July,27,6,2024-07-06,2,5,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,72.25,0,0
HB-097593,City Hotel,0,4,2024,September,38,16,2024-09-16,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,9.0,,0,Transient,183.0,0,1
HB-033486,Resort Hotel,0,22,2025,February,8,23,2025-02-23,0,2,2,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,68.0,,0,Transient-Party,60.0,0,0
HB-024464,Resort Hotel,0,5,2024,May,21,21,2024-05-21,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,196.0,,0,Transient,79.0,1,0
HB-066687,City Hotel,1,135,2025,April,17,23,2025-04-23,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,171.0,,0,Transient,90.0,0,0
HB-094280,City Hotel,0,4,2024,November,44,2,2024-11-02,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,4,A,A,0,No Deposit,,221.0,0,Transient,88.0,0,3
HB-057569,City Hotel,1,47,2024,September,39,27,2024-09-27,0,4,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.61,0,1
HB-008018,Resort Hotel,1,238,2024,September,36,7,2024-09-07,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,D,D,0,Non Refund,1.0,,0,Transient,89.0,0,0
HB-062751,City Hotel,1,251,2025,January,4,21,2025-01-21,2,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,77.35,0,0
HB-063508,City Hotel,1,62,2025,February,7,12,2025-02-12,2,2,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,132.6,0,1
HB-069447,City Hotel,1,62,2025,May,22,31,2025-05-31,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,,,7,Transient,135.0,0,0
HB-047425,City Hotel,1,30,2024,February,8,20,2024-02-20,2,4,1,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,73.42,0,0
HB-062153,City Hotel,1,29,2025,January,1,3,2025-01-03,0,2,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,1
HB-086129,City Hotel,0,0,2024,March,13,25,2024-03-25,1,2,2,1.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Contract,67.5,0,2
HB-106802,City Hotel,0,7,2025,February,9,26,2025-02-26,2,3,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,0
HB-066910,City Hotel,1,88,2025,April,17,26,2025-04-26,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,170.0,,0,Transient,140.0,0,0
HB-059444,City Hotel,1,286,2024,October,44,28,2024-10-28,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,65.0,0,0
HB-012356,Resort Hotel,1,311,2025,June,26,25,2025-06-25,2,5,2,2.0,0,BB,IRL,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,151.14,0,0
HB-085894,City Hotel,0,78,2024,March,12,22,2024-03-22,0,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,22.0,,0,Transient,69.7,0,0
HB-041255,City Hotel,0,39,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-074441,City Hotel,1,304,2023,August,33,17,2023-08-17,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-015969,Resort Hotel,0,67,2023,August,31,1,2023-08-01,2,6,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,240.0,,0,Transient,193.13,0,1
HB-029121,Resort Hotel,0,259,2024,October,42,14,2024-10-14,2,5,1,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,C,1,No Deposit,273.0,,0,Transient-Party,46.36,0,0
HB-117904,City Hotel,0,479,2025,August,32,9,2025-08-09,0,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,1
HB-087080,City Hotel,0,134,2024,April,15,9,2024-04-09,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,90.0,0,1
HB-070680,City Hotel,1,42,2025,June,25,20,2025-06-20,2,7,2,0.0,0,SC,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,1
HB-108003,City Hotel,0,59,2025,March,12,19,2025-03-19,2,0,2,0.0,1,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,1
HB-118175,City Hotel,0,171,2025,August,33,14,2025-08-14,1,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,139.5,1,0
HB-000319,Resort Hotel,0,116,2023,July,28,12,2023-07-12,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,40.0,,0,Contract,119.25,0,0
HB-050060,City Hotel,1,142,2024,April,17,22,2024-04-22,2,3,1,0.0,0,BB,POL,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,89.0,0,0
HB-003297,Resort Hotel,1,74,2023,December,49,4,2023-12-04,2,2,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,92.1,0,0
HB-050755,City Hotel,1,67,2024,May,19,7,2024-05-07,0,1,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,159.3,0,0
HB-057907,City Hotel,1,157,2024,October,40,3,2024-10-03,1,2,2,0.0,0,SC,MEX,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,0
HB-009188,Resort Hotel,1,378,2024,November,44,1,2024-11-01,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,248.0,,0,Transient,46.0,0,0
HB-048071,City Hotel,1,18,2024,March,11,15,2024-03-15,0,5,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,128.8,0,0
HB-071482,City Hotel,1,155,2025,July,27,6,2025-07-06,0,3,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,0
HB-071829,City Hotel,1,234,2025,July,28,13,2025-07-13,0,3,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,120.6,0,0
HB-024059,Resort Hotel,0,113,2024,May,19,11,2024-05-11,2,7,2,0.0,0,HB,POL,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,75.0,,0,Contract,68.85,0,0
HB-115909,City Hotel,0,214,2025,July,27,6,2025-07-06,2,5,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,156.6,0,2
HB-035366,Resort Hotel,0,27,2025,April,16,19,2025-04-19,0,1,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,,251.0,0,Transient,95.0,0,1
HB-038370,Resort Hotel,0,27,2025,July,28,13,2025-07-13,0,3,3,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,222.0,0,0
HB-094554,City Hotel,0,131,2024,August,31,1,2024-08-01,1,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,23.0,,0,Transient,81.25,0,1
HB-022754,Resort Hotel,0,64,2024,April,14,2,2024-04-02,2,1,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,A,D,0,No Deposit,250.0,,0,Transient,57.33,0,0
HB-107359,City Hotel,0,2,2025,March,11,11,2025-03-11,0,1,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,78.4,0,0
HB-118982,City Hotel,0,0,2025,August,35,27,2025-08-27,1,0,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.1,0,1
HB-020067,Resort Hotel,0,25,2024,January,2,14,2024-01-14,0,2,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,79.0,0,1
HB-030392,Resort Hotel,0,67,2024,November,47,18,2024-11-18,1,2,2,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,411.0,,0,Transient-Party,50.0,0,0
HB-095230,City Hotel,0,171,2024,August,32,11,2024-08-11,2,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.45,0,1
HB-016632,Resort Hotel,0,101,2023,August,35,29,2023-08-29,2,5,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,2,No Deposit,250.0,,0,Transient,135.14,0,1
HB-107275,City Hotel,0,3,2025,March,10,9,2025-03-09,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,98.0,0,2
HB-023775,Resort Hotel,0,2,2024,May,18,3,2024-05-03,0,1,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,87.0,0,1
HB-014351,Resort Hotel,0,4,2025,April,14,3,2025-04-03,1,0,1,0.0,0,BB,,Corporate,Corporate,0,0,1,A,A,0,No Deposit,,154.0,0,Transient,48.0,0,0
HB-094243,City Hotel,0,1,2024,August,31,1,2024-08-01,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,111.0,1,1
HB-064860,City Hotel,1,160,2025,March,12,17,2025-03-17,2,6,0,2.0,0,BB,EGY,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient,89.88,0,1
HB-028887,Resort Hotel,0,235,2024,October,42,17,2024-10-17,1,1,2,0.0,0,BB,BEL,Direct,Direct,0,0,1,D,D,0,No Deposit,,,0,Transient,74.5,1,1
HB-000987,Resort Hotel,0,2,2023,August,32,9,2023-08-09,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,134.0,0,1
HB-055518,City Hotel,1,133,2024,August,33,15,2024-08-15,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,83.0,,0,Transient,113.6,0,0
HB-077691,City Hotel,1,18,2023,October,40,4,2023-10-04,2,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,29.0,,0,Transient,110.0,0,0
HB-107102,City Hotel,0,137,2025,March,10,6,2025-03-06,1,1,2,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,80.0,0,1
HB-049837,City Hotel,1,265,2024,April,16,20,2024-04-20,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,176,Transient-Party,101.0,0,0
HB-091208,City Hotel,0,1,2024,June,24,15,2024-06-15,0,3,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,177.0,0,4
HB-044192,City Hotel,0,164,2023,October,40,2,2023-10-02,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,19.0,,0,Transient-Party,100.0,0,0
HB-003425,Resort Hotel,0,45,2023,December,49,5,2023-12-05,2,1,3,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,C,1,No Deposit,38.0,,0,Transient-Party,91.8,0,0
HB-076532,City Hotel,1,195,2023,September,37,17,2023-09-17,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,20.0,,0,Transient,48.0,0,0
HB-094810,City Hotel,0,59,2024,August,32,8,2024-08-08,1,1,1,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,131.4,0,1
HB-118052,City Hotel,0,102,2025,August,32,7,2025-08-07,2,5,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,7.0,,0,Transient,201.4,0,2
HB-083755,City Hotel,0,7,2024,May,21,24,2024-05-24,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,174.0,0,Transient,117.9,0,0
HB-020305,Resort Hotel,0,4,2024,January,4,23,2024-01-23,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,51.0,0,0
HB-103767,City Hotel,0,283,2024,December,52,28,2024-12-28,0,4,2,0.0,0,SC,UKR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,72.25,0,2
HB-049981,City Hotel,1,18,2024,April,17,22,2024-04-22,0,1,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,197.0,0,0
HB-058568,City Hotel,1,37,2024,October,41,13,2024-10-13,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,105.0,0,0
HB-116582,City Hotel,0,85,2025,July,29,20,2025-07-20,0,2,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,178.0,0,2
HB-090801,City Hotel,0,231,2024,June,23,8,2024-06-08,0,4,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Contract,115.2,0,1
HB-094576,City Hotel,0,114,2024,August,31,4,2024-08-04,0,3,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,106.5,1,1
HB-003221,Resort Hotel,0,78,2023,November,47,21,2023-11-21,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,342.0,0,Transient-Party,32.0,0,0
HB-097136,City Hotel,0,27,2024,September,37,9,2024-09-09,2,2,2,0.0,0,BB,IRN,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,86.0,,0,Transient-Party,167.2,0,0
HB-089668,City Hotel,0,6,2024,May,21,23,2024-05-23,1,1,2,0.0,0,SC,KOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.0,0,2
HB-066615,City Hotel,1,118,2025,April,17,22,2025-04-22,2,1,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,175.5,0,2
HB-112427,City Hotel,0,193,2025,May,21,23,2025-05-23,0,1,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,0
HB-049677,City Hotel,1,275,2024,April,16,17,2024-04-17,2,0,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,0,Transient,110.0,0,0
HB-058128,City Hotel,1,34,2024,October,40,6,2024-10-06,0,3,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,176.4,0,2
HB-074825,City Hotel,1,335,2023,September,37,17,2023-09-17,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,5.0,,0,Transient,85.0,0,0
HB-109309,City Hotel,0,127,2025,April,15,7,2025-04-07,0,2,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.5,0,2
HB-019403,Resort Hotel,0,0,2023,December,50,17,2023-12-17,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,E,0,No Deposit,,144.0,0,Transient,25.0,0,0
HB-045151,City Hotel,0,41,2023,October,42,19,2023-10-19,1,2,2,0.0,0,BB,VEN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,103.5,0,2
HB-119104,City Hotel,0,189,2025,August,35,27,2025-08-27,2,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient-Party,114.0,0,1
HB-035512,Resort Hotel,0,4,2025,April,17,24,2025-04-24,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,1,No Deposit,,437.0,0,Transient,72.0,1,0
HB-105902,City Hotel,0,1,2025,February,8,21,2025-02-21,0,1,2,0.0,0,SC,ESP,Online TA,TA/TO,1,0,1,A,A,0,No Deposit,9.0,,0,Group,88.0,0,1
HB-093557,City Hotel,0,292,2024,July,29,21,2024-07-21,0,2,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,90.0,0,0
HB-056937,City Hotel,1,23,2024,September,37,15,2024-09-15,1,3,2,0.0,0,BB,MOZ,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,156.5,0,0
HB-100599,City Hotel,0,36,2024,October,44,28,2024-10-28,0,2,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.0,0,2
HB-100577,City Hotel,0,95,2024,October,43,27,2024-10-27,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,104.4,0,1
HB-029750,Resort Hotel,0,99,2024,November,45,4,2024-11-04,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,37.8,0,1
HB-015604,Resort Hotel,0,160,2023,July,29,21,2023-07-21,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,2.0,,0,Contract,110.5,0,1
HB-030131,Resort Hotel,0,0,2024,November,46,14,2024-11-14,1,0,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient,80.0,0,0
HB-036807,Resort Hotel,0,18,2025,May,21,25,2025-05-25,1,3,2,0.0,0,BB,IND,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,240.0,,0,Transient,122.0,0,1
HB-030554,Resort Hotel,0,25,2024,November,47,24,2024-11-24,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,242.0,,0,Transient,61.19,0,1
HB-113274,City Hotel,0,93,2025,June,23,3,2025-06-03,1,1,2,2.0,0,BB,SWE,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,250.0,0,0
HB-033035,Resort Hotel,0,19,2025,February,7,11,2025-02-11,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-074439,City Hotel,1,304,2023,August,33,17,2023-08-17,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-098328,City Hotel,0,144,2024,September,39,23,2024-09-23,2,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,129.6,0,2
HB-031636,Resort Hotel,0,73,2024,December,1,30,2024-12-30,1,2,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,D,E,0,No Deposit,,,0,Transient,176.0,1,1
HB-087829,City Hotel,0,101,2024,April,17,26,2024-04-26,0,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,35.0,,0,Transient-Party,98.0,0,0
HB-045166,City Hotel,0,45,2023,October,42,19,2023-10-19,1,5,2,0.0,0,BB,HUN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,94.5,0,2
HB-026983,Resort Hotel,0,218,2024,August,33,13,2024-08-13,2,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,126.0,0,2
HB-028793,Resort Hotel,0,0,2024,October,41,10,2024-10-10,1,0,2,0.0,0,BB,NLD,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,66.0,1,0
HB-095279,City Hotel,0,202,2024,August,32,8,2024-08-08,3,7,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.95,0,2
HB-115973,City Hotel,0,179,2025,July,28,9,2025-07-09,2,2,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,89.1,0,1
HB-064818,City Hotel,1,72,2025,March,12,17,2025-03-17,0,1,2,2.0,0,BB,USA,Online TA,TA/TO,0,0,0,F,G,0,No Deposit,9.0,,0,Transient,160.2,0,0
HB-074877,City Hotel,1,153,2023,August,31,3,2023-08-03,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-015059,Resort Hotel,0,0,2025,May,18,2,2025-05-02,0,2,2,0.0,0,BB,ITA,Direct,Direct,1,0,1,A,D,0,No Deposit,,,0,Transient,85.0,0,1
HB-063732,City Hotel,1,235,2025,February,8,19,2025-02-19,2,1,2,0.0,0,BB,AUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.0,0,1
HB-087284,City Hotel,0,0,2024,April,16,16,2024-04-16,0,1,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,99.0,0,0
HB-043300,City Hotel,0,22,2023,September,37,17,2023-09-17,1,3,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,109.25,0,3
HB-071043,City Hotel,1,141,2025,June,26,27,2025-06-27,2,5,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,130.0,0,0
HB-044250,City Hotel,0,65,2023,October,40,2,2023-10-02,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,19.0,,59,Transient-Party,100.0,0,0
HB-039405,Resort Hotel,0,173,2025,August,33,11,2025-08-11,2,4,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,200.0,0,4
HB-093155,City Hotel,0,184,2024,July,29,16,2024-07-16,1,1,2,0.0,0,HB,ITA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,125.0,0,1
HB-012701,Resort Hotel,1,20,2025,July,28,12,2025-07-12,1,4,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,272.0,0,0
HB-077321,City Hotel,0,237,2023,September,37,14,2023-09-14,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,89.25,0,0
HB-085801,City Hotel,0,5,2024,March,12,19,2024-03-19,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,93.33,0,0
HB-112355,City Hotel,0,12,2025,May,20,16,2025-05-16,2,5,1,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient-Party,156.75,0,1
HB-067490,City Hotel,1,148,2025,May,18,4,2025-05-04,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,171.0,,0,Transient,95.0,0,0
HB-009450,Resort Hotel,1,139,2024,November,48,30,2024-11-30,0,3,2,0.0,0,BB,LUX,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,54.0,0,0
HB-087311,City Hotel,0,33,2024,April,15,14,2024-04-14,1,3,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,0
HB-056690,City Hotel,1,36,2024,September,37,10,2024-09-10,2,1,1,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,134.46,0,0
HB-021541,Resort Hotel,0,0,2024,March,9,1,2024-03-01,0,2,2,0.0,0,BB,BRA,Direct,Direct,0,0,0,F,F,1,No Deposit,,,0,Transient,65.0,1,0
HB-036739,Resort Hotel,0,388,2025,May,21,25,2025-05-25,0,3,2,0.0,0,BB,CN,Groups,TA/TO,0,0,0,E,E,0,No Deposit,96.0,,0,Transient-Party,72.0,0,1
HB-053883,City Hotel,1,179,2024,July,27,1,2024-07-01,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,65.0,0,0
HB-030277,Resort Hotel,0,41,2024,November,46,12,2024-11-12,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,55.8,0,2
HB-031503,Resort Hotel,0,81,2024,December,51,16,2024-12-16,4,10,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,89.43,0,2
HB-062310,City Hotel,1,75,2025,January,2,8,2025-01-08,2,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,D,D,0,No Deposit,330.0,,0,Transient-Party,67.0,0,2
HB-099217,City Hotel,0,110,2024,October,41,9,2024-10-09,1,0,1,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,K,1,No Deposit,234.0,,0,Transient-Party,120.0,0,0
HB-098693,City Hotel,0,91,2024,September,40,30,2024-09-30,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,3.0,,0,Transient-Party,80.0,0,0
HB-003434,Resort Hotel,1,81,2023,December,49,6,2023-12-06,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,40.5,0,2
HB-078206,City Hotel,1,52,2025,January,2,6,2025-01-06,2,2,2,0.0,0,BB,ITA,Online TA,TA/TO,1,1,1,A,A,0,No Deposit,9.0,,0,Transient,88.4,0,2
HB-024478,Resort Hotel,0,62,2024,May,21,22,2024-05-22,2,2,2,0.0,0,BB,GBR,Offline TA/TO,Direct,0,0,0,A,A,0,No Deposit,115.0,,0,Transient,45.1,0,0
HB-055731,City Hotel,1,303,2024,August,34,19,2024-08-19,2,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,78.0,0,0
HB-005228,Resort Hotel,0,191,2024,April,17,22,2024-04-22,1,2,2,0.0,0,Undefined,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,85.33,0,0
HB-084250,City Hotel,0,6,2024,February,8,20,2024-02-20,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-028386,Resort Hotel,0,198,2024,September,39,25,2024-09-25,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Contract,65.4,0,0
HB-056382,City Hotel,1,62,2024,September,36,4,2024-09-04,2,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.55,0,1
HB-087700,City Hotel,0,143,2024,April,17,24,2024-04-24,0,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,0.0,0,0
HB-115189,City Hotel,0,97,2025,June,26,26,2025-06-26,2,5,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,121.75,0,0
HB-107162,City Hotel,0,174,2025,March,10,5,2025-03-05,2,2,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,90.0,0,1
HB-037264,Resort Hotel,0,18,2025,June,24,9,2025-06-09,1,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,63.0,0,0
HB-064897,City Hotel,1,47,2025,March,12,20,2025-03-20,1,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,0
HB-103936,City Hotel,0,41,2024,December,52,27,2024-12-27,1,5,2,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,220.0,,0,Transient-Party,70.0,0,1
HB-093953,City Hotel,0,158,2024,July,30,25,2024-07-25,1,3,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.25,0,3
HB-099492,City Hotel,0,1,2024,October,41,13,2024-10-13,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,90.0,0,0
HB-081418,City Hotel,0,8,2023,December,49,9,2023-12-09,0,2,1,0.0,0,BB,FRA,Corporate,Corporate,0,0,0,A,A,1,No Deposit,91.0,,0,Transient,79.0,0,0
HB-067418,City Hotel,1,106,2025,May,18,3,2025-05-03,0,3,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,126.0,0,0
HB-005617,Resort Hotel,0,252,2024,May,19,6,2024-05-06,0,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,0.0,0,0
HB-053267,City Hotel,1,148,2024,June,25,17,2024-06-17,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,116.1,0,0
HB-073682,City Hotel,1,215,2025,August,35,30,2025-08-30,2,5,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,162.0,0,0
HB-005491,Resort Hotel,1,31,2024,April,18,30,2024-04-30,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,86.0,0,0
HB-021425,Resort Hotel,0,40,2024,February,9,27,2024-02-27,1,1,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,32.0,0,0
HB-082162,City Hotel,1,99,2024,February,8,19,2024-02-19,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,1,0,A,A,0,No Deposit,,67.0,0,Transient-Party,80.0,0,0
HB-076454,City Hotel,1,379,2023,October,44,31,2023-10-31,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-001012,Resort Hotel,1,72,2023,August,32,10,2023-08-10,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,120.6,0,0
HB-020753,Resort Hotel,0,72,2024,February,6,6,2024-02-06,2,1,2,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,73.33,0,1
HB-050133,City Hotel,1,146,2024,April,17,24,2024-04-24,2,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,26.0,,50,Transient,95.0,0,0
HB-083197,City Hotel,0,2,2024,January,4,22,2024-01-22,0,2,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.0,0,1
HB-067909,City Hotel,1,410,2025,May,19,9,2025-05-09,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-078530,City Hotel,0,0,2023,October,41,11,2023-10-11,1,0,2,0.0,0,BB,KOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-007116,Resort Hotel,1,59,2024,July,30,22,2024-07-22,0,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,160.0,0,0
HB-084504,City Hotel,0,1,2024,February,9,26,2024-02-26,0,2,1,0.0,0,BB,CN,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,83.5,0,1
HB-013219,Resort Hotel,1,20,2025,August,32,5,2025-08-05,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,160.2,0,1
HB-029619,Resort Hotel,0,93,2024,October,43,27,2024-10-27,2,4,2,0.0,0,HB,AUT,Online TA,TA/TO,0,0,0,E,E,2,No Deposit,240.0,,0,Transient,102.93,1,1
HB-073296,City Hotel,1,20,2025,August,34,18,2025-08-18,0,2,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,128.0,0,1
HB-062986,City Hotel,1,61,2025,January,4,25,2025-01-25,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,326.0,,0,Transient,80.0,0,0
HB-026600,Resort Hotel,0,121,2024,July,31,29,2024-07-29,2,6,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,221.38,0,1
HB-096569,City Hotel,0,55,2024,September,36,2,2024-09-02,1,2,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,109.8,0,1
HB-092686,City Hotel,0,131,2024,July,28,9,2024-07-09,1,1,2,1.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,22.0,,0,Transient,72.25,0,0
HB-116771,City Hotel,0,200,2025,July,30,21,2025-07-21,1,2,2,1.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.7,0,4
HB-103118,City Hotel,0,4,2024,December,50,9,2024-12-09,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,118.67,0,1
HB-061437,City Hotel,1,32,2024,December,50,10,2024-12-10,2,1,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,1
HB-092767,City Hotel,0,0,2024,July,28,10,2024-07-10,2,0,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,103.18,0,0
HB-076876,City Hotel,1,239,2023,October,42,17,2023-10-17,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-024356,Resort Hotel,0,40,2024,May,20,17,2024-05-17,0,2,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,D,0,No Deposit,248.0,,0,Transient-Party,46.0,0,0
HB-116681,City Hotel,0,423,2025,July,30,22,2025-07-22,1,1,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,95.5,0,0
HB-017999,Resort Hotel,0,0,2024,February,5,3,2024-02-03,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,8,A,A,0,No Deposit,88.0,,0,Transient,30.0,0,0
HB-101460,City Hotel,0,46,2024,November,46,11,2024-11-11,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-095395,City Hotel,0,0,2024,December,50,13,2024-12-13,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,4,A,A,0,No Deposit,,40.0,0,Transient,67.0,0,1
HB-098871,City Hotel,0,38,2024,October,40,2,2024-10-02,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-000128,Resort Hotel,0,100,2023,July,27,4,2023-07-04,1,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient-Party,73.8,1,1
HB-110952,City Hotel,0,118,2025,May,18,1,2025-05-01,1,3,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-042560,City Hotel,0,52,2023,September,36,7,2023-09-07,1,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,72.76,0,2
HB-059932,City Hotel,1,304,2024,November,44,3,2024-11-03,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,89.0,0,0
HB-067133,City Hotel,1,109,2025,April,18,28,2025-04-28,2,2,1,1.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,137.25,0,0
HB-055460,City Hotel,1,195,2024,August,33,13,2024-08-13,2,1,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,106.03,0,1
HB-013931,Resort Hotel,0,134,2025,April,15,13,2025-04-13,0,3,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,3.0,,0,Transient-Party,82.8,0,2
HB-119131,City Hotel,0,278,2025,August,35,25,2025-08-25,2,3,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,89.1,0,2
HB-112762,City Hotel,0,184,2025,May,21,25,2025-05-25,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,138.9,0,1
HB-036028,Resort Hotel,0,111,2025,April,17,24,2025-04-24,4,10,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,89.0,0,0
HB-060967,City Hotel,1,32,2024,November,48,27,2024-11-27,4,9,1,0.0,0,BB,AGO,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,1
HB-025100,Resort Hotel,0,27,2024,June,24,12,2024-06-12,2,1,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,120.0,0,1
HB-009997,Resort Hotel,1,31,2025,February,6,3,2025-02-03,2,2,1,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,58.0,0,0
HB-097932,City Hotel,0,3,2024,September,38,19,2024-09-19,1,2,1,0.0,0,BB,PRT,Aviation,Corporate,0,0,0,D,D,0,No Deposit,153.0,,0,Transient,110.0,0,0
HB-044103,City Hotel,1,30,2023,September,39,30,2023-09-30,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,121.0,0,0
HB-016375,Resort Hotel,0,62,2023,August,34,25,2023-08-25,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,H,0,No Deposit,240.0,,0,Transient,132.6,1,1
HB-061377,City Hotel,1,43,2024,December,49,8,2024-12-08,1,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,0
HB-013767,Resort Hotel,1,29,2025,August,35,29,2025-08-29,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,180.0,0,0
HB-100995,City Hotel,0,38,2024,November,45,4,2024-11-04,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-096877,City Hotel,0,97,2024,September,36,6,2024-09-06,0,4,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.1,0,1
HB-034454,Resort Hotel,0,84,2025,March,9,1,2025-03-01,6,19,2,0.0,0,HB,CN,Groups,TA/TO,0,0,0,A,A,0,No Deposit,440.0,,0,Transient-Party,55.8,0,1
HB-069942,City Hotel,1,169,2025,June,23,8,2025-06-08,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,170.0,0,0
HB-106430,City Hotel,0,3,2025,February,8,21,2025-02-21,0,4,2,2.0,0,BB,NLD,Direct,Direct,0,0,0,F,F,1,No Deposit,,,0,Transient,149.6,0,1
HB-022742,Resort Hotel,0,77,2025,March,14,31,2025-03-31,1,2,2,0.0,0,BB,PRT,Direct,TA/TO,1,0,1,E,F,1,No Deposit,250.0,,0,Transient,83.47,1,0
HB-047284,City Hotel,1,2,2024,February,7,14,2024-02-14,2,1,1,0.0,0,SC,AGO,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient-Party,79.0,0,0
HB-009307,Resort Hotel,1,33,2024,November,46,11,2024-11-11,0,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,C,1,No Deposit,240.0,,0,Transient,37.8,0,1
HB-054378,City Hotel,1,372,2024,July,28,14,2024-07-14,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-108549,City Hotel,0,158,2025,March,13,27,2025-03-27,1,1,2,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,95.0,0,1
HB-071812,City Hotel,1,253,2025,July,28,13,2025-07-13,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,0
HB-108023,City Hotel,0,59,2025,March,12,20,2025-03-20,1,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,106.2,0,2
HB-001642,Resort Hotel,0,90,2023,September,36,6,2023-09-06,4,7,2,2.0,0,BB,IRL,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,139.18,0,0
HB-040262,City Hotel,1,12,2023,July,29,18,2023-07-18,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-075618,City Hotel,1,281,2023,July,30,25,2023-07-25,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-001686,Resort Hotel,0,130,2023,September,36,9,2023-09-09,2,4,1,0.0,0,BB,LVA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,77.7,1,2
HB-086833,City Hotel,0,115,2024,April,15,8,2024-04-08,0,2,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,34,Transient-Party,65.0,0,1
HB-037798,Resort Hotel,0,251,2025,June,26,26,2025-06-26,1,3,2,0.0,0,HB,CN,Groups,TA/TO,0,0,0,D,E,0,No Deposit,96.0,,0,Transient-Party,106.0,0,0
HB-006658,Resort Hotel,0,253,2024,June,25,22,2024-06-22,0,3,2,0.0,0,HB,POL,Groups,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient-Party,92.0,0,0
HB-098412,City Hotel,0,3,2024,September,39,25,2024-09-25,2,2,1,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,A,0,No Deposit,,45.0,0,Transient,0.0,0,0
HB-061386,City Hotel,1,91,2024,December,50,9,2024-12-09,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,0
HB-009806,Resort Hotel,1,6,2025,January,1,4,2025-01-04,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,39.0,0,0
HB-058954,City Hotel,1,68,2024,October,42,18,2024-10-18,0,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,132.3,0,2
HB-031470,Resort Hotel,0,120,2024,December,51,22,2024-12-22,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,47.8,0,4
HB-105435,City Hotel,0,24,2025,February,6,5,2025-02-05,2,1,1,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,1,No Deposit,,407.0,0,Transient-Party,75.0,0,0
HB-052766,City Hotel,1,69,2024,June,24,12,2024-06-12,2,4,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,120.0,0,0
HB-101727,City Hotel,0,190,2024,November,46,14,2024-11-14,1,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,81.9,0,1
HB-063127,City Hotel,1,56,2025,February,5,1,2025-02-01,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,60.0,0,0
HB-027609,Resort Hotel,0,212,2024,August,34,21,2024-08-21,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Contract,57.8,0,1
HB-071220,City Hotel,1,162,2025,June,26,29,2025-06-29,2,4,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,155.4,0,1
HB-034362,Resort Hotel,0,16,2025,March,12,19,2025-03-19,2,2,2,0.0,0,HB,DEU,Direct,Direct,0,0,0,E,E,1,No Deposit,,,0,Transient-Party,80.0,0,0
HB-028693,Resort Hotel,0,11,2024,October,41,9,2024-10-09,1,0,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,405.0,0,Transient-Party,50.0,0,1
HB-021916,Resort Hotel,0,1,2024,March,11,12,2024-03-12,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,F,0,No Deposit,240.0,,0,Transient,84.0,1,0
HB-021169,Resort Hotel,0,7,2024,February,7,17,2024-02-17,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient-Party,48.0,0,1
HB-096971,City Hotel,0,183,2024,September,36,8,2024-09-08,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,44.0,,0,Transient-Party,110.0,0,1
HB-073823,City Hotel,1,300,2023,August,32,13,2023-08-13,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-005988,Resort Hotel,1,40,2024,May,20,18,2024-05-18,0,2,1,0.0,0,BB,PRT,Groups,Corporate,0,0,0,A,A,0,Non Refund,,,0,Transient,55.0,0,0
HB-044357,City Hotel,0,61,2023,October,40,4,2023-10-04,2,0,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,91.0,0,0
HB-072152,City Hotel,1,423,2025,July,30,22,2025-07-22,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,80.0,0,0
HB-051928,City Hotel,0,316,2024,May,21,26,2024-05-26,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,110.0,0,0
HB-012415,Resort Hotel,1,267,2025,June,26,28,2025-06-28,0,4,2,0.0,0,HB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,112.22,0,0
HB-092451,City Hotel,0,104,2024,July,27,3,2024-07-03,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.3,0,1
HB-048269,City Hotel,1,393,2024,March,12,19,2024-03-19,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-115065,City Hotel,0,107,2025,June,26,29,2025-06-29,0,2,2,0.0,0,HB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,178.2,1,0
HB-042745,City Hotel,0,71,2023,September,36,9,2023-09-09,0,3,1,0.0,0,BB,FRA,Corporate,Corporate,0,0,0,A,D,1,No Deposit,,68.0,0,Transient-Party,90.0,0,0
HB-060121,City Hotel,1,95,2024,November,45,5,2024-11-05,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,75.0,0,0
HB-062754,City Hotel,1,294,2025,January,4,21,2025-01-21,2,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,77.35,0,0
HB-086542,City Hotel,0,56,2024,March,13,30,2024-03-30,2,4,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,101.72,0,1
HB-077980,City Hotel,1,45,2023,October,43,29,2023-10-29,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,3.0,,0,Transient,70.0,0,0
HB-055980,City Hotel,1,31,2024,August,35,26,2024-08-26,0,1,1,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.5,0,1
HB-084219,City Hotel,0,41,2024,February,7,18,2024-02-18,0,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient-Party,72.38,0,0
HB-094013,City Hotel,0,172,2024,July,30,22,2024-07-22,2,6,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,70.85,0,1
HB-063236,City Hotel,1,32,2025,February,6,3,2025-02-03,0,1,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,0
HB-044964,City Hotel,1,102,2023,October,42,16,2023-10-16,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-061705,City Hotel,1,199,2024,December,52,23,2024-12-23,2,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,1
HB-110403,City Hotel,0,204,2025,April,17,23,2025-04-23,2,2,2,2.0,0,BB,CHE,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,210.0,0,4
HB-056047,City Hotel,1,56,2024,August,35,27,2024-08-27,1,1,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,136.35,0,1
HB-092715,City Hotel,0,176,2024,July,28,8,2024-07-08,1,2,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient-Party,85.5,0,0
HB-052992,City Hotel,1,8,2024,June,24,15,2024-06-15,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,156.0,0,0
HB-033793,Resort Hotel,0,7,2025,March,10,3,2025-03-03,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,467.0,,0,Transient,57.6,0,0
HB-022867,Resort Hotel,0,17,2024,April,14,7,2024-04-07,0,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,53.1,0,0
HB-087634,City Hotel,0,46,2024,April,16,21,2024-04-21,0,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.3,0,1
HB-100698,City Hotel,0,0,2024,October,44,29,2024-10-29,1,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,117.04,0,0
HB-017680,Resort Hotel,0,283,2023,October,41,12,2023-10-12,2,5,1,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,A,0,No Deposit,273.0,,0,Transient-Party,41.98,0,0
HB-026024,Resort Hotel,0,39,2024,July,29,17,2024-07-17,2,0,2,2.0,0,BB,BRA,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,271.0,0,0
HB-074370,City Hotel,1,276,2023,July,29,20,2023-07-20,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Contract,62.0,0,0
HB-081872,City Hotel,1,178,2024,April,17,28,2024-04-28,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,46,Transient,110.0,0,0
HB-093791,City Hotel,0,172,2024,July,30,23,2024-07-23,2,2,2,2.0,0,BB,BEL,Direct,Direct,0,0,0,G,G,0,No Deposit,14.0,,0,Transient,222.35,1,0
HB-071857,City Hotel,1,174,2025,July,29,14,2025-07-14,0,2,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,116.1,0,0
HB-036033,Resort Hotel,0,42,2025,May,18,1,2025-05-01,2,5,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,130.0,0,0
HB-050560,City Hotel,0,123,2024,May,18,4,2024-05-04,0,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,71.6,0,0
HB-001079,Resort Hotel,1,72,2023,August,32,13,2023-08-13,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,147.0,,0,Transient,114.14,0,1
HB-117217,City Hotel,0,468,2025,July,31,29,2025-07-29,2,1,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,1
HB-115609,City Hotel,0,80,2025,July,28,7,2025-07-07,0,1,2,0.0,0,BB,DNK,Direct,Direct,0,0,0,A,C,0,No Deposit,14.0,,0,Transient-Party,108.0,0,1
HB-009336,Resort Hotel,1,124,2024,November,46,14,2024-11-14,1,0,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,241.0,,0,Transient,57.28,0,0
HB-056793,City Hotel,1,41,2024,September,37,14,2024-09-14,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,86.0,,0,Transient-Party,130.0,0,0
HB-039739,Resort Hotel,0,129,2025,August,34,20,2025-08-20,2,5,2,1.0,0,FB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,181.0,,0,Transient,227.06,0,2
HB-070688,City Hotel,1,32,2025,June,25,21,2025-06-21,0,2,2,0.0,0,BB,KOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,0
HB-022141,Resort Hotel,0,4,2024,March,11,12,2024-03-12,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,2.0,,0,Contract,47.0,0,0
HB-048510,City Hotel,1,85,2024,March,12,24,2024-03-24,2,3,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,F,F,2,No Deposit,9.0,,0,Transient-Party,157.25,0,0
HB-113068,City Hotel,0,20,2025,May,22,30,2025-05-30,0,3,1,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,142.33,0,1
HB-059845,City Hotel,1,304,2024,November,44,3,2024-11-03,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,89.0,0,0
HB-046772,City Hotel,0,151,2024,January,3,19,2024-01-19,0,2,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,4,No Deposit,19.0,,63,Transient-Party,86.5,0,0
HB-069129,City Hotel,1,30,2025,May,22,26,2025-05-26,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,160.0,0,1
HB-078790,City Hotel,1,28,2023,November,44,2,2023-11-02,1,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Contract,90.95,0,0
HB-091588,City Hotel,0,5,2024,June,25,22,2024-06-22,0,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,122.0,0,1
HB-013984,Resort Hotel,0,4,2025,May,19,8,2025-05-08,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,5,A,D,0,No Deposit,,62.0,0,Transient,45.0,0,0
HB-068371,City Hotel,1,394,2025,May,20,16,2025-05-16,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-015783,Resort Hotel,0,15,2023,July,31,31,2023-07-31,0,2,2,2.0,0,BB,CHN,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,248.0,1,2
HB-091064,City Hotel,0,2,2024,June,24,13,2024-06-13,1,2,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,145.67,0,2
HB-006445,Resort Hotel,1,227,2024,June,24,11,2024-06-11,4,6,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,72.0,0,2
HB-026693,Resort Hotel,0,12,2024,August,31,4,2024-08-04,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,236.0,0,0
HB-109101,City Hotel,0,12,2025,April,14,5,2025-04-05,0,2,1,0.0,0,BB,POL,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,129.0,0,0
HB-033042,Resort Hotel,0,17,2025,February,7,10,2025-02-10,1,2,2,0.0,0,HB,POL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,69.3,0,1
HB-092477,City Hotel,0,139,2024,July,27,4,2024-07-04,1,2,2,2.0,0,HB,SWE,Online TA,TA/TO,0,0,0,F,G,1,No Deposit,9.0,,0,Transient,228.6,0,2
HB-017541,Resort Hotel,0,56,2023,October,41,12,2023-10-12,1,0,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,42.3,0,2
HB-080856,City Hotel,0,1,2023,December,50,15,2023-12-15,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,2,A,A,0,No Deposit,,148.0,0,Transient,75.0,0,0
HB-005691,Resort Hotel,1,203,2024,May,19,10,2024-05-10,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,248.0,,0,Transient-Party,46.0,0,0
HB-069161,City Hotel,1,168,2025,May,22,26,2025-05-26,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,43.0,0,Transient,140.0,0,0
HB-030863,Resort Hotel,0,32,2024,November,47,23,2024-11-23,4,10,2,0.0,1,Undefined,FRA,Offline TA/TO,TA/TO,0,0,0,C,C,2,No Deposit,464.0,,0,Transient,96.0,0,1
HB-004128,Resort Hotel,1,0,2024,February,7,15,2024-02-15,0,0,0,0.0,0,SC,,Offline TA/TO,TA/TO,0,0,0,P,P,0,No Deposit,,383.0,0,Transient,0.0,0,0
HB-014364,Resort Hotel,1,0,2024,June,23,5,2024-06-05,1,0,1,0.0,0,BB,,Direct,Corporate,0,0,1,A,A,1,No Deposit,,,0,Transient,90.0,0,0
HB-063233,City Hotel,1,91,2025,February,6,3,2025-02-03,0,1,2,0.0,0,SC,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,1
HB-049425,City Hotel,1,11,2024,April,15,13,2024-04-13,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,143.33,0,0
HB-080575,City Hotel,0,54,2023,November,46,16,2023-11-16,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Transient,69.0,0,0
HB-049781,City Hotel,1,103,2024,April,16,19,2024-04-19,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,0,Transient,115.0,0,0
HB-022004,Resort Hotel,0,0,2024,March,10,10,2024-03-10,2,4,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,96.0,,0,Transient,29.0,0,0
HB-068558,City Hotel,1,175,2025,May,21,19,2025-05-19,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,44.0,,0,Transient,90.0,0,0
HB-083578,City Hotel,0,129,2024,February,5,4,2024-02-04,0,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Group,62.0,0,0
HB-086282,City Hotel,0,2,2024,March,13,28,2024-03-28,1,2,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,7.0,,0,Transient,148.37,0,2
HB-077447,City Hotel,1,100,2023,December,52,25,2023-12-25,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,8.0,,0,Transient,85.0,0,2
HB-073788,City Hotel,1,279,2023,July,29,23,2023-07-23,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-073288,City Hotel,1,213,2025,August,34,18,2025-08-18,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,9.0,,0,Transient,154.8,0,1
HB-034286,Resort Hotel,0,26,2025,March,11,14,2025-03-14,0,5,2,0.0,0,HB,DEU,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient-Party,80.0,0,0
HB-012135,Resort Hotel,1,131,2025,June,24,15,2025-06-15,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,110.0,0,0
HB-087740,City Hotel,0,38,2024,April,16,21,2024-04-21,1,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,118.8,0,1
HB-019123,Resort Hotel,0,1,2023,December,49,5,2023-12-05,2,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-083827,City Hotel,0,1,2024,February,7,13,2024-02-13,0,1,1,0.0,0,BB,ITA,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,144.0,0,Transient-Party,79.0,0,0
HB-026122,Resort Hotel,0,97,2024,July,29,21,2024-07-21,0,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,E,E,6,No Deposit,240.0,,0,Transient,230.0,0,2
HB-053976,City Hotel,1,38,2024,July,27,4,2024-07-04,1,0,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.9,0,0
HB-013736,Resort Hotel,1,63,2025,August,35,28,2025-08-28,1,2,2,0.0,0,HB,GIB,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,236.0,0,2
HB-077771,City Hotel,0,6,2023,September,38,20,2023-09-20,2,5,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,138.57,0,1
HB-072731,City Hotel,1,300,2025,August,32,4,2025-08-04,1,2,3,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,109.2,0,2
HB-001455,Resort Hotel,0,83,2023,August,35,30,2023-08-30,2,4,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,112.33,1,1
HB-025394,Resort Hotel,0,192,2024,June,25,21,2024-06-21,0,5,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,68.0,0,0
HB-033930,Resort Hotel,0,5,2025,March,10,6,2025-03-06,1,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient,30.0,0,0
HB-014343,Resort Hotel,0,0,2024,February,5,3,2024-02-03,0,1,1,0.0,0,BB,,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,39.0,0,1
HB-112425,City Hotel,0,11,2025,May,21,21,2025-05-21,2,1,2,0.0,0,BB,USA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,120.0,0,0
HB-105187,City Hotel,0,7,2025,January,5,29,2025-01-29,2,2,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,54.71,0,0
HB-034155,Resort Hotel,0,176,2025,March,11,12,2025-03-12,2,1,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,D,D,1,No Deposit,,,0,Transient-Party,40.5,0,1
HB-018317,Resort Hotel,0,31,2023,November,44,2,2023-11-02,5,10,2,0.0,0,BB,AUS,Corporate,Corporate,0,0,0,E,E,5,No Deposit,185.0,281.0,0,Transient-Party,52.2,0,0
HB-113910,City Hotel,0,182,2025,June,24,13,2025-06-13,0,1,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,144.38,0,0
HB-012168,Resort Hotel,1,33,2025,June,25,16,2025-06-16,2,2,2,2.0,0,HB,AUS,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,273.0,0,0
HB-082434,City Hotel,0,21,2023,December,52,25,2023-12-25,2,3,2,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient-Party,58.0,0,1
HB-070065,City Hotel,1,178,2025,June,24,9,2025-06-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,86.0,,0,Transient,130.0,0,0
HB-045738,City Hotel,0,98,2023,November,47,23,2023-11-23,1,2,1,0.0,0,BB,IRL,Groups,TA/TO,0,0,0,A,D,0,No Deposit,37.0,,0,Transient-Party,70.0,0,0
HB-045089,City Hotel,0,102,2023,October,42,16,2023-10-16,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-021715,Resort Hotel,0,1,2024,March,9,1,2024-03-01,2,6,1,0.0,0,BB,FIN,Corporate,Corporate,0,0,0,E,E,0,No Deposit,,,0,Transient,39.5,0,0
HB-020615,Resort Hotel,0,0,2024,February,5,4,2024-02-04,0,1,2,0.0,0,BB,NLD,Direct,Direct,0,0,0,A,E,0,No Deposit,,,0,Transient,55.0,0,0
HB-102977,City Hotel,0,49,2024,December,49,7,2024-12-07,0,4,2,0.0,0,HB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,94.51,0,1
HB-023817,Resort Hotel,0,152,2024,May,18,2,2024-05-02,1,2,2,0.0,0,BB,ARG,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,336.0,,0,Transient,41.4,0,1
HB-061415,City Hotel,1,79,2024,December,50,9,2024-12-09,1,2,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,126.0,0,2
HB-012811,Resort Hotel,1,159,2025,July,29,17,2025-07-17,3,6,2,0.0,0,HB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,192.0,0,0
HB-021673,Resort Hotel,0,10,2025,February,9,26,2025-02-26,2,4,2,0.0,0,BB,PRT,Direct,Direct,1,0,2,F,F,0,No Deposit,250.0,,0,Transient,72.83,0,2
HB-093614,City Hotel,0,226,2024,July,30,22,2024-07-22,0,2,2,0.0,0,BB,USA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,96,Transient-Party,76.5,0,1
HB-042388,City Hotel,0,32,2023,September,36,5,2023-09-05,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Contract,94.5,0,3
HB-069552,City Hotel,1,114,2025,June,22,1,2025-06-01,2,3,2,1.0,0,HB,HRV,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,200.7,0,0
HB-110212,City Hotel,0,15,2025,April,17,21,2025-04-21,1,2,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,126.0,0,1
HB-068747,City Hotel,1,75,2025,May,21,20,2025-05-20,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,1
HB-079401,City Hotel,0,37,2023,October,43,23,2023-10-23,2,2,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,85.5,0,0
HB-021955,Resort Hotel,0,52,2024,March,10,6,2024-03-06,3,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,28.1,0,0
HB-029961,Resort Hotel,0,150,2024,November,45,8,2024-11-08,0,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,37.8,0,2
HB-118449,City Hotel,0,13,2025,August,33,17,2025-08-17,0,3,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,1
HB-074233,City Hotel,1,278,2023,July,29,22,2023-07-22,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Contract,62.0,0,0
HB-107531,City Hotel,0,49,2025,March,10,9,2025-03-09,2,3,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,79.2,0,0
HB-061258,City Hotel,1,102,2024,December,49,6,2024-12-06,0,2,1,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,B,1,No Deposit,9.0,,0,Transient,86.4,0,2
HB-117952,City Hotel,0,4,2025,August,32,10,2025-08-10,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,199.0,0,1
HB-087557,City Hotel,0,95,2024,April,16,20,2024-04-20,0,2,2,0.0,0,HB,AUT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,35.0,,0,Transient-Party,98.0,0,0
HB-097007,City Hotel,0,54,2024,September,37,9,2024-09-09,0,2,2,1.0,0,SC,KOR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,42.0,,0,Transient,121.68,0,1
HB-083361,City Hotel,0,1,2024,January,4,27,2024-01-27,0,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,10.0,,0,Transient,71.7,0,0
HB-091107,City Hotel,0,256,2024,June,24,15,2024-06-15,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-070952,City Hotel,1,199,2025,June,26,26,2025-06-26,1,1,2,2.0,0,HB,POL,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,9.0,,0,Transient,189.0,0,0
HB-046999,City Hotel,1,30,2024,February,5,2,2024-02-02,1,5,2,2.0,0,BB,BRA,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient,139.05,0,0
HB-016861,Resort Hotel,0,254,2023,September,37,12,2023-09-12,2,2,2,0.0,0,BB,CN,Groups,TA/TO,0,0,0,A,C,0,No Deposit,15.0,,0,Transient-Party,36.0,0,0
HB-115838,City Hotel,0,168,2025,July,28,9,2025-07-09,2,1,3,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,86.0,,0,Transient,121.68,0,0
HB-005478,Resort Hotel,1,78,2024,April,18,29,2024-04-29,2,7,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,3,No Deposit,95.0,,0,Transient-Party,40.0,0,0
HB-030237,Resort Hotel,0,0,2024,November,46,14,2024-11-14,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,F,0,No Deposit,240.0,,0,Transient,85.0,0,2
HB-038893,Resort Hotel,0,176,2025,July,30,26,2025-07-26,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,6.0,,0,Transient,152.1,0,0
HB-015542,Resort Hotel,0,56,2023,July,29,21,2023-07-21,0,4,2,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,A,E,1,No Deposit,240.0,,0,Transient,132.3,0,0
HB-053224,City Hotel,1,350,2024,June,25,17,2024-06-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,140.0,0,0
HB-114348,City Hotel,0,52,2025,June,25,17,2025-06-17,2,1,2,0.0,0,BB,AUT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,439.0,0,Transient,126.0,0,0
HB-113085,City Hotel,0,0,2025,June,22,1,2025-06-01,0,1,2,2.0,0,SC,RUS,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,126.0,0,1
HB-087265,City Hotel,0,7,2024,April,16,15,2024-04-15,0,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.0,0,1
HB-117561,City Hotel,0,39,2025,August,32,4,2025-08-04,0,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,0
HB-018268,Resort Hotel,0,37,2023,November,45,8,2023-11-08,2,5,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,1,No Deposit,185.0,281.0,0,Transient-Party,36.0,0,0
HB-056745,City Hotel,1,99,2024,September,37,12,2024-09-12,1,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.1,0,0
HB-075274,City Hotel,1,299,2023,August,32,12,2023-08-12,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-090441,City Hotel,0,2,2024,June,23,4,2024-06-04,1,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.0,0,1
HB-111014,City Hotel,0,2,2025,May,18,4,2025-05-04,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,77.0,,0,Transient,125.0,0,0
HB-095550,City Hotel,0,0,2024,August,34,20,2024-08-20,0,1,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,168.3,0,2
HB-116694,City Hotel,0,423,2025,July,30,22,2025-07-22,1,1,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,122.4,0,1
HB-101578,City Hotel,0,180,2024,November,46,13,2024-11-13,1,0,1,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,51.28,0,2
HB-108403,City Hotel,0,78,2025,March,12,21,2025-03-21,0,5,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,97.2,0,2
HB-112096,City Hotel,0,102,2025,May,20,18,2025-05-18,0,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,112.5,0,0
HB-005628,Resort Hotel,0,354,2024,May,19,6,2024-05-06,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Transient,37.56,0,0
HB-073696,City Hotel,1,131,2025,August,35,31,2025-08-31,0,3,2,0.0,0,BB,BLR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,165.0,0,0
HB-021767,Resort Hotel,0,6,2024,April,15,14,2024-04-14,0,1,1,0.0,0,BB,PRT,Direct,Direct,1,0,1,A,A,1,No Deposit,,,0,Transient,50.0,0,0
HB-087564,City Hotel,0,25,2024,April,16,17,2024-04-17,2,3,2,0.0,0,BB,UKR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.4,0,1
HB-007237,Resort Hotel,1,46,2024,July,31,30,2024-07-30,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,179.0,0,0
HB-071666,City Hotel,1,107,2025,July,28,9,2025-07-09,2,2,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,136.8,0,0
HB-064207,City Hotel,1,28,2025,March,9,2,2025-03-02,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,95.0,0,0
HB-052198,City Hotel,1,20,2024,June,22,2,2024-06-02,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,121.0,0,0
HB-078564,City Hotel,0,0,2024,January,3,20,2024-01-20,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,2,A,A,0,No Deposit,,40.0,0,Transient-Party,65.0,0,1
HB-098455,City Hotel,0,35,2024,September,39,27,2024-09-27,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,83.0,,0,Transient,108.4,0,0
HB-021465,Resort Hotel,0,12,2024,February,9,27,2024-02-27,1,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,2
HB-053157,City Hotel,1,10,2024,June,24,16,2024-06-16,0,3,2,0.0,0,SC,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,129.0,0,1
HB-095779,City Hotel,0,24,2024,August,34,19,2024-08-19,2,3,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,21.0,,0,Transient-Party,70.0,0,0
HB-013799,Resort Hotel,1,6,2025,August,35,31,2025-08-31,1,3,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,207.5,0,0
HB-102570,City Hotel,0,21,2024,November,48,30,2024-11-30,0,2,2,0.0,0,BB,POL,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,81.0,0,0
HB-096124,City Hotel,0,122,2024,August,34,21,2024-08-21,3,5,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,52.0,,0,Transient-Party,81.26,1,2
HB-066177,City Hotel,1,96,2025,April,16,15,2025-04-15,2,1,2,2.0,0,HB,DEU,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,258.0,0,0
HB-100145,City Hotel,0,220,2024,October,42,20,2024-10-20,1,3,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,80.75,0,1
HB-025730,Resort Hotel,0,89,2024,July,27,3,2024-07-03,2,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,64.8,0,1
HB-029432,Resort Hotel,0,5,2024,October,43,26,2024-10-26,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,73.5,1,1
HB-018905,Resort Hotel,0,9,2023,November,48,30,2023-11-30,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,46.4,0,1
HB-001480,Resort Hotel,1,159,2023,August,35,31,2023-08-31,1,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,101.44,0,0
HB-094779,City Hotel,0,10,2024,August,32,8,2024-08-08,1,1,2,2.0,0,BB,CHN,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,207.9,0,1
HB-091669,City Hotel,0,39,2024,June,25,21,2024-06-21,0,3,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,94.5,0,1
HB-066440,City Hotel,1,67,2025,April,16,20,2025-04-20,0,3,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,135.0,0,0
HB-117063,City Hotel,0,28,2025,July,30,26,2025-07-26,0,3,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,0
HB-112970,City Hotel,0,119,2025,May,22,29,2025-05-29,1,1,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.0,0,0
HB-054808,City Hotel,1,391,2024,July,30,27,2024-07-27,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,65.0,0,0
HB-056217,City Hotel,1,419,2024,September,35,1,2024-09-01,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-022781,Resort Hotel,0,0,2024,April,14,5,2024-04-05,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,56.0,0,0
HB-036330,Resort Hotel,0,5,2025,May,20,13,2025-05-13,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,196.0,,0,Transient,89.0,0,0
HB-064397,City Hotel,1,182,2025,March,10,8,2025-03-08,1,4,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,104.0,0,1
HB-077665,City Hotel,0,12,2023,September,38,22,2023-09-22,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,85.0,0,1
HB-086224,City Hotel,0,122,2024,March,13,27,2024-03-27,2,1,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,26.0,,0,Transient-Party,86.0,0,0
HB-113211,City Hotel,0,181,2025,June,23,2,2025-06-02,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,153.0,0,2
HB-116249,City Hotel,0,178,2025,July,28,10,2025-07-10,2,5,2,0.0,0,HB,SWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,112.58,0,1
HB-008264,Resort Hotel,0,328,2024,September,38,20,2024-09-20,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,143.0,,0,Transient,51.85,0,1
HB-074579,City Hotel,1,353,2023,October,40,5,2023-10-05,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-038769,Resort Hotel,0,15,2025,July,30,23,2025-07-23,2,4,2,1.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,253.0,0,0
HB-096266,City Hotel,0,61,2024,August,35,28,2024-08-28,2,1,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,78.25,0,0
HB-059588,City Hotel,1,109,2024,October,44,29,2024-10-29,2,1,2,2.0,0,BB,BRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,159.9,0,0
HB-016691,Resort Hotel,0,199,2023,August,35,28,2023-08-28,4,7,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,115.0,,0,Contract,87.75,0,1
HB-119339,City Hotel,0,137,2025,August,35,29,2025-08-29,0,5,1,0.0,0,SC,JPN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,96.8,0,1
HB-061018,City Hotel,1,42,2024,November,48,29,2024-11-29,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,348.0,0,Transient,90.0,0,0
HB-115448,City Hotel,0,405,2025,July,27,4,2025-07-04,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,114.4,0,0
HB-090474,City Hotel,0,220,2024,June,23,4,2024-06-04,2,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,0.0,0,0
HB-116735,City Hotel,0,423,2025,July,30,22,2025-07-22,1,1,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,95.5,0,0
HB-029590,Resort Hotel,0,0,2024,November,44,1,2024-11-01,0,1,2,0.0,0,BB,PRT,Direct,Direct,1,0,0,A,A,0,No Deposit,,,0,Transient,55.0,1,0
HB-046823,City Hotel,0,151,2024,January,3,19,2024-01-19,0,3,1,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,3,No Deposit,19.0,,63,Transient-Party,71.0,0,0
HB-106137,City Hotel,0,2,2025,February,8,18,2025-02-18,2,2,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,59.4,0,0
HB-111218,City Hotel,0,51,2025,May,19,6,2025-05-06,1,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,134.1,0,0
HB-064805,City Hotel,1,86,2025,March,11,16,2025-03-16,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.2,0,1
HB-051310,City Hotel,0,323,2024,May,20,17,2024-05-17,0,4,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,112.0,0,1
HB-032749,Resort Hotel,0,1,2025,February,5,1,2025-02-01,0,3,1,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,31.21,0,1
HB-111317,City Hotel,0,144,2025,May,19,6,2025-05-06,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,52.0,,0,Transient-Party,90.0,0,1
HB-033623,Resort Hotel,0,22,2025,February,9,25,2025-02-25,2,1,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,314.0,,0,Transient,71.44,1,2
HB-068980,City Hotel,1,357,2025,May,21,24,2025-05-24,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,0
HB-112104,City Hotel,0,0,2025,May,21,19,2025-05-19,0,1,1,0.0,0,BB,PRT,Aviation,Corporate,0,0,0,A,A,1,No Deposit,153.0,,0,Group,110.0,0,0
HB-075587,City Hotel,0,257,2023,July,26,1,2023-07-01,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,101.5,0,0
HB-000343,Resort Hotel,0,50,2023,July,28,12,2023-07-12,2,3,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,156.0,,0,Contract,123.0,0,0
HB-053801,City Hotel,1,358,2024,June,26,30,2024-06-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-001429,Resort Hotel,1,59,2023,August,35,29,2023-08-29,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,164.0,0,2
HB-101919,City Hotel,0,44,2024,November,47,18,2024-11-18,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,83.39,0,1
HB-090734,City Hotel,0,45,2024,June,23,8,2024-06-08,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,128.4,0,1
HB-017288,Resort Hotel,0,42,2023,September,39,28,2023-09-28,1,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,75.8,0,0
HB-075084,City Hotel,1,283,2023,July,30,27,2023-07-27,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-065186,City Hotel,1,16,2025,March,13,27,2025-03-27,1,0,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,128.0,0,0
HB-078704,City Hotel,0,0,2024,March,10,9,2024-03-09,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,14,A,A,0,No Deposit,,40.0,0,Transient-Party,65.0,0,1
HB-032518,Resort Hotel,0,88,2025,January,4,22,2025-01-22,2,5,2,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,D,D,0,No Deposit,273.0,,0,Transient-Party,66.8,0,0
HB-115467,City Hotel,0,405,2025,July,27,4,2025-07-04,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,114.4,0,0
HB-051592,City Hotel,1,36,2024,May,21,22,2024-05-22,2,0,2,0.0,0,SC,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,92.88,0,0
HB-009031,Resort Hotel,1,29,2024,October,43,24,2024-10-24,1,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,60.0,0,1
HB-092182,City Hotel,0,132,2024,June,26,28,2024-06-28,0,4,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.95,0,0
HB-056909,City Hotel,1,317,2024,September,37,15,2024-09-15,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,120.0,0,0
HB-015114,Resort Hotel,1,214,2023,October,40,3,2023-10-03,1,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,208.0,,0,Transient,34.0,0,0
HB-091926,City Hotel,0,190,2024,June,25,22,2024-06-22,1,4,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,G,G,2,No Deposit,34.0,,0,Transient-Party,110.0,0,0
HB-006098,Resort Hotel,0,257,2024,May,21,25,2024-05-25,0,2,2,2.0,0,BB,DEU,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,101.7,0,0
HB-035665,Resort Hotel,0,276,2025,April,17,22,2025-04-22,2,5,2,0.0,0,Undefined,SWE,Groups,TA/TO,0,0,0,A,A,0,No Deposit,527.0,,0,Transient-Party,104.0,0,0
HB-096870,City Hotel,0,52,2024,September,36,7,2024-09-07,0,2,3,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,149.4,0,2
HB-049439,City Hotel,1,13,2024,April,15,14,2024-04-14,0,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,83.0,,0,Transient,131.6,0,0
HB-015375,Resort Hotel,0,128,2023,July,27,8,2023-07-08,0,3,1,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,129.0,1,1
HB-019422,Resort Hotel,0,20,2023,December,50,17,2023-12-17,0,2,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,58.0,0,0
HB-102772,City Hotel,0,220,2024,November,48,29,2024-11-29,2,5,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,73.95,0,2
HB-113010,City Hotel,0,38,2025,May,22,31,2025-05-31,0,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,128.0,0,1
HB-117065,City Hotel,0,171,2025,July,31,28,2025-07-28,0,1,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,168.0,,0,Transient,80.1,0,0
HB-095650,City Hotel,0,138,2024,August,33,17,2024-08-17,1,4,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,141.3,0,2
HB-034529,Resort Hotel,0,15,2025,March,13,27,2025-03-27,1,0,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient-Party,90.0,0,0
HB-015701,Resort Hotel,1,245,2023,September,39,25,2023-09-25,0,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,248.0,,0,Transient,80.0,0,0
HB-115149,City Hotel,0,139,2025,June,26,27,2025-06-27,0,5,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,160.02,0,0
HB-002861,Resort Hotel,0,5,2023,November,44,3,2023-11-03,0,1,1,0.0,0,BB,FRA,Corporate,Corporate,0,0,0,A,E,0,No Deposit,,,0,Transient,46.0,1,0
HB-001378,Resort Hotel,1,62,2023,August,34,27,2023-08-27,2,3,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,172.6,0,1
HB-048525,City Hotel,0,80,2024,March,13,25,2024-03-25,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient-Party,85.5,0,2
HB-028749,Resort Hotel,0,131,2024,October,41,9,2024-10-09,2,0,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,55.0,0,1
HB-001850,Resort Hotel,1,76,2023,September,37,17,2023-09-17,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,84.71,0,1
HB-044700,City Hotel,0,66,2023,October,41,9,2023-10-09,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,75.0,0,0
HB-046855,City Hotel,0,18,2024,January,3,21,2024-01-21,0,2,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient-Party,75.0,0,0
HB-066889,City Hotel,1,156,2025,April,17,26,2025-04-26,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,100.0,0,0
HB-047882,City Hotel,0,76,2024,March,10,7,2024-03-07,1,3,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,65.75,0,1
HB-000378,Resort Hotel,0,72,2023,July,28,13,2023-07-13,1,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,98.5,0,2
HB-065367,City Hotel,1,208,2025,April,14,1,2025-04-01,2,1,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,2
HB-074923,City Hotel,1,136,2023,July,29,17,2023-07-17,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient,60.0,0,0
HB-058115,City Hotel,1,454,2024,October,40,6,2024-10-06,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-038739,Resort Hotel,0,194,2025,July,29,17,2025-07-17,3,8,2,1.0,0,HB,CHE,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,189.85,0,0
HB-107255,City Hotel,0,27,2025,March,10,5,2025-03-05,2,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,0
HB-027092,Resort Hotel,0,14,2024,August,33,15,2024-08-15,1,4,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,265.0,0,2
HB-031719,Resort Hotel,0,45,2025,January,1,2,2025-01-02,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,42.0,0,1
HB-050940,City Hotel,1,309,2024,May,19,12,2024-05-12,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-033818,Resort Hotel,0,120,2025,February,9,28,2025-02-28,0,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,240.0,,0,Transient,62.8,0,1
HB-090948,City Hotel,0,1,2024,June,24,13,2024-06-13,1,0,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,1,1
HB-013749,Resort Hotel,1,112,2025,August,35,28,2025-08-28,1,5,3,0.0,0,HB,ESP,Direct,Direct,0,0,0,D,D,1,No Deposit,250.0,,0,Transient,312.0,0,3
HB-073060,City Hotel,1,257,2025,August,33,13,2025-08-13,2,2,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,180.0,0,1
HB-071275,City Hotel,1,144,2025,June,27,30,2025-06-30,2,5,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,117.51,0,0
HB-112722,City Hotel,0,293,2025,May,21,25,2025-05-25,0,3,3,0.0,0,BB,DNK,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,159.3,0,1
HB-047368,City Hotel,1,44,2024,February,7,17,2024-02-17,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,44.0,,3,Transient,75.0,0,0
HB-041440,City Hotel,0,12,2023,August,33,16,2023-08-16,2,3,3,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,27.0,,0,Transient,68.8,0,0
HB-084334,City Hotel,0,8,2024,February,8,21,2024-02-21,2,1,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,111.0,0,3
HB-083547,City Hotel,0,8,2024,February,6,5,2024-02-05,0,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,93.0,0,1
HB-027927,Resort Hotel,0,10,2024,September,37,13,2024-09-13,0,2,2,0.0,1,BB,USA,Direct,Direct,0,0,0,E,E,1,No Deposit,250.0,,0,Transient,129.0,0,0
HB-021459,Resort Hotel,0,17,2024,February,9,26,2024-02-26,1,2,2,0.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,196.0,,0,Transient,56.0,0,0
HB-094744,City Hotel,0,129,2024,August,31,4,2024-08-04,2,3,2,0.0,0,BB,DNK,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,80.5,0,1
HB-079810,City Hotel,1,55,2023,December,52,30,2023-12-30,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,1,1,0,A,A,0,No Deposit,3.0,,0,Transient-Party,70.0,0,0
HB-057478,City Hotel,0,418,2024,September,39,26,2024-09-26,1,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,132.0,,223,Transient-Party,107.0,0,0
HB-011745,Resort Hotel,1,103,2025,May,22,28,2025-05-28,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,410.0,,0,Transient,45.5,0,1
HB-104655,City Hotel,0,1,2025,January,3,15,2025-01-15,2,3,1,0.0,0,BB,CYP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,100.47,0,0
HB-053330,City Hotel,1,123,2024,June,25,17,2024-06-17,2,2,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.15,0,2
HB-001435,Resort Hotel,0,1,2023,August,35,29,2023-08-29,2,2,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,D,1,No Deposit,,,0,Transient-Party,142.5,0,1
HB-018545,Resort Hotel,0,289,2023,November,47,20,2023-11-20,1,2,2,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,57.0,0,0
HB-072441,City Hotel,1,315,2025,July,31,28,2025-07-28,1,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,0
HB-114572,City Hotel,0,125,2025,June,25,21,2025-06-21,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,0
HB-046211,City Hotel,0,3,2023,December,52,26,2023-12-26,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,75.0,0,0
HB-034269,Resort Hotel,0,186,2025,February,9,25,2025-02-25,6,15,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,75.0,,0,Transient,38.55,0,1
HB-101430,City Hotel,0,92,2024,November,46,11,2024-11-11,0,1,2,0.0,0,BB,THA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,364.0,,0,Transient-Party,90.0,0,0
HB-047857,City Hotel,1,20,2024,March,10,6,2024-03-06,2,1,1,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.0,0,0
HB-111758,City Hotel,0,277,2025,May,20,12,2025-05-12,1,2,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,16.0,,0,Transient,89.1,0,1
HB-081583,City Hotel,1,197,2024,June,23,3,2024-06-03,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,21.0,,25,Transient,80.0,0,0
HB-015358,Resort Hotel,0,121,2023,July,27,3,2023-07-03,2,5,2,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,115.0,,0,Contract,88.95,0,1
HB-024217,Resort Hotel,0,77,2024,May,19,10,2024-05-10,0,5,2,0.0,0,HB,USA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,241.0,,0,Transient,34.0,1,1
HB-065915,City Hotel,1,31,2025,April,15,10,2025-04-10,1,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,0
HB-059937,City Hotel,1,83,2024,November,44,3,2024-11-03,1,3,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,0
HB-017792,Resort Hotel,1,0,2025,February,9,27,2025-02-27,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,10,A,D,0,No Deposit,,380.0,0,Transient,35.0,0,0
HB-108962,City Hotel,0,86,2025,April,14,1,2025-04-01,2,2,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,157.25,0,1
HB-118100,City Hotel,0,7,2025,August,33,14,2025-08-14,1,0,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,180.0,0,0
HB-007036,Resort Hotel,1,181,2024,July,29,17,2024-07-17,2,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,152.86,0,1
HB-114469,City Hotel,0,28,2025,June,25,21,2025-06-21,0,1,1,0.0,0,BB,AUS,Corporate,Corporate,0,0,0,A,B,1,No Deposit,,481.0,0,Transient,144.0,0,0
HB-041369,City Hotel,1,40,2023,August,33,15,2023-08-15,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-086780,City Hotel,0,12,2024,April,15,8,2024-04-08,0,1,1,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,101.0,0,0
HB-100295,City Hotel,0,87,2024,October,43,23,2024-10-23,2,1,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,16.0,,0,Transient,80.75,0,1
HB-057011,City Hotel,1,205,2024,September,38,16,2024-09-16,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,120.0,0,0
HB-066875,City Hotel,1,88,2025,April,17,26,2025-04-26,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,170.0,,0,Transient,140.0,0,0
HB-062929,City Hotel,1,61,2025,January,4,25,2025-01-25,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,326.0,,0,Transient,80.0,0,0
HB-113789,City Hotel,0,29,2025,June,24,11,2025-06-11,1,0,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,1
HB-033352,Resort Hotel,0,16,2025,February,8,17,2025-02-17,2,2,3,0.0,0,BB,DNK,Corporate,Corporate,0,0,0,D,D,1,No Deposit,,498.0,0,Transient-Party,53.25,1,0
HB-050617,City Hotel,0,148,2024,May,18,5,2024-05-05,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,105.3,0,0
HB-106073,City Hotel,0,73,2025,February,8,17,2025-02-17,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,68.47,0,1
HB-076039,City Hotel,1,336,2023,September,38,18,2023-09-18,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-088383,City Hotel,0,3,2024,May,18,2,2024-05-02,1,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,E,0,No Deposit,28.0,,0,Transient,92.7,0,0
HB-034795,Resort Hotel,0,60,2025,April,14,4,2025-04-04,0,1,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,,251.0,0,Transient,62.0,0,1
HB-113804,City Hotel,0,25,2025,June,24,11,2025-06-11,1,0,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,129.0,0,1
HB-021316,Resort Hotel,0,0,2025,February,7,15,2025-02-15,0,1,1,0.0,0,BB,PRT,Online TA,Direct,1,0,3,A,D,1,No Deposit,240.0,,0,Transient,60.0,0,0
HB-067151,City Hotel,1,29,2025,April,18,29,2025-04-29,1,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,115.0,0,2
HB-097017,City Hotel,0,47,2024,September,37,9,2024-09-09,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.1,0,1
HB-038879,Resort Hotel,0,25,2025,July,31,28,2025-07-28,2,4,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,I,1,No Deposit,429.0,,0,Transient,0.0,0,0
HB-069606,City Hotel,1,129,2025,June,23,2,2025-06-02,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,154.0,,0,Transient,130.0,0,0
HB-026787,Resort Hotel,0,136,2024,August,32,7,2024-08-07,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,165.23,0,1
HB-002863,Resort Hotel,0,0,2023,November,44,3,2023-11-03,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,42.0,1,1
HB-016508,Resort Hotel,0,61,2023,August,35,29,2023-08-29,2,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,115.0,0,1
HB-096538,City Hotel,0,30,2024,September,35,1,2024-09-01,0,3,1,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,181.8,0,1
HB-074390,City Hotel,1,283,2023,July,30,27,2023-07-27,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-112945,City Hotel,0,174,2025,May,22,26,2025-05-26,2,3,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,162.0,0,2
HB-021970,Resort Hotel,0,2,2024,March,11,13,2024-03-13,1,0,1,0.0,0,BB,AUT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,15.0,,0,Transient,25.0,0,0
HB-020468,Resort Hotel,0,0,2024,March,12,18,2024-03-18,0,1,2,0.0,0,BB,,Direct,Direct,1,0,1,E,D,0,No Deposit,,,0,Transient,68.0,0,0
HB-043290,City Hotel,1,97,2023,September,37,17,2023-09-17,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,102.0,0,0
HB-094133,City Hotel,0,301,2024,July,31,30,2024-07-30,1,1,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-039859,Resort Hotel,0,3,2025,August,35,28,2025-08-28,1,2,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,235.8,0,2
HB-100093,City Hotel,0,96,2024,October,42,19,2024-10-19,0,4,2,0.0,0,BB,HUN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.8,0,2
HB-104404,City Hotel,0,2,2025,June,22,1,2025-06-01,0,3,2,0.0,0,BB,PRT,Corporate,Direct,1,0,2,A,A,0,No Deposit,,163.0,0,Transient,130.0,0,2
HB-044893,City Hotel,1,193,2023,October,41,15,2023-10-15,0,3,2,0.0,0,BB,,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,0,Transient,65.0,0,0
HB-094201,City Hotel,0,144,2024,July,31,30,2024-07-30,1,1,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,114.3,0,2
HB-088799,City Hotel,0,109,2024,May,19,8,2024-05-08,2,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,6.0,,0,Transient-Party,90.96,0,1
HB-038536,Resort Hotel,0,152,2025,July,29,16,2025-07-16,2,3,2,2.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,C,C,1,No Deposit,196.0,,0,Transient,188.65,0,0
HB-041738,City Hotel,0,3,2023,August,34,22,2023-08-22,2,1,1,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,36.25,0,0
HB-022047,Resort Hotel,0,0,2024,March,11,16,2024-03-16,0,1,1,0.0,0,BB,PRT,Corporate,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,40.0,0,0
HB-032264,Resort Hotel,0,64,2025,January,3,15,2025-01-15,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,62.0,0,1
HB-043948,City Hotel,1,88,2023,September,39,26,2023-09-26,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-046377,City Hotel,1,148,2023,December,52,30,2023-12-30,1,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,79,Transient,67.0,0,0
HB-018438,Resort Hotel,0,27,2025,April,14,2,2025-04-02,2,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,3,A,C,0,No Deposit,,20.0,0,Transient,45.0,0,1
HB-064368,City Hotel,1,356,2025,March,10,7,2025-03-07,0,4,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,77.35,0,0
HB-102262,City Hotel,0,109,2024,November,47,21,2024-11-21,1,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,97.75,0,2
HB-044560,City Hotel,0,92,2023,October,40,7,2023-10-07,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,58,Transient-Party,70.0,0,0
HB-065634,City Hotel,1,69,2025,April,14,6,2025-04-06,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,Non Refund,,197.0,0,Transient,85.0,0,0
HB-036645,Resort Hotel,0,114,2025,May,20,18,2025-05-18,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Transient,78.85,0,0
HB-032657,Resort Hotel,0,6,2025,January,5,31,2025-01-31,0,1,1,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,40.0,0,0
HB-085344,City Hotel,0,56,2024,March,10,10,2024-03-10,1,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,73.95,0,1
HB-119061,City Hotel,0,233,2025,August,35,26,2025-08-26,2,1,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,B,B,0,No Deposit,14.0,,0,Transient,123.05,0,0
HB-043814,City Hotel,0,56,2023,September,39,25,2023-09-25,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,44.0,,0,Transient-Party,185.0,0,0
HB-016161,Resort Hotel,0,101,2023,August,32,10,2023-08-10,2,5,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,184.0,0,0
HB-080153,City Hotel,0,18,2023,November,45,11,2023-11-11,0,1,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,101.0,0,2
HB-006724,Resort Hotel,1,0,2024,June,26,27,2024-06-27,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,8.0,0,0
HB-052144,City Hotel,1,113,2024,May,22,31,2024-05-31,0,3,1,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,A,0,Non Refund,,202.0,0,Transient,100.0,0,0
HB-020499,Resort Hotel,0,1,2024,January,5,30,2024-01-30,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,54.0,1,1
HB-080652,City Hotel,0,32,2023,November,47,20,2023-11-20,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,E,1,No Deposit,119.0,,0,Transient-Party,73.0,0,0
HB-020952,Resort Hotel,0,1,2024,February,6,11,2024-02-11,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,70.0,0,2
HB-015727,Resort Hotel,1,245,2023,September,39,25,2023-09-25,0,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,248.0,,0,Transient,80.0,0,0
HB-004680,Resort Hotel,1,143,2024,March,13,27,2024-03-27,2,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,45.6,0,2
HB-087724,City Hotel,0,42,2024,April,16,21,2024-04-21,1,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,103.84,0,1
HB-011303,Resort Hotel,1,87,2025,May,18,2,2025-05-02,0,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,115.0,0,0
HB-107809,City Hotel,0,54,2025,March,11,15,2025-03-15,0,4,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,57.6,0,1
HB-064647,City Hotel,1,53,2025,March,11,14,2025-03-14,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,94.0,,0,Transient-Party,65.0,0,0
HB-062300,City Hotel,1,129,2025,January,2,8,2025-01-08,2,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,D,D,0,Non Refund,,,0,Transient,67.0,0,0
HB-056446,City Hotel,1,49,2024,September,36,6,2024-09-06,0,3,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.91,0,0
HB-119217,City Hotel,0,29,2025,August,35,30,2025-08-30,0,2,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,10.0,,0,Transient,95.0,0,0
HB-002549,Resort Hotel,1,107,2023,October,42,21,2023-10-21,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,55.0,0,1
HB-055634,City Hotel,1,405,2024,August,33,18,2024-08-18,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-022012,Resort Hotel,0,9,2024,March,11,11,2024-03-11,2,3,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,83.2,0,0
HB-002014,Resort Hotel,0,100,2023,September,39,27,2023-09-27,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Transient,55.43,0,0
HB-040888,City Hotel,1,16,2023,August,32,8,2023-08-08,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-031716,Resort Hotel,0,10,2024,December,52,28,2024-12-28,2,6,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,H,2,No Deposit,240.0,,0,Transient,67.75,0,1
HB-049897,City Hotel,1,270,2024,April,16,20,2024-04-20,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,187,Transient-Party,62.8,0,0
HB-081276,City Hotel,0,16,2023,December,49,4,2023-12-04,2,2,2,1.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,92.85,0,0
HB-051868,City Hotel,0,159,2024,May,21,26,2024-05-26,0,3,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,7,No Deposit,9.0,,0,Transient,119.85,0,1
HB-086293,City Hotel,0,0,2024,March,13,29,2024-03-29,0,2,2,0.0,0,BB,GBR,Complementary,Direct,0,0,0,A,B,1,No Deposit,,,0,Transient,0.0,0,1
HB-053703,City Hotel,1,116,2024,June,26,27,2024-06-27,1,5,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,15,Transient,140.0,0,0
HB-077832,City Hotel,0,5,2023,September,39,28,2023-09-28,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-087221,City Hotel,0,0,2024,April,15,13,2024-04-13,0,3,2,0.0,0,SC,MAR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,118.0,1,1
HB-086739,City Hotel,0,77,2024,April,14,6,2024-04-06,0,2,2,0.0,0,BB,KOR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,105.3,0,1
HB-001590,Resort Hotel,0,25,2023,September,36,5,2023-09-05,1,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,E,F,0,No Deposit,240.0,,0,Transient,139.5,1,1
HB-069229,City Hotel,1,17,2025,May,22,28,2025-05-28,2,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,2
HB-053113,City Hotel,1,188,2024,June,24,15,2024-06-15,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,39,Transient,130.0,0,0
HB-044099,City Hotel,1,27,2023,September,39,30,2023-09-30,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,64.0,,21,Transient,108.0,0,0
HB-102906,City Hotel,0,46,2024,December,49,5,2024-12-05,1,3,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,16.0,,0,Transient,98.0,0,0
HB-081982,City Hotel,1,115,2024,March,12,20,2024-03-20,2,0,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,41.0,,22,Transient,70.0,0,0
HB-119142,City Hotel,0,190,2025,August,35,27,2025-08-27,2,1,3,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,162.0,0,2
HB-043973,City Hotel,1,33,2023,September,39,26,2023-09-26,2,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,16.0,,0,Transient,57.92,0,1
HB-012081,Resort Hotel,1,13,2025,June,24,12,2025-06-12,1,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,388.0,0,Transient,75.0,0,0
HB-078465,City Hotel,0,12,2023,October,40,5,2023-10-05,1,4,1,0.0,0,HB,DZA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,83.0,,0,Transient,110.5,0,0
HB-039536,Resort Hotel,0,67,2025,August,33,11,2025-08-11,3,7,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,135.0,0,0
HB-054496,City Hotel,1,217,2024,July,29,18,2024-07-18,1,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient,95.63,0,1
HB-075900,City Hotel,1,274,2023,July,29,18,2023-07-18,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-019931,Resort Hotel,0,8,2024,January,2,8,2024-01-08,0,2,2,0.0,0,BB,MAR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-116862,City Hotel,0,70,2025,July,30,22,2025-07-22,2,2,3,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,197.5,0,1
HB-073835,City Hotel,1,307,2023,August,33,20,2023-08-20,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-094797,City Hotel,0,77,2024,August,31,3,2024-08-03,2,5,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,4,No Deposit,9.0,,0,Transient,150.3,0,2
HB-086805,City Hotel,0,8,2024,April,14,5,2024-04-05,0,4,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,92.17,0,1
HB-073986,City Hotel,1,286,2023,July,30,30,2023-07-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-029132,Resort Hotel,0,1,2024,October,42,18,2024-10-18,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,90.0,0,1
HB-041817,City Hotel,0,5,2023,August,34,24,2023-08-24,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Contract,90.0,0,2
HB-016177,Resort Hotel,0,115,2023,August,32,10,2023-08-10,2,5,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,191.0,0,0
HB-051392,City Hotel,1,161,2024,May,20,19,2024-05-19,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,128.7,0,0
HB-092918,City Hotel,0,110,2024,July,28,11,2024-07-11,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.3,0,0
HB-031163,Resort Hotel,0,81,2024,December,50,10,2024-12-10,2,5,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,54.4,1,0
HB-040690,City Hotel,1,34,2023,August,31,5,2023-08-05,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-069651,City Hotel,1,270,2025,June,23,3,2025-06-03,2,1,2,1.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,138.6,0,1
HB-080542,City Hotel,0,20,2023,November,45,11,2023-11-11,2,5,1,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,68.85,0,1
HB-004376,Resort Hotel,1,15,2024,March,10,9,2024-03-09,0,3,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,115.0,,0,Transient-Party,59.0,0,0
HB-069520,City Hotel,1,174,2025,June,22,1,2025-06-01,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,110.0,0,0
HB-005552,Resort Hotel,0,199,2024,May,18,2,2024-05-02,1,1,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,85.0,0,0
HB-113877,City Hotel,0,223,2025,June,24,11,2025-06-11,2,0,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,90.09,0,1
HB-049147,City Hotel,1,29,2024,April,14,6,2024-04-06,0,4,2,0.0,0,SC,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,85.0,0,0
HB-109663,City Hotel,0,94,2025,April,15,11,2025-04-11,0,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,88.88,0,1
HB-014667,Resort Hotel,0,11,2025,July,28,11,2025-07-11,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,3,A,D,0,No Deposit,,135.0,0,Transient,142.0,0,1
HB-000134,Resort Hotel,0,0,2023,July,27,5,2023-07-05,1,0,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,C,1,No Deposit,306.0,,0,Transient,85.1,0,0
HB-082235,City Hotel,1,203,2024,June,22,2,2024-06-02,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,41,Transient,65.0,0,0
HB-003451,Resort Hotel,0,29,2023,December,49,10,2023-12-10,0,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,115.0,,0,Transient-Party,26.1,0,0
HB-058600,City Hotel,1,37,2024,October,41,13,2024-10-13,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,95.0,0,0
HB-004588,Resort Hotel,1,57,2024,March,12,24,2024-03-24,0,3,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,115.0,0,0
HB-091802,City Hotel,0,192,2024,June,26,24,2024-06-24,0,2,2,0.0,0,BB,SRB,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,34.0,,0,Transient-Party,110.0,0,0
HB-075466,City Hotel,1,334,2023,September,37,16,2023-09-16,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-040058,Resort Hotel,0,204,2025,August,35,29,2025-08-29,4,10,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,,0,Transient,153.57,0,3
HB-088408,City Hotel,0,102,2024,May,18,3,2024-05-03,0,3,2,0.0,0,BB,IND,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,9.0,,0,Transient,108.3,0,1
HB-097889,City Hotel,0,164,2024,September,38,17,2024-09-17,2,3,1,0.0,0,BB,AUS,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,108.11,0,1
HB-011825,Resort Hotel,1,411,2025,May,22,31,2025-05-31,2,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,71.1,0,0
HB-055945,City Hotel,1,412,2024,August,34,25,2024-08-25,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-042686,City Hotel,1,86,2023,September,36,9,2023-09-09,0,2,2,0.0,0,BB,FRA,Groups,Corporate,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,110.0,0,0
HB-098826,City Hotel,0,9,2024,October,40,2,2024-10-02,2,1,2,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,85.0,0,1
HB-089929,City Hotel,0,4,2024,May,22,29,2024-05-29,1,0,1,0.0,0,BB,NOR,Offline TA/TO,GDS,0,0,0,A,A,0,No Deposit,195.0,,0,Transient,96.0,0,0
HB-109773,City Hotel,0,298,2025,April,16,14,2025-04-14,1,2,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,6.0,,0,Transient-Party,80.0,0,0
HB-038376,Resort Hotel,0,5,2025,July,29,14,2025-07-14,0,2,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,G,1,No Deposit,240.0,,0,Transient,284.0,1,1
HB-061274,City Hotel,1,14,2024,December,49,6,2024-12-06,1,5,1,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.78,0,0
HB-100556,City Hotel,0,260,2024,October,43,22,2024-10-22,2,5,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,108.68,0,3
HB-084194,City Hotel,0,6,2024,February,8,19,2024-02-19,0,2,2,0.0,0,BB,TUR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,107.0,0,2
HB-030869,Resort Hotel,0,14,2024,December,49,5,2024-12-05,1,2,3,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,C,0,No Deposit,134.0,,0,Transient-Party,115.5,0,0
HB-033290,Resort Hotel,0,8,2025,February,8,18,2025-02-18,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,138.0,0,3
HB-032018,Resort Hotel,0,8,2025,January,3,14,2025-01-14,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,68.0,0,1
HB-007700,Resort Hotel,1,73,2024,August,34,21,2024-08-21,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,240.0,,0,Transient,205.0,0,0
HB-021353,Resort Hotel,0,93,2024,February,9,26,2024-02-26,2,7,1,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,B,1,No Deposit,314.0,,0,Transient,22.5,0,0
HB-113939,City Hotel,0,39,2025,June,24,12,2025-06-12,1,2,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,1
HB-012794,Resort Hotel,1,64,2025,July,29,17,2025-07-17,1,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,241.0,,0,Transient,201.4,0,1
HB-115201,City Hotel,0,126,2025,July,27,2,2025-07-02,1,0,2,1.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,133.6,0,0
HB-090963,City Hotel,0,137,2024,June,24,10,2024-06-10,2,2,2,0.0,0,BB,CHE,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,135.0,0,1
HB-073702,City Hotel,1,75,2025,August,35,31,2025-08-31,0,3,3,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,193.33,0,0
HB-049115,City Hotel,1,105,2024,April,14,6,2024-04-06,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,0,Transient,75.0,0,0
HB-013848,Resort Hotel,0,0,2025,June,23,5,2025-06-05,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,47.0,0,Transient,75.0,0,0
HB-018896,Resort Hotel,0,24,2024,May,18,2,2024-05-02,1,5,2,2.0,0,BB,FRA,Online TA,TA/TO,1,0,2,G,G,1,No Deposit,240.0,,0,Transient,147.0,1,1
HB-077224,City Hotel,0,327,2023,September,36,9,2023-09-09,2,4,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,21.0,,0,Transient-Party,76.0,0,0
HB-010245,Resort Hotel,1,70,2025,February,8,22,2025-02-22,0,4,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,405.0,0,Transient-Party,42.0,0,0
HB-022717,Resort Hotel,0,77,2024,March,13,31,2024-03-31,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,52.27,0,3
HB-110088,City Hotel,0,28,2025,April,17,21,2025-04-21,0,1,1,0.0,0,BB,USA,Direct,Direct,0,0,0,A,D,1,No Deposit,14.0,,0,Transient,93.5,0,0
HB-097298,City Hotel,0,346,2024,September,37,13,2024-09-13,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-080533,City Hotel,0,22,2023,November,46,17,2023-11-17,0,1,1,0.0,0,BB,AUT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,127.0,0,Transient-Party,71.0,0,0
HB-014926,Resort Hotel,1,132,2025,April,18,28,2025-04-28,1,2,1,0.0,0,BB,PRT,Online TA,Direct,1,4,13,A,A,0,No Deposit,,,0,Transient,61.5,0,4
HB-105624,City Hotel,0,0,2025,February,7,12,2025-02-12,0,0,2,0.0,0,BB,PRT,Direct,Direct,1,0,0,A,A,1,No Deposit,,,0,Transient,0.0,0,0
HB-099495,City Hotel,0,91,2024,October,41,12,2024-10-12,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,113.4,0,0
HB-079349,City Hotel,0,32,2023,October,43,24,2023-10-24,1,1,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Contract,136.0,0,1
HB-021092,Resort Hotel,0,0,2024,February,7,17,2024-02-17,0,1,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,43.0,0,1
HB-013346,Resort Hotel,1,262,2025,August,33,11,2025-08-11,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,153.75,0,0
HB-062184,City Hotel,1,46,2025,January,1,3,2025-01-03,2,8,2,0.0,0,SC,AGO,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,0
HB-087559,City Hotel,0,95,2024,April,16,20,2024-04-20,0,2,2,0.0,0,HB,AUT,Groups,TA/TO,0,0,0,A,B,0,No Deposit,35.0,,0,Transient-Party,98.0,0,0
HB-038277,Resort Hotel,0,183,2025,July,27,5,2025-07-05,2,7,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,139.78,1,1
HB-029687,Resort Hotel,0,36,2024,October,44,31,2024-10-31,1,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,49.17,0,2
HB-053341,City Hotel,1,91,2024,June,25,18,2024-06-18,1,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,116.1,0,0
HB-035080,Resort Hotel,0,22,2025,April,15,10,2025-04-10,1,2,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,120.67,1,1
HB-106198,City Hotel,0,27,2025,February,8,20,2025-02-20,1,2,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,79.0,,0,Transient,64.0,0,0
HB-038126,Resort Hotel,0,174,2025,July,28,7,2025-07-07,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,314.0,,0,Transient,92.4,0,0
HB-102765,City Hotel,0,13,2024,December,49,5,2024-12-05,1,0,1,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.0,0,0
HB-106744,City Hotel,0,61,2025,February,9,27,2025-02-27,1,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.0,0,2
HB-034026,Resort Hotel,0,19,2025,March,10,7,2025-03-07,0,4,2,0.0,0,HB,AUT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,75.0,1,0
HB-097022,City Hotel,0,89,2024,September,37,9,2024-09-09,0,2,3,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,168.3,0,2
HB-063112,City Hotel,1,56,2025,February,5,1,2025-02-01,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,60.0,0,0
HB-048735,City Hotel,1,56,2024,March,13,29,2024-03-29,0,3,3,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,123.3,0,1
HB-028057,Resort Hotel,0,9,2024,September,38,18,2024-09-18,1,0,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,E,E,0,No Deposit,223.0,,0,Transient-Party,90.0,0,0
HB-037254,Resort Hotel,0,21,2025,June,24,9,2025-06-09,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,126.0,0,1
HB-046538,City Hotel,0,1,2024,January,1,5,2024-01-05,4,13,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,6,No Deposit,,,0,Transient,70.67,0,0
HB-039982,Resort Hotel,0,97,2025,August,35,27,2025-08-27,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,118.5,0,1
HB-080959,City Hotel,1,18,2023,December,49,4,2023-12-04,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,B,B,0,No Deposit,9.0,,0,Contract,93.08,0,1
HB-100901,City Hotel,0,15,2024,November,44,1,2024-11-01,0,2,1,0.0,0,BB,PAN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,112.0,0,1
HB-103730,City Hotel,0,80,2024,December,52,27,2024-12-27,0,3,1,1.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,114.9,0,1
HB-075633,City Hotel,1,281,2023,July,30,25,2023-07-25,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-028704,Resort Hotel,0,7,2024,October,40,5,2024-10-05,0,4,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,D,1,No Deposit,,405.0,0,Transient-Party,50.0,0,0
HB-018330,Resort Hotel,0,82,2024,February,6,7,2024-02-07,2,0,2,1.0,0,Undefined,PRT,Groups,TA/TO,1,0,0,A,C,1,No Deposit,67.0,,0,Transient-Party,86.0,0,0
HB-012347,Resort Hotel,1,113,2025,June,26,25,2025-06-25,2,4,2,2.0,0,HB,ESP,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,248.0,0,0
HB-096813,City Hotel,0,35,2024,September,36,5,2024-09-05,1,3,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,157.0,,0,Transient,118.8,0,0
HB-010170,Resort Hotel,1,42,2025,February,8,18,2025-02-18,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,58.0,0,1
HB-022772,Resort Hotel,0,25,2024,April,14,4,2024-04-04,1,1,1,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,1,Non Refund,298.0,,0,Transient-Party,54.5,0,0
HB-001038,Resort Hotel,1,116,2023,August,32,11,2023-08-11,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,164.0,0,0
HB-110020,City Hotel,0,14,2025,April,16,18,2025-04-18,0,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,115.0,0,1
HB-085744,City Hotel,0,13,2024,March,12,20,2024-03-20,1,0,2,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,220.0,,0,Transient-Party,85.0,0,1
HB-010265,Resort Hotel,1,22,2025,February,8,23,2025-02-23,0,2,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,C,0,No Deposit,68.0,,0,Transient-Party,46.0,0,0
HB-058176,City Hotel,1,232,2024,October,41,7,2024-10-07,0,2,2,0.0,0,BB,CHE,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,98.1,0,0
HB-084820,City Hotel,0,53,2024,February,9,27,2024-02-27,2,4,2,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,121.0,,0,Transient,61.5,0,1
HB-084723,City Hotel,0,5,2024,March,9,2,2024-03-02,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,92.0,0,0
HB-037957,Resort Hotel,0,1,2025,July,27,3,2025-07-03,1,0,1,0.0,0,BB,KAZ,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient,173.0,0,2
HB-110116,City Hotel,0,120,2025,April,16,20,2025-04-20,0,3,2,0.0,0,BB,BRA,Direct,Direct,0,0,0,D,D,1,No Deposit,,,0,Transient,155.0,0,3
HB-092141,City Hotel,0,89,2024,June,26,26,2024-06-26,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,3
HB-023875,Resort Hotel,0,16,2024,April,18,29,2024-04-29,2,5,1,0.0,0,HB,NLD,Offline TA/TO,TA/TO,0,0,0,A,C,0,No Deposit,71.0,,0,Transient,48.1,0,0
HB-106092,City Hotel,0,10,2025,February,8,17,2025-02-17,1,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,92.0,0,1
HB-113043,City Hotel,0,131,2025,May,22,28,2025-05-28,2,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,85.0,0,1
HB-007959,Resort Hotel,1,78,2024,September,36,4,2024-09-04,3,5,3,1.0,0,HB,ESP,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,252.0,0,0
HB-072017,City Hotel,1,214,2025,July,29,17,2025-07-17,1,5,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,103.8,0,0
HB-079305,City Hotel,0,43,2023,October,43,23,2023-10-23,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,2.0,,0,Transient-Party,0.0,0,0
HB-003032,Resort Hotel,0,103,2023,November,45,11,2023-11-11,1,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,49.59,0,2
HB-051221,City Hotel,1,451,2024,May,20,16,2024-05-16,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-110202,City Hotel,0,133,2025,April,16,19,2025-04-19,0,4,2,0.0,0,BB,POL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,390.0,,0,Transient-Party,124.0,0,0
HB-017725,Resort Hotel,0,153,2023,October,41,14,2023-10-14,1,4,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,8.0,,0,Contract,57.6,0,1
HB-081920,City Hotel,1,278,2024,August,32,11,2024-08-11,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,65.0,0,0
HB-079999,City Hotel,1,159,2024,March,12,20,2024-03-20,2,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Contract,90.0,0,2
HB-106194,City Hotel,0,243,2025,February,8,19,2025-02-19,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,97.75,0,4
HB-054151,City Hotel,1,117,2024,July,27,7,2024-07-07,0,3,3,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,129.5,0,0
HB-110372,City Hotel,0,310,2025,April,17,23,2025-04-23,2,2,1,0.0,0,BB,AUT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,21.0,,0,Transient-Party,68.88,0,0
HB-108881,City Hotel,0,77,2025,March,14,31,2025-03-31,1,2,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,67.59,0,1
HB-008801,Resort Hotel,1,435,2024,October,42,14,2024-10-14,2,6,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,2.0,,0,Contract,63.4,0,0
HB-109955,City Hotel,0,157,2025,April,16,19,2025-04-19,0,1,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,99.0,0,1
HB-066137,City Hotel,1,151,2025,April,16,14,2025-04-14,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,135.0,0,1
HB-016650,Resort Hotel,0,208,2023,September,35,1,2023-09-01,0,5,2,0.0,0,BB,LUX,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,5.0,,0,Transient,58.95,1,0
HB-040867,City Hotel,1,124,2023,August,32,8,2023-08-08,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-072857,City Hotel,1,326,2025,August,32,8,2025-08-08,0,2,2,2.0,0,BB,MAR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,199.0,0,0
HB-063408,City Hotel,1,15,2025,February,7,11,2025-02-11,1,1,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,0
HB-015997,Resort Hotel,0,103,2023,August,31,6,2023-08-06,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,103.18,1,1
HB-054243,City Hotel,1,144,2024,July,28,9,2024-07-09,2,5,3,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,133.69,0,0
HB-101487,City Hotel,0,54,2024,November,46,11,2024-11-11,0,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,83.7,0,2
HB-086232,City Hotel,0,122,2024,March,13,27,2024-03-27,2,1,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,26.0,,0,Transient-Party,86.0,0,0
HB-089014,City Hotel,0,53,2024,May,20,13,2024-05-13,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,149.4,0,1
HB-035847,Resort Hotel,0,5,2025,May,18,2,2025-05-02,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,146.0,,0,Transient,45.0,1,0
HB-114829,City Hotel,0,93,2025,June,25,22,2025-06-22,2,3,2,0.0,0,BB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,85.0,0,0
HB-080921,City Hotel,1,3,2023,November,48,28,2023-11-28,0,1,2,0.0,1,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,83.0,,0,Transient,77.6,0,0
HB-114585,City Hotel,0,247,2025,June,25,22,2025-06-22,0,3,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,2
HB-078734,City Hotel,1,13,2023,October,42,19,2023-10-19,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Contract,126.0,0,3
HB-063528,City Hotel,1,61,2025,February,7,13,2025-02-13,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,95.4,0,0
HB-102563,City Hotel,0,0,2024,November,48,30,2024-11-30,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,383.0,0,Transient,64.0,0,1
HB-116972,City Hotel,0,127,2025,July,30,25,2025-07-25,0,3,2,0.0,0,BB,AUT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,16.0,,0,Transient,89.1,0,0
HB-066256,City Hotel,1,99,2025,April,16,15,2025-04-15,2,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,58.0,,0,Transient-Party,105.0,0,0
HB-016897,Resort Hotel,0,217,2023,September,36,7,2023-09-07,3,7,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,62.48,0,0
HB-107039,City Hotel,0,4,2025,March,10,6,2025-03-06,1,0,1,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,62.4,0,0
HB-058744,City Hotel,1,252,2024,October,42,15,2024-10-15,2,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient-Party,106.3,0,0
HB-020555,Resort Hotel,0,5,2024,December,50,14,2024-12-14,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,D,1,No Deposit,,43.0,0,Transient,30.0,0,0
HB-114532,City Hotel,0,106,2025,June,25,19,2025-06-19,1,3,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,1
HB-069975,City Hotel,1,130,2025,June,23,8,2025-06-08,0,3,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,162.0,0,0
HB-065439,City Hotel,1,73,2025,April,14,3,2025-04-03,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,105.0,0,0
HB-022025,Resort Hotel,0,20,2024,March,10,10,2024-03-10,2,4,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,102.0,0,2
HB-026053,Resort Hotel,0,0,2024,July,29,19,2024-07-19,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,119.0,0,0
HB-035704,Resort Hotel,0,317,2025,April,17,23,2025-04-23,2,5,2,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,D,D,1,No Deposit,273.0,,64,Transient-Party,78.94,0,0
HB-051616,City Hotel,1,84,2024,May,21,22,2024-05-22,2,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.31,0,1
HB-005034,Resort Hotel,1,78,2024,April,15,12,2024-04-12,4,10,2,0.0,0,HB,PRT,Groups,Direct,0,0,0,D,D,0,No Deposit,273.0,,0,Transient-Party,80.0,0,0
HB-094256,City Hotel,0,2,2024,August,31,1,2024-08-01,1,0,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,109.0,0,0
HB-089804,City Hotel,0,9,2024,May,21,25,2024-05-25,0,1,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,147.0,0,2
HB-052428,City Hotel,1,118,2024,June,23,6,2024-06-06,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,37.0,,0,Transient-Party,120.0,0,0
HB-089614,City Hotel,0,0,2024,June,25,20,2024-06-20,1,3,1,0.0,0,BB,FRA,Aviation,Corporate,1,0,1,A,A,0,No Deposit,,153.0,0,Transient,95.0,0,0
HB-096078,City Hotel,0,110,2024,August,34,21,2024-08-21,2,5,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,7.0,,0,Transient,205.38,0,2
HB-057935,City Hotel,1,219,2024,October,40,3,2024-10-03,1,3,2,0.0,0,BB,MKD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,102.85,0,1
HB-011143,Resort Hotel,1,239,2025,April,17,22,2025-04-22,2,5,3,0.0,0,FB,PRT,Groups,Corporate,0,0,0,C,C,0,No Deposit,,,0,Transient-Party,158.0,0,0
HB-087679,City Hotel,0,166,2024,April,16,21,2024-04-21,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,B,B,2,No Deposit,7.0,,0,Group,73.6,0,2
HB-053500,City Hotel,1,351,2024,June,25,23,2024-06-23,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,59.0,0,0
HB-088496,City Hotel,0,103,2024,May,18,4,2024-05-04,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,154.0,,0,Transient-Party,80.0,0,0
HB-098982,City Hotel,0,29,2024,October,40,5,2024-10-05,0,2,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,201.25,0,3
HB-074353,City Hotel,1,269,2023,July,28,13,2023-07-13,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Contract,62.0,0,0
HB-083005,City Hotel,0,35,2024,January,2,8,2024-01-08,2,2,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,58.0,0,1
HB-102630,City Hotel,0,30,2024,November,48,29,2024-11-29,0,4,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,1
HB-113021,City Hotel,0,54,2025,May,22,29,2025-05-29,1,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,121.6,0,1
HB-083978,City Hotel,0,12,2024,November,47,23,2024-11-23,0,2,1,0.0,0,BB,FRA,Corporate,Corporate,1,0,3,A,A,1,No Deposit,,91.0,0,Transient,79.0,0,0
HB-011060,Resort Hotel,1,221,2025,April,16,16,2025-04-16,2,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,60.0,0,2
HB-062475,City Hotel,1,38,2025,January,3,14,2025-01-14,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,Non Refund,,67.0,0,Transient,75.0,0,0
HB-035151,Resort Hotel,0,108,2025,April,15,10,2025-04-10,1,4,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,70.4,0,0
HB-098873,City Hotel,0,26,2024,October,40,3,2024-10-03,1,2,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,142.0,1,2
HB-009756,Resort Hotel,1,135,2024,December,1,30,2024-12-30,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,73.5,0,0
HB-019794,Resort Hotel,0,3,2024,January,1,2,2024-01-02,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,330.0,,0,Transient,39.0,0,0
HB-084587,City Hotel,0,32,2024,February,9,26,2024-02-26,1,2,2,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,26.0,,0,Transient,62.0,0,2
HB-081779,City Hotel,1,113,2024,February,8,25,2024-02-25,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,44,Transient,75.0,0,0
HB-105872,City Hotel,0,8,2025,February,7,15,2025-02-15,0,2,1,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,D,0,No Deposit,33.0,,0,Transient-Party,65.0,0,0
HB-075381,City Hotel,1,313,2023,August,34,26,2023-08-26,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-001611,Resort Hotel,0,40,2023,September,36,6,2023-09-06,2,0,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,128.0,0,1
HB-010072,Resort Hotel,1,238,2025,February,7,10,2025-02-10,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,155.0,,0,Transient,54.0,0,0
HB-060390,City Hotel,1,28,2024,November,45,9,2024-11-09,0,1,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,201.0,0,2
HB-076613,City Hotel,0,138,2023,July,30,25,2023-07-25,0,1,2,0.0,0,BB,BRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,60.0,0,0
HB-061547,City Hotel,1,185,2024,December,51,16,2024-12-16,1,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,0
HB-097084,City Hotel,0,55,2024,September,37,10,2024-09-10,1,1,3,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,168.3,0,1
HB-079247,City Hotel,1,444,2024,December,48,1,2024-12-01,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,34.0,,39,Transient,75.0,0,0
HB-083543,City Hotel,0,2,2024,February,5,3,2024-02-03,0,4,3,0.0,0,BB,HUN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.0,0,2
HB-073514,City Hotel,1,139,2025,August,34,24,2025-08-24,3,8,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,83.0,,0,Transient,117.41,0,0
HB-110468,City Hotel,0,40,2025,April,17,25,2025-04-25,0,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,174.0,0,2
HB-062955,City Hotel,1,61,2025,January,4,25,2025-01-25,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,326.0,,0,Transient,80.0,0,0
HB-080129,City Hotel,1,72,2023,December,52,27,2023-12-27,2,0,1,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,65.0,0,0
HB-098944,City Hotel,0,34,2024,October,40,4,2024-10-04,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,160.2,1,1
HB-034241,Resort Hotel,0,339,2025,March,11,11,2025-03-11,2,5,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,D,D,0,No Deposit,298.0,,0,Transient-Party,64.0,0,0
HB-021322,Resort Hotel,0,19,2024,February,8,21,2024-02-21,2,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,64.0,1,0
HB-032932,Resort Hotel,0,1,2025,February,7,10,2025-02-10,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-030657,Resort Hotel,0,21,2024,November,48,28,2024-11-28,1,1,1,0.0,0,BB,POL,Groups,TA/TO,0,0,0,E,E,0,No Deposit,,,0,Transient,45.0,0,0
HB-099320,City Hotel,0,23,2024,October,41,9,2024-10-09,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-068914,City Hotel,1,115,2025,May,21,22,2025-05-22,1,3,2,0.0,0,BB,LUX,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,173.25,0,2
HB-068356,City Hotel,1,78,2025,May,20,15,2025-05-15,1,3,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.25,0,0
HB-086008,City Hotel,0,37,2024,March,12,24,2024-03-24,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,126.45,0,0
HB-073424,City Hotel,1,188,2025,August,34,21,2025-08-21,1,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,0
HB-041033,City Hotel,0,1,2023,August,32,11,2023-08-11,0,2,2,2.0,0,SC,FRA,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,9.0,,0,Contract,162.0,1,0
HB-084671,City Hotel,0,115,2024,February,9,27,2024-02-27,2,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,134.0,,0,Transient-Party,76.0,0,0
HB-111342,City Hotel,0,17,2025,May,19,5,2025-05-05,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.5,0,3
HB-077418,City Hotel,0,19,2023,October,40,6,2023-10-06,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,1,0,0,A,D,0,No Deposit,82.0,,0,Transient-Party,80.0,0,0
HB-068359,City Hotel,1,172,2025,May,20,15,2025-05-15,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.1,0,0
HB-115122,City Hotel,0,125,2025,June,26,29,2025-06-29,0,3,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,96.53,0,0
HB-008750,Resort Hotel,0,364,2024,October,41,12,2024-10-12,0,4,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,D,0,No Deposit,,223.0,0,Transient-Party,72.0,1,0
HB-005351,Resort Hotel,1,189,2024,April,17,26,2024-04-26,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,248.0,,0,Transient-Party,46.0,0,0
HB-041374,City Hotel,0,2,2023,August,33,15,2023-08-15,2,2,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,E,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-043128,City Hotel,0,14,2023,September,37,15,2023-09-15,0,3,1,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,114.0,0,1
HB-042462,City Hotel,0,55,2023,September,36,6,2023-09-06,2,0,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,75.0,0,0
HB-109582,City Hotel,0,28,2025,April,15,11,2025-04-11,0,3,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,1
HB-104583,City Hotel,0,16,2025,January,3,15,2025-01-15,2,2,2,1.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,103.81,0,2
HB-083203,City Hotel,0,6,2024,January,4,23,2024-01-23,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,87.0,0,0
HB-040015,Resort Hotel,0,0,2025,August,35,29,2025-08-29,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,186.43,1,2
HB-070442,City Hotel,1,137,2025,June,25,17,2025-06-17,1,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,0
HB-091931,City Hotel,0,0,2024,June,26,26,2024-06-26,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,105.3,0,0
HB-076715,City Hotel,0,7,2024,December,50,14,2024-12-14,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,5,56,A,A,3,No Deposit,,40.0,0,Transient,67.0,1,2
HB-043079,City Hotel,0,17,2023,September,37,14,2023-09-14,1,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,13.0,,0,Contract,84.0,0,0
HB-055432,City Hotel,1,188,2024,August,33,13,2024-08-13,1,1,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.3,0,0
HB-089863,City Hotel,0,2,2024,May,22,27,2024-05-27,0,1,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,197.0,0,1
HB-092157,City Hotel,0,35,2024,June,26,27,2024-06-27,1,4,1,0.0,0,BB,FRA,Direct,Direct,0,0,0,E,E,1,No Deposit,14.0,,0,Transient,88.98,0,0
HB-069972,City Hotel,1,192,2025,June,23,8,2025-06-08,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,23,Transient,170.0,0,0
HB-029204,Resort Hotel,0,386,2024,October,42,20,2024-10-20,0,3,1,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,4,No Deposit,,,0,Transient-Party,46.0,0,0
HB-072322,City Hotel,1,243,2025,July,30,26,2025-07-26,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-050874,City Hotel,1,27,2024,May,19,10,2024-05-10,0,3,2,0.0,0,BB,TJK,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,141.0,0,0
HB-080214,City Hotel,0,48,2023,November,45,10,2023-11-10,0,4,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,43.5,0,0
HB-012718,Resort Hotel,1,31,2025,July,29,14,2025-07-14,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,215.0,0,1
HB-037757,Resort Hotel,0,292,2025,June,26,23,2025-06-23,2,4,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,80.1,0,2
HB-003066,Resort Hotel,1,41,2023,November,45,12,2023-11-12,1,3,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,E,E,1,No Deposit,185.0,281.0,0,Transient-Party,52.2,0,0
HB-094027,City Hotel,0,100,2024,July,30,25,2024-07-25,1,4,3,0.0,0,HB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,198.0,1,0
HB-068869,City Hotel,1,286,2025,May,21,22,2025-05-22,1,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,84.6,0,0
HB-079630,City Hotel,0,32,2023,October,43,26,2023-10-26,1,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,113.4,0,1
HB-025596,Resort Hotel,0,170,2024,July,27,2,2024-07-02,0,1,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,242.0,,0,Transient,119.1,1,2
HB-066039,City Hotel,1,111,2025,April,15,13,2025-04-13,0,3,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,181.5,0,0
HB-108534,City Hotel,0,158,2025,March,13,27,2025-03-27,1,1,2,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,95.0,0,1
HB-006906,Resort Hotel,1,35,2024,July,28,10,2024-07-10,2,1,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,160.0,0,0
HB-114337,City Hotel,0,5,2025,June,25,19,2025-06-19,1,0,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,190.0,0,1
HB-088158,City Hotel,0,61,2024,April,18,30,2024-04-30,1,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,97.71,0,0
HB-002108,Resort Hotel,0,50,2023,October,39,1,2023-10-01,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Transient,63.08,0,2
HB-081899,City Hotel,1,178,2024,April,17,28,2024-04-28,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,46,Transient,120.0,0,0
HB-025229,Resort Hotel,0,158,2024,June,24,12,2024-06-12,2,5,3,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,143.0,,0,Transient,99.9,0,0
HB-081227,City Hotel,0,21,2023,December,49,4,2023-12-04,1,2,2,0.0,0,SC,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,77.92,0,1
HB-084821,City Hotel,0,6,2024,March,9,2,2024-03-02,0,2,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,70.0,0,0
HB-027018,Resort Hotel,0,1,2024,August,33,16,2024-08-16,0,1,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient,209.0,0,1
HB-047769,City Hotel,1,16,2024,March,9,3,2024-03-03,0,3,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,84.33,0,0
HB-041470,City Hotel,0,46,2023,August,33,17,2023-08-17,1,1,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-014927,Resort Hotel,0,12,2024,April,16,15,2024-04-15,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,1,0,1,D,E,0,No Deposit,240.0,,0,Transient,75.0,0,1
HB-035274,Resort Hotel,0,108,2025,April,16,14,2025-04-14,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,91.67,0,1
HB-106000,City Hotel,0,114,2025,February,7,15,2025-02-15,0,4,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,242.0,0,Transient-Party,78.0,0,0
HB-104010,City Hotel,0,103,2024,December,1,31,2024-12-31,2,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,125.0,0,0
HB-026032,Resort Hotel,0,0,2024,July,29,18,2024-07-18,1,0,3,2.0,0,BB,AUS,Direct,Direct,0,0,0,H,H,1,No Deposit,,,0,Transient,210.0,0,0
HB-075689,City Hotel,1,295,2023,August,32,8,2023-08-08,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-081613,City Hotel,1,61,2023,December,51,24,2023-12-24,0,3,3,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,2,No Deposit,13.0,,0,Group,152.2,0,2
HB-100525,City Hotel,0,34,2024,October,43,26,2024-10-26,0,3,2,1.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,100.0,0,0
HB-116949,City Hotel,0,152,2025,July,30,22,2025-07-22,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,354.0,,0,Transient-Party,127.1,0,0
HB-079608,City Hotel,0,0,2023,October,43,28,2023-10-28,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,126.0,0,0
HB-018494,Resort Hotel,0,69,2023,November,46,17,2023-11-17,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,29.16,0,0
HB-054879,City Hotel,1,92,2024,July,30,28,2024-07-28,0,3,2,0.0,0,BB,PAK,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,121.8,0,0
HB-003456,Resort Hotel,0,126,2023,December,50,11,2023-12-11,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,24.95,0,1
HB-019904,Resort Hotel,0,0,2024,April,15,11,2024-04-11,1,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,2,A,A,0,No Deposit,,99.0,0,Transient,42.0,0,0
HB-117436,City Hotel,0,106,2025,July,31,30,2025-07-30,2,3,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,112.5,0,0
HB-014237,Resort Hotel,0,0,2023,November,44,3,2023-11-03,0,1,1,0.0,0,BB,,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,36.0,0,1
HB-035403,Resort Hotel,0,30,2025,April,16,14,2025-04-14,2,5,2,0.0,0,SC,PRT,Offline TA/TO,TA/TO,0,0,0,A,I,4,No Deposit,420.0,,0,Transient,3.0,0,0
HB-024795,Resort Hotel,0,112,2024,June,22,1,2024-06-01,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,171.0,,0,Transient,83.0,0,0
HB-078211,City Hotel,0,7,2023,October,40,5,2023-10-05,1,1,1,0.0,0,SC,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,114.0,0,1
HB-029390,Resort Hotel,0,31,2024,October,44,28,2024-10-28,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,47.0,0,0
HB-047411,City Hotel,1,24,2024,February,8,20,2024-02-20,0,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.0,0,0
HB-075911,City Hotel,1,274,2023,July,29,18,2023-07-18,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-028431,Resort Hotel,0,153,2024,September,39,29,2024-09-29,1,3,2,2.0,0,BB,ISR,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,150.0,1,1
HB-041581,City Hotel,1,13,2023,August,33,18,2023-08-18,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,90.0,0,2
HB-044842,City Hotel,1,38,2023,October,41,13,2023-10-13,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,13.0,,0,Group,84.0,0,0
HB-088461,City Hotel,0,97,2024,May,18,2,2024-05-02,1,4,2,0.0,0,SC,DNK,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,78.95,0,0
HB-084295,City Hotel,0,17,2024,February,8,20,2024-02-20,2,1,1,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,79.0,0,0
HB-032530,Resort Hotel,0,3,2025,January,5,28,2025-01-28,0,1,2,0.0,0,BB,PRT,Groups,Corporate,0,0,0,A,A,0,Non Refund,,504.0,0,Transient-Party,36.0,0,0
HB-100492,City Hotel,0,0,2024,October,44,29,2024-10-29,0,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,1,0,0,A,D,0,No Deposit,28.0,,0,Transient,0.0,0,1
HB-068968,City Hotel,1,357,2025,May,21,24,2025-05-24,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,0
HB-008662,Resort Hotel,1,131,2024,October,41,9,2024-10-09,2,0,2,0.0,0,BB,PRT,Groups,Corporate,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,55.0,0,0
HB-032972,Resort Hotel,0,25,2025,February,6,4,2025-02-04,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,38.4,0,0
HB-012197,Resort Hotel,1,112,2025,June,25,17,2025-06-17,2,5,2,2.0,0,BB,IRL,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,158.0,0,0
HB-118124,City Hotel,0,504,2025,August,33,12,2025-08-12,2,1,2,0.0,0,BB,USA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,1
HB-094861,City Hotel,0,26,2024,August,32,7,2024-08-07,2,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,151.0,0,2
HB-003920,Resort Hotel,1,72,2024,February,6,6,2024-02-06,2,1,2,0.0,0,HB,PRT,Groups,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,73.33,0,0
HB-001535,Resort Hotel,0,29,2023,September,35,3,2023-09-03,0,3,2,1.0,0,HB,PRT,Direct,Direct,0,0,0,D,F,2,No Deposit,250.0,,0,Transient,211.0,0,2
HB-052324,City Hotel,1,177,2024,June,23,3,2024-06-03,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,119.0,,0,Transient-Party,100.0,0,0
HB-062596,City Hotel,1,27,2025,January,3,16,2025-01-16,1,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,95.09,0,1
HB-114868,City Hotel,0,203,2025,June,25,22,2025-06-22,2,4,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,2
HB-068384,City Hotel,1,320,2025,May,20,16,2025-05-16,0,3,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.8,0,2
HB-025691,Resort Hotel,0,230,2024,June,26,28,2024-06-28,2,7,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,80.0,0,1
HB-079156,City Hotel,0,7,2023,October,42,21,2023-10-21,0,1,2,0.0,0,BB,USA,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,114.0,0,0
HB-104182,City Hotel,0,16,2025,January,2,6,2025-01-06,0,1,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,156.0,0,1
HB-056906,City Hotel,1,70,2024,September,37,15,2024-09-15,0,2,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,166.9,0,0
HB-013960,Resort Hotel,0,3,2025,March,9,2,2025-03-02,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,2,10,A,G,0,No Deposit,,135.0,0,Transient,35.0,1,2
HB-072820,City Hotel,1,111,2025,August,32,7,2025-08-07,1,3,2,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,183.0,0,3
HB-109354,City Hotel,0,67,2025,April,15,7,2025-04-07,1,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,42.0,,0,Transient,89.1,0,0
HB-090277,City Hotel,0,17,2024,June,23,3,2024-06-03,0,1,2,0.0,0,BB,COL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,141.0,0,1
HB-026927,Resort Hotel,0,87,2024,August,33,12,2024-08-12,1,2,2,2.0,0,BB,BRA,Direct,Direct,0,0,0,C,C,1,No Deposit,,,0,Transient,241.0,0,1
HB-045055,City Hotel,1,102,2023,October,42,16,2023-10-16,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-042129,City Hotel,0,27,2023,August,35,31,2023-08-31,1,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,75.0,0,0
HB-117959,City Hotel,0,148,2025,August,32,9,2025-08-09,0,3,2,0.0,1,HB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,164.7,0,1
HB-024322,Resort Hotel,0,61,2024,May,20,13,2024-05-13,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,78.25,0,1
HB-009059,Resort Hotel,1,65,2024,October,43,26,2024-10-26,0,4,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,98.0,0,2
HB-044942,City Hotel,1,180,2023,October,42,16,2023-10-16,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,70.0,0,0
HB-043751,City Hotel,0,86,2023,September,38,24,2023-09-24,0,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,105.0,0,0
HB-030795,Resort Hotel,0,80,2024,December,49,2,2024-12-02,0,2,2,0.0,0,BB,IRL,Groups,TA/TO,0,0,0,D,D,0,No Deposit,253.0,,0,Transient-Party,51.8,0,1
HB-003809,Resort Hotel,1,28,2024,January,2,9,2024-01-09,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,56.0,0,1
HB-005615,Resort Hotel,0,253,2024,May,18,5,2024-05-05,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,37.4,0,0
HB-009548,Resort Hotel,1,92,2024,December,49,8,2024-12-08,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,42.0,0,0
HB-051416,City Hotel,1,25,2024,May,20,19,2024-05-19,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,7.0,,0,Transient,158.0,0,0
HB-070629,City Hotel,1,128,2025,June,25,19,2025-06-19,1,5,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,0
HB-018548,Resort Hotel,0,289,2023,November,47,20,2023-11-20,1,2,3,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,A,C,1,No Deposit,134.0,,0,Transient-Party,85.5,0,0
HB-018785,Resort Hotel,0,9,2023,November,48,27,2023-11-27,0,2,2,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,0.0,0,1
HB-063912,City Hotel,1,134,2025,February,9,25,2025-02-25,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,75.0,0,0
HB-085306,City Hotel,0,3,2024,March,11,11,2024-03-11,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.0,0,2
HB-057943,City Hotel,1,285,2024,October,40,3,2024-10-03,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,24,Transient,100.0,0,0
HB-063068,City Hotel,1,36,2025,January,5,28,2025-01-28,2,5,3,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,145.84,0,1
HB-117408,City Hotel,0,192,2025,July,31,31,2025-07-31,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,144.67,0,0
HB-023758,Resort Hotel,0,3,2024,April,17,28,2024-04-28,2,3,1,0.0,0,HB,IRL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient-Party,127.0,0,1
HB-068709,City Hotel,1,93,2025,May,21,20,2025-05-20,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,89.1,0,1
HB-014765,Resort Hotel,1,259,2023,September,37,17,2023-09-17,0,3,1,0.0,0,BB,GBR,Groups,Corporate,0,1,0,A,A,0,Non Refund,,223.0,0,Transient,33.3,0,0
HB-041907,City Hotel,0,55,2023,August,34,26,2023-08-26,0,2,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,60.0,0,0
HB-083161,City Hotel,0,63,2024,January,3,19,2024-01-19,0,3,1,0.0,0,BB,BGR,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,19.0,,0,Transient-Party,71.0,0,0
HB-044011,City Hotel,0,68,2023,September,39,29,2023-09-29,0,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,20.0,,0,Transient-Party,65.0,0,0
HB-044162,City Hotel,0,164,2023,October,40,2,2023-10-02,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,19.0,,0,Transient-Party,100.0,0,1
HB-033716,Resort Hotel,0,0,2025,February,9,27,2025-02-27,1,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,60.0,0,0
HB-107444,City Hotel,0,1,2025,March,11,12,2025-03-12,1,0,1,0.0,0,BB,ITA,Aviation,Corporate,0,0,0,A,A,0,No Deposit,,153.0,0,Transient,80.0,0,0
HB-080927,City Hotel,0,8,2023,November,47,26,2023-11-26,0,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,10.0,,0,Group,67.5,0,1
HB-066176,City Hotel,1,44,2025,April,16,15,2025-04-15,2,1,2,0.0,0,BB,LUX,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,146.67,0,0
HB-064646,City Hotel,1,28,2025,March,11,14,2025-03-14,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,65.0,0,0
HB-094301,City Hotel,0,7,2025,August,34,24,2025-08-24,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,11,A,A,0,No Deposit,,40.0,0,Transient,67.0,0,1
HB-047993,City Hotel,0,67,2024,March,11,11,2024-03-11,1,2,2,0.0,0,BB,POL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,67.5,0,1
HB-032908,Resort Hotel,0,1,2025,February,6,8,2025-02-08,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,250.0,,0,Transient-Party,43.0,0,0
HB-022106,Resort Hotel,0,10,2024,March,11,17,2024-03-17,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,337.0,0,Transient-Party,30.0,0,1
HB-009353,Resort Hotel,1,80,2024,November,46,17,2024-11-17,1,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,37.8,0,1
HB-020400,Resort Hotel,0,3,2024,January,4,25,2024-01-25,1,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,207.0,0,Transient,33.0,1,0
HB-068233,City Hotel,1,104,2025,May,20,15,2025-05-15,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-019784,Resort Hotel,0,16,2025,June,27,30,2025-06-30,1,2,2,1.0,0,BB,PRT,Online TA,Direct,1,0,1,C,C,1,No Deposit,240.0,,0,Transient,193.33,0,1
HB-035378,Resort Hotel,0,130,2025,April,16,15,2025-04-15,2,4,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,1,No Deposit,493.0,,0,Contract,87.0,1,0
HB-053399,City Hotel,1,62,2024,June,25,20,2024-06-20,1,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.9,0,0
HB-061024,City Hotel,1,319,2024,November,48,29,2024-11-29,0,4,2,0.0,0,SC,AUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,63.75,0,0
HB-073771,City Hotel,1,272,2023,July,28,16,2023-07-16,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-015187,Resort Hotel,1,253,2023,September,37,12,2023-09-12,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,96.0,,0,Transient,58.95,0,0
HB-108025,City Hotel,0,17,2025,March,12,20,2025-03-20,1,1,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,2,No Deposit,9.0,,0,Transient,148.0,0,1
HB-037768,Resort Hotel,0,325,2025,June,26,23,2025-06-23,2,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient,85.21,0,1
HB-093733,City Hotel,0,136,2024,July,30,23,2024-07-23,2,1,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,B,B,0,No Deposit,1.0,,0,Transient,75.0,0,0
HB-090955,City Hotel,0,147,2024,June,24,11,2024-06-11,2,1,2,0.0,0,BB,ITA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient-Party,102.3,0,0
HB-113044,City Hotel,0,72,2025,May,22,28,2025-05-28,2,3,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,42.0,,0,Transient,121.1,0,1
HB-006792,Resort Hotel,1,171,2024,July,27,2,2024-07-02,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,94.5,0,1
HB-047214,City Hotel,1,19,2024,February,7,12,2024-02-12,1,2,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,138.0,0,1
HB-116829,City Hotel,0,227,2025,July,30,22,2025-07-22,2,2,2,1.0,0,BB,CMR,Online TA,TA/TO,0,0,0,A,A,3,No Deposit,9.0,,0,Transient,152.63,0,2
HB-056852,City Hotel,1,433,2024,September,37,15,2024-09-15,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-034562,Resort Hotel,0,54,2025,March,13,26,2025-03-26,2,1,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,65.0,0,2
HB-101575,City Hotel,0,74,2024,November,46,11,2024-11-11,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.6,0,2
HB-084276,City Hotel,0,17,2024,February,8,19,2024-02-19,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,66.0,0,0
HB-075148,City Hotel,1,278,2023,July,29,22,2023-07-22,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-081908,City Hotel,1,181,2024,May,18,5,2024-05-05,2,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,26.0,,42,Transient,90.0,0,0
HB-098218,City Hotel,0,19,2024,September,39,23,2024-09-23,1,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,139.0,0,3
HB-036939,Resort Hotel,0,6,2025,May,22,31,2025-05-31,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,290.0,0,Transient-Party,75.0,0,0
HB-101769,City Hotel,0,98,2024,November,46,14,2024-11-14,1,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,69.3,0,1
HB-063805,City Hotel,1,139,2025,February,8,21,2025-02-21,0,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,96.9,0,2
HB-067300,City Hotel,1,157,2025,May,18,1,2025-05-01,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,130.0,0,0
HB-100883,City Hotel,0,98,2024,October,44,30,2024-10-30,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.45,0,1
HB-036001,Resort Hotel,0,191,2025,May,18,4,2025-05-04,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,240.0,,0,Transient,82.17,0,1
HB-086893,City Hotel,0,134,2024,April,15,9,2024-04-09,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,90.0,0,1
HB-005503,Resort Hotel,1,31,2024,April,18,30,2024-04-30,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,86.0,0,0
HB-051818,City Hotel,1,323,2024,May,21,26,2024-05-26,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-107029,City Hotel,0,1,2025,March,10,3,2025-03-03,1,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,91.8,0,0
HB-118209,City Hotel,0,166,2025,August,33,12,2025-08-12,2,2,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,B,A,1,No Deposit,14.0,,0,Transient-Party,146.25,0,0
HB-059489,City Hotel,1,189,2024,October,44,28,2024-10-28,1,2,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,109.8,0,0
HB-029735,Resort Hotel,0,69,2024,October,44,29,2024-10-29,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient-Party,52.86,0,3
HB-015865,Resort Hotel,0,182,2023,July,30,27,2023-07-27,3,7,3,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,175.0,,0,Transient,154.35,0,1
HB-023858,Resort Hotel,0,3,2024,May,18,5,2024-05-05,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,B,0,No Deposit,78.0,,0,Transient,66.0,0,0
HB-088945,City Hotel,0,81,2024,May,19,12,2024-05-12,0,3,2,1.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,9.0,,0,Transient,143.1,0,2
HB-108041,City Hotel,0,151,2025,March,12,20,2025-03-20,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,C,0,No Deposit,37.0,,0,Transient-Party,95.0,0,0
HB-119055,City Hotel,0,8,2025,August,35,26,2025-08-26,2,1,2,3.0,0,BB,GBR,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,7.0,,0,Transient,253.51,0,2
HB-054461,City Hotel,1,157,2024,July,29,16,2024-07-16,2,2,2,0.0,0,SC,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,87.13,0,0
HB-036700,Resort Hotel,0,11,2025,May,21,24,2025-05-24,0,3,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,241.0,,0,Transient,120.0,1,1
HB-101032,City Hotel,0,42,2024,November,44,2,2024-11-02,0,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,73.37,0,1
HB-024311,Resort Hotel,0,1,2024,June,26,28,2024-06-28,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,1,0,1,A,C,1,No Deposit,168.0,,0,Transient,96.0,0,0
HB-021064,Resort Hotel,0,1,2024,February,7,16,2024-02-16,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,146.0,,0,Transient,25.0,1,0
HB-047048,City Hotel,0,60,2024,February,6,5,2024-02-05,1,2,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,78.3,0,0
HB-015938,Resort Hotel,0,12,2023,August,31,2,2023-08-02,2,5,2,0.0,1,BB,GBR,Online TA,TA/TO,0,0,0,F,G,0,No Deposit,241.0,,0,Transient,172.63,0,2
HB-031258,Resort Hotel,0,0,2024,December,51,18,2024-12-18,2,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,50.0,1,0
HB-021136,Resort Hotel,0,1,2024,February,7,17,2024-02-17,0,2,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,232.0,0,Transient,46.0,1,0
HB-014569,Resort Hotel,0,181,2023,August,32,10,2023-08-10,3,6,3,0.0,0,HB,,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,158.33,0,1
HB-077569,City Hotel,0,5,2023,September,38,22,2023-09-22,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-115875,City Hotel,0,80,2025,July,28,8,2025-07-08,2,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,96.0,0,1
HB-099570,City Hotel,0,53,2024,October,42,14,2024-10-14,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,E,0,No Deposit,77.0,,0,Transient-Party,120.0,0,0
HB-067584,City Hotel,1,161,2025,May,19,5,2025-05-05,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,30.0,,0,Transient,120.0,0,0
HB-090434,City Hotel,0,191,2024,June,23,3,2024-06-03,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient,132.0,0,0
HB-107589,City Hotel,0,0,2025,March,11,14,2025-03-14,0,1,2,0.0,0,BB,RUS,Online TA,Corporate,0,0,0,A,A,0,No Deposit,,120.0,0,Transient,98.0,0,1
HB-033631,Resort Hotel,0,0,2025,February,9,24,2025-02-24,2,2,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient-Party,38.0,0,0
HB-102288,City Hotel,0,2,2024,November,48,25,2024-11-25,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,197.0,0,Transient-Party,67.0,0,0
HB-045577,City Hotel,0,233,2023,November,45,7,2023-11-07,1,1,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,60.0,0,0
HB-042656,City Hotel,0,69,2023,September,36,9,2023-09-09,0,2,3,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,D,2,No Deposit,1.0,,0,Transient-Party,84.0,0,0
HB-048149,City Hotel,0,85,2024,March,11,17,2024-03-17,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,73.95,0,2
HB-010760,Resort Hotel,1,57,2025,April,14,1,2025-04-01,2,6,2,0.0,0,HB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,93.88,0,1
HB-083521,City Hotel,0,31,2024,February,5,4,2024-02-04,0,2,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,174.0,0,Transient-Party,77.0,0,0
HB-050048,City Hotel,1,142,2024,April,17,22,2024-04-22,2,3,1,0.0,0,BB,POL,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,89.0,0,0
HB-030186,Resort Hotel,0,1,2024,November,46,15,2024-11-15,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,358.0,,0,Transient,33.0,1,0
HB-025471,Resort Hotel,0,175,2024,June,25,22,2024-06-22,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,26.0,,0,Transient,78.95,0,0
HB-067751,City Hotel,1,407,2025,May,19,6,2025-05-06,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-023927,Resort Hotel,0,97,2024,May,18,1,2024-05-01,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,241.0,,0,Transient,76.89,0,1
HB-042205,City Hotel,0,63,2023,September,35,2,2023-09-02,0,3,2,0.0,0,BB,BRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,60.0,0,1
HB-113475,City Hotel,0,257,2025,June,23,4,2025-06-04,2,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,2
HB-088811,City Hotel,0,24,2024,May,19,8,2024-05-08,2,3,1,0.0,0,BB,USA,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,174.0,0,Transient,95.0,0,1
HB-073877,City Hotel,1,321,2023,September,35,3,2023-09-03,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-003506,Resort Hotel,1,216,2023,December,51,20,2023-12-20,4,9,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,40.29,0,1
HB-028349,Resort Hotel,0,117,2024,September,39,26,2024-09-26,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,150.0,1,1
HB-012760,Resort Hotel,1,17,2025,July,29,15,2025-07-15,3,6,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,241.0,,0,Transient,234.67,0,1
HB-116534,City Hotel,0,78,2025,July,29,19,2025-07-19,0,3,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,91.2,0,1
HB-039830,Resort Hotel,0,41,2025,August,35,26,2025-08-26,2,2,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,266.0,1,2
HB-039690,Resort Hotel,0,125,2025,August,34,20,2025-08-20,2,4,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,276.0,1,2
HB-054842,City Hotel,1,386,2024,July,30,28,2024-07-28,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-063047,City Hotel,1,192,2025,January,5,27,2025-01-27,0,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,103.5,0,0
HB-104471,City Hotel,0,275,2025,January,3,13,2025-01-13,0,1,2,0.0,0,BB,AUS,Direct,Direct,0,0,0,A,A,3,No Deposit,14.0,,0,Transient,67.15,0,0
HB-094871,City Hotel,0,38,2024,August,32,10,2024-08-10,0,1,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,152.1,0,1
HB-068427,City Hotel,1,395,2025,May,20,17,2025-05-17,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,90.0,0,0
HB-114301,City Hotel,0,448,2025,June,25,17,2025-06-17,2,1,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,1
HB-031081,Resort Hotel,0,14,2024,December,50,13,2024-12-13,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,250.0,,0,Transient,49.0,1,0
HB-037498,Resort Hotel,0,7,2025,June,25,19,2025-06-19,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,135.0,0,Transient,75.0,0,0
HB-049739,City Hotel,0,127,2024,April,16,18,2024-04-18,1,3,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,53.25,0,0
HB-045790,City Hotel,0,98,2023,November,47,23,2023-11-23,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,37.0,,0,Transient-Party,75.0,0,1
HB-007108,Resort Hotel,1,10,2024,July,30,22,2024-07-22,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,126.0,0,0
HB-063518,City Hotel,1,126,2025,February,7,12,2025-02-12,2,4,2,2.0,0,BB,DNK,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,169.65,0,0
HB-031569,Resort Hotel,0,128,2024,December,1,30,2024-12-30,0,2,2,0.0,0,HB,PRT,Groups,Direct,0,0,0,D,D,0,No Deposit,,,97,Transient-Party,325.0,0,1
HB-009086,Resort Hotel,1,142,2024,October,43,27,2024-10-27,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,78.0,0,0
HB-008507,Resort Hotel,1,403,2024,October,40,1,2024-10-01,6,15,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,52.2,0,0
HB-086468,City Hotel,0,135,2024,April,14,1,2024-04-01,0,2,2,1.0,1,BB,PRT,Direct,Direct,0,0,0,F,G,1,No Deposit,,,0,Transient,175.0,0,2
HB-094572,City Hotel,0,128,2024,August,31,3,2024-08-03,0,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.5,0,1
HB-052319,City Hotel,1,177,2024,June,23,3,2024-06-03,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,119.0,,0,Transient-Party,100.0,0,0
HB-023350,Resort Hotel,0,37,2024,April,16,19,2024-04-19,0,4,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,83.0,0,0
HB-003670,Resort Hotel,0,165,2023,December,52,30,2023-12-30,0,4,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,308.0,,122,Transient-Party,136.5,0,0
HB-060526,City Hotel,1,134,2024,November,46,13,2024-11-13,2,1,2,0.0,0,HB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,124.2,0,0
HB-039534,Resort Hotel,0,194,2025,August,33,14,2025-08-14,2,5,2,1.0,0,HB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,201.6,0,2
HB-084170,City Hotel,0,4,2024,February,8,19,2024-02-19,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,111.0,,0,Transient-Party,72.1,0,0
HB-115645,City Hotel,0,89,2025,July,28,8,2025-07-08,0,1,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,D,D,1,No Deposit,14.0,,0,Transient,170.5,0,1
HB-015852,Resort Hotel,0,0,2023,August,31,4,2023-08-04,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient,179.0,0,0
HB-098660,City Hotel,0,193,2024,September,40,30,2024-09-30,1,2,2,0.0,0,BB,DEU,Groups,Corporate,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,132.0,0,0
HB-032652,Resort Hotel,0,1,2025,February,7,15,2025-02-15,0,1,1,0.0,0,BB,PRT,Corporate,Direct,1,0,1,A,D,1,No Deposit,,225.0,0,Transient,35.0,0,0
HB-069718,City Hotel,1,173,2025,June,23,4,2025-06-04,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,120.0,0,0
HB-049975,City Hotel,1,58,2024,April,16,21,2024-04-21,1,3,2,2.0,0,BB,ITA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,167.45,0,0
HB-049820,City Hotel,1,270,2024,April,16,20,2024-04-20,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,187,Transient-Party,62.8,0,0
HB-058515,City Hotel,1,461,2024,October,41,13,2024-10-13,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-029265,Resort Hotel,0,111,2024,October,43,21,2024-10-21,1,2,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,83.0,0,1
HB-077884,City Hotel,0,17,2023,September,39,26,2023-09-26,2,2,1,0.0,0,BB,DNK,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,170.0,0,0
HB-039941,Resort Hotel,0,128,2025,August,35,28,2025-08-28,1,4,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,237.0,0,2
HB-067116,City Hotel,1,140,2025,April,18,28,2025-04-28,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,119.0,,0,Transient-Party,130.0,0,0
HB-095115,City Hotel,0,111,2024,August,33,13,2024-08-13,1,1,2,1.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,83.0,,0,Transient,99.28,0,0
HB-092332,City Hotel,0,100,2024,July,27,4,2024-07-04,1,0,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,112.5,1,1
HB-078709,City Hotel,0,2,2024,April,16,21,2024-04-21,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,20,A,A,0,No Deposit,,40.0,0,Transient,67.0,0,1
HB-117965,City Hotel,0,6,2025,August,32,10,2025-08-10,0,3,2,0.0,0,SC,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,166.67,0,2
HB-100822,City Hotel,0,68,2024,October,44,30,2024-10-30,2,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.6,0,2
HB-026781,Resort Hotel,0,50,2024,August,32,5,2024-08-05,2,4,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,C,C,1,No Deposit,426.0,,0,Transient-Party,231.17,0,0
HB-110730,City Hotel,0,7,2025,April,18,28,2025-04-28,1,2,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,1
HB-075361,City Hotel,1,313,2023,August,34,26,2023-08-26,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-017697,Resort Hotel,0,283,2023,October,41,12,2023-10-12,2,5,1,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,A,0,No Deposit,273.0,,0,Transient-Party,41.98,0,0
HB-117045,City Hotel,0,90,2025,July,30,22,2025-07-22,2,5,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,2,No Deposit,9.0,,0,Transient,225.0,0,2
HB-000550,Resort Hotel,1,62,2023,July,29,19,2023-07-19,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,261.0,,0,Transient,158.5,0,1
HB-048607,City Hotel,1,161,2024,March,13,25,2024-03-25,1,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,B,B,0,Non Refund,12.0,,101,Transient,130.0,0,0
HB-003535,Resort Hotel,0,131,2023,December,51,22,2023-12-22,2,5,2,0.0,0,HB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient-Party,64.14,0,1
HB-034625,Resort Hotel,0,77,2025,March,13,26,2025-03-26,2,3,2,0.0,0,HB,POL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,95.2,0,3
HB-083115,City Hotel,0,4,2024,January,3,19,2024-01-19,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,80.0,0,0
HB-083633,City Hotel,0,4,2024,February,6,7,2024-02-07,2,0,2,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,87.0,0,0
HB-001013,Resort Hotel,0,30,2023,August,32,10,2023-08-10,1,2,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient,211.0,0,0
HB-104143,City Hotel,0,17,2024,December,1,30,2024-12-30,2,5,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.34,0,1
HB-119100,City Hotel,0,26,2025,August,35,27,2025-08-27,2,0,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,143.5,0,2
HB-028751,Resort Hotel,0,30,2024,October,41,9,2024-10-09,2,0,1,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,55.0,0,0
HB-014249,Resort Hotel,0,2,2024,June,22,2,2024-06-02,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,4,A,D,0,No Deposit,,,0,Transient,75.0,0,0
HB-002877,Resort Hotel,0,8,2023,November,44,3,2023-11-03,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,43.2,1,1
HB-084415,City Hotel,0,0,2024,February,8,25,2024-02-25,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,70.0,0,0
HB-002687,Resort Hotel,0,115,2023,October,43,25,2023-10-25,2,4,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Contract,36.0,0,2
HB-102852,City Hotel,0,1,2025,January,5,29,2025-01-29,2,0,1,0.0,0,BB,PRT,Direct,TA/TO,1,0,1,A,A,2,No Deposit,,,0,Transient,80.0,0,0
HB-064945,City Hotel,1,56,2025,March,12,21,2025-03-21,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,86.0,,0,Transient,85.0,0,0
HB-044625,City Hotel,0,80,2023,October,41,9,2023-10-09,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,A,0,No Deposit,12.0,,50,Transient-Party,136.0,0,0
HB-115509,City Hotel,0,10,2025,July,27,6,2025-07-06,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,219.0,,0,Transient-Party,95.0,0,0
HB-048496,City Hotel,0,96,2024,March,12,24,2024-03-24,1,3,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient-Party,99.45,0,0
HB-088852,City Hotel,0,25,2024,May,19,10,2024-05-10,0,3,1,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,129.0,0,0
HB-104715,City Hotel,0,148,2025,January,3,17,2025-01-17,0,4,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,79.2,0,0
HB-025667,Resort Hotel,0,29,2024,July,27,5,2024-07-05,0,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,241.0,,0,Transient,150.92,0,1
HB-037895,Resort Hotel,0,139,2025,June,26,29,2025-06-29,0,3,2,3.0,0,BB,BRA,Online TA,TA/TO,0,0,0,C,H,3,No Deposit,240.0,,0,Transient,158.0,1,1
HB-098994,City Hotel,0,28,2024,October,40,4,2024-10-04,0,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,147.67,0,2
HB-054064,City Hotel,1,245,2024,July,27,6,2024-07-06,2,4,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,110.0,0,0
HB-080417,City Hotel,1,34,2023,December,49,8,2023-12-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,0,Transient,90.0,0,0
HB-072430,City Hotel,1,315,2025,July,31,28,2025-07-28,1,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,0
HB-007633,Resort Hotel,1,112,2024,August,33,17,2024-08-17,2,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,179.0,0,1
HB-115269,City Hotel,0,34,2025,July,27,3,2025-07-03,1,0,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,103.2,0,1
HB-117177,City Hotel,0,10,2025,July,31,28,2025-07-28,1,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,143.0,0,0
HB-107838,City Hotel,0,13,2025,March,12,18,2025-03-18,0,1,2,1.0,2,BB,PRT,Direct,Direct,0,0,0,D,F,3,No Deposit,14.0,,0,Transient,152.0,1,2
HB-065761,City Hotel,1,197,2025,April,15,7,2025-04-07,4,7,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,1
HB-110242,City Hotel,0,75,2025,April,17,21,2025-04-21,1,2,3,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,171.0,0,1
HB-037894,Resort Hotel,0,28,2025,July,27,1,2025-07-01,0,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,128.0,0,1
HB-037482,Resort Hotel,0,2,2025,June,25,16,2025-06-16,1,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,250.0,,0,Transient,135.0,0,0
HB-074761,City Hotel,0,241,2023,October,42,19,2023-10-19,1,2,2,0.0,0,BB,USA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,60.0,0,0
HB-080896,City Hotel,1,36,2023,December,52,31,2023-12-31,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,D,D,0,No Deposit,9.0,,0,Transient,123.3,0,0
HB-002950,Resort Hotel,1,36,2023,November,45,7,2023-11-07,2,6,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,281.0,,0,Transient-Party,40.0,0,0
HB-021450,Resort Hotel,0,53,2024,February,9,26,2024-02-26,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,196.0,,0,Transient,30.0,0,0
HB-105557,City Hotel,0,28,2025,February,6,9,2025-02-09,0,3,2,2.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,17.0,,0,Transient,120.75,0,0
HB-104360,City Hotel,0,5,2025,January,2,7,2025-01-07,2,3,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,116.62,0,2
HB-116529,City Hotel,0,161,2025,July,29,18,2025-07-18,0,4,2,1.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.1,0,1
HB-064799,City Hotel,1,53,2025,March,11,16,2025-03-16,0,3,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,106.2,0,4
HB-119324,City Hotel,0,136,2025,August,35,29,2025-08-29,0,5,1,0.0,0,SC,JPN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,131.0,0,2
HB-009274,Resort Hotel,1,0,2024,November,45,7,2024-11-07,1,0,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient-Party,85.0,0,0
HB-086622,City Hotel,0,55,2024,April,14,6,2024-04-06,0,1,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,A,1,No Deposit,56.0,,0,Transient-Party,92.0,0,0
HB-013157,Resort Hotel,1,213,2025,August,31,2,2025-08-02,2,8,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,165.15,0,2
HB-018273,Resort Hotel,0,0,2023,November,46,15,2023-11-15,1,0,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,D,1,No Deposit,,,0,Transient,38.0,0,0
HB-023695,Resort Hotel,0,197,2024,April,18,30,2024-04-30,1,1,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,85.0,0,0
HB-007795,Resort Hotel,1,73,2024,August,35,27,2024-08-27,0,1,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,189.0,0,0
HB-005213,Resort Hotel,0,191,2024,April,17,22,2024-04-22,1,2,2,0.0,0,Undefined,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,85.33,0,1
HB-111821,City Hotel,0,0,2025,May,20,15,2025-05-15,1,0,1,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,152.0,,0,Transient,88.56,0,0
HB-037938,Resort Hotel,0,258,2025,July,27,1,2025-07-01,1,1,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,137.3,0,2
HB-074345,City Hotel,1,269,2023,July,28,13,2023-07-13,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Contract,62.0,0,0
HB-005746,Resort Hotel,1,236,2024,May,19,12,2024-05-12,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,315.0,,0,Transient-Party,48.0,0,0
HB-080905,City Hotel,1,3,2023,November,48,27,2023-11-27,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Contract,87.0,0,1
HB-073818,City Hotel,1,300,2023,August,32,13,2023-08-13,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-085561,City Hotel,0,9,2024,March,11,17,2024-03-17,0,1,1,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,97.0,0,1
HB-060086,City Hotel,1,95,2024,November,45,5,2024-11-05,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,75.0,0,0
HB-097066,City Hotel,0,9,2024,September,37,11,2024-09-11,1,0,2,0.0,0,BB,PRT,Complementary,Direct,0,0,0,G,G,0,No Deposit,,,0,Transient,0.0,0,2
HB-032297,Resort Hotel,0,0,2025,January,4,21,2025-01-21,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,43.0,0,1
HB-064674,City Hotel,1,37,2025,March,11,15,2025-03-15,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,378.0,,0,Transient,110.0,0,0
HB-025981,Resort Hotel,0,95,2024,July,29,15,2024-07-15,1,2,3,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,241.0,,0,Transient,158.2,0,4
HB-046829,City Hotel,0,43,2024,January,3,19,2024-01-19,0,5,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,77.69,0,1
HB-002171,Resort Hotel,0,2,2023,October,40,4,2023-10-04,1,0,2,0.0,0,HB,DEU,Corporate,Corporate,0,0,0,A,E,0,No Deposit,110.0,,0,Transient,92.6,0,0
HB-058399,City Hotel,1,279,2024,October,41,12,2024-10-12,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,98.0,,0,Transient,110.0,0,0
HB-001861,Resort Hotel,1,101,2023,September,38,18,2023-09-18,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,83.0,0,0
HB-112184,City Hotel,0,28,2025,May,20,18,2025-05-18,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,190.0,0,1
HB-087016,City Hotel,0,170,2024,April,15,8,2024-04-08,2,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,78.0,0,0
HB-077909,City Hotel,0,9,2023,September,39,27,2023-09-27,2,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,155.08,0,1
HB-077894,City Hotel,0,1,2023,September,39,29,2023-09-29,0,1,2,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,D,0,No Deposit,92.0,,0,Transient-Party,85.0,0,0
HB-059797,City Hotel,1,104,2024,November,44,1,2024-11-01,0,5,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,0
HB-068105,City Hotel,1,14,2025,May,20,13,2025-05-13,0,1,2,0.0,0,SC,FIN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,180.0,0,1
HB-033520,Resort Hotel,0,2,2025,February,8,22,2025-02-22,0,3,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,F,F,1,No Deposit,250.0,,0,Transient,113.0,0,2
HB-046194,City Hotel,0,0,2023,December,51,24,2023-12-24,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.0,0,0
HB-114776,City Hotel,0,396,2025,June,26,25,2025-06-25,2,0,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,122.4,0,1
HB-109053,City Hotel,0,91,2025,April,14,2,2025-04-02,2,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,4
HB-026118,Resort Hotel,0,0,2024,July,29,21,2024-07-21,0,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,149.0,0,0
HB-051311,City Hotel,1,28,2024,May,20,17,2024-05-17,0,3,1,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,213.63,0,0
HB-082123,City Hotel,1,99,2024,February,8,19,2024-02-19,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,1,0,A,A,0,No Deposit,,67.0,0,Transient-Party,80.0,0,0
HB-028368,Resort Hotel,0,258,2024,September,39,29,2024-09-29,0,2,2,0.0,0,HB,LVA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,100.8,0,1
HB-104724,City Hotel,0,32,2025,January,4,21,2025-01-21,2,1,2,0.0,0,BB,TUR,Groups,TA/TO,0,0,0,A,A,1,No Deposit,171.0,,0,Group,85.0,0,0
HB-048377,City Hotel,1,251,2024,March,12,22,2024-03-22,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,93,Transient,90.0,0,0
HB-111941,City Hotel,0,100,2025,May,20,14,2025-05-14,2,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,139.5,0,2
HB-104100,City Hotel,0,2,2025,January,1,4,2025-01-04,0,2,3,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,156.0,0,0
HB-020580,Resort Hotel,0,0,2024,February,7,18,2024-02-18,0,1,1,0.0,0,BB,PRT,Direct,Direct,1,0,2,A,A,0,No Deposit,,,0,Transient,40.0,0,0
HB-068714,City Hotel,1,25,2025,May,21,20,2025-05-20,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,90.0,0,0
HB-069427,City Hotel,1,63,2025,May,22,30,2025-05-30,0,3,3,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,168.0,,0,Transient,125.1,0,1
HB-033387,Resort Hotel,0,5,2025,February,8,20,2025-02-20,1,0,1,0.0,0,SC,PRT,Corporate,Corporate,0,0,0,A,I,0,No Deposit,,515.0,0,Transient,0.0,0,0
HB-059294,City Hotel,1,86,2024,October,43,26,2024-10-26,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,104.4,0,1
HB-001095,Resort Hotel,0,0,2023,August,33,14,2023-08-14,0,1,2,2.0,0,BB,CHE,Direct,Direct,0,0,0,G,G,0,No Deposit,,,0,Transient,203.0,0,0
HB-084936,City Hotel,0,38,2024,March,9,3,2024-03-03,0,3,2,0.0,0,BB,POL,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,87.71,0,1
HB-009993,Resort Hotel,1,31,2025,February,6,3,2025-02-03,2,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,43.0,0,0
HB-054145,City Hotel,1,365,2024,July,27,7,2024-07-07,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-117244,City Hotel,0,468,2025,July,31,29,2025-07-29,2,1,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,1
HB-009306,Resort Hotel,1,19,2024,November,45,10,2024-11-10,2,5,2,0.0,0,Undefined,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,464.0,,0,Transient,66.0,0,0
HB-068414,City Hotel,1,237,2025,May,20,17,2025-05-17,0,1,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.1,0,2
HB-024493,Resort Hotel,0,74,2024,May,20,14,2024-05-14,3,6,2,0.0,0,BB,POL,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,70.0,0,0
HB-054259,City Hotel,0,195,2024,July,28,10,2024-07-10,2,2,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,B,A,4,No Deposit,9.0,,0,Transient-Party,81.81,0,1
HB-009401,Resort Hotel,1,46,2024,November,47,24,2024-11-24,0,3,1,0.0,0,BB,ARE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,37.8,0,1
HB-044205,City Hotel,0,164,2023,October,40,2,2023-10-02,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,19.0,,0,Transient-Party,100.0,0,0
HB-025542,Resort Hotel,0,164,2024,June,25,18,2024-06-18,4,10,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,2.0,,0,Contract,59.8,0,0
HB-036540,Resort Hotel,0,79,2025,May,20,17,2025-05-17,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,80.0,0,1
HB-020790,Resort Hotel,0,0,2024,February,6,6,2024-02-06,2,2,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,156.0,,0,Transient,48.19,0,0
HB-041227,City Hotel,1,39,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,101.5,0,0
HB-095529,City Hotel,0,320,2024,August,33,18,2024-08-18,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-071041,City Hotel,1,141,2025,June,26,27,2025-06-27,2,5,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,130.0,0,0
HB-026097,Resort Hotel,0,17,2024,July,30,22,2024-07-22,2,2,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,183.5,0,1
HB-098902,City Hotel,0,1,2024,October,40,6,2024-10-06,0,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,152.0,,0,Transient,108.04,0,0
HB-062013,City Hotel,1,18,2024,December,1,30,2024-12-30,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,120.0,0,0
HB-095070,City Hotel,0,135,2024,August,33,13,2024-08-13,0,1,2,1.0,0,BB,DNK,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.5,0,1
HB-110060,City Hotel,0,167,2025,April,16,17,2025-04-17,1,3,2,0.0,0,BB,CHE,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,16.0,,0,Transient-Party,89.1,0,0
HB-111869,City Hotel,0,96,2025,May,20,14,2025-05-14,2,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,138.0,0,0
HB-115471,City Hotel,0,405,2025,July,27,4,2025-07-04,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,114.4,0,0
HB-038970,Resort Hotel,0,169,2025,July,31,31,2025-07-31,1,3,2,0.0,1,HB,PRT,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,212.0,0,4
HB-097011,City Hotel,0,206,2024,September,36,8,2024-09-08,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient-Party,130.5,1,1
HB-114054,City Hotel,0,0,2025,June,24,14,2025-06-14,0,2,2,0.0,0,SC,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,160.0,0,0
HB-078068,City Hotel,0,6,2023,September,39,27,2023-09-27,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,7.0,,0,Transient,136.75,0,1
HB-008748,Resort Hotel,0,364,2024,October,41,12,2024-10-12,0,4,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,D,0,No Deposit,,223.0,0,Transient-Party,66.0,0,0
HB-053190,City Hotel,1,245,2024,June,25,17,2024-06-17,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,0,Transient,75.0,0,0
HB-091575,City Hotel,0,7,2024,June,25,20,2024-06-20,1,3,2,0.0,0,SC,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,72.25,0,0
HB-031658,Resort Hotel,0,294,2024,December,52,28,2024-12-28,2,4,1,0.0,0,HB,GBR,Direct,Direct,0,0,0,A,A,2,No Deposit,250.0,,0,Transient,84.5,0,0
HB-060441,City Hotel,1,58,2024,November,46,11,2024-11-11,0,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,0
HB-011316,Resort Hotel,1,237,2025,May,18,3,2025-05-03,0,1,2,0.0,0,HB,RUS,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient-Party,92.0,0,0
HB-086554,City Hotel,0,20,2024,April,14,3,2024-04-03,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,95.0,0,0
HB-106568,City Hotel,0,49,2025,February,9,24,2025-02-24,1,2,2,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,C,0,No Deposit,85.0,,0,Transient,72.0,0,1
HB-091273,City Hotel,0,18,2024,June,25,17,2024-06-17,0,2,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,129.0,0,0
HB-039886,Resort Hotel,0,185,2025,August,35,27,2025-08-27,2,2,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,410.0,,0,Transient,116.5,0,2
HB-010670,Resort Hotel,1,103,2025,March,13,27,2025-03-27,1,1,1,0.0,0,BB,PRT,Groups,Corporate,0,0,0,A,A,0,Non Refund,495.0,,0,Transient,42.0,0,0
HB-088877,City Hotel,0,18,2024,May,19,10,2024-05-10,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,146.0,0,1
HB-115689,City Hotel,0,175,2025,July,27,5,2025-07-05,1,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,0
HB-118307,City Hotel,0,1,2025,August,33,17,2025-08-17,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,189.0,0,2
HB-025441,Resort Hotel,0,124,2024,June,25,21,2024-06-21,2,5,2,1.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,142.36,0,3
HB-113299,City Hotel,0,104,2025,June,23,2,2025-06-02,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,144.0,0,0
HB-086142,City Hotel,0,81,2024,March,13,25,2024-03-25,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,4,No Deposit,3.0,,4,Transient-Party,65.0,0,1
HB-017302,Resort Hotel,0,174,2023,September,38,24,2023-09-24,2,8,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Contract,37.73,0,0
HB-110574,City Hotel,0,0,2025,April,17,27,2025-04-27,0,2,2,0.0,0,BB,PRT,Complementary,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,0.0,1,2
HB-083211,City Hotel,0,8,2024,January,3,20,2024-01-20,0,4,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,79.0,0,2
HB-052471,City Hotel,1,213,2024,June,23,7,2024-06-07,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,62,Transient,130.0,0,0
HB-019689,Resort Hotel,0,0,2023,December,52,31,2023-12-31,0,3,2,2.0,0,BB,PRT,Direct,Direct,1,0,0,H,H,1,No Deposit,,,0,Transient,139.33,1,0
HB-056448,City Hotel,1,49,2024,September,36,6,2024-09-06,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,110.7,0,0
HB-027067,Resort Hotel,0,250,2025,August,32,6,2025-08-06,4,10,3,0.0,0,HB,PRT,Direct,Direct,1,0,1,E,E,0,No Deposit,,,0,Transient,251.43,1,3
HB-095946,City Hotel,0,142,2024,August,34,21,2024-08-21,2,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient,95.79,0,1
HB-110844,City Hotel,0,140,2025,April,18,28,2025-04-28,2,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,119.0,,0,Transient-Party,130.0,0,1
HB-085406,City Hotel,0,53,2024,March,11,12,2024-03-12,2,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,67.5,0,1
HB-031758,Resort Hotel,0,76,2025,January,1,2,2025-01-02,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,37.8,0,3
HB-006323,Resort Hotel,1,122,2024,June,23,3,2024-06-03,2,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,97.5,0,3
HB-047550,City Hotel,0,68,2024,February,9,26,2024-02-26,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.3,0,0
HB-092696,City Hotel,0,177,2024,July,28,9,2024-07-09,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,96.0,0,0
HB-064766,City Hotel,1,2,2025,March,11,16,2025-03-16,0,1,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,0
HB-072117,City Hotel,1,31,2025,July,30,21,2025-07-21,1,2,1,0.0,0,BB,AGO,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,170.0,0,0
HB-111522,City Hotel,0,307,2025,May,19,11,2025-05-11,0,1,2,0.0,0,BB,MOZ,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,467.0,,0,Transient-Party,89.1,0,0
HB-001287,Resort Hotel,1,80,2023,August,34,22,2023-08-22,3,6,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,151.89,0,2
HB-055651,City Hotel,1,405,2024,August,33,18,2024-08-18,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-096272,City Hotel,0,194,2024,August,34,24,2024-08-24,2,5,2,1.0,0,BB,DZA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,111.11,0,2
HB-063697,City Hotel,1,183,2025,February,8,17,2025-02-17,1,2,2,2.0,0,BB,IRL,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,156.6,0,2
HB-068733,City Hotel,1,420,2025,May,21,20,2025-05-20,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-098389,City Hotel,0,12,2024,September,39,27,2024-09-27,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,B,1,No Deposit,138.0,,0,Transient,95.0,0,0
HB-043184,City Hotel,0,37,2023,September,37,16,2023-09-16,0,2,2,0.0,0,BB,NZL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,94.5,0,0
HB-060837,City Hotel,1,3,2024,November,47,23,2024-11-23,6,18,2,0.0,0,SC,SAU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.78,0,0
HB-088331,City Hotel,0,83,2024,May,18,1,2024-05-01,2,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-032750,Resort Hotel,0,1,2025,February,6,3,2025-02-03,0,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,241.0,,0,Transient,56.21,0,1
HB-101690,City Hotel,0,43,2024,November,46,16,2024-11-16,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.0,0,1
HB-065649,City Hotel,1,69,2025,April,14,6,2025-04-06,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,Non Refund,,197.0,0,Transient,85.0,0,0
HB-110707,City Hotel,0,150,2025,April,18,28,2025-04-28,1,2,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,144.0,0,0
HB-108245,City Hotel,0,9,2025,March,12,20,2025-03-20,1,4,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,87.04,0,0
HB-066359,City Hotel,1,21,2025,April,16,18,2025-04-18,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,115.0,0,1
HB-050181,City Hotel,1,82,2024,April,17,25,2024-04-25,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,74.15,0,1
HB-068788,City Hotel,1,75,2025,May,21,20,2025-05-20,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,90.0,0,0
HB-105201,City Hotel,0,29,2025,January,5,31,2025-01-31,0,2,2,0.0,0,HB,ESP,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,145.0,0,1
HB-074965,City Hotel,1,164,2023,August,33,14,2023-08-14,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-003993,Resort Hotel,0,112,2024,February,7,12,2024-02-12,0,2,2,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,70.0,0,0
HB-097058,City Hotel,0,47,2024,September,37,10,2024-09-10,1,1,2,0.0,0,HB,ITA,Groups,TA/TO,0,0,0,A,C,1,No Deposit,1.0,,0,Transient-Party,96.0,0,1
HB-076413,City Hotel,0,103,2023,July,29,18,2023-07-18,2,1,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,72.5,0,0
HB-045267,City Hotel,0,69,2023,October,43,25,2023-10-25,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,58,Transient-Party,85.67,0,0
HB-072931,City Hotel,1,217,2025,August,32,10,2025-08-10,0,2,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,123.3,0,1
HB-087619,City Hotel,0,69,2024,April,16,21,2024-04-21,0,2,3,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,G,0,No Deposit,9.0,,0,Transient,137.7,0,2
HB-028537,Resort Hotel,0,3,2024,October,40,2,2024-10-02,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,101.0,1,1
HB-102959,City Hotel,0,17,2024,December,50,9,2024-12-09,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-012113,Resort Hotel,1,97,2025,June,24,14,2025-06-14,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,120.0,0,1
HB-071379,City Hotel,1,405,2025,July,27,4,2025-07-04,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,80.0,0,0
HB-061334,City Hotel,1,517,2024,December,49,8,2024-12-08,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-084578,City Hotel,0,9,2024,February,9,26,2024-02-26,1,2,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,64.03,0,1
HB-093080,City Hotel,0,149,2024,July,28,12,2024-07-12,0,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.45,0,1
HB-085525,City Hotel,0,108,2024,March,11,13,2024-03-13,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,59.37,0,0
HB-117129,City Hotel,0,351,2025,July,30,27,2025-07-27,0,3,0,2.0,0,BB,CHE,Online TA,TA/TO,0,0,0,B,A,0,No Deposit,9.0,,0,Transient,90.05,0,1
HB-105664,City Hotel,0,79,2025,February,7,10,2025-02-10,1,2,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,3
HB-063078,City Hotel,1,9,2025,January,5,29,2025-01-29,4,10,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,0
HB-068451,City Hotel,1,115,2025,May,20,18,2025-05-18,0,3,1,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,1
HB-062564,City Hotel,1,18,2025,January,3,14,2025-01-14,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,82.88,0,0
HB-015383,Resort Hotel,0,137,2023,July,27,7,2023-07-07,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient,110.7,0,1
HB-107165,City Hotel,0,174,2025,March,10,5,2025-03-05,2,2,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,90.0,0,1
HB-057664,City Hotel,1,287,2024,September,39,29,2024-09-29,1,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,100.3,0,0
HB-050449,City Hotel,1,22,2024,May,18,1,2024-05-01,2,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,137.67,0,0
HB-092683,City Hotel,0,82,2024,July,28,9,2024-07-09,0,1,3,1.0,0,BB,CN,Online TA,TA/TO,0,0,0,D,E,2,No Deposit,9.0,,0,Transient,181.7,0,1
HB-085233,City Hotel,0,4,2024,March,10,7,2024-03-07,1,3,1,0.0,0,HB,DZA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,12.0,,0,Transient-Party,88.0,0,0
HB-042783,City Hotel,1,44,2023,September,36,10,2023-09-10,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,41.0,,0,Transient,126.0,0,0
HB-108411,City Hotel,0,0,2025,March,13,24,2025-03-24,0,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,152.0,,0,Transient,64.95,0,0
HB-009255,Resort Hotel,1,211,2024,November,45,5,2024-11-05,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,11.0,,0,Transient,30.0,0,0
HB-021990,Resort Hotel,0,0,2024,March,11,14,2024-03-14,1,0,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,49.0,1,0
HB-103294,City Hotel,0,87,2024,December,51,16,2024-12-16,0,2,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,126.0,0,2
HB-066275,City Hotel,1,45,2025,April,16,16,2025-04-16,2,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,0
HB-097633,City Hotel,0,315,2024,September,38,17,2024-09-17,1,1,2,0.0,0,BB,AUT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,38,Transient-Party,65.0,0,1
HB-103925,City Hotel,0,0,2024,December,52,29,2024-12-29,1,3,2,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,220.0,,0,Transient-Party,12.0,0,0
HB-060168,City Hotel,1,277,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-059439,City Hotel,1,199,2024,October,44,28,2024-10-28,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,29.0,,0,Transient-Party,95.0,0,0
HB-090833,City Hotel,0,107,2024,June,24,10,2024-06-10,0,2,1,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,187.0,,0,Transient-Party,120.0,0,0
HB-119214,City Hotel,0,213,2025,August,35,28,2025-08-28,1,3,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,19.0,,0,Transient-Party,104.0,0,0
HB-025484,Resort Hotel,0,203,2024,June,25,23,2024-06-23,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,143.0,,0,Transient,51.85,0,2
HB-027072,Resort Hotel,0,0,2024,August,33,18,2024-08-18,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,209.0,0,1
HB-053286,City Hotel,1,350,2024,June,25,17,2024-06-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,140.0,0,0
HB-013363,Resort Hotel,1,201,2025,August,33,12,2025-08-12,2,1,2,0.0,0,FB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,155.7,0,0
HB-009079,Resort Hotel,1,142,2024,October,43,27,2024-10-27,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,78.0,0,0
HB-101297,City Hotel,0,45,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,EST,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,147.6,0,0
HB-104398,City Hotel,0,0,2025,January,2,12,2025-01-12,0,1,1,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,53.9,0,0
HB-022665,Resort Hotel,0,67,2024,April,14,1,2024-04-01,1,2,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,D,E,0,No Deposit,250.0,,0,Transient,60.92,0,2
HB-008614,Resort Hotel,1,385,2024,October,41,8,2024-10-08,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,2,Refundable,315.0,,0,Transient-Party,48.0,0,0
HB-065216,City Hotel,1,19,2025,March,13,29,2025-03-29,0,1,1,0.0,0,SC,ZAF,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.0,0,0
HB-021642,Resort Hotel,0,4,2024,March,10,5,2024-03-05,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,2,No Deposit,250.0,,0,Transient,50.0,0,0
HB-041602,City Hotel,0,7,2023,August,33,19,2023-08-19,1,4,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,B,1,No Deposit,,,0,Transient,75.0,0,0
HB-068068,City Hotel,1,84,2025,May,20,12,2025-05-12,0,2,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,189.0,0,0
HB-040891,City Hotel,0,16,2023,August,32,8,2023-08-08,2,2,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-102498,City Hotel,0,45,2024,November,48,28,2024-11-28,1,1,2,0.0,0,BB,ITA,Direct,Direct,0,0,0,D,A,0,No Deposit,14.0,,10,Transient-Party,80.0,0,0
HB-031885,Resort Hotel,0,186,2025,January,1,3,2025-01-03,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,314.0,,0,Transient,51.6,0,0
HB-112692,City Hotel,0,3,2025,May,22,26,2025-05-26,0,1,1,0.0,0,SC,ITA,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,128.0,0,0
HB-045006,City Hotel,0,102,2023,October,42,16,2023-10-16,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,B,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-001153,Resort Hotel,1,4,2023,August,33,16,2023-08-16,1,0,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,E,E,0,No Deposit,,110.0,0,Transient,185.0,0,0
HB-030980,Resort Hotel,0,22,2024,December,49,8,2024-12-08,0,3,2,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,38.0,,0,Transient-Party,80.0,0,0
HB-055061,City Hotel,1,160,2024,August,31,4,2024-08-04,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.5,0,0
HB-021570,Resort Hotel,0,1,2024,February,9,29,2024-02-29,1,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,66.0,1,0
HB-040060,Resort Hotel,0,161,2025,August,35,31,2025-08-31,4,10,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,69.0,,0,Transient,99.06,0,0
HB-053244,City Hotel,1,245,2024,June,25,17,2024-06-17,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,0,Transient,75.0,0,0
HB-042902,City Hotel,1,6,2023,September,37,11,2023-09-11,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,127.0,0,0
HB-068943,City Hotel,1,201,2025,May,21,23,2025-05-23,0,3,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,0
HB-093933,City Hotel,0,116,2024,July,30,28,2024-07-28,0,1,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,105.3,0,1
HB-034325,Resort Hotel,0,0,2025,March,12,19,2025-03-19,1,0,2,0.0,0,BB,USA,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient-Party,100.0,0,0
HB-102055,City Hotel,0,0,2024,November,47,23,2024-11-23,0,0,0,0.0,0,BB,PRT,Online TA,TA/TO,1,0,0,A,A,0,No Deposit,9.0,,0,Transient,0.0,0,1
HB-010986,Resort Hotel,1,162,2025,April,15,13,2025-04-13,2,7,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,E,E,5,No Deposit,240.0,,0,Transient-Party,90.0,0,0
HB-074831,City Hotel,1,335,2023,September,37,17,2023-09-17,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,5.0,,0,Transient,85.0,0,0
HB-051074,City Hotel,1,68,2024,May,20,13,2024-05-13,1,2,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,140.4,0,0
HB-061142,City Hotel,1,17,2024,December,49,2,2024-12-02,2,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.29,0,1
HB-004591,Resort Hotel,1,136,2024,March,12,24,2024-03-24,0,3,2,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,46.0,0,0
HB-043506,City Hotel,0,41,2023,September,38,18,2023-09-18,2,3,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,74.4,0,0
HB-078806,City Hotel,0,14,2023,October,41,15,2023-10-15,0,2,1,0.0,0,BB,ROU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,99.0,,0,Transient-Party,100.0,0,0
HB-004566,Resort Hotel,0,136,2024,March,12,24,2024-03-24,0,3,2,0.0,0,Undefined,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,387.0,,0,Transient-Party,84.0,0,0
HB-074042,City Hotel,1,307,2023,August,33,20,2023-08-20,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-005053,Resort Hotel,0,183,2024,April,16,16,2024-04-16,1,1,1,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,1,No Deposit,298.0,,0,Transient-Party,54.5,0,0
HB-092791,City Hotel,0,56,2024,July,28,11,2024-07-11,1,0,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,88.01,0,0
HB-019392,Resort Hotel,0,7,2023,December,50,16,2023-12-16,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,F,1,No Deposit,,,0,Transient,38.0,0,3
HB-020561,Resort Hotel,0,57,2024,January,5,30,2024-01-30,2,2,2,1.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,63.0,0,1
HB-100582,City Hotel,0,32,2024,October,43,27,2024-10-27,0,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.0,0,1
HB-107116,City Hotel,0,137,2025,March,10,6,2025-03-06,1,1,1,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,A,1,No Deposit,37.0,,0,Transient-Party,65.0,0,0
HB-078426,City Hotel,0,5,2023,October,40,6,2023-10-06,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,151.33,0,0
HB-080311,City Hotel,1,33,2023,December,49,9,2023-12-09,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,44.0,,0,Transient,110.0,0,0
HB-074127,City Hotel,1,335,2023,September,37,17,2023-09-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-052958,City Hotel,1,71,2024,June,24,14,2024-06-14,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,120.0,0,0
HB-014958,Resort Hotel,0,18,2024,November,45,8,2024-11-08,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,9,A,C,0,No Deposit,270.0,,0,Transient,30.0,0,0
HB-078725,City Hotel,0,28,2023,October,41,12,2023-10-12,1,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,99.87,0,2
HB-074261,City Hotel,1,267,2023,July,28,11,2023-07-11,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-060049,City Hotel,1,62,2024,November,45,4,2024-11-04,1,2,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.2,0,2
HB-067066,City Hotel,1,206,2025,April,18,28,2025-04-28,0,2,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.5,0,3
HB-046234,City Hotel,0,22,2023,December,52,27,2023-12-27,2,0,2,2.0,0,BB,JPN,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,177.0,0,0
HB-087890,City Hotel,0,83,2024,April,17,25,2024-04-25,1,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.3,0,1
HB-043937,City Hotel,1,88,2023,September,39,26,2023-09-26,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-034166,Resort Hotel,0,195,2025,March,10,5,2025-03-05,4,6,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,D,D,0,No Deposit,273.0,,0,Transient-Party,62.28,0,0
HB-014463,Resort Hotel,0,23,2025,June,24,9,2025-06-09,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,140.0,0,1
HB-071862,City Hotel,1,255,2025,July,29,14,2025-07-14,1,2,2,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,141.3,0,0
HB-084127,City Hotel,0,99,2024,February,8,19,2024-02-19,0,1,1,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,A,0,No Deposit,,67.0,0,Transient-Party,81.0,0,0
HB-061242,City Hotel,1,1,2024,December,49,5,2024-12-05,3,5,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,77.03,0,1
HB-027315,Resort Hotel,0,204,2024,August,33,12,2024-08-12,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,2.0,,0,Contract,106.55,0,0
HB-105581,City Hotel,0,24,2025,February,6,5,2025-02-05,2,5,1,0.0,0,BB,MAR,Groups,TA/TO,0,0,0,A,A,1,No Deposit,,407.0,0,Transient-Party,75.0,0,0
HB-004784,Resort Hotel,0,169,2024,March,13,31,2024-03-31,1,3,1,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,2,Refundable,,223.0,0,Transient-Party,60.0,0,0
HB-097450,City Hotel,0,2,2024,September,37,15,2024-09-15,0,1,1,0.0,0,BB,CZE,Online TA,GDS,0,0,0,A,A,0,No Deposit,195.0,,0,Transient,163.0,0,0
HB-110362,City Hotel,0,279,2025,April,17,24,2025-04-24,1,2,1,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,109.8,0,1
HB-086028,City Hotel,0,1,2024,March,12,23,2024-03-23,0,3,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,211.0,0,0
HB-085342,City Hotel,0,20,2024,March,11,11,2024-03-11,1,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.0,0,1
HB-103063,City Hotel,0,157,2024,December,49,8,2024-12-08,0,3,3,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,83.0,,0,Transient-Party,92.65,0,0
HB-080893,City Hotel,0,73,2023,November,47,24,2023-11-24,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,27,Transient-Party,85.67,0,0
HB-041726,City Hotel,0,138,2023,August,34,22,2023-08-22,2,1,1,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,17.0,,0,Transient-Party,72.5,0,0
HB-102176,City Hotel,0,55,2024,November,47,23,2024-11-23,0,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,89.0,,0,Transient,74.88,0,0
HB-047504,City Hotel,1,18,2024,February,8,24,2024-02-24,0,4,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.0,0,1
HB-112639,City Hotel,0,174,2025,May,21,24,2025-05-24,0,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.8,0,1
HB-005694,Resort Hotel,1,203,2024,May,19,10,2024-05-10,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,248.0,,0,Transient-Party,46.0,0,0
HB-067679,City Hotel,1,31,2025,May,19,6,2025-05-06,1,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,169.0,0,1
HB-028556,Resort Hotel,0,22,2024,October,40,5,2024-10-05,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,251.0,,0,Transient,59.0,0,0
HB-081809,City Hotel,1,117,2024,February,9,29,2024-02-29,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,44,Transient,75.0,0,0
HB-034741,Resort Hotel,0,173,2025,March,13,30,2025-03-30,1,3,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient,89.9,1,4
HB-112871,City Hotel,0,54,2025,May,22,26,2025-05-26,1,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,121.6,0,1
HB-034934,Resort Hotel,0,14,2025,April,14,6,2025-04-06,0,3,2,0.0,0,BB,USA,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,110.0,0,0
HB-054900,City Hotel,0,230,2024,July,31,29,2024-07-29,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,7.0,,0,Transient,76.85,0,1
HB-000171,Resort Hotel,0,7,2023,July,27,6,2023-07-06,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,240.0,,0,Transient,98.0,0,2
HB-003717,Resort Hotel,0,90,2023,December,52,31,2023-12-31,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,66.02,0,0
HB-094048,City Hotel,0,6,2025,March,11,13,2025-03-13,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,2,E,E,0,No Deposit,,51.0,0,Transient,110.0,0,0
HB-090931,City Hotel,0,107,2024,June,23,3,2024-06-03,3,7,0,0.0,0,SC,FRA,Groups,TA/TO,0,0,0,A,K,3,No Deposit,37.0,,0,Transient-Party,0.0,0,0
HB-079024,City Hotel,0,0,2023,October,42,20,2023-10-20,0,0,1,0.0,0,BB,PRT,Online TA,TA/TO,1,0,0,A,F,1,No Deposit,9.0,,0,Contract,0.0,0,1
HB-077105,City Hotel,0,219,2023,September,36,4,2023-09-04,1,2,1,0.0,0,BB,SWE,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,76.67,0,0
HB-028442,Resort Hotel,0,8,2024,October,40,2,2024-10-02,1,0,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,136.0,1,1
HB-057423,City Hotel,1,24,2024,September,39,26,2024-09-26,1,1,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,0
HB-108405,City Hotel,0,76,2025,March,13,24,2025-03-24,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,102.2,0,1
HB-089470,City Hotel,0,189,2024,May,20,19,2024-05-19,0,3,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,65.0,0,0
HB-006351,Resort Hotel,1,151,2024,June,23,4,2024-06-04,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,99.0,0,2
HB-114836,City Hotel,0,396,2025,June,26,25,2025-06-25,2,0,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,122.4,0,1
HB-024416,Resort Hotel,0,123,2024,May,20,15,2024-05-15,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,85.2,1,2
HB-071815,City Hotel,1,414,2025,July,28,13,2025-07-13,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,B,1,No Deposit,6.0,,0,Transient-Party,80.0,0,0
HB-111851,City Hotel,0,6,2025,May,20,14,2025-05-14,2,1,1,0.0,0,BB,MEX,Groups,Corporate,0,0,0,A,A,0,No Deposit,,169.0,0,Transient-Party,110.0,0,0
HB-090582,City Hotel,0,118,2024,June,23,6,2024-06-06,1,1,1,0.0,0,BB,PRT,Offline TA/TO,Corporate,0,0,0,A,D,1,No Deposit,191.0,,0,Transient-Party,110.0,0,0
HB-011722,Resort Hotel,1,107,2025,May,22,27,2025-05-27,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,410.0,,0,Transient,45.5,0,0
HB-084711,City Hotel,0,1,2024,March,9,2,2024-03-02,0,1,1,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,104.0,1,2
HB-079158,City Hotel,0,5,2023,October,42,21,2023-10-21,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,3.0,,0,Transient-Party,0.0,0,0
HB-115830,City Hotel,0,169,2025,July,28,9,2025-07-09,2,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,74.61,0,1
HB-007431,Resort Hotel,1,126,2024,August,32,8,2024-08-08,3,7,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,218.0,0,0
HB-112267,City Hotel,0,99,2025,May,20,18,2025-05-18,1,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Contract,80.0,0,1
HB-115663,City Hotel,0,96,2025,July,28,7,2025-07-07,0,2,2,0.0,0,SC,RUS,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,120.0,0,1
HB-069071,City Hotel,1,181,2025,May,21,25,2025-05-25,0,2,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,130.0,0,0
HB-098541,City Hotel,0,98,2024,September,39,27,2024-09-27,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,95.0,0,1
HB-036265,Resort Hotel,0,156,2025,May,19,8,2025-05-08,2,5,2,0.0,0,HB,IRL,Groups,TA/TO,0,0,0,E,E,0,No Deposit,434.0,,0,Transient-Party,100.0,0,0
HB-102673,City Hotel,0,29,2024,December,49,2,2024-12-02,0,2,2,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,85.0,0,0
HB-115345,City Hotel,0,199,2025,July,27,2,2025-07-02,2,1,2,1.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,125.1,0,2
HB-033978,Resort Hotel,0,191,2025,February,8,23,2025-02-23,4,10,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,96.0,,0,Transient,52.0,1,1
HB-058890,City Hotel,1,605,2024,October,42,17,2024-10-17,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-058978,City Hotel,1,153,2024,October,42,19,2024-10-19,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,89.76,0,0
HB-044105,City Hotel,1,27,2023,September,39,30,2023-09-30,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,64.0,,21,Transient,108.0,0,0
HB-045460,City Hotel,0,59,2023,October,43,29,2023-10-29,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,72.25,0,2
HB-032351,Resort Hotel,0,2,2025,March,9,1,2025-03-01,0,1,2,0.0,0,BB,PRT,Corporate,Direct,1,1,1,A,A,1,No Deposit,,195.0,0,Transient,40.0,0,0
HB-106827,City Hotel,0,1,2025,March,10,3,2025-03-03,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient,0.0,0,0
HB-090518,City Hotel,0,247,2024,June,23,6,2024-06-06,1,1,2,0.0,0,HB,AUT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-035976,Resort Hotel,0,261,2025,April,18,30,2025-04-30,2,5,1,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,36.2,0,1
HB-090134,City Hotel,0,211,2024,May,22,31,2024-05-31,0,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,11.0,,0,Transient,68.69,0,0
HB-116938,City Hotel,0,176,2025,July,29,17,2025-07-17,3,7,2,1.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,136.8,0,2
HB-104790,City Hotel,0,34,2025,January,4,20,2025-01-20,0,2,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,77.0,0,1
HB-107661,City Hotel,0,7,2025,March,11,15,2025-03-15,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,F,1,No Deposit,,,0,Transient,65.0,0,0
HB-035598,Resort Hotel,0,31,2025,April,17,23,2025-04-23,2,4,1,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,74.0,0,0
HB-076981,City Hotel,0,177,2023,August,33,19,2023-08-19,0,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,76.5,0,2
HB-097110,City Hotel,0,38,2024,September,37,9,2024-09-09,1,2,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,170.1,0,1
HB-001810,Resort Hotel,0,46,2023,September,37,16,2023-09-16,0,1,2,0.0,0,BB,CHE,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,251.0,,0,Transient,62.0,0,0
HB-063088,City Hotel,1,85,2025,January,5,30,2025-01-30,1,2,2,2.0,0,BB,CHN,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,140.94,0,0
HB-107861,City Hotel,0,72,2025,March,12,17,2025-03-17,0,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,71.1,0,1
HB-060404,City Hotel,1,1,2024,November,45,10,2024-11-10,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,140.0,0,0
HB-057198,City Hotel,1,1,2024,September,38,20,2024-09-20,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,160.0,0,0
HB-115279,City Hotel,0,48,2025,July,27,3,2025-07-03,1,0,2,0.0,0,SC,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.0,0,1
HB-038442,Resort Hotel,0,33,2025,July,28,11,2025-07-11,2,5,2,0.0,0,BB,USA,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,241.86,1,0
HB-089481,City Hotel,0,189,2024,May,20,19,2024-05-19,0,3,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,65.0,0,0
HB-001849,Resort Hotel,0,110,2023,September,37,17,2023-09-17,1,3,1,0.0,0,BB,NLD,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient-Party,74.0,0,0
HB-008711,Resort Hotel,1,236,2024,October,41,9,2024-10-09,4,6,2,0.0,0,HB,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,273.0,,0,Transient-Party,63.45,0,0
HB-072019,City Hotel,1,217,2025,July,29,17,2025-07-17,1,5,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,111.0,0,2
HB-099282,City Hotel,0,180,2024,October,41,10,2024-10-10,1,0,1,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,98.1,0,1
HB-009986,Resort Hotel,1,169,2025,February,5,2,2025-02-02,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,37.8,0,2
HB-013132,Resort Hotel,1,242,2025,August,31,1,2025-08-01,2,5,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,153.75,0,0
HB-052365,City Hotel,1,275,2024,June,23,4,2024-06-04,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,5.0,,69,Transient,62.8,0,0
HB-013322,Resort Hotel,1,239,2025,August,32,9,2025-08-09,1,4,2,0.0,0,BB,CN,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,196.2,0,0
HB-118469,City Hotel,0,10,2025,August,34,18,2025-08-18,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,180.0,0,2
HB-003710,Resort Hotel,1,41,2023,December,52,30,2023-12-30,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,86.29,0,1
HB-059778,City Hotel,1,43,2024,November,44,1,2024-11-01,0,3,3,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,194.3,0,2
HB-108081,City Hotel,0,16,2025,May,20,14,2025-05-14,2,2,1,0.0,0,BB,IRL,Online TA,TA/TO,1,0,1,D,D,0,No Deposit,9.0,,0,Transient,160.0,0,3
HB-008634,Resort Hotel,1,393,2024,October,41,8,2024-10-08,2,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,68.0,,0,Transient,72.0,0,0
HB-029519,Resort Hotel,0,18,2024,October,44,29,2024-10-29,0,1,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,44.0,1,0
HB-024146,Resort Hotel,0,23,2024,May,19,7,2024-05-07,2,5,1,0.0,0,HB,AUT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,15.0,,0,Transient-Party,72.0,0,0
HB-021256,Resort Hotel,0,0,2024,February,8,23,2024-02-23,0,1,1,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,40.0,1,0
HB-006315,Resort Hotel,1,182,2024,June,23,3,2024-06-03,1,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,248.0,,0,Transient,97.3,0,0
HB-002186,Resort Hotel,1,170,2023,October,40,4,2023-10-04,4,8,2,0.0,0,BB,CN,Groups,TA/TO,0,0,0,A,A,0,Non Refund,15.0,,0,Transient,44.5,0,0
HB-014032,Resort Hotel,0,6,2023,September,38,23,2023-09-23,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,1,A,A,0,No Deposit,240.0,,0,Transient,72.0,0,1
HB-014869,Resort Hotel,1,289,2023,November,47,26,2023-11-26,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,240.0,,0,Transient,36.0,0,0
HB-076568,City Hotel,1,207,2023,September,39,29,2023-09-29,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,20.0,,0,Transient,48.0,0,0
HB-057700,City Hotel,1,267,2024,September,40,30,2024-09-30,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,26.0,,0,Transient,95.0,0,0
HB-013622,Resort Hotel,1,209,2025,August,34,23,2025-08-23,2,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,158.0,0,1
HB-020653,Resort Hotel,0,1,2024,February,5,4,2024-02-04,0,3,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,242.0,,0,Transient-Party,48.0,0,1
HB-081569,City Hotel,1,192,2024,May,19,12,2024-05-12,0,3,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,39.0,,42,Transient,135.0,0,0
HB-069585,City Hotel,1,212,2025,June,23,2,2025-06-02,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,20.0,,0,Transient-Party,105.0,0,0
HB-105768,City Hotel,0,67,2025,February,7,12,2025-02-12,2,1,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,72.0,0,0
HB-078695,City Hotel,0,1,2024,January,1,5,2024-01-05,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,6,A,A,0,No Deposit,,40.0,0,Transient,66.0,0,0
HB-101765,City Hotel,0,52,2024,November,46,14,2024-11-14,1,3,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,83.0,,0,Transient,82.08,0,0
HB-072134,City Hotel,1,423,2025,July,30,22,2025-07-22,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,80.0,0,0
HB-039853,Resort Hotel,0,0,2025,August,35,30,2025-08-30,0,0,2,0.0,0,BB,PRT,Online TA,TA/TO,1,0,0,A,A,0,No Deposit,306.0,,0,Transient,0.0,0,0
HB-112299,City Hotel,0,13,2025,May,20,16,2025-05-16,2,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,7.0,,0,Transient,194.34,0,2
HB-069630,City Hotel,1,212,2025,June,23,2,2025-06-02,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,20.0,,0,Transient-Party,105.0,0,0
HB-101284,City Hotel,0,146,2024,November,45,6,2024-11-06,2,2,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,161.33,0,1
HB-062444,City Hotel,1,38,2025,January,3,14,2025-01-14,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,Non Refund,,67.0,0,Transient,75.0,0,0
HB-076753,City Hotel,0,0,2023,August,32,7,2023-08-07,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.0,0,0
HB-025057,Resort Hotel,0,0,2024,June,24,12,2024-06-12,1,0,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,131.0,1,0
HB-073040,City Hotel,1,51,2025,August,33,12,2025-08-12,2,4,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,3
HB-084503,City Hotel,0,0,2024,February,9,26,2024-02-26,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,89.0,0,0
HB-064058,City Hotel,1,121,2025,February,9,27,2025-02-27,1,3,2,1.0,0,BB,BEL,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,147.9,0,2
HB-055983,City Hotel,1,48,2024,August,35,26,2024-08-26,0,1,3,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,168.3,0,1
HB-060702,City Hotel,1,64,2024,November,47,18,2024-11-18,1,2,1,0.0,0,BB,LUX,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.0,0,3
HB-107569,City Hotel,0,4,2025,March,11,13,2025-03-13,1,1,1,0.0,0,BB,DEU,Direct,Direct,0,0,0,A,A,2,No Deposit,,,0,Transient,88.2,0,0
HB-034004,Resort Hotel,0,107,2025,March,10,9,2025-03-09,0,2,1,0.0,0,Undefined,CN,Groups,TA/TO,0,0,0,E,E,1,No Deposit,96.0,,0,Transient-Party,72.0,0,0
HB-108680,City Hotel,0,21,2025,March,13,26,2025-03-26,2,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,107.1,0,0
HB-085202,City Hotel,0,94,2024,May,22,30,2024-05-30,1,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,17,E,E,0,Non Refund,,51.0,0,Transient-Party,106.0,0,0
HB-012856,Resort Hotel,1,41,2025,July,29,20,2025-07-20,2,3,3,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,314.0,,0,Transient,209.58,0,0
HB-061819,City Hotel,1,355,2024,December,52,26,2024-12-26,2,5,2,0.0,0,BB,JEY,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,87.31,0,0
HB-114213,City Hotel,0,121,2025,June,25,18,2025-06-18,2,0,2,0.0,0,BB,RUS,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Group,99.0,0,4
HB-047931,City Hotel,1,36,2024,March,10,10,2024-03-10,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,81.9,0,2
HB-048206,City Hotel,0,90,2024,March,12,18,2024-03-18,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,78.3,0,0
HB-095444,City Hotel,0,11,2024,August,34,19,2024-08-19,0,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient,127.6,0,1
HB-004735,Resort Hotel,1,123,2024,March,13,30,2024-03-30,2,5,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,110.71,0,0
HB-031007,Resort Hotel,0,72,2024,December,49,5,2024-12-05,1,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,242.0,,0,Transient-Party,47.85,0,1
HB-103033,City Hotel,0,22,2024,December,49,7,2024-12-07,0,4,2,2.0,0,BB,ESP,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,146.5,0,0
HB-009886,Resort Hotel,1,40,2025,January,3,16,2025-01-16,1,2,1,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,55.0,0,0
HB-113547,City Hotel,0,11,2025,June,23,4,2025-06-04,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,83.0,,0,Transient,154.16,0,0
HB-056248,City Hotel,1,69,2024,September,35,1,2024-09-01,2,6,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,123.98,0,0
HB-011688,Resort Hotel,1,162,2025,May,21,25,2025-05-25,2,5,2,1.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Refundable,,223.0,0,Transient-Party,10.0,0,0
HB-070557,City Hotel,1,91,2025,June,25,18,2025-06-18,2,1,2,0.0,0,SC,ISR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-013206,Resort Hotel,1,91,2025,August,32,4,2025-08-04,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,184.0,0,0
HB-078624,City Hotel,0,282,2023,October,41,10,2023-10-10,2,1,2,0.0,0,BB,SWE,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,76.67,0,0
HB-053094,City Hotel,1,188,2024,June,24,15,2024-06-15,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,39,Transient,130.0,0,0
HB-008033,Resort Hotel,1,211,2024,September,36,7,2024-09-07,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,D,D,0,Non Refund,1.0,,0,Transient,89.0,0,0
HB-016213,Resort Hotel,0,68,2023,August,33,19,2023-08-19,2,7,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,149.0,,0,Transient,107.0,0,0
HB-119137,City Hotel,0,223,2025,August,34,23,2025-08-23,2,5,3,0.0,0,HB,AUT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,83.0,,0,Transient,154.7,0,1
HB-118770,City Hotel,0,141,2025,August,34,23,2025-08-23,0,2,2,0.0,0,BB,USA,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,150.0,0,2
HB-003186,Resort Hotel,0,24,2023,November,47,21,2023-11-21,0,1,2,0.0,1,BB,PRT,Corporate,Corporate,0,0,0,A,C,1,No Deposit,,342.0,0,Transient-Party,32.0,0,1
HB-115878,City Hotel,0,51,2025,July,28,7,2025-07-07,2,3,2,0.0,0,SC,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,149.0,0,2
HB-056853,City Hotel,1,433,2024,September,37,15,2024-09-15,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-116507,City Hotel,0,150,2025,July,29,19,2025-07-19,0,2,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,98.1,0,1
HB-096952,City Hotel,0,52,2024,September,37,9,2024-09-09,0,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.1,0,1
HB-046384,City Hotel,1,15,2023,December,52,30,2023-12-30,1,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,123.0,0,2
HB-075655,City Hotel,1,290,2023,August,31,3,2023-08-03,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-084028,City Hotel,0,8,2024,February,7,16,2024-02-16,0,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,1,1
HB-037622,Resort Hotel,0,0,2025,June,26,23,2025-06-23,0,1,2,0.0,0,BB,SWE,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,138.0,1,0
HB-082484,City Hotel,0,96,2023,December,52,29,2023-12-29,0,3,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,70.0,0,0
HB-002694,Resort Hotel,1,51,2023,October,43,26,2023-10-26,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,8.0,,0,Contract,48.6,0,1
HB-056719,City Hotel,1,44,2024,September,37,11,2024-09-11,2,1,2,1.0,0,BB,TUR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,152.1,0,0
HB-029444,Resort Hotel,0,194,2024,October,43,22,2024-10-22,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,430.0,,0,Transient,82.28,0,0
HB-089146,City Hotel,0,5,2024,May,20,15,2024-05-15,2,1,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,1,Transient,125.0,0,0
HB-105965,City Hotel,0,70,2025,February,7,15,2025-02-15,0,4,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,B,0,No Deposit,,242.0,0,Transient-Party,78.0,0,0
HB-108111,City Hotel,0,19,2025,March,12,19,2025-03-19,2,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,100.3,0,1
HB-087809,City Hotel,0,65,2024,April,17,24,2024-04-24,2,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,118.8,0,1
HB-118396,City Hotel,0,70,2025,August,33,15,2025-08-15,0,4,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,85.0,,0,Transient,98.1,0,0
HB-065504,City Hotel,1,112,2025,April,14,4,2025-04-04,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,,385.0,0,Transient,95.0,0,0
HB-083067,City Hotel,0,50,2024,January,2,14,2024-01-14,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,20.0,,43,Transient-Party,52.0,0,2
HB-053858,City Hotel,1,179,2024,July,27,1,2024-07-01,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,65.0,0,0
HB-077242,City Hotel,0,327,2023,September,36,9,2023-09-09,2,4,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,88.0,0,0
HB-116709,City Hotel,0,423,2025,July,30,22,2025-07-22,1,1,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,95.5,0,0
HB-111907,City Hotel,0,34,2025,May,19,10,2025-05-10,2,6,1,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,124.9,0,1
HB-088058,City Hotel,0,0,2024,April,18,29,2024-04-29,0,1,2,1.0,0,BB,RUS,Direct,Direct,0,0,0,A,C,0,No Deposit,,,0,Transient,197.0,0,0
HB-096529,City Hotel,0,308,2024,September,35,1,2024-09-01,0,3,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,68.69,0,0
HB-071962,City Hotel,1,156,2025,July,29,16,2025-07-16,2,1,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,0
HB-072446,City Hotel,1,296,2025,July,31,28,2025-07-28,2,3,2,2.0,0,SC,DOM,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,0
HB-018478,Resort Hotel,0,6,2023,November,46,16,2023-11-16,1,4,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,26.0,0,0
HB-095354,City Hotel,0,0,2024,August,33,17,2024-08-17,0,1,2,0.0,0,BB,AUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,150.0,0,1
HB-032086,Resort Hotel,0,0,2025,January,2,9,2025-01-09,2,5,2,0.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,171.0,,0,Transient,70.0,0,0
HB-072161,City Hotel,1,176,2025,July,30,22,2025-07-22,2,2,2,1.0,0,BB,LUX,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.5,0,0
HB-090305,City Hotel,0,188,2024,June,22,2,2024-06-02,0,3,2,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,118.0,,0,Transient,80.75,0,0
HB-117016,City Hotel,0,206,2025,July,30,27,2025-07-27,0,2,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,130.5,0,2
HB-042734,City Hotel,0,69,2023,September,36,9,2023-09-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-044311,City Hotel,1,89,2023,October,40,3,2023-10-03,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-083102,City Hotel,0,12,2024,January,3,16,2024-01-16,2,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,61.0,0,0
HB-077262,City Hotel,1,5,2023,September,38,20,2023-09-20,2,0,2,0.0,0,BB,PRT,Corporate,Corporate,1,1,0,A,A,0,Non Refund,78.0,,0,Transient,100.0,0,0
HB-099672,City Hotel,0,377,2024,October,42,14,2024-10-14,0,2,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,90.0,0,0
HB-083976,City Hotel,0,13,2024,March,9,2,2024-03-02,0,3,1,0.0,0,BB,FRA,Corporate,Corporate,1,0,1,A,A,1,No Deposit,91.0,,0,Transient,80.0,0,0
HB-014570,Resort Hotel,0,181,2025,August,32,4,2025-08-04,2,5,3,0.0,0,HB,PRT,Online TA,Direct,0,0,1,A,A,1,No Deposit,242.0,,0,Transient,230.84,0,2
HB-091446,City Hotel,0,86,2024,June,25,17,2024-06-17,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.9,0,1
HB-098692,City Hotel,0,223,2024,September,39,29,2024-09-29,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,92.28,0,1
HB-099057,City Hotel,0,38,2024,October,40,6,2024-10-06,0,3,2,0.0,0,BB,SWE,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,109.0,0,0
HB-095020,City Hotel,0,8,2024,August,32,11,2024-08-11,0,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,139.0,0,2
HB-112704,City Hotel,0,240,2025,May,21,25,2025-05-25,0,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,138.6,0,2
HB-112452,City Hotel,0,87,2025,May,21,22,2025-05-22,1,1,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,475.0,,0,Transient-Party,126.0,0,0
HB-058071,City Hotel,1,275,2024,October,40,5,2024-10-05,1,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,44.0,,0,Transient,90.0,0,0
HB-009576,Resort Hotel,1,50,2024,December,50,15,2024-12-15,0,3,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,43.0,0,0
HB-083480,City Hotel,0,5,2024,February,5,3,2024-02-03,0,1,3,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.0,0,1
HB-081081,City Hotel,0,68,2023,November,48,29,2023-11-29,2,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Transient,60.0,0,0
HB-091699,City Hotel,0,265,2024,June,26,24,2024-06-24,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-076543,City Hotel,1,199,2023,September,38,21,2023-09-21,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,20.0,,0,Transient,48.0,0,0
HB-013444,Resort Hotel,1,126,2025,August,33,15,2025-08-15,1,5,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,230.0,0,1
HB-108778,City Hotel,0,123,2025,March,14,31,2025-03-31,0,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,0
HB-088148,City Hotel,0,127,2024,April,17,28,2024-04-28,1,3,2,0.0,0,BB,USA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,90.0,0,0
HB-007101,Resort Hotel,1,114,2024,July,29,21,2024-07-21,2,3,2,2.0,0,BB,USA,Online TA,TA/TO,0,0,0,G,G,1,No Deposit,240.0,,0,Transient,240.0,0,0
HB-030096,Resort Hotel,0,50,2024,November,45,9,2024-11-09,1,4,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,6.0,,0,Transient,52.4,0,0
HB-109489,City Hotel,0,74,2025,April,15,9,2025-04-09,2,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,1
HB-019503,Resort Hotel,0,24,2023,December,51,19,2023-12-19,2,3,2,1.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,314.0,,0,Transient,91.9,0,1
HB-068477,City Hotel,1,67,2025,May,20,18,2025-05-18,0,3,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,144.0,0,0
HB-073998,City Hotel,1,293,2023,August,31,6,2023-08-06,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-095500,City Hotel,0,20,2024,August,34,19,2024-08-19,0,1,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,F,G,0,No Deposit,9.0,,0,Transient,240.0,1,1
HB-085152,City Hotel,0,53,2024,March,10,6,2024-03-06,2,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,65.75,0,0
HB-061520,City Hotel,1,6,2024,December,50,15,2024-12-15,1,3,2,0.0,0,SC,IDN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,66.3,0,0
HB-029638,Resort Hotel,0,141,2024,October,42,19,2024-10-19,4,10,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,314.0,,0,Transient,79.66,0,1
HB-095790,City Hotel,0,121,2024,August,34,23,2024-08-23,0,1,2,2.0,0,BB,BEL,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,198.9,1,2
HB-003707,Resort Hotel,0,165,2023,December,52,30,2023-12-30,0,4,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,308.0,,122,Transient-Party,84.5,0,0
HB-007247,Resort Hotel,1,26,2024,July,31,30,2024-07-30,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,200.43,0,1
HB-058899,City Hotel,1,605,2024,October,42,17,2024-10-17,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-086272,City Hotel,0,2,2025,March,13,29,2025-03-29,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,10,A,A,0,No Deposit,,219.0,0,Transient,80.0,0,1
HB-101722,City Hotel,0,61,2024,November,46,12,2024-11-12,2,3,3,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,92.65,0,2
HB-108191,City Hotel,0,27,2025,March,12,19,2025-03-19,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,76.23,0,0
HB-053796,City Hotel,1,358,2024,June,26,30,2024-06-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-021032,Resort Hotel,0,9,2024,February,7,13,2024-02-13,2,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-033906,Resort Hotel,0,7,2025,March,9,2,2025-03-02,1,3,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,D,D,0,No Deposit,,223.0,0,Transient-Party,47.0,0,0
HB-054616,City Hotel,1,379,2024,July,29,21,2024-07-21,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-084602,City Hotel,0,1,2024,February,9,27,2024-02-27,1,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,117.0,0,0
HB-102858,City Hotel,0,6,2024,December,49,6,2024-12-06,0,2,1,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,10.0,,0,Transient,79.2,0,0
HB-118972,City Hotel,0,60,2025,August,35,26,2025-08-26,1,1,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,85.0,,0,Transient,122.4,0,1
HB-015160,Resort Hotel,1,244,2023,September,35,2,2023-09-02,2,5,2,0.0,0,BB,IRL,Groups,TA/TO,0,24,0,A,A,0,No Deposit,96.0,,0,Transient-Party,8.0,0,0
HB-019146,Resort Hotel,0,1,2023,December,49,8,2023-12-08,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,241.0,,0,Group,36.96,0,0
HB-083627,City Hotel,0,13,2024,February,6,6,2024-02-06,2,1,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,130.0,0,2
HB-048175,City Hotel,1,91,2024,March,12,18,2024-03-18,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,20,Transient,75.0,0,0
HB-108872,City Hotel,0,62,2025,March,14,31,2025-03-31,1,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,110.4,0,0
HB-023177,Resort Hotel,0,72,2024,April,15,9,2024-04-09,2,6,1,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,96.0,,0,Transient-Party,36.0,0,0
HB-025551,Resort Hotel,0,204,2024,June,26,25,2024-06-25,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,68.43,1,0
HB-023613,Resort Hotel,0,12,2024,April,17,27,2024-04-27,0,3,2,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,A,A,1,No Deposit,385.0,,0,Transient-Party,85.33,0,0
HB-014499,Resort Hotel,0,1,2023,November,47,25,2023-11-25,0,1,1,0.0,0,BB,,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,78.0,,0,Transient,25.0,0,0
HB-057514,City Hotel,0,418,2024,September,39,26,2024-09-26,1,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,132.0,,223,Transient,107.0,0,0
HB-024547,Resort Hotel,0,129,2024,May,21,22,2024-05-22,2,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,240.0,,0,Transient,71.7,1,2
HB-107737,City Hotel,0,47,2025,March,11,13,2025-03-13,1,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-119236,City Hotel,0,189,2025,August,35,29,2025-08-29,0,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,B,1,No Deposit,42.0,,0,Transient,80.1,0,1
HB-086550,City Hotel,0,55,2024,April,14,3,2024-04-03,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,28.0,,0,Transient-Party,75.0,0,1
HB-014542,Resort Hotel,0,14,2023,September,37,17,2023-09-17,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,H,1,No Deposit,,,0,Transient,80.1,0,0
HB-056565,City Hotel,1,433,2024,September,36,8,2024-09-08,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,70.0,0,0
HB-114832,City Hotel,0,93,2025,June,25,22,2025-06-22,2,3,2,0.0,0,BB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,85.0,0,0
HB-066266,City Hotel,1,66,2025,April,16,16,2025-04-16,1,0,2,0.0,0,BB,CYP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-052922,City Hotel,1,71,2024,June,24,14,2024-06-14,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,120.0,0,0
HB-110075,City Hotel,0,62,2025,April,16,18,2025-04-18,0,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,135.0,0,2
HB-119004,City Hotel,0,164,2025,August,34,23,2025-08-23,1,4,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.5,0,2
HB-069057,City Hotel,1,181,2025,May,21,25,2025-05-25,0,2,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,130.0,0,0
HB-103262,City Hotel,0,12,2024,December,50,15,2024-12-15,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,117.0,0,0
HB-096484,City Hotel,0,2,2024,August,35,31,2024-08-31,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,139.0,0,1
HB-079019,City Hotel,0,4,2023,October,42,19,2023-10-19,1,0,1,0.0,0,BB,FIN,Online TA,Corporate,0,0,0,A,D,0,No Deposit,,47.0,0,Transient,90.0,0,0
HB-017026,Resort Hotel,0,239,2023,September,38,19,2023-09-19,1,1,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,F,0,No Deposit,248.0,,0,Transient-Party,80.0,0,0
HB-110798,City Hotel,0,9,2025,April,18,29,2025-04-29,2,1,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,141.0,0,3
HB-100708,City Hotel,0,130,2024,October,44,29,2024-10-29,2,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,104.4,0,2
HB-058905,City Hotel,1,605,2024,October,42,17,2024-10-17,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-004772,Resort Hotel,0,169,2024,March,13,31,2024-03-31,1,3,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Refundable,,223.0,0,Transient-Party,66.0,0,0
HB-020174,Resort Hotel,0,1,2024,May,19,12,2024-05-12,0,0,2,0.0,0,BB,PRT,Corporate,Corporate,1,0,2,A,E,1,No Deposit,,99.0,0,Transient,0.0,0,0
HB-077093,City Hotel,0,219,2023,September,36,4,2023-09-04,1,2,1,0.0,0,BB,SWE,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,76.67,0,1
HB-083724,City Hotel,0,1,2024,February,6,9,2024-02-09,0,1,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,109.0,0,0
HB-050796,City Hotel,1,33,2024,May,19,8,2024-05-08,2,1,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,121.5,0,0
HB-074695,City Hotel,1,365,2023,October,42,17,2023-10-17,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-085370,City Hotel,0,50,2024,March,11,11,2024-03-11,1,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,87.3,0,1
HB-059158,City Hotel,1,240,2024,October,43,21,2024-10-21,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,110.0,0,0
HB-049878,City Hotel,0,265,2024,April,16,20,2024-04-20,0,4,2,0.0,0,BB,AUT,Groups,TA/TO,0,0,0,A,B,0,No Deposit,30.0,,176,Transient-Party,99.0,0,0
HB-006572,Resort Hotel,1,250,2024,June,25,18,2024-06-18,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,99.0,0,2
HB-041950,City Hotel,0,119,2023,August,34,27,2023-08-27,2,6,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,82.87,0,1
HB-036319,Resort Hotel,0,1,2025,May,20,15,2025-05-15,1,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,F,0,No Deposit,240.0,,0,Transient,109.5,1,2
HB-116700,City Hotel,0,423,2025,July,30,22,2025-07-22,1,1,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,95.5,0,0
HB-002145,Resort Hotel,1,4,2023,October,40,3,2023-10-03,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,175.0,,0,Transient,58.0,0,1
HB-017280,Resort Hotel,0,272,2023,September,39,30,2023-09-30,0,3,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,C,0,No Deposit,256.0,,0,Transient-Party,73.0,0,0
HB-033112,Resort Hotel,0,1,2025,February,7,14,2025-02-14,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,330.0,,0,Transient-Party,30.0,0,0
HB-040004,Resort Hotel,0,51,2025,August,35,31,2025-08-31,2,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,116.5,0,0
HB-115540,City Hotel,0,314,2025,July,27,5,2025-07-05,0,2,2,0.0,0,BB,AUS,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,103.5,0,3
HB-024737,Resort Hotel,0,179,2024,June,22,1,2024-06-01,0,1,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,F,0,No Deposit,251.0,,0,Transient-Party,78.0,0,0
HB-105620,City Hotel,0,9,2025,February,6,8,2025-02-08,0,4,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,B,A,1,No Deposit,14.0,,0,Transient,91.1,0,0
HB-039389,Resort Hotel,0,197,2025,August,33,13,2025-08-13,2,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient-Party,110.7,0,0
HB-085562,City Hotel,0,22,2024,March,11,16,2024-03-16,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,1,No Deposit,213.0,,0,Transient-Party,89.0,0,0
HB-011453,Resort Hotel,1,302,2025,May,19,9,2025-05-09,0,4,2,0.0,0,HB,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,81.0,0,0
HB-079061,City Hotel,0,36,2023,October,42,20,2023-10-20,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,9.0,,0,Contract,96.3,0,1
HB-070745,City Hotel,1,249,2025,June,25,21,2025-06-21,0,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,149.4,0,1
HB-032846,Resort Hotel,0,10,2025,February,6,3,2025-02-03,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,36.61,0,1
HB-044438,City Hotel,1,97,2023,October,40,5,2023-10-05,1,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,140.0,0,0
HB-022834,Resort Hotel,0,31,2024,April,14,2,2024-04-02,2,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,71.56,0,1
HB-053258,City Hotel,1,245,2024,June,25,17,2024-06-17,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,0,Transient,75.0,0,0
HB-018060,Resort Hotel,0,0,2024,October,44,29,2024-10-29,0,1,2,0.0,0,BB,PRT,Direct,Direct,1,0,1,A,H,0,No Deposit,,,0,Transient,38.0,0,0
HB-071152,City Hotel,1,215,2025,June,26,28,2025-06-28,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-113178,City Hotel,0,170,2025,June,22,1,2025-06-01,0,3,2,0.0,0,HB,ARG,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,144.37,0,0
HB-023461,Resort Hotel,0,172,2024,April,16,18,2024-04-18,3,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,147.0,,0,Transient-Party,66.42,0,1
HB-087295,City Hotel,0,77,2024,April,15,14,2024-04-14,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.3,0,1
HB-053048,City Hotel,1,188,2024,June,24,15,2024-06-15,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,39,Transient,130.0,0,0
HB-050347,City Hotel,1,443,2024,April,18,29,2024-04-29,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,65.0,0,0
HB-054397,City Hotel,1,160,2024,July,28,14,2024-07-14,0,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.5,0,0
HB-100251,City Hotel,0,0,2024,October,43,21,2024-10-21,2,2,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,106.25,0,2
HB-075043,City Hotel,1,264,2023,July,27,8,2023-07-08,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-033155,Resort Hotel,0,10,2025,February,8,20,2025-02-20,1,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,1,A,A,0,No Deposit,146.0,,0,Transient,32.0,0,0
HB-080347,City Hotel,1,15,2023,December,48,1,2023-12-01,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,1,1,0,A,A,0,No Deposit,10.0,,0,Transient,69.0,0,0
HB-004193,Resort Hotel,1,74,2024,February,9,26,2024-02-26,1,2,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,68.0,,0,Transient,70.0,0,0
HB-038486,Resort Hotel,0,144,2025,July,29,16,2025-07-16,2,2,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,410.0,,0,Transient,118.5,0,0
HB-040817,City Hotel,0,1,2023,August,32,8,2023-08-08,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,75.0,0,2
HB-068822,City Hotel,1,183,2025,May,21,20,2025-05-20,2,5,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,175.11,0,0
HB-111202,City Hotel,0,7,2025,May,19,5,2025-05-05,1,2,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,100.0,0,1
HB-061452,City Hotel,1,18,2024,December,50,11,2024-12-11,2,4,1,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,96.9,0,0
HB-033157,Resort Hotel,0,94,2025,February,7,13,2025-02-13,1,3,2,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,152.0,,0,Transient-Party,62.0,0,0
HB-083951,City Hotel,0,11,2024,February,7,15,2024-02-15,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,1
HB-116325,City Hotel,0,168,2025,July,29,15,2025-07-15,2,1,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,114.07,0,2
HB-002629,Resort Hotel,1,148,2023,October,43,24,2023-10-24,0,1,1,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,39.0,0,0
HB-028594,Resort Hotel,0,32,2024,October,40,3,2024-10-03,1,3,2,2.0,0,BB,IRL,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,170.5,0,1
HB-021292,Resort Hotel,0,0,2024,February,8,22,2024-02-22,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient-Party,60.0,0,2
HB-067988,City Hotel,1,19,2025,May,19,10,2025-05-10,2,7,3,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,201.0,0,0
HB-040165,City Hotel,0,96,2023,July,28,11,2023-07-11,2,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-032916,Resort Hotel,0,1,2025,February,6,7,2025-02-07,0,2,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient,86.0,1,1
HB-029220,Resort Hotel,0,9,2024,October,43,23,2024-10-23,0,0,2,0.0,0,BB,PRT,Groups,Corporate,0,0,0,A,G,5,No Deposit,,,0,Transient-Party,0.0,0,1
HB-068225,City Hotel,1,164,2025,May,20,15,2025-05-15,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-018449,Resort Hotel,0,0,2023,November,46,19,2023-11-19,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,43.2,0,1
HB-004778,Resort Hotel,1,169,2024,March,13,31,2024-03-31,1,3,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Refundable,,223.0,0,Transient-Party,46.0,0,0
HB-102479,City Hotel,0,0,2024,November,48,28,2024-11-28,1,1,2,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,4.5,0,0
HB-001581,Resort Hotel,0,67,2023,September,36,4,2023-09-04,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,40.0,,0,Transient,97.5,0,0
HB-011107,Resort Hotel,1,213,2025,April,16,19,2025-04-19,0,4,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,109.8,0,2
HB-018730,Resort Hotel,0,10,2023,November,47,23,2023-11-23,1,4,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,196.0,,0,Transient,58.0,0,0
HB-118253,City Hotel,0,190,2025,August,33,12,2025-08-12,2,3,2,3.0,0,BB,NOR,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,8.0,,0,Transient,326.5,0,2
HB-014164,Resort Hotel,0,134,2025,April,15,13,2025-04-13,0,3,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,3,No Deposit,3.0,,0,Transient-Party,136.2,0,1
HB-035235,Resort Hotel,0,237,2025,April,15,13,2025-04-13,1,3,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,80.85,0,0
HB-115882,City Hotel,0,30,2025,July,28,9,2025-07-09,2,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,138.33,0,0
HB-010547,Resort Hotel,1,168,2025,March,11,14,2025-03-14,0,5,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,37.8,0,1
HB-029120,Resort Hotel,0,259,2024,October,42,14,2024-10-14,2,5,1,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,D,1,No Deposit,273.0,,0,Transient-Party,47.79,0,0
HB-057558,City Hotel,1,32,2024,September,39,27,2024-09-27,0,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,154.0,0,1
HB-108595,City Hotel,0,71,2025,March,13,27,2025-03-27,1,2,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,74.84,0,1
HB-114862,City Hotel,0,0,2025,June,26,27,2025-06-27,0,1,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,102.0,0,0
HB-031945,Resort Hotel,0,2,2025,January,4,26,2025-01-26,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,1,0,1,A,D,0,No Deposit,240.0,,0,Transient,43.0,0,0
HB-068200,City Hotel,1,104,2025,May,20,15,2025-05-15,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-106469,City Hotel,0,134,2025,February,9,25,2025-02-25,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,75.0,0,0
HB-011301,Resort Hotel,1,308,2025,May,18,1,2025-05-01,3,6,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,82.8,0,0
HB-066531,City Hotel,1,99,2025,April,17,21,2025-04-21,1,2,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,172.8,0,0
HB-027233,Resort Hotel,0,112,2024,August,33,18,2024-08-18,2,3,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,127.0,,0,Transient,171.2,0,1
HB-065157,City Hotel,1,166,2025,March,13,25,2025-03-25,2,2,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.4,0,1
HB-041359,City Hotel,0,16,2023,August,33,15,2023-08-15,1,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,B,0,No Deposit,17.0,,0,Transient-Party,104.0,0,0
HB-119177,City Hotel,0,5,2025,August,35,29,2025-08-29,0,2,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,4,No Deposit,19.0,,0,Transient-Party,104.0,0,0
HB-098897,City Hotel,0,39,2024,October,40,3,2024-10-03,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,118.0,0,0
HB-021335,Resort Hotel,0,8,2025,April,14,6,2025-04-06,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,511.0,0,Transient,45.0,0,0
HB-071215,City Hotel,1,123,2025,June,26,29,2025-06-29,2,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,120.06,0,0
HB-042010,City Hotel,0,145,2023,August,35,29,2023-08-29,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-057049,City Hotel,1,315,2024,September,38,17,2024-09-17,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,38,Transient-Party,65.0,0,0
HB-051896,City Hotel,0,316,2024,May,21,26,2024-05-26,0,3,2,0.0,0,BB,AUT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,110.0,0,0
HB-063555,City Hotel,1,64,2025,February,7,14,2025-02-14,0,1,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,140.4,0,2
HB-089259,City Hotel,0,126,2024,May,20,15,2024-05-15,2,2,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,107.95,0,3
HB-000664,Resort Hotel,1,42,2023,July,30,24,2023-07-24,3,7,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,95.0,,0,Transient,107.0,0,0
HB-002957,Resort Hotel,1,241,2023,November,45,7,2023-11-07,2,6,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,66.0,0,1
HB-014280,Resort Hotel,0,2,2024,June,23,9,2024-06-09,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,3,A,A,0,No Deposit,,,0,Transient,107.1,0,0
HB-073845,City Hotel,1,307,2023,August,33,20,2023-08-20,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-066286,City Hotel,1,128,2025,April,16,16,2025-04-16,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,0,Transient,100.0,0,0
HB-010295,Resort Hotel,1,19,2025,February,9,25,2025-02-25,1,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,62.0,0,3
HB-067794,City Hotel,1,88,2025,May,19,7,2025-05-07,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,89.1,0,0
HB-056220,City Hotel,1,419,2024,September,35,1,2024-09-01,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-084385,City Hotel,0,0,2024,February,8,24,2024-02-24,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.0,0,0
HB-075898,City Hotel,1,274,2023,July,29,18,2023-07-18,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-093927,City Hotel,0,130,2024,July,30,26,2024-07-26,0,3,3,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,22.0,,0,Transient,96.9,0,0
HB-058202,City Hotel,1,71,2024,October,41,7,2024-10-07,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,101.87,0,0
HB-054573,City Hotel,1,384,2024,July,29,20,2024-07-20,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,65.0,0,0
HB-077767,City Hotel,1,0,2023,September,39,26,2023-09-26,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,1,0,0,D,D,0,No Deposit,9.0,,0,Transient,180.0,0,2
HB-097957,City Hotel,0,1,2024,September,38,22,2024-09-22,0,1,1,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,185.0,0,2
HB-049618,City Hotel,1,1,2024,April,16,16,2024-04-16,0,1,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,147.0,0,1
HB-063554,City Hotel,1,63,2025,February,7,14,2025-02-14,0,1,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,1
HB-032829,Resort Hotel,0,145,2025,February,6,4,2025-02-04,2,1,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,242.0,,0,Transient,46.8,0,2
HB-020074,Resort Hotel,0,0,2025,January,2,9,2025-01-09,1,0,2,2.0,0,BB,PRT,Online TA,TA/TO,1,0,2,G,G,0,No Deposit,240.0,,0,Transient,95.0,1,2
HB-054474,City Hotel,1,25,2024,July,29,17,2024-07-17,1,0,2,0.0,0,SC,BRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,139.0,0,0
HB-040208,City Hotel,1,82,2023,July,28,16,2023-07-16,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,0
HB-105355,City Hotel,0,69,2025,February,5,2,2025-02-02,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.6,0,1
HB-083818,City Hotel,0,24,2024,February,6,11,2024-02-11,0,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,27.0,,0,Transient,46.67,0,1
HB-027186,Resort Hotel,0,88,2024,August,33,18,2024-08-18,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,193.0,1,2
HB-107978,City Hotel,0,0,2025,March,12,21,2025-03-21,0,0,0,0.0,0,SC,GBR,Online TA,TA/TO,1,0,0,A,A,2,No Deposit,9.0,,0,Transient,0.0,1,1
HB-026330,Resort Hotel,0,1,2024,July,30,28,2024-07-28,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,179.0,0,0
HB-065235,City Hotel,1,36,2025,March,13,30,2025-03-30,0,1,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,0
HB-080134,City Hotel,0,0,2023,November,45,9,2023-11-09,1,2,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,100.0,1,1
HB-006318,Resort Hotel,1,182,2024,June,23,3,2024-06-03,1,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,248.0,,0,Transient,97.3,0,0
HB-099905,City Hotel,0,25,2024,October,42,17,2024-10-17,1,2,1,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,129.0,0,2
HB-043962,City Hotel,1,88,2023,September,39,26,2023-09-26,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-091655,City Hotel,0,19,2024,June,25,22,2024-06-22,0,2,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,1,No Deposit,215.0,,0,Transient-Party,100.0,0,0
HB-086328,City Hotel,0,70,2024,March,13,28,2024-03-28,1,3,3,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,22.0,,0,Transient,84.15,0,1
HB-073372,City Hotel,1,195,2025,August,34,19,2025-08-19,2,1,3,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,158.7,0,0
HB-072649,City Hotel,1,130,2025,August,31,2,2025-08-02,0,3,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.0,0,2
HB-027272,Resort Hotel,0,67,2024,August,34,23,2024-08-23,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,168.63,0,1
HB-036838,Resort Hotel,1,258,2025,May,22,31,2025-05-31,2,4,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,143.0,,0,Transient,68.95,0,1
HB-053954,City Hotel,1,32,2024,July,27,3,2024-07-03,2,0,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,112.59,0,0
HB-058955,City Hotel,1,205,2024,October,42,18,2024-10-18,0,4,2,0.0,0,SC,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.5,0,2
HB-096072,City Hotel,0,205,2024,August,34,20,2024-08-20,2,6,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,92.01,0,1
HB-013958,Resort Hotel,0,0,2025,February,7,13,2025-02-13,1,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,2,8,A,E,1,No Deposit,,135.0,0,Transient,35.0,1,2
HB-090591,City Hotel,0,118,2024,June,23,6,2024-06-06,1,2,1,0.0,0,BB,FRA,Offline TA/TO,Corporate,0,0,0,A,D,0,No Deposit,191.0,,0,Transient-Party,110.0,0,0
HB-006719,Resort Hotel,1,105,2024,June,26,26,2024-06-26,2,5,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,143.57,0,0
HB-065589,City Hotel,1,75,2025,April,14,5,2025-04-05,0,4,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,132.0,,0,Transient-Party,85.0,0,0
HB-076325,City Hotel,0,0,2023,July,28,16,2023-07-16,0,0,2,0.0,0,SC,PRT,Offline TA/TO,TA/TO,1,0,0,A,D,0,No Deposit,19.0,,0,Transient,0.0,0,0
HB-100229,City Hotel,0,386,2024,October,43,23,2024-10-23,2,0,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-007187,Resort Hotel,1,105,2024,July,30,25,2024-07-25,3,5,1,0.0,0,BB,PRT,Groups,Corporate,0,0,0,A,A,0,No Deposit,307.0,,0,Transient-Party,139.0,0,0
HB-081098,City Hotel,1,24,2023,December,49,5,2023-12-05,2,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,1,0,A,A,0,No Deposit,,143.0,0,Transient-Party,50.0,0,0
HB-029999,Resort Hotel,0,46,2024,November,45,5,2024-11-05,2,5,2,0.0,0,BB,MLT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,35.0,1,0
HB-088004,City Hotel,0,56,2024,April,17,24,2024-04-24,2,3,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient-Party,115.09,0,2
HB-097728,City Hotel,0,11,2024,September,38,19,2024-09-19,1,0,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,187.0,0,2
HB-004045,Resort Hotel,1,140,2024,February,7,12,2024-02-12,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,50.0,0,0
HB-069851,City Hotel,1,96,2025,June,23,7,2025-06-07,2,5,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,178.2,0,0
HB-093433,City Hotel,0,61,2024,July,29,17,2024-07-17,2,3,2,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,120.6,0,1
HB-036980,Resort Hotel,0,1,2025,June,22,1,2025-06-01,0,2,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,96.5,0,0
HB-037743,Resort Hotel,0,37,2025,June,26,24,2025-06-24,2,2,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,243.0,1,3
HB-073510,City Hotel,1,138,2025,August,34,24,2025-08-24,1,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,155.0,0,1
HB-093549,City Hotel,0,292,2024,July,29,21,2024-07-21,0,2,2,0.0,0,HB,AUT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,0
HB-049148,City Hotel,0,91,2024,April,14,6,2024-04-06,0,4,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,A,D,0,No Deposit,14.0,,0,Transient,76.5,0,0
HB-066199,City Hotel,1,58,2025,April,16,15,2025-04-15,2,1,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.0,0,0
HB-041937,City Hotel,0,13,2023,August,34,27,2023-08-27,0,1,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,2,No Deposit,9.0,,0,Transient,153.0,0,2
HB-061813,City Hotel,1,218,2024,December,52,26,2024-12-26,1,5,3,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,110.22,0,2
HB-000712,Resort Hotel,1,54,2023,July,30,26,2023-07-26,2,4,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,95.02,0,2
HB-099034,City Hotel,0,32,2024,October,40,6,2024-10-06,0,2,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,157.5,0,2
HB-064868,City Hotel,1,55,2025,March,12,18,2025-03-18,1,1,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,106.2,0,1
HB-099589,City Hotel,0,0,2024,October,41,12,2024-10-12,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,C,1,No Deposit,132.0,,0,Transient-Party,70.0,0,0
HB-118186,City Hotel,0,4,2025,August,33,13,2025-08-13,2,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,200.0,0,1
HB-013020,Resort Hotel,1,203,2025,July,31,28,2025-07-28,0,1,2,1.0,0,BB,ITA,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,249.0,0,1
HB-041288,City Hotel,1,0,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-111412,City Hotel,0,173,2025,May,19,7,2025-05-07,2,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,42.0,,0,Transient-Party,89.1,0,1
HB-062180,City Hotel,1,12,2025,January,1,3,2025-01-03,0,4,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,K,0,No Deposit,9.0,,0,Transient,107.1,0,2
HB-096844,City Hotel,0,157,2024,September,36,5,2024-09-05,1,3,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,161.1,0,2
HB-060227,City Hotel,1,277,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-020485,Resort Hotel,0,15,2024,January,4,28,2024-01-28,0,3,2,1.0,0,BB,GBR,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,43.0,0,1
HB-109437,City Hotel,0,44,2025,April,15,7,2025-04-07,2,3,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,110.4,0,1
HB-086063,City Hotel,0,39,2024,March,12,24,2024-03-24,0,3,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,9.0,,0,Transient,142.8,1,1
HB-063322,City Hotel,1,32,2025,February,6,8,2025-02-08,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,86.0,,0,Transient,66.64,0,0
HB-083820,City Hotel,0,1,2024,February,6,11,2024-02-11,0,3,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,109.0,0,3
HB-040697,City Hotel,0,12,2023,August,31,5,2023-08-05,0,3,2,0.0,0,BB,RUS,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,38.0,0,Transient-Party,65.0,0,0
HB-103076,City Hotel,0,70,2024,December,50,9,2024-12-09,0,2,2,1.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,22.0,,0,Transient,80.33,0,0
HB-042485,City Hotel,0,1,2023,September,36,6,2023-09-06,2,0,1,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,75.0,0,0
HB-032638,Resort Hotel,0,4,2025,January,5,29,2025-01-29,2,0,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,34.0,0,0
HB-107855,City Hotel,0,109,2025,March,11,14,2025-03-14,0,5,3,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,22.0,,0,Transient,102.0,0,1
HB-081548,City Hotel,1,218,2024,June,23,9,2024-06-09,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,133.0,,0,Transient,135.0,0,0
HB-097919,City Hotel,0,44,2024,September,38,18,2024-09-18,2,2,2,0.0,0,BB,CHE,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,85.5,0,0
HB-071572,City Hotel,1,95,2025,July,28,7,2025-07-07,2,3,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,1
HB-066200,City Hotel,1,82,2025,April,16,15,2025-04-15,2,1,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,177.0,0,0
HB-081701,City Hotel,0,3,2023,December,51,18,2023-12-18,0,1,2,0.0,0,SC,FRA,Direct,Direct,0,0,0,A,D,2,No Deposit,,,0,Transient,75.0,0,1
HB-060443,City Hotel,1,22,2024,November,46,11,2024-11-11,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.0,0,3
HB-033816,Resort Hotel,0,163,2025,February,9,28,2025-02-28,0,5,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,F,2,No Deposit,240.0,,0,Transient-Party,37.0,0,0
HB-021483,Resort Hotel,0,3,2024,February,9,28,2024-02-28,2,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,171.0,,0,Transient,30.0,0,0
HB-001463,Resort Hotel,1,104,2023,August,35,30,2023-08-30,2,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,161.29,0,0
HB-095836,City Hotel,0,21,2024,August,34,24,2024-08-24,0,1,2,1.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,9.0,,0,Transient,146.5,0,2
HB-009970,Resort Hotel,1,72,2025,January,5,30,2025-01-30,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,45.36,0,0
HB-078028,City Hotel,0,0,2023,September,39,30,2023-09-30,0,1,2,2.0,0,BB,NOR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Contract,196.0,0,1
HB-019197,Resort Hotel,1,92,2024,February,9,26,2024-02-26,1,2,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,134.0,,0,Transient,79.0,0,0
HB-038360,Resort Hotel,0,89,2025,July,28,13,2025-07-13,0,3,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,242.0,,0,Transient,201.67,0,1
HB-053363,City Hotel,1,29,2024,June,25,18,2024-06-18,2,2,1,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.8,0,0
HB-001459,Resort Hotel,1,47,2023,August,35,30,2023-08-30,2,5,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,113.43,0,0
HB-065694,City Hotel,1,93,2025,April,14,6,2025-04-06,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,170.0,,0,Transient,95.0,0,0
HB-084859,City Hotel,0,6,2024,March,10,4,2024-03-04,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,91.0,0,0
HB-086100,City Hotel,0,41,2024,March,12,24,2024-03-24,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,117.6,0,0
HB-029967,Resort Hotel,0,36,2024,November,45,4,2024-11-04,2,5,1,0.0,0,BB,FIN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,27.0,0,1
HB-082687,City Hotel,0,23,2024,January,1,2,2024-01-02,2,1,1,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,26.0,,0,Transient-Party,79.0,0,0
HB-105973,City Hotel,0,114,2025,February,7,15,2025-02-15,0,4,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,242.0,0,Transient-Party,78.0,0,0
HB-082706,City Hotel,0,45,2024,January,1,1,2024-01-01,2,2,2,1.0,0,SC,PRT,Online TA,TA/TO,0,0,0,F,F,2,No Deposit,9.0,,0,Contract,159.08,0,3
HB-097071,City Hotel,0,91,2024,September,36,7,2024-09-07,1,4,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,109.29,0,2
HB-030262,Resort Hotel,0,0,2024,November,46,16,2024-11-16,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,60.0,0,0
HB-021782,Resort Hotel,0,19,2024,March,10,6,2024-03-06,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,241.0,,0,Transient,36.61,0,2
HB-110235,City Hotel,0,44,2025,April,16,20,2025-04-20,1,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,85.0,0,0
HB-005571,Resort Hotel,0,199,2024,May,18,2,2024-05-02,1,1,1,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,1,No Deposit,298.0,,0,Transient-Party,54.5,0,1
HB-045768,City Hotel,0,98,2023,November,47,23,2023-11-23,1,2,1,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,D,0,No Deposit,37.0,,0,Transient-Party,70.0,0,0
HB-040989,City Hotel,0,39,2023,August,32,10,2023-08-10,1,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,0.0,0,0
HB-090493,City Hotel,0,247,2024,June,23,6,2024-06-06,1,1,2,0.0,0,HB,AUT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-101048,City Hotel,0,3,2024,November,45,4,2024-11-04,0,2,1,0.0,0,BB,EST,Online TA,TA/TO,0,0,0,A,K,0,No Deposit,7.0,,0,Transient,109.73,0,1
HB-111534,City Hotel,0,139,2025,May,19,8,2025-05-08,1,3,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,144.0,0,2
HB-005605,Resort Hotel,1,159,2024,May,18,5,2024-05-05,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,52.2,0,2
HB-000060,Resort Hotel,0,14,2023,July,26,2,2023-07-02,0,2,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,242.0,,0,Transient,98.0,0,1
HB-109747,City Hotel,0,34,2025,April,16,14,2025-04-14,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,150.0,0,0
HB-053175,City Hotel,1,245,2024,June,25,17,2024-06-17,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,0,Transient,75.0,0,0
HB-113244,City Hotel,0,227,2025,June,22,1,2025-06-01,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,157.5,0,1
HB-047838,City Hotel,1,31,2024,March,10,5,2024-03-05,2,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,84.9,0,0
HB-028394,Resort Hotel,0,4,2024,September,40,30,2024-09-30,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,115.0,0,1
HB-023849,Resort Hotel,0,101,2024,April,18,29,2024-04-29,2,5,1,0.0,0,HB,NLD,Groups,TA/TO,0,0,0,A,A,9,No Deposit,95.0,,0,Transient-Party,54.0,0,0
HB-002284,Resort Hotel,0,94,2023,October,40,8,2023-10-08,2,5,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,77.43,0,0
HB-116905,City Hotel,0,16,2025,July,30,26,2025-07-26,0,1,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,200.0,0,0
HB-107658,City Hotel,0,8,2025,March,11,15,2025-03-15,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,103.0,,0,Transient-Party,109.0,1,0
HB-078909,City Hotel,0,16,2023,October,41,15,2023-10-15,1,3,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,90.0,0,0
HB-086594,City Hotel,0,72,2024,April,14,3,2024-04-03,2,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,87.3,0,2
HB-024333,Resort Hotel,0,4,2024,May,20,14,2024-05-14,2,2,2,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,D,D,1,No Deposit,,110.0,0,Transient,85.5,0,2
HB-019585,Resort Hotel,0,0,2023,December,52,27,2023-12-27,1,0,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient,75.0,0,0
HB-008286,Resort Hotel,0,397,2024,September,38,21,2024-09-21,0,4,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,96.0,,0,Transient-Party,72.5,0,1
HB-016728,Resort Hotel,0,244,2023,September,35,2,2023-09-02,2,5,1,0.0,0,BB,IRL,Groups,TA/TO,0,0,0,A,A,0,No Deposit,96.0,,0,Transient,0.0,0,0
HB-107157,City Hotel,0,32,2025,March,10,5,2025-03-05,2,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,0
HB-094731,City Hotel,0,26,2024,August,32,8,2024-08-08,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,65.0,1,0
HB-020145,Resort Hotel,0,0,2024,January,3,15,2024-01-15,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,59.0,0,1
HB-011018,Resort Hotel,1,173,2025,April,16,14,2025-04-14,2,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,88.5,0,3
HB-062794,City Hotel,1,29,2025,January,4,22,2025-01-22,8,16,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,72.39,0,0
HB-002546,Resort Hotel,1,145,2023,October,42,21,2023-10-21,1,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,66.0,0,0
HB-091902,City Hotel,0,14,2024,June,26,26,2024-06-26,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,110.0,1,1
HB-118687,City Hotel,0,159,2025,August,34,20,2025-08-20,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,130.5,0,0
HB-110110,City Hotel,0,159,2025,April,16,20,2025-04-20,0,2,2,1.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient-Party,114.0,0,0
HB-045763,City Hotel,0,98,2023,November,47,23,2023-11-23,1,2,1,0.0,0,BB,EGY,Groups,TA/TO,0,0,0,A,D,0,No Deposit,37.0,,0,Transient-Party,70.0,0,0
HB-051038,City Hotel,1,74,2024,May,20,13,2024-05-13,1,2,2,1.0,0,BB,BGR,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,9.0,,0,Transient,143.1,0,2
HB-098746,City Hotel,0,54,2024,October,40,2,2024-10-02,2,0,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.8,0,2
HB-083527,City Hotel,0,31,2024,January,5,30,2024-01-30,2,5,2,1.0,0,BB,TUR,Offline TA/TO,TA/TO,0,0,0,D,E,0,No Deposit,16.0,,0,Transient,84.03,0,3
HB-040635,City Hotel,1,28,2023,August,31,3,2023-08-03,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-087128,City Hotel,0,45,2024,April,15,13,2024-04-13,0,2,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.5,0,1
HB-091985,City Hotel,0,128,2024,June,26,26,2024-06-26,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,109.8,0,1
HB-011919,Resort Hotel,1,320,2025,June,23,3,2025-06-03,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,74.25,0,1
HB-065254,City Hotel,1,629,2025,March,13,30,2025-03-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-023290,Resort Hotel,0,91,2024,April,16,20,2024-04-20,0,1,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,251.0,,0,Transient-Party,59.0,0,1
HB-103009,City Hotel,0,122,2024,December,49,8,2024-12-08,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,83.0,,0,Transient-Party,68.0,0,0
HB-091256,City Hotel,0,71,2024,June,25,17,2024-06-17,0,2,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,168.0,,0,Transient,80.75,0,0
HB-067390,City Hotel,1,20,2025,May,18,3,2025-05-03,0,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,130.0,0,1
HB-036823,Resort Hotel,0,151,2025,May,22,26,2025-05-26,2,2,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,112.5,0,1
HB-096412,City Hotel,0,42,2024,August,35,27,2024-08-27,2,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,147.9,0,2
HB-081811,City Hotel,1,211,2024,May,22,31,2024-05-31,0,3,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,3.0,,46,Transient,115.0,0,0
HB-030955,Resort Hotel,0,34,2024,December,50,9,2024-12-09,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-064270,City Hotel,1,33,2025,March,10,3,2025-03-03,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,77.23,0,0
HB-092321,City Hotel,0,160,2024,June,26,30,2024-06-30,1,3,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.95,0,1
HB-053185,City Hotel,1,350,2024,June,25,17,2024-06-17,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,130.0,0,0
HB-086097,City Hotel,0,73,2024,March,12,24,2024-03-24,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,56.38,0,1
HB-117924,City Hotel,0,207,2025,August,32,10,2025-08-10,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,112.5,0,2
HB-087285,City Hotel,0,122,2024,April,16,15,2024-04-15,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,151.0,,56,Transient-Party,85.0,0,0
HB-077355,City Hotel,1,19,2023,October,40,6,2023-10-06,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,1,1,0,A,A,0,Non Refund,82.0,,0,Transient,80.0,0,0
HB-010127,Resort Hotel,1,19,2025,February,7,14,2025-02-14,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,60.5,0,3
HB-005737,Resort Hotel,0,236,2024,May,19,12,2024-05-12,1,3,2,0.0,0,SC,GBR,Groups,TA/TO,0,0,0,A,I,0,No Deposit,315.0,,0,Transient-Party,0.0,0,0
HB-012013,Resort Hotel,1,304,2025,June,23,8,2025-06-08,2,3,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,298.0,,0,Transient,94.0,0,0
HB-060191,City Hotel,1,277,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-055283,City Hotel,1,162,2024,August,32,9,2024-08-09,1,5,2,0.0,0,HB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,134.25,0,0
HB-013215,Resort Hotel,1,167,2025,August,32,5,2025-08-05,0,1,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,220.0,0,0
HB-024738,Resort Hotel,0,2,2024,May,22,30,2024-05-30,1,2,1,0.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,175.0,,0,Transient,68.8,0,0
HB-102280,City Hotel,0,308,2024,November,47,23,2024-11-23,0,3,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,78.3,0,2
HB-088359,City Hotel,0,110,2024,May,18,2,2024-05-02,1,2,2,1.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,11.0,,0,Transient,68.04,0,1
HB-090003,City Hotel,0,61,2024,May,22,29,2024-05-29,2,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,135.0,0,2
HB-005541,Resort Hotel,0,199,2024,May,18,2,2024-05-02,1,1,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,85.0,0,0
HB-097948,City Hotel,0,1,2024,September,38,22,2024-09-22,0,1,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,B,1,No Deposit,9.0,,0,Transient,175.0,0,1
HB-072091,City Hotel,1,158,2025,July,29,20,2025-07-20,1,3,2,0.0,0,BB,ISR,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,123.3,0,2
HB-006047,Resort Hotel,1,34,2024,May,21,23,2024-05-23,1,1,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,105.0,0,1
HB-116046,City Hotel,0,414,2025,July,28,13,2025-07-13,0,2,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,122.4,0,1
HB-044564,City Hotel,1,30,2023,October,40,7,2023-10-07,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,94.5,0,2
HB-017221,Resort Hotel,0,167,2023,September,37,17,2023-09-17,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,F,1,No Deposit,243.0,,0,Contract,65.9,0,0
HB-040273,City Hotel,1,12,2023,July,29,18,2023-07-18,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-004534,Resort Hotel,0,162,2024,March,12,24,2024-03-24,0,3,2,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,84.0,0,0
HB-018978,Resort Hotel,0,0,2023,December,49,9,2023-12-09,0,1,1,0.0,0,BB,PRT,Direct,Direct,1,0,1,A,A,0,No Deposit,,,0,Transient,38.0,0,0
HB-050270,City Hotel,1,21,2024,April,17,28,2024-04-28,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,95.0,0,0
HB-061976,City Hotel,1,15,2024,December,52,29,2024-12-29,1,3,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,102.0,0,0
HB-012198,Resort Hotel,1,331,2025,June,25,17,2025-06-17,2,5,2,2.0,0,BB,CHE,Online TA,TA/TO,0,0,0,G,G,1,No Deposit,240.0,,0,Transient-Party,143.0,0,0
HB-099156,City Hotel,0,187,2024,October,41,7,2024-10-07,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.9,0,3
HB-040590,City Hotel,0,117,2023,August,31,1,2023-08-01,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-101068,City Hotel,0,8,2024,November,45,5,2024-11-05,0,1,2,0.0,0,BB,CHN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,359.0,,0,Transient-Party,130.0,0,0
HB-091740,City Hotel,0,265,2024,June,26,24,2024-06-24,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-017019,Resort Hotel,0,88,2023,September,37,16,2023-09-16,1,4,2,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,93.17,0,1
HB-014438,Resort Hotel,0,6,2024,January,4,28,2024-01-28,0,2,1,0.0,0,BB,,Direct,Direct,0,0,1,A,D,0,No Deposit,,,0,Transient,14.0,0,1
HB-020139,Resort Hotel,0,1,2024,January,3,16,2024-01-16,0,1,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,1,No Deposit,240.0,,0,Transient,76.0,0,0
HB-102600,City Hotel,0,31,2024,November,48,27,2024-11-27,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,7.0,,0,Transient,66.71,0,1
HB-001801,Resort Hotel,1,81,2023,September,37,15,2023-09-15,0,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,103.8,0,1
HB-102826,City Hotel,0,80,2024,December,49,5,2024-12-05,1,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient-Party,75.0,0,1
HB-001903,Resort Hotel,0,125,2023,September,38,20,2023-09-20,4,7,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Contract,68.5,0,0
HB-037584,Resort Hotel,0,143,2025,June,25,21,2025-06-21,0,2,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,129.0,1,2
HB-054212,City Hotel,1,173,2024,July,28,8,2024-07-08,2,5,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.75,0,0
HB-046013,City Hotel,1,135,2023,December,49,5,2023-12-05,1,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,51.4,0,0
HB-061244,City Hotel,1,18,2024,December,49,5,2024-12-05,4,10,1,0.0,0,SC,AGO,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,89.0,0,0
HB-113991,City Hotel,0,39,2025,June,24,12,2025-06-12,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,99.0,0,1
HB-026043,Resort Hotel,0,60,2024,July,29,15,2024-07-15,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,174.0,0,1
HB-067849,City Hotel,1,106,2025,May,19,8,2025-05-08,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,89.1,0,1
HB-083332,City Hotel,0,58,2024,January,4,27,2024-01-27,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,87.0,,0,Transient-Party,81.0,0,0
HB-013231,Resort Hotel,1,45,2025,August,32,5,2025-08-05,2,4,2,2.0,0,HB,MAR,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,378.0,0,0
HB-109575,City Hotel,0,74,2025,April,15,9,2025-04-09,2,3,2,1.0,0,BB,AUT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,7.0,,0,Transient,197.82,0,0
HB-048183,City Hotel,1,91,2024,March,12,18,2024-03-18,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,20,Transient,75.0,0,0
HB-101684,City Hotel,0,8,2024,November,46,14,2024-11-14,1,1,1,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,103.0,0,1
HB-040008,Resort Hotel,0,33,2025,August,35,31,2025-08-31,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,154.0,0,1
HB-118849,City Hotel,0,159,2025,August,34,22,2025-08-22,0,4,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,83.0,,0,Transient,104.4,0,0
HB-111598,City Hotel,0,122,2025,May,19,11,2025-05-11,0,2,1,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,117.0,0,0
HB-053464,City Hotel,1,35,2024,June,25,21,2024-06-21,0,1,3,0.0,0,BB,SGP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,132.3,0,0
HB-054026,City Hotel,0,198,2024,July,27,6,2024-07-06,0,4,0,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,K,0,No Deposit,9.0,,0,Transient,0.0,0,1
HB-013069,Resort Hotel,1,342,2025,July,31,29,2025-07-29,4,6,2,2.0,0,HB,GBR,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,266.6,0,0
HB-115556,City Hotel,0,169,2025,July,27,6,2025-07-06,0,2,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient-Party,107.1,0,0
HB-094639,City Hotel,0,136,2024,August,31,1,2024-08-01,2,5,2,0.0,0,BB,POL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,97.07,0,0
HB-015279,Resort Hotel,0,8,2024,September,38,20,2024-09-20,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,6,A,A,0,No Deposit,,338.0,0,Transient,68.0,1,0
HB-010227,Resort Hotel,1,28,2025,February,8,21,2025-02-21,2,5,1,2.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,95.0,0,0
HB-059083,City Hotel,1,192,2024,October,43,21,2024-10-21,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,29.0,,0,Transient-Party,95.0,0,0
HB-079865,City Hotel,1,34,2023,December,49,8,2023-12-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,0,Transient,90.0,0,0
HB-088700,City Hotel,0,19,2024,May,19,9,2024-05-09,1,1,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,2
HB-105499,City Hotel,0,2,2025,February,6,9,2025-02-09,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.0,0,1
HB-083842,City Hotel,0,76,2024,February,6,7,2024-02-07,2,5,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,41.0,0,0
HB-025901,Resort Hotel,0,0,2024,July,29,15,2024-07-15,0,2,2,0.0,0,BB,PRT,Direct,Direct,1,0,0,A,D,0,No Deposit,,,0,Transient,176.0,0,0
HB-026162,Resort Hotel,0,200,2024,July,29,16,2024-07-16,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,108.0,0,1
HB-111525,City Hotel,0,307,2025,May,19,11,2025-05-11,0,1,2,0.0,0,BB,MOZ,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,467.0,,0,Transient-Party,89.1,0,0
HB-041924,City Hotel,0,55,2023,August,34,26,2023-08-26,0,2,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-097231,City Hotel,0,0,2024,September,37,13,2024-09-13,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,169.0,0,0
HB-049280,City Hotel,1,190,2024,April,15,9,2024-04-09,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,31,Transient-Party,70.0,0,0
HB-050117,City Hotel,1,31,2024,April,17,23,2024-04-23,2,4,2,1.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,83.0,,0,Transient,26.35,0,0
HB-086250,City Hotel,0,7,2024,March,13,30,2024-03-30,0,1,2,1.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.0,0,0
HB-033143,Resort Hotel,0,5,2025,February,7,15,2025-02-15,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,C,0,No Deposit,168.0,,0,Transient-Party,30.0,0,0
HB-116816,City Hotel,0,201,2025,July,30,24,2025-07-24,1,0,2,2.0,0,BB,SWE,Direct,Direct,0,0,0,E,E,2,No Deposit,14.0,,0,Transient,181.5,1,2
HB-026992,Resort Hotel,0,1,2024,August,33,16,2024-08-16,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,219.0,0,1
HB-017559,Resort Hotel,0,2,2023,October,41,12,2023-10-12,1,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,56.0,0,0
HB-068969,City Hotel,1,208,2025,May,21,24,2025-05-24,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,12.0,0,0
HB-059844,City Hotel,1,304,2024,November,44,3,2024-11-03,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,89.0,0,0
HB-063929,City Hotel,1,134,2025,February,9,25,2025-02-25,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,75.0,0,0
HB-057304,City Hotel,1,244,2024,September,39,23,2024-09-23,0,2,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,95.4,0,0
HB-025653,Resort Hotel,0,168,2024,June,25,21,2024-06-21,4,10,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,106.71,0,1
HB-074507,City Hotel,1,325,2023,September,36,7,2023-09-07,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-114759,City Hotel,0,396,2025,June,26,25,2025-06-25,2,0,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,122.4,0,1
HB-077941,City Hotel,0,16,2023,September,39,25,2023-09-25,2,3,1,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,170.0,0,0
HB-050988,City Hotel,1,18,2024,May,20,13,2024-05-13,0,1,1,0.0,0,BB,JPN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,156.0,0,0
HB-045499,City Hotel,1,100,2023,October,44,31,2023-10-31,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-111472,City Hotel,0,35,2025,May,19,8,2025-05-08,1,2,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,262.0,,0,Transient,99.0,0,2
HB-116931,City Hotel,0,91,2025,July,30,23,2025-07-23,2,2,2,0.0,0,BB,ISR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,112.5,0,1
HB-061984,City Hotel,1,269,2024,December,52,29,2024-12-29,2,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,70.0,0,0
HB-022043,Resort Hotel,0,32,2025,January,5,30,2025-01-30,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,7,A,D,0,No Deposit,,113.0,0,Transient,42.0,1,0
HB-021511,Resort Hotel,0,22,2024,February,8,24,2024-02-24,2,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,63.14,1,1
HB-114617,City Hotel,0,149,2025,June,26,24,2025-06-24,0,1,2,0.0,0,HB,ITA,Corporate,Corporate,0,0,0,A,B,1,No Deposit,495.0,,0,Transient-Party,154.0,0,0
HB-112902,City Hotel,0,201,2025,May,21,24,2025-05-24,2,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.1,0,3
HB-017403,Resort Hotel,0,69,2023,October,40,4,2023-10-04,2,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient,50.4,0,1
HB-066716,City Hotel,1,99,2025,April,17,23,2025-04-23,2,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,0
HB-039840,Resort Hotel,0,106,2025,August,34,23,2025-08-23,2,5,3,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,224.25,0,0
HB-087794,City Hotel,0,55,2024,April,17,22,2024-04-22,2,2,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,130.05,0,2
HB-119132,City Hotel,0,146,2025,August,35,28,2025-08-28,1,1,3,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,195.0,0,1
HB-108793,City Hotel,0,60,2025,March,13,30,2025-03-30,0,3,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.8,0,0
HB-049409,City Hotel,0,124,2024,April,15,12,2024-04-12,0,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient-Party,82.13,0,0
HB-103438,City Hotel,0,142,2024,December,51,22,2024-12-22,0,2,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,1
HB-093687,City Hotel,0,96,2024,July,30,23,2024-07-23,1,1,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,94.5,0,0
HB-009533,Resort Hotel,1,38,2024,December,49,8,2024-12-08,0,1,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,43.0,0,0
HB-112162,City Hotel,0,158,2025,May,20,18,2025-05-18,0,3,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,170.0,0,0
HB-058735,City Hotel,1,163,2024,October,42,15,2024-10-15,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,34.0,,0,Transient,115.0,0,0
HB-104417,City Hotel,0,65,2025,January,2,12,2025-01-12,0,1,1,0.0,0,BB,DEU,Groups,TA/TO,0,0,0,A,A,1,No Deposit,,366.0,0,Transient-Party,65.0,0,0
HB-086035,City Hotel,0,35,2024,March,12,22,2024-03-22,0,4,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,138.38,0,1
HB-084706,City Hotel,0,9,2024,March,9,2,2024-03-02,0,1,1,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,69.0,0,0
HB-076448,City Hotel,1,379,2023,October,44,31,2023-10-31,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-113382,City Hotel,0,158,2025,June,23,6,2025-06-06,0,1,2,0.0,0,SC,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Group,126.0,0,2
HB-015584,Resort Hotel,0,171,2023,July,30,24,2023-07-24,1,2,2,1.0,0,BB,CHE,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,,0,Transient,153.1,1,1
HB-008392,Resort Hotel,1,56,2024,September,39,26,2024-09-26,1,3,1,2.0,0,BB,IRL,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,169.0,0,0
HB-079347,City Hotel,0,32,2023,October,43,24,2023-10-24,1,1,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Contract,136.0,0,1
HB-050364,City Hotel,0,119,2024,April,18,29,2024-04-29,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,B,1,No Deposit,9.0,,0,Transient,99.3,0,0
HB-083623,City Hotel,0,4,2024,February,6,7,2024-02-07,2,0,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,102.0,1,1
HB-034633,Resort Hotel,0,57,2025,March,13,26,2025-03-26,2,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,55.2,0,1
HB-065921,City Hotel,1,10,2025,April,15,10,2025-04-10,1,1,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,115.0,0,1
HB-053692,City Hotel,1,59,2024,June,26,27,2024-06-27,1,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,102.6,0,0
HB-112050,City Hotel,0,75,2025,May,20,16,2025-05-16,0,3,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-033171,Resort Hotel,0,94,2025,February,7,13,2025-02-13,1,3,2,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,152.0,,0,Transient-Party,62.0,0,0
HB-076091,City Hotel,1,364,2023,October,42,16,2023-10-16,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-095427,City Hotel,0,148,2024,August,33,15,2024-08-15,1,3,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,182.83,1,1
HB-049005,City Hotel,1,101,2024,April,14,4,2024-04-04,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,41,Transient,80.0,0,0
HB-025365,Resort Hotel,0,17,2024,June,25,19,2024-06-19,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,241.0,,0,Transient,123.62,0,1
HB-026698,Resort Hotel,0,1,2024,August,32,6,2024-08-06,1,1,2,0.0,0,BB,ARG,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,200.05,0,1
HB-088757,City Hotel,0,4,2024,May,19,9,2024-05-09,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,95.0,0,0
HB-104683,City Hotel,0,55,2025,January,3,16,2025-01-16,1,3,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,72.0,0,1
HB-065014,City Hotel,1,9,2025,March,12,22,2025-03-22,0,2,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.0,0,0
HB-026926,Resort Hotel,0,87,2024,August,33,12,2024-08-12,1,2,3,1.0,0,BB,BRA,Direct,Direct,0,0,0,H,H,0,No Deposit,,,0,Transient,279.0,1,1
HB-064401,City Hotel,1,608,2025,March,10,9,2025-03-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-026406,Resort Hotel,0,0,2024,July,30,28,2024-07-28,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,193.67,0,0
HB-055480,City Hotel,1,207,2024,August,33,13,2024-08-13,4,6,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,81.6,0,0
HB-100442,City Hotel,0,8,2024,October,43,27,2024-10-27,0,1,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,7.0,,0,Transient,84.7,0,1
HB-115097,City Hotel,0,203,2025,July,27,1,2025-07-01,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,2
HB-037055,Resort Hotel,0,136,2025,May,22,29,2025-05-29,2,5,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,,0,Transient,106.72,0,1
HB-077839,City Hotel,0,0,2023,September,39,28,2023-09-28,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,72.0,,0,Transient,40.0,0,0
HB-068407,City Hotel,1,12,2025,May,20,16,2025-05-16,2,5,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,175.71,0,0
HB-029849,Resort Hotel,0,84,2024,October,44,31,2024-10-31,2,5,2,1.0,0,BB,FIN,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,241.0,,0,Transient,62.9,0,2
HB-099565,City Hotel,0,238,2024,October,41,13,2024-10-13,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,80.0,0,0
HB-113679,City Hotel,0,175,2025,June,24,9,2025-06-09,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,130.0,0,0
HB-033854,Resort Hotel,0,7,2025,March,9,2,2025-03-02,1,3,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,D,D,0,No Deposit,,223.0,0,Transient-Party,54.0,1,0
HB-000990,Resort Hotel,0,62,2023,August,32,9,2023-08-09,2,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,F,1,No Deposit,240.0,,0,Transient,210.33,1,2
HB-054275,City Hotel,1,49,2024,July,28,11,2024-07-11,1,0,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.15,0,0
HB-094069,City Hotel,0,158,2024,July,30,28,2024-07-28,0,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,121.8,0,1
HB-051968,City Hotel,1,37,2024,May,22,27,2024-05-27,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,140.4,0,0
HB-089405,City Hotel,0,198,2024,May,21,20,2024-05-20,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,98,Transient-Party,65.0,0,0
HB-094043,City Hotel,0,0,2024,July,31,29,2024-07-29,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,119.0,0,0
HB-037367,Resort Hotel,0,0,2025,June,24,14,2025-06-14,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,121.5,0,3
HB-035284,Resort Hotel,0,84,2025,April,15,13,2025-04-13,2,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,40.95,0,0
HB-017533,Resort Hotel,0,152,2023,October,41,12,2023-10-12,1,0,2,0.0,0,BB,COL,Online TA,TA/TO,0,0,0,E,F,0,No Deposit,240.0,,0,Transient,76.0,0,2
HB-077850,City Hotel,0,16,2023,September,39,25,2023-09-25,2,2,1,0.0,0,BB,BEL,Groups,TA/TO,0,0,0,A,D,1,No Deposit,1.0,,0,Transient-Party,170.0,0,0
HB-024794,Resort Hotel,0,79,2024,May,22,30,2024-05-30,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,99.5,1,1
HB-006555,Resort Hotel,0,228,2024,June,25,17,2024-06-17,2,5,2,2.0,0,BB,NLD,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,147.0,1,1
HB-062900,City Hotel,1,53,2025,January,4,24,2025-01-24,0,4,3,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,117.81,0,0
HB-029715,Resort Hotel,0,13,2024,November,44,3,2024-11-03,0,1,2,0.0,0,BB,UKR,Groups,TA/TO,0,0,0,A,A,2,No Deposit,368.0,,0,Transient-Party,38.0,0,1
HB-086910,City Hotel,0,159,2024,April,15,9,2024-04-09,1,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,70.0,0,0
HB-095840,City Hotel,0,141,2024,August,34,22,2024-08-22,1,2,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,7.0,,0,Transient,77.62,0,0
HB-001915,Resort Hotel,0,185,2023,September,38,21,2023-09-21,1,1,2,0.0,0,HB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,208.0,,0,Transient-Party,90.0,0,1
HB-110356,City Hotel,0,131,2025,April,17,24,2025-04-24,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,1
HB-034982,Resort Hotel,0,152,2025,April,14,5,2025-04-05,1,4,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,D,4,No Deposit,,223.0,0,Transient-Party,48.0,0,0
HB-000569,Resort Hotel,0,0,2023,July,29,20,2023-07-20,0,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,I,0,No Deposit,5.0,,0,Transient,0.0,0,0
HB-068922,City Hotel,1,423,2025,May,21,23,2025-05-23,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-069463,City Hotel,1,292,2025,May,22,31,2025-05-31,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,90.0,0,0
HB-065838,City Hotel,1,171,2025,April,15,9,2025-04-09,2,0,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,2
HB-066508,City Hotel,1,57,2025,April,17,21,2025-04-21,0,2,2,0.0,0,BB,CHE,Direct,Direct,0,0,0,F,F,0,No Deposit,14.0,,0,Transient,225.0,0,0
HB-061034,City Hotel,1,8,2024,November,48,30,2024-11-30,0,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,114.0,0,0
HB-007031,Resort Hotel,1,107,2024,July,29,17,2024-07-17,2,4,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,,0,Transient,237.0,0,1
HB-085059,City Hotel,0,0,2024,March,10,8,2024-03-08,0,1,2,0.0,0,BB,ROU,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,87.0,0,0
HB-051420,City Hotel,1,322,2024,May,20,19,2024-05-19,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,120,Transient,80.0,0,0
HB-035510,Resort Hotel,0,140,2025,April,17,24,2025-04-24,1,0,2,0.0,0,BB,CHE,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,251.0,,0,Transient,74.0,0,1
HB-031467,Resort Hotel,0,12,2024,December,52,23,2024-12-23,2,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,90.17,0,0
HB-035986,Resort Hotel,0,191,2025,April,18,30,2025-04-30,2,5,1,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,54.71,0,0
HB-076294,City Hotel,1,147,2023,July,29,21,2023-07-21,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient,0.0,0,0
HB-015077,Resort Hotel,0,0,2023,December,51,22,2023-12-22,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,94.0,0,Transient,25.0,0,0
HB-061641,City Hotel,1,220,2024,December,51,21,2024-12-21,1,4,3,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,104.55,0,0
HB-067496,City Hotel,1,143,2025,May,18,4,2025-05-04,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,56.0,,0,Transient,120.0,0,0
HB-005475,Resort Hotel,1,87,2024,April,18,29,2024-04-29,2,5,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,71.0,,0,Transient,46.0,0,0
HB-052580,City Hotel,1,56,2024,June,23,8,2024-06-08,0,1,2,0.0,0,BB,PRT,Offline TA/TO,Corporate,0,0,0,A,A,0,No Deposit,191.0,,0,Transient-Party,120.0,0,0
HB-000732,Resort Hotel,0,96,2023,July,30,27,2023-07-27,1,2,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,240.0,,0,Transient,166.0,1,2
HB-074160,City Hotel,1,349,2023,October,39,1,2023-10-01,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-038967,Resort Hotel,0,230,2025,August,31,1,2025-08-01,0,3,2,0.0,1,BB,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,153.75,0,2
HB-108311,City Hotel,0,115,2025,March,12,23,2025-03-23,0,3,1,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,1,No Deposit,171.0,,0,Transient-Party,90.0,0,1
HB-100871,City Hotel,0,200,2024,October,44,31,2024-10-31,1,2,0,2.0,0,BB,CHE,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient,82.92,0,3
HB-025841,Resort Hotel,0,89,2024,July,28,14,2024-07-14,0,0,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,0.0,0,0
HB-042149,City Hotel,1,15,2023,September,35,1,2023-09-01,0,5,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Contract,165.0,0,1
HB-013638,Resort Hotel,1,77,2025,August,34,24,2025-08-24,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,198.0,0,0
HB-039778,Resort Hotel,0,58,2025,August,35,25,2025-08-25,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,195.0,0,2
HB-058274,City Hotel,1,131,2024,October,41,10,2024-10-10,1,0,1,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,0
HB-042763,City Hotel,0,1,2023,September,36,9,2023-09-09,0,2,1,0.0,0,BB,FRA,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,68.0,0,Transient-Party,90.0,0,0
HB-049869,City Hotel,1,86,2024,April,16,20,2024-04-20,0,2,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,127.8,0,0
HB-094495,City Hotel,0,1,2024,August,31,4,2024-08-04,0,1,2,0.0,0,SC,ESP,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,139.0,1,2
HB-012885,Resort Hotel,1,180,2025,July,30,22,2025-07-22,2,5,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,E,E,1,No Deposit,250.0,,0,Transient,187.52,0,0
HB-012940,Resort Hotel,1,85,2025,July,30,24,2025-07-24,1,4,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,237.0,0,0
HB-058571,City Hotel,1,37,2024,October,41,13,2024-10-13,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,95.0,0,0
HB-069367,City Hotel,1,186,2025,May,22,30,2025-05-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,130.0,0,0
HB-050286,City Hotel,1,295,2024,April,17,28,2024-04-28,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-110802,City Hotel,0,29,2025,April,18,28,2025-04-28,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,143.5,0,1
HB-018520,Resort Hotel,0,44,2023,November,47,21,2023-11-21,0,1,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,E,1,No Deposit,240.0,,0,Transient,73.5,1,2
HB-109360,City Hotel,0,104,2025,April,15,7,2025-04-07,1,2,2,1.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,144.0,1,3
HB-092563,City Hotel,0,0,2024,July,28,8,2024-07-08,0,0,1,0.0,0,BB,PRT,Aviation,Corporate,1,0,0,A,K,0,No Deposit,,153.0,0,Transient,0.0,0,0
HB-053359,City Hotel,1,68,2024,June,25,18,2024-06-18,2,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,92.83,0,0
HB-032687,Resort Hotel,0,4,2025,January,5,29,2025-01-29,2,2,2,1.0,0,HB,POL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,171.0,,0,Transient,68.0,0,0
HB-111153,City Hotel,0,108,2025,May,19,5,2025-05-05,0,2,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-090514,City Hotel,0,247,2024,June,23,6,2024-06-06,1,1,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-089076,City Hotel,0,100,2024,May,20,15,2024-05-15,2,0,3,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,F,4,No Deposit,9.0,,0,Transient,210.6,0,2
HB-036321,Resort Hotel,0,112,2025,May,19,8,2025-05-08,3,6,3,0.0,0,HB,IRL,Direct,Direct,0,0,0,D,D,1,No Deposit,250.0,,0,Transient,143.89,0,1
HB-090346,City Hotel,0,93,2024,June,23,3,2024-06-03,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,80.75,0,1
HB-018974,Resort Hotel,1,196,2024,June,24,14,2024-06-14,2,7,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,E,E,0,No Deposit,240.0,,0,Transient,99.0,0,2
HB-068171,City Hotel,1,201,2025,May,20,14,2025-05-14,2,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,4,No Deposit,9.0,,0,Transient,139.5,0,1
HB-111738,City Hotel,0,168,2025,May,19,9,2025-05-09,1,5,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,D,D,5,No Deposit,9.0,,0,Transient,145.5,0,0
HB-094099,City Hotel,0,188,2024,July,30,28,2024-07-28,0,3,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient-Party,80.75,0,0
HB-114424,City Hotel,0,4,2025,June,25,20,2025-06-20,0,2,1,0.0,0,BB,DEU,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,215.0,0,0
HB-000050,Resort Hotel,0,50,2023,July,26,2,2023-07-02,2,5,2,0.0,0,HB,IRL,Online TA,TA/TO,0,0,0,E,F,1,No Deposit,241.0,,0,Transient,119.35,0,1
HB-115976,City Hotel,0,112,2025,July,28,9,2025-07-09,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,1
HB-056359,City Hotel,0,251,2024,September,36,3,2024-09-03,2,5,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,105.64,0,1
HB-064191,City Hotel,1,28,2025,March,9,2,2025-03-02,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,95.0,0,0
HB-029521,Resort Hotel,0,0,2024,October,44,30,2024-10-30,1,0,2,0.0,0,BB,CN,Direct,Direct,1,0,0,A,A,0,No Deposit,,,0,Transient,55.0,1,0
HB-006111,Resort Hotel,0,224,2024,May,21,25,2024-05-25,1,4,1,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,A,5,No Deposit,,223.0,0,Transient-Party,40.0,0,0
HB-033008,Resort Hotel,0,33,2025,February,6,8,2025-02-08,0,4,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,54.0,0,1
HB-106585,City Hotel,0,26,2025,February,9,27,2025-02-27,1,0,1,0.0,0,SC,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,1
HB-048787,City Hotel,1,57,2024,March,13,30,2024-03-30,0,4,2,0.0,0,SC,HUN,Online TA,TA/TO,0,0,0,A,A,3,No Deposit,9.0,,0,Transient,76.76,0,0
HB-067791,City Hotel,1,110,2025,May,19,7,2025-05-07,2,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,0
HB-069822,City Hotel,1,134,2025,June,23,7,2025-06-07,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,110.0,0,0
HB-028667,Resort Hotel,0,11,2024,October,41,9,2024-10-09,1,0,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,C,0,No Deposit,,405.0,0,Transient-Party,56.0,1,1
HB-056167,City Hotel,1,70,2024,August,35,31,2024-08-31,0,2,1,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,121.5,0,0
HB-056485,City Hotel,1,258,2024,September,36,8,2024-09-08,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,41,Transient,65.0,0,0
HB-111276,City Hotel,0,158,2025,May,19,5,2025-05-05,2,2,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,144.5,0,3
HB-071803,City Hotel,1,229,2025,July,28,12,2025-07-12,1,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-029065,Resort Hotel,0,5,2024,October,42,18,2024-10-18,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,459.0,0,Transient-Party,51.0,0,0
HB-113721,City Hotel,0,80,2025,June,24,10,2025-06-10,0,1,2,1.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,162.0,0,0
HB-083738,City Hotel,0,0,2024,February,6,10,2024-02-10,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.0,0,0
HB-008027,Resort Hotel,1,211,2024,September,36,7,2024-09-07,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,D,D,0,Non Refund,1.0,,0,Transient,89.0,0,0
HB-103202,City Hotel,0,0,2024,December,50,14,2024-12-14,0,1,1,0.0,0,SC,PRT,Complementary,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,0.0,0,0
HB-034272,Resort Hotel,0,148,2025,March,11,11,2025-03-11,2,5,2,0.0,0,BB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,60,Transient-Party,34.0,0,0
HB-012667,Resort Hotel,1,21,2025,July,28,11,2025-07-11,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,269.0,0,Transient,135.0,0,0
HB-049710,City Hotel,1,33,2024,April,16,17,2024-04-17,2,3,1,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.1,0,0
HB-105597,City Hotel,0,14,2025,February,6,9,2025-02-09,0,3,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,158.0,0,0
HB-007837,Resort Hotel,1,25,2024,August,35,29,2024-08-29,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,189.0,0,2
HB-019780,Resort Hotel,0,11,2024,December,52,27,2024-12-27,0,1,2,0.0,0,HB,PRT,Online TA,Direct,1,0,0,D,D,0,No Deposit,240.0,,0,Group,109.0,1,3
HB-009953,Resort Hotel,1,18,2025,January,5,28,2025-01-28,0,1,2,0.0,0,HB,PRT,Complementary,Direct,0,0,0,G,G,0,No Deposit,,,0,Transient,0.0,0,1
HB-044269,City Hotel,0,164,2023,October,40,2,2023-10-02,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,B,0,No Deposit,19.0,,0,Transient-Party,100.0,0,0
HB-052562,City Hotel,1,56,2024,June,23,8,2024-06-08,0,1,2,0.0,0,BB,PRT,Offline TA/TO,Corporate,0,0,0,A,A,0,No Deposit,191.0,,0,Transient-Party,120.0,0,0
HB-031866,Resort Hotel,0,95,2025,January,2,8,2025-01-08,1,0,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,242.0,,0,Transient,37.8,0,1
HB-052147,City Hotel,1,113,2024,May,22,31,2024-05-31,0,3,1,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,A,0,Non Refund,,202.0,0,Transient,100.0,0,0
HB-048204,City Hotel,1,38,2024,March,12,18,2024-03-18,1,2,1,0.0,0,BB,LUX,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,131.4,0,0
HB-045233,City Hotel,1,50,2023,October,43,24,2023-10-24,0,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,146.0,0,0
HB-073668,City Hotel,1,48,2025,August,35,29,2025-08-29,1,5,1,0.0,0,BB,BLR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,139.0,0,0
HB-107337,City Hotel,0,102,2025,March,10,9,2025-03-09,0,3,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,79.2,0,0
HB-104289,City Hotel,0,75,2025,January,2,8,2025-01-08,2,1,1,0.0,0,BB,USA,Groups,TA/TO,0,0,0,D,D,0,No Deposit,330.0,,0,Transient-Party,67.0,0,2
HB-035305,Resort Hotel,0,69,2025,April,16,14,2025-04-14,2,2,2,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,111.5,0,0
HB-069790,City Hotel,1,161,2025,June,23,6,2025-06-06,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,144.0,0,1
HB-048420,City Hotel,1,77,2024,March,12,22,2024-03-22,0,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,95.7,0,2
HB-062206,City Hotel,1,78,2025,January,1,4,2025-01-04,0,4,2,1.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.4,0,0
HB-088032,City Hotel,0,100,2024,April,17,26,2024-04-26,0,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.08,0,1
HB-114115,City Hotel,0,196,2025,June,24,13,2025-06-13,0,4,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,128.25,0,0
HB-060417,City Hotel,1,7,2024,November,45,10,2024-11-10,0,2,2,1.0,0,BB,PRT,Complementary,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,0.0,0,2
HB-059811,City Hotel,1,38,2024,November,44,2,2024-11-02,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,77.23,0,3
HB-050725,City Hotel,1,101,2024,May,19,6,2024-05-06,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.9,0,0
HB-088012,City Hotel,0,0,2024,April,17,28,2024-04-28,0,1,1,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,E,0,No Deposit,94.0,,0,Transient-Party,45.0,0,2
HB-019262,Resort Hotel,1,40,2023,December,51,23,2023-12-23,0,2,1,0.0,0,Undefined,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,196.0,,0,Transient-Party,50.0,0,1
HB-104321,City Hotel,0,3,2025,January,2,9,2025-01-09,1,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,155.0,,0,Transient,97.5,0,3
HB-058519,City Hotel,1,461,2024,October,41,13,2024-10-13,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-081422,City Hotel,0,0,2024,June,24,14,2024-06-14,0,1,2,0.0,0,BB,PRT,Direct,Direct,1,0,2,A,A,0,No Deposit,,,0,Transient,50.0,0,0
HB-072644,City Hotel,1,208,2025,August,31,2,2025-08-02,0,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,125.0,0,0
HB-002318,Resort Hotel,1,78,2023,October,41,9,2023-10-09,1,2,2,0.0,0,FB,ESP,Groups,TA/TO,0,0,0,A,A,0,Non Refund,134.0,,0,Transient,92.0,0,0
HB-043693,City Hotel,0,83,2023,September,38,23,2023-09-23,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-118023,City Hotel,0,144,2025,August,32,10,2025-08-10,0,3,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,121.5,0,1
HB-111070,City Hotel,0,322,2025,May,19,5,2025-05-05,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,21.0,,0,Transient-Party,64.5,0,0
HB-031015,Resort Hotel,0,35,2024,December,49,8,2024-12-08,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-024671,Resort Hotel,0,87,2024,May,20,19,2024-05-19,3,8,2,0.0,0,FB,CN,Offline TA/TO,TA/TO,0,0,0,E,E,1,No Deposit,96.0,,0,Transient-Party,134.4,0,0
HB-113047,City Hotel,0,13,2025,May,22,29,2025-05-29,1,3,1,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,290.0,148.0,0,Transient,95.0,0,0
HB-118476,City Hotel,0,250,2025,August,33,14,2025-08-14,2,5,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,16.0,,0,Transient,112.1,0,0
HB-102157,City Hotel,0,215,2024,November,47,21,2024-11-21,1,2,1,0.0,0,BB,PRT,Groups,Corporate,0,0,0,A,D,2,No Deposit,,233.0,0,Transient,75.0,0,1
HB-015236,Resort Hotel,0,0,2024,March,11,14,2024-03-14,1,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,3,A,A,4,No Deposit,47.0,,0,Transient,30.0,0,0
HB-023259,Resort Hotel,0,32,2024,April,16,19,2024-04-19,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,E,0,No Deposit,,397.0,0,Transient-Party,50.0,0,0
HB-072264,City Hotel,1,106,2025,July,30,25,2025-07-25,0,1,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.0,0,0
HB-046684,City Hotel,0,38,2024,January,3,15,2024-01-15,1,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,55.59,0,0
HB-040330,City Hotel,1,20,2023,July,29,22,2023-07-22,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-078581,City Hotel,0,6,2023,October,41,12,2023-10-12,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-065244,City Hotel,1,629,2025,March,13,30,2025-03-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-090490,City Hotel,0,79,2024,June,23,7,2024-06-07,0,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,8.0,,0,Transient,132.6,0,1
HB-060731,City Hotel,1,45,2024,November,47,19,2024-11-19,1,1,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,86.4,0,0
HB-098855,City Hotel,0,201,2024,October,40,3,2024-10-03,1,2,3,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,D,D,3,No Deposit,9.0,,0,Transient,142.56,0,2
HB-046349,City Hotel,0,1,2023,December,52,30,2023-12-30,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,127.0,0,1
HB-036997,Resort Hotel,0,119,2025,June,23,3,2025-06-03,2,4,2,2.0,0,BB,IRL,Direct,Direct,0,0,0,G,G,1,No Deposit,250.0,,0,Transient-Party,175.0,0,1
HB-001410,Resort Hotel,0,34,2023,August,35,28,2023-08-28,0,2,2,0.0,1,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,120.6,0,3
HB-027418,Resort Hotel,0,39,2024,August,34,25,2024-08-25,1,3,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,270.5,1,1
HB-062538,City Hotel,1,38,2025,January,3,14,2025-01-14,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,Non Refund,,67.0,0,Transient,75.0,0,0
HB-032997,Resort Hotel,0,4,2025,February,7,11,2025-02-11,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,68.0,0,1
HB-079512,City Hotel,0,0,2023,October,43,24,2023-10-24,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,140.25,0,1
HB-092428,City Hotel,0,54,2024,July,27,3,2024-07-03,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,85.5,0,0
HB-107886,City Hotel,0,17,2025,March,12,18,2025-03-18,1,1,2,0.0,0,BB,SWE,Direct,Direct,0,0,0,G,G,0,No Deposit,,,0,Transient,233.0,0,1
HB-007718,Resort Hotel,1,14,2024,August,34,22,2024-08-22,1,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,198.0,0,0
HB-004663,Resort Hotel,0,142,2024,March,13,25,2024-03-25,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,26.0,,0,Transient,43.7,0,0
HB-085138,City Hotel,0,30,2024,March,10,5,2024-03-05,2,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.7,0,0
HB-087577,City Hotel,0,100,2024,April,16,19,2024-04-19,0,3,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient-Party,76.5,0,0
HB-104748,City Hotel,0,2,2025,January,3,19,2025-01-19,0,3,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,29.0,,0,Transient-Party,95.0,0,0
HB-067411,City Hotel,1,266,2025,May,18,3,2025-05-03,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,0,Transient,100.0,0,0
HB-039997,Resort Hotel,0,73,2025,August,35,28,2025-08-28,2,5,2,0.0,0,HB,IRL,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,314.0,,0,Transient,221.41,0,0
HB-101066,City Hotel,0,8,2024,November,45,5,2024-11-05,0,1,2,0.0,0,BB,CHN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,359.0,,0,Transient-Party,130.0,0,0
HB-110743,City Hotel,0,1,2025,April,18,30,2025-04-30,1,0,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,152.0,,0,Transient,88.56,0,0
HB-090560,City Hotel,0,247,2024,June,23,6,2024-06-06,1,1,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-091801,City Hotel,0,192,2024,June,26,24,2024-06-24,0,2,1,0.0,0,BB,SRB,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,34.0,,0,Transient-Party,95.0,0,0
HB-019522,Resort Hotel,0,297,2024,December,52,23,2024-12-23,1,2,2,0.0,0,HB,PRT,Direct,Direct,1,0,0,E,E,2,No Deposit,,,0,Transient-Party,60.87,0,3
HB-109516,City Hotel,0,256,2025,April,15,8,2025-04-08,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.8,0,2
HB-001599,Resort Hotel,0,52,2023,September,36,5,2023-09-05,2,5,2,0.0,0,FB,ESP,Offline TA/TO,TA/TO,0,0,0,A,B,1,No Deposit,149.0,,0,Transient,111.5,1,0
HB-107486,City Hotel,0,66,2025,March,11,10,2025-03-10,1,2,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,154.0,,0,Transient-Party,80.0,0,1
HB-000845,Resort Hotel,1,84,2023,August,31,1,2023-08-01,2,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,175.0,,0,Transient-Party,118.06,0,0
HB-084004,City Hotel,0,87,2024,February,7,14,2024-02-14,2,1,2,1.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,83.0,,0,Contract,117.79,0,1
HB-112720,City Hotel,0,1,2025,May,22,26,2025-05-26,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,E,1,No Deposit,,,0,Transient,160.0,0,1
HB-085036,City Hotel,0,30,2024,March,10,5,2024-03-05,2,1,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.1,0,2
HB-055966,City Hotel,1,412,2024,August,34,25,2024-08-25,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-007783,Resort Hotel,1,145,2024,August,35,26,2024-08-26,2,2,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,249.5,0,0
HB-086440,City Hotel,0,5,2024,April,14,2,2024-04-02,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,1
HB-055655,City Hotel,1,320,2024,August,33,18,2024-08-18,0,2,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,90.0,0,0
HB-005259,Resort Hotel,1,35,2024,April,17,23,2024-04-23,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,75.0,0,0
HB-020576,Resort Hotel,0,0,2024,February,5,3,2024-02-03,0,1,1,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,39.0,0,0
HB-051367,City Hotel,1,28,2024,May,20,19,2024-05-19,0,2,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,174.0,0,Transient-Party,100.0,0,0
HB-098072,City Hotel,0,296,2024,September,38,21,2024-09-21,0,4,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,26.0,,0,Transient-Party,117.0,0,1
HB-009094,Resort Hotel,1,206,2024,October,43,27,2024-10-27,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,4,No Deposit,240.0,,0,Transient,55.25,0,1
HB-075593,City Hotel,0,257,2023,July,26,1,2023-07-01,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,101.5,0,0
HB-034902,Resort Hotel,0,152,2025,April,14,5,2025-04-05,0,4,1,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,E,2,No Deposit,,223.0,0,Transient-Party,42.0,0,0
HB-098550,City Hotel,0,78,2024,September,39,29,2024-09-29,0,3,2,0.0,0,BB,USA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,95.0,0,1
HB-043557,City Hotel,0,57,2023,September,38,19,2023-09-19,2,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,66.53,0,1
HB-063369,City Hotel,1,12,2025,February,7,10,2025-02-10,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,0
HB-013645,Resort Hotel,1,20,2025,August,34,24,2025-08-24,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,255.0,0,1
HB-007016,Resort Hotel,1,144,2024,July,29,16,2024-07-16,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,253.0,,0,Transient,119.7,0,0
HB-012000,Resort Hotel,1,21,2025,June,23,8,2025-06-08,2,3,2,2.0,0,BB,IRL,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,180.0,0,1
HB-097734,City Hotel,0,89,2024,September,38,16,2024-09-16,2,2,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,3,No Deposit,9.0,,0,Transient,149.4,0,1
HB-052695,City Hotel,1,149,2024,June,23,9,2024-06-09,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,129.0,0,0
HB-098267,City Hotel,0,35,2024,September,39,26,2024-09-26,1,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,290.0,,0,Transient-Party,99.0,0,0
HB-091602,City Hotel,0,60,2024,June,25,21,2024-06-21,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,75.48,0,0
HB-019082,Resort Hotel,0,11,2023,December,49,5,2023-12-05,2,1,2,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,350.0,,0,Transient-Party,68.0,0,0
HB-094338,City Hotel,0,4,2024,August,31,2,2024-08-02,0,1,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,121.0,0,1
HB-004001,Resort Hotel,1,140,2024,February,7,12,2024-02-12,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,50.0,0,0
HB-077230,City Hotel,0,0,2023,September,37,14,2023-09-14,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,133.0,0,0
HB-111499,City Hotel,0,5,2025,May,19,8,2025-05-08,1,3,1,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,134.0,0,1
HB-106902,City Hotel,0,43,2025,February,8,23,2025-02-23,2,8,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,K,0,No Deposit,9.0,,0,Transient,116.28,0,0
HB-032992,Resort Hotel,0,9,2025,February,6,8,2025-02-08,0,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,55.0,1,1
HB-069429,City Hotel,1,74,2025,May,22,30,2025-05-30,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,165.0,0,0
HB-098809,City Hotel,0,1,2024,October,40,3,2024-10-03,1,1,2,0.0,0,BB,PRT,Complementary,Corporate,0,0,0,A,B,1,No Deposit,341.0,,0,Transient,0.0,1,2
HB-082222,City Hotel,1,317,2024,September,37,9,2024-09-09,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,58.0,,56,Transient,90.0,0,0
HB-018589,Resort Hotel,1,287,2024,August,34,25,2024-08-25,2,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,D,D,0,Non Refund,,,0,Transient,128.0,0,0
HB-058659,City Hotel,1,37,2024,October,41,13,2024-10-13,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,95.0,0,0
HB-069106,City Hotel,1,172,2025,May,21,25,2025-05-25,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.5,0,2
HB-068388,City Hotel,1,71,2025,May,20,16,2025-05-16,0,3,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,126.0,0,0
HB-036394,Resort Hotel,0,234,2025,May,20,13,2025-05-13,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient,55.71,0,1
HB-103738,City Hotel,0,4,2024,December,52,27,2024-12-27,0,4,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,112.2,0,2
HB-078059,City Hotel,0,11,2023,September,39,30,2023-09-30,0,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,10.0,,0,Group,113.4,0,0
HB-021723,Resort Hotel,0,49,2024,March,10,5,2024-03-05,2,2,1,0.0,0,HB,PRT,Groups,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient-Party,66.0,0,0
HB-002393,Resort Hotel,0,6,2023,October,41,11,2023-10-11,2,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,113.0,0,Transient,82.0,1,1
HB-093583,City Hotel,0,83,2024,July,30,23,2024-07-23,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,105.3,0,1
HB-053375,City Hotel,1,34,2024,June,25,19,2024-06-19,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,52.0,,0,Transient,81.0,0,0
HB-076819,City Hotel,0,1,2023,August,35,28,2023-08-28,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,2,A,A,0,No Deposit,40.0,,0,Transient,65.0,0,0
HB-073088,City Hotel,1,186,2025,August,33,14,2025-08-14,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.5,0,0
HB-037426,Resort Hotel,0,13,2025,June,24,11,2025-06-11,2,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,108.57,0,1
HB-078455,City Hotel,0,12,2023,October,40,5,2023-10-05,1,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,14.0,,0,Transient,114.0,0,3
HB-085849,City Hotel,0,0,2024,March,9,2,2024-03-02,6,15,1,0.0,0,BB,GNB,Direct,Direct,0,0,0,A,A,2,No Deposit,,,0,Transient-Party,75.65,0,0
HB-069918,City Hotel,1,183,2025,June,23,8,2025-06-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,86.0,,0,Transient,120.0,0,0
HB-016370,Resort Hotel,0,59,2023,August,33,20,2023-08-20,2,5,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,C,D,2,No Deposit,241.0,,0,Transient,127.59,0,2
HB-064725,City Hotel,1,92,2025,March,11,15,2025-03-15,0,3,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,85.0,0,0
HB-002207,Resort Hotel,0,52,2023,October,40,5,2023-10-05,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,171.0,,0,Transient,54.72,0,0
HB-102987,City Hotel,0,40,2024,December,49,7,2024-12-07,0,4,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,96.9,0,1
HB-110244,City Hotel,0,15,2025,April,16,20,2025-04-20,1,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,115.0,0,2
HB-069154,City Hotel,1,122,2025,May,22,26,2025-05-26,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.67,0,0
HB-114930,City Hotel,0,30,2025,June,26,26,2025-06-26,1,2,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,153.0,0,1
HB-083127,City Hotel,0,12,2024,January,3,19,2024-01-19,0,2,1,0.0,0,BB,JPN,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,19.0,,0,Transient-Party,71.0,0,0
HB-012924,Resort Hotel,1,175,2025,July,30,23,2025-07-23,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,198.0,0,0
HB-092851,City Hotel,0,13,2024,July,28,11,2024-07-11,1,1,1,0.0,0,BB,ESP,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,62.0,0,Transient,79.0,0,0
HB-050851,City Hotel,1,8,2024,May,19,10,2024-05-10,0,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,7.0,,0,Transient,108.57,0,1
HB-017721,Resort Hotel,0,287,2023,October,41,15,2023-10-15,1,3,1,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,1,No Deposit,,223.0,0,Transient-Party,43.0,1,0
HB-101440,City Hotel,0,3,2024,November,45,10,2024-11-10,0,2,1,0.0,0,BB,PRT,Aviation,Corporate,0,0,0,D,D,0,No Deposit,,153.0,0,Transient-Party,95.0,0,0
HB-066708,City Hotel,1,54,2025,April,17,23,2025-04-23,2,1,3,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,171.0,0,0
HB-103507,City Hotel,0,7,2024,December,50,13,2024-12-13,4,10,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,88.4,0,0
HB-004478,Resort Hotel,1,35,2024,March,12,19,2024-03-19,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,62.86,0,2
HB-108842,City Hotel,0,86,2025,March,13,29,2025-03-29,0,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.1,0,2
HB-003155,Resort Hotel,1,122,2023,November,47,20,2023-11-20,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,32.4,0,2
HB-049543,City Hotel,1,126,2024,April,15,14,2024-04-14,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,39,Transient,65.0,0,0
HB-079544,City Hotel,1,16,2023,November,44,4,2023-11-04,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,1,0,A,A,0,Non Refund,,122.0,0,Transient,95.0,0,0
HB-085250,City Hotel,0,37,2024,March,11,11,2024-03-11,0,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,71.1,0,0
HB-043697,City Hotel,1,83,2023,September,38,23,2023-09-23,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,60.0,0,0
HB-107115,City Hotel,0,137,2025,March,10,6,2025-03-06,1,1,2,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,80.0,0,1
HB-078144,City Hotel,0,16,2023,October,39,1,2023-10-01,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,111.75,0,1
HB-039427,Resort Hotel,0,10,2025,August,33,11,2025-08-11,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,40.0,0,Contract,135.0,0,3
HB-016388,Resort Hotel,0,3,2024,April,14,4,2024-04-04,1,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,3,A,D,1,No Deposit,,154.0,0,Transient,39.0,0,0
HB-079248,City Hotel,1,444,2024,December,48,1,2024-12-01,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,34.0,,39,Transient,75.0,0,0
HB-029410,Resort Hotel,0,362,2024,December,52,24,2024-12-24,1,1,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,1,E,E,2,No Deposit,57.0,,0,Contract,80.0,0,1
HB-003926,Resort Hotel,1,120,2024,February,6,6,2024-02-06,4,6,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,50.4,0,1
HB-047684,City Hotel,1,1,2024,February,9,28,2024-02-28,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,60.0,0,0
HB-017035,Resort Hotel,0,148,2023,September,36,8,2023-09-08,4,10,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,5.0,,0,Transient,52.14,1,0
HB-105633,City Hotel,0,17,2025,February,7,10,2025-02-10,1,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.0,1,0
HB-076398,City Hotel,0,273,2023,July,29,17,2023-07-17,0,2,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,87.0,0,0
HB-038472,Resort Hotel,0,90,2025,July,28,12,2025-07-12,2,5,1,2.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,242.0,,0,Transient,250.0,1,2
HB-100449,City Hotel,0,62,2024,October,43,25,2024-10-25,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,9.0,,0,Transient,111.6,0,1
HB-021448,Resort Hotel,0,4,2024,February,9,26,2024-02-26,1,2,2,0.0,0,FB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient,75.0,0,1
HB-018055,Resort Hotel,0,153,2023,October,43,29,2023-10-29,0,3,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,36.0,0,0
HB-084932,City Hotel,0,38,2024,March,9,3,2024-03-03,0,3,2,0.0,0,BB,POL,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,87.71,0,1
HB-059793,City Hotel,1,20,2024,November,44,1,2024-11-01,0,4,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,102.0,0,1
HB-091449,City Hotel,0,79,2024,June,24,16,2024-06-16,2,4,2,0.0,0,SC,AUT,Online TA,TA/TO,0,0,0,A,B,1,No Deposit,9.0,,0,Transient,120.6,0,0
HB-069978,City Hotel,1,169,2025,June,23,8,2025-06-08,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,170.0,0,0
HB-048919,City Hotel,1,44,2024,April,14,2,2024-04-02,1,1,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,0
HB-073243,City Hotel,1,283,2025,August,33,17,2025-08-17,0,3,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,134.1,0,1
HB-113026,City Hotel,0,126,2025,May,22,26,2025-05-26,2,4,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,0
HB-091368,City Hotel,0,110,2024,June,24,13,2024-06-13,2,5,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient-Party,119.85,0,4
HB-104963,City Hotel,0,33,2025,January,4,22,2025-01-22,2,3,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,22.0,,0,Transient,108.5,0,1
HB-045105,City Hotel,0,102,2023,October,42,16,2023-10-16,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,B,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-059987,City Hotel,1,78,2024,November,45,4,2024-11-04,1,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,80.0,0,1
HB-102949,City Hotel,0,79,2024,December,49,7,2024-12-07,0,3,3,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,105.0,0,0
HB-096947,City Hotel,0,230,2024,September,36,6,2024-09-06,0,5,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,44.0,,0,Transient-Party,137.0,0,1
HB-025187,Resort Hotel,0,152,2024,June,24,11,2024-06-11,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,40.0,,0,Contract,62.9,0,0
HB-025750,Resort Hotel,0,311,2024,June,26,26,2024-06-26,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,2.0,,0,Contract,70.0,0,0
HB-117996,City Hotel,0,19,2025,August,32,7,2025-08-07,1,5,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,239.0,1,3
HB-013662,Resort Hotel,1,90,2025,August,35,25,2025-08-25,2,2,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,270.0,0,1
HB-033466,Resort Hotel,0,64,2025,February,8,17,2025-02-17,2,5,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,47.25,0,1
HB-067099,City Hotel,1,0,2025,April,18,28,2025-04-28,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.5,0,1
HB-111380,City Hotel,0,111,2025,May,19,6,2025-05-06,2,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,92.17,0,1
HB-019235,Resort Hotel,1,92,2024,February,9,26,2024-02-26,1,2,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,134.0,,0,Transient,79.0,0,0
HB-023450,Resort Hotel,0,32,2024,April,16,19,2024-04-19,2,5,2,0.0,0,HB,GBR,Groups,Direct,0,0,0,D,D,0,No Deposit,273.0,,0,Transient-Party,69.36,0,0
HB-035546,Resort Hotel,0,203,2025,April,17,25,2025-04-25,0,2,2,0.0,0,HB,AUT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,502.0,,0,Transient-Party,90.0,0,0
HB-104130,City Hotel,0,29,2025,January,1,2,2025-01-02,1,3,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,129.7,0,1
HB-098464,City Hotel,0,18,2024,September,39,25,2024-09-25,2,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,B,0,No Deposit,138.0,,0,Transient,95.0,0,0
HB-028964,Resort Hotel,0,12,2024,October,42,17,2024-10-17,0,0,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,I,0,No Deposit,240.0,,0,Transient,0.0,0,2
HB-029397,Resort Hotel,0,116,2024,October,43,23,2024-10-23,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient-Party,70.0,0,1
HB-017786,Resort Hotel,0,7,2024,April,14,6,2024-04-06,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,4,A,D,0,No Deposit,,380.0,0,Transient,42.0,0,0
HB-103721,City Hotel,0,78,2024,December,52,27,2024-12-27,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,114.9,0,2
HB-088039,City Hotel,0,78,2024,April,17,26,2024-04-26,0,4,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-005170,Resort Hotel,1,208,2024,April,16,19,2024-04-19,2,5,1,0.0,0,HB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,273.0,,0,Transient,44.36,0,0
HB-079409,City Hotel,1,137,2024,January,4,27,2024-01-27,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,29.0,,45,Transient,70.0,0,0
HB-019927,Resort Hotel,0,11,2024,January,1,6,2024-01-06,0,4,2,0.0,0,HB,FRA,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,102.0,1,0
HB-070292,City Hotel,1,134,2025,June,24,14,2025-06-14,0,4,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,175.5,0,0
HB-090184,City Hotel,0,4,2024,May,22,30,2024-05-30,1,3,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,124.1,0,1
HB-009621,Resort Hotel,1,250,2024,December,51,20,2024-12-20,2,7,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,88.4,0,0
HB-107561,City Hotel,0,1,2025,March,11,14,2025-03-14,0,1,1,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,70.4,0,1
HB-087281,City Hotel,0,32,2024,April,15,14,2024-04-14,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,111.3,0,2
HB-083999,City Hotel,0,6,2024,February,7,16,2024-02-16,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.0,0,0
HB-047195,City Hotel,1,15,2024,February,7,12,2024-02-12,0,2,2,0.0,0,SC,AUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.0,0,0
HB-005177,Resort Hotel,1,208,2024,April,16,19,2024-04-19,2,5,1,0.0,0,HB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,273.0,,0,Transient,44.36,0,0
HB-083138,City Hotel,0,8,2024,January,3,19,2024-01-19,0,2,1,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,77.5,0,1
HB-022705,Resort Hotel,0,1,2024,April,14,2,2024-04-02,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,68.18,1,0
HB-084373,City Hotel,0,5,2024,February,8,22,2024-02-22,1,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,10.0,,0,Transient,77.1,0,0
HB-049952,City Hotel,1,288,2024,April,16,21,2024-04-21,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-052206,City Hotel,1,330,2024,June,22,2,2024-06-02,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-098295,City Hotel,0,144,2024,September,39,23,2024-09-23,2,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,129.6,0,2
HB-093283,City Hotel,0,32,2024,July,29,18,2024-07-18,1,1,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,39.0,,0,Transient-Party,85.0,0,0
HB-032122,Resort Hotel,0,41,2025,January,3,17,2025-01-17,0,0,1,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,0.0,0,0
HB-037224,Resort Hotel,0,115,2025,May,22,31,2025-05-31,2,9,2,0.0,0,HB,IRL,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,241.0,,0,Transient,140.21,0,0
HB-032590,Resort Hotel,0,1,2025,February,6,3,2025-02-03,13,32,1,0.0,0,BB,GBR,Direct,Direct,1,0,1,A,D,2,No Deposit,,,0,Transient,42.11,0,3
HB-115208,City Hotel,0,125,2025,June,27,30,2025-06-30,1,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,119.4,0,0
HB-079331,City Hotel,0,13,2023,October,42,18,2023-10-18,2,5,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,128.71,0,1
HB-006772,Resort Hotel,1,170,2024,July,27,1,2024-07-01,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,2.0,,0,Transient,57.8,0,0
HB-094208,City Hotel,0,301,2024,July,31,30,2024-07-30,1,1,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,90.0,0,0
HB-108391,City Hotel,0,67,2025,March,12,23,2025-03-23,0,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,133.2,0,1
HB-009600,Resort Hotel,1,52,2024,December,51,18,2024-12-18,2,2,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,56.0,0,0
HB-107829,City Hotel,0,96,2025,March,11,16,2025-03-16,0,3,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,79.2,0,3
HB-031150,Resort Hotel,0,0,2024,December,50,14,2024-12-14,0,2,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,44.0,0,0
HB-082282,City Hotel,0,19,2023,December,51,22,2023-12-22,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,58.0,0,1
HB-016291,Resort Hotel,0,14,2023,August,33,17,2023-08-17,1,4,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,279.0,1,2
HB-036732,Resort Hotel,0,388,2025,May,21,25,2025-05-25,0,3,1,0.0,0,BB,CN,Groups,TA/TO,0,0,0,E,E,1,No Deposit,96.0,,0,Transient-Party,72.0,0,0
HB-095865,City Hotel,0,0,2024,August,34,24,2024-08-24,0,1,1,0.0,0,BB,ITA,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,129.0,0,0
HB-108136,City Hotel,0,31,2025,March,12,19,2025-03-19,2,2,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,90.78,0,0
HB-093784,City Hotel,0,63,2024,July,30,24,2024-07-24,2,1,2,1.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,121.5,0,2
HB-046688,City Hotel,1,12,2024,January,3,15,2024-01-15,2,2,2,0.0,0,SC,OMN,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient-Party,77.0,0,0
HB-067810,City Hotel,1,105,2025,May,19,7,2025-05-07,2,4,2,0.0,0,HB,GBR,Direct,Direct,0,0,0,E,E,1,No Deposit,14.0,,0,Transient,216.33,0,1
HB-095765,City Hotel,0,17,2024,August,34,22,2024-08-22,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,1,No Deposit,,40.0,0,Transient,67.0,1,1
HB-013483,Resort Hotel,1,40,2025,August,33,17,2025-08-17,1,3,1,2.0,0,HB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,242.0,,0,Transient,311.5,0,1
HB-111775,City Hotel,0,168,2025,May,20,12,2025-05-12,1,2,2,0.0,0,BB,CHE,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient-Party,120.0,0,0
HB-035221,Resort Hotel,0,65,2025,April,15,13,2025-04-13,0,3,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,132.0,0,2
HB-084558,City Hotel,0,2,2024,February,9,27,2024-02-27,0,1,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.0,0,1
HB-056066,City Hotel,1,12,2024,August,35,28,2024-08-28,2,0,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.0,0,2
HB-057013,City Hotel,1,205,2024,September,38,16,2024-09-16,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,120.0,0,0
HB-054731,City Hotel,1,19,2024,July,30,25,2024-07-25,1,0,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,151.0,0,1
HB-023284,Resort Hotel,0,9,2024,April,16,20,2024-04-20,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,77.0,1,0
HB-008091,Resort Hotel,1,88,2024,September,37,11,2024-09-11,2,1,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,148.4,0,0
HB-056619,City Hotel,1,178,2024,September,37,9,2024-09-09,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,135.0,0,0
HB-066001,City Hotel,1,101,2025,April,15,12,2025-04-12,0,4,3,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,167.88,0,0
HB-101820,City Hotel,0,44,2024,November,46,14,2024-11-14,1,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.4,0,2
HB-035337,Resort Hotel,0,126,2025,April,16,17,2025-04-17,1,1,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,314.0,,0,Transient-Party,54.0,0,1
HB-072344,City Hotel,1,243,2025,July,30,26,2025-07-26,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-082279,City Hotel,1,205,2024,May,22,29,2024-05-29,2,1,3,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,1,Non Refund,26.0,,0,Transient,125.0,0,0
HB-081924,City Hotel,1,278,2024,August,32,11,2024-08-11,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,65.0,0,0
HB-053459,City Hotel,1,205,2024,June,25,20,2024-06-20,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,79.0,,0,Transient,80.24,0,0
HB-015838,Resort Hotel,0,143,2023,July,30,30,2023-07-30,2,3,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient-Party,90.95,0,1
HB-031025,Resort Hotel,0,57,2024,December,49,8,2024-12-08,0,3,3,0.0,0,FB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,6.0,,0,Transient-Party,114.07,0,0
HB-051938,City Hotel,0,316,2024,May,21,26,2024-05-26,0,3,2,0.0,0,BB,AUT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,110.0,0,0
HB-080211,City Hotel,0,50,2023,November,45,11,2023-11-11,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Transient,60.0,0,0
HB-014152,Resort Hotel,0,35,2025,April,17,27,2025-04-27,0,2,2,0.0,0,BB,PRT,Direct,Corporate,0,0,6,F,F,0,No Deposit,,,0,Transient,124.0,1,0
HB-042324,City Hotel,0,14,2023,September,36,4,2023-09-04,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,78.54,0,1
HB-093752,City Hotel,0,20,2024,July,30,23,2024-07-23,2,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,151.0,0,1
HB-031784,Resort Hotel,0,1,2025,January,1,4,2025-01-04,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient-Party,48.0,0,1
HB-066539,City Hotel,1,99,2025,April,17,21,2025-04-21,1,2,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,172.8,0,0
HB-039434,Resort Hotel,0,223,2025,August,33,13,2025-08-13,2,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,162.3,0,2
HB-064151,City Hotel,1,28,2025,March,9,2,2025-03-02,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,95.0,0,0
HB-116347,City Hotel,0,194,2025,July,28,12,2025-07-12,2,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,0
HB-059295,City Hotel,1,98,2024,October,43,26,2024-10-26,0,2,2,0.0,0,SC,DNK,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.1,0,0
HB-081280,City Hotel,0,24,2023,December,49,5,2023-12-05,2,1,2,0.0,0,BB,ITA,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,143.0,0,Transient-Party,50.0,0,0
HB-032813,Resort Hotel,0,29,2025,February,6,4,2025-02-04,1,1,2,0.0,0,HB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient-Party,74.1,0,2
HB-030683,Resort Hotel,0,76,2024,November,48,29,2024-11-29,0,2,1,0.0,0,BB,DNK,Corporate,Corporate,0,0,0,E,E,1,No Deposit,481.0,,0,Transient,50.0,0,0
HB-104237,City Hotel,0,28,2025,January,1,5,2025-01-05,1,3,2,0.0,0,BB,HRV,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,74.8,0,1
HB-052385,City Hotel,0,178,2024,June,23,4,2024-06-04,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,100.3,0,0
HB-033726,Resort Hotel,0,0,2025,February,9,27,2025-02-27,1,2,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,60.0,0,1
HB-084899,City Hotel,0,84,2024,March,9,3,2024-03-03,0,3,2,0.0,0,BB,AUT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,38.67,0,0
HB-030436,Resort Hotel,0,49,2024,November,46,16,2024-11-16,2,4,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient-Party,82.8,0,2
HB-038436,Resort Hotel,0,3,2025,July,28,11,2025-07-11,2,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,241.0,,0,Transient,132.8,0,1
HB-076431,City Hotel,1,358,2023,October,41,10,2023-10-10,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-081234,City Hotel,0,72,2023,December,49,5,2023-12-05,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Transient,60.0,0,0
HB-103849,City Hotel,0,44,2025,January,1,1,2025-01-01,1,0,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,65.0,0,0
HB-107016,City Hotel,0,104,2025,March,10,3,2025-03-03,1,2,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,151.2,1,2
HB-058924,City Hotel,1,237,2024,October,42,17,2024-10-17,1,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,B,1,No Deposit,9.0,,0,Transient,90.95,0,2
HB-057624,City Hotel,1,447,2024,September,39,29,2024-09-29,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-011971,Resort Hotel,1,149,2025,June,23,6,2025-06-06,0,1,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,140.0,0,0
HB-072896,City Hotel,1,36,2025,August,32,9,2025-08-09,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,229.0,,0,Transient-Party,112.67,0,0
HB-031837,Resort Hotel,0,0,2025,January,2,7,2025-01-07,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,44.0,0,0
HB-011634,Resort Hotel,1,220,2025,May,21,22,2025-05-22,3,7,2,0.0,0,HB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,86.5,0,0
HB-081037,City Hotel,1,86,2024,January,4,22,2024-01-22,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,29.0,,35,Transient,85.0,0,0
HB-099109,City Hotel,0,85,2024,October,40,6,2024-10-06,1,3,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,85.0,0,1
HB-064935,City Hotel,1,56,2025,March,12,21,2025-03-21,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,86.0,,0,Transient,85.0,0,0
HB-042103,City Hotel,0,7,2023,August,35,31,2023-08-31,1,2,1,0.0,0,HB,ISR,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,60.0,0,0
HB-089224,City Hotel,0,74,2024,May,20,15,2024-05-15,2,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,132.6,0,1
HB-056977,City Hotel,1,43,2024,September,38,16,2024-09-16,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,86.0,,0,Transient-Party,130.0,0,0
HB-045636,City Hotel,0,140,2023,November,46,18,2023-11-18,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,2,No Deposit,29.0,,87,Transient-Party,65.0,0,0
HB-051555,City Hotel,1,47,2024,May,21,21,2024-05-21,1,1,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,116.1,0,0
HB-095709,City Hotel,0,73,2024,August,34,19,2024-08-19,2,2,2,0.0,0,SC,RUS,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,63.75,0,0
HB-118455,City Hotel,0,30,2025,August,33,17,2025-08-17,0,3,2,1.0,0,BB,FRA,Direct,Direct,0,0,0,B,A,1,No Deposit,14.0,,0,Transient-Party,138.02,0,2
HB-031630,Resort Hotel,0,116,2024,December,1,30,2024-12-30,1,2,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,192.67,1,1
HB-073848,City Hotel,1,307,2023,August,33,20,2023-08-20,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-039801,Resort Hotel,0,17,2025,August,35,28,2025-08-28,1,3,3,0.0,0,FB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,5.0,,0,Transient,248.29,0,0
HB-114171,City Hotel,0,40,2025,June,25,17,2025-06-17,0,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,170.0,0,1
HB-109848,City Hotel,0,84,2025,April,16,15,2025-04-15,2,1,2,0.0,0,SC,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.0,0,2
HB-056440,City Hotel,1,277,2024,September,36,5,2024-09-05,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,80.0,0,0
HB-028833,Resort Hotel,0,12,2024,October,41,10,2024-10-10,1,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,66.0,0,2
HB-105458,City Hotel,0,126,2025,February,5,2,2025-02-02,2,5,2,0.0,1,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,79.2,0,0
HB-058806,City Hotel,1,258,2024,October,42,16,2024-10-16,1,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,0,Transient,110.0,0,0
HB-053137,City Hotel,1,344,2024,June,24,16,2024-06-16,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-020815,Resort Hotel,0,7,2024,February,6,10,2024-02-10,0,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,0.0,0,1
HB-069218,City Hotel,1,145,2025,May,22,27,2025-05-27,2,2,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,165.75,0,0
HB-076559,City Hotel,1,207,2023,September,39,29,2023-09-29,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,20.0,,0,Transient,48.0,0,0
HB-053930,City Hotel,1,6,2024,July,27,2,2024-07-02,1,1,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,132.0,0,0
HB-109931,City Hotel,0,14,2025,April,16,16,2025-04-16,2,1,2,0.0,0,SC,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,115.0,0,0
HB-110702,City Hotel,0,237,2025,April,18,28,2025-04-28,1,2,2,0.0,0,SC,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,72.42,0,2
HB-016402,Resort Hotel,0,87,2023,August,33,14,2023-08-14,4,10,3,0.0,0,FB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,175.0,,0,Transient,209.2,1,0
HB-111791,City Hotel,0,78,2025,May,19,9,2025-05-09,1,5,2,0.0,0,HB,ARG,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,132.0,0,1
HB-037591,Resort Hotel,0,125,2025,June,25,20,2025-06-20,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,F,0,No Deposit,240.0,,0,Transient,150.0,0,1
HB-003092,Resort Hotel,0,0,2023,November,46,16,2023-11-16,0,0,2,1.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,0.0,0,1
HB-015964,Resort Hotel,0,51,2023,August,31,3,2023-08-03,1,5,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,240.0,,0,Transient,173.0,0,0
HB-003058,Resort Hotel,1,3,2023,November,45,12,2023-11-12,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,1,No Deposit,334.0,281.0,0,Transient-Party,40.0,0,0
HB-057923,City Hotel,1,285,2024,October,40,3,2024-10-03,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,24,Transient,100.0,0,0
HB-062815,City Hotel,1,59,2025,January,4,23,2025-01-23,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,326.0,,0,Transient,80.0,0,0
HB-031711,Resort Hotel,0,0,2025,January,1,4,2025-01-04,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,E,0,No Deposit,,,0,Transient,64.0,0,0
HB-083962,City Hotel,0,2,2024,February,6,10,2024-02-10,2,4,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.0,0,0
HB-056721,City Hotel,1,111,2024,September,37,11,2024-09-11,2,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.8,0,2
HB-034550,Resort Hotel,0,152,2025,March,11,15,2025-03-15,4,10,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient,54.21,1,0
HB-053623,City Hotel,1,172,2024,June,26,26,2024-06-26,2,0,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.5,0,0
HB-048884,City Hotel,1,57,2024,April,14,1,2024-04-01,1,2,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,81.9,0,0
HB-059967,City Hotel,1,305,2024,November,45,4,2024-11-04,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,89.0,0,0
HB-023661,Resort Hotel,0,69,2024,April,17,26,2024-04-26,0,4,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,26.0,,0,Transient,39.95,0,0
HB-028544,Resort Hotel,0,5,2024,October,40,4,2024-10-04,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,131.0,1,1
HB-027562,Resort Hotel,0,20,2024,August,35,28,2024-08-28,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,175.8,0,1
HB-087874,City Hotel,0,71,2024,April,17,24,2024-04-24,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,112.8,0,0
HB-093386,City Hotel,0,1,2024,July,29,20,2024-07-20,0,1,1,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,86.0,,0,Transient,93.0,0,0
HB-069615,City Hotel,1,80,2025,June,23,2,2025-06-02,1,2,3,1.0,0,BB,FRA,Direct,Direct,0,0,0,F,F,0,No Deposit,14.0,,0,Transient,285.0,0,0
HB-024041,Resort Hotel,0,28,2024,May,19,10,2024-05-10,0,1,2,0.0,0,BB,CHE,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,251.0,,0,Transient,59.0,0,0
HB-055881,City Hotel,1,137,2024,August,34,23,2024-08-23,0,4,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,133.2,0,0
HB-092066,City Hotel,0,37,2024,June,26,29,2024-06-29,0,1,3,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,G,0,No Deposit,22.0,,0,Transient,111.6,0,1
HB-006761,Resort Hotel,1,20,2024,June,26,30,2024-06-30,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,129.0,0,0
HB-119066,City Hotel,0,518,2025,August,35,26,2025-08-26,2,1,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,1
HB-110605,City Hotel,0,12,2025,April,18,28,2025-04-28,0,1,1,0.0,0,SC,FIN,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,150.0,0,0
HB-009827,Resort Hotel,1,66,2025,January,2,7,2025-01-07,2,2,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,42.0,0,1
HB-039959,Resort Hotel,0,38,2025,August,35,27,2025-08-27,2,5,1,2.0,0,BB,IRL,Online TA,TA/TO,0,0,0,G,G,1,No Deposit,240.0,,0,Transient,284.29,0,1
HB-048507,City Hotel,1,85,2024,March,12,24,2024-03-24,2,3,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,9.0,,0,Transient-Party,157.25,0,1
HB-081881,City Hotel,1,178,2024,April,17,28,2024-04-28,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,46,Transient,110.0,0,0
HB-069633,City Hotel,1,20,2025,June,23,2,2025-06-02,2,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,170.0,0,1
HB-108746,City Hotel,0,54,2025,March,13,28,2025-03-28,0,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,100.3,0,1
HB-061023,City Hotel,1,63,2024,November,48,29,2024-11-29,0,4,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.4,0,1
HB-000097,Resort Hotel,1,63,2023,July,27,3,2023-07-03,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,242.0,,0,Transient,117.0,0,1
HB-110708,City Hotel,0,28,2025,April,18,29,2025-04-29,1,1,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,124.0,0,1
HB-095732,City Hotel,0,320,2024,August,34,20,2024-08-20,2,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Contract,94.95,0,1
HB-106532,City Hotel,0,0,2025,February,9,25,2025-02-25,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,108.0,0,0
HB-027417,Resort Hotel,0,15,2024,August,35,27,2024-08-27,1,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,171.47,1,1
HB-084517,City Hotel,0,10,2024,February,8,24,2024-02-24,0,4,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,93.0,0,1
HB-026609,Resort Hotel,0,136,2024,August,31,4,2024-08-04,0,2,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,223.0,0,1
HB-094612,City Hotel,0,110,2024,August,31,1,2024-08-01,1,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,120.3,0,1
HB-096482,City Hotel,0,2,2024,September,36,2,2024-09-02,0,1,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,249.0,1,1
HB-027357,Resort Hotel,0,193,2024,August,34,20,2024-08-20,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,196.0,,0,Transient-Party,153.29,0,0
HB-105970,City Hotel,0,114,2025,February,7,15,2025-02-15,0,4,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,242.0,0,Transient-Party,78.0,0,0
HB-098089,City Hotel,0,276,2024,September,38,22,2024-09-22,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,178,Transient-Party,116.33,0,0
HB-013818,Resort Hotel,0,1,2025,February,8,21,2025-02-21,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,1,A,A,0,No Deposit,94.0,,0,Transient-Party,35.0,0,0
HB-008402,Resort Hotel,1,168,2024,September,39,26,2024-09-26,3,5,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,108.26,0,0
HB-045529,City Hotel,0,67,2023,November,44,1,2023-11-01,2,1,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Group,32.71,0,0
HB-108436,City Hotel,0,67,2025,March,13,25,2025-03-25,1,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,133.2,0,1
HB-108852,City Hotel,0,64,2025,March,13,30,2025-03-30,1,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-061529,City Hotel,1,23,2024,December,51,16,2024-12-16,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,104.0,0,0
HB-027490,Resort Hotel,0,32,2024,August,35,30,2024-08-30,0,1,3,1.0,0,BB,BEL,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,274.0,2,1
HB-011723,Resort Hotel,1,67,2025,May,22,27,2025-05-27,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,115.0,0,2
HB-105524,City Hotel,0,23,2025,February,6,7,2025-02-07,0,4,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,2
HB-044046,City Hotel,1,92,2023,September,39,30,2023-09-30,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-037212,Resort Hotel,0,131,2025,June,22,1,2025-06-01,2,8,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,314.0,,0,Transient-Party,102.8,0,1
HB-104205,City Hotel,0,4,2025,January,2,7,2025-01-07,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,115.0,1,0
HB-098646,City Hotel,0,261,2024,October,40,1,2024-10-01,1,1,1,0.0,0,HB,ITA,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,73.0,0,0
HB-001048,Resort Hotel,1,34,2023,August,32,11,2023-08-11,2,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,274.93,0,2
HB-010354,Resort Hotel,1,63,2025,February,9,28,2025-02-28,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,332.0,,14,Transient,35.0,0,0
HB-114852,City Hotel,0,29,2025,June,26,27,2025-06-27,0,1,1,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,2
HB-061443,City Hotel,1,333,2024,December,50,10,2024-12-10,2,3,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,73.95,0,0
HB-108450,City Hotel,0,9,2025,March,12,23,2025-03-23,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,7.0,,0,Transient,190.4,0,1
HB-042533,City Hotel,0,67,2023,September,36,6,2023-09-06,2,2,2,0.0,0,HB,FRA,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,80.0,0,1
HB-085911,City Hotel,0,56,2024,March,12,20,2024-03-20,2,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient-Party,119.75,1,1
HB-001875,Resort Hotel,1,36,2023,September,38,19,2023-09-19,2,2,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,242.0,,0,Transient,162.0,0,1
HB-075147,City Hotel,1,278,2023,July,29,22,2023-07-22,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-094665,City Hotel,0,67,2024,August,31,4,2024-08-04,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.9,0,1
HB-089468,City Hotel,0,189,2024,May,20,19,2024-05-19,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,65.0,0,0
HB-060963,City Hotel,1,133,2024,November,48,27,2024-11-27,2,3,3,0.0,0,BB,GRC,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,115.6,0,0
HB-059161,City Hotel,1,240,2024,October,43,21,2024-10-21,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,110.0,0,0
HB-045851,City Hotel,0,98,2023,November,47,23,2023-11-23,1,3,1,0.0,0,BB,HRV,Groups,TA/TO,0,0,0,A,A,1,No Deposit,37.0,,0,Transient-Party,70.0,0,0
HB-054948,City Hotel,1,132,2024,July,31,31,2024-07-31,2,5,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,121.37,0,0
HB-055532,City Hotel,1,148,2024,August,33,15,2024-08-15,1,3,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,136.43,0,1
HB-088652,City Hotel,0,190,2024,May,19,6,2024-05-06,2,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,8.0,,0,Transient,100.3,0,0
HB-082317,City Hotel,0,3,2023,December,52,25,2023-12-25,1,2,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-029685,Resort Hotel,0,1,2024,November,44,2,2024-11-02,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,85.0,0,0
HB-088176,City Hotel,0,67,2024,April,18,30,2024-04-30,1,1,3,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,219.6,1,2
HB-077231,City Hotel,1,18,2023,October,40,3,2023-10-03,2,5,1,0.0,0,SC,PRT,Online TA,TA/TO,1,1,0,A,A,0,No Deposit,15.0,,0,Transient,78.17,0,0
HB-094196,City Hotel,0,179,2024,July,30,28,2024-07-28,1,3,2,0.0,0,BB,NLD,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,85.0,0,0
HB-008566,Resort Hotel,0,383,2024,October,40,6,2024-10-06,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,315.0,,0,Transient-Party,48.0,0,0
HB-080587,City Hotel,0,2,2023,November,46,18,2023-11-18,0,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,107.0,0,0
HB-068386,City Hotel,1,71,2025,May,20,16,2025-05-16,0,3,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,126.0,0,0
HB-016664,Resort Hotel,0,0,2023,September,36,5,2023-09-05,0,1,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,G,0,No Deposit,,,0,Transient,172.0,1,0
HB-100905,City Hotel,0,2,2024,November,44,2,2024-11-02,0,2,1,0.0,0,BB,AUT,Aviation,Corporate,0,0,0,D,D,0,No Deposit,,153.0,0,Transient,94.0,0,0
HB-115692,City Hotel,0,95,2025,July,28,7,2025-07-07,1,2,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,108.0,0,1
HB-112708,City Hotel,0,14,2025,May,21,25,2025-05-25,0,3,3,0.0,0,BB,ECU,Direct,Direct,0,0,0,G,G,0,No Deposit,14.0,,0,Transient,335.0,0,0
HB-030558,Resort Hotel,0,11,2024,November,48,26,2024-11-26,0,1,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,241.0,,0,Transient,49.75,0,1
HB-105694,City Hotel,0,6,2025,February,7,13,2025-02-13,1,0,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,143.0,0,1
HB-013089,Resort Hotel,1,2,2025,July,31,31,2025-07-31,1,1,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,250.0,0,1
HB-005179,Resort Hotel,1,32,2024,April,16,19,2024-04-19,2,5,2,0.0,0,HB,PRT,Groups,Direct,0,0,0,D,D,0,No Deposit,273.0,,0,Transient-Party,69.36,0,0
HB-065388,City Hotel,1,44,2025,April,14,2,2025-04-02,2,0,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,102.6,0,0
HB-090991,City Hotel,0,255,2024,June,24,14,2024-06-14,0,1,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,87.0,0,0
HB-060348,City Hotel,1,277,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-113757,City Hotel,0,33,2025,June,23,4,2025-06-04,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,120.51,0,1
HB-087778,City Hotel,0,44,2024,April,17,23,2024-04-23,2,1,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,24.0,,0,Transient-Party,85.0,0,0
HB-105546,City Hotel,0,3,2025,February,6,4,2025-02-04,2,5,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,0
HB-105193,City Hotel,0,1,2025,February,5,1,2025-02-01,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,426.0,0,Transient,80.0,0,0
HB-087500,City Hotel,0,27,2024,April,16,20,2024-04-20,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,E,0,No Deposit,,179.0,0,Transient,89.0,0,0
HB-004700,Resort Hotel,0,147,2024,March,13,28,2024-03-28,2,5,2,0.0,0,HB,LUX,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,,,0,Transient-Party,73.0,0,0
HB-114554,City Hotel,0,183,2025,June,25,21,2025-06-21,0,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,89.1,0,0
HB-048677,City Hotel,1,92,2024,March,13,26,2024-03-26,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,170.0,,0,Transient,100.0,0,0
HB-042733,City Hotel,0,85,2023,September,36,9,2023-09-09,0,2,1,0.0,0,BB,FRA,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,68.0,0,Transient-Party,90.0,0,0
HB-040420,City Hotel,1,110,2023,July,30,25,2023-07-25,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-070552,City Hotel,1,125,2025,June,25,18,2025-06-18,2,0,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,0
HB-108479,City Hotel,0,65,2025,March,13,25,2025-03-25,2,1,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,142.2,0,0
HB-019191,Resort Hotel,1,92,2024,February,9,26,2024-02-26,1,2,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,134.0,,0,Transient,79.0,0,0
HB-008365,Resort Hotel,1,22,2024,September,39,24,2024-09-24,1,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,119.0,0,0
HB-048918,City Hotel,1,57,2024,April,14,2,2024-04-02,1,1,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,82.8,0,0
HB-117257,City Hotel,0,69,2025,July,30,26,2025-07-26,2,4,2,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,476.0,,0,Transient,95.37,0,1
HB-105445,City Hotel,0,8,2025,February,6,6,2025-02-06,1,2,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,88.0,0,0
HB-008187,Resort Hotel,0,336,2024,September,37,15,2024-09-15,2,3,2,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,A,1,No Deposit,,223.0,0,Transient-Party,73.2,0,0
HB-031864,Resort Hotel,0,60,2025,January,2,8,2025-01-08,1,0,2,2.0,1,BB,BRA,Online TA,TA/TO,0,0,0,G,G,1,No Deposit,240.0,,0,Transient,89.0,1,0
HB-117688,City Hotel,0,47,2025,August,31,3,2025-08-03,2,3,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,126.0,0,0
HB-044343,City Hotel,0,61,2023,October,40,4,2023-10-04,2,0,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,91.0,0,0
HB-089012,City Hotel,0,129,2024,May,20,13,2024-05-13,1,2,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,173.0,,0,Transient,80.75,0,2
HB-012934,Resort Hotel,1,134,2025,July,30,24,2025-07-24,1,3,2,0.0,0,BB,GIB,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,200.0,0,1
HB-003931,Resort Hotel,0,143,2024,February,6,8,2024-02-08,1,1,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,41.4,0,1
HB-020267,Resort Hotel,0,3,2024,January,3,21,2024-01-21,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,40.0,0,2
HB-037926,Resort Hotel,0,178,2025,June,26,26,2025-06-26,2,5,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,C,C,2,No Deposit,314.0,,0,Transient,106.56,1,1
HB-021885,Resort Hotel,0,30,2024,March,10,7,2024-03-07,1,5,2,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,38.0,,0,Transient-Party,65.4,0,0
HB-086359,City Hotel,0,83,2024,March,13,28,2024-03-28,1,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,16.0,,0,Transient,80.75,0,0
HB-066073,City Hotel,1,85,2025,April,15,13,2025-04-13,1,3,3,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,202.5,0,2
HB-106381,City Hotel,0,153,2025,February,8,21,2025-02-21,0,4,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,119.0,0,2
HB-053822,City Hotel,1,11,2024,June,26,30,2024-06-30,0,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,139.0,0,1
HB-114576,City Hotel,0,113,2025,June,25,18,2025-06-18,2,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-021101,Resort Hotel,0,28,2024,February,6,10,2024-02-10,2,6,2,0.0,0,HB,NLD,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,171.0,,0,Transient,55.0,0,1
HB-115972,City Hotel,0,11,2025,July,28,10,2025-07-10,1,2,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,111.47,0,0
HB-073578,City Hotel,1,9,2025,August,35,26,2025-08-26,2,5,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,232.57,0,1
HB-098335,City Hotel,0,1,2024,September,39,27,2024-09-27,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,190.0,0,1
HB-117425,City Hotel,0,3,2025,August,35,31,2025-08-31,0,1,2,1.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,40.0,0,Transient,95.0,0,4
HB-062031,City Hotel,1,220,2024,December,1,30,2024-12-30,2,2,3,0.0,0,BB,CHL,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,114.75,0,1
HB-069623,City Hotel,1,129,2025,June,23,2,2025-06-02,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,154.0,,0,Transient,130.0,0,0
HB-043701,City Hotel,0,83,2023,September,38,23,2023-09-23,0,2,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-047688,City Hotel,1,1,2024,February,9,28,2024-02-28,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,60.0,0,0
HB-041445,City Hotel,0,137,2023,August,33,16,2023-08-16,1,0,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,0
HB-000620,Resort Hotel,0,73,2023,July,29,23,2023-07-23,0,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,I,1,No Deposit,240.0,,0,Transient,0.0,0,1
HB-008963,Resort Hotel,1,178,2024,October,43,22,2024-10-22,2,2,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,70.75,0,0
HB-044983,City Hotel,1,102,2023,October,42,16,2023-10-16,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-078437,City Hotel,0,0,2023,October,40,7,2023-10-07,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,B,0,No Deposit,1.0,,0,Transient-Party,138.0,0,0
HB-032310,Resort Hotel,0,4,2025,January,5,28,2025-01-28,0,1,2,0.0,0,BB,PRT,Direct,Direct,1,0,1,D,D,0,No Deposit,,,0,Transient,55.0,1,2
HB-025368,Resort Hotel,0,146,2024,June,24,13,2024-06-13,3,8,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,8.0,,0,Transient,81.02,0,0
HB-000074,Resort Hotel,0,15,2023,July,27,3,2023-07-03,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,114.5,0,0
HB-099025,City Hotel,0,6,2024,October,40,4,2024-10-04,0,4,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,0
HB-100090,City Hotel,0,27,2024,October,42,20,2024-10-20,0,3,2,0.0,1,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,85.0,0,1
HB-038625,Resort Hotel,0,130,2025,July,29,20,2025-07-20,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,170.0,0,1
HB-032477,Resort Hotel,0,6,2025,January,4,22,2025-01-22,2,4,2,0.0,0,HB,ESP,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,108.0,1,0
HB-054767,City Hotel,1,156,2024,July,30,26,2024-07-26,0,1,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,105.3,0,1
HB-007159,Resort Hotel,1,140,2024,July,30,24,2024-07-24,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,207.0,0,0
HB-003678,Resort Hotel,0,165,2023,December,52,30,2023-12-30,0,4,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,308.0,,122,Transient-Party,136.5,0,0
HB-015877,Resort Hotel,0,6,2025,May,20,16,2025-05-16,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,5,A,E,0,No Deposit,,103.0,0,Transient,45.0,0,0
HB-020713,Resort Hotel,0,0,2024,February,6,5,2024-02-05,1,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,64.33,0,0
HB-046728,City Hotel,0,42,2024,January,3,17,2024-01-17,2,0,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,75.95,0,1
HB-118630,City Hotel,0,98,2025,August,33,16,2025-08-16,2,5,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,42.0,,0,Transient,81.39,0,1
HB-110337,City Hotel,0,69,2025,April,17,21,2025-04-21,2,3,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,108.0,0,0
HB-087807,City Hotel,0,2,2024,April,17,23,2024-04-23,2,1,2,2.0,0,BB,RUS,Online TA,TA/TO,0,0,0,D,G,1,No Deposit,9.0,,0,Transient,244.8,0,1
HB-074411,City Hotel,1,290,2023,August,31,3,2023-08-03,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-018358,Resort Hotel,1,82,2024,February,6,7,2024-02-07,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,67.0,,0,Transient-Party,86.0,0,0
HB-011873,Resort Hotel,1,282,2025,June,23,2,2025-06-02,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,80.1,0,1
HB-079971,City Hotel,0,0,2023,November,45,7,2023-11-07,1,1,1,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Group,73.15,0,0
HB-103933,City Hotel,0,0,2025,January,1,3,2025-01-03,0,2,2,0.0,0,BB,USA,Direct,Direct,1,0,1,D,D,0,No Deposit,14.0,,0,Transient,108.0,0,0
HB-004571,Resort Hotel,1,56,2024,March,12,24,2024-03-24,0,3,2,2.0,0,BB,PRT,Direct,Direct,0,0,0,G,G,0,No Deposit,250.0,,0,Transient,110.0,0,0
HB-100269,City Hotel,0,386,2024,October,43,23,2024-10-23,2,0,2,0.0,0,HB,AUT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-075554,City Hotel,0,257,2023,July,26,1,2023-07-01,0,2,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient,80.0,0,0
HB-064919,City Hotel,1,52,2025,March,12,20,2025-03-20,1,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,92.88,0,0
HB-068017,City Hotel,1,171,2025,May,19,11,2025-05-11,0,3,1,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,136.8,0,0
HB-023537,Resort Hotel,0,0,2024,April,17,27,2024-04-27,0,1,2,0.0,0,BB,ESP,Online TA,Direct,0,0,0,A,A,2,No Deposit,,,0,Transient,65.0,0,1
HB-052713,City Hotel,1,135,2024,June,23,9,2024-06-09,0,3,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,116.1,0,0
HB-043957,City Hotel,1,88,2023,September,39,26,2023-09-26,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-116118,City Hotel,0,251,2025,July,28,8,2025-07-08,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,2
HB-018754,Resort Hotel,0,2,2023,November,48,28,2023-11-28,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,58.0,0,1
HB-117597,City Hotel,0,106,2025,August,31,3,2025-08-03,1,3,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,226.0,1,0
HB-075820,City Hotel,1,330,2023,September,37,12,2023-09-12,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-026899,Resort Hotel,0,32,2024,August,33,12,2024-08-12,0,2,1,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,254.0,0,1
HB-009867,Resort Hotel,1,45,2025,January,3,14,2025-01-14,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,37.8,0,1
HB-002111,Resort Hotel,0,145,2023,October,39,1,2023-10-01,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Contract,55.43,0,0
HB-046271,City Hotel,1,119,2023,December,52,28,2023-12-28,2,5,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,11.0,,0,Transient,46.51,0,1
HB-063678,City Hotel,1,63,2025,February,8,17,2025-02-17,0,2,2,0.0,0,SC,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,2
HB-090701,City Hotel,0,58,2024,June,23,8,2024-06-08,0,2,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,138.6,0,2
HB-082074,City Hotel,0,2,2024,October,43,23,2024-10-23,0,0,2,0.0,1,BB,PRT,Complementary,Direct,1,0,1,D,D,0,No Deposit,,45.0,0,Transient,0.0,0,1
HB-013442,Resort Hotel,1,221,2025,August,33,15,2025-08-15,1,5,1,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,224.33,0,2
HB-083370,City Hotel,0,1,2024,January,4,28,2024-01-28,0,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.0,0,0
HB-019577,Resort Hotel,0,14,2023,December,51,21,2023-12-21,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,69.0,1,0
HB-031449,Resort Hotel,0,47,2024,December,51,22,2024-12-22,2,5,1,0.0,0,Undefined,FRA,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,464.0,,0,Transient-Party,69.64,0,1
HB-027462,Resort Hotel,0,28,2024,August,35,27,2024-08-27,2,1,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,236.0,1,1
HB-116393,City Hotel,0,113,2025,July,29,17,2025-07-17,1,1,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,135.0,0,1
HB-077595,City Hotel,0,7,2024,July,28,11,2024-07-11,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,16,A,D,1,No Deposit,,40.0,0,Transient,67.0,0,1
HB-034872,Resort Hotel,0,81,2025,April,14,1,2025-04-01,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,314.0,,0,Transient,64.49,0,0
HB-115336,City Hotel,0,141,2025,June,27,30,2025-06-30,2,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,80.1,0,1
HB-112721,City Hotel,0,293,2025,May,21,25,2025-05-25,0,3,2,0.0,0,BB,DNK,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,132.6,0,1
HB-106285,City Hotel,0,48,2025,February,8,22,2025-02-22,0,2,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,65.0,0,1
HB-018673,Resort Hotel,0,0,2023,November,47,25,2023-11-25,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,38.0,0,0
HB-111289,City Hotel,0,128,2025,May,19,6,2025-05-06,2,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-011240,Resort Hotel,1,172,2025,April,18,29,2025-04-29,2,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,314.0,,0,Transient,86.91,0,0
HB-012921,Resort Hotel,1,195,2025,July,30,23,2025-07-23,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,153.75,0,0
HB-078278,City Hotel,0,19,2023,October,40,7,2023-10-07,0,1,1,0.0,0,BB,ESP,Corporate,Corporate,0,0,0,A,D,1,No Deposit,,,0,Transient,85.5,0,0
HB-049755,City Hotel,1,1,2024,April,16,19,2024-04-19,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,E,1,No Deposit,214.0,,0,Transient-Party,107.0,0,0
HB-008955,Resort Hotel,1,4,2024,October,43,21,2024-10-21,2,4,2,0.0,0,BB,PRT,Groups,Corporate,0,0,0,G,G,0,No Deposit,,,0,Transient-Party,8.0,0,0
HB-023669,Resort Hotel,0,33,2024,April,17,25,2024-04-25,1,4,1,0.0,0,BB,USA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,37.1,0,0
HB-037709,Resort Hotel,0,207,2025,June,25,16,2025-06-16,3,7,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,110.0,0,1
HB-092885,City Hotel,0,3,2024,July,28,11,2024-07-11,1,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,275.0,0,Transient,118.15,0,0
HB-020192,Resort Hotel,0,0,2024,January,2,14,2024-01-14,2,4,1,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,0.0,0,1
HB-008328,Resort Hotel,0,343,2024,September,38,21,2024-09-21,0,4,2,0.0,0,HB,BEL,Corporate,Corporate,0,0,0,A,C,0,No Deposit,183.0,,0,Transient-Party,92.0,0,0
HB-020626,Resort Hotel,0,1,2024,February,5,2,2024-02-02,0,3,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,68.0,0,2
HB-049794,City Hotel,1,1,2024,April,16,19,2024-04-19,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,214.0,,0,Transient-Party,107.0,0,0
HB-015387,Resort Hotel,0,123,2023,July,27,5,2023-07-05,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,196.0,,0,Transient,58.95,0,1
HB-088497,City Hotel,0,166,2024,May,18,3,2024-05-03,0,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,89.25,0,0
HB-080272,City Hotel,0,3,2023,November,46,13,2023-11-13,1,2,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Contract,64.0,0,0
HB-046011,City Hotel,0,95,2023,December,49,5,2023-12-05,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,72.25,0,2
HB-113241,City Hotel,0,240,2025,June,23,3,2025-06-03,0,1,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,157.5,0,1
HB-052418,City Hotel,1,51,2024,June,23,5,2024-06-05,2,5,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,D,D,0,No Deposit,,216.0,0,Transient,110.0,0,0
HB-042211,City Hotel,0,20,2023,September,35,2,2023-09-02,0,4,2,0.0,0,BB,TWN,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,7.0,,0,Transient,80.85,0,2
HB-003015,Resort Hotel,0,61,2023,November,45,11,2023-11-11,0,4,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,C,3,No Deposit,281.0,,0,Contract,48.0,0,0
HB-035275,Resort Hotel,0,72,2025,April,15,13,2025-04-13,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,93.75,0,1
HB-064571,City Hotel,1,52,2025,March,11,13,2025-03-13,1,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,56.0,,0,Transient,80.0,0,0
HB-105723,City Hotel,0,27,2025,February,7,12,2025-02-12,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-113319,City Hotel,0,98,2025,June,23,2,2025-06-02,1,2,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.33,0,1
HB-020130,Resort Hotel,0,12,2024,January,3,16,2024-01-16,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,2
HB-096490,City Hotel,0,34,2024,August,35,27,2024-08-27,2,5,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,103.89,0,1
HB-073480,City Hotel,1,159,2025,August,34,23,2025-08-23,0,4,3,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,7.0,,0,Transient,225.48,0,1
HB-075227,City Hotel,1,294,2023,August,32,7,2023-08-07,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-012983,Resort Hotel,1,174,2025,July,30,26,2025-07-26,1,4,1,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,242.0,,0,Transient,212.16,0,0
HB-071864,City Hotel,1,183,2025,July,29,14,2025-07-14,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,117.9,0,0
HB-106496,City Hotel,0,3,2025,February,8,23,2025-02-23,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,118.0,0,0
HB-063788,City Hotel,1,85,2025,February,8,20,2025-02-20,1,4,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,1
HB-034162,Resort Hotel,0,195,2025,March,10,5,2025-03-05,4,6,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,D,D,0,No Deposit,273.0,,0,Transient-Party,62.28,0,0
HB-042196,City Hotel,1,79,2023,September,35,2,2023-09-02,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.25,0,0
HB-066593,City Hotel,1,332,2025,April,17,22,2025-04-22,1,1,2,1.0,0,BB,BEL,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,180.9,0,0
HB-029924,Resort Hotel,0,22,2024,November,45,7,2024-11-07,1,1,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,61.0,1,1
HB-117213,City Hotel,0,2,2025,July,31,30,2025-07-30,1,0,3,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,179.1,0,1
HB-103534,City Hotel,0,0,2024,December,51,22,2024-12-22,2,3,2,0.0,0,SC,MYS,Direct,Direct,0,0,0,A,A,3,No Deposit,,,0,Transient,80.0,0,0
HB-001857,Resort Hotel,0,167,2023,September,37,17,2023-09-17,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Contract,45.9,0,1
HB-098068,City Hotel,0,296,2024,September,38,21,2024-09-21,0,4,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,26.0,,0,Transient-Party,117.0,0,1
HB-015596,Resort Hotel,0,50,2023,July,29,22,2023-07-22,1,4,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,166.6,1,0
HB-090450,City Hotel,0,220,2024,June,23,4,2024-06-04,2,1,2,0.0,0,BB,USA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,73.33,0,1
HB-077145,City Hotel,0,3,2023,October,41,12,2023-10-12,1,1,2,0.0,0,BB,PRT,Complementary,Direct,1,0,3,G,G,1,No Deposit,,45.0,0,Transient,0.0,0,0
HB-072074,City Hotel,1,179,2025,July,29,20,2025-07-20,0,2,2,0.0,0,BB,AUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,1
HB-031580,Resort Hotel,0,31,2024,December,1,30,2024-12-30,0,2,2,0.0,0,HB,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,305.0,0,1
HB-013243,Resort Hotel,1,209,2025,August,32,6,2025-08-06,2,2,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,188.0,0,0
HB-091959,City Hotel,0,144,2024,June,26,26,2024-06-26,2,0,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,85.5,0,1
HB-074372,City Hotel,1,276,2023,July,29,20,2023-07-20,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Contract,62.0,0,0
HB-023850,Resort Hotel,0,101,2024,April,18,29,2024-04-29,2,5,2,0.0,0,HB,NLD,Groups,TA/TO,0,0,0,A,A,12,No Deposit,95.0,,0,Transient-Party,75.0,0,0
HB-038927,Resort Hotel,0,185,2025,July,30,27,2025-07-27,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient,112.7,0,0
HB-046359,City Hotel,0,160,2023,December,52,30,2023-12-30,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,111,Transient-Party,70.67,0,0
HB-028755,Resort Hotel,0,7,2024,October,40,5,2024-10-05,2,4,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,1,No Deposit,,405.0,0,Transient-Party,50.0,0,0
HB-066026,City Hotel,1,315,2025,April,15,13,2025-04-13,0,3,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,144.8,0,0
HB-036601,Resort Hotel,0,192,2025,May,21,23,2025-05-23,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,92.0,1,2
HB-071097,City Hotel,1,52,2025,June,26,28,2025-06-28,0,2,1,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,1
HB-009488,Resort Hotel,1,183,2024,December,49,3,2024-12-03,2,1,2,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,38.0,,0,Transient,72.0,0,0
HB-017670,Resort Hotel,0,286,2023,October,41,14,2023-10-14,1,4,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,1,No Deposit,,223.0,0,Transient-Party,44.5,0,0
HB-000788,Resort Hotel,1,118,2023,July,30,29,2023-07-29,1,4,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,186.0,0,2
HB-078807,City Hotel,0,14,2023,October,41,15,2023-10-15,0,2,1,0.0,0,BB,SVN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,99.0,,0,Transient-Party,100.0,0,0
HB-052705,City Hotel,1,149,2024,June,23,9,2024-06-09,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,129.0,0,0
HB-014301,Resort Hotel,0,0,2024,June,26,28,2024-06-28,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,5,A,H,0,No Deposit,,290.0,0,Transient,79.0,0,0
HB-096154,City Hotel,0,138,2024,August,35,27,2024-08-27,2,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.3,0,1
HB-050902,City Hotel,1,286,2024,May,19,11,2024-05-11,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,176,Transient-Party,101.0,0,0
HB-002041,Resort Hotel,0,77,2023,September,39,28,2023-09-28,2,5,2,0.0,0,HB,POL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,78.1,0,2
HB-047974,City Hotel,0,64,2024,March,11,11,2024-03-11,1,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,51.97,0,1
HB-064372,City Hotel,1,56,2025,March,10,7,2025-03-07,0,5,1,0.0,0,BB,BRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,79.2,0,0
HB-068710,City Hotel,1,212,2025,May,21,20,2025-05-20,1,1,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,138.6,0,1
HB-112828,City Hotel,0,246,2025,May,22,27,2025-05-27,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,128.0,0,1
HB-103391,City Hotel,0,3,2024,December,51,19,2024-12-19,1,2,1,0.0,0,SC,MYS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.5,0,0
HB-011359,Resort Hotel,1,210,2025,May,18,4,2025-05-04,2,5,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient,50.4,0,1
HB-010561,Resort Hotel,1,194,2025,March,11,14,2025-03-14,4,14,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,440.0,,50,Transient-Party,62.0,0,0
HB-026862,Resort Hotel,0,209,2024,August,31,2,2024-08-02,2,9,1,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,242.0,,0,Transient,162.0,0,2
HB-100987,City Hotel,0,152,2024,November,44,1,2024-11-01,0,4,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,98.0,0,0
HB-036555,Resort Hotel,0,33,2025,August,34,18,2025-08-18,1,2,2,0.0,0,FB,PRT,Online TA,Direct,1,0,1,A,E,10,No Deposit,240.0,,0,Transient-Party,270.0,1,4
HB-041765,City Hotel,0,4,2023,August,34,23,2023-08-23,2,1,1,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,A,1,No Deposit,,45.0,0,Transient,0.0,0,1
HB-073398,City Hotel,1,114,2025,August,34,20,2025-08-20,2,3,2,1.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Transient,102.6,0,0
HB-091633,City Hotel,0,60,2024,June,25,21,2024-06-21,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.9,0,1
HB-025355,Resort Hotel,0,117,2024,June,24,13,2024-06-13,3,7,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,137.8,0,1
HB-068298,City Hotel,1,164,2025,May,20,15,2025-05-15,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-005709,Resort Hotel,1,468,2024,May,19,12,2024-05-12,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,249.0,,0,Transient-Party,67.0,0,0
HB-004590,Resort Hotel,0,136,2024,March,12,24,2024-03-24,0,3,2,0.0,0,Undefined,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,387.0,,0,Transient-Party,84.0,0,0
HB-113372,City Hotel,0,121,2025,June,23,3,2025-06-03,2,1,2,0.0,0,SC,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-091059,City Hotel,0,21,2024,June,24,12,2024-06-12,2,2,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,156.5,0,1
HB-099562,City Hotel,0,2,2024,October,41,13,2024-10-13,0,1,1,0.0,0,BB,CPV,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,344.0,,0,Transient-Party,109.65,0,0
HB-095310,City Hotel,0,26,2024,August,33,15,2024-08-15,1,2,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,168.0,,0,Transient,85.0,0,0
HB-085047,City Hotel,0,35,2024,March,9,3,2024-03-03,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,83.9,0,2
HB-041187,City Hotel,1,87,2023,August,33,14,2023-08-14,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,12.0,0,0
HB-053697,City Hotel,1,172,2024,June,26,27,2024-06-27,1,4,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.75,0,0
HB-074377,City Hotel,1,283,2023,July,30,27,2023-07-27,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-115802,City Hotel,0,263,2025,July,27,6,2025-07-06,2,3,2,1.0,0,HB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,166.05,0,2
HB-076908,City Hotel,1,342,2023,September,38,24,2023-09-24,2,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-113297,City Hotel,0,135,2025,June,22,1,2025-06-01,1,3,2,0.0,0,BB,CHE,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-095300,City Hotel,0,1,2024,August,33,17,2024-08-17,0,1,2,1.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,115.89,0,1
HB-113664,City Hotel,0,30,2025,June,23,8,2025-06-08,0,3,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,181.67,0,3
HB-113510,City Hotel,0,16,2025,June,23,5,2025-06-05,1,2,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,G,G,1,No Deposit,7.0,,0,Transient,213.33,0,1
HB-112140,City Hotel,0,7,2025,May,20,18,2025-05-18,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,1
HB-079059,City Hotel,0,13,2023,October,42,19,2023-10-19,1,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,126.0,0,2
HB-009402,Resort Hotel,1,64,2024,November,47,24,2024-11-24,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient,37.8,0,2
HB-073406,City Hotel,1,107,2025,August,34,20,2025-08-20,2,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,155.0,0,1
HB-038944,Resort Hotel,0,63,2025,July,30,24,2025-07-24,3,8,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,137.0,0,0
HB-006669,Resort Hotel,0,322,2024,June,25,22,2024-06-22,2,4,1,0.0,0,SC,POL,Groups,Direct,0,0,0,A,I,2,No Deposit,,,75,Transient-Party,0.0,0,0
HB-014717,Resort Hotel,1,259,2023,September,37,17,2023-09-17,0,3,2,0.0,0,BB,GBR,Groups,Corporate,0,1,0,A,A,0,Non Refund,,223.0,0,Transient,40.05,0,0
HB-018020,Resort Hotel,0,61,2023,October,43,29,2023-10-29,0,1,2,0.0,0,BB,CHE,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,251.0,,0,Transient,46.0,0,1
HB-113019,City Hotel,0,15,2025,May,22,31,2025-05-31,0,1,2,0.0,0,SC,LUX,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,1
HB-025641,Resort Hotel,0,9,2024,July,27,4,2024-07-04,1,0,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,171.0,0,0
HB-113131,City Hotel,0,409,2025,May,22,31,2025-05-31,0,3,2,0.0,0,BB,AUS,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,1
HB-047381,City Hotel,0,47,2024,February,7,18,2024-02-18,0,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,90.3,0,0
HB-079772,City Hotel,1,21,2023,November,46,13,2023-11-13,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,D,D,0,No Deposit,9.0,,0,Contract,82.45,0,1
HB-096446,City Hotel,0,74,2024,August,35,29,2024-08-29,1,4,2,0.0,0,SC,NOR,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,168.0,,0,Transient,72.25,0,0
HB-034120,Resort Hotel,0,29,2025,March,11,11,2025-03-11,1,1,2,0.0,0,BB,URY,Corporate,Direct,0,0,0,A,E,2,No Deposit,,263.0,0,Transient-Party,58.0,0,0
HB-118711,City Hotel,0,2,2025,August,34,24,2025-08-24,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,147.0,,0,Transient-Party,140.0,0,1
HB-023544,Resort Hotel,0,32,2024,April,17,25,2024-04-25,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,65.0,0,1
HB-000118,Resort Hotel,0,92,2023,July,27,4,2023-07-04,4,6,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,71.55,0,1
HB-051305,City Hotel,1,323,2024,May,20,17,2024-05-17,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,70.0,0,0
HB-069512,City Hotel,1,174,2025,June,22,1,2025-06-01,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,110.0,0,0
HB-107789,City Hotel,0,0,2025,March,12,17,2025-03-17,0,1,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,98.0,0,0
HB-094387,City Hotel,0,4,2025,May,19,9,2025-05-09,0,1,1,0.0,0,BB,PRT,Complementary,Direct,1,2,10,D,A,1,No Deposit,,45.0,0,Transient,0.0,0,2
HB-066820,City Hotel,1,156,2025,April,17,26,2025-04-26,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,100.0,0,0
HB-007907,Resort Hotel,0,332,2024,September,35,1,2024-09-01,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Transient,70.0,0,0
HB-115897,City Hotel,0,21,2025,July,28,12,2025-07-12,0,1,1,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,1
HB-078947,City Hotel,0,3,2023,October,42,19,2023-10-19,1,0,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,139.0,0,0
HB-094150,City Hotel,0,301,2024,July,31,30,2024-07-30,1,1,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-014709,Resort Hotel,1,259,2023,September,37,17,2023-09-17,0,3,2,0.0,0,BB,GBR,Groups,Corporate,0,1,0,A,A,0,Non Refund,,223.0,0,Transient,40.05,0,0
HB-057350,City Hotel,1,254,2024,September,39,24,2024-09-24,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,96.0,0,0
HB-046493,City Hotel,1,145,2024,January,1,3,2024-01-03,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,85,Transient,65.0,0,0
HB-063776,City Hotel,1,21,2025,February,8,20,2025-02-20,1,3,2,1.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,103.7,0,2
HB-076694,City Hotel,0,2,2024,July,28,10,2024-07-10,2,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,3,37,A,A,1,No Deposit,,40.0,0,Transient,65.0,0,0
HB-078010,City Hotel,0,16,2023,September,39,25,2023-09-25,2,4,1,0.0,0,BB,FIN,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient,170.0,0,0
HB-071760,City Hotel,1,214,2025,July,28,11,2025-07-11,2,6,2,0.0,0,HB,RUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,143.1,0,1
HB-079465,City Hotel,1,137,2024,January,4,27,2024-01-27,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,29.0,,45,Transient,70.0,0,0
HB-017515,Resort Hotel,0,8,2023,October,40,7,2023-10-07,2,4,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,2,No Deposit,281.0,,0,Contract,45.0,0,0
HB-034151,Resort Hotel,0,0,2025,March,10,6,2025-03-06,3,6,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,96.0,,0,Group,42.0,0,1
HB-043848,City Hotel,1,87,2023,September,39,25,2023-09-25,2,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-045847,City Hotel,0,98,2023,November,47,23,2023-11-23,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,37.0,,0,Transient-Party,75.0,0,1
HB-028735,Resort Hotel,0,8,2024,October,40,6,2024-10-06,1,3,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,1,No Deposit,,405.0,0,Transient-Party,58.0,1,0
HB-007840,Resort Hotel,0,222,2024,August,35,29,2024-08-29,2,5,2,0.0,0,HB,POL,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,315.0,,0,Transient,109.3,0,0
HB-007775,Resort Hotel,1,12,2024,August,35,26,2024-08-26,1,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,1,No Deposit,,,0,Transient,205.67,0,0
HB-020747,Resort Hotel,0,0,2024,February,6,8,2024-02-08,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,65.0,0,0
HB-091055,City Hotel,0,9,2024,June,24,15,2024-06-15,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,148.0,1,0
HB-056316,City Hotel,1,46,2024,September,36,3,2024-09-03,2,1,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,181.8,0,0
HB-096675,City Hotel,0,174,2024,September,36,2,2024-09-02,2,2,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.85,0,1
HB-060239,City Hotel,1,277,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-098867,City Hotel,0,18,2024,October,40,2,2024-10-02,2,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-106388,City Hotel,0,3,2025,February,8,22,2025-02-22,0,3,2,3.0,0,HB,NLD,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,9.0,,0,Transient,275.0,0,2
HB-087526,City Hotel,0,90,2024,April,16,17,2024-04-17,2,3,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,85.85,0,1
HB-089207,City Hotel,0,1,2024,May,20,18,2024-05-18,0,1,2,0.0,0,BB,ITA,Direct,Direct,0,0,0,A,F,0,No Deposit,,,0,Transient,120.0,0,0
HB-022603,Resort Hotel,0,0,2024,March,13,29,2024-03-29,0,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,0
HB-009704,Resort Hotel,1,288,2024,December,52,26,2024-12-26,3,6,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,96.4,0,0
HB-051735,City Hotel,1,158,2024,May,21,24,2024-05-24,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,31,Transient,130.0,0,0
HB-041831,City Hotel,1,50,2023,August,34,25,2023-08-25,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-040387,City Hotel,1,96,2023,July,29,23,2023-07-23,0,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,68.0,0,1
HB-018275,Resort Hotel,0,0,2024,January,3,19,2024-01-19,0,1,1,0.0,0,BB,GBR,Direct,Direct,1,0,2,A,D,0,No Deposit,,,0,Transient,39.0,0,0
HB-022249,Resort Hotel,0,11,2024,March,11,12,2024-03-12,4,6,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,115.0,,0,Transient,27.9,0,0
HB-081685,City Hotel,1,61,2023,December,52,30,2023-12-30,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Transient,100.67,0,1
HB-119192,City Hotel,0,213,2025,August,35,28,2025-08-28,1,3,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,19.0,,0,Transient-Party,104.0,0,0
HB-091551,City Hotel,0,36,2024,June,25,19,2024-06-19,2,2,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,87.89,0,1
HB-118306,City Hotel,0,134,2025,August,33,16,2025-08-16,0,2,1,0.0,0,SC,USA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,52.0,,0,Transient,71.1,0,0
HB-112345,City Hotel,0,14,2025,May,20,18,2025-05-18,2,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,178.0,0,2
HB-012727,Resort Hotel,1,169,2025,July,29,14,2025-07-14,2,5,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,151.43,0,1
HB-015593,Resort Hotel,0,42,2023,July,29,20,2023-07-20,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,175.0,,0,Transient,122.34,1,1
HB-066691,City Hotel,1,135,2025,April,17,23,2025-04-23,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,171.0,,0,Transient,90.0,0,0
HB-019822,Resort Hotel,0,0,2024,January,1,3,2024-01-03,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-004998,Resort Hotel,1,212,2024,April,15,11,2024-04-11,2,5,2,0.0,0,HB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,273.0,,0,Transient,67.05,0,0
HB-053856,City Hotel,1,179,2024,July,27,1,2024-07-01,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,65.0,0,0
HB-078927,City Hotel,0,16,2023,October,41,15,2023-10-15,1,3,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,90.0,0,0
HB-108794,City Hotel,0,3,2025,April,14,1,2025-04-01,0,1,2,0.0,0,BB,PRT,Complementary,Direct,0,0,0,F,G,0,No Deposit,,,0,Transient,0.0,0,1
HB-102822,City Hotel,0,26,2024,December,49,5,2024-12-05,1,1,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,87.78,0,1
HB-056198,City Hotel,1,419,2024,September,35,1,2024-09-01,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-005527,Resort Hotel,0,229,2024,May,18,1,2024-05-01,2,4,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,314.0,,0,Transient,70.4,0,1
HB-102497,City Hotel,0,13,2024,November,48,29,2024-11-29,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-082975,City Hotel,0,0,2023,December,50,16,2023-12-16,0,1,1,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,A,0,No Deposit,45.0,,0,Transient,0.0,0,0
HB-066491,City Hotel,1,177,2025,April,17,21,2025-04-21,0,2,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,0
HB-002206,Resort Hotel,0,10,2023,October,40,5,2023-10-05,1,3,2,0.0,1,BB,PRT,Direct,Direct,0,0,0,A,C,0,No Deposit,,,0,Transient,67.0,0,2
HB-098857,City Hotel,0,17,2024,October,40,3,2024-10-03,1,2,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-087325,City Hotel,0,3,2024,April,16,17,2024-04-17,1,0,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.0,0,0
HB-099434,City Hotel,0,26,2024,October,41,9,2024-10-09,2,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,B,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-091692,City Hotel,0,3,2024,June,25,23,2024-06-23,0,1,1,0.0,0,BB,SRB,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,34.0,,0,Transient-Party,95.0,0,0
HB-116769,City Hotel,0,48,2025,July,29,19,2025-07-19,1,4,2,2.0,0,BB,USA,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,7.0,,0,Transient,232.16,0,1
HB-031798,Resort Hotel,0,34,2025,January,1,2,2025-01-02,1,4,2,1.0,0,HB,ESP,Direct,Direct,0,0,0,C,C,1,No Deposit,250.0,,0,Transient,88.53,0,0
HB-118675,City Hotel,0,171,2025,August,34,23,2025-08-23,0,1,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,175.5,0,0
HB-049883,City Hotel,0,270,2024,April,16,20,2024-04-20,0,4,2,0.0,0,BB,ISL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,187,Transient-Party,80.0,0,0
HB-116733,City Hotel,0,423,2025,July,30,22,2025-07-22,1,1,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,122.4,0,1
HB-058413,City Hotel,1,279,2024,October,41,12,2024-10-12,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,98.0,,0,Transient,110.0,0,0
HB-000932,Resort Hotel,0,87,2023,August,31,6,2023-08-06,2,6,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,240.0,,0,Transient,154.0,0,2
HB-117563,City Hotel,0,8,2025,August,32,5,2025-08-05,0,1,2,0.0,0,SC,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,15.0,,0,Transient,128.0,0,0
HB-096803,City Hotel,0,10,2024,September,36,7,2024-09-07,0,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,F,0,No Deposit,7.0,,0,Transient,114.73,0,1
HB-053356,City Hotel,1,44,2024,June,25,18,2024-06-18,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,6.0,,0,Transient,96.3,0,0
HB-019353,Resort Hotel,0,1,2023,December,50,15,2023-12-15,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,5.0,,0,Transient,25.0,0,0
HB-003468,Resort Hotel,1,125,2023,December,50,17,2023-12-17,2,8,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,46.16,0,2
HB-036853,Resort Hotel,0,32,2025,May,22,27,2025-05-27,2,2,2,2.0,0,BB,USA,Direct,Direct,0,0,0,G,G,0,No Deposit,250.0,,0,Transient,165.0,0,1
HB-102988,City Hotel,0,74,2024,December,50,9,2024-12-09,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-034603,Resort Hotel,0,68,2025,March,13,26,2025-03-26,2,3,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,86.2,1,0
HB-042323,City Hotel,0,22,2023,September,36,4,2023-09-04,2,3,1,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,73.15,0,0
HB-096953,City Hotel,0,125,2024,September,36,7,2024-09-07,0,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,136.0,0,2
HB-072275,City Hotel,1,464,2025,July,30,25,2025-07-25,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-052491,City Hotel,1,213,2024,June,23,7,2024-06-07,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,62,Transient,130.0,0,0
HB-109214,City Hotel,0,36,2025,April,14,5,2025-04-05,0,3,3,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,190.0,0,2
HB-101090,City Hotel,0,190,2024,November,44,3,2024-11-03,0,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.9,0,0
HB-073737,City Hotel,1,265,2023,July,27,9,2023-07-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-024052,Resort Hotel,0,0,2024,May,19,9,2024-05-09,1,1,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,94.0,0,1
HB-064693,City Hotel,1,92,2025,March,11,15,2025-03-15,0,3,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,85.0,0,0
HB-046691,City Hotel,0,18,2024,January,3,15,2024-01-15,2,3,2,2.0,0,BB,IRQ,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,9.0,,0,Transient-Party,169.0,0,0
HB-010401,Resort Hotel,1,316,2025,March,10,4,2025-03-04,6,15,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,55.8,0,0
HB-091381,City Hotel,0,76,2024,June,25,17,2024-06-17,2,2,2,1.0,0,BB,EGY,Online TA,TA/TO,0,0,0,A,D,6,No Deposit,9.0,,0,Transient,126.9,0,2
HB-011279,Resort Hotel,1,221,2025,April,18,30,2025-04-30,2,5,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,83.43,0,0
HB-004974,Resort Hotel,1,212,2024,April,15,11,2024-04-11,2,5,2,0.0,0,HB,PRT,Groups,Direct,0,0,0,D,D,0,Non Refund,273.0,,0,Transient,76.05,0,0
HB-117140,City Hotel,0,89,2025,July,30,27,2025-07-27,0,3,1,0.0,0,SC,FIN,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,120.0,0,1
HB-052634,City Hotel,1,27,2024,June,23,9,2024-06-09,0,1,2,0.0,0,BB,PRT,Offline TA/TO,Corporate,0,0,0,A,A,0,No Deposit,191.0,,0,Transient-Party,120.0,0,0
HB-062723,City Hotel,1,130,2025,January,4,20,2025-01-20,0,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,104.0,0,0
HB-104405,City Hotel,0,4,2025,January,2,9,2025-01-09,1,3,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,79.0,,0,Transient,54.15,0,0
HB-017862,Resort Hotel,0,5,2023,October,42,19,2023-10-19,1,4,1,0.0,0,HB,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,0.0,0,0
HB-006787,Resort Hotel,1,189,2024,July,27,2,2024-07-02,2,4,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,135.0,0,0
HB-003683,Resort Hotel,0,65,2023,December,52,30,2023-12-30,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,102.6,0,2
HB-104206,City Hotel,0,14,2025,January,2,6,2025-01-06,0,2,2,1.0,0,BB,RUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,2
HB-076879,City Hotel,1,239,2023,October,42,17,2023-10-17,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-072426,City Hotel,1,17,2025,July,31,28,2025-07-28,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,1
HB-040780,City Hotel,0,0,2023,August,32,7,2023-08-07,0,2,2,2.0,0,SC,POL,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Contract,153.0,0,1
HB-100608,City Hotel,0,142,2024,October,43,27,2024-10-27,0,3,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,100.8,0,1
HB-062177,City Hotel,1,226,2025,January,1,3,2025-01-03,0,4,2,0.0,0,SC,DOM,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,67.15,0,0
HB-041905,City Hotel,0,55,2023,August,34,26,2023-08-26,0,2,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-102533,City Hotel,0,30,2024,November,48,26,2024-11-26,2,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,3
HB-062566,City Hotel,1,137,2025,January,3,14,2025-01-14,4,6,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,2
HB-031881,Resort Hotel,0,0,2025,January,2,9,2025-01-09,1,0,2,0.0,0,BB,USA,Online TA,TA/TO,1,0,0,A,A,0,No Deposit,306.0,,0,Transient,30.99,0,0
HB-093407,City Hotel,0,0,2024,July,29,18,2024-07-18,1,2,2,0.0,0,BB,NZL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,129.0,0,0
HB-092673,City Hotel,0,158,2024,July,27,7,2024-07-07,0,3,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,146.7,0,2
HB-056405,City Hotel,1,36,2024,September,36,5,2024-09-05,1,0,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-055164,City Hotel,1,129,2024,August,32,6,2024-08-06,2,3,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,103.5,0,1
HB-084302,City Hotel,0,32,2024,February,8,19,2024-02-19,2,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,86.15,0,1
HB-041466,City Hotel,0,0,2023,August,33,17,2023-08-17,1,0,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Contract,129.0,0,0
HB-023644,Resort Hotel,0,111,2024,April,17,28,2024-04-28,0,2,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient,44.1,0,1
HB-100375,City Hotel,0,221,2024,October,43,22,2024-10-22,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.95,0,2
HB-082346,City Hotel,1,94,2024,March,10,4,2024-03-04,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,154.0,,28,Transient,80.0,0,0
HB-035796,Resort Hotel,0,100,2025,April,18,29,2025-04-29,2,1,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,385.0,,0,Transient-Party,83.0,0,1
HB-051738,City Hotel,1,158,2024,May,21,24,2024-05-24,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,31,Transient,130.0,0,0
HB-025798,Resort Hotel,0,166,2024,July,27,2,2024-07-02,4,6,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,C,2,No Deposit,143.0,,0,Contract,81.9,0,0
HB-105038,City Hotel,0,10,2025,January,3,18,2025-01-18,2,8,2,1.0,0,BB,BRA,Online TA,TA/TO,0,0,0,E,E,2,No Deposit,9.0,,0,Transient,113.39,0,2
HB-104311,City Hotel,0,0,2025,January,2,9,2025-01-09,1,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,2,No Deposit,,408.0,0,Transient,78.0,0,0
HB-081328,City Hotel,0,5,2023,December,49,5,2023-12-05,2,1,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,62.8,0,0
HB-025948,Resort Hotel,0,2,2024,July,29,15,2024-07-15,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,176.0,0,1
HB-036068,Resort Hotel,0,95,2025,April,18,29,2025-04-29,4,6,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,143.0,,0,Transient,42.75,0,2
HB-029593,Resort Hotel,0,46,2024,October,44,29,2024-10-29,2,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,58.0,0,1
HB-076308,City Hotel,0,264,2023,July,27,8,2023-07-08,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-115003,City Hotel,0,119,2025,June,26,25,2025-06-25,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-083982,City Hotel,0,0,2024,February,7,16,2024-02-16,0,1,2,0.0,0,BB,DEU,Online TA,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,79.0,0,0
HB-083167,City Hotel,0,9,2024,January,3,17,2024-01-17,2,4,2,0.0,0,BB,HRV,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,83.0,0,1
HB-045224,City Hotel,1,50,2023,October,43,24,2023-10-24,1,1,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,75.0,0,0
HB-090015,City Hotel,0,0,2024,May,22,30,2024-05-30,1,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,140.0,0,0
HB-058843,City Hotel,1,99,2024,October,42,16,2024-10-16,2,1,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.8,0,1
HB-080375,City Hotel,1,104,2024,February,9,29,2024-02-29,1,5,2,0.0,0,BB,PRT,Online TA,TA/TO,1,1,0,A,A,0,No Deposit,11.0,,0,Transient,61.43,0,0
HB-090782,City Hotel,0,74,2024,June,24,10,2024-06-10,0,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,116.1,0,1
HB-018667,Resort Hotel,0,0,2023,November,47,25,2023-11-25,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,46.4,0,0
HB-084031,City Hotel,0,3,2024,February,7,14,2024-02-14,2,2,2,0.0,0,HB,ESP,Direct,Direct,0,0,0,D,D,2,No Deposit,14.0,,0,Transient,147.0,1,0
HB-074729,City Hotel,0,71,2024,October,42,15,2024-10-15,0,1,3,0.0,0,BB,PRT,Complementary,Direct,1,0,32,G,E,0,No Deposit,,45.0,0,Transient,0.0,0,4
HB-095867,City Hotel,0,37,2024,August,34,20,2024-08-20,2,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.1,0,3
HB-071164,City Hotel,1,215,2025,June,26,28,2025-06-28,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-059568,City Hotel,1,183,2024,October,44,29,2024-10-29,2,1,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.1,0,2
HB-113364,City Hotel,0,434,2025,June,23,3,2025-06-03,2,1,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,1
HB-097554,City Hotel,0,291,2024,September,38,21,2024-09-21,0,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,1,A,E,0,No Deposit,3.0,,44,Transient-Party,117.0,0,0
HB-043172,City Hotel,0,76,2023,September,37,16,2023-09-16,0,2,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,B,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-028175,Resort Hotel,0,141,2024,September,38,20,2024-09-20,0,3,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,100.33,1,1
HB-058060,City Hotel,1,275,2024,October,40,5,2024-10-05,1,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,44.0,,0,Transient,90.0,0,0
HB-076575,City Hotel,1,207,2023,September,39,29,2023-09-29,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,20.0,,0,Transient,48.0,0,0
HB-078257,City Hotel,1,16,2023,October,40,7,2023-10-07,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,85.5,0,1
HB-100193,City Hotel,0,80,2024,October,43,21,2024-10-21,2,2,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,151.2,0,0
HB-000407,Resort Hotel,0,113,2023,July,28,14,2023-07-14,4,11,3,0.0,0,BB,PRT,Direct,Direct,0,0,0,H,H,1,No Deposit,,,0,Transient,187.5,1,3
HB-012062,Resort Hotel,1,83,2025,June,24,11,2025-06-11,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,410.0,,0,Transient,56.7,0,0
HB-012096,Resort Hotel,1,162,2025,June,24,13,2025-06-13,0,2,3,1.0,0,BB,FIN,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,185.0,0,1
HB-022813,Resort Hotel,0,75,2024,April,14,2,2024-04-02,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,39.91,0,1
HB-025773,Resort Hotel,0,0,2024,July,27,7,2024-07-07,0,3,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,132.16,0,0
HB-011963,Resort Hotel,1,128,2025,June,23,5,2025-06-05,1,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,140.0,0,0
HB-102845,City Hotel,0,24,2024,December,49,4,2024-12-04,2,1,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,2
HB-070625,City Hotel,1,210,2025,June,25,19,2025-06-19,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,154.0,,0,Transient,130.0,0,0
HB-018429,Resort Hotel,0,6,2023,November,46,16,2023-11-16,1,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,337.0,0,Transient-Party,38.0,0,0
HB-062779,City Hotel,1,20,2025,January,4,21,2025-01-21,6,15,2,2.0,0,BB,AGO,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,146.51,0,0
HB-031963,Resort Hotel,0,6,2025,January,2,10,2025-01-10,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,181.0,,0,Transient-Party,34.0,0,1
HB-092193,City Hotel,0,145,2024,July,27,1,2024-07-01,0,1,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,72.76,0,0
HB-087730,City Hotel,0,35,2024,April,17,22,2024-04-22,1,2,1,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.5,0,1
HB-092098,City Hotel,0,3,2024,June,26,29,2024-06-29,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,63.5,0,0
HB-050512,City Hotel,1,437,2024,May,18,2,2024-05-02,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-105476,City Hotel,0,34,2025,February,6,7,2025-02-07,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,400.0,0,Transient,88.0,0,0
HB-071738,City Hotel,1,13,2025,July,28,11,2025-07-11,0,2,2,1.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,0
HB-004526,Resort Hotel,1,65,2024,March,12,23,2024-03-23,0,4,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,114.0,0,0
HB-108056,City Hotel,0,0,2025,March,12,20,2025-03-20,1,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,F,1,No Deposit,,,0,Transient,152.0,0,0
HB-022836,Resort Hotel,0,48,2024,April,14,4,2024-04-04,1,3,2,0.0,0,FB,GBR,Offline TA/TO,TA/TO,0,0,0,A,C,1,No Deposit,26.0,,0,Transient,79.05,0,0
HB-112948,City Hotel,0,6,2025,May,22,29,2025-05-29,1,1,1,0.0,0,BB,GRC,Aviation,Corporate,0,0,0,A,A,0,No Deposit,,153.0,0,Transient,95.0,0,0
HB-044414,City Hotel,1,97,2023,October,40,5,2023-10-05,1,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,140.0,0,0
HB-115213,City Hotel,0,100,2025,June,27,30,2025-06-30,1,2,1,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,108.0,0,1
HB-071999,City Hotel,1,128,2025,July,29,17,2025-07-17,1,3,1,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,0
HB-056202,City Hotel,1,419,2024,September,35,1,2024-09-01,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-083506,City Hotel,0,0,2024,February,5,3,2024-02-03,0,2,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,B,B,1,No Deposit,,,0,Transient-Party,22.5,0,0
HB-101426,City Hotel,0,92,2024,November,46,11,2024-11-11,0,1,2,0.0,0,BB,THA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,364.0,,0,Transient-Party,90.0,0,0
HB-011357,Resort Hotel,1,108,2025,May,18,4,2025-05-04,0,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,85.0,0,0
HB-053428,City Hotel,1,193,2024,June,25,20,2024-06-20,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,162.0,,39,Transient,120.0,0,0
HB-061065,City Hotel,1,290,2024,December,48,1,2024-12-01,1,3,2,0.0,0,BB,SVK,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,73.95,0,0
HB-024348,Resort Hotel,0,124,2024,May,20,18,2024-05-18,0,4,2,0.0,1,BB,IRL,Online TA,TA/TO,0,0,0,A,C,2,No Deposit,240.0,,0,Transient,60.0,0,2
HB-075179,City Hotel,1,292,2023,August,31,5,2023-08-05,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-096512,City Hotel,0,8,2024,September,36,2,2024-09-02,0,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.0,0,1
HB-089814,City Hotel,0,15,2024,May,21,25,2024-05-25,0,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,9.0,,0,Transient,111.0,0,0
HB-079039,City Hotel,0,3,2023,October,42,19,2023-10-19,1,1,2,0.0,0,BB,KOR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,81.0,0,Transient,142.0,0,0
HB-008353,Resort Hotel,1,31,2024,September,39,23,2024-09-23,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,145.67,0,2
HB-006703,Resort Hotel,0,229,2024,June,26,25,2024-06-25,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,100.29,0,2
HB-030438,Resort Hotel,0,0,2024,November,47,21,2024-11-21,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,55.0,0,0
HB-057611,City Hotel,1,27,2024,September,39,29,2024-09-29,0,2,2,2.0,0,BB,NOR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,234.0,0,1
HB-048348,City Hotel,1,49,2024,March,12,21,2024-03-21,1,3,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.8,0,1
HB-104542,City Hotel,0,2,2025,January,3,13,2025-01-13,1,2,1,2.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,1,No Deposit,14.0,,0,Transient,115.33,0,1
HB-110548,City Hotel,0,60,2025,April,17,24,2025-04-24,1,4,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,130.5,0,0
HB-071766,City Hotel,1,81,2025,July,28,12,2025-07-12,0,2,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,150.0,0,2
HB-056393,City Hotel,1,40,2024,September,36,4,2024-09-04,2,5,0,2.0,0,BB,DEU,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient,106.9,0,0
HB-022990,Resort Hotel,0,18,2024,April,15,10,2024-04-10,2,0,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,85.0,0,1
HB-006233,Resort Hotel,1,139,2024,May,22,29,2024-05-29,2,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,242.0,,0,Transient,105.81,0,0
HB-003491,Resort Hotel,1,93,2023,December,51,19,2023-12-19,0,1,2,0.0,0,FB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,80.0,0,0
HB-014823,Resort Hotel,1,213,2023,September,37,17,2023-09-17,0,2,2,0.0,0,HB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,240.0,,0,Transient,93.6,0,1
HB-053938,City Hotel,1,136,2024,July,27,2,2024-07-02,2,2,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.08,0,0
HB-041129,City Hotel,1,1,2023,August,32,12,2023-08-12,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,42.0,,0,Transient,110.0,0,0
HB-024398,Resort Hotel,0,1,2024,May,20,18,2024-05-18,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,323.0,0,Transient,42.0,0,0
HB-076228,City Hotel,1,165,2023,August,32,8,2023-08-08,2,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,86.0,0,0
HB-047750,City Hotel,1,48,2024,March,9,2,2024-03-02,0,3,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,73.1,0,1
HB-111339,City Hotel,0,144,2025,May,19,6,2025-05-06,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,52.0,,0,Transient,90.0,0,1
HB-110644,City Hotel,0,171,2025,April,17,27,2025-04-27,0,3,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,89.0,0,0
HB-041422,City Hotel,1,11,2023,August,33,15,2023-08-15,2,1,3,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,17.0,,0,Transient-Party,138.5,0,1
HB-073988,City Hotel,1,286,2023,July,30,30,2023-07-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-070572,City Hotel,1,321,2025,June,25,18,2025-06-18,2,3,2,0.0,0,HB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,144.0,0,0
HB-064078,City Hotel,1,47,2025,March,9,1,2025-03-01,0,3,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,97.2,0,0
HB-023741,Resort Hotel,0,5,2024,April,18,30,2024-04-30,1,1,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,117.0,0,1
HB-064498,City Hotel,1,127,2025,March,11,11,2025-03-11,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,0,Transient,80.0,0,0
HB-042838,City Hotel,0,168,2023,September,37,11,2023-09-11,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,B,1,No Deposit,1.0,,0,Transient-Party,50.0,0,0
HB-013940,Resort Hotel,0,11,2024,November,46,15,2024-11-15,0,1,1,0.0,0,BB,,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,34.4,0,0
HB-016673,Resort Hotel,0,288,2023,September,35,2,2023-09-02,1,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient-Party,110.7,0,0
HB-044634,City Hotel,0,80,2023,October,41,9,2023-10-09,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,12.0,,50,Transient-Party,136.0,0,0
HB-072917,City Hotel,1,191,2025,August,32,9,2025-08-09,0,4,2,0.0,0,SC,RUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,112.5,0,1
HB-024243,Resort Hotel,0,9,2024,May,20,15,2024-05-15,1,0,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,Refundable,,,0,Transient-Party,70.0,0,0
HB-065772,City Hotel,1,73,2025,April,15,8,2025-04-08,2,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,126.0,0,2
HB-019679,Resort Hotel,0,23,2023,December,52,30,2023-12-30,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,58.0,0,1
HB-012756,Resort Hotel,1,126,2025,July,29,15,2025-07-15,2,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,192.0,0,1
HB-052397,City Hotel,1,163,2024,June,23,5,2024-06-05,2,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,171.0,,0,Transient,100.0,0,0
HB-106367,City Hotel,0,2,2025,February,8,23,2025-02-23,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,73.0,0,Transient-Party,65.0,0,0
HB-027363,Resort Hotel,0,171,2024,August,34,21,2024-08-21,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Contract,104.55,0,0
HB-015911,Resort Hotel,0,85,2023,August,31,2,2023-08-02,2,3,3,0.0,0,BB,LUX,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,8.0,,0,Transient,161.45,1,1
HB-066901,City Hotel,1,156,2025,April,17,26,2025-04-26,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,100.0,0,0
HB-073001,City Hotel,1,0,2025,August,33,12,2025-08-12,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,219.0,0,0
HB-104577,City Hotel,0,9,2025,January,3,14,2025-01-14,2,2,2,0.0,0,BB,MAR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,88.0,0,0
HB-087791,City Hotel,0,44,2024,April,17,23,2024-04-23,2,1,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,24.0,,0,Transient-Party,85.0,0,0
HB-009087,Resort Hotel,1,31,2024,October,43,27,2024-10-27,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,75.0,0,2
HB-067394,City Hotel,1,82,2025,May,18,3,2025-05-03,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,130.0,0,0
HB-101607,City Hotel,0,19,2024,November,46,14,2024-11-14,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,40.0,,0,Transient,65.0,0,0
HB-091102,City Hotel,0,256,2024,June,24,15,2024-06-15,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-072804,City Hotel,1,112,2025,August,32,7,2025-08-07,1,1,3,0.0,0,BB,GBR,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,175.0,0,0
HB-041796,City Hotel,0,53,2023,August,34,24,2023-08-24,1,1,3,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,D,1,No Deposit,1.0,,0,Transient-Party,84.0,0,1
HB-054642,City Hotel,1,101,2024,July,29,21,2024-07-21,0,3,1,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,142.3,0,0
HB-008600,Resort Hotel,1,383,2024,October,40,6,2024-10-06,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,315.0,,0,Transient-Party,48.0,0,0
HB-017233,Resort Hotel,0,260,2023,September,38,18,2023-09-18,4,10,1,0.0,0,HB,LVA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,171.0,,0,Transient,45.9,0,1
HB-089274,City Hotel,0,64,2024,May,20,16,2024-05-16,1,3,1,0.0,0,BB,DEU,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,109.65,0,0
HB-078697,City Hotel,0,3,2024,January,3,18,2024-01-18,1,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,8,A,A,0,No Deposit,,40.0,0,Transient-Party,66.0,0,0
HB-011610,Resort Hotel,1,60,2025,May,21,21,2025-05-21,2,0,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,1,No Deposit,,169.0,0,Transient-Party,60.0,0,1
HB-049600,City Hotel,0,107,2024,April,16,15,2024-04-15,2,2,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,95.2,0,1
HB-080618,City Hotel,0,42,2023,November,46,16,2023-11-16,1,4,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Contract,104.42,0,1
HB-098417,City Hotel,0,3,2025,January,2,12,2025-01-12,0,2,1,0.0,0,BB,PRT,Direct,Direct,1,0,1,A,E,1,No Deposit,,,0,Transient,75.0,1,1
HB-051256,City Hotel,1,286,2024,May,20,17,2024-05-17,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,75,Transient,65.0,0,0
HB-079662,City Hotel,0,44,2023,October,44,31,2023-10-31,0,1,2,1.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,113.8,0,3
HB-005866,Resort Hotel,1,30,2024,May,20,15,2024-05-15,2,1,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,241.0,,0,Transient,113.19,0,1
HB-006199,Resort Hotel,0,225,2024,May,22,28,2024-05-28,1,1,1,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,D,1,No Deposit,298.0,,0,Transient-Party,54.5,0,0
HB-075855,City Hotel,1,337,2023,September,38,19,2023-09-19,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-076545,City Hotel,1,199,2023,September,38,21,2023-09-21,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,20.0,,0,Transient,48.0,0,0
HB-081136,City Hotel,1,46,2023,December,51,22,2023-12-22,4,12,3,0.0,0,BB,PRT,Direct,Direct,0,1,0,D,D,1,No Deposit,,,0,Transient,102.25,0,0
HB-072361,City Hotel,1,150,2025,July,30,27,2025-07-27,0,1,2,1.0,0,HB,GBR,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,190.8,0,0
HB-031528,Resort Hotel,0,2,2024,December,52,29,2024-12-29,0,2,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient-Party,75.0,0,0
HB-007222,Resort Hotel,0,159,2024,July,30,28,2024-07-28,3,8,2,0.0,0,BB,POL,Offline TA/TO,TA/TO,0,0,0,E,E,1,No Deposit,315.0,,0,Transient,113.05,0,0
HB-060768,City Hotel,1,83,2024,November,47,20,2024-11-20,2,1,2,0.0,0,BB,HUN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.6,0,0
HB-023626,Resort Hotel,0,12,2024,April,17,27,2024-04-27,0,3,2,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,A,A,1,No Deposit,385.0,,0,Transient-Party,85.33,0,0
HB-000542,Resort Hotel,0,0,2023,July,29,19,2023-07-19,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,,240.0,0,Group,88.2,0,0
HB-047711,City Hotel,1,13,2024,February,9,29,2024-02-29,1,3,2,1.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,83.0,,0,Transient,86.8,0,0
HB-010082,Resort Hotel,1,14,2025,February,7,10,2025-02-10,1,2,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-015626,Resort Hotel,1,243,2023,September,36,4,2023-09-04,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,240.0,,0,Transient-Party,110.7,0,1
HB-044798,City Hotel,1,105,2023,October,41,12,2023-10-12,1,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,110.0,0,0
HB-064134,City Hotel,1,28,2025,March,9,2,2025-03-02,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,95.0,0,0
HB-009302,Resort Hotel,1,37,2024,November,45,10,2024-11-10,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,37.8,0,0
HB-049965,City Hotel,1,288,2024,April,16,21,2024-04-21,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-077584,City Hotel,0,10,2023,December,49,10,2023-12-10,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,6,A,A,0,No Deposit,,40.0,0,Transient,74.0,0,0
HB-015088,Resort Hotel,0,0,2023,November,48,30,2023-11-30,1,1,1,0.0,0,BB,PRT,Direct,Direct,1,0,2,A,A,0,No Deposit,,,0,Transient,38.0,0,0
HB-097688,City Hotel,0,67,2024,September,38,16,2024-09-16,2,2,2,0.0,0,BB,USA,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,137.7,0,1
HB-114325,City Hotel,0,448,2025,June,25,17,2025-06-17,2,1,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,3
HB-090345,City Hotel,0,93,2024,June,23,3,2024-06-03,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,80.75,0,1
HB-053257,City Hotel,1,245,2024,June,25,17,2024-06-17,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,0,Transient,75.0,0,0
HB-027021,Resort Hotel,0,199,2024,August,31,2,2024-08-02,4,12,2,1.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,196.0,,0,Transient,103.5,0,1
HB-032880,Resort Hotel,0,21,2025,February,6,4,2025-02-04,2,2,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-002771,Resort Hotel,1,155,2023,October,44,31,2023-10-31,0,1,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,36.0,0,0
HB-050640,City Hotel,1,302,2024,May,18,5,2024-05-05,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-063472,City Hotel,1,67,2025,February,7,12,2025-02-12,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,80.0,0,0
HB-086608,City Hotel,0,6,2024,April,14,3,2024-04-03,2,2,2,0.0,0,SC,BEL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,85.0,0,0
HB-003019,Resort Hotel,1,40,2023,November,45,11,2023-11-11,0,4,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,281.0,,0,Transient-Party,40.0,0,0
HB-005497,Resort Hotel,1,8,2024,April,18,30,2024-04-30,1,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,91.0,0,1
HB-005268,Resort Hotel,1,106,2024,April,17,23,2024-04-23,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,52.2,0,0
HB-059117,City Hotel,1,1,2024,October,43,21,2024-10-21,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,130.0,0,0
HB-079168,City Hotel,0,28,2023,October,42,19,2023-10-19,1,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-019553,Resort Hotel,0,30,2023,December,51,23,2023-12-23,0,4,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,98.5,1,2
HB-057323,City Hotel,0,429,2024,September,39,23,2024-09-23,0,2,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,330,Transient-Party,65.0,0,0
HB-019449,Resort Hotel,0,2,2023,December,51,18,2023-12-18,0,2,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,63.0,0,1
HB-085387,City Hotel,0,46,2024,March,11,12,2024-03-12,1,1,2,0.0,0,SC,NZL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,71.1,0,1
HB-057427,City Hotel,1,24,2024,September,39,26,2024-09-26,1,1,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,0
HB-003779,Resort Hotel,1,5,2024,January,1,4,2024-01-04,1,3,2,0.0,0,HB,PRT,Groups,Corporate,0,0,0,A,A,0,No Deposit,,174.0,0,Transient-Party,68.0,0,0
HB-118460,City Hotel,0,85,2025,August,34,18,2025-08-18,0,2,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,80.1,0,0
HB-061145,City Hotel,1,75,2024,December,49,2,2024-12-02,2,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,1
HB-117421,City Hotel,0,22,2025,July,31,31,2025-07-31,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,109.44,0,1
HB-037861,Resort Hotel,0,4,2025,June,27,30,2025-06-30,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,150.0,1,1
HB-005019,Resort Hotel,1,168,2024,April,15,12,2024-04-12,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,245.0,,0,Transient,86.0,0,0
HB-033968,Resort Hotel,0,11,2025,March,10,6,2025-03-06,1,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,50.0,0,1
HB-043339,City Hotel,1,74,2023,September,38,18,2023-09-18,0,2,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient-Party,80.0,0,0
HB-092996,City Hotel,0,3,2024,July,28,10,2024-07-10,2,3,2,2.0,0,BB,RUS,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,229.0,0,2
HB-053728,City Hotel,1,119,2024,June,26,28,2024-06-28,0,1,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,112.5,0,0
HB-021580,Resort Hotel,0,36,2024,March,9,3,2024-03-03,0,1,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,26.0,0,1
HB-109358,City Hotel,0,88,2025,April,14,5,2025-04-05,1,4,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.5,0,1
HB-069155,City Hotel,1,235,2025,May,22,26,2025-05-26,1,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,142.1,0,1
HB-034682,Resort Hotel,0,113,2025,March,13,29,2025-03-29,0,4,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-082677,City Hotel,0,23,2024,January,1,2,2024-01-02,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,26.0,,0,Transient-Party,109.0,0,1
HB-059052,City Hotel,1,30,2024,October,42,20,2024-10-20,0,3,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,159.0,0,1
HB-020773,Resort Hotel,0,5,2024,February,6,6,2024-02-06,2,1,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,D,2,No Deposit,,,0,Transient,61.0,0,0
HB-076754,City Hotel,0,0,2023,August,31,6,2023-08-06,0,2,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,81.0,0,0
HB-064659,City Hotel,1,20,2025,March,11,14,2025-03-14,0,5,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,132.0,,0,Transient,65.0,0,0
HB-005080,Resort Hotel,1,183,2024,April,16,16,2024-04-16,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,298.0,,0,Transient-Party,85.0,0,0
HB-097238,City Hotel,0,18,2024,September,37,11,2024-09-11,2,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,119.58,0,0
HB-109499,City Hotel,0,67,2025,April,15,9,2025-04-09,2,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,168.0,,0,Transient,89.1,0,0
HB-020268,Resort Hotel,0,3,2024,February,8,25,2024-02-25,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,1,0,1,A,D,0,No Deposit,240.0,,0,Transient,43.0,0,2
HB-011733,Resort Hotel,1,313,2025,May,22,27,2025-05-27,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,59.79,0,1
HB-095964,City Hotel,0,0,2024,August,35,26,2024-08-26,0,0,2,0.0,0,SC,PRT,Online TA,TA/TO,1,0,0,A,K,0,No Deposit,9.0,,0,Contract,0.0,0,1
HB-017389,Resort Hotel,0,0,2023,October,40,5,2023-10-05,1,3,2,0.0,0,FB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,174.0,0,Transient-Party,109.0,0,0
HB-062240,City Hotel,1,31,2025,January,1,5,2025-01-05,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.4,0,1
HB-012832,Resort Hotel,1,128,2025,July,29,18,2025-07-18,2,5,2,0.0,0,BB,LUX,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,188.57,0,1
HB-024417,Resort Hotel,0,35,2024,May,20,14,2024-05-14,2,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,147.0,,0,Transient-Party,53.87,0,0
HB-000112,Resort Hotel,0,78,2023,July,27,4,2023-07-04,2,5,2,0.0,1,HB,PRT,Online TA,TA/TO,0,0,0,E,F,0,No Deposit,240.0,,0,Transient,139.0,0,2
HB-080380,City Hotel,1,34,2023,December,49,8,2023-12-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,0,Transient,90.0,0,0
HB-056050,City Hotel,1,64,2024,August,35,27,2024-08-27,2,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,143.4,0,1
HB-038861,Resort Hotel,0,62,2025,July,29,18,2025-07-18,4,10,2,0.0,0,HB,IRL,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,531.0,,0,Transient,192.1,0,2
HB-079032,City Hotel,0,4,2023,October,42,18,2023-10-18,2,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-040811,City Hotel,1,125,2023,August,32,7,2023-08-07,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,1
HB-040877,City Hotel,0,16,2023,August,32,8,2023-08-08,2,2,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-075542,City Hotel,1,278,2023,July,29,22,2023-07-22,0,2,3,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,1,Non Refund,1.0,,0,Transient-Party,84.0,0,0
HB-056249,City Hotel,1,69,2024,September,35,1,2024-09-01,2,6,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,123.98,0,0
HB-018227,Resort Hotel,0,25,2025,April,14,2,2025-04-02,2,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,E,E,1,No Deposit,,281.0,0,Transient-Party,50.0,0,0
HB-074673,City Hotel,1,359,2023,October,41,11,2023-10-11,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-092793,City Hotel,0,125,2024,July,28,9,2024-07-09,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.3,0,1
HB-047686,City Hotel,1,1,2024,February,9,28,2024-02-28,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,60.0,0,0
HB-088480,City Hotel,0,117,2024,May,19,6,2024-05-06,0,2,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient-Party,114.3,0,1
HB-036379,Resort Hotel,0,121,2025,May,20,16,2025-05-16,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,85.0,0,1
HB-091728,City Hotel,0,265,2024,June,26,24,2024-06-24,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-003836,Resort Hotel,1,3,2024,January,3,21,2024-01-21,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,E,0,No Deposit,,47.0,0,Transient,30.0,0,0
HB-024859,Resort Hotel,0,2,2024,June,23,5,2024-06-05,1,0,3,1.0,0,BB,CN,Online TA,TA/TO,0,0,0,H,I,0,No Deposit,,,0,Transient,174.0,0,1
HB-032504,Resort Hotel,0,1,2025,January,5,28,2025-01-28,0,1,2,0.0,0,HB,ESP,Direct,Direct,0,0,0,F,F,1,No Deposit,,,0,Transient-Party,110.0,0,1
HB-104746,City Hotel,0,27,2025,January,3,19,2025-01-19,0,3,1,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,29.0,,25,Transient-Party,85.0,0,0
HB-112424,City Hotel,0,11,2025,May,21,21,2025-05-21,2,1,2,0.0,0,BB,USA,Direct,Direct,0,0,0,A,B,0,No Deposit,14.0,,0,Transient,120.0,0,0
HB-031611,Resort Hotel,0,196,2024,December,1,30,2024-12-30,1,2,1,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,,308.0,0,Transient-Party,0.0,0,0
HB-046261,City Hotel,0,17,2023,December,52,28,2023-12-28,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,136.0,1,1
HB-096031,City Hotel,0,256,2024,August,35,26,2024-08-26,0,2,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,72.25,0,1
HB-048368,City Hotel,1,251,2024,March,12,22,2024-03-22,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,93,Transient,90.0,0,0
HB-073114,City Hotel,1,507,2025,August,33,15,2025-08-15,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-081928,City Hotel,1,278,2024,August,32,11,2024-08-11,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,65.0,0,0
HB-039987,Resort Hotel,0,9,2025,August,35,28,2025-08-28,1,5,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,232.5,0,2
HB-105398,City Hotel,0,21,2025,February,6,6,2025-02-06,1,0,1,0.0,0,BB,FRA,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,179.0,0,Transient,80.0,0,0
HB-116981,City Hotel,0,166,2025,July,30,21,2025-07-21,2,5,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,110.94,0,0
HB-051413,City Hotel,1,322,2024,May,20,19,2024-05-19,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,120,Transient,80.0,0,0
HB-054136,City Hotel,1,365,2024,July,27,7,2024-07-07,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-004905,Resort Hotel,1,85,2024,April,14,7,2024-04-07,0,3,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,67.0,,0,Transient-Party,64.0,0,0
HB-087018,City Hotel,0,86,2024,April,15,9,2024-04-09,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,B,1,No Deposit,121.0,,0,Transient-Party,80.75,0,1
HB-081151,City Hotel,0,1,2023,December,48,1,2023-12-01,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient,34.5,0,0
HB-029234,Resort Hotel,0,386,2024,October,42,20,2024-10-20,1,3,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,2,No Deposit,,,0,Transient-Party,49.0,0,0
HB-072990,City Hotel,1,160,2025,August,33,11,2025-08-11,1,2,2,0.0,0,SC,DNK,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.83,0,0
HB-071316,City Hotel,1,60,2025,July,27,2,2025-07-02,2,0,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,1
HB-090971,City Hotel,0,4,2024,June,24,12,2024-06-12,2,0,2,0.0,0,SC,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,72.25,0,0
HB-063040,City Hotel,1,28,2025,January,5,27,2025-01-27,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.5,0,0
HB-059228,City Hotel,1,115,2024,October,43,22,2024-10-22,2,3,2,0.0,0,BB,TUR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.64,0,3
HB-049908,City Hotel,1,270,2024,April,16,20,2024-04-20,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,187,Transient-Party,62.8,0,0
HB-085194,City Hotel,0,52,2024,April,16,18,2024-04-18,1,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,8,E,E,0,No Deposit,,51.0,0,Transient,106.0,0,1
HB-076280,City Hotel,1,147,2023,July,29,21,2023-07-21,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient,75.0,0,0
HB-061875,City Hotel,1,246,2024,December,52,27,2024-12-27,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,58.36,0,1
HB-108672,City Hotel,0,306,2025,March,13,27,2025-03-27,1,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,86.35,1,2
HB-062707,City Hotel,1,559,2025,January,3,19,2025-01-19,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-030333,Resort Hotel,0,26,2024,November,45,6,2024-11-06,4,10,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,68.72,0,0
HB-105164,City Hotel,0,15,2025,January,5,27,2025-01-27,2,3,1,0.0,0,BB,ESP,Online TA,GDS,0,0,0,A,A,0,No Deposit,195.0,,0,Transient,98.0,0,0
HB-108526,City Hotel,0,158,2025,March,13,27,2025-03-27,1,1,2,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,95.0,0,1
HB-056665,City Hotel,1,198,2024,September,37,9,2024-09-09,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,90.0,0,0
HB-064165,City Hotel,1,28,2025,March,9,2,2025-03-02,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,95.0,0,0
HB-023516,Resort Hotel,0,113,2024,April,17,26,2024-04-26,0,2,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,241.0,,0,Transient,78.31,0,1
HB-007719,Resort Hotel,1,54,2024,August,34,22,2024-08-22,1,4,3,1.0,0,HB,ESP,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,322.0,0,1
HB-019092,Resort Hotel,0,26,2023,December,49,5,2023-12-05,2,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,58.0,0,0
HB-008197,Resort Hotel,0,363,2024,September,38,16,2024-09-16,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Transient,64.9,0,0
HB-096063,City Hotel,0,143,2024,August,34,25,2024-08-25,0,3,2,0.0,0,BB,CZE,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,36.0,,0,Transient-Party,100.0,0,0
HB-056697,City Hotel,1,242,2024,September,37,10,2024-09-10,2,2,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,100.3,0,0
HB-031665,Resort Hotel,0,98,2024,December,52,27,2024-12-27,2,5,1,1.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,6.0,,0,Transient,78.19,0,1
HB-075584,City Hotel,0,257,2023,July,26,1,2023-07-01,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,101.5,0,0
HB-085552,City Hotel,0,21,2024,March,11,14,2024-03-14,1,3,1,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.0,0,1
HB-076812,City Hotel,0,1,2023,November,44,5,2023-11-05,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,2,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-006139,Resort Hotel,0,225,2024,May,21,26,2024-05-26,1,3,2,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,C,2,No Deposit,,223.0,0,Transient-Party,68.0,0,0
HB-065145,City Hotel,1,278,2025,March,13,25,2025-03-25,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient,90.0,0,0
HB-112194,City Hotel,0,31,2025,May,20,18,2025-05-18,0,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,144.4,0,2
HB-000353,Resort Hotel,0,0,2023,July,28,13,2023-07-13,1,1,2,0.0,0,BB,AUS,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient,117.9,1,0
HB-029451,Resort Hotel,0,115,2024,October,43,23,2024-10-23,2,4,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,49.0,0,1
HB-018827,Resort Hotel,1,8,2023,December,49,5,2023-12-05,2,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,38.0,,0,Transient-Party,68.0,0,0
HB-019228,Resort Hotel,1,92,2024,February,9,26,2024-02-26,1,2,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,134.0,,0,Transient,79.0,0,0
HB-030375,Resort Hotel,0,65,2024,November,47,18,2024-11-18,1,2,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,314.0,,0,Transient,58.24,0,0
HB-041475,City Hotel,1,46,2023,August,33,17,2023-08-17,1,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,60.0,0,0
HB-106982,City Hotel,0,17,2025,March,9,2,2025-03-02,1,3,2,0.0,0,BB,DNK,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,70.69,0,1
HB-094940,City Hotel,0,189,2024,August,32,8,2024-08-08,1,3,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient-Party,72.25,0,0
HB-115177,City Hotel,0,103,2025,July,27,3,2025-07-03,1,2,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Group,169.2,0,3
HB-119226,City Hotel,0,213,2025,August,35,28,2025-08-28,1,3,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,19.0,,0,Transient-Party,104.0,0,0
HB-113038,City Hotel,0,6,2025,May,22,30,2025-05-30,0,2,1,0.0,0,BB,BEL,Aviation,Corporate,0,0,0,D,D,0,No Deposit,,153.0,0,Transient,110.0,0,0
HB-045473,City Hotel,1,99,2023,October,44,30,2023-10-30,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,65.0,0,0
HB-042191,City Hotel,0,0,2023,September,35,2,2023-09-02,0,2,2,0.0,0,SC,AUS,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Contract,105.5,0,0
HB-081051,City Hotel,1,86,2024,January,4,22,2024-01-22,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,29.0,,35,Transient,75.0,0,0
HB-062600,City Hotel,1,22,2025,January,3,16,2025-01-16,1,5,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,99.24,0,0
HB-097442,City Hotel,0,96,2024,September,37,13,2024-09-13,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,16.0,,0,Transient,90.95,0,0
HB-022928,Resort Hotel,0,3,2024,April,15,9,2024-04-09,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,45.0,0,0
HB-039671,Resort Hotel,0,169,2025,August,34,20,2025-08-20,2,3,2,0.0,1,HB,PRT,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,240.0,,0,Transient,262.0,1,4
HB-112263,City Hotel,0,12,2025,May,21,20,2025-05-20,1,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,170.0,0,1
HB-088894,City Hotel,0,39,2024,May,19,12,2024-05-12,0,2,2,0.0,0,BB,NOR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,116.1,0,0
HB-068345,City Hotel,1,70,2025,May,20,15,2025-05-15,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,144.0,0,0
HB-083671,City Hotel,0,20,2024,February,6,8,2024-02-08,1,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,83.8,0,1
HB-084417,City Hotel,0,1,2024,February,8,25,2024-02-25,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,80.0,0,0
HB-048471,City Hotel,1,33,2024,March,12,24,2024-03-24,0,2,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,143.1,0,0
HB-008175,Resort Hotel,0,336,2024,September,37,15,2024-09-15,1,3,1,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,A,1,No Deposit,,223.0,0,Transient-Party,62.0,0,0
HB-063939,City Hotel,1,134,2025,February,9,25,2025-02-25,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,D,0,No Deposit,30.0,,0,Transient-Party,75.0,0,0
HB-110805,City Hotel,0,168,2025,April,18,29,2025-04-29,2,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,2
HB-094543,City Hotel,0,131,2024,August,31,3,2024-08-03,0,3,2,0.0,0,BB,USA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,,,0,Transient,87.03,0,3
HB-066564,City Hotel,1,195,2025,April,17,21,2025-04-21,2,2,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,1
HB-099847,City Hotel,0,48,2024,October,42,15,2024-10-15,2,2,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,158.4,0,0
HB-000418,Resort Hotel,0,57,2023,July,28,15,2023-07-15,0,2,2,0.0,0,FB,PRT,Groups,Direct,0,0,0,A,D,0,No Deposit,305.0,,0,Transient,107.0,0,0
HB-082932,City Hotel,1,177,2024,May,19,8,2024-05-08,2,0,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,3.0,,0,Transient,121.0,0,0
HB-075643,City Hotel,1,290,2023,August,31,3,2023-08-03,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-058896,City Hotel,1,605,2024,October,42,17,2024-10-17,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-076318,City Hotel,1,164,2023,July,29,20,2023-07-20,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,B,B,0,No Deposit,13.0,,0,Transient-Party,63.75,0,2
HB-099099,City Hotel,0,17,2024,October,41,7,2024-10-07,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.0,0,1
HB-091529,City Hotel,0,0,2024,June,25,22,2024-06-22,0,1,1,0.0,0,BB,GBR,Aviation,Corporate,0,0,0,A,A,0,No Deposit,,153.0,0,Transient,95.0,0,0
HB-014886,Resort Hotel,1,265,2023,September,38,24,2023-09-24,1,3,2,0.0,0,HB,BEL,Groups,Corporate,0,14,0,A,A,0,Non Refund,183.0,,0,Transient,89.2,0,0
HB-074867,City Hotel,1,164,2023,August,33,14,2023-08-14,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-023768,Resort Hotel,0,0,2024,May,18,2,2024-05-02,1,0,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,79.0,0,0
HB-038592,Resort Hotel,0,69,2025,July,29,18,2025-07-18,0,5,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,200.0,0,2
HB-031433,Resort Hotel,0,94,2024,December,52,24,2024-12-24,2,3,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,30.24,0,0
HB-042142,City Hotel,0,1,2023,September,35,1,2023-09-01,0,1,1,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,F,0,No Deposit,,45.0,0,Transient,0.0,0,1
HB-102624,City Hotel,0,79,2024,November,48,29,2024-11-29,0,4,2,1.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,122.0,0,2
HB-106368,City Hotel,0,17,2025,February,8,19,2025-02-19,2,3,2,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,9.0,,0,Transient,177.31,0,0
HB-024204,Resort Hotel,0,101,2024,May,20,14,2024-05-14,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,F,0,No Deposit,240.0,,0,Transient,94.0,1,1
HB-080428,City Hotel,1,34,2023,December,49,8,2023-12-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,0,Transient,90.0,0,0
HB-076745,City Hotel,1,327,2023,September,36,9,2023-09-09,2,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,4.0,,0,Transient-Party,76.0,0,0
HB-103894,City Hotel,0,203,2024,December,52,29,2024-12-29,1,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,102.85,0,2
HB-104295,City Hotel,0,0,2025,January,2,10,2025-01-10,0,1,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.5,0,0
HB-086352,City Hotel,0,50,2024,March,13,28,2024-03-28,1,3,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.85,0,0
HB-049767,City Hotel,1,103,2024,April,16,19,2024-04-19,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,0,Transient,115.0,0,0
HB-052879,City Hotel,1,71,2024,June,24,14,2024-06-14,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,120.0,0,0
HB-088821,City Hotel,0,111,2024,May,19,9,2024-05-09,1,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,102.75,0,1
HB-051656,City Hotel,1,158,2024,May,21,24,2024-05-24,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,31,Transient,130.0,0,0
HB-030947,Resort Hotel,0,203,2024,December,49,2,2024-12-02,2,5,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,F,F,4,No Deposit,250.0,,0,Transient,66.8,0,0
HB-024424,Resort Hotel,0,25,2024,May,20,16,2024-05-16,1,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,G,G,1,No Deposit,,,0,Transient,135.0,0,2
HB-068043,City Hotel,1,116,2025,May,19,11,2025-05-11,1,3,3,0.0,0,BB,COL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,181.8,0,0
HB-080840,City Hotel,1,54,2023,December,48,1,2023-12-01,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,1,0,A,A,0,No Deposit,,,0,Transient-Party,81.0,0,0
HB-068052,City Hotel,1,142,2025,May,19,11,2025-05-11,2,3,2,0.0,0,SC,MOZ,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,129.6,0,1
HB-107875,City Hotel,0,137,2025,March,12,17,2025-03-17,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.6,0,2
HB-089693,City Hotel,0,212,2024,May,21,20,2024-05-20,2,3,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,21.0,,0,Transient-Party,70.0,0,0
HB-045537,City Hotel,1,80,2023,November,44,2,2023-11-02,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,37.0,60,Transient,111.0,0,0
HB-020391,Resort Hotel,0,1,2024,January,4,26,2024-01-26,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,40.0,0,1
HB-045323,City Hotel,0,69,2023,October,43,25,2023-10-25,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,58,Transient-Party,85.67,0,0
HB-054520,City Hotel,1,185,2024,July,29,18,2024-07-18,2,5,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.95,0,0
HB-049725,City Hotel,1,90,2024,April,16,18,2024-04-18,1,2,1,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.9,0,1
HB-035940,Resort Hotel,0,85,2025,April,18,29,2025-04-29,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,143.0,,0,Transient,70.66,0,0
HB-042125,City Hotel,0,3,2023,August,35,31,2023-08-31,1,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,46.54,0,0
HB-040974,City Hotel,1,4,2023,August,32,10,2023-08-10,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,75.0,0,0
HB-065560,City Hotel,1,373,2025,April,14,5,2025-04-05,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-014696,Resort Hotel,1,259,2023,September,37,17,2023-09-17,0,3,2,0.0,0,BB,GBR,Groups,Corporate,0,1,0,A,A,0,Non Refund,,223.0,0,Transient,40.05,0,0
HB-015876,Resort Hotel,0,6,2025,February,8,22,2025-02-22,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,4,A,E,1,No Deposit,,103.0,0,Transient,35.0,0,0
HB-085548,City Hotel,0,56,2024,March,11,15,2024-03-15,0,3,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,56.83,0,1
HB-081617,City Hotel,1,130,2024,April,15,13,2024-04-13,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,29.0,,10,Transient,100.0,0,0
HB-114979,City Hotel,0,8,2025,June,26,29,2025-06-29,0,1,1,0.0,0,BB,ESP,Online TA,GDS,0,0,0,A,A,0,No Deposit,195.0,,0,Transient,170.0,0,0
HB-042028,City Hotel,0,2,2023,August,35,30,2023-08-30,1,0,1,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,D,1,No Deposit,37.0,,0,Transient-Party,65.0,0,2
HB-112730,City Hotel,0,180,2025,May,21,25,2025-05-25,0,3,2,1.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,144.0,0,0
HB-117199,City Hotel,0,156,2025,July,31,28,2025-07-28,1,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,90.0,0,1
HB-077304,City Hotel,0,256,2023,September,37,14,2023-09-14,1,2,2,0.0,0,BB,SWE,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,4.0,,0,Transient-Party,76.67,0,0
HB-008469,Resort Hotel,1,231,2024,September,40,30,2024-09-30,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,96.0,,0,Transient,57.6,0,0
HB-106226,City Hotel,0,27,2025,February,9,27,2025-02-27,1,0,1,0.0,0,SC,IRL,Online TA,TA/TO,0,0,1,A,A,0,No Deposit,9.0,,0,Group,88.0,0,2
HB-044206,City Hotel,0,164,2023,October,40,2,2023-10-02,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,19.0,,0,Transient-Party,100.0,0,0
HB-004794,Resort Hotel,1,169,2024,March,13,31,2024-03-31,1,3,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Refundable,,223.0,0,Transient-Party,46.0,0,0
HB-029067,Resort Hotel,0,1,2024,October,42,18,2024-10-18,0,2,1,0.0,0,BB,PRT,Direct,Corporate,0,0,0,A,B,0,No Deposit,,120.0,0,Transient,56.0,1,0
HB-009413,Resort Hotel,1,46,2024,November,48,26,2024-11-26,0,1,3,1.0,0,HB,PRT,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,135.0,0,0
HB-090629,City Hotel,0,16,2024,June,23,8,2024-06-08,0,1,2,0.0,0,BB,CYP,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,92.65,0,0
HB-040864,City Hotel,1,30,2023,August,32,8,2023-08-08,2,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,86.0,0,0
HB-078067,City Hotel,0,0,2023,October,39,1,2023-10-01,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,96.0,0,Transient,109.0,0,1
HB-078428,City Hotel,0,13,2023,October,40,6,2023-10-06,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Transient,75.0,0,1
HB-040437,City Hotel,0,16,2023,July,30,25,2023-07-25,2,1,3,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,D,1,No Deposit,1.0,,0,Transient-Party,124.7,0,0
HB-013859,Resort Hotel,0,5,2024,April,14,5,2024-04-05,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,1,4,A,D,0,No Deposit,,94.0,0,Transient,39.0,0,0
HB-024721,Resort Hotel,0,1,2024,May,22,31,2024-05-31,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient,79.0,0,0
HB-105181,City Hotel,0,0,2025,January,5,31,2025-01-31,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,78.4,0,0
HB-091546,City Hotel,0,45,2024,June,25,19,2024-06-19,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,79.33,0,1
HB-049982,City Hotel,1,66,2024,April,17,22,2024-04-22,0,2,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,137.7,0,1
HB-056471,City Hotel,1,65,2024,September,36,7,2024-09-07,0,3,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,136.8,0,0
HB-106304,City Hotel,0,48,2025,February,8,22,2025-02-22,0,2,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,65.0,0,1
HB-065147,City Hotel,1,278,2025,March,13,25,2025-03-25,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient,90.0,0,0
HB-001598,Resort Hotel,1,54,2023,September,36,5,2023-09-05,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,131.0,0,2
HB-029061,Resort Hotel,0,159,2024,October,42,16,2024-10-16,2,2,1,0.0,0,HB,SWE,Groups,Corporate,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,58.0,0,0
HB-111751,City Hotel,0,101,2025,May,20,12,2025-05-12,1,2,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,147.0,0,1
HB-063859,City Hotel,1,38,2025,February,8,23,2025-02-23,0,3,1,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,118.0,0,0
HB-065470,City Hotel,1,372,2025,April,14,4,2025-04-04,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-013918,Resort Hotel,0,10,2025,May,20,15,2025-05-15,1,1,1,0.0,0,BB,PRT,Corporate,Direct,0,0,1,A,D,0,No Deposit,,530.0,0,Transient,63.5,1,0
HB-043007,City Hotel,0,68,2023,September,37,12,2023-09-12,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-090622,City Hotel,0,43,2024,June,23,8,2024-06-08,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,80.39,0,2
HB-080065,City Hotel,0,46,2023,November,45,7,2023-11-07,2,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,E,0,No Deposit,28.0,,0,Transient,60.0,0,0
HB-028177,Resort Hotel,0,41,2024,September,38,18,2024-09-18,2,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,80.0,0,1
HB-117188,City Hotel,0,130,2025,July,30,24,2025-07-24,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,80.1,0,1
HB-068484,City Hotel,1,48,2025,May,20,18,2025-05-18,1,3,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,1
HB-109783,City Hotel,0,74,2025,April,16,16,2025-04-16,1,0,2,2.0,0,BB,DEU,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,195.0,0,0
HB-042200,City Hotel,0,63,2023,September,35,2,2023-09-02,0,3,1,0.0,0,BB,BRA,Groups,TA/TO,0,0,0,A,D,1,No Deposit,1.0,,0,Transient-Party,0.0,0,0
HB-097789,City Hotel,0,75,2024,September,38,17,2024-09-17,2,2,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,80.75,0,0
HB-013893,Resort Hotel,0,39,2024,July,28,12,2024-07-12,0,1,2,0.0,0,BB,PRT,Offline TA/TO,Direct,0,0,4,A,C,1,No Deposit,126.0,,0,Transient,132.0,1,0
HB-061701,City Hotel,1,381,2024,December,52,23,2024-12-23,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient,78.55,0,1
HB-077234,City Hotel,0,327,2023,September,36,9,2023-09-09,2,4,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,88.0,0,0
HB-011329,Resort Hotel,1,93,2025,May,18,3,2025-05-03,0,3,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,147.0,0,2
HB-076282,City Hotel,1,147,2023,July,29,21,2023-07-21,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient,75.0,0,0
HB-118233,City Hotel,0,83,2025,August,33,13,2025-08-13,2,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,150.0,0,1
HB-094654,City Hotel,0,1,2024,August,32,7,2024-08-07,1,0,2,0.0,0,SC,CN,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,9.0,,0,Transient,98.0,0,0
HB-075984,City Hotel,1,301,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-118656,City Hotel,0,116,2025,August,34,20,2025-08-20,2,2,2,2.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,168.0,,0,Transient,178.5,0,0
HB-065267,City Hotel,1,73,2025,March,13,30,2025-03-30,0,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.8,0,0
HB-004063,Resort Hotel,1,140,2024,February,7,12,2024-02-12,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,50.0,0,0
HB-091968,City Hotel,0,149,2024,June,26,25,2024-06-25,2,1,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,85.0,,0,Transient,80.75,0,1
HB-012267,Resort Hotel,1,43,2025,June,25,21,2025-06-21,0,4,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,D,D,0,No Deposit,531.0,,0,Transient,76.0,0,0
HB-110615,City Hotel,0,52,2025,April,17,27,2025-04-27,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,9.0,,0,Transient,171.0,0,3
HB-042559,City Hotel,0,0,2023,September,36,7,2023-09-07,1,1,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,13.0,,0,Contract,99.2,0,0
HB-099707,City Hotel,0,377,2024,October,42,14,2024-10-14,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-050769,City Hotel,1,127,2024,May,19,7,2024-05-07,2,1,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient-Party,94.5,0,0
HB-083797,City Hotel,0,1,2024,February,6,10,2024-02-10,0,3,1,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,86.0,0,0
HB-012434,Resort Hotel,1,51,2025,June,26,29,2025-06-29,2,5,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,D,D,0,No Deposit,531.0,,0,Transient,76.0,0,0
HB-000325,Resort Hotel,0,12,2023,July,28,12,2023-07-12,4,5,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,148.3,1,2
HB-075812,City Hotel,1,330,2023,September,37,12,2023-09-12,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-073206,City Hotel,1,142,2025,August,33,16,2025-08-16,0,4,3,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.0,0,0
HB-108634,City Hotel,0,91,2025,March,13,29,2025-03-29,0,2,2,0.0,0,SC,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,60.98,0,1
HB-051769,City Hotel,1,1,2024,May,21,25,2024-05-25,0,1,1,0.0,0,BB,PRT,Aviation,Corporate,0,0,0,A,A,0,No Deposit,,153.0,0,Transient,95.0,0,0
HB-005050,Resort Hotel,0,183,2024,April,16,16,2024-04-16,1,1,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,1,No Deposit,298.0,,0,Transient-Party,42.5,0,0
HB-112495,City Hotel,0,20,2025,May,21,24,2025-05-24,0,1,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,87.0,,0,Transient-Party,120.0,0,0
HB-059838,City Hotel,1,482,2024,November,44,3,2024-11-03,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-010803,Resort Hotel,1,152,2025,April,14,5,2025-04-05,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,D,E,1,No Deposit,,223.0,0,Transient-Party,60.0,0,0
HB-102322,City Hotel,0,72,2024,November,47,24,2024-11-24,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-032565,Resort Hotel,0,43,2025,January,5,27,2025-01-27,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient-Party,48.0,0,1
HB-032759,Resort Hotel,0,3,2025,February,5,2,2025-02-02,0,3,2,0.0,0,BB,SVN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,56.0,0,0
HB-003080,Resort Hotel,1,121,2023,November,46,14,2023-11-14,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,40.93,0,1
HB-073131,City Hotel,1,31,2025,August,33,15,2025-08-15,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,180.0,0,1
HB-035502,Resort Hotel,0,61,2025,April,16,18,2025-04-18,1,5,1,0.0,0,BB,ITA,Groups,Corporate,0,0,0,A,A,1,No Deposit,,307.0,0,Transient-Party,85.0,0,0
HB-079852,City Hotel,1,34,2023,December,49,8,2023-12-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,0,Transient,90.0,0,0
HB-041536,City Hotel,1,46,2023,August,33,17,2023-08-17,1,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,60.0,0,0
HB-019469,Resort Hotel,0,19,2023,December,51,21,2023-12-21,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,D,2,No Deposit,240.0,,0,Transient,56.33,1,0
HB-041403,City Hotel,1,131,2023,August,33,15,2023-08-15,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-081156,City Hotel,0,0,2024,November,47,21,2024-11-21,1,0,2,0.0,0,BB,PRT,Direct,Direct,1,0,1,E,E,0,No Deposit,,,0,Transient,150.0,0,1
HB-038163,Resort Hotel,0,3,2025,July,28,10,2025-07-10,1,0,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,97.0,0,1
HB-031085,Resort Hotel,0,1,2024,December,50,13,2024-12-13,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,2
HB-118190,City Hotel,0,126,2025,August,33,12,2025-08-12,2,2,2,2.0,0,HB,ESP,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,159.0,,0,Transient,198.44,0,0
HB-031183,Resort Hotel,0,1,2024,December,51,16,2024-12-16,0,2,2,0.0,1,BB,ESP,Corporate,Corporate,0,0,0,G,G,1,No Deposit,,496.0,0,Transient,81.0,1,2
HB-004134,Resort Hotel,0,192,2024,February,7,15,2024-02-15,1,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,50.4,0,2
HB-086316,City Hotel,0,115,2024,March,13,28,2024-03-28,1,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,58.0,0,0
HB-080932,City Hotel,0,0,2023,November,48,28,2023-11-28,0,1,2,0.0,0,BB,AGO,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,152.0,,0,Transient,54.31,0,0
HB-085097,City Hotel,0,12,2024,March,10,7,2024-03-07,1,1,1,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,86.0,0,1
HB-112334,City Hotel,0,19,2025,May,21,20,2025-05-20,2,1,1,0.0,0,SC,FIN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,98.8,0,1
HB-055214,City Hotel,1,10,2024,August,32,8,2024-08-08,1,0,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,139.0,0,1
HB-075678,City Hotel,1,295,2023,August,32,8,2023-08-08,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-110478,City Hotel,0,140,2025,April,18,28,2025-04-28,2,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,119.0,,0,Transient-Party,130.0,0,2
HB-028946,Resort Hotel,0,5,2024,October,42,16,2024-10-16,1,0,1,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,75.0,0,0
HB-107383,City Hotel,0,87,2025,March,10,9,2025-03-09,0,3,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,60.98,0,1
HB-063205,City Hotel,1,573,2025,February,5,2,2025-02-02,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-064762,City Hotel,1,64,2025,March,11,15,2025-03-15,2,8,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,100.3,0,1
HB-072753,City Hotel,1,191,2025,August,32,5,2025-08-05,1,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,3,No Deposit,9.0,,0,Transient,139.5,0,0
HB-034350,Resort Hotel,0,24,2025,March,12,18,2025-03-18,2,1,2,0.0,0,FB,GBR,Online TA,TA/TO,0,0,0,A,C,1,No Deposit,314.0,,0,Transient,93.13,0,0
HB-112411,City Hotel,0,12,2025,May,21,23,2025-05-23,0,1,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.0,0,1
HB-056380,City Hotel,1,62,2024,September,36,4,2024-09-04,2,2,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient,96.23,0,0
HB-030767,Resort Hotel,0,10,2024,December,49,3,2024-12-03,0,1,1,0.0,0,HB,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,44.0,0,0
HB-065109,City Hotel,1,39,2025,March,13,24,2025-03-24,1,2,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,B,1,No Deposit,9.0,,0,Transient,91.33,0,3
HB-066513,City Hotel,1,130,2025,April,17,21,2025-04-21,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,286.0,,0,Transient,95.0,0,0
HB-078133,City Hotel,0,12,2023,October,40,4,2023-10-04,1,0,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,3.0,,0,Transient-Party,72.0,0,0
HB-011832,Resort Hotel,1,1,2025,June,22,1,2025-06-01,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,90.0,0,0
HB-015660,Resort Hotel,1,468,2024,May,19,12,2024-05-12,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,249.0,,0,Transient-Party,67.0,0,0
HB-079858,City Hotel,1,34,2023,December,49,8,2023-12-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,0,Transient,90.0,0,0
HB-079400,City Hotel,0,41,2023,October,43,23,2023-10-23,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,7.0,,0,Group,110.09,0,1
HB-039645,Resort Hotel,0,16,2025,August,34,22,2025-08-22,0,2,3,1.0,0,HB,GBR,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,382.0,1,1
HB-042854,City Hotel,0,72,2023,September,37,11,2023-09-11,0,2,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,D,1,No Deposit,30.0,,0,Transient-Party,98.0,0,0
HB-030707,Resort Hotel,0,6,2024,November,47,22,2024-11-22,2,8,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,35.99,0,1
HB-030573,Resort Hotel,0,45,2024,November,48,25,2024-11-25,0,2,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,67.8,0,2
HB-106965,City Hotel,0,11,2025,March,10,3,2025-03-03,0,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,112.5,0,1
HB-012506,Resort Hotel,1,100,2025,July,27,2,2025-07-02,2,4,1,2.0,0,BB,BRA,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,190.0,0,2
HB-027280,Resort Hotel,0,68,2024,August,33,18,2024-08-18,2,5,2,1.0,0,HB,ROU,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,279.36,0,2
HB-031648,Resort Hotel,0,71,2024,December,52,29,2024-12-29,1,3,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,2,No Deposit,,,0,Transient,154.69,0,1
HB-102939,City Hotel,0,56,2024,December,49,7,2024-12-07,0,3,0,2.0,0,BB,ITA,Online TA,TA/TO,0,0,0,B,A,1,No Deposit,9.0,,0,Transient,82.44,0,1
HB-051389,City Hotel,1,316,2024,May,20,19,2024-05-19,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-107831,City Hotel,0,3,2025,March,12,17,2025-03-17,0,2,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,127.0,0,1
HB-081022,City Hotel,1,86,2024,January,4,22,2024-01-22,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,29.0,,35,Transient,85.0,0,0
HB-098049,City Hotel,0,294,2024,September,38,21,2024-09-21,0,4,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,26.0,,0,Transient-Party,117.0,0,1
HB-073623,City Hotel,1,168,2025,August,35,28,2025-08-28,1,2,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,175.5,0,0
HB-098674,City Hotel,0,193,2024,September,40,30,2024-09-30,1,2,2,0.0,0,BB,DEU,Groups,Corporate,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,132.0,0,0
HB-044962,City Hotel,1,102,2023,October,42,16,2023-10-16,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-059325,City Hotel,1,475,2024,October,43,27,2024-10-27,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,59.0,0,0
HB-101193,City Hotel,0,3,2024,November,44,3,2024-11-03,2,3,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,146.4,0,2
HB-047934,City Hotel,1,35,2024,March,10,10,2024-03-10,0,1,1,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,71.1,0,0
HB-079785,City Hotel,0,6,2023,November,44,3,2023-11-03,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,105.0,0,0
HB-110496,City Hotel,0,38,2025,April,17,24,2025-04-24,1,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,9.0,,0,Transient,174.0,0,3
HB-113805,City Hotel,0,34,2025,June,23,8,2025-06-08,1,3,1,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,108.0,0,0
HB-071008,City Hotel,1,145,2025,June,26,27,2025-06-27,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-002725,Resort Hotel,0,49,2023,October,43,28,2023-10-28,2,5,1,0.0,0,HB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,69.76,1,1
HB-098934,City Hotel,0,22,2024,October,40,5,2024-10-05,0,2,3,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,115.0,0,0
HB-075859,City Hotel,1,351,2023,October,40,3,2023-10-03,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-086582,City Hotel,0,68,2024,April,14,1,2024-04-01,2,3,2,0.0,0,HB,BEL,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient-Party,130.9,0,1
HB-020060,Resort Hotel,0,0,2024,January,2,13,2024-01-13,0,2,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,38.0,0,0
HB-053591,City Hotel,1,121,2024,June,26,24,2024-06-24,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,90.0,0,0
HB-092850,City Hotel,1,0,2024,October,42,17,2024-10-17,1,0,1,0.0,0,BB,ESP,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,62.0,0,Transient,95.0,0,0
HB-016639,Resort Hotel,0,47,2023,August,35,30,2023-08-30,2,4,2,0.0,1,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,100.7,1,1
HB-026895,Resort Hotel,0,213,2024,August,32,8,2024-08-08,1,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,126.0,0,2
HB-019363,Resort Hotel,0,0,2023,December,50,15,2023-12-15,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,290.0,0,Transient,35.0,0,0
HB-004159,Resort Hotel,1,100,2024,February,8,20,2024-02-20,2,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,38.32,0,2
HB-017405,Resort Hotel,0,90,2023,October,40,5,2023-10-05,1,4,1,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,47.0,0,0
HB-116103,City Hotel,0,414,2025,July,28,13,2025-07-13,0,2,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,114.4,0,1
HB-108610,City Hotel,0,77,2025,March,13,26,2025-03-26,2,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,67.15,0,1
HB-022685,Resort Hotel,0,129,2024,March,13,25,2024-03-25,2,6,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,50.17,0,2
HB-019049,Resort Hotel,0,0,2024,January,2,14,2024-01-14,0,1,2,0.0,0,BB,PRT,Direct,Direct,1,0,3,A,D,0,No Deposit,,,0,Transient,44.0,1,0
HB-088454,City Hotel,0,0,2025,May,22,30,2025-05-30,0,3,1,0.0,0,BB,PRT,Aviation,Corporate,1,0,1,A,A,0,No Deposit,,153.0,0,Transient,95.0,0,2
HB-032385,Resort Hotel,0,2,2025,January,4,21,2025-01-21,2,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,55.0,1,1
HB-094567,City Hotel,0,147,2024,August,32,5,2024-08-05,0,1,1,1.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,78.1,0,0
HB-016187,Resort Hotel,0,196,2023,August,32,11,2023-08-11,2,5,2,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,142.0,,0,Contract,96.3,0,0
HB-082139,City Hotel,1,99,2024,February,8,19,2024-02-19,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,1,0,A,A,0,No Deposit,,67.0,0,Transient-Party,80.0,0,0
HB-082956,City Hotel,0,80,2024,January,1,7,2024-01-07,0,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,87.32,0,0
HB-023717,Resort Hotel,0,197,2024,April,18,30,2024-04-30,1,1,1,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,1,No Deposit,298.0,,0,Transient-Party,54.5,0,0
HB-042396,City Hotel,1,61,2023,September,36,5,2023-09-05,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-026273,Resort Hotel,0,18,2024,July,30,24,2024-07-24,2,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,206.0,1,1
HB-045770,City Hotel,0,98,2023,November,47,23,2023-11-23,1,2,1,0.0,0,BB,DEU,Groups,TA/TO,0,0,0,A,D,0,No Deposit,37.0,,0,Transient-Party,70.0,0,0
HB-097184,City Hotel,0,23,2024,September,37,11,2024-09-11,2,0,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,10.0,,0,Transient,100.1,0,2
HB-028866,Resort Hotel,0,0,2024,October,41,10,2024-10-10,1,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,1,No Deposit,,,0,Transient,75.0,0,1
HB-095853,City Hotel,0,0,2024,August,33,18,2024-08-18,2,5,2,0.0,0,BB,DNK,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,86.7,0,0
HB-068669,City Hotel,1,175,2025,May,21,19,2025-05-19,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,0,Transient,110.0,0,0
HB-086825,City Hotel,0,79,2024,April,14,4,2024-04-04,1,5,2,0.0,0,BB,ZAF,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,67.85,0,1
HB-061617,City Hotel,1,72,2024,December,51,19,2024-12-19,1,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,0
HB-102950,City Hotel,0,61,2024,December,49,8,2024-12-08,0,2,0,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient-Party,91.6,0,0
HB-106046,City Hotel,0,242,2025,February,7,16,2025-02-16,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,99.2,0,0
HB-028117,Resort Hotel,0,245,2024,September,38,17,2024-09-17,2,2,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,E,1,No Deposit,240.0,,0,Transient,95.0,0,2
HB-067253,City Hotel,1,28,2025,April,18,30,2025-04-30,2,1,2,0.0,0,SC,MAR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,141.0,0,1
HB-088539,City Hotel,0,53,2024,May,19,6,2024-05-06,0,2,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,159.3,0,3
HB-108047,City Hotel,0,138,2025,March,12,18,2025-03-18,2,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,68.07,0,1
HB-047501,City Hotel,1,45,2024,February,8,24,2024-02-24,0,3,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,67.5,0,1
HB-106208,City Hotel,0,2,2025,March,9,1,2025-03-01,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,D,0,No Deposit,,219.0,0,Transient,89.0,0,2
HB-024612,Resort Hotel,0,114,2024,May,19,12,2024-05-12,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,I,0,No Deposit,243.0,,0,Contract,48.75,0,1
HB-056657,City Hotel,1,198,2024,September,37,9,2024-09-09,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,120.0,0,0
HB-061276,City Hotel,1,26,2024,December,49,6,2024-12-06,2,5,1,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.4,0,3
HB-022397,Resort Hotel,0,20,2024,March,12,22,2024-03-22,0,2,3,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,,0,Transient,95.0,0,1
HB-019371,Resort Hotel,0,2,2023,December,48,2,2023-12-02,4,10,1,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,37.7,0,0
HB-017454,Resort Hotel,0,221,2023,October,41,10,2023-10-10,1,1,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,C,0,No Deposit,208.0,,0,Transient-Party,74.0,0,1
HB-096073,City Hotel,0,30,2024,August,34,25,2024-08-25,0,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,83.0,,0,Transient,137.52,0,0
HB-034049,Resort Hotel,0,312,2025,March,10,5,2025-03-05,2,5,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,56.0,0,0
HB-017767,Resort Hotel,0,7,2023,October,42,19,2023-10-19,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,8.0,,0,Transient-Party,37.0,0,0
HB-073046,City Hotel,1,78,2025,August,33,13,2025-08-13,1,0,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.0,0,1
HB-031195,Resort Hotel,0,3,2024,December,51,17,2024-12-17,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,39.0,0,1
HB-054147,City Hotel,1,128,2024,July,27,7,2024-07-07,0,3,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,103.5,0,0
HB-117155,City Hotel,0,156,2025,July,31,28,2025-07-28,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,112.5,0,1
HB-035188,Resort Hotel,0,34,2025,April,15,8,2025-04-08,2,5,2,2.0,0,BB,HUN,Direct,Direct,0,0,0,C,C,0,No Deposit,250.0,,0,Transient,118.57,0,3
HB-040040,Resort Hotel,0,108,2025,August,35,31,2025-08-31,2,5,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,207.03,0,1
HB-101651,City Hotel,0,5,2024,November,45,10,2024-11-10,2,4,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,106.21,0,2
HB-003176,Resort Hotel,1,36,2023,November,47,20,2023-11-20,0,2,2,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,38.0,,0,Transient-Party,64.0,0,0
HB-117949,City Hotel,0,41,2025,August,32,7,2025-08-07,1,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,1
HB-007561,Resort Hotel,1,212,2024,August,33,14,2024-08-14,4,10,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,140.0,0,2
HB-055689,City Hotel,1,79,2024,August,34,19,2024-08-19,0,2,2,0.0,0,BB,AUS,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,149.4,0,0
HB-020634,Resort Hotel,0,6,2025,March,13,27,2025-03-27,1,3,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,2,A,A,0,No Deposit,,378.0,0,Transient,35.0,0,1
HB-024192,Resort Hotel,0,59,2024,May,19,8,2024-05-08,2,5,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,G,G,0,No Deposit,250.0,,0,Transient-Party,126.0,1,0
HB-030519,Resort Hotel,0,1,2024,November,48,26,2024-11-26,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient-Party,63.0,0,0
HB-078932,City Hotel,0,18,2023,October,42,16,2023-10-16,1,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,F,0,No Deposit,8.0,,0,Transient,129.33,1,1
HB-102496,City Hotel,0,1,2025,August,31,2,2025-08-02,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,5,D,D,0,No Deposit,,219.0,0,Transient,95.0,0,2
HB-052390,City Hotel,1,102,2024,June,23,5,2024-06-05,1,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,65.0,0,0
HB-042342,City Hotel,0,9,2023,September,36,5,2023-09-05,0,1,2,0.0,0,BB,PRT,Complementary,Direct,0,0,0,E,G,2,No Deposit,,,0,Transient,0.0,0,1
HB-032370,Resort Hotel,0,14,2025,January,4,22,2025-01-22,2,1,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,58.0,0,1
HB-022684,Resort Hotel,0,101,2024,March,13,29,2024-03-29,0,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,50.6,0,1
HB-075609,City Hotel,1,145,2023,July,27,4,2023-07-04,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,2
HB-016489,Resort Hotel,0,12,2023,August,34,24,2023-08-24,2,5,2,0.0,1,HB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,174.14,0,1
HB-028274,Resort Hotel,0,285,2024,September,38,20,2024-09-20,2,5,2,0.0,0,BB,IRL,Groups,TA/TO,0,0,0,A,A,1,No Deposit,96.0,,0,Transient-Party,64.0,0,1
HB-101214,City Hotel,0,5,2024,November,45,8,2024-11-08,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,224.0,1,3
HB-054660,City Hotel,1,205,2024,July,30,22,2024-07-22,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,90.95,0,0
HB-052707,City Hotel,1,87,2024,June,23,9,2024-06-09,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,97.71,0,0
HB-083275,City Hotel,0,12,2024,January,4,24,2024-01-24,2,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient-Party,66.0,0,1
HB-119328,City Hotel,0,186,2025,August,35,31,2025-08-31,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,126.0,0,2
HB-093604,City Hotel,0,226,2024,July,30,22,2024-07-22,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,96,Transient-Party,76.5,0,1
HB-056043,City Hotel,1,166,2024,August,35,27,2024-08-27,2,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.3,0,0
HB-083695,City Hotel,0,59,2024,February,6,6,2024-02-06,2,2,2,0.0,0,BB,AUT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-091445,City Hotel,0,79,2024,June,24,16,2024-06-16,2,4,2,0.0,0,SC,AUT,Online TA,TA/TO,0,0,0,A,B,1,No Deposit,9.0,,0,Transient,120.6,0,0
HB-106444,City Hotel,0,258,2025,February,9,25,2025-02-25,0,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,2
HB-101990,City Hotel,0,63,2024,November,46,17,2024-11-17,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,88.4,0,1
HB-021828,Resort Hotel,0,12,2024,March,10,9,2024-03-09,0,3,1,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,A,A,1,No Deposit,115.0,,0,Transient-Party,49.0,0,0
HB-075770,City Hotel,1,323,2023,September,36,5,2023-09-05,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-032159,Resort Hotel,0,40,2025,January,3,16,2025-01-16,1,2,1,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,55.0,0,0
HB-037589,Resort Hotel,0,282,2025,June,25,16,2025-06-16,2,5,2,1.0,0,BB,IRL,Direct,Direct,0,0,0,D,D,1,No Deposit,250.0,,0,Transient-Party,120.6,0,0
HB-091182,City Hotel,0,256,2024,June,24,15,2024-06-15,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,112.0,0,1
HB-040444,City Hotel,0,19,2023,July,30,25,2023-07-25,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-038713,Resort Hotel,0,23,2025,July,30,23,2025-07-23,2,2,2,1.0,0,HB,ESP,Direct,Direct,0,0,0,A,A,1,No Deposit,250.0,,0,Transient,258.0,0,0
HB-106853,City Hotel,0,0,2025,February,9,26,2025-02-26,2,4,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,91.8,0,0
HB-099635,City Hotel,0,335,2024,October,41,13,2024-10-13,0,3,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,80.0,0,0
HB-115283,City Hotel,0,168,2025,July,27,1,2025-07-01,2,1,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,153.9,0,1
HB-034125,Resort Hotel,0,110,2025,March,11,13,2025-03-13,1,0,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,1,No Deposit,66.0,,0,Transient-Party,32.0,0,0
HB-023194,Resort Hotel,0,153,2024,April,15,14,2024-04-14,0,3,3,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient-Party,123.0,0,2
HB-090786,City Hotel,0,107,2024,June,24,10,2024-06-10,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,187.0,,0,Transient-Party,130.0,0,1
HB-008870,Resort Hotel,1,95,2024,October,42,17,2024-10-17,1,4,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,58.0,0,1
HB-100323,City Hotel,0,109,2024,October,43,26,2024-10-26,0,1,1,0.0,0,SC,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.1,0,1
HB-074540,City Hotel,1,339,2023,September,38,21,2023-09-21,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-013822,Resort Hotel,0,7,2024,September,37,13,2024-09-13,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,2,A,E,0,No Deposit,94.0,,0,Transient,66.0,0,0
HB-107998,City Hotel,1,13,2025,May,22,29,2025-05-29,1,2,1,0.0,0,BB,SWE,Direct,Direct,1,1,1,A,A,0,No Deposit,,,0,Transient,95.0,0,0
HB-011742,Resort Hotel,1,51,2025,May,22,28,2025-05-28,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,314.0,,0,Transient,96.21,0,0
HB-013720,Resort Hotel,1,20,2025,August,35,27,2025-08-27,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,11.0,,0,Transient,182.0,0,1
HB-077646,City Hotel,0,0,2023,September,38,21,2023-09-21,1,2,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-042487,City Hotel,0,55,2023,September,36,6,2023-09-06,2,0,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,75.0,0,0
HB-101170,City Hotel,0,46,2024,November,45,6,2024-11-06,1,0,1,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.2,0,2
HB-083071,City Hotel,0,6,2024,January,3,16,2024-01-16,0,1,2,0.0,0,BB,BFA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.3,0,1
HB-057424,City Hotel,1,24,2024,September,39,26,2024-09-26,1,1,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,0
HB-101740,City Hotel,0,22,2024,November,46,15,2024-11-15,0,2,1,0.0,0,BB,LTU,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,77.0,0,0
HB-103261,City Hotel,0,39,2024,December,49,8,2024-12-08,2,8,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.9,0,2
HB-080773,City Hotel,1,180,2024,April,15,13,2024-04-13,0,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,21.0,,38,Transient,125.0,0,0
HB-055268,City Hotel,1,142,2024,August,32,9,2024-08-09,0,3,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.5,0,1
HB-109879,City Hotel,0,82,2025,April,16,16,2025-04-16,2,0,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,171.0,0,0
HB-081130,City Hotel,1,146,2024,March,13,30,2024-03-30,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,86.0,,28,Transient,80.0,0,0
HB-076724,City Hotel,0,6,2025,May,21,22,2025-05-22,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,6,64,A,A,1,No Deposit,,40.0,0,Transient,65.0,0,1
HB-037322,Resort Hotel,0,104,2025,June,24,12,2025-06-12,1,1,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,110.0,1,1
HB-080033,City Hotel,0,1,2024,January,2,8,2024-01-08,0,2,2,0.0,0,SC,BRA,Online TA,TA/TO,1,11,0,A,A,0,No Deposit,9.0,,0,Transient-Party,76.5,1,0
HB-104479,City Hotel,0,4,2025,January,3,14,2025-01-14,0,1,1,0.0,0,BB,AGO,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,80.0,0,0
HB-065056,City Hotel,1,270,2025,March,12,23,2025-03-23,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.0,0,3
HB-038821,Resort Hotel,0,46,2025,July,30,24,2025-07-24,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,135.0,0,0
HB-026987,Resort Hotel,0,16,2024,August,33,13,2024-08-13,2,1,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,293.0,0,1
HB-046267,City Hotel,0,118,2023,December,52,28,2023-12-28,1,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,110.8,0,2
HB-077407,City Hotel,0,19,2023,October,40,6,2023-10-06,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,1,0,0,A,A,0,No Deposit,82.0,,0,Transient-Party,90.0,0,0
HB-022289,Resort Hotel,0,36,2024,March,11,16,2024-03-16,2,5,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,69.0,,0,Transient-Party,30.6,0,1
HB-019088,Resort Hotel,0,1,2023,December,49,5,2023-12-05,2,1,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,5.0,,0,Transient,30.0,0,0
HB-075031,City Hotel,1,219,2023,September,36,4,2023-09-04,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,3.0,,0,Transient-Party,80.0,0,0
HB-040369,City Hotel,0,132,2023,July,29,23,2023-07-23,0,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,90.0,0,0
HB-001241,Resort Hotel,0,40,2023,August,33,20,2023-08-20,2,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,176.8,1,1
HB-007367,Resort Hotel,1,149,2024,August,32,5,2024-08-05,2,7,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,188.89,0,0
HB-071460,City Hotel,1,179,2025,July,27,6,2025-07-06,0,1,2,2.0,0,HB,ITA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,233.1,0,0
HB-054754,City Hotel,1,99,2024,July,30,25,2024-07-25,1,3,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.5,0,0
HB-055910,City Hotel,1,107,2024,August,34,24,2024-08-24,0,4,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,152.1,0,0
HB-105840,City Hotel,0,10,2025,February,7,12,2025-02-12,2,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,91.8,0,0
HB-119282,City Hotel,0,158,2025,August,35,31,2025-08-31,0,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,83.0,,0,Transient,126.0,1,0
HB-108028,City Hotel,0,49,2025,March,12,18,2025-03-18,2,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,168.0,,0,Transient-Party,72.0,0,0
HB-050754,City Hotel,1,39,2024,May,19,7,2024-05-07,0,1,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.9,0,0
HB-025004,Resort Hotel,0,159,2024,June,23,5,2024-06-05,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,81.85,0,0
HB-030970,Resort Hotel,0,22,2024,December,49,8,2024-12-08,0,3,2,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,38.0,,0,Transient-Party,80.0,0,0
HB-028030,Resort Hotel,0,327,2024,September,37,14,2024-09-14,0,4,2,0.0,0,BB,IRL,Groups,TA/TO,0,0,0,A,C,0,No Deposit,201.0,,0,Transient-Party,61.4,0,0
HB-018706,Resort Hotel,1,17,2023,December,50,11,2023-12-11,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,D,D,0,No Deposit,15.0,,0,Transient,37.0,0,1
HB-032089,Resort Hotel,0,5,2025,January,3,15,2025-01-15,1,0,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,68.0,0,1
HB-105774,City Hotel,0,20,2025,February,7,13,2025-02-13,1,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,108.0,0,0
HB-105375,City Hotel,0,26,2025,February,6,4,2025-02-04,1,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,148.0,0,0
HB-110232,City Hotel,0,165,2025,April,17,22,2025-04-22,1,1,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,166.5,0,2
HB-025064,Resort Hotel,0,96,2024,June,23,6,2024-06-06,2,5,2,0.0,0,FB,PRT,Offline TA/TO,TA/TO,0,0,0,E,G,2,No Deposit,171.0,,0,Transient,135.1,0,1
HB-118998,City Hotel,0,161,2025,August,34,21,2025-08-21,2,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.5,0,1
HB-029408,Resort Hotel,0,121,2024,October,43,25,2024-10-25,0,3,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,4,No Deposit,250.0,,0,Transient,95.53,0,2
HB-064286,City Hotel,1,45,2025,March,10,4,2025-03-04,1,1,1,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,0
HB-013582,Resort Hotel,1,106,2025,August,34,20,2025-08-20,4,9,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,234.62,0,1
HB-013691,Resort Hotel,1,184,2025,August,35,26,2025-08-26,2,5,2,0.0,0,FB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,173.0,0,0
HB-100544,City Hotel,0,35,2024,October,43,25,2024-10-25,0,4,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,149.0,0,2
HB-046254,City Hotel,0,12,2023,December,52,28,2023-12-28,1,0,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.0,0,0
HB-060651,City Hotel,1,11,2024,November,46,17,2024-11-17,2,3,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.05,0,0
HB-081387,City Hotel,1,18,2024,September,39,27,2024-09-27,0,1,1,0.0,0,BB,FRA,Corporate,Corporate,1,1,5,A,A,0,No Deposit,,91.0,0,Transient,95.0,0,0
HB-089377,City Hotel,0,0,2024,May,21,20,2024-05-20,0,1,1,0.0,0,SC,ITA,Direct,Direct,0,0,0,A,B,1,No Deposit,,,0,Transient-Party,149.0,0,0
HB-055388,City Hotel,1,221,2024,August,33,12,2024-08-12,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,147,Transient-Party,80.0,0,0
HB-088534,City Hotel,0,1,2024,May,19,6,2024-05-06,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,158.0,1,0
HB-060755,City Hotel,1,95,2024,November,47,20,2024-11-20,2,0,1,0.0,0,BB,HUN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.0,0,2
HB-087974,City Hotel,0,13,2024,April,17,26,2024-04-26,0,3,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,58.0,,0,Transient-Party,96.0,0,0
HB-073748,City Hotel,1,265,2023,July,27,9,2023-07-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-037822,Resort Hotel,0,251,2025,June,26,26,2025-06-26,1,3,2,0.0,0,HB,CN,Groups,TA/TO,0,0,0,D,F,4,No Deposit,96.0,,0,Transient-Party,108.0,0,0
HB-069294,City Hotel,1,37,2025,May,22,29,2025-05-29,1,2,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,270.0,0,0
HB-096087,City Hotel,0,167,2024,August,35,26,2024-08-26,1,2,1,0.0,0,BB,SVK,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.3,0,0
HB-022756,Resort Hotel,0,3,2024,April,14,4,2024-04-04,1,0,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,62.0,1,1
HB-053005,City Hotel,1,188,2024,June,24,15,2024-06-15,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,39,Transient,130.0,0,0
HB-056366,City Hotel,1,64,2024,September,36,4,2024-09-04,1,0,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,3,No Deposit,9.0,,0,Transient,143.5,0,1
HB-013396,Resort Hotel,1,300,2025,August,33,13,2025-08-13,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,241.0,,0,Transient,219.6,0,0
HB-005265,Resort Hotel,1,36,2024,April,17,23,2024-04-23,2,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,85.33,0,0
HB-005578,Resort Hotel,0,203,2024,May,18,2,2024-05-02,1,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,3,No Deposit,240.0,,0,Transient,46.98,0,1
HB-092574,City Hotel,0,109,2024,July,27,4,2024-07-04,1,4,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,97.75,0,0
HB-020749,Resort Hotel,0,6,2024,February,6,5,2024-02-05,2,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,250.0,,0,Transient,45.0,0,0
HB-054709,City Hotel,1,134,2024,July,30,24,2024-07-24,2,0,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,177.3,0,0
HB-033876,Resort Hotel,0,7,2025,March,9,2,2025-03-02,1,3,1,0.0,0,BB,BEL,Groups,Corporate,0,0,0,A,C,1,No Deposit,,223.0,0,Transient-Party,29.0,0,0
HB-093020,City Hotel,0,78,2024,July,28,12,2024-07-12,0,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.3,1,2
HB-099802,City Hotel,0,277,2024,October,42,16,2024-10-16,2,0,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.3,0,0
HB-068372,City Hotel,1,394,2025,May,20,16,2025-05-16,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-088963,City Hotel,0,24,2024,May,19,11,2024-05-11,0,4,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.0,0,0
HB-106724,City Hotel,0,270,2025,February,9,27,2025-02-27,1,2,3,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,75.71,0,1
HB-092497,City Hotel,0,43,2024,July,27,3,2024-07-03,2,2,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,150.3,0,2
HB-092491,City Hotel,0,82,2024,July,27,1,2024-07-01,2,4,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,146.7,0,2
HB-025815,Resort Hotel,0,317,2024,July,27,6,2024-07-06,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,240.0,,0,Transient,102.71,0,3
HB-099430,City Hotel,0,181,2024,October,41,11,2024-10-11,0,2,1,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,234.0,,0,Transient-Party,120.0,0,0
HB-063449,City Hotel,1,67,2025,February,7,12,2025-02-12,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,80.0,0,0
HB-024803,Resort Hotel,0,4,2024,June,23,4,2024-06-04,0,1,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient,81.0,1,0
HB-098273,City Hotel,0,6,2024,September,39,26,2024-09-26,1,0,3,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,133.0,0,1
HB-017017,Resort Hotel,0,239,2023,September,38,19,2023-09-19,1,1,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,248.0,,0,Transient-Party,0.0,0,0
HB-101510,City Hotel,0,42,2024,November,45,9,2024-11-09,0,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,133.03,0,1
HB-071718,City Hotel,1,146,2025,July,28,11,2025-07-11,0,1,2,1.0,0,BB,LUX,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.1,0,0
HB-095669,City Hotel,0,78,2024,August,34,19,2024-08-19,1,2,0,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient,115.68,0,1
HB-004015,Resort Hotel,1,140,2024,February,7,12,2024-02-12,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,50.0,0,0
HB-005353,Resort Hotel,1,189,2024,April,17,26,2024-04-26,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,248.0,,0,Transient-Party,46.0,0,0
HB-085891,City Hotel,0,48,2024,March,12,20,2024-03-20,2,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,93.5,0,2
HB-119135,City Hotel,0,19,2025,August,35,29,2025-08-29,0,1,1,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,140.0,0,2
HB-115621,City Hotel,0,193,2025,July,28,7,2025-07-07,0,2,2,1.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,9.0,,0,Transient,114.1,0,2
HB-034290,Resort Hotel,0,125,2025,March,12,17,2025-03-17,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,75.0,0,1
HB-084740,City Hotel,0,115,2024,February,9,27,2024-02-27,2,3,1,0.0,0,BB,MOZ,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,134.0,,0,Transient-Party,76.0,0,0
HB-119337,City Hotel,0,103,2025,August,35,29,2025-08-29,0,5,1,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,153.6,0,0
HB-099042,City Hotel,0,190,2024,September,40,30,2024-09-30,2,7,2,0.0,0,BB,ISL,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,110.9,0,0
HB-089080,City Hotel,0,10,2024,May,20,16,2024-05-16,1,0,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,103.0,0,0
HB-037959,Resort Hotel,0,220,2025,June,26,28,2025-06-28,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient-Party,81.2,0,1
HB-112347,City Hotel,0,75,2025,May,21,20,2025-05-20,2,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,229.0,,0,Transient-Party,0.0,0,0
HB-018541,Resort Hotel,0,289,2023,November,47,20,2023-11-20,1,2,2,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,57.0,0,0
HB-045795,City Hotel,1,98,2023,November,47,23,2023-11-23,1,2,1,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,84.0,0,0
HB-070670,City Hotel,1,19,2025,June,25,20,2025-06-20,0,4,2,2.0,0,BB,USA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,250.0,0,1
HB-024218,Resort Hotel,0,236,2024,May,19,12,2024-05-12,0,3,1,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,1,No Deposit,315.0,,0,Transient-Party,48.0,1,0
HB-102275,City Hotel,0,16,2024,November,47,20,2024-11-20,2,4,1,0.0,0,BB,CHN,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,360.0,0,Transient,79.75,0,0
HB-049138,City Hotel,1,55,2024,April,14,6,2024-04-06,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,155.0,,0,Transient,118.33,0,1
HB-038595,Resort Hotel,0,9,2025,July,30,21,2025-07-21,0,2,2,2.0,0,BB,ESP,Direct,Direct,0,0,0,C,C,0,No Deposit,250.0,,0,Transient,256.5,1,0
HB-099446,City Hotel,0,36,2024,October,41,13,2024-10-13,0,1,1,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient-Party,102.6,0,2
HB-114601,City Hotel,0,221,2025,June,26,23,2025-06-23,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,89.1,0,2
HB-085245,City Hotel,0,6,2024,March,10,9,2024-03-09,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,90.0,0,0
HB-086166,City Hotel,0,48,2024,March,13,28,2024-03-28,1,0,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.1,0,0
HB-003268,Resort Hotel,1,133,2023,November,48,30,2023-11-30,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,29.16,0,1
HB-083595,City Hotel,0,2,2024,February,6,5,2024-02-05,1,2,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,57.98,0,1
HB-020480,Resort Hotel,0,1,2024,January,5,29,2024-01-29,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,45.0,1,1
HB-086372,City Hotel,0,41,2024,March,13,28,2024-03-28,1,4,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,114.04,0,0
HB-035435,Resort Hotel,0,58,2025,April,16,16,2025-04-16,2,5,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,C,0,No Deposit,493.0,,0,Contract,82.0,0,1
HB-015208,Resort Hotel,1,267,2023,September,39,26,2023-09-26,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,96.0,,0,Transient,54.99,0,0
HB-033307,Resort Hotel,0,16,2025,February,8,17,2025-02-17,1,2,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,498.0,0,Transient-Party,40.0,0,0
HB-081110,City Hotel,1,82,2024,February,5,2,2024-02-02,0,5,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,21,Transient,96.0,0,0
HB-111081,City Hotel,0,21,2025,May,18,3,2025-05-03,0,3,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,354.0,,0,Transient,146.78,0,0
HB-016803,Resort Hotel,0,178,2023,September,37,12,2023-09-12,0,1,1,0.0,0,BB,SWE,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,251.0,,0,Transient,54.9,0,0
HB-097997,City Hotel,0,3,2024,September,38,22,2024-09-22,0,1,1,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,161.7,0,1
HB-117687,City Hotel,0,63,2025,August,31,1,2025-08-01,2,5,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.0,0,2
HB-009914,Resort Hotel,1,44,2025,January,4,22,2025-01-22,2,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,42.0,0,0
HB-006937,Resort Hotel,1,244,2024,July,28,12,2024-07-12,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,92.57,0,1
HB-111308,City Hotel,0,56,2025,May,18,4,2025-05-04,2,3,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,100.8,0,0
HB-025053,Resort Hotel,0,59,2024,June,24,10,2024-06-10,0,2,3,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,3,No Deposit,250.0,,0,Transient,171.0,1,1
HB-082199,City Hotel,0,3,2023,December,51,21,2023-12-21,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,B,B,0,No Deposit,168.0,,0,Transient-Party,37.5,0,1
HB-007399,Resort Hotel,1,148,2024,August,32,7,2024-08-07,2,4,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,269.0,0,0
HB-040826,City Hotel,0,1,2023,August,32,8,2023-08-08,1,1,2,0.0,1,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,14.0,,0,Transient,75.0,0,1
HB-005915,Resort Hotel,0,213,2024,May,20,16,2024-05-16,1,1,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,85.0,0,0
HB-043144,City Hotel,0,26,2023,September,37,15,2023-09-15,2,6,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,27.0,,0,Transient,56.25,0,1
HB-038470,Resort Hotel,0,80,2025,July,29,17,2025-07-17,1,1,2,0.0,0,HB,BRA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,241.0,,0,Transient,203.6,0,2
HB-112271,City Hotel,0,2,2025,May,21,21,2025-05-21,1,0,1,0.0,0,BB,BRA,Corporate,Corporate,0,0,0,D,D,0,No Deposit,,150.0,0,Transient,110.0,0,0
HB-034705,Resort Hotel,0,0,2025,April,14,1,2025-04-01,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,87.0,0,0
HB-036162,Resort Hotel,0,2,2025,May,19,11,2025-05-11,0,1,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,85.0,0,2
HB-072256,City Hotel,1,344,2025,July,30,24,2025-07-24,1,5,2,0.0,0,SC,HUN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,1
HB-098396,City Hotel,0,0,2024,September,39,28,2024-09-28,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient,185.0,0,2
HB-000479,Resort Hotel,0,53,2023,July,29,17,2023-07-17,2,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,152.0,,0,Transient-Party,107.0,0,0
HB-067464,City Hotel,1,24,2025,May,18,4,2025-05-04,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,179.0,0,0
HB-049562,City Hotel,1,122,2024,April,16,15,2024-04-15,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,151.0,,56,Transient-Party,85.0,0,0
HB-007889,Resort Hotel,1,249,2024,September,35,1,2024-09-01,2,4,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,81.0,0,0
HB-107295,City Hotel,0,0,2025,March,11,10,2025-03-10,0,1,2,0.0,0,FB,PRT,Complementary,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,0.0,0,1
HB-004870,Resort Hotel,1,27,2024,April,14,4,2024-04-04,1,5,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,125.0,0,0
HB-073259,City Hotel,1,171,2025,August,33,17,2025-08-17,1,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.5,0,0
HB-097614,City Hotel,0,3,2024,September,37,15,2024-09-15,0,3,2,0.0,0,SC,AGO,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,161.33,1,2
HB-018484,Resort Hotel,0,0,2024,February,5,1,2024-02-01,1,1,1,0.0,0,HB,PRT,Corporate,Corporate,1,0,2,A,A,0,No Deposit,,20.0,0,Transient,46.0,0,0
HB-109571,City Hotel,0,93,2025,April,15,11,2025-04-11,0,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,1
HB-114644,City Hotel,0,186,2025,June,25,22,2025-06-22,0,3,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,166.5,0,2
HB-003483,Resort Hotel,1,93,2023,December,51,19,2023-12-19,0,1,2,0.0,0,FB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,80.0,0,0
HB-080220,City Hotel,0,0,2023,November,45,12,2023-11-12,0,2,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.0,0,0
HB-020583,Resort Hotel,0,0,2024,February,5,3,2024-02-03,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,,0,Transient,39.0,0,0
HB-111767,City Hotel,0,95,2025,May,20,12,2025-05-12,1,2,1,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,147.0,0,1
HB-008752,Resort Hotel,0,364,2024,October,41,12,2024-10-12,0,4,1,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,1,No Deposit,,223.0,0,Transient-Party,60.0,0,0
HB-041252,City Hotel,0,39,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-012652,Resort Hotel,1,125,2025,July,28,10,2025-07-10,1,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,148.5,0,0
HB-086589,City Hotel,0,73,2024,April,14,3,2024-04-03,2,1,1,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient-Party,76.5,0,1
HB-070369,City Hotel,1,164,2025,June,24,15,2025-06-15,2,5,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,134.36,0,0
HB-032600,Resort Hotel,0,1,2025,January,5,27,2025-01-27,1,2,2,1.0,1,BB,IRL,Direct,Direct,0,0,0,H,H,1,No Deposit,250.0,,0,Transient-Party,95.33,0,4
HB-117396,City Hotel,0,142,2025,July,31,31,2025-07-31,1,2,2,1.0,0,BB,USA,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,164.0,0,1
HB-015078,Resort Hotel,1,135,2023,July,27,8,2023-07-08,1,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,240.0,,0,Transient,123.0,0,0
HB-004914,Resort Hotel,1,15,2024,April,15,8,2024-04-08,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,71.0,0,0
HB-000305,Resort Hotel,0,32,2023,July,28,11,2023-07-11,4,6,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,178.0,1,0
HB-021308,Resort Hotel,0,0,2024,February,8,25,2024-02-25,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,40.0,1,0
HB-071315,City Hotel,1,219,2025,July,27,2,2025-07-02,2,0,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.39,0,0
HB-048639,City Hotel,1,43,2024,March,13,25,2024-03-25,4,10,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,170.61,0,0
HB-068941,City Hotel,1,141,2025,May,21,23,2025-05-23,0,2,4,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,8.0,,0,Transient,295.0,0,2
HB-021050,Resort Hotel,0,0,2024,March,9,1,2024-03-01,0,1,2,0.0,0,BB,PRT,Direct,TA/TO,1,0,1,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,0
HB-093286,City Hotel,0,152,2024,July,28,13,2024-07-13,2,5,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,130.05,0,2
HB-009205,Resort Hotel,1,37,2024,November,44,2,2024-11-02,1,4,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,37.8,0,1
HB-099663,City Hotel,0,335,2024,October,41,13,2024-10-13,0,3,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,80.0,0,0
HB-080393,City Hotel,1,34,2023,December,49,8,2023-12-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,0,Transient,90.0,0,0
HB-049919,City Hotel,1,265,2024,April,16,20,2024-04-20,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,30.0,,0,Transient,101.0,0,0
HB-000193,Resort Hotel,0,65,2023,July,27,6,2023-07-06,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,127.0,,0,Transient,83.5,0,0
HB-074493,City Hotel,1,318,2023,August,35,31,2023-08-31,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-044174,City Hotel,1,164,2023,October,40,2,2023-10-02,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,19.0,,0,Transient-Party,100.0,0,0
HB-062977,City Hotel,1,78,2025,January,4,25,2025-01-25,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,365.0,0,Transient-Party,85.0,0,0
HB-052302,City Hotel,0,149,2024,June,23,3,2024-06-03,0,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,124.2,1,0
HB-068028,City Hotel,1,183,2025,May,19,11,2025-05-11,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,0,Transient,130.0,0,0
HB-110795,City Hotel,0,112,2025,April,18,28,2025-04-28,2,2,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,123.75,0,1
HB-056007,City Hotel,1,77,2024,August,35,26,2024-08-26,2,2,2,1.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,147.6,0,0
HB-109578,City Hotel,0,98,2025,April,15,10,2025-04-10,1,3,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,159.38,0,1
HB-001712,Resort Hotel,1,147,2023,September,36,10,2023-09-10,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,142.0,,0,Contract,70.48,0,0
HB-031203,Resort Hotel,0,25,2024,December,51,16,2024-12-16,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,54.0,1,2
HB-010600,Resort Hotel,1,26,2025,March,12,18,2025-03-18,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,68.0,0,0
HB-088987,City Hotel,0,38,2024,May,20,13,2024-05-13,1,2,0,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient,127.39,0,0
HB-053759,City Hotel,1,20,2024,June,26,29,2024-06-29,0,3,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,177.0,0,0
HB-078529,City Hotel,0,11,2023,October,41,9,2023-10-09,1,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,139.33,0,1
HB-057177,City Hotel,1,125,2024,September,38,20,2024-09-20,1,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,143.1,0,0
HB-052815,City Hotel,1,69,2024,June,24,12,2024-06-12,2,4,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,120.0,0,0
HB-008227,Resort Hotel,1,38,2024,September,38,19,2024-09-19,1,1,2,0.0,0,BB,LUX,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,92.0,0,2
HB-074290,City Hotel,1,309,2023,August,34,22,2023-08-22,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-001643,Resort Hotel,0,144,2023,September,36,6,2023-09-06,4,10,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,83.15,0,1
HB-115411,City Hotel,0,405,2025,July,27,4,2025-07-04,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,114.4,0,0
HB-108556,City Hotel,0,142,2025,March,13,25,2025-03-25,2,2,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,136.8,0,0
HB-084243,City Hotel,0,27,2024,February,7,18,2024-02-18,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.0,0,1
HB-065658,City Hotel,1,62,2025,April,14,6,2025-04-06,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,135.0,0,0
HB-084695,City Hotel,0,115,2024,February,9,27,2024-02-27,2,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,134.0,,0,Transient-Party,76.0,0,0
HB-066605,City Hotel,1,284,2025,April,17,22,2025-04-22,2,1,1,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,104.4,0,0
HB-101734,City Hotel,0,22,2024,November,46,14,2024-11-14,1,2,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,7.0,,0,Transient,64.37,0,1
HB-061526,City Hotel,1,28,2024,December,50,15,2024-12-15,2,3,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,74.8,0,1
HB-036931,Resort Hotel,0,1,2025,June,22,1,2025-06-01,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,82.0,1,1
HB-014998,Resort Hotel,1,244,2023,September,35,3,2023-09-03,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,19,0,A,A,0,Non Refund,,,0,Transient,36.0,0,0
HB-024265,Resort Hotel,0,9,2024,May,20,15,2024-05-15,1,0,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,Refundable,,,0,Group,70.0,0,0
HB-095266,City Hotel,0,14,2024,August,33,15,2024-08-15,1,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,151.0,0,1
HB-067107,City Hotel,1,272,2025,April,18,28,2025-04-28,1,2,2,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,144.0,0,0
HB-001022,Resort Hotel,1,77,2023,August,32,10,2023-08-10,1,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,134.0,0,0
HB-012937,Resort Hotel,1,181,2025,July,30,24,2025-07-24,1,4,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,206.0,0,0
HB-059480,City Hotel,1,247,2024,October,44,28,2024-10-28,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,110.0,0,0
HB-112984,City Hotel,0,53,2025,May,22,31,2025-05-31,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,28.0,,0,Transient,84.6,0,0
HB-103578,City Hotel,0,25,2024,December,52,27,2024-12-27,0,1,2,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,220.0,,0,Transient-Party,65.0,0,0
HB-078272,City Hotel,1,14,2023,October,41,15,2023-10-15,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,99.0,,0,Transient-Party,100.0,0,0
HB-013000,Resort Hotel,1,340,2025,July,30,27,2025-07-27,0,3,2,2.0,0,BB,FRA,Direct,Direct,0,0,0,G,G,0,No Deposit,250.0,,0,Transient,192.6,0,0
HB-117013,City Hotel,0,171,2025,July,30,26,2025-07-26,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,132.5,0,1
HB-051218,City Hotel,1,451,2024,May,20,16,2024-05-16,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-042062,City Hotel,1,104,2023,August,35,30,2023-08-30,2,1,2,0.0,0,HB,ESP,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,90.0,0,0
HB-116992,City Hotel,0,84,2025,July,30,24,2025-07-24,1,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,1
HB-066494,City Hotel,1,130,2025,April,17,21,2025-04-21,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,286.0,,0,Transient,95.0,0,0
HB-099943,City Hotel,0,8,2024,October,42,19,2024-10-19,0,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,123.2,0,0
HB-064506,City Hotel,1,45,2025,March,11,11,2025-03-11,1,1,2,2.0,0,BB,USA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,198.0,0,0
HB-093334,City Hotel,0,187,2024,July,29,15,2024-07-15,2,4,2,2.0,0,BB,SWE,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,149.85,0,1
HB-107360,City Hotel,0,48,2025,March,11,10,2025-03-10,0,2,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,97.2,0,0
HB-003632,Resort Hotel,1,49,2023,December,52,28,2023-12-28,1,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,39.0,0,2
HB-083421,City Hotel,0,1,2024,January,5,30,2024-01-30,1,1,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,101.0,0,1
HB-054167,City Hotel,1,147,2024,July,27,7,2024-07-07,1,3,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,138.55,0,1
HB-008225,Resort Hotel,0,375,2024,September,38,18,2024-09-18,4,9,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,1,No Deposit,40.0,,0,Contract,58.95,0,1
HB-003364,Resort Hotel,0,45,2023,December,49,5,2023-12-05,2,1,2,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,38.0,,0,Transient-Party,68.0,0,0
HB-058690,City Hotel,1,162,2024,October,42,14,2024-10-14,2,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,34.0,,0,Transient,115.0,0,0
HB-039717,Resort Hotel,0,122,2025,August,34,19,2025-08-19,2,5,3,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,4,No Deposit,181.0,,0,Transient-Party,253.8,0,0
HB-004594,Resort Hotel,0,162,2024,March,12,24,2024-03-24,0,3,2,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,84.0,0,0
HB-026290,Resort Hotel,0,67,2024,July,30,26,2024-07-26,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,195.0,0,0
HB-062523,City Hotel,1,38,2025,January,3,14,2025-01-14,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,Non Refund,,67.0,0,Transient,75.0,0,0
HB-027494,Resort Hotel,0,40,2024,August,35,31,2024-08-31,0,0,3,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,241.0,,0,Transient,0.0,0,1
HB-074077,City Hotel,1,321,2023,September,35,3,2023-09-03,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-011690,Resort Hotel,1,162,2025,May,21,25,2025-05-25,2,5,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,C,C,0,Refundable,,223.0,0,Transient-Party,8.0,0,0
HB-089104,City Hotel,0,0,2024,May,20,17,2024-05-17,0,0,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,1,0,0,A,A,0,No Deposit,6.0,,0,Transient,0.0,0,0
HB-117878,City Hotel,0,148,2025,August,31,3,2025-08-03,2,7,3,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,175.5,0,0
HB-016241,Resort Hotel,0,190,2023,August,33,14,2023-08-14,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,120.6,0,0
HB-014721,Resort Hotel,1,259,2023,September,37,17,2023-09-17,0,3,2,0.0,0,BB,GBR,Groups,Corporate,0,1,0,A,A,0,Non Refund,,223.0,0,Transient,40.05,0,0
HB-007402,Resort Hotel,1,91,2024,August,32,7,2024-08-07,2,5,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,4,No Deposit,240.0,,0,Transient,236.71,0,0
HB-024682,Resort Hotel,0,224,2024,May,21,25,2024-05-25,1,4,2,1.0,0,BB,GBR,Groups,Direct,0,0,0,A,C,2,No Deposit,,223.0,0,Transient-Party,91.1,1,0
HB-109644,City Hotel,0,5,2025,April,15,13,2025-04-13,0,2,2,1.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,204.0,0,2
HB-036754,Resort Hotel,0,3,2025,May,22,28,2025-05-28,1,0,2,0.0,0,BB,GBR,Direct,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient,85.0,0,0
HB-110741,City Hotel,0,106,2025,April,17,26,2025-04-26,1,4,1,0.0,0,BB,NOR,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,100.8,0,0
HB-069906,City Hotel,1,183,2025,June,23,8,2025-06-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,86.0,,0,Transient,120.0,0,0
HB-040723,City Hotel,0,12,2023,August,31,5,2023-08-05,0,3,1,0.0,0,BB,RUS,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,38.0,0,Transient-Party,60.0,0,0
HB-106105,City Hotel,0,2,2025,February,8,17,2025-02-17,2,2,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,9.0,,0,Transient,79.48,0,1
HB-040594,City Hotel,0,94,2023,August,31,1,2023-08-01,2,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,76.5,0,0
HB-019803,Resort Hotel,0,100,2023,December,51,23,2023-12-23,3,9,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,108.26,1,1
HB-113649,City Hotel,0,24,2025,June,23,6,2025-06-06,0,4,2,0.0,0,SC,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,89.0,0,0
HB-065773,City Hotel,1,117,2025,April,15,8,2025-04-08,2,1,1,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.8,0,1
HB-092993,City Hotel,0,98,2024,July,28,11,2024-07-11,1,3,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,9.0,,0,Transient,141.75,0,0
HB-091041,City Hotel,0,137,2024,June,24,13,2024-06-13,1,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,101.53,0,2
HB-064741,City Hotel,1,92,2025,March,11,15,2025-03-15,0,3,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,85.0,0,0
HB-097623,City Hotel,0,64,2024,September,37,14,2024-09-14,1,4,1,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,157.0,,0,Transient,92.48,0,0
HB-098486,City Hotel,0,26,2024,September,39,25,2024-09-25,2,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,84.14,0,1
HB-047158,City Hotel,1,21,2024,February,6,11,2024-02-11,0,1,1,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.0,0,0
HB-090102,City Hotel,0,22,2024,May,22,31,2024-05-31,0,2,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.0,0,1
HB-075045,City Hotel,1,264,2023,July,27,8,2023-07-08,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-101268,City Hotel,0,70,2024,November,45,4,2024-11-04,2,4,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.15,0,2
HB-071076,City Hotel,1,26,2025,June,26,28,2025-06-28,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,280.0,0,Transient-Party,100.0,0,0
HB-063279,City Hotel,1,25,2025,February,6,4,2025-02-04,2,5,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,0
HB-117646,City Hotel,0,259,2025,August,32,4,2025-08-04,1,2,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,1
HB-003906,Resort Hotel,1,72,2024,February,6,6,2024-02-06,2,1,2,0.0,0,HB,PRT,Groups,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,73.33,0,0
HB-086505,City Hotel,0,29,2024,April,14,1,2024-04-01,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,128.6,0,1
HB-026196,Resort Hotel,0,139,2024,July,28,14,2024-07-14,2,8,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,104.55,0,0
HB-008180,Resort Hotel,1,51,2024,September,37,15,2024-09-15,1,3,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,189.25,0,1
HB-004596,Resort Hotel,0,162,2024,March,12,24,2024-03-24,0,3,2,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,84.0,0,0
HB-019864,Resort Hotel,0,5,2024,January,1,2,2024-01-02,2,2,2,0.0,0,BB,BRA,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,73.25,0,0
HB-035951,Resort Hotel,0,175,2025,April,18,29,2025-04-29,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,42.66,0,0
HB-043952,City Hotel,1,88,2023,September,39,26,2023-09-26,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-015301,Resort Hotel,0,116,2023,July,27,3,2023-07-03,0,2,3,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,201.0,1,1
HB-044182,City Hotel,0,164,2023,October,40,2,2023-10-02,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,19.0,,0,Transient-Party,100.0,0,0
HB-016123,Resort Hotel,0,90,2023,August,32,11,2023-08-11,0,5,2,1.0,0,HB,ESP,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,241.0,,0,Transient,179.63,1,2
HB-046687,City Hotel,1,43,2024,January,3,15,2024-01-15,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,60.29,0,0
HB-082198,City Hotel,0,0,2023,December,51,20,2023-12-20,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,58.0,0,0
HB-007288,Resort Hotel,1,180,2024,August,31,1,2024-08-01,2,5,2,0.0,0,Undefined,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,196.0,,0,Transient-Party,165.0,0,1
HB-048060,City Hotel,1,41,2024,March,11,15,2024-03-15,0,1,1,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,0
HB-060948,City Hotel,1,34,2024,November,48,27,2024-11-27,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,75.0,0,0
HB-100220,City Hotel,0,386,2024,October,43,23,2024-10-23,2,0,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-077137,City Hotel,0,18,2024,December,50,11,2024-12-11,2,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,3,A,A,0,No Deposit,,40.0,0,Transient,67.0,1,0
HB-026384,Resort Hotel,0,153,2024,July,30,24,2024-07-24,2,4,3,0.0,0,BB,CHE,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,36.0,,0,Transient,105.47,0,1
HB-018800,Resort Hotel,0,0,2025,February,7,10,2025-02-10,0,2,2,0.0,0,BB,PRT,Direct,Direct,1,0,4,A,A,0,No Deposit,,,0,Transient,48.0,0,0
HB-081571,City Hotel,1,192,2024,May,19,12,2024-05-12,0,3,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,39.0,,42,Transient,135.0,0,0
HB-090992,City Hotel,0,32,2024,June,24,12,2024-06-12,2,1,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,65.14,0,1
HB-095595,City Hotel,0,69,2024,August,33,15,2024-08-15,1,5,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.9,0,1
HB-101418,City Hotel,0,92,2024,November,46,11,2024-11-11,0,1,2,0.0,0,BB,THA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,364.0,,0,Transient-Party,90.0,0,0
HB-087389,City Hotel,0,158,2024,April,16,16,2024-04-16,2,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,7.0,,0,Transient,69.92,0,1
HB-060812,City Hotel,1,62,2024,November,47,22,2024-11-22,0,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.6,0,2
HB-064641,City Hotel,1,97,2025,March,11,14,2025-03-14,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,0,Transient,85.0,0,0
HB-078391,City Hotel,0,0,2023,November,46,18,2023-11-18,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,3,A,A,1,No Deposit,,40.0,0,Transient,65.0,0,0
HB-072966,City Hotel,1,109,2025,August,32,10,2025-08-10,2,4,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.0,0,1
HB-085761,City Hotel,0,0,2024,March,12,20,2024-03-20,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,129.0,0,0
HB-084878,City Hotel,0,0,2024,March,10,4,2024-03-04,0,1,2,0.0,0,SC,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,89.0,0,0
HB-004037,Resort Hotel,1,112,2024,February,7,12,2024-02-12,0,2,2,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,68.0,0,0
HB-073657,City Hotel,1,210,2025,August,35,29,2025-08-29,0,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,0
HB-084340,City Hotel,0,75,2024,February,8,20,2024-02-20,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,60.0,0,0
HB-040886,City Hotel,0,16,2023,August,32,8,2023-08-08,2,2,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,B,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-098387,City Hotel,0,336,2024,September,38,21,2024-09-21,2,6,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,21.0,,0,Transient-Party,81.88,0,0
HB-073775,City Hotel,1,279,2023,July,29,23,2023-07-23,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-090301,City Hotel,0,52,2024,May,22,31,2024-05-31,0,5,1,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,140.4,0,0
HB-076989,City Hotel,0,1,2023,August,33,20,2023-08-20,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,113.6,0,2
HB-026169,Resort Hotel,0,51,2024,July,29,17,2024-07-17,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,261.0,,0,Transient,138.6,0,0
HB-058911,City Hotel,1,605,2024,October,42,17,2024-10-17,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-034089,Resort Hotel,0,13,2025,March,11,10,2025-03-10,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,68.0,0,1
HB-002265,Resort Hotel,0,10,2023,October,40,8,2023-10-08,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,240.0,,0,Transient,73.66,0,2
HB-104430,City Hotel,0,65,2025,January,2,12,2025-01-12,0,2,1,0.0,0,BB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,366.0,0,Transient-Party,65.0,0,0
HB-096139,City Hotel,0,4,2024,August,35,28,2024-08-28,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,139.0,0,1
HB-037810,Resort Hotel,0,335,2025,June,26,26,2025-06-26,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,74.25,0,2
HB-113812,City Hotel,0,226,2025,June,24,9,2025-06-09,1,2,3,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,8.0,,0,Transient,242.5,0,1
HB-085797,City Hotel,0,68,2024,March,12,19,2024-03-19,2,1,2,0.0,0,BB,KAZ,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,105.3,0,2
HB-067595,City Hotel,1,83,2025,May,19,5,2025-05-05,0,2,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,135.0,0,0
HB-055521,City Hotel,1,0,2024,August,33,15,2024-08-15,1,2,3,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,101.0,0,0
HB-039750,Resort Hotel,0,23,2025,August,35,25,2025-08-25,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,240.0,0,2
HB-099380,City Hotel,0,181,2024,October,41,11,2024-10-11,0,2,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,234.0,,0,Transient-Party,120.0,0,0
HB-062213,City Hotel,1,545,2025,January,1,5,2025-01-05,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,59.0,0,0
HB-081659,City Hotel,0,47,2023,December,50,16,2023-12-16,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-028881,Resort Hotel,0,252,2024,October,41,12,2024-10-12,0,1,2,0.0,0,BB,CHE,Offline TA/TO,TA/TO,0,0,0,D,F,0,No Deposit,251.0,,0,Transient,59.0,0,1
HB-019192,Resort Hotel,1,92,2024,February,9,26,2024-02-26,1,2,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,134.0,,0,Transient,79.0,0,0
HB-031897,Resort Hotel,0,147,2024,December,50,13,2024-12-13,8,20,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,,,0,Transient,59.08,0,1
HB-017619,Resort Hotel,0,174,2023,October,40,8,2023-10-08,2,8,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,F,1,No Deposit,243.0,,0,Contract,70.6,0,0
HB-077951,City Hotel,0,16,2023,September,39,25,2023-09-25,2,3,1,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,170.0,0,1
HB-075920,City Hotel,1,157,2023,July,27,6,2023-07-06,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,1
HB-094821,City Hotel,0,103,2024,August,32,7,2024-08-07,2,1,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,150.3,0,1
HB-099553,City Hotel,0,22,2024,October,41,11,2024-10-11,0,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,138.0,,0,Transient,95.0,0,0
HB-075692,City Hotel,1,295,2023,August,32,8,2023-08-08,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-010007,Resort Hotel,1,111,2025,February,6,4,2025-02-04,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,42.0,0,0
HB-009290,Resort Hotel,1,2,2024,November,45,9,2024-11-09,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,291.0,,0,Transient,30.0,0,0
HB-114817,City Hotel,0,396,2025,June,26,25,2025-06-25,2,0,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,122.4,0,1
HB-042642,City Hotel,0,10,2023,September,36,8,2023-09-08,0,4,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.0,0,2
HB-106766,City Hotel,0,41,2025,February,9,28,2025-02-28,0,3,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,80.0,0,0
HB-078242,City Hotel,1,8,2023,October,41,10,2023-10-10,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-054104,City Hotel,1,0,2024,July,27,7,2024-07-07,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,G,G,0,No Deposit,,,0,Transient,215.0,0,0
HB-032816,Resort Hotel,0,80,2025,February,6,4,2025-02-04,1,1,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,242.0,,0,Transient-Party,63.65,0,1
HB-105217,City Hotel,0,154,2025,January,5,27,2025-01-27,2,4,2,2.0,0,BB,BRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,7.0,,0,Transient,143.84,0,1
HB-058646,City Hotel,1,37,2024,October,41,13,2024-10-13,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,95.0,0,0
HB-066821,City Hotel,1,156,2025,April,17,26,2025-04-26,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,100.0,0,0
HB-102092,City Hotel,0,215,2024,November,47,21,2024-11-21,1,1,1,0.0,0,BB,NOR,Groups,Corporate,0,0,0,A,A,0,No Deposit,,233.0,0,Transient,75.0,0,0
HB-090154,City Hotel,0,0,2024,June,22,2,2024-06-02,0,1,2,1.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,158.0,0,0
HB-056843,City Hotel,1,317,2024,September,37,15,2024-09-15,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,120.0,0,0
HB-021850,Resort Hotel,0,46,2024,March,11,11,2024-03-11,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,375.0,,0,Transient-Party,25.0,0,0
HB-038142,Resort Hotel,0,2,2025,July,28,9,2025-07-09,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,105.0,0,1
HB-025548,Resort Hotel,0,248,2024,June,25,18,2024-06-18,4,10,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,3,No Deposit,143.0,,0,Transient,81.9,0,1
HB-070270,City Hotel,1,9,2025,June,24,13,2025-06-13,0,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,180.0,0,1
HB-116110,City Hotel,0,414,2025,July,28,13,2025-07-13,0,2,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,122.4,0,1
HB-010214,Resort Hotel,1,5,2025,February,8,20,2025-02-20,1,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,0
HB-081303,City Hotel,0,24,2023,December,49,5,2023-12-05,2,1,2,0.0,0,BB,ESP,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,143.0,0,Transient-Party,50.0,0,0
HB-023685,Resort Hotel,0,44,2024,April,18,29,2024-04-29,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,82.5,1,0
HB-043116,City Hotel,0,29,2023,September,37,15,2023-09-15,0,2,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Contract,94.5,0,0
HB-112465,City Hotel,0,18,2025,May,21,22,2025-05-22,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,315.0,,0,Transient-Party,120.0,0,1
HB-052358,City Hotel,1,275,2024,June,23,4,2024-06-04,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,5.0,,69,Transient,62.8,0,0
HB-093160,City Hotel,0,184,2024,July,29,16,2024-07-16,1,1,2,0.0,0,HB,ITA,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,125.0,0,1
HB-006494,Resort Hotel,1,32,2024,June,24,13,2024-06-13,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,129.0,0,0
HB-095518,City Hotel,0,320,2024,August,33,18,2024-08-18,0,2,1,0.0,0,HB,AUT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,90.0,0,0
HB-080691,City Hotel,0,32,2023,November,47,20,2023-11-20,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,119.0,,0,Transient-Party,73.0,0,0
HB-072722,City Hotel,1,389,2025,August,32,4,2025-08-04,0,2,1,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,6,No Deposit,9.0,,0,Transient,118.75,0,2
HB-101333,City Hotel,0,3,2024,November,45,10,2024-11-10,0,1,1,0.0,0,BB,BEL,Aviation,Corporate,0,0,0,D,D,0,No Deposit,,153.0,0,Transient-Party,95.0,0,0
HB-076432,City Hotel,1,358,2023,October,41,10,2023-10-10,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-042071,City Hotel,1,104,2023,August,35,30,2023-08-30,2,1,2,0.0,0,HB,ESP,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,90.0,0,0
HB-006151,Resort Hotel,0,225,2024,May,21,26,2024-05-26,2,3,2,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,A,2,Refundable,,223.0,0,Transient-Party,80.0,2,0
HB-088506,City Hotel,0,157,2024,May,18,5,2024-05-05,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Contract,127.0,0,0
HB-104391,City Hotel,0,8,2025,January,2,10,2025-01-10,0,2,2,0.0,0,BB,PER,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,75.08,0,1
HB-030797,Resort Hotel,0,1,2024,December,49,3,2024-12-03,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,65.0,0,0
HB-077001,City Hotel,0,0,2023,August,34,24,2023-08-24,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,B,B,1,No Deposit,,,0,Transient-Party,67.5,0,0
HB-119016,City Hotel,0,14,2025,August,35,27,2025-08-27,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,1,2
HB-094652,City Hotel,0,144,2024,August,31,3,2024-08-03,1,4,2,0.0,0,BB,HRV,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,92.65,0,0
HB-024827,Resort Hotel,0,117,2024,May,22,30,2024-05-30,1,5,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,241.0,,0,Transient,75.1,0,1
HB-077191,City Hotel,0,195,2023,September,36,7,2023-09-07,1,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,89.25,0,1
HB-065537,City Hotel,1,54,2025,April,14,5,2025-04-05,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-030917,Resort Hotel,0,40,2024,December,48,1,2024-12-01,2,5,2,0.0,0,Undefined,FRA,Offline TA/TO,TA/TO,0,0,0,C,C,2,No Deposit,464.0,,0,Transient,64.0,0,0
HB-108291,City Hotel,0,116,2025,March,13,24,2025-03-24,0,2,1,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,1,No Deposit,171.0,,0,Transient-Party,90.0,0,0
HB-069491,City Hotel,1,74,2025,June,22,1,2025-06-01,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,144.0,0,0
HB-029058,Resort Hotel,0,159,2024,October,42,16,2024-10-16,2,2,1,0.0,0,HB,SWE,Groups,Corporate,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,58.0,0,0
HB-085405,City Hotel,0,45,2024,March,10,10,2024-03-10,2,3,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,67.15,0,1
HB-025562,Resort Hotel,0,3,2024,June,26,30,2024-06-30,0,2,2,2.0,0,BB,PRT,Direct,Direct,0,0,0,H,H,0,No Deposit,250.0,,0,Transient,191.0,1,0
HB-007355,Resort Hotel,1,20,2024,August,32,5,2024-08-05,0,2,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,299.0,0,0
HB-060039,City Hotel,1,305,2024,November,45,4,2024-11-04,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,89.0,0,0
HB-048836,City Hotel,1,267,2024,March,13,31,2024-03-31,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-008560,Resort Hotel,0,383,2024,October,40,6,2024-10-06,0,3,1,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,1,No Deposit,315.0,,0,Transient-Party,48.0,0,0
HB-020341,Resort Hotel,0,26,2024,January,3,21,2024-01-21,1,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,0
HB-060613,City Hotel,1,57,2024,November,46,17,2024-11-17,0,2,2,0.0,0,HB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,136.8,0,1
HB-110546,City Hotel,0,35,2025,April,18,28,2025-04-28,0,1,1,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,83.2,0,0
HB-037085,Resort Hotel,0,241,2025,June,23,3,2025-06-03,2,2,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,3,No Deposit,240.0,,0,Transient,95.6,0,2
HB-040246,City Hotel,1,103,2023,July,29,18,2023-07-18,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-061190,City Hotel,1,17,2024,December,49,3,2024-12-03,2,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.39,0,0
HB-030566,Resort Hotel,0,8,2024,November,48,26,2024-11-26,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient-Party,63.0,0,1
HB-027146,Resort Hotel,0,1,2024,August,34,21,2024-08-21,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,250.0,,0,Transient,200.0,0,1
HB-019278,Resort Hotel,0,80,2023,December,49,6,2023-12-06,2,4,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,250.0,,0,Transient,27.9,0,0
HB-044133,City Hotel,0,85,2023,September,39,30,2023-09-30,0,3,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,31.0,,80,Transient-Party,125.0,0,0
HB-084589,City Hotel,0,35,2024,February,9,26,2024-02-26,1,2,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,86.9,0,1
HB-012221,Resort Hotel,1,129,2025,June,25,18,2025-06-18,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,483.0,,0,Transient,63.0,0,0
HB-096878,City Hotel,0,80,2024,September,36,4,2024-09-04,2,4,1,0.0,0,BB,USA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,86.0,,0,Transient-Party,85.0,0,0
HB-001109,Resort Hotel,1,91,2023,August,33,14,2023-08-14,2,2,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient,209.0,0,0
HB-036406,Resort Hotel,0,150,2025,May,21,19,2025-05-19,0,1,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,251.0,,0,Transient,62.0,0,0
HB-063900,City Hotel,1,69,2025,February,9,24,2025-02-24,2,4,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,94.2,0,1
HB-025066,Resort Hotel,0,17,2024,June,24,11,2024-06-11,1,1,2,0.0,0,BB,GIB,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,141.0,1,0
HB-096012,City Hotel,0,85,2024,August,34,22,2024-08-22,1,5,3,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,165.3,0,0
HB-099898,City Hotel,0,3,2024,October,42,16,2024-10-16,2,2,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.0,0,1
HB-006598,Resort Hotel,1,11,2024,June,25,20,2024-06-20,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,100.0,0,0
HB-032167,Resort Hotel,0,40,2025,January,3,16,2025-01-16,1,2,1,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,A,E,1,No Deposit,,,0,Transient-Party,55.0,0,0
HB-032373,Resort Hotel,0,1,2025,January,4,24,2025-01-24,0,1,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient,88.0,0,1
HB-102583,City Hotel,0,57,2024,December,48,1,2024-12-01,0,1,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,2
HB-114542,City Hotel,0,34,2025,June,25,19,2025-06-19,1,4,1,0.0,0,SC,USA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,136.0,0,0
HB-025338,Resort Hotel,0,245,2024,June,23,9,2024-06-09,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,143.0,,0,Transient,64.9,0,0
HB-013380,Resort Hotel,1,193,2025,August,33,12,2025-08-12,4,10,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,110.7,0,0
HB-025031,Resort Hotel,0,179,2024,June,24,11,2024-06-11,2,5,1,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,2,No Deposit,314.0,,0,Transient,93.2,0,2
HB-034164,Resort Hotel,0,195,2025,March,10,5,2025-03-05,4,6,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,D,D,0,No Deposit,273.0,,0,Transient-Party,62.28,0,0
HB-119285,City Hotel,0,141,2025,August,35,29,2025-08-29,0,4,2,0.0,0,BB,JPN,Direct,Direct,0,0,0,A,A,4,No Deposit,14.0,,0,Transient,138.75,0,1
HB-078151,City Hotel,0,19,2023,October,39,1,2023-10-01,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,121.75,0,1
HB-117504,City Hotel,0,0,2025,August,31,3,2025-08-03,0,2,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,7.0,,0,Transient,111.6,0,1
HB-080171,City Hotel,0,26,2024,July,28,11,2024-07-11,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,1,A,A,1,No Deposit,,40.0,0,Transient,65.0,0,0
HB-117467,City Hotel,0,172,2025,July,31,30,2025-07-30,2,3,2,0.0,0,BB,CHE,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,112.5,0,2
HB-000850,Resort Hotel,1,10,2023,August,31,1,2023-08-01,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,G,G,1,No Deposit,,,0,Transient-Party,252.0,0,0
HB-023220,Resort Hotel,0,2,2024,April,16,17,2024-04-17,1,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,39.0,0,0
HB-054477,City Hotel,1,12,2024,July,29,17,2024-07-17,1,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,85.0,0,0
HB-113646,City Hotel,0,34,2025,June,23,6,2025-06-06,0,4,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,149.5,0,1
HB-098139,City Hotel,0,174,2024,September,38,22,2024-09-22,0,3,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,95.67,0,0
HB-045566,City Hotel,0,86,2023,November,45,6,2023-11-06,2,3,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,72.25,0,1
HB-031084,Resort Hotel,0,0,2025,March,12,20,2025-03-20,1,3,1,0.0,0,BB,PRT,Direct,Direct,1,0,1,A,C,1,No Deposit,,,0,Transient,55.0,0,0
HB-034302,Resort Hotel,0,6,2025,March,11,16,2025-03-16,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,F,0,No Deposit,240.0,,0,Transient,75.0,0,1
HB-049363,City Hotel,1,50,2024,April,15,11,2024-04-11,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.45,0,1
HB-025120,Resort Hotel,0,36,2024,June,24,15,2024-06-15,2,4,3,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,H,H,1,No Deposit,240.0,,0,Transient,26.0,1,0
HB-065009,City Hotel,1,6,2025,March,12,22,2025-03-22,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,86.0,,0,Transient,94.4,0,0
HB-093460,City Hotel,0,103,2024,July,29,15,2024-07-15,2,5,2,0.0,0,BB,DNK,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,106.59,0,1
HB-111320,City Hotel,0,144,2025,May,19,6,2025-05-06,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,52.0,,0,Transient-Party,90.0,0,1
HB-024316,Resort Hotel,0,12,2024,May,20,16,2024-05-16,1,0,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,184.0,,0,Transient,70.0,1,0
HB-107840,City Hotel,0,20,2025,March,11,14,2025-03-14,0,5,1,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,132.0,,0,Transient,65.0,0,0
HB-079185,City Hotel,0,28,2023,October,41,12,2023-10-12,3,8,2,0.0,0,BB,SRB,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Contract,107.92,0,1
HB-010489,Resort Hotel,1,142,2025,March,10,9,2025-03-09,2,3,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,66.3,0,0
HB-115029,City Hotel,0,1,2025,June,26,29,2025-06-29,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,B,A,1,No Deposit,14.0,,0,Transient,168.5,0,0
HB-101123,City Hotel,0,262,2024,November,45,4,2024-11-04,0,2,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,146.7,0,2
HB-101525,City Hotel,0,46,2024,November,45,7,2024-11-07,1,5,1,0.0,0,BB,MEX,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,10.0,,0,Transient,124.71,0,0
HB-077776,City Hotel,0,16,2023,September,39,25,2023-09-25,0,2,2,0.0,0,BB,ITA,Groups,TA/TO,0,0,0,A,D,1,No Deposit,1.0,,0,Transient-Party,170.0,0,0
HB-040287,City Hotel,1,118,2023,July,29,19,2023-07-19,2,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.5,0,1
HB-051834,City Hotel,0,316,2024,May,21,26,2024-05-26,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,110.0,0,0
HB-097074,City Hotel,0,12,2024,September,37,11,2024-09-11,1,0,1,0.0,0,BB,CHN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,295.0,,0,Transient-Party,85.0,0,1
HB-082213,City Hotel,1,317,2024,September,37,9,2024-09-09,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,58.0,,56,Transient,90.0,0,0
HB-071674,City Hotel,1,272,2025,July,28,10,2025-07-10,1,0,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,1
HB-055890,City Hotel,1,10,2024,August,34,24,2024-08-24,0,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,3
HB-069717,City Hotel,1,352,2025,June,23,4,2025-06-04,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,75.0,0,0
HB-100935,City Hotel,0,125,2024,November,44,1,2024-11-01,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.0,0,2
HB-009933,Resort Hotel,1,30,2025,January,5,27,2025-01-27,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,78.0,0,0
HB-027342,Resort Hotel,0,136,2024,August,34,20,2024-08-20,2,5,3,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,181.0,,0,Transient,222.38,0,0
HB-100028,City Hotel,0,179,2024,October,42,19,2024-10-19,0,3,2,0.0,0,SC,HUN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.5,0,2
HB-090458,City Hotel,0,220,2024,June,23,4,2024-06-04,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,73.33,0,1
HB-110073,City Hotel,0,14,2025,April,16,17,2025-04-17,1,3,2,0.0,0,SC,ARG,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,115.0,0,2
HB-076510,City Hotel,1,195,2023,September,37,17,2023-09-17,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,20.0,,0,Transient,48.0,0,0
HB-021688,Resort Hotel,0,3,2024,March,10,5,2024-03-05,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,58.0,0,0
HB-071729,City Hotel,1,450,2025,July,28,11,2025-07-11,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-077323,City Hotel,0,237,2023,September,37,14,2023-09-14,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient-Party,89.25,0,0
HB-109871,City Hotel,0,13,2025,April,16,16,2025-04-16,2,0,2,2.0,0,BB,ISR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,225.0,0,1
HB-117325,City Hotel,0,64,2025,July,31,31,2025-07-31,1,1,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,240.0,0,0
HB-059059,City Hotel,0,290,2024,October,42,20,2024-10-20,2,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,3,No Deposit,9.0,,0,Transient-Party,90.95,0,0
HB-025150,Resort Hotel,0,139,2024,June,23,5,2024-06-05,4,7,2,0.0,0,HB,NLD,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,171.0,,0,Transient,93.8,0,0
HB-103284,City Hotel,0,59,2024,December,50,13,2024-12-13,0,5,2,1.0,0,HB,ITA,Online TA,TA/TO,0,0,0,D,D,4,No Deposit,9.0,,0,Transient,129.2,0,2
HB-009123,Resort Hotel,1,129,2024,October,44,28,2024-10-28,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,C,1,No Deposit,240.0,,0,Transient,48.95,0,2
HB-034875,Resort Hotel,0,57,2025,April,14,5,2025-04-05,0,3,2,0.0,0,BB,PRT,Direct,Corporate,0,0,0,A,E,0,No Deposit,,,0,Transient,50.0,0,0
HB-066869,City Hotel,1,156,2025,April,17,26,2025-04-26,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,100.0,0,0
HB-018396,Resort Hotel,0,2,2023,November,46,18,2023-11-18,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,337.0,0,Transient,38.0,0,0
HB-054509,City Hotel,1,165,2024,July,29,18,2024-07-18,1,3,2,0.0,0,SC,MOZ,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.0,0,1
HB-083744,City Hotel,0,57,2024,February,6,7,2024-02-07,2,2,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,B,B,0,No Deposit,,,0,Transient,65.0,0,1
HB-067987,City Hotel,1,22,2025,May,19,10,2025-05-10,2,7,3,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,204.0,0,0
HB-047528,City Hotel,1,56,2024,February,9,26,2024-02-26,0,2,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,69.6,0,0
HB-089873,City Hotel,0,14,2024,May,22,27,2024-05-27,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,62.5,0,0
HB-087948,City Hotel,0,2,2024,April,17,27,2024-04-27,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,146.0,0,1
HB-107262,City Hotel,0,41,2025,March,10,3,2025-03-03,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,100.3,0,0
HB-079635,City Hotel,0,0,2023,October,43,26,2023-10-26,1,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,3,No Deposit,,,0,Transient,133.0,0,0
HB-084472,City Hotel,0,38,2024,February,8,24,2024-02-24,0,3,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,75.5,0,0
HB-115861,City Hotel,0,1,2025,July,28,11,2025-07-11,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,170.0,0,0
HB-042340,City Hotel,1,25,2023,September,36,5,2023-09-05,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,105.0,0,1
HB-073686,City Hotel,1,134,2025,August,35,31,2025-08-31,0,2,2,1.0,0,BB,SAU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,162.5,0,1
HB-060148,City Hotel,1,66,2024,November,45,6,2024-11-06,2,3,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,83.0,,0,Transient,150.22,0,0
HB-057791,City Hotel,1,4,2024,October,40,1,2024-10-01,0,1,2,0.0,0,BB,PRT,Complementary,Direct,0,0,0,E,E,0,No Deposit,,45.0,0,Transient,0.0,0,1
HB-105849,City Hotel,0,10,2025,February,7,12,2025-02-12,2,2,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,91.8,0,2
HB-005459,Resort Hotel,1,87,2024,April,18,29,2024-04-29,2,5,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,71.0,,0,Transient,46.0,0,0
HB-039815,Resort Hotel,0,204,2025,August,35,26,2025-08-26,2,1,2,1.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,15.0,,0,Transient-Party,168.6,0,2
HB-044280,City Hotel,0,198,2023,October,40,3,2023-10-03,1,1,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,E,0,No Deposit,1.0,,0,Transient-Party,60.0,0,0
HB-006614,Resort Hotel,1,152,2024,June,25,20,2024-06-20,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,315.0,,0,Transient,62.9,0,0
HB-025248,Resort Hotel,0,43,2024,June,24,15,2024-06-15,1,4,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,201.0,1,1
HB-028131,Resort Hotel,0,76,2024,September,38,18,2024-09-18,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,80.0,0,2
HB-011374,Resort Hotel,1,210,2025,May,18,4,2025-05-04,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient,68.4,0,1
HB-118890,City Hotel,0,457,2025,August,35,25,2025-08-25,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,122.4,0,1
HB-024619,Resort Hotel,0,93,2024,May,20,18,2024-05-18,2,7,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,90.0,0,3
HB-068848,City Hotel,1,84,2025,May,21,21,2025-05-21,2,2,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,A,A,2,No Deposit,14.0,,0,Transient,109.25,0,0
HB-051960,City Hotel,0,316,2024,May,21,26,2024-05-26,0,3,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,110.0,0,0
HB-042267,City Hotel,0,63,2023,September,36,4,2023-09-04,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,21.0,,0,Transient-Party,116.0,0,0
HB-004597,Resort Hotel,0,162,2024,March,12,24,2024-03-24,0,3,3,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,C,1,No Deposit,,,0,Transient-Party,113.4,0,0
HB-116565,City Hotel,0,244,2025,July,29,15,2025-07-15,2,5,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,1
HB-088371,City Hotel,0,28,2024,May,18,1,2024-05-01,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,133.95,0,1
HB-090289,City Hotel,0,16,2024,June,22,2,2024-06-02,0,3,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,152.67,0,1
HB-033874,Resort Hotel,0,5,2025,February,9,28,2025-02-28,1,5,2,0.0,0,BB,NLD,Groups,Corporate,0,0,0,A,A,1,No Deposit,,223.0,0,Transient-Party,47.5,2,0
HB-041144,City Hotel,1,0,2023,August,32,13,2023-08-13,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,89.0,0,1
HB-113023,City Hotel,0,82,2025,May,22,28,2025-05-28,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,42.0,,0,Transient,89.1,0,1
HB-010505,Resort Hotel,1,57,2025,March,11,11,2025-03-11,2,5,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,D,D,0,No Deposit,298.0,,0,Transient-Party,64.0,0,0
HB-070211,City Hotel,1,139,2025,June,24,12,2025-06-12,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,110.0,0,0
HB-102078,City Hotel,0,215,2024,November,47,21,2024-11-21,1,1,1,0.0,0,BB,ESP,Groups,Corporate,0,0,0,A,A,1,No Deposit,,233.0,0,Transient,75.0,0,0
HB-104428,City Hotel,0,2,2025,January,2,10,2025-01-10,0,4,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,108.59,0,3
HB-099317,City Hotel,0,32,2024,October,41,9,2024-10-09,2,1,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,85.5,0,0
HB-087028,City Hotel,0,55,2024,April,15,12,2024-04-12,0,1,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient-Party,94.5,0,0
HB-010537,Resort Hotel,1,146,2025,March,11,13,2025-03-13,1,0,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,66.0,,34,Transient-Party,36.0,0,0
HB-017866,Resort Hotel,0,25,2023,October,43,23,2023-10-23,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,56.0,0,2
HB-006821,Resort Hotel,1,38,2024,July,27,4,2024-07-04,1,4,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,241.0,,0,Transient,178.64,0,0
HB-007150,Resort Hotel,1,12,2024,July,30,24,2024-07-24,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,126.0,0,0
HB-002182,Resort Hotel,1,170,2023,October,40,4,2023-10-04,4,8,2,0.0,0,BB,CN,Groups,TA/TO,0,0,0,A,A,0,Non Refund,15.0,,0,Transient,44.5,0,0
HB-103538,City Hotel,0,0,2024,December,52,26,2024-12-26,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,12.0,0,0
HB-030151,Resort Hotel,0,97,2024,November,45,7,2024-11-07,3,6,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,75.0,,0,Transient,64.6,0,0
HB-024413,Resort Hotel,0,2,2024,May,20,19,2024-05-19,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,10.0,,0,Transient,72.0,0,0
HB-009898,Resort Hotel,1,41,2025,January,3,19,2025-01-19,0,2,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,468.0,,0,Transient,57.6,0,0
HB-046780,City Hotel,1,151,2024,January,3,19,2024-01-19,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,19.0,,63,Transient-Party,80.0,0,0
HB-060644,City Hotel,1,39,2024,November,46,17,2024-11-17,1,3,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,2
HB-092938,City Hotel,0,94,2024,July,28,13,2024-07-13,0,2,3,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,137.7,0,2
HB-028133,Resort Hotel,0,12,2024,September,38,19,2024-09-19,1,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,125.0,0,3
HB-002999,Resort Hotel,0,0,2023,November,45,11,2023-11-11,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,E,0,No Deposit,,,0,Transient,79.0,1,0
HB-072622,City Hotel,1,188,2025,August,31,1,2025-08-01,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-101585,City Hotel,0,30,2024,November,46,11,2024-11-11,1,2,2,0.0,0,SC,SWE,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,87.27,0,0
HB-041701,City Hotel,1,44,2023,August,34,22,2023-08-22,2,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,86.0,0,0
HB-058148,City Hotel,1,16,2024,October,41,7,2024-10-07,0,1,2,0.0,0,SC,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.0,0,0
HB-105580,City Hotel,0,24,2025,February,6,5,2025-02-05,2,5,1,0.0,0,BB,MAR,Groups,TA/TO,0,0,0,A,A,1,No Deposit,,407.0,0,Transient-Party,75.0,0,0
HB-000933,Resort Hotel,0,51,2023,August,31,6,2023-08-06,2,6,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,173.0,0,0
HB-102851,City Hotel,0,8,2024,December,49,7,2024-12-07,0,1,1,0.0,0,SC,PRT,Direct,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient,88.0,0,1
HB-046570,City Hotel,0,14,2024,January,2,8,2024-01-08,1,2,1,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,68.85,0,0
HB-114176,City Hotel,0,165,2025,June,24,14,2025-06-14,0,4,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,144.0,0,0
HB-009101,Resort Hotel,1,181,2024,October,43,27,2024-10-27,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,6,No Deposit,240.0,,0,Transient-Party,55.25,0,1
HB-019017,Resort Hotel,0,15,2023,December,49,4,2023-12-04,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient-Party,64.67,0,2
HB-001468,Resort Hotel,0,83,2023,August,35,31,2023-08-31,1,1,1,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,80.55,0,0
HB-032905,Resort Hotel,0,0,2025,February,6,8,2025-02-08,0,1,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,48.0,0,0
HB-098731,City Hotel,0,11,2024,October,40,3,2024-10-03,1,0,1,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,144.0,0,2
HB-054588,City Hotel,1,246,2024,July,29,20,2024-07-20,0,3,3,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Contract,96.73,0,1
HB-043282,City Hotel,1,162,2023,September,37,17,2023-09-17,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,3.0,,0,Transient-Party,60.0,0,0
HB-090055,City Hotel,0,56,2024,May,22,30,2024-05-30,1,1,1,0.0,0,BB,CHE,Groups,TA/TO,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,120.0,0,0
HB-097648,City Hotel,0,315,2024,September,38,17,2024-09-17,1,1,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,38,Transient-Party,65.0,0,1
HB-000804,Resort Hotel,0,52,2023,July,30,30,2023-07-30,0,3,2,2.0,0,FB,ESP,Offline TA/TO,TA/TO,0,0,0,C,C,0,No Deposit,196.0,,0,Transient,280.74,1,0
HB-012330,Resort Hotel,1,273,2025,June,26,24,2025-06-24,2,6,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,81.76,0,1
HB-029630,Resort Hotel,0,21,2024,October,44,29,2024-10-29,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,60.64,0,1
HB-119348,City Hotel,0,63,2025,August,35,31,2025-08-31,0,3,3,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,195.33,0,2
HB-031358,Resort Hotel,0,109,2024,December,52,24,2024-12-24,1,1,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,37.8,0,2
HB-091920,City Hotel,0,53,2024,June,26,24,2024-06-24,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,65.0,0,1
HB-104125,City Hotel,0,89,2025,January,1,1,2025-01-01,2,3,3,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,99.0,0,0
HB-114179,City Hotel,0,278,2025,June,24,14,2025-06-14,0,4,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,110.0,0,2
HB-010991,Resort Hotel,1,71,2025,April,16,14,2025-04-14,0,1,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,117.0,0,2
HB-042960,City Hotel,1,72,2023,September,37,11,2023-09-11,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,126.0,0,0
HB-052036,City Hotel,1,107,2024,May,22,29,2024-05-29,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient-Party,80.75,0,1
HB-010239,Resort Hotel,1,2,2025,February,8,22,2025-02-22,0,4,1,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,36.0,0,0
HB-003034,Resort Hotel,1,55,2023,November,45,11,2023-11-11,0,3,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,281.0,,0,Contract,53.0,0,0
HB-014716,Resort Hotel,1,259,2023,September,37,17,2023-09-17,0,3,2,0.0,0,BB,GBR,Groups,Corporate,0,1,0,A,A,0,Non Refund,,223.0,0,Transient,40.05,0,0
HB-014022,Resort Hotel,0,2,2024,December,50,14,2024-12-14,0,2,1,0.0,0,BB,,Corporate,Corporate,0,0,23,A,D,1,No Deposit,,204.0,0,Transient,30.0,0,2
HB-070200,City Hotel,1,173,2025,June,24,11,2025-06-11,2,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,140.0,0,0
HB-033630,Resort Hotel,0,0,2025,February,9,24,2025-02-24,2,2,2,1.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient-Party,40.5,0,0
HB-025263,Resort Hotel,0,223,2024,June,24,13,2024-06-13,2,5,1,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,52.83,0,0
HB-090084,City Hotel,0,0,2024,June,22,1,2024-06-01,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,116.1,0,1
HB-024342,Resort Hotel,0,90,2024,May,19,10,2024-05-10,2,6,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,175.0,,0,Transient,70.4,0,0
HB-091045,City Hotel,0,0,2024,June,24,13,2024-06-13,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,80.75,0,0
HB-089025,City Hotel,0,3,2024,May,19,12,2024-05-12,2,3,2,0.0,0,SC,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,96.8,0,1
HB-082367,City Hotel,1,108,2024,March,12,18,2024-03-18,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,154.0,,0,Transient,80.0,0,0
HB-105138,City Hotel,0,3,2025,January,5,28,2025-01-28,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-090275,City Hotel,0,2,2024,June,22,2,2024-06-02,0,2,2,0.0,0,BB,PRT,Online TA,Corporate,0,0,0,A,E,0,No Deposit,,263.0,0,Transient,120.0,0,0
HB-106906,City Hotel,0,1,2025,March,10,4,2025-03-04,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,0
HB-045867,City Hotel,0,98,2023,November,47,23,2023-11-23,1,3,2,0.0,0,BB,KWT,Groups,TA/TO,0,0,0,A,A,2,No Deposit,37.0,,0,Transient-Party,75.0,0,0
HB-063703,City Hotel,1,10,2025,February,8,17,2025-02-17,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Contract,68.0,0,0
HB-057249,City Hotel,1,14,2024,September,38,22,2024-09-22,0,1,1,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,184.0,0,2
HB-105549,City Hotel,0,1,2025,February,7,10,2025-02-10,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,94.0,,0,Transient,65.0,0,1
HB-011424,Resort Hotel,1,136,2025,May,19,7,2025-05-07,2,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,242.0,,0,Transient,115.0,0,1
HB-063203,City Hotel,1,573,2025,February,5,2,2025-02-02,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-111662,City Hotel,0,14,2025,May,19,10,2025-05-10,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,148.0,0,1
HB-009801,Resort Hotel,1,56,2025,January,1,3,2025-01-03,0,4,3,0.0,0,BB,AUS,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,62.0,0,2
HB-088505,City Hotel,0,112,2024,May,18,4,2024-05-04,0,4,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,101.58,0,1
HB-088855,City Hotel,0,25,2024,May,19,10,2024-05-10,0,3,1,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,129.0,0,0
HB-017665,Resort Hotel,0,287,2023,October,41,15,2023-10-15,1,3,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,0,No Deposit,,223.0,0,Transient-Party,44.5,0,0
HB-085318,City Hotel,0,3,2024,March,11,12,2024-03-12,0,1,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient,65.0,0,1
HB-110928,City Hotel,0,103,2025,May,18,2,2025-05-02,0,2,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,125.09,0,1
HB-083204,City Hotel,0,4,2024,January,4,22,2024-01-22,0,2,2,0.0,0,BB,PRT,Complementary,Direct,0,0,0,G,G,1,No Deposit,,,0,Transient,1.0,1,1
HB-059841,City Hotel,1,482,2024,November,44,3,2024-11-03,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-048532,City Hotel,1,87,2024,March,13,25,2024-03-25,1,2,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.5,0,1
HB-051381,City Hotel,1,316,2024,May,20,19,2024-05-19,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-116154,City Hotel,0,8,2025,July,29,15,2025-07-15,0,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.0,0,1
HB-054256,City Hotel,1,12,2024,July,28,10,2024-07-10,2,1,1,0.0,0,BB,CZE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,145.0,0,0
HB-060219,City Hotel,1,277,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-038328,Resort Hotel,0,1,2025,July,28,13,2025-07-13,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,140.0,0,2
HB-052299,City Hotel,0,149,2024,June,23,3,2024-06-03,0,1,2,0.0,0,SC,GRC,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,95.4,0,0
HB-057579,City Hotel,1,215,2024,September,39,28,2024-09-28,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,97.71,0,0
HB-015014,Resort Hotel,1,244,2023,September,35,3,2023-09-03,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,19,0,A,A,0,Non Refund,,,0,Transient,36.0,0,0
HB-047342,City Hotel,1,44,2024,February,7,17,2024-02-17,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,44.0,,3,Transient,75.0,0,0
HB-080169,City Hotel,1,17,2023,November,45,12,2023-11-12,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-057069,City Hotel,1,118,2024,September,38,18,2024-09-18,1,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,34.0,,0,Transient,125.0,0,0
HB-023123,Resort Hotel,0,117,2024,April,15,12,2024-04-12,0,4,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,242.0,,0,Transient,102.5,1,1
HB-010906,Resort Hotel,1,124,2025,April,15,9,2025-04-09,2,5,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,492.0,,0,Transient,80.0,0,0
HB-009451,Resort Hotel,1,69,2024,November,48,30,2024-11-30,2,5,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,1,No Deposit,250.0,,0,Transient,58.4,0,1
HB-040693,City Hotel,0,12,2023,August,31,5,2023-08-05,0,3,1,0.0,0,BB,RUS,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,38.0,0,Transient-Party,60.0,0,0
HB-104056,City Hotel,0,4,2025,January,1,3,2025-01-03,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,81.62,0,1
HB-023152,Resort Hotel,0,72,2024,April,15,9,2024-04-09,2,5,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,C,0,No Deposit,96.0,,0,Transient-Party,41.4,0,0
HB-040993,City Hotel,0,3,2023,August,32,10,2023-08-10,1,2,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,,,0,Transient,63.5,0,1
HB-024735,Resort Hotel,0,179,2024,June,22,1,2024-06-01,0,1,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,F,0,No Deposit,251.0,,0,Transient-Party,78.0,0,0
HB-017152,Resort Hotel,0,207,2023,September,39,26,2023-09-26,1,1,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,208.0,,0,Transient-Party,74.0,0,0
HB-043534,City Hotel,0,75,2023,September,38,19,2023-09-19,2,2,2,0.0,0,BB,RUS,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-116275,City Hotel,0,172,2025,July,29,15,2025-07-15,1,1,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.1,0,0
HB-096800,City Hotel,0,64,2024,September,36,5,2024-09-05,1,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,115.5,0,2
HB-102013,City Hotel,0,17,2024,November,47,21,2024-11-21,1,0,2,0.0,0,SC,PRT,Direct,Direct,0,0,0,A,A,2,No Deposit,,,0,Transient,38.5,0,1
HB-004371,Resort Hotel,0,259,2024,March,10,8,2024-03-08,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,4,No Deposit,2.0,,0,Contract,26.1,0,0
HB-094600,City Hotel,0,10,2024,August,32,5,2024-08-05,0,2,2,1.0,1,BB,PRT,Online TA,TA/TO,0,0,0,D,E,1,No Deposit,9.0,,0,Transient,186.0,0,1
HB-092765,City Hotel,0,141,2024,July,27,5,2024-07-05,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,A,0,No Deposit,27.0,,0,Transient-Party,82.45,0,1
HB-025034,Resort Hotel,0,90,2024,June,23,7,2024-06-07,0,5,1,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,107.0,0,0
HB-092258,City Hotel,0,129,2024,June,26,30,2024-06-30,0,3,3,0.0,0,BB,DEU,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient-Party,164.87,0,2
HB-063987,City Hotel,1,311,2025,February,9,25,2025-02-25,2,2,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,107.95,0,1
HB-009349,Resort Hotel,1,42,2024,November,46,17,2024-11-17,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,62.0,0,1
HB-028403,Resort Hotel,0,10,2024,September,40,30,2024-09-30,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,2,No Deposit,240.0,,0,Transient,151.0,1,1
HB-024310,Resort Hotel,0,2,2024,June,26,26,2024-06-26,2,0,1,0.0,0,BB,PRT,Online TA,TA/TO,1,0,1,A,I,0,No Deposit,339.0,,0,Transient,108.0,1,0
HB-037594,Resort Hotel,0,158,2025,June,25,16,2025-06-16,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,154.0,1,2
HB-108268,City Hotel,0,46,2025,March,12,22,2025-03-22,0,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,82.2,0,0
HB-088674,City Hotel,0,46,2024,May,19,7,2024-05-07,2,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.9,0,2
HB-063971,City Hotel,1,158,2025,February,9,25,2025-02-25,1,1,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,126.0,0,2
HB-109981,City Hotel,0,148,2025,April,16,14,2025-04-14,2,4,2,0.0,0,BB,MRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,97.65,0,1
HB-098350,City Hotel,0,19,2024,September,39,26,2024-09-26,1,1,2,0.0,0,BB,IRN,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,86.0,,0,Transient,151.2,0,0
HB-020464,Resort Hotel,0,106,2024,January,4,23,2024-01-23,2,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,41.4,0,1
HB-022833,Resort Hotel,0,90,2024,April,14,5,2024-04-05,0,3,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,81.2,0,1
HB-107603,City Hotel,0,6,2025,March,11,12,2025-03-12,2,2,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,76.23,0,0
HB-034923,Resort Hotel,0,78,2025,April,14,6,2025-04-06,0,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,F,0,No Deposit,40.0,,0,Contract,50.85,0,0
HB-008908,Resort Hotel,0,385,2024,October,42,19,2024-10-19,1,4,3,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,C,1,No Deposit,,,0,Transient-Party,79.0,0,0
HB-001632,Resort Hotel,1,142,2023,September,36,6,2023-09-06,2,5,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,103.85,0,1
HB-081780,City Hotel,1,113,2024,February,8,25,2024-02-25,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,44,Transient,75.0,0,0
HB-084725,City Hotel,0,7,2024,February,9,28,2024-02-28,2,2,2,0.0,0,BB,MAR,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,134.0,,0,Transient-Party,87.0,0,0
HB-006090,Resort Hotel,0,227,2024,May,21,24,2024-05-24,2,8,2,0.0,0,HB,IRL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,175.0,,0,Transient,79.13,0,1
HB-115089,City Hotel,0,50,2025,June,26,27,2025-06-27,0,4,2,0.0,0,BB,SAU,Direct,Direct,0,0,0,A,D,0,No Deposit,14.0,,0,Transient,103.5,0,0
HB-042075,City Hotel,0,1,2023,August,35,30,2023-08-30,2,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,114.0,0,0
HB-062409,City Hotel,1,8,2025,January,3,13,2025-01-13,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,108.0,0,2
HB-034444,Resort Hotel,0,84,2025,March,9,1,2025-03-01,6,19,2,0.0,0,HB,CN,Groups,TA/TO,0,0,0,A,A,0,No Deposit,440.0,,0,Transient-Party,55.8,0,1
HB-082527,City Hotel,0,57,2023,December,52,25,2023-12-25,2,5,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,72.47,0,0
HB-086822,City Hotel,0,86,2024,April,14,6,2024-04-06,0,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,99.3,0,1
HB-013202,Resort Hotel,1,165,2025,August,32,4,2025-08-04,2,4,3,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,201.6,0,1
HB-053269,City Hotel,1,245,2024,June,25,17,2024-06-17,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,0,Transient,75.0,0,0
HB-090509,City Hotel,0,247,2024,June,23,6,2024-06-06,1,1,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-049336,City Hotel,1,24,2024,April,15,10,2024-04-10,2,5,1,0.0,0,BB,SGP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,127.97,0,1
HB-114795,City Hotel,0,396,2025,June,26,25,2025-06-25,2,0,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,122.4,0,1
HB-035432,Resort Hotel,0,84,2025,April,16,15,2025-04-15,2,5,2,0.0,1,HB,NGA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,171.0,,0,Transient,83.22,0,0
HB-047598,City Hotel,1,116,2024,February,9,28,2024-02-28,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,61.0,0,0
HB-047913,City Hotel,1,30,2024,March,10,9,2024-03-09,0,3,2,2.0,0,BB,USA,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient,77.5,0,0
HB-083934,City Hotel,0,17,2024,February,7,12,2024-02-12,1,2,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,144.0,0,0
HB-014540,Resort Hotel,0,6,2024,February,6,9,2024-02-09,0,3,1,0.0,0,BB,,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,196.0,,0,Transient,25.0,0,0
HB-092578,City Hotel,0,116,2024,July,27,7,2024-07-07,0,2,2,0.0,0,BB,NOR,Direct,Direct,0,0,0,A,A,2,No Deposit,14.0,,0,Transient,125.0,0,0
HB-116878,City Hotel,0,144,2025,July,30,22,2025-07-22,2,2,2,2.0,0,BB,GBR,Direct,Direct,0,0,0,F,F,1,No Deposit,14.0,,0,Transient,230.0,0,0
HB-111093,City Hotel,0,8,2025,May,18,1,2025-05-01,1,4,2,0.0,0,SC,FRA,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,110.4,0,0
HB-007741,Resort Hotel,1,92,2024,August,34,23,2024-08-23,2,5,1,0.0,0,FB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,5.0,,0,Transient,175.34,0,0
HB-024509,Resort Hotel,0,6,2024,May,21,23,2024-05-23,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,H,0,No Deposit,,399.0,0,Transient,63.0,0,0
HB-045667,City Hotel,0,140,2023,November,46,18,2023-11-18,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,29.0,,87,Transient-Party,75.0,0,0
HB-060595,City Hotel,1,14,2024,November,46,16,2024-11-16,0,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.0,0,0
HB-096915,City Hotel,0,32,2024,September,37,9,2024-09-09,0,1,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.9,0,2
HB-022005,Resort Hotel,0,0,2024,March,10,10,2024-03-10,2,4,1,0.0,0,BB,NLD,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,70.0,0,0
HB-082593,City Hotel,0,69,2023,December,52,30,2023-12-30,0,4,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Contract,111.3,0,1
HB-083225,City Hotel,0,11,2024,January,3,21,2024-01-21,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.0,0,1
HB-106848,City Hotel,0,20,2025,February,9,27,2025-02-27,1,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,100.3,0,0
HB-069352,City Hotel,1,186,2025,May,22,30,2025-05-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,130.0,0,0
HB-019535,Resort Hotel,0,73,2023,December,50,12,2023-12-12,4,10,1,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,36.0,0,1
HB-093082,City Hotel,0,257,2024,July,29,16,2024-07-16,0,1,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,B,B,0,No Deposit,14.0,,0,Transient,90.5,0,0
HB-104527,City Hotel,0,8,2025,January,3,13,2025-01-13,1,2,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.0,0,2
HB-053205,City Hotel,1,245,2024,June,25,17,2024-06-17,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,0,Transient,75.0,0,0
HB-054131,City Hotel,1,365,2024,July,27,7,2024-07-07,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-095418,City Hotel,0,0,2024,August,33,17,2024-08-17,0,2,2,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,8.0,,0,Transient,165.0,0,1
HB-085788,City Hotel,0,0,2024,March,12,21,2024-03-21,1,0,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.0,0,0
HB-108370,City Hotel,0,104,2025,March,12,19,2025-03-19,2,5,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,20.0,,0,Transient-Party,75.0,0,1
HB-088379,City Hotel,0,105,2024,May,18,2,2024-05-02,1,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,94.5,0,1
HB-115234,City Hotel,0,3,2025,June,26,29,2025-06-29,1,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,149.5,0,1
HB-007618,Resort Hotel,1,143,2024,August,33,16,2024-08-16,4,10,2,2.0,0,BB,ROU,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,286.79,0,0
HB-097636,City Hotel,0,25,2024,September,38,16,2024-09-16,1,2,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,155.67,0,4
HB-029403,Resort Hotel,0,29,2024,October,43,27,2024-10-27,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,113.0,0,Transient,45.0,0,0
HB-005954,Resort Hotel,1,132,2024,May,20,17,2024-05-17,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,79.2,0,1
HB-102862,City Hotel,0,65,2024,December,49,4,2024-12-04,2,2,2,0.0,0,BB,GRC,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,68.0,0,1
HB-011900,Resort Hotel,1,323,2025,June,23,3,2025-06-03,2,5,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,72.0,0,0
HB-006280,Resort Hotel,1,215,2024,June,22,1,2024-06-01,0,3,2,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,96.0,,0,Transient,110.0,0,0
HB-038337,Resort Hotel,0,142,2025,July,28,10,2025-07-10,1,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,154.0,0,1
HB-067299,City Hotel,1,157,2025,May,18,1,2025-05-01,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,130.0,0,0
HB-062451,City Hotel,1,38,2025,January,3,14,2025-01-14,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,Non Refund,,67.0,0,Transient,75.0,0,0
HB-060316,City Hotel,1,277,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-011158,Resort Hotel,1,201,2025,April,17,23,2025-04-23,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,C,1,No Deposit,240.0,,0,Transient,54.0,0,0
HB-055872,City Hotel,1,137,2024,August,34,23,2024-08-23,0,4,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,133.2,0,0
HB-014069,Resort Hotel,0,6,2024,January,2,13,2024-01-13,0,1,1,0.0,0,BB,,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,184.0,,0,Transient,37.0,0,0
HB-022073,Resort Hotel,0,4,2024,March,11,14,2024-03-14,1,2,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,40.0,0,0
HB-117754,City Hotel,0,13,2025,August,32,6,2025-08-06,2,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,186.0,0,0
HB-031017,Resort Hotel,0,44,2024,December,49,8,2024-12-08,0,3,2,0.0,0,FB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,72.0,0,0
HB-106310,City Hotel,0,48,2025,February,8,22,2025-02-22,0,2,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,65.0,0,1
HB-000330,Resort Hotel,0,81,2023,July,28,12,2023-07-12,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,147.0,,0,Transient,78.84,0,0
HB-114158,City Hotel,0,32,2025,June,25,17,2025-06-17,0,1,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,1
HB-069333,City Hotel,1,186,2025,May,22,30,2025-05-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,130.0,0,0
HB-094262,City Hotel,0,22,2024,August,31,1,2024-08-01,1,0,1,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,138.0,1,1
HB-104639,City Hotel,0,32,2025,January,3,16,2025-01-16,1,2,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,2,No Deposit,19.0,,0,Transient-Party,75.0,0,0
HB-084983,City Hotel,0,16,2024,March,9,3,2024-03-03,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,88.8,0,2
HB-022673,Resort Hotel,0,51,2024,March,13,31,2024-03-31,0,1,2,1.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,E,0,No Deposit,251.0,,0,Transient,73.75,0,1
HB-040098,City Hotel,1,83,2023,July,27,6,2023-07-06,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,1
HB-104060,City Hotel,0,0,2025,January,1,2,2025-01-02,1,2,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,109.67,0,0
HB-017344,Resort Hotel,0,1,2023,October,40,6,2023-10-06,0,5,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient,67.0,0,0
HB-020262,Resort Hotel,0,61,2024,January,3,19,2024-01-19,0,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,65.4,1,1
HB-081470,City Hotel,0,7,2023,December,49,9,2023-12-09,0,3,2,0.0,0,BB,CHE,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,58.0,0,0
HB-113446,City Hotel,0,26,2025,June,23,6,2025-06-06,0,2,2,1.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,140.0,0,2
HB-093424,City Hotel,0,7,2024,July,29,20,2024-07-20,0,1,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,1
HB-041530,City Hotel,0,46,2023,August,33,17,2023-08-17,1,1,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,1
HB-087775,City Hotel,0,138,2024,April,17,23,2024-04-23,2,1,2,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,71.0,0,0
HB-056949,City Hotel,1,64,2024,September,38,16,2024-09-16,0,1,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,149.4,0,0
HB-056666,City Hotel,1,198,2024,September,37,9,2024-09-09,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,120.0,0,0
HB-104664,City Hotel,0,3,2025,January,3,19,2025-01-19,0,1,1,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,102.0,1,0
HB-012651,Resort Hotel,1,217,2025,July,28,10,2025-07-10,1,3,3,1.0,0,HB,CHE,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,293.0,0,0
HB-032482,Resort Hotel,0,4,2025,January,3,18,2025-01-18,2,9,2,0.0,0,BB,ITA,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,45.82,0,0
HB-066570,City Hotel,1,158,2025,April,17,21,2025-04-21,2,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,1
HB-077029,City Hotel,0,183,2023,September,35,1,2023-09-01,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.5,0,1
HB-095938,City Hotel,0,1,2024,August,34,24,2024-08-24,0,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,99.33,0,1
HB-080922,City Hotel,0,35,2023,November,47,26,2023-11-26,0,3,1,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Contract,103.5,1,2
HB-033144,Resort Hotel,0,75,2025,February,7,12,2025-02-12,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient-Party,66.5,0,2
HB-097236,City Hotel,0,7,2024,September,37,13,2024-09-13,0,1,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,9.0,,0,Transient,184.0,0,2
HB-080540,City Hotel,0,13,2023,November,46,15,2023-11-15,2,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,85.0,0,1
HB-108151,City Hotel,0,46,2025,March,12,17,2025-03-17,2,5,2,0.0,0,SC,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,59.5,0,0
HB-047837,City Hotel,1,63,2024,March,10,5,2024-03-05,2,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,87.3,0,0
HB-038560,Resort Hotel,0,147,2025,July,28,12,2025-07-12,2,8,2,0.0,0,HB,BEL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,479.0,,0,Transient,143.05,0,3
HB-088998,City Hotel,0,196,2024,May,19,12,2024-05-12,1,3,2,0.0,0,BB,USA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,128.0,,0,Transient-Party,80.75,0,0
HB-014970,Resort Hotel,0,195,2025,March,10,5,2025-03-05,4,6,2,0.0,0,BB,GBR,Groups,Direct,1,0,2,A,H,2,No Deposit,273.0,,0,Transient-Party,-6.38,0,0
HB-024104,Resort Hotel,0,5,2024,May,19,11,2024-05-11,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,D,D,1,No Deposit,250.0,,0,Transient,84.6,0,0
HB-025817,Resort Hotel,0,177,2024,July,27,6,2024-07-06,2,5,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,E,E,1,No Deposit,250.0,,0,Transient,104.6,0,1
HB-038404,Resort Hotel,0,139,2025,July,28,10,2025-07-10,2,5,2,0.0,1,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,107.71,0,3
HB-095619,City Hotel,0,112,2024,August,33,14,2024-08-14,2,5,2,2.0,0,BB,FRA,Direct,Direct,0,0,0,G,G,0,No Deposit,14.0,,0,Transient,240.3,0,1
HB-101928,City Hotel,0,60,2024,November,47,18,2024-11-18,0,2,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-017712,Resort Hotel,0,283,2023,October,41,12,2023-10-12,2,5,2,0.0,0,BB,GBR,Groups,Direct,0,0,0,D,D,1,No Deposit,273.0,,0,Transient-Party,67.31,0,0
HB-035339,Resort Hotel,0,5,2025,April,16,18,2025-04-18,0,1,1,0.0,0,BB,GBR,Complementary,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Transient,0.0,0,2
HB-041284,City Hotel,1,39,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,101.5,0,0
HB-031854,Resort Hotel,0,20,2025,January,2,6,2025-01-06,0,2,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,H,H,1,No Deposit,240.0,,0,Transient-Party,100.0,1,2
HB-036940,Resort Hotel,0,135,2025,May,22,30,2025-05-30,0,3,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,94.97,0,2
HB-079120,City Hotel,0,6,2023,October,42,20,2023-10-20,0,2,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,120.0,0,2
HB-022414,Resort Hotel,0,42,2024,March,12,19,2024-03-19,2,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,29.0,0,0
HB-082927,City Hotel,1,177,2024,May,19,8,2024-05-08,2,0,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,3.0,,0,Transient,121.0,0,0
HB-082972,City Hotel,0,0,2024,January,1,7,2024-01-07,0,1,2,0.0,0,SC,AGO,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,75.0,0,0
HB-105128,City Hotel,0,11,2025,January,4,25,2025-01-25,1,4,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,0
HB-057146,City Hotel,1,280,2024,September,38,19,2024-09-19,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,35,Transient,110.0,0,0
HB-031816,Resort Hotel,0,3,2025,January,2,7,2025-01-07,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,330.0,,0,Transient-Party,44.0,0,1
HB-068688,City Hotel,1,165,2025,May,21,19,2025-05-19,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,225.0,0,0
HB-079216,City Hotel,0,26,2023,October,42,19,2023-10-19,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Transient,75.0,0,1
HB-087403,City Hotel,0,67,2024,April,16,15,2024-04-15,2,2,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,104.98,0,0
HB-008897,Resort Hotel,1,2,2024,October,42,19,2024-10-19,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,5.0,,0,Transient-Party,52.8,0,0
HB-021635,Resort Hotel,0,5,2024,March,10,5,2024-03-05,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,F,0,No Deposit,240.0,,0,Transient,68.0,0,3
HB-072179,City Hotel,1,240,2025,July,30,23,2025-07-23,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-096496,City Hotel,0,0,2024,September,36,2,2024-09-02,0,1,2,0.0,0,SC,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,149.0,0,0
HB-028481,Resort Hotel,0,0,2024,October,40,4,2024-10-04,0,1,3,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,120.0,0,1
HB-046159,City Hotel,0,7,2023,December,51,18,2023-12-18,1,2,2,0.0,1,BB,GBR,Direct,Direct,0,0,0,F,F,1,No Deposit,14.0,,0,Transient,170.0,0,2
HB-017538,Resort Hotel,0,38,2023,October,40,2,2023-10-02,4,7,2,2.0,0,BB,USA,Online TA,TA/TO,0,0,0,G,G,1,No Deposit,240.0,,0,Transient,115.0,0,1
HB-059520,City Hotel,1,247,2024,October,44,28,2024-10-28,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,110.0,0,0
HB-087843,City Hotel,0,101,2024,April,17,26,2024-04-26,0,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,35.0,,0,Transient-Party,98.0,0,0
HB-032511,Resort Hotel,0,1,2025,January,5,28,2025-01-28,0,1,2,0.0,0,HB,ESP,Direct,Direct,0,0,0,F,F,2,No Deposit,,,0,Transient,110.0,0,1
HB-116235,City Hotel,0,170,2025,July,29,15,2025-07-15,1,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,0
HB-078089,City Hotel,1,40,2023,October,43,24,2023-10-24,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Contract,96.3,0,2
HB-005052,Resort Hotel,0,183,2024,April,16,16,2024-04-16,1,1,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,B,0,No Deposit,298.0,,0,Transient-Party,85.0,0,0
HB-114426,City Hotel,0,235,2025,June,25,20,2025-06-20,0,2,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,127.13,1,0
HB-096540,City Hotel,0,11,2024,September,36,2,2024-09-02,0,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,124.0,0,1
HB-019603,Resort Hotel,0,4,2023,December,52,27,2023-12-27,1,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,330.0,,0,Transient-Party,25.0,0,1
HB-021355,Resort Hotel,0,0,2024,February,9,26,2024-02-26,0,1,2,0.0,0,BB,CHE,Direct,Direct,0,0,0,E,A,0,No Deposit,,,0,Transient,50.0,0,0
HB-094141,City Hotel,0,301,2024,July,31,30,2024-07-30,1,1,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-089227,City Hotel,0,116,2024,May,20,18,2024-05-18,0,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,F,0,No Deposit,9.0,,0,Transient,105.3,0,1
HB-091134,City Hotel,0,256,2024,June,24,15,2024-06-15,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,0
HB-070857,City Hotel,1,53,2025,June,26,23,2025-06-23,1,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.67,0,0
HB-090226,City Hotel,0,56,2024,June,22,1,2024-06-01,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,3,No Deposit,9.0,,0,Transient,140.4,0,1
HB-032221,Resort Hotel,0,40,2025,January,3,16,2025-01-16,1,2,1,0.0,0,Undefined,ESP,Groups,Direct,0,0,0,A,E,0,No Deposit,,,0,Transient-Party,55.0,0,0
HB-081208,City Hotel,0,12,2023,December,49,5,2023-12-05,1,1,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,55.0,0,1
HB-047740,City Hotel,1,9,2024,March,9,2,2024-03-02,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,1,No Deposit,210.0,,0,Transient-Party,55.0,0,0
HB-014017,Resort Hotel,0,7,2024,July,27,6,2024-07-06,0,1,1,0.0,0,BB,,Corporate,Corporate,0,0,18,A,F,0,No Deposit,,204.0,0,Transient,73.0,0,2
HB-008357,Resort Hotel,1,44,2024,September,39,23,2024-09-23,2,4,2,1.0,0,HB,PRT,Direct,Direct,0,0,0,F,F,1,No Deposit,250.0,,0,Transient,182.25,0,2
HB-101116,City Hotel,0,0,2024,November,45,5,2024-11-05,2,1,1,0.0,0,BB,SWE,Direct,Direct,0,0,0,A,A,2,No Deposit,,,0,Transient,150.0,0,0
HB-100452,City Hotel,0,216,2024,October,43,23,2024-10-23,2,3,0,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient,83.83,0,3
HB-061059,City Hotel,1,510,2024,December,48,1,2024-12-01,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-077214,City Hotel,1,31,2023,October,41,15,2023-10-15,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,D,D,0,No Deposit,9.0,,0,Transient,111.0,0,1
HB-104127,City Hotel,0,22,2025,January,1,2,2025-01-02,1,3,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,1
HB-014258,Resort Hotel,0,17,2023,October,42,22,2023-10-22,1,3,1,0.0,0,BB,,Direct,Direct,0,0,0,D,F,0,No Deposit,,,0,Transient,45.0,0,1
HB-053586,City Hotel,1,121,2024,June,26,24,2024-06-24,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,90.0,0,0
HB-060939,City Hotel,1,12,2024,November,48,26,2024-11-26,2,1,3,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,1,No Deposit,14.0,,0,Transient,180.33,0,2
HB-118017,City Hotel,0,190,2025,August,32,7,2025-08-07,1,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.5,0,0
HB-024589,Resort Hotel,0,113,2024,May,21,25,2024-05-25,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,E,0,No Deposit,251.0,,0,Transient,59.0,0,0
HB-115585,City Hotel,0,224,2025,July,27,3,2025-07-03,1,4,2,2.0,0,HB,ITA,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,9.0,,0,Transient,179.1,0,0
HB-114677,City Hotel,0,44,2025,June,25,17,2025-06-17,2,6,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,100.7,0,1
HB-064285,City Hotel,1,96,2025,March,10,4,2025-03-04,1,1,1,0.0,0,BB,HKG,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,95.0,0,0
HB-077427,City Hotel,0,19,2023,October,40,6,2023-10-06,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,1,0,0,A,D,0,No Deposit,82.0,,0,Transient-Party,80.0,0,0
HB-056691,City Hotel,1,203,2024,September,37,10,2024-09-10,2,1,2,0.0,0,BB,CRI,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.9,0,0
HB-068153,City Hotel,1,8,2025,May,20,13,2025-05-13,2,3,2,2.0,0,BB,ITA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,254.0,0,0
HB-117865,City Hotel,0,197,2025,August,32,5,2025-08-05,2,4,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-093889,City Hotel,0,175,2024,July,30,24,2024-07-24,2,2,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient-Party,123.25,0,1
HB-039867,Resort Hotel,0,308,2025,August,34,24,2025-08-24,2,5,1,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,115.0,,0,Transient,125.3,0,1
HB-106903,City Hotel,0,49,2025,March,9,2,2025-03-02,0,3,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,77.0,0,0
HB-109797,City Hotel,0,202,2025,April,16,14,2025-04-14,1,2,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,1
HB-000857,Resort Hotel,1,74,2023,August,31,1,2023-08-01,2,5,2,2.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,0,No Deposit,250.0,,0,Transient,177.14,0,0
HB-081740,City Hotel,1,109,2024,February,8,21,2024-02-21,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,44,Transient,75.0,0,0
HB-058143,City Hotel,1,206,2024,October,40,6,2024-10-06,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,102.85,0,0
HB-017941,Resort Hotel,0,5,2023,October,43,26,2023-10-26,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,94.0,0,Transient,37.0,0,0
HB-080578,City Hotel,0,1,2024,September,37,15,2024-09-15,0,2,2,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,2,No Deposit,,40.0,0,Transient,75.0,0,0
HB-014714,Resort Hotel,1,259,2023,September,37,17,2023-09-17,0,3,2,0.0,0,BB,GBR,Groups,Corporate,0,1,0,A,A,0,Non Refund,,223.0,0,Transient,40.05,0,0
HB-080419,City Hotel,1,34,2023,December,49,8,2023-12-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,0,Transient,90.0,0,0
HB-078436,City Hotel,0,5,2023,October,41,12,2023-10-12,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,1,A,A,0,No Deposit,1.0,,0,Transient-Party,138.0,0,0
HB-061882,City Hotel,1,239,2024,December,52,27,2024-12-27,2,10,2,0.0,0,BB,MEX,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,78.77,0,0
HB-075190,City Hotel,1,292,2023,August,31,5,2023-08-05,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-118882,City Hotel,0,457,2025,August,35,25,2025-08-25,0,2,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,6.0,,0,Transient-Party,95.5,0,1
HB-055905,City Hotel,1,102,2024,August,34,24,2024-08-24,0,4,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,150.3,0,0
HB-042465,City Hotel,0,55,2023,September,36,6,2023-09-06,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,75.0,0,0
HB-046412,City Hotel,1,148,2023,December,52,31,2023-12-31,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,98,Transient,77.5,0,0
HB-069347,City Hotel,1,186,2025,May,22,30,2025-05-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,130.0,0,0
HB-106570,City Hotel,0,1,2025,February,9,25,2025-02-25,1,1,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.0,0,1
HB-075650,City Hotel,1,290,2023,August,31,3,2023-08-03,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-069346,City Hotel,1,186,2025,May,22,30,2025-05-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,130.0,0,0
HB-054634,City Hotel,1,379,2024,July,29,21,2024-07-21,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-035842,Resort Hotel,0,110,2025,April,18,29,2025-04-29,2,2,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,171.0,,0,Transient,81.2,0,0
HB-091764,City Hotel,0,235,2024,June,26,24,2024-06-24,0,2,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,61,Transient-Party,65.0,0,1
HB-080728,City Hotel,0,0,2023,November,47,22,2023-11-22,1,0,2,0.0,0,BB,MAR,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,89.0,0,0
HB-064806,City Hotel,1,129,2025,March,11,16,2025-03-16,0,3,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.85,0,1
HB-051634,City Hotel,1,65,2024,May,21,23,2024-05-23,1,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,2,No Deposit,14.0,,0,Transient-Party,85.0,0,0
HB-052081,City Hotel,1,14,2024,May,22,30,2024-05-30,1,0,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.35,0,0
HB-014967,Resort Hotel,0,0,2023,November,46,18,2023-11-18,0,1,2,0.0,0,BB,PRT,Direct,Direct,1,0,1,A,D,0,No Deposit,,,0,Transient,43.0,0,0
HB-053310,City Hotel,1,290,2024,June,25,17,2024-06-17,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,108,Transient-Party,72.0,0,0
HB-022931,Resort Hotel,0,1,2024,April,15,9,2024-04-09,0,1,2,0.0,0,BB,PRT,Complementary,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient,0.0,0,1
HB-035566,Resort Hotel,0,105,2025,April,17,25,2025-04-25,0,2,2,0.0,0,HB,AUT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,241.0,,0,Transient,76.81,0,1
HB-041332,City Hotel,1,39,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,101.5,0,0
HB-031104,Resort Hotel,0,0,2024,December,50,14,2024-12-14,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,1,No Deposit,,388.0,0,Transient,30.0,0,0
HB-004325,Resort Hotel,1,162,2024,March,10,4,2024-03-04,6,15,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,96.0,,0,Transient,82.0,0,0
HB-035869,Resort Hotel,0,126,2025,May,18,2,2025-05-02,0,2,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,G,0,No Deposit,6.0,,0,Contract,84.0,1,1
HB-023492,Resort Hotel,0,0,2025,January,1,4,2025-01-04,0,0,2,0.0,0,BB,PRT,Direct,TA/TO,1,0,2,A,D,1,No Deposit,,,0,Transient,0.0,0,0
HB-071240,City Hotel,1,135,2025,June,27,30,2025-06-30,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,30.0,,0,Transient,130.0,0,0
HB-089329,City Hotel,0,76,2024,May,20,17,2024-05-17,0,3,1,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,G,0,No Deposit,9.0,,0,Transient,126.9,0,0
HB-019582,Resort Hotel,0,47,2023,December,51,23,2023-12-23,1,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,88.0,1,0
HB-080267,City Hotel,0,58,2023,November,46,13,2023-11-13,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,79.2,0,1
HB-059293,City Hotel,1,21,2024,October,43,26,2024-10-26,0,2,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,110.0,0,1
HB-043795,City Hotel,0,29,2023,September,38,24,2023-09-24,2,5,1,0.0,0,BB,AGO,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,170.0,0,1
HB-058209,City Hotel,1,196,2024,October,41,8,2024-10-08,1,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,122.4,0,0
HB-046259,City Hotel,0,20,2023,December,52,28,2023-12-28,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,7.0,,0,Transient,70.42,0,0
HB-076484,City Hotel,1,414,2023,December,49,5,2023-12-05,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-003870,Resort Hotel,1,28,2024,February,5,1,2024-02-01,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,46.4,0,2
HB-042771,City Hotel,0,2,2023,September,36,10,2023-09-10,0,1,1,0.0,0,BB,FRA,Corporate,Corporate,0,0,0,A,A,1,No Deposit,,68.0,0,Transient-Party,90.0,0,0
HB-105767,City Hotel,0,55,2025,February,7,12,2025-02-12,2,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,2
HB-104260,City Hotel,0,128,2025,January,2,6,2025-01-06,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,B,A,3,No Deposit,9.0,,0,Transient,82.44,0,0
HB-071156,City Hotel,1,91,2025,June,26,28,2025-06-28,0,4,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,0
HB-082616,City Hotel,0,0,2024,January,1,2,2024-01-02,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,95.0,0,0
HB-060235,City Hotel,1,277,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-043671,City Hotel,1,13,2023,September,38,22,2023-09-22,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,124.0,0,2
HB-109049,City Hotel,0,0,2025,April,14,4,2025-04-04,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,103.0,,0,Transient,95.0,0,0
HB-040684,City Hotel,1,34,2023,August,31,5,2023-08-05,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-007067,Resort Hotel,0,305,2024,July,29,18,2024-07-18,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,314.0,,0,Transient-Party,116.57,0,1
HB-076859,City Hotel,1,239,2023,October,42,17,2023-10-17,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-118149,City Hotel,0,7,2025,August,33,12,2025-08-12,2,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,180.0,0,1
HB-077446,City Hotel,0,0,2023,September,37,17,2023-09-17,0,1,2,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,A,1,No Deposit,,46.0,0,Transient,0.0,0,0
HB-076896,City Hotel,1,238,2023,September,38,18,2023-09-18,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,8.0,,0,Transient,89.25,0,2
HB-100402,City Hotel,0,21,2024,October,43,26,2024-10-26,0,2,1,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,95.48,0,1
HB-093144,City Hotel,0,87,2024,July,29,17,2024-07-17,1,0,3,0.0,0,BB,SLV,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,137.7,0,2
HB-065580,City Hotel,1,75,2025,April,14,5,2025-04-05,0,4,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,132.0,,0,Transient-Party,85.0,0,0
HB-078179,City Hotel,1,93,2023,December,52,26,2023-12-26,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Contract,106.2,0,1
HB-119241,City Hotel,0,205,2025,August,35,27,2025-08-27,2,3,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,0
HB-114992,City Hotel,0,1,2025,June,26,25,2025-06-25,2,3,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,152.0,0,1
HB-063583,City Hotel,1,21,2025,February,7,14,2025-02-14,0,4,3,0.0,0,BB,TWN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,134.3,0,0
HB-017804,Resort Hotel,0,16,2023,October,42,21,2023-10-21,0,1,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,86.0,0,1
HB-029850,Resort Hotel,0,84,2024,October,44,31,2024-10-31,2,5,1,1.0,0,BB,FIN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,33.26,0,1
HB-098305,City Hotel,0,35,2024,September,39,25,2024-09-25,2,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,2
HB-031264,Resort Hotel,0,0,2024,December,51,20,2024-12-20,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,62.0,1,0
HB-079117,City Hotel,0,6,2023,October,42,20,2023-10-20,0,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,129.0,1,3
HB-015670,Resort Hotel,1,468,2024,May,19,12,2024-05-12,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,249.0,,0,Transient-Party,67.0,0,0
HB-055560,City Hotel,0,228,2024,August,33,16,2024-08-16,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,118.9,1,1
HB-088391,City Hotel,0,2,2024,May,18,4,2024-05-04,0,1,1,0.0,0,BB,PRT,Aviation,Corporate,0,0,0,A,A,0,No Deposit,,153.0,0,Transient,95.0,0,0
HB-055492,City Hotel,1,94,2024,August,33,14,2024-08-14,2,2,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,152.1,0,0
HB-022483,Resort Hotel,0,72,2024,June,25,17,2024-06-17,2,4,2,0.0,0,BB,PRT,Direct,Direct,1,0,1,A,A,2,No Deposit,250.0,,0,Transient,119.0,0,0
HB-115161,City Hotel,0,57,2025,June,26,27,2025-06-27,0,5,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,108.0,0,0
HB-025466,Resort Hotel,0,173,2024,June,25,21,2024-06-21,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,241.0,,0,Transient,64.24,0,2
HB-073318,City Hotel,1,301,2025,August,34,18,2025-08-18,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,121.5,0,2
HB-088398,City Hotel,0,2,2024,October,40,6,2024-10-06,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,3,D,E,0,No Deposit,,219.0,0,Transient,110.0,0,1
HB-028149,Resort Hotel,0,77,2024,September,38,19,2024-09-19,1,2,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,242.0,,0,Transient,180.67,1,1
HB-049841,City Hotel,1,270,2024,April,16,20,2024-04-20,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,187,Transient-Party,62.8,0,0
HB-091282,City Hotel,0,2,2024,June,25,18,2024-06-18,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,129.0,0,1
HB-091982,City Hotel,0,3,2024,June,26,27,2024-06-27,1,1,1,0.0,0,SC,ESP,Offline TA/TO,GDS,0,0,0,A,A,0,No Deposit,195.0,,0,Transient,124.0,0,0
HB-083809,City Hotel,0,66,2024,February,6,11,2024-02-11,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,58.0,0,1
HB-067704,City Hotel,1,162,2025,May,19,6,2025-05-06,2,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,80.0,0,0
HB-063720,City Hotel,1,149,2025,February,8,18,2025-02-18,2,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.4,0,1
HB-039383,Resort Hotel,0,273,2025,August,32,7,2025-08-07,3,7,2,0.0,0,HB,FRA,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient-Party,214.8,1,1
HB-007536,Resort Hotel,1,162,2024,August,33,13,2024-08-13,2,5,2,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,235.57,0,0
HB-042333,City Hotel,0,0,2023,September,36,5,2023-09-05,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,143.0,0,1
HB-105185,City Hotel,0,77,2025,January,5,30,2025-01-30,1,2,3,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,133.74,1,3
HB-077072,City Hotel,0,219,2023,September,36,4,2023-09-04,0,1,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,108.0,0,0
HB-015751,Resort Hotel,0,3,2023,July,30,30,2023-07-30,0,2,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,195.0,1,3
HB-053056,City Hotel,1,74,2024,June,24,15,2024-06-15,0,2,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,186.3,0,0
HB-042423,City Hotel,1,61,2023,September,36,5,2023-09-05,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-044506,City Hotel,0,97,2023,October,40,7,2023-10-07,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-017336,Resort Hotel,0,0,2023,October,40,5,2023-10-05,1,0,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,47.0,1,0
HB-103426,City Hotel,0,53,2024,December,51,17,2024-12-17,2,5,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,2
HB-050112,City Hotel,1,71,2024,April,17,23,2024-04-23,2,3,3,0.0,0,BB,CHL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,124.95,0,2
HB-034234,Resort Hotel,0,88,2025,March,11,11,2025-03-11,2,5,2,0.0,0,BB,DEU,Groups,TA/TO,0,0,0,A,A,2,No Deposit,177.0,,0,Transient-Party,34.0,0,0
HB-025613,Resort Hotel,0,144,2024,June,26,25,2024-06-25,3,6,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,8.0,,0,Transient,95.6,1,0
HB-078486,City Hotel,0,22,2023,October,40,6,2023-10-06,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Contract,115.0,0,2
HB-011071,Resort Hotel,1,133,2025,April,16,16,2025-04-16,1,0,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,60.0,0,0
HB-109273,City Hotel,0,75,2025,April,14,5,2025-04-05,0,4,1,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,85.0,0,0
HB-035983,Resort Hotel,0,221,2025,April,18,30,2025-04-30,2,5,2,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,83.43,0,0
HB-102966,City Hotel,0,4,2024,December,50,9,2024-12-09,0,1,1,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,105.0,0,0
HB-014220,Resort Hotel,0,0,2024,December,49,5,2024-12-05,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,6,A,D,0,No Deposit,,113.0,0,Transient,30.0,0,0
HB-082360,City Hotel,1,94,2024,March,10,4,2024-03-04,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,154.0,,28,Transient,80.0,0,0
HB-031664,Resort Hotel,0,1,2025,January,1,2,2025-01-02,1,0,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-071005,City Hotel,1,83,2025,June,26,27,2025-06-27,0,2,3,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,190.0,0,1
HB-038456,Resort Hotel,0,96,2025,July,28,12,2025-07-12,2,5,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,216.14,0,1
HB-017578,Resort Hotel,0,12,2023,October,41,12,2023-10-12,1,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,72.0,1,1
HB-017822,Resort Hotel,0,292,2023,October,42,21,2023-10-21,0,2,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,208.0,,0,Transient-Party,70.0,0,0
HB-038267,Resort Hotel,0,176,2025,July,27,6,2025-07-06,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,147.0,,0,Transient,93.54,0,0
HB-054431,City Hotel,1,172,2024,July,29,15,2024-07-15,2,5,2,1.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,112.32,0,0
HB-054000,City Hotel,1,140,2024,July,27,4,2024-07-04,1,5,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,116.45,0,0
HB-030859,Resort Hotel,0,1,2024,December,49,6,2024-12-06,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,490.0,0,Transient,49.5,1,0
HB-106212,City Hotel,0,12,2025,February,8,21,2025-02-21,0,2,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,80.0,0,1
HB-075003,City Hotel,1,122,2023,July,27,9,2023-07-09,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Transient-Party,76.5,0,1
HB-086381,City Hotel,0,2,2024,March,13,31,2024-03-31,0,2,1,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,D,G,1,No Deposit,9.0,,0,Transient,147.0,0,0
HB-069217,City Hotel,1,204,2025,May,22,27,2025-05-27,2,2,2,0.0,0,BB,GRC,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,138.6,0,2
HB-025508,Resort Hotel,0,17,2024,June,26,30,2024-06-30,0,0,2,2.0,0,BB,BEL,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient-Party,0.0,0,0
HB-086394,City Hotel,0,73,2024,March,13,29,2024-03-29,0,4,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,82.45,0,1
HB-032843,Resort Hotel,0,1,2025,February,6,6,2025-02-06,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,87.0,1,0
HB-000516,Resort Hotel,0,26,2023,July,29,18,2023-07-18,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,132.6,1,0
HB-074231,City Hotel,1,278,2023,July,29,22,2023-07-22,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Contract,62.0,0,0
HB-061463,City Hotel,1,26,2024,December,50,12,2024-12-12,2,5,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,154.0,,0,Transient,75.0,0,0
HB-055350,City Hotel,1,398,2024,August,32,11,2024-08-11,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-064826,City Hotel,1,74,2025,March,12,17,2025-03-17,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,106.2,0,1
HB-114636,City Hotel,0,219,2025,June,25,20,2025-06-20,0,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.5,0,2
HB-089815,City Hotel,0,35,2024,May,21,22,2024-05-22,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.9,0,0
HB-117964,City Hotel,0,183,2025,August,32,6,2025-08-06,2,5,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,148.5,0,0
HB-045208,City Hotel,1,50,2023,October,43,24,2023-10-24,0,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,146.0,0,0
HB-073990,City Hotel,1,286,2023,July,30,30,2023-07-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-084584,City Hotel,0,43,2024,February,9,26,2024-02-26,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.5,1,1
HB-054331,City Hotel,1,0,2024,July,28,13,2024-07-13,0,1,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,208.0,0,0
HB-089177,City Hotel,0,2,2024,May,20,15,2024-05-15,2,2,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,81.75,0,0
HB-020217,Resort Hotel,0,0,2024,January,3,19,2024-01-19,0,1,2,0.0,0,BB,AUT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,45.0,0,0
HB-045262,City Hotel,0,69,2023,October,43,25,2023-10-25,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,58,Transient-Party,85.67,0,0
HB-046087,City Hotel,1,106,2023,December,49,9,2023-12-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,57,Transient,75.0,0,0
HB-102701,City Hotel,0,38,2024,December,49,2,2024-12-02,0,2,2,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,A,0,No Deposit,,,9,Transient-Party,85.0,0,0
HB-003165,Resort Hotel,0,8,2023,November,47,20,2023-11-20,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,E,1,No Deposit,,,0,Transient,37.0,1,2
HB-084693,City Hotel,0,36,2024,March,9,1,2024-03-01,0,1,1,0.0,0,BB,DEU,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,185.0,0,Transient-Party,86.5,0,0
HB-098100,City Hotel,0,141,2024,September,39,23,2024-09-23,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,163.8,0,1
HB-049551,City Hotel,1,75,2024,April,15,14,2024-04-14,0,3,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,15.0,,0,Transient,157.6,0,0
HB-023523,Resort Hotel,0,89,2024,April,16,16,2024-04-16,4,8,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,69.0,,0,Transient,59.5,0,0
HB-111106,City Hotel,0,322,2025,May,19,5,2025-05-05,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,75.0,0,0
HB-110878,City Hotel,0,27,2025,April,18,29,2025-04-29,2,2,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,137.0,0,3
HB-024360,Resort Hotel,0,84,2024,May,19,12,2024-05-12,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Contract,72.75,0,0
HB-080763,City Hotel,1,176,2024,April,15,9,2024-04-09,1,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,21.0,,0,Transient,125.0,0,0
HB-031702,Resort Hotel,0,68,2024,December,52,29,2024-12-29,2,5,2,0.0,0,Undefined,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,464.0,,0,Transient,94.29,0,1
HB-037488,Resort Hotel,0,145,2025,June,25,18,2025-06-18,1,0,2,0.0,0,BB,NZL,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,171.0,,0,Transient,83.7,1,0
HB-051452,City Hotel,1,211,2024,May,21,20,2024-05-20,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,111,Transient,100.0,0,0
HB-099546,City Hotel,0,36,2024,October,41,13,2024-10-13,0,1,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient-Party,102.6,0,2
HB-084347,City Hotel,0,9,2024,February,8,22,2024-02-22,1,1,2,0.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,83.0,,0,Transient,86.8,0,0
HB-085665,City Hotel,0,51,2024,March,11,16,2024-03-16,0,4,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,15.0,,0,Transient,92.82,0,1
HB-035167,Resort Hotel,0,351,2025,April,15,8,2025-04-08,2,5,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,D,D,0,No Deposit,298.0,,0,Transient-Party,84.0,0,0
HB-019969,Resort Hotel,0,4,2024,January,2,10,2024-01-10,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-070365,City Hotel,1,95,2025,June,24,15,2025-06-15,1,3,2,0.0,0,SC,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-079077,City Hotel,1,24,2023,November,44,5,2023-11-05,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,8.0,,0,Transient,117.0,0,0
HB-058769,City Hotel,1,36,2024,October,42,16,2024-10-16,1,0,1,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,1
HB-052568,City Hotel,1,56,2024,June,23,8,2024-06-08,0,1,2,0.0,0,BB,PRT,Offline TA/TO,Corporate,0,0,0,A,A,0,No Deposit,191.0,,0,Transient-Party,120.0,0,0
HB-078064,City Hotel,0,3,2023,October,39,1,2023-10-01,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,0
HB-116857,City Hotel,0,125,2025,July,30,23,2025-07-23,2,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient-Party,146.17,0,1
HB-069704,City Hotel,1,173,2025,June,23,4,2025-06-04,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,120.0,0,0
HB-062303,City Hotel,1,129,2025,January,2,8,2025-01-08,2,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,D,D,0,Non Refund,,,0,Transient,67.0,0,0
HB-016089,Resort Hotel,0,175,2023,July,31,31,2023-07-31,4,10,2,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,128.0,,0,Contract,104.55,0,1
HB-007396,Resort Hotel,1,98,2024,August,32,7,2024-08-07,2,3,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,241.0,0,0
HB-105418,City Hotel,0,5,2025,February,6,6,2025-02-06,1,1,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,98.0,0,1
HB-096180,City Hotel,0,100,2024,August,35,26,2024-08-26,2,2,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,150.3,0,1
HB-089295,City Hotel,0,77,2024,May,20,16,2024-05-16,1,3,3,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,B,0,No Deposit,22.0,,0,Transient,105.4,0,1
HB-093883,City Hotel,0,80,2024,July,30,24,2024-07-24,2,2,2,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,121.0,,0,Transient,72.25,0,0
HB-083226,City Hotel,0,0,2024,January,3,20,2024-01-20,1,4,2,0.0,0,SC,FRA,Direct,Direct,0,0,0,D,D,5,No Deposit,,,0,Transient,78.4,0,0
HB-109240,City Hotel,0,139,2025,April,14,6,2025-04-06,0,3,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,3
HB-013506,Resort Hotel,1,84,2025,August,33,17,2025-08-17,2,5,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,270.0,0,2
HB-071024,City Hotel,1,35,2025,June,26,27,2025-06-27,0,3,1,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,123.0,0,2
HB-053079,City Hotel,1,239,2024,June,24,15,2024-06-15,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,80,Transient,112.2,0,0
HB-088516,City Hotel,0,91,2024,May,18,4,2024-05-04,0,4,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,28.0,,0,Transient,105.0,0,0
HB-060521,City Hotel,1,72,2024,November,46,13,2024-11-13,2,0,2,0.0,0,SC,MAR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,3
HB-104361,City Hotel,0,4,2025,January,2,10,2025-01-10,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,405.0,0,Transient-Party,70.0,0,0
HB-061650,City Hotel,1,101,2024,December,51,21,2024-12-21,2,5,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,122.0,0,2
HB-061831,City Hotel,1,50,2024,December,52,27,2024-12-27,0,1,2,1.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,111.6,0,0
HB-037545,Resort Hotel,0,213,2025,June,24,15,2025-06-15,2,5,2,1.0,1,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,143.0,,0,Transient,72.88,0,0
HB-040314,City Hotel,0,20,2023,July,29,22,2023-07-22,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-083164,City Hotel,0,2,2024,January,3,20,2024-01-20,0,2,2,0.0,0,SC,AGO,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,81.0,0,0
HB-044840,City Hotel,0,43,2023,October,41,13,2023-10-13,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,63.0,,0,Transient-Party,75.0,0,0
HB-099970,City Hotel,0,9,2024,October,42,17,2024-10-17,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,155.0,0,1
HB-061823,City Hotel,1,314,2024,December,52,26,2024-12-26,3,6,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,68.66,0,0
HB-060275,City Hotel,1,277,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-004047,Resort Hotel,1,140,2024,February,7,12,2024-02-12,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,50.0,0,0
HB-042611,City Hotel,0,0,2023,September,36,8,2023-09-08,0,1,2,0.0,0,SC,AGO,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,115.0,0,0
HB-029197,Resort Hotel,0,39,2024,October,43,23,2024-10-23,1,0,2,0.0,0,BB,GBR,Offline TA/TO,Corporate,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,47.0,0,0
HB-062954,City Hotel,1,61,2025,January,4,25,2025-01-25,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,326.0,,0,Transient,80.0,0,0
HB-027689,Resort Hotel,0,5,2024,September,36,3,2024-09-03,2,2,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,170.1,0,0
HB-019869,Resort Hotel,0,0,2024,January,1,6,2024-01-06,0,1,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,E,0,No Deposit,,,0,Transient,61.0,0,0
HB-067202,City Hotel,1,104,2025,April,18,29,2025-04-29,1,1,3,0.0,0,HB,BEL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,189.0,0,0
HB-015735,Resort Hotel,0,204,2023,July,30,27,2023-07-27,1,4,3,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,175.0,,0,Transient,131.4,0,1
HB-016380,Resort Hotel,0,0,2023,August,34,26,2023-08-26,0,1,1,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,153.0,0,0
HB-061990,City Hotel,1,22,2024,December,52,29,2024-12-29,2,3,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,198.88,0,2
HB-029570,Resort Hotel,0,5,2024,October,44,29,2024-10-29,1,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,38.0,0,2
HB-071029,City Hotel,1,5,2025,June,26,27,2025-06-27,0,3,2,1.0,0,BB,RUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,186.67,0,0
HB-072052,City Hotel,1,183,2025,July,29,18,2025-07-18,0,4,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,0
HB-005531,Resort Hotel,0,199,2024,May,18,2,2024-05-02,1,1,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient,85.0,0,0
HB-117686,City Hotel,0,127,2025,August,31,1,2025-08-01,2,5,2,0.0,1,SC,BRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,71.1,0,1
HB-061621,City Hotel,1,21,2024,December,51,19,2024-12-19,1,4,1,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,67.32,0,0
HB-050529,City Hotel,1,70,2024,May,18,2,2024-05-02,1,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,16.0,,0,Transient,80.75,0,0
HB-059272,City Hotel,1,124,2024,October,43,25,2024-10-25,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,104.4,0,0
HB-048797,City Hotel,1,80,2024,March,13,30,2024-03-30,2,8,2,0.0,0,SC,ARG,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,73.1,0,0
HB-110587,City Hotel,0,1,2025,June,24,15,2025-06-15,2,3,1,0.0,0,BB,PRT,Aviation,Corporate,1,0,1,D,D,0,No Deposit,,153.0,0,Transient,110.0,0,1
HB-046115,City Hotel,0,110,2023,December,49,9,2023-12-09,0,4,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,69,Transient-Party,70.0,0,0
HB-039078,Resort Hotel,0,3,2025,August,32,6,2025-08-06,1,0,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,151.99,0,1
HB-021225,Resort Hotel,0,3,2024,May,20,19,2024-05-19,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,113.0,0,Transient,53.0,1,0
HB-074365,City Hotel,1,276,2023,July,29,20,2023-07-20,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Contract,62.0,0,0
HB-025366,Resort Hotel,0,161,2024,June,25,17,2024-06-17,2,4,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,72.0,0,2
HB-072105,City Hotel,1,11,2025,July,30,21,2025-07-21,0,1,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.0,0,1
HB-063974,City Hotel,1,180,2025,February,9,25,2025-02-25,1,1,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.6,0,1
HB-108456,City Hotel,0,34,2025,March,12,21,2025-03-21,2,5,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,B,A,1,No Deposit,14.0,,0,Transient,93.82,0,0
HB-070485,City Hotel,1,150,2025,June,25,17,2025-06-17,2,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,120.0,0,0
HB-003928,Resort Hotel,1,4,2024,February,6,7,2024-02-07,2,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,39.0,0,0
HB-032331,Resort Hotel,0,0,2025,January,4,22,2025-01-22,1,0,2,0.0,0,BB,NLD,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,60.0,0,0
HB-057933,City Hotel,0,281,2024,October,40,3,2024-10-03,1,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient-Party,108.8,0,0
HB-020412,Resort Hotel,0,1,2024,January,4,24,2024-01-24,2,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,E,2,No Deposit,240.0,,0,Transient,40.0,0,0
HB-053770,City Hotel,1,21,2024,June,26,29,2024-06-29,0,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,124.2,0,0
HB-098209,City Hotel,0,0,2024,September,39,25,2024-09-25,1,0,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,0
HB-046773,City Hotel,0,151,2024,January,3,19,2024-01-19,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,19.0,,63,Transient-Party,71.0,0,0
HB-102300,City Hotel,0,14,2024,November,48,25,2024-11-25,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,369.0,0,Transient-Party,76.0,1,0
HB-000340,Resort Hotel,0,97,2023,July,28,12,2023-07-12,2,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,90.95,0,0
HB-111951,City Hotel,0,58,2025,May,20,15,2025-05-15,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,129.6,0,1
HB-092750,City Hotel,0,141,2024,July,27,6,2024-07-06,1,4,1,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,107.95,0,0
HB-076706,City Hotel,1,9,2024,October,42,19,2024-10-19,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,5,48,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-005598,Resort Hotel,1,49,2024,May,18,3,2024-05-03,2,7,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,314.0,,0,Transient,52.56,0,1
HB-064407,City Hotel,1,608,2025,March,10,9,2025-03-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-076809,City Hotel,0,0,2023,August,32,12,2023-08-12,0,1,1,0.0,0,BB,BRA,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,138.0,0,0
HB-002354,Resort Hotel,0,5,2023,October,41,10,2023-10-10,1,1,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,101.5,0,2
HB-117036,City Hotel,0,465,2025,July,30,26,2025-07-26,0,3,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,1
HB-027694,Resort Hotel,0,34,2024,August,35,31,2024-08-31,2,5,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,170.0,1,3
HB-066623,City Hotel,1,393,2025,April,17,22,2025-04-22,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-033494,Resort Hotel,0,6,2025,February,9,24,2025-02-24,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,E,0,No Deposit,,,0,Transient,61.2,0,1
HB-012796,Resort Hotel,1,182,2025,July,29,17,2025-07-17,1,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,181.88,0,1
HB-017528,Resort Hotel,0,4,2023,October,41,12,2023-10-12,1,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,146.0,,0,Transient,37.0,0,0
HB-111834,City Hotel,0,6,2025,May,20,14,2025-05-14,2,1,1,0.0,0,BB,KOR,Groups,Corporate,0,0,0,A,A,0,No Deposit,,169.0,0,Transient-Party,110.0,0,0
HB-112604,City Hotel,0,208,2025,May,21,24,2025-05-24,0,2,1,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,91.5,0,0
HB-044050,City Hotel,0,83,2023,September,39,30,2023-09-30,0,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,26.0,,77,Transient-Party,112.2,0,0
HB-041785,City Hotel,0,53,2023,August,34,24,2023-08-24,1,1,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-031459,Resort Hotel,0,61,2024,December,51,22,2024-12-22,2,5,2,0.0,0,Undefined,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,464.0,,0,Transient,114.29,0,0
HB-047797,City Hotel,0,61,2024,March,10,4,2024-03-04,0,2,2,0.0,0,SC,HUN,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,89.5,0,0
HB-082679,City Hotel,0,23,2024,January,1,2,2024-01-02,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,26.0,,0,Transient-Party,109.0,0,0
HB-071170,City Hotel,1,120,2025,June,26,29,2025-06-29,0,1,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,3,No Deposit,9.0,,0,Transient,171.0,0,0
HB-039660,Resort Hotel,0,187,2025,August,33,14,2025-08-14,3,8,2,0.0,1,HB,PRT,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,233.64,0,4
HB-081866,City Hotel,1,178,2024,April,17,28,2024-04-28,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,46,Transient,110.0,0,0
HB-099437,City Hotel,0,180,2024,October,41,10,2024-10-10,1,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,234.0,,0,Transient-Party,120.0,0,0
HB-111621,City Hotel,0,122,2025,May,19,11,2025-05-11,0,2,1,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,117.0,0,0
HB-090062,City Hotel,0,81,2024,May,22,30,2024-05-30,1,1,1,0.0,0,BB,DEU,Groups,TA/TO,0,0,0,A,A,1,No Deposit,,,25,Transient-Party,120.0,0,0
HB-002429,Resort Hotel,1,21,2023,October,41,13,2023-10-13,0,3,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,117.0,0,0
HB-021788,Resort Hotel,0,2,2024,March,10,10,2024-03-10,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,E,0,No Deposit,,,0,Transient,40.0,0,0
HB-036889,Resort Hotel,0,174,2025,May,22,28,2025-05-28,2,2,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,410.0,,0,Transient,63.0,0,0
HB-076096,City Hotel,1,364,2023,October,42,16,2023-10-16,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-011881,Resort Hotel,1,241,2025,June,23,2,2025-06-02,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,93.6,0,1
HB-083893,City Hotel,0,139,2024,February,6,11,2024-02-11,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Transient,62.0,0,1
HB-102242,City Hotel,0,62,2024,November,47,20,2024-11-20,2,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-007417,Resort Hotel,1,22,2024,August,32,8,2024-08-08,1,3,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,231.0,0,0
HB-062074,City Hotel,1,46,2025,January,1,1,2025-01-01,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,65.0,0,0
HB-032974,Resort Hotel,0,1,2025,February,7,10,2025-02-10,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-034803,Resort Hotel,0,3,2025,April,14,2,2025-04-02,2,1,2,0.0,0,BB,NPL,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient,85.0,0,1
HB-030843,Resort Hotel,0,22,2024,December,49,6,2024-12-06,0,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,0.0,0,1
HB-109989,City Hotel,0,181,2025,April,16,17,2025-04-17,1,2,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,6,No Deposit,9.0,,0,Transient,130.5,0,3
HB-041941,City Hotel,1,15,2023,August,34,27,2023-08-27,0,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,80.0,0,1
HB-086153,City Hotel,0,113,2024,March,13,25,2024-03-25,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,58.0,0,1
HB-107932,City Hotel,0,169,2025,March,11,16,2025-03-16,1,3,2,0.0,0,BB,LUX,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,96.9,0,0
HB-073867,City Hotel,1,314,2023,August,34,27,2023-08-27,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-070668,City Hotel,1,25,2025,June,25,20,2025-06-20,0,4,2,2.0,0,BB,POL,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,250.0,0,0
HB-032389,Resort Hotel,0,2,2025,January,4,23,2025-01-23,1,1,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,34.0,0,0
HB-015065,Resort Hotel,0,1,2023,July,29,19,2023-07-19,1,0,1,0.0,0,BB,PRT,Direct,Direct,1,0,1,A,E,0,No Deposit,,,0,Transient,92.1,1,0
HB-113543,City Hotel,0,218,2025,June,23,7,2025-06-07,0,2,2,0.0,0,SC,ARG,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,79.35,0,1
HB-086034,City Hotel,0,5,2024,March,12,23,2024-03-23,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,133.0,0,0
HB-045212,City Hotel,1,50,2023,October,43,24,2023-10-24,0,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,146.0,0,0
HB-074014,City Hotel,1,293,2023,August,31,6,2023-08-06,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-064215,City Hotel,1,28,2025,March,9,2,2025-03-02,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,95.0,0,0
HB-042329,City Hotel,0,10,2023,September,36,5,2023-09-05,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Group,85.0,0,1
HB-108643,City Hotel,0,184,2025,March,13,26,2025-03-26,2,3,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,83.0,,0,Transient,70.72,0,0
HB-000454,Resort Hotel,1,35,2023,July,28,16,2023-07-16,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,135.0,0,0
HB-118489,City Hotel,0,101,2025,August,34,18,2025-08-18,1,2,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,A,A,2,No Deposit,14.0,,0,Transient,93.42,0,1
HB-023169,Resort Hotel,0,87,2024,April,15,10,2024-04-10,2,5,2,0.0,0,HB,GBR,Groups,Direct,0,0,1,D,D,0,No Deposit,273.0,,0,Transient-Party,36.22,0,0
HB-106243,City Hotel,0,22,2025,February,8,22,2025-02-22,0,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.0,0,1
HB-119017,City Hotel,0,104,2025,August,35,27,2025-08-27,1,0,3,1.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,162.0,0,1
HB-001968,Resort Hotel,0,84,2023,September,38,24,2023-09-24,2,8,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,40.0,,0,Contract,83.8,0,1
HB-006924,Resort Hotel,1,284,2024,July,28,11,2024-07-11,4,10,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,115.93,0,2
HB-116919,City Hotel,0,152,2025,July,30,24,2025-07-24,1,2,1,0.0,0,BB,CHE,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,75.6,0,0
HB-047332,City Hotel,1,44,2024,February,7,17,2024-02-17,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,44.0,,3,Transient,75.0,0,0
HB-041326,City Hotel,0,39,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-093751,City Hotel,0,97,2024,July,29,21,2024-07-21,2,3,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,141.3,0,2
HB-063300,City Hotel,1,71,2025,February,6,6,2025-02-06,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,93.6,0,1
HB-051794,City Hotel,1,323,2024,May,21,26,2024-05-26,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-040900,City Hotel,0,16,2023,August,32,8,2023-08-08,2,2,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,B,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-092625,City Hotel,0,0,2024,July,27,6,2024-07-06,0,3,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,145.67,0,0
HB-055867,City Hotel,1,3,2024,August,34,23,2024-08-23,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,163.67,0,0
HB-025001,Resort Hotel,0,96,2024,June,23,8,2024-06-08,0,4,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,107.0,0,0
HB-001891,Resort Hotel,1,92,2023,September,38,19,2023-09-19,4,10,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,125.71,0,0
HB-018291,Resort Hotel,0,0,2023,November,46,15,2023-11-15,1,0,2,0.0,0,BB,CHE,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,59.0,1,0
HB-085246,City Hotel,0,8,2024,March,10,9,2024-03-09,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,100.0,0,0
HB-116629,City Hotel,0,53,2025,July,30,22,2025-07-22,0,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,160.0,0,2
HB-085182,City Hotel,0,21,2024,March,10,8,2024-03-08,0,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,73.03,0,1
HB-047127,City Hotel,0,34,2024,February,6,8,2024-02-08,1,4,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,73.9,0,0
HB-067031,City Hotel,1,286,2025,April,17,27,2025-04-27,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,175,Transient,120.0,0,0
HB-016843,Resort Hotel,0,254,2023,September,37,12,2023-09-12,2,2,2,0.0,0,BB,CN,Groups,TA/TO,0,0,0,A,A,1,No Deposit,15.0,,0,Transient-Party,36.0,0,0
HB-113468,City Hotel,0,33,2025,June,23,6,2025-06-06,0,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,110.2,0,1
HB-109977,City Hotel,0,4,2025,April,16,17,2025-04-17,1,2,2,1.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,164.0,0,1
HB-022669,Resort Hotel,0,34,2024,March,13,27,2024-03-27,2,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,52.36,0,1
HB-004523,Resort Hotel,0,146,2024,March,12,22,2024-03-22,2,8,3,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,1,No Deposit,314.0,,0,Transient,85.72,0,1
HB-024694,Resort Hotel,0,0,2024,May,22,30,2024-05-30,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,60.0,0,0
HB-003472,Resort Hotel,0,113,2023,December,51,18,2023-12-18,0,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,I,0,No Deposit,240.0,,0,Transient,0.0,0,2
HB-096194,City Hotel,0,198,2024,August,34,25,2024-08-25,2,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,22.0,,0,Transient-Party,72.25,0,0
HB-116722,City Hotel,0,423,2025,July,30,22,2025-07-22,1,1,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,122.4,0,1
HB-005235,Resort Hotel,0,191,2024,April,17,22,2024-04-22,1,2,2,0.0,0,Undefined,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,85.33,0,0
HB-094103,City Hotel,0,188,2024,July,30,28,2024-07-28,0,3,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient-Party,80.75,0,0
HB-116455,City Hotel,0,93,2025,July,29,18,2025-07-18,0,3,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,139.5,0,0
HB-009606,Resort Hotel,1,244,2024,December,51,19,2024-12-19,1,2,3,2.0,0,HB,PRT,Direct,Direct,0,0,0,H,H,1,No Deposit,250.0,,0,Transient,144.57,0,0
HB-000070,Resort Hotel,1,63,2023,July,27,3,2023-07-03,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,82.0,0,2
HB-047739,City Hotel,1,8,2024,March,9,2,2024-03-02,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,94.0,,0,Transient-Party,56.0,0,0
HB-084849,City Hotel,0,6,2024,March,9,3,2024-03-03,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,87.0,0,2
HB-031788,Resort Hotel,0,0,2025,January,5,30,2025-01-30,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,270.0,0,Transient,35.0,0,0
HB-054297,City Hotel,1,174,2024,July,28,11,2024-07-11,1,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.95,0,0
HB-054467,City Hotel,0,210,2024,July,29,16,2024-07-16,2,5,2,0.0,0,SC,CHL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,87.18,0,1
HB-024579,Resort Hotel,0,106,2024,May,20,19,2024-05-19,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,46.75,0,1
HB-055997,City Hotel,1,179,2024,August,35,26,2024-08-26,1,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.5,0,0
HB-098544,City Hotel,0,36,2024,September,39,24,2024-09-24,2,5,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,7.0,,0,Transient,177.77,0,1
HB-003562,Resort Hotel,0,44,2023,December,51,23,2023-12-23,2,5,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,6.0,,0,Transient,73.4,0,0
HB-049545,City Hotel,1,70,2024,April,15,14,2024-04-14,1,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.25,0,0
HB-085876,City Hotel,0,43,2024,March,12,20,2024-03-20,2,1,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.2,0,1
HB-069900,City Hotel,1,42,2025,June,23,8,2025-06-08,0,3,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,2
HB-084150,City Hotel,0,99,2024,February,8,19,2024-02-19,0,1,1,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,A,0,No Deposit,,67.0,0,Transient-Party,81.0,0,0
HB-083642,City Hotel,0,12,2024,February,6,7,2024-02-07,2,0,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,0,No Deposit,14.0,,0,Transient,136.25,0,1
HB-081262,City Hotel,0,14,2023,December,49,5,2023-12-05,2,1,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient-Party,64.0,0,0
HB-073307,City Hotel,1,121,2025,August,34,18,2025-08-18,1,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.0,0,0
HB-058870,City Hotel,1,45,2024,October,42,17,2024-10-17,1,0,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,2
HB-113440,City Hotel,0,30,2025,June,23,6,2025-06-06,0,2,1,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,423.0,,0,Transient,130.0,0,0
HB-096448,City Hotel,0,180,2024,August,35,27,2024-08-27,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,22.0,,0,Transient,90.95,0,0
HB-043950,City Hotel,1,88,2023,September,39,26,2023-09-26,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-024323,Resort Hotel,0,116,2024,May,20,13,2024-05-13,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,90.0,0,3
HB-065165,City Hotel,1,160,2025,March,13,26,2025-03-26,2,1,2,1.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.8,0,0
HB-043867,City Hotel,0,192,2023,September,39,25,2023-09-25,2,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,0.0,0,0
HB-046905,City Hotel,0,55,2024,January,4,25,2024-01-25,1,3,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,58.94,0,1
HB-109493,City Hotel,0,202,2025,April,15,9,2025-04-09,2,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,B,B,3,No Deposit,9.0,,0,Transient,215.1,1,1
HB-029199,Resort Hotel,0,9,2024,October,43,21,2024-10-21,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,F,0,No Deposit,240.0,,0,Transient,90.0,0,2
HB-071197,City Hotel,1,133,2025,June,26,29,2025-06-29,0,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,113.7,0,0
HB-013104,Resort Hotel,1,357,2025,July,31,31,2025-07-31,1,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,138.38,0,3
HB-096966,City Hotel,0,150,2024,September,37,9,2024-09-09,0,2,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,89.4,0,1
HB-053083,City Hotel,1,188,2024,June,24,15,2024-06-15,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,39,Transient,130.0,0,0
HB-006246,Resort Hotel,1,237,2024,May,22,30,2024-05-30,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,66.34,0,2
HB-009735,Resort Hotel,1,44,2024,December,1,30,2024-12-30,0,2,2,1.0,0,HB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,241.0,,0,Transient,302.11,0,0
HB-077875,City Hotel,1,1,2023,September,39,30,2023-09-30,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,1,1,0,A,A,0,Non Refund,50.0,,0,Transient,98.1,0,0
HB-075539,City Hotel,1,355,2023,October,40,7,2023-10-07,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-017261,Resort Hotel,1,277,2023,October,40,5,2023-10-05,4,10,2,0.0,0,HB,GBR,Groups,Direct,0,1,0,D,D,0,Non Refund,273.0,,0,Transient,78.5,0,0
HB-000831,Resort Hotel,1,18,2023,July,31,31,2023-07-31,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,149.7,0,1
HB-091040,City Hotel,0,2,2024,June,24,14,2024-06-14,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.0,0,1
HB-002245,Resort Hotel,0,6,2023,October,40,7,2023-10-07,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,49.01,0,0
HB-085920,City Hotel,0,5,2024,March,12,23,2024-03-23,0,1,2,0.0,0,BB,MEX,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,112.0,0,0
HB-099164,City Hotel,0,141,2024,October,40,6,2024-10-06,1,3,2,0.0,0,BB,AUT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,80.75,0,0
HB-088134,City Hotel,0,56,2024,April,18,30,2024-04-30,0,1,3,0.0,0,BB,ARG,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,142.1,0,0
HB-068623,City Hotel,1,69,2025,May,21,19,2025-05-19,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,99.0,0,0
HB-040200,City Hotel,0,0,2023,July,28,15,2023-07-15,2,5,2,0.0,0,SC,PRT,Direct,Direct,0,0,0,F,A,4,No Deposit,,,0,Transient,0.0,0,0
HB-009909,Resort Hotel,1,86,2025,January,4,20,2025-01-20,2,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,42.0,0,1
HB-106899,City Hotel,0,20,2025,March,9,2,2025-03-02,0,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,1
HB-070371,City Hotel,1,130,2025,June,24,15,2025-06-15,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,122.4,0,0
HB-051077,City Hotel,1,309,2024,May,20,13,2024-05-13,1,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,215,Transient-Party,101.0,0,0
HB-024811,Resort Hotel,0,101,2024,May,22,30,2024-05-30,1,4,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,59.6,0,0
HB-074250,City Hotel,1,377,2023,October,43,29,2023-10-29,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-114635,City Hotel,0,216,2025,June,25,20,2025-06-20,0,5,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,3,No Deposit,9.0,,0,Transient,109.0,0,1
HB-008243,Resort Hotel,0,243,2024,September,38,19,2024-09-19,2,5,1,0.0,0,FB,POL,Offline TA/TO,TA/TO,0,0,0,A,C,1,No Deposit,315.0,,0,Transient,71.9,0,1
HB-032923,Resort Hotel,0,7,2025,February,6,9,2025-02-09,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient-Party,43.0,0,2
HB-068614,City Hotel,1,105,2025,May,21,19,2025-05-19,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-032119,Resort Hotel,0,41,2025,January,3,17,2025-01-17,0,0,1,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,A,A,3,No Deposit,,,0,Transient-Party,0.0,0,0
HB-031559,Resort Hotel,0,0,2024,December,52,29,2024-12-29,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,85.67,0,1
HB-102001,City Hotel,0,16,2024,November,47,18,2024-11-18,1,2,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,104.67,0,0
HB-087484,City Hotel,0,2,2024,April,16,17,2024-04-17,2,2,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,61.38,0,0
HB-002432,Resort Hotel,0,32,2023,October,41,14,2023-10-14,0,1,2,0.0,0,HB,FRA,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,,0,Transient,117.0,1,0
HB-118938,City Hotel,0,457,2025,August,35,25,2025-08-25,0,2,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,6.0,,0,Transient-Party,95.5,0,1
HB-035576,Resort Hotel,0,195,2025,April,16,20,2025-04-20,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,73.79,0,1
HB-080982,City Hotel,1,10,2023,December,48,3,2023-12-03,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,D,D,0,No Deposit,7.0,,0,Transient,72.21,0,0
HB-102490,City Hotel,0,0,2024,November,48,29,2024-11-29,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-012319,Resort Hotel,1,209,2025,June,26,24,2025-06-24,2,5,3,0.0,0,HB,ESP,Direct,Direct,0,0,0,A,A,1,No Deposit,250.0,,0,Transient,162.12,0,0
HB-061825,City Hotel,1,314,2024,December,52,26,2024-12-26,3,6,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,68.66,0,0
HB-100509,City Hotel,0,2,2024,October,43,25,2024-10-25,0,4,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,109.38,0,1
HB-101072,City Hotel,0,43,2024,November,44,1,2024-11-01,0,5,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,68.0,0,0
HB-104850,City Hotel,0,0,2025,January,4,22,2025-01-22,1,0,2,0.0,0,SC,JPN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,152.0,,0,Transient,58.31,0,0
HB-023106,Resort Hotel,0,45,2024,April,15,14,2024-04-14,0,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,64.0,0,1
HB-072848,City Hotel,1,478,2025,August,32,8,2025-08-08,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-044662,City Hotel,0,80,2023,October,41,9,2023-10-09,0,2,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,12.0,,50,Transient-Party,108.0,0,0
HB-063569,City Hotel,1,226,2025,February,7,14,2025-02-14,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.0,0,2
HB-094647,City Hotel,0,1,2024,August,32,7,2024-08-07,1,0,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.0,0,1
HB-000640,Resort Hotel,0,36,2023,July,30,24,2023-07-24,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,134.0,0,0
HB-088764,City Hotel,0,2,2024,June,24,15,2024-06-15,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,2,D,D,0,No Deposit,,219.0,0,Transient,119.0,1,1
HB-095606,City Hotel,0,0,2024,August,34,20,2024-08-20,0,1,1,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,92.17,0,0
HB-106621,City Hotel,0,43,2025,February,9,26,2025-02-26,2,0,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,3
HB-098459,City Hotel,0,28,2024,September,39,28,2024-09-28,0,2,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,163.0,0,1
HB-107556,City Hotel,0,20,2025,March,11,13,2025-03-13,1,1,1,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,254.0,,0,Transient-Party,178.0,0,0
HB-039784,Resort Hotel,0,2,2025,August,35,25,2025-08-25,1,2,2,0.0,0,HB,PAK,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,314.0,,0,Transient-Party,243.81,1,0
HB-006779,Resort Hotel,0,305,2024,July,27,1,2024-07-01,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,40.0,,0,Contract,59.8,0,0
HB-051542,City Hotel,1,49,2024,May,21,21,2024-05-21,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.9,0,0
HB-044766,City Hotel,0,79,2023,October,41,10,2023-10-10,1,1,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-096227,City Hotel,0,61,2024,August,35,28,2024-08-28,2,0,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,82.45,0,0
HB-091999,City Hotel,0,87,2024,June,26,26,2024-06-26,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,77.29,0,0
HB-082437,City Hotel,0,20,2023,December,52,27,2023-12-27,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,2,No Deposit,28.0,,0,Transient,58.0,0,0
HB-035747,Resort Hotel,0,110,2025,April,18,29,2025-04-29,1,1,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,115.0,0,1
HB-081933,City Hotel,1,278,2024,August,32,11,2024-08-11,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,65.0,0,0
HB-041599,City Hotel,0,6,2023,August,33,19,2023-08-19,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,106.0,0,2
HB-042470,City Hotel,0,55,2023,September,36,6,2023-09-06,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,B,0,No Deposit,1.0,,0,Transient-Party,75.0,0,0
HB-021099,Resort Hotel,0,0,2024,February,7,17,2024-02-17,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,F,0,No Deposit,,,0,Transient,75.0,1,0
HB-084227,City Hotel,0,6,2024,February,8,20,2024-02-20,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient-Party,80.0,0,1
HB-058898,City Hotel,1,605,2024,October,42,17,2024-10-17,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-098966,City Hotel,0,0,2024,October,40,6,2024-10-06,0,1,2,0.0,0,BB,AUT,Direct,Direct,0,0,0,A,B,0,No Deposit,,,0,Transient-Party,150.0,0,3
HB-084581,City Hotel,0,22,2024,February,9,26,2024-02-26,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,72.64,0,1
HB-104900,City Hotel,0,8,2025,January,4,24,2025-01-24,0,1,1,0.0,0,BB,ITA,Online TA,GDS,0,0,0,A,A,0,No Deposit,195.0,,0,Transient,98.0,0,2
HB-045940,City Hotel,0,84,2023,November,48,27,2023-11-27,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,56.0,0,0
HB-105615,City Hotel,0,0,2025,February,7,10,2025-02-10,0,2,3,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,8.0,,0,Transient,272.0,0,0
HB-078912,City Hotel,0,16,2023,October,41,15,2023-10-15,1,3,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,65.0,0,0
HB-106396,City Hotel,0,2,2025,February,9,24,2025-02-24,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,K,0,No Deposit,9.0,,0,Transient,98.0,0,2
HB-096889,City Hotel,0,53,2024,September,36,4,2024-09-04,2,4,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,128.1,0,2
HB-069446,City Hotel,1,80,2025,May,22,31,2025-05-31,0,2,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-009647,Resort Hotel,1,2,2024,December,52,23,2024-12-23,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,1,No Deposit,154.0,,0,Transient,27.0,0,0
HB-094862,City Hotel,0,6,2024,August,32,7,2024-08-07,2,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,148.0,0,0
HB-080770,City Hotel,1,180,2024,April,15,13,2024-04-13,0,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,21.0,,38,Transient,125.0,0,0
HB-064322,City Hotel,1,10,2025,March,10,5,2025-03-05,3,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,102.43,0,0
HB-043271,City Hotel,0,14,2023,September,37,17,2023-09-17,0,2,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,C,0,No Deposit,20.0,,0,Transient-Party,0.0,0,0
HB-067108,City Hotel,1,17,2025,April,18,28,2025-04-28,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.5,0,1
HB-030700,Resort Hotel,0,0,2024,November,48,30,2024-11-30,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,0
HB-043908,City Hotel,1,87,2023,September,39,25,2023-09-25,2,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-057525,City Hotel,1,23,2024,September,39,26,2024-09-26,1,3,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.0,0,1
HB-051349,City Hotel,1,316,2024,May,20,19,2024-05-19,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,59.0,0,0
HB-092870,City Hotel,0,12,2024,July,28,9,2024-07-09,2,2,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,85.0,0,0
HB-109268,City Hotel,0,75,2025,April,14,5,2025-04-05,0,4,1,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,85.0,0,0
HB-094254,City Hotel,0,272,2024,July,30,28,2024-07-28,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,90.1,0,0
HB-110889,City Hotel,0,28,2025,April,18,29,2025-04-29,2,2,2,0.0,0,SC,SYR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,137.0,0,3
HB-092827,City Hotel,0,159,2024,July,27,6,2024-07-06,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,82.19,0,1
HB-039957,Resort Hotel,0,81,2025,August,35,27,2025-08-27,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Group,135.0,0,0
HB-035486,Resort Hotel,0,1,2025,April,17,21,2025-04-21,1,2,1,0.0,0,BB,DEU,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient-Party,74.6,0,0
HB-020208,Resort Hotel,0,16,2024,January,2,13,2024-01-13,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-102172,City Hotel,0,46,2024,November,47,23,2024-11-23,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,86.4,0,2
HB-107459,City Hotel,0,66,2025,March,11,10,2025-03-10,1,2,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,154.0,,0,Transient-Party,80.0,0,1
HB-045359,City Hotel,0,53,2023,October,43,26,2023-10-26,1,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,94.5,0,1
HB-088078,City Hotel,0,73,2024,April,17,28,2024-04-28,0,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.9,0,0
HB-103364,City Hotel,0,83,2024,December,51,18,2024-12-18,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-087106,City Hotel,0,69,2024,April,15,10,2024-04-10,2,2,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,D,D,3,No Deposit,9.0,,0,Transient,117.18,0,1
HB-104320,City Hotel,0,162,2025,January,2,7,2025-01-07,2,2,1,0.0,0,BB,AUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,2
HB-052014,City Hotel,1,95,2024,May,22,29,2024-05-29,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,65.0,0,0
HB-008713,Resort Hotel,1,10,2024,October,41,10,2024-10-10,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,394.0,0,Transient-Party,41.4,0,0
HB-023923,Resort Hotel,0,98,2024,May,18,4,2024-05-04,0,4,3,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,66.45,0,2
HB-118980,City Hotel,0,16,2025,August,35,25,2025-08-25,1,2,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,D,F,1,No Deposit,,,0,Transient,160.0,0,2
HB-023162,Resort Hotel,0,190,2024,April,15,10,2024-04-10,2,5,1,0.0,0,HB,GBR,Groups,Direct,0,0,0,A,A,0,No Deposit,273.0,,0,Transient-Party,47.9,0,0
HB-098623,City Hotel,0,254,2024,September,39,29,2024-09-29,0,3,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,95.4,0,1
HB-055316,City Hotel,1,405,2024,August,32,10,2024-08-10,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,65.0,0,0
HB-006775,Resort Hotel,0,0,2024,July,27,1,2024-07-01,2,7,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient,83.0,0,2
HB-074718,City Hotel,0,0,2024,April,14,7,2024-04-07,0,1,1,0.0,0,BB,PRT,Complementary,Direct,1,0,21,A,D,0,No Deposit,,45.0,0,Transient,0.0,0,1
HB-099095,City Hotel,0,7,2024,October,40,4,2024-10-04,0,5,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,1
HB-095657,City Hotel,0,3,2024,August,34,20,2024-08-20,1,1,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,128.0,0,1
HB-062072,City Hotel,1,46,2025,January,1,1,2025-01-01,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,65.0,0,0
HB-053112,City Hotel,1,239,2024,June,24,15,2024-06-15,0,2,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,80,Transient,90.6,0,0
HB-108910,City Hotel,0,0,2025,March,13,30,2025-03-30,1,3,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,91.15,0,1
HB-113390,City Hotel,0,8,2025,June,23,6,2025-06-06,0,1,1,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,150.0,0,0
HB-061673,City Hotel,1,531,2024,December,51,22,2024-12-22,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-028184,Resort Hotel,0,178,2024,September,38,17,2024-09-17,2,5,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,143.86,0,0
HB-036674,Resort Hotel,0,114,2025,May,21,22,2025-05-22,1,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,122.0,1,1
HB-026326,Resort Hotel,0,138,2024,July,30,23,2024-07-23,2,4,3,0.0,0,Undefined,ESP,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient,318.0,0,1
HB-044647,City Hotel,0,80,2023,October,41,9,2023-10-09,0,2,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,12.0,,50,Transient-Party,108.0,0,0
HB-055940,City Hotel,1,412,2024,August,34,25,2024-08-25,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-035498,Resort Hotel,0,47,2025,April,16,17,2025-04-17,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,50.85,0,0
HB-047340,City Hotel,1,44,2024,February,7,17,2024-02-17,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,44.0,,3,Transient,75.0,0,0
HB-105588,City Hotel,0,24,2025,February,6,5,2025-02-05,2,5,1,0.0,0,BB,MAR,Groups,TA/TO,0,0,0,A,A,1,No Deposit,,407.0,0,Transient-Party,75.0,0,0
HB-112889,City Hotel,0,149,2025,May,22,27,2025-05-27,2,1,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,112.0,0,0
HB-002344,Resort Hotel,0,4,2023,October,41,9,2023-10-09,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,70.4,0,1
HB-086225,City Hotel,0,122,2024,March,13,27,2024-03-27,2,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,26.0,,0,Transient-Party,107.0,0,1
HB-080553,City Hotel,1,58,2023,December,52,27,2023-12-27,2,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,B,B,0,No Deposit,9.0,,0,Transient-Party,77.35,0,1
HB-005730,Resort Hotel,0,236,2024,May,19,12,2024-05-12,0,3,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,315.0,,0,Transient-Party,48.0,0,0
HB-082024,City Hotel,1,305,2024,October,40,1,2024-10-01,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,35.0,,17,Transient,100.0,0,0
HB-098719,City Hotel,0,180,2024,October,40,1,2024-10-01,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.9,0,1
HB-073482,City Hotel,1,175,2025,August,34,23,2025-08-23,2,5,2,1.0,0,BB,FRA,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,155.0,0,1
HB-056023,City Hotel,1,162,2024,August,35,27,2024-08-27,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.3,0,0
HB-067152,City Hotel,1,286,2025,April,18,29,2025-04-29,1,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.8,0,0
HB-043982,City Hotel,1,89,2023,September,39,27,2023-09-27,1,0,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-037911,Resort Hotel,0,318,2025,June,25,19,2025-06-19,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Contract,84.8,0,0
HB-073861,City Hotel,1,314,2023,August,34,27,2023-08-27,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-084402,City Hotel,0,2,2025,June,26,26,2025-06-26,1,1,2,0.0,0,BB,AGO,Direct,Direct,1,0,1,A,D,4,No Deposit,14.0,,0,Transient,146.67,0,1
HB-094424,City Hotel,0,12,2024,August,31,1,2024-08-01,1,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,K,0,No Deposit,9.0,,0,Transient,119.0,0,2
HB-080334,City Hotel,1,33,2023,December,49,9,2023-12-09,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,44.0,,0,Transient,110.0,0,0
HB-110201,City Hotel,0,133,2025,April,16,19,2025-04-19,0,4,2,0.0,0,BB,ISL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,390.0,,0,Transient-Party,124.0,0,0
HB-006355,Resort Hotel,0,250,2024,June,23,4,2024-06-04,4,6,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Transient,79.84,0,0
HB-031838,Resort Hotel,0,24,2025,January,1,2,2025-01-02,1,5,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-038402,Resort Hotel,0,136,2025,July,28,10,2025-07-10,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,181.43,0,2
HB-113202,City Hotel,0,130,2025,June,22,1,2025-06-01,0,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,147.0,0,0
HB-073121,City Hotel,1,507,2025,August,33,15,2025-08-15,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-092848,City Hotel,0,35,2024,July,28,11,2024-07-11,1,1,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,118.15,0,1
HB-025008,Resort Hotel,0,94,2024,June,23,6,2024-06-06,1,5,2,1.0,0,HB,POL,Direct,Direct,0,0,0,F,F,2,No Deposit,250.0,,0,Transient,188.4,0,2
HB-023375,Resort Hotel,0,14,2024,April,17,22,2024-04-22,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient-Party,80.0,0,1
HB-039183,Resort Hotel,0,240,2025,August,32,6,2025-08-06,2,2,2,1.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,410.0,,0,Transient-Party,147.13,0,1
HB-035011,Resort Hotel,0,152,2025,April,14,5,2025-04-05,2,4,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,D,D,1,No Deposit,,223.0,0,Transient-Party,60.0,0,1
HB-110739,City Hotel,0,106,2025,April,17,26,2025-04-26,1,4,1,0.0,0,BB,NOR,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,100.8,0,1
HB-058114,City Hotel,1,454,2024,October,40,6,2024-10-06,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-052740,City Hotel,1,152,2024,June,24,10,2024-06-10,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,132.9,0,0
HB-114110,City Hotel,0,13,2025,June,24,13,2025-06-13,0,4,2,0.0,0,BB,AUS,Groups,TA/TO,0,0,0,A,A,3,No Deposit,229.0,,0,Transient-Party,90.0,0,1
HB-052838,City Hotel,1,154,2024,June,24,12,2024-06-12,2,1,2,2.0,0,BB,USA,Online TA,TA/TO,0,0,0,F,F,2,No Deposit,9.0,,0,Transient,189.9,0,0
HB-047108,City Hotel,0,35,2024,February,6,7,2024-02-07,2,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.3,0,1
HB-102552,City Hotel,0,154,2024,November,48,30,2024-11-30,0,1,2,0.0,0,BB,LUX,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,16.0,,0,Transient,68.0,0,0
HB-038230,Resort Hotel,0,0,2025,July,28,11,2025-07-11,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient-Party,135.0,0,1
HB-071915,City Hotel,1,476,2025,July,29,15,2025-07-15,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,91.33,0,0
HB-081204,City Hotel,0,25,2023,December,49,4,2023-12-04,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,10.0,,0,Transient,69.0,0,0
HB-052084,City Hotel,1,12,2024,May,22,30,2024-05-30,1,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,97.02,0,0
HB-055329,City Hotel,1,182,2024,August,32,10,2024-08-10,2,7,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,112.2,0,2
HB-110764,City Hotel,0,12,2025,April,18,30,2025-04-30,1,0,1,0.0,0,BB,FIN,Direct,Direct,0,0,0,G,G,0,No Deposit,14.0,,0,Transient,285.0,0,3
HB-026861,Resort Hotel,0,22,2024,August,33,12,2024-08-12,0,1,1,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,195.58,0,1
HB-013356,Resort Hotel,1,306,2025,August,33,11,2025-08-11,0,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,167.18,0,2
HB-103836,City Hotel,0,127,2024,December,52,29,2024-12-29,1,3,2,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,84.15,0,0
HB-087768,City Hotel,0,170,2024,April,17,23,2024-04-23,2,1,2,0.0,0,BB,RUS,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,2.0,,48,Transient-Party,70.0,0,1
HB-016983,Resort Hotel,0,92,2023,September,37,13,2023-09-13,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,E,F,0,No Deposit,240.0,,0,Transient,99.0,0,2
HB-009314,Resort Hotel,1,100,2024,November,46,11,2024-11-11,2,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,C,1,No Deposit,240.0,,0,Transient,37.8,0,3
HB-090717,City Hotel,0,118,2024,June,23,6,2024-06-06,1,3,1,0.0,0,BB,NLD,Offline TA/TO,Corporate,0,0,0,A,D,1,No Deposit,191.0,,0,Transient-Party,110.0,0,0
HB-101167,City Hotel,0,165,2024,November,45,5,2024-11-05,1,1,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.1,0,2
HB-081497,City Hotel,0,61,2025,July,28,8,2025-07-08,0,1,2,1.0,0,BB,PRT,Complementary,Direct,1,0,14,B,A,1,No Deposit,,45.0,0,Transient,0.0,0,2
HB-007957,Resort Hotel,1,171,2024,September,36,4,2024-09-04,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient,139.0,0,0
HB-025414,Resort Hotel,0,203,2024,June,26,24,2024-06-24,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient-Party,72.0,0,1
HB-113811,City Hotel,0,27,2025,June,24,9,2025-06-09,1,2,2,0.0,0,SC,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,135.33,0,0
HB-086140,City Hotel,0,130,2024,March,13,25,2024-03-25,1,2,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Contract,102.58,0,1
HB-048593,City Hotel,1,161,2024,March,13,25,2024-03-25,1,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,101,Transient,130.0,0,0
HB-113735,City Hotel,0,212,2025,June,24,9,2025-06-09,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,1
HB-000498,Resort Hotel,0,38,2023,July,29,17,2023-07-17,1,2,2,1.0,0,HB,PRT,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,192.0,0,1
HB-095966,City Hotel,0,33,2024,August,34,24,2024-08-24,0,3,2,2.0,0,BB,RUS,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,207.9,0,2
HB-082151,City Hotel,1,99,2024,February,8,19,2024-02-19,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,1,0,A,A,0,No Deposit,,67.0,0,Transient-Party,80.0,0,0
HB-018436,Resort Hotel,0,3,2024,May,21,23,2024-05-23,0,0,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,20.0,0,Transient,0.0,0,0
HB-015890,Resort Hotel,0,211,2023,August,31,3,2023-08-03,1,3,2,2.0,0,HB,PRT,Online TA,TA/TO,0,0,0,G,H,0,No Deposit,240.0,,0,Transient,256.0,0,2
HB-023748,Resort Hotel,0,0,2024,May,18,1,2024-05-01,1,0,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,,,0,Transient,115.0,0,1
HB-054528,City Hotel,1,1,2024,July,29,19,2024-07-19,0,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,139.0,0,1
HB-097485,City Hotel,0,247,2024,September,37,14,2024-09-14,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,115.2,1,2
HB-064640,City Hotel,1,113,2025,March,11,14,2025-03-14,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,16,Transient,85.0,0,0
HB-006395,Resort Hotel,0,323,2024,June,23,7,2024-06-07,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,40.0,,0,Contract,78.5,0,0
HB-018204,Resort Hotel,0,36,2023,November,45,7,2023-11-07,2,6,1,0.0,0,BB,USA,Corporate,Corporate,0,0,0,A,A,1,No Deposit,185.0,281.0,0,Transient-Party,36.0,0,0
HB-008405,Resort Hotel,1,339,2024,September,39,26,2024-09-26,3,6,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,15.0,,0,Transient,80.0,0,0
HB-068119,City Hotel,1,356,2025,May,20,13,2025-05-13,1,1,2,2.0,0,BB,BHR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,189.9,0,3
HB-031228,Resort Hotel,0,42,2024,December,51,17,2024-12-17,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-059631,City Hotel,1,75,2024,October,44,30,2024-10-30,2,0,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,105.0,0,0
HB-022086,Resort Hotel,0,3,2024,March,11,17,2024-03-17,0,1,1,0.0,0,BB,ESP,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,154.0,0,Transient,25.0,0,0
HB-080378,City Hotel,1,34,2023,December,49,8,2023-12-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,0,Transient,90.0,0,0
HB-069680,City Hotel,1,58,2025,June,23,3,2025-06-03,2,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,170.0,0,1
HB-003347,Resort Hotel,1,45,2023,December,49,5,2023-12-05,2,1,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,38.0,,0,Transient-Party,68.0,0,0
HB-049146,City Hotel,1,86,2024,April,14,6,2024-04-06,0,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,84.58,0,0
HB-061817,City Hotel,1,223,2024,December,52,26,2024-12-26,2,5,2,0.0,0,BB,USA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,69.09,0,0
HB-091158,City Hotel,0,256,2024,June,24,15,2024-06-15,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-088228,City Hotel,0,12,2024,May,18,2,2024-05-02,1,0,2,0.0,1,BB,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,141.0,0,2
HB-063103,City Hotel,1,36,2025,January,5,31,2025-01-31,0,4,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,81.09,0,0
HB-083190,City Hotel,0,9,2024,January,3,16,2024-01-16,2,6,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,61.5,0,0
HB-015581,Resort Hotel,0,55,2023,July,29,20,2023-07-20,2,5,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,142.86,1,0
HB-020244,Resort Hotel,0,0,2024,January,3,20,2024-01-20,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,109.0,0,Transient,30.0,0,0
HB-004274,Resort Hotel,1,138,2024,February,9,29,2024-02-29,3,7,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,40.5,0,1
HB-034180,Resort Hotel,0,0,2025,March,11,14,2025-03-14,0,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,,,0,Transient,80.0,0,1
HB-006370,Resort Hotel,1,3,2024,June,23,6,2024-06-06,1,0,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,G,0,No Deposit,,,0,Transient,65.0,0,0
HB-080360,City Hotel,0,7,2023,November,46,16,2023-11-16,1,0,1,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,91.0,0,2
HB-025797,Resort Hotel,0,173,2024,July,27,2,2024-07-02,4,6,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,143.0,,0,Transient,79.9,0,2
HB-112555,City Hotel,0,26,2025,May,21,21,2025-05-21,2,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,190.0,0,1
HB-026990,Resort Hotel,0,45,2024,August,33,14,2024-08-14,2,0,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,243.0,0,1
HB-054813,City Hotel,1,56,2024,July,30,27,2024-07-27,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.9,0,0
HB-052336,City Hotel,1,58,2024,June,23,3,2024-06-03,1,2,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,137.4,0,0
HB-015166,Resort Hotel,1,244,2023,September,35,2,2023-09-02,2,5,2,0.0,0,BB,IRL,Groups,TA/TO,0,24,0,A,A,0,No Deposit,96.0,,0,Transient-Party,8.0,0,0
HB-086713,City Hotel,0,5,2024,April,14,4,2024-04-04,1,3,1,0.0,0,BB,BEL,Aviation,Corporate,0,0,0,A,A,0,No Deposit,,153.0,0,Transient-Party,95.0,0,0
HB-105777,City Hotel,0,73,2025,February,7,12,2025-02-12,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,72.0,0,0
HB-054106,City Hotel,1,365,2024,July,27,7,2024-07-07,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,59.0,0,0
HB-065010,City Hotel,1,1,2025,March,12,22,2025-03-22,0,1,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.0,0,0
HB-002023,Resort Hotel,1,55,2023,September,39,27,2023-09-27,3,5,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,74.2,0,0
HB-061587,City Hotel,1,98,2024,December,51,17,2024-12-17,2,2,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,140.0,0,1
HB-019502,Resort Hotel,0,4,2023,December,51,21,2023-12-21,1,1,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,D,E,0,No Deposit,,,0,Transient,58.0,0,2
HB-061080,City Hotel,1,35,2024,December,48,1,2024-12-01,1,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,0
HB-042354,City Hotel,1,65,2023,September,36,5,2023-09-05,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-031773,Resort Hotel,0,1,2025,January,1,3,2025-01-03,0,3,1,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,43.0,0,0
HB-054182,City Hotel,1,13,2024,July,28,8,2024-07-08,0,1,2,0.0,0,SC,ISR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,137.0,0,0
HB-031500,Resort Hotel,0,79,2024,December,52,27,2024-12-27,0,3,2,1.0,0,HB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,314.0,,0,Transient,67.05,0,0
HB-101666,City Hotel,0,8,2024,November,46,14,2024-11-14,1,1,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,103.0,0,1
HB-109029,City Hotel,0,76,2025,April,14,2,2025-04-02,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-033766,Resort Hotel,0,0,2025,March,9,1,2025-03-01,0,2,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,57.0,0,0
HB-074856,City Hotel,1,185,2023,July,27,5,2023-07-05,3,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,0
HB-101425,City Hotel,0,92,2024,November,46,11,2024-11-11,0,1,2,0.0,0,BB,THA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,364.0,,0,Transient-Party,90.0,0,0
HB-013438,Resort Hotel,1,6,2025,August,33,15,2025-08-15,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient,190.0,0,1
HB-061280,City Hotel,1,15,2024,December,49,7,2024-12-07,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-068831,City Hotel,1,97,2025,May,21,21,2025-05-21,2,1,3,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,180.0,0,0
HB-104462,City Hotel,0,2,2025,January,3,13,2025-01-13,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,100.0,0,1
HB-055551,City Hotel,1,155,2024,August,33,16,2024-08-16,0,2,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.5,0,0
HB-099384,City Hotel,0,31,2024,October,41,9,2024-10-09,2,2,1,0.0,0,BB,DEU,Corporate,Corporate,0,0,0,A,A,1,No Deposit,,174.0,0,Transient,95.0,0,0
HB-079170,City Hotel,0,5,2023,October,40,4,2023-10-04,6,13,1,0.0,0,BB,BRA,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,93.0,0,Transient,95.0,0,1
HB-027612,Resort Hotel,0,1,2024,September,36,3,2024-09-03,0,1,2,0.0,0,BB,USA,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,154.0,0,1
HB-103687,City Hotel,0,140,2024,December,52,27,2024-12-27,0,3,2,2.0,0,BB,BRA,Online TA,TA/TO,0,0,0,F,G,0,No Deposit,7.0,,0,Transient,140.98,0,2
HB-065906,City Hotel,1,88,2025,April,15,9,2025-04-09,2,5,2,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,159.43,0,0
HB-019356,Resort Hotel,1,19,2023,December,52,30,2023-12-30,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,D,D,0,No Deposit,240.0,,0,Transient,99.0,0,0
HB-086501,City Hotel,0,72,2024,April,14,2,2024-04-02,1,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,96.3,0,1
HB-100291,City Hotel,0,219,2024,October,43,22,2024-10-22,2,2,2,0.0,0,BB,GRC,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.95,0,2
HB-019052,Resort Hotel,0,0,2024,February,6,10,2024-02-10,0,1,2,0.0,0,BB,PRT,Direct,Direct,1,0,6,A,D,0,No Deposit,,,0,Transient,48.0,1,1
HB-097460,City Hotel,0,40,2024,September,37,13,2024-09-13,0,4,1,0.0,0,BB,SWE,Groups,TA/TO,0,0,0,A,A,1,No Deposit,86.0,,0,Transient-Party,108.0,0,0
HB-068705,City Hotel,1,185,2025,May,21,20,2025-05-20,0,1,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.5,0,3
HB-045261,City Hotel,0,69,2023,October,43,25,2023-10-25,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,58,Transient-Party,85.67,0,0
HB-021366,Resort Hotel,0,3,2024,February,9,26,2024-02-26,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,330.0,,0,Transient-Party,40.0,0,0
HB-025055,Resort Hotel,0,46,2024,May,22,30,2024-05-30,4,10,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,147.0,,0,Transient,57.72,0,0
HB-014575,Resort Hotel,0,5,2023,October,43,28,2023-10-28,0,1,1,0.0,0,BB,,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,154.0,0,Transient,37.0,0,0
HB-027450,Resort Hotel,0,8,2024,August,35,26,2024-08-26,2,2,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,241.0,,0,Transient,141.91,0,1
HB-110575,City Hotel,0,8,2025,April,18,28,2025-04-28,0,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,144.0,0,1
HB-063085,City Hotel,1,63,2025,January,5,30,2025-01-30,1,1,1,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,77.76,0,0
HB-106326,City Hotel,0,30,2025,February,8,22,2025-02-22,0,2,1,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.0,0,1
HB-084708,City Hotel,0,7,2024,March,9,2,2024-03-02,0,1,1,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,86.0,0,1
HB-023273,Resort Hotel,0,24,2024,April,16,17,2024-04-17,2,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,81.0,1,1
HB-003187,Resort Hotel,0,78,2023,November,47,21,2023-11-21,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,342.0,0,Transient-Party,32.0,0,0
HB-011330,Resort Hotel,1,83,2025,May,18,3,2025-05-03,0,4,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,147.0,0,0
HB-092082,City Hotel,0,0,2024,June,26,28,2024-06-28,0,2,2,1.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,,,0,Transient,143.5,0,2
HB-061554,City Hotel,1,9,2024,December,51,16,2024-12-16,1,2,2,0.0,0,SC,IDN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,78.0,0,0
HB-018970,Resort Hotel,0,0,2023,November,48,28,2023-11-28,2,4,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,38.0,0,0
HB-057024,City Hotel,1,302,2024,September,38,16,2024-09-16,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,70,Transient,100.0,0,0
HB-011236,Resort Hotel,1,172,2025,April,18,29,2025-04-29,2,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,314.0,,0,Transient,97.71,0,0
HB-114668,City Hotel,0,186,2025,June,25,22,2025-06-22,0,3,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,166.5,0,2
HB-084209,City Hotel,0,15,2024,February,7,18,2024-02-18,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,196.0,,0,Transient-Party,86.0,0,0
HB-103893,City Hotel,0,207,2024,December,1,30,2024-12-30,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,C,0,No Deposit,104.0,,0,Transient,95.0,0,0
HB-106426,City Hotel,0,0,2025,February,9,24,2025-02-24,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,1,0,0,A,D,1,No Deposit,9.0,,0,Transient,12.0,0,0
HB-000433,Resort Hotel,0,57,2023,July,28,15,2023-07-15,0,2,2,0.0,0,FB,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,305.0,,0,Transient-Party,107.0,0,0
HB-115168,City Hotel,0,0,2025,July,27,2,2025-07-02,1,0,2,0.0,0,SC,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,123.0,0,0
HB-036820,Resort Hotel,0,272,2025,May,22,26,2025-05-26,2,2,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,A,A,2,No Deposit,250.0,,0,Transient,92.1,0,1
HB-016243,Resort Hotel,0,175,2023,August,33,17,2023-08-17,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,134.0,0,1
HB-006441,Resort Hotel,0,241,2024,June,24,11,2024-06-11,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient-Party,99.0,0,2
HB-001911,Resort Hotel,1,33,2023,September,38,21,2023-09-21,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,208.0,,0,Transient-Party,90.0,0,0
HB-035281,Resort Hotel,0,73,2025,April,16,15,2025-04-15,2,1,1,1.0,0,BB,IND,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,64.17,0,0
HB-113272,City Hotel,0,211,2025,June,22,1,2025-06-01,1,3,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,20.0,,0,Transient-Party,121.75,0,0
HB-094506,City Hotel,0,28,2024,August,31,4,2024-08-04,0,1,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,125.1,0,2
HB-018640,Resort Hotel,0,0,2024,November,47,21,2024-11-21,1,1,1,0.0,0,BB,PRT,Online TA,Direct,1,0,2,A,I,2,No Deposit,240.0,,0,Transient,55.0,0,0
HB-097839,City Hotel,0,14,2024,September,38,20,2024-09-20,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,129.0,0,1
HB-084418,City Hotel,0,2,2024,February,8,25,2024-02-25,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,69.0,0,0
HB-102450,City Hotel,0,5,2024,November,48,28,2024-11-28,1,0,1,0.0,0,BB,ESP,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,377.0,0,Transient-Party,77.0,0,0
HB-017553,Resort Hotel,0,0,2023,October,41,13,2023-10-13,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient,74.4,1,1
HB-091962,City Hotel,0,119,2024,June,26,26,2024-06-26,2,0,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.3,0,1
HB-013614,Resort Hotel,1,49,2025,August,34,22,2025-08-22,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,230.0,0,2
HB-037364,Resort Hotel,0,13,2025,June,24,13,2025-06-13,0,2,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,132.0,0,0
HB-007541,Resort Hotel,1,169,2024,August,33,13,2024-08-13,2,6,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,154.64,0,0
HB-048623,City Hotel,1,81,2024,March,13,25,2024-03-25,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,4,Transient-Party,65.0,0,0
HB-108512,City Hotel,0,158,2025,March,13,27,2025-03-27,1,1,2,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,95.0,0,0
HB-028529,Resort Hotel,0,266,2024,September,39,29,2024-09-29,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,48.75,0,0
HB-092364,City Hotel,0,155,2024,June,26,28,2024-06-28,2,5,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,121.55,0,2
HB-086796,City Hotel,0,3,2024,April,14,7,2024-04-07,0,2,3,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,7.0,,0,Transient,185.57,0,0
HB-018714,Resort Hotel,1,11,2023,December,49,5,2023-12-05,2,1,2,0.0,0,FB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,,,0,Transient-Party,64.0,0,0
HB-108474,City Hotel,0,15,2025,March,12,22,2025-03-22,2,4,2,0.0,0,BB,IRN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,108.8,0,0
HB-050859,City Hotel,1,91,2024,May,19,10,2024-05-10,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,75.0,0,0
HB-076369,City Hotel,0,273,2023,July,29,17,2023-07-17,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-034802,Resort Hotel,0,0,2025,March,13,28,2025-03-28,2,6,1,0.0,0,BB,FIN,Offline TA/TO,TA/TO,0,0,0,A,B,1,No Deposit,8.0,,0,Transient,36.0,0,0
HB-088330,City Hotel,0,102,2024,May,18,1,2024-05-01,2,2,1,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.25,0,2
HB-081958,City Hotel,1,272,2024,August,32,5,2024-08-05,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,41,Transient,65.0,0,0
HB-082324,City Hotel,0,6,2023,December,52,27,2023-12-27,2,0,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,1,No Deposit,,40.0,0,Transient,75.0,0,0
HB-039206,Resort Hotel,0,0,2025,August,32,10,2025-08-10,0,1,2,0.0,0,BB,RUS,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,194.0,1,0
HB-078634,City Hotel,1,14,2023,October,41,15,2023-10-15,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,99.0,,0,Transient-Party,100.0,0,0
HB-093100,City Hotel,0,4,2024,July,29,16,2024-07-16,0,1,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,139.0,0,1
HB-091330,City Hotel,0,1,2024,June,25,17,2024-06-17,1,2,1,0.0,0,BB,AUT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,70.0,0,0
HB-051014,City Hotel,0,309,2024,May,20,13,2024-05-13,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,215,Transient-Party,65.0,0,0
HB-049190,City Hotel,1,88,2024,April,14,7,2024-04-07,0,2,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,0
HB-082587,City Hotel,0,49,2023,December,52,30,2023-12-30,0,4,2,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,71.0,0,0
HB-016382,Resort Hotel,0,0,2023,August,34,24,2023-08-24,1,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,D,1,No Deposit,,,0,Transient,153.0,0,0
HB-094129,City Hotel,0,198,2024,July,31,30,2024-07-30,1,1,2,0.0,0,HB,ITA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,96.0,0,1
HB-075937,City Hotel,1,301,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-084633,City Hotel,0,116,2024,February,9,28,2024-02-28,2,1,2,0.0,0,BB,COL,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,134.0,,0,Transient-Party,87.0,0,0
HB-073667,City Hotel,1,123,2025,August,35,29,2025-08-29,1,5,1,0.0,0,BB,JPN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,155.0,0,1
HB-004049,Resort Hotel,1,111,2024,February,7,12,2024-02-12,0,2,2,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,38.0,,0,Transient,70.0,0,0
HB-012831,Resort Hotel,1,67,2025,July,29,18,2025-07-18,1,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,225.0,0,1
HB-022631,Resort Hotel,0,16,2024,March,13,30,2024-03-30,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,39.0,0,1
HB-105346,City Hotel,0,0,2025,February,6,4,2025-02-04,0,1,1,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,98.0,0,0
HB-005111,Resort Hotel,1,185,2024,April,16,18,2024-04-18,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,86.0,0,0
HB-038249,Resort Hotel,0,152,2025,July,27,4,2025-07-04,2,7,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient,151.0,0,2
HB-062655,City Hotel,1,54,2025,January,3,18,2025-01-18,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,171.0,,0,Transient,65.0,0,0
HB-106817,City Hotel,0,0,2025,March,9,1,2025-03-01,0,2,2,1.0,0,BB,POL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,107.88,0,0
HB-014945,Resort Hotel,1,226,2023,August,33,15,2023-08-15,2,5,2,1.0,0,BB,PRT,Online TA,TA/TO,0,2,0,A,A,0,No Deposit,240.0,,0,Transient,135.6,0,3
HB-036190,Resort Hotel,0,257,2025,May,19,9,2025-05-09,0,4,2,0.0,0,HB,GBR,Groups,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient-Party,101.0,0,0
HB-067920,City Hotel,1,305,2025,May,19,9,2025-05-09,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,89.1,0,0
HB-063019,City Hotel,1,566,2025,January,4,26,2025-01-26,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-104729,City Hotel,0,29,2025,January,3,18,2025-01-18,0,3,1,0.0,0,BB,RUS,Groups,TA/TO,0,0,0,A,A,0,No Deposit,171.0,,0,Transient-Party,65.0,0,0
HB-100722,City Hotel,0,77,2024,October,44,30,2024-10-30,2,0,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.9,0,1
HB-043805,City Hotel,0,56,2023,September,39,25,2023-09-25,2,2,1,0.0,0,BB,GRC,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,44.0,,0,Transient-Party,185.0,0,0
HB-039354,Resort Hotel,0,1,2025,August,33,15,2025-08-15,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,103.2,0,2
HB-070956,City Hotel,1,213,2025,June,26,26,2025-06-26,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,323.0,,0,Transient,115.0,0,0
HB-009638,Resort Hotel,1,252,2024,December,51,22,2024-12-22,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,55.8,0,0
HB-043951,City Hotel,0,65,2023,September,39,26,2023-09-26,2,2,2,0.0,0,BB,GRC,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,13.0,,0,Contract,129.2,0,0
HB-029323,Resort Hotel,0,124,2024,October,43,22,2024-10-22,2,2,1,0.0,0,BB,SWE,Groups,Corporate,0,0,0,E,E,3,No Deposit,,,0,Transient-Party,77.0,1,0
HB-091664,City Hotel,0,75,2024,June,25,20,2024-06-20,1,3,2,0.0,0,BB,SWE,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,168.0,,0,Transient,80.75,0,1
HB-052793,City Hotel,1,69,2024,June,24,12,2024-06-12,2,4,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,120.0,0,0
HB-108198,City Hotel,0,50,2025,March,12,18,2025-03-18,2,4,2,0.0,0,BB,SWE,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,68.0,0,0
HB-110288,City Hotel,0,343,2025,April,17,21,2025-04-21,2,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,B,B,1,No Deposit,,,0,Transient,99.25,0,1
HB-048146,City Hotel,1,75,2024,March,11,17,2024-03-17,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,12.0,0,0
HB-060747,City Hotel,1,33,2024,November,47,19,2024-11-19,2,6,2,0.0,1,BB,BRA,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,9.0,,0,Transient,147.9,0,2
HB-017618,Resort Hotel,0,3,2023,October,42,18,2023-10-18,1,0,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,F,0,No Deposit,,,0,Transient,76.0,0,0
HB-077530,City Hotel,0,3,2023,September,38,19,2023-09-19,2,1,2,0.0,0,BB,ESP,Corporate,Corporate,0,0,0,A,A,1,No Deposit,81.0,,0,Transient,120.0,0,0
HB-094449,City Hotel,0,122,2024,August,31,2,2024-08-02,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,8.0,,0,Transient,118.8,0,1
HB-011547,Resort Hotel,1,41,2025,May,20,15,2025-05-15,1,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,104.0,0,1
HB-076816,City Hotel,1,5,2023,August,33,18,2023-08-18,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,2,No Deposit,,40.0,0,Transient,65.0,0,0
HB-015552,Resort Hotel,0,51,2023,July,29,22,2023-07-22,0,3,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,240.0,,0,Transient,135.0,1,1
HB-050664,City Hotel,1,204,2024,May,18,5,2024-05-05,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,34.0,,96,Transient,100.0,0,0
HB-009236,Resort Hotel,1,24,2024,November,45,4,2024-11-04,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,54.98,0,0
HB-000945,Resort Hotel,0,98,2023,August,32,7,2023-08-07,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,134.0,0,2
HB-070208,City Hotel,1,25,2025,June,24,12,2025-06-12,1,1,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.0,0,1
HB-068931,City Hotel,1,423,2025,May,21,23,2025-05-23,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-069213,City Hotel,1,146,2025,May,22,27,2025-05-27,2,1,2,0.0,0,HB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,162.0,0,1
HB-100772,City Hotel,0,177,2024,October,44,29,2024-10-29,2,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,104.4,0,2
HB-000922,Resort Hotel,1,69,2023,August,31,6,2023-08-06,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,146.0,,0,Transient,112.0,0,0
HB-017978,Resort Hotel,0,9,2023,October,43,24,2023-10-24,2,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,78.2,0,0
HB-105137,City Hotel,0,35,2025,January,4,26,2025-01-26,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,61.11,0,1
HB-102661,City Hotel,0,4,2024,December,49,3,2024-12-03,0,1,2,2.0,0,BB,AUT,Online TA,TA/TO,0,0,0,F,G,0,No Deposit,9.0,,0,Transient,190.0,0,0
HB-004465,Resort Hotel,1,197,2024,March,12,19,2024-03-19,2,3,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,77.4,0,3
HB-112835,City Hotel,0,175,2025,May,22,27,2025-05-27,1,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,1
HB-019240,Resort Hotel,0,3,2023,December,49,10,2023-12-10,0,0,2,0.0,1,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,0.0,0,2
HB-072031,City Hotel,1,45,2025,July,29,18,2025-07-18,0,2,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,10.0,,0,Transient,126.0,0,0
HB-011437,Resort Hotel,1,82,2025,May,19,8,2025-05-08,1,3,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,85.0,0,0
HB-090590,City Hotel,0,118,2024,June,23,6,2024-06-06,1,2,1,0.0,0,BB,SVK,Offline TA/TO,Corporate,0,0,0,A,A,0,No Deposit,191.0,,0,Transient-Party,110.0,0,0
HB-019350,Resort Hotel,1,30,2024,January,1,1,2024-01-01,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,D,D,0,No Deposit,240.0,,0,Transient,66.5,0,0
HB-066288,City Hotel,1,49,2025,April,16,16,2025-04-16,2,1,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.2,0,0
HB-088172,City Hotel,0,69,2024,April,17,27,2024-04-27,1,4,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,108.53,0,2
HB-029142,Resort Hotel,0,26,2024,October,42,17,2024-10-17,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,314.0,,0,Transient,67.0,0,1
HB-006177,Resort Hotel,1,100,2024,May,22,27,2024-05-27,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,58.0,0,2
HB-036347,Resort Hotel,0,8,2025,May,20,14,2025-05-14,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,314.0,,0,Transient-Party,89.18,0,1
HB-059678,City Hotel,1,248,2024,October,44,31,2024-10-31,1,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,E,E,0,Non Refund,,51.0,0,Transient-Party,106.0,0,0
HB-035879,Resort Hotel,0,27,2025,May,18,3,2025-05-03,0,1,2,0.0,0,BB,AUT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,,251.0,0,Transient,62.0,0,0
HB-071872,City Hotel,1,152,2025,July,29,14,2025-07-14,2,2,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,143.1,0,0
HB-085161,City Hotel,0,1,2024,March,10,10,2024-03-10,0,1,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,103.0,0,1
HB-002320,Resort Hotel,1,78,2023,October,41,9,2023-10-09,1,2,2,0.0,0,FB,ESP,Groups,TA/TO,0,0,0,A,A,0,Non Refund,134.0,,0,Transient,92.0,0,0
HB-023726,Resort Hotel,0,197,2024,April,18,30,2024-04-30,1,1,1,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,1,No Deposit,298.0,,0,Transient,54.5,0,0
HB-036750,Resort Hotel,0,21,2025,May,22,26,2025-05-26,0,2,2,1.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,96.0,,0,Transient,120.0,1,0
HB-045432,City Hotel,0,72,2023,October,43,28,2023-10-28,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,58,Transient-Party,85.67,0,0
HB-112531,City Hotel,0,120,2025,May,21,22,2025-05-22,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-048167,City Hotel,1,91,2024,March,12,18,2024-03-18,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,20,Transient,75.0,0,0
HB-044001,City Hotel,0,68,2023,September,39,29,2023-09-29,0,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,20.0,,0,Transient-Party,65.0,0,0
HB-066545,City Hotel,1,135,2025,April,17,21,2025-04-21,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,90.0,0,0
HB-034783,Resort Hotel,0,30,2025,March,13,29,2025-03-29,2,5,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,62.71,0,1
HB-067781,City Hotel,1,96,2025,May,19,7,2025-05-07,2,1,2,0.0,0,BB,PHL,Direct,Direct,0,0,0,F,F,0,No Deposit,14.0,,0,Transient,225.0,0,0
HB-028524,Resort Hotel,0,152,2024,September,39,26,2024-09-26,3,7,2,0.0,0,HB,CN,Groups,TA/TO,0,0,0,A,A,0,No Deposit,15.0,,0,Transient-Party,82.0,0,1
HB-093676,City Hotel,0,172,2024,July,30,22,2024-07-22,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,108.3,1,1
HB-079666,City Hotel,0,9,2023,November,48,28,2023-11-28,0,1,2,2.0,0,BB,PRT,Direct,Direct,1,0,1,F,F,1,No Deposit,,,0,Transient,64.0,0,0
HB-055762,City Hotel,1,156,2024,August,34,20,2024-08-20,2,2,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,112.2,0,0
HB-099244,City Hotel,0,12,2024,October,41,10,2024-10-10,1,0,2,0.0,0,BB,ESP,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,130.0,0,0
HB-082427,City Hotel,0,59,2023,December,52,27,2023-12-27,2,1,2,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,E,1,No Deposit,121.0,,0,Transient,112.0,0,0
HB-115111,City Hotel,0,3,2025,June,27,30,2025-06-30,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,42.0,,0,Transient,144.0,0,1
HB-073756,City Hotel,1,272,2023,July,28,16,2023-07-16,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-112774,City Hotel,0,202,2025,May,21,25,2025-05-25,0,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,96.32,0,1
HB-097647,City Hotel,0,315,2024,September,38,17,2024-09-17,1,1,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,38,Transient-Party,65.0,0,1
HB-025002,Resort Hotel,0,108,2024,June,23,5,2024-06-05,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Contract,62.9,0,0
HB-099426,City Hotel,0,180,2024,October,41,10,2024-10-10,1,2,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,234.0,,0,Transient-Party,120.0,0,0
HB-014450,Resort Hotel,0,1,2024,March,10,10,2024-03-10,0,1,1,0.0,0,BB,,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,42.4,1,0
HB-095200,City Hotel,0,7,2024,August,33,12,2024-08-12,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,174.0,0,1
HB-002650,Resort Hotel,1,148,2023,October,43,24,2023-10-24,0,1,1,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,39.0,0,0
HB-010192,Resort Hotel,1,35,2025,February,8,18,2025-02-18,2,1,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,0
HB-105266,City Hotel,0,23,2025,January,5,28,2025-01-28,2,5,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,49.74,0,1
HB-018845,Resort Hotel,0,0,2023,November,47,26,2023-11-26,2,3,2,0.0,0,BB,NLD,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,43.0,0,0
HB-079246,City Hotel,1,444,2024,December,48,1,2024-12-01,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,34.0,,39,Transient,75.0,0,0
HB-096887,City Hotel,0,67,2024,September,36,5,2024-09-05,1,4,1,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,104.76,0,1
HB-052353,City Hotel,1,37,2024,June,23,4,2024-06-04,1,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,131.4,0,0
HB-024854,Resort Hotel,0,149,2024,May,22,27,2024-05-27,3,7,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,314.0,,0,Transient,73.28,0,2
HB-093065,City Hotel,0,232,2024,July,28,12,2024-07-12,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Contract,100.75,1,1
HB-042475,City Hotel,1,1,2023,September,36,6,2023-09-06,2,0,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,6.0,0,0
HB-087711,City Hotel,0,186,2024,April,17,22,2024-04-22,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,23.0,,0,Transient-Party,80.0,0,0
HB-051489,City Hotel,1,22,2024,May,21,20,2024-05-20,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,34.0,,0,Transient,140.0,0,0
HB-095681,City Hotel,0,0,2024,August,34,20,2024-08-20,1,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,152.0,,0,Transient,96.6,0,1
HB-043288,City Hotel,1,162,2023,September,37,17,2023-09-17,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,70.0,0,0
HB-118535,City Hotel,0,0,2025,August,34,20,2025-08-20,2,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,98.0,,0,Transient-Party,115.0,0,0
HB-036366,Resort Hotel,0,37,2025,May,20,16,2025-05-16,0,2,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,106.0,1,3
HB-104021,City Hotel,0,1,2025,January,1,2,2025-01-02,1,1,2,0.0,0,BB,JPN,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,149.0,0,0
HB-071748,City Hotel,1,224,2025,July,28,11,2025-07-11,0,4,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,114.55,0,0
HB-113854,City Hotel,0,21,2025,June,24,12,2025-06-12,1,0,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,149.0,0,1
HB-069609,City Hotel,1,129,2025,June,23,2,2025-06-02,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,154.0,,0,Transient,130.0,0,0
HB-062196,City Hotel,1,86,2025,January,1,4,2025-01-04,0,3,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,2
HB-119305,City Hotel,0,4,2025,August,35,30,2025-08-30,0,3,1,0.0,0,BB,JPN,Direct,Direct,0,0,0,D,D,1,No Deposit,14.0,,0,Transient,140.7,0,0
HB-063949,City Hotel,1,134,2025,February,9,25,2025-02-25,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,75.0,0,0
HB-084082,City Hotel,0,12,2024,February,7,14,2024-02-14,2,3,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,129.0,0,1
HB-010568,Resort Hotel,1,144,2025,March,11,14,2025-03-14,4,14,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,C,1,No Deposit,440.0,,0,Transient-Party,62.0,0,0
HB-047714,City Hotel,1,88,2024,March,9,1,2024-03-01,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient,70.0,0,0
HB-030861,Resort Hotel,0,4,2024,December,49,6,2024-12-06,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,154.0,0,Transient,27.0,0,0
HB-036551,Resort Hotel,0,2,2025,May,21,24,2025-05-24,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Group,42.0,0,0
HB-100497,City Hotel,0,91,2024,October,43,24,2024-10-24,1,4,2,0.0,0,BB,CMR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,109.98,0,0
HB-077077,City Hotel,0,219,2023,September,36,4,2023-09-04,0,1,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,108.0,0,0
HB-116969,City Hotel,0,127,2025,July,30,25,2025-07-25,0,3,2,0.0,0,BB,AUT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,16.0,,0,Transient,98.1,0,0
HB-033767,Resort Hotel,0,5,2025,February,9,26,2025-02-26,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,75.2,0,2
HB-048643,City Hotel,1,72,2024,March,13,26,2024-03-26,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,96.0,0,0
HB-044431,City Hotel,1,97,2023,October,40,5,2023-10-05,1,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,140.0,0,0
HB-037289,Resort Hotel,0,228,2025,June,23,6,2025-06-06,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,143.0,436.0,0,Group,87.13,0,0
HB-115343,City Hotel,0,299,2025,July,27,4,2025-07-04,0,1,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,1
HB-106951,City Hotel,0,0,2025,March,10,4,2025-03-04,0,1,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,1
HB-004613,Resort Hotel,1,106,2024,March,12,24,2024-03-24,1,3,2,0.0,0,FB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,68.0,,0,Transient,84.0,0,0
HB-021247,Resort Hotel,0,9,2024,February,7,17,2024-02-17,2,5,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,26.1,0,0
HB-004656,Resort Hotel,1,127,2024,March,13,25,2024-03-25,0,2,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,47.0,0,0
HB-074270,City Hotel,1,281,2023,July,30,25,2023-07-25,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-052847,City Hotel,1,27,2024,June,24,12,2024-06-12,2,3,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.84,0,0
HB-012492,Resort Hotel,1,52,2025,July,27,1,2025-07-01,4,6,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,D,D,0,No Deposit,531.0,,0,Transient,92.0,0,0
HB-108201,City Hotel,0,31,2025,March,12,20,2025-03-20,1,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,1
HB-000594,Resort Hotel,1,49,2023,July,29,20,2023-07-20,3,6,2,0.0,0,FB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,15.0,,0,Transient,111.2,0,0
HB-006206,Resort Hotel,0,225,2024,May,22,28,2024-05-28,1,1,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,E,0,No Deposit,298.0,,0,Transient-Party,85.0,0,0
HB-058906,City Hotel,1,605,2024,October,42,17,2024-10-17,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-098221,City Hotel,0,39,2024,September,39,25,2024-09-25,1,0,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,10.0,,0,Transient,129.7,0,0
HB-114620,City Hotel,0,149,2025,June,26,24,2025-06-24,0,1,2,0.0,0,HB,USA,Corporate,Corporate,0,0,0,A,D,0,No Deposit,495.0,,0,Transient-Party,154.0,0,1
HB-039085,Resort Hotel,0,182,2025,July,31,29,2025-07-29,3,6,2,2.0,0,HB,ESP,Direct,Direct,0,0,0,C,C,1,No Deposit,250.0,,0,Transient,223.14,0,1
HB-044769,City Hotel,1,174,2023,October,41,10,2023-10-10,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,70.0,0,0
HB-089313,City Hotel,0,123,2024,May,20,17,2024-05-17,0,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.5,0,1
HB-031427,Resort Hotel,0,10,2025,February,9,27,2025-02-27,1,2,2,0.0,0,BB,PRT,Online TA,Direct,1,0,0,D,D,0,No Deposit,240.0,,0,Transient,52.67,0,2
HB-080741,City Hotel,1,13,2023,December,49,6,2023-12-06,2,0,2,0.0,0,BB,PRT,Online TA,TA/TO,1,1,0,A,A,0,No Deposit,9.0,,0,Contract,107.0,0,2
HB-103942,City Hotel,0,41,2024,December,52,27,2024-12-27,2,5,2,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,220.0,,0,Transient-Party,69.29,0,0
HB-075595,City Hotel,0,257,2023,July,26,1,2023-07-01,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,101.5,0,0
HB-023339,Resort Hotel,0,53,2024,April,15,13,2024-04-13,2,8,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,314.0,,0,Transient,52.56,0,0
HB-032204,Resort Hotel,0,40,2025,January,3,16,2025-01-16,1,2,1,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,A,C,1,No Deposit,,,0,Transient-Party,55.0,0,0
HB-036237,Resort Hotel,0,90,2025,May,19,9,2025-05-09,0,5,2,0.0,0,BB,SRB,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient-Party,94.0,1,1
HB-109525,City Hotel,0,76,2025,April,15,7,2025-04-07,2,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,126.0,0,2
HB-061082,City Hotel,1,290,2024,December,48,1,2024-12-01,1,3,2,0.0,0,BB,SVK,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,73.95,0,0
HB-105574,City Hotel,0,12,2025,February,7,10,2025-02-10,0,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.0,0,0
HB-016634,Resort Hotel,0,68,2023,August,35,30,2023-08-30,2,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,115.0,1,1
HB-051485,City Hotel,1,211,2024,May,21,20,2024-05-20,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,111,Transient,100.0,0,0
HB-054427,City Hotel,1,210,2024,July,29,15,2024-07-15,2,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,96.0,0,0
HB-034548,Resort Hotel,0,152,2025,March,11,15,2025-03-15,4,10,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient,55.86,0,0
HB-058517,City Hotel,1,461,2024,October,41,13,2024-10-13,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-046933,City Hotel,1,10,2024,January,4,28,2024-01-28,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient-Party,66.0,0,0
HB-022064,Resort Hotel,0,47,2024,March,9,3,2024-03-03,4,10,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,26.1,0,0
HB-105663,City Hotel,0,9,2025,February,7,10,2025-02-10,1,2,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,112.42,0,1
HB-032775,Resort Hotel,0,2,2025,February,6,4,2025-02-04,0,1,2,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,55.0,1,1
HB-019732,Resort Hotel,0,112,2023,December,52,30,2023-12-30,0,3,2,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,237.33,0,0
HB-090427,City Hotel,0,191,2024,June,23,3,2024-06-03,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,132.0,0,0
HB-096987,City Hotel,0,183,2024,September,36,8,2024-09-08,0,3,2,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,44.0,,0,Transient-Party,110.0,0,1
HB-100585,City Hotel,0,178,2024,October,43,26,2024-10-26,0,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.9,0,2
HB-011026,Resort Hotel,1,267,2025,April,16,14,2025-04-14,2,5,2,1.0,0,BB,IRL,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,68.81,0,1
HB-056075,City Hotel,1,35,2024,August,35,28,2024-08-28,2,1,2,1.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,171.45,0,0
HB-088440,City Hotel,0,52,2024,April,18,30,2024-04-30,2,4,0,0.0,0,SC,SWE,Direct,Direct,0,0,0,E,K,2,No Deposit,14.0,,0,Transient-Party,136.46,0,1
HB-029904,Resort Hotel,0,1,2024,November,45,8,2024-11-08,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,96.0,1,1
HB-058353,City Hotel,1,97,2024,October,41,11,2024-10-11,0,2,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.2,0,1
HB-085197,City Hotel,0,5,2024,May,18,4,2024-05-04,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,12,E,E,0,Non Refund,,51.0,0,Transient-Party,106.0,0,0
HB-019277,Resort Hotel,0,0,2023,December,49,9,2023-12-09,0,3,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,2,No Deposit,,,0,Transient,43.0,0,0
HB-079162,City Hotel,0,0,2024,June,23,7,2024-06-07,0,1,1,0.0,0,BB,PRT,Complementary,Direct,1,0,2,D,D,0,No Deposit,,45.0,0,Transient,0.0,0,0
HB-046299,City Hotel,0,146,2023,December,52,29,2023-12-29,0,3,2,0.0,0,BB,AUT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,99,Transient-Party,75.0,0,0
HB-086950,City Hotel,0,89,2024,April,15,9,2024-04-09,2,1,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.5,0,1
HB-023347,Resort Hotel,0,1,2024,April,17,22,2024-04-22,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,5.0,,0,Transient,68.0,0,0
HB-085501,City Hotel,0,60,2024,March,11,13,2024-03-13,2,2,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,D,A,0,No Deposit,14.0,,0,Transient,77.35,0,0
HB-063158,City Hotel,1,56,2025,February,5,1,2025-02-01,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,60.0,0,0
HB-091515,City Hotel,0,58,2024,June,25,20,2024-06-20,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.9,1,0
HB-019510,Resort Hotel,0,13,2023,December,51,22,2023-12-22,0,3,2,0.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,156.0,,0,Transient,59.85,0,0
HB-108244,City Hotel,0,16,2025,March,12,23,2025-03-23,0,2,1,0.0,0,BB,FIN,Corporate,Corporate,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,108.0,0,0
HB-003874,Resort Hotel,1,4,2024,February,5,3,2024-02-03,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,68.0,0,1
HB-000672,Resort Hotel,0,1,2023,July,30,25,2023-07-25,1,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,E,0,No Deposit,,,0,Transient,147.0,0,0
HB-001722,Resort Hotel,0,167,2023,September,36,10,2023-09-10,4,10,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,156.0,,0,Contract,50.15,0,2
HB-095843,City Hotel,0,1,2024,August,34,24,2024-08-24,0,1,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,228.0,1,2
HB-058642,City Hotel,1,37,2024,October,41,13,2024-10-13,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,105.0,0,0
HB-037618,Resort Hotel,0,280,2025,June,25,17,2025-06-17,2,5,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,150.81,0,3
HB-013152,Resort Hotel,1,310,2025,August,31,2,2025-08-02,2,6,2,1.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,15.0,,0,Transient,148.74,0,0
HB-000090,Resort Hotel,0,9,2023,July,27,3,2023-07-03,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient,98.0,1,2
HB-035596,Resort Hotel,0,31,2025,April,17,23,2025-04-23,2,4,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,93.0,0,0
HB-038369,Resort Hotel,0,25,2025,July,29,14,2025-07-14,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,215.0,0,1
HB-095039,City Hotel,0,117,2024,August,33,12,2024-08-12,0,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,112.5,0,1
HB-054265,City Hotel,1,49,2024,July,28,11,2024-07-11,1,0,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.15,0,0
HB-070569,City Hotel,1,342,2025,June,25,18,2025-06-18,2,3,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,0
HB-047884,City Hotel,1,45,2024,March,10,7,2024-03-07,1,3,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,63.75,0,0
HB-063345,City Hotel,1,16,2025,February,6,9,2025-02-09,0,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-052741,City Hotel,1,9,2024,June,24,10,2024-06-10,1,2,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,221.0,0,0
HB-052323,City Hotel,1,177,2024,June,23,3,2024-06-03,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,119.0,,0,Transient-Party,100.0,0,0
HB-069158,City Hotel,1,235,2025,May,22,26,2025-05-26,1,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,1
HB-059877,City Hotel,1,304,2024,November,44,3,2024-11-03,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,89.0,0,0
HB-103022,City Hotel,0,101,2024,December,49,8,2024-12-08,0,3,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,165.6,0,1
HB-107159,City Hotel,0,171,2025,March,10,5,2025-03-05,2,2,1,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,80.0,0,2
HB-020206,Resort Hotel,0,0,2024,January,3,19,2024-01-19,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,58.0,1,0
HB-115579,City Hotel,0,131,2025,July,28,7,2025-07-07,0,1,2,0.0,0,SC,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,0
HB-024626,Resort Hotel,0,90,2024,May,21,22,2024-05-22,2,3,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,68.0,0,0
HB-086905,City Hotel,0,159,2024,April,15,9,2024-04-09,1,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,70.0,0,1
HB-097396,City Hotel,0,5,2024,September,37,13,2024-09-13,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,184.0,0,1
HB-095693,City Hotel,0,35,2024,August,34,20,2024-08-20,2,1,2,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,85.0,0,1
HB-116117,City Hotel,0,78,2025,July,28,10,2025-07-10,1,4,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,150.0,0,1
HB-106247,City Hotel,0,23,2025,February,8,19,2025-02-19,2,2,2,2.0,0,BB,NLD,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,190.0,0,0
HB-115162,City Hotel,0,124,2025,June,26,28,2025-06-28,0,4,2,0.0,0,BB,USA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,96.53,0,0
HB-068782,City Hotel,1,75,2025,May,21,20,2025-05-20,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,90.0,0,0
HB-102231,City Hotel,0,39,2024,November,47,20,2024-11-20,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.4,0,2
HB-034794,Resort Hotel,0,8,2025,April,14,4,2025-04-04,0,1,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,85.0,0,0
HB-088306,City Hotel,0,6,2024,November,45,8,2024-11-08,0,1,1,0.0,0,BB,FRA,Corporate,Corporate,1,0,2,D,D,0,No Deposit,,227.0,0,Transient,94.0,0,0
HB-030831,Resort Hotel,0,21,2024,December,48,1,2024-12-01,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,240.0,,0,Transient,60.0,0,2
HB-096621,City Hotel,0,58,2024,September,36,2,2024-09-02,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,123.3,0,2
HB-065510,City Hotel,1,13,2025,April,14,4,2025-04-04,0,4,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,224.0,0,0
HB-056775,City Hotel,1,32,2024,September,37,13,2024-09-13,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,83.0,,0,Transient,137.52,0,0
HB-064890,City Hotel,1,114,2025,March,12,19,2025-03-19,2,2,2,0.0,0,SC,LUX,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,0
HB-110308,City Hotel,0,74,2025,April,17,24,2025-04-24,1,1,3,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,171.0,0,0
HB-044818,City Hotel,1,105,2023,October,41,12,2023-10-12,1,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,110.0,0,0
HB-102733,City Hotel,0,52,2024,December,48,1,2024-12-01,1,3,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,2
HB-115620,City Hotel,0,122,2025,July,28,8,2025-07-08,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,3,No Deposit,9.0,,0,Transient-Party,126.0,0,1
HB-062865,City Hotel,1,59,2025,January,4,23,2025-01-23,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,326.0,,0,Transient,80.0,0,0
HB-092493,City Hotel,0,4,2024,July,27,6,2024-07-06,0,1,2,1.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,89.0,,0,Transient,100.08,0,1
HB-084952,City Hotel,0,4,2024,March,10,7,2024-03-07,1,3,2,0.0,0,HB,DZA,Offline TA/TO,TA/TO,0,0,1,A,A,0,No Deposit,12.0,,0,Transient-Party,106.0,0,0
HB-010842,Resort Hotel,1,58,2025,April,15,8,2025-04-08,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,105.0,0,1
HB-032737,Resort Hotel,0,1,2025,February,6,3,2025-02-03,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,330.0,,0,Transient-Party,34.0,0,1
HB-009160,Resort Hotel,1,5,2024,October,44,30,2024-10-30,2,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,B,0,No Deposit,,,0,Transient,38.0,0,0
HB-086089,City Hotel,0,7,2024,March,12,24,2024-03-24,0,3,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,9.0,,0,Transient,174.67,0,2
HB-022545,Resort Hotel,0,1,2024,March,13,27,2024-03-27,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,68.0,0,1
HB-022052,Resort Hotel,0,4,2025,April,14,4,2025-04-04,0,1,1,0.0,0,HB,PRT,Online TA,TA/TO,1,0,2,A,A,1,No Deposit,5.0,,0,Transient,75.6,0,0
HB-100389,City Hotel,0,232,2024,October,43,23,2024-10-23,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,66.53,0,1
HB-049188,City Hotel,1,274,2024,April,14,7,2024-04-07,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-020000,Resort Hotel,0,5,2024,January,2,9,2024-01-09,2,2,1,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,242.0,,0,Transient,48.0,0,1
HB-068818,City Hotel,1,210,2025,May,21,20,2025-05-20,2,4,2,1.0,0,BB,DNK,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,197.1,0,0
HB-110972,City Hotel,0,67,2025,May,18,2,2025-05-02,0,3,2,0.0,0,BB,SWE,Groups,Corporate,0,0,0,A,A,0,No Deposit,,409.0,0,Transient-Party,120.0,0,0
HB-104216,City Hotel,0,71,2025,January,1,4,2025-01-04,0,4,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,54.71,0,1
HB-042065,City Hotel,1,104,2023,August,35,30,2023-08-30,2,1,2,0.0,0,HB,ESP,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,90.0,0,0
HB-075706,City Hotel,1,302,2023,August,33,15,2023-08-15,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-001676,Resort Hotel,0,28,2023,September,36,9,2023-09-09,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,154.0,0,Transient,80.0,0,0
HB-059023,City Hotel,1,109,2024,October,42,20,2024-10-20,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.8,0,0
HB-058742,City Hotel,1,93,2024,October,42,15,2024-10-15,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,34.0,,0,Transient,115.0,0,0
HB-116280,City Hotel,0,78,2025,July,29,15,2025-07-15,1,1,2,0.0,0,BB,DNK,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,130.5,0,2
HB-082745,City Hotel,1,325,2024,October,42,17,2024-10-17,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,58.0,,0,Transient,95.0,0,0
HB-026251,Resort Hotel,0,48,2024,July,30,24,2024-07-24,2,0,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,253.0,1,1
HB-078123,City Hotel,0,1,2023,October,40,3,2023-10-03,0,1,1,0.0,0,BB,POL,Direct,Direct,0,0,0,A,D,0,Non Refund,,,0,Transient-Party,145.0,0,0
HB-023989,Resort Hotel,0,164,2024,May,18,5,2024-05-05,1,3,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient-Party,44.1,0,1
HB-003769,Resort Hotel,1,113,2024,January,1,2,2024-01-02,0,1,2,0.0,0,HB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,305.0,,0,Transient,72.0,0,0
HB-026320,Resort Hotel,0,0,2024,July,30,25,2024-07-25,1,2,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,214.33,0,1
HB-096528,City Hotel,0,59,2024,September,35,1,2024-09-01,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,123.3,0,2
HB-118032,City Hotel,0,135,2025,August,32,7,2025-08-07,2,5,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,189.43,0,2
HB-109229,City Hotel,0,75,2025,April,14,5,2025-04-05,0,4,1,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,85.0,0,0
HB-004677,Resort Hotel,1,20,2024,March,13,27,2024-03-27,2,2,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,36.0,0,0
HB-021499,Resort Hotel,0,0,2025,January,3,18,2025-01-18,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,4,A,A,0,No Deposit,,290.0,0,Transient,35.0,0,0
HB-054426,City Hotel,1,210,2024,July,29,15,2024-07-15,2,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,96.0,0,0
HB-113976,City Hotel,0,67,2025,June,24,12,2025-06-12,1,2,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,95.76,0,1
HB-113534,City Hotel,0,88,2025,June,23,5,2025-06-05,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,83.0,,0,Transient,122.4,0,0
HB-037766,Resort Hotel,0,121,2025,June,26,24,2025-06-24,2,3,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,G,G,1,No Deposit,250.0,,0,Transient,185.0,0,3
HB-072709,City Hotel,1,174,2025,August,31,3,2025-08-03,2,3,2,1.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,148.5,0,0
HB-085292,City Hotel,0,1,2024,March,11,12,2024-03-12,0,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient,97.0,0,1
HB-034752,Resort Hotel,0,142,2025,March,13,30,2025-03-30,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,70.8,0,2
HB-021053,Resort Hotel,0,4,2024,February,7,16,2024-02-16,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,146.0,,0,Transient,25.0,0,0
HB-029777,Resort Hotel,0,35,2024,October,44,31,2024-10-31,1,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,40.68,0,1
HB-110399,City Hotel,0,21,2025,April,17,26,2025-04-26,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,219.0,0,Transient,104.0,1,1
HB-013067,Resort Hotel,1,137,2025,July,31,29,2025-07-29,3,6,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,241.0,,0,Transient,229.33,0,1
HB-049863,City Hotel,0,270,2024,April,16,20,2024-04-20,0,4,2,0.0,0,BB,ISL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,187,Transient-Party,80.0,0,0
HB-025915,Resort Hotel,0,132,2024,July,28,10,2024-07-10,2,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,172.0,0,1
HB-010066,Resort Hotel,1,238,2025,February,7,10,2025-02-10,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,155.0,,0,Transient,54.0,0,0
HB-109445,City Hotel,0,104,2025,April,15,9,2025-04-09,2,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,3
HB-000285,Resort Hotel,0,117,2023,July,28,11,2023-07-11,2,4,3,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,15.0,,0,Transient,144.4,0,1
HB-086584,City Hotel,0,65,2024,April,14,1,2024-04-01,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.91,0,1
HB-045185,City Hotel,0,47,2023,October,42,22,2023-10-22,0,1,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.5,0,1
HB-051257,City Hotel,1,286,2024,May,20,17,2024-05-17,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,75,Transient,65.0,0,0
HB-114002,City Hotel,0,115,2025,June,24,14,2025-06-14,0,1,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,9.0,,0,Transient,198.0,0,1
HB-117237,City Hotel,0,153,2025,July,31,29,2025-07-29,2,1,2,1.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,148.5,0,0
HB-022531,Resort Hotel,0,0,2024,March,12,24,2024-03-24,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,242.0,,0,Transient,60.0,1,1
HB-116335,City Hotel,0,174,2025,July,29,14,2025-07-14,2,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,89.4,0,1
HB-116910,City Hotel,0,232,2025,July,30,24,2025-07-24,1,2,2,1.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,148.5,0,1
HB-024144,Resort Hotel,0,110,2024,May,19,7,2024-05-07,2,4,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,57.8,0,0
HB-032754,Resort Hotel,0,131,2025,January,2,8,2025-01-08,8,20,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,G,0,No Deposit,314.0,,0,Transient,54.35,0,0
HB-022914,Resort Hotel,0,31,2024,April,14,7,2024-04-07,0,3,1,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,1,No Deposit,67.0,,0,Transient-Party,0.0,0,0
HB-039392,Resort Hotel,0,26,2025,August,32,7,2025-08-07,3,7,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,151.3,0,2
HB-051639,City Hotel,0,157,2024,May,21,23,2024-05-23,1,2,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,114.3,0,2
HB-085243,City Hotel,0,8,2024,March,10,9,2024-03-09,0,3,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,100.0,0,0
HB-097646,City Hotel,0,75,2024,September,38,17,2024-09-17,1,1,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,80.75,0,0
HB-077087,City Hotel,0,1,2023,September,35,3,2023-09-03,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,130.33,0,0
HB-102355,City Hotel,0,68,2024,November,48,25,2024-11-25,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.6,0,0
HB-065562,City Hotel,1,373,2025,April,14,5,2025-04-05,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-040889,City Hotel,0,16,2023,August,32,8,2023-08-08,2,2,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,0.0,0,0
HB-027750,Resort Hotel,0,250,2024,September,36,5,2024-09-05,1,4,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,132.0,1,1
HB-050223,City Hotel,1,106,2024,April,17,26,2024-04-26,2,6,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,86.06,0,0
HB-110456,City Hotel,0,5,2025,April,17,26,2025-04-26,0,2,1,0.0,0,BB,ESP,Direct,Direct,0,0,0,D,D,1,No Deposit,,,0,Transient,185.0,0,0
HB-115848,City Hotel,0,133,2025,July,28,9,2025-07-09,2,1,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient-Party,89.1,0,2
HB-058422,City Hotel,1,279,2024,October,41,12,2024-10-12,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,98.0,,0,Transient,110.0,0,0
HB-102655,City Hotel,0,41,2024,December,48,1,2024-12-01,0,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,89.0,,0,Transient,66.88,0,0
HB-060647,City Hotel,1,102,2024,November,46,17,2024-11-17,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.0,0,2
HB-097776,City Hotel,0,10,2024,September,38,18,2024-09-18,2,1,2,0.0,1,BB,POL,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,171.33,0,2
HB-069344,City Hotel,1,408,2025,May,22,30,2025-05-30,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-118792,City Hotel,0,121,2025,August,34,19,2025-08-19,2,4,2,0.0,0,BB,CHL,Direct,Direct,0,0,0,A,A,4,No Deposit,14.0,,0,Transient,114.75,0,1
HB-059550,City Hotel,1,15,2024,October,44,29,2024-10-29,1,1,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,220.0,0,0
HB-110679,City Hotel,0,28,2025,April,18,28,2025-04-28,1,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,115.0,0,1
HB-053608,City Hotel,1,163,2024,June,26,25,2024-06-25,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,96.0,0,0
HB-056302,City Hotel,0,251,2024,September,36,3,2024-09-03,0,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.3,0,1
HB-044468,City Hotel,1,97,2023,October,40,5,2023-10-05,1,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,140.0,0,0
HB-044756,City Hotel,0,79,2023,October,41,10,2023-10-10,1,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,0.0,0,0
HB-109432,City Hotel,0,8,2025,April,15,8,2025-04-08,2,1,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,115.0,0,0
HB-055852,City Hotel,1,196,2024,August,34,22,2024-08-22,1,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.45,0,0
HB-080751,City Hotel,1,176,2024,April,15,9,2024-04-09,1,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,21.0,,0,Transient,125.0,0,0
HB-109095,City Hotel,0,58,2025,March,13,29,2025-03-29,2,7,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,80.76,0,0
HB-109639,City Hotel,0,108,2025,April,15,8,2025-04-08,2,5,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,16.0,,0,Transient,130.1,0,0
HB-055080,City Hotel,0,214,2024,August,31,4,2024-08-04,0,2,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,105.3,1,1
HB-076359,City Hotel,0,273,2023,July,29,17,2023-07-17,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-043203,City Hotel,0,76,2023,September,37,16,2023-09-16,0,2,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-051886,City Hotel,0,316,2024,May,21,26,2024-05-26,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,B,0,No Deposit,30.0,,0,Transient-Party,110.0,0,0
HB-070101,City Hotel,1,219,2025,June,24,9,2025-06-09,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,105.0,0,0
HB-060722,City Hotel,1,45,2024,November,47,19,2024-11-19,1,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.6,0,0
HB-022462,Resort Hotel,0,12,2024,March,13,26,2024-03-26,1,1,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,240.0,,0,Transient,72.0,0,1
HB-066142,City Hotel,1,176,2025,April,16,14,2025-04-14,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,2.0,,0,Transient-Party,90.0,0,0
HB-096367,City Hotel,0,50,2024,August,35,30,2024-08-30,0,3,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,181.8,0,0
HB-101935,City Hotel,0,11,2024,November,47,18,2024-11-18,0,2,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,104.0,1,1
HB-002678,Resort Hotel,0,9,2023,October,43,24,2023-10-24,4,7,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,63.82,0,2
HB-033841,Resort Hotel,0,112,2025,June,25,18,2025-06-18,2,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient,154.0,1,1
HB-095659,City Hotel,0,6,2024,August,34,21,2024-08-21,1,0,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,145.0,0,2
HB-000186,Resort Hotel,0,112,2023,July,27,6,2023-07-06,3,7,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,120.6,0,1
HB-054774,City Hotel,1,230,2024,July,30,26,2024-07-26,0,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient-Party,95.75,0,1
HB-000241,Resort Hotel,0,14,2023,July,27,9,2023-07-09,2,3,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,75.46,1,1
HB-111485,City Hotel,0,98,2025,May,19,7,2025-05-07,2,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-113863,City Hotel,0,5,2025,June,24,9,2025-06-09,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,169.75,0,1
HB-115947,City Hotel,0,127,2025,July,28,8,2025-07-08,2,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,82.08,0,0
HB-087253,City Hotel,0,122,2024,April,16,15,2024-04-15,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,151.0,,56,Transient-Party,85.0,0,0
HB-083907,City Hotel,0,137,2024,February,7,12,2024-02-12,1,2,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,D,A,0,No Deposit,14.0,,0,Transient,102.0,0,0
HB-013633,Resort Hotel,1,77,2025,August,34,24,2025-08-24,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,198.0,0,0
HB-014615,Resort Hotel,0,25,2023,July,30,24,2023-07-24,2,6,2,0.0,0,BB,PRT,Direct,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,154.0,0,2
HB-032150,Resort Hotel,0,1,2025,April,17,27,2025-04-27,0,1,1,0.0,0,BB,PRT,Online TA,Direct,1,0,2,A,A,0,No Deposit,240.0,,0,Transient-Party,71.0,1,1
HB-040076,City Hotel,0,43,2023,July,27,3,2023-07-03,0,2,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,63.0,0,0
HB-069030,City Hotel,1,310,2025,May,21,24,2025-05-24,0,4,2,0.0,0,BB,DNK,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient,99.45,0,0
HB-092945,City Hotel,0,30,2024,November,46,13,2024-11-13,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,3,A,A,0,No Deposit,,40.0,0,Transient,67.0,1,0
HB-102614,City Hotel,0,4,2024,November,48,27,2024-11-27,2,4,2,0.0,0,BB,AGO,Online TA,TA/TO,0,0,0,A,A,3,No Deposit,9.0,,0,Transient,80.79,0,1
HB-019854,Resort Hotel,0,5,2024,January,1,5,2024-01-05,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,1,No Deposit,,159.0,0,Transient,37.0,0,0
HB-114926,City Hotel,0,24,2025,June,26,26,2025-06-26,1,2,2,0.0,0,BB,FRA,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,280.0,0,Transient-Party,100.0,0,0
HB-081901,City Hotel,1,181,2024,May,18,5,2024-05-05,2,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,26.0,,42,Transient,90.0,0,0
HB-040230,City Hotel,0,18,2023,July,29,18,2023-07-18,1,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,57.5,0,0
HB-048746,City Hotel,0,85,2024,March,13,29,2024-03-29,0,4,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,82.45,0,0
HB-096921,City Hotel,0,36,2024,September,37,9,2024-09-09,0,1,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,112.59,0,1
HB-049647,City Hotel,0,127,2024,April,16,16,2024-04-16,2,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,55.9,0,1
HB-118386,City Hotel,0,22,2025,August,34,19,2025-08-19,1,1,2,1.0,0,BB,FRA,Direct,TA/TO,0,0,0,D,A,0,No Deposit,,,0,Transient,174.0,0,3
HB-105243,City Hotel,0,1,2025,February,5,2,2025-02-02,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,86.0,0,0
HB-091210,City Hotel,0,1,2024,June,24,14,2024-06-14,0,4,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,121.5,0,1
HB-077103,City Hotel,0,219,2023,September,36,4,2023-09-04,1,2,1,0.0,0,BB,SWE,Offline TA/TO,TA/TO,0,0,0,A,E,0,No Deposit,3.0,,0,Transient-Party,76.67,0,0
HB-048776,City Hotel,1,123,2024,March,13,30,2024-03-30,0,3,0,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient-Party,89.92,0,0
HB-007839,Resort Hotel,1,45,2024,August,35,29,2024-08-29,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,11.0,,0,Transient,128.0,0,0
HB-040716,City Hotel,0,12,2023,August,31,5,2023-08-05,0,3,2,0.0,0,BB,RUS,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,38.0,0,Transient-Party,65.0,0,0
HB-027783,Resort Hotel,0,174,2024,September,35,1,2024-09-01,2,8,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Contract,70.0,0,0
HB-035713,Resort Hotel,0,3,2025,April,18,28,2025-04-28,0,2,1,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,78.4,0,1
HB-093480,City Hotel,0,1,2024,July,29,21,2024-07-21,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,219.0,,0,Transient,88.0,1,1
HB-040290,City Hotel,1,96,2023,July,29,19,2023-07-19,3,5,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,10.0,,0,Transient,80.7,0,0
HB-109674,City Hotel,0,2,2025,April,15,10,2025-04-10,1,4,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,154.0,0,2
HB-073415,City Hotel,1,151,2025,August,34,21,2025-08-21,1,1,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.5,0,0
HB-115173,City Hotel,0,4,2025,July,27,2,2025-07-02,1,0,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,152.0,,0,Transient,87.74,0,0
HB-109963,City Hotel,0,116,2025,April,16,17,2025-04-17,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,89.1,0,1
HB-046700,City Hotel,0,42,2024,January,3,16,2024-01-16,0,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.3,0,1
HB-029015,Resort Hotel,0,47,2024,October,42,18,2024-10-18,0,1,2,0.0,0,HB,RUS,Groups,TA/TO,0,0,0,A,A,0,No Deposit,368.0,,0,Transient-Party,72.0,0,0
HB-020068,Resort Hotel,0,14,2024,January,2,12,2024-01-12,0,4,2,0.0,0,HB,FIN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,242.0,,0,Transient,74.8,0,1
HB-039001,Resort Hotel,0,22,2025,July,31,31,2025-07-31,1,4,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,225.0,0,2
HB-093700,City Hotel,0,94,2024,July,29,21,2024-07-21,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,123.3,0,0
HB-039514,Resort Hotel,0,242,2025,August,33,12,2025-08-12,2,6,3,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,261.0,,0,Transient,187.24,0,1
HB-057440,City Hotel,1,418,2024,September,39,26,2024-09-26,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,223,Transient-Party,75.0,0,0
HB-035375,Resort Hotel,0,1,2025,April,16,15,2025-04-15,2,3,1,1.0,0,HB,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,241.0,,0,Transient,98.88,0,1
HB-081298,City Hotel,0,17,2023,December,48,3,2023-12-03,2,3,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,91.0,0,0
HB-106076,City Hotel,0,151,2025,February,8,17,2025-02-17,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-086297,City Hotel,0,90,2024,March,13,28,2024-03-28,1,2,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,27.0,,0,Transient,46.67,0,0
HB-067121,City Hotel,1,140,2025,April,18,28,2025-04-28,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,119.0,,0,Transient-Party,130.0,0,0
HB-072772,City Hotel,1,102,2025,August,32,5,2025-08-05,2,5,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,121.5,0,1
HB-003463,Resort Hotel,0,103,2023,December,50,14,2023-12-14,1,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,26.95,0,1
HB-030827,Resort Hotel,0,26,2024,November,48,30,2024-11-30,1,4,2,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,38.62,0,1
HB-105709,City Hotel,0,9,2025,February,7,10,2025-02-10,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,100.8,0,0
HB-007298,Resort Hotel,0,163,2024,August,31,1,2024-08-01,2,5,2,0.0,0,HB,POL,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,315.0,,0,Transient,140.76,0,1
HB-068993,City Hotel,1,341,2025,May,21,24,2025-05-24,0,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,123.3,0,1
HB-028923,Resort Hotel,0,231,2024,October,41,8,2024-10-08,2,5,1,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,D,1,No Deposit,273.0,,0,Transient-Party,44.36,0,0
HB-111964,City Hotel,0,47,2025,May,20,15,2025-05-15,1,2,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,455.0,,0,Transient-Party,164.0,0,1
HB-103622,City Hotel,0,79,2024,December,52,27,2024-12-27,0,1,2,2.0,0,BB,ITA,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,9.0,,0,Transient,156.6,0,1
HB-116863,City Hotel,0,86,2025,July,30,24,2025-07-24,1,1,2,0.0,0,SC,JPN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,1
HB-031988,Resort Hotel,0,0,2025,January,3,13,2025-01-13,0,1,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-075401,City Hotel,1,323,2023,September,36,5,2023-09-05,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-034136,Resort Hotel,0,112,2025,March,11,13,2025-03-13,1,0,2,0.0,0,BB,CHN,Groups,TA/TO,0,0,0,E,E,0,No Deposit,66.0,,0,Transient-Party,50.0,0,0
HB-106659,City Hotel,0,17,2025,February,9,26,2025-02-26,2,1,1,0.0,0,BB,CHN,Groups,TA/TO,0,0,0,D,D,0,No Deposit,30.0,,0,Transient-Party,75.0,0,0
HB-035056,Resort Hotel,0,3,2025,April,15,10,2025-04-10,1,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,90.0,0,1
HB-088394,City Hotel,0,0,2024,May,18,4,2024-05-04,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,99.0,0,0
HB-029350,Resort Hotel,0,216,2024,October,41,13,2024-10-13,4,10,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Transient,63.4,0,0
HB-065875,City Hotel,1,79,2025,April,15,9,2025-04-09,2,1,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,0
HB-051261,City Hotel,1,286,2024,May,20,17,2024-05-17,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,75,Transient,65.0,0,0
HB-110917,City Hotel,0,122,2025,April,18,30,2025-04-30,2,2,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,128.25,0,0
HB-052290,City Hotel,1,130,2024,June,22,2,2024-06-02,0,3,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,116.1,0,0
HB-098578,City Hotel,0,100,2024,September,39,28,2024-09-28,0,4,1,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,B,1,No Deposit,26.0,,0,Transient-Party,0.0,0,0
HB-085332,City Hotel,0,47,2024,March,10,9,2024-03-09,0,4,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,65.0,0,1
HB-054691,City Hotel,1,135,2024,July,30,23,2024-07-23,2,2,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.45,0,0
HB-071074,City Hotel,1,142,2025,June,26,28,2025-06-28,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,125.0,0,0
HB-073850,City Hotel,1,307,2023,August,33,20,2023-08-20,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-009675,Resort Hotel,1,79,2024,December,52,24,2024-12-24,2,3,2,0.0,0,BB,MAR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,37.8,0,1
HB-078997,City Hotel,0,26,2023,October,42,17,2023-10-17,2,1,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-036567,Resort Hotel,0,87,2025,May,21,20,2025-05-20,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,94.0,0,2
HB-052165,City Hotel,1,18,2024,May,22,31,2024-05-31,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,15.0,,0,Transient,112.8,0,0
HB-049788,City Hotel,1,103,2024,April,16,19,2024-04-19,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,0,Transient,115.0,0,0
HB-109583,City Hotel,0,168,2025,April,15,10,2025-04-10,1,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.25,0,1
HB-041411,City Hotel,1,131,2023,August,33,15,2023-08-15,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-115871,City Hotel,0,145,2025,July,28,9,2025-07-09,2,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,107.1,0,1
HB-008442,Resort Hotel,1,131,2024,September,39,28,2024-09-28,0,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,91.5,0,0
HB-081765,City Hotel,1,113,2024,February,8,25,2024-02-25,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,44,Transient,75.0,0,0
HB-075583,City Hotel,0,257,2023,July,26,1,2023-07-01,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,101.5,0,0
HB-085817,City Hotel,0,6,2024,March,12,19,2024-03-19,2,1,3,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,177.0,0,1
HB-104309,City Hotel,0,7,2025,January,2,8,2025-01-08,2,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,82.88,0,0
HB-063855,City Hotel,1,58,2025,February,8,23,2025-02-23,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,132.0,,0,Transient,78.0,0,0
HB-021070,Resort Hotel,0,2,2025,March,12,18,2025-03-18,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,1,0,1,A,A,0,No Deposit,330.0,,0,Transient-Party,34.0,0,1
HB-035368,Resort Hotel,0,100,2025,April,16,15,2025-04-15,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,80.0,0,1
HB-071464,City Hotel,1,10,2025,July,27,6,2025-07-06,0,1,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.0,0,2
HB-104616,City Hotel,0,34,2025,January,3,18,2025-01-18,0,1,1,0.0,0,BB,CHN,Groups,TA/TO,0,0,0,A,A,1,No Deposit,19.0,,0,Transient-Party,75.0,0,0
HB-029225,Resort Hotel,0,386,2024,October,42,20,2024-10-20,1,3,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,55.0,0,1
HB-076522,City Hotel,1,195,2023,September,37,17,2023-09-17,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,20.0,,0,Transient,48.0,0,0
HB-067619,City Hotel,1,104,2025,May,19,5,2025-05-05,1,2,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,162.0,0,0
HB-046187,City Hotel,0,1,2023,December,51,23,2023-12-23,0,3,0,2.0,0,BB,DEU,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient-Party,6.0,0,0
HB-070490,City Hotel,1,150,2025,June,25,17,2025-06-17,2,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,120.0,0,0
HB-115136,City Hotel,0,238,2025,June,26,28,2025-06-28,0,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.53,0,1
HB-023064,Resort Hotel,0,0,2024,April,15,13,2024-04-13,0,2,1,0.0,0,BB,DEU,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient,95.0,0,0
HB-084769,City Hotel,0,18,2024,February,9,28,2024-02-28,2,2,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,9.0,,0,Transient,130.0,0,2
HB-026551,Resort Hotel,0,81,2024,July,31,29,2024-07-29,2,4,3,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,265.83,0,0
HB-022128,Resort Hotel,0,5,2024,April,14,6,2024-04-06,0,1,1,0.0,0,BB,PRT,Direct,TA/TO,1,0,1,A,A,0,No Deposit,,61.0,0,Transient,56.0,0,0
HB-114860,City Hotel,0,2,2025,June,26,26,2025-06-26,1,1,2,0.0,0,SC,AUT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,149.0,0,0
HB-091715,City Hotel,0,265,2024,June,26,24,2024-06-24,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-073876,City Hotel,1,321,2023,September,35,3,2023-09-03,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,2,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-103388,City Hotel,0,8,2024,December,51,19,2024-12-19,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.0,0,1
HB-104627,City Hotel,0,34,2025,January,3,18,2025-01-18,0,1,1,0.0,0,BB,IND,Groups,TA/TO,0,0,0,A,A,0,No Deposit,19.0,,0,Transient-Party,75.0,0,0
HB-065275,City Hotel,1,70,2025,March,13,30,2025-03-30,2,3,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,89.32,0,0
HB-058132,City Hotel,1,85,2024,October,40,6,2024-10-06,1,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,75.0,0,0
HB-025682,Resort Hotel,0,133,2024,June,26,30,2024-06-30,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Contract,90.1,0,1
HB-095752,City Hotel,0,188,2024,August,34,20,2024-08-20,2,2,2,0.0,0,BB,ITA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,89.25,0,0
HB-029399,Resort Hotel,0,323,2024,October,43,23,2024-10-23,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,241.0,,0,Transient,40.19,0,2
HB-016343,Resort Hotel,0,159,2023,August,33,17,2023-08-17,3,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,,,0,Transient,139.0,0,1
HB-059519,City Hotel,1,247,2024,October,44,28,2024-10-28,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,110.0,0,0
HB-085392,City Hotel,0,24,2024,March,11,12,2024-03-12,1,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,71.46,0,1
HB-052853,City Hotel,1,120,2024,June,24,13,2024-06-13,1,0,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,140.4,0,0
HB-074491,City Hotel,1,318,2023,August,35,31,2023-08-31,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-101916,City Hotel,0,59,2024,November,46,17,2024-11-17,0,3,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,86.0,,0,Transient,70.72,0,0
HB-020134,Resort Hotel,0,11,2024,January,3,15,2024-01-15,0,2,3,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,71.2,0,0
HB-046770,City Hotel,0,151,2024,January,3,19,2024-01-19,0,2,1,0.0,0,BB,LVA,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,19.0,,63,Transient-Party,70.0,0,0
HB-047780,City Hotel,1,46,2024,March,9,3,2024-03-03,0,3,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,73.9,0,0
HB-009063,Resort Hotel,1,79,2024,October,43,26,2024-10-26,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,46.51,0,1
HB-078225,City Hotel,0,19,2023,October,40,3,2023-10-03,2,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,111.75,0,2
HB-095979,City Hotel,0,142,2024,August,34,24,2024-08-24,0,3,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,99.3,0,0
HB-020344,Resort Hotel,0,153,2024,January,3,20,2024-01-20,1,4,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,E,E,2,No Deposit,241.0,,0,Transient,38.81,0,1
HB-091441,City Hotel,0,86,2024,June,25,19,2024-06-19,2,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.9,0,1
HB-049259,City Hotel,1,268,2024,April,15,8,2024-04-08,2,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,224,Transient-Party,78.0,0,0
HB-056698,City Hotel,1,71,2024,September,37,10,2024-09-10,2,2,3,0.0,0,BB,COL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,168.3,0,2
HB-078668,City Hotel,0,28,2023,October,41,12,2023-10-12,1,1,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,95.95,0,2
HB-112298,City Hotel,0,19,2025,May,21,22,2025-05-22,1,0,1,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,2
HB-111182,City Hotel,0,0,2025,May,19,6,2025-05-06,0,1,3,0.0,0,BB,AGO,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,250.0,0,1
HB-021880,Resort Hotel,0,30,2024,March,10,7,2024-03-07,1,5,1,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,1,No Deposit,38.0,,0,Transient-Party,48.7,0,0
HB-013908,Resort Hotel,0,0,2024,February,7,17,2024-02-17,0,1,1,0.0,0,BB,,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,40.0,0,0
HB-075293,City Hotel,1,299,2023,August,32,12,2023-08-12,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,60.0,0,0
HB-056020,City Hotel,1,90,2024,August,35,27,2024-08-27,0,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.9,0,0
HB-094626,City Hotel,0,158,2024,August,31,4,2024-08-04,0,3,3,0.0,0,BB,DEU,Direct,Direct,0,0,0,A,C,0,No Deposit,14.0,,0,Transient,123.5,0,0
HB-024383,Resort Hotel,0,19,2024,May,20,16,2024-05-16,1,2,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient-Party,141.0,1,0
HB-085874,City Hotel,0,66,2024,March,12,19,2024-03-19,2,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,62.18,0,1
HB-016283,Resort Hotel,0,81,2023,August,33,15,2023-08-15,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,123.0,0,0
HB-110041,City Hotel,0,83,2025,April,16,18,2025-04-18,0,3,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,115.0,0,0
HB-042927,City Hotel,1,9,2023,September,37,11,2023-09-11,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,105.0,0,2
HB-080107,City Hotel,1,333,2024,September,38,20,2024-09-20,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,58.0,,19,Transient,80.0,0,0
HB-111592,City Hotel,0,106,2025,May,19,10,2025-05-10,0,3,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,132.0,0,2
HB-082509,City Hotel,0,0,2023,December,52,31,2023-12-31,0,1,1,0.0,0,SC,PRT,Complementary,Direct,0,0,0,C,A,0,No Deposit,,45.0,0,Transient,0.0,0,0
HB-039990,Resort Hotel,0,34,2025,August,35,28,2025-08-28,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,137.0,0,0
HB-055462,City Hotel,1,136,2024,August,33,13,2024-08-13,2,1,3,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,163.2,0,2
HB-082900,City Hotel,1,68,2024,February,7,17,2024-02-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,37.0,,0,Transient,75.0,0,0
HB-059106,City Hotel,1,457,2024,October,43,21,2024-10-21,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,391,Transient,65.0,0,0
HB-097161,City Hotel,0,41,2024,September,37,10,2024-09-10,2,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.1,0,1
HB-067598,City Hotel,1,161,2025,May,19,5,2025-05-05,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,30.0,,0,Transient,120.0,0,0
HB-078976,City Hotel,1,26,2023,November,44,3,2023-11-03,0,4,1,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Transient,85.85,0,1
HB-053144,City Hotel,1,344,2024,June,24,16,2024-06-16,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-004892,Resort Hotel,1,85,2024,April,14,7,2024-04-07,0,3,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,67.0,,0,Transient-Party,64.0,0,0
HB-027003,Resort Hotel,0,107,2024,August,33,13,2024-08-13,2,2,3,0.0,0,BB,ESP,Direct,Direct,0,0,0,F,F,1,No Deposit,250.0,,0,Transient,271.0,1,0
HB-070037,City Hotel,1,41,2025,June,23,8,2025-06-08,1,3,1,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,130.0,0,1
HB-094581,City Hotel,0,53,2024,August,32,6,2024-08-06,0,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,168.3,0,1
HB-002977,Resort Hotel,0,5,2023,November,45,9,2023-11-09,1,0,1,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,40.0,0,0
HB-119037,City Hotel,0,1,2025,August,35,27,2025-08-27,1,0,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.1,0,1
HB-097008,City Hotel,0,32,2024,September,37,9,2024-09-09,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.9,0,1
HB-034987,Resort Hotel,0,152,2025,April,14,5,2025-04-05,1,4,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,D,D,5,No Deposit,,223.0,0,Transient-Party,67.0,1,0
HB-064921,City Hotel,1,22,2025,March,12,20,2025-03-20,1,4,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,91.8,0,0
HB-112072,City Hotel,0,395,2025,May,20,17,2025-05-17,0,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,1
HB-100977,City Hotel,0,21,2024,October,44,31,2024-10-31,1,4,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.6,0,1
HB-119259,City Hotel,0,163,2025,August,35,30,2025-08-30,0,2,2,0.0,0,BB,ZAF,Offline TA/TO,TA/TO,0,0,0,D,E,1,No Deposit,168.0,,0,Transient,89.1,0,0
HB-084487,City Hotel,0,12,2024,February,8,24,2024-02-24,0,3,1,0.0,0,BB,TUR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.0,0,0
HB-091701,City Hotel,0,265,2024,June,26,24,2024-06-24,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-117056,City Hotel,0,64,2025,July,30,26,2025-07-26,0,3,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,42.0,,0,Transient,104.0,0,0
HB-100118,City Hotel,0,24,2024,October,42,20,2024-10-20,0,3,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.0,0,2
HB-040956,City Hotel,0,39,2023,August,32,10,2023-08-10,1,1,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-054349,City Hotel,1,372,2024,July,28,14,2024-07-14,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,59.0,0,0
HB-022905,Resort Hotel,0,80,2024,April,14,7,2024-04-07,0,3,2,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,67.0,,0,Transient-Party,68.0,0,0
HB-027370,Resort Hotel,0,195,2024,August,34,21,2024-08-21,2,5,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,75.0,,0,Contract,132.8,0,0
HB-029428,Resort Hotel,0,223,2024,October,43,21,2024-10-21,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,F,0,No Deposit,240.0,,0,Transient,66.6,0,2
HB-107002,City Hotel,0,79,2025,February,9,28,2025-02-28,1,5,2,0.0,1,BB,FIN,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,7.0,,0,Transient,70.47,0,2
HB-091099,City Hotel,0,27,2024,June,24,13,2024-06-13,1,3,1,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,7.0,,0,Transient,104.72,0,1
HB-017162,Resort Hotel,0,73,2023,September,39,28,2023-09-28,1,1,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,242.0,,0,Transient,76.0,0,1
HB-086581,City Hotel,0,64,2024,April,14,1,2024-04-01,2,3,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,119.51,0,2
HB-097730,City Hotel,0,119,2024,September,38,19,2024-09-19,1,0,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,162.0,0,1
HB-064742,City Hotel,1,55,2025,March,11,15,2025-03-15,0,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,1
HB-061792,City Hotel,1,262,2024,December,52,26,2024-12-26,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,73.95,0,0
HB-010989,Resort Hotel,1,162,2025,April,15,13,2025-04-13,2,7,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,E,E,6,No Deposit,240.0,,0,Transient-Party,90.0,0,0
HB-010057,Resort Hotel,1,238,2025,February,7,10,2025-02-10,0,2,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,155.0,,0,Transient,47.0,0,0
HB-101306,City Hotel,0,124,2024,November,45,6,2024-11-06,2,2,1,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,146.03,0,3
HB-110866,City Hotel,0,47,2025,May,18,2,2025-05-02,0,1,2,0.0,0,SC,USA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,80.1,0,0
HB-037318,Resort Hotel,0,310,2025,June,23,4,2025-06-04,4,6,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,58.7,0,1
HB-113123,City Hotel,0,409,2025,May,22,31,2025-05-31,0,3,2,0.0,0,BB,AUS,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,2
HB-006808,Resort Hotel,1,152,2024,July,27,3,2024-07-03,2,5,2,0.0,1,FB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,15.0,,0,Transient,121.6,0,1
HB-014502,Resort Hotel,0,2,2023,October,40,2,2023-10-02,0,1,2,0.0,0,BB,,Corporate,Corporate,0,0,0,A,F,2,No Deposit,,287.0,0,Transient,82.0,1,1
HB-088580,City Hotel,0,109,2024,May,18,4,2024-05-04,0,4,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,3,No Deposit,9.0,,0,Transient,120.28,0,1
HB-058685,City Hotel,1,233,2024,October,42,14,2024-10-14,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,90.0,0,0
HB-095728,City Hotel,0,38,2024,August,34,21,2024-08-21,2,0,1,0.0,0,BB,MOZ,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.95,0,0
HB-017940,Resort Hotel,0,5,2023,October,43,26,2023-10-26,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,94.0,0,Transient,37.0,0,0
HB-094698,City Hotel,0,0,2024,August,32,7,2024-08-07,1,0,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,G,G,0,No Deposit,,,0,Transient,121.0,0,0
HB-065259,City Hotel,1,109,2025,March,13,30,2025-03-30,0,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,4,No Deposit,9.0,,0,Transient,85.8,0,0
HB-050515,City Hotel,0,121,2024,May,18,2,2024-05-02,1,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.45,0,1
HB-013059,Resort Hotel,1,56,2025,July,31,29,2025-07-29,2,5,2,0.0,0,BB,MAR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,225.0,0,2
HB-061466,City Hotel,1,26,2024,December,50,12,2024-12-12,2,5,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,154.0,,0,Transient,75.0,0,0
HB-116554,City Hotel,0,173,2025,July,29,18,2025-07-18,0,4,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,98.1,0,2
HB-014259,Resort Hotel,0,29,2024,March,10,9,2024-03-09,1,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,1,D,D,0,No Deposit,250.0,,0,Transient,61.0,1,1
HB-002567,Resort Hotel,0,133,2023,October,42,22,2023-10-22,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Transient,60.0,1,1
HB-001376,Resort Hotel,1,57,2023,August,34,27,2023-08-27,1,3,2,0.0,1,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,15.0,,0,Transient,133.0,0,1
HB-103121,City Hotel,0,20,2024,December,50,9,2024-12-09,1,2,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,92.67,0,1
HB-099755,City Hotel,0,10,2024,October,42,14,2024-10-14,1,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,39.0,,0,Transient-Party,119.0,0,0
HB-064469,City Hotel,1,175,2025,March,11,10,2025-03-10,1,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.6,0,0
HB-070803,City Hotel,1,227,2025,June,26,23,2025-06-23,0,2,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,0
HB-005350,Resort Hotel,1,189,2024,April,17,26,2024-04-26,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,248.0,,0,Transient-Party,46.0,0,0
HB-032711,Resort Hotel,0,0,2025,February,5,2,2025-02-02,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,48.0,0,1
HB-055788,City Hotel,1,167,2024,August,34,21,2024-08-21,2,0,2,0.0,1,BB,FRA,Online TA,TA/TO,0,0,0,A,A,4,No Deposit,9.0,,0,Transient,119.7,0,1
HB-086548,City Hotel,0,4,2024,April,14,3,2024-04-03,2,0,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,7.0,,0,Transient,77.77,0,1
HB-042331,City Hotel,0,3,2023,September,36,5,2023-09-05,0,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,143.0,0,1
HB-046399,City Hotel,0,2,2023,December,52,31,2023-12-31,0,2,2,0.0,0,BB,PHL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,139.0,1,0
HB-017277,Resort Hotel,0,272,2023,September,39,30,2023-09-30,0,3,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,C,0,No Deposit,256.0,,0,Transient-Party,73.0,0,0
HB-003279,Resort Hotel,0,21,2023,December,48,2,2023-12-02,0,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,61.2,0,2
HB-052589,City Hotel,1,26,2024,June,23,8,2024-06-08,0,1,2,0.0,0,BB,PRT,Offline TA/TO,Corporate,0,0,0,A,A,0,No Deposit,191.0,,0,Transient-Party,120.0,0,0
HB-048553,City Hotel,1,78,2024,March,13,25,2024-03-25,1,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,105.3,0,0
HB-045556,City Hotel,0,56,2023,November,45,6,2023-11-06,1,2,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,D,A,0,No Deposit,28.0,,0,Transient,60.0,0,1
HB-108216,City Hotel,0,72,2025,March,12,21,2025-03-21,0,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,106.2,0,2
HB-097638,City Hotel,0,5,2024,September,38,17,2024-09-17,1,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,154.0,0,4
HB-084322,City Hotel,0,60,2024,April,17,25,2024-04-25,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,40.0,0,Transient-Party,65.0,0,0
HB-016064,Resort Hotel,0,35,2023,August,32,10,2023-08-10,1,2,2,0.0,0,BB,DNK,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,241.0,,0,Transient,167.09,0,1
HB-042545,City Hotel,0,0,2023,September,36,7,2023-09-07,1,0,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,133.0,0,1
HB-119169,City Hotel,0,232,2025,August,35,26,2025-08-26,2,3,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,157.25,0,0
HB-020165,Resort Hotel,0,4,2024,January,3,17,2024-01-17,1,0,2,0.0,0,FB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,82.0,0,0
HB-052927,City Hotel,1,71,2024,June,24,14,2024-06-14,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,120.0,0,0
HB-057743,City Hotel,1,267,2024,September,40,30,2024-09-30,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,26.0,,0,Transient,95.0,0,0
HB-018916,Resort Hotel,0,0,2023,December,48,2,2023-12-02,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,1,No Deposit,,,0,Transient,38.0,0,0
HB-050815,City Hotel,1,115,2024,May,19,9,2024-05-09,1,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.5,0,0
HB-035474,Resort Hotel,0,124,2025,April,15,9,2025-04-09,4,10,2,1.0,0,HB,PRT,Groups,TA/TO,0,0,0,H,H,0,No Deposit,493.0,,0,Contract,120.0,0,0
HB-029928,Resort Hotel,0,6,2024,November,45,9,2024-11-09,0,0,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,I,1,No Deposit,250.0,,0,Transient,0.0,0,0
HB-101186,City Hotel,0,40,2024,November,45,6,2024-11-06,2,0,2,1.0,0,BB,RUS,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,2.0,,0,Transient,134.0,0,0
HB-037950,Resort Hotel,0,27,2025,July,27,3,2025-07-03,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,135.0,0,Transient,142.0,0,0
HB-053724,City Hotel,1,119,2024,June,26,28,2024-06-28,0,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.5,0,0
HB-048000,City Hotel,1,50,2024,March,11,11,2024-03-11,2,2,2,0.0,0,BB,TUR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,82.45,0,0
HB-046875,City Hotel,0,38,2024,January,4,23,2024-01-23,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.3,0,1
HB-079654,City Hotel,0,5,2023,October,44,31,2023-10-31,0,1,2,2.0,0,BB,IRL,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,177.0,0,0
HB-101007,City Hotel,0,25,2024,November,44,1,2024-11-01,0,4,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.0,0,1
HB-030752,Resort Hotel,0,0,2024,December,49,2,2024-12-02,0,2,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,E,E,1,No Deposit,,,0,Transient,58.0,1,0
HB-023157,Resort Hotel,0,90,2024,April,15,10,2024-04-10,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,52.2,0,0
HB-061720,City Hotel,1,126,2024,December,52,24,2024-12-24,0,1,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,136.8,0,2
HB-018577,Resort Hotel,0,1,2024,December,51,17,2024-12-17,0,1,2,0.0,0,HB,PRT,Direct,Direct,1,0,3,E,E,1,No Deposit,250.0,,0,Transient,101.0,1,1
HB-040702,City Hotel,0,12,2023,August,31,5,2023-08-05,0,3,2,0.0,0,BB,RUS,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,38.0,0,Transient-Party,65.0,0,0
HB-035585,Resort Hotel,0,222,2025,April,17,22,2025-04-22,2,4,2,0.0,0,HB,BEL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,116.8,1,1
HB-065372,City Hotel,1,149,2025,April,14,1,2025-04-01,2,1,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,0
HB-083965,City Hotel,0,14,2024,February,7,13,2024-02-13,2,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.0,0,1
HB-083153,City Hotel,0,1,2024,January,3,18,2024-01-18,1,3,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,80.0,0,0
HB-072984,City Hotel,1,87,2025,August,33,11,2025-08-11,1,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,145.0,0,1
HB-026343,Resort Hotel,0,2,2024,July,30,28,2024-07-28,0,1,2,2.0,0,BB,DEU,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,259.0,1,1
HB-093779,City Hotel,0,67,2024,July,30,26,2024-07-26,0,1,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,39.0,,27,Transient-Party,95.0,0,0
HB-000091,Resort Hotel,0,1,2023,July,27,3,2023-07-03,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient,131.0,0,1
HB-084892,City Hotel,0,57,2024,March,10,4,2024-03-04,0,2,3,0.0,0,BB,CHE,Groups,Corporate,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,103.0,0,1
HB-105090,City Hotel,0,6,2025,January,5,28,2025-01-28,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,3
HB-058174,City Hotel,1,179,2024,October,41,7,2024-10-07,0,2,3,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,141.3,0,0
HB-116741,City Hotel,0,256,2025,July,30,21,2025-07-21,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,107.1,0,2
HB-007142,Resort Hotel,1,149,2024,July,30,23,2024-07-23,2,5,2,0.0,0,FB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,96.0,,0,Transient,156.6,0,1
HB-021934,Resort Hotel,0,3,2024,March,11,12,2024-03-12,0,1,3,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,C,C,0,No Deposit,177.0,,0,Transient,45.9,0,0
HB-000037,Resort Hotel,0,15,2023,July,26,2,2023-07-02,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient,98.0,0,0
HB-118311,City Hotel,0,176,2025,August,33,14,2025-08-14,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,132.5,0,0
HB-028159,Resort Hotel,0,51,2024,September,38,17,2024-09-17,2,3,2,0.0,1,BB,PRT,Direct,Direct,0,0,0,F,F,1,No Deposit,250.0,,0,Transient,145.6,1,1
HB-007816,Resort Hotel,1,115,2024,August,35,28,2024-08-28,2,1,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient-Party,194.0,0,0
HB-029913,Resort Hotel,0,1,2024,November,45,8,2024-11-08,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,180.0,,0,Transient,30.0,0,0
HB-051475,City Hotel,1,211,2024,May,21,20,2024-05-20,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,111,Transient,100.0,0,0
HB-105818,City Hotel,0,41,2025,February,7,14,2025-02-14,0,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,0
HB-018960,Resort Hotel,0,0,2023,December,48,1,2023-12-01,0,3,1,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,F,F,0,No Deposit,,,0,Transient,85.0,1,0
HB-102341,City Hotel,0,186,2024,November,47,24,2024-11-24,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,15.0,,0,Transient,64.56,0,0
HB-087134,City Hotel,0,72,2024,April,15,13,2024-04-13,0,2,3,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,137.7,0,2
HB-110410,City Hotel,0,41,2025,April,17,26,2025-04-26,0,1,2,0.0,0,BB,POL,Corporate,Corporate,0,0,0,A,A,1,No Deposit,,280.0,0,Transient-Party,120.0,0,0
HB-054793,City Hotel,1,109,2024,July,30,27,2024-07-27,0,1,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.5,0,1
HB-057020,City Hotel,1,302,2024,September,38,16,2024-09-16,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,70,Transient,100.0,0,0
HB-038225,Resort Hotel,0,144,2025,July,28,9,2025-07-09,2,1,2,2.0,0,BB,RUS,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,196.0,1,1
HB-066538,City Hotel,1,177,2025,April,17,21,2025-04-21,1,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,2
HB-043621,City Hotel,0,60,2023,September,38,21,2023-09-21,1,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,20.0,,0,Transient-Party,65.0,0,0
HB-043722,City Hotel,0,34,2023,September,38,23,2023-09-23,0,3,2,0.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,52.0,,33,Transient-Party,224.67,0,0
HB-040266,City Hotel,1,12,2023,July,29,18,2023-07-18,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-080206,City Hotel,0,0,2023,November,45,12,2023-11-12,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,139.0,0,Transient,84.0,0,0
HB-033342,Resort Hotel,0,73,2025,February,8,17,2025-02-17,1,2,2,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,498.0,0,Transient-Party,40.0,0,0
HB-074543,City Hotel,1,339,2023,September,38,21,2023-09-21,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-032163,Resort Hotel,0,10,2025,January,3,18,2025-01-18,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,58.0,1,0
HB-060416,City Hotel,1,489,2024,November,45,10,2024-11-10,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-068270,City Hotel,1,104,2025,May,20,15,2025-05-15,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-097903,City Hotel,0,159,2024,September,38,19,2024-09-19,1,2,2,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,144.0,0,0
HB-024685,Resort Hotel,0,11,2025,February,8,18,2025-02-18,0,1,2,2.0,0,BB,GBR,Online TA,TA/TO,1,0,1,C,C,0,No Deposit,240.0,,0,Transient,75.0,0,2
HB-106173,City Hotel,0,21,2025,February,8,19,2025-02-19,2,1,1,0.0,0,BB,JPN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,72.0,0,0
HB-050458,City Hotel,1,71,2024,May,18,1,2024-05-01,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,3,No Deposit,9.0,,0,Transient,132.6,0,0
HB-069898,City Hotel,1,169,2025,June,23,8,2025-06-08,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,170.0,0,0
HB-067960,City Hotel,1,316,2025,May,19,10,2025-05-10,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.8,0,1
HB-001919,Resort Hotel,1,73,2023,September,38,21,2023-09-21,1,4,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,72.0,0,0
HB-089953,City Hotel,0,52,2024,May,22,27,2024-05-27,1,2,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,138.0,,0,Transient,85.0,0,0
HB-040871,City Hotel,0,30,2023,August,32,8,2023-08-08,2,1,2,0.0,0,HB,ITA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,86.0,0,0
HB-056006,City Hotel,1,193,2024,August,35,26,2024-08-26,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,95.2,0,0
HB-015426,Resort Hotel,0,127,2023,July,26,2,2023-07-02,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Contract,104.55,0,1
HB-100672,City Hotel,0,268,2024,October,44,28,2024-10-28,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.3,0,2
HB-055106,City Hotel,1,147,2024,August,31,4,2024-08-04,2,5,2,2.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,188.42,0,0
HB-056821,City Hotel,1,30,2024,September,37,15,2024-09-15,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.9,0,1
HB-008050,Resort Hotel,1,145,2024,September,36,8,2024-09-08,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,139.0,0,2
HB-029807,Resort Hotel,0,2,2024,November,45,4,2024-11-04,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,93.0,0,0
HB-081454,City Hotel,0,6,2023,December,49,10,2023-12-10,0,2,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,0.0,0,0
HB-012615,Resort Hotel,1,3,2025,July,28,8,2025-07-08,2,2,3,1.0,0,BB,PRT,Direct,Direct,0,0,0,H,H,0,No Deposit,250.0,,0,Transient,265.0,0,1
HB-000893,Resort Hotel,1,61,2023,August,31,3,2023-08-03,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,153.0,0,0
HB-116604,City Hotel,0,170,2025,July,29,17,2025-07-17,1,4,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,152.1,0,2
HB-095238,City Hotel,0,1,2024,August,33,16,2024-08-16,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient,184.5,0,2
HB-090195,City Hotel,0,69,2024,May,22,30,2024-05-30,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,102.1,0,1
HB-111724,City Hotel,0,85,2025,May,19,10,2025-05-10,1,4,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,151.2,0,0
HB-051192,City Hotel,1,77,2024,May,20,15,2024-05-15,2,2,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,E,1,No Deposit,9.0,,0,Transient,150.45,0,1
HB-020084,Resort Hotel,0,0,2024,January,3,15,2024-01-15,0,1,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,49.0,0,0
HB-009111,Resort Hotel,1,0,2024,October,44,28,2024-10-28,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,73.0,0,0
HB-096337,City Hotel,0,15,2024,August,35,30,2024-08-30,0,2,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,2
HB-056877,City Hotel,1,15,2024,September,37,15,2024-09-15,0,2,1,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,139.0,0,0
HB-096558,City Hotel,0,40,2024,August,35,28,2024-08-28,2,5,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient-Party,100.16,0,0
HB-069568,City Hotel,1,175,2025,June,23,2,2025-06-02,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,144.0,0,0
HB-018364,Resort Hotel,1,82,2024,February,6,7,2024-02-07,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,67.0,,0,Transient-Party,86.0,0,0
HB-043034,City Hotel,0,12,2023,September,37,12,2023-09-12,2,2,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,116.75,0,2
HB-016947,Resort Hotel,0,119,2023,September,37,12,2023-09-12,2,4,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,102.6,0,1
HB-109764,City Hotel,0,34,2025,April,16,15,2025-04-15,1,1,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,1
HB-084787,City Hotel,0,14,2024,November,47,23,2024-11-23,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,9,A,A,0,No Deposit,,219.0,0,Transient,88.0,1,1
HB-011767,Resort Hotel,1,132,2025,May,22,28,2025-05-28,4,6,2,0.0,0,HB,BEL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,160.0,0,0
HB-107443,City Hotel,0,7,2025,March,11,10,2025-03-10,1,2,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.67,0,1
HB-037343,Resort Hotel,0,148,2025,June,24,13,2025-06-13,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,154.0,1,1
HB-107887,City Hotel,0,17,2025,March,12,18,2025-03-18,1,1,2,0.0,0,BB,SWE,Direct,Direct,0,0,0,G,G,0,No Deposit,,,0,Transient,233.0,0,1
HB-087163,City Hotel,0,38,2024,April,15,10,2024-04-10,2,3,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,137.7,0,1
HB-035968,Resort Hotel,0,0,2025,May,19,5,2025-05-05,0,1,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,77.0,1,0
HB-035480,Resort Hotel,0,62,2025,April,16,19,2025-04-19,1,4,1,0.0,0,BB,AUS,Groups,Corporate,0,0,0,E,E,2,No Deposit,,,0,Transient-Party,74.6,0,0
HB-082393,City Hotel,1,302,2024,October,40,6,2024-10-06,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,3.0,,0,Transient,105.0,0,0
HB-094198,City Hotel,0,147,2024,July,30,25,2024-07-25,2,5,2,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,121.0,,0,Transient,72.25,0,0
HB-019406,Resort Hotel,0,0,2023,December,50,14,2023-12-14,1,3,1,0.0,0,HB,PRT,Corporate,Corporate,0,0,0,A,A,1,No Deposit,,110.0,0,Transient,40.0,0,1
HB-092785,City Hotel,0,99,2024,July,28,9,2024-07-09,2,1,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.5,0,1
HB-013174,Resort Hotel,1,246,2025,August,31,3,2025-08-03,2,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,153.75,0,0
HB-038019,Resort Hotel,0,200,2025,July,27,2,2025-07-02,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient,124.0,1,1
HB-019978,Resort Hotel,0,16,2024,January,2,11,2024-01-11,1,0,1,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,39.0,0,1
HB-036420,Resort Hotel,0,16,2025,May,20,18,2025-05-18,0,2,2,0.0,0,BB,HUN,Online TA,TA/TO,0,0,0,A,H,0,No Deposit,240.0,,0,Transient,85.0,0,2
HB-108931,City Hotel,0,48,2025,April,14,1,2025-04-01,2,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,162.0,0,3
HB-097533,City Hotel,0,24,2024,September,38,16,2024-09-16,0,2,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,139.0,0,1
HB-076472,City Hotel,1,379,2023,October,44,31,2023-10-31,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-074430,City Hotel,1,297,2023,August,32,10,2023-08-10,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-048280,City Hotel,1,56,2024,March,12,19,2024-03-19,2,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.5,0,0
HB-024903,Resort Hotel,0,11,2024,June,23,7,2024-06-07,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,240.0,,0,Transient,109.0,1,1
HB-005206,Resort Hotel,0,191,2024,April,17,22,2024-04-22,1,2,2,0.0,0,Undefined,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,85.33,0,0
HB-013124,Resort Hotel,1,298,2025,August,31,1,2025-08-01,0,5,3,0.0,0,HB,LUX,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,218.18,0,3
HB-100917,City Hotel,0,6,2024,October,44,31,2024-10-31,1,3,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,121.75,0,2
HB-070943,City Hotel,1,213,2025,June,26,26,2025-06-26,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,323.0,,0,Transient,115.0,0,0
HB-007638,Resort Hotel,1,73,2024,August,33,17,2024-08-17,4,9,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,227.92,0,0
HB-112134,City Hotel,0,91,2025,May,20,18,2025-05-18,0,2,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,86.63,0,0
HB-067981,City Hotel,1,329,2025,May,19,10,2025-05-10,0,4,1,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,109.8,0,2
HB-004470,Resort Hotel,1,201,2024,March,12,19,2024-03-19,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,37.54,0,1
HB-008094,Resort Hotel,1,17,2024,September,37,11,2024-09-11,2,2,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,171.0,0,2
HB-071518,City Hotel,1,86,2025,July,28,7,2025-07-07,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,62.0,0,Transient,80.0,0,0
HB-015635,Resort Hotel,0,142,2023,July,28,16,2023-07-16,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Contract,88.4,0,1
HB-095193,City Hotel,0,84,2024,August,33,14,2024-08-14,2,0,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,189.9,0,1
HB-106616,City Hotel,0,1,2025,February,9,26,2025-02-26,2,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-066771,City Hotel,1,148,2025,April,17,25,2025-04-25,0,2,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,0
HB-036836,Resort Hotel,0,337,2025,May,22,28,2025-05-28,2,0,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,240.0,,0,Transient,54.0,0,1
HB-093051,City Hotel,0,157,2024,July,28,14,2024-07-14,0,2,2,1.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient-Party,121.5,0,1
HB-040095,City Hotel,1,92,2023,July,27,6,2023-07-06,1,3,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,68.0,0,2
HB-075617,City Hotel,1,281,2023,July,30,25,2023-07-25,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-037405,Resort Hotel,0,312,2025,June,23,3,2025-06-03,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,68.4,0,0
HB-011775,Resort Hotel,1,72,2025,May,22,29,2025-05-29,3,6,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,Refundable,242.0,,0,Transient,158.33,0,1
HB-091274,City Hotel,0,1,2024,June,24,15,2024-06-15,0,4,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,150.0,1,1
HB-039686,Resort Hotel,0,62,2025,August,34,21,2025-08-21,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,15.0,,0,Transient,205.0,0,2
HB-087973,City Hotel,0,13,2024,April,17,26,2024-04-26,0,3,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,58.0,,0,Transient-Party,96.0,0,0
HB-092242,City Hotel,0,36,2024,July,27,1,2024-07-01,0,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,1
HB-109858,City Hotel,0,206,2025,April,16,16,2025-04-16,2,0,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,1
HB-010392,Resort Hotel,1,8,2025,March,10,3,2025-03-03,1,2,2,0.0,0,BB,PRT,Groups,Corporate,0,0,0,A,A,5,No Deposit,,223.0,0,Transient-Party,37.0,0,0
HB-094440,City Hotel,0,77,2024,July,30,26,2024-07-26,2,7,2,2.0,0,BB,FRA,Direct,Direct,0,0,0,E,E,1,No Deposit,,,0,Transient,160.7,0,2
HB-046316,City Hotel,1,140,2023,December,52,29,2023-12-29,0,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,70.0,0,0
HB-106837,City Hotel,0,0,2025,March,10,3,2025-03-03,0,1,1,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.0,0,0
HB-019721,Resort Hotel,0,14,2023,December,52,30,2023-12-30,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,E,0,No Deposit,,,0,Transient,166.67,0,1
HB-075283,City Hotel,1,299,2023,August,32,12,2023-08-12,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-040354,City Hotel,0,132,2023,July,29,23,2023-07-23,0,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,90.0,0,0
HB-061346,City Hotel,1,17,2024,December,49,8,2024-12-08,0,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,92.67,0,0
HB-066835,City Hotel,1,156,2025,April,17,26,2025-04-26,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,100.0,0,0
HB-102783,City Hotel,0,8,2024,December,49,3,2024-12-03,2,1,2,2.0,0,HB,ESP,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,185.33,0,1
HB-021143,Resort Hotel,0,5,2024,February,7,15,2024-02-15,1,3,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,93.0,0,0
HB-041991,City Hotel,0,145,2023,August,35,29,2023-08-29,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-114053,City Hotel,0,41,2025,June,24,15,2025-06-15,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,112.0,0,1
HB-014362,Resort Hotel,0,45,2025,February,9,25,2025-02-25,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,75.0,1,3
HB-115814,City Hotel,0,68,2025,July,28,10,2025-07-10,1,0,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,100.0,0,1
HB-117685,City Hotel,0,127,2025,August,31,1,2025-08-01,2,5,2,0.0,0,SC,BRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,71.1,0,0
HB-058719,City Hotel,1,40,2024,October,42,15,2024-10-15,0,1,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,176.4,0,1
HB-111079,City Hotel,0,179,2025,May,18,3,2025-05-03,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,117.0,0,2
HB-038059,Resort Hotel,0,45,2025,July,27,1,2025-07-01,2,5,1,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,C,C,1,No Deposit,240.0,,0,Transient,210.0,1,1
HB-111829,City Hotel,0,31,2025,May,20,14,2025-05-14,2,1,1,0.0,0,BB,DEU,Groups,Corporate,0,0,0,A,A,1,No Deposit,459.0,,0,Transient-Party,130.0,0,0
HB-099134,City Hotel,0,349,2024,October,40,4,2024-10-04,1,5,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,B,0,No Deposit,58.0,,162,Transient-Party,96.67,0,0
HB-035754,Resort Hotel,0,75,2025,April,18,29,2025-04-29,1,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,82.0,1,1
HB-052999,City Hotel,1,188,2024,June,24,15,2024-06-15,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,39,Transient,130.0,0,0
HB-030793,Resort Hotel,0,19,2024,December,49,2,2024-12-02,0,2,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,96.0,1,1
HB-020783,Resort Hotel,0,2,2024,February,6,7,2024-02-07,2,0,2,0.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,177.0,,0,Transient,63.0,0,0
HB-100391,City Hotel,0,36,2024,October,43,25,2024-10-25,0,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.0,0,2
HB-099097,City Hotel,0,204,2024,October,41,7,2024-10-07,0,2,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,180.9,0,1
HB-015067,Resort Hotel,0,0,2023,September,38,24,2023-09-24,0,1,1,0.0,0,BB,PRT,Direct,Direct,1,0,3,D,I,1,No Deposit,,,0,Transient,81.0,1,0
HB-079813,City Hotel,0,35,2023,November,44,2,2023-11-02,1,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,28.0,,0,Group,60.0,0,0
HB-084683,City Hotel,0,21,2024,March,9,1,2024-03-01,0,1,2,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,138.0,,0,Transient,64.8,0,0
HB-051517,City Hotel,1,29,2024,May,21,20,2024-05-20,1,2,1,0.0,0,BB,TUR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.6,0,0
HB-054107,City Hotel,1,70,2024,July,27,7,2024-07-07,0,1,2,0.0,0,SC,IDN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,0
HB-081372,City Hotel,1,0,2023,December,49,9,2023-12-09,1,4,2,0.0,0,BB,PRT,Direct,Direct,1,0,0,A,D,0,No Deposit,,,0,Transient,95.0,0,0
HB-004480,Resort Hotel,1,66,2024,March,12,19,2024-03-19,2,6,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,242.0,,0,Transient,82.73,0,1
HB-059151,City Hotel,1,240,2024,October,43,21,2024-10-21,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,110.0,0,0
HB-024411,Resort Hotel,0,41,2024,May,20,16,2024-05-16,1,3,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,125.0,0,0
HB-086350,City Hotel,0,3,2024,March,13,31,2024-03-31,0,1,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,8.0,,0,Transient,106.0,0,1
HB-072520,City Hotel,1,185,2025,July,31,29,2025-07-29,2,6,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,117.9,0,0
HB-040692,City Hotel,0,12,2023,August,31,5,2023-08-05,0,3,2,0.0,0,BB,RUS,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,38.0,0,Transient-Party,65.0,0,0
HB-063875,City Hotel,1,1,2025,February,9,24,2025-02-24,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,B,0,No Deposit,,,0,Transient,88.0,0,2
HB-076704,City Hotel,0,3,2024,September,39,26,2024-09-26,3,7,1,0.0,0,BB,PRT,Corporate,Corporate,1,4,46,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-098407,City Hotel,0,108,2024,September,39,24,2024-09-24,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,B,D,1,No Deposit,9.0,,0,Transient,127.38,0,3
HB-112761,City Hotel,0,137,2025,May,21,25,2025-05-25,0,3,2,2.0,0,BB,POL,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,198.0,0,0
HB-025236,Resort Hotel,0,8,2024,June,24,15,2024-06-15,0,4,3,1.0,0,BB,BRA,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,196.0,1,0
HB-096196,City Hotel,0,65,2024,August,35,26,2024-08-26,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,269.0,,0,Transient-Party,134.0,0,0
HB-088647,City Hotel,0,16,2024,May,19,6,2024-05-06,2,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,7.0,,0,Transient,194.58,0,2
HB-057502,City Hotel,0,418,2024,September,39,26,2024-09-26,1,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,132.0,,223,Transient-Party,107.0,0,0
HB-038458,Resort Hotel,0,12,2025,July,28,12,2025-07-12,2,5,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,172.14,0,0
HB-067753,City Hotel,1,45,2025,May,19,6,2025-05-06,2,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,152.1,0,0
HB-077715,City Hotel,0,1,2023,September,38,24,2023-09-24,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,147.0,0,0
HB-113630,City Hotel,0,118,2025,June,23,8,2025-06-08,0,2,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,126.0,0,1
HB-048263,City Hotel,1,108,2024,March,12,19,2024-03-19,2,1,2,0.0,1,BB,ESP,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,116.0,0,2
HB-007961,Resort Hotel,0,373,2024,September,36,4,2024-09-04,4,6,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,,,0,Transient,105.02,0,0
HB-039222,Resort Hotel,0,152,2025,August,32,7,2025-08-07,1,4,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,220.0,0,2
HB-042040,City Hotel,1,104,2023,August,35,30,2023-08-30,2,1,2,0.0,0,HB,ESP,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,90.0,0,0
HB-038886,Resort Hotel,0,335,2025,July,30,24,2025-07-24,3,6,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,134.85,0,1
HB-085521,City Hotel,0,46,2024,March,11,14,2024-03-14,1,2,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,107.1,0,0
HB-046311,City Hotel,1,208,2023,December,52,29,2023-12-29,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,75.44,0,0
HB-105119,City Hotel,0,71,2025,January,4,26,2025-01-26,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,96.9,0,2
HB-014407,Resort Hotel,0,1,2024,August,35,28,2024-08-28,2,1,2,1.0,0,HB,,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,140.0,0,0
HB-026735,Resort Hotel,0,3,2024,August,32,8,2024-08-08,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,236.0,0,1
HB-035420,Resort Hotel,0,232,2025,April,16,15,2025-04-15,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,56.89,0,2
HB-057450,City Hotel,1,213,2024,September,39,26,2024-09-26,1,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,E,E,0,Non Refund,,51.0,0,Transient-Party,106.0,0,0
HB-016315,Resort Hotel,0,54,2023,August,33,18,2023-08-18,0,5,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,151.23,0,1
HB-049994,City Hotel,1,58,2024,April,17,22,2024-04-22,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,118.8,0,0
HB-003522,Resort Hotel,1,39,2023,December,51,21,2023-12-21,3,6,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,50.77,0,2
HB-086642,City Hotel,0,55,2024,April,14,6,2024-04-06,0,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,B,0,No Deposit,56.0,,0,Transient-Party,104.0,0,0
HB-016122,Resort Hotel,0,90,2023,August,32,11,2023-08-11,0,5,2,1.0,0,HB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,196.34,1,2
HB-024327,Resort Hotel,0,116,2024,May,20,13,2024-05-13,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,75.0,0,2
HB-004485,Resort Hotel,1,20,2024,March,12,20,2024-03-20,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,60.0,0,2
HB-044207,City Hotel,1,164,2023,October,40,2,2023-10-02,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,19.0,,0,Transient-Party,100.0,0,0
HB-074446,City Hotel,1,304,2023,August,33,17,2023-08-17,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-072635,City Hotel,1,20,2025,August,31,1,2025-08-01,2,5,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,230.0,0,1
HB-060819,City Hotel,1,15,2024,November,47,22,2024-11-22,2,5,2,0.0,0,SC,ZAF,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,77.35,0,2
HB-013188,Resort Hotel,1,42,2025,August,32,4,2025-08-04,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,212.5,0,0
HB-078829,City Hotel,1,9,2023,October,42,21,2023-10-21,2,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,D,D,0,No Deposit,9.0,,0,Contract,139.17,0,1
HB-023503,Resort Hotel,0,9,2024,April,17,25,2024-04-25,1,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,50.05,0,1
HB-070860,City Hotel,1,233,2025,June,26,23,2025-06-23,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,105.0,0,0
HB-021817,Resort Hotel,0,81,2024,March,10,9,2024-03-09,0,3,3,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,A,C,0,No Deposit,115.0,,0,Transient-Party,86.55,0,0
HB-081379,City Hotel,0,8,2023,December,49,9,2023-12-09,0,1,1,0.0,0,BB,FRA,Corporate,Corporate,0,0,0,A,A,0,No Deposit,91.0,,0,Transient,79.0,0,0
HB-022773,Resort Hotel,0,25,2024,April,14,4,2024-04-04,1,1,1,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,1,Non Refund,298.0,,0,Transient-Party,54.5,0,0
HB-117069,City Hotel,0,36,2025,July,31,28,2025-07-28,0,1,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,86.0,,0,Transient,144.0,0,1
HB-026257,Resort Hotel,0,161,2024,July,29,19,2024-07-19,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,26.0,,0,Transient,97.76,0,0
HB-105656,City Hotel,0,0,2025,February,7,11,2025-02-11,1,1,2,1.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,2,No Deposit,,,0,Transient,134.0,0,1
HB-017809,Resort Hotel,0,5,2023,November,45,9,2023-11-09,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,D,0,No Deposit,,,0,Transient,54.0,1,0
HB-071767,City Hotel,1,122,2025,July,28,12,2025-07-12,0,2,3,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,222.3,0,0
HB-030864,Resort Hotel,0,92,2024,December,49,3,2024-12-03,2,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,336.0,,0,Transient,34.0,0,2
HB-073139,City Hotel,1,309,2025,August,33,15,2025-08-15,0,4,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,0
HB-094507,City Hotel,0,28,2024,August,31,4,2024-08-04,0,1,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,125.1,0,2
HB-034605,Resort Hotel,0,18,2025,March,13,28,2025-03-28,0,3,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,314.0,,0,Transient,80.0,0,0
HB-027427,Resort Hotel,0,30,2024,August,35,27,2024-08-27,1,1,3,1.0,0,BB,ITA,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,286.0,1,1
HB-107793,City Hotel,0,182,2025,March,11,11,2025-03-11,2,6,2,0.0,0,BB,GBR,Corporate,TA/TO,0,0,0,A,A,0,No Deposit,330.0,,0,Transient-Party,90.0,0,1
HB-001898,Resort Hotel,0,103,2023,September,38,20,2023-09-20,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,241.0,,0,Transient,58.98,0,0
HB-118752,City Hotel,0,30,2025,August,34,23,2025-08-23,0,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,129.5,0,1
HB-069012,City Hotel,1,130,2025,May,21,24,2025-05-24,0,4,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,198.0,0,1
HB-084258,City Hotel,0,81,2024,February,8,19,2024-02-19,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,60.0,0,0
HB-013006,Resort Hotel,1,199,2025,July,30,27,2025-07-27,2,4,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,183.75,0,2
HB-111072,City Hotel,0,8,2025,May,18,2,2025-05-02,0,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,160.0,0,0
HB-026820,Resort Hotel,0,226,2024,August,32,8,2024-08-08,1,3,2,0.0,1,BB,PRT,Online TA,TA/TO,0,0,0,A,D,2,No Deposit,240.0,,0,Transient,138.0,1,2
HB-004999,Resort Hotel,1,212,2024,April,15,11,2024-04-11,2,5,2,0.0,0,HB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,273.0,,0,Transient,67.05,0,0
HB-116860,City Hotel,0,54,2025,July,30,24,2025-07-24,1,1,2,0.0,0,SC,TUR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.0,0,1
HB-019374,Resort Hotel,0,16,2023,December,50,14,2023-12-14,1,1,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,36.0,,0,Transient,31.2,0,0
HB-008881,Resort Hotel,1,71,2024,October,42,18,2024-10-18,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,44.66,0,1
HB-013056,Resort Hotel,1,335,2025,July,31,29,2025-07-29,2,5,2,0.0,0,HB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,167.18,0,2
HB-023611,Resort Hotel,0,12,2024,April,17,27,2024-04-27,0,3,2,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,A,A,1,No Deposit,385.0,,0,Transient-Party,85.33,0,0
HB-078470,City Hotel,0,24,2023,October,40,8,2023-10-08,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,9.0,,0,Contract,107.0,0,2
HB-086933,City Hotel,0,9,2024,April,15,8,2024-04-08,1,2,1,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,131.33,0,1
HB-013672,Resort Hotel,1,172,2025,August,35,25,2025-08-25,2,5,3,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,5.0,,0,Transient,259.0,0,0
HB-066604,City Hotel,1,206,2025,April,17,22,2025-04-22,2,1,1,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.8,0,0
HB-091904,City Hotel,0,53,2024,June,26,24,2024-06-24,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,B,0,No Deposit,1.0,,0,Transient-Party,65.0,0,1
HB-025232,Resort Hotel,0,7,2024,June,25,18,2024-06-18,0,1,2,1.0,0,BB,CN,Direct,Direct,0,0,0,E,E,1,No Deposit,250.0,,0,Transient-Party,158.1,0,1
HB-068970,City Hotel,1,305,2025,May,21,24,2025-05-24,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,1
HB-099927,City Hotel,0,159,2024,October,42,16,2024-10-16,2,2,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,108.0,0,0
HB-075088,City Hotel,1,283,2023,July,30,27,2023-07-27,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-017119,Resort Hotel,0,0,2023,September,38,23,2023-09-23,0,3,2,0.0,0,BB,NLD,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient,172.33,1,0
HB-013573,Resort Hotel,1,360,2025,August,34,20,2025-08-20,2,4,3,1.0,0,HB,PRT,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,343.0,0,0
HB-093149,City Hotel,0,7,2024,July,29,16,2024-07-16,1,1,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,139.0,0,0
HB-102076,City Hotel,0,215,2024,November,47,21,2024-11-21,1,1,1,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,1,No Deposit,,233.0,0,Transient,75.0,0,0
HB-103385,City Hotel,0,3,2024,December,51,19,2024-12-19,1,2,1,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.5,0,0
HB-077184,City Hotel,0,0,2023,September,36,10,2023-09-10,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,114.0,0,0
HB-074662,City Hotel,1,359,2023,October,41,11,2023-10-11,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-065243,City Hotel,1,629,2025,March,13,30,2025-03-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-095888,City Hotel,0,4,2024,September,36,6,2024-09-06,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,40.0,0,Transient,67.0,1,1
HB-089921,City Hotel,0,24,2024,May,22,29,2024-05-29,1,0,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,159.0,0,2
HB-011280,Resort Hotel,1,221,2025,April,18,30,2025-04-30,2,5,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,83.43,0,0
HB-020647,Resort Hotel,0,0,2024,February,5,4,2024-02-04,0,2,2,0.0,1,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,38.4,0,0
HB-096134,City Hotel,0,115,2024,August,34,22,2024-08-22,2,5,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,27.0,,0,Transient,82.45,0,0
HB-002151,Resort Hotel,1,192,2023,October,40,3,2023-10-03,2,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,38.07,0,0
HB-093380,City Hotel,0,1,2024,July,29,20,2024-07-20,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,111.0,0,0
HB-005085,Resort Hotel,0,183,2024,April,16,16,2024-04-16,1,1,1,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,1,No Deposit,298.0,,0,Transient-Party,54.5,0,0
HB-106235,City Hotel,0,11,2025,February,8,20,2025-02-20,1,2,1,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,69.3,0,0
HB-011489,Resort Hotel,1,0,2025,May,19,11,2025-05-11,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,80.0,0,0
HB-013692,Resort Hotel,1,142,2025,August,35,26,2025-08-26,2,5,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,96.0,,0,Transient,155.0,0,0
HB-103518,City Hotel,0,92,2024,December,51,22,2024-12-22,2,3,2,0.0,0,BB,GRC,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,96.9,0,1
HB-069736,City Hotel,1,46,2025,June,23,5,2025-06-05,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,159.0,,0,Transient,170.0,0,0
HB-005608,Resort Hotel,1,164,2024,May,18,5,2024-05-05,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,240.0,,0,Transient-Party,65.7,0,0
HB-088487,City Hotel,0,54,2024,May,19,6,2024-05-06,0,1,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,G,0,No Deposit,9.0,,0,Transient,198.9,0,2
HB-052946,City Hotel,1,71,2024,June,24,14,2024-06-14,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,120.0,0,0
HB-052391,City Hotel,1,102,2024,June,23,5,2024-06-05,1,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,65.0,0,0
HB-116620,City Hotel,0,21,2025,July,29,20,2025-07-20,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,159.33,0,1
HB-054693,City Hotel,1,192,2024,July,30,23,2024-07-23,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,99.45,0,0
HB-025041,Resort Hotel,0,155,2024,June,24,10,2024-06-10,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,72.0,0,0
HB-035112,Resort Hotel,0,0,2025,April,15,13,2025-04-13,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,131.0,0,0
HB-002319,Resort Hotel,1,78,2023,October,41,9,2023-10-09,1,2,2,0.0,0,FB,ESP,Groups,TA/TO,0,0,0,A,A,0,Non Refund,134.0,,0,Transient,92.0,0,0
HB-111355,City Hotel,0,2,2025,May,22,31,2025-05-31,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,3,A,A,0,No Deposit,,238.0,0,Transient,65.0,0,0
HB-100029,City Hotel,0,26,2024,October,42,16,2024-10-16,2,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,139.0,0,1
HB-099557,City Hotel,0,2,2024,October,41,13,2024-10-13,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,344.0,,0,Transient,109.65,0,0
HB-067462,City Hotel,1,118,2025,May,18,3,2025-05-03,1,4,1,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.8,0,1
HB-118145,City Hotel,0,504,2025,August,33,12,2025-08-12,2,1,2,0.0,0,BB,USA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,1
HB-072176,City Hotel,1,240,2025,July,30,23,2025-07-23,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-080990,City Hotel,1,22,2023,December,51,18,2023-12-18,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,1,0,A,A,0,No Deposit,,40.0,0,Transient-Party,65.0,0,0
HB-066844,City Hotel,1,156,2025,April,17,26,2025-04-26,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,100.0,0,0
HB-055903,City Hotel,1,137,2024,August,34,24,2024-08-24,0,4,3,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.95,0,0
HB-076155,City Hotel,0,185,2023,July,27,6,2023-07-06,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,66.13,0,0
HB-037022,Resort Hotel,0,23,2025,June,23,2,2025-06-02,0,2,3,0.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,F,F,0,No Deposit,,,0,Transient,198.4,1,0
HB-013204,Resort Hotel,1,178,2025,August,32,4,2025-08-04,2,5,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,,0,Transient,203.13,0,2
HB-118631,City Hotel,0,0,2025,August,34,21,2025-08-21,1,1,2,0.0,0,SC,AUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,2
HB-027869,Resort Hotel,0,214,2024,September,36,5,2024-09-05,3,6,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,69.0,,0,Transient,72.0,0,1
HB-109863,City Hotel,0,62,2025,April,16,15,2025-04-15,2,1,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,177.0,0,0
HB-054479,City Hotel,1,140,2024,July,29,17,2024-07-17,2,0,2,0.0,0,SC,RUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.5,0,0
HB-016801,Resort Hotel,0,2,2023,September,36,10,2023-09-10,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,C,0,No Deposit,,,0,Transient,131.0,0,0
HB-098163,City Hotel,0,28,2024,September,38,22,2024-09-22,1,3,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,220.53,0,1
HB-036516,Resort Hotel,0,222,2025,May,20,16,2025-05-16,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,143.0,,0,Transient,42.95,0,1
HB-035201,Resort Hotel,0,17,2025,April,15,13,2025-04-13,0,3,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,152.0,0,2
HB-053309,City Hotel,1,290,2024,June,25,17,2024-06-17,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,108,Transient-Party,72.0,0,0
HB-081596,City Hotel,1,197,2024,June,23,3,2024-06-03,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,21.0,,25,Transient,80.0,0,0
HB-006471,Resort Hotel,1,277,2024,June,24,12,2024-06-12,2,2,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-060067,City Hotel,1,11,2024,November,45,5,2024-11-05,0,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.0,0,1
HB-052087,City Hotel,1,17,2024,May,22,30,2024-05-30,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,102.15,0,0
HB-100872,City Hotel,0,91,2024,October,44,30,2024-10-30,2,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,61.33,0,1
HB-034571,Resort Hotel,0,48,2025,March,12,23,2025-03-23,2,5,1,0.0,0,Undefined,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,464.0,,0,Transient,47.0,0,0
HB-045270,City Hotel,0,69,2023,October,43,25,2023-10-25,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,58,Transient-Party,85.67,0,0
HB-039109,Resort Hotel,0,19,2025,August,32,4,2025-08-04,2,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,175.14,1,1
HB-056227,City Hotel,1,419,2024,September,35,1,2024-09-01,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-029342,Resort Hotel,0,176,2024,October,42,19,2024-10-19,2,6,2,0.0,0,HB,IRL,Offline TA/TO,TA/TO,0,0,0,A,C,0,No Deposit,177.0,,0,Transient,72.0,0,0
HB-082735,City Hotel,0,102,2024,January,1,3,2024-01-03,2,1,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,27.0,,0,Transient,48.67,0,2
HB-068308,City Hotel,1,164,2025,May,20,15,2025-05-15,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-060525,City Hotel,1,50,2024,November,46,13,2024-11-13,2,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,114.0,0,2
HB-065521,City Hotel,1,334,2025,April,14,4,2025-04-04,2,6,1,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.1,0,0
HB-027073,Resort Hotel,0,173,2024,August,33,15,2024-08-15,1,3,3,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,196.0,,0,Transient,143.0,0,0
HB-083510,City Hotel,0,31,2024,February,5,4,2024-02-04,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,2,No Deposit,,174.0,0,Transient-Party,71.0,0,0
HB-020452,Resort Hotel,0,303,2024,July,28,13,2024-07-13,0,4,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,1,G,G,0,No Deposit,240.0,,0,Transient,159.38,1,2
HB-026974,Resort Hotel,0,83,2025,August,32,7,2025-08-07,1,5,2,0.0,0,BB,ITA,Online TA,TA/TO,1,0,0,A,A,0,No Deposit,240.0,,0,Transient,230.0,0,2
HB-024330,Resort Hotel,0,113,2024,May,19,7,2024-05-07,4,7,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,147.0,,0,Transient,78.94,0,1
HB-095312,City Hotel,0,43,2024,August,33,15,2024-08-15,1,2,2,1.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,203.85,1,1
HB-008814,Resort Hotel,1,198,2024,October,42,15,2024-10-15,2,5,2,2.0,0,BB,AUT,Online TA,TA/TO,0,0,0,G,G,1,No Deposit,240.0,,0,Transient-Party,124.14,0,0
HB-007651,Resort Hotel,1,149,2024,August,33,18,2024-08-18,1,3,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,256.75,0,0
HB-100533,City Hotel,0,0,2024,October,44,28,2024-10-28,0,1,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,150.0,0,0
HB-112972,City Hotel,0,0,2025,May,22,31,2025-05-31,0,2,1,0.0,0,BB,BEL,Aviation,Corporate,1,0,0,A,A,0,No Deposit,,153.0,0,Transient,95.0,0,0
HB-050077,City Hotel,1,142,2024,April,17,22,2024-04-22,2,3,2,0.0,0,BB,POL,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,103.0,0,0
HB-110733,City Hotel,0,17,2025,April,18,29,2025-04-29,1,1,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,149.0,0,1
HB-033236,Resort Hotel,0,10,2025,February,7,15,2025-02-15,0,3,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,467.0,,0,Transient,84.24,0,0
HB-066945,City Hotel,1,170,2025,April,17,26,2025-04-26,0,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.5,0,2
HB-052756,City Hotel,1,16,2024,June,24,11,2024-06-11,0,1,2,2.0,0,BB,USA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,221.0,0,0
HB-011845,Resort Hotel,1,263,2025,June,22,1,2025-06-01,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,89.0,0,0
HB-027135,Resort Hotel,0,32,2024,August,33,15,2024-08-15,1,5,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,2,No Deposit,250.0,,0,Transient,199.1,0,0
HB-064843,City Hotel,1,74,2025,March,12,17,2025-03-17,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.2,0,0
HB-079972,City Hotel,0,26,2023,November,44,3,2023-11-03,1,5,2,0.0,0,BB,PAN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.45,0,0
HB-050428,City Hotel,1,32,2024,April,18,30,2024-04-30,2,1,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,9.0,,0,Transient,198.9,0,0
HB-023282,Resort Hotel,0,91,2024,April,15,14,2024-04-14,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,40.0,,0,Contract,84.95,0,0
HB-095452,City Hotel,0,12,2024,August,34,19,2024-08-19,0,1,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,220.0,0,0
HB-052626,City Hotel,1,27,2024,June,23,9,2024-06-09,0,1,2,0.0,0,BB,PRT,Offline TA/TO,Corporate,0,0,0,A,A,0,No Deposit,191.0,,0,Transient-Party,120.0,0,0
HB-053018,City Hotel,1,188,2024,June,24,15,2024-06-15,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,39,Transient,130.0,0,0
HB-084036,City Hotel,0,0,2024,March,12,23,2024-03-23,0,1,1,0.0,0,BB,PRT,Direct,Direct,1,0,1,A,A,1,No Deposit,,,0,Transient,89.0,0,0
HB-033251,Resort Hotel,0,11,2025,February,8,18,2025-02-18,0,1,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,C,C,1,No Deposit,240.0,,0,Transient,75.0,0,2
HB-042467,City Hotel,0,1,2023,September,36,6,2023-09-06,2,0,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,75.0,0,0
HB-047794,City Hotel,1,15,2024,March,10,4,2024-03-04,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,88.8,0,0
HB-006123,Resort Hotel,0,225,2024,May,21,26,2024-05-26,0,3,1,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,A,2,No Deposit,,223.0,0,Transient-Party,60.0,0,0
HB-019420,Resort Hotel,0,105,2023,December,50,14,2023-12-14,1,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,31.88,0,1
HB-051474,City Hotel,1,211,2024,May,21,20,2024-05-20,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,111,Transient,100.0,0,0
HB-063274,City Hotel,1,26,2025,February,6,4,2025-02-04,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,83.3,0,0
HB-094334,City Hotel,0,165,2024,August,31,1,2024-08-01,1,1,2,1.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,94.56,0,2
HB-047681,City Hotel,1,1,2024,February,9,28,2024-02-28,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,60.0,0,0
HB-033951,Resort Hotel,0,4,2025,March,10,7,2025-03-07,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,65.0,0,1
HB-031252,Resort Hotel,0,60,2024,December,50,15,2024-12-15,2,3,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,57.93,1,2
HB-000424,Resort Hotel,0,57,2023,July,28,15,2023-07-15,0,2,3,0.0,0,FB,PRT,Groups,Direct,0,0,0,A,C,1,No Deposit,305.0,,0,Transient-Party,148.23,0,0
HB-058987,City Hotel,1,50,2024,October,42,20,2024-10-20,0,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,0
HB-104496,City Hotel,0,30,2025,January,3,13,2025-01-13,0,2,2,1.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,22.0,,0,Transient,136.0,0,0
HB-081032,City Hotel,1,86,2024,January,4,22,2024-01-22,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,29.0,,35,Transient,85.0,0,0
HB-104086,City Hotel,0,53,2024,December,1,31,2024-12-31,2,3,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,194.4,0,3
HB-070964,City Hotel,1,213,2025,June,26,26,2025-06-26,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,323.0,,0,Transient,115.0,0,0
HB-082086,City Hotel,0,22,2023,December,50,15,2023-12-15,0,5,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,69.0,0,0
HB-036131,Resort Hotel,0,27,2025,May,19,8,2025-05-08,1,2,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,86.0,0,1
HB-097779,City Hotel,0,172,2024,September,38,18,2024-09-18,2,1,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,22.0,,0,Transient,90.95,0,1
HB-051315,City Hotel,1,323,2024,May,20,17,2024-05-17,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,70.0,0,0
HB-110331,City Hotel,0,31,2025,April,17,21,2025-04-21,2,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,85.0,0,0
HB-088333,City Hotel,0,83,2024,May,18,1,2024-05-01,2,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient-Party,75.0,0,1
HB-030984,Resort Hotel,0,22,2024,December,49,8,2024-12-08,0,3,2,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,38.0,,0,Transient-Party,80.0,0,0
HB-052905,City Hotel,1,71,2024,June,24,14,2024-06-14,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,120.0,0,0
HB-082147,City Hotel,1,99,2024,February,8,19,2024-02-19,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,1,0,A,A,0,No Deposit,,67.0,0,Transient-Party,80.0,0,0
HB-111920,City Hotel,0,309,2025,May,20,13,2025-05-13,2,3,2,0.0,0,BB,MOZ,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,467.0,,0,Transient-Party,89.1,0,0
HB-102558,City Hotel,0,11,2024,November,48,27,2024-11-27,2,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,379.0,0,Transient,89.89,0,2
HB-097587,City Hotel,0,22,2024,September,37,15,2024-09-15,0,3,2,0.0,0,SC,CZE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,139.0,0,3
HB-015169,Resort Hotel,1,244,2023,September,35,2,2023-09-02,2,5,2,0.0,0,BB,IRL,Groups,TA/TO,0,24,0,A,A,0,No Deposit,96.0,,0,Transient-Party,8.0,0,0
HB-110485,City Hotel,0,42,2025,April,17,23,2025-04-23,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,144.0,0,0
HB-111008,City Hotel,0,207,2025,May,18,2,2025-05-02,0,3,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,2
HB-061275,City Hotel,1,14,2024,December,49,6,2024-12-06,2,5,1,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.1,0,0
HB-022133,Resort Hotel,0,1,2024,March,11,15,2024-03-15,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,48.0,0,0
HB-087052,City Hotel,0,1,2024,April,15,13,2024-04-13,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-039022,Resort Hotel,0,3,2025,August,32,4,2025-08-04,0,2,2,0.0,0,BB,PHL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,164.0,0,1
HB-066053,City Hotel,1,155,2025,April,15,13,2025-04-13,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,0,Transient,130.0,0,0
HB-068281,City Hotel,1,164,2025,May,20,15,2025-05-15,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-027807,Resort Hotel,0,13,2024,September,37,11,2024-09-11,2,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,250.0,,0,Transient,99.0,0,0
HB-098932,City Hotel,0,47,2024,October,40,4,2024-10-04,0,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.8,0,1
HB-086430,City Hotel,0,50,2024,March,13,31,2024-03-31,0,3,2,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,65.0,0,0
HB-004259,Resort Hotel,1,82,2024,February,9,27,2024-02-27,1,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,39.0,0,0
HB-039140,Resort Hotel,0,165,2025,July,31,28,2025-07-28,4,8,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient-Party,163.5,0,0
HB-084374,City Hotel,0,18,2024,February,8,22,2024-02-22,1,2,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,120.0,0,2
HB-070403,City Hotel,1,226,2025,June,25,16,2025-06-16,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,105.0,0,0
HB-067690,City Hotel,1,86,2025,May,19,6,2025-05-06,2,1,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,171.0,0,0
HB-077130,City Hotel,0,30,2023,September,36,6,2023-09-06,2,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,E,0,No Deposit,40.0,,0,Transient,65.0,0,0
HB-017686,Resort Hotel,0,287,2023,October,41,15,2023-10-15,1,3,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,D,1,No Deposit,,223.0,0,Transient-Party,50.5,1,0
HB-031946,Resort Hotel,0,1,2025,February,6,8,2025-02-08,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,1,0,2,A,D,0,No Deposit,240.0,,0,Transient,43.0,0,0
HB-025758,Resort Hotel,0,164,2024,June,26,30,2024-06-30,2,8,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Contract,57.8,0,0
HB-112674,City Hotel,0,108,2025,May,21,22,2025-05-22,1,4,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,183.6,0,0
HB-021362,Resort Hotel,0,12,2024,February,8,21,2024-02-21,2,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,64.0,1,1
HB-033493,Resort Hotel,0,2,2025,February,8,23,2025-02-23,0,2,3,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,C,1,No Deposit,68.0,,0,Transient-Party,82.5,0,0
HB-063743,City Hotel,1,33,2025,February,8,20,2025-02-20,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,70.0,0,1
HB-085730,City Hotel,0,13,2024,March,12,20,2024-03-20,1,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,220.0,,0,Transient-Party,85.0,0,1
HB-003424,Resort Hotel,0,45,2023,December,49,5,2023-12-05,2,1,2,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,38.0,,0,Transient-Party,68.0,0,0
HB-000217,Resort Hotel,1,105,2023,July,27,8,2023-07-08,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,73.8,0,1
HB-006097,Resort Hotel,1,100,2024,May,21,25,2024-05-25,0,4,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,105.0,0,2
HB-034318,Resort Hotel,0,207,2025,March,11,16,2025-03-16,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,37.8,0,3
HB-099405,City Hotel,0,126,2024,October,41,9,2024-10-09,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient,110.7,0,4
HB-108214,City Hotel,0,11,2025,March,12,20,2025-03-20,1,3,1,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,108.8,0,0
HB-033708,Resort Hotel,0,0,2025,February,9,27,2025-02-27,1,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,62.0,1,0
HB-099435,City Hotel,0,111,2024,October,41,10,2024-10-10,1,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,234.0,,0,Transient-Party,120.0,0,0
HB-093575,City Hotel,0,292,2024,July,29,21,2024-07-21,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,6.0,,0,Transient-Party,112.0,0,0
HB-107056,City Hotel,0,36,2025,March,10,4,2025-03-04,2,1,3,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,248.0,0,1
HB-011593,Resort Hotel,1,98,2025,May,21,19,2025-05-19,2,6,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,123.0,0,2
HB-103355,City Hotel,0,24,2024,December,51,18,2024-12-18,2,1,1,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,104.0,0,1
HB-086947,City Hotel,0,7,2024,April,15,11,2024-04-11,1,0,1,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.0,0,0
HB-008462,Resort Hotel,1,231,2024,September,40,30,2024-09-30,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,96.0,,0,Transient,57.6,0,0
HB-004572,Resort Hotel,0,136,2024,March,12,24,2024-03-24,0,3,2,0.0,0,Undefined,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,387.0,,0,Transient-Party,84.0,0,0
HB-003565,Resort Hotel,0,65,2023,December,51,23,2023-12-23,2,8,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,82.17,0,1
HB-034108,Resort Hotel,0,274,2025,March,11,10,2025-03-10,1,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,57.8,0,2
HB-089553,City Hotel,0,100,2024,May,20,19,2024-05-19,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,9.0,,0,Transient-Party,136.0,0,1
HB-117640,City Hotel,0,183,2025,July,31,31,2025-07-31,2,5,2,1.0,0,BB,IRN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,148.5,0,2
HB-109335,City Hotel,0,3,2025,April,15,9,2025-04-09,1,0,1,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,112.0,0,1
HB-066239,City Hotel,1,87,2025,April,16,15,2025-04-15,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,95.0,0,0
HB-103600,City Hotel,0,81,2024,December,52,23,2024-12-23,2,3,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,119.0,0,0
HB-056759,City Hotel,1,147,2024,September,37,12,2024-09-12,1,5,2,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.9,0,0
HB-049773,City Hotel,1,103,2024,April,16,19,2024-04-19,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,0,Transient,115.0,0,0
HB-070647,City Hotel,1,46,2025,June,25,20,2025-06-20,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,90.0,0,0
HB-034866,Resort Hotel,0,15,2025,March,13,30,2025-03-30,2,6,1,0.0,0,Undefined,PRT,Corporate,Corporate,0,0,0,A,A,1,No Deposit,,523.0,0,Transient-Party,90.0,0,0
HB-098832,City Hotel,0,34,2024,October,40,2,2024-10-02,2,1,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,117.0,0,0
HB-088787,City Hotel,0,27,2025,June,26,27,2025-06-27,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,24,A,A,1,No Deposit,,219.0,0,Transient,104.0,1,2
HB-002881,Resort Hotel,0,24,2023,November,44,3,2023-11-03,3,10,2,0.0,0,BB,ESP,Corporate,Corporate,0,0,0,A,A,2,No Deposit,334.0,281.0,0,Transient-Party,48.0,0,0
HB-010021,Resort Hotel,1,95,2025,February,6,6,2025-02-06,1,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,62.0,0,0
HB-058487,City Hotel,1,113,2024,October,41,13,2024-10-13,0,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-062152,City Hotel,1,177,2025,January,1,3,2025-01-03,0,1,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,153.0,0,2
HB-070391,City Hotel,1,226,2025,June,25,16,2025-06-16,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,105.0,0,0
HB-086875,City Hotel,0,134,2024,April,15,9,2024-04-09,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,90.0,0,1
HB-067671,City Hotel,1,39,2025,May,19,5,2025-05-05,2,3,2,0.0,0,SC,UKR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,149.0,0,0
HB-110966,City Hotel,0,46,2025,May,18,2,2025-05-02,0,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,152.1,0,2
HB-065863,City Hotel,1,66,2025,April,15,9,2025-04-09,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-046692,City Hotel,0,18,2024,January,3,15,2024-01-15,2,3,2,0.0,0,BB,IRQ,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient-Party,89.0,0,1
HB-028471,Resort Hotel,0,342,2024,September,39,29,2024-09-29,2,4,1,0.0,0,BB,IRL,Groups,TA/TO,0,0,0,A,A,0,No Deposit,201.0,,0,Transient-Party,36.0,0,0
HB-100288,City Hotel,0,87,2024,October,43,23,2024-10-23,2,1,2,0.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,A,C,0,No Deposit,42.0,,0,Transient,106.25,0,1
HB-089634,City Hotel,0,51,2024,May,21,23,2024-05-23,1,0,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.9,1,0
HB-065117,City Hotel,1,58,2025,March,13,24,2025-03-24,2,6,2,2.0,0,BB,ARE,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,198.0,0,0
HB-001879,Resort Hotel,0,99,2023,September,38,19,2023-09-19,2,3,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,F,0,No Deposit,240.0,,0,Transient,127.0,1,0
HB-114014,City Hotel,0,37,2025,June,24,14,2025-06-14,0,2,2,0.0,0,BB,KOR,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,130.0,0,0
HB-054309,City Hotel,1,60,2024,July,28,12,2024-07-12,0,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.3,0,0
HB-008526,Resort Hotel,1,55,2024,October,40,3,2024-10-03,3,6,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,89.0,0,2
HB-103132,City Hotel,0,38,2024,December,50,10,2024-12-10,2,1,2,2.0,0,BB,PHL,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,143.0,0,0
HB-102932,City Hotel,0,3,2024,December,49,6,2024-12-06,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,81.88,0,0
HB-028962,Resort Hotel,0,239,2024,October,41,8,2024-10-08,3,6,2,0.0,1,BB,GBR,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,241.0,,0,Transient,51.5,0,2
HB-077621,City Hotel,0,10,2023,September,38,22,2023-09-22,0,2,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,114.0,0,0
HB-019609,Resort Hotel,0,3,2023,December,51,22,2023-12-22,2,5,2,0.0,0,HB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,175.0,,0,Transient,53.71,0,0
HB-110664,City Hotel,0,289,2025,April,17,27,2025-04-27,0,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.8,0,1
HB-033936,Resort Hotel,0,7,2025,March,9,2,2025-03-02,2,3,1,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,2,No Deposit,,223.0,0,Transient-Party,37.0,0,0
HB-079759,City Hotel,0,0,2023,November,44,2,2023-11-02,1,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Contract,104.0,0,1
HB-040233,City Hotel,1,103,2023,July,29,18,2023-07-18,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-066232,City Hotel,1,87,2025,April,16,15,2025-04-15,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,95.0,0,0
HB-084287,City Hotel,0,6,2024,February,8,20,2024-02-20,1,1,2,0.0,0,SC,IND,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,81.0,0,0
HB-055366,City Hotel,1,398,2024,August,32,11,2024-08-11,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-018235,Resort Hotel,0,2,2023,November,46,13,2023-11-13,0,2,4,0.0,0,BB,PRT,Direct,Direct,0,0,0,H,H,0,No Deposit,,,0,Transient,129.0,0,0
HB-045531,City Hotel,0,76,2023,November,44,1,2023-11-01,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,72.25,0,1
HB-106836,City Hotel,0,3,2025,March,9,2,2025-03-02,0,2,1,0.0,0,BB,DZA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,75.0,0,1
HB-028947,Resort Hotel,0,364,2024,October,41,12,2024-10-12,1,4,2,0.0,0,BB,PRT,Groups,Corporate,0,0,0,A,C,1,No Deposit,,223.0,0,Transient-Party,66.0,0,0
HB-027410,Resort Hotel,0,152,2024,August,33,16,2024-08-16,3,10,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,126.33,0,1
HB-085671,City Hotel,0,53,2024,March,11,17,2024-03-17,0,3,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient-Party,101.4,0,0
HB-010390,Resort Hotel,1,8,2025,March,10,3,2025-03-03,1,2,2,0.0,0,BB,PRT,Groups,Corporate,0,0,0,D,D,2,No Deposit,,223.0,0,Transient-Party,47.0,0,0
HB-029485,Resort Hotel,0,82,2024,October,43,23,2024-10-23,2,4,1,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,51.0,0,2
HB-055834,City Hotel,1,139,2024,August,34,22,2024-08-22,1,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,103.05,0,0
HB-042918,City Hotel,1,17,2023,September,37,11,2023-09-11,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,126.0,0,0
HB-076406,City Hotel,1,163,2023,July,30,24,2023-07-24,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,1
HB-093792,City Hotel,0,69,2024,July,30,25,2024-07-25,1,1,3,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,9.0,,0,Transient,137.7,0,0
HB-006835,Resort Hotel,0,255,2024,July,27,4,2024-07-04,4,10,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,314.0,,0,Transient,105.2,0,0
HB-099956,City Hotel,0,45,2024,October,42,20,2024-10-20,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,2
HB-080447,City Hotel,1,34,2023,December,49,8,2023-12-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,0,Transient,90.0,0,0
HB-073389,City Hotel,1,143,2025,August,34,20,2025-08-20,2,1,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.0,0,0
HB-073556,City Hotel,1,28,2025,August,35,26,2025-08-26,1,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.5,0,2
HB-036087,Resort Hotel,0,96,2025,May,19,7,2025-05-07,2,0,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,242.0,,0,Transient-Party,118.25,1,1
HB-038025,Resort Hotel,0,170,2025,June,27,30,2025-06-30,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,110.0,0,1
HB-033340,Resort Hotel,0,8,2025,February,8,17,2025-02-17,1,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,250.0,,0,Transient,67.0,1,0
HB-064230,City Hotel,1,28,2025,March,9,2,2025-03-02,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,95.0,0,0
HB-090938,City Hotel,0,117,2024,June,23,9,2024-06-09,2,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,3,No Deposit,9.0,,0,Transient-Party,105.26,0,0
HB-106628,City Hotel,0,53,2025,February,9,26,2025-02-26,2,0,1,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.2,0,0
HB-048564,City Hotel,1,161,2024,March,13,25,2024-03-25,1,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,101,Transient,130.0,0,0
HB-058247,City Hotel,1,110,2024,October,41,9,2024-10-09,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,234.0,,0,Transient-Party,80.0,0,0
HB-039572,Resort Hotel,0,274,2025,August,33,16,2025-08-16,2,4,2,1.0,0,HB,PRT,Direct,Direct,0,0,0,C,C,0,No Deposit,250.0,,0,Transient,224.1,1,3
HB-010440,Resort Hotel,1,220,2025,March,10,7,2025-03-07,0,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,37.8,0,1
HB-107959,City Hotel,0,56,2025,March,11,16,2025-03-16,1,3,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,3
HB-016788,Resort Hotel,0,32,2023,September,36,9,2023-09-09,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,120.0,1,0
HB-009477,Resort Hotel,1,128,2024,December,49,3,2024-12-03,0,1,2,0.0,0,HB,PRT,Groups,Direct,0,0,0,A,C,1,No Deposit,,,0,Transient-Party,64.0,0,0
HB-092460,City Hotel,0,14,2024,July,27,3,2024-07-03,2,2,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,151.0,0,1
HB-092658,City Hotel,0,0,2024,July,28,8,2024-07-08,0,2,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,143.5,0,0
HB-057977,City Hotel,1,46,2024,October,40,4,2024-10-04,0,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.5,0,1
HB-029170,Resort Hotel,0,163,2024,October,42,16,2024-10-16,2,5,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient-Party,102.43,0,2
HB-104992,City Hotel,0,75,2025,January,4,22,2025-01-22,2,3,3,0.0,0,BB,PAN,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,9.0,,0,Transient,138.6,0,1
HB-117272,City Hotel,0,164,2025,July,31,30,2025-07-30,2,0,1,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient,84.6,0,1
HB-095459,City Hotel,0,320,2024,August,33,18,2024-08-18,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-057002,City Hotel,1,205,2024,September,38,16,2024-09-16,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,120.0,0,0
HB-089027,City Hotel,0,3,2024,May,19,12,2024-05-12,2,3,2,0.0,0,SC,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,121.0,0,0
HB-052617,City Hotel,1,179,2024,June,23,8,2024-06-08,2,5,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,182.26,0,0
HB-095818,City Hotel,0,27,2024,August,34,22,2024-08-22,1,1,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,137.7,0,0
HB-117699,City Hotel,0,0,2025,August,32,7,2025-08-07,1,0,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,152.0,,0,Transient,87.82,0,0
HB-073594,City Hotel,1,14,2025,August,35,27,2025-08-27,1,0,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.0,0,1
HB-048518,City Hotel,1,41,2024,March,13,25,2024-03-25,0,2,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,159.3,0,0
HB-028171,Resort Hotel,0,126,2024,September,38,16,2024-09-16,2,5,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,E,E,1,No Deposit,177.0,,0,Transient,93.0,0,0
HB-027245,Resort Hotel,0,4,2024,August,34,23,2024-08-23,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,42.0,0,Transient,138.0,1,0
HB-013210,Resort Hotel,1,302,2025,August,32,4,2025-08-04,2,7,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,172.8,0,2
HB-002524,Resort Hotel,0,22,2023,October,42,20,2023-10-20,0,5,3,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,F,0,No Deposit,171.0,,0,Transient,88.67,0,0
HB-050573,City Hotel,1,253,2024,May,18,4,2024-05-04,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,55,Transient,90.0,0,0
HB-028458,Resort Hotel,0,159,2024,September,39,27,2024-09-27,2,5,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,314.0,,0,Transient-Party,89.49,0,0
HB-059984,City Hotel,1,305,2024,November,45,4,2024-11-04,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,89.0,0,0
HB-109174,City Hotel,0,1,2025,April,14,5,2025-04-05,0,3,2,0.0,0,BB,BRA,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,157.5,0,2
HB-061585,City Hotel,1,29,2024,December,51,17,2024-12-17,1,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,104.0,0,0
HB-033681,Resort Hotel,0,2,2025,February,9,27,2025-02-27,1,0,2,1.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Group,42.5,0,0
HB-053655,City Hotel,1,31,2024,June,26,26,2024-06-26,2,4,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,112.14,0,3
HB-051263,City Hotel,1,286,2024,May,20,17,2024-05-17,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,75,Transient,65.0,0,0
HB-103344,City Hotel,0,25,2024,December,51,17,2024-12-17,2,1,1,0.0,0,BB,KAZ,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.0,0,0
HB-036038,Resort Hotel,0,248,2025,May,18,3,2025-05-03,1,4,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,54.0,0,1
HB-028822,Resort Hotel,0,14,2024,October,41,11,2024-10-11,0,1,1,0.0,0,BB,GBR,Direct,Corporate,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,57.6,0,0
HB-010967,Resort Hotel,1,180,2025,April,15,13,2025-04-13,0,3,3,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,160.0,0,1
HB-078864,City Hotel,0,17,2023,October,42,16,2023-10-16,0,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,20.0,,17,Transient-Party,48.0,0,0
HB-090814,City Hotel,0,35,2024,June,23,9,2024-06-09,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,136.2,0,2
HB-091458,City Hotel,0,54,2024,June,25,17,2024-06-17,2,3,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,A,1,No Deposit,9.0,,0,Transient,148.5,0,2
HB-081647,City Hotel,0,38,2023,December,50,13,2023-12-13,2,1,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Contract,87.0,0,2
HB-116986,City Hotel,0,56,2025,July,30,24,2025-07-24,1,3,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,127.0,0,1
HB-021653,Resort Hotel,0,17,2024,March,10,5,2024-03-05,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,29.0,0,1
HB-024173,Resort Hotel,0,468,2024,May,19,12,2024-05-12,0,2,2,0.0,0,HB,FRA,Groups,TA/TO,0,0,0,A,F,0,No Deposit,249.0,,0,Transient-Party,67.0,0,1
HB-061824,City Hotel,1,314,2024,December,52,26,2024-12-26,3,6,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,68.66,0,0
HB-002015,Resort Hotel,0,73,2023,September,39,27,2023-09-27,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,40.0,,0,Contract,93.43,0,0
HB-027985,Resort Hotel,0,7,2024,September,37,13,2024-09-13,0,4,2,0.0,0,BB,CHL,Direct,Direct,0,0,0,G,G,0,No Deposit,250.0,,0,Transient,187.25,1,0
HB-086734,City Hotel,0,124,2024,April,14,5,2024-04-05,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,71.0,0,0
HB-058623,City Hotel,1,237,2024,October,41,13,2024-10-13,0,3,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,128.4,0,0
HB-070087,City Hotel,1,219,2025,June,24,9,2025-06-09,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,105.0,0,0
HB-034789,Resort Hotel,0,1,2025,April,14,4,2025-04-04,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,127.0,,0,Transient-Party,61.6,0,0
HB-042052,City Hotel,1,104,2023,August,35,30,2023-08-30,2,1,2,0.0,0,HB,ESP,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,90.0,0,0
HB-107643,City Hotel,0,65,2025,March,11,12,2025-03-12,2,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,73.0,0,1
HB-026400,Resort Hotel,0,112,2024,July,31,30,2024-07-30,0,0,2,2.0,0,HB,PRT,Online TA,TA/TO,0,0,0,G,I,0,No Deposit,240.0,,0,Transient,0.0,0,0
HB-099683,City Hotel,0,377,2024,October,42,14,2024-10-14,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-025804,Resort Hotel,0,0,2024,July,28,11,2024-07-11,1,0,1,0.0,0,BB,SWE,Direct,Direct,0,0,0,E,E,3,No Deposit,,,0,Transient,161.0,1,0
HB-008316,Resort Hotel,1,385,2024,September,38,21,2024-09-21,0,4,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,66.0,0,0
HB-002214,Resort Hotel,0,207,2023,October,40,5,2023-10-05,3,7,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,156.0,,0,Transient,65.45,0,0
HB-053158,City Hotel,1,44,2024,June,24,16,2024-06-16,0,3,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,251.7,0,0
HB-055402,City Hotel,1,149,2024,August,33,12,2024-08-12,1,2,2,1.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.5,0,0
HB-005558,Resort Hotel,0,199,2024,May,18,2,2024-05-02,1,1,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,85.0,0,0
HB-065807,City Hotel,1,217,2025,April,15,8,2025-04-08,2,3,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient,103.05,0,2
HB-089208,City Hotel,0,23,2024,May,20,18,2024-05-18,0,1,1,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,G,0,No Deposit,7.0,,0,Transient,120.12,0,1
HB-039529,Resort Hotel,0,53,2025,August,33,14,2025-08-14,2,5,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,218.0,0,1
HB-107762,City Hotel,0,2,2025,March,11,16,2025-03-16,0,2,2,0.0,0,BB,FIN,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,88.2,0,1
HB-063590,City Hotel,1,93,2025,February,7,14,2025-02-14,2,6,2,0.0,0,SC,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,2
HB-030212,Resort Hotel,0,85,2024,November,46,14,2024-11-14,1,2,2,0.0,0,BB,DNK,Online TA,TA/TO,0,0,0,E,E,2,No Deposit,242.0,,0,Transient,61.8,1,1
HB-082145,City Hotel,1,99,2024,February,8,19,2024-02-19,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,1,0,A,A,0,No Deposit,,67.0,0,Transient-Party,80.0,0,0
HB-000238,Resort Hotel,1,17,2023,July,27,9,2023-07-09,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,105.08,0,0
HB-105646,City Hotel,0,10,2025,February,6,9,2025-02-09,1,3,2,2.0,1,HB,FRA,Offline TA/TO,TA/TO,0,0,0,G,G,0,No Deposit,427.0,,0,Transient,233.75,0,2
HB-007203,Resort Hotel,1,22,2024,July,30,27,2024-07-27,0,4,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,226.0,0,1
HB-093142,City Hotel,0,84,2024,July,29,15,2024-07-15,0,2,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,121.5,0,2
HB-027414,Resort Hotel,0,29,2024,August,35,26,2024-08-26,1,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,221.0,0,0
HB-112904,City Hotel,0,27,2025,May,22,29,2025-05-29,1,0,3,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Transient,139.0,0,0
HB-080897,City Hotel,0,61,2023,November,47,23,2023-11-23,1,3,1,0.0,0,BB,TUN,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,70.0,0,0
HB-084841,City Hotel,0,6,2024,March,9,2,2024-03-02,0,2,1,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,80.0,0,1
HB-056330,City Hotel,1,420,2024,September,36,3,2024-09-03,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,35.0,,0,Transient,75.0,0,0
HB-023714,Resort Hotel,0,197,2024,April,18,30,2024-04-30,1,1,1,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,1,No Deposit,298.0,,0,Transient-Party,54.5,0,0
HB-024845,Resort Hotel,0,258,2024,May,22,30,2024-05-30,1,5,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,56.29,0,0
HB-071749,City Hotel,1,336,2025,July,28,11,2025-07-11,0,4,2,0.0,0,HB,KAZ,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,147.6,0,2
HB-059943,City Hotel,1,30,2024,November,45,4,2024-11-04,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,80.47,0,1
HB-003676,Resort Hotel,0,165,2023,December,52,30,2023-12-30,0,4,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,308.0,,122,Transient-Party,0.0,0,0
HB-099599,City Hotel,0,34,2024,October,41,13,2024-10-13,0,2,1,0.0,0,BB,ATA,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,175.5,0,0
HB-104980,City Hotel,0,79,2025,January,4,26,2025-01-26,0,1,1,0.0,0,BB,POL,Groups,TA/TO,0,0,0,A,A,1,No Deposit,,365.0,0,Transient-Party,85.0,0,0
HB-096025,City Hotel,0,143,2024,August,34,25,2024-08-25,0,3,2,0.0,0,BB,CZE,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,36.0,,0,Transient-Party,100.0,0,0
HB-041710,City Hotel,1,117,2023,August,34,22,2023-08-22,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,0
HB-110891,City Hotel,0,5,2025,May,18,1,2025-05-01,1,1,3,0.0,0,BB,ECU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,220.0,0,2
HB-039531,Resort Hotel,0,3,2025,August,33,17,2025-08-17,1,3,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,271.0,0,2
HB-100951,City Hotel,0,96,2024,November,44,2,2024-11-02,0,2,2,0.0,0,SC,POL,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,9.0,,0,Transient,79.2,0,3
HB-071126,City Hotel,1,368,2025,June,26,28,2025-06-28,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-019053,Resort Hotel,0,0,2024,February,8,22,2024-02-22,1,3,1,0.0,0,BB,PRT,Direct,Direct,1,0,7,A,D,1,No Deposit,,,0,Transient,43.0,1,1
HB-036326,Resort Hotel,0,118,2025,May,19,10,2025-05-10,2,5,1,0.0,0,BB,IRL,Groups,TA/TO,0,0,0,A,A,0,No Deposit,96.0,,0,Transient-Party,44.0,0,0
HB-000898,Resort Hotel,1,61,2023,August,31,4,2023-08-04,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,153.0,0,0
HB-101887,City Hotel,0,116,2024,November,46,17,2024-11-17,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.0,0,1
HB-046602,City Hotel,0,4,2024,January,2,10,2024-01-10,2,0,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,82.9,0,1
HB-076830,City Hotel,1,176,2023,August,35,28,2023-08-28,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,1
HB-051483,City Hotel,1,211,2024,May,21,20,2024-05-20,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,111,Transient,100.0,0,0
HB-076820,City Hotel,0,0,2024,February,7,16,2024-02-16,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,2,3,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-082301,City Hotel,0,35,2023,December,52,26,2023-12-26,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,97.0,0,1
HB-052569,City Hotel,1,56,2024,June,23,8,2024-06-08,0,1,2,0.0,0,BB,PRT,Offline TA/TO,Corporate,0,0,0,A,A,0,No Deposit,191.0,,0,Transient-Party,120.0,0,0
HB-029594,Resort Hotel,0,160,2024,October,44,29,2024-10-29,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,46.4,0,1
HB-004742,Resort Hotel,1,224,2024,March,13,31,2024-03-31,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,51.3,0,2
HB-096403,City Hotel,0,31,2024,August,35,30,2024-08-30,0,3,2,0.0,1,SC,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,108.0,0,1
HB-016414,Resort Hotel,0,239,2023,August,35,28,2023-08-28,4,10,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,114.71,0,1
HB-047320,City Hotel,1,44,2024,February,7,17,2024-02-17,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,44.0,,3,Transient,75.0,0,0
HB-098278,City Hotel,0,150,2024,September,39,25,2024-09-25,2,0,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,7.0,,0,Transient,91.48,0,1
HB-025447,Resort Hotel,0,1,2025,March,13,28,2025-03-28,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,2,A,D,0,No Deposit,,47.0,0,Transient,35.0,0,0
HB-078918,City Hotel,0,35,2023,October,42,17,2023-10-17,1,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,104.85,0,1
HB-033055,Resort Hotel,0,16,2025,February,6,9,2025-02-09,1,3,2,1.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,436.0,,0,Transient,42.5,0,0
HB-074751,City Hotel,1,159,2023,July,30,25,2023-07-25,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,1
HB-053952,City Hotel,1,73,2024,July,27,2,2024-07-02,4,10,3,0.0,0,BB,AGO,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,145.93,0,0
HB-046093,City Hotel,1,106,2023,December,49,9,2023-12-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,57,Transient,75.0,0,0
HB-101223,City Hotel,0,3,2024,November,45,7,2024-11-07,1,1,1,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,D,0,No Deposit,37.0,,0,Transient,140.0,0,1
HB-105018,City Hotel,0,68,2025,January,4,26,2025-01-26,0,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,111.6,1,0
HB-060618,City Hotel,1,496,2024,November,46,17,2024-11-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-039947,Resort Hotel,0,59,2025,August,35,27,2025-08-27,2,4,2,0.0,0,BB,BGR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,168.0,0,0
HB-013149,Resort Hotel,1,231,2025,August,31,2,2025-08-02,2,4,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,183.33,0,2
HB-054627,City Hotel,1,14,2024,July,29,21,2024-07-21,0,2,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,174.0,0,Transient-Party,105.0,0,0
HB-054129,City Hotel,1,365,2024,July,27,7,2024-07-07,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-006644,Resort Hotel,0,322,2024,June,25,22,2024-06-22,0,3,2,0.0,0,HB,POL,Groups,Direct,0,0,0,A,C,1,No Deposit,,,75,Transient-Party,92.0,0,0
HB-047709,City Hotel,1,21,2024,February,9,29,2024-02-29,1,3,1,0.0,0,BB,TUR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,102.05,0,0
HB-038942,Resort Hotel,0,124,2025,July,31,30,2025-07-30,2,2,2,0.0,0,BB,MAR,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,245.0,1,3
HB-011102,Resort Hotel,1,100,2025,April,16,18,2025-04-18,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,94.29,0,0
HB-102308,City Hotel,0,55,2024,November,48,25,2024-11-25,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,G,0,No Deposit,9.0,,0,Transient,93.6,0,1
HB-040264,City Hotel,0,12,2023,July,29,18,2023-07-18,2,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,60.0,0,0
HB-045291,City Hotel,0,69,2023,October,43,25,2023-10-25,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,58,Transient-Party,85.67,0,0
HB-067653,City Hotel,1,232,2025,May,19,5,2025-05-05,2,2,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,166.0,0,0
HB-049989,City Hotel,1,70,2024,April,17,22,2024-04-22,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,B,1,No Deposit,9.0,,0,Transient,105.3,0,1
HB-073183,City Hotel,1,84,2025,August,33,16,2025-08-16,0,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.0,0,1
HB-056190,City Hotel,0,256,2024,August,35,31,2024-08-31,0,4,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,90.95,0,0
HB-072996,City Hotel,1,170,2025,August,33,11,2025-08-11,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,175.5,0,0
HB-063293,City Hotel,1,148,2025,February,6,5,2025-02-05,2,5,0,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient,91.6,0,2
HB-096773,City Hotel,0,31,2024,September,36,5,2024-09-05,1,2,4,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,7.0,,0,Transient,197.65,0,1
HB-027933,Resort Hotel,0,5,2024,September,37,14,2024-09-14,0,1,1,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,E,0,No Deposit,223.0,,0,Transient-Party,60.0,0,0
HB-034198,Resort Hotel,0,14,2025,March,11,16,2025-03-16,0,1,3,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,115.0,0,1
HB-097246,City Hotel,0,45,2024,September,37,12,2024-09-12,1,1,1,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,81.0,0,0
HB-005798,Resort Hotel,0,211,2024,May,20,14,2024-05-14,1,1,1,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,1,No Deposit,298.0,,0,Transient-Party,54.5,0,0
HB-058033,City Hotel,1,48,2024,October,40,5,2024-10-05,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,120.0,0,0
HB-040933,City Hotel,0,142,2023,August,32,9,2023-08-09,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient,76.5,0,1
HB-083150,City Hotel,0,0,2024,January,3,21,2024-01-21,0,1,2,0.0,0,BB,NLD,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,91.0,1,1
HB-066110,City Hotel,1,252,2025,April,16,14,2025-04-14,1,2,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,2
HB-088463,City Hotel,0,104,2024,May,18,4,2024-05-04,0,3,1,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,110.1,0,1
HB-119028,City Hotel,0,1,2025,August,35,27,2025-08-27,1,0,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,111.2,0,1
HB-007428,Resort Hotel,1,119,2024,August,32,8,2024-08-08,3,6,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,206.78,0,0
HB-087869,City Hotel,0,69,2024,April,17,23,2024-04-23,2,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,9.0,,0,Transient-Party,107.95,0,0
HB-058555,City Hotel,1,37,2024,October,41,13,2024-10-13,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,95.0,0,0
HB-056794,City Hotel,1,41,2024,September,37,14,2024-09-14,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,86.0,,0,Transient-Party,130.0,0,0
HB-101348,City Hotel,0,119,2024,November,45,10,2024-11-10,0,1,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,161.1,0,1
HB-050190,City Hotel,1,99,2024,April,17,25,2024-04-25,1,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.95,0,0
HB-042001,City Hotel,1,145,2023,August,35,29,2023-08-29,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-078980,City Hotel,1,230,2024,June,23,5,2024-06-05,2,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,B,B,0,No Deposit,8.0,,0,Transient,89.0,0,1
HB-062232,City Hotel,1,65,2025,January,1,5,2025-01-05,0,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.6,0,0
HB-072889,City Hotel,1,246,2025,August,32,9,2025-08-09,0,2,1,0.0,0,BB,JPN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,123.3,0,0
HB-040101,City Hotel,1,86,2023,July,27,6,2023-07-06,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,0
HB-011061,Resort Hotel,1,131,2025,April,16,16,2025-04-16,2,5,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,493.0,,0,Transient-Party,80.0,0,0
HB-038342,Resort Hotel,0,31,2025,July,28,13,2025-07-13,0,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,128.0,1,1
HB-056850,City Hotel,1,317,2024,September,37,15,2024-09-15,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,120.0,0,0
HB-032873,Resort Hotel,0,0,2025,February,6,7,2025-02-07,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,60.0,1,0
HB-095451,City Hotel,0,203,2024,August,33,17,2024-08-17,0,3,2,1.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,87.99,0,0
HB-113833,City Hotel,0,120,2025,June,24,9,2025-06-09,2,2,3,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,214.2,0,0
HB-039278,Resort Hotel,0,84,2025,August,32,8,2025-08-08,0,5,2,2.0,0,Undefined,ESP,Direct,Direct,0,0,0,C,C,0,No Deposit,,,0,Transient,335.0,0,1
HB-108455,City Hotel,0,76,2025,March,12,23,2025-03-23,2,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,68.0,0,1
HB-026218,Resort Hotel,0,126,2024,July,30,23,2024-07-23,1,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,240.0,,0,Transient,184.0,1,1
HB-108374,City Hotel,0,99,2025,March,12,23,2025-03-23,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,106.2,0,1
HB-069924,City Hotel,1,169,2025,June,23,8,2025-06-08,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,170.0,0,0
HB-055639,City Hotel,1,405,2024,August,33,18,2024-08-18,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-048915,City Hotel,1,66,2024,April,14,2,2024-04-02,1,1,1,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.2,0,0
HB-014920,Resort Hotel,0,321,2024,November,48,30,2024-11-30,0,4,1,0.0,0,BB,PRT,Online TA,Direct,1,1,9,A,A,0,No Deposit,,,0,Transient,39.0,0,4
HB-021102,Resort Hotel,0,6,2024,February,7,15,2024-02-15,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,50.0,1,0
HB-026035,Resort Hotel,0,85,2024,July,28,12,2024-07-12,2,5,2,0.0,0,BB,LTU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,162.0,0,1
HB-043101,City Hotel,0,29,2023,September,37,15,2023-09-15,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,5,No Deposit,9.0,,0,Contract,105.0,0,1
HB-018056,Resort Hotel,0,153,2023,October,43,29,2023-10-29,0,3,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,42.0,1,0
HB-114566,City Hotel,0,0,2025,June,25,22,2025-06-22,0,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,220.0,0,0
HB-039413,Resort Hotel,0,256,2025,August,32,8,2025-08-08,2,7,2,1.0,0,HB,BEL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,479.0,,0,Transient,172.81,0,4
HB-114925,City Hotel,0,24,2025,June,26,26,2025-06-26,1,2,2,0.0,0,BB,FRA,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,280.0,0,Transient-Party,100.0,0,0
HB-052624,City Hotel,1,27,2024,June,23,9,2024-06-09,0,1,2,0.0,0,BB,PRT,Offline TA/TO,Corporate,0,0,0,A,A,0,No Deposit,191.0,,0,Transient-Party,120.0,0,0
HB-096123,City Hotel,0,143,2024,August,34,25,2024-08-25,1,3,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,22.0,,0,Transient,112.45,0,0
HB-023233,Resort Hotel,0,0,2024,April,16,18,2024-04-18,1,0,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,339.0,,0,Transient,52.0,0,0
HB-018849,Resort Hotel,0,0,2023,November,48,30,2023-11-30,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,48.0,0,2
HB-032066,Resort Hotel,0,10,2025,January,3,14,2025-01-14,0,1,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,E,E,1,No Deposit,250.0,,0,Transient,114.0,0,1
HB-015834,Resort Hotel,0,67,2023,August,31,2,2023-08-02,2,0,2,0.0,1,BB,ESP,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,241.0,,0,Transient,137.9,1,2
HB-002512,Resort Hotel,0,86,2023,October,42,19,2023-10-19,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,40.0,,0,Contract,79.63,0,0
HB-049495,City Hotel,1,126,2024,April,15,14,2024-04-14,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,39,Transient,57.5,0,0
HB-074030,City Hotel,1,300,2023,August,32,13,2023-08-13,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-036062,Resort Hotel,0,79,2025,May,19,6,2025-05-06,1,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,85.0,0,2
HB-065401,City Hotel,1,129,2025,April,14,3,2025-04-03,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,0,Transient,100.0,0,0
HB-004110,Resort Hotel,1,0,2024,February,7,13,2024-02-13,0,1,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,G,G,0,No Deposit,,,0,Transient,107.0,0,0
HB-039337,Resort Hotel,0,49,2025,August,33,13,2025-08-13,2,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,198.0,0,1
HB-058629,City Hotel,1,54,2024,October,41,13,2024-10-13,0,3,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,139.5,0,3
HB-112254,City Hotel,0,92,2025,May,20,18,2025-05-18,1,3,2,1.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,155.25,0,2
HB-107518,City Hotel,0,28,2025,March,11,12,2025-03-12,2,0,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-082869,City Hotel,1,68,2024,February,7,17,2024-02-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,37.0,,0,Transient,75.0,0,0
HB-118179,City Hotel,0,182,2025,August,33,14,2025-08-14,1,1,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,175.5,0,0
HB-069295,City Hotel,1,105,2025,May,22,29,2025-05-29,1,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,124.67,0,0
HB-055455,City Hotel,1,143,2024,August,33,13,2024-08-13,1,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.3,0,0
HB-009869,Resort Hotel,1,242,2025,January,3,14,2025-01-14,4,10,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,37.8,0,0
HB-098403,City Hotel,0,80,2024,September,39,25,2024-09-25,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.9,0,0
HB-106697,City Hotel,0,348,2025,February,9,24,2025-02-24,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,9.0,,0,Transient,90.1,0,2
HB-041850,City Hotel,1,50,2023,August,34,25,2023-08-25,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-076337,City Hotel,0,271,2023,July,28,15,2023-07-15,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-015277,Resort Hotel,0,7,2024,April,17,26,2024-04-26,0,2,1,0.0,0,BB,PRT,Direct,Direct,1,0,4,A,A,0,No Deposit,,338.0,0,Transient,56.4,1,0
HB-053922,City Hotel,1,139,2024,July,27,2,2024-07-02,0,1,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.5,0,0
HB-004646,Resort Hotel,1,106,2024,March,12,24,2024-03-24,1,3,2,0.0,0,FB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,68.0,,0,Transient,84.0,0,0
HB-082173,City Hotel,1,99,2024,February,8,19,2024-02-19,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,1,0,A,A,0,No Deposit,,67.0,0,Transient-Party,80.0,0,0
HB-095072,City Hotel,0,128,2024,August,32,9,2024-08-09,0,5,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,103.5,0,1
HB-028316,Resort Hotel,0,13,2024,September,39,28,2024-09-28,0,1,1,0.0,0,BB,PRT,Direct,Corporate,0,0,0,A,A,0,No Deposit,72.0,,0,Transient,65.0,0,0
HB-027268,Resort Hotel,0,98,2024,August,33,14,2024-08-14,4,7,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,211.91,0,1
HB-055403,City Hotel,1,93,2024,August,33,12,2024-08-12,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.9,0,2
HB-019183,Resort Hotel,1,237,2024,August,31,1,2024-08-01,1,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,240.0,,0,Transient,126.0,0,0
HB-118729,City Hotel,0,2,2025,August,34,24,2025-08-24,0,1,2,0.0,0,BB,MEX,Groups,TA/TO,0,0,0,A,A,0,No Deposit,147.0,,0,Transient-Party,140.0,0,1
HB-071079,City Hotel,1,0,2025,June,26,28,2025-06-28,0,1,1,0.0,0,BB,PRT,Aviation,Corporate,0,0,0,A,A,0,No Deposit,,153.0,0,Transient,95.0,0,0
HB-112132,City Hotel,0,69,2025,May,20,16,2025-05-16,0,4,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,144.0,0,1
HB-004687,Resort Hotel,1,45,2024,March,13,28,2024-03-28,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,96.0,0,0
HB-037401,Resort Hotel,0,61,2025,June,24,13,2025-06-13,0,4,2,0.0,0,HB,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,145.6,0,1
HB-031152,Resort Hotel,0,8,2024,December,50,15,2024-12-15,0,1,1,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient-Party,43.0,1,1
HB-057280,City Hotel,1,82,2024,September,38,22,2024-09-22,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,95.0,0,0
HB-043088,City Hotel,0,25,2023,September,37,14,2023-09-14,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,78.54,0,1
HB-118367,City Hotel,0,77,2025,August,33,15,2025-08-15,0,4,2,0.0,0,BB,ETH,Direct,Direct,0,0,0,D,A,0,No Deposit,14.0,,0,Transient,111.8,0,0
HB-013164,Resort Hotel,1,28,2025,August,31,3,2025-08-03,0,2,2,0.0,0,BB,PHL,Online TA,TA/TO,0,0,0,A,A,3,No Deposit,240.0,,0,Transient,205.0,0,1
HB-080801,City Hotel,1,183,2024,April,17,22,2024-04-22,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Contract,115.2,0,1
HB-116849,City Hotel,0,282,2025,July,29,17,2025-07-17,3,6,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,7.0,,0,Transient,131.01,0,1
HB-063017,City Hotel,1,566,2025,January,4,26,2025-01-26,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-084714,City Hotel,0,8,2024,March,9,2,2024-03-02,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,86.0,0,0
HB-039057,Resort Hotel,0,0,2025,August,32,6,2025-08-06,1,0,2,0.0,0,BB,GBR,Direct,TA/TO,1,0,0,A,A,0,No Deposit,,,0,Transient,185.0,0,0
HB-019127,Resort Hotel,0,0,2023,December,49,5,2023-12-05,2,1,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,242.0,,0,Transient,99.1,1,0
HB-010514,Resort Hotel,1,339,2025,March,11,11,2025-03-11,2,5,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,D,D,0,No Deposit,298.0,,0,Transient-Party,51.0,0,0
HB-089598,City Hotel,0,46,2024,May,21,22,2024-05-22,1,0,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,116.1,0,0
HB-005640,Resort Hotel,1,95,2024,May,19,7,2024-05-07,2,1,2,0.0,1,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,58.0,0,3
HB-025169,Resort Hotel,0,0,2024,June,25,17,2024-06-17,0,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,1,0,0,A,I,0,No Deposit,177.0,,0,Group,0.0,0,0
HB-087347,City Hotel,0,93,2024,April,15,14,2024-04-14,1,3,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,80.75,0,1
HB-113190,City Hotel,0,107,2025,June,22,1,2025-06-01,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Contract,80.0,0,0
HB-112672,City Hotel,0,23,2025,May,22,26,2025-05-26,0,1,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,117.0,0,1
HB-092031,City Hotel,0,92,2024,June,26,26,2024-06-26,2,1,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,118.0,,0,Transient,80.75,0,1
HB-034211,Resort Hotel,0,2,2025,March,11,16,2025-03-16,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,146.0,,0,Transient,32.0,0,0
HB-080566,City Hotel,0,49,2023,November,46,16,2023-11-16,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Group,60.0,0,0
HB-007643,Resort Hotel,1,27,2024,August,33,18,2024-08-18,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,200.1,0,0
HB-056411,City Hotel,1,192,2024,September,36,5,2024-09-05,1,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,E,E,0,Non Refund,,51.0,0,Transient-Party,106.0,0,0
HB-081242,City Hotel,0,47,2023,December,49,5,2023-12-05,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-079119,City Hotel,0,11,2023,October,42,18,2023-10-18,2,2,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,85.0,0,0
HB-009361,Resort Hotel,1,21,2024,November,47,18,2024-11-18,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,63.0,0,1
HB-094911,City Hotel,0,152,2024,August,32,10,2024-08-10,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,114.3,0,1
HB-085682,City Hotel,0,35,2024,March,12,18,2024-03-18,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,9.0,,0,Transient,162.45,0,0
HB-091781,City Hotel,0,192,2024,June,26,24,2024-06-24,0,2,1,0.0,0,BB,SRB,Offline TA/TO,TA/TO,0,0,0,A,E,0,No Deposit,34.0,,0,Transient-Party,95.0,0,0
HB-006463,Resort Hotel,1,277,2024,June,24,12,2024-06-12,2,2,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-116127,City Hotel,0,277,2025,July,28,13,2025-07-13,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,89.1,0,2
HB-005091,Resort Hotel,1,34,2024,April,16,16,2024-04-16,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,65.45,0,0
HB-028125,Resort Hotel,0,6,2024,September,38,20,2024-09-20,0,1,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,106.0,0,1
HB-028108,Resort Hotel,0,1,2024,September,38,20,2024-09-20,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,282.0,,0,Transient-Party,65.0,0,0
HB-056196,City Hotel,1,419,2024,September,35,1,2024-09-01,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,59.0,0,0
HB-032629,Resort Hotel,0,0,2025,January,5,30,2025-01-30,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,510.0,,0,Transient,40.0,0,0
HB-098013,City Hotel,0,133,2024,September,38,19,2024-09-19,1,4,2,1.0,0,BB,JPN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,156.15,0,3
HB-033983,Resort Hotel,0,1,2025,March,10,9,2025-03-09,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,168.0,,0,Transient,48.0,1,1
HB-086719,City Hotel,0,70,2024,April,14,4,2024-04-04,1,3,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,121.55,0,2
HB-115736,City Hotel,0,180,2025,July,28,7,2025-07-07,1,2,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,89.1,0,0
HB-084134,City Hotel,0,8,2024,February,8,19,2024-02-19,0,1,1,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,D,0,No Deposit,,67.0,0,Transient-Party,80.0,0,0
HB-067694,City Hotel,1,162,2025,May,19,6,2025-05-06,2,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,80.0,0,0
HB-098343,City Hotel,0,0,2024,September,39,27,2024-09-27,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,1,No Deposit,174.0,,0,Transient-Party,160.0,0,0
HB-032735,Resort Hotel,0,31,2025,February,6,3,2025-02-03,0,1,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient-Party,55.0,1,1
HB-082680,City Hotel,0,44,2024,January,1,2,2024-01-02,2,1,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,1.0,0,0
HB-118725,City Hotel,0,2,2025,August,34,24,2025-08-24,0,1,2,0.0,0,BB,MEX,Groups,TA/TO,0,0,0,A,A,0,No Deposit,147.0,,0,Transient-Party,140.0,0,1
HB-029788,Resort Hotel,0,37,2024,November,44,2,2024-11-02,0,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient,54.0,0,2
HB-108954,City Hotel,0,48,2025,April,14,1,2025-04-01,2,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,162.0,0,3
HB-114046,City Hotel,0,76,2025,June,24,11,2025-06-11,2,3,1,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,148.5,0,2
HB-115214,City Hotel,0,2,2025,July,27,2,2025-07-02,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.0,0,1
HB-028706,Resort Hotel,0,167,2024,October,40,3,2024-10-03,2,5,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,101.43,0,1
HB-109492,City Hotel,0,202,2025,April,15,9,2025-04-09,2,1,3,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,158.4,1,2
HB-070963,City Hotel,1,213,2025,June,26,26,2025-06-26,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,323.0,,0,Transient,115.0,0,0
HB-088974,City Hotel,0,56,2024,May,20,13,2024-05-13,0,2,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,140.4,0,1
HB-096982,City Hotel,0,65,2024,September,37,9,2024-09-09,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,149.4,0,1
HB-075892,City Hotel,1,274,2023,July,29,18,2023-07-18,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-116368,City Hotel,0,27,2025,July,29,14,2025-07-14,2,3,2,1.0,0,BB,BEL,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,211.0,0,4
HB-088964,City Hotel,0,22,2024,May,19,10,2024-05-10,0,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,142.2,0,0
HB-057595,City Hotel,1,100,2024,September,39,28,2024-09-28,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,26.0,,0,Transient-Party,100.0,0,0
HB-090696,City Hotel,0,18,2024,June,23,9,2024-06-09,0,1,2,0.0,0,BB,USA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,92.65,0,0
HB-021194,Resort Hotel,0,2,2024,February,8,20,2024-02-20,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,66.0,1,1
HB-031192,Resort Hotel,0,3,2024,December,51,17,2024-12-17,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,39.0,0,1
HB-046227,City Hotel,0,10,2023,December,52,26,2023-12-26,2,2,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,65.05,1,0
HB-103771,City Hotel,0,223,2024,December,1,30,2024-12-30,0,2,1,0.0,0,BB,JPN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.9,0,0
HB-040940,City Hotel,0,0,2023,August,32,10,2023-08-10,1,0,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,115.0,0,0
HB-009593,Resort Hotel,1,11,2024,December,51,17,2024-12-17,2,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,43.0,0,1
HB-024283,Resort Hotel,0,186,2024,May,19,9,2024-05-09,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,52.2,0,1
HB-088425,City Hotel,0,88,2024,May,18,3,2024-05-03,0,3,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,117.0,0,1
HB-012429,Resort Hotel,1,201,2025,June,26,29,2025-06-29,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient,110.0,0,1
HB-051851,City Hotel,0,316,2024,May,21,26,2024-05-26,0,3,1,0.0,0,BB,AUT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,30.0,,0,Transient-Party,100.0,0,0
HB-083726,City Hotel,0,39,2024,February,6,8,2024-02-08,1,1,3,0.0,0,BB,CHN,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,83.0,,0,Transient,98.94,0,2
HB-098783,City Hotel,0,12,2024,October,40,2,2024-10-02,2,1,1,0.0,0,BB,USA,Offline TA/TO,GDS,0,0,0,A,A,0,No Deposit,195.0,,0,Transient,6.0,0,0
HB-059271,City Hotel,1,69,2024,October,43,25,2024-10-25,0,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.1,0,1
HB-015549,Resort Hotel,0,44,2023,July,29,18,2023-07-18,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient,115.0,0,0
HB-079112,City Hotel,0,3,2023,October,42,19,2023-10-19,1,2,1,0.0,0,SC,DNK,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,133.0,0,1
HB-001437,Resort Hotel,1,32,2023,August,35,29,2023-08-29,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,135.2,0,2
HB-020456,Resort Hotel,0,1,2024,January,4,28,2024-01-28,0,1,1,0.0,0,BB,NLD,Direct,Direct,0,0,0,A,D,0,No Deposit,250.0,,0,Transient,45.0,1,0
HB-005207,Resort Hotel,0,191,2024,April,17,22,2024-04-22,1,2,2,0.0,0,Undefined,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,85.33,0,0
HB-049988,City Hotel,1,70,2024,April,17,22,2024-04-22,0,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,127.8,0,1
HB-062124,City Hotel,1,21,2025,January,1,2,2025-01-02,1,3,2,0.0,0,BB,KOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.1,0,2
HB-026539,Resort Hotel,0,1,2024,August,31,2,2024-08-02,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,2,No Deposit,250.0,,0,Transient,241.0,0,0
HB-079745,City Hotel,0,18,2023,October,44,31,2023-10-31,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,7.0,,0,Transient,78.54,0,1
HB-114353,City Hotel,0,126,2025,June,25,17,2025-06-17,2,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,1
HB-065704,City Hotel,1,69,2025,April,14,6,2025-04-06,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,Non Refund,,197.0,0,Transient,85.0,0,0
HB-046225,City Hotel,1,14,2023,December,52,26,2023-12-26,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.5,0,0
HB-093395,City Hotel,0,1,2024,July,29,20,2024-07-20,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,118.0,1,0
HB-051858,City Hotel,0,316,2024,May,21,26,2024-05-26,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,110.0,0,0
HB-072771,City Hotel,1,173,2025,August,32,5,2025-08-05,2,5,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,148.5,0,0
HB-001999,Resort Hotel,1,61,2023,September,39,26,2023-09-26,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,79.0,0,2
HB-080466,City Hotel,1,34,2023,December,49,8,2023-12-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,0,Transient,90.0,0,0
HB-008327,Resort Hotel,0,343,2024,September,38,21,2024-09-21,0,4,2,0.0,0,HB,BEL,Corporate,Corporate,0,0,0,A,C,0,No Deposit,183.0,,0,Transient-Party,92.0,0,0
HB-074914,City Hotel,1,136,2023,July,29,17,2023-07-17,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient,60.0,0,0
HB-002180,Resort Hotel,0,75,2023,October,40,4,2023-10-04,4,6,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,60.4,0,1
HB-036808,Resort Hotel,0,38,2025,May,21,25,2025-05-25,1,3,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,G,G,1,No Deposit,242.0,,0,Transient,170.0,0,0
HB-019841,Resort Hotel,0,0,2024,January,1,3,2024-01-03,2,0,2,0.0,0,BB,COL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Group,50.8,1,0
HB-098004,City Hotel,0,3,2024,September,38,20,2024-09-20,0,3,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient,155.68,0,4
HB-009617,Resort Hotel,1,172,2024,December,51,20,2024-12-20,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,55.8,0,1
HB-094590,City Hotel,0,167,2024,August,32,5,2024-08-05,0,2,2,1.0,0,BB,ISR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,121.5,0,3
HB-032002,Resort Hotel,0,2,2025,January,2,12,2025-01-12,0,2,1,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,43.0,0,1
HB-073762,City Hotel,1,272,2023,July,28,16,2023-07-16,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-070048,City Hotel,1,178,2025,June,24,9,2025-06-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,86.0,,0,Transient,130.0,0,0
HB-021713,Resort Hotel,0,26,2025,March,11,14,2025-03-14,0,5,2,0.0,0,HB,ITA,Direct,Direct,1,0,2,E,E,0,No Deposit,,,0,Transient-Party,80.0,0,1
HB-027984,Resort Hotel,0,244,2024,September,37,12,2024-09-12,1,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,89.1,0,1
HB-056063,City Hotel,1,52,2024,August,35,28,2024-08-28,1,0,1,0.0,0,SC,POL,Online TA,TA/TO,0,0,0,A,A,3,No Deposit,9.0,,0,Transient,118.0,0,1
HB-087674,City Hotel,0,68,2024,April,16,21,2024-04-21,0,3,1,0.0,0,BB,TUR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,112.2,0,1
HB-031998,Resort Hotel,0,66,2025,January,2,10,2025-01-10,0,4,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient,37.0,0,1
HB-048923,City Hotel,0,102,2024,April,14,2,2024-04-02,2,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,63.86,0,1
HB-090889,City Hotel,0,122,2024,June,23,9,2024-06-09,1,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-059754,City Hotel,1,166,2024,November,44,1,2024-11-01,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,110.0,0,0
HB-045863,City Hotel,0,98,2023,November,47,23,2023-11-23,1,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,D,1,No Deposit,37.0,,0,Transient-Party,70.0,0,0
HB-011930,Resort Hotel,1,320,2025,June,23,3,2025-06-03,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,74.25,0,1
HB-049846,City Hotel,0,265,2024,April,16,20,2024-04-20,0,4,2,0.0,0,BB,AUT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,176,Transient-Party,99.0,0,0
HB-029053,Resort Hotel,0,159,2024,October,42,16,2024-10-16,2,2,1,0.0,0,HB,SWE,Groups,Corporate,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,60.0,0,0
HB-088825,City Hotel,0,6,2024,May,19,12,2024-05-12,0,1,1,0.0,0,BB,FRA,Corporate,Direct,0,0,0,A,A,0,No Deposit,,246.0,0,Transient-Party,129.0,0,0
HB-101149,City Hotel,0,44,2024,November,45,4,2024-11-04,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,110.13,0,2
HB-078623,City Hotel,0,221,2023,October,41,10,2023-10-10,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,65.0,0,0
HB-097165,City Hotel,0,19,2024,September,37,12,2024-09-12,1,0,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.0,0,0
HB-091452,City Hotel,0,32,2024,June,25,20,2024-06-20,1,1,2,0.0,0,BB,ARG,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,103.35,0,1
HB-085310,City Hotel,0,21,2024,March,11,12,2024-03-12,0,1,1,2.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,127.0,0,0
HB-070583,City Hotel,1,99,2025,June,25,19,2025-06-19,1,2,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,130.67,0,0
HB-071776,City Hotel,1,451,2025,July,28,12,2025-07-12,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,90.0,0,0
HB-115007,City Hotel,0,0,2025,June,26,28,2025-06-28,0,2,1,1.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,124.0,0,0
HB-107046,City Hotel,0,4,2025,March,10,6,2025-03-06,1,0,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.0,0,1
HB-033656,Resort Hotel,0,21,2025,February,9,25,2025-02-25,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient-Party,61.33,0,2
HB-073020,City Hotel,1,115,2025,August,33,12,2025-08-12,2,2,2,0.0,0,SC,LUX,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.0,0,1
HB-111846,City Hotel,0,6,2025,May,20,14,2025-05-14,2,1,1,0.0,0,BB,SWE,Groups,Corporate,0,0,0,A,A,0,No Deposit,,169.0,0,Transient-Party,110.0,0,0
HB-028025,Resort Hotel,0,327,2024,September,37,14,2024-09-14,0,4,2,0.0,0,BB,IRL,Groups,TA/TO,0,0,0,A,D,1,No Deposit,201.0,,0,Transient-Party,61.4,0,0
HB-079228,City Hotel,1,444,2024,December,48,1,2024-12-01,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,34.0,,39,Transient,75.0,0,0
HB-003755,Resort Hotel,1,113,2024,January,1,2,2024-01-02,0,1,2,0.0,0,HB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,305.0,,0,Transient,72.0,0,0
HB-038103,Resort Hotel,0,205,2025,July,27,6,2025-07-06,0,3,3,0.0,0,HB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,129.72,0,2
HB-017105,Resort Hotel,0,99,2023,September,38,18,2023-09-18,2,5,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,121.0,0,0
HB-034274,Resort Hotel,0,88,2025,March,11,11,2025-03-11,2,5,1,0.0,0,BB,DEU,Groups,TA/TO,0,0,0,A,A,1,No Deposit,177.0,,0,Transient-Party,30.0,0,0
HB-061308,City Hotel,1,65,2024,December,49,7,2024-12-07,0,4,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,119.0,0,1
HB-084182,City Hotel,0,12,2024,February,7,16,2024-02-16,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-064027,City Hotel,1,14,2025,February,9,26,2025-02-26,2,2,2,1.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.8,0,0
HB-053057,City Hotel,1,188,2024,June,24,15,2024-06-15,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,39,Transient,130.0,0,0
HB-086075,City Hotel,0,32,2024,March,13,26,2024-03-26,0,1,3,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,168.3,0,2
HB-069844,City Hotel,1,39,2025,June,23,7,2025-06-07,0,3,2,0.0,0,SC,IND,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.67,0,0
HB-023972,Resort Hotel,0,103,2024,May,18,2,2024-05-02,2,5,2,0.0,0,BB,POL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,315.0,,0,Transient,46.75,0,0
HB-074463,City Hotel,1,311,2023,August,34,24,2023-08-24,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-088339,City Hotel,0,23,2024,May,18,2,2024-05-02,1,2,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,143.99,0,1
HB-088753,City Hotel,0,89,2024,May,19,9,2024-05-09,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-018822,Resort Hotel,1,8,2023,December,49,5,2023-12-05,2,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,38.0,,0,Transient-Party,68.0,0,0
HB-068657,City Hotel,1,175,2025,May,21,19,2025-05-19,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,0,Transient,110.0,0,0
HB-027362,Resort Hotel,0,98,2024,August,34,21,2024-08-21,2,4,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,5.0,,0,Transient,197.2,1,0
HB-082215,City Hotel,1,317,2024,September,37,9,2024-09-09,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,58.0,,56,Transient,90.0,0,0
HB-110904,City Hotel,0,206,2025,May,18,1,2025-05-01,1,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,0
HB-011326,Resort Hotel,1,83,2025,May,18,3,2025-05-03,0,4,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,147.0,0,0
HB-112481,City Hotel,0,0,2025,May,21,23,2025-05-23,0,2,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,234.5,0,2
HB-078508,City Hotel,0,1,2023,October,41,10,2023-10-10,1,1,2,0.0,0,BB,AUT,Direct,Direct,0,0,0,A,G,0,No Deposit,,,0,Transient,128.0,0,0
HB-034092,Resort Hotel,0,1,2025,March,11,11,2025-03-11,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,90.0,0,1
HB-109849,City Hotel,0,176,2025,April,16,14,2025-04-14,2,2,2,0.0,0,HB,RUS,Groups,TA/TO,0,0,0,A,A,0,No Deposit,2.0,,0,Transient-Party,113.0,0,1
HB-021513,Resort Hotel,0,83,2024,February,9,28,2024-02-28,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,62.53,0,1
HB-022028,Resort Hotel,0,3,2024,March,11,13,2024-03-13,2,1,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,F,0,No Deposit,8.0,,0,Transient,57.0,0,0
HB-026607,Resort Hotel,0,180,2024,August,31,1,2024-08-01,1,4,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,241.0,,0,Transient,138.6,0,2
HB-085695,City Hotel,0,43,2024,March,11,17,2024-03-17,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,106.8,0,0
HB-035200,Resort Hotel,0,153,2025,April,15,12,2025-04-12,0,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,90.0,0,2
HB-105377,City Hotel,0,15,2025,February,6,3,2025-02-03,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,86.4,0,0
HB-084939,City Hotel,0,38,2024,March,9,3,2024-03-03,0,3,1,0.0,0,BB,POL,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,67.75,0,0
HB-063377,City Hotel,1,24,2025,February,7,10,2025-02-10,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,94.4,0,0
HB-015760,Resort Hotel,1,244,2023,September,35,2,2023-09-02,2,5,2,0.0,0,BB,IRL,Groups,TA/TO,0,1,0,A,A,0,No Deposit,96.0,,0,Transient-Party,8.0,0,0
HB-048584,City Hotel,1,161,2024,March,13,25,2024-03-25,1,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,101,Transient,130.0,0,0
HB-016087,Resort Hotel,0,1,2023,August,32,12,2023-08-12,0,2,2,0.0,0,BB,AUT,Corporate,Corporate,0,0,0,F,F,0,No Deposit,,110.0,0,Transient,132.0,0,2
HB-089261,City Hotel,0,64,2024,May,20,17,2024-05-17,0,2,1,0.0,0,BB,GBR,Corporate,TA/TO,0,0,0,A,A,0,No Deposit,,218.0,0,Transient-Party,130.0,0,0
HB-055376,City Hotel,1,181,2024,August,32,11,2024-08-11,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,99.45,0,1
HB-050198,City Hotel,1,26,2024,April,17,25,2024-04-25,1,4,2,2.0,0,BB,TUN,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,197.78,0,0
HB-044471,City Hotel,1,97,2023,October,40,5,2023-10-05,1,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,140.0,0,0
HB-081501,City Hotel,0,36,2023,December,49,10,2023-12-10,0,2,3,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,11.0,,0,Transient,55.09,0,1
HB-035720,Resort Hotel,0,2,2025,April,18,29,2025-04-29,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,115.0,0,1
HB-057172,City Hotel,1,55,2024,September,38,20,2024-09-20,0,3,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,168.3,0,0
HB-106131,City Hotel,0,72,2025,February,8,17,2025-02-17,2,2,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.1,0,2
HB-110944,City Hotel,0,93,2025,May,18,1,2025-05-01,1,2,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,52.0,,0,Transient,89.1,0,0
HB-026151,Resort Hotel,1,1,2025,July,28,11,2025-07-11,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,1,2,2,E,E,0,No Deposit,,543.0,0,Transient,119.7,0,3
HB-072805,City Hotel,1,123,2025,August,32,7,2025-08-07,1,1,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.0,0,0
HB-029899,Resort Hotel,0,6,2024,November,45,8,2024-11-08,0,1,2,0.0,0,BB,AUT,Offline TA/TO,TA/TO,0,0,0,D,E,0,No Deposit,251.0,,0,Transient-Party,42.0,0,1
HB-028703,Resort Hotel,0,11,2024,October,41,9,2024-10-09,1,0,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,405.0,0,Transient-Party,50.0,1,1
HB-016207,Resort Hotel,0,195,2023,August,32,10,2023-08-10,3,6,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,196.0,0,2
HB-033685,Resort Hotel,0,26,2025,February,9,24,2025-02-24,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient-Party,58.0,0,0
HB-062807,City Hotel,1,59,2025,January,4,23,2025-01-23,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,326.0,,0,Transient,80.0,0,0
HB-042846,City Hotel,0,168,2023,September,37,11,2023-09-11,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,56.67,0,0
HB-088774,City Hotel,0,1,2025,January,1,4,2025-01-04,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,1,1,11,A,A,0,No Deposit,,219.0,0,Transient,89.0,1,2
HB-073380,City Hotel,1,202,2025,August,34,19,2025-08-19,2,5,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,106.59,0,0
HB-047919,City Hotel,1,29,2024,March,10,9,2024-03-09,0,3,2,2.0,0,BB,USA,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient,77.5,0,2
HB-036335,Resort Hotel,0,215,2025,May,18,3,2025-05-03,4,10,2,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,63.57,0,1
HB-025156,Resort Hotel,0,191,2024,June,24,12,2024-06-12,2,2,2,2.0,0,HB,PRT,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,242.0,,0,Transient,145.2,1,1
HB-044203,City Hotel,0,164,2023,October,40,2,2023-10-02,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,19.0,,0,Transient-Party,100.0,0,0
HB-086200,City Hotel,0,48,2024,March,13,28,2024-03-28,1,1,2,0.0,0,BB,RUS,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,80.1,0,1
HB-041534,City Hotel,0,46,2023,August,33,17,2023-08-17,1,1,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-107150,City Hotel,0,17,2025,March,10,5,2025-03-05,2,1,1,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,D,D,1,No Deposit,37.0,,0,Transient-Party,60.0,0,2
HB-067860,City Hotel,1,85,2025,May,19,8,2025-05-08,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-060406,City Hotel,1,11,2024,November,45,10,2024-11-10,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,140.0,0,1
HB-113158,City Hotel,0,77,2025,May,22,31,2025-05-31,0,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,159.0,0,2
HB-013592,Resort Hotel,1,247,2025,August,34,21,2025-08-21,1,3,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,244.0,0,0
HB-063182,City Hotel,1,56,2025,February,5,1,2025-02-01,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,60.0,0,0
HB-011190,Resort Hotel,1,34,2025,April,17,27,2025-04-27,2,3,2,2.0,0,HB,ESP,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,173.0,0,2
HB-014163,Resort Hotel,0,13,2025,May,18,2,2025-05-02,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,154.0,0,Transient,45.0,0,0
HB-084739,City Hotel,0,115,2024,February,9,27,2024-02-27,2,3,1,0.0,0,BB,MOZ,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,134.0,,0,Transient-Party,76.0,0,0
HB-091155,City Hotel,0,22,2024,June,24,13,2024-06-13,1,3,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,8.0,,0,Transient,206.0,0,2
HB-105727,City Hotel,0,0,2025,February,7,15,2025-02-15,0,0,0,0.0,0,SC,PRT,Online TA,TA/TO,1,0,0,A,K,0,No Deposit,7.0,,0,Transient,0.0,0,1
HB-011617,Resort Hotel,1,259,2025,May,21,21,2025-05-21,2,2,2,2.0,0,BB,USA,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,130.0,0,0
HB-101080,City Hotel,0,5,2024,November,45,4,2024-11-04,0,2,1,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,2
HB-014943,Resort Hotel,0,152,2025,April,14,5,2025-04-05,0,4,1,0.0,0,BB,GBR,Groups,Corporate,1,0,3,A,E,3,No Deposit,,223.0,0,Transient-Party,42.0,0,0
HB-091935,City Hotel,0,126,2024,June,26,26,2024-06-26,2,0,1,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.9,0,1
HB-040759,City Hotel,0,0,2023,August,31,6,2023-08-06,2,5,1,0.0,0,BB,AGO,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,67.0,0,0
HB-041562,City Hotel,0,11,2023,August,33,18,2023-08-18,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,90.0,0,1
HB-044427,City Hotel,1,97,2023,October,40,5,2023-10-05,1,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,140.0,0,0
HB-016933,Resort Hotel,0,5,2024,April,16,19,2024-04-19,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,3,A,D,0,No Deposit,,86.0,0,Transient,59.0,0,0
HB-028376,Resort Hotel,0,195,2024,September,38,22,2024-09-22,2,8,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Contract,46.75,0,0
HB-041875,City Hotel,1,12,2023,August,34,25,2023-08-25,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,12.0,0,1
HB-011565,Resort Hotel,1,336,2025,May,20,17,2025-05-17,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,54.86,0,1
HB-030543,Resort Hotel,0,31,2024,November,47,19,2024-11-19,2,5,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,177.0,,0,Transient,52.4,0,0
HB-052500,City Hotel,1,213,2024,June,23,7,2024-06-07,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,62,Transient,130.0,0,0
HB-093164,City Hotel,0,155,2024,July,28,10,2024-07-10,3,5,2,2.0,0,HB,PRT,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,9.0,,0,Transient,218.03,0,2
HB-076741,City Hotel,0,0,2023,August,31,5,2023-08-05,0,2,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.0,0,0
HB-093710,City Hotel,0,24,2024,July,30,23,2024-07-23,1,1,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,139.0,0,1
HB-016868,Resort Hotel,0,222,2023,September,37,14,2023-09-14,1,1,2,0.0,0,HB,FRA,Groups,TA/TO,0,0,0,A,D,0,No Deposit,68.0,,0,Transient-Party,80.0,0,0
HB-016340,Resort Hotel,0,70,2023,August,33,17,2023-08-17,3,5,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,E,D,0,No Deposit,241.0,,0,Transient,119.97,0,1
HB-036147,Resort Hotel,0,0,2025,May,19,11,2025-05-11,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,C,0,No Deposit,250.0,,0,Transient,80.0,0,0
HB-063183,City Hotel,1,56,2025,February,5,1,2025-02-01,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,60.0,0,0
HB-002093,Resort Hotel,0,24,2023,October,39,1,2023-10-01,0,3,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,93.0,1,2
HB-077965,City Hotel,0,16,2023,September,39,25,2023-09-25,2,3,1,0.0,0,BB,BEL,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,170.0,0,0
HB-098217,City Hotel,0,19,2024,September,39,23,2024-09-23,1,2,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,9.0,,0,Transient,139.0,0,1
HB-117081,City Hotel,0,177,2025,July,30,27,2025-07-27,0,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,89.0,0,1
HB-057016,City Hotel,1,205,2024,September,38,16,2024-09-16,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,120.0,0,0
HB-065313,City Hotel,1,67,2025,March,14,31,2025-03-31,0,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,0
HB-019056,Resort Hotel,0,120,2023,December,49,4,2023-12-04,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,240.0,,0,Transient,32.4,0,1
HB-028734,Resort Hotel,0,17,2024,October,41,10,2024-10-10,0,0,1,0.0,0,BB,PRT,Groups,Corporate,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,0.0,0,0
HB-026913,Resort Hotel,0,122,2024,August,31,4,2024-08-04,3,8,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,221.0,0,0
HB-111504,City Hotel,0,15,2025,May,19,10,2025-05-10,0,2,1,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,166.25,0,1
HB-106565,City Hotel,0,3,2025,February,9,26,2025-02-26,1,0,1,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,62.4,0,0
HB-038028,Resort Hotel,0,8,2025,July,27,6,2025-07-06,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,147.25,0,1
HB-015405,Resort Hotel,0,30,2023,July,27,6,2023-07-06,2,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,155.0,0,0
HB-036616,Resort Hotel,0,98,2025,May,20,16,2025-05-16,2,7,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,95.0,,0,Transient,49.78,0,0
HB-070126,City Hotel,1,68,2025,June,24,10,2025-06-10,1,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,170.0,0,2
HB-053102,City Hotel,1,188,2024,June,24,15,2024-06-15,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,39,Transient,130.0,0,0
HB-028302,Resort Hotel,0,237,2024,September,37,15,2024-09-15,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Contract,64.9,0,0
HB-069323,City Hotel,1,230,2025,May,22,30,2025-05-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,44,Transient,130.0,0,0
HB-105298,City Hotel,0,46,2025,February,5,2,2025-02-02,0,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,0
HB-046906,City Hotel,1,16,2024,January,4,25,2024-01-25,1,4,2,0.0,0,BB,MAR,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient-Party,77.25,0,0
HB-108751,City Hotel,0,4,2025,March,13,29,2025-03-29,0,3,2,0.0,0,SC,BGR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,78.4,0,0
HB-106465,City Hotel,0,134,2025,February,9,25,2025-02-25,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,75.0,0,0
HB-083845,City Hotel,0,22,2024,February,7,12,2024-02-12,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,76.5,0,2
HB-048136,City Hotel,1,75,2024,March,11,17,2024-03-17,1,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient,70.0,0,0
HB-003323,Resort Hotel,0,66,2023,December,49,5,2023-12-05,1,1,2,0.0,0,FB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,68.0,,0,Transient-Party,64.0,0,0
HB-097933,City Hotel,0,2,2024,October,41,8,2024-10-08,2,2,1,0.0,0,BB,ITA,Aviation,Corporate,1,0,1,D,D,2,No Deposit,153.0,,0,Transient,110.0,0,0
HB-075815,City Hotel,1,330,2023,September,37,12,2023-09-12,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-068293,City Hotel,1,104,2025,May,20,15,2025-05-15,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-076929,City Hotel,1,342,2023,September,38,24,2023-09-24,2,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-074394,City Hotel,1,283,2023,July,30,27,2023-07-27,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-065550,City Hotel,1,373,2025,April,14,5,2025-04-05,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-003605,Resort Hotel,1,0,2023,December,52,25,2023-12-25,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,Non Refund,240.0,,0,Transient,55.0,0,0
HB-050327,City Hotel,1,59,2024,April,17,28,2024-04-28,2,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,128.69,0,0
HB-019804,Resort Hotel,0,9,2024,January,1,4,2024-01-04,0,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,0.0,0,0
HB-019881,Resort Hotel,0,0,2024,January,2,11,2024-01-11,1,2,1,0.0,0,BB,PRT,Direct,Direct,1,0,0,A,D,1,No Deposit,,,0,Transient,38.0,0,0
HB-079676,City Hotel,0,0,2023,October,44,31,2023-10-31,0,1,2,2.0,0,BB,PRT,Complementary,Direct,0,0,0,F,G,0,No Deposit,45.0,,0,Transient,0.0,0,0
HB-035347,Resort Hotel,0,60,2025,April,16,15,2025-04-15,2,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,104.0,0,2
HB-114613,City Hotel,0,149,2025,June,26,24,2025-06-24,0,1,2,0.0,0,HB,USA,Corporate,Corporate,0,0,0,A,A,0,No Deposit,495.0,,0,Transient-Party,154.0,0,1
HB-018988,Resort Hotel,1,15,2023,December,49,5,2023-12-05,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,E,0,No Deposit,,,0,Transient,43.0,0,1
HB-053708,City Hotel,1,35,2024,June,26,27,2024-06-27,1,5,2,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,128.4,0,0
HB-005661,Resort Hotel,1,192,2024,May,19,8,2024-05-08,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,147.0,,0,Transient,53.87,0,0
HB-110130,City Hotel,0,44,2025,April,16,20,2025-04-20,0,3,2,0.0,0,BB,ITA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,133.33,0,1
HB-053776,City Hotel,1,358,2024,June,26,30,2024-06-30,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,59.0,0,0
HB-041523,City Hotel,0,6,2023,August,33,17,2023-08-17,1,5,2,0.0,1,BB,MAR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Contract,104.0,1,2
HB-044557,City Hotel,0,92,2023,October,40,7,2023-10-07,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,58,Transient-Party,70.0,0,0
HB-037009,Resort Hotel,0,1,2025,June,22,1,2025-06-01,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,109.0,1,1
HB-063566,City Hotel,1,12,2025,February,7,14,2025-02-14,0,1,1,0.0,0,BB,AGO,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,0
HB-064581,City Hotel,1,52,2025,March,11,13,2025-03-13,1,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,56.0,,0,Transient,80.0,0,0
HB-030083,Resort Hotel,0,34,2024,November,45,10,2024-11-10,1,3,3,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,C,0,No Deposit,171.0,,0,Transient,77.18,0,0
HB-019827,Resort Hotel,0,148,2024,January,1,2,2024-01-02,2,1,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,100.33,1,3
HB-076796,City Hotel,0,1,2023,August,32,8,2023-08-08,2,1,2,0.0,0,BB,BRA,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,75.0,0,0
HB-017706,Resort Hotel,0,1,2024,July,29,16,2024-07-16,1,1,2,0.0,0,BB,PRT,Direct,Direct,1,0,1,A,A,0,No Deposit,,,0,Transient,142.0,1,0
HB-023764,Resort Hotel,0,23,2024,April,18,30,2024-04-30,2,1,2,0.0,0,BB,PHL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,98.33,0,2
HB-080184,City Hotel,0,21,2025,January,5,30,2025-01-30,1,0,1,0.0,0,BB,FRA,Direct,Direct,1,0,1,A,A,1,No Deposit,,91.0,0,Transient,80.0,0,1
HB-041540,City Hotel,0,0,2023,August,33,18,2023-08-18,0,1,1,0.0,0,SC,AGO,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,100.0,0,0
HB-001386,Resort Hotel,0,10,2023,August,34,27,2023-08-27,2,5,2,1.0,0,BB,GBR,Direct,Direct,0,0,0,C,C,0,No Deposit,250.0,,0,Transient,155.86,0,2
HB-065345,City Hotel,1,55,2025,March,14,31,2025-03-31,2,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,82.42,0,1
HB-103724,City Hotel,0,1,2024,December,52,27,2024-12-27,0,3,2,0.0,0,SC,PRT,Direct,Direct,0,0,0,A,B,0,No Deposit,,,0,Transient,97.0,0,0
HB-033652,Resort Hotel,0,7,2025,February,9,26,2025-02-26,2,0,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,107.0,1,1
HB-117235,City Hotel,0,468,2025,July,31,29,2025-07-29,2,1,2,0.0,0,BB,ZAF,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,1
HB-106056,City Hotel,0,23,2025,February,8,17,2025-02-17,1,2,1,0.0,0,BB,EST,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient,75.0,0,0
HB-069312,City Hotel,1,130,2025,May,22,30,2025-05-30,0,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-006133,Resort Hotel,0,225,2024,May,21,26,2024-05-26,1,3,2,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,D,2,No Deposit,,223.0,0,Transient-Party,66.0,0,0
HB-010372,Resort Hotel,1,240,2025,March,9,1,2025-03-01,4,10,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,26.64,0,0
HB-042077,City Hotel,0,13,2023,August,35,30,2023-08-30,2,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,99.0,0,2
HB-049638,City Hotel,1,94,2024,April,16,16,2024-04-16,2,2,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,0
HB-012014,Resort Hotel,1,304,2025,June,23,8,2025-06-08,2,3,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,298.0,,0,Transient,66.0,0,0
HB-117500,City Hotel,0,1,2025,August,31,3,2025-08-03,0,2,2,1.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,185.0,0,0
HB-079094,City Hotel,0,5,2023,October,42,19,2023-10-19,1,2,2,0.0,0,BB,POL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,112.0,,0,Transient-Party,90.0,0,0
HB-087096,City Hotel,0,38,2024,April,15,11,2024-04-11,1,2,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,103.5,1,0
HB-078535,City Hotel,1,36,2023,November,46,13,2023-11-13,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Transient,105.3,0,1
HB-093070,City Hotel,0,134,2024,July,28,12,2024-07-12,0,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,89.85,0,2
HB-085632,City Hotel,0,0,2024,March,11,15,2024-03-15,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Transient,55.0,0,0
HB-070083,City Hotel,1,142,2025,June,24,9,2025-06-09,1,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.33,0,0
HB-070717,City Hotel,1,153,2025,June,25,21,2025-06-21,0,4,1,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,A,0,Non Refund,,348.0,0,Transient,110.0,0,0
HB-026428,Resort Hotel,0,143,2024,July,30,25,2024-07-25,1,5,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,127.2,1,0
HB-063265,City Hotel,1,9,2025,February,6,4,2025-02-04,1,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,0
HB-093874,City Hotel,0,56,2024,July,30,27,2024-07-27,0,1,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,125.1,0,1
HB-060557,City Hotel,1,56,2024,November,46,14,2024-11-14,1,5,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.4,0,0
HB-076196,City Hotel,0,260,2023,July,27,4,2023-07-04,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-004078,Resort Hotel,1,111,2024,February,7,12,2024-02-12,0,2,2,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,38.0,,0,Transient,70.0,0,0
HB-085007,City Hotel,1,44,2024,March,10,7,2024-03-07,1,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,K,0,No Deposit,118.0,,0,Transient-Party,65.4,0,0
HB-109082,City Hotel,0,77,2025,April,14,3,2025-04-03,1,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,C,0,No Deposit,42.0,,0,Transient,89.1,0,0
HB-042409,City Hotel,0,61,2023,September,36,5,2023-09-05,2,2,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-039731,Resort Hotel,0,7,2025,August,35,25,2025-08-25,0,2,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,222.0,0,1
HB-085098,City Hotel,0,8,2024,March,10,8,2024-03-08,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,96.0,0,1
HB-063898,City Hotel,1,195,2025,February,9,24,2025-02-24,2,3,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,2
HB-017106,Resort Hotel,0,262,2023,September,38,21,2023-09-21,1,3,2,0.0,0,HB,BEL,Groups,Corporate,0,0,0,A,A,0,No Deposit,183.0,,0,Transient,89.2,0,0
HB-050905,City Hotel,1,115,2024,May,19,11,2024-05-11,0,4,2,0.0,0,BB,HUN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.65,0,0
HB-007053,Resort Hotel,1,182,2024,July,29,18,2024-07-18,1,4,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,154.3,0,3
HB-052666,City Hotel,1,337,2024,June,23,9,2024-06-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-093648,City Hotel,0,63,2024,July,30,23,2024-07-23,0,1,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.5,0,2
HB-066144,City Hotel,1,173,2025,April,16,14,2025-04-14,2,2,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,155.7,0,0
HB-034242,Resort Hotel,0,112,2025,March,11,15,2025-03-15,0,3,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,477.0,0,Transient-Party,40.0,0,0
HB-102304,City Hotel,0,56,2024,November,47,22,2024-11-22,0,4,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,119.0,0,2
HB-026311,Resort Hotel,0,137,2024,July,30,25,2024-07-25,1,2,2,1.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,171.0,,0,Transient,173.25,0,0
HB-091292,City Hotel,0,1,2024,June,25,17,2024-06-17,0,2,2,0.0,0,SC,IRN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,152.0,,0,Transient,77.71,0,0
HB-093582,City Hotel,0,14,2024,July,29,21,2024-07-21,0,2,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,1,No Deposit,,174.0,0,Transient-Party,105.0,0,0
HB-013375,Resort Hotel,1,341,2025,August,33,12,2025-08-12,4,6,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,138.38,0,2
HB-084424,City Hotel,0,1,2024,February,8,25,2024-02-25,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,86.0,0,0
HB-054546,City Hotel,1,12,2024,July,29,20,2024-07-20,0,1,1,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.0,0,0
HB-091298,City Hotel,0,160,2024,June,25,17,2024-06-17,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,129.0,0,1
HB-021622,Resort Hotel,0,0,2024,March,10,5,2024-03-05,0,1,2,2.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,0,No Deposit,,,0,Transient,75.0,0,0
HB-042738,City Hotel,1,86,2023,September,36,9,2023-09-09,0,2,2,0.0,0,BB,FRA,Groups,Corporate,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,110.0,0,0
HB-064086,City Hotel,1,1,2025,March,9,1,2025-03-01,0,4,2,0.0,0,SC,NGA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,1
HB-085101,City Hotel,0,1,2024,May,21,24,2024-05-24,0,1,1,0.0,0,SC,ITA,Online TA,TA/TO,1,0,1,A,A,0,No Deposit,9.0,,0,Transient,129.0,0,0
HB-060699,City Hotel,1,50,2024,November,47,18,2024-11-18,1,2,1,0.0,0,BB,LUX,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,86.4,0,2
HB-025351,Resort Hotel,0,96,2024,June,24,12,2024-06-12,4,7,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,F,1,No Deposit,243.0,,0,Contract,83.85,0,0
HB-029287,Resort Hotel,0,4,2024,October,43,24,2024-10-24,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,1,No Deposit,,254.0,0,Transient,54.9,0,0
HB-112777,City Hotel,0,202,2025,May,21,25,2025-05-25,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,96.32,0,1
HB-080381,City Hotel,1,34,2023,December,49,8,2023-12-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,0,Transient,90.0,0,0
HB-067345,City Hotel,1,20,2025,May,18,2,2025-05-02,0,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,169.0,0,1
HB-046324,City Hotel,1,140,2023,December,52,29,2023-12-29,0,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,70.0,0,0
HB-034119,Resort Hotel,0,15,2025,March,11,11,2025-03-11,1,1,2,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,0.0,0,0
HB-086951,City Hotel,0,0,2024,April,15,11,2024-04-11,1,0,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,88.65,0,0
HB-090482,City Hotel,0,119,2024,June,23,7,2024-06-07,0,3,2,0.0,0,BB,TUR,Offline TA/TO,Corporate,0,0,0,A,A,2,No Deposit,191.0,,0,Transient-Party,120.0,0,0
HB-079414,City Hotel,1,137,2024,January,4,27,2024-01-27,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,29.0,,45,Transient,70.0,0,0
HB-093979,City Hotel,0,131,2024,July,31,29,2024-07-29,0,1,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.5,0,1
HB-027884,Resort Hotel,0,34,2024,September,37,11,2024-09-11,2,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,141.0,1,3
HB-083440,City Hotel,0,13,2024,January,5,31,2024-01-31,2,0,1,0.0,0,BB,FRA,Corporate,Corporate,0,0,0,A,A,1,No Deposit,,179.0,0,Transient,80.0,0,0
HB-001360,Resort Hotel,0,76,2023,August,34,26,2023-08-26,0,4,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,156.0,,0,Transient,116.85,0,3
HB-085489,City Hotel,0,30,2024,March,13,26,2024-03-26,1,1,3,0.0,0,BB,COL,Direct,Direct,0,0,1,A,D,0,No Deposit,14.0,,0,Transient,142.1,0,1
HB-087629,City Hotel,0,4,2024,April,16,19,2024-04-19,0,4,2,1.0,0,BB,ESP,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,125.58,0,2
HB-046615,City Hotel,0,5,2024,January,2,11,2024-01-11,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,99.0,0,1
HB-072855,City Hotel,1,478,2025,August,32,8,2025-08-08,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-042258,City Hotel,0,41,2023,September,36,4,2023-09-04,0,1,1,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,B,0,No Deposit,39.0,,38,Transient-Party,83.0,0,0
HB-106124,City Hotel,0,43,2025,February,8,19,2025-02-19,2,0,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.0,0,2
HB-076201,City Hotel,0,260,2023,July,27,4,2023-07-04,2,2,3,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,84.0,0,0
HB-052530,City Hotel,1,56,2024,June,23,8,2024-06-08,0,1,2,0.0,0,BB,PRT,Offline TA/TO,Corporate,0,0,0,A,A,0,No Deposit,191.0,,0,Transient-Party,120.0,0,0
HB-077962,City Hotel,0,7,2023,September,39,28,2023-09-28,1,1,1,0.0,0,BB,USA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,170.0,0,0
HB-011811,Resort Hotel,1,411,2025,May,22,31,2025-05-31,2,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,71.1,0,0
HB-013714,Resort Hotel,1,61,2025,August,35,27,2025-08-27,2,2,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,222.0,0,2
HB-024970,Resort Hotel,0,1,2024,June,24,10,2024-06-10,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,G,0,No Deposit,,,0,Transient,120.0,1,0
HB-028309,Resort Hotel,0,195,2024,September,38,22,2024-09-22,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Contract,53.85,0,0
HB-018853,Resort Hotel,0,0,2023,December,48,1,2023-12-01,0,1,1,0.0,0,BB,RUS,Direct,Direct,1,0,0,A,A,1,No Deposit,,,0,Transient,38.0,0,2
HB-004454,Resort Hotel,1,14,2024,March,12,19,2024-03-19,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient,29.0,0,0
HB-076335,City Hotel,0,271,2023,July,28,15,2023-07-15,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-104967,City Hotel,0,78,2025,January,4,25,2025-01-25,0,2,1,0.0,0,BB,RUS,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,365.0,0,Transient-Party,85.0,0,0
HB-021221,Resort Hotel,0,26,2024,February,7,17,2024-02-17,1,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-025065,Resort Hotel,0,132,2024,June,23,6,2024-06-06,2,5,2,0.0,1,BB,GBR,Direct,Direct,0,0,0,E,F,1,No Deposit,250.0,,0,Transient,100.44,0,2
HB-011585,Resort Hotel,1,38,2025,May,21,19,2025-05-19,0,2,4,0.0,0,BB,PRT,Direct,Direct,0,0,0,H,H,0,No Deposit,,,0,Transient,209.0,0,2
HB-042633,City Hotel,1,11,2023,September,36,8,2023-09-08,0,4,2,1.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,B,B,0,No Deposit,6.0,,0,Transient,78.94,0,2
HB-047829,City Hotel,1,16,2024,March,10,5,2024-03-05,1,1,2,0.0,0,SC,ZAF,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,84.0,0,0
HB-092560,City Hotel,0,55,2024,July,27,7,2024-07-07,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,219.0,0,Transient,79.0,0,0
HB-100048,City Hotel,0,2,2024,October,42,19,2024-10-19,0,3,3,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,7.0,,0,Transient,198.28,0,1
HB-091722,City Hotel,0,265,2024,June,26,24,2024-06-24,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-089627,City Hotel,0,4,2024,May,21,23,2024-05-23,1,0,1,0.0,0,SC,POL,Offline TA/TO,GDS,0,0,0,A,A,0,No Deposit,195.0,,0,Transient,153.0,0,1
HB-094195,City Hotel,0,0,2024,July,31,31,2024-07-31,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,132.0,0,0
HB-118451,City Hotel,0,109,2025,August,33,16,2025-08-16,0,4,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,225.0,0,1
HB-052018,City Hotel,1,95,2024,May,22,29,2024-05-29,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,65.0,0,0
HB-097745,City Hotel,0,5,2024,September,38,19,2024-09-19,1,0,1,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,159.0,0,1
HB-069559,City Hotel,1,181,2025,June,23,2,2025-06-02,0,2,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,193.5,0,0
HB-011055,Resort Hotel,1,132,2025,April,16,16,2025-04-16,2,4,3,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,40.0,,0,Transient,83.84,0,1
HB-067913,City Hotel,1,0,2025,May,19,9,2025-05-09,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,39.0,,0,Transient-Party,130.0,0,0
HB-118769,City Hotel,0,37,2025,August,34,24,2025-08-24,0,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.0,0,1
HB-059834,City Hotel,1,482,2024,November,44,3,2024-11-03,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-093671,City Hotel,0,175,2024,July,30,23,2024-07-23,1,1,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.5,0,1
HB-075249,City Hotel,1,297,2023,August,32,10,2023-08-10,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-102877,City Hotel,0,27,2024,December,49,7,2024-12-07,0,1,2,0.0,0,BB,CZE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,104.0,0,2
HB-078786,City Hotel,0,14,2023,October,41,15,2023-10-15,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,99.0,,0,Transient-Party,100.0,0,0
HB-117863,City Hotel,0,44,2025,August,32,9,2025-08-09,0,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,1
HB-089816,City Hotel,0,74,2024,May,21,21,2024-05-21,2,3,2,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,132.6,0,3
HB-077054,City Hotel,1,262,2023,November,45,9,2023-11-09,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-009514,Resort Hotel,1,14,2024,December,49,5,2024-12-05,1,2,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,84.0,0,0
HB-031374,Resort Hotel,0,124,2024,December,52,23,2024-12-23,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,51.13,0,3
HB-088500,City Hotel,0,111,2024,May,18,4,2024-05-04,0,4,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,11.0,,0,Transient,122.1,0,1
HB-102875,City Hotel,0,1,2024,December,49,6,2024-12-06,0,2,1,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,78.0,0,1
HB-083324,City Hotel,0,12,2025,May,22,29,2025-05-29,1,0,1,0.0,0,BB,PRT,Complementary,Direct,1,0,1,A,A,0,No Deposit,,45.0,0,Transient,0.0,0,0
HB-036774,Resort Hotel,0,203,2025,May,21,25,2025-05-25,0,3,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,223.0,0,Transient-Party,55.0,1,0
HB-055797,City Hotel,1,40,2024,August,34,21,2024-08-21,2,1,1,0.0,0,BB,MAR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,125.1,0,0
HB-013194,Resort Hotel,1,34,2025,August,32,4,2025-08-04,1,2,3,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,283.6,0,1
HB-115106,City Hotel,0,123,2025,June,26,28,2025-06-28,0,4,1,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,96.53,0,0
HB-076628,City Hotel,0,209,2023,July,30,29,2023-07-29,1,4,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,55.96,0,0
HB-015193,Resort Hotel,1,253,2023,September,37,12,2023-09-12,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,96.0,,0,Transient,58.95,0,0
HB-015859,Resort Hotel,0,0,2023,August,31,3,2023-08-03,1,1,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,241.0,0,0
HB-086444,City Hotel,0,18,2024,April,14,2,2024-04-02,0,1,2,0.0,0,SC,BGR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,129.0,0,1
HB-091524,City Hotel,0,1,2024,June,25,22,2024-06-22,0,1,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.0,0,1
HB-109970,City Hotel,0,83,2025,April,16,17,2025-04-17,1,2,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,171.0,0,1
HB-113249,City Hotel,0,144,2025,June,22,1,2025-06-01,0,3,3,0.0,0,BB,IRL,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient-Party,168.55,0,2
HB-094375,City Hotel,0,0,2024,April,16,19,2024-04-19,0,1,1,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,A,0,No Deposit,,45.0,0,Transient,0.0,0,0
HB-033319,Resort Hotel,0,0,2025,February,8,19,2025-02-19,1,0,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,60.0,1,0
HB-009893,Resort Hotel,1,41,2025,January,3,17,2025-01-17,0,2,1,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,A,D,1,No Deposit,,,0,Transient-Party,55.0,0,0
HB-070378,City Hotel,1,50,2025,June,25,16,2025-06-16,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,126.0,0,0
HB-008789,Resort Hotel,0,342,2024,October,42,14,2024-10-14,2,5,2,0.0,0,BB,GBR,Groups,Direct,0,0,0,E,F,0,No Deposit,273.0,,125,Transient-Party,80.81,0,0
HB-091627,City Hotel,0,9,2024,June,25,23,2024-06-23,0,1,3,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,127.0,0,3
HB-050020,City Hotel,1,61,2024,April,17,22,2024-04-22,1,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,118.8,0,0
HB-005927,Resort Hotel,1,28,2024,May,20,16,2024-05-16,3,6,3,1.0,0,BB,IRL,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,140.0,0,0
HB-097591,City Hotel,0,22,2024,September,38,16,2024-09-16,0,2,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,239.0,0,2
HB-037362,Resort Hotel,0,146,2025,June,24,10,2025-06-10,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,240.0,,0,Transient,110.0,0,1
HB-026307,Resort Hotel,0,130,2024,July,30,25,2024-07-25,1,2,4,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,C,4,No Deposit,240.0,,0,Transient,208.0,0,0
HB-009660,Resort Hotel,1,91,2024,December,52,23,2024-12-23,2,4,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,G,G,3,No Deposit,240.0,,0,Transient-Party,137.5,0,0
HB-006767,Resort Hotel,1,62,2024,July,27,1,2024-07-01,0,2,2,2.0,0,BB,IND,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,220.0,0,0
HB-078035,City Hotel,1,1,2023,October,40,2,2023-10-02,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,1,1,0,A,A,0,No Deposit,19.0,,0,Transient-Party,100.0,0,0
HB-092840,City Hotel,0,2,2024,July,28,12,2024-07-12,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,151.0,0,0
HB-091350,City Hotel,0,44,2024,June,25,18,2024-06-18,1,1,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,E,0,No Deposit,6.0,,0,Transient,96.3,0,0
HB-117931,City Hotel,0,277,2025,August,32,9,2025-08-09,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,92.86,0,1
HB-066748,City Hotel,1,102,2025,April,17,24,2025-04-24,1,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,100.0,0,0
HB-052091,City Hotel,1,55,2024,May,22,30,2024-05-30,1,2,1,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.35,0,0
HB-008444,Resort Hotel,1,63,2024,September,39,28,2024-09-28,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,96.0,,0,Transient-Party,76.0,0,0
HB-093548,City Hotel,0,292,2024,July,29,21,2024-07-21,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,0
HB-067457,City Hotel,1,214,2025,May,18,3,2025-05-03,0,4,2,1.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,133.2,0,2
HB-055640,City Hotel,1,405,2024,August,33,18,2024-08-18,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-065714,City Hotel,1,69,2025,April,14,6,2025-04-06,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,Non Refund,,197.0,0,Transient,85.0,0,0
HB-026066,Resort Hotel,0,55,2024,July,29,21,2024-07-21,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,172.0,0,1
HB-044761,City Hotel,0,79,2023,October,41,10,2023-10-10,1,1,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-028903,Resort Hotel,0,33,2024,October,41,13,2024-10-13,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,F,0,No Deposit,,444.0,0,Transient-Party,40.0,0,0
HB-091397,City Hotel,0,0,2024,October,41,10,2024-10-10,1,0,1,0.0,0,BB,ESP,Corporate,Corporate,1,0,1,A,B,0,No Deposit,,62.0,0,Transient,95.0,0,0
HB-087693,City Hotel,0,2,2024,April,17,23,2024-04-23,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,131.0,0,0
HB-117126,City Hotel,0,47,2025,July,31,28,2025-07-28,0,2,2,1.0,0,HB,SWE,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,9.0,,0,Transient,307.0,0,0
HB-101560,City Hotel,0,57,2024,November,46,11,2024-11-11,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,28.0,,0,Transient,75.0,0,0
HB-099452,City Hotel,0,21,2024,October,41,10,2024-10-10,1,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,85.0,,0,Transient,107.0,0,0
HB-043378,City Hotel,1,74,2023,September,38,18,2023-09-18,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-024049,Resort Hotel,0,3,2024,May,19,8,2024-05-08,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient,79.0,0,1
HB-012175,Resort Hotel,1,250,2025,June,25,16,2025-06-16,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,80.1,0,1
HB-045934,City Hotel,0,84,2023,November,48,27,2023-11-27,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,56.0,0,0
HB-037130,Resort Hotel,0,324,2025,June,22,1,2025-06-01,2,5,1,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Contract,63.95,0,0
HB-042437,City Hotel,1,3,2023,September,36,5,2023-09-05,2,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,0.0,0,0
HB-011612,Resort Hotel,1,60,2025,May,21,21,2025-05-21,2,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,169.0,0,Transient-Party,50.0,0,0
HB-090984,City Hotel,0,11,2024,June,24,14,2024-06-14,0,1,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,10.0,,0,Transient,78.8,0,0
HB-002901,Resort Hotel,0,34,2023,November,44,5,2023-11-05,2,8,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,2,No Deposit,185.0,281.0,0,Transient-Party,43.2,0,0
HB-056168,City Hotel,1,20,2024,August,35,31,2024-08-31,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,122.0,0,1
HB-043527,City Hotel,1,75,2023,September,38,19,2023-09-19,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-101480,City Hotel,0,57,2024,November,46,11,2024-11-11,0,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-106261,City Hotel,0,64,2025,February,8,20,2025-02-20,1,3,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,0
HB-014464,Resort Hotel,0,2,2023,July,26,1,2023-07-01,0,1,1,0.0,0,BB,,Online TA,TA/TO,0,0,1,A,C,0,No Deposit,240.0,,0,Transient,4.0,0,1
HB-076435,City Hotel,1,358,2023,October,41,10,2023-10-10,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-049789,City Hotel,1,103,2024,April,16,19,2024-04-19,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,0,Transient,115.0,0,0
HB-039800,Resort Hotel,0,36,2025,August,35,25,2025-08-25,1,2,3,0.0,0,FB,PRT,Online TA,TA/TO,0,0,0,A,A,3,No Deposit,5.0,,0,Transient,259.0,0,0
HB-117601,City Hotel,0,1,2025,August,31,3,2025-08-03,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,182.5,0,0
HB-064447,City Hotel,1,196,2025,March,10,9,2025-03-09,2,5,2,1.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,D,4,No Deposit,9.0,,0,Transient,105.3,0,3
HB-030175,Resort Hotel,0,29,2024,November,46,15,2024-11-15,0,1,1,0.0,0,BB,FRA,Groups,Corporate,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,48.0,0,0
HB-105638,City Hotel,0,12,2025,February,7,11,2025-02-11,1,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,2
HB-055630,City Hotel,1,320,2024,August,33,18,2024-08-18,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,0
HB-010424,Resort Hotel,1,312,2025,March,10,5,2025-03-05,2,5,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,30.0,0,0
HB-087169,City Hotel,0,48,2024,April,15,11,2024-04-11,1,3,2,0.0,0,BB,NLD,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,107.1,0,0
HB-064242,City Hotel,1,37,2025,March,9,2,2025-03-02,2,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,100.3,0,0
HB-080485,City Hotel,1,25,2023,December,49,8,2023-12-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,0,Transient,90.0,0,0
HB-078866,City Hotel,0,32,2023,October,41,14,2023-10-14,0,4,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.58,0,1
HB-011858,Resort Hotel,1,1,2025,June,23,2,2025-06-02,0,2,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,348.0,,0,Transient,105.0,0,0
HB-023184,Resort Hotel,0,0,2024,April,15,12,2024-04-12,0,5,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,E,0,No Deposit,152.0,,0,Transient,55.0,0,0
HB-097802,City Hotel,0,0,2024,September,38,20,2024-09-20,0,1,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,A,E,0,No Deposit,,,0,Transient,210.0,0,0
HB-058657,City Hotel,1,58,2024,October,41,13,2024-10-13,0,3,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,132.3,0,0
HB-031529,Resort Hotel,0,187,2024,December,52,24,2024-12-24,2,5,1,0.0,0,HB,AUT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,75.0,,0,Transient,61.64,0,0
HB-103582,City Hotel,0,15,2024,December,52,27,2024-12-27,0,1,3,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,220.0,,0,Transient-Party,90.0,0,2
HB-061189,City Hotel,1,12,2024,December,49,3,2024-12-03,2,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,89.59,0,0
HB-082715,City Hotel,1,1,2024,January,1,5,2024-01-05,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,77.0,0,0
HB-110612,City Hotel,0,101,2025,April,18,30,2025-04-30,1,0,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,1,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,1
HB-109216,City Hotel,0,69,2025,April,14,6,2025-04-06,0,2,1,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,K,1,No Deposit,,418.0,0,Transient-Party,100.0,0,0
HB-067386,City Hotel,1,16,2025,May,18,3,2025-05-03,0,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,1
HB-075933,City Hotel,1,301,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-030814,Resort Hotel,0,1,2024,December,49,3,2024-12-03,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,G,G,0,No Deposit,,364.0,0,Transient,50.0,0,3
HB-084719,City Hotel,0,115,2024,February,9,27,2024-02-27,2,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,134.0,,0,Transient-Party,76.0,0,0
HB-107538,City Hotel,0,4,2025,March,11,13,2025-03-13,1,0,1,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,254.0,,0,Transient-Party,241.25,0,0
HB-059867,City Hotel,1,304,2024,November,44,3,2024-11-03,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,89.0,0,0
HB-078490,City Hotel,0,12,2023,October,40,5,2023-10-05,1,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,114.0,0,3
HB-060046,City Hotel,1,305,2024,November,45,4,2024-11-04,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,89.0,0,0
HB-113345,City Hotel,0,198,2025,June,23,2,2025-06-02,2,2,1,1.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,115.21,0,1
HB-103691,City Hotel,0,107,2024,December,52,27,2024-12-27,0,3,2,0.0,0,HB,ITA,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,147.67,0,0
HB-100498,City Hotel,0,2,2024,October,43,27,2024-10-27,0,2,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.0,0,3
HB-005434,Resort Hotel,1,114,2024,April,18,29,2024-04-29,1,2,3,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,123.0,0,0
HB-078565,City Hotel,0,1,2024,January,4,28,2024-01-28,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,3,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,1
HB-008944,Resort Hotel,1,110,2024,October,43,21,2024-10-21,0,2,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,77.0,0,0
HB-092447,City Hotel,0,91,2024,July,27,6,2024-07-06,0,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.3,0,0
HB-054429,City Hotel,1,144,2024,July,29,15,2024-07-15,2,4,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.25,0,0
HB-036329,Resort Hotel,0,5,2025,May,20,13,2025-05-13,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,196.0,,0,Transient,94.5,1,0
HB-115960,City Hotel,0,46,2025,July,28,10,2025-07-10,1,2,2,0.0,0,SC,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,2
HB-103773,City Hotel,0,39,2024,December,52,28,2024-12-28,0,4,2,0.0,0,HB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,192.95,0,0
HB-080482,City Hotel,1,25,2023,December,49,8,2023-12-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,0,Transient,90.0,0,0
HB-034179,Resort Hotel,0,1,2025,March,11,14,2025-03-14,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,55.6,0,1
HB-046640,City Hotel,0,7,2024,January,2,13,2024-01-13,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.3,0,1
HB-093279,City Hotel,0,143,2024,July,29,16,2024-07-16,2,2,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,D,A,1,No Deposit,15.0,,0,Transient,115.6,0,0
HB-001062,Resort Hotel,0,33,2023,August,32,12,2023-08-12,0,1,2,0.0,0,BB,PRT,Groups,Corporate,0,0,0,G,G,0,No Deposit,,307.0,0,Transient-Party,252.0,0,1
HB-059546,City Hotel,1,4,2024,October,44,29,2024-10-29,0,1,1,0.0,0,BB,PRT,Aviation,Corporate,0,0,0,D,D,0,No Deposit,,153.0,0,Transient,110.0,0,0
HB-027845,Resort Hotel,0,245,2024,September,36,6,2024-09-06,2,5,3,0.0,0,BB,IRL,Direct,Direct,0,0,0,G,G,0,No Deposit,,,0,Transient-Party,127.0,0,2
HB-030143,Resort Hotel,0,50,2024,November,46,12,2024-11-12,2,1,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,64.8,0,2
HB-035228,Resort Hotel,0,156,2025,April,16,14,2025-04-14,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,60.0,0,2
HB-088508,City Hotel,0,101,2024,May,18,5,2024-05-05,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,126.9,0,1
HB-031817,Resort Hotel,0,3,2025,January,2,7,2025-01-07,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,330.0,,0,Transient-Party,39.0,0,1
HB-056345,City Hotel,1,420,2024,September,36,3,2024-09-03,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,35.0,,0,Transient,75.0,0,0
HB-106319,City Hotel,0,48,2025,February,8,22,2025-02-22,0,2,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,65.0,0,1
HB-066737,City Hotel,1,44,2025,April,17,24,2025-04-24,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,99.0,0,0
HB-104408,City Hotel,0,9,2025,January,2,11,2025-01-11,0,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,42.0,,0,Transient,67.0,0,1
HB-053343,City Hotel,1,156,2024,June,25,18,2024-06-18,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,96.0,0,0
HB-058721,City Hotel,1,163,2024,October,42,15,2024-10-15,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,34.0,,0,Transient,115.0,0,0
HB-031267,Resort Hotel,0,0,2024,December,51,20,2024-12-20,0,1,2,0.0,0,BB,USA,Direct,Direct,0,0,0,A,G,0,No Deposit,,,0,Transient,90.0,1,0
HB-038244,Resort Hotel,0,5,2025,July,28,12,2025-07-12,0,1,1,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,H,0,No Deposit,250.0,,0,Transient,73.95,0,0
HB-097586,City Hotel,0,226,2024,September,38,16,2024-09-16,0,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.9,0,1
HB-027120,Resort Hotel,0,6,2024,August,33,18,2024-08-18,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,189.0,0,1
HB-016708,Resort Hotel,0,78,2023,August,35,30,2023-08-30,4,6,3,0.0,0,BB,GBR,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,168.4,0,1
HB-086759,City Hotel,0,64,2024,April,14,4,2024-04-04,1,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,99.45,0,1
HB-065098,City Hotel,1,256,2025,March,13,24,2025-03-24,0,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.0,0,0
HB-097743,City Hotel,0,253,2024,September,38,19,2024-09-19,1,0,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,115.2,0,2
HB-072206,City Hotel,1,240,2025,July,30,23,2025-07-23,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-114354,City Hotel,0,4,2025,June,25,20,2025-06-20,0,1,1,0.0,0,SC,ESP,Online TA,GDS,0,0,0,E,E,0,No Deposit,195.0,,0,Transient,200.0,0,0
HB-057706,City Hotel,1,315,2024,September,40,30,2024-09-30,1,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,69,Transient,160.0,0,0
HB-007320,Resort Hotel,1,190,2024,August,31,2,2024-08-02,2,5,3,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,250.0,0,0
HB-022638,Resort Hotel,0,7,2024,March,13,28,2024-03-28,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,74.0,1,0
HB-003335,Resort Hotel,0,66,2023,December,49,5,2023-12-05,1,1,1,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,155.0,,0,Transient-Party,0.0,0,0
HB-002665,Resort Hotel,1,4,2023,October,43,24,2023-10-24,2,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,45.0,0,0
HB-095920,City Hotel,0,154,2024,August,34,24,2024-08-24,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,95.4,0,0
HB-104341,City Hotel,0,262,2025,January,2,9,2025-01-09,1,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,81.9,0,2
HB-027412,Resort Hotel,0,82,2024,August,34,22,2024-08-22,2,5,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,179.0,0,0
HB-013881,Resort Hotel,0,19,2025,March,11,13,2025-03-13,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,1,7,A,D,0,No Deposit,,82.0,0,Transient,35.0,0,0
HB-081980,City Hotel,1,115,2024,March,12,20,2024-03-20,2,0,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,41.0,,22,Transient,70.0,0,0
HB-119377,City Hotel,0,165,2025,August,35,29,2025-08-29,1,5,3,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,209.25,0,3
HB-026930,Resort Hotel,0,12,2024,August,33,13,2024-08-13,1,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,270.0,0,1
HB-046449,City Hotel,1,11,2024,January,1,2,2024-01-02,2,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient,83.58,0,0
HB-078781,City Hotel,0,0,2023,October,41,14,2023-10-14,0,2,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,146.0,0,2
HB-015415,Resort Hotel,1,159,2023,August,31,2,2023-08-02,2,4,2,1.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,D,D,0,No Deposit,15.0,,0,Transient,134.1,0,1
HB-014833,Resort Hotel,1,222,2023,September,37,15,2023-09-15,1,5,2,0.0,0,FB,PRT,Groups,Corporate,0,25,0,A,A,0,Non Refund,252.0,,0,Transient,49.95,0,0
HB-025325,Resort Hotel,0,105,2024,June,24,16,2024-06-16,2,4,2,0.0,0,Undefined,PRT,Direct,Direct,0,0,0,E,E,1,No Deposit,250.0,,0,Transient,181.9,0,0
HB-013419,Resort Hotel,1,91,2025,August,33,14,2025-08-14,1,4,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,221.0,0,0
HB-094808,City Hotel,0,183,2024,August,32,8,2024-08-08,1,1,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,105.3,0,1
HB-057722,City Hotel,1,219,2024,September,40,30,2024-09-30,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,120.0,0,0
HB-086079,City Hotel,0,70,2024,March,12,24,2024-03-24,0,3,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,42.0,,0,Transient,59.5,0,0
HB-066203,City Hotel,1,87,2025,April,16,15,2025-04-15,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,95.0,0,0
HB-104744,City Hotel,0,33,2025,January,3,14,2025-01-14,2,6,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,72.12,0,1
HB-042766,City Hotel,1,6,2023,September,36,10,2023-09-10,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,111.6,0,0
HB-106155,City Hotel,0,73,2025,February,8,18,2025-02-18,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.1,0,2
HB-074999,City Hotel,1,140,2023,July,27,7,2023-07-07,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,2
HB-052371,City Hotel,1,59,2024,June,23,4,2024-06-04,1,1,2,0.0,0,HB,CHN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,153.09,0,1
HB-080964,City Hotel,0,0,2023,November,48,29,2023-11-29,1,0,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,69.0,0,0
HB-040710,City Hotel,0,12,2023,August,31,5,2023-08-05,0,3,2,0.0,0,BB,RUS,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,38.0,0,Transient-Party,65.0,0,0
HB-075657,City Hotel,1,290,2023,August,31,3,2023-08-03,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-062712,City Hotel,1,12,2025,January,3,19,2025-01-19,0,3,1,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,92.0,0,2
HB-103692,City Hotel,0,104,2024,December,52,23,2024-12-23,2,5,2,0.0,0,BB,DNK,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,71.9,0,1
HB-046343,City Hotel,0,1,2023,December,52,30,2023-12-30,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,115.0,0,1
HB-115778,City Hotel,0,19,2025,July,28,7,2025-07-07,2,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,1
HB-116231,City Hotel,0,12,2025,July,29,15,2025-07-15,1,1,1,0.0,0,BB,MOZ,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,129.0,0,2
HB-020005,Resort Hotel,0,1,2024,February,6,10,2024-02-10,0,1,1,0.0,0,BB,PRT,Direct,Direct,1,0,1,A,D,0,No Deposit,,,0,Transient,4.0,0,0
HB-076839,City Hotel,0,0,2023,August,32,13,2023-08-13,0,2,2,0.0,0,BB,CHN,Direct,Direct,0,0,0,A,A,2,No Deposit,,,0,Transient,89.0,0,0
HB-036918,Resort Hotel,0,73,2025,May,22,30,2025-05-30,0,2,2,0.0,0,BB,PAK,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,100.0,0,1
HB-025090,Resort Hotel,0,150,2024,June,23,5,2024-06-05,4,6,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Transient,92.9,0,0
HB-061525,City Hotel,1,24,2024,December,50,15,2024-12-15,2,8,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,1
HB-064340,City Hotel,1,192,2025,March,10,6,2025-03-06,1,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.2,0,2
HB-052185,City Hotel,1,101,2024,June,22,1,2024-06-01,0,4,2,2.0,0,BB,ITA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,187.85,0,0
HB-088576,City Hotel,0,81,2024,May,19,7,2024-05-07,0,1,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,116.1,0,0
HB-092572,City Hotel,0,58,2024,July,28,8,2024-07-08,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,A,0,No Deposit,85.0,,0,Transient,87.3,0,0
HB-053617,City Hotel,1,156,2024,June,26,26,2024-06-26,1,0,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.3,0,0
HB-056486,City Hotel,1,426,2024,September,36,8,2024-09-08,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,59.0,0,0
HB-006671,Resort Hotel,0,2,2024,June,25,22,2024-06-22,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,F,0,No Deposit,,331.0,0,Transient,79.0,0,0
HB-015075,Resort Hotel,1,198,2023,August,34,22,2023-08-22,2,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,2,0,A,A,0,No Deposit,240.0,,0,Transient-Party,147.6,0,2
HB-116997,City Hotel,0,134,2025,July,30,23,2025-07-23,2,3,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,175.5,0,0
HB-096193,City Hotel,0,3,2024,August,34,24,2024-08-24,2,4,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,117.26,0,2
HB-103297,City Hotel,0,92,2024,December,49,6,2024-12-06,2,10,2,2.0,0,BB,AGO,Online TA,TA/TO,0,0,0,F,F,2,No Deposit,9.0,,0,Transient,147.9,0,4
HB-012202,Resort Hotel,1,277,2025,June,25,17,2025-06-17,4,6,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,98.4,0,0
HB-026881,Resort Hotel,0,42,2024,August,32,10,2024-08-10,0,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,243.0,0,1
HB-090620,City Hotel,0,118,2024,June,23,6,2024-06-06,1,2,1,0.0,0,BB,ESP,Offline TA/TO,Corporate,0,0,0,A,A,0,No Deposit,191.0,,0,Transient-Party,119.0,0,0
HB-025044,Resort Hotel,0,107,2024,June,23,3,2024-06-03,2,7,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,241.0,,0,Transient,58.52,0,1
HB-108850,City Hotel,0,72,2025,March,13,27,2025-03-27,2,5,2,0.0,0,BB,ITA,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,109.16,0,0
HB-095416,City Hotel,0,210,2024,August,33,18,2024-08-18,0,1,1,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,F,0,No Deposit,9.0,,0,Transient,96.3,0,0
HB-001490,Resort Hotel,0,27,2023,September,35,1,2023-09-01,0,3,2,1.0,0,HB,PRT,Direct,Direct,0,0,0,C,C,0,No Deposit,250.0,,0,Transient,153.0,0,2
HB-025353,Resort Hotel,0,168,2024,June,24,16,2024-06-16,2,5,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,6.0,,0,Transient,70.4,0,0
HB-089269,City Hotel,0,81,2024,May,20,16,2024-05-16,1,3,2,1.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.15,0,1
HB-068145,City Hotel,1,151,2025,May,20,13,2025-05-13,2,2,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,95.0,0,0
HB-058233,City Hotel,1,104,2024,October,41,9,2024-10-09,1,0,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-010558,Resort Hotel,1,94,2025,March,11,14,2025-03-14,2,7,1,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,55.0,0,0
HB-075809,City Hotel,1,330,2023,September,37,12,2023-09-12,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-095333,City Hotel,0,129,2024,August,33,15,2024-08-15,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.3,0,1
HB-011422,Resort Hotel,1,33,2025,May,19,6,2025-05-06,4,8,2,2.0,0,BB,SVK,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,127.83,0,1
HB-019796,Resort Hotel,0,3,2024,January,1,2,2024-01-02,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,330.0,,0,Transient,46.0,0,1
HB-101309,City Hotel,0,99,2024,November,45,7,2024-11-07,1,2,1,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,171.9,0,2
HB-098233,City Hotel,0,1,2024,September,38,22,2024-09-22,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,315.0,,0,Transient-Party,176.0,0,0
HB-108579,City Hotel,0,41,2025,March,13,29,2025-03-29,0,0,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,K,0,No Deposit,9.0,,0,Transient,0.0,0,0
HB-093309,City Hotel,0,41,2024,July,29,17,2024-07-17,2,1,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,8.0,,0,Transient,137.7,0,2
HB-089362,City Hotel,0,0,2024,December,51,21,2024-12-21,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,1,2,6,A,A,2,No Deposit,94.0,,0,Group,65.0,0,0
HB-066532,City Hotel,1,251,2025,April,17,21,2025-04-21,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.8,0,2
HB-041679,City Hotel,0,11,2023,August,34,21,2023-08-21,1,2,2,2.0,0,SC,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Contract,153.0,0,1
HB-041705,City Hotel,0,138,2023,August,34,22,2023-08-22,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-032158,Resort Hotel,0,108,2025,January,2,12,2025-01-12,2,5,1,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,49.7,1,1
HB-006345,Resort Hotel,1,37,2024,June,23,4,2024-06-04,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,122.14,0,0
HB-028119,Resort Hotel,0,280,2024,September,37,15,2024-09-15,2,4,2,0.0,0,HB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,125.83,0,0
HB-111582,City Hotel,0,34,2025,May,20,12,2025-05-12,0,1,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,180.0,0,2
HB-019747,Resort Hotel,0,112,2023,December,52,30,2023-12-30,0,3,2,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient-Party,245.33,0,0
HB-070765,City Hotel,1,116,2025,June,25,22,2025-06-22,0,3,2,1.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,186.3,0,1
HB-012019,Resort Hotel,1,307,2025,June,23,8,2025-06-08,4,10,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Contract,56.7,0,0
HB-067701,City Hotel,1,407,2025,May,19,6,2025-05-06,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-019752,Resort Hotel,0,112,2023,December,52,30,2023-12-30,0,3,1,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,D,D,1,No Deposit,,,0,Transient-Party,168.67,0,0
HB-064084,City Hotel,1,30,2025,March,9,1,2025-03-01,0,4,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,125.8,0,3
HB-096307,City Hotel,0,94,2025,June,23,2,2025-06-02,0,1,2,0.0,0,BB,PRT,Complementary,Direct,1,0,1,G,G,1,No Deposit,,45.0,0,Transient,0.0,1,4
HB-005032,Resort Hotel,0,229,2024,April,15,12,2024-04-12,2,6,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,D,D,1,No Deposit,250.0,,0,Transient,62.05,0,0
HB-052524,City Hotel,1,56,2024,June,23,8,2024-06-08,0,1,2,0.0,0,BB,PRT,Offline TA/TO,Corporate,0,0,0,A,A,0,No Deposit,191.0,,0,Transient-Party,120.0,0,0
HB-009654,Resort Hotel,1,57,2024,December,52,23,2024-12-23,2,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,56.0,0,4
HB-059674,City Hotel,1,23,2024,October,44,30,2024-10-30,2,5,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,89.64,0,1
HB-043262,City Hotel,0,56,2023,September,37,17,2023-09-17,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,20.0,,0,Transient-Party,82.0,0,0
HB-000431,Resort Hotel,0,57,2023,July,28,15,2023-07-15,0,2,2,0.0,0,FB,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,305.0,,0,Transient,107.0,0,0
HB-011542,Resort Hotel,1,158,2025,May,20,14,2025-05-14,4,7,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Transient,50.85,0,0
HB-095782,City Hotel,0,169,2024,August,34,22,2024-08-22,1,1,3,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,A,B,1,No Deposit,9.0,,0,Transient-Party,137.7,0,0
HB-024363,Resort Hotel,0,107,2024,May,18,5,2024-05-05,4,10,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Contract,74.18,0,2
HB-096169,City Hotel,0,216,2024,August,35,27,2024-08-27,2,1,3,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,128.7,0,2
HB-059259,City Hotel,1,200,2024,October,43,24,2024-10-24,1,3,2,0.0,0,BB,NLD,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,100.3,0,0
HB-017198,Resort Hotel,0,159,2023,September,38,23,2023-09-23,2,5,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,275.0,,0,Transient-Party,77.93,0,0
HB-072562,City Hotel,1,69,2025,July,31,31,2025-07-31,1,2,3,0.0,0,BB,QAT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,200.0,0,0
HB-006663,Resort Hotel,0,322,2024,June,25,22,2024-06-22,0,3,2,0.0,0,HB,POL,Groups,Direct,0,0,0,A,A,0,No Deposit,,,75,Transient-Party,92.0,0,0
HB-001691,Resort Hotel,1,159,2023,September,36,9,2023-09-09,2,7,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,82.0,0,1
HB-081203,City Hotel,0,1,2023,December,49,6,2023-12-06,1,0,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,2,No Deposit,,,0,Transient,100.0,0,0
HB-060327,City Hotel,1,277,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-067216,City Hotel,1,78,2025,April,18,29,2025-04-29,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient,90.0,0,0
HB-071645,City Hotel,1,226,2025,July,28,9,2025-07-09,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-005376,Resort Hotel,1,12,2024,April,17,27,2024-04-27,0,3,2,0.0,0,HB,PRT,Groups,Direct,0,0,0,A,A,1,No Deposit,385.0,,0,Transient-Party,85.33,0,0
HB-053320,City Hotel,0,290,2024,June,25,17,2024-06-17,1,2,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,3.0,,108,Transient-Party,65.0,0,1
HB-077340,City Hotel,0,65,2024,February,6,11,2024-02-11,2,4,2,0.0,0,BB,FRA,Direct,Direct,1,13,0,D,D,1,No Deposit,,,0,Transient,79.02,0,0
HB-004388,Resort Hotel,1,46,2024,March,11,11,2024-03-11,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,375.0,,0,Transient-Party,25.0,0,0
HB-027558,Resort Hotel,0,219,2024,August,35,29,2024-08-29,1,3,2,0.0,0,BB,USA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,93.0,1,0
HB-034368,Resort Hotel,0,181,2025,March,12,19,2025-03-19,2,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,29.0,0,0
HB-045608,City Hotel,1,79,2023,November,46,13,2023-11-13,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,60.0,,69,Transient,75.0,0,0
HB-101896,City Hotel,0,45,2024,November,47,18,2024-11-18,0,2,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,79.2,0,1
HB-078757,City Hotel,0,12,2023,October,41,12,2023-10-12,1,3,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,1,No Deposit,95.0,,0,Transient-Party,95.0,0,0
HB-095069,City Hotel,0,135,2024,August,33,13,2024-08-13,0,1,2,1.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.5,0,1
HB-015744,Resort Hotel,0,23,2023,July,30,26,2023-07-26,2,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,5.0,,0,Transient,131.2,0,1
HB-053220,City Hotel,1,350,2024,June,25,17,2024-06-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,140.0,0,0
HB-040733,City Hotel,0,83,2023,August,31,5,2023-08-05,1,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient-Party,76.5,1,1
HB-104288,City Hotel,0,75,2025,January,2,8,2025-01-08,2,1,1,0.0,0,BB,USA,Groups,TA/TO,0,0,0,D,D,0,No Deposit,330.0,,0,Transient-Party,67.0,0,2
HB-021128,Resort Hotel,0,6,2024,February,7,16,2024-02-16,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,62.0,0,Transient,30.0,0,0
HB-041065,City Hotel,0,1,2023,August,32,11,2023-08-11,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Contract,105.0,1,1
HB-038182,Resort Hotel,0,13,2025,July,28,8,2025-07-08,2,1,2,2.0,0,BB,LUX,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,214.0,1,2
HB-052258,City Hotel,1,330,2024,June,22,2,2024-06-02,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-111611,City Hotel,0,122,2025,May,19,11,2025-05-11,0,2,1,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,117.0,0,0
HB-109478,City Hotel,0,61,2025,April,15,8,2025-04-08,2,2,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,99.0,0,1
HB-016875,Resort Hotel,0,222,2023,September,37,14,2023-09-14,1,1,2,0.0,0,HB,FRA,Groups,TA/TO,0,0,0,A,F,0,No Deposit,68.0,,0,Transient-Party,80.0,0,0
HB-092519,City Hotel,0,54,2024,July,27,4,2024-07-04,1,3,2,0.0,0,HB,LUX,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,161.1,1,0
HB-023645,Resort Hotel,0,111,2024,April,17,28,2024-04-28,0,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient,58.2,1,1
HB-038621,Resort Hotel,0,136,2025,July,30,21,2025-07-21,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,175.0,0,1
HB-019147,Resort Hotel,0,27,2023,December,49,6,2023-12-06,2,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,54.67,0,1
HB-012329,Resort Hotel,1,176,2025,June,26,24,2025-06-24,2,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,241.0,,0,Transient,131.67,0,1
HB-086858,City Hotel,0,78,2024,April,14,6,2024-04-06,0,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient-Party,108.45,0,1
HB-046218,City Hotel,0,11,2023,December,52,26,2023-12-26,2,1,2,0.0,1,BB,ESP,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient-Party,92.58,0,1
HB-110728,City Hotel,0,107,2025,April,18,28,2025-04-28,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,0
HB-101085,City Hotel,0,48,2024,November,45,4,2024-11-04,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.2,0,2
HB-018752,Resort Hotel,0,15,2023,November,48,27,2023-11-27,0,2,2,1.0,0,HB,PRT,Corporate,Direct,0,0,0,D,D,1,No Deposit,,346.0,0,Transient-Party,80.0,1,1
HB-069481,City Hotel,1,174,2025,June,22,1,2025-06-01,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,0,Transient,100.0,0,0
HB-105791,City Hotel,0,11,2025,February,7,12,2025-02-12,2,1,2,0.0,0,BB,LUX,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,77.0,0,0
HB-033722,Resort Hotel,0,37,2025,February,8,23,2025-02-23,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,57.0,,0,Transient,34.0,0,1
HB-079771,City Hotel,0,11,2023,November,44,1,2023-11-01,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,87.0,0,1
HB-048976,City Hotel,1,79,2024,April,14,3,2024-04-03,2,4,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,95.2,0,0
HB-093346,City Hotel,0,9,2024,July,28,14,2024-07-14,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,160.29,0,1
HB-036604,Resort Hotel,0,6,2025,May,21,24,2025-05-24,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,240.0,,0,Transient,67.5,0,0
HB-025718,Resort Hotel,0,167,2024,June,26,28,2024-06-28,2,8,2,1.0,0,BB,IRL,Online TA,TA/TO,0,0,0,E,E,2,No Deposit,241.0,,0,Transient,81.08,0,2
HB-084259,City Hotel,0,6,2024,February,8,21,2024-02-21,1,0,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-036168,Resort Hotel,0,257,2025,May,19,9,2025-05-09,0,4,2,0.0,0,HB,GBR,Groups,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient-Party,101.0,0,0
HB-077349,City Hotel,1,190,2024,April,15,9,2024-04-09,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,1,13,1,A,A,0,No Deposit,,,31,Transient-Party,70.0,0,0
HB-024289,Resort Hotel,0,5,2024,May,19,11,2024-05-11,1,4,2,2.0,0,BB,GBR,Corporate,Corporate,0,0,0,C,C,1,No Deposit,,405.0,0,Transient-Party,0.0,1,0
HB-020474,Resort Hotel,0,22,2024,January,5,29,2024-01-29,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,39.0,1,0
HB-112827,City Hotel,0,246,2025,May,22,27,2025-05-27,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,128.0,0,1
HB-103112,City Hotel,0,0,2024,December,50,12,2024-12-12,1,0,2,0.0,0,BB,ESP,Direct,Direct,1,0,0,A,A,0,No Deposit,,,0,Transient,88.0,0,0
HB-030804,Resort Hotel,0,80,2024,December,49,2,2024-12-02,0,2,1,0.0,0,BB,IRL,Groups,TA/TO,0,0,0,D,D,3,No Deposit,253.0,,0,Transient-Party,44.8,0,0
HB-010607,Resort Hotel,1,205,2025,March,12,18,2025-03-18,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,37.8,0,1
HB-056403,City Hotel,1,23,2024,September,36,5,2024-09-05,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,93.94,0,0
HB-110379,City Hotel,0,5,2025,April,17,26,2025-04-26,0,1,1,0.0,0,BB,ESP,Direct,Direct,0,0,0,E,E,1,No Deposit,14.0,,0,Transient,215.0,0,0
HB-065936,City Hotel,1,83,2025,April,15,10,2025-04-10,1,3,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,164.25,0,0
HB-097328,City Hotel,0,346,2024,September,37,13,2024-09-13,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-044602,City Hotel,0,210,2023,October,40,8,2023-10-08,1,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,12.0,,0,Transient-Party,72.75,0,0
HB-046889,City Hotel,1,20,2024,January,4,24,2024-01-24,2,2,1,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,67.5,0,0
HB-009095,Resort Hotel,1,117,2024,October,43,27,2024-10-27,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient-Party,55.43,0,0
HB-075638,City Hotel,1,281,2023,July,30,25,2023-07-25,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-058197,City Hotel,1,338,2024,October,41,7,2024-10-07,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,68,Transient-Party,80.0,0,0
HB-046033,City Hotel,1,198,2023,December,49,5,2023-12-05,2,1,2,0.0,0,HB,ESP,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,90.0,0,0
HB-088697,City Hotel,0,1,2024,May,19,10,2024-05-10,0,1,2,0.0,0,BB,DEU,Online TA,Corporate,0,0,0,A,A,0,No Deposit,,47.0,0,Transient,83.0,0,0
HB-077168,City Hotel,1,343,2023,September,39,25,2023-09-25,2,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,1,Non Refund,1.0,,0,Transient,170.0,0,0
HB-104470,City Hotel,0,3,2025,January,3,13,2025-01-13,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,108.0,0,2
HB-073102,City Hotel,1,176,2025,August,33,14,2025-08-14,1,5,2,1.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,144.6,0,0
HB-047595,City Hotel,1,43,2024,February,9,28,2024-02-28,2,0,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,90.9,0,0
HB-079876,City Hotel,1,32,2023,November,47,20,2023-11-20,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,119.0,,0,Transient-Party,73.0,0,0
HB-047418,City Hotel,1,31,2024,February,8,20,2024-02-20,2,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,71.1,0,0
HB-068399,City Hotel,1,297,2025,May,20,16,2025-05-16,0,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.8,0,2
HB-101664,City Hotel,0,46,2024,November,46,13,2024-11-13,2,1,1,0.0,0,BB,JPN,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,79.2,0,0
HB-104319,City Hotel,0,3,2025,January,2,7,2025-01-07,2,2,2,0.0,1,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.69,1,3
HB-045871,City Hotel,0,98,2023,November,47,23,2023-11-23,1,3,1,0.0,0,BB,CZE,Groups,TA/TO,0,0,0,A,A,1,No Deposit,37.0,,0,Transient-Party,70.0,0,0
HB-053496,City Hotel,1,351,2024,June,25,23,2024-06-23,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,59.0,0,0
HB-088785,City Hotel,0,7,2025,June,23,7,2025-06-07,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,22,A,A,0,No Deposit,,219.0,0,Transient,142.65,1,2
HB-006200,Resort Hotel,0,225,2024,May,22,28,2024-05-28,1,1,1,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,E,1,No Deposit,298.0,,0,Transient-Party,54.5,0,0
HB-005499,Resort Hotel,0,197,2024,April,18,30,2024-04-30,1,1,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,85.0,0,0
HB-078815,City Hotel,0,29,2023,October,41,13,2023-10-13,0,4,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,98.98,0,2
HB-023520,Resort Hotel,0,109,2024,April,17,24,2024-04-24,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,C,1,No Deposit,240.0,,0,Transient,52.2,0,1
HB-114482,City Hotel,0,66,2025,June,25,20,2025-06-20,0,3,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,170.0,0,1
HB-075052,City Hotel,1,271,2023,July,28,15,2023-07-15,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-033135,Resort Hotel,0,8,2025,February,7,15,2025-02-15,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,80.0,0,1
HB-005609,Resort Hotel,0,189,2024,May,18,5,2024-05-05,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,64.0,1,2
HB-041026,City Hotel,0,0,2023,August,32,11,2023-08-11,0,1,2,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,A,0,No Deposit,,45.0,0,Transient,0.0,0,0
HB-038270,Resort Hotel,0,182,2025,July,27,5,2025-07-05,2,6,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,147.0,,0,Transient,103.05,0,0
HB-084394,City Hotel,0,22,2024,February,8,22,2024-02-22,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-118677,City Hotel,0,185,2025,August,34,20,2025-08-20,2,2,1,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,0
HB-102226,City Hotel,0,215,2024,November,47,21,2024-11-21,1,2,1,0.0,0,BB,MLT,Groups,Corporate,0,0,0,A,A,0,No Deposit,,233.0,0,Transient,75.0,0,0
HB-039207,Resort Hotel,0,208,2025,August,32,8,2025-08-08,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,G,3,No Deposit,240.0,,0,Transient,206.0,0,2
HB-069077,City Hotel,1,167,2025,May,21,25,2025-05-25,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,0,Transient,115.0,0,0
HB-012041,Resort Hotel,1,37,2025,June,24,10,2025-06-10,2,2,2,2.0,0,HB,PAK,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,228.0,0,1
HB-071261,City Hotel,1,157,2025,June,27,30,2025-06-30,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,119.4,0,0
HB-012389,Resort Hotel,1,165,2025,June,26,26,2025-06-26,2,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,140.0,0,0
HB-002993,Resort Hotel,1,39,2023,November,45,10,2023-11-10,0,5,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,281.0,,0,Transient-Party,40.0,0,0
HB-009210,Resort Hotel,1,292,2024,November,44,3,2024-11-03,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,368.0,,0,Transient-Party,38.0,0,0
HB-047716,City Hotel,1,0,2024,March,9,1,2024-03-01,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,60.0,0,0
HB-082806,City Hotel,1,68,2024,February,7,17,2024-02-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,37.0,,0,Transient,75.0,0,0
HB-061356,City Hotel,1,86,2024,December,49,8,2024-12-08,0,3,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,122.0,0,0
HB-068211,City Hotel,1,103,2025,May,20,15,2025-05-15,1,2,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.0,0,0
HB-034095,Resort Hotel,0,0,2025,March,11,11,2025-03-11,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,240.0,,0,Transient,95.0,0,2
HB-063740,City Hotel,1,50,2025,February,8,19,2025-02-19,2,5,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,149.6,0,0
HB-104942,City Hotel,0,21,2025,January,4,22,2025-01-22,2,2,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,67.58,0,1
HB-072088,City Hotel,1,193,2025,July,29,20,2025-07-20,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.9,0,0
HB-019888,Resort Hotel,0,5,2024,January,1,4,2024-01-04,1,3,1,0.0,0,HB,PRT,Groups,Corporate,0,0,0,A,A,0,No Deposit,,174.0,0,Transient-Party,61.0,0,0
HB-047420,City Hotel,1,49,2024,February,8,20,2024-02-20,2,1,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,67.5,0,0
HB-106593,City Hotel,0,17,2025,February,9,24,2025-02-24,2,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,102.43,0,3
HB-072700,City Hotel,1,106,2025,August,31,3,2025-08-03,0,3,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.0,0,1
HB-017653,Resort Hotel,0,287,2023,October,41,15,2023-10-15,1,3,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,0,No Deposit,,223.0,0,Transient-Party,46.5,0,0
HB-057372,City Hotel,1,20,2024,September,39,24,2024-09-24,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,86.0,,0,Transient,117.2,0,0
HB-003257,Resort Hotel,0,15,2023,November,48,27,2023-11-27,0,2,2,0.0,0,BB,PRT,Complementary,Corporate,0,0,0,A,A,1,No Deposit,,,0,Transient,0.0,0,0
HB-113443,City Hotel,0,2,2025,May,22,31,2025-05-31,2,6,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,94.0,,0,Transient,65.0,0,0
HB-086808,City Hotel,0,30,2024,April,14,6,2024-04-06,0,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,11.0,,0,Transient,110.8,0,0
HB-115270,City Hotel,0,128,2025,July,27,1,2025-07-01,2,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,0
HB-062272,City Hotel,1,10,2025,January,2,6,2025-01-06,2,2,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,71.19,0,0
HB-094368,City Hotel,0,191,2024,August,31,1,2024-08-01,1,2,3,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,22.0,,0,Transient,96.9,0,0
HB-059699,City Hotel,1,166,2024,November,44,1,2024-11-01,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,110.0,0,0
HB-061252,City Hotel,1,88,2024,December,49,6,2024-12-06,0,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,0
HB-073483,City Hotel,1,121,2025,August,34,23,2025-08-23,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,155.0,0,0
HB-004684,Resort Hotel,1,20,2024,March,13,28,2024-03-28,1,1,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,43.0,0,0
HB-001273,Resort Hotel,0,46,2023,August,34,22,2023-08-22,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,261.0,,0,Transient,149.0,0,1
HB-076862,City Hotel,1,239,2023,October,42,17,2023-10-17,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-056197,City Hotel,1,83,2024,September,35,1,2024-09-01,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,112.8,0,0
HB-096214,City Hotel,0,207,2024,August,34,20,2024-08-20,4,6,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient-Party,72.25,0,0
HB-116898,City Hotel,0,20,2025,July,30,25,2025-07-25,0,2,2,0.0,0,BB,CHN,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,150.0,0,1
HB-024840,Resort Hotel,0,14,2024,June,22,1,2024-06-01,0,4,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,109.0,0,1
HB-028701,Resort Hotel,0,11,2024,October,41,9,2024-10-09,1,0,1,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,1,No Deposit,,405.0,0,Transient-Party,50.0,0,0
HB-050495,City Hotel,1,437,2024,May,18,2,2024-05-02,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-041311,City Hotel,1,39,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,101.5,0,0
HB-014402,Resort Hotel,0,110,2023,August,32,8,2023-08-08,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,15.0,,0,Transient,107.0,0,1
HB-052938,City Hotel,1,71,2024,June,24,14,2024-06-14,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,120.0,0,0
HB-040137,City Hotel,0,3,2023,July,28,11,2023-07-11,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,75.0,0,0
HB-009604,Resort Hotel,1,21,2024,December,51,19,2024-12-19,1,0,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-010827,Resort Hotel,1,1,2025,April,15,7,2025-04-07,0,2,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,,0,Transient,110.0,0,0
HB-095768,City Hotel,0,48,2024,August,34,20,2024-08-20,2,2,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,168.3,0,0
HB-094374,City Hotel,0,257,2024,July,31,31,2024-07-31,2,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,90.95,0,0
HB-062532,City Hotel,1,38,2025,January,3,14,2025-01-14,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,Non Refund,,67.0,0,Transient,75.0,0,0
HB-105642,City Hotel,0,14,2025,February,7,10,2025-02-10,1,2,2,0.0,0,SC,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,2
HB-020989,Resort Hotel,0,10,2024,February,6,11,2024-02-11,1,3,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,41.0,0,2
HB-053498,City Hotel,1,23,2024,June,25,23,2024-06-23,0,1,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.0,0,0
HB-083402,City Hotel,0,13,2024,January,3,21,2024-01-21,2,8,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,75.6,0,0
HB-018217,Resort Hotel,0,37,2023,November,45,8,2023-11-08,2,5,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,E,E,1,No Deposit,185.0,281.0,0,Transient-Party,52.2,0,0
HB-066301,City Hotel,1,16,2025,April,16,16,2025-04-16,2,1,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,115.0,0,2
HB-068804,City Hotel,1,20,2025,May,21,20,2025-05-20,2,2,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,137.5,0,1
HB-054895,City Hotel,1,28,2024,July,31,29,2024-07-29,0,1,2,1.0,0,BB,JPN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.0,0,0
HB-092716,City Hotel,0,176,2024,July,28,8,2024-07-08,1,2,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient-Party,85.5,0,0
HB-072491,City Hotel,1,490,2025,July,31,29,2025-07-29,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-087720,City Hotel,0,5,2024,April,17,22,2024-04-22,1,2,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,201.0,0,2
HB-017733,Resort Hotel,0,287,2023,October,41,15,2023-10-15,1,3,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,A,0,No Deposit,,223.0,0,Transient-Party,44.5,0,0
HB-090437,City Hotel,0,107,2024,June,23,3,2024-06-03,1,2,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,90.67,0,0
HB-068944,City Hotel,1,160,2025,May,21,23,2025-05-23,0,3,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,162.0,0,2
HB-039359,Resort Hotel,0,0,2025,August,33,15,2025-08-15,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,161.1,0,1
HB-077254,City Hotel,1,6,2023,September,38,20,2023-09-20,2,0,2,0.0,0,BB,PRT,Corporate,Corporate,0,1,0,A,A,0,Non Refund,78.0,,0,Transient,100.0,0,0
HB-065064,City Hotel,1,187,2025,March,12,23,2025-03-23,0,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.6,0,1
HB-072631,City Hotel,1,285,2025,August,31,1,2025-08-01,0,5,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,1
HB-045844,City Hotel,1,98,2023,November,47,23,2023-11-23,1,2,1,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,84.0,0,0
HB-064444,City Hotel,1,303,2025,March,10,9,2025-03-09,1,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,90.1,0,2
HB-022175,Resort Hotel,0,49,2024,March,11,15,2024-03-15,0,5,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,171.0,,0,Transient,38.0,0,0
HB-056343,City Hotel,1,420,2024,September,36,3,2024-09-03,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,35.0,,0,Transient,75.0,0,0
HB-064182,City Hotel,1,28,2025,March,9,2,2025-03-02,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,95.0,0,0
HB-114121,City Hotel,0,175,2025,June,24,14,2025-06-14,0,3,2,0.0,0,HB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,171.0,0,1
HB-028638,Resort Hotel,0,188,2024,September,39,25,2024-09-25,4,10,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,F,F,2,No Deposit,250.0,,0,Transient,114.71,0,0
HB-032867,Resort Hotel,0,10,2025,February,6,6,2025-02-06,1,1,2,0.0,0,Undefined,PRT,Groups,Corporate,0,0,0,A,A,0,No Deposit,,507.0,0,Transient-Party,90.0,0,0
HB-082171,City Hotel,1,99,2024,February,8,19,2024-02-19,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,1,0,A,A,0,No Deposit,,67.0,0,Transient-Party,80.0,0,0
HB-079121,City Hotel,0,6,2023,October,42,20,2023-10-20,0,2,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Contract,136.0,0,1
HB-020266,Resort Hotel,0,7,2025,March,10,8,2025-03-08,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,1,0,3,A,A,0,No Deposit,240.0,,0,Transient-Party,55.0,1,2
HB-041677,City Hotel,0,3,2023,August,34,21,2023-08-21,1,2,1,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,75.0,0,1
HB-068726,City Hotel,1,420,2025,May,21,20,2025-05-20,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,B,1,Non Refund,229.0,,0,Transient,90.0,0,0
HB-103040,City Hotel,0,25,2024,December,50,9,2024-12-09,0,2,2,2.0,0,BB,PRT,Direct,Direct,0,0,0,D,G,0,No Deposit,,,0,Transient,104.0,0,2
HB-097437,City Hotel,0,13,2024,September,37,15,2024-09-15,0,1,2,0.0,0,SC,FRA,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,233.0,0,Transient-Party,100.0,0,1
HB-028987,Resort Hotel,0,29,2024,October,42,15,2024-10-15,2,1,2,0.0,0,BB,CHE,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,42.0,0,0
HB-054857,City Hotel,1,386,2024,July,30,28,2024-07-28,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-026595,Resort Hotel,0,151,2024,August,31,1,2024-08-01,1,3,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,96.0,,0,Transient,115.2,0,0
HB-104990,City Hotel,0,75,2025,January,4,22,2025-01-22,2,3,2,0.0,0,BB,PAN,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,94.8,0,0
HB-047523,City Hotel,1,44,2024,February,8,25,2024-02-25,7,18,2,0.0,0,BB,AGO,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,86.39,0,0
HB-106078,City Hotel,0,33,2025,February,7,13,2025-02-13,2,5,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,132.13,1,2
HB-025588,Resort Hotel,0,10,2024,July,27,2,2024-07-02,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,F,1,No Deposit,240.0,,0,Transient,159.0,0,1
HB-056141,City Hotel,1,165,2024,August,35,30,2024-08-30,0,3,3,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,138.9,0,0
HB-025661,Resort Hotel,0,0,2024,July,27,5,2024-07-05,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,129.0,0,0
HB-112812,City Hotel,0,145,2025,May,22,26,2025-05-26,1,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,112.0,0,0
HB-084014,City Hotel,0,99,2024,February,7,14,2024-02-14,2,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient,79.5,0,2
HB-034673,Resort Hotel,0,90,2025,March,13,27,2025-03-27,1,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,59.8,1,2
HB-053568,City Hotel,1,234,2024,June,26,24,2024-06-24,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,65.0,0,0
HB-022570,Resort Hotel,0,43,2024,March,13,26,2024-03-26,2,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,79.67,1,2
HB-035914,Resort Hotel,0,220,2025,May,19,5,2025-05-05,0,1,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,54.0,0,1
HB-076997,City Hotel,0,0,2023,August,34,25,2023-08-25,0,1,2,1.0,0,SC,ESP,Online TA,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,97.0,0,0
HB-111992,City Hotel,0,31,2025,May,20,14,2025-05-14,2,3,1,0.0,0,BB,PRT,Groups,Corporate,0,0,0,A,A,0,No Deposit,459.0,,0,Transient-Party,130.0,0,0
HB-109459,City Hotel,0,96,2025,April,15,9,2025-04-09,2,1,2,0.0,0,BB,LUX,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,89.1,0,0
HB-030653,Resort Hotel,0,21,2024,November,48,28,2024-11-28,1,1,1,0.0,0,BB,POL,Groups,TA/TO,0,0,0,E,E,0,No Deposit,,,0,Transient-Party,45.0,0,0
HB-089664,City Hotel,0,1,2024,May,21,23,2024-05-23,1,0,2,0.0,0,BB,LTU,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,149.0,0,0
HB-103703,City Hotel,0,2,2024,December,52,28,2024-12-28,0,2,2,1.0,0,BB,KOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,142.0,0,2
HB-073097,City Hotel,1,274,2025,August,33,14,2025-08-14,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,1
HB-030200,Resort Hotel,0,0,2024,November,46,15,2024-11-15,0,1,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,G,G,0,No Deposit,,,0,Transient,111.0,1,0
HB-048082,City Hotel,0,72,2024,March,11,16,2024-03-16,0,3,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,81.3,0,1
HB-061456,City Hotel,1,30,2024,December,50,12,2024-12-12,1,0,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,3
HB-112488,City Hotel,0,24,2025,May,21,21,2025-05-21,2,2,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,27.0,,0,Transient,119.9,0,0
HB-022190,Resort Hotel,0,123,2024,March,12,19,2024-03-19,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,98.0,0,1
HB-006078,Resort Hotel,0,223,2024,May,21,24,2024-05-24,1,5,2,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,A,3,No Deposit,,223.0,0,Transient-Party,66.0,0,0
HB-086614,City Hotel,0,55,2024,April,14,6,2024-04-06,0,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,104.0,0,0
HB-027260,Resort Hotel,0,72,2024,August,33,16,2024-08-16,2,6,2,2.0,0,HB,ESP,Direct,Direct,0,0,0,C,C,3,No Deposit,250.0,,0,Transient,261.25,0,2
HB-083644,City Hotel,0,17,2024,February,6,7,2024-02-07,2,0,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,81.07,0,1
HB-076098,City Hotel,1,364,2023,October,42,16,2023-10-16,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-058484,City Hotel,1,36,2024,October,41,13,2024-10-13,0,1,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,102.6,0,0
HB-009078,Resort Hotel,1,0,2024,October,43,27,2024-10-27,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,75.0,0,0
HB-064776,City Hotel,1,615,2025,March,11,16,2025-03-16,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-042674,City Hotel,0,12,2023,September,36,9,2023-09-09,0,2,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,80.85,0,2
HB-083311,City Hotel,0,11,2024,January,4,26,2024-01-26,0,2,2,0.0,0,BB,TWN,Direct,Direct,0,0,0,A,D,1,No Deposit,14.0,,0,Transient,91.0,0,2
HB-071860,City Hotel,1,157,2025,July,29,14,2025-07-14,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,80.1,0,1
HB-021112,Resort Hotel,0,7,2024,February,7,17,2024-02-17,0,2,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient-Party,43.0,0,1
HB-007395,Resort Hotel,1,290,2024,August,32,7,2024-08-07,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,157.5,0,2
HB-000332,Resort Hotel,0,34,2023,July,28,12,2023-07-12,2,0,2,2.0,0,BB,BEL,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,193.0,0,1
HB-033902,Resort Hotel,0,7,2025,March,9,2,2025-03-02,1,3,2,0.0,0,BB,NLD,Groups,Corporate,0,0,0,D,E,0,No Deposit,,223.0,0,Transient-Party,54.0,1,0
HB-036594,Resort Hotel,0,13,2025,May,21,24,2025-05-24,0,1,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,60.0,0,1
HB-009930,Resort Hotel,1,281,2025,January,4,26,2025-01-26,2,5,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,37.8,0,0
HB-029081,Resort Hotel,0,138,2024,October,42,19,2024-10-19,0,1,2,0.0,0,BB,AUT,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,251.0,,0,Transient,59.0,0,0
HB-039670,Resort Hotel,0,169,2025,August,34,20,2025-08-20,2,3,1,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,240.0,,0,Transient,248.0,0,3
HB-110725,City Hotel,0,131,2025,April,18,28,2025-04-28,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.5,0,2
HB-039559,Resort Hotel,0,256,2025,August,32,7,2025-08-07,4,10,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,126.41,0,1
HB-026803,Resort Hotel,0,10,2024,August,32,5,2024-08-05,2,4,1,1.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,242.33,0,1
HB-031151,Resort Hotel,0,18,2024,December,50,15,2024-12-15,0,1,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,43.0,0,1
HB-070657,City Hotel,1,451,2025,June,25,20,2025-06-20,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-085426,City Hotel,0,46,2024,March,10,10,2024-03-10,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,77.35,0,2
HB-012900,Resort Hotel,1,159,2025,July,30,22,2025-07-22,2,5,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,212.0,0,0
HB-068797,City Hotel,1,25,2025,May,21,20,2025-05-20,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,90.0,0,0
HB-114908,City Hotel,0,0,2025,June,26,27,2025-06-27,0,1,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,100.3,0,1
HB-030545,Resort Hotel,0,151,2024,November,47,19,2024-11-19,2,5,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,314.0,,0,Transient,26.64,0,0
HB-051166,City Hotel,0,136,2024,May,20,14,2024-05-14,2,2,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,113.05,0,1
HB-022251,Resort Hotel,0,12,2024,March,12,19,2024-03-19,2,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,26.0,,0,Transient,53.2,0,0
HB-047567,City Hotel,1,66,2024,February,9,27,2024-02-27,2,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient,65.66,0,0
HB-040091,City Hotel,1,71,2023,July,27,5,2023-07-05,2,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,11.0,,0,Transient,55.8,0,0
HB-069250,City Hotel,1,121,2025,May,22,28,2025-05-28,2,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,148.5,0,1
HB-002163,Resort Hotel,0,51,2023,October,40,3,2023-10-03,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,241.0,,0,Transient,83.05,0,2
HB-040880,City Hotel,0,16,2023,August,32,8,2023-08-08,2,2,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-099181,City Hotel,0,28,2024,October,41,8,2024-10-08,1,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,E,G,0,No Deposit,86.0,,0,Transient,171.87,0,0
HB-108833,City Hotel,0,53,2025,March,13,30,2025-03-30,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,91.47,0,1
HB-061195,City Hotel,1,5,2024,December,49,4,2024-12-04,1,0,2,2.0,0,BB,CHN,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,156.6,0,0
HB-029520,Resort Hotel,0,17,2024,October,44,28,2024-10-28,0,2,2,0.0,0,BB,CN,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,44.0,1,0
HB-014836,Resort Hotel,1,222,2023,September,37,15,2023-09-15,1,5,2,0.0,0,FB,PRT,Groups,Corporate,0,25,0,A,A,0,Non Refund,252.0,,0,Transient,49.95,0,0
HB-030402,Resort Hotel,0,0,2024,November,47,18,2024-11-18,1,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,H,H,0,No Deposit,,,0,Transient,105.0,0,0
HB-046456,City Hotel,1,150,2024,January,1,2,2024-01-02,2,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,91,Transient,101.0,0,0
HB-051610,City Hotel,1,97,2024,May,21,22,2024-05-22,2,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient,112.01,0,0
HB-018912,Resort Hotel,0,1,2024,March,11,15,2024-03-15,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,1,0,2,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-081579,City Hotel,1,222,2024,July,27,6,2024-07-06,1,4,2,0.0,0,SC,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Contract,90.95,0,1
HB-026111,Resort Hotel,0,2,2024,July,29,18,2024-07-18,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,176.0,0,0
HB-086847,City Hotel,0,115,2024,April,15,8,2024-04-08,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,2,No Deposit,1.0,,34,Transient-Party,57.5,0,1
HB-071889,City Hotel,1,315,2025,July,29,15,2025-07-15,1,1,1,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,0
HB-096386,City Hotel,0,40,2024,August,35,30,2024-08-30,0,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,80.32,0,1
HB-093565,City Hotel,0,292,2024,July,29,21,2024-07-21,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,0
HB-015774,Resort Hotel,0,39,2023,July,30,26,2023-07-26,2,5,2,0.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,196.0,,0,Transient,133.0,0,1
HB-006715,Resort Hotel,1,90,2024,June,26,26,2024-06-26,2,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,123.33,0,1
HB-003284,Resort Hotel,1,20,2023,December,48,3,2023-12-03,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,46.4,0,1
HB-098071,City Hotel,0,296,2024,September,38,21,2024-09-21,0,4,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,26.0,,0,Transient-Party,117.0,0,1
HB-025647,Resort Hotel,0,158,2024,June,26,28,2024-06-28,2,5,2,0.0,0,BB,CHE,Direct,Direct,0,0,0,E,F,0,No Deposit,,,0,Transient,131.5,1,1
HB-054887,City Hotel,1,227,2024,July,30,28,2024-07-28,2,4,2,3.0,0,BB,FRA,Direct,Direct,0,0,0,B,B,2,No Deposit,14.0,,0,Transient,79.26,0,0
HB-029725,Resort Hotel,0,89,2024,October,44,30,2024-10-30,2,3,1,0.0,0,HB,GBR,Direct,Direct,0,0,0,D,D,1,No Deposit,250.0,,0,Transient,61.8,0,0
HB-014271,Resort Hotel,0,19,2025,April,16,17,2025-04-17,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,1,12,A,E,0,No Deposit,,292.0,0,Transient,48.5,1,1
HB-027316,Resort Hotel,0,204,2024,August,33,12,2024-08-12,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,2.0,,0,Contract,91.96,0,1
HB-084214,City Hotel,0,41,2024,February,7,18,2024-02-18,0,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient-Party,72.37,0,0
HB-107179,City Hotel,0,64,2025,March,10,5,2025-03-05,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,7.0,,0,Transient,70.69,0,2
HB-048287,City Hotel,1,40,2024,March,12,20,2024-03-20,2,0,3,0.0,0,BB,CHL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,131.4,0,0
HB-053958,City Hotel,1,39,2024,July,27,3,2024-07-03,2,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.9,0,0
HB-074179,City Hotel,1,356,2023,October,40,8,2023-10-08,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-046789,City Hotel,1,151,2024,January,3,19,2024-01-19,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,19.0,,63,Transient-Party,80.0,0,0
HB-109672,City Hotel,0,7,2025,April,15,13,2025-04-13,0,2,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,2
HB-060058,City Hotel,1,95,2024,November,45,5,2024-11-05,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,75.0,0,0
HB-059415,City Hotel,1,199,2024,October,44,28,2024-10-28,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,29.0,,0,Transient-Party,95.0,0,0
HB-027336,Resort Hotel,0,22,2024,August,34,20,2024-08-20,2,5,2,0.0,0,FB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,247.0,0,1
HB-043256,City Hotel,0,56,2023,September,37,17,2023-09-17,0,2,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,20.0,,0,Transient-Party,82.0,0,0
HB-097961,City Hotel,0,1,2024,September,38,22,2024-09-22,0,1,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,132.0,,0,Transient,107.0,0,0
HB-097158,City Hotel,0,62,2024,September,37,11,2024-09-11,2,0,2,1.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,152.1,0,1
HB-075489,City Hotel,1,341,2023,September,38,23,2023-09-23,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-107835,City Hotel,0,56,2025,March,12,18,2025-03-18,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,88.2,0,1
HB-065174,City Hotel,1,75,2025,March,13,26,2025-03-26,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,296.0,,0,Transient-Party,72.0,0,0
HB-020218,Resort Hotel,0,1,2024,January,3,18,2024-01-18,1,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-079701,City Hotel,0,86,2024,June,26,26,2024-06-26,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,7,A,A,0,No Deposit,,40.0,0,Transient-Party,65.0,0,0
HB-009082,Resort Hotel,1,142,2024,October,43,27,2024-10-27,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,78.0,0,0
HB-035450,Resort Hotel,0,12,2025,April,16,18,2025-04-18,0,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,47.5,0,0
HB-072923,City Hotel,1,224,2025,August,32,9,2025-08-09,2,6,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,148.5,0,1
HB-079135,City Hotel,0,12,2023,October,42,20,2023-10-20,0,2,1,0.0,0,BB,SWE,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,105.0,0,Transient-Party,130.0,0,0
HB-046409,City Hotel,1,148,2023,December,52,31,2023-12-31,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,98,Transient,77.5,0,0
HB-003982,Resort Hotel,1,64,2024,February,6,11,2024-02-11,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,15.0,,0,Transient,29.0,0,0
HB-039518,Resort Hotel,0,24,2025,August,33,17,2025-08-17,0,3,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,G,G,1,No Deposit,240.0,,0,Transient,392.0,1,1
HB-071712,City Hotel,1,224,2025,July,28,10,2025-07-10,2,5,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,0
HB-037256,Resort Hotel,0,3,2025,June,24,9,2025-06-09,0,2,2,2.0,0,BB,ROU,Direct,Direct,0,0,0,C,C,0,No Deposit,250.0,,0,Transient,182.0,1,0
HB-043648,City Hotel,0,26,2023,September,38,21,2023-09-21,1,3,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,124.0,0,0
HB-071756,City Hotel,1,320,2025,July,28,11,2025-07-11,2,5,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,0
HB-083583,City Hotel,0,12,2024,February,6,5,2024-02-05,1,2,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,130.0,0,1
HB-086514,City Hotel,0,62,2024,April,14,1,2024-04-01,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,106.2,0,0
HB-048662,City Hotel,1,92,2024,March,13,26,2024-03-26,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,170.0,,0,Transient,100.0,0,0
HB-090926,City Hotel,0,17,2024,June,24,12,2024-06-12,1,0,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,85.47,0,1
HB-107152,City Hotel,0,49,2025,March,10,3,2025-03-03,2,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient,68.0,0,0
HB-107638,City Hotel,0,65,2025,March,11,12,2025-03-12,2,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,73.0,0,1
HB-073473,City Hotel,1,67,2025,August,34,23,2025-08-23,0,2,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,169.0,0,1
HB-035265,Resort Hotel,0,10,2025,April,16,15,2025-04-15,1,1,1,1.0,0,HB,PRT,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,241.0,,0,Transient,158.4,0,1
HB-021262,Resort Hotel,0,39,2024,February,8,23,2024-02-23,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,1,No Deposit,250.0,,0,Transient,38.0,0,0
HB-065799,City Hotel,1,104,2025,April,15,8,2025-04-08,2,3,2,0.0,0,BB,DNK,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.5,0,2
HB-045086,City Hotel,1,102,2023,October,42,16,2023-10-16,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-061022,City Hotel,1,42,2024,November,48,29,2024-11-29,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,348.0,0,Transient,90.0,0,0
HB-012570,Resort Hotel,1,8,2025,July,27,5,2025-07-05,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,355.0,0,Transient,135.0,0,0
HB-074363,City Hotel,1,276,2023,July,29,20,2023-07-20,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Contract,62.0,0,0
HB-085531,City Hotel,0,35,2024,March,11,12,2024-03-12,2,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,16.0,,0,Transient,63.0,0,0
HB-041377,City Hotel,0,145,2023,August,33,15,2023-08-15,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,76.5,0,1
HB-062261,City Hotel,1,91,2025,January,2,6,2025-01-06,1,2,2,2.0,0,BB,DEU,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,131.1,0,0
HB-000835,Resort Hotel,1,18,2023,July,31,31,2023-07-31,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,173.0,0,3
HB-044265,City Hotel,0,164,2023,October,40,2,2023-10-02,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,19.0,,0,Transient-Party,100.0,0,0
HB-073387,City Hotel,1,73,2025,August,34,20,2025-08-20,1,0,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,148.5,0,0
HB-012007,Resort Hotel,1,304,2025,June,23,8,2025-06-08,2,3,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,1,Non Refund,298.0,,0,Transient,94.0,0,0
HB-109896,City Hotel,0,146,2025,April,16,16,2025-04-16,2,1,2,0.0,0,BB,MEX,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,138.0,,0,Transient,99.0,0,0
HB-037278,Resort Hotel,0,23,2025,June,24,9,2025-06-09,1,2,1,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,156.12,1,1
HB-016736,Resort Hotel,0,266,2024,June,24,13,2024-06-13,3,7,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,1,0,1,A,A,1,No Deposit,40.0,,0,Contract,53.85,0,0
HB-048752,City Hotel,1,68,2024,March,13,29,2024-03-29,4,11,1,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.22,0,0
HB-112875,City Hotel,0,50,2025,May,22,26,2025-05-26,2,2,2,0.0,0,SC,DEU,Direct,Direct,0,0,0,A,D,1,No Deposit,14.0,,0,Transient,180.0,0,2
HB-086918,City Hotel,0,159,2024,April,15,9,2024-04-09,1,1,3,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,3.0,,0,Transient-Party,100.0,0,1
HB-042078,City Hotel,0,6,2023,August,35,30,2023-08-30,2,3,2,1.0,0,BB,ESP,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,94.0,0,1
HB-014678,Resort Hotel,0,0,2023,November,47,26,2023-11-26,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,1,A,D,0,No Deposit,,329.0,0,Transient,38.0,1,0
HB-115680,City Hotel,0,95,2025,July,27,6,2025-07-06,0,3,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,110.0,0,1
HB-011205,Resort Hotel,1,26,2025,April,18,29,2025-04-29,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,85.0,0,1
HB-113572,City Hotel,0,24,2025,June,23,8,2025-06-08,0,1,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,98.8,0,1
HB-026086,Resort Hotel,0,227,2024,July,28,12,2024-07-12,2,7,2,0.0,0,BB,CHE,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,76.8,0,2
HB-040071,City Hotel,0,43,2023,July,27,3,2023-07-03,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,86.0,0,0
HB-020709,Resort Hotel,0,20,2024,February,6,5,2024-02-05,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,54.67,0,1
HB-090376,City Hotel,0,50,2024,June,23,3,2024-06-03,1,2,2,2.0,0,BB,ITA,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,9.0,,0,Transient,189.9,0,2
HB-018616,Resort Hotel,0,0,2024,December,50,14,2024-12-14,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,1,0,3,A,A,0,No Deposit,240.0,,0,Transient,43.0,0,1
HB-099460,City Hotel,0,180,2024,October,41,10,2024-10-10,1,2,1,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,234.0,,0,Transient-Party,120.0,0,0
HB-076804,City Hotel,0,1,2023,August,32,11,2023-08-11,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,105.0,1,1
HB-020913,Resort Hotel,0,0,2024,February,7,18,2024-02-18,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,1,0,1,A,D,0,No Deposit,240.0,,0,Transient,49.0,1,0
HB-029102,Resort Hotel,0,0,2024,October,42,19,2024-10-19,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,G,0,No Deposit,,,0,Transient,140.0,0,0
HB-023193,Resort Hotel,0,66,2024,April,15,9,2024-04-09,2,6,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,73.0,0,1
HB-113981,City Hotel,0,41,2025,June,23,8,2025-06-08,2,5,2,0.0,0,SC,FIN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.71,0,1
HB-098877,City Hotel,0,7,2024,October,40,3,2024-10-03,1,2,1,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,103.18,0,3
HB-002377,Resort Hotel,1,143,2023,October,41,10,2023-10-10,2,5,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,96.0,,0,Transient,36.05,0,0
HB-048966,City Hotel,1,87,2024,April,14,3,2024-04-03,2,2,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,72.25,0,0
HB-015886,Resort Hotel,0,154,2023,July,30,28,2023-07-28,2,8,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,156.0,,0,Contract,90.95,0,0
HB-100682,City Hotel,0,26,2024,October,44,29,2024-10-29,1,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,145.0,0,1
HB-011536,Resort Hotel,1,28,2025,May,20,14,2025-05-14,2,5,2,2.0,0,BB,AUS,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,170.0,0,1
HB-024594,Resort Hotel,0,141,2024,May,21,25,2024-05-25,0,1,2,0.0,0,BB,NOR,Offline TA/TO,TA/TO,0,0,0,D,E,0,No Deposit,251.0,,0,Transient-Party,59.0,0,1
HB-068011,City Hotel,1,93,2025,May,19,11,2025-05-11,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,15.0,,0,Transient,105.84,0,0
HB-075416,City Hotel,1,323,2023,September,36,5,2023-09-05,1,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,60.0,0,0
HB-110925,City Hotel,0,94,2025,April,18,30,2025-04-30,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,123.75,0,1
HB-117176,City Hotel,0,13,2025,July,31,30,2025-07-30,1,0,1,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.0,0,1
HB-010402,Resort Hotel,1,9,2025,March,10,5,2025-03-05,1,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,34.0,0,0
HB-008336,Resort Hotel,1,18,2024,September,38,22,2024-09-22,0,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,119.0,0,0
HB-041160,City Hotel,0,142,2023,August,32,13,2023-08-13,2,5,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,76.5,0,1
HB-075225,City Hotel,1,294,2023,August,32,7,2023-08-07,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-035273,Resort Hotel,0,4,2025,April,16,16,2025-04-16,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,91.0,0,0
HB-055479,City Hotel,1,147,2024,August,33,13,2024-08-13,2,5,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,122.04,0,0
HB-040804,City Hotel,0,36,2023,August,32,7,2023-08-07,0,2,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-099080,City Hotel,0,9,2024,October,41,7,2024-10-07,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,175.0,0,2
HB-047835,City Hotel,1,48,2024,March,10,5,2024-03-05,2,1,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,67.5,0,0
HB-022604,Resort Hotel,0,9,2024,March,13,25,2024-03-25,2,3,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,85.4,0,2
HB-116065,City Hotel,0,451,2025,July,28,12,2025-07-12,0,3,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,1
HB-063270,City Hotel,1,13,2025,February,6,4,2025-02-04,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,91.8,0,1
HB-080749,City Hotel,1,176,2024,April,15,9,2024-04-09,1,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,21.0,,0,Transient,125.0,0,0
HB-048694,City Hotel,1,109,2024,March,13,27,2024-03-27,2,2,2,0.0,0,SC,KWT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,81.25,0,0
HB-117790,City Hotel,0,148,2025,August,32,7,2025-08-07,1,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.0,0,0
HB-046272,City Hotel,0,2,2023,December,52,28,2023-12-28,2,5,2,0.0,0,BB,DZA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,113.57,0,1
HB-086344,City Hotel,0,123,2024,March,13,28,2024-03-28,1,3,3,0.0,0,BB,DEU,Direct,Direct,0,0,0,A,B,1,No Deposit,,,0,Transient,93.0,0,3
HB-034216,Resort Hotel,0,2,2025,March,11,16,2025-03-16,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,E,0,No Deposit,,518.0,0,Transient,35.0,0,1
HB-098657,City Hotel,0,51,2024,October,41,13,2024-10-13,0,1,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,1,D,D,0,No Deposit,9.0,,0,Transient,158.4,0,1
HB-104595,City Hotel,0,34,2025,January,3,18,2025-01-18,0,1,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,1,No Deposit,19.0,,0,Transient-Party,75.0,0,0
HB-102561,City Hotel,0,0,2025,January,3,13,2025-01-13,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,D,0,No Deposit,,383.0,0,Transient,75.0,0,1
HB-007207,Resort Hotel,0,301,2024,July,30,27,2024-07-27,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,128.0,0,2
HB-095498,City Hotel,0,210,2024,August,33,17,2024-08-17,0,3,2,1.0,1,BB,DEU,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,108.3,0,3
HB-042094,City Hotel,0,145,2023,August,35,31,2023-08-31,1,2,2,0.0,0,HB,ISR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,80.0,0,1
HB-080132,City Hotel,0,2,2023,November,45,9,2023-11-09,1,2,1,0.0,0,BB,USA,Complementary,Direct,0,0,0,A,A,0,No Deposit,45.0,,0,Group,79.0,0,0
HB-001145,Resort Hotel,0,75,2023,August,33,15,2023-08-15,2,5,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,156.0,,0,Transient,101.65,0,0
HB-057115,City Hotel,1,42,2024,September,38,19,2024-09-19,1,1,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,112.59,0,1
HB-057599,City Hotel,1,0,2024,September,39,29,2024-09-29,0,1,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,89.0,,0,Transient,118.09,0,0
HB-061874,City Hotel,1,41,2024,December,52,27,2024-12-27,2,5,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,69.29,0,0
HB-093328,City Hotel,0,53,2024,July,29,18,2024-07-18,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.3,0,0
HB-078080,City Hotel,0,0,2023,October,40,2,2023-10-02,0,0,3,0.0,0,BB,PRT,Offline TA/TO,TA/TO,1,0,0,D,K,0,No Deposit,28.0,,0,Transient,0.0,0,1
HB-082127,City Hotel,1,99,2024,February,8,19,2024-02-19,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,1,0,A,A,0,No Deposit,,67.0,0,Transient-Party,80.0,0,0
HB-016397,Resort Hotel,0,100,2023,August,33,17,2023-08-17,3,8,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,147.0,,0,Transient,87.9,0,1
HB-028848,Resort Hotel,0,4,2024,October,41,10,2024-10-10,1,1,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,62.0,1,2
HB-103377,City Hotel,0,37,2024,December,50,14,2024-12-14,2,5,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,96.1,0,1
HB-049431,City Hotel,1,30,2024,April,15,13,2024-04-13,0,4,2,0.0,0,SC,KHM,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,0
HB-066746,City Hotel,1,36,2025,April,17,24,2025-04-24,1,3,2,2.0,0,BB,CHE,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,224.0,0,0
HB-067035,City Hotel,1,111,2025,April,17,27,2025-04-27,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,0,Transient,120.0,0,0
HB-107019,City Hotel,0,15,2025,March,9,2,2025-03-02,1,3,1,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,1
HB-006543,Resort Hotel,1,32,2024,June,25,17,2024-06-17,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,57.0,0,0
HB-079841,City Hotel,1,34,2023,December,49,8,2023-12-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,0,Transient,90.0,0,0
HB-031938,Resort Hotel,0,0,2025,January,2,10,2025-01-10,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,E,3,No Deposit,,,0,Transient,64.0,0,0
HB-103428,City Hotel,0,127,2024,December,51,22,2024-12-22,0,2,2,1.0,0,BB,IND,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,106.2,0,3
HB-047984,City Hotel,1,8,2024,March,11,11,2024-03-11,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,124.0,0,0
HB-068430,City Hotel,1,267,2025,May,20,17,2025-05-17,0,3,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,B,B,1,No Deposit,9.0,,0,Transient,108.95,0,2
HB-049162,City Hotel,1,274,2024,April,14,7,2024-04-07,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-032076,Resort Hotel,0,142,2025,January,3,14,2025-01-14,1,1,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,37.8,0,1
HB-091596,City Hotel,0,0,2024,June,25,23,2024-06-23,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,148.0,0,Transient,95.0,0,0
HB-074775,City Hotel,1,241,2023,October,42,19,2023-10-19,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient,0.0,0,0
HB-029757,Resort Hotel,0,1,2024,November,45,4,2024-11-04,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,D,D,1,No Deposit,,51.0,0,Transient,48.0,1,0
HB-082612,City Hotel,0,29,2023,December,52,31,2023-12-31,0,3,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,115.0,0,1
HB-029776,Resort Hotel,0,34,2024,October,44,31,2024-10-31,1,4,2,0.0,0,HB,BEL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,87.48,0,0
HB-113602,City Hotel,0,22,2025,June,23,8,2025-06-08,0,1,1,0.0,0,BB,CRI,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,150.0,0,1
HB-076678,City Hotel,0,0,2024,February,8,24,2024-02-24,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,2,21,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,1
HB-053149,City Hotel,1,344,2024,June,24,16,2024-06-16,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-074029,City Hotel,1,300,2023,August,32,13,2023-08-13,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-001790,Resort Hotel,0,84,2023,September,37,14,2023-09-14,4,10,2,0.0,0,HB,NLD,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,241.0,,0,Transient,103.51,1,0
HB-082056,City Hotel,0,22,2023,December,51,18,2023-12-18,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient-Party,65.0,0,0
HB-057018,City Hotel,1,302,2024,September,38,16,2024-09-16,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,70,Transient,100.0,0,0
HB-066841,City Hotel,1,156,2025,April,17,26,2025-04-26,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,100.0,0,0
HB-109455,City Hotel,0,202,2025,April,15,9,2025-04-09,2,1,3,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,149.4,0,2
HB-062087,City Hotel,1,46,2025,January,1,1,2025-01-01,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,65.0,0,0
HB-087409,City Hotel,0,86,2024,April,16,17,2024-04-17,2,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.3,0,1
HB-046884,City Hotel,0,20,2024,January,4,23,2024-01-23,2,1,2,0.0,0,BB,CN,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,122.33,0,0
HB-027402,Resort Hotel,0,22,2024,August,35,27,2024-08-27,0,1,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,281.0,1,1
HB-037249,Resort Hotel,0,58,2025,June,24,9,2025-06-09,0,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,76.0,0,2
HB-002889,Resort Hotel,0,0,2023,November,44,4,2023-11-04,0,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,44.1,0,1
HB-009386,Resort Hotel,1,56,2024,November,47,21,2024-11-21,1,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,55.8,0,1
HB-027846,Resort Hotel,0,245,2024,September,37,12,2024-09-12,1,0,2,0.0,0,BB,CHE,Offline TA/TO,TA/TO,0,0,0,D,E,0,No Deposit,251.0,,0,Transient-Party,86.0,0,1
HB-067633,City Hotel,1,116,2025,May,19,5,2025-05-05,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-108280,City Hotel,0,1,2025,March,12,19,2025-03-19,2,4,1,0.0,0,BB,CPV,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,94.0,,0,Transient,65.0,0,0
HB-033385,Resort Hotel,0,13,2025,February,8,17,2025-02-17,2,2,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient,102.0,1,1
HB-098534,City Hotel,0,64,2024,September,39,28,2024-09-28,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,157.0,,0,Transient,101.52,0,0
HB-114893,City Hotel,0,25,2025,June,26,27,2025-06-27,0,1,1,0.0,0,BB,BEL,Corporate,Corporate,0,0,0,A,A,2,No Deposit,,280.0,0,Transient-Party,95.0,0,0
HB-034669,Resort Hotel,0,15,2025,March,13,27,2025-03-27,1,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,65.0,0,2
HB-063675,City Hotel,1,15,2025,February,8,17,2025-02-17,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,95.0,0,0
HB-027887,Resort Hotel,0,7,2024,September,37,11,2024-09-11,2,1,2,0.0,0,BB,BLR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient-Party,127.67,1,2
HB-025993,Resort Hotel,0,133,2024,July,28,11,2024-07-11,2,5,2,2.0,0,Undefined,FRA,Direct,Direct,0,0,0,C,C,0,No Deposit,250.0,,0,Transient,263.57,1,0
HB-073384,City Hotel,1,331,2025,August,34,19,2025-08-19,2,5,1,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.67,0,0
HB-026951,Resort Hotel,0,8,2024,August,33,13,2024-08-13,1,1,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,E,F,0,No Deposit,240.0,,0,Transient,286.0,0,1
HB-065103,City Hotel,1,111,2025,March,13,24,2025-03-24,1,2,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,106.2,0,1
HB-070908,City Hotel,1,129,2025,June,26,24,2025-06-24,2,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,30.0,,0,Transient,120.0,0,0
HB-074516,City Hotel,1,332,2023,September,37,14,2023-09-14,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-022353,Resort Hotel,0,10,2024,March,12,18,2024-03-18,2,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,49.0,1,0
HB-040882,City Hotel,0,16,2023,August,32,8,2023-08-08,2,2,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-052493,City Hotel,1,213,2024,June,23,7,2024-06-07,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,62,Transient,130.0,0,0
HB-085516,City Hotel,0,39,2024,March,11,14,2024-03-14,1,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,81.9,0,0
HB-055672,City Hotel,1,192,2024,August,33,18,2024-08-18,2,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,99.45,0,1
HB-004639,Resort Hotel,1,106,2024,March,12,24,2024-03-24,1,3,2,0.0,0,FB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,68.0,,0,Transient,84.0,0,0
HB-031086,Resort Hotel,0,0,2024,December,50,14,2024-12-14,0,0,1,0.0,0,BB,,Corporate,Corporate,1,0,0,A,A,0,No Deposit,,178.0,0,Transient,0.0,0,0
HB-074445,City Hotel,1,304,2023,August,33,17,2023-08-17,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-011440,Resort Hotel,1,158,2025,May,19,8,2025-05-08,1,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,85.0,0,0
HB-110595,City Hotel,0,93,2025,April,17,21,2025-04-21,2,6,2,1.0,0,HB,EST,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,184.5,0,1
HB-098662,City Hotel,0,193,2024,September,40,30,2024-09-30,1,2,2,0.0,0,BB,DEU,Groups,Corporate,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,132.0,0,0
HB-025063,Resort Hotel,0,136,2024,June,24,12,2024-06-12,1,0,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,251.0,,0,Transient,78.0,0,0
HB-107824,City Hotel,0,256,2025,March,12,17,2025-03-17,0,2,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,2
HB-029191,Resort Hotel,0,244,2024,October,42,16,2024-10-16,2,5,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,120.0,0,1
HB-100690,City Hotel,0,118,2024,October,43,27,2024-10-27,1,3,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,96.78,0,1
HB-026319,Resort Hotel,0,169,2024,July,29,21,2024-07-21,2,5,2,0.0,0,BB,PLW,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,136.29,0,2
HB-084732,City Hotel,0,116,2024,February,9,28,2024-02-28,2,2,1,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,134.0,,0,Transient-Party,75.75,0,0
HB-080513,City Hotel,1,221,2024,June,24,10,2024-06-10,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,3.0,,15,Transient,80.0,0,0
HB-072454,City Hotel,1,65,2025,July,31,28,2025-07-28,2,7,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.44,0,1
HB-096748,City Hotel,0,136,2024,September,36,4,2024-09-04,2,2,2,0.0,0,BB,ROU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,80.75,0,0
HB-060396,City Hotel,1,43,2024,November,45,9,2024-11-09,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,155.0,,0,Transient,176.67,0,2
HB-041936,City Hotel,0,1,2023,August,34,26,2023-08-26,1,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,110.8,0,1
HB-047918,City Hotel,0,66,2024,March,10,9,2024-03-09,0,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,96.3,1,0
HB-100350,City Hotel,0,40,2024,October,43,24,2024-10-24,1,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-059711,City Hotel,1,166,2024,November,44,1,2024-11-01,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,110.0,0,0
HB-054797,City Hotel,1,391,2024,July,30,27,2024-07-27,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,65.0,0,0
HB-062876,City Hotel,1,59,2025,January,4,23,2025-01-23,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,326.0,,0,Transient,80.0,0,0
HB-084413,City Hotel,0,3,2024,July,28,11,2024-07-11,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,5,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,1
HB-111268,City Hotel,0,99,2025,May,18,4,2025-05-04,1,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,135.0,0,2
HB-094067,City Hotel,0,75,2024,July,31,30,2024-07-30,0,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,127.8,0,1
HB-006387,Resort Hotel,1,34,2024,June,23,7,2024-06-07,0,4,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,119.0,0,0
HB-029328,Resort Hotel,0,166,2024,October,42,19,2024-10-19,2,5,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,98.14,0,2
HB-068771,City Hotel,1,420,2025,May,21,20,2025-05-20,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-038289,Resort Hotel,0,98,2025,July,28,10,2025-07-10,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,193.0,1,1
HB-058213,City Hotel,1,96,2024,October,41,8,2024-10-08,1,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.8,0,3
HB-012227,Resort Hotel,1,263,2025,June,25,18,2025-06-18,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Contract,96.4,0,0
HB-075894,City Hotel,1,274,2023,July,29,18,2023-07-18,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-070555,City Hotel,1,91,2025,June,25,18,2025-06-18,2,1,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,216.0,0,0
HB-056600,City Hotel,1,178,2024,September,37,9,2024-09-09,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,0,Transient,135.0,0,0
HB-039705,Resort Hotel,0,212,2025,August,34,21,2025-08-21,1,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,4,No Deposit,240.0,,0,Transient,156.25,0,1
HB-044350,City Hotel,0,61,2023,October,40,4,2023-10-04,2,0,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,12.0,,0,Transient-Party,73.0,0,0
HB-034323,Resort Hotel,0,0,2025,March,12,19,2025-03-19,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,80.0,0,0
HB-057370,City Hotel,1,23,2024,September,39,24,2024-09-24,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,161.5,0,2
HB-016226,Resort Hotel,0,139,2023,August,32,10,2023-08-10,3,7,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,120.6,0,1
HB-063043,City Hotel,1,61,2025,January,5,27,2025-01-27,0,2,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,1
HB-040922,City Hotel,0,2,2023,August,32,9,2023-08-09,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,67.5,0,2
HB-014741,Resort Hotel,1,259,2023,September,37,17,2023-09-17,0,3,1,0.0,0,BB,GBR,Groups,Corporate,0,1,0,A,A,0,Non Refund,,223.0,0,Transient,33.3,0,0
HB-029770,Resort Hotel,0,158,2024,October,44,29,2024-10-29,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,37.14,0,2
HB-054625,City Hotel,1,89,2024,July,29,21,2024-07-21,0,2,2,2.0,0,BB,ITA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,186.3,0,0
HB-061764,City Hotel,1,102,2024,December,52,26,2024-12-26,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,B,B,3,No Deposit,9.0,,0,Transient-Party,110.34,0,0
HB-016373,Resort Hotel,0,79,2023,August,33,14,2023-08-14,4,9,3,2.0,0,BB,PRT,Direct,Direct,0,0,0,H,H,0,No Deposit,,,0,Transient,241.0,1,0
HB-004541,Resort Hotel,0,136,2024,March,12,24,2024-03-24,0,3,1,0.0,0,Undefined,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,387.0,,0,Transient-Party,62.0,0,0
HB-081161,City Hotel,1,12,2023,December,50,12,2023-12-12,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Contract,87.0,0,1
HB-056550,City Hotel,1,163,2024,September,36,8,2024-09-08,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,44.0,,0,Transient-Party,110.0,0,0
HB-119147,City Hotel,0,39,2025,August,35,29,2025-08-29,0,1,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,E,1,No Deposit,9.0,,0,Transient,170.0,0,1
HB-049424,City Hotel,1,32,2024,April,15,13,2024-04-13,0,3,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,140.7,0,0
HB-014543,Resort Hotel,0,2,2023,December,50,17,2023-12-17,0,2,2,0.0,0,BB,,Direct,Direct,0,0,1,A,D,0,No Deposit,,,0,Transient,43.0,0,1
HB-012301,Resort Hotel,1,28,2025,June,26,23,2025-06-23,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,170.0,0,2
HB-055632,City Hotel,1,405,2024,August,33,18,2024-08-18,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-067778,City Hotel,1,102,2025,May,19,7,2025-05-07,2,0,2,0.0,0,SC,KOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,0
HB-066146,City Hotel,1,181,2025,April,16,14,2025-04-14,2,2,2,2.0,0,HB,BRA,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,9.0,,0,Transient,189.0,0,2
HB-064539,City Hotel,1,98,2025,March,11,12,2025-03-12,2,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.2,0,0
HB-028211,Resort Hotel,0,247,2024,September,38,19,2024-09-19,1,5,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,116.0,0,2
HB-115107,City Hotel,0,261,2025,June,26,29,2025-06-29,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,90.96,0,0
HB-022082,Resort Hotel,0,10,2024,March,10,4,2024-03-04,4,10,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,96.0,,0,Transient,42.36,0,0
HB-039827,Resort Hotel,0,191,2025,August,33,16,2025-08-16,4,10,2,2.0,0,BB,ARG,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,526.0,,0,Transient,144.0,0,0
HB-013255,Resort Hotel,1,31,2025,August,32,6,2025-08-06,2,3,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,225.6,0,1
HB-060565,City Hotel,1,74,2024,November,46,15,2024-11-15,0,4,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.4,0,2
HB-044185,City Hotel,0,164,2023,October,40,2,2023-10-02,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,19.0,,0,Transient-Party,100.0,0,0
HB-089757,City Hotel,0,5,2024,May,21,24,2024-05-24,0,2,2,0.0,0,BB,MEX,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,78.0,0,Transient-Party,110.0,0,1
HB-074647,City Hotel,1,374,2023,October,43,26,2023-10-26,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-061064,City Hotel,1,24,2024,December,48,1,2024-12-01,1,3,2,0.0,0,BB,ESP,Online TA,GDS,0,0,0,A,A,0,No Deposit,195.0,,0,Transient,104.0,0,0
HB-118829,City Hotel,0,148,2025,August,34,21,2025-08-21,1,4,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,83.0,,0,Transient,142.2,0,1
HB-032280,Resort Hotel,0,2,2025,January,4,20,2025-01-20,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,F,0,No Deposit,,,0,Transient,60.0,0,2
HB-059689,City Hotel,1,29,2024,October,44,31,2024-10-31,1,4,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.4,0,2
HB-072936,City Hotel,1,125,2025,August,32,10,2025-08-10,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,83.0,,0,Transient,114.39,0,0
HB-017417,Resort Hotel,0,16,2023,October,41,9,2023-10-09,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,274.0,0,Transient-Party,48.0,0,0
HB-032392,Resort Hotel,0,72,2025,January,3,19,2025-01-19,2,5,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,92.0,0,2
HB-030769,Resort Hotel,0,10,2024,December,49,3,2024-12-03,0,1,1,0.0,0,HB,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,44.0,0,0
HB-064458,City Hotel,1,43,2025,March,11,10,2025-03-10,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,72.0,0,1
HB-080836,City Hotel,0,0,2023,November,47,22,2023-11-22,2,2,2,0.0,0,BB,DEU,Groups,TA/TO,0,0,0,A,A,1,No Deposit,37.0,,0,Transient,75.0,0,0
HB-042716,City Hotel,1,86,2023,September,36,9,2023-09-09,0,2,2,0.0,0,BB,FRA,Groups,Corporate,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,110.0,0,0
HB-032449,Resort Hotel,0,0,2025,January,4,26,2025-01-26,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,55.0,1,1
HB-103745,City Hotel,0,119,2024,December,52,28,2024-12-28,0,3,2,1.0,0,HB,CHE,Direct,Direct,0,0,0,E,E,2,No Deposit,14.0,,0,Transient,202.33,0,1
HB-014758,Resort Hotel,1,259,2023,September,37,17,2023-09-17,0,3,1,0.0,0,BB,GBR,Groups,Corporate,0,1,0,A,A,0,Non Refund,,223.0,0,Transient,33.3,0,0
HB-032823,Resort Hotel,0,67,2025,February,6,3,2025-02-03,1,2,2,0.0,0,BB,CN,Direct,Direct,0,0,0,A,D,0,No Deposit,250.0,,0,Transient,33.26,0,0
HB-105021,City Hotel,0,1,2025,January,4,21,2025-01-21,2,5,2,0.0,0,BB,AGO,Direct,TA/TO,0,0,0,A,A,1,No Deposit,,,0,Group,88.0,0,1
HB-021742,Resort Hotel,0,0,2024,March,10,7,2024-03-07,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,E,E,0,No Deposit,,212.0,0,Transient,55.0,0,0
HB-101051,City Hotel,0,8,2024,November,45,5,2024-11-05,0,1,2,0.0,0,BB,CHN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,359.0,,0,Transient-Party,130.0,0,0
HB-072395,City Hotel,1,191,2025,July,30,27,2025-07-27,2,5,3,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,E,E,2,No Deposit,9.0,,0,Transient,225.0,0,1
HB-068870,City Hotel,1,26,2025,May,21,22,2025-05-22,1,0,1,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,1
HB-028347,Resort Hotel,0,40,2024,September,39,23,2024-09-23,2,5,2,2.0,0,BB,IRL,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,164.86,0,0
HB-053272,City Hotel,1,245,2024,June,25,17,2024-06-17,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,0,Transient,75.0,0,0
HB-024825,Resort Hotel,0,115,2024,May,22,29,2024-05-29,2,5,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,70.2,0,1
HB-042107,City Hotel,0,0,2023,August,35,31,2023-08-31,1,2,2,2.0,0,BB,VEN,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Contract,155.33,0,0
HB-100031,City Hotel,0,5,2024,October,42,20,2024-10-20,0,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,3
HB-111971,City Hotel,0,13,2025,May,20,15,2025-05-15,1,2,1,0.0,0,BB,FRA,Corporate,Corporate,0,0,0,E,E,0,No Deposit,,450.0,0,Transient,125.0,0,0
HB-097412,City Hotel,0,48,2024,September,37,14,2024-09-14,0,2,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,281.0,,0,Transient-Party,130.0,0,0
HB-028411,Resort Hotel,0,175,2024,October,40,1,2024-10-01,1,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,C,4,No Deposit,240.0,,0,Transient,114.5,1,1
HB-014269,Resort Hotel,0,17,2025,February,8,21,2025-02-21,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,1,10,E,E,0,No Deposit,,292.0,0,Transient,58.0,1,1
HB-009967,Resort Hotel,1,12,2025,January,5,30,2025-01-30,1,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,242.0,,0,Transient,55.1,0,1
HB-072330,City Hotel,1,243,2025,July,30,26,2025-07-26,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-065675,City Hotel,1,69,2025,April,14,6,2025-04-06,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,Non Refund,,197.0,0,Transient,85.0,0,0
HB-078700,City Hotel,0,1,2024,February,7,17,2024-02-17,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,11,A,A,0,No Deposit,,40.0,0,Transient,66.0,0,1
HB-096366,City Hotel,0,61,2024,August,35,29,2024-08-29,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,1,0
HB-073553,City Hotel,1,78,2025,August,35,26,2025-08-26,1,1,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,85.0,,0,Transient,116.0,0,0
HB-042984,City Hotel,1,65,2023,September,37,12,2023-09-12,2,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,86.0,0,0
HB-032172,Resort Hotel,0,40,2025,January,3,16,2025-01-16,1,2,1,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,A,D,1,No Deposit,,,0,Transient-Party,55.0,0,0
HB-045715,City Hotel,0,76,2023,November,46,19,2023-11-19,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,72.25,0,2
HB-048180,City Hotel,1,91,2024,March,12,18,2024-03-18,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,20,Transient,75.0,0,0
HB-006296,Resort Hotel,0,217,2024,June,22,1,2024-06-01,1,4,2,0.0,0,HB,IRL,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,148.0,0,0
HB-030891,Resort Hotel,0,14,2024,December,49,5,2024-12-05,1,2,2,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,134.0,,0,Transient-Party,84.0,0,0
HB-017893,Resort Hotel,0,0,2023,October,43,23,2023-10-23,1,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,47.0,0,1
HB-072782,City Hotel,1,84,2025,August,32,6,2025-08-06,2,1,2,1.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,160.0,0,0
HB-015167,Resort Hotel,1,244,2023,September,35,2,2023-09-02,2,5,2,0.0,0,BB,IRL,Groups,TA/TO,0,24,0,A,A,0,No Deposit,96.0,,0,Transient-Party,8.0,0,0
HB-104169,City Hotel,0,14,2025,January,1,2,2025-01-02,1,4,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,91.6,1,0
HB-110537,City Hotel,0,123,2025,April,17,24,2025-04-24,1,3,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,105.75,0,1
HB-016534,Resort Hotel,0,1,2023,August,35,29,2023-08-29,2,2,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,D,1,No Deposit,,,0,Transient-Party,142.5,0,1
HB-041647,City Hotel,1,13,2023,August,33,20,2023-08-20,0,3,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,80.0,0,1
HB-104300,City Hotel,0,181,2025,January,2,8,2025-01-08,2,1,2,0.0,0,HB,IRL,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,9.0,,0,Transient,137.7,0,1
HB-057272,City Hotel,1,94,2024,September,38,22,2024-09-22,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,85.0,0,0
HB-093717,City Hotel,0,82,2024,July,30,23,2024-07-23,2,1,0,2.0,0,BB,BEL,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient,97.54,0,1
HB-055802,City Hotel,1,38,2024,August,34,21,2024-08-21,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.9,0,0
HB-108659,City Hotel,0,28,2025,March,13,30,2025-03-30,0,1,1,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,86.4,0,0
HB-005471,Resort Hotel,1,87,2024,April,18,29,2024-04-29,2,5,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,71.0,,0,Transient,46.0,0,0
HB-039831,Resort Hotel,0,202,2025,August,34,21,2025-08-21,3,6,2,2.0,0,HB,PRT,Online TA,TA/TO,0,0,0,C,C,1,No Deposit,314.0,,0,Transient,196.5,1,0
HB-059309,City Hotel,1,34,2024,October,43,26,2024-10-26,0,4,2,0.0,0,BB,THA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,129.0,0,1
HB-018049,Resort Hotel,0,48,2023,October,43,25,2023-10-25,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Contract,42.5,0,1
HB-104615,City Hotel,0,34,2025,January,3,18,2025-01-18,0,1,1,0.0,0,BB,MDV,Groups,TA/TO,0,0,0,A,A,0,No Deposit,19.0,,0,Transient-Party,75.0,0,0
HB-080818,City Hotel,0,27,2023,November,47,22,2023-11-22,2,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-029438,Resort Hotel,0,0,2024,October,43,23,2024-10-23,2,4,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,96.0,,0,Group,46.0,0,1
HB-055643,City Hotel,1,138,2024,August,33,18,2024-08-18,0,2,3,0.0,0,BB,ARE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,142.2,0,0
HB-112288,City Hotel,0,212,2025,May,21,20,2025-05-20,1,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,125.1,0,1
HB-022828,Resort Hotel,0,72,2024,April,14,3,2024-04-03,2,3,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,E,1,No Deposit,314.0,,0,Transient,104.0,0,0
HB-041419,City Hotel,1,131,2023,August,33,15,2023-08-15,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-095168,City Hotel,0,5,2024,August,33,15,2024-08-15,1,0,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,114.3,0,1
HB-027597,Resort Hotel,0,8,2024,September,35,1,2024-09-01,0,2,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,C,0,No Deposit,250.0,,0,Transient,161.0,0,0
HB-077654,City Hotel,1,98,2023,December,52,26,2023-12-26,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,8.0,,0,Transient,118.0,0,1
HB-005066,Resort Hotel,1,183,2024,April,16,16,2024-04-16,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,298.0,,0,Transient-Party,85.0,0,0
HB-017440,Resort Hotel,0,59,2023,October,40,8,2023-10-08,0,3,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,281.0,,50,Contract,45.0,0,0
HB-093418,City Hotel,0,1,2024,July,29,20,2024-07-20,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-024021,Resort Hotel,0,67,2024,April,17,26,2024-04-26,4,10,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,,0,Transient,75.0,0,2
HB-071731,City Hotel,1,450,2025,July,28,11,2025-07-11,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-117072,City Hotel,0,7,2025,July,30,27,2025-07-27,0,2,2,0.0,0,BB,MEX,Direct,Direct,0,0,0,E,E,0,No Deposit,,485.0,0,Transient,125.0,0,1
HB-048676,City Hotel,1,17,2024,March,13,26,2024-03-26,2,1,2,2.0,0,BB,NLD,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,224.33,0,0
HB-056110,City Hotel,1,139,2024,August,35,29,2024-08-29,1,2,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,85.5,0,0
HB-107060,City Hotel,0,1,2025,March,10,6,2025-03-06,1,0,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient,88.0,0,1
HB-103655,City Hotel,0,5,2024,December,52,28,2024-12-28,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,84.8,0,0
HB-079340,City Hotel,0,10,2023,October,42,22,2023-10-22,1,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,27.0,,0,Transient,63.75,0,0
HB-055730,City Hotel,1,303,2024,August,34,19,2024-08-19,2,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,78.0,0,0
HB-075408,City Hotel,1,323,2023,September,36,5,2023-09-05,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-110165,City Hotel,0,133,2025,April,16,19,2025-04-19,0,4,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,390.0,,0,Transient-Party,124.0,0,0
HB-099372,City Hotel,0,180,2024,October,41,10,2024-10-10,1,2,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,234.0,,0,Transient-Party,120.0,0,0
HB-081971,City Hotel,1,115,2024,March,12,20,2024-03-20,2,0,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,41.0,,22,Transient,70.0,0,0
HB-000757,Resort Hotel,1,101,2023,July,30,27,2023-07-27,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,134.0,0,2
HB-015428,Resort Hotel,0,115,2023,July,27,5,2023-07-05,4,7,2,0.0,0,HB,CHE,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,69.0,,0,Contract,113.05,0,0
HB-048687,City Hotel,0,1,2024,March,13,27,2024-03-27,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,99.0,0,1
HB-004320,Resort Hotel,1,30,2024,March,10,4,2024-03-04,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,39.0,0,2
HB-045207,City Hotel,1,50,2023,October,43,24,2023-10-24,0,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,146.0,0,0
HB-026572,Resort Hotel,0,0,2024,August,31,2,2024-08-02,0,2,2,0.0,0,BB,AUS,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,219.0,0,0
HB-094348,City Hotel,0,168,2024,July,31,31,2024-07-31,2,1,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,7.0,,0,Transient,81.08,0,1
HB-057953,City Hotel,1,67,2024,October,40,3,2024-10-03,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,85.0,0,0
HB-084991,City Hotel,0,35,2024,March,9,3,2024-03-03,1,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,83.9,0,1
HB-013668,Resort Hotel,1,253,2025,August,35,25,2025-08-25,2,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,153.75,0,2
HB-002569,Resort Hotel,0,122,2023,October,42,22,2023-10-22,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,240.0,,0,Transient,55.0,2,2
HB-061256,City Hotel,1,101,2024,December,49,6,2024-12-06,0,1,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,1
HB-063189,City Hotel,1,37,2025,February,5,1,2025-02-01,2,4,2,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,90.1,0,1
HB-079943,City Hotel,1,194,2024,May,18,4,2024-05-04,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Contract,106.2,0,0
HB-049680,City Hotel,1,275,2024,April,16,17,2024-04-17,2,0,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,0,Transient,110.0,0,0
HB-042684,City Hotel,1,86,2023,September,36,9,2023-09-09,0,2,2,0.0,0,BB,FRA,Groups,Corporate,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,110.0,0,0
HB-096631,City Hotel,0,68,2024,August,35,29,2024-08-29,2,5,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,92.35,0,1
HB-005370,Resort Hotel,1,26,2024,April,17,26,2024-04-26,0,4,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,15.0,,0,Transient,78.2,0,0
HB-113055,City Hotel,0,81,2025,May,22,29,2025-05-29,1,3,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,168.0,,0,Transient,98.1,0,0
HB-082870,City Hotel,1,68,2024,February,7,17,2024-02-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,37.0,,0,Transient,75.0,0,0
HB-092594,City Hotel,0,126,2024,July,28,8,2024-07-08,0,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,123.3,1,1
HB-052494,City Hotel,1,213,2024,June,23,7,2024-06-07,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,62,Transient,130.0,0,0
HB-000930,Resort Hotel,1,28,2023,August,31,6,2023-08-06,1,3,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,242.0,,0,Transient,239.3,0,1
HB-103605,City Hotel,0,107,2024,December,51,21,2024-12-21,2,5,2,0.0,0,SC,NLD,Online TA,TA/TO,0,0,0,A,A,4,No Deposit,9.0,,0,Transient,76.69,0,1
HB-005452,Resort Hotel,1,147,2024,April,18,29,2024-04-29,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,65.7,0,0
HB-044772,City Hotel,0,99,2023,October,41,10,2023-10-10,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,89.25,0,3
HB-117071,City Hotel,0,261,2025,July,30,26,2025-07-26,0,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,42.0,,0,Transient,89.0,0,0
HB-043994,City Hotel,1,96,2023,September,39,28,2023-09-28,1,1,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,3.0,,0,Transient-Party,123.5,0,0
HB-082464,City Hotel,0,40,2023,December,52,26,2023-12-26,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,64.15,0,0
HB-063774,City Hotel,1,212,2025,February,8,20,2025-02-20,1,2,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.0,0,0
HB-087896,City Hotel,0,20,2024,April,17,24,2024-04-24,2,2,2,0.0,0,SC,ESP,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,120.5,1,0
HB-004673,Resort Hotel,1,21,2024,March,13,27,2024-03-27,2,0,2,2.0,0,HB,GBR,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,141.0,0,0
HB-052215,City Hotel,1,330,2024,June,22,2,2024-06-02,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-098960,City Hotel,0,34,2024,October,40,5,2024-10-05,0,2,2,0.0,0,BB,HUN,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,83.0,,0,Transient,144.0,0,0
HB-059507,City Hotel,1,247,2024,October,44,28,2024-10-28,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,110.0,0,0
HB-007463,Resort Hotel,1,217,2024,August,32,10,2024-08-10,2,5,2,1.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,170.0,0,0
HB-050931,City Hotel,0,286,2024,May,19,11,2024-05-11,0,4,2,0.0,0,BB,AUT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,176,Transient-Party,99.0,0,1
HB-062329,City Hotel,1,14,2025,January,2,8,2025-01-08,2,3,2,0.0,0,BB,TUR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,82.88,0,2
HB-014412,Resort Hotel,0,40,2023,September,36,6,2023-09-06,2,3,2,1.0,0,HB,,Direct,Direct,0,0,0,F,F,2,No Deposit,250.0,,0,Transient,174.8,0,1
HB-001650,Resort Hotel,0,2,2023,September,36,7,2023-09-07,1,4,2,0.0,1,HB,PRT,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient,188.0,0,2
HB-000670,Resort Hotel,0,39,2023,July,30,25,2023-07-25,0,1,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,F,0,No Deposit,134.0,,0,Transient,107.0,0,0
HB-010659,Resort Hotel,1,102,2025,March,13,26,2025-03-26,2,1,1,0.0,0,BB,PRT,Groups,Corporate,0,0,0,A,A,0,Non Refund,495.0,,0,Transient,39.33,0,0
HB-025105,Resort Hotel,0,131,2024,June,24,13,2024-06-13,1,1,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,93.62,1,1
HB-043881,City Hotel,0,192,2023,September,39,25,2023-09-25,2,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,102.0,0,0
HB-076438,City Hotel,1,358,2023,October,41,10,2023-10-10,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-072236,City Hotel,1,163,2025,July,30,24,2025-07-24,1,2,3,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,175.5,0,0
HB-014728,Resort Hotel,1,259,2023,September,37,17,2023-09-17,0,3,2,0.0,0,BB,GBR,Groups,Corporate,0,1,0,A,A,0,Non Refund,,223.0,0,Transient,40.05,0,0
HB-112934,City Hotel,0,112,2025,May,22,27,2025-05-27,2,2,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,153.0,1,2
HB-051501,City Hotel,1,211,2024,May,21,20,2024-05-20,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,111,Transient,100.0,0,0
HB-100774,City Hotel,0,95,2024,October,44,30,2024-10-30,2,0,1,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.5,0,1
HB-069113,City Hotel,1,161,2025,May,21,25,2025-05-25,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,102.04,0,1
HB-053729,City Hotel,1,119,2024,June,26,28,2024-06-28,0,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.5,0,0
HB-114307,City Hotel,0,186,2025,June,25,18,2025-06-18,2,0,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,42.0,,0,Transient,89.1,0,0
HB-065022,City Hotel,1,73,2025,March,12,22,2025-03-22,0,4,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,117.3,0,0
HB-075955,City Hotel,1,301,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-110538,City Hotel,0,123,2025,April,17,24,2025-04-24,1,3,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,105.75,0,1
HB-024025,Resort Hotel,0,163,2024,May,18,5,2024-05-05,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient-Party,52.2,0,1
HB-001703,Resort Hotel,0,113,2023,September,36,10,2023-09-10,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,147.0,,0,Transient,57.54,0,0
HB-073323,City Hotel,1,109,2025,August,34,18,2025-08-18,2,4,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,204.0,0,1
HB-115664,City Hotel,0,46,2025,July,27,6,2025-07-06,0,3,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,146.7,0,1
HB-043279,City Hotel,0,162,2023,September,37,17,2023-09-17,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,0,Transient-Party,70.0,0,0
HB-065937,City Hotel,1,48,2025,April,15,10,2025-04-10,1,3,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,0
HB-077718,City Hotel,0,6,2023,September,38,21,2023-09-21,1,3,1,0.0,0,BB,HUN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,10.0,,0,Transient,114.0,0,1
HB-117588,City Hotel,0,300,2025,August,32,4,2025-08-04,1,2,3,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,83.0,,0,Transient,98.28,0,2
HB-063965,City Hotel,1,204,2025,February,9,25,2025-02-25,1,1,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,122.4,0,2
HB-012342,Resort Hotel,1,128,2025,June,26,25,2025-06-25,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,410.0,,0,Transient,63.0,0,0
HB-105503,City Hotel,0,63,2025,February,6,5,2025-02-05,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.4,0,2
HB-056277,City Hotel,1,120,2024,September,36,2,2024-09-02,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,115.0,0,0
HB-007126,Resort Hotel,1,31,2024,July,30,23,2024-07-23,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,160.93,0,0
HB-102035,City Hotel,0,80,2024,November,47,19,2024-11-19,2,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.6,0,1
HB-029321,Resort Hotel,0,124,2024,October,43,22,2024-10-22,2,2,2,0.0,0,BB,SWE,Groups,Corporate,0,0,0,F,F,1,No Deposit,,,0,Transient-Party,95.0,1,0
HB-026045,Resort Hotel,0,155,2024,July,28,10,2024-07-10,4,5,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,A,A,1,No Deposit,250.0,,0,Transient,102.9,0,2
HB-019579,Resort Hotel,0,8,2023,December,52,26,2023-12-26,1,1,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,339.0,,0,Transient,29.0,0,0
HB-084041,City Hotel,0,8,2024,February,7,16,2024-02-16,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,64.0,0,0
HB-000936,Resort Hotel,0,1,2023,August,32,7,2023-08-07,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,F,0,No Deposit,,144.0,0,Transient,114.0,0,0
HB-090575,City Hotel,0,247,2024,June,23,6,2024-06-06,1,1,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,93.0,0,1
HB-033621,Resort Hotel,0,88,2025,January,4,24,2025-01-24,10,25,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,41.47,0,1
HB-065418,City Hotel,1,129,2025,April,14,3,2025-04-03,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,0,Transient,100.0,0,0
HB-053915,City Hotel,0,198,2024,July,27,1,2024-07-01,2,5,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.95,0,1
HB-088200,City Hotel,0,60,2024,April,18,30,2024-04-30,1,1,2,1.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,83.0,,0,Transient,114.57,0,0
HB-020449,Resort Hotel,0,2,2024,January,4,28,2024-01-28,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-091343,City Hotel,0,1,2024,June,25,17,2024-06-17,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,75.0,0,1
HB-079886,City Hotel,1,32,2023,November,47,20,2023-11-20,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,119.0,,0,Transient-Party,73.0,0,0
HB-073313,City Hotel,1,214,2025,August,34,18,2025-08-18,2,2,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,130.78,0,0
HB-012678,Resort Hotel,1,110,2025,July,28,11,2025-07-11,0,5,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,260.0,0,1
HB-080659,City Hotel,0,32,2023,November,47,20,2023-11-20,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,119.0,,0,Transient-Party,73.0,0,0
HB-092921,City Hotel,0,9,2024,July,27,7,2024-07-07,2,5,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,116.45,0,0
HB-041787,City Hotel,0,53,2023,August,34,24,2023-08-24,1,1,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-047153,City Hotel,0,37,2024,February,6,10,2024-02-10,1,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.3,0,1
HB-015505,Resort Hotel,0,140,2023,July,28,16,2023-07-16,2,5,2,1.0,0,FB,PRT,Direct,Direct,0,0,0,A,A,2,No Deposit,250.0,,0,Transient,174.95,0,1
HB-105838,City Hotel,0,12,2025,February,7,12,2025-02-12,2,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,54.71,0,1
HB-047853,City Hotel,1,10,2024,March,10,6,2024-03-06,1,0,1,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.0,0,0
HB-036947,Resort Hotel,0,3,2025,May,22,29,2025-05-29,1,3,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,I,0,No Deposit,240.0,,0,Transient,129.0,1,2
HB-039391,Resort Hotel,0,197,2025,August,33,13,2025-08-13,2,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient-Party,110.7,0,0
HB-091434,City Hotel,0,63,2024,June,25,19,2024-06-19,2,1,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,F,0,No Deposit,9.0,,0,Transient,141.3,0,1
HB-093682,City Hotel,0,175,2024,July,30,23,2024-07-23,1,1,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.5,0,1
HB-104490,City Hotel,0,21,2025,January,2,11,2025-01-11,0,4,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,82.88,0,3
HB-056847,City Hotel,1,317,2024,September,37,15,2024-09-15,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,120.0,0,0
HB-079417,City Hotel,1,137,2024,January,4,27,2024-01-27,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,29.0,,45,Transient,70.0,0,0
HB-098709,City Hotel,0,281,2024,October,40,1,2024-10-01,2,1,2,1.0,0,HB,ITA,Groups,TA/TO,0,0,0,A,A,2,No Deposit,1.0,,174,Transient-Party,96.0,0,0
HB-058511,City Hotel,1,461,2024,October,41,13,2024-10-13,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-069535,City Hotel,1,23,2025,June,22,1,2025-06-01,0,3,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,210.0,0,1
HB-012670,Resort Hotel,1,47,2025,July,28,11,2025-07-11,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,170.0,0,0
HB-079381,City Hotel,1,16,2023,October,44,30,2023-10-30,0,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,1,No Deposit,9.0,,0,Contract,110.5,0,0
HB-095292,City Hotel,0,15,2024,August,33,17,2024-08-17,0,1,1,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,124.0,0,1
HB-115890,City Hotel,0,191,2025,July,28,8,2025-07-08,2,2,2,2.0,0,BB,POL,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,42.0,,0,Transient,152.28,0,0
HB-011545,Resort Hotel,1,41,2025,May,20,15,2025-05-15,1,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,119.0,0,1
HB-013781,Resort Hotel,1,98,2025,August,35,30,2025-08-30,0,3,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,210.0,0,1
HB-005489,Resort Hotel,1,39,2024,April,18,30,2024-04-30,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,86.0,0,0
HB-008144,Resort Hotel,0,327,2024,September,37,14,2024-09-14,0,4,2,0.0,0,BB,IRL,Groups,TA/TO,0,0,0,A,A,1,No Deposit,201.0,,0,Transient-Party,61.4,0,0
HB-101682,City Hotel,0,110,2024,November,46,12,2024-11-12,2,2,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,78.1,0,1
HB-041231,City Hotel,1,39,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,101.5,0,0
HB-095120,City Hotel,0,5,2024,August,33,13,2024-08-13,1,1,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,174.0,0,2
HB-001097,Resort Hotel,0,0,2023,August,33,14,2023-08-14,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,F,0,No Deposit,240.0,,0,Transient-Party,172.0,0,2
HB-002685,Resort Hotel,0,1,2023,October,43,24,2023-10-24,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,67.0,0,3
HB-047293,City Hotel,1,39,2024,February,7,15,2024-02-15,1,1,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,67.5,0,0
HB-049557,City Hotel,1,19,2024,April,15,14,2024-04-14,2,3,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,131.6,0,0
HB-083597,City Hotel,0,81,2024,February,6,6,2024-02-06,1,1,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,77.0,0,1
HB-067478,City Hotel,1,143,2025,May,18,4,2025-05-04,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,56.0,,0,Transient,120.0,0,0
HB-019021,Resort Hotel,0,50,2023,December,49,5,2023-12-05,1,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,49.2,1,1
HB-086804,City Hotel,0,8,2024,April,14,5,2024-04-05,0,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,92.17,0,2
HB-063679,City Hotel,1,3,2025,February,8,17,2025-02-17,0,2,2,1.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,186.0,0,0
HB-026657,Resort Hotel,0,0,2024,August,32,5,2024-08-05,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,219.0,0,1
HB-080695,City Hotel,0,32,2023,November,47,20,2023-11-20,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,119.0,,0,Transient-Party,73.0,0,0
HB-014426,Resort Hotel,0,1,2024,June,22,1,2024-06-01,0,1,1,0.0,0,BB,,Direct,Direct,0,0,2,A,A,0,No Deposit,,,0,Transient,75.0,0,0
HB-110121,City Hotel,0,44,2025,April,16,20,2025-04-20,0,3,1,0.0,0,BB,ITA,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,106.67,0,0
HB-004239,Resort Hotel,0,123,2024,February,9,27,2024-02-27,1,1,2,0.0,0,FB,ESP,Groups,Direct,0,0,0,A,A,0,No Deposit,38.0,,0,Transient-Party,64.0,0,0
HB-035564,Resort Hotel,0,99,2025,April,17,25,2025-04-25,0,2,2,0.0,0,HB,AUT,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,241.0,,0,Transient,87.78,0,1
HB-036014,Resort Hotel,0,0,2025,May,19,5,2025-05-05,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,80.0,0,0
HB-059099,City Hotel,1,279,2024,October,43,21,2024-10-21,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,65.0,0,0
HB-060524,City Hotel,1,55,2024,November,46,13,2024-11-13,2,1,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,71.28,0,0
HB-109993,City Hotel,0,13,2025,April,16,16,2025-04-16,2,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,92.0,0,1
HB-079961,City Hotel,0,3,2023,November,44,5,2023-11-05,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Contract,105.5,1,1
HB-092037,City Hotel,0,120,2024,June,26,27,2024-06-27,1,2,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,85.5,0,1
HB-085190,City Hotel,0,24,2024,March,12,21,2024-03-21,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,3,E,E,1,No Deposit,,51.0,0,Transient-Party,106.0,0,1
HB-016536,Resort Hotel,0,211,2023,August,34,26,2023-08-26,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,126.57,0,1
HB-029125,Resort Hotel,0,3,2024,October,42,20,2024-10-20,0,1,1,0.0,0,BB,ESP,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,458.0,0,Transient,50.0,0,0
HB-005522,Resort Hotel,1,36,2024,May,18,1,2024-05-01,2,0,2,2.0,0,BB,CHE,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,125.0,0,0
HB-105400,City Hotel,0,11,2025,February,6,5,2025-02-05,2,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-011651,Resort Hotel,1,92,2025,May,21,24,2025-05-24,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,68.0,0,1
HB-106162,City Hotel,0,4,2025,February,8,19,2025-02-19,2,1,1,1.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,88.0,0,1
HB-034258,Resort Hotel,0,112,2025,March,11,15,2025-03-15,0,3,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,477.0,0,Transient-Party,40.0,0,0
HB-094451,City Hotel,0,173,2024,August,31,4,2024-08-04,0,1,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.3,0,0
HB-108074,City Hotel,0,151,2025,March,12,20,2025-03-20,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,95.0,0,1
HB-091191,City Hotel,0,2,2024,June,24,16,2024-06-16,0,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,141.0,0,0
HB-092573,City Hotel,0,20,2024,July,28,8,2024-07-08,0,1,2,1.0,0,BB,CN,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,158.95,0,1
HB-024892,Resort Hotel,0,133,2024,June,23,6,2024-06-06,1,1,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,A,C,0,No Deposit,250.0,,0,Transient,63.75,0,0
HB-076161,City Hotel,1,233,2023,September,38,18,2023-09-18,0,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,6.0,,0,Transient-Party,120.0,0,0
HB-060805,City Hotel,1,46,2024,November,47,22,2024-11-22,0,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,0
HB-068447,City Hotel,1,323,2025,May,20,18,2025-05-18,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,0
HB-050700,City Hotel,0,124,2024,May,18,5,2024-05-05,1,3,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.45,0,0
HB-008503,Resort Hotel,1,48,2024,October,40,1,2024-10-01,2,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,99.0,0,0
HB-021694,Resort Hotel,0,0,2025,January,3,17,2025-01-17,0,1,1,0.0,0,BB,ESP,Direct,Direct,1,0,1,A,A,0,No Deposit,,,0,Transient,57.0,0,0
HB-086033,City Hotel,0,7,2024,March,12,23,2024-03-23,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,148.0,0,0
HB-037393,Resort Hotel,0,4,2025,June,24,9,2025-06-09,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,78.0,0,0
HB-015961,Resort Hotel,0,53,2023,August,31,3,2023-08-03,1,5,2,0.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,C,C,3,No Deposit,177.0,,0,Transient,180.0,1,3
HB-103070,City Hotel,0,7,2024,December,50,9,2024-12-09,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,124.0,0,1
HB-059021,City Hotel,1,468,2024,October,42,20,2024-10-20,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-085276,City Hotel,0,43,2024,March,11,11,2024-03-11,0,1,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,114.3,0,2
HB-103804,City Hotel,0,16,2024,December,52,29,2024-12-29,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,138.0,0,1
HB-058968,City Hotel,1,59,2024,October,42,19,2024-10-19,0,3,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,D,D,3,No Deposit,9.0,,0,Transient,139.5,0,1
HB-102235,City Hotel,0,1,2024,November,47,24,2024-11-24,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,152.0,,0,Transient,65.6,0,0
HB-103155,City Hotel,0,9,2024,December,50,13,2024-12-13,0,1,1,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,88.0,0,2
HB-011938,Resort Hotel,1,219,2025,June,23,3,2025-06-03,4,6,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,98.4,0,0
HB-029569,Resort Hotel,0,5,2024,October,44,29,2024-10-29,1,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,38.0,0,2
HB-106213,City Hotel,0,14,2025,February,8,19,2025-02-19,2,2,3,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,127.5,0,1
HB-070108,City Hotel,1,206,2025,June,24,9,2025-06-09,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,144.0,0,2
HB-092605,City Hotel,0,168,2024,July,27,2,2024-07-02,2,5,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,62.18,0,1
HB-088530,City Hotel,0,190,2024,May,18,5,2024-05-05,0,3,2,0.0,0,BB,CHE,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,95.4,0,1
HB-020127,Resort Hotel,0,7,2024,January,2,14,2024-01-14,0,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,67.5,1,1
HB-079604,City Hotel,0,28,2023,October,43,29,2023-10-29,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,E,0,No Deposit,98.0,,0,Transient-Party,130.0,0,0
HB-034492,Resort Hotel,0,166,2025,March,12,23,2025-03-23,1,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,40.95,0,1
HB-106667,City Hotel,0,0,2025,February,9,26,2025-02-26,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,88.0,0,0
HB-090765,City Hotel,0,62,2024,June,23,9,2024-06-09,0,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.9,0,0
HB-015937,Resort Hotel,0,156,2023,August,31,2,2023-08-02,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,156.0,,0,Transient,112.63,0,0
HB-015855,Resort Hotel,0,77,2023,August,31,1,2023-08-01,2,2,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,95.0,,0,Transient,201.5,0,1
HB-113054,City Hotel,0,108,2025,June,22,1,2025-06-01,0,1,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,0
HB-022964,Resort Hotel,0,55,2024,April,14,7,2024-04-07,1,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,171.0,,0,Transient,41.4,0,0
HB-075954,City Hotel,1,301,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-108260,City Hotel,0,81,2025,March,12,21,2025-03-21,0,4,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,117.3,0,1
HB-066071,City Hotel,1,172,2025,April,15,13,2025-04-13,1,3,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,123.75,0,1
HB-028077,Resort Hotel,0,1,2024,September,38,20,2024-09-20,0,0,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,195.0,0,Transient,0.0,0,0
HB-000989,Resort Hotel,1,10,2023,August,32,9,2023-08-09,2,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,211.5,0,1
HB-080398,City Hotel,1,34,2023,December,49,8,2023-12-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,0,Transient,90.0,0,0
HB-097859,City Hotel,0,27,2024,September,38,20,2024-09-20,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,288.0,,0,Transient-Party,95.0,0,0
HB-011144,Resort Hotel,1,214,2025,April,17,22,2025-04-22,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,51.97,0,1
HB-075360,City Hotel,1,313,2023,August,34,26,2023-08-26,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-050139,City Hotel,1,146,2024,April,17,24,2024-04-24,2,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,26.0,,50,Transient,95.0,0,0
HB-118105,City Hotel,0,225,2025,August,33,11,2025-08-11,2,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.5,0,2
HB-105144,City Hotel,0,20,2025,January,5,30,2025-01-30,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,410.0,0,Transient-Party,80.0,0,0
HB-018610,Resort Hotel,0,112,2023,November,45,12,2023-11-12,4,9,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,314.0,,0,Contract,66.42,0,1
HB-080648,City Hotel,0,64,2023,November,47,20,2023-11-20,0,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,10.0,,0,Transient,79.2,0,2
HB-068838,City Hotel,1,28,2025,May,21,21,2025-05-21,2,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,190.0,0,2
HB-052305,City Hotel,1,177,2024,June,23,3,2024-06-03,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,119.0,,0,Transient-Party,100.0,0,0
HB-047745,City Hotel,1,55,2024,March,9,2,2024-03-02,0,3,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,69.5,0,0
HB-049038,City Hotel,1,95,2024,April,14,5,2024-04-05,0,2,1,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,72.8,0,0
HB-083621,City Hotel,0,0,2024,February,6,8,2024-02-08,1,0,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,80.0,0,0
HB-069011,City Hotel,1,147,2025,May,21,24,2025-05-24,0,4,2,3.0,0,BB,BEL,Direct,Direct,0,0,0,G,G,0,No Deposit,14.0,,0,Transient,250.0,0,0
HB-081196,City Hotel,0,24,2023,December,49,4,2023-12-04,0,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Contract,55.0,0,0
HB-098288,City Hotel,0,100,2024,September,39,25,2024-09-25,2,1,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,80.75,0,0
HB-116052,City Hotel,0,414,2025,July,28,13,2025-07-13,0,2,1,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,B,1,No Deposit,6.0,,0,Transient-Party,95.5,0,0
HB-021166,Resort Hotel,0,7,2024,February,7,17,2024-02-17,0,3,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient-Party,43.0,0,1
HB-084670,City Hotel,0,115,2024,February,9,27,2024-02-27,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,134.0,,0,Transient-Party,87.0,0,0
HB-020755,Resort Hotel,0,0,2024,February,6,5,2024-02-05,2,2,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,45.0,0,0
HB-105172,City Hotel,0,1,2025,January,5,31,2025-01-31,0,1,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.0,0,2
HB-101084,City Hotel,0,48,2024,November,45,4,2024-11-04,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.2,0,2
HB-034101,Resort Hotel,0,32,2025,March,11,10,2025-03-10,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,G,G,2,No Deposit,250.0,,0,Transient,132.5,0,2
HB-071501,City Hotel,1,310,2025,July,27,6,2025-07-06,1,3,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.1,0,2
HB-010337,Resort Hotel,1,49,2025,February,9,28,2025-02-28,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,332.0,,0,Transient,35.0,0,0
HB-004694,Resort Hotel,1,66,2024,March,13,28,2024-03-28,1,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,52.0,0,2
HB-118081,City Hotel,0,504,2025,August,33,12,2025-08-12,2,1,2,0.0,0,BB,AUS,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,1
HB-025897,Resort Hotel,0,59,2024,July,28,13,2024-07-13,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,202.0,1,0
HB-100828,City Hotel,0,98,2024,October,44,30,2024-10-30,2,1,2,0.0,0,BB,SVN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.6,0,1
HB-054847,City Hotel,0,213,2024,July,30,28,2024-07-28,0,2,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,B,B,1,No Deposit,14.0,,0,Transient,83.92,0,0
HB-010060,Resort Hotel,1,238,2025,February,7,10,2025-02-10,0,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,155.0,,0,Transient,54.0,0,0
HB-030391,Resort Hotel,0,67,2024,November,47,18,2024-11-18,1,2,2,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,411.0,,0,Transient-Party,50.0,0,0
HB-038218,Resort Hotel,0,87,2025,July,28,10,2025-07-10,1,1,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,202.0,0,1
HB-057658,City Hotel,1,287,2024,September,39,29,2024-09-29,1,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,100.3,0,0
HB-024102,Resort Hotel,0,5,2024,May,19,11,2024-05-11,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,84.6,0,0
HB-095800,City Hotel,0,221,2024,August,34,22,2024-08-22,1,1,3,0.0,0,BB,TUR,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,22.0,,0,Transient,96.9,0,1
HB-048869,City Hotel,0,88,2024,March,13,31,2024-03-31,2,6,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,72.25,0,1
HB-084609,City Hotel,0,34,2024,February,8,22,2024-02-22,2,5,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,80.04,1,0
HB-031407,Resort Hotel,0,156,2024,December,51,19,2024-12-19,3,6,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,78.2,0,1
HB-112602,City Hotel,0,208,2025,May,21,24,2025-05-24,0,2,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,114.4,0,0
HB-101735,City Hotel,0,17,2024,November,46,14,2024-11-14,1,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,7.0,,0,Transient,67.76,0,1
HB-093470,City Hotel,0,69,2024,July,29,19,2024-07-19,0,3,2,2.0,0,BB,NLD,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,9.0,,0,Transient,180.3,0,2
HB-074506,City Hotel,1,325,2023,September,36,7,2023-09-07,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-054246,City Hotel,1,113,2024,July,28,10,2024-07-10,1,0,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,103.5,0,0
HB-056390,City Hotel,1,41,2024,September,36,4,2024-09-04,2,3,2,2.0,0,BB,DEU,Online TA,TA/TO,0,0,0,B,B,3,No Deposit,9.0,,0,Transient,208.93,0,0
HB-035790,Resort Hotel,0,46,2025,April,18,28,2025-04-28,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient-Party,115.0,0,0
HB-003624,Resort Hotel,1,31,2023,December,52,27,2023-12-27,2,0,1,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,250.0,,0,Transient,80.0,0,0
HB-031196,Resort Hotel,0,98,2024,December,51,16,2024-12-16,0,2,2,0.0,1,BB,PRT,Direct,Direct,0,0,0,A,D,1,No Deposit,250.0,,0,Transient,43.8,1,0
HB-000335,Resort Hotel,0,1,2023,July,28,12,2023-07-12,2,0,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,240.0,,0,Transient,114.5,0,1
HB-117471,City Hotel,0,229,2025,August,31,2,2025-08-02,0,2,1,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,123.3,0,1
HB-068786,City Hotel,1,200,2025,May,21,20,2025-05-20,2,1,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,138.6,0,0
HB-104002,City Hotel,0,6,2024,December,1,30,2024-12-30,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,122.48,0,3
HB-059179,City Hotel,1,78,2024,October,43,21,2024-10-21,2,2,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,132.3,0,0
HB-092820,City Hotel,0,79,2024,July,27,6,2024-07-06,2,5,3,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,9.0,,0,Transient,146.96,0,2
HB-014779,Resort Hotel,1,275,2023,October,40,4,2023-10-04,2,0,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,208.0,,0,Transient,50.0,0,0
HB-081965,City Hotel,1,272,2024,August,32,5,2024-08-05,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,41,Transient,65.0,0,0
HB-076526,City Hotel,1,195,2023,September,37,17,2023-09-17,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,20.0,,0,Transient,48.0,0,0
HB-097266,City Hotel,0,130,2024,September,37,10,2024-09-10,2,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,28.0,,0,Transient,99.95,0,0
HB-066140,City Hotel,1,125,2025,April,16,14,2025-04-14,2,2,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,103.5,0,0
HB-118814,City Hotel,0,111,2025,August,34,20,2025-08-20,2,4,2,0.0,0,BB,CHN,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,160.0,0,3
HB-055636,City Hotel,1,405,2024,August,33,18,2024-08-18,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-060299,City Hotel,1,277,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-070563,City Hotel,1,120,2025,June,25,18,2025-06-18,2,2,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.86,0,1
HB-069530,City Hotel,1,174,2025,June,22,1,2025-06-01,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,110.0,0,0
HB-114090,City Hotel,0,423,2025,June,24,14,2025-06-14,0,3,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,2,No Deposit,229.0,,0,Transient-Party,112.67,0,1
HB-011794,Resort Hotel,1,279,2025,May,22,30,2025-05-30,0,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,80.1,0,2
HB-096978,City Hotel,0,183,2024,September,36,8,2024-09-08,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,44.0,,0,Transient-Party,110.0,0,1
HB-112547,City Hotel,0,31,2025,May,21,22,2025-05-22,1,2,1,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,7.0,,0,Transient,144.4,0,1
HB-093126,City Hotel,0,5,2024,July,28,14,2024-07-14,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,121.43,0,1
HB-059248,City Hotel,0,292,2024,October,43,23,2024-10-23,2,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,B,B,3,No Deposit,9.0,,0,Transient-Party,163.63,0,1
HB-071790,City Hotel,1,229,2025,July,28,12,2025-07-12,1,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-033393,Resort Hotel,0,15,2025,February,8,17,2025-02-17,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,467.0,,0,Transient,39.74,0,0
HB-064271,City Hotel,1,27,2025,March,10,3,2025-03-03,2,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,91.8,0,0
HB-035187,Resort Hotel,0,31,2025,April,15,13,2025-04-13,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,C,C,1,No Deposit,240.0,,0,Transient,152.0,1,2
HB-104318,City Hotel,0,23,2025,January,2,11,2025-01-11,0,0,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,5,No Deposit,9.0,,0,Transient,0.0,0,2
HB-064024,City Hotel,1,21,2025,February,9,26,2025-02-26,2,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,91.8,0,0
HB-028582,Resort Hotel,0,14,2024,October,40,3,2024-10-03,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,40.0,1,0
HB-083336,City Hotel,0,4,2024,January,4,25,2024-01-25,1,3,1,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,63.8,0,0
HB-045744,City Hotel,0,98,2023,November,47,23,2023-11-23,1,2,1,0.0,0,BB,IND,Groups,TA/TO,0,0,0,A,D,0,No Deposit,37.0,,0,Transient-Party,70.0,0,0
HB-026356,Resort Hotel,0,132,2024,July,30,23,2024-07-23,2,5,2,0.0,0,BB,ITA,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,151.5,0,0
HB-039574,Resort Hotel,0,8,2025,August,33,17,2025-08-17,2,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,171.2,0,1
HB-080948,City Hotel,0,12,2023,November,47,23,2023-11-23,1,5,1,0.0,0,BB,ISR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,84.0,0,0
HB-027596,Resort Hotel,0,55,2024,August,33,18,2024-08-18,4,12,2,0.0,0,BB,NOR,Direct,Direct,0,0,0,F,E,0,No Deposit,250.0,,0,Transient,203.29,0,1
HB-104383,City Hotel,0,4,2025,January,2,10,2025-01-10,0,2,1,0.0,0,BB,ITA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,405.0,0,Transient-Party,70.0,0,0
HB-008681,Resort Hotel,1,131,2024,October,41,9,2024-10-09,2,1,2,0.0,0,BB,PRT,Groups,Corporate,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,55.0,0,0
HB-089813,City Hotel,0,87,2024,May,21,21,2024-05-21,2,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.85,0,1
HB-039837,Resort Hotel,0,40,2025,August,35,28,2025-08-28,1,1,2,1.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,204.16,0,3
HB-000839,Resort Hotel,1,136,2023,July,31,31,2023-07-31,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,172.0,0,0
HB-005674,Resort Hotel,1,122,2024,May,19,9,2024-05-09,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,64.09,0,0
HB-103670,City Hotel,0,1,2024,December,52,27,2024-12-27,0,2,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,D,E,1,No Deposit,397.0,,0,Transient,108.0,0,0
HB-070005,City Hotel,1,169,2025,June,23,8,2025-06-08,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,170.0,0,0
HB-071931,City Hotel,1,51,2025,July,29,15,2025-07-15,2,2,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,232.5,0,1
HB-058669,City Hotel,1,237,2024,October,41,13,2024-10-13,1,3,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,134.73,0,0
HB-056016,City Hotel,0,162,2024,August,35,26,2024-08-26,2,3,1,1.0,0,BB,BEL,Direct,Direct,0,0,0,B,B,2,No Deposit,,,0,Transient-Party,85.5,0,1
HB-036830,Resort Hotel,0,345,2025,May,22,26,2025-05-26,2,2,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,241.0,,0,Transient,92.4,0,1
HB-096198,City Hotel,0,5,2024,August,35,27,2024-08-27,2,1,2,0.0,0,BB,AUT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,114.92,0,0
HB-101224,City Hotel,0,44,2024,November,45,5,2024-11-05,2,2,2,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,112.0,0,0
HB-006406,Resort Hotel,1,14,2024,June,23,8,2024-06-08,2,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,137.67,0,0
HB-077476,City Hotel,0,0,2023,September,38,20,2023-09-20,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,133.0,0,0
HB-054915,City Hotel,1,139,2024,July,31,30,2024-07-30,2,1,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,192.3,0,1
HB-096088,City Hotel,0,7,2024,August,35,26,2024-08-26,1,2,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,124.67,0,1
HB-037555,Resort Hotel,0,158,2025,June,24,11,2025-06-11,4,7,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,70.4,0,1
HB-085355,City Hotel,0,133,2024,March,11,11,2024-03-11,1,2,2,0.0,0,BB,USA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,129.0,,0,Transient-Party,84.33,0,1
HB-039622,Resort Hotel,0,290,2025,August,34,20,2025-08-20,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,140.38,0,1
HB-009692,Resort Hotel,1,155,2024,December,52,26,2024-12-26,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,37.8,0,2
HB-034889,Resort Hotel,0,9,2025,April,15,7,2025-04-07,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,115.0,0,2
HB-075806,City Hotel,1,330,2023,September,37,12,2023-09-12,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-086014,City Hotel,0,176,2024,March,12,20,2024-03-20,2,4,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.0,0,1
HB-018369,Resort Hotel,0,0,2023,November,46,17,2023-11-17,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,88.0,0,Transient,35.0,1,0
HB-025432,Resort Hotel,0,2,2024,June,26,25,2024-06-25,1,1,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,241.0,,0,Transient,122.23,1,1
HB-090133,City Hotel,0,14,2024,May,22,30,2024-05-30,1,3,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,80.75,0,0
HB-024582,Resort Hotel,0,70,2024,May,20,19,2024-05-19,2,5,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Contract,48.75,0,0
HB-051933,City Hotel,0,316,2024,May,21,26,2024-05-26,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,110.0,0,0
HB-052361,City Hotel,1,275,2024,June,23,4,2024-06-04,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,5.0,,69,Transient,62.8,0,0
HB-016082,Resort Hotel,0,36,2023,August,32,9,2023-08-09,2,3,1,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,240.0,,0,Transient,163.8,0,1
HB-066594,City Hotel,1,393,2025,April,17,22,2025-04-22,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-005535,Resort Hotel,1,199,2024,May,18,2,2024-05-02,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,85.0,0,0
HB-018500,Resort Hotel,0,7,2023,November,47,21,2023-11-21,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,E,0,No Deposit,,342.0,0,Transient-Party,32.0,0,0
HB-040145,City Hotel,0,96,2023,July,28,11,2023-07-11,2,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-115884,City Hotel,0,123,2025,July,28,9,2025-07-09,2,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,1
HB-067517,City Hotel,1,148,2025,May,18,4,2025-05-04,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,171.0,,0,Transient,95.0,0,0
HB-015232,Resort Hotel,0,48,2024,October,44,29,2024-10-29,2,5,1,0.0,0,BB,IRL,Online TA,TA/TO,1,0,1,A,A,0,No Deposit,240.0,,0,Transient-Party,42.14,0,1
HB-026521,Resort Hotel,0,174,2024,July,30,27,2024-07-27,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,100.8,0,0
HB-034964,Resort Hotel,0,152,2025,April,14,5,2025-04-05,0,4,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,1,No Deposit,,223.0,0,Transient-Party,53.25,1,0
HB-054400,City Hotel,1,91,2024,July,28,14,2024-07-14,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,118.8,0,0
HB-112549,City Hotel,0,115,2025,May,21,22,2025-05-22,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.0,0,4
HB-116478,City Hotel,0,177,2025,July,29,18,2025-07-18,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,0
HB-006067,Resort Hotel,0,223,2024,May,21,24,2024-05-24,1,5,2,0.0,0,BB,GBR,Groups,Direct,0,0,0,A,A,2,No Deposit,,223.0,0,Transient-Party,67.67,0,0
HB-110987,City Hotel,0,35,2025,May,18,1,2025-05-01,1,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,99.0,0,0
HB-025985,Resort Hotel,0,12,2024,July,28,11,2024-07-11,2,5,3,0.0,0,HB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,240.86,0,1
HB-078755,City Hotel,0,12,2023,October,41,12,2023-10-12,1,3,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,2,No Deposit,95.0,,0,Transient-Party,100.0,0,0
HB-047781,City Hotel,1,35,2024,March,9,3,2024-03-03,1,3,2,0.0,0,SC,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,71.1,0,0
HB-083568,City Hotel,0,11,2024,February,6,6,2024-02-06,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.0,0,1
HB-103982,City Hotel,0,269,2024,December,52,29,2024-12-29,2,3,1,0.0,0,BB,SWE,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,70.0,0,0
HB-106962,City Hotel,0,49,2025,March,9,2,2025-03-02,0,3,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,77.0,0,0
HB-039334,Resort Hotel,0,5,2025,August,33,13,2025-08-13,2,0,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,210.0,0,1
HB-118569,City Hotel,0,153,2025,August,33,15,2025-08-15,2,5,3,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,6.0,,0,Transient,125.1,0,0
HB-067374,City Hotel,1,32,2025,May,18,3,2025-05-03,0,1,2,0.0,0,BB,ZAF,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,134.1,0,0
HB-053282,City Hotel,1,245,2024,June,25,17,2024-06-17,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,0,Transient,75.0,0,0
HB-025148,Resort Hotel,0,73,2024,June,24,15,2024-06-15,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,C,2,No Deposit,240.0,,0,Transient,116.0,0,0
HB-076340,City Hotel,0,271,2023,July,28,15,2023-07-15,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-013324,Resort Hotel,1,116,2025,August,32,9,2025-08-09,2,8,2,1.0,0,HB,PRT,Direct,Direct,0,0,0,F,F,3,No Deposit,250.0,,0,Transient,392.0,0,0
HB-087732,City Hotel,0,6,2024,April,17,24,2024-04-24,1,0,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,146.0,1,2
HB-002101,Resort Hotel,0,24,2023,October,39,1,2023-10-01,2,5,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,103.0,1,1
HB-013787,Resort Hotel,1,207,2025,August,35,30,2025-08-30,2,4,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,152.33,0,1
HB-031111,Resort Hotel,0,0,2025,March,9,1,2025-03-01,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,1,0,1,A,D,0,No Deposit,314.0,,0,Transient,43.2,0,0
HB-014353,Resort Hotel,0,0,2025,April,14,3,2025-04-03,1,1,1,0.0,0,BB,,Online TA,TA/TO,0,0,1,A,A,0,No Deposit,241.0,,0,Group,61.6,0,1
HB-084949,City Hotel,0,30,2024,March,10,4,2024-03-04,0,2,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient-Party,88.4,0,0
HB-110018,City Hotel,0,3,2025,April,16,16,2025-04-16,2,3,1,0.0,0,BB,PRT,Aviation,Corporate,0,0,0,D,D,1,No Deposit,,153.0,0,Transient,110.0,0,0
HB-040875,City Hotel,1,124,2023,August,32,8,2023-08-08,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-048537,City Hotel,1,161,2024,March,13,25,2024-03-25,1,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,101,Transient,130.0,0,0
HB-065307,City Hotel,1,80,2025,March,14,31,2025-03-31,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,56.0,,0,Transient,90.0,0,0
HB-074065,City Hotel,1,314,2023,August,34,27,2023-08-27,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-012245,Resort Hotel,1,237,2025,June,25,19,2025-06-19,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,315.0,,0,Contract,108.9,0,0
HB-000760,Resort Hotel,0,76,2023,July,30,27,2023-07-27,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,102.72,0,1
HB-102361,City Hotel,0,33,2024,November,48,26,2024-11-26,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,9.0,,0,Transient,113.0,0,1
HB-074101,City Hotel,1,328,2023,September,36,10,2023-09-10,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-021076,Resort Hotel,0,40,2024,February,7,17,2024-02-17,0,1,2,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,E,E,0,No Deposit,,360.0,0,Transient,61.0,0,0
HB-048497,City Hotel,1,34,2024,March,12,24,2024-03-24,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,124.65,0,0
HB-045527,City Hotel,0,88,2023,October,44,31,2023-10-31,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,54.63,0,0
HB-033377,Resort Hotel,0,26,2025,February,7,16,2025-02-16,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,467.0,,0,Transient,59.56,1,0
HB-065059,City Hotel,1,38,2025,March,12,23,2025-03-23,0,3,2,0.0,0,SC,TUR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,91.33,0,0
HB-007590,Resort Hotel,1,196,2024,August,33,15,2024-08-15,2,5,2,1.0,0,HB,PRT,Direct,Direct,0,0,0,E,E,1,No Deposit,,,0,Transient,201.25,0,1
HB-109093,City Hotel,0,2,2025,April,14,5,2025-04-05,0,1,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,150.0,0,1
HB-049973,City Hotel,1,38,2024,April,16,21,2024-04-21,1,3,2,1.0,0,BB,CHL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,118.8,0,0
HB-036817,Resort Hotel,0,203,2025,May,21,25,2025-05-25,2,3,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,2,No Deposit,,223.0,0,Transient-Party,56.2,0,0
HB-113402,City Hotel,0,7,2025,June,23,6,2025-06-06,0,1,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,160.0,0,1
HB-034537,Resort Hotel,0,35,2025,March,12,22,2025-03-22,2,5,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient,80.0,0,2
HB-058553,City Hotel,1,37,2024,October,41,13,2024-10-13,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,105.0,0,0
HB-005607,Resort Hotel,0,209,2024,May,18,5,2024-05-05,1,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.98,0,2
HB-062581,City Hotel,1,46,2025,January,3,15,2025-01-15,4,8,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,96.91,0,0
HB-100537,City Hotel,0,247,2024,October,43,25,2024-10-25,0,4,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.95,0,1
HB-079750,City Hotel,0,15,2023,October,44,31,2023-10-31,2,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,117.0,0,1
HB-118950,City Hotel,0,38,2025,August,34,24,2025-08-24,0,3,2,0.0,0,BB,AUS,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,162.67,0,2
HB-016117,Resort Hotel,0,40,2023,August,32,10,2023-08-10,1,4,2,0.0,0,BB,ARG,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,202.0,0,1
HB-116691,City Hotel,0,175,2025,July,30,21,2025-07-21,1,2,2,1.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.63,0,3
HB-048878,City Hotel,1,71,2024,April,14,1,2024-04-01,0,2,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,87.3,0,0
HB-065833,City Hotel,1,248,2025,April,15,9,2025-04-09,2,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,58.0,,0,Transient-Party,80.0,0,0
HB-073582,City Hotel,1,71,2025,August,35,26,2025-08-26,2,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,200.0,0,0
HB-036371,Resort Hotel,0,121,2025,May,20,16,2025-05-16,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,240.0,,0,Transient-Party,85.0,0,2
HB-051965,City Hotel,0,159,2024,May,21,26,2024-05-26,0,3,2,1.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,B,17,No Deposit,9.0,,0,Transient,119.85,0,1
HB-096697,City Hotel,0,55,2024,August,35,30,2024-08-30,2,6,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,168.0,,0,Transient,85.5,0,0
HB-035501,Resort Hotel,0,42,2025,April,16,18,2025-04-18,1,5,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,1,No Deposit,,,0,Transient,70.0,0,1
HB-034477,Resort Hotel,0,2,2025,March,13,24,2025-03-24,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,75.0,0,1
HB-091462,City Hotel,0,31,2024,June,25,20,2024-06-20,1,1,2,1.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,22.0,,0,Transient,118.5,0,0
HB-016116,Resort Hotel,0,89,2023,August,32,10,2023-08-10,1,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,F,0,No Deposit,240.0,,0,Transient,154.0,0,2
HB-036161,Resort Hotel,0,5,2025,May,19,11,2025-05-11,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,85.0,0,1
HB-020596,Resort Hotel,0,0,2024,February,5,2,2024-02-02,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,1,No Deposit,,,0,Transient,58.0,0,0
HB-045253,City Hotel,0,45,2023,October,43,24,2023-10-24,2,2,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,15.0,,0,Transient,76.77,0,0
HB-005763,Resort Hotel,0,213,2024,May,19,12,2024-05-12,2,8,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,40.0,,0,Transient-Party,58.95,0,2
HB-072354,City Hotel,1,162,2025,July,30,26,2025-07-26,2,8,1,1.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,22.0,,0,Transient,96.91,0,0
HB-059476,City Hotel,1,249,2024,October,44,28,2024-10-28,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.3,0,0
HB-017092,Resort Hotel,0,262,2023,September,38,21,2023-09-21,1,3,1,0.0,0,HB,PRT,Groups,Corporate,0,0,0,A,A,1,No Deposit,183.0,,0,Transient-Party,65.5,0,0
HB-110849,City Hotel,0,140,2025,April,18,28,2025-04-28,2,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,119.0,,0,Transient-Party,130.0,0,1
HB-064848,City Hotel,1,108,2025,March,12,17,2025-03-17,2,2,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,134.3,0,0
HB-110735,City Hotel,0,110,2025,April,17,27,2025-04-27,1,3,2,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,0
HB-070305,City Hotel,1,201,2025,June,24,14,2025-06-14,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-057770,City Hotel,1,315,2024,September,40,30,2024-09-30,1,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,,69,Transient,160.0,0,0
HB-027991,Resort Hotel,0,220,2024,September,37,10,2024-09-10,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,88.74,0,1
HB-093514,City Hotel,0,119,2024,July,29,19,2024-07-19,0,4,2,0.0,0,BB,AUS,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,8.0,,0,Transient,116.45,0,1
HB-078303,City Hotel,0,5,2025,May,22,31,2025-05-31,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,14,A,A,0,No Deposit,,40.0,0,Transient,67.0,1,2
HB-090161,City Hotel,0,0,2024,June,22,2,2024-06-02,0,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,139.0,0,0
HB-003324,Resort Hotel,0,66,2023,December,49,5,2023-12-05,1,1,2,0.0,0,FB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,155.0,,0,Transient-Party,64.0,0,0
HB-037090,Resort Hotel,0,69,2025,June,23,3,2025-06-03,2,2,2,0.0,0,BB,ARG,Online TA,TA/TO,0,0,0,C,C,1,No Deposit,240.0,,0,Transient-Party,167.0,1,0
HB-026826,Resort Hotel,0,17,2024,August,32,8,2024-08-08,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,224.0,0,0
HB-023320,Resort Hotel,0,4,2024,April,16,20,2024-04-20,0,2,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,D,D,1,No Deposit,,,0,Transient,79.0,1,0
HB-074520,City Hotel,1,332,2023,September,37,14,2023-09-14,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-007540,Resort Hotel,1,82,2024,August,33,13,2024-08-13,2,5,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,201.86,0,0
HB-111077,City Hotel,0,83,2025,May,18,4,2025-05-04,0,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,126.0,0,3
HB-096778,City Hotel,0,62,2024,September,36,5,2024-09-05,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,B,0,No Deposit,9.0,,0,Transient,115.5,0,1
HB-045183,City Hotel,0,43,2023,October,42,21,2023-10-21,2,4,2,2.0,0,BB,CHE,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Contract,166.5,0,1
HB-038222,Resort Hotel,0,121,2025,July,27,5,2025-07-05,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,123.5,0,0
HB-014396,Resort Hotel,0,4,2025,May,21,22,2025-05-22,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,110.0,0,0
HB-084180,City Hotel,0,15,2024,February,8,19,2024-02-19,0,1,2,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,A,1,No Deposit,,67.0,0,Transient-Party,81.0,1,0
HB-021801,Resort Hotel,0,5,2024,March,10,9,2024-03-09,0,2,2,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient-Party,48.0,0,0
HB-036098,Resort Hotel,0,3,2025,May,19,7,2025-05-07,2,1,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,175.0,,0,Transient,65.33,0,0
HB-041173,City Hotel,1,39,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,101.5,0,0
HB-074295,City Hotel,1,330,2023,September,37,12,2023-09-12,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-077521,City Hotel,1,32,2023,October,42,19,2023-10-19,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,0,No Deposit,9.0,,0,Contract,96.3,0,0
HB-087418,City Hotel,0,2,2024,April,16,17,2024-04-17,2,1,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,99.0,0,0
HB-018123,Resort Hotel,0,27,2023,November,44,3,2023-11-03,0,3,2,0.0,0,HB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,65.7,0,2
HB-050766,City Hotel,1,61,2024,May,19,7,2024-05-07,2,1,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,159.3,0,0
HB-068740,City Hotel,1,75,2025,May,21,20,2025-05-20,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,90.0,0,0
HB-009150,Resort Hotel,1,142,2024,October,44,29,2024-10-29,2,5,3,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,103.57,0,0
HB-036742,Resort Hotel,0,388,2025,May,21,25,2025-05-25,0,3,2,0.0,0,BB,CN,Groups,TA/TO,0,0,0,E,E,0,No Deposit,96.0,,0,Transient-Party,72.0,0,0
HB-118665,City Hotel,0,96,2025,August,34,20,2025-08-20,2,2,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,80.1,0,1
HB-008596,Resort Hotel,1,383,2024,October,40,6,2024-10-06,1,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,315.0,,0,Transient-Party,48.0,0,0
HB-001408,Resort Hotel,0,39,2023,August,35,28,2023-08-28,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,240.0,,0,Transient,120.6,0,2
HB-098797,City Hotel,0,37,2024,October,40,2,2024-10-02,2,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,126.0,0,1
HB-034896,Resort Hotel,0,4,2025,April,15,7,2025-04-07,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,85.0,0,3
HB-033519,Resort Hotel,0,125,2025,February,6,4,2025-02-04,6,15,1,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,242.0,,0,Transient,48.8,0,1
HB-045021,City Hotel,1,102,2023,October,42,16,2023-10-16,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-024981,Resort Hotel,0,26,2024,June,23,6,2024-06-06,1,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,117.0,1,0
HB-058384,City Hotel,1,182,2024,October,41,12,2024-10-12,0,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.1,0,0
HB-074839,City Hotel,1,335,2023,September,37,17,2023-09-17,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,5.0,,0,Transient,85.0,0,0
HB-103408,City Hotel,0,21,2024,December,51,19,2024-12-19,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.4,0,0
HB-071813,City Hotel,1,414,2025,July,28,13,2025-07-13,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,B,1,No Deposit,6.0,,0,Transient-Party,80.0,0,0
HB-043909,City Hotel,1,87,2023,September,39,25,2023-09-25,2,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-031157,Resort Hotel,0,16,2024,December,51,16,2024-12-16,0,1,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,43.0,0,2
HB-113767,City Hotel,0,330,2025,June,24,9,2025-06-09,1,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,2
HB-045746,City Hotel,0,98,2023,November,47,23,2023-11-23,1,2,1,0.0,0,BB,ROU,Groups,TA/TO,0,0,0,A,D,0,No Deposit,37.0,,0,Transient-Party,70.0,0,0
HB-060757,City Hotel,1,95,2024,November,47,20,2024-11-20,2,0,2,0.0,0,BB,HUN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,84.6,0,2
HB-053410,City Hotel,1,193,2024,June,25,20,2024-06-20,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,162.0,,39,Transient,120.0,0,0
HB-037949,Resort Hotel,0,1,2025,July,27,3,2025-07-03,1,0,2,0.0,0,BB,USA,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient,173.0,0,1
HB-039319,Resort Hotel,0,0,2025,August,32,9,2025-08-09,2,4,2,0.0,0,BB,NOR,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,192.0,0,0
HB-086964,City Hotel,0,89,2024,April,15,8,2024-04-08,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,65.13,0,1
HB-024797,Resort Hotel,0,137,2024,May,22,29,2024-05-29,2,4,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,175.0,,0,Transient,62.48,0,1
HB-031376,Resort Hotel,0,0,2024,December,52,26,2024-12-26,0,0,2,0.0,0,BB,PRT,Corporate,Corporate,1,0,0,D,I,0,No Deposit,,270.0,0,Transient,0.0,0,1
HB-079351,City Hotel,0,32,2023,October,43,24,2023-10-24,1,1,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,120.0,0,1
HB-079342,City Hotel,0,32,2023,October,43,24,2023-10-24,1,1,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Contract,136.0,0,1
HB-084796,City Hotel,0,5,2024,March,9,1,2024-03-01,0,3,1,0.0,0,BB,NLD,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,51.0,0,0
HB-039517,Resort Hotel,0,280,2025,August,33,15,2025-08-15,0,5,3,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,15.0,,0,Transient,147.0,0,3
HB-016636,Resort Hotel,0,232,2023,August,34,22,2023-08-22,4,10,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,156.0,,0,Contract,67.58,0,1
HB-028432,Resort Hotel,0,542,2024,September,39,26,2024-09-26,2,5,2,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,E,E,0,No Deposit,253.0,,0,Transient-Party,89.0,0,2
HB-102641,City Hotel,0,313,2024,December,48,1,2024-12-01,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,91.8,0,1
HB-082379,City Hotel,1,108,2024,March,12,18,2024-03-18,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,154.0,,0,Transient,80.0,0,0
HB-097530,City Hotel,0,41,2024,September,37,14,2024-09-14,0,4,1,0.0,0,BB,IRL,Groups,TA/TO,0,0,0,A,A,2,No Deposit,86.0,,0,Transient-Party,108.0,0,0
HB-065526,City Hotel,1,89,2025,April,14,5,2025-04-05,0,2,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,117.0,0,1
HB-099454,City Hotel,0,3,2024,October,41,11,2024-10-11,0,2,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,154.0,0,1
HB-042336,City Hotel,0,2,2023,September,36,5,2023-09-05,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,75.0,0,0
HB-041535,City Hotel,0,46,2023,August,33,17,2023-08-17,1,1,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,60.0,0,0
HB-016458,Resort Hotel,0,88,2023,August,34,23,2023-08-23,2,5,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,E,F,1,No Deposit,,,0,Transient,170.5,0,3
HB-099915,City Hotel,0,52,2024,October,42,15,2024-10-15,2,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,148.5,0,2
HB-001248,Resort Hotel,1,36,2023,August,34,21,2023-08-21,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,178.33,0,1
HB-103609,City Hotel,0,39,2024,December,52,27,2024-12-27,0,1,2,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,220.0,,0,Transient-Party,65.0,0,1
HB-075596,City Hotel,0,257,2023,July,26,1,2023-07-01,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,101.5,0,0
HB-017436,Resort Hotel,0,236,2023,October,40,4,2023-10-04,2,5,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,5.0,,0,Transient,50.03,0,1
HB-065400,City Hotel,1,0,2025,April,14,3,2025-04-03,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,12.0,0,0
HB-049399,City Hotel,1,197,2024,April,15,12,2024-04-12,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,106.2,0,2
HB-095996,City Hotel,0,11,2024,August,34,24,2024-08-24,0,3,4,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,7.0,,0,Transient,227.15,0,1
HB-105367,City Hotel,0,66,2025,February,6,4,2025-02-04,1,1,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,71.28,0,1
HB-022033,Resort Hotel,0,23,2024,March,11,13,2024-03-13,2,2,3,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,76.75,0,1
HB-012955,Resort Hotel,1,196,2025,July,30,24,2025-07-24,3,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,153.75,0,1
HB-019968,Resort Hotel,0,0,2024,January,3,20,2024-01-20,0,2,2,0.0,0,BB,PRT,Direct,Direct,1,0,1,A,D,0,No Deposit,,,0,Transient,45.0,0,1
HB-044252,City Hotel,0,164,2023,October,40,2,2023-10-02,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,19.0,,0,Transient-Party,100.0,0,0
HB-109658,City Hotel,0,183,2025,April,15,10,2025-04-10,1,4,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,7.0,,0,Transient,138.26,0,2
HB-051596,City Hotel,1,172,2024,May,21,22,2024-05-22,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,115.2,0,0
HB-042327,City Hotel,0,22,2023,September,36,4,2023-09-04,2,4,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,E,1,No Deposit,9.0,,0,Contract,122.5,0,3
HB-031812,Resort Hotel,0,20,2025,January,1,2,2025-01-02,1,4,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,115.0,,0,Transient,68.0,0,1
HB-048040,City Hotel,1,33,2024,March,11,13,2024-03-13,2,2,2,0.0,0,SC,TUR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,71.1,0,0
HB-106954,City Hotel,0,4,2025,March,9,2,2025-03-02,0,3,1,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,62.4,0,0
HB-048318,City Hotel,0,74,2024,March,12,20,2024-03-20,2,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,82.45,0,1
HB-097067,City Hotel,0,18,2024,September,37,9,2024-09-09,1,2,2,2.0,0,BB,NLD,Online TA,TA/TO,0,0,0,B,B,2,No Deposit,9.0,,0,Transient,145.0,0,1
HB-023740,Resort Hotel,0,4,2024,April,18,30,2024-04-30,1,1,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,6.0,,0,Transient,58.0,1,3
HB-031822,Resort Hotel,0,34,2025,January,2,6,2025-01-06,0,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,55.0,1,2
HB-108697,City Hotel,0,1,2025,March,13,30,2025-03-30,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.0,0,0
HB-052331,City Hotel,1,49,2024,June,23,3,2024-06-03,1,2,3,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,150.3,0,0
HB-038018,Resort Hotel,0,165,2025,July,27,3,2025-07-03,1,3,2,1.0,0,HB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,250.0,,0,Transient,172.2,0,3
HB-087386,City Hotel,0,3,2024,April,16,17,2024-04-17,2,0,2,0.0,0,BB,EST,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,84.65,1,0
HB-096969,City Hotel,0,183,2024,September,36,8,2024-09-08,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,44.0,,0,Transient-Party,110.0,0,1
HB-021786,Resort Hotel,0,16,2024,March,10,9,2024-03-09,0,2,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-083367,City Hotel,0,58,2024,January,4,27,2024-01-27,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,87.0,,0,Transient-Party,80.0,0,0
HB-103597,City Hotel,0,43,2024,December,52,27,2024-12-27,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,83.0,,0,Transient,74.88,0,0
HB-030993,Resort Hotel,0,1,2024,December,49,8,2024-12-08,0,3,2,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,38.0,,0,Transient-Party,80.0,0,0
HB-066504,City Hotel,1,130,2025,April,17,21,2025-04-21,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,286.0,,0,Transient,95.0,0,0
HB-010034,Resort Hotel,1,8,2025,February,6,8,2025-02-08,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,2
HB-068814,City Hotel,1,116,2025,May,21,20,2025-05-20,2,2,2,0.0,0,SC,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,0
HB-042014,City Hotel,0,145,2023,August,35,29,2023-08-29,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,17.0,,0,Transient-Party,94.5,0,0
HB-017603,Resort Hotel,0,7,2023,October,41,12,2023-10-12,1,3,2,0.0,0,FB,PRT,Corporate,Corporate,0,0,0,A,A,0,Non Refund,,174.0,0,Transient-Party,109.0,0,0
HB-046998,City Hotel,0,0,2024,February,5,2,2024-02-02,0,2,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,100.0,1,1
HB-094276,City Hotel,0,4,2024,August,31,1,2024-08-01,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,221.0,0,Transient,79.0,0,0
HB-111396,City Hotel,0,206,2025,May,19,7,2025-05-07,2,1,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,1
HB-093813,City Hotel,0,92,2024,July,29,18,2024-07-18,3,6,3,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,148.7,0,2
HB-016986,Resort Hotel,0,7,2023,September,38,19,2023-09-19,0,1,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,H,H,1,No Deposit,240.0,,0,Transient,160.0,1,0
HB-042900,City Hotel,0,48,2023,September,37,11,2023-09-11,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,60.0,0,0
HB-006659,Resort Hotel,0,322,2024,June,25,22,2024-06-22,0,3,2,0.0,0,HB,POL,Groups,Direct,0,0,0,A,E,0,No Deposit,,,75,Transient-Party,92.0,0,0
HB-082636,City Hotel,0,38,2023,December,52,31,2023-12-31,0,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,B,0,No Deposit,104.0,,0,Transient,118.0,0,1
HB-044128,City Hotel,1,30,2023,September,39,30,2023-09-30,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,121.0,0,0
HB-037152,Resort Hotel,0,2,2025,June,23,8,2025-06-08,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,337.0,0,Transient,75.0,0,0
HB-070429,City Hotel,1,226,2025,June,25,16,2025-06-16,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,,0,Transient,105.0,0,0
HB-016780,Resort Hotel,0,32,2023,September,36,6,2023-09-06,2,4,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,100.87,0,1
HB-098019,City Hotel,0,271,2024,September,38,21,2024-09-21,0,3,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,101.33,0,1
HB-017043,Resort Hotel,0,85,2023,September,37,16,2023-09-16,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,142.0,,0,Transient,105.2,1,0
HB-035886,Resort Hotel,0,84,2025,May,18,2,2025-05-02,0,2,2,0.0,0,BB,CHE,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,127.0,1,1
HB-000587,Resort Hotel,0,82,2023,July,29,20,2023-07-20,2,5,2,0.0,1,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,152.43,0,3
HB-055724,City Hotel,1,303,2024,August,34,19,2024-08-19,2,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,0,Transient-Party,78.0,0,0
HB-093728,City Hotel,0,127,2024,July,30,25,2024-07-25,1,0,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.5,0,1
HB-002816,Resort Hotel,1,155,2023,October,44,31,2023-10-31,0,1,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,36.0,0,0
HB-036847,Resort Hotel,0,1,2025,May,22,30,2025-05-30,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,104.0,,0,Transient,72.0,0,0
HB-024487,Resort Hotel,0,132,2024,May,20,17,2024-05-17,1,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,71.7,1,1
HB-083073,City Hotel,0,2,2024,January,3,16,2024-01-16,0,1,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,78.5,1,1
HB-061690,City Hotel,1,89,2024,December,51,22,2024-12-22,2,3,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,1
HB-078007,City Hotel,0,2,2023,September,39,28,2023-09-28,1,2,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,170.0,0,0
HB-007245,Resort Hotel,0,150,2024,July,31,30,2024-07-30,2,5,3,0.0,0,HB,PRT,Direct,Direct,0,0,0,C,C,0,No Deposit,,,0,Transient,204.0,0,3
HB-088824,City Hotel,0,68,2024,May,19,10,2024-05-10,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient-Party,135.9,1,1
HB-013228,Resort Hotel,1,142,2025,August,32,5,2025-08-05,2,4,2,2.0,0,HB,ITA,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,298.0,0,1
HB-026468,Resort Hotel,0,3,2024,July,31,30,2024-07-30,1,1,2,2.0,0,BB,NOR,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,241.0,,0,Transient,207.05,0,0
HB-044384,City Hotel,0,88,2023,October,40,5,2023-10-05,1,1,1,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,26.0,,77,Transient-Party,90.6,0,0
HB-115117,City Hotel,0,3,2025,July,27,1,2025-07-01,0,1,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,180.0,0,1
HB-038936,Resort Hotel,0,287,2025,July,31,29,2025-07-29,2,3,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient,154.38,0,1
HB-002579,Resort Hotel,0,21,2023,October,42,22,2023-10-22,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Transient-Party,42.5,0,2
HB-059493,City Hotel,1,247,2024,October,44,28,2024-10-28,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,110.0,0,0
HB-026254,Resort Hotel,0,158,2024,July,29,19,2024-07-19,2,5,3,1.0,0,HB,FRA,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,278.0,0,0
HB-020871,Resort Hotel,0,15,2024,February,6,6,2024-02-06,2,5,1,0.0,0,FB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,2,No Deposit,6.0,,0,Transient,57.0,0,0
HB-116550,City Hotel,0,12,2025,July,29,16,2025-07-16,2,4,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,147.67,0,2
HB-081284,City Hotel,0,18,2023,December,49,4,2023-12-04,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Contract,93.88,1,0
HB-091389,City Hotel,0,0,2024,June,25,18,2024-06-18,2,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,129.0,0,2
HB-093900,City Hotel,0,51,2024,July,29,21,2024-07-21,2,5,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,16.0,,0,Transient,87.3,0,0
HB-096047,City Hotel,0,143,2024,August,34,25,2024-08-25,0,3,2,0.0,0,BB,CZE,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,36.0,,0,Transient-Party,100.0,0,0
HB-053347,City Hotel,1,156,2024,June,25,18,2024-06-18,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,96.0,0,0
HB-049026,City Hotel,1,79,2024,April,14,4,2024-04-04,1,5,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,96.62,0,1
HB-013040,Resort Hotel,1,60,2025,July,31,29,2025-07-29,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,205.0,0,1
HB-017882,Resort Hotel,0,11,2023,October,43,23,2023-10-23,0,2,1,0.0,0,BB,CHE,Complementary,TA/TO,0,0,0,F,G,0,No Deposit,253.0,,0,Transient,0.0,0,1
HB-005109,Resort Hotel,0,185,2024,April,16,18,2024-04-18,1,1,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,85.0,0,0
HB-099389,City Hotel,0,260,2024,October,41,7,2024-10-07,2,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,100.3,0,2
HB-063730,City Hotel,1,34,2025,February,8,19,2025-02-19,2,1,2,0.0,0,SC,TZA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.0,0,0
HB-009691,Resort Hotel,1,90,2024,December,52,26,2024-12-26,1,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,37.8,0,1
HB-048558,City Hotel,1,78,2024,March,13,25,2024-03-25,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,154.0,,0,Transient,100.0,0,0
HB-068628,City Hotel,1,24,2025,May,21,19,2025-05-19,0,2,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,128.0,0,1
HB-030288,Resort Hotel,0,12,2025,February,6,3,2025-02-03,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,1,0,2,D,D,0,No Deposit,240.0,,0,Transient,65.0,1,1
HB-078149,City Hotel,1,2,2023,October,40,6,2023-10-06,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,1,0,E,E,2,No Deposit,,,0,Transient,165.0,0,0
HB-075623,City Hotel,1,281,2023,July,30,25,2023-07-25,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-025506,Resort Hotel,0,170,2024,June,26,24,2024-06-24,2,4,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,E,0,No Deposit,156.0,,0,Transient-Party,91.8,0,0
HB-000656,Resort Hotel,0,55,2023,July,30,24,2023-07-24,2,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,147.0,,0,Transient-Party,75.44,0,1
HB-116072,City Hotel,0,414,2025,July,28,13,2025-07-13,0,2,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,B,0,No Deposit,6.0,,0,Transient-Party,122.4,0,1
HB-019995,Resort Hotel,0,0,2024,January,2,11,2024-01-11,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,F,0,No Deposit,,,0,Transient,51.0,0,0
HB-002560,Resort Hotel,0,36,2023,October,42,22,2023-10-22,1,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,C,0,No Deposit,2.0,,0,Contract,42.5,0,0
HB-026738,Resort Hotel,0,141,2024,August,31,3,2024-08-03,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,242.0,,0,Transient,128.0,0,2
HB-090143,City Hotel,0,138,2024,May,22,31,2024-05-31,0,3,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.9,0,1
HB-016539,Resort Hotel,0,35,2023,August,35,29,2023-08-29,2,2,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,96.3,0,2
HB-042564,City Hotel,0,13,2023,September,36,7,2023-09-07,1,2,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,102.33,0,2
HB-039890,Resort Hotel,0,66,2025,August,34,24,2025-08-24,2,5,3,0.0,0,FB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,468.0,,0,Transient,276.46,0,0
HB-058934,City Hotel,1,57,2024,October,42,17,2024-10-17,1,3,3,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,158.4,0,1
HB-045642,City Hotel,0,140,2023,November,46,18,2023-11-18,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,2,No Deposit,29.0,,87,Transient-Party,65.0,0,0
HB-056159,City Hotel,1,227,2024,August,35,30,2024-08-30,2,5,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,92.29,0,0
HB-112306,City Hotel,0,75,2025,May,21,20,2025-05-20,2,1,2,0.0,0,BB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,112.67,0,1
HB-007639,Resort Hotel,1,3,2024,August,33,18,2024-08-18,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,214.0,0,1
HB-101499,City Hotel,0,37,2024,November,45,9,2024-11-09,0,4,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,125.57,0,1
HB-046938,City Hotel,1,86,2024,January,4,28,2024-01-28,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,87.0,0,0
HB-004994,Resort Hotel,0,214,2024,April,15,11,2024-04-11,2,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,52.2,0,2
HB-024592,Resort Hotel,0,70,2024,May,20,19,2024-05-19,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Transient,55.0,0,0
HB-038814,Resort Hotel,0,0,2025,July,31,28,2025-07-28,1,2,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,306.0,,0,Transient,105.31,1,0
HB-067193,City Hotel,1,313,2025,April,18,29,2025-04-29,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient,90.0,0,0
HB-047102,City Hotel,1,3,2024,February,6,7,2024-02-07,2,0,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.0,0,0
HB-058134,City Hotel,1,32,2024,October,40,6,2024-10-06,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,140.0,0,2
HB-034109,Resort Hotel,0,274,2025,March,11,10,2025-03-10,1,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,39.8,0,2
HB-069215,City Hotel,1,255,2025,May,22,27,2025-05-27,2,1,2,0.0,0,SC,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.0,0,0
HB-045657,City Hotel,0,140,2023,November,46,18,2023-11-18,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,29.0,,87,Transient-Party,65.0,0,0
HB-110406,City Hotel,0,137,2025,April,17,24,2025-04-24,1,2,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,105.25,0,0
HB-104649,City Hotel,0,47,2025,January,3,16,2025-01-16,1,2,1,0.0,0,BB,DZA,Groups,TA/TO,0,0,0,A,A,1,No Deposit,19.0,,15,Transient-Party,75.0,0,0
HB-033371,Resort Hotel,0,32,2025,February,7,11,2025-02-11,4,6,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,107.0,1,2
HB-103683,City Hotel,0,24,2024,December,52,25,2024-12-25,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,95.2,0,1
HB-026931,Resort Hotel,0,10,2024,August,32,10,2024-08-10,1,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,251.0,1,0
HB-112941,City Hotel,0,1,2025,May,22,30,2025-05-30,0,1,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,9.0,,0,Transient,206.1,0,0
HB-037937,Resort Hotel,0,0,2025,July,27,2,2025-07-02,1,0,1,0.0,0,HB,KAZ,Online TA,TA/TO,0,0,0,A,F,0,No Deposit,240.0,,0,Transient,156.0,0,2
HB-106614,City Hotel,0,32,2025,February,9,26,2025-02-26,2,0,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,28.0,,0,Transient,75.0,0,0
HB-008841,Resort Hotel,1,181,2024,October,42,16,2024-10-16,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,11.0,,0,Transient,37.0,0,0
HB-058343,City Hotel,1,109,2024,October,41,11,2024-10-11,0,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,0
HB-044974,City Hotel,0,102,2023,October,42,16,2023-10-16,0,2,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient-Party,87.0,0,0
HB-106528,City Hotel,0,1,2025,February,9,25,2025-02-25,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,98.0,1,0
HB-024336,Resort Hotel,0,7,2025,April,14,5,2025-04-05,0,1,1,0.0,0,BB,PRT,Corporate,Direct,1,0,1,A,E,0,No Deposit,,178.0,0,Transient,48.0,0,0
HB-083631,City Hotel,0,10,2024,February,6,6,2024-02-06,2,1,3,0.0,0,BB,ITA,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,132.5,0,2
HB-067886,City Hotel,1,273,2025,May,19,9,2025-05-09,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,84.6,0,0
HB-039678,Resort Hotel,0,10,2025,August,34,22,2025-08-22,0,3,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,275.33,0,2
HB-046239,City Hotel,0,9,2023,December,52,27,2023-12-27,2,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,103.67,0,1
HB-037274,Resort Hotel,0,15,2025,June,24,9,2025-06-09,1,2,2,0.0,0,BB,ARG,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,240.0,,0,Transient,153.5,1,0
HB-047247,City Hotel,0,68,2024,February,7,13,2024-02-13,1,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,78.3,0,1
HB-054678,City Hotel,1,180,2024,July,30,23,2024-07-23,1,1,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,9.0,,0,Transient,112.5,0,0
HB-031683,Resort Hotel,0,0,2025,January,1,3,2025-01-03,0,1,1,0.0,0,BB,CN,Direct,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient,64.0,0,0
HB-075601,City Hotel,0,257,2023,July,26,1,2023-07-01,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,101.5,0,0
HB-005555,Resort Hotel,1,199,2024,May,18,2,2024-05-02,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,85.0,0,0
HB-067081,City Hotel,1,186,2025,April,18,28,2025-04-28,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.5,0,1
HB-075906,City Hotel,1,274,2023,July,29,18,2023-07-18,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-053108,City Hotel,1,239,2024,June,24,15,2024-06-15,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,80,Transient,112.2,0,0
HB-058052,City Hotel,1,275,2024,October,40,5,2024-10-05,1,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,44.0,,0,Transient,90.0,0,0
HB-107092,City Hotel,0,137,2025,March,10,6,2025-03-06,1,1,1,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,E,G,1,No Deposit,37.0,,0,Transient-Party,65.0,0,2
HB-052483,City Hotel,1,213,2024,June,23,7,2024-06-07,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,62,Transient,130.0,0,0
HB-087542,City Hotel,0,95,2024,April,16,20,2024-04-20,0,2,2,0.0,0,HB,AUT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,35.0,,0,Transient-Party,98.0,0,0
HB-061896,City Hotel,1,275,2024,December,52,28,2024-12-28,0,4,2,0.0,0,SC,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,72.25,0,0
HB-035545,Resort Hotel,0,203,2025,April,17,25,2025-04-25,0,2,2,0.0,0,HB,AUT,Groups,TA/TO,0,0,0,A,D,0,No Deposit,502.0,,0,Transient-Party,90.0,0,0
HB-004775,Resort Hotel,1,169,2024,March,13,31,2024-03-31,1,3,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Refundable,,223.0,0,Transient-Party,46.0,0,0
HB-052057,City Hotel,0,143,2024,May,22,29,2024-05-29,2,3,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,99.79,0,0
HB-001416,Resort Hotel,1,22,2023,August,35,28,2023-08-28,2,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,145.0,0,1
HB-092972,City Hotel,0,71,2024,July,28,10,2024-07-10,2,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,122.4,0,1
HB-009419,Resort Hotel,1,232,2024,November,48,26,2024-11-26,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,11.0,,0,Transient,30.0,0,0
HB-025272,Resort Hotel,0,2,2024,June,25,19,2024-06-19,2,0,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,141.0,1,1
HB-044379,City Hotel,0,40,2023,October,40,5,2023-10-05,1,1,2,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,3.0,,40,Transient-Party,70.0,0,0
HB-052260,City Hotel,1,330,2024,June,22,2,2024-06-02,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-040016,Resort Hotel,0,30,2025,August,35,29,2025-08-29,2,5,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,147.01,0,0
HB-045308,City Hotel,0,69,2023,October,43,25,2023-10-25,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,58,Transient-Party,85.67,0,0
HB-091442,City Hotel,0,27,2024,June,25,19,2024-06-19,2,1,2,0.0,0,BB,ROU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,42.0,,0,Transient,95.0,0,0
HB-021805,Resort Hotel,0,15,2024,March,10,9,2024-03-09,0,3,1,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,115.0,,0,Transient-Party,49.0,0,0
HB-064615,City Hotel,1,34,2025,March,11,13,2025-03-13,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Contract,68.0,0,0
HB-033196,Resort Hotel,0,94,2025,February,7,13,2025-02-13,1,3,2,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,152.0,,0,Transient-Party,62.0,0,0
HB-055348,City Hotel,1,398,2024,August,32,11,2024-08-11,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-057498,City Hotel,0,418,2024,September,39,26,2024-09-26,1,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,132.0,,223,Transient-Party,107.0,0,0
HB-086650,City Hotel,0,79,2024,April,14,2,2024-04-02,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,92.65,0,1
HB-112490,City Hotel,0,29,2025,May,21,22,2025-05-22,1,2,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,166.5,0,2
HB-021421,Resort Hotel,0,18,2024,February,9,27,2024-02-27,1,1,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient,80.0,0,0
HB-038296,Resort Hotel,0,1,2025,July,28,13,2025-07-13,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,120.0,0,3
HB-007827,Resort Hotel,1,333,2024,August,35,28,2024-08-28,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,86.79,0,1
HB-040936,City Hotel,0,87,2023,August,32,9,2023-08-09,2,1,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,2
HB-060100,City Hotel,1,95,2024,November,45,5,2024-11-05,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,75.0,0,0
HB-017121,Resort Hotel,0,27,2023,September,38,23,2023-09-23,0,3,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,150.0,1,1
HB-112733,City Hotel,0,180,2025,May,21,25,2025-05-25,0,3,3,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,166.0,0,1
HB-044180,City Hotel,0,164,2023,October,40,2,2023-10-02,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,19.0,,0,Transient-Party,100.0,0,0
HB-025526,Resort Hotel,0,139,2024,June,26,28,2024-06-28,0,3,3,0.0,0,BB,ITA,Direct,Direct,0,0,0,E,F,1,No Deposit,250.0,,0,Transient,159.9,1,0
HB-076018,City Hotel,1,336,2023,September,38,18,2023-09-18,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-075223,City Hotel,1,294,2023,August,32,7,2023-08-07,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-061718,City Hotel,1,313,2024,December,52,23,2024-12-23,3,7,1,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,77.69,0,0
HB-001240,Resort Hotel,0,80,2023,August,33,20,2023-08-20,2,7,2,0.0,0,BB,RUS,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,164.0,0,2
HB-081787,City Hotel,1,117,2024,February,9,29,2024-02-29,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,19.0,,44,Transient,75.0,0,0
HB-068575,City Hotel,1,105,2025,May,21,19,2025-05-19,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-046029,City Hotel,1,198,2023,December,49,5,2023-12-05,2,1,2,0.0,0,HB,ESP,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,90.0,0,0
HB-035211,Resort Hotel,0,16,2025,April,15,13,2025-04-13,0,3,3,1.0,0,HB,ESP,Online TA,TA/TO,0,0,0,H,H,0,No Deposit,240.0,,0,Transient,270.0,1,0
HB-118797,City Hotel,0,205,2025,August,35,25,2025-08-25,0,1,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,99.0,0,0
HB-075822,City Hotel,1,330,2023,September,37,12,2023-09-12,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-099858,City Hotel,0,23,2024,October,42,16,2024-10-16,2,2,2,0.0,0,SC,FIN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,91.63,0,1
HB-059498,City Hotel,1,247,2024,October,44,28,2024-10-28,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,110.0,0,0
HB-045799,City Hotel,0,98,2023,November,47,23,2023-11-23,1,2,1,0.0,0,BB,IRN,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,70.0,0,0
HB-052170,City Hotel,1,60,2024,June,22,1,2024-06-01,0,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,116.1,0,0
HB-017509,Resort Hotel,0,12,2024,May,20,16,2024-05-16,1,0,1,0.0,0,BB,PRT,Online TA,TA/TO,1,0,1,A,A,0,No Deposit,184.0,146.0,0,Group,70.0,0,0
HB-086577,City Hotel,0,6,2024,April,14,5,2024-04-05,0,1,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,8.0,,0,Transient,137.0,0,2
HB-026064,Resort Hotel,0,80,2024,July,29,16,2024-07-16,2,2,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,186.0,0,1
HB-102762,City Hotel,0,3,2024,December,49,5,2024-12-05,1,0,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.0,0,0
HB-062763,City Hotel,1,83,2025,January,4,21,2025-01-21,2,2,1,0.0,0,BB,MAC,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.4,0,2
HB-052723,City Hotel,1,134,2024,June,23,9,2024-06-09,2,5,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.85,0,1
HB-005245,Resort Hotel,1,83,2024,April,17,22,2024-04-22,2,5,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,D,D,0,Non Refund,71.0,,0,Transient,58.0,0,0
HB-028509,Resort Hotel,0,87,2024,September,39,29,2024-09-29,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,241.0,,0,Transient,109.03,0,1
HB-108897,City Hotel,0,30,2025,April,14,1,2025-04-01,1,1,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,150.0,0,0
HB-087682,City Hotel,0,56,2024,April,17,22,2024-04-22,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,119.1,1,1
HB-105780,City Hotel,0,47,2025,February,7,13,2025-02-13,1,1,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,79.2,0,0
HB-035710,Resort Hotel,0,8,2025,April,17,27,2025-04-27,0,3,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,97.0,0,1
HB-095014,City Hotel,0,22,2024,August,33,12,2024-08-12,0,1,2,0.0,0,BB,PRT,Corporate,Direct,0,0,0,A,A,0,No Deposit,,72.0,0,Transient,84.0,0,0
HB-037900,Resort Hotel,0,4,2025,July,27,1,2025-07-01,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient,160.0,0,1
HB-044966,City Hotel,1,180,2023,October,42,16,2023-10-16,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,70.0,0,0
HB-118344,City Hotel,0,10,2025,August,34,18,2025-08-18,0,1,2,1.0,0,BB,USA,Direct,Direct,0,0,0,F,F,0,No Deposit,14.0,,0,Transient,260.0,0,1
HB-015498,Resort Hotel,0,50,2023,July,29,22,2023-07-22,2,6,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,196.0,,0,Transient,135.0,0,0
HB-069593,City Hotel,1,129,2025,June,23,2,2025-06-02,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,154.0,,0,Transient,130.0,0,0
HB-075565,City Hotel,0,257,2023,July,26,1,2023-07-01,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,101.5,0,0
HB-027598,Resort Hotel,0,11,2024,August,35,29,2024-08-29,1,4,2,1.0,0,HB,PRT,Direct,Direct,0,0,0,E,F,1,No Deposit,250.0,,0,Transient,229.2,1,0
HB-030774,Resort Hotel,0,128,2024,December,49,3,2024-12-03,0,1,2,0.0,0,HB,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,64.0,0,1
HB-073047,City Hotel,1,13,2025,August,33,13,2025-08-13,1,0,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,170.0,0,0
HB-088220,City Hotel,0,161,2024,April,18,29,2024-04-29,2,2,2,0.0,0,SC,AUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,95.2,0,1
HB-061638,City Hotel,1,38,2024,December,51,21,2024-12-21,1,4,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.7,0,1
HB-042939,City Hotel,0,13,2023,September,37,11,2023-09-11,0,1,1,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,95.0,0,1
HB-062368,City Hotel,1,552,2025,January,2,12,2025-01-12,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-045882,City Hotel,0,98,2023,November,47,23,2023-11-23,1,3,2,0.0,0,BB,JOR,Groups,TA/TO,0,0,0,A,A,2,No Deposit,37.0,,0,Transient-Party,75.0,0,0
HB-085286,City Hotel,0,21,2024,March,10,10,2024-03-10,0,2,2,0.0,0,BB,NZL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.0,0,1
HB-092520,City Hotel,0,29,2024,July,27,6,2024-07-06,0,2,1,0.0,0,BB,FRA,Corporate,Corporate,0,0,0,D,A,0,No Deposit,,91.0,0,Transient,105.0,0,0
HB-039338,Resort Hotel,0,191,2025,August,32,9,2025-08-09,2,4,2,0.0,0,BB,CN,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,162.0,0,0
HB-041672,City Hotel,1,10,2023,August,34,21,2023-08-21,1,2,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,F,1,No Deposit,9.0,,0,Contract,153.0,0,2
HB-063066,City Hotel,1,122,2025,January,5,28,2025-01-28,2,5,2,1.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,103.7,0,1
HB-116273,City Hotel,0,116,2025,July,29,15,2025-07-15,1,1,2,2.0,0,BB,FIN,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,230.0,0,1
HB-107148,City Hotel,0,14,2025,March,10,4,2025-03-04,2,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,80.24,0,0
HB-059484,City Hotel,1,247,2024,October,44,28,2024-10-28,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,110.0,0,0
HB-044549,City Hotel,0,92,2023,October,40,7,2023-10-07,0,4,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,B,1,No Deposit,3.0,,58,Transient-Party,65.0,0,0
HB-067703,City Hotel,1,64,2025,May,19,6,2025-05-06,2,1,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,189.0,0,0
HB-046352,City Hotel,0,160,2023,December,52,30,2023-12-30,0,3,2,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,111,Transient-Party,70.67,0,0
HB-090187,City Hotel,0,8,2024,May,22,29,2024-05-29,2,3,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,D,A,1,No Deposit,28.0,,0,Transient,120.95,0,0
HB-067127,City Hotel,1,140,2025,April,18,28,2025-04-28,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,119.0,,0,Transient-Party,130.0,0,0
HB-070003,City Hotel,1,169,2025,June,23,8,2025-06-08,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,170.0,0,0
HB-015244,Resort Hotel,0,1,2025,May,20,16,2025-05-16,0,3,2,0.0,0,BB,PRT,Direct,Direct,1,0,1,A,C,0,No Deposit,,,0,Transient,90.25,0,2
HB-024125,Resort Hotel,0,7,2024,October,40,5,2024-10-05,0,4,2,0.0,0,BB,GBR,Groups,Corporate,1,0,3,A,A,1,No Deposit,,405.0,0,Transient-Party,50.0,0,0
HB-099168,City Hotel,0,253,2024,October,41,7,2024-10-07,1,2,1,0.0,0,BB,LUX,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,140.4,0,1
HB-024032,Resort Hotel,0,36,2024,May,19,7,2024-05-07,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,C,2,No Deposit,240.0,,0,Transient,65.0,0,1
HB-109316,City Hotel,0,92,2025,April,15,7,2025-04-07,0,2,3,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,166.5,0,0
HB-071755,City Hotel,1,338,2025,July,28,11,2025-07-11,2,5,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,134.1,0,2
HB-017379,Resort Hotel,0,35,2023,September,39,28,2023-09-28,3,8,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,61.7,0,0
HB-002070,Resort Hotel,0,2,2023,September,39,30,2023-09-30,0,3,1,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,256.0,,0,Transient-Party,58.5,0,0
HB-001150,Resort Hotel,1,47,2023,August,33,15,2023-08-15,6,12,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,181.94,0,0
HB-066112,City Hotel,1,298,2025,April,16,14,2025-04-14,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,90.0,0,0
HB-077617,City Hotel,0,2,2025,April,14,5,2025-04-05,0,1,1,0.0,0,BB,PRT,Complementary,Direct,1,0,3,A,D,0,No Deposit,,45.0,0,Transient,0.0,0,1
HB-006908,Resort Hotel,1,146,2024,July,28,10,2024-07-10,2,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,119.0,0,1
HB-022183,Resort Hotel,0,15,2024,March,12,18,2024-03-18,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,45.0,0,0
HB-111222,City Hotel,0,91,2025,May,19,6,2025-05-06,1,1,2,0.0,0,BB,NOR,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,9.0,,0,Transient,162.0,0,3
HB-016915,Resort Hotel,0,2,2023,September,37,16,2023-09-16,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,99.0,0,2
HB-018410,Resort Hotel,0,4,2024,February,8,22,2024-02-22,1,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,1,0,3,A,D,0,No Deposit,146.0,,0,Group,31.0,1,0
HB-056400,City Hotel,1,243,2024,September,36,4,2024-09-04,4,6,1,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.17,0,0
HB-111341,City Hotel,0,106,2025,May,19,6,2025-05-06,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,85.0,0,0
HB-070455,City Hotel,1,165,2025,June,25,17,2025-06-17,2,1,2,0.0,0,BB,UKR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.5,0,2
HB-060314,City Hotel,1,277,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-079446,City Hotel,1,137,2024,January,4,27,2024-01-27,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,29.0,,45,Transient,70.0,0,0
HB-017238,Resort Hotel,0,67,2023,September,39,28,2023-09-28,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,55.44,0,1
HB-011831,Resort Hotel,1,350,2025,May,22,31,2025-05-31,2,7,2,2.0,0,BB,IRL,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,140.44,0,0
HB-008218,Resort Hotel,1,53,2024,September,38,18,2024-09-18,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,111.75,0,0
HB-022910,Resort Hotel,0,76,2024,April,14,3,2024-04-03,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,241.0,,0,Transient,59.93,0,1
HB-052389,City Hotel,1,102,2024,June,23,5,2024-06-05,1,0,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,65.0,0,0
HB-036337,Resort Hotel,0,13,2025,May,19,11,2025-05-11,2,4,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,240.0,,0,Transient,105.83,0,2
HB-076041,City Hotel,1,336,2023,September,38,18,2023-09-18,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-055168,City Hotel,1,129,2024,August,32,6,2024-08-06,2,3,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,103.5,0,2
HB-114268,City Hotel,0,216,2025,June,24,13,2025-06-13,1,5,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,108.0,0,1
HB-014458,Resort Hotel,0,10,2024,May,19,9,2024-05-09,1,3,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,4,A,C,0,No Deposit,,47.0,0,Transient,42.0,0,0
HB-016304,Resort Hotel,0,115,2023,August,33,16,2023-08-16,2,5,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,E,F,1,No Deposit,240.0,,0,Transient,196.0,0,1
HB-067817,City Hotel,1,7,2025,May,19,8,2025-05-08,1,0,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,3
HB-084913,City Hotel,0,93,2024,March,10,4,2024-03-04,0,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,60.0,0,1
HB-001895,Resort Hotel,0,83,2023,September,38,20,2023-09-20,2,5,2,0.0,0,HB,ESP,Offline TA/TO,TA/TO,0,0,0,D,E,0,No Deposit,134.0,,0,Transient,100.93,0,0
HB-039628,Resort Hotel,0,189,2025,August,33,14,2025-08-14,3,7,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,134.85,0,1
HB-102944,City Hotel,0,58,2024,December,50,9,2024-12-09,0,1,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.2,1,2
HB-003253,Resort Hotel,0,14,2023,November,47,26,2023-11-26,0,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,64.0,1,1
HB-011964,Resort Hotel,1,319,2025,June,23,5,2025-06-05,1,3,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,68.08,0,1
HB-022553,Resort Hotel,0,31,2024,March,13,25,2024-03-25,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,55.6,0,2
HB-085519,City Hotel,0,65,2024,March,11,13,2024-03-13,2,2,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,63.75,0,0
HB-083217,City Hotel,0,1,2024,January,4,24,2024-01-24,1,0,2,0.0,0,SC,ZAF,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.0,0,0
HB-103463,City Hotel,0,45,2024,December,51,22,2024-12-22,0,3,3,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,127.2,0,0
HB-029436,Resort Hotel,0,0,2024,October,43,23,2024-10-23,2,4,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,96.0,,0,Group,46.0,0,1
HB-037351,Resort Hotel,0,147,2025,June,24,10,2025-06-10,2,3,2,0.0,1,BB,IRL,Online TA,TA/TO,0,0,0,G,G,1,No Deposit,240.0,,0,Transient,180.0,0,2
HB-051515,City Hotel,1,22,2024,May,21,20,2024-05-20,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,34.0,,0,Transient,140.0,0,0
HB-070901,City Hotel,1,129,2025,June,26,24,2025-06-24,2,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,30.0,,0,Transient,120.0,0,0
HB-043894,City Hotel,0,192,2023,September,39,25,2023-09-25,2,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,102.0,0,0
HB-104644,City Hotel,0,34,2025,January,3,18,2025-01-18,0,1,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,19.0,,0,Transient-Party,75.0,0,0
HB-044515,City Hotel,0,97,2023,October,40,7,2023-10-07,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-017497,Resort Hotel,0,277,2023,October,40,6,2023-10-06,2,5,2,0.0,0,HB,GBR,Groups,Direct,0,0,0,D,E,0,No Deposit,273.0,,0,Transient-Party,68.74,0,0
HB-065825,City Hotel,1,41,2025,April,15,9,2025-04-09,2,0,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.0,0,0
HB-020319,Resort Hotel,0,1,2024,January,4,22,2024-01-22,0,2,2,0.0,0,BB,USA,Direct,Direct,0,0,0,A,D,0,No Deposit,250.0,,0,Transient,45.0,0,0
HB-068732,City Hotel,1,75,2025,May,21,20,2025-05-20,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,229.0,,0,Transient-Party,90.0,0,0
HB-104482,City Hotel,0,3,2025,January,3,13,2025-01-13,0,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.0,0,1
HB-001085,Resort Hotel,0,76,2023,August,32,13,2023-08-13,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,147.0,,0,Transient,87.91,0,1
HB-067494,City Hotel,1,205,2025,May,18,4,2025-05-04,0,2,2,0.0,0,SC,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,1
HB-090157,City Hotel,0,13,2024,May,22,30,2024-05-30,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,11.0,,0,Transient,85.32,0,0
HB-030549,Resort Hotel,0,52,2024,November,47,19,2024-11-19,2,5,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,30.24,0,0
HB-062973,City Hotel,1,61,2025,January,4,25,2025-01-25,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,326.0,,0,Transient,80.0,0,0
HB-109215,City Hotel,0,94,2025,April,14,1,2025-04-01,2,5,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,157.25,0,0
HB-001905,Resort Hotel,1,185,2023,September,38,21,2023-09-21,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,208.0,,0,Transient-Party,26.0,0,0
HB-096404,City Hotel,0,172,2024,August,35,28,2024-08-28,2,3,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,D,D,2,No Deposit,14.0,,0,Transient-Party,98.6,0,0
HB-069356,City Hotel,1,186,2025,May,22,30,2025-05-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,130.0,0,0
HB-027169,Resort Hotel,0,255,2024,August,34,19,2024-08-19,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,15.0,,0,Transient,100.8,0,0
HB-050556,City Hotel,1,253,2024,May,18,4,2024-05-04,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,55,Transient,90.0,0,0
HB-077577,City Hotel,0,1,2023,September,38,21,2023-09-21,1,1,2,0.0,0,BB,ITA,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,133.0,0,0
HB-107915,City Hotel,0,178,2025,March,12,18,2025-03-18,1,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,28.0,,0,Transient,75.0,0,0
HB-119275,City Hotel,0,213,2025,August,35,28,2025-08-28,1,3,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,K,2,No Deposit,19.0,,0,Transient-Party,104.0,0,0
HB-117738,City Hotel,0,158,2025,July,31,31,2025-07-31,3,6,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,112.5,0,1
HB-070937,City Hotel,1,213,2025,June,26,26,2025-06-26,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,323.0,,0,Transient,115.0,0,0
HB-112689,City Hotel,0,68,2025,May,21,24,2025-05-24,0,3,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,234.0,0,1
HB-050597,City Hotel,1,137,2024,May,18,5,2024-05-05,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.3,0,0
HB-030607,Resort Hotel,0,146,2024,November,45,7,2024-11-07,6,15,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,E,E,1,No Deposit,75.0,,0,Transient,70.6,1,2
HB-023089,Resort Hotel,0,43,2024,April,15,12,2024-04-12,0,3,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,56.21,0,1
HB-001268,Resort Hotel,1,21,2023,August,34,22,2023-08-22,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,C,0,No Deposit,,,0,Transient,172.0,0,0
HB-061655,City Hotel,1,84,2024,December,51,22,2024-12-22,0,1,2,1.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,122.0,0,0
HB-058130,City Hotel,1,238,2024,October,40,6,2024-10-06,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,140.4,0,0
HB-095794,City Hotel,0,195,2024,August,33,17,2024-08-17,2,5,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,112.2,0,2
HB-098694,City Hotel,0,91,2024,September,40,30,2024-09-30,1,2,3,0.0,1,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,3.0,,0,Transient-Party,110.0,0,0
HB-070302,City Hotel,1,201,2025,June,24,14,2025-06-14,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-001464,Resort Hotel,1,346,2023,August,35,30,2023-08-30,4,8,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,171.0,,0,Transient,96.3,0,0
HB-039597,Resort Hotel,0,38,2025,August,34,19,2025-08-19,2,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,5,No Deposit,240.0,,0,Transient,262.0,0,1
HB-022345,Resort Hotel,0,17,2024,March,12,20,2024-03-20,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,171.0,,0,Transient,37.15,0,0
HB-117057,City Hotel,0,67,2025,July,30,26,2025-07-26,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,80.1,0,0
HB-044260,City Hotel,0,164,2023,October,40,2,2023-10-02,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,19.0,,0,Transient-Party,100.0,0,0
HB-044530,City Hotel,0,97,2023,October,40,7,2023-10-07,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,B,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-080841,City Hotel,1,54,2023,December,48,1,2023-12-01,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,1,0,A,A,0,No Deposit,,,0,Transient-Party,81.0,0,0
HB-099737,City Hotel,0,335,2024,October,41,13,2024-10-13,0,3,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,56.0,,0,Transient-Party,80.0,0,0
HB-062007,City Hotel,1,18,2024,December,1,30,2024-12-30,0,2,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,140.0,0,0
HB-055747,City Hotel,1,9,2024,August,34,20,2024-08-20,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.0,0,1
HB-075982,City Hotel,1,301,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-093965,City Hotel,0,139,2024,July,30,28,2024-07-28,0,1,2,0.0,0,SC,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.5,0,1
HB-008656,Resort Hotel,1,368,2024,October,41,8,2024-10-08,4,10,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,143.0,,0,Contract,61.2,0,0
HB-042583,City Hotel,0,9,2023,September,36,7,2023-09-07,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.5,0,2
HB-082649,City Hotel,1,150,2024,March,12,24,2024-03-24,1,3,0,2.0,0,BB,PRT,Online TA,TA/TO,0,1,0,B,B,0,No Deposit,8.0,,0,Transient-Party,6.0,0,1
HB-093007,City Hotel,0,173,2024,July,28,11,2024-07-11,1,3,1,1.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,65.49,0,1
HB-049859,City Hotel,1,265,2024,April,16,20,2024-04-20,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,176,Transient-Party,101.0,0,0
HB-002931,Resort Hotel,0,18,2023,November,45,7,2023-11-07,2,3,1,0.0,0,BB,DZA,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,314.0,,0,Transient,62.16,1,0
HB-051552,City Hotel,1,90,2024,May,21,21,2024-05-21,1,1,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,116.1,0,0
HB-036482,Resort Hotel,0,0,2025,May,21,21,2025-05-21,1,0,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,93.0,0,0
HB-116832,City Hotel,0,7,2025,July,30,23,2025-07-23,2,1,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,1
HB-004108,Resort Hotel,1,32,2024,February,7,13,2024-02-13,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,78.0,0,0
HB-061975,City Hotel,1,78,2024,December,52,29,2024-12-29,1,3,3,1.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,G,G,0,No Deposit,,,0,Transient-Party,274.2,0,0
HB-073118,City Hotel,1,507,2025,August,33,15,2025-08-15,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-036759,Resort Hotel,0,203,2025,May,21,25,2025-05-25,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,223.0,0,Transient-Party,48.0,0,0
HB-087038,City Hotel,0,84,2024,April,15,10,2024-04-10,2,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,58.14,0,0
HB-027977,Resort Hotel,0,109,2024,September,37,13,2024-09-13,0,3,2,1.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,F,2,No Deposit,240.0,,0,Transient,146.5,0,2
HB-023576,Resort Hotel,0,6,2025,March,12,22,2025-03-22,0,1,1,0.0,0,BB,PRT,Direct,TA/TO,1,0,2,A,D,0,No Deposit,,,0,Transient,60.0,0,1
HB-105898,City Hotel,0,19,2025,February,7,14,2025-02-14,0,3,2,0.0,1,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,A,0,No Deposit,168.0,,0,Transient,90.0,0,2
HB-089192,City Hotel,0,64,2024,May,20,17,2024-05-17,0,2,1,0.0,0,BB,DEU,Corporate,TA/TO,0,0,0,A,A,0,No Deposit,,218.0,0,Transient-Party,130.0,0,0
HB-000460,Resort Hotel,0,6,2023,July,29,17,2023-07-17,0,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,0.0,0,1
HB-054339,City Hotel,1,84,2024,July,28,13,2024-07-13,0,4,3,0.0,0,BB,GRC,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,137.7,0,0
HB-051819,City Hotel,1,323,2024,May,21,26,2024-05-26,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-003011,Resort Hotel,1,40,2023,November,45,11,2023-11-11,0,4,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,281.0,,0,Transient-Party,40.0,0,0
HB-039299,Resort Hotel,0,191,2025,August,32,6,2025-08-06,3,5,2,0.0,0,Undefined,PRT,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,196.0,,0,Transient,196.0,1,0
HB-088942,City Hotel,0,122,2024,May,19,12,2024-05-12,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,121.5,0,1
HB-102696,City Hotel,0,29,2024,December,49,2,2024-12-02,0,2,2,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,85.0,0,0
HB-112983,City Hotel,0,7,2025,May,22,31,2025-05-31,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,238.0,0,Transient,65.0,0,0
HB-024680,Resort Hotel,0,3,2024,May,22,29,2024-05-29,1,0,2,0.0,0,BB,MEX,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,85.0,1,0
HB-045353,City Hotel,0,61,2023,October,43,26,2023-10-26,1,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,72.24,0,1
HB-075037,City Hotel,1,219,2023,September,36,4,2023-09-04,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,3.0,,0,Transient-Party,80.0,0,0
HB-047410,City Hotel,1,130,2024,February,8,20,2024-02-20,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,7.0,,0,Transient,61.25,0,0
HB-048727,City Hotel,1,182,2024,March,13,28,2024-03-28,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,96.94,0,1
HB-111144,City Hotel,0,38,2025,May,19,5,2025-05-05,0,2,1,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,G,1,No Deposit,9.0,,0,Transient,179.0,0,1
HB-115218,City Hotel,0,18,2025,July,27,2,2025-07-02,1,0,2,0.0,0,SC,USA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,160.0,0,2
HB-007134,Resort Hotel,1,149,2024,July,30,23,2024-07-23,2,5,2,1.0,0,FB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,2,No Deposit,96.0,,0,Transient,195.75,0,1
HB-090302,City Hotel,0,5,2024,June,22,1,2024-06-01,0,4,1,0.0,0,BB,CHL,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,126.0,0,0
HB-010883,Resort Hotel,1,124,2025,April,15,9,2025-04-09,2,5,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,492.0,,0,Transient,80.0,0,0
HB-014999,Resort Hotel,1,244,2023,September,35,3,2023-09-03,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,19,0,A,A,0,Non Refund,,,0,Transient,36.0,0,0
HB-005044,Resort Hotel,1,164,2024,April,16,15,2024-04-15,0,2,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,118.0,0,2
HB-055865,City Hotel,1,94,2024,August,34,23,2024-08-23,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.9,0,0
HB-054419,City Hotel,1,210,2024,July,29,15,2024-07-15,2,2,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,96.0,0,0
HB-087010,City Hotel,0,2,2024,April,15,11,2024-04-11,1,1,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,104.0,0,1
HB-109514,City Hotel,0,36,2025,April,15,10,2025-04-10,1,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,4
HB-016704,Resort Hotel,0,167,2023,September,35,1,2023-09-01,2,5,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,73.8,0,0
HB-017981,Resort Hotel,0,21,2023,October,42,22,2023-10-22,2,5,2,0.0,1,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Transient,43.93,0,2
HB-116916,City Hotel,0,200,2025,July,30,26,2025-07-26,0,1,3,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient,175.5,0,1
HB-025516,Resort Hotel,0,0,2024,June,26,27,2024-06-27,1,2,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,140.0,1,0
HB-073043,City Hotel,1,264,2025,August,33,12,2025-08-12,2,5,2,1.0,0,HB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,167.85,0,0
HB-088621,City Hotel,0,98,2024,May,18,4,2024-05-04,1,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,141.6,1,1
HB-083579,City Hotel,0,6,2024,February,6,5,2024-02-05,0,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,108.0,0,0
HB-052598,City Hotel,1,12,2024,June,23,8,2024-06-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,42.0,,0,Transient,90.0,0,1
HB-081005,City Hotel,1,86,2024,January,4,22,2024-01-22,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,29.0,,35,Transient,85.0,0,0
HB-064446,City Hotel,1,50,2025,March,10,9,2025-03-09,2,4,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,74.8,0,1
HB-093289,City Hotel,0,11,2024,July,29,18,2024-07-18,1,1,1,0.0,0,BB,PRT,Offline TA/TO,GDS,0,0,0,E,E,0,No Deposit,195.0,,0,Transient,181.0,0,0
HB-091025,City Hotel,0,16,2024,June,24,12,2024-06-12,2,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,102.33,0,0
HB-006237,Resort Hotel,0,229,2024,May,22,30,2024-05-30,0,0,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,D,5,No Deposit,,223.0,0,Transient-Party,0.0,0,0
HB-049510,City Hotel,1,101,2024,April,15,14,2024-04-14,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,130.0,0,0
HB-018034,Resort Hotel,0,88,2023,October,43,24,2023-10-24,2,5,2,2.0,0,BB,IRL,Direct,Direct,0,0,0,G,G,0,No Deposit,250.0,,0,Transient,96.43,0,1
HB-011810,Resort Hotel,1,411,2025,May,22,31,2025-05-31,2,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,71.1,0,0
HB-030846,Resort Hotel,0,72,2024,December,49,2,2024-12-02,2,2,2,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,6.0,,0,Transient,29.0,0,0
HB-082284,City Hotel,0,44,2023,December,51,24,2023-12-24,0,2,1,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,69.0,0,0
HB-000032,Resort Hotel,0,95,2023,July,26,1,2023-07-01,4,11,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,63.86,0,0
HB-108669,City Hotel,0,14,2025,March,13,29,2025-03-29,0,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,74.48,0,0
HB-061033,City Hotel,1,21,2024,November,48,30,2024-11-30,0,2,1,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,76.0,0,0
HB-098456,City Hotel,0,35,2024,September,39,25,2024-09-25,2,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,137.34,0,2
HB-060585,City Hotel,1,47,2024,November,46,16,2024-11-16,0,3,3,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-095891,City Hotel,0,4,2024,October,41,11,2024-10-11,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,4,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,1
HB-027909,Resort Hotel,0,53,2024,September,37,12,2024-09-12,1,2,2,0.0,0,BB,AUS,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,241.0,,0,Transient,122.43,0,1
HB-050932,City Hotel,1,129,2024,May,19,11,2024-05-11,1,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,112.03,0,1
HB-008970,Resort Hotel,1,135,2024,October,43,22,2024-10-22,2,2,2,2.0,0,BB,SWE,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,118.0,0,0
HB-057360,City Hotel,1,254,2024,September,39,24,2024-09-24,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,96.0,0,0
HB-086257,City Hotel,0,13,2024,March,13,28,2024-03-28,1,2,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,141.33,0,1
HB-059840,City Hotel,1,482,2024,November,44,3,2024-11-03,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-017394,Resort Hotel,0,0,2023,October,40,5,2023-10-05,1,3,2,0.0,0,FB,PRT,Corporate,Corporate,0,0,0,A,H,0,No Deposit,,174.0,0,Transient-Party,109.0,0,0
HB-097852,City Hotel,0,7,2024,September,38,20,2024-09-20,0,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,86.0,,0,Transient,119.2,0,0
HB-025183,Resort Hotel,0,52,2024,June,24,12,2024-06-12,2,4,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,5.0,,0,Transient,130.87,1,1
HB-020444,Resort Hotel,0,0,2024,January,4,28,2024-01-28,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,58.0,0,2
HB-008819,Resort Hotel,1,198,2024,October,42,15,2024-10-15,2,5,2,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,240.0,,0,Transient-Party,60.83,0,0
HB-096030,City Hotel,0,175,2024,August,34,24,2024-08-24,0,4,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,123.68,0,0
HB-061594,City Hotel,1,257,2024,December,51,17,2024-12-17,2,5,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,73.95,0,0
HB-118945,City Hotel,0,164,2025,August,34,23,2025-08-23,0,4,2,1.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,125.08,0,1
HB-103288,City Hotel,0,29,2024,December,51,17,2024-12-17,0,1,1,1.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,130.0,0,0
HB-081218,City Hotel,0,13,2023,December,49,4,2023-12-04,1,2,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,B,B,0,No Deposit,14.0,,0,Transient,87.08,0,1
HB-044381,City Hotel,0,88,2023,October,40,5,2023-10-05,1,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,26.0,,77,Transient-Party,112.2,0,0
HB-099407,City Hotel,0,181,2024,October,41,11,2024-10-11,0,2,1,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,234.0,,0,Transient-Party,120.0,0,0
HB-069608,City Hotel,1,129,2025,June,23,2,2025-06-02,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,154.0,,0,Transient,130.0,0,0
HB-029823,Resort Hotel,0,29,2024,November,45,4,2024-11-04,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient-Party,55.8,0,2
HB-070262,City Hotel,1,422,2025,June,24,13,2025-06-13,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-027271,Resort Hotel,0,66,2024,August,34,23,2024-08-23,0,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,F,E,0,No Deposit,241.0,,0,Transient,176.33,0,2
HB-033421,Resort Hotel,0,117,2025,February,7,16,2025-02-16,2,5,2,2.0,0,Undefined,FRA,Offline TA/TO,TA/TO,0,0,0,C,C,2,No Deposit,464.0,,0,Transient,100.71,0,0
HB-071847,City Hotel,1,16,2025,July,28,13,2025-07-13,2,3,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,162.0,0,0
HB-030758,Resort Hotel,0,10,2024,December,49,3,2024-12-03,0,1,1,0.0,0,HB,PRT,Groups,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,44.0,0,0
HB-107176,City Hotel,0,46,2025,March,10,4,2025-03-04,2,3,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-073979,City Hotel,1,286,2023,July,30,30,2023-07-30,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-073974,City Hotel,1,279,2023,July,29,23,2023-07-23,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Contract,62.0,0,0
HB-041659,City Hotel,0,0,2023,August,34,21,2023-08-21,0,1,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,174.0,0,1
HB-105484,City Hotel,0,0,2025,February,6,9,2025-02-09,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,93.0,0,0
HB-088161,City Hotel,0,61,2024,April,18,30,2024-04-30,1,1,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,B,1,No Deposit,85.0,,0,Transient,89.75,0,1
HB-092977,City Hotel,0,57,2024,July,28,14,2024-07-14,0,1,3,0.0,0,BB,NZL,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,9.0,,0,Transient,146.7,1,1
HB-017492,Resort Hotel,0,277,2023,October,40,6,2023-10-06,2,5,1,0.0,0,HB,GBR,Groups,Direct,0,0,0,A,A,0,No Deposit,273.0,,0,Transient-Party,43.41,0,0
HB-047438,City Hotel,1,9,2024,February,8,21,2024-02-21,2,1,1,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,79.0,0,0
HB-083090,City Hotel,0,6,2024,February,5,1,2024-02-01,1,0,1,0.0,0,BB,PRT,Online TA,TA/TO,1,3,1,A,A,0,No Deposit,9.0,,0,Transient,86.0,0,0
HB-082287,City Hotel,0,19,2023,December,51,24,2023-12-24,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,B,B,0,No Deposit,,,0,Transient-Party,83.75,0,1
HB-015209,Resort Hotel,1,267,2023,September,39,26,2023-09-26,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,96.0,,0,Transient,54.99,0,0
HB-076725,City Hotel,0,20,2025,June,23,6,2025-06-06,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,1,6,65,A,A,1,No Deposit,,40.0,0,Transient,65.0,0,1
HB-021052,Resort Hotel,0,0,2024,December,50,13,2024-12-13,0,1,2,0.0,0,BB,PRT,Online TA,Direct,1,0,3,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,0
HB-057485,City Hotel,0,418,2024,September,39,26,2024-09-26,1,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,132.0,,223,Transient-Party,107.0,0,0
HB-021516,Resort Hotel,0,38,2024,February,8,25,2024-02-25,2,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,15.0,,0,Transient-Party,35.0,1,1
HB-101629,City Hotel,0,53,2024,November,46,11,2024-11-11,2,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-037003,Resort Hotel,0,67,2025,June,23,4,2025-06-04,2,1,2,0.0,0,BB,CN,Online TA,Direct,0,0,0,A,D,0,No Deposit,314.0,,0,Transient,114.8,0,1
HB-069187,City Hotel,1,235,2025,May,22,26,2025-05-26,1,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,1
HB-037416,Resort Hotel,0,242,2025,June,23,3,2025-06-03,4,10,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,143.0,,0,Transient,68.4,0,0
HB-040127,City Hotel,1,89,2023,July,27,9,2023-07-09,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.5,0,1
HB-053506,City Hotel,1,26,2024,June,25,23,2024-06-23,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,101.0,0,0
HB-007327,Resort Hotel,1,15,2024,August,31,3,2024-08-03,1,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,219.0,0,1
HB-022494,Resort Hotel,0,73,2024,March,12,19,2024-03-19,2,6,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,G,G,1,No Deposit,240.0,,0,Transient,96.13,0,0
HB-011230,Resort Hotel,1,100,2025,April,18,29,2025-04-29,2,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,D,D,0,No Deposit,385.0,,0,Transient-Party,85.0,0,0
HB-095982,City Hotel,0,142,2024,August,34,24,2024-08-24,0,3,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,99.3,0,0
HB-014278,Resort Hotel,0,72,2024,September,38,16,2024-09-16,1,2,2,0.0,0,HB,PRT,Direct,Direct,0,0,1,G,G,1,No Deposit,250.0,,0,Transient,203.4,1,1
HB-012145,Resort Hotel,1,151,2025,June,24,15,2025-06-15,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,140.0,0,1
HB-073546,City Hotel,1,15,2025,August,35,25,2025-08-25,2,2,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,101.8,0,1
HB-073552,City Hotel,1,210,2025,August,35,26,2025-08-26,0,1,2,2.0,0,BB,NLD,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,220.0,0,0
HB-111140,City Hotel,0,50,2025,May,19,5,2025-05-05,0,2,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,134.1,0,3
HB-094832,City Hotel,0,44,2024,August,32,10,2024-08-10,0,1,3,0.0,0,HB,ISR,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,219.6,0,2
HB-040088,City Hotel,1,68,2023,July,27,4,2023-07-04,2,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,68.0,0,0
HB-004254,Resort Hotel,1,123,2024,February,9,27,2024-02-27,1,1,2,0.0,0,Undefined,ESP,Groups,Direct,0,0,0,A,A,0,No Deposit,38.0,,0,Transient-Party,64.0,0,0
HB-095944,City Hotel,0,0,2024,August,34,22,2024-08-22,1,3,2,0.0,0,BB,BEL,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,142.92,0,0
HB-063609,City Hotel,1,48,2025,February,7,15,2025-02-15,0,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.1,0,1
HB-100225,City Hotel,0,386,2024,October,43,23,2024-10-23,2,0,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-054965,City Hotel,1,123,2024,August,31,1,2024-08-01,1,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.3,0,0
HB-033263,Resort Hotel,0,2,2025,February,8,18,2025-02-18,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,67.0,1,1
HB-037188,Resort Hotel,0,176,2025,June,23,6,2025-06-06,0,4,3,0.0,0,BB,IRL,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,142.5,0,1
HB-051771,City Hotel,1,30,2024,May,21,25,2024-05-25,0,1,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,98.1,0,0
HB-001242,Resort Hotel,0,102,2023,August,34,21,2023-08-21,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,134.0,0,1
HB-102352,City Hotel,0,86,2024,November,48,26,2024-11-26,0,1,2,0.0,0,BB,POL,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,79.2,0,0
HB-119129,City Hotel,0,209,2025,August,35,26,2025-08-26,2,2,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,162.0,0,0
HB-052542,City Hotel,1,56,2024,June,23,8,2024-06-08,0,1,2,0.0,0,BB,PRT,Offline TA/TO,Corporate,0,0,0,A,A,0,No Deposit,191.0,,0,Transient-Party,120.0,0,0
HB-046814,City Hotel,1,151,2024,January,3,19,2024-01-19,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,19.0,,63,Transient-Party,80.0,0,0
HB-014676,Resort Hotel,0,1,2025,January,3,19,2025-01-19,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,165.0,0,Transient,35.0,0,0
HB-094948,City Hotel,0,126,2024,August,31,1,2024-08-01,3,8,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,1,No Deposit,14.0,,0,Transient,166.61,1,2
HB-031903,Resort Hotel,0,0,2025,January,2,10,2025-01-10,0,1,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,0
HB-017530,Resort Hotel,0,2,2023,October,41,12,2023-10-12,1,0,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,76.0,0,1
HB-045858,City Hotel,0,98,2023,November,47,23,2023-11-23,1,3,2,0.0,0,BB,JOR,Groups,TA/TO,0,0,0,A,A,1,No Deposit,37.0,,0,Transient-Party,75.0,0,0
HB-110401,City Hotel,0,4,2025,April,17,27,2025-04-27,0,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,0.0,0,2
HB-049020,City Hotel,1,67,2024,April,14,4,2024-04-04,1,4,2,0.0,0,SC,FIN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.75,0,0
HB-074204,City Hotel,1,363,2023,October,41,15,2023-10-15,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-069912,City Hotel,1,183,2025,June,23,8,2025-06-08,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,86.0,,0,Transient,120.0,0,0
HB-046920,City Hotel,1,12,2024,January,4,26,2024-01-26,7,20,2,0.0,0,SC,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,76.55,0,0
HB-094166,City Hotel,0,301,2024,July,31,30,2024-07-30,1,1,1,0.0,0,HB,ROU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,90.0,0,0
HB-011407,Resort Hotel,1,233,2025,May,19,5,2025-05-05,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,60.0,0,2
HB-029259,Resort Hotel,0,36,2024,October,42,20,2024-10-20,1,3,2,0.0,0,BB,GBR,Groups,Corporate,0,0,0,A,H,1,No Deposit,,,0,Transient-Party,6.0,1,0
HB-114407,City Hotel,0,127,2025,June,25,19,2025-06-19,1,2,3,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,162.0,0,0
HB-085518,City Hotel,0,49,2024,March,11,15,2024-03-15,0,2,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,81.9,0,1
HB-031393,Resort Hotel,0,44,2024,December,52,25,2024-12-25,2,0,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,C,2,No Deposit,240.0,,0,Transient,60.0,0,2
HB-090636,City Hotel,0,12,2024,June,23,8,2024-06-08,0,1,1,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.0,0,1
HB-009334,Resort Hotel,1,59,2024,November,46,12,2024-11-12,9,21,1,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,37.7,0,1
HB-005135,Resort Hotel,0,185,2024,April,16,18,2024-04-18,1,1,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,85.0,0,0
HB-017149,Resort Hotel,0,207,2023,September,39,26,2023-09-26,1,1,2,0.0,0,HB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,208.0,,0,Transient-Party,74.0,0,0
HB-076786,City Hotel,1,395,2024,March,12,21,2024-03-21,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-096858,City Hotel,0,35,2024,September,36,5,2024-09-05,1,3,3,0.0,0,BB,IRN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,157.0,,0,Transient,110.16,0,0
HB-117655,City Hotel,0,217,2025,August,32,4,2025-08-04,1,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,180.0,0,0
HB-068562,City Hotel,1,105,2025,May,21,19,2025-05-19,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-099576,City Hotel,0,105,2024,October,41,12,2024-10-12,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,132.0,,0,Transient-Party,75.0,0,0
HB-062218,City Hotel,1,545,2025,January,1,5,2025-01-05,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-096723,City Hotel,0,204,2024,September,36,3,2024-09-03,2,2,2,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,121.0,,0,Transient-Party,80.75,0,2
HB-044023,City Hotel,1,68,2023,September,39,29,2023-09-29,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,20.0,,0,Transient-Party,48.0,0,0
HB-075189,City Hotel,1,292,2023,August,31,5,2023-08-05,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-021415,Resort Hotel,0,3,2024,February,9,28,2024-02-28,1,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,171.0,,0,Transient,4.0,0,0
HB-093893,City Hotel,0,61,2024,July,30,23,2024-07-23,2,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.5,0,1
HB-052881,City Hotel,1,11,2024,June,24,14,2024-06-14,0,3,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,D,D,0,Non Refund,,51.0,0,Transient,90.0,0,0
HB-022343,Resort Hotel,0,111,2024,March,11,14,2024-03-14,3,6,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,61.2,0,1
HB-057080,City Hotel,1,41,2024,September,38,18,2024-09-18,2,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,149.4,0,1
HB-088660,City Hotel,0,2,2024,May,19,9,2024-05-09,1,0,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.0,0,2
HB-114602,City Hotel,0,221,2025,June,26,23,2025-06-23,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,89.1,0,2
HB-076897,City Hotel,0,0,2023,August,33,18,2023-08-18,0,2,2,0.0,0,SC,ESP,Direct,Direct,0,0,0,B,B,0,No Deposit,,,0,Transient,113.0,0,0
HB-117348,City Hotel,0,208,2025,August,31,2,2025-08-02,0,1,2,0.0,0,HB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,157.0,0,1
HB-086106,City Hotel,0,81,2024,March,13,25,2024-03-25,1,2,2,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,3.0,,4,Transient-Party,65.0,0,0
HB-030586,Resort Hotel,0,23,2024,November,47,21,2024-11-21,1,5,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,62.0,1,1
HB-063991,City Hotel,1,28,2025,February,9,25,2025-02-25,2,2,3,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,134.3,0,0
HB-005061,Resort Hotel,0,183,2024,April,16,16,2024-04-16,1,1,2,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,0,No Deposit,298.0,,0,Transient-Party,85.0,0,0
HB-084864,City Hotel,0,54,2024,March,9,1,2024-03-01,0,4,2,0.0,0,SC,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,49.43,0,0
HB-012702,Resort Hotel,1,77,2025,July,28,12,2025-07-12,0,4,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,198.75,0,0
HB-072266,City Hotel,1,464,2025,July,30,25,2025-07-25,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-079449,City Hotel,1,137,2024,January,4,27,2024-01-27,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,29.0,,45,Transient,70.0,0,0
HB-090439,City Hotel,0,14,2024,May,22,30,2024-05-30,2,5,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,131.7,0,1
HB-024662,Resort Hotel,0,0,2024,May,22,28,2024-05-28,0,1,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,G,G,1,No Deposit,,,0,Transient,185.0,0,0
HB-023730,Resort Hotel,0,8,2024,November,44,2,2024-11-02,0,2,2,0.0,0,BB,PRT,Direct,Direct,1,0,1,D,E,0,No Deposit,250.0,,0,Transient,69.0,1,1
HB-066092,City Hotel,1,14,2025,April,16,14,2025-04-14,0,2,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,150.0,0,2
HB-024809,Resort Hotel,0,105,2024,May,22,30,2024-05-30,1,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,84.2,0,1
HB-098376,City Hotel,0,17,2024,September,39,27,2024-09-27,0,2,2,0.0,0,SC,JPN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,85.0,0,0
HB-042981,City Hotel,1,65,2023,September,37,12,2023-09-12,2,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,86.0,0,0
HB-117802,City Hotel,0,184,2025,August,32,8,2025-08-08,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,141.5,0,0
HB-068236,City Hotel,1,104,2025,May,20,15,2025-05-15,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-089163,City Hotel,0,52,2024,May,20,15,2024-05-15,2,1,1,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,140.4,0,1
HB-010231,Resort Hotel,1,51,2025,February,8,22,2025-02-22,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,0
HB-026222,Resort Hotel,0,119,2024,July,29,20,2024-07-20,1,4,2,0.0,0,BB,PRT,Online TA,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,180.0,0,1
HB-041623,City Hotel,0,0,2023,August,33,19,2023-08-19,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,106.0,0,2
HB-099214,City Hotel,0,36,2024,October,41,13,2024-10-13,0,1,1,0.0,0,SC,USA,Online TA,TA/TO,0,0,1,A,A,0,No Deposit,8.0,,0,Transient-Party,102.6,0,2
HB-004327,Resort Hotel,1,162,2024,March,10,4,2024-03-04,6,15,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,96.0,,0,Transient,82.0,0,0
HB-018039,Resort Hotel,0,130,2023,October,43,24,2023-10-24,2,5,2,2.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,C,G,0,No Deposit,2.0,,0,Contract,130.07,0,1
HB-027122,Resort Hotel,0,119,2024,August,34,20,2024-08-20,2,5,2,1.0,0,FB,BRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,196.0,,0,Transient-Party,215.6,0,1
HB-022600,Resort Hotel,0,0,2024,March,13,29,2024-03-29,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,35.11,0,0
HB-068866,City Hotel,1,26,2025,May,21,22,2025-05-22,1,0,1,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,1
HB-011275,Resort Hotel,1,221,2025,April,18,30,2025-04-30,2,5,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,82.0,0,0
HB-018292,Resort Hotel,1,2,2023,November,46,18,2023-11-18,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,0,A,A,0,No Deposit,,337.0,0,Transient,38.0,0,0
HB-058930,City Hotel,1,103,2024,October,42,17,2024-10-17,1,4,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.8,0,3
HB-021219,Resort Hotel,0,0,2024,February,7,16,2024-02-16,0,5,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,2,No Deposit,,,0,Transient,46.2,1,0
HB-055181,City Hotel,1,148,2024,August,32,7,2024-08-07,1,0,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,114.3,0,0
HB-000683,Resort Hotel,0,33,2023,July,30,25,2023-07-25,2,3,2,2.0,0,HB,PRT,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,241.0,,0,Transient,142.03,0,1
HB-044522,City Hotel,0,97,2023,October,40,7,2023-10-07,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,C,0,No Deposit,1.0,,0,Transient-Party,60.0,0,0
HB-007657,Resort Hotel,1,14,2024,August,33,18,2024-08-18,2,5,2,1.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,15.0,,0,Transient,208.48,0,0
HB-108713,City Hotel,0,43,2025,March,13,26,2025-03-26,2,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,83.0,,0,Transient,85.91,0,0
HB-044606,City Hotel,0,62,2023,October,40,8,2023-10-08,1,3,2,0.0,0,BB,SRB,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,89.25,0,2
HB-110641,City Hotel,0,29,2025,April,18,28,2025-04-28,0,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,124.0,0,1
HB-018658,Resort Hotel,0,4,2025,August,31,1,2025-08-01,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,3,A,A,0,No Deposit,,94.0,0,Transient,142.0,1,0
HB-068604,City Hotel,1,105,2025,May,21,19,2025-05-19,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-074302,City Hotel,1,330,2023,September,37,12,2023-09-12,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-096187,City Hotel,0,130,2024,August,35,27,2024-08-27,2,1,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,109.8,0,2
HB-107153,City Hotel,0,4,2025,March,10,6,2025-03-06,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,E,E,0,No Deposit,,435.0,0,Transient,110.0,0,0
HB-075540,City Hotel,1,355,2023,October,40,7,2023-10-07,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,60.0,0,0
HB-014632,Resort Hotel,0,184,2024,September,36,3,2024-09-03,4,6,2,0.0,0,BB,,Direct,Direct,0,0,0,F,F,1,No Deposit,250.0,,0,Transient,166.0,1,1
HB-114561,City Hotel,0,39,2025,June,25,20,2025-06-20,0,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,160.0,0,1
HB-022431,Resort Hotel,0,61,2024,March,12,20,2024-03-20,2,3,2,1.0,0,HB,PRT,Direct,Direct,0,0,0,D,D,1,No Deposit,250.0,,0,Transient,113.3,1,0
HB-069509,City Hotel,1,174,2025,June,22,1,2025-06-01,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,0,Transient,100.0,0,0
HB-117961,City Hotel,0,9,2025,August,33,12,2025-08-12,2,1,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,K,3,No Deposit,9.0,,0,Transient-Party,0.0,0,0
HB-092205,City Hotel,0,131,2024,June,26,29,2024-06-29,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient-Party,85.5,0,0
HB-040772,City Hotel,0,36,2023,August,32,7,2023-08-07,0,2,3,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,D,1,No Deposit,1.0,,0,Transient-Party,84.0,0,1
HB-095051,City Hotel,0,93,2024,August,33,13,2024-08-13,0,1,1,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,112.5,0,1
HB-005424,Resort Hotel,1,65,2024,April,18,29,2024-04-29,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,73.0,0,0
HB-050360,City Hotel,1,124,2024,April,18,29,2024-04-29,0,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,96.3,0,0
HB-108242,City Hotel,0,116,2025,March,13,24,2025-03-24,0,2,1,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,1,No Deposit,171.0,,0,Transient-Party,90.0,0,0
HB-022479,Resort Hotel,0,9,2024,March,13,25,2024-03-25,0,2,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,242.0,,0,Transient,153.0,1,1
HB-048833,City Hotel,1,30,2024,March,13,31,2024-03-31,0,2,2,2.0,0,BB,IRN,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,195.0,0,0
HB-100910,City Hotel,0,51,2024,November,44,1,2024-11-01,0,3,2,1.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,129.0,0,1
HB-015779,Resort Hotel,0,16,2023,July,30,30,2023-07-30,0,3,3,0.0,0,BB,NOR,Direct,Direct,0,0,0,E,F,0,No Deposit,250.0,,0,Transient,194.0,0,0
HB-043018,City Hotel,0,68,2023,September,37,12,2023-09-12,2,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-004345,Resort Hotel,1,38,2024,March,10,5,2024-03-05,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,2
HB-061004,City Hotel,1,42,2024,November,48,29,2024-11-29,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,348.0,0,Transient,90.0,0,0
HB-098291,City Hotel,0,0,2024,September,39,27,2024-09-27,0,1,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,152.0,,0,Transient,100.37,0,0
HB-037612,Resort Hotel,0,0,2025,June,26,23,2025-06-23,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,128.0,0,1
HB-103356,City Hotel,0,24,2024,December,51,18,2024-12-18,2,1,1,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,104.0,0,1
HB-107192,City Hotel,0,11,2025,March,10,7,2025-03-07,0,2,1,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,441.0,,0,Transient-Party,130.0,0,2
HB-107946,City Hotel,0,51,2025,March,12,17,2025-03-17,1,2,2,1.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,90.0,0,3
HB-008047,Resort Hotel,0,355,2024,September,36,7,2024-09-07,4,10,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,92.9,0,0
HB-037424,Resort Hotel,0,1,2025,June,25,16,2025-06-16,0,1,1,0.0,0,BB,DNK,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,107.6,0,1
HB-028601,Resort Hotel,0,118,2024,October,40,4,2024-10-04,0,3,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,G,0,No Deposit,171.0,,0,Transient,46.0,0,0
HB-080951,City Hotel,0,27,2023,November,48,29,2023-11-29,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-086374,City Hotel,0,67,2024,April,14,1,2024-04-01,0,1,2,0.0,0,BB,KOR,Online TA,TA/TO,0,0,0,A,A,4,No Deposit,9.0,,0,Transient,109.1,1,0
HB-036140,Resort Hotel,0,79,2025,May,19,8,2025-05-08,1,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,241.0,,0,Transient,95.48,0,0
HB-011132,Resort Hotel,1,23,2025,April,17,22,2025-04-22,2,5,2,0.0,0,FB,PRT,Groups,Corporate,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,116.0,0,0
HB-046293,City Hotel,0,146,2023,December,52,29,2023-12-29,0,3,2,0.0,0,BB,AUT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,99,Transient-Party,75.0,0,0
HB-104031,City Hotel,0,0,2025,January,1,3,2025-01-03,0,1,1,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,A,1,No Deposit,,,0,Transient,0.0,0,0
HB-027049,Resort Hotel,0,154,2024,August,33,16,2024-08-16,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,3,No Deposit,240.0,,0,Transient-Party,232.8,0,1
HB-103251,City Hotel,0,11,2024,December,51,16,2024-12-16,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,104.0,0,1
HB-017357,Resort Hotel,0,50,2023,October,39,1,2023-10-01,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,243.0,,0,Transient,63.08,0,2
HB-048749,City Hotel,1,74,2024,March,13,29,2024-03-29,0,5,1,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,72.25,0,0
HB-091671,City Hotel,0,56,2024,June,25,22,2024-06-22,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,89.1,0,0
HB-046812,City Hotel,0,151,2024,January,3,19,2024-01-19,0,3,1,0.0,0,BB,DNK,Offline TA/TO,TA/TO,0,0,0,A,D,3,No Deposit,19.0,,63,Transient-Party,71.0,0,0
HB-077664,City Hotel,0,5,2025,June,26,27,2025-06-27,0,2,2,0.0,0,BB,ESP,Corporate,Corporate,1,0,7,A,A,0,No Deposit,,62.0,0,Transient,100.0,0,1
HB-061901,City Hotel,1,199,2024,December,52,28,2024-12-28,0,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,9.0,,0,Transient,102.85,0,0
HB-078721,City Hotel,0,20,2024,January,1,5,2024-01-05,0,2,1,0.0,0,BB,FRA,Corporate,Corporate,1,1,0,A,A,0,No Deposit,91.0,,0,Transient,80.0,0,1
HB-097463,City Hotel,0,15,2024,September,37,15,2024-09-15,0,2,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,7.0,,0,Transient,141.68,0,1
HB-022977,Resort Hotel,0,0,2024,April,15,11,2024-04-11,1,0,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,59.4,0,1
HB-096023,City Hotel,0,143,2024,August,34,25,2024-08-25,0,3,1,0.0,0,BB,CZE,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,36.0,,0,Transient-Party,90.0,0,0
HB-091724,City Hotel,0,235,2024,June,26,24,2024-06-24,0,2,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,61,Transient-Party,65.0,0,1
HB-112709,City Hotel,0,87,2025,May,21,24,2025-05-24,0,4,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,144.0,0,0
HB-078382,City Hotel,1,21,2023,October,40,8,2023-10-08,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Contract,117.0,0,1
HB-074211,City Hotel,1,363,2023,October,41,15,2023-10-15,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-063565,City Hotel,1,88,2025,February,7,14,2025-02-14,0,1,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,71.28,0,1
HB-053120,City Hotel,1,31,2024,June,24,16,2024-06-16,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,132.6,0,0
HB-012399,Resort Hotel,1,188,2025,June,26,26,2025-06-26,4,10,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,110.0,0,0
HB-033734,Resort Hotel,0,20,2025,February,8,23,2025-02-23,2,5,2,0.0,0,Undefined,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,464.0,,0,Transient,66.0,0,0
HB-052383,City Hotel,0,150,2024,June,23,4,2024-06-04,2,2,2,0.0,0,BB,CHE,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,108.59,0,0
HB-100539,City Hotel,0,247,2024,October,43,25,2024-10-25,0,4,2,0.0,0,BB,ROU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,90.95,0,0
HB-067485,City Hotel,1,148,2025,May,18,4,2025-05-04,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,171.0,,0,Transient,95.0,0,0
HB-109012,City Hotel,0,111,2025,April,14,3,2025-04-03,1,1,2,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,,0,Transient-Party,95.0,0,1
HB-011366,Resort Hotel,1,223,2025,May,18,4,2025-05-04,2,5,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,177.0,,0,Transient,68.4,0,1
HB-046096,City Hotel,1,106,2023,December,49,9,2023-12-09,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,57,Transient,75.0,0,0
HB-018613,Resort Hotel,0,0,2023,November,47,24,2023-11-24,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,40.0,0,0
HB-109332,City Hotel,0,133,2025,April,15,8,2025-04-08,1,1,2,0.0,0,BB,ARG,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,85.59,0,0
HB-116892,City Hotel,0,20,2025,July,30,25,2025-07-25,0,2,2,0.0,0,BB,CHN,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,,0,Transient,150.0,0,1
HB-064496,City Hotel,1,127,2025,March,11,11,2025-03-11,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,58.0,,0,Transient,80.0,0,0
HB-114289,City Hotel,0,130,2025,June,24,15,2025-06-15,2,3,2,0.0,0,BB,FIN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,8.0,,0,Transient,131.4,0,0
HB-010181,Resort Hotel,1,74,2025,February,8,18,2025-02-18,1,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,498.0,0,Transient-Party,40.0,0,0
HB-031852,Resort Hotel,0,36,2025,January,1,1,2025-01-01,2,5,1,0.0,0,BB,MYS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,175.0,,0,Transient-Party,33.94,0,1
HB-014856,Resort Hotel,1,207,2023,September,39,26,2023-09-26,1,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,1,1,0,A,A,0,No Deposit,208.0,,0,Transient,34.0,0,0
HB-088066,City Hotel,0,4,2024,April,18,30,2024-04-30,0,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,B,0,No Deposit,138.0,,0,Transient,0.0,0,0
HB-093774,City Hotel,0,40,2024,July,30,26,2024-07-26,0,1,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,39.0,,0,Transient-Party,95.0,0,0
HB-042949,City Hotel,0,72,2023,September,37,11,2023-09-11,0,2,1,0.0,0,HB,LUX,Groups,TA/TO,0,0,0,A,D,1,No Deposit,30.0,,0,Transient-Party,98.0,0,0
HB-022034,Resort Hotel,0,2,2024,March,11,16,2024-03-16,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,D,0,No Deposit,,47.0,0,Transient,30.0,0,0
HB-102848,City Hotel,0,81,2024,December,49,4,2024-12-04,2,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,75.0,0,0
HB-051874,City Hotel,0,316,2024,May,21,26,2024-05-26,0,3,2,0.0,0,BB,AUT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,30.0,,0,Transient-Party,110.0,0,0
HB-049865,City Hotel,1,270,2024,April,16,20,2024-04-20,0,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,187,Transient-Party,62.8,0,0
HB-056027,City Hotel,1,226,2024,August,35,27,2024-08-27,1,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,96.0,0,0
HB-064760,City Hotel,1,307,2025,March,11,15,2025-03-15,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,77.35,0,0
HB-001055,Resort Hotel,0,84,2023,August,32,11,2023-08-11,2,8,2,1.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,D,D,1,No Deposit,171.0,,0,Transient,142.26,0,1
HB-075525,City Hotel,1,355,2023,October,40,7,2023-10-07,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-057205,City Hotel,1,171,2024,September,38,20,2024-09-20,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,80.75,0,0
HB-020317,Resort Hotel,0,19,2024,January,4,23,2024-01-23,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,1,No Deposit,240.0,,0,Transient,48.0,0,0
HB-015939,Resort Hotel,0,75,2023,August,31,3,2023-08-03,1,5,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,149.0,,0,Transient,123.0,0,2
HB-091304,City Hotel,0,45,2024,June,25,17,2024-06-17,1,2,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,65.0,0,1
HB-063417,City Hotel,1,33,2025,February,7,11,2025-02-11,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,83.3,0,2
HB-042982,City Hotel,1,65,2023,September,37,12,2023-09-12,2,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,86.0,0,0
HB-045309,City Hotel,0,69,2023,October,43,25,2023-10-25,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,D,0,No Deposit,37.0,,58,Transient-Party,85.67,0,0
HB-107847,City Hotel,0,175,2025,March,11,16,2025-03-16,0,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,72.0,0,2
HB-036954,Resort Hotel,0,107,2025,May,22,27,2025-05-27,2,5,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,196.0,,0,Transient,80.43,0,0
HB-017404,Resort Hotel,0,224,2023,October,40,2,2023-10-02,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,45.9,0,0
HB-035550,Resort Hotel,0,203,2025,April,17,25,2025-04-25,0,2,2,0.0,0,HB,AUT,Groups,TA/TO,0,0,0,A,A,2,No Deposit,502.0,,0,Transient-Party,90.0,0,0
HB-055001,City Hotel,1,175,2024,August,31,2,2024-08-02,0,3,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.3,0,0
HB-055291,City Hotel,1,405,2024,August,32,10,2024-08-10,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,65.0,0,0
HB-028968,Resort Hotel,0,5,2024,October,42,15,2024-10-15,1,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,H,H,1,No Deposit,,,0,Transient,135.0,0,1
HB-115965,City Hotel,0,62,2025,July,28,9,2025-07-09,2,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,80.1,0,0
HB-055787,City Hotel,1,5,2024,August,34,21,2024-08-21,1,0,2,0.0,0,BB,PRT,Online TA,Corporate,0,0,0,A,A,0,Non Refund,,47.0,0,Transient,167.0,0,0
HB-039061,Resort Hotel,0,24,2025,August,32,4,2025-08-04,1,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,135.0,0,0
HB-094850,City Hotel,0,158,2024,August,32,8,2024-08-08,1,2,2,3.0,0,BB,NLD,Direct,Direct,0,0,0,G,G,0,No Deposit,14.0,,0,Transient,252.9,1,0
HB-024075,Resort Hotel,0,103,2024,May,18,1,2024-05-01,4,7,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,243.0,,0,Contract,39.04,0,0
HB-046681,City Hotel,0,9,2024,January,3,15,2024-01-15,1,2,2,0.0,0,BB,DZA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,80.3,0,1
HB-014246,Resort Hotel,0,2,2024,January,3,20,2024-01-20,0,2,1,0.0,0,BB,PRT,Direct,Direct,0,0,1,A,D,0,No Deposit,,,0,Transient,39.0,0,0
HB-004712,Resort Hotel,1,29,2024,March,13,29,2024-03-29,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,48.0,0,0
HB-014437,Resort Hotel,0,4,2024,January,4,26,2024-01-26,0,1,1,0.0,0,BB,,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,49.0,0,0
HB-092773,City Hotel,0,60,2024,July,28,9,2024-07-09,2,1,3,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,177.9,0,1
HB-064650,City Hotel,1,28,2025,March,11,14,2025-03-14,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,65.0,0,0
HB-069621,City Hotel,1,86,2025,June,23,2,2025-06-02,1,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,180.0,0,0
HB-053950,City Hotel,1,54,2024,July,27,2,2024-07-02,2,5,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,146.7,0,0
HB-067246,City Hotel,1,212,2025,April,18,30,2025-04-30,1,0,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,10.0,,0,Transient,99.0,0,0
HB-056901,City Hotel,1,433,2024,September,37,15,2024-09-15,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-099808,City Hotel,0,248,2024,October,41,13,2024-10-13,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,7.0,,0,Transient,83.38,0,2
HB-115139,City Hotel,0,151,2025,June,26,29,2025-06-29,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,122.7,0,0
HB-084365,City Hotel,0,21,2024,February,8,25,2024-02-25,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,68.0,0,1
HB-093843,City Hotel,0,115,2024,July,30,26,2024-07-26,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,94.5,0,1
HB-027459,Resort Hotel,0,272,2024,August,34,25,2024-08-25,2,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,201.0,,0,Transient-Party,131.6,0,0
HB-075464,City Hotel,1,334,2023,September,37,16,2023-09-16,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-046160,City Hotel,1,107,2023,December,51,18,2023-12-18,2,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,55.63,0,0
HB-006096,Resort Hotel,1,100,2024,May,21,25,2024-05-25,0,4,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,105.0,0,0
HB-059502,City Hotel,1,247,2024,October,44,28,2024-10-28,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,110.0,0,0
HB-057939,City Hotel,0,281,2024,October,40,3,2024-10-03,1,3,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,7,No Deposit,9.0,,0,Transient-Party,126.3,0,0
HB-043905,City Hotel,1,87,2023,September,39,25,2023-09-25,2,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-105063,City Hotel,0,73,2025,January,5,27,2025-01-27,0,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,1
HB-081594,City Hotel,1,197,2024,June,23,3,2024-06-03,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,21.0,,25,Transient,80.0,0,0
HB-000474,Resort Hotel,1,23,2023,July,29,17,2023-07-17,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,120.6,0,1
HB-117406,City Hotel,0,44,2025,July,31,30,2025-07-30,2,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,169.0,0,1
HB-010604,Resort Hotel,1,201,2025,March,12,18,2025-03-18,2,5,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient,37.8,0,2
HB-081166,City Hotel,1,27,2023,December,49,4,2023-12-04,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,B,B,0,No Deposit,7.0,,0,Transient,77.87,0,0
HB-086453,City Hotel,0,81,2024,April,14,1,2024-04-01,0,2,2,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,0.0,0,0
HB-030986,Resort Hotel,0,22,2024,December,49,8,2024-12-08,0,3,2,0.0,0,Undefined,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,38.0,,0,Transient-Party,80.0,0,0
HB-051083,City Hotel,1,309,2024,May,20,13,2024-05-13,1,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,3.0,,215,Transient-Party,101.0,0,0
HB-057656,City Hotel,1,270,2024,September,39,29,2024-09-29,1,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,108.8,0,1
HB-039087,Resort Hotel,0,15,2025,August,32,4,2025-08-04,1,2,2,0.0,0,BB,AUS,Direct,Direct,0,0,0,A,A,0,No Deposit,250.0,,0,Transient,207.33,0,1
HB-099743,City Hotel,0,100,2024,October,41,13,2024-10-13,0,3,2,0.0,0,BB,USA,Direct,Direct,0,0,0,E,F,4,No Deposit,14.0,,0,Transient,152.46,0,0
HB-057109,City Hotel,1,27,2024,September,38,19,2024-09-19,1,0,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,287.0,,8,Transient,118.15,0,0
HB-024369,Resort Hotel,0,107,2024,May,18,5,2024-05-05,4,10,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,243.0,,0,Contract,72.75,0,2
HB-065913,City Hotel,1,83,2025,April,15,10,2025-04-10,1,0,2,1.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,177.75,0,3
HB-062783,City Hotel,1,12,2025,January,4,22,2025-01-22,2,0,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,78.0,0,1
HB-073894,City Hotel,1,321,2023,September,35,3,2023-09-03,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,1,1,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.8,0,0
HB-073163,City Hotel,1,180,2025,August,33,16,2025-08-16,0,1,1,1.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,121.0,0,0
HB-052489,City Hotel,1,213,2024,June,23,7,2024-06-07,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,62,Transient,130.0,0,0
HB-110048,City Hotel,0,150,2025,April,16,19,2025-04-19,0,2,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Transient,117.0,0,2
HB-041229,City Hotel,1,39,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,101.5,0,0
HB-027669,Resort Hotel,0,0,2024,September,36,4,2024-09-04,1,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,0,No Deposit,,,0,Transient,177.0,0,0
HB-026917,Resort Hotel,0,17,2024,August,33,14,2024-08-14,1,0,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,251.0,,0,Transient,215.0,0,1
HB-031531,Resort Hotel,0,11,2024,December,52,29,2024-12-29,0,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,I,0,No Deposit,240.0,,0,Transient,83.5,0,1
HB-025668,Resort Hotel,0,17,2024,July,27,2,2024-07-02,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,E,0,No Deposit,240.0,,0,Transient,145.5,1,1
HB-078284,City Hotel,0,0,2023,October,43,27,2023-10-27,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,40.0,0,Transient,65.0,1,0
HB-062452,City Hotel,1,38,2025,January,3,14,2025-01-14,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,Non Refund,,67.0,0,Transient,75.0,0,0
HB-054231,City Hotel,1,76,2024,July,28,9,2024-07-09,2,1,2,0.0,0,BB,CN,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,127.8,0,0
HB-109221,City Hotel,0,105,2025,April,14,5,2025-04-05,0,4,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,2
HB-059890,City Hotel,1,304,2024,November,44,3,2024-11-03,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,21.0,,0,Transient,89.0,0,0
HB-077948,City Hotel,0,17,2023,September,39,26,2023-09-26,2,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,170.0,0,0
HB-115519,City Hotel,0,162,2025,July,27,5,2025-07-05,0,2,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,108.5,0,0
HB-069315,City Hotel,1,408,2025,May,22,30,2025-05-30,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,229.0,,0,Transient,90.0,0,0
HB-111439,City Hotel,0,35,2025,May,19,10,2025-05-10,0,1,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,1,No Deposit,39.0,,0,Transient-Party,130.0,0,0
HB-086065,City Hotel,0,147,2024,March,12,24,2024-03-24,0,3,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,174.0,1,1
HB-099929,City Hotel,0,153,2024,October,42,16,2024-10-16,2,2,2,0.0,0,SC,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,,0,Transient,72.25,0,1
HB-108237,City Hotel,0,16,2025,March,12,23,2025-03-23,0,1,1,0.0,0,BB,FRA,Corporate,Corporate,0,0,0,D,C,0,No Deposit,,,0,Transient-Party,108.0,0,0
HB-111211,City Hotel,0,97,2025,May,19,5,2025-05-05,1,2,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,171.0,0,0
HB-087477,City Hotel,0,0,2024,April,16,20,2024-04-20,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,F,0,No Deposit,7.0,,0,Transient,69.99,0,0
HB-116679,City Hotel,0,423,2025,July,30,22,2025-07-22,1,1,1,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,95.5,0,0
HB-084672,City Hotel,0,115,2024,February,9,27,2024-02-27,2,2,2,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,134.0,,0,Transient-Party,86.0,0,0
HB-080560,City Hotel,0,25,2023,November,46,17,2023-11-17,0,2,1,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,101.0,0,1
HB-037380,Resort Hotel,0,0,2025,June,24,15,2025-06-15,0,1,1,0.0,0,BB,PRT,Complementary,Corporate,0,0,0,A,A,0,No Deposit,302.0,,0,Transient,0.0,0,0
HB-029013,Resort Hotel,0,47,2024,October,42,18,2024-10-18,0,1,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,368.0,,0,Transient-Party,72.0,0,0
HB-082059,City Hotel,0,5,2023,December,50,17,2023-12-17,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,85.0,,0,Transient,69.0,0,0
HB-066917,City Hotel,1,156,2025,April,17,26,2025-04-26,0,3,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,100.0,0,0
HB-111777,City Hotel,0,168,2025,May,20,12,2025-05-12,1,2,2,0.0,0,BB,CHE,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient-Party,120.0,0,0
HB-024193,Resort Hotel,0,236,2024,May,19,12,2024-05-12,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,315.0,,0,Transient-Party,42.0,0,0
HB-028111,Resort Hotel,0,174,2024,September,38,20,2024-09-20,0,1,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,D,C,1,No Deposit,251.0,,0,Transient,78.0,0,0
HB-059733,City Hotel,1,166,2024,November,44,1,2024-11-01,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,110.0,0,0
HB-011741,Resort Hotel,1,198,2025,May,22,28,2025-05-28,2,0,2,0.0,0,HB,COL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,115.0,0,1
HB-020926,Resort Hotel,0,12,2024,February,7,13,2024-02-13,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,58.0,0,0
HB-016208,Resort Hotel,0,151,2025,August,32,6,2025-08-06,2,5,2,0.0,0,HB,PRT,Direct,TA/TO,1,0,1,D,D,1,No Deposit,250.0,,0,Transient,236.93,0,2
HB-082344,City Hotel,1,94,2024,March,10,4,2024-03-04,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,154.0,,28,Transient,80.0,0,0
HB-061829,City Hotel,1,15,2024,December,52,27,2024-12-27,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,65.0,0,0
HB-064617,City Hotel,1,37,2025,March,11,13,2025-03-13,1,3,1,0.0,0,BB,AUT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,104.55,0,0
HB-059172,City Hotel,1,240,2024,October,43,21,2024-10-21,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,110.0,0,0
HB-088613,City Hotel,0,78,2024,May,18,5,2024-05-05,1,3,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,80.75,0,0
HB-106145,City Hotel,0,236,2025,February,8,20,2025-02-20,1,1,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,103.5,0,1
HB-043229,City Hotel,0,15,2023,September,37,17,2023-09-17,0,1,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,9.0,,0,Contract,115.0,0,3
HB-002759,Resort Hotel,0,11,2023,October,44,30,2023-10-30,1,2,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,177.0,,0,Transient-Party,47.45,1,1
HB-093263,City Hotel,0,18,2024,July,29,17,2024-07-17,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,138.0,,0,Transient,85.0,0,0
HB-100224,City Hotel,0,386,2024,October,43,23,2024-10-23,2,0,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,1
HB-050169,City Hotel,1,45,2024,April,17,24,2024-04-24,2,2,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,128.56,0,0
HB-049412,City Hotel,1,1,2024,April,15,12,2024-04-12,2,6,1,0.0,0,BB,PRT,Aviation,Corporate,0,0,0,A,A,0,No Deposit,153.0,,0,Transient,95.0,0,0
HB-039580,Resort Hotel,0,76,2025,August,33,16,2025-08-16,2,4,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,241.67,0,2
HB-048529,City Hotel,1,161,2024,March,13,25,2024-03-25,1,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,12.0,,101,Transient,130.0,0,0
HB-003180,Resort Hotel,1,36,2023,November,47,20,2023-11-20,0,2,2,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,38.0,,0,Transient-Party,64.0,0,0
HB-009162,Resort Hotel,1,19,2024,October,44,30,2024-10-30,2,2,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,15.0,,0,Transient,78.0,0,2
HB-085009,City Hotel,0,93,2024,March,10,5,2024-03-05,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,60.0,0,0
HB-003299,Resort Hotel,0,22,2023,December,49,4,2023-12-04,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,52.4,0,2
HB-055699,City Hotel,1,291,2024,August,34,19,2024-08-19,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,39.0,,0,Transient,115.0,0,0
HB-031586,Resort Hotel,0,45,2024,December,1,30,2024-12-30,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,225.0,0,2
HB-105735,City Hotel,0,5,2025,February,7,12,2025-02-12,2,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,2
HB-046392,City Hotel,0,0,2023,December,52,31,2023-12-31,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.0,0,0
HB-096991,City Hotel,0,183,2024,September,36,8,2024-09-08,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,44.0,,0,Transient-Party,110.0,0,1
HB-045127,City Hotel,0,74,2023,October,42,17,2023-10-17,2,2,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,15.0,,0,Transient,68.5,0,0
HB-006378,Resort Hotel,0,251,2024,June,23,6,2024-06-06,1,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,F,0,No Deposit,147.0,,0,Transient,95.73,0,0
HB-078058,City Hotel,0,2,2023,September,39,30,2023-09-30,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,126.0,0,1
HB-056959,City Hotel,1,422,2024,September,38,16,2024-09-16,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,379,Transient-Party,65.0,0,0
HB-023013,Resort Hotel,0,1,2024,April,15,12,2024-04-12,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,330.0,,0,Transient,59.4,0,0
HB-093553,City Hotel,0,292,2024,July,29,21,2024-07-21,0,2,2,0.0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,115.0,0,0
HB-049830,City Hotel,1,265,2024,April,16,20,2024-04-20,0,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,30.0,,0,Transient,101.0,0,0
HB-084110,City Hotel,0,8,2024,February,8,19,2024-02-19,0,1,1,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,D,0,No Deposit,,67.0,0,Transient-Party,81.0,0,0
HB-107303,City Hotel,0,15,2025,March,10,8,2025-03-08,0,3,1,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,121.33,0,1
HB-012762,Resort Hotel,1,354,2025,July,29,15,2025-07-15,4,6,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,194.4,0,2
HB-102937,City Hotel,0,44,2024,December,49,6,2024-12-06,0,4,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,94.5,0,1
HB-005476,Resort Hotel,1,87,2024,April,18,29,2024-04-29,2,5,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,D,D,0,Non Refund,71.0,,0,Transient,58.0,0,0
HB-081274,City Hotel,0,23,2023,December,49,4,2023-12-04,2,2,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Contract,55.0,0,0
HB-110092,City Hotel,0,28,2025,April,17,21,2025-04-21,0,1,1,0.0,0,BB,USA,Direct,Direct,0,0,0,A,D,1,No Deposit,14.0,,0,Transient,93.5,0,0
HB-103570,City Hotel,0,39,2024,December,52,27,2024-12-27,0,1,2,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,220.0,,0,Transient-Party,65.0,0,0
HB-062103,City Hotel,1,37,2025,January,1,1,2025-01-01,2,4,1,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,71.4,0,0
HB-027486,Resort Hotel,0,14,2024,August,35,30,2024-08-30,0,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,B,0,No Deposit,240.0,,0,Transient,180.0,0,2
HB-038313,Resort Hotel,0,165,2025,July,28,8,2025-07-08,2,5,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,143.0,,0,Transient,132.85,0,0
HB-107550,City Hotel,0,107,2025,March,11,12,2025-03-12,2,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,83.0,,0,Transient,99.36,0,0
HB-075178,City Hotel,1,292,2023,August,31,5,2023-08-05,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-016475,Resort Hotel,0,22,2023,August,34,25,2023-08-25,0,5,3,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,250.0,,0,Transient,203.0,0,2
HB-050477,City Hotel,1,11,2024,May,18,2,2024-05-02,1,1,2,1.0,0,BB,FIN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,159.0,0,0
HB-021544,Resort Hotel,0,0,2024,February,9,29,2024-02-29,1,2,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,43.0,0,1
HB-012686,Resort Hotel,1,87,2025,July,28,12,2025-07-12,0,1,2,2.0,0,BB,CHE,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,270.0,0,0
HB-001189,Resort Hotel,0,74,2023,August,33,17,2023-08-17,2,5,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Transient,101.65,0,0
HB-073536,City Hotel,1,222,2025,August,35,25,2025-08-25,1,2,2,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,117.0,0,0
HB-068318,City Hotel,1,104,2025,May,20,15,2025-05-15,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-056834,City Hotel,1,317,2024,September,37,15,2024-09-15,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,19.0,,0,Transient,120.0,0,0
HB-103018,City Hotel,0,85,2024,December,49,8,2024-12-08,0,3,3,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,28.0,,0,Transient,105.0,0,0
HB-068215,City Hotel,1,104,2025,May,20,15,2025-05-15,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-063509,City Hotel,1,19,2025,February,7,12,2025-02-12,2,2,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,7.0,,0,Transient,90.71,0,0
HB-065337,City Hotel,1,105,2025,March,14,31,2025-03-31,2,2,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,110.7,0,1
HB-105196,City Hotel,0,10,2025,January,5,31,2025-01-31,0,2,3,1.0,0,BB,CHN,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,183.0,0,2
HB-009262,Resort Hotel,1,44,2024,November,45,5,2024-11-05,2,5,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,82.8,0,1
HB-086865,City Hotel,0,115,2024,April,15,8,2024-04-08,0,2,1,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,2,No Deposit,1.0,,34,Transient-Party,57.5,0,1
HB-004418,Resort Hotel,1,110,2024,March,11,14,2024-03-14,4,10,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,65.31,0,0
HB-095092,City Hotel,0,121,2024,August,32,8,2024-08-08,2,5,3,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,2,No Deposit,14.0,,0,Transient,166.25,0,0
HB-002201,Resort Hotel,0,1,2023,October,40,5,2023-10-05,1,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,G,0,No Deposit,240.0,,0,Group,61.5,0,1
HB-051537,City Hotel,1,50,2024,May,21,21,2024-05-21,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.9,0,0
HB-054593,City Hotel,1,99,2024,July,29,21,2024-07-21,0,1,2,1.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,130.5,0,0
HB-068624,City Hotel,1,99,2025,May,21,19,2025-05-19,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,121.0,,0,Transient,89.1,0,0
HB-096286,City Hotel,0,24,2024,August,35,29,2024-08-29,1,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,40.0,0,Transient,67.0,1,1
HB-111784,City Hotel,0,76,2025,May,19,8,2025-05-08,2,5,2,0.0,0,HB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,133.48,0,0
HB-117074,City Hotel,0,144,2025,July,30,22,2025-07-22,2,5,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,D,A,1,No Deposit,83.0,,0,Transient,132.6,0,0
HB-100896,City Hotel,0,59,2024,October,44,31,2024-10-31,1,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,60.35,0,1
HB-095661,City Hotel,0,101,2024,August,34,20,2024-08-20,1,1,2,1.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,134.1,0,1
HB-117012,City Hotel,0,171,2025,July,30,26,2025-07-26,0,3,1,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,4,No Deposit,9.0,,0,Transient,121.5,0,1
HB-077348,City Hotel,1,190,2024,April,15,9,2024-04-09,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,1,13,1,A,A,0,No Deposit,,,31,Transient-Party,70.0,0,0
HB-060505,City Hotel,1,47,2024,November,46,12,2024-11-12,2,2,2,0.0,0,BB,IND,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,85.75,0,1
HB-012039,Resort Hotel,1,6,2025,June,24,10,2025-06-10,0,1,2,2.0,0,BB,ESP,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,180.0,0,0
HB-116029,City Hotel,0,414,2025,July,28,13,2025-07-13,0,2,1,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,A,A,1,No Deposit,6.0,,0,Transient-Party,95.5,0,0
HB-059825,City Hotel,1,482,2024,November,44,3,2024-11-03,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-000553,Resort Hotel,0,104,2023,July,29,19,2023-07-19,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,115.0,,0,Contract,123.0,0,1
HB-090308,City Hotel,0,65,2024,June,22,2,2024-06-02,0,3,2,0.0,0,SC,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,132.0,,0,Transient,72.25,0,0
HB-023219,Resort Hotel,0,53,2024,April,16,15,2024-04-15,1,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,241.0,,0,Transient,59.4,1,1
HB-043451,City Hotel,0,74,2023,September,38,18,2023-09-18,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-022279,Resort Hotel,0,8,2024,March,12,19,2024-03-19,2,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,F,0,No Deposit,240.0,,0,Transient,71.33,0,0
HB-047516,City Hotel,1,10,2024,February,8,25,2024-02-25,0,3,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.0,0,0
HB-095692,City Hotel,0,107,2024,August,34,21,2024-08-21,2,0,2,0.0,0,BB,ITA,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,99.0,0,0
HB-090729,City Hotel,0,3,2024,June,23,7,2024-06-07,0,3,1,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,7.0,,0,Transient,109.85,0,2
HB-027618,Resort Hotel,0,84,2024,August,35,28,2024-08-28,2,5,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,G,G,2,No Deposit,240.0,,0,Transient-Party,297.57,0,1
HB-017307,Resort Hotel,0,55,2023,September,39,30,2023-09-30,0,4,2,0.0,0,BB,IRL,Direct,Direct,0,0,0,D,E,0,No Deposit,250.0,,0,Transient,68.8,0,0
HB-061748,City Hotel,1,122,2024,December,52,25,2024-12-25,2,2,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,113.78,0,1
HB-105525,City Hotel,0,34,2025,February,6,7,2025-02-07,0,4,2,0.0,1,HB,FRA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,7.0,,0,Transient,89.54,0,2
HB-085509,City Hotel,0,0,2024,March,11,14,2024-03-14,1,2,1,0.0,0,BB,AUS,Corporate,Corporate,0,0,0,A,D,0,No Deposit,,174.0,0,Transient,79.0,0,0
HB-108635,City Hotel,0,6,2025,March,13,29,2025-03-29,0,2,1,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,10.0,,0,Transient,79.2,0,0
HB-041788,City Hotel,0,53,2023,August,34,24,2023-08-24,1,1,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-057868,City Hotel,1,34,2024,October,40,2,2024-10-02,2,1,2,0.0,0,SC,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,0
HB-024153,Resort Hotel,0,24,2024,May,19,7,2024-05-07,2,5,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,15.0,,0,Transient-Party,85.0,0,0
HB-072829,City Hotel,1,131,2025,August,32,7,2025-08-07,1,4,3,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,252.0,0,2
HB-119194,City Hotel,0,213,2025,August,35,28,2025-08-28,1,3,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,19.0,,0,Transient-Party,104.0,0,0
HB-074229,City Hotel,1,278,2023,July,29,22,2023-07-22,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,No Deposit,1.0,,0,Contract,62.0,0,0
HB-095346,City Hotel,0,8,2024,August,33,16,2024-08-16,0,2,2,0.0,0,SC,AUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,133.0,0,1
HB-036586,Resort Hotel,0,132,2025,May,20,18,2025-05-18,2,5,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,143.0,,0,Transient,40.95,0,0
HB-023496,Resort Hotel,0,6,2024,April,17,26,2024-04-26,0,1,2,0.0,0,BB,ESP,Direct,Direct,0,0,0,A,D,0,No Deposit,,,0,Transient,77.0,0,1
HB-098502,City Hotel,0,85,2024,September,39,29,2024-09-29,0,2,2,0.0,0,BB,BRA,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,158.0,0,Transient,129.73,0,0
HB-044405,City Hotel,0,88,2023,October,40,5,2023-10-05,1,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,26.0,,77,Transient-Party,112.2,0,0
HB-054121,City Hotel,1,365,2024,July,27,7,2024-07-07,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-097386,City Hotel,0,5,2024,September,37,15,2024-09-15,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,159.0,0,1
HB-059162,City Hotel,1,240,2024,October,43,21,2024-10-21,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,37.0,,0,Transient,110.0,0,0
HB-078584,City Hotel,0,7,2023,December,49,10,2023-12-10,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,1,A,A,0,No Deposit,,40.0,0,Transient,65.0,0,0
HB-017023,Resort Hotel,0,3,2023,September,37,17,2023-09-17,1,3,2,2.0,0,BB,ITA,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,132.75,0,0
HB-079622,City Hotel,0,6,2023,October,43,28,2023-10-28,0,3,2,0.0,0,BB,ISR,Groups,TA/TO,0,0,0,A,A,1,No Deposit,37.0,,6,Transient-Party,75.0,0,0
HB-019946,Resort Hotel,0,0,2024,January,2,9,2024-01-09,0,1,1,0.0,0,BB,IRL,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,38.0,0,0
HB-074869,City Hotel,1,164,2023,August,33,14,2023-08-14,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,60.0,0,0
HB-009728,Resort Hotel,1,31,2024,December,1,30,2024-12-30,0,2,2,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient-Party,340.0,0,1
HB-070666,City Hotel,1,204,2025,June,25,20,2025-06-20,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,130.5,0,0
HB-042353,City Hotel,1,65,2023,September,36,5,2023-09-05,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-013715,Resort Hotel,1,22,2025,August,35,27,2025-08-27,2,2,2,2.0,0,BB,GBR,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,295.0,0,0
HB-068272,City Hotel,1,104,2025,May,20,15,2025-05-15,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,170.0,0,0
HB-020665,Resort Hotel,0,14,2024,February,6,5,2024-02-05,0,2,2,0.0,0,BB,ESP,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,177.0,,0,Contract,35.0,1,0
HB-039235,Resort Hotel,0,190,2025,August,31,2,2025-08-02,2,8,2,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,40.0,,0,Contract,161.4,0,0
HB-038673,Resort Hotel,0,72,2025,July,29,19,2025-07-19,2,5,2,0.0,0,HB,ESP,Direct,Direct,0,0,0,F,F,0,No Deposit,250.0,,0,Transient,306.0,1,1
HB-062979,City Hotel,1,61,2025,January,4,25,2025-01-25,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,326.0,,0,Transient,80.0,0,0
HB-028182,Resort Hotel,0,10,2024,September,38,20,2024-09-20,0,3,2,0.0,1,FB,PRT,Direct,Direct,0,0,0,D,H,1,No Deposit,250.0,,0,Transient,173.6,1,2
HB-051072,City Hotel,1,91,2024,May,20,13,2024-05-13,1,2,2,1.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient-Party,140.4,0,0
HB-059724,City Hotel,1,166,2024,November,44,1,2024-11-01,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,236.0,,0,Transient,110.0,0,0
HB-069121,City Hotel,1,212,2025,May,21,25,2025-05-25,1,3,2,0.0,0,SC,GRC,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,1
HB-017957,Resort Hotel,0,6,2024,April,14,6,2024-04-06,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,1,A,D,2,No Deposit,,94.0,0,Transient,39.0,0,0
HB-053015,City Hotel,1,188,2024,June,24,15,2024-06-15,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,119.0,,39,Transient,130.0,0,0
HB-030199,Resort Hotel,0,97,2025,June,24,12,2025-06-12,1,1,2,1.0,0,BB,PRT,Corporate,Direct,1,0,4,A,A,1,No Deposit,,255.0,0,Transient,108.5,1,1
HB-025032,Resort Hotel,0,94,2024,June,24,10,2024-06-10,0,2,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,8,No Deposit,240.0,,0,Transient-Party,163.0,1,0
HB-040401,City Hotel,0,84,2023,July,30,25,2023-07-25,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,8.0,,0,Transient,76.5,0,2
HB-011981,Resort Hotel,1,35,2025,June,23,7,2025-06-07,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,,251.0,0,Transient,126.0,0,0
HB-009961,Resort Hotel,1,178,2025,January,5,28,2025-01-28,8,20,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,242.0,,0,Transient,55.8,0,3
HB-044686,City Hotel,0,204,2023,October,41,9,2023-10-09,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,72.75,0,0
HB-089765,City Hotel,0,5,2024,May,21,24,2024-05-24,0,2,2,0.0,0,BB,ARG,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,78.0,0,Transient-Party,110.0,0,1
HB-032713,Resort Hotel,0,1,2025,February,9,28,2025-02-28,0,2,2,0.0,0,BB,PRT,Direct,Direct,1,0,1,A,A,0,No Deposit,250.0,,0,Group,45.5,0,1
HB-009486,Resort Hotel,1,183,2024,December,49,3,2024-12-03,2,1,2,0.0,0,FB,PRT,Groups,TA/TO,0,0,0,A,C,1,Non Refund,38.0,,0,Transient,72.0,0,0
HB-020277,Resort Hotel,0,4,2024,January,4,22,2024-01-22,0,1,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,0,No Deposit,250.0,,0,Transient,57.0,1,0
HB-043209,City Hotel,0,76,2023,September,37,16,2023-09-16,0,2,2,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,D,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-092769,City Hotel,0,94,2024,July,28,8,2024-07-08,2,2,3,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,146.7,0,1
HB-056463,City Hotel,1,66,2024,September,36,7,2024-09-07,0,1,1,0.0,0,BB,ITA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,92.7,0,0
HB-041264,City Hotel,1,0,2023,August,33,14,2023-08-14,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,109.0,0,0
HB-090417,City Hotel,0,8,2024,June,23,4,2024-06-04,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,146.0,0,0
HB-077534,City Hotel,0,6,2023,September,38,20,2023-09-20,2,0,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,7.0,,0,Transient,152.84,0,1
HB-008025,Resort Hotel,1,211,2024,September,36,7,2024-09-07,0,3,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,D,D,0,Non Refund,1.0,,0,Transient,89.0,0,0
HB-084106,City Hotel,0,15,2024,February,8,19,2024-02-19,0,1,1,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,A,0,No Deposit,,67.0,0,Transient-Party,81.0,0,0
HB-115537,City Hotel,0,171,2025,July,27,4,2025-07-04,0,3,2,2.0,0,HB,FRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,233.1,0,1
HB-015401,Resort Hotel,0,109,2025,June,25,16,2025-06-16,4,7,3,0.0,0,FB,PRT,Direct,Direct,1,0,2,F,F,0,No Deposit,,,0,Transient,318.82,1,2
HB-111872,City Hotel,0,96,2025,May,20,14,2025-05-14,2,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,138.0,0,0
HB-014031,Resort Hotel,0,9,2024,September,38,21,2024-09-21,2,8,1,0.0,0,BB,PRT,Direct,Direct,0,0,1,E,E,0,No Deposit,,,0,Transient,95.0,0,3
HB-014907,Resort Hotel,0,31,2024,March,12,24,2024-03-24,0,3,2,1.0,0,BB,PRT,Online TA,TA/TO,1,0,1,E,E,1,No Deposit,240.0,,0,Group,85.0,0,1
HB-068533,City Hotel,1,175,2025,May,21,19,2025-05-19,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,44.0,,0,Transient,90.0,0,0
HB-052282,City Hotel,1,13,2024,June,22,2,2024-06-02,0,3,2,0.0,0,BB,DNK,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,152.67,0,0
HB-061887,City Hotel,1,37,2024,December,52,28,2024-12-28,0,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,0
HB-118795,City Hotel,0,109,2025,August,34,20,2025-08-20,2,4,2,0.0,1,BB,COL,Direct,Direct,0,0,0,B,B,2,No Deposit,14.0,,0,Transient-Party,146.25,0,2
HB-034398,Resort Hotel,0,96,2025,March,11,12,2025-03-12,4,7,2,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,52.55,0,0
HB-001495,Resort Hotel,0,122,2023,September,35,1,2023-09-01,0,4,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,E,F,0,No Deposit,240.0,,0,Transient,155.0,0,2
HB-046282,City Hotel,1,146,2023,December,52,29,2023-12-29,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,21.0,,99,Transient-Party,85.0,0,0
HB-077365,City Hotel,1,19,2023,October,40,6,2023-10-06,0,3,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,1,1,0,A,A,0,Non Refund,82.0,,0,Transient,80.0,0,0
HB-114525,City Hotel,0,63,2025,June,25,21,2025-06-21,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,85.0,,0,Transient,89.1,0,0
HB-111759,City Hotel,0,129,2025,May,20,12,2025-05-12,1,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,120.0,0,1
HB-050307,City Hotel,1,295,2024,April,17,28,2024-04-28,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-007293,Resort Hotel,1,180,2024,August,31,1,2024-08-01,2,5,2,1.0,0,Undefined,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,196.0,,0,Transient-Party,177.5,0,2
HB-073705,City Hotel,1,112,2025,August,35,31,2025-08-31,1,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,145.0,0,2
HB-087302,City Hotel,0,1,2024,April,16,16,2024-04-16,0,1,2,0.0,0,SC,MAR,Online TA,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,89.0,1,1
HB-040339,City Hotel,1,22,2023,July,29,22,2023-07-22,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient-Party,62.0,0,0
HB-106992,City Hotel,0,84,2025,March,10,3,2025-03-03,1,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.2,0,1
HB-113485,City Hotel,0,148,2025,June,22,1,2025-06-01,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,143.71,0,0
HB-089854,City Hotel,0,9,2024,May,21,26,2024-05-26,0,2,3,0.0,0,BB,PRT,Direct,Direct,0,0,0,G,G,0,No Deposit,,,0,Transient,218.45,0,2
HB-114903,City Hotel,0,26,2025,June,26,26,2025-06-26,1,1,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,8.0,,0,Transient,269.5,0,1
HB-114883,City Hotel,0,25,2025,June,26,27,2025-06-27,0,1,2,0.0,0,BB,MAR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,280.0,0,Transient-Party,100.0,0,0
HB-101528,City Hotel,0,45,2024,November,45,7,2024-11-07,2,5,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,,0,Transient,75.0,0,1
HB-049933,City Hotel,1,68,2024,April,16,21,2024-04-21,0,1,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,137.7,0,1
HB-055598,City Hotel,1,145,2024,August,33,17,2024-08-17,0,2,2,1.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,1,No Deposit,,,0,Transient-Party,147.0,0,1
HB-073306,City Hotel,1,121,2025,August,34,18,2025-08-18,1,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,125.0,0,0
HB-085019,City Hotel,0,31,2024,March,10,5,2024-03-05,2,1,2,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,83.9,0,1
HB-063238,City Hotel,1,94,2025,February,6,3,2025-02-03,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,93.6,0,0
HB-098074,City Hotel,0,296,2024,September,38,21,2024-09-21,0,4,1,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,26.0,,0,Transient-Party,81.0,0,0
HB-058740,City Hotel,1,93,2024,October,42,15,2024-10-15,2,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,34.0,,0,Transient,115.0,0,0
HB-103742,City Hotel,0,55,2024,December,1,30,2024-12-30,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,K,0,No Deposit,9.0,,0,Transient,131.4,0,1
HB-057431,City Hotel,1,253,2024,September,39,26,2024-09-26,1,2,1,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,2.0,0,0
HB-048355,City Hotel,0,89,2024,March,12,21,2024-03-21,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,8.0,,0,Transient,83.66,0,1
HB-040941,City Hotel,0,0,2023,August,32,10,2023-08-10,1,0,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,115.0,0,0
HB-052211,City Hotel,1,330,2024,June,22,2,2024-06-02,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-060248,City Hotel,1,626,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.8,0,0
HB-039406,Resort Hotel,0,174,2025,August,32,7,2025-08-07,3,7,2,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,232.0,0,3
HB-055773,City Hotel,1,41,2024,August,34,20,2024-08-20,2,5,2,0.0,0,BB,HUN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,135.9,0,0
HB-056210,City Hotel,1,419,2024,September,35,1,2024-09-01,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-092652,City Hotel,0,60,2024,July,28,9,2024-07-09,0,1,3,0.0,0,BB,COL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,152.1,0,2
HB-071255,City Hotel,1,102,2025,June,27,30,2025-06-30,1,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,9.0,,0,Transient,112.0,0,1
HB-029026,Resort Hotel,0,1,2024,October,42,19,2024-10-19,0,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,306.0,,0,Group,42.65,0,0
HB-024649,Resort Hotel,0,126,2024,May,21,21,2024-05-21,2,6,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,50.06,0,1
HB-048193,City Hotel,1,91,2024,March,12,18,2024-03-18,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,29.0,,20,Transient,75.0,0,0
HB-006427,Resort Hotel,1,17,2024,June,24,10,2024-06-10,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,129.0,0,0
HB-039590,Resort Hotel,0,24,2025,August,34,22,2025-08-22,0,5,2,0.0,0,HB,PRT,Online TA,Direct,0,0,0,A,A,0,No Deposit,241.0,,0,Transient,223.6,1,1
HB-006453,Resort Hotel,1,277,2024,June,24,12,2024-06-12,2,2,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,110.0,0,0
HB-082684,City Hotel,0,4,2024,January,1,2,2024-01-02,2,1,2,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,26.0,,0,Transient-Party,109.0,0,0
HB-003206,Resort Hotel,0,44,2023,November,47,21,2023-11-21,0,1,2,0.0,1,HB,PRT,Online TA,TA/TO,0,0,0,A,E,1,No Deposit,240.0,,0,Transient,73.5,1,3
HB-096779,City Hotel,0,62,2024,September,36,5,2024-09-05,1,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,124.5,1,2
HB-110497,City Hotel,0,102,2025,April,17,24,2025-04-24,1,3,2,0.0,0,BB,IRL,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,424.0,0,Transient-Party,100.0,0,0
HB-080710,City Hotel,0,32,2023,November,47,20,2023-11-20,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,119.0,,0,Transient-Party,73.0,0,0
HB-042888,City Hotel,0,168,2023,September,37,11,2023-09-11,0,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,50.0,0,0
HB-025698,Resort Hotel,0,3,2024,July,28,8,2024-07-08,1,2,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,241.0,,0,Transient,157.08,0,0
HB-015176,Resort Hotel,1,246,2023,September,36,5,2023-09-05,2,5,2,0.0,0,BB,,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,96.0,,0,Transient-Party,58.95,0,0
HB-010166,Resort Hotel,1,16,2025,February,8,17,2025-02-17,1,2,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,498.0,0,Transient-Party,40.0,0,0
HB-043766,City Hotel,0,86,2023,September,38,24,2023-09-24,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,105.0,0,0
HB-061722,City Hotel,1,119,2024,December,52,24,2024-12-24,1,1,2,1.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,109.8,0,0
HB-038007,Resort Hotel,0,0,2025,July,27,3,2025-07-03,1,2,2,0.0,0,SC,CHE,Direct,Direct,0,0,0,G,I,0,No Deposit,,,0,Transient,0.0,0,2
HB-082214,City Hotel,1,317,2024,September,37,9,2024-09-09,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,58.0,,56,Transient,90.0,0,0
HB-043658,City Hotel,0,69,2023,September,38,22,2023-09-22,0,2,1,0.0,0,HB,ITA,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,3.0,,65,Transient-Party,83.0,0,0
HB-043308,City Hotel,0,72,2023,September,38,18,2023-09-18,0,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient-Party,108.0,0,0
HB-073665,City Hotel,1,158,2025,August,35,29,2025-08-29,0,5,1,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,88.96,0,0
HB-113172,City Hotel,0,82,2025,May,22,31,2025-05-31,0,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,2,No Deposit,9.0,,0,Transient-Party,198.0,0,2
HB-060535,City Hotel,1,114,2024,November,46,13,2024-11-13,2,4,2,0.0,0,SC,RUS,Online TA,TA/TO,0,0,0,A,B,3,No Deposit,9.0,,0,Transient,74.8,0,1
HB-074243,City Hotel,1,377,2023,October,43,29,2023-10-29,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Contract,62.0,0,0
HB-007454,Resort Hotel,1,155,2024,August,32,10,2024-08-10,0,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,240.0,0,0
HB-007797,Resort Hotel,1,42,2024,August,35,27,2024-08-27,2,2,2,2.0,0,BB,MAR,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,269.0,0,0
HB-008840,Resort Hotel,1,181,2024,October,42,16,2024-10-16,2,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,11.0,,0,Transient,37.0,0,0
HB-095717,City Hotel,0,212,2024,August,33,16,2024-08-16,2,5,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,63.11,0,1
HB-051003,City Hotel,1,22,2024,May,20,13,2024-05-13,0,2,2,2.0,0,BB,ITA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,221.0,0,1
HB-027749,Resort Hotel,0,59,2024,September,36,3,2024-09-03,2,5,4,0.0,0,BB,PRT,Direct,Direct,0,0,0,H,H,0,No Deposit,250.0,,0,Transient,251.0,1,0
HB-028498,Resort Hotel,0,6,2024,September,39,27,2024-09-27,2,6,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,117.25,1,1
HB-030153,Resort Hotel,0,0,2024,November,46,15,2024-11-15,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,314.0,,0,Transient,52.0,0,0
HB-008078,Resort Hotel,1,129,2024,September,37,10,2024-09-10,2,2,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,314.0,,0,Transient,133.2,0,0
HB-108418,City Hotel,0,0,2025,March,13,26,2025-03-26,1,0,1,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,108.0,0,0
HB-104608,City Hotel,0,33,2025,January,3,17,2025-01-17,0,2,1,0.0,0,BB,ESP,Groups,TA/TO,0,0,0,A,E,1,No Deposit,19.0,,0,Transient-Party,75.0,0,0
HB-028775,Resort Hotel,0,1,2025,March,13,29,2025-03-29,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,1,0,1,A,A,0,No Deposit,196.0,,0,Transient,70.0,0,0
HB-050409,City Hotel,1,184,2024,April,18,30,2024-04-30,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,118.0,0,1
HB-113167,City Hotel,0,99,2025,May,22,30,2025-05-30,0,4,3,0.0,0,HB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,205.2,0,2
HB-083974,City Hotel,0,4,2024,February,7,14,2024-02-14,2,1,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,E,E,0,No Deposit,14.0,,0,Transient,127.0,0,0
HB-066561,City Hotel,1,82,2025,April,17,21,2025-04-21,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-116908,City Hotel,0,147,2025,July,30,24,2025-07-24,1,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,,0,Transient,80.1,0,0
HB-102530,City Hotel,0,35,2024,November,48,28,2024-11-28,1,1,1,0.0,0,BB,SVN,Groups,TA/TO,0,0,0,A,A,1,No Deposit,,,0,Transient-Party,65.0,0,0
HB-071003,City Hotel,1,28,2025,June,26,27,2025-06-27,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,129.5,0,1
HB-019003,Resort Hotel,0,16,2023,December,48,3,2023-12-03,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,46.4,0,1
HB-013512,Resort Hotel,1,168,2025,August,33,17,2025-08-17,2,6,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,217.5,0,1
HB-044215,City Hotel,0,164,2023,October,40,2,2023-10-02,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,19.0,,0,Transient-Party,100.0,0,0
HB-020463,Resort Hotel,0,1,2024,February,5,2,2024-02-02,0,5,1,0.0,0,BB,IRL,Offline TA/TO,TA/TO,1,0,1,A,A,0,No Deposit,6.0,,0,Transient,25.0,0,0
HB-034246,Resort Hotel,0,57,2025,March,11,11,2025-03-11,2,5,1,0.0,0,HB,DEU,Groups,TA/TO,0,0,0,D,D,0,No Deposit,298.0,,0,Transient-Party,51.0,0,0
HB-063586,City Hotel,1,105,2025,February,7,14,2025-02-14,0,4,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,147.9,0,0
HB-060306,City Hotel,1,277,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-052632,City Hotel,1,71,2024,June,23,9,2024-06-09,0,1,2,0.0,0,BB,JPN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.9,0,0
HB-107311,City Hotel,0,109,2025,March,10,6,2025-03-06,1,4,1,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,,0,Transient,74.8,0,0
HB-042167,City Hotel,0,22,2023,September,35,1,2023-09-01,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,105.0,0,2
HB-000618,Resort Hotel,1,41,2023,July,29,22,2023-07-22,1,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,178.4,0,0
HB-060432,City Hotel,1,300,2024,November,46,11,2024-11-11,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,65.0,0,0
HB-010885,Resort Hotel,1,124,2025,April,15,9,2025-04-09,2,5,2,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,492.0,,0,Transient,80.0,0,0
HB-048228,City Hotel,1,17,2024,March,12,19,2024-03-19,1,1,1,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,97.0,0,0
HB-014114,Resort Hotel,0,303,2024,September,38,17,2024-09-17,3,6,1,0.0,0,BB,IRL,Direct,Direct,0,0,2,E,E,0,No Deposit,,,0,Transient,71.0,0,1
HB-095639,City Hotel,0,219,2024,August,34,20,2024-08-20,1,1,3,0.0,0,HB,ITA,Groups,TA/TO,0,0,0,A,A,1,No Deposit,1.0,,0,Transient-Party,139.2,0,0
HB-025145,Resort Hotel,0,26,2025,May,22,30,2025-05-30,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,11,A,D,0,No Deposit,,154.0,0,Transient,45.0,0,0
HB-001788,Resort Hotel,1,94,2023,September,37,14,2023-09-14,1,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,89.0,0,0
HB-026049,Resort Hotel,0,0,2024,July,29,19,2024-07-19,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,339.0,,0,Transient,95.2,0,0
HB-076011,City Hotel,1,336,2023,September,38,18,2023-09-18,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-043635,City Hotel,0,27,2023,September,38,21,2023-09-21,1,2,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,22.0,,0,Transient,97.0,0,0
HB-110464,City Hotel,0,172,2025,April,17,23,2025-04-23,2,3,3,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,1,No Deposit,14.0,,0,Transient,120.0,0,0
HB-073273,City Hotel,1,23,2025,August,34,18,2025-08-18,0,1,3,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,230.0,0,1
HB-082792,City Hotel,1,68,2024,February,7,17,2024-02-17,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,37.0,,0,Transient,75.0,0,0
HB-112705,City Hotel,0,147,2025,May,21,23,2025-05-23,0,5,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,,0,Transient,162.0,0,1
HB-004432,Resort Hotel,1,51,2024,March,11,17,2024-03-17,0,1,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,66.0,,0,Transient-Party,26.0,0,0
HB-004697,Resort Hotel,1,24,2024,March,13,28,2024-03-28,2,5,1,0.0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,58.0,0,0
HB-034122,Resort Hotel,0,0,2025,March,11,11,2025-03-11,1,1,1,0.0,0,BB,DNK,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,241.0,,0,Transient,64.0,0,1
HB-044702,City Hotel,0,204,2023,October,41,9,2023-10-09,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,12.0,,0,Transient-Party,72.75,0,0
HB-067083,City Hotel,1,222,2025,April,18,28,2025-04-28,1,2,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,135.33,0,3
HB-064701,City Hotel,1,92,2025,March,11,15,2025-03-15,0,3,2,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,85.0,0,0
HB-055141,City Hotel,1,167,2024,August,32,6,2024-08-06,0,1,2,0.0,0,BB,ISR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,105.3,0,0
HB-088040,City Hotel,0,57,2024,April,16,21,2024-04-21,2,7,2,0.0,0,BB,DZA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,114.66,0,1
HB-021269,Resort Hotel,0,4,2024,February,8,22,2024-02-22,1,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,240.0,,0,Transient,48.0,0,1
HB-087942,City Hotel,0,9,2024,April,17,27,2024-04-27,0,2,1,0.0,0,BB,FRA,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,91.0,0,Transient,95.0,0,0
HB-065164,City Hotel,1,112,2025,March,13,26,2025-03-26,1,0,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,2
HB-095788,City Hotel,0,28,2024,August,34,21,2024-08-21,2,1,2,0.0,0,SC,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,134.37,0,1
HB-080645,City Hotel,0,32,2023,November,47,20,2023-11-20,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,119.0,,0,Transient-Party,73.0,0,0
HB-090738,City Hotel,0,5,2024,June,23,7,2024-06-07,0,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,146.0,0,1
HB-072298,City Hotel,1,253,2025,July,30,25,2025-07-25,2,6,1,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.9,0,1
HB-069536,City Hotel,1,71,2025,June,22,1,2025-06-01,0,3,2,2.0,0,BB,ITA,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,,0,Transient,250.0,0,0
HB-063281,City Hotel,1,58,2025,February,6,5,2025-02-05,2,0,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,0
HB-091758,City Hotel,0,235,2024,June,26,24,2024-06-24,0,2,2,0.0,0,BB,FRA,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,61,Transient-Party,65.0,0,1
HB-086987,City Hotel,0,2,2024,April,15,12,2024-04-12,0,1,2,0.0,0,SC,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,119.0,0,0
HB-029686,Resort Hotel,0,28,2024,November,44,2,2024-11-02,0,2,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,,0,Transient,37.8,0,1
HB-096407,City Hotel,0,16,2024,August,35,28,2024-08-28,2,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,168.0,,0,Transient,107.0,0,0
HB-081903,City Hotel,1,181,2024,May,18,5,2024-05-05,2,4,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,26.0,,42,Transient,90.0,0,0
HB-077269,City Hotel,1,5,2023,September,38,20,2023-09-20,2,0,2,0.0,0,BB,PRT,Corporate,Corporate,1,1,0,A,A,0,Non Refund,78.0,,0,Transient,100.0,0,0
HB-029682,Resort Hotel,0,110,2024,October,44,29,2024-10-29,2,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,314.0,,0,Transient,52.18,0,0
HB-102364,City Hotel,0,71,2024,November,48,25,2024-11-25,0,2,2,0.0,0,SC,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,79.2,0,2
HB-087959,City Hotel,0,45,2024,April,17,28,2024-04-28,0,1,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,106.2,0,1
HB-111241,City Hotel,0,99,2025,May,18,1,2025-05-01,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.0,0,1
HB-068323,City Hotel,1,104,2025,May,20,15,2025-05-15,1,2,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-017255,Resort Hotel,1,277,2023,October,40,5,2023-10-05,4,10,2,0.0,0,HB,GBR,Groups,Direct,0,1,0,E,E,0,Non Refund,273.0,,0,Transient,88.0,0,0
HB-045079,City Hotel,1,102,2023,October,42,16,2023-10-16,0,2,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,0,Transient-Party,101.5,0,0
HB-004416,Resort Hotel,1,14,2024,March,11,14,2024-03-14,3,6,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,68.0,0,1
HB-093943,City Hotel,0,63,2024,July,30,25,2024-07-25,1,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,94.5,0,1
HB-036175,Resort Hotel,0,257,2025,May,19,9,2025-05-09,0,4,2,0.0,0,HB,GBR,Groups,Direct,0,0,0,E,E,0,No Deposit,,,0,Transient-Party,101.0,0,0
HB-024550,Resort Hotel,0,64,2024,May,21,23,2024-05-23,1,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,240.0,,0,Transient,80.0,0,1
HB-080076,City Hotel,0,1,2023,November,45,10,2023-11-10,0,1,1,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,A,0,No Deposit,,45.0,0,Transient,0.0,0,0
HB-103799,City Hotel,0,190,2024,December,52,28,2024-12-28,0,4,2,0.0,0,BB,DEU,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,167.8,0,1
HB-119007,City Hotel,0,201,2025,August,34,24,2025-08-24,1,3,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,0
HB-015117,Resort Hotel,1,214,2023,October,40,3,2023-10-03,1,1,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,No Deposit,208.0,,0,Transient,34.0,0,0
HB-046485,City Hotel,1,145,2024,January,1,3,2024-01-03,2,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,85,Transient,65.0,0,0
HB-083014,City Hotel,0,16,2024,January,2,9,2024-01-09,2,2,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,15.0,,0,Transient,61.16,0,0
HB-013248,Resort Hotel,1,128,2025,August,32,6,2025-08-06,2,3,2,2.0,0,BB,GEO,Online TA,TA/TO,0,0,0,C,C,0,No Deposit,240.0,,0,Transient,269.0,0,1
HB-010560,Resort Hotel,1,144,2025,March,11,14,2025-03-14,4,14,1,0.0,0,HB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,440.0,,0,Transient-Party,44.0,0,0
HB-030457,Resort Hotel,0,3,2024,November,47,21,2024-11-21,1,1,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,115.0,,0,Transient,34.0,0,0
HB-110514,City Hotel,0,3,2025,April,17,27,2025-04-27,0,1,2,0.0,0,BB,RUS,Corporate,Corporate,0,0,0,A,A,1,No Deposit,,280.0,0,Transient,170.0,0,0
HB-055203,City Hotel,0,217,2024,August,32,7,2024-08-07,2,4,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,80.75,0,1
HB-000877,Resort Hotel,0,67,2023,August,31,2,2023-08-02,2,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,163.5,0,1
HB-007911,Resort Hotel,1,73,2024,September,36,2,2024-09-02,0,1,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,E,E,1,No Deposit,240.0,,0,Transient,169.0,0,0
HB-064452,City Hotel,1,51,2025,March,11,10,2025-03-10,0,2,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,106.2,0,0
HB-080519,City Hotel,0,22,2023,November,46,17,2023-11-17,0,1,1,0.0,0,BB,AUT,Corporate,Corporate,0,0,0,A,D,1,No Deposit,,127.0,0,Transient-Party,62.0,0,1
HB-114685,City Hotel,0,54,2025,June,26,23,2025-06-23,1,2,2,0.0,0,SC,AUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,126.67,0,1
HB-027774,Resort Hotel,0,252,2024,August,34,25,2024-08-25,4,13,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40.0,,0,Contract,70.0,0,2
HB-050282,City Hotel,1,295,2024,April,17,28,2024-04-28,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-091516,City Hotel,0,39,2024,June,25,21,2024-06-21,0,2,1,2.0,0,BB,USA,Direct,Direct,0,0,0,F,F,0,No Deposit,14.0,,0,Transient,168.3,0,2
HB-059242,City Hotel,1,52,2024,October,43,23,2024-10-23,2,3,2,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,83.0,,0,Transient,145.24,0,0
HB-070983,City Hotel,1,152,2025,June,26,26,2025-06-26,1,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,126.0,0,0
HB-073220,City Hotel,1,181,2025,August,33,16,2025-08-16,2,5,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,103.37,0,2
HB-064040,City Hotel,1,12,2025,February,9,27,2025-02-27,1,0,2,0.0,0,SC,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,88.0,0,0
HB-097070,City Hotel,0,55,2024,September,36,7,2024-09-07,1,4,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,89.0,,0,Transient,122.4,0,2
HB-044081,City Hotel,1,92,2023,September,39,30,2023-09-30,0,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-023065,Resort Hotel,0,0,2024,April,15,13,2024-04-13,0,2,1,0.0,0,BB,DEU,Direct,Direct,0,0,0,F,F,0,No Deposit,,,0,Transient,95.0,0,0
HB-093218,City Hotel,0,93,2024,July,28,12,2024-07-12,2,5,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,71.4,0,1
HB-026887,Resort Hotel,0,164,2024,August,32,6,2024-08-06,2,6,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,314.0,,0,Transient-Party,131.6,0,0
HB-022272,Resort Hotel,0,5,2024,March,12,21,2024-03-21,1,0,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,C,1,No Deposit,336.0,,0,Transient,29.0,0,1
HB-050351,City Hotel,1,443,2024,April,18,29,2024-04-29,0,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,60.0,0,0
HB-099901,City Hotel,0,159,2024,October,42,16,2024-10-16,2,2,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,108.0,0,0
HB-106795,City Hotel,0,17,2025,February,9,26,2025-02-26,2,3,1,0.0,0,SC,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,48.5,0,0
HB-113984,City Hotel,0,1,2025,June,24,10,2025-06-10,2,3,2,0.0,0,BB,GRC,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,83.0,,0,Transient,150.55,0,0
HB-057124,City Hotel,1,280,2024,September,38,19,2024-09-19,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,6.0,,35,Transient,110.0,0,0
HB-020274,Resort Hotel,0,1,2024,January,3,21,2024-01-21,0,1,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,40.0,0,1
HB-013163,Resort Hotel,1,28,2025,August,31,3,2025-08-03,0,2,2,0.0,0,BB,PHL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,225.0,0,0
HB-020729,Resort Hotel,0,72,2024,February,6,6,2024-02-06,2,1,2,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,73.33,0,0
HB-016201,Resort Hotel,0,0,2023,August,33,17,2023-08-17,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,C,0,No Deposit,240.0,,0,Transient,153.0,0,2
HB-090951,City Hotel,0,17,2024,June,24,13,2024-06-13,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,101.0,0,1
HB-102694,City Hotel,0,17,2024,December,49,2,2024-12-02,0,2,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,9.0,,0,Transient,157.5,0,2
HB-068596,City Hotel,1,105,2025,May,21,19,2025-05-19,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-115989,City Hotel,0,4,2025,July,28,11,2025-07-11,0,2,1,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,140.0,0,2
HB-079727,City Hotel,1,350,2024,September,40,30,2024-09-30,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,1,0,A,A,0,Non Refund,4.0,,17,Transient,90.0,0,0
HB-029853,Resort Hotel,0,10,2024,November,44,3,2024-11-03,1,3,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,61.5,0,2
HB-104689,City Hotel,0,29,2025,January,3,18,2025-01-18,0,3,1,0.0,0,BB,NOR,Groups,TA/TO,0,0,0,A,A,0,No Deposit,171.0,,0,Transient-Party,65.0,0,0
HB-097982,City Hotel,0,14,2024,September,38,22,2024-09-22,0,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,184.0,0,0
HB-014076,Resort Hotel,0,11,2024,July,28,10,2024-07-10,5,10,2,0.0,0,BB,,Direct,Direct,0,0,0,A,I,2,No Deposit,,,0,Transient,4.0,0,0
HB-076954,City Hotel,1,342,2023,September,38,24,2023-09-24,2,4,2,0.0,0,BB,PRT,Groups,TA/TO,0,1,0,A,A,0,Non Refund,1.0,,0,Transient,170.0,0,0
HB-002577,Resort Hotel,0,19,2023,October,42,22,2023-10-22,1,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,240.0,,0,Transient,81.5,0,1
HB-067942,City Hotel,1,29,2025,May,19,10,2025-05-10,0,1,1,0.0,0,BB,BEL,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,174.0,0,0
HB-107474,City Hotel,0,49,2025,March,11,10,2025-03-10,1,2,2,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,2,No Deposit,83.0,,0,Transient,86.76,1,1
HB-068569,City Hotel,1,105,2025,May,21,19,2025-05-19,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-060266,City Hotel,1,277,2024,November,45,7,2024-11-07,1,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,100.0,0,0
HB-015380,Resort Hotel,0,127,2023,July,27,4,2023-07-04,2,5,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,96.9,0,0
HB-087637,City Hotel,0,18,2024,April,16,20,2024-04-20,0,3,2,1.0,0,BB,KOR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,7.0,,0,Transient,167.74,0,2
HB-101417,City Hotel,0,92,2024,November,46,11,2024-11-11,0,1,2,0.0,0,BB,THA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,364.0,,0,Transient-Party,90.0,0,0
HB-114314,City Hotel,0,123,2025,June,25,17,2025-06-17,2,1,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient-Party,105.3,0,1
HB-021340,Resort Hotel,0,2,2024,February,8,25,2024-02-25,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,241.0,,0,Transient,36.96,0,1
HB-083516,City Hotel,0,31,2024,February,5,4,2024-02-04,0,2,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,1,No Deposit,,174.0,0,Transient-Party,77.0,0,0
HB-035982,Resort Hotel,0,221,2025,April,18,30,2025-04-30,2,5,2,0.0,0,HB,GBR,Groups,TA/TO,0,0,0,D,D,0,No Deposit,,,0,Transient-Party,83.43,0,0
HB-043476,City Hotel,1,24,2023,September,38,18,2023-09-18,1,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Contract,124.0,0,1
HB-085815,City Hotel,0,6,2025,July,28,11,2025-07-11,0,3,1,0.0,0,BB,PRT,Aviation,Corporate,1,0,5,D,D,0,No Deposit,,153.0,0,Transient,95.0,0,2
HB-083922,City Hotel,0,11,2024,February,7,14,2024-02-14,1,0,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,127.0,0,1
HB-000819,Resort Hotel,1,16,2023,July,31,31,2023-07-31,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,,0,Transient,173.0,0,3
HB-092852,City Hotel,0,13,2024,July,28,11,2024-07-11,1,1,1,0.0,0,BB,ESP,Corporate,Corporate,0,0,0,A,A,0,No Deposit,,62.0,0,Transient,79.0,0,0
HB-007236,Resort Hotel,1,46,2024,July,31,30,2024-07-30,0,1,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,179.0,0,0
HB-004930,Resort Hotel,1,121,2024,April,15,9,2024-04-09,2,5,2,0.0,0,HB,GBR,Groups,Direct,0,0,0,D,D,0,Non Refund,273.0,,0,Transient,72.0,0,0
HB-112478,City Hotel,0,248,2025,May,21,19,2025-05-19,2,4,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,7.0,,0,Transient,101.68,0,1
HB-104956,City Hotel,0,6,2025,January,4,23,2025-01-23,1,2,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,,0,Transient,54.21,0,1
HB-062923,City Hotel,1,130,2025,January,4,25,2025-01-25,0,2,2,0.0,0,SC,CHN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,71.28,0,2
HB-048308,City Hotel,1,60,2024,March,12,20,2024-03-20,2,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,3.0,,0,Transient,75.0,0,0
HB-093370,City Hotel,0,92,2024,July,29,17,2024-07-17,2,2,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,,0,Transient,137.7,0,0
HB-008302,Resort Hotel,0,329,2024,September,38,21,2024-09-21,4,10,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,75.0,,0,Contract,70.85,0,1
HB-118669,City Hotel,0,19,2025,August,34,22,2025-08-22,0,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,169.0,1,1
HB-087716,City Hotel,0,186,2024,April,17,22,2024-04-22,1,2,3,0.0,0,BB,ITA,Offline TA/TO,TA/TO,0,0,0,A,D,1,No Deposit,23.0,,0,Transient-Party,115.0,0,0
HB-023021,Resort Hotel,0,18,2024,April,15,9,2024-04-09,2,3,1,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,40.0,,0,Contract,33.3,0,0
HB-015355,Resort Hotel,0,128,2023,July,27,5,2023-07-05,2,2,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,,,0,Transient,108.9,1,0
HB-033229,Resort Hotel,0,89,2025,February,7,15,2025-02-15,0,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,242.0,,0,Transient,77.9,0,1
HB-041125,City Hotel,0,0,2023,August,32,12,2023-08-12,0,3,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,D,0,No Deposit,9.0,,0,Contract,138.0,0,0
HB-111249,City Hotel,0,55,2025,May,19,5,2025-05-05,1,2,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,,0,Transient,126.0,0,0
HB-004266,Resort Hotel,1,119,2024,February,9,27,2024-02-27,2,6,1,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient,35.1,0,0
HB-064580,City Hotel,1,52,2025,March,11,13,2025-03-13,1,1,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,56.0,,0,Transient,80.0,0,0
HB-100298,City Hotel,0,1,2024,October,43,25,2024-10-25,0,1,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,A,2,No Deposit,14.0,,0,Transient,123.33,0,0
HB-002638,Resort Hotel,1,148,2023,October,43,24,2023-10-24,0,1,1,0.0,0,BB,PRT,Groups,Direct,0,0,0,A,A,0,Non Refund,,,0,Transient,39.0,0,0
HB-068583,City Hotel,1,105,2025,May,21,19,2025-05-19,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,,,0,Transient,160.0,0,0
HB-055129,City Hotel,1,166,2024,August,32,5,2024-08-05,2,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.45,0,0
HB-092946,City Hotel,0,45,2024,November,48,28,2024-11-28,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,4,A,A,1,No Deposit,,40.0,0,Transient,67.0,1,0
HB-106414,City Hotel,0,1,2025,February,9,24,2025-02-24,0,1,2,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,98.0,0,0
HB-111316,City Hotel,0,144,2025,May,19,6,2025-05-06,2,1,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,52.0,,0,Transient-Party,90.0,0,1
HB-015470,Resort Hotel,0,17,2023,July,28,16,2023-07-16,0,3,3,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,E,1,No Deposit,,,0,Transient,139.0,0,1
HB-078881,City Hotel,0,17,2023,October,42,16,2023-10-16,0,2,2,0.0,0,BB,FRA,Offline TA/TO,TA/TO,0,0,0,A,F,0,No Deposit,20.0,,17,Transient-Party,48.0,0,0
HB-023646,Resort Hotel,0,5,2024,April,17,27,2024-04-27,0,3,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,0,No Deposit,,,0,Transient,86.0,1,0
HB-024979,Resort Hotel,0,150,2024,June,23,4,2024-06-04,2,5,2,0.0,0,BB,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,,0,Transient-Party,73.71,0,2
HB-096770,City Hotel,0,203,2024,September,36,5,2024-09-05,1,2,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,27.0,,0,Transient-Party,80.75,0,0
HB-089866,City Hotel,0,10,2024,May,20,15,2024-05-15,4,9,2,0.0,0,BB,BRA,Corporate,Corporate,0,0,0,A,D,4,No Deposit,,158.0,0,Transient,129.0,0,0
HB-054380,City Hotel,1,372,2024,July,28,14,2024-07-14,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,1.0,,0,Transient,62.0,0,0
HB-020281,Resort Hotel,0,18,2024,January,4,22,2024-01-22,0,1,2,0.0,0,HB,GBR,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,242.0,,0,Transient,88.0,0,1
HB-099368,City Hotel,0,181,2024,October,41,11,2024-10-11,0,2,1,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,2,No Deposit,234.0,,0,Transient-Party,250.0,0,0
HB-116490,City Hotel,0,164,2025,July,29,18,2025-07-18,0,3,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,107.1,0,1
HB-028605,Resort Hotel,0,3,2024,October,40,4,2024-10-04,0,3,2,2.0,0,BB,POL,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,,0,Transient,165.0,0,0
HB-076331,City Hotel,0,271,2023,July,28,15,2023-07-15,0,2,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,1.0,,0,Transient-Party,62.0,0,0
HB-070944,City Hotel,1,213,2025,June,26,26,2025-06-26,1,1,2,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,A,0,Non Refund,323.0,,0,Transient,115.0,0,0
HB-114510,City Hotel,0,141,2025,June,25,19,2025-06-19,1,3,2,0.0,0,SC,AUT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,99.0,0,0
HB-050519,City Hotel,1,120,2024,May,18,2,2024-05-02,1,3,2,0.0,0,SC,IRL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,,0,Transient,89.25,0,1
HB-048774,City Hotel,1,29,2024,March,13,30,2024-03-30,0,3,2,0.0,0,BB,IRN,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,,0,Transient,140.0,0,0
HB-004547,Resort Hotel,0,162,2024,March,12,24,2024-03-24,0,3,2,0.0,0,Undefined,PRT,Groups,TA/TO,0,0,0,A,A,0,No Deposit,,,0,Transient-Party,84.0,0,0
HB-077924,City Hotel,1,6,2023,October,40,4,2023-10-04,2,3,1,0.0,0,BB,PRT,Online TA,TA/TO,0,1,0,A,A,1,No Deposit,9.0,,0,Contract,131.4,0,1
HB-046974,City Hotel,0,47,2024,January,5,30,2024-01-30,2,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,11.0,,0,Transient,55.24,0,0
"""

ruta_archivo = Path("hotel booking TPI grupo L.csv")

ruta_archivo.write_text(contenido_csv, encoding="utf-8")

print(f"Archivo creado correctamente: {ruta_archivo.name}")

Archivo creado correctamente: hotel booking TPI grupo L.csv

In [4]:
df = pd.read_csv("hotel booking TPI grupo L.csv")
print ("El dataset fue cargado correctamente")

El dataset fue cargado correctamente

## 4. Vista Inicial

Visualizacion de las primeras filas del Dataset.

In [5]:
df.head()

,booking_id,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,arrival_date,stays_in_weekend_nights,...,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests
0,HB-050638,City Hotel,1,302,2024,May,18,5,2024-05-05,0,...,A,0,Non Refund,1.0,NaN,0,Transient,62.0,0,0
1,HB-042358,City Hotel,1,65,2023,September,36,5,2023-09-05,1,...,A,0,Non Refund,1.0,NaN,0,Transient,62.0,0,0
2,HB-113042,City Hotel,0,32,2025,May,22,30,2025-05-30,0,...,A,0,No Deposit,9.0,NaN,0,Transient,160.0,0,2
3,HB-020264,Resort Hotel,0,3,2024,February,8,25,2024-02-25,0,...,D,0,No Deposit,240.0,NaN,0,Transient,43.0,1,2
4,HB-017627,Resort Hotel,0,5,2023,October,41,10,2023-10-10,2,...,A,0,No Deposit,36.0,NaN,0,Transient,42.0,0,0

## 5. Estructura general

Cantidad de filas, cantidad de columnas y nombres de las variables

In [6]:
filas, columnas = df.shape
print("Filas: ", filas)
print("\nColumnas: ", columnas)

print("Variables")
print(df.columns.tolist())

Filas:  25000

Columnas:  32
Variables
['booking_id', 'hotel', 'is_canceled', 'lead_time', 'arrival_date_year', 'arrival_date_month', 'arrival_date_week_number', 'arrival_date_day_of_month', 'arrival_date', 'stays_in_weekend_nights', 'stays_in_week_nights', 'adults', 'children', 'babies', 'meal', 'country', 'market_segment', 'distribution_channel', 'is_repeated_guest', 'previous_cancellations', 'previous_bookings_not_canceled', 'reserved_room_type', 'assigned_room_type', 'booking_changes', 'deposit_type', 'agent', 'company', 'days_in_waiting_list', 'customer_type', 'adr', 'required_car_parking_spaces', 'total_of_special_requests']

### 6 Tipos de variables

  Clasificacion inicial de las variables numericas, categoricas y temporales

In [7]:
# Código de análisis
print("Tipos de datos")
print(df.dtypes)

Tipos de datos
booking_id                         object
hotel                              object
is_canceled                         int64
lead_time                           int64
arrival_date_year                   int64
arrival_date_month                 object
arrival_date_week_number            int64
arrival_date_day_of_month           int64
arrival_date                       object
stays_in_weekend_nights             int64
stays_in_week_nights                int64
adults                              int64
children                          float64
babies                              int64
meal                               object
country                            object
market_segment                     object
distribution_channel               object
is_repeated_guest                   int64
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                 object
assigned_room_type                 object
booking_changes                     int64
deposit_type                       object
agent                             float64
company                           float64
days_in_waiting_list                int64
customer_type                      object
adr                               float64
required_car_parking_spaces         int64
total_of_special_requests           int64
dtype: object

## 7. Caracterizacion descriptiva inicial

Exploracion basica de las variables mediante resumenes que permitan conocer sus valores, rangos o comportamientos generales, acompañados por observaciones escritas.

In [8]:
df.describe().round(2)

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
count,25000.00,25000.00,25000.00,25000.00,25000.00,25000.00,25000.00,25000.00,24999.0,25000.00,25000.00,25000.00,25000.00,25000.00,21578.00,1385.00,25000.00,25000.00,25000.00,25000.00
mean,0.37,104.10,2024.16,26.65,15.76,0.93,2.51,1.85,0.1,0.01,0.03,0.09,0.13,0.22,87.08,185.96,2.30,102.40,0.06,0.56
std,0.48,106.57,0.71,13.34,8.80,1.01,1.93,0.51,0.4,0.09,0.17,0.85,1.50,0.65,110.94,130.03,17.46,58.33,0.24,0.79
min,0.00,0.00,2023.00,1.00,1.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,1.00,9.00,0.00,-6.38,0.00,0.00
25%,0.00,18.00,2024.00,16.00,8.00,0.00,1.00,2.00,0.0,0.00,0.00,0.00,0.00,0.00,9.00,62.00,0.00,70.00,0.00,0.00
50%,0.00,70.00,2024.00,27.00,16.00,1.00,2.00,2.00,0.0,0.00,0.00,0.00,0.00,0.00,14.00,174.00,0.00,95.00,0.00,0.00
75%,1.00,161.00,2025.00,37.00,23.00,2.00,3.00,2.00,0.0,0.00,0.00,0.00,0.00,0.00,229.00,255.00,0.00,126.00,0.00,1.00
max,1.00,629.00,2025.00,52.00,31.00,16.00,40.00,20.00,3.0,2.00,1.00,26.00,70.00,21.00,531.00,543.00,391.00,5400.00,2.00,5.00

---

### 8. Primeras observaciones

Comentarios generales sobre la informacion descubierta hasta el momento.



*   En un primer analisis de la variable objetivo <b>is_canceled</b>, podemos decir que existe una proporcion considerable de reservas canceladas.
*   Los tiempos de reserva (<b>lead_time</b>) muestran un rango muy amplio, con valores minimos de 0 días hasta varios 629 dias. La desviacion estandar sera un punto de interes.
* Se detectaron variables con muchos valores nulos, apuntando directamente a <b>company</b> y <b>agent</b>.
* Se observa valores atipicos (outliers) en variables clave que requeriran tratamiento, como tarifas diarias <b>(adr)</b> con montos negativos o registros que indican hasta 20 adultos en una sola reserva.

##9. Consideraciones eticas iniciales
Reflexion breve sobre el uso responsable de los datos y los limites de las conclusiones que pueden obtenerse en la primera etapa.

Al trabajar con datos del sector hotelero, la prioridad debe ser proteger la privacidad de los huéspedes. Aunque la identidad en este dataset se mantiene en el anonimato y no contiene información de identificación directa, variables como la nacionalidad (country) o las peticiones especiales deben analizarse de manera objetiva, evitando interpretaciones que puedan llevar a una clasificación inadecuada de los huéspedes. Asimismo, es importante establecer los límites de esta etapa: dado que los datos aún presentan ruido, valores nulos y valores atípicos, no resulta ético ni profesional utilizarlos para fundamentar decisiones de negocio definitivas sin realizar previamente un proceso de limpieza, validación y control de calidad.